ArmNN: src/backends/backendsCommon/test/layerTests/ActivationTestImpl.hpp File Reference
ActivationTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > SimpleSigmoidTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SimpleSigmoidUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SimpleSigmoidInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > TanhTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > TanhUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > TanhInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > ConstantLinearActivationTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > ConstantLinearActivationUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > ConstantLinearActivationInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > ReLuTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > ReLuUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > ReLuInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > BoundedReLuUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, float upperBound)
LayerTestResult< uint8_t, 4 > BoundedReLuUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, float upperBound, float lowerBound)
LayerTestResult< int16_t, 4 > BoundedReLuInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > BoundedReLuUpperAndLowerBoundTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > BoundedReLuUint8UpperAndLowerBoundTest (armnn::IWorkloadFactory &workloadFactor, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManagery, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > BoundedReLuUpperBoundOnlyTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > BoundedReLuUint8UpperBoundOnlyTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > CompareBoundedReLuTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, float upperBound, float lowerBound)
LayerTestResult< float, 4 > SoftReLuTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SoftReLuUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SoftReLuInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > LeakyReLuTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LeakyReLuUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > LeakyReLuInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > EluTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EluUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > EluInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > AbsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > AbsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > AbsInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SqrtTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > SqrtNNTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SqrtUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SqrtInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SquareTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SquareUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SquareInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > HardSwishTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > HardSwishUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > HardSwishInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > CompareActivationTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::ActivationFunction f, unsigned int batchSize)
LayerTestResult< uint8_t, 4 > CompareActivationUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::ActivationFunction f)
LayerTestResult< int16_t, 4 > CompareActivationInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::ActivationFunction f)
Function Documentation
AbsInt16Test()
LayerTestResult<int16_t, 4> AbsInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 836 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AbsTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
AbsTest()
LayerTestResult<float, 4> AbsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 820 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AbsTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
AbsUint8Test()
LayerTestResult<uint8_t, 4> AbsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 828 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AbsTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.0625f, 64);
 }
BoundedReLuInt16Test()
LayerTestResult<int16_t, 4> BoundedReLuInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 648 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ReLuTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
BoundedReLuUint8Test() [1/2]
LayerTestResult<uint8_t, 4> BoundedReLuUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, float upperBound)
BoundedReLuUint8Test() [2/2]
LayerTestResult<uint8_t, 4> BoundedReLuUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, float upperBound, float lowerBound)
BoundedReLuUint8UpperAndLowerBoundTest()
LayerTestResult<uint8_t, 4> BoundedReLuUint8UpperAndLowerBoundTest (armnn::IWorkloadFactory & workloadFactor, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManagery, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 188 of file ActivationTestImpl.cpp.
References armnn::Activation, CopyDataFromITensorHandle(), CopyDataToITensorHandle(), ITensorHandleFactory::CreateTensorHandle(), IWorkloadFactory::CreateWorkload(), armnn::Float32, TensorInfo::GetNumElements(), armnn::IgnoreUnused(), and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by TEST_SUITE().
 {
     unsigned int inputWidth     = 3u;
     unsigned int inputHeight    = 2u;
     unsigned int inputChannels  = 1u;
     unsigned int inputBatchSize = 1;
     std::vector<uint8_t> input = std::vector<uint8_t>{
          51, 230, 28,
         251,   8, 92
     };
     // Calculated manually.
     std::vector<uint8_t> output = std::vector<uint8_t>{
          51, 192, 32,
         192,  32, 92
     };
     int32_t inputOffset = 112;
     float inputScale    = 0.0125f;
     return BoundedReLuTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -1.0f,
         inputScale, inputOffset, inputScale, inputOffset, // Input/output scale & offset same.
         input, output, inputWidth, inputHeight, inputChannels, inputBatchSize);
 }
BoundedReLuUint8UpperBoundOnlyTest()
LayerTestResult<uint8_t, 4> BoundedReLuUint8UpperBoundOnlyTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 156 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     unsigned int inputWidth     = 3u;
     unsigned int inputHeight    = 2u;
     unsigned int inputChannels  = 1u;
     unsigned int inputBatchSize = 1;
     std::vector<uint8_t> input = std::vector<uint8_t>{
          51, 124, 28,
         251,   8, 92
     };
     // Calculated manually.
     std::vector<uint8_t> output = std::vector<uint8_t>{
           0, 122,  0,
         255,   0, 58
     };
     float inputScale     = 12.0f / 255.0f;
     int32_t inputOffset  = 63;
     float outputScale    = 6.0f / 255.0f;
     int32_t outputOffset = 0;
     return BoundedReLuTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 6.0f, 0.0f,
         inputScale, inputOffset, outputScale, outputOffset,
         input, output, inputWidth, inputHeight, inputChannels, inputBatchSize);
 }
BoundedReLuUpperAndLowerBoundTest()
LayerTestResult<float, 4> BoundedReLuUpperAndLowerBoundTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 92 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     unsigned int inputWidth = 4u;
     unsigned int inputHeight = 5u;
     unsigned int inputChannels = 1u;
     unsigned int inputBatchSize = 1;
     std::vector<float> input = std::vector<float>{
       -2.0f,       0.1f,     0.5f,     1.25f,
      0.786f,    0.9875f,    -1.5f,    0.384f,
     1.0001f,       3.5f,     7.5f,    0.896f,
      2.126f,       2.0f,     0.3f,     0.15f,
      0.999f,       1.2f,    0.89f,      6.1f,
     };
     // Calculated manually.
     std::vector<float> output = std::vector<float>{
       -1.0f,       0.1f,     0.5f,      1.0f,
      0.786f,    0.9875f,    -1.0f,    0.384f,
        1.0f,       1.0f,     1.0f,    0.896f,
        1.0f,       1.0f,     0.3f,     0.15f,
      0.999f,       1.0f,    0.89f,      1.0f,
     };
     return BoundedReLuTestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -1.0f, 1.0f, 0, 1.0f, 0, input, output,
         inputWidth, inputHeight, inputChannels, inputBatchSize);
 }
BoundedReLuUpperBoundOnlyTest()
LayerTestResult<float, 4> BoundedReLuUpperBoundOnlyTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 124 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     unsigned int inputWidth = 4u;
     unsigned int inputHeight = 5u;
     unsigned int inputChannels = 1u;
     unsigned int inputBatchSize = 1;
     std::vector<float> input = std::vector<float>{
       -1.0f,       0.1f,     0.5f,      6.25f,
      0.786f,    5.9875f,    -0.5f,     0.384f,
     6.0001f,       3.5f,     7.5f,     0.896f,
      2.126f,      12.0f,     0.3f,      0.15f,
      0.999f,       1.2f,    0.89f,       6.1f,
     };
     // Calculated manually.
     std::vector<float> output = std::vector<float>{
        0.0f,       0.1f,     0.5f,       6.0f,
      0.786f,    5.9875f,     0.0f,     0.384f,
        6.0f,       3.5f,     6.0f,     0.896f,
      2.126f,       6.0f,     0.3f,      0.15f,
      0.999f,       1.2f,    0.89f,       6.0f,
     };
     return BoundedReLuTestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 6.0f, 0.0f, 1.0f, 0, 1.0f, 0, input, output,
         inputWidth, inputHeight, inputChannels, inputBatchSize);
 }
CompareActivationInt16Test()
LayerTestResult<int16_t, 4> CompareActivationInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::ActivationFunction f)
Definition at line 1341 of file ActivationTestImpl.cpp.
 {
     return CompareActivationTestImpl<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory,
             refTensorHandleFactory, f, 5, 0.1f, 0);
 }
CompareActivationTest()
LayerTestResult<float, 4> CompareActivationTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::ActivationFunction f, unsigned int batchSize)
Definition at line 1314 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CompareActivationTestImpl<armnn::DataType::Float32>(
         workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory,
         refTensorHandleFactory, f, batchSize);
 }
CompareActivationUint8Test()
LayerTestResult<uint8_t, 4> CompareActivationUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::ActivationFunction f)
Definition at line 1328 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CompareActivationTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, refWorkloadFactory,
         tensorHandleFactory, refTensorHandleFactory, f, 5, 0.1f, 50);
 }
CompareBoundedReLuTest()
LayerTestResult<float, 4> CompareBoundedReLuTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, float upperBound, float lowerBound)
Definition at line 290 of file ActivationTestImpl.cpp.
References armnn::BoundedReLu, ActivationDescriptor::m_A, LayerTestResult< T, n >::m_ActualData, ActivationDescriptor::m_B, LayerTestResult< T, n >::m_ExpectedData, and ActivationDescriptor::m_Function.
Referenced by TEST_SUITE().
 {
     LayerTestResult<float, 4> result(BoundedReLuRandomInputTestTraits::GetOutputTensorInfo());
     armnn::ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = armnn::ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = upperBound;
     activationDescriptor.m_B = lowerBound;
     result.m_ActualData = BoundedReLuRandomInputTest(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, upperBound, activationDescriptor);
     result.m_ExpectedData = BoundedReLuRandomInputTest(
         refWorkloadFactory, nullptr, refTensorHandleFactory, 0.0f, upperBound, activationDescriptor);
     return result;
 }
ConstantLinearActivationInt16Test()
LayerTestResult<int16_t, 4> ConstantLinearActivationInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 398 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ConstantLinearActivationTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
ConstantLinearActivationTest()
LayerTestResult<float, 4> ConstantLinearActivationTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 379 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ConstantLinearActivationTestCommon<armnn::DataType::Float32>(workloadFactory,
                                                                         memoryManager,
                                                                         tensorHandleFactory);
 }
ConstantLinearActivationUint8Test()
LayerTestResult<uint8_t, 4> ConstantLinearActivationUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 389 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ConstantLinearActivationTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 4.0f, 3);
 }
EluInt16Test()
LayerTestResult<int16_t, 4> EluInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1142 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return EluTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
EluTest()
LayerTestResult<float, 4> EluTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1126 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return EluTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
EluUint8Test()
LayerTestResult<uint8_t, 4> EluUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1134 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return EluTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 64);
 }
HardSwishInt16Test()
LayerTestResult<int16_t, 4> HardSwishInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1211 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return HardSwishTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
HardSwishTest()
LayerTestResult<float, 4> HardSwishTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1194 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return HardSwishTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
HardSwishUint8Test()
LayerTestResult<uint8_t, 4> HardSwishUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1202 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return HardSwishTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager,
                                                           tensorHandleFactory, 0.1f, 64);
 }
LeakyReLuInt16Test()
LayerTestResult<int16_t, 4> LeakyReLuInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 775 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LeakyReLuTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
LeakyReLuTest()
LayerTestResult<float, 4> LeakyReLuTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 758 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LeakyReLuTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
LeakyReLuUint8Test()
LayerTestResult<uint8_t, 4> LeakyReLuUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 766 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LeakyReLuTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager,
                                                           tensorHandleFactory, 0.0625f, 64);
 }
ReLuInt16Test()
LayerTestResult<int16_t, 4> ReLuInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 584 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ReLuTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
ReLuTest()
LayerTestResult<float, 4> ReLuTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 601 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ReLuTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
ReLuUint8Test()
LayerTestResult<uint8_t, 4> ReLuUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 593 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ReLuTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SimpleSigmoidInt16Test()
LayerTestResult<int16_t, 4> SimpleSigmoidInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 538 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleSigmoidTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager,
                                                               tensorHandleFactory, 0.1f, 0);
 }
SimpleSigmoidTest()
LayerTestResult<float, 4> SimpleSigmoidTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 520 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleSigmoidTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager,
                                                             tensorHandleFactory, 0.0f, 0);
 }
SimpleSigmoidUint8Test()
LayerTestResult<uint8_t, 4> SimpleSigmoidUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 529 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleSigmoidTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager,
                                                               tensorHandleFactory, 0.1f, 50);
 }
SoftReLuInt16Test()
LayerTestResult<int16_t, 4> SoftReLuInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 712 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SoftReLuTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SoftReLuTest()
LayerTestResult<float, 4> SoftReLuTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 695 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SoftReLuTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SoftReLuUint8Test()
LayerTestResult<uint8_t, 4> SoftReLuUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 703 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SoftReLuTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager,
                                                          tensorHandleFactory, 0.0625f, 64);
 }
SqrtInt16Test()
LayerTestResult<int16_t, 4> SqrtInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 953 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SqrtTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SqrtNNTest()
LayerTestResult<float, 5> SqrtNNTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 844 of file ActivationTestImpl.cpp.
References armnn::Activation, CopyDataFromITensorHandle(), CopyDataToITensorHandle(), ITensorHandleFactory::CreateTensorHandle(), IWorkloadFactory::CreateWorkload(), armnn::Float32, armnn::IgnoreUnused(), ActivationDescriptor::m_Function, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::Sqrt.
Referenced by TEST_SUITE().
 {
     IgnoreUnused(memoryManager);
     const int inputDataSize = 120;
     std::vector<float> inputData(inputDataSize);
     for (unsigned int i = 0u; i < inputDataSize; ++i)
     {
         inputData[i] = static_cast<float>(i) / 10;
     }
     auto f = [](float value)
     {
         return std::sqrt(value);
     };
     std::vector<float> expectedOutput(inputDataSize);
     std::transform(inputData.begin(), inputData.end(), expectedOutput.begin(), f);
     armnn::TensorInfo inputTensorInfo(
         { 1u, 2u, 3u, 4u, 5u }, armnn::DataType::Float32);
     armnn::TensorInfo outputTensorInfo(
         { 1u, 2u, 3u, 4u, 5u }, armnn::DataType::Float32);
     std::vector<float> actualOutput(outputTensorInfo.GetNumElements());
     std::unique_ptr<armnn::ITensorHandle> inputHandle  = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::ActivationQueueDescriptor descriptor;
     armnn::WorkloadInfo workloadInfo;
     AddInputToWorkload(descriptor, workloadInfo, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, workloadInfo, outputTensorInfo, outputHandle.get());
     descriptor.m_Parameters.m_Function = armnn::ActivationFunction::Sqrt;
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateWorkload(armnn::LayerType::Activation,
                                                                                 descriptor, workloadInfo);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), inputData.data());
     workload->Execute();
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     return LayerTestResult<float, 5>(actualOutput,
                                      expectedOutput,
                                      outputHandle->GetShape(),
                                      outputTensorInfo.GetShape());
 };
SqrtTest()
LayerTestResult<float, 4> SqrtTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 937 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SqrtTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SqrtUint8Test()
LayerTestResult<uint8_t, 4> SqrtUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 945 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SqrtTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.0625f, 64);
 }
SquareInt16Test()
LayerTestResult<int16_t, 4> SquareInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1015 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SquareTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SquareTest()
LayerTestResult<float, 4> SquareTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 998 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SquareTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
SquareUint8Test()
LayerTestResult<uint8_t, 4> SquareUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1006 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SquareTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager,
                                                       tensorHandleFactory, 0.0625f, 64);
 }
TanhInt16Test()
LayerTestResult<int16_t, 4> TanhInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1078 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return TanhTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
TanhTest()
LayerTestResult<float, 4> TanhTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1062 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return TanhTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 0);
 }
TanhUint8Test()
LayerTestResult<uint8_t, 4> TanhUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1070 of file ActivationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return TanhTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 64);
 }