ArmNN: src/backends/backendsCommon/test/layerTests/Conv2dTestImpl.hpp File Reference
Conv2dTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <ResolveType.hpp>
#include <armnn/Types.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > Convolution2d3x3Dilation3x3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > Convolution2d2x3x3Dilation3x3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > SimpleConvolution2d3x5Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > SimpleConvolution2d3x3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > SimpleConvolution2d3x3Stride2x2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > SimpleConvolution2d3x3NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled)
LayerTestResult< uint8_t, 4 > SimpleConvolution2d3x5Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > SimpleConvolution2d3x3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > SimpleConvolution2d3x5QSymm16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > SimpleConvolution2d3x3QSymm16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, armnn::DataLayout layout)
LayerTestResult< float, 4 > Convolution2dAsymmetricPaddingTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, armnn::DataLayout layout)
LayerTestResult< float, 4 > Convolution1dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled)
LayerTestResult< uint8_t, 4 > Convolution1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled)
LayerTestResult< float, 4 > CompareConvolution2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory)
LayerTestResult< uint8_t, 4 > Convolution2dPerAxisQuantTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > Convolution2d3x3Stride2x2BFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout &dataLayout)
LayerTestResult< float, 4 > Convolution2d3x3Stride2x2BFloat16SmallValueTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout &dataLayout)
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > DepthwiseConvolution2d3x3Dilation3x3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > DepthwiseConvolution2d2x3x3Dilation3x3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > DepthwiseConvolution2dMult4Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
template<armnn::DataType ArmnnType, armnn::DataType ArmnnBType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > DepthwiseConvolution2dMult2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
template<typename T >
LayerTestResult< T, 4 > CompareDepthwiseConvolution2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > DepthwiseConvolution2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > DepthwiseConvolution2dDepthNhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled)
LayerTestResult< float, 4 > DepthwiseConvolution2dDepthMul1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > DepthwiseConvolution2dDepthMul64Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > DepthwiseConvolution2dAsymmetricTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< float, 4 > SimpleDepthwiseConvolution2d3x3Dilation3x3NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > DepthwiseConvolution2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > DepthwiseConvolution2dDepthMul1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > DepthwiseConvolution2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > DepthwiseConvolution2dDepthMul1Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > DepthwiseConvolution2dPerAxisQuantTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > CompareDepthwiseConvolution2dFloatTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > CompareDepthwiseConvolution2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, const armnn::DataLayout layout)
Function Documentation
CompareConvolution2dTest()
LayerTestResult<float, 4> CompareConvolution2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory)
Definition at line 3747 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CompareConvolution2dTestImpl<armnn::DataType::Float32>(
             workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory);
 }
CompareDepthwiseConvolution2dFloatTest()
LayerTestResult<float, 4> CompareDepthwiseConvolution2dFloatTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, const armnn::DataLayout layout)
Definition at line 4039 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CompareDepthwiseConvolution2dTestImpl<armnn::DataType::Float32>(
         workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, layout);
 }
CompareDepthwiseConvolution2dTest()
LayerTestResult<T, 4> CompareDepthwiseConvolution2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, const armnn::DataLayout layout)
CompareDepthwiseConvolution2dUint8Test()
LayerTestResult<uint8_t, 4> CompareDepthwiseConvolution2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, const armnn::DataLayout layout)
Definition at line 4051 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CompareDepthwiseConvolution2dTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, layout);
 }
Convolution1dTest()
LayerTestResult<float, 4> Convolution1dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled)
Definition at line 3611 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution1dTestImpl<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, biasEnabled);
 }
Convolution1dUint8Test()
LayerTestResult<uint8_t, 4> Convolution1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled)
Definition at line 3621 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution1dTestImpl<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 128, biasEnabled);
 }
Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test()
LayerTestResult<T, 4> Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 1300 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     armnn::TensorInfo inputTensorInfo({ 1, 1, 10, 10 }, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
     {
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1
     };
     armnn::TensorInfo kernelTensorInfo({ 1, 1, 2, 2 }, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
     {
         1, 2,
         3, 4
     };
     // Since the dilation rate is 2 this will dilate the kernel to be like 3x3: d(K-1)+1 --> 2 x (2-1) + 1 = 3,
     // therefore the output will be 4x4: (I  K + 2P)/S +1 => trunc ( (10 - 3 + 2x2 ) / 3 + 1 )
     // where, dilation size = d = 2; kernel size = K = 2; input size = I = 10; padding size = P = 2; stride = S = 3
     armnn::TensorInfo outputTensorInfo({ 1, 1, 4, 4}, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
     {
         4,  7,  7, 3,
         6, 10, 10, 4,
         6, 10, 10, 4,
         2,  3,  3, 1
     };
     uint32_t padLeft = 1;
     uint32_t padTop = 1;
     uint32_t padRight = 1;
     uint32_t padBottom = 1;
     return Convolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             2,
             2,
             layout,
             padLeft,
             padTop,
             padRight,
             padBottom,
             3,
             3,
             biasEnabled
             );
 }
Convolution2d2x3x3Dilation3x3Test()
LayerTestResult<T, 4> Convolution2d2x3x3Dilation3x3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 1227 of file Conv2dTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo({ 1, 2, 10, 10 }, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
     {
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0
     };
     armnn::TensorInfo kernelTensorInfo({ 1, 2, 3, 3 }, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         1, 2, 3,
         4, 5, 6,
         7, 8, 9
     };
     // Since the dilation rate is 3 this will dilate the kernel to be like 7x7,
     // therefore the output will be 4x4: (IK+2P)/S +1 => (10-7 +0)/1 +1
     armnn::TensorInfo outputTensorInfo({ 1, 1, 4, 4 }, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
     {
         12., 10., 10., 10.,
         12., 10., 10., 10.,
         12., 10., 10., 10.,
          6.,  4.,  4.,  4.
     };
     return Convolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             3,
             3,
             layout,
             biasEnabled);
 }
Convolution2d3x3Dilation3x3Test()
LayerTestResult<T, 4> Convolution2d3x3Dilation3x3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 1169 of file Conv2dTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo({ 1, 1, 10, 10 }, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
     {
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0
     };
     armnn::TensorInfo kernelTensorInfo({ 1, 1, 3, 3}, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9
     };
     // Since the dilation rate is 3 this will dilate the kernel to be like 7x7,
     // therefore the output will be 4x4: (IK+2P)/S +1 => (10-7 +0)/1 +1
     armnn::TensorInfo outputTensorInfo({ 1, 1, 4, 4}, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
     {
         6., 5., 5., 5.,
         6., 5., 5., 5.,
         6., 5., 5., 5.,
         3., 2., 2., 2.
     };
     return Convolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             3,
             3,
             layout,
             biasEnabled);
 }
Convolution2d3x3Stride2x2BFloat16SmallValueTest()
LayerTestResult<float, 4> Convolution2d3x3Stride2x2BFloat16SmallValueTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout & dataLayout)
Definition at line 1602 of file Conv2dTestImpl.cpp.
References armnn::BFloat16, armnn::Float32, armnn::IgnoreUnused(), and SimpleConvolution2dNhwcTestImpl().
Referenced by TEST_SUITE().
 {
     // BFloat16 input and weight, Float32 output
     armnn::IgnoreUnused(biasEnabled);
     // Input is a single-batch, 1 channel, 5x5 image.
     armnn::TensorInfo inputDesc({1, 5, 5, 1}, armnn::DataType::BFloat16);
     std::vector<armnn::BFloat16> inputValues = armnnUtils::QuantizedVector<armnn::BFloat16>(
         {
             0.0367984f,  // 0.0368652
             0.0380895f,  // 0.0380859
             0.0420157f,  // 0.0419922
             0.0675631f,  // 0.0673828
             0.0938920f,  // 0.09375
             0.0476106f,  // 0.0476074
             0.1035490f,  // 0.103516
             0.1260370f,  // 0.125977
             0.0461647f,  // 0.0461426
             0.0883828f,  // 0.0883789
             0.1159540f,  // 0.115723
             0.0498519f,  // 0.0498047
             0.0104630f,  // 0.010437
             0.0154114f,  // 0.0154419
             0.00137681f, // 0.00137329
             0.0344238f,  // 0.0344616
             0.0356445f,  // 0.0355693
             0.0495605f,  // 0.0495018
             0.0683594f,  // 0.0683308
             0.0991211f,  // 0.0988837
             0.0461426f,  // 0.0461838
             0.0996094f,  // 0.0997546
             0.1269530f,  // 0.127099
             0.0393066f,  // 0.0392791
             0.103516f    // 0.103641
        },
         1.0f, 0);
     // Use a 3x3 kernel.
     armnn::TensorInfo kernelDesc({1, 3, 3, 1}, armnn::DataType::BFloat16);
     std::vector<armnn::BFloat16> kernelValues = armnnUtils::QuantizedVector<armnn::BFloat16>(
         {
             -0.126184f, // -0.125977
             -0.150468f, // -0.150391
             -0.101412f, // -0.101562
             -0.0586369f,// -0.0585938
             -0.0865864f,// -0.0864258
             -0.0435089f,// -0.043457
             0.0347555f, // 0.034668
             0.0323111f, // 0.0322266
             0.0385381f  // 0.0385742
          },
         1.0f, 0);
     // Expected output is a single-batch, 1 channel, 3x3 image.
     armnn::TensorInfo outputDesc({1, 3, 3, 1}, armnn::DataType::Float32);
     // Expected output (with results if calculated as FP32 in the comments)
     const std::vector<float> outputData =
         {
              0.000686645508f, // 0.000685
              0.000640869141f, // 0.000639
             -0.00759887695f,  // -0.007631
             -0.02734375f,     // -0.027388
             -0.0356445312f,   // -0.035737
             -0.0145874023f,   // -0.014568
             -0.0170898438f,   // -0.017124
             -0.0373535156f,   // -0.037431
             -0.0346679688f    // -0.034808
         };
     uint32_t padLeft = 1;
     uint32_t padTop = 1;
     uint32_t padRight = 1;
     uint32_t padBottom = 1;
     uint32_t strideX  = 2;
     uint32_t strideY  = 2;
     return SimpleConvolution2dNhwcTestImpl
         <armnn::DataType::BFloat16, armnn::DataType::Float32, armnn::BFloat16, float, armnn::DataType::Float32, float>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputValues,
         kernelValues,
         std::vector<float>(),
         outputData,
         inputDesc.GetShape(),
         kernelDesc.GetShape(),
         outputDesc.GetShape(),
         dataLayout,
         1.0f,
         0,
         padLeft,
         padTop,
         padRight,
         padBottom,
         strideX,
         strideY);
 }
Convolution2d3x3Stride2x2BFloat16Test()
LayerTestResult<float, 4> Convolution2d3x3Stride2x2BFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout & dataLayout)
Definition at line 1495 of file Conv2dTestImpl.cpp.
References armnn::BFloat16, armnn::Float32, armnn::IgnoreUnused(), and SimpleConvolution2dNhwcTestImpl().
Referenced by TEST_SUITE().
 {
     // BFloat16 input and weight, Float32 output
     armnn::IgnoreUnused(biasEnabled);
     // Input is a single-batch, 1 channel, 5x5 image.
     armnn::TensorInfo inputDesc({ 1, 5, 5, 1 }, armnn::DataType::BFloat16);
     std::vector<armnn::BFloat16> inputValues = armnnUtils::QuantizedVector<armnn::BFloat16>(
         {
             10.0367984f,  // 10.0625
              2.0380895f,  // 2.03125
             15.0420157f,  // 15.0625
             22.0675631f,  // 22.125
              8.0938920f,  // 8.125
              5.0476106f,  // 5.0625
             80.1035490f,  // 80
            100.1260370f,  // 100
             55.0461647f,  // 55
            120.0883828f,  // 120
              9.1159540f,  // 9.125
             90.0498519f,  // 90
            200.0104630f,  // 200
             30.0154114f,  // 30
             75.00137681f, // 75
             30.0344238f,  // 30
             25.0356445f,  // 25
            130.0495605f,  // 130
             60.0683594f,  // 60
             35.0991211f,  // 35
              8.0461426f,  // 8.0625
             12.0996094f,  // 12.125
             98.1269530f,  // 98
            125.0393066f,  // 125
              5.103516f    // 5.0937
        },
         1.0f, 0);
     // Use a 3x3 kernel.
     armnn::TensorInfo kernelDesc({1, 3, 3, 1}, armnn::DataType::BFloat16);
     std::vector<armnn::BFloat16> kernelValues = armnnUtils::QuantizedVector<armnn::BFloat16>(
         {
             -0.126184f, // -0.125977
             -0.150468f, // -0.150391
             -0.101412f, // -0.101562
             -0.0586369f,// -0.0585938
             -0.0865864f,// -0.0864258
             -0.0435089f,// -0.043457
             0.0347555f, // 0.034668
             0.0323111f, // 0.0322266
             0.0385381f  // 0.0385742
          },
         1.0f, 0);
     // Expected output is a single-batch, 1 channel, 3x3 image.
     armnn::TensorInfo outputDesc({ 1, 3, 3, 1 }, armnn::DataType::Float32);
     // Expected output (with results if calculated as FP32 in the comments)
     const std::vector<float> outputData =
         {
             2.296875f, //  2.29240716
             5.75f,     //  5.75851926
             3.78125f,  //  3.79855026
             -11.625f,  // -11.65498118
             -47.25f,   // -47.27316893
             -30.0f,    // -30.04771684
             -8.25f,    //  -8.28126168
             -43.5f,    // -43.46531337
             -20.625f   // -20.63477281
         };
     uint32_t padLeft = 1;
     uint32_t padTop = 1;
     uint32_t padRight = 1;
     uint32_t padBottom = 1;
     uint32_t strideX  = 2;
     uint32_t strideY  = 2;
     return SimpleConvolution2dNhwcTestImpl
         <armnn::DataType::BFloat16, armnn::DataType::Float32, armnn::BFloat16, float, armnn::DataType::Float32, float>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputValues,
         kernelValues,
         std::vector<float>(),
         outputData,
         inputDesc.GetShape(),
         kernelDesc.GetShape(),
         outputDesc.GetShape(),
         dataLayout,
         1.0f,
         0,
         padLeft,
         padTop,
         padRight,
         padBottom,
         strideX,
         strideY);
 }
Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTest()
LayerTestResult<float, 4> Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, armnn::DataLayout layout)
Definition at line 3600 of file Conv2dTestImpl.cpp.
References Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTestCommon(), and armnn::Float32.
Referenced by TEST_SUITE().
 {
     return Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTestCommon
             <armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, layout, 0.0f, 0);
 }
Convolution2dAsymmetricPaddingTest()
LayerTestResult<float, 4> Convolution2dAsymmetricPaddingTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, armnn::DataLayout layout)
Definition at line 3590 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2dAsymmetricPaddingTestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, layout, 0.0f, 0);
 }
Convolution2dPerAxisQuantTest()
LayerTestResult<uint8_t, 4> Convolution2dPerAxisQuantTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 3631 of file Conv2dTestImpl.cpp.
References AllocateAndCopyDataToITensorHandle(), armnn::Convolution2d, CopyDataFromITensorHandle(), CopyDataToITensorHandle(), ITensorHandleFactory::CreateTensorHandle(), IWorkloadFactory::CreateWorkload(), QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, Convolution2dDescriptor::m_StrideX, armnn::NCHW, and PermuteTensorNhwcToNchw().
Referenced by TEST_SUITE().
 {
     using namespace armnn;
     const DataType inputType  = DataType::QAsymmU8;
     const DataType kernelType = DataType::QSymmS8;
     const DataType biasType   = DataType::Signed32;
     TensorInfo inputInfo ({ 1, 3, 1, 2 }, inputType, 0.5f, 128);
     TensorInfo outputInfo({ 1, 3, 1, 3 }, inputType, 1.0f, 128);
     const std::vector<float> quantScales{ 0.5f, 0.75f, 1.0f };
     constexpr unsigned int quantDimension = 0;
     TensorInfo kernelInfo({ 3, 1, 1, 2 }, kernelType, quantScales, quantDimension);
     const std::vector<float> biasQuantScales{ 0.25f, 0.375f, 0.5f };
     TensorInfo biasInfo({ 3 }, biasType, biasQuantScales, quantDimension);
     std::vector<uint8_t> inputData =
     {
         138, 108, 138, 108, 138, 108
     };
     std::vector<int8_t> kernelData =
     {
         1, 2, 1, 2, 1, 2
     };
     std::vector<int32_t> biasData =
     {
         4, 4, 4
     };
     std::vector<uint8_t> expectedOutputData =
     {
         121, 118, 115, 121, 118, 115, 121, 118, 115
     };
     if (layout == DataLayout::NCHW)
     {
         PermuteTensorNhwcToNchw(inputInfo, inputData);
         PermuteTensorNhwcToNchw(kernelInfo, kernelData);
         PermuteTensorNhwcToNchw(outputInfo, expectedOutputData);
     }
     std::vector<uint8_t> actualOutput(outputInfo.GetNumElements());
     Convolution2dDescriptor descriptor;
     descriptor.m_StrideX     = 1;
     descriptor.m_StrideY     = 1;
     descriptor.m_PadLeft     = 0;
     descriptor.m_PadRight    = 0;
     descriptor.m_PadTop      = 0;
     descriptor.m_PadBottom   = 0;
     descriptor.m_BiasEnabled = true;
     descriptor.m_DataLayout  = layout;
     std::unique_ptr<ITensorHandle> inputHandle  = tensorHandleFactory.CreateTensorHandle(inputInfo);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputInfo);
     std::unique_ptr<armnn::ITensorHandle> weightsHandle = tensorHandleFactory.CreateTensorHandle(kernelInfo);
     std::unique_ptr<armnn::ITensorHandle> biasHandle = nullptr;
     WorkloadInfo workloadInfo;
     ScopedTensorHandle weightTensor(kernelInfo);
     ScopedTensorHandle biasTensor(biasInfo);
     AllocateAndCopyDataToITensorHandle(&weightTensor, kernelData.data());
     AllocateAndCopyDataToITensorHandle(&biasTensor, biasData.data());
     Convolution2dQueueDescriptor queueDescriptor;
     queueDescriptor.m_Parameters = descriptor;
     queueDescriptor.m_Weight     = &weightTensor;
     queueDescriptor.m_Bias       = &biasTensor;
     AddInputToWorkload(queueDescriptor, workloadInfo, inputInfo, inputHandle.get());
     AddInputToWorkload(queueDescriptor, workloadInfo, kernelInfo, weightsHandle.get());
     if (descriptor.m_BiasEnabled)
     {
         biasHandle = tensorHandleFactory.CreateTensorHandle(biasInfo);
         AddInputToWorkload(queueDescriptor, workloadInfo, biasInfo, biasHandle.get());
     }
     AddOutputToWorkload(queueDescriptor, workloadInfo, outputInfo, outputHandle.get());
     std::unique_ptr<IWorkload> workload= workloadFactory.CreateWorkload(armnn::LayerType::Convolution2d,
                                                                         queueDescriptor,
                                                                         workloadInfo);
     inputHandle->Allocate();
     outputHandle->Allocate();
     weightsHandle->Allocate();
     if (descriptor.m_BiasEnabled)
     {
         biasHandle->Allocate();
         CopyDataToITensorHandle(biasHandle.get(), biasData.data());
     }
     CopyDataToITensorHandle(inputHandle.get(), inputData.data());
     CopyDataToITensorHandle(weightsHandle.get(), kernelData.data());
     ExecuteWorkload(*workload, memoryManager);
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     return LayerTestResult<uint8_t, 4>(actualOutput,
                                        expectedOutputData,
                                        outputHandle->GetShape(),
                                        outputInfo.GetShape());
 }
DepthwiseConvolution2d2x3x3Dilation3x3Test()
LayerTestResult<T, 4> DepthwiseConvolution2d2x3x3Dilation3x3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 2879 of file Conv2dTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo({1, 2, 10, 10}, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
             {
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0
             };
     armnn::TensorInfo kernelTensorInfo({ 1, 3, 3, 2}, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
             {
                     1, 2, 3,
                     4, 5, 6,
                     7, 8, 9,
                     1, 2, 3,
                     4, 5, 6,
                     7, 8, 9
             };
     // Since the dilation rate is 3 this will dilate the kernel to be like 7x7,
     // therefore the output will be 2x4x4: (IK+2P)/S +1 => (10-7 +0)/1 +1
     armnn::TensorInfo outputTensorInfo({ 1, 2, 4, 4}, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
             {
                     2, 9, 9, 9, 2, 9, 9, 9, 2, 9, 9, 9, 5, 3, 3, 3, 3,
                     1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 6, 4, 4, 4
             };
     return DepthwiseConvolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             3,
             3,
             layout,
             biasEnabled);
 }
DepthwiseConvolution2d3x3Dilation3x3Test()
LayerTestResult<T, 4> DepthwiseConvolution2d3x3Dilation3x3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 2821 of file Conv2dTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo({1, 1, 10, 10}, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
             {
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0
             };
     armnn::TensorInfo kernelTensorInfo({ 1, 3, 3, 1}, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
             {
                     1, 2, 3,
                     4, 5, 6,
                     7, 8, 9
             };
     // Since the dilation rate is 3 this will dilate the kernel to be like 7x7,
     // therefore the output will be 4x4: (IK+2P)/S +1 => (10-7 +0)/1 +1
     armnn::TensorInfo outputTensorInfo({ 1, 1, 4, 4}, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
             {
                     6., 5., 5., 5.,
                     6., 5., 5., 5.,
                     6., 5., 5., 5.,
                     3., 2., 2., 2.
             };
     return DepthwiseConvolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             3,
             3,
             layout,
             biasEnabled);
 }
DepthwiseConvolution2dAsymmetricTest()
LayerTestResult<float, 4> DepthwiseConvolution2dAsymmetricTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3833 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dAsymmetricTestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, biasEnabled, layout);
 }
DepthwiseConvolution2dDepthMul1Int16Test()
LayerTestResult<int16_t, 4> DepthwiseConvolution2dDepthMul1Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3891 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dDepthMul1TestImpl<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
DepthwiseConvolution2dDepthMul1Test()
LayerTestResult<float, 4> DepthwiseConvolution2dDepthMul1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3779 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dDepthMul1TestImpl<armnn::DataType::Float32, armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, biasEnabled, layout);
 }
DepthwiseConvolution2dDepthMul1Uint8Test()
LayerTestResult<uint8_t, 4> DepthwiseConvolution2dDepthMul1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3855 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dDepthMul1TestImpl<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
DepthwiseConvolution2dDepthMul64Test()
LayerTestResult<float, 4> DepthwiseConvolution2dDepthMul64Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 3790 of file Conv2dTestImpl.cpp.
References armnn::Float32, armnn::GetDataTypeSize(), armnn::NCHW, armnnUtils::Permute(), and armnnUtils::Permuted().
Referenced by TEST_SUITE().
 {
     armnn::TensorInfo inputTensorInfo({ 1, 1, 2, 2 }, armnn::DataType::Float32);
     std::vector<float> input = { 1.f, 2.f, 3.f, 4.f };
     std::vector<float> kernelData;
     std::vector<float> singleDepthKernel{ 1.f, -1.f, -1.f, 1.f };
     for (unsigned int i = 0; i < 64; ++i)
     {
         kernelData.insert(kernelData.end(), singleDepthKernel.begin(), singleDepthKernel.end());
     }
     armnn::TensorInfo kernelTensorInfo({ 64, 1, 2, 2 }, armnn::DataType::Float32);
     // permute from [O,1,H,W] --> [1,H,W,O]
     armnn::PermutationVector permutationVector {3,0,1,2};
     kernelTensorInfo = armnnUtils::Permuted(kernelTensorInfo, permutationVector);
     std::vector<float> kernelPermuted(kernelTensorInfo.GetNumElements());
     armnnUtils::Permute(kernelTensorInfo.GetShape(), permutationVector,
                         kernelData.data(), kernelPermuted.data(),
                         GetDataTypeSize(kernelTensorInfo.GetDataType()));
     std::vector<float> expectedOutputData(64, 0.f);
     armnn::TensorInfo outputTensorInfo({ 1, 64, 1, 1 }, armnn::DataType::Float32);
     return DepthwiseConvolution2dTestImpl<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             input,
             kernelPermuted,
             std::vector<float>(),
             expectedOutputData,
             inputTensorInfo.GetShape(),
             kernelTensorInfo.GetShape(),
             outputTensorInfo.GetShape(),
             0.f,
             0,
             armnn::DataLayout::NCHW);
 }
DepthwiseConvolution2dDepthNhwcTest()
LayerTestResult<float, 4> DepthwiseConvolution2dDepthNhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled)
Definition at line 3769 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dNhwcTestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, biasEnabled);
 }
DepthwiseConvolution2dInt16Test()
LayerTestResult<int16_t, 4> DepthwiseConvolution2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3880 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dTestImpl<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
DepthwiseConvolution2dMult2Test()
LayerTestResult<T, 4> DepthwiseConvolution2dMult2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3026 of file Conv2dTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo({1, 2, 3, 3}, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
             {
                     10.0, 10.0, 10.0,
                     10.0, 10.0, 10.0,
                     10.0, 10.0, 10.0,
                     21.0, 22.0, 23.0,
                     24.0, 25.0, 26.0,
                     27.0, 28.0, 29.0
             };
     armnn::TensorInfo kernelTensorInfo({ 1, 2, 2, 4}, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
             {
                     0.25f, 0.25f,
                     0.25f, 0.25f,
                     0.2f , 0.0f,
                     0.0f , 0.0f,
                     0.0f , 0.0f,
                     0.0f , 0.1f,
                     0.0f , 0.3f,
                     0.0f , 0.0f
             };
     armnn::TensorInfo outputTensorInfo({ 1, 4, 2, 2}, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
             {
                      4.5f, 4.5f, 4.5f,  4.5f,
                      5.5f, 5.5f, 5.5f,  5.5f,
                     5.25f, 5.5f, 6.0f, 6.25f,
                     7.65f, 8.0f, 8.7f, 9.05f
             };
     return DepthwiseConvolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             1,
             1,
             layout,
             biasEnabled);
 }
DepthwiseConvolution2dMult4Test()
LayerTestResult<T, 4> DepthwiseConvolution2dMult4Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 2951 of file Conv2dTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo({1, 2, 3, 3}, ArmnnType);
     std::vector<float> inputNoQuantizedValues =
             {
                     10.0, 10.0, 10.0,
                     10.0, 10.0, 10.0,
                     10.0, 10.0, 10.0,
                     21.0, 22.0, 23.0,
                     24.0, 25.0, 26.0,
                     27.0, 28.0, 29.0
             };
     armnn::TensorInfo kernelTensorInfo({ 1, 2, 2, 8}, ArmnnType);
     std::vector<float> kernelNoQuantizedValues =
             {
                     0.25f, 0.25f,
                     0.25f, 0.25f,
                     0.25f, 0.25f,
                     0.25f, 0.25f,
                     0.0f , 0.0f,
                     0.0f , 0.1f,
                     0.0f , 0.0f,
                     0.0f , 0.1f,
                     0.2f , 0.0f,
                     0.0f , 0.0f,
                     0.2f , 0.0f,
                     0.0f , 0.0f,
                     0.0f , 0.3f,
                     0.0f , 0.0f,
                     0.0f , 0.3f,
                     0.0f , 0.0f
             };
     armnn::TensorInfo outputTensorInfo({ 1, 8, 2, 2}, ArmnnType);
     std::vector<float> outputExpectedNoQuantizedValues =
             {
                       4.5f,  4.5f,  4.5f,   4.5f,   5.5f,  5.5f,  5.5f,   5.5f,
                       2.5f,  2.5f,  2.5f,   2.5f,   3.5f,  3.5f,  3.5f,   3.5f,
                     10.05f, 10.5f, 11.4f, 11.85f, 12.75f, 13.3f, 14.4f, 14.95f,
                      5.25f,  5.5f,  6.0f,  6.25f,  7.45f,  7.8f,  8.5f,  8.85f
             };
     return DepthwiseConvolution2d3x3DilationTestCommon<ArmnnType, ArmnnBType>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             inputNoQuantizedValues,
             inputTensorInfo,
             kernelNoQuantizedValues,
             kernelTensorInfo,
             outputExpectedNoQuantizedValues,
             outputTensorInfo,
             1,
             1,
             layout,
             biasEnabled);
 }
DepthwiseConvolution2dPerAxisQuantTest()
LayerTestResult<uint8_t, 4> DepthwiseConvolution2dPerAxisQuantTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 3902 of file Conv2dTestImpl.cpp.
References AllocateAndCopyDataToITensorHandle(), CopyDataFromITensorHandle(), CopyDataToITensorHandle(), ITensorHandleFactory::CreateTensorHandle(), IWorkloadFactory::CreateWorkload(), armnn::DepthwiseConvolution2d, IWorkloadFactory::GetBackendId(), DepthwiseConvolution2dQueueDescriptor::m_Bias, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, DepthwiseConvolution2dDescriptor::m_StrideX, DepthwiseConvolution2dQueueDescriptor::m_Weight, armnn::NCHW, armnnUtils::Permute(), armnnUtils::Permuted(), PermuteTensorNhwcToNchw(), and TensorInfo::SetShape().
Referenced by TEST_SUITE().
 {
     using namespace armnn;
     const DataType inputType  = DataType::QAsymmU8;
     const DataType kernelType = DataType::QSymmS8;
     const DataType biasType   = DataType::Signed32;
     TensorInfo inputInfo ({ 1, 3, 3, 2 }, inputType, 0.5f, 128); // N H W C
     TensorInfo outputInfo({ 1, 2, 2, 4 }, inputType, 1.0f, 128); // N H W C
     const std::vector<float> quantScales{ 1.0f, 0.5f, 1.0f, 0.5f };
     const unsigned int quantDimension = 3;
     TensorInfo kernelInfo({ 1, 2, 2, 4 }, kernelType, quantScales, quantDimension); // [1, H, W, I*M]
     const std::vector<float> biasQuantScales{ 0.5f, 0.25f, 0.5f, 0.25f };
     constexpr unsigned int biasQuantDimension = 0;
     TensorInfo biasInfo({ 4 }, biasType, biasQuantScales, biasQuantDimension);
     std::vector<uint8_t> inputData =
     {
         129, 130,
         129, 130,
         129, 130,
         129, 130,
         129, 130,
         129, 130,
         129, 130,
         129, 130,
         129, 130
     };
     std::vector<int8_t> kernelData =
     {
         1, 1, 1, 1,
         1, 1, 1, 1,
         1, 1, 1, 1,
         1, 1, 1, 1
     };
     if (workloadFactory.GetBackendId() == armnn::BackendId("GpuAcc") ||
         workloadFactory.GetBackendId() == armnn::BackendId("CpuAcc"))
     {
         if (layout == armnn::DataLayout::NCHW)
         {
             std::vector<int8_t> tmp(kernelData.size());
             kernelInfo.SetShape(armnnUtils::Permuted(kernelInfo.GetShape(), {0, 2, 3, 1}));
             armnnUtils::Permute(kernelInfo.GetShape(), {0, 2, 3, 1}, kernelData.data(), tmp.data(), sizeof(int8_t));
             kernelData = tmp;
         }
     }
     std::vector<int32_t> biasData =
     {
         4, 4, 4, 4
     };
     std::vector<uint8_t> expectedOutputData =
     {
         132, 130, 134, 131,
         132, 130, 134, 131,
         132, 130, 134, 131,
         132, 130, 134, 131
     };
     if (layout == DataLayout::NCHW)
     {
         PermuteTensorNhwcToNchw(inputInfo, inputData);
         PermuteTensorNhwcToNchw(outputInfo, expectedOutputData);
     }
     std::vector<uint8_t> actualOutput(outputInfo.GetNumElements());
     DepthwiseConvolution2dDescriptor descriptor;
     descriptor.m_StrideX     = 1;
     descriptor.m_StrideY     = 1;
     descriptor.m_PadLeft     = 0;
     descriptor.m_PadRight    = 0;
     descriptor.m_PadTop      = 0;
     descriptor.m_PadBottom   = 0;
     descriptor.m_DilationX   = 1;
     descriptor.m_DilationY   = 1;
     descriptor.m_BiasEnabled = true;
     descriptor.m_DataLayout  = layout;
     std::unique_ptr<ITensorHandle> inputHandle  = tensorHandleFactory.CreateTensorHandle(inputInfo);
     std::unique_ptr<ITensorHandle> weightsHandle = tensorHandleFactory.CreateTensorHandle(kernelInfo);
     std::unique_ptr<ITensorHandle> biasHandle = tensorHandleFactory.CreateTensorHandle(biasInfo);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputInfo);
     DepthwiseConvolution2dQueueDescriptor queueDescriptor;
     WorkloadInfo workloadInfo;
     ScopedTensorHandle weightTensor(kernelInfo);
     ScopedTensorHandle biasTensor(biasInfo);
     AddInputToWorkload(queueDescriptor, workloadInfo, inputInfo, inputHandle.get());
     AddInputToWorkload(queueDescriptor, workloadInfo, kernelInfo, weightsHandle.get());
     AddOutputToWorkload(queueDescriptor, workloadInfo, outputInfo, outputHandle.get());
     AddInputToWorkload(queueDescriptor, workloadInfo, biasInfo, biasHandle.get());
     // AllocateAndCopyDataToITensorHandle() is required twice for the weights AND biases:
     // See comment in DepthwiseConvolution2dAsymmetricTestImpl() for reasons.
     // 1) ScopedTensorHandle (weightsTensor) required for QueueDescriptor (data.m_Weight).
     // 2) ITensorHandle (converts to Backend TensorHandle) required in RefWorkload for GetTensorInfo() method.
     AllocateAndCopyDataToITensorHandle(weightsHandle.get(), kernelData.data());
     AllocateAndCopyDataToITensorHandle(&weightTensor, kernelData.data());
     AllocateAndCopyDataToITensorHandle(biasHandle.get(), biasData.data());
     AllocateAndCopyDataToITensorHandle(&biasTensor, biasData.data());
     queueDescriptor.m_Parameters = descriptor;
     queueDescriptor.m_Weight     = &weightTensor;
     queueDescriptor.m_Bias       = &biasTensor;
     std::unique_ptr<IWorkload> workload = workloadFactory.CreateWorkload(armnn::LayerType::DepthwiseConvolution2d,
                                                                          queueDescriptor,
                                                                          workloadInfo);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), inputData.data());
     ExecuteWorkload(*workload, memoryManager);
     LayerTestResult<uint8_t, 4> ret(outputInfo);
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     return LayerTestResult<uint8_t, 4>(actualOutput,
                                        expectedOutputData,
                                        outputHandle->GetShape(),
                                        outputInfo.GetShape());
 }
DepthwiseConvolution2dTest()
LayerTestResult<float, 4> DepthwiseConvolution2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3758 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dTestImpl<armnn::DataType::Float32, armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, biasEnabled, layout);
 }
DepthwiseConvolution2dUint8Test()
LayerTestResult<uint8_t, 4> DepthwiseConvolution2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3844 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DepthwiseConvolution2dTestImpl<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
SimpleConvolution2d3x3NhwcTest()
LayerTestResult<float, 4> SimpleConvolution2d3x3NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled)
Definition at line 3524 of file Conv2dTestImpl.cpp.
References armnn::NHWC.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x3NhwcTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         biasEnabled,
         armnn::DataLayout::NHWC);
 }
SimpleConvolution2d3x3QSymm16Test()
LayerTestResult<int16_t, 4> SimpleConvolution2d3x3QSymm16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3579 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x3TestCommon<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
SimpleConvolution2d3x3Stride2x2Test()
LayerTestResult<float, 4> SimpleConvolution2d3x3Stride2x2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3540 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x3Stride2x2TestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         biasEnabled,
         layout);
 }
SimpleConvolution2d3x3Test()
LayerTestResult<float, 4> SimpleConvolution2d3x3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3513 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x3TestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.f, 0, biasEnabled, layout);
 }
SimpleConvolution2d3x3Uint8Test()
LayerTestResult<uint8_t, 4> SimpleConvolution2d3x3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3557 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x3TestCommon<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
SimpleConvolution2d3x5QSymm16Test()
LayerTestResult<int16_t, 4> SimpleConvolution2d3x5QSymm16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3568 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x5TestCommon<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
SimpleConvolution2d3x5Test()
LayerTestResult<float, 4> SimpleConvolution2d3x5Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3491 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x5TestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.f, 0, biasEnabled, layout);
 }
SimpleConvolution2d3x5Uint8Test()
LayerTestResult<uint8_t, 4> SimpleConvolution2d3x5Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, const armnn::DataLayout layout)
Definition at line 3502 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution2d3x5TestCommon<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, 50, biasEnabled, layout);
 }
SimpleDepthwiseConvolution2d3x3Dilation3x3NhwcTest()
LayerTestResult<float, 4> SimpleDepthwiseConvolution2d3x3Dilation3x3NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 3866 of file Conv2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleDepthwiseConvolution2d3x3Dilation3x3NhwcTestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory,
             memoryManager,
             tensorHandleFactory,
             0.f,
             0,
             false);
 }