ArmNN: tests/ExecuteNetwork/ExecuteNetworkParams.cpp File Reference
ExecuteNetworkParams.cpp File Reference
#include "ExecuteNetworkParams.hpp"
#include "NetworkExecutionUtils/NetworkExecutionUtils.hpp"
#include <InferenceModel.hpp>
#include <armnn/Logging.hpp>
#include <fmt/format.h>
Functions
bool IsModelBinary (const std::string &modelFormat)
void CheckModelFormat (const std::string &modelFormat)
void CheckClTuningParameter (const int &tuningLevel, const std::string &tuningPath, const std::vector< armnn::BackendId > computeDevices)
Function Documentation
CheckClTuningParameter()
void CheckClTuningParameter (const int & tuningLevel, const std::string & tuningPath, const std::vector< armnn::BackendId > computeDevices)
Definition at line 75 of file ExecuteNetworkParams.cpp.
References ARMNN_LOG, and ValidatePath().
Referenced by ExecuteNetworkParams::ValidateParams().
 {
     if (!tuningPath.empty())
     {
         if (tuningLevel == 0)
         {
             ARMNN_LOG(info) << "Using cl tuning file: " << tuningPath << "\n";
             if (!ValidatePath(tuningPath, true))
             {
                 throw armnn::InvalidArgumentException("The tuning path is not valid");
             }
         }
         else if ((1 <= tuningLevel) && (tuningLevel <= 3))
         {
             ARMNN_LOG(info) << "Starting execution to generate a cl tuning file: " << tuningPath << "\n"
                             << "Tuning level in use: " << tuningLevel << "\n";
         }
         else if ((0 < tuningLevel) || (tuningLevel > 3))
         {
             throw armnn::InvalidArgumentException(fmt::format("The tuning level {} is not valid.",
                                                               tuningLevel));
         }
         // Ensure that a GpuAcc is enabled. Otherwise no tuning data are used or genereted
         // Only warn if it's not enabled
         auto it = std::find(computeDevices.begin(), computeDevices.end(), "GpuAcc");
         if (it == computeDevices.end())
         {
             ARMNN_LOG(warning) << "To use Cl Tuning the compute device GpuAcc needs to be active.";
         }
     }
 }
CheckModelFormat()
void CheckModelFormat (const std::string & modelFormat)
Definition at line 33 of file ExecuteNetworkParams.cpp.
References IsModelBinary().
Referenced by ExecuteNetworkParams::ValidateParams().
 {
     // Forward to implementation based on the parser type
     if (modelFormat.find("armnn") != std::string::npos)
     {
 #if defined(ARMNN_SERIALIZER)
 #else
         throw armnn::InvalidArgumentException("Can't run model in armnn format without a "
                                               "built with serialization support.");
 #endif
     }
     else if (modelFormat.find("onnx") != std::string::npos)
     {
 #if defined(ARMNN_ONNX_PARSER)
 #else
         throw armnn::InvalidArgumentException("Can't run model in onnx format without a "
                                               "built with Onnx parser support.");
 #endif
     }
     else if (modelFormat.find("tflite") != std::string::npos)
     {
 #if defined(ARMNN_TF_LITE_PARSER)
         if (!IsModelBinary(modelFormat))
         {
             throw armnn::InvalidArgumentException(fmt::format("Unknown model format: '{}'. Only 'binary' "
                                                               "format supported for tflite files",
                                                               modelFormat));
         }
 #elif defined(ARMNN_TFLITE_DELEGATE)
 #else
         throw armnn::InvalidArgumentException("Can't run model in tflite format without a "
                                               "built with Tensorflow Lite parser support.");
 #endif
     }
     else
     {
         throw armnn::InvalidArgumentException(fmt::format("Unknown model format: '{}'. "
                                                           "Please include 'tflite' or 'onnx'",
                                                           modelFormat));
     }
 }
IsModelBinary()
bool IsModelBinary (const std::string & modelFormat)
Definition at line 14 of file ExecuteNetworkParams.cpp.
Referenced by CheckModelFormat(), and ExecuteNetworkParams::ValidateParams().
 {
     // Parse model binary flag from the model-format string we got from the command-line
     if (modelFormat.find("binary") != std::string::npos)
     {
         return true;
     }
     else if (modelFormat.find("txt") != std::string::npos || modelFormat.find("text") != std::string::npos)
     {
         return false;
     }
     else
     {
         throw armnn::InvalidArgumentException(fmt::format("Unknown model format: '{}'. "
                                                           "Please include 'binary' or 'text'",
                                                           modelFormat));
     }
 }