ArmNN: src/backends/backendsCommon/test/layerTests/NormalizationTestImpl.hpp File Reference
NormalizationTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <armnn/Types.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > SimpleNormalizationAcrossTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SimpleNormalizationWithinTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SimpleNormalizationAcrossNhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > CompareNormalizationTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::NormalizationAlgorithmChannel normChannel, armnn::NormalizationAlgorithmMethod normMethod)
LayerTestResult< float, 4 > AcrossChannelNormalizationTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
AcrossChannelNormalizationTest()
LayerTestResult<float, 4> AcrossChannelNormalizationTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 541 of file NormalizationTestImpl.cpp.
References armnn::Across, and armnn::LocalBrightness.
Referenced by TEST_SUITE().
 {
     auto normMethod = armnn::NormalizationAlgorithmMethod::LocalBrightness;
     auto normChannel = armnn::NormalizationAlgorithmChannel::Across;
     return AcrossChannelNormalizationTestImpl(workloadFactory,
                                                memoryManager,
                                                tensorHandleFactory,
                                                normChannel,
                                                normMethod);
 }
CompareNormalizationTest()
LayerTestResult<float, 4> CompareNormalizationTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::NormalizationAlgorithmChannel normChannel, armnn::NormalizationAlgorithmMethod normMethod)
Definition at line 527 of file NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CompareNormalizationTestImpl(
             workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory,
             normChannel, normMethod);
 }
SimpleNormalizationAcrossNhwcTest()
LayerTestResult<float,4> SimpleNormalizationAcrossNhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 516 of file NormalizationTestImpl.cpp.
References armnn::Across, and armnn::LocalBrightness.
Referenced by TEST_SUITE().
 {
     auto normMethod = armnn::NormalizationAlgorithmMethod::LocalBrightness;
     auto normChannel = armnn::NormalizationAlgorithmChannel::Across;
     return SimpleNormalizationNhwcTestImpl(
             workloadFactory, memoryManager,  tensorHandleFactory, normChannel, normMethod);
 }
SimpleNormalizationAcrossTest()
LayerTestResult<float, 4> SimpleNormalizationAcrossTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 496 of file NormalizationTestImpl.cpp.
References armnn::Across, and armnn::LocalBrightness.
Referenced by TEST_SUITE().
 {
     auto normMethod = armnn::NormalizationAlgorithmMethod::LocalBrightness;
     auto normChannel = armnn::NormalizationAlgorithmChannel::Across;
     return SimpleNormalizationTestImpl(workloadFactory, memoryManager,  tensorHandleFactory, normChannel, normMethod);
 }
SimpleNormalizationWithinTest()
LayerTestResult<float, 4> SimpleNormalizationWithinTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 506 of file NormalizationTestImpl.cpp.
References armnn::LocalBrightness, and armnn::Within.
Referenced by TEST_SUITE().
 {
     auto normMethod = armnn::NormalizationAlgorithmMethod::LocalBrightness;
     auto normChannel = armnn::NormalizationAlgorithmChannel::Within;
     return SimpleNormalizationTestImpl(workloadFactory, memoryManager,  tensorHandleFactory, normChannel, normMethod);
 }