ArmNN: src/backends/backendsCommon/test/layerTests/Pooling3dTestImpl.cpp File Reference
Pooling3dTestImpl.cpp File Reference
#include "Pooling3dTestImpl.hpp"
#include <armnnUtils/QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnUtils/TensorUtils.hpp>
#include <armnnUtils/DataLayoutIndexed.hpp>
#include <armnnUtils/Permute.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <armnn/utility/NumericCast.hpp>
#include <armnn/BackendHelper.hpp>
#include <backendsCommon/WorkloadInfo.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
Functions
LayerTestResult< float, 5 > SimpleMaxPooling3dSize2x2x2Stride1x1x1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleMaxPooling3dSize2x2x2Stride1x1x1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleMaxPooling3dSize2x2x2Stride1x1x1Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > SimpleMaxPooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > IgnorePaddingSimpleMaxPooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > IgnorePaddingSimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > IgnorePaddingSimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > SimpleAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > SimpleL2Pooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > LargeTensorsAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > LargeTensorsAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > LargeTensorsAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > IgnorePaddingSimpleAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > IgnorePaddingSimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > IgnorePaddingSimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > IgnorePaddingSimpleL2Pooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > IgnorePaddingSimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > IgnorePaddingSimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > AsymmetricNonSquareMaxPooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareMaxPooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareMaxPooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > AsymmetricNonSquareAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > AsymmetricNonSquareL2Pooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareL2Pooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareL2Pooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > ComparePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > ComparePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > ComparePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType, const armnn::DataLayout dataLayout)
Function Documentation
AsymmetricNonSquareAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1552 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareAveragePooling3dTest()
LayerTestResult<float, 5> AsymmetricNonSquareAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1532 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1542 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1582 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolTest()
LayerTestResult<float, 5> AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1562 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1572 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareL2Pooling3dInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareL2Pooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1612 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareL2Pooling3dTest()
LayerTestResult<float, 5> AsymmetricNonSquareL2Pooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1592 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareL2Pooling3dUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareL2Pooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1602 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1642 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolTest()
LayerTestResult<float, 5> AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1622 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1632 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareMaxPooling3dInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareMaxPooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1492 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareMaxPooling3dTest()
LayerTestResult<float, 5> AsymmetricNonSquareMaxPooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1472 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareMaxPooling3dUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareMaxPooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1482 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1522 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolTest()
LayerTestResult<float, 5> AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1502 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1512 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dWithPaddingOnlyPoolTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
ComparePooling3dInt16Test()
LayerTestResult<int16_t, 5> ComparePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType, const armnn::DataLayout dataLayout)
Definition at line 1680 of file Pooling3dTestImpl.cpp.
 {
     return ComparePooling3dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory,
         poolingType, dataLayout);
 }
ComparePooling3dTest()
LayerTestResult<float, 5> ComparePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType, const armnn::DataLayout dataLayout)
Definition at line 1652 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ComparePooling3dTestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory,
         poolingType, dataLayout);
 }
ComparePooling3dUint8Test()
LayerTestResult<uint8_t, 5> ComparePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType, const armnn::DataLayout dataLayout)
Definition at line 1666 of file Pooling3dTestImpl.cpp.
 {
     return ComparePooling3dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory,
         poolingType, dataLayout, 0.1f, 128);
 }
IgnorePaddingSimpleAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> IgnorePaddingSimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1432 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
IgnorePaddingSimpleAveragePooling3dTest()
LayerTestResult<float, 5> IgnorePaddingSimpleAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1412 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
IgnorePaddingSimpleAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> IgnorePaddingSimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1422 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout, 1.0f, -5);
 }
IgnorePaddingSimpleL2Pooling3dInt16Test()
LayerTestResult<int16_t, 5> IgnorePaddingSimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1462 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
IgnorePaddingSimpleL2Pooling3dTest()
LayerTestResult<float, 5> IgnorePaddingSimpleL2Pooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1442 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
IgnorePaddingSimpleL2Pooling3dUint8Test()
LayerTestResult<uint8_t, 5> IgnorePaddingSimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1452 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout, 1.0f, -5);
 }
IgnorePaddingSimpleMaxPooling3dInt16Test()
LayerTestResult<int16_t, 5> IgnorePaddingSimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1312 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
IgnorePaddingSimpleMaxPooling3dTest()
LayerTestResult<float, 5> IgnorePaddingSimpleMaxPooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1292 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
IgnorePaddingSimpleMaxPooling3dUint8Test()
LayerTestResult<uint8_t, 5> IgnorePaddingSimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1302 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory,dataLayout, 1.0f, -5);
 }
LargeTensorsAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> LargeTensorsAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1402 of file Pooling3dTestImpl.cpp.
 {
     return LargeTensorsAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
LargeTensorsAveragePooling3dTest()
LayerTestResult<float, 5> LargeTensorsAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1382 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LargeTensorsAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
LargeTensorsAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> LargeTensorsAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1392 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LargeTensorsAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, dataLayout, 0.5, -1);
 }
SimpleAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> SimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1342 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleAveragePooling3dTest()
LayerTestResult<float, 5> SimpleAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1322 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> SimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1332 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling3dInt16Test()
LayerTestResult<int16_t, 5> SimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1372 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling3dTest()
LayerTestResult<float, 5> SimpleL2Pooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1352 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling3dUint8Test()
LayerTestResult<uint8_t, 5> SimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1362 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dInt16Test()
LayerTestResult<int16_t, 5> SimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1282 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dSize2x2x2Stride1x1x1Int16Test()
LayerTestResult<int16_t, 5> SimpleMaxPooling3dSize2x2x2Stride1x1x1Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1252 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dSize2x2x2Stride1x1x1TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dSize2x2x2Stride1x1x1Test()
LayerTestResult<float, 5> SimpleMaxPooling3dSize2x2x2Stride1x1x1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1232 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dSize2x2x2Stride1x1x1TestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dSize2x2x2Stride1x1x1Uint8Test()
LayerTestResult<uint8_t, 5> SimpleMaxPooling3dSize2x2x2Stride1x1x1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1242 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dSize2x2x2Stride1x1x1TestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, dataLayout, 0.1f, 128);
 }
SimpleMaxPooling3dTest()
LayerTestResult<float, 5> SimpleMaxPooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1262 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dUint8Test()
LayerTestResult<uint8_t, 5> SimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1272 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }