ArmNN: src/backends/backendsCommon/test/layerTests/Pooling2dTestImpl.cpp File Reference
Pooling2dTestImpl.cpp File Reference
#include "Pooling2dTestImpl.hpp"
#include <armnnUtils/QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnUtils/TensorUtils.hpp>
#include <armnnUtils/DataLayoutIndexed.hpp>
#include <armnnUtils/Permute.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <armnn/utility/NumericCast.hpp>
#include <armnn/BackendHelper.hpp>
#include <backendsCommon/WorkloadInfo.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
Functions
LayerTestResult< float, 4 > SimpleMaxPooling2dSize2x2Stride2x2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< uint8_t, 4 > SimpleMaxPooling2dSize2x2Stride2x2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< int16_t, 4 > SimpleMaxPooling2dSize2x2Stride2x2Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< float, 4 > SimpleMaxPooling2dSize3x3Stride2x4Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< uint8_t, 4 > SimpleMaxPooling2dSize3x3Stride2x4Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< int16_t, 4 > SimpleMaxPooling2dSize3x3Stride2x4Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< float, 4 > SimpleMaxPooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 4 > SimpleMaxPooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 4 > SimpleMaxPooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 4 > IgnorePaddingSimpleMaxPooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingSimpleMaxPooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingSimpleMaxPooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > IgnorePaddingMaxPooling2dSize3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingMaxPooling2dSize3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingMaxPooling2dSize3Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SimpleAveragePooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 4 > SimpleAveragePooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 4 > SimpleAveragePooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 4 > IgnorePaddingAveragePooling2dSize3x2Stride2x2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool forceNoPadding)
LayerTestResult< float, 4 > LargeTensorsAveragePooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LargeTensorsAveragePooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > LargeTensorsAveragePooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > IgnorePaddingSimpleAveragePooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingSimpleAveragePooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingSimpleAveragePooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > IgnorePaddingSimpleAveragePooling2dNoPaddingTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingSimpleAveragePooling2dNoPaddingInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > IgnorePaddingAveragePooling2dSize3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingAveragePooling2dSize3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingAveragePooling2dSize3Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SimpleL2Pooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 4 > SimpleL2Pooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 4 > SimpleL2Pooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 4 > L2Pooling2dSize3Stride1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > L2Pooling2dSize3Stride1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > L2Pooling2dSize3Stride1Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > L2Pooling2dSize3Stride3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > L2Pooling2dSize3Stride3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > L2Pooling2dSize3Stride3Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > L2Pooling2dSize3Stride4Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > L2Pooling2dSize3Stride4Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > L2Pooling2dSize3Stride4Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > L2Pooling2dSize7Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > L2Pooling2dSize7Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > L2Pooling2dSize7Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > L2Pooling2dSize9Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > L2Pooling2dSize9Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > L2Pooling2dSize9Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > IgnorePaddingSimpleL2Pooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingSimpleL2Pooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingSimpleL2Pooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > IgnorePaddingL2Pooling2dSize3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > IgnorePaddingL2Pooling2dSize3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > IgnorePaddingL2Pooling2dSize3Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > AsymmetricNonSquarePooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > AsymmetricNonSquarePooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > AsymmetricNonSquarePooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > ComparePooling2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
LayerTestResult< uint8_t, 4 > ComparePooling2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
LayerTestResult< int16_t, 4 > ComparePooling2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Function Documentation
AsymmetricNonSquarePooling2dInt16Test()
LayerTestResult<int16_t, 4> AsymmetricNonSquarePooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1919 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquarePooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquarePooling2dTest()
LayerTestResult<float, 4> AsymmetricNonSquarePooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1901 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquarePooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquarePooling2dUint8Test()
LayerTestResult<uint8_t, 4> AsymmetricNonSquarePooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1910 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquarePooling2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
ComparePooling2dInt16Test()
LayerTestResult<int16_t, 4> ComparePooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Definition at line 1953 of file Pooling2dTestImpl.cpp.
 {
     return ComparePooling2dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, poolingType);
 }
ComparePooling2dTest()
LayerTestResult<float, 4> ComparePooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Definition at line 1928 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ComparePooling2dTestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, poolingType);
 }
ComparePooling2dUint8Test()
LayerTestResult<uint8_t, 4> ComparePooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Definition at line 1940 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return ComparePooling2dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory,
         poolingType, 0.1f, 128);
 }
IgnorePaddingAveragePooling2dSize3Int16Test()
LayerTestResult<int16_t, 4> IgnorePaddingAveragePooling2dSize3Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1675 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingAveragePooling2dSize3TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingAveragePooling2dSize3Test()
LayerTestResult<float, 4> IgnorePaddingAveragePooling2dSize3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1657 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingAveragePooling2dSize3TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingAveragePooling2dSize3Uint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingAveragePooling2dSize3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1666 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingAveragePooling2dSize3TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingAveragePooling2dSize3x2Stride2x2Test()
LayerTestResult<float, 4> IgnorePaddingAveragePooling2dSize3x2Stride2x2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1567 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingAveragePooling2dSize3x2Stride2x2TestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding);
 }
IgnorePaddingL2Pooling2dSize3Int16Test()
LayerTestResult<int16_t, 4> IgnorePaddingL2Pooling2dSize3Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1892 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingL2Pooling2dSize3TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingL2Pooling2dSize3Test()
LayerTestResult<float, 4> IgnorePaddingL2Pooling2dSize3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1874 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingL2Pooling2dSize3TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingL2Pooling2dSize3Uint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingL2Pooling2dSize3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1883 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingL2Pooling2dSize3TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingMaxPooling2dSize3Int16Test()
LayerTestResult<int16_t, 4> IgnorePaddingMaxPooling2dSize3Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1528 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingMaxPooling2dSize3TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingMaxPooling2dSize3Test()
LayerTestResult<float, 4> IgnorePaddingMaxPooling2dSize3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1510 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingMaxPooling2dSize3TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingMaxPooling2dSize3Uint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingMaxPooling2dSize3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1519 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingMaxPooling2dSize3TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -5);
 }
IgnorePaddingSimpleAveragePooling2dInt16Test()
LayerTestResult<int16_t, 4> IgnorePaddingSimpleAveragePooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1621 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling2dNoPaddingInt16Test()
LayerTestResult<int16_t, 4> IgnorePaddingSimpleAveragePooling2dNoPaddingInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1648 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling2dNoPaddingTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling2dNoPaddingTest()
LayerTestResult<float, 4> IgnorePaddingSimpleAveragePooling2dNoPaddingTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1630 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling2dNoPaddingTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1639 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling2dNoPaddingTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling2dTest()
LayerTestResult<float, 4> IgnorePaddingSimpleAveragePooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1603 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling2dUint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingSimpleAveragePooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1612 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleL2Pooling2dInt16Test()
LayerTestResult<int16_t, 4> IgnorePaddingSimpleL2Pooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1865 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleL2Pooling2dTest()
LayerTestResult<float, 4> IgnorePaddingSimpleL2Pooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1847 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleL2Pooling2dUint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingSimpleL2Pooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1856 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleMaxPooling2dInt16Test()
LayerTestResult<int16_t, 4> IgnorePaddingSimpleMaxPooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1501 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleMaxPooling2dTest()
LayerTestResult<float, 4> IgnorePaddingSimpleMaxPooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1483 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleMaxPooling2dUint8Test()
LayerTestResult<uint8_t, 4> IgnorePaddingSimpleMaxPooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1492 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -5);
 }
L2Pooling2dSize3Stride1Int16Test()
LayerTestResult<int16_t, 4> L2Pooling2dSize3Stride1Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1732 of file Pooling2dTestImpl.cpp.
 {
     return L2Pooling2dSize3Stride1TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride1Test()
LayerTestResult<float, 4> L2Pooling2dSize3Stride1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1714 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize3Stride1TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride1Uint8Test()
LayerTestResult<uint8_t, 4> L2Pooling2dSize3Stride1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1723 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize3Stride1TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride3Int16Test()
LayerTestResult<int16_t, 4> L2Pooling2dSize3Stride3Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1759 of file Pooling2dTestImpl.cpp.
 {
     return L2Pooling2dSize3Stride3TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride3Test()
LayerTestResult<float, 4> L2Pooling2dSize3Stride3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1741 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize3Stride3TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride3Uint8Test()
LayerTestResult<uint8_t, 4> L2Pooling2dSize3Stride3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1750 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize3Stride3TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride4Int16Test()
LayerTestResult<int16_t, 4> L2Pooling2dSize3Stride4Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1785 of file Pooling2dTestImpl.cpp.
 {
     return L2Pooling2dSize3Stride4TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride4Test()
LayerTestResult<float, 4> L2Pooling2dSize3Stride4Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1767 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize3Stride4TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize3Stride4Uint8Test()
LayerTestResult<uint8_t, 4> L2Pooling2dSize3Stride4Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1776 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize3Stride4TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize7Int16Test()
LayerTestResult<int16_t, 4> L2Pooling2dSize7Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1812 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize7TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize7Test()
LayerTestResult<float, 4> L2Pooling2dSize7Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1794 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize7TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize7Uint8Test()
LayerTestResult<uint8_t, 4> L2Pooling2dSize7Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1803 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize7TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize9Int16Test()
LayerTestResult<int16_t, 4> L2Pooling2dSize9Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1839 of file Pooling2dTestImpl.cpp.
 {
     return L2Pooling2dSize9TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize9Test()
LayerTestResult<float, 4> L2Pooling2dSize9Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1821 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize9TestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
L2Pooling2dSize9Uint8Test()
LayerTestResult<uint8_t, 4> L2Pooling2dSize9Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1830 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Pooling2dSize9TestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
LargeTensorsAveragePooling2dInt16Test()
LayerTestResult<int16_t, 4> LargeTensorsAveragePooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1595 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LargeTensorsAveragePooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
LargeTensorsAveragePooling2dTest()
LayerTestResult<float, 4> LargeTensorsAveragePooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1577 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LargeTensorsAveragePooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
LargeTensorsAveragePooling2dUint8Test()
LayerTestResult<uint8_t, 4> LargeTensorsAveragePooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1586 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return LargeTensorsAveragePooling2dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5, -1);
 }
SimpleAveragePooling2dInt16Test()
LayerTestResult<int16_t, 4> SimpleAveragePooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1557 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleAveragePooling2dTest()
LayerTestResult<float, 4> SimpleAveragePooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1537 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleAveragePooling2dUint8Test()
LayerTestResult<uint8_t, 4> SimpleAveragePooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1547 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling2dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, dataLayout, 0.5, -1);
 }
SimpleL2Pooling2dInt16Test()
LayerTestResult<int16_t, 4> SimpleL2Pooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1704 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling2dTest()
LayerTestResult<float, 4> SimpleL2Pooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1684 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling2dUint8Test()
LayerTestResult<uint8_t, 4> SimpleL2Pooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1694 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling2dInt16Test()
LayerTestResult<int16_t, 4> SimpleMaxPooling2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1474 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling2dSize2x2Stride2x2Int16Test()
LayerTestResult<int16_t, 4> SimpleMaxPooling2dSize2x2Stride2x2Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1414 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dSize2x2Stride2x2TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding);
 }
SimpleMaxPooling2dSize2x2Stride2x2Test()
LayerTestResult<float, 4> SimpleMaxPooling2dSize2x2Stride2x2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1394 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dSize2x2Stride2x2TestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding);
 }
SimpleMaxPooling2dSize2x2Stride2x2Uint8Test()
LayerTestResult<uint8_t, 4> SimpleMaxPooling2dSize2x2Stride2x2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1404 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dSize2x2Stride2x2TestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding, 3.0f, -5);
 }
SimpleMaxPooling2dSize3x3Stride2x4Int16Test()
LayerTestResult<int16_t, 4> SimpleMaxPooling2dSize3x3Stride2x4Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1444 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dSize3x3Stride2x4TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding);
 }
SimpleMaxPooling2dSize3x3Stride2x4Test()
LayerTestResult<float, 4> SimpleMaxPooling2dSize3x3Stride2x4Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1424 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dSize3x3Stride2x4TestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding);
 }
SimpleMaxPooling2dSize3x3Stride2x4Uint8Test()
LayerTestResult<uint8_t, 4> SimpleMaxPooling2dSize3x3Stride2x4Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool forceNoPadding)
Definition at line 1434 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dSize3x3Stride2x4TestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, forceNoPadding, 0.1f, 128);
 }
SimpleMaxPooling2dTest()
LayerTestResult<float, 4> SimpleMaxPooling2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1454 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling2dUint8Test()
LayerTestResult<uint8_t, 4> SimpleMaxPooling2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1464 of file Pooling2dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }