ArmNN: src/backends/reference/test/RefPerAxisIteratorTests.cpp File Reference
RefPerAxisIteratorTests.cpp File Reference
#include <reference/workloads/Decoders.hpp>
#include <fmt/format.h>
#include <doctest/doctest.h>
#include <chrono>
Functions
template<typename T >
void CompareVector (std::vector< T > vec1, std::vector< T > vec2)
TEST_SUITE ("RefPerAxisIterator")
Function Documentation
CompareVector()
void CompareVector (std::vector< T > vec1, std::vector< T > vec2)
Definition at line 15 of file RefPerAxisIteratorTests.cpp.
References TensorShape::GetNumElements(), and armnn::IgnoreUnused().
Referenced by TEST_SUITE().
 {
     CHECK(vec1.size() == vec2.size());
     bool mismatch = false;
     for (uint32_t i = 0; i < vec1.size(); ++i)
     {
         if (vec1[i] != vec2[i])
         {
             MESSAGE(fmt::format("Vector value mismatch: index={}  {} != {}",
                                 i,
                                 vec1[i],
                                 vec2[i]));
             mismatch = true;
         }
     }
     if (mismatch)
     {
         FAIL("Error in CompareVector. Vectors don't match.");
     }
 }
TEST_SUITE()
TEST_SUITE ("RefPerAxisIterator")
Definition at line 80 of file RefPerAxisIteratorTests.cpp.
References CompareVector(), and armnn::QSymmS8.
 {
 // Test Loop (Equivalent to DecodeTensor) and Axis = 0
 TEST_CASE("PerAxisIteratorTest1")
 {
     std::vector<int8_t> input = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     TensorInfo tensorInfo ({3,1,2,2},DataType::QSymmS8);
     // test axis=0
     std::vector<int8_t> expOutput = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     auto iterator = MockPerAxisIterator(input.data(), tensorInfo.GetShape(), 0);
     std::vector<int8_t> output = iterator.Loop();
     CompareVector(output, expOutput);
     // Set iterator to index and check if the axis index is correct
     iterator[5];
     CHECK(iterator.GetAxisIndex() == 1u);
     iterator[1];
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator[10];
     CHECK(iterator.GetAxisIndex() == 2u);
 }
 // Test Axis = 1
 TEST_CASE("PerAxisIteratorTest2")
 {
     std::vector<int8_t> input = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     TensorInfo tensorInfo ({3,1,2,2},DataType::QSymmS8);
     // test axis=1
     std::vector<int8_t> expOutput = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     auto iterator = MockPerAxisIterator(input.data(), tensorInfo.GetShape(), 1);
     std::vector<int8_t> output = iterator.Loop();
     CompareVector(output, expOutput);
     // Set iterator to index and check if the axis index is correct
     iterator[5];
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator[1];
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator[10];
     CHECK(iterator.GetAxisIndex() == 0u);
 }
 // Test Axis = 2
 TEST_CASE("PerAxisIteratorTest3")
 {
     std::vector<int8_t> input = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     TensorInfo tensorInfo ({3,1,2,2},DataType::QSymmS8);
     // test axis=2
     std::vector<int8_t> expOutput = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     auto iterator = MockPerAxisIterator(input.data(), tensorInfo.GetShape(), 2);
     std::vector<int8_t> output = iterator.Loop();
     CompareVector(output, expOutput);
     // Set iterator to index and check if the axis index is correct
     iterator[5];
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator[1];
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator[10];
     CHECK(iterator.GetAxisIndex() == 1u);
 }
 // Test Axis = 3
 TEST_CASE("PerAxisIteratorTest4")
 {
     std::vector<int8_t> input = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     TensorInfo tensorInfo ({3,1,2,2},DataType::QSymmS8);
     // test axis=3
     std::vector<int8_t> expOutput = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
     auto iterator = MockPerAxisIterator(input.data(), tensorInfo.GetShape(), 3);
     std::vector<int8_t> output = iterator.Loop();
     CompareVector(output, expOutput);
     // Set iterator to index and check if the axis index is correct
     iterator[5];
     CHECK(iterator.GetAxisIndex() == 1u);
     iterator[1];
     CHECK(iterator.GetAxisIndex() == 1u);
     iterator[10];
     CHECK(iterator.GetAxisIndex() == 0u);
 }
 // Test Axis = 1. Different tensor shape
 TEST_CASE("PerAxisIteratorTest5")
 {
     using namespace armnn;
     std::vector<int8_t> input =
     {
          0,  1,  2,  3,
          4,  5,  6,  7,
          8,  9, 10, 11,
         12, 13, 14, 15
     };
     std::vector<int8_t> expOutput =
     {
          0,  1,  2,  3,
          4,  5,  6,  7,
          8,  9, 10, 11,
         12, 13, 14, 15
     };
     TensorInfo tensorInfo ({2,2,2,2},DataType::QSymmS8);
     auto iterator = MockPerAxisIterator(input.data(), tensorInfo.GetShape(), 1);
     std::vector<int8_t> output = iterator.Loop();
     CompareVector(output, expOutput);
     // Set iterator to index and check if the axis index is correct
     iterator[5];
     CHECK(iterator.GetAxisIndex() == 1u);
     iterator[1];
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator[10];
     CHECK(iterator.GetAxisIndex() == 0u);
 }
 // Test the increment and decrement operator
 TEST_CASE("PerAxisIteratorTest7")
 {
     using namespace armnn;
     std::vector<int8_t> input =
     {
         0, 1,  2,  3,
         4, 5,  6,  7,
         8, 9, 10, 11
     };
     std::vector<int8_t> expOutput =
     {
         0, 1,  2,  3,
         4, 5,  6,  7,
         8, 9, 10, 11
     };
     TensorInfo tensorInfo ({3,1,2,2},DataType::QSymmS8);
     auto iterator = MockPerAxisIterator(input.data(), tensorInfo.GetShape(), 2);
     iterator += 3;
     CHECK(iterator.Get() == expOutput[3]);
     CHECK(iterator.GetAxisIndex() == 1u);
     iterator += 3;
     CHECK(iterator.Get() == expOutput[6]);
     CHECK(iterator.GetAxisIndex() == 1u);
     iterator -= 2;
     CHECK(iterator.Get() == expOutput[4]);
     CHECK(iterator.GetAxisIndex() == 0u);
     iterator -= 1;
     CHECK(iterator.Get() == expOutput[3]);
     CHECK(iterator.GetAxisIndex() == 1u);
 }
 }