ArmNN: src/backends/backendsCommon/test/layerTests/SpaceToBatchNdTestImpl.cpp File Reference
SpaceToBatchNdTestImpl.cpp File Reference
#include "SpaceToBatchNdTestImpl.hpp"
#include <armnnUtils/QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnUtils/Permute.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
Functions
LayerTestResult< float, 4 > SpaceToBatchNdSimpleFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiChannelsFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiBlockFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdPaddingFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiChannelsFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiBlockFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdPaddingFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiChannelsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiBlockUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdPaddingUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdSimpleNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiChannelsNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiBlockNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdPaddingNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdSimpleNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiChannelsNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiBlockNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdPaddingNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdSimpleNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiChannelsNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiBlockNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdPaddingNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdSimpleUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiChannelsUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiBlockUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdPaddingUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdSimpleNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiChannelsNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiBlockNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdPaddingNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
SpaceToBatchNdMultiBlockFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiBlockFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 366 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::Float16>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiBlockFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 326 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::Float32>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiBlockNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 486 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiBlockNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 446 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiBlockNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 606 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                        memoryManager,
                                                                        tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiBlockNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 526 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                        memoryManager,
                                                                        tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiBlockUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 566 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiBlockUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 406 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiChannelsFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 356 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::Float16>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiChannelsFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 316 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::Float32>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiChannelsNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 476 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                          memoryManager,
                                                                          tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiChannelsNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 436 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                          memoryManager,
                                                                          tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiChannelsNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 596 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                           memoryManager,
                                                                           tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiChannelsNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 516 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                           memoryManager,
                                                                           tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiChannelsUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 556 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiChannelsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 396 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdPaddingFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdPaddingFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 376 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::Float16>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
SpaceToBatchNdPaddingFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdPaddingFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 336 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdPaddingNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 496 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdPaddingNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 456 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdPaddingNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 616 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                     memoryManager,
                                                                     tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdPaddingNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 536 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                     memoryManager,
                                                                     tensorHandleFactory);
 }
SpaceToBatchNdPaddingUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdPaddingUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 576 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory);
 }
SpaceToBatchNdPaddingUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdPaddingUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 416 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory);
 }
SpaceToBatchNdSimpleFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 346 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::Float16>(workloadFactory,
                                                               memoryManager,
                                                               tensorHandleFactory);
 }
SpaceToBatchNdSimpleFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdSimpleFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 306 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::Float32>(workloadFactory,
                                                               memoryManager,
                                                               tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdSimpleNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 466 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdSimpleNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 426 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdSimpleNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 586 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdSimpleNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 506 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdSimpleUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdSimpleUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 546 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
SpaceToBatchNdSimpleUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 386 of file SpaceToBatchNdTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }