ArmNN: src/armnnTestUtils/CommonTestUtils.hpp File Reference
CommonTestUtils.hpp File Reference
#include "TestUtils.hpp"
#include <Graph.hpp>
#include <ResolveType.hpp>
#include <SubgraphViewSelector.hpp>
#include <armnn/BackendRegistry.hpp>
#include <armnn/Types.hpp>
#include <armnn/backends/SubgraphView.hpp>
#include <armnn/backends/TensorHandle.hpp>
#include <algorithm>
#include <random>
#include <vector>
Functions
template<typename CollectionType >
bool AreEqual (const CollectionType &lhs, const CollectionType &rhs)
template<typename CollectionType >
bool Contains (const CollectionType &collection, const typename CollectionType::value_type &item)
template<typename MapType >
bool Contains (const MapType &map, const typename MapType::key_type &key)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
bool Compare (T a, T b, float tolerance=0.000001f)
template<typename ConvolutionLayer >
void SetWeightAndBias (ConvolutionLayer *layer, const armnn::TensorInfo &weightInfo, const armnn::TensorInfo &biasInfo)
armnn::SubgraphView::InputSlots CreateInputsFrom (armnn::Layer *layer, std::vector< unsigned int > ignoreSlots={})
armnn::SubgraphView::InputSlots CreateInputsFrom (const std::vector< armnn::Layer *> &layers, std::vector< unsigned int > ignoreSlots={})
armnn::SubgraphView::OutputSlots CreateOutputsFrom (const std::vector< armnn::Layer *> &layers)
armnn::SubgraphView::SubgraphViewPtr CreateSubgraphViewFrom (armnn::SubgraphView::InputSlots &&inputs, armnn::SubgraphView::OutputSlots &&outputs, armnn::SubgraphView::Layers &&layers)
armnn::IBackendInternalUniquePtr CreateBackendObject (const armnn::BackendId &backendId)
armnn::TensorShape MakeTensorShape (unsigned int batches, unsigned int channels, unsigned int height, unsigned int width, armnn::DataLayout layout)
Function Documentation
AreEqual()
bool AreEqual (const CollectionType & lhs, const CollectionType & rhs)
Definition at line 27 of file CommonTestUtils.hpp.
 {
     if (lhs.size() != rhs.size())
     {
         return false;
     }
     auto lhs_it = std::find_if(lhs.begin(), lhs.end(), [&rhs](auto& item)
     {
         return std::find(rhs.begin(), rhs.end(), item) == rhs.end();
     });
     return lhs_it == lhs.end();
 }
Compare()
bool Compare (T a, T b, float tolerance = 0.000001f) inline
Definition at line 58 of file CommonTestUtils.hpp.
References armnn::Boolean.
 {
     if (ArmnnType == armnn::DataType::Boolean)
     {
         // NOTE: Boolean is represented as uint8_t (with zero equals
         // false and everything else equals true), therefore values
         // need to be casted to bool before comparing them
         return static_cast<bool>(a) == static_cast<bool>(b);
     }
     // NOTE: All other types can be cast to float and compared with
     // a certain level of tolerance
     return std::fabs(static_cast<float>(a) - static_cast<float>(b)) <= tolerance;
 }
Contains() [1/2]
bool Contains (const CollectionType & collection, const typename CollectionType::value_type & item)
Definition at line 44 of file CommonTestUtils.hpp.
 {
     return std::find(collection.begin(), collection.end(), item) != collection.end();
 }
Contains() [2/2]
bool Contains (const MapType & map, const typename MapType::key_type & key)
Definition at line 51 of file CommonTestUtils.hpp.
 {
     return map.find(key) != map.end();
 }
CreateBackendObject()
armnn::IBackendInternalUniquePtr CreateBackendObject (const armnn::BackendId & backendId)
Definition at line 72 of file CommonTestUtils.cpp.
References armnn::BackendRegistryInstance().
Referenced by SetWeightAndBias(), and TEST_SUITE().
 {
     auto& backendRegistry = BackendRegistryInstance();
     auto  backendFactory  = backendRegistry.GetFactory(backendId);
     auto  backendObjPtr   = backendFactory();
     return backendObjPtr;
 }
CreateInputsFrom() [1/2]
armnn::SubgraphView::InputSlots CreateInputsFrom (armnn::Layer * layer, std::vector< unsigned int > ignoreSlots = {})
Definition at line 12 of file CommonTestUtils.cpp.
References Layer::BeginInputSlots(), and Layer::EndInputSlots().
Referenced by SetWeightAndBias(), and TEST_SUITE().
 {
     SubgraphView::InputSlots result;
     for (auto&& it = layer->BeginInputSlots(); it != layer->EndInputSlots(); ++it)
     {
         if (std::find(ignoreSlots.begin(), ignoreSlots.end(), it->GetSlotIndex()) != ignoreSlots.end())
         {
             continue;
         }
         else
         {
             result.push_back(&(*it));
         }
     }
         return result;
 }
CreateInputsFrom() [2/2]
armnn::SubgraphView::InputSlots CreateInputsFrom (const std::vector< armnn::Layer *> & layers, std::vector< unsigned int > ignoreSlots = {})
Definition at line 31 of file CommonTestUtils.cpp.
 {
     SubgraphView::InputSlots result;
     for (auto&& layer: layers)
     {
         for (auto&& it = layer->BeginInputSlots(); it != layer->EndInputSlots(); ++it)
         {
             if (std::find(ignoreSlots.begin(), ignoreSlots.end(), it->GetSlotIndex()) != ignoreSlots.end())
             {
                 continue;
             }
             else
             {
                 result.push_back(&(*it));
             }
         }
     }
     return result;
 }
CreateOutputsFrom()
armnn::SubgraphView::OutputSlots CreateOutputsFrom (const std::vector< armnn::Layer *> & layers)
Definition at line 52 of file CommonTestUtils.cpp.
Referenced by SetWeightAndBias(), and TEST_SUITE().
 {
     SubgraphView::OutputSlots result;
     for (auto && layer : layers)
     {
         for (auto&& it = layer->BeginOutputSlots(); it != layer->EndOutputSlots(); ++it)
         {
             result.push_back(&(*it));
         }
     }
     return result;
 }
CreateSubgraphViewFrom()
armnn::SubgraphView::SubgraphViewPtr CreateSubgraphViewFrom (armnn::SubgraphView::InputSlots && inputs, armnn::SubgraphView::OutputSlots && outputs, armnn::SubgraphView::Layers && layers)
Definition at line 65 of file CommonTestUtils.cpp.
Referenced by SetWeightAndBias(), and TEST_SUITE().
 {
     return std::make_unique<SubgraphView>(std::move(inputs), std::move(outputs), std::move(layers));
 }
MakeTensorShape()
armnn::TensorShape MakeTensorShape (unsigned int batches, unsigned int channels, unsigned int height, unsigned int width, armnn::DataLayout layout)
Definition at line 81 of file CommonTestUtils.cpp.
References armnn::GetDataLayoutName(), armnn::NCHW, and armnn::NHWC.
Referenced by SetWeightAndBias(), and TransposeConvolution2dEndToEnd().
 {
     using namespace armnn;
     switch (layout)
     {
         case DataLayout::NCHW:
             return TensorShape{ batches, channels, height, width };
         case DataLayout::NHWC:
             return TensorShape{ batches, height, width, channels };
         default:
             throw InvalidArgumentException(std::string("Unsupported data layout: ") + GetDataLayoutName(layout));
     }
 }
SetWeightAndBias()
void SetWeightAndBias (ConvolutionLayer * layer, const armnn::TensorInfo & weightInfo, const armnn::TensorInfo & biasInfo)
Definition at line 74 of file CommonTestUtils.hpp.
References CreateBackendObject(), CreateInputsFrom(), CreateOutputsFrom(), CreateSubgraphViewFrom(), and MakeTensorShape().
 {
     layer->m_Weight = std::make_unique<armnn::ScopedTensorHandle>(weightInfo);
     layer->m_Bias   = std::make_unique<armnn::ScopedTensorHandle>(biasInfo);
     layer->m_Weight->Allocate();
     layer->m_Bias->Allocate();
 }