ArmNN: ClImportTensorHandleFactory Class Reference
ClImportTensorHandleFactory Class Reference
This factory creates ClImportTensorHandles that refer to imported memory tensors.
#include <ClImportTensorHandleFactory.hpp>
Public Member Functions
ClImportTensorHandleFactory (MemorySourceFlags importFlags, MemorySourceFlags exportFlags)
Create a tensor handle factory for tensors that will be imported or exported.
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, const TensorShape &subTensorShape, const unsigned int *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const override
Utility Functions for backends which require TensorHandles to have unmanaged memory.
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override
const FactoryId & GetId () const override
bool SupportsSubTensors () const override
bool SupportsMapUnmap () const override
MemorySourceFlags GetExportFlags () const override
MemorySourceFlags GetImportFlags () const override
std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass) override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual bool SupportsInPlaceComputation () const
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Static Public Attributes
static const FactoryId m_Id
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Detailed Description
This factory creates ClImportTensorHandles that refer to imported memory tensors.
Definition at line 23 of file ClImportTensorHandleFactory.hpp.
Constructor & Destructor Documentation
ClImportTensorHandleFactory()
ClImportTensorHandleFactory (MemorySourceFlags importFlags, MemorySourceFlags exportFlags) inline
Create a tensor handle factory for tensors that will be imported or exported.
Parameters
importFlags
exportFlags
Definition at line 34 of file ClImportTensorHandleFactory.hpp.
References ClImportTensorHandleFactory::CreateSubTensorHandle(), ClImportTensorHandleFactory::CreateTensorHandle(), ClImportTensorHandleFactory::GetCapabilities(), ClImportTensorHandleFactory::GetExportFlags(), ClImportTensorHandleFactory::GetId(), ClImportTensorHandleFactory::GetIdStatic(), ClImportTensorHandleFactory::GetImportFlags(), ClImportTensorHandleFactory::SupportsMapUnmap(), and ClImportTensorHandleFactory::SupportsSubTensors().
         : m_ImportFlags(importFlags)
         , m_ExportFlags(exportFlags)
     {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, const TensorShape & subTensorShape, const unsigned int * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 20 of file ClImportTensorHandleFactory.cpp.
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory(), and TEST_SUITE().
 {
     arm_compute::Coordinates coords;
     arm_compute::TensorShape shape = armcomputetensorutils::BuildArmComputeTensorShape(subTensorShape);
     coords.set_num_dimensions(subTensorShape.GetNumDimensions());
     for (unsigned int i = 0; i < subTensorShape.GetNumDimensions(); ++i)
     {
         // Arm compute indexes tensor coords in reverse order.
         unsigned int revertedIndex = subTensorShape.GetNumDimensions() - i - 1;
         coords.set(i, armnn::numeric_cast<int>(subTensorOrigin[revertedIndex]));
     }
     const arm_compute::TensorShape parentShape = armcomputetensorutils::BuildArmComputeTensorShape(parent.GetShape());
     // In order for ACL to support subtensors the concat axis cannot be on x or y and the values of x and y
     // must match the parent shapes
     if (coords.x() != 0 || coords.y() != 0)
     {
         return nullptr;
     }
     if ((parentShape.x() != shape.x()) || (parentShape.y() != shape.y()))
     {
         return nullptr;
     }
     if (!::arm_compute::error_on_invalid_subtensor(__func__, __FILE__, __LINE__, parentShape, coords, shape))
     {
         return nullptr;
     }
     return std::make_unique<ClImportSubTensorHandle>(
         PolymorphicDowncast<IClTensorHandle*>(&parent), shape, coords);
 }
CreateTensorHandle() [1/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 56 of file ClImportTensorHandleFactory.cpp.
References ClImportTensorHandleFactory::GetImportFlags().
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory(), ClImportTensorHandleFactory::CreateTensorHandle(), and TEST_SUITE().
 {
     std::unique_ptr<ClImportTensorHandle> tensorHandle = std::make_unique<ClImportTensorHandle>(tensorInfo,
                                                                                                 GetImportFlags());
     return tensorHandle;
 }
CreateTensorHandle() [2/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 63 of file ClImportTensorHandleFactory.cpp.
References ClImportTensorHandleFactory::GetImportFlags().
 {
     std::unique_ptr<ClImportTensorHandle> tensorHandle = std::make_unique<ClImportTensorHandle>(tensorInfo,
                                                                                                 dataLayout,
                                                                                                 GetImportFlags());
     return tensorHandle;
 }
CreateTensorHandle() [3/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged) const override virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented from ITensorHandleFactory.
Definition at line 72 of file ClImportTensorHandleFactory.cpp.
References ClImportTensorHandleFactory::CreateTensorHandle().
 {
     if (IsMemoryManaged)
     {
         throw InvalidArgumentException("ClImportTensorHandleFactory does not support memory managed tensors.");
     }
     return CreateTensorHandle(tensorInfo);
 }
CreateTensorHandle() [4/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 82 of file ClImportTensorHandleFactory.cpp.
References ClImportTensorHandleFactory::CreateTensorHandle().
 {
     if (IsMemoryManaged)
     {
         throw InvalidArgumentException("ClImportTensorHandleFactory does not support memory managed tensors.");
     }
     return CreateTensorHandle(tensorInfo, dataLayout);
 }
GetCapabilities()
std::vector< Capability > GetCapabilities (const IConnectableLayer * layer, const IConnectableLayer * connectedLayer, CapabilityClass capabilityClass) override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 124 of file ClImportTensorHandleFactory.cpp.
References armnn::FallbackImportDisabled, and armnn::IgnoreUnused().
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory().
 {
     IgnoreUnused(layer);
     IgnoreUnused(connectedLayer);
     std::vector<Capability> capabilities;
     if (capabilityClass == CapabilityClass::FallbackImportDisabled)
     {
         Capability paddingCapability(CapabilityClass::FallbackImportDisabled, true);
         capabilities.push_back(paddingCapability);
     }
     return capabilities;
 }
GetExportFlags()
MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 114 of file ClImportTensorHandleFactory.cpp.
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory().
 {
     return m_ExportFlags;
 }
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 99 of file ClImportTensorHandleFactory.cpp.
References ClImportTensorHandleFactory::GetIdStatic().
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory().
 {
     return GetIdStatic();
 }
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 93 of file ClImportTensorHandleFactory.cpp.
References armnn::ClImportTensorHandleFactoryId().
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory(), ClBackend::GetHandleFactoryPreferences(), ClImportTensorHandleFactory::GetId(), and TEST_SUITE().
 {
     static const FactoryId s_Id(ClImportTensorHandleFactoryId());
     return s_Id;
 }
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 119 of file ClImportTensorHandleFactory.cpp.
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory(), and ClImportTensorHandleFactory::CreateTensorHandle().
 {
     return m_ImportFlags;
 }
SupportsMapUnmap()
bool SupportsMapUnmap () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 109 of file ClImportTensorHandleFactory.cpp.
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory().
 {
     return false;
 }
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 104 of file ClImportTensorHandleFactory.cpp.
Referenced by ClImportTensorHandleFactory::ClImportTensorHandleFactory().
 {
     return true;
 }
Member Data Documentation
m_Id
const FactoryId m_Id static
Definition at line 26 of file ClImportTensorHandleFactory.hpp.
The documentation for this class was generated from the following files:
src/backends/cl/ClImportTensorHandleFactory.hpp
src/backends/cl/ClImportTensorHandleFactory.cpp