ArmNN: MockImportBackendInitialiser Class Reference
MockImportBackendInitialiser Class Reference
#include <MockImportBackend.hpp>
Public Member Functions
MockImportBackendInitialiser ()
~MockImportBackendInitialiser ()
Detailed Description
Definition at line 14 of file MockImportBackend.hpp.
Constructor & Destructor Documentation
MockImportBackendInitialiser()
MockImportBackendInitialiser ()
Definition at line 22 of file MockImportBackend.cpp.
References armnn::BackendRegistryInstance(), MockImportBackend::GetIdStatic(), and BackendRegistry::Register().
 {
     BackendRegistryInstance().Register(MockImportBackend::GetIdStatic(),
                                        []()
{
                                            return IBackendInternalUniquePtr(new MockImportBackend);
                                        });
 }
~MockImportBackendInitialiser()
~MockImportBackendInitialiser ()
Definition at line 31 of file MockImportBackend.cpp.
References armnn::BackendRegistryInstance(), BackendRegistry::Deregister(), and MockImportBackend::GetIdStatic().
 {
     try
     {
         BackendRegistryInstance().Deregister(MockImportBackend::GetIdStatic());
     }
     catch (...)
     {
         std::cerr << "could not deregister mock import backend" << std::endl;
     }
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/test/mockBackend/MockImportBackend.hpp
src/backends/backendsCommon/test/mockBackend/MockImportBackend.cpp