ArmNN: LstmLayer Class Reference
LstmLayer Class Reference
This layer represents a LSTM operation.
#include <LstmLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the LSTM type.
LstmLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of LstmLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
ARMNN_NO_DEPRECATE_WARN_BEGIN void Accept (ILayerVisitor &visitor) const override
ARMNN_NO_DEPRECATE_WARN_END void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Public Member Functions inherited from LayerWithParameters< LstmDescriptor >
const LstmDescriptor & GetParameters () const override
If the layer has a descriptor return it.
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T >
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
Public Member Functions inherited from IConnectableLayer
ARMNN_NO_DEPRECATE_WARN_BEGIN ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("Accept is deprecated. The ILayerVisitor that works in conjunction with this " "Accept function is deprecated. Use IStrategy in combination with " "ExecuteStrategy instead, which is an ABI/API stable version of the " "visitor pattern.", "22.05") virtual void Accept(ILayerVisitor &visitor) const =0
Apply a visitor to this layer.
Public Attributes
LstmBasicParameters m_BasicParameters
LstmOptCifgParameters m_CifgParameters
LstmOptProjectionParameters m_ProjectionParameters
LstmOptPeepholeParameters m_PeepholeParameters
LstmOptLayerNormParameters m_LayerNormParameters
Protected Member Functions
LstmLayer (const LstmDescriptor &param, const char *name)
Constructor to create a LstmLayer.
~LstmLayer ()=default
Default destructor.
Layer::ConstantTensors GetConstantTensorsByRef () override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from LayerWithParameters< LstmDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const LstmDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< LstmDescriptor >
using DescriptorType = LstmDescriptor
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector< std::reference_wrapper< std::shared_ptr< ConstTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< LstmDescriptor >
LstmDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a LSTM operation.
Definition at line 16 of file LstmLayer.hpp.
Constructor & Destructor Documentation
LstmLayer()
LstmLayer (const LstmDescriptor & param, const char * name) protected
Constructor to create a LstmLayer.
Parameters
[in] param LstmDescriptor to configure the lstm operation.
[in] name Optional name for the layer.
Definition at line 17 of file LstmLayer.cpp.
References armnn::Lstm.
         : LayerWithParameters(3, 4, LayerType::Lstm, param, name)
 {
 }
~LstmLayer()
~LstmLayer () protected default
Default destructor.
Member Function Documentation
Accept()
ARMNN_NO_DEPRECATE_WARN_BEGIN void Accept (ILayerVisitor & visitor) const override
Definition at line 305 of file LstmLayer.cpp.
References ARMNN_NO_DEPRECATE_WARN_END, Layer::GetName(), LayerWithParameters< LstmDescriptor >::GetParameters(), ManagedConstTensorHandle::GetTensorInfo(), LstmLayer::m_BasicParameters, LstmInputParams::m_CellBias, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmLayer::m_CifgParameters, LstmInputParams::m_ForgetGateBias, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmInputParams::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmInputParams::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmInputParams::m_InputLayerNormWeights, LstmInputParams::m_InputToCellWeights, LstmBasicParameters::m_InputToCellWeights, LstmInputParams::m_InputToForgetWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmLayer::m_LayerNormParameters, LstmInputParams::m_OutputGateBias, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LstmInputParams::m_OutputLayerNormWeights, LstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmInputParams::m_ProjectionBias, LstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToOutputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, and ManagedConstTensorHandle::Map().
 {
     LstmInputParams inputParams;
     ManagedConstTensorHandle managedInputToForgetWeights(m_BasicParameters.m_InputToForgetWeights);
     ManagedConstTensorHandle managedInputToCellWeights(m_BasicParameters.m_InputToCellWeights);
     ManagedConstTensorHandle managedInputToOutputWeights(m_BasicParameters.m_InputToOutputWeights);
     ManagedConstTensorHandle managedRecurrentToForgetWeights(m_BasicParameters.m_RecurrentToForgetWeights);
     ManagedConstTensorHandle managedRecurrentToCellWeights(m_BasicParameters.m_RecurrentToCellWeights);
     ManagedConstTensorHandle managedRecurrentToOutputWeights(m_BasicParameters.m_RecurrentToOutputWeights);
     ManagedConstTensorHandle managedForgetGateBias(m_BasicParameters.m_ForgetGateBias);
     ManagedConstTensorHandle managedCellBias(m_BasicParameters.m_CellBias);
     ManagedConstTensorHandle managedOutputGateBias(m_BasicParameters.m_OutputGateBias);
     // Cifg parameters
     ManagedConstTensorHandle managedInputToInputWeights(m_CifgParameters.m_InputToInputWeights);
     ManagedConstTensorHandle managedRecurrentToInputWeights(m_CifgParameters.m_RecurrentToInputWeights);
     ManagedConstTensorHandle managedInputGateBias(m_CifgParameters.m_InputGateBias);
     // Projection parameters
     ManagedConstTensorHandle managedProjectionWeights(m_ProjectionParameters.m_ProjectionWeights);
     ManagedConstTensorHandle managedProjectionBias(m_ProjectionParameters.m_ProjectionBias);
     // Peephole parameters
     ManagedConstTensorHandle managedCellToInputWeights(m_PeepholeParameters.m_CellToInputWeights);
     ManagedConstTensorHandle managedCellToForgetWeights(m_PeepholeParameters.m_CellToForgetWeights);
     ManagedConstTensorHandle managedCellToOutputWeights(m_PeepholeParameters.m_CellToOutputWeights);
     // Layer normalisation parameters
     ManagedConstTensorHandle managedInputLayerNormWeights(m_LayerNormParameters.m_InputLayerNormWeights);
     ManagedConstTensorHandle managedForgetLayerNormWeights(m_LayerNormParameters.m_ForgetLayerNormWeights);
     ManagedConstTensorHandle managedCellLayerNormWeights(m_LayerNormParameters.m_CellLayerNormWeights);
     ManagedConstTensorHandle managedOutputLayerNormWeights(m_LayerNormParameters.m_OutputLayerNormWeights);
     ConstTensor inputToInputWeightsTensor;
     if (m_CifgParameters.m_InputToInputWeights != nullptr)
     {
         ConstTensor inputToInputWeightsTensorCopy(managedInputToInputWeights.GetTensorInfo(),
                                                   managedInputToInputWeights.Map());
         inputToInputWeightsTensor = inputToInputWeightsTensorCopy;
         inputParams.m_InputToInputWeights = &inputToInputWeightsTensor;
     }
     ConstTensor inputToForgetWeightsTensor;
     if (m_BasicParameters.m_InputToForgetWeights != nullptr)
     {
         ConstTensor inputToForgetWeightsTensorCopy(managedInputToForgetWeights.GetTensorInfo(),
                                                    managedInputToForgetWeights.Map());
         inputToForgetWeightsTensor = inputToForgetWeightsTensorCopy;
         inputParams.m_InputToForgetWeights = &inputToForgetWeightsTensor;
     }
     ConstTensor inputToCellWeightsTensor;
     if (m_BasicParameters.m_InputToCellWeights != nullptr)
     {
         ConstTensor inputToCellWeightsTensorCopy(managedInputToCellWeights.GetTensorInfo(),
                                                  managedInputToCellWeights.Map());
         inputToCellWeightsTensor = inputToCellWeightsTensorCopy;
         inputParams.m_InputToCellWeights = &inputToCellWeightsTensor;
     }
     ConstTensor inputToOutputWeightsTensor;
     if (m_BasicParameters.m_InputToOutputWeights != nullptr)
     {
         ConstTensor inputToOutputWeightsTensorCopy(managedInputToOutputWeights.GetTensorInfo(),
                                                    managedInputToOutputWeights.Map());
         inputToOutputWeightsTensor = inputToOutputWeightsTensorCopy;
         inputParams.m_InputToOutputWeights = &inputToOutputWeightsTensor;
     }
     ConstTensor recurrentToInputWeightsTensor;
     if (m_CifgParameters.m_RecurrentToInputWeights != nullptr)
     {
         ConstTensor recurrentToInputWeightsTensorCopy(
                 managedRecurrentToInputWeights.GetTensorInfo(),
                 managedRecurrentToInputWeights.Map());
         recurrentToInputWeightsTensor = recurrentToInputWeightsTensorCopy;
         inputParams.m_RecurrentToInputWeights = &recurrentToInputWeightsTensor;
     }
     ConstTensor recurrentToForgetWeightsTensor;
     if (m_BasicParameters.m_RecurrentToForgetWeights != nullptr)
     {
         ConstTensor recurrentToForgetWeightsTensorCopy(
                 managedRecurrentToForgetWeights.GetTensorInfo(),
                 managedRecurrentToForgetWeights.Map());
         recurrentToForgetWeightsTensor = recurrentToForgetWeightsTensorCopy;
         inputParams.m_RecurrentToForgetWeights = &recurrentToForgetWeightsTensor;
     }
     ConstTensor recurrentToCellWeightsTensor;
     if (m_BasicParameters.m_RecurrentToCellWeights != nullptr)
     {
         ConstTensor recurrentToCellWeightsTensorCopy(
                 managedRecurrentToCellWeights.GetTensorInfo(),
                 managedRecurrentToCellWeights.Map());
         recurrentToCellWeightsTensor = recurrentToCellWeightsTensorCopy;
         inputParams.m_RecurrentToCellWeights = &recurrentToCellWeightsTensor;
     }
     ConstTensor recurrentToOutputWeightsTensor;
     if (m_BasicParameters.m_RecurrentToOutputWeights != nullptr)
     {
         ConstTensor recurrentToOutputWeightsTensorCopy(
                 managedRecurrentToOutputWeights.GetTensorInfo(),
                 managedRecurrentToOutputWeights.Map());
         recurrentToOutputWeightsTensor = recurrentToOutputWeightsTensorCopy;
         inputParams.m_RecurrentToOutputWeights = &recurrentToOutputWeightsTensor;
     }
     ConstTensor cellToInputWeightsTensor;
     if (m_PeepholeParameters.m_CellToInputWeights != nullptr)
     {
         ConstTensor cellToInputWeightsTensorCopy(managedCellToInputWeights.GetTensorInfo(),
                                                  managedCellToInputWeights.Map());
         cellToInputWeightsTensor = cellToInputWeightsTensorCopy;
         inputParams.m_CellToInputWeights = &cellToInputWeightsTensor;
     }
     ConstTensor cellToForgetWeightsTensor;
     if (m_PeepholeParameters.m_CellToForgetWeights != nullptr)
     {
         ConstTensor cellToForgetWeightsTensorCopy(managedCellToForgetWeights.GetTensorInfo(),
                                                   managedCellToForgetWeights.Map());
         cellToForgetWeightsTensor = cellToForgetWeightsTensorCopy;
         inputParams.m_CellToForgetWeights = &cellToForgetWeightsTensor;
     }
     ConstTensor cellToOutputWeightsTensor;
     if (m_PeepholeParameters.m_CellToOutputWeights != nullptr)
     {
         ConstTensor cellToOutputWeightsTensorCopy(managedCellToOutputWeights.GetTensorInfo(),
                                                   managedCellToOutputWeights.Map());
         cellToOutputWeightsTensor = cellToOutputWeightsTensorCopy;
         inputParams.m_CellToOutputWeights = &cellToOutputWeightsTensor;
     }
     ConstTensor inputGateBiasTensor;
     if (m_CifgParameters.m_InputGateBias != nullptr)
     {
         ConstTensor inputGateBiasTensorCopy(managedInputGateBias.GetTensorInfo(),
                                         managedInputGateBias.Map());
         inputGateBiasTensor = inputGateBiasTensorCopy;
         inputParams.m_InputGateBias = &inputGateBiasTensor;
     }
     ConstTensor forgetGateBiasTensor;
     if (m_BasicParameters.m_ForgetGateBias != nullptr)
     {
         ConstTensor forgetGateBiasTensorCopy(managedForgetGateBias.GetTensorInfo(),
                                              managedForgetGateBias.Map());
         forgetGateBiasTensor = forgetGateBiasTensorCopy;
         inputParams.m_ForgetGateBias = &forgetGateBiasTensor;
     }
     ConstTensor cellBiasTensor;
     if (m_BasicParameters.m_CellBias != nullptr)
     {
         ConstTensor cellBiasTensorCopy(managedCellBias.GetTensorInfo(),
                                        managedCellBias.Map());
         cellBiasTensor = cellBiasTensorCopy;
         inputParams.m_CellBias = &cellBiasTensor;
     }
     ConstTensor outputGateBias;
     if (m_BasicParameters.m_OutputGateBias != nullptr)
     {
         ConstTensor outputGateBiasCopy(managedOutputGateBias.GetTensorInfo(),
                                        managedOutputGateBias.Map());
         outputGateBias = outputGateBiasCopy;
         inputParams.m_OutputGateBias = &outputGateBias;
     }
     ConstTensor projectionWeightsTensor;
     if (m_ProjectionParameters.m_ProjectionWeights != nullptr)
     {
         ConstTensor projectionWeightsTensorCopy(managedProjectionWeights.GetTensorInfo(),
                                                 managedProjectionWeights.Map());
         projectionWeightsTensor = projectionWeightsTensorCopy;
         inputParams.m_ProjectionWeights = &projectionWeightsTensor;
     }
     ConstTensor projectionBiasTensor;
     if (m_ProjectionParameters.m_ProjectionBias != nullptr)
     {
         ConstTensor projectionBiasTensorCopy(managedProjectionBias.GetTensorInfo(),
                                              managedProjectionBias.Map());
         projectionBiasTensor = projectionBiasTensorCopy;
         inputParams.m_ProjectionBias = &projectionBiasTensor;
     }
     ConstTensor inputLayerNormTensor;
     if (m_LayerNormParameters.m_InputLayerNormWeights != nullptr)
     {
         ConstTensor inputLayerNormTensorCopy(managedInputLayerNormWeights.GetTensorInfo(),
                                              managedInputLayerNormWeights.Map());
         inputLayerNormTensor = inputLayerNormTensorCopy;
         inputParams.m_InputLayerNormWeights = &inputLayerNormTensor;
     }
     ConstTensor forgetLayerNormTensor;
     if (m_LayerNormParameters.m_ForgetLayerNormWeights != nullptr)
     {
         ConstTensor forgetLayerNormTensorCopy(managedForgetLayerNormWeights.GetTensorInfo(),
                                              managedForgetLayerNormWeights.Map());
         forgetLayerNormTensor = forgetLayerNormTensorCopy;
         inputParams.m_ForgetLayerNormWeights = &forgetLayerNormTensor;
     }
     ConstTensor cellLayerNormTensor;
     if (m_LayerNormParameters.m_CellLayerNormWeights != nullptr)
     {
         ConstTensor cellLayerNormTensorCopy(managedCellLayerNormWeights.GetTensorInfo(),
                                               managedCellLayerNormWeights.Map());
         cellLayerNormTensor = cellLayerNormTensorCopy;
         inputParams.m_CellLayerNormWeights = &cellLayerNormTensor;
     }
     ConstTensor outputLayerNormTensor;
     if (m_LayerNormParameters.m_OutputLayerNormWeights != nullptr)
     {
         ConstTensor outputLayerNormTensorCopy(managedOutputLayerNormWeights.GetTensorInfo(),
                                             managedOutputLayerNormWeights.Map());
         outputLayerNormTensor = outputLayerNormTensorCopy;
         inputParams.m_OutputLayerNormWeights = &outputLayerNormTensor;
     }
     visitor.VisitLstmLayer(this, GetParameters(), inputParams, GetName());
 }
Clone()
LstmLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 80 of file LstmLayer.cpp.
References Layer::GetName(), LstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LayerWithParameters< LstmDescriptor >::m_Param, LstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, and LstmBasicParameters::m_RecurrentToOutputWeights.
 {
     auto layer = CloneBase<LstmLayer>(graph, m_Param, GetName());
     layer->m_BasicParameters.m_InputToForgetWeights = m_BasicParameters.m_InputToForgetWeights ?
             m_BasicParameters.m_InputToForgetWeights
                 : nullptr;
     layer->m_BasicParameters.m_InputToCellWeights = m_BasicParameters.m_InputToCellWeights ?
             m_BasicParameters.m_InputToCellWeights : nullptr;
     layer->m_BasicParameters.m_InputToOutputWeights = m_BasicParameters.m_InputToOutputWeights ?
             m_BasicParameters.m_InputToOutputWeights : nullptr;
     layer->m_BasicParameters.m_RecurrentToForgetWeights = m_BasicParameters.m_RecurrentToForgetWeights ?
             m_BasicParameters.m_RecurrentToForgetWeights : nullptr;
     layer->m_BasicParameters.m_RecurrentToCellWeights = m_BasicParameters.m_RecurrentToCellWeights ?
             m_BasicParameters.m_RecurrentToCellWeights : nullptr;
     layer->m_BasicParameters.m_RecurrentToOutputWeights = m_BasicParameters.m_RecurrentToOutputWeights ?
             m_BasicParameters.m_RecurrentToOutputWeights : nullptr;
     layer->m_BasicParameters.m_ForgetGateBias = m_BasicParameters.m_ForgetGateBias ?
             m_BasicParameters.m_ForgetGateBias : nullptr;
     layer->m_BasicParameters.m_CellBias = m_BasicParameters.m_CellBias ?
             m_BasicParameters.m_CellBias : nullptr;
     layer->m_BasicParameters.m_OutputGateBias = m_BasicParameters.m_OutputGateBias ?
             m_BasicParameters.m_OutputGateBias : nullptr;
     if (!m_Param.m_CifgEnabled)
     {
         layer->m_CifgParameters.m_InputToInputWeights = m_CifgParameters.m_InputToInputWeights ?
                 m_CifgParameters.m_InputToInputWeights : nullptr;
         layer->m_CifgParameters.m_RecurrentToInputWeights = m_CifgParameters.m_RecurrentToInputWeights ?
                 m_CifgParameters.m_RecurrentToInputWeights : nullptr;
         layer->m_CifgParameters.m_InputGateBias = m_CifgParameters.m_InputGateBias ?
                 m_CifgParameters.m_InputGateBias : nullptr;
     }
     if (m_Param.m_ProjectionEnabled)
     {
         layer->m_ProjectionParameters.m_ProjectionWeights = m_ProjectionParameters.m_ProjectionWeights ?
                m_ProjectionParameters.m_ProjectionWeights : nullptr;
         layer->m_ProjectionParameters.m_ProjectionBias = m_ProjectionParameters.m_ProjectionBias ?
                m_ProjectionParameters.m_ProjectionBias : nullptr;
     }
     if (m_Param.m_PeepholeEnabled)
     {
         if (!m_Param.m_CifgEnabled)
         {
             layer->m_PeepholeParameters.m_CellToInputWeights = m_PeepholeParameters.m_CellToInputWeights ?
                 m_PeepholeParameters.m_CellToInputWeights : nullptr;
         }
         layer->m_PeepholeParameters.m_CellToForgetWeights = m_PeepholeParameters.m_CellToForgetWeights ?
                m_PeepholeParameters.m_CellToForgetWeights : nullptr;
         layer->m_PeepholeParameters.m_CellToOutputWeights = m_PeepholeParameters.m_CellToOutputWeights ?
                m_PeepholeParameters.m_CellToOutputWeights : nullptr;
     }
     if (m_Param.m_LayerNormEnabled)
     {
         layer->m_LayerNormParameters.m_InputLayerNormWeights = m_LayerNormParameters.m_InputLayerNormWeights ?
                m_LayerNormParameters.m_InputLayerNormWeights : nullptr;
         layer->m_LayerNormParameters.m_ForgetLayerNormWeights = m_LayerNormParameters.m_ForgetLayerNormWeights ?
                m_LayerNormParameters.m_ForgetLayerNormWeights : nullptr;
         layer->m_LayerNormParameters.m_CellLayerNormWeights = m_LayerNormParameters.m_CellLayerNormWeights ?
                m_LayerNormParameters.m_CellLayerNormWeights : nullptr;
         layer->m_LayerNormParameters.m_OutputLayerNormWeights = m_LayerNormParameters.m_OutputLayerNormWeights ?
                m_LayerNormParameters.m_OutputLayerNormWeights : nullptr;
     }
     return std::move(layer);
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the LSTM type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 22 of file LstmLayer.cpp.
References IWorkloadFactory::CreateWorkload(), armnn::Lstm, LstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmQueueDescriptor::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmQueueDescriptor::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmQueueDescriptor::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmQueueDescriptor::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmQueueDescriptor::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, LstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmQueueDescriptor::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmQueueDescriptor::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmQueueDescriptor::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmQueueDescriptor::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmQueueDescriptor::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmQueueDescriptor::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmQueueDescriptor::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmQueueDescriptor::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, LstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmQueueDescriptor::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LstmQueueDescriptor::m_OutputLayerNormWeights, LayerWithParameters< LstmDescriptor >::m_Param, LstmDescriptor::m_PeepholeEnabled, LstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmQueueDescriptor::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, LstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmQueueDescriptor::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmQueueDescriptor::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmQueueDescriptor::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, LstmQueueDescriptor::m_RecurrentToInputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, LstmQueueDescriptor::m_RecurrentToOutputWeights, LayerWithParameters< LstmDescriptor >::PrepInfoAndDesc(), and Layer::SetAdditionalInfo().
 {
     LstmQueueDescriptor descriptor;
     // Basic parameters
     descriptor.m_InputToForgetWeights = m_BasicParameters.m_InputToForgetWeights.get();
     descriptor.m_InputToCellWeights = m_BasicParameters.m_InputToCellWeights.get();
     descriptor.m_InputToOutputWeights = m_BasicParameters.m_InputToOutputWeights.get();
     descriptor.m_RecurrentToForgetWeights = m_BasicParameters.m_RecurrentToForgetWeights.get();
     descriptor.m_RecurrentToCellWeights = m_BasicParameters.m_RecurrentToCellWeights.get();
     descriptor.m_RecurrentToOutputWeights = m_BasicParameters.m_RecurrentToOutputWeights.get();
     descriptor.m_ForgetGateBias = m_BasicParameters.m_ForgetGateBias.get();
     descriptor.m_CellBias = m_BasicParameters.m_CellBias.get();
     descriptor.m_OutputGateBias = m_BasicParameters.m_OutputGateBias.get();
     // Cifg parameters
     if (!m_Param.m_CifgEnabled)
     {
         descriptor.m_InputToInputWeights = m_CifgParameters.m_InputToInputWeights.get();
         descriptor.m_RecurrentToInputWeights = m_CifgParameters.m_RecurrentToInputWeights.get();
         descriptor.m_InputGateBias = m_CifgParameters.m_InputGateBias.get();
     }
     // Projection parameters
     if (m_Param.m_ProjectionEnabled)
     {
         descriptor.m_ProjectionWeights = m_ProjectionParameters.m_ProjectionWeights.get();
         descriptor.m_ProjectionBias    = m_ProjectionParameters.m_ProjectionBias.get();
     }
     // Peephole parameters
     if (m_Param.m_PeepholeEnabled)
     {
         if (!m_Param.m_CifgEnabled)
         {
             descriptor.m_CellToInputWeights = m_PeepholeParameters.m_CellToInputWeights.get();
         }
         descriptor.m_CellToForgetWeights = m_PeepholeParameters.m_CellToForgetWeights.get();
         descriptor.m_CellToOutputWeights = m_PeepholeParameters.m_CellToOutputWeights.get();
     }
     // Layer normalisation parameters
     if(m_Param.m_LayerNormEnabled)
     {
         if (!m_Param.m_CifgEnabled)
         {
             descriptor.m_InputLayerNormWeights = m_LayerNormParameters.m_InputLayerNormWeights.get();
         }
         descriptor.m_ForgetLayerNormWeights = m_LayerNormParameters.m_ForgetLayerNormWeights.get();
         descriptor.m_CellLayerNormWeights = m_LayerNormParameters.m_CellLayerNormWeights.get();
         descriptor.m_OutputLayerNormWeights = m_LayerNormParameters.m_OutputLayerNormWeights.get();
     }
     SetAdditionalInfo(descriptor);
     return factory.CreateWorkload(LayerType::Lstm, descriptor, PrepInfoAndDesc(descriptor));
 }
ExecuteStrategy()
ARMNN_NO_DEPRECATE_WARN_END void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Reimplemented from Layer.
Definition at line 516 of file LstmLayer.cpp.
References IStrategy::ExecuteStrategy(), Layer::GetName(), LayerWithParameters< LstmDescriptor >::GetParameters(), ManagedConstTensorHandle::GetTensorInfo(), LstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, LstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, LstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LstmDescriptor::m_PeepholeEnabled, LstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, LstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, and ManagedConstTensorHandle::Map().
 {
     std::vector<ConstTensor> constTensors;
     LstmDescriptor descriptor = GetParameters();
     ManagedConstTensorHandle managedInputToForgetWeights(m_BasicParameters.m_InputToForgetWeights);
     ManagedConstTensorHandle managedInputToCellWeights(m_BasicParameters.m_InputToCellWeights);
     ManagedConstTensorHandle managedInputToOutputWeights(m_BasicParameters.m_InputToOutputWeights);
     ManagedConstTensorHandle managedRecurrentToForgetWeights(m_BasicParameters.m_RecurrentToForgetWeights);
     ManagedConstTensorHandle managedRecurrentToCellWeights(m_BasicParameters.m_RecurrentToCellWeights);
     ManagedConstTensorHandle managedRecurrentToOutputWeights(m_BasicParameters.m_RecurrentToOutputWeights);
     ManagedConstTensorHandle managedForgetGateBias(m_BasicParameters.m_ForgetGateBias);
     ManagedConstTensorHandle managedCellBias(m_BasicParameters.m_CellBias);
     ManagedConstTensorHandle managedOutputGateBias(m_BasicParameters.m_OutputGateBias);
     // Cifg parameters
     ManagedConstTensorHandle managedInputToInputWeights(m_CifgParameters.m_InputToInputWeights);
     ManagedConstTensorHandle managedRecurrentToInputWeights(m_CifgParameters.m_RecurrentToInputWeights);
     ManagedConstTensorHandle managedInputGateBias(m_CifgParameters.m_InputGateBias);
     // Projection parameters
     ManagedConstTensorHandle managedProjectionWeights(m_ProjectionParameters.m_ProjectionWeights);
     ManagedConstTensorHandle managedProjectionBias(m_ProjectionParameters.m_ProjectionBias);
     // Peephole parameters
     ManagedConstTensorHandle managedCellToInputWeights(m_PeepholeParameters.m_CellToInputWeights);
     ManagedConstTensorHandle managedCellToForgetWeights(m_PeepholeParameters.m_CellToForgetWeights);
     ManagedConstTensorHandle managedCellToOutputWeights(m_PeepholeParameters.m_CellToOutputWeights);
     // Layer normalisation parameters
     ManagedConstTensorHandle managedInputLayerNormWeights(m_LayerNormParameters.m_InputLayerNormWeights);
     ManagedConstTensorHandle managedForgetLayerNormWeights(m_LayerNormParameters.m_ForgetLayerNormWeights);
     ManagedConstTensorHandle managedCellLayerNormWeights(m_LayerNormParameters.m_CellLayerNormWeights);
     ManagedConstTensorHandle managedOutputLayerNormWeights(m_LayerNormParameters.m_OutputLayerNormWeights);
     // First add mandatory/basic parameters
     if (m_BasicParameters.m_InputToForgetWeights != nullptr)
     {
         constTensors.emplace_back(ConstTensor(managedInputToForgetWeights.GetTensorInfo(),
                                               managedInputToForgetWeights.Map()));
     }
     if (m_BasicParameters.m_InputToCellWeights != nullptr)
     {
         constTensors.emplace_back(ConstTensor(managedInputToCellWeights.GetTensorInfo(),
                                               managedInputToCellWeights.Map()));
     }
     if (m_BasicParameters.m_InputToOutputWeights != nullptr)
     {
         constTensors.emplace_back(ConstTensor(managedInputToOutputWeights.GetTensorInfo(),
                                               managedInputToOutputWeights.Map()));
     }
     if (m_BasicParameters.m_RecurrentToForgetWeights != nullptr)
     {
         constTensors.emplace_back(ConstTensor(
                 managedRecurrentToForgetWeights.GetTensorInfo(),
                 managedRecurrentToForgetWeights.Map()));
     }
     if (m_BasicParameters.m_RecurrentToCellWeights != nullptr)
     {
         constTensors.emplace_back(ConstTensor(
                 managedRecurrentToCellWeights.GetTensorInfo(),
                 managedRecurrentToCellWeights.Map()));
     }
     if (m_BasicParameters.m_RecurrentToOutputWeights != nullptr)
     {
         constTensors.emplace_back(ConstTensor(
                 managedRecurrentToOutputWeights.GetTensorInfo(),
                 managedRecurrentToOutputWeights.Map()));
     }
     if (m_BasicParameters.m_ForgetGateBias != nullptr)
     {
         constTensors.emplace_back(ConstTensor(managedForgetGateBias.GetTensorInfo(),
                                               managedForgetGateBias.Map()));
     }
     if (m_BasicParameters.m_CellBias != nullptr)
     {
         constTensors.emplace_back(ConstTensor(managedCellBias.GetTensorInfo(),
                                               managedCellBias.Map()));
     }
     if (m_BasicParameters.m_OutputGateBias != nullptr)
     {
         constTensors.emplace_back(ConstTensor(managedOutputGateBias.GetTensorInfo(),
                                               managedOutputGateBias.Map()));
     }
     // Add cifg parameters
     if (!descriptor.m_CifgEnabled)
     {
         if (m_CifgParameters.m_InputToInputWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedInputToInputWeights.GetTensorInfo(),
                                                   managedInputToInputWeights.Map()));
         }
         if (m_CifgParameters.m_RecurrentToInputWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(
                     managedRecurrentToInputWeights.GetTensorInfo(),
                     managedRecurrentToInputWeights.Map()));
         }
         if (m_CifgParameters.m_InputGateBias != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedInputGateBias.GetTensorInfo(),
                                                   managedInputGateBias.Map()));
         }
     }
     // Add peephole parameters
     if (descriptor.m_PeepholeEnabled)
     {
         if (!descriptor.m_CifgEnabled)
         {
             if (m_PeepholeParameters.m_CellToInputWeights != nullptr)
             {
                 constTensors.emplace_back(ConstTensor(managedCellToInputWeights.GetTensorInfo(),
                                                       managedCellToInputWeights.Map()));
             }
         }
         if (m_PeepholeParameters.m_CellToForgetWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedCellToForgetWeights.GetTensorInfo(),
                                                   managedCellToForgetWeights.Map()));
         }
         if (m_PeepholeParameters.m_CellToOutputWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedCellToOutputWeights.GetTensorInfo(),
                                                   managedCellToOutputWeights.Map()));
         }
     }
     // Add projection parameters
     if (descriptor.m_ProjectionEnabled)
     {
         if (m_ProjectionParameters.m_ProjectionWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedProjectionWeights.GetTensorInfo(),
                                                   managedProjectionWeights.Map()));
         }
         if (m_ProjectionParameters.m_ProjectionBias != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedProjectionBias.GetTensorInfo(),
                                                   managedProjectionBias.Map()));
         }
     }
     // Add norm parameters
     if (descriptor.m_LayerNormEnabled)
     {
         if (!descriptor.m_CifgEnabled)
         {
             if (m_LayerNormParameters.m_InputLayerNormWeights != nullptr)
             {
                 constTensors.emplace_back(ConstTensor(managedInputLayerNormWeights.GetTensorInfo(),
                                                       managedInputLayerNormWeights.Map()));
             }
         }
         if (m_LayerNormParameters.m_ForgetLayerNormWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedForgetLayerNormWeights.GetTensorInfo(),
                                                   managedForgetLayerNormWeights.Map()));
         }
         if (m_LayerNormParameters.m_CellLayerNormWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedCellLayerNormWeights.GetTensorInfo(),
                                                   managedCellLayerNormWeights.Map()));
         }
         if (m_LayerNormParameters.m_OutputLayerNormWeights != nullptr)
         {
             constTensors.emplace_back(ConstTensor(managedOutputLayerNormWeights.GetTensorInfo(),
                                                   managedOutputLayerNormWeights.Map()));
         }
     }
     strategy.ExecuteStrategy(this, GetParameters(), constTensors, GetName());
 }
GetConstantTensorsByRef()
Layer::ConstantTensors GetConstantTensorsByRef () override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 270 of file LstmLayer.cpp.
References ARMNN_NO_DEPRECATE_WARN_BEGIN, LstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, and LstmBasicParameters::m_RecurrentToOutputWeights.
 {
     // For API stability DO NOT ALTER order and add new members to the end of vector
     return {m_BasicParameters.m_InputToForgetWeights,
             m_BasicParameters.m_InputToCellWeights,
             m_BasicParameters.m_InputToOutputWeights,
             m_BasicParameters.m_RecurrentToForgetWeights,
             m_BasicParameters.m_RecurrentToCellWeights,
             m_BasicParameters.m_RecurrentToOutputWeights,
             m_BasicParameters.m_ForgetGateBias,
             m_BasicParameters.m_CellBias,
             m_BasicParameters.m_OutputGateBias,
             // Cifg parameters
             m_CifgParameters.m_InputToInputWeights,
             m_CifgParameters.m_RecurrentToInputWeights,
             m_CifgParameters.m_InputGateBias,
             // Projection parameters
             m_ProjectionParameters.m_ProjectionWeights,
             m_ProjectionParameters.m_ProjectionBias,
             // Peephole parameters
             m_PeepholeParameters.m_CellToInputWeights,
             m_PeepholeParameters.m_CellToForgetWeights,
             m_PeepholeParameters.m_CellToOutputWeights,
             // Layer normalisation parameters
             m_LayerNormParameters.m_InputLayerNormWeights,
             m_LayerNormParameters.m_ForgetLayerNormWeights,
             m_LayerNormParameters.m_CellLayerNormWeights,
             m_LayerNormParameters.m_OutputLayerNormWeights};
 }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 150 of file LstmLayer.cpp.
References ARMNN_ASSERT, LstmDescriptor::m_CifgEnabled, and LayerWithParameters< LstmDescriptor >::m_Param.
Referenced by LstmLayer::ValidateTensorShapesFromInputs().
 {
     ARMNN_ASSERT(inputShapes.size() == 3);
     // Get input values for validation
     unsigned int batchSize = inputShapes[0][0];
     unsigned int outputSize = inputShapes[1][1];
     unsigned int numUnits = inputShapes[2][1];
     std::vector<TensorShape> outShapes;
     outShapes.push_back(TensorShape({batchSize, numUnits * (m_Param.m_CifgEnabled ? 3 : 4)}));
     outShapes.push_back(TensorShape({batchSize, outputSize}));
     outShapes.push_back(TensorShape({batchSize, numUnits}));
     outShapes.push_back(TensorShape({batchSize, outputSize}));
     return outShapes;
 }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of LstmLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 168 of file LstmLayer.cpp.
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), armnn::GetTensorInfo(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), LstmLayer::InferOutputShapes(), LstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, LstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptCifgParameters::m_InputGateBias, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmBasicParameters::m_OutputGateBias, LayerWithParameters< LstmDescriptor >::m_Param, LstmDescriptor::m_PeepholeEnabled, LstmLayer::m_PeepholeParameters, LstmDescriptor::m_ProjectionEnabled, LstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
 {
     VerifyLayerConnections(3, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     auto inferredShapes = InferOutputShapes( {
         GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape(),
         GetInputSlot(1).GetConnection()->GetTensorInfo().GetShape(),
         GetInputSlot(2).GetConnection()->GetTensorInfo().GetShape()
     });
     ARMNN_ASSERT(inferredShapes.size() == 4);
     // Check if the weights are nullptr
     ARMNN_ASSERT_MSG(m_BasicParameters.m_InputToForgetWeights != nullptr,
                      "LstmLayer: m_BasicParameters.m_InputToForgetWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_InputToCellWeights != nullptr,
                      "LstmLayer: m_BasicParameters.m_InputToCellWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_InputToOutputWeights != nullptr,
                      "LstmLayer: m_BasicParameters.m_InputToOutputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_RecurrentToForgetWeights != nullptr,
                      "LstmLayer: m_BasicParameters.m_RecurrentToForgetWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_RecurrentToCellWeights != nullptr,
                      "LstmLayer: m_BasicParameters.m_RecurrentToCellWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_RecurrentToOutputWeights != nullptr,
                      "LstmLayer: m_BasicParameters.m_RecurrentToOutputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_ForgetGateBias != nullptr,
                      "LstmLayer: m_BasicParameters.m_ForgetGateBias should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_CellBias != nullptr,
                      "LstmLayer: m_BasicParameters.m_CellBias should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_OutputGateBias != nullptr,
                      "LstmLayer: m_BasicParameters.m_OutputGateBias should not be null.");
     if (!m_Param.m_CifgEnabled)
     {
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputToInputWeights != nullptr,
                          "LstmLayer: m_CifgParameters.m_InputToInputWeights should not be null.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_RecurrentToInputWeights != nullptr,
                          "LstmLayer: m_CifgParameters.m_RecurrentToInputWeights should not be null.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputGateBias != nullptr,
                          "LstmLayer: m_CifgParameters.m_InputGateBias should not be null.");
         ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "LstmLayer");
     }
     else
     {
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputToInputWeights == nullptr,
             "LstmLayer: m_CifgParameters.m_InputToInputWeights should not have a value when CIFG is enabled.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_RecurrentToInputWeights == nullptr,
             "LstmLayer: m_CifgParameters.m_RecurrentToInputWeights should not have a value when CIFG is enabled.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputGateBias == nullptr,
             "LstmLayer: m_CifgParameters.m_InputGateBias should not have a value when CIFG is enabled.");
         ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "LstmLayer");
     }
     if (m_Param.m_ProjectionEnabled)
     {
         ARMNN_ASSERT_MSG(m_ProjectionParameters.m_ProjectionWeights != nullptr,
                          "LstmLayer: m_ProjectionParameters.m_ProjectionWeights should not be null.");
     }
     if (m_Param.m_PeepholeEnabled)
     {
         if (!m_Param.m_CifgEnabled)
         {
             ARMNN_ASSERT_MSG(m_PeepholeParameters.m_CellToInputWeights != nullptr,
                              "LstmLayer: m_PeepholeParameters.m_CellToInputWeights should not be null "
                              "when Peephole is enabled and CIFG is disabled.");
         }
         ARMNN_ASSERT_MSG(m_PeepholeParameters.m_CellToForgetWeights != nullptr,
                          "LstmLayer: m_PeepholeParameters.m_CellToForgetWeights should not be null.");
         ARMNN_ASSERT_MSG(m_PeepholeParameters.m_CellToOutputWeights != nullptr,
                          "LstmLayer: m_PeepholeParameters.m_CellToOutputWeights should not be null.");
     }
     ValidateAndCopyShape(
             GetOutputSlot(1).GetTensorInfo().GetShape(), inferredShapes[1], m_ShapeInferenceMethod, "LstmLayer", 1);
     ValidateAndCopyShape(
             GetOutputSlot(2).GetTensorInfo().GetShape(), inferredShapes[2], m_ShapeInferenceMethod, "LstmLayer", 2);
     ValidateAndCopyShape(
             GetOutputSlot(3).GetTensorInfo().GetShape(), inferredShapes[3], m_ShapeInferenceMethod, "LstmLayer", 3);
     if (m_Param.m_LayerNormEnabled)
     {
         if(!m_Param.m_CifgEnabled)
         {
             ARMNN_ASSERT_MSG(m_LayerNormParameters.m_InputLayerNormWeights != nullptr,
                              "LstmLayer: m_LayerNormParameters.m_inputLayerNormWeights should not be null.");
         }
         ARMNN_ASSERT_MSG(m_LayerNormParameters.m_ForgetLayerNormWeights != nullptr,
                          "LstmLayer: m_LayerNormParameters.m_forgetLayerNormWeights should not be null.");
         ARMNN_ASSERT_MSG(m_LayerNormParameters.m_CellLayerNormWeights != nullptr,
                          "LstmLayer: m_LayerNormParameters.m_cellLayerNormWeights should not be null.");
         ARMNN_ASSERT_MSG(m_LayerNormParameters.m_OutputLayerNormWeights != nullptr,
                          "LstmLayer: m_LayerNormParameters.m_outputLayerNormWeights should not be null.");
     }
 }
Member Data Documentation
m_BasicParameters
LstmBasicParameters m_BasicParameters
Definition at line 20 of file LstmLayer.hpp.
Referenced by LstmLayer::Accept(), NetworkImpl::AddLstmLayer(), LstmLayer::Clone(), LstmLayer::CreateWorkload(), LstmLayer::ExecuteStrategy(), LstmLayer::GetConstantTensorsByRef(), and LstmLayer::ValidateTensorShapesFromInputs().
m_CifgParameters
LstmOptCifgParameters m_CifgParameters
Definition at line 21 of file LstmLayer.hpp.
Referenced by LstmLayer::Accept(), LstmLayer::Clone(), LstmLayer::CreateWorkload(), LstmLayer::ExecuteStrategy(), LstmLayer::GetConstantTensorsByRef(), and LstmLayer::ValidateTensorShapesFromInputs().
m_LayerNormParameters
LstmOptLayerNormParameters m_LayerNormParameters
Definition at line 24 of file LstmLayer.hpp.
Referenced by LstmLayer::Accept(), LstmLayer::Clone(), LstmLayer::CreateWorkload(), LstmLayer::ExecuteStrategy(), and LstmLayer::GetConstantTensorsByRef().
m_PeepholeParameters
LstmOptPeepholeParameters m_PeepholeParameters
Definition at line 23 of file LstmLayer.hpp.
Referenced by LstmLayer::Accept(), LstmLayer::Clone(), LstmLayer::CreateWorkload(), LstmLayer::ExecuteStrategy(), LstmLayer::GetConstantTensorsByRef(), and LstmLayer::ValidateTensorShapesFromInputs().
m_ProjectionParameters
LstmOptProjectionParameters m_ProjectionParameters
Definition at line 22 of file LstmLayer.hpp.
Referenced by LstmLayer::Accept(), LstmLayer::Clone(), LstmLayer::CreateWorkload(), LstmLayer::ExecuteStrategy(), LstmLayer::GetConstantTensorsByRef(), and LstmLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/LstmLayer.hpp
src/armnn/layers/LstmLayer.cpp