ArmNN: ConvertConstPermuteLayersToConstLayers Class Reference
ConvertConstPermuteLayersToConstLayers Class Reference
#include <ConvertConstPermuteLayersToConstLayers.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Protected Member Functions
ConvertConstPermuteLayersToConstLayers ()=default
~ConvertConstPermuteLayersToConstLayers ()=default
Detailed Description
Definition at line 17 of file ConvertConstPermuteLayersToConstLayers.hpp.
Constructor & Destructor Documentation
ConvertConstPermuteLayersToConstLayers()
ConvertConstPermuteLayersToConstLayers () protected default
Referenced by ConvertConstPermuteLayersToConstLayers::Run().
~ConvertConstPermuteLayersToConstLayers()
~ConvertConstPermuteLayersToConstLayers () protected default
Referenced by ConvertConstPermuteLayersToConstLayers::Run().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Definition at line 20 of file ConvertConstPermuteLayersToConstLayers.hpp.
References ARMNN_ASSERT, armnn::BFloat16, armnn::Boolean, armnn::Constant, ConvertConstPermuteLayersToConstLayers::ConvertConstPermuteLayersToConstLayers(), armnn::Float16, armnn::Float32, InputSlot::GetConnectedOutputSlot(), TensorInfo::GetDataType(), Layer::GetDataType(), armnn::GetDataTypeSize(), TensorInfo::GetNumElements(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), PermuteLayer::GetPermutation(), TensorInfo::GetShape(), OutputSlot::GetTensorInfo(), Layer::GetType(), armnn::IgnoreUnused(), TensorInfo::IsConstant(), ConstantLayer::m_LayerOutput, OutputSlot::MoveAllConnections(), armnn::Permute, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, TensorInfo::SetConstant(), OutputSlot::SetTensorInfo(), armnn::Signed32, armnn::Signed64, and ConvertConstPermuteLayersToConstLayers::~ConvertConstPermuteLayersToConstLayers().
     {
         Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
         Layer& child = connection.GetOwningLayer();
         ARMNN_ASSERT(base.GetType() == LayerType::Constant);
         ARMNN_ASSERT(child.GetType() == LayerType::Permute);
         if (base.GetDataType() == child.GetDataType())
         {
             switch (base.GetDataType())
             {
                 case DataType::Float16:
                     ReplaceConstPermuteLayer<DataType::Float16>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::Float32:
                     ReplaceConstPermuteLayer<DataType::Float32>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::QAsymmU8:
                     ReplaceConstPermuteLayer<DataType::QAsymmU8>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::Signed32:
                     ReplaceConstPermuteLayer<DataType::Signed32>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::QSymmS16:
                     ReplaceConstPermuteLayer<DataType::QSymmS16>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::QSymmS8:
                     ReplaceConstPermuteLayer<DataType::QSymmS8>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::QAsymmS8:
                     ReplaceConstPermuteLayer<DataType::QAsymmS8>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::BFloat16:
                     ReplaceConstPermuteLayer<DataType::BFloat16>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::Signed64:
                     ReplaceConstPermuteLayer<DataType::Signed64>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
                 case DataType::Boolean:
                     ReplaceConstPermuteLayer<DataType::Boolean>(graph,
                                                                  PolymorphicDowncast<ConstantLayer*>(&base),
                                                                  PolymorphicDowncast<PermuteLayer*>(&child));
                     break;
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/ConvertConstPermuteLayersToConstLayers.hpp