ArmNN: TestLstmLayerVisitor Class Reference
TestLstmLayerVisitor Class Reference
#include <ConstTensorLayerVisitor.hpp>
Public Member Functions
TestLstmLayerVisitor (const LstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from LstmVisitor
LstmVisitor (const LstmInputParams &params, const char *name=nullptr)
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Protected Member Functions
void CheckDescriptor (const LstmDescriptor &descriptor)
Protected Member Functions inherited from LstmVisitor
template<typename LayerType >
void CheckInputParameters (const LayerType *layer, const LstmInputParams &inputParams)
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckConstTensors (const ConstTensor &expected, const ConstTensorHandle &actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const ConstTensor *actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const std::shared_ptr< ConstTensorHandle > actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from StrategyBase< NoThrowStrategy >
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Additional Inherited Members
Protected Attributes inherited from LstmVisitor
LstmInputParams m_InputParams
Protected Attributes inherited from StrategyBase< NoThrowStrategy >
NoThrowStrategy m_DefaultStrategy
Detailed Description
Definition at line 321 of file ConstTensorLayerVisitor.hpp.
Constructor & Destructor Documentation
TestLstmLayerVisitor()
TestLstmLayerVisitor (const LstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr) inline explicit
Definition at line 324 of file ConstTensorLayerVisitor.hpp.
         : LstmVisitor(params, name)
         , m_Descriptor(descriptor)
     {}
Member Function Documentation
CheckDescriptor()
void CheckDescriptor (const LstmDescriptor & descriptor) protected
Definition at line 51 of file ConstTensorLayerVisitor.cpp.
References LstmDescriptor::m_ActivationFunc, LstmDescriptor::m_CifgEnabled, LstmDescriptor::m_ClippingThresCell, LstmDescriptor::m_ClippingThresProj, LstmDescriptor::m_PeepholeEnabled, and LstmDescriptor::m_ProjectionEnabled.
 {
     CHECK(m_Descriptor.m_ActivationFunc == descriptor.m_ActivationFunc);
     CHECK(m_Descriptor.m_ClippingThresCell == descriptor.m_ClippingThresCell);
     CHECK(m_Descriptor.m_ClippingThresProj == descriptor.m_ClippingThresProj);
     CHECK(m_Descriptor.m_CifgEnabled == descriptor.m_CifgEnabled);
     CHECK(m_Descriptor.m_PeepholeEnabled == descriptor.m_PeepholeEnabled);
     CHECK(m_Descriptor.m_ProjectionEnabled == descriptor.m_ProjectionEnabled);
 }
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Reimplemented from StrategyBase< NoThrowStrategy >.
Definition at line 331 of file ConstTensorLayerVisitor.hpp.
References NoThrowStrategy::Apply(), TestConvolution2dLayerVisitor::CheckDescriptor(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), armnn::Lstm, and StrategyBase< NoThrowStrategy >::m_DefaultStrategy.
     {
         armnn::IgnoreUnused(descriptor, constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::Lstm:
             {
                 CheckLayerPointer(layer);
                 CheckLayerName(name);
                 CheckDescriptor(static_cast<const armnn::LstmDescriptor&>(descriptor));
                 CheckInputParameters<const LstmLayer>(PolymorphicDowncast<const LstmLayer*>(layer), m_InputParams);
                 break;
             }
             default:
             {
                 m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
             }
         }
     }
The documentation for this class was generated from the following files:
src/armnn/test/ConstTensorLayerVisitor.hpp
src/armnn/test/ConstTensorLayerVisitor.cpp