ArmNN: BaseIterator Class Reference
BaseIterator Class Reference abstract
#include <BaseIterator.hpp>
Public Member Functions
BaseIterator ()
virtual ~BaseIterator ()
virtual BaseIterator & operator++ ()=0
virtual BaseIterator & operator+= (const unsigned int increment)=0
virtual BaseIterator & operator-= (const unsigned int increment)=0
virtual BaseIterator & operator[] (const unsigned int index)=0
Detailed Description
Definition at line 20 of file BaseIterator.hpp.
Constructor & Destructor Documentation
BaseIterator()
BaseIterator () inline
Definition at line 23 of file BaseIterator.hpp.
 {}
~BaseIterator()
virtual ~BaseIterator () inline virtual
Definition at line 25 of file BaseIterator.hpp.
References BaseIterator::operator++(), BaseIterator::operator+=(), BaseIterator::operator-=(), and BaseIterator::operator[]().
 {}
Member Function Documentation
operator++()
virtual BaseIterator& operator++ () pure virtual
Implemented in PerAxisIterator< int8_t, Encoder< float > >, PerAxisIterator< const int32_t, Decoder< float > >, PerAxisIterator< const int8_t, Decoder< int8_t > >, PerAxisIterator< const int8_t, Decoder< float > >, TypedIterator< int32_t, Encoder< float > >, TypedIterator< armnn::BFloat16, Encoder< float > >, TypedIterator< const BFloat16, Decoder< float > >, TypedIterator< int8_t, Encoder< float > >, TypedIterator< uint8_t, Encoder< bool > >, TypedIterator< uint8_t, Encoder< float > >, TypedIterator< int16_t, Encoder< float > >, TypedIterator< const int32_t, Decoder< float > >, TypedIterator< int32_t, Encoder< int32_t > >, TypedIterator< const uint8_t, Decoder< bool > >, TypedIterator< float, Encoder< float > >, TypedIterator< const Half, Decoder< float > >, TypedIterator< const uint8_t, Decoder< float > >, TypedIterator< const int16_t, Decoder< float > >, TypedIterator< const int8_t, Decoder< float > >, TypedIterator< Half, Encoder< float > >, TypedIterator< const int32_t, Decoder< int32_t > >, and TypedIterator< const float, Decoder< float > >.
Referenced by BaseIterator::~BaseIterator().
operator+=()
virtual BaseIterator& operator+= (const unsigned int increment) pure virtual
Implemented in PerAxisIterator< int8_t, Encoder< float > >, PerAxisIterator< const int32_t, Decoder< float > >, PerAxisIterator< const int8_t, Decoder< int8_t > >, PerAxisIterator< const int8_t, Decoder< float > >, TypedIterator< int32_t, Encoder< float > >, TypedIterator< armnn::BFloat16, Encoder< float > >, TypedIterator< const BFloat16, Decoder< float > >, TypedIterator< int8_t, Encoder< float > >, TypedIterator< uint8_t, Encoder< bool > >, TypedIterator< uint8_t, Encoder< float > >, TypedIterator< int16_t, Encoder< float > >, TypedIterator< const int32_t, Decoder< float > >, TypedIterator< int32_t, Encoder< int32_t > >, TypedIterator< const uint8_t, Decoder< bool > >, TypedIterator< float, Encoder< float > >, TypedIterator< const Half, Decoder< float > >, TypedIterator< const uint8_t, Decoder< float > >, TypedIterator< const int16_t, Decoder< float > >, TypedIterator< const int8_t, Decoder< float > >, TypedIterator< Half, Encoder< float > >, TypedIterator< const int32_t, Decoder< int32_t > >, and TypedIterator< const float, Decoder< float > >.
Referenced by BaseIterator::~BaseIterator().
operator-=()
virtual BaseIterator& operator-= (const unsigned int increment) pure virtual
Implemented in PerAxisIterator< int8_t, Encoder< float > >, PerAxisIterator< const int32_t, Decoder< float > >, PerAxisIterator< const int8_t, Decoder< int8_t > >, PerAxisIterator< const int8_t, Decoder< float > >, TypedIterator< int32_t, Encoder< float > >, TypedIterator< armnn::BFloat16, Encoder< float > >, TypedIterator< const BFloat16, Decoder< float > >, TypedIterator< int8_t, Encoder< float > >, TypedIterator< uint8_t, Encoder< bool > >, TypedIterator< uint8_t, Encoder< float > >, TypedIterator< int16_t, Encoder< float > >, TypedIterator< const int32_t, Decoder< float > >, TypedIterator< int32_t, Encoder< int32_t > >, TypedIterator< const uint8_t, Decoder< bool > >, TypedIterator< float, Encoder< float > >, TypedIterator< const Half, Decoder< float > >, TypedIterator< const uint8_t, Decoder< float > >, TypedIterator< const int16_t, Decoder< float > >, TypedIterator< const int8_t, Decoder< float > >, TypedIterator< Half, Encoder< float > >, TypedIterator< const int32_t, Decoder< int32_t > >, and TypedIterator< const float, Decoder< float > >.
Referenced by BaseIterator::~BaseIterator().
operator[]()
virtual BaseIterator& operator[] (const unsigned int index) pure virtual
Implemented in PerAxisIterator< int8_t, Encoder< float > >, PerAxisIterator< const int32_t, Decoder< float > >, PerAxisIterator< const int8_t, Decoder< int8_t > >, PerAxisIterator< const int8_t, Decoder< float > >, TypedIterator< int32_t, Encoder< float > >, TypedIterator< armnn::BFloat16, Encoder< float > >, TypedIterator< const BFloat16, Decoder< float > >, TypedIterator< int8_t, Encoder< float > >, TypedIterator< uint8_t, Encoder< bool > >, TypedIterator< uint8_t, Encoder< float > >, TypedIterator< int16_t, Encoder< float > >, TypedIterator< const int32_t, Decoder< float > >, TypedIterator< int32_t, Encoder< int32_t > >, TypedIterator< const uint8_t, Decoder< bool > >, TypedIterator< float, Encoder< float > >, TypedIterator< const Half, Decoder< float > >, TypedIterator< const uint8_t, Decoder< float > >, TypedIterator< const int16_t, Decoder< float > >, TypedIterator< const int8_t, Decoder< float > >, TypedIterator< Half, Encoder< float > >, TypedIterator< const int32_t, Decoder< int32_t > >, and TypedIterator< const float, Decoder< float > >.
Referenced by QASymm8Decoder::DecodeTensor(), QASymmS8Decoder::DecodeTensor(), QSymmS8Decoder::DecodeTensor(), QSymm16Decoder::DecodeTensor(), BFloat16Decoder::DecodeTensor(), Float16Decoder::DecodeTensor(), ScaledInt32Decoder::DecodeTensor(), Int32Decoder::DecodeTensor(), Int32ToInt32tDecoder::DecodeTensor(), BooleanDecoder::DecodeTensor(), BooleanDecoderBool::DecodeTensor(), ScaledInt32PerAxisDecoder::DecodeTensor(), PerAxisIterator< const int8_t, Decoder< float > >::operator++(), PerAxisIterator< const int8_t, Decoder< float > >::operator+=(), PerAxisIterator< const int8_t, Decoder< float > >::operator-=(), and BaseIterator::~BaseIterator().
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp