ArmNN: SendCounterPacketTest Class Reference
SendCounterPacketTest Class Reference
#include <SendCounterPacketTests.hpp>
Public Member Functions
SendCounterPacketTest (IBufferManager &buffer)
bool CreateDeviceRecordTest (const DevicePtr &device, DeviceRecord &deviceRecord, std::string &errorMessage)
bool CreateCounterSetRecordTest (const CounterSetPtr &counterSet, CounterSetRecord &counterSetRecord, std::string &errorMessage)
bool CreateEventRecordTest (const CounterPtr &counter, EventRecord &eventRecord, std::string &errorMessage)
bool CreateCategoryRecordTest (const CategoryPtr &category, const Counters &counters, CategoryRecord &categoryRecord, std::string &errorMessage)
Detailed Description
Definition at line 29 of file SendCounterPacketTests.hpp.
Constructor & Destructor Documentation
SendCounterPacketTest()
SendCounterPacketTest (IBufferManager & buffer) inline
Definition at line 32 of file SendCounterPacketTests.hpp.
         : SendCounterPacket(buffer,
                             arm::pipe::ARMNN_SOFTWARE_INFO,
                             arm::pipe::ARMNN_SOFTWARE_VERSION,
                             arm::pipe::ARMNN_HARDWARE_VERSION)
     {}
Member Function Documentation
CreateCategoryRecordTest()
bool CreateCategoryRecordTest (const CategoryPtr & category, const Counters & counters, CategoryRecord & categoryRecord, std::string & errorMessage) inline
Definition at line 60 of file SendCounterPacketTests.hpp.
Referenced by TEST_SUITE().
     {
         return CreateCategoryRecord(category, counters, categoryRecord, errorMessage);
     }
CreateCounterSetRecordTest()
bool CreateCounterSetRecordTest (const CounterSetPtr & counterSet, CounterSetRecord & counterSetRecord, std::string & errorMessage) inline
Definition at line 46 of file SendCounterPacketTests.hpp.
Referenced by TEST_SUITE().
     {
         return CreateCounterSetRecord(counterSet, counterSetRecord, errorMessage);
     }
CreateDeviceRecordTest()
bool CreateDeviceRecordTest (const DevicePtr & device, DeviceRecord & deviceRecord, std::string & errorMessage) inline
Definition at line 39 of file SendCounterPacketTests.hpp.
Referenced by TEST_SUITE().
     {
         return CreateDeviceRecord(device, deviceRecord, errorMessage);
     }
CreateEventRecordTest()
bool CreateEventRecordTest (const CounterPtr & counter, EventRecord & eventRecord, std::string & errorMessage) inline
Definition at line 53 of file SendCounterPacketTests.hpp.
Referenced by TEST_SUITE().
     {
         return CreateEventRecord(counter, eventRecord, errorMessage);
     }
The documentation for this class was generated from the following file:
src/profiling/test/SendCounterPacketTests.hpp