ArmNN: TestBatchNormalizationLayerVisitor Class Reference
TestBatchNormalizationLayerVisitor Class Reference
#include <ConstTensorLayerVisitor.hpp>
Public Member Functions
TestBatchNormalizationLayerVisitor (const BatchNormalizationDescriptor &descriptor, const ConstTensor &mean, const ConstTensor &variance, const ConstTensor &beta, const ConstTensor &gamma, const char *name=nullptr)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Protected Member Functions
void CheckDescriptor (const BatchNormalizationDescriptor &descriptor)
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckConstTensors (const ConstTensor &expected, const ConstTensorHandle &actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const ConstTensor *actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const std::shared_ptr< ConstTensorHandle > actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from StrategyBase< NoThrowStrategy >
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Additional Inherited Members
Protected Attributes inherited from StrategyBase< NoThrowStrategy >
NoThrowStrategy m_DefaultStrategy
Detailed Description
Definition at line 142 of file ConstTensorLayerVisitor.hpp.
Constructor & Destructor Documentation
TestBatchNormalizationLayerVisitor()
TestBatchNormalizationLayerVisitor (const BatchNormalizationDescriptor & descriptor, const ConstTensor & mean, const ConstTensor & variance, const ConstTensor & beta, const ConstTensor & gamma, const char * name = nullptr) inline
Definition at line 145 of file ConstTensorLayerVisitor.hpp.
         : TestLayerVisitor(name)
         , m_Descriptor(descriptor)
         , m_Mean(mean)
         , m_Variance(variance)
         , m_Beta(beta)
         , m_Gamma(gamma)
     {}
Member Function Documentation
CheckDescriptor()
void CheckDescriptor (const BatchNormalizationDescriptor & descriptor) protected
Definition at line 45 of file ConstTensorLayerVisitor.cpp.
References Convolution2dDescriptor::m_DataLayout, BatchNormalizationDescriptor::m_DataLayout, and BatchNormalizationDescriptor::m_Eps.
 {
     CHECK(m_Descriptor.m_Eps == descriptor.m_Eps);
     CHECK(m_Descriptor.m_DataLayout == descriptor.m_DataLayout);
 }
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Reimplemented from StrategyBase< NoThrowStrategy >.
Definition at line 159 of file ConstTensorLayerVisitor.hpp.
References NoThrowStrategy::Apply(), armnn::BatchNormalization, TestLayerVisitor::CheckConstTensors(), TestConvolution2dLayerVisitor::CheckDescriptor(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), and StrategyBase< NoThrowStrategy >::m_DefaultStrategy.
     {
         armnn::IgnoreUnused(descriptor, constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::BatchNormalization:
             {
                 CheckLayerPointer(layer);
                 CheckLayerName(name);
                 CheckDescriptor(static_cast<const armnn::BatchNormalizationDescriptor&>(descriptor));
                 CheckConstTensors(m_Mean,     constants[0]);
                 CheckConstTensors(m_Variance, constants[1]);
                 CheckConstTensors(m_Beta,     constants[2]);
                 CheckConstTensors(m_Gamma,    constants[3]);
                 break;
             }
             default:
             {
                 m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
             }
         }
     }
The documentation for this class was generated from the following files:
src/armnn/test/ConstTensorLayerVisitor.hpp
src/armnn/test/ConstTensorLayerVisitor.cpp