ArmNN: ProfilerManager Class Reference
ProfilerManager Class Reference
#include <Profiling.hpp>
Public Member Functions
void RegisterProfiler (IProfiler *profiler)
IProfiler * GetProfiler ()
Static Public Member Functions
static ProfilerManager & GetInstance ()
Detailed Description
Definition at line 111 of file Profiling.hpp.
Member Function Documentation
GetInstance()
ProfilerManager & GetInstance () static
Definition at line 572 of file Profiling.cpp.
Referenced by RuntimeImpl::CreateWorkingMemHandle(), DetectionPostProcessImpl(), RuntimeImpl::EnqueueWorkload(), RuntimeImpl::Execute(), armnn::GetProfilerEventSequenceSize(), GetSoftmaxProfilerJson(), RuntimeImpl::LoadNetwork(), LoadedNetwork::MakeLoadedNetwork(), armnn::Optimize(), armnn::ProfilingUpdateDescriptions(), RunTestFunction(), RunTestFunctionUsingTensorHandleFactory(), TEST_SUITE(), RuntimeImpl::UnloadNetwork(), and ProfilerImpl::~ProfilerImpl().
 {
     // Global reference to the single ProfileManager instance allowed.
     static ProfilerManager s_ProfilerManager;
     return s_ProfilerManager;
 }
GetProfiler()
IProfiler * GetProfiler ()
Definition at line 584 of file Profiling.cpp.
References armnn::tl_Profiler.
Referenced by armnn::GetProfilerEventSequenceSize(), and TEST_SUITE().
 {
     return tl_Profiler;
 }
RegisterProfiler()
void RegisterProfiler (IProfiler * profiler)
Definition at line 579 of file Profiling.cpp.
Referenced by RuntimeImpl::CreateWorkingMemHandle(), DetectionPostProcessImpl(), RuntimeImpl::EnqueueWorkload(), RuntimeImpl::Execute(), armnn::GetProfilerEventSequenceSize(), RuntimeImpl::LoadNetwork(), LoadedNetwork::MakeLoadedNetwork(), armnn::Optimize(), RunTestFunction(), RunTestFunctionUsingTensorHandleFactory(), TEST_SUITE(), RuntimeImpl::UnloadNetwork(), and ProfilerImpl::~ProfilerImpl().
 {
     tl_Profiler = profiler;
 }
The documentation for this class was generated from the following files:
src/armnn/Profiling.hpp
src/armnn/Profiling.cpp