ArmNN: IDeserializer::DeserializerImpl Class Reference
IDeserializer::DeserializerImpl Class Reference
#include <Deserializer.hpp>
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent)
Create an input network from binary file contents.
armnn::INetworkPtr CreateNetworkFromBinary (std::istream &binaryContent)
Create an input network from a binary input stream.
BindingPointInfo GetNetworkInputBindingInfo (unsigned int layerId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
BindingPointInfo GetNetworkOutputBindingInfo (unsigned int layerId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
DeserializerImpl ()
~DeserializerImpl ()=default
DeserializerImpl (const DeserializerImpl &)=delete
DeserializerImpl & operator= (const DeserializerImpl &)=delete
Static Public Member Functions
static GraphPtr LoadGraphFromBinary (const uint8_t *binaryContent, size_t len)
static TensorRawPtrVector GetInputs (const GraphPtr &graph, unsigned int layerIndex)
static TensorRawPtrVector GetOutputs (const GraphPtr &graph, unsigned int layerIndex)
static LayerBaseRawPtr GetBaseLayer (const GraphPtr &graphPtr, unsigned int layerIndex)
static int32_t GetBindingLayerInfo (const GraphPtr &graphPtr, unsigned int layerIndex)
static std::string GetLayerName (const GraphPtr &graph, unsigned int index)
static armnn::Pooling2dDescriptor GetPooling2dDescriptor (Pooling2dDescriptor pooling2dDescriptor, unsigned int layerIndex)
static armnn::Pooling3dDescriptor GetPooling3dDescriptor (Pooling3dDescriptor pooling3dDescriptor, unsigned int layerIndex)
static armnn::NormalizationDescriptor GetNormalizationDescriptor (NormalizationDescriptorPtr normalizationDescriptor, unsigned int layerIndex)
static armnn::LstmDescriptor GetLstmDescriptor (LstmDescriptorPtr lstmDescriptor)
static armnn::LstmInputParams GetLstmInputParams (LstmDescriptorPtr lstmDescriptor, LstmInputParamsPtr lstmInputParams)
static armnn::QLstmDescriptor GetQLstmDescriptor (QLstmDescriptorPtr qLstmDescriptorPtr)
static armnn::UnidirectionalSequenceLstmDescriptor GetUnidirectionalSequenceLstmDescriptor (UnidirectionalSequenceLstmDescriptorPtr descriptor)
static armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo &inputTensorInfo, const std::vector< uint32_t > &targetDimsIn)
Detailed Description
Definition at line 34 of file Deserializer.hpp.
Constructor & Destructor Documentation
DeserializerImpl() [1/2]
DeserializerImpl ()
Definition at line 207 of file Deserializer.cpp.
References armnnSerializer::Layer_AbsLayer, armnnSerializer::Layer_ActivationLayer, armnnSerializer::Layer_AdditionLayer, armnnSerializer::Layer_ArgMinMaxLayer, armnnSerializer::Layer_BatchNormalizationLayer, armnnSerializer::Layer_BatchToSpaceNdLayer, armnnSerializer::Layer_CastLayer, armnnSerializer::Layer_ChannelShuffleLayer, armnnSerializer::Layer_ComparisonLayer, armnnSerializer::Layer_ConcatLayer, armnnSerializer::Layer_ConstantLayer, armnnSerializer::Layer_Convolution2dLayer, armnnSerializer::Layer_Convolution3dLayer, armnnSerializer::Layer_DepthToSpaceLayer, armnnSerializer::Layer_DepthwiseConvolution2dLayer, armnnSerializer::Layer_DequantizeLayer, armnnSerializer::Layer_DetectionPostProcessLayer, armnnSerializer::Layer_DivisionLayer, armnnSerializer::Layer_ElementwiseUnaryLayer, armnnSerializer::Layer_EqualLayer, armnnSerializer::Layer_FillLayer, armnnSerializer::Layer_FloorLayer, armnnSerializer::Layer_FullyConnectedLayer, armnnSerializer::Layer_GatherLayer, armnnSerializer::Layer_GatherNdLayer, armnnSerializer::Layer_GreaterLayer, armnnSerializer::Layer_InstanceNormalizationLayer, armnnSerializer::Layer_L2NormalizationLayer, armnnSerializer::Layer_LogicalBinaryLayer, armnnSerializer::Layer_LogSoftmaxLayer, armnnSerializer::Layer_LstmLayer, armnnSerializer::Layer_MaximumLayer, armnnSerializer::Layer_MeanLayer, armnnSerializer::Layer_MergeLayer, armnnSerializer::Layer_MergerLayer, armnnSerializer::Layer_MinimumLayer, armnnSerializer::Layer_MultiplicationLayer, armnnSerializer::Layer_NormalizationLayer, armnnSerializer::Layer_PadLayer, armnnSerializer::Layer_PermuteLayer, armnnSerializer::Layer_Pooling2dLayer, armnnSerializer::Layer_Pooling3dLayer, armnnSerializer::Layer_PreluLayer, armnnSerializer::Layer_QLstmLayer, armnnSerializer::Layer_QuantizedLstmLayer, armnnSerializer::Layer_QuantizeLayer, armnnSerializer::Layer_RankLayer, armnnSerializer::Layer_ReduceLayer, armnnSerializer::Layer_ReshapeLayer, armnnSerializer::Layer_ResizeBilinearLayer, armnnSerializer::Layer_ResizeLayer, armnnSerializer::Layer_RsqrtLayer, armnnSerializer::Layer_ShapeLayer, armnnSerializer::Layer_SliceLayer, armnnSerializer::Layer_SoftmaxLayer, armnnSerializer::Layer_SpaceToBatchNdLayer, armnnSerializer::Layer_SpaceToDepthLayer, armnnSerializer::Layer_SplitterLayer, armnnSerializer::Layer_StackLayer, armnnSerializer::Layer_StandInLayer, armnnSerializer::Layer_StridedSliceLayer, armnnSerializer::Layer_SubtractionLayer, armnnSerializer::Layer_SwitchLayer, armnnSerializer::Layer_TransposeConvolution2dLayer, armnnSerializer::Layer_TransposeLayer, and armnnSerializer::Layer_UnidirectionalSequenceLstmLayer.
 : m_Network(nullptr, nullptr),
 //May require LayerType_Max to be included
 m_ParserFunctions(Layer_MAX+1, &IDeserializer::DeserializerImpl::ParseUnsupportedLayer)
 {
     // register supported layers
     m_ParserFunctions[Layer_AbsLayer]                    = &DeserializerImpl::ParseAbs;
     m_ParserFunctions[Layer_ActivationLayer]             = &DeserializerImpl::ParseActivation;
     m_ParserFunctions[Layer_AdditionLayer]               = &DeserializerImpl::ParseAdd;
     m_ParserFunctions[Layer_ArgMinMaxLayer]              = &DeserializerImpl::ParseArgMinMax;
     m_ParserFunctions[Layer_BatchToSpaceNdLayer]         = &DeserializerImpl::ParseBatchToSpaceNd;
     m_ParserFunctions[Layer_BatchNormalizationLayer]     = &DeserializerImpl::ParseBatchNormalization;
     m_ParserFunctions[Layer_CastLayer]                   = &DeserializerImpl::ParseCast;
     m_ParserFunctions[Layer_ChannelShuffleLayer]         = &DeserializerImpl::ParseChannelShuffle;
     m_ParserFunctions[Layer_ComparisonLayer]             = &DeserializerImpl::ParseComparison;
     m_ParserFunctions[Layer_ConcatLayer]                 = &DeserializerImpl::ParseConcat;
     m_ParserFunctions[Layer_ConstantLayer]               = &DeserializerImpl::ParseConstant;
     m_ParserFunctions[Layer_Convolution2dLayer]          = &DeserializerImpl::ParseConvolution2d;
     m_ParserFunctions[Layer_Convolution3dLayer]          = &DeserializerImpl::ParseConvolution3d;
     m_ParserFunctions[Layer_DepthToSpaceLayer]           = &DeserializerImpl::ParseDepthToSpace;
     m_ParserFunctions[Layer_DepthwiseConvolution2dLayer] = &DeserializerImpl::ParseDepthwiseConvolution2d;
     m_ParserFunctions[Layer_DequantizeLayer]             = &DeserializerImpl::ParseDequantize;
     m_ParserFunctions[Layer_DetectionPostProcessLayer]   = &DeserializerImpl::ParseDetectionPostProcess;
     m_ParserFunctions[Layer_DivisionLayer]               = &DeserializerImpl::ParseDivision;
     m_ParserFunctions[Layer_ElementwiseUnaryLayer]       = &DeserializerImpl::ParseElementwiseUnary;
     m_ParserFunctions[Layer_EqualLayer]                  = &DeserializerImpl::ParseEqual;
     m_ParserFunctions[Layer_FullyConnectedLayer]         = &DeserializerImpl::ParseFullyConnected;
     m_ParserFunctions[Layer_FillLayer]                   = &DeserializerImpl::ParseFill;
     m_ParserFunctions[Layer_FloorLayer]                  = &DeserializerImpl::ParseFloor;
     m_ParserFunctions[Layer_GatherLayer]                 = &DeserializerImpl::ParseGather;
     m_ParserFunctions[Layer_GatherNdLayer]               = &DeserializerImpl::ParseGatherNd;
     m_ParserFunctions[Layer_GreaterLayer]                = &DeserializerImpl::ParseGreater;
     m_ParserFunctions[Layer_InstanceNormalizationLayer]  = &DeserializerImpl::ParseInstanceNormalization;
     m_ParserFunctions[Layer_L2NormalizationLayer]        = &DeserializerImpl::ParseL2Normalization;
     m_ParserFunctions[Layer_LogicalBinaryLayer]          = &DeserializerImpl::ParseLogicalBinary;
     m_ParserFunctions[Layer_LogSoftmaxLayer]             = &DeserializerImpl::ParseLogSoftmax;
     m_ParserFunctions[Layer_LstmLayer]                   = &DeserializerImpl::ParseLstm;
     m_ParserFunctions[Layer_MaximumLayer]                = &DeserializerImpl::ParseMaximum;
     m_ParserFunctions[Layer_MeanLayer]                   = &DeserializerImpl::ParseMean;
     m_ParserFunctions[Layer_MinimumLayer]                = &DeserializerImpl::ParseMinimum;
     m_ParserFunctions[Layer_MergeLayer]                  = &DeserializerImpl::ParseMerge;
     m_ParserFunctions[Layer_MergerLayer]                 = &DeserializerImpl::ParseConcat;
     m_ParserFunctions[Layer_MultiplicationLayer]         = &DeserializerImpl::ParseMultiplication;
     m_ParserFunctions[Layer_NormalizationLayer]          = &DeserializerImpl::ParseNormalization;
     m_ParserFunctions[Layer_PadLayer]                    = &DeserializerImpl::ParsePad;
     m_ParserFunctions[Layer_PermuteLayer]                = &DeserializerImpl::ParsePermute;
     m_ParserFunctions[Layer_Pooling2dLayer]              = &DeserializerImpl::ParsePooling2d;
     m_ParserFunctions[Layer_Pooling3dLayer]              = &DeserializerImpl::ParsePooling3d;
     m_ParserFunctions[Layer_PreluLayer]                  = &DeserializerImpl::ParsePrelu;
     m_ParserFunctions[Layer_QLstmLayer]                  = &DeserializerImpl::ParseQLstm;
     m_ParserFunctions[Layer_QuantizeLayer]               = &DeserializerImpl::ParseQuantize;
     m_ParserFunctions[Layer_QuantizedLstmLayer]          = &DeserializerImpl::ParseQuantizedLstm;
     m_ParserFunctions[Layer_RankLayer]                   = &DeserializerImpl::ParseRank;
     m_ParserFunctions[Layer_ReduceLayer]                 = &DeserializerImpl::ParseReduce;
     m_ParserFunctions[Layer_ReshapeLayer]                = &DeserializerImpl::ParseReshape;
     m_ParserFunctions[Layer_ResizeBilinearLayer]         = &DeserializerImpl::ParseResizeBilinear;
     m_ParserFunctions[Layer_ResizeLayer]                 = &DeserializerImpl::ParseResize;
     m_ParserFunctions[Layer_RsqrtLayer]                  = &DeserializerImpl::ParseRsqrt;
     m_ParserFunctions[Layer_ShapeLayer]                  = &DeserializerImpl::ParseShape;
     m_ParserFunctions[Layer_SliceLayer]                  = &DeserializerImpl::ParseSlice;
     m_ParserFunctions[Layer_SoftmaxLayer]                = &DeserializerImpl::ParseSoftmax;
     m_ParserFunctions[Layer_SpaceToBatchNdLayer]         = &DeserializerImpl::ParseSpaceToBatchNd;
     m_ParserFunctions[Layer_SpaceToDepthLayer]           = &DeserializerImpl::ParseSpaceToDepth;
     m_ParserFunctions[Layer_SplitterLayer]               = &DeserializerImpl::ParseSplitter;
     m_ParserFunctions[Layer_StackLayer]                  = &DeserializerImpl::ParseStack;
     m_ParserFunctions[Layer_StandInLayer]                = &DeserializerImpl::ParseStandIn;
     m_ParserFunctions[Layer_StridedSliceLayer]           = &DeserializerImpl::ParseStridedSlice;
     m_ParserFunctions[Layer_SubtractionLayer]            = &DeserializerImpl::ParseSubtraction;
     m_ParserFunctions[Layer_SwitchLayer]                 = &DeserializerImpl::ParseSwitch;
     m_ParserFunctions[Layer_TransposeConvolution2dLayer] = &DeserializerImpl::ParseTransposeConvolution2d;
     m_ParserFunctions[Layer_TransposeLayer]              = &DeserializerImpl::ParseTranspose;
     m_ParserFunctions[Layer_UnidirectionalSequenceLstmLayer] = &DeserializerImpl::ParseUnidirectionalSequenceLstm;
 }
~DeserializerImpl()
~DeserializerImpl () default
DeserializerImpl() [2/2]
DeserializerImpl (const DeserializerImpl &) delete
Member Function Documentation
CreateNetworkFromBinary() [1/2]
INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent)
Create an input network from binary file contents.
Definition at line 813 of file Deserializer.cpp.
References IDeserializer::DeserializerImpl::LoadGraphFromBinary().
 {
      ResetParser();
      GraphPtr graph = LoadGraphFromBinary(binaryContent.data(), binaryContent.size());
      return CreateNetworkFromGraph(graph);
 }
CreateNetworkFromBinary() [2/2]
armnn::INetworkPtr CreateNetworkFromBinary (std::istream & binaryContent)
Create an input network from a binary input stream.
Definition at line 820 of file Deserializer.cpp.
References ARMNN_LOG, armnn::error, and IDeserializer::DeserializerImpl::LoadGraphFromBinary().
 {
     ResetParser();
     if (binaryContent.fail()) {
         ARMNN_LOG(error) << (std::string("Cannot read input"));
         throw ParseException("Unable to read Input stream data");
     }
     binaryContent.seekg(0, std::ios::end);
     const std::streamoff size = binaryContent.tellg();
     std::vector<char> content(static_cast<size_t>(size));
     binaryContent.seekg(0);
     binaryContent.read(content.data(), static_cast<std::streamsize>(size));
     GraphPtr graph = LoadGraphFromBinary(reinterpret_cast<uint8_t*>(content.data()), static_cast<size_t>(size));
     return CreateNetworkFromGraph(graph);
 }
GetBaseLayer()
LayerBaseRawPtr GetBaseLayer (const GraphPtr & graphPtr, unsigned int layerIndex) static
Definition at line 281 of file Deserializer.cpp.
References armnnSerializer::Layer_AbsLayer, armnnSerializer::Layer_ActivationLayer, armnnSerializer::Layer_AdditionLayer, armnnSerializer::Layer_ArgMinMaxLayer, armnnSerializer::Layer_BatchNormalizationLayer, armnnSerializer::Layer_BatchToSpaceNdLayer, armnnSerializer::Layer_CastLayer, armnnSerializer::Layer_ChannelShuffleLayer, armnnSerializer::Layer_ComparisonLayer, armnnSerializer::Layer_ConcatLayer, armnnSerializer::Layer_ConstantLayer, armnnSerializer::Layer_Convolution2dLayer, armnnSerializer::Layer_Convolution3dLayer, armnnSerializer::Layer_DepthToSpaceLayer, armnnSerializer::Layer_DepthwiseConvolution2dLayer, armnnSerializer::Layer_DequantizeLayer, armnnSerializer::Layer_DetectionPostProcessLayer, armnnSerializer::Layer_DivisionLayer, armnnSerializer::Layer_ElementwiseUnaryLayer, armnnSerializer::Layer_EqualLayer, armnnSerializer::Layer_FillLayer, armnnSerializer::Layer_FloorLayer, armnnSerializer::Layer_FullyConnectedLayer, armnnSerializer::Layer_GatherLayer, armnnSerializer::Layer_GatherNdLayer, armnnSerializer::Layer_GreaterLayer, armnnSerializer::Layer_InputLayer, armnnSerializer::Layer_InstanceNormalizationLayer, armnnSerializer::Layer_L2NormalizationLayer, armnnSerializer::Layer_LogicalBinaryLayer, armnnSerializer::Layer_LogSoftmaxLayer, armnnSerializer::Layer_LstmLayer, armnnSerializer::Layer_MaximumLayer, armnnSerializer::Layer_MeanLayer, armnnSerializer::Layer_MergeLayer, armnnSerializer::Layer_MergerLayer, armnnSerializer::Layer_MinimumLayer, armnnSerializer::Layer_MultiplicationLayer, armnnSerializer::Layer_NONE, armnnSerializer::Layer_NormalizationLayer, armnnSerializer::Layer_OutputLayer, armnnSerializer::Layer_PadLayer, armnnSerializer::Layer_PermuteLayer, armnnSerializer::Layer_Pooling2dLayer, armnnSerializer::Layer_Pooling3dLayer, armnnSerializer::Layer_PreluLayer, armnnSerializer::Layer_QLstmLayer, armnnSerializer::Layer_QuantizedLstmLayer, armnnSerializer::Layer_QuantizeLayer, armnnSerializer::Layer_RankLayer, armnnSerializer::Layer_ReduceLayer, armnnSerializer::Layer_ReshapeLayer, armnnSerializer::Layer_ResizeBilinearLayer, armnnSerializer::Layer_ResizeLayer, armnnSerializer::Layer_RsqrtLayer, armnnSerializer::Layer_ShapeLayer, armnnSerializer::Layer_SliceLayer, armnnSerializer::Layer_SoftmaxLayer, armnnSerializer::Layer_SpaceToBatchNdLayer, armnnSerializer::Layer_SpaceToDepthLayer, armnnSerializer::Layer_SplitterLayer, armnnSerializer::Layer_StackLayer, armnnSerializer::Layer_StandInLayer, armnnSerializer::Layer_StridedSliceLayer, armnnSerializer::Layer_SubtractionLayer, armnnSerializer::Layer_SwitchLayer, armnnSerializer::Layer_TransposeConvolution2dLayer, armnnSerializer::Layer_TransposeLayer, and armnnSerializer::Layer_UnidirectionalSequenceLstmLayer.
Referenced by IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), and IDeserializer::DeserializerImpl::GetOutputs().
 {
     auto layerType = graphPtr->layers()->Get(layerIndex)->layer_type();
     switch(layerType)
     {
         case Layer::Layer_AbsLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_AbsLayer()->base();
         case Layer::Layer_ActivationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ActivationLayer()->base();
         case Layer::Layer_AdditionLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_AdditionLayer()->base();
         case Layer::Layer_ArgMinMaxLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ArgMinMaxLayer()->base();
         case Layer::Layer_BatchToSpaceNdLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_BatchToSpaceNdLayer()->base();
         case Layer::Layer_BatchNormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_BatchNormalizationLayer()->base();
         case Layer::Layer_CastLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_CastLayer()->base();
         case Layer::Layer_ChannelShuffleLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ChannelShuffleLayer()->base();
         case Layer::Layer_ComparisonLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ComparisonLayer()->base();
         case Layer::Layer_ConcatLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ConcatLayer()->base();
         case Layer::Layer_ConstantLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ConstantLayer()->base();
         case Layer::Layer_Convolution2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_Convolution2dLayer()->base();
         case Layer::Layer_Convolution3dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_Convolution3dLayer()->base();
         case Layer::Layer_DepthToSpaceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DepthToSpaceLayer()->base();
         case Layer::Layer_DepthwiseConvolution2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DepthwiseConvolution2dLayer()->base();
         case Layer::Layer_DequantizeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DequantizeLayer()->base();
         case Layer::Layer_DetectionPostProcessLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DetectionPostProcessLayer()->base();
         case Layer::Layer_DivisionLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DivisionLayer()->base();
         case Layer::Layer_EqualLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_EqualLayer()->base();
         case Layer::Layer_ElementwiseUnaryLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ElementwiseUnaryLayer()->base();
         case Layer::Layer_FullyConnectedLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_FullyConnectedLayer()->base();
         case Layer::Layer_FillLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_FillLayer()->base();
         case Layer::Layer_FloorLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_FloorLayer()->base();
         case Layer::Layer_GatherLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_GatherLayer()->base();
         case Layer::Layer_GatherNdLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_GatherNdLayer()->base();
         case Layer::Layer_GreaterLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_GreaterLayer()->base();
         case Layer::Layer_InputLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_InputLayer()->base()->base();
         case Layer::Layer_InstanceNormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_InstanceNormalizationLayer()->base();
         case Layer::Layer_L2NormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_L2NormalizationLayer()->base();
         case Layer::Layer_LogicalBinaryLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_LogicalBinaryLayer()->base();
         case Layer::Layer_LogSoftmaxLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_LogSoftmaxLayer()->base();
         case Layer::Layer_LstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_LstmLayer()->base();
         case Layer::Layer_MeanLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MeanLayer()->base();
         case Layer::Layer_MinimumLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MinimumLayer()->base();
         case Layer::Layer_MaximumLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MaximumLayer()->base();
         case Layer::Layer_MergeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MergeLayer()->base();
         case Layer::Layer_MergerLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MergerLayer()->base();
         case Layer::Layer_MultiplicationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MultiplicationLayer()->base();
         case Layer::Layer_NormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_NormalizationLayer()->base();
         case Layer::Layer_OutputLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_OutputLayer()->base()->base();
         case Layer::Layer_PadLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_PadLayer()->base();
         case Layer::Layer_PermuteLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_PermuteLayer()->base();
         case Layer::Layer_Pooling2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_Pooling2dLayer()->base();
         case Layer::Layer_Pooling3dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_Pooling3dLayer()->base();
         case Layer::Layer_PreluLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_PreluLayer()->base();
         case Layer::Layer_QLstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_QLstmLayer()->base();
         case Layer::Layer_QuantizeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_QuantizeLayer()->base();
         case Layer::Layer_QuantizedLstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_QuantizedLstmLayer()->base();
         case Layer::Layer_RankLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_RankLayer()->base();
         case Layer::Layer_ReduceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ReduceLayer()->base();
         case Layer::Layer_ReshapeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ReshapeLayer()->base();
         case Layer::Layer_ResizeBilinearLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ResizeBilinearLayer()->base();
         case Layer::Layer_ResizeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ResizeLayer()->base();
         case Layer::Layer_RsqrtLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_RsqrtLayer()->base();
         case Layer::Layer_ShapeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ShapeLayer()->base();
         case Layer::Layer_SliceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SliceLayer()->base();
         case Layer::Layer_SoftmaxLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SoftmaxLayer()->base();
         case Layer::Layer_SpaceToBatchNdLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SpaceToBatchNdLayer()->base();
         case Layer::Layer_SpaceToDepthLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SpaceToDepthLayer()->base();
         case Layer::Layer_SplitterLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SplitterLayer()->base();
         case Layer::Layer_StackLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_StackLayer()->base();
         case Layer::Layer_StandInLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_StandInLayer()->base();
         case Layer::Layer_StridedSliceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_StridedSliceLayer()->base();
         case Layer::Layer_SubtractionLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SubtractionLayer()->base();
         case Layer::Layer_SwitchLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SwitchLayer()->base();
         case Layer::Layer_TransposeConvolution2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_TransposeConvolution2dLayer()->base();
         case Layer::Layer_TransposeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_TransposeLayer()->base();
         case Layer::Layer_UnidirectionalSequenceLstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_UnidirectionalSequenceLstmLayer()->base();
         case Layer::Layer_NONE:
         default:
             throw ParseException(fmt::format("Layer type {} not recognized", layerType));
     }
 }
GetBindingLayerInfo()
int32_t GetBindingLayerInfo (const GraphPtr & graphPtr, unsigned int layerIndex) static
Definition at line 436 of file Deserializer.cpp.
References armnnSerializer::Layer_InputLayer, and armnnSerializer::Layer_OutputLayer.
Referenced by IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo().
 {
     auto layerType = graphPtr->layers()->Get(layerIndex)->layer_type();
     if (layerType == Layer::Layer_InputLayer)
     {
         return graphPtr->layers()->Get(layerIndex)->layer_as_InputLayer()->base()->layerBindingId();
     }
     else if ( layerType == Layer::Layer_OutputLayer )
     {
         return graphPtr->layers()->Get(layerIndex)->layer_as_OutputLayer()->base()->layerBindingId();
     }
     return 0;
 }
GetInputs()
TensorRawPtrVector GetInputs (const GraphPtr & graph, unsigned int layerIndex) static
Definition at line 762 of file Deserializer.cpp.
References CHECK_LAYERS, CHECKED_NON_NEGATIVE, and IDeserializer::DeserializerImpl::GetBaseLayer().
Referenced by IDeserializer::DeserializerImpl::GetLstmDescriptor(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), IDeserializer::DeserializerImpl::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), IDeserializer::DeserializerImpl::GetPooling3dDescriptor(), IDeserializer::DeserializerImpl::GetQLstmDescriptor(), IDeserializer::DeserializerImpl::GetUnidirectionalSequenceLstmDescriptor(), and IDeserializer::DeserializerImpl::OutputShapeOfReshape().
 {
     CHECK_LAYERS(graphPtr, 0, layerIndex);
     auto layer = GetBaseLayer(graphPtr, layerIndex);
     const auto& numInputs = layer->inputSlots()->size();
     TensorRawPtrVector result(numInputs);
    for (unsigned int i=0; i<numInputs; ++i)
    {
        auto inputId = CHECKED_NON_NEGATIVE(static_cast<int32_t>
                                           (layer->inputSlots()->Get(i)->connection()->sourceLayerIndex()));
        result[i] = GetBaseLayer(graphPtr, inputId)->outputSlots()->Get(0)->tensorInfo();
    }
    return result;
 }
GetLayerName()
std::string GetLayerName (const GraphPtr & graph, unsigned int index) static
Definition at line 429 of file Deserializer.cpp.
References IDeserializer::DeserializerImpl::GetBaseLayer().
Referenced by IDeserializer::DeserializerImpl::GetLstmDescriptor(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), IDeserializer::DeserializerImpl::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), IDeserializer::DeserializerImpl::GetPooling3dDescriptor(), IDeserializer::DeserializerImpl::GetQLstmDescriptor(), IDeserializer::DeserializerImpl::GetUnidirectionalSequenceLstmDescriptor(), and IDeserializer::DeserializerImpl::OutputShapeOfReshape().
 {
     auto layer = GetBaseLayer(graph, index);
     assert(layer);
     return layer->layerName()->str();
 }
GetLstmDescriptor()
armnn::LstmDescriptor GetLstmDescriptor (LstmDescriptorPtr lstmDescriptor) static
Definition at line 3114 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_VALID_SIZE, IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), LstmDescriptor::m_ActivationFunc, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, LstmDescriptor::m_ClippingThresCell, LstmDescriptor::m_ClippingThresProj, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, LstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, LstmDescriptor::m_PeepholeEnabled, LstmInputParams::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToOutputWeights, IOutputSlot::SetTensorInfo(), armnnDeserializer::ToConstTensor(), and armnnDeserializer::ToTensorInfo().
 {
     armnn::LstmDescriptor desc;
     desc.m_ActivationFunc = lstmDescriptor->activationFunc();
     desc.m_ClippingThresCell = lstmDescriptor->clippingThresCell();
     desc.m_ClippingThresProj = lstmDescriptor->clippingThresProj();
     desc.m_CifgEnabled = lstmDescriptor->cifgEnabled();
     desc.m_PeepholeEnabled = lstmDescriptor->peepholeEnabled();
     desc.m_ProjectionEnabled = lstmDescriptor->projectionEnabled();
     desc.m_LayerNormEnabled = lstmDescriptor->layerNormEnabled();
     return desc;
 }
GetLstmInputParams()
static armnn::LstmInputParams GetLstmInputParams (LstmDescriptorPtr lstmDescriptor, LstmInputParamsPtr lstmInputParams) static
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (unsigned int layerId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Definition at line 895 of file Deserializer.cpp.
References CHECK_LOCATION, and armnn::IgnoreUnused().
 {
     IgnoreUnused(layerIndex);
     for (auto inputBinding : m_InputBindings)
     {
         if (inputBinding.first == name)
         {
             return inputBinding.second;
         }
     }
     throw ParseException(fmt::format("No input binding found for layer:{0} / {1}",
                                      name,
                                      CHECK_LOCATION().AsString()));
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (unsigned int layerId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Definition at line 911 of file Deserializer.cpp.
References armnn::Abs, ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_GRAPH, CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, armnn::Equal, IDeserializer::DeserializerImpl::GetBaseLayer(), IDeserializer::DeserializerImpl::GetBindingLayerInfo(), armnn::GetDataTypeSize(), BaseTensor< MemoryType >::GetInfo(), IDeserializer::DeserializerImpl::GetInputs(), IConnectableLayer::GetInputSlot(), IDeserializer::DeserializerImpl::GetLayerName(), BaseTensor< MemoryType >::GetMemoryArea(), TensorInfo::GetNumBytes(), Convolution2dDescriptor::GetNumInputs(), Convolution3dDescriptor::GetNumInputs(), DepthwiseConvolution2dDescriptor::GetNumInputs(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetNumOutputSlots(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), armnn::Greater, armnn::IgnoreUnused(), armnnSerializer::Layer_InputLayer, armnnSerializer::Layer_OutputLayer, ActivationDescriptor::m_A, ArgMinMaxDescriptor::m_Axis, ActivationDescriptor::m_B, SoftmaxDescriptor::m_Beta, InstanceNormalizationDescriptor::m_Beta, Convolution2dDescriptor::m_BiasEnabled, Convolution3dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, BatchToSpaceNdDescriptor::m_BlockShape, SpaceToDepthDescriptor::m_BlockSize, BatchToSpaceNdDescriptor::m_Crops, Convolution2dDescriptor::m_DataLayout, Convolution3dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, L2NormalizationDescriptor::m_DataLayout, BatchNormalizationDescriptor::m_DataLayout, InstanceNormalizationDescriptor::m_DataLayout, BatchToSpaceNdDescriptor::m_DataLayout, SpaceToDepthDescriptor::m_DataLayout, DetectionPostProcessDescriptor::m_DetectionsPerClass, Convolution2dDescriptor::m_DilationX, Convolution3dDescriptor::m_DilationX, DepthwiseConvolution2dDescriptor::m_DilationX, Convolution2dDescriptor::m_DilationY, Convolution3dDescriptor::m_DilationY, DepthwiseConvolution2dDescriptor::m_DilationY, Convolution3dDescriptor::m_DilationZ, L2NormalizationDescriptor::m_Eps, BatchNormalizationDescriptor::m_Eps, InstanceNormalizationDescriptor::m_Eps, ActivationDescriptor::m_Function, ArgMinMaxDescriptor::m_Function, InstanceNormalizationDescriptor::m_Gamma, DetectionPostProcessDescriptor::m_MaxClassesPerDetection, DetectionPostProcessDescriptor::m_MaxDetections, DetectionPostProcessDescriptor::m_NmsIouThreshold, DetectionPostProcessDescriptor::m_NmsScoreThreshold, DetectionPostProcessDescriptor::m_NumClasses, LogicalBinaryDescriptor::m_Operation, Convolution3dDescriptor::m_PadBack, Convolution2dDescriptor::m_PadBottom, Convolution3dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, Convolution3dDescriptor::m_PadFront, Convolution2dDescriptor::m_PadLeft, Convolution3dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, Convolution3dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, Convolution3dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, DetectionPostProcessDescriptor::m_ScaleH, DetectionPostProcessDescriptor::m_ScaleW, DetectionPostProcessDescriptor::m_ScaleX, DetectionPostProcessDescriptor::m_ScaleY, Convolution2dDescriptor::m_StrideX, Convolution3dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, Convolution3dDescriptor::m_StrideY, DepthwiseConvolution2dDescriptor::m_StrideY, Convolution3dDescriptor::m_StrideZ, DetectionPostProcessDescriptor::m_UseRegularNms, FillDescriptor::m_Value, armnn::numeric_cast(), armnnUtils::Permute(), armnnUtils::Permuted(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToActivationFunction(), armnnDeserializer::ToArgMinMaxFunction(), armnnDeserializer::ToConstTensor(), armnnDeserializer::ToDataLayout(), armnnDeserializer::ToLogicalBinaryOperation(), and armnnDeserializer::ToTensorInfo().
 {
     IgnoreUnused(layerIndex);
     for (auto outputBinding : m_OutputBindings)
     {
         if (outputBinding.first == name)
         {
             return outputBinding.second;
         }
     }
     throw ParseException(fmt::format("No output binding found for layer:{0} / {1}",
                                      name,
                                      CHECK_LOCATION().AsString()));
 }
GetNormalizationDescriptor()
armnn::NormalizationDescriptor GetNormalizationDescriptor (NormalizationDescriptorPtr normalizationDescriptor, unsigned int layerIndex) static
Definition at line 2785 of file Deserializer.cpp.
References armnn::Across, ARMNN_ASSERT_MSG, CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, armnnSerializer::DataLayout_NCHW, armnnSerializer::DataLayout_NHWC, IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), armnn::IgnoreUnused(), armnn::LocalBrightness, armnn::LocalContrast, NormalizationDescriptor::m_Alpha, GatherDescriptor::m_Axis, MeanDescriptor::m_Axis, SliceDescriptor::m_Begin, NormalizationDescriptor::m_Beta, NormalizationDescriptor::m_DataLayout, NormalizationDescriptor::m_K, MeanDescriptor::m_KeepDims, NormalizationDescriptor::m_NormChannelType, NormalizationDescriptor::m_NormMethodType, NormalizationDescriptor::m_NormSize, SliceDescriptor::m_Size, armnn::NCHW, armnn::NHWC, armnnSerializer::NormalizationAlgorithmChannel_Across, armnnSerializer::NormalizationAlgorithmChannel_Within, armnnSerializer::NormalizationAlgorithmMethod_LocalBrightness, armnnSerializer::NormalizationAlgorithmMethod_LocalContrast, armnn::Rsqrt, IOutputSlot::SetTensorInfo(), ViewsDescriptor::SetViewOriginCoord(), ViewsDescriptor::SetViewSize(), armnnDeserializer::ToDataLayout(), armnnDeserializer::ToTensorInfo(), and armnn::Within.
 {
     IgnoreUnused(layerIndex);
     armnn::NormalizationDescriptor desc;
     switch (normalizationDescriptor->normChannelType())
     {
         case NormalizationAlgorithmChannel_Across:
         {
             desc.m_NormChannelType = armnn::NormalizationAlgorithmChannel::Across;
             break;
         }
         case NormalizationAlgorithmChannel_Within:
         {
             desc.m_NormChannelType = armnn::NormalizationAlgorithmChannel::Within;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported normalization channel type");
         }
     }
     switch (normalizationDescriptor->normMethodType())
     {
         case NormalizationAlgorithmMethod_LocalBrightness:
         {
             desc.m_NormMethodType = armnn::NormalizationAlgorithmMethod::LocalBrightness;
             break;
         }
         case NormalizationAlgorithmMethod_LocalContrast:
         {
             desc.m_NormMethodType = armnn::NormalizationAlgorithmMethod::LocalContrast;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported normalization method type");
         }
     }
     switch (normalizationDescriptor->dataLayout())
     {
         case DataLayout_NCHW:
         {
             desc.m_DataLayout = armnn::DataLayout::NCHW;
             break;
         }
         case DataLayout_NHWC:
         {
             desc.m_DataLayout = armnn::DataLayout::NHWC;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported data layout");
         }
     }
     desc.m_Alpha    = normalizationDescriptor->alpha();
     desc.m_Beta     = normalizationDescriptor->beta();
     desc.m_K        = normalizationDescriptor->k();
     desc.m_NormSize = normalizationDescriptor->normSize();
     return desc;
 }
GetOutputs()
TensorRawPtrVector GetOutputs (const GraphPtr & graph, unsigned int layerIndex) static
Definition at line 779 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_LOCATION, and IDeserializer::DeserializerImpl::GetBaseLayer().
Referenced by IDeserializer::DeserializerImpl::GetLstmDescriptor(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), IDeserializer::DeserializerImpl::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), IDeserializer::DeserializerImpl::GetPooling3dDescriptor(), IDeserializer::DeserializerImpl::GetQLstmDescriptor(), IDeserializer::DeserializerImpl::GetUnidirectionalSequenceLstmDescriptor(), and IDeserializer::DeserializerImpl::OutputShapeOfReshape().
 {
     CHECK_LAYERS(graphPtr, 0, layerIndex);
     auto layer = GetBaseLayer(graphPtr, layerIndex);
     const auto& numOutputs = layer->outputSlots()->size();
     TensorRawPtrVector result(numOutputs);
     for (unsigned int i=0; i<numOutputs; ++i)
     {
         result[i] = layer->outputSlots()->Get(i)->tensorInfo();
     }
     return result;
 }
GetPooling2dDescriptor()
armnn::Pooling2dDescriptor GetPooling2dDescriptor (Pooling2dDescriptor pooling2dDescriptor, unsigned int layerIndex) static
Definition at line 2231 of file Deserializer.cpp.
References ARMNN_ASSERT_MSG, armnn::Average, armnn::Ceiling, armnnSerializer::DataLayout_NCHW, armnnSerializer::DataLayout_NHWC, armnn::Exclude, armnn::Floor, armnn::IgnoreUnused(), armnn::IgnoreValue, armnn::L2, Pooling2dDescriptor::m_DataLayout, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, armnn::Max, armnn::NCHW, armnn::NHWC, armnnSerializer::OutputShapeRounding_Ceiling, armnnSerializer::OutputShapeRounding_Floor, armnnSerializer::PaddingMethod_Exclude, armnnSerializer::PaddingMethod_IgnoreValue, armnnSerializer::PoolingAlgorithm_Average, armnnSerializer::PoolingAlgorithm_L2, and armnnSerializer::PoolingAlgorithm_Max.
Referenced by IDeserializer::DeserializerImpl::GetPooling3dDescriptor().
 {
     IgnoreUnused(layerIndex);
     armnn::Pooling2dDescriptor desc;
     switch (pooling2dDesc->poolType())
     {
         case PoolingAlgorithm_Average:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::Average;
             break;
         }
         case PoolingAlgorithm_Max:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::Max;
             break;
         }
         case PoolingAlgorithm_L2:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::L2;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported pooling algorithm");
         }
     }
     switch (pooling2dDesc->outputShapeRounding())
     {
         case OutputShapeRounding_Floor:
         {
             desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Floor;
             break;
         }
         case OutputShapeRounding_Ceiling:
         {
             desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Ceiling;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported output shape rounding");
         }
     }
     switch (pooling2dDesc->paddingMethod())
     {
         case PaddingMethod_Exclude:
         {
             desc.m_PaddingMethod = armnn::PaddingMethod::Exclude;
             break;
         }
         case PaddingMethod_IgnoreValue:
         {
             desc.m_PaddingMethod = armnn::PaddingMethod::IgnoreValue;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported padding method");
         }
     }
     switch (pooling2dDesc->dataLayout())
     {
         case DataLayout_NCHW:
         {
             desc.m_DataLayout = armnn::DataLayout::NCHW;
             break;
         }
         case DataLayout_NHWC:
         {
             desc.m_DataLayout = armnn::DataLayout::NHWC;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported data layout");
         }
     }
     desc.m_PadRight   = pooling2dDesc->padRight();
     desc.m_PadLeft    = pooling2dDesc->padLeft();
     desc.m_PadBottom  = pooling2dDesc->padBottom();
     desc.m_PadTop     = pooling2dDesc->padTop();
     desc.m_StrideX    = pooling2dDesc->strideX();
     desc.m_StrideY    = pooling2dDesc->strideY();
     desc.m_PoolWidth  = pooling2dDesc->poolWidth();
     desc.m_PoolHeight = pooling2dDesc->poolHeight();
     return desc;
 }
GetPooling3dDescriptor()
armnn::Pooling3dDescriptor GetPooling3dDescriptor (Pooling3dDescriptor pooling3dDescriptor, unsigned int layerIndex) static
Definition at line 2326 of file Deserializer.cpp.
References ARMNN_ASSERT_MSG, armnn::Average, armnn::Ceiling, CHECK_LAYERS, CHECK_VALID_SIZE, armnnSerializer::DataLayout_NCDHW, armnnSerializer::DataLayout_NDHWC, armnn::Exclude, armnn::Floor, IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), IDeserializer::DeserializerImpl::GetPooling2dDescriptor(), armnn::IgnoreUnused(), armnn::IgnoreValue, armnn::L2, Pooling3dDescriptor::m_DataLayout, Pooling3dDescriptor::m_OutputShapeRounding, Pooling3dDescriptor::m_PadBack, Pooling3dDescriptor::m_PadBottom, Pooling3dDescriptor::m_PaddingMethod, Pooling3dDescriptor::m_PadFront, Pooling3dDescriptor::m_PadLeft, Pooling3dDescriptor::m_PadRight, Pooling3dDescriptor::m_PadTop, Pooling3dDescriptor::m_PoolDepth, Pooling3dDescriptor::m_PoolHeight, Pooling3dDescriptor::m_PoolType, Pooling3dDescriptor::m_PoolWidth, Pooling3dDescriptor::m_StrideX, Pooling3dDescriptor::m_StrideY, Pooling3dDescriptor::m_StrideZ, armnn::Max, armnn::NCDHW, armnn::NDHWC, armnnSerializer::OutputShapeRounding_Ceiling, armnnSerializer::OutputShapeRounding_Floor, armnnSerializer::PaddingMethod_Exclude, armnnSerializer::PaddingMethod_IgnoreValue, armnnSerializer::PoolingAlgorithm_Average, armnnSerializer::PoolingAlgorithm_L2, armnnSerializer::PoolingAlgorithm_Max, IOutputSlot::SetTensorInfo(), and armnnDeserializer::ToTensorInfo().
 {
     IgnoreUnused(layerIndex);
     armnn::Pooling3dDescriptor desc;
     switch (pooling3dDesc->poolType())
     {
         case PoolingAlgorithm_Average:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::Average;
             break;
         }
         case PoolingAlgorithm_Max:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::Max;
             break;
         }
         case PoolingAlgorithm_L2:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::L2;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported pooling algorithm");
         }
     }
     switch (pooling3dDesc->outputShapeRounding())
     {
         case OutputShapeRounding_Floor:
         {
             desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Floor;
             break;
         }
         case OutputShapeRounding_Ceiling:
         {
             desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Ceiling;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported output shape rounding");
         }
     }
     switch (pooling3dDesc->paddingMethod())
     {
         case PaddingMethod_Exclude:
         {
             desc.m_PaddingMethod = armnn::PaddingMethod::Exclude;
             break;
         }
         case PaddingMethod_IgnoreValue:
         {
             desc.m_PaddingMethod = armnn::PaddingMethod::IgnoreValue;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported padding method");
         }
     }
     switch (pooling3dDesc->dataLayout())
     {
         case DataLayout_NCDHW:
         {
             desc.m_DataLayout = armnn::DataLayout::NCDHW;
             break;
         }
         case DataLayout_NDHWC:
         {
             desc.m_DataLayout = armnn::DataLayout::NDHWC;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported data layout");
         }
     }
     desc.m_PadRight   = pooling3dDesc->padRight();
     desc.m_PadLeft    = pooling3dDesc->padLeft();
     desc.m_PadBottom  = pooling3dDesc->padBottom();
     desc.m_PadTop     = pooling3dDesc->padTop();
     desc.m_PadFront   = pooling3dDesc->padFront();
     desc.m_PadBack    = pooling3dDesc->padBack();
     desc.m_StrideX    = pooling3dDesc->strideX();
     desc.m_StrideY    = pooling3dDesc->strideY();
     desc.m_StrideZ    = pooling3dDesc->strideZ();
     desc.m_PoolWidth  = pooling3dDesc->poolWidth();
     desc.m_PoolHeight = pooling3dDesc->poolHeight();
     desc.m_PoolDepth  = pooling3dDesc->poolDepth();
     return desc;
 }
GetQLstmDescriptor()
armnn::QLstmDescriptor GetQLstmDescriptor (QLstmDescriptorPtr qLstmDescriptorPtr) static
Definition at line 3245 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), TransposeConvolution2dDescriptor::m_BiasEnabled, QuantizedLstmInputParams::m_CellBias, LstmInputParams::m_CellBias, QLstmDescriptor::m_CellClip, QLstmDescriptor::m_CellIntermediateScale, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, QLstmDescriptor::m_CifgEnabled, TransposeConvolution2dDescriptor::m_DataLayout, QuantizedLstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetGateBias, QLstmDescriptor::m_ForgetIntermediateScale, LstmInputParams::m_ForgetLayerNormWeights, QLstmDescriptor::m_HiddenStateScale, QLstmDescriptor::m_HiddenStateZeroPoint, QuantizedLstmInputParams::m_InputGateBias, LstmInputParams::m_InputGateBias, QLstmDescriptor::m_InputIntermediateScale, LstmInputParams::m_InputLayerNormWeights, QuantizedLstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToCellWeights, QuantizedLstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToForgetWeights, QuantizedLstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToInputWeights, QuantizedLstmInputParams::m_InputToOutputWeights, LstmInputParams::m_InputToOutputWeights, QLstmDescriptor::m_LayerNormEnabled, StandInDescriptor::m_NumInputs, StandInDescriptor::m_NumOutputs, QuantizedLstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputGateBias, QLstmDescriptor::m_OutputIntermediateScale, LstmInputParams::m_OutputLayerNormWeights, TransposeConvolution2dDescriptor::m_PadBottom, TransposeConvolution2dDescriptor::m_PadLeft, TransposeConvolution2dDescriptor::m_PadRight, TransposeConvolution2dDescriptor::m_PadTop, QLstmDescriptor::m_PeepholeEnabled, LstmInputParams::m_ProjectionBias, QLstmDescriptor::m_ProjectionClip, QLstmDescriptor::m_ProjectionEnabled, LstmInputParams::m_ProjectionWeights, QuantizedLstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToCellWeights, QuantizedLstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToForgetWeights, QuantizedLstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToInputWeights, QuantizedLstmInputParams::m_RecurrentToOutputWeights, LstmInputParams::m_RecurrentToOutputWeights, TransposeConvolution2dDescriptor::m_StrideX, TransposeConvolution2dDescriptor::m_StrideY, IOutputSlot::SetTensorInfo(), armnnDeserializer::ToConstTensor(), armnnDeserializer::ToDataLayout(), and armnnDeserializer::ToTensorInfo().
 {
     armnn::QLstmDescriptor desc;
     desc.m_CifgEnabled       = qLstmDescriptor->cifgEnabled();
     desc.m_PeepholeEnabled   = qLstmDescriptor->peepholeEnabled();
     desc.m_ProjectionEnabled = qLstmDescriptor->projectionEnabled();
     desc.m_LayerNormEnabled  = qLstmDescriptor->layerNormEnabled();
     desc.m_CellClip       = qLstmDescriptor->cellClip();
     desc.m_ProjectionClip = qLstmDescriptor->projectionClip();
     desc.m_InputIntermediateScale  = qLstmDescriptor->inputIntermediateScale();
     desc.m_ForgetIntermediateScale = qLstmDescriptor->forgetIntermediateScale();
     desc.m_CellIntermediateScale   = qLstmDescriptor->cellIntermediateScale();
     desc.m_OutputIntermediateScale = qLstmDescriptor->outputIntermediateScale();
     desc.m_HiddenStateScale     = qLstmDescriptor->hiddenStateScale();
     desc.m_HiddenStateZeroPoint = qLstmDescriptor->hiddenStateZeroPoint();
     return desc;
 }
GetUnidirectionalSequenceLstmDescriptor()
armnn::UnidirectionalSequenceLstmDescriptor GetUnidirectionalSequenceLstmDescriptor (UnidirectionalSequenceLstmDescriptorPtr descriptor) static
Definition at line 3677 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_VALID_SIZE, IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), LstmDescriptor::m_ActivationFunc, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, LstmDescriptor::m_ClippingThresCell, LstmDescriptor::m_ClippingThresProj, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, LstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, LstmDescriptor::m_PeepholeEnabled, LstmInputParams::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToOutputWeights, LstmDescriptor::m_TimeMajor, IOutputSlot::SetTensorInfo(), armnnDeserializer::ToConstTensor(), and armnnDeserializer::ToTensorInfo().
 {
     armnn::UnidirectionalSequenceLstmDescriptor desc;
     desc.m_ActivationFunc = descriptor->activationFunc();
     desc.m_ClippingThresCell = descriptor->clippingThresCell();
     desc.m_ClippingThresProj = descriptor->clippingThresProj();
     desc.m_CifgEnabled = descriptor->cifgEnabled();
     desc.m_PeepholeEnabled = descriptor->peepholeEnabled();
     desc.m_ProjectionEnabled = descriptor->projectionEnabled();
     desc.m_LayerNormEnabled = descriptor->layerNormEnabled();
     desc.m_TimeMajor = descriptor->timeMajor();
     return desc;
 }
LoadGraphFromBinary()
GraphPtr LoadGraphFromBinary (const uint8_t * binaryContent, size_t len) static
Definition at line 836 of file Deserializer.cpp.
References ARMNN_ASSERT, CHECK_LOCATION, IOutputSlot::Connect(), armnnSerializer::GetSerializedGraph(), armnnSerializer::Layer_InputLayer, and armnnSerializer::Layer_OutputLayer.
Referenced by IDeserializer::DeserializerImpl::CreateNetworkFromBinary().
 {
     if (binaryContent == nullptr)
     {
         throw InvalidArgumentException(fmt::format("Invalid (null) binary content {}",
                                                    CHECK_LOCATION().AsString()));
     }
     flatbuffers::Verifier verifier(binaryContent, len);
     if (verifier.VerifyBuffer<SerializedGraph>() == false)
     {
         throw ParseException(fmt::format("Buffer doesn't conform to the expected Armnn "
                                          "flatbuffers format. size:{0} {1}",
                                          len,
                                          CHECK_LOCATION().AsString()));
     }
     return GetSerializedGraph(binaryContent);
 }
operator=()
DeserializerImpl& operator= (const DeserializerImpl &) delete
OutputShapeOfReshape()
armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo & inputTensorInfo, const std::vector< uint32_t > & targetDimsIn) static
Definition at line 2486 of file Deserializer.cpp.
References armnn::Bilinear, CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, armnnDeserializer::CheckShape(), IDeserializer::DeserializerImpl::GetInputs(), IDeserializer::DeserializerImpl::GetLayerName(), TensorInfo::GetNumElements(), IDeserializer::DeserializerImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), ResizeDescriptor::m_AlignCorners, SoftmaxDescriptor::m_Beta, SpaceToBatchNdDescriptor::m_BlockShape, SpaceToDepthDescriptor::m_BlockSize, ResizeDescriptor::m_DataLayout, SpaceToBatchNdDescriptor::m_DataLayout, SpaceToDepthDescriptor::m_DataLayout, ResizeDescriptor::m_HalfPixelCenters, ReduceDescriptor::m_KeepDims, ResizeDescriptor::m_Method, SpaceToBatchNdDescriptor::m_PadList, ReduceDescriptor::m_ReduceOperation, ResizeDescriptor::m_TargetHeight, ReshapeDescriptor::m_TargetShape, ResizeDescriptor::m_TargetWidth, ReduceDescriptor::m_vAxis, armnn::numeric_cast(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToDataLayout(), armnnDeserializer::ToReduceOperation(), armnnDeserializer::ToResizeMethod(), and armnnDeserializer::ToTensorInfo().
 {
     std::vector<unsigned int> outputDims(targetDimsIn.begin(), targetDimsIn.end());
     const auto stretchDim = std::find(targetDimsIn.begin(), targetDimsIn.end(), -1);
     if (stretchDim != targetDimsIn.end())
     {
         if (std::find(std::next(stretchDim), targetDimsIn.end(), -1) != targetDimsIn.end())
         {
             throw ParseException(fmt::format("At most one component of shape can be -1 {}",
                                              CHECK_LOCATION().AsString()));
         }
         auto targetNumElements =
            armnn::numeric_cast<unsigned int>(
                std::accumulate(targetDimsIn.begin(), targetDimsIn.end(), -1, std::multiplies<int32_t>()));
         auto stretchIndex = static_cast<size_t>(std::distance(targetDimsIn.begin(), stretchDim));
         outputDims[stretchIndex] = inputTensorInfo.GetNumElements() / targetNumElements;
     }
     TensorShape outputShape = TensorShape(static_cast<unsigned int>(outputDims.size()), outputDims.data());
     armnn::TensorInfo reshapeInfo = inputTensorInfo;
     reshapeInfo.SetShape(outputShape);
     return reshapeInfo;
 }
The documentation for this class was generated from the following files:
src/armnnDeserializer/Deserializer.hpp
src/armnnDeserializer/Deserializer.cpp