ArmNN: NeonTimer Class Reference
NeonTimer Class Reference
#include <NeonTimer.hpp>
Public Types
using KernelMeasurements = std::vector< Measurement >
Public Member Functions
NeonTimer ()=default
~NeonTimer ()=default
void Start () override
void Stop () override
std::vector< Measurement > GetMeasurements () const override
const char * GetName () const override
Public Member Functions inherited from Instrument
virtual ~Instrument ()
Detailed Description
Definition at line 21 of file NeonTimer.hpp.
Member Typedef Documentation
KernelMeasurements
using KernelMeasurements = std::vector<Measurement>
Definition at line 24 of file NeonTimer.hpp.
Constructor & Destructor Documentation
NeonTimer()
NeonTimer () default
~NeonTimer()
~NeonTimer () default
Member Function Documentation
GetMeasurements()
std::vector< Measurement > GetMeasurements () const override virtual
Implements Instrument.
Definition at line 45 of file NeonTimer.cpp.
References NeonTimer::GetName().
 {
     std::vector<Measurement> measurements = m_Kernels;
     unsigned int kernel_number = 0;
     for (auto & kernel : measurements)
     {
         std::string kernelName = std::string(this->GetName()) + "/" + std::to_string(kernel_number++) + ": " + kernel
                 .m_Name;
         kernel.m_Name = kernelName;
     }
     return measurements;
 }
GetName()
const char * GetName () const override virtual
Implements Instrument.
Definition at line 58 of file NeonTimer.cpp.
Referenced by NeonTimer::GetMeasurements(), and TEST_SUITE().
 {
     return "NeonKernelTimer";
 }
Start()
void Start () override virtual
Implements Instrument.
Definition at line 21 of file NeonTimer.cpp.
References ARMNN_ASSERT.
Referenced by TEST_SUITE().
 {
     m_Kernels.clear();
     ARMNN_ASSERT(g_Interceptor->GetKernels() == nullptr);
     g_Interceptor->SetKernels(&m_Kernels);
     m_RealSchedulerType = arm_compute::Scheduler::get_type();
     //Note: We can't currently replace a custom scheduler
     if(m_RealSchedulerType != arm_compute::Scheduler::Type::CUSTOM)
     {
         // Keep the real schedule and add NeonInterceptorScheduler as an interceptor
         m_RealScheduler  = &arm_compute::Scheduler::get();
         arm_compute::Scheduler::set(armnn::PolymorphicPointerDowncast<arm_compute::IScheduler>(g_Interceptor));
     }
 }
Stop()
void Stop () override virtual
Implements Instrument.
Definition at line 37 of file NeonTimer.cpp.
 {
     // Restore real scheduler
     g_Interceptor->SetKernels(nullptr);
     arm_compute::Scheduler::set(m_RealSchedulerType);
     m_RealScheduler = nullptr;
 }
The documentation for this class was generated from the following files:
src/backends/neon/NeonTimer.hpp
src/backends/neon/NeonTimer.cpp