ArmNN: IProfiler Class Reference
IProfiler Class Reference
#include <IProfiler.hpp>
Public Member Functions
void EnableProfiling (bool enableProfiling)
Enables/disables profiling for this profiler.
bool IsProfilingEnabled ()
Checks whether profiling is enabled.
void AnalyzeEventsAndWriteResults (std::ostream &outStream) const
Analyzes the tracked events and writes the results to the given output stream.
void Print (std::ostream &outStream) const
Print stats for events in JSON Format to the given output stream.
void EnableNetworkDetailsToStdOut (ProfilingDetailsMethod detailsMethod)
Print out details of each layer within the network that possesses a descriptor.
~IProfiler ()
IProfiler ()
Friends
class ScopedProfilingEvent
template<typename DescriptorType >
void ProfilingUpdateDescriptions (const std::string &name, const DescriptorType &desc, const WorkloadInfo &infos, const arm::pipe::ProfilingGuid guid)
size_t GetProfilerEventSequenceSize (armnn::IProfiler *profiler)
Detailed Description
Definition at line 21 of file IProfiler.hpp.
Constructor & Destructor Documentation
~IProfiler()
~IProfiler () default
Referenced by IProfiler::Print().
IProfiler()
IProfiler ()
Definition at line 623 of file Profiling.cpp.
                      : pProfilerImpl(new ProfilerImpl())
 {};
Member Function Documentation
AnalyzeEventsAndWriteResults()
void AnalyzeEventsAndWriteResults (std::ostream & outStream) const
Analyzes the tracked events and writes the results to the given output stream.
Please refer to the configuration variables in Profiling.cpp to customize the information written.
Parameters
[out] outStream The stream where to write the profiling results to.
Definition at line 604 of file Profiling.cpp.
Referenced by TEST_SUITE().
 {
     pProfilerImpl->AnalyzeEventsAndWriteResults(outStream);
 }
EnableNetworkDetailsToStdOut()
void EnableNetworkDetailsToStdOut (ProfilingDetailsMethod detailsMethod)
Print out details of each layer within the network that possesses a descriptor.
Also outputs tensor info. This will be part of the profiling json output
Definition at line 594 of file Profiling.cpp.
 {
     pProfilerImpl->EnableNetworkDetailsToStdOut(detailsMethod);
 }
EnableProfiling()
void EnableProfiling (bool enableProfiling)
Enables/disables profiling for this profiler.
Parameters
[in] enableProfiling A flag that indicates whether profiling should be enabled or not.
Definition at line 589 of file Profiling.cpp.
 {
     pProfilerImpl->EnableProfiling(enableProfiling);
 }
IsProfilingEnabled()
bool IsProfilingEnabled ()
Checks whether profiling is enabled.
Profiling is disabled by default.
Returns
true if profiling is enabled, false otherwise.
Definition at line 599 of file Profiling.cpp.
Referenced by armnn::ProfilingUpdateDescriptions().
 {
     return pProfilerImpl->IsProfilingEnabled();
 }
Print()
void Print (std::ostream & outStream) const
Print stats for events in JSON Format to the given output stream.
Parameters
[out] outStream The stream where to write the profiling results to.
Definition at line 609 of file Profiling.cpp.
References IProfiler::~IProfiler().
Referenced by TEST_SUITE().
 {
     pProfilerImpl->Print(outStream);
 }
Friends And Related Function Documentation
GetProfilerEventSequenceSize
size_t GetProfilerEventSequenceSize (armnn::IProfiler * profiler) friend
Definition at line 19 of file ProfilerTests.cpp.
 {
     if (!profiler)
     {
         return static_cast<size_t>(-1);
     }
     return profiler->pProfilerImpl->m_EventSequence.size();
 }
ProfilingUpdateDescriptions
void ProfilingUpdateDescriptions (const std::string & name, const DescriptorType & desc, const WorkloadInfo & infos, const arm::pipe::ProfilingGuid guid) friend
< Profiler used
Definition at line 180 of file Profiling.hpp.
 {
     IProfiler* profiler(ProfilerManager::GetInstance().GetProfiler()); ///< Profiler used
     if (profiler && profiler->IsProfilingEnabled())
     {
         profiler->AddLayerDetails(name, desc, infos, guid);
     }
 }
ScopedProfilingEvent
friend class ScopedProfilingEvent friend
Definition at line 66 of file IProfiler.hpp.
The documentation for this class was generated from the following files:
include/armnn/IProfiler.hpp
src/armnn/Profiling.cpp
src/armnn/Profiling.hpp