ArmNN: FloatingPointConverter Class Reference
FloatingPointConverter Class Reference
#include <FloatingPointConverter.hpp>
Static Public Member Functions
static void ConvertFloat32To16 (const float *srcFloat32Buffer, size_t numElements, void *dstFloat16Buffer)
Converts a buffer of FP32 values to FP16, and stores in the given dstFloat16Buffer.
static void ConvertFloat16To32 (const void *srcFloat16Buffer, size_t numElements, float *dstFloat32Buffer)
static void ConvertFloat32ToBFloat16 (const float *srcFloat32Buffer, size_t numElements, void *dstBFloat16Buffer)
static void ConvertBFloat16ToFloat32 (const void *srcBFloat16Buffer, size_t numElements, float *dstFloat32Buffer)
Detailed Description
Definition at line 13 of file FloatingPointConverter.hpp.
Member Function Documentation
ConvertBFloat16ToFloat32()
void ConvertBFloat16ToFloat32 (const void * srcBFloat16Buffer, size_t numElements, float * dstFloat32Buffer) static
Definition at line 61 of file FloatingPointConverter.cpp.
References ARMNN_ASSERT, and BFloat16::ToFloat32().
Referenced by armnn::ConvertBf16ToFp32Weight(), BFloat16Decoder::DecodeTensor(), NeonConvertBf16ToFp32Workload::Execute(), RefConvertBf16ToFp32Workload::ExecuteAsync(), BFloat16ToFloat32::Func(), BFloat16Decoder::Get(), BFloat16Encoder::Get(), and TEST_SUITE().
 {
     ARMNN_ASSERT(srcBFloat16Buffer != nullptr);
     ARMNN_ASSERT(dstFloat32Buffer != nullptr);
     const armnn::BFloat16* bf16 = static_cast<const armnn::BFloat16*>(srcBFloat16Buffer);
     for (size_t i = 0; i < numElements; i++)
     {
         dstFloat32Buffer[i] = bf16[i].ToFloat32();
     }
 }
ConvertFloat16To32()
void ConvertFloat16To32 (const void * srcFloat16Buffer, size_t numElements, float * dstFloat32Buffer) static
Definition at line 31 of file FloatingPointConverter.cpp.
References ARMNN_ASSERT.
Referenced by armnn::AttemptBackendAssignment(), Float16Decoder::DecodeTensor(), NeonConvertFp16ToFp32Workload::Execute(), RefConvertFp16ToFp32Workload::ExecuteAsync(), Float16ToFloat32::Func(), Float16Decoder::Get(), Float16Encoder::Get(), ConvertConstDequantisationLayersToConstLayersImpl::Run(), and TEST_SUITE().
 {
     ARMNN_ASSERT(srcFloat16Buffer != nullptr);
     ARMNN_ASSERT(dstFloat32Buffer != nullptr);
     const armnn::Half* pHalf = static_cast<const armnn::Half*>(srcFloat16Buffer);
     for (size_t i = 0; i < numElements; i++)
     {
         dstFloat32Buffer[i] = pHalf[i];
     }
 }
ConvertFloat32To16()
void ConvertFloat32To16 (const float * srcFloat32Buffer, size_t numElements, void * dstFloat16Buffer) static
Converts a buffer of FP32 values to FP16, and stores in the given dstFloat16Buffer.
dstFloat16Buffer should be (numElements * 2) in size
Definition at line 16 of file FloatingPointConverter.cpp.
References ARMNN_ASSERT.
Referenced by NeonConvertFp32ToFp16Workload::Execute(), RefConvertFp32ToFp16Workload::ExecuteAsync(), Float32ToFloat16::Func(), Float16Encoder::Set(), and TEST_SUITE().
 {
     ARMNN_ASSERT(srcFloat32Buffer != nullptr);
     ARMNN_ASSERT(dstFloat16Buffer != nullptr);
     armnn::Half* pHalf = static_cast<armnn::Half*>(dstFloat16Buffer);
     for (size_t i = 0; i < numElements; i++)
     {
         pHalf[i] = armnn::Half(srcFloat32Buffer[i]);
     }
 }
ConvertFloat32ToBFloat16()
void ConvertFloat32ToBFloat16 (const float * srcFloat32Buffer, size_t numElements, void * dstBFloat16Buffer) static
Definition at line 46 of file FloatingPointConverter.cpp.
References ARMNN_ASSERT.
Referenced by armnn::optimizations::ConvertWeight(), NeonConvertFp32ToBf16Workload::Execute(), RefConvertFp32ToBf16Workload::ExecuteAsync(), Float32ToBFloat16::Func(), BFloat16Encoder::Set(), and TEST_SUITE().
 {
     ARMNN_ASSERT(srcFloat32Buffer != nullptr);
     ARMNN_ASSERT(dstBFloat16Buffer != nullptr);
     armnn::BFloat16* bf16 = static_cast<armnn::BFloat16*>(dstBFloat16Buffer);
     for (size_t i = 0; i < numElements; i++)
     {
         bf16[i] = armnn::BFloat16(srcFloat32Buffer[i]);
     }
 }
The documentation for this class was generated from the following files:
include/armnnUtils/FloatingPointConverter.hpp
src/armnnUtils/FloatingPointConverter.cpp