ArmNN: MockCounterDirectory Class Reference
MockCounterDirectory Class Reference
#include <ProfilingMocks.hpp>
Public Member Functions
MockCounterDirectory ()=default
~MockCounterDirectory ()=default
const Category * RegisterCategory (const std::string &categoryName)
const Device * RegisterDevice (const std::string &deviceName, uint16_t cores=0)
const CounterSet * RegisterCounterSet (const std::string &counterSetName, uint16_t count=0)
const Counter * RegisterCounter (const std::string &backendId, const uint16_t uid, const std::string &parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string &name, const std::string &description, const arm::pipe::Optional< std::string > &units=arm::pipe::EmptyOptional(), const arm::pipe::Optional< uint16_t > &numberOfCores=arm::pipe::EmptyOptional(), const arm::pipe::Optional< uint16_t > &deviceUid=arm::pipe::EmptyOptional(), const arm::pipe::Optional< uint16_t > &counterSetUid=arm::pipe::EmptyOptional())
uint16_t GetCategoryCount () const override
uint16_t GetDeviceCount () const override
uint16_t GetCounterSetCount () const override
uint16_t GetCounterCount () const override
const Categories & GetCategories () const override
const Devices & GetDevices () const override
const CounterSets & GetCounterSets () const override
const Counters & GetCounters () const override
const Category * GetCategory (const std::string &name) const override
const Device * GetDevice (uint16_t uid) const override
const CounterSet * GetCounterSet (uint16_t uid) const override
const Counter * GetCounter (uint16_t uid) const override
Detailed Description
Definition at line 447 of file ProfilingMocks.hpp.
Constructor & Destructor Documentation
MockCounterDirectory()
MockCounterDirectory () default
~MockCounterDirectory()
~MockCounterDirectory () default
Member Function Documentation
GetCategories()
const Categories& GetCategories () const inline override
Definition at line 583 of file ProfilingMocks.hpp.
 { return m_Categories;  }
GetCategory()
const Category* GetCategory (const std::string & name) const inline override
Definition at line 589 of file ProfilingMocks.hpp.
     {
         auto it = std::find_if(m_Categories.begin(), m_Categories.end(), [&name](const CategoryPtr& category)
         {
             ARM_PIPE_ASSERT(category);
             return category->m_Name == name;
         });
         if (it == m_Categories.end())
         {
             return nullptr;
         }
         return it->get();
     }
GetCategoryCount()
uint16_t GetCategoryCount () const inline override
Definition at line 577 of file ProfilingMocks.hpp.
References armnn::numeric_cast().
 { return arm::pipe::numeric_cast<uint16_t>(m_Categories.size());  }
GetCounter()
const Counter* GetCounter (uint16_t uid) const inline override
Definition at line 618 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
     {
         arm::pipe::IgnoreUnused(uid);
         return nullptr; // Not used by the unit tests
     }
GetCounterCount()
uint16_t GetCounterCount () const inline override
Definition at line 580 of file ProfilingMocks.hpp.
References armnn::numeric_cast().
 { return arm::pipe::numeric_cast<uint16_t>(m_Counters.size());    }
GetCounters()
const Counters& GetCounters () const inline override
Definition at line 586 of file ProfilingMocks.hpp.
 { return m_Counters;    }
GetCounterSet()
const CounterSet* GetCounterSet (uint16_t uid) const inline override
Definition at line 612 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
     {
         arm::pipe::IgnoreUnused(uid);
         return nullptr; // Not used by the unit tests
     }
GetCounterSetCount()
uint16_t GetCounterSetCount () const inline override
Definition at line 579 of file ProfilingMocks.hpp.
References armnn::numeric_cast().
 { return arm::pipe::numeric_cast<uint16_t>(m_CounterSets.size()); }
GetCounterSets()
const CounterSets& GetCounterSets () const inline override
Definition at line 585 of file ProfilingMocks.hpp.
 { return m_CounterSets; }
GetDevice()
const Device* GetDevice (uint16_t uid) const inline override
Definition at line 606 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
     {
         arm::pipe::IgnoreUnused(uid);
         return nullptr; // Not used by the unit tests
     }
GetDeviceCount()
uint16_t GetDeviceCount () const inline override
Definition at line 578 of file ProfilingMocks.hpp.
References armnn::numeric_cast().
 { return arm::pipe::numeric_cast<uint16_t>(m_Devices.size());     }
GetDevices()
const Devices& GetDevices () const inline override
Definition at line 584 of file ProfilingMocks.hpp.
 { return m_Devices;     }
RegisterCategory()
const Category* RegisterCategory (const std::string & categoryName) inline
Definition at line 454 of file ProfilingMocks.hpp.
     {
         // Create the category
         CategoryPtr category = std::make_unique<Category>(categoryName);
         ARM_PIPE_ASSERT(category);
         // Get the raw category pointer
         const Category* categoryPtr = category.get();
         ARM_PIPE_ASSERT(categoryPtr);
         // Register the category
         m_Categories.insert(std::move(category));
         return categoryPtr;
     }
RegisterCounter()
const Counter* RegisterCounter (const std::string & backendId, const uint16_t uid, const std::string & parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string & name, const std::string & description, const arm::pipe::Optional< std::string > & units = arm::pipe::EmptyOptional(), const arm::pipe::Optional< uint16_t > & numberOfCores = arm::pipe::EmptyOptional(), const arm::pipe::Optional< uint16_t > & deviceUid = arm::pipe::EmptyOptional(), const arm::pipe::Optional< uint16_t > & counterSetUid = arm::pipe::EmptyOptional()) inline
Definition at line 511 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
     {
         arm::pipe::IgnoreUnused(backendId);
         // Get the number of cores from the argument only
         uint16_t deviceCores = numberOfCores.has_value() ? numberOfCores.value() : 0;
         // Get the device UID
         uint16_t deviceUidValue = deviceUid.has_value() ? deviceUid.value() : 0;
         // Get the counter set UID
         uint16_t counterSetUidValue = counterSetUid.has_value() ? counterSetUid.value() : 0;
         // Get the counter UIDs and calculate the max counter UID
         std::vector<uint16_t> counterUids = GetNextCounterUids(uid, deviceCores);
         ARM_PIPE_ASSERT(!counterUids.empty());
         uint16_t maxCounterUid = deviceCores <= 1 ? counterUids.front() : counterUids.back();
         // Get the counter units
         const std::string unitsValue = units.has_value() ? units.value() : "";
         // Create the counter
         CounterPtr counter = std::make_shared<Counter>(armnn::profiling::BACKEND_ID,
                                                        counterUids.front(),
                                                        maxCounterUid,
                                                        counterClass,
                                                        interpolation,
                                                        multiplier,
                                                        name,
                                                        description,
                                                        unitsValue,
                                                        deviceUidValue,
                                                        counterSetUidValue);
         ARM_PIPE_ASSERT(counter);
         // Get the raw counter pointer
         const Counter* counterPtr = counter.get();
         ARM_PIPE_ASSERT(counterPtr);
         // Process multiple counters if necessary
         for (uint16_t counterUid : counterUids)
         {
             // Connect the counter to the parent category
             Category* parentCategory = const_cast<Category*>(GetCategory(parentCategoryName));
             ARM_PIPE_ASSERT(parentCategory);
             parentCategory->m_Counters.push_back(counterUid);
             // Register the counter
             m_Counters.insert(std::make_pair(counterUid, counter));
         }
         return counterPtr;
     }
RegisterCounterSet()
const CounterSet* RegisterCounterSet (const std::string & counterSetName, uint16_t count = 0) inline
Definition at line 490 of file ProfilingMocks.hpp.
     {
         // Get the counter set UID
         uint16_t counterSetUid = GetNextUid();
         // Create the counter set
         CounterSetPtr counterSet = std::make_unique<CounterSet>(counterSetUid, counterSetName, count);
         ARM_PIPE_ASSERT(counterSet);
         // Get the raw counter set pointer
         const CounterSet* counterSetPtr = counterSet.get();
         ARM_PIPE_ASSERT(counterSetPtr);
         // Register the counter set
         m_CounterSets.insert(std::make_pair(counterSetUid, std::move(counterSet)));
         return counterSetPtr;
     }
RegisterDevice()
const Device* RegisterDevice (const std::string & deviceName, uint16_t cores = 0) inline
Definition at line 470 of file ProfilingMocks.hpp.
     {
         // Get the device UID
         uint16_t deviceUid = GetNextUid();
         // Create the device
         DevicePtr device = std::make_unique<Device>(deviceUid, deviceName, cores);
         ARM_PIPE_ASSERT(device);
         // Get the raw device pointer
         const Device* devicePtr = device.get();
         ARM_PIPE_ASSERT(devicePtr);
         // Register the device
         m_Devices.insert(std::make_pair(deviceUid, std::move(device)));
         return devicePtr;
     }
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingMocks.hpp