ArmNN: StridedSliceDescriptorBuilder Struct Reference
StridedSliceDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef StridedSliceDescriptor Table
Public Member Functions
void add_begin (flatbuffers::Offset< flatbuffers::Vector< int32_t >> begin)
void add_end (flatbuffers::Offset< flatbuffers::Vector< int32_t >> end)
void add_stride (flatbuffers::Offset< flatbuffers::Vector< int32_t >> stride)
void add_beginMask (int32_t beginMask)
void add_endMask (int32_t endMask)
void add_shrinkAxisMask (int32_t shrinkAxisMask)
void add_ellipsisMask (int32_t ellipsisMask)
void add_newAxisMask (int32_t newAxisMask)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
StridedSliceDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
StridedSliceDescriptorBuilder & operator= (const StridedSliceDescriptorBuilder &)
flatbuffers::Offset< StridedSliceDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7382 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef StridedSliceDescriptor Table
Definition at line 7383 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
StridedSliceDescriptorBuilder()
StridedSliceDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7413 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_begin()
void add_begin (flatbuffers::Offset< flatbuffers::Vector< int32_t >> begin) inline
Definition at line 7386 of file ArmnnSchema_generated.h.
References VT_BEGIN.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddOffset(StridedSliceDescriptor::VT_BEGIN, begin);
   }
add_beginMask()
void add_beginMask (int32_t beginMask) inline
Definition at line 7395 of file ArmnnSchema_generated.h.
References VT_BEGINMASK.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddElement<int32_t>(StridedSliceDescriptor::VT_BEGINMASK, beginMask, 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 7410 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddElement<int8_t>(StridedSliceDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_ellipsisMask()
void add_ellipsisMask (int32_t ellipsisMask) inline
Definition at line 7404 of file ArmnnSchema_generated.h.
References VT_ELLIPSISMASK.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddElement<int32_t>(StridedSliceDescriptor::VT_ELLIPSISMASK, ellipsisMask, 0);
   }
add_end()
void add_end (flatbuffers::Offset< flatbuffers::Vector< int32_t >> end) inline
Definition at line 7389 of file ArmnnSchema_generated.h.
References VT_END.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddOffset(StridedSliceDescriptor::VT_END, end);
   }
add_endMask()
void add_endMask (int32_t endMask) inline
Definition at line 7398 of file ArmnnSchema_generated.h.
References VT_ENDMASK.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddElement<int32_t>(StridedSliceDescriptor::VT_ENDMASK, endMask, 0);
   }
add_newAxisMask()
void add_newAxisMask (int32_t newAxisMask) inline
Definition at line 7407 of file ArmnnSchema_generated.h.
References VT_NEWAXISMASK.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddElement<int32_t>(StridedSliceDescriptor::VT_NEWAXISMASK, newAxisMask, 0);
   }
add_shrinkAxisMask()
void add_shrinkAxisMask (int32_t shrinkAxisMask) inline
Definition at line 7401 of file ArmnnSchema_generated.h.
References VT_SHRINKAXISMASK.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddElement<int32_t>(StridedSliceDescriptor::VT_SHRINKAXISMASK, shrinkAxisMask, 0);
   }
add_stride()
void add_stride (flatbuffers::Offset< flatbuffers::Vector< int32_t >> stride) inline
Definition at line 7392 of file ArmnnSchema_generated.h.
References VT_STRIDE.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     fbb_.AddOffset(StridedSliceDescriptor::VT_STRIDE, stride);
   }
Finish()
flatbuffers::Offset<StridedSliceDescriptor> Finish () inline
Definition at line 7418 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateStridedSliceDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<StridedSliceDescriptor>(end);
     return o;
   }
operator=()
StridedSliceDescriptorBuilder& operator= (const StridedSliceDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7384 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7385 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h