ArmNN: OriginsDescriptorBuilder Struct Reference
OriginsDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef OriginsDescriptor Table
Public Member Functions
void add_concatAxis (uint32_t concatAxis)
void add_numViews (uint32_t numViews)
void add_numDimensions (uint32_t numDimensions)
void add_viewOrigins (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewOrigins)
OriginsDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
OriginsDescriptorBuilder & operator= (const OriginsDescriptorBuilder &)
flatbuffers::Offset< OriginsDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7669 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef OriginsDescriptor Table
Definition at line 7670 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
OriginsDescriptorBuilder()
OriginsDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7685 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_concatAxis()
void add_concatAxis (uint32_t concatAxis) inline
Definition at line 7673 of file ArmnnSchema_generated.h.
References VT_CONCATAXIS.
Referenced by armnnSerializer::CreateOriginsDescriptor().
{
     fbb_.AddElement<uint32_t>(OriginsDescriptor::VT_CONCATAXIS, concatAxis, 0);
   }
add_numDimensions()
void add_numDimensions (uint32_t numDimensions) inline
Definition at line 7679 of file ArmnnSchema_generated.h.
References VT_NUMDIMENSIONS.
Referenced by armnnSerializer::CreateOriginsDescriptor().
{
     fbb_.AddElement<uint32_t>(OriginsDescriptor::VT_NUMDIMENSIONS, numDimensions, 0);
   }
add_numViews()
void add_numViews (uint32_t numViews) inline
Definition at line 7676 of file ArmnnSchema_generated.h.
References VT_NUMVIEWS.
Referenced by armnnSerializer::CreateOriginsDescriptor().
{
     fbb_.AddElement<uint32_t>(OriginsDescriptor::VT_NUMVIEWS, numViews, 0);
   }
add_viewOrigins()
void add_viewOrigins (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewOrigins) inline
Definition at line 7682 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateOriginsDescriptor().
{
     fbb_.AddOffset(OriginsDescriptor::VT_VIEWORIGINS, viewOrigins);
   }
Finish()
flatbuffers::Offset<OriginsDescriptor> Finish () inline
Definition at line 7690 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateOriginsDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<OriginsDescriptor>(end);
     return o;
   }
operator=()
OriginsDescriptorBuilder& operator= (const OriginsDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7671 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7672 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h