ArmNN: BindableLayerBaseBuilder Struct Reference
BindableLayerBaseBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef BindableLayerBase Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_layerBindingId (int32_t layerBindingId)
BindableLayerBaseBuilder (flatbuffers::FlatBufferBuilder &_fbb)
BindableLayerBaseBuilder & operator= (const BindableLayerBaseBuilder &)
flatbuffers::Offset< BindableLayerBase > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2466 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef BindableLayerBase Table
Definition at line 2467 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
BindableLayerBaseBuilder()
BindableLayerBaseBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2476 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 2470 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateBindableLayerBase().
{
     fbb_.AddOffset(BindableLayerBase::VT_BASE, base);
   }
add_layerBindingId()
void add_layerBindingId (int32_t layerBindingId) inline
Definition at line 2473 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateBindableLayerBase().
{
     fbb_.AddElement<int32_t>(BindableLayerBase::VT_LAYERBINDINGID, layerBindingId, 0);
   }
Finish()
flatbuffers::Offset<BindableLayerBase> Finish () inline
Definition at line 2481 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateBindableLayerBase().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<BindableLayerBase>(end);
     return o;
   }
operator=()
BindableLayerBaseBuilder& operator= (const BindableLayerBaseBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2468 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2469 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h