ArmNN: ChannelShuffleDescriptorBuilder Struct Reference
ChannelShuffleDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ChannelShuffleDescriptor Table
Public Member Functions
void add_axis (uint32_t axis)
void add_numGroups (uint32_t numGroups)
ChannelShuffleDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ChannelShuffleDescriptorBuilder & operator= (const ChannelShuffleDescriptorBuilder &)
flatbuffers::Offset< ChannelShuffleDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2924 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ChannelShuffleDescriptor Table
Definition at line 2925 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ChannelShuffleDescriptorBuilder()
ChannelShuffleDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2934 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_axis()
void add_axis (uint32_t axis) inline
Definition at line 2928 of file ArmnnSchema_generated.h.
References VT_AXIS.
Referenced by armnnSerializer::CreateChannelShuffleDescriptor().
{
     fbb_.AddElement<uint32_t>(ChannelShuffleDescriptor::VT_AXIS, axis, 0);
   }
add_numGroups()
void add_numGroups (uint32_t numGroups) inline
Definition at line 2931 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateChannelShuffleDescriptor().
{
     fbb_.AddElement<uint32_t>(ChannelShuffleDescriptor::VT_NUMGROUPS, numGroups, 0);
   }
Finish()
flatbuffers::Offset<ChannelShuffleDescriptor> Finish () inline
Definition at line 2939 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateChannelShuffleDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ChannelShuffleDescriptor>(end);
     return o;
   }
operator=()
ChannelShuffleDescriptorBuilder& operator= (const ChannelShuffleDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2926 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2927 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h