ArmNN: Pooling3dLayerBuilder Struct Reference
Pooling3dLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Pooling3dLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::Pooling3dDescriptor > descriptor)
Pooling3dLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Pooling3dLayerBuilder & operator= (const Pooling3dLayerBuilder &)
flatbuffers::Offset< Pooling3dLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 4971 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Pooling3dLayer Table
Definition at line 4972 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Pooling3dLayerBuilder()
Pooling3dLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 4981 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 4975 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreatePooling3dLayer().
{
     fbb_.AddOffset(Pooling3dLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::Pooling3dDescriptor > descriptor) inline
Definition at line 4978 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreatePooling3dLayer().
{
     fbb_.AddOffset(Pooling3dLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<Pooling3dLayer> Finish () inline
Definition at line 4986 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePooling3dLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Pooling3dLayer>(end);
     return o;
   }
operator=()
Pooling3dLayerBuilder& operator= (const Pooling3dLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 4973 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 4974 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h