ArmNN: Convolution3dDescriptorBuilder Struct Reference
Convolution3dDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Convolution3dDescriptor Table
Public Member Functions
void add_padLeft (uint32_t padLeft)
void add_padRight (uint32_t padRight)
void add_padTop (uint32_t padTop)
void add_padBottom (uint32_t padBottom)
void add_padFront (uint32_t padFront)
void add_padBack (uint32_t padBack)
void add_strideX (uint32_t strideX)
void add_strideY (uint32_t strideY)
void add_strideZ (uint32_t strideZ)
void add_dilationX (uint32_t dilationX)
void add_dilationY (uint32_t dilationY)
void add_dilationZ (uint32_t dilationZ)
void add_biasEnabled (bool biasEnabled)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
Convolution3dDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Convolution3dDescriptorBuilder & operator= (const Convolution3dDescriptorBuilder &)
flatbuffers::Offset< Convolution3dDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 3448 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Convolution3dDescriptor Table
Definition at line 3449 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Convolution3dDescriptorBuilder()
Convolution3dDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3494 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_biasEnabled()
void add_biasEnabled (bool biasEnabled) inline
Definition at line 3488 of file ArmnnSchema_generated.h.
References VT_BIASENABLED.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint8_t>(Convolution3dDescriptor::VT_BIASENABLED, static_cast<uint8_t>(biasEnabled), 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 3491 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<int8_t>(Convolution3dDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 2);
   }
add_dilationX()
void add_dilationX (uint32_t dilationX) inline
Definition at line 3479 of file ArmnnSchema_generated.h.
References VT_DILATIONX.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_DILATIONX, dilationX, 1);
   }
add_dilationY()
void add_dilationY (uint32_t dilationY) inline
Definition at line 3482 of file ArmnnSchema_generated.h.
References VT_DILATIONY.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_DILATIONY, dilationY, 1);
   }
add_dilationZ()
void add_dilationZ (uint32_t dilationZ) inline
Definition at line 3485 of file ArmnnSchema_generated.h.
References VT_DILATIONZ.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_DILATIONZ, dilationZ, 1);
   }
add_padBack()
void add_padBack (uint32_t padBack) inline
Definition at line 3467 of file ArmnnSchema_generated.h.
References VT_PADBACK.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_PADBACK, padBack, 0);
   }
add_padBottom()
void add_padBottom (uint32_t padBottom) inline
Definition at line 3461 of file ArmnnSchema_generated.h.
References VT_PADBOTTOM.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_PADBOTTOM, padBottom, 0);
   }
add_padFront()
void add_padFront (uint32_t padFront) inline
Definition at line 3464 of file ArmnnSchema_generated.h.
References VT_PADFRONT.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_PADFRONT, padFront, 0);
   }
add_padLeft()
void add_padLeft (uint32_t padLeft) inline
Definition at line 3452 of file ArmnnSchema_generated.h.
References VT_PADLEFT.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_PADLEFT, padLeft, 0);
   }
add_padRight()
void add_padRight (uint32_t padRight) inline
Definition at line 3455 of file ArmnnSchema_generated.h.
References VT_PADRIGHT.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_PADRIGHT, padRight, 0);
   }
add_padTop()
void add_padTop (uint32_t padTop) inline
Definition at line 3458 of file ArmnnSchema_generated.h.
References VT_PADTOP.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_PADTOP, padTop, 0);
   }
add_strideX()
void add_strideX (uint32_t strideX) inline
Definition at line 3470 of file ArmnnSchema_generated.h.
References VT_STRIDEX.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_STRIDEX, strideX, 0);
   }
add_strideY()
void add_strideY (uint32_t strideY) inline
Definition at line 3473 of file ArmnnSchema_generated.h.
References VT_STRIDEY.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_STRIDEY, strideY, 0);
   }
add_strideZ()
void add_strideZ (uint32_t strideZ) inline
Definition at line 3476 of file ArmnnSchema_generated.h.
References VT_STRIDEZ.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution3dDescriptor::VT_STRIDEZ, strideZ, 0);
   }
Finish()
flatbuffers::Offset<Convolution3dDescriptor> Finish () inline
Definition at line 3499 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConvolution3dDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Convolution3dDescriptor>(end);
     return o;
   }
operator=()
Convolution3dDescriptorBuilder& operator= (const Convolution3dDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 3450 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 3451 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h