ArmNN: DepthwiseConvolution2dDescriptorBuilder Struct Reference
DepthwiseConvolution2dDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef DepthwiseConvolution2dDescriptor Table
Public Member Functions
void add_padLeft (uint32_t padLeft)
void add_padRight (uint32_t padRight)
void add_padTop (uint32_t padTop)
void add_padBottom (uint32_t padBottom)
void add_strideX (uint32_t strideX)
void add_strideY (uint32_t strideY)
void add_dilationX (uint32_t dilationX)
void add_dilationY (uint32_t dilationY)
void add_biasEnabled (bool biasEnabled)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
DepthwiseConvolution2dDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
DepthwiseConvolution2dDescriptorBuilder & operator= (const DepthwiseConvolution2dDescriptorBuilder &)
flatbuffers::Offset< DepthwiseConvolution2dDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5632 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef DepthwiseConvolution2dDescriptor Table
Definition at line 5633 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
DepthwiseConvolution2dDescriptorBuilder()
DepthwiseConvolution2dDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5666 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_biasEnabled()
void add_biasEnabled (bool biasEnabled) inline
Definition at line 5660 of file ArmnnSchema_generated.h.
References VT_BIASENABLED.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint8_t>(DepthwiseConvolution2dDescriptor::VT_BIASENABLED, static_cast<uint8_t>(biasEnabled), 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 5663 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<int8_t>(DepthwiseConvolution2dDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 1);
   }
add_dilationX()
void add_dilationX (uint32_t dilationX) inline
Definition at line 5654 of file ArmnnSchema_generated.h.
References VT_DILATIONX.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_DILATIONX, dilationX, 1);
   }
add_dilationY()
void add_dilationY (uint32_t dilationY) inline
Definition at line 5657 of file ArmnnSchema_generated.h.
References VT_DILATIONY.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_DILATIONY, dilationY, 1);
   }
add_padBottom()
void add_padBottom (uint32_t padBottom) inline
Definition at line 5645 of file ArmnnSchema_generated.h.
References VT_PADBOTTOM.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_PADBOTTOM, padBottom, 0);
   }
add_padLeft()
void add_padLeft (uint32_t padLeft) inline
Definition at line 5636 of file ArmnnSchema_generated.h.
References VT_PADLEFT.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_PADLEFT, padLeft, 0);
   }
add_padRight()
void add_padRight (uint32_t padRight) inline
Definition at line 5639 of file ArmnnSchema_generated.h.
References VT_PADRIGHT.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_PADRIGHT, padRight, 0);
   }
add_padTop()
void add_padTop (uint32_t padTop) inline
Definition at line 5642 of file ArmnnSchema_generated.h.
References VT_PADTOP.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_PADTOP, padTop, 0);
   }
add_strideX()
void add_strideX (uint32_t strideX) inline
Definition at line 5648 of file ArmnnSchema_generated.h.
References VT_STRIDEX.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_STRIDEX, strideX, 0);
   }
add_strideY()
void add_strideY (uint32_t strideY) inline
Definition at line 5651 of file ArmnnSchema_generated.h.
References VT_STRIDEY.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthwiseConvolution2dDescriptor::VT_STRIDEY, strideY, 0);
   }
Finish()
flatbuffers::Offset<DepthwiseConvolution2dDescriptor> Finish () inline
Definition at line 5671 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<DepthwiseConvolution2dDescriptor>(end);
     return o;
   }
operator=()
DepthwiseConvolution2dDescriptorBuilder& operator= (const DepthwiseConvolution2dDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5634 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5635 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h