ArmNN: ReshapeLayerBuilder Struct Reference
ReshapeLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ReshapeLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::ReshapeDescriptor > descriptor)
ReshapeLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ReshapeLayerBuilder & operator= (const ReshapeLayerBuilder &)
flatbuffers::Offset< ReshapeLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5769 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ReshapeLayer Table
Definition at line 5770 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ReshapeLayerBuilder()
ReshapeLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5779 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 5773 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateReshapeLayer().
{
     fbb_.AddOffset(ReshapeLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::ReshapeDescriptor > descriptor) inline
Definition at line 5776 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateReshapeLayer().
{
     fbb_.AddOffset(ReshapeLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<ReshapeLayer> Finish () inline
Definition at line 5784 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateReshapeLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ReshapeLayer>(end);
     return o;
   }
operator=()
ReshapeLayerBuilder& operator= (const ReshapeLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5771 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5772 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h