ArmNN: BatchNormalizationDescriptorBuilder Struct Reference
BatchNormalizationDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef BatchNormalizationDescriptor Table
Public Member Functions
void add_eps (float eps)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
BatchNormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
BatchNormalizationDescriptorBuilder & operator= (const BatchNormalizationDescriptorBuilder &)
flatbuffers::Offset< BatchNormalizationDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6981 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef BatchNormalizationDescriptor Table
Definition at line 6982 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
BatchNormalizationDescriptorBuilder()
BatchNormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6991 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 6988 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateBatchNormalizationDescriptor().
{
     fbb_.AddElement<int8_t>(BatchNormalizationDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_eps()
void add_eps (float eps) inline
Definition at line 6985 of file ArmnnSchema_generated.h.
References VT_EPS.
Referenced by armnnSerializer::CreateBatchNormalizationDescriptor().
{
     fbb_.AddElement<float>(BatchNormalizationDescriptor::VT_EPS, eps, 0.0f);
   }
Finish()
flatbuffers::Offset<BatchNormalizationDescriptor> Finish () inline
Definition at line 6996 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateBatchNormalizationDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<BatchNormalizationDescriptor>(end);
     return o;
   }
operator=()
BatchNormalizationDescriptorBuilder& operator= (const BatchNormalizationDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6983 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6984 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h