ArmNN: ConvertConstDequantisationLayersToConstLayersImpl Class Reference
ConvertConstDequantisationLayersToConstLayersImpl Class Reference
#include <ConvertConstDequantisationLayersToConstLayers.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Protected Member Functions
ConvertConstDequantisationLayersToConstLayersImpl ()=default
~ConvertConstDequantisationLayersToConstLayersImpl ()=default
Detailed Description
Definition at line 18 of file ConvertConstDequantisationLayersToConstLayers.hpp.
Constructor & Destructor Documentation
ConvertConstDequantisationLayersToConstLayersImpl()
ConvertConstDequantisationLayersToConstLayersImpl () protected default
Referenced by ConvertConstDequantisationLayersToConstLayersImpl::Run().
~ConvertConstDequantisationLayersToConstLayersImpl()
~ConvertConstDequantisationLayersToConstLayersImpl () protected default
Referenced by ConvertConstDequantisationLayersToConstLayersImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Definition at line 21 of file ConvertConstDequantisationLayersToConstLayers.hpp.
References ARMNN_ASSERT, ARMNN_LOG, armnn::Constant, ConvertConstDequantisationLayersToConstLayersImpl::ConvertConstDequantisationLayersToConstLayersImpl(), FloatingPointConverter::ConvertFloat16To32(), armnn::Convolution2d, armnn::Dequantize, armnn::Float16, armnn::Float32, InputSlot::GetConnectedOutputSlot(), OutputSlot::GetConnection(), TensorInfo::GetDataType(), armnn::GetDataTypeName(), armnn::GetDataTypeSize(), Layer::GetInputSlot(), OutputSlot::GetNumConnections(), TensorInfo::GetNumElements(), Layer::GetNumOutputSlots(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), TensorInfo::GetQuantizationOffset(), TensorInfo::GetQuantizationScale(), TensorInfo::GetShape(), OutputSlot::GetTensorInfo(), Layer::GetType(), armnn::info, TensorInfo::IsConstant(), ConstantLayer::m_LayerOutput, OutputSlot::MoveAllConnections(), armnn::NCHW, armnn::Permute, armnn::QAsymmS8, armnn::QSymmS8, TensorInfo::SetConstant(), OutputSlot::SetTensorInfo(), and ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl().
     {
         Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
         Layer& child = connection.GetOwningLayer();
         ARMNN_ASSERT(base.GetType() == LayerType::Constant);
         ARMNN_ASSERT(child.GetType() == LayerType::Dequantize);
         ReplaceConstDequantisationLayer(graph,
                                         PolymorphicDowncast<ConstantLayer*>(&base),
                                         PolymorphicDowncast<DequantizeLayer*>(&child));
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/ConvertConstDequantisationLayersToConstLayers.hpp