ArmNN: ClBackendModelContext Class Reference
ClBackendModelContext Class Reference
The ClBackendModelContext is used to pass in CL specific backend ModelOptions.
#include <ClBackendModelContext.hpp>
Public Member Functions
ClBackendModelContext (const ModelOptions &modelOptions)
std::string GetCachedNetworkFilePath () const
bool IsFastMathEnabled () const
bool SaveCachedNetwork () const
int GetCachedFileDescriptor () const
Public Member Functions inherited from IBackendModelContext
virtual ~IBackendModelContext ()
Detailed Description
The ClBackendModelContext is used to pass in CL specific backend ModelOptions.
The supported backend ModelOptions are:
"FastMathEnabled"
Using the fast_math flag can lead to performance improvements in fp32 and fp16 layers but may result in
results with reduced or different precision. The fast_math flag will not have any effect on int8 performance.
"SaveCachedNetwork"
Using the save_cached_network flag enables saving the cached network
to a file given with the cached_network_file_path option.
"CachedNetworkFilePath"
If the cached_network_file_path is a valid file and the save_cached_network flag is present
then the cached network will be saved to the given file.
If the cached_network_file_path is a valid file and the save_cached_network flag is not present
then the cached network will be loaded from the given file.
This will remove the time taken for initial compilation of kernels and speed up the first execution.
Definition at line 28 of file ClBackendModelContext.hpp.
Constructor & Destructor Documentation
ClBackendModelContext()
ClBackendModelContext (const ModelOptions & modelOptions)
Definition at line 34 of file ClBackendModelContext.cpp.
References armnn::ParseFile(), armnn::ParseIntBackendOption(), and armnn::ParseOptions().
     : m_CachedNetworkFilePath(""), m_IsFastMathEnabled(false), m_SaveCachedNetwork(false), m_CachedFileDescriptor(-1)
 {
    if (!modelOptions.empty())
    {
        ParseOptions(modelOptions, "GpuAcc", [&](std::string name, const BackendOptions::Var& value)
        {
            if (name == "FastMathEnabled")
            {
                m_IsFastMathEnabled |= ParseBool(value, false);
            }
            if (name == "SaveCachedNetwork")
            {
                m_SaveCachedNetwork |= ParseBool(value, false);
            }
            if (name == "CachedNetworkFilePath")
            {
                m_CachedNetworkFilePath = ParseFile(value, "");
            }
            if (name == "CachedFileDescriptor")
            {
                m_CachedFileDescriptor = armnn::ParseIntBackendOption(value, -1);
            }
        });
    }
 }
Member Function Documentation
GetCachedFileDescriptor()
int GetCachedFileDescriptor () const
Definition at line 76 of file ClBackendModelContext.cpp.
 {
     return m_CachedFileDescriptor;
 }
GetCachedNetworkFilePath()
std::string GetCachedNetworkFilePath () const
Definition at line 61 of file ClBackendModelContext.cpp.
Referenced by ClWorkloadFactory::AfterWorkloadsCreated().
 {
     return m_CachedNetworkFilePath;
 }
IsFastMathEnabled()
bool IsFastMathEnabled () const
Definition at line 66 of file ClBackendModelContext.cpp.
Referenced by ClWorkloadFactory::CreateWorkload(), ClLayerSupport::IsConvolution2dSupported(), ClLayerSupport::IsConvolution3dSupported(), and ClBackend::OptimizeSubgraphView().
 {
     return m_IsFastMathEnabled;
 }
SaveCachedNetwork()
bool SaveCachedNetwork () const
Definition at line 71 of file ClBackendModelContext.cpp.
 {
     return m_SaveCachedNetwork;
 }
The documentation for this class was generated from the following files:
src/backends/cl/ClBackendModelContext.hpp
src/backends/cl/ClBackendModelContext.cpp