ArmNN: NeonConvertBf16ToFp32Workload Class Reference
NeonConvertBf16ToFp32Workload Class Reference
#include <NeonConvertBf16ToFp32Workload.hpp>
Public Member Functions
NeonConvertBf16ToFp32Workload (const ConvertBf16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info)
virtual void Execute () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from MultiTypedWorkload< QueueDescriptor, InputDataType, OutputDataType >
MultiTypedWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
Public Member Functions inherited from BaseWorkload< QueueDescriptor >
BaseWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const QueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< QueueDescriptor >
QueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 15 of file NeonConvertBf16ToFp32Workload.hpp.
Constructor & Destructor Documentation
NeonConvertBf16ToFp32Workload()
NeonConvertBf16ToFp32Workload (const ConvertBf16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 17 of file NeonConvertBf16ToFp32Workload.cpp.
References armnn::GatherTensorHandlePairs(), BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::ValidateInputsOutputs().
      : BFloat16ToFloat32Workload<ConvertBf16ToFp32QueueDescriptor>(descriptor, info)
 {
     this->m_Data.ValidateInputsOutputs("NeonConvertBf16ToFp32Workload", 1, 1);
     GatherTensorHandlePairs(descriptor, m_TensorHandlePairs);
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 25 of file NeonConvertBf16ToFp32Workload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID, FloatingPointConverter::ConvertBFloat16ToFloat32(), armnn::CopyTensorContentsGeneric(), and BaseWorkload< QueueDescriptor >::GetGuid().
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID("NeonConvertBf16ToFp32Workload_Execute", this->GetGuid());
     auto convertFunc = [](uint8_t* dst, const uint8_t* src, size_t size)
         {
             auto input = reinterpret_cast<const BFloat16*>(src);
             auto output = reinterpret_cast<float*>(dst);
             size_t numElements = size/2; // 2 bytes per Bf16
             armnnUtils::FloatingPointConverter::ConvertBFloat16ToFloat32(input, numElements, output);
         };
     for (const auto& pair : m_TensorHandlePairs)
     {
         CopyTensorContentsGeneric(pair.first, pair.second, convertFunc);
     }
 }
ReplaceInputTensorHandle()
void ReplaceInputTensorHandle (ITensorHandle * tensorHandle, unsigned int slot) override virtual
Reimplemented from BaseWorkload< QueueDescriptor >.
Definition at line 43 of file NeonConvertBf16ToFp32Workload.cpp.
References BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
 {
     ITensorHandle* backupHandle = this->m_Data.m_Inputs[slot];
     this->m_Data.m_Inputs[slot] = tensorHandle;
     try
     {
         Reconfigure();
     }
     catch(armnn::UnimplementedException& e)
     {
         // Cannot reconfigure, revert the slot back and throw the exception.
         this->m_Data.m_Inputs[slot] = backupHandle;
         throw e;
     }
 }
ReplaceOutputTensorHandle()
void ReplaceOutputTensorHandle (ITensorHandle * tensorHandle, unsigned int slot) override virtual
Reimplemented from BaseWorkload< QueueDescriptor >.
Definition at line 60 of file NeonConvertBf16ToFp32Workload.cpp.
References BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
 {
     ITensorHandle* backupHandle = this->m_Data.m_Inputs[slot];
     this->m_Data.m_Inputs[slot] = tensorHandle;
     try
     {
         Reconfigure();
     }
     catch(armnn::UnimplementedException& e)
     {
         // Cannot reconfigure, revert the slot back and throw the exception.
         this->m_Data.m_Inputs[slot] = backupHandle;
         throw e;
     }
 }
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonConvertBf16ToFp32Workload.hpp
src/backends/neon/workloads/NeonConvertBf16ToFp32Workload.cpp