ArmNN: RedirectMembersToConstantInputsImpl Class Reference
RedirectMembersToConstantInputsImpl Class Reference
#include <RedirectMembersToConstantInputs.hpp>
Public Member Functions
void Run (Graph &graph, Layer &layer) const
Search for layers with ConstantLayers as inputs.
Protected Member Functions
RedirectMembersToConstantInputsImpl ()=default
~RedirectMembersToConstantInputsImpl ()=default
Detailed Description
Definition at line 18 of file RedirectMembersToConstantInputs.hpp.
Constructor & Destructor Documentation
RedirectMembersToConstantInputsImpl()
RedirectMembersToConstantInputsImpl () protected default
Referenced by RedirectMembersToConstantInputsImpl::Run().
~RedirectMembersToConstantInputsImpl()
~RedirectMembersToConstantInputsImpl () protected default
Referenced by RedirectMembersToConstantInputsImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, Layer & layer) const inline
Search for layers with ConstantLayers as inputs.
If the inputs are constant redirect the layers member variable for ConstTensors (e.g. m_weights) to the data stored in the ConstantLayer it is connected to.
Definition at line 23 of file RedirectMembersToConstantInputs.hpp.
References ARMNN_ASSERT, armnn::BatchNormalization, armnn::Constant, armnn::Convolution2d, armnn::Debug, armnn::DepthwiseConvolution2d, armnn::DetectionPostProcess, armnn::FullyConnected, OutputSlot::GetOwningLayer(), Layer::GetType(), armnn::IgnoreUnused(), armnn::Lstm, ConstantLayer::m_LayerOutput, RedirectMembersToConstantInputsImpl::RedirectMembersToConstantInputsImpl(), armnn::TransposeConvolution2d, and RedirectMembersToConstantInputsImpl::~RedirectMembersToConstantInputsImpl().
     {
         IgnoreUnused(graph);
         switch (layer.GetType())
         {
             case LayerType::BatchNormalization:
                 break;
             case LayerType::Convolution2d:
                 RedirectWeightsAndBiases<Convolution2dLayer>(&layer);
                 break;
             case LayerType::DepthwiseConvolution2d:
                 RedirectWeightsAndBiases<DepthwiseConvolution2dLayer>(&layer);
                 break;
             case LayerType::DetectionPostProcess:
                 break;
             case LayerType::FullyConnected:
                 RedirectWeightsAndBiases<FullyConnectedLayer>(&layer);
                 break;
             case LayerType::Lstm:
                 break;
             case LayerType::TransposeConvolution2d:
                 break;
             default:
                 break;
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/RedirectMembersToConstantInputs.hpp