var dir_5bee762cfd03f62aa80233ed05f1bfdf =
[
    [ "AddBroadcastReshapeLayer.hpp", "_add_broadcast_reshape_layer_8hpp.xhtml", "_add_broadcast_reshape_layer_8hpp" ],
    [ "AddDebug.hpp", "_add_debug_8hpp.xhtml", "_add_debug_8hpp" ],
    [ "All.hpp", "_all_8hpp.xhtml", null ],
    [ "ConvertConstants.hpp", "_convert_constants_8hpp.xhtml", "_convert_constants_8hpp" ],
    [ "ConvertConstDequantisationLayersToConstLayers.hpp", "_convert_const_dequantisation_layers_to_const_layers_8hpp.xhtml", "_convert_const_dequantisation_layers_to_const_layers_8hpp" ],
    [ "ConvertConstPermuteLayersToConstLayers.hpp", "_convert_const_permute_layers_to_const_layers_8hpp.xhtml", "_convert_const_permute_layers_to_const_layers_8hpp" ],
    [ "ConvertFp32NetworkToBf16.hpp", "_convert_fp32_network_to_bf16_8hpp.xhtml", "_convert_fp32_network_to_bf16_8hpp" ],
    [ "ConvertFp32NetworkToFp16.hpp", "_convert_fp32_network_to_fp16_8hpp.xhtml", "_convert_fp32_network_to_fp16_8hpp" ],
    [ "FoldPadIntoLayer2d.hpp", "_fold_pad_into_layer2d_8hpp.xhtml", "_fold_pad_into_layer2d_8hpp" ],
    [ "FuseBatchNorm.hpp", "_fuse_batch_norm_8hpp.xhtml", "_fuse_batch_norm_8hpp" ],
    [ "FuseConvertFp32ToBf16IntoConstLayers.hpp", "_fuse_convert_fp32_to_bf16_into_const_layers_8hpp.xhtml", "_fuse_convert_fp32_to_bf16_into_const_layers_8hpp" ],
    [ "MovePermuteUp.hpp", "_move_permute_up_8hpp.xhtml", "_move_permute_up_8hpp" ],
    [ "MoveTransposeUp.hpp", "_move_transpose_up_8hpp.xhtml", "_move_transpose_up_8hpp" ],
    [ "Optimization.hpp", "_optimization_8hpp.xhtml", [
      [ "Optimization", "classarmnn_1_1_optimization.xhtml", "classarmnn_1_1_optimization" ],
      [ "OptimizeForTypeImpl", "classarmnn_1_1_optimize_for_type_impl.xhtml", "classarmnn_1_1_optimize_for_type_impl" ],
      [ "OptimizeForTypeImpl< Layer, Wrapped >", "classarmnn_1_1_optimize_for_type_impl_3_01_layer_00_01_wrapped_01_4.xhtml", "classarmnn_1_1_optimize_for_type_impl_3_01_layer_00_01_wrapped_01_4" ],
      [ "OptimizeForType", "classarmnn_1_1_optimize_for_type.xhtml", null ],
      [ "OptimizeForConnectionImpl", "classarmnn_1_1_optimize_for_connection_impl.xhtml", "classarmnn_1_1_optimize_for_connection_impl" ],
      [ "OptimizeForConnection", "classarmnn_1_1_optimize_for_connection.xhtml", null ],
      [ "OptimizeForExclusiveConnectionImpl", "classarmnn_1_1_optimize_for_exclusive_connection_impl.xhtml", "classarmnn_1_1_optimize_for_exclusive_connection_impl" ],
      [ "OptimizeForExclusiveConnection", "classarmnn_1_1_optimize_for_exclusive_connection.xhtml", null ]
    ] ],
    [ "OptimizeConsecutiveReshapes.hpp", "_optimize_consecutive_reshapes_8hpp.xhtml", "_optimize_consecutive_reshapes_8hpp" ],
    [ "OptimizeInverseConversions.hpp", "_optimize_inverse_conversions_8hpp.xhtml", "_optimize_inverse_conversions_8hpp" ],
    [ "OptimizeInversePermutes.hpp", "_optimize_inverse_permutes_8hpp.xhtml", "_optimize_inverse_permutes_8hpp" ],
    [ "PermuteAndBatchToSpaceAsDepthToSpace.hpp", "_permute_and_batch_to_space_as_depth_to_space_8hpp.xhtml", "_permute_and_batch_to_space_as_depth_to_space_8hpp" ],
    [ "PermuteAsReshape.hpp", "_permute_as_reshape_8hpp.xhtml", "_permute_as_reshape_8hpp" ],
    [ "PermuteDepthwiseConv2dWeights.hpp", "_permute_depthwise_conv2d_weights_8hpp.xhtml", "_permute_depthwise_conv2d_weights_8hpp" ],
    [ "RedirectMembersToConstantInputs.hpp", "_redirect_members_to_constant_inputs_8hpp.xhtml", "_redirect_members_to_constant_inputs_8hpp" ],
    [ "SquashEqualSiblings.hpp", "_squash_equal_siblings_8hpp.xhtml", "_squash_equal_siblings_8hpp" ],
    [ "TransposeAsReshape.hpp", "_transpose_as_reshape_8hpp.xhtml", "_transpose_as_reshape_8hpp" ]
];