ArmNN: armnnOnnxParser Namespace Reference
armnnOnnxParser Namespace Reference
Classes
class IOnnxParser
class OnnxParserImpl
Typedefs
using BindingPointInfo = armnn::BindingPointInfo
using IOnnxParserPtr = std::unique_ptr< IOnnxParser, void(*)(IOnnxParser *parser)>
using ModelPtr = std::unique_ptr< onnx::ModelProto >
Functions
template<typename T >
std::pair< armnn::ConstTensor, std::unique_ptr< T[]> > CreateConstTensorImpl (const T *bufferPtr, armnn::TensorInfo &tensorInfo, const armnn::Optional< armnn::PermutationVector &> permutationVector)
Typedef Documentation
BindingPointInfo
using BindingPointInfo = armnn::BindingPointInfo
Definition at line 17 of file IOnnxParser.hpp.
IOnnxParserPtr
using IOnnxParserPtr = std::unique_ptr<IOnnxParser, void(*)(IOnnxParser* parser)>
Definition at line 21 of file IOnnxParser.hpp.
ModelPtr
using ModelPtr = std::unique_ptr<onnx::ModelProto>
Definition at line 23 of file OnnxParser.hpp.
Function Documentation
CreateConstTensorImpl()
std::pair<armnn::ConstTensor, std::unique_ptr<T[]> > armnnOnnxParser::CreateConstTensorImpl (const T * bufferPtr, armnn::TensorInfo & tensorInfo, const armnn::Optional< armnn::PermutationVector &> permutationVector)
Definition at line 566 of file OnnxParser.cpp.
References ARMNN_ASSERT_MSG, CHECK_LOCATION, CHECK_VALID_DATATYPE, CHECKED_INT32, TensorInfo::GetNumBytes(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), PermutationVector::GetSize(), OptionalBase::has_value(), armnnUtils::Permute(), armnnUtils::Permuted(), TensorInfo::SetConstant(), and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
 {
     ARMNN_ASSERT_MSG(bufferPtr != nullptr, fmt::format("Buffer for permutation is null").c_str());
     std::unique_ptr<T[]> data(new T[tensorInfo.GetNumElements()]);
     if (permutationVector.has_value() && permutationVector.value().GetSize() > 0)
     {
         tensorInfo = armnnUtils::Permuted(tensorInfo, permutationVector.value());
         armnnUtils::Permute(tensorInfo.GetShape(), permutationVector.value(),
                             reinterpret_cast<const T*>(bufferPtr), data.get(), sizeof(T));
     }
     else
     {
         ::memcpy(data.get(), bufferPtr, tensorInfo.GetNumBytes());
     }
     return std::make_pair(ConstTensor(tensorInfo, data.get()), std::move(data));
 }