ArmNN: BackendOptions Struct Reference
BackendOptions Struct Reference
Struct for the users to pass backend specific options.
#include <BackendOptions.hpp>
Classes
struct BackendOption
class Var
Very basic type safe variant.
Public Member Functions
BackendOptions (BackendId backend)
BackendOptions (BackendId backend, std::initializer_list< BackendOption > options)
BackendOptions (const BackendOptions &other)=default
BackendOptions (BackendOptions &&other)=default
BackendOptions & operator= (const BackendOptions &other)=default
BackendOptions & operator= (BackendOptions &&other)=default
void AddOption (BackendOption &&option)
void AddOption (const BackendOption &option)
const BackendId & GetBackendId () const noexcept
size_t GetOptionCount () const noexcept
const BackendOption & GetOption (size_t idx) const
Detailed Description
Struct for the users to pass backend specific options.
Definition at line 22 of file BackendOptions.hpp.
Constructor & Destructor Documentation
BackendOptions() [1/4]
BackendOptions (BackendId backend) inline explicit
Definition at line 259 of file BackendOptions.hpp.
Referenced by BackendOptions::BackendOptions().
         : m_TargetBackend(backend)
     {}
BackendOptions() [2/4]
BackendOptions (BackendId backend, std::initializer_list< BackendOption > options) inline
Definition at line 263 of file BackendOptions.hpp.
References BackendOptions::BackendOptions(), and BackendOptions::operator=().
         : m_TargetBackend(backend)
         , m_Options(options)
     {}
BackendOptions() [3/4]
BackendOptions (const BackendOptions & other) default
BackendOptions() [4/4]
BackendOptions (BackendOptions && other) default
Member Function Documentation
AddOption() [1/2]
void AddOption (BackendOption && option) inline
Definition at line 273 of file BackendOptions.hpp.
     {
         m_Options.push_back(option);
     }
AddOption() [2/2]
void AddOption (const BackendOption & option) inline
Definition at line 278 of file BackendOptions.hpp.
     {
         m_Options.push_back(option);
     }
GetBackendId()
const BackendId& GetBackendId () const inline noexcept
Definition at line 283 of file BackendOptions.hpp.
 { return m_TargetBackend; }
GetOption()
const BackendOption& GetOption (size_t idx) const inline
Definition at line 285 of file BackendOptions.hpp.
Referenced by armnn::GetCapability(), and armnn::HasCapability().
 { return m_Options[idx]; }
GetOptionCount()
size_t GetOptionCount () const inline noexcept
Definition at line 284 of file BackendOptions.hpp.
Referenced by armnn::GetCapability(), and armnn::HasCapability().
 { return m_Options.size(); }
operator=() [1/2]
BackendOptions& operator= (const BackendOptions & other) default
Referenced by BackendOptions::BackendOption::BackendOption(), and BackendOptions::BackendOptions().
operator=() [2/2]
BackendOptions& operator= (BackendOptions && other) default
The documentation for this struct was generated from the following file:
include/armnn/BackendOptions.hpp