ArmNN: StringMapping Struct Reference
StringMapping Struct Reference
StringMapping is helper class to be able to use strings as template parameters, so this allows simplifying code which only differs in a string, such as a debug string literal.
#include <StringMapping.hpp>
Public Types
enum Id {
RefAdditionWorkload_Execute, RefDivisionWorkload_Execute, RefMaximumWorkload_Execute, RefMinimumWorkload_Execute,
RefMultiplicationWorkload_Execute, RefSubtractionWorkload_Execute, MAX_STRING_ID
}
Public Member Functions
const char * Get (Id id) const
Static Public Member Functions
static const StringMapping & Instance ()
Detailed Description
StringMapping is helper class to be able to use strings as template parameters, so this allows simplifying code which only differs in a string, such as a debug string literal.
Definition at line 16 of file StringMapping.hpp.
Member Enumeration Documentation
Id
enum Id
Enumerator
RefAdditionWorkload_Execute
RefDivisionWorkload_Execute
RefMaximumWorkload_Execute
RefMinimumWorkload_Execute
RefMultiplicationWorkload_Execute
RefSubtractionWorkload_Execute
MAX_STRING_ID
Definition at line 19 of file StringMapping.hpp.
             {
         RefAdditionWorkload_Execute,
         RefDivisionWorkload_Execute,
         RefMaximumWorkload_Execute,
         RefMinimumWorkload_Execute,
         RefMultiplicationWorkload_Execute,
         RefSubtractionWorkload_Execute,
         MAX_STRING_ID
     };
Member Function Documentation
Get()
const char* Get (Id id) const inline
Definition at line 29 of file StringMapping.hpp.
References StringMapping::Instance(), StringMapping::MAX_STRING_ID, StringMapping::RefAdditionWorkload_Execute, StringMapping::RefDivisionWorkload_Execute, StringMapping::RefMaximumWorkload_Execute, StringMapping::RefMinimumWorkload_Execute, StringMapping::RefMultiplicationWorkload_Execute, and StringMapping::RefSubtractionWorkload_Execute.
     {
         return m_Strings[id];
     }
Instance()
const StringMapping & Instance () static
Definition at line 11 of file StringMapping.cpp.
Referenced by RefElementwiseWorkload< Functor, ParentDescriptor, DebugString >::ExecuteAsync(), and StringMapping::Get().
 {
     static StringMapping instance;
     return instance;
 }
The documentation for this struct was generated from the following files:
src/backends/reference/workloads/StringMapping.hpp
src/backends/reference/workloads/StringMapping.cpp