var searchData=
[
  ['ranklayer_5973',['RankLayer',['../classarmnn_1_1_rank_layer.html',1,'armnn']]],
  ['rankqueuedescriptor_5974',['RankQueueDescriptor',['../structarmnn_1_1_rank_queue_descriptor.html',1,'armnn']]],
  ['reducedescriptor_5975',['ReduceDescriptor',['../structarmnn_1_1_reduce_descriptor.html',1,'armnn']]],
  ['reducelayer_5976',['ReduceLayer',['../classarmnn_1_1_reduce_layer.html',1,'armnn']]],
  ['reducequeuedescriptor_5977',['ReduceQueueDescriptor',['../structarmnn_1_1_reduce_queue_descriptor.html',1,'armnn']]],
  ['refactivationworkload_5978',['RefActivationWorkload',['../classarmnn_1_1_ref_activation_workload.html',1,'armnn']]],
  ['refargminmaxworkload_5979',['RefArgMinMaxWorkload',['../classarmnn_1_1_ref_arg_min_max_workload.html',1,'armnn']]],
  ['refbackend_5980',['RefBackend',['../classarmnn_1_1_ref_backend.html',1,'armnn']]],
  ['refbaseworkload_5981',['RefBaseWorkload',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20activationqueuedescriptor_20_3e_5982',['RefBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5983',['RefBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5984',['RefBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5985',['RefBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5986',['RefBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20broadcasttoqueuedescriptor_20_3e_5987',['RefBaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20castqueuedescriptor_20_3e_5988',['RefBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5989',['RefBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5990',['RefBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20concatqueuedescriptor_20_3e_5991',['RefBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20constantqueuedescriptor_20_3e_5992',['RefBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5993',['RefBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5994',['RefBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5995',['RefBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5996',['RefBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5997',['RefBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5998',['RefBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5999',['RefBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_6000',['RefBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20fillqueuedescriptor_20_3e_6001',['RefBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20floorqueuedescriptor_20_3e_6002',['RefBaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_6003',['RefBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20gatherndqueuedescriptor_20_3e_6004',['RefBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20gatherqueuedescriptor_20_3e_6005',['RefBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_6006',['RefBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20l2normalizationqueuedescriptor_20_3e_6007',['RefBaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_6008',['RefBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_6009',['RefBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20lstmqueuedescriptor_20_3e_6010',['RefBaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20meanqueuedescriptor_20_3e_6011',['RefBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20normalizationqueuedescriptor_20_3e_6012',['RefBaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20padqueuedescriptor_20_3e_6013',['RefBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20parentdescriptor_20_3e_6014',['RefBaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_6015',['RefBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_6016',['RefBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20preluqueuedescriptor_20_3e_6017',['RefBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20qlstmqueuedescriptor_20_3e_6018',['RefBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20quantizequeuedescriptor_20_3e_6019',['RefBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20rankqueuedescriptor_20_3e_6020',['RefBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reducequeuedescriptor_20_3e_6021',['RefBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reshapequeuedescriptor_20_3e_6022',['RefBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20resizequeuedescriptor_20_3e_6023',['RefBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reversev2queuedescriptor_20_3e_6024',['RefBaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20scatterndqueuedescriptor_20_3e_6025',['RefBaseWorkload&lt; ScatterNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20shapequeuedescriptor_20_3e_6026',['RefBaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20slicequeuedescriptor_20_3e_6027',['RefBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20softmaxqueuedescriptor_20_3e_6028',['RefBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_6029',['RefBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_6030',['RefBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20splitterqueuedescriptor_20_3e_6031',['RefBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20stackqueuedescriptor_20_3e_6032',['RefBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_6033',['RefBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20tilequeuedescriptor_20_3e_6034',['RefBaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_6035',['RefBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_6036',['RefBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbatchmatmulworkload_6037',['RefBatchMatMulWorkload',['../classarmnn_1_1_ref_batch_mat_mul_workload.html',1,'armnn']]],
  ['refbatchnormalizationworkload_6038',['RefBatchNormalizationWorkload',['../classarmnn_1_1_ref_batch_normalization_workload.html',1,'armnn']]],
  ['refbatchtospacendworkload_6039',['RefBatchToSpaceNdWorkload',['../classarmnn_1_1_ref_batch_to_space_nd_workload.html',1,'armnn']]],
  ['refbroadcasttoworkload_6040',['RefBroadcastToWorkload',['../classarmnn_1_1_ref_broadcast_to_workload.html',1,'armnn']]],
  ['refcastworkload_6041',['RefCastWorkload',['../classarmnn_1_1_ref_cast_workload.html',1,'armnn']]],
  ['refchannelshuffleworkload_6042',['RefChannelShuffleWorkload',['../classarmnn_1_1_ref_channel_shuffle_workload.html',1,'armnn']]],
  ['refcomparisonworkload_6043',['RefComparisonWorkload',['../classarmnn_1_1_ref_comparison_workload.html',1,'armnn']]],
  ['refconcatworkload_6044',['RefConcatWorkload',['../classarmnn_1_1_ref_concat_workload.html',1,'armnn']]],
  ['refconstantworkload_6045',['RefConstantWorkload',['../classarmnn_1_1_ref_constant_workload.html',1,'armnn']]],
  ['refconvertfp16tofp32workload_6046',['RefConvertFp16ToFp32Workload',['../classarmnn_1_1_ref_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['refconvertfp32tofp16workload_6047',['RefConvertFp32ToFp16Workload',['../classarmnn_1_1_ref_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['refconvolution2dworkload_6048',['RefConvolution2dWorkload',['../classarmnn_1_1_ref_convolution2d_workload.html',1,'armnn']]],
  ['refconvolution3dworkload_6049',['RefConvolution3dWorkload',['../classarmnn_1_1_ref_convolution3d_workload.html',1,'armnn']]],
  ['refdebugworkload_6050',['RefDebugWorkload',['../classarmnn_1_1_ref_debug_workload.html',1,'armnn']]],
  ['refdepthtospaceworkload_6051',['RefDepthToSpaceWorkload',['../classarmnn_1_1_ref_depth_to_space_workload.html',1,'armnn']]],
  ['refdepthwiseconvolution2dworkload_6052',['RefDepthwiseConvolution2dWorkload',['../classarmnn_1_1_ref_depthwise_convolution2d_workload.html',1,'armnn']]],
  ['refdequantizeworkload_6053',['RefDequantizeWorkload',['../classarmnn_1_1_ref_dequantize_workload.html',1,'armnn']]],
  ['refdetectionpostprocessworkload_6054',['RefDetectionPostProcessWorkload',['../classarmnn_1_1_ref_detection_post_process_workload.html',1,'armnn']]],
  ['refelementwisebinaryworkload_6055',['RefElementwiseBinaryWorkload',['../classarmnn_1_1_ref_elementwise_binary_workload.html',1,'armnn']]],
  ['refelementwiseunaryworkload_6056',['RefElementwiseUnaryWorkload',['../classarmnn_1_1_ref_elementwise_unary_workload.html',1,'armnn']]],
  ['refelementwiseworkload_6057',['RefElementwiseWorkload',['../classarmnn_1_1_ref_elementwise_workload.html',1,'armnn']]],
  ['reffakequantizationfloat32workload_6058',['RefFakeQuantizationFloat32Workload',['../classarmnn_1_1_ref_fake_quantization_float32_workload.html',1,'armnn']]],
  ['reffillworkload_6059',['RefFillWorkload',['../classarmnn_1_1_ref_fill_workload.html',1,'armnn']]],
  ['reffloorworkload_6060',['RefFloorWorkload',['../classarmnn_1_1_ref_floor_workload.html',1,'armnn']]],
  ['reffullyconnectedworkload_6061',['RefFullyConnectedWorkload',['../classarmnn_1_1_ref_fully_connected_workload.html',1,'armnn']]],
  ['refgatherndworkload_6062',['RefGatherNdWorkload',['../classarmnn_1_1_ref_gather_nd_workload.html',1,'armnn']]],
  ['refgatherworkload_6063',['RefGatherWorkload',['../classarmnn_1_1_ref_gather_workload.html',1,'armnn']]],
  ['refinstancenormalizationworkload_6064',['RefInstanceNormalizationWorkload',['../classarmnn_1_1_ref_instance_normalization_workload.html',1,'armnn']]],
  ['refl2normalizationworkload_6065',['RefL2NormalizationWorkload',['../classarmnn_1_1_ref_l2_normalization_workload.html',1,'armnn']]],
  ['reflayersupport_6066',['RefLayerSupport',['../classarmnn_1_1_ref_layer_support.html',1,'armnn']]],
  ['reflogicalbinaryworkload_6067',['RefLogicalBinaryWorkload',['../classarmnn_1_1_ref_logical_binary_workload.html',1,'armnn']]],
  ['reflogicalunaryworkload_6068',['RefLogicalUnaryWorkload',['../classarmnn_1_1_ref_logical_unary_workload.html',1,'armnn']]],
  ['reflogsoftmaxworkload_6069',['RefLogSoftmaxWorkload',['../classarmnn_1_1_ref_log_softmax_workload.html',1,'armnn']]],
  ['reflstmworkload_6070',['RefLstmWorkload',['../classarmnn_1_1_ref_lstm_workload.html',1,'armnn']]],
  ['refmeanworkload_6071',['RefMeanWorkload',['../classarmnn_1_1_ref_mean_workload.html',1,'armnn']]],
  ['refmemorymanager_6072',['RefMemoryManager',['../classarmnn_1_1_ref_memory_manager.html',1,'armnn']]],
  ['refnormalizationworkload_6073',['RefNormalizationWorkload',['../classarmnn_1_1_ref_normalization_workload.html',1,'armnn']]],
  ['refpadworkload_6074',['RefPadWorkload',['../classarmnn_1_1_ref_pad_workload.html',1,'armnn']]],
  ['refpermuteworkload_6075',['RefPermuteWorkload',['../classarmnn_1_1_ref_permute_workload.html',1,'armnn']]],
  ['refpooling2dworkload_6076',['RefPooling2dWorkload',['../classarmnn_1_1_ref_pooling2d_workload.html',1,'armnn']]],
  ['refpooling3dworkload_6077',['RefPooling3dWorkload',['../classarmnn_1_1_ref_pooling3d_workload.html',1,'armnn']]],
  ['refpreluworkload_6078',['RefPreluWorkload',['../classarmnn_1_1_ref_prelu_workload.html',1,'armnn']]],
  ['refqlstmworkload_6079',['RefQLstmWorkload',['../classarmnn_1_1_ref_q_lstm_workload.html',1,'armnn']]],
  ['refquantizeworkload_6080',['RefQuantizeWorkload',['../classarmnn_1_1_ref_quantize_workload.html',1,'armnn']]],
  ['refrankworkload_6081',['RefRankWorkload',['../structarmnn_1_1_ref_rank_workload.html',1,'armnn']]],
  ['refreduceworkload_6082',['RefReduceWorkload',['../classarmnn_1_1_ref_reduce_workload.html',1,'armnn']]],
  ['refreshapeworkload_6083',['RefReshapeWorkload',['../classarmnn_1_1_ref_reshape_workload.html',1,'armnn']]],
  ['refresizeworkload_6084',['RefResizeWorkload',['../classarmnn_1_1_ref_resize_workload.html',1,'armnn']]],
  ['refreversev2workload_6085',['RefReverseV2Workload',['../classarmnn_1_1_ref_reverse_v2_workload.html',1,'armnn']]],
  ['refscatterndworkload_6086',['RefScatterNdWorkload',['../classarmnn_1_1_ref_scatter_nd_workload.html',1,'armnn']]],
  ['refshapeworkload_6087',['RefShapeWorkload',['../structarmnn_1_1_ref_shape_workload.html',1,'armnn']]],
  ['refsliceworkload_6088',['RefSliceWorkload',['../classarmnn_1_1_ref_slice_workload.html',1,'armnn']]],
  ['refsoftmaxworkload_6089',['RefSoftmaxWorkload',['../classarmnn_1_1_ref_softmax_workload.html',1,'armnn']]],
  ['refspacetobatchndworkload_6090',['RefSpaceToBatchNdWorkload',['../classarmnn_1_1_ref_space_to_batch_nd_workload.html',1,'armnn']]],
  ['refspacetodepthworkload_6091',['RefSpaceToDepthWorkload',['../classarmnn_1_1_ref_space_to_depth_workload.html',1,'armnn']]],
  ['refsplitterworkload_6092',['RefSplitterWorkload',['../classarmnn_1_1_ref_splitter_workload.html',1,'armnn']]],
  ['refstackworkload_6093',['RefStackWorkload',['../classarmnn_1_1_ref_stack_workload.html',1,'armnn']]],
  ['refstridedsliceworkload_6094',['RefStridedSliceWorkload',['../classarmnn_1_1_ref_strided_slice_workload.html',1,'armnn']]],
  ['reftensorhandle_6095',['RefTensorHandle',['../classarmnn_1_1_ref_tensor_handle.html',1,'armnn']]],
  ['reftensorhandledecorator_6096',['RefTensorHandleDecorator',['../classarmnn_1_1_ref_tensor_handle_decorator.html',1,'armnn']]],
  ['reftensorhandlefactory_6097',['RefTensorHandleFactory',['../classarmnn_1_1_ref_tensor_handle_factory.html',1,'armnn']]],
  ['reftileworkload_6098',['RefTileWorkload',['../classarmnn_1_1_ref_tile_workload.html',1,'armnn']]],
  ['reftransposeconvolution2dworkload_6099',['RefTransposeConvolution2dWorkload',['../classarmnn_1_1_ref_transpose_convolution2d_workload.html',1,'armnn']]],
  ['reftransposeworkload_6100',['RefTransposeWorkload',['../classarmnn_1_1_ref_transpose_workload.html',1,'armnn']]],
  ['refunidirectionalsequencelstmworkload_6101',['RefUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_ref_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['refworkloadfactory_6102',['RefWorkloadFactory',['../classarmnn_1_1_ref_workload_factory.html',1,'armnn']]],
  ['reshapedescriptor_6103',['ReshapeDescriptor',['../structarmnn_1_1_reshape_descriptor.html',1,'armnn']]],
  ['reshapelayer_6104',['ReshapeLayer',['../classarmnn_1_1_reshape_layer.html',1,'armnn']]],
  ['reshapequeuedescriptor_6105',['ReshapeQueueDescriptor',['../structarmnn_1_1_reshape_queue_descriptor.html',1,'armnn']]],
  ['resizedescriptor_6106',['ResizeDescriptor',['../structarmnn_1_1_resize_descriptor.html',1,'armnn']]],
  ['resizelayer_6107',['ResizeLayer',['../classarmnn_1_1_resize_layer.html',1,'armnn']]],
  ['resizequeuedescriptor_6108',['ResizeQueueDescriptor',['../structarmnn_1_1_resize_queue_descriptor.html',1,'armnn']]],
  ['resolvetypeimpl_6109',['ResolveTypeImpl',['../structarmnn_1_1_resolve_type_impl.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3abfloat16_20_3e_6110',['ResolveTypeImpl&lt; DataType::BFloat16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_b_float16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aboolean_20_3e_6111',['ResolveTypeImpl&lt; DataType::Boolean &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_boolean_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat16_20_3e_6112',['ResolveTypeImpl&lt; DataType::Float16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat32_20_3e_6113',['ResolveTypeImpl&lt; DataType::Float32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float32_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymms8_20_3e_6114',['ResolveTypeImpl&lt; DataType::QAsymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_s8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymmu8_20_3e_6115',['ResolveTypeImpl&lt; DataType::QAsymmU8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_u8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms16_20_3e_6116',['ResolveTypeImpl&lt; DataType::QSymmS16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms8_20_3e_6117',['ResolveTypeImpl&lt; DataType::QSymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned32_20_3e_6118',['ResolveTypeImpl&lt; DataType::Signed32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed32_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned64_20_3e_6119',['ResolveTypeImpl&lt; DataType::Signed64 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed64_01_4.html',1,'armnn']]],
  ['reversev2layer_6120',['ReverseV2Layer',['../classarmnn_1_1_reverse_v2_layer.html',1,'armnn']]],
  ['reversev2queuedescriptor_6121',['ReverseV2QueueDescriptor',['../structarmnn_1_1_reverse_v2_queue_descriptor.html',1,'armnn']]],
  ['rsqrt_6122',['rsqrt',['../structarmnn_1_1rsqrt.html',1,'armnn']]],
  ['rsqrtlayer_6123',['RsqrtLayer',['../classarmnn_1_1_rsqrt_layer.html',1,'armnn']]],
  ['rsqrtqueuedescriptor_6124',['RsqrtQueueDescriptor',['../structarmnn_1_1_rsqrt_queue_descriptor.html',1,'armnn']]],
  ['rule_6125',['Rule',['../structarmnn_1_1_rule.html',1,'armnn']]],
  ['runtimeexception_6126',['RuntimeException',['../classarmnn_1_1_runtime_exception.html',1,'armnn']]],
  ['runtimeimpl_6127',['RuntimeImpl',['../structarmnn_1_1_runtime_impl.html',1,'armnn']]]
];
