var searchData=
[
  ['qasymm8decoder_5895',['QASymm8Decoder',['../classarmnn_1_1_q_a_symm8_decoder.html',1,'armnn']]],
  ['qasymm8encoder_5896',['QASymm8Encoder',['../classarmnn_1_1_q_a_symm8_encoder.html',1,'armnn']]],
  ['qasymms8decoder_5897',['QASymmS8Decoder',['../classarmnn_1_1_q_a_symm_s8_decoder.html',1,'armnn']]],
  ['qasymms8encoder_5898',['QASymmS8Encoder',['../classarmnn_1_1_q_a_symm_s8_encoder.html',1,'armnn']]],
  ['qlstmbasicparameters_5899',['QLstmBasicParameters',['../structarmnn_1_1_q_lstm_basic_parameters.html',1,'armnn']]],
  ['qlstmdescriptor_5900',['QLstmDescriptor',['../structarmnn_1_1_q_lstm_descriptor.html',1,'armnn']]],
  ['qlstmlayer_5901',['QLstmLayer',['../classarmnn_1_1_q_lstm_layer.html',1,'armnn']]],
  ['qlstmoptcifgparameters_5902',['QLstmOptCifgParameters',['../structarmnn_1_1_q_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['qlstmoptlayernormparameters_5903',['QLstmOptLayerNormParameters',['../structarmnn_1_1_q_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['qlstmoptpeepholeparameters_5904',['QLstmOptPeepholeParameters',['../structarmnn_1_1_q_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['qlstmoptprojectionparameters_5905',['QLstmOptProjectionParameters',['../structarmnn_1_1_q_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['qlstmqueuedescriptor_5906',['QLstmQueueDescriptor',['../structarmnn_1_1_q_lstm_queue_descriptor.html',1,'armnn']]],
  ['qsymm16decoder_5907',['QSymm16Decoder',['../classarmnn_1_1_q_symm16_decoder.html',1,'armnn']]],
  ['qsymm16encoder_5908',['QSymm16Encoder',['../classarmnn_1_1_q_symm16_encoder.html',1,'armnn']]],
  ['qsymm16peraxisencoder_5909',['QSymm16PerAxisEncoder',['../classarmnn_1_1_q_symm16_per_axis_encoder.html',1,'armnn']]],
  ['qsymm8peraxisdecoder_5910',['QSymm8PerAxisDecoder',['../classarmnn_1_1_q_symm8_per_axis_decoder.html',1,'armnn']]],
  ['qsymm8peraxisencoder_5911',['QSymm8PerAxisEncoder',['../classarmnn_1_1_q_symm8_per_axis_encoder.html',1,'armnn']]],
  ['qsymms8decoder_5912',['QSymmS8Decoder',['../classarmnn_1_1_q_symm_s8_decoder.html',1,'armnn']]],
  ['qsymms8encoder_5913',['QSymmS8Encoder',['../classarmnn_1_1_q_symm_s8_encoder.html',1,'armnn']]],
  ['quantizationparametersareequal_5914',['QuantizationParametersAreEqual',['../structarmnn_1_1_quantization_parameters_are_equal.html',1,'armnn']]],
  ['quantizedlstminputparams_5915',['QuantizedLstmInputParams',['../structarmnn_1_1_quantized_lstm_input_params.html',1,'armnn']]],
  ['quantizedlstminputparamsinfo_5916',['QuantizedLstmInputParamsInfo',['../structarmnn_1_1_quantized_lstm_input_params_info.html',1,'armnn']]],
  ['quantizedlstmlayer_5917',['QuantizedLstmLayer',['../classarmnn_1_1_quantized_lstm_layer.html',1,'armnn']]],
  ['quantizedlstmparameters_5918',['QuantizedLstmParameters',['../structarmnn_1_1_quantized_lstm_parameters.html',1,'armnn']]],
  ['quantizedlstmqueuedescriptor_5919',['QuantizedLstmQueueDescriptor',['../structarmnn_1_1_quantized_lstm_queue_descriptor.html',1,'armnn']]],
  ['quantizedmultipliersmallerthanone_5920',['QuantizedMultiplierSmallerThanOne',['../structarmnn_1_1_quantized_multiplier_smaller_than_one.html',1,'armnn']]],
  ['quantizelayer_5921',['QuantizeLayer',['../classarmnn_1_1_quantize_layer.html',1,'armnn']]],
  ['quantizequeuedescriptor_5922',['QuantizeQueueDescriptor',['../structarmnn_1_1_quantize_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptor_5923',['QueueDescriptor',['../structarmnn_1_1_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptorwithparameters_5924',['QueueDescriptorWithParameters',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20activationdescriptor_20_3e_5925',['QueueDescriptorWithParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20argminmaxdescriptor_20_3e_5926',['QueueDescriptorWithParameters&lt; ArgMinMaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchmatmuldescriptor_20_3e_5927',['QueueDescriptorWithParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchnormalizationdescriptor_20_3e_5928',['QueueDescriptorWithParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchtospacenddescriptor_20_3e_5929',['QueueDescriptorWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20broadcasttodescriptor_20_3e_5930',['QueueDescriptorWithParameters&lt; BroadcastToDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20channelshuffledescriptor_20_3e_5931',['QueueDescriptorWithParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20comparisondescriptor_20_3e_5932',['QueueDescriptorWithParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution2ddescriptor_20_3e_5933',['QueueDescriptorWithParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution3ddescriptor_20_3e_5934',['QueueDescriptorWithParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthtospacedescriptor_20_3e_5935',['QueueDescriptorWithParameters&lt; DepthToSpaceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_5936',['QueueDescriptorWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20detectionpostprocessdescriptor_20_3e_5937',['QueueDescriptorWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwisebinarydescriptor_20_3e_5938',['QueueDescriptorWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwiseunarydescriptor_20_3e_5939',['QueueDescriptorWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fakequantizationdescriptor_20_3e_5940',['QueueDescriptorWithParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20filldescriptor_20_3e_5941',['QueueDescriptorWithParameters&lt; FillDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fullyconnecteddescriptor_20_3e_5942',['QueueDescriptorWithParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fuseddescriptor_20_3e_5943',['QueueDescriptorWithParameters&lt; FusedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20gatherdescriptor_20_3e_5944',['QueueDescriptorWithParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20instancenormalizationdescriptor_20_3e_5945',['QueueDescriptorWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20l2normalizationdescriptor_20_3e_5946',['QueueDescriptorWithParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logicalbinarydescriptor_20_3e_5947',['QueueDescriptorWithParameters&lt; LogicalBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logsoftmaxdescriptor_20_3e_5948',['QueueDescriptorWithParameters&lt; LogSoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20lstmdescriptor_20_3e_5949',['QueueDescriptorWithParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20meandescriptor_20_3e_5950',['QueueDescriptorWithParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20normalizationdescriptor_20_3e_5951',['QueueDescriptorWithParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20originsdescriptor_20_3e_5952',['QueueDescriptorWithParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20paddescriptor_20_3e_5953',['QueueDescriptorWithParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20permutedescriptor_20_3e_5954',['QueueDescriptorWithParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling2ddescriptor_20_3e_5955',['QueueDescriptorWithParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling3ddescriptor_20_3e_5956',['QueueDescriptorWithParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20precompileddescriptor_20_3e_5957',['QueueDescriptorWithParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20qlstmdescriptor_20_3e_5958',['QueueDescriptorWithParameters&lt; QLstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reducedescriptor_20_3e_5959',['QueueDescriptorWithParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reshapedescriptor_20_3e_5960',['QueueDescriptorWithParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20resizedescriptor_20_3e_5961',['QueueDescriptorWithParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20scatternddescriptor_20_3e_5962',['QueueDescriptorWithParameters&lt; ScatterNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20slicedescriptor_20_3e_5963',['QueueDescriptorWithParameters&lt; SliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20softmaxdescriptor_20_3e_5964',['QueueDescriptorWithParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetobatchnddescriptor_20_3e_5965',['QueueDescriptorWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetodepthdescriptor_20_3e_5966',['QueueDescriptorWithParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stackdescriptor_20_3e_5967',['QueueDescriptorWithParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stridedslicedescriptor_20_3e_5968',['QueueDescriptorWithParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20tiledescriptor_20_3e_5969',['QueueDescriptorWithParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_5970',['QueueDescriptorWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposedescriptor_20_3e_5971',['QueueDescriptorWithParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20viewsdescriptor_20_3e_5972',['QueueDescriptorWithParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]]
];
