Arm NN: ModelToINetworkTransformer Class Reference
ModelToINetworkTransformer Class Reference
#include <ModelToINetworkTransformer.hpp>
Public Member Functions
ModelToINetworkTransformer (const std::vector< armnn::BackendId > &backends, const Model &model, const std::set< unsigned int > &forcedUnsupportedOperations)
ConversionResult GetConversionResult () const
armnn::INetwork * GetINetwork () const
bool IsOperationSupported (uint32_t operationIndex) const
Detailed Description
Definition at line 30 of file ModelToINetworkTransformer.hpp.
Constructor & Destructor Documentation
ModelToINetworkTransformer()
ModelToINetworkTransformer (const std::vector< armnn::BackendId > & backends, const Model & model, const std::set< unsigned int > & forcedUnsupportedOperations)
Definition at line 18 of file ModelToINetworkTransformer.cpp.
     : m_Data(backends)
     , m_Model(model)
     , m_ForcedUnsupportedOperations(forcedUnsupportedOperations)
     , m_ConversionResult(ConversionResult::Success)
 {
     try
     {
         Convert();
     }
     catch (std::exception& e)
     {
         m_ConversionResult = ConversionResult::UnsupportedFeature;
         VLOG(DRIVER) << "ModelToINetworkTransformer: Unexpected exception: " << e.what() << " Model was: "
                      << GetModelSummary(model);
         assert(false);
     }
 }
References armnn_driver::GetModelSummary(), armnn::Success, and armnn_driver::UnsupportedFeature.
Member Function Documentation
GetConversionResult()
ConversionResult GetConversionResult () const inline
Definition at line 37 of file ModelToINetworkTransformer.hpp.
 { return m_ConversionResult; }
Referenced by ArmnnDriver::getSupportedOperations(), and ArmnnDriverImpl::PrepareArmnnModel().
GetINetwork()
armnn::INetwork* GetINetwork () const inline
Definition at line 40 of file ModelToINetworkTransformer.hpp.
 { return m_Data.m_Network.get(); }
Referenced by ArmnnDriverImpl::PrepareArmnnModel().
IsOperationSupported()
bool IsOperationSupported (uint32_t operationIndex) const
Definition at line 196 of file ModelToINetworkTransformer.cpp.
 {
     std::map<uint32_t, bool>::const_iterator it = m_OperationSupported.find(operationIndex);
     assert(it != m_OperationSupported.end());
     return it->second;
 }
Referenced by ArmnnDriver::getSupportedOperations().
The documentation for this class was generated from the following files:
shim/sl/canonical/ModelToINetworkTransformer.hpp
shim/sl/canonical/ModelToINetworkTransformer.cpp