Arm NN: IInputSlot Class Reference
IInputSlot Class Reference abstract
An input connection slot for a layer.
#include <INetwork.hpp>
Public Member Functions
virtual const IOutputSlot * GetConnection () const =0
virtual IOutputSlot * GetConnection ()=0
virtual const IConnectableLayer & GetOwningIConnectableLayer () const =0
virtual IConnectableLayer & GetOwningIConnectableLayer ()=0
virtual unsigned int GetSlotIndex () const =0
virtual void SetTensorInfo (const TensorInfo tensorInfo)=0
Sets the TensorInfo for this InputSlot.
virtual const TensorInfo & GetTensorInfo () const =0
Gets the TensorInfo for this InputSlot.
virtual bool IsTensorInfoSet () const =0
Returns true if this InputSlot either has an overridden TensorInfo for this InputSlot that was set through a call to SetTensorInfo() or is Connected to an OutputSlot that has its TensorInfo set.
virtual bool IsTensorInfoOverridden () const =0
Returns true if this InputSlot has an overridden TensorInfo that was set through a call to SetTensorInfo().
Protected Member Functions
~IInputSlot ()
Not user deletable.
Detailed Description
An input connection slot for a layer.
The input slot can be connected to an output slot of the preceding layer in the graph. Only one connection to the input slot is allowed.
Definition at line 25 of file INetwork.hpp.
Constructor & Destructor Documentation
~IInputSlot()
~IInputSlot () inline protected
Not user deletable.
Definition at line 48 of file INetwork.hpp.
 {}
Member Function Documentation
GetConnection() [1/2]
virtual const IOutputSlot* GetConnection () const pure virtual
Implemented in InputSlot.
Referenced by armnn_driver::IsConnectedToDequantize(), and armnn_driver::SetupAndTrackLayerOutputSlot().
GetConnection() [2/2]
virtual IOutputSlot* GetConnection () pure virtual
Implemented in InputSlot.
GetOwningIConnectableLayer() [1/2]
virtual const IConnectableLayer& GetOwningIConnectableLayer () const pure virtual
Implemented in InputSlot.
GetOwningIConnectableLayer() [2/2]
virtual IConnectableLayer& GetOwningIConnectableLayer () pure virtual
Implemented in InputSlot.
GetSlotIndex()
virtual unsigned int GetSlotIndex () const pure virtual
Implemented in InputSlot.
GetTensorInfo()
virtual const TensorInfo& GetTensorInfo () const pure virtual
Gets the TensorInfo for this InputSlot.
If the InputSlot's TensorInfo has not been set then this will get the TensorInfo from the Connected TensorInfo.
Implemented in InputSlot.
IsTensorInfoOverridden()
virtual bool IsTensorInfoOverridden () const pure virtual
Returns true if this InputSlot has an overridden TensorInfo that was set through a call to SetTensorInfo().
Implemented in InputSlot.
IsTensorInfoSet()
virtual bool IsTensorInfoSet () const pure virtual
Returns true if this InputSlot either has an overridden TensorInfo for this InputSlot that was set through a call to SetTensorInfo() or is Connected to an OutputSlot that has its TensorInfo set.
Implemented in InputSlot.
SetTensorInfo()
virtual void SetTensorInfo (const TensorInfo tensorInfo) pure virtual
Sets the TensorInfo for this InputSlot.
This can be used to override the TensorInfo and if set will be returned instead of the TensorInfo for the Connected OutputSlot.
Implemented in InputSlot.
Referenced by SubgraphView::GetWorkingCopy().
The documentation for this class was generated from the following file:
include/armnn/INetwork.hpp