Arm NN: ScaledInt32PerAxisDecoder Class Reference
ScaledInt32PerAxisDecoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
ScaledInt32PerAxisDecoder (const int32_t *data, const armnn::TensorInfo tensorInfo)
float Get () const override
float GetScale () const
std::vector< float > DecodeTensor (const TensorShape &tensorShape, bool isDepthwise) override
Public Member Functions inherited from PerAxisIterator< const int32_t, Decoder< float > >
PerAxisIterator (const int32_t *data=nullptr, unsigned int axisFactor=0, unsigned int axisDimensionality=0)
PerAxisIterator (const int32_t *data=nullptr, const armnn::TensorShape &tensorShape=TensorShape(), const unsigned int axis=0)
void Reset (void *data) override
PerAxisIterator & operator++ () override
PerAxisIterator & operator+= (const unsigned int increment) override
PerAxisIterator & operator-= (const unsigned int decrement) override
PerAxisIterator & SetIndexOnMem (const unsigned int index)
PerAxisIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
virtual float Get () const=0
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from PerAxisIterator< const int32_t, Decoder< float > >
const int32_t * m_Iterator
const int32_t * m_Start
unsigned int m_AxisIndex
unsigned int m_AxisDimensionality
unsigned int m_AxisFactor
unsigned int m_Index
Detailed Description
Definition at line 861 of file BaseIterator.hpp.
Constructor & Destructor Documentation
ScaledInt32PerAxisDecoder()
ScaledInt32PerAxisDecoder (const int32_t * data, const armnn::TensorInfo tensorInfo) inline
Definition at line 864 of file BaseIterator.hpp.
     : PerAxisIterator(data, tensorInfo.GetShape(), tensorInfo.GetQuantizationDim().value()),
       m_Scales(tensorInfo.GetQuantizationScales())
     {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, bool isDepthwise) inline override virtual
Implements Decoder< float >.
Definition at line 880 of file BaseIterator.hpp.
     {
         const uint32_t size = tensorShape.GetNumElements();
         const uint32_t stepSize = isDepthwise ?
                                   tensorShape[2] * tensorShape[3] : tensorShape.GetNumElements() / tensorShape[0];
         const uint32_t stepNum = size / stepSize;
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         // channelMultiplier is only used in depthwise convolutions and in other cases will have no effect
         // stepSize is the length of a contiguous area sharing a quantization scale within a tensor
         // stepNum is the number of those steps/blocks in the tensor
         for (uint32_t step = 0; step < stepNum; ++step)
         {
             //scale = (channelMultiplier * step + mult) % scaleSize;
             for (uint32_t i = 0; i < stepSize; ++i)
             {
                 unsigned int index = step * stepSize + i;
                 this->operator[](index);
                 decodedTensor.emplace_back(armnn::Dequantize(*m_Iterator, m_Scales[step], 0));
             }
         }
         return decodedTensor;
     }
References armnn::Dequantize(), TensorShape::GetNumElements(), PerAxisIterator< const int32_t, Decoder< float > >::m_Iterator, and PerAxisIterator< const int32_t, Decoder< float > >::operator[]().
Get()
float Get () const inline override
Definition at line 869 of file BaseIterator.hpp.
     {
         return armnn::Dequantize(*m_Iterator, m_Scales[m_AxisIndex], 0);
     }
References armnn::Dequantize(), PerAxisIterator< const int32_t, Decoder< float > >::m_AxisIndex, and PerAxisIterator< const int32_t, Decoder< float > >::m_Iterator.
GetScale()
float GetScale () const inline
Definition at line 875 of file BaseIterator.hpp.
     {
         return m_Scales[m_AxisIndex];
     }
References PerAxisIterator< const int32_t, Decoder< float > >::m_AxisIndex.
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp