Arm NN: SampleDynamicTensorHandleFactory Class Reference
SampleDynamicTensorHandleFactory Class Reference
#include <SampleDynamicTensorHandleFactory.hpp>
Public Member Functions
SampleDynamicTensorHandleFactory (std::shared_ptr< SampleMemoryManager > mgr)
std::unique_ptr< armnn::ITensorHandle > CreateSubTensorHandle (armnn::ITensorHandle &parent, armnn::TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo &tensorInfo) const override
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo &tensorInfo, armnn::DataLayout dataLayout) const override
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo &tensorInfo, const bool IsMemoryManaged) const override
Utility Functions for backends which require TensorHandles to have unmanaged memory.
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo &tensorInfo, armnn::DataLayout dataLayout, const bool IsMemoryManaged) const override
const FactoryId & GetId () const override
bool SupportsSubTensors () const override
armnn::MemorySourceFlags GetExportFlags () const override
armnn::MemorySourceFlags GetImportFlags () const override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual bool SupportsInPlaceComputation () const
virtual bool SupportsMapUnmap () const
virtual std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass)
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Detailed Description
Definition at line 17 of file SampleDynamicTensorHandleFactory.hpp.
Constructor & Destructor Documentation
SampleDynamicTensorHandleFactory()
SampleDynamicTensorHandleFactory (std::shared_ptr< SampleMemoryManager > mgr) inline
Definition at line 21 of file SampleDynamicTensorHandleFactory.hpp.
     : m_MemoryManager(mgr),
       m_ImportFlags(static_cast<armnn::MemorySourceFlags>(armnn::MemorySource::Malloc)),
       m_ExportFlags(static_cast<armnn::MemorySourceFlags>(armnn::MemorySource::Malloc))
     {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< armnn::ITensorHandle > CreateSubTensorHandle (armnn::ITensorHandle & parent, armnn::TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 23 of file SampleDynamicTensorHandleFactory.cpp.
 {
     IgnoreUnused(parent, subTensorShape, subTensorOrigin);
     return nullptr;
 }
References armnn::IgnoreUnused().
CreateTensorHandle() [1/4]
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 31 of file SampleDynamicTensorHandleFactory.cpp.
 {
     return std::make_unique<SampleTensorHandle>(tensorInfo, m_MemoryManager);
 }
CreateTensorHandle() [2/4]
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo & tensorInfo, armnn::DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 37 of file SampleDynamicTensorHandleFactory.cpp.
 {
     IgnoreUnused(dataLayout);
     return std::make_unique<SampleTensorHandle>(tensorInfo, m_MemoryManager);
 }
References armnn::IgnoreUnused().
CreateTensorHandle() [3/4]
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo & tensorInfo, armnn::DataLayout dataLayout, const bool IsMemoryManaged) const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 59 of file SampleDynamicTensorHandleFactory.cpp.
 {
     IgnoreUnused(dataLayout);
     if (IsMemoryManaged)
     {
         return std::make_unique<SampleTensorHandle>(tensorInfo, m_MemoryManager);
     }
     else
     {
         return std::make_unique<SampleTensorHandle>(tensorInfo, m_ImportFlags);
     }
 }
References armnn::IgnoreUnused().
CreateTensorHandle() [4/4]
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo & tensorInfo, const bool IsMemoryManaged) const override virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented from ITensorHandleFactory.
Definition at line 45 of file SampleDynamicTensorHandleFactory.cpp.
 {
     if (IsMemoryManaged)
     {
         return std::make_unique<SampleTensorHandle>(tensorInfo, m_MemoryManager);
     }
     else
     {
         return std::make_unique<SampleTensorHandle>(tensorInfo, m_ImportFlags);
     }
 }
GetExportFlags()
armnn::MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 85 of file SampleDynamicTensorHandleFactory.cpp.
 {
     return m_ExportFlags;
 }
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 75 of file SampleDynamicTensorHandleFactory.cpp.
 {
     return GetIdStatic();
 }
References SampleDynamicTensorHandleFactory::GetIdStatic().
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 16 of file SampleDynamicTensorHandleFactory.cpp.
 {
     static const FactoryId s_Id(SampleDynamicTensorHandleFactoryId());
     return s_Id;
 }
References sdb::SampleDynamicTensorHandleFactoryId().
Referenced by SampleDynamicTensorHandleFactory::GetId().
GetImportFlags()
armnn::MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 90 of file SampleDynamicTensorHandleFactory.cpp.
 {
     return m_ImportFlags;
 }
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 80 of file SampleDynamicTensorHandleFactory.cpp.
 {
     return false;
 }
The documentation for this class was generated from the following files:
src/dynamic/sample/SampleDynamicTensorHandleFactory.hpp
src/dynamic/sample/SampleDynamicTensorHandleFactory.cpp