Arm NN: ArmnnDriver Class Reference
ArmnnDriver Class Reference
#include <ArmnnDriver.hpp>
Public Member Functions
ArmnnDriver (DriverOptions options)
const std::string & getName () const override
const std::string & getVersionString () const override
Version getFeatureLevel () const override
DeviceType getType () const override
const std::vector< Extension > & getSupportedExtensions () const override
const Capabilities & getCapabilities () const override
std::pair< uint32_t, uint32_t > getNumberOfCacheFilesNeeded () const override
GeneralResult< void > wait () const override
GeneralResult< std::vector< bool > > getSupportedOperations (const Model &model) const override
GeneralResult< SharedPreparedModel > prepareModel (const Model &model, ExecutionPreference preference, Priority priority, OptionalTimePoint deadline, const std::vector< SharedHandle > &modelCache, const std::vector< SharedHandle > &dataCache, const CacheToken &token, const std::vector< android::nn::TokenValuePair > &hints, const std::vector< android::nn::ExtensionNameAndPrefix > &extensionNameToPrefix) const override
GeneralResult< SharedPreparedModel > prepareModelFromCache (OptionalTimePoint deadline, const std::vector< SharedHandle > &modelCache, const std::vector< SharedHandle > &dataCache, const CacheToken &token) const override
GeneralResult< SharedBuffer > allocate (const BufferDesc &, const std::vector< SharedPreparedModel > &, const std::vector< BufferRole > &, const std::vector< BufferRole > &) const override
Detailed Description
Definition at line 31 of file ArmnnDriver.hpp.
Constructor & Destructor Documentation
ArmnnDriver()
ArmnnDriver (DriverOptions options) inline
Definition at line 37 of file ArmnnDriver.hpp.
     {
         try
         {
             VLOG(DRIVER) << "ArmnnDriver::ArmnnDriver()";
             m_Device = std::unique_ptr<ArmnnDevice>(new ArmnnDevice(std::move(options)));
         }
         catch (armnn::InvalidArgumentException& ex)
         {
             VLOG(DRIVER) << "ArmnnDevice failed to initialise: " << ex.what();
         }
         catch (...)
         {
             VLOG(DRIVER) << "ArmnnDevice failed to initialise with an unknown error";
         }
     }
References Exception::what().
Member Function Documentation
allocate()
GeneralResult<SharedBuffer> allocate (const BufferDesc & , const std::vector< SharedPreparedModel > & , const std::vector< BufferRole > & , const std::vector< BufferRole > &) const inline override
Definition at line 256 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::allocate()";
         return NN_ERROR(ErrorStatus::INVALID_ARGUMENT) << "ArmnnDriver::allocate -- does not support allocate.";
     }
getCapabilities()
const Capabilities& getCapabilities () const inline override
Definition at line 89 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::GetCapabilities()";
         return ArmnnDriverImpl::GetCapabilities(m_Device->m_Runtime);
     }
References ArmnnDriverImpl::GetCapabilities().
getFeatureLevel()
Version getFeatureLevel () const inline override
Definition at line 70 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getFeatureLevel()";
         return kVersionFeatureLevel6;
     }
getName()
const std::string& getName () const inline override
Definition at line 56 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getName()";
         static const std::string name = "arm-armnn-sl";
         return name;
     }
getNumberOfCacheFilesNeeded()
std::pair<uint32_t, uint32_t> getNumberOfCacheFilesNeeded () const inline override
Definition at line 95 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getNumberOfCacheFilesNeeded()";
         unsigned int numberOfCachedModelFiles = 0;
         for (auto& backend : m_Device->m_Options.GetBackends())
         {
             numberOfCachedModelFiles += GetNumberOfCacheFiles(backend);
             VLOG(DRIVER) << "ArmnnDriver::getNumberOfCacheFilesNeeded() = "
                          << std::to_string(numberOfCachedModelFiles);
         }
         return std::make_pair(numberOfCachedModelFiles, 1ul);
     }
References armnn::GetNumberOfCacheFiles().
getSupportedExtensions()
const std::vector<Extension>& getSupportedExtensions () const inline override
Definition at line 82 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getSupportedExtensions()";
         static const std::vector<Extension> extensions = {};
         return extensions;
     }
getSupportedOperations()
GeneralResult<std::vector<bool> > getSupportedOperations (const Model & model) const inline override
Definition at line 114 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getSupportedOperations()";
         if (m_Device.get() == nullptr)
         {
             return NN_ERROR(ErrorStatus::DEVICE_UNAVAILABLE) << "Device Unavailable!";
         }
         std::stringstream ss;
         ss << "ArmnnDriverImpl::getSupportedOperations()";
         std::string fileName;
         std::string timestamp;
         if (!m_Device->m_Options.GetRequestInputsAndOutputsDumpDir().empty())
         {
             ss << " : "
                << m_Device->m_Options.GetRequestInputsAndOutputsDumpDir()
                << "/"
                // << GetFileTimestamp()
                << "_getSupportedOperations.txt";
         }
         VLOG(DRIVER) << ss.str().c_str();
         if (!m_Device->m_Options.GetRequestInputsAndOutputsDumpDir().empty())
         {
             //dump the marker file
             std::ofstream fileStream;
             fileStream.open(fileName, std::ofstream::out | std::ofstream::trunc);
             if (fileStream.good())
             {
                 fileStream << timestamp << std::endl;
                 fileStream << timestamp << std::endl;
             }
             fileStream.close();
         }
         std::vector<bool> result;
         if (!m_Device->m_Runtime)
         {
             return NN_ERROR(ErrorStatus::DEVICE_UNAVAILABLE) << "Device Unavailable!";
         }
         // Run general model validation, if this doesn't pass we shouldn't analyse the model anyway.
         if (const auto result = validate(model); !result.ok())
         {
             return NN_ERROR(ErrorStatus::INVALID_ARGUMENT) << "Invalid Model!";
         }
         // Attempt to convert the model to an ArmNN input network (INetwork).
         ModelToINetworkTransformer modelConverter(m_Device->m_Options.GetBackends(),
                                                   model,
                                                   m_Device->m_Options.GetForcedUnsupportedOperations());
         if (modelConverter.GetConversionResult() != ConversionResult::Success
             && modelConverter.GetConversionResult() != ConversionResult::UnsupportedFeature)
         {
             return NN_ERROR(ErrorStatus::GENERAL_FAILURE) << "Conversion Error!";
         }
         // Check each operation if it was converted successfully and copy the flags
         // into the result (vector<bool>) that we need to return to Android.
         result.reserve(model.main.operations.size());
         for (uint32_t operationIdx = 0; operationIdx < model.main.operations.size(); ++operationIdx)
         {
             bool operationSupported = modelConverter.IsOperationSupported(operationIdx);
             result.push_back(operationSupported);
         }
         return result;
     }
References ModelToINetworkTransformer::GetConversionResult(), ModelToINetworkTransformer::IsOperationSupported(), armnn_driver::Success, and armnn_driver::UnsupportedFeature.
getType()
DeviceType getType () const inline override
Definition at line 76 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getType()";
         return DeviceType::CPU;
     }
getVersionString()
const std::string& getVersionString () const inline override
Definition at line 63 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::getVersionString()";
         static const std::string versionString = ARMNN_VERSION;
         return versionString;
     }
References ARMNN_VERSION.
prepareModel()
GeneralResult<SharedPreparedModel> prepareModel (const Model & model, ExecutionPreference preference, Priority priority, OptionalTimePoint deadline, const std::vector< SharedHandle > & modelCache, const std::vector< SharedHandle > & dataCache, const CacheToken & token, const std::vector< android::nn::TokenValuePair > & hints, const std::vector< android::nn::ExtensionNameAndPrefix > & extensionNameToPrefix) const inline override
Definition at line 184 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::prepareModel()";
         if (m_Device.get() == nullptr)
         {
             return NN_ERROR(ErrorStatus::DEVICE_UNAVAILABLE) << "Device Unavailable!";
         }
         // Validate arguments.
         if (const auto result = validate(model); !result.ok()) {
             return NN_ERROR(ErrorStatus::INVALID_ARGUMENT) << "Invalid Model: " << result.error();
         }
         if (const auto result = validate(preference); !result.ok()) {
             return NN_ERROR(ErrorStatus::INVALID_ARGUMENT)
                 << "Invalid ExecutionPreference: " << result.error();
         }
         if (const auto result = validate(priority); !result.ok()) {
             return NN_ERROR(ErrorStatus::INVALID_ARGUMENT) << "Invalid Priority: " << result.error();
         }
         // Check if deadline has passed.
         if (hasDeadlinePassed(deadline)) {
             return NN_ERROR(ErrorStatus::MISSED_DEADLINE_PERSISTENT);
         }
 ARMNN_NO_DEPRECATE_WARN_BEGIN
         return ArmnnDriverImpl::PrepareArmnnModel(m_Device->m_Runtime,
             m_Device->m_ClTunedParameters,
             m_Device->m_Options,
             model,
             modelCache,
             dataCache,
             token,
             model.relaxComputationFloat32toFloat16 && m_Device->m_Options.GetFp16Enabled(),
             priority);
 ARMNN_NO_DEPRECATE_WARN_END
     }
References ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, and ArmnnDriverImpl::PrepareArmnnModel().
prepareModelFromCache()
GeneralResult<SharedPreparedModel> prepareModelFromCache (OptionalTimePoint deadline, const std::vector< SharedHandle > & modelCache, const std::vector< SharedHandle > & dataCache, const CacheToken & token) const inline override
Definition at line 229 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::prepareModelFromCache()";
         if (m_Device.get() == nullptr)
         {
             return NN_ERROR(ErrorStatus::DEVICE_UNAVAILABLE) << "Device Unavailable!";
         }
         // Check if deadline has passed.
         if (hasDeadlinePassed(deadline)) {
             return NN_ERROR(ErrorStatus::MISSED_DEADLINE_PERSISTENT);
         }
 ARMNN_NO_DEPRECATE_WARN_BEGIN
         return ArmnnDriverImpl::PrepareArmnnModelFromCache(
                      m_Device->m_Runtime,
                      m_Device->m_ClTunedParameters,
                      m_Device->m_Options,
                      modelCache,
                      dataCache,
                      token,
                      m_Device->m_Options.GetFp16Enabled());
 ARMNN_NO_DEPRECATE_WARN_END
     }
References ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, and ArmnnDriverImpl::PrepareArmnnModelFromCache().
wait()
GeneralResult<void> wait () const inline override
Definition at line 108 of file ArmnnDriver.hpp.
     {
         VLOG(DRIVER) << "ArmnnDriver::wait()";
         return {};
     }
The documentation for this class was generated from the following file:
shim/sl/canonical/ArmnnDriver.hpp