Arm NN: OptimizeConsecutiveReshapesImpl Class Reference
OptimizeConsecutiveReshapesImpl Class Reference
#include <OptimizeConsecutiveReshapes.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Run for every connection between a base ReshapeLayer and a child ReshapeLayer.
Protected Member Functions
OptimizeConsecutiveReshapesImpl ()=default
~OptimizeConsecutiveReshapesImpl ()=default
Detailed Description
Definition at line 14 of file OptimizeConsecutiveReshapes.hpp.
Constructor & Destructor Documentation
OptimizeConsecutiveReshapesImpl()
OptimizeConsecutiveReshapesImpl () protected default
~OptimizeConsecutiveReshapesImpl()
~OptimizeConsecutiveReshapesImpl () protected default
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Run for every connection between a base ReshapeLayer and a child ReshapeLayer.
Inserts an equivalent ReshapeLayer that bypasses both for that connection.
Definition at line 19 of file OptimizeConsecutiveReshapes.hpp.
     {
         Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
         Layer& child = connection.GetOwningLayer();
         ARMNN_ASSERT(base.GetType() == LayerType::Reshape);
         ARMNN_ASSERT(child.GetType() == LayerType::Reshape);
         OutputSlot* parentOut = base.GetInputSlot(0).GetConnectedOutputSlot();
         const TensorInfo& inInfo = parentOut->GetTensorInfo();
         const TensorInfo& outInfo = child.GetOutputHandler().GetTensorInfo();
         // This Optimization is only appropriate when the base ReshapeLayer is connected to the child ReshapeLayer
         // and no other Layer.
         if (base.GetOutputSlot(0).GetNumConnections() > 1)
         {
             return;
         }
         if (inInfo.GetShape() != outInfo.GetShape())
         {
             // Inserts equivalent reshape before base layer.
             const std::string name = std::string("merged-") + base.GetName() + std::string("-with-") + child.GetName();
             const ReshapeDescriptor descriptor{outInfo.GetShape()};
             auto& newReshape = *graph.InsertNewLayer<ReshapeLayer>(base.GetInputSlot(0), descriptor, name.c_str());
             // Parent is now the new layer.
             parentOut = &newReshape.GetOutputSlot();
         }
         // Moves connections in child output to parent layer.
         // Child layer will be removed as it's left unconnected.
         // Base layer will be removed if left unconnected.
         child.GetOutputSlot().MoveAllConnections(*parentOut);
     }
References ARMNN_ASSERT, InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), Layer::GetName(), OutputSlot::GetNumConnections(), Layer::GetOutputHandler(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), TensorInfo::GetShape(), OutputHandler::GetTensorInfo(), OutputSlot::GetTensorInfo(), Layer::GetType(), Graph::InsertNewLayer(), OutputSlot::MoveAllConnections(), and armnn::Reshape.
The documentation for this class was generated from the following file:
src/armnn/optimizations/OptimizeConsecutiveReshapes.hpp