Arm NN: ITensorHandle Class Reference
ITensorHandle Class Reference abstract
#include <ITensorHandle.hpp>
Public Member Functions
virtual ~ITensorHandle ()
virtual void Manage ()=0
Indicate to the memory manager that this resource is active.
virtual void Allocate ()=0
Indicate to the memory manager that this resource is no longer active.
virtual ITensorHandle * GetParent () const =0
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool blocking=true) const =0
Map the tensor data for access.
virtual void Unmap () const =0
Unmap the tensor data.
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual TensorShape GetStrides () const =0
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
virtual TensorShape GetShape () const =0
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
virtual void CopyOutTo (void *memory) const =0
Testing support to be able to verify and set tensor data content.
virtual void CopyInFrom (const void *memory)=0
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo)
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Detailed Description
Definition at line 16 of file ITensorHandle.hpp.
Constructor & Destructor Documentation
~ITensorHandle()
virtual ~ITensorHandle () inline virtual
Definition at line 19 of file ITensorHandle.hpp.
 {}
Member Function Documentation
Allocate()
virtual void Allocate () pure virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implemented in NeonTensorHandleDecorator, ClTensorHandleDecorator, ClImportSubTensorHandle, NeonSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, ConstPassthroughTensorHandle, PassthroughTensorHandle, ScopedTensorHandle, RefTensorHandleDecorator, NeonTensorHandle, ClTensorHandle, ClImportTensorHandle, GpuFsaTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Referenced by AllocateAndCopyDataToITensorHandle(), and Graph::AllocateDynamicBuffers().
CanBeImported()
virtual bool CanBeImported (void * memory, MemorySource source) inline virtual
Implementations must determine if this memory block can be imported.
This might be based on alignment or memory source type.
Returns
true if this memory can be imported.
false by default, cannot be imported.
Reimplemented in ClTensorHandle, RefTensorHandleDecorator, NeonTensorHandle, RefTensorHandle, TosaRefTensorHandle, GpuFsaTensorHandle, and ClImportTensorHandle.
Definition at line 86 of file ITensorHandle.hpp.
     {
         IgnoreUnused(memory, source);
         return false;
     };
References armnn::IgnoreUnused().
CopyInFrom()
virtual void CopyInFrom (const void * memory) pure virtual
Implemented in RefTensorHandleDecorator.
Referenced by CopyDataToITensorHandle().
CopyOutTo()
virtual void CopyOutTo (void * memory) const pure virtual
Testing support to be able to verify and set tensor data content.
Implemented in RefTensorHandleDecorator.
Referenced by CopyDataFromITensorHandle().
DecorateTensorHandle()
virtual std::shared_ptr<ITensorHandle> DecorateTensorHandle (const TensorInfo & tensorInfo) inline virtual
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Parameters
tensorInfo the overidden TensorInfo.
Reimplemented in NeonTensorHandle, ClTensorHandle, RefTensorHandleDecorator, RefTensorHandle, NeonTensorHandleDecorator, and NeonSubTensorHandle.
Definition at line 98 of file ITensorHandle.hpp.
     {
         IgnoreUnused(tensorInfo);
         return nullptr;
     }
References armnn::IgnoreUnused().
GetImportFlags()
virtual unsigned int GetImportFlags () const inline virtual
Get flags describing supported import sources.
Reimplemented in RefTensorHandleDecorator, ClTensorHandle, GpuFsaTensorHandle, NeonTensorHandle, ClImportTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Definition at line 70 of file ITensorHandle.hpp.
 { return 0; }
Referenced by LoadedNetwork::ImportInputs(), and LoadedNetwork::ImportOutputs().
GetParent()
virtual ITensorHandle* GetParent () const pure virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implemented in NeonTensorHandleDecorator, ClTensorHandleDecorator, ClImportSubTensorHandle, NeonSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, RefTensorHandleDecorator, ClTensorHandle, GpuFsaTensorHandle, NeonTensorHandle, ClImportTensorHandle, ConstTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Referenced by Graph::AllocateDynamicBuffers().
GetShape()
virtual TensorShape GetShape () const pure virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implemented in NeonTensorHandleDecorator, ClTensorHandleDecorator, ClImportSubTensorHandle, NeonSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, RefTensorHandleDecorator, ClTensorHandle, GpuFsaTensorHandle, NeonTensorHandle, ClImportTensorHandle, ConstTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Referenced by armnn::CopyTensorContentsGeneric(), and armnnUtils::FindMinMax().
GetStrides()
virtual TensorShape GetStrides () const pure virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implemented in NeonTensorHandleDecorator, ClTensorHandleDecorator, ClImportSubTensorHandle, NeonSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, RefTensorHandleDecorator, ClTensorHandle, GpuFsaTensorHandle, NeonTensorHandle, ClImportTensorHandle, ConstTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Referenced by armnn::CopyTensorContentsGeneric().
Import()
virtual bool Import (void * memory, MemorySource source) inline virtual
Import externally allocated memory.
Parameters
memory base address of the memory being imported.
source source of the allocation for the memory being imported.
Returns
true on success or false on failure
Reimplemented in NeonTensorHandle, ClTensorHandle, RefTensorHandleDecorator, ClImportTensorHandle, RefTensorHandle, TosaRefTensorHandle, SampleTensorHandle, and GpuFsaTensorHandle.
Definition at line 76 of file ITensorHandle.hpp.
     {
         IgnoreUnused(memory, source);
         return false;
     };
References armnn::IgnoreUnused().
Referenced by LoadedNetwork::ImportInputs(), and LoadedNetwork::ImportOutputs().
Manage()
virtual void Manage () pure virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implemented in NeonTensorHandleDecorator, ClTensorHandleDecorator, ClImportSubTensorHandle, NeonSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, RefTensorHandleDecorator, ClTensorHandle, NeonTensorHandle, GpuFsaTensorHandle, ClImportTensorHandle, ConstTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Referenced by Graph::AllocateDynamicBuffers().
Map() [1/2]
void* Map (bool blocking = true) inline
Map the tensor data for access.
Must be paired with call to Unmap().
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Definition at line 44 of file ITensorHandle.hpp.
     {
         return const_cast<void*>(static_cast<const ITensorHandle*>(this)->Map(blocking));
     }
References ITensorHandle::Map().
Map() [2/2]
virtual const void* Map (bool blocking = true) const pure virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implemented in NeonTensorHandleDecorator, NeonSubTensorHandle, RefTensorHandleDecorator, NeonTensorHandle, ConstTensorHandle, RefTensorHandle, TosaRefTensorHandle, SampleTensorHandle, ClTensorHandleDecorator, ClImportSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, ClTensorHandle, GpuFsaTensorHandle, and ClImportTensorHandle.
Referenced by armnn::CopyTensorContentsGeneric(), SyncMemGenericWorkload::Execute(), armnnUtils::FindMinMax(), sdb::GetInputTensorData(), armnn::GetInputTensorData(), sdb::GetOutputTensorData(), armnn::GetOutputTensorData(), armnn::InitializeArmComputeTensorData(), ITensorHandle::Map(), armnn::MirrorPad(), and armnn::Pad().
Unimport()
virtual void Unimport () inline virtual
Unimport externally allocated memory.
Reimplemented in RefTensorHandleDecorator.
Definition at line 93 of file ITensorHandle.hpp.
     {};
Unmap() [1/2]
void Unmap () inline
Unmap the tensor data that was previously mapped with call to Map().
Definition at line 50 of file ITensorHandle.hpp.
     {
         return static_cast<const ITensorHandle*>(this)->Unmap();
     }
References ITensorHandle::Unmap().
Unmap() [2/2]
virtual void Unmap () const pure virtual
Unmap the tensor data.
Implemented in NeonTensorHandleDecorator, ClTensorHandleDecorator, ClImportSubTensorHandle, NeonSubTensorHandle, ClSubTensorHandle, GpuFsaSubTensorHandle, RefTensorHandleDecorator, NeonTensorHandle, ClTensorHandle, GpuFsaTensorHandle, ClImportTensorHandle, ConstTensorHandle, RefTensorHandle, TosaRefTensorHandle, and SampleTensorHandle.
Referenced by armnn::CopyTensorContentsGeneric(), SyncMemGenericWorkload::Execute(), armnnUtils::FindMinMax(), and ITensorHandle::Unmap().
The documentation for this class was generated from the following file:
include/armnn/backends/ITensorHandle.hpp