Arm NN: DeleteBroadcastToImpl Class Reference
DeleteBroadcastToImpl Class Reference
#include <DeleteBroadcastTo.hpp>
Public Member Functions
void Run (Graph &, BroadcastToLayer &layer) const
Run for every BroadcastToLayer.
Protected Member Functions
DeleteBroadcastToImpl ()=default
~DeleteBroadcastToImpl ()=default
Detailed Description
Definition at line 13 of file DeleteBroadcastTo.hpp.
Constructor & Destructor Documentation
DeleteBroadcastToImpl()
DeleteBroadcastToImpl () protected default
~DeleteBroadcastToImpl()
~DeleteBroadcastToImpl () protected default
Member Function Documentation
Run()
void Run (Graph & , BroadcastToLayer & layer) const inline
Run for every BroadcastToLayer.
Remove it if it is before an ElementWiseLayer. Since ElementWiseBinary uses a brodcastLoop, using a broadcastTo layer is not necessary so it will be deleted.
Definition at line 19 of file DeleteBroadcastTo.hpp.
     {
         if(layer.GetType() == LayerType::BroadcastTo)
         {
             TensorInfo info = layer.GetOutputSlot(0).GetTensorInfo();
             Layer& next = layer.GetOutputSlot(0).GetConnection(0)->GetOwningLayer();
             if (next.GetType() == LayerType::ElementwiseBinary)
             {
                 Layer& connectedLayer = layer.GetInputSlots()[0].GetConnectedOutputSlot()->GetOwningLayer();
                 auto tensorInfo = connectedLayer.GetOutputSlot().GetTensorInfo();
                 layer.GetOutputSlot().MoveAllConnections(connectedLayer.GetOutputSlot());
                 connectedLayer.GetOutputSlot().GetOutputHandler().SetTensorInfo(tensorInfo);
             }
         }
     }
References armnn::BroadcastTo, armnn::ElementwiseBinary, OutputSlot::GetConnection(), Layer::GetInputSlots(), OutputSlot::GetOutputHandler(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetTensorInfo(), Layer::GetType(), armnn::info, OutputSlot::MoveAllConnections(), and OutputHandler::SetTensorInfo().
The documentation for this class was generated from the following file:
src/armnn/optimizations/DeleteBroadcastTo.hpp