Arm NN: RefMemoryManager::Pool Class Reference
RefMemoryManager::Pool Class Reference
#include <RefMemoryManager.hpp>
Public Member Functions
Pool (unsigned int numBytes)
~Pool ()
void Acquire ()
void Release ()
void * GetPointer ()
void Reserve (unsigned int numBytes)
Detailed Description
Definition at line 33 of file RefMemoryManager.hpp.
Constructor & Destructor Documentation
Pool()
Pool (unsigned int numBytes)
Definition at line 63 of file RefMemoryManager.cpp.
     : m_Size(numBytes),
       m_Pointer(nullptr)
 {}
~Pool()
~Pool ()
Definition at line 68 of file RefMemoryManager.cpp.
 {
     if (m_Pointer)
     {
         Release();
     }
 }
References RefMemoryManager::Release().
Member Function Documentation
Acquire()
void Acquire ()
Definition at line 90 of file RefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(!m_Pointer, RuntimeException,
                              "RefMemoryManager::Pool::Acquire() called when memory already acquired");
     m_Pointer = ::operator new(size_t(m_Size));
 }
References ARMNN_THROW_MSG_IF_FALSE.
GetPointer()
void * GetPointer ()
Definition at line 76 of file RefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(m_Pointer, RuntimeException,
                              "RefMemoryManager::Pool::GetPointer() called when memory not acquired");
     return m_Pointer;
 }
References ARMNN_THROW_MSG_IF_FALSE.
Referenced by RefMemoryManager::GetPointer().
Release()
void Release ()
Definition at line 97 of file RefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(m_Pointer, RuntimeException,
                              "RefMemoryManager::Pool::Release() called when memory not acquired");
     ::operator delete(m_Pointer);
     m_Pointer = nullptr;
 }
References ARMNN_THROW_MSG_IF_FALSE.
Reserve()
void Reserve (unsigned int numBytes)
Definition at line 83 of file RefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(!m_Pointer, RuntimeException,
                              "RefMemoryManager::Pool::Reserve() cannot be called after memory acquired");
     m_Size = std::max(m_Size, numBytes);
 }
References ARMNN_THROW_MSG_IF_FALSE.
Referenced by RefMemoryManager::Manage().
The documentation for this class was generated from the following files:
src/backends/reference/RefMemoryManager.hpp
src/backends/reference/RefMemoryManager.cpp