var namespacearmnn_1_1optimizations =
[
    [ "pad_fold", "namespacearmnn_1_1optimizations_1_1pad__fold.html", "namespacearmnn_1_1optimizations_1_1pad__fold" ],
    [ "AddBroadcastReshapeLayerImpl", "classarmnn_1_1optimizations_1_1_add_broadcast_reshape_layer_impl.html", "classarmnn_1_1optimizations_1_1_add_broadcast_reshape_layer_impl" ],
    [ "AddDebugImpl", "classarmnn_1_1optimizations_1_1_add_debug_impl.html", "classarmnn_1_1optimizations_1_1_add_debug_impl" ],
    [ "AddDebugToFileImpl", "classarmnn_1_1optimizations_1_1_add_debug_to_file_impl.html", "classarmnn_1_1optimizations_1_1_add_debug_to_file_impl" ],
    [ "ConvertConstants", "classarmnn_1_1optimizations_1_1_convert_constants.html", "classarmnn_1_1optimizations_1_1_convert_constants" ],
    [ "ConvertConstDequantisationLayersToConstLayersImpl", "classarmnn_1_1optimizations_1_1_convert_const_dequantisation_layers_to_const_layers_impl.html", "classarmnn_1_1optimizations_1_1_convert_const_dequantisation_layers_to_const_layers_impl" ],
    [ "ConvertConstPermuteLayersToConstLayers", "classarmnn_1_1optimizations_1_1_convert_const_permute_layers_to_const_layers.html", "classarmnn_1_1optimizations_1_1_convert_const_permute_layers_to_const_layers" ],
    [ "ConvertFp32NetworkToFp16Impl", "classarmnn_1_1optimizations_1_1_convert_fp32_network_to_fp16_impl.html", "classarmnn_1_1optimizations_1_1_convert_fp32_network_to_fp16_impl" ],
    [ "DeleteBroadcastToImpl", "classarmnn_1_1optimizations_1_1_delete_broadcast_to_impl.html", "classarmnn_1_1optimizations_1_1_delete_broadcast_to_impl" ],
    [ "Float16ToFloat32", "structarmnn_1_1optimizations_1_1_float16_to_float32.html", null ],
    [ "Float32ToFloat16", "structarmnn_1_1optimizations_1_1_float32_to_float16.html", null ],
    [ "FuseBatchNorm", "classarmnn_1_1optimizations_1_1_fuse_batch_norm.html", "classarmnn_1_1optimizations_1_1_fuse_batch_norm" ],
    [ "IsFloat16Layer", "structarmnn_1_1optimizations_1_1_is_float16_layer.html", null ],
    [ "IsFloat32Layer", "structarmnn_1_1optimizations_1_1_is_float32_layer.html", null ],
    [ "MaxMinIntoBoundedReluImpl", "classarmnn_1_1optimizations_1_1_max_min_into_bounded_relu_impl.html", "classarmnn_1_1optimizations_1_1_max_min_into_bounded_relu_impl" ],
    [ "MovePermuteUpImpl", "classarmnn_1_1optimizations_1_1_move_permute_up_impl.html", "classarmnn_1_1optimizations_1_1_move_permute_up_impl" ],
    [ "MoveTransposeUpImpl", "classarmnn_1_1optimizations_1_1_move_transpose_up_impl.html", "classarmnn_1_1optimizations_1_1_move_transpose_up_impl" ],
    [ "OptimizeConsecutiveReshapesImpl", "classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl.html", "classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl" ],
    [ "OptimizeInverseConversionsImpl", "classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl.html", "classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl" ],
    [ "OptimizeInversePermutesImpl", "classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl.html", "classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl" ],
    [ "PermuteAndBatchToSpaceAsDepthToSpaceImpl", "classarmnn_1_1optimizations_1_1_permute_and_batch_to_space_as_depth_to_space_impl.html", "classarmnn_1_1optimizations_1_1_permute_and_batch_to_space_as_depth_to_space_impl" ],
    [ "PermuteAsReshapeImpl", "classarmnn_1_1optimizations_1_1_permute_as_reshape_impl.html", "classarmnn_1_1optimizations_1_1_permute_as_reshape_impl" ],
    [ "PermuteDepthwiseConv2dWeightsImpl", "classarmnn_1_1optimizations_1_1_permute_depthwise_conv2d_weights_impl.html", "classarmnn_1_1optimizations_1_1_permute_depthwise_conv2d_weights_impl" ],
    [ "SquashEqualSiblingsImpl", "classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl.html", "classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl" ],
    [ "TransposeAsReshapeImpl", "classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.html", "classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl" ]
];