Arm NN: SliceQueueDescriptor Struct Reference
SliceQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< SliceDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Additional Inherited Members
Public Attributes inherited from QueueDescriptorWithParameters< SliceDescriptor >
SliceDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions inherited from QueueDescriptorWithParameters< SliceDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 656 of file WorkloadData.hpp.
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 3634 of file WorkloadData.cpp.
 {
     const std::string descriptorName{"SliceQueueDescriptor"};
     ValidateNumInputs(workloadInfo,  descriptorName, 1);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     ValidateTensorDataTypesMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
     const unsigned int rank = inputTensorInfo.GetNumDimensions();
     if (rank > 5)
     {
         throw InvalidArgumentException(descriptorName + ": Input tensors with rank greater than 5 are not supported.");
     }
     ValidateTensorNumDimensions(outputTensorInfo, descriptorName, rank, "output");
     // Check if m_Begin and m_Size have the expected length
     if (m_Parameters.m_Begin.size() != rank)
     {
         throw InvalidArgumentException(descriptorName +
             ": Length of begin offset descriptor must equal rank " + std::to_string(rank));
     }
     if (m_Parameters.m_Size.size() != rank)
     {
         throw InvalidArgumentException(descriptorName +
             ": Length of size descriptor must equal rank " + std::to_string(rank));
     }
     // Check if the shape of the output tensor matches m_Size
     const TensorShape& outputShape = outputTensorInfo.GetShape();
     for (unsigned int i = 0u; i < rank; ++i)
     {
         if (m_Parameters.m_Size[i] != outputShape[i])
         {
             throw InvalidArgumentException(descriptorName + ": Size descriptor does not match output tensor.");
         }
     }
     // Check if the sum of begin offset and size in a given dimension
     // does not exceed the size of corresponding input
     const TensorShape& inputShape  = inputTensorInfo.GetShape();
     for(unsigned int i = 0u; i < rank; ++i)
     {
         if (m_Parameters.m_Begin[i] + m_Parameters.m_Size[i] > inputShape[i])
         {
             throw InvalidArgumentException(descriptorName + ": Sum of begin offset and size for dimension " +
                 std::to_string(i) + " exceeds input size.");
         }
     }
 }
References TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), SliceDescriptor::m_Begin, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< SliceDescriptor >::m_Parameters, SliceDescriptor::m_Size, and QueueDescriptor::ValidateTensorNumDimensions().
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp