Arm NN: StringifyLayerParameters< LayerParameter > Struct Template Reference
StringifyLayerParameters< LayerParameter > Struct Template Reference
StringifyLayerParameters allows serializing layer parameters to string.
#include <SerializeLayerParameters.hpp>
Static Public Member Functions
static void Serialize (ParameterStringifyFunction &, const LayerParameter &)
Detailed Description
template<typename LayerParameter>
struct armnn::StringifyLayerParameters< LayerParameter >
StringifyLayerParameters allows serializing layer parameters to string.
The default implementation is a no-op because this operation is considered non-vital for ArmNN and thus we allow adding new layer parameters without supplying the corresponding stringify functionality.
Definition at line 23 of file SerializeLayerParameters.hpp.
Member Function Documentation
Serialize()
static void Serialize (ParameterStringifyFunction & , const LayerParameter &) inline static
Definition at line 25 of file SerializeLayerParameters.hpp.
 {}
Referenced by ProfilingDetails::AddDetailsToString(), StringifyLayerParameters< ViewsDescriptor >::Serialize(), LayerWithParameters< StridedSliceDescriptor >::SerializeLayerParameters(), and Layer::SerializeLayerParameters().
The documentation for this struct was generated from the following file:
src/armnn/SerializeLayerParameters.hpp