Arm NN: BroadcastLoop Struct Reference
BroadcastLoop Struct Reference
#include <Broadcast.hpp>
Public Member Functions
BroadcastLoop (const TensorShape &inShape0, const TensorShape &inShape1, const TensorShape &outShape)
BroadcastLoop (const TensorShape &inShape, const TensorShape &outShape)
unsigned int GetNumDimensions ()
template<typename Func , typename DecoderOp , typename EncoderOp >
void Unroll (Func operationFunc, unsigned int dimension, DecoderOp &inData0, DecoderOp &inData1, EncoderOp &outData)
template<typename Func , typename DecoderOp , typename EncoderOp >
void Unroll (Func operationFunc, unsigned int dimension, DecoderOp &inData, EncoderOp &outData)
Detailed Description
Definition at line 14 of file Broadcast.hpp.
Constructor & Destructor Documentation
BroadcastLoop() [1/2]
BroadcastLoop (const TensorShape & inShape0, const TensorShape & inShape1, const TensorShape & outShape)
Definition at line 11 of file Broadcast.cpp.
 : m_DimData(outShape.GetNumDimensions())
 {
     const unsigned int numDims = GetNumDimensions();
     unsigned int sIn0 = 1;
     unsigned int sIn1 = 1;
     unsigned int sOut = 1;
     for (unsigned int j = numDims - 1, k = 0; k < numDims ; k++, j--)
     {
         m_DimData[j].m_DimSize = outShape[j];
         m_DimData[j].m_Stride1 = (inShape0[j] > 1) ? sIn0 : 0;
         m_DimData[j].m_Stride2 = (inShape1[j] > 1) ? sIn1 : 0;
         m_DimData[j].m_StrideOut = sOut;
         sIn0 *= inShape0[j];
         sIn1 *= inShape1[j];
         sOut *= outShape[j];
     }
 }
References BroadcastLoop::GetNumDimensions().
BroadcastLoop() [2/2]
BroadcastLoop (const TensorShape & inShape, const TensorShape & outShape)
Definition at line 33 of file Broadcast.cpp.
 : m_DimData(outShape.GetNumDimensions())
 {
     const unsigned int numDims = GetNumDimensions();
     unsigned int sIn = 1;
     unsigned int sOut = 1;
     // Get the difference between the output dimension and input dimension
     const unsigned int dimDifference = numDims - inShape.GetNumDimensions();
     for (unsigned int j = numDims - 1, k = 0; k < numDims ; k++, j--)
     {
         m_DimData[j].m_DimSize = outShape[j];
         // Pretend there are extra 1-dimensional tensors prepended
         if (dimDifference > 0 && j < dimDifference)
         {
             m_DimData[j].m_Stride1 = 0;
             sIn *= 1;
         }
         else if (dimDifference > 0)
         {
             m_DimData[j].m_Stride1 = (inShape[j - dimDifference] > 1) ? sIn : 0;
             sIn *= inShape[j - dimDifference];
         }
         else
         {
             m_DimData[j].m_Stride1 = (inShape[j] > 1) ? sIn : 0;
             sIn *= inShape[j];
         }
         m_DimData[j].m_StrideOut = sOut;
         sOut *= outShape[j];
     }
 }
References BroadcastLoop::GetNumDimensions(), and TensorShape::GetNumDimensions().
Member Function Documentation
GetNumDimensions()
unsigned int GetNumDimensions () inline
Definition at line 20 of file Broadcast.hpp.
     {
         return static_cast<unsigned int>(m_DimData.size());
     }
Referenced by BroadcastLoop::BroadcastLoop(), and BroadcastLoop::Unroll().
Unroll() [1/2]
void Unroll (Func operationFunc, unsigned int dimension, DecoderOp & inData, EncoderOp & outData) inline
Definition at line 62 of file Broadcast.hpp.
     {
         if (dimension >= GetNumDimensions())
         {
             outData.Set(operationFunc(inData.Get()));
             return;
         }
         unsigned int inDataMovement = 0;
         unsigned int outDataMovement = 0;
         for (unsigned int i = 0; i < m_DimData[dimension].m_DimSize; i++)
         {
             Unroll(operationFunc, dimension + 1, inData, outData);
             inData += m_DimData[dimension].m_Stride1;
             outData += m_DimData[dimension].m_StrideOut;
             inDataMovement += m_DimData[dimension].m_Stride1;
             outDataMovement += m_DimData[dimension].m_StrideOut;
         }
         // move iterator back to the start
         inData -= inDataMovement;
         outData -= outDataMovement;
     }
References BroadcastLoop::GetNumDimensions(), and BroadcastLoop::Unroll().
Unroll() [2/2]
void Unroll (Func operationFunc, unsigned int dimension, DecoderOp & inData0, DecoderOp & inData1, EncoderOp & outData) inline
Definition at line 26 of file Broadcast.hpp.
     {
         if (dimension >= GetNumDimensions())
         {
             outData.Set(operationFunc(inData0.Get(), inData1.Get()));
             return;
         }
         unsigned int inData0Movement = 0;
         unsigned int inData1Movement = 0;
         unsigned int outDataMovement = 0;
         for (unsigned int i = 0; i < m_DimData[dimension].m_DimSize; i++)
         {
             Unroll(operationFunc, dimension + 1, inData0, inData1, outData);
             inData0 += m_DimData[dimension].m_Stride1;
             inData1 += m_DimData[dimension].m_Stride2;
             outData += m_DimData[dimension].m_StrideOut;
             inData0Movement += m_DimData[dimension].m_Stride1;
             inData1Movement += m_DimData[dimension].m_Stride2;
             outDataMovement += m_DimData[dimension].m_StrideOut;
         }
         // move iterator back to the start
         inData0 -= inData0Movement;
         inData1 -= inData1Movement;
         outData -= outDataMovement;
     }
References BroadcastLoop::GetNumDimensions().
Referenced by ElementwiseBinaryFunction< Functor >::ElementwiseBinaryFunction(), ElementwiseUnaryFunction< Functor >::ElementwiseUnaryFunction(), LogicalBinaryFunction< Functor >::LogicalBinaryFunction(), LogicalUnaryFunction< Functor >::LogicalUnaryFunction(), armnn::PreluImpl(), and BroadcastLoop::Unroll().
The documentation for this struct was generated from the following files:
src/backends/reference/workloads/Broadcast.hpp
src/backends/reference/workloads/Broadcast.cpp