Arm NN: ArgMinMaxQueueDescriptor Struct Reference
ArgMinMaxQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< ArgMinMaxDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Additional Inherited Members
Public Attributes inherited from QueueDescriptorWithParameters< ArgMinMaxDescriptor >
ArgMinMaxDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions inherited from QueueDescriptorWithParameters< ArgMinMaxDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 163 of file WorkloadData.hpp.
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 629 of file WorkloadData.cpp.
 {
     const std::string descriptorName{"ArgMinMaxQueueDescriptor"};
     ValidateNumInputs(workloadInfo,  descriptorName, 1);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     if (outputTensorInfo.GetDataType() != DataType::Signed32 &&
         outputTensorInfo.GetDataType() != DataType::Signed64)
     {
         throw InvalidArgumentException(descriptorName + ": Output of ArgMinMax layer must be Int32 or Int64.");
     }
     std::vector<DataType> supportedInputTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32,
         DataType::Signed64
     };
     ValidateDataTypes(inputTensorInfo, supportedInputTypes, descriptorName);
     auto inputShape = inputTensorInfo.GetShape();
     auto outputShape = outputTensorInfo.GetShape();
     auto inputNumDimensions = inputShape.GetNumDimensions();
     auto unsignedAxis = armnnUtils::GetUnsignedAxis(inputNumDimensions, m_Parameters.m_Axis);
     const std::string outputShapeError{": Output tensor shape does not match shape inferred from input tensor."};
     // 1D input shape results in scalar output shape
     if (inputShape.GetNumDimensions() == 1)
     {
         if (outputShape.GetNumDimensions() != 1 && outputShape[0] != 1)
         {
             throw InvalidArgumentException(descriptorName + outputShapeError);
         }
     }
     else
     {
         for (unsigned int i = 0; i < unsignedAxis; ++i)
         {
             if (outputShape[i] != inputShape[i])
             {
                 throw InvalidArgumentException(descriptorName + outputShapeError);
             }
         }
         for (auto i = unsignedAxis + 1; i < inputNumDimensions; ++i)
         {
             if (outputShape[i - 1] != inputShape[i])
             {
                 throw InvalidArgumentException(descriptorName + outputShapeError);
             }
         }
     }
 }
References armnn::BFloat16, armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), TensorShape::GetNumDimensions(), TensorInfo::GetShape(), armnnUtils::GetUnsignedAxis(), ArgMinMaxDescriptor::m_Axis, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< ArgMinMaxDescriptor >::m_Parameters, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::Signed32, and armnn::Signed64.
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp