var _convert_const_dequantisation_layers_to_const_layers_8hpp =
[
    [ "ConvertConstDequantisationLayersToConstLayersImpl", "classarmnn_1_1optimizations_1_1_convert_const_dequantisation_layers_to_const_layers_impl.html", "classarmnn_1_1optimizations_1_1_convert_const_dequantisation_layers_to_const_layers_impl" ],
    [ "ConvertConstDequantisationLayersToConstLayers", "_convert_const_dequantisation_layers_to_const_layers_8hpp.html#a4625d132ba3ba9015de618fbc658b194", null ]
];