var _turbo_convert_const_dequantisation_layers_to_const_layers_8hpp =
[
    [ "TurboConvertConstDequantisationLayersToConstLayersImpl", "classarmnn_1_1optimizations_1_1_turbo_convert_const_dequantisation_layers_to_const_layers_impl.html", "classarmnn_1_1optimizations_1_1_turbo_convert_const_dequantisation_layers_to_const_layers_impl" ],
    [ "TurboConvertConstDequantisationLayersToConstLayers", "_turbo_convert_const_dequantisation_layers_to_const_layers_8hpp.html#a752aec0b27ea8647f645306a9aec0fbe", null ]
];