Arm NN: NeonTensorHandleFactory Class Reference
NeonTensorHandleFactory Class Reference
#include <NeonTensorHandleFactory.hpp>
Public Member Functions
NeonTensorHandleFactory (std::weak_ptr< NeonMemoryManager > mgr)
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, const TensorShape &subTensorShape, const unsigned int *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const override
Utility Functions for backends which require TensorHandles to have unmanaged memory.
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
const FactoryId & GetId () const override
bool SupportsInPlaceComputation () const override
bool SupportsSubTensors () const override
MemorySourceFlags GetExportFlags () const override
MemorySourceFlags GetImportFlags () const override
std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass) override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual bool SupportsMapUnmap () const
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Detailed Description
Definition at line 34 of file NeonTensorHandleFactory.hpp.
Constructor & Destructor Documentation
NeonTensorHandleFactory()
NeonTensorHandleFactory (std::weak_ptr< NeonMemoryManager > mgr) inline
Definition at line 37 of file NeonTensorHandleFactory.hpp.
                            : m_MemoryManager(mgr),
                              m_ImportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc)),
                              m_ExportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc))
    {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, const TensorShape & subTensorShape, const unsigned int * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 20 of file NeonTensorHandleFactory.cpp.
{
    const arm_compute::TensorShape shape = armcomputetensorutils::BuildArmComputeTensorShape(subTensorShape);
    arm_compute::Coordinates coords;
    coords.set_num_dimensions(subTensorShape.GetNumDimensions());
    for (unsigned int i = 0; i < subTensorShape.GetNumDimensions(); ++i)
    {
        // Arm compute indexes tensor coords in reverse order.
        unsigned int revertedIndex = subTensorShape.GetNumDimensions() - i - 1;
        coords.set(i, armnn::numeric_cast<int>(subTensorOrigin[revertedIndex]));
    }
    const arm_compute::TensorShape parentShape = armcomputetensorutils::BuildArmComputeTensorShape(parent.GetShape());
    if (!::arm_compute::error_on_invalid_subtensor(__func__, __FILE__, __LINE__, parentShape, coords, shape))
    {
        return nullptr;
    }
    return std::make_unique<NeonSubTensorHandle>(
            PolymorphicDowncast<IAclTensorHandle*>(&parent), shape, coords);
}
References TensorShape::GetNumDimensions(), and ITensorHandle::GetShape().
CreateTensorHandle() [1/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 47 of file NeonTensorHandleFactory.cpp.
{
    return NeonTensorHandleFactory::CreateTensorHandle(tensorInfo, true);
}
References NeonTensorHandleFactory::CreateTensorHandle().
Referenced by NeonTensorHandleFactory::CreateTensorHandle(), and NeonTensorHandleFactory::CreateTensorHandle().
CreateTensorHandle() [2/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged) const override virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented from ITensorHandleFactory.
Definition at line 58 of file NeonTensorHandleFactory.cpp.
{
    auto tensorHandle = std::make_unique<NeonTensorHandle>(tensorInfo);
    if (IsMemoryManaged)
    {
        tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
    }
    // If we are not Managing the Memory then we must be importing
    tensorHandle->SetImportEnabledFlag(!IsMemoryManaged);
    tensorHandle->SetImportFlags(GetImportFlags());
    return tensorHandle;
}
References NeonTensorHandleFactory::GetImportFlags().
CreateTensorHandle() [3/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 52 of file NeonTensorHandleFactory.cpp.
{
    return NeonTensorHandleFactory::CreateTensorHandle(tensorInfo, dataLayout, true);
}
References NeonTensorHandleFactory::CreateTensorHandle().
CreateTensorHandle() [4/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 73 of file NeonTensorHandleFactory.cpp.
{
    auto tensorHandle = std::make_unique<NeonTensorHandle>(tensorInfo, dataLayout);
    if (IsMemoryManaged)
    {
        tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
    }
    // If we are not Managing the Memory then we must be importing
    tensorHandle->SetImportEnabledFlag(!IsMemoryManaged);
    tensorHandle->SetImportFlags(GetImportFlags());
    return tensorHandle;
}
References NeonTensorHandleFactory::GetImportFlags().
GetCapabilities()
std::vector< Capability > GetCapabilities (const IConnectableLayer * layer, const IConnectableLayer * connectedLayer, CapabilityClass capabilityClass) override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 120 of file NeonTensorHandleFactory.cpp.
{
    IgnoreUnused(connectedLayer);
    std::vector<Capability> capabilities;
    if (capabilityClass == CapabilityClass::PaddingRequired)
    {
        auto search = paddingRequiredLayers.find((PolymorphicDowncast<const Layer*>(layer))->GetType());
        if ( search != paddingRequiredLayers.end())
        {
            Capability paddingCapability(CapabilityClass::PaddingRequired, true);
            capabilities.push_back(paddingCapability);
        }
    }
    return capabilities;
}
References armnn::IgnoreUnused(), armnn::PaddingRequired, and armnn::paddingRequiredLayers.
GetExportFlags()
MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 110 of file NeonTensorHandleFactory.cpp.
{
    return m_ExportFlags;
}
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 95 of file NeonTensorHandleFactory.cpp.
{
    return GetIdStatic();
}
References NeonTensorHandleFactory::GetIdStatic().
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 89 of file NeonTensorHandleFactory.cpp.
{
    static const FactoryId s_Id(NeonTensorHandleFactoryId());
    return s_Id;
}
References armnn::NeonTensorHandleFactoryId().
Referenced by NeonBackend::GetHandleFactoryPreferences(), and NeonTensorHandleFactory::GetId().
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 115 of file NeonTensorHandleFactory.cpp.
{
    return m_ImportFlags;
}
Referenced by NeonTensorHandleFactory::CreateTensorHandle(), and NeonTensorHandleFactory::CreateTensorHandle().
SupportsInPlaceComputation()
bool SupportsInPlaceComputation () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 100 of file NeonTensorHandleFactory.cpp.
{
    return true;
}
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 105 of file NeonTensorHandleFactory.cpp.
{
    return false;
}
The documentation for this class was generated from the following files:
src/backends/neon/NeonTensorHandleFactory.hpp
src/backends/neon/NeonTensorHandleFactory.cpp