Arm NN: OptimizeInversePermutesImpl< PermuteType > Class Template Reference
OptimizeInversePermutesImpl< PermuteType > Class Template Reference
#include <OptimizeInversePermutes.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Run for every connection between a base PermuteLayer and a child PermuteLayer.
Protected Member Functions
OptimizeInversePermutesImpl ()=default
~OptimizeInversePermutesImpl ()=default
Detailed Description
template<typename PermuteType>
class armnn::optimizations::OptimizeInversePermutesImpl< PermuteType >
Definition at line 18 of file OptimizeInversePermutes.hpp.
Constructor & Destructor Documentation
OptimizeInversePermutesImpl()
template<typename PermuteType > OptimizeInversePermutesImpl () protected default
~OptimizeInversePermutesImpl()
template<typename PermuteType > ~OptimizeInversePermutesImpl () protected default
Member Function Documentation
Run()
template<typename PermuteType > void Run (Graph & graph, InputSlot & connection) const inline
Run for every connection between a base PermuteLayer and a child PermuteLayer.
Bypasses both layers for that connection if one is the inverse of the other.
Definition at line 23 of file OptimizeInversePermutes.hpp.
    {
        IgnoreUnused(graph);
        Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
        auto child = PolymorphicDowncast<PermuteType*>(&connection.GetOwningLayer());
        if (child->IsInverse(*PolymorphicDowncast<PermuteType*>(&base)))
        {
            // Bypass both layers. Child will be removed as it's left unconnected.
            // Base layer will be removed if left unconnected.
            child->GetOutputSlot().MoveAllConnections(*base.GetInputSlot(0).GetConnectedOutputSlot());
        }
    }
References InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), and armnn::IgnoreUnused().
The documentation for this class was generated from the following file:
src/armnn/optimizations/OptimizeInversePermutes.hpp