Arm NN: UnidirectionalSequenceLstmLayer Class Reference
UnidirectionalSequenceLstmLayer Class Reference
This layer represents a LSTM operation.
#include <UnidirectionalSequenceLstmLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the UnidirectionalSequence LSTM type.
UnidirectionalSequenceLstmLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of UnidirectionalSequenceLstmLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Public Member Functions inherited from LayerWithParameters< LstmDescriptor >
const LstmDescriptor & GetParameters () const override
If the layer has a descriptor return it.
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id) override
Set the backend of the IConnectableLayer.
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer * >::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T >
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
Public Attributes
LstmBasicParameters m_BasicParameters
LstmOptCifgParameters m_CifgParameters
LstmOptProjectionParameters m_ProjectionParameters
LstmOptPeepholeParameters m_PeepholeParameters
LstmOptLayerNormParameters m_LayerNormParameters
Protected Member Functions
UnidirectionalSequenceLstmLayer (const LstmDescriptor &param, const char *name)
Constructor to create a UnidirectionalSequenceLstmLayer.
~UnidirectionalSequenceLstmLayer ()=default
Default destructor.
Layer::ImmutableConstantTensors GetConstantTensorsByRef () const override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from LayerWithParameters< LstmDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const LstmDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
Layer::ImmutableConstantTensors GetConnectedConstantAsInputTensors () const
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef () override final
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< LstmDescriptor >
using DescriptorType
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector<std::reference_wrapper<std::shared_ptr<ConstTensorHandle>>>
using ImmutableConstantTensors = std::vector<std::reference_wrapper<const std::shared_ptr<ConstTensorHandle>>>
Protected Attributes inherited from LayerWithParameters< LstmDescriptor >
LstmDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a LSTM operation.
Definition at line 16 of file UnidirectionalSequenceLstmLayer.hpp.
Constructor & Destructor Documentation
UnidirectionalSequenceLstmLayer()
UnidirectionalSequenceLstmLayer (const LstmDescriptor & param, const char * name) protected
Constructor to create a UnidirectionalSequenceLstmLayer.
Parameters
[in] param LstmDescriptor to configure the lstm operation.
[in] name Optional name for the layer.
Definition at line 17 of file UnidirectionalSequenceLstmLayer.cpp.
        : LayerWithParameters(3, 3, LayerType::UnidirectionalSequenceLstm, param, name)
{
}
~UnidirectionalSequenceLstmLayer()
~UnidirectionalSequenceLstmLayer () protected default
Default destructor.
Member Function Documentation
Clone()
UnidirectionalSequenceLstmLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 80 of file UnidirectionalSequenceLstmLayer.cpp.
{
    auto layer = CloneBase<UnidirectionalSequenceLstmLayer>(graph, m_Param, GetName());
    layer->m_BasicParameters.m_InputToForgetWeights = m_BasicParameters.m_InputToForgetWeights ?
            m_BasicParameters.m_InputToForgetWeights
                : nullptr;
    layer->m_BasicParameters.m_InputToCellWeights = m_BasicParameters.m_InputToCellWeights ?
            m_BasicParameters.m_InputToCellWeights : nullptr;
    layer->m_BasicParameters.m_InputToOutputWeights = m_BasicParameters.m_InputToOutputWeights ?
            m_BasicParameters.m_InputToOutputWeights : nullptr;
    layer->m_BasicParameters.m_RecurrentToForgetWeights = m_BasicParameters.m_RecurrentToForgetWeights ?
            m_BasicParameters.m_RecurrentToForgetWeights : nullptr;
    layer->m_BasicParameters.m_RecurrentToCellWeights = m_BasicParameters.m_RecurrentToCellWeights ?
            m_BasicParameters.m_RecurrentToCellWeights : nullptr;
    layer->m_BasicParameters.m_RecurrentToOutputWeights = m_BasicParameters.m_RecurrentToOutputWeights ?
            m_BasicParameters.m_RecurrentToOutputWeights : nullptr;
    layer->m_BasicParameters.m_ForgetGateBias = m_BasicParameters.m_ForgetGateBias ?
            m_BasicParameters.m_ForgetGateBias : nullptr;
    layer->m_BasicParameters.m_CellBias = m_BasicParameters.m_CellBias ?
            m_BasicParameters.m_CellBias : nullptr;
    layer->m_BasicParameters.m_OutputGateBias = m_BasicParameters.m_OutputGateBias ?
            m_BasicParameters.m_OutputGateBias : nullptr;
    if (!m_Param.m_CifgEnabled)
    {
        layer->m_CifgParameters.m_InputToInputWeights = m_CifgParameters.m_InputToInputWeights ?
                m_CifgParameters.m_InputToInputWeights : nullptr;
        layer->m_CifgParameters.m_RecurrentToInputWeights = m_CifgParameters.m_RecurrentToInputWeights ?
                m_CifgParameters.m_RecurrentToInputWeights : nullptr;
        layer->m_CifgParameters.m_InputGateBias = m_CifgParameters.m_InputGateBias ?
                m_CifgParameters.m_InputGateBias : nullptr;
    }
    if (m_Param.m_ProjectionEnabled)
    {
        layer->m_ProjectionParameters.m_ProjectionWeights = m_ProjectionParameters.m_ProjectionWeights ?
               m_ProjectionParameters.m_ProjectionWeights : nullptr;
        layer->m_ProjectionParameters.m_ProjectionBias = m_ProjectionParameters.m_ProjectionBias ?
               m_ProjectionParameters.m_ProjectionBias : nullptr;
    }
    if (m_Param.m_PeepholeEnabled)
    {
        if (!m_Param.m_CifgEnabled)
        {
            layer->m_PeepholeParameters.m_CellToInputWeights = m_PeepholeParameters.m_CellToInputWeights ?
                m_PeepholeParameters.m_CellToInputWeights : nullptr;
        }
        layer->m_PeepholeParameters.m_CellToForgetWeights = m_PeepholeParameters.m_CellToForgetWeights ?
               m_PeepholeParameters.m_CellToForgetWeights : nullptr;
        layer->m_PeepholeParameters.m_CellToOutputWeights = m_PeepholeParameters.m_CellToOutputWeights ?
               m_PeepholeParameters.m_CellToOutputWeights : nullptr;
    }
    if (m_Param.m_LayerNormEnabled)
    {
        layer->m_LayerNormParameters.m_InputLayerNormWeights = m_LayerNormParameters.m_InputLayerNormWeights ?
               m_LayerNormParameters.m_InputLayerNormWeights : nullptr;
        layer->m_LayerNormParameters.m_ForgetLayerNormWeights = m_LayerNormParameters.m_ForgetLayerNormWeights ?
               m_LayerNormParameters.m_ForgetLayerNormWeights : nullptr;
        layer->m_LayerNormParameters.m_CellLayerNormWeights = m_LayerNormParameters.m_CellLayerNormWeights ?
               m_LayerNormParameters.m_CellLayerNormWeights : nullptr;
        layer->m_LayerNormParameters.m_OutputLayerNormWeights = m_LayerNormParameters.m_OutputLayerNormWeights ?
               m_LayerNormParameters.m_OutputLayerNormWeights : nullptr;
    }
    return std::move(layer);
}
References Layer::GetName(), UnidirectionalSequenceLstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, UnidirectionalSequenceLstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, UnidirectionalSequenceLstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LayerWithParameters< LstmDescriptor >::m_Param, LstmDescriptor::m_PeepholeEnabled, UnidirectionalSequenceLstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, UnidirectionalSequenceLstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, and LstmBasicParameters::m_RecurrentToOutputWeights.
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the UnidirectionalSequence LSTM type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 22 of file UnidirectionalSequenceLstmLayer.cpp.
{
    UnidirectionalSequenceLstmQueueDescriptor descriptor;
    // Basic parameters
    descriptor.m_InputToForgetWeights = m_BasicParameters.m_InputToForgetWeights.get();
    descriptor.m_InputToCellWeights = m_BasicParameters.m_InputToCellWeights.get();
    descriptor.m_InputToOutputWeights = m_BasicParameters.m_InputToOutputWeights.get();
    descriptor.m_RecurrentToForgetWeights = m_BasicParameters.m_RecurrentToForgetWeights.get();
    descriptor.m_RecurrentToCellWeights = m_BasicParameters.m_RecurrentToCellWeights.get();
    descriptor.m_RecurrentToOutputWeights = m_BasicParameters.m_RecurrentToOutputWeights.get();
    descriptor.m_ForgetGateBias = m_BasicParameters.m_ForgetGateBias.get();
    descriptor.m_CellBias = m_BasicParameters.m_CellBias.get();
    descriptor.m_OutputGateBias = m_BasicParameters.m_OutputGateBias.get();
    // Cifg parameters
    if (!m_Param.m_CifgEnabled)
    {
        descriptor.m_InputToInputWeights = m_CifgParameters.m_InputToInputWeights.get();
        descriptor.m_RecurrentToInputWeights = m_CifgParameters.m_RecurrentToInputWeights.get();
        descriptor.m_InputGateBias = m_CifgParameters.m_InputGateBias.get();
    }
    // Projection parameters
    if (m_Param.m_ProjectionEnabled)
    {
        descriptor.m_ProjectionWeights = m_ProjectionParameters.m_ProjectionWeights.get();
        descriptor.m_ProjectionBias    = m_ProjectionParameters.m_ProjectionBias.get();
    }
    // Peephole parameters
    if (m_Param.m_PeepholeEnabled)
    {
        if (!m_Param.m_CifgEnabled)
        {
            descriptor.m_CellToInputWeights = m_PeepholeParameters.m_CellToInputWeights.get();
        }
        descriptor.m_CellToForgetWeights = m_PeepholeParameters.m_CellToForgetWeights.get();
        descriptor.m_CellToOutputWeights = m_PeepholeParameters.m_CellToOutputWeights.get();
    }
    // Layer normalisation parameters
    if(m_Param.m_LayerNormEnabled)
    {
        if (!m_Param.m_CifgEnabled)
        {
            descriptor.m_InputLayerNormWeights = m_LayerNormParameters.m_InputLayerNormWeights.get();
        }
        descriptor.m_ForgetLayerNormWeights = m_LayerNormParameters.m_ForgetLayerNormWeights.get();
        descriptor.m_CellLayerNormWeights = m_LayerNormParameters.m_CellLayerNormWeights.get();
        descriptor.m_OutputLayerNormWeights = m_LayerNormParameters.m_OutputLayerNormWeights.get();
    }
    SetAdditionalInfo(descriptor);
    return factory.CreateWorkload(LayerType::UnidirectionalSequenceLstm, descriptor, PrepInfoAndDesc(descriptor));
}
References IWorkloadFactory::CreateWorkload(), UnidirectionalSequenceLstmLayer::m_BasicParameters, UnidirectionalSequenceLstmQueueDescriptor::m_CellBias, LstmBasicParameters::m_CellBias, UnidirectionalSequenceLstmQueueDescriptor::m_CellLayerNormWeights, LstmOptLayerNormParameters::m_CellLayerNormWeights, UnidirectionalSequenceLstmQueueDescriptor::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, UnidirectionalSequenceLstmQueueDescriptor::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToInputWeights, UnidirectionalSequenceLstmQueueDescriptor::m_CellToOutputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, UnidirectionalSequenceLstmLayer::m_CifgParameters, UnidirectionalSequenceLstmQueueDescriptor::m_ForgetGateBias, LstmBasicParameters::m_ForgetGateBias, UnidirectionalSequenceLstmQueueDescriptor::m_ForgetLayerNormWeights, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, UnidirectionalSequenceLstmQueueDescriptor::m_InputGateBias, LstmOptCifgParameters::m_InputGateBias, UnidirectionalSequenceLstmQueueDescriptor::m_InputLayerNormWeights, LstmOptLayerNormParameters::m_InputLayerNormWeights, UnidirectionalSequenceLstmQueueDescriptor::m_InputToCellWeights, LstmBasicParameters::m_InputToCellWeights, UnidirectionalSequenceLstmQueueDescriptor::m_InputToForgetWeights, LstmBasicParameters::m_InputToForgetWeights, UnidirectionalSequenceLstmQueueDescriptor::m_InputToInputWeights, LstmOptCifgParameters::m_InputToInputWeights, UnidirectionalSequenceLstmQueueDescriptor::m_InputToOutputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, UnidirectionalSequenceLstmLayer::m_LayerNormParameters, UnidirectionalSequenceLstmQueueDescriptor::m_OutputGateBias, LstmBasicParameters::m_OutputGateBias, UnidirectionalSequenceLstmQueueDescriptor::m_OutputLayerNormWeights, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LayerWithParameters< LstmDescriptor >::m_Param, LstmDescriptor::m_PeepholeEnabled, UnidirectionalSequenceLstmLayer::m_PeepholeParameters, UnidirectionalSequenceLstmQueueDescriptor::m_ProjectionBias, LstmOptProjectionParameters::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, UnidirectionalSequenceLstmLayer::m_ProjectionParameters, UnidirectionalSequenceLstmQueueDescriptor::m_ProjectionWeights, LstmOptProjectionParameters::m_ProjectionWeights, UnidirectionalSequenceLstmQueueDescriptor::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToCellWeights, UnidirectionalSequenceLstmQueueDescriptor::m_RecurrentToForgetWeights, LstmBasicParameters::m_RecurrentToForgetWeights, UnidirectionalSequenceLstmQueueDescriptor::m_RecurrentToInputWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, UnidirectionalSequenceLstmQueueDescriptor::m_RecurrentToOutputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, LayerWithParameters< LstmDescriptor >::PrepInfoAndDesc(), Layer::SetAdditionalInfo(), and armnn::UnidirectionalSequenceLstm.
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Reimplemented from LayerWithParameters< LstmDescriptor >.
Definition at line 397 of file UnidirectionalSequenceLstmLayer.cpp.
{
    std::vector<ConstTensor> constTensors;
    LstmDescriptor descriptor = GetParameters();
    ManagedConstTensorHandle managedInputToForgetWeights(m_BasicParameters.m_InputToForgetWeights);
    ManagedConstTensorHandle managedInputToCellWeights(m_BasicParameters.m_InputToCellWeights);
    ManagedConstTensorHandle managedInputToOutputWeights(m_BasicParameters.m_InputToOutputWeights);
    ManagedConstTensorHandle managedRecurrentToForgetWeights(m_BasicParameters.m_RecurrentToForgetWeights);
    ManagedConstTensorHandle managedRecurrentToCellWeights(m_BasicParameters.m_RecurrentToCellWeights);
    ManagedConstTensorHandle managedRecurrentToOutputWeights(m_BasicParameters.m_RecurrentToOutputWeights);
    ManagedConstTensorHandle managedForgetGateBias(m_BasicParameters.m_ForgetGateBias);
    ManagedConstTensorHandle managedCellBias(m_BasicParameters.m_CellBias);
    ManagedConstTensorHandle managedOutputGateBias(m_BasicParameters.m_OutputGateBias);
    // Cifg parameters
    ManagedConstTensorHandle managedInputToInputWeights(m_CifgParameters.m_InputToInputWeights);
    ManagedConstTensorHandle managedRecurrentToInputWeights(m_CifgParameters.m_RecurrentToInputWeights);
    ManagedConstTensorHandle managedInputGateBias(m_CifgParameters.m_InputGateBias);
    // Projection parameters
    ManagedConstTensorHandle managedProjectionWeights(m_ProjectionParameters.m_ProjectionWeights);
    ManagedConstTensorHandle managedProjectionBias(m_ProjectionParameters.m_ProjectionBias);
    // Peephole parameters
    ManagedConstTensorHandle managedCellToInputWeights(m_PeepholeParameters.m_CellToInputWeights);
    ManagedConstTensorHandle managedCellToForgetWeights(m_PeepholeParameters.m_CellToForgetWeights);
    ManagedConstTensorHandle managedCellToOutputWeights(m_PeepholeParameters.m_CellToOutputWeights);
    // Layer normalisation parameters
    ManagedConstTensorHandle managedInputLayerNormWeights(m_LayerNormParameters.m_InputLayerNormWeights);
    ManagedConstTensorHandle managedForgetLayerNormWeights(m_LayerNormParameters.m_ForgetLayerNormWeights);
    ManagedConstTensorHandle managedCellLayerNormWeights(m_LayerNormParameters.m_CellLayerNormWeights);
    ManagedConstTensorHandle managedOutputLayerNormWeights(m_LayerNormParameters.m_OutputLayerNormWeights);
    // First add mandatory/basic parameters
    if (m_BasicParameters.m_InputToForgetWeights != nullptr)
    {
        constTensors.emplace_back(ConstTensor(managedInputToForgetWeights.GetTensorInfo(),
                                              managedInputToForgetWeights.Map()));
    }
    if (m_BasicParameters.m_InputToCellWeights != nullptr)
    {
        constTensors.emplace_back(ConstTensor(managedInputToCellWeights.GetTensorInfo(),
                                              managedInputToCellWeights.Map()));
    }
    if (m_BasicParameters.m_InputToOutputWeights != nullptr)
    {
        constTensors.emplace_back(ConstTensor(managedInputToOutputWeights.GetTensorInfo(),
                                              managedInputToOutputWeights.Map()));
    }
    if (m_BasicParameters.m_RecurrentToForgetWeights != nullptr)
    {
        constTensors.emplace_back(ConstTensor(
                managedRecurrentToForgetWeights.GetTensorInfo(),
                managedRecurrentToForgetWeights.Map()));
    }
    if (m_BasicParameters.m_RecurrentToCellWeights != nullptr)
    {
        constTensors.emplace_back(ConstTensor(
                managedRecurrentToCellWeights.GetTensorInfo(),
                managedRecurrentToCellWeights.Map()));
    }
    if (m_BasicParameters.m_RecurrentToOutputWeights != nullptr)
    {
        constTensors.emplace_back(ConstTensor(
                managedRecurrentToOutputWeights.GetTensorInfo(),
                managedRecurrentToOutputWeights.Map()));
    }
    if (m_BasicParameters.m_ForgetGateBias != nullptr)
    {
        constTensors.emplace_back(ConstTensor(managedForgetGateBias.GetTensorInfo(),
                                              managedForgetGateBias.Map()));
    }
    if (m_BasicParameters.m_CellBias != nullptr)
    {
        constTensors.emplace_back(ConstTensor(managedCellBias.GetTensorInfo(),
                                              managedCellBias.Map()));
    }
    if (m_BasicParameters.m_OutputGateBias != nullptr)
    {
        constTensors.emplace_back(ConstTensor(managedOutputGateBias.GetTensorInfo(),
                                              managedOutputGateBias.Map()));
    }
    // Add cifg parameters
    if (!descriptor.m_CifgEnabled)
    {
        if (m_CifgParameters.m_InputToInputWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedInputToInputWeights.GetTensorInfo(),
                                                  managedInputToInputWeights.Map()));
        }
        if (m_CifgParameters.m_RecurrentToInputWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(
                    managedRecurrentToInputWeights.GetTensorInfo(),
                    managedRecurrentToInputWeights.Map()));
        }
        if (m_CifgParameters.m_InputGateBias != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedInputGateBias.GetTensorInfo(),
                                                  managedInputGateBias.Map()));
        }
    }
    // Add peephole parameters
    if (descriptor.m_PeepholeEnabled)
    {
        if (!descriptor.m_CifgEnabled)
        {
            if (m_PeepholeParameters.m_CellToInputWeights != nullptr)
            {
                constTensors.emplace_back(ConstTensor(managedCellToInputWeights.GetTensorInfo(),
                                                      managedCellToInputWeights.Map()));
            }
        }
        if (m_PeepholeParameters.m_CellToForgetWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedCellToForgetWeights.GetTensorInfo(),
                                                  managedCellToForgetWeights.Map()));
        }
        if (m_PeepholeParameters.m_CellToOutputWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedCellToOutputWeights.GetTensorInfo(),
                                                  managedCellToOutputWeights.Map()));
        }
    }
    // Add projection parameters
    if (descriptor.m_ProjectionEnabled)
    {
        if (m_ProjectionParameters.m_ProjectionWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedProjectionWeights.GetTensorInfo(),
                                                  managedProjectionWeights.Map()));
        }
        if (m_ProjectionParameters.m_ProjectionBias != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedProjectionBias.GetTensorInfo(),
                                                  managedProjectionBias.Map()));
        }
    }
    // Add norm parameters
    if (descriptor.m_LayerNormEnabled)
    {
        if (!descriptor.m_CifgEnabled)
        {
            if (m_LayerNormParameters.m_InputLayerNormWeights != nullptr)
            {
                constTensors.emplace_back(ConstTensor(managedInputLayerNormWeights.GetTensorInfo(),
                                                      managedInputLayerNormWeights.Map()));
            }
        }
        if (m_LayerNormParameters.m_ForgetLayerNormWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedForgetLayerNormWeights.GetTensorInfo(),
                                                  managedForgetLayerNormWeights.Map()));
        }
        if (m_LayerNormParameters.m_CellLayerNormWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedCellLayerNormWeights.GetTensorInfo(),
                                                  managedCellLayerNormWeights.Map()));
        }
        if (m_LayerNormParameters.m_OutputLayerNormWeights != nullptr)
        {
            constTensors.emplace_back(ConstTensor(managedOutputLayerNormWeights.GetTensorInfo(),
                                                  managedOutputLayerNormWeights.Map()));
        }
    }
    strategy.ExecuteStrategy(this, GetParameters(), constTensors, GetName());
}
References IStrategy::ExecuteStrategy(), Layer::GetName(), LayerWithParameters< LstmDescriptor >::GetParameters(), ManagedConstTensorHandle::GetTensorInfo(), UnidirectionalSequenceLstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, UnidirectionalSequenceLstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, UnidirectionalSequenceLstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LstmDescriptor::m_PeepholeEnabled, UnidirectionalSequenceLstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, UnidirectionalSequenceLstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, and ManagedConstTensorHandle::Map().
GetConstantTensorsByRef()
Layer::ImmutableConstantTensors GetConstantTensorsByRef () const override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 363 of file UnidirectionalSequenceLstmLayer.cpp.
{
    // For API stability DO NOT ALTER order and add new members to the end of vector
    return {m_BasicParameters.m_InputToForgetWeights,
            m_BasicParameters.m_InputToCellWeights,
            m_BasicParameters.m_InputToOutputWeights,
            m_BasicParameters.m_RecurrentToForgetWeights,
            m_BasicParameters.m_RecurrentToCellWeights,
            m_BasicParameters.m_RecurrentToOutputWeights,
            m_BasicParameters.m_ForgetGateBias,
            m_BasicParameters.m_CellBias,
            m_BasicParameters.m_OutputGateBias,
            // Cifg parameters
            m_CifgParameters.m_InputToInputWeights,
            m_CifgParameters.m_RecurrentToInputWeights,
            m_CifgParameters.m_InputGateBias,
            // Projection parameters
            m_ProjectionParameters.m_ProjectionWeights,
            m_ProjectionParameters.m_ProjectionBias,
            // Peephole parameters
            m_PeepholeParameters.m_CellToInputWeights,
            m_PeepholeParameters.m_CellToForgetWeights,
            m_PeepholeParameters.m_CellToOutputWeights,
            // Layer normalisation parameters
            m_LayerNormParameters.m_InputLayerNormWeights,
            m_LayerNormParameters.m_ForgetLayerNormWeights,
            m_LayerNormParameters.m_CellLayerNormWeights,
            m_LayerNormParameters.m_OutputLayerNormWeights};
}
References UnidirectionalSequenceLstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, UnidirectionalSequenceLstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, UnidirectionalSequenceLstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, UnidirectionalSequenceLstmLayer::m_PeepholeParameters, LstmOptProjectionParameters::m_ProjectionBias, UnidirectionalSequenceLstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, and LstmBasicParameters::m_RecurrentToOutputWeights.
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 150 of file UnidirectionalSequenceLstmLayer.cpp.
{
    ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(inputShapes.size() == 3,
                                        "inputShapes' size is \"" + std::to_string(inputShapes.size()) +
                                        "\" - should be \"3\".");
    // Get input values for validation
    unsigned int outputSize = inputShapes[1][1];
    std::vector<TensorShape> outShapes;
    if (m_Param.m_TimeMajor)
    {
        outShapes.push_back(TensorShape({inputShapes[0][0], inputShapes[0][1], outputSize}));
    }
    else
    {
        outShapes.push_back(TensorShape({inputShapes[0][0], inputShapes[0][1], outputSize}));
    }
    return outShapes;
}
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, LayerWithParameters< LstmDescriptor >::m_Param, and LstmDescriptor::m_TimeMajor.
Referenced by UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of UnidirectionalSequenceLstmLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 172 of file UnidirectionalSequenceLstmLayer.cpp.
{
    VerifyLayerConnections(3, CHECK_LOCATION());
    const TensorShape& outputShape = GetOutputSlot(2).GetTensorInfo().GetShape();
    VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
    auto inferredShapes = InferOutputShapes( {
        GetInputSlot(0).GetTensorInfo().GetShape(),
        GetInputSlot(1).GetTensorInfo().GetShape(),
        GetInputSlot(2).GetTensorInfo().GetShape()
    });
    if (inferredShapes.size() != 1)
    {
        throw armnn::LayerValidationException("inferredShapes has "
                                              + std::to_string(inferredShapes.size()) +
                                              " elements - should only have 1.");
    }
    // Check if the weights are nullptr
    if (!m_BasicParameters.m_InputToForgetWeights)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_InputToForgetWeights should not be null.");
    }
    if (!m_BasicParameters.m_InputToCellWeights)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_InputToCellWeights should not be null.");
    }
    if (!m_BasicParameters.m_InputToOutputWeights)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_InputToOutputWeights should not be null.");
    }
    if (!m_BasicParameters.m_RecurrentToForgetWeights)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_RecurrentToForgetWeights should not be null.");
    }
    if (!m_BasicParameters.m_RecurrentToCellWeights)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_RecurrentToCellWeights should not be null.");
    }
    if (!m_BasicParameters.m_RecurrentToOutputWeights)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_RecurrentToOutputWeights should not be null.");
    }
    if (!m_BasicParameters.m_ForgetGateBias)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_ForgetGateBias should not be null.");
    }
    if (!m_BasicParameters.m_CellBias)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_CellBias should not be null.");
    }
    if (!m_BasicParameters.m_OutputGateBias)
    {
        throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                              "m_BasicParameters.m_OutputGateBias should not be null.");
    }
    if (!m_Param.m_CifgEnabled)
    {
        if (!m_CifgParameters.m_InputToInputWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_CifgParameters.m_InputToInputWeights should not be null.");
        }
        if (!m_CifgParameters.m_RecurrentToInputWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_CifgParameters.m_RecurrentToInputWeights should not be null.");
        }
        if (!m_CifgParameters.m_InputGateBias)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_CifgParameters.m_InputGateBias should not be null.");
        }
    }
    else
    {
        if (m_CifgParameters.m_InputToInputWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_CifgParameters.m_InputToInputWeights should not have a value "
                                                  "when CIFG is enabled.");
        }
        if (m_CifgParameters.m_RecurrentToInputWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_CifgParameters.m_RecurrentToInputWeights should not have a value "
                                                  "when CIFG is enabled.");
        }
        if (m_CifgParameters.m_InputGateBias)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_CifgParameters.m_InputGateBias should not have a value "
                                                  "when CIFG is enabled.");
        }
    }
    if (m_Param.m_ProjectionEnabled)
    {
        if (!m_ProjectionParameters.m_ProjectionWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_ProjectionParameters.m_ProjectionWeights should not be null.");
        }
    }
    if (m_Param.m_PeepholeEnabled)
    {
        if (!m_Param.m_CifgEnabled)
        {
            if (!m_PeepholeParameters.m_CellToInputWeights)
            {
                throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                      "m_PeepholeParameters.m_CellToInputWeights should not be null "
                                                      "when Peephole is enabled and CIFG is disabled.");
            }
        }
        if (!m_PeepholeParameters.m_CellToForgetWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_PeepholeParameters.m_CellToForgetWeights should not be null.");
        }
        if (!m_PeepholeParameters.m_CellToOutputWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_PeepholeParameters.m_CellToOutputWeights should not be null.");
        }
    }
    if (m_Param.m_LayerNormEnabled)
    {
        if(!m_Param.m_CifgEnabled)
        {
            if (!m_LayerNormParameters.m_InputLayerNormWeights)
            {
                throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                      "m_LayerNormParameters.m_inputLayerNormWeights "
                                                      "should not be null.");
            }
        }
        if (!m_LayerNormParameters.m_ForgetLayerNormWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_LayerNormParameters.m_forgetLayerNormWeights "
                                                  "should not be null.");
        }
        if (!m_LayerNormParameters.m_CellLayerNormWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_LayerNormParameters.m_cellLayerNormWeights "
                                                  "should not be null.");
        }
        if (!m_LayerNormParameters.m_OutputLayerNormWeights)
        {
            throw armnn::LayerValidationException("UnidirectionalSequenceLstmLayer: "
                                                  "m_LayerNormParameters.m_outputLayerNormWeights "
                                                  "should not be null.");
        }
    }
    ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "UnidirectionalSequenceLstmLayer");
}
References CHECK_LOCATION, Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), InputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), UnidirectionalSequenceLstmLayer::InferOutputShapes(), UnidirectionalSequenceLstmLayer::m_BasicParameters, LstmBasicParameters::m_CellBias, LstmOptLayerNormParameters::m_CellLayerNormWeights, LstmOptPeepholeParameters::m_CellToForgetWeights, LstmOptPeepholeParameters::m_CellToInputWeights, LstmOptPeepholeParameters::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, UnidirectionalSequenceLstmLayer::m_CifgParameters, LstmBasicParameters::m_ForgetGateBias, LstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmOptCifgParameters::m_InputGateBias, LstmOptLayerNormParameters::m_InputLayerNormWeights, LstmBasicParameters::m_InputToCellWeights, LstmBasicParameters::m_InputToForgetWeights, LstmOptCifgParameters::m_InputToInputWeights, LstmBasicParameters::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, UnidirectionalSequenceLstmLayer::m_LayerNormParameters, LstmBasicParameters::m_OutputGateBias, LstmOptLayerNormParameters::m_OutputLayerNormWeights, LayerWithParameters< LstmDescriptor >::m_Param, LstmDescriptor::m_PeepholeEnabled, UnidirectionalSequenceLstmLayer::m_PeepholeParameters, LstmDescriptor::m_ProjectionEnabled, UnidirectionalSequenceLstmLayer::m_ProjectionParameters, LstmOptProjectionParameters::m_ProjectionWeights, LstmBasicParameters::m_RecurrentToCellWeights, LstmBasicParameters::m_RecurrentToForgetWeights, LstmOptCifgParameters::m_RecurrentToInputWeights, LstmBasicParameters::m_RecurrentToOutputWeights, Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
Member Data Documentation
m_BasicParameters
LstmBasicParameters m_BasicParameters
Definition at line 20 of file UnidirectionalSequenceLstmLayer.hpp.
Referenced by NetworkImpl::AddUnidirectionalSequenceLstmLayer(), UnidirectionalSequenceLstmLayer::Clone(), UnidirectionalSequenceLstmLayer::CreateWorkload(), UnidirectionalSequenceLstmLayer::ExecuteStrategy(), UnidirectionalSequenceLstmLayer::GetConstantTensorsByRef(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
m_CifgParameters
LstmOptCifgParameters m_CifgParameters
Definition at line 21 of file UnidirectionalSequenceLstmLayer.hpp.
Referenced by UnidirectionalSequenceLstmLayer::Clone(), UnidirectionalSequenceLstmLayer::CreateWorkload(), UnidirectionalSequenceLstmLayer::ExecuteStrategy(), UnidirectionalSequenceLstmLayer::GetConstantTensorsByRef(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
m_LayerNormParameters
LstmOptLayerNormParameters m_LayerNormParameters
Definition at line 24 of file UnidirectionalSequenceLstmLayer.hpp.
Referenced by UnidirectionalSequenceLstmLayer::Clone(), UnidirectionalSequenceLstmLayer::CreateWorkload(), UnidirectionalSequenceLstmLayer::ExecuteStrategy(), UnidirectionalSequenceLstmLayer::GetConstantTensorsByRef(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
m_PeepholeParameters
LstmOptPeepholeParameters m_PeepholeParameters
Definition at line 23 of file UnidirectionalSequenceLstmLayer.hpp.
Referenced by UnidirectionalSequenceLstmLayer::Clone(), UnidirectionalSequenceLstmLayer::CreateWorkload(), UnidirectionalSequenceLstmLayer::ExecuteStrategy(), UnidirectionalSequenceLstmLayer::GetConstantTensorsByRef(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
m_ProjectionParameters
LstmOptProjectionParameters m_ProjectionParameters
Definition at line 22 of file UnidirectionalSequenceLstmLayer.hpp.
Referenced by UnidirectionalSequenceLstmLayer::Clone(), UnidirectionalSequenceLstmLayer::CreateWorkload(), UnidirectionalSequenceLstmLayer::ExecuteStrategy(), UnidirectionalSequenceLstmLayer::GetConstantTensorsByRef(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/UnidirectionalSequenceLstmLayer.hpp
src/armnn/layers/UnidirectionalSequenceLstmLayer.cpp