Arm NN: RefMemoryManager Class Reference
RefMemoryManager Class Reference
#include <RefMemoryManager.hpp>
Classes
class Pool
Public Member Functions
RefMemoryManager ()
virtual ~RefMemoryManager ()
Pool * Manage (unsigned int numBytes)
void Allocate (Pool *pool)
void * GetPointer (Pool *pool)
void Acquire () override
void Release () override
Public Member Functions inherited from IMemoryManager
virtual ~IMemoryManager ()
Additional Inherited Members
Protected Member Functions inherited from IMemoryManager
IMemoryManager ()
Detailed Description
Definition at line 16 of file RefMemoryManager.hpp.
Constructor & Destructor Documentation
RefMemoryManager()
RefMemoryManager ()
Definition at line 14 of file RefMemoryManager.cpp.
{}
~RefMemoryManager()
~RefMemoryManager () virtual
Definition at line 17 of file RefMemoryManager.cpp.
{}
Member Function Documentation
Acquire()
void Acquire () override virtual
Implements IMemoryManager.
Definition at line 47 of file RefMemoryManager.cpp.
{
    for (Pool &pool: m_Pools)
    {
         pool.Acquire();
    }
}
Allocate()
void Allocate (RefMemoryManager::Pool * pool)
Definition at line 36 of file RefMemoryManager.cpp.
{
    ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(pool, "Null memory manager passed to RefMemoryManager.");
    m_FreePools.push_back(pool);
}
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE.
GetPointer()
void * GetPointer (RefMemoryManager::Pool * pool)
Definition at line 42 of file RefMemoryManager.cpp.
{
    return pool->GetPointer();
}
References RefMemoryManager::Pool::GetPointer().
Manage()
RefMemoryManager::Pool * Manage (unsigned int numBytes)
Definition at line 20 of file RefMemoryManager.cpp.
{
    if (!m_FreePools.empty())
    {
        Pool* res = m_FreePools.back();
        m_FreePools.pop_back();
        res->Reserve(numBytes);
        return res;
    }
    else
    {
        m_Pools.push_front(Pool(numBytes));
        return &m_Pools.front();
    }
}
References RefMemoryManager::Pool::Reserve().
Release()
void Release () override virtual
Implements IMemoryManager.
Definition at line 55 of file RefMemoryManager.cpp.
{
    for (Pool &pool: m_Pools)
    {
         pool.Release();
    }
}
Referenced by RefMemoryManager::Pool::~Pool().
The documentation for this class was generated from the following files:
src/backends/reference/RefMemoryManager.hpp
src/backends/reference/RefMemoryManager.cpp