Arm NN: OptionalReferenceSwitch< true, T > Class Template Reference
OptionalReferenceSwitch< true, T > Class Template Reference
This is the special case for reference types.
#include <Optional.hpp>
Public Types
using Base = OptionalBase
using NonRefT = typename std::remove_reference<T>::type
Public Member Functions
OptionalReferenceSwitch () noexcept
OptionalReferenceSwitch (EmptyOptional) noexcept
OptionalReferenceSwitch (const OptionalReferenceSwitch &other)
OptionalReferenceSwitch (T value)
template<class... Args>
OptionalReferenceSwitch (ConstructInPlace, Args &&... args)=delete
OptionalReferenceSwitch & operator= (const T value)
OptionalReferenceSwitch & operator= (const OptionalReferenceSwitch &other)
OptionalReferenceSwitch & operator= (EmptyOptional)
~OptionalReferenceSwitch ()
void reset ()
const T value () const
T value ()
Public Member Functions inherited from OptionalBase
OptionalBase () noexcept
bool has_value () const noexcept
operator bool () const noexcept
Conversion to bool, so can be used in if-statements and similar contexts expecting a bool.
Additional Inherited Members
Protected Member Functions inherited from OptionalBase
OptionalBase (bool hasValue) noexcept
Protected Attributes inherited from OptionalBase
bool m_HasValue
Detailed Description
template<typename T>
class armnn::OptionalReferenceSwitch< true, T >
This is the special case for reference types.
This holds a pointer to the referenced type. This doesn't own the referenced memory and it never calls delete on the pointer.
Definition at line 191 of file Optional.hpp.
Member Typedef Documentation
Base
template<typename T > using Base = OptionalBase
Definition at line 194 of file Optional.hpp.
NonRefT
template<typename T > using NonRefT = typename std::remove_reference<T>::type
Definition at line 195 of file Optional.hpp.
Constructor & Destructor Documentation
OptionalReferenceSwitch() [1/5]
template<typename T > OptionalReferenceSwitch () inline noexcept
Definition at line 197 of file Optional.hpp.
: Base{}, m_Storage{nullptr} {}
OptionalReferenceSwitch() [2/5]
template<typename T > OptionalReferenceSwitch (EmptyOptional) inline noexcept
Definition at line 198 of file Optional.hpp.
: Base{}, m_Storage{nullptr} {}
OptionalReferenceSwitch() [3/5]
template<typename T > OptionalReferenceSwitch (const OptionalReferenceSwitch< true, T > & other) inline
Definition at line 200 of file Optional.hpp.
                                                                  : Base{}
    {
        *this = other;
    }
OptionalReferenceSwitch() [4/5]
template<typename T > OptionalReferenceSwitch (T value) inline
Definition at line 205 of file Optional.hpp.
        : Base{true}
        , m_Storage{&value}
    {
    }
OptionalReferenceSwitch() [5/5]
template<typename T > template<class... Args> OptionalReferenceSwitch (ConstructInPlace , Args &&... args) delete
~OptionalReferenceSwitch()
template<typename T > ~OptionalReferenceSwitch () inline
Definition at line 234 of file Optional.hpp.
    {
        reset();
    }
References OptionalReferenceSwitch< IsReference, T >::reset().
Member Function Documentation
operator=() [1/3]
template<typename T > OptionalReferenceSwitch & operator= (const OptionalReferenceSwitch< true, T > & other) inline
Definition at line 221 of file Optional.hpp.
    {
        m_Storage = other.m_Storage;
        Base::m_HasValue = other.has_value();
        return *this;
    }
References OptionalBase::has_value(), and OptionalBase::m_HasValue.
operator=() [2/3]
template<typename T > OptionalReferenceSwitch & operator= (const T value) inline
Definition at line 214 of file Optional.hpp.
    {
        m_Storage = &value;
        Base::m_HasValue = true;
        return *this;
    }
References OptionalBase::m_HasValue, and OptionalReferenceSwitch< IsReference, T >::value().
operator=() [3/3]
template<typename T > OptionalReferenceSwitch & operator= (EmptyOptional) inline
Definition at line 228 of file Optional.hpp.
    {
        reset();
        return *this;
    }
References OptionalReferenceSwitch< IsReference, T >::reset().
reset()
template<typename T > void reset () inline
Definition at line 239 of file Optional.hpp.
    {
        Base::m_HasValue = false;
        m_Storage = nullptr;
    }
References OptionalBase::m_HasValue.
value() [1/2]
template<typename T > T value () inline
Definition at line 255 of file Optional.hpp.
    {
        if (!Base::has_value())
        {
            throw BadOptionalAccessException("Optional has no value");
        }
        return *m_Storage;
    }
References OptionalBase::has_value().
value() [2/2]
template<typename T > const T value () const inline
Definition at line 245 of file Optional.hpp.
    {
        if (!Base::has_value())
        {
            throw BadOptionalAccessException("Optional has no value");
        }
        return *m_Storage;
    }
References OptionalBase::has_value().
The documentation for this class was generated from the following file:
include/armnn/Optional.hpp