Arm NN: Optimizer Class Reference
Optimizer Class Reference
#include <Optimizer.hpp>
Public Types
using OptimizationPtr = std::unique_ptr<Optimization>
using Optimizations = std::vector<OptimizationPtr>
Static Public Member Functions
static void Pass (Graph &graph, const Optimizations &optimizations)
Detailed Description
Definition at line 14 of file Optimizer.hpp.
Member Typedef Documentation
OptimizationPtr
using OptimizationPtr = std::unique_ptr<Optimization>
Definition at line 17 of file Optimizer.hpp.
Optimizations
using Optimizations = std::vector<OptimizationPtr>
Definition at line 18 of file Optimizer.hpp.
Member Function Documentation
Pass()
void Pass (Graph & graph, const Optimizations & optimizations) static
Definition at line 16 of file Optimizer.cpp.
{
    ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "Optimizer_Pass");
    // Create observables to observe changes to the graph
    AddedLayerObservable addedLayerObservable(graph);
    ErasedLayerNamesObservable erasedLayerNamesObservable(graph);
    bool graphNeedsSorting = false;
    auto it = graph.TopologicalSort().end();
    // Calls TopologicalSort() for every iteration to re-order the list in case layers were added/removed.
    while (it != graph.TopologicalSort().begin())
    {
        --it;
        for (auto&& optimization : optimizations)
        {
            if (!*it)
            {
                throw armnn::NullPointerException("Layer must not be null.");
            }
            optimization->Run(graph, **it);
            if ((*it)->IsOutputUnconnected())
            {
                auto next = std::next(graph.GetPosInGraph(**it));
                graph.EraseLayer(it);
                it = next;
                graphNeedsSorting = true;
            }
            // Add the names of erased layers as related layers to the new added layers
            for (auto& erasedLayerName : erasedLayerNamesObservable)
            {
                for (auto& addedLayer : addedLayerObservable)
                {
                    addedLayer->AddRelatedLayerName(erasedLayerName);
                }
            }
            erasedLayerNamesObservable.Clear();
            addedLayerObservable.Clear();
            if (graphNeedsSorting)
            {
                graphNeedsSorting = false;
                break;
            }
        }
    }
}
References ARMNN_SCOPED_PROFILING_EVENT, Graph::begin(), GraphObservable< ObservedType >::Clear(), Graph::end(), Graph::EraseLayer(), Graph::GetPosInGraph(), Graph::TopologicalSort(), and armnn::Undefined.
Referenced by armnn::ApplyBackendOptimizations().
The documentation for this class was generated from the following files:
src/armnn/Optimizer.hpp
src/armnn/Optimizer.cpp