Arm NN: NeonConvolution2dWorkload Class Reference
NeonConvolution2dWorkload Class Reference
#include <NeonConvolution2dWorkload.hpp>
Public Member Functions
NeonConvolution2dWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager, const bool isFastMathENabled=false)
void Execute () const override
arm_compute::ConvolutionMethod GetConvolutionMethod () const
Public Member Functions inherited from NeonBaseWorkload< Convolution2dQueueDescriptor >
NeonBaseWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< QueueDescriptor >
BaseWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const QueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from NeonBaseWorkload< Convolution2dQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< QueueDescriptor >
QueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 27 of file NeonConvolution2dWorkload.hpp.
Constructor & Destructor Documentation
NeonConvolution2dWorkload()
NeonConvolution2dWorkload (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager, const bool isFastMathENabled = false)
Definition at line 71 of file NeonConvolution2dWorkload.cpp.
    : NeonBaseWorkload<Convolution2dQueueDescriptor>(descriptor, info)
{
    using arm_compute::NEConvolutionLayer;
    uint32_t numInputs = m_Data.m_Parameters.m_BiasEnabled ? 3: 2;
    m_Data.ValidateInputsOutputs("NeonConvolution2dWorkload", numInputs, 1);
    arm_compute::ITensor& input = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
    arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
    arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
    input.info()->set_data_layout(aclDataLayout);
    output.info()->set_data_layout(aclDataLayout);
    m_KernelTensor = std::make_unique<arm_compute::Tensor>();
    BuildArmComputeTensor(*m_KernelTensor, info.m_InputTensorInfos[1], m_Data.m_Parameters.m_DataLayout);
    m_KernelTensor->info()->set_are_values_constant(info.m_InputTensorInfos[1].IsConstant());
    if (m_Data.m_Parameters.m_BiasEnabled)
    {
        m_BiasTensor = std::make_unique<arm_compute::Tensor>();
        BuildArmComputeTensor(*m_BiasTensor, info.m_InputTensorInfos[2], m_Data.m_Parameters.m_DataLayout);
        m_BiasTensor->info()->set_are_values_constant(info.m_InputTensorInfos[2].IsConstant());
    }
    arm_compute::PadStrideInfo padStrideInfo = BuildArmComputePadStrideInfo(m_Data.m_Parameters);
    const arm_compute::Size2D aclDilationInfo = BuildArmComputeSize2D(m_Data.m_Parameters.m_DilationX,
                                                                      m_Data.m_Parameters.m_DilationY);
    const arm_compute::ActivationLayerInfo activationInfo = ConvertAdditionalInfoToAclActivationLayerInfo(descriptor);
    auto convolutionLayer = std::make_unique<arm_compute::NEConvolutionLayer>(memoryManager);
    convolutionLayer->configure(&input,
                                m_KernelTensor.get(),
                                m_BiasTensor.get(),
                                &output,
                                padStrideInfo,
                                arm_compute::WeightsInfo(),
                                aclDilationInfo,
                                activationInfo,
                                isFastMathEnabled);
    m_ConvolutionMethod =
        convolutionLayer->get_convolution_method(input.info(),
                                                 m_KernelTensor->info(),
                                                 output.info(),
                                                 padStrideInfo,
                                                 arm_compute::WeightsInfo(),
                                                 aclDilationInfo,
                                                 activationInfo,
                                                 isFastMathEnabled);
    // Add details for profiling output
    WorkloadInfo detailsInfo;
    detailsInfo.m_InputTensorInfos = info.m_InputTensorInfos;
    detailsInfo.m_OutputTensorInfos = info.m_OutputTensorInfos;
    detailsInfo.m_ConvolutionMethod = armnn::Optional<std::string>(GetConvolutionMethodString(m_ConvolutionMethod));
    // Report Profiling Details
    ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonConvolution2dWorkload_Construct",
                                         descriptor.m_Parameters,
                                         detailsInfo,
                                         GetGuid());
    m_ConvolutionLayer.reset(convolutionLayer.release());
    m_KernelTensorInfo = info.m_InputTensorInfos[1];
    if (m_Data.m_Parameters.m_BiasEnabled)
    {
        m_BiasTensorInfo = info.m_InputTensorInfos[2];
    }
}
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, armnn::ConvertAdditionalInfoToAclActivationLayerInfo(), armnn::GetConvolutionMethodString(), BaseWorkload< QueueDescriptor >::GetGuid(), armnn::info, WorkloadInfo::m_ConvolutionMethod, BaseWorkload< QueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, WorkloadInfo::m_InputTensorInfos, QueueDescriptor::m_Outputs, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and QueueDescriptor::ValidateInputsOutputs().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 150 of file NeonConvolution2dWorkload.cpp.
{
    ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID("NeonConvolution2dWorkload_Execute");
    // The constant tensors may not be fully in place until the workload is Executed
    if (!prepared)
    {
        InitializeArmComputeTensorData(*m_KernelTensor, m_KernelTensorInfo, m_Data.m_Inputs[1]);
        if (m_Data.m_Parameters.m_BiasEnabled)
        {
            InitializeArmComputeTensorData(*m_BiasTensor, m_BiasTensorInfo, m_Data.m_Inputs[2]);
        }
        m_ConvolutionLayer->prepare();
        FreeTensorIfUnused(m_KernelTensor);
        FreeTensorIfUnused(m_BiasTensor);
        prepared = true;
    }
    m_ConvolutionLayer->run();
}
References ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID, armnn::InitializeArmComputeTensorData(), BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
GetConvolutionMethod()
arm_compute::ConvolutionMethod GetConvolutionMethod () const
Definition at line 170 of file NeonConvolution2dWorkload.cpp.
{
    return m_ConvolutionMethod;
}
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonConvolution2dWorkload.hpp
src/backends/neon/workloads/NeonConvolution2dWorkload.cpp