Arm NN: ClTensorHandle Class Reference
ClTensorHandle Class Reference
#include <ClTensorHandle.hpp>
Public Member Functions
ClTensorHandle (const TensorInfo &tensorInfo)
ClTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, MemorySourceFlags importFlags=static_cast< MemorySourceFlags >(MemorySource::Undefined))
arm_compute::CLTensor & GetTensor () override
arm_compute::CLTensor const & GetTensor () const override
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual const void * Map (bool blocking=true) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual arm_compute::DataType GetDataType () const override
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > &memoryGroup) override
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
void SetImportFlags (MemorySourceFlags importFlags)
MemorySourceFlags GetImportFlags () const override
Get flags describing supported import sources.
void SetImportEnabledFlag (bool importEnabledFlag)
virtual bool Import (void *memory, MemorySource source) override
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source) override
Implementations must determine if this memory block can be imported.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo) override
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual void Unimport ()
Unimport externally allocated memory.
Detailed Description
Definition at line 28 of file ClTensorHandle.hpp.
Constructor & Destructor Documentation
ClTensorHandle() [1/2]
ClTensorHandle (const TensorInfo & tensorInfo) inline
Definition at line 31 of file ClTensorHandle.hpp.
                     : m_ImportFlags(static_cast<MemorySourceFlags>(MemorySource::Undefined)),
                       m_Imported(false),
                       m_IsImportEnabled(false)
    {
        armnn::armcomputetensorutils::BuildArmComputeTensor(m_Tensor, tensorInfo);
    }
ClTensorHandle() [2/2]
ClTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, MemorySourceFlags importFlags = static_cast<MemorySourceFlags>(MemorySource::Undefined)) inline
Definition at line 39 of file ClTensorHandle.hpp.
                   : m_ImportFlags(importFlags),
                     m_Imported(false),
                     m_IsImportEnabled(false)
    {
        armnn::armcomputetensorutils::BuildArmComputeTensor(m_Tensor, tensorInfo, dataLayout);
    }
Member Function Documentation
Allocate()
virtual void Allocate () inline override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 51 of file ClTensorHandle.hpp.
    {
        // If we have enabled Importing, don't allocate the tensor
        if (m_IsImportEnabled)
        {
            throw MemoryImportException("ClTensorHandle::Attempting to allocate memory when importing");
        }
        else
        {
            armnn::armcomputetensorutils::InitialiseArmComputeTensorEmpty(m_Tensor);
        }
    }
CanBeImported()
virtual bool CanBeImported (void * memory, MemorySource source) inline override virtual
Implementations must determine if this memory block can be imported.
This might be based on alignment or memory source type.
Returns
true if this memory can be imported.
false by default, cannot be imported.
Reimplemented from ITensorHandle.
Definition at line 135 of file ClTensorHandle.hpp.
    {
        // This TensorHandle can never import.
        armnn::IgnoreUnused(memory, source);
        return false;
    }
References armnn::IgnoreUnused().
DecorateTensorHandle()
std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo & tensorInfo) override virtual
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Parameters
tensorInfo the overidden TensorInfo.
Reimplemented from ITensorHandle.
Definition at line 12 of file ClTensorHandle.cpp.
    {
        auto* parent = const_cast<ClTensorHandle*>(this);
        auto decorated = std::make_shared<ClTensorHandleDecorator>(parent, tensorInfo);
        m_Decorated.emplace_back(decorated);
        return decorated;
    }
GetDataType()
virtual arm_compute::DataType GetDataType () const inline override virtual
Implements IClTensorHandle.
Definition at line 89 of file ClTensorHandle.hpp.
    {
        return m_Tensor.info()->data_type();
    }
GetImportFlags()
MemorySourceFlags GetImportFlags () const inline override virtual
Get flags describing supported import sources.
Reimplemented from ITensorHandle.
Definition at line 114 of file ClTensorHandle.hpp.
    {
        return m_ImportFlags;
    }
GetParent()
virtual ITensorHandle * GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Definition at line 87 of file ClTensorHandle.hpp.
{ return nullptr; }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Definition at line 104 of file ClTensorHandle.hpp.
    {
        return armcomputetensorutils::GetShape(m_Tensor.info()->tensor_shape());
    }
Referenced by ClRankWorkload::Execute().
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Definition at line 99 of file ClTensorHandle.hpp.
    {
        return armcomputetensorutils::GetStrides(m_Tensor.info()->strides_in_bytes());
    }
GetTensor() [1/2]
arm_compute::CLTensor const & GetTensor () const inline override virtual
Implements IClTensorHandle.
Definition at line 50 of file ClTensorHandle.hpp.
{ return m_Tensor; }
GetTensor() [2/2]
arm_compute::CLTensor & GetTensor () inline override virtual
Implements IClTensorHandle.
Definition at line 49 of file ClTensorHandle.hpp.
{ return m_Tensor; }
Import()
virtual bool Import (void * memory, MemorySource source) inline override virtual
Import externally allocated memory.
Parameters
memory base address of the memory being imported.
source source of the allocation for the memory being imported.
Returns
true on success or false on failure
Reimplemented from ITensorHandle.
Definition at line 124 of file ClTensorHandle.hpp.
    {
        armnn::IgnoreUnused(memory);
        if (m_ImportFlags& static_cast<MemorySourceFlags>(source))
        {
            throw MemoryImportException("ClTensorHandle::Incorrect import flag");
        }
        m_Imported = false;
        return false;
    }
References armnn::IgnoreUnused().
Manage()
virtual void Manage () inline override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 65 of file ClTensorHandle.hpp.
    {
        // If we have enabled Importing, don't manage the tensor
        if (m_IsImportEnabled)
        {
            throw MemoryImportException("ClTensorHandle::Attempting to manage memory when importing");
        }
        else
        {
            assert(m_MemoryGroup != nullptr);
            m_MemoryGroup->manage(&m_Tensor);
        }
    }
Map()
virtual const void * Map (bool blocking = true) const inline override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Definition at line 79 of file ClTensorHandle.hpp.
    {
        const_cast<arm_compute::CLTensor*>(&m_Tensor)->map(blocking);
        return static_cast<const void*>(m_Tensor.buffer() + m_Tensor.info()->offset_first_element_in_bytes());
    }
SetImportEnabledFlag()
void SetImportEnabledFlag (bool importEnabledFlag) inline
Definition at line 119 of file ClTensorHandle.hpp.
    {
        m_IsImportEnabled = importEnabledFlag;
    }
SetImportFlags()
void SetImportFlags (MemorySourceFlags importFlags) inline
Definition at line 109 of file ClTensorHandle.hpp.
    {
        m_ImportFlags = importFlags;
    }
SetMemoryGroup()
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > & memoryGroup) inline override virtual
Implements IClTensorHandle.
Definition at line 94 of file ClTensorHandle.hpp.
    {
        m_MemoryGroup = PolymorphicPointerDowncast<arm_compute::MemoryGroup>(memoryGroup);
    }
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Definition at line 85 of file ClTensorHandle.hpp.
{ const_cast<arm_compute::CLTensor*>(&m_Tensor)->unmap(); }
The documentation for this class was generated from the following files:
src/backends/cl/ClTensorHandle.hpp
src/backends/cl/ClTensorHandle.cpp