Arm NN: OnnxParserImpl Class Reference
OnnxParserImpl Class Reference
#include <OnnxParser.hpp>
Public Types
using GraphPtr = std::unique_ptr<onnx::GraphProto>
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile)
Create the network from a protobuf binary file on disk.
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network from a protobuf binary file on disk, with inputShapes specified.
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent)
Create the network from a protobuf binary.
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network from a protobuf binary, with inputShapes specified.
armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile)
Create the network from a protobuf text file on disk.
armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network from a protobuf text file on disk, with inputShapes specified.
armnn::INetworkPtr CreateNetworkFromString (const std::string &protoText)
Create the network directly from protobuf text in a string. Useful for debugging/testing.
armnn::INetworkPtr CreateNetworkFromString (const std::string &protoText, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network directly from protobuf text in a string, with inputShapes specified.
BindingPointInfo GetNetworkInputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
BindingPointInfo GetNetworkOutputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
OnnxParserImpl ()
~OnnxParserImpl ()=default
template<typename TypePair , typename Location >
void ValidateInputs (const onnx::NodeProto &node, TypePair validInputs, const Location &location)
Static Public Member Functions
static ModelPtr LoadModelFromBinary (const std::vector< uint8_t > &binaryContent)
static ModelPtr LoadModelFromBinaryFile (const char *fileName)
static ModelPtr LoadModelFromTextFile (const char *fileName)
static ModelPtr LoadModelFromString (const std::string &inputString)
static std::vector< std::string > GetInputs (ModelPtr &model)
Retrieve inputs names.
static std::vector< std::string > GetOutputs (ModelPtr &model)
Retrieve outputs names.
static const std::string GetVersion ()
Retrieve version in X.Y.Z form.
Detailed Description
Definition at line 25 of file OnnxParser.hpp.
Member Typedef Documentation
GraphPtr
using GraphPtr = std::unique_ptr<onnx::GraphProto>
Definition at line 32 of file OnnxParser.hpp.
Constructor & Destructor Documentation
OnnxParserImpl()
OnnxParserImpl ()
Definition at line 580 of file OnnxParser.cpp.
    : m_Network(nullptr, nullptr)
{
}
~OnnxParserImpl()
~OnnxParserImpl () default
Member Function Documentation
CreateNetworkFromBinary() [1/2]
INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent)
Create the network from a protobuf binary.
Definition at line 775 of file OnnxParser.cpp.
{
    ResetParser();
    ModelPtr modelProto = LoadModelFromBinary(binaryContent);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromBinary().
CreateNetworkFromBinary() [2/2]
INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network from a protobuf binary, with inputShapes specified.
Definition at line 782 of file OnnxParser.cpp.
{
    ResetParser();
    m_InputShapes = inputShapes;
    ModelPtr modelProto = LoadModelFromBinary(binaryContent);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromBinary().
CreateNetworkFromBinaryFile() [1/2]
INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile)
Create the network from a protobuf binary file on disk.
Definition at line 841 of file OnnxParser.cpp.
{
    ResetParser();
    ModelPtr modelProto = LoadModelFromBinaryFile(graphFile);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromBinaryFile().
CreateNetworkFromBinaryFile() [2/2]
INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network from a protobuf binary file on disk, with inputShapes specified.
Definition at line 848 of file OnnxParser.cpp.
{
    ResetParser();
    m_InputShapes = inputShapes;
    ModelPtr modelProto = LoadModelFromBinaryFile(graphFile);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromBinaryFile().
CreateNetworkFromString() [1/2]
INetworkPtr CreateNetworkFromString (const std::string & protoText)
Create the network directly from protobuf text in a string. Useful for debugging/testing.
Definition at line 876 of file OnnxParser.cpp.
{
    ResetParser();
    ModelPtr modelProto = LoadModelFromString(protoText);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromString().
CreateNetworkFromString() [2/2]
INetworkPtr CreateNetworkFromString (const std::string & protoText, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network directly from protobuf text in a string, with inputShapes specified.
Useful for debugging/testing
Definition at line 883 of file OnnxParser.cpp.
{
    ResetParser();
    m_InputShapes = inputShapes;
    ModelPtr modelProto = LoadModelFromString(protoText);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromString().
CreateNetworkFromTextFile() [1/2]
INetworkPtr CreateNetworkFromTextFile (const char * graphFile)
Create the network from a protobuf text file on disk.
Definition at line 759 of file OnnxParser.cpp.
{
    ResetParser();
    ModelPtr modelProto = LoadModelFromTextFile(graphFile);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromTextFile().
CreateNetworkFromTextFile() [2/2]
INetworkPtr CreateNetworkFromTextFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network from a protobuf text file on disk, with inputShapes specified.
Definition at line 766 of file OnnxParser.cpp.
{
    ResetParser();
    m_InputShapes = inputShapes;
    ModelPtr modelProto = LoadModelFromTextFile(graphFile);
    return CreateNetworkFromModel(*modelProto);
}
References OnnxParserImpl::LoadModelFromTextFile().
GetInputs()
std::vector< std::string > GetInputs (ModelPtr & model) static
Retrieve inputs names.
Definition at line 2663 of file OnnxParser.cpp.
{
    if(model == nullptr) {
        throw InvalidArgumentException(fmt::format("The given model cannot be null {}",
                                                   CHECK_LOCATION().AsString()));
    }
    std::vector<std::string> inputNames;
    std::map<std::string, bool> isConstant;
    for(auto tensor : model->graph().initializer())
    {
        isConstant[tensor.name()] = true;
    }
    for(auto input : model->graph().input())
    {
        auto it = isConstant.find(input.name());
        if(it == isConstant.end())
        {
            inputNames.push_back(input.name());
        }
    }
    return inputNames;
}
References CHECK_LOCATION.
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Definition at line 2625 of file OnnxParser.cpp.
{
    for(int i = 0; i < m_Graph->input_size(); ++i)
    {
        auto input = m_Graph->input(i);
        if(input.name() == name)
        {
            auto it = m_InputInfos.find(name);
            if (it != m_InputInfos.end())
            {
                return std::make_pair(static_cast<armnn::LayerBindingId>(i), it->second);
            }
        }
    }
    throw InvalidArgumentException(fmt::format("The input layer '{}' does not exist {}",
                                               name, CHECK_LOCATION().AsString()));
}
References CHECK_LOCATION.
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Definition at line 2644 of file OnnxParser.cpp.
{
    for(int i = 0; i < m_Graph->output_size(); ++i)
    {
        auto output = m_Graph->output(i);
        if(output.name() == name)
        {
            auto it = m_OutputInfos.find(name);
            if (it != m_OutputInfos.end())
            {
                return std::make_pair(static_cast<armnn::LayerBindingId>(i), it->second);
            }
        }
    }
    throw InvalidArgumentException(fmt::format("The output layer '{}' does not exist {}",
                                               name, CHECK_LOCATION().AsString()));
}
References CHECK_LOCATION.
GetOutputs()
std::vector< std::string > GetOutputs (ModelPtr & model) static
Retrieve outputs names.
Definition at line 2687 of file OnnxParser.cpp.
{
    if(model == nullptr) {
        throw InvalidArgumentException(fmt::format("The given model cannot be null {}",
                                                   CHECK_LOCATION().AsString()));
    }
    std::vector<std::string> outputNames;
    for(auto output : model->graph().output())
    {
        outputNames.push_back(output.name());
    }
    return outputNames;
}
References CHECK_LOCATION.
GetVersion()
const std::string GetVersion () static
Retrieve version in X.Y.Z form.
Definition at line 2702 of file OnnxParser.cpp.
{
    return ONNX_PARSER_VERSION;
}
References ONNX_PARSER_VERSION.
LoadModelFromBinary()
ModelPtr LoadModelFromBinary (const std::vector< uint8_t > & binaryContent) static
Definition at line 791 of file OnnxParser.cpp.
{
    if (binaryContent.size() == 0)
    {
        throw ParseException(fmt::format("Missing binary content", CHECK_LOCATION().AsString()));
    }
    // Parse the file into a message
    ModelPtr modelProto = std::make_unique<onnx::ModelProto>();
    google::protobuf::io::CodedInputStream codedStream(binaryContent.data(), static_cast<int>(binaryContent.size()));
    codedStream.SetTotalBytesLimit(INT_MAX);
    bool success = modelProto.get()->ParseFromCodedStream(&codedStream);
    if (!success)
    {
        std::stringstream error;
        error << "Failed to parse graph";
        throw ParseException(fmt::format("{} {}", error.str(), CHECK_LOCATION().AsString()));
    }
    return modelProto;
}
References CHECK_LOCATION, and armnn::error.
Referenced by OnnxParserImpl::CreateNetworkFromBinary(), and OnnxParserImpl::CreateNetworkFromBinary().
LoadModelFromBinaryFile()
ModelPtr LoadModelFromBinaryFile (const char * fileName) static
Definition at line 813 of file OnnxParser.cpp.
{
    FILE* fd = fopen(graphFile, "rb");
    if (fd == nullptr)
    {
        throw FileNotFoundException(fmt::format("Invalid (null) filename {}", CHECK_LOCATION().AsString()));
    }
    // Parse the file into a message
    ModelPtr modelProto = std::make_unique<onnx::ModelProto>();
    google::protobuf::io::FileInputStream  inStream(fileno(fd));
    google::protobuf::io::CodedInputStream codedStream(&inStream);
    codedStream.SetTotalBytesLimit(INT_MAX);
    bool success = modelProto.get()->ParseFromCodedStream(&codedStream);
    fclose(fd);
    if (!success)
    {
        std::stringstream error;
        error << "Failed to parse graph file";
        throw ParseException(fmt::format("{} {}", error.str(), CHECK_LOCATION().AsString()));
    }
    return modelProto;
}
References CHECK_LOCATION, and armnn::error.
Referenced by OnnxParserImpl::CreateNetworkFromBinaryFile(), and OnnxParserImpl::CreateNetworkFromBinaryFile().
LoadModelFromString()
ModelPtr LoadModelFromString (const std::string & inputString) static
Definition at line 857 of file OnnxParser.cpp.
{
    if (protoText == "")
    {
        throw InvalidArgumentException(fmt::format("Invalid (empty) string for model parameter {}",
                                                   CHECK_LOCATION().AsString()));
    }
    // Parse the string into a message
    ModelPtr modelProto = std::make_unique<onnx::ModelProto>();
    bool success = google::protobuf::TextFormat::ParseFromString(protoText, modelProto.get());
    if (!success)
    {
        std::stringstream error;
        error << "Failed to parse graph file";
        throw ParseException(fmt::format("{} {}", error.str(), CHECK_LOCATION().AsString()));
    }
    return modelProto;
}
References CHECK_LOCATION, and armnn::error.
Referenced by OnnxParserImpl::CreateNetworkFromString(), and OnnxParserImpl::CreateNetworkFromString().
LoadModelFromTextFile()
ModelPtr LoadModelFromTextFile (const char * fileName) static
Definition at line 734 of file OnnxParser.cpp.
{
    FILE* fd = fopen(graphFile, "r");
    if (fd == nullptr)
    {
        throw FileNotFoundException(fmt::format("Invalid (null) filename {}", CHECK_LOCATION().AsString()));
    }
    // Parse the file into a message
    ModelPtr     modelProto = std::make_unique<onnx::ModelProto>();
    using google::protobuf::io::FileInputStream;
    std::unique_ptr<FileInputStream> input = std::make_unique<FileInputStream>(fileno(fd));
    bool                 success = google::protobuf::TextFormat::Parse(input.get(), modelProto.get());
    fclose(fd);
    if (!success)
    {
        std::stringstream error;
        error << "Failed to parse graph file";
        throw ParseException(fmt::format("{} {}", error.str(), CHECK_LOCATION().AsString()));
    }
    return modelProto;
}
References CHECK_LOCATION, and armnn::error.
Referenced by OnnxParserImpl::CreateNetworkFromTextFile(), and OnnxParserImpl::CreateNetworkFromTextFile().
ValidateInputs()
template<typename TypePair , typename Location > void ValidateInputs (const onnx::NodeProto & node, TypePair validInputs, const Location & location)
Definition at line 496 of file OnnxParser.cpp.
{
    for(auto input : node.input())
    {
        CheckValidDataType(validInputs.second,
                           m_TensorsInfo[input].m_dtype,
                           validInputs.first,
                           node.name(),
                           input,
                           location);
    }
}
The documentation for this class was generated from the following files:
src/armnnOnnxParser/OnnxParser.hpp
src/armnnOnnxParser/OnnxParser.cpp