Arm NN: ICLTensorProxy Class Reference
ICLTensorProxy Class Reference
#include <ICLTensorProxy.hpp>
Public Member Functions
ICLTensorProxy (arm_compute::ICLTensor *iclTensor)
ICLTensorProxy (const ICLTensorProxy &)=delete
ICLTensorProxy & operator= (const ICLTensorProxy &)=delete
ICLTensorProxy (ICLTensorProxy &&)=default
ICLTensorProxy & operator= (ICLTensorProxy &&)=default
void set (arm_compute::ICLTensor *iclTensor)
arm_compute::ITensorInfo * info () const
arm_compute::ITensorInfo * info ()
uint8_t * buffer () const
arm_compute::CLQuantization quantization () const
const cl::Buffer & cl_buffer () const
Protected Member Functions
uint8_t * do_map (cl::CommandQueue &q, bool blocking)
void do_unmap (cl::CommandQueue &q)
Detailed Description
Definition at line 13 of file ICLTensorProxy.hpp.
Constructor & Destructor Documentation
ICLTensorProxy() [1/3]
ICLTensorProxy (arm_compute::ICLTensor * iclTensor) inline
Definition at line 16 of file ICLTensorProxy.hpp.
: m_DelegateTensor(iclTensor) {}
ICLTensorProxy() [2/3]
ICLTensorProxy (const ICLTensorProxy &) delete
ICLTensorProxy() [3/3]
ICLTensorProxy (ICLTensorProxy &&) default
Member Function Documentation
buffer()
uint8_t * buffer () const inline
Definition at line 43 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        return m_DelegateTensor->buffer();
    }
References ICLTensorProxy::set().
cl_buffer()
const cl::Buffer & cl_buffer () const inline
Definition at line 55 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        return m_DelegateTensor->cl_buffer();
    }
References ICLTensorProxy::set().
do_map()
uint8_t * do_map (cl::CommandQueue & q, bool blocking) inline protected
Definition at line 62 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        m_DelegateTensor->map(q, blocking);
        return m_DelegateTensor->buffer();
    }
References ICLTensorProxy::set().
do_unmap()
void do_unmap (cl::CommandQueue & q) inline protected
Definition at line 68 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        return m_DelegateTensor->unmap(q);
    }
References ICLTensorProxy::set().
info() [1/2]
arm_compute::ITensorInfo * info () inline
Definition at line 37 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        return m_DelegateTensor->info();
    }
References ICLTensorProxy::set().
info() [2/2]
arm_compute::ITensorInfo * info () const inline
Definition at line 31 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        return m_DelegateTensor->info();
    }
References ICLTensorProxy::set().
operator=() [1/2]
ICLTensorProxy & operator= (const ICLTensorProxy &) delete
operator=() [2/2]
ICLTensorProxy & operator= (ICLTensorProxy &&) default
quantization()
arm_compute::CLQuantization quantization () const inline
Definition at line 49 of file ICLTensorProxy.hpp.
    {
        ARM_COMPUTE_ERROR_ON(m_DelegateTensor == nullptr);
        return m_DelegateTensor->quantization();
    }
References ICLTensorProxy::set().
set()
void set (arm_compute::ICLTensor * iclTensor) inline
Definition at line 22 of file ICLTensorProxy.hpp.
    {
        if(iclTensor != nullptr)
        {
            m_DelegateTensor = iclTensor;
        }
    }
References ICLTensorProxy::set().
Referenced by ICLTensorProxy::buffer(), ICLTensorProxy::cl_buffer(), ICLTensorProxy::do_map(), ICLTensorProxy::do_unmap(), ICLTensorProxy::info(), ICLTensorProxy::info(), ICLTensorProxy::quantization(), and ICLTensorProxy::set().
The documentation for this class was generated from the following file:
src/backends/cl/ICLTensorProxy.hpp