Arm NN: NeonTensorHandleDecorator Class Reference
NeonTensorHandleDecorator Class Reference
#include <NeonTensorHandle.hpp>
Public Member Functions
NeonTensorHandleDecorator (IAclTensorHandle *parent, const TensorInfo &info)
arm_compute::ITensor & GetTensor () override
arm_compute::ITensor const & GetTensor () const override
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual arm_compute::DataType GetDataType () const override
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > &) override
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &) override
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
Detailed Description
Definition at line 445 of file NeonTensorHandle.hpp.
Constructor & Destructor Documentation
NeonTensorHandleDecorator()
NeonTensorHandleDecorator (IAclTensorHandle * parent, const TensorInfo & info) inline
Definition at line 448 of file NeonTensorHandle.hpp.
    : m_Tensor(&parent->GetTensor(), info)
    {
        parentHandle = parent;
    }
Member Function Documentation
Allocate()
virtual void Allocate () inline override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 457 of file NeonTensorHandle.hpp.
{}
DecorateTensorHandle()
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo & tensorInfo) inline override virtual
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Parameters
tensorInfo the overidden TensorInfo.
Reimplemented from ITensorHandle.
Definition at line 485 of file NeonTensorHandle.hpp.
    {
        return nullptr;
    };
GetDataType()
virtual arm_compute::DataType GetDataType () const inline override virtual
Implements IAclTensorHandle.
Definition at line 462 of file NeonTensorHandle.hpp.
    {
        return m_Tensor.info()->data_type();
    }
References NeonTensorDecorator::info().
GetParent()
virtual ITensorHandle * GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Definition at line 460 of file NeonTensorHandle.hpp.
{ return nullptr; }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Definition at line 480 of file NeonTensorHandle.hpp.
    {
        return armcomputetensorutils::GetShape(m_Tensor.info()->tensor_shape());
    }
References NeonTensorDecorator::info().
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Definition at line 475 of file NeonTensorHandle.hpp.
    {
        return armcomputetensorutils::GetStrides(m_Tensor.info()->strides_in_bytes());
    }
References NeonTensorDecorator::info().
GetTensor() [1/2]
arm_compute::ITensor const & GetTensor () const inline override virtual
Implements IAclTensorHandle.
Definition at line 455 of file NeonTensorHandle.hpp.
{ return m_Tensor; }
GetTensor() [2/2]
arm_compute::ITensor & GetTensor () inline override virtual
Implements IAclTensorHandle.
Definition at line 454 of file NeonTensorHandle.hpp.
{ return m_Tensor; }
Manage()
virtual void Manage () inline override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 458 of file NeonTensorHandle.hpp.
{}
Map()
virtual const void * Map (bool blocking) const inline override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Definition at line 469 of file NeonTensorHandle.hpp.
    {
        return static_cast<const void*>(m_Tensor.buffer() + m_Tensor.info()->offset_first_element_in_bytes());
    }
References NeonTensorDecorator::buffer(), and NeonTensorDecorator::info().
SetMemoryGroup()
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > &) inline override virtual
Implements IAclTensorHandle.
Definition at line 467 of file NeonTensorHandle.hpp.
{}
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Definition at line 473 of file NeonTensorHandle.hpp.
{}
The documentation for this class was generated from the following file:
src/backends/neon/NeonTensorHandle.hpp