Arm NN: TensorHandleFactoryRegistry Class Reference
TensorHandleFactoryRegistry Class Reference
#include <TensorHandleFactoryRegistry.hpp>
Public Member Functions
TensorHandleFactoryRegistry ()=default
TensorHandleFactoryRegistry (const TensorHandleFactoryRegistry &other)=delete
TensorHandleFactoryRegistry (TensorHandleFactoryRegistry &&other)=delete
void RegisterFactory (std::unique_ptr< ITensorHandleFactory > allocator)
Register a TensorHandleFactory and transfer ownership.
void RegisterMemoryManager (std::shared_ptr< IMemoryManager > memoryManger)
Register a memory manager with shared ownership.
ITensorHandleFactory * GetFactory (ITensorHandleFactory::FactoryId id) const
Find a TensorHandleFactory by Id Returns nullptr if not found.
ITensorHandleFactory * GetFactory (ITensorHandleFactory::FactoryId id, MemorySource memSource) const
Overload of above allowing specification of Memory Source.
void RegisterCopyAndImportFactoryPair (ITensorHandleFactory::FactoryId copyFactoryId, ITensorHandleFactory::FactoryId importFactoryId)
Register a pair of TensorHandleFactory Id for Memory Copy and TensorHandleFactory Id for Memory Import.
ITensorHandleFactory::FactoryId GetMatchingImportFactoryId (ITensorHandleFactory::FactoryId copyFactoryId)
Get a matching TensorHandleFatory Id for Memory Import given TensorHandleFactory Id for Memory Copy.
void AquireMemory ()
Aquire memory required for inference.
void ReleaseMemory ()
Release memory required for inference.
std::vector< std::shared_ptr< IMemoryManager > > & GetMemoryManagers ()
Detailed Description
Definition at line 23 of file TensorHandleFactoryRegistry.hpp.
Constructor & Destructor Documentation
TensorHandleFactoryRegistry() [1/3]
TensorHandleFactoryRegistry () default
TensorHandleFactoryRegistry() [2/3]
TensorHandleFactoryRegistry (const TensorHandleFactoryRegistry & other) delete
TensorHandleFactoryRegistry() [3/3]
TensorHandleFactoryRegistry (TensorHandleFactoryRegistry && other) delete
Member Function Documentation
AquireMemory()
void AquireMemory ()
Aquire memory required for inference.
Definition at line 78 of file TensorHandleFactoryRegistry.cpp.
{
    for (auto& mgr : m_MemoryManagers)
    {
        mgr->Acquire();
    }
}
GetFactory() [1/2]
ITensorHandleFactory * GetFactory (ITensorHandleFactory::FactoryId id) const
Find a TensorHandleFactory by Id Returns nullptr if not found.
Definition at line 39 of file TensorHandleFactoryRegistry.cpp.
{
    for (auto& factory : m_Factories)
    {
        if (factory->GetId() == id)
        {
            return factory.get();
        }
    }
    return nullptr;
}
Referenced by Graph::AddCompatibilityLayers(), armnn::CalculateEdgeStrategy(), armnn::CalculateSlotOption(), armnn::CalculateSlotOptionForInput(), Layer::CreateTensorHandles(), ConcatLayer::CreateTensorHandles(), SplitterLayer::CreateTensorHandles(), and armnn::RequiresCopy().
GetFactory() [2/2]
ITensorHandleFactory * GetFactory (ITensorHandleFactory::FactoryId id, MemorySource memSource) const
Overload of above allowing specification of Memory Source.
Definition at line 52 of file TensorHandleFactoryRegistry.cpp.
{
    for (auto& factory : m_Factories)
    {
        if (factory->GetId() == id && factory->GetImportFlags() == static_cast<MemorySourceFlags>(memSource))
        {
            return factory.get();
        }
    }
    return nullptr;
}
GetMatchingImportFactoryId()
ITensorHandleFactory::FactoryId GetMatchingImportFactoryId (ITensorHandleFactory::FactoryId copyFactoryId)
Get a matching TensorHandleFatory Id for Memory Import given TensorHandleFactory Id for Memory Copy.
Definition at line 72 of file TensorHandleFactoryRegistry.cpp.
{
    return m_FactoryMappings[copyFactoryId];
}
GetMemoryManagers()
std::vector< std::shared_ptr< IMemoryManager > > & GetMemoryManagers () inline
Definition at line 58 of file TensorHandleFactoryRegistry.hpp.
    {
        return m_MemoryManagers;
    }
RegisterCopyAndImportFactoryPair()
void RegisterCopyAndImportFactoryPair (ITensorHandleFactory::FactoryId copyFactoryId, ITensorHandleFactory::FactoryId importFactoryId)
Register a pair of TensorHandleFactory Id for Memory Copy and TensorHandleFactory Id for Memory Import.
Definition at line 66 of file TensorHandleFactoryRegistry.cpp.
{
    m_FactoryMappings[copyFactoryId] = importFactoryId;
}
Referenced by NeonBackend::CreateWorkloadFactory(), RefBackend::CreateWorkloadFactory(), TosaRefBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), NeonBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), NeonBackend::RegisterTensorHandleFactories(), RefBackend::RegisterTensorHandleFactories(), TosaRefBackend::RegisterTensorHandleFactories(), ClBackend::RegisterTensorHandleFactories(), and ClBackend::RegisterTensorHandleFactories().
RegisterFactory()
void RegisterFactory (std::unique_ptr< ITensorHandleFactory > allocator)
Register a TensorHandleFactory and transfer ownership.
Definition at line 12 of file TensorHandleFactoryRegistry.cpp.
{
    if (!newFactory)
    {
        return;
    }
    ITensorHandleFactory::FactoryId id = newFactory->GetId();
    // Don't register duplicates
    for (auto& registeredFactory : m_Factories)
    {
        if (id == registeredFactory->GetId())
        {
            return;
        }
    }
    // Take ownership of the new allocator
    m_Factories.push_back(std::move(newFactory));
}
Referenced by NeonBackend::CreateWorkloadFactory(), RefBackend::CreateWorkloadFactory(), TosaRefBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), NeonBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), NeonBackend::RegisterTensorHandleFactories(), RefBackend::RegisterTensorHandleFactories(), TosaRefBackend::RegisterTensorHandleFactories(), ClBackend::RegisterTensorHandleFactories(), and ClBackend::RegisterTensorHandleFactories().
RegisterMemoryManager()
void RegisterMemoryManager (std::shared_ptr< IMemoryManager > memoryManger)
Register a memory manager with shared ownership.
Definition at line 34 of file TensorHandleFactoryRegistry.cpp.
{
    m_MemoryManagers.push_back(memoryManger);
}
Referenced by NeonBackend::CreateWorkloadFactory(), RefBackend::CreateWorkloadFactory(), TosaRefBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), NeonBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), ClBackend::CreateWorkloadFactory(), NeonBackend::RegisterTensorHandleFactories(), RefBackend::RegisterTensorHandleFactories(), TosaRefBackend::RegisterTensorHandleFactories(), ClBackend::RegisterTensorHandleFactories(), and ClBackend::RegisterTensorHandleFactories().
ReleaseMemory()
void ReleaseMemory ()
Release memory required for inference.
Definition at line 86 of file TensorHandleFactoryRegistry.cpp.
{
    for (auto& mgr : m_MemoryManagers)
    {
        mgr->Release();
    }
}
Referenced by LoadedNetwork::FreeWorkingMemory().
The documentation for this class was generated from the following files:
src/backends/backendsCommon/TensorHandleFactoryRegistry.hpp
src/backends/backendsCommon/TensorHandleFactoryRegistry.cpp