Arm NN: ClTensorDecorator Class Reference
ClTensorDecorator Class Reference
ClTensorDecorator wraps an existing CL tensor allowing us to override the TensorInfo for it.
#include <ClTensorHandle.hpp>
Public Member Functions
ClTensorDecorator ()
ClTensorDecorator (arm_compute::ICLTensor *original, const TensorInfo &info)
~ClTensorDecorator ()=default
ClTensorDecorator (const ClTensorDecorator &)=delete
ClTensorDecorator & operator= (const ClTensorDecorator &)=delete
ClTensorDecorator (ClTensorDecorator &&)=default
ClTensorDecorator & operator= (ClTensorDecorator &&)=default
arm_compute::ICLTensor * parent ()
void map (bool blocking=true)
void unmap ()
virtual arm_compute::ITensorInfo * info () const override
virtual arm_compute::ITensorInfo * info () override
const cl::Buffer & cl_buffer () const override
arm_compute::CLQuantization quantization () const override
Protected Member Functions
uint8_t * do_map (cl::CommandQueue &q, bool blocking) override
void do_unmap (cl::CommandQueue &q) override
Detailed Description
ClTensorDecorator wraps an existing CL tensor allowing us to override the TensorInfo for it.
Definition at line 379 of file ClTensorHandle.hpp.
Constructor & Destructor Documentation
ClTensorDecorator() [1/4]
ClTensorDecorator ()
Definition at line 20 of file ClTensorHandle.cpp.
    : m_Original(nullptr), m_TensorInfo()
    {
    }
ClTensorDecorator() [2/4]
ClTensorDecorator (arm_compute::ICLTensor * original, const TensorInfo & info)
Definition at line 25 of file ClTensorHandle.cpp.
    : m_Original(nullptr), m_TensorInfo()
    {
        m_TensorInfo = armcomputetensorutils::BuildArmComputeTensorInfo(tensorInfo);
        m_Original = original;
    }
~ClTensorDecorator()
~ClTensorDecorator () default
ClTensorDecorator() [3/4]
ClTensorDecorator (const ClTensorDecorator &) delete
ClTensorDecorator() [4/4]
ClTensorDecorator (ClTensorDecorator &&) default
Member Function Documentation
cl_buffer()
const cl::Buffer & cl_buffer () const override
Definition at line 42 of file ClTensorHandle.cpp.
    {
        ARM_COMPUTE_ERROR_ON(m_Original == nullptr);
        return m_Original->cl_buffer();
    }
do_map()
uint8_t * do_map (cl::CommandQueue & q, bool blocking) override protected
Definition at line 68 of file ClTensorHandle.cpp.
    {
        if(m_Original->buffer() == nullptr)
        {
            m_Original->map(q, blocking);
        }
        return m_Original->buffer();
    }
do_unmap()
void do_unmap (cl::CommandQueue & q) override protected
Definition at line 77 of file ClTensorHandle.cpp.
    {
        m_Original->unmap(q);
    }
info() [1/2]
arm_compute::ITensorInfo * info () const override virtual
Definition at line 32 of file ClTensorHandle.cpp.
    {
        return &m_TensorInfo;
    }
Referenced by ClTensorHandleDecorator::GetDataType(), ClTensorHandleDecorator::GetShape(), ClTensorHandleDecorator::GetStrides(), and ClTensorHandleDecorator::Map().
info() [2/2]
arm_compute::ITensorInfo * info () override virtual
Definition at line 37 of file ClTensorHandle.cpp.
    {
        return &m_TensorInfo;
    }
map()
void map (bool blocking = true)
Definition at line 58 of file ClTensorHandle.cpp.
    {
        arm_compute::ICLTensor::map(arm_compute::CLScheduler::get().queue(), blocking);
    }
Referenced by ClTensorHandleDecorator::Map().
operator=() [1/2]
ClTensorDecorator & operator= (ClTensorDecorator &&) default
operator=() [2/2]
ClTensorDecorator & operator= (const ClTensorDecorator &) delete
parent()
arm_compute::ICLTensor * parent ()
Definition at line 48 of file ClTensorHandle.cpp.
    {
        return nullptr;
    }
quantization()
arm_compute::CLQuantization quantization () const override
Definition at line 53 of file ClTensorHandle.cpp.
    {
        return m_Original->quantization();
    }
unmap()
void unmap ()
Definition at line 63 of file ClTensorHandle.cpp.
    {
        arm_compute::ICLTensor::unmap(arm_compute::CLScheduler::get().queue());
    }
Referenced by ClTensorHandleDecorator::Unmap().
The documentation for this class was generated from the following files:
src/backends/cl/ClTensorHandle.hpp
src/backends/cl/ClTensorHandle.cpp