Arm NN: OptionalReferenceSwitch< IsReference, T > Class Template Reference
OptionalReferenceSwitch< IsReference, T > Class Template Reference
The default implementation is the non-reference case.
#include <Optional.hpp>
Public Types
using Base = OptionalBase
Public Member Functions
OptionalReferenceSwitch () noexcept
OptionalReferenceSwitch (EmptyOptional) noexcept
OptionalReferenceSwitch (const T &value)
template<class... Args>
OptionalReferenceSwitch (ConstructInPlace, Args &&... args)
OptionalReferenceSwitch (const OptionalReferenceSwitch &other)
OptionalReferenceSwitch & operator= (const T &value)
OptionalReferenceSwitch & operator= (const OptionalReferenceSwitch &other)
OptionalReferenceSwitch & operator= (EmptyOptional)
~OptionalReferenceSwitch ()
void reset ()
const T & value () const
T & value ()
Public Member Functions inherited from OptionalBase
OptionalBase () noexcept
bool has_value () const noexcept
operator bool () const noexcept
Conversion to bool, so can be used in if-statements and similar contexts expecting a bool.
Additional Inherited Members
Protected Member Functions inherited from OptionalBase
OptionalBase (bool hasValue) noexcept
Protected Attributes inherited from OptionalBase
bool m_HasValue
Detailed Description
template<bool IsReference, typename T>
class armnn::OptionalReferenceSwitch< IsReference, T >
The default implementation is the non-reference case.
This has an unsigned char array for storing the optional value which is in-place constructed there.
Definition at line 81 of file Optional.hpp.
Member Typedef Documentation
Base
template<bool IsReference, typename T > using Base = OptionalBase
Definition at line 84 of file Optional.hpp.
Constructor & Destructor Documentation
OptionalReferenceSwitch() [1/5]
template<bool IsReference, typename T > OptionalReferenceSwitch () inline noexcept
Definition at line 86 of file Optional.hpp.
: Base{} {}
OptionalReferenceSwitch() [2/5]
template<bool IsReference, typename T > OptionalReferenceSwitch (EmptyOptional) inline noexcept
Definition at line 87 of file Optional.hpp.
: Base{} {}
OptionalReferenceSwitch() [3/5]
template<bool IsReference, typename T > OptionalReferenceSwitch (const T & value) inline
Definition at line 89 of file Optional.hpp.
        : Base{}
    {
        Construct(value);
    }
References OptionalReferenceSwitch< IsReference, T >::value().
OptionalReferenceSwitch() [4/5]
template<bool IsReference, typename T > template<class... Args> OptionalReferenceSwitch (ConstructInPlace , Args &&... args) inline
Definition at line 96 of file Optional.hpp.
        : Base{}
    {
        Construct(CONSTRUCT_IN_PLACE, std::forward<Args>(args)...);
    }
References CONSTRUCT_IN_PLACE.
OptionalReferenceSwitch() [5/5]
template<bool IsReference, typename T > OptionalReferenceSwitch (const OptionalReferenceSwitch< IsReference, T > & other) inline
Definition at line 102 of file Optional.hpp.
        : Base{}
    {
        *this = other;
    }
~OptionalReferenceSwitch()
template<bool IsReference, typename T > ~OptionalReferenceSwitch () inline
Definition at line 132 of file Optional.hpp.
    {
        reset();
    }
References OptionalReferenceSwitch< IsReference, T >::reset().
Member Function Documentation
operator=() [1/3]
template<bool IsReference, typename T > OptionalReferenceSwitch & operator= (const OptionalReferenceSwitch< IsReference, T > & other) inline
Definition at line 115 of file Optional.hpp.
    {
        reset();
        if (other.has_value())
        {
            Construct(other.value());
        }
        return *this;
    }
References OptionalBase::has_value(), OptionalReferenceSwitch< IsReference, T >::reset(), and OptionalReferenceSwitch< IsReference, T >::value().
operator=() [2/3]
template<bool IsReference, typename T > OptionalReferenceSwitch & operator= (const T & value) inline
Definition at line 108 of file Optional.hpp.
    {
        reset();
        Construct(value);
        return *this;
    }
References OptionalReferenceSwitch< IsReference, T >::reset(), and OptionalReferenceSwitch< IsReference, T >::value().
operator=() [3/3]
template<bool IsReference, typename T > OptionalReferenceSwitch & operator= (EmptyOptional) inline
Definition at line 126 of file Optional.hpp.
    {
        reset();
        return *this;
    }
References OptionalReferenceSwitch< IsReference, T >::reset().
reset()
template<bool IsReference, typename T > void reset () inline
Definition at line 137 of file Optional.hpp.
    {
        if (Base::has_value())
        {
            value().T::~T();
            Base::m_HasValue = false;
        }
    }
References OptionalBase::has_value(), OptionalBase::m_HasValue, and OptionalReferenceSwitch< IsReference, T >::value().
Referenced by OptionalReferenceSwitch< IsReference, T >::operator=(), OptionalReferenceSwitch< IsReference, T >::operator=(), OptionalReferenceSwitch< IsReference, T >::operator=(), OptionalReferenceSwitch< true, T >::operator=(), OptionalReferenceSwitch< IsReference, T >::~OptionalReferenceSwitch(), and OptionalReferenceSwitch< true, T >::~OptionalReferenceSwitch().
value() [1/2]
template<bool IsReference, typename T > T & value () inline
Definition at line 157 of file Optional.hpp.
    {
        if (!Base::has_value())
        {
            throw BadOptionalAccessException("Optional has no value");
        }
        auto valuePtr = reinterpret_cast<T*>(m_Storage);
        return *valuePtr;
    }
References OptionalBase::has_value().
value() [2/2]
template<bool IsReference, typename T > const T & value () const inline
Definition at line 146 of file Optional.hpp.
    {
        if (!Base::has_value())
        {
            throw BadOptionalAccessException("Optional has no value");
        }
        auto valuePtr = reinterpret_cast<const T*>(m_Storage);
        return *valuePtr;
    }
References OptionalBase::has_value().
Referenced by ProfilingDetails::AddDetailsToString(), NetworkImpl::AddPrecompiledLayer(), NetworkImpl::AddTransposeConvolution2dLayer(), armnn::CheckSupportRule(), armnn::ClConvolution2dWorkloadValidate(), armnn::ClConvolution3dWorkloadValidate(), armnn::ClDepthwiseConvolutionWorkloadValidate(), armnn::ClFullyConnectedWorkloadValidate(), armnn::ClTransposeConvolution2dWorkloadValidate(), armnnOnnxParser::CreateConstTensorImpl(), BackendRegistry::Deregister(), armnn::ExtractJsonObjects(), armnn::GetBiasTypeFromWeightsType(), armnnUtils::GetPerAxisParams(), TensorInfo::GetQuantizationOffset(), LayerSupportHandle::IsBroadcastToSupported(), LayerSupportHandle::IsConvolution2dSupported(), RefLayerSupport::IsConvolution2dSupported(), LayerSupportHandle::IsConvolution3dSupported(), RefLayerSupport::IsConvolution3dSupported(), LayerSupportHandle::IsDepthwiseConvolutionSupported(), RefLayerSupport::IsDepthwiseConvolutionSupported(), LayerSupportHandle::IsDilatedDepthwiseConvolutionSupported(), LayerSupportHandle::IsFullyConnectedSupported(), RefLayerSupport::IsLayerSupported(), TosaRefLayerSupport::IsLayerSupported(), ClLayerSupport::IsLayerSupported(), NeonLayerSupport::IsLayerSupported(), armnn::IsLayerTypeSupported(), LayerSupportBase::IsStandInSupported(), LayerSupportHandle::IsTransposeConvolution2dSupported(), RefLayerSupport::IsTransposeConvolution2dSupported(), armnn::NeonConvolution2dWorkloadValidate(), armnn::NeonConvolution3dWorkloadValidate(), armnn::NeonDepthwiseConvolutionWorkloadValidate(), armnn::NeonFullyConnectedWorkloadValidate(), armnn::NeonTransposeConvolution2dWorkloadValidate(), OptionalReferenceSwitch< IsReference, T >::operator=(), OptionalReferenceSwitch< IsReference, T >::operator=(), OptionalReferenceSwitch< true, T >::operator=(), Optional< T >::operator==(), OptionalReferenceSwitch< IsReference, T >::OptionalReferenceSwitch(), BackendRegistry::Register(), OptionalReferenceSwitch< IsReference, T >::reset(), armnn::SetValueChecked(), armnnUtils::ToFloatArray(), IBackendInternal::UseCustomMemoryAllocator(), Convolution2dQueueDescriptor::Validate(), Convolution3dQueueDescriptor::Validate(), DepthwiseConvolution2dQueueDescriptor::Validate(), and TransposeConvolution2dQueueDescriptor::Validate().
The documentation for this class was generated from the following file:
include/armnn/Optional.hpp