Arm NN: OutputHandler Class Reference
OutputHandler Class Reference
#include <OutputHandler.hpp>
Public Member Functions
void SetTensorInfo (const TensorInfo &tensorInfo)
Sets the TensorInfo used by this output handler.
void CreateTensorHandles (const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
Creates tensor handles used by the intermediate tensors.
void CreateTensorHandles (const ITensorHandleFactory &factory, const bool IsMemoryManaged=true)
const TensorInfo & GetTensorInfo () const
Gets the matching TensorInfo for the output.
ITensorHandle * GetData () const
Gets the allocated tensor memory.
void CollectWorkloadOutputs (WorkloadDataCollector &dataCollector) const
Fill the outputs for a given queue descriptor.
void SetData (std::unique_ptr< ITensorHandle > data)
void SetAllocatedData ()
void UseAllocatedData ()
bool IsTensorInfoSet () const
Returns true if SetTensorInfo() has been called at least once on this.
Detailed Description
Definition at line 28 of file OutputHandler.hpp.
Member Function Documentation
CollectWorkloadOutputs()
void CollectWorkloadOutputs (WorkloadDataCollector & dataCollector) const
Fill the outputs for a given queue descriptor.
Definition at line 33 of file OutputHandler.cpp.
{
    dataCollector.Push(m_TensorHandle.get(), m_TensorInfo);
}
References WorkloadDataCollector::Push().
CreateTensorHandles() [1/2]
void CreateTensorHandles (const ITensorHandleFactory & factory, const bool IsMemoryManaged = true)
Definition at line 28 of file OutputHandler.cpp.
{
    m_TensorHandle = factory.CreateTensorHandle(m_TensorInfo, IsMemoryManaged);
}
References ITensorHandleFactory::CreateTensorHandle().
CreateTensorHandles() [2/2]
void CreateTensorHandles (const IWorkloadFactory & factory, const bool IsMemoryManaged = true)
Creates tensor handles used by the intermediate tensors.
Does not allocate memory.
Parameters
factory - Factory to be used for handler creation.
Definition at line 21 of file OutputHandler.cpp.
{
    ARMNN_NO_DEPRECATE_WARN_BEGIN
    m_TensorHandle = factory.CreateTensorHandle(m_TensorInfo, IsMemoryManaged);
    ARMNN_NO_DEPRECATE_WARN_END
}
References ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, and IWorkloadFactory::CreateTensorHandle().
Referenced by Layer::CreateTensorHandles().
GetData()
ITensorHandle * GetData () const inline
Gets the allocated tensor memory.
Returns
- Pointer to the tensor memory.
Definition at line 46 of file OutputHandler.hpp.
{ return m_TensorHandle.get(); }
Referenced by LoadedNetwork::EnqueueWorkload().
GetTensorInfo()
const TensorInfo & GetTensorInfo () const inline
Gets the matching TensorInfo for the output.
Returns
- References to the output TensorInfo.
Definition at line 42 of file OutputHandler.hpp.
{ return m_TensorInfo; }
Referenced by OutputSlot::GetTensorInfo(), OptimizeConsecutiveReshapesImpl::Run(), PermuteAsReshapeImpl::Run(), TransposeAsReshapeImpl::Run(), OutputSlot::ValidateTensorShape(), PermuteAsReshapeImpl::~PermuteAsReshapeImpl(), and TransposeAsReshapeImpl::~TransposeAsReshapeImpl().
IsTensorInfoSet()
bool IsTensorInfoSet () const inline
Returns true if SetTensorInfo() has been called at least once on this.
Definition at line 58 of file OutputHandler.hpp.
{ return m_bTensorInfoSet; }
Referenced by OutputSlot::IsTensorInfoSet().
SetAllocatedData()
void SetAllocatedData ()
Definition at line 38 of file OutputHandler.cpp.
{
    // Set allocated data only once
    if (!m_AllocatedTensorHandle)
    {
       m_AllocatedTensorHandle = std::move(m_TensorHandle);
    }
}
SetData()
void SetData (std::unique_ptr< ITensorHandle > data) inline
Definition at line 51 of file OutputHandler.hpp.
{ m_TensorHandle = std::move(data); }
SetTensorInfo()
void SetTensorInfo (const TensorInfo & tensorInfo)
Sets the TensorInfo used by this output handler.
Parameters
tensorInfo - TensorInfo for the output.
Definition at line 15 of file OutputHandler.cpp.
{
    m_TensorInfo = tensorInfo;
    m_bTensorInfoSet = true;
}
Referenced by InputSlot::Insert(), OutputSlot::MoveAllConnections(), DeleteBroadcastToImpl::Run(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), and OutputSlot::SetTensorInfo().
UseAllocatedData()
void UseAllocatedData () inline
Definition at line 55 of file OutputHandler.hpp.
{ m_TensorHandle = m_AllocatedTensorHandle; }
The documentation for this class was generated from the following files:
src/armnn/OutputHandler.hpp
src/armnn/OutputHandler.cpp