Arm NN: MaxMinIntoBoundedReluImpl Class Reference
MaxMinIntoBoundedReluImpl Class Reference
#include <MaxMinIntoBoundedRelu.hpp>
Static Public Member Functions
static void Run (Graph &graph, InputSlot &connection)
Run for every exclusive connection between any Max & Min layers The Max, Min and its associated constant inputs will be removed, and replaced with a BoundedRelu Activation.
Protected Member Functions
MaxMinIntoBoundedReluImpl ()=default
~MaxMinIntoBoundedReluImpl ()=default
Detailed Description
Definition at line 13 of file MaxMinIntoBoundedRelu.hpp.
Constructor & Destructor Documentation
MaxMinIntoBoundedReluImpl()
MaxMinIntoBoundedReluImpl () protected default
~MaxMinIntoBoundedReluImpl()
~MaxMinIntoBoundedReluImpl () protected default
References armnn::BFloat16, armnn::Boolean, armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and armnn::Signed64.
Member Function Documentation
Run()
static void Run (Graph & graph, InputSlot & connection) inline static
Run for every exclusive connection between any Max & Min layers The Max, Min and its associated constant inputs will be removed, and replaced with a BoundedRelu Activation.
Definition at line 18 of file MaxMinIntoBoundedRelu.hpp.
    {
        Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
        Layer& child = connection.GetOwningLayer();
        auto& maxLayer = *PolymorphicDowncast<ElementwiseBinaryLayer*>(&base);
        if (maxLayer.GetParameters().m_Operation != BinaryOperation::Maximum)
        {
            return;
        }
        auto& minLayer = *PolymorphicDowncast<ElementwiseBinaryLayer*>(&child);
        if (minLayer.GetParameters().m_Operation != BinaryOperation::Minimum)
        {
            return;
        }
        if (maxLayer.GetDataType() != minLayer.GetDataType())
        {
            return;
        }
        // get max and min values
        float_t maxValue;
        if (!GetValue(maxLayer, maxValue))
        {
            return;
        }
        float_t minValue;
        if (!GetValue(minLayer, minValue))
        {
            return;
        }
        // Save original parent output slot of the max layer
        OutputSlot& parentOut = *maxLayer.GetInputSlot(0).GetConnectedOutputSlot();
        // Insert activation layer between max layer and its parent layer
        ActivationDescriptor boundedReluDescriptor(ActivationFunction::BoundedReLu, minValue, maxValue);
        const std::string name = std::string("replaced-") + maxLayer.GetName() + std::string("-") + minLayer.GetName()
                               + std::string("-with-BoundedRelu");
        auto& boundedReluLayer = *graph.InsertNewLayer<ActivationLayer>(maxLayer.GetInputSlot(0),
                                                                        boundedReluDescriptor,
                                                                        name.c_str());
        // Reconnects with original parent.
        boundedReluLayer.GetOutputSlot().MoveAllConnections(parentOut);
        // Moves connections in min layer output to parent layer.
        // Min layer will be removed as it's left unconnected.
        // Max layer will be removed if left unconnected.
        minLayer.GetOutputSlot().MoveAllConnections(boundedReluLayer.GetOutputSlot());
    }
References armnn::BoundedReLu, InputSlot::GetConnectedOutputSlot(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), Graph::InsertNewLayer(), armnn::Maximum, armnn::Minimum, and OutputSlot::MoveAllConnections().
The documentation for this class was generated from the following file:
src/armnn/optimizations/MaxMinIntoBoundedRelu.hpp