Arm NN: ConstTensorHandle Class Reference
ConstTensorHandle Class Reference
#include <TensorHandle.hpp>
Public Member Functions
template<typename T >
const T * GetConstTensor () const
const TensorInfo & GetTensorInfo () const
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
virtual void Allocate ()=0
Indicate to the memory manager that this resource is no longer active.
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo)
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Protected Member Functions
ConstTensorHandle (const TensorInfo &tensorInfo)
void SetConstMemory (const void *mem)
Detailed Description
Definition at line 24 of file TensorHandle.hpp.
Constructor & Destructor Documentation
ConstTensorHandle()
ConstTensorHandle (const TensorInfo & tensorInfo) protected
Definition at line 31 of file TensorHandle.cpp.
: m_TensorInfo(tensorInfo)
, m_Memory(nullptr)
{
}
Member Function Documentation
GetConstTensor() [1/4]
template<typename T > const T * GetConstTensor () const inline
Definition at line 28 of file TensorHandle.hpp.
    {
        if (armnnUtils::CompatibleTypes<T>(GetTensorInfo().GetDataType()))
        {
            return reinterpret_cast<const T*>(m_Memory);
        }
        else
        {
            throw armnn::Exception("Attempting to get not compatible type tensor!");
        }
    }
References ConstTensorHandle::GetTensorInfo().
Referenced by ClConstantWorkload::Execute(), NeonConstantWorkload::Execute(), armnn::InitializeArmComputeClTensorData(), armnn::InitializeArmComputeTensorData(), armnn::PermuteTensor(), and ScopedTensorHandle::ScopedTensorHandle().
GetConstTensor() [2/4]
template<> const void * GetConstTensor () const
GetConstTensor() [3/4]
template<> const void * GetConstTensor () const
GetConstTensor() [4/4]
template<> const void * GetConstTensor () const
Definition at line 38 of file TensorHandle.cpp.
{
    return m_Memory;
}
GetParent()
virtual ITensorHandle * GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Definition at line 47 of file TensorHandle.hpp.
{ return nullptr; }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Definition at line 56 of file TensorHandle.hpp.
{ return m_TensorInfo.GetShape(); }
References TensorInfo::GetShape().
Referenced by LstmQueueDescriptor::Validate(), and UnidirectionalSequenceLstmQueueDescriptor::Validate().
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Definition at line 52 of file TensorHandle.hpp.
    {
        return GetUnpaddedTensorStrides(m_TensorInfo);
    }
References armnn::GetUnpaddedTensorStrides().
GetTensorInfo()
const TensorInfo & GetTensorInfo () const inline
Definition at line 40 of file TensorHandle.hpp.
    {
        return m_TensorInfo;
    }
Referenced by ScopedTensorHandle::Allocate(), ClTransposeConvolution2dWorkload::ClTransposeConvolution2dWorkload(), armnn::Convert1HWOTensorToAcl(), armnn::Convert1HWOtoMIHW(), armnn::ConvertWeightTensorFromArmnnToAcl(), ConstTensorHandle::GetConstTensor(), TensorHandle::GetTensor(), armnn::InitializeArmComputeClTensorData(), armnn::InitializeArmComputeTensorData(), NeonDetectionPostProcessWorkload::NeonDetectionPostProcessWorkload(), NeonTransposeConvolution2dWorkload::NeonTransposeConvolution2dWorkload(), armnn::PermuteTensor(), ScopedTensorHandle::ScopedTensorHandle(), DetectionPostProcessQueueDescriptor::Validate(), BatchNormalizationQueueDescriptor::Validate(), ConstantQueueDescriptor::Validate(), LstmQueueDescriptor::Validate(), TransposeConvolution2dQueueDescriptor::Validate(), QLstmQueueDescriptor::Validate(), QuantizedLstmQueueDescriptor::Validate(), and UnidirectionalSequenceLstmQueueDescriptor::Validate().
Manage()
virtual void Manage () inline override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 45 of file TensorHandle.hpp.
{}
Map()
virtual const void * Map (bool blocking) const inline override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Definition at line 49 of file TensorHandle.hpp.
{ return m_Memory; }
SetConstMemory()
void SetConstMemory (const void * mem) inline protected
Definition at line 61 of file TensorHandle.hpp.
{ m_Memory = mem; }
Referenced by ConstPassthroughTensorHandle::ConstPassthroughTensorHandle(), and TensorHandle::SetMemory().
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Definition at line 50 of file TensorHandle.hpp.
{}
The documentation for this class was generated from the following files:
include/armnn/backends/TensorHandle.hpp
src/backends/backendsCommon/TensorHandle.cpp