Arm NN: TurboConvertConstDequantisationLayersToConstLayersImpl Class Reference
TurboConvertConstDequantisationLayersToConstLayersImpl Class Reference
#include <TurboConvertConstDequantisationLayersToConstLayers.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Protected Member Functions
TurboConvertConstDequantisationLayersToConstLayersImpl ()=default
~TurboConvertConstDequantisationLayersToConstLayersImpl ()=default
Detailed Description
Definition at line 18 of file TurboConvertConstDequantisationLayersToConstLayers.hpp.
Constructor & Destructor Documentation
TurboConvertConstDequantisationLayersToConstLayersImpl()
TurboConvertConstDequantisationLayersToConstLayersImpl () protected default
~TurboConvertConstDequantisationLayersToConstLayersImpl()
~TurboConvertConstDequantisationLayersToConstLayersImpl () protected default
References ARMNN_ASSERT, ARMNN_LOG, armnn::Convolution2d, InputSlot::GetConnectedOutputSlot(), OutputSlot::GetConnection(), TensorInfo::GetDataType(), armnn::GetDataTypeName(), armnn::GetDataTypeSize(), Layer::GetInputSlot(), OutputSlot::GetNumConnections(), TensorInfo::GetNumElements(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), TensorInfo::GetShape(), OutputSlot::GetTensorInfo(), armnn::info, TensorInfo::IsConstant(), ConstantLayer::m_LayerOutput, OutputSlot::MoveAllConnections(), armnn::NCHW, armnn::Permute, TensorInfo::SetConstant(), and OutputSlot::SetTensorInfo().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Definition at line 21 of file TurboConvertConstDequantisationLayersToConstLayers.hpp.
    {
        Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
        Layer& child = connection.GetOwningLayer();
        // Check the basic criteria for the optimization are met.
        if ((base.GetType() == LayerType::Constant) && (child.GetType() == LayerType::Dequantize))
        {
            ReplaceConstDequantisationLayer(graph, PolymorphicDowncast<ConstantLayer*>(&base),
                                            PolymorphicDowncast<DequantizeLayer*>(&child));
        }
    }
References armnn::Constant, armnn::Dequantize, InputSlot::GetConnectedOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), and Layer::GetType().
The documentation for this class was generated from the following file:
src/armnn/optimizations/TurboConvertConstDequantisationLayersToConstLayers.hpp