Arm NN: PerAxisIterator< T, Base > Class Template Reference
PerAxisIterator< T, Base > Class Template Reference
PerAxisIterator for per-axis quantization.
#include <BaseIterator.hpp>
Public Member Functions
PerAxisIterator (T *data=nullptr, unsigned int axisFactor=0, unsigned int axisDimensionality=0)
PerAxisIterator (T *data=nullptr, const armnn::TensorShape &tensorShape=TensorShape(), const unsigned int axis=0)
void Reset (void *data) override
PerAxisIterator & operator++ () override
PerAxisIterator & operator+= (const unsigned int increment) override
PerAxisIterator & operator-= (const unsigned int decrement) override
PerAxisIterator & SetIndexOnMem (const unsigned int index)
PerAxisIterator & operator[] (const unsigned int index) override
Protected Attributes
T * m_Iterator
T * m_Start
unsigned int m_AxisIndex
unsigned int m_AxisDimensionality
unsigned int m_AxisFactor
unsigned int m_Index
Detailed Description
template<typename T, typename Base>
class armnn::PerAxisIterator< T, Base >
PerAxisIterator for per-axis quantization.
Iterates over a tensor as layed out in memory and keeps track of the axis index.
Definition at line 707 of file BaseIterator.hpp.
Constructor & Destructor Documentation
PerAxisIterator() [1/2]
template<typename T , typename Base > PerAxisIterator (T * data = nullptr, unsigned int axisFactor = 0, unsigned int axisDimensionality = 0) inline
Definition at line 710 of file BaseIterator.hpp.
        : m_Iterator(data),
          m_Start(data),
          m_AxisIndex(0), // iterates over the dimension of axis
          m_AxisDimensionality(axisDimensionality), // tensorShape[quantization_dim]
          m_AxisFactor(axisFactor),
          m_Index(0)
    {}
PerAxisIterator() [2/2]
template<typename T , typename Base > PerAxisIterator (T * data = nullptr, const armnn::TensorShape & tensorShape = TensorShape(), const unsigned int axis = 0) inline
Definition at line 721 of file BaseIterator.hpp.
        : m_Iterator(data),
          m_Start(data),
          m_AxisIndex(0),
          m_Index(0)
    {
        m_AxisDimensionality = tensorShape[axis];
        m_AxisFactor = armnnUtils::GetNumElementsAfter(tensorShape, axis);
    }
References armnnUtils::GetNumElementsAfter(), PerAxisIterator< T, Base >::m_AxisDimensionality, and PerAxisIterator< T, Base >::m_AxisFactor.
Member Function Documentation
operator++()
template<typename T , typename Base > PerAxisIterator & operator++ () inline override
Definition at line 741 of file BaseIterator.hpp.
    {
        ++m_Index;
        this -> operator[](m_Index);
        return *this;
    }
References PerAxisIterator< T, Base >::m_Index, and PerAxisIterator< T, Base >::operator[]().
operator+=()
template<typename T , typename Base > PerAxisIterator & operator+= (const unsigned int increment) inline override
Definition at line 748 of file BaseIterator.hpp.
    {
        m_Index += increment;
        this -> operator[](m_Index);
        return *this;
    }
References PerAxisIterator< T, Base >::m_Index, and PerAxisIterator< T, Base >::operator[]().
operator-=()
template<typename T , typename Base > PerAxisIterator & operator-= (const unsigned int decrement) inline override
Definition at line 755 of file BaseIterator.hpp.
    {
        m_Index -= decrement;
        this -> operator[](m_Index);
        return *this;
    }
References PerAxisIterator< T, Base >::m_Index, and PerAxisIterator< T, Base >::operator[]().
operator[]()
template<typename T , typename Base > PerAxisIterator & operator[] (const unsigned int index) inline override
Definition at line 779 of file BaseIterator.hpp.
    {
        SetIndexOnMem(index);
        return *this;
    }
References PerAxisIterator< T, Base >::SetIndexOnMem().
Referenced by PerAxisIterator< T, Base >::operator++(), PerAxisIterator< T, Base >::operator+=(), and PerAxisIterator< T, Base >::operator-=().
Reset()
template<typename T , typename Base > void Reset (void * data) inline override
Definition at line 733 of file BaseIterator.hpp.
    {
        m_Iterator = reinterpret_cast<T*>(data);
        m_Start = m_Iterator;
        m_AxisIndex = 0;
        m_Index = 0;
    }
References PerAxisIterator< T, Base >::m_AxisIndex, PerAxisIterator< T, Base >::m_Index, PerAxisIterator< T, Base >::m_Iterator, and PerAxisIterator< T, Base >::m_Start.
SetIndexOnMem()
template<typename T , typename Base > PerAxisIterator & SetIndexOnMem (const unsigned int index) inline
Definition at line 763 of file BaseIterator.hpp.
    {
        ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(m_Iterator, "PerAxisIterator: m_Iterator is null!");
        m_Iterator = m_Start + index;
        if (index < m_AxisFactor || m_AxisDimensionality < 1)
        {
            m_AxisIndex = 0;
        }
        else
        {
            m_AxisIndex = (index / m_AxisFactor) % m_AxisDimensionality;
        }
        m_Index = index;
        return *this;
    }
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, PerAxisIterator< T, Base >::m_AxisDimensionality, PerAxisIterator< T, Base >::m_AxisFactor, PerAxisIterator< T, Base >::m_AxisIndex, PerAxisIterator< T, Base >::m_Index, PerAxisIterator< T, Base >::m_Iterator, and PerAxisIterator< T, Base >::m_Start.
Referenced by PerAxisIterator< T, Base >::operator[]().
Member Data Documentation
m_AxisDimensionality
template<typename T , typename Base > unsigned int m_AxisDimensionality protected
Definition at line 789 of file BaseIterator.hpp.
Referenced by PerAxisIterator< T, Base >::PerAxisIterator(), and PerAxisIterator< T, Base >::SetIndexOnMem().
m_AxisFactor
template<typename T , typename Base > unsigned int m_AxisFactor protected
Definition at line 790 of file BaseIterator.hpp.
Referenced by PerAxisIterator< T, Base >::PerAxisIterator(), and PerAxisIterator< T, Base >::SetIndexOnMem().
m_AxisIndex
template<typename T , typename Base > unsigned int m_AxisIndex protected
Definition at line 788 of file BaseIterator.hpp.
Referenced by PerAxisIterator< T, Base >::Reset(), and PerAxisIterator< T, Base >::SetIndexOnMem().
m_Index
template<typename T , typename Base > unsigned int m_Index protected
Definition at line 791 of file BaseIterator.hpp.
Referenced by PerAxisIterator< T, Base >::operator++(), PerAxisIterator< T, Base >::operator+=(), PerAxisIterator< T, Base >::operator-=(), PerAxisIterator< T, Base >::Reset(), and PerAxisIterator< T, Base >::SetIndexOnMem().
m_Iterator
template<typename T , typename Base > T* m_Iterator protected
Definition at line 786 of file BaseIterator.hpp.
Referenced by PerAxisIterator< T, Base >::Reset(), and PerAxisIterator< T, Base >::SetIndexOnMem().
m_Start
template<typename T , typename Base > T* m_Start protected
Definition at line 787 of file BaseIterator.hpp.
Referenced by PerAxisIterator< T, Base >::Reset(), and PerAxisIterator< T, Base >::SetIndexOnMem().
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp