Arm NN: OptimizationViews Class Reference
OptimizationViews Class Reference
#include <OptimizationViews.hpp>
Classes
struct SubstitutionPair
Public Types
using Subgraphs = std::vector<SubgraphView>
using Substitutions = std::vector<SubstitutionPair>
Public Member Functions
OptimizationViews (const NetworkOptions &networkOptions={})
OptimizationViews (const OptimizationViews &)=delete
OptimizationViews & operator= (const OptimizationViews &)=delete
OptimizationViews (OptimizationViews &&)=default
OptimizationViews & operator= (OptimizationViews &&)=default
void AddSubstitution (SubstitutionPair &&substitution)
void AddFailedSubgraph (SubgraphView &&subgraph)
void AddUntouchedSubgraph (SubgraphView &&subgraph)
void AddDeletedSubgraph (SubgraphView &&subgraph)
const Substitutions & GetSubstitutions () const
const Subgraphs & GetFailedSubgraphs () const
const Subgraphs & GetUntouchedSubgraphs () const
const Subgraphs & GetDeletedSubgraphs () const
Substitutions & GetSubstitutions ()
Subgraphs & GetFailedSubgraphs ()
Subgraphs & GetUntouchedSubgraphs ()
bool Validate (const SubgraphView &originalSubgraph) const
INetwork * GetINetwork ()
INetwork & GetINetworkRef ()
Detailed Description
Definition at line 17 of file OptimizationViews.hpp.
Member Typedef Documentation
Subgraphs
using Subgraphs = std::vector<SubgraphView>
Definition at line 35 of file OptimizationViews.hpp.
Substitutions
using Substitutions = std::vector<SubstitutionPair>
Definition at line 36 of file OptimizationViews.hpp.
Constructor & Destructor Documentation
OptimizationViews() [1/3]
OptimizationViews (const NetworkOptions & networkOptions = {}) inline
Definition at line 20 of file OptimizationViews.hpp.
{}) : m_INetwork(INetwork::Create(networkOptions)) {}
OptimizationViews() [2/3]
OptimizationViews (const OptimizationViews &) delete
OptimizationViews() [3/3]
OptimizationViews (OptimizationViews &&) default
Member Function Documentation
AddDeletedSubgraph()
void AddDeletedSubgraph (SubgraphView && subgraph) inline
Definition at line 53 of file OptimizationViews.hpp.
    {
        m_DeletedSubgraphs.emplace_back(subgraph);
    }
Referenced by armnn::FoldPadLayer2d(), and armnn::RemoveReshapeLayer().
AddFailedSubgraph()
void AddFailedSubgraph (SubgraphView && subgraph) inline
Definition at line 43 of file OptimizationViews.hpp.
    {
        m_FailedOptimizations.emplace_back(subgraph);
    }
AddSubstitution()
void AddSubstitution (SubstitutionPair && substitution) inline
Definition at line 38 of file OptimizationViews.hpp.
    {
        m_SuccesfulOptimizations.emplace_back(substitution);
    }
Referenced by armnn::FoldPadLayer(), armnn::FuseLayer(), TosaRefBackend::OptimizeSubgraphView(), armnn::ReplaceLayer(), armnn::ReplaceLayers(), and armnn::ReplaceMultipleLayers().
AddUntouchedSubgraph()
void AddUntouchedSubgraph (SubgraphView && subgraph) inline
Definition at line 48 of file OptimizationViews.hpp.
    {
        m_UntouchedSubgraphs.emplace_back(subgraph);
    }
Referenced by IBackendInternal::OptimizeSubgraphView(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), and armnn::ReportUntouchedLayers().
GetDeletedSubgraphs()
const Subgraphs & GetDeletedSubgraphs () const inline
Definition at line 61 of file OptimizationViews.hpp.
{ return m_DeletedSubgraphs; }
Referenced by armnn::ApplyBackendOptimizations(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), and RefBackend::OptimizeSubgraphView().
GetFailedSubgraphs() [1/2]
Subgraphs & GetFailedSubgraphs () inline
Definition at line 64 of file OptimizationViews.hpp.
{ return m_FailedOptimizations; }
GetFailedSubgraphs() [2/2]
const Subgraphs & GetFailedSubgraphs () const inline
Definition at line 59 of file OptimizationViews.hpp.
{ return m_FailedOptimizations; }
Referenced by armnn::ApplyBackendOptimizations().
GetINetwork()
INetwork * GetINetwork () inline
Definition at line 69 of file OptimizationViews.hpp.
{ return m_INetwork.get(); }
Referenced by armnn::ChainReduceLayers(), armnn::FoldPadLayer2d(), armnn::FuseAdditionLayer(), armnn::FuseBatchNormalizationLayer(), armnn::FuseConvolution2dLayer(), armnn::FuseDepthwiseConvolution2dLayer(), armnn::FuseDivisionLayer(), armnn::FuseElementwiseBinaryLayer(), armnn::FuseFullyConnectedLayer(), armnn::FuseMultiplicationLayer(), armnn::FuseSubtractionLayer(), NeonBackend::OptimizeSubgraphView(), and TosaRefBackend::OptimizeSubgraphView().
GetINetworkRef()
INetwork & GetINetworkRef () inline
Definition at line 70 of file OptimizationViews.hpp.
{ return *m_INetwork; }
GetSubstitutions() [1/2]
Substitutions & GetSubstitutions () inline
Definition at line 63 of file OptimizationViews.hpp.
{ return m_SuccesfulOptimizations; }
GetSubstitutions() [2/2]
const Substitutions & GetSubstitutions () const inline
Definition at line 58 of file OptimizationViews.hpp.
{ return m_SuccesfulOptimizations; }
Referenced by armnn::ApplyBackendOptimizations(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), and RefBackend::OptimizeSubgraphView().
GetUntouchedSubgraphs() [1/2]
Subgraphs & GetUntouchedSubgraphs () inline
Definition at line 65 of file OptimizationViews.hpp.
{ return m_UntouchedSubgraphs; }
GetUntouchedSubgraphs() [2/2]
const Subgraphs & GetUntouchedSubgraphs () const inline
Definition at line 60 of file OptimizationViews.hpp.
{ return m_UntouchedSubgraphs; }
operator=() [1/2]
OptimizationViews & operator= (const OptimizationViews &) delete
operator=() [2/2]
OptimizationViews & operator= (OptimizationViews &&) default
Validate()
bool Validate (const SubgraphView & originalSubgraph) const
Definition at line 11 of file OptimizationViews.cpp.
{
    //This needs to verify that:
    // 1) the sum of m_SuccesfulOptimizations & m_FailedOptimizations & m_UntouchedSubgraphs contains subgraphviews
    //    which cover the entire space of the originalSubgraph.
    // 2) Each SubstitutionPair contains matching inputs and outputs
    bool valid = true;
    // Create a copy of the layer list from the original subgraph and sort it
    SubgraphView::IConnectableLayers originalLayers = originalSubgraph.GetIConnectableLayers();
    originalLayers.sort();
    // Create a new list based on the sum of all the subgraphs and sort it
    SubgraphView::IConnectableLayers countedLayers;
    for (auto& failed : m_FailedOptimizations)
    {
        countedLayers.insert(countedLayers.end(),
                             failed.GetIConnectableLayers().begin(),
                             failed.GetIConnectableLayers().end());
    }
    for (auto& untouched : m_UntouchedSubgraphs)
    {
        countedLayers.insert(countedLayers.end(),
                             untouched.GetIConnectableLayers().begin(),
                             untouched.GetIConnectableLayers().end());
    }
    for (auto& successful : m_SuccesfulOptimizations)
    {
        countedLayers.insert(countedLayers.end(),
                             successful.m_SubstitutableSubgraph.GetIConnectableLayers().begin(),
                             successful.m_SubstitutableSubgraph.GetIConnectableLayers().end());
    }
    for (auto& successful : m_DeletedSubgraphs)
    {
        countedLayers.insert(countedLayers.end(),
                             successful.GetIConnectableLayers().begin(),
                             successful.GetIConnectableLayers().end());
    }
    countedLayers.sort();
    // Compare the two lists to make sure they match
    valid &= originalLayers.size() == countedLayers.size();
    auto oIt = originalLayers.begin();
    auto cIt = countedLayers.begin();
    for (size_t i=0; i < originalLayers.size() && valid; ++i, ++oIt, ++cIt)
    {
        valid &= (*oIt == *cIt);
    }
    // Compare the substitution subgraphs to ensure they are compatible
    if (valid)
    {
        for (auto& substitution : m_SuccesfulOptimizations)
        {
            bool validSubstitution = true;
            const SubgraphView& replacement = substitution.m_ReplacementSubgraph;
            const SubgraphView& old = substitution.m_SubstitutableSubgraph;
            validSubstitution &= replacement.GetIInputSlots().size() == old.GetIInputSlots().size();
            validSubstitution &= replacement.GetIOutputSlots().size() == old.GetIOutputSlots().size();
            valid &= validSubstitution;
        }
    }
    return valid;
}
References SubgraphView::GetIConnectableLayers(), SubgraphView::GetIInputSlots(), and SubgraphView::GetIOutputSlots().
Referenced by armnn::ApplyBackendOptimizations().
The documentation for this class was generated from the following files:
include/armnn/backends/OptimizationViews.hpp
src/backends/backendsCommon/OptimizationViews.cpp