Arm NN: Decoder< IType > Class Template Reference
Decoder< IType > Class Template Reference abstract
#include <BaseIterator.hpp>
Public Member Functions
Decoder ()
virtual ~Decoder ()
virtual void Reset (void *)=0
virtual IType Get () const =0
virtual std::vector< float > DecodeTensor (const TensorShape &tensorShape, bool isDepthwise=false)=0
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
virtual BaseIterator & operator++ ()=0
virtual BaseIterator & operator+= (const unsigned int increment)=0
virtual BaseIterator & operator-= (const unsigned int increment)=0
virtual BaseIterator & operator[] (const unsigned int index)=0
Detailed Description
template<typename IType>
class armnn::Decoder< IType >
Definition at line 35 of file BaseIterator.hpp.
Constructor & Destructor Documentation
Decoder()
template<typename IType > Decoder () inline
Definition at line 38 of file BaseIterator.hpp.
{}
~Decoder()
template<typename IType > virtual ~Decoder () inline virtual
Definition at line 40 of file BaseIterator.hpp.
{}
Member Function Documentation
DecodeTensor()
template<typename IType > virtual std::vector< float > DecodeTensor (const TensorShape & tensorShape, bool isDepthwise = false) pure virtual
Implemented in ScaledInt32PerAxisDecoder, QASymm8Decoder, QASymmS8Decoder, QSymmS8Decoder, QSymm16Decoder, Float16Decoder, Float32Decoder, ScaledInt32Decoder, Int32Decoder, Int32ToInt32tDecoder, Int64Decoder, BooleanDecoder, BooleanDecoderBool, and QSymm8PerAxisDecoder.
Referenced by BatchMatMul::BatchMatMul(), armnn::Convolve(), armnn::Convolve3d(), armnn::FullyConnected(), armnn::Pooling2d(), armnn::Pooling3d(), armnn::ScatterNd(), armnn::Tile(), and armnn::TransposeConvolution2dImpl().
Get()
template<typename IType > virtual IType Get () const pure virtual
Implemented in QASymm8Decoder, QASymmS8Decoder, QSymmS8Decoder, QSymm16Decoder, Float16Decoder, Float32Decoder, ScaledInt32Decoder, Int32Decoder, Int32ToInt32tDecoder, Int64Decoder, BooleanDecoder, BooleanDecoderBool, QSymm8PerAxisDecoder, and ScaledInt32PerAxisDecoder.
Referenced by armnn::Activation(), armnn::ArgMinMax(), armnn::BatchNormImpl(), armnn::BatchToSpaceNd(), ClipVector(), armnn::Concatenate(), CopyVector(), armnn::Dequantize(), armnn::DetectionPostProcess(), armnn::Gather(), armnn::InstanceNorm(), armnn::LogSoftmax(), MatrixBatchVectorMultiplyAccumulate(), MeanStddevNormalization(), armnn::MirrorPad(), armnn::Pad(), armnn::Reduce(), armnn::Resize(), armnn::ReverseV2(), armnn::ScatterNd(), armnn::ScatterNd(), armnn::Softmax(), armnn::SpaceToBatchNd(), armnn::SpaceToDepth(), armnn::Split(), Sub1Vector(), armnn::Tile(), armnn::TransposeConvolution2dImpl(), VectorBatchVectorAdd(), VectorBatchVectorAssign(), VectorBatchVectorCwiseProduct(), VectorBatchVectorCwiseProductAccumulate(), VectorVectorCwiseProduct(), and VectorVectorCwiseProductAccumulate().
Reset()
template<typename IType > virtual void Reset (void *) pure virtual
Implemented in TypedIterator< const float, Decoder< float > >, TypedIterator< const Half, Decoder< float > >, TypedIterator< const int16_t, Decoder< float > >, TypedIterator< const int32_t, Decoder< float > >, TypedIterator< const int32_t, Decoder< int32_t > >, TypedIterator< const int64_t, Decoder< double_t > >, TypedIterator< const int8_t, Decoder< float > >, TypedIterator< const uint8_t, Decoder< bool > >, TypedIterator< const uint8_t, Decoder< float > >, PerAxisIterator< const int32_t, Decoder< float > >, and PerAxisIterator< const int8_t, Decoder< float > >.
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp