Arm NN: RefTensorHandle Class Reference
RefTensorHandle Class Reference
#include <RefTensorHandle.hpp>
Public Member Functions
RefTensorHandle (const TensorInfo &tensorInfo, std::shared_ptr< RefMemoryManager > &memoryManager)
RefTensorHandle (const TensorInfo &tensorInfo)
RefTensorHandle (const TensorInfo &tensorInfo, const RefTensorHandle &parent)
~RefTensorHandle ()
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
const TensorInfo & GetTensorInfo () const
virtual MemorySourceFlags GetImportFlags () const override
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source) override
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source) override
Implementations must determine if this memory block can be imported.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo) override
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
virtual const void * Map (bool blocking=true) const=0
Map the tensor data for access.
void * Map (bool blocking=true)
Map the tensor data for access.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual void Unimport ()
Unimport externally allocated memory.
Detailed Description
Definition at line 17 of file RefTensorHandle.hpp.
Constructor & Destructor Documentation
RefTensorHandle() [1/3]
RefTensorHandle (const TensorInfo & tensorInfo, std::shared_ptr< RefMemoryManager > & memoryManager)
Definition at line 11 of file RefTensorHandle.cpp.
                                                                                                            :
    m_TensorInfo(tensorInfo),
    m_MemoryManager(memoryManager),
    m_Pool(nullptr),
    m_UnmanagedMemory(nullptr),
    m_ImportedMemory(nullptr),
    m_Decorated()
{
}
RefTensorHandle() [2/3]
RefTensorHandle (const TensorInfo & tensorInfo)
Definition at line 21 of file RefTensorHandle.cpp.
                                 : m_TensorInfo(tensorInfo),
                                   m_Pool(nullptr),
                                   m_UnmanagedMemory(nullptr),
                                   m_ImportedMemory(nullptr),
                                   m_Decorated()
{
}
RefTensorHandle() [3/3]
RefTensorHandle (const TensorInfo & tensorInfo, const RefTensorHandle & parent)
Definition at line 30 of file RefTensorHandle.cpp.
        : m_TensorInfo(tensorInfo),
          m_MemoryManager(parent.m_MemoryManager),
          m_Pool(parent.m_Pool),
          m_UnmanagedMemory(parent.m_UnmanagedMemory),
          m_ImportedMemory(parent.m_ImportedMemory),
          m_Decorated()
{
}
~RefTensorHandle()
~RefTensorHandle ()
Definition at line 40 of file RefTensorHandle.cpp.
{
    ::operator delete(m_UnmanagedMemory);
}
Member Function Documentation
Allocate()
void Allocate () override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 56 of file RefTensorHandle.cpp.
{
    if (!m_UnmanagedMemory)
    {
        if (!m_Pool)
        {
            // unmanaged
            m_UnmanagedMemory = ::operator new(m_TensorInfo.GetNumBytes());
        }
        else
        {
            m_MemoryManager->Allocate(m_Pool);
        }
    }
    else
    {
        throw InvalidArgumentException("RefTensorHandle::Allocate Trying to allocate a RefTensorHandle"
                                       "that already has allocated memory.");
    }
}
References TensorInfo::GetNumBytes().
CanBeImported()
bool CanBeImported (void * memory, MemorySource source) override virtual
Implementations must determine if this memory block can be imported.
This might be based on alignment or memory source type.
Returns
true if this memory can be imported.
false by default, cannot be imported.
Reimplemented from ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 153 of file RefTensorHandle.cpp.
{
    if (source == MemorySource::Malloc)
    {
        uintptr_t alignment = GetDataTypeSize(m_TensorInfo.GetDataType());
        if (reinterpret_cast<uintptr_t>(memory) % alignment)
        {
            return false;
        }
        return true;
    }
    return false;
}
References TensorInfo::GetDataType(), armnn::GetDataTypeSize(), and armnn::Malloc.
Referenced by RefTensorHandle::Import().
DecorateTensorHandle()
std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo & tensorInfo) override virtual
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Parameters
tensorInfo the overidden TensorInfo.
Reimplemented from ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 167 of file RefTensorHandle.cpp.
{
    auto decorated = std::make_shared<RefTensorHandleDecorator>(tensorInfo, *this);
    m_Decorated.emplace_back(decorated);
    return decorated;
}
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Get flags describing supported import sources.
Reimplemented from ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 130 of file RefTensorHandle.cpp.
{
    return static_cast<MemorySourceFlags>(MemorySource::Malloc);
}
References armnn::Malloc.
GetParent()
virtual ITensorHandle * GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 32 of file RefTensorHandle.hpp.
    {
        return nullptr;
    }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 48 of file RefTensorHandle.hpp.
    {
        return m_TensorInfo.GetShape();
    }
References TensorInfo::GetShape().
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 43 of file RefTensorHandle.hpp.
    {
        return GetUnpaddedTensorStrides(m_TensorInfo);
    }
References armnn::GetUnpaddedTensorStrides().
GetTensorInfo()
const TensorInfo & GetTensorInfo () const inline
Definition at line 53 of file RefTensorHandle.hpp.
    {
        return m_TensorInfo;
    }
Import()
bool Import (void * memory, MemorySource source) override virtual
Import externally allocated memory.
Parameters
memory base address of the memory being imported.
source source of the allocation for the memory being imported.
Returns
true on success or false on failure
Reimplemented from ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 135 of file RefTensorHandle.cpp.
{
    if (source == MemorySource::Malloc)
    {
        // Check memory alignment
        if(!CanBeImported(memory, source))
        {
            m_ImportedMemory = nullptr;
            return false;
        }
        m_ImportedMemory = memory;
        return true;
    }
    return false;
}
References RefTensorHandle::CanBeImported(), and armnn::Malloc.
Manage()
void Manage () override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 45 of file RefTensorHandle.cpp.
{
    ARMNN_THROW_MSG_IF_FALSE(!m_Pool, RuntimeException, "RefTensorHandle::Manage() called twice");
    ARMNN_THROW_MSG_IF_FALSE(!m_UnmanagedMemory, RuntimeException, "RefTensorHandle::Manage() called after Allocate()");
    if (m_MemoryManager)
    {
        m_Pool = m_MemoryManager->Manage(m_TensorInfo.GetNumBytes());
    }
}
References ARMNN_THROW_MSG_IF_FALSE, and TensorInfo::GetNumBytes().
Map() [1/3]
void * Map (bool blocking = true) inline
Map the tensor data for access.
Must be paired with call to Unmap().
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Definition at line 44 of file ITensorHandle.hpp.
    {
        return const_cast<void*>(static_cast<const ITensorHandle*>(this)->Map(blocking));
    }
Map() [2/3]
virtual const void * Map (bool blocking = true) const virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator, and RefTensorHandleDecorator.
Map() [3/3]
const void * Map (bool blocking) const override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator, and RefTensorHandleDecorator.
Definition at line 77 of file RefTensorHandle.cpp.
{
    return GetPointer();
}
Referenced by RefTensorHandleDecorator::Map().
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Reimplemented in RefTensorHandleDecorator.
Definition at line 40 of file RefTensorHandle.hpp.
    {}
The documentation for this class was generated from the following files:
src/backends/reference/RefTensorHandle.hpp
src/backends/reference/RefTensorHandle.cpp