Arm NN: ManagedConstTensorHandle Class Reference
ManagedConstTensorHandle Class Reference
#include <TensorHandle.hpp>
Public Member Functions
ManagedConstTensorHandle (std::shared_ptr< ConstTensorHandle > ptr)
const void * Map (bool blocking=true)
RAII Managed resource Unmaps MemoryArea once out of scope.
ManagedConstTensorHandle (const ConstTensorHandle &other)=delete
ManagedConstTensorHandle & operator= (const ManagedConstTensorHandle &other)=delete
ManagedConstTensorHandle & operator= (ManagedConstTensorHandle &&other) noexcept=delete
~ManagedConstTensorHandle ()
void Unmap ()
const TensorInfo & GetTensorInfo () const
bool IsMapped () const
Detailed Description
Definition at line 187 of file TensorHandle.hpp.
Constructor & Destructor Documentation
ManagedConstTensorHandle() [1/2]
ManagedConstTensorHandle (std::shared_ptr< ConstTensorHandle > ptr) inline explicit
Definition at line 191 of file TensorHandle.hpp.
        : m_Mapped(false)
        , m_TensorHandle(std::move(ptr)) {};
ManagedConstTensorHandle() [2/2]
ManagedConstTensorHandle (const ConstTensorHandle & other) delete
~ManagedConstTensorHandle()
~ManagedConstTensorHandle () inline
Definition at line 220 of file TensorHandle.hpp.
    {
        // Bias tensor handles need to be initialized empty before entering scope of if statement checking if enabled
        if (m_TensorHandle)
        {
            Unmap();
        }
    }
References ManagedConstTensorHandle::Unmap().
Member Function Documentation
GetTensorInfo()
const TensorInfo & GetTensorInfo () const inline
Definition at line 239 of file TensorHandle.hpp.
    {
        return m_TensorHandle->GetTensorInfo();
    }
Referenced by BatchNormalizationLayer::ExecuteStrategy(), ConstantLayer::ExecuteStrategy(), DetectionPostProcessLayer::ExecuteStrategy(), LstmLayer::ExecuteStrategy(), QLstmLayer::ExecuteStrategy(), QuantizedLstmLayer::ExecuteStrategy(), TransposeConvolution2dLayer::ExecuteStrategy(), and UnidirectionalSequenceLstmLayer::ExecuteStrategy().
IsMapped()
bool IsMapped () const inline
Definition at line 244 of file TensorHandle.hpp.
    {
        return m_Mapped;
    }
Map()
const void * Map (bool blocking = true) inline
RAII Managed resource Unmaps MemoryArea once out of scope.
Definition at line 196 of file TensorHandle.hpp.
    {
        if (m_TensorHandle)
        {
            auto pRet = m_TensorHandle->Map(blocking);
            m_Mapped = true;
            return pRet;
        }
        else
        {
            throw armnn::Exception("Attempting to Map null TensorHandle");
        }
    }
Referenced by BatchNormalizationLayer::ExecuteStrategy(), ConstantLayer::ExecuteStrategy(), DetectionPostProcessLayer::ExecuteStrategy(), LstmLayer::ExecuteStrategy(), QLstmLayer::ExecuteStrategy(), QuantizedLstmLayer::ExecuteStrategy(), TransposeConvolution2dLayer::ExecuteStrategy(), and UnidirectionalSequenceLstmLayer::ExecuteStrategy().
operator=() [1/2]
ManagedConstTensorHandle & operator= (const ManagedConstTensorHandle & other) delete
operator=() [2/2]
ManagedConstTensorHandle & operator= (ManagedConstTensorHandle && other) delete noexcept
Unmap()
void Unmap () inline
Definition at line 229 of file TensorHandle.hpp.
    {
        // Only unmap if mapped and TensorHandle exists.
        if (m_Mapped && m_TensorHandle)
        {
            m_TensorHandle->Unmap();
            m_Mapped = false;
        }
    }
Referenced by ManagedConstTensorHandle::~ManagedConstTensorHandle().
The documentation for this class was generated from the following file:
include/armnn/backends/TensorHandle.hpp