Arm NN: BackendSettings Struct Reference
BackendSettings Struct Reference
#include <BackendSettings.hpp>
Public Member Functions
BackendSettings ()=default
BackendSettings (const BackendIdVector &preferredBackends, const IDeviceSpec &deviceSpec)
BackendSettings (const BackendSettings &other)
bool IsBackendPreferred (const BackendId &backend) const
bool IsBackendSupported (const BackendId &backend) const
bool IsBackendSelected (const BackendId &backend) const
bool IsBackendIgnored (const BackendId &backend) const
bool IsCpuRefUsed () const
BackendIdVector GetAvailablePreferredBackends () const
Public Attributes
BackendIdVector m_PreferredBackends
BackendIdSet m_SupportedBackends
BackendIdSet m_SelectedBackends
BackendIdSet m_IgnoredBackends
Detailed Description
Definition at line 18 of file BackendSettings.hpp.
Constructor & Destructor Documentation
BackendSettings() [1/3]
BackendSettings () default
BackendSettings() [2/3]
BackendSettings (const BackendIdVector & preferredBackends, const IDeviceSpec & deviceSpec) inline
Definition at line 27 of file BackendSettings.hpp.
    {
        Initialize(preferredBackends, deviceSpec);
    }
BackendSettings() [3/3]
BackendSettings (const BackendSettings & other) inline
Definition at line 33 of file BackendSettings.hpp.
        : m_PreferredBackends(other.m_PreferredBackends)
        , m_SupportedBackends(other.m_SupportedBackends)
        , m_SelectedBackends(other.m_SelectedBackends)
        , m_IgnoredBackends(other.m_IgnoredBackends)
    {
    }
Member Function Documentation
GetAvailablePreferredBackends()
BackendIdVector GetAvailablePreferredBackends () const inline
Definition at line 67 of file BackendSettings.hpp.
    {
        BackendIdVector availablePreferredBackends;
        for (const BackendId& backend : m_PreferredBackends)
        {
            if (IsBackendSupported(backend) && !IsBackendIgnored(backend))
            {
                availablePreferredBackends.push_back(backend);
            }
        }
        return availablePreferredBackends;
    }
References BackendSettings::IsBackendIgnored(), BackendSettings::IsBackendSupported(), and BackendSettings::m_PreferredBackends.
Referenced by armnn::AssignBackends(), and armnn::AssignBackends().
IsBackendIgnored()
bool IsBackendIgnored (const BackendId & backend) const inline
Definition at line 56 of file BackendSettings.hpp.
    {
        return IsBackendInCollection(backend, m_IgnoredBackends);
    }
References BackendSettings::m_IgnoredBackends.
Referenced by BackendSettings::GetAvailablePreferredBackends().
IsBackendPreferred()
bool IsBackendPreferred (const BackendId & backend) const inline
Definition at line 41 of file BackendSettings.hpp.
    {
        return IsBackendInCollection(backend, m_PreferredBackends);
    }
References BackendSettings::m_PreferredBackends.
Referenced by BackendSettings::IsCpuRefUsed().
IsBackendSelected()
bool IsBackendSelected (const BackendId & backend) const inline
Definition at line 51 of file BackendSettings.hpp.
    {
        return IsBackendInCollection(backend, m_SelectedBackends);
    }
References BackendSettings::m_SelectedBackends.
IsBackendSupported()
bool IsBackendSupported (const BackendId & backend) const inline
Definition at line 46 of file BackendSettings.hpp.
    {
        return IsBackendInCollection(backend, m_SupportedBackends);
    }
References BackendSettings::m_SupportedBackends.
Referenced by armnn::AssignBackendsIConnectable(), BackendSettings::GetAvailablePreferredBackends(), and BackendSettings::IsCpuRefUsed().
IsCpuRefUsed()
bool IsCpuRefUsed () const inline
Definition at line 61 of file BackendSettings.hpp.
    {
        BackendId cpuBackendId(Compute::CpuRef);
        return IsBackendSupported(cpuBackendId) && IsBackendPreferred(cpuBackendId);
    }
References armnn::CpuRef, BackendSettings::IsBackendPreferred(), and BackendSettings::IsBackendSupported().
Referenced by armnn::AssignBackendsIConnectable().
Member Data Documentation
m_IgnoredBackends
BackendIdSet m_IgnoredBackends
Definition at line 23 of file BackendSettings.hpp.
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssignBackendsIConnectable(), and BackendSettings::IsBackendIgnored().
m_PreferredBackends
BackendIdVector m_PreferredBackends
Definition at line 20 of file BackendSettings.hpp.
Referenced by BackendSettings::GetAvailablePreferredBackends(), BackendSettings::IsBackendPreferred(), and armnn::ReturnWithError().
m_SelectedBackends
BackendIdSet m_SelectedBackends
Definition at line 22 of file BackendSettings.hpp.
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssignBackendsIConnectable(), and BackendSettings::IsBackendSelected().
m_SupportedBackends
BackendIdSet m_SupportedBackends
Definition at line 21 of file BackendSettings.hpp.
Referenced by armnn::CreateSupportedBackends(), and BackendSettings::IsBackendSupported().
The documentation for this struct was generated from the following file:
src/armnn/BackendSettings.hpp