Arm NN: LstmInputParamsInfo Struct Reference
LstmInputParamsInfo Struct Reference
#include <LstmParams.hpp>
Public Member Functions
LstmInputParamsInfo ()
const TensorInfo & Deref (const TensorInfo *tensorInfo) const
const TensorInfo & GetInputToInputWeights () const
const TensorInfo & GetInputToForgetWeights () const
const TensorInfo & GetInputToCellWeights () const
const TensorInfo & GetInputToOutputWeights () const
const TensorInfo & GetRecurrentToInputWeights () const
const TensorInfo & GetRecurrentToForgetWeights () const
const TensorInfo & GetRecurrentToCellWeights () const
const TensorInfo & GetRecurrentToOutputWeights () const
const TensorInfo & GetCellToInputWeights () const
const TensorInfo & GetCellToForgetWeights () const
const TensorInfo & GetCellToOutputWeights () const
const TensorInfo & GetInputGateBias () const
const TensorInfo & GetForgetGateBias () const
const TensorInfo & GetCellBias () const
const TensorInfo & GetOutputGateBias () const
const TensorInfo & GetProjectionWeights () const
const TensorInfo & GetProjectionBias () const
const TensorInfo & GetInputLayerNormWeights () const
const TensorInfo & GetForgetLayerNormWeights () const
const TensorInfo & GetCellLayerNormWeights () const
const TensorInfo & GetOutputLayerNormWeights () const
Public Attributes
const TensorInfo * m_InputToInputWeights
const TensorInfo * m_InputToForgetWeights
const TensorInfo * m_InputToCellWeights
const TensorInfo * m_InputToOutputWeights
const TensorInfo * m_RecurrentToInputWeights
const TensorInfo * m_RecurrentToForgetWeights
const TensorInfo * m_RecurrentToCellWeights
const TensorInfo * m_RecurrentToOutputWeights
const TensorInfo * m_CellToInputWeights
const TensorInfo * m_CellToForgetWeights
const TensorInfo * m_CellToOutputWeights
const TensorInfo * m_InputGateBias
const TensorInfo * m_ForgetGateBias
const TensorInfo * m_CellBias
const TensorInfo * m_OutputGateBias
const TensorInfo * m_ProjectionWeights
const TensorInfo * m_ProjectionBias
const TensorInfo * m_InputLayerNormWeights
const TensorInfo * m_ForgetLayerNormWeights
const TensorInfo * m_CellLayerNormWeights
const TensorInfo * m_OutputLayerNormWeights
Detailed Description
Definition at line 63 of file LstmParams.hpp.
Constructor & Destructor Documentation
LstmInputParamsInfo()
LstmInputParamsInfo () inline
Definition at line 65 of file LstmParams.hpp.
            : m_InputToInputWeights(nullptr)
            , m_InputToForgetWeights(nullptr)
            , m_InputToCellWeights(nullptr)
            , m_InputToOutputWeights(nullptr)
            , m_RecurrentToInputWeights(nullptr)
            , m_RecurrentToForgetWeights(nullptr)
            , m_RecurrentToCellWeights(nullptr)
            , m_RecurrentToOutputWeights(nullptr)
            , m_CellToInputWeights(nullptr)
            , m_CellToForgetWeights(nullptr)
            , m_CellToOutputWeights(nullptr)
            , m_InputGateBias(nullptr)
            , m_ForgetGateBias(nullptr)
            , m_CellBias(nullptr)
            , m_OutputGateBias(nullptr)
            , m_ProjectionWeights(nullptr)
            , m_ProjectionBias(nullptr)
            , m_InputLayerNormWeights(nullptr)
            , m_ForgetLayerNormWeights(nullptr)
            , m_CellLayerNormWeights(nullptr)
            , m_OutputLayerNormWeights(nullptr)
    {
    }
Member Function Documentation
Deref()
const TensorInfo & Deref (const TensorInfo * tensorInfo) const inline
Definition at line 111 of file LstmParams.hpp.
    {
        if (tensorInfo != nullptr)
        {
            const TensorInfo &temp = *tensorInfo;
            return temp;
        }
        throw InvalidArgumentException("Can't dereference a null pointer");
    }
Referenced by LstmInputParamsInfo::GetCellBias(), LstmInputParamsInfo::GetCellLayerNormWeights(), LstmInputParamsInfo::GetCellToForgetWeights(), LstmInputParamsInfo::GetCellToInputWeights(), LstmInputParamsInfo::GetCellToOutputWeights(), LstmInputParamsInfo::GetForgetGateBias(), LstmInputParamsInfo::GetForgetLayerNormWeights(), LstmInputParamsInfo::GetInputGateBias(), LstmInputParamsInfo::GetInputLayerNormWeights(), LstmInputParamsInfo::GetInputToCellWeights(), LstmInputParamsInfo::GetInputToForgetWeights(), LstmInputParamsInfo::GetInputToInputWeights(), LstmInputParamsInfo::GetInputToOutputWeights(), LstmInputParamsInfo::GetOutputGateBias(), LstmInputParamsInfo::GetOutputLayerNormWeights(), LstmInputParamsInfo::GetProjectionBias(), LstmInputParamsInfo::GetProjectionWeights(), LstmInputParamsInfo::GetRecurrentToCellWeights(), LstmInputParamsInfo::GetRecurrentToForgetWeights(), LstmInputParamsInfo::GetRecurrentToInputWeights(), and LstmInputParamsInfo::GetRecurrentToOutputWeights().
GetCellBias()
const TensorInfo & GetCellBias () const inline
Definition at line 173 of file LstmParams.hpp.
    {
        return Deref(m_CellBias);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_CellBias.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetCellLayerNormWeights()
const TensorInfo & GetCellLayerNormWeights () const inline
Definition at line 197 of file LstmParams.hpp.
    {
        return Deref(m_CellLayerNormWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_CellLayerNormWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetCellToForgetWeights()
const TensorInfo & GetCellToForgetWeights () const inline
Definition at line 157 of file LstmParams.hpp.
    {
        return Deref(m_CellToForgetWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_CellToForgetWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetCellToInputWeights()
const TensorInfo & GetCellToInputWeights () const inline
Definition at line 153 of file LstmParams.hpp.
    {
        return Deref(m_CellToInputWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_CellToInputWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetCellToOutputWeights()
const TensorInfo & GetCellToOutputWeights () const inline
Definition at line 161 of file LstmParams.hpp.
    {
        return Deref(m_CellToOutputWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_CellToOutputWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetForgetGateBias()
const TensorInfo & GetForgetGateBias () const inline
Definition at line 169 of file LstmParams.hpp.
    {
        return Deref(m_ForgetGateBias);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_ForgetGateBias.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetForgetLayerNormWeights()
const TensorInfo & GetForgetLayerNormWeights () const inline
Definition at line 193 of file LstmParams.hpp.
    {
        return Deref(m_ForgetLayerNormWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_ForgetLayerNormWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetInputGateBias()
const TensorInfo & GetInputGateBias () const inline
Definition at line 165 of file LstmParams.hpp.
    {
        return Deref(m_InputGateBias);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_InputGateBias.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetInputLayerNormWeights()
const TensorInfo & GetInputLayerNormWeights () const inline
Definition at line 189 of file LstmParams.hpp.
    {
        return Deref(m_InputLayerNormWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_InputLayerNormWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetInputToCellWeights()
const TensorInfo & GetInputToCellWeights () const inline
Definition at line 129 of file LstmParams.hpp.
    {
        return Deref(m_InputToCellWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_InputToCellWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetInputToForgetWeights()
const TensorInfo & GetInputToForgetWeights () const inline
Definition at line 125 of file LstmParams.hpp.
    {
        return Deref(m_InputToForgetWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_InputToForgetWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetInputToInputWeights()
const TensorInfo & GetInputToInputWeights () const inline
Definition at line 121 of file LstmParams.hpp.
    {
        return Deref(m_InputToInputWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_InputToInputWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetInputToOutputWeights()
const TensorInfo & GetInputToOutputWeights () const inline
Definition at line 133 of file LstmParams.hpp.
    {
        return Deref(m_InputToOutputWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_InputToOutputWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetOutputGateBias()
const TensorInfo & GetOutputGateBias () const inline
Definition at line 177 of file LstmParams.hpp.
    {
        return Deref(m_OutputGateBias);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_OutputGateBias.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetOutputLayerNormWeights()
const TensorInfo & GetOutputLayerNormWeights () const inline
Definition at line 201 of file LstmParams.hpp.
    {
        return Deref(m_OutputLayerNormWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_OutputLayerNormWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetProjectionBias()
const TensorInfo & GetProjectionBias () const inline
Definition at line 185 of file LstmParams.hpp.
    {
        return Deref(m_ProjectionBias);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_ProjectionBias.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetProjectionWeights()
const TensorInfo & GetProjectionWeights () const inline
Definition at line 181 of file LstmParams.hpp.
    {
        return Deref(m_ProjectionWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_ProjectionWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetRecurrentToCellWeights()
const TensorInfo & GetRecurrentToCellWeights () const inline
Definition at line 145 of file LstmParams.hpp.
    {
        return Deref(m_RecurrentToCellWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_RecurrentToCellWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetRecurrentToForgetWeights()
const TensorInfo & GetRecurrentToForgetWeights () const inline
Definition at line 141 of file LstmParams.hpp.
    {
        return Deref(m_RecurrentToForgetWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_RecurrentToForgetWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetRecurrentToInputWeights()
const TensorInfo & GetRecurrentToInputWeights () const inline
Definition at line 137 of file LstmParams.hpp.
    {
        return Deref(m_RecurrentToInputWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_RecurrentToInputWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
GetRecurrentToOutputWeights()
const TensorInfo & GetRecurrentToOutputWeights () const inline
Definition at line 149 of file LstmParams.hpp.
    {
        return Deref(m_RecurrentToOutputWeights);
    }
References LstmInputParamsInfo::Deref(), and LstmInputParamsInfo::m_RecurrentToOutputWeights.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
Member Data Documentation
m_CellBias
const TensorInfo* m_CellBias
Definition at line 102 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetCellBias().
m_CellLayerNormWeights
const TensorInfo* m_CellLayerNormWeights
Definition at line 108 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetCellLayerNormWeights().
m_CellToForgetWeights
const TensorInfo* m_CellToForgetWeights
Definition at line 98 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetCellToForgetWeights().
m_CellToInputWeights
const TensorInfo* m_CellToInputWeights
Definition at line 97 of file LstmParams.hpp.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), LstmInputParamsInfo::GetCellToInputWeights(), and armnn::NeonQLstmWorkloadValidate().
m_CellToOutputWeights
const TensorInfo* m_CellToOutputWeights
Definition at line 99 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetCellToOutputWeights().
m_ForgetGateBias
const TensorInfo* m_ForgetGateBias
Definition at line 101 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetForgetGateBias().
m_ForgetLayerNormWeights
const TensorInfo* m_ForgetLayerNormWeights
Definition at line 107 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetForgetLayerNormWeights().
m_InputGateBias
const TensorInfo* m_InputGateBias
Definition at line 100 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetInputGateBias().
m_InputLayerNormWeights
const TensorInfo* m_InputLayerNormWeights
Definition at line 106 of file LstmParams.hpp.
Referenced by armnn::ClQLstmWorkloadValidate(), LstmInputParamsInfo::GetInputLayerNormWeights(), and armnn::NeonQLstmWorkloadValidate().
m_InputToCellWeights
const TensorInfo* m_InputToCellWeights
Definition at line 91 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetInputToCellWeights().
m_InputToForgetWeights
const TensorInfo* m_InputToForgetWeights
Definition at line 90 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetInputToForgetWeights().
m_InputToInputWeights
const TensorInfo* m_InputToInputWeights
Definition at line 89 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetInputToInputWeights().
m_InputToOutputWeights
const TensorInfo* m_InputToOutputWeights
Definition at line 92 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetInputToOutputWeights().
m_OutputGateBias
const TensorInfo* m_OutputGateBias
Definition at line 103 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetOutputGateBias().
m_OutputLayerNormWeights
const TensorInfo* m_OutputLayerNormWeights
Definition at line 109 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetOutputLayerNormWeights().
m_ProjectionBias
const TensorInfo* m_ProjectionBias
Definition at line 105 of file LstmParams.hpp.
Referenced by armnn::ClLstmFloatWorkloadValidate(), armnn::ClQLstmWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), LstmInputParamsInfo::GetProjectionBias(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::NeonLstmFloatWorkloadValidate(), armnn::NeonQLstmWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), and armnn::NeonUnidirectionalSequenceLstmWorkloadValidate().
m_ProjectionWeights
const TensorInfo* m_ProjectionWeights
Definition at line 104 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetProjectionWeights().
m_RecurrentToCellWeights
const TensorInfo* m_RecurrentToCellWeights
Definition at line 95 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetRecurrentToCellWeights().
m_RecurrentToForgetWeights
const TensorInfo* m_RecurrentToForgetWeights
Definition at line 94 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetRecurrentToForgetWeights().
m_RecurrentToInputWeights
const TensorInfo* m_RecurrentToInputWeights
Definition at line 93 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetRecurrentToInputWeights().
m_RecurrentToOutputWeights
const TensorInfo* m_RecurrentToOutputWeights
Definition at line 96 of file LstmParams.hpp.
Referenced by LstmInputParamsInfo::GetRecurrentToOutputWeights().
The documentation for this struct was generated from the following file:
include/armnn/LstmParams.hpp