Arm NN: QuantizedLstmInputParamsInfo Struct Reference
QuantizedLstmInputParamsInfo Struct Reference
#include <QuantizedLstmParams.hpp>
Public Member Functions
QuantizedLstmInputParamsInfo ()
const TensorInfo & Deref (const TensorInfo *tensorInfo) const
const TensorInfo & GetInputToInputWeights () const
const TensorInfo & GetInputToForgetWeights () const
const TensorInfo & GetInputToCellWeights () const
const TensorInfo & GetInputToOutputWeights () const
const TensorInfo & GetRecurrentToInputWeights () const
const TensorInfo & GetRecurrentToForgetWeights () const
const TensorInfo & GetRecurrentToCellWeights () const
const TensorInfo & GetRecurrentToOutputWeights () const
const TensorInfo & GetInputGateBias () const
const TensorInfo & GetForgetGateBias () const
const TensorInfo & GetCellBias () const
const TensorInfo & GetOutputGateBias () const
Public Attributes
const TensorInfo * m_InputToInputWeights
const TensorInfo * m_InputToForgetWeights
const TensorInfo * m_InputToCellWeights
const TensorInfo * m_InputToOutputWeights
const TensorInfo * m_RecurrentToInputWeights
const TensorInfo * m_RecurrentToForgetWeights
const TensorInfo * m_RecurrentToCellWeights
const TensorInfo * m_RecurrentToOutputWeights
const TensorInfo * m_InputGateBias
const TensorInfo * m_ForgetGateBias
const TensorInfo * m_CellBias
const TensorInfo * m_OutputGateBias
Detailed Description
Definition at line 119 of file QuantizedLstmParams.hpp.
Constructor & Destructor Documentation
QuantizedLstmInputParamsInfo()
QuantizedLstmInputParamsInfo () inline
Definition at line 121 of file QuantizedLstmParams.hpp.
        : m_InputToInputWeights(nullptr)
        , m_InputToForgetWeights(nullptr)
        , m_InputToCellWeights(nullptr)
        , m_InputToOutputWeights(nullptr)
        , m_RecurrentToInputWeights(nullptr)
        , m_RecurrentToForgetWeights(nullptr)
        , m_RecurrentToCellWeights(nullptr)
        , m_RecurrentToOutputWeights(nullptr)
        , m_InputGateBias(nullptr)
        , m_ForgetGateBias(nullptr)
        , m_CellBias(nullptr)
        , m_OutputGateBias(nullptr)
    {
    }
Member Function Documentation
Deref()
const TensorInfo & Deref (const TensorInfo * tensorInfo) const inline
Definition at line 155 of file QuantizedLstmParams.hpp.
    {
        if (tensorInfo != nullptr)
        {
            const TensorInfo &temp = *tensorInfo;
            return temp;
        }
        throw InvalidArgumentException("Can't dereference a null pointer");
    }
Referenced by QuantizedLstmInputParamsInfo::GetCellBias(), QuantizedLstmInputParamsInfo::GetForgetGateBias(), QuantizedLstmInputParamsInfo::GetInputGateBias(), QuantizedLstmInputParamsInfo::GetInputToCellWeights(), QuantizedLstmInputParamsInfo::GetInputToForgetWeights(), QuantizedLstmInputParamsInfo::GetInputToInputWeights(), QuantizedLstmInputParamsInfo::GetInputToOutputWeights(), QuantizedLstmInputParamsInfo::GetOutputGateBias(), QuantizedLstmInputParamsInfo::GetRecurrentToCellWeights(), QuantizedLstmInputParamsInfo::GetRecurrentToForgetWeights(), QuantizedLstmInputParamsInfo::GetRecurrentToInputWeights(), and QuantizedLstmInputParamsInfo::GetRecurrentToOutputWeights().
GetCellBias()
const TensorInfo & GetCellBias () const inline
Definition at line 207 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_CellBias);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_CellBias.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetForgetGateBias()
const TensorInfo & GetForgetGateBias () const inline
Definition at line 203 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_ForgetGateBias);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_ForgetGateBias.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetInputGateBias()
const TensorInfo & GetInputGateBias () const inline
Definition at line 199 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_InputGateBias);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_InputGateBias.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetInputToCellWeights()
const TensorInfo & GetInputToCellWeights () const inline
Definition at line 173 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_InputToCellWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_InputToCellWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetInputToForgetWeights()
const TensorInfo & GetInputToForgetWeights () const inline
Definition at line 169 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_InputToForgetWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_InputToForgetWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetInputToInputWeights()
const TensorInfo & GetInputToInputWeights () const inline
Definition at line 165 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_InputToInputWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_InputToInputWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetInputToOutputWeights()
const TensorInfo & GetInputToOutputWeights () const inline
Definition at line 177 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_InputToOutputWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_InputToOutputWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetOutputGateBias()
const TensorInfo & GetOutputGateBias () const inline
Definition at line 211 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_OutputGateBias);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_OutputGateBias.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetRecurrentToCellWeights()
const TensorInfo & GetRecurrentToCellWeights () const inline
Definition at line 190 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_RecurrentToCellWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_RecurrentToCellWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetRecurrentToForgetWeights()
const TensorInfo & GetRecurrentToForgetWeights () const inline
Definition at line 186 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_RecurrentToForgetWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_RecurrentToForgetWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetRecurrentToInputWeights()
const TensorInfo & GetRecurrentToInputWeights () const inline
Definition at line 182 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_RecurrentToInputWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_RecurrentToInputWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
GetRecurrentToOutputWeights()
const TensorInfo & GetRecurrentToOutputWeights () const inline
Definition at line 194 of file QuantizedLstmParams.hpp.
    {
        return Deref(m_RecurrentToOutputWeights);
    }
References QuantizedLstmInputParamsInfo::Deref(), and QuantizedLstmInputParamsInfo::m_RecurrentToOutputWeights.
Referenced by armnn::ClQuantizedLstmWorkloadValidate(), and armnn::NeonQuantizedLstmWorkloadValidate().
Member Data Documentation
m_CellBias
const TensorInfo* m_CellBias
Definition at line 151 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetCellBias().
m_ForgetGateBias
const TensorInfo* m_ForgetGateBias
Definition at line 150 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetForgetGateBias().
m_InputGateBias
const TensorInfo* m_InputGateBias
Definition at line 149 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetInputGateBias().
m_InputToCellWeights
const TensorInfo* m_InputToCellWeights
Definition at line 141 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetInputToCellWeights().
m_InputToForgetWeights
const TensorInfo* m_InputToForgetWeights
Definition at line 140 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetInputToForgetWeights().
m_InputToInputWeights
const TensorInfo* m_InputToInputWeights
Definition at line 139 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetInputToInputWeights().
m_InputToOutputWeights
const TensorInfo* m_InputToOutputWeights
Definition at line 142 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetInputToOutputWeights().
m_OutputGateBias
const TensorInfo* m_OutputGateBias
Definition at line 152 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetOutputGateBias().
m_RecurrentToCellWeights
const TensorInfo* m_RecurrentToCellWeights
Definition at line 146 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetRecurrentToCellWeights().
m_RecurrentToForgetWeights
const TensorInfo* m_RecurrentToForgetWeights
Definition at line 145 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetRecurrentToForgetWeights().
m_RecurrentToInputWeights
const TensorInfo* m_RecurrentToInputWeights
Definition at line 144 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetRecurrentToInputWeights().
m_RecurrentToOutputWeights
const TensorInfo* m_RecurrentToOutputWeights
Definition at line 147 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParamsInfo::GetRecurrentToOutputWeights().
The documentation for this struct was generated from the following file:
include/armnn/QuantizedLstmParams.hpp