Arm NN: ViewsDescriptor Struct Reference
ViewsDescriptor Struct Reference
A ViewsDescriptor for the SplitterLayer.
#include <Descriptors.hpp>
Public Member Functions
ViewsDescriptor (uint32_t numViews, uint32_t numDimensions=4)
ViewsDescriptor (const ViewsDescriptor &other)
ViewsDescriptor ()
ViewsDescriptor (ViewsDescriptor &&other)
~ViewsDescriptor ()
ViewsDescriptor & operator= (ViewsDescriptor rhs)
bool operator== (const ViewsDescriptor &rhs) const
Status SetViewOriginCoord (uint32_t view, uint32_t coord, uint32_t value)
@Brief Set the view origin coordinates.
Status SetViewSize (uint32_t view, uint32_t coord, uint32_t value)
Set the size of the views.
uint32_t GetNumViews () const
Get the number of views.
uint32_t GetNumDimensions () const
Get the number of dimensions.
const uint32_t * GetViewOrigin (uint32_t idx) const
Get the view origin at the int value idx.
const uint32_t * GetViewSizes (uint32_t idx) const
Get the view sizes at the int value idx.
const OriginsDescriptor & GetOrigins () const
Get the View Origins.
void SetAxis (int32_t axis)
Set the axis value.
int32_t GetAxis () const
Get the axis value.
bool HasAxis () const
Returns true if an axis has been set.
Public Member Functions inherited from BaseDescriptor
virtual bool IsNull () const
virtual ~BaseDescriptor ()=default
Friends
void swap (ViewsDescriptor &first, ViewsDescriptor &second)
Swap the ViewsDescriptor value first and second.
Detailed Description
A ViewsDescriptor for the SplitterLayer.
Descriptor to configure the splitting process. Number of Views must be equal to the number of outputs, and their order must match - e.g. first view corresponds to the first output, second view to the second output, etc.
Definition at line 244 of file Descriptors.hpp.
Constructor & Destructor Documentation
ViewsDescriptor() [1/4]
ViewsDescriptor (uint32_t numViews, uint32_t numDimensions = 4)
Definition at line 224 of file Descriptors.cpp.
    : m_Origins(numViews, numDimensions)
    , m_ViewSizes(numViews > 0 && numDimensions > 0 ?
                      new uint32_t *[numViews]() : nullptr)
    , m_IsAxisSet(false)
    , m_Axis(0)
{
    if (m_ViewSizes)
    {
        for (uint32_t i = 0; GetNumDimensions() > 0 && i < GetNumViews(); ++i)
        {
            m_ViewSizes[i] = new uint32_t[GetNumDimensions()]();
        }
    }
}
References ViewsDescriptor::GetNumDimensions(), and ViewsDescriptor::GetNumViews().
ViewsDescriptor() [2/4]
ViewsDescriptor (const ViewsDescriptor & other)
Definition at line 240 of file Descriptors.cpp.
    : m_Origins(other.m_Origins)
    , m_ViewSizes(other.GetNumViews() > 0 && other.GetNumDimensions() > 0 ?
                      new uint32_t *[other.GetNumViews()]() : nullptr)
    , m_IsAxisSet(other.m_IsAxisSet)
    , m_Axis(other.m_Axis)
{
    if (m_ViewSizes)
    {
        for (uint32_t i = 0; GetNumDimensions() > 0 && i < GetNumViews(); ++i)
        {
            m_ViewSizes[i] = new uint32_t[GetNumDimensions()]();
            memcpy(m_ViewSizes[i], other.m_ViewSizes[i], GetNumDimensions() * sizeof(uint32_t));
        }
    }
}
References ViewsDescriptor::GetNumDimensions(), and ViewsDescriptor::GetNumViews().
ViewsDescriptor() [3/4]
ViewsDescriptor ()
Definition at line 217 of file Descriptors.cpp.
: m_Origins()
, m_ViewSizes(nullptr)
, m_IsAxisSet(false)
, m_Axis(0)
{}
ViewsDescriptor() [4/4]
ViewsDescriptor (ViewsDescriptor && other)
Definition at line 257 of file Descriptors.cpp.
    : ViewsDescriptor()
{
    swap(*this, other);
}
References ViewsDescriptor::swap.
~ViewsDescriptor()
~ViewsDescriptor ()
Definition at line 263 of file Descriptors.cpp.
{
    if (m_ViewSizes)
    {
        for (uint32_t i = 0; GetNumDimensions() > 0 && i < GetNumViews(); ++i)
        {
            delete[] m_ViewSizes[i];
        }
        delete[] m_ViewSizes;
    }
}
References ViewsDescriptor::GetNumDimensions(), and ViewsDescriptor::GetNumViews().
Member Function Documentation
GetAxis()
int32_t GetAxis () const
Get the axis value.
Definition at line 382 of file Descriptors.cpp.
{
    return m_Axis;
}
Referenced by armnn::ComputeSplitAxis(), and StringifyLayerParameters< ViewsDescriptor >::Serialize().
GetNumDimensions()
uint32_t GetNumDimensions () const
Get the number of dimensions.
Definition at line 307 of file Descriptors.cpp.
{
    return m_Origins.GetNumDimensions();
}
References OriginsDescriptor::GetNumDimensions().
Referenced by ClSplitterWorkload::ClSplitterWorkload(), ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), armnn::ComputeSplitAxis(), SplitterLayer::CreateWorkload(), SplitterLayer::InferOutputShapes(), ClLayerSupport::IsSplitterSupported(), NeonLayerSupport::IsSplitterSupported(), NeonSplitterWorkload::NeonSplitterWorkload(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload(), ViewsDescriptor::operator==(), StringifyLayerParameters< ViewsDescriptor >::Serialize(), ViewsDescriptor::SetViewSize(), SplitterLayer::ValidateTensorShapesFromInputs(), ViewsDescriptor::ViewsDescriptor(), ViewsDescriptor::ViewsDescriptor(), and ViewsDescriptor::~ViewsDescriptor().
GetNumViews()
uint32_t GetNumViews () const
Get the number of views.
Definition at line 302 of file Descriptors.cpp.
{
    return m_Origins.GetNumViews();
}
References OriginsDescriptor::GetNumViews().
Referenced by armnn::ComputeSplitAxis(), ConvertSplitToTosaOperator(), SplitterLayer::CreateWorkload(), SplitterLayer::InferOutputShapes(), ViewsDescriptor::operator==(), StringifyLayerParameters< ViewsDescriptor >::Serialize(), ViewsDescriptor::SetViewSize(), SplitterLayer::ValidateTensorShapesFromInputs(), ViewsDescriptor::ViewsDescriptor(), ViewsDescriptor::ViewsDescriptor(), and ViewsDescriptor::~ViewsDescriptor().
GetOrigins()
const OriginsDescriptor & GetOrigins () const
Get the View Origins.
Definition at line 352 of file Descriptors.cpp.
{
    return m_Origins;
}
Referenced by StringifyLayerParameters< ViewsDescriptor >::Serialize().
GetViewOrigin()
const uint32_t * GetViewOrigin (uint32_t idx) const
Get the view origin at the int value idx.
Definition at line 312 of file Descriptors.cpp.
{
    return m_Origins.GetViewOrigin(idx);
}
References OriginsDescriptor::GetViewOrigin().
Referenced by SplitterLayer::CreateWorkload(), and ViewsDescriptor::operator==().
GetViewSizes()
const uint32_t * GetViewSizes (uint32_t idx) const
Get the view sizes at the int value idx.
Definition at line 347 of file Descriptors.cpp.
{
    return m_ViewSizes ? m_ViewSizes[idx] : nullptr;
}
Referenced by armnn::ComputeSplitAxis(), SplitterLayer::InferOutputShapes(), ViewsDescriptor::operator==(), StringifyLayerParameters< ViewsDescriptor >::Serialize(), and SplitterLayer::ValidateTensorShapesFromInputs().
HasAxis()
bool HasAxis () const
Returns true if an axis has been set.
Definition at line 388 of file Descriptors.cpp.
{
    return m_IsAxisSet;
}
Referenced by armnn::ComputeSplitAxis(), and StringifyLayerParameters< ViewsDescriptor >::Serialize().
operator=()
ViewsDescriptor & operator= (ViewsDescriptor rhs)
Definition at line 275 of file Descriptors.cpp.
{
    swap(*this, rhs);
    return *this;
}
References ViewsDescriptor::swap.
operator==()
bool operator== (const ViewsDescriptor & rhs) const
Definition at line 281 of file Descriptors.cpp.
{
    if (GetNumViews() != rhs.GetNumViews() || GetNumDimensions() != rhs.GetNumDimensions())
    {
        return false;
    }
    for (unsigned int i = 0u; i < GetNumViews(); ++i)
    {
        for (unsigned int j = 0u; j < GetNumDimensions(); ++j)
        {
            if (GetViewOrigin(i)[j] != rhs.GetViewOrigin(i)[j] || GetViewSizes(i)[j] != rhs.GetViewSizes(i)[j])
            {
                return false;
            }
        }
    }
    return true;
}
References ViewsDescriptor::GetNumDimensions(), ViewsDescriptor::GetNumViews(), ViewsDescriptor::GetViewOrigin(), and ViewsDescriptor::GetViewSizes().
SetAxis()
void SetAxis (int32_t axis)
Set the axis value.
Definition at line 375 of file Descriptors.cpp.
{
    m_Axis = axis;
    m_IsAxisSet = true;
}
SetViewOriginCoord()
Status SetViewOriginCoord (uint32_t view, uint32_t coord, uint32_t value)
@Brief Set the view origin coordinates.
The arguments are: view, dimension, value. If the view is greater than or equal to GetNumViews(), then the view argument is out of range. If the coord is greater than or equal to GetNumDimensions(), then the coord argument is out of range.
Definition at line 317 of file Descriptors.cpp.
{
    return m_Origins.SetViewOriginCoord(view, coord, value);
}
References OriginsDescriptor::SetViewOriginCoord().
Referenced by ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), and NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload().
SetViewSize()
Status SetViewSize (uint32_t view, uint32_t coord, uint32_t value)
Set the size of the views.
The arguments are: view, dimension, value. If the view is greater than or equal to GetNumViews(), then the view argument is out of range. If the coord is greater than or equal to GetNumDimensions(), then the coord argument is out of range.
Definition at line 322 of file Descriptors.cpp.
{
    if (!m_ViewSizes)
    {
        ARMNN_LOG(error) << "ViewsDescriptor::SetViewSize: invalid view sizes";
        return Status::Failure;
    }
    if (view >= GetNumViews())
    {
        ARMNN_LOG(error) << "ViewsDescriptor::SetViewSize: view argument:" << view <<
                                 " is out of range";
        return Status::Failure;
    }
    if (coord >= GetNumDimensions())
    {
        ARMNN_LOG(error) << "ViewsDescriptor::SetViewSize: coord argument:" << coord <<
                                 " is out of range";
        return Status::Failure;
    }
    m_ViewSizes[view][coord] = value;
    return Status::Success;
}
References ARMNN_LOG, armnn::error, armnn::Failure, ViewsDescriptor::GetNumDimensions(), ViewsDescriptor::GetNumViews(), and armnn::Success.
Referenced by ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), and NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload().
Friends And Related Symbol Documentation
swap
void swap (ViewsDescriptor & first, ViewsDescriptor & second) friend
Swap the ViewsDescriptor value first and second.
Definition at line 366 of file Descriptors.cpp.
{
    using std::swap;
    swap(first.m_Origins, second.m_Origins);
    swap(first.m_ViewSizes, second.m_ViewSizes);
    swap(first.m_IsAxisSet, second.m_IsAxisSet);
    swap(first.m_Axis, second.m_Axis);
}
Referenced by ViewsDescriptor::operator=(), and ViewsDescriptor::ViewsDescriptor().
The documentation for this struct was generated from the following files:
include/armnn/Descriptors.hpp
src/armnn/Descriptors.cpp