ArmNN: src/backends/backendsCommon/test/layerTests/DebugTestImpl.cpp File Reference
DebugTestImpl.cpp File Reference
#include "DebugTestImpl.hpp"
#include <armnnUtils/QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
#include <doctest/doctest.h>
Functions
LayerTestResult< float, 4 > Debug4dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 3 > Debug3dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 2 > Debug2dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 1 > Debug1dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 4 > Debug4dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 3 > Debug3dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 2 > Debug2dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 1 > Debug1dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > Debug4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 3 > Debug3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 2 > Debug2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 1 > Debug1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > Debug4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 3 > Debug3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 2 > Debug2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 1 > Debug1dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
Debug1dBFloat16Test()
LayerTestResult<armnn::BFloat16, 1> Debug1dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 337 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug1dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug1dFloat32Test()
LayerTestResult<float, 1> Debug1dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 309 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug1dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug1dInt16Test()
LayerTestResult<int16_t, 1> Debug1dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 393 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug1dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug1dUint8Test()
LayerTestResult<uint8_t, 1> Debug1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 365 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug1dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Debug2dBFloat16Test()
LayerTestResult<armnn::BFloat16, 2> Debug2dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 330 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug2dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug2dFloat32Test()
LayerTestResult<float, 2> Debug2dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 302 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug2dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug2dInt16Test()
LayerTestResult<int16_t, 2> Debug2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 386 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug2dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug2dUint8Test()
LayerTestResult<uint8_t, 2> Debug2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 358 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug2dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Debug3dBFloat16Test()
LayerTestResult<armnn::BFloat16, 3> Debug3dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 323 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug3dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug3dFloat32Test()
LayerTestResult<float, 3> Debug3dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 295 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug3dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug3dInt16Test()
LayerTestResult<int16_t, 3> Debug3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 379 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug3dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug3dUint8Test()
LayerTestResult<uint8_t, 3> Debug3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 351 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug3dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Debug4dBFloat16Test()
LayerTestResult<armnn::BFloat16, 4> Debug4dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 316 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug4dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug4dFloat32Test()
LayerTestResult<float, 4> Debug4dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 288 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug4dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug4dInt16Test()
LayerTestResult<int16_t, 4> Debug4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 372 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug4dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug4dUint8Test()
LayerTestResult<uint8_t, 4> Debug4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 344 of file DebugTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Debug4dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }