var _exceptions_8hpp =
[
    [ "CheckLocation", "structarmnn_1_1_check_location.xhtml", "structarmnn_1_1_check_location" ],
    [ "Exception", "classarmnn_1_1_exception.xhtml", "classarmnn_1_1_exception" ],
    [ "BackendUnavailableException", "classarmnn_1_1_backend_unavailable_exception.xhtml", null ],
    [ "ClRuntimeUnavailableException", "classarmnn_1_1_cl_runtime_unavailable_exception.xhtml", null ],
    [ "InvalidArgumentException", "classarmnn_1_1_invalid_argument_exception.xhtml", null ],
    [ "FileNotFoundException", "classarmnn_1_1_file_not_found_exception.xhtml", null ],
    [ "ParseException", "classarmnn_1_1_parse_exception.xhtml", null ],
    [ "UnimplementedException", "classarmnn_1_1_unimplemented_exception.xhtml", "classarmnn_1_1_unimplemented_exception" ],
    [ "LayerValidationException", "classarmnn_1_1_layer_validation_exception.xhtml", null ],
    [ "GraphValidationException", "classarmnn_1_1_graph_validation_exception.xhtml", null ],
    [ "BadOptionalAccessException", "classarmnn_1_1_bad_optional_access_exception.xhtml", null ],
    [ "RuntimeException", "classarmnn_1_1_runtime_exception.xhtml", null ],
    [ "MemoryImportException", "classarmnn_1_1_memory_import_exception.xhtml", null ],
    [ "MemoryExportException", "classarmnn_1_1_memory_export_exception.xhtml", null ],
    [ "TimeoutException", "classarmnn_1_1_timeout_exception.xhtml", null ],
    [ "BackendProfilingException", "classarmnn_1_1_backend_profiling_exception.xhtml", null ],
    [ "PolymorphicDowncastException", "classarmnn_1_1_polymorphic_downcast_exception.xhtml", null ],
    [ "NullPointerException", "classarmnn_1_1_null_pointer_exception.xhtml", null ],
    [ "BackendCapabilityException", "classarmnn_1_1_backend_capability_exception.xhtml", null ],
    [ "MemoryValidationException", "classarmnn_1_1_memory_validation_exception.xhtml", null ],
    [ "CHECK_LOCATION", "_exceptions_8hpp.xhtml#aa3be76aec4ce713822a5ea1ecbb7bc61", null ],
    [ "ConditionalThrow", "_exceptions_8hpp.xhtml#ae4ab3bf0697ad13316a6bcba0a8fade5", null ],
    [ "ConditionalThrow", "_exceptions_8hpp.xhtml#a6ed414c05eb6d4c89e0e4a475a0479c0", null ],
    [ "ConditionalThrowIfNotEqual", "_exceptions_8hpp.xhtml#ae57b7f9e2cb7080bf10b28d1f72b558e", null ]
];