ArmNN: src/backends/backendsCommon/test/layerTests/Pooling3dTestImpl.hpp File Reference
Pooling3dTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <armnn/Types.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 5 > SimpleMaxPooling3dSize2x2x2Stride1x1x1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > SimpleMaxPooling3dSize2x2x2Stride1x1x1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > SimpleMaxPooling3dSize2x2x2Stride1x1x1Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > SimpleMaxPooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > IgnorePaddingSimpleMaxPooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > IgnorePaddingSimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > IgnorePaddingSimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > SimpleAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > LargeTensorsAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > LargeTensorsAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > LargeTensorsAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > IgnorePaddingSimpleAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > IgnorePaddingSimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > IgnorePaddingSimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > SimpleL2Pooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > IgnorePaddingSimpleL2Pooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > IgnorePaddingSimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > IgnorePaddingSimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > AsymmetricNonSquareMaxPooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareMaxPooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareMaxPooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > AsymmetricNonSquareAveragePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareAveragePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareAveragePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > AsymmetricNonSquareL2Pooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 5 > AsymmetricNonSquareL2Pooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 5 > AsymmetricNonSquareL2Pooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > ComparePooling3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
LayerTestResult< uint8_t, 5 > ComparePooling3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
LayerTestResult< int16_t, 5 > ComparePooling3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Function Documentation
AsymmetricNonSquareAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1338 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareAveragePooling3dTest()
LayerTestResult<float, 5> AsymmetricNonSquareAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1320 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1329 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareL2Pooling3dInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareL2Pooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1365 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareL2Pooling3dTest()
LayerTestResult<float, 5> AsymmetricNonSquareL2Pooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1347 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareL2Pooling3dUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareL2Pooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1356 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareL2Pooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareMaxPooling3dInt16Test()
LayerTestResult<int16_t, 5> AsymmetricNonSquareMaxPooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1311 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareMaxPooling3dTest()
LayerTestResult<float, 5> AsymmetricNonSquareMaxPooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1293 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
AsymmetricNonSquareMaxPooling3dUint8Test()
LayerTestResult<uint8_t, 5> AsymmetricNonSquareMaxPooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1302 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return AsymmetricNonSquareMaxPooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
ComparePooling3dInt16Test()
LayerTestResult<int16_t, 5> ComparePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Definition at line 1399 of file Pooling3dTestImpl.cpp.
 {
     return ComparePooling3dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, poolingType);
 }
ComparePooling3dTest()
LayerTestResult<float, 5> ComparePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Definition at line 1374 of file Pooling3dTestImpl.cpp.
 {
     return ComparePooling3dTestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, poolingType);
 }
ComparePooling3dUint8Test()
LayerTestResult<uint8_t, 5> ComparePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory, armnn::PoolingAlgorithm poolingType)
Definition at line 1386 of file Pooling3dTestImpl.cpp.
 {
     return ComparePooling3dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager,  refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory,
         poolingType, 0.1f, 128);
 }
IgnorePaddingSimpleAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> IgnorePaddingSimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1257 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling3dTest()
LayerTestResult<float, 5> IgnorePaddingSimpleAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1239 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> IgnorePaddingSimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1248 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -5);
 }
IgnorePaddingSimpleL2Pooling3dInt16Test()
LayerTestResult<int16_t, 5> IgnorePaddingSimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1284 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleL2Pooling3dTest()
LayerTestResult<float, 5> IgnorePaddingSimpleL2Pooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1266 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleL2Pooling3dUint8Test()
LayerTestResult<uint8_t, 5> IgnorePaddingSimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1275 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleL2Pooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -5);
 }
IgnorePaddingSimpleMaxPooling3dInt16Test()
LayerTestResult<int16_t, 5> IgnorePaddingSimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1143 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleMaxPooling3dTest()
LayerTestResult<float, 5> IgnorePaddingSimpleMaxPooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1125 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
IgnorePaddingSimpleMaxPooling3dUint8Test()
LayerTestResult<uint8_t, 5> IgnorePaddingSimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1134 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return IgnorePaddingSimpleMaxPooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, -5);
 }
LargeTensorsAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> LargeTensorsAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1230 of file Pooling3dTestImpl.cpp.
 {
     return LargeTensorsAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
LargeTensorsAveragePooling3dTest()
LayerTestResult<float, 5> LargeTensorsAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1212 of file Pooling3dTestImpl.cpp.
 {
     return LargeTensorsAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
LargeTensorsAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> LargeTensorsAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1221 of file Pooling3dTestImpl.cpp.
 {
     return LargeTensorsAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5, -1);
 }
SimpleAveragePooling3dInt16Test()
LayerTestResult<int16_t, 5> SimpleAveragePooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1172 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleAveragePooling3dTest()
LayerTestResult<float, 5> SimpleAveragePooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1152 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleAveragePooling3dUint8Test()
LayerTestResult<uint8_t, 5> SimpleAveragePooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1162 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleAveragePooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling3dInt16Test()
LayerTestResult<int16_t, 5> SimpleL2Pooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1202 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling3dTest()
LayerTestResult<float, 5> SimpleL2Pooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1182 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleL2Pooling3dUint8Test()
LayerTestResult<uint8_t, 5> SimpleL2Pooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1192 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleL2Pooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dInt16Test()
LayerTestResult<int16_t, 5> SimpleMaxPooling3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1115 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dTestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dSize2x2x2Stride1x1x1Int16Test()
LayerTestResult<int16_t, 5> SimpleMaxPooling3dSize2x2x2Stride1x1x1Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1086 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dSize2x2x2Stride1x1x1TestCommon<armnn::DataType::QSymmS16>(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
SimpleMaxPooling3dSize2x2x2Stride1x1x1Test()
LayerTestResult<float, 5> SimpleMaxPooling3dSize2x2x2Stride1x1x1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1068 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dSize2x2x2Stride1x1x1TestCommon<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory);
 }
SimpleMaxPooling3dSize2x2x2Stride1x1x1Uint8Test()
LayerTestResult<uint8_t, 5> SimpleMaxPooling3dSize2x2x2Stride1x1x1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1077 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dSize2x2x2Stride1x1x1TestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.1f, 128);
 }
SimpleMaxPooling3dTest()
LayerTestResult<float, 5> SimpleMaxPooling3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1095 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }
SimpleMaxPooling3dUint8Test()
LayerTestResult<uint8_t, 5> SimpleMaxPooling3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout dataLayout)
Definition at line 1105 of file Pooling3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleMaxPooling3dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, dataLayout);
 }