ArmNN: src/armnnTestUtils/DataTypeUtils.hpp File Reference
DataTypeUtils.hpp File Reference
#include <ResolveType.hpp>
#include <reference/workloads/Encoders.hpp>
#include <vector>
Functions
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
std::vector< T > ConvertToDataType (const std::vector< float > &input, const armnn::TensorInfo &inputTensorInfo)
template<typename T >
T ConvertToDataType (const float &value, const armnn::TensorInfo &tensorInfo)
Function Documentation
ConvertToDataType() [1/2]
std::vector<T> ConvertToDataType (const std::vector< float > & input, const armnn::TensorInfo & inputTensorInfo)
Definition at line 17 of file DataTypeUtils.hpp.
References Encoder< IType >::Set(), and TensorInfo::SetDataType().
 {
     std::vector<T> output(input.size());
     auto outputTensorInfo = inputTensorInfo;
     outputTensorInfo.SetDataType(ArmnnType);
     std::unique_ptr<armnn::Encoder<float>> pOutputEncoder = armnn::MakeEncoder<float>(outputTensorInfo, output.data());
     armnn::Encoder<float>& rOutputEncoder = *pOutputEncoder;
     for (auto it = input.begin(); it != input.end(); ++it)
     {
         rOutputEncoder.Set(*it);
         ++rOutputEncoder;
     }
     return output;
 }
ConvertToDataType() [2/2]
T ConvertToDataType (const float & value, const armnn::TensorInfo & tensorInfo)
Definition at line 37 of file DataTypeUtils.hpp.
References Encoder< IType >::Set().
 {
     std::vector<T> output(1);
     std::unique_ptr<armnn::Encoder<float>> pEncoder = armnn::MakeEncoder<float>(tensorInfo, output.data());
     armnn::Encoder<float>& rEncoder = *pEncoder;
     rEncoder.Set(value);
     return output[0];
 }