ArmNN: NeonTransposeWorkload Class Reference
NeonTransposeWorkload Class Reference
#include <NeonTransposeWorkload.hpp>
Public Member Functions
NeonTransposeWorkload (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info)
void Execute () const override
Public Member Functions inherited from NeonBaseWorkload< TransposeQueueDescriptor >
NeonBaseWorkload (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< TransposeQueueDescriptor >
BaseWorkload (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const TransposeQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Static Public Member Functions
static const std::string & GetName ()
Additional Inherited Members
Protected Member Functions inherited from NeonBaseWorkload< TransposeQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< TransposeQueueDescriptor >
TransposeQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 22 of file NeonTransposeWorkload.hpp.
Constructor & Destructor Documentation
NeonTransposeWorkload()
NeonTransposeWorkload (const TransposeQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 27 of file NeonTransposeWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, NeonTransposeWorkload::GetName(), BaseWorkload< TransposeQueueDescriptor >::m_Data, TransposeDescriptor::m_DimMappings, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and QueueDescriptor::ValidateInputsOutputs().
Referenced by NeonTransposeWorkload::GetName().
         : NeonBaseWorkload<TransposeQueueDescriptor>(descriptor, info)
 {
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonTransposeWorkload_Construct",
                                          descriptor.m_Parameters,
                                          info,
                                          this->GetGuid());
     m_Data.ValidateInputsOutputs(GetName(), 1, 1);
     const arm_compute::ITensor& input = static_cast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ITensor& output = static_cast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     const armnn::PermutationVector& mappings = m_Data.m_Parameters.m_DimMappings;
     // Run the layer.
     m_PermuteFunction.configure(&input, &output,
                                 armcomputetensorutils::BuildArmComputeTransposeVector(mappings));
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 48 of file NeonTransposeWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID, BaseWorkload< TransposeQueueDescriptor >::GetGuid(), and NeonTransposeWorkload::GetName().
Referenced by NeonTransposeWorkload::GetName().
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID(GetName() + "_Execute", this->GetGuid());
     m_PermuteFunction.run();
 }
GetName()
static const std::string& GetName () inline static
Definition at line 25 of file NeonTransposeWorkload.hpp.
References NeonTransposeWorkload::Execute(), armnn::info, and NeonTransposeWorkload::NeonTransposeWorkload().
Referenced by NeonTransposeWorkload::Execute(), and NeonTransposeWorkload::NeonTransposeWorkload().
     {
         static const std::string name = std::string("NeonTransposeWorkload");
         return name;
     }
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonTransposeWorkload.hpp
src/backends/neon/workloads/NeonTransposeWorkload.cpp