ArmNN: RefLayerSupport Class Reference
RefLayerSupport Class Reference
#include <RefLayerSupport.hpp>
Public Member Functions
bool IsLayerSupported (const LayerType &type, const std::vector< TensorInfo > &infos, const BaseDescriptor &descriptor, const Optional< LstmInputParamsInfo > &lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > &, Optional< std::string &> reasonIfUnsupported) const override
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const ComparisonDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo *> inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertBf16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToBf16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDebugSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDetectionPostProcessSupported (const TensorInfo &boxEncodings, const TensorInfo &scores, const TensorInfo &anchors, const TensorInfo &detectionBoxes, const TensorInfo &detectionClasses, const TensorInfo &detectionScores, const TensorInfo &numDetections, const DetectionPostProcessDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFakeQuantizationSupported (const TensorInfo &input, const FakeQuantizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFillSupported (const TensorInfo &input, const TensorInfo &output, const FillDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMemCopySupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsRankSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsShapeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo *> &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &output, const Optional< TensorInfo > &hiddenStateOutput, const Optional< TensorInfo > &cellStateOutput, const UnidirectionalSequenceLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
Public Member Functions inherited from LayerSupportBase
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const ComparisonDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo *> inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertBf16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToBf16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDebugSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDetectionPostProcessSupported (const TensorInfo &boxEncodings, const TensorInfo &scores, const TensorInfo &anchors, const TensorInfo &detectionBoxes, const TensorInfo &detectionClasses, const TensorInfo &detectionScores, const TensorInfo &numDetections, const DetectionPostProcessDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFakeQuantizationSupported (const TensorInfo &input, const FakeQuantizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMemCopySupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMemImportSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMergeSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPreCompiledSupported (const TensorInfo &input, const PreCompiledDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizedLstmSupported (const TensorInfo &input, const TensorInfo &previousCellStateIn, const TensorInfo &previousOutputIn, const TensorInfo &cellStateOut, const TensorInfo &output, const QuantizedLstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsRankSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsShapeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo *> &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStandInSupported (const std::vector< const TensorInfo *> &inputs, const std::vector< const TensorInfo *> &outputs, const StandInDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSwitchSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output0, const TensorInfo &output1, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &output, const Optional< TensorInfo > &hiddenStateOutput, const Optional< TensorInfo > &cellStateOutput, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
Public Member Functions inherited from ILayerSupport
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsActivationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsAdditionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsArgMinMaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsBatchNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsBatchToSpaceNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsCastSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsChannelShuffleSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsComparisonSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConvertBf16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConvertFp32ToBf16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConvertFp16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConvertFp32ToFp16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConvolution3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDebugSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDepthToSpaceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDequantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDetectionPostProcessSupported(const TensorInfo &boxEncodings
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDilatedDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsDivisionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsElementwiseUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsFakeQuantizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsFillSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsFloorSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsFullyConnectedSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsGatherSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsInputSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsInstanceNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsL2NormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsLogicalBinarySupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsLogicalUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsLogSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMaximumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMeanSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMemCopySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMemImportSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMergeSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMinimumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsMultiplicationSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsOutputSupported(const TensorInfo &output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsPadSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsPermuteSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsPooling2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsPooling3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsPreCompiledSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsPreluSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsQuantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsQLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsQuantizedLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsRankSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsReduceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsReshapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsResizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsShapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSliceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSpaceToBatchNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSpaceToDepthSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSplitterSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSubtractionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsSwitchSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsTransposeConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsTransposeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsUnidirectionalSequenceLstmSupported(const TensorInfo &input
Additional Inherited Members
Public Attributes inherited from ILayerSupport
const TensorInfo & output
const TensorInfo const ActivationDescriptor & descriptor
const TensorInfo const ActivationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & input1
const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ArgMinMaxDescriptor & descriptor
const TensorInfo const ArgMinMaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & mean
const TensorInfo const TensorInfo const TensorInfo & var
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & beta
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & gamma
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const BatchToSpaceNdDescriptor & descriptor
const TensorInfo const BatchToSpaceNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ChannelShuffleDescriptor & descriptor
const TensorInfo const ChannelShuffleDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const ComparisonDescriptor & descriptor
const TensorInfo const TensorInfo const ComparisonDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsConcatSupported(const std Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution2dDescriptor & descriptor
const TensorInfo const Convolution2dDescriptor const TensorInfo & weights
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution3dDescriptor & descriptor
const TensorInfo const Convolution3dDescriptor const TensorInfo & weights
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthToSpaceDescriptor & descriptor
const TensorInfo const DepthToSpaceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthwiseConvolution2dDescriptor & descriptor
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & scores
const TensorInfo const TensorInfo & anchors
const TensorInfo const TensorInfo const TensorInfo & detectionBoxes
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionClasses
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionScores
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & numDetections
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const =0
const TensorInfo const ElementwiseUnaryDescriptor & descriptor
const TensorInfo const ElementwiseUnaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const FakeQuantizationDescriptor & descriptor
const FakeQuantizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const FillDescriptor & descriptor
const TensorInfo const FillDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & weights
const TensorInfo const TensorInfo const TensorInfo & biases
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const GatherDescriptor & descriptor
const TensorInfo const TensorInfo const GatherDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const InstanceNormalizationDescriptor & descriptor
const TensorInfo const InstanceNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const L2NormalizationDescriptor & descriptor
const TensorInfo const L2NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const LogicalBinaryDescriptor & descriptor
const TensorInfo const TensorInfo const LogicalBinaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const LogSoftmaxDescriptor & descriptor
const TensorInfo const LogSoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & outputStateIn
const TensorInfo const TensorInfo & cellStateIn
const TensorInfo const TensorInfo const TensorInfo & scratchBuffer
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const MeanDescriptor & descriptor
const TensorInfo const MeanDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & ouput
const TensorInfo const NormalizationDescriptor & descriptor
const TensorInfo const NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PadDescriptor & descriptor
const TensorInfo const PadDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PermuteDescriptor & descriptor
const TensorInfo const PermuteDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling2dDescriptor & descriptor
const TensorInfo const Pooling2dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling3dDescriptor & descriptor
const TensorInfo const Pooling3dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const PreCompiledDescriptor & descriptor
const PreCompiledDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & alpha
const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReduceDescriptor & descriptor
const TensorInfo const ReduceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReshapeDescriptor & descriptor
const TensorInfo const ReshapeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ResizeDescriptor & descriptor
const TensorInfo const ResizeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SliceDescriptor & descriptor
const TensorInfo const SliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SoftmaxDescriptor & descriptor
const TensorInfo const SoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToBatchNdDescriptor & descriptor
const TensorInfo const SpaceToBatchNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToDepthDescriptor & descriptor
const TensorInfo const SpaceToDepthDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const std::vector< std::reference_wrapper< TensorInfo > > & outputs
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor & descriptor
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsStandInSupported(const std const TensorInfo & output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor & descriptor
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "22.11") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & output0
const TensorInfo const TensorInfo const TensorInfo & output1
const TensorInfo const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeConvolution2dDescriptor & descriptor
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeDescriptor & descriptor
const TensorInfo const TransposeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const Optional< TensorInfo > & hiddenStateOutput
const TensorInfo const TensorInfo const TensorInfo const Optional< TensorInfo > const Optional< TensorInfo > & cellStateOutput
const TensorInfo const TensorInfo const TensorInfo const Optional< TensorInfo > const Optional< TensorInfo > const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const Optional< TensorInfo > const Optional< TensorInfo > const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const Optional< TensorInfo > const Optional< TensorInfo > const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Protected Member Functions inherited from ILayerSupport
ILayerSupport ()
virtual ~ILayerSupport ()
Detailed Description
Definition at line 12 of file RefLayerSupport.hpp.
Member Function Documentation
IsActivationSupported()
bool IsActivationSupported (const TensorInfo & input, const TensorInfo & output, const ActivationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 543 of file RefLayerSupport.cpp.
References armnn::Abs, armnn::BFloat16, armnn::BoundedReLu, armnn::CheckSupportRule(), armnn::Elu, armnn::Float16, armnn::Float32, armnn::HardSwish, armnn::LeakyReLu, armnn::Linear, ActivationDescriptor::m_Function, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::ReLu, armnn::Sigmoid, armnn::SoftReLu, armnn::Sqrt, armnn::Square, and armnn::TanH.
Referenced by RefLayerSupport::IsLayerSupported().
 {
    bool supported = true;
     // Define supported types.
     std::array<DataType,6> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference activation: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference activation: output type not supported.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference activation: input and output types mismatched.");
     supported &= CheckSupportRule(ShapesAreSameRank(input, output), reasonIfUnsupported,
                                   "Reference activation: input and output shapes are of different rank.");
     struct ActivationFunctionSupported : public Rule
     {
         ActivationFunctionSupported(const ActivationDescriptor& desc)
         {
             switch(desc.m_Function)
             {
                 case ActivationFunction::Abs:
                 case ActivationFunction::BoundedReLu:
                 case ActivationFunction::Elu:
                 case ActivationFunction::HardSwish:
                 case ActivationFunction::LeakyReLu:
                 case ActivationFunction::Linear:
                 case ActivationFunction::ReLu:
                 case ActivationFunction::Sigmoid:
                 case ActivationFunction::SoftReLu:
                 case ActivationFunction::Sqrt:
                 case ActivationFunction::Square:
                 case ActivationFunction::TanH:
                 {
                     m_Res = true;
                     break;
                 }
                 default:
                 {
                     m_Res = false;
                     break;
                 }
             }
         }
     };
     // Function is supported
     supported &= CheckSupportRule(ActivationFunctionSupported(descriptor), reasonIfUnsupported,
                                   "Reference activation: function not supported.");
     return supported;
 }
IsAdditionSupported()
bool IsAdditionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 611 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported(), and TEST_SUITE().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference addition: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference addition: input 1 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference addition: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference addition: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference addition: input and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input0, input1, output), reasonIfUnsupported,
                                   "Reference addition: shapes are not suitable for implicit broadcast.");
     return supported;
 }
IsArgMinMaxSupported()
bool IsArgMinMaxSupported (const TensorInfo & input, const TensorInfo & output, const ArgMinMaxDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 649 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::Signed32, and armnn::Signed64.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     std::array<DataType, 8> supportedInputTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32,
         DataType::Signed64
     };
     std::array<DataType,2> supportedOutputTypes = {
         DataType::Signed32,
         DataType::Signed64
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedInputTypes), reasonIfUnsupported,
                                   "Reference ArgMinMax: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedOutputTypes), reasonIfUnsupported,
                                   "Reference ArgMinMax: output type not supported");
     return supported;
 }
IsBatchNormalizationSupported()
bool IsBatchNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & mean, const TensorInfo & var, const TensorInfo & beta, const TensorInfo & gamma, const BatchNormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 682 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     std::array<DataType, 6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference batch normalization: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference batch normalization: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference batch normalization: input and output types are mismatched");
     supported &= CheckSupportRule(TypeAnyOf(mean, supportedTypes), reasonIfUnsupported,
                                   "Reference batch normalization: mean is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(variance, supportedTypes), reasonIfUnsupported,
                                   "Reference batch normalization: variance is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(beta, supportedTypes), reasonIfUnsupported,
                                   "Reference batch normalization: beta is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(gamma, supportedTypes), reasonIfUnsupported,
                                   "Reference batch normalization: gamma is not a supported type.");
     return supported;
 }
IsBatchToSpaceNdSupported()
bool IsBatchToSpaceNdSupported (const TensorInfo & input, const TensorInfo & output, const BatchToSpaceNdDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 729 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetNumDimensions(), armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::string batchToSpaceNdLayerStr = "batchToSpaceNd";
     std::string inputTensorStr = "input";
     std::string outputTensorStr = "output";
     // Define supported types.
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference BatchToSpaceNd: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference BatchToSpaceNd: output type not supported.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference BatchToSpaceNd: input and output types mismatched.");
     supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(output, 4),
                                   reasonIfUnsupported,
                                   CreateIncorrectDimensionsErrorMsg(4,
                                                                     output.GetNumDimensions(),
                                                                     batchToSpaceNdLayerStr,
                                                                     outputTensorStr).data());
     supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(input, 4),
                                   reasonIfUnsupported,
                                   CreateIncorrectDimensionsErrorMsg(4,
                                                                     input.GetNumDimensions(),
                                                                     batchToSpaceNdLayerStr,
                                                                     inputTensorStr).data());
     return supported;
 }
IsCastSupported()
bool IsCastSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 779 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     std::array<DataType, 9> supportedInputTypes =
             {
                     DataType::BFloat16,
                     DataType::Float32,
                     DataType::Float16,
                     DataType::QSymmS8,
                     DataType::QAsymmS8,
                     DataType::QAsymmU8,
                     DataType::QSymmS16,
                     DataType::Signed32
             };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedInputTypes), reasonIfUnsupported,
                                   "Reference cast: input is not a supported type");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedInputTypes), reasonIfUnsupported,
                                   "Reference cast: output is not a supported type");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference cast: input and output shapes have different number of total elements");
     return supported;
 }
IsChannelShuffleSupported()
bool IsChannelShuffleSupported (const TensorInfo & input, const TensorInfo & output, const ChannelShuffleDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 809 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::QSymmS8.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported output and inputs types.
     std::array<DataType, 7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference ChannelShuffle: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference ChannelShuffle: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference ChannelShuffle: input and output types are mismatched.");
     return supported;
 }
IsComparisonSupported()
bool IsComparisonSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const ComparisonDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 842 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::Boolean, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     std::array<DataType, 8> supportedInputTypes =
     {
         DataType::Boolean,
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedInputTypes), reasonIfUnsupported,
                                   "Reference comparison: input 0 is not a supported type");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference comparison: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypeIs(output, DataType::Boolean), reasonIfUnsupported,
                                   "Reference comparison: output is not of type Boolean");
     return supported;
 }
IsConcatSupported()
bool IsConcatSupported (const std::vector< const TensorInfo *> inputs, const TensorInfo & output, const OriginsDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 874 of file RefLayerSupport.cpp.
References ARMNN_ASSERT, armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference concatenation: output type not supported");
     for (const TensorInfo* input : inputs)
     {
         ARMNN_ASSERT(input != nullptr);
         supported &= CheckSupportRule(TypeAnyOf(*input, supportedTypes), reasonIfUnsupported,
             "Reference concatenation: input type not supported");
         supported &= CheckSupportRule(TypesAreEqual(*input, output), reasonIfUnsupported,
             "Reference concatenation: input and output types mismatched.");
     }
     return supported;
 }
IsConstantSupported()
bool IsConstantSupported (const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 907 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     std::array<DataType,8> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     return CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference constant: output is not a supported type.");
 }
IsConvertBf16ToFp32Supported()
bool IsConvertBf16ToFp32Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 926 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), and armnn::Float32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     supported &= CheckSupportRule(TypeIs(input, DataType::BFloat16), reasonIfUnsupported,
                                   "Reference for ConvertBf16ToFp32 layer: input type not supported");
     supported &= CheckSupportRule(TypeIs(output, DataType::Float32), reasonIfUnsupported,
                                   "Reference for ConvertBf16ToFp32 layer: output type not supported");
     return supported;
 }
IsConvertFp16ToFp32Supported()
bool IsConvertFp16ToFp32Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 941 of file RefLayerSupport.cpp.
References TensorInfo::GetDataType(), and armnn::IsSupportedForDataTypeGeneric().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     return (IsSupportedForDataTypeGeneric(reasonIfUnsupported,
                                           input.GetDataType(),
                                           &TrueFunc<>,
                                           &FalseInputFuncF32<>,
                                           &FalseFuncU8<>,
                                           &FalseFuncI32<>,
                                           &FalseFuncU8<>) &&
             IsSupportedForDataTypeGeneric(reasonIfUnsupported,
                                           output.GetDataType(),
                                           &FalseOutputFuncF16<>,
                                           &TrueFunc<>,
                                           &FalseFuncU8<>,
                                           &FalseFuncI32<>,
                                           &FalseFuncU8<>));
 }
IsConvertFp32ToBf16Supported()
bool IsConvertFp32ToBf16Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 961 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), and armnn::Float32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     supported &= CheckSupportRule(TypeIs(input, DataType::Float32), reasonIfUnsupported,
                                   "Reference for ConvertFp32ToBf16 layer: input type not supported");
     supported &= CheckSupportRule(TypeIs(output, DataType::BFloat16), reasonIfUnsupported,
                                   "Reference for ConvertFp32ToBf16 layer: output type not supported");
     return supported;
 }
IsConvertFp32ToFp16Supported()
bool IsConvertFp32ToFp16Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 976 of file RefLayerSupport.cpp.
References TensorInfo::GetDataType(), and armnn::IsSupportedForDataTypeGeneric().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     return (IsSupportedForDataTypeGeneric(reasonIfUnsupported,
                                           input.GetDataType(),
                                           &FalseInputFuncF16<>,
                                           &TrueFunc<>,
                                           &FalseFuncU8<>,
                                           &FalseFuncI32<>,
                                           &FalseFuncU8<>) &&
             IsSupportedForDataTypeGeneric(reasonIfUnsupported,
                                           output.GetDataType(),
                                           &TrueFunc<>,
                                           &FalseOutputFuncF32<>,
                                           &FalseFuncU8<>,
                                           &FalseFuncI32<>,
                                           &FalseFuncU8<>));
 }
IsConvolution2dSupported()
bool IsConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 996 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), OptionalBase::has_value(), armnn::IgnoreUnused(), armnn::IsQuantized8BitType(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     // Define supported types.
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Convolution2d: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Convolution2d: output is not a supported type.");
     // For Convolution2d, we allow to have BFloat16 input with Float32 output for optimization.
     if (input.GetDataType() == DataType::BFloat16)
     {
         if (output.GetDataType() != DataType::BFloat16 && output.GetDataType() != DataType::Float32)
         {
             reasonIfUnsupported.value() += "Output tensor type must be BFloat16 or Float32 for BFloat16 input.\n";
             supported = false;
         }
     }
     else
     {
         supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Convolution2d: input and output types mismatched.");
     }
     const DataType inputType = input.GetDataType();
     if (IsQuantized8BitType(inputType))
     {
         std::array<DataType, 3> supportedWeightTypes =
         {
             DataType::QAsymmS8,
             DataType::QAsymmU8,
             DataType::QSymmS8
         };
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedWeightTypes), reasonIfUnsupported,
                                       "Reference Convolution2d: weights type not supported for quantized input.");
     }
     else
     {
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedTypes), reasonIfUnsupported,
                                       "Reference Convolution2d: weights is not a supported type.");
         supported &= CheckSupportRule(TypesAreEqual(input, weights), reasonIfUnsupported,
                                       "Reference Convolution2d: input and weights types mismatched.");
     }
     if (biases.has_value())
     {
         std::array<DataType,4> biasesSupportedTypes =
         {
             DataType::BFloat16,
             DataType::Float32,
             DataType::Float16,
             DataType::Signed32
         };
         supported &= CheckSupportRule(TypeAnyOf(biases.value(), biasesSupportedTypes), reasonIfUnsupported,
                                       "Reference Convolution2d: biases is not a supported type.");
     }
     IgnoreUnused(descriptor);
     return supported;
 }
IsConvolution3dSupported()
bool IsConvolution3dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution3dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1078 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), OptionalBase::has_value(), armnn::IgnoreUnused(), armnn::IsQuantized8BitType(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     // Define supported types.
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Convolution3d: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Convolution3d: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Convolution3d: input and output types mismatched.");
     const DataType inputType = input.GetDataType();
     if (IsQuantized8BitType(inputType))
     {
         std::array<DataType, 3> supportedWeightTypes =
         {
             DataType::QAsymmS8,
             DataType::QAsymmU8,
             DataType::QSymmS8
         };
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedWeightTypes), reasonIfUnsupported,
                                       "Reference Convolution3d: weights type not supported for quantized input.");
     }
     else
     {
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedTypes), reasonIfUnsupported,
                                       "Reference Convolution3d: weights is not a supported type.");
         supported &= CheckSupportRule(TypesAreEqual(input, weights), reasonIfUnsupported,
                                       "Reference Convolution3d: input and weights types mismatched.");
     }
     if (biases.has_value())
     {
         std::array<DataType,4> biasesSupportedTypes =
         {
             DataType::BFloat16,
             DataType::Float32,
             DataType::Float16,
             DataType::Signed32
         };
         supported &= CheckSupportRule(TypeAnyOf(biases.value(), biasesSupportedTypes), reasonIfUnsupported,
                                       "Reference Convolution3d: biases is not a supported type.");
     }
     IgnoreUnused(descriptor);
     return supported;
 }
IsDebugSupported()
bool IsDebugSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1148 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType, 8> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference for Debug layer: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference for Debug layer: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference for Debug layer: input and output types are mismatched");
     return supported;
 }
IsDepthToSpaceSupported()
bool IsDepthToSpaceSupported (const TensorInfo & input, const TensorInfo & output, const DepthToSpaceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1178 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
         "Reference DepthToSpace: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
         "Reference DepthToSpace: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
         "Reference DepthToSpace: input and output types are mismatched");
     return supported;
 }
IsDepthwiseConvolutionSupported()
bool IsDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1208 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), OptionalBase::has_value(), armnn::IgnoreUnused(), armnn::IsQuantized8BitType(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsDilatedDepthwiseConvolutionSupported(), and RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported types.
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference DepthwiseConvolution2d: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference DepthwiseConvolution2d: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference DepthwiseConvolution2d: input and output types mismatched.");
     const DataType inputType = input.GetDataType();
     if (IsQuantized8BitType(inputType))
     {
         std::array<DataType, 3> supportedWeightTypes =
                 {
                         DataType::QAsymmS8,
                         DataType::QAsymmU8,
                         DataType::QSymmS8,
                 };
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedWeightTypes), reasonIfUnsupported,
                                        "Reference DepthwiseConvolution2d: weights type not supported for "
                                        "quantized input.");
     }
     else
     {
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedTypes), reasonIfUnsupported,
                                       "Reference DepthwiseConvolution2d: weights is not a supported type.");
         supported &= CheckSupportRule(TypesAreEqual(input, weights), reasonIfUnsupported,
                                       "Reference DepthwiseConvolution2d: input and weights types mismatched.");
     }
     if (biases.has_value())
     {
         std::array<DataType,4> biasesSupportedTypes =
         {
             DataType::BFloat16,
             DataType::Float32,
             DataType::Float16,
             DataType::Signed32
         };
         supported &= CheckSupportRule(TypeAnyOf(biases.value(), biasesSupportedTypes), reasonIfUnsupported,
                                       "Reference DepthwiseConvolution2d: biases is not a supported type.");
     }
     return supported;
 }
IsDequantizeSupported()
bool IsDequantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1279 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::QSymmS8.
Referenced by RefLayerSupport::IsLayerSupported().
 {
    bool supported = true;
     std::array<DataType,4> supportedInputTypes = {
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedInputTypes), reasonIfUnsupported,
                                   "Reference for Dequantize layer: input type not supported.");
     supported &= CheckSupportRule(TypeNotPerAxisQuantized(input), reasonIfUnsupported,
                                   "Reference for Dequantize layer: per-axis quantized input not supported.");
     std::array<DataType,3> supportedOutputTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16
     };
     supported &= CheckSupportRule(TypeAnyOf(output, supportedOutputTypes), reasonIfUnsupported,
                                   "Reference for Dequantize layer: output type not supported.");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference for Dequantize layer: input/output shapes have different num total "
                                   "elements.");
     return supported;
 }
IsDetectionPostProcessSupported()
bool IsDetectionPostProcessSupported (const TensorInfo & boxEncodings, const TensorInfo & scores, const TensorInfo & anchors, const TensorInfo & detectionBoxes, const TensorInfo & detectionClasses, const TensorInfo & detectionScores, const TensorInfo & numDetections, const DetectionPostProcessDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1314 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(anchors, detectionBoxes, detectionClasses, detectionScores, numDetections, descriptor);
     bool supported = true;
     std::array<DataType,6> supportedInputTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(boxEncodings, supportedInputTypes), reasonIfUnsupported,
                                   "Reference DetectionPostProcess: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(scores, supportedInputTypes), reasonIfUnsupported,
                                   "Reference DetectionPostProcess: input 1 is not a supported type.");
     return supported;
 }
IsDilatedDepthwiseConvolutionSupported()
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1347 of file RefLayerSupport.cpp.
References RefLayerSupport::IsDepthwiseConvolutionSupported().
 {
     return IsDepthwiseConvolutionSupported(input, output, descriptor, weights, biases, reasonIfUnsupported);
 }
IsDivisionSupported()
bool IsDivisionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1357 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference division: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference division: input 1 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference division: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference division: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference division: input and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input0, input1, output), reasonIfUnsupported,
                                   "Reference division: shapes are not suitable for implicit broadcast.");
     return supported;
 }
IsElementwiseUnarySupported()
bool IsElementwiseUnarySupported (const TensorInfo & input, const TensorInfo & output, const ElementwiseUnaryDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1395 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::Boolean, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::LogicalNot, ElementwiseUnaryDescriptor::m_Operation, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     std::array<DataType, 7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     std::array<DataType, 1> logicalSupportedTypes =
     {
         DataType::Boolean
     };
     bool supported = true;
     if (descriptor.m_Operation == UnaryOperation::LogicalNot)
     {
         supported &= CheckSupportRule(TypeAnyOf(input, logicalSupportedTypes), reasonIfUnsupported,
                                       "Reference elementwise unary: input type not supported");
         supported &= CheckSupportRule(TypeAnyOf(output, logicalSupportedTypes), reasonIfUnsupported,
                                       "Reference elementwise unary: output type not supported");
     }
     else
     {
         supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                       "Reference elementwise unary: input type not supported");
         supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                       "Reference elementwise unary: output type not supported");
     }
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference elementwise unary: input and output types not matching");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference elementwise unary: input and output shapes"
                                   "have different number of total elements");
     return supported;
 }
IsFakeQuantizationSupported()
bool IsFakeQuantizationSupported (const TensorInfo & input, const FakeQuantizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1447 of file RefLayerSupport.cpp.
References armnn::CheckSupportRule(), armnn::Float32, and armnn::IgnoreUnused().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,1> supportedTypes =
     {
         DataType::Float32
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference fake quantization: input type not supported.");
     return supported;
 }
IsFillSupported()
bool IsFillSupported (const TensorInfo & input, const TensorInfo & output, const FillDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override virtual
Reimplemented from LayerSupportBase.
Definition at line 1465 of file RefLayerSupport.cpp.
References armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     IgnoreUnused(output);
     bool supported = true;
     std::array<DataType,3> supportedTypes =
     {
         DataType::Float32,
         DataType::Float16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeIs(input, DataType::Signed32), reasonIfUnsupported,
                                   "Reference Fill: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Fill: output type not supported.");
     return supported;
 }
IsFloorSupported()
bool IsFloorSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1490 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, and armnn::IgnoreUnused().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(output);
     bool supported = true;
     std::array<DataType,3> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Floor: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Floor: output type not supported.");
     return supported;
 }
IsFullyConnectedSupported()
bool IsFullyConnectedSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & weights, const TensorInfo & biases, const FullyConnectedDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1513 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), FullyConnectedDescriptor::m_BiasEnabled, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     // Define supported types.
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Fully Connected: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Fully Connected: output type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(weights, supportedTypes), reasonIfUnsupported,
                                   "Reference Fully Connected: weights type not supported.");
     // For FullyConnected, we allow to have BFloat16 input with Float32 output for optimization.
     if (input.GetDataType() == DataType::BFloat16)
     {
         if (output.GetDataType() != DataType::BFloat16 && output.GetDataType() != DataType::Float32)
         {
             reasonIfUnsupported.value() += "Output tensor type must be BFloat16 or Float32 for BFloat16 input.\n";
             supported = false;
         }
     }
     else
     {
         supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Fully Connected: input and output types mismatched.");
     }
     supported &= CheckSupportRule(TypeAnyOf(weights, supportedTypes), reasonIfUnsupported,
                                   "Reference Fully Connected: weights is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, weights), reasonIfUnsupported,
                                   "Reference Fully Connected: input and weights types mismatched.");
     if (descriptor.m_BiasEnabled)
     {
         // Defined supported types for bias
         std::array<DataType, 5>
         supportedBiasTypes =
         {
             DataType::BFloat16,
             DataType::Float32,
             DataType::Float16,
             DataType::Signed32,
             DataType::QAsymmS8
         };
         supported &= CheckSupportRule(TypeAnyOf(biases, supportedBiasTypes), reasonIfUnsupported,
                                       "Reference Fully Connected: bias type not supported.");
         supported &= CheckSupportRule(BiasAndWeightsTypesMatch(biases, weights), reasonIfUnsupported,
                                       "Reference Fully Connected: bias and weight types mismatch.");
         supported &= CheckSupportRule(BiasAndWeightsTypesCompatible(weights, supportedBiasTypes), reasonIfUnsupported,
                                       "Reference Fully Connected: bias type inferred from weights is incompatible.");
         supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(biases, 1U), reasonIfUnsupported,
                                       "Reference Fully Connected: bias must have 1 dimension.");
     }
     return supported;
 }
IsGatherSupported()
bool IsGatherSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const GatherDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1593 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, GatherDescriptor::m_Axis, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     if (descriptor.m_Axis != 0)
     {
         reasonIfUnsupported.value() += std::string("Reference Gather: axis not supported\n");
         supported &= false;
     }
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference Gather: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Gather: output type not supported");
     supported &= CheckSupportRule(TypeIs(input1, DataType::Signed32), reasonIfUnsupported,
                                   "Reference Gather: indices (input1) type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference Gather: input and output types not matching");
     return supported;
 }
IsInputSupported()
bool IsInputSupported (const TensorInfo & input, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1631 of file RefLayerSupport.cpp.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     return true;
 }
IsInstanceNormalizationSupported()
bool IsInstanceNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const InstanceNormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1637 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, and armnn::IgnoreUnused().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     // Define supported types
     std::array<DataType, 3> supportedTypes =
         {
             DataType::BFloat16,
             DataType::Float32,
             DataType::Float16
         };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Instance Normalization: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Instance Normalization: output type not supported.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Instance Normalization: input and output types mismatched.");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference Instance Normalization: input and output shapes have different "
                                   "num total elements.");
     return supported;
 }
IsL2NormalizationSupported()
bool IsL2NormalizationSupported (const TensorInfo & input, const TensorInfo & output, const L2NormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1669 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     // Define supported types
     std::array<DataType, 6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference L2normalization: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference L2normalization: output type not supported.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference L2normalization: input and output types mismatched.");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference L2normalization: input and output shapes have different "
                                   "num total elements.");
     return supported;
 }
IsLayerSupported()
bool IsLayerSupported (const LayerType & type, const std::vector< TensorInfo > & infos, const BaseDescriptor & descriptor, const Optional< LstmInputParamsInfo > & lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > & quantizedLstmInputParamsInfo, Optional< std::string &> reasonIfUnsupported) const override virtual
Reimplemented from LayerSupportBase.
Definition at line 61 of file RefLayerSupport.cpp.
References armnn::Activation, armnn::Addition, armnn::ArgMinMax, armnn::BatchNormalization, armnn::BatchToSpaceNd, armnn::Cast, armnn::ChannelShuffle, armnn::Comparison, armnn::Concat, armnn::Constant, armnn::ConvertBf16ToFp32, armnn::ConvertFp16ToFp32, armnn::ConvertFp32ToBf16, armnn::ConvertFp32ToFp16, armnn::Convolution2d, armnn::Convolution3d, armnn::Debug, armnn::DepthToSpace, armnn::DepthwiseConvolution2d, armnn::Dequantize, ILayerSupport::descriptor, armnn::DetectionPostProcess, armnn::Division, armnn::ElementwiseUnary, armnn::FakeQuantization, armnn::Fill, armnn::Floor, armnn::FullyConnected, armnn::Gather, armnn::Input, armnn::InstanceNormalization, RefLayerSupport::IsActivationSupported(), RefLayerSupport::IsAdditionSupported(), RefLayerSupport::IsArgMinMaxSupported(), RefLayerSupport::IsBatchNormalizationSupported(), RefLayerSupport::IsBatchToSpaceNdSupported(), RefLayerSupport::IsCastSupported(), RefLayerSupport::IsChannelShuffleSupported(), RefLayerSupport::IsComparisonSupported(), RefLayerSupport::IsConcatSupported(), RefLayerSupport::IsConstantSupported(), RefLayerSupport::IsConvertBf16ToFp32Supported(), RefLayerSupport::IsConvertFp16ToFp32Supported(), RefLayerSupport::IsConvertFp32ToBf16Supported(), RefLayerSupport::IsConvertFp32ToFp16Supported(), RefLayerSupport::IsConvolution2dSupported(), RefLayerSupport::IsConvolution3dSupported(), RefLayerSupport::IsDebugSupported(), RefLayerSupport::IsDepthToSpaceSupported(), RefLayerSupport::IsDepthwiseConvolutionSupported(), RefLayerSupport::IsDequantizeSupported(), RefLayerSupport::IsDetectionPostProcessSupported(), RefLayerSupport::IsDivisionSupported(), RefLayerSupport::IsElementwiseUnarySupported(), RefLayerSupport::IsFakeQuantizationSupported(), RefLayerSupport::IsFillSupported(), RefLayerSupport::IsFloorSupported(), RefLayerSupport::IsFullyConnectedSupported(), RefLayerSupport::IsGatherSupported(), RefLayerSupport::IsInputSupported(), RefLayerSupport::IsInstanceNormalizationSupported(), RefLayerSupport::IsL2NormalizationSupported(), RefLayerSupport::IsLogicalBinarySupported(), RefLayerSupport::IsLogSoftmaxSupported(), RefLayerSupport::IsLstmSupported(), RefLayerSupport::IsMaximumSupported(), RefLayerSupport::IsMeanSupported(), RefLayerSupport::IsMemCopySupported(), LayerSupportBase::IsMemImportSupported(), LayerSupportBase::IsMergeSupported(), RefLayerSupport::IsMinimumSupported(), RefLayerSupport::IsMultiplicationSupported(), RefLayerSupport::IsNormalizationSupported(), RefLayerSupport::IsOutputSupported(), RefLayerSupport::IsPadSupported(), RefLayerSupport::IsPermuteSupported(), RefLayerSupport::IsPooling2dSupported(), RefLayerSupport::IsPooling3dSupported(), RefLayerSupport::IsPreluSupported(), RefLayerSupport::IsQLstmSupported(), LayerSupportBase::IsQuantizedLstmSupported(), RefLayerSupport::IsQuantizeSupported(), RefLayerSupport::IsRankSupported(), RefLayerSupport::IsReduceSupported(), RefLayerSupport::IsReshapeSupported(), RefLayerSupport::IsResizeSupported(), RefLayerSupport::IsShapeSupported(), RefLayerSupport::IsSliceSupported(), RefLayerSupport::IsSoftmaxSupported(), RefLayerSupport::IsSpaceToBatchNdSupported(), RefLayerSupport::IsSpaceToDepthSupported(), RefLayerSupport::IsSplitterSupported(), RefLayerSupport::IsStackSupported(), RefLayerSupport::IsStridedSliceSupported(), RefLayerSupport::IsSubtractionSupported(), RefLayerSupport::IsTransposeConvolution2dSupported(), RefLayerSupport::IsTransposeSupported(), RefLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::L2Normalization, armnn::LogicalBinary, armnn::LogSoftmax, armnn::Lstm, armnn::Map, armnn::Maximum, armnn::Mean, armnn::MemCopy, armnn::MemImport, armnn::Merge, armnn::Minimum, armnn::Multiplication, armnn::Normalization, armnn::Output, armnn::Pad, armnn::Permute, armnn::Pooling2d, armnn::Pooling3d, armnn::Prelu, armnn::QLstm, armnn::Quantize, armnn::QuantizedLstm, armnn::Rank, ILayerSupport::reasonIfUnsupported, armnn::Reduce, armnn::Reshape, armnn::Resize, armnn::Shape, armnn::Slice, armnn::Softmax, armnn::SpaceToBatchNd, armnn::SpaceToDepth, armnn::Splitter, armnn::Stack, armnn::StridedSlice, armnn::Subtraction, armnn::Transpose, armnn::TransposeConvolution2d, armnn::UnidirectionalSequenceLstm, armnn::Unmap, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
 {
     switch (type)
     {
         case LayerType::Activation:
             return IsActivationSupported(infos[0],
                                          infos[1],
                                          *(PolymorphicDowncast<const ActivationDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Addition:
             return IsAdditionSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::ArgMinMax:
             return IsArgMinMaxSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const ArgMinMaxDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::BatchNormalization:
             return IsBatchNormalizationSupported(infos[0],
                                                  infos[1],
                                                  infos[2],
                                                  infos[3],
                                                  infos[4],
                                                  infos[5],
                                                  *(PolymorphicDowncast<const BatchNormalizationDescriptor*>
                                                      (&descriptor)),
                                                  reasonIfUnsupported);
         case LayerType::BatchToSpaceNd:
             return IsBatchToSpaceNdSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const BatchToSpaceNdDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Comparison:
             return IsComparisonSupported(infos[0],
                                          infos[1],
                                          infos[2],
                                          *(PolymorphicDowncast<const ComparisonDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Concat:
         {
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < (infos.size() - 1); i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             return IsConcatSupported(inputInfos,
                                      infos[infos.size() - 1],
                                      *(PolymorphicDowncast<const OriginsDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         }
         case LayerType::Constant:
             return IsConstantSupported(infos[0], reasonIfUnsupported);
         case LayerType::ConvertBf16ToFp32:
             return IsConvertBf16ToFp32Supported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::ConvertFp16ToFp32:
             return IsConvertFp16ToFp32Supported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::ConvertFp32ToBf16:
             return IsConvertFp32ToBf16Supported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::ConvertFp32ToFp16:
             return IsConvertFp32ToFp16Supported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Convolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const Convolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsConvolution2dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsConvolution2dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 infos[3],
                                                 reasonIfUnsupported);
             }
         }
         case LayerType::DepthToSpace:
             return IsDepthToSpaceSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const DepthToSpaceDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::DepthwiseConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of DepthwiseConvolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const DepthwiseConvolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsDepthwiseConvolutionSupported(infos[0],
                                                        infos[1],
                                                        desc,
                                                        infos[2],
                                                        EmptyOptional(),
                                                        reasonIfUnsupported);
             }
             else
             {
                 return IsDepthwiseConvolutionSupported(infos[0],
                                                        infos[1],
                                                        desc,
                                                        infos[2],
                                                        infos[3],
                                                        reasonIfUnsupported);
             }
         }
         case LayerType::Dequantize:
             return IsDequantizeSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Division:
             return IsDivisionSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::ElementwiseUnary:
             return IsElementwiseUnarySupported(infos[0],
                                                infos[1],
                                                *(PolymorphicDowncast<const ElementwiseUnaryDescriptor*>(&descriptor)),
                                                reasonIfUnsupported);
         case LayerType::Fill:
             return IsFillSupported(infos[0],
                                    infos[1],
                                    *(PolymorphicDowncast<const FillDescriptor*>(&descriptor)),
                                    reasonIfUnsupported);
         case LayerType::Floor:
             return IsFloorSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::FullyConnected:
             return IsFullyConnectedSupported(infos[0],
                                              infos[1],
                                              infos[2],
                                              infos[3],
                                              *(PolymorphicDowncast<const FullyConnectedDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Gather:
             return IsGatherSupported(infos[0],
                                      infos[1],
                                      infos[2],
                                      *(PolymorphicDowncast<const GatherDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Input:
             return IsInputSupported(infos[0], reasonIfUnsupported);
         case LayerType::InstanceNormalization:
             return IsInstanceNormalizationSupported(infos[0],
                                                     infos[1],
                                                     *(PolymorphicDowncast<const InstanceNormalizationDescriptor*>
                                                         (&descriptor)),
                                                     reasonIfUnsupported);
         case LayerType::L2Normalization:
             return IsL2NormalizationSupported(infos[0],
                                               infos[1],
                                               *(PolymorphicDowncast<const L2NormalizationDescriptor*>(&descriptor)),
                                               reasonIfUnsupported);
         case LayerType::LogicalBinary:
             return IsLogicalBinarySupported(infos[0],
                                             infos[1],
                                             infos[2],
                                             *(PolymorphicDowncast<const LogicalBinaryDescriptor*>(&descriptor)),
                                             reasonIfUnsupported);
         case LayerType::LogSoftmax:
             return IsLogSoftmaxSupported(infos[0],
                                          infos[1],
                                          *(PolymorphicDowncast<const LogSoftmaxDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Lstm:
             return IsLstmSupported(infos[0],
                                    infos[1],
                                    infos[2],
                                    infos[3],
                                    infos[4],
                                    infos[5],
                                    infos[6],
                                    *(PolymorphicDowncast<const LstmDescriptor*>(&descriptor)),
                                    lstmParamsInfo.value(),
                                    reasonIfUnsupported);
         case LayerType::QLstm:
             return IsQLstmSupported(infos[0],
                                     infos[1],
                                     infos[2],
                                     infos[3],
                                     infos[4],
                                     infos[5],
                                     *(PolymorphicDowncast<const QLstmDescriptor*>(&descriptor)),
                                     lstmParamsInfo.value(),
                                     reasonIfUnsupported);
         case LayerType::Maximum:
             return IsMaximumSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::Mean:
             return IsMeanSupported(infos[0],
                                    infos[1],
                                    *(PolymorphicDowncast<const MeanDescriptor*>(&descriptor)),
                                    reasonIfUnsupported);
         case LayerType::Minimum:
             return IsMinimumSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::Multiplication:
             return IsMultiplicationSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::Normalization:
             return IsNormalizationSupported(infos[0],
                                             infos[1],
                                             *(PolymorphicDowncast<const NormalizationDescriptor*>(&descriptor)),
                                             reasonIfUnsupported);
         case LayerType::Output:
             return IsOutputSupported(infos[0], reasonIfUnsupported);
         case LayerType::Pad:
             return IsPadSupported(infos[0],
                                   infos[1],
                                   *(PolymorphicDowncast<const PadDescriptor*>(&descriptor)),
                                   reasonIfUnsupported);
         case LayerType::Permute:
             return IsPermuteSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const PermuteDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::Pooling2d:
             return IsPooling2dSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const Pooling2dDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::Prelu:
             return IsPreluSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::Quantize:
             return IsQuantizeSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Reshape:
             return IsReshapeSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const ReshapeDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::Resize:
             return IsResizeSupported(infos[0],
                                      infos[1],
                                      *(PolymorphicDowncast<const ResizeDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Reduce:
             return IsReduceSupported(infos[0],
                                      infos[1],
                                      *(PolymorphicDowncast<const ReduceDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Slice:
             return IsSliceSupported(infos[0],
                                     infos[1],
                                     *(PolymorphicDowncast<const SliceDescriptor*>(&descriptor)),
                                     reasonIfUnsupported);
         case LayerType::Softmax:
             return IsSoftmaxSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const SoftmaxDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::SpaceToBatchNd:
             return IsSpaceToBatchNdSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const SpaceToBatchNdDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::SpaceToDepth:
             return IsSpaceToDepthSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const SpaceToDepthDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::Splitter:
         {
             std::vector<TensorInfo> outputInfos;
             for (uint32_t i = 1; i < infos.size(); i++)
             {
                 outputInfos.push_back(infos[i]);
             }
             return IsSplitterSupported(infos[0],
                                        {outputInfos.begin(), outputInfos.end()},
                                        *(PolymorphicDowncast<const ViewsDescriptor*>(&descriptor)),
                                        reasonIfUnsupported);
         }
         case LayerType::Stack:
         {
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < infos.size() - 1; i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             return IsStackSupported(inputInfos,
                                     infos[infos.size() - 1],
                                     *(PolymorphicDowncast<const StackDescriptor*>(&descriptor)),
                                     reasonIfUnsupported);
         }
         case LayerType::StridedSlice:
             return IsStridedSliceSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const StridedSliceDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::Subtraction:
             return IsSubtractionSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::Transpose:
             return IsTransposeSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const TransposeDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::TransposeConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of TransposeConvolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const TransposeConvolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsTransposeConvolution2dSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          EmptyOptional(),
                                                          reasonIfUnsupported);
             }
             else
             {
                 return IsTransposeConvolution2dSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          infos[3],
                                                          reasonIfUnsupported);
             }
         }
         case LayerType::Cast:
             return IsCastSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::ChannelShuffle:
             return IsChannelShuffleSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const ChannelShuffleDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Convolution3d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution3d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const Convolution3dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsConvolution3dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsConvolution3dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 infos[3],
                                                 reasonIfUnsupported);
             }
         }
         case LayerType::Debug:
             return IsDebugSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::DetectionPostProcess:
             return IsDetectionPostProcessSupported(infos[0],
                                                    infos[1],
                                                    infos[2],
                                                    infos[3],
                                                    infos[4],
                                                    infos[5],
                                                    infos[6],
                                                    *(PolymorphicDowncast<const DetectionPostProcessDescriptor*>
                                                        (&descriptor)),
                                                    reasonIfUnsupported);
         case LayerType::FakeQuantization:
             return IsFakeQuantizationSupported(infos[0],
                                                *(PolymorphicDowncast<const FakeQuantizationDescriptor*>(&descriptor)),
                                                reasonIfUnsupported);
         case LayerType::MemCopy:
             return IsMemCopySupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Rank:
             return IsRankSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Shape:
             return IsShapeSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::UnidirectionalSequenceLstm:
         {
             if (infos.size() != 6)
             {
                 throw InvalidArgumentException("Invalid number of UnidirectionalSequenceLstm TensorInfos. TensorInfos "
                                                "should be of format: {input, outputStateIn, cellStateIn, "
                                                "hiddenStateOutputVal, cellStateOutputVal, output}");
             }
             auto desc = *(PolymorphicDowncast<const UnidirectionalSequenceLstmDescriptor*>(&descriptor));
             bool isHiddenStateOutputOptional = (infos[4] == TensorInfo());
             bool isCellStateOutput = (infos[5] == TensorInfo());
             if (isHiddenStateOutputOptional && isCellStateOutput)
             {
                 return IsUnidirectionalSequenceLstmSupported(infos[0],
                                                              infos[1],
                                                              infos[2],
                                                              infos[3],
                                                              EmptyOptional(),
                                                              EmptyOptional(),
                                                              desc,
                                                              lstmParamsInfo.value(),
                                                              reasonIfUnsupported);
             }
             else if (isHiddenStateOutputOptional)
             {
                 return IsUnidirectionalSequenceLstmSupported(infos[0],
                                                              infos[1],
                                                              infos[2],
                                                              infos[3],
                                                              EmptyOptional(),
                                                              infos[5],
                                                              desc,
                                                              lstmParamsInfo.value(),
                                                              reasonIfUnsupported);
             }
             else if (isCellStateOutput)
             {
                 return IsUnidirectionalSequenceLstmSupported(infos[0],
                                                              infos[1],
                                                              infos[2],
                                                              infos[3],
                                                              infos[4],
                                                              EmptyOptional(),
                                                              desc,
                                                              lstmParamsInfo.value(),
                                                              reasonIfUnsupported);
             }
             else
             {
                 return IsUnidirectionalSequenceLstmSupported(infos[0],
                                                              infos[1],
                                                              infos[2],
                                                              infos[3],
                                                              infos[4],
                                                              infos[5],
                                                              desc,
                                                              lstmParamsInfo.value(),
                                                              reasonIfUnsupported);
             }
         }
         case LayerType::Pooling3d:
             return IsPooling3dSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const Pooling3dDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::Map:
             return true;
         case LayerType::Unmap:
             return true;
         case LayerType::MemImport:
             return LayerSupportBase::IsMemImportSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Merge:
             return LayerSupportBase::IsMergeSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::QuantizedLstm:
             return LayerSupportBase::IsQuantizedLstmSupported(infos[0],
                                                               infos[1],
                                                               infos[2],
                                                               infos[3],
                                                               infos[4],
                                                               quantizedLstmInputParamsInfo.value(),
                                                               reasonIfUnsupported);
         default:
             // layers not supported in neon by default:
             // precompiled, standin, switch
             return false;
     }
 }
IsLogicalBinarySupported()
bool IsLogicalBinarySupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const LogicalBinaryDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported) const override
Definition at line 1704 of file RefLayerSupport.cpp.
References armnn::Boolean, armnn::CheckSupportRule(), and armnn::IgnoreUnused().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     std::array<DataType, 1> supportedTypes =
     {
         DataType::Boolean
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference LogicalBinary: input 0 type not supported");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference LogicalBinary: input 1 type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference LogicalBinary: input and output types do not match");
     return supported;
 }
IsLogSoftmaxSupported()
bool IsLogSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const LogSoftmaxDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported) const override
Definition at line 1729 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, and armnn::IgnoreUnused().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     std::array<DataType, 3> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference LogSoftmax: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference LogSoftmax: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference LogSoftmax: input and output types do not match");
     return supported;
 }
IsLstmSupported()
bool IsLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & scratchBuffer, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const LstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1756 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float32, LstmInputParamsInfo::GetCellBias(), LstmInputParamsInfo::GetCellLayerNormWeights(), LstmInputParamsInfo::GetCellToForgetWeights(), LstmInputParamsInfo::GetCellToInputWeights(), LstmInputParamsInfo::GetCellToOutputWeights(), LstmInputParamsInfo::GetForgetGateBias(), LstmInputParamsInfo::GetForgetLayerNormWeights(), LstmInputParamsInfo::GetInputGateBias(), LstmInputParamsInfo::GetInputLayerNormWeights(), LstmInputParamsInfo::GetInputToCellWeights(), LstmInputParamsInfo::GetInputToForgetWeights(), LstmInputParamsInfo::GetInputToInputWeights(), LstmInputParamsInfo::GetInputToOutputWeights(), LstmInputParamsInfo::GetOutputGateBias(), LstmInputParamsInfo::GetOutputLayerNormWeights(), LstmInputParamsInfo::GetProjectionBias(), LstmInputParamsInfo::GetProjectionWeights(), LstmInputParamsInfo::GetRecurrentToCellWeights(), LstmInputParamsInfo::GetRecurrentToForgetWeights(), LstmInputParamsInfo::GetRecurrentToInputWeights(), LstmInputParamsInfo::GetRecurrentToOutputWeights(), armnn::IgnoreUnused(), LstmDescriptor::m_CifgEnabled, LstmDescriptor::m_LayerNormEnabled, LstmDescriptor::m_PeepholeEnabled, LstmInputParamsInfo::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     IgnoreUnused(paramsInfo);
     bool supported = true;
     std::array<DataType,3> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::QSymmS16
     };
     // check inputs and outputs
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Lstm: input is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, outputStateIn), reasonIfUnsupported,
                                   "Reference Lstm: input and outputStateIn types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, cellStateIn), reasonIfUnsupported,
                                   "Reference Lstm: input and cellStateIn types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, scratchBuffer), reasonIfUnsupported,
                                   "Reference Lstm: input and scratchBuffer types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, outputStateOut), reasonIfUnsupported,
                                   "Reference Lstm: input and outputStateOut types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, cellStateOut), reasonIfUnsupported,
                                   "Reference Lstm: input and cellStateOut types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Lstm: input and output types are mismatched");
     // check layer parameters
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputToForgetWeights()), reasonIfUnsupported,
                                   "Reference Lstm: input and InputToForgetWeights types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputToCellWeights()), reasonIfUnsupported,
                                   "Reference Lstm: input and InputToCellWeights types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputToOutputWeights()), reasonIfUnsupported,
                                   "Reference Lstm: input and InputToOutputWeights types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetRecurrentToForgetWeights()), reasonIfUnsupported,
                                   "Reference Lstm: input and RecurrentToForgetWeights types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetRecurrentToCellWeights()), reasonIfUnsupported,
                                   "Reference Lstm: input and RecurrentToCellWeights types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetRecurrentToOutputWeights()), reasonIfUnsupported,
                                   "Reference Lstm: input and RecurrentToOutputWeights types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetForgetGateBias()), reasonIfUnsupported,
                                   "Reference Lstm: input and ForgetGateBias types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetCellBias()), reasonIfUnsupported,
                                   "Reference Lstm: input and CellBias types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetOutputGateBias()), reasonIfUnsupported,
                                   "Reference Lstm: input and OutputGateBias types are mismatched");
     if (!descriptor.m_CifgEnabled)
     {
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputToInputWeights()), reasonIfUnsupported,
                                       "Reference Lstm: input and InputToInputWeights types are mismatched");
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetRecurrentToInputWeights()),
                                       reasonIfUnsupported,
                                       "Reference Lstm: input and RecurrentToInputWeights types are mismatched");
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputGateBias()), reasonIfUnsupported,
                                       "Reference Lstm: input and InputGateBias types are mismatched");
         if (descriptor.m_PeepholeEnabled)
         {
             supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetCellToInputWeights()),
                                           reasonIfUnsupported,
                                           "Reference Lstm: input and CellToInputWeights types are mismatched");
         }
     }
     if (descriptor.m_PeepholeEnabled)
     {
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetCellToForgetWeights()), reasonIfUnsupported,
                                       "Reference Lstm: input and CellToForgetWeights types are mismatched");
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetCellToOutputWeights()), reasonIfUnsupported,
                                       "Reference Lstm: input and CellToOutputWeights types are mismatched");
     }
     if (descriptor.m_ProjectionEnabled)
     {
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetProjectionWeights()), reasonIfUnsupported,
                                       "Reference Lstm: input and mProjectionWeights types are mismatched");
         if (paramsInfo.m_ProjectionBias != nullptr)
         {
             supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetProjectionBias()), reasonIfUnsupported,
                                           "Reference Lstm: input and ProjectionBias types are mismatched");
         }
     }
     if (descriptor.m_LayerNormEnabled)
     {
         if (!descriptor.m_CifgEnabled)
         {
             supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputLayerNormWeights()),
                                           reasonIfUnsupported,
                                           "Reference Lstm: input and InputLayerNormWeights types are mismatched");
         }
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetForgetLayerNormWeights()),
                                       reasonIfUnsupported,
                                       "Reference Lstm: input and ForgetLayerNormWeights types are mismatched");
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetCellLayerNormWeights()),
                                       reasonIfUnsupported,
                                       "Reference Lstm: input and CellLayerNormWeights types are mismatched");
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetOutputLayerNormWeights()),
                                       reasonIfUnsupported,
                                       "Reference Lstm: input and OutputLayerNormWeights types are mismatched");
     }
     return supported;
 }
IsMaximumSupported()
bool IsMaximumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1868 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference maximum: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference maximum: input 1 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference maximum: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference maximum: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference maximum: input and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input0, input1, output), reasonIfUnsupported,
                                   "Reference maximum: shapes are not suitable for implicit broadcast.");
     return supported;
 }
IsMeanSupported()
bool IsMeanSupported (const TensorInfo & input, const TensorInfo & output, const MeanDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1906 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetNumDimensions(), MeanDescriptor::m_Axis, MeanDescriptor::m_KeepDims, armnn::numeric_cast(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::string meanLayerStr = "Mean";
     std::string outputTensorStr = "output";
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Mean: input type not supported.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Mean: input and output types are mismatched");
     if (descriptor.m_KeepDims)
     {
         supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(output, input.GetNumDimensions()),
                                       reasonIfUnsupported,
                                       CreateIncorrectDimensionsErrorMsg(input.GetNumDimensions(),
                                                                         output.GetNumDimensions(),
                                                                         meanLayerStr, outputTensorStr).data());
     }
     else if (descriptor.m_Axis.empty())
     {
         supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(output, 1),
                                       reasonIfUnsupported,
                                       CreateIncorrectDimensionsErrorMsg(1, output.GetNumDimensions(),
                                                                         meanLayerStr, outputTensorStr).data());
     }
     else
     {
         auto outputDim = input.GetNumDimensions() - armnn::numeric_cast<unsigned int>(descriptor.m_Axis.size());
         if (outputDim > 0)
         {
             supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(output, outputDim),
                                           reasonIfUnsupported,
                                           CreateIncorrectDimensionsErrorMsg(outputDim, output.GetNumDimensions(),
                                                                             meanLayerStr, outputTensorStr).data());
         }
         else
         {
             supported &= CheckSupportRule(TensorNumDimensionsAreCorrect(output, 1),
                                           reasonIfUnsupported,
                                           CreateIncorrectDimensionsErrorMsg(1, output.GetNumDimensions(),
                                                                             meanLayerStr, outputTensorStr).data());
         }
     }
     return supported;
 }
IsMemCopySupported()
bool IsMemCopySupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1969 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::Boolean, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Boolean
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference MemCopy: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference MemCopy: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference MemCopy: input and output types are mismatched");
     return supported;
 }
IsMinimumSupported()
bool IsMinimumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1998 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference minimum: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference minimum: input 1 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference minimum: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference minimum: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference minimum: input and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input0, input1, output), reasonIfUnsupported,
                                   "Reference minimum: shapes are not suitable for implicit broadcast.");
     return supported;
 }
IsMultiplicationSupported()
bool IsMultiplicationSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2036 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference multiplication: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference multiplication: input 1 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference multiplication: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference multiplication: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference multiplication: input and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input0, input1, output), reasonIfUnsupported,
                                   "Reference multiplication: shapes are not suitable for implicit broadcast.");
     return supported;
 }
IsNormalizationSupported()
bool IsNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const NormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2074 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     // Define supported types
     std::array<DataType, 6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     bool supported = true;
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference normalization: input type not supported.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference normalization: output type not supported.");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference normalization: input and output shapes have different "
                                   "num total elements.");
     return supported;
 }
IsOutputSupported()
bool IsOutputSupported (const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2107 of file RefLayerSupport.cpp.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     return true;
 }
IsPadSupported()
bool IsPadSupported (const TensorInfo & input, const TensorInfo & output, const PadDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2113 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported output and inputs types.
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference pad: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference pad: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference pad: input and output types are mismatched.");
     return supported;
 }
IsPermuteSupported()
bool IsPermuteSupported (const TensorInfo & input, const TensorInfo & output, const PermuteDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2144 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported output and inputs types.
     std::array<DataType, 6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference permute: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference permute: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference permute: input and output types are mismatched.");
     return supported;
 }
IsPooling2dSupported()
bool IsPooling2dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling2dDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2175 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported output and inputs types.
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference poolind2d: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference poolind2d: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference poolind2d: input and output types are mismatched.");
     return supported;
 }
IsPooling3dSupported()
bool IsPooling3dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling3dDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2206 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported output and inputs types.
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference poolind3d: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference poolind3d: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference poolind3d: input and output types are mismatched.");
     return supported;
 }
IsPreluSupported()
bool IsPreluSupported (const TensorInfo & input, const TensorInfo & alpha, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2665 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType, 6> supportedTypes
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "PReLU: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(alpha, supportedTypes), reasonIfUnsupported,
                                   "PReLU: alpha is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "PReLU: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, alpha, output), reasonIfUnsupported,
                                   "PReLU: input, alpha and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input, alpha, output), reasonIfUnsupported,
                                   "PReLU: shapes are not suitable for implicit broadcast");
     return supported;
 }
IsQLstmSupported()
bool IsQLstmSupported (const TensorInfo & input, const TensorInfo & previousOutputIn, const TensorInfo & previousCellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const QLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2238 of file RefLayerSupport.cpp.
References armnn::IgnoreUnused().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(input);
     IgnoreUnused(previousOutputIn);
     IgnoreUnused(previousCellStateIn);
     IgnoreUnused(outputStateOut);
     IgnoreUnused(cellStateOut);
     IgnoreUnused(output);
     IgnoreUnused(descriptor);
     IgnoreUnused(paramsInfo);
     IgnoreUnused(reasonIfUnsupported);
     return true;
 }
IsQuantizeSupported()
bool IsQuantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2262 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::QSymmS8.
Referenced by RefLayerSupport::IsLayerSupported().
 {
    bool supported = true;
     // Define supported input types.
     std::array<DataType,7> supportedInputTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedInputTypes), reasonIfUnsupported,
                                   "Reference quantize: input type not supported.");
     // Define supported output types.
     std::array<DataType,4> supportedOutputTypes = {
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(output, supportedOutputTypes), reasonIfUnsupported,
                                   "Reference quantize: output type not supported.");
     supported &= CheckSupportRule(ShapesAreSameTotalSize(input, output), reasonIfUnsupported,
                                   "Reference quantize: input and output shapes have different num total elements.");
     return supported;
 }
IsRankSupported()
bool IsRankSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2298 of file RefLayerSupport.cpp.
References armnn::CheckSupportRule(), armnn::IgnoreUnused(), and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(input);
     // Define supported output types.
     std::array<DataType,1> supportedOutputTypes =
     {
         DataType::Signed32,
     };
     return CheckSupportRule(TypeAnyOf(output, supportedOutputTypes), reasonIfUnsupported,
            "Reference rank: input type not supported.");
 }
IsReduceSupported()
bool IsReduceSupported (const TensorInfo & input, const TensorInfo & output, const ReduceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2313 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Reduce: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Reduce: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Reduce: input and output types not matching");
     return supported;
 }
IsReshapeSupported()
bool IsReshapeSupported (const TensorInfo & input, const TensorInfo & output, const ReshapeDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2343 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::Boolean, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(output);
     IgnoreUnused(descriptor);
     // Define supported output types.
     std::array<DataType,8> supportedOutputTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::Signed32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Boolean
     };
     return CheckSupportRule(TypeAnyOf(input, supportedOutputTypes), reasonIfUnsupported,
         "Reference reshape: input type not supported.");
 }
IsResizeSupported()
bool IsResizeSupported (const TensorInfo & input, const TensorInfo & output, const ResizeDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2367 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Resize: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Resize: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Resize: input and output types not matching");
     return supported;
 }
IsShapeSupported()
bool IsShapeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2396 of file RefLayerSupport.cpp.
References armnn::CheckSupportRule(), armnn::IgnoreUnused(), and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(input);
     bool supported = true;
     std::array<DataType, 1> supportedTypes =
     {
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Shape: output type not supported");
     return supported;
 }
IsSliceSupported()
bool IsSliceSupported (const TensorInfo & input, const TensorInfo & output, const SliceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2414 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType, 5> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Slice: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Slice: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Slice: input and output types are mismatched");
     return supported;
 }
IsSoftmaxSupported()
bool IsSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const SoftmaxDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2443 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::QSymmS8.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QSymmS8,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference Softmax: output type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference Softmax: input type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference Softmax: input type not supported");
     return supported;
 }
IsSpaceToBatchNdSupported()
bool IsSpaceToBatchNdSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToBatchNdDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2473 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference SpaceToBatchNd: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference SpaceToBatchNd: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference SpaceToBatchNd: input and output types are mismatched");
     return supported;
 }
IsSpaceToDepthSupported()
bool IsSpaceToDepthSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToDepthDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2502 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
         "Reference SpaceToDepth: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
         "Reference SpaceToDepth: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
         "Reference SpaceToDepth: input and output types are mismatched");
     return supported;
 }
IsSplitterSupported()
bool IsSplitterSupported (const TensorInfo & input, const std::vector< std::reference_wrapper< TensorInfo >> & outputs, const ViewsDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2533 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), ILayerSupport::output, ILayerSupport::outputs, armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference splitter: output type not supported");
     for (const TensorInfo& output : outputs)
     {
         supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                       "Reference splitter: input type not supported");
         supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                       "Reference splitter: input and output types mismatched.");
     }
     return supported;
 }
IsStackSupported()
bool IsStackSupported (const std::vector< const TensorInfo *> & inputs, const TensorInfo & output, const StackDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2564 of file RefLayerSupport.cpp.
References ARMNN_ASSERT, armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference stack: output type not supported");
     for (const TensorInfo* input : inputs)
     {
         ARMNN_ASSERT(input != nullptr);
         supported &= CheckSupportRule(TypeAnyOf(*input, supportedTypes), reasonIfUnsupported,
             "Reference stack: input type not supported");
         supported &= CheckSupportRule(TypesAreEqual(*input, output), reasonIfUnsupported,
             "Reference stack: input and output types mismatched.");
     }
     return supported;
 }
IsStridedSliceSupported()
bool IsStridedSliceSupported (const TensorInfo & input, const TensorInfo & output, const StridedSliceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2598 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,5> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference StridedSlice: input type not supported");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference StridedSlice: output type not supported");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference StridedSlice: input and output types are mismatched");
     return supported;
 }
IsSubtractionSupported()
bool IsSubtractionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2627 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and armnn::Signed32.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     bool supported = true;
     std::array<DataType,7> supportedTypes = {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32
     };
     supported &= CheckSupportRule(TypeAnyOf(input0, supportedTypes), reasonIfUnsupported,
                                   "Reference subtraction: input 0 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(input1, supportedTypes), reasonIfUnsupported,
                                   "Reference subtraction: input 1 is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference subtraction: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input0, input1), reasonIfUnsupported,
                                   "Reference subtraction: input 0 and Input 1 types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input0, output), reasonIfUnsupported,
                                   "Reference subtraction: input and output types are mismatched");
     supported &= CheckSupportRule(ShapesAreBroadcastCompatible(input0, input1, output), reasonIfUnsupported,
                                   "Reference subtraction: shapes are not suitable for implicit broadcast.");
     return supported;
 }
IsTransposeConvolution2dSupported()
bool IsTransposeConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const TransposeConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2700 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), OptionalBase::has_value(), armnn::IgnoreUnused(), armnn::IsQuantized8BitType(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     std::array<DataType,7> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference TransposeConvolution2d: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference TransposeConvolution2d: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference TransposeConvolution2d: input and output types mismatched.");
     const DataType inputType = input.GetDataType();
     if (IsQuantized8BitType(inputType))
     {
         std::array<DataType, 3> supportedWeightTypes =
         {
             DataType::QAsymmS8,
             DataType::QAsymmU8,
             DataType::QSymmS8
         };
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedWeightTypes), reasonIfUnsupported,
                                       "Reference TransposeConvolution2d: weights type not supported for "
                                       "quantized input.");
     }
     else
     {
         supported &= CheckSupportRule(TypeAnyOf(weights, supportedTypes), reasonIfUnsupported,
                                     "Reference TransposeConvolution2d: weights is not a supported type.");
         supported &= CheckSupportRule(TypesAreEqual(input, weights), reasonIfUnsupported,
                                     "Reference TransposeConvolution2d: input and weights types mismatched.");
     }
     if (biases.has_value())
     {
         std::array<DataType,4> biasesSupportedTypes =
         {
             DataType::BFloat16,
             DataType::Float32,
             DataType::Float16,
             DataType::Signed32
         };
         supported &= CheckSupportRule(TypeAnyOf(biases.value(), biasesSupportedTypes), reasonIfUnsupported,
                                       "Reference TransposeConvolution2d: biases is not a supported type.");
     }
     return supported;
 }
IsTransposeSupported()
bool IsTransposeSupported (const TensorInfo & input, const TensorInfo & output, const TransposeDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2770 of file RefLayerSupport.cpp.
References armnn::BFloat16, armnn::CheckSupportRule(), armnn::Float16, armnn::Float32, armnn::IgnoreUnused(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     bool supported = true;
     // Define supported output and inputs types.
     std::array<DataType, 6> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference transpose: input is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(output, supportedTypes), reasonIfUnsupported,
                                   "Reference transpose: output is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference transpose: input and output types are mismatched.");
     return supported;
 }
IsUnidirectionalSequenceLstmSupported()
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & output, const Optional< TensorInfo > & hiddenStateOutput, const Optional< TensorInfo > & cellStateOutput, const UnidirectionalSequenceLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 2801 of file RefLayerSupport.cpp.
References armnn::CheckSupportRule(), armnn::Float32, LstmInputParamsInfo::GetCellBias(), LstmInputParamsInfo::GetCellLayerNormWeights(), LstmInputParamsInfo::GetCellToForgetWeights(), LstmInputParamsInfo::GetCellToInputWeights(), LstmInputParamsInfo::GetCellToOutputWeights(), LstmInputParamsInfo::GetForgetGateBias(), LstmInputParamsInfo::GetForgetLayerNormWeights(), LstmInputParamsInfo::GetInputGateBias(), LstmInputParamsInfo::GetInputLayerNormWeights(), LstmInputParamsInfo::GetInputToCellWeights(), LstmInputParamsInfo::GetInputToForgetWeights(), LstmInputParamsInfo::GetInputToInputWeights(), LstmInputParamsInfo::GetInputToOutputWeights(), LstmInputParamsInfo::GetOutputGateBias(), LstmInputParamsInfo::GetOutputLayerNormWeights(), LstmInputParamsInfo::GetProjectionBias(), LstmInputParamsInfo::GetProjectionWeights(), LstmInputParamsInfo::GetRecurrentToCellWeights(), LstmInputParamsInfo::GetRecurrentToForgetWeights(), LstmInputParamsInfo::GetRecurrentToInputWeights(), LstmInputParamsInfo::GetRecurrentToOutputWeights(), OptionalBase::has_value(), armnn::IgnoreUnused(), LstmDescriptor::m_CifgEnabled, LstmDescriptor::m_LayerNormEnabled, LstmDescriptor::m_PeepholeEnabled, LstmInputParamsInfo::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, armnn::QAsymmS8, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by RefLayerSupport::IsLayerSupported().
 {
     IgnoreUnused(descriptor);
     IgnoreUnused(paramsInfo);
     IgnoreUnused(outputStateIn);
     IgnoreUnused(cellStateIn);
     bool supported = true;
     if (hiddenStateOutput.has_value() || cellStateOutput.has_value())
     {
         reasonIfUnsupported.value() += "Reference UnidirectionalSequenceLstm: hidden state output "
                                        "and cell state output are not supported at the moment.";
     }
     std::array<DataType, 1> supportedTypes =
     {
         DataType::Float32
     };
     std::array<DataType, 2> supportedWeightTypes =
     {
         DataType::Float32,
         DataType::QAsymmS8
     };
     // check inputs and outputs
     supported &= CheckSupportRule(TypeAnyOf(input, supportedTypes), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, outputStateIn), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input and outputStateIn types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, cellStateIn), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input and cellStateIn types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, output), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input and output types are mismatched");
     // check layer parameters
     supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetInputToForgetWeights(), supportedWeightTypes),
                                   reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: InputToForgetWeights "
                                   "is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetInputToCellWeights(), supportedWeightTypes),
                                   reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: InputToCellWeights is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetInputToOutputWeights(), supportedWeightTypes),
                                   reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: InputToOutputWeights "
                                   "is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetRecurrentToForgetWeights(), supportedWeightTypes),
                                   reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: RecurrentToForgetWeights "
                                   "is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetRecurrentToCellWeights(), supportedWeightTypes),
                                   reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: RecurrentToCellWeights "
                                   "is not a supported type.");
     supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetRecurrentToOutputWeights(), supportedWeightTypes),
                                   reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: RecurrentToOutputWeights "
                                   "is not a supported type.");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetForgetGateBias()), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input and ForgetGateBias types "
                                   "are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetCellBias()), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input and CellBias types are mismatched");
     supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetOutputGateBias()), reasonIfUnsupported,
                                   "Reference UnidirectionalSequenceLstm: input and OutputGateBias types "
                                   "are mismatched");
     if (!descriptor.m_CifgEnabled)
     {
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetInputToInputWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: InputToInputWeights "
                                       "is not a supported type.");
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetRecurrentToInputWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: RecurrentToInputWeights "
                                       "is not a supported type.");
         supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetInputGateBias()), reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: input and InputGateBias types "
                                       "are mismatched");
         if (descriptor.m_PeepholeEnabled)
         {
             supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetCellToInputWeights(), supportedWeightTypes),
                                           reasonIfUnsupported,
                                           "Reference UnidirectionalSequenceLstm: CellToInputWeights "
                                           "is not a supported type.");
         }
     }
     if (descriptor.m_PeepholeEnabled)
     {
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetCellToForgetWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: CellToForgetWeights "
                                       "is not a supported type.");
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetCellToOutputWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: CellToOutputWeights "
                                       "is not a supported type.");
     }
     if (descriptor.m_ProjectionEnabled)
     {
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetProjectionWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: ProjectionWeights "
                                       "is not a supported type.");
         if (paramsInfo.m_ProjectionBias != nullptr)
         {
             supported &= CheckSupportRule(TypesAreEqual(input, paramsInfo.GetProjectionBias()), reasonIfUnsupported,
                                           "Reference UnidirectionalSequenceLstm: input and ProjectionBias types "
                                           "are mismatched");
         }
     }
     if (descriptor.m_LayerNormEnabled)
     {
         if (!descriptor.m_CifgEnabled)
         {
             supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetInputLayerNormWeights(), supportedWeightTypes),
                                           reasonIfUnsupported,
                                           "Reference UnidirectionalSequenceLstm: InputLayerNormWeights "
                                           "is not a supported type.");
         }
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetForgetLayerNormWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: ForgetLayerNormWeights "
                                       "is not a supported type.");
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetCellLayerNormWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: CellLayerNormWeights "
                                       "is not a supported type.");
         supported &= CheckSupportRule(TypeAnyOf(paramsInfo.GetOutputLayerNormWeights(), supportedWeightTypes),
                                       reasonIfUnsupported,
                                       "Reference UnidirectionalSequenceLstm: OutputLayerNormWeights "
                                       "is not a supported type.");
     }
     return supported;
 }
The documentation for this class was generated from the following files:
src/backends/reference/RefLayerSupport.hpp
src/backends/reference/RefLayerSupport.cpp