ArmNN: IProfilingService Class Reference
IProfilingService Class Reference abstract
#include <IProfilingService.hpp>
Public Member Functions
virtual ~IProfilingService ()
virtual std::unique_ptr< ISendTimelinePacket > GetSendTimelinePacket () const =0
virtual const ICounterMappings & GetCounterMappings () const =0
virtual ISendCounterPacket & GetSendCounterPacket ()=0
virtual bool IsProfilingEnabled () const =0
virtual CaptureData GetCaptureData ()=0
Public Member Functions inherited from IProfilingServiceStatus
virtual void NotifyProfilingServiceActive ()=0
virtual void WaitForProfilingServiceActivation (unsigned int timeout)=0
virtual ~IProfilingServiceStatus ()
Detailed Description
Definition at line 21 of file IProfilingService.hpp.
Constructor & Destructor Documentation
~IProfilingService()
virtual ~IProfilingService () inline virtual
Definition at line 24 of file IProfilingService.hpp.
References IProfilingService::GetCaptureData(), IProfilingService::GetCounterMappings(), IProfilingService::GetSendCounterPacket(), IProfilingService::GetSendTimelinePacket(), and IProfilingService::IsProfilingEnabled().
 {};
Member Function Documentation
GetCaptureData()
virtual CaptureData GetCaptureData () pure virtual
Implemented in MockProfilingService, and ProfilingService.
Referenced by IProfilingService::~IProfilingService().
GetCounterMappings()
virtual const ICounterMappings& GetCounterMappings () const pure virtual
Implemented in MockProfilingService, and ProfilingService.
Referenced by IProfilingService::~IProfilingService().
GetSendCounterPacket()
virtual ISendCounterPacket& GetSendCounterPacket () pure virtual
Implemented in MockProfilingService, and ProfilingService.
Referenced by IProfilingService::~IProfilingService().
GetSendTimelinePacket()
virtual std::unique_ptr<ISendTimelinePacket> GetSendTimelinePacket () const pure virtual
Implemented in MockProfilingService, and ProfilingService.
Referenced by IProfilingService::~IProfilingService().
IsProfilingEnabled()
virtual bool IsProfilingEnabled () const pure virtual
Implemented in MockProfilingService, and ProfilingService.
Referenced by IProfilingService::~IProfilingService().
The documentation for this class was generated from the following file:
src/profiling/IProfilingService.hpp