ArmNN: SampleTensorHandle Class Reference
SampleTensorHandle Class Reference
#include <SampleTensorHandle.hpp>
Public Member Functions
SampleTensorHandle (const armnn::TensorInfo &tensorInfo, std::shared_ptr< SampleMemoryManager > &memoryManager)
SampleTensorHandle (const armnn::TensorInfo &tensorInfo, armnn::MemorySourceFlags importFlags)
~SampleTensorHandle ()
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
armnn::TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
armnn::TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
const armnn::TensorInfo & GetTensorInfo () const
virtual armnn::MemorySourceFlags GetImportFlags () const override
Get flags describing supported import sources.
virtual bool Import (void *memory, armnn::MemorySource source) override
Import externally allocated memory.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
Detailed Description
Definition at line 15 of file SampleTensorHandle.hpp.
Constructor & Destructor Documentation
SampleTensorHandle() [1/2]
SampleTensorHandle (const armnn::TensorInfo & tensorInfo, std::shared_ptr< SampleMemoryManager > & memoryManager)
Definition at line 11 of file SampleTensorHandle.cpp.
Referenced by SampleTensorHandle::GetImportFlags().
     : m_TensorInfo(tensorInfo),
       m_MemoryManager(memoryManager),
       m_Pool(nullptr),
       m_UnmanagedMemory(nullptr),
       m_ImportFlags(static_cast<armnn::MemorySourceFlags>(armnn::MemorySource::Undefined)),
       m_Imported(false)
 {
 }
SampleTensorHandle() [2/2]
SampleTensorHandle (const armnn::TensorInfo & tensorInfo, armnn::MemorySourceFlags importFlags)
Definition at line 23 of file SampleTensorHandle.cpp.
     : m_TensorInfo(tensorInfo),
       m_MemoryManager(nullptr),
       m_Pool(nullptr),
       m_UnmanagedMemory(nullptr),
       m_ImportFlags(importFlags),
       m_Imported(true)
 {
 }
~SampleTensorHandle()
~SampleTensorHandle ()
Definition at line 35 of file SampleTensorHandle.cpp.
 {
     if (!m_Pool)
     {
         // unmanaged
         if (!m_Imported)
         {
             ::operator delete(m_UnmanagedMemory);
         }
     }
 }
Member Function Documentation
Allocate()
void Allocate () override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 52 of file SampleTensorHandle.cpp.
References TensorInfo::GetNumBytes().
 {
     if (!m_UnmanagedMemory)
     {
         if (!m_Pool)
         {
             // unmanaged
             m_UnmanagedMemory = ::operator new(m_TensorInfo.GetNumBytes());
         }
         else
         {
             m_MemoryManager->Allocate(m_Pool);
         }
     }
     else
     {
         throw armnn::InvalidArgumentException("SampleTensorHandle::Allocate Trying to allocate a "
                                               "SampleTensorHandle that already has allocated "
                                               "memory.");
     }
 }
GetImportFlags()
virtual armnn::MemorySourceFlags GetImportFlags () const inline override virtual
Get flags describing supported import sources.
Reimplemented from ITensorHandle.
Definition at line 54 of file SampleTensorHandle.hpp.
References SampleTensorHandle::Import(), and SampleTensorHandle::SampleTensorHandle().
     {
         return m_ImportFlags;
     }
GetParent()
virtual ITensorHandle* GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Definition at line 28 of file SampleTensorHandle.hpp.
References SampleTensorHandle::Map().
     {
         return nullptr;
     }
GetShape()
armnn::TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Definition at line 44 of file SampleTensorHandle.hpp.
References TensorInfo::GetShape().
     {
         return m_TensorInfo.GetShape();
     }
GetStrides()
armnn::TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Definition at line 39 of file SampleTensorHandle.hpp.
References armnn::GetUnpaddedTensorStrides().
     {
         return GetUnpaddedTensorStrides(m_TensorInfo);
     }
GetTensorInfo()
const armnn::TensorInfo& GetTensorInfo () const inline
Definition at line 49 of file SampleTensorHandle.hpp.
Referenced by sdb::GetTensorInfo().
     {
         return m_TensorInfo;
     }
Import()
bool Import (void * memory, armnn::MemorySource source) override virtual
Import externally allocated memory.
Parameters
memory base address of the memory being imported.
source source of the allocation for the memory being imported.
Returns
true on success or false on failure
Reimplemented from ITensorHandle.
Definition at line 91 of file SampleTensorHandle.cpp.
References ARMNN_ASSERT, TensorInfo::GetNumBytes(), and armnn::Malloc.
Referenced by SampleTensorHandle::GetImportFlags().
 {
     if (m_ImportFlags & static_cast<armnn::MemorySourceFlags>(source))
     {
         if (source == armnn::MemorySource::Malloc)
         {
             // Check memory alignment
             constexpr uintptr_t alignment = sizeof(size_t);
             if (reinterpret_cast<uintptr_t>(memory) % alignment)
             {
                 if (m_Imported)
                 {
                     m_Imported = false;
                     m_UnmanagedMemory = nullptr;
                 }
                 return false;
             }
             // m_UnmanagedMemory not yet allocated.
             if (!m_Imported && !m_UnmanagedMemory)
             {
                 m_UnmanagedMemory = memory;
                 m_Imported = true;
                 return true;
             }
             // m_UnmanagedMemory initially allocated with Allocate().
             if (!m_Imported && m_UnmanagedMemory)
             {
                 return false;
             }
             // m_UnmanagedMemory previously imported.
             if (m_Imported)
             {
                 m_UnmanagedMemory = memory;
                 return true;
             }
         }
     }
     return false;
 }
Manage()
void Manage () override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 47 of file SampleTensorHandle.cpp.
References TensorInfo::GetNumBytes().
 {
     m_Pool = m_MemoryManager->Manage(m_TensorInfo.GetNumBytes());
 }
Map()
const void * Map (bool blocking) const override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Definition at line 74 of file SampleTensorHandle.cpp.
Referenced by SampleTensorHandle::GetParent().
 {
     return GetPointer();
 }
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Definition at line 36 of file SampleTensorHandle.hpp.
     {}
The documentation for this class was generated from the following files:
src/dynamic/sample/SampleTensorHandle.hpp
src/dynamic/sample/SampleTensorHandle.cpp