ArmNN: YoloTestCase< Model > Class Template Reference
YoloTestCase< Model > Class Template Reference
#include <YoloInferenceTest.hpp>
Public Member Functions
YoloTestCase (Model &model, unsigned int testCaseId, YoloTestCaseData &testCaseData)
virtual TestCaseResult ProcessResult (const InferenceTestOptions &options) override
Public Member Functions inherited from InferenceModelTestCase< Model >
InferenceModelTestCase (Model &model, unsigned int testCaseId, const std::vector< armnnUtils::TContainer > &inputs, const std::vector< unsigned int > &outputSizes)
virtual void Run () override
Public Member Functions inherited from IInferenceTestCase
virtual ~IInferenceTestCase ()
Additional Inherited Members
Protected Member Functions inherited from InferenceModelTestCase< Model >
unsigned int GetTestCaseId () const
const std::vector< armnnUtils::TContainer > & GetOutputs () const
Detailed Description
template<typename Model>
class YoloTestCase< Model >
Definition at line 21 of file YoloInferenceTest.hpp.
Constructor & Destructor Documentation
YoloTestCase()
YoloTestCase (Model & model, unsigned int testCaseId, YoloTestCaseData & testCaseData) inline
Definition at line 24 of file YoloInferenceTest.hpp.
References YoloTestCaseData::m_InputImage, and YoloOutputSize.
      : InferenceModelTestCase<Model>(model, testCaseId, { std::move(testCaseData.m_InputImage) }, { YoloOutputSize })
      , m_TopObjectDetections(std::move(testCaseData.m_TopObjectDetections))
     {
     }
Member Function Documentation
ProcessResult()
virtual TestCaseResult ProcessResult (const InferenceTestOptions & options) inline override virtual
Implements IInferenceTestCase.
Definition at line 32 of file YoloInferenceTest.hpp.
References ARMNN_ASSERT, ARMNN_LOG, InferenceModelTestCase< Model >::GetOutputs(), InferenceModelTestCase< Model >::GetTestCaseId(), armnn::IgnoreUnused(), YoloDetectedObject::m_Box, YoloDetectedObject::m_Class, YoloDetectedObject::m_Confidence, YoloBoundingBox::m_H, YoloBoundingBox::m_W, YoloBoundingBox::m_X, YoloBoundingBox::m_Y, armnnUtils::within_percentage_tolerance(), YoloImageHeight, YoloImageWidth, and YoloOutputSize.
     {
         armnn::IgnoreUnused(options);
         const std::vector<float>& output = mapbox::util::get<std::vector<float>>(this->GetOutputs()[0]);
         ARMNN_ASSERT(output.size() == YoloOutputSize);
         constexpr unsigned int gridSize = 7;
         constexpr unsigned int numClasses = 20;
         constexpr unsigned int numScales = 2;
         const float* outputPtr =  output.data();
         // Range 0-980. Class probabilities. 7x7x20
         vector<vector<vector<float>>> classProbabilities(gridSize, vector<vector<float>>(gridSize,
                                                          vector<float>(numClasses)));
         for (unsigned int y = 0; y < gridSize; ++y)
         {
             for (unsigned int x = 0; x < gridSize; ++x)
             {
                 for (unsigned int c = 0; c < numClasses; ++c)
                 {
                     classProbabilities[y][x][c] = *outputPtr++;
                 }
             }
         }
         // Range 980-1078. Scales. 7x7x2
         vector<vector<vector<float>>> scales(gridSize, vector<vector<float>>(gridSize, vector<float>(numScales)));
         for (unsigned int y = 0; y < gridSize; ++y)
         {
             for (unsigned int x = 0; x < gridSize; ++x)
             {
                 for (unsigned int s = 0; s < numScales; ++s)
                 {
                     scales[y][x][s] = *outputPtr++;
                 }
             }
         }
         // Range 1078-1469. Bounding boxes. 7x7x2x4
         constexpr float imageWidthAsFloat = static_cast<float>(YoloImageWidth);
         constexpr float imageHeightAsFloat = static_cast<float>(YoloImageHeight);
         vector<vector<vector<vector<float>>>> boxes(gridSize, vector<vector<vector<float>>>
             (gridSize, vector<vector<float>>(numScales, vector<float>(4))));
         for (unsigned int y = 0; y < gridSize; ++y)
         {
             for (unsigned int x = 0; x < gridSize; ++x)
             {
                 for (unsigned int s = 0; s < numScales; ++s)
                 {
                     float bx = *outputPtr++;
                     float by = *outputPtr++;
                     float bw = *outputPtr++;
                     float bh = *outputPtr++;
                     boxes[y][x][s][0] = ((bx + static_cast<float>(x)) / 7.0f) * imageWidthAsFloat;
                     boxes[y][x][s][1] = ((by + static_cast<float>(y)) / 7.0f) * imageHeightAsFloat;
                     boxes[y][x][s][2] = bw * bw * static_cast<float>(imageWidthAsFloat);
                     boxes[y][x][s][3] = bh * bh * static_cast<float>(imageHeightAsFloat);
                 }
             }
         }
         ARMNN_ASSERT(output.data() + YoloOutputSize == outputPtr);
         std::vector<YoloDetectedObject> detectedObjects;
         detectedObjects.reserve(gridSize * gridSize * numScales * numClasses);
         for (unsigned int y = 0; y < gridSize; ++y)
         {
             for (unsigned int x = 0; x < gridSize; ++x)
             {
                 for (unsigned int s = 0; s < numScales; ++s)
                 {
                     for (unsigned int c = 0; c < numClasses; ++c)
                     {
                         // Resolved confidence: class probabilities * scales.
                         const float confidence = classProbabilities[y][x][c] * scales[y][x][s];
                         // Resolves bounding box and stores.
                         YoloBoundingBox box;
                         box.m_X = boxes[y][x][s][0];
                         box.m_Y = boxes[y][x][s][1];
                         box.m_W = boxes[y][x][s][2];
                         box.m_H = boxes[y][x][s][3];
                         detectedObjects.emplace_back(c, box, confidence);
                     }
                 }
             }
         }
         // Sorts detected objects by confidence.
         std::sort(detectedObjects.begin(), detectedObjects.end(),
             [](const YoloDetectedObject& a, const YoloDetectedObject& b)
             {
                 // Sorts by largest confidence first, then by class.
                 return a.m_Confidence > b.m_Confidence
                     || (a.m_Confidence == b.m_Confidence && a.m_Class > b.m_Class);
             });
         // Checks the top N detections.
         auto outputIt  = detectedObjects.begin();
         auto outputEnd = detectedObjects.end();
         for (const YoloDetectedObject& expectedDetection : m_TopObjectDetections)
         {
             if (outputIt == outputEnd)
             {
                 // Somehow expected more things to check than detections found by the model.
                 return TestCaseResult::Abort;
             }
             const YoloDetectedObject& detectedObject = *outputIt;
             if (detectedObject.m_Class != expectedDetection.m_Class)
             {
                 ARMNN_LOG(error) << "Prediction for test case " << this->GetTestCaseId() <<
                     " is incorrect: Expected (" << expectedDetection.m_Class << ")" <<
                     " but predicted (" << detectedObject.m_Class << ")";
                 return TestCaseResult::Failed;
             }
             if (!armnnUtils::within_percentage_tolerance(detectedObject.m_Box.m_X, expectedDetection.m_Box.m_X) ||
                 !armnnUtils::within_percentage_tolerance(detectedObject.m_Box.m_Y, expectedDetection.m_Box.m_Y) ||
                 !armnnUtils::within_percentage_tolerance(detectedObject.m_Box.m_W, expectedDetection.m_Box.m_W) ||
                 !armnnUtils::within_percentage_tolerance(detectedObject.m_Box.m_H, expectedDetection.m_Box.m_H) ||
                 !armnnUtils::within_percentage_tolerance(detectedObject.m_Confidence, expectedDetection.m_Confidence))
             {
                 ARMNN_LOG(error) << "Detected bounding box for test case " << this->GetTestCaseId() <<
                     " is incorrect";
                 return TestCaseResult::Failed;
             }
             ++outputIt;
         }
         return TestCaseResult::Ok;
     }
The documentation for this class was generated from the following file:
tests/YoloInferenceTest.hpp