ArmNN: TestBackendRegistry Class Reference
TestBackendRegistry Class Reference
#include <DynamicBackendTests.hpp>
Public Member Functions
TestBackendRegistry ()
~TestBackendRegistry ()
Public Member Functions inherited from BackendRegistry
void Register (const BackendId &id, FactoryFunction factory)
bool IsBackendRegistered (const BackendId &id) const
FactoryFunction GetFactory (const BackendId &id) const
size_t Size () const
BackendIdSet GetBackendIds () const
std::string GetBackendIdsAsString () const
void SetProfilingService (armnn::Optional< profiling::ProfilingService &> profilingService)
void RegisterAllocator (const BackendId &id, std::shared_ptr< ICustomAllocator > alloc)
std::unordered_map< BackendId, std::shared_ptr< ICustomAllocator > > GetAllocators ()
void RegisterMemoryOptimizerStrategy (const BackendId &id, std::shared_ptr< IMemoryOptimizerStrategy > strategy)
MemoryOptimizerStrategiesMapRef GetMemoryOptimizerStrategies ()
BackendRegistry ()
virtual ~BackendRegistry ()
void Deregister (const BackendId &id)
void DeregisterAllocator (const BackendId &id)
void DeregisterMemoryOptimizerStrategy (const BackendId &id)
Additional Inherited Members
Public Types inherited from BackendRegistry
using PointerType = IBackendInternalUniquePtr
using FactoryFunction = std::function< PointerType()>
Protected Types inherited from BackendRegistry
using FactoryStorage = std::unordered_map< BackendId, FactoryFunction >
Static Protected Member Functions inherited from BackendRegistry
static void Swap (BackendRegistry &instance, FactoryStorage &other)
For testing only.
Detailed Description
Definition at line 96 of file DynamicBackendTests.hpp.
Constructor & Destructor Documentation
TestBackendRegistry()
TestBackendRegistry () inline
Definition at line 99 of file DynamicBackendTests.hpp.
References armnn::BackendRegistryInstance().
                           : armnn::BackendRegistry()
     {
         Swap(armnn::BackendRegistryInstance(), m_TempStorage);
     }
~TestBackendRegistry()
~TestBackendRegistry () inline
Definition at line 104 of file DynamicBackendTests.hpp.
References armnn::BackendRegistryInstance(), and GetUnitTestExecutablePath().
     {
         Swap(armnn::BackendRegistryInstance(), m_TempStorage);
     }
The documentation for this class was generated from the following file:
src/backends/backendsCommon/test/DynamicBackendTests.hpp