ArmNN: BackendProfiling Class Reference
BackendProfiling Class Reference
#include <BackendProfiling.hpp>
Public Member Functions
BackendProfiling (const IRuntime::CreationOptions &options, ProfilingService &profilingService, const BackendId &backendId)
~BackendProfiling ()
std::unique_ptr< IRegisterBackendCounters > GetCounterRegistrationInterface (uint16_t currentMaxGlobalCounterID) override
std::unique_ptr< ISendTimelinePacket > GetSendTimelinePacket () override
IProfilingGuidGenerator & GetProfilingGuidGenerator () override
void ReportCounters (const std::vector< Timestamp > &) override
CounterStatus GetCounterStatus (uint16_t backendCounterId) override
std::vector< CounterStatus > GetActiveCounters () override
bool IsProfilingEnabled () const override
Public Member Functions inherited from IBackendProfiling
virtual ~IBackendProfiling ()
Detailed Description
Definition at line 17 of file BackendProfiling.hpp.
Constructor & Destructor Documentation
BackendProfiling()
BackendProfiling (const IRuntime::CreationOptions & options, ProfilingService & profilingService, const BackendId & backendId) inline
Definition at line 20 of file BackendProfiling.hpp.
             : m_Options(options),
               m_ProfilingService(profilingService),
               m_BackendId(backendId) {}
~BackendProfiling()
~BackendProfiling () inline
Definition at line 27 of file BackendProfiling.hpp.
References BackendProfiling::GetActiveCounters(), BackendProfiling::GetCounterRegistrationInterface(), BackendProfiling::GetCounterStatus(), BackendProfiling::GetProfilingGuidGenerator(), BackendProfiling::GetSendTimelinePacket(), BackendProfiling::IsProfilingEnabled(), and BackendProfiling::ReportCounters().
     {}
Member Function Documentation
GetActiveCounters()
std::vector< CounterStatus > GetActiveCounters () override virtual
Implements IBackendProfiling.
Definition at line 67 of file BackendProfiling.cpp.
References ICounterMappings::GetBackendId(), ProfilingService::GetCaptureData(), CaptureData::GetCapturePeriod(), CaptureData::GetCounterIds(), and ProfilingService::GetCounterMappings().
Referenced by BackendProfiling::~BackendProfiling().
 {
     CaptureData captureData = m_ProfilingService.GetCaptureData();
     const std::vector<uint16_t>& globalCounterIds = captureData.GetCounterIds();
     std::vector<CounterStatus> activeCounterIds;
     for (auto globalCounterId : globalCounterIds) {
         // Get pair of local counterId and backendId using globalCounterId
         const std::pair<uint16_t, armnn::BackendId>& backendCounterIdPair =
                 m_ProfilingService.GetCounterMappings().GetBackendId(globalCounterId);
         if (backendCounterIdPair.second == m_BackendId)
         {
             activeCounterIds.emplace_back(backendCounterIdPair.first,
                                           globalCounterId,
                                           true,
                                           captureData.GetCapturePeriod());
         }
     }
     return activeCounterIds;
 }
GetCounterRegistrationInterface()
std::unique_ptr< IRegisterBackendCounters > GetCounterRegistrationInterface (uint16_t currentMaxGlobalCounterID) override virtual
Implements IBackendProfiling.
Definition at line 16 of file BackendProfiling.cpp.
Referenced by BackendProfiling::~BackendProfiling().
 {
     return std::make_unique<RegisterBackendCounters>(
         RegisterBackendCounters(currentMaxGlobalCounterID, m_BackendId, m_ProfilingService));
 }
GetCounterStatus()
CounterStatus GetCounterStatus (uint16_t backendCounterId) override virtual
Implements IBackendProfiling.
Definition at line 51 of file BackendProfiling.cpp.
References ProfilingService::GetCaptureData(), CaptureData::GetCapturePeriod(), ProfilingService::GetCounterMappings(), ICounterMappings::GetGlobalId(), CaptureData::IsCounterIdInCaptureData(), CounterStatus::m_Enabled, and CounterStatus::m_SamplingRateInMicroseconds.
Referenced by BackendProfiling::~BackendProfiling().
 {
     uint16_t globalCounterId = m_ProfilingService.GetCounterMappings().GetGlobalId(backendCounterId, m_BackendId);
     CaptureData captureData = m_ProfilingService.GetCaptureData();
     CounterStatus counterStatus(backendCounterId, globalCounterId, false, 0);
     if (captureData.IsCounterIdInCaptureData(globalCounterId))
     {
         counterStatus.m_Enabled = true;
         counterStatus.m_SamplingRateInMicroseconds = captureData.GetCapturePeriod();
     }
     return counterStatus;
 }
GetProfilingGuidGenerator()
IProfilingGuidGenerator & GetProfilingGuidGenerator () override virtual
Implements IBackendProfiling.
Definition at line 27 of file BackendProfiling.cpp.
Referenced by BackendProfiling::~BackendProfiling().
 {
     // The profiling service is our Guid Generator.
     return m_ProfilingService;
 }
GetSendTimelinePacket()
std::unique_ptr< ISendTimelinePacket > GetSendTimelinePacket () override virtual
Implements IBackendProfiling.
Definition at line 22 of file BackendProfiling.cpp.
References ProfilingService::GetSendTimelinePacket().
Referenced by BackendProfiling::~BackendProfiling().
 {
     return m_ProfilingService.GetSendTimelinePacket();
 }
IsProfilingEnabled()
bool IsProfilingEnabled () const override virtual
Implements IBackendProfiling.
Definition at line 90 of file BackendProfiling.cpp.
References ProfilingService::IsProfilingEnabled().
Referenced by BackendProfiling::~BackendProfiling().
 {
     return m_ProfilingService.IsProfilingEnabled();
 }
ReportCounters()
void ReportCounters (const std::vector< Timestamp > & timestamps) override virtual
Implements IBackendProfiling.
Definition at line 33 of file BackendProfiling.cpp.
References ProfilingService::GetCounterMappings(), ICounterMappings::GetGlobalId(), ProfilingService::GetSendCounterPacket(), and ISendCounterPacket::SendPeriodicCounterCapturePacket().
Referenced by BackendProfiling::~BackendProfiling().
 {
     for (const auto& timestampInfo : timestamps)
     {
         std::vector<CounterValue> backendCounterValues = timestampInfo.counterValues;
         for_each(backendCounterValues.begin(), backendCounterValues.end(), [&](CounterValue& backendCounterValue)
         {
             // translate the counterId to globalCounterId
             backendCounterValue.counterId = m_ProfilingService.GetCounterMappings().GetGlobalId(
                 backendCounterValue.counterId, m_BackendId);
         });
         // Send Periodic Counter Capture Packet for the Timestamp
         m_ProfilingService.GetSendCounterPacket().SendPeriodicCounterCapturePacket(
             timestampInfo.timestamp, backendCounterValues);
     }
 }
The documentation for this class was generated from the following files:
src/profiling/backends/BackendProfiling.hpp
src/profiling/backends/BackendProfiling.cpp