ArmNN: StreamMetaDataProcessor Class Reference
StreamMetaDataProcessor Class Reference
#include <FileOnlyProfilingConnection.hpp>
Public Member Functions
StreamMetaDataProcessor (FileOnlyProfilingConnection *fileOnlyProfilingConnection)
std::vector< uint32_t > GetHeadersAccepted () override
void HandlePacket (const arm::pipe::Packet &packet) override
process the packet
Public Member Functions inherited from ILocalPacketHandler
virtual ~ILocalPacketHandler ()
virtual void SetConnection (IInternalProfilingConnection *profilingConnection)
Set a profiling connection on the handler.
Detailed Description
Definition at line 32 of file FileOnlyProfilingConnection.hpp.
Constructor & Destructor Documentation
StreamMetaDataProcessor()
StreamMetaDataProcessor (FileOnlyProfilingConnection * fileOnlyProfilingConnection) inline explicit
Definition at line 35 of file FileOnlyProfilingConnection.hpp.
References StreamMetaDataProcessor::GetHeadersAccepted(), and StreamMetaDataProcessor::HandlePacket().
                                                                                                :
             m_FileOnlyProfilingConnection(fileOnlyProfilingConnection),
             m_MetaDataPacketHeader(ConstructHeader(0, 0)) {};
Member Function Documentation
GetHeadersAccepted()
std::vector< uint32_t > GetHeadersAccepted () override virtual
Returns
lists the headers of the packets that this handler accepts only these packets will get sent to this handler. If this function returns an empty list then ALL packets will be sent to the PacketHandler i.e. a universal handler.
Implements ILocalPacketHandler.
Definition at line 23 of file FileOnlyProfilingConnection.cpp.
Referenced by StreamMetaDataProcessor::StreamMetaDataProcessor().
 {
     std::vector<uint32_t> headers;
     headers.push_back(m_MetaDataPacketHeader);
     return headers;
 }
HandlePacket()
void HandlePacket (const arm::pipe::Packet & packet) override virtual
process the packet
Implements ILocalPacketHandler.
Definition at line 30 of file FileOnlyProfilingConnection.cpp.
References armnn::profiling::BeWire, armnn::profiling::LeWire, FileOnlyProfilingConnection::ReturnPacket(), and FileOnlyProfilingConnection::SetEndianess().
Referenced by StreamMetaDataProcessor::StreamMetaDataProcessor().
 {
     if (packet.GetHeader() != m_MetaDataPacketHeader)
     {
         throw arm::pipe::ProfilingException("StreamMetaDataProcessor can only handle Stream Meta Data Packets");
     }
     // determine the endianness of the protocol
     TargetEndianness endianness;
     if (ToUint32(packet.GetData(),TargetEndianness::BeWire) == arm::pipe::PIPE_MAGIC)
     {
         endianness = TargetEndianness::BeWire;
     }
     else if (ToUint32(packet.GetData(), TargetEndianness::LeWire) == arm::pipe::PIPE_MAGIC)
     {
         endianness = TargetEndianness::LeWire;
     }
     else
     {
         throw arm::pipe::ProfilingException("Protocol read error. Unable to read the PIPE_MAGIC value.");
     }
     m_FileOnlyProfilingConnection->SetEndianess(endianness);
     // send back the acknowledgement
     std::unique_ptr<unsigned char[]> uniqueNullPtr = nullptr;
     arm::pipe::Packet returnPacket(0x10000, 0, uniqueNullPtr);
     m_FileOnlyProfilingConnection->ReturnPacket(returnPacket);
 }
The documentation for this class was generated from the following files:
src/profiling/FileOnlyProfilingConnection.hpp
src/profiling/FileOnlyProfilingConnection.cpp