ArmNN: TestQLstmLayerVisitor Class Reference
TestQLstmLayerVisitor Class Reference
#include <ConstTensorLayerVisitor.hpp>
Public Member Functions
TestQLstmLayerVisitor (const QLstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from LstmVisitor
LstmVisitor (const LstmInputParams &params, const char *name=nullptr)
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Protected Member Functions
void CheckDescriptor (const QLstmDescriptor &descriptor)
Protected Member Functions inherited from LstmVisitor
template<typename LayerType >
void CheckInputParameters (const LayerType *layer, const LstmInputParams &inputParams)
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckConstTensors (const ConstTensor &expected, const ConstTensorHandle &actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const ConstTensor *actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const std::shared_ptr< ConstTensorHandle > actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from StrategyBase< NoThrowStrategy >
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Additional Inherited Members
Protected Attributes inherited from LstmVisitor
LstmInputParams m_InputParams
Protected Attributes inherited from StrategyBase< NoThrowStrategy >
NoThrowStrategy m_DefaultStrategy
Detailed Description
Definition at line 386 of file ConstTensorLayerVisitor.hpp.
Constructor & Destructor Documentation
TestQLstmLayerVisitor()
TestQLstmLayerVisitor (const QLstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr) inline explicit
Definition at line 389 of file ConstTensorLayerVisitor.hpp.
             : LstmVisitor(params, name)
             , m_Descriptor(descriptor)
     {}
Member Function Documentation
CheckDescriptor()
void CheckDescriptor (const QLstmDescriptor & descriptor) protected
Definition at line 61 of file ConstTensorLayerVisitor.cpp.
References QLstmDescriptor::m_CellClip, QLstmDescriptor::m_CifgEnabled, QLstmDescriptor::m_PeepholeEnabled, QLstmDescriptor::m_ProjectionClip, and QLstmDescriptor::m_ProjectionEnabled.
 {
     CHECK(m_Descriptor.m_CellClip == descriptor.m_CellClip);
     CHECK(m_Descriptor.m_ProjectionClip == descriptor.m_ProjectionClip);
     CHECK(m_Descriptor.m_CifgEnabled == descriptor.m_CifgEnabled);
     CHECK(m_Descriptor.m_PeepholeEnabled == descriptor.m_PeepholeEnabled);
     CHECK(m_Descriptor.m_ProjectionEnabled == descriptor.m_ProjectionEnabled);
 }
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Reimplemented from StrategyBase< NoThrowStrategy >.
Definition at line 396 of file ConstTensorLayerVisitor.hpp.
References NoThrowStrategy::Apply(), TestConvolution2dLayerVisitor::CheckDescriptor(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), StrategyBase< NoThrowStrategy >::m_DefaultStrategy, and armnn::QLstm.
     {
         armnn::IgnoreUnused(descriptor, constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::QLstm:
             {
                 CheckLayerPointer(layer);
                 CheckLayerName(name);
                 CheckDescriptor(static_cast<const armnn::QLstmDescriptor&>(descriptor));
                 CheckInputParameters<const QLstmLayer>(PolymorphicDowncast<const QLstmLayer*>(layer), m_InputParams);
                 break;
             }
             default:
             {
                 m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
             }
         }
     }
The documentation for this class was generated from the following files:
src/armnn/test/ConstTensorLayerVisitor.hpp
src/armnn/test/ConstTensorLayerVisitor.cpp