ArmNN: ProfilingServiceRuntimeHelper Class Reference
ProfilingServiceRuntimeHelper Class Reference
#include <ProfilingTestUtils.hpp>
Public Member Functions
ProfilingServiceRuntimeHelper (ProfilingService &profilingService)
~ProfilingServiceRuntimeHelper ()=default
BufferManager & GetProfilingBufferManager ()
void ForceTransitionToState (ProfilingState newState)
Public Member Functions inherited from ProfilingService
ProfilingService (Optional< IReportStructure &> reportStructure=EmptyOptional())
~ProfilingService ()
void ResetExternalProfilingOptions (const ExternalProfilingOptions &options, bool resetProfilingService=false)
ProfilingState ConfigureProfilingService (const ExternalProfilingOptions &options, bool resetProfilingService=false)
void Update ()
void Disconnect ()
void AddBackendProfilingContext (const BackendId backendId, std::shared_ptr< armnn::profiling::IBackendProfilingContext > profilingContext)
void NotifyBackendsForTimelineReporting () override
const ICounterDirectory & GetCounterDirectory () const
ICounterRegistry & GetCounterRegistry ()
ProfilingState GetCurrentState () const
bool IsCounterRegistered (uint16_t counterUid) const override
uint32_t GetAbsoluteCounterValue (uint16_t counterUid) const override
uint32_t GetDeltaCounterValue (uint16_t counterUid) override
uint16_t GetCounterCount () const override
const ICounterMappings & GetCounterMappings () const override
IRegisterCounterMapping & GetCounterMappingRegistry ()
bool IsProfilingEnabled () const override
CaptureData GetCaptureData () override
void SetCaptureData (uint32_t capturePeriod, const std::vector< uint16_t > &counterIds, const std::set< BackendId > &activeBackends)
void SetCounterValue (uint16_t counterUid, uint32_t value) override
uint32_t AddCounterValue (uint16_t counterUid, uint32_t value) override
uint32_t SubtractCounterValue (uint16_t counterUid, uint32_t value) override
uint32_t IncrementCounterValue (uint16_t counterUid) override
ProfilingDynamicGuid NextGuid () override
Return the next random Guid in the sequence.
ProfilingStaticGuid GenerateStaticId (const std::string &str) override
Create a ProfilingStaticGuid based on a hash of the string.
std::unique_ptr< ISendTimelinePacket > GetSendTimelinePacket () const override
ISendCounterPacket & GetSendCounterPacket () override
void ResetGuidGenerator ()
bool IsTimelineReportingEnabled ()
void AddLocalPacketHandler (ILocalPacketHandlerSharedPtr localPacketHandler)
void NotifyProfilingServiceActive () override
void WaitForProfilingServiceActivation (unsigned int timeout) override
Public Member Functions inherited from IReadWriteCounterValues
virtual ~IReadWriteCounterValues ()
Public Member Functions inherited from IReadCounterValues
virtual ~IReadCounterValues ()
Public Member Functions inherited from IWriteCounterValues
virtual ~IWriteCounterValues ()
Public Member Functions inherited from IProfilingService
virtual ~IProfilingService ()
Public Member Functions inherited from IProfilingServiceStatus
virtual ~IProfilingServiceStatus ()
Public Member Functions inherited from INotifyBackends
virtual ~INotifyBackends ()
Public Attributes
armnn::profiling::ProfilingService & m_ProfilingService
Additional Inherited Members
Public Types inherited from ProfilingService
using ExternalProfilingOptions = IRuntime::CreationOptions::ExternalProfilingOptions
using IProfilingConnectionFactoryPtr = std::unique_ptr< IProfilingConnectionFactory >
using IProfilingConnectionPtr = std::unique_ptr< IProfilingConnection >
using CounterIndices = std::vector< std::atomic< uint32_t > * >
using CounterValues = std::list< std::atomic< uint32_t > >
using BackendProfilingContext = std::unordered_map< BackendId, std::shared_ptr< armnn::profiling::IBackendProfilingContext > >
Static Public Member Functions inherited from ProfilingService
static ProfilingDynamicGuid GetNextGuid ()
static ProfilingStaticGuid GetStaticId (const std::string &str)
Protected Member Functions inherited from ProfilingService
void SwapProfilingConnectionFactory (ProfilingService &instance, IProfilingConnectionFactory *other, IProfilingConnectionFactory *&backup)
IProfilingConnection * GetProfilingConnection (ProfilingService &instance)
void TransitionToState (ProfilingService &instance, ProfilingState newState)
bool WaitForPacketSent (ProfilingService &instance, uint32_t timeout=1000)
BufferManager & GetBufferManager (ProfilingService &instance)
Detailed Description
Definition at line 72 of file ProfilingTestUtils.hpp.
Constructor & Destructor Documentation
ProfilingServiceRuntimeHelper()
ProfilingServiceRuntimeHelper (ProfilingService & profilingService) inline
Definition at line 75 of file ProfilingTestUtils.hpp.
     : m_ProfilingService(profilingService) {}
~ProfilingServiceRuntimeHelper()
~ProfilingServiceRuntimeHelper () default
Member Function Documentation
ForceTransitionToState()
void ForceTransitionToState (ProfilingState newState) inline
Definition at line 85 of file ProfilingTestUtils.hpp.
Referenced by TEST_SUITE(), and VerifyPostOptimisationStructureTestImpl().
     {
         TransitionToState(m_ProfilingService, newState);
     }
GetProfilingBufferManager()
BufferManager& GetProfilingBufferManager () inline
Definition at line 79 of file ProfilingTestUtils.hpp.
Referenced by TEST_SUITE(), and VerifyPostOptimisationStructureTestImpl().
     {
         return GetBufferManager(m_ProfilingService);
     }
Member Data Documentation
m_ProfilingService
armnn::profiling::ProfilingService& m_ProfilingService
Definition at line 83 of file ProfilingTestUtils.hpp.
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingTestUtils.hpp