ArmNN: ClassifierTestCase< TTestCaseDatabase, TModel > Class Template Reference
ClassifierTestCase< TTestCaseDatabase, TModel > Class Template Reference
#include <InferenceTest.hpp>
Public Member Functions
ClassifierTestCase (int &numInferencesRef, int &numCorrectInferencesRef, const std::vector< unsigned int > &validationPredictions, std::vector< unsigned int > *validationPredictionsOut, TModel &model, unsigned int testCaseId, unsigned int label, std::vector< typename TModel::DataType > modelInput)
virtual TestCaseResult ProcessResult (const InferenceTestOptions &params) override
Public Member Functions inherited from InferenceModelTestCase< TModel >
InferenceModelTestCase (TModel &model, unsigned int testCaseId, const std::vector< armnnUtils::TContainer > &inputs, const std::vector< unsigned int > &outputSizes)
virtual void Run () override
Public Member Functions inherited from IInferenceTestCase
virtual ~IInferenceTestCase ()
Additional Inherited Members
Protected Member Functions inherited from InferenceModelTestCase< TModel >
unsigned int GetTestCaseId () const
const std::vector< armnnUtils::TContainer > & GetOutputs () const
Detailed Description
template<typename TTestCaseDatabase, typename TModel>
class armnn::test::ClassifierTestCase< TTestCaseDatabase, TModel >
Definition at line 151 of file InferenceTest.hpp.
Constructor & Destructor Documentation
ClassifierTestCase()
ClassifierTestCase (int & numInferencesRef, int & numCorrectInferencesRef, const std::vector< unsigned int > & validationPredictions, std::vector< unsigned int > * validationPredictionsOut, TModel & model, unsigned int testCaseId, unsigned int label, std::vector< typename TModel::DataType > modelInput)
Definition at line 33 of file InferenceTest.inl.
References ARMNN_ASSERT_MSG, armnn::Dequantize, and armnn::IgnoreUnused().
     : InferenceModelTestCase<TModel>(
             model, testCaseId, std::vector<armnnUtils::TContainer>{ modelInput }, { model.GetOutputSize() })
     , m_Label(label)
     , m_QuantizationParams(model.GetQuantizationParams())
     , m_NumInferencesRef(numInferencesRef)
     , m_NumCorrectInferencesRef(numCorrectInferencesRef)
     , m_ValidationPredictions(validationPredictions)
     , m_ValidationPredictionsOut(validationPredictionsOut)
 {
 }
Member Function Documentation
ProcessResult()
TestCaseResult ProcessResult (const InferenceTestOptions & params) override virtual
Implements IInferenceTestCase.
Definition at line 124 of file InferenceTest.inl.
References ARMNN_LOG, armnn::error, armnn::test::Failed, InferenceModelTestCase< TModel >::GetOutputs(), InferenceModelTestCase< TModel >::GetTestCaseId(), armnn::info, InferenceTestOptions::m_IterationCount, armnn::numeric_cast(), and armnn::test::Ok.
 {
     auto& output = this->GetOutputs()[0];
     const auto testCaseId = this->GetTestCaseId();
     ClassifierResultProcessor resultProcessor(m_QuantizationParams.first, m_QuantizationParams.second);
     mapbox::util::apply_visitor(resultProcessor, output);
     ARMNN_LOG(info) << "= Prediction values for test #" << testCaseId;
     auto it = resultProcessor.GetResultMap().rbegin();
     for (int i=0; i<5 && it != resultProcessor.GetResultMap().rend(); ++i)
     {
         ARMNN_LOG(info) << "Top(" << (i+1) << ") prediction is " << it->second <<
           " with value: " << (it->first);
         ++it;
     }
     unsigned int prediction = 0;
     mapbox::util::apply_visitor([&](auto&& value)
{
                              prediction = armnn::numeric_cast<unsigned int>(
                                      std::distance(value.begin(), std::max_element(value.begin(), value.end())));
                          },
                          output);
     // If we're just running the defaultTestCaseIds, each one must be classified correctly.
     if (params.m_IterationCount == 0 && prediction != m_Label)
     {
         ARMNN_LOG(error) << "Prediction for test case " << testCaseId << " (" << prediction << ")" <<
             " is incorrect (should be " << m_Label << ")";
         return TestCaseResult::Failed;
     }
     // If a validation file was provided as input, it checks that the prediction matches.
     if (!m_ValidationPredictions.empty() && prediction != m_ValidationPredictions[testCaseId])
     {
         ARMNN_LOG(error) << "Prediction for test case " << testCaseId << " (" << prediction << ")" <<
             " doesn't match the prediction in the validation file (" << m_ValidationPredictions[testCaseId] << ")";
         return TestCaseResult::Failed;
     }
     // If a validation file was requested as output, it stores the predictions.
     if (m_ValidationPredictionsOut)
     {
         m_ValidationPredictionsOut->push_back(prediction);
     }
     // Updates accuracy stats.
     m_NumInferencesRef++;
     if (prediction == m_Label)
     {
         m_NumCorrectInferencesRef++;
     }
     return TestCaseResult::Ok;
 }
The documentation for this class was generated from the following files:
tests/InferenceTest.hpp
tests/InferenceTest.inl