ArmNN: Holder Class Reference
Holder Class Reference
#include <Holder.hpp>
Public Member Functions
Holder ()
CaptureData GetCaptureData () const
void SetCaptureData (uint32_t capturePeriod, const std::vector< uint16_t > &counterIds, const std::set< armnn::BackendId > &activeBackends)
Detailed Description
Definition at line 51 of file Holder.hpp.
Constructor & Destructor Documentation
Holder()
Holder () inline
Definition at line 54 of file Holder.hpp.
         : m_CaptureData() {}
Member Function Documentation
GetCaptureData()
CaptureData GetCaptureData () const
Definition at line 54 of file Holder.cpp.
Referenced by ProfilingService::GetCaptureData(), PeriodicCounterSelectionCommandHandler::operator()(), PeriodicCounterCapture::Stop(), and TEST_SUITE().
 {
     std::lock_guard<std::mutex> lockGuard(m_CaptureThreadMutex);
     return m_CaptureData;
 }
SetCaptureData()
void SetCaptureData (uint32_t capturePeriod, const std::vector< uint16_t > & counterIds, const std::set< armnn::BackendId > & activeBackends)
Definition at line 74 of file Holder.cpp.
Referenced by PeriodicCounterSelectionCommandHandler::operator()(), ProfilingService::SetCaptureData(), and TEST_SUITE().
 {
     std::lock_guard<std::mutex> lockGuard(m_CaptureThreadMutex);
     m_CaptureData.SetCapturePeriod(capturePeriod);
     m_CaptureData.SetCounterIds(counterIds);
     m_CaptureData.SetActiveBackends(activeBackends);
 }
The documentation for this class was generated from the following files:
src/profiling/Holder.hpp
src/profiling/Holder.cpp