ArmNN: ICounterRegistry Class Reference
ICounterRegistry Class Reference abstract
#include <ICounterRegistry.hpp>
Public Member Functions
virtual ~ICounterRegistry ()
virtual const Category * RegisterCategory (const std::string &categoryName)=0
virtual const Device * RegisterDevice (const std::string &deviceName, uint16_t cores, const Optional< std::string > &parentCategoryName)=0
virtual const CounterSet * RegisterCounterSet (const std::string &counterSetName, uint16_t count, const Optional< std::string > &parentCategoryName)=0
virtual const Counter * RegisterCounter (const BackendId &backendId, const uint16_t uid, const std::string &parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string &name, const std::string &description, const Optional< std::string > &units, const Optional< uint16_t > &numberOfCores, const Optional< uint16_t > &deviceUid, const Optional< uint16_t > &counterSetUid)=0
Detailed Description
Definition at line 17 of file ICounterRegistry.hpp.
Constructor & Destructor Documentation
~ICounterRegistry()
virtual ~ICounterRegistry () inline virtual
Definition at line 20 of file ICounterRegistry.hpp.
References ICounterRegistry::RegisterCategory(), ICounterRegistry::RegisterCounter(), ICounterRegistry::RegisterCounterSet(), and ICounterRegistry::RegisterDevice().
 {}
Member Function Documentation
RegisterCategory()
virtual const Category* RegisterCategory (const std::string & categoryName) pure virtual
Implemented in CounterDirectory.
Referenced by RegisterBackendCounters::RegisterCategory(), and ICounterRegistry::~ICounterRegistry().
RegisterCounter()
virtual const Counter* RegisterCounter (const BackendId & backendId, const uint16_t uid, const std::string & parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string & name, const std::string & description, const Optional< std::string > & units, const Optional< uint16_t > & numberOfCores, const Optional< uint16_t > & deviceUid, const Optional< uint16_t > & counterSetUid) pure virtual
Implemented in CounterDirectory.
Referenced by RegisterBackendCounters::RegisterCounter(), and ICounterRegistry::~ICounterRegistry().
RegisterCounterSet()
virtual const CounterSet* RegisterCounterSet (const std::string & counterSetName, uint16_t count, const Optional< std::string > & parentCategoryName) pure virtual
Implemented in CounterDirectory.
Referenced by RegisterBackendCounters::RegisterCounterSet(), and ICounterRegistry::~ICounterRegistry().
RegisterDevice()
virtual const Device* RegisterDevice (const std::string & deviceName, uint16_t cores, const Optional< std::string > & parentCategoryName) pure virtual
Implemented in CounterDirectory.
Referenced by RegisterBackendCounters::RegisterDevice(), and ICounterRegistry::~ICounterRegistry().
The documentation for this class was generated from the following file:
src/profiling/ICounterRegistry.hpp