ArmNN: NeonDivisionWorkload Class Reference
NeonDivisionWorkload Class Reference
#include <NeonDivisionWorkload.hpp>
Public Member Functions
NeonDivisionWorkload (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual void Execute () const override
Public Member Functions inherited from NeonBaseWorkload< DivisionQueueDescriptor >
NeonBaseWorkload (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< DivisionQueueDescriptor >
BaseWorkload (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const DivisionQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Member Functions inherited from NeonBaseWorkload< DivisionQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< DivisionQueueDescriptor >
DivisionQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 22 of file NeonDivisionWorkload.hpp.
Constructor & Destructor Documentation
NeonDivisionWorkload()
NeonDivisionWorkload (const DivisionQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 36 of file NeonDivisionWorkload.cpp.
References armnn::ConvertAdditionalInfoToAclActivationLayerInfo(), BaseWorkload< DivisionQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, and QueueDescriptor::ValidateInputsOutputs().
     : NeonBaseWorkload<DivisionQueueDescriptor>(descriptor, info)
 {
     m_Data.ValidateInputsOutputs("NeonDivisionWorkload", 2, 1);
     arm_compute::ITensor& input0 = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ITensor& input1 = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[1])->GetTensor();
     arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     const arm_compute::ActivationLayerInfo activationInfo = ConvertAdditionalInfoToAclActivationLayerInfo(descriptor);
     m_DivLayer.configure(&input0, &input1, &output, activationInfo);
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 51 of file NeonDivisionWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID, and BaseWorkload< DivisionQueueDescriptor >::GetGuid().
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID("NeonDivisionWorkload_Execute", this->GetGuid());
     m_DivLayer.run();
 }
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonDivisionWorkload.hpp
src/backends/neon/workloads/NeonDivisionWorkload.cpp