ArmNN: ActivationLayerBuilder Struct Reference
ActivationLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ActivationLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::ActivationDescriptor > descriptor)
ActivationLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ActivationLayerBuilder & operator= (const ActivationLayerBuilder &)
flatbuffers::Offset< ActivationLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2551 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ActivationLayer Table
Definition at line 2552 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ActivationLayerBuilder()
ActivationLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2561 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 2555 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateActivationLayer().
{
     fbb_.AddOffset(ActivationLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::ActivationDescriptor > descriptor) inline
Definition at line 2558 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateActivationLayer().
{
     fbb_.AddOffset(ActivationLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<ActivationLayer> Finish () inline
Definition at line 2566 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateActivationLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ActivationLayer>(end);
     return o;
   }
operator=()
ActivationLayerBuilder& operator= (const ActivationLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2553 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2554 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h