ArmNN: UnidirectionalSequenceLstmDescriptorBuilder Struct Reference
UnidirectionalSequenceLstmDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef UnidirectionalSequenceLstmDescriptor Table
Public Member Functions
void add_activationFunc (uint32_t activationFunc)
void add_clippingThresCell (float clippingThresCell)
void add_clippingThresProj (float clippingThresProj)
void add_cifgEnabled (bool cifgEnabled)
void add_peepholeEnabled (bool peepholeEnabled)
void add_projectionEnabled (bool projectionEnabled)
void add_layerNormEnabled (bool layerNormEnabled)
void add_timeMajor (bool timeMajor)
UnidirectionalSequenceLstmDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
UnidirectionalSequenceLstmDescriptorBuilder & operator= (const UnidirectionalSequenceLstmDescriptorBuilder &)
flatbuffers::Offset< UnidirectionalSequenceLstmDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 10196 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef UnidirectionalSequenceLstmDescriptor Table
Definition at line 10197 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
UnidirectionalSequenceLstmDescriptorBuilder()
UnidirectionalSequenceLstmDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 10224 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_activationFunc()
void add_activationFunc (uint32_t activationFunc) inline
Definition at line 10200 of file ArmnnSchema_generated.h.
References VT_ACTIVATIONFUNC.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<uint32_t>(UnidirectionalSequenceLstmDescriptor::VT_ACTIVATIONFUNC, activationFunc, 0);
   }
add_cifgEnabled()
void add_cifgEnabled (bool cifgEnabled) inline
Definition at line 10209 of file ArmnnSchema_generated.h.
References VT_CIFGENABLED.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(UnidirectionalSequenceLstmDescriptor::VT_CIFGENABLED, static_cast<uint8_t>(cifgEnabled), 1);
   }
add_clippingThresCell()
void add_clippingThresCell (float clippingThresCell) inline
Definition at line 10203 of file ArmnnSchema_generated.h.
References VT_CLIPPINGTHRESCELL.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<float>(UnidirectionalSequenceLstmDescriptor::VT_CLIPPINGTHRESCELL, clippingThresCell, 0.0f);
   }
add_clippingThresProj()
void add_clippingThresProj (float clippingThresProj) inline
Definition at line 10206 of file ArmnnSchema_generated.h.
References VT_CLIPPINGTHRESPROJ.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<float>(UnidirectionalSequenceLstmDescriptor::VT_CLIPPINGTHRESPROJ, clippingThresProj, 0.0f);
   }
add_layerNormEnabled()
void add_layerNormEnabled (bool layerNormEnabled) inline
Definition at line 10218 of file ArmnnSchema_generated.h.
References VT_LAYERNORMENABLED.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(UnidirectionalSequenceLstmDescriptor::VT_LAYERNORMENABLED, static_cast<uint8_t>(layerNormEnabled), 0);
   }
add_peepholeEnabled()
void add_peepholeEnabled (bool peepholeEnabled) inline
Definition at line 10212 of file ArmnnSchema_generated.h.
References VT_PEEPHOLEENABLED.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(UnidirectionalSequenceLstmDescriptor::VT_PEEPHOLEENABLED, static_cast<uint8_t>(peepholeEnabled), 0);
   }
add_projectionEnabled()
void add_projectionEnabled (bool projectionEnabled) inline
Definition at line 10215 of file ArmnnSchema_generated.h.
References VT_PROJECTIONENABLED.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(UnidirectionalSequenceLstmDescriptor::VT_PROJECTIONENABLED, static_cast<uint8_t>(projectionEnabled), 0);
   }
add_timeMajor()
void add_timeMajor (bool timeMajor) inline
Definition at line 10221 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(UnidirectionalSequenceLstmDescriptor::VT_TIMEMAJOR, static_cast<uint8_t>(timeMajor), 0);
   }
Finish()
flatbuffers::Offset<UnidirectionalSequenceLstmDescriptor> Finish () inline
Definition at line 10229 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<UnidirectionalSequenceLstmDescriptor>(end);
     return o;
   }
operator=()
UnidirectionalSequenceLstmDescriptorBuilder& operator= (const UnidirectionalSequenceLstmDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 10198 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 10199 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h