ArmNN: Float32ToBFloat16 Struct Reference
Float32ToBFloat16 Struct Reference
#include <ConvertConstants.hpp>
Static Public Member Functions
static void Func (std::shared_ptr< ConstTensorHandle > &handle)
Detailed Description
Definition at line 64 of file ConvertConstants.hpp.
Member Function Documentation
Func()
static void Func (std::shared_ptr< ConstTensorHandle > & handle) inline static
Definition at line 66 of file ConvertConstants.hpp.
References armnn::BFloat16, FloatingPointConverter::ConvertFloat32ToBFloat16(), armnn::Float32, TensorInfo::GetDataType(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), and armnn::info.
     {
         const TensorInfo& info = handle->GetTensorInfo();
         if (info.GetDataType() == DataType::Float32)
         {
             std::vector<BFloat16> newValues(info.GetNumElements());
             armnnUtils::FloatingPointConverter::ConvertFloat32ToBFloat16(handle->GetConstTensor<float>(),
                                                                          info.GetNumElements(),
                                                                          newValues.data());
             TensorInfo newInfo(info.GetShape(), DataType::BFloat16, 0.0f, 0, true);
             ConstTensor newInput(newInfo, newValues);
             handle.reset(new ScopedTensorHandle(newInput));
         }
     }
The documentation for this struct was generated from the following file:
src/armnn/optimizations/ConvertConstants.hpp