ArmNN: TransposeConvolution2dLayerBuilder Struct Reference
TransposeConvolution2dLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef TransposeConvolution2dLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::TransposeConvolution2dDescriptor > descriptor)
void add_weights (flatbuffers::Offset< armnnSerializer::ConstTensor > weights)
void add_biases (flatbuffers::Offset< armnnSerializer::ConstTensor > biases)
TransposeConvolution2dLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
TransposeConvolution2dLayerBuilder & operator= (const TransposeConvolution2dLayerBuilder &)
flatbuffers::Offset< TransposeConvolution2dLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9331 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef TransposeConvolution2dLayer Table
Definition at line 9332 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
TransposeConvolution2dLayerBuilder()
TransposeConvolution2dLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9347 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 9335 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateTransposeConvolution2dLayer().
{
     fbb_.AddOffset(TransposeConvolution2dLayer::VT_BASE, base);
   }
add_biases()
void add_biases (flatbuffers::Offset< armnnSerializer::ConstTensor > biases) inline
Definition at line 9344 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateTransposeConvolution2dLayer().
{
     fbb_.AddOffset(TransposeConvolution2dLayer::VT_BIASES, biases);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::TransposeConvolution2dDescriptor > descriptor) inline
Definition at line 9338 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateTransposeConvolution2dLayer().
{
     fbb_.AddOffset(TransposeConvolution2dLayer::VT_DESCRIPTOR, descriptor);
   }
add_weights()
void add_weights (flatbuffers::Offset< armnnSerializer::ConstTensor > weights) inline
Definition at line 9341 of file ArmnnSchema_generated.h.
References VT_WEIGHTS.
Referenced by armnnSerializer::CreateTransposeConvolution2dLayer().
{
     fbb_.AddOffset(TransposeConvolution2dLayer::VT_WEIGHTS, weights);
   }
Finish()
flatbuffers::Offset<TransposeConvolution2dLayer> Finish () inline
Definition at line 9352 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateTransposeConvolution2dLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<TransposeConvolution2dLayer>(end);
     return o;
   }
operator=()
TransposeConvolution2dLayerBuilder& operator= (const TransposeConvolution2dLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9333 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9334 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h