ArmNN: BaseDescriptor Struct Reference
BaseDescriptor Struct Reference
Base class for all descriptors.
#include <Descriptors.hpp>
Public Member Functions
virtual bool IsNull () const
virtual ~BaseDescriptor ()=default
Detailed Description
Base class for all descriptors.
Definition at line 22 of file Descriptors.hpp.
Constructor & Destructor Documentation
~BaseDescriptor()
virtual ~BaseDescriptor () virtual default
Referenced by BaseDescriptor::IsNull().
Member Function Documentation
IsNull()
virtual bool IsNull () const inline virtual
Reimplemented in NullDescriptor.
Definition at line 24 of file Descriptors.hpp.
References BaseDescriptor::~BaseDescriptor().
Referenced by TEST_SUITE().
 { return false; }
The documentation for this struct was generated from the following file:
include/armnn/Descriptors.hpp