ArmNN: LogSoftmaxLayerBuilder Struct Reference
LogSoftmaxLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef LogSoftmaxLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::LogSoftmaxDescriptor > descriptor)
LogSoftmaxLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
LogSoftmaxLayerBuilder & operator= (const LogSoftmaxLayerBuilder &)
flatbuffers::Offset< LogSoftmaxLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 4424 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef LogSoftmaxLayer Table
Definition at line 4425 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
LogSoftmaxLayerBuilder()
LogSoftmaxLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 4434 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 4428 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateLogSoftmaxLayer().
{
     fbb_.AddOffset(LogSoftmaxLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::LogSoftmaxDescriptor > descriptor) inline
Definition at line 4431 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateLogSoftmaxLayer().
{
     fbb_.AddOffset(LogSoftmaxLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<LogSoftmaxLayer> Finish () inline
Definition at line 4439 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLogSoftmaxLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<LogSoftmaxLayer>(end);
     return o;
   }
operator=()
LogSoftmaxLayerBuilder& operator= (const LogSoftmaxLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 4426 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 4427 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h