ArmNN: ResizeDescriptorBuilder Struct Reference
ResizeDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ResizeDescriptor Table
Public Member Functions
void add_targetHeight (uint32_t targetHeight)
void add_targetWidth (uint32_t targetWidth)
void add_method (armnnSerializer::ResizeMethod method)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
void add_alignCorners (bool alignCorners)
void add_halfPixelCenters (bool halfPixelCenters)
ResizeDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ResizeDescriptorBuilder & operator= (const ResizeDescriptorBuilder &)
flatbuffers::Offset< ResizeDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9685 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ResizeDescriptor Table
Definition at line 9686 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ResizeDescriptorBuilder()
ResizeDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9707 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_alignCorners()
void add_alignCorners (bool alignCorners) inline
Definition at line 9701 of file ArmnnSchema_generated.h.
References VT_ALIGNCORNERS.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     fbb_.AddElement<uint8_t>(ResizeDescriptor::VT_ALIGNCORNERS, static_cast<uint8_t>(alignCorners), 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 9698 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     fbb_.AddElement<int8_t>(ResizeDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_halfPixelCenters()
void add_halfPixelCenters (bool halfPixelCenters) inline
Definition at line 9704 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     fbb_.AddElement<uint8_t>(ResizeDescriptor::VT_HALFPIXELCENTERS, static_cast<uint8_t>(halfPixelCenters), 0);
   }
add_method()
void add_method (armnnSerializer::ResizeMethod method) inline
Definition at line 9695 of file ArmnnSchema_generated.h.
References VT_METHOD.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     fbb_.AddElement<int8_t>(ResizeDescriptor::VT_METHOD, static_cast<int8_t>(method), 0);
   }
add_targetHeight()
void add_targetHeight (uint32_t targetHeight) inline
Definition at line 9689 of file ArmnnSchema_generated.h.
References VT_TARGETHEIGHT.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     fbb_.AddElement<uint32_t>(ResizeDescriptor::VT_TARGETHEIGHT, targetHeight, 0);
   }
add_targetWidth()
void add_targetWidth (uint32_t targetWidth) inline
Definition at line 9692 of file ArmnnSchema_generated.h.
References VT_TARGETWIDTH.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     fbb_.AddElement<uint32_t>(ResizeDescriptor::VT_TARGETWIDTH, targetWidth, 0);
   }
Finish()
flatbuffers::Offset<ResizeDescriptor> Finish () inline
Definition at line 9712 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateResizeDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ResizeDescriptor>(end);
     return o;
   }
operator=()
ResizeDescriptorBuilder& operator= (const ResizeDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9687 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9688 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h