ArmNN: ParserPrototxtFixture< TParser > Struct Template Reference
ParserPrototxtFixture< TParser > Struct Template Reference
#include <ParserPrototxtFixture.hpp>
Public Member Functions
ParserPrototxtFixture ()
template<std::size_t NumOutputDimensions>
void RunTest (const std::vector< float > &inputData, const std::vector< float > &expectedOutputData)
Executes the network with the given input tensor and checks the result against the given output tensor.
template<std::size_t NumOutputDimensions>
void RunComparisonTest (const std::map< std::string, std::vector< float >> &inputData, const std::map< std::string, std::vector< uint8_t >> &expectedOutputData)
Executes the network with the given input tensor and checks the result against the given output tensor.
template<std::size_t NumOutputDimensions, typename T = float>
void RunTest (const std::map< std::string, std::vector< float >> &inputData, const std::map< std::string, std::vector< T >> &expectedOutputData)
Executes the network with the given input tensors and checks the results against the given output tensors.
void SetupSingleInputSingleOutput (const std::string &inputName, const std::string &outputName)
Parses and loads the network defined by the m_Prototext string.
void SetupSingleInputSingleOutput (const armnn::TensorShape &inputTensorShape, const std::string &inputName, const std::string &outputName)
void SetupSingleInputSingleOutput (const armnn::TensorShape &inputTensorShape, const armnn::TensorShape &outputTensorShape, const std::string &inputName, const std::string &outputName)
void Setup (const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
void Setup (const std::map< std::string, armnn::TensorShape > &inputShapes)
void Setup ()
armnn::IOptimizedNetworkPtr SetupOptimizedNetwork (const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Public Attributes
std::string m_Prototext
std::unique_ptr< TParser, void(*)(TParser *parser)> m_Parser
armnn::IRuntimePtr m_Runtime
armnn::NetworkId m_NetworkIdentifier
armnn::TensorShape m_SingleOutputShape
This will store the output shape so it don't need to be passed to the single-input-single-output overload of RunTest().
std::string m_SingleInputName
If the single-input-single-output overload of Setup() is called, these will store the input and output name so they don't need to be passed to the single-input-single-output overload of RunTest().
std::string m_SingleOutputName
Detailed Description
template<typename TParser>
struct armnnUtils::ParserPrototxtFixture< TParser >
Definition at line 24 of file ParserPrototxtFixture.hpp.
Constructor & Destructor Documentation
ParserPrototxtFixture()
ParserPrototxtFixture () inline
Definition at line 26 of file ParserPrototxtFixture.hpp.
References ParserPrototxtFixture< TParser >::RunComparisonTest(), ParserPrototxtFixture< TParser >::RunTest(), ParserPrototxtFixture< TParser >::Setup(), ParserPrototxtFixture< TParser >::SetupOptimizedNetwork(), and ParserPrototxtFixture< TParser >::SetupSingleInputSingleOutput().
         : m_Parser(TParser::Create())
         , m_Runtime(armnn::IRuntime::Create(armnn::IRuntime::CreationOptions()))
         , m_NetworkIdentifier(-1)
     {
     }
Member Function Documentation
RunComparisonTest()
void RunComparisonTest (const std::map< std::string, std::vector< float >> & inputData, const std::map< std::string, std::vector< uint8_t >> & expectedOutputData)
Executes the network with the given input tensor and checks the result against the given output tensor.
Calls RunTest with output type of uint8_t for checking comparison operators.
Definition at line 194 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::ParserPrototxtFixture().
 {
     RunTest<NumOutputDimensions, uint8_t>(inputData, expectedOutputData);
 }
RunTest() [1/2]
void RunTest (const std::vector< float > & inputData, const std::vector< float > & expectedOutputData)
Executes the network with the given input tensor and checks the result against the given output tensor.
This overload assumes that the network has a single input and a single output.
Definition at line 186 of file ParserPrototxtFixture.hpp.
References ParserPrototxtFixture< TParser >::m_SingleInputName, and ParserPrototxtFixture< TParser >::m_SingleOutputName.
Referenced by ParserPrototxtFixture< TParser >::ParserPrototxtFixture().
 {
     RunTest<NumOutputDimensions>({ { m_SingleInputName, inputData } }, { { m_SingleOutputName, expectedOutputData } });
 }
RunTest() [2/2]
void RunTest (const std::map< std::string, std::vector< float >> & inputData, const std::map< std::string, std::vector< T >> & expectedOutputData)
Executes the network with the given input tensors and checks the results against the given output tensors.
This overload supports multiple inputs and multiple outputs, identified by name.
Definition at line 203 of file ParserPrototxtFixture.hpp.
References CHECK_LOCATION, CompareTensors(), TensorShape::GetNumDimensions(), ParserPrototxtFixture< TParser >::m_NetworkIdentifier, ParserPrototxtFixture< TParser >::m_Parser, ParserPrototxtFixture< TParser >::m_Runtime, and ParserPrototxtFixture< TParser >::m_SingleOutputShape.
 {
     // Sets up the armnn input tensors from the given vectors.
     armnn::InputTensors inputTensors;
     for (auto&& it : inputData)
     {
         armnn::BindingPointInfo bindingInfo = m_Parser->GetNetworkInputBindingInfo(it.first);
         bindingInfo.second.SetConstant(true);
         inputTensors.push_back({ bindingInfo.first, armnn::ConstTensor(bindingInfo.second, it.second.data()) });
         if (bindingInfo.second.GetNumElements() != it.second.size())
         {
             throw armnn::Exception(fmt::format("Input tensor {0} is expected to have {1} elements. "
                                                "{2} elements supplied. {3}",
                                                it.first,
                                                bindingInfo.second.GetNumElements(),
                                                it.second.size(),
                                                CHECK_LOCATION().AsString()));
         }
     }
     // Allocates storage for the output tensors to be written to and sets up the armnn output tensors.
     std::map<std::string, std::vector<T>> outputStorage;
     armnn::OutputTensors outputTensors;
     for (auto&& it : expectedOutputData)
     {
         armnn::BindingPointInfo bindingInfo = m_Parser->GetNetworkOutputBindingInfo(it.first);
         outputStorage.emplace(it.first, std::vector<T>(bindingInfo.second.GetNumElements()));
         outputTensors.push_back(
             { bindingInfo.first, armnn::Tensor(bindingInfo.second, outputStorage.at(it.first).data()) });
     }
     m_Runtime->EnqueueWorkload(m_NetworkIdentifier, inputTensors, outputTensors);
     // Compares each output tensor to the expected values.
     for (auto&& it : expectedOutputData)
     {
         armnn::BindingPointInfo bindingInfo = m_Parser->GetNetworkOutputBindingInfo(it.first);
         if (bindingInfo.second.GetNumElements() != it.second.size())
         {
             throw armnn::Exception(fmt::format("Output tensor {0} is expected to have {1} elements. "
                                                "{2} elements supplied. {3}",
                                                it.first,
                                                bindingInfo.second.GetNumElements(),
                                                it.second.size(),
                                                CHECK_LOCATION().AsString()));
         }
         // If the expected output shape is set, the output tensor checks will be carried out.
         if (m_SingleOutputShape.GetNumDimensions() != 0)
         {
             if (bindingInfo.second.GetShape().GetNumDimensions() == NumOutputDimensions &&
                 bindingInfo.second.GetShape().GetNumDimensions() == m_SingleOutputShape.GetNumDimensions())
             {
                 for (unsigned int i = 0; i < m_SingleOutputShape.GetNumDimensions(); ++i)
                 {
                     if (m_SingleOutputShape[i] != bindingInfo.second.GetShape()[i])
                     {
                         // This exception message could not be created by fmt:format because of an oddity in
                         // the operator << of TensorShape.
                         std::stringstream message;
                         message << "Output tensor " << it.first << " is expected to have "
                                 << bindingInfo.second.GetShape() << "shape. "
                                 << m_SingleOutputShape << " shape supplied. "
                                 << CHECK_LOCATION().AsString();
                         throw armnn::Exception(message.str());
                     }
                 }
             }
             else
             {
                 throw armnn::Exception(fmt::format("Output tensor {0} is expected to have {1} dimensions. "
                                                    "{2} dimensions supplied. {3}",
                                                    it.first,
                                                    bindingInfo.second.GetShape().GetNumDimensions(),
                                                    NumOutputDimensions,
                                                    CHECK_LOCATION().AsString()));
             }
         }
         auto outputExpected = it.second;
         auto shape = bindingInfo.second.GetShape();
         if (std::is_same<T, uint8_t>::value)
         {
             auto result = CompareTensors(outputExpected, outputStorage[it.first], shape, shape, true);
             CHECK_MESSAGE(result.m_Result, result.m_Message.str());
         }
         else
         {
             auto result = CompareTensors(outputExpected, outputStorage[it.first], shape, shape);
             CHECK_MESSAGE(result.m_Result, result.m_Message.str());
         }
     }
 }
Setup() [1/3]
void Setup (const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Definition at line 122 of file ParserPrototxtFixture.hpp.
References CHECK_LOCATION, armnn::CpuRef, ParserPrototxtFixture< TParser >::m_NetworkIdentifier, ParserPrototxtFixture< TParser >::m_Parser, ParserPrototxtFixture< TParser >::m_Prototext, ParserPrototxtFixture< TParser >::m_Runtime, armnn::Optimize(), and armnn::Success.
 {
     std::string errorMessage;
     armnn::INetworkPtr network =
         m_Parser->CreateNetworkFromString(m_Prototext.c_str(), inputShapes, requestedOutputs);
     auto optimized = Optimize(*network, { armnn::Compute::CpuRef }, m_Runtime->GetDeviceSpec());
     armnn::Status ret = m_Runtime->LoadNetwork(m_NetworkIdentifier, move(optimized), errorMessage);
     if (ret != armnn::Status::Success)
     {
         throw armnn::Exception(fmt::format("LoadNetwork failed with error: '{0}' {1}",
                                            errorMessage,
                                            CHECK_LOCATION().AsString()));
     }
 }
Setup() [2/3]
void Setup (const std::map< std::string, armnn::TensorShape > & inputShapes)
Definition at line 140 of file ParserPrototxtFixture.hpp.
References CHECK_LOCATION, armnn::CpuRef, ParserPrototxtFixture< TParser >::m_NetworkIdentifier, ParserPrototxtFixture< TParser >::m_Parser, ParserPrototxtFixture< TParser >::m_Prototext, ParserPrototxtFixture< TParser >::m_Runtime, armnn::Optimize(), and armnn::Success.
 {
     std::string errorMessage;
     armnn::INetworkPtr network =
         m_Parser->CreateNetworkFromString(m_Prototext.c_str(), inputShapes);
     auto optimized = Optimize(*network, { armnn::Compute::CpuRef }, m_Runtime->GetDeviceSpec());
     armnn::Status ret = m_Runtime->LoadNetwork(m_NetworkIdentifier, move(optimized), errorMessage);
     if (ret != armnn::Status::Success)
     {
         throw armnn::Exception(fmt::format("LoadNetwork failed with error: '{0}' {1}",
                                            errorMessage,
                                            CHECK_LOCATION().AsString()));
     }
 }
Setup() [3/3]
void Setup ()
Definition at line 157 of file ParserPrototxtFixture.hpp.
References CHECK_LOCATION, armnn::CpuRef, ParserPrototxtFixture< TParser >::m_NetworkIdentifier, ParserPrototxtFixture< TParser >::m_Parser, ParserPrototxtFixture< TParser >::m_Prototext, ParserPrototxtFixture< TParser >::m_Runtime, armnn::Optimize(), and armnn::Success.
Referenced by ParserPrototxtFixture< TParser >::ParserPrototxtFixture(), ParserPrototxtFixture< TParser >::SetupSingleInputSingleOutput(), and TEST_SUITE().
 {
     std::string errorMessage;
     armnn::INetworkPtr network =
         m_Parser->CreateNetworkFromString(m_Prototext.c_str());
     auto optimized = Optimize(*network, { armnn::Compute::CpuRef }, m_Runtime->GetDeviceSpec());
     armnn::Status ret = m_Runtime->LoadNetwork(m_NetworkIdentifier, move(optimized), errorMessage);
     if (ret != armnn::Status::Success)
     {
         throw armnn::Exception(fmt::format("LoadNetwork failed with error: '{0}' {1}",
                                            errorMessage,
                                            CHECK_LOCATION().AsString()));
     }
 }
SetupOptimizedNetwork()
armnn::IOptimizedNetworkPtr SetupOptimizedNetwork (const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Definition at line 174 of file ParserPrototxtFixture.hpp.
References armnn::CpuRef, ParserPrototxtFixture< TParser >::m_Parser, ParserPrototxtFixture< TParser >::m_Prototext, ParserPrototxtFixture< TParser >::m_Runtime, and armnn::Optimize().
Referenced by ParserPrototxtFixture< TParser >::ParserPrototxtFixture().
 {
     armnn::INetworkPtr network =
         m_Parser->CreateNetworkFromString(m_Prototext.c_str(), inputShapes, requestedOutputs);
     auto optimized = Optimize(*network, { armnn::Compute::CpuRef }, m_Runtime->GetDeviceSpec());
     return optimized;
 }
SetupSingleInputSingleOutput() [1/3]
void SetupSingleInputSingleOutput (const std::string & inputName, const std::string & outputName)
Parses and loads the network defined by the m_Prototext string.
Definition at line 87 of file ParserPrototxtFixture.hpp.
References ParserPrototxtFixture< TParser >::m_SingleInputName, ParserPrototxtFixture< TParser >::m_SingleOutputName, and ParserPrototxtFixture< TParser >::Setup().
Referenced by ParserPrototxtFixture< TParser >::ParserPrototxtFixture().
 {
     // Stores the input and output name so they don't need to be passed to the single-input-single-output RunTest().
     m_SingleInputName = inputName;
     m_SingleOutputName = outputName;
     Setup({ }, { outputName });
 }
SetupSingleInputSingleOutput() [2/3]
void SetupSingleInputSingleOutput (const armnn::TensorShape & inputTensorShape, const std::string & inputName, const std::string & outputName)
Definition at line 97 of file ParserPrototxtFixture.hpp.
References ParserPrototxtFixture< TParser >::m_SingleInputName, ParserPrototxtFixture< TParser >::m_SingleOutputName, and ParserPrototxtFixture< TParser >::Setup().
 {
     // Stores the input and output name so they don't need to be passed to the single-input-single-output RunTest().
     m_SingleInputName = inputName;
     m_SingleOutputName = outputName;
     Setup({ { inputName, inputTensorShape } }, { outputName });
 }
SetupSingleInputSingleOutput() [3/3]
void SetupSingleInputSingleOutput (const armnn::TensorShape & inputTensorShape, const armnn::TensorShape & outputTensorShape, const std::string & inputName, const std::string & outputName)
Definition at line 108 of file ParserPrototxtFixture.hpp.
References ParserPrototxtFixture< TParser >::m_SingleInputName, ParserPrototxtFixture< TParser >::m_SingleOutputName, ParserPrototxtFixture< TParser >::m_SingleOutputShape, and ParserPrototxtFixture< TParser >::Setup().
 {
     // Stores the input name, the output name and the output tensor shape
     // so they don't need to be passed to the single-input-single-output RunTest().
     m_SingleInputName = inputName;
     m_SingleOutputName = outputName;
     m_SingleOutputShape = outputTensorShape;
     Setup({ { inputName, inputTensorShape } }, { outputName });
 }
Member Data Documentation
m_NetworkIdentifier
armnn::NetworkId m_NetworkIdentifier
Definition at line 72 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::RunTest(), and ParserPrototxtFixture< TParser >::Setup().
m_Parser
std::unique_ptr<TParser, void(*)(TParser* parser)> m_Parser
Definition at line 70 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::RunTest(), ParserPrototxtFixture< TParser >::Setup(), and ParserPrototxtFixture< TParser >::SetupOptimizedNetwork().
m_Prototext
std::string m_Prototext
Definition at line 69 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::Setup(), and ParserPrototxtFixture< TParser >::SetupOptimizedNetwork().
m_Runtime
armnn::IRuntimePtr m_Runtime
Definition at line 71 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::RunTest(), ParserPrototxtFixture< TParser >::Setup(), and ParserPrototxtFixture< TParser >::SetupOptimizedNetwork().
m_SingleInputName
std::string m_SingleInputName
If the single-input-single-output overload of Setup() is called, these will store the input and output name so they don't need to be passed to the single-input-single-output overload of RunTest().
Definition at line 77 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::RunTest(), and ParserPrototxtFixture< TParser >::SetupSingleInputSingleOutput().
m_SingleOutputName
std::string m_SingleOutputName
Definition at line 78 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::RunTest(), and ParserPrototxtFixture< TParser >::SetupSingleInputSingleOutput().
m_SingleOutputShape
armnn::TensorShape m_SingleOutputShape
This will store the output shape so it don't need to be passed to the single-input-single-output overload of RunTest().
Definition at line 83 of file ParserPrototxtFixture.hpp.
Referenced by ParserPrototxtFixture< TParser >::RunTest(), and ParserPrototxtFixture< TParser >::SetupSingleInputSingleOutput().
The documentation for this struct was generated from the following file:
src/armnnUtils/ParserPrototxtFixture.hpp