ArmNN: ViewsDescriptorBuilder Struct Reference
ViewsDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ViewsDescriptor Table
Public Member Functions
void add_origins (flatbuffers::Offset< armnnSerializer::OriginsDescriptor > origins)
void add_viewSizes (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewSizes)
ViewsDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ViewsDescriptorBuilder & operator= (const ViewsDescriptorBuilder &)
flatbuffers::Offset< ViewsDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7693 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ViewsDescriptor Table
Definition at line 7694 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ViewsDescriptorBuilder()
ViewsDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7703 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_origins()
void add_origins (flatbuffers::Offset< armnnSerializer::OriginsDescriptor > origins) inline
Definition at line 7697 of file ArmnnSchema_generated.h.
References VT_ORIGINS.
Referenced by armnnSerializer::CreateViewsDescriptor().
{
     fbb_.AddOffset(ViewsDescriptor::VT_ORIGINS, origins);
   }
add_viewSizes()
void add_viewSizes (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewSizes) inline
Definition at line 7700 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateViewsDescriptor().
{
     fbb_.AddOffset(ViewsDescriptor::VT_VIEWSIZES, viewSizes);
   }
Finish()
flatbuffers::Offset<ViewsDescriptor> Finish () inline
Definition at line 7708 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateViewsDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ViewsDescriptor>(end);
     return o;
   }
operator=()
ViewsDescriptorBuilder& operator= (const ViewsDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7695 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7696 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h