ArmNN: SplitterLayerBuilder Struct Reference
SplitterLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SplitterLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::ViewsDescriptor > descriptor)
SplitterLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SplitterLayerBuilder & operator= (const SplitterLayerBuilder &)
flatbuffers::Offset< SplitterLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7758 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SplitterLayer Table
Definition at line 7759 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SplitterLayerBuilder()
SplitterLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7768 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 7762 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateSplitterLayer().
{
     fbb_.AddOffset(SplitterLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::ViewsDescriptor > descriptor) inline
Definition at line 7765 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateSplitterLayer().
{
     fbb_.AddOffset(SplitterLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<SplitterLayer> Finish () inline
Definition at line 7773 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSplitterLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SplitterLayer>(end);
     return o;
   }
operator=()
SplitterLayerBuilder& operator= (const SplitterLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7760 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7761 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h