ArmNN: BatchToSpaceNdLayerBuilder Struct Reference
BatchToSpaceNdLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef BatchToSpaceNdLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::BatchToSpaceNdDescriptor > descriptor)
BatchToSpaceNdLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
BatchToSpaceNdLayerBuilder & operator= (const BatchToSpaceNdLayerBuilder &)
flatbuffers::Offset< BatchToSpaceNdLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6249 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef BatchToSpaceNdLayer Table
Definition at line 6250 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
BatchToSpaceNdLayerBuilder()
BatchToSpaceNdLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6259 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 6253 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateBatchToSpaceNdLayer().
{
     fbb_.AddOffset(BatchToSpaceNdLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::BatchToSpaceNdDescriptor > descriptor) inline
Definition at line 6256 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateBatchToSpaceNdLayer().
{
     fbb_.AddOffset(BatchToSpaceNdLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<BatchToSpaceNdLayer> Finish () inline
Definition at line 6264 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateBatchToSpaceNdLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<BatchToSpaceNdLayer>(end);
     return o;
   }
operator=()
BatchToSpaceNdLayerBuilder& operator= (const BatchToSpaceNdLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6251 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6252 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h