Arm NN: src/dynamic/sample/SampleDynamicBackend.hpp File Reference
SampleDynamicBackend.hpp File Reference
#include <cstdint>
Functions
const char * GetBackendId ()
void GetVersion (uint32_t *outMajor, uint32_t *outMinor)
void * BackendFactory ()
Function Documentation
BackendFactory()
void* BackendFactory ()
Definition at line 30 of file RefDynamicBackend.cpp.
 {
     return new RefBackend();
 }
GetBackendId()
const char* GetBackendId ()
Definition at line 12 of file RefDynamicBackend.cpp.
 {
     return RefBackend::GetIdStatic().Get().c_str();
 }
References BackendId::Get(), and RefBackend::GetIdStatic().
GetVersion()
void GetVersion (uint32_t * outMajor, uint32_t * outMinor)
Definition at line 17 of file RefDynamicBackend.cpp.
 {
     if (!outMajor || !outMinor)
     {
         return;
     }
     BackendVersion apiVersion = IBackendInternal::GetApiVersion();
     *outMajor = apiVersion.m_Major;
     *outMinor = apiVersion.m_Minor;
 }
References IBackendInternal::GetApiVersion(), BackendVersion::m_Major, and BackendVersion::m_Minor.