Arm NN: ConstTensorPin Class Reference
ConstTensorPin Class Reference
#include <ConversionUtils.hpp>
Public Member Functions
ConstTensorPin (bool optional=false)
ConstTensorPin (armnn::TensorInfo &tensorInfo, const void *valueStart, uint32_t numBytes, const armnn::PermutationVector &mappings)
ConstTensorPin (const ConstTensorPin &other)=delete
ConstTensorPin (ConstTensorPin &&other)=default
bool IsValid () const
bool IsOptional () const
const armnn::ConstTensor & GetConstTensor () const
const armnn::ConstTensor * GetConstTensorPtr () const
Detailed Description
Definition at line 92 of file ConversionUtils.hpp.
Constructor & Destructor Documentation
ConstTensorPin() [1/4]
ConstTensorPin (bool optional = false)
Definition at line 82 of file ConversionUtils.cpp.
     : m_Optional(optional)
 {}
ConstTensorPin() [2/4]
ConstTensorPin (armnn::TensorInfo & tensorInfo, const void * valueStart, uint32_t numBytes, const armnn::PermutationVector & mappings)
Definition at line 86 of file ConversionUtils.cpp.
     : m_Optional(false)
 {
     armnn::IgnoreUnused(numBytes);
     if (tensorInfo.GetNumBytes() != numBytes)
     {
         VLOG(DRIVER) << "The size of ConstTensor does not match its TensorInfo.";
     }
     const bool needsSwizzling = (mappings.GetSize() > 0);
     if (needsSwizzling)
     {
         m_SwizzledTensorData.resize(tensorInfo.GetNumBytes());
         SwizzleAndroidNn4dTensorToArmNn(tensorInfo, valueStart, m_SwizzledTensorData.data(), mappings);
         m_ConstTensor = armnn::ConstTensor(tensorInfo, m_SwizzledTensorData.data());
     }
     else
     {
         m_ConstTensor = armnn::ConstTensor(tensorInfo, valueStart);
     }
 }
References TensorInfo::GetNumBytes(), PermutationVector::GetSize(), armnn::IgnoreUnused(), and armnn_driver::SwizzleAndroidNn4dTensorToArmNn().
ConstTensorPin() [3/4]
ConstTensorPin (const ConstTensorPin & other) delete
ConstTensorPin() [4/4]
ConstTensorPin (ConstTensorPin && other) default
Member Function Documentation
GetConstTensor()
const armnn::ConstTensor & GetConstTensor () const
Definition at line 122 of file ConversionUtils.cpp.
 {
     return m_ConstTensor;
 }
Referenced by armnn_driver::ConvertToLayerInputHandle().
GetConstTensorPtr()
const armnn::ConstTensor * GetConstTensorPtr () const
Definition at line 127 of file ConversionUtils.cpp.
 {
     if (IsValid() && m_ConstTensor.GetNumElements() > 0)
     {
         return &m_ConstTensor;
     }
     // tensor is either invalid, or has no elements (indicating an optional tensor that was not provided)
     return nullptr;
 }
References BaseTensor< MemoryType >::GetNumElements(), and ConstTensorPin::IsValid().
IsOptional()
bool IsOptional () const
Definition at line 117 of file ConversionUtils.cpp.
 {
     return m_Optional;
 }
IsValid()
bool IsValid () const
Definition at line 112 of file ConversionUtils.cpp.
 {
     return m_ConstTensor.GetMemoryArea() != nullptr;
 }
References BaseTensor< MemoryType >::GetMemoryArea().
Referenced by armnn_driver::ConvertToLayerInputHandle(), and ConstTensorPin::GetConstTensorPtr().
The documentation for this class was generated from the following files:
shim/sl/canonical/ConversionUtils.hpp
shim/sl/canonical/ConversionUtils.cpp