Arm NN: TransposeAsReshapeImpl Class Reference
TransposeAsReshapeImpl Class Reference
#include <TransposeAsReshape.hpp>
Public Member Functions
void Run (Graph &graph, TransposeLayer &transpose) const
Run for every TransposeLayer. Replaces it with a ReshapeLayer if they are equivalent.
Protected Member Functions
TransposeAsReshapeImpl ()=default
~TransposeAsReshapeImpl ()=default
Detailed Description
Definition at line 14 of file TransposeAsReshape.hpp.
Constructor & Destructor Documentation
TransposeAsReshapeImpl()
TransposeAsReshapeImpl () protected default
~TransposeAsReshapeImpl()
~TransposeAsReshapeImpl () protected default
Member Function Documentation
Run()
void Run (Graph & graph, TransposeLayer & transpose) const inline
Run for every TransposeLayer. Replaces it with a ReshapeLayer if they are equivalent.
Definition at line 18 of file TransposeAsReshape.hpp.
     {
         if (IsReshape(transpose))
         {
             const TensorInfo& outInfo = transpose.GetOutputHandler().GetTensorInfo();
             const std::string name = std::string("as_reshape-") + transpose.GetName();
             const ReshapeDescriptor descriptor{outInfo.GetShape()};
             // Inserts NewLayer so layers don't need to be re-sorted.
             auto reshape = graph.InsertNewLayer<ReshapeLayer>(transpose.GetInputSlot(0), descriptor, name.c_str());
             // Bypass transpose. It will be deleted since it's left unconnected.
             transpose.GetOutputSlot().MoveAllConnections(reshape->GetOutputSlot());
         }
     }
References Layer::GetInputSlot(), Layer::GetName(), Layer::GetOutputHandler(), Layer::GetOutputSlot(), TensorInfo::GetShape(), OutputHandler::GetTensorInfo(), Graph::InsertNewLayer(), and OutputSlot::MoveAllConnections().
The documentation for this class was generated from the following file:
src/armnn/optimizations/TransposeAsReshape.hpp