Arm NN: TransposeConvolution2dLayer Class Reference
TransposeConvolution2dLayer Class Reference
This layer represents a 2D transpose convolution operation.
#include <TransposeConvolution2dLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the TransposeConvolution2d type.
TransposeConvolution2dLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of TransposeConvolution2dLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
Infers the output shapes from given input shapes and layer properties.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Public Member Functions inherited from LayerWithParameters< TransposeConvolution2dDescriptor >
const TransposeConvolution2dDescriptor & GetParameters () const override
If the layer has a descriptor return it.
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id) override
Set the backend of the IConnectableLayer.
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer * >::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T >
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
virtual const BaseDescriptor & GetParameters () const override
If the layer has a descriptor return it.
Public Attributes
std::shared_ptr< ConstTensorHandle > m_Weight
A unique pointer to store weight values.
std::shared_ptr< ConstTensorHandle > m_Bias
A unique pointer to store bias values.
Protected Member Functions
TransposeConvolution2dLayer (const TransposeConvolution2dDescriptor &param, const char *name)
Constructor to create a TransposeConvolution2dLayer.
~TransposeConvolution2dLayer ()=default
Default destructor.
ImmutableConstantTensors GetConstantTensorsByRef () const override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from LayerWithParameters< TransposeConvolution2dDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const TransposeConvolution2dDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *Layer::CreateWorkload.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Layer::ImmutableConstantTensors GetConnectedConstantAsInputTensors () const
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *Layer::CreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef () override final
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< TransposeConvolution2dDescriptor >
using DescriptorType = TransposeConvolution2dDescriptor
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector< std::reference_wrapper< std::shared_ptr< ConstTensorHandle > >>
using ImmutableConstantTensors = std::vector< std::reference_wrapper< const std::shared_ptr< ConstTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< TransposeConvolution2dDescriptor >
TransposeConvolution2dDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a 2D transpose convolution operation.
Definition at line 15 of file TransposeConvolution2dLayer.hpp.
Constructor & Destructor Documentation
TransposeConvolution2dLayer()
TransposeConvolution2dLayer (const TransposeConvolution2dDescriptor & param, const char * name) protected
Constructor to create a TransposeConvolution2dLayer.
Parameters
[in] param TransposeConvolution2dDescriptor to configure the 2D transpose convolution operation.
[in] name Optional name for the layer.
Definition at line 19 of file TransposeConvolution2dLayer.cpp.
     : LayerWithParameters(1, 1, LayerType::TransposeConvolution2d, param, name)
 {
 }
References armnn::TransposeConvolution2d.
~TransposeConvolution2dLayer()
~TransposeConvolution2dLayer () protected default
Default destructor.
Member Function Documentation
Clone()
TransposeConvolution2dLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 43 of file TransposeConvolution2dLayer.cpp.
 {
     auto layer = CloneBase<TransposeConvolution2dLayer>(graph, m_Param, GetName());
     layer->m_Weight = m_Weight ? m_Weight : nullptr;
     if (layer->m_Param.m_BiasEnabled)
     {
         layer->m_Bias = m_Bias ? m_Bias : nullptr;
     }
     return std::move(layer);
 }
References Layer::GetName(), TransposeConvolution2dLayer::m_Bias, LayerWithParameters< TransposeConvolution2dDescriptor >::m_Param, and TransposeConvolution2dLayer::m_Weight.
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the TransposeConvolution2d type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 25 of file TransposeConvolution2dLayer.cpp.
 {
     ARMNN_ASSERT_MSG(m_Weight != nullptr, "TransposeConvolution2dLayer: Weights data should not be null.");
     TransposeConvolution2dQueueDescriptor descriptor;
     descriptor.m_Weight = m_Weight.get();
     if (m_Param.m_BiasEnabled)
     {
         ARMNN_ASSERT_MSG(m_Bias != nullptr, "TransposeConvolution2dLayer: Bias data should not be null.");
         descriptor.m_Bias = m_Bias.get();
     }
     SetAdditionalInfo(descriptor);
     return factory.CreateWorkload(LayerType::TransposeConvolution2d, descriptor, PrepInfoAndDesc(descriptor));
 }
References ARMNN_ASSERT_MSG, IWorkloadFactory::CreateWorkload(), TransposeConvolution2dLayer::m_Bias, TransposeConvolution2dQueueDescriptor::m_Bias, TransposeConvolution2dDescriptor::m_BiasEnabled, LayerWithParameters< TransposeConvolution2dDescriptor >::m_Param, TransposeConvolution2dLayer::m_Weight, TransposeConvolution2dQueueDescriptor::m_Weight, LayerWithParameters< TransposeConvolution2dDescriptor >::PrepInfoAndDesc(), Layer::SetAdditionalInfo(), and armnn::TransposeConvolution2d.
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Reimplemented from Layer.
Definition at line 130 of file TransposeConvolution2dLayer.cpp.
 {
     ManagedConstTensorHandle managedWeight(m_Weight);
     std::vector<armnn::ConstTensor> constTensors { { managedWeight.GetTensorInfo(), managedWeight.Map() } };
     ManagedConstTensorHandle managedBias(m_Bias);
     if (GetParameters().m_BiasEnabled)
     {
         constTensors.emplace_back(ConstTensor(managedBias.GetTensorInfo(), managedBias.Map()));
     }
     strategy.ExecuteStrategy(this, GetParameters(), constTensors, GetName());
 }
References IStrategy::ExecuteStrategy(), Layer::GetName(), LayerWithParameters< TransposeConvolution2dDescriptor >::GetParameters(), ManagedConstTensorHandle::GetTensorInfo(), TransposeConvolution2dLayer::m_Bias, TransposeConvolution2dLayer::m_Weight, and ManagedConstTensorHandle::Map().
GetConstantTensorsByRef()
Layer::ImmutableConstantTensors GetConstantTensorsByRef () const override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 124 of file TransposeConvolution2dLayer.cpp.
 {
     // For API stability DO NOT ALTER order and add new members to the end of vector
     return {m_Weight, m_Bias};
 }
References TransposeConvolution2dLayer::m_Bias, and TransposeConvolution2dLayer::m_Weight.
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
Infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes the layer has.
Returns
A vector of the inferred output shape.
Reimplemented from Layer.
Definition at line 57 of file TransposeConvolution2dLayer.cpp.
 {
     ARMNN_ASSERT(inputShapes.size() == 2);
     const TensorShape& inputShape  = inputShapes[0];
     const TensorShape& kernelShape = inputShapes[1];
     ARMNN_ASSERT_MSG(inputShape.GetNumDimensions() == 4, "Transpose convolutions will always have 4D input");
     DataLayoutIndexed dataLayoutIndex(m_Param.m_DataLayout);
     const unsigned int batches = inputShape[0];
     const unsigned int wInput = inputShape[dataLayoutIndex.GetWidthIndex()];
     const unsigned int hInput = inputShape[dataLayoutIndex.GetHeightIndex()];
     const unsigned int wKernel = kernelShape[dataLayoutIndex.GetWidthIndex()];
     const unsigned int hKernel = kernelShape[dataLayoutIndex.GetHeightIndex()];
     unsigned int wPadding = m_Param.m_PadLeft + m_Param.m_PadRight;
     unsigned int hPadding = m_Param.m_PadTop + m_Param.m_PadBottom;
     unsigned int wOutput = (wInput - 1) * m_Param.m_StrideX + wKernel - wPadding;
     unsigned int hOutput = (hInput - 1) * m_Param.m_StrideY + hKernel - hPadding;
     unsigned int cOutput = kernelShape[0];
     TensorShape tensorShape = m_Param.m_DataLayout == armnn::DataLayout::NHWC ?
          TensorShape( { batches, hOutput, wOutput, cOutput } ) :
          TensorShape( { batches, cOutput, hOutput, wOutput });
     return std::vector<TensorShape>({ tensorShape });
 }
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, DataLayoutIndexed::GetHeightIndex(), TensorShape::GetNumDimensions(), DataLayoutIndexed::GetWidthIndex(), TransposeConvolution2dDescriptor::m_DataLayout, TransposeConvolution2dDescriptor::m_PadBottom, TransposeConvolution2dDescriptor::m_PadLeft, TransposeConvolution2dDescriptor::m_PadRight, TransposeConvolution2dDescriptor::m_PadTop, LayerWithParameters< TransposeConvolution2dDescriptor >::m_Param, TransposeConvolution2dDescriptor::m_StrideX, TransposeConvolution2dDescriptor::m_StrideY, and armnn::NHWC.
Referenced by TransposeConvolution2dLayer::ValidateTensorShapesFromInputs().
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of TransposeConvolution2dLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 90 of file TransposeConvolution2dLayer.cpp.
 {
     VerifyLayerConnections(1, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     ARMNN_ASSERT_MSG(m_Weight != nullptr, "TransposeConvolution2dLayer: Weight data cannot be null.");
     std::vector<TensorShape> expectedOutputShape;
     std::vector<TensorShape> outputShapeGivenAsInput;
     expectedOutputShape = InferOutputShapes({GetInputSlot(0).GetTensorInfo().GetShape(),
                                              m_Weight->GetTensorInfo().GetShape() });
     ARMNN_ASSERT(expectedOutputShape.size() == 1);
     // If output_shape was specified then use it rather than calculate an inferred output shape.
     if (m_Param.m_OutputShapeEnabled)
     {
         TensorShape shapeAsTensorShape(static_cast<unsigned int>(m_Param.m_OutputShape.size()),
             m_Param.m_OutputShape.data());
         outputShapeGivenAsInput.push_back(shapeAsTensorShape);
         ARMNN_ASSERT(outputShapeGivenAsInput.size() == 1);
         ARMNN_ASSERT_MSG(expectedOutputShape == outputShapeGivenAsInput,
                          "TransposeConvolution2dLayer: output calculated by InferOutputShapes and "
                          "the output given as an input parameter to the layer are not matching");
     }
     ValidateAndCopyShape(outputShape, expectedOutputShape[0], m_ShapeInferenceMethod, "TransposeConvolution2dLayer");
 }
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_LOCATION, Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), InputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), TransposeConvolution2dLayer::InferOutputShapes(), TransposeConvolution2dDescriptor::m_OutputShape, TransposeConvolution2dDescriptor::m_OutputShapeEnabled, LayerWithParameters< TransposeConvolution2dDescriptor >::m_Param, Layer::m_ShapeInferenceMethod, TransposeConvolution2dLayer::m_Weight, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
Member Data Documentation
m_Bias
std::shared_ptr<ConstTensorHandle> m_Bias
A unique pointer to store bias values.
Definition at line 21 of file TransposeConvolution2dLayer.hpp.
Referenced by TransposeConvolution2dLayer::Clone(), TransposeConvolution2dLayer::CreateWorkload(), TransposeConvolution2dLayer::ExecuteStrategy(), and TransposeConvolution2dLayer::GetConstantTensorsByRef().
m_Weight
std::shared_ptr<ConstTensorHandle> m_Weight
A unique pointer to store weight values.
Definition at line 19 of file TransposeConvolution2dLayer.hpp.
Referenced by NetworkImpl::AddTransposeConvolution2dLayer(), TransposeConvolution2dLayer::Clone(), TransposeConvolution2dLayer::CreateWorkload(), TransposeConvolution2dLayer::ExecuteStrategy(), TransposeConvolution2dLayer::GetConstantTensorsByRef(), and TransposeConvolution2dLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/TransposeConvolution2dLayer.hpp
src/armnn/layers/TransposeConvolution2dLayer.cpp