Arm NN: NeonTensorDecorator Class Reference
NeonTensorDecorator Class Reference
NeonTensorDecorator wraps an existing Neon tensor allowing us to override the TensorInfo for it.
#include <NeonTensorHandle.hpp>
Public Member Functions
NeonTensorDecorator ()
NeonTensorDecorator (arm_compute::ITensor *original, const TensorInfo &info)
~NeonTensorDecorator ()=default
NeonTensorDecorator (const NeonTensorDecorator &)=delete
NeonTensorDecorator & operator= (const NeonTensorDecorator &)=delete
NeonTensorDecorator (NeonTensorDecorator &&)=default
NeonTensorDecorator & operator= (NeonTensorDecorator &&)=default
arm_compute::ITensorInfo * info () const override
arm_compute::ITensorInfo * info () override
uint8_t * buffer () const override
Detailed Description
NeonTensorDecorator wraps an existing Neon tensor allowing us to override the TensorInfo for it.
Definition at line 409 of file NeonTensorHandle.hpp.
Constructor & Destructor Documentation
NeonTensorDecorator() [1/4]
NeonTensorDecorator ()
Definition at line 20 of file NeonTensorHandle.cpp.
         : m_Original(nullptr), m_TensorInfo()
 {
 }
NeonTensorDecorator() [2/4]
NeonTensorDecorator (arm_compute::ITensor * original, const TensorInfo & info)
Definition at line 25 of file NeonTensorHandle.cpp.
         : m_Original(nullptr), m_TensorInfo()
 {
     m_TensorInfo = armcomputetensorutils::BuildArmComputeTensorInfo(tensorInfo);
     m_Original = parent;
 }
~NeonTensorDecorator()
~NeonTensorDecorator () default
NeonTensorDecorator() [3/4]
NeonTensorDecorator (const NeonTensorDecorator &) delete
NeonTensorDecorator() [4/4]
NeonTensorDecorator (NeonTensorDecorator &&) default
Member Function Documentation
buffer()
uint8_t * buffer () const override
Definition at line 42 of file NeonTensorHandle.cpp.
 {
     return m_Original->buffer();
 }
Referenced by NeonTensorHandleDecorator::Map().
info() [1/2]
arm_compute::ITensorInfo * info () const override
Definition at line 32 of file NeonTensorHandle.cpp.
 {
     return &m_TensorInfo;
 }
Referenced by NeonTensorHandleDecorator::GetDataType(), and NeonTensorHandleDecorator::Map().
info() [2/2]
arm_compute::ITensorInfo* info () override
operator=() [1/2]
NeonTensorDecorator& operator= (const NeonTensorDecorator &) delete
operator=() [2/2]
NeonTensorDecorator& operator= (NeonTensorDecorator &&) default
The documentation for this class was generated from the following files:
src/backends/neon/NeonTensorHandle.hpp
src/backends/neon/NeonTensorHandle.cpp