Arm NN: SpaceToBatchNdQueueDescriptor Struct Reference
SpaceToBatchNdQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< SpaceToBatchNdDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Additional Inherited Members
Public Attributes inherited from QueueDescriptorWithParameters< SpaceToBatchNdDescriptor >
SpaceToBatchNdDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions inherited from QueueDescriptorWithParameters< SpaceToBatchNdDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 385 of file WorkloadData.hpp.
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 1847 of file WorkloadData.cpp.
 {
     const std::string descriptorName{"SpaceToBatchNdQueueDescriptor"};
     ValidateNumInputs(workloadInfo,  descriptorName, 1);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     if (m_Parameters.m_BlockShape.size() != m_Parameters.m_PadList.size())
     {
         throw InvalidArgumentException(descriptorName + ": Pad List must contain the same number of "
                                        "dimensions as Block Shape.");
     }
     if (m_Parameters.m_BlockShape.size() == 2)
     {
         ValidateTensorNumDimensions(inputTensorInfo,  descriptorName, 4, "input");
         ValidateTensorNumDimensions(outputTensorInfo, descriptorName, 4, "output");
     }
     else if (m_Parameters.m_BlockShape.size() == 1)
     {
         ValidateTensorNumDimensions(inputTensorInfo,  descriptorName, 3, "input");
         ValidateTensorNumDimensions(outputTensorInfo, descriptorName, 3, "output");
     }
     else
     {
         throw InvalidArgumentException(descriptorName + ": Invalid Block and Crops size.");
     }
     // Check input + padding and output have the same number of elements
     DataLayoutIndexed dimensionIndices(m_Parameters.m_DataLayout);
     const unsigned int inputHeight = inputTensorInfo.GetShape()[dimensionIndices.GetHeightIndex()] +
                                      m_Parameters.m_PadList[0].first + m_Parameters.m_PadList[0].second;
     const unsigned int inputWidth = (inputTensorInfo.GetNumDimensions() == 3) ? 1 :
                                     inputTensorInfo.GetShape()[dimensionIndices.GetWidthIndex()] +
                                     m_Parameters.m_PadList[1].first + m_Parameters.m_PadList[1].second;
     const int channelsIndex_int = (m_Parameters.m_DataLayout == DataLayout::NCHW) ? 1 : -1;
     const unsigned int channelsIndex = channelsIndex_int < 0 ?
             static_cast<unsigned int>(channelsIndex_int) + inputTensorInfo.GetNumDimensions()
             : static_cast<unsigned int>(channelsIndex_int);
     const unsigned int numInputElements = inputTensorInfo.GetShape()[0] *
                                           inputHeight *
                                           inputWidth *
                                           inputTensorInfo.GetShape()[channelsIndex];
     if (outputTensorInfo.GetNumElements() != numInputElements)
     {
         throw InvalidArgumentException(descriptorName + ": Input tensor has " +
                                        to_string(numInputElements) + " after padding but output tensor has " +
                                        to_string(outputTensorInfo.GetNumElements()) + " elements.");
     }
     // In a 4D tensor, there will be 2 spatialDimensions (H and W), and the for loop will run twice.
     // In a 3D tensor, there will be 1 spatialDimensions, and the for loop will run once.
     unsigned int firstSpatialDimension = m_Parameters.m_DataLayout == DataLayout::NCHW ? 2 : 1;
     for (unsigned int i = 0; i < m_Parameters.m_BlockShape.size(); ++i)
     {
         unsigned int spatialDimension = firstSpatialDimension + i;
         auto inputSize = inputTensorInfo.GetShape()[spatialDimension] +
                          m_Parameters.m_PadList[i].first +
                          m_Parameters.m_PadList[i].second;
         if (inputSize % m_Parameters.m_BlockShape[i] != 0)
         {
             throw InvalidArgumentException(descriptorName + ": Input dimension size after padding must be "
                                         "divisible by Block Shape in dimension: " + to_string(spatialDimension) + ".");
         }
     }
     std::vector<DataType> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     ValidateDataTypes(inputTensorInfo, supportedTypes, descriptorName);
     ValidateTensorDataTypesMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
 }
References armnn::BFloat16, armnn::Float16, armnn::Float32, DataLayoutIndexed::GetHeightIndex(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), DataLayoutIndexed::GetWidthIndex(), SpaceToBatchNdDescriptor::m_BlockShape, SpaceToBatchNdDescriptor::m_DataLayout, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, SpaceToBatchNdDescriptor::m_PadList, QueueDescriptorWithParameters< SpaceToBatchNdDescriptor >::m_Parameters, armnn::NCHW, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and QueueDescriptor::ValidateTensorNumDimensions().
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp