Arm NN: ProgramBuilder Struct Reference
ProgramBuilder Struct Reference
#include <ClContextSchema_generated.h>
Public Types
typedef Program Table
Public Member Functions
void add_name (flatbuffers::Offset< flatbuffers::String > name)
void add_binary (flatbuffers::Offset< flatbuffers::Vector< uint8_t >> binary)
ProgramBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ProgramBuilder & operator= (const ProgramBuilder &)
flatbuffers::Offset< Program > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 96 of file ClContextSchema_generated.h.
Member Typedef Documentation
Table
typedef Program Table
Definition at line 97 of file ClContextSchema_generated.h.
Constructor & Destructor Documentation
ProgramBuilder()
ProgramBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 106 of file ClContextSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
References ProgramBuilder::fbb_, and ProgramBuilder::start_.
Member Function Documentation
add_binary()
void add_binary (flatbuffers::Offset< flatbuffers::Vector< uint8_t >> binary) inline
Definition at line 103 of file ClContextSchema_generated.h.
{
     fbb_.AddOffset(Program::VT_BINARY, binary);
   }
References ProgramBuilder::fbb_.
Referenced by armnn::CreateProgram().
add_name()
void add_name (flatbuffers::Offset< flatbuffers::String > name) inline
Definition at line 100 of file ClContextSchema_generated.h.
{
     fbb_.AddOffset(Program::VT_NAME, name);
   }
References ProgramBuilder::fbb_, and VT_NAME.
Referenced by armnn::CreateProgram().
Finish()
flatbuffers::Offset<Program> Finish () inline
Definition at line 111 of file ClContextSchema_generated.h.
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Program>(end);
     return o;
   }
References ProgramBuilder::fbb_, and ProgramBuilder::start_.
Referenced by armnn::CreateProgram().
operator=()
ProgramBuilder& operator= (const ProgramBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 98 of file ClContextSchema_generated.h.
Referenced by ProgramBuilder::add_binary(), ProgramBuilder::add_name(), ProgramBuilder::Finish(), and ProgramBuilder::ProgramBuilder().
start_
flatbuffers::uoffset_t start_
Definition at line 99 of file ClContextSchema_generated.h.
Referenced by ProgramBuilder::Finish(), and ProgramBuilder::ProgramBuilder().
The documentation for this struct was generated from the following file:
src/backends/cl/ClContextSchema_generated.h