Arm NN: StringifyLayerParameters< NormalizationDescriptor > Struct Reference
StringifyLayerParameters< NormalizationDescriptor > Struct Reference
#include <SerializeLayerParameters.hpp>
Static Public Member Functions
static void Serialize (ParameterStringifyFunction &fn, const NormalizationDescriptor &desc)
Detailed Description
Definition at line 118 of file SerializeLayerParameters.hpp.
Member Function Documentation
Serialize()
void Serialize (ParameterStringifyFunction & fn, const NormalizationDescriptor & desc) static
Definition at line 260 of file SerializeLayerParameters.cpp.
 {
     fn("NormChannelType", GetNormalizationAlgorithmChannelAsCString(desc.m_NormChannelType));
     fn("NormMethodType", GetNormalizationAlgorithmMethodAsCString(desc.m_NormMethodType));
     fn("NormSize", std::to_string(desc.m_NormSize));
     fn("Alpha", std::to_string(desc.m_Alpha));
     fn("Beta", std::to_string(desc.m_Beta));
     fn("K", std::to_string(desc.m_K));
     fn("DataLayout", GetDataLayoutName(desc.m_DataLayout));
 }
References armnn::GetDataLayoutName(), armnn::GetNormalizationAlgorithmChannelAsCString(), armnn::GetNormalizationAlgorithmMethodAsCString(), NormalizationDescriptor::m_Alpha, NormalizationDescriptor::m_Beta, NormalizationDescriptor::m_DataLayout, NormalizationDescriptor::m_K, NormalizationDescriptor::m_NormChannelType, NormalizationDescriptor::m_NormMethodType, and NormalizationDescriptor::m_NormSize.
The documentation for this struct was generated from the following files:
src/armnn/SerializeLayerParameters.hpp
src/armnn/SerializeLayerParameters.cpp