ArmNN: src/backends/backendsCommon/test/layerTests/DetectionPostProcessTestImpl.hpp File Reference
DetectionPostProcessTestImpl.hpp File Reference
#include <ResolveType.hpp>
#include <armnn/Types.hpp>
#include <backendsCommon/TensorHandle.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadFactoryHelper.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
#include <doctest/doctest.h>
Functions
template<typename FactoryType , armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
void DetectionPostProcessImpl (const armnn::TensorInfo &boxEncodingsInfo, const armnn::TensorInfo &scoresInfo, const armnn::TensorInfo &anchorsInfo, const std::vector< T > &boxEncodingsData, const std::vector< T > &scoresData, const std::vector< T > &anchorsData, const std::vector< float > &expectedDetectionBoxes, const std::vector< float > &expectedDetectionClasses, const std::vector< float > &expectedDetectionScores, const std::vector< float > &expectedNumDetections, bool useRegularNms)
template<armnn::DataType QuantizedType, typename RawType = armnn::ResolveType<QuantizedType>>
void QuantizeData (RawType *quant, const float *dequant, const armnn::TensorInfo &info)
template<typename FactoryType >
void DetectionPostProcessRegularNmsFloatTest ()
template<typename FactoryType , armnn::DataType QuantizedType, typename RawType = armnn::ResolveType<QuantizedType>>
void DetectionPostProcessRegularNmsQuantizedTest ()
template<typename FactoryType >
void DetectionPostProcessFastNmsFloatTest ()
template<typename FactoryType , armnn::DataType QuantizedType, typename RawType = armnn::ResolveType<QuantizedType>>
void DetectionPostProcessFastNmsQuantizedTest ()
Function Documentation
DetectionPostProcessFastNmsFloatTest()
void DetectionPostProcessFastNmsFloatTest ()
Definition at line 322 of file DetectionPostProcessTestImpl.hpp.
References armnn::Float32.
 {
     return DetectionPostProcessImpl<FactoryType, armnn::DataType::Float32>(
         armnn::TensorInfo(TestData::s_BoxEncodingsShape, armnn::DataType::Float32),
         armnn::TensorInfo(TestData::s_ScoresShape, armnn::DataType::Float32),
         armnn::TensorInfo(TestData::s_AnchorsShape, armnn::DataType::Float32),
         TestData::s_BoxEncodings,
         TestData::s_Scores,
         TestData::s_Anchors,
         FastNmsExpectedResults::s_DetectionBoxes,
         FastNmsExpectedResults::s_DetectionClasses,
         FastNmsExpectedResults::s_DetectionScores,
         FastNmsExpectedResults::s_NumDetections,
         false);
 }
DetectionPostProcessFastNmsQuantizedTest()
void DetectionPostProcessFastNmsQuantizedTest ()
Definition at line 341 of file DetectionPostProcessTestImpl.hpp.
References TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo boxEncodingsInfo(TestData::s_BoxEncodingsShape, QuantizedType);
     armnn::TensorInfo scoresInfo(TestData::s_ScoresShape, QuantizedType);
     armnn::TensorInfo anchorsInfo(TestData::s_AnchorsShape, QuantizedType);
     boxEncodingsInfo.SetQuantizationScale(TestData::s_BoxEncodingsQuantData.first);
     boxEncodingsInfo.SetQuantizationOffset(TestData::s_BoxEncodingsQuantData.second);
     scoresInfo.SetQuantizationScale(TestData::s_ScoresQuantData.first);
     scoresInfo.SetQuantizationOffset(TestData::s_ScoresQuantData.second);
     anchorsInfo.SetQuantizationScale(TestData::s_AnchorsQuantData.first);
     anchorsInfo.SetQuantizationOffset(TestData::s_BoxEncodingsQuantData.second);
     std::vector<RawType> boxEncodingsData(TestData::s_BoxEncodingsShape.GetNumElements());
     QuantizeData<QuantizedType>(boxEncodingsData.data(),
                                 TestData::s_BoxEncodings.data(),
                                 boxEncodingsInfo);
     std::vector<RawType> scoresData(TestData::s_ScoresShape.GetNumElements());
     QuantizeData<QuantizedType>(scoresData.data(),
                                 TestData::s_Scores.data(),
                                 scoresInfo);
     std::vector<RawType> anchorsData(TestData::s_AnchorsShape.GetNumElements());
     QuantizeData<QuantizedType>(anchorsData.data(),
                                 TestData::s_Anchors.data(),
                                 anchorsInfo);
     return DetectionPostProcessImpl<FactoryType, QuantizedType>(
         boxEncodingsInfo,
         scoresInfo,
         anchorsInfo,
         boxEncodingsData,
         scoresData,
         anchorsData,
         FastNmsExpectedResults::s_DetectionBoxes,
         FastNmsExpectedResults::s_DetectionClasses,
         FastNmsExpectedResults::s_DetectionScores,
         FastNmsExpectedResults::s_NumDetections,
         false);
 }
DetectionPostProcessImpl()
void DetectionPostProcessImpl (const armnn::TensorInfo & boxEncodingsInfo, const armnn::TensorInfo & scoresInfo, const armnn::TensorInfo & anchorsInfo, const std::vector< T > & boxEncodingsData, const std::vector< T > & scoresData, const std::vector< T > & anchorsData, const std::vector< float > & expectedDetectionBoxes, const std::vector< float > & expectedDetectionClasses, const std::vector< float > & expectedDetectionScores, const std::vector< float > & expectedNumDetections, bool useRegularNms)
Definition at line 141 of file DetectionPostProcessTestImpl.hpp.
References AllocateAndCopyDataToITensorHandle(), CompareTensors(), CopyDataFromITensorHandle(), CopyDataToITensorHandle(), armnn::Float32, ProfilerManager::GetInstance(), QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, DetectionPostProcessDescriptor::m_UseRegularNms, and ProfilerManager::RegisterProfiler().
 {
     std::unique_ptr<armnn::IProfiler> profiler = std::make_unique<armnn::IProfiler>();
     armnn::ProfilerManager::GetInstance().RegisterProfiler(profiler.get());
     auto memoryManager = WorkloadFactoryHelper<FactoryType>::GetMemoryManager();
     FactoryType workloadFactory = WorkloadFactoryHelper<FactoryType>::GetFactory(memoryManager);
     auto tensorHandleFactory = WorkloadFactoryHelper<FactoryType>::GetTensorHandleFactory(memoryManager);
     armnn::TensorInfo detectionBoxesInfo({ 1, 3, 4 }, armnn::DataType::Float32);
     armnn::TensorInfo detectionClassesInfo({ 1, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo detectionScoresInfo({ 1, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo numDetectionInfo({ 1 }, armnn::DataType::Float32);
     std::vector<float> actualDetectionBoxesOutput(detectionBoxesInfo.GetNumElements());
     std::vector<float> actualDetectionClassesOutput(detectionClassesInfo.GetNumElements());
     std::vector<float> actualDetectionScoresOutput(detectionScoresInfo.GetNumElements());
     std::vector<float> actualNumDetectionOutput(numDetectionInfo.GetNumElements());
     auto boxedHandle = tensorHandleFactory.CreateTensorHandle(boxEncodingsInfo);
     auto scoreshandle = tensorHandleFactory.CreateTensorHandle(scoresInfo);
     auto anchorsHandle = tensorHandleFactory.CreateTensorHandle(anchorsInfo);
     auto outputBoxesHandle = tensorHandleFactory.CreateTensorHandle(detectionBoxesInfo);
     auto classesHandle = tensorHandleFactory.CreateTensorHandle(detectionClassesInfo);
     auto outputScoresHandle = tensorHandleFactory.CreateTensorHandle(detectionScoresInfo);
     auto numDetectionHandle = tensorHandleFactory.CreateTensorHandle(numDetectionInfo);
     armnn::ScopedTensorHandle anchorsTensor(anchorsInfo);
     AllocateAndCopyDataToITensorHandle(&anchorsTensor, anchorsData.data());
     armnn::DetectionPostProcessQueueDescriptor data;
     data.m_Parameters.m_UseRegularNms = useRegularNms;
     data.m_Parameters.m_MaxDetections = 3;
     data.m_Parameters.m_MaxClassesPerDetection = 1;
     data.m_Parameters.m_DetectionsPerClass =1;
     data.m_Parameters.m_NmsScoreThreshold = 0.0;
     data.m_Parameters.m_NmsIouThreshold = 0.5;
     data.m_Parameters.m_NumClasses = 2;
     data.m_Parameters.m_ScaleY = 10.0;
     data.m_Parameters.m_ScaleX = 10.0;
     data.m_Parameters.m_ScaleH = 5.0;
     data.m_Parameters.m_ScaleW = 5.0;
     data.m_Anchors = &anchorsTensor;
     armnn::WorkloadInfo info;
     AddInputToWorkload(data,  info, boxEncodingsInfo, boxedHandle.get());
     AddInputToWorkload(data,  info, scoresInfo, scoreshandle.get());
     AddOutputToWorkload(data, info, detectionBoxesInfo, outputBoxesHandle.get());
     AddOutputToWorkload(data, info, detectionClassesInfo, classesHandle.get());
     AddOutputToWorkload(data, info, detectionScoresInfo, outputScoresHandle.get());
     AddOutputToWorkload(data, info, numDetectionInfo, numDetectionHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateDetectionPostProcess(data, info);
     boxedHandle->Allocate();
     scoreshandle->Allocate();
     outputBoxesHandle->Allocate();
     classesHandle->Allocate();
     outputScoresHandle->Allocate();
     numDetectionHandle->Allocate();
     CopyDataToITensorHandle(boxedHandle.get(), boxEncodingsData.data());
     CopyDataToITensorHandle(scoreshandle.get(), scoresData.data());
     workload->Execute();
     CopyDataFromITensorHandle(actualDetectionBoxesOutput.data(), outputBoxesHandle.get());
     CopyDataFromITensorHandle(actualDetectionClassesOutput.data(), classesHandle.get());
     CopyDataFromITensorHandle(actualDetectionScoresOutput.data(), outputScoresHandle.get());
     CopyDataFromITensorHandle(actualNumDetectionOutput.data(), numDetectionHandle.get());
     auto result = CompareTensors(actualDetectionBoxesOutput,
                                  expectedDetectionBoxes,
                                  outputBoxesHandle->GetShape(),
                                  detectionBoxesInfo.GetShape());
     CHECK_MESSAGE(result.m_Result, result.m_Message.str());
     result = CompareTensors(actualDetectionClassesOutput,
                             expectedDetectionClasses,
                             classesHandle->GetShape(),
                             detectionClassesInfo.GetShape());
     CHECK_MESSAGE(result.m_Result, result.m_Message.str());
     result = CompareTensors(actualDetectionScoresOutput,
                             expectedDetectionScores,
                             outputScoresHandle->GetShape(),
                             detectionScoresInfo.GetShape());
     CHECK_MESSAGE(result.m_Result, result.m_Message.str());
     result = CompareTensors(actualNumDetectionOutput,
                             expectedNumDetections,
                             numDetectionHandle->GetShape(),
                             numDetectionInfo.GetShape());
     CHECK_MESSAGE(result.m_Result, result.m_Message.str());
 }
DetectionPostProcessRegularNmsFloatTest()
void DetectionPostProcessRegularNmsFloatTest ()
Definition at line 258 of file DetectionPostProcessTestImpl.hpp.
References armnn::Float32.
 {
     return DetectionPostProcessImpl<FactoryType, armnn::DataType::Float32>(
         armnn::TensorInfo(TestData::s_BoxEncodingsShape, armnn::DataType::Float32),
         armnn::TensorInfo(TestData::s_ScoresShape, armnn::DataType::Float32),
         armnn::TensorInfo(TestData::s_AnchorsShape, armnn::DataType::Float32),
         TestData::s_BoxEncodings,
         TestData::s_Scores,
         TestData::s_Anchors,
         RegularNmsExpectedResults::s_DetectionBoxes,
         RegularNmsExpectedResults::s_DetectionClasses,
         RegularNmsExpectedResults::s_DetectionScores,
         RegularNmsExpectedResults::s_NumDetections,
         true);
 }
DetectionPostProcessRegularNmsQuantizedTest()
void DetectionPostProcessRegularNmsQuantizedTest ()
Definition at line 277 of file DetectionPostProcessTestImpl.hpp.
References TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo boxEncodingsInfo(TestData::s_BoxEncodingsShape, QuantizedType);
     armnn::TensorInfo scoresInfo(TestData::s_ScoresShape, QuantizedType);
     armnn::TensorInfo anchorsInfo(TestData::s_AnchorsShape, QuantizedType);
     boxEncodingsInfo.SetQuantizationScale(TestData::s_BoxEncodingsQuantData.first);
     boxEncodingsInfo.SetQuantizationOffset(TestData::s_BoxEncodingsQuantData.second);
     scoresInfo.SetQuantizationScale(TestData::s_ScoresQuantData.first);
     scoresInfo.SetQuantizationOffset(TestData::s_ScoresQuantData.second);
     anchorsInfo.SetQuantizationScale(TestData::s_AnchorsQuantData.first);
     anchorsInfo.SetQuantizationOffset(TestData::s_BoxEncodingsQuantData.second);
     std::vector<RawType> boxEncodingsData(TestData::s_BoxEncodingsShape.GetNumElements());
     QuantizeData<QuantizedType>(boxEncodingsData.data(),
                                 TestData::s_BoxEncodings.data(),
                                 boxEncodingsInfo);
     std::vector<RawType> scoresData(TestData::s_ScoresShape.GetNumElements());
     QuantizeData<QuantizedType>(scoresData.data(),
                                 TestData::s_Scores.data(),
                                 scoresInfo);
     std::vector<RawType> anchorsData(TestData::s_AnchorsShape.GetNumElements());
     QuantizeData<QuantizedType>(anchorsData.data(),
                                 TestData::s_Anchors.data(),
                                 anchorsInfo);
     return DetectionPostProcessImpl<FactoryType, QuantizedType>(
         boxEncodingsInfo,
         scoresInfo,
         anchorsInfo,
         boxEncodingsData,
         scoresData,
         anchorsData,
         RegularNmsExpectedResults::s_DetectionBoxes,
         RegularNmsExpectedResults::s_DetectionClasses,
         RegularNmsExpectedResults::s_DetectionScores,
         RegularNmsExpectedResults::s_NumDetections,
         true);
 }
QuantizeData()
void QuantizeData (RawType * quant, const float * dequant, const armnn::TensorInfo & info)
Definition at line 248 of file DetectionPostProcessTestImpl.hpp.
References TensorInfo::GetNumElements(), TensorInfo::GetQuantizationOffset(), and TensorInfo::GetQuantizationScale().
Referenced by TEST_SUITE().
 {
     for (size_t i = 0; i < info.GetNumElements(); i++)
     {
         quant[i] = armnn::Quantize<RawType>(
             dequant[i], info.GetQuantizationScale(), info.GetQuantizationOffset());
     }
 }