ArmNN: src/backends/backendsCommon/test/layerTests/FillTestImpl.cpp File Reference
FillTestImpl.cpp File Reference
#include "FillTestImpl.hpp"
#include <backendsCommon/test/DataTypeUtils.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< T, 4 > SimpleFillTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< armnn::ResolveType< armnn::DataType::Float32 >, 4 > SimpleFillTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< armnn::ResolveType< armnn::DataType::Float16 >, 4 > SimpleFillTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< armnn::ResolveType< armnn::DataType::Signed32 >, 4 > SimpleFillTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
SimpleFillTest()
LayerTestResult<T, 4> SimpleFillTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 15 of file FillTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateFill(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, FillDescriptor::m_Value, and armnn::Signed32.
 {
     IgnoreUnused(memoryManager);
     armnn::TensorInfo inputTensorInfo({4}, armnn::DataType::Signed32);
     armnn::TensorInfo outputTensorInfo({2, 2, 3, 2}, ArmnnType);
     std::vector<int32_t> input = ConvertToDataType<armnn::DataType::Signed32>( { 2, 2, 3, 2 }, inputTensorInfo);
     std::vector<T> actualOutput(outputTensorInfo.GetNumElements());
     std::vector<T> expectedOutput = ConvertToDataType<ArmnnType>(
         {
             1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
             1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f
         },
         outputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::FillQueueDescriptor data;
     data.m_Parameters.m_Value = 1.0f;
     armnn::WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateFill(data, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), input.data());
     workload->Execute();
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     return LayerTestResult<T, 4>(actualOutput,
                                  expectedOutput,
                                  outputHandle->GetShape(),
                                  outputTensorInfo.GetShape());
 }
SimpleFillTest< armnn::DataType::Float16 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::Float16>, 4> SimpleFillTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
SimpleFillTest< armnn::DataType::Float32 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::Float32>, 4> SimpleFillTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
SimpleFillTest< armnn::DataType::Signed32 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::Signed32>, 4> SimpleFillTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)