ArmNN: tests/InferenceTestImage.cpp File Reference
InferenceTestImage.cpp File Reference
#include "InferenceTestImage.hpp"
#include <armnn/utility/Assert.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <armnn/utility/NumericCast.hpp>
#include <fmt/format.h>
#include <array>
#include <stb/stb_image.h>
#include <stb/stb_image_resize.h>
#include <stb/stb_image_write.h>
Macros
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
Functions
template<typename TProcessValueCallable >
std::vector< float > GetImageDataInArmNnLayoutAsFloats (ImageChannelLayout channelLayout, const InferenceTestImage &image, TProcessValueCallable processValue)
std::vector< float > GetImageDataInArmNnLayoutAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage &image)
std::vector< float > GetImageDataInArmNnLayoutAsFloatsSubtractingMean (ImageChannelLayout layout, const InferenceTestImage &image, const std::array< float, 3 > &mean)
std::vector< float > GetImageDataAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage &image)
Macro Definition Documentation
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 15 of file InferenceTestImage.cpp.
STB_IMAGE_RESIZE_IMPLEMENTATION
#define STB_IMAGE_RESIZE_IMPLEMENTATION
Definition at line 18 of file InferenceTestImage.cpp.
STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
Definition at line 21 of file InferenceTestImage.cpp.
Function Documentation
GetImageDataAsNormalizedFloats()
std::vector<float> GetImageDataAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage & image)
Definition at line 333 of file InferenceTestImage.cpp.
References B, G, InferenceTestImage::GetHeight(), InferenceTestImage::GetPixelAs3Channels(), InferenceTestImage::GetWidth(), and R.
 {
     std::vector<float> imageData;
     const unsigned int h = image.GetHeight();
     const unsigned int w = image.GetWidth();
     const unsigned int rDstIndex = GetImageChannelIndex(layout, ImageChannel::R);
     const unsigned int gDstIndex = GetImageChannelIndex(layout, ImageChannel::G);
     const unsigned int bDstIndex = GetImageChannelIndex(layout, ImageChannel::B);
     imageData.resize(h * w * 3);
     unsigned int offset = 0;
     for (unsigned int j = 0; j < h; ++j)
     {
         for (unsigned int i = 0; i < w; ++i)
         {
             uint8_t r, g, b;
             std::tie(r, g, b) = image.GetPixelAs3Channels(i, j);
             imageData[offset+rDstIndex] = float(r) / 255.0f;
             imageData[offset+gDstIndex] = float(g) / 255.0f;
             imageData[offset+bDstIndex] = float(b) / 255.0f;
             offset += 3;
         }
     }
     return imageData;
 }
GetImageDataInArmNnLayoutAsFloats()
std::vector<float> GetImageDataInArmNnLayoutAsFloats (ImageChannelLayout channelLayout, const InferenceTestImage & image, TProcessValueCallable processValue)
Definition at line 279 of file InferenceTestImage.cpp.
References B, G, InferenceTestImage::GetHeight(), InferenceTestImage::GetPixelAs3Channels(), InferenceTestImage::GetWidth(), and R.
Referenced by GetImageDataInArmNnLayoutAsFloatsSubtractingMean(), and GetImageDataInArmNnLayoutAsNormalizedFloats().
 {
     const unsigned int h = image.GetHeight();
     const unsigned int w = image.GetWidth();
     std::vector<float> imageData;
     imageData.resize(h * w * 3);
     for (unsigned int j = 0; j < h; ++j)
     {
         for (unsigned int i = 0; i < w; ++i)
         {
             uint8_t r, g, b;
             std::tie(r, g, b) = image.GetPixelAs3Channels(i, j);
             // ArmNN order: C, H, W
             const unsigned int rDstIndex = GetImageChannelIndex(channelLayout, ImageChannel::R) * h * w + j * w + i;
             const unsigned int gDstIndex = GetImageChannelIndex(channelLayout, ImageChannel::G) * h * w + j * w + i;
             const unsigned int bDstIndex = GetImageChannelIndex(channelLayout, ImageChannel::B) * h * w + j * w + i;
             imageData[rDstIndex] = processValue(ImageChannel::R, float(r));
             imageData[gDstIndex] = processValue(ImageChannel::G, float(g));
             imageData[bDstIndex] = processValue(ImageChannel::B, float(b));
         }
     }
     return imageData;
 }
GetImageDataInArmNnLayoutAsFloatsSubtractingMean()
std::vector<float> GetImageDataInArmNnLayoutAsFloatsSubtractingMean (ImageChannelLayout layout, const InferenceTestImage & image, const std::array< float, 3 > & mean)
Definition at line 321 of file InferenceTestImage.cpp.
References GetImageDataInArmNnLayoutAsFloats().
 {
     return GetImageDataInArmNnLayoutAsFloats(layout, image,
         [layout, &mean](ImageChannel channel, float value)
         {
             const unsigned int channelIndex = GetImageChannelIndex(layout, channel);
             return value - mean[channelIndex];
         });
 }
GetImageDataInArmNnLayoutAsNormalizedFloats()
std::vector<float> GetImageDataInArmNnLayoutAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage & image)
Definition at line 310 of file InferenceTestImage.cpp.
References GetImageDataInArmNnLayoutAsFloats(), and armnn::IgnoreUnused().
Referenced by YoloDatabase::GetTestCaseData().
 {
     return GetImageDataInArmNnLayoutAsFloats(layout, image,
         [](ImageChannel channel, float value)
         {
             armnn::IgnoreUnused(channel);
             return value / 255.f;
         });
 }