ArmNN: src/backends/backendsCommon/test/layerTests/L2NormalizationTestImpl.cpp File Reference
L2NormalizationTestImpl.cpp File Reference
#include "L2NormalizationTestImpl.hpp"
#include <QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnUtils/TensorUtils.hpp>
#include <armnnUtils/Permute.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
#include <numeric>
Functions
LayerTestResult< float, 4 > L2NormalizationDefaultEpsilonTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2NormalizationNonDefaultEpsilonTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2Normalization1dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization1dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2Normalization2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 2 > L2Normalization2dShapeTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > L2Normalization3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2Normalization4dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::DataLayout layout)
Function Documentation
L2Normalization1dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization1dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 616 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization1dTest()
LayerTestResult<float, 4> L2Normalization1dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 599 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization1dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 633 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2Normalization2dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 667 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization2dShapeTest()
LayerTestResult<float, 2> L2Normalization2dShapeTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 701 of file L2NormalizationTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateL2Normalization(), ITensorHandleFactory::CreateTensorHandle(), armnn::Float32, TensorInfo::GetNumElements(), TensorInfo::GetShape(), L2NormalizationDescriptor::m_DataLayout, L2NormalizationDescriptor::m_Eps, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::NHWC.
Referenced by TEST_SUITE().
 {
     const armnn::DataLayout layout = armnn::DataLayout::NHWC;
     const armnn::TensorShape inputOutputTensorShape = armnn::TensorShape({ 5, 2 });
     std::vector<float> inputData
     {
         1.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f, 8.f, 9.f, 10.f
     };
     std::vector<float> expectedOutputData
     {
         1.0f * CalcInvL2Norm({ 1.0f,  2.0f }),
         2.0f * CalcInvL2Norm({ 1.0f,  2.0f }),
         3.0f * CalcInvL2Norm({ 3.0f,  4.0f }),
         4.0f * CalcInvL2Norm({ 3.0f,  4.0f }),
         5.0f * CalcInvL2Norm({ 5.0f,  6.0f }),
         6.0f * CalcInvL2Norm({ 5.0f,  6.0f }),
         7.0f * CalcInvL2Norm({ 7.0f,  8.0f }),
         8.0f * CalcInvL2Norm({ 7.0f,  8.0f }),
         9.0f  * CalcInvL2Norm({ 9.0f, 10.0f }),
         10.0f * CalcInvL2Norm({ 9.0f, 10.0f })
     };
     const armnn::TensorInfo inputTensorInfo(inputOutputTensorShape, armnn::DataType::Float32, 0.f, 0);
     const armnn::TensorInfo outputTensorInfo(inputOutputTensorShape, armnn::DataType::Float32, 0.f, 0);
     std::vector<float> actualOutput(outputTensorInfo.GetNumElements());
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::L2NormalizationQueueDescriptor descriptor;
     descriptor.m_Parameters.m_Eps = 1e-12f;
     descriptor.m_Parameters.m_DataLayout = layout;
     armnn::WorkloadInfo info;
     AddInputToWorkload(descriptor, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateL2Normalization(descriptor, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), inputData.data());
     workload->PostAllocationConfigure();
     ExecuteWorkload(*workload, memoryManager);
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     return LayerTestResult<float, 2>(actualOutput,
                                      expectedOutputData,
                                      outputHandle->GetShape(),
                                      outputTensorInfo.GetShape());
 }
L2Normalization2dTest()
LayerTestResult<float, 4> L2Normalization2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 650 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization2dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization2dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 684 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2Normalization3dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 778 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization3dTest()
LayerTestResult<float, 4> L2Normalization3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 761 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization3dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization3dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 795 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2Normalization4dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 829 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization4dTest()
LayerTestResult<float, 4> L2Normalization4dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 812 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization4dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization4dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 846 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2NormalizationDefaultEpsilonTest()
LayerTestResult<float, 4> L2NormalizationDefaultEpsilonTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 560 of file L2NormalizationTestImpl.cpp.
References L2NormalizationDescriptor::m_Eps.
Referenced by TEST_SUITE().
 {
     // Dummy descriptor to get the default value of epsilon.
     armnn::L2NormalizationDescriptor descriptor;
     return L2NormalizationEpsilonTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         0.f,
         0,
         layout,
         descriptor.m_Eps);
 }
L2NormalizationNonDefaultEpsilonTest()
LayerTestResult<float, 4> L2NormalizationNonDefaultEpsilonTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::DataLayout layout)
Definition at line 581 of file L2NormalizationTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return L2NormalizationEpsilonTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         0.f,
         0,
         0.f,
         0,
         layout,
         1e-9f);
 }