ArmNN: src/backends/aclCommon/test/MemCopyTests.cpp File Reference
MemCopyTests.cpp File Reference
#include <aclCommon/ArmComputeTensorUtils.hpp>
#include <aclCommon/test/MemCopyTestImpl.hpp>
#include <cl/ClWorkloadFactory.hpp>
#include <cl/test/ClContextControlFixture.hpp>
#include <cl/test/ClWorkloadFactoryHelper.hpp>
#include <neon/NeonWorkloadFactory.hpp>
#include <neon/test/NeonWorkloadFactoryHelper.hpp>
#include <doctest/doctest.h>
Functions
TEST_SUITE ("MemCopyCommon")
TEST_CASE_FIXTURE (ClContextControlFixture, "CopyBetweenNeonAndGpu")
TEST_CASE_FIXTURE (ClContextControlFixture, "CopyBetweenGpuAndNeon")
TEST_CASE_FIXTURE (ClContextControlFixture, "CopyBetweenNeonAndGpuWithSubtensors")
TEST_CASE_FIXTURE (ClContextControlFixture, "CopyBetweenGpuAndNeonWithSubtensors")
Function Documentation
TEST_CASE_FIXTURE() [1/4]
TEST_CASE_FIXTURE (ClContextControlFixture , "CopyBetweenNeonAndGpu")
Definition at line 45 of file MemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::m_ActualData, LayerTestResult< T, n >::m_ActualShape, LayerTestResult< T, n >::m_ExpectedData, and LayerTestResult< T, n >::m_ExpectedShape.
Referenced by TEST_SUITE().
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::NeonWorkloadFactory, armnn::ClWorkloadFactory, armnn::DataType::Float32>(false);
     auto predResult = CompareTensors(result.m_ActualData, result.m_ExpectedData,
                                      result.m_ActualShape, result.m_ExpectedShape);
     CHECK_MESSAGE(predResult.m_Result, predResult.m_Message.str());
 }
TEST_CASE_FIXTURE() [2/4]
TEST_CASE_FIXTURE (ClContextControlFixture , "CopyBetweenGpuAndNeon")
Definition at line 54 of file MemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::m_ActualData, LayerTestResult< T, n >::m_ActualShape, LayerTestResult< T, n >::m_ExpectedData, and LayerTestResult< T, n >::m_ExpectedShape.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::ClWorkloadFactory, armnn::NeonWorkloadFactory, armnn::DataType::Float32>(false);
     auto predResult = CompareTensors(result.m_ActualData, result.m_ExpectedData,
                                      result.m_ActualShape, result.m_ExpectedShape);
     CHECK_MESSAGE(predResult.m_Result, predResult.m_Message.str());
 }
TEST_CASE_FIXTURE() [3/4]
TEST_CASE_FIXTURE (ClContextControlFixture , "CopyBetweenNeonAndGpuWithSubtensors")
Definition at line 63 of file MemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::m_ActualData, LayerTestResult< T, n >::m_ActualShape, LayerTestResult< T, n >::m_ExpectedData, and LayerTestResult< T, n >::m_ExpectedShape.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::NeonWorkloadFactory, armnn::ClWorkloadFactory, armnn::DataType::Float32>(true);
     auto predResult = CompareTensors(result.m_ActualData, result.m_ExpectedData,
                                      result.m_ActualShape, result.m_ExpectedShape);
     CHECK_MESSAGE(predResult.m_Result, predResult.m_Message.str());
 }
TEST_CASE_FIXTURE() [4/4]
TEST_CASE_FIXTURE (ClContextControlFixture , "CopyBetweenGpuAndNeonWithSubtensors")
Definition at line 72 of file MemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::m_ActualData, LayerTestResult< T, n >::m_ActualShape, LayerTestResult< T, n >::m_ExpectedData, and LayerTestResult< T, n >::m_ExpectedShape.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::ClWorkloadFactory, armnn::NeonWorkloadFactory, armnn::DataType::Float32>(true);
     auto predResult = CompareTensors(result.m_ActualData, result.m_ExpectedData,
                                      result.m_ActualShape, result.m_ExpectedShape);
     CHECK_MESSAGE(predResult.m_Result, predResult.m_Message.str());
 }
TEST_SUITE()
TEST_SUITE ("MemCopyCommon")
Definition at line 20 of file MemCopyTests.cpp.
 {
 TEST_CASE("AclTypeConversions")
 {
     arm_compute::Strides strides(1, 2, 3, 4);
     armnn::TensorShape convertedStrides = armnn::armcomputetensorutils::GetStrides(strides);
     CHECK(convertedStrides[0] == 4);
     CHECK(convertedStrides[1] == 3);
     CHECK(convertedStrides[2] == 2);
     CHECK(convertedStrides[3] == 1);
     arm_compute::TensorShape shape(5, 6, 7, 8);
     armnn::TensorShape convertedshape = armnn::armcomputetensorutils::GetShape(shape);
     CHECK(convertedshape[0] == 8);
     CHECK(convertedshape[1] == 7);
     CHECK(convertedshape[2] == 6);
     CHECK(convertedshape[3] == 5);
 }
 }