var _serialize_layer_parameters_8hpp =
[
    [ "StringifyLayerParameters", "structarmnn_1_1_stringify_layer_parameters.xhtml", null ],
    [ "StringifyLayerParameters< ActivationDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_activation_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< BatchNormalizationDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_batch_normalization_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< BatchToSpaceNdDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_batch_to_space_nd_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ComparisonDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_comparison_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< Convolution2dDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_convolution2d_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< DetectionPostProcessDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_detection_post_process_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< DepthwiseConvolution2dDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_depthwise_convolution2d_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ElementwiseUnaryDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_unary_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< FakeQuantizationDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_fake_quantization_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< FullyConnectedDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_fully_connected_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< L2NormalizationDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_l2_normalization_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< LstmDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_lstm_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< MeanDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_mean_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< NormalizationDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_normalization_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< OriginsDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_origins_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< PadDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_pad_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< PermuteDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_permute_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< Pooling2dDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_pooling2d_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< PreCompiledDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_pre_compiled_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ReduceDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_reduce_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ReshapeDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_reshape_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ResizeBilinearDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_resize_bilinear_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ResizeDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_resize_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< SpaceToBatchNdDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_space_to_batch_nd_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< SpaceToDepthDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_space_to_depth_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< StackDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_stack_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< StridedSliceDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_strided_slice_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< SoftmaxDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_softmax_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< TransposeConvolution2dDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_transpose_convolution2d_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< TransposeDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_transpose_descriptor_01_4.xhtml", null ],
    [ "StringifyLayerParameters< ViewsDescriptor >", "structarmnn_1_1_stringify_layer_parameters_3_01_views_descriptor_01_4.xhtml", null ],
    [ "ParameterStringifyFunction", "_serialize_layer_parameters_8hpp.xhtml#a8c42c6647e31ebe525aeba878d133e45", null ]
];