ArmNN: src/backends/backendsCommon/test/layerTests/StridedSliceTestImpl.cpp File Reference
StridedSliceTestImpl.cpp File Reference
#include "StridedSliceTestImpl.hpp"
#include <QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
LayerTestResult< float, 4 > StridedSlice4dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSlice4dReverseFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSliceSimpleStrideFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSliceSimpleRangeMaskFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSliceShrinkAxisMaskCTSFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition0Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition1Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0And1Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0And2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0And3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 1 > StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSlice3dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSlice3dReverseFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSlice2dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSlice2dReverseFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSlice4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSlice4dReverseUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSliceSimpleStrideUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSliceSimpleRangeMaskUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition0Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 1 > StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSlice3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSlice3dReverseUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSlice2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSlice2dReverseUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSlice4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSlice4dReverseInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSliceSimpleStrideInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSliceSimpleRangeMaskInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > StridedSliceShrinkAxisMaskInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 3 > StridedSlice3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 3 > StridedSlice3dReverseInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > StridedSlice2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > StridedSlice2dReverseInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
StridedSlice2dFloat32Test()
LayerTestResult<float, 2> StridedSlice2dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1033 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dTest<armnn::DataType::Float32>(workloadFactory,
                                                         memoryManager,
                                                         tensorHandleFactory);
 }
StridedSlice2dInt16Test()
LayerTestResult<int16_t, 2> StridedSlice2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1287 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice2dReverseFloat32Test()
LayerTestResult<float, 2> StridedSlice2dReverseFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1043 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dReverseTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
StridedSlice2dReverseInt16Test()
LayerTestResult<int16_t, 2> StridedSlice2dReverseInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1295 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dReverseTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice2dReverseUint8Test()
LayerTestResult<uint8_t, 2> StridedSlice2dReverseUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1217 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dReverseTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice2dUint8Test()
LayerTestResult<uint8_t, 2> StridedSlice2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1209 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dFloat32Test()
LayerTestResult<float, 3> StridedSlice3dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1013 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dTest<armnn::DataType::Float32>(workloadFactory,
                                                         memoryManager,
                                                         tensorHandleFactory);
 }
StridedSlice3dInt16Test()
LayerTestResult<int16_t, 3> StridedSlice3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1271 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dReverseFloat32Test()
LayerTestResult<float, 3> StridedSlice3dReverseFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1023 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dReverseTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
StridedSlice3dReverseInt16Test()
LayerTestResult<int16_t, 3> StridedSlice3dReverseInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1279 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dReverseTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dReverseUint8Test()
LayerTestResult<uint8_t, 3> StridedSlice3dReverseUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1201 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dReverseTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dUint8Test()
LayerTestResult<uint8_t, 3> StridedSlice3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1193 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice4dFloat32Test()
LayerTestResult<float, 4> StridedSlice4dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 863 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dTest<armnn::DataType::Float32>(workloadFactory,
                                                         memoryManager,
                                                         tensorHandleFactory);
 }
StridedSlice4dInt16Test()
LayerTestResult<int16_t, 4> StridedSlice4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1225 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice4dReverseFloat32Test()
LayerTestResult<float, 4> StridedSlice4dReverseFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 873 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dReverseTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
StridedSlice4dReverseInt16Test()
LayerTestResult<int16_t, 4> StridedSlice4dReverseInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1233 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dReverseTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice4dReverseUint8Test()
LayerTestResult<uint8_t, 4> StridedSlice4dReverseUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1063 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dReverseTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory);
 }
StridedSlice4dUint8Test()
LayerTestResult<uint8_t, 4> StridedSlice4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1053 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                          memoryManager,
                                                          tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test()
LayerTestResult<float, 1> StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1003 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1And3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                         memoryManager,
                                                                                         tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test()
LayerTestResult<uint8_t, 1> StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1183 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1And3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                          memoryManager,
                                                                                          tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0And1Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 973 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1153 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And2Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0And2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 983 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And2Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1163 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And2Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And3Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0And3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 993 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1173 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 923 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Dim3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1103 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Dim3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition0Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 933 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition0Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1113 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition1Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition1Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 943 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition1Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition1Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1123 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition1Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition2Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 953 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition2Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition2Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1133 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition2Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition3Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 963 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition3Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1143 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskCTSFloat32Test()
LayerTestResult<float, 4> StridedSliceShrinkAxisMaskCTSFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 913 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskCTSTest<armnn::DataType::Float32>(workloadFactory,
                                                                        memoryManager,
                                                                        tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskFloat32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 903 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskTest<armnn::DataType::Float32>(workloadFactory,
                                                                     memoryManager,
                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskInt16Test()
LayerTestResult<int16_t, 2> StridedSliceShrinkAxisMaskInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1261 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskUint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1093 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
StridedSliceSimpleRangeMaskFloat32Test()
LayerTestResult<float, 4> StridedSliceSimpleRangeMaskFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 893 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleRangeMaskTest<armnn::DataType::Float32>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
StridedSliceSimpleRangeMaskInt16Test()
LayerTestResult<int16_t, 4> StridedSliceSimpleRangeMaskInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1251 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleRangeMaskTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
StridedSliceSimpleRangeMaskUint8Test()
LayerTestResult<uint8_t, 4> StridedSliceSimpleRangeMaskUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1083 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleRangeMaskTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
StridedSliceSimpleStrideFloat32Test()
LayerTestResult<float, 4> StridedSliceSimpleStrideFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 883 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleStrideTest<armnn::DataType::Float32>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
StridedSliceSimpleStrideInt16Test()
LayerTestResult<int16_t, 4> StridedSliceSimpleStrideInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1241 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleStrideTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
StridedSliceSimpleStrideUint8Test()
LayerTestResult<uint8_t, 4> StridedSliceSimpleStrideUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1073 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleStrideTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }