ArmNN: src/armnn/test/TensorHandleStrategyTest.cpp File Reference
TensorHandleStrategyTest.cpp File Reference
#include <doctest/doctest.h>
#include <armnn/LayerVisitorBase.hpp>
#include <armnn/backends/IBackendContext.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/IMemoryManager.hpp>
#include <armnn/backends/ITensorHandleFactory.hpp>
#include <backendsCommon/TensorHandleFactoryRegistry.hpp>
#include <optimizations/Optimization.hpp>
#include <Network.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <vector>
#include <string>
Functions
TEST_SUITE ("TensorHandle")
Function Documentation
TEST_SUITE()
TEST_SUITE ("TensorHandle")
Definition at line 274 of file TensorHandleStrategyTest.cpp.
References Graph::AddCompatibilityLayers(), Graph::AddLayer(), OutputSlot::Connect(), armnn::CopyToTarget, armnn::DirectCompatibility, armnn::ExportToTarget, Graph::ForEachLayer(), OutputSlot::GetEdgeStrategyForConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), OutputSlot::GetTensorHandleFactoryId(), Layer::GetType(), armnn::MemCopy, armnn::MemImport, armnn::SelectTensorHandleStrategy(), Layer::SetBackendId(), and Graph::TopologicalSort().
 {
 TEST_CASE("RegisterFactories")
 {
     TestBackendA backendA;
     TestBackendB backendB;
     CHECK(backendA.GetHandleFactoryPreferences()[0] == "TestHandleFactoryA1");
     CHECK(backendA.GetHandleFactoryPreferences()[1] == "TestHandleFactoryA2");
     CHECK(backendA.GetHandleFactoryPreferences()[2] == "TestHandleFactoryB1");
     CHECK(backendA.GetHandleFactoryPreferences()[3] == "TestHandleFactoryD1");
     TensorHandleFactoryRegistry registry;
     backendA.RegisterTensorHandleFactories(registry);
     backendB.RegisterTensorHandleFactories(registry);
     CHECK((registry.GetFactory("Non-existing Backend") == nullptr));
     CHECK((registry.GetFactory("TestHandleFactoryA1") != nullptr));
     CHECK((registry.GetFactory("TestHandleFactoryA2") != nullptr));
     CHECK((registry.GetFactory("TestHandleFactoryB1") != nullptr));
 }
 TEST_CASE("TensorHandleSelectionStrategy")
 {
     auto backendA = std::make_unique<TestBackendA>();
     auto backendB = std::make_unique<TestBackendB>();
     auto backendC = std::make_unique<TestBackendC>();
     auto backendD = std::make_unique<TestBackendD>();
     TensorHandleFactoryRegistry registry;
     backendA->RegisterTensorHandleFactories(registry);
     backendB->RegisterTensorHandleFactories(registry);
     backendC->RegisterTensorHandleFactories(registry);
     backendD->RegisterTensorHandleFactories(registry);
     BackendsMap backends;
     backends["BackendA"] = std::move(backendA);
     backends["BackendB"] = std::move(backendB);
     backends["BackendC"] = std::move(backendC);
     backends["BackendD"] = std::move(backendD);
     armnn::Graph graph;
     armnn::InputLayer* const inputLayer = graph.AddLayer<armnn::InputLayer>(0, "input");
     inputLayer->SetBackendId("BackendA");
     armnn::SoftmaxDescriptor smDesc;
     armnn::SoftmaxLayer* const softmaxLayer1 = graph.AddLayer<armnn::SoftmaxLayer>(smDesc, "softmax1");
     softmaxLayer1->SetBackendId("BackendA");
     armnn::SoftmaxLayer* const softmaxLayer2 = graph.AddLayer<armnn::SoftmaxLayer>(smDesc, "softmax2");
     softmaxLayer2->SetBackendId("BackendB");
     armnn::SoftmaxLayer* const softmaxLayer3 = graph.AddLayer<armnn::SoftmaxLayer>(smDesc, "softmax3");
     softmaxLayer3->SetBackendId("BackendC");
     armnn::SoftmaxLayer* const softmaxLayer4 = graph.AddLayer<armnn::SoftmaxLayer>(smDesc, "softmax4");
     softmaxLayer4->SetBackendId("BackendD");
     armnn::OutputLayer* const outputLayer = graph.AddLayer<armnn::OutputLayer>(0, "output");
     outputLayer->SetBackendId("BackendA");
     inputLayer->GetOutputSlot(0).Connect(softmaxLayer1->GetInputSlot(0));
     softmaxLayer1->GetOutputSlot(0).Connect(softmaxLayer2->GetInputSlot(0));
     softmaxLayer2->GetOutputSlot(0).Connect(softmaxLayer3->GetInputSlot(0));
     softmaxLayer3->GetOutputSlot(0).Connect(softmaxLayer4->GetInputSlot(0));
     softmaxLayer4->GetOutputSlot(0).Connect(outputLayer->GetInputSlot(0));
     graph.TopologicalSort();
     std::vector<std::string> errors;
     auto result = SelectTensorHandleStrategy(graph, backends, registry, true, errors);
     CHECK(result.m_Error == false);
     CHECK(result.m_Warning == false);
     OutputSlot& inputLayerOut = inputLayer->GetOutputSlot(0);
     OutputSlot& softmaxLayer1Out = softmaxLayer1->GetOutputSlot(0);
     OutputSlot& softmaxLayer2Out = softmaxLayer2->GetOutputSlot(0);
     OutputSlot& softmaxLayer3Out = softmaxLayer3->GetOutputSlot(0);
     OutputSlot& softmaxLayer4Out = softmaxLayer4->GetOutputSlot(0);
     // Check that the correct factory was selected
     CHECK(inputLayerOut.GetTensorHandleFactoryId() == "TestHandleFactoryD1");
     CHECK(softmaxLayer1Out.GetTensorHandleFactoryId() == "TestHandleFactoryB1");
     CHECK(softmaxLayer2Out.GetTensorHandleFactoryId() == "TestHandleFactoryB1");
     CHECK(softmaxLayer3Out.GetTensorHandleFactoryId() == "TestHandleFactoryC1");
     CHECK(softmaxLayer4Out.GetTensorHandleFactoryId() == "TestHandleFactoryD1");
     // Check that the correct strategy was selected
     CHECK((inputLayerOut.GetEdgeStrategyForConnection(0) == EdgeStrategy::DirectCompatibility));
     CHECK((softmaxLayer1Out.GetEdgeStrategyForConnection(0) == EdgeStrategy::DirectCompatibility));
     CHECK((softmaxLayer2Out.GetEdgeStrategyForConnection(0) == EdgeStrategy::CopyToTarget));
     CHECK((softmaxLayer3Out.GetEdgeStrategyForConnection(0) == EdgeStrategy::ExportToTarget));
     CHECK((softmaxLayer4Out.GetEdgeStrategyForConnection(0) == EdgeStrategy::DirectCompatibility));
     graph.AddCompatibilityLayers(backends, registry);
     // Test for copy layers
     int copyCount= 0;
     graph.ForEachLayer([&copyCount](Layer* layer)
     {
         if (layer->GetType() == LayerType::MemCopy)
         {
             copyCount++;
         }
     });
     CHECK(copyCount == 1);
     // Test for import layers
     int importCount= 0;
     graph.ForEachLayer([&importCount](Layer *layer)
     {
         if (layer->GetType() == LayerType::MemImport)
         {
             importCount++;
         }
     });
     CHECK(importCount == 1);
 }
 }