ArmNN: src/backends/backendsCommon/test/TestDynamicBackend.cpp File Reference
TestDynamicBackend.cpp File Reference
#include "TestDynamicBackend.hpp"
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
Functions
constexpr const char * TestDynamicBackendId ()
const char * GetBackendId ()
void GetVersion (uint32_t *outMajor, uint32_t *outMinor)
void * BackendFactory ()
Function Documentation
BackendFactory()
void* BackendFactory ()
Definition at line 128 of file TestDynamicBackend.cpp.
 {
 #if defined(INVALID_TEST_DYNAMIC_BACKEND_6)
     // Return an invalid backend instance
     return nullptr;
 #else
     // Return a non-null backend instance
     return new TestDynamicBackend();
 #endif
 }
GetBackendId()
const char* GetBackendId ()
Definition at line 80 of file TestDynamicBackend.cpp.
Referenced by TEST_SUITE().
 {
 #if defined(INVALID_TEST_DYNAMIC_BACKEND_5) || \
     defined(INVALID_TEST_DYNAMIC_BACKEND_8)
     // Return an invalid backend id
     return nullptr;
 #else
     // Return a valid backend id
     return TestDynamicBackendId();
 #endif
 }
GetVersion()
void GetVersion (uint32_t * outMajor, uint32_t * outMinor)
Definition at line 96 of file TestDynamicBackend.cpp.
 {
     if (!outMajor || !outMinor)
     {
         return;
     }
 #if defined(INVALID_TEST_DYNAMIC_BACKEND_7) || \
     defined(INVALID_TEST_DYNAMIC_BACKEND_8)
     *outMajor = 0;
     *outMinor = 7;
 #else
     armnn::BackendVersion apiVersion = armnn::IBackendInternal::GetApiVersion();
     *outMajor = apiVersion.m_Major;
 #if defined(INVALID_TEST_DYNAMIC_BACKEND_9)
     *outMinor = apiVersion.m_Minor + 1;
 #else
     *outMinor = apiVersion.m_Minor;
 #endif
 #endif
 }
TestDynamicBackendId()
constexpr const char* TestDynamicBackendId ()
Definition at line 12 of file TestDynamicBackend.cpp.
References IBackendInternal::CreateWorkloadFactory(), IBackend::GetId(), IBackendInternal::GetLayerSupport(), and armnn::IgnoreUnused().
Referenced by GetBackendId().
 {
 #if defined(VALID_TEST_DYNAMIC_BACKEND_1)
     return "ValidTestDynamicBackend";
 #elif defined(VALID_TEST_DYNAMIC_BACKEND_2) || \
       defined(VALID_TEST_DYNAMIC_BACKEND_4) || \
       defined(INVALID_TEST_DYNAMIC_BACKEND_9)
     // This backend id is shared among different test dynamic backends for testing purposes:
     // the test dynamic backend 4 is actually a duplicate of the test dynamic backend 2 (with the same version),
     // the test dynamic backend 9 is actually a duplicate of the test dynamic backend 2 (but with a version
     // incompatible with the current Backend API)
     return "TestValid2";
 #elif defined(VALID_TEST_DYNAMIC_BACKEND_3)
     // The test dynamic backend 3 is a different backend than the test dynamic backend 2
     return "TestValid3";
 #elif defined(VALID_TEST_DYNAMIC_BACKEND_5)
     // The test dynamic backend 5 is a different backend than the test dynamic backend 2
     return "TestValid5";
 #elif defined(INVALID_TEST_DYNAMIC_BACKEND_10)
     // Empty backend id
     return "";
 #elif defined(INVALID_TEST_DYNAMIC_BACKEND_11)
     // "Unknown" backend id, "Unknown" is a reserved id in ArmNN
     return "Unknown";
 #else
     return "InvalidTestDynamicBackend";
 #endif
 }