ArmNN: IPeriodicCounterCapture Class Reference
IPeriodicCounterCapture Class Reference abstract
#include <IPeriodicCounterCapture.hpp>
Public Member Functions
virtual ~IPeriodicCounterCapture ()
virtual void Start ()=0
virtual void Stop ()=0
Detailed Description
Definition at line 13 of file IPeriodicCounterCapture.hpp.
Constructor & Destructor Documentation
~IPeriodicCounterCapture()
virtual ~IPeriodicCounterCapture () inline virtual
Definition at line 16 of file IPeriodicCounterCapture.hpp.
References IPeriodicCounterCapture::Start(), and IPeriodicCounterCapture::Stop().
 {}
Member Function Documentation
Start()
virtual void Start () pure virtual
Implemented in PeriodicCounterCapture.
Referenced by PeriodicCounterSelectionCommandHandler::operator()(), and IPeriodicCounterCapture::~IPeriodicCounterCapture().
Stop()
virtual void Stop () pure virtual
Implemented in PeriodicCounterCapture.
Referenced by PeriodicCounterSelectionCommandHandler::operator()(), and IPeriodicCounterCapture::~IPeriodicCounterCapture().
The documentation for this class was generated from the following file:
src/profiling/IPeriodicCounterCapture.hpp