ArmNN: NeonWorkloadFactory Class Reference
NeonWorkloadFactory Class Reference
#include <NeonWorkloadFactory.hpp>
Public Member Functions
NeonWorkloadFactory (const std::shared_ptr< NeonMemoryManager > &memoryManager)
NeonWorkloadFactory (const std::shared_ptr< NeonMemoryManager > &memoryManager, const IBackendInternal::IBackendSpecificModelContextPtr &modelContextPtr)
const BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor &descriptor, const WorkloadInfo &Info) const override
std::unique_ptr< IWorkload > CreateCast (const CastQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &Info) const override
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &Info) const override
std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFill (const FillQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLogicalBinary (const LogicalBinaryQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor &descriptor, const WorkloadInfo &Info) const override
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMerger (const MergerQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateRank (const RankQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateReduce (const ReduceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
Public Member Functions inherited from WorkloadFactoryBase
std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMerge (const MergeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSwitch (const SwitchQueueDescriptor &, const WorkloadInfo &) const override
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual void AfterWorkloadsCreated ()
virtual std::unique_ptr< IWorkload > CreateLogicalUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateShape (const ShapeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateUnidirectionalSequenceLstm (const UnidirectionalSequenceLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const
Static Public Member Functions
static bool IsLayerSupported (const Layer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 20 of file NeonWorkloadFactory.hpp.
Constructor & Destructor Documentation
NeonWorkloadFactory() [1/2]
NeonWorkloadFactory (const std::shared_ptr< NeonMemoryManager > & memoryManager)
Definition at line 73 of file NeonWorkloadFactory.cpp.
     : m_MemoryManager(memoryManager), m_ModelContextPtr(IBackendInternal::IBackendSpecificModelContextPtr{})
 {
     SetNumberOfThreads();
 }
NeonWorkloadFactory() [2/2]
NeonWorkloadFactory (const std::shared_ptr< NeonMemoryManager > & memoryManager, const IBackendInternal::IBackendSpecificModelContextPtr & modelContextPtr)
Definition at line 79 of file NeonWorkloadFactory.cpp.
     : m_MemoryManager(memoryManager), m_ModelContextPtr(modelContextPtr)
 {
     SetNumberOfThreads();
 }
Member Function Documentation
CreateAbs()
std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 134 of file NeonWorkloadFactory.cpp.
References armnn::Abs, NeonWorkloadFactory::CreateElementwiseUnary(), armnn::IgnoreUnused(), and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(descriptor);
     ElementwiseUnaryQueueDescriptor elementwiseUnaryDescriptor;
     elementwiseUnaryDescriptor.m_Parameters = ElementwiseUnaryDescriptor(UnaryOperation::Abs);
     return CreateElementwiseUnary(elementwiseUnaryDescriptor, info);
 }
CreateActivation()
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 145 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors(), and TEST_SUITE().
 {
     return std::make_unique<NeonActivationWorkload>(descriptor, info);
 }
CreateAddition()
std::unique_ptr< armnn::IWorkload > CreateAddition (const AdditionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 151 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonAdditionWorkload>(descriptor, info);
 }
CreateArgMinMax()
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 157 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonArgMinMaxWorkload>(descriptor, info);
 }
CreateBatchNormalization()
std::unique_ptr< armnn::IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 163 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonBatchNormalizationWorkload>(descriptor, info);
 }
CreateBatchToSpaceNd()
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor & descriptor, const WorkloadInfo & Info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 169 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonBatchToSpaceNdWorkload>(descriptor, info);
 }
CreateCast()
std::unique_ptr< IWorkload > CreateCast (const CastQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 175 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonCastWorkload>(descriptor, info);
 }
CreateComparison()
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor & descriptor, const WorkloadInfo & Info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 181 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::CreateEqual(), NeonWorkloadFactory::CreateGreater(), and NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonComparisonWorkload>(descriptor, info);
 }
CreateConcat()
std::unique_ptr< armnn::IWorkload > CreateConcat (const ConcatQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 187 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::CreateMerger(), and NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonConcatWorkload>(descriptor, info);
 }
CreateConstant()
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 193 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonConstantWorkload>(descriptor, info);
 }
CreateConvertBf16ToFp32()
std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 199 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonConvertBf16ToFp32Workload>(descriptor, info);
 }
CreateConvertFp16ToFp32()
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 206 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonConvertFp16ToFp32Workload>(descriptor, info);
 }
CreateConvertFp32ToBf16()
std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 213 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonConvertFp32ToBf16Workload>(descriptor, info);
 }
CreateConvertFp32ToFp16()
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 220 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonConvertFp32ToFp16Workload>(descriptor, info);
 }
CreateConvolution2d()
std::unique_ptr< armnn::IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 227 of file NeonWorkloadFactory.cpp.
References armnn::info, and NeonBackendModelContext::IsFastMathEnabled().
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     bool isFastMathEnabled = false;
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<NeonBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
     return std::make_unique<NeonConvolution2dWorkload>(descriptor,
                                                        info,
                                                        m_MemoryManager->GetIntraLayerManager(),
                                                        isFastMathEnabled);
 }
CreateDebug()
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 248 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NullWorkload, NullWorkload>(descriptor, info);
 }
CreateDepthToSpace()
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 254 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonDepthToSpaceWorkload>(descriptor, info);
 }
CreateDepthwiseConvolution2d()
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 260 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonDepthwiseConvolutionWorkload>(descriptor, info);
 }
CreateDequantize()
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 266 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonDequantizeWorkload>(descriptor, info);
 }
CreateDetectionPostProcess()
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 272 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NullWorkload, NullWorkload>(descriptor, info);
 }
CreateDivision()
std::unique_ptr< armnn::IWorkload > CreateDivision (const DivisionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 278 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonDivisionWorkload>(descriptor, info);
 }
CreateElementwiseUnary()
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & Info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 284 of file NeonWorkloadFactory.cpp.
References armnn::Abs, armnn::Exp, armnn::info, armnn::Log, armnn::LogicalNot, QueueDescriptor::m_Inputs, ElementwiseUnaryDescriptor::m_Operation, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::Neg, armnn::Rsqrt, and armnn::Sin.
Referenced by NeonWorkloadFactory::CreateAbs(), NeonWorkloadFactory::CreateRsqrt(), and NeonWorkloadFactory::SupportsSubTensors().
 {
     switch(descriptor.m_Parameters.m_Operation)
     {
         case UnaryOperation::Abs:
         {
             AbsQueueDescriptor absQueueDescriptor;
             absQueueDescriptor.m_Inputs  = descriptor.m_Inputs;
             absQueueDescriptor.m_Outputs = descriptor.m_Outputs;
             return std::make_unique<NeonAbsWorkload>(absQueueDescriptor, info);
         }
         case UnaryOperation::Exp:
             return std::make_unique<NeonExpWorkload>(descriptor, info);
         case UnaryOperation::LogicalNot:
             return std::make_unique<NeonLogicalNotWorkload>(descriptor, info);
         case UnaryOperation::Log:
             return std::make_unique<NeonLogWorkload>(descriptor, info);
         case UnaryOperation::Neg:
             return std::make_unique<NeonNegWorkload>(descriptor, info);
         case UnaryOperation::Rsqrt:
         {
             RsqrtQueueDescriptor rsqrtQueueDescriptor;
             rsqrtQueueDescriptor.m_Inputs  = descriptor.m_Inputs;
             rsqrtQueueDescriptor.m_Outputs = descriptor.m_Outputs;
             return std::make_unique<NeonRsqrtWorkload>(rsqrtQueueDescriptor, info);
         }
         case UnaryOperation::Sin:
             return std::make_unique<NeonSinWorkload>(descriptor, info);
         default:
             return nullptr;
     }
 }
CreateEqual()
std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 320 of file NeonWorkloadFactory.cpp.
References NeonWorkloadFactory::CreateComparison(), armnn::Equal, armnn::IgnoreUnused(), and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(descriptor);
     ComparisonQueueDescriptor comparisonDescriptor;
     comparisonDescriptor.m_Parameters = ComparisonDescriptor(ComparisonOperation::Equal);
     return CreateComparison(comparisonDescriptor, info);
 }
CreateFill()
std::unique_ptr< IWorkload > CreateFill (const FillQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 331 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonFillWorkload>(descriptor, info);
 }
CreateFloor()
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 337 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NeonFloorFloatWorkload, NullWorkload>(descriptor, info);
 }
CreateFullyConnected()
std::unique_ptr< armnn::IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 343 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonFullyConnectedWorkload>(descriptor, info, m_MemoryManager->GetIntraLayerManager());
 }
CreateGather()
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 349 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonGatherWorkload>(descriptor, info);
 }
CreateGreater()
std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 355 of file NeonWorkloadFactory.cpp.
References NeonWorkloadFactory::CreateComparison(), armnn::Greater, armnn::IgnoreUnused(), and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(descriptor);
     ComparisonQueueDescriptor comparisonDescriptor;
     comparisonDescriptor.m_Parameters = ComparisonDescriptor(ComparisonOperation::Greater);
     return CreateComparison(comparisonDescriptor, info);
 }
CreateInput()
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 366 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreateInstanceNormalization()
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 372 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonInstanceNormalizationWorkload>(descriptor, info);
 }
CreateL2Normalization()
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 379 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NeonL2NormalizationFloatWorkload, NullWorkload>(descriptor, info,
                                                                               m_MemoryManager->GetIntraLayerManager());
 }
CreateLogicalBinary()
std::unique_ptr< IWorkload > CreateLogicalBinary (const LogicalBinaryQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 392 of file NeonWorkloadFactory.cpp.
References armnn::info, armnn::LogicalAnd, armnn::LogicalOr, LogicalBinaryDescriptor::m_Operation, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     switch(descriptor.m_Parameters.m_Operation)
     {
         case LogicalBinaryOperation::LogicalAnd:
             return std::make_unique<NeonLogicalAndWorkload>(descriptor, info);
         case LogicalBinaryOperation::LogicalOr:
             return std::make_unique<NeonLogicalOrWorkload>(descriptor, info);
         default:
             return nullptr;
     }
 }
CreateLogSoftmax()
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 386 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonLogSoftmaxWorkload>(descriptor, info, m_MemoryManager->GetIntraLayerManager());
 }
CreateLstm()
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 406 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NeonLstmFloatWorkload, NullWorkload>(descriptor, info);
 }
CreateMaximum()
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 412 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonMaximumWorkload>(descriptor, info);
 }
CreateMean()
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor & descriptor, const WorkloadInfo & Info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 418 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonMeanWorkload>(descriptor, info);
 }
CreateMemCopy()
std::unique_ptr< armnn::IWorkload > CreateMemCopy (const MemCopyQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 424 of file NeonWorkloadFactory.cpp.
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     if (descriptor.m_Inputs.empty() || !descriptor.m_Inputs[0])
     {
         throw InvalidArgumentException("NeonWorkloadFactory: Invalid null input for MemCopy workload");
     }
     return MakeWorkloadHelper<CopyMemGenericWorkload, CopyMemGenericWorkload>(descriptor, info);
 }
CreateMemImport()
std::unique_ptr< armnn::IWorkload > CreateMemImport (const MemImportQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 435 of file NeonWorkloadFactory.cpp.
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     if (descriptor.m_Inputs.empty() || !descriptor.m_Inputs[0])
     {
         throw InvalidArgumentException("NeonWorkloadFactory: Invalid null input for MemImport workload");
     }
     return std::make_unique<ImportMemGenericWorkload>(descriptor, info);
 }
CreateMerger()
std::unique_ptr< armnn::IWorkload > CreateMerger (const MergerQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 446 of file NeonWorkloadFactory.cpp.
References NeonWorkloadFactory::CreateConcat().
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return CreateConcat(descriptor, info);
 }
CreateMinimum()
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 452 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonMinimumWorkload>(descriptor, info);
 }
CreateMultiplication()
std::unique_ptr< armnn::IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 458 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonMultiplicationWorkload>(descriptor, info);
 }
CreateNormalization()
std::unique_ptr< armnn::IWorkload > CreateNormalization (const NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 464 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NeonNormalizationFloatWorkload, NullWorkload>(descriptor, info,
                                                                             m_MemoryManager->GetIntraLayerManager());
 }
CreateOutput()
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 471 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreatePad()
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 477 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonPadWorkload>(descriptor, info);
 }
CreatePermute()
std::unique_ptr< armnn::IWorkload > CreatePermute (const PermuteQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 483 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonPermuteWorkload>(descriptor, info);
 }
CreatePooling2d()
std::unique_ptr< armnn::IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 489 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonPooling2dWorkload>(descriptor, info);
 }
CreatePreCompiled()
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 495 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkloadHelper<NullWorkload, NullWorkload>(descriptor, info);
 }
CreatePrelu()
std::unique_ptr< armnn::IWorkload > CreatePrelu (const PreluQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 501 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonPreluWorkload>(descriptor, info);
 }
CreateQLstm()
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 507 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonQLstmWorkload>(descriptor, info);
 }
CreateQuantize()
std::unique_ptr< armnn::IWorkload > CreateQuantize (const QuantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 513 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonQuantizeWorkload>(descriptor, info);
 }
CreateQuantizedLstm()
std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 519 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonQuantizedLstmWorkload>(descriptor, info);
 }
CreateRank()
std::unique_ptr< IWorkload > CreateRank (const RankQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 525 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonRankWorkload>(descriptor, info);
 }
CreateReduce()
std::unique_ptr< IWorkload > CreateReduce (const ReduceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 531 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonReduceWorkload>(descriptor, info);
 }
CreateReshape()
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 537 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonReshapeWorkload>(descriptor, info);
 }
CreateResize()
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 543 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::CreateResizeBilinear(), and NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonResizeWorkload>(descriptor, info);
 }
CreateResizeBilinear()
std::unique_ptr< armnn::IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 549 of file NeonWorkloadFactory.cpp.
References NeonWorkloadFactory::CreateResize(), ResizeBilinearDescriptor::m_DataLayout, ResizeDescriptor::m_DataLayout, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, ResizeBilinearDescriptor::m_TargetHeight, ResizeDescriptor::m_TargetHeight, ResizeBilinearDescriptor::m_TargetWidth, and ResizeDescriptor::m_TargetWidth.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     ResizeQueueDescriptor resizeDescriptor;
     resizeDescriptor.m_Inputs  = descriptor.m_Inputs;
     resizeDescriptor.m_Outputs = descriptor.m_Outputs;
     resizeDescriptor.m_Parameters.m_DataLayout   = descriptor.m_Parameters.m_DataLayout;
     resizeDescriptor.m_Parameters.m_TargetWidth  = descriptor.m_Parameters.m_TargetWidth;
     resizeDescriptor.m_Parameters.m_TargetHeight = descriptor.m_Parameters.m_TargetHeight;
     return CreateResize(resizeDescriptor, info);
 }
CreateRsqrt()
std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 564 of file NeonWorkloadFactory.cpp.
References NeonWorkloadFactory::CreateElementwiseUnary(), armnn::IgnoreUnused(), QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::Rsqrt.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(descriptor);
     ElementwiseUnaryQueueDescriptor elementwiseUnaryDescriptor;
     elementwiseUnaryDescriptor.m_Parameters = ElementwiseUnaryDescriptor(UnaryOperation::Rsqrt);
     return CreateElementwiseUnary(elementwiseUnaryDescriptor, info);
 }
CreateSlice()
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 575 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonSliceWorkload>(descriptor, info);
 }
CreateSoftmax()
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 581 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonSoftmaxWorkload>(descriptor, info, m_MemoryManager->GetIntraLayerManager());
 }
CreateSpaceToBatchNd()
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 587 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonSpaceToBatchNdWorkload>(descriptor, info);
 }
CreateSpaceToDepth()
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 593 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonSpaceToDepthWorkload>(descriptor, info);
 }
CreateSplitter()
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 599 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonSplitterWorkload>(descriptor, info);
 }
CreateStack()
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 605 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonStackWorkload>(descriptor, info);
 }
CreateStridedSlice()
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 611 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonStridedSliceWorkload>(descriptor, info);
 }
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 86 of file NeonWorkloadFactory.cpp.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     const arm_compute::TensorShape shape = armcomputetensorutils::BuildArmComputeTensorShape(subTensorShape);
     arm_compute::Coordinates coords;
     coords.set_num_dimensions(subTensorShape.GetNumDimensions());
     for (unsigned int i = 0; i < subTensorShape.GetNumDimensions(); i++)
     {
         // Arm compute indexes tensor coords in reverse order.
         unsigned int revertedIndex = subTensorShape.GetNumDimensions() - i - 1;
         coords.set(i, armnn::numeric_cast<int>(subTensorOrigin[revertedIndex]));
     }
     const arm_compute::TensorShape parentShape = armcomputetensorutils::BuildArmComputeTensorShape(parent.GetShape());
     if (!::arm_compute::error_on_invalid_subtensor(__func__, __FILE__, __LINE__, parentShape, coords, shape))
     {
         return nullptr;
     }
     return std::make_unique<NeonSubTensorHandle>(
         PolymorphicDowncast<IAclTensorHandle*>(&parent), shape, coords);
 }
CreateSubtraction()
std::unique_ptr< armnn::IWorkload > CreateSubtraction (const SubtractionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 617 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonSubtractionWorkload>(descriptor, info);
 }
CreateTensorHandle() [1/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 111 of file NeonWorkloadFactory.cpp.
Referenced by NeonWorkloadFactory::SupportsSubTensors(), and TEST_SUITE().
 {
     auto tensorHandle = std::make_unique<NeonTensorHandle>(tensorInfo);
     if (IsMemoryManaged)
     {
         tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     }
     return tensorHandle;
 }
CreateTensorHandle() [2/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 122 of file NeonWorkloadFactory.cpp.
 {
     auto tensorHandle = std::make_unique<NeonTensorHandle>(tensorInfo, dataLayout);
     if (IsMemoryManaged)
     {
         tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     }
     return tensorHandle;
 }
CreateTranspose()
std::unique_ptr< armnn::IWorkload > CreateTranspose (const TransposeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 623 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonTransposeWorkload>(descriptor, info);
 }
CreateTransposeConvolution2d()
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 629 of file NeonWorkloadFactory.cpp.
References armnn::info.
Referenced by NeonWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<NeonTransposeConvolution2dWorkload>(descriptor, info,
                                                                 m_MemoryManager->GetIntraLayerManager());
 }
GetBackendId()
const BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 49 of file NeonWorkloadFactory.cpp.
References NeonBackendModelContext::GetNumberOfThreads().
 {
     return s_Id;
 }
IsLayerSupported() [1/2]
bool IsLayerSupported (const Layer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 34 of file NeonWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported);
 }
IsLayerSupported() [2/2]
bool IsLayerSupported (const IConnectableLayer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported, const ModelOptions & modelOptions) static
Definition at line 41 of file NeonWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported, modelOptions);
 }
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 39 of file NeonWorkloadFactory.hpp.
References ARMNN_DEPRECATED_MSG, NeonWorkloadFactory::CreateAbs(), NeonWorkloadFactory::CreateActivation(), NeonWorkloadFactory::CreateAddition(), NeonWorkloadFactory::CreateArgMinMax(), NeonWorkloadFactory::CreateBatchNormalization(), NeonWorkloadFactory::CreateBatchToSpaceNd(), NeonWorkloadFactory::CreateCast(), NeonWorkloadFactory::CreateComparison(), NeonWorkloadFactory::CreateConcat(), NeonWorkloadFactory::CreateConstant(), NeonWorkloadFactory::CreateConvertBf16ToFp32(), NeonWorkloadFactory::CreateConvertFp16ToFp32(), NeonWorkloadFactory::CreateConvertFp32ToBf16(), NeonWorkloadFactory::CreateConvertFp32ToFp16(), NeonWorkloadFactory::CreateConvolution2d(), NeonWorkloadFactory::CreateDebug(), NeonWorkloadFactory::CreateDepthToSpace(), NeonWorkloadFactory::CreateDepthwiseConvolution2d(), NeonWorkloadFactory::CreateDequantize(), NeonWorkloadFactory::CreateDetectionPostProcess(), NeonWorkloadFactory::CreateDivision(), NeonWorkloadFactory::CreateElementwiseUnary(), NeonWorkloadFactory::CreateEqual(), NeonWorkloadFactory::CreateFill(), NeonWorkloadFactory::CreateFloor(), NeonWorkloadFactory::CreateFullyConnected(), NeonWorkloadFactory::CreateGather(), NeonWorkloadFactory::CreateGreater(), NeonWorkloadFactory::CreateInput(), NeonWorkloadFactory::CreateInstanceNormalization(), NeonWorkloadFactory::CreateL2Normalization(), NeonWorkloadFactory::CreateLogicalBinary(), NeonWorkloadFactory::CreateLogSoftmax(), NeonWorkloadFactory::CreateLstm(), NeonWorkloadFactory::CreateMaximum(), NeonWorkloadFactory::CreateMean(), NeonWorkloadFactory::CreateMemCopy(), NeonWorkloadFactory::CreateMemImport(), NeonWorkloadFactory::CreateMerger(), NeonWorkloadFactory::CreateMinimum(), NeonWorkloadFactory::CreateMultiplication(), NeonWorkloadFactory::CreateNormalization(), NeonWorkloadFactory::CreateOutput(), NeonWorkloadFactory::CreatePad(), NeonWorkloadFactory::CreatePermute(), NeonWorkloadFactory::CreatePooling2d(), NeonWorkloadFactory::CreatePreCompiled(), NeonWorkloadFactory::CreatePrelu(), NeonWorkloadFactory::CreateQLstm(), NeonWorkloadFactory::CreateQuantize(), NeonWorkloadFactory::CreateQuantizedLstm(), NeonWorkloadFactory::CreateRank(), NeonWorkloadFactory::CreateReduce(), NeonWorkloadFactory::CreateReshape(), NeonWorkloadFactory::CreateResize(), NeonWorkloadFactory::CreateResizeBilinear(), NeonWorkloadFactory::CreateRsqrt(), NeonWorkloadFactory::CreateSlice(), NeonWorkloadFactory::CreateSoftmax(), NeonWorkloadFactory::CreateSpaceToBatchNd(), NeonWorkloadFactory::CreateSpaceToDepth(), NeonWorkloadFactory::CreateSplitter(), NeonWorkloadFactory::CreateStack(), NeonWorkloadFactory::CreateStridedSlice(), NeonWorkloadFactory::CreateSubTensorHandle(), NeonWorkloadFactory::CreateSubtraction(), NeonWorkloadFactory::CreateTensorHandle(), NeonWorkloadFactory::CreateTranspose(), NeonWorkloadFactory::CreateTransposeConvolution2d(), armnn::Info, and armnn::info.
 { return true; }
The documentation for this class was generated from the following files:
src/backends/neon/NeonWorkloadFactory.hpp
src/backends/neon/NeonWorkloadFactory.cpp