ArmNN: BFloat16Decoder Class Reference
BFloat16Decoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
BFloat16Decoder (const BFloat16 *data)
BFloat16Decoder ()
float Get () const override
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const bool isDepthwise) override
Public Member Functions inherited from TypedIterator< const BFloat16, Decoder< float > >
TypedIterator (const BFloat16 *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< const BFloat16, Decoder< float > >
const BFloat16 * m_Iterator
const BFloat16 * m_Start
Detailed Description
Definition at line 263 of file BaseIterator.hpp.
Constructor & Destructor Documentation
BFloat16Decoder() [1/2]
BFloat16Decoder (const BFloat16 * data) inline
Definition at line 266 of file BaseIterator.hpp.
         : TypedIterator(data) {}
BFloat16Decoder() [2/2]
BFloat16Decoder () inline
Definition at line 269 of file BaseIterator.hpp.
         : BFloat16Decoder(nullptr) {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, const bool isDepthwise) inline override virtual
Implements Decoder< float >.
Definition at line 278 of file BaseIterator.hpp.
References FloatingPointConverter::ConvertBFloat16ToFloat32(), TensorShape::GetNumElements(), armnn::IgnoreUnused(), and BaseIterator::operator[]().
     {
         IgnoreUnused(isDepthwise);
         const unsigned int size = tensorShape.GetNumElements();
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         for (uint32_t i = 0; i < size; ++i)
         {
             this->operator[](i);
             float val = 0.f;
             armnnUtils::FloatingPointConverter::ConvertBFloat16ToFloat32(m_Iterator, 1, &val);
             decodedTensor.emplace_back(val);
         }
         return decodedTensor;
     }
Get()
float Get () const inline override virtual
Implements Decoder< float >.
Definition at line 272 of file BaseIterator.hpp.
References FloatingPointConverter::ConvertBFloat16ToFloat32().
     {
         float val = 0.f;
         armnnUtils::FloatingPointConverter::ConvertBFloat16ToFloat32(m_Iterator, 1, &val);
         return val;
     }
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp