ArmNN: ICounterMappings Class Reference
ICounterMappings Class Reference abstract
#include <CounterIdMap.hpp>
Public Member Functions
virtual uint16_t GetGlobalId (uint16_t backendCounterId, const armnn::BackendId &backendId) const =0
virtual const std::pair< uint16_t, armnn::BackendId > & GetBackendId (uint16_t globalCounterId) const =0
virtual ~ICounterMappings ()
Detailed Description
Definition at line 15 of file CounterIdMap.hpp.
Constructor & Destructor Documentation
~ICounterMappings()
virtual ~ICounterMappings () inline virtual
Definition at line 20 of file CounterIdMap.hpp.
 {}
Member Function Documentation
GetBackendId()
virtual const std::pair<uint16_t, armnn::BackendId>& GetBackendId (uint16_t globalCounterId) const pure virtual
Implemented in CounterIdMap.
Referenced by BackendProfiling::GetActiveCounters(), PeriodicCounterSelectionCommandHandler::operator()(), and CounterIdMap::~CounterIdMap().
GetGlobalId()
virtual uint16_t GetGlobalId (uint16_t backendCounterId, const armnn::BackendId & backendId) const pure virtual
Implemented in CounterIdMap.
Referenced by BackendProfiling::GetCounterStatus(), BackendProfiling::ReportCounters(), PeriodicCounterCapture::Stop(), TEST_SUITE(), and CounterIdMap::~CounterIdMap().
The documentation for this class was generated from the following file:
src/profiling/CounterIdMap.hpp