ArmNN: NeonLogSoftmaxWorkload Class Reference
NeonLogSoftmaxWorkload Class Reference
#include <NeonLogSoftmaxWorkload.hpp>
Public Member Functions
NeonLogSoftmaxWorkload (const LogSoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager)
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< LogSoftmaxQueueDescriptor >
BaseWorkload (const LogSoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const LogSoftmaxQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< LogSoftmaxQueueDescriptor >
LogSoftmaxQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 24 of file NeonLogSoftmaxWorkload.hpp.
Constructor & Destructor Documentation
NeonLogSoftmaxWorkload()
NeonLogSoftmaxWorkload (const LogSoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager)
Definition at line 33 of file NeonLogSoftmaxWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, armnn::ComputeAclAxis(), SoftmaxDescriptor::m_Axis, SoftmaxDescriptor::m_Beta, BaseWorkload< LogSoftmaxQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, WorkloadInfo::m_InputTensorInfos, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and QueueDescriptor::ValidateInputsOutputs().
     : BaseWorkload<LogSoftmaxQueueDescriptor>(descriptor, info)
 {
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonLogSoftmaxWorkload_Construct",
                                          descriptor.m_Parameters,
                                          info,
                                          this->GetGuid());
     m_Data.ValidateInputsOutputs("NeonLogSoftmaxWorkload", 1, 1);
     arm_compute::ITensor& input = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     auto layer = std::make_unique<arm_compute::NELogSoftmaxLayer>(memoryManager);
     int aclAxis = ComputeAclAxis(m_Data.m_Parameters.m_Axis, info.m_InputTensorInfos[0]);
     layer->configure(&input, &output, m_Data.m_Parameters.m_Beta, aclAxis);
     m_LogSoftmaxLayer.reset(layer.release());
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 55 of file NeonLogSoftmaxWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID, and BaseWorkload< LogSoftmaxQueueDescriptor >::GetGuid().
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID("NeonLogSoftmaxWorkload_Execute", this->GetGuid());
     m_LogSoftmaxLayer->run();
 }
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonLogSoftmaxWorkload.hpp
src/backends/neon/workloads/NeonLogSoftmaxWorkload.cpp