ArmNN: RefWorkloadFactory Class Reference
RefWorkloadFactory Class Reference
#include <RefWorkloadFactory.hpp>
Public Member Functions
RefWorkloadFactory (const std::shared_ptr< RefMemoryManager > &memoryManager)
RefWorkloadFactory ()
~RefWorkloadFactory ()
const BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateCast (const CastQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFill (const FillQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLogicalBinary (const LogicalBinaryQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor &descriptor, const WorkloadInfo &Info) const override
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMerger (const MergerQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateRank (const RankQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateReduce (const ReduceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateShape (const ShapeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateUnidirectionalSequenceLstm (const UnidirectionalSequenceLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual void AfterWorkloadsCreated ()
virtual std::unique_ptr< IWorkload > CreateLogicalUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateMerge (const MergeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSwitch (const SwitchQueueDescriptor &descriptor, const WorkloadInfo &Info) const
Static Public Member Functions
static bool IsLayerSupported (const Layer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 30 of file RefWorkloadFactory.hpp.
Constructor & Destructor Documentation
RefWorkloadFactory() [1/2]
RefWorkloadFactory (const std::shared_ptr< RefMemoryManager > & memoryManager) explicit
Definition at line 83 of file RefWorkloadFactory.cpp.
     : m_MemoryManager(memoryManager)
 {
 }
RefWorkloadFactory() [2/2]
RefWorkloadFactory ()
Definition at line 88 of file RefWorkloadFactory.cpp.
     : m_MemoryManager(new RefMemoryManager())
 {
 }
~RefWorkloadFactory()
~RefWorkloadFactory () inline
Definition at line 36 of file RefWorkloadFactory.hpp.
References RefWorkloadFactory::GetBackendId(), and RefWorkloadFactory::IsLayerSupported().
 {}
Member Function Documentation
CreateAbs()
std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 132 of file RefWorkloadFactory.cpp.
References armnn::Abs, RefWorkloadFactory::CreateElementwiseUnary(), armnn::IgnoreUnused(), ElementwiseUnaryDescriptor::m_Operation, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     IgnoreUnused(descriptor);
     ElementwiseUnaryQueueDescriptor elementwiseUnaryDescriptor;
     elementwiseUnaryDescriptor.m_Parameters.m_Operation = UnaryOperation::Abs;
     return CreateElementwiseUnary(elementwiseUnaryDescriptor, info);
 }
CreateActivation()
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 142 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefActivationWorkload>(descriptor, info);
 }
CreateAddition()
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 148 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and armnn::Signed32.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos[0].GetDataType() == armnn::DataType::Signed32)
     {
         return std::make_unique<RefAdditionWorkload<int32_t>>(descriptor, info);
     }
     else
     {
         return std::make_unique<RefAdditionWorkload<float>>(descriptor, info);
     }
 }
CreateArgMinMax()
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 161 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefArgMinMaxWorkload>(descriptor, info);
 }
CreateBatchNormalization()
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 167 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefBatchNormalizationWorkload>(descriptor, info);
 }
CreateBatchToSpaceNd()
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 174 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefBatchToSpaceNdWorkload>(descriptor, info);
 }
CreateCast()
std::unique_ptr< IWorkload > CreateCast (const CastQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 180 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefCastWorkload>(descriptor, info);
 }
CreateComparison()
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 186 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateEqual(), RefWorkloadFactory::CreateGreater(), and RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefComparisonWorkload>(descriptor, info);
 }
CreateConcat()
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 192 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateMerger(), and RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConcatWorkload>(descriptor, info);
 }
CreateConstant()
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 198 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConstantWorkload>(descriptor, info);
 }
CreateConvertBf16ToFp32()
std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 204 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConvertBf16ToFp32Workload>(descriptor, info);
 }
CreateConvertFp16ToFp32()
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 211 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConvertFp16ToFp32Workload>(descriptor, info);
 }
CreateConvertFp32ToBf16()
std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 218 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConvertFp32ToBf16Workload>(descriptor, info);
 }
CreateConvertFp32ToFp16()
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 225 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConvertFp32ToFp16Workload>(descriptor, info);
 }
CreateConvolution2d()
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 232 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefConvolution2dWorkload>(descriptor, info);
 }
CreateDebug()
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 238 of file RefWorkloadFactory.cpp.
References armnn::info, armnn::IsBFloat16(), armnn::IsFloat16(), armnn::IsQAsymmS8(), armnn::IsQAsymmU8(), armnn::IsQSymmS16(), armnn::IsQSymmS8(), and armnn::IsSigned32().
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (IsBFloat16(info))
     {
         return std::make_unique<RefDebugBFloat16Workload>(descriptor, info);
     }
     if (IsFloat16(info))
     {
         return std::make_unique<RefDebugFloat16Workload>(descriptor, info);
     }
     if (IsQSymmS16(info))
     {
         return std::make_unique<RefDebugQSymmS16Workload>(descriptor, info);
     }
     if (IsQSymmS8(info))
     {
         return std::make_unique<RefDebugQSymmS8Workload>(descriptor, info);
     }
     if (IsQAsymmU8(info))
     {
         return std::make_unique<RefDebugQAsymmU8Workload>(descriptor, info);
     }
     if (IsQAsymmS8(info))
     {
         return std::make_unique<RefDebugQAsymmS8Workload>(descriptor, info);
     }
     if (IsSigned32(info))
     {
         return std::make_unique<RefDebugSigned32Workload>(descriptor, info);
     }
     return MakeWorkload<RefDebugFloat32Workload, RefDebugQAsymmU8Workload>(descriptor, info);
 }
CreateDepthToSpace()
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 273 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefDepthToSpaceWorkload>(descriptor, info);
 }
CreateDepthwiseConvolution2d()
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 279 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefDepthwiseConvolution2dWorkload>(descriptor, info);
 }
CreateDequantize()
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 286 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefDequantizeWorkload>(descriptor, info);
 }
CreateDetectionPostProcess()
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 292 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefDetectionPostProcessWorkload>(descriptor, info);
 }
CreateDivision()
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 299 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and armnn::Signed32.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos[0].GetDataType() == armnn::DataType::Signed32)
     {
         return std::make_unique<RefDivisionWorkload<int32_t>>(descriptor, info);
     }
     else
     {
         return std::make_unique<RefDivisionWorkload<float>>(descriptor, info);
     }
 }
CreateElementwiseUnary()
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 312 of file RefWorkloadFactory.cpp.
References armnn::info, armnn::LogicalNot, ElementwiseUnaryDescriptor::m_Operation, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by RefWorkloadFactory::CreateAbs(), RefWorkloadFactory::CreateRsqrt(), and RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (descriptor.m_Parameters.m_Operation == UnaryOperation::LogicalNot)
     {
         return std::make_unique<RefLogicalUnaryWorkload>(descriptor, info);
     }
     return std::make_unique<RefElementwiseUnaryWorkload>(descriptor, info);
 }
CreateEqual()
std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 322 of file RefWorkloadFactory.cpp.
References RefWorkloadFactory::CreateComparison(), armnn::Equal, armnn::IgnoreUnused(), ComparisonDescriptor::m_Operation, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     IgnoreUnused(descriptor);
     ComparisonQueueDescriptor comparisonDescriptor;
     comparisonDescriptor.m_Parameters.m_Operation = ComparisonOperation::Equal;
     return CreateComparison(comparisonDescriptor, info);
 }
CreateFakeQuantization()
std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 332 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return MakeWorkload<RefFakeQuantizationFloat32Workload, NullWorkload>(descriptor, info);
 }
CreateFill()
std::unique_ptr< IWorkload > CreateFill (const FillQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 338 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefFillWorkload>(descriptor, info);
 }
CreateFloor()
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 344 of file RefWorkloadFactory.cpp.
References armnn::info, armnn::IsQuantizedType(), and WorkloadInfo::m_InputTensorInfos.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if(IsQuantizedType(info.m_InputTensorInfos[0].GetDataType()))
     {
         return nullptr;
     }
     else
     {
         return std::make_unique<RefFloorWorkload>(descriptor, info);
     }
 }
CreateFullyConnected()
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 357 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefFullyConnectedWorkload>(descriptor, info);
 }
CreateGather()
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 364 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefGatherWorkload>(descriptor, info);
 }
CreateGreater()
std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 370 of file RefWorkloadFactory.cpp.
References RefWorkloadFactory::CreateComparison(), armnn::Greater, armnn::IgnoreUnused(), ComparisonDescriptor::m_Operation, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     IgnoreUnused(descriptor);
     ComparisonQueueDescriptor comparisonDescriptor;
     comparisonDescriptor.m_Parameters.m_Operation = ComparisonOperation::Greater;
     return CreateComparison(comparisonDescriptor, info);
 }
CreateInput()
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Implements IWorkloadFactory.
Definition at line 380 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and WorkloadInfo::m_OutputTensorInfos.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos.empty() )
     {
         throw InvalidArgumentException("RefWorkloadFactory::CreateInput: Input cannot be zero length");
     }
     if (info.m_OutputTensorInfos.empty())
     {
         throw InvalidArgumentException("RefWorkloadFactory::CreateInput: Output cannot be zero length");
     }
     if (info.m_InputTensorInfos[0].GetNumBytes() != info.m_OutputTensorInfos[0].GetNumBytes())
     {
         throw InvalidArgumentException("RefWorkloadFactory::CreateInput: data input and output differ in byte count.");
     }
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreateInstanceNormalization()
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 400 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefInstanceNormalizationWorkload>(descriptor, info);
 }
CreateL2Normalization()
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 407 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefL2NormalizationWorkload>(descriptor, info);
 }
CreateLogicalBinary()
std::unique_ptr< IWorkload > CreateLogicalBinary (const LogicalBinaryQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 413 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefLogicalBinaryWorkload>(descriptor, info);
 }
CreateLogSoftmax()
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 419 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefLogSoftmaxWorkload>(descriptor, info);
 }
CreateLstm()
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 425 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefLstmWorkload>(descriptor, info);
 }
CreateMaximum()
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 431 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and armnn::Signed32.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos[0].GetDataType() == armnn::DataType::Signed32)
     {
         return std::make_unique<RefMaximumWorkload<int32_t>>(descriptor, info);
     }
     else
     {
         return std::make_unique<RefMaximumWorkload<float>>(descriptor, info);
     }
 }
CreateMean()
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor & descriptor, const WorkloadInfo & Info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 444 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return  std::make_unique<RefMeanWorkload>(descriptor, info);
 }
CreateMemCopy()
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 450 of file RefWorkloadFactory.cpp.
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (descriptor.m_Inputs.empty())
     {
         throw InvalidArgumentException("RefWorkloadFactory: CreateMemCopy() expected an input tensor.");
     }
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreateMemImport()
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 460 of file RefWorkloadFactory.cpp.
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (descriptor.m_Inputs.empty())
     {
         throw InvalidArgumentException("RefWorkloadFactory: CreateMemImport() expected an input tensor.");
     }
     return std::make_unique<ImportMemGenericWorkload>(descriptor, info);
 }
CreateMerger()
std::unique_ptr< IWorkload > CreateMerger (const MergerQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 470 of file RefWorkloadFactory.cpp.
References RefWorkloadFactory::CreateConcat().
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return CreateConcat(descriptor, info);
 }
CreateMinimum()
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 476 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and armnn::Signed32.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos[0].GetDataType() == armnn::DataType::Signed32)
     {
         return std::make_unique<RefMinimumWorkload<int32_t>>(descriptor, info);
     }
     else
     {
         return std::make_unique<RefMinimumWorkload<float>>(descriptor, info);
     }
 }
CreateMultiplication()
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 489 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and armnn::Signed32.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos[0].GetDataType() == armnn::DataType::Signed32)
     {
         return std::make_unique<RefMultiplicationWorkload<int32_t>>(descriptor, info);
     }
     else
     {
         return std::make_unique<RefMultiplicationWorkload<float>>(descriptor, info);
     }
 }
CreateNormalization()
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 502 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefNormalizationWorkload>(descriptor, info);
 }
CreateOutput()
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 508 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and WorkloadInfo::m_OutputTensorInfos.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos.empty() )
     {
         throw InvalidArgumentException("RefWorkloadFactory::CreateOutput: Input cannot be zero length");
     }
     if (info.m_OutputTensorInfos.empty())
     {
         throw InvalidArgumentException("RefWorkloadFactory::CreateOutput: Output cannot be zero length");
     }
     if (info.m_InputTensorInfos[0].GetNumBytes() != info.m_OutputTensorInfos[0].GetNumBytes())
     {
         throw InvalidArgumentException("RefWorkloadFactory::CreateOutput: data input and output differ in byte count.");
     }
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreatePad()
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 527 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefPadWorkload>(descriptor, info);
 }
CreatePermute()
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 533 of file RefWorkloadFactory.cpp.
References armnn::info, armnn::IsBFloat16(), armnn::IsQAsymmS8(), and armnn::IsQSymmS16().
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (IsQSymmS16(info))
     {
         return std::make_unique<RefPermuteQSymm16Workload>(descriptor, info);
     }
     else if (IsBFloat16(info))
     {
         return std::make_unique<RefPermuteBFloat16Workload>(descriptor, info);
     }
     else if (IsQAsymmS8(info))
     {
         return std::make_unique<RefPermuteQAsymmS8Workload>(descriptor, info);
     }
     return MakeWorkloadHelper<RefPermuteFloat16Workload, RefPermuteFloat32Workload, RefPermuteQAsymm8Workload,
         NullWorkload, NullWorkload, NullWorkload>(descriptor, info);
 }
CreatePooling2d()
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 552 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefPooling2dWorkload>(descriptor, info);
 }
CreatePreCompiled()
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 558 of file RefWorkloadFactory.cpp.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return nullptr;
 }
CreatePrelu()
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 564 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefPreluWorkload>(descriptor, info);
 }
CreateQLstm()
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 570 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefQLstmWorkload>(descriptor, info);
 }
CreateQuantize()
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 576 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefQuantizeWorkload>(descriptor, info);
 }
CreateRank()
std::unique_ptr< IWorkload > CreateRank (const RankQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 582 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefRankWorkload>(descriptor, info);
 }
CreateReduce()
std::unique_ptr< IWorkload > CreateReduce (const ReduceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 588 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefReduceWorkload>(descriptor, info);
 }
CreateReshape()
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 594 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefReshapeWorkload>(descriptor, info);
 }
CreateResize()
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 600 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateResizeBilinear(), and RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefResizeWorkload>(descriptor, info);
 }
CreateResizeBilinear()
std::unique_ptr< IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 606 of file RefWorkloadFactory.cpp.
References armnn::Bilinear, RefWorkloadFactory::CreateResize(), ResizeBilinearDescriptor::m_DataLayout, ResizeDescriptor::m_DataLayout, ResizeDescriptor::m_Method, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, ResizeBilinearDescriptor::m_TargetHeight, ResizeDescriptor::m_TargetHeight, ResizeBilinearDescriptor::m_TargetWidth, and ResizeDescriptor::m_TargetWidth.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     ResizeQueueDescriptor resizeDescriptor;
     resizeDescriptor.m_Parameters.m_Method       = ResizeMethod::Bilinear;
     resizeDescriptor.m_Parameters.m_DataLayout   = descriptor.m_Parameters.m_DataLayout;
     resizeDescriptor.m_Parameters.m_TargetWidth  = descriptor.m_Parameters.m_TargetWidth;
     resizeDescriptor.m_Parameters.m_TargetHeight = descriptor.m_Parameters.m_TargetHeight;
     return CreateResize(resizeDescriptor, info);
 }
CreateRsqrt()
std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 618 of file RefWorkloadFactory.cpp.
References RefWorkloadFactory::CreateElementwiseUnary(), armnn::IgnoreUnused(), ElementwiseUnaryDescriptor::m_Operation, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::Rsqrt.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     IgnoreUnused(descriptor);
     ElementwiseUnaryQueueDescriptor elementwiseUnaryDescriptor;
     elementwiseUnaryDescriptor.m_Parameters.m_Operation = UnaryOperation::Rsqrt;
     return CreateElementwiseUnary(elementwiseUnaryDescriptor, info);
 }
CreateShape()
std::unique_ptr< IWorkload > CreateShape (const ShapeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 628 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefShapeWorkload>(descriptor, info);
 }
CreateSlice()
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 634 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefSliceWorkload>(descriptor, info);
 }
CreateSoftmax()
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 640 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefSoftmaxWorkload>(descriptor, info);
 }
CreateSpaceToBatchNd()
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 646 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefSpaceToBatchNdWorkload>(descriptor, info);
 }
CreateSpaceToDepth()
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 652 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefSpaceToDepthWorkload>(descriptor, info);
 }
CreateSplitter()
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 658 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefSplitterWorkload>(descriptor, info);
 }
CreateStack()
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 664 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefStackWorkload>(descriptor, info);
 }
CreateStridedSlice()
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 670 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefStridedSliceWorkload>(descriptor, info);
 }
CreateSubTensorHandle()
std::unique_ptr<ITensorHandle> CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const inline override virtual
Implements IWorkloadFactory.
Definition at line 52 of file RefWorkloadFactory.hpp.
References ARMNN_DEPRECATED_MSG, RefWorkloadFactory::CreateAbs(), RefWorkloadFactory::CreateActivation(), RefWorkloadFactory::CreateAddition(), RefWorkloadFactory::CreateArgMinMax(), RefWorkloadFactory::CreateBatchNormalization(), RefWorkloadFactory::CreateBatchToSpaceNd(), RefWorkloadFactory::CreateCast(), RefWorkloadFactory::CreateComparison(), RefWorkloadFactory::CreateConcat(), RefWorkloadFactory::CreateConstant(), RefWorkloadFactory::CreateConvertBf16ToFp32(), RefWorkloadFactory::CreateConvertFp16ToFp32(), RefWorkloadFactory::CreateConvertFp32ToBf16(), RefWorkloadFactory::CreateConvertFp32ToFp16(), RefWorkloadFactory::CreateConvolution2d(), RefWorkloadFactory::CreateDebug(), RefWorkloadFactory::CreateDepthToSpace(), RefWorkloadFactory::CreateDepthwiseConvolution2d(), RefWorkloadFactory::CreateDequantize(), RefWorkloadFactory::CreateDetectionPostProcess(), RefWorkloadFactory::CreateDivision(), RefWorkloadFactory::CreateElementwiseUnary(), RefWorkloadFactory::CreateEqual(), RefWorkloadFactory::CreateFakeQuantization(), RefWorkloadFactory::CreateFill(), RefWorkloadFactory::CreateFloor(), RefWorkloadFactory::CreateFullyConnected(), RefWorkloadFactory::CreateGather(), RefWorkloadFactory::CreateGreater(), RefWorkloadFactory::CreateInput(), RefWorkloadFactory::CreateInstanceNormalization(), RefWorkloadFactory::CreateL2Normalization(), RefWorkloadFactory::CreateLogicalBinary(), RefWorkloadFactory::CreateLogSoftmax(), RefWorkloadFactory::CreateLstm(), RefWorkloadFactory::CreateMaximum(), RefWorkloadFactory::CreateMean(), RefWorkloadFactory::CreateMemCopy(), RefWorkloadFactory::CreateMemImport(), RefWorkloadFactory::CreateMerger(), RefWorkloadFactory::CreateMinimum(), RefWorkloadFactory::CreateMultiplication(), RefWorkloadFactory::CreateNormalization(), RefWorkloadFactory::CreateOutput(), RefWorkloadFactory::CreatePad(), RefWorkloadFactory::CreatePermute(), RefWorkloadFactory::CreatePooling2d(), RefWorkloadFactory::CreatePreCompiled(), RefWorkloadFactory::CreatePrelu(), RefWorkloadFactory::CreateQLstm(), RefWorkloadFactory::CreateQuantize(), RefWorkloadFactory::CreateRank(), RefWorkloadFactory::CreateReduce(), RefWorkloadFactory::CreateReshape(), RefWorkloadFactory::CreateResize(), RefWorkloadFactory::CreateResizeBilinear(), RefWorkloadFactory::CreateRsqrt(), RefWorkloadFactory::CreateShape(), RefWorkloadFactory::CreateSlice(), RefWorkloadFactory::CreateSoftmax(), RefWorkloadFactory::CreateSpaceToBatchNd(), RefWorkloadFactory::CreateSpaceToDepth(), RefWorkloadFactory::CreateSplitter(), RefWorkloadFactory::CreateStack(), RefWorkloadFactory::CreateStridedSlice(), RefWorkloadFactory::CreateSubtraction(), RefWorkloadFactory::CreateTensorHandle(), RefWorkloadFactory::CreateTranspose(), RefWorkloadFactory::CreateTransposeConvolution2d(), RefWorkloadFactory::CreateUnidirectionalSequenceLstm(), armnn::IgnoreUnused(), armnn::Info, and armnn::info.
     {
         IgnoreUnused(parent, subTensorShape, subTensorOrigin);
         return nullptr;
     }
CreateSubtraction()
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 676 of file RefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and armnn::Signed32.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos[0].GetDataType() == armnn::DataType::Signed32)
     {
         return std::make_unique<RefSubtractionWorkload<int32_t>>(descriptor, info);
     }
     else
     {
         return std::make_unique<RefSubtractionWorkload<float>>(descriptor, info);
     }
 }
CreateTensorHandle() [1/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 113 of file RefWorkloadFactory.cpp.
References armnn::IgnoreUnused().
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     // For Ref it is okay to make the TensorHandle memory managed as it can also store a pointer
     // to unmanaged memory. This also ensures memory alignment.
     IgnoreUnused(isMemoryManaged);
     return std::make_unique<RefTensorHandle>(tensorInfo, m_MemoryManager);
 }
CreateTensorHandle() [2/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 122 of file RefWorkloadFactory.cpp.
References armnn::IgnoreUnused().
 {
     // For Ref it is okay to make the TensorHandle memory managed as it can also store a pointer
     // to unmanaged memory. This also ensures memory alignment.
     IgnoreUnused(isMemoryManaged, dataLayout);
     return std::make_unique<RefTensorHandle>(tensorInfo, m_MemoryManager);
 }
CreateTranspose()
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 689 of file RefWorkloadFactory.cpp.
References armnn::info, armnn::IsBFloat16(), armnn::IsQAsymmS8(), and armnn::IsQSymmS16().
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     if (IsQSymmS16(info))
     {
         return std::make_unique<RefTransposeQSymm16Workload>(descriptor, info);
     }
     else if (IsBFloat16(info))
     {
         return std::make_unique<RefTransposeBFloat16Workload>(descriptor, info);
     }
     else if (IsQAsymmS8(info))
     {
         return std::make_unique<RefTransposeQAsymmS8Workload>(descriptor, info);
     }
     return MakeWorkloadHelper<RefTransposeFloat16Workload, RefTransposeFloat32Workload, RefTransposeQAsymm8Workload,
             NullWorkload, NullWorkload, NullWorkload>(descriptor, info);
 }
CreateTransposeConvolution2d()
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 708 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefTransposeConvolution2dWorkload>(descriptor, info);
 }
CreateUnidirectionalSequenceLstm()
std::unique_ptr< IWorkload > CreateUnidirectionalSequenceLstm (const UnidirectionalSequenceLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 715 of file RefWorkloadFactory.cpp.
References armnn::info.
Referenced by RefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<RefUnidirectionalSequenceLstmWorkload>(descriptor, info);;
 }
GetBackendId()
const BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 93 of file RefWorkloadFactory.cpp.
Referenced by RefWorkloadFactory::~RefWorkloadFactory().
 {
     return s_Id;
 }
IsLayerSupported() [1/2]
bool IsLayerSupported (const Layer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 98 of file RefWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
Referenced by RefWorkloadFactory::~RefWorkloadFactory().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported);
 }
IsLayerSupported() [2/2]
bool IsLayerSupported (const IConnectableLayer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported, const ModelOptions & modelOptions) static
Definition at line 105 of file RefWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported, modelOptions);
 }
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Implements IWorkloadFactory.
Definition at line 49 of file RefWorkloadFactory.hpp.
References ARMNN_DEPRECATED_MSG.
 { return false; }
The documentation for this class was generated from the following files:
src/backends/reference/RefWorkloadFactory.hpp
src/backends/reference/RefWorkloadFactory.cpp