ArmNN: NeonArgMinMaxWorkload Class Reference
NeonArgMinMaxWorkload Class Reference
#include <NeonArgMinMaxWorkload.hpp>
Public Member Functions
NeonArgMinMaxWorkload (const ArgMinMaxQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< ArgMinMaxQueueDescriptor >
BaseWorkload (const ArgMinMaxQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const ArgMinMaxQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ArgMinMaxQueueDescriptor >
ArgMinMaxQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 20 of file NeonArgMinMaxWorkload.hpp.
Constructor & Destructor Documentation
NeonArgMinMaxWorkload()
NeonArgMinMaxWorkload (const ArgMinMaxQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 55 of file NeonArgMinMaxWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, armnnUtils::GetUnsignedAxis(), ArgMinMaxDescriptor::m_Axis, BaseWorkload< ArgMinMaxQueueDescriptor >::m_Data, ArgMinMaxDescriptor::m_Function, QueueDescriptor::m_Inputs, WorkloadInfo::m_InputTensorInfos, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::Max, and armnn::numeric_cast().
         : BaseWorkload<ArgMinMaxQueueDescriptor>(descriptor, info)
 {
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonArgMinMaxWorkload_Construct",
                                          descriptor.m_Parameters,
                                          info,
                                          this->GetGuid());
     arm_compute::ITensor& input = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     auto numDims = info.m_InputTensorInfos[0].GetNumDimensions();
     auto unsignedAxis = armnnUtils::GetUnsignedAxis(numDims, m_Data.m_Parameters.m_Axis);
     int aclAxis = armnn::numeric_cast<int>(CalcAclAxis(numDims, unsignedAxis));
     auto layer = std::make_unique<arm_compute::NEArgMinMaxLayer>();
     if (m_Data.m_Parameters.m_Function == ArgMinMaxFunction::Max)
     {
         layer->configure(&input, aclAxis, &output, arm_compute::ReductionOperation::ARG_IDX_MAX);
     }
     else
     {
         layer->configure(&input, aclAxis, &output, arm_compute::ReductionOperation::ARG_IDX_MIN);
     }
     m_ArgMinMaxLayer.reset(layer.release());
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 86 of file NeonArgMinMaxWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID, and BaseWorkload< ArgMinMaxQueueDescriptor >::GetGuid().
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON_GUID("NeonArgMinMaxWorkload_Execute", this->GetGuid());
     m_ArgMinMaxLayer->run();
 }
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonArgMinMaxWorkload.hpp
src/backends/neon/workloads/NeonArgMinMaxWorkload.cpp