ArmNN: ClDepthwiseConvolutionWorkload Class Reference
ClDepthwiseConvolutionWorkload Class Reference
#include <ClDepthwiseConvolutionWorkload.hpp>
Public Member Functions
ClDepthwiseConvolutionWorkload (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
void Execute () const override
Public Member Functions inherited from BaseWorkload< DepthwiseConvolution2dQueueDescriptor >
BaseWorkload (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const DepthwiseConvolution2dQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Protected Member Functions
void FreeUnusedTensors ()
Protected Attributes
std::unique_ptr< arm_compute::IFunction > m_DepthwiseConvolutionLayer
std::unique_ptr< arm_compute::CLTensor > m_KernelTensor
std::unique_ptr< arm_compute::CLTensor > m_BiasTensor
Protected Attributes inherited from BaseWorkload< DepthwiseConvolution2dQueueDescriptor >
DepthwiseConvolution2dQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 24 of file ClDepthwiseConvolutionWorkload.hpp.
Constructor & Destructor Documentation
ClDepthwiseConvolutionWorkload()
ClDepthwiseConvolutionWorkload (const DepthwiseConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 75 of file ClDepthwiseConvolutionWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, armnn::Convert1HWOTensorToAcl(), TensorInfo::GetNumBytes(), ConstTensorHandle::GetTensorInfo(), DepthwiseConvolution2dQueueDescriptor::m_Bias, DepthwiseConvolution2dDescriptor::m_BiasEnabled, WorkloadInfo::m_BiasTensorInfo, BaseWorkload< DepthwiseConvolution2dQueueDescriptor >::m_Data, DepthwiseConvolution2dDescriptor::m_DataLayout, WorkloadInfo::m_InputTensorInfos, ClDepthwiseConvolutionWorkload::m_KernelTensor, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, DepthwiseConvolution2dQueueDescriptor::m_Weight, and WorkloadInfo::m_WeightsTensorInfo.
     : BaseWorkload<DepthwiseConvolution2dQueueDescriptor>(descriptor, info)
 {
     // Add details for profiling output
     WorkloadInfo detailsInfo;
     detailsInfo.m_InputTensorInfos = info.m_InputTensorInfos;
     detailsInfo.m_OutputTensorInfos = info.m_OutputTensorInfos;
     detailsInfo.m_WeightsTensorInfo = armnn::Optional<armnn::TensorInfo>(descriptor.m_Weight->GetTensorInfo());
     if (descriptor.m_Parameters.m_BiasEnabled)
     {
         detailsInfo.m_BiasTensorInfo = armnn::Optional<armnn::TensorInfo>(descriptor.m_Bias->GetTensorInfo());
     }
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("ClDepthwiseConvolutionWorkload_Construct",
                                          descriptor.m_Parameters,
                                          detailsInfo,
                                          this->GetGuid());
     // ArmNN's weight format is usually [ M, I, H, W ] but for depthwise its [ 1, H, W, I*M]
     // Permute to [ 1, I * M, H, W ] (if NCHW), as required by the compute library
     ConstTensor weightPermuted;
     unsigned int depthMultiplier;
     std::unique_ptr<unsigned char[]> permuteBuffer(new unsigned char[m_Data.m_Weight->GetTensorInfo().GetNumBytes()]);
     std::tie(weightPermuted, depthMultiplier) = Convert1HWOTensorToAcl(m_Data.m_Weight,
                                                                        info.m_InputTensorInfos[0],
                                                                        m_Data.m_Parameters.m_DataLayout,
                                                                        permuteBuffer.get());
     // Convert the weights into the compute library format
     m_KernelTensor = std::make_unique<arm_compute::CLTensor>();
     BuildArmComputeTensor(*m_KernelTensor, weightPermuted.GetInfo(), m_Data.m_Parameters.m_DataLayout);
     if (m_Data.m_Parameters.m_BiasEnabled)
     {
         m_BiasTensor = std::make_unique<arm_compute::CLTensor>();
         BuildArmComputeTensor(*m_BiasTensor, m_Data.m_Bias->GetTensorInfo(), m_Data.m_Parameters.m_DataLayout);
     }
     const arm_compute::Size2D aclDilationInfo = BuildArmComputeSize2D(
                 m_Data.m_Parameters.m_DilationX,
                 m_Data.m_Parameters.m_DilationY);
     std::string name = std::string("ClDepthwiseConvolutionWorkload");
     m_Data.ValidateInputsOutputs(name, 1, 1);
     arm_compute::ICLTensor& input  = static_cast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = static_cast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
     input.info()->set_data_layout(aclDataLayout);
     output.info()->set_data_layout(aclDataLayout);
     arm_compute::PadStrideInfo padStrideInfo = BuildArmComputePadStrideInfo(m_Data.m_Parameters);
     const arm_compute::ActivationLayerInfo activationInfo = ConvertAdditionalInfoToAclActivationLayerInfo(descriptor);
     m_DepthwiseConvolutionLayer = std::make_unique<arm_compute::CLDepthwiseConvolutionLayer>();
     static_cast<arm_compute::CLDepthwiseConvolutionLayer*>(m_DepthwiseConvolutionLayer.get())->configure(
         clCompileContext,
         &input,
         m_KernelTensor.get(),
         m_BiasTensor.get(),
         &output,
         padStrideInfo,
         depthMultiplier,
         activationInfo,
         aclDilationInfo);
     ARMNN_ASSERT(m_DepthwiseConvolutionLayer);
     ScopedTensorHandle weightsPermutedHandle(weightPermuted);
     InitializeArmComputeClTensorData(*m_KernelTensor, &weightsPermutedHandle);
     if (m_BiasTensor)
     {
         InitializeArmComputeClTensorData(*m_BiasTensor, m_Data.m_Bias);
     }
     m_DepthwiseConvolutionLayer->prepare();
     FreeUnusedTensors();
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 169 of file ClDepthwiseConvolutionWorkload.cpp.
References ARMNN_ASSERT, ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< DepthwiseConvolution2dQueueDescriptor >::GetGuid(), ClDepthwiseConvolutionWorkload::m_DepthwiseConvolutionLayer, and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClDepthwiseConvolutionWorkload_Execute", this->GetGuid());
     ARMNN_ASSERT(m_DepthwiseConvolutionLayer);
     RunClFunction(*m_DepthwiseConvolutionLayer, CHECK_LOCATION());
 }
FreeUnusedTensors()
void FreeUnusedTensors () protected
Definition at line 163 of file ClDepthwiseConvolutionWorkload.cpp.
 {
     FreeTensorIfUnused(m_KernelTensor);
     FreeTensorIfUnused(m_BiasTensor);
 }
Member Data Documentation
m_BiasTensor
std::unique_ptr<arm_compute::CLTensor> m_BiasTensor protected
Definition at line 39 of file ClDepthwiseConvolutionWorkload.hpp.
m_DepthwiseConvolutionLayer
std::unique_ptr<arm_compute::IFunction> m_DepthwiseConvolutionLayer protected
Definition at line 36 of file ClDepthwiseConvolutionWorkload.hpp.
Referenced by ClDepthwiseConvolutionWorkload::Execute().
m_KernelTensor
std::unique_ptr<arm_compute::CLTensor> m_KernelTensor protected
Definition at line 38 of file ClDepthwiseConvolutionWorkload.hpp.
Referenced by ClDepthwiseConvolutionWorkload::ClDepthwiseConvolutionWorkload().
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClDepthwiseConvolutionWorkload.hpp
src/backends/cl/workloads/ClDepthwiseConvolutionWorkload.cpp