ArmNN: IWorkingMemHandle Class Reference
IWorkingMemHandle Class Reference abstract
#include <IWorkingMemHandle.hpp>
Public Member Functions
virtual ~IWorkingMemHandle ()
virtual NetworkId GetNetworkId ()=0
Returns the NetworkId of the Network that this IWorkingMemHandle works with.
virtual void Allocate ()=0
Allocate the backing memory required for execution.
virtual void Free ()=0
Free the backing memory required for execution. The mutex must be locked.
virtual bool IsAllocated ()=0
IsAllocated returns true if the backing memory is currently allocated. The mutex must be locked.
virtual std::mutex & GetMutex ()=0
Get a mutex which can be used for synchronizing access to the WorkingMemHandle object.
virtual WorkingMemDescriptor & GetWorkingMemDescriptor (LayerGuid id)=0
Get the WorkingMemDescriptor for a Layer. The mutex must be locked.
virtual WorkingMemDescriptor & GetWorkingMemDescriptorAt (unsigned int id)=0
Get the WorkingMemDescriptor at an index.
Detailed Description
Definition at line 20 of file IWorkingMemHandle.hpp.
Constructor & Destructor Documentation
~IWorkingMemHandle()
virtual ~IWorkingMemHandle () inline virtual
Definition at line 23 of file IWorkingMemHandle.hpp.
References IWorkingMemHandle::Allocate(), IWorkingMemHandle::Free(), IWorkingMemHandle::GetMutex(), IWorkingMemHandle::GetNetworkId(), IWorkingMemHandle::GetWorkingMemDescriptor(), IWorkingMemHandle::GetWorkingMemDescriptorAt(), and IWorkingMemHandle::IsAllocated().
 {};
Member Function Documentation
Allocate()
virtual void Allocate () pure virtual
Allocate the backing memory required for execution.
If this is not called, then allocation will be deferred to execution time. The mutex must be locked.
Implemented in WorkingMemHandle.
Referenced by IWorkingMemHandle::~IWorkingMemHandle().
Free()
virtual void Free () pure virtual
Free the backing memory required for execution. The mutex must be locked.
Implemented in WorkingMemHandle.
Referenced by IWorkingMemHandle::~IWorkingMemHandle().
GetMutex()
virtual std::mutex& GetMutex () pure virtual
Get a mutex which can be used for synchronizing access to the WorkingMemHandle object.
Implemented in WorkingMemHandle.
Referenced by IWorkingMemHandle::~IWorkingMemHandle().
GetNetworkId()
virtual NetworkId GetNetworkId () pure virtual
Returns the NetworkId of the Network that this IWorkingMemHandle works with.
Implemented in WorkingMemHandle.
Referenced by RuntimeImpl::Execute(), and IWorkingMemHandle::~IWorkingMemHandle().
GetWorkingMemDescriptor()
virtual WorkingMemDescriptor& GetWorkingMemDescriptor (LayerGuid id) pure virtual
Get the WorkingMemDescriptor for a Layer. The mutex must be locked.
Implemented in WorkingMemHandle.
Referenced by IWorkingMemHandle::~IWorkingMemHandle().
GetWorkingMemDescriptorAt()
virtual WorkingMemDescriptor& GetWorkingMemDescriptorAt (unsigned int id) pure virtual
Get the WorkingMemDescriptor at an index.
The WorkingMemDescriptors are stored in the same order as the Workloads in a topologically sorted graph. The mutex must be locked.
Implemented in WorkingMemHandle.
Referenced by IWorkingMemHandle::~IWorkingMemHandle().
IsAllocated()
virtual bool IsAllocated () pure virtual
IsAllocated returns true if the backing memory is currently allocated. The mutex must be locked.
Implemented in WorkingMemHandle.
Referenced by IWorkingMemHandle::~IWorkingMemHandle().
The documentation for this class was generated from the following file:
include/armnn/IWorkingMemHandle.hpp