ArmNN: CounterIdMap Class Reference
CounterIdMap Class Reference
#include <CounterIdMap.hpp>
Public Member Functions
CounterIdMap ()=default
virtual ~CounterIdMap ()
void RegisterMapping (uint16_t globalCounterId, uint16_t backendCounterId, const armnn::BackendId &backendId) override
void Reset () override
uint16_t GetGlobalId (uint16_t backendCounterId, const armnn::BackendId &backendId) const override
const std::pair< uint16_t, armnn::BackendId > & GetBackendId (uint16_t globalCounterId) const override
Public Member Functions inherited from ICounterMappings
virtual ~ICounterMappings ()
Public Member Functions inherited from IRegisterCounterMapping
virtual ~IRegisterCounterMapping ()
Detailed Description
Definition at line 33 of file CounterIdMap.hpp.
Constructor & Destructor Documentation
CounterIdMap()
CounterIdMap () default
~CounterIdMap()
virtual ~CounterIdMap () inline virtual
Definition at line 38 of file CounterIdMap.hpp.
References ICounterMappings::GetBackendId(), and ICounterMappings::GetGlobalId().
 {}
Member Function Documentation
GetBackendId()
const std::pair< uint16_t, armnn::BackendId > & GetBackendId (uint16_t globalCounterId) const override virtual
Implements ICounterMappings.
Definition at line 43 of file CounterIdMap.cpp.
 {
     auto it = m_GlobalCounterIdMap.find(globalCounterId);
     if (it == m_GlobalCounterIdMap.end())
     {
         std::stringstream ss;
         ss << "No Global Counter ID [" << globalCounterId << "] registered";
         throw armnn::Exception(ss.str());
     }
     return it->second;
 }
GetGlobalId()
uint16_t GetGlobalId (uint16_t backendCounterId, const armnn::BackendId & backendId) const override virtual
Implements ICounterMappings.
Definition at line 30 of file CounterIdMap.cpp.
 {
     std::pair<uint16_t, armnn::BackendId> backendIdPair(backendCounterId, backendId);
     auto it = m_BackendCounterIdMap.find(backendIdPair);
     if (it == m_BackendCounterIdMap.end())
     {
         std::stringstream ss;
         ss << "No Backend Counter [" << backendIdPair.second << ":" << backendIdPair.first << "] registered";
         throw armnn::Exception(ss.str());
     }
     return it->second;
 }
RegisterMapping()
void RegisterMapping (uint16_t globalCounterId, uint16_t backendCounterId, const armnn::BackendId & backendId) override virtual
Implements IRegisterCounterMapping.
Definition at line 15 of file CounterIdMap.cpp.
Referenced by TEST_SUITE().
 {
     std::pair<uint16_t, armnn::BackendId> backendIdPair(backendCounterId, backendId);
     m_GlobalCounterIdMap[globalCounterId] = backendIdPair;
     m_BackendCounterIdMap[backendIdPair] = globalCounterId;
 }
Reset()
void Reset () override virtual
Implements IRegisterCounterMapping.
Definition at line 24 of file CounterIdMap.cpp.
Referenced by ProfilingService::GetSendTimelinePacket().
 {
     m_GlobalCounterIdMap.clear();
     m_BackendCounterIdMap.clear();
 }
The documentation for this class was generated from the following files:
src/profiling/CounterIdMap.hpp
src/profiling/CounterIdMap.cpp