ArmNN: BatchToSpaceNdDescriptorBuilder Struct Reference
BatchToSpaceNdDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef BatchToSpaceNdDescriptor Table
Public Member Functions
void add_blockShape (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape)
void add_crops (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> crops)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
BatchToSpaceNdDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
BatchToSpaceNdDescriptorBuilder & operator= (const BatchToSpaceNdDescriptorBuilder &)
flatbuffers::Offset< BatchToSpaceNdDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5630 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef BatchToSpaceNdDescriptor Table
Definition at line 5631 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
BatchToSpaceNdDescriptorBuilder()
BatchToSpaceNdDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5643 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_blockShape()
void add_blockShape (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape) inline
Definition at line 5634 of file ArmnnSchema_generated.h.
References VT_BLOCKSHAPE.
Referenced by armnnSerializer::CreateBatchToSpaceNdDescriptor().
{
     fbb_.AddOffset(BatchToSpaceNdDescriptor::VT_BLOCKSHAPE, blockShape);
   }
add_crops()
void add_crops (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> crops) inline
Definition at line 5637 of file ArmnnSchema_generated.h.
References VT_CROPS.
Referenced by armnnSerializer::CreateBatchToSpaceNdDescriptor().
{
     fbb_.AddOffset(BatchToSpaceNdDescriptor::VT_CROPS, crops);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 5640 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateBatchToSpaceNdDescriptor().
{
     fbb_.AddElement<int8_t>(BatchToSpaceNdDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
Finish()
flatbuffers::Offset<BatchToSpaceNdDescriptor> Finish () inline
Definition at line 5648 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateBatchToSpaceNdDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<BatchToSpaceNdDescriptor>(end);
     return o;
   }
operator=()
BatchToSpaceNdDescriptorBuilder& operator= (const BatchToSpaceNdDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5632 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5633 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h