ArmNN: SliceDescriptorBuilder Struct Reference
SliceDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SliceDescriptor Table
Public Member Functions
void add_begin (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> begin)
void add_size (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> size)
SliceDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SliceDescriptorBuilder & operator= (const SliceDescriptorBuilder &)
flatbuffers::Offset< SliceDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6480 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SliceDescriptor Table
Definition at line 6481 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SliceDescriptorBuilder()
SliceDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6490 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_begin()
void add_begin (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> begin) inline
Definition at line 6484 of file ArmnnSchema_generated.h.
References VT_BEGIN.
Referenced by armnnSerializer::CreateSliceDescriptor().
{
     fbb_.AddOffset(SliceDescriptor::VT_BEGIN, begin);
   }
add_size()
void add_size (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> size) inline
Definition at line 6487 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSliceDescriptor().
{
     fbb_.AddOffset(SliceDescriptor::VT_SIZE, size);
   }
Finish()
flatbuffers::Offset<SliceDescriptor> Finish () inline
Definition at line 6495 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSliceDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SliceDescriptor>(end);
     return o;
   }
operator=()
SliceDescriptorBuilder& operator= (const SliceDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6482 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6483 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h