ArmNN: QLstmDescriptorBuilder Struct Reference
QLstmDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef QLstmDescriptor Table
Public Member Functions
void add_cifgEnabled (bool cifgEnabled)
void add_peepholeEnabled (bool peepholeEnabled)
void add_projectionEnabled (bool projectionEnabled)
void add_layerNormEnabled (bool layerNormEnabled)
void add_cellClip (float cellClip)
void add_projectionClip (float projectionClip)
void add_inputIntermediateScale (float inputIntermediateScale)
void add_forgetIntermediateScale (float forgetIntermediateScale)
void add_cellIntermediateScale (float cellIntermediateScale)
void add_outputIntermediateScale (float outputIntermediateScale)
void add_hiddenStateZeroPoint (int32_t hiddenStateZeroPoint)
void add_hiddenStateScale (float hiddenStateScale)
QLstmDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
QLstmDescriptorBuilder & operator= (const QLstmDescriptorBuilder &)
flatbuffers::Offset< QLstmDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8070 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef QLstmDescriptor Table
Definition at line 8071 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
QLstmDescriptorBuilder()
QLstmDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8110 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_cellClip()
void add_cellClip (float cellClip) inline
Definition at line 8086 of file ArmnnSchema_generated.h.
References VT_CELLCLIP.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_CELLCLIP, cellClip, 0.0f);
   }
add_cellIntermediateScale()
void add_cellIntermediateScale (float cellIntermediateScale) inline
Definition at line 8098 of file ArmnnSchema_generated.h.
References VT_CELLINTERMEDIATESCALE.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_CELLINTERMEDIATESCALE, cellIntermediateScale, 0.0f);
   }
add_cifgEnabled()
void add_cifgEnabled (bool cifgEnabled) inline
Definition at line 8074 of file ArmnnSchema_generated.h.
References VT_CIFGENABLED.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(QLstmDescriptor::VT_CIFGENABLED, static_cast<uint8_t>(cifgEnabled), 1);
   }
add_forgetIntermediateScale()
void add_forgetIntermediateScale (float forgetIntermediateScale) inline
Definition at line 8095 of file ArmnnSchema_generated.h.
References VT_FORGETINTERMEDIATESCALE.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_FORGETINTERMEDIATESCALE, forgetIntermediateScale, 0.0f);
   }
add_hiddenStateScale()
void add_hiddenStateScale (float hiddenStateScale) inline
Definition at line 8107 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_HIDDENSTATESCALE, hiddenStateScale, 0.0f);
   }
add_hiddenStateZeroPoint()
void add_hiddenStateZeroPoint (int32_t hiddenStateZeroPoint) inline
Definition at line 8104 of file ArmnnSchema_generated.h.
References VT_HIDDENSTATEZEROPOINT.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<int32_t>(QLstmDescriptor::VT_HIDDENSTATEZEROPOINT, hiddenStateZeroPoint, 0);
   }
add_inputIntermediateScale()
void add_inputIntermediateScale (float inputIntermediateScale) inline
Definition at line 8092 of file ArmnnSchema_generated.h.
References VT_INPUTINTERMEDIATESCALE.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_INPUTINTERMEDIATESCALE, inputIntermediateScale, 0.0f);
   }
add_layerNormEnabled()
void add_layerNormEnabled (bool layerNormEnabled) inline
Definition at line 8083 of file ArmnnSchema_generated.h.
References VT_LAYERNORMENABLED.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(QLstmDescriptor::VT_LAYERNORMENABLED, static_cast<uint8_t>(layerNormEnabled), 0);
   }
add_outputIntermediateScale()
void add_outputIntermediateScale (float outputIntermediateScale) inline
Definition at line 8101 of file ArmnnSchema_generated.h.
References VT_OUTPUTINTERMEDIATESCALE.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_OUTPUTINTERMEDIATESCALE, outputIntermediateScale, 0.0f);
   }
add_peepholeEnabled()
void add_peepholeEnabled (bool peepholeEnabled) inline
Definition at line 8077 of file ArmnnSchema_generated.h.
References VT_PEEPHOLEENABLED.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(QLstmDescriptor::VT_PEEPHOLEENABLED, static_cast<uint8_t>(peepholeEnabled), 0);
   }
add_projectionClip()
void add_projectionClip (float projectionClip) inline
Definition at line 8089 of file ArmnnSchema_generated.h.
References VT_PROJECTIONCLIP.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<float>(QLstmDescriptor::VT_PROJECTIONCLIP, projectionClip, 0.0f);
   }
add_projectionEnabled()
void add_projectionEnabled (bool projectionEnabled) inline
Definition at line 8080 of file ArmnnSchema_generated.h.
References VT_PROJECTIONENABLED.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(QLstmDescriptor::VT_PROJECTIONENABLED, static_cast<uint8_t>(projectionEnabled), 0);
   }
Finish()
flatbuffers::Offset<QLstmDescriptor> Finish () inline
Definition at line 8115 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQLstmDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<QLstmDescriptor>(end);
     return o;
   }
operator=()
QLstmDescriptorBuilder& operator= (const QLstmDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8072 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8073 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h