ArmNN: StandInLayerBuilder Struct Reference
StandInLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef StandInLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::StandInDescriptor > descriptor)
StandInLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
StandInLayerBuilder & operator= (const StandInLayerBuilder &)
flatbuffers::Offset< StandInLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9251 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef StandInLayer Table
Definition at line 9252 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
StandInLayerBuilder()
StandInLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9261 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 9255 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateStandInLayer().
{
     fbb_.AddOffset(StandInLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::StandInDescriptor > descriptor) inline
Definition at line 9258 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateStandInLayer().
{
     fbb_.AddOffset(StandInLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<StandInLayer> Finish () inline
Definition at line 9266 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateStandInLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<StandInLayer>(end);
     return o;
   }
operator=()
StandInLayerBuilder& operator= (const StandInLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9253 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9254 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h