ArmNN: CounterSetRecord Struct Reference
CounterSetRecord Struct Reference
#include <CounterDirectory.hpp>
Public Member Functions
void printContents () const
Static Public Member Functions
static void printHeader ()
Public Attributes
uint16_t m_CounterSetUid
uint16_t m_CounterSetCount
std::string m_CounterSetName
Detailed Description
Definition at line 148 of file CounterDirectory.hpp.
Member Function Documentation
printContents()
void printContents () const inline
Definition at line 173 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting().
Referenced by CounterDirectory::print().
     {
         std::string body;
         body.append(gatordmock::CentreAlignFormatting(m_CounterSetName, 20));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterSetUid), 13));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterSetCount), 10));
         body.append("\n");
         std::cout << std::string(body.size(), '-') << "\n";
         std::cout<< body;
     }
printHeader()
static void printHeader () inline static
Definition at line 154 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting().
Referenced by CounterDirectory::print().
     {
         std::string header;
         header.append(gatordmock::CentreAlignFormatting("Counter set name", 20));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("UID",13));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Count",10));
         header.append("\n");
         std::cout << "\n" << "\n";
         std::cout << gatordmock::CentreAlignFormatting("COUNTER SETS", static_cast<int>(header.size()));
         std::cout << "\n";
         std::cout << std::string(header.size(), '=') << "\n";
         std::cout<< header;
     }
Member Data Documentation
m_CounterSetCount
uint16_t m_CounterSetCount
Definition at line 151 of file CounterDirectory.hpp.
m_CounterSetName
std::string m_CounterSetName
Definition at line 152 of file CounterDirectory.hpp.
m_CounterSetUid
uint16_t m_CounterSetUid
Definition at line 150 of file CounterDirectory.hpp.
The documentation for this struct was generated from the following file:
tests/profiling/gatordmock/CounterDirectory.hpp