ArmNN: FeatureCompatibilityVersionsBuilder Struct Reference
FeatureCompatibilityVersionsBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef FeatureCompatibilityVersions Table
Public Member Functions
void add_bindingIdsScheme (uint32_t bindingIdsScheme)
void add_weightsLayoutScheme (uint32_t weightsLayoutScheme)
void add_constantTensorsAsInputs (uint32_t constantTensorsAsInputs)
FeatureCompatibilityVersionsBuilder (flatbuffers::FlatBufferBuilder &_fbb)
FeatureCompatibilityVersionsBuilder & operator= (const FeatureCompatibilityVersionsBuilder &)
flatbuffers::Offset< FeatureCompatibilityVersions > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 10160 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef FeatureCompatibilityVersions Table
Definition at line 10161 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
FeatureCompatibilityVersionsBuilder()
FeatureCompatibilityVersionsBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 10173 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_bindingIdsScheme()
void add_bindingIdsScheme (uint32_t bindingIdsScheme) inline
Definition at line 10164 of file ArmnnSchema_generated.h.
References VT_BINDINGIDSSCHEME.
Referenced by armnnSerializer::CreateFeatureCompatibilityVersions().
{
     fbb_.AddElement<uint32_t>(FeatureCompatibilityVersions::VT_BINDINGIDSSCHEME, bindingIdsScheme, 0);
   }
add_constantTensorsAsInputs()
void add_constantTensorsAsInputs (uint32_t constantTensorsAsInputs) inline
Definition at line 10170 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateFeatureCompatibilityVersions().
{
     fbb_.AddElement<uint32_t>(FeatureCompatibilityVersions::VT_CONSTANTTENSORSASINPUTS, constantTensorsAsInputs, 0);
   }
add_weightsLayoutScheme()
void add_weightsLayoutScheme (uint32_t weightsLayoutScheme) inline
Definition at line 10167 of file ArmnnSchema_generated.h.
References VT_WEIGHTSLAYOUTSCHEME.
Referenced by armnnSerializer::CreateFeatureCompatibilityVersions().
{
     fbb_.AddElement<uint32_t>(FeatureCompatibilityVersions::VT_WEIGHTSLAYOUTSCHEME, weightsLayoutScheme, 0);
   }
Finish()
flatbuffers::Offset<FeatureCompatibilityVersions> Finish () inline
Definition at line 10178 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateFeatureCompatibilityVersions().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<FeatureCompatibilityVersions>(end);
     return o;
   }
operator=()
FeatureCompatibilityVersionsBuilder& operator= (const FeatureCompatibilityVersionsBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 10162 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 10163 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h