ArmNN: QLstmLayerBuilder Struct Reference
QLstmLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef QLstmLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::QLstmDescriptor > descriptor)
void add_inputParams (flatbuffers::Offset< armnnSerializer::QLstmInputParams > inputParams)
QLstmLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
QLstmLayerBuilder & operator= (const QLstmLayerBuilder &)
flatbuffers::Offset< QLstmLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8180 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef QLstmLayer Table
Definition at line 8181 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
QLstmLayerBuilder()
QLstmLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8193 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 8184 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateQLstmLayer().
{
     fbb_.AddOffset(QLstmLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::QLstmDescriptor > descriptor) inline
Definition at line 8187 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateQLstmLayer().
{
     fbb_.AddOffset(QLstmLayer::VT_DESCRIPTOR, descriptor);
   }
add_inputParams()
void add_inputParams (flatbuffers::Offset< armnnSerializer::QLstmInputParams > inputParams) inline
Definition at line 8190 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQLstmLayer().
{
     fbb_.AddOffset(QLstmLayer::VT_INPUTPARAMS, inputParams);
   }
Finish()
flatbuffers::Offset<QLstmLayer> Finish () inline
Definition at line 8198 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQLstmLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<QLstmLayer>(end);
     return o;
   }
operator=()
QLstmLayerBuilder& operator= (const QLstmLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8182 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8183 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h