ArmNN: SpaceToBatchNdDescriptorBuilder Struct Reference
SpaceToBatchNdDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SpaceToBatchNdDescriptor Table
Public Member Functions
void add_blockShape (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape)
void add_padList (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
SpaceToBatchNdDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SpaceToBatchNdDescriptorBuilder & operator= (const SpaceToBatchNdDescriptorBuilder &)
flatbuffers::Offset< SpaceToBatchNdDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5349 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SpaceToBatchNdDescriptor Table
Definition at line 5350 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SpaceToBatchNdDescriptorBuilder()
SpaceToBatchNdDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5362 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_blockShape()
void add_blockShape (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape) inline
Definition at line 5353 of file ArmnnSchema_generated.h.
References VT_BLOCKSHAPE.
Referenced by armnnSerializer::CreateSpaceToBatchNdDescriptor().
{
     fbb_.AddOffset(SpaceToBatchNdDescriptor::VT_BLOCKSHAPE, blockShape);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 5359 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateSpaceToBatchNdDescriptor().
{
     fbb_.AddElement<int8_t>(SpaceToBatchNdDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_padList()
void add_padList (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList) inline
Definition at line 5356 of file ArmnnSchema_generated.h.
References VT_PADLIST.
Referenced by armnnSerializer::CreateSpaceToBatchNdDescriptor().
{
     fbb_.AddOffset(SpaceToBatchNdDescriptor::VT_PADLIST, padList);
   }
Finish()
flatbuffers::Offset<SpaceToBatchNdDescriptor> Finish () inline
Definition at line 5367 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSpaceToBatchNdDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SpaceToBatchNdDescriptor>(end);
     return o;
   }
operator=()
SpaceToBatchNdDescriptorBuilder& operator= (const SpaceToBatchNdDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5351 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5352 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h