ArmNN: InputSlotBuilder Struct Reference
InputSlotBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef InputSlot Table
Public Member Functions
void add_index (uint32_t index)
void add_connection (const armnnSerializer::Connection *connection)
InputSlotBuilder (flatbuffers::FlatBufferBuilder &_fbb)
InputSlotBuilder & operator= (const InputSlotBuilder &)
flatbuffers::Offset< InputSlot > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2151 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef InputSlot Table
Definition at line 2152 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
InputSlotBuilder()
InputSlotBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2161 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_connection()
void add_connection (const armnnSerializer::Connection * connection) inline
Definition at line 2158 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateInputSlot().
{
     fbb_.AddStruct(InputSlot::VT_CONNECTION, connection);
   }
add_index()
void add_index (uint32_t index) inline
Definition at line 2155 of file ArmnnSchema_generated.h.
References VT_INDEX.
Referenced by armnnSerializer::CreateInputSlot().
{
     fbb_.AddElement<uint32_t>(InputSlot::VT_INDEX, index, 0);
   }
Finish()
flatbuffers::Offset<InputSlot> Finish () inline
Definition at line 2166 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateInputSlot().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<InputSlot>(end);
     return o;
   }
operator=()
InputSlotBuilder& operator= (const InputSlotBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2153 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2154 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h