ArmNN: StringifyLayerParameters< OriginsDescriptor > Struct Template Reference
StringifyLayerParameters< OriginsDescriptor > Struct Template Reference
#include <SerializeLayerParameters.hpp>
Static Public Member Functions
static void Serialize (ParameterStringifyFunction &fn, const OriginsDescriptor &desc)
Detailed Description
template<>
struct armnn::StringifyLayerParameters< OriginsDescriptor >
Definition at line 98 of file SerializeLayerParameters.hpp.
Member Function Documentation
Serialize()
void Serialize (ParameterStringifyFunction & fn, const OriginsDescriptor & desc) static
Definition at line 216 of file SerializeLayerParameters.cpp.
References OriginsDescriptor::GetConcatAxis(), OriginsDescriptor::GetNumDimensions(), OriginsDescriptor::GetNumViews(), and OriginsDescriptor::GetViewOrigin().
 {
     fn("ConcatAxis", std::to_string(desc.GetConcatAxis()));
     uint32_t numViews = desc.GetNumViews();
     uint32_t numDims  = desc.GetNumDimensions();
     for (uint32_t view = 0; view < numViews; ++view)
     {
         std::stringstream key;
         key << "MergeTo#" << view;
         std::stringstream value;
         value << "[";
         auto viewData = desc.GetViewOrigin(view);
         for (uint32_t dim = 0; dim < numDims; ++dim)
         {
             if (dim > 0)
             {
                 value << ",";
             }
             value << viewData[dim];
         }
         value << "]";
         fn(key.str(), value.str());
     }
 }
The documentation for this struct was generated from the following files:
src/armnn/SerializeLayerParameters.hpp
src/armnn/SerializeLayerParameters.cpp