var searchData=
[
  ['onnxparserimpl_5764',['OnnxParserImpl',['../classarmnn_onnx_parser_1_1_onnx_parser_impl.html',1,'armnnOnnxParser']]],
  ['opencltimer_5765',['OpenClTimer',['../classarmnn_1_1_open_cl_timer.html',1,'armnn']]],
  ['optimization_5766',['Optimization',['../classarmnn_1_1_optimization.html',1,'armnn']]],
  ['optimizationresult_5767',['OptimizationResult',['../structarmnn_1_1_optimization_result.html',1,'armnn']]],
  ['optimizationviews_5768',['OptimizationViews',['../classarmnn_1_1_optimization_views.html',1,'armnn']]],
  ['optimizeconsecutivereshapesimpl_5769',['OptimizeConsecutiveReshapesImpl',['../classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl.html',1,'armnn::optimizations']]],
  ['optimizednetworkimpl_5770',['OptimizedNetworkImpl',['../classarmnn_1_1_optimized_network_impl.html',1,'armnn']]],
  ['optimizeforconnection_5771',['OptimizeForConnection',['../classarmnn_1_1_optimize_for_connection.html',1,'armnn']]],
  ['optimizeforconnectionimpl_5772',['OptimizeForConnectionImpl',['../classarmnn_1_1_optimize_for_connection_impl.html',1,'armnn']]],
  ['optimizeforexclusiveconnection_5773',['OptimizeForExclusiveConnection',['../classarmnn_1_1_optimize_for_exclusive_connection.html',1,'armnn']]],
  ['optimizeforexclusiveconnectionimpl_5774',['OptimizeForExclusiveConnectionImpl',['../classarmnn_1_1_optimize_for_exclusive_connection_impl.html',1,'armnn']]],
  ['optimizefortype_5775',['OptimizeForType',['../classarmnn_1_1_optimize_for_type.html',1,'armnn']]],
  ['optimizefortypeimpl_5776',['OptimizeForTypeImpl',['../classarmnn_1_1_optimize_for_type_impl.html',1,'armnn']]],
  ['optimizefortypeimpl_3c_20basetype_2c_20optimizeforconnectionimpl_3c_20basetype_2c_20childtype_2c_20wrapped_20_3e_20_3e_5777',['OptimizeForTypeImpl&lt; BaseType, OptimizeForConnectionImpl&lt; BaseType, ChildType, Wrapped &gt; &gt;',['../classarmnn_1_1_optimize_for_type_impl.html',1,'armnn']]],
  ['optimizefortypeimpl_3c_20basetype_2c_20optimizeforexclusiveconnectionimpl_3c_20basetype_2c_20childtype_2c_20wrapped_20_3e_20_3e_5778',['OptimizeForTypeImpl&lt; BaseType, OptimizeForExclusiveConnectionImpl&lt; BaseType, ChildType, Wrapped &gt; &gt;',['../classarmnn_1_1_optimize_for_type_impl.html',1,'armnn']]],
  ['optimizefortypeimpl_3c_20layer_2c_20wrapped_20_3e_5779',['OptimizeForTypeImpl&lt; Layer, Wrapped &gt;',['../classarmnn_1_1_optimize_for_type_impl_3_01_layer_00_01_wrapped_01_4.html',1,'armnn']]],
  ['optimizeinverseconversionsimpl_5780',['OptimizeInverseConversionsImpl',['../classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl.html',1,'armnn::optimizations']]],
  ['optimizeinversepermutesimpl_5781',['OptimizeInversePermutesImpl',['../classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl.html',1,'armnn::optimizations']]],
  ['optimizer_5782',['Optimizer',['../classarmnn_1_1_optimizer.html',1,'armnn']]],
  ['optimizeroptions_5783',['OptimizerOptions',['../structarmnn_1_1_optimizer_options.html',1,'armnn']]],
  ['optimizeroptionsopaque_5784',['OptimizerOptionsOpaque',['../classarmnn_1_1_optimizer_options_opaque.html',1,'armnn']]],
  ['optimizeroptionsopaqueimpl_5785',['OptimizerOptionsOpaqueImpl',['../structarmnn_1_1_optimizer_options_opaque_impl.html',1,'armnn']]],
  ['optional_5786',['Optional',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_5787',['Optional&lt; arm::pipe::IProfilingService &amp; &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_5788',['Optional&lt; arm::pipe::ProfilingGuid &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20armnn_3a_3abackendid_20_3e_5789',['Optional&lt; armnn::BackendId &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20armnn_3a_3atensorinfo_20_3e_5790',['Optional&lt; armnn::TensorInfo &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_5791',['Optional&lt; armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20int32_5ft_20_3e_5792',['Optional&lt; int32_t &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20std_3a_3astring_20_3e_5793',['Optional&lt; std::string &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_5794',['Optional&lt; std::vector&lt; armnn::MemoryInfo &gt; &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20unsigned_20int_20_3e_5795',['Optional&lt; unsigned int &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optionalbase_5796',['OptionalBase',['../classarmnn_1_1_optional_base.html',1,'armnn']]],
  ['optionalreferenceswitch_5797',['OptionalReferenceSwitch',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20t_20_3e_3a_3avalue_2c_20t_20_3e_5798',['OptionalReferenceSwitch&lt; std::is_reference&lt; T &gt;::value, T &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20true_2c_20t_20_3e_5799',['OptionalReferenceSwitch&lt; true, T &gt;',['../classarmnn_1_1_optional_reference_switch_3_01true_00_01_t_01_4.html',1,'armnn']]],
  ['originsdescriptor_5800',['OriginsDescriptor',['../structarmnn_1_1_origins_descriptor.html',1,'armnn']]],
  ['outputhandler_5801',['OutputHandler',['../classarmnn_1_1_output_handler.html',1,'armnn']]],
  ['outputlayer_5802',['OutputLayer',['../classarmnn_1_1_output_layer.html',1,'armnn']]],
  ['outputlayersaccessor_5803',['OutputLayersAccessor',['../structarmnn_1_1_graph_1_1_output_layers_accessor.html',1,'armnn::Graph']]],
  ['outputslot_5804',['OutputSlot',['../classarmnn_1_1_output_slot.html',1,'armnn']]]
];
