var searchData=
[
  ['tensor_6181',['Tensor',['../classarmnn_1_1_tensor.html',1,'armnn']]],
  ['tensorbufferarrayview_6182',['TensorBufferArrayView',['../classarmnn_1_1_tensor_buffer_array_view.html',1,'armnn']]],
  ['tensorhandle_6183',['TensorHandle',['../classarmnn_1_1_tensor_handle.html',1,'armnn']]],
  ['tensorhandlefactoryregistry_6184',['TensorHandleFactoryRegistry',['../classarmnn_1_1_tensor_handle_factory_registry.html',1,'armnn']]],
  ['tensorinfo_6185',['TensorInfo',['../classarmnn_1_1_tensor_info.html',1,'armnn']]],
  ['tensormemory_6186',['TensorMemory',['../structarmnn_1_1_tensor_memory.html',1,'armnn']]],
  ['tensornumdimensionsarecorrect_6187',['TensorNumDimensionsAreCorrect',['../structarmnn_1_1_tensor_num_dimensions_are_correct.html',1,'armnn']]],
  ['tensornumdimensionsaregreaterorequalto_6188',['TensorNumDimensionsAreGreaterOrEqualTo',['../structarmnn_1_1_tensor_num_dimensions_are_greater_or_equal_to.html',1,'armnn']]],
  ['tensorshape_6189',['TensorShape',['../classarmnn_1_1_tensor_shape.html',1,'armnn']]],
  ['tfliteparserimpl_6190',['TfLiteParserImpl',['../classarmnn_tf_lite_parser_1_1_tf_lite_parser_impl.html',1,'armnnTfLiteParser']]],
  ['tfliteparseroptions_6191',['TfLiteParserOptions',['../structarmnn_tf_lite_parser_1_1_i_tf_lite_parser_1_1_tf_lite_parser_options.html',1,'armnnTfLiteParser::ITfLiteParser']]],
  ['throwingstrategy_6192',['ThrowingStrategy',['../structarmnn_1_1_throwing_strategy.html',1,'armnn']]],
  ['tiledescriptor_6193',['TileDescriptor',['../structarmnn_1_1_tile_descriptor.html',1,'armnn']]],
  ['tilelayer_6194',['TileLayer',['../classarmnn_1_1_tile_layer.html',1,'armnn']]],
  ['tilequeuedescriptor_6195',['TileQueueDescriptor',['../structarmnn_1_1_tile_queue_descriptor.html',1,'armnn']]],
  ['timeoutexception_6196',['TimeoutException',['../classarmnn_1_1_timeout_exception.html',1,'armnn']]],
  ['tosaassertsize_6197',['TosaAssertSize',['../struct_tosa_assert_size.html',1,'']]],
  ['tosacontainercontainsthreetypes_6198',['TosaContainerContainsThreeTypes',['../struct_tosa_container_contains_three_types.html',1,'']]],
  ['tosacontainercontainstwotypes_6199',['TosaContainerContainsTwoTypes',['../struct_tosa_container_contains_two_types.html',1,'']]],
  ['tosaoperatorattributeofany_6200',['TosaOperatorAttributeOfAny',['../struct_tosa_operator_attribute_of_any.html',1,'']]],
  ['tosarefbackend_6201',['TosaRefBackend',['../classarmnn_1_1_tosa_ref_backend.html',1,'armnn']]],
  ['tosarefbaseworkload_6202',['TosaRefBaseWorkload',['../classarmnn_1_1_tosa_ref_base_workload.html',1,'armnn']]],
  ['tosareflayersupport_6203',['TosaRefLayerSupport',['../classarmnn_1_1_tosa_ref_layer_support.html',1,'armnn']]],
  ['tosarefmemorymanager_6204',['TosaRefMemoryManager',['../classarmnn_1_1_tosa_ref_memory_manager.html',1,'armnn']]],
  ['tosarefprecompiledworkload_6205',['TosaRefPreCompiledWorkload',['../classarmnn_1_1_tosa_ref_pre_compiled_workload.html',1,'armnn']]],
  ['tosareftensorhandle_6206',['TosaRefTensorHandle',['../classarmnn_1_1_tosa_ref_tensor_handle.html',1,'armnn']]],
  ['tosareftensorhandlefactory_6207',['TosaRefTensorHandleFactory',['../classarmnn_1_1_tosa_ref_tensor_handle_factory.html',1,'armnn']]],
  ['tosarefworkloadfactory_6208',['TosaRefWorkloadFactory',['../classarmnn_1_1_tosa_ref_workload_factory.html',1,'armnn']]],
  ['tosatensornumdimensionswithinbounds_6209',['TosaTensorNumDimensionsWithinBounds',['../struct_tosa_tensor_num_dimensions_within_bounds.html',1,'']]],
  ['tosatypeanyof_6210',['TosaTypeAnyOf',['../struct_tosa_type_any_of.html',1,'']]],
  ['transformiterator_6211',['TransformIterator',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transposeasreshapeimpl_6212',['TransposeAsReshapeImpl',['../classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.html',1,'armnn::optimizations']]],
  ['transposeconvolution2ddescriptor_6213',['TransposeConvolution2dDescriptor',['../structarmnn_1_1_transpose_convolution2d_descriptor.html',1,'armnn']]],
  ['transposeconvolution2dlayer_6214',['TransposeConvolution2dLayer',['../classarmnn_1_1_transpose_convolution2d_layer.html',1,'armnn']]],
  ['transposeconvolution2dqueuedescriptor_6215',['TransposeConvolution2dQueueDescriptor',['../structarmnn_1_1_transpose_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['transposedescriptor_6216',['TransposeDescriptor',['../structarmnn_1_1_transpose_descriptor.html',1,'armnn']]],
  ['transposelayer_6217',['TransposeLayer',['../classarmnn_1_1_transpose_layer.html',1,'armnn']]],
  ['transposequeuedescriptor_6218',['TransposeQueueDescriptor',['../structarmnn_1_1_transpose_queue_descriptor.html',1,'armnn']]],
  ['turboconvertconstdequantisationlayerstoconstlayersimpl_6219',['TurboConvertConstDequantisationLayersToConstLayersImpl',['../classarmnn_1_1optimizations_1_1_turbo_convert_const_dequantisation_layers_to_const_layers_impl.html',1,'armnn::optimizations']]],
  ['typeanyof_6220',['TypeAnyOf',['../structarmnn_1_1_type_any_of.html',1,'armnn']]],
  ['typediterator_6221',['TypedIterator',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20float_2c_20decoder_3c_20float_20_3e_20_3e_6222',['TypedIterator&lt; const float, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20half_2c_20decoder_3c_20float_20_3e_20_3e_6223',['TypedIterator&lt; const Half, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int16_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6224',['TypedIterator&lt; const int16_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6225',['TypedIterator&lt; const int32_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20int32_5ft_20_3e_20_3e_6226',['TypedIterator&lt; const int32_t, Decoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int64_5ft_2c_20decoder_3c_20double_5ft_20_3e_20_3e_6227',['TypedIterator&lt; const int64_t, Decoder&lt; double_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6228',['TypedIterator&lt; const int8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20bool_20_3e_20_3e_6229',['TypedIterator&lt; const uint8_t, Decoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6230',['TypedIterator&lt; const uint8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20float_2c_20encoder_3c_20float_20_3e_20_3e_6231',['TypedIterator&lt; float, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20half_2c_20encoder_3c_20float_20_3e_20_3e_6232',['TypedIterator&lt; Half, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int16_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6233',['TypedIterator&lt; int16_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6234',['TypedIterator&lt; int32_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20int32_5ft_20_3e_20_3e_6235',['TypedIterator&lt; int32_t, Encoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int64_5ft_2c_20encoder_3c_20double_20_3e_20_3e_6236',['TypedIterator&lt; int64_t, Encoder&lt; double &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6237',['TypedIterator&lt; int8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20bool_20_3e_20_3e_6238',['TypedIterator&lt; uint8_t, Encoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6239',['TypedIterator&lt; uint8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typedworkload_6240',['TypedWorkload',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20debugqueuedescriptor_2c_20datatype_20_3e_6241',['TypedWorkload&lt; DebugQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20permutequeuedescriptor_2c_20datatype_20_3e_6242',['TypedWorkload&lt; PermuteQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20transposequeuedescriptor_2c_20datatype_20_3e_6243',['TypedWorkload&lt; TransposeQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typeis_6244',['TypeIs',['../structarmnn_1_1_type_is.html',1,'armnn']]],
  ['typenotperaxisquantized_6245',['TypeNotPerAxisQuantized',['../structarmnn_1_1_type_not_per_axis_quantized.html',1,'armnn']]],
  ['typesareequal_6246',['TypesAreEqual',['../structarmnn_1_1_types_are_equal.html',1,'armnn']]]
];
