var searchData=
[
  ['neonabsworkload_5612',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.html',1,'armnn']]],
  ['neonactivationworkload_5613',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.html',1,'armnn']]],
  ['neonadditionworkload_5614',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.html',1,'armnn']]],
  ['neonargminmaxworkload_5615',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.html',1,'armnn']]],
  ['neonbackend_5616',['NeonBackend',['../classarmnn_1_1_neon_backend.html',1,'armnn']]],
  ['neonbackendmodelcontext_5617',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.html',1,'armnn']]],
  ['neonbaseworkload_5618',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e_5619',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e_5620',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e_5621',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5622',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5623',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5624',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5625',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e_5626',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5627',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5628',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e_5629',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e_5630',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5631',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5632',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5633',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5634',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5635',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5636',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e_5637',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5638',['NeonBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5639',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e_5640',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5641',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fusedqueuedescriptor_20_3e_5642',['NeonBaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e_5643',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e_5644',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5645',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5646',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5647',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e_5648',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e_5649',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e_5650',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e_5651',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e_5652',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e_5653',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_5654',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_5655',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e_5656',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e_5657',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5658',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e_5659',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e_5660',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e_5661',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e_5662',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e_5663',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e_5664',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e_5665',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e_5666',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5667',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5668',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e_5669',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e_5670',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_5671',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e_5672',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5673',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e_5674',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5675',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbatchmatmulworkload_5676',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.html',1,'armnn']]],
  ['neonbatchnormalizationworkload_5677',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.html',1,'armnn']]],
  ['neonbatchtospacendworkload_5678',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.html',1,'armnn']]],
  ['neoncastworkload_5679',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.html',1,'armnn']]],
  ['neonchannelshuffleworkload_5680',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.html',1,'armnn']]],
  ['neoncomparisonworkload_5681',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.html',1,'armnn']]],
  ['neonconcatworkload_5682',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.html',1,'armnn']]],
  ['neonconstantworkload_5683',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.html',1,'armnn']]],
  ['neonconvertfp16tofp32workload_5684',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['neonconvertfp32tofp16workload_5685',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['neonconvolution2dworkload_5686',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.html',1,'armnn']]],
  ['neonconvolution3dworkload_5687',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.html',1,'armnn']]],
  ['neondepthtospaceworkload_5688',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.html',1,'armnn']]],
  ['neondepthwiseconvolutionworkload_5689',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.html',1,'armnn']]],
  ['neondequantizeworkload_5690',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.html',1,'armnn']]],
  ['neondetectionpostprocessworkload_5691',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.html',1,'armnn']]],
  ['neondivisionworkload_5692',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.html',1,'armnn']]],
  ['neonelementwisebinaryworkload_5693',['NeonElementwiseBinaryWorkload',['../classarmnn_1_1_neon_elementwise_binary_workload.html',1,'armnn']]],
  ['neonexpworkload_5694',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.html',1,'armnn']]],
  ['neonfillworkload_5695',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.html',1,'armnn']]],
  ['neonfloordivworkload_5696',['NeonFloorDivWorkload',['../classarmnn_1_1_neon_floor_div_workload.html',1,'armnn']]],
  ['neonfloorfloatworkload_5697',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.html',1,'armnn']]],
  ['neonfullyconnectedworkload_5698',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.html',1,'armnn']]],
  ['neonfusedworkload_5699',['NeonFusedWorkload',['../classarmnn_1_1_neon_fused_workload.html',1,'armnn']]],
  ['neongatherndworkload_5700',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.html',1,'armnn']]],
  ['neongatherworkload_5701',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.html',1,'armnn']]],
  ['neoninstancenormalizationworkload_5702',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.html',1,'armnn']]],
  ['neoninterceptorscheduler_5703',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.html',1,'armnn']]],
  ['neonl2normalizationfloatworkload_5704',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.html',1,'armnn']]],
  ['neonlayersupport_5705',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.html',1,'armnn']]],
  ['neonlogicalandworkload_5706',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.html',1,'armnn']]],
  ['neonlogicalnotworkload_5707',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.html',1,'armnn']]],
  ['neonlogicalorworkload_5708',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.html',1,'armnn']]],
  ['neonlogsoftmaxworkload_5709',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.html',1,'armnn']]],
  ['neonlogworkload_5710',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.html',1,'armnn']]],
  ['neonlstmfloatworkload_5711',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.html',1,'armnn']]],
  ['neonmaximumworkload_5712',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.html',1,'armnn']]],
  ['neonmeanworkload_5713',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.html',1,'armnn']]],
  ['neonmemorymanager_5714',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.html',1,'armnn']]],
  ['neonminimumworkload_5715',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.html',1,'armnn']]],
  ['neonmultiplicationworkload_5716',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.html',1,'armnn']]],
  ['neonnegworkload_5717',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.html',1,'armnn']]],
  ['neonnormalizationfloatworkload_5718',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.html',1,'armnn']]],
  ['neonpadworkload_5719',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.html',1,'armnn']]],
  ['neonpermuteworkload_5720',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.html',1,'armnn']]],
  ['neonpooling2dworkload_5721',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.html',1,'armnn']]],
  ['neonpooling3dworkload_5722',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.html',1,'armnn']]],
  ['neonpreluworkload_5723',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.html',1,'armnn']]],
  ['neonqlstmworkload_5724',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.html',1,'armnn']]],
  ['neonquantizedlstmworkload_5725',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.html',1,'armnn']]],
  ['neonquantizeworkload_5726',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.html',1,'armnn']]],
  ['neonrankworkload_5727',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.html',1,'armnn']]],
  ['neonreduceworkload_5728',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.html',1,'armnn']]],
  ['neonreshapeworkload_5729',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.html',1,'armnn']]],
  ['neonresizeworkload_5730',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.html',1,'armnn']]],
  ['neonreversev2workload_5731',['NeonReverseV2Workload',['../classarmnn_1_1_neon_reverse_v2_workload.html',1,'armnn']]],
  ['neonrsqrtworkload_5732',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.html',1,'armnn']]],
  ['neonsinworkload_5733',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.html',1,'armnn']]],
  ['neonsliceworkload_5734',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.html',1,'armnn']]],
  ['neonsoftmaxworkload_5735',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.html',1,'armnn']]],
  ['neonspacetobatchndworkload_5736',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.html',1,'armnn']]],
  ['neonspacetodepthworkload_5737',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.html',1,'armnn']]],
  ['neonsplitterworkload_5738',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.html',1,'armnn']]],
  ['neonsqrtworkload_5739',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.html',1,'armnn']]],
  ['neonstackworkload_5740',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.html',1,'armnn']]],
  ['neonstridedsliceworkload_5741',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.html',1,'armnn']]],
  ['neonsubtensorhandle_5742',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.html',1,'armnn']]],
  ['neonsubtractionworkload_5743',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.html',1,'armnn']]],
  ['neontensordecorator_5744',['NeonTensorDecorator',['../classarmnn_1_1_neon_tensor_decorator.html',1,'armnn']]],
  ['neontensorhandle_5745',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.html',1,'armnn']]],
  ['neontensorhandledecorator_5746',['NeonTensorHandleDecorator',['../classarmnn_1_1_neon_tensor_handle_decorator.html',1,'armnn']]],
  ['neontensorhandlefactory_5747',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.html',1,'armnn']]],
  ['neontileworkload_5748',['NeonTileWorkload',['../classarmnn_1_1_neon_tile_workload.html',1,'armnn']]],
  ['neontimer_5749',['NeonTimer',['../classarmnn_1_1_neon_timer.html',1,'armnn']]],
  ['neontransposeconvolution2dworkload_5750',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.html',1,'armnn']]],
  ['neontransposeworkload_5751',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload_5752',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload_5753',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['neonworkloadfactory_5754',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.html',1,'armnn']]],
  ['networkimpl_5755',['NetworkImpl',['../classarmnn_1_1_network_impl.html',1,'armnn']]],
  ['nodecontent_5756',['NodeContent',['../classarmnn_1_1_node_content.html',1,'armnn']]],
  ['normalizationdescriptor_5757',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.html',1,'armnn']]],
  ['normalizationlayer_5758',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.html',1,'armnn']]],
  ['normalizationqueuedescriptor_5759',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.html',1,'armnn']]],
  ['nothrowstrategy_5760',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.html',1,'armnn']]],
  ['nulldescriptor_5761',['NullDescriptor',['../structarmnn_1_1_null_descriptor.html',1,'armnn']]],
  ['nullpointerexception_5762',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.html',1,'armnn']]],
  ['nullworkload_5763',['NullWorkload',['../classarmnn_1_1_null_workload.html',1,'armnn']]]
];
