var searchData=
[
  ['qasymm8decoder_5842',['QASymm8Decoder',['../classarmnn_1_1_q_a_symm8_decoder.html',1,'armnn']]],
  ['qasymm8encoder_5843',['QASymm8Encoder',['../classarmnn_1_1_q_a_symm8_encoder.html',1,'armnn']]],
  ['qasymms8decoder_5844',['QASymmS8Decoder',['../classarmnn_1_1_q_a_symm_s8_decoder.html',1,'armnn']]],
  ['qasymms8encoder_5845',['QASymmS8Encoder',['../classarmnn_1_1_q_a_symm_s8_encoder.html',1,'armnn']]],
  ['qlstmbasicparameters_5846',['QLstmBasicParameters',['../structarmnn_1_1_q_lstm_basic_parameters.html',1,'armnn']]],
  ['qlstmdescriptor_5847',['QLstmDescriptor',['../structarmnn_1_1_q_lstm_descriptor.html',1,'armnn']]],
  ['qlstmlayer_5848',['QLstmLayer',['../classarmnn_1_1_q_lstm_layer.html',1,'armnn']]],
  ['qlstmoptcifgparameters_5849',['QLstmOptCifgParameters',['../structarmnn_1_1_q_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['qlstmoptlayernormparameters_5850',['QLstmOptLayerNormParameters',['../structarmnn_1_1_q_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['qlstmoptpeepholeparameters_5851',['QLstmOptPeepholeParameters',['../structarmnn_1_1_q_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['qlstmoptprojectionparameters_5852',['QLstmOptProjectionParameters',['../structarmnn_1_1_q_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['qlstmqueuedescriptor_5853',['QLstmQueueDescriptor',['../structarmnn_1_1_q_lstm_queue_descriptor.html',1,'armnn']]],
  ['qsymm16decoder_5854',['QSymm16Decoder',['../classarmnn_1_1_q_symm16_decoder.html',1,'armnn']]],
  ['qsymm16encoder_5855',['QSymm16Encoder',['../classarmnn_1_1_q_symm16_encoder.html',1,'armnn']]],
  ['qsymm16peraxisencoder_5856',['QSymm16PerAxisEncoder',['../classarmnn_1_1_q_symm16_per_axis_encoder.html',1,'armnn']]],
  ['qsymm8peraxisdecoder_5857',['QSymm8PerAxisDecoder',['../classarmnn_1_1_q_symm8_per_axis_decoder.html',1,'armnn']]],
  ['qsymm8peraxisencoder_5858',['QSymm8PerAxisEncoder',['../classarmnn_1_1_q_symm8_per_axis_encoder.html',1,'armnn']]],
  ['qsymms8decoder_5859',['QSymmS8Decoder',['../classarmnn_1_1_q_symm_s8_decoder.html',1,'armnn']]],
  ['qsymms8encoder_5860',['QSymmS8Encoder',['../classarmnn_1_1_q_symm_s8_encoder.html',1,'armnn']]],
  ['quantizationparametersareequal_5861',['QuantizationParametersAreEqual',['../structarmnn_1_1_quantization_parameters_are_equal.html',1,'armnn']]],
  ['quantizedlstminputparams_5862',['QuantizedLstmInputParams',['../structarmnn_1_1_quantized_lstm_input_params.html',1,'armnn']]],
  ['quantizedlstminputparamsinfo_5863',['QuantizedLstmInputParamsInfo',['../structarmnn_1_1_quantized_lstm_input_params_info.html',1,'armnn']]],
  ['quantizedlstmlayer_5864',['QuantizedLstmLayer',['../classarmnn_1_1_quantized_lstm_layer.html',1,'armnn']]],
  ['quantizedlstmparameters_5865',['QuantizedLstmParameters',['../structarmnn_1_1_quantized_lstm_parameters.html',1,'armnn']]],
  ['quantizedlstmqueuedescriptor_5866',['QuantizedLstmQueueDescriptor',['../structarmnn_1_1_quantized_lstm_queue_descriptor.html',1,'armnn']]],
  ['quantizedmultipliersmallerthanone_5867',['QuantizedMultiplierSmallerThanOne',['../structarmnn_1_1_quantized_multiplier_smaller_than_one.html',1,'armnn']]],
  ['quantizelayer_5868',['QuantizeLayer',['../classarmnn_1_1_quantize_layer.html',1,'armnn']]],
  ['quantizequeuedescriptor_5869',['QuantizeQueueDescriptor',['../structarmnn_1_1_quantize_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptor_5870',['QueueDescriptor',['../structarmnn_1_1_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptorwithparameters_5871',['QueueDescriptorWithParameters',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20activationdescriptor_20_3e_5872',['QueueDescriptorWithParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20argminmaxdescriptor_20_3e_5873',['QueueDescriptorWithParameters&lt; ArgMinMaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchmatmuldescriptor_20_3e_5874',['QueueDescriptorWithParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchnormalizationdescriptor_20_3e_5875',['QueueDescriptorWithParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchtospacenddescriptor_20_3e_5876',['QueueDescriptorWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20broadcasttodescriptor_20_3e_5877',['QueueDescriptorWithParameters&lt; BroadcastToDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20channelshuffledescriptor_20_3e_5878',['QueueDescriptorWithParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20comparisondescriptor_20_3e_5879',['QueueDescriptorWithParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution2ddescriptor_20_3e_5880',['QueueDescriptorWithParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution3ddescriptor_20_3e_5881',['QueueDescriptorWithParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthtospacedescriptor_20_3e_5882',['QueueDescriptorWithParameters&lt; DepthToSpaceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_5883',['QueueDescriptorWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20detectionpostprocessdescriptor_20_3e_5884',['QueueDescriptorWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwisebinarydescriptor_20_3e_5885',['QueueDescriptorWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwiseunarydescriptor_20_3e_5886',['QueueDescriptorWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fakequantizationdescriptor_20_3e_5887',['QueueDescriptorWithParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20filldescriptor_20_3e_5888',['QueueDescriptorWithParameters&lt; FillDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fullyconnecteddescriptor_20_3e_5889',['QueueDescriptorWithParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fuseddescriptor_20_3e_5890',['QueueDescriptorWithParameters&lt; FusedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20gatherdescriptor_20_3e_5891',['QueueDescriptorWithParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20instancenormalizationdescriptor_20_3e_5892',['QueueDescriptorWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20l2normalizationdescriptor_20_3e_5893',['QueueDescriptorWithParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logicalbinarydescriptor_20_3e_5894',['QueueDescriptorWithParameters&lt; LogicalBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logsoftmaxdescriptor_20_3e_5895',['QueueDescriptorWithParameters&lt; LogSoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20lstmdescriptor_20_3e_5896',['QueueDescriptorWithParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20meandescriptor_20_3e_5897',['QueueDescriptorWithParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20normalizationdescriptor_20_3e_5898',['QueueDescriptorWithParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20originsdescriptor_20_3e_5899',['QueueDescriptorWithParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20paddescriptor_20_3e_5900',['QueueDescriptorWithParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20permutedescriptor_20_3e_5901',['QueueDescriptorWithParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling2ddescriptor_20_3e_5902',['QueueDescriptorWithParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling3ddescriptor_20_3e_5903',['QueueDescriptorWithParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20precompileddescriptor_20_3e_5904',['QueueDescriptorWithParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20qlstmdescriptor_20_3e_5905',['QueueDescriptorWithParameters&lt; QLstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reducedescriptor_20_3e_5906',['QueueDescriptorWithParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reshapedescriptor_20_3e_5907',['QueueDescriptorWithParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20resizedescriptor_20_3e_5908',['QueueDescriptorWithParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20scatternddescriptor_20_3e_5909',['QueueDescriptorWithParameters&lt; ScatterNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20slicedescriptor_20_3e_5910',['QueueDescriptorWithParameters&lt; SliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20softmaxdescriptor_20_3e_5911',['QueueDescriptorWithParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetobatchnddescriptor_20_3e_5912',['QueueDescriptorWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetodepthdescriptor_20_3e_5913',['QueueDescriptorWithParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stackdescriptor_20_3e_5914',['QueueDescriptorWithParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stridedslicedescriptor_20_3e_5915',['QueueDescriptorWithParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20tiledescriptor_20_3e_5916',['QueueDescriptorWithParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_5917',['QueueDescriptorWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposedescriptor_20_3e_5918',['QueueDescriptorWithParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20viewsdescriptor_20_3e_5919',['QueueDescriptorWithParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]]
];
