var searchData=
[
  ['rangetracker',['RangeTracker',['../classarmnn_1_1_range_tracker.xhtml',1,'armnn']]],
  ['ranklayer',['RankLayer',['../classarmnn_1_1_rank_layer.xhtml',1,'armnn']]],
  ['ranklayerbuilder',['RankLayerBuilder',['../structarmnn_serializer_1_1_rank_layer_builder.xhtml',1,'armnnSerializer']]],
  ['rankqueuedescriptor',['RankQueueDescriptor',['../structarmnn_1_1_rank_queue_descriptor.xhtml',1,'armnn']]],
  ['redirectmemberstoconstantinputsimpl',['RedirectMembersToConstantInputsImpl',['../classarmnn_1_1optimizations_1_1_redirect_members_to_constant_inputs_impl.xhtml',1,'armnn::optimizations']]],
  ['reducedescriptor',['ReduceDescriptor',['../structarmnn_1_1_reduce_descriptor.xhtml',1,'armnn']]],
  ['reducedescriptorbuilder',['ReduceDescriptorBuilder',['../structarmnn_serializer_1_1_reduce_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['reducelayer',['ReduceLayer',['../classarmnn_1_1_reduce_layer.xhtml',1,'armnn']]],
  ['reducelayerbuilder',['ReduceLayerBuilder',['../structarmnn_serializer_1_1_reduce_layer_builder.xhtml',1,'armnnSerializer']]],
  ['reducequeuedescriptor',['ReduceQueueDescriptor',['../structarmnn_1_1_reduce_queue_descriptor.xhtml',1,'armnn']]],
  ['refactivationworkload',['RefActivationWorkload',['../classarmnn_1_1_ref_activation_workload.xhtml',1,'armnn']]],
  ['refargminmaxworkload',['RefArgMinMaxWorkload',['../classarmnn_1_1_ref_arg_min_max_workload.xhtml',1,'armnn']]],
  ['refbackend',['RefBackend',['../classarmnn_1_1_ref_backend.xhtml',1,'armnn']]],
  ['refbaseworkload',['RefBaseWorkload',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20activationqueuedescriptor_20_3e',['RefBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20argminmaxqueuedescriptor_20_3e',['RefBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e',['RefBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e',['RefBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20castqueuedescriptor_20_3e',['RefBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20channelshufflequeuedescriptor_20_3e',['RefBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20comparisonqueuedescriptor_20_3e',['RefBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20concatqueuedescriptor_20_3e',['RefBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20constantqueuedescriptor_20_3e',['RefBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20convolution2dqueuedescriptor_20_3e',['RefBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20convolution3dqueuedescriptor_20_3e',['RefBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20depthtospacequeuedescriptor_20_3e',['RefBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e',['RefBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20dequantizequeuedescriptor_20_3e',['RefBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e',['RefBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e',['RefBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20fillqueuedescriptor_20_3e',['RefBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20floorqueuedescriptor_20_3e',['RefBaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e',['RefBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20gatherndqueuedescriptor_20_3e',['RefBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20gatherqueuedescriptor_20_3e',['RefBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e',['RefBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20l2normalizationqueuedescriptor_20_3e',['RefBaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e',['RefBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e',['RefBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20lstmqueuedescriptor_20_3e',['RefBaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20meanqueuedescriptor_20_3e',['RefBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20normalizationqueuedescriptor_20_3e',['RefBaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20padqueuedescriptor_20_3e',['RefBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20parentdescriptor_20_3e',['RefBaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20pooling2dqueuedescriptor_20_3e',['RefBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20pooling3dqueuedescriptor_20_3e',['RefBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20preluqueuedescriptor_20_3e',['RefBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20qlstmqueuedescriptor_20_3e',['RefBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20quantizequeuedescriptor_20_3e',['RefBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20rankqueuedescriptor_20_3e',['RefBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20reducequeuedescriptor_20_3e',['RefBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20reshapequeuedescriptor_20_3e',['RefBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20resizequeuedescriptor_20_3e',['RefBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20shapequeuedescriptor_20_3e',['RefBaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20slicequeuedescriptor_20_3e',['RefBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20softmaxqueuedescriptor_20_3e',['RefBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e',['RefBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e',['RefBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20splitterqueuedescriptor_20_3e',['RefBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20stackqueuedescriptor_20_3e',['RefBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20stridedslicequeuedescriptor_20_3e',['RefBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e',['RefBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e',['RefBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbatchnormalizationworkload',['RefBatchNormalizationWorkload',['../classarmnn_1_1_ref_batch_normalization_workload.xhtml',1,'armnn']]],
  ['refbatchtospacendworkload',['RefBatchToSpaceNdWorkload',['../classarmnn_1_1_ref_batch_to_space_nd_workload.xhtml',1,'armnn']]],
  ['refcastworkload',['RefCastWorkload',['../classarmnn_1_1_ref_cast_workload.xhtml',1,'armnn']]],
  ['refchannelshuffleworkload',['RefChannelShuffleWorkload',['../classarmnn_1_1_ref_channel_shuffle_workload.xhtml',1,'armnn']]],
  ['refcomparisonworkload',['RefComparisonWorkload',['../classarmnn_1_1_ref_comparison_workload.xhtml',1,'armnn']]],
  ['refconcatworkload',['RefConcatWorkload',['../classarmnn_1_1_ref_concat_workload.xhtml',1,'armnn']]],
  ['refconstantworkload',['RefConstantWorkload',['../classarmnn_1_1_ref_constant_workload.xhtml',1,'armnn']]],
  ['refconvertbf16tofp32workload',['RefConvertBf16ToFp32Workload',['../classarmnn_1_1_ref_convert_bf16_to_fp32_workload.xhtml',1,'armnn']]],
  ['refconvertfp16tofp32workload',['RefConvertFp16ToFp32Workload',['../classarmnn_1_1_ref_convert_fp16_to_fp32_workload.xhtml',1,'armnn']]],
  ['refconvertfp32tobf16workload',['RefConvertFp32ToBf16Workload',['../classarmnn_1_1_ref_convert_fp32_to_bf16_workload.xhtml',1,'armnn']]],
  ['refconvertfp32tofp16workload',['RefConvertFp32ToFp16Workload',['../classarmnn_1_1_ref_convert_fp32_to_fp16_workload.xhtml',1,'armnn']]],
  ['refconvolution2dworkload',['RefConvolution2dWorkload',['../classarmnn_1_1_ref_convolution2d_workload.xhtml',1,'armnn']]],
  ['refconvolution3dworkload',['RefConvolution3dWorkload',['../classarmnn_1_1_ref_convolution3d_workload.xhtml',1,'armnn']]],
  ['refdebugworkload',['RefDebugWorkload',['../classarmnn_1_1_ref_debug_workload.xhtml',1,'armnn']]],
  ['refdepthtospaceworkload',['RefDepthToSpaceWorkload',['../classarmnn_1_1_ref_depth_to_space_workload.xhtml',1,'armnn']]],
  ['refdepthwiseconvolution2dworkload',['RefDepthwiseConvolution2dWorkload',['../classarmnn_1_1_ref_depthwise_convolution2d_workload.xhtml',1,'armnn']]],
  ['refdequantizeworkload',['RefDequantizeWorkload',['../classarmnn_1_1_ref_dequantize_workload.xhtml',1,'armnn']]],
  ['refdetectionpostprocessworkload',['RefDetectionPostProcessWorkload',['../classarmnn_1_1_ref_detection_post_process_workload.xhtml',1,'armnn']]],
  ['refelementwiseunaryworkload',['RefElementwiseUnaryWorkload',['../classarmnn_1_1_ref_elementwise_unary_workload.xhtml',1,'armnn']]],
  ['refelementwiseworkload',['RefElementwiseWorkload',['../classarmnn_1_1_ref_elementwise_workload.xhtml',1,'armnn']]],
  ['reffakequantizationfloat32workload',['RefFakeQuantizationFloat32Workload',['../classarmnn_1_1_ref_fake_quantization_float32_workload.xhtml',1,'armnn']]],
  ['reffillworkload',['RefFillWorkload',['../classarmnn_1_1_ref_fill_workload.xhtml',1,'armnn']]],
  ['reffloorworkload',['RefFloorWorkload',['../classarmnn_1_1_ref_floor_workload.xhtml',1,'armnn']]],
  ['reffullyconnectedworkload',['RefFullyConnectedWorkload',['../classarmnn_1_1_ref_fully_connected_workload.xhtml',1,'armnn']]],
  ['refgatherndworkload',['RefGatherNdWorkload',['../classarmnn_1_1_ref_gather_nd_workload.xhtml',1,'armnn']]],
  ['refgatherworkload',['RefGatherWorkload',['../classarmnn_1_1_ref_gather_workload.xhtml',1,'armnn']]],
  ['refinstancenormalizationworkload',['RefInstanceNormalizationWorkload',['../classarmnn_1_1_ref_instance_normalization_workload.xhtml',1,'armnn']]],
  ['refl2normalizationworkload',['RefL2NormalizationWorkload',['../classarmnn_1_1_ref_l2_normalization_workload.xhtml',1,'armnn']]],
  ['reflayersupport',['RefLayerSupport',['../classarmnn_1_1_ref_layer_support.xhtml',1,'armnn']]],
  ['reflogicalbinaryworkload',['RefLogicalBinaryWorkload',['../classarmnn_1_1_ref_logical_binary_workload.xhtml',1,'armnn']]],
  ['reflogicalunaryworkload',['RefLogicalUnaryWorkload',['../classarmnn_1_1_ref_logical_unary_workload.xhtml',1,'armnn']]],
  ['reflogsoftmaxworkload',['RefLogSoftmaxWorkload',['../classarmnn_1_1_ref_log_softmax_workload.xhtml',1,'armnn']]],
  ['reflstmworkload',['RefLstmWorkload',['../classarmnn_1_1_ref_lstm_workload.xhtml',1,'armnn']]],
  ['refmeanworkload',['RefMeanWorkload',['../classarmnn_1_1_ref_mean_workload.xhtml',1,'armnn']]],
  ['refmemorymanager',['RefMemoryManager',['../classarmnn_1_1_ref_memory_manager.xhtml',1,'armnn']]],
  ['refnormalizationworkload',['RefNormalizationWorkload',['../classarmnn_1_1_ref_normalization_workload.xhtml',1,'armnn']]],
  ['refpadworkload',['RefPadWorkload',['../classarmnn_1_1_ref_pad_workload.xhtml',1,'armnn']]],
  ['refpermuteworkload',['RefPermuteWorkload',['../classarmnn_1_1_ref_permute_workload.xhtml',1,'armnn']]],
  ['refpooling2dworkload',['RefPooling2dWorkload',['../classarmnn_1_1_ref_pooling2d_workload.xhtml',1,'armnn']]],
  ['refpooling3dworkload',['RefPooling3dWorkload',['../classarmnn_1_1_ref_pooling3d_workload.xhtml',1,'armnn']]],
  ['refpreluworkload',['RefPreluWorkload',['../classarmnn_1_1_ref_prelu_workload.xhtml',1,'armnn']]],
  ['refqlstmworkload',['RefQLstmWorkload',['../classarmnn_1_1_ref_q_lstm_workload.xhtml',1,'armnn']]],
  ['refquantizeworkload',['RefQuantizeWorkload',['../classarmnn_1_1_ref_quantize_workload.xhtml',1,'armnn']]],
  ['refrankworkload',['RefRankWorkload',['../structarmnn_1_1_ref_rank_workload.xhtml',1,'armnn']]],
  ['refreduceworkload',['RefReduceWorkload',['../classarmnn_1_1_ref_reduce_workload.xhtml',1,'armnn']]],
  ['refreshapeworkload',['RefReshapeWorkload',['../classarmnn_1_1_ref_reshape_workload.xhtml',1,'armnn']]],
  ['refresizeworkload',['RefResizeWorkload',['../classarmnn_1_1_ref_resize_workload.xhtml',1,'armnn']]],
  ['refshapeworkload',['RefShapeWorkload',['../structarmnn_1_1_ref_shape_workload.xhtml',1,'armnn']]],
  ['refsliceworkload',['RefSliceWorkload',['../classarmnn_1_1_ref_slice_workload.xhtml',1,'armnn']]],
  ['refsoftmaxworkload',['RefSoftmaxWorkload',['../classarmnn_1_1_ref_softmax_workload.xhtml',1,'armnn']]],
  ['refspacetobatchndworkload',['RefSpaceToBatchNdWorkload',['../classarmnn_1_1_ref_space_to_batch_nd_workload.xhtml',1,'armnn']]],
  ['refspacetodepthworkload',['RefSpaceToDepthWorkload',['../classarmnn_1_1_ref_space_to_depth_workload.xhtml',1,'armnn']]],
  ['refsplitterworkload',['RefSplitterWorkload',['../classarmnn_1_1_ref_splitter_workload.xhtml',1,'armnn']]],
  ['refstackworkload',['RefStackWorkload',['../classarmnn_1_1_ref_stack_workload.xhtml',1,'armnn']]],
  ['refstridedsliceworkload',['RefStridedSliceWorkload',['../classarmnn_1_1_ref_strided_slice_workload.xhtml',1,'armnn']]],
  ['reftensorhandle',['RefTensorHandle',['../classarmnn_1_1_ref_tensor_handle.xhtml',1,'armnn']]],
  ['reftensorhandlefactory',['RefTensorHandleFactory',['../classarmnn_1_1_ref_tensor_handle_factory.xhtml',1,'armnn']]],
  ['reftransposeconvolution2dworkload',['RefTransposeConvolution2dWorkload',['../classarmnn_1_1_ref_transpose_convolution2d_workload.xhtml',1,'armnn']]],
  ['reftransposeworkload',['RefTransposeWorkload',['../classarmnn_1_1_ref_transpose_workload.xhtml',1,'armnn']]],
  ['refunidirectionalsequencelstmworkload',['RefUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_ref_unidirectional_sequence_lstm_workload.xhtml',1,'armnn']]],
  ['refworkloadfactory',['RefWorkloadFactory',['../classarmnn_1_1_ref_workload_factory.xhtml',1,'armnn']]],
  ['requestcounterspackethandler',['RequestCountersPacketHandler',['../classarm_1_1pipe_1_1_request_counters_packet_handler.xhtml',1,'arm::pipe']]],
  ['reshapedescriptor',['ReshapeDescriptor',['../structarmnn_1_1_reshape_descriptor.xhtml',1,'armnn']]],
  ['reshapedescriptorbuilder',['ReshapeDescriptorBuilder',['../structarmnn_serializer_1_1_reshape_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['reshapelayer',['ReshapeLayer',['../classarmnn_1_1_reshape_layer.xhtml',1,'armnn']]],
  ['reshapelayerbuilder',['ReshapeLayerBuilder',['../structarmnn_serializer_1_1_reshape_layer_builder.xhtml',1,'armnnSerializer']]],
  ['reshapequeuedescriptor',['ReshapeQueueDescriptor',['../structarmnn_1_1_reshape_queue_descriptor.xhtml',1,'armnn']]],
  ['resizebilineardescriptorbuilder',['ResizeBilinearDescriptorBuilder',['../structarmnn_serializer_1_1_resize_bilinear_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['resizebilinearlayerbuilder',['ResizeBilinearLayerBuilder',['../structarmnn_serializer_1_1_resize_bilinear_layer_builder.xhtml',1,'armnnSerializer']]],
  ['resizedescriptor',['ResizeDescriptor',['../structarmnn_1_1_resize_descriptor.xhtml',1,'armnn']]],
  ['resizedescriptorbuilder',['ResizeDescriptorBuilder',['../structarmnn_serializer_1_1_resize_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['resizelayer',['ResizeLayer',['../classarmnn_1_1_resize_layer.xhtml',1,'armnn']]],
  ['resizelayerbuilder',['ResizeLayerBuilder',['../structarmnn_serializer_1_1_resize_layer_builder.xhtml',1,'armnnSerializer']]],
  ['resizequeuedescriptor',['ResizeQueueDescriptor',['../structarmnn_1_1_resize_queue_descriptor.xhtml',1,'armnn']]],
  ['resolvetypeimpl',['ResolveTypeImpl',['../structarmnn_1_1_resolve_type_impl.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3abfloat16_20_3e',['ResolveTypeImpl&lt; DataType::BFloat16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_b_float16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aboolean_20_3e',['ResolveTypeImpl&lt; DataType::Boolean &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_boolean_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat16_20_3e',['ResolveTypeImpl&lt; DataType::Float16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat32_20_3e',['ResolveTypeImpl&lt; DataType::Float32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float32_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymms8_20_3e',['ResolveTypeImpl&lt; DataType::QAsymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_s8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymmu8_20_3e',['ResolveTypeImpl&lt; DataType::QAsymmU8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_u8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms16_20_3e',['ResolveTypeImpl&lt; DataType::QSymmS16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms8_20_3e',['ResolveTypeImpl&lt; DataType::QSymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned32_20_3e',['ResolveTypeImpl&lt; DataType::Signed32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed32_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned64_20_3e',['ResolveTypeImpl&lt; DataType::Signed64 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed64_01_4.xhtml',1,'armnn']]],
  ['rsqrt',['rsqrt',['../structarmnn_1_1rsqrt.xhtml',1,'armnn']]],
  ['rsqrtlayer',['RsqrtLayer',['../classarmnn_1_1_rsqrt_layer.xhtml',1,'armnn']]],
  ['rsqrtlayerbuilder',['RsqrtLayerBuilder',['../structarmnn_serializer_1_1_rsqrt_layer_builder.xhtml',1,'armnnSerializer']]],
  ['rsqrtqueuedescriptor',['RsqrtQueueDescriptor',['../structarmnn_1_1_rsqrt_queue_descriptor.xhtml',1,'armnn']]],
  ['rule',['Rule',['../structarmnn_1_1_rule.xhtml',1,'armnn']]],
  ['runtimeexception',['RuntimeException',['../classarmnn_1_1_runtime_exception.xhtml',1,'armnn']]],
  ['runtimeimpl',['RuntimeImpl',['../structarmnn_1_1_runtime_impl.xhtml',1,'armnn']]]
];
