Arm NN: GpuFsaTensorHandleFactory Class Reference
GpuFsaTensorHandleFactory Class Reference
#include <GpuFsaTensorHandleFactory.hpp>
Public Member Functions
GpuFsaTensorHandleFactory (std::shared_ptr< GpuFsaMemoryManager > mgr)
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const override
Utility Functions for backends which require TensorHandles to have unmanaged memory.
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override
const FactoryId & GetId () const override
bool SupportsSubTensors () const override
MemorySourceFlags GetExportFlags () const override
MemorySourceFlags GetImportFlags () const override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual bool SupportsInPlaceComputation () const
virtual bool SupportsMapUnmap () const
virtual std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass)
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Detailed Description
Definition at line 16 of file GpuFsaTensorHandleFactory.hpp.
Constructor & Destructor Documentation
GpuFsaTensorHandleFactory()
GpuFsaTensorHandleFactory (std::shared_ptr< GpuFsaMemoryManager > mgr) inline
Definition at line 20 of file GpuFsaTensorHandleFactory.hpp.
     : m_MemoryManager(mgr)
     {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 14 of file GpuFsaTensorHandleFactory.cpp.
 {
     arm_compute::Coordinates coords;
     arm_compute::TensorShape shape = armcomputetensorutils::BuildArmComputeTensorShape(subTensorShape);
     coords.set_num_dimensions(subTensorShape.GetNumDimensions());
     for (unsigned int i = 0; i < subTensorShape.GetNumDimensions(); ++i)
     {
         // Arm compute indexes tensor coords in reverse order.
         unsigned int revertedIndex = subTensorShape.GetNumDimensions() - i - 1;
         coords.set(i, armnn::numeric_cast<int>(subTensorOrigin[revertedIndex]));
     }
     const arm_compute::TensorShape parentShape = armcomputetensorutils::BuildArmComputeTensorShape(parent.GetShape());
     // In order for ACL to support subtensors the concat axis cannot be on x or y and the values of x and y
     // must match the parent shapes
     if (coords.x() != 0 || coords.y() != 0)
     {
         return nullptr;
     }
     if ((parentShape.x() != shape.x()) || (parentShape.y() != shape.y()))
     {
         return nullptr;
     }
     if (!::arm_compute::error_on_invalid_subtensor(__func__, __FILE__, __LINE__, parentShape, coords, shape))
     {
         return nullptr;
     }
     return std::make_unique<GpuFsaSubTensorHandle>(PolymorphicDowncast<IClTensorHandle*>(&parent), shape, coords);
 }
CreateTensorHandle() [1/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 50 of file GpuFsaTensorHandleFactory.cpp.
 {
     return GpuFsaTensorHandleFactory::CreateTensorHandle(tensorInfo, true);
 }
Referenced by GpuFsaTensorHandleFactory::CreateTensorHandle().
CreateTensorHandle() [2/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged) const override virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented from ITensorHandleFactory.
Definition at line 61 of file GpuFsaTensorHandleFactory.cpp.
 {
     std::unique_ptr<GpuFsaTensorHandle> tensorHandle = std::make_unique<GpuFsaTensorHandle>(tensorInfo);
     if (!IsMemoryManaged)
     {
         ARMNN_LOG(warning) << "GpuFsaTensorHandleFactory only has support for memory managed.";
     }
     tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     return tensorHandle;
 }
References ARMNN_LOG, and armnn::warning.
CreateTensorHandle() [3/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 55 of file GpuFsaTensorHandleFactory.cpp.
 {
     return GpuFsaTensorHandleFactory::CreateTensorHandle(tensorInfo, dataLayout, true);
 }
References GpuFsaTensorHandleFactory::CreateTensorHandle().
CreateTensorHandle() [4/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 73 of file GpuFsaTensorHandleFactory.cpp.
 {
     std::unique_ptr<GpuFsaTensorHandle> tensorHandle = std::make_unique<GpuFsaTensorHandle>(tensorInfo, dataLayout);
     if (!IsMemoryManaged)
     {
         ARMNN_LOG(warning) << "GpuFsaTensorHandleFactory only has support for memory managed.";
     }
     tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     return tensorHandle;
 }
References ARMNN_LOG, and armnn::warning.
GetExportFlags()
MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 102 of file GpuFsaTensorHandleFactory.cpp.
 {
     return MemorySourceFlags(MemorySource::Undefined);
 }
References armnn::Undefined.
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 92 of file GpuFsaTensorHandleFactory.cpp.
 {
     return GetIdStatic();
 }
References GpuFsaTensorHandleFactory::GetIdStatic().
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 86 of file GpuFsaTensorHandleFactory.cpp.
 {
     static const FactoryId s_Id(GpuFsaTensorHandleFactoryId());
     return s_Id;
 }
References armnn::GpuFsaTensorHandleFactoryId().
Referenced by GpuFsaBackend::GetHandleFactoryPreferences(), and GpuFsaTensorHandleFactory::GetId().
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 107 of file GpuFsaTensorHandleFactory.cpp.
 {
     return MemorySourceFlags(MemorySource::Undefined);
 }
References armnn::Undefined.
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 97 of file GpuFsaTensorHandleFactory.cpp.
 {
     return true;
 }
The documentation for this class was generated from the following files:
src/backends/gpuFsa/GpuFsaTensorHandleFactory.hpp
src/backends/gpuFsa/GpuFsaTensorHandleFactory.cpp