Arm NN: GpuFsaLayerSupport Class Reference
GpuFsaLayerSupport Class Reference
#include <GpuFsaLayerSupport.hpp>
Public Member Functions
bool IsLayerSupported (const LayerType &type, const std::vector< TensorInfo > &infos, const BaseDescriptor &descriptor, const Optional< LstmInputParamsInfo > &lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > &, Optional< std::string & > reasonIfUnsupported) const override
Default implementation of the ILayerSupport interface, Backends should implement this as a switch statement for each of their LayerTypes calling their specific backend implementation of IsXXXLayerSupported.
Additional Inherited Members
Protected Member Functions inherited from ILayerSupport
ILayerSupport ()
virtual ~ILayerSupport ()
Detailed Description
Definition at line 13 of file GpuFsaLayerSupport.hpp.
Member Function Documentation
IsLayerSupported()
bool IsLayerSupported (const LayerType & type, const std::vector< TensorInfo > & infos, const BaseDescriptor & descriptor, const Optional< LstmInputParamsInfo > & lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > & quantizedLstmParamsInfo, Optional< std::string & > reasonIfUnsupported) const override virtual
Default implementation of the ILayerSupport interface, Backends should implement this as a switch statement for each of their LayerTypes calling their specific backend implementation of IsXXXLayerSupported.
Reimplemented from ILayerSupport.
Definition at line 71 of file GpuFsaLayerSupport.cpp.
 {
     IgnoreUnused(lstmParamsInfo);
     IgnoreUnused(quantizedLstmInputParamsInfo);
     switch (type)
     {
         case LayerType::Activation:
         {
             if (infos.size() != 2)
             {
                 throw InvalidArgumentException("Invalid number of Activation TensorInfos. "
                                                "TensorInfos should be of format: {input, output}.");
             }
             auto desc = PolymorphicDowncast<const ActivationDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaActivationValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         *desc);
         }
         case LayerType::BatchMatMul:
         {
             if (infos.size() != 3)
             {
                 throw InvalidArgumentException("Invalid number of BatchMatMul TensorInfos. "
                                                "TensorInfos should be of format: {input0, input1 output}.");
             }
             auto desc = PolymorphicDowncast<const BatchMatMulDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaBatchMatMulValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         infos[1],
                                         *desc);
         }
         case LayerType::Cast:
         {
             if (infos.size() != 2)
             {
                 throw InvalidArgumentException("Invalid number of cast TensorInfos. "
                                                "TensorInfos should be of format: {input, output}.");
             }
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaCastValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         infos[1]);
         }
         case LayerType::Convolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = PolymorphicDowncast<const Convolution2dDescriptor*>(&descriptor);
             if (infos[3] == TensorInfo())
             {
                 FORWARD_LAYER_VALIDATE_FUNC(GpuFsaConvolution2dValidate,
                                             reasonIfUnsupported,
                                             infos[0],
                                             *desc,
                                             infos[2],
                                             EmptyOptional());
             }
             else
             {
                 FORWARD_LAYER_VALIDATE_FUNC(GpuFsaConvolution2dValidate,
                                             reasonIfUnsupported,
                                             infos[0],
                                             *desc,
                                             infos[2],
                                             infos[3]);
             }
         }
         case LayerType::DepthwiseConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of DepthwiseConvolution2dDescriptor TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = PolymorphicDowncast<const DepthwiseConvolution2dDescriptor*>(&descriptor);
             if (infos[3] == TensorInfo())
             {
                 FORWARD_LAYER_VALIDATE_FUNC(GpuFsaDepthwiseConvolution2dValidate,
                                             reasonIfUnsupported,
                                             infos[0],
                                             *desc,
                                             infos[2],
                                             EmptyOptional());
             }
             else
             {
                 FORWARD_LAYER_VALIDATE_FUNC(GpuFsaDepthwiseConvolution2dValidate,
                                             reasonIfUnsupported,
                                             infos[0],
                                             *desc,
                                             infos[2],
                                             infos[3]);
             }
         }
         case LayerType::ElementwiseBinary:
         {
             if (infos.size() != 3)
             {
                 throw InvalidArgumentException("Invalid number of ElementwiseBinary TensorInfos. "
                                                "TensorInfos should be of format: {input0, input1, output}.");
             }
             auto desc = PolymorphicDowncast<const ElementwiseBinaryDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaElementwiseBinaryValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         infos[1],
                                         *desc);
         }
         case LayerType::Pooling2d:
         {
             if (infos.size() != 2)
             {
                 throw InvalidArgumentException("Invalid number of Pooling2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output}.");
             }
             auto desc = PolymorphicDowncast<const Pooling2dDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaPooling2dValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         *desc);
         }
         case LayerType::Reshape:
         {
             if (infos.size() != 2)
             {
                 throw InvalidArgumentException("Invalid number of Reshape TensorInfos. "
                                                "TensorInfos should be of format: { input, output }.");
             }
             auto desc = PolymorphicDowncast<const ReshapeDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaReshapeValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         *desc);
         }
         case LayerType::Resize:
         {
             if (infos.size() != 2)
             {
                 throw InvalidArgumentException("Invalid number of Resize TensorInfos. "
                                                "TensorInfos should be of format: {input, output}.");
             }
             auto desc = PolymorphicDowncast<const ResizeDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaResizeValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         *desc);
         }
         case LayerType::Softmax:
         {
             if (infos.size() != 2)
             {
                 throw InvalidArgumentException("Invalid number of Softmax TensorInfos. "
                                                "TensorInfos should be of format: {input, output}.");
             }
             auto desc = PolymorphicDowncast<const SoftmaxDescriptor*>(&descriptor);
             FORWARD_LAYER_VALIDATE_FUNC(GpuFsaSoftmaxValidate,
                                         reasonIfUnsupported,
                                         infos[0],
                                         infos[1],
                                         *desc);
         }
         case LayerType::Constant:
         case LayerType::Input:
         case LayerType::Output:
             return IsGpuFsaBackendSupported(reasonIfUnsupported, infos[0]);
         default:
             // Layers not supported in the GpuFsa backend.
             return false;
     }
 }
References armnn::Activation, armnn::BatchMatMul, armnn::Cast, armnn::Constant, armnn::Convolution2d, armnn::DepthwiseConvolution2d, armnn::ElementwiseBinary, FORWARD_LAYER_VALIDATE_FUNC, armnn::GpuFsaActivationValidate(), armnn::GpuFsaBatchMatMulValidate(), armnn::GpuFsaCastValidate(), armnn::GpuFsaConvolution2dValidate(), armnn::GpuFsaDepthwiseConvolution2dValidate(), armnn::GpuFsaElementwiseBinaryValidate(), armnn::GpuFsaPooling2dValidate(), armnn::GpuFsaReshapeValidate(), armnn::GpuFsaResizeValidate(), armnn::GpuFsaSoftmaxValidate(), armnn::IgnoreUnused(), armnn::Input, armnn::IsGpuFsaBackendSupported(), armnn::Output, armnn::Pooling2d, armnn::Reshape, armnn::Resize, and armnn::Softmax.
The documentation for this class was generated from the following files:
src/backends/gpuFsa/GpuFsaLayerSupport.hpp
src/backends/gpuFsa/GpuFsaLayerSupport.cpp