Arm NN: JsonUtils Class Reference
JsonUtils Class Reference
#include <JsonUtils.hpp>
Public Member Functions
JsonUtils (std::ostream &outputStream)
void PrintTabs ()
void DecrementNumberOfTabs ()
void IncrementNumberOfTabs ()
void PrintNewLine ()
void PrintFooter ()
void PrintHeader ()
void PrintArmNNHeader ()
void PrintSeparator ()
Detailed Description
Definition at line 16 of file JsonUtils.hpp.
Constructor & Destructor Documentation
JsonUtils()
JsonUtils (std::ostream & outputStream) inline
Definition at line 19 of file JsonUtils.hpp.
         : m_NumTabs(0), m_OutputStream(outputStream)
     {}
Member Function Documentation
DecrementNumberOfTabs()
void DecrementNumberOfTabs () inline
Definition at line 32 of file JsonUtils.hpp.
     {
         if ( m_NumTabs == 0 )
         {
             return;
         }
         --m_NumTabs;
     }
Referenced by JsonUtils::PrintFooter(), JsonPrinter::PrintJsonChildObject(), and JsonPrinter::PrintMeasurementsList().
IncrementNumberOfTabs()
void IncrementNumberOfTabs () inline
Definition at line 41 of file JsonUtils.hpp.
     {
         ++m_NumTabs;
     }
Referenced by JsonUtils::PrintArmNNHeader(), JsonUtils::PrintHeader(), JsonPrinter::PrintJsonChildObject(), JsonPrinter::PrintLabel(), and JsonPrinter::PrintMeasurementsList().
PrintArmNNHeader()
void PrintArmNNHeader () inline
Definition at line 64 of file JsonUtils.hpp.
     {
         PrintTabs();
         m_OutputStream << R"("ArmNN": {)" << std::endl;
         IncrementNumberOfTabs();
     }
References JsonUtils::IncrementNumberOfTabs(), and JsonUtils::PrintTabs().
Referenced by ProfilerImpl::Print().
PrintFooter()
void PrintFooter () inline
Definition at line 51 of file JsonUtils.hpp.
     {
         DecrementNumberOfTabs();
         PrintTabs();
         m_OutputStream << "}";
     }
References JsonUtils::DecrementNumberOfTabs(), and JsonUtils::PrintTabs().
Referenced by ProfilingDetails::AddDetailsToString(), ProfilerImpl::Print(), and JsonPrinter::PrintJsonChildObject().
PrintHeader()
void PrintHeader () inline
Definition at line 58 of file JsonUtils.hpp.
     {
         m_OutputStream << "{" << std::endl;
         IncrementNumberOfTabs();
     }
References JsonUtils::IncrementNumberOfTabs().
Referenced by ProfilingDetails::AddDetailsToString(), and ProfilerImpl::Print().
PrintNewLine()
void PrintNewLine () inline
Definition at line 46 of file JsonUtils.hpp.
     {
         m_OutputStream << std::endl;
     }
Referenced by ProfilingDetails::AddDetailsToString(), ProfilerImpl::Print(), and JsonPrinter::PrintJsonChildObject().
PrintSeparator()
void PrintSeparator () inline
Definition at line 70 of file JsonUtils.hpp.
     {
         m_OutputStream << ",";
     }
Referenced by ProfilingDetails::AddDetailsToString(), ProfilerImpl::Print(), and JsonPrinter::PrintJsonChildObject().
PrintTabs()
void PrintTabs () inline
Definition at line 23 of file JsonUtils.hpp.
     {
         unsigned int numTabs = m_NumTabs;
         while ( numTabs-- > 0 )
         {
             m_OutputStream << "\t";
         }
     }
Referenced by ProfilingDetails::AddDetailsToString(), JsonUtils::PrintArmNNHeader(), JsonUtils::PrintFooter(), JsonPrinter::PrintGuid(), JsonPrinter::PrintJsonChildObject(), JsonPrinter::PrintLabel(), JsonPrinter::PrintMeasurementsList(), JsonPrinter::PrintType(), and JsonPrinter::PrintUnit().
The documentation for this class was generated from the following file:
src/armnn/JsonUtils.hpp