Arm NN: IBackend Class Reference
IBackend Class Reference abstract
Each backend should implement an IBackend.
#include <Types.hpp>
Public Member Functions
virtual const BackendId & GetId () const =0
Protected Member Functions
IBackend ()
virtual ~IBackend ()
Detailed Description
Each backend should implement an IBackend.
Definition at line 272 of file Types.hpp.
Constructor & Destructor Documentation
IBackend()
IBackend () inline protected
Definition at line 275 of file Types.hpp.
 {}
~IBackend()
virtual ~IBackend () inline protected virtual
Definition at line 276 of file Types.hpp.
 {}
Member Function Documentation
GetId()
virtual const BackendId& GetId () const pure virtual
Implemented in GpuFsaBackend, RefBackend, ClBackend, NeonBackend, and TosaRefBackend.
Referenced by IBackendInternal::CreateWorkloadFactory(), IBackendInternal::GetLayerSupport(), and IBackendInternal::UseCustomMemoryAllocator().
The documentation for this class was generated from the following file:
include/armnn/Types.hpp