Arm NN: BackendOptions::Var Class Reference
BackendOptions::Var Class Reference
Very basic type safe variant.
#include <BackendOptions.hpp>
Public Member Functions
Var (int i)
Constructors.
Var (unsigned int u)
Var (float f)
Var (bool b)
Var (const char *s)
Var (std::string s)
template<typename DisallowedType >
Var (DisallowedType)
Disallow implicit conversions from types not explicitly allowed below.
Var (const Var &other)
Copy Construct.
Var & operator= (const Var &other)
Copy operator.
bool IsBool () const
Type getters.
bool IsInt () const
bool IsUnsignedInt () const
bool IsFloat () const
bool IsString () const
bool AsBool () const
Value getters.
int AsInt () const
unsigned int AsUnsignedInt () const
float AsFloat () const
std::string AsString () const
std::string ToString ()
~Var ()
Destructor.
Detailed Description
Very basic type safe variant.
Definition at line 38 of file BackendOptions.hpp.
Constructor & Destructor Documentation
Var() [1/8]
Var (int i) inline explicit
Constructors.
Definition at line 43 of file BackendOptions.hpp.
 : m_Vals(i), m_Type(VarTypes::Integer) {};
Var() [2/8]
Var (unsigned int u) inline explicit
Definition at line 44 of file BackendOptions.hpp.
 : m_Vals(u), m_Type(VarTypes::UnsignedInteger) {};
Var() [3/8]
Var (float f) inline explicit
Definition at line 45 of file BackendOptions.hpp.
 : m_Vals(f), m_Type(VarTypes::Float) {};
Var() [4/8]
Var (bool b) inline explicit
Definition at line 46 of file BackendOptions.hpp.
 : m_Vals(b), m_Type(VarTypes::Boolean) {};
References armnn::Boolean.
Var() [5/8]
Var (const char * s) inline explicit
Definition at line 47 of file BackendOptions.hpp.
 : m_Vals(s), m_Type(VarTypes::String) {};
Var() [6/8]
Var (std::string s) inline explicit
Definition at line 48 of file BackendOptions.hpp.
 : m_Vals(s), m_Type(VarTypes::String) {};
Var() [7/8]
Var (DisallowedType) inline
Disallow implicit conversions from types not explicitly allowed below.
Definition at line 52 of file BackendOptions.hpp.
         {
             static_assert(CheckAllowed<DisallowedType>::value, "Type is not allowed for Var<DisallowedType>.");
             assert(false && "Unreachable code");
         }
Var() [8/8]
Var (const Var & other) inline
Copy Construct.
Definition at line 59 of file BackendOptions.hpp.
             : m_Type(other.m_Type)
         {
             switch(m_Type)
             {
                 case VarTypes::String:
                 {
                     new (&m_Vals.s) std::string(other.m_Vals.s);
                     break;
                 }
                 default:
                 {
                     DoOp(other, [](auto& a, auto& b)
{
                             a = b;
                         });
                     break;
                 }
             }
         }
~Var()
~Var () inline
Destructor.
Definition at line 138 of file BackendOptions.hpp.
         {
             DoOp(*this, [this](auto& a, auto&)
                 {
                     Destruct(a);
                 });
         }
Member Function Documentation
AsBool()
bool AsBool () const inline
Value getters.
Definition at line 119 of file BackendOptions.hpp.
 { assert(IsBool()); return m_Vals.b; }
References BackendOptions::Var::IsBool().
Referenced by armnn::HasMatchingCapability(), armnn::ParseBooleanBackendOption(), and BackendOptions::Var::ToString().
AsFloat()
float AsFloat () const inline
Definition at line 122 of file BackendOptions.hpp.
 { assert(IsFloat()); return m_Vals.f; }
References BackendOptions::Var::IsFloat().
Referenced by armnn::HasMatchingCapability(), and BackendOptions::Var::ToString().
AsInt()
int AsInt () const inline
Definition at line 120 of file BackendOptions.hpp.
 { assert(IsInt()); return m_Vals.i; }
References BackendOptions::Var::IsInt().
Referenced by armnn::HasMatchingCapability(), armnn::ParseIntBackendOption(), armnn::ParseTuningLevel(), and BackendOptions::Var::ToString().
AsString()
std::string AsString () const inline
Definition at line 123 of file BackendOptions.hpp.
 { assert(IsString()); return m_Vals.s; }
References BackendOptions::Var::IsString().
Referenced by armnn::HasMatchingCapability(), armnn::ParseStringBackendOption(), and BackendOptions::Var::ToString().
AsUnsignedInt()
unsigned int AsUnsignedInt () const inline
Definition at line 121 of file BackendOptions.hpp.
 { assert(IsUnsignedInt()); return m_Vals.u; }
References BackendOptions::Var::IsUnsignedInt().
Referenced by armnn::HasMatchingCapability(), and BackendOptions::Var::ToString().
IsBool()
bool IsBool () const inline
Type getters.
Definition at line 112 of file BackendOptions.hpp.
 { return m_Type == VarTypes::Boolean; }
Referenced by BackendOptions::Var::AsBool(), armnn::HasMatchingCapability(), armnn::ParseBooleanBackendOption(), and BackendOptions::Var::ToString().
IsFloat()
bool IsFloat () const inline
Definition at line 115 of file BackendOptions.hpp.
 { return m_Type == VarTypes::Float; }
Referenced by BackendOptions::Var::AsFloat(), armnn::HasMatchingCapability(), and BackendOptions::Var::ToString().
IsInt()
bool IsInt () const inline
Definition at line 113 of file BackendOptions.hpp.
 { return m_Type == VarTypes::Integer; }
Referenced by BackendOptions::Var::AsInt(), armnn::HasMatchingCapability(), armnn::ParseIntBackendOption(), armnn::ParseTuningLevel(), and BackendOptions::Var::ToString().
IsString()
bool IsString () const inline
Definition at line 116 of file BackendOptions.hpp.
 { return m_Type == VarTypes::String; }
Referenced by BackendOptions::Var::AsString(), armnn::HasMatchingCapability(), armnn::ParseStringBackendOption(), and BackendOptions::Var::ToString().
IsUnsignedInt()
bool IsUnsignedInt () const inline
Definition at line 114 of file BackendOptions.hpp.
 { return m_Type == VarTypes::UnsignedInteger; }
Referenced by BackendOptions::Var::AsUnsignedInt(), armnn::HasMatchingCapability(), and BackendOptions::Var::ToString().
operator=()
Var& operator= (const Var & other) inline
Copy operator.
Definition at line 81 of file BackendOptions.hpp.
         {
             // Destroy existing string
             if (m_Type == VarTypes::String)
             {
                 Destruct(m_Vals.s);
             }
             m_Type = other.m_Type;
             switch(m_Type)
             {
                 case VarTypes::String:
                 {
                     new (&m_Vals.s) std::string(other.m_Vals.s);
                     break;
                 }
                 default:
                 {
                     DoOp(other, [](auto& a, auto& b)
{
                             a = b;
                         });
                     break;
                 }
             }
             return *this;
         };
ToString()
std::string ToString () inline
Definition at line 124 of file BackendOptions.hpp.
         {
             if (IsBool()) { return AsBool() ? "true" : "false"; }
             else if (IsInt()) { return std::to_string(AsInt()); }
             else if (IsUnsignedInt()) { return std::to_string(AsUnsignedInt()); }
             else if (IsFloat()) { return std::to_string(AsFloat()); }
             else if (IsString()) { return AsString(); }
             else
             {
                 throw armnn::InvalidArgumentException("Unknown data type for string conversion");
             }
         }
References BackendOptions::Var::AsBool(), BackendOptions::Var::AsFloat(), BackendOptions::Var::AsInt(), BackendOptions::Var::AsString(), BackendOptions::Var::AsUnsignedInt(), BackendOptions::Var::IsBool(), BackendOptions::Var::IsFloat(), BackendOptions::Var::IsInt(), BackendOptions::Var::IsString(), and BackendOptions::Var::IsUnsignedInt().
Referenced by OptimizerOptions::ToString(), and OptimizerOptionsOpaque::ToString().
The documentation for this class was generated from the following file:
include/armnn/BackendOptions.hpp