Arm NN: TosaRefMemoryManager Class Reference
TosaRefMemoryManager Class Reference
#include <TosaRefMemoryManager.hpp>
Classes
class Pool
Public Member Functions
TosaRefMemoryManager ()
virtual ~TosaRefMemoryManager ()
Pool * Manage (unsigned int numBytes)
void Allocate (Pool *pool)
void * GetPointer (Pool *pool)
void Acquire () override
void Release () override
Public Member Functions inherited from IMemoryManager
virtual ~IMemoryManager ()
Additional Inherited Members
Protected Member Functions inherited from IMemoryManager
IMemoryManager ()
Detailed Description
Definition at line 16 of file TosaRefMemoryManager.hpp.
Constructor & Destructor Documentation
TosaRefMemoryManager()
TosaRefMemoryManager ()
Definition at line 13 of file TosaRefMemoryManager.cpp.
 {}
~TosaRefMemoryManager()
~TosaRefMemoryManager () virtual
Definition at line 16 of file TosaRefMemoryManager.cpp.
 {}
Member Function Documentation
Acquire()
void Acquire () override virtual
Implements IMemoryManager.
Definition at line 46 of file TosaRefMemoryManager.cpp.
 {
     for (Pool &pool: m_Pools)
     {
          pool.Acquire();
     }
 }
Allocate()
void Allocate (TosaRefMemoryManager::Pool * pool)
Definition at line 35 of file TosaRefMemoryManager.cpp.
 {
     ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(pool, "Null memory manager passed to TosaRefMemoryManager.");
     m_FreePools.push_back(pool);
 }
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE.
GetPointer()
void * GetPointer (TosaRefMemoryManager::Pool * pool)
Definition at line 41 of file TosaRefMemoryManager.cpp.
 {
     return pool->GetPointer();
 }
References TosaRefMemoryManager::Pool::GetPointer().
Manage()
TosaRefMemoryManager::Pool * Manage (unsigned int numBytes)
Definition at line 19 of file TosaRefMemoryManager.cpp.
 {
     if (!m_FreePools.empty())
     {
         Pool* res = m_FreePools.back();
         m_FreePools.pop_back();
         res->Reserve(numBytes);
         return res;
     }
     else
     {
         m_Pools.push_front(Pool(numBytes));
         return &m_Pools.front();
     }
 }
References TosaRefMemoryManager::Pool::Reserve().
Release()
void Release () override virtual
Implements IMemoryManager.
Definition at line 54 of file TosaRefMemoryManager.cpp.
 {
     for (Pool &pool: m_Pools)
     {
          pool.Release();
     }
 }
Referenced by TosaRefMemoryManager::Pool::~Pool().
The documentation for this class was generated from the following files:
src/backends/tosaReference/TosaRefMemoryManager.hpp
src/backends/tosaReference/TosaRefMemoryManager.cpp