Arm NN: GpuFsaContextControl Class Reference
GpuFsaContextControl Class Reference
#include <GpuFsaContextControl.hpp>
Public Member Functions
GpuFsaContextControl (arm_compute::CLTuner *=nullptr, arm_compute::CLGEMMHeuristicsHandle *=nullptr, bool profilingEnabled=false)
virtual ~GpuFsaContextControl ()
void LoadOpenClRuntime ()
void UnloadOpenClRuntime ()
void ClearClCache ()
Detailed Description
Definition at line 13 of file GpuFsaContextControl.hpp.
Constructor & Destructor Documentation
GpuFsaContextControl()
GpuFsaContextControl (arm_compute::CLTuner * tuner = nullptr, arm_compute::CLGEMMHeuristicsHandle * heuristicsHandle = nullptr, bool profilingEnabled = false)
Definition at line 27 of file GpuFsaContextControl.cpp.
     : m_Tuner(tuner)
     , m_HeuristicsHandle(heuristicsHandle)
     , m_ProfilingEnabled(profilingEnabled)
 {
     try
     {
         std::vector<cl::Platform> platforms;
         cl::Platform::get(&platforms);
         // Selects default platform for the first element.
         cl::Platform::setDefault(platforms[0]);
         std::vector<cl::Device> devices;
         platforms[0].getDevices(CL_DEVICE_TYPE_GPU, &devices);
         // Selects default device for the first element.
         cl::Device::setDefault(devices[0]);
     }
     catch (const cl::Error& clError)
     {
         throw ClRuntimeUnavailableException(fmt::format(
             "Could not initialize the CL runtime. Error description: {0}. CL error code: {1}",
             clError.what(), clError.err()));
     }
     // Removes the use of global CL context.
     cl::Context::setDefault(cl::Context{});
     if (cl::Context::getDefault()() != NULL)
     {
         throw armnn::Exception("GpuFsaContextControl: Unable to remove the global CL context");
     }
     // Removes the use of global CL command queue.
     cl::CommandQueue::setDefault(cl::CommandQueue{});
     if (cl::CommandQueue::getDefault()() != NULL)
     {
         throw armnn::Exception("GpuFsaContextControl: Unable to remove the global CL command queue");
     }
     // Always load the OpenCL runtime.
     LoadOpenClRuntime();
 }
References GpuFsaContextControl::LoadOpenClRuntime().
~GpuFsaContextControl()
~GpuFsaContextControl () virtual
Definition at line 73 of file GpuFsaContextControl.cpp.
 {
     // Load the OpencCL runtime without the tuned parameters to free the memory for them.
     try
     {
         UnloadOpenClRuntime();
     }
     catch (const cl::Error& clError)
     {
         // This should not happen, it is ignored if it does.
         // Coverity fix: BOOST_LOG_TRIVIAL (previously used here to report the error) may throw an
         // exception of type std::length_error.
         // Using stderr instead in this context as there is no point in nesting try-catch blocks here.
         std::cerr << "A CL error occurred unloading the runtime tuner parameters: "
                   << clError.what() << ". CL error code is: " << clError.err() << std::endl;
     }
 }
References GpuFsaContextControl::UnloadOpenClRuntime().
Member Function Documentation
ClearClCache()
void ClearClCache ()
Definition at line 164 of file GpuFsaContextControl.cpp.
 {
     DoLoadOpenClRuntime(true);
 }
LoadOpenClRuntime()
void LoadOpenClRuntime ()
Definition at line 92 of file GpuFsaContextControl.cpp.
 {
     DoLoadOpenClRuntime(true);
 }
Referenced by GpuFsaContextControl::GpuFsaContextControl().
UnloadOpenClRuntime()
void UnloadOpenClRuntime ()
Definition at line 97 of file GpuFsaContextControl.cpp.
 {
     DoLoadOpenClRuntime(false);
 }
Referenced by GpuFsaContextControl::~GpuFsaContextControl().
The documentation for this class was generated from the following files:
src/backends/gpuFsa/GpuFsaContextControl.hpp
src/backends/gpuFsa/GpuFsaContextControl.cpp