Arm NN: IGpuAccTunedParameters Class Reference
IGpuAccTunedParameters Class Reference abstract
Manages a set of GpuAcc parameters which have been tuned for maximum performance.
#include <IRuntime.hpp>
Public Types
enum Mode { UseTunedParameters, UpdateTunedParameters }
enum TuningLevel { Rapid = 1, Normal = 2, Exhaustive = 3 }
Public Member Functions
virtual void Load (const char *filename)=0
Loads an existing set of tuned parameters from the given file.
virtual void Save (const char *filename) const =0
Saves the current set of tuned parameters to the given file.
Static Public Member Functions
static void Destroy (IGpuAccTunedParameters *params)
static IGpuAccTunedParameters * CreateRaw (Mode mode, TuningLevel tunerMode)
Creates an IClTunedParameters with the given mode.
static IGpuAccTunedParametersPtr Create (Mode mode, TuningLevel tunerMode)
Protected Member Functions
virtual ~IGpuAccTunedParameters ()
Detailed Description
Manages a set of GpuAcc parameters which have been tuned for maximum performance.
Passes an instance of this object to the IRuntime::Create() method (via IRuntime::CreationOptions) to use it for all GPU workload execution.
Can be created in two modes:
In UseTunedParameters mode, the parameters stored in this object are used to execute GPU workloads.
In UpdateTunedParameters mode, additionally, whenever a GPU workload is executed for the first time, the optimum parameters will be found and stored in this object. WARNING - This tuning can be slow.
The parameters can be loaded from and saved to a file so that you can first run a slow initial read-write execution, save the parameters for later and then run fast read-only executions using the optimised parameters.
Definition at line 314 of file IRuntime.hpp.
Member Enumeration Documentation
Mode
enum Mode strong
Enumerator
UseTunedParameters
UpdateTunedParameters
Definition at line 317 of file IRuntime.hpp.
     {
         UseTunedParameters,
         UpdateTunedParameters
     };
TuningLevel
enum TuningLevel strong
Enumerator
Rapid
Normal
Exhaustive
Definition at line 323 of file IRuntime.hpp.
     {
         Rapid = 1,
         Normal = 2,
         Exhaustive = 3
     };
Constructor & Destructor Documentation
~IGpuAccTunedParameters()
virtual ~IGpuAccTunedParameters () inline protected virtual
Definition at line 346 of file IRuntime.hpp.
 {};
Member Function Documentation
Create()
IGpuAccTunedParametersPtr Create (IGpuAccTunedParameters::Mode mode, IGpuAccTunedParameters::TuningLevel tuningLevel) static
Definition at line 17 of file ArmComputeTuningUtils.cpp.
 {
     return IGpuAccTunedParametersPtr(CreateRaw(mode, tuningLevel), &IGpuAccTunedParameters::Destroy);
 }
References IGpuAccTunedParameters::CreateRaw(), and IGpuAccTunedParameters::Destroy().
Referenced by ArmnnDevice::ArmnnDevice().
CreateRaw()
IGpuAccTunedParameters * CreateRaw (IGpuAccTunedParameters::Mode mode, IGpuAccTunedParameters::TuningLevel tuningLevel) static
Creates an IClTunedParameters with the given mode.
Definition at line 11 of file ArmComputeTuningUtils.cpp.
 {
     return new ClTunedParameters(mode, tuningLevel);
 }
Referenced by IGpuAccTunedParameters::Create().
Destroy()
void Destroy (IGpuAccTunedParameters * params) static
Definition at line 23 of file ArmComputeTuningUtils.cpp.
 {
     delete params;
 }
Referenced by IGpuAccTunedParameters::Create().
Load()
virtual void Load (const char * filename) pure virtual
Loads an existing set of tuned parameters from the given file.
If there is an error loading the file, an armnn::Exception is thrown.
Implemented in ClTunedParameters.
Save()
virtual void Save (const char * filename) const pure virtual
Saves the current set of tuned parameters to the given file.
If there is an error saving to the file, an armnn::Exception is thrown.
Implemented in ClTunedParameters.
The documentation for this class was generated from the following files:
include/armnn/IRuntime.hpp
src/backends/aclCommon/ArmComputeTuningUtils.cpp