Arm NN: Graph::OutputLayersAccessor Struct Reference
Graph::OutputLayersAccessor Struct Reference
Wrapper class returned by Graph::GetOutputLayers()
#include <Graph.hpp>
Public Member Functions
OutputLayersAccessor (const Graph &graph)
ConstIteratorOutputs begin () const
ConstIteratorOutputs end () const
Public Attributes
const Graph & m_Graph
Detailed Description
Wrapper class returned by Graph::GetOutputLayers()
Definition at line 80 of file Graph.hpp.
Constructor & Destructor Documentation
OutputLayersAccessor()
OutputLayersAccessor (const Graph & graph) inline explicit
Definition at line 82 of file Graph.hpp.
 : m_Graph(graph) {}
Member Function Documentation
begin()
ConstIteratorOutputs begin () const inline
Definition at line 84 of file Graph.hpp.
         {
             return { std::prev(m_Graph.m_Layers.end(), static_cast<IteratorDifference>(m_Graph.GetNumOutputs())),
                      &(PtrCast<const OutputLayer>) };
         }
References Graph::GetNumOutputs(), and Graph::OutputLayersAccessor::m_Graph.
Referenced by LoadedNetwork::ImportOutputs().
end()
ConstIteratorOutputs end () const inline
Definition at line 90 of file Graph.hpp.
         {
             return { m_Graph.m_Layers.end(), &(PtrCast<const OutputLayer>) };
         }
References Graph::OutputLayersAccessor::m_Graph.
Referenced by LoadedNetwork::ImportOutputs().
Member Data Documentation
m_Graph
const Graph& m_Graph
Definition at line 95 of file Graph.hpp.
Referenced by Graph::OutputLayersAccessor::begin(), and Graph::OutputLayersAccessor::end().
The documentation for this struct was generated from the following file:
src/armnn/Graph.hpp