ArmNN: src/backends/backendsCommon/test/layerTests/ArgMinMaxTestImpl.cpp File Reference
ArgMinMaxTestImpl.cpp File Reference
#include "ArgMinMaxTestImpl.hpp"
#include <backendsCommon/test/DataTypeUtils.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 3 > ArgMaxSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 3 > ArgMinSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 3 > ArgMinChannelTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 3 > ArgMaxChannelTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 3 > ArgMaxHeightTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 3 > ArgMinWidthTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxSimpleTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxSimpleTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxSimpleTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxSimpleTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxSimpleTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinSimpleTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinSimpleTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinSimpleTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinSimpleTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinSimpleTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinChannelTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinChannelTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinChannelTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinChannelTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinChannelTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinChannelTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxChannelTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxChannelTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxChannelTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxChannelTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxChannelTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxChannelTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxHeightTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxHeightTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxHeightTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxHeightTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMaxHeightTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinWidthTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinWidthTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinWidthTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinWidthTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 3 > ArgMinWidthTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
ArgMaxChannelTest()
LayerTestResult<int32_t, 3> ArgMaxChannelTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 156 of file ArgMinMaxTestImpl.cpp.
References armnn::Max, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), and armnn::Signed32.
 {
     const armnn::TensorShape inputShape{ 1, 3, 2, 4};
     const armnn::TensorShape outputShape{ 1, 2, 4 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Signed32);
     std::vector<float> inputValues({  1.0f,   2.0f,   3.0f,   4.0f,
                                       5.0f,   6.0f,   7.0f,   8.0f,
                                      10.0f,  20.0f,  30.0f,  40.0f,
                                      50.0f,  60.0f,  70.0f,  80.0f,
                                     100.0f, 200.0f, 300.0f, 400.0f,
                                     500.0f, 600.0f, 700.0f, 800.0f });
     std::vector<int32_t> outputValues({ 2, 2, 2, 2,
                                         2, 2, 2, 2 });
     return ArgMinMaxTestCommon<ArmnnType>(workloadFactory, memoryManager, tensorHandleFactory,
                                           armnn::ArgMinMaxFunction::Max,
                                           inputTensorInfo, outputTensorInfo,
                                           inputValues, outputValues, 1);
 }
ArgMaxChannelTest< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 3> ArgMaxChannelTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxChannelTest< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 3> ArgMaxChannelTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxChannelTest< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 3> ArgMaxChannelTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxChannelTest< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 3> ArgMaxChannelTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxChannelTest< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 3> ArgMaxChannelTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxChannelTest< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 3> ArgMaxChannelTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxHeightTest()
LayerTestResult<int32_t, 3> ArgMaxHeightTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 192 of file ArgMinMaxTestImpl.cpp.
References armnn::Max, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), and armnn::Signed32.
 {
     const armnn::TensorShape inputShape{ 1, 3, 2, 4};
     const armnn::TensorShape outputShape{ 1, 3, 4 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Signed32);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     std::vector<float> inputValues({  1.0f,   2.0f,   3.0f,   4.0f,
                                       5.0f,   6.0f,   7.0f,   8.0f,
                                      10.0f,  20.0f,  30.0f,  40.0f,
                                      50.0f,  60.0f,  70.0f,  80.0f,
                                     100.0f, 200.0f, 300.0f, 400.0f,
                                     500.0f, 600.0f, 700.0f, 800.0f });
     std::vector<int32_t> outputValues({ 1, 1, 1, 1,
                                         1, 1, 1, 1,
                                         1, 1, 1, 1 });
     return ArgMinMaxTestCommon<ArmnnType>(workloadFactory, memoryManager, tensorHandleFactory,
                                           armnn::ArgMinMaxFunction::Max,
                                           inputTensorInfo, outputTensorInfo,
                                           inputValues, outputValues, 2);
 }
ArgMaxHeightTest< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 3> ArgMaxHeightTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxHeightTest< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 3> ArgMaxHeightTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxHeightTest< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 3> ArgMaxHeightTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxHeightTest< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 3> ArgMaxHeightTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxHeightTest< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 3> ArgMaxHeightTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxSimpleTest()
LayerTestResult<int32_t, 3> ArgMaxSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 64 of file ArgMinMaxTestImpl.cpp.
References armnn::Max, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), and armnn::Signed32.
 {
     const armnn::TensorShape inputShape{ 1, 1, 1, 5 };
     const armnn::TensorShape outputShape{ 1, 1, 1 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Signed32);
     std::vector<float> inputValues({ 5.0f, 2.0f, 8.0f, 10.0f, 9.0f });
     std::vector<int32_t> outputValues({ 3 });
     return ArgMinMaxTestCommon<ArmnnType>(workloadFactory, memoryManager, tensorHandleFactory,
                                           armnn::ArgMinMaxFunction::Max,
                                           inputTensorInfo, outputTensorInfo,
                                           inputValues, outputValues, -1); // axis -1 === 3
 }
ArgMaxSimpleTest< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 3> ArgMaxSimpleTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxSimpleTest< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 3> ArgMaxSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxSimpleTest< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 3> ArgMaxSimpleTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxSimpleTest< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 3> ArgMaxSimpleTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxSimpleTest< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 3> ArgMaxSimpleTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMaxSimpleTest< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 3> ArgMaxSimpleTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinChannelTest()
LayerTestResult<int32_t, 3> ArgMinChannelTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 120 of file ArgMinMaxTestImpl.cpp.
References armnn::Min, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), and armnn::Signed32.
 {
     const armnn::TensorShape inputShape{ 1, 3, 2, 4};
     const armnn::TensorShape outputShape{ 1, 2, 4 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Signed32);
     std::vector<float> inputValues({   1.0f,   2.0f,   3.0f,   4.0f,
                                        5.0f,   6.0f,   7.0f,   8.0f,
                                       10.0f,  20.0f,  30.0f,  40.0f,
                                       50.0f,  60.0f,  70.0f,  80.0f,
                                      100.0f, 200.0f, 300.0f, 400.0f,
                                      500.0f, 600.0f, 700.0f, 800.0f });
     std::vector<int32_t> outputValues({ 0, 0, 0, 0,
                                         0, 0, 0, 0 });
     return ArgMinMaxTestCommon<ArmnnType>(workloadFactory, memoryManager, tensorHandleFactory,
                                           armnn::ArgMinMaxFunction::Min,
                                           inputTensorInfo, outputTensorInfo,
                                           inputValues, outputValues, 1);
 }
ArgMinChannelTest< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 3> ArgMinChannelTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinChannelTest< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 3> ArgMinChannelTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinChannelTest< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 3> ArgMinChannelTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinChannelTest< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 3> ArgMinChannelTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinChannelTest< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 3> ArgMinChannelTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinChannelTest< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 3> ArgMinChannelTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinSimpleTest()
LayerTestResult<int32_t, 3> ArgMinSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 92 of file ArgMinMaxTestImpl.cpp.
References armnn::Min, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), and armnn::Signed32.
 {
     const armnn::TensorShape inputShape{ 1, 1, 1, 5 };
     const armnn::TensorShape outputShape{ 1, 1, 1 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Signed32);
     std::vector<float> inputValues({ 5.0f, 2.0f, 8.0f, 10.0f, 9.0f });
     std::vector<int32_t> outputValues({ 1 });
     return ArgMinMaxTestCommon<ArmnnType>(workloadFactory, memoryManager, tensorHandleFactory,
                                           armnn::ArgMinMaxFunction::Min,
                                           inputTensorInfo, outputTensorInfo,
                                           inputValues, outputValues, 3);
 }
ArgMinSimpleTest< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 3> ArgMinSimpleTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinSimpleTest< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 3> ArgMinSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinSimpleTest< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 3> ArgMinSimpleTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinSimpleTest< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 3> ArgMinSimpleTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinSimpleTest< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 3> ArgMinSimpleTest< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinSimpleTest< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 3> ArgMinSimpleTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinWidthTest()
LayerTestResult<int32_t, 3> ArgMinWidthTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 228 of file ArgMinMaxTestImpl.cpp.
References armnn::Min, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), and armnn::Signed32.
 {
     const armnn::TensorShape inputShape{ 1, 3, 2, 4};
     const armnn::TensorShape outputShape{ 1, 3, 2 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Signed32);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     std::vector<float> inputValues({  1.0f,   2.0f,   3.0f,   4.0f,
                                       5.0f,   6.0f,   7.0f,   8.0f,
                                      10.0f,  20.0f,  30.0f,  40.0f,
                                      50.0f,  60.0f,  70.0f,  80.0f,
                                     100.0f, 200.0f, 300.0f, 400.0f,
                                     500.0f, 600.0f, 700.0f, 800.0f });
     std::vector<int32_t> outputValues({ 0, 0,
                                         0, 0,
                                         0, 0 });
     return ArgMinMaxTestCommon<ArmnnType>(workloadFactory, memoryManager, tensorHandleFactory,
                                           armnn::ArgMinMaxFunction::Min,
                                           inputTensorInfo, outputTensorInfo,
                                           inputValues, outputValues, 3);
 }
ArgMinWidthTest< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 3> ArgMinWidthTest< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinWidthTest< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 3> ArgMinWidthTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinWidthTest< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 3> ArgMinWidthTest< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinWidthTest< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 3> ArgMinWidthTest< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ArgMinWidthTest< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 3> ArgMinWidthTest< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)