ArmNN: src/backends/backendsCommon/test/layerTests/GatherTestImpl.cpp File Reference
GatherTestImpl.cpp File Reference
#include "GatherTestImpl.hpp"
#include <ResolveType.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
LayerTestResult< float, 1 > Gather1dParamsFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 1 > Gather1dParamsFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 1 > Gather1dParamsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 1 > Gather1dParamsInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int32_t, 1 > Gather1dParamsInt32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > GatherMultiDimParamsFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 2 > GatherMultiDimParamsFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > GatherMultiDimParamsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > GatherMultiDimParamsInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int32_t, 2 > GatherMultiDimParamsInt32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > GatherMultiDimParamsMultiDimIndicesFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > GatherMultiDimParamsMultiDimIndicesFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GatherMultiDimParamsMultiDimIndicesUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > GatherMultiDimParamsMultiDimIndicesInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int32_t, 4 > GatherMultiDimParamsMultiDimIndicesInt32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
Gather1dParamsFloat16Test()
LayerTestResult<armnn::Half, 1> Gather1dParamsFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 321 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float16>::Gather1dParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
Gather1dParamsFloat32Test()
LayerTestResult<float, 1> Gather1dParamsFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 312 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float32>::Gather1dParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
Gather1dParamsInt16Test()
LayerTestResult<int16_t, 1> Gather1dParamsInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 339 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QSymmS16>::Gather1dParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
Gather1dParamsInt32Test()
LayerTestResult<int32_t, 1> Gather1dParamsInt32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 348 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Signed32>::Gather1dParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
Gather1dParamsUint8Test()
LayerTestResult<uint8_t, 1> Gather1dParamsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 330 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QAsymmU8>::Gather1dParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsFloat16Test()
LayerTestResult<armnn::Half, 2> GatherMultiDimParamsFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 366 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float16>::GatherMultiDimParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsFloat32Test()
LayerTestResult<float, 2> GatherMultiDimParamsFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 357 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float32>::GatherMultiDimParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsInt16Test()
LayerTestResult<int16_t, 2> GatherMultiDimParamsInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 384 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QSymmS16>::GatherMultiDimParamsTestImpl(
         workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsInt32Test()
LayerTestResult<int32_t, 2> GatherMultiDimParamsInt32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 393 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Signed32>::GatherMultiDimParamsTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsMultiDimIndicesFloat16Test()
LayerTestResult<armnn::Half, 4> GatherMultiDimParamsMultiDimIndicesFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 411 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float16>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsMultiDimIndicesFloat32Test()
LayerTestResult<float, 4> GatherMultiDimParamsMultiDimIndicesFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 402 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float32>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsMultiDimIndicesInt16Test()
LayerTestResult<int16_t, 4> GatherMultiDimParamsMultiDimIndicesInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 429 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QSymmS16>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsMultiDimIndicesInt32Test()
LayerTestResult<int32_t, 4> GatherMultiDimParamsMultiDimIndicesInt32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 438 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Signed32>::GatherMultiDimParamsMultiDimIndicesTestImpl(
             workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsMultiDimIndicesUint8Test()
LayerTestResult<uint8_t, 4> GatherMultiDimParamsMultiDimIndicesUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 420 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QAsymmU8>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager, tensorHandleFactory);
 }
GatherMultiDimParamsUint8Test()
LayerTestResult<uint8_t, 2> GatherMultiDimParamsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 375 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QAsymmU8>::GatherMultiDimParamsTestImpl(
         workloadFactory, memoryManager, tensorHandleFactory);
 }