ArmNN: src/backends/backendsCommon/test/layerTests/LstmTestImpl.hpp File Reference
LstmTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 2 > LstmLayerFloat32WithCifgWithPeepholeNoProjectionTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > LstmLayerFloat32NoCifgWithPeepholeWithProjectionTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > LstmLayerInt16NoCifgNoPeepholeNoProjectionTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > LstmLayerInt16WithCifgWithPeepholeNoProjectionTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > LstmLayerInt16NoCifgWithPeepholeWithProjectionTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16ConstantTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > QuantizedLstmTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > QLstmTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > QLstmTest1 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > QLstmTest2 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest()
LayerTestResult<float, 2> LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2701 of file LstmTestImpl.cpp.
References armnn::Float32.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({2, 2}, armnn::DataType::Float32);
     boost::multi_array<float, 2> input = MakeTensor<float, 2>(inputDesc, std::vector<float>(
             {2., 3., 3., 4.}));
     armnn::TensorInfo outputDesc({2, 4}, armnn::DataType::Float32);
     boost::multi_array<float, 2> expectedOutput = MakeTensor<float, 2>(outputDesc, std::vector<float>(
             {{-0.02973187f, 0.1229473f,   0.20885126f, -0.15358765f,
               -0.0185422f,   0.11281417f,  0.24466537f, -0.1826292f}}));
     return LstmNoCifgNoPeepholeNoProjectionTestImpl<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
LstmLayerFloat32NoCifgWithPeepholeWithProjectionTest()
LayerTestResult<float, 2> LstmLayerFloat32NoCifgWithPeepholeWithProjectionTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2678 of file LstmTestImpl.cpp.
References armnn::Float32.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({ 2, 5 }, armnn::DataType::Float32);
     boost::multi_array<float, 2> input = MakeTensor<float, 2>(inputDesc, std::vector<float>(
             {0.787926f, 0.151646f, 0.071352f, 0.118426f, 0.458058f,
              0.295743f, 0.544053f, 0.690064f, 0.858138f, 0.497181f}));
     armnn::TensorInfo outputDesc({ 2, 16 }, armnn::DataType::Float32);
     boost::multi_array<float, 2> expectedOutput = MakeTensor<float, 2>(outputDesc, std::vector<float>(
             {-0.00396806f, 0.029352f,     -0.00279226f, 0.0159977f,   -0.00835576f,
              -0.0211779f,  0.0283512f,    -0.0114597f,  0.00907307f,  -0.0244004f,
              -0.0152191f,  -0.0259063f,   0.00914318f,  0.00415118f,  0.017147f,
              0.0134203f, -0.013869f,    0.0287268f,   -0.00334693f, 0.00733398f,  -0.0287926f,
              -0.0186926f,   0.0193662f,   -0.0115437f,  0.00422612f,  -0.0345232f,
              0.00223253f,   -0.00957321f, 0.0210624f,   0.013331f,    0.0150954f,
              0.02168f}));
     return LstmLayerNoCifgWithPeepholeWithProjectionTestImpl<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest()
LayerTestResult<float, 2> LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2719 of file LstmTestImpl.cpp.
References armnn::Float32.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({ 2, 5 }, armnn::DataType::Float32);
     boost::multi_array<float, 2> input = MakeTensor<float, 2>(inputDesc, std::vector<float>(
             {0.7f, 0.8f, 0.1f, 0.2f, 0.3f,     //batch 0
              0.3f, 0.2f, 0.9f, 0.8f, 0.1f}));  //batch 1
     armnn::TensorInfo outputDesc({ 2, 3 }, armnn::DataType::Float32);
     boost::multi_array<float, 2> expectedOutput = MakeTensor<float, 2>(outputDesc, std::vector<float>(
             {  0.0244077f,  0.128027f, -0.00170918f,    //batch 0
              -0.00692428f, 0.0848741f,    0.063445f})); //batch 1
     return LstmLayerNoCifgWithPeepholeWithProjectionWithLayerNormTestImpl<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
LstmLayerFloat32WithCifgWithPeepholeNoProjectionTest()
LayerTestResult<float, 2> LstmLayerFloat32WithCifgWithPeepholeNoProjectionTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2661 of file LstmTestImpl.cpp.
References armnn::Float32.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({ 2, 2 }, armnn::DataType::Float32);
     boost::multi_array<float, 2> input = MakeTensor<float, 2>(inputDesc, std::vector<float>(
             { 2., 3., 3., 4. }));
     armnn::TensorInfo outputDesc({ 2, 4 }, armnn::DataType::Float32);
     boost::multi_array<float, 2> expectedOutput = MakeTensor<float, 2>(outputDesc, std::vector<float>(
             {-0.36444446f, -0.00352185f, 0.12886585f, -0.05163646f,
              -0.42734814f, -0.00478661f,  0.13455015f, -0.03560682f}));
     return LstmLayerWithCifgWithPeepholeNoProjectionTestImpl<armnn::DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16ConstantTest()
LayerTestResult<int16_t, 2> LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16ConstantTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2843 of file LstmTestImpl.cpp.
References armnn::QSymmS16.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     const float qScale = 1.0f;
     const int32_t qOffset = 0;
     const armnn::DataType datatype = armnn::DataType::QSymmS16; // datatype & constants set to QSymm16
     armnn::TensorInfo inputDesc({2, 2}, datatype);
     boost::multi_array<int16_t , 2> input =
         MakeTensor<int16_t , 2>(inputDesc,
                                 armnnUtils::QuantizedVector<int16_t>({ 2.f, 3.f, 3.f, 4.f }, qScale, qOffset));
     armnn::TensorInfo outputDesc({2, 4}, datatype);
     boost::multi_array<int16_t, 2> expectedOutput =
         MakeTensor<int16_t, 2>(
             outputDesc,
             armnnUtils::QuantizedVector<int16_t>(
                 {
                     -0.02973187f, 0.12294730f, 0.20885126f, -0.15358765f,
                     -0.01854220f, 0.11281417f, 0.24466537f, -0.18262920f
                 },
                 qScale, qOffset));
     return LstmNoCifgNoPeepholeNoProjectionTestImpl<datatype>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput, qScale, qOffset, datatype);
 }
LstmLayerInt16NoCifgNoPeepholeNoProjectionTest()
LayerTestResult<int16_t, 2> LstmLayerInt16NoCifgNoPeepholeNoProjectionTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2737 of file LstmTestImpl.cpp.
References armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     const float qScale = 1.0f;
     const int32_t qOffset = 0;
     const armnn::DataType datatype = armnn::DataType::QSymmS16;
     const armnn::DataType constantDatatype = armnn::DataType::QAsymmU8;
     armnn::TensorInfo inputDesc({2, 2}, datatype);
     boost::multi_array<int16_t , 2> input = MakeTensor<int16_t , 2>(
         inputDesc,
         armnnUtils::QuantizedVector<int16_t>({ 2.f, 3.f, 3.f, 4.f }, qScale, qOffset));
     armnn::TensorInfo outputDesc({2, 4}, datatype);
     boost::multi_array<int16_t, 2> expectedOutput = MakeTensor<int16_t, 2>(
         outputDesc,
         armnnUtils::QuantizedVector<int16_t>(
             {
                 -0.02973187f, 0.12294730f, 0.20885126f, -0.15358765f,
                 -0.01854220f, 0.11281417f, 0.24466537f, -0.18262920f
             },
             qScale, qOffset));
     return LstmNoCifgNoPeepholeNoProjectionTestImpl<datatype>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput, qScale, qOffset, constantDatatype);
 }
LstmLayerInt16NoCifgWithPeepholeWithProjectionTest()
LayerTestResult<int16_t, 2> LstmLayerInt16NoCifgWithPeepholeWithProjectionTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2800 of file LstmTestImpl.cpp.
References armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     const float qScale = 2.0f;
     const int32_t qOffset = 0;
     const armnn::DataType datatype = armnn::DataType::QSymmS16;
     const armnn::DataType constantDatatype = armnn::DataType::QAsymmU8;
     armnn::TensorInfo inputDesc({ 2, 5 }, datatype);
     boost::multi_array<int16_t, 2> input =
         MakeTensor<int16_t, 2>(
             inputDesc,
             armnnUtils::QuantizedVector<int16_t>(
                 {
                     0.787926f, 0.151646f, 0.071352f, 0.118426f, 0.458058f,
                     0.295743f, 0.544053f, 0.690064f, 0.858138f, 0.497181f
                 },
                 qScale, qOffset));
     armnn::TensorInfo outputDesc({ 2, 16 }, datatype);
     boost::multi_array<int16_t, 2> expectedOutput =
         MakeTensor<int16_t, 2>(
             outputDesc,
             armnnUtils::QuantizedVector<int16_t>(
                 {
                     -0.00396806f,  0.02935200f, -0.00279226f,  0.01599770f,
                     -0.00835576f, -0.02117790f,  0.02835120f, -0.01145970f,
                      0.00907307f, -0.02440040f, -0.01521910f, -0.02590630f,
                      0.00914318f,  0.00415118f,  0.01714700f,  0.01342030f,
                     -0.01386900f,  0.02872680f, -0.00334693f,  0.00733398f,
                     -0.02879260f, -0.01869260f,  0.01936620f, -0.01154370f,
                      0.00422612f, -0.03452320f,  0.00223253f, -0.00957321f,
                      0.02106240f,  0.01333100f,  0.01509540f,  0.02168000f
                 },
                 qScale, qOffset));
     return LstmLayerNoCifgWithPeepholeWithProjectionTestImpl<datatype>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput, qScale, qOffset, constantDatatype);
 }
LstmLayerInt16WithCifgWithPeepholeNoProjectionTest()
LayerTestResult<int16_t, 2> LstmLayerInt16WithCifgWithPeepholeNoProjectionTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2768 of file LstmTestImpl.cpp.
References armnn::QAsymmU8, and armnn::QSymmS16.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     const float qScale = 1.0f;
     const int32_t qOffset = 0;
     const armnn::DataType datatype = armnn::DataType::QSymmS16;
     const armnn::DataType constantDatatype = armnn::DataType::QAsymmU8;
     armnn::TensorInfo inputDesc({ 2, 2 }, datatype);
     boost::multi_array<int16_t, 2> input =
         MakeTensor<int16_t, 2>(
             inputDesc,
             armnnUtils::QuantizedVector<int16_t>({ 2.f, 3.f, 3.f, 4.f }, qScale, qOffset));
     armnn::TensorInfo outputDesc({ 2, 4 }, datatype);
     boost::multi_array<int16_t, 2> expectedOutput =
         MakeTensor<int16_t, 2>(
             outputDesc,
             armnnUtils::QuantizedVector<int16_t>(
                 {
                     -0.36444446f, -0.00352185f, 0.12886585f, -0.05163646f,
                     -0.42734814f, -0.00478661f, 0.13455015f, -0.03560682f
                 },
                 qScale, qOffset));
     return LstmLayerWithCifgWithPeepholeNoProjectionTestImpl<datatype>(
         workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput, qScale, qOffset, constantDatatype);
 }
QLstmTest()
LayerTestResult<int8_t, 2> QLstmTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2894 of file LstmTestImpl.cpp.
References armnn::QAsymmS8.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({2, 5}, armnn::DataType::QAsymmS8);
     boost::multi_array<int8_t, 2> input = MakeTensor<int8_t, 2>(inputDesc, std::vector<int8_t>(
             {90, 102, 13, 26, 38, 102, 13, 26, 51, 64}));
     armnn::TensorInfo outputDesc({2, 4}, armnn::DataType::QAsymmS8);
     boost::multi_array<int8_t, 2> expectedOutput = MakeTensor<int8_t, 2>(outputDesc, std::vector<int8_t>(
             {-15, 21, 14, 20, -15, 15, 5, 27}));
     return QLstmTestImpl(workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
QLstmTest1()
LayerTestResult<int8_t, 2> QLstmTest1 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2910 of file LstmTestImpl.cpp.
References armnn::QAsymmS8.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({2, 5}, armnn::DataType::QAsymmS8);
     boost::multi_array<int8_t, 2> input = MakeTensor<int8_t, 2>(inputDesc, std::vector<int8_t>(
             {90, 102, 13, 26, 38, 102, 13, 26, 51, 64}));
     armnn::TensorInfo outputDesc({2, 3}, armnn::DataType::QAsymmS8);
     boost::multi_array<int8_t, 2> expectedOutput = MakeTensor<int8_t, 2>(outputDesc, std::vector<int8_t>(
             {127, 127, -108, -67, 127, 127}));
     return QLstmTestImpl1(workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
QLstmTest2()
LayerTestResult<int8_t, 2> QLstmTest2 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2926 of file LstmTestImpl.cpp.
References armnn::QAsymmS8.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo inputDesc({2, 5}, armnn::DataType::QAsymmS8);
     boost::multi_array<int8_t, 2> input = MakeTensor<int8_t, 2>(inputDesc, std::vector<int8_t>(
             {90, 102, 13, 26, 38, 102, 13, 26, 51, 64}));
     armnn::TensorInfo outputDesc({2, 3}, armnn::DataType::QAsymmS8);
     boost::multi_array<int8_t, 2> expectedOutput = MakeTensor<int8_t, 2>(outputDesc, std::vector<int8_t>(
             {127, 127, 127, -128, 127, 127}));
     return QLstmTestImpl2(workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }
QuantizedLstmTest()
LayerTestResult<uint8_t, 2> QuantizedLstmTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2877 of file LstmTestImpl.cpp.
References armnn::QAsymmU8.
 {
     armnn::TensorInfo inputDesc({2, 2}, armnn::DataType::QAsymmU8);
     boost::multi_array<uint8_t, 2> input = MakeTensor<uint8_t, 2>(inputDesc, std::vector<uint8_t>(
         {166, 179, 50, 150}));
     armnn::TensorInfo outputDesc({2, 4}, armnn::DataType::QAsymmU8);
     boost::multi_array<uint8_t, 2> expectedOutput = MakeTensor<uint8_t, 2>(outputDesc, std::vector<uint8_t>(
         {140, 151, 146, 112, 136, 156, 142, 112 }));
     return QuantizedLstmTestImpl(workloadFactory, memoryManager, tensorHandleFactory, input, expectedOutput);
 }