ArmNN: src/armnn/test/ObservableTest.cpp File Reference
ObservableTest.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "Graph.hpp"
#include "Observable.hpp"
Functions
BOOST_AUTO_TEST_CASE (AddedLayerObservableTest)
BOOST_AUTO_TEST_CASE (ClearAddedLayerObservableTest)
BOOST_AUTO_TEST_CASE (ErasedLayerNamesObservableTest)
BOOST_AUTO_TEST_CASE (ClearErasedLayerNamesObservableTest)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (AddedLayerObservableTest)
Definition at line 13 of file ObservableTest.cpp.
References Graph::AddLayer(), GraphObservable< ObservedType >::begin(), GraphObservable< ObservedType >::end(), and Graph::InsertNewLayer().
 {
     armnn::Graph graph;
     // Create a graph observable
     armnn::AddedLayerObservable layerObservable(graph);
     // Add a few layers
     auto output = graph.AddLayer<armnn::OutputLayer>(0, "output");
     auto input = graph.InsertNewLayer<armnn::InputLayer>(output->GetInputSlot(0), 0, "input");
     // Check the observable has observed the changes
     std::list<armnn::Layer*> testLayers({ output, input });
     BOOST_CHECK_EQUAL_COLLECTIONS(layerObservable.begin(), layerObservable.end(),
                                   testLayers.begin(), testLayers.end());
 }
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (ClearAddedLayerObservableTest)
Definition at line 31 of file ObservableTest.cpp.
References Graph::AddLayer(), GraphObservable< ObservedType >::begin(), GraphObservable< ObservedType >::Clear(), GraphObservable< ObservedType >::end(), and Graph::InsertNewLayer().
 {
     armnn::Graph graph;
     // Create a graph observable
     armnn::AddedLayerObservable addedLayerObservable(graph);
     // Add a few layers
     auto output = graph.AddLayer<armnn::OutputLayer>(0, "output");
     graph.InsertNewLayer<armnn::InputLayer>(output->GetInputSlot(0), 0, "input");
     addedLayerObservable.Clear();
     // Check the observable has observed the changes
     std::list<armnn::Layer*> emptyList({});
     BOOST_CHECK_EQUAL_COLLECTIONS(addedLayerObservable.begin(), addedLayerObservable.end(),
                                   emptyList.begin(), emptyList.end());
 }
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (ErasedLayerNamesObservableTest)
Definition at line 51 of file ObservableTest.cpp.
References Graph::AddLayer(), GraphObservable< ObservedType >::begin(), GraphObservable< ObservedType >::end(), Graph::EraseLayer(), and Graph::InsertNewLayer().
 {
     armnn::Graph graph;
     // Create a graph observable
     armnn::ErasedLayerNamesObservable erasedLayerNamesObservable(graph);
     // Add a few layers
     auto output = graph.AddLayer<armnn::OutputLayer>(0, "output");
     graph.InsertNewLayer<armnn::InputLayer>(output->GetInputSlot(0), 0, "input");
     graph.EraseLayer(output);
     // Check the observable has observed the changes
     std::list<std::string> testList({"output"});
     BOOST_CHECK_EQUAL_COLLECTIONS(erasedLayerNamesObservable.begin(), erasedLayerNamesObservable.end(),
                                   testList.begin(), testList.end());
 }
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (ClearErasedLayerNamesObservableTest)
Definition at line 71 of file ObservableTest.cpp.
References Graph::AddLayer(), GraphObservable< ObservedType >::begin(), BOOST_AUTO_TEST_SUITE_END(), GraphObservable< ObservedType >::Clear(), GraphObservable< ObservedType >::end(), Graph::EraseLayer(), and Graph::InsertNewLayer().
 {
     armnn::Graph graph;
     // Create a graph observable
     armnn::ErasedLayerNamesObservable erasedLayerNamesObservable(graph);
     // Add a few layers
     auto output = graph.AddLayer<armnn::OutputLayer>(0, "output");
     graph.InsertNewLayer<armnn::InputLayer>(output->GetInputSlot(0), 0, "input");
     graph.EraseLayer(output);
     erasedLayerNamesObservable.Clear();
     // Check the observable has observed the changes
     std::list<std::string> emptyList({});
     BOOST_CHECK_EQUAL_COLLECTIONS(erasedLayerNamesObservable.begin(), erasedLayerNamesObservable.end(),
                                   emptyList.begin(), emptyList.end());
 }