ArmNN: src/backends/reference/test/RefLayerTests.cpp File Reference
RefLayerTests.cpp File Reference
#include "RefWorkloadFactoryHelper.hpp"
#include <backendsCommon/test/LayerTests.hpp>
#include <reference/RefWorkloadFactory.hpp>
#include <test/UnitTests.hpp>
#include <boost/test/unit_test.hpp>
Typedefs
using FactoryType = RefWorkloadFactory
Functions
ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleConvolution2d3x5QSymm16Nhwc, SimpleConvolution2d3x5QSymm16Test, true, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleConvolution2d3x3QSymm16Nhwc
DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedConvolution2dSquareStride2x2Nhwc, SimpleConvolution2d3x3Stride2x2Test, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleConvolution2dAsymmetricPaddingLargerThanHalfKernelSize
DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleConvolution2dAsymmetricPadding, Convolution2dAsymmetricPaddingTest, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleConvolution2dAsymmetricPaddingLargerThanHalfKernelSizeNhwc
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleConvolution2dAsymmetricPaddingNhwc, Convolution2dAsymmetricPaddingTest, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d3x3Dilation3x3BFloat16
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcBFloat16, Convolution2d3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d3x3Dilation3x3
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3Nhwc, Convolution2d3x3Dilation3x3Test< DataType::Float32, DataType::Float32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d3x3Dilation3x3Int8
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcInt8, Convolution2d3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d3x3Dilation3x3Uint8
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcUint8, Convolution2d3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d3x3Dilation3x3Int16
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcInt16, Convolution2d3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x3x3Dilation3x3BFloat16
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcBFloat16, Convolution2d2x3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x3x3Dilation3x3
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3Nhwc, Convolution2d2x3x3Dilation3x3Test< DataType::Float32, DataType::Float32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x3x3Dilation3x3Int8
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcInt8, Convolution2d2x3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x3x3Dilation3x3Uint8
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcUint8, Convolution2d2x3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x3x3Dilation3x3Int16
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcInt16, Convolution2d2x3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x2Dilation2x2Padding2x2Stride3x3BFloat16
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcBFloat16, Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::BFloat16, DataType::BFloat16 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x2Dilation2x2Padding2x2Stride3x3
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3Nhwc, Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::Float32, DataType::Float32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x2Dilation2x2Padding2x2Stride3x3Int8
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcInt8, Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::QAsymmS8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x2Dilation2x2Padding2x2Stride3x3Uint8
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcUint8, Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::QAsymmU8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2d2x2Dilation2x2Padding2x2Stride3x3Int16
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcInt16, Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::QSymmS16, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(Convolution2dPerAxisQuantTestNchw
ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2dPerAxisQuantTestNhwc, Convolution2dPerAxisQuantTest, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Stride2x2Bf16, Convolution2d3x3Stride2x2BFloat16Test, false, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Stride2x2BFloat16SmallValue, Convolution2d3x3Stride2x2BFloat16SmallValueTest, false, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedDepthwiseConvolution2dUint8, DepthwiseConvolution2dUint8Test, false, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedDepthwiseConvolution2dUint8Nhwc
DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleDepthwiseConvolution2d3x3Dilation3x3Nhwc, SimpleDepthwiseConvolution2d3x3Dilation3x3NhwcTest) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d3x3Dilation3x3
DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3Nhwc, DepthwiseConvolution2d3x3Dilation3x3Test< DataType::Float32, DataType::Float32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d3x3Dilation3x3BFloat16
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcBFloat16, DepthwiseConvolution2d3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d3x3Dilation3x3Int8
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcInt8, DepthwiseConvolution2d3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d3x3Dilation3x3Uint8
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcUint8, DepthwiseConvolution2d3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d3x3Dilation3x3Int16
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcInt16, DepthwiseConvolution2d3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d2x3x3Dilation3x3
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3Nhwc, DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::Float32, DataType::Float32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d2x3x3Dilation3x3BFloat16
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcBFloat16, DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d2x3x3Dilation3x3Int8
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcInt8, DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d2x3x3Dilation3x3Uint8
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcUint8, DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2d2x3x3Dilation3x3Int16
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcInt16, DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 >, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2dMult4
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dMult2, DepthwiseConvolution2dMult2Test< armnn::DataType::Float32, armnn::DataType::Float32 >, false, armnn::DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2dMult4BFloat16
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dMult2BFloat16, DepthwiseConvolution2dMult2Test< armnn::DataType::BFloat16, armnn::DataType::BFloat16 >, false, armnn::DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2dDepthMul1
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dDepthMul1Uint8, DepthwiseConvolution2dDepthMul1Uint8Test, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2dDepthMul1Int16
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedDepthwiseConvolution2dDepthMul1, DepthwiseConvolution2dDepthMul1Test, false, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedDepthwiseConvolution2dDepthMul1Uint8
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dDepthMul1Nhwc, DepthwiseConvolution2dDepthMul1Test, true, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(DepthwiseConvolution2dDepthMul1Uint8Nhwc
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedDepthwiseConvolution2dDepthMul1Nhwc, DepthwiseConvolution2dDepthMul1Test, false, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedDepthwiseConvolution2dDepthMul1Uint8Nhwc
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dAsymmetric, DepthwiseConvolution2dAsymmetricTest, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedDepthwiseConvolution2dAsymmetric
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dAsymmetricNhwc, DepthwiseConvolution2dAsymmetricTest, true, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedDepthwiseConvolution2dAsymmetricNhwc
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dDepthMul64, DepthwiseConvolution2dDepthMul64Test)
ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dPerAxisQuantTestNchw, DepthwiseConvolution2dPerAxisQuantTest, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dPerAxisQuantTestNhwc, DepthwiseConvolution2dPerAxisQuantTest, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleMaxPooling2dSize2x2Stride2x2Uint8, SimpleMaxPooling2dSize2x2Stride2x2Uint8Test, false) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleMaxPooling2dSize2x2Stride2x2Int16
false ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleMaxPooling2dSize3x3Stride2x4Uint8, SimpleMaxPooling2dSize3x3Stride2x4Uint8Test, false) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleMaxPooling2dSize3x3Stride2x4Int16
false false ARMNN_AUTO_TEST_CASE_WITH_THF (IgnorePaddingSimpleAveragePooling2dNoPadding, IgnorePaddingSimpleAveragePooling2dNoPaddingTest) ARMNN_AUTO_TEST_CASE_WITH_THF(IgnorePaddingSimpleAveragePooling2dNoPaddingUint8
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (IgnorePaddingSimpleAveragePooling2dNoPaddingInt16, IgnorePaddingSimpleAveragePooling2dNoPaddingInt16Test) ARMNN_AUTO_TEST_CASE_WITH_THF(IgnorePaddingAveragePooling2dSize3x2Stride2x2
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test false ARMNN_AUTO_TEST_CASE_WITH_THF (IgnorePaddingAveragePooling2dSize3x2Stride2x2NoPadding, IgnorePaddingAveragePooling2dSize3x2Stride2x2Test, true) ARMNN_AUTO_TEST_CASE_WITH_THF(InstanceNormFloat32Nchw
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nchw, InstanceNormFloat16Test, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat32Nhwc, InstanceNormFloat32Test, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nhwc, InstanceNormFloat16Test, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat32Nchw2, InstanceNormFloat32Test2, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nchw2, InstanceNormFloat16Test2, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat32Nhwc2, InstanceNormFloat32Test2, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nhwc2, InstanceNormFloat16Test2, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (ConcatUint8DifferentInputOutputQParam, ConcatDifferentInputOutputQParamTest< DataType::QAsymmU8 >, true) ARMNN_AUTO_TEST_CASE_WITH_THF(ConcatInt16DifferentInputOutputQParam
true ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinear, SimpleResizeBilinearTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeBilinearFloat16
true DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearInt8, SimpleResizeBilinearTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeBilinearUint8
true DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearUint16, SimpleResizeBilinearTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearNop
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopFloat16, ResizeBilinearNopTest< DataType::Float16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearNopInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopUint8, ResizeBilinearNopTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(esizeBilinearNopUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMin, ResizeBilinearSqMinTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearSqMinFloat16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinInt8, ResizeBilinearSqMinTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearSqMinUint8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinUint16, SimpleResizeBilinearTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMin
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinFloat16, ResizeBilinearMinTest< DataType::Float16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMinInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinUint8, ResizeBilinearMinTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMinUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMag, ResizeBilinearMagTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMagFloat16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagInt8, ResizeBilinearMagTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMagUint8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagUint16, SimpleResizeBilinearTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeBilinear
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearFloat16, HalfPixelCentersResizeBilinearTest< DataType::Float16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeBilinearInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearUint8, HalfPixelCentersResizeBilinearTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeBilinearUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinear, AlignCornersResizeBilinearTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeBilinearFloat16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearInt8, AlignCornersResizeBilinearTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeBilinearUint8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearUint16, AlignCornersResizeBilinearTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearNopNhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopNhwcFloat16, ResizeBilinearNopTest< DataType::Float16 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearNopInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopUint8Nhwc, ResizeBilinearNopTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearNopUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearNhwc, SimpleResizeBilinearTest< DataType::Float32 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeBilinearNhwcFloat16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearInt8Nhwc, SimpleResizeBilinearTest< DataType::QAsymmS8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeBilinearUint8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearUint16Nhwc, ResizeBilinearNopTest< DataType::QSymmS16 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearSqMinNhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinNhwcFloat16, ResizeBilinearSqMinTest< DataType::Float16 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearSqMinInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinUint8Nhwc, ResizeBilinearSqMinTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearSqMinUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinNhwc, ResizeBilinearMinTest< DataType::Float32 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMinNhwcFloat16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinInt8Nhwc, ResizeBilinearMinTest< DataType::QAsymmS8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMinUint8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinUint16Nhwc, ResizeBilinearNopTest< DataType::QSymmS16 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMagNhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagNhwcFloat16, ResizeBilinearMagTest< DataType::Float16 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMagInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagUint8Nhwc, ResizeBilinearMagTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeBilinearMagUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearNhwc, HalfPixelCentersResizeBilinearTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeBilinearFloat16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearInt8Nhwc, HalfPixelCentersResizeBilinearTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeBilinearUint8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearUint16Nhwc, HalfPixelCentersResizeBilinearTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeBilinearNhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearFloat16Nhwc, AlignCornersResizeBilinearTest< DataType::Float16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeBilinearInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearUint8Nhwc, AlignCornersResizeBilinearTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeBilinearUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighbor, SimpleResizeNearestNeighborTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeNearestNeighborInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighborUint8, SimpleResizeNearestNeighborTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeNearestNeighborUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNop, ResizeNearestNeighborNopTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborNopInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNopUint8, ResizeNearestNeighborNopTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(esizeNearestNeighborNopUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMin, ResizeNearestNeighborSqMinTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborSqMinInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMinUint8, ResizeNearestNeighborSqMinTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborSqMinUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMin, ResizeNearestNeighborMinTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMinInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMinUint8, ResizeNearestNeighborMinTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMinUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMag, ResizeNearestNeighborMagTest< DataType::Float32 >, DataLayout::NCHW, 0.10f, 50, 0.11f, 20) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMagInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMagUint8, ResizeNearestNeighborMagTest< DataType::QAsymmU8 >, DataLayout::NCHW, 0.10f, 50, 0.11f, 20) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMagUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbour, HalfPixelCentersResizeNearestNeighbourTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeNearestNeighbourFloat16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourInt8, HalfPixelCentersResizeNearestNeighbourTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeNearestNeighbourUint8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourUint16, HalfPixelCentersResizeNearestNeighbourTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeNearestNeighbour
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourFloat16, AlignCornersResizeNearestNeighbourTest< DataType::Float16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeNearestNeighbourInt8
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourUint8, AlignCornersResizeNearestNeighbourTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeNearestNeighbourUint16
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNopNhwc, ResizeNearestNeighborNopTest< DataType::Float32 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborNopInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNopUint8Nhwc, ResizeNearestNeighborNopTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborNopUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighborNhwc, SimpleResizeNearestNeighborTest< DataType::Float32 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeNearestNeighborInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighborUint8Nhwc, SimpleResizeNearestNeighborTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleResizeNearestNeighborUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMinNhwc, ResizeNearestNeighborSqMinTest< DataType::Float32 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborSqMinInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMinUint8Nhwc, ResizeNearestNeighborSqMinTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborSqMinUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMinNhwc, ResizeNearestNeighborMinTest< DataType::Float32 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMinInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMinUint8Nhwc, ResizeNearestNeighborMinTest< DataType::QAsymmU8 >, DataLayout::NHWC) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMinUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMagNhwc, ResizeNearestNeighborMagTest< DataType::Float32 >, DataLayout::NHWC, 0.10f, 50, 0.11f, 20) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMagInt8Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMagUint8Nhwc, ResizeNearestNeighborMagTest< DataType::QAsymmU8 >, DataLayout::NHWC, 0.10f, 50, 0.11f, 20) ARMNN_AUTO_TEST_CASE_WITH_THF(ResizeNearestNeighborMagUint16Nhwc
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourNchw, HalfPixelCentersResizeNearestNeighbourTest< DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeNearestNeighbourFloat16Nchw
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourInt8Nchw, HalfPixelCentersResizeNearestNeighbourTest< DataType::QAsymmS8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(HalfPixelCentersResizeNearestNeighbourUint8Nchw
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourUint16Nchw, HalfPixelCentersResizeNearestNeighbourTest< DataType::QSymmS16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeNearestNeighbourNchw
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourFloat16Nchw, AlignCornersResizeNearestNeighbourTest< DataType::Float16 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeNearestNeighbourInt8NchRsqrtw
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourUint8Nchw, AlignCornersResizeNearestNeighbourTest< DataType::QAsymmU8 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(AlignCornersResizeNearestNeighbourUint16Nchw
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (L2Normalization2dShape, L2Normalization2dShapeTest)
BOOST_AUTO_TEST_CASE (LstmUtilsZeroVector)
BOOST_AUTO_TEST_CASE (LstmUtilsMeanStddevNormalization)
BOOST_AUTO_TEST_CASE (LstmUtilsVectorBatchVectorCwiseProduct)
BOOST_AUTO_TEST_CASE (LstmUtilsVectorBatchVectorAdd)
ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerFloat32WithCifgWithPeepholeNoProjection, LstmLayerFloat32WithCifgWithPeepholeNoProjectionTest) ARMNN_AUTO_TEST_CASE_WITH_THF(LstmLayerFloat32NoCifgNoPeepholeNoProjection
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerFloat32NoCifgWithPeepholeWithProjection, LstmLayerFloat32NoCifgWithPeepholeWithProjectionTest) ARMNN_AUTO_TEST_CASE_WITH_THF(LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNorm
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerInt16NoCifgNoPeepholeNoProjection, LstmLayerInt16NoCifgNoPeepholeNoProjectionTest) ARMNN_AUTO_TEST_CASE_WITH_THF(LstmLayerInt16WithCifgWithPeepholeNoProjection
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest LstmLayerInt16WithCifgWithPeepholeNoProjectionTest ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerInt16NoCifgWithPeepholeWithProjection, LstmLayerInt16NoCifgWithPeepholeWithProjectionTest) ARMNN_AUTO_TEST_CASE_WITH_THF(LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16Constant
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest LstmLayerInt16WithCifgWithPeepholeNoProjectionTest LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16ConstantTest ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_1, DepthToSpaceTest1< DataType::Float32 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_2, DepthToSpaceTest2< DataType::Float32 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_3, DepthToSpaceTest3< DataType::Float32 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_4, DepthToSpaceTest4< DataType::Float32 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_1, DepthToSpaceTest1< DataType::Float16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_2, DepthToSpaceTest2< DataType::Float16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_3, DepthToSpaceTest3< DataType::Float16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_4, DepthToSpaceTest4< DataType::Float16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_1, DepthToSpaceTest1< DataType::QAsymmS8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_2, DepthToSpaceTest2< DataType::QAsymmS8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_3, DepthToSpaceTest3< DataType::QAsymmS8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_4, DepthToSpaceTest4< DataType::QAsymmS8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_1, DepthToSpaceTest1< DataType::QAsymmU8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_2, DepthToSpaceTest2< DataType::QAsymmU8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_3, DepthToSpaceTest3< DataType::QAsymmU8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_4, DepthToSpaceTest4< DataType::QAsymmU8 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_1, DepthToSpaceTest1< DataType::QSymmS16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_2, DepthToSpaceTest2< DataType::QSymmS16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_3, DepthToSpaceTest3< DataType::QSymmS16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_4, DepthToSpaceTest4< DataType::QSymmS16 >, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_1, DepthToSpaceTest1< DataType::Float32 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_2, DepthToSpaceTest2< DataType::Float32 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_3, DepthToSpaceTest3< DataType::Float32 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_4, DepthToSpaceTest4< DataType::Float32 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_1, DepthToSpaceTest1< DataType::Float16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_2, DepthToSpaceTest2< DataType::Float16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_3, DepthToSpaceTest3< DataType::Float16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_4, DepthToSpaceTest4< DataType::Float16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_1, DepthToSpaceTest1< DataType::QAsymmS8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_2, DepthToSpaceTest2< DataType::QAsymmS8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_3, DepthToSpaceTest3< DataType::QAsymmS8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_4, DepthToSpaceTest4< DataType::QAsymmS8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_1, DepthToSpaceTest1< DataType::QAsymmU8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_2, DepthToSpaceTest2< DataType::QAsymmU8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_3, DepthToSpaceTest3< DataType::QAsymmU8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_4, DepthToSpaceTest4< DataType::QAsymmU8 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_1, DepthToSpaceTest1< DataType::QSymmS16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_2, DepthToSpaceTest2< DataType::QSymmS16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_3, DepthToSpaceTest3< DataType::QSymmS16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_4, DepthToSpaceTest4< DataType::QSymmS16 >, DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0Dim3Float32, StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition0Float32
StridedSliceShrinkAxisMaskBitPosition0Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition1Float32, StridedSliceShrinkAxisMaskBitPosition1Float32Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition2Float32
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition3Float32, StridedSliceShrinkAxisMaskBitPosition3Float32Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition0And1Float32
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And2Float32, StridedSliceShrinkAxisMaskBitPosition0And2Float32Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition0And3Float32
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And1And3Float32, StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0Uint8, StridedSliceShrinkAxisMaskBitPosition0Uint8Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition1Uint8
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition2Uint8, StridedSliceShrinkAxisMaskBitPosition2Uint8Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition3Uint8
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And1Uint8, StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition0And2Uint8
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And3Uint8, StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (GatherMultiDimParamsMultiDimIndicesFloat32, GatherMultiDimParamsMultiDimIndicesFloat32Test) ARMNN_AUTO_TEST_CASE_WITH_THF(GatherMultiDimParamsMultiDimIndicesFloat16
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test GatherMultiDimParamsMultiDimIndicesFloat16Test BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsFloat)
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsFloat)
BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsInt8)
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsInt8)
BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsUint8)
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsUint8)
BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsInt16)
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsInt16)
ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dFloatNchw, SimpleTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleTransposeConvolution2dFloatNhwc
DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dInt8Nchw, SimpleTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dUint8Nchw, SimpleTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dInt16Nchw, SimpleTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(SimpleTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dFloatNchw, SimpleTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, false, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedSimpleTransposeConvolution2dFloatNhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dInt8Nchw, SimpleTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedSimpleTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dUint8Nchw, SimpleTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedSimpleTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dInt16Nchw, SimpleTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedSimpleTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dFloatNchw, PaddedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(PaddedTransposeConvolution2dFloatNhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dInt8Nchw, PaddedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(PaddedTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dUint8Nchw, PaddedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(PaddedTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dInt16Nchw, PaddedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(PaddedTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dFloatNchw, PaddedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, false, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedPaddedTransposeConvolution2dFloatNhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dInt8Nchw, PaddedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedPaddedTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dUint8Nchw, PaddedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedPaddedTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dInt16Nchw, PaddedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedPaddedTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dFloatNchw, StridedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedTransposeConvolution2dFloatNhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dInt8Nchw, StridedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dUint8Nchw, StridedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dInt16Nchw, StridedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(StridedTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dFloatNchw, StridedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, false, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedStridedTransposeConvolution2dFloatNhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dInt8Nchw, StridedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedStridedTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dUint8Nchw, StridedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedStridedTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dInt16Nchw, StridedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, true, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(UnbiasedStridedTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dFloatNchw, MultiChannelTransposeConvolution2dTest< DataType::Float32, DataType::Float32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(MultiChannelTransposeConvolution2dFloatNhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dInt8Nchw, MultiChannelTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(MultiChannelTransposeConvolution2dInt8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dUint8Nchw, MultiChannelTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(MultiChannelTransposeConvolution2dUint8Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dInt16Nchw, MultiChannelTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 >, DataLayout::NCHW) ARMNN_AUTO_TEST_CASE_WITH_THF(MultiChannelTransposeConvolution2dInt16Nhwc
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (TransposeConvolution2dPerAxisQuantTestNchw, TransposeConvolution2dPerAxisQuantTest, DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF (TransposeConvolution2dPerAxisQuantTestNhwc, TransposeConvolution2dPerAxisQuantTest, DataLayout::NHWC)
Variables
SimpleConvolution2d3x3QSymm16Test
true
DataLayout::NCHW Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTest
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC false
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW Convolution2dPerAxisQuantTest
DepthwiseConvolution2dUint8Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DepthwiseConvolution2dDepthMul1Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DepthwiseConvolution2dDepthMul1Int16Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DepthwiseConvolution2dDepthMul1Uint8Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DepthwiseConvolution2dAsymmetricTest
SimpleMaxPooling2dSize2x2Stride2x2Int16Test
false SimpleMaxPooling2dSize3x3Stride2x4Int16Test
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test IgnorePaddingAveragePooling2dSize3x2Stride2x2Test
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test false InstanceNormFloat32Test
Typedef Documentation
FactoryType
using FactoryType = RefWorkloadFactory
Definition at line 20 of file RefLayerTests.cpp.
Function Documentation
ARMNN_AUTO_TEST_CASE() [1/40]
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest LstmLayerInt16WithCifgWithPeepholeNoProjectionTest LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16ConstantTest ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_1 , DepthToSpaceTest1< DataType::Float32 > , DataLayout::NCHW)
Referenced by BOOST_AUTO_TEST_CASE().
ARMNN_AUTO_TEST_CASE() [2/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_2 , DepthToSpaceTest2< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [3/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_3 , DepthToSpaceTest3< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [4/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat32_4 , DepthToSpaceTest4< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [5/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_1 , DepthToSpaceTest1< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [6/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_2 , DepthToSpaceTest2< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [7/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_3 , DepthToSpaceTest3< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [8/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwFloat16_4 , DepthToSpaceTest4< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [9/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_1 , DepthToSpaceTest1< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [10/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_2 , DepthToSpaceTest2< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [11/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_3 , DepthToSpaceTest3< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [12/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt8_4 , DepthToSpaceTest4< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [13/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_1 , DepthToSpaceTest1< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [14/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_2 , DepthToSpaceTest2< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [15/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_3 , DepthToSpaceTest3< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [16/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwUint8_4 , DepthToSpaceTest4< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [17/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_1 , DepthToSpaceTest1< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [18/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_2 , DepthToSpaceTest2< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [19/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_3 , DepthToSpaceTest3< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [20/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNchwInt16_4 , DepthToSpaceTest4< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE() [21/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_1 , DepthToSpaceTest1< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [22/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_2 , DepthToSpaceTest2< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [23/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_3 , DepthToSpaceTest3< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [24/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat32_4 , DepthToSpaceTest4< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [25/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_1 , DepthToSpaceTest1< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [26/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_2 , DepthToSpaceTest2< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [27/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_3 , DepthToSpaceTest3< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [28/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcFloat16_4 , DepthToSpaceTest4< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [29/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_1 , DepthToSpaceTest1< DataType::QAsymmS8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [30/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_2 , DepthToSpaceTest2< DataType::QAsymmS8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [31/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_3 , DepthToSpaceTest3< DataType::QAsymmS8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [32/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt8_4 , DepthToSpaceTest4< DataType::QAsymmS8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [33/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_1 , DepthToSpaceTest1< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [34/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_2 , DepthToSpaceTest2< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [35/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_3 , DepthToSpaceTest3< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [36/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcUint8_4 , DepthToSpaceTest4< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [37/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_1 , DepthToSpaceTest1< DataType::QSymmS16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [38/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_2 , DepthToSpaceTest2< DataType::QSymmS16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [39/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_3 , DepthToSpaceTest3< DataType::QSymmS16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE() [40/40]
ARMNN_AUTO_TEST_CASE (DepthToSpaceNhwcInt16_4 , DepthToSpaceTest4< DataType::QSymmS16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [1/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleConvolution2d3x5QSymm16Nhwc , SimpleConvolution2d3x5QSymm16Test , true , DataLayout::NHWC)
Referenced by BOOST_AUTO_TEST_CASE().
ARMNN_AUTO_TEST_CASE_WITH_THF() [2/168]
DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedConvolution2dSquareStride2x2Nhwc , SimpleConvolution2d3x3Stride2x2Test , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [3/168]
DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleConvolution2dAsymmetricPadding , Convolution2dAsymmetricPaddingTest , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [4/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleConvolution2dAsymmetricPaddingNhwc , Convolution2dAsymmetricPaddingTest , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [5/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcBFloat16 , Convolution2d3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [6/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3Nhwc , Convolution2d3x3Dilation3x3Test< DataType::Float32, DataType::Float32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [7/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcInt8 , Convolution2d3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [8/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcUint8 , Convolution2d3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [9/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Dilation3x3NhwcInt16 , Convolution2d3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [10/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcBFloat16 , Convolution2d2x3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [11/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3Nhwc , Convolution2d2x3x3Dilation3x3Test< DataType::Float32, DataType::Float32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [12/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcInt8 , Convolution2d2x3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [13/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcUint8 , Convolution2d2x3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [14/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x3x3Dilation3x3NhwcInt16 , Convolution2d2x3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [15/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcBFloat16 , Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::BFloat16, DataType::BFloat16 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [16/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3Nhwc , Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::Float32, DataType::Float32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [17/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcInt8 , Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::QAsymmS8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [18/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcUint8 , Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::QAsymmU8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [19/168]
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d2x2Dilation2x2Padding2x2Stride3x3NhwcInt16 , Convolution2d2x2Dilation2x2Padding2x2Stride3x3Test< DataType::QSymmS16, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [20/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2dPerAxisQuantTestNhwc , Convolution2dPerAxisQuantTest , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [21/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Stride2x2Bf16 , Convolution2d3x3Stride2x2BFloat16Test , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [22/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (Convolution2d3x3Stride2x2BFloat16SmallValue , Convolution2d3x3Stride2x2BFloat16SmallValueTest , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [23/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedDepthwiseConvolution2dUint8 , DepthwiseConvolution2dUint8Test , false , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [24/168]
DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleDepthwiseConvolution2d3x3Dilation3x3Nhwc , SimpleDepthwiseConvolution2d3x3Dilation3x3NhwcTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [25/168]
DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3Nhwc , DepthwiseConvolution2d3x3Dilation3x3Test< DataType::Float32, DataType::Float32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [26/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcBFloat16 , DepthwiseConvolution2d3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [27/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcInt8 , DepthwiseConvolution2d3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [28/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcUint8 , DepthwiseConvolution2d3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [29/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d3x3Dilation3x3NhwcInt16 , DepthwiseConvolution2d3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [30/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3Nhwc , DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::Float32, DataType::Float32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [31/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcBFloat16 , DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::BFloat16, DataType::BFloat16 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [32/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcInt8 , DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::QAsymmS8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [33/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcUint8 , DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::QAsymmU8, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [34/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2d2x3x3Dilation3x3NhwcInt16 , DepthwiseConvolution2d2x3x3Dilation3x3Test< DataType::QSymmS16, DataType::Signed32 > , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [35/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dMult2 , DepthwiseConvolution2dMult2Test< armnn::DataType::Float32, armnn::DataType::Float32 > , false , armnn::DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [36/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dMult2BFloat16 , DepthwiseConvolution2dMult2Test< armnn::DataType::BFloat16, armnn::DataType::BFloat16 > , false , armnn::DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [37/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dDepthMul1Uint8 , DepthwiseConvolution2dDepthMul1Uint8Test , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [38/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedDepthwiseConvolution2dDepthMul1 , DepthwiseConvolution2dDepthMul1Test , false , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [39/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dDepthMul1Nhwc , DepthwiseConvolution2dDepthMul1Test , true , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [40/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedDepthwiseConvolution2dDepthMul1Nhwc , DepthwiseConvolution2dDepthMul1Test , false , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [41/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dAsymmetric , DepthwiseConvolution2dAsymmetricTest , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [42/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dAsymmetricNhwc , DepthwiseConvolution2dAsymmetricTest , true , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [43/168]
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dDepthMul64 , DepthwiseConvolution2dDepthMul64Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [44/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dPerAxisQuantTestNchw , DepthwiseConvolution2dPerAxisQuantTest , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [45/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (DepthwiseConvolution2dPerAxisQuantTestNhwc , DepthwiseConvolution2dPerAxisQuantTest , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [46/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleMaxPooling2dSize2x2Stride2x2Uint8 , SimpleMaxPooling2dSize2x2Stride2x2Uint8Test , false)
ARMNN_AUTO_TEST_CASE_WITH_THF() [47/168]
false ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleMaxPooling2dSize3x3Stride2x4Uint8 , SimpleMaxPooling2dSize3x3Stride2x4Uint8Test , false)
ARMNN_AUTO_TEST_CASE_WITH_THF() [48/168]
false false ARMNN_AUTO_TEST_CASE_WITH_THF (IgnorePaddingSimpleAveragePooling2dNoPadding , IgnorePaddingSimpleAveragePooling2dNoPaddingTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [49/168]
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (IgnorePaddingSimpleAveragePooling2dNoPaddingInt16 , IgnorePaddingSimpleAveragePooling2dNoPaddingInt16Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [50/168]
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test false ARMNN_AUTO_TEST_CASE_WITH_THF (IgnorePaddingAveragePooling2dSize3x2Stride2x2NoPadding , IgnorePaddingAveragePooling2dSize3x2Stride2x2Test , true)
ARMNN_AUTO_TEST_CASE_WITH_THF() [51/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nchw , InstanceNormFloat16Test , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [52/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat32Nhwc , InstanceNormFloat32Test , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [53/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nhwc , InstanceNormFloat16Test , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [54/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat32Nchw2 , InstanceNormFloat32Test2 , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [55/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nchw2 , InstanceNormFloat16Test2 , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [56/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat32Nhwc2 , InstanceNormFloat32Test2 , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [57/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (InstanceNormFloat16Nhwc2 , InstanceNormFloat16Test2 , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [58/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (ConcatUint8DifferentInputOutputQParam , ConcatDifferentInputOutputQParamTest< DataType::QAsymmU8 > , true)
ARMNN_AUTO_TEST_CASE_WITH_THF() [59/168]
true ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinear , SimpleResizeBilinearTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [60/168]
true DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearInt8 , SimpleResizeBilinearTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [61/168]
true DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearUint16 , SimpleResizeBilinearTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [62/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopFloat16 , ResizeBilinearNopTest< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [63/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopUint8 , ResizeBilinearNopTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [64/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMin , ResizeBilinearSqMinTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [65/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinInt8 , ResizeBilinearSqMinTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [66/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinUint16 , SimpleResizeBilinearTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [67/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinFloat16 , ResizeBilinearMinTest< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [68/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinUint8 , ResizeBilinearMinTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [69/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMag , ResizeBilinearMagTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [70/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagInt8 , ResizeBilinearMagTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [71/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagUint16 , SimpleResizeBilinearTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [72/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearFloat16 , HalfPixelCentersResizeBilinearTest< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [73/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearUint8 , HalfPixelCentersResizeBilinearTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [74/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinear , AlignCornersResizeBilinearTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [75/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearInt8 , AlignCornersResizeBilinearTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [76/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearUint16 , AlignCornersResizeBilinearTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [77/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopNhwcFloat16 , ResizeBilinearNopTest< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [78/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearNopUint8Nhwc , ResizeBilinearNopTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [79/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearNhwc , SimpleResizeBilinearTest< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [80/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearInt8Nhwc , SimpleResizeBilinearTest< DataType::QAsymmS8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [81/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeBilinearUint16Nhwc , ResizeBilinearNopTest< DataType::QSymmS16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [82/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinNhwcFloat16 , ResizeBilinearSqMinTest< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [83/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearSqMinUint8Nhwc , ResizeBilinearSqMinTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [84/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinNhwc , ResizeBilinearMinTest< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [85/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinInt8Nhwc , ResizeBilinearMinTest< DataType::QAsymmS8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [86/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMinUint16Nhwc , ResizeBilinearNopTest< DataType::QSymmS16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [87/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagNhwcFloat16 , ResizeBilinearMagTest< DataType::Float16 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [88/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeBilinearMagUint8Nhwc , ResizeBilinearMagTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [89/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearNhwc , HalfPixelCentersResizeBilinearTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [90/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearInt8Nhwc , HalfPixelCentersResizeBilinearTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [91/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeBilinearUint16Nhwc , HalfPixelCentersResizeBilinearTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [92/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearFloat16Nhwc , AlignCornersResizeBilinearTest< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [93/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeBilinearUint8Nhwc , AlignCornersResizeBilinearTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [94/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighbor , SimpleResizeNearestNeighborTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [95/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighborUint8 , SimpleResizeNearestNeighborTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [96/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNop , ResizeNearestNeighborNopTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [97/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNopUint8 , ResizeNearestNeighborNopTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [98/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMin , ResizeNearestNeighborSqMinTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [99/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMinUint8 , ResizeNearestNeighborSqMinTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [100/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMin , ResizeNearestNeighborMinTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [101/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMinUint8 , ResizeNearestNeighborMinTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [102/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMag , ResizeNearestNeighborMagTest< DataType::Float32 > , DataLayout::NCHW , 0. 10f, 50 , 0. 11f, 20)
ARMNN_AUTO_TEST_CASE_WITH_THF() [103/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMagUint8 , ResizeNearestNeighborMagTest< DataType::QAsymmU8 > , DataLayout::NCHW , 0. 10f, 50 , 0. 11f, 20)
ARMNN_AUTO_TEST_CASE_WITH_THF() [104/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbour , HalfPixelCentersResizeNearestNeighbourTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [105/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourInt8 , HalfPixelCentersResizeNearestNeighbourTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [106/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourUint16 , HalfPixelCentersResizeNearestNeighbourTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [107/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourFloat16 , AlignCornersResizeNearestNeighbourTest< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [108/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourUint8 , AlignCornersResizeNearestNeighbourTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [109/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNopNhwc , ResizeNearestNeighborNopTest< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [110/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborNopUint8Nhwc , ResizeNearestNeighborNopTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [111/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighborNhwc , SimpleResizeNearestNeighborTest< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [112/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleResizeNearestNeighborUint8Nhwc , SimpleResizeNearestNeighborTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [113/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMinNhwc , ResizeNearestNeighborSqMinTest< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [114/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborSqMinUint8Nhwc , ResizeNearestNeighborSqMinTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [115/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMinNhwc , ResizeNearestNeighborMinTest< DataType::Float32 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [116/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMinUint8Nhwc , ResizeNearestNeighborMinTest< DataType::QAsymmU8 > , DataLayout::NHWC)
ARMNN_AUTO_TEST_CASE_WITH_THF() [117/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMagNhwc , ResizeNearestNeighborMagTest< DataType::Float32 > , DataLayout::NHWC , 0. 10f, 50 , 0. 11f, 20)
ARMNN_AUTO_TEST_CASE_WITH_THF() [118/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (ResizeNearestNeighborMagUint8Nhwc , ResizeNearestNeighborMagTest< DataType::QAsymmU8 > , DataLayout::NHWC , 0. 10f, 50 , 0. 11f, 20)
ARMNN_AUTO_TEST_CASE_WITH_THF() [119/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourNchw , HalfPixelCentersResizeNearestNeighbourTest< DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [120/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourInt8Nchw , HalfPixelCentersResizeNearestNeighbourTest< DataType::QAsymmS8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [121/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (HalfPixelCentersResizeNearestNeighbourUint16Nchw , HalfPixelCentersResizeNearestNeighbourTest< DataType::QSymmS16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [122/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourFloat16Nchw , AlignCornersResizeNearestNeighbourTest< DataType::Float16 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [123/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (AlignCornersResizeNearestNeighbourUint8Nchw , AlignCornersResizeNearestNeighbourTest< DataType::QAsymmU8 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [124/168]
true DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (L2Normalization2dShape , L2Normalization2dShapeTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [125/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerFloat32WithCifgWithPeepholeNoProjection , LstmLayerFloat32WithCifgWithPeepholeNoProjectionTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [126/168]
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerFloat32NoCifgWithPeepholeWithProjection , LstmLayerFloat32NoCifgWithPeepholeWithProjectionTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [127/168]
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerInt16NoCifgNoPeepholeNoProjection , LstmLayerInt16NoCifgNoPeepholeNoProjectionTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [128/168]
LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest LstmLayerInt16WithCifgWithPeepholeNoProjectionTest ARMNN_AUTO_TEST_CASE_WITH_THF (LstmLayerInt16NoCifgWithPeepholeWithProjection , LstmLayerInt16NoCifgWithPeepholeWithProjectionTest)
ARMNN_AUTO_TEST_CASE_WITH_THF() [129/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0Dim3Float32 , StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [130/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition1Float32 , StridedSliceShrinkAxisMaskBitPosition1Float32Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [131/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition3Float32 , StridedSliceShrinkAxisMaskBitPosition3Float32Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [132/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And2Float32 , StridedSliceShrinkAxisMaskBitPosition0And2Float32Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [133/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And1And3Float32 , StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [134/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0Uint8 , StridedSliceShrinkAxisMaskBitPosition0Uint8Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [135/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition2Uint8 , StridedSliceShrinkAxisMaskBitPosition2Uint8Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [136/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And1Uint8 , StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [137/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (StridedSliceShrinkAxisMaskBitPosition0And3Uint8 , StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [138/168]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test ARMNN_AUTO_TEST_CASE_WITH_THF (GatherMultiDimParamsMultiDimIndicesFloat32 , GatherMultiDimParamsMultiDimIndicesFloat32Test)
ARMNN_AUTO_TEST_CASE_WITH_THF() [139/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dFloatNchw , SimpleTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [140/168]
DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dInt8Nchw , SimpleTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [141/168]
DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dUint8Nchw , SimpleTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [142/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (SimpleTransposeConvolution2dInt16Nchw , SimpleTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [143/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dFloatNchw , SimpleTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , false , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [144/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dInt8Nchw , SimpleTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [145/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dUint8Nchw , SimpleTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [146/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedSimpleTransposeConvolution2dInt16Nchw , SimpleTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [147/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dFloatNchw , PaddedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [148/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dInt8Nchw , PaddedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [149/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dUint8Nchw , PaddedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [150/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (PaddedTransposeConvolution2dInt16Nchw , PaddedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [151/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dFloatNchw , PaddedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , false , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [152/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dInt8Nchw , PaddedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [153/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dUint8Nchw , PaddedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [154/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedPaddedTransposeConvolution2dInt16Nchw , PaddedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [155/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dFloatNchw , StridedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [156/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dInt8Nchw , StridedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [157/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dUint8Nchw , StridedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [158/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (StridedTransposeConvolution2dInt16Nchw , StridedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [159/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dFloatNchw , StridedTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , false , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [160/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dInt8Nchw , StridedTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [161/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dUint8Nchw , StridedTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [162/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (UnbiasedStridedTransposeConvolution2dInt16Nchw , StridedTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , true , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [163/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dFloatNchw , MultiChannelTransposeConvolution2dTest< DataType::Float32, DataType::Float32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [164/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dInt8Nchw , MultiChannelTransposeConvolution2dTest< DataType::QAsymmS8, DataType::Signed32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [165/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dUint8Nchw , MultiChannelTransposeConvolution2dTest< DataType::QAsymmU8, DataType::Signed32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [166/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC ARMNN_AUTO_TEST_CASE_WITH_THF (MultiChannelTransposeConvolution2dInt16Nchw , MultiChannelTransposeConvolution2dTest< DataType::QSymmS16, DataType::Signed32 > , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [167/168]
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW ARMNN_AUTO_TEST_CASE_WITH_THF (TransposeConvolution2dPerAxisQuantTestNchw , TransposeConvolution2dPerAxisQuantTest , DataLayout::NCHW)
ARMNN_AUTO_TEST_CASE_WITH_THF() [168/168]
ARMNN_AUTO_TEST_CASE_WITH_THF (TransposeConvolution2dPerAxisQuantTestNhwc , TransposeConvolution2dPerAxisQuantTest , DataLayout::NHWC)
BOOST_AUTO_TEST_CASE() [1/12]
BOOST_AUTO_TEST_CASE (LstmUtilsZeroVector)
Definition at line 1429 of file RefLayerTests.cpp.
{
                               LstmUtilsZeroVectorTest(); }
BOOST_AUTO_TEST_CASE() [2/12]
BOOST_AUTO_TEST_CASE (LstmUtilsMeanStddevNormalization)
Definition at line 1431 of file RefLayerTests.cpp.
{
                               LstmUtilsMeanStddevNormalizationNoneZeroInputTest();
                               LstmUtilsMeanStddevNormalizationAllZeroInputTest();
                               LstmUtilsMeanStddevNormalizationMixedZeroInputTest(); }
BOOST_AUTO_TEST_CASE() [3/12]
BOOST_AUTO_TEST_CASE (LstmUtilsVectorBatchVectorCwiseProduct)
Definition at line 1435 of file RefLayerTests.cpp.
{
                               LstmUtilsVectorBatchVectorCwiseProductTest(); }
BOOST_AUTO_TEST_CASE() [4/12]
BOOST_AUTO_TEST_CASE (LstmUtilsVectorBatchVectorAdd)
Definition at line 1437 of file RefLayerTests.cpp.
References AdditionAfterMaxPoolTest(), ARMNN_AUTO_TEST_CASE(), ARMNN_AUTO_TEST_CASE_WITH_THF(), armnn::ConvertBf16ToFp32, ConvertBf16ToFp32Test(), armnn::ConvertFp32ToBf16, ConvertFp32ToBf16Test(), Debug1dBFloat16Test(), Debug1dFloat32Test(), Debug1dInt16Test(), Debug1dUint8Test(), Debug2dBFloat16Test(), Debug2dFloat32Test(), Debug2dInt16Test(), Debug2dUint8Test(), Debug3dBFloat16Test(), Debug3dFloat32Test(), Debug3dInt16Test(), Debug3dUint8Test(), Debug4dBFloat16Test(), Debug4dFloat32Test(), Debug4dInt16Test(), Debug4dUint8Test(), Gather1dParamsFloat16Test(), Gather1dParamsFloat32Test(), Gather1dParamsInt16Test(), Gather1dParamsInt32Test(), Gather1dParamsUint8Test(), GatherMultiDimParamsFloat16Test(), GatherMultiDimParamsFloat32Test(), GatherMultiDimParamsInt16Test(), GatherMultiDimParamsInt32Test(), GatherMultiDimParamsMultiDimIndicesFloat16Test(), GatherMultiDimParamsMultiDimIndicesFloat32Test(), GatherMultiDimParamsMultiDimIndicesInt16Test(), GatherMultiDimParamsMultiDimIndicesInt32Test(), GatherMultiDimParamsMultiDimIndicesUint8Test(), GatherMultiDimParamsUint8Test(), LstmLayerFloat32NoCifgNoPeepholeNoProjectionTest(), LstmLayerFloat32NoCifgWithPeepholeWithProjectionTest(), LstmLayerFloat32NoCifgWithPeepholeWithProjectionWithLayerNormTest(), LstmLayerFloat32WithCifgWithPeepholeNoProjectionTest(), LstmLayerInt16NoCifgNoPeepholeNoProjectionInt16ConstantTest(), LstmLayerInt16NoCifgNoPeepholeNoProjectionTest(), LstmLayerInt16NoCifgWithPeepholeWithProjectionTest(), LstmLayerInt16WithCifgWithPeepholeNoProjectionTest(), armnn::NCHW, armnn::NHWC, armnn::QLstm, QLstmTest(), QLstmTest1(), QLstmTest2(), SimpleConvertFp16ToFp32Test(), SimpleConvertFp32ToFp16Test(), SpaceToBatchNdMultiBlockFloat16Test(), SpaceToBatchNdMultiBlockFloat32Test(), SpaceToBatchNdMultiBlockNhwcFloat16Test(), SpaceToBatchNdMultiBlockNhwcFloat32Test(), SpaceToBatchNdMultiBlockNhwcUint16Test(), SpaceToBatchNdMultiBlockNhwcUint8Test(), SpaceToBatchNdMultiBlockUint16Test(), SpaceToBatchNdMultiBlockUint8Test(), SpaceToBatchNdMultiChannelsFloat16Test(), SpaceToBatchNdMultiChannelsFloat32Test(), SpaceToBatchNdMultiChannelsNhwcFloat16Test(), SpaceToBatchNdMultiChannelsNhwcFloat32Test(), SpaceToBatchNdMultiChannelsNhwcUint16Test(), SpaceToBatchNdMultiChannelsNhwcUint8Test(), SpaceToBatchNdMultiChannelsUint16Test(), SpaceToBatchNdMultiChannelsUint8Test(), SpaceToBatchNdPaddingFloat16Test(), SpaceToBatchNdPaddingFloat32Test(), SpaceToBatchNdPaddingNhwcFloat16Test(), SpaceToBatchNdPaddingNhwcFloat32Test(), SpaceToBatchNdPaddingNhwcUint16Test(), SpaceToBatchNdPaddingNhwcUint8Test(), SpaceToBatchNdPaddingUint16Test(), SpaceToBatchNdPaddingUint8Test(), SpaceToBatchNdSimpleFloat16Test(), SpaceToBatchNdSimpleFloat32Test(), SpaceToBatchNdSimpleNhwcFloat16Test(), SpaceToBatchNdSimpleNhwcFloat32Test(), SpaceToBatchNdSimpleNhwcUint16Test(), SpaceToBatchNdSimpleNhwcUint8Test(), SpaceToBatchNdSimpleUint16Test(), SpaceToBatchNdSimpleUint8Test(), SpaceToDepthNchwAsymmQ8Test(), SpaceToDepthNchwFloat32Test1(), SpaceToDepthNchwFloat32Test2(), SpaceToDepthNchwQSymm16Test(), SpaceToDepthNhwcAsymmQ8Test(), SpaceToDepthNhwcFloat32Test1(), SpaceToDepthNhwcFloat32Test2(), SpaceToDepthNhwcQSymm16Test(), StridedSlice2dFloat32Test(), StridedSlice2dInt16Test(), StridedSlice2dReverseFloat32Test(), StridedSlice2dReverseInt16Test(), StridedSlice2dReverseUint8Test(), StridedSlice2dUint8Test(), StridedSlice3dFloat32Test(), StridedSlice3dInt16Test(), StridedSlice3dReverseFloat32Test(), StridedSlice3dReverseInt16Test(), StridedSlice3dReverseUint8Test(), StridedSlice3dUint8Test(), StridedSlice4dFloat32Test(), StridedSlice4dInt16Test(), StridedSlice4dReverseFloat32Test(), StridedSlice4dReverseInt16Test(), StridedSlice4dReverseUint8Test(), StridedSlice4dUint8Test(), StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test(), StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test(), StridedSliceShrinkAxisMaskBitPosition0And1Float32Test(), StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test(), StridedSliceShrinkAxisMaskBitPosition0And2Float32Test(), StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test(), StridedSliceShrinkAxisMaskBitPosition0And3Float32Test(), StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test(), StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test(), StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test(), StridedSliceShrinkAxisMaskBitPosition0Float32Test(), StridedSliceShrinkAxisMaskBitPosition0Uint8Test(), StridedSliceShrinkAxisMaskBitPosition1Float32Test(), StridedSliceShrinkAxisMaskBitPosition1Uint8Test(), StridedSliceShrinkAxisMaskBitPosition2Float32Test(), StridedSliceShrinkAxisMaskBitPosition2Uint8Test(), StridedSliceShrinkAxisMaskBitPosition3Float32Test(), StridedSliceShrinkAxisMaskBitPosition3Uint8Test(), StridedSliceShrinkAxisMaskCTSFloat32Test(), StridedSliceShrinkAxisMaskFloat32Test(), StridedSliceShrinkAxisMaskInt16Test(), StridedSliceShrinkAxisMaskUint8Test(), StridedSliceSimpleRangeMaskFloat32Test(), StridedSliceSimpleRangeMaskInt16Test(), StridedSliceSimpleRangeMaskUint8Test(), StridedSliceSimpleStrideFloat32Test(), StridedSliceSimpleStrideInt16Test(), and StridedSliceSimpleStrideUint8Test().
{
                               LstmUtilsVectorBatchVectorAddTest(); }
BOOST_AUTO_TEST_CASE() [5/12]
StridedSliceShrinkAxisMaskBitPosition0Float32Test StridedSliceShrinkAxisMaskBitPosition2Float32Test StridedSliceShrinkAxisMaskBitPosition0And1Float32Test StridedSliceShrinkAxisMaskBitPosition0And3Float32Test StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test StridedSliceShrinkAxisMaskBitPosition1Uint8Test StridedSliceShrinkAxisMaskBitPosition3Uint8Test StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test GatherMultiDimParamsMultiDimIndicesFloat16Test BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsFloat)
Definition at line 1851 of file RefLayerTests.cpp.
 {
     DetectionPostProcessRegularNmsFloatTest<RefWorkloadFactory>();
 }
BOOST_AUTO_TEST_CASE() [6/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsFloat)
Definition at line 1855 of file RefLayerTests.cpp.
 {
     DetectionPostProcessFastNmsFloatTest<RefWorkloadFactory>();
 }
BOOST_AUTO_TEST_CASE() [7/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsInt8)
Definition at line 1859 of file RefLayerTests.cpp.
References DetectionPostProcessRegularNmsQuantizedTest(), and armnn::QAsymmS8.
 {
     DetectionPostProcessRegularNmsQuantizedTest<
         RefWorkloadFactory, DataType::QAsymmS8>();
 }
BOOST_AUTO_TEST_CASE() [8/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsInt8)
Definition at line 1864 of file RefLayerTests.cpp.
References DetectionPostProcessRegularNmsQuantizedTest(), and armnn::QAsymmS8.
 {
     DetectionPostProcessRegularNmsQuantizedTest<
         RefWorkloadFactory, DataType::QAsymmS8>();
 }
BOOST_AUTO_TEST_CASE() [9/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsUint8)
Definition at line 1869 of file RefLayerTests.cpp.
References DetectionPostProcessRegularNmsQuantizedTest(), and armnn::QAsymmU8.
 {
     DetectionPostProcessRegularNmsQuantizedTest<
         RefWorkloadFactory, DataType::QAsymmU8>();
 }
BOOST_AUTO_TEST_CASE() [10/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsUint8)
Definition at line 1874 of file RefLayerTests.cpp.
References DetectionPostProcessRegularNmsQuantizedTest(), and armnn::QAsymmU8.
 {
     DetectionPostProcessRegularNmsQuantizedTest<
         RefWorkloadFactory, DataType::QAsymmU8>();
 }
BOOST_AUTO_TEST_CASE() [11/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessRegularNmsInt16)
Definition at line 1879 of file RefLayerTests.cpp.
References DetectionPostProcessRegularNmsQuantizedTest(), and armnn::QSymmS16.
 {
     DetectionPostProcessRegularNmsQuantizedTest<
         RefWorkloadFactory, DataType::QSymmS16>();
 }
BOOST_AUTO_TEST_CASE() [12/12]
BOOST_AUTO_TEST_CASE (DetectionPostProcessFastNmsInt16)
Definition at line 1884 of file RefLayerTests.cpp.
References ARMNN_AUTO_TEST_CASE(), ARMNN_AUTO_TEST_CASE_WITH_THF(), BOOST_AUTO_TEST_SUITE_END(), DequantizeOffsetAsymmInt8Test(), DequantizeOffsetUint8Test(), DequantizeSimpleAsymmInt8Test(), DequantizeSimpleInt16Test(), DequantizeSimpleInt16ToFp16Test(), DequantizeSimpleInt8Test(), DequantizeSimpleInt8ToFp16Test(), DequantizeSimpleUint8Test(), DequantizeSimpleUint8ToFp16Test(), DetectionPostProcessFastNmsQuantizedTest(), armnn::LogicalAnd, LogicalAndBroadcast1Test(), LogicalAndBroadcast2Test(), LogicalAndBroadcast3Test(), LogicalAndIntTest(), LogicalAndTest(), armnn::LogicalNot, LogicalNotIntTest(), LogicalNotTest(), armnn::LogicalOr, LogicalOrBroadcast1Test(), LogicalOrBroadcast2Test(), LogicalOrBroadcast3Test(), LogicalOrIntTest(), LogicalOrTest(), armnn::NCHW, armnn::NHWC, armnn::QSymmS16, QuantizeClampAsymmInt8Test(), QuantizeClampInt16Test(), QuantizeClampInt8Test(), QuantizeClampUint8Test(), QuantizeSimpleUint8Test(), Slice1dFloat32Test(), Slice1dInt16Test(), Slice1dUint8Test(), Slice2dFloat32Test(), Slice2dInt16Test(), Slice2dUint8Test(), Slice3dFloat32Test(), Slice3dInt16Test(), Slice3dUint8Test(), Slice4dFloat32Test(), Slice4dInt16Test(), Slice4dUint8Test(), StackAxis0Float32Test(), StackFloat16Test(), StackOutput3DInputs3Float32Test(), StackOutput4DAxis1Float32Test(), StackOutput4DAxis2Float32Test(), StackOutput4DAxis3Float32Test(), StackOutput5DFloat32Test(), and TransposeConvolution2dPerAxisQuantTest().
 {
     DetectionPostProcessFastNmsQuantizedTest<
         RefWorkloadFactory, DataType::QSymmS16>();
 }
Variable Documentation
Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTest
DataLayout::NCHW DataLayout::NCHW Convolution2dAsymmetricPaddingLargerThanHalfKernelSizeTest
Definition at line 62 of file RefLayerTests.cpp.
Convolution2dPerAxisQuantTest
DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW Convolution2dPerAxisQuantTest
Definition at line 200 of file RefLayerTests.cpp.
DepthwiseConvolution2dAsymmetricTest
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DepthwiseConvolution2dAsymmetricTest
Definition at line 358 of file RefLayerTests.cpp.
DepthwiseConvolution2dDepthMul1Int16Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DepthwiseConvolution2dDepthMul1Int16Test
Definition at line 338 of file RefLayerTests.cpp.
DepthwiseConvolution2dDepthMul1Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DepthwiseConvolution2dDepthMul1Test
Definition at line 334 of file RefLayerTests.cpp.
DepthwiseConvolution2dDepthMul1Uint8Test
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DepthwiseConvolution2dDepthMul1Uint8Test
Definition at line 343 of file RefLayerTests.cpp.
DepthwiseConvolution2dUint8Test
DepthwiseConvolution2dUint8Test
Definition at line 228 of file RefLayerTests.cpp.
false
DataLayout::NHWC DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW armnn::DataLayout::NCHW armnn::DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW false
Definition at line 77 of file RefLayerTests.cpp.
IgnorePaddingAveragePooling2dSize3x2Stride2x2Test
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test IgnorePaddingAveragePooling2dSize3x2Stride2x2Test
Definition at line 421 of file RefLayerTests.cpp.
InstanceNormFloat32Test
false false IgnorePaddingSimpleAveragePooling2dNoPaddingUint8Test false InstanceNormFloat32Test
Definition at line 461 of file RefLayerTests.cpp.
SimpleConvolution2d3x3QSymm16Test
SimpleConvolution2d3x3QSymm16Test
Definition at line 50 of file RefLayerTests.cpp.
SimpleMaxPooling2dSize2x2Stride2x2Int16Test
SimpleMaxPooling2dSize2x2Stride2x2Int16Test
Definition at line 377 of file RefLayerTests.cpp.
SimpleMaxPooling2dSize3x3Stride2x4Int16Test
false SimpleMaxPooling2dSize3x3Stride2x4Int16Test
Definition at line 383 of file RefLayerTests.cpp.
true
DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC DataLayout::NCHW DataLayout::NHWC DataLayout::NHWC DataLayout::NHWC true
Definition at line 50 of file RefLayerTests.cpp.