ArmNN: src/backends/backendsCommon/test/layerTests/ReshapeTestImpl.hpp File Reference
ReshapeTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <ResolveType.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > SimpleReshapeTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 5 > Reshape5dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > ReshapeBooleanTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
Reshape5dTest()
LayerTestResult<T, 5> Reshape5dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 111 of file ReshapeTestImpl.cpp.
References TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo inputTensorInfo;
     armnn::TensorInfo outputTensorInfo;
     unsigned int inputShape[] = { 2, 2, 8, 1, 1 };
     unsigned int outputShape[] = { 2, 2, 2, 2, 2 };
     inputTensorInfo = armnn::TensorInfo(5, inputShape, ArmnnType);
     inputTensorInfo.SetQuantizationScale(1.0f);
     outputTensorInfo = armnn::TensorInfo(5, outputShape, ArmnnType);
     outputTensorInfo.SetQuantizationScale(1.0f);
     auto input = ConvertToDataType<ArmnnType>(
         {
             0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f,
             8.0f, 9.0f, 10.0f, 11.0f, 12.0f, 13.0f, 14.0f, 15.0f,
             16.0f, 17.0f, 18.0f, 19.0f, 20.0f, 21.0f, 22.0f, 23.0f,
             24.0f, 25.0f, 26.0f, 27.0f, 28.0f, 29.0f, 30.0f, 31.0f,
         },
         inputTensorInfo);
     auto outputExpected = ConvertToDataType<ArmnnType>(
         {
             0.0f, 1.0f,
             2.0f, 3.0f,
             4.0f, 5.0f,
             6.0f, 7.0f,
             8.0f, 9.0f,
             10.0f, 11.0f,
             12.0f, 13.0f,
             14.0f, 15.0f,
             16.0f, 17.0f,
             18.0f, 19.0f,
             20.0f, 21.0f,
             22.0f, 23.0f,
             24.0f, 25.0f,
             26.0f, 27.0f,
             28.0f, 29.0f,
             30.0f, 31.0f,
         },
         outputTensorInfo);
     return SimpleReshapeTestImpl<T, 5>(
         workloadFactory, memoryManager, tensorHandleFactory, inputTensorInfo, outputTensorInfo, input, outputExpected);
 }
ReshapeBooleanTest()
LayerTestResult<uint8_t, 2> ReshapeBooleanTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 173 of file ReshapeTestImpl.cpp.
References armnn::Boolean, and TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo inputTensorInfo;
     armnn::TensorInfo outputTensorInfo;
     unsigned int inputShape[] = { 1, 4 };
     unsigned int outputShape[] = { 2, 2 };
     inputTensorInfo = armnn::TensorInfo(2, inputShape, armnn::DataType::Boolean);
     inputTensorInfo.SetQuantizationScale(1.0f);
     outputTensorInfo = armnn::TensorInfo(2, outputShape, armnn::DataType::Boolean);
     outputTensorInfo.SetQuantizationScale(1.0f);
     const std::vector<uint8_t> input = { true, false, false, true };
     const std::vector<uint8_t> outputExpected = { true, false, false, true };
     return SimpleReshapeTestImpl<uint8_t, 2>(
         workloadFactory, memoryManager, tensorHandleFactory, inputTensorInfo, outputTensorInfo, input, outputExpected);
 }
SimpleReshapeTest()
LayerTestResult<T, 4> SimpleReshapeTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 58 of file ReshapeTestImpl.cpp.
References TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo inputTensorInfo;
     armnn::TensorInfo outputTensorInfo;
     unsigned int inputShape[] = { 2, 2, 3, 3 };
     unsigned int outputShape[] = { 2, 2, 9, 1 };
     inputTensorInfo = armnn::TensorInfo(4, inputShape, ArmnnType);
     inputTensorInfo.SetQuantizationScale(1.0f);
     outputTensorInfo = armnn::TensorInfo(4, outputShape, ArmnnType);
     outputTensorInfo.SetQuantizationScale(1.0f);
     auto input = ConvertToDataType<ArmnnType>(
         {
             0.0f, 1.0f, 2.0f,
             3.0f, 4.0f, 5.0f,
             6.0f, 7.0f, 8.0f,
             9.0f, 10.0f, 11.0f,
             12.0f, 13.0f, 14.0f,
             15.0f, 16.0f, 17.0f,
             18.0f, 19.0f, 20.0f,
             21.0f, 22.0f, 23.0f,
             24.0f, 25.0f, 26.0f,
             27.0f, 28.0f, 29.0f,
             30.0f, 31.0f, 32.0f,
             33.0f, 34.0f, 35.0f,
         },
         inputTensorInfo);
     auto outputExpected = ConvertToDataType<ArmnnType>(
         {
             0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f,
             9.0f, 10.0f, 11.0f, 12.0f, 13.0f, 14.0f, 15.0f, 16.0f, 17.0f,
             18.0f, 19.0f, 20.0f, 21.0f, 22.0f, 23.0f, 24.0f, 25.0f, 26.0f,
             27.0f, 28.0f, 29.0f, 30.0f, 31.0f, 32.0f, 33.0f, 34.0f, 35.0f,
         },
         outputTensorInfo);
     return SimpleReshapeTestImpl<T, 4>(
         workloadFactory, memoryManager, tensorHandleFactory, inputTensorInfo, outputTensorInfo, input, outputExpected);
 }