ArmNN: src/backends/backendsCommon/test/layerTests/SpaceToBatchNdTestImpl.hpp File Reference
SpaceToBatchNdTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <Half.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > SpaceToBatchNdSimpleFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiChannelsFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiBlockFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdPaddingFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiChannelsFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiBlockFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdPaddingFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiChannelsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiBlockUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdPaddingUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdSimpleNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiChannelsNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdMultiBlockNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToBatchNdPaddingNhwcFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdSimpleNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiChannelsNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdMultiBlockNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToBatchNdPaddingNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdSimpleNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiChannelsNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdMultiBlockNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToBatchNdPaddingNhwcUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdSimpleUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiChannelsUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiBlockUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdPaddingUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdSimpleNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiChannelsNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdMultiBlockNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToBatchNdPaddingNhwcUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
SpaceToBatchNdMultiBlockFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiBlockFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 364 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::Float16>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiBlockFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 324 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::Float32>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiBlockNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 484 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiBlockNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 444 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiBlockNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 604 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                        memoryManager,
                                                                        tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiBlockNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 524 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                        memoryManager,
                                                                        tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiBlockUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 564 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdMultiBlockUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiBlockUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 404 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiBlockTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiChannelsFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 354 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::Float16>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiChannelsFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 314 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::Float32>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdMultiChannelsNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 474 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                          memoryManager,
                                                                          tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdMultiChannelsNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 434 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                          memoryManager,
                                                                          tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiChannelsNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 594 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                           memoryManager,
                                                                           tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiChannelsNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 514 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                           memoryManager,
                                                                           tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdMultiChannelsUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 554 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdMultiChannelsUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdMultiChannelsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 394 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdMultiChannelsTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
SpaceToBatchNdPaddingFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdPaddingFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 374 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::Float16>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
SpaceToBatchNdPaddingFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdPaddingFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 334 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdPaddingNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 494 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdPaddingNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 454 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdPaddingNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 614 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                     memoryManager,
                                                                     tensorHandleFactory);
 }
SpaceToBatchNdPaddingNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdPaddingNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 534 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                     memoryManager,
                                                                     tensorHandleFactory);
 }
SpaceToBatchNdPaddingUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdPaddingUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 574 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory);
 }
SpaceToBatchNdPaddingUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdPaddingUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 414 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdPaddingTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory);
 }
SpaceToBatchNdSimpleFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 344 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::Float16>(workloadFactory,
                                                               memoryManager,
                                                               tensorHandleFactory);
 }
SpaceToBatchNdSimpleFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdSimpleFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 304 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::Float32>(workloadFactory,
                                                               memoryManager,
                                                               tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToBatchNdSimpleNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 464 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::Float16>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcFloat32Test()
LayerTestResult<float, 4> SpaceToBatchNdSimpleNhwcFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 424 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::Float32>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdSimpleNhwcUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 584 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdSimpleNhwcUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdSimpleNhwcUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 504 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleNhwcTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
SpaceToBatchNdSimpleUint16Test()
LayerTestResult<int16_t, 4> SpaceToBatchNdSimpleUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 544 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
SpaceToBatchNdSimpleUint8Test()
LayerTestResult<uint8_t, 4> SpaceToBatchNdSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 384 of file SpaceToBatchNdTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToBatchNdSimpleTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }