ArmNN: src/backends/backendsCommon/test/SpaceToDepthEndToEndTestImpl.cpp File Reference
SpaceToDepthEndToEndTestImpl.cpp File Reference
#include "SpaceToDepthEndToEndTestImpl.hpp"
#include "ResolveType.hpp"
#include "EndToEndTestImpl.hpp"
#include <armnn/INetwork.hpp>
#include <armnnUtils/Permute.hpp>
#include <armnnUtils/DataLayoutIndexed.hpp>
#include <backendsCommon/test/DataLayoutUtils.hpp>
#include <test/TestUtils.hpp>
#include <boost/test/unit_test.hpp>
Functions
void SpaceToDepthNhwcEndToEndTest1 (const std::vector< armnn::BackendId > &defaultBackends)
void SpaceToDepthNchwEndToEndTest1 (const std::vector< armnn::BackendId > &defaultBackends)
void SpaceToDepthNhwcEndToEndTest2 (const std::vector< armnn::BackendId > &defaultBackends)
void SpaceToDepthNchwEndToEndTest2 (const std::vector< armnn::BackendId > &defaultBackends)
Function Documentation
SpaceToDepthNchwEndToEndTest1()
void SpaceToDepthNchwEndToEndTest1 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 129 of file SpaceToDepthEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const unsigned int blockSize = 2;
     TensorShape inputShape{1, 2, 2, 1};
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     TensorShape outputShape{1, 1, 1, 4};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
     {
         1.0f, 2.0f, 3.0f, 4.0f
     });
     std::vector<float> expectedOutputData = std::vector<float>(
     {
         1.0f, 2.0f, 3.0f, 4.0f
     });
     SpaceToDepthEndToEnd(defaultBackends,
                          DataLayout::NCHW,
                          inputTensorInfo,
                          outputTensorInfo,
                          inputData,
                          expectedOutputData,
                          blockSize);
 }
SpaceToDepthNchwEndToEndTest2()
void SpaceToDepthNchwEndToEndTest2 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 191 of file SpaceToDepthEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const unsigned int blockSize = 2;
     TensorShape inputShape{1, 2, 2, 2};
     TensorShape outputShape{1, 1, 1, 8};
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
     {
         1.4f, 2.3f, 3.2f, 4.1f, 5.4f, 6.3f, 7.2f, 8.1f
     });
     std::vector<float> expectedOutputData = std::vector<float>(
     {
         1.4f, 2.3f, 3.2f, 4.1f, 5.4f, 6.3f, 7.2f, 8.1f
     });
     SpaceToDepthEndToEnd(defaultBackends,
                          DataLayout::NCHW,
                          inputTensorInfo,
                          outputTensorInfo,
                          inputData,
                          expectedOutputData,
                          blockSize);
 }
SpaceToDepthNhwcEndToEndTest1()
void SpaceToDepthNhwcEndToEndTest1 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 98 of file SpaceToDepthEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NHWC.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const unsigned int blockSize = 2;
     TensorShape inputShape{1, 2, 2, 1};
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     TensorShape outputShape{1, 1, 1, 4};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
     {
         1.0f, 2.0f, 3.0f, 4.0f
     });
     std::vector<float> expectedOutputData = std::vector<float>(
     {
         1.0f, 2.0f, 3.0f, 4.0f
     });
     SpaceToDepthEndToEnd(defaultBackends,
                          DataLayout::NHWC,
                          inputTensorInfo,
                          outputTensorInfo,
                          inputData,
                          expectedOutputData,
                          blockSize);
 }
SpaceToDepthNhwcEndToEndTest2()
void SpaceToDepthNhwcEndToEndTest2 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 160 of file SpaceToDepthEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NHWC.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const unsigned int blockSize = 2;
     TensorShape inputShape{1, 2, 2, 2};
     TensorShape outputShape{1, 1, 1, 8};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
     {
         1.4f, 2.3f, 3.2f, 4.1f, 5.4f, 6.3f, 7.2f, 8.1f
     });
     std::vector<float> expectedOutputData = std::vector<float>(
     {
         1.4f, 2.3f, 3.2f, 4.1f, 5.4f, 6.3f, 7.2f, 8.1f
     });
     SpaceToDepthEndToEnd(defaultBackends,
                          DataLayout::NHWC,
                          inputTensorInfo,
                          outputTensorInfo,
                          inputData,
                          expectedOutputData,
                          blockSize);
 }