ArmNN: src/backends/backendsCommon/test/TensorCopyUtils.cpp File Reference
TensorCopyUtils.cpp File Reference
#include "TensorCopyUtils.hpp"
#include <Half.hpp>
Functions
void CopyDataToITensorHandle (armnn::ITensorHandle *tensorHandle, const void *memory)
void CopyDataFromITensorHandle (void *memory, const armnn::ITensorHandle *tensorHandle)
void AllocateAndCopyDataToITensorHandle (armnn::ITensorHandle *tensorHandle, const void *memory)
Function Documentation
AllocateAndCopyDataToITensorHandle()
void AllocateAndCopyDataToITensorHandle (armnn::ITensorHandle * tensorHandle, const void * memory)
Definition at line 19 of file TensorCopyUtils.cpp.
References ITensorHandle::Allocate(), and CopyDataToITensorHandle().
Referenced by CompareBatchNormTest(), CompareConvolution2dTestImpl(), CompareDepthwiseConvolution2dTestImpl(), Convolution1dTestImpl(), Convolution2dPerAxisQuantTest(), DepthwiseConvolution2dAsymmetricTestImpl(), DepthwiseConvolution2dDepthMul1TestImpl(), DepthwiseConvolution2dPerAxisQuantTest(), DepthwiseConvolution2dTestImpl(), DetectionPostProcessImpl(), SimpleConvolution2dNhwcTestImpl(), SimpleConvolution2dTestImpl(), SimpleFullyConnectedTestImpl(), and TransposeConvolution2dPerAxisQuantTest().
 {
     tensorHandle->Allocate();
     CopyDataToITensorHandle(tensorHandle, memory);
 }
CopyDataFromITensorHandle()
void CopyDataFromITensorHandle (void * memory, const armnn::ITensorHandle * tensorHandle)
Definition at line 14 of file TensorCopyUtils.cpp.
References ITensorHandle::CopyOutTo().
Referenced by AdditionAfterMaxPoolTest(), AdditionBroadcast1ElementTestImpl(), AdditionBroadcastTestImpl(), BoundedReLuTestCommon(), BoundedReLuUint8UpperAndLowerBoundTest(), CompareActivationTestImpl(), CompareAdditionTest(), CompareBatchNormTest(), CompareConvolution2dTestImpl(), CompareDepthwiseConvolution2dTestImpl(), CompareMultiplicationTest(), ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), ConstantLinearActivationTestCommon(), ConvertBf16ToFp32Test(), ConvertFp32ToBf16Test(), Convolution1dTestImpl(), Convolution2dPerAxisQuantTest(), DepthwiseConvolution2dAsymmetricTestImpl(), DepthwiseConvolution2dDepthMul1TestImpl(), DepthwiseConvolution2dPerAxisQuantTest(), DepthwiseConvolution2dTestImpl(), DetectionPostProcessImpl(), ElementwiseTestHelper(), ElementwiseUnaryTestHelper(), FakeQuantizationTest(), L2Normalization2dShapeTest(), Pad2dTestCommon(), Pad3dTestCommon(), Pad4dTestCommon(), PermuteOutputForConcat(), PermuteTensorData(), PreluTest(), RankTest(), SimpleActivationTest(), SimpleConvertFp16ToFp32Test(), SimpleConvertFp32ToFp16Test(), SimpleConvolution2dNhwcTestImpl(), SimpleConvolution2dTestImpl(), SimpleFillTest(), SimpleFloorTest(), SimpleFullyConnectedTestImpl(), SimplePermuteTestImpl(), SimpleTransposeTestImpl(), SqrtNNTest(), and TransposeConvolution2dPerAxisQuantTest().
 {
     tensorHandle->CopyOutTo(memory);
 }
CopyDataToITensorHandle()
void CopyDataToITensorHandle (armnn::ITensorHandle * tensorHandle, const void * memory)
Definition at line 9 of file TensorCopyUtils.cpp.
References ITensorHandle::CopyInFrom().
Referenced by AdditionAfterMaxPoolTest(), AdditionBroadcast1ElementTestImpl(), AdditionBroadcastTestImpl(), AllocateAndCopyDataToITensorHandle(), BOOST_AUTO_TEST_CASE(), BoundedReLuTestCommon(), BoundedReLuUint8UpperAndLowerBoundTest(), CompareActivationTestImpl(), CompareAdditionTest(), CompareBatchNormTest(), CompareConvolution2dTestImpl(), CompareDepthwiseConvolution2dTestImpl(), CompareMultiplicationTest(), ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), ConstantLinearActivationTestCommon(), ConvertBf16ToFp32Test(), ConvertFp32ToBf16Test(), Convolution1dTestImpl(), Convolution2dPerAxisQuantTest(), DepthwiseConvolution2dAsymmetricTestImpl(), DepthwiseConvolution2dDepthMul1TestImpl(), DepthwiseConvolution2dPerAxisQuantTest(), DepthwiseConvolution2dTestImpl(), DetectionPostProcessImpl(), ElementwiseTestHelper(), ElementwiseUnaryTestHelper(), FakeQuantizationTest(), L2Normalization2dShapeTest(), Pad2dTestCommon(), Pad3dTestCommon(), Pad4dTestCommon(), PermuteTensorData(), PreluTest(), RankTest(), SimpleActivationTest(), SimpleConvertFp16ToFp32Test(), SimpleConvertFp32ToFp16Test(), SimpleConvolution2dNhwcTestImpl(), SimpleConvolution2dTestImpl(), SimpleFillTest(), SimpleFloorTest(), SimpleFullyConnectedTestImpl(), SimplePermuteTestImpl(), SimpleTransposeTestImpl(), SqrtNNTest(), and TransposeConvolution2dPerAxisQuantTest().
 {
     tensorHandle->CopyInFrom(memory);
 }