ArmNN: src/armnnOnnxParser/test/GetInputsOutputs.cpp File Reference
GetInputsOutputs.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "../OnnxParser.hpp"
#include "ParserPrototxtFixture.hpp"
#include <onnx/onnx.pb.h>
#include "google/protobuf/stubs/logging.h"
Typedefs
using ModelPtr = std::unique_ptr< onnx::ModelProto >
Functions
BOOST_FIXTURE_TEST_CASE (GetInput, GetInputsOutputsMainFixture)
BOOST_FIXTURE_TEST_CASE (GetOutput, GetInputsOutputsMainFixture)
BOOST_FIXTURE_TEST_CASE (GetEmptyInputs, GetEmptyInputsOutputsFixture)
BOOST_AUTO_TEST_CASE (GetInputsNullModel)
BOOST_AUTO_TEST_CASE (GetOutputsNullModel)
BOOST_FIXTURE_TEST_CASE (GetInputsMultipleInputs, GetInputsMultipleFixture)
Typedef Documentation
ModelPtr
using ModelPtr = std::unique_ptr<onnx::ModelProto>
Definition at line 12 of file GetInputsOutputs.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (GetInputsNullModel)
Definition at line 147 of file GetInputsOutputs.cpp.
References OnnxParser::LoadModelFromString().
 {
     BOOST_CHECK_THROW(armnnOnnxParser::OnnxParser::LoadModelFromString(""), armnn::InvalidArgumentException);
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (GetOutputsNullModel)
Definition at line 152 of file GetInputsOutputs.cpp.
References OnnxParser::LoadModelFromString().
 {
     auto silencer = google::protobuf::LogSilencer(); //get rid of errors from protobuf
     BOOST_CHECK_THROW(armnnOnnxParser::OnnxParser::LoadModelFromString("nknnk"), armnn::ParseException);
 }
BOOST_FIXTURE_TEST_CASE() [1/4]
BOOST_FIXTURE_TEST_CASE (GetInput , GetInputsOutputsMainFixture)
Definition at line 69 of file GetInputsOutputs.cpp.
References OnnxParser::GetInputs(), and OnnxParser::LoadModelFromString().
 {
     ModelPtr model = armnnOnnxParser::OnnxParser::LoadModelFromString(m_Prototext.c_str());
     std::vector<std::string> tensors = armnnOnnxParser::OnnxParser::GetInputs(model);
     BOOST_CHECK_EQUAL(1, tensors.size());
     BOOST_CHECK_EQUAL("Input", tensors[0]);
 }
BOOST_FIXTURE_TEST_CASE() [2/4]
BOOST_FIXTURE_TEST_CASE (GetOutput , GetInputsOutputsMainFixture)
Definition at line 78 of file GetInputsOutputs.cpp.
References OnnxParser::GetOutputs(), and OnnxParser::LoadModelFromString().
 {
     ModelPtr model = armnnOnnxParser::OnnxParser::LoadModelFromString(m_Prototext.c_str());
     std::vector<std::string> tensors = armnnOnnxParser::OnnxParser::GetOutputs(model);
     BOOST_CHECK_EQUAL(1, tensors.size());
     BOOST_CHECK_EQUAL("Output", tensors[0]);
 }
BOOST_FIXTURE_TEST_CASE() [3/4]
BOOST_FIXTURE_TEST_CASE (GetEmptyInputs , GetEmptyInputsOutputsFixture)
Definition at line 140 of file GetInputsOutputs.cpp.
References OnnxParser::GetInputs(), and OnnxParser::LoadModelFromString().
 {
     ModelPtr model = armnnOnnxParser::OnnxParser::LoadModelFromString(m_Prototext.c_str());
     std::vector<std::string> tensors = armnnOnnxParser::OnnxParser::GetInputs(model);
     BOOST_CHECK_EQUAL(0, tensors.size());
 }
BOOST_FIXTURE_TEST_CASE() [4/4]
BOOST_FIXTURE_TEST_CASE (GetInputsMultipleInputs , GetInputsMultipleFixture)
Definition at line 244 of file GetInputsOutputs.cpp.
References BOOST_AUTO_TEST_SUITE_END(), OnnxParser::GetInputs(), and OnnxParser::LoadModelFromString().
 {
     ModelPtr model = armnnOnnxParser::OnnxParser::LoadModelFromString(m_Prototext.c_str());
     std::vector<std::string> tensors = armnnOnnxParser::OnnxParser::GetInputs(model);
     BOOST_CHECK_EQUAL(2, tensors.size());
     BOOST_CHECK_EQUAL("Input0", tensors[0]);
     BOOST_CHECK_EQUAL("Input1", tensors[1]);
 }