ArmNN: PacketBuffer Class Reference
PacketBuffer Class Reference
#include <PacketBuffer.hpp>
Public Member Functions
PacketBuffer (unsigned int maxSize)
~PacketBuffer ()
const unsigned char * GetReadableData () const override
unsigned int GetSize () const override
void MarkRead () override
void Commit (unsigned int size) override
void Release () override
unsigned char * GetWritableData () override
void Destroy () override
release the memory held and reset internal point to null.
Public Member Functions inherited from IPacketBuffer
virtual ~IPacketBuffer ()
Public Member Functions inherited from IReadOnlyPacketBuffer
virtual ~IReadOnlyPacketBuffer ()
Detailed Description
Definition at line 18 of file PacketBuffer.hpp.
Constructor & Destructor Documentation
PacketBuffer()
PacketBuffer (unsigned int maxSize)
Definition at line 16 of file PacketBuffer.cpp.
     : m_MaxSize(maxSize)
     , m_Size(0)
 {
     m_Data = std::make_unique<unsigned char[]>(m_MaxSize);
 }
~PacketBuffer()
~PacketBuffer () inline
Definition at line 23 of file PacketBuffer.hpp.
References PacketBuffer::Commit(), PacketBuffer::Destroy(), PacketBuffer::GetReadableData(), PacketBuffer::GetSize(), PacketBuffer::GetWritableData(), PacketBuffer::MarkRead(), and PacketBuffer::Release().
 {}
Member Function Documentation
Commit()
void Commit (unsigned int size) override virtual
Implements IPacketBuffer.
Definition at line 38 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     if (size > m_MaxSize)
     {
         throw armnn::RuntimeException("Cannot commit [" + std::to_string(size) +
                 "] bytes which is more than the maximum size of the buffer [" + std::to_string(m_MaxSize) + "]");
     }
     m_Size = size;
 }
Destroy()
void Destroy () override virtual
release the memory held and reset internal point to null.
After this function is invoked the PacketBuffer is unusable.
Implements IPacketBuffer.
Definition at line 58 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     m_Data.reset(nullptr);
     m_Size = 0;
     m_MaxSize = 0;
 }
GetReadableData()
const unsigned char * GetReadableData () const override virtual
Implements IReadOnlyPacketBuffer.
Definition at line 23 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     return m_Data.get();
 }
GetSize()
unsigned int GetSize () const override virtual
Implements IReadOnlyPacketBuffer.
Definition at line 28 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     return m_Size;
 }
GetWritableData()
unsigned char * GetWritableData () override virtual
Implements IPacketBuffer.
Definition at line 53 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     return m_Data.get();
 }
MarkRead()
void MarkRead () override virtual
Implements IReadOnlyPacketBuffer.
Definition at line 33 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     m_Size = 0;
 }
Release()
void Release () override virtual
Implements IPacketBuffer.
Definition at line 48 of file PacketBuffer.cpp.
Referenced by PacketBuffer::~PacketBuffer().
 {
     m_Size = 0;
 }
The documentation for this class was generated from the following files:
src/profiling/PacketBuffer.hpp
src/profiling/PacketBuffer.cpp