ArmNN: CommandHandler Class Reference
CommandHandler Class Reference
#include <CommandHandler.hpp>
Public Member Functions
CommandHandler (uint32_t timeout, bool stopAfterTimeout, arm::pipe::CommandHandlerRegistry &commandHandlerRegistry, arm::pipe::PacketVersionResolver &packetVersionResolver)
~CommandHandler ()
void SetTimeout (uint32_t timeout)
void SetStopAfterTimeout (bool stopAfterTimeout)
void Start (IProfilingConnection &profilingConnection)
void Stop ()
bool IsRunning () const
Detailed Description
Definition at line 22 of file CommandHandler.hpp.
Constructor & Destructor Documentation
CommandHandler()
CommandHandler (uint32_t timeout, bool stopAfterTimeout, arm::pipe::CommandHandlerRegistry & commandHandlerRegistry, arm::pipe::PacketVersionResolver & packetVersionResolver) inline
Definition at line 25 of file CommandHandler.hpp.
         : m_Timeout(timeout),
           m_StopAfterTimeout(stopAfterTimeout),
           m_IsRunning(false),
           m_KeepRunning(false),
           m_CommandThread(),
           m_CommandHandlerRegistry(commandHandlerRegistry),
           m_PacketVersionResolver(packetVersionResolver)
     {}
~CommandHandler()
~CommandHandler () inline
Definition at line 37 of file CommandHandler.hpp.
References CommandHandler::Stop().
 { Stop(); }
Member Function Documentation
IsRunning()
bool IsRunning () const inline
Definition at line 44 of file CommandHandler.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and CommandHandler::Start().
 { return m_IsRunning.load(); }
SetStopAfterTimeout()
void SetStopAfterTimeout (bool stopAfterTimeout) inline
Definition at line 40 of file CommandHandler.hpp.
References CommandHandler::Start(), and CommandHandler::Stop().
Referenced by BOOST_AUTO_TEST_CASE().
 { m_StopAfterTimeout.store(stopAfterTimeout); }
SetTimeout()
void SetTimeout (uint32_t timeout) inline
Definition at line 39 of file CommandHandler.hpp.
 { m_Timeout.store(timeout); }
Start()
void Start (IProfilingConnection & profilingConnection)
Definition at line 17 of file CommandHandler.cpp.
References CommandHandler::IsRunning().
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandler::SetStopAfterTimeout(), and ProfilingService::Update().
 {
     if (IsRunning())
     {
         return;
     }
     if (m_CommandThread.joinable())
     {
         m_CommandThread.join();
     }
     m_IsRunning.store(true);
     m_KeepRunning.store(true);
     m_CommandThread = std::thread(&CommandHandler::HandleCommands, this, std::ref(profilingConnection));
 }
Stop()
void Stop ()
Definition at line 34 of file CommandHandler.cpp.
References ARMNN_ASSERT, ARMNN_LOG, IProfilingConnection::IsOpen(), IProfilingConnection::ReadPacket(), armnn::warning, and Exception::what().
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::GetSendTimelinePacket(), CommandHandler::SetStopAfterTimeout(), ProfilingService::Update(), and CommandHandler::~CommandHandler().
 {
     m_KeepRunning.store(false);
     if (m_CommandThread.joinable())
     {
         m_CommandThread.join();
     }
 }
The documentation for this class was generated from the following files:
src/profiling/CommandHandler.hpp
src/profiling/CommandHandler.cpp