ArmNN: QASymm8Decoder Class Reference
QASymm8Decoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
QASymm8Decoder (const uint8_t *data, const float scale, const int32_t offset)
QASymm8Decoder (const float scale, const int32_t offset)
float Get () const override
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const unsigned int channelMultiplier, const bool isDepthwise) override
Public Member Functions inherited from TypedIterator< const uint8_t, Decoder< float > >
TypedIterator (const uint8_t *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
TypedIterator & SetIndex (unsigned int index, unsigned int axisIndex=0) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< const uint8_t, Decoder< float > >
const uint8_t * m_Iterator
const uint8_t * m_Start
Detailed Description
Definition at line 124 of file BaseIterator.hpp.
Constructor & Destructor Documentation
QASymm8Decoder() [1/2]
QASymm8Decoder (const uint8_t * data, const float scale, const int32_t offset) inline
Definition at line 127 of file BaseIterator.hpp.
         : TypedIterator(data), m_Scale(scale), m_Offset(offset) {}
QASymm8Decoder() [2/2]
QASymm8Decoder (const float scale, const int32_t offset) inline
Definition at line 130 of file BaseIterator.hpp.
         : QASymm8Decoder(nullptr, scale, offset) {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, const unsigned int channelMultiplier, const bool isDepthwise) inline override virtual
Implements Decoder< float >.
Definition at line 137 of file BaseIterator.hpp.
References armnn::Dequantize, TensorShape::GetNumElements(), armnn::IgnoreUnused(), and BaseIterator::operator[]().
     {
         IgnoreUnused(channelMultiplier, isDepthwise);
         const unsigned int size = tensorShape.GetNumElements();
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         for (uint32_t i = 0; i < size; ++i)
         {
             this->operator[](i);
             decodedTensor.emplace_back(armnn::Dequantize(*m_Iterator, m_Scale, m_Offset));
         }
         return decodedTensor;
     }
Get()
float Get () const inline override virtual
Implements Decoder< float >.
Definition at line 133 of file BaseIterator.hpp.
References armnn::Dequantize.
     {
         return armnn::Dequantize(*m_Iterator, m_Scale, m_Offset);
     }
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp