ArmNN: QuantizationInput Class Reference
QuantizationInput Class Reference
QuantizationInput for specific pass ID, can list a corresponding raw data file for each LayerBindingId.
#include <QuantizationInput.hpp>
Public Member Functions
QuantizationInput (const unsigned int passId, const armnn::LayerBindingId bindingId, const std::string fileName)
Constructor for QuantizationInput.
QuantizationInput (const QuantizationInput &other)
void AddEntry (const armnn::LayerBindingId bindingId, const std::string fileName)
std::vector< float > GetDataForEntry (const armnn::LayerBindingId bindingId) const
std::vector< armnn::LayerBindingId > GetLayerBindingIds () const
Retrieve Layer Binding IDs for this QuantizationInput.
unsigned long GetNumberOfInputs () const
Get number of inputs for this QuantizationInput.
unsigned int GetPassId () const
Retrieve Pass ID for this QuantizationInput.
std::string GetFileName (const armnn::LayerBindingId bindingId) const
Retrieve filename path for specified Layer Binding ID.
~QuantizationInput () noexcept
Destructor.
Detailed Description
QuantizationInput for specific pass ID, can list a corresponding raw data file for each LayerBindingId.
Definition at line 16 of file QuantizationInput.hpp.
Constructor & Destructor Documentation
QuantizationInput() [1/2]
QuantizationInput (const unsigned int passId, const armnn::LayerBindingId bindingId, const std::string fileName)
Constructor for QuantizationInput.
Definition at line 16 of file QuantizationInput.cpp.
                              :
     m_PassId(passId)
 {
     m_LayerBindingIdToFileName.emplace(bindingId, fileName);
 }
QuantizationInput() [2/2]
QuantizationInput (const QuantizationInput & other)
Definition at line 24 of file QuantizationInput.cpp.
References QuantizationInput::AddEntry(), QuantizationInput::GetFileName(), QuantizationInput::GetLayerBindingIds(), and QuantizationInput::GetPassId().
 {
     m_PassId = other.GetPassId();
     m_LayerBindingIdToFileName.clear();
     for (armnn::LayerBindingId bindingId : other.GetLayerBindingIds())
     {
         std::string filename = other.GetFileName(bindingId);
         AddEntry(bindingId, filename);
     }
 }
~QuantizationInput()
~QuantizationInput () noexcept
Destructor.
Definition at line 99 of file QuantizationInput.cpp.
 {
 }
Member Function Documentation
AddEntry()
void AddEntry (const armnn::LayerBindingId bindingId, const std::string fileName)
Definition at line 35 of file QuantizationInput.cpp.
Referenced by QuantizationInput::QuantizationInput().
 {
     m_LayerBindingIdToFileName.emplace(bindingId, fileName);
 }
GetDataForEntry()
std::vector< float > GetDataForEntry (const armnn::LayerBindingId bindingId) const
Definition at line 40 of file QuantizationInput.cpp.
 {
     if (m_LayerBindingIdToFileName.at(bindingId).empty())
     {
         throw armnn::Exception("Layer binding ID not found");
     }
     std::string fileName = m_LayerBindingIdToFileName.at(bindingId);
     std::ifstream in(fileName.c_str(), std::ifstream::binary);
     if (!in.is_open())
     {
         throw armnn::Exception("Failed to open input tensor file " + fileName);
     }
     std::string line;
     std::vector<float> values;
     char* pEnd;
     while (std::getline(in, line, ' '))
     {
         values.emplace_back(std::strtof(line.c_str(), &pEnd));
     }
     return values;
 }
GetFileName()
std::string GetFileName (const armnn::LayerBindingId bindingId) const
Retrieve filename path for specified Layer Binding ID.
Definition at line 86 of file QuantizationInput.cpp.
Referenced by QuantizationInput::QuantizationInput().
 {
     auto iterator = m_LayerBindingIdToFileName.find(bindingId);
     if (iterator != m_LayerBindingIdToFileName.end())
     {
         return m_LayerBindingIdToFileName.at(bindingId);
     }
     else
     {
         throw armnn::Exception("Could not retrieve filename for binding ID " + std::to_string(bindingId));
     }
 }
GetLayerBindingIds()
std::vector< armnn::LayerBindingId > GetLayerBindingIds () const
Retrieve Layer Binding IDs for this QuantizationInput.
Definition at line 65 of file QuantizationInput.cpp.
Referenced by QuantizationInput::QuantizationInput().
 {
     std::vector<armnn::LayerBindingId> layerBindingIDs;
     for (auto iterator = m_LayerBindingIdToFileName.begin(); iterator != m_LayerBindingIdToFileName.end(); ++iterator)
     {
         layerBindingIDs.emplace_back(iterator->first);
     }
     return layerBindingIDs;
 }
GetNumberOfInputs()
unsigned long GetNumberOfInputs () const
Get number of inputs for this QuantizationInput.
Definition at line 76 of file QuantizationInput.cpp.
 {
     return m_LayerBindingIdToFileName.size();
 }
GetPassId()
unsigned int GetPassId () const
Retrieve Pass ID for this QuantizationInput.
Definition at line 81 of file QuantizationInput.cpp.
Referenced by QuantizationInput::QuantizationInput().
 {
     return m_PassId;
 }
The documentation for this class was generated from the following files:
src/armnnQuantizer/QuantizationInput.hpp
src/armnnQuantizer/QuantizationInput.cpp