ArmNN: MockStreamCounterBuffer Class Reference
MockStreamCounterBuffer Class Reference
#include <ProfilingMocks.hpp>
Public Member Functions
MockStreamCounterBuffer (unsigned int maxBufferSize=4096)
~MockStreamCounterBuffer ()
IPacketBufferPtr Reserve (unsigned int requestedSize, unsigned int &reservedSize) override
void Commit (IPacketBufferPtr &packetBuffer, unsigned int size, bool notifyConsumer=true) override
void Release (IPacketBufferPtr &packetBuffer) override
IPacketBufferPtr GetReadableBuffer () override
void MarkRead (IPacketBufferPtr &packetBuffer) override
void SetConsumer (IConsumer *consumer) override
void FlushReadList () override
unsigned int GetCommittedSize () const
unsigned int GetReadableSize () const
unsigned int GetReadSize () const
Public Member Functions inherited from IBufferManager
virtual ~IBufferManager ()
Detailed Description
Definition at line 277 of file ProfilingMocks.hpp.
Constructor & Destructor Documentation
MockStreamCounterBuffer()
MockStreamCounterBuffer (unsigned int maxBufferSize = 4096) inline
Definition at line 280 of file ProfilingMocks.hpp.
         : m_MaxBufferSize(maxBufferSize)
         , m_BufferList()
         , m_CommittedSize(0)
         , m_ReadableSize(0)
         , m_ReadSize(0)
     {}
~MockStreamCounterBuffer()
~MockStreamCounterBuffer () inline
Definition at line 287 of file ProfilingMocks.hpp.
 {}
Member Function Documentation
Commit()
void Commit (IPacketBufferPtr & packetBuffer, unsigned int size, bool notifyConsumer = true) inline override virtual
Implements IBufferManager.
Definition at line 303 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         packetBuffer->Commit(size);
         m_BufferList.push_back(std::move(packetBuffer));
         m_CommittedSize += size;
         if (notifyConsumer)
         {
             FlushReadList();
         }
     }
FlushReadList()
void FlushReadList () inline override virtual
Implements IBufferManager.
Definition at line 354 of file ProfilingMocks.hpp.
     {
         // notify consumer that packet is ready to read
         if (m_Consumer != nullptr)
         {
             m_Consumer->SetReadyToRead();
         }
     }
GetCommittedSize()
unsigned int GetCommittedSize () const inline
Definition at line 363 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_CommittedSize; }
GetReadableBuffer()
IPacketBufferPtr GetReadableBuffer () inline override virtual
Implements IBufferManager.
Definition at line 324 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         if (m_BufferList.empty())
         {
             return nullptr;
         }
         IPacketBufferPtr buffer = std::move(m_BufferList.back());
         m_BufferList.pop_back();
         m_ReadableSize += buffer->GetSize();
         return buffer;
     }
GetReadableSize()
unsigned int GetReadableSize () const inline
Definition at line 364 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_ReadableSize;  }
GetReadSize()
unsigned int GetReadSize () const inline
Definition at line 365 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_ReadSize;      }
MarkRead()
void MarkRead (IPacketBufferPtr & packetBuffer) inline override virtual
Implements IBufferManager.
Definition at line 338 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         m_ReadSize += packetBuffer->GetSize();
         packetBuffer->MarkRead();
     }
Release()
void Release (IPacketBufferPtr & packetBuffer) inline override virtual
Implements IBufferManager.
Definition at line 317 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         packetBuffer->Release();
     }
Reserve()
IPacketBufferPtr Reserve (unsigned int requestedSize, unsigned int & reservedSize) inline override virtual
Implements IBufferManager.
Definition at line 289 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         reservedSize = 0;
         if (requestedSize > m_MaxBufferSize)
         {
             throw armnn::InvalidArgumentException("The maximum buffer size that can be requested is [" +
                                                   std::to_string(m_MaxBufferSize) + "] bytes");
         }
         reservedSize = requestedSize;
         return std::make_unique<MockPacketBuffer>(requestedSize);
     }
SetConsumer()
void SetConsumer (IConsumer * consumer) inline override virtual
Implements IBufferManager.
Definition at line 346 of file ProfilingMocks.hpp.
     {
         if (consumer != nullptr)
         {
             m_Consumer = consumer;
         }
     }
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingMocks.hpp