ArmNN: SquashEqualSiblingsImpl< Comparable > Class Template Reference
SquashEqualSiblingsImpl< Comparable > Class Template Reference
#include <SquashEqualSiblings.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Run for every connection between a base Layer (any) and a child ComparableLayer.
Protected Member Functions
SquashEqualSiblingsImpl ()=default
~SquashEqualSiblingsImpl ()=default
Detailed Description
template<typename Comparable>
class armnn::optimizations::SquashEqualSiblingsImpl< Comparable >
Definition at line 18 of file SquashEqualSiblings.hpp.
Constructor & Destructor Documentation
SquashEqualSiblingsImpl()
SquashEqualSiblingsImpl () protected default
Referenced by SquashEqualSiblingsImpl< Comparable >::Run().
~SquashEqualSiblingsImpl()
~SquashEqualSiblingsImpl () protected default
Referenced by SquashEqualSiblingsImpl< Comparable >::Run().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Run for every connection between a base Layer (any) and a child ComparableLayer.
For all siblings of the child layer that compare equal to it, bypasses and removes them. I.e., moves the connections in the outputs of the siblings to the outputs of the child layer, so the siblings are left unconnected (and later removed).
Definition at line 25 of file SquashEqualSiblings.hpp.
References Layer::BeginOutputSlots(), InputSlot::GetConnectedOutputSlot(), OutputSlot::GetConnections(), OutputSlot::GetNumConnections(), InputSlot::GetOwningLayer(), Layer::GetPriority(), armnn::IgnoreUnused(), SquashEqualSiblingsImpl< Comparable >::SquashEqualSiblingsImpl(), armnn::swap(), and SquashEqualSiblingsImpl< Comparable >::~SquashEqualSiblingsImpl().
     {
         IgnoreUnused(graph);
         auto& child = connection.GetOwningLayer();
         if (!child.IsOutputUnconnected())
         {
             OutputSlot& baseOutput = *connection.GetConnectedOutputSlot();
             if (baseOutput.GetNumConnections() > 1)
             {
                 auto& comparableChild = *PolymorphicDowncast<Comparable*>(&child);
                 Layer* lowestPriorityChild = &child;
                 for (auto&& it : baseOutput.GetConnections())
                 {
                     Layer* sibling = &it->GetOwningLayer();
                     if ((sibling != lowestPriorityChild) && comparableChild.IsEqual(*sibling))
                     {
                         if (sibling->GetPriority() < lowestPriorityChild->GetPriority())
{
                             std::swap(sibling, lowestPriorityChild);
                         }
                         // Bypasses sibling. It will be removed as it's left unconnected.
                         auto siblingOut = sibling->BeginOutputSlots();
                         for (auto lowestPriorityChildOut = lowestPriorityChild->BeginOutputSlots();
                              lowestPriorityChildOut != lowestPriorityChild->EndOutputSlots(); ++lowestPriorityChildOut)
{
                             siblingOut->MoveAllConnections(*lowestPriorityChildOut);
                             ++siblingOut;
                         }
                     }
                 }
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/SquashEqualSiblings.hpp