ArmNN: RequestCountersPacketHandler Class Reference
RequestCountersPacketHandler Class Reference
#include <RequestCountersPacketHandler.hpp>
Public Member Functions
RequestCountersPacketHandler (uint32_t capturePeriod=LOWEST_CAPTURE_PERIOD)
std::vector< uint32_t > GetHeadersAccepted () override
void HandlePacket (const arm::pipe::Packet &packet) override
process the packet
void SetConnection (IInternalProfilingConnection *profilingConnection) override
Set a profiling connection on the handler.
Public Member Functions inherited from ILocalPacketHandler
virtual ~ILocalPacketHandler ()
Detailed Description
Definition at line 20 of file RequestCountersPacketHandler.hpp.
Constructor & Destructor Documentation
RequestCountersPacketHandler()
RequestCountersPacketHandler (uint32_t capturePeriod = LOWEST_CAPTURE_PERIOD) inline explicit
Definition at line 23 of file RequestCountersPacketHandler.hpp.
References RequestCountersPacketHandler::GetHeadersAccepted(), and RequestCountersPacketHandler::HandlePacket().
                                                                                           :
         m_CapturePeriod(capturePeriod),
         m_Connection(nullptr),
         m_CounterDirectoryMessageHeader(ConstructHeader(0, 2)) {}
Member Function Documentation
GetHeadersAccepted()
std::vector< uint32_t > GetHeadersAccepted () override virtual
Returns
lists the headers of the packets that this handler accepts only these packets will get sent to this handler. If this function returns an empty list then ALL packets will be sent to the PacketHandler i.e. a universal handler.
Implements ILocalPacketHandler.
Definition at line 21 of file RequestCountersPacketHandler.cpp.
Referenced by RequestCountersPacketHandler::RequestCountersPacketHandler().
 {
     std::vector<uint32_t> headers;
     headers.push_back(m_CounterDirectoryMessageHeader); // counter directory
     return headers;
 }
HandlePacket()
void HandlePacket (const arm::pipe::Packet & packet) override virtual
process the packet
Implements ILocalPacketHandler.
Definition at line 28 of file RequestCountersPacketHandler.cpp.
References ICounterDirectory::GetCategories(), armnn::numeric_cast(), IInternalProfilingConnection::ReturnPacket(), armnn::profiling::uint16_t_size, armnn::profiling::uint32_t_size, armnn::profiling::WriteUint16(), and armnn::profiling::WriteUint32().
Referenced by RequestCountersPacketHandler::RequestCountersPacketHandler().
 {
     if (packet.GetHeader() != m_CounterDirectoryMessageHeader)
     {
         return;
     }
     arm::pipe::PacketVersionResolver packetVersionResolver;
     DirectoryCaptureCommandHandler directoryCaptureCommandHandler(
             0, 2, packetVersionResolver.ResolvePacketVersion(0, 2).GetEncodedValue());
     directoryCaptureCommandHandler.operator()(packet);
     const ICounterDirectory& counterDirectory = directoryCaptureCommandHandler.GetCounterDirectory();
     for (auto& category : counterDirectory.GetCategories())
     {
         // Remember we need to translate the Uid's from our CounterDirectory instance to the parent one.
         std::vector<uint16_t> translatedCounters;
         for (auto const& copyUid : category->m_Counters)
         {
             translatedCounters.emplace_back(directoryCaptureCommandHandler.TranslateUIDCopyToOriginal(copyUid));
         }
         m_IdList.insert(std::end(m_IdList), std::begin(translatedCounters), std::end(translatedCounters));
     }
     SendCounterSelectionPacket();
 }
SetConnection()
void SetConnection (IInternalProfilingConnection * profilingConnection) inline override virtual
Set a profiling connection on the handler.
Only need to implement this function if the handler will be writing data back to the profiled application.
Reimplemented from ILocalPacketHandler.
Definition at line 32 of file RequestCountersPacketHandler.hpp.
     {
         m_Connection = profilingConnection;
     }
The documentation for this class was generated from the following files:
src/profiling/test/RequestCountersPacketHandler.hpp
src/profiling/test/RequestCountersPacketHandler.cpp