ArmNN: Serializer Class Reference
Serializer Class Reference
#include <Serializer.hpp>
Public Member Functions
Serializer ()
~Serializer ()
void Serialize (const armnn::INetwork &inNetwork) override
Serializes the network to ArmNN SerializedGraph.
bool SaveSerializedToStream (std::ostream &stream) override
Serializes the SerializedGraph to the stream.
Additional Inherited Members
Static Public Member Functions inherited from ISerializer
static ISerializer * CreateRaw ()
static ISerializerPtr Create ()
static void Destroy (ISerializer *serializer)
Protected Member Functions inherited from ISerializer
virtual ~ISerializer ()
Detailed Description
Definition at line 348 of file Serializer.hpp.
Constructor & Destructor Documentation
Serializer()
Serializer () inline
Definition at line 351 of file Serializer.hpp.
 {}
~Serializer()
~Serializer () inline
Definition at line 352 of file Serializer.hpp.
 {}
Member Function Documentation
SaveSerializedToStream()
bool SaveSerializedToStream (std::ostream & stream) override virtual
Serializes the SerializedGraph to the stream.
Parameters
[stream] the stream to save to
Returns
true if graph is Serialized to the Stream, false otherwise
Implements ISerializer.
Definition at line 1766 of file Serializer.cpp.
References armnn::numeric_cast().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     flatbuffers::FlatBufferBuilder& fbBuilder = m_SerializerVisitor.GetFlatBufferBuilder();
     auto bytesToWrite = armnn::numeric_cast<std::streamsize>(fbBuilder.GetSize());
     stream.write(reinterpret_cast<const char*>(fbBuilder.GetBufferPointer()), bytesToWrite);
     return !stream.bad();
 }
Serialize()
void Serialize (const armnn::INetwork & inNetwork) override virtual
Serializes the network to ArmNN SerializedGraph.
Parameters
[in] inNetwork The network to be serialized.
Implements ISerializer.
Definition at line 1748 of file Serializer.cpp.
References INetwork::Accept().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     // Iterate through to network
     inNetwork.Accept(m_SerializerVisitor);
     flatbuffers::FlatBufferBuilder& fbBuilder = m_SerializerVisitor.GetFlatBufferBuilder();
     // Create FlatBuffer SerializedGraph
     auto serializedGraph = serializer::CreateSerializedGraph(
         fbBuilder,
         fbBuilder.CreateVector(m_SerializerVisitor.GetSerializedLayers()),
         fbBuilder.CreateVector(m_SerializerVisitor.GetInputIds()),
         fbBuilder.CreateVector(m_SerializerVisitor.GetOutputIds()),
         m_SerializerVisitor.GetVersionTable());
     // Serialize the graph
     fbBuilder.Finish(serializedGraph);
 }
The documentation for this class was generated from the following files:
src/armnnSerializer/Serializer.hpp
src/armnnSerializer/Serializer.cpp