ArmNN: Network Class Reference
Network Class Reference final
Private implementation of INetwork.
#include <Network.hpp>
Public Member Functions
Network (NetworkOptions networkOptions={})
~Network ()
const Graph & GetGraph () const
Status PrintGraph () override
IConnectableLayer * AddInputLayer (LayerBindingId id, const char *name=nullptr) override
Adds an input layer to the network.
IConnectableLayer * AddArgMinMaxLayer (const ArgMinMaxDescriptor &desc, const char *name=nullptr) override
Adds an ArgMinMax layer to the network.
IConnectableLayer * AddBatchToSpaceNdLayer (const BatchToSpaceNdDescriptor &batchToSpaceNdDescriptor, const char *name=nullptr) override
Adds a batch to space ND layer to the network.
IConnectableLayer * AddComparisonLayer (const ComparisonDescriptor &comparisonDescriptor, const char *name=nullptr) override
Add a Comparison layer to the network.
IConnectableLayer * AddConcatLayer (const ConcatDescriptor &concatDescriptor, const char *name=nullptr) override
Adds a concatenation layer to the network.
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Adds a 2D convolution layer to the network.
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const char *name=nullptr) override
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const ConstTensor &biases, const char *name=nullptr) override
IConnectableLayer * AddDepthToSpaceLayer (const DepthToSpaceDescriptor &depthToSpaceDescriptor, const char *name=nullptr) override
Adds a depth to space layer to the network.
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Adds a 2D depthwise convolution layer to the network.
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const char *name=nullptr) override
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const ConstTensor &biases, const char *name=nullptr) override
IConnectableLayer * AddDequantizeLayer (const char *name=nullptr) override
Adds a Dequantize layer to the network.
IConnectableLayer * AddDetectionPostProcessLayer (const DetectionPostProcessDescriptor &descriptor, const ConstTensor &anchors, const char *name=nullptr) override
Adds a Detection PostProcess layer to the network.
IConnectableLayer * AddElementwiseUnaryLayer (const ElementwiseUnaryDescriptor &elementwiseUnaryDescriptor, const char *name=nullptr) override
Add an ElementwiseUnary layer to the network.
IConnectableLayer * AddFillLayer (const FillDescriptor &fillDescriptor, const char *name=nullptr) override
Add an Fill layer to the network.
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Adds a fully connected layer to the network.
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const char *name=nullptr) override
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const ConstTensor &biases, const char *name=nullptr) override
IConnectableLayer * AddGatherLayer (const char *name=nullptr) override
Add Gather layer to the network.
IConnectableLayer * AddGatherLayer (const GatherDescriptor &gatherDescriptor, const char *name=nullptr) override
Add Gather layer to the network.
IConnectableLayer * AddPermuteLayer (const PermuteDescriptor &permuteDescriptor, const char *name=nullptr) override
Adds a permute layer to the network.
IConnectableLayer * AddPooling2dLayer (const Pooling2dDescriptor &pooling2dDescriptor, const char *name=nullptr) override
Adds a pooling layer to the network.
IConnectableLayer * AddActivationLayer (const ActivationDescriptor &activationDescriptor, const char *name=nullptr) override
Adds an activation layer to the network.
IConnectableLayer * AddNormalizationLayer (const NormalizationDescriptor &normalizationDescriptor, const char *name=nullptr) override
Adds a normalization layer to the network.
IConnectableLayer * AddSliceLayer (const SliceDescriptor &sliceDescriptor, const char *name=nullptr) override
Adds a slice layer to the network.
IConnectableLayer * AddSoftmaxLayer (const SoftmaxDescriptor &softmaxDescriptor, const char *name=nullptr) override
Adds a softmax layer to the network.
IConnectableLayer * AddSplitterLayer (const ViewsDescriptor &splitterDescriptor, const char *name=nullptr) override
Adds a splitter layer to the network.
IConnectableLayer * AddMergerLayer (const MergerDescriptor &mergerDescriptor, const char *name=nullptr) override
Adds a concat layer to the network.
IConnectableLayer * AddAbsLayer (const char *name=nullptr) override
Add absolute layer to the network.
IConnectableLayer * AddAdditionLayer (const char *name=nullptr) override
Adds an addition layer to the network.
IConnectableLayer * AddMultiplicationLayer (const char *name=nullptr) override
Adds a multiplication layer to the network.
IConnectableLayer * AddBatchNormalizationLayer (const BatchNormalizationDescriptor &desc, const ConstTensor &mean, const ConstTensor &variance, const ConstTensor &beta, const ConstTensor &gamma, const char *name=nullptr) override
Adds a batch normalization layer to the network.
IConnectableLayer * AddRankLayer (const char *name=nullptr) override
Adds a rank layer to the network.
IConnectableLayer * AddResizeBilinearLayer (const ResizeBilinearDescriptor &resizeDesc, const char *name=nullptr) override
Adds a resize bilinear layer to the network.
IConnectableLayer * AddResizeLayer (const ResizeDescriptor &resizeDescriptor, const char *name=nullptr) override
Adds a resize layer to the network.
IConnectableLayer * AddInstanceNormalizationLayer (const InstanceNormalizationDescriptor &desc, const char *name=nullptr) override
Adds an instance normalization layer to the network.
IConnectableLayer * AddL2NormalizationLayer (const L2NormalizationDescriptor &desc, const char *name=nullptr) override
Adds an L2 normalization layer to the network.
IConnectableLayer * AddLogSoftmaxLayer (const LogSoftmaxDescriptor &logSoftmaxDescriptor, const char *name=nullptr) override
Adds a log softmax layer to the network.
IConnectableLayer * AddConstantLayer (const ConstTensor &input, const char *name=nullptr) override
Adds a layer with no inputs and a single output, which always corresponds to the passed in constant tensor.
IConnectableLayer * AddReshapeLayer (const ReshapeDescriptor &reshapeDescriptor, const char *name=nullptr) override
Adds a reshape layer to the network.
IConnectableLayer * AddSpaceToBatchNdLayer (const SpaceToBatchNdDescriptor &spaceToBatchNdDescriptor, const char *name=nullptr) override
Adds a space to batch layer to the network.
IConnectableLayer * AddSpaceToDepthLayer (const SpaceToDepthDescriptor &spaceToDepthDescriptor, const char *name=nullptr) override
Adds a space to depth layer to the network.
IConnectableLayer * AddFloorLayer (const char *name=nullptr) override
Adds a floor layer to the network.
IConnectableLayer * AddOutputLayer (LayerBindingId id, const char *name=nullptr) override
Adds an output layer to the network.
IConnectableLayer * AddLstmLayer (const LstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr) override
Add a Lstm layer to the network.
IConnectableLayer * AddDivisionLayer (const char *name=nullptr) override
Adds a division layer to the network.
IConnectableLayer * AddSubtractionLayer (const char *name=nullptr) override
Adds a subtraction layer to the network.
IConnectableLayer * AddMaximumLayer (const char *name=nullptr) override
Add a Maximum layer to the network.
IConnectableLayer * AddMeanLayer (const MeanDescriptor &meanDescriptor, const char *name=nullptr) override
Add a Mean layer to the network.
IConnectableLayer * AddPadLayer (const PadDescriptor &padDescriptor, const char *name=nullptr) override
Adds a fully pad layer to the network.
IConnectableLayer * AddQuantizeLayer (const char *name=nullptr) override
Add a quantize layer to the network.
IConnectableLayer * AddStridedSliceLayer (const StridedSliceDescriptor &stridedSliceDescriptor, const char *name=nullptr) override
Adds a strided slice layer to the network.
IConnectableLayer * AddMinimumLayer (const char *name=nullptr) override
Add a Minimum layer to the network.
IConnectableLayer * AddGreaterLayer (const char *name=nullptr) override
Add a Greater layer to the network.
IConnectableLayer * AddEqualLayer (const char *name=nullptr) override
Add a Equal layer to the network.
IConnectableLayer * AddRsqrtLayer (const char *name=nullptr) override
Add Reciprocal of square root layer to the network.
IConnectableLayer * AddMergeLayer (const char *name=nullptr) override
Adds a merge layer to the network.
IConnectableLayer * AddSwitchLayer (const char *name=nullptr) override
Adds a switch layer to the network.
IConnectableLayer * AddPreluLayer (const char *name=nullptr) override
Adds a PReLU layer to the network.
IConnectableLayer * AddTransposeConvolution2dLayer (const TransposeConvolution2dDescriptor &descriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Adds a 2D transpose convolution layer to the network.
IConnectableLayer * AddTransposeLayer (const TransposeDescriptor &transposeDescriptor, const char *name=nullptr) override
Adds a transpose layer to the network.
IConnectableLayer * AddStackLayer (const StackDescriptor &stackDescriptor, const char *name=nullptr) override
Adds a stack layer to the network.
IConnectableLayer * AddStandInLayer (const StandInDescriptor &descriptor, const char *name=nullptr) override
Add a stand-in layer for a type unknown to the Arm NN framework.
IConnectableLayer * AddQLstmLayer (const QLstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr) override
Add a QLstm layer to the network.
IConnectableLayer * AddQuantizedLstmLayer (const QuantizedLstmInputParams &params, const char *name=nullptr) override
Add a QuantizedLstm layer to the network.
IConnectableLayer * AddLogicalBinaryLayer (const LogicalBinaryDescriptor &logicalBinaryDescriptor, const char *name=nullptr) override
Adds a Logical Binary layer to the network.
void Accept (ILayerVisitor &visitor) const override
Additional Inherited Members
Static Public Member Functions inherited from INetwork
static INetwork * CreateRaw (NetworkOptions networkOptions={})
static INetworkPtr Create (NetworkOptions networkOptions={})
static void Destroy (INetwork *network)
Protected Member Functions inherited from INetwork
~INetwork ()
Detailed Description
Private implementation of INetwork.
Definition at line 28 of file Network.hpp.
Constructor & Destructor Documentation
Network()
Network (NetworkOptions networkOptions = {})
Definition at line 1177 of file Network.cpp.
 : m_NetworkOptions(networkOptions),
   m_Graph(std::make_unique<Graph>(GetShapeInferenceMethod()))
 {}
~Network()
~Network ()
Definition at line 1182 of file Network.cpp.
 {
 }
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Implements INetwork.
Definition at line 2010 of file Network.cpp.
References Network::GetGraph().
Referenced by Network::GetGraph().
 {
     for (auto layer : GetGraph())
     {
         layer->Accept(visitor);
     };
 }
AddAbsLayer()
IConnectableLayer * AddAbsLayer (const char * name = nullptr) override virtual
Add absolute layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1452 of file Network.cpp.
References armnn::Abs, and Network::AddElementwiseUnaryLayer().
Referenced by Network::GetGraph().
 {
     return AddElementwiseUnaryLayer(ElementwiseUnaryDescriptor(UnaryOperation::Abs), name);
 }
AddActivationLayer()
IConnectableLayer * AddActivationLayer (const ActivationDescriptor & activationDescriptor, const char * name = nullptr) override virtual
Adds an activation layer to the network.
Parameters
activationDescriptor - ActivationDescriptor to configure the activation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1400 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<ActivationLayer>(activationDescriptor, name);
 }
AddAdditionLayer()
IConnectableLayer * AddAdditionLayer (const char * name = nullptr) override virtual
Adds an addition layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1457 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<AdditionLayer>(name);
 }
AddArgMinMaxLayer()
IConnectableLayer * AddArgMinMaxLayer (const ArgMinMaxDescriptor & desc, const char * name = nullptr) override virtual
Adds an ArgMinMax layer to the network.
Parameters
desc - Parameters for the L2 normalization operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1406 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<ArgMinMaxLayer>(argMinMaxDescriptor, name);
 }
AddBatchNormalizationLayer()
IConnectableLayer * AddBatchNormalizationLayer (const BatchNormalizationDescriptor & desc, const ConstTensor & mean, const ConstTensor & variance, const ConstTensor & beta, const ConstTensor & gamma, const char * name = nullptr) override virtual
Adds a batch normalization layer to the network.
Parameters
mean - Pre-calculated mean for each channel.
variance - Pre-calculated variance for each channel.
beta - Per-channel additive factor.
gamma - Per-channel multiplicative factor.
Returns
- Interface for configuring the layer.
Parameters
name - Optional name for the layer.
Implements INetwork.
Definition at line 1472 of file Network.cpp.
References BatchNormalizationLayer::m_Mean.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     const auto layer = m_Graph->AddLayer<BatchNormalizationLayer>(desc, name);
     layer->m_Mean = std::make_unique<ScopedCpuTensorHandle>(mean);
     layer->m_Variance = std::make_unique<ScopedCpuTensorHandle>(variance);
     layer->m_Beta = std::make_unique<ScopedCpuTensorHandle>(beta);
     layer->m_Gamma = std::make_unique<ScopedCpuTensorHandle>(gamma);
     return layer;
 }
AddBatchToSpaceNdLayer()
IConnectableLayer * AddBatchToSpaceNdLayer (const BatchToSpaceNdDescriptor & batchToSpaceNdDescriptor, const char * name = nullptr) override virtual
Adds a batch to space ND layer to the network.
Parameters
batchToSpaceNdDescriptor - Description of the layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1197 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<BatchToSpaceNdLayer>(batchToSpaceNdDescriptor, name);
 }
AddComparisonLayer()
IConnectableLayer * AddComparisonLayer (const ComparisonDescriptor & comparisonDescriptor, const char * name = nullptr) override virtual
Add a Comparison layer to the network.
Parameters
name - Optional name for the layer.
desc - Descriptor for the comparison operation.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1203 of file Network.cpp.
Referenced by Network::AddEqualLayer(), Network::AddGreaterLayer(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<ComparisonLayer>(comparisonDescriptor, name);
 }
AddConcatLayer()
IConnectableLayer * AddConcatLayer (const ConcatDescriptor & concatDescriptor, const char * name = nullptr) override virtual
Adds a concatenation layer to the network.
Parameters
concatDescriptor - ConcatDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1268 of file Network.cpp.
References OptionalBase::has_value(), Convolution2dDescriptor::m_BiasEnabled, Convolution2dLayer::m_Weight, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by Network::AddMergerLayer(), BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<ConcatLayer>(concatDescriptor, name);
 }
AddConstantLayer()
IConnectableLayer * AddConstantLayer (const ConstTensor & input, const char * name = nullptr) override virtual
Adds a layer with no inputs and a single output, which always corresponds to the passed in constant tensor.
Parameters
input - Tensor to be provided as the only output of the layer. The layer will maintain its own copy of the tensor data, meaning the memory referenced by input can be freed or reused after this function is called.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1532 of file Network.cpp.
References ConstantLayer::m_LayerOutput.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     auto layer = m_Graph->AddLayer<ConstantLayer>(name);
     layer->m_LayerOutput = std::make_unique<ScopedCpuTensorHandle>(input);
     return layer;
 }
AddConvolution2dLayer() [1/3]
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Adds a 2D convolution layer to the network.
Parameters
convolution2dDescriptor - Description of the 2D convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1296 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return AddConvolution2dLayerImpl(convolution2dDescriptor, weights, biases, name);
 }
AddConvolution2dLayer() [2/3]
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const char * name = nullptr) override virtual
Implements INetwork.
Definition at line 1304 of file Network.cpp.
 {
     Optional<ConstTensor> biases;
     return AddConvolution2dLayerImpl(convolution2dDescriptor, weights, biases, name);
 }
AddConvolution2dLayer() [3/3]
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const ConstTensor & biases, const char * name = nullptr) override virtual
Implements INetwork.
Definition at line 1312 of file Network.cpp.
References OptionalBase::has_value(), DepthwiseConvolution2dDescriptor::m_BiasEnabled, DepthwiseConvolution2dLayer::m_Weight, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
 {
     Optional<ConstTensor> optionalBiases(biases);
     return AddConvolution2dLayerImpl(convolution2dDescriptor, weights, optionalBiases, name);
 }
AddDepthToSpaceLayer()
IConnectableLayer * AddDepthToSpaceLayer (const DepthToSpaceDescriptor & depthToSpaceDescriptor, const char * name = nullptr) override virtual
Adds a depth to space layer to the network.
Parameters
depthToSpaceDescriptor - Parameters for the depth to space operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1344 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<DepthToSpaceLayer>(depthToSpaceDescriptor, name);
 }
AddDepthwiseConvolution2dLayer() [1/3]
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Adds a 2D depthwise convolution layer to the network.
Parameters
convolution2dDescriptor - Description of the 2D depthwise convolution layer.
weights - Tensor for the weights. Expected format: [channelMultiplier, inputChannels, height, width].
biases Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1350 of file Network.cpp.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return AddDepthwiseConvolution2dLayerImpl(convolution2dDescriptor, weights, biases, name);
 }
AddDepthwiseConvolution2dLayer() [2/3]
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const char * name = nullptr) override virtual
Implements INetwork.
Definition at line 1359 of file Network.cpp.
 {
     Optional<ConstTensor> biases;
     return AddDepthwiseConvolution2dLayerImpl(convolution2dDescriptor, weights, biases, name);
 }
AddDepthwiseConvolution2dLayer() [3/3]
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const ConstTensor & biases, const char * name = nullptr) override virtual
Implements INetwork.
Definition at line 1368 of file Network.cpp.
 {
     Optional<ConstTensor> optionalBiases(biases);
     return AddDepthwiseConvolution2dLayerImpl(convolution2dDescriptor, weights, optionalBiases, name);
 }
AddDequantizeLayer()
IConnectableLayer * AddDequantizeLayer (const char * name = nullptr) override virtual
Adds a Dequantize layer to the network.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1730 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<DequantizeLayer>(name);
 }
AddDetectionPostProcessLayer()
IConnectableLayer * AddDetectionPostProcessLayer (const DetectionPostProcessDescriptor & descriptor, const ConstTensor & anchors, const char * name = nullptr) override virtual
Adds a Detection PostProcess layer to the network.
Parameters
descriptor - Description of the Detection PostProcess layer.
anchors - Tensor for anchors.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1378 of file Network.cpp.
References anchors(), and DetectionPostProcessLayer::m_Anchors.
Referenced by Network::GetGraph().
 {
     const auto layer = m_Graph->AddLayer<DetectionPostProcessLayer>(descriptor, name);
     layer->m_Anchors = std::make_unique<ScopedCpuTensorHandle>(anchors);
     return layer;
 }
AddDivisionLayer()
IConnectableLayer * AddDivisionLayer (const char * name = nullptr) override virtual
Adds a division layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1705 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<DivisionLayer>(name);
 }
AddElementwiseUnaryLayer()
IConnectableLayer * AddElementwiseUnaryLayer (const ElementwiseUnaryDescriptor & elementwiseUnaryDescriptor, const char * name = nullptr) override virtual
Add an ElementwiseUnary layer to the network.
Parameters
name - Optional name for the layer.
desc - Descriptor for the elementwiseUnary operation.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1209 of file Network.cpp.
Referenced by Network::AddAbsLayer(), Network::AddRsqrtLayer(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<ElementwiseUnaryLayer>(elementwiseUnaryDescriptor, name);
 }
AddEqualLayer()
IConnectableLayer * AddEqualLayer (const char * name = nullptr) override virtual
Add a Equal layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1746 of file Network.cpp.
References Network::AddComparisonLayer(), and armnn::Equal.
Referenced by Network::GetGraph().
 {
     return AddComparisonLayer(ComparisonDescriptor(ComparisonOperation::Equal), name);
 }
AddFillLayer()
IConnectableLayer * AddFillLayer (const FillDescriptor & fillDescriptor, const char * name = nullptr) override virtual
Add an Fill layer to the network.
Parameters
name - Optional name for the layer.
fillDescriptor - Descriptor for the fill operation.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1215 of file Network.cpp.
References OptionalBase::has_value(), FullyConnectedDescriptor::m_BiasEnabled, FullyConnectedLayer::m_Weight, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<FillLayer>(fillDescriptor, name);
 }
AddFloorLayer()
IConnectableLayer * AddFloorLayer (const char * name = nullptr) override virtual
Adds a floor layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1559 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<FloorLayer>(name);
 }
AddFullyConnectedLayer() [1/3]
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Adds a fully connected layer to the network.
Parameters
fullyConnectedDescriptor - Description of the fully connected layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1243 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return AddFullyConnectedLayerImpl(fullyConnectedDescriptor, weights, biases, name);
 }
AddFullyConnectedLayer() [2/3]
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const char * name = nullptr) override virtual
Implements INetwork.
Definition at line 1251 of file Network.cpp.
 {
     Optional<ConstTensor> biases;
     return AddFullyConnectedLayerImpl(fullyConnectedDescriptor, weights, biases, name);
 }
AddFullyConnectedLayer() [3/3]
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const ConstTensor & biases, const char * name = nullptr) override virtual
Implements INetwork.
Definition at line 1259 of file Network.cpp.
 {
     Optional<ConstTensor> optionalBiases(biases);
     return AddFullyConnectedLayerImpl(fullyConnectedDescriptor, weights, optionalBiases, name);
 }
AddGatherLayer() [1/2]
IConnectableLayer * AddGatherLayer (const char * name = nullptr) override virtual
Add Gather layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1756 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     GatherDescriptor gatherDescriptor{};
     return AddGatherLayer(gatherDescriptor, name);
 }
AddGatherLayer() [2/2]
IConnectableLayer * AddGatherLayer (const GatherDescriptor & descriptor, const char * name = nullptr) override virtual
Add Gather layer to the network.
Parameters
descriptor - Description of the gather layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1762 of file Network.cpp.
 {
     return m_Graph->AddLayer<GatherLayer>(gatherDescriptor, name);
 }
AddGreaterLayer()
IConnectableLayer * AddGreaterLayer (const char * name = nullptr) override virtual
Add a Greater layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1741 of file Network.cpp.
References Network::AddComparisonLayer(), and armnn::Greater.
Referenced by Network::GetGraph().
 {
     return AddComparisonLayer(ComparisonDescriptor(ComparisonOperation::Greater), name);
 }
AddInputLayer()
IConnectableLayer * AddInputLayer (LayerBindingId id, const char * name = nullptr) override virtual
Adds an input layer to the network.
Parameters
id - User generated id to uniquely identify a particular input. The same id needs to be specified. when passing the inputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1192 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<InputLayer>(id, name);
 }
AddInstanceNormalizationLayer()
IConnectableLayer * AddInstanceNormalizationLayer (const InstanceNormalizationDescriptor & desc, const char * name = nullptr) override virtual
Adds an instance normalization layer to the network.
Parameters
desc - Parameters for the instance normalization operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1514 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<InstanceNormalizationLayer>(desc, name);
 }
AddL2NormalizationLayer()
IConnectableLayer * AddL2NormalizationLayer (const L2NormalizationDescriptor & desc, const char * name = nullptr) override virtual
Adds an L2 normalization layer to the network.
Normalization is performed along dimension 1, but requires a 4d input.
Parameters
desc - Parameters for the L2 normalization operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1520 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<L2NormalizationLayer>(desc, name);
 }
AddLogicalBinaryLayer()
IConnectableLayer * AddLogicalBinaryLayer (const LogicalBinaryDescriptor & descriptor, const char * name = nullptr) override virtual
Adds a Logical Binary layer to the network.
Parameters
descriptor - Description of the Logical Binary layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 2004 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<LogicalBinaryLayer>(logicalBinaryDescriptor, name);
 }
AddLogSoftmaxLayer()
IConnectableLayer * AddLogSoftmaxLayer (const LogSoftmaxDescriptor & logSoftmaxDescriptor, const char * name = nullptr) override virtual
Adds a log softmax layer to the network.
Parameters
logSoftmaxDescriptor - LogSoftmaxDescriptor to configure the log softmax.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1526 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<LogSoftmaxLayer>(desc, name);
 }
AddLstmLayer()
IConnectableLayer * AddLstmLayer (const LstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr) override virtual
Add a Lstm layer to the network.
Parameters
descriptor - Parameters for the Lstm operation
params - Weights and biases for the LSTM cell
name - Optional name for the layer
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1564 of file Network.cpp.
References LstmLayer::m_BasicParameters, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, LstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToForgetWeights, LstmBasicParameters::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, LstmInputParams::m_ProjectionBias, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, and LstmInputParams::m_RecurrentToOutputWeights.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     const auto layer = m_Graph->AddLayer<LstmLayer>(descriptor, name);
     //Lstm Basic Parameters
     layer->m_BasicParameters.m_InputToForgetWeights =
         std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToForgetWeights));
     layer->m_BasicParameters.m_InputToCellWeights =
         std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToCellWeights));
     layer->m_BasicParameters.m_InputToOutputWeights =
         std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToOutputWeights));
     layer->m_BasicParameters.m_RecurrentToForgetWeights =
         std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToForgetWeights));
     layer->m_BasicParameters.m_RecurrentToCellWeights =
         std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToCellWeights));
     layer->m_BasicParameters.m_RecurrentToOutputWeights =
         std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToOutputWeights));
     layer->m_BasicParameters.m_ForgetGateBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_ForgetGateBias));
     layer->m_BasicParameters.m_CellBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellBias));
     layer->m_BasicParameters.m_OutputGateBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_OutputGateBias));
     //Lstm Cifg parameters
     if(!descriptor.m_CifgEnabled)
     {
         if(params.m_InputToInputWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Input To Input Weights cannot be NULL "
                                            "when CIFG is disabled.");
         }
         if(params.m_RecurrentToInputWeights == nullptr)
         {
             throw InvalidArgumentException(
                     "AddLstmLayer: Recurrent To Input Weights cannot be NULL "
                     "when CIFG is disabled.");
         }
         if(params.m_InputGateBias == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Input Gate Bias cannot be NULL "
                                            "when CIFG is disabled.");
         }
         layer->m_CifgParameters.m_InputToInputWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToInputWeights));
         layer->m_CifgParameters.m_RecurrentToInputWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToInputWeights));
         layer->m_CifgParameters.m_InputGateBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputGateBias));
     }
     //Lstm projection parameters
     if(descriptor.m_ProjectionEnabled)
     {
         if(params.m_ProjectionWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Projection Weights cannot be NULL "
                                            "when projection is enabled.");
         }
         layer->m_ProjectionParameters.m_ProjectionWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_ProjectionWeights));
         if(params.m_ProjectionBias != nullptr)
         {
             layer->m_ProjectionParameters.m_ProjectionBias =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_ProjectionBias));
         }
     }
     //Lstm Peephole params
     if(descriptor.m_PeepholeEnabled)
     {
         if(!descriptor.m_CifgEnabled)
         {
             if(params.m_CellToInputWeights == nullptr)
             {
                 throw InvalidArgumentException("AddLstmLayer: Cell To Input Weights cannot be NULL "
                                                "when Peephole is enabled and CIFG disabled.");
             }
             layer->m_PeepholeParameters.m_CellToInputWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellToInputWeights));
         }
         if(params.m_CellToForgetWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Cell To Forget Weights cannot be NULL "
                                            "when Peephole is enabled.");
         }
         if(params.m_CellToOutputWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Cell To Output Weights cannot be NULL "
                                            "when Peephole is enabled.");
         }
         layer->m_PeepholeParameters.m_CellToForgetWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellToForgetWeights));
         layer->m_PeepholeParameters.m_CellToOutputWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellToOutputWeights));
     }
     //Lstm Layer Normalization params
     if(descriptor.m_LayerNormEnabled)
     {
         if(!descriptor.m_CifgEnabled)
         {
             if(params.m_InputLayerNormWeights == nullptr)
             {
                 throw InvalidArgumentException("AddLstmLayer: Input layer normalization weights cannot be NULL "
                                                "when layer normalization is enabled and CIFG disabled.");
             }
             layer->m_LayerNormParameters.m_InputLayerNormWeights =
                     std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputLayerNormWeights));
         }
         if(params.m_ForgetLayerNormWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Forget layer normalization weights cannot be NULL "
                                            "when layer normalization is enabled.");
         }
         if(params.m_CellLayerNormWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Cell layer normalization weights cannot be NULL "
                                            "when layer normalization is enabled.");
         }
         if(params.m_OutputLayerNormWeights == nullptr)
         {
             throw InvalidArgumentException("AddLstmLayer: Output layer normalization weights cannot be NULL "
                                            "when layer normalization is enabled.");
         }
         layer->m_LayerNormParameters.m_ForgetLayerNormWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_ForgetLayerNormWeights));
         layer->m_LayerNormParameters.m_CellLayerNormWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellLayerNormWeights));
         layer->m_LayerNormParameters.m_OutputLayerNormWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_OutputLayerNormWeights));
     }
     return layer;
 }
AddMaximumLayer()
IConnectableLayer * AddMaximumLayer (const char * name = nullptr) override virtual
Add a Maximum layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1436 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<MaximumLayer>(name);
 }
AddMeanLayer()
IConnectableLayer * AddMeanLayer (const MeanDescriptor & meanDescriptor, const char * name = nullptr) override virtual
Add a Mean layer to the network.
Parameters
meanDescriptor - Parameters for the mean operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1715 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<MeanLayer>(meanDescriptor,name);
 }
AddMergeLayer()
IConnectableLayer * AddMergeLayer (const char * name = nullptr) override virtual
Adds a merge layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1768 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<MergeLayer>(name);
 }
AddMergerLayer()
IConnectableLayer * AddMergerLayer (const MergerDescriptor & mergerDescriptor, const char * name = nullptr) override virtual
Adds a concat layer to the network.
Parameters
mergerDescriptor - MergerDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1446 of file Network.cpp.
References Network::AddConcatLayer().
Referenced by Network::GetGraph().
 {
     return AddConcatLayer(mergerDescriptor, name);
 }
AddMinimumLayer()
IConnectableLayer * AddMinimumLayer (const char * name = nullptr) override virtual
Add a Minimum layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1441 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<MinimumLayer>(name);
 }
AddMultiplicationLayer()
IConnectableLayer * AddMultiplicationLayer (const char * name = nullptr) override virtual
Adds a multiplication layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1462 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<MultiplicationLayer>(name);
 }
AddNormalizationLayer()
IConnectableLayer * AddNormalizationLayer (const NormalizationDescriptor & normalizationDescriptor, const char * name = nullptr) override virtual
Adds a normalization layer to the network.
Parameters
normalizationDescriptor - NormalizationDescriptor to configure the normalization.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1412 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<NormalizationLayer>(normalizationDescriptor, name);
 }
AddOutputLayer()
IConnectableLayer * AddOutputLayer (LayerBindingId id, const char * name = nullptr) override virtual
Adds an output layer to the network.
Parameters
id - User generated id to uniquely identify a particular output. The same id needs to be specified when passing the outputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1467 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<OutputLayer>(id, name);
 }
AddPadLayer()
IConnectableLayer * AddPadLayer (const PadDescriptor & padDescriptor, const char * name = nullptr) override virtual
Adds a fully pad layer to the network.
Parameters
paddings - n by 2 tensor, where n is the rank of the input tensor, such that paddings[i,0] indicates the amount of padding to add in front of dimonsion i, and paddings[i,1] indicates the amount of padding to add after the end of dimension i
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1720 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<PadLayer>(padDescriptor,name);
 }
AddPermuteLayer()
IConnectableLayer * AddPermuteLayer (const PermuteDescriptor & permuteDescriptor, const char * name = nullptr) override virtual
Adds a permute layer to the network.
Parameters
permuteDescriptor - PermuteDescriptor to configure the permute.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1388 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<PermuteLayer>(permuteDescriptor, name);
 }
AddPooling2dLayer()
IConnectableLayer * AddPooling2dLayer (const Pooling2dDescriptor & pooling2dDescriptor, const char * name = nullptr) override virtual
Adds a pooling layer to the network.
Parameters
pooling2dDescriptor - Pooling2dDescriptor to configure the pooling.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1394 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<Pooling2dLayer>(pooling2dDescriptor, name);
 }
AddPreluLayer()
IConnectableLayer * AddPreluLayer (const char * name = nullptr) override virtual
Adds a PReLU layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1778 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<PreluLayer>(name);
 }
AddQLstmLayer()
IConnectableLayer * AddQLstmLayer (const QLstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr) override virtual
Add a QLstm layer to the network.
Parameters
descriptor - Parameters for the QLstm operation
params - Weights and biases for the layer
name - Optional name for the layer
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1862 of file Network.cpp.
References QLstmLayer::m_BasicParameters, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, LstmInputParams::m_InputToCellWeights, QLstmBasicParameters::m_InputToForgetWeights, LstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, LstmInputParams::m_ProjectionBias, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, and LstmInputParams::m_RecurrentToOutputWeights.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     const auto layer = m_Graph->AddLayer<QLstmLayer>(descriptor, name);
     // QLstm Basic Parameters
     layer->m_BasicParameters.m_InputToForgetWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToForgetWeights));
     layer->m_BasicParameters.m_InputToCellWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToCellWeights));
     layer->m_BasicParameters.m_InputToOutputWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToOutputWeights));
     layer->m_BasicParameters.m_RecurrentToForgetWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToForgetWeights));
     layer->m_BasicParameters.m_RecurrentToCellWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToCellWeights));
     layer->m_BasicParameters.m_RecurrentToOutputWeights =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToOutputWeights));
     layer->m_BasicParameters.m_ForgetGateBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_ForgetGateBias));
     layer->m_BasicParameters.m_CellBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellBias));
     layer->m_BasicParameters.m_OutputGateBias =
             std::make_unique<ScopedCpuTensorHandle>(*(params.m_OutputGateBias));
     // QLstm Cifg parameters
     if(!descriptor.m_CifgEnabled)
     {
         if(params.m_InputToInputWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Input To Input Weights cannot be NULL");
         }
         if(params.m_RecurrentToInputWeights == nullptr)
         {
             throw InvalidArgumentException(
                     "AddQLstmLayer: Recurrent To Input Weights cannot be NULL");
         }
         if(params.m_InputGateBias == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Input Gate Bias cannot be NULL");
         }
         layer->m_CifgParameters.m_InputToInputWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputToInputWeights));
         layer->m_CifgParameters.m_RecurrentToInputWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_RecurrentToInputWeights));
         layer->m_CifgParameters.m_InputGateBias =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputGateBias));
     }
     // QLstm Projection parameters
     if(descriptor.m_ProjectionEnabled)
     {
         if(params.m_ProjectionWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Projection Weights cannot be NULL");
         }
         layer->m_ProjectionParameters.m_ProjectionWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_ProjectionWeights));
         // Projection bias is optional even if projection is enabled
         if(params.m_ProjectionWeights != nullptr)
         {
             layer->m_ProjectionParameters.m_ProjectionBias =
                     std::make_unique<ScopedCpuTensorHandle>(*(params.m_ProjectionBias));
         }
     }
     // QLstm Peephole params
     if(descriptor.m_PeepholeEnabled)
     {
         if(params.m_CellToForgetWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Cell To Forget Weights cannot be NULL");
         }
         if(params.m_CellToOutputWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Cell To Output Weights cannot be NULL");
         }
         if(!descriptor.m_CifgEnabled)
         {
             if(params.m_CellToInputWeights == nullptr)
             {
                 throw InvalidArgumentException("AddQLstmLayer: Cell To Input Weights cannot be NULL");
             }
             layer->m_PeepholeParameters.m_CellToInputWeights =
                     std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellToInputWeights));
         }
         layer->m_PeepholeParameters.m_CellToForgetWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellToForgetWeights));
         layer->m_PeepholeParameters.m_CellToOutputWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellToOutputWeights));
     }
     // QLstm Layer Normalization params
     if(descriptor.m_LayerNormEnabled)
     {
         if(params.m_ForgetLayerNormWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Forget layer normalization weights cannot be NULL");
         }
         if(params.m_CellLayerNormWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Cell layer normalization weights cannot be NULL");
         }
         if(params.m_OutputLayerNormWeights == nullptr)
         {
             throw InvalidArgumentException("AddQLstmLayer: Output layer normalization weights cannot be NULL");
         }
         if(!descriptor.m_CifgEnabled)
         {
             if(params.m_InputLayerNormWeights == nullptr)
             {
                 throw InvalidArgumentException("AddQLstmLayer: Input layer normalization weights cannot be NULL");
             }
             layer->m_LayerNormParameters.m_InputLayerNormWeights =
                     std::make_unique<ScopedCpuTensorHandle>(*(params.m_InputLayerNormWeights));
         }
         layer->m_LayerNormParameters.m_ForgetLayerNormWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_ForgetLayerNormWeights));
         layer->m_LayerNormParameters.m_CellLayerNormWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_CellLayerNormWeights));
         layer->m_LayerNormParameters.m_OutputLayerNormWeights =
                 std::make_unique<ScopedCpuTensorHandle>(*(params.m_OutputLayerNormWeights));
     }
     return layer;
 }
AddQuantizedLstmLayer()
IConnectableLayer * AddQuantizedLstmLayer (const QuantizedLstmInputParams & params, const char * name = nullptr) override virtual
Add a QuantizedLstm layer to the network.
Parameters
params - The weights and biases for the Quantized LSTM cell
name - Optional name for the layer
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1824 of file Network.cpp.
References QuantizedLstmInputParams::GetCellBias(), QuantizedLstmInputParams::GetForgetGateBias(), QuantizedLstmInputParams::GetInputGateBias(), QuantizedLstmInputParams::GetInputToCellWeights(), QuantizedLstmInputParams::GetInputToForgetWeights(), QuantizedLstmInputParams::GetInputToInputWeights(), QuantizedLstmInputParams::GetInputToOutputWeights(), QuantizedLstmInputParams::GetOutputGateBias(), QuantizedLstmInputParams::GetRecurrentToCellWeights(), QuantizedLstmInputParams::GetRecurrentToForgetWeights(), QuantizedLstmInputParams::GetRecurrentToInputWeights(), QuantizedLstmInputParams::GetRecurrentToOutputWeights(), QuantizedLstmParameters::m_InputToInputWeights, and QuantizedLstmLayer::m_QuantizedLstmParameters.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     const auto layer = m_Graph->AddLayer<QuantizedLstmLayer>(name);
     // InputToX weights
     layer->m_QuantizedLstmParameters.m_InputToInputWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetInputToInputWeights());
     layer->m_QuantizedLstmParameters.m_InputToForgetWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetInputToForgetWeights());
     layer->m_QuantizedLstmParameters.m_InputToCellWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetInputToCellWeights());
     layer->m_QuantizedLstmParameters.m_InputToOutputWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetInputToOutputWeights());
     // RecurrentToX weights
     layer->m_QuantizedLstmParameters.m_RecurrentToInputWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetRecurrentToInputWeights());
     layer->m_QuantizedLstmParameters.m_RecurrentToForgetWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetRecurrentToForgetWeights());
     layer->m_QuantizedLstmParameters.m_RecurrentToCellWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetRecurrentToCellWeights());
     layer->m_QuantizedLstmParameters.m_RecurrentToOutputWeights =
             std::make_unique<ScopedCpuTensorHandle>(params.GetRecurrentToOutputWeights());
     // Bias
     layer->m_QuantizedLstmParameters.m_InputGateBias =
             std::make_unique<ScopedCpuTensorHandle>(params.GetInputGateBias());
     layer->m_QuantizedLstmParameters.m_ForgetGateBias =
             std::make_unique<ScopedCpuTensorHandle>(params.GetForgetGateBias());
     layer->m_QuantizedLstmParameters.m_CellBias =
             std::make_unique<ScopedCpuTensorHandle>(params.GetCellBias());
     layer->m_QuantizedLstmParameters.m_OutputGateBias =
             std::make_unique<ScopedCpuTensorHandle>(params.GetOutputGateBias());
     return layer;
 }
AddQuantizeLayer()
IConnectableLayer * AddQuantizeLayer (const char * name = nullptr) override virtual
Add a quantize layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1725 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<QuantizeLayer>(name);
 }
AddRankLayer()
IConnectableLayer * AddRankLayer (const char * name = nullptr) override virtual
Adds a rank layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1489 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<RankLayer>(name);
 }
AddReshapeLayer()
IConnectableLayer * AddReshapeLayer (const ReshapeDescriptor & reshapeDescriptor, const char * name = nullptr) override virtual
Adds a reshape layer to the network.
Parameters
reshapeDescriptor - Parameters for the reshape operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1541 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<ReshapeLayer>(reshapeDescriptor, name);
 }
AddResizeBilinearLayer()
IConnectableLayer * AddResizeBilinearLayer (const ResizeBilinearDescriptor & resizeDesc, const char * name = nullptr) override virtual
Adds a resize bilinear layer to the network.
Parameters
resizeDesc - Parameters for the resize operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1494 of file Network.cpp.
References armnn::Bilinear, ResizeBilinearDescriptor::m_AlignCorners, ResizeDescriptor::m_AlignCorners, ResizeBilinearDescriptor::m_DataLayout, ResizeDescriptor::m_DataLayout, ResizeBilinearDescriptor::m_HalfPixelCenters, ResizeDescriptor::m_HalfPixelCenters, ResizeDescriptor::m_Method, ResizeBilinearDescriptor::m_TargetHeight, ResizeDescriptor::m_TargetHeight, ResizeBilinearDescriptor::m_TargetWidth, and ResizeDescriptor::m_TargetWidth.
Referenced by Network::GetGraph().
 {
     ResizeDescriptor resizeDescriptor;
     resizeDescriptor.m_Method           = ResizeMethod::Bilinear;
     resizeDescriptor.m_DataLayout       = descriptor.m_DataLayout;
     resizeDescriptor.m_TargetWidth      = descriptor.m_TargetWidth;
     resizeDescriptor.m_TargetHeight     = descriptor.m_TargetHeight;
     resizeDescriptor.m_AlignCorners     = descriptor.m_AlignCorners;
     resizeDescriptor.m_HalfPixelCenters = descriptor.m_HalfPixelCenters;
     return m_Graph->AddLayer<ResizeLayer>(resizeDescriptor, name);
 }
AddResizeLayer()
IConnectableLayer * AddResizeLayer (const ResizeDescriptor & resizeDescriptor, const char * name = nullptr) override virtual
Adds a resize layer to the network.
Parameters
resizeDescriptor - Parameters for the resize operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1508 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<ResizeLayer>(resizeDescriptor, name);
 }
AddRsqrtLayer()
IConnectableLayer * AddRsqrtLayer (const char * name = nullptr) override virtual
Add Reciprocal of square root layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1751 of file Network.cpp.
References Network::AddElementwiseUnaryLayer(), and armnn::Rsqrt.
Referenced by Network::GetGraph().
 {
     return AddElementwiseUnaryLayer(ElementwiseUnaryDescriptor(UnaryOperation::Rsqrt), name);
 }
AddSliceLayer()
IConnectableLayer * AddSliceLayer (const SliceDescriptor & sliceDescriptor, const char * name = nullptr) override virtual
Adds a slice layer to the network.
Parameters
sliceDescriptor - SliceDescriptor to configure the slice operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1419 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<SliceLayer>(sliceDescriptor, name);
 }
AddSoftmaxLayer()
IConnectableLayer * AddSoftmaxLayer (const SoftmaxDescriptor & softmaxDescriptor, const char * name = nullptr) override virtual
Adds a softmax layer to the network.
If the data type is QAsymm8, then the output quantization parameters must have a scale of 1/256 and an offset of 0
Parameters
softmaxDescriptor - SoftmaxDescriptor to configure the softmax.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1424 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<SoftmaxLayer>(softmaxDescriptor, name);
 }
AddSpaceToBatchNdLayer()
IConnectableLayer * AddSpaceToBatchNdLayer (const SpaceToBatchNdDescriptor & spaceToBatchNdDescriptor, const char * name = nullptr) override virtual
Adds a space to batch layer to the network.
Parameters
spaceToBatchNdDescriptor - Parameters for the space to batch operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1547 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<SpaceToBatchNdLayer>(spaceToBatchNdDescriptor, name);
 }
AddSpaceToDepthLayer()
IConnectableLayer * AddSpaceToDepthLayer (const SpaceToDepthDescriptor & spaceToDepthDescriptor, const char * name = nullptr) override virtual
Adds a space to depth layer to the network.
Parameters
spaceToDepthDescriptor - Parameters for the space to depth operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1553 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<SpaceToDepthLayer>(spaceToDepthDescriptor, name);
 }
AddSplitterLayer()
IConnectableLayer * AddSplitterLayer (const ViewsDescriptor & splitterDescriptor, const char * name = nullptr) override virtual
Adds a splitter layer to the network.
Parameters
splitterDescriptor - ViewsDescriptor to configure the splitting process. Number of Views must be equal to the number of outputs, and their order must match - e.g. first view corresponds to the first output, second view to the second output, etc....
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1430 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<SplitterLayer>(splitterDescriptor, name);
 }
AddStackLayer()
IConnectableLayer * AddStackLayer (const StackDescriptor & descriptor, const char * name = nullptr) override virtual
Adds a stack layer to the network.
Parameters
descriptor - Description of the stack layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1811 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<StackLayer>(stackDescriptor, name);
 }
AddStandInLayer()
IConnectableLayer * AddStandInLayer (const StandInDescriptor & descriptor, const char * name = nullptr) override virtual
Add a stand-in layer for a type unknown to the Arm NN framework.
Note: Due to the nature of this layer, no validation can be performed by the framework. Furthermore, Any model containing this layer cannot make use of dynamic tensors since the tensor sizes cannot be inferred. - Descriptor for the StandIn layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1818 of file Network.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     return m_Graph->AddLayer<StandInLayer>(desc, name);
 }
AddStridedSliceLayer()
IConnectableLayer * AddStridedSliceLayer (const StridedSliceDescriptor & stridedSliceDescriptor, const char * name = nullptr) override virtual
Adds a strided slice layer to the network.
Parameters
StridedSliceDescriptor - Parameters for the strided slice operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1735 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<StridedSliceLayer>(stridedSliceDescriptor, name);
 }
AddSubtractionLayer()
IConnectableLayer * AddSubtractionLayer (const char * name = nullptr) override virtual
Adds a subtraction layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1710 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<SubtractionLayer>(name);
 }
AddSwitchLayer()
IConnectableLayer * AddSwitchLayer (const char * name = nullptr) override virtual
Adds a switch layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1773 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<SwitchLayer>(name);
 }
AddTransposeConvolution2dLayer()
IConnectableLayer * AddTransposeConvolution2dLayer (const TransposeConvolution2dDescriptor & descriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Adds a 2D transpose convolution layer to the network.
Parameters
descriptor - Description of the 2D transpose convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1783 of file Network.cpp.
References OptionalBase::has_value(), TransposeConvolution2dDescriptor::m_BiasEnabled, TransposeConvolution2dLayer::m_Weight, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by Network::GetGraph().
 {
     if (descriptor.m_BiasEnabled && !biases.has_value())
     {
         throw InvalidArgumentException("AddTransposeConvolution2dLayer: Biases cannot be empty");
     }
     const auto layer = m_Graph->AddLayer<TransposeConvolution2dLayer>(descriptor, name);
     layer->m_Weight = std::make_unique<ScopedCpuTensorHandle>(weights);
     if (descriptor.m_BiasEnabled)
     {
         layer->m_Bias = std::make_unique<ScopedCpuTensorHandle>(biases.value());
     }
     return layer;
 }
AddTransposeLayer()
IConnectableLayer * AddTransposeLayer (const TransposeDescriptor & transposeDescriptor, const char * name = nullptr) override virtual
Adds a transpose layer to the network.
Parameters
transposeDescriptor - TransposeDescriptor to configure the transpose.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Implements INetwork.
Definition at line 1805 of file Network.cpp.
Referenced by Network::GetGraph().
 {
     return m_Graph->AddLayer<TransposeLayer>(transposeDescriptor, name);
 }
GetGraph()
const Graph& GetGraph () const inline
Definition at line 34 of file Network.hpp.
References Network::Accept(), Network::AddAbsLayer(), Network::AddActivationLayer(), Network::AddAdditionLayer(), Network::AddArgMinMaxLayer(), Network::AddBatchNormalizationLayer(), Network::AddBatchToSpaceNdLayer(), Network::AddComparisonLayer(), Network::AddConcatLayer(), Network::AddConstantLayer(), Network::AddConvolution2dLayer(), Network::AddDepthToSpaceLayer(), Network::AddDepthwiseConvolution2dLayer(), Network::AddDequantizeLayer(), Network::AddDetectionPostProcessLayer(), Network::AddDivisionLayer(), Network::AddElementwiseUnaryLayer(), Network::AddEqualLayer(), Network::AddFillLayer(), Network::AddFloorLayer(), Network::AddFullyConnectedLayer(), Network::AddGatherLayer(), Network::AddGreaterLayer(), Network::AddInputLayer(), Network::AddInstanceNormalizationLayer(), Network::AddL2NormalizationLayer(), Network::AddLogicalBinaryLayer(), Network::AddLogSoftmaxLayer(), Network::AddLstmLayer(), Network::AddMaximumLayer(), Network::AddMeanLayer(), Network::AddMergeLayer(), Network::AddMergerLayer(), Network::AddMinimumLayer(), Network::AddMultiplicationLayer(), Network::AddNormalizationLayer(), Network::AddOutputLayer(), Network::AddPadLayer(), Network::AddPermuteLayer(), Network::AddPooling2dLayer(), Network::AddPreluLayer(), Network::AddQLstmLayer(), Network::AddQuantizedLstmLayer(), Network::AddQuantizeLayer(), Network::AddRankLayer(), Network::AddReshapeLayer(), Network::AddResizeBilinearLayer(), Network::AddResizeLayer(), Network::AddRsqrtLayer(), Network::AddSliceLayer(), Network::AddSoftmaxLayer(), Network::AddSpaceToBatchNdLayer(), Network::AddSpaceToDepthLayer(), Network::AddSplitterLayer(), Network::AddStackLayer(), Network::AddStandInLayer(), Network::AddStridedSliceLayer(), Network::AddSubtractionLayer(), Network::AddSwitchLayer(), Network::AddTransposeConvolution2dLayer(), Network::AddTransposeLayer(), anchors(), ARMNN_DEPRECATED_MSG, and Network::PrintGraph().
Referenced by Network::Accept(), BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), armnn::GetInputTensorInfo(), and armnn::Optimize().
 { return *m_Graph; }
PrintGraph()
Status PrintGraph () override virtual
Implements INetwork.
Definition at line 1186 of file Network.cpp.
References armnn::Success.
Referenced by BOOST_AUTO_TEST_CASE(), and Network::GetGraph().
 {
     m_Graph->Print();
     return Status::Success;
 }
The documentation for this class was generated from the following files:
src/armnn/Network.hpp
src/armnn/Network.cpp