ArmNN: RefConstantWorkload Class Reference
RefConstantWorkload Class Reference
#include <RefConstantWorkload.hpp>
Public Member Functions
RefConstantWorkload (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< ConstantQueueDescriptor >
BaseWorkload (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const ConstantQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ConstantQueueDescriptor >
const ConstantQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 17 of file RefConstantWorkload.hpp.
Constructor & Destructor Documentation
RefConstantWorkload()
RefConstantWorkload (const ConstantQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 19 of file RefConstantWorkload.cpp.
     : BaseWorkload<ConstantQueueDescriptor>(descriptor, info) {}
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 36 of file RefConstantWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, and armnn::CpuRef.
 {
     ARMNN_SCOPED_PROFILING_EVENT(Compute::CpuRef, "RefConstantWorkload_Execute");
 }
PostAllocationConfigure()
void PostAllocationConfigure () override virtual
Implements IWorkload.
Definition at line 23 of file RefConstantWorkload.cpp.
References ARMNN_ASSERT, ConstCpuTensorHandle::GetConstTensor(), TensorInfo::GetNumBytes(), armnn::GetTensorInfo(), ConstCpuTensorHandle::GetTensorInfo(), BaseWorkload< ConstantQueueDescriptor >::m_Data, ConstantQueueDescriptor::m_LayerOutput, and QueueDescriptor::m_Outputs.
 {
     const ConstantQueueDescriptor& data = this->m_Data;
     ARMNN_ASSERT(data.m_LayerOutput != nullptr);
     const TensorInfo& outputInfo = GetTensorInfo(data.m_Outputs[0]);
     ARMNN_ASSERT(data.m_LayerOutput->GetTensorInfo().GetNumBytes() == outputInfo.GetNumBytes());
     memcpy(GetOutputTensorData<void>(0, data), data.m_LayerOutput->GetConstTensor<void>(),
         outputInfo.GetNumBytes());
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefConstantWorkload.hpp
src/backends/reference/workloads/RefConstantWorkload.cpp