ArmNN: ProfilingGuidGenerator Class Reference
ProfilingGuidGenerator Class Reference
#include <ProfilingGuidGenerator.hpp>
Public Member Functions
ProfilingGuidGenerator ()
Construct a generator with the default address space static/dynamic partitioning.
ProfilingDynamicGuid NextGuid () override
Return the next random Guid in the sequence.
ProfilingStaticGuid GenerateStaticId (const std::string &str) override
Create a ProfilingStaticGuid based on a hash of the string.
void Reset ()
Reset the generator back to zero. Used mainly for test.
Public Member Functions inherited from IProfilingGuidGenerator
virtual ~IProfilingGuidGenerator ()
Detailed Description
Definition at line 19 of file ProfilingGuidGenerator.hpp.
Constructor & Destructor Documentation
ProfilingGuidGenerator()
ProfilingGuidGenerator () inline
Construct a generator with the default address space static/dynamic partitioning.
Definition at line 23 of file ProfilingGuidGenerator.hpp.
 : m_Sequence(0) {}
Member Function Documentation
GenerateStaticId()
ProfilingStaticGuid GenerateStaticId (const std::string & str) inline override virtual
Create a ProfilingStaticGuid based on a hash of the string.
Implements IProfilingGuidGenerator.
Definition at line 40 of file ProfilingGuidGenerator.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::GetStaticId().
     {
         uint64_t staticHash = m_Hash(str) | MIN_STATIC_GUID;
         return ProfilingStaticGuid(staticHash);
     }
NextGuid()
ProfilingDynamicGuid NextGuid () inline override virtual
Return the next random Guid in the sequence.
Implements IProfilingGuidGenerator.
Definition at line 26 of file ProfilingGuidGenerator.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::GetNextGuid().
     {
         std::lock_guard<std::mutex> sequencelock(m_SequenceMutex);
         ProfilingDynamicGuid guid(m_Sequence);
         m_Sequence++;
         if (m_Sequence >= MIN_STATIC_GUID)
         {
             // Reset the sequence to 0 when it reaches the upper bound of dynamic guid
             m_Sequence = 0;
         }
         return guid;
     }
Reset()
void Reset () inline
Reset the generator back to zero. Used mainly for test.
Definition at line 47 of file ProfilingGuidGenerator.hpp.
Referenced by ProfilingService::ResetGuidGenerator().
     {
         std::lock_guard<std::mutex> sequencelock(m_SequenceMutex);
         m_Sequence = 0;
     }
The documentation for this class was generated from the following file:
src/profiling/ProfilingGuidGenerator.hpp