ArmNN: INetworkQuantizer Class Reference
INetworkQuantizer Class Reference abstract
Quantizer class Quantizes a float32 InputNetwork.
#include <INetworkQuantizer.hpp>
Public Member Functions
virtual void OverrideInputRange (LayerBindingId layerId, float min, float max)=0
Overrides the default quantization values for the input layer with the given id.
virtual void Refine (const InputTensors &inputTensors)=0
Refine input network with a set of refinement data for specified LayerBindingId.
virtual INetworkPtr ExportNetwork ()=0
Extract final quantized network.
Static Public Member Functions
static INetworkQuantizer * CreateRaw (INetwork *inputNetwork, const QuantizerOptions &options=QuantizerOptions())
Create Quantizer object and return raw pointer.
static INetworkQuantizerPtr Create (INetwork *inputNetwork, const QuantizerOptions &options=QuantizerOptions())
Create Quantizer object wrapped in unique_ptr.
static void Destroy (INetworkQuantizer *quantizer)
Destroy Quantizer object.
Protected Member Functions
virtual ~INetworkQuantizer ()
Detailed Description
Quantizer class Quantizes a float32 InputNetwork.
Definition at line 32 of file INetworkQuantizer.hpp.
Constructor & Destructor Documentation
~INetworkQuantizer()
virtual ~INetworkQuantizer () inline protected virtual
Definition at line 54 of file INetworkQuantizer.hpp.
 {}
Member Function Documentation
Create()
INetworkQuantizerPtr Create (INetwork * inputNetwork, const QuantizerOptions & options = QuantizerOptions()) static
Create Quantizer object wrapped in unique_ptr.
Definition at line 41 of file NetworkQuantizer.cpp.
References INetworkQuantizer::CreateRaw(), and INetworkQuantizer::Destroy().
Referenced by armnn::BOOST_AUTO_TEST_CASE(), main(), armnn::PreserveTypeTestImpl(), armnn::TestQuantizeConvolution2d(), armnn::TestQuantizeDepthwiseConvolution2d(), armnn::TestQuantizeTransposeConvolution2d(), and armnn::ValidateFullyConnectedLayer().
 {
     return INetworkQuantizerPtr(CreateRaw(inputNetwork, options), &INetworkQuantizer::Destroy);
 }
CreateRaw()
INetworkQuantizer * CreateRaw (INetwork * inputNetwork, const QuantizerOptions & options = QuantizerOptions()) static
Create Quantizer object and return raw pointer.
Definition at line 36 of file NetworkQuantizer.cpp.
Referenced by INetworkQuantizer::Create().
 {
     return new NetworkQuantizer(inputNetwork, options);
 }
Destroy()
void Destroy (INetworkQuantizer * quantizer) static
Destroy Quantizer object.
Definition at line 46 of file NetworkQuantizer.cpp.
Referenced by INetworkQuantizer::Create().
 {
     delete PolymorphicDowncast<NetworkQuantizer*>(quantizer);
 }
ExportNetwork()
virtual INetworkPtr ExportNetwork () pure virtual
Extract final quantized network.
Implemented in NetworkQuantizer.
OverrideInputRange()
virtual void OverrideInputRange (LayerBindingId layerId, float min, float max) pure virtual
Overrides the default quantization values for the input layer with the given id.
Implemented in NetworkQuantizer.
Refine()
virtual void Refine (const InputTensors & inputTensors) pure virtual
Refine input network with a set of refinement data for specified LayerBindingId.
Implemented in NetworkQuantizer.
The documentation for this class was generated from the following files:
include/armnnQuantizer/INetworkQuantizer.hpp
src/armnn/NetworkQuantizer.cpp