ArmNN: GraphObservable< ObservedType > Class Template Reference
GraphObservable< ObservedType > Class Template Reference
#include <Observable.hpp>
Public Types
using Iterator = typename std::list< ObservedType >::const_iterator
Public Member Functions
GraphObservable (Graph &subject, GraphEvent notifyOnEvent)
void Clear ()
Iterator begin ()
Iterator end ()
Public Member Functions inherited from IGraphObservable
virtual void Update (Layer *graphLayer)=0
Protected Member Functions
~GraphObservable ()
Protected Member Functions inherited from IGraphObservable
virtual ~IGraphObservable ()=default
Protected Attributes
GraphEvent m_NotifyOnEvent
Graph * m_Subject
std::list< ObservedType > m_ObservedObjects
Detailed Description
template<typename ObservedType>
class armnn::GraphObservable< ObservedType >
Definition at line 14 of file Observable.hpp.
Member Typedef Documentation
Iterator
using Iterator = typename std::list<ObservedType>::const_iterator
Definition at line 17 of file Observable.hpp.
Constructor & Destructor Documentation
GraphObservable()
GraphObservable (Graph & subject, GraphEvent notifyOnEvent) inline
Definition at line 19 of file Observable.hpp.
     : m_Subject(&subject)
     {
         m_NotifyOnEvent = notifyOnEvent;
         m_Subject->AttachObservable(this, m_NotifyOnEvent);
     };
~GraphObservable()
~GraphObservable () inline protected
Definition at line 33 of file Observable.hpp.
     {
         if (m_Subject)
         {
             m_Subject->DetachObservable(this, m_NotifyOnEvent);
         }
     }
Member Function Documentation
begin()
Iterator begin () inline
Definition at line 28 of file Observable.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_ObservedObjects.begin(); }
Clear()
void Clear () inline
Definition at line 26 of file Observable.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and Optimizer::Pass().
 { m_ObservedObjects.clear(); };
end()
Iterator end () inline
Definition at line 30 of file Observable.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_ObservedObjects.end(); }
Member Data Documentation
m_NotifyOnEvent
GraphEvent m_NotifyOnEvent protected
Definition at line 41 of file Observable.hpp.
Referenced by GraphObservable< Layer *>::GraphObservable(), and GraphObservable< Layer *>::~GraphObservable().
m_ObservedObjects
std::list<ObservedType> m_ObservedObjects protected
Definition at line 43 of file Observable.hpp.
Referenced by GraphObservable< Layer *>::begin(), GraphObservable< Layer *>::Clear(), and GraphObservable< Layer *>::end().
m_Subject
Graph* m_Subject protected
Definition at line 42 of file Observable.hpp.
Referenced by GraphObservable< Layer *>::GraphObservable(), and GraphObservable< Layer *>::~GraphObservable().
The documentation for this class was generated from the following file:
src/armnn/Observable.hpp