ArmNN: INotifyBackends Class Reference
INotifyBackends Class Reference abstract
#include <INotifyBackends.hpp>
Public Member Functions
virtual ~INotifyBackends ()
virtual void NotifyBackendsForTimelineReporting ()=0
Detailed Description
Definition at line 14 of file INotifyBackends.hpp.
Constructor & Destructor Documentation
~INotifyBackends()
virtual ~INotifyBackends () inline virtual
Definition at line 17 of file INotifyBackends.hpp.
References INotifyBackends::NotifyBackendsForTimelineReporting().
 {}
Member Function Documentation
NotifyBackendsForTimelineReporting()
virtual void NotifyBackendsForTimelineReporting () pure virtual
Implemented in ProfilingService.
Referenced by DeactivateTimelineReportingCommandHandler::operator()(), ActivateTimelineReportingCommandHandler::operator()(), and INotifyBackends::~INotifyBackends().
The documentation for this class was generated from the following file:
src/profiling/INotifyBackends.hpp