ArmNN: TimelineUtilityMethods Class Reference
TimelineUtilityMethods Class Reference
#include <TimelineUtilityMethods.hpp>
Public Member Functions
TimelineUtilityMethods (std::unique_ptr< ISendTimelinePacket > &sendTimelinePacket)
TimelineUtilityMethods (TimelineUtilityMethods &&other)
TimelineUtilityMethods (const TimelineUtilityMethods &other)=delete
TimelineUtilityMethods & operator= (const TimelineUtilityMethods &other)=delete
TimelineUtilityMethods & operator= (TimelineUtilityMethods &&other)=default
~TimelineUtilityMethods ()=default
ProfilingDynamicGuid CreateNamedTypedEntity (const std::string &name, const std::string &type)
void CreateNamedTypedEntity (ProfilingGuid entityGuid, const std::string &name, const std::string &type)
void CreateNamedTypedEntity (ProfilingGuid entityGuid, const std::string &name, ProfilingStaticGuid typeGuid)
void MarkEntityWithLabel (ProfilingGuid entityGuid, const std::string &labelName, ProfilingStaticGuid labelLinkGuid)
ProfilingStaticGuid DeclareLabel (const std::string &labelName)
void NameEntity (ProfilingGuid entityGuid, const std::string &name)
void TypeEntity (ProfilingGuid entityGuid, const std::string &type)
ProfilingDynamicGuid CreateNamedTypedChildEntity (ProfilingGuid parentEntityGuid, const std::string &entityName, const std::string &entityType)
void CreateNamedTypedChildEntity (ProfilingGuid entityGuid, ProfilingGuid parentEntityGuid, const std::string &entityName, const std::string &entityType)
void CreateNamedTypedChildEntity (ProfilingGuid entityGuid, ProfilingGuid parentEntityGuid, const std::string &entityName, ProfilingStaticGuid typeGuid)
ProfilingDynamicGuid CreateRelationship (ProfilingRelationshipType relationshipType, ProfilingGuid headGuid, ProfilingGuid tailGuid, ProfilingGuid relationshipCategory)
ProfilingDynamicGuid CreateConnectionRelationship (ProfilingRelationshipType relationshipType, ProfilingGuid headGuid, ProfilingGuid tailGuid)
void CreateTypedEntity (ProfilingGuid entityGuid, ProfilingStaticGuid typeGuid)
void MarkEntityWithType (ProfilingGuid entityGuid, ProfilingStaticGuid typeNameGuid)
ProfilingDynamicGuid RecordEvent (ProfilingGuid entityGuid, ProfilingStaticGuid eventClassGuid)
ProfilingDynamicGuid RecordWorkloadInferenceAndStartOfLifeEvent (ProfilingGuid workloadGuid, ProfilingGuid inferenceGuid)
void RecordEndOfLifeEvent (ProfilingGuid entityGuid)
void Commit ()
Static Public Member Functions
static std::unique_ptr< TimelineUtilityMethods > GetTimelineUtils (ProfilingService &profilingService)
static void SendWellKnownLabelsAndEventClasses (ISendTimelinePacket &timelinePacket)
Detailed Description
Definition at line 19 of file TimelineUtilityMethods.hpp.
Constructor & Destructor Documentation
TimelineUtilityMethods() [1/3]
TimelineUtilityMethods (std::unique_ptr< ISendTimelinePacket > & sendTimelinePacket) inline
Definition at line 27 of file TimelineUtilityMethods.hpp.
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
         : m_SendTimelinePacket(std::move(sendTimelinePacket)) {}
TimelineUtilityMethods() [2/3]
TimelineUtilityMethods (TimelineUtilityMethods && other) inline
Definition at line 31 of file TimelineUtilityMethods.hpp.
References TimelineUtilityMethods::CreateConnectionRelationship(), TimelineUtilityMethods::CreateNamedTypedChildEntity(), TimelineUtilityMethods::CreateNamedTypedEntity(), TimelineUtilityMethods::CreateRelationship(), TimelineUtilityMethods::CreateTypedEntity(), TimelineUtilityMethods::DeclareLabel(), TimelineUtilityMethods::MarkEntityWithLabel(), TimelineUtilityMethods::MarkEntityWithType(), TimelineUtilityMethods::NameEntity(), TimelineUtilityMethods::operator=(), TimelineUtilityMethods::RecordEndOfLifeEvent(), TimelineUtilityMethods::RecordEvent(), TimelineUtilityMethods::RecordWorkloadInferenceAndStartOfLifeEvent(), TimelineUtilityMethods::SendWellKnownLabelsAndEventClasses(), TimelineUtilityMethods::TimelineUtilityMethods(), TimelineUtilityMethods::TypeEntity(), and TimelineUtilityMethods::~TimelineUtilityMethods().
         : m_SendTimelinePacket(std::move(other.m_SendTimelinePacket)) {}
TimelineUtilityMethods() [3/3]
TimelineUtilityMethods (const TimelineUtilityMethods & other) delete
~TimelineUtilityMethods()
~TimelineUtilityMethods () default
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
Member Function Documentation
Commit()
void Commit () inline
Definition at line 92 of file TimelineUtilityMethods.hpp.
 { m_SendTimelinePacket->Commit(); }
CreateConnectionRelationship()
ProfilingDynamicGuid CreateConnectionRelationship (ProfilingRelationshipType relationshipType, ProfilingGuid headGuid, ProfilingGuid tailGuid)
Definition at line 344 of file TimelineUtilityMethods.cpp.
References LabelsAndEventClasses::CONNECTION_GUID, and ProfilingService::GetNextGuid().
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Generate a GUID for the relationship
     ProfilingDynamicGuid relationshipGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new retention link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(relationshipType,
                                                                relationshipGuid,
                                                                headGuid,
                                                                tailGuid,
                                                                LabelsAndEventClasses::CONNECTION_GUID);
     return relationshipGuid;
 }
CreateNamedTypedChildEntity() [1/3]
ProfilingDynamicGuid CreateNamedTypedChildEntity (ProfilingGuid parentEntityGuid, const std::string & entityName, const std::string & entityType)
Definition at line 234 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::CreateNamedTypedEntity(), LabelsAndEventClasses::EMPTY_GUID, ProfilingService::GetNextGuid(), and armnn::profiling::RetentionLink.
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Check that the entity name is valid
     if (entityName.empty())
     {
         // The entity name is invalid
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Check that the entity type is valid
     if (entityType.empty())
     {
         // The entity type is invalid
         throw InvalidArgumentException("Invalid entity type, the entity type cannot be empty");
     }
     // Create a named type entity from the given name and type, this call throws in case of error
     ProfilingDynamicGuid childEntityGuid = CreateNamedTypedEntity(entityName, entityType);
     // Generate a GUID for the retention link relationship
     ProfilingDynamicGuid retentionLinkGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new retention link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(ProfilingRelationshipType::RetentionLink,
                                                                retentionLinkGuid,
                                                                parentEntityGuid,
                                                                childEntityGuid,
                                                                LabelsAndEventClasses::EMPTY_GUID);
     return childEntityGuid;
 }
CreateNamedTypedChildEntity() [2/3]
void CreateNamedTypedChildEntity (ProfilingGuid entityGuid, ProfilingGuid parentEntityGuid, const std::string & entityName, const std::string & entityType)
Definition at line 268 of file TimelineUtilityMethods.cpp.
References LabelsAndEventClasses::CHILD_GUID, TimelineUtilityMethods::CreateNamedTypedEntity(), ProfilingService::GetNextGuid(), and armnn::profiling::RetentionLink.
 {
     // Check that the entity name is valid
     if (entityName.empty())
     {
         // The entity name is invalid
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Check that the entity type is valid
     if (entityType.empty())
     {
         // The entity type is invalid
         throw InvalidArgumentException("Invalid entity type, the entity type cannot be empty");
     }
     // Create a named type entity from the given guid, name and type, this call throws in case of error
     CreateNamedTypedEntity(childEntityGuid, entityName, entityType);
     // Generate a GUID for the retention link relationship
     ProfilingDynamicGuid retentionLinkGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new retention link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(ProfilingRelationshipType::RetentionLink,
                                                                retentionLinkGuid,
                                                                parentEntityGuid,
                                                                childEntityGuid,
                                                                LabelsAndEventClasses::CHILD_GUID);
 }
CreateNamedTypedChildEntity() [3/3]
void CreateNamedTypedChildEntity (ProfilingGuid entityGuid, ProfilingGuid parentEntityGuid, const std::string & entityName, ProfilingStaticGuid typeGuid)
Definition at line 301 of file TimelineUtilityMethods.cpp.
References LabelsAndEventClasses::CHILD_GUID, TimelineUtilityMethods::CreateNamedTypedEntity(), ProfilingService::GetNextGuid(), and armnn::profiling::RetentionLink.
 {
     // Check that the entity name is valid
     if (entityName.empty())
     {
         // The entity name is invalid
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Create a named type entity from the given guid, name and type, this call throws in case of error
     CreateNamedTypedEntity(childEntityGuid, entityName, typeGuid);
     // Generate a GUID for the retention link relationship
     ProfilingDynamicGuid retentionLinkGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new retention link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(ProfilingRelationshipType::RetentionLink,
                                                                retentionLinkGuid,
                                                                parentEntityGuid,
                                                                childEntityGuid,
                                                                LabelsAndEventClasses::CHILD_GUID);
 }
CreateNamedTypedEntity() [1/3]
ProfilingDynamicGuid CreateNamedTypedEntity (const std::string & name, const std::string & type)
Definition at line 99 of file TimelineUtilityMethods.cpp.
References ProfilingService::GetNextGuid().
Referenced by TimelineUtilityMethods::CreateNamedTypedChildEntity(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Check that the entity name is valid
     if (name.empty())
     {
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Check that the entity type is valid
     if (type.empty())
     {
         throw InvalidArgumentException("Invalid entity type, the entity type cannot be empty");
     }
     // Generate dynamic GUID of the entity
     ProfilingDynamicGuid entityGuid = profiling::ProfilingService::GetNextGuid();
     CreateNamedTypedEntity(entityGuid, name, type);
     return entityGuid;
 }
CreateNamedTypedEntity() [2/3]
void CreateNamedTypedEntity (ProfilingGuid entityGuid, const std::string & name, const std::string & type)
Definition at line 121 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::NameEntity(), and TimelineUtilityMethods::TypeEntity().
 {
     // Check that the entity name is valid
     if (name.empty())
     {
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Check that the entity type is valid
     if (type.empty())
     {
         throw InvalidArgumentException("Invalid entity type, the entity type cannot be empty");
     }
     // Send Entity Binary Packet of the entity to the external profiling service
     m_SendTimelinePacket->SendTimelineEntityBinaryPacket(entityGuid);
     // Create name entity and send the relationship of the entity with the given name
     NameEntity(entityGuid, name);
     // Create type entity and send the relationship of the entity with the given type
     TypeEntity(entityGuid, type);
 }
CreateNamedTypedEntity() [3/3]
void CreateNamedTypedEntity (ProfilingGuid entityGuid, const std::string & name, ProfilingStaticGuid typeGuid)
Definition at line 147 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::MarkEntityWithType(), and TimelineUtilityMethods::NameEntity().
 {
     // Check that the entity name is valid
     if (name.empty())
     {
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Send Entity Binary Packet of the entity to the external profiling service
     m_SendTimelinePacket->SendTimelineEntityBinaryPacket(entityGuid);
     // Create name entity and send the relationship of the entity with the given name
     NameEntity(entityGuid, name);
     // Create type entity and send the relationship of the entity with the given type
     MarkEntityWithType(entityGuid, typeGuid);
 }
CreateRelationship()
ProfilingDynamicGuid CreateRelationship (ProfilingRelationshipType relationshipType, ProfilingGuid headGuid, ProfilingGuid tailGuid, ProfilingGuid relationshipCategory)
Definition at line 327 of file TimelineUtilityMethods.cpp.
References ProfilingService::GetNextGuid().
Referenced by TimelineUtilityMethods::RecordWorkloadInferenceAndStartOfLifeEvent(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Generate a GUID for the relationship
     ProfilingDynamicGuid relationshipGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new retention link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(relationshipType,
                                                                relationshipGuid,
                                                                headGuid,
                                                                tailGuid,
                                                                relationshipCategory);
     return relationshipGuid;
 }
CreateTypedEntity()
void CreateTypedEntity (ProfilingGuid entityGuid, ProfilingStaticGuid typeGuid)
Definition at line 360 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::MarkEntityWithType().
Referenced by TimelineUtilityMethods::RecordWorkloadInferenceAndStartOfLifeEvent(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Send Entity Binary Packet of the entity to the external profiling service
     m_SendTimelinePacket->SendTimelineEntityBinaryPacket(entityGuid);
     // Create type entity and send the relationship of the entity with the given type
     MarkEntityWithType(entityGuid, entityTypeGuid);
 }
DeclareLabel()
ProfilingStaticGuid DeclareLabel (const std::string & labelName)
Definition at line 167 of file TimelineUtilityMethods.cpp.
References ProfilingService::GetStaticId().
Referenced by TimelineUtilityMethods::MarkEntityWithLabel(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Check that the label name is valid
     if (labelName.empty())
     {
         // The label name is invalid
         throw InvalidArgumentException("Invalid label name, the label name cannot be empty");
     }
     // Generate a static GUID for the given label name
     ProfilingStaticGuid labelGuid = profiling::ProfilingService::GetStaticId(labelName);
     // Send the new label to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineLabelBinaryPacket(labelGuid, labelName);
     return labelGuid;
 }
GetTimelineUtils()
std::unique_ptr< TimelineUtilityMethods > GetTimelineUtils (ProfilingService & profilingService) static
Definition at line 15 of file TimelineUtilityMethods.cpp.
References armnn::profiling::Active, ProfilingService::GetCurrentState(), ProfilingService::GetSendTimelinePacket(), and ProfilingService::IsTimelineReportingEnabled().
Referenced by LoadedNetwork::EnqueueWorkload(), LoadedNetwork::MakeLoadedNetwork(), LoadedNetwork::SendNetworkStructure(), and Runtime::UnloadNetwork().
 {
     if (profilingService.GetCurrentState() == ProfilingState::Active && profilingService.IsTimelineReportingEnabled())
     {
         std::unique_ptr<ISendTimelinePacket> sendTimelinepacket = profilingService.GetSendTimelinePacket();
         return std::make_unique<TimelineUtilityMethods>(sendTimelinepacket);
     }
     else
     {
         std::unique_ptr<TimelineUtilityMethods> empty;
         return empty;
     }
 }
MarkEntityWithLabel()
void MarkEntityWithLabel (ProfilingGuid entityGuid, const std::string & labelName, ProfilingStaticGuid labelLinkGuid)
Definition at line 185 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::DeclareLabel(), ProfilingService::GetNextGuid(), and armnn::profiling::LabelLink.
Referenced by TimelineUtilityMethods::NameEntity(), TimelineUtilityMethods::TimelineUtilityMethods(), and TimelineUtilityMethods::TypeEntity().
 {
     // Check that the label name is valid
     if (labelName.empty())
     {
         // The label name is invalid
         throw InvalidArgumentException("Invalid entity name, the entity name cannot be empty");
     }
     // Declare a label with the label's name, this call throws in case of error
     ProfilingStaticGuid labelGuid = DeclareLabel(labelName);
     // Generate a GUID for the label relationship
     ProfilingDynamicGuid relationshipGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new label link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(ProfilingRelationshipType::LabelLink,
                                                                relationshipGuid,
                                                                entityGuid,
                                                                labelGuid,
                                                                labelTypeGuid);
 }
MarkEntityWithType()
void MarkEntityWithType (ProfilingGuid entityGuid, ProfilingStaticGuid typeNameGuid)
Definition at line 210 of file TimelineUtilityMethods.cpp.
References ProfilingService::GetNextGuid(), armnn::profiling::LabelLink, and LabelsAndEventClasses::TYPE_GUID.
Referenced by TimelineUtilityMethods::CreateNamedTypedEntity(), TimelineUtilityMethods::CreateTypedEntity(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Generate a GUID for the label relationship
     ProfilingDynamicGuid relationshipGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new label link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(ProfilingRelationshipType::LabelLink,
                                                                relationshipGuid,
                                                                entityGuid,
                                                                typeNameGuid,
                                                                LabelsAndEventClasses::TYPE_GUID);
 }
NameEntity()
void NameEntity (ProfilingGuid entityGuid, const std::string & name)
Definition at line 224 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::MarkEntityWithLabel(), and LabelsAndEventClasses::NAME_GUID.
Referenced by TimelineUtilityMethods::CreateNamedTypedEntity(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     MarkEntityWithLabel(entityGuid, name, LabelsAndEventClasses::NAME_GUID);
 }
operator=() [1/2]
TimelineUtilityMethods& operator= (const TimelineUtilityMethods & other) delete
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
operator=() [2/2]
TimelineUtilityMethods& operator= (TimelineUtilityMethods && other) default
RecordEndOfLifeEvent()
void RecordEndOfLifeEvent (ProfilingGuid entityGuid)
Definition at line 413 of file TimelineUtilityMethods.cpp.
References LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS, and TimelineUtilityMethods::RecordEvent().
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
 {
     RecordEvent(entityGuid, LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS);
 }
RecordEvent()
ProfilingDynamicGuid RecordEvent (ProfilingGuid entityGuid, ProfilingStaticGuid eventClassGuid)
Definition at line 369 of file TimelineUtilityMethods.cpp.
References armnn::profiling::ExecutionLink, armnnUtils::Threads::GetCurrentThreadId(), ProfilingService::GetNextGuid(), and armnn::profiling::GetTimestamp().
Referenced by TimelineUtilityMethods::RecordEndOfLifeEvent(), TimelineUtilityMethods::RecordWorkloadInferenceAndStartOfLifeEvent(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Take a timestamp
     uint64_t timestamp = GetTimestamp();
     // Get the thread id
     int threadId = armnnUtils::Threads::GetCurrentThreadId();
     // Generate a GUID for the event
     ProfilingDynamicGuid eventGuid = profiling::ProfilingService::GetNextGuid();
     // Send the new timeline event to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineEventBinaryPacket(timestamp, threadId, eventGuid);
     // Generate a GUID for the execution link
     ProfilingDynamicGuid executionLinkId = profiling::ProfilingService::GetNextGuid();
     // Send the new execution link to the external profiling service, this call throws in case of error
     m_SendTimelinePacket->SendTimelineRelationshipBinaryPacket(ProfilingRelationshipType::ExecutionLink,
                                                                executionLinkId,
                                                                entityGuid,
                                                                eventGuid,
                                                                eventClassGuid);
     return eventGuid;
 }
RecordWorkloadInferenceAndStartOfLifeEvent()
ProfilingDynamicGuid RecordWorkloadInferenceAndStartOfLifeEvent (ProfilingGuid workloadGuid, ProfilingGuid inferenceGuid)
Definition at line 396 of file TimelineUtilityMethods.cpp.
References LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS, LabelsAndEventClasses::CHILD_GUID, TimelineUtilityMethods::CreateRelationship(), TimelineUtilityMethods::CreateTypedEntity(), LabelsAndEventClasses::EXECUTION_OF_GUID, ProfilingService::GetNextGuid(), TimelineUtilityMethods::RecordEvent(), armnn::profiling::RetentionLink, and LabelsAndEventClasses::WORKLOAD_EXECUTION_GUID.
Referenced by TimelineUtilityMethods::TimelineUtilityMethods().
 {
     ProfilingDynamicGuid workloadInferenceGuid = profiling::ProfilingService::GetNextGuid();
     CreateTypedEntity(workloadInferenceGuid, LabelsAndEventClasses::WORKLOAD_EXECUTION_GUID);
     CreateRelationship(ProfilingRelationshipType::RetentionLink,
                        inferenceGuid,
                        workloadInferenceGuid,
                        LabelsAndEventClasses::CHILD_GUID);
     CreateRelationship(ProfilingRelationshipType::RetentionLink,
                        workloadGuid,
                        workloadInferenceGuid,
                        LabelsAndEventClasses::EXECUTION_OF_GUID);
     RecordEvent(workloadInferenceGuid, LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS);
     return workloadInferenceGuid;
 }
SendWellKnownLabelsAndEventClasses()
void SendWellKnownLabelsAndEventClasses (ISendTimelinePacket & timelinePacket) static
Definition at line 30 of file TimelineUtilityMethods.cpp.
References LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS, LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS_NAME, LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS_NAME_GUID, LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS, LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS_NAME, LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS_NAME_GUID, LabelsAndEventClasses::BACKENDID_GUID, LabelsAndEventClasses::BACKENDID_LABEL, LabelsAndEventClasses::CHILD_GUID, LabelsAndEventClasses::CHILD_LABEL, ISendTimelinePacket::Commit(), LabelsAndEventClasses::CONNECTION, LabelsAndEventClasses::CONNECTION_GUID, LabelsAndEventClasses::EXECUTION_OF_GUID, LabelsAndEventClasses::EXECUTION_OF_LABEL, LabelsAndEventClasses::INDEX_GUID, LabelsAndEventClasses::INDEX_LABEL, LabelsAndEventClasses::INFERENCE, LabelsAndEventClasses::INFERENCE_GUID, LabelsAndEventClasses::LAYER, LabelsAndEventClasses::LAYER_GUID, LabelsAndEventClasses::NAME_GUID, LabelsAndEventClasses::NAME_LABEL, LabelsAndEventClasses::NETWORK, LabelsAndEventClasses::NETWORK_GUID, LabelsAndEventClasses::PROCESS_ID_GUID, LabelsAndEventClasses::PROCESS_ID_LABEL, ISendTimelinePacket::SendTimelineEventClassBinaryPacket(), ISendTimelinePacket::SendTimelineLabelBinaryPacket(), LabelsAndEventClasses::TYPE_GUID, LabelsAndEventClasses::TYPE_LABEL, LabelsAndEventClasses::WORKLOAD, LabelsAndEventClasses::WORKLOAD_EXECUTION, LabelsAndEventClasses::WORKLOAD_EXECUTION_GUID, and LabelsAndEventClasses::WORKLOAD_GUID.
Referenced by BOOST_AUTO_TEST_CASE(), ActivateTimelineReportingCommandHandler::operator()(), ConnectionAcknowledgedCommandHandler::operator()(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     // Send the "name" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::NAME_GUID,
                                                  LabelsAndEventClasses::NAME_LABEL);
     // Send the "type" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::TYPE_GUID,
                                                  LabelsAndEventClasses::TYPE_LABEL);
     // Send the "index" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::INDEX_GUID,
                                                  LabelsAndEventClasses::INDEX_LABEL);
     // Send the "backendId" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::BACKENDID_GUID,
                                                  LabelsAndEventClasses::BACKENDID_LABEL);
     // Send the "child" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::CHILD_GUID,
                                                  LabelsAndEventClasses::CHILD_LABEL);
     // Send the "execution_of" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::EXECUTION_OF_GUID,
                                                  LabelsAndEventClasses::EXECUTION_OF_LABEL);
     // Send the "process_id" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::PROCESS_ID_GUID,
                                                  LabelsAndEventClasses::PROCESS_ID_LABEL);
     // Send the "layer" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::LAYER_GUID,
                                                  LabelsAndEventClasses::LAYER);
     // Send the "workload" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::WORKLOAD_GUID,
                                                  LabelsAndEventClasses::WORKLOAD);
     // Send the "network" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::NETWORK_GUID,
                                                  LabelsAndEventClasses::NETWORK);
     // Send the "connection" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::CONNECTION_GUID,
                                                  LabelsAndEventClasses::CONNECTION);
     // Send the "inference" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::INFERENCE_GUID,
                                                  LabelsAndEventClasses::INFERENCE);
     // Send the "workload_execution" label, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::WORKLOAD_EXECUTION_GUID,
                                                  LabelsAndEventClasses::WORKLOAD_EXECUTION);
     // Send the "start of life" event class, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS_NAME_GUID,
                                                  LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS_NAME);
     timelinePacket.SendTimelineEventClassBinaryPacket(LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS,
                                                       LabelsAndEventClasses::ARMNN_PROFILING_SOL_EVENT_CLASS_NAME_GUID);
     // Send the "end of life" event class, this call throws in case of error
     timelinePacket.SendTimelineLabelBinaryPacket(LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS_NAME_GUID,
                                                  LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS_NAME);
     timelinePacket.SendTimelineEventClassBinaryPacket(LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS,
                                                       LabelsAndEventClasses::ARMNN_PROFILING_EOL_EVENT_CLASS_NAME_GUID);
     timelinePacket.Commit();
 }
TypeEntity()
void TypeEntity (ProfilingGuid entityGuid, const std::string & type)
Definition at line 229 of file TimelineUtilityMethods.cpp.
References TimelineUtilityMethods::MarkEntityWithLabel(), and LabelsAndEventClasses::TYPE_GUID.
Referenced by TimelineUtilityMethods::CreateNamedTypedEntity(), and TimelineUtilityMethods::TimelineUtilityMethods().
 {
     MarkEntityWithLabel(entityGuid, type, LabelsAndEventClasses::TYPE_GUID);
 }
The documentation for this class was generated from the following files:
src/profiling/TimelineUtilityMethods.hpp
src/profiling/TimelineUtilityMethods.cpp