ArmNN: IBackendProfilingContext Class Reference
IBackendProfilingContext Class Reference abstract
#include <IBackendProfilingContext.hpp>
Public Member Functions
virtual ~IBackendProfilingContext ()
virtual uint16_t RegisterCounters (uint16_t currentMaxGlobalCounterID)=0
virtual Optional< std::string > ActivateCounters (uint32_t capturePeriod, const std::vector< uint16_t > &counterIds)=0
virtual std::vector< Timestamp > ReportCounterValues ()=0
virtual bool EnableProfiling (bool flag)=0
virtual bool EnableTimelineReporting (bool flag)=0
Detailed Description
Definition at line 16 of file IBackendProfilingContext.hpp.
Constructor & Destructor Documentation
~IBackendProfilingContext()
virtual ~IBackendProfilingContext () inline virtual
Definition at line 19 of file IBackendProfilingContext.hpp.
References IBackendProfilingContext::ActivateCounters(), IBackendProfilingContext::EnableProfiling(), IBackendProfilingContext::EnableTimelineReporting(), IBackendProfilingContext::RegisterCounters(), and IBackendProfilingContext::ReportCounterValues().
     {}
Member Function Documentation
ActivateCounters()
virtual Optional<std::string> ActivateCounters (uint32_t capturePeriod, const std::vector< uint16_t > & counterIds) pure virtual
Implemented in MockBackendProfilingContext.
Referenced by IBackendProfilingContext::~IBackendProfilingContext().
EnableProfiling()
virtual bool EnableProfiling (bool flag) pure virtual
Implemented in MockBackendProfilingContext.
Referenced by IBackendProfilingContext::~IBackendProfilingContext().
EnableTimelineReporting()
virtual bool EnableTimelineReporting (bool flag) pure virtual
Implemented in MockBackendProfilingContext.
Referenced by IBackendProfilingContext::~IBackendProfilingContext().
RegisterCounters()
virtual uint16_t RegisterCounters (uint16_t currentMaxGlobalCounterID) pure virtual
Implemented in MockBackendProfilingContext.
Referenced by IBackendProfilingContext::~IBackendProfilingContext().
ReportCounterValues()
virtual std::vector<Timestamp> ReportCounterValues () pure virtual
Implemented in MockBackendProfilingContext.
Referenced by IBackendProfilingContext::~IBackendProfilingContext().
The documentation for this class was generated from the following file:
include/armnn/backends/profiling/IBackendProfilingContext.hpp