ArmNN: Deserializer Class Reference
Deserializer Class Reference
#include <Deserializer.hpp>
Public Types
using ConstTensorRawPtr = const armnnSerializer::ConstTensor *
using GraphPtr = const armnnSerializer::SerializedGraph *
using TensorRawPtr = const armnnSerializer::TensorInfo *
using PoolingDescriptor = const armnnSerializer::Pooling2dDescriptor *
using NormalizationDescriptorPtr = const armnnSerializer::NormalizationDescriptor *
using LstmDescriptorPtr = const armnnSerializer::LstmDescriptor *
using LstmInputParamsPtr = const armnnSerializer::LstmInputParams *
using QLstmDescriptorPtr = const armnnSerializer::QLstmDescriptor *
using QunatizedLstmInputParamsPtr = const armnnSerializer::QuantizedLstmInputParams *
using TensorRawPtrVector = std::vector< TensorRawPtr >
using LayerRawPtr = const armnnSerializer::LayerBase *
using LayerBaseRawPtr = const armnnSerializer::LayerBase *
using LayerBaseRawPtrVector = std::vector< LayerBaseRawPtr >
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent) override
Create an input network from binary file contents.
armnn::INetworkPtr CreateNetworkFromBinary (std::istream &binaryContent) override
Create an input network from a binary input stream.
BindingPointInfo GetNetworkInputBindingInfo (unsigned int layerId, const std::string &name) const override
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
BindingPointInfo GetNetworkOutputBindingInfo (unsigned int layerId, const std::string &name) const override
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Deserializer ()
~Deserializer ()
Static Public Member Functions
static GraphPtr LoadGraphFromBinary (const uint8_t *binaryContent, size_t len)
static TensorRawPtrVector GetInputs (const GraphPtr &graph, unsigned int layerIndex)
static TensorRawPtrVector GetOutputs (const GraphPtr &graph, unsigned int layerIndex)
static LayerBaseRawPtr GetBaseLayer (const GraphPtr &graphPtr, unsigned int layerIndex)
static int32_t GetBindingLayerInfo (const GraphPtr &graphPtr, unsigned int layerIndex)
static std::string GetLayerName (const GraphPtr &graph, unsigned int index)
static armnn::Pooling2dDescriptor GetPoolingDescriptor (PoolingDescriptor pooling2dDescriptor, unsigned int layerIndex)
static armnn::NormalizationDescriptor GetNormalizationDescriptor (NormalizationDescriptorPtr normalizationDescriptor, unsigned int layerIndex)
static armnn::LstmDescriptor GetLstmDescriptor (LstmDescriptorPtr lstmDescriptor)
static armnn::LstmInputParams GetLstmInputParams (LstmDescriptorPtr lstmDescriptor, LstmInputParamsPtr lstmInputParams)
static armnn::QLstmDescriptor GetQLstmDescriptor (QLstmDescriptorPtr qLstmDescriptorPtr)
static armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo &inputTensorInfo, const std::vector< uint32_t > &targetDimsIn)
Static Public Member Functions inherited from IDeserializer
static IDeserializer * CreateRaw ()
static IDeserializerPtr Create ()
static void Destroy (IDeserializer *parser)
Additional Inherited Members
Protected Member Functions inherited from IDeserializer
virtual ~IDeserializer ()
Detailed Description
Definition at line 16 of file Deserializer.hpp.
Member Typedef Documentation
ConstTensorRawPtr
using ConstTensorRawPtr = const armnnSerializer::ConstTensor *
Definition at line 20 of file Deserializer.hpp.
GraphPtr
using GraphPtr = const armnnSerializer::SerializedGraph *
Definition at line 21 of file Deserializer.hpp.
LayerBaseRawPtr
using LayerBaseRawPtr = const armnnSerializer::LayerBase *
Definition at line 31 of file Deserializer.hpp.
LayerBaseRawPtrVector
using LayerBaseRawPtrVector = std::vector<LayerBaseRawPtr>
Definition at line 32 of file Deserializer.hpp.
LayerRawPtr
using LayerRawPtr = const armnnSerializer::LayerBase *
Definition at line 30 of file Deserializer.hpp.
LstmDescriptorPtr
using LstmDescriptorPtr = const armnnSerializer::LstmDescriptor *
Definition at line 25 of file Deserializer.hpp.
LstmInputParamsPtr
using LstmInputParamsPtr = const armnnSerializer::LstmInputParams *
Definition at line 26 of file Deserializer.hpp.
NormalizationDescriptorPtr
using NormalizationDescriptorPtr = const armnnSerializer::NormalizationDescriptor *
Definition at line 24 of file Deserializer.hpp.
PoolingDescriptor
using PoolingDescriptor = const armnnSerializer::Pooling2dDescriptor *
Definition at line 23 of file Deserializer.hpp.
QLstmDescriptorPtr
using QLstmDescriptorPtr = const armnnSerializer::QLstmDescriptor *
Definition at line 27 of file Deserializer.hpp.
QunatizedLstmInputParamsPtr
using QunatizedLstmInputParamsPtr = const armnnSerializer::QuantizedLstmInputParams *
Definition at line 28 of file Deserializer.hpp.
TensorRawPtr
using TensorRawPtr = const armnnSerializer::TensorInfo *
Definition at line 22 of file Deserializer.hpp.
TensorRawPtrVector
using TensorRawPtrVector = std::vector<TensorRawPtr>
Definition at line 29 of file Deserializer.hpp.
Constructor & Destructor Documentation
Deserializer()
Deserializer ()
Definition at line 167 of file Deserializer.cpp.
Referenced by IDeserializer::CreateRaw(), and Deserializer::~Deserializer().
 : m_Network(nullptr, nullptr),
 //May require LayerType_Max to be included
 m_ParserFunctions(Layer_MAX+1, &Deserializer::ParseUnsupportedLayer)
 {
     // register supported layers
     m_ParserFunctions[Layer_AbsLayer]                    = &Deserializer::ParseAbs;
     m_ParserFunctions[Layer_ActivationLayer]             = &Deserializer::ParseActivation;
     m_ParserFunctions[Layer_AdditionLayer]               = &Deserializer::ParseAdd;
     m_ParserFunctions[Layer_ArgMinMaxLayer]              = &Deserializer::ParseArgMinMax;
     m_ParserFunctions[Layer_BatchToSpaceNdLayer]         = &Deserializer::ParseBatchToSpaceNd;
     m_ParserFunctions[Layer_BatchNormalizationLayer]     = &Deserializer::ParseBatchNormalization;
     m_ParserFunctions[Layer_ComparisonLayer]             = &Deserializer::ParseComparison;
     m_ParserFunctions[Layer_ConcatLayer]                 = &Deserializer::ParseConcat;
     m_ParserFunctions[Layer_ConstantLayer]               = &Deserializer::ParseConstant;
     m_ParserFunctions[Layer_Convolution2dLayer]          = &Deserializer::ParseConvolution2d;
     m_ParserFunctions[Layer_DepthToSpaceLayer]           = &Deserializer::ParseDepthToSpace;
     m_ParserFunctions[Layer_DepthwiseConvolution2dLayer] = &Deserializer::ParseDepthwiseConvolution2d;
     m_ParserFunctions[Layer_DequantizeLayer]             = &Deserializer::ParseDequantize;
     m_ParserFunctions[Layer_DetectionPostProcessLayer]   = &Deserializer::ParseDetectionPostProcess;
     m_ParserFunctions[Layer_DivisionLayer]               = &Deserializer::ParseDivision;
     m_ParserFunctions[Layer_ElementwiseUnaryLayer]       = &Deserializer::ParseElementwiseUnary;
     m_ParserFunctions[Layer_EqualLayer]                  = &Deserializer::ParseEqual;
     m_ParserFunctions[Layer_FullyConnectedLayer]         = &Deserializer::ParseFullyConnected;
     m_ParserFunctions[Layer_FillLayer]                   = &Deserializer::ParseFill;
     m_ParserFunctions[Layer_FloorLayer]                  = &Deserializer::ParseFloor;
     m_ParserFunctions[Layer_GatherLayer]                 = &Deserializer::ParseGather;
     m_ParserFunctions[Layer_GreaterLayer]                = &Deserializer::ParseGreater;
     m_ParserFunctions[Layer_InstanceNormalizationLayer]  = &Deserializer::ParseInstanceNormalization;
     m_ParserFunctions[Layer_L2NormalizationLayer]        = &Deserializer::ParseL2Normalization;
     m_ParserFunctions[Layer_LogicalBinaryLayer]          = &Deserializer::ParseLogicalBinary;
     m_ParserFunctions[Layer_LogSoftmaxLayer]             = &Deserializer::ParseLogSoftmax;
     m_ParserFunctions[Layer_LstmLayer]                   = &Deserializer::ParseLstm;
     m_ParserFunctions[Layer_MaximumLayer]                = &Deserializer::ParseMaximum;
     m_ParserFunctions[Layer_MeanLayer]                   = &Deserializer::ParseMean;
     m_ParserFunctions[Layer_MinimumLayer]                = &Deserializer::ParseMinimum;
     m_ParserFunctions[Layer_MergeLayer]                  = &Deserializer::ParseMerge;
     m_ParserFunctions[Layer_MergerLayer]                 = &Deserializer::ParseConcat;
     m_ParserFunctions[Layer_MultiplicationLayer]         = &Deserializer::ParseMultiplication;
     m_ParserFunctions[Layer_NormalizationLayer]          = &Deserializer::ParseNormalization;
     m_ParserFunctions[Layer_PadLayer]                    = &Deserializer::ParsePad;
     m_ParserFunctions[Layer_PermuteLayer]                = &Deserializer::ParsePermute;
     m_ParserFunctions[Layer_Pooling2dLayer]              = &Deserializer::ParsePooling2d;
     m_ParserFunctions[Layer_PreluLayer]                  = &Deserializer::ParsePrelu;
     m_ParserFunctions[Layer_QLstmLayer]                  = &Deserializer::ParseQLstm;
     m_ParserFunctions[Layer_QuantizeLayer]               = &Deserializer::ParseQuantize;
     m_ParserFunctions[Layer_QuantizedLstmLayer]          = &Deserializer::ParseQuantizedLstm;
     m_ParserFunctions[Layer_RankLayer]                   = &Deserializer::ParseRank;
     m_ParserFunctions[Layer_ReshapeLayer]                = &Deserializer::ParseReshape;
     m_ParserFunctions[Layer_ResizeBilinearLayer]         = &Deserializer::ParseResizeBilinear;
     m_ParserFunctions[Layer_ResizeLayer]                 = &Deserializer::ParseResize;
     m_ParserFunctions[Layer_RsqrtLayer]                  = &Deserializer::ParseRsqrt;
     m_ParserFunctions[Layer_SliceLayer]                  = &Deserializer::ParseSlice;
     m_ParserFunctions[Layer_SoftmaxLayer]                = &Deserializer::ParseSoftmax;
     m_ParserFunctions[Layer_SpaceToBatchNdLayer]         = &Deserializer::ParseSpaceToBatchNd;
     m_ParserFunctions[Layer_SpaceToDepthLayer]           = &Deserializer::ParseSpaceToDepth;
     m_ParserFunctions[Layer_SplitterLayer]               = &Deserializer::ParseSplitter;
     m_ParserFunctions[Layer_StackLayer]                  = &Deserializer::ParseStack;
     m_ParserFunctions[Layer_StandInLayer]                = &Deserializer::ParseStandIn;
     m_ParserFunctions[Layer_StridedSliceLayer]           = &Deserializer::ParseStridedSlice;
     m_ParserFunctions[Layer_SubtractionLayer]            = &Deserializer::ParseSubtraction;
     m_ParserFunctions[Layer_SwitchLayer]                 = &Deserializer::ParseSwitch;
     m_ParserFunctions[Layer_TransposeConvolution2dLayer] = &Deserializer::ParseTransposeConvolution2d;
     m_ParserFunctions[Layer_TransposeLayer]              = &Deserializer::ParseTranspose;
 }
~Deserializer()
~Deserializer () inline
Definition at line 49 of file Deserializer.hpp.
References Deserializer::Deserializer(), Deserializer::GetBaseLayer(), Deserializer::GetBindingLayerInfo(), Deserializer::GetInputs(), Deserializer::GetLayerName(), Deserializer::GetLstmDescriptor(), Deserializer::GetLstmInputParams(), Deserializer::GetNormalizationDescriptor(), Deserializer::GetOutputs(), Deserializer::GetPoolingDescriptor(), Deserializer::GetQLstmDescriptor(), Deserializer::LoadGraphFromBinary(), and Deserializer::OutputShapeOfReshape().
 {}
Member Function Documentation
CreateNetworkFromBinary() [1/2]
INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent) override virtual
Create an input network from binary file contents.
Implements IDeserializer.
Definition at line 703 of file Deserializer.cpp.
References Deserializer::LoadGraphFromBinary().
 {
      ResetParser();
      GraphPtr graph = LoadGraphFromBinary(binaryContent.data(), binaryContent.size());
      return CreateNetworkFromGraph(graph);
 }
CreateNetworkFromBinary() [2/2]
armnn::INetworkPtr CreateNetworkFromBinary (std::istream & binaryContent) override virtual
Create an input network from a binary input stream.
Implements IDeserializer.
Definition at line 710 of file Deserializer.cpp.
References Deserializer::LoadGraphFromBinary().
 {
     ResetParser();
     std::vector<uint8_t> content((std::istreambuf_iterator<char>(binaryContent)), std::istreambuf_iterator<char>());
     GraphPtr graph = LoadGraphFromBinary(content.data(), content.size());
     return CreateNetworkFromGraph(graph);
 }
GetBaseLayer()
Deserializer::LayerBaseRawPtr GetBaseLayer (const GraphPtr & graphPtr, unsigned int layerIndex) static
Definition at line 233 of file Deserializer.cpp.
Referenced by Deserializer::GetInputs(), Deserializer::GetLayerName(), Deserializer::GetNetworkOutputBindingInfo(), Deserializer::GetOutputs(), and Deserializer::~Deserializer().
 {
     auto layerType = graphPtr->layers()->Get(layerIndex)->layer_type();
     switch(layerType)
     {
         case Layer::Layer_AbsLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_AbsLayer()->base();
         case Layer::Layer_ActivationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ActivationLayer()->base();
         case Layer::Layer_AdditionLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_AdditionLayer()->base();
         case Layer::Layer_ArgMinMaxLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ArgMinMaxLayer()->base();
         case Layer::Layer_BatchToSpaceNdLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_BatchToSpaceNdLayer()->base();
         case Layer::Layer_BatchNormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_BatchNormalizationLayer()->base();
         case Layer::Layer_ComparisonLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ComparisonLayer()->base();
         case Layer::Layer_ConcatLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ConcatLayer()->base();
         case Layer::Layer_ConstantLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ConstantLayer()->base();
         case Layer::Layer_Convolution2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_Convolution2dLayer()->base();
         case Layer::Layer_DepthToSpaceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DepthToSpaceLayer()->base();
         case Layer::Layer_DepthwiseConvolution2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DepthwiseConvolution2dLayer()->base();
         case Layer::Layer_DequantizeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DequantizeLayer()->base();
         case Layer::Layer_DetectionPostProcessLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DetectionPostProcessLayer()->base();
         case Layer::Layer_DivisionLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_DivisionLayer()->base();
         case Layer::Layer_EqualLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_EqualLayer()->base();
         case Layer::Layer_ElementwiseUnaryLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ElementwiseUnaryLayer()->base();
         case Layer::Layer_FullyConnectedLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_FullyConnectedLayer()->base();
         case Layer::Layer_FillLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_FillLayer()->base();
         case Layer::Layer_FloorLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_FloorLayer()->base();
         case Layer::Layer_GatherLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_GatherLayer()->base();
         case Layer::Layer_GreaterLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_GreaterLayer()->base();
         case Layer::Layer_InputLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_InputLayer()->base()->base();
         case Layer::Layer_InstanceNormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_InstanceNormalizationLayer()->base();
         case Layer::Layer_L2NormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_L2NormalizationLayer()->base();
         case Layer::Layer_LogicalBinaryLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_LogicalBinaryLayer()->base();
         case Layer::Layer_LogSoftmaxLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_LogSoftmaxLayer()->base();
         case Layer::Layer_LstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_LstmLayer()->base();
         case Layer::Layer_MeanLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MeanLayer()->base();
         case Layer::Layer_MinimumLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MinimumLayer()->base();
         case Layer::Layer_MaximumLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MaximumLayer()->base();
         case Layer::Layer_MergeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MergeLayer()->base();
         case Layer::Layer_MergerLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MergerLayer()->base();
         case Layer::Layer_MultiplicationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_MultiplicationLayer()->base();
         case Layer::Layer_NormalizationLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_NormalizationLayer()->base();
         case Layer::Layer_OutputLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_OutputLayer()->base()->base();
         case Layer::Layer_PadLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_PadLayer()->base();
         case Layer::Layer_PermuteLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_PermuteLayer()->base();
         case Layer::Layer_Pooling2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_Pooling2dLayer()->base();
         case Layer::Layer_PreluLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_PreluLayer()->base();
         case Layer::Layer_QLstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_QLstmLayer()->base();
         case Layer::Layer_QuantizeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_QuantizeLayer()->base();
         case Layer::Layer_QuantizedLstmLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_QuantizedLstmLayer()->base();
         case Layer::Layer_RankLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_RankLayer()->base();
         case Layer::Layer_ReshapeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ReshapeLayer()->base();
         case Layer::Layer_ResizeBilinearLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ResizeBilinearLayer()->base();
         case Layer::Layer_ResizeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_ResizeLayer()->base();
         case Layer::Layer_RsqrtLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_RsqrtLayer()->base();
         case Layer::Layer_SliceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SliceLayer()->base();
         case Layer::Layer_SoftmaxLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SoftmaxLayer()->base();
         case Layer::Layer_SpaceToBatchNdLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SpaceToBatchNdLayer()->base();
         case Layer::Layer_SpaceToDepthLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SpaceToDepthLayer()->base();
         case Layer::Layer_SplitterLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SplitterLayer()->base();
         case Layer::Layer_StackLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_StackLayer()->base();
         case Layer::Layer_StandInLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_StandInLayer()->base();
         case Layer::Layer_StridedSliceLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_StridedSliceLayer()->base();
         case Layer::Layer_SubtractionLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SubtractionLayer()->base();
         case Layer::Layer_SwitchLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_SwitchLayer()->base();
         case Layer::Layer_TransposeConvolution2dLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_TransposeConvolution2dLayer()->base();
         case Layer::Layer_TransposeLayer:
             return graphPtr->layers()->Get(layerIndex)->layer_as_TransposeLayer()->base();
         case Layer::Layer_NONE:
         default:
             throw ParseException(fmt::format("Layer type {} not recognized", layerType));
     }
 }
GetBindingLayerInfo()
int32_t GetBindingLayerInfo (const GraphPtr & graphPtr, unsigned int layerIndex) static
Definition at line 372 of file Deserializer.cpp.
Referenced by Deserializer::GetNetworkOutputBindingInfo(), and Deserializer::~Deserializer().
 {
     auto layerType = graphPtr->layers()->Get(layerIndex)->layer_type();
     if (layerType == Layer::Layer_InputLayer)
     {
         return graphPtr->layers()->Get(layerIndex)->layer_as_InputLayer()->base()->layerBindingId();
     }
     else if ( layerType == Layer::Layer_OutputLayer )
     {
         return graphPtr->layers()->Get(layerIndex)->layer_as_OutputLayer()->base()->layerBindingId();
     }
     return 0;
 }
GetInputs()
Deserializer::TensorRawPtrVector GetInputs (const GraphPtr & graph, unsigned int layerIndex) static
Definition at line 636 of file Deserializer.cpp.
References CHECK_LAYERS, CHECKED_NON_NEGATIVE, and Deserializer::GetBaseLayer().
Referenced by Deserializer::GetLstmDescriptor(), Deserializer::GetNetworkOutputBindingInfo(), Deserializer::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), Deserializer::GetPoolingDescriptor(), Deserializer::GetQLstmDescriptor(), Deserializer::OutputShapeOfReshape(), and Deserializer::~Deserializer().
 {
     CHECK_LAYERS(graphPtr, 0, layerIndex);
     auto layer = GetBaseLayer(graphPtr, layerIndex);
     const auto& numInputs = layer->inputSlots()->size();
     TensorRawPtrVector result(numInputs);
    for (unsigned int i=0; i<numInputs; ++i)
    {
        auto inputId = CHECKED_NON_NEGATIVE(static_cast<int32_t>
                                           (layer->inputSlots()->Get(i)->connection()->sourceLayerIndex()));
        result[i] = GetBaseLayer(graphPtr, inputId)->outputSlots()->Get(0)->tensorInfo();
    }
    return result;
 }
GetLayerName()
std::string GetLayerName (const GraphPtr & graph, unsigned int index) static
Definition at line 365 of file Deserializer.cpp.
References Deserializer::GetBaseLayer().
Referenced by Deserializer::GetLstmDescriptor(), Deserializer::GetNetworkOutputBindingInfo(), Deserializer::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), Deserializer::GetPoolingDescriptor(), Deserializer::GetQLstmDescriptor(), Deserializer::OutputShapeOfReshape(), and Deserializer::~Deserializer().
 {
     auto layer = GetBaseLayer(graph, index);
     assert(layer);
     return layer->layerName()->str();
 }
GetLstmDescriptor()
armnn::LstmDescriptor GetLstmDescriptor (Deserializer::LstmDescriptorPtr lstmDescriptor) static
Definition at line 2564 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_VALID_SIZE, Deserializer::GetInputs(), Deserializer::GetLayerName(), Deserializer::GetOutputs(), IConnectableLayer::GetOutputSlot(), LstmDescriptor::m_ActivationFunc, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, LstmDescriptor::m_CifgEnabled, LstmDescriptor::m_ClippingThresCell, LstmDescriptor::m_ClippingThresProj, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, LstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, LstmDescriptor::m_LayerNormEnabled, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, LstmDescriptor::m_PeepholeEnabled, LstmInputParams::m_ProjectionBias, LstmDescriptor::m_ProjectionEnabled, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToOutputWeights, IOutputSlot::SetTensorInfo(), armnnDeserializer::ToConstTensor(), and armnnDeserializer::ToTensorInfo().
Referenced by Deserializer::~Deserializer().
 {
     armnn::LstmDescriptor desc;
     desc.m_ActivationFunc = lstmDescriptor->activationFunc();
     desc.m_ClippingThresCell = lstmDescriptor->clippingThresCell();
     desc.m_ClippingThresProj = lstmDescriptor->clippingThresProj();
     desc.m_CifgEnabled = lstmDescriptor->cifgEnabled();
     desc.m_PeepholeEnabled = lstmDescriptor->peepholeEnabled();
     desc.m_ProjectionEnabled = lstmDescriptor->projectionEnabled();
     desc.m_LayerNormEnabled = lstmDescriptor->layerNormEnabled();
     return desc;
 }
GetLstmInputParams()
static armnn::LstmInputParams GetLstmInputParams (LstmDescriptorPtr lstmDescriptor, LstmInputParamsPtr lstmInputParams) static
Referenced by Deserializer::~Deserializer().
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (unsigned int layerId, const std::string & name) const override virtual
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Implements IDeserializer.
Definition at line 777 of file Deserializer.cpp.
References CHECK_LOCATION, and armnn::IgnoreUnused().
 {
     IgnoreUnused(layerIndex);
     for (auto inputBinding : m_InputBindings)
     {
         if (inputBinding.first == name)
         {
             return inputBinding.second;
         }
     }
     throw ParseException(fmt::format("No input binding found for layer:{0} / {1}",
                                      name,
                                      CHECK_LOCATION().AsString()));
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (unsigned int layerId, const std::string & name) const override virtual
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Implements IDeserializer.
Definition at line 793 of file Deserializer.cpp.
References armnn::Abs, anchors(), ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_GRAPH, CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, armnn::Equal, Deserializer::GetBaseLayer(), Deserializer::GetBindingLayerInfo(), Deserializer::GetInputs(), IConnectableLayer::GetInputSlot(), Deserializer::GetLayerName(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetNumOutputSlots(), Deserializer::GetOutputs(), IConnectableLayer::GetOutputSlot(), armnn::Greater, armnn::IgnoreUnused(), ActivationDescriptor::m_A, ArgMinMaxDescriptor::m_Axis, ActivationDescriptor::m_B, SoftmaxDescriptor::m_Beta, InstanceNormalizationDescriptor::m_Beta, Convolution2dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, BatchToSpaceNdDescriptor::m_BlockShape, SpaceToDepthDescriptor::m_BlockSize, BatchToSpaceNdDescriptor::m_Crops, Convolution2dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, L2NormalizationDescriptor::m_DataLayout, BatchNormalizationDescriptor::m_DataLayout, InstanceNormalizationDescriptor::m_DataLayout, BatchToSpaceNdDescriptor::m_DataLayout, SpaceToDepthDescriptor::m_DataLayout, DetectionPostProcessDescriptor::m_DetectionsPerClass, Convolution2dDescriptor::m_DilationX, DepthwiseConvolution2dDescriptor::m_DilationX, Convolution2dDescriptor::m_DilationY, DepthwiseConvolution2dDescriptor::m_DilationY, L2NormalizationDescriptor::m_Eps, BatchNormalizationDescriptor::m_Eps, InstanceNormalizationDescriptor::m_Eps, ActivationDescriptor::m_Function, ArgMinMaxDescriptor::m_Function, InstanceNormalizationDescriptor::m_Gamma, DetectionPostProcessDescriptor::m_MaxClassesPerDetection, DetectionPostProcessDescriptor::m_MaxDetections, DetectionPostProcessDescriptor::m_NmsIouThreshold, DetectionPostProcessDescriptor::m_NmsScoreThreshold, DetectionPostProcessDescriptor::m_NumClasses, LogicalBinaryDescriptor::m_Operation, Convolution2dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, DetectionPostProcessDescriptor::m_ScaleH, DetectionPostProcessDescriptor::m_ScaleW, DetectionPostProcessDescriptor::m_ScaleX, DetectionPostProcessDescriptor::m_ScaleY, Convolution2dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, DepthwiseConvolution2dDescriptor::m_StrideY, DetectionPostProcessDescriptor::m_UseRegularNms, armnn::numeric_cast(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToActivationFunction(), armnnDeserializer::ToArgMinMaxFunction(), armnnDeserializer::ToConstTensor(), armnnDeserializer::ToDataLayout(), armnnDeserializer::ToLogicalBinaryOperation(), and armnnDeserializer::ToTensorInfo().
 {
     IgnoreUnused(layerIndex);
     for (auto outputBinding : m_OutputBindings)
     {
         if (outputBinding.first == name)
         {
             return outputBinding.second;
         }
     }
     throw ParseException(fmt::format("No output binding found for layer:{0} / {1}",
                                      name,
                                      CHECK_LOCATION().AsString()));
 }
GetNormalizationDescriptor()
armnn::NormalizationDescriptor GetNormalizationDescriptor (Deserializer::NormalizationDescriptorPtr normalizationDescriptor, unsigned int layerIndex) static
Definition at line 2255 of file Deserializer.cpp.
References armnn::Across, ARMNN_ASSERT_MSG, CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, Deserializer::GetInputs(), Deserializer::GetLayerName(), Deserializer::GetOutputs(), IConnectableLayer::GetOutputSlot(), armnn::IgnoreUnused(), armnn::LocalBrightness, armnn::LocalContrast, NormalizationDescriptor::m_Alpha, GatherDescriptor::m_Axis, MeanDescriptor::m_Axis, SliceDescriptor::m_Begin, NormalizationDescriptor::m_Beta, NormalizationDescriptor::m_DataLayout, NormalizationDescriptor::m_K, MeanDescriptor::m_KeepDims, NormalizationDescriptor::m_NormChannelType, NormalizationDescriptor::m_NormMethodType, NormalizationDescriptor::m_NormSize, SliceDescriptor::m_Size, armnn::NCHW, armnn::NHWC, armnn::Rsqrt, IOutputSlot::SetTensorInfo(), ViewsDescriptor::SetViewOriginCoord(), ViewsDescriptor::SetViewSize(), armnnDeserializer::ToDataLayout(), armnnDeserializer::ToTensorInfo(), and armnn::Within.
Referenced by Deserializer::~Deserializer().
 {
     IgnoreUnused(layerIndex);
     armnn::NormalizationDescriptor desc;
     switch (normalizationDescriptor->normChannelType())
     {
         case NormalizationAlgorithmChannel_Across:
         {
             desc.m_NormChannelType = armnn::NormalizationAlgorithmChannel::Across;
             break;
         }
         case NormalizationAlgorithmChannel_Within:
         {
             desc.m_NormChannelType = armnn::NormalizationAlgorithmChannel::Within;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported normalization channel type");
         }
     }
     switch (normalizationDescriptor->normMethodType())
     {
         case NormalizationAlgorithmMethod_LocalBrightness:
         {
             desc.m_NormMethodType = armnn::NormalizationAlgorithmMethod::LocalBrightness;
             break;
         }
         case NormalizationAlgorithmMethod_LocalContrast:
         {
             desc.m_NormMethodType = armnn::NormalizationAlgorithmMethod::LocalContrast;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported normalization method type");
         }
     }
     switch (normalizationDescriptor->dataLayout())
     {
         case DataLayout_NCHW:
         {
             desc.m_DataLayout = armnn::DataLayout::NCHW;
             break;
         }
         case DataLayout_NHWC:
         {
             desc.m_DataLayout = armnn::DataLayout::NHWC;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported data layout");
         }
     }
     desc.m_Alpha    = normalizationDescriptor->alpha();
     desc.m_Beta     = normalizationDescriptor->beta();
     desc.m_K        = normalizationDescriptor->k();
     desc.m_NormSize = normalizationDescriptor->normSize();
     return desc;
 }
GetOutputs()
Deserializer::TensorRawPtrVector GetOutputs (const GraphPtr & graph, unsigned int layerIndex) static
Definition at line 654 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_LOCATION, and Deserializer::GetBaseLayer().
Referenced by Deserializer::GetLstmDescriptor(), Deserializer::GetNetworkOutputBindingInfo(), Deserializer::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), Deserializer::GetPoolingDescriptor(), Deserializer::GetQLstmDescriptor(), Deserializer::OutputShapeOfReshape(), and Deserializer::~Deserializer().
 {
     CHECK_LAYERS(graphPtr, 0, layerIndex);
     auto layer = GetBaseLayer(graphPtr, layerIndex);
     const auto& numOutputs = layer->outputSlots()->size();
     TensorRawPtrVector result(numOutputs);
     for (unsigned int i=0; i<numOutputs; ++i)
     {
         result[i] = layer->outputSlots()->Get(i)->tensorInfo();
     }
     return result;
 }
GetPoolingDescriptor()
armnn::Pooling2dDescriptor GetPoolingDescriptor (Deserializer::PoolingDescriptor pooling2dDesc, unsigned int layerIndex) static
Definition at line 1880 of file Deserializer.cpp.
References ARMNN_ASSERT_MSG, armnn::Average, armnn::Ceiling, CHECK_LAYERS, CHECK_VALID_SIZE, armnn::Exclude, armnn::Floor, Deserializer::GetInputs(), Deserializer::GetLayerName(), Deserializer::GetOutputs(), IConnectableLayer::GetOutputSlot(), armnn::IgnoreUnused(), armnn::IgnoreValue, Pooling2dDescriptor::m_DataLayout, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, armnn::Max, armnn::NCHW, armnn::NHWC, IOutputSlot::SetTensorInfo(), and armnnDeserializer::ToTensorInfo().
Referenced by Deserializer::~Deserializer().
 {
     IgnoreUnused(layerIndex);
     armnn::Pooling2dDescriptor desc;
     switch (pooling2dDesc->poolType())
     {
         case PoolingAlgorithm_Average:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::Average;
             break;
         }
         case PoolingAlgorithm_Max:
         {
             desc.m_PoolType = armnn::PoolingAlgorithm::Max;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported pooling algorithm");
         }
     }
     switch (pooling2dDesc->outputShapeRounding())
     {
         case OutputShapeRounding_Floor:
         {
             desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Floor;
             break;
         }
         case OutputShapeRounding_Ceiling:
         {
             desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Ceiling;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported output shape rounding");
         }
     }
     switch (pooling2dDesc->paddingMethod())
     {
         case PaddingMethod_Exclude:
         {
             desc.m_PaddingMethod = armnn::PaddingMethod::Exclude;
             break;
         }
         case PaddingMethod_IgnoreValue:
         {
             desc.m_PaddingMethod = armnn::PaddingMethod::IgnoreValue;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported padding method");
         }
     }
     switch (pooling2dDesc->dataLayout())
     {
         case DataLayout_NCHW:
         {
             desc.m_DataLayout = armnn::DataLayout::NCHW;
             break;
         }
         case DataLayout_NHWC:
         {
             desc.m_DataLayout = armnn::DataLayout::NHWC;
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "Unsupported data layout");
         }
     }
     desc.m_PadRight   = pooling2dDesc->padRight();
     desc.m_PadLeft    = pooling2dDesc->padLeft();
     desc.m_PadBottom  = pooling2dDesc->padBottom();
     desc.m_PadTop     = pooling2dDesc->padTop();
     desc.m_StrideX    = pooling2dDesc->strideX();
     desc.m_StrideY    = pooling2dDesc->strideY();
     desc.m_PoolWidth  = pooling2dDesc->poolWidth();
     desc.m_PoolHeight = pooling2dDesc->poolHeight();
     return desc;
 }
GetQLstmDescriptor()
armnn::QLstmDescriptor GetQLstmDescriptor (Deserializer::QLstmDescriptorPtr qLstmDescriptor) static
Definition at line 2695 of file Deserializer.cpp.
References CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, Deserializer::GetInputs(), Deserializer::GetLayerName(), Deserializer::GetOutputs(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), TransposeConvolution2dDescriptor::m_BiasEnabled, QuantizedLstmInputParams::m_CellBias, LstmInputParams::m_CellBias, QLstmDescriptor::m_CellClip, QLstmDescriptor::m_CellIntermediateScale, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, QLstmDescriptor::m_CifgEnabled, TransposeConvolution2dDescriptor::m_DataLayout, QuantizedLstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetGateBias, QLstmDescriptor::m_ForgetIntermediateScale, LstmInputParams::m_ForgetLayerNormWeights, QLstmDescriptor::m_HiddenStateScale, QLstmDescriptor::m_HiddenStateZeroPoint, QuantizedLstmInputParams::m_InputGateBias, LstmInputParams::m_InputGateBias, QLstmDescriptor::m_InputIntermediateScale, LstmInputParams::m_InputLayerNormWeights, QuantizedLstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToCellWeights, QuantizedLstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToForgetWeights, QuantizedLstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToInputWeights, QuantizedLstmInputParams::m_InputToOutputWeights, LstmInputParams::m_InputToOutputWeights, QLstmDescriptor::m_LayerNormEnabled, StandInDescriptor::m_NumInputs, StandInDescriptor::m_NumOutputs, QuantizedLstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputGateBias, QLstmDescriptor::m_OutputIntermediateScale, LstmInputParams::m_OutputLayerNormWeights, TransposeConvolution2dDescriptor::m_PadBottom, TransposeConvolution2dDescriptor::m_PadLeft, TransposeConvolution2dDescriptor::m_PadRight, TransposeConvolution2dDescriptor::m_PadTop, QLstmDescriptor::m_PeepholeEnabled, LstmInputParams::m_ProjectionBias, QLstmDescriptor::m_ProjectionClip, QLstmDescriptor::m_ProjectionEnabled, LstmInputParams::m_ProjectionWeights, QuantizedLstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToCellWeights, QuantizedLstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToForgetWeights, QuantizedLstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToInputWeights, QuantizedLstmInputParams::m_RecurrentToOutputWeights, LstmInputParams::m_RecurrentToOutputWeights, TransposeConvolution2dDescriptor::m_StrideX, TransposeConvolution2dDescriptor::m_StrideY, IOutputSlot::SetTensorInfo(), armnnDeserializer::ToConstTensor(), armnnDeserializer::ToDataLayout(), and armnnDeserializer::ToTensorInfo().
Referenced by Deserializer::~Deserializer().
 {
     armnn::QLstmDescriptor desc;
     desc.m_CifgEnabled       = qLstmDescriptor->cifgEnabled();
     desc.m_PeepholeEnabled   = qLstmDescriptor->peepholeEnabled();
     desc.m_ProjectionEnabled = qLstmDescriptor->projectionEnabled();
     desc.m_LayerNormEnabled  = qLstmDescriptor->layerNormEnabled();
     desc.m_CellClip       = qLstmDescriptor->cellClip();
     desc.m_ProjectionClip = qLstmDescriptor->projectionClip();
     desc.m_InputIntermediateScale  = qLstmDescriptor->inputIntermediateScale();
     desc.m_ForgetIntermediateScale = qLstmDescriptor->forgetIntermediateScale();
     desc.m_CellIntermediateScale   = qLstmDescriptor->cellIntermediateScale();
     desc.m_OutputIntermediateScale = qLstmDescriptor->outputIntermediateScale();
     desc.m_HiddenStateScale     = qLstmDescriptor->hiddenStateScale();
     desc.m_HiddenStateZeroPoint = qLstmDescriptor->hiddenStateZeroPoint();
     return desc;
 }
LoadGraphFromBinary()
Deserializer::GraphPtr LoadGraphFromBinary (const uint8_t * binaryContent, size_t len) static
Definition at line 718 of file Deserializer.cpp.
References ARMNN_ASSERT, CHECK_LOCATION, and IOutputSlot::Connect().
Referenced by Deserializer::CreateNetworkFromBinary(), and Deserializer::~Deserializer().
 {
     if (binaryContent == nullptr)
     {
         throw InvalidArgumentException(fmt::format("Invalid (null) binary content {}",
                                                    CHECK_LOCATION().AsString()));
     }
     flatbuffers::Verifier verifier(binaryContent, len);
     if (verifier.VerifyBuffer<SerializedGraph>() == false)
     {
         throw ParseException(fmt::format("Buffer doesn't conform to the expected Armnn "
                                          "flatbuffers format. size:{0} {1}",
                                          len,
                                          CHECK_LOCATION().AsString()));
     }
     return GetSerializedGraph(binaryContent);
 }
OutputShapeOfReshape()
armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo & inputTensorInfo, const std::vector< uint32_t > & targetDimsIn) static
Definition at line 2010 of file Deserializer.cpp.
References armnn::Bilinear, CHECK_LAYERS, CHECK_LOCATION, CHECK_VALID_SIZE, armnnDeserializer::CheckShape(), Deserializer::GetInputs(), Deserializer::GetLayerName(), TensorInfo::GetNumElements(), Deserializer::GetOutputs(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), ResizeDescriptor::m_AlignCorners, SoftmaxDescriptor::m_Beta, SpaceToBatchNdDescriptor::m_BlockShape, SpaceToDepthDescriptor::m_BlockSize, ResizeDescriptor::m_DataLayout, SpaceToBatchNdDescriptor::m_DataLayout, SpaceToDepthDescriptor::m_DataLayout, ResizeDescriptor::m_HalfPixelCenters, ResizeDescriptor::m_Method, SpaceToBatchNdDescriptor::m_PadList, ResizeDescriptor::m_TargetHeight, ReshapeDescriptor::m_TargetShape, ResizeDescriptor::m_TargetWidth, armnn::numeric_cast(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToDataLayout(), armnnDeserializer::ToResizeMethod(), and armnnDeserializer::ToTensorInfo().
Referenced by Deserializer::~Deserializer().
 {
     std::vector<unsigned int> outputDims(targetDimsIn.begin(), targetDimsIn.end());
     const auto stretchDim = std::find(targetDimsIn.begin(), targetDimsIn.end(), -1);
     if (stretchDim != targetDimsIn.end())
     {
         if (std::find(std::next(stretchDim), targetDimsIn.end(), -1) != targetDimsIn.end())
         {
             throw ParseException(fmt::format("At most one component of shape can be -1 {}",
                                              CHECK_LOCATION().AsString()));
         }
         auto targetNumElements =
            armnn::numeric_cast<unsigned int>(
                std::accumulate(targetDimsIn.begin(), targetDimsIn.end(), -1, std::multiplies<int32_t>()));
         auto stretchIndex = static_cast<size_t>(std::distance(targetDimsIn.begin(), stretchDim));
         outputDims[stretchIndex] = inputTensorInfo.GetNumElements() / targetNumElements;
     }
     TensorShape outputShape = TensorShape(static_cast<unsigned int>(outputDims.size()), outputDims.data());
     armnn::TensorInfo reshapeInfo = inputTensorInfo;
     reshapeInfo.SetShape(outputShape);
     return reshapeInfo;
 }
The documentation for this class was generated from the following files:
src/armnnDeserializer/Deserializer.hpp
src/armnnDeserializer/Deserializer.cpp