ArmNN: QuantizerVisitor Class Reference
QuantizerVisitor Class Reference
Visitor object for quantizing layers in a network.
#include <QuantizerVisitor.hpp>
Public Member Functions
QuantizerVisitor (const RangeTracker &rangeTracker, const IQuantizationScheme *quantizationScheme, bool preserveType=false)
~QuantizerVisitor ()=default
void VisitAbsLayer (const IConnectableLayer *layer, const char *name=nullptr) override
Functions to quantize the individual layers, overridden from ILayerVisitor.
void VisitActivationLayer (const IConnectableLayer *layer, const ActivationDescriptor &activationDescriptor, const char *name=nullptr) override
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitAdditionLayer (const IConnectableLayer *layer, const char *name=nullptr) override
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitArgMinMaxLayer (const IConnectableLayer *layer, const ArgMinMaxDescriptor &argMinMaxDescriptor, const char *name=nullptr) override
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchNormalizationLayer (const IConnectableLayer *layer, const BatchNormalizationDescriptor &desc, const ConstTensor &mean, const ConstTensor &variance, const ConstTensor &beta, const ConstTensor &gamma, const char *name=nullptr) override
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchToSpaceNdLayer (const IConnectableLayer *layer, const BatchToSpaceNdDescriptor &batchToSpaceNdDescriptor, const char *name=nullptr) override
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitComparisonLayer (const IConnectableLayer *layer, const ComparisonDescriptor &comparisonDescriptor, const char *name=nullptr) override
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConcatLayer (const IConnectableLayer *layer, const OriginsDescriptor &originsDescriptor, const char *name=nullptr) override
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConstantLayer (const IConnectableLayer *layer, const ConstTensor &input, const char *name=nullptr) override
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConvolution2dLayer (const IConnectableLayer *layer, const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthToSpaceLayer (const IConnectableLayer *layer, const DepthToSpaceDescriptor &depthToSpaceDescriptor, const char *name=nullptr) override
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *layer, const DepthwiseConvolution2dDescriptor &desc, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitElementwiseUnaryLayer (const IConnectableLayer *layer, const ElementwiseUnaryDescriptor &elementwiseUnaryDescriptor, const char *name=nullptr) override
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFillLayer (const IConnectableLayer *layer, const FillDescriptor &desc, const char *name) override
Function a fill layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFullyConnectedLayer (const IConnectableLayer *layer, const FullyConnectedDescriptor &desc, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInputLayer (const IConnectableLayer *layer, LayerBindingId id, const char *name=nullptr) override
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInstanceNormalizationLayer (const IConnectableLayer *layer, const InstanceNormalizationDescriptor &instanceNormalizationDescriptor, const char *name=nullptr) override
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLogSoftmaxLayer (const IConnectableLayer *layer, const LogSoftmaxDescriptor &logSoftmaxDescriptor, const char *name=nullptr) override
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMeanLayer (const IConnectableLayer *layer, const MeanDescriptor &meanDescriptor, const char *name=nullptr) override
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMultiplicationLayer (const IConnectableLayer *layer, const char *name=nullptr) override
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitNormalizationLayer (const IConnectableLayer *layer, const NormalizationDescriptor &normalizationDescriptor, const char *name=nullptr) override
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitOutputLayer (const IConnectableLayer *layer, LayerBindingId id, const char *name=nullptr) override
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPadLayer (const IConnectableLayer *, const PadDescriptor &, const char *name=nullptr) override
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPermuteLayer (const IConnectableLayer *layer, const PermuteDescriptor &permuteDescriptor, const char *name=nullptr) override
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPooling2dLayer (const IConnectableLayer *layer, const Pooling2dDescriptor &pooling2dDescriptor, const char *name=nullptr) override
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPreluLayer (const IConnectableLayer *layer, const char *name=nullptr) override
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitReshapeLayer (const IConnectableLayer *layer, const ReshapeDescriptor &reshapeDescriptor, const char *name=nullptr) override
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeLayer (const IConnectableLayer *layer, const ResizeDescriptor &resizeDescriptor, const char *name=nullptr) override
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeBilinearLayer (const IConnectableLayer *layer, const ResizeBilinearDescriptor &resizeDesc, const char *name=nullptr) override
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitRsqrtLayer (const IConnectableLayer *, const char *name=nullptr) override
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSliceLayer (const IConnectableLayer *layer, const SliceDescriptor &sliceDescriptor, const char *name=nullptr) override
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSoftmaxLayer (const IConnectableLayer *layer, const SoftmaxDescriptor &softmaxDescriptor, const char *name=nullptr) override
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToBatchNdLayer (const IConnectableLayer *layer, const SpaceToBatchNdDescriptor &spaceToBatchNdDescriptor, const char *name=nullptr) override
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToDepthLayer (const IConnectableLayer *layer, const SpaceToDepthDescriptor &spaceToDepthDescriptor, const char *name=nullptr) override
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSplitterLayer (const IConnectableLayer *layer, const SplitterDescriptor &splitterDescriptor, const char *name=nullptr) override
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStackLayer (const IConnectableLayer *layer, const StackDescriptor &stackDescriptor, const char *name=nullptr) override
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStridedSliceLayer (const IConnectableLayer *layer, const StridedSliceDescriptor &stridedSliceDescriptor, const char *name=nullptr) override
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSubtractionLayer (const IConnectableLayer *layer, const char *name=nullptr) override
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeConvolution2dLayer (const IConnectableLayer *layer, const TransposeConvolution2dDescriptor &descriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeLayer (const IConnectableLayer *layer, const TransposeDescriptor &descriptor, const char *name=nullptr) override
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
INetworkPtr RetrieveFinalNetwork ()
Extract the quantized network.
Public Member Functions inherited from LayerVisitorBase< VisitorThrowingPolicy >
void VisitAbsLayer (const IConnectableLayer *, const char *) override
Function an absolute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitActivationLayer (const IConnectableLayer *, const ActivationDescriptor &, const char *) override
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitAdditionLayer (const IConnectableLayer *, const char *) override
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitArgMinMaxLayer (const IConnectableLayer *, const ArgMinMaxDescriptor &, const char *) override
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchNormalizationLayer (const IConnectableLayer *, const BatchNormalizationDescriptor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const char *) override
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchToSpaceNdLayer (const IConnectableLayer *, const BatchToSpaceNdDescriptor &, const char *) override
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitComparisonLayer (const IConnectableLayer *, const ComparisonDescriptor &, const char *) override
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConcatLayer (const IConnectableLayer *, const ConcatDescriptor &, const char *) override
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConstantLayer (const IConnectableLayer *, const ConstTensor &, const char *) override
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConvolution2dLayer (const IConnectableLayer *, const Convolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthToSpaceLayer (const IConnectableLayer *, const DepthToSpaceDescriptor &, const char *) override
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *, const DepthwiseConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDequantizeLayer (const IConnectableLayer *, const char *) override
Function that a Dequantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDetectionPostProcessLayer (const IConnectableLayer *, const DetectionPostProcessDescriptor &, const ConstTensor &, const char *) override
Function that a Detection PostProcess layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDivisionLayer (const IConnectableLayer *, const char *) override
Function a division layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitElementwiseUnaryLayer (const IConnectableLayer *, const ElementwiseUnaryDescriptor &, const char *) override
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitEqualLayer (const IConnectableLayer *, const char *) override
Function an Equal layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFillLayer (const IConnectableLayer *, const FillDescriptor &, const char *) override
Function a fill layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFloorLayer (const IConnectableLayer *, const char *) override
Function a floor layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFullyConnectedLayer (const IConnectableLayer *, const FullyConnectedDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGatherLayer (const IConnectableLayer *, const char *) override
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGatherLayer (const IConnectableLayer *, const GatherDescriptor &, const char *) override
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGreaterLayer (const IConnectableLayer *, const char *) override
Function a Greater layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInstanceNormalizationLayer (const IConnectableLayer *, const InstanceNormalizationDescriptor &, const char *) override
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitL2NormalizationLayer (const IConnectableLayer *, const L2NormalizationDescriptor &, const char *) override
Function that an L2 normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLogSoftmaxLayer (const IConnectableLayer *, const LogSoftmaxDescriptor &, const char *) override
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLogicalBinaryLayer (const IConnectableLayer *, const LogicalBinaryDescriptor &, const char *) override
Function that a logical binary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLstmLayer (const IConnectableLayer *, const LstmDescriptor &, const LstmInputParams &, const char *) override
Function an Lstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMaximumLayer (const IConnectableLayer *, const char *) override
Function a Maximum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMeanLayer (const IConnectableLayer *, const MeanDescriptor &, const char *) override
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMergeLayer (const IConnectableLayer *, const char *) override
Function that a merge layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMergerLayer (const IConnectableLayer *, const MergerDescriptor &, const char *) override
Function that a merger layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMinimumLayer (const IConnectableLayer *, const char *) override
Function a Minimum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMultiplicationLayer (const IConnectableLayer *, const char *) override
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitNormalizationLayer (const IConnectableLayer *, const NormalizationDescriptor &, const char *) override
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitOutputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPadLayer (const IConnectableLayer *, const PadDescriptor &, const char *) override
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPermuteLayer (const IConnectableLayer *, const PermuteDescriptor &, const char *) override
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPooling2dLayer (const IConnectableLayer *, const Pooling2dDescriptor &, const char *) override
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPreluLayer (const IConnectableLayer *, const char *) override
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQuantizeLayer (const IConnectableLayer *, const char *) override
Function a quantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQLstmLayer (const IConnectableLayer *, const QLstmDescriptor &, const LstmInputParams &, const char *) override
Function a QLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQuantizedLstmLayer (const IConnectableLayer *, const QuantizedLstmInputParams &, const char *) override
Function a QuantizedLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitRankLayer (const IConnectableLayer *, const char *) override
Function a rank layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitReshapeLayer (const IConnectableLayer *, const ReshapeDescriptor &, const char *) override
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeBilinearLayer (const IConnectableLayer *, const ResizeBilinearDescriptor &, const char *) override
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeLayer (const IConnectableLayer *, const ResizeDescriptor &, const char *) override
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitRsqrtLayer (const IConnectableLayer *, const char *) override
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSliceLayer (const IConnectableLayer *, const SliceDescriptor &, const char *) override
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSoftmaxLayer (const IConnectableLayer *, const SoftmaxDescriptor &, const char *) override
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToBatchNdLayer (const IConnectableLayer *, const SpaceToBatchNdDescriptor &, const char *) override
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToDepthLayer (const IConnectableLayer *, const SpaceToDepthDescriptor &, const char *) override
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSplitterLayer (const IConnectableLayer *, const ViewsDescriptor &, const char *) override
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStackLayer (const IConnectableLayer *, const StackDescriptor &, const char *) override
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStandInLayer (const IConnectableLayer *, const StandInDescriptor &, const char *) override
Function a StandInLayer should call back to when its Accept(ILaterVisitor&) function is invoked.
void VisitStridedSliceLayer (const IConnectableLayer *, const StridedSliceDescriptor &, const char *) override
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSubtractionLayer (const IConnectableLayer *, const char *) override
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSwitchLayer (const IConnectableLayer *, const char *) override
Function a switch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeConvolution2dLayer (const IConnectableLayer *, const TransposeConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeLayer (const IConnectableLayer *, const TransposeDescriptor &, const char *) override
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Public Member Functions inherited from ILayerVisitor
virtual void StartVisit ()
virtual void FinishVisit ()
Additional Inherited Members
Protected Member Functions inherited from LayerVisitorBase< VisitorThrowingPolicy >
LayerVisitorBase ()
virtual ~LayerVisitorBase ()
Protected Member Functions inherited from ILayerVisitor
ILayerVisitor ()
virtual ~ILayerVisitor ()
Detailed Description
Visitor object for quantizing layers in a network.
Definition at line 25 of file QuantizerVisitor.hpp.
Constructor & Destructor Documentation
QuantizerVisitor()
QuantizerVisitor (const RangeTracker & rangeTracker, const IQuantizationScheme * quantizationScheme, bool preserveType = false)
Definition at line 17 of file QuantizerVisitor.cpp.
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, OutputSlot::CalculateIndexOnOwner(), IQuantizationScheme::ComputeScheme(), IOutputSlot::Connect(), InputSlot::GetConnectedOutputSlot(), IQuantizationScheme::GetDataType(), IConnectableLayer::GetGuid(), Layer::GetGuid(), BaseTensor< MemoryType >::GetInfo(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetOutputSlot(), OutputSlot::GetOwningLayer(), TensorInfo::GetQuantizationScale(), RangeTracker::GetRange(), OutputSlot::GetTensorInfo(), armnn::info, armnn::numeric_cast(), IOutputSlot::SetTensorInfo(), armnn::Signed32, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
     : m_Ranges(rangeTracker)
     , m_QuantizedNetwork(INetwork::Create())
     , m_QuantizationScheme(quantizationScheme)
     , m_PreserveType(preserveType)
 {
 }
~QuantizerVisitor()
~QuantizerVisitor () default
Member Function Documentation
RetrieveFinalNetwork()
INetworkPtr RetrieveFinalNetwork () inline
Extract the quantized network.
Definition at line 199 of file QuantizerVisitor.hpp.
 { return std::move(m_QuantizedNetwork); }
VisitAbsLayer()
void VisitAbsLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Functions to quantize the individual layers, overridden from ILayerVisitor.
Implements ILayerVisitor.
Definition at line 119 of file QuantizerVisitor.cpp.
References armnn::Abs, and QuantizerVisitor::VisitElementwiseUnaryLayer().
 {
     VisitElementwiseUnaryLayer(layer, ElementwiseUnaryDescriptor(UnaryOperation::Abs), name);
 }
VisitActivationLayer()
void VisitActivationLayer (const IConnectableLayer * layer, const ActivationDescriptor & activationDescriptor, const char * name = nullptr) override virtual
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
activationDescriptor - ActivationDescriptor to configure the activation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 124 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddActivationLayer(activationDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitAdditionLayer()
void VisitAdditionLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 133 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddAdditionLayer(name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitArgMinMaxLayer()
void VisitArgMinMaxLayer (const IConnectableLayer * layer, const ArgMinMaxDescriptor & argMinMaxDescriptor, const char * name = nullptr) override virtual
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
argMinMaxDescriptor - ArgMinMaxDescriptor to configure the activation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 140 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddArgMinMaxLayer(argMinMaxDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitBatchNormalizationLayer()
void VisitBatchNormalizationLayer (const IConnectableLayer * layer, const BatchNormalizationDescriptor & desc, const ConstTensor & mean, const ConstTensor & variance, const ConstTensor & beta, const ConstTensor & gamma, const char * name = nullptr) override virtual
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
mean - Pre-calculated mean for each channel.
variance - Pre-calculated variance for each channel.
beta - Per-channel additive factor.
gamma - Per-channel multiplicative factor.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 149 of file QuantizerVisitor.cpp.
References armnn::CreateQuantizedConst().
 {
     std::vector<uint8_t> meanBacking;
     ConstTensor qMean = CreateQuantizedConst(mean, meanBacking);
     std::vector<uint8_t> varianceBacking;
     ConstTensor qVariance = CreateQuantizedConst(variance, varianceBacking);
     std::vector<uint8_t> betaBacking;
     ConstTensor qBeta = CreateQuantizedConst(beta, betaBacking);
     std::vector<uint8_t> gammaBacking;
     ConstTensor qGamma = CreateQuantizedConst(gamma, gammaBacking);
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddBatchNormalizationLayer(desc,
                                                                                  qMean,
                                                                                  qVariance,
                                                                                  qBeta,
                                                                                  qGamma,
                                                                                  name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitBatchToSpaceNdLayer()
void VisitBatchToSpaceNdLayer (const IConnectableLayer * layer, const BatchToSpaceNdDescriptor & batchToSpaceNdDescriptor, const char * name = nullptr) override virtual
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
batchToSpaceNdDescriptor - Description of the layer.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 180 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddBatchToSpaceNdLayer(batchToSpaceNdDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitComparisonLayer()
void VisitComparisonLayer (const IConnectableLayer * layer, const ComparisonDescriptor & comparisonDescriptor, const char * name = nullptr) override virtual
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
comparisonDescriptor - Description of the layer.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 189 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddComparisonLayer(comparisonDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitConcatLayer()
void VisitConcatLayer (const IConnectableLayer * layer, const OriginsDescriptor & concatDescriptor, const char * name = nullptr) override virtual
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
concatDescriptor - ConcatDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Reimplemented from ILayerVisitor.
Definition at line 198 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddConcatLayer(originsDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitConstantLayer()
void VisitConstantLayer (const IConnectableLayer * layer, const ConstTensor & input, const char * name = nullptr) override virtual
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
input - Tensor to be provided as the only output of the layer. The layer will maintain its own copy of the tensor data, meaning the memory referenced by input can be freed or reused after this function is called.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 207 of file QuantizerVisitor.cpp.
References armnn::CreateQuantizedConst().
 {
     std::vector<uint8_t> inputBacking;
     ConstTensor qInput = CreateQuantizedConst(input, inputBacking);
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddConstantLayer(qInput, name);
     RecordLayer(layer, newLayer);
 }
VisitConvolution2dLayer()
void VisitConvolution2dLayer (const IConnectableLayer * layer, const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 218 of file QuantizerVisitor.cpp.
References armnn::CreateQuantizedConst(), and OptionalBase::has_value().
 {
     std::vector<uint8_t> weightsBacking;
     ConstTensor qWeights = CreateQuantizedConst(weights, weightsBacking);
     Optional<ConstTensor> optionalQBiases;
     std::vector<int32_t> biasesBacking;
     if (biases.has_value())
     {
         ConstTensor qBiases = CreateQuantizedBias(layer, qWeights, biases, biasesBacking);
         optionalQBiases = Optional<ConstTensor>(qBiases);
     }
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddConvolution2dLayer(convolution2dDescriptor,
                                                                             qWeights,
                                                                             optionalQBiases,
                                                                             name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitDepthToSpaceLayer()
void VisitDepthToSpaceLayer (const IConnectableLayer * layer, const DepthToSpaceDescriptor & depthToSpaceDescriptor, const char * name = nullptr) override virtual
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
depthToSpaceDescriptor - Parameters for the depth to space operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 244 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddDepthToSpaceLayer(descriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitDepthwiseConvolution2dLayer()
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer * layer, const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D depthwise convolution layer.
weights - Tensor for the weights. Expected format: [channelMultiplier, inputChannels, height, width].
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 253 of file QuantizerVisitor.cpp.
References armnn::CreateQuantizedConst(), and OptionalBase::has_value().
 {
     std::vector<uint8_t> weightsBacking;
     ConstTensor qWeights = CreateQuantizedConst(weights, weightsBacking);
     Optional<ConstTensor> optionalQBiases;
     std::vector<int32_t> biasesBacking;
     if (biases.has_value())
     {
         ConstTensor qBiases = CreateQuantizedBias(layer, qWeights, biases, biasesBacking);
         optionalQBiases = Optional<ConstTensor>(qBiases);
     }
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddDepthwiseConvolution2dLayer(desc,
                                                                                      qWeights,
                                                                                      optionalQBiases,
                                                                                      name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitElementwiseUnaryLayer()
void VisitElementwiseUnaryLayer (const IConnectableLayer * layer, const ElementwiseUnaryDescriptor & elementwiseUnaryDescriptor, const char * name = nullptr) override virtual
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
elementwiseUnaryDescriptor - Description of the layer.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 279 of file QuantizerVisitor.cpp.
Referenced by QuantizerVisitor::VisitAbsLayer(), and QuantizerVisitor::VisitRsqrtLayer().
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddElementwiseUnaryLayer(elementwiseUnaryDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitFillLayer()
void VisitFillLayer (const IConnectableLayer * layer, const FillDescriptor & fillDescriptor, const char * name) override virtual
Function a fill layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
fillDescriptor - Description of the layer
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 288 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddFillLayer(desc, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitFullyConnectedLayer()
void VisitFullyConnectedLayer (const IConnectableLayer * layer, const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
fullyConnectedDescriptor - Description of the fully connected layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 297 of file QuantizerVisitor.cpp.
References armnn::CreateQuantizedConst(), and OptionalBase::has_value().
 {
     std::vector<uint8_t> weightsBacking;
     ConstTensor qWeights = CreateQuantizedConst(weights, weightsBacking);
     Optional<ConstTensor> optionalQBiases;
     std::vector<int32_t> biasesBacking;
     if (biases.has_value())
     {
         ConstTensor qBiases = CreateQuantizedBias(layer, qWeights, biases, biasesBacking);
         optionalQBiases = Optional<ConstTensor>(qBiases);
     }
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddFullyConnectedLayer(desc,
                                                                              qWeights,
                                                                              optionalQBiases,
                                                                              name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitInputLayer()
void VisitInputLayer (const IConnectableLayer * layer, LayerBindingId id, const char * name = nullptr) override virtual
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
id - User generated id to uniquely identify a particular input. The same id needs to be specified when passing the inputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 323 of file QuantizerVisitor.cpp.
References IOutputSlot::Connect(), armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), IOutputSlot::GetTensorInfo(), and IOutputSlot::SetTensorInfo().
 {
     const DataType dataType = layer->GetOutputSlot(0).GetTensorInfo().GetDataType();
     IConnectableLayer* inputLayer = m_QuantizedNetwork->AddInputLayer(id, name);
     if (m_PreserveType && (dataType == DataType::Float32 || dataType == DataType::Float16))
     {
         IConnectableLayer* quantizeLayer = m_QuantizedNetwork->AddQuantizeLayer();
         inputLayer->GetOutputSlot(0).Connect(quantizeLayer->GetInputSlot(0));
         inputLayer->GetOutputSlot(0).SetTensorInfo(layer->GetOutputSlot(0).GetTensorInfo());
         RecordLayer(layer, quantizeLayer);
     }
     else
     {
         RecordLayer(layer, inputLayer);
     }
 }
VisitInstanceNormalizationLayer()
void VisitInstanceNormalizationLayer (const IConnectableLayer * layer, const InstanceNormalizationDescriptor & desc, const char * name = nullptr) override virtual
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
desc - Parameters for the instance normalization operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 341 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddInstanceNormalizationLayer(descriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitLogSoftmaxLayer()
void VisitLogSoftmaxLayer (const IConnectableLayer * layer, const LogSoftmaxDescriptor & logSoftmaxDescriptor, const char * name = nullptr) override virtual
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
logSoftmaxDescriptor - LogSoftmaxDescriptor to configure the log softmax.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 350 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddLogSoftmaxLayer(logSoftmaxDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitMeanLayer()
void VisitMeanLayer (const IConnectableLayer * layer, const MeanDescriptor & meanDescriptor, const char * name = nullptr) override virtual
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
meanDescriptor - Parameters for the mean operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 359 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddMeanLayer(meanDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitMultiplicationLayer()
void VisitMultiplicationLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 368 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddMultiplicationLayer(name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitNormalizationLayer()
void VisitNormalizationLayer (const IConnectableLayer * layer, const NormalizationDescriptor & normalizationDescriptor, const char * name = nullptr) override virtual
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
normalizationDescriptor - NormalizationDescriptor to configure the normalization.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 376 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddNormalizationLayer(normalizationDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitOutputLayer()
void VisitOutputLayer (const IConnectableLayer * layer, LayerBindingId id, const char * name = nullptr) override virtual
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
id - User generated id to uniquely identify a particular output. The same id needs to be specified when passing the outputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 385 of file QuantizerVisitor.cpp.
References IOutputSlot::Connect(), armnn::Float16, armnn::Float32, IInputSlot::GetConnection(), TensorInfo::GetDataType(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), IOutputSlot::GetTensorInfo(), armnn::info, and IOutputSlot::SetTensorInfo().
 {
     const TensorInfo& info = layer->GetInputSlot(0).GetConnection()->GetTensorInfo();
     const DataType& dataType = info.GetDataType();
     IConnectableLayer* outputLayer = m_QuantizedNetwork->AddOutputLayer(id, name);
     if (m_PreserveType  && (dataType == DataType::Float32 || dataType == DataType::Float16))
     {
         IConnectableLayer* dequantizeLayer = m_QuantizedNetwork->AddDequantizeLayer();
         RecordLayer(layer, dequantizeLayer);
         SetQuantizedInputConnections(layer, dequantizeLayer);
         dequantizeLayer->GetOutputSlot(0).Connect(outputLayer->GetInputSlot(0));
         dequantizeLayer->GetOutputSlot(0).SetTensorInfo(info);
     }
     else
     {
         RecordLayer(layer, outputLayer);
         SetQuantizedInputConnections(layer, outputLayer);
     }
 }
VisitPadLayer()
void VisitPadLayer (const IConnectableLayer * layer, const PadDescriptor & padDescriptor, const char * name = nullptr) override virtual
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
paddings - n by 2 tensor, where n is the rank of the input tensor, such that paddings[i,0] indicates the amount of padding to add in front of dimension i, and paddings[i,1] indicates the amount of padding to add after the end of dimension i
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 406 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddPadLayer(padDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitPermuteLayer()
void VisitPermuteLayer (const IConnectableLayer * layer, const PermuteDescriptor & permuteDescriptor, const char * name = nullptr) override virtual
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
permuteDescriptor - PermuteDescriptor to configure the permute.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 415 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddPermuteLayer(permuteDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitPooling2dLayer()
void VisitPooling2dLayer (const IConnectableLayer * layer, const Pooling2dDescriptor & pooling2dDescriptor, const char * name = nullptr) override virtual
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
pooling2dDescriptor - Pooling2dDescriptor to configure the pooling.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 424 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddPooling2dLayer(pooling2dDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitPreluLayer()
void VisitPreluLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 433 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddPreluLayer(name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitReshapeLayer()
void VisitReshapeLayer (const IConnectableLayer * layer, const ReshapeDescriptor & reshapeDescriptor, const char * name = nullptr) override virtual
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
reshapeDescriptor - Parameters for the reshape operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 441 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddReshapeLayer(reshapeDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitResizeBilinearLayer()
void VisitResizeBilinearLayer (const IConnectableLayer * layer, const ResizeBilinearDescriptor & resizeDesc, const char * name = nullptr) override virtual
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
resizeDesc - Parameters for the resize operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 450 of file QuantizerVisitor.cpp.
References armnn::Bilinear, ResizeBilinearDescriptor::m_DataLayout, ResizeDescriptor::m_DataLayout, ResizeDescriptor::m_Method, ResizeBilinearDescriptor::m_TargetHeight, ResizeDescriptor::m_TargetHeight, ResizeBilinearDescriptor::m_TargetWidth, ResizeDescriptor::m_TargetWidth, and QuantizerVisitor::VisitResizeLayer().
 {
     ResizeDescriptor resizeDescriptor;
     resizeDescriptor.m_Method       = ResizeMethod::Bilinear;
     resizeDescriptor.m_TargetWidth  = resizeBilinearDescriptor.m_TargetWidth;
     resizeDescriptor.m_TargetHeight = resizeBilinearDescriptor.m_TargetHeight;
     resizeDescriptor.m_DataLayout   = resizeBilinearDescriptor.m_DataLayout;
     VisitResizeLayer(layer, resizeDescriptor, name);
 }
VisitResizeLayer()
void VisitResizeLayer (const IConnectableLayer * layer, const ResizeDescriptor & resizeDescriptor, const char * name = nullptr) override virtual
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
resizeDescriptor - Parameters for the resize operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 463 of file QuantizerVisitor.cpp.
Referenced by QuantizerVisitor::VisitResizeBilinearLayer().
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddResizeLayer(resizeDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitRsqrtLayer()
void VisitRsqrtLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 472 of file QuantizerVisitor.cpp.
References armnn::Rsqrt, and QuantizerVisitor::VisitElementwiseUnaryLayer().
 {
     VisitElementwiseUnaryLayer(layer, ElementwiseUnaryDescriptor(UnaryOperation::Rsqrt), name);
 }
VisitSliceLayer()
void VisitSliceLayer (const IConnectableLayer * layer, const SliceDescriptor & sliceDescriptor, const char * name = nullptr) override virtual
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
sliceDescriptor - SliceDescriptor to configure the slice operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 477 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddSliceLayer(sliceDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitSoftmaxLayer()
void VisitSoftmaxLayer (const IConnectableLayer * layer, const SoftmaxDescriptor & softmaxDescriptor, const char * name = nullptr) override virtual
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
softmaxDescriptor - SoftmaxDescriptor to configure the softmax.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 486 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddSoftmaxLayer(softmaxDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitSpaceToBatchNdLayer()
void VisitSpaceToBatchNdLayer (const IConnectableLayer * layer, const SpaceToBatchNdDescriptor & spaceToBatchNdDescriptor, const char * name = nullptr) override virtual
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
spaceToBatchNdDescriptor - Parameters for the space to batch operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 495 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddSpaceToBatchNdLayer(spaceToBatchNdDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitSpaceToDepthLayer()
void VisitSpaceToDepthLayer (const IConnectableLayer * layer, const SpaceToDepthDescriptor & spaceToDepthDescriptor, const char * name = nullptr) override virtual
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
spaceToDepthDescriptor - Parameters for the space to depth operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 504 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddSpaceToDepthLayer(spaceToDepthDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitSplitterLayer()
void VisitSplitterLayer (const IConnectableLayer * layer, const SplitterDescriptor & splitterDescriptor, const char * name = nullptr) override virtual
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
splitterDescriptor - ViewsDescriptor to configure the splitting process. Number of Views must be equal to the number of outputs, and their order must match - e.g. first view corresponds to the first output, second view to the second output, etc....
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 513 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddSplitterLayer(splitterDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitStackLayer()
void VisitStackLayer (const IConnectableLayer * layer, const StackDescriptor & stackDescriptor, const char * name = nullptr) override virtual
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
stackDescriptor - Parameters for the stack operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 522 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddStackLayer(stackDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitStridedSliceLayer()
void VisitStridedSliceLayer (const IConnectableLayer * layer, const StridedSliceDescriptor & stridedSliceDescriptor, const char * name = nullptr) override virtual
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
stridedSliceDescriptor - Parameters for the strided slice operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 531 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddStridedSliceLayer(stridedSliceDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitSubtractionLayer()
void VisitSubtractionLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 540 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddSubtractionLayer(name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitTransposeConvolution2dLayer()
void VisitTransposeConvolution2dLayer (const IConnectableLayer * layer, const TransposeConvolution2dDescriptor & descriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
descriptor - Description of the 2D transpose convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 548 of file QuantizerVisitor.cpp.
References armnn::CreateQuantizedConst(), and OptionalBase::has_value().
 {
     // quantize weights
     std::vector<uint8_t> weightsBacking;
     ConstTensor qWeights = CreateQuantizedConst(weights, weightsBacking);
     // quantize biases
     std::vector<int32_t> biasesBacking;
     Optional<ConstTensor> optionalQBiases;
     if (biases.has_value())
     {
         ConstTensor qBiases = CreateQuantizedBias(layer, qWeights, biases, biasesBacking);
         optionalQBiases = Optional<ConstTensor>(qBiases);
     }
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddTransposeConvolution2dLayer(descriptor,
                                                                                      qWeights,
                                                                                      optionalQBiases,
                                                                                      name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
VisitTransposeLayer()
void VisitTransposeLayer (const IConnectableLayer * layer, const TransposeDescriptor & transposeDescriptor, const char * name = nullptr) override virtual
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
transposeDescriptor - TransposeDescriptor to configure the transpose.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 576 of file QuantizerVisitor.cpp.
 {
     IConnectableLayer* newLayer = m_QuantizedNetwork->AddTransposeLayer(transposeDescriptor, name);
     RecordLayer(layer, newLayer);
     SetQuantizedInputConnections(layer, newLayer);
 }
The documentation for this class was generated from the following files:
src/armnn/QuantizerVisitor.hpp
src/armnn/QuantizerVisitor.cpp