ArmNN: CaptureData Class Reference
CaptureData Class Reference
#include <Holder.hpp>
Public Member Functions
CaptureData ()
CaptureData (uint32_t capturePeriod, std::vector< uint16_t > &counterIds, std::set< armnn::BackendId > activeBackends)
CaptureData (const CaptureData &captureData)
CaptureData & operator= (const CaptureData &other)
void SetActiveBackends (const std::set< armnn::BackendId > &activeBackends)
void SetCapturePeriod (uint32_t capturePeriod)
void SetCounterIds (const std::vector< uint16_t > &counterIds)
uint32_t GetCapturePeriod () const
const std::vector< uint16_t > & GetCounterIds () const
const std::set< armnn::BackendId > & GetActiveBackends () const
bool IsCounterIdInCaptureData (uint16_t counterId)
Detailed Description
Definition at line 19 of file Holder.hpp.
Constructor & Destructor Documentation
CaptureData() [1/3]
CaptureData () inline
Definition at line 22 of file Holder.hpp.
         : m_CapturePeriod(0)
         , m_CounterIds()
         , m_ActiveBackends(){}
CaptureData() [2/3]
CaptureData (uint32_t capturePeriod, std::vector< uint16_t > & counterIds, std::set< armnn::BackendId > activeBackends) inline
Definition at line 26 of file Holder.hpp.
         : m_CapturePeriod(capturePeriod)
         , m_CounterIds(counterIds)
         , m_ActiveBackends(activeBackends){}
CaptureData() [3/3]
CaptureData (const CaptureData & captureData) inline
Definition at line 30 of file Holder.hpp.
References CaptureData::GetActiveBackends(), CaptureData::GetCapturePeriod(), CaptureData::GetCounterIds(), CaptureData::IsCounterIdInCaptureData(), CaptureData::operator=(), CaptureData::SetActiveBackends(), CaptureData::SetCapturePeriod(), and CaptureData::SetCounterIds().
         : m_CapturePeriod(captureData.m_CapturePeriod)
         , m_CounterIds(captureData.m_CounterIds)
         , m_ActiveBackends(captureData.m_ActiveBackends){}
Member Function Documentation
GetActiveBackends()
const std::set< armnn::BackendId > & GetActiveBackends () const
Definition at line 39 of file Holder.cpp.
Referenced by CaptureData::CaptureData(), and PeriodicCounterSelectionCommandHandler::operator()().
 {
     return m_ActiveBackends;
 }
GetCapturePeriod()
uint32_t GetCapturePeriod () const
Definition at line 44 of file Holder.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CaptureData::CaptureData(), BackendProfiling::GetActiveCounters(), BackendProfiling::GetCounterStatus(), and PeriodicCounterSelectionCommandHandler::operator()().
 {
     return m_CapturePeriod;
 }
GetCounterIds()
const std::vector< uint16_t > & GetCounterIds () const
Definition at line 49 of file Holder.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CaptureData::CaptureData(), BackendProfiling::GetActiveCounters(), and PeriodicCounterSelectionCommandHandler::operator()().
 {
     return m_CounterIds;
 }
IsCounterIdInCaptureData()
bool IsCounterIdInCaptureData (uint16_t counterId)
Definition at line 61 of file Holder.cpp.
Referenced by CaptureData::CaptureData(), and BackendProfiling::GetCounterStatus().
 {
     for (auto m_CounterId : m_CounterIds) {
         if (m_CounterId == counterId)
         {
             return true;
         }
     }
     // Return false by default unless counterId is found
     return false;
 }
operator=()
CaptureData & operator= (const CaptureData & other)
Definition at line 15 of file Holder.cpp.
Referenced by CaptureData::CaptureData().
 {
     m_CapturePeriod  = other.m_CapturePeriod;
     m_CounterIds     = other.m_CounterIds;
     m_ActiveBackends = other.m_ActiveBackends;
     return *this;
 }
SetActiveBackends()
void SetActiveBackends (const std::set< armnn::BackendId > & activeBackends)
Definition at line 24 of file Holder.cpp.
Referenced by CaptureData::CaptureData().
 {
     m_ActiveBackends = activeBackends;
 }
SetCapturePeriod()
void SetCapturePeriod (uint32_t capturePeriod)
Definition at line 29 of file Holder.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and CaptureData::CaptureData().
 {
     m_CapturePeriod = capturePeriod;
 }
SetCounterIds()
void SetCounterIds (const std::vector< uint16_t > & counterIds)
Definition at line 34 of file Holder.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and CaptureData::CaptureData().
 {
     m_CounterIds = counterIds;
 }
The documentation for this class was generated from the following files:
src/profiling/Holder.hpp
src/profiling/Holder.cpp