ArmNN: YoloDatabase Class Reference
YoloDatabase Class Reference
#include <YoloDatabase.hpp>
Public Types
using TTestCaseData = YoloTestCaseData
Public Member Functions
YoloDatabase (const std::string &imageDir)
std::unique_ptr< TTestCaseData > GetTestCaseData (unsigned int testCaseId)
Detailed Description
Definition at line 53 of file YoloDatabase.hpp.
Member Typedef Documentation
TTestCaseData
using TTestCaseData = YoloTestCaseData
Definition at line 56 of file YoloDatabase.hpp.
Constructor & Destructor Documentation
YoloDatabase()
YoloDatabase (const std::string & imageDir) explicit
Definition at line 68 of file YoloDatabase.cpp.
     : m_ImageDir(imageDir)
 {
 }
Member Function Documentation
GetTestCaseData()
std::unique_ptr< YoloDatabase::TTestCaseData > GetTestCaseData (unsigned int testCaseId)
Definition at line 73 of file YoloDatabase.cpp.
References ARMNN_LOG, CHECK_LOCATION, GetImageDataInArmNnLayoutAsNormalizedFloats(), armnn::numeric_cast(), InferenceTestImage::Resize(), Rgb, Exception::what(), YoloImageHeight, and YoloImageWidth.
 {
     testCaseId = testCaseId % armnn::numeric_cast<unsigned int>(g_PerTestCaseInputOutput.size());
     const auto& testCaseInputOutput = g_PerTestCaseInputOutput[testCaseId];
     const std::string imagePath = m_ImageDir + testCaseInputOutput.first;
     // Loads test case input image.
     std::vector<float> imageData;
     try
     {
         InferenceTestImage image(imagePath.c_str());
         if (YoloImageWidth != image.GetWidth() || YoloImageHeight != image.GetHeight())
         {
             image.Resize(YoloImageWidth, YoloImageHeight, CHECK_LOCATION());
         }
         imageData = GetImageDataInArmNnLayoutAsNormalizedFloats(ImageChannelLayout::Rgb, image);
     }
     catch (const InferenceTestImageException& e)
     {
         ARMNN_LOG(fatal) << "Failed to load test case " << testCaseId << " with error: " << e.what();
         return nullptr;
     }
     // Prepares test case output.
     std::vector<YoloDetectedObject> topObjectDetections;
     topObjectDetections.reserve(1);
     topObjectDetections.push_back(testCaseInputOutput.second);
     return std::make_unique<YoloTestCaseData>(std::move(imageData), std::move(topObjectDetections));
 }
The documentation for this class was generated from the following files:
tests/YoloDatabase.hpp
tests/YoloDatabase.cpp