ArmNN: QuantizationDataSet Class Reference
QuantizationDataSet Class Reference
QuantizationDataSet is a structure which is created after parsing a quantization CSV file.
#include <QuantizationDataSet.hpp>
Public Types
using iterator = QuantizationInputs::iterator
using const_iterator = QuantizationInputs::const_iterator
Public Member Functions
QuantizationDataSet ()
QuantizationDataSet (std::string csvFilePath)
~QuantizationDataSet ()
bool IsEmpty () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Detailed Description
QuantizationDataSet is a structure which is created after parsing a quantization CSV file.
It contains records of filenames which contain refinement data per pass ID for binding ID.
Definition at line 18 of file QuantizationDataSet.hpp.
Member Typedef Documentation
const_iterator
using const_iterator = QuantizationInputs::const_iterator
Definition at line 24 of file QuantizationDataSet.hpp.
iterator
using iterator = QuantizationInputs::iterator
Definition at line 23 of file QuantizationDataSet.hpp.
Constructor & Destructor Documentation
QuantizationDataSet() [1/2]
QuantizationDataSet ()
Definition at line 17 of file QuantizationDataSet.cpp.
 {
 }
QuantizationDataSet() [2/2]
QuantizationDataSet (std::string csvFilePath)
Definition at line 21 of file QuantizationDataSet.cpp.
                                                                    :
     m_QuantizationInputs(),
     m_CsvFilePath(csvFilePath)
 {
     ParseCsvFile();
 }
~QuantizationDataSet()
~QuantizationDataSet ()
Definition at line 46 of file QuantizationDataSet.cpp.
 {
 }
Member Function Documentation
begin() [1/2]
iterator begin () inline
Definition at line 31 of file QuantizationDataSet.hpp.
 { return m_QuantizationInputs.begin(); }
begin() [2/2]
const_iterator begin () const inline
Definition at line 33 of file QuantizationDataSet.hpp.
 { return m_QuantizationInputs.begin(); }
cbegin()
const_iterator cbegin () const inline
Definition at line 35 of file QuantizationDataSet.hpp.
 { return m_QuantizationInputs.cbegin(); }
cend()
const_iterator cend () const inline
Definition at line 36 of file QuantizationDataSet.hpp.
 { return m_QuantizationInputs.cend(); }
end() [1/2]
iterator end () inline
Definition at line 32 of file QuantizationDataSet.hpp.
 { return m_QuantizationInputs.end(); }
end() [2/2]
const_iterator end () const inline
Definition at line 34 of file QuantizationDataSet.hpp.
 { return m_QuantizationInputs.end(); }
IsEmpty()
bool IsEmpty () const inline
Definition at line 29 of file QuantizationDataSet.hpp.
Referenced by BOOST_FIXTURE_TEST_CASE(), CommandLineProcessor::HasQuantizationData(), and main().
 {return m_QuantizationInputs.empty();}
The documentation for this class was generated from the following files:
src/armnnQuantizer/QuantizationDataSet.hpp
src/armnnQuantizer/QuantizationDataSet.cpp