ArmNN: StringifyLayerParameters< Pooling2dDescriptor > Struct Template Reference
StringifyLayerParameters< Pooling2dDescriptor > Struct Template Reference
#include <SerializeLayerParameters.hpp>
Static Public Member Functions
static void Serialize (ParameterStringifyFunction &fn, const Pooling2dDescriptor &desc)
Detailed Description
template<>
struct armnn::StringifyLayerParameters< Pooling2dDescriptor >
Definition at line 58 of file SerializeLayerParameters.hpp.
Member Function Documentation
Serialize()
void Serialize (ParameterStringifyFunction & fn, const Pooling2dDescriptor & desc) static
Definition at line 110 of file SerializeLayerParameters.cpp.
References armnn::GetDataLayoutName(), armnn::GetOutputShapeRoundingAsCString(), armnn::GetPaddingMethodAsCString(), armnn::GetPoolingAlgorithmAsCString(), Pooling2dDescriptor::m_DataLayout, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, and Pooling2dDescriptor::m_StrideY.
 {
     fn("Type", GetPoolingAlgorithmAsCString(desc.m_PoolType));
     {
         std::stringstream ss;
         ss << "(" << desc.m_PadTop    << "," << desc.m_PadLeft
            << "," << desc.m_PadBottom << "," << desc.m_PadRight << ")";
         fn("Padding(T,L,B,R)", ss.str());
     }
     {
         std::stringstream ss;
         ss << "(" << desc.m_PoolWidth    << "," << desc.m_PoolHeight << ")";
         fn("(Width,Height)", ss.str());
     }
     {
         std::stringstream ss;
         ss << "(" << desc.m_StrideX <<  "," << desc.m_StrideY << ")";
         fn("Stride(X,Y)", ss.str());
     }
     fn("OutputShapeRounding", GetOutputShapeRoundingAsCString(desc.m_OutputShapeRounding));
     fn("PaddingMethod", GetPaddingMethodAsCString(desc.m_PaddingMethod));
     fn("DataLayout", GetDataLayoutName(desc.m_DataLayout));
 }
The documentation for this struct was generated from the following files:
src/armnn/SerializeLayerParameters.hpp
src/armnn/SerializeLayerParameters.cpp