ArmNN: QuantizedLstmInputParams Struct Reference
QuantizedLstmInputParams Struct Reference
#include <QuantizedLstmParams.hpp>
Public Member Functions
QuantizedLstmInputParams ()
const ConstTensor & Deref (const ConstTensor *tensorPtr) const
const ConstTensor & GetInputToInputWeights () const
const ConstTensor & GetInputToForgetWeights () const
const ConstTensor & GetInputToCellWeights () const
const ConstTensor & GetInputToOutputWeights () const
const ConstTensor & GetRecurrentToInputWeights () const
const ConstTensor & GetRecurrentToForgetWeights () const
const ConstTensor & GetRecurrentToCellWeights () const
const ConstTensor & GetRecurrentToOutputWeights () const
const ConstTensor & GetInputGateBias () const
const ConstTensor & GetForgetGateBias () const
const ConstTensor & GetCellBias () const
const ConstTensor & GetOutputGateBias () const
Public Attributes
const ConstTensor * m_InputToInputWeights
const ConstTensor * m_InputToForgetWeights
const ConstTensor * m_InputToCellWeights
const ConstTensor * m_InputToOutputWeights
const ConstTensor * m_RecurrentToInputWeights
const ConstTensor * m_RecurrentToForgetWeights
const ConstTensor * m_RecurrentToCellWeights
const ConstTensor * m_RecurrentToOutputWeights
const ConstTensor * m_InputGateBias
const ConstTensor * m_ForgetGateBias
const ConstTensor * m_CellBias
const ConstTensor * m_OutputGateBias
Detailed Description
Definition at line 13 of file QuantizedLstmParams.hpp.
Constructor & Destructor Documentation
QuantizedLstmInputParams()
QuantizedLstmInputParams () inline
Definition at line 15 of file QuantizedLstmParams.hpp.
         : m_InputToInputWeights(nullptr)
         , m_InputToForgetWeights(nullptr)
         , m_InputToCellWeights(nullptr)
         , m_InputToOutputWeights(nullptr)
         , m_RecurrentToInputWeights(nullptr)
         , m_RecurrentToForgetWeights(nullptr)
         , m_RecurrentToCellWeights(nullptr)
         , m_RecurrentToOutputWeights(nullptr)
         , m_InputGateBias(nullptr)
         , m_ForgetGateBias(nullptr)
         , m_CellBias(nullptr)
         , m_OutputGateBias(nullptr)
     {
     }
Member Function Documentation
Deref()
const ConstTensor& Deref (const ConstTensor * tensorPtr) const inline
Definition at line 48 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmInputParams::GetCellBias(), QuantizedLstmInputParamsInfo::GetCellBias(), QuantizedLstmInputParams::GetForgetGateBias(), QuantizedLstmInputParamsInfo::GetForgetGateBias(), QuantizedLstmInputParams::GetInputGateBias(), QuantizedLstmInputParamsInfo::GetInputGateBias(), QuantizedLstmInputParams::GetInputToCellWeights(), QuantizedLstmInputParamsInfo::GetInputToCellWeights(), QuantizedLstmInputParams::GetInputToForgetWeights(), QuantizedLstmInputParamsInfo::GetInputToForgetWeights(), QuantizedLstmInputParams::GetInputToInputWeights(), QuantizedLstmInputParamsInfo::GetInputToInputWeights(), QuantizedLstmInputParams::GetInputToOutputWeights(), QuantizedLstmInputParamsInfo::GetInputToOutputWeights(), QuantizedLstmInputParams::GetOutputGateBias(), QuantizedLstmInputParamsInfo::GetOutputGateBias(), QuantizedLstmInputParams::GetRecurrentToCellWeights(), QuantizedLstmInputParamsInfo::GetRecurrentToCellWeights(), QuantizedLstmInputParams::GetRecurrentToForgetWeights(), QuantizedLstmInputParamsInfo::GetRecurrentToForgetWeights(), QuantizedLstmInputParams::GetRecurrentToInputWeights(), QuantizedLstmInputParamsInfo::GetRecurrentToInputWeights(), QuantizedLstmInputParams::GetRecurrentToOutputWeights(), and QuantizedLstmInputParamsInfo::GetRecurrentToOutputWeights().
     {
         if (tensorPtr != nullptr)
         {
             const ConstTensor &temp = *tensorPtr;
             return temp;
         }
         throw InvalidArgumentException("QuantizedLstmInputParams: Can't dereference a null pointer");
     }
GetCellBias()
const ConstTensor& GetCellBias () const inline
Definition at line 108 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_CellBias);
     }
GetForgetGateBias()
const ConstTensor& GetForgetGateBias () const inline
Definition at line 103 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_ForgetGateBias);
     }
GetInputGateBias()
const ConstTensor& GetInputGateBias () const inline
Definition at line 98 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_InputGateBias);
     }
GetInputToCellWeights()
const ConstTensor& GetInputToCellWeights () const inline
Definition at line 68 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_InputToCellWeights);
     }
GetInputToForgetWeights()
const ConstTensor& GetInputToForgetWeights () const inline
Definition at line 63 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_InputToForgetWeights);
     }
GetInputToInputWeights()
const ConstTensor& GetInputToInputWeights () const inline
Definition at line 58 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_InputToInputWeights);
     }
GetInputToOutputWeights()
const ConstTensor& GetInputToOutputWeights () const inline
Definition at line 73 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_InputToOutputWeights);
     }
GetOutputGateBias()
const ConstTensor& GetOutputGateBias () const inline
Definition at line 113 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_OutputGateBias);
     }
GetRecurrentToCellWeights()
const ConstTensor& GetRecurrentToCellWeights () const inline
Definition at line 88 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_RecurrentToCellWeights);
     }
GetRecurrentToForgetWeights()
const ConstTensor& GetRecurrentToForgetWeights () const inline
Definition at line 83 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_RecurrentToForgetWeights);
     }
GetRecurrentToInputWeights()
const ConstTensor& GetRecurrentToInputWeights () const inline
Definition at line 78 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_RecurrentToInputWeights);
     }
GetRecurrentToOutputWeights()
const ConstTensor& GetRecurrentToOutputWeights () const inline
Definition at line 93 of file QuantizedLstmParams.hpp.
References QuantizedLstmInputParams::Deref().
Referenced by Network::AddQuantizedLstmLayer(), and SerializerVisitor::VisitQuantizedLstmLayer().
     {
         return Deref(m_RecurrentToOutputWeights);
     }
Member Data Documentation
m_CellBias
const ConstTensor* m_CellBias
Definition at line 45 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_ForgetGateBias
const ConstTensor* m_ForgetGateBias
Definition at line 44 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_InputGateBias
const ConstTensor* m_InputGateBias
Definition at line 43 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_InputToCellWeights
const ConstTensor* m_InputToCellWeights
Definition at line 35 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_InputToForgetWeights
const ConstTensor* m_InputToForgetWeights
Definition at line 34 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_InputToInputWeights
const ConstTensor* m_InputToInputWeights
Definition at line 33 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_InputToOutputWeights
const ConstTensor* m_InputToOutputWeights
Definition at line 36 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_OutputGateBias
const ConstTensor* m_OutputGateBias
Definition at line 46 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_RecurrentToCellWeights
const ConstTensor* m_RecurrentToCellWeights
Definition at line 40 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_RecurrentToForgetWeights
const ConstTensor* m_RecurrentToForgetWeights
Definition at line 39 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_RecurrentToInputWeights
const ConstTensor* m_RecurrentToInputWeights
Definition at line 38 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
m_RecurrentToOutputWeights
const ConstTensor* m_RecurrentToOutputWeights
Definition at line 41 of file QuantizedLstmParams.hpp.
Referenced by QuantizedLstmLayer::Accept(), armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), and Deserializer::GetQLstmDescriptor().
The documentation for this struct was generated from the following file:
include/armnn/QuantizedLstmParams.hpp