ArmNN: CheckLocation Struct Reference
CheckLocation Struct Reference
#include <Exceptions.hpp>
Public Member Functions
CheckLocation (const char *func, const char *file, unsigned int line)
std::string AsString () const
std::string FileLine () const
Public Attributes
const char * m_Function
const char * m_File
unsigned int m_Line
Detailed Description
Definition at line 14 of file Exceptions.hpp.
Constructor & Destructor Documentation
CheckLocation()
CheckLocation (const char * func, const char * file, unsigned int line) inline
Definition at line 20 of file Exceptions.hpp.
     : m_Function{func}
     , m_File{file}
     , m_Line{line}
     {
     }
Member Function Documentation
AsString()
std::string AsString () const inline
Definition at line 29 of file Exceptions.hpp.
Referenced by armnnUtils::CheckValidSize(), armnnUtils::NonNegative(), InferenceTestImage::Resize(), armnnDeserializer::ToConstTensor(), armnnDeserializer::ToTensorInfo(), armnnUtils::VerifyInt32(), and Layer::VerifyLayerConnections().
     {
         std::stringstream ss;
         ss << " at function " << m_Function
            << " [" << m_File << ':' << m_Line << "]";
         return ss.str();
     }
FileLine()
std::string FileLine () const inline
Definition at line 37 of file Exceptions.hpp.
     {
         std::stringstream ss;
         ss << " [" << m_File << ':' << m_Line << "]";
         return ss.str();
     }
Member Data Documentation
m_File
const char* m_File
Definition at line 17 of file Exceptions.hpp.
m_Function
const char* m_Function
Definition at line 16 of file Exceptions.hpp.
m_Line
unsigned int m_Line
Definition at line 18 of file Exceptions.hpp.
The documentation for this struct was generated from the following file:
include/armnn/Exceptions.hpp