var searchData=
[
  ['name',['name',['../structarmnn_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.xhtml#ae480e553e8e67cc07388093b9ae0e7ae',1,'armnn::FLATBUFFERS_FINAL_CLASS']]],
  ['namedtempfile',['NamedTempFile',['../namespacearmnn_utils_1_1_filesystem.xhtml#a606d65835d72a332109c3c9f96a01b8a',1,'armnnUtils::Filesystem']]],
  ['nan',['Nan',['../classarmnn_1_1_b_float16.xhtml#ae80b11dd8875fbf6e76cb054764ca6fb',1,'armnn::BFloat16']]],
  ['ncdhw',['NCDHW',['../namespacearmnn.xhtml#ad1d5cce2d9e9a5d61c243e5c989112e0a884e0167ebf9bbe6cfd6ca5ab97ab015',1,'armnn']]],
  ['nchw',['NCHW',['../namespacearmnn.xhtml#ad1d5cce2d9e9a5d61c243e5c989112e0a6b99f356fe3b30a2a850b5ea897c289f',1,'armnn']]],
  ['ndhwc',['NDHWC',['../namespacearmnn.xhtml#ad1d5cce2d9e9a5d61c243e5c989112e0a4dd0194b114cbf51da5b3a72569863ef',1,'armnn']]],
  ['nearestneighbor',['NearestNeighbor',['../namespacearmnn.xhtml#a9a2af2f8c4af4f9efa8e79417d505ac4aaa020331bb30d2fa2ecf7c3a0777823f',1,'armnn']]],
  ['neg',['Neg',['../namespacearmnn.xhtml#a1cfaa710db2a54673b21d2ea2da757c8afb278fa5defd7e699fcbc930c3e76ccd',1,'armnn']]],
  ['neonabsworkload',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.xhtml',1,'NeonAbsWorkload'],['../classarmnn_1_1_neon_abs_workload.xhtml#a96f0d11c757b397d025bb98ab950946e',1,'armnn::NeonAbsWorkload::NeonAbsWorkload()']]],
  ['neonabsworkload_2ecpp',['NeonAbsWorkload.cpp',['../_neon_abs_workload_8cpp.xhtml',1,'']]],
  ['neonabsworkload_2ehpp',['NeonAbsWorkload.hpp',['../_neon_abs_workload_8hpp.xhtml',1,'']]],
  ['neonabsworkloadvalidate',['NeonAbsWorkloadValidate',['../namespacearmnn.xhtml#afc773aec6f845adc0cc547ce475dfe3f',1,'armnn']]],
  ['neonactivationworkload',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.xhtml',1,'NeonActivationWorkload'],['../classarmnn_1_1_neon_activation_workload.xhtml#a375b7b712d4d2aaa6a5d9edfe8cafb51',1,'armnn::NeonActivationWorkload::NeonActivationWorkload()']]],
  ['neonactivationworkload_2ecpp',['NeonActivationWorkload.cpp',['../_neon_activation_workload_8cpp.xhtml',1,'']]],
  ['neonactivationworkload_2ehpp',['NeonActivationWorkload.hpp',['../_neon_activation_workload_8hpp.xhtml',1,'']]],
  ['neonactivationworkloadvalidate',['NeonActivationWorkloadValidate',['../namespacearmnn.xhtml#a46495807633a01d826851e1cb498f071',1,'armnn']]],
  ['neonadditionworkload',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.xhtml',1,'NeonAdditionWorkload'],['../classarmnn_1_1_neon_addition_workload.xhtml#ad77ac4545d497dd50a88f7857966993b',1,'armnn::NeonAdditionWorkload::NeonAdditionWorkload()']]],
  ['neonadditionworkload_2ecpp',['NeonAdditionWorkload.cpp',['../_neon_addition_workload_8cpp.xhtml',1,'']]],
  ['neonadditionworkload_2ehpp',['NeonAdditionWorkload.hpp',['../_neon_addition_workload_8hpp.xhtml',1,'']]],
  ['neonadditionworkloadvalidate',['NeonAdditionWorkloadValidate',['../namespacearmnn.xhtml#a1b03e82a1a53b686aedea3734b2fb957',1,'armnn']]],
  ['neonargminmaxworkload',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.xhtml',1,'NeonArgMinMaxWorkload'],['../classarmnn_1_1_neon_arg_min_max_workload.xhtml#ae0b677bd8fd4afded95b50b9b28d187c',1,'armnn::NeonArgMinMaxWorkload::NeonArgMinMaxWorkload()']]],
  ['neonargminmaxworkload_2ecpp',['NeonArgMinMaxWorkload.cpp',['../_neon_arg_min_max_workload_8cpp.xhtml',1,'']]],
  ['neonargminmaxworkload_2ehpp',['NeonArgMinMaxWorkload.hpp',['../_neon_arg_min_max_workload_8hpp.xhtml',1,'']]],
  ['neonargminmaxworkloadvalidate',['NeonArgMinMaxWorkloadValidate',['../namespacearmnn.xhtml#a61d1f39297fec6e3062e4047dc5f236e',1,'armnn']]],
  ['neonbackend',['NeonBackend',['../classarmnn_1_1_neon_backend.xhtml',1,'NeonBackend'],['../classarmnn_1_1_neon_backend.xhtml#a1d64639ac88622afa0d86f7943f39d99',1,'armnn::NeonBackend::NeonBackend()']]],
  ['neonbackend_2ecpp',['NeonBackend.cpp',['../_neon_backend_8cpp.xhtml',1,'']]],
  ['neonbackend_2ehpp',['NeonBackend.hpp',['../_neon_backend_8hpp.xhtml',1,'']]],
  ['neonbackendid',['NeonBackendId',['../namespacearmnn.xhtml#a3a34a305e5187f3a3c67030d3bebbdb0',1,'armnn']]],
  ['neonbackendid_2ehpp',['NeonBackendId.hpp',['../_neon_backend_id_8hpp.xhtml',1,'']]],
  ['neonbackendmodelcontext',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.xhtml',1,'NeonBackendModelContext'],['../classarmnn_1_1_neon_backend_model_context.xhtml#ad294d1b0a3cacd966314a512d96f46fb',1,'armnn::NeonBackendModelContext::NeonBackendModelContext()']]],
  ['neonbackendmodelcontext_2ecpp',['NeonBackendModelContext.cpp',['../_neon_backend_model_context_8cpp.xhtml',1,'']]],
  ['neonbackendmodelcontext_2ehpp',['NeonBackendModelContext.hpp',['../_neon_backend_model_context_8hpp.xhtml',1,'']]],
  ['neonbaseworkload',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.xhtml',1,'NeonBaseWorkload&lt; QueueDescriptor &gt;'],['../classarmnn_1_1_neon_base_workload.xhtml#a446042983b3fa49c4c57f2262ef3a2f0',1,'armnn::NeonBaseWorkload::NeonBaseWorkload()']]],
  ['neonbaseworkload_2ehpp',['NeonBaseWorkload.hpp',['../_neon_base_workload_8hpp.xhtml',1,'']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbatchmatmulvalidate',['NeonBatchMatMulValidate',['../namespacearmnn.xhtml#abc5405fc939efb69e2d630421f0d4271',1,'armnn']]],
  ['neonbatchmatmulworkload',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.xhtml',1,'NeonBatchMatMulWorkload'],['../classarmnn_1_1_neon_batch_mat_mul_workload.xhtml#a2eed4c19f5918cfa8efd910e6195c99c',1,'armnn::NeonBatchMatMulWorkload::NeonBatchMatMulWorkload()']]],
  ['neonbatchmatmulworkload_2ecpp',['NeonBatchMatMulWorkload.cpp',['../_neon_batch_mat_mul_workload_8cpp.xhtml',1,'']]],
  ['neonbatchmatmulworkload_2ehpp',['NeonBatchMatMulWorkload.hpp',['../_neon_batch_mat_mul_workload_8hpp.xhtml',1,'']]],
  ['neonbatchnormalizationvalidate',['NeonBatchNormalizationValidate',['../namespacearmnn.xhtml#ac1be1c9a317b23b5684c83af59fb2c96',1,'armnn']]],
  ['neonbatchnormalizationworkload',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.xhtml',1,'NeonBatchNormalizationWorkload'],['../classarmnn_1_1_neon_batch_normalization_workload.xhtml#a8044a4d50d30c30e405ab785946bef12',1,'armnn::NeonBatchNormalizationWorkload::NeonBatchNormalizationWorkload()']]],
  ['neonbatchnormalizationworkload_2ecpp',['NeonBatchNormalizationWorkload.cpp',['../_neon_batch_normalization_workload_8cpp.xhtml',1,'']]],
  ['neonbatchnormalizationworkload_2ehpp',['NeonBatchNormalizationWorkload.hpp',['../_neon_batch_normalization_workload_8hpp.xhtml',1,'']]],
  ['neonbatchtospacendworkload',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.xhtml',1,'NeonBatchToSpaceNdWorkload'],['../classarmnn_1_1_neon_batch_to_space_nd_workload.xhtml#a1011c98cd37ecc95fa04bd9005a6548c',1,'armnn::NeonBatchToSpaceNdWorkload::NeonBatchToSpaceNdWorkload()']]],
  ['neonbatchtospacendworkload_2ecpp',['NeonBatchToSpaceNdWorkload.cpp',['../_neon_batch_to_space_nd_workload_8cpp.xhtml',1,'']]],
  ['neonbatchtospacendworkload_2ehpp',['NeonBatchToSpaceNdWorkload.hpp',['../_neon_batch_to_space_nd_workload_8hpp.xhtml',1,'']]],
  ['neonbatchtospacendworkloadvalidate',['NeonBatchToSpaceNdWorkloadValidate',['../namespacearmnn.xhtml#aad5f7f0fcd2dbb0aad7016ff984e7cc6',1,'armnn']]],
  ['neoncastvalidate',['NeonCastValidate',['../namespacearmnn.xhtml#a3ab69cec1cab301e096a2830f65a36ec',1,'armnn']]],
  ['neoncastworkload',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.xhtml',1,'NeonCastWorkload'],['../classarmnn_1_1_neon_cast_workload.xhtml#adeba18fb879a362620d65a07fe0cd063',1,'armnn::NeonCastWorkload::NeonCastWorkload()']]],
  ['neoncastworkload_2ecpp',['NeonCastWorkload.cpp',['../_neon_cast_workload_8cpp.xhtml',1,'']]],
  ['neoncastworkload_2ehpp',['NeonCastWorkload.hpp',['../_neon_cast_workload_8hpp.xhtml',1,'']]],
  ['neonchannelshufflevalidate',['NeonChannelShuffleValidate',['../namespacearmnn.xhtml#a2ee21869ffad00d6344afffb0a9baba1',1,'armnn']]],
  ['neonchannelshuffleworkload',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.xhtml',1,'NeonChannelShuffleWorkload'],['../classarmnn_1_1_neon_channel_shuffle_workload.xhtml#adcfc07d5002b8f83fd66678fbac75204',1,'armnn::NeonChannelShuffleWorkload::NeonChannelShuffleWorkload()']]],
  ['neonchannelshuffleworkload_2ecpp',['NeonChannelShuffleWorkload.cpp',['../_neon_channel_shuffle_workload_8cpp.xhtml',1,'']]],
  ['neonchannelshuffleworkload_2ehpp',['NeonChannelShuffleWorkload.hpp',['../_neon_channel_shuffle_workload_8hpp.xhtml',1,'']]],
  ['neoncomparisonworkload',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.xhtml',1,'NeonComparisonWorkload'],['../classarmnn_1_1_neon_comparison_workload.xhtml#adcae1537853ec29e0b8b1e231cf1c765',1,'armnn::NeonComparisonWorkload::NeonComparisonWorkload()']]],
  ['neoncomparisonworkload_2ecpp',['NeonComparisonWorkload.cpp',['../_neon_comparison_workload_8cpp.xhtml',1,'']]],
  ['neoncomparisonworkload_2ehpp',['NeonComparisonWorkload.hpp',['../_neon_comparison_workload_8hpp.xhtml',1,'']]],
  ['neoncomparisonworkloadvalidate',['NeonComparisonWorkloadValidate',['../namespacearmnn.xhtml#ae412e8e64d6a6dde3ace908b59c29c06',1,'armnn']]],
  ['neonconcatworkload',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.xhtml',1,'NeonConcatWorkload'],['../classarmnn_1_1_neon_concat_workload.xhtml#a9e2f12901f4165674c424597ea597ec8',1,'armnn::NeonConcatWorkload::NeonConcatWorkload()']]],
  ['neonconcatworkload_2ecpp',['NeonConcatWorkload.cpp',['../_neon_concat_workload_8cpp.xhtml',1,'']]],
  ['neonconcatworkload_2ehpp',['NeonConcatWorkload.hpp',['../_neon_concat_workload_8hpp.xhtml',1,'']]],
  ['neonconcatworkloadvalidate',['NeonConcatWorkloadValidate',['../namespacearmnn.xhtml#a8a219633e750d6daffcef3b641fa11f3',1,'armnn']]],
  ['neonconstantworkload',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.xhtml',1,'NeonConstantWorkload'],['../classarmnn_1_1_neon_constant_workload.xhtml#a104b2d6e3d37d807cd758d2111922ac2',1,'armnn::NeonConstantWorkload::NeonConstantWorkload()']]],
  ['neonconstantworkload_2ecpp',['NeonConstantWorkload.cpp',['../_neon_constant_workload_8cpp.xhtml',1,'']]],
  ['neonconstantworkload_2ehpp',['NeonConstantWorkload.hpp',['../_neon_constant_workload_8hpp.xhtml',1,'']]],
  ['neonconstantworkloadvalidate',['NeonConstantWorkloadValidate',['../namespacearmnn.xhtml#afb681fd9b8afe0b236d51b6c868ae660',1,'armnn']]],
  ['neonconvertfp16tofp32workload',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.xhtml',1,'NeonConvertFp16ToFp32Workload'],['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.xhtml#a9f374c3ca4d79ded86921bf82ead0da5',1,'armnn::NeonConvertFp16ToFp32Workload::NeonConvertFp16ToFp32Workload()']]],
  ['neonconvertfp16tofp32workload_2ecpp',['NeonConvertFp16ToFp32Workload.cpp',['../_neon_convert_fp16_to_fp32_workload_8cpp.xhtml',1,'']]],
  ['neonconvertfp16tofp32workload_2ehpp',['NeonConvertFp16ToFp32Workload.hpp',['../_neon_convert_fp16_to_fp32_workload_8hpp.xhtml',1,'']]],
  ['neonconvertfp32tofp16workload',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.xhtml',1,'NeonConvertFp32ToFp16Workload'],['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.xhtml#a074e5e0c6d0901ec2a2a2cba69e5df98',1,'armnn::NeonConvertFp32ToFp16Workload::NeonConvertFp32ToFp16Workload()']]],
  ['neonconvertfp32tofp16workload_2ecpp',['NeonConvertFp32ToFp16Workload.cpp',['../_neon_convert_fp32_to_fp16_workload_8cpp.xhtml',1,'']]],
  ['neonconvertfp32tofp16workload_2ehpp',['NeonConvertFp32ToFp16Workload.hpp',['../_neon_convert_fp32_to_fp16_workload_8hpp.xhtml',1,'']]],
  ['neonconvolution2dworkload',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.xhtml',1,'NeonConvolution2dWorkload'],['../classarmnn_1_1_neon_convolution2d_workload.xhtml#ad8b152d87bee8fc25b37cfe562c29ea8',1,'armnn::NeonConvolution2dWorkload::NeonConvolution2dWorkload()']]],
  ['neonconvolution2dworkload_2ecpp',['NeonConvolution2dWorkload.cpp',['../_neon_convolution2d_workload_8cpp.xhtml',1,'']]],
  ['neonconvolution2dworkload_2ehpp',['NeonConvolution2dWorkload.hpp',['../_neon_convolution2d_workload_8hpp.xhtml',1,'']]],
  ['neonconvolution2dworkloadvalidate',['NeonConvolution2dWorkloadValidate',['../namespacearmnn.xhtml#a45691b0c4a46c239b4986cfed95de13b',1,'armnn']]],
  ['neonconvolution3dworkload',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.xhtml',1,'NeonConvolution3dWorkload'],['../classarmnn_1_1_neon_convolution3d_workload.xhtml#ab51509d151f08aecbe91d50e5fb16764',1,'armnn::NeonConvolution3dWorkload::NeonConvolution3dWorkload()']]],
  ['neonconvolution3dworkload_2ecpp',['NeonConvolution3dWorkload.cpp',['../_neon_convolution3d_workload_8cpp.xhtml',1,'']]],
  ['neonconvolution3dworkload_2ehpp',['NeonConvolution3dWorkload.hpp',['../_neon_convolution3d_workload_8hpp.xhtml',1,'']]],
  ['neonconvolution3dworkloadvalidate',['NeonConvolution3dWorkloadValidate',['../namespacearmnn.xhtml#acbb4d7b86eb01bb437230e1586b9aeb4',1,'armnn']]],
  ['neondepthtospaceworkload',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.xhtml',1,'NeonDepthToSpaceWorkload'],['../classarmnn_1_1_neon_depth_to_space_workload.xhtml#a883228e0b87a75f3e50bbaacb8d328cf',1,'armnn::NeonDepthToSpaceWorkload::NeonDepthToSpaceWorkload()']]],
  ['neondepthtospaceworkload_2ecpp',['NeonDepthToSpaceWorkload.cpp',['../_neon_depth_to_space_workload_8cpp.xhtml',1,'']]],
  ['neondepthtospaceworkload_2ehpp',['NeonDepthToSpaceWorkload.hpp',['../_neon_depth_to_space_workload_8hpp.xhtml',1,'']]],
  ['neondepthtospaceworkloadvalidate',['NeonDepthToSpaceWorkloadValidate',['../namespacearmnn.xhtml#a116d88067bf98ce9858ab73e68f605f9',1,'armnn']]],
  ['neondepthwiseconvolutionworkload',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.xhtml',1,'NeonDepthwiseConvolutionWorkload'],['../classarmnn_1_1_neon_depthwise_convolution_workload.xhtml#aa6173c66256d333ee73a068206c746d6',1,'armnn::NeonDepthwiseConvolutionWorkload::NeonDepthwiseConvolutionWorkload()']]],
  ['neondepthwiseconvolutionworkload_2ecpp',['NeonDepthwiseConvolutionWorkload.cpp',['../_neon_depthwise_convolution_workload_8cpp.xhtml',1,'']]],
  ['neondepthwiseconvolutionworkload_2ehpp',['NeonDepthwiseConvolutionWorkload.hpp',['../_neon_depthwise_convolution_workload_8hpp.xhtml',1,'']]],
  ['neondepthwiseconvolutionworkloadvalidate',['NeonDepthwiseConvolutionWorkloadValidate',['../namespacearmnn.xhtml#a63d684b26fb838b22123490d780bce08',1,'armnn']]],
  ['neondequantizeworkload',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.xhtml',1,'NeonDequantizeWorkload'],['../classarmnn_1_1_neon_dequantize_workload.xhtml#a5a5bbcb5d952afc490e3ec32f95f36c4',1,'armnn::NeonDequantizeWorkload::NeonDequantizeWorkload()']]],
  ['neondequantizeworkload_2ecpp',['NeonDequantizeWorkload.cpp',['../_neon_dequantize_workload_8cpp.xhtml',1,'']]],
  ['neondequantizeworkload_2ehpp',['NeonDequantizeWorkload.hpp',['../_neon_dequantize_workload_8hpp.xhtml',1,'']]],
  ['neondequantizeworkloadvalidate',['NeonDequantizeWorkloadValidate',['../namespacearmnn.xhtml#acefede7cc57c71ea4cfe1c888bb413e0',1,'armnn']]],
  ['neondetected',['NeonDetected',['../namespacearmnn.xhtml#ad734960f7ae60a86b74f6722f6c14332',1,'armnn']]],
  ['neondetectionpostprocessvalidate',['NeonDetectionPostProcessValidate',['../namespacearmnn.xhtml#ab816c37fc6a6243badf4f7a3d0c88d46',1,'armnn']]],
  ['neondetectionpostprocessworkload',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.xhtml',1,'NeonDetectionPostProcessWorkload'],['../classarmnn_1_1_neon_detection_post_process_workload.xhtml#a2561133f68a4f0ab661fc29313386974',1,'armnn::NeonDetectionPostProcessWorkload::NeonDetectionPostProcessWorkload()']]],
  ['neondetectionpostprocessworkload_2ecpp',['NeonDetectionPostProcessWorkload.cpp',['../_neon_detection_post_process_workload_8cpp.xhtml',1,'']]],
  ['neondetectionpostprocessworkload_2ehpp',['NeonDetectionPostProcessWorkload.hpp',['../_neon_detection_post_process_workload_8hpp.xhtml',1,'']]],
  ['neondivisionworkload',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.xhtml',1,'NeonDivisionWorkload'],['../classarmnn_1_1_neon_division_workload.xhtml#aad5ee66ecd7dd43b7208e903022be860',1,'armnn::NeonDivisionWorkload::NeonDivisionWorkload()']]],
  ['neondivisionworkload_2ecpp',['NeonDivisionWorkload.cpp',['../_neon_division_workload_8cpp.xhtml',1,'']]],
  ['neondivisionworkload_2ehpp',['NeonDivisionWorkload.hpp',['../_neon_division_workload_8hpp.xhtml',1,'']]],
  ['neondivisionworkloadvalidate',['NeonDivisionWorkloadValidate',['../namespacearmnn.xhtml#a65c912bfcf02b3096f36caf21fa175d0',1,'armnn']]],
  ['neonexpworkload',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.xhtml',1,'NeonExpWorkload'],['../classarmnn_1_1_neon_exp_workload.xhtml#ac20961b446a9f626d556eb03ed564c35',1,'armnn::NeonExpWorkload::NeonExpWorkload()']]],
  ['neonexpworkload_2ecpp',['NeonExpWorkload.cpp',['../_neon_exp_workload_8cpp.xhtml',1,'']]],
  ['neonexpworkload_2ehpp',['NeonExpWorkload.hpp',['../_neon_exp_workload_8hpp.xhtml',1,'']]],
  ['neonexpworkloadvalidate',['NeonExpWorkloadValidate',['../namespacearmnn.xhtml#aec5669eb9285cbca1ee6c7e1dd7bcf6a',1,'armnn']]],
  ['neonfillworkload',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.xhtml',1,'NeonFillWorkload'],['../classarmnn_1_1_neon_fill_workload.xhtml#ae2e092f913815f30684f46872118719e',1,'armnn::NeonFillWorkload::NeonFillWorkload()']]],
  ['neonfillworkload_2ecpp',['NeonFillWorkload.cpp',['../_neon_fill_workload_8cpp.xhtml',1,'']]],
  ['neonfillworkload_2ehpp',['NeonFillWorkload.hpp',['../_neon_fill_workload_8hpp.xhtml',1,'']]],
  ['neonfloorfloatworkload',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.xhtml',1,'NeonFloorFloatWorkload'],['../classarmnn_1_1_neon_floor_float_workload.xhtml#a4c3deee68fd34bace44cc58e953d9ab1',1,'armnn::NeonFloorFloatWorkload::NeonFloorFloatWorkload()']]],
  ['neonfloorfloatworkload_2ecpp',['NeonFloorFloatWorkload.cpp',['../_neon_floor_float_workload_8cpp.xhtml',1,'']]],
  ['neonfloorfloatworkload_2ehpp',['NeonFloorFloatWorkload.hpp',['../_neon_floor_float_workload_8hpp.xhtml',1,'']]],
  ['neonfullyconnectedworkload',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.xhtml',1,'NeonFullyConnectedWorkload'],['../classarmnn_1_1_neon_fully_connected_workload.xhtml#addd5ca5793cf188ba62c9f73f378e014',1,'armnn::NeonFullyConnectedWorkload::NeonFullyConnectedWorkload()']]],
  ['neonfullyconnectedworkload_2ecpp',['NeonFullyConnectedWorkload.cpp',['../_neon_fully_connected_workload_8cpp.xhtml',1,'']]],
  ['neonfullyconnectedworkload_2ehpp',['NeonFullyConnectedWorkload.hpp',['../_neon_fully_connected_workload_8hpp.xhtml',1,'']]],
  ['neonfullyconnectedworkloadvalidate',['NeonFullyConnectedWorkloadValidate',['../namespacearmnn.xhtml#ae455144d3472c502b636697f4775400c',1,'armnn']]],
  ['neongatherndworkload',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.xhtml',1,'NeonGatherNdWorkload'],['../classarmnn_1_1_neon_gather_nd_workload.xhtml#aed7f95d9f00861351b0bd4d7b17e27b2',1,'armnn::NeonGatherNdWorkload::NeonGatherNdWorkload()']]],
  ['neongatherndworkload_2ecpp',['NeonGatherNdWorkload.cpp',['../_neon_gather_nd_workload_8cpp.xhtml',1,'']]],
  ['neongatherndworkload_2ehpp',['NeonGatherNdWorkload.hpp',['../_neon_gather_nd_workload_8hpp.xhtml',1,'']]],
  ['neongatherndworkloadvalidate',['NeonGatherNdWorkloadValidate',['../namespacearmnn.xhtml#aec41b8c86e61ce02a07b8215bf8bc073',1,'armnn']]],
  ['neongatherworkload',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.xhtml',1,'NeonGatherWorkload'],['../classarmnn_1_1_neon_gather_workload.xhtml#a0b0128cc0929c7dd8f89a09e040bb576',1,'armnn::NeonGatherWorkload::NeonGatherWorkload()']]],
  ['neongatherworkload_2ecpp',['NeonGatherWorkload.cpp',['../_neon_gather_workload_8cpp.xhtml',1,'']]],
  ['neongatherworkload_2ehpp',['NeonGatherWorkload.hpp',['../_neon_gather_workload_8hpp.xhtml',1,'']]],
  ['neongatherworkloadvalidate',['NeonGatherWorkloadValidate',['../namespacearmnn.xhtml#a6c354904637149b84767275e6f725741',1,'armnn']]],
  ['neoninstancenormalizationworkload',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.xhtml',1,'NeonInstanceNormalizationWorkload'],['../classarmnn_1_1_neon_instance_normalization_workload.xhtml#a4c5c0092a4eb57743a29fc7f1a403b24',1,'armnn::NeonInstanceNormalizationWorkload::NeonInstanceNormalizationWorkload()']]],
  ['neoninstancenormalizationworkload_2ecpp',['NeonInstanceNormalizationWorkload.cpp',['../_neon_instance_normalization_workload_8cpp.xhtml',1,'']]],
  ['neoninstancenormalizationworkload_2ehpp',['NeonInstanceNormalizationWorkload.hpp',['../_neon_instance_normalization_workload_8hpp.xhtml',1,'']]],
  ['neoninstancenormalizationworkloadvalidate',['NeonInstanceNormalizationWorkloadValidate',['../namespacearmnn.xhtml#aea722abe239545030f4c6fe4e083816f',1,'armnn']]],
  ['neoninterceptorscheduler',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.xhtml',1,'NeonInterceptorScheduler'],['../classarmnn_1_1_neon_interceptor_scheduler.xhtml#a54394a4d67b6c4e7878cdf36ace0b9a8',1,'armnn::NeonInterceptorScheduler::NeonInterceptorScheduler()']]],
  ['neoninterceptorscheduler_2ecpp',['NeonInterceptorScheduler.cpp',['../_neon_interceptor_scheduler_8cpp.xhtml',1,'']]],
  ['neoninterceptorscheduler_2ehpp',['NeonInterceptorScheduler.hpp',['../_neon_interceptor_scheduler_8hpp.xhtml',1,'']]],
  ['neonl2normalizationfloatworkload',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.xhtml',1,'NeonL2NormalizationFloatWorkload'],['../classarmnn_1_1_neon_l2_normalization_float_workload.xhtml#a91ba7d823503e4b193e2dd2e580fc3a4',1,'armnn::NeonL2NormalizationFloatWorkload::NeonL2NormalizationFloatWorkload()']]],
  ['neonl2normalizationfloatworkload_2ecpp',['NeonL2NormalizationFloatWorkload.cpp',['../_neon_l2_normalization_float_workload_8cpp.xhtml',1,'']]],
  ['neonl2normalizationfloatworkload_2ehpp',['NeonL2NormalizationFloatWorkload.hpp',['../_neon_l2_normalization_float_workload_8hpp.xhtml',1,'']]],
  ['neonl2normalizationworkloadvalidate',['NeonL2NormalizationWorkloadValidate',['../namespacearmnn.xhtml#ae838df3960d2b5d18d73ed2a07aee917',1,'armnn']]],
  ['neonlayersupport',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.xhtml',1,'NeonLayerSupport'],['../classarmnn_1_1_neon_layer_support.xhtml#a45ecbb863cc8ef62d09bd7749089e0f8',1,'armnn::NeonLayerSupport::NeonLayerSupport(const IBackendInternal::IBackendSpecificModelContextPtr &amp;modelContextPtr)'],['../classarmnn_1_1_neon_layer_support.xhtml#a0e8bdd2741997b0cdc329cbfcaeebf93',1,'armnn::NeonLayerSupport::NeonLayerSupport()']]],
  ['neonlayersupport_2ecpp',['NeonLayerSupport.cpp',['../_neon_layer_support_8cpp.xhtml',1,'']]],
  ['neonlayersupport_2ehpp',['NeonLayerSupport.hpp',['../_neon_layer_support_8hpp.xhtml',1,'']]],
  ['neonlogicalandworkload',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.xhtml',1,'NeonLogicalAndWorkload'],['../classarmnn_1_1_neon_logical_and_workload.xhtml#aa53344371ecd3c9b58cacfb0565bba8e',1,'armnn::NeonLogicalAndWorkload::NeonLogicalAndWorkload()']]],
  ['neonlogicalandworkload_2ecpp',['NeonLogicalAndWorkload.cpp',['../_neon_logical_and_workload_8cpp.xhtml',1,'']]],
  ['neonlogicalandworkload_2ehpp',['NeonLogicalAndWorkload.hpp',['../_neon_logical_and_workload_8hpp.xhtml',1,'']]],
  ['neonlogicalandworkloadvalidate',['NeonLogicalAndWorkloadValidate',['../namespacearmnn.xhtml#a7832b675e7efeb1315b31067e46ce705',1,'armnn']]],
  ['neonlogicalnotworkload',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.xhtml',1,'NeonLogicalNotWorkload'],['../classarmnn_1_1_neon_logical_not_workload.xhtml#ab1044573be8ca82e421824437e05d084',1,'armnn::NeonLogicalNotWorkload::NeonLogicalNotWorkload()']]],
  ['neonlogicalnotworkload_2ecpp',['NeonLogicalNotWorkload.cpp',['../_neon_logical_not_workload_8cpp.xhtml',1,'']]],
  ['neonlogicalnotworkload_2ehpp',['NeonLogicalNotWorkload.hpp',['../_neon_logical_not_workload_8hpp.xhtml',1,'']]],
  ['neonlogicalnotworkloadvalidate',['NeonLogicalNotWorkloadValidate',['../namespacearmnn.xhtml#af4f8e11ae5715973420a82d841dfa676',1,'armnn']]],
  ['neonlogicalorworkload',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.xhtml',1,'NeonLogicalOrWorkload'],['../classarmnn_1_1_neon_logical_or_workload.xhtml#a4748e5f01190d3898b4af0b401cc3525',1,'armnn::NeonLogicalOrWorkload::NeonLogicalOrWorkload()']]],
  ['neonlogicalorworkload_2ecpp',['NeonLogicalOrWorkload.cpp',['../_neon_logical_or_workload_8cpp.xhtml',1,'']]],
  ['neonlogicalorworkload_2ehpp',['NeonLogicalOrWorkload.hpp',['../_neon_logical_or_workload_8hpp.xhtml',1,'']]],
  ['neonlogicalorworkloadvalidate',['NeonLogicalOrWorkloadValidate',['../namespacearmnn.xhtml#a2de04fd10d0a2419e0a05f12741017dc',1,'armnn']]],
  ['neonlogsoftmaxworkload',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.xhtml',1,'NeonLogSoftmaxWorkload'],['../classarmnn_1_1_neon_log_softmax_workload.xhtml#aef84e71395cb46a70f6c87dbbd952c94',1,'armnn::NeonLogSoftmaxWorkload::NeonLogSoftmaxWorkload()']]],
  ['neonlogsoftmaxworkload_2ecpp',['NeonLogSoftmaxWorkload.cpp',['../_neon_log_softmax_workload_8cpp.xhtml',1,'']]],
  ['neonlogsoftmaxworkload_2ehpp',['NeonLogSoftmaxWorkload.hpp',['../_neon_log_softmax_workload_8hpp.xhtml',1,'']]],
  ['neonlogsoftmaxworkloadvalidate',['NeonLogSoftmaxWorkloadValidate',['../namespacearmnn.xhtml#ac57d1e00cc24022c21aa7ff95eb618ba',1,'armnn']]],
  ['neonlogworkload',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.xhtml',1,'NeonLogWorkload'],['../classarmnn_1_1_neon_log_workload.xhtml#afa3de920aaea6a4bf32d85fbb867c6fb',1,'armnn::NeonLogWorkload::NeonLogWorkload()']]],
  ['neonlogworkload_2ecpp',['NeonLogWorkload.cpp',['../_neon_log_workload_8cpp.xhtml',1,'']]],
  ['neonlogworkload_2ehpp',['NeonLogWorkload.hpp',['../_neon_log_workload_8hpp.xhtml',1,'']]],
  ['neonlogworkloadvalidate',['NeonLogWorkloadValidate',['../namespacearmnn.xhtml#ad1991a3499a991b1fdd71d918f793f13',1,'armnn']]],
  ['neonlstmfloatworkload',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.xhtml',1,'NeonLstmFloatWorkload'],['../classarmnn_1_1_neon_lstm_float_workload.xhtml#a471d876fac9cbcc3347eec34e558fe46',1,'armnn::NeonLstmFloatWorkload::NeonLstmFloatWorkload()']]],
  ['neonlstmfloatworkload_2ecpp',['NeonLstmFloatWorkload.cpp',['../_neon_lstm_float_workload_8cpp.xhtml',1,'']]],
  ['neonlstmfloatworkload_2ehpp',['NeonLstmFloatWorkload.hpp',['../_neon_lstm_float_workload_8hpp.xhtml',1,'']]],
  ['neonlstmfloatworkloadvalidate',['NeonLstmFloatWorkloadValidate',['../namespacearmnn.xhtml#a9e06cc2a2ac8b88fc72972695a17910f',1,'armnn']]],
  ['neonmaximumworkload',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.xhtml',1,'NeonMaximumWorkload'],['../classarmnn_1_1_neon_maximum_workload.xhtml#ad66b23bbca641e44b85a040a6e3f228c',1,'armnn::NeonMaximumWorkload::NeonMaximumWorkload()']]],
  ['neonmaximumworkload_2ecpp',['NeonMaximumWorkload.cpp',['../_neon_maximum_workload_8cpp.xhtml',1,'']]],
  ['neonmaximumworkload_2ehpp',['NeonMaximumWorkload.hpp',['../_neon_maximum_workload_8hpp.xhtml',1,'']]],
  ['neonmaximumworkloadvalidate',['NeonMaximumWorkloadValidate',['../namespacearmnn.xhtml#a8d2ea79addd8ef64be2ca0dad3408f00',1,'armnn']]],
  ['neonmeanworkload',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.xhtml',1,'NeonMeanWorkload'],['../classarmnn_1_1_neon_mean_workload.xhtml#a2e92aaf909295489c0faedb9916339d4',1,'armnn::NeonMeanWorkload::NeonMeanWorkload()']]],
  ['neonmeanworkload_2ecpp',['NeonMeanWorkload.cpp',['../_neon_mean_workload_8cpp.xhtml',1,'']]],
  ['neonmeanworkload_2ehpp',['NeonMeanWorkload.hpp',['../_neon_mean_workload_8hpp.xhtml',1,'']]],
  ['neonmeanworkloadvalidate',['NeonMeanWorkloadValidate',['../namespacearmnn.xhtml#ae74e210a3f716c1f5f32663a8ec66345',1,'armnn']]],
  ['neonmemorymanager',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.xhtml',1,'NeonMemoryManager'],['../classarmnn_1_1_neon_memory_manager.xhtml#a01c63dc2570896ad660376c2c5efaf0c',1,'armnn::NeonMemoryManager::NeonMemoryManager()'],['../classarmnn_1_1_neon_memory_manager.xhtml#ae7c23c3fd7b529d5b05e9afd71b16c08',1,'armnn::NeonMemoryManager::NeonMemoryManager(std::unique_ptr&lt; arm_compute::IAllocator &gt; alloc, MemoryAffinity memoryAffinity)']]],
  ['neonminimumworkload',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.xhtml',1,'NeonMinimumWorkload'],['../classarmnn_1_1_neon_minimum_workload.xhtml#a29164dbeb4546e3a5f95978d0ad40a52',1,'armnn::NeonMinimumWorkload::NeonMinimumWorkload()']]],
  ['neonminimumworkload_2ecpp',['NeonMinimumWorkload.cpp',['../_neon_minimum_workload_8cpp.xhtml',1,'']]],
  ['neonminimumworkload_2ehpp',['NeonMinimumWorkload.hpp',['../_neon_minimum_workload_8hpp.xhtml',1,'']]],
  ['neonminimumworkloadvalidate',['NeonMinimumWorkloadValidate',['../namespacearmnn.xhtml#ab81159ebfa638af1b91fe1e8c5de1955',1,'armnn']]],
  ['neonmultiplicationworkload',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.xhtml',1,'NeonMultiplicationWorkload'],['../classarmnn_1_1_neon_multiplication_workload.xhtml#a2998b0d7211a2e61730c2d7af29268f4',1,'armnn::NeonMultiplicationWorkload::NeonMultiplicationWorkload()']]],
  ['neonmultiplicationworkload_2ecpp',['NeonMultiplicationWorkload.cpp',['../_neon_multiplication_workload_8cpp.xhtml',1,'']]],
  ['neonmultiplicationworkload_2ehpp',['NeonMultiplicationWorkload.hpp',['../_neon_multiplication_workload_8hpp.xhtml',1,'']]],
  ['neonmultiplicationworkloadvalidate',['NeonMultiplicationWorkloadValidate',['../namespacearmnn.xhtml#ad512520e809bfed4fbd3db9fbc241263',1,'armnn']]],
  ['neonnegworkload',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.xhtml',1,'NeonNegWorkload'],['../classarmnn_1_1_neon_neg_workload.xhtml#aa3e05eb372337f617871ea523d0dd79e',1,'armnn::NeonNegWorkload::NeonNegWorkload()']]],
  ['neonnegworkload_2ecpp',['NeonNegWorkload.cpp',['../_neon_neg_workload_8cpp.xhtml',1,'']]],
  ['neonnegworkload_2ehpp',['NeonNegWorkload.hpp',['../_neon_neg_workload_8hpp.xhtml',1,'']]],
  ['neonnegworkloadvalidate',['NeonNegWorkloadValidate',['../namespacearmnn.xhtml#a7f955750d00cdcae6038f07cc73686ea',1,'armnn']]],
  ['neonnormalizationfloatworkload',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.xhtml',1,'NeonNormalizationFloatWorkload'],['../classarmnn_1_1_neon_normalization_float_workload.xhtml#a08d141881dde41efd6118750e576e632',1,'armnn::NeonNormalizationFloatWorkload::NeonNormalizationFloatWorkload()']]],
  ['neonnormalizationfloatworkload_2ecpp',['NeonNormalizationFloatWorkload.cpp',['../_neon_normalization_float_workload_8cpp.xhtml',1,'']]],
  ['neonnormalizationfloatworkload_2ehpp',['NeonNormalizationFloatWorkload.hpp',['../_neon_normalization_float_workload_8hpp.xhtml',1,'']]],
  ['neonnormalizationworkloadvalidate',['NeonNormalizationWorkloadValidate',['../namespacearmnn.xhtml#a2ec6297db90d1d4c258c13d2d72b13d9',1,'armnn']]],
  ['neonpadworkload',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.xhtml',1,'NeonPadWorkload'],['../classarmnn_1_1_neon_pad_workload.xhtml#a9cb608b77c2d3061f8a8fa88b0b5ecba',1,'armnn::NeonPadWorkload::NeonPadWorkload()']]],
  ['neonpadworkload_2ecpp',['NeonPadWorkload.cpp',['../_neon_pad_workload_8cpp.xhtml',1,'']]],
  ['neonpadworkload_2ehpp',['NeonPadWorkload.hpp',['../_neon_pad_workload_8hpp.xhtml',1,'']]],
  ['neonpadworkloadvalidate',['NeonPadWorkloadValidate',['../namespacearmnn.xhtml#a39209c0c078e83227222eb885317c2c5',1,'armnn']]],
  ['neonpermuteworkload',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.xhtml',1,'NeonPermuteWorkload'],['../classarmnn_1_1_neon_permute_workload.xhtml#a318805b46d67e7a97073d17b167ef15f',1,'armnn::NeonPermuteWorkload::NeonPermuteWorkload()']]],
  ['neonpermuteworkload_2ecpp',['NeonPermuteWorkload.cpp',['../_neon_permute_workload_8cpp.xhtml',1,'']]],
  ['neonpermuteworkload_2ehpp',['NeonPermuteWorkload.hpp',['../_neon_permute_workload_8hpp.xhtml',1,'']]],
  ['neonpermuteworkloadvalidate',['NeonPermuteWorkloadValidate',['../namespacearmnn.xhtml#a70650f6b1d3b8511fcdb989ca769cdbb',1,'armnn']]],
  ['neonpooling2dworkload',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.xhtml',1,'NeonPooling2dWorkload'],['../classarmnn_1_1_neon_pooling2d_workload.xhtml#affb713ca83cf6b44ff5bc753bf2e1852',1,'armnn::NeonPooling2dWorkload::NeonPooling2dWorkload()']]],
  ['neonpooling2dworkload_2ecpp',['NeonPooling2dWorkload.cpp',['../_neon_pooling2d_workload_8cpp.xhtml',1,'']]],
  ['neonpooling2dworkload_2ehpp',['NeonPooling2dWorkload.hpp',['../_neon_pooling2d_workload_8hpp.xhtml',1,'']]],
  ['neonpooling2dworkloadvalidate',['NeonPooling2dWorkloadValidate',['../namespacearmnn.xhtml#a1f07655db8ad7f2738bb0d3d9e2316cc',1,'armnn']]],
  ['neonpooling3dworkload',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.xhtml',1,'NeonPooling3dWorkload'],['../classarmnn_1_1_neon_pooling3d_workload.xhtml#a71bf9440a0940c1f5df25aeae219231c',1,'armnn::NeonPooling3dWorkload::NeonPooling3dWorkload()']]],
  ['neonpooling3dworkload_2ecpp',['NeonPooling3dWorkload.cpp',['../_neon_pooling3d_workload_8cpp.xhtml',1,'']]],
  ['neonpooling3dworkload_2ehpp',['NeonPooling3dWorkload.hpp',['../_neon_pooling3d_workload_8hpp.xhtml',1,'']]],
  ['neonpooling3dworkloadvalidate',['NeonPooling3dWorkloadValidate',['../namespacearmnn.xhtml#aa2b7034aa064d5ec7a9d07828edc48bc',1,'armnn']]],
  ['neonpreluworkload',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.xhtml',1,'NeonPreluWorkload'],['../classarmnn_1_1_neon_prelu_workload.xhtml#aed40c2596c3d58ed292d029c8fb6acd3',1,'armnn::NeonPreluWorkload::NeonPreluWorkload()']]],
  ['neonpreluworkload_2ecpp',['NeonPreluWorkload.cpp',['../_neon_prelu_workload_8cpp.xhtml',1,'']]],
  ['neonpreluworkload_2ehpp',['NeonPreluWorkload.hpp',['../_neon_prelu_workload_8hpp.xhtml',1,'']]],
  ['neonpreluworkloadvalidate',['NeonPreluWorkloadValidate',['../namespacearmnn.xhtml#a188adc104b16db3dc23ed2c5ff06cbb8',1,'armnn']]],
  ['neonqlstmworkload',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.xhtml',1,'NeonQLstmWorkload'],['../classarmnn_1_1_neon_q_lstm_workload.xhtml#a83c87b3dd014c18b6609c6fecf6c8368',1,'armnn::NeonQLstmWorkload::NeonQLstmWorkload()']]],
  ['neonqlstmworkload_2ecpp',['NeonQLstmWorkload.cpp',['../_neon_q_lstm_workload_8cpp.xhtml',1,'']]],
  ['neonqlstmworkload_2ehpp',['NeonQLstmWorkload.hpp',['../_neon_q_lstm_workload_8hpp.xhtml',1,'']]],
  ['neonqlstmworkloadvalidate',['NeonQLstmWorkloadValidate',['../namespacearmnn.xhtml#a6e6f731864d33c0acd4140c7dfe17b0a',1,'armnn']]],
  ['neonquantizedlstmworkload',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.xhtml',1,'NeonQuantizedLstmWorkload'],['../classarmnn_1_1_neon_quantized_lstm_workload.xhtml#a22b3f0c6bd6ac4987c47b90521b82e57',1,'armnn::NeonQuantizedLstmWorkload::NeonQuantizedLstmWorkload()']]],
  ['neonquantizedlstmworkload_2ecpp',['NeonQuantizedLstmWorkload.cpp',['../_neon_quantized_lstm_workload_8cpp.xhtml',1,'']]],
  ['neonquantizedlstmworkload_2ehpp',['NeonQuantizedLstmWorkload.hpp',['../_neon_quantized_lstm_workload_8hpp.xhtml',1,'']]],
  ['neonquantizedlstmworkloadvalidate',['NeonQuantizedLstmWorkloadValidate',['../namespacearmnn.xhtml#ae83632e641892ad2de78f316376f6bd0',1,'armnn']]],
  ['neonquantizeworkload',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.xhtml',1,'NeonQuantizeWorkload'],['../classarmnn_1_1_neon_quantize_workload.xhtml#a0d5010cfae3f419b7ba614295b8a7272',1,'armnn::NeonQuantizeWorkload::NeonQuantizeWorkload()']]],
  ['neonquantizeworkload_2ecpp',['NeonQuantizeWorkload.cpp',['../_neon_quantize_workload_8cpp.xhtml',1,'']]],
  ['neonquantizeworkload_2ehpp',['NeonQuantizeWorkload.hpp',['../_neon_quantize_workload_8hpp.xhtml',1,'']]],
  ['neonquantizeworkloadvalidate',['NeonQuantizeWorkloadValidate',['../namespacearmnn.xhtml#a4d1e35c8bbe48e99dd522ac0f75f77d7',1,'armnn']]],
  ['neonrankworkload',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.xhtml',1,'armnn']]],
  ['neonrankworkload_2ehpp',['NeonRankWorkload.hpp',['../_neon_rank_workload_8hpp.xhtml',1,'']]],
  ['neonreduceworkload',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.xhtml',1,'NeonReduceWorkload'],['../classarmnn_1_1_neon_reduce_workload.xhtml#a6cfb00d93a07b0eb6eb81010a59a93b5',1,'armnn::NeonReduceWorkload::NeonReduceWorkload()']]],
  ['neonreduceworkload_2ecpp',['NeonReduceWorkload.cpp',['../_neon_reduce_workload_8cpp.xhtml',1,'']]],
  ['neonreduceworkload_2ehpp',['NeonReduceWorkload.hpp',['../_neon_reduce_workload_8hpp.xhtml',1,'']]],
  ['neonreduceworkloadvalidate',['NeonReduceWorkloadValidate',['../namespacearmnn.xhtml#aceb6d218204c4e0e7b4c968d6266917c',1,'armnn']]],
  ['neonregistryinitializer_2ecpp',['NeonRegistryInitializer.cpp',['../_neon_registry_initializer_8cpp.xhtml',1,'']]],
  ['neonreshapeworkload',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.xhtml',1,'NeonReshapeWorkload'],['../classarmnn_1_1_neon_reshape_workload.xhtml#a963f265760d77caec31cf13cdf63831e',1,'armnn::NeonReshapeWorkload::NeonReshapeWorkload()']]],
  ['neonreshapeworkload_2ecpp',['NeonReshapeWorkload.cpp',['../_neon_reshape_workload_8cpp.xhtml',1,'']]],
  ['neonreshapeworkload_2ehpp',['NeonReshapeWorkload.hpp',['../_neon_reshape_workload_8hpp.xhtml',1,'']]],
  ['neonreshapeworkloadvalidate',['NeonReshapeWorkloadValidate',['../namespacearmnn.xhtml#a430021076042c8157a926a3bb3a37152',1,'armnn']]],
  ['neonresizeworkload',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.xhtml',1,'NeonResizeWorkload'],['../classarmnn_1_1_neon_resize_workload.xhtml#acb5c45db124d15363bc59527a3758352',1,'armnn::NeonResizeWorkload::NeonResizeWorkload()']]],
  ['neonresizeworkload_2ecpp',['NeonResizeWorkload.cpp',['../_neon_resize_workload_8cpp.xhtml',1,'']]],
  ['neonresizeworkload_2ehpp',['NeonResizeWorkload.hpp',['../_neon_resize_workload_8hpp.xhtml',1,'']]],
  ['neonresizeworkloadvalidate',['NeonResizeWorkloadValidate',['../namespacearmnn.xhtml#a552d65f4e0a6c9e7c7796e77590063e9',1,'armnn']]],
  ['neonrsqrtworkload',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.xhtml',1,'NeonRsqrtWorkload'],['../classarmnn_1_1_neon_rsqrt_workload.xhtml#aa552d35605ed501009ca5f037d22990f',1,'armnn::NeonRsqrtWorkload::NeonRsqrtWorkload()']]],
  ['neonrsqrtworkload_2ecpp',['NeonRsqrtWorkload.cpp',['../_neon_rsqrt_workload_8cpp.xhtml',1,'']]],
  ['neonrsqrtworkload_2ehpp',['NeonRsqrtWorkload.hpp',['../_neon_rsqrt_workload_8hpp.xhtml',1,'']]],
  ['neonrsqrtworkloadvalidate',['NeonRsqrtWorkloadValidate',['../namespacearmnn.xhtml#aa7d1b5e38aa8cb731519ff12e2a73350',1,'armnn']]],
  ['neonsinworkload',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.xhtml',1,'NeonSinWorkload'],['../classarmnn_1_1_neon_sin_workload.xhtml#ad0d8c0355ffad5b01d2db4b6db206095',1,'armnn::NeonSinWorkload::NeonSinWorkload()']]],
  ['neonsinworkload_2ecpp',['NeonSinWorkload.cpp',['../_neon_sin_workload_8cpp.xhtml',1,'']]],
  ['neonsinworkload_2ehpp',['NeonSinWorkload.hpp',['../_neon_sin_workload_8hpp.xhtml',1,'']]],
  ['neonsinworkloadvalidate',['NeonSinWorkloadValidate',['../namespacearmnn.xhtml#af873a38f5251d348f37f0e94a2adc400',1,'armnn']]],
  ['neonsliceworkload',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.xhtml',1,'NeonSliceWorkload'],['../classarmnn_1_1_neon_slice_workload.xhtml#ace345c45bb2faea917c783d71c38c15c',1,'armnn::NeonSliceWorkload::NeonSliceWorkload()']]],
  ['neonsliceworkload_2ecpp',['NeonSliceWorkload.cpp',['../_neon_slice_workload_8cpp.xhtml',1,'']]],
  ['neonsliceworkload_2ehpp',['NeonSliceWorkload.hpp',['../_neon_slice_workload_8hpp.xhtml',1,'']]],
  ['neonsliceworkloadvalidate',['NeonSliceWorkloadValidate',['../namespacearmnn.xhtml#a0a223c0997e3f7faa373ed55f954252b',1,'armnn']]],
  ['neonsoftmaxworkload',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.xhtml',1,'NeonSoftmaxWorkload'],['../classarmnn_1_1_neon_softmax_workload.xhtml#a133aef7f812a938890e67b09b61ae5d3',1,'armnn::NeonSoftmaxWorkload::NeonSoftmaxWorkload()']]],
  ['neonsoftmaxworkload_2ecpp',['NeonSoftmaxWorkload.cpp',['../_neon_softmax_workload_8cpp.xhtml',1,'']]],
  ['neonsoftmaxworkload_2ehpp',['NeonSoftmaxWorkload.hpp',['../_neon_softmax_workload_8hpp.xhtml',1,'']]],
  ['neonsoftmaxworkloadvalidate',['NeonSoftmaxWorkloadValidate',['../namespacearmnn.xhtml#a4077a9771ba9c551f4ce61863f65e798',1,'armnn']]],
  ['neonspacetobatchndworkload',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.xhtml',1,'NeonSpaceToBatchNdWorkload'],['../classarmnn_1_1_neon_space_to_batch_nd_workload.xhtml#ad54e9fc1d5791024594d2c81975c9148',1,'armnn::NeonSpaceToBatchNdWorkload::NeonSpaceToBatchNdWorkload()']]],
  ['neonspacetobatchndworkload_2ecpp',['NeonSpaceToBatchNdWorkload.cpp',['../_neon_space_to_batch_nd_workload_8cpp.xhtml',1,'']]],
  ['neonspacetobatchndworkload_2ehpp',['NeonSpaceToBatchNdWorkload.hpp',['../_neon_space_to_batch_nd_workload_8hpp.xhtml',1,'']]],
  ['neonspacetobatchndworkloadvalidate',['NeonSpaceToBatchNdWorkloadValidate',['../namespacearmnn.xhtml#ab29257da888af2c4971db1344d8a526c',1,'armnn']]],
  ['neonspacetodepthworkload',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.xhtml',1,'NeonSpaceToDepthWorkload'],['../classarmnn_1_1_neon_space_to_depth_workload.xhtml#a7f6bbf57af4ec5a4b34e68d4e483e7d5',1,'armnn::NeonSpaceToDepthWorkload::NeonSpaceToDepthWorkload()']]],
  ['neonspacetodepthworkload_2ecpp',['NeonSpaceToDepthWorkload.cpp',['../_neon_space_to_depth_workload_8cpp.xhtml',1,'']]],
  ['neonspacetodepthworkload_2ehpp',['NeonSpaceToDepthWorkload.hpp',['../_neon_space_to_depth_workload_8hpp.xhtml',1,'']]],
  ['neonspacetodepthworkloadvalidate',['NeonSpaceToDepthWorkloadValidate',['../namespacearmnn.xhtml#af6d2d40482240def4614deb694933d1e',1,'armnn']]],
  ['neonsplitterworkload',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.xhtml',1,'NeonSplitterWorkload'],['../classarmnn_1_1_neon_splitter_workload.xhtml#a4ef44659ac28386257a1540de3276d2c',1,'armnn::NeonSplitterWorkload::NeonSplitterWorkload()']]],
  ['neonsplitterworkload_2ecpp',['NeonSplitterWorkload.cpp',['../_neon_splitter_workload_8cpp.xhtml',1,'']]],
  ['neonsplitterworkload_2ehpp',['NeonSplitterWorkload.hpp',['../_neon_splitter_workload_8hpp.xhtml',1,'']]],
  ['neonsplitterworkloadvalidate',['NeonSplitterWorkloadValidate',['../namespacearmnn.xhtml#aab5ea316b3decb05430323d847e3a773',1,'armnn']]],
  ['neonsqrtworkload',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.xhtml',1,'NeonSqrtWorkload'],['../classarmnn_1_1_neon_sqrt_workload.xhtml#a6db078484a6eb177c5bfdc20f0e356de',1,'armnn::NeonSqrtWorkload::NeonSqrtWorkload()']]],
  ['neonsqrtworkload_2ecpp',['NeonSqrtWorkload.cpp',['../_neon_sqrt_workload_8cpp.xhtml',1,'']]],
  ['neonsqrtworkload_2ehpp',['NeonSqrtWorkload.hpp',['../_neon_sqrt_workload_8hpp.xhtml',1,'']]],
  ['neonsqrtworkloadvalidate',['NeonSqrtWorkloadValidate',['../namespacearmnn.xhtml#a5fadc539a1a3c35c4a6138bf6e970e4c',1,'armnn']]],
  ['neonstackworkload',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.xhtml',1,'NeonStackWorkload'],['../classarmnn_1_1_neon_stack_workload.xhtml#aeb65cb0556b7a21b06f8bc9f025be5c5',1,'armnn::NeonStackWorkload::NeonStackWorkload()']]],
  ['neonstackworkload_2ecpp',['NeonStackWorkload.cpp',['../_neon_stack_workload_8cpp.xhtml',1,'']]],
  ['neonstackworkload_2ehpp',['NeonStackWorkload.hpp',['../_neon_stack_workload_8hpp.xhtml',1,'']]],
  ['neonstackworkloadvalidate',['NeonStackWorkloadValidate',['../namespacearmnn.xhtml#a65c83c74bdbd66cdd547d331998952eb',1,'armnn']]],
  ['neonstridedsliceworkload',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.xhtml',1,'NeonStridedSliceWorkload'],['../classarmnn_1_1_neon_strided_slice_workload.xhtml#aa29e48678619feee23a25e04168fa3b8',1,'armnn::NeonStridedSliceWorkload::NeonStridedSliceWorkload()']]],
  ['neonstridedsliceworkload_2ecpp',['NeonStridedSliceWorkload.cpp',['../_neon_strided_slice_workload_8cpp.xhtml',1,'']]],
  ['neonstridedsliceworkload_2ehpp',['NeonStridedSliceWorkload.hpp',['../_neon_strided_slice_workload_8hpp.xhtml',1,'']]],
  ['neonstridedsliceworkloadvalidate',['NeonStridedSliceWorkloadValidate',['../namespacearmnn.xhtml#ac71d08bf1257807c112b4d019802acc3',1,'armnn']]],
  ['neonsubtensorhandle',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.xhtml',1,'NeonSubTensorHandle'],['../classarmnn_1_1_neon_sub_tensor_handle.xhtml#a959a81401ab9e41d16bbc4a62a019aa2',1,'armnn::NeonSubTensorHandle::NeonSubTensorHandle()']]],
  ['neonsubtractionworkload',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.xhtml',1,'NeonSubtractionWorkload'],['../classarmnn_1_1_neon_subtraction_workload.xhtml#abb9c1c1aebc7e9c80216e77b275d82a5',1,'armnn::NeonSubtractionWorkload::NeonSubtractionWorkload()']]],
  ['neonsubtractionworkload_2ecpp',['NeonSubtractionWorkload.cpp',['../_neon_subtraction_workload_8cpp.xhtml',1,'']]],
  ['neonsubtractionworkload_2ehpp',['NeonSubtractionWorkload.hpp',['../_neon_subtraction_workload_8hpp.xhtml',1,'']]],
  ['neonsubtractionworkloadvalidate',['NeonSubtractionWorkloadValidate',['../namespacearmnn.xhtml#abc968e1323027f9e42cbc7642800d5ce',1,'armnn']]],
  ['neontensorhandle',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.xhtml',1,'NeonTensorHandle'],['../classarmnn_1_1_neon_tensor_handle.xhtml#aec1964e898a1dfc9c6be2f5589c0ee33',1,'armnn::NeonTensorHandle::NeonTensorHandle(const TensorInfo &amp;tensorInfo)'],['../classarmnn_1_1_neon_tensor_handle.xhtml#a8be757c370ed96fdb90168e2ff0216d6',1,'armnn::NeonTensorHandle::NeonTensorHandle(const TensorInfo &amp;tensorInfo, DataLayout dataLayout, MemorySourceFlags importFlags=static_cast&lt; MemorySourceFlags &gt;(MemorySource::Malloc))']]],
  ['neontensorhandle_2ehpp',['NeonTensorHandle.hpp',['../_neon_tensor_handle_8hpp.xhtml',1,'']]],
  ['neontensorhandlefactory',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.xhtml',1,'NeonTensorHandleFactory'],['../classarmnn_1_1_neon_tensor_handle_factory.xhtml#a07a3328cd4d6d3de55f19db56386c87a',1,'armnn::NeonTensorHandleFactory::NeonTensorHandleFactory()']]],
  ['neontensorhandlefactory_2ecpp',['NeonTensorHandleFactory.cpp',['../_neon_tensor_handle_factory_8cpp.xhtml',1,'']]],
  ['neontensorhandlefactory_2ehpp',['NeonTensorHandleFactory.hpp',['../_neon_tensor_handle_factory_8hpp.xhtml',1,'']]],
  ['neontensorhandlefactoryid',['NeonTensorHandleFactoryId',['../namespacearmnn.xhtml#aad5d4888304a57fb22c4608dc5d94dc1',1,'armnn']]],
  ['neontimer',['NeonTimer',['../classarmnn_1_1_neon_timer.xhtml',1,'NeonTimer'],['../classarmnn_1_1_neon_timer.xhtml#a5c6f81ce68d345e58fc8619b70d417a1',1,'armnn::NeonTimer::NeonTimer()']]],
  ['neontimer_2ecpp',['NeonTimer.cpp',['../_neon_timer_8cpp.xhtml',1,'']]],
  ['neontimer_2ehpp',['NeonTimer.hpp',['../_neon_timer_8hpp.xhtml',1,'']]],
  ['neontransposeconvolution2dworkload',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.xhtml',1,'NeonTransposeConvolution2dWorkload'],['../classarmnn_1_1_neon_transpose_convolution2d_workload.xhtml#a58184834e21feb8a03afcb9e53e3b503',1,'armnn::NeonTransposeConvolution2dWorkload::NeonTransposeConvolution2dWorkload()']]],
  ['neontransposeconvolution2dworkload_2ecpp',['NeonTransposeConvolution2dWorkload.cpp',['../_neon_transpose_convolution2d_workload_8cpp.xhtml',1,'']]],
  ['neontransposeconvolution2dworkload_2ehpp',['NeonTransposeConvolution2dWorkload.hpp',['../_neon_transpose_convolution2d_workload_8hpp.xhtml',1,'']]],
  ['neontransposeconvolution2dworkloadvalidate',['NeonTransposeConvolution2dWorkloadValidate',['../namespacearmnn.xhtml#abc73c3c9a09f91c22c64d7c166e9be4d',1,'armnn']]],
  ['neontransposeworkload',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.xhtml',1,'NeonTransposeWorkload'],['../classarmnn_1_1_neon_transpose_workload.xhtml#a009fddafe8e60e07e55785776b9528b9',1,'armnn::NeonTransposeWorkload::NeonTransposeWorkload()']]],
  ['neontransposeworkload_2ecpp',['NeonTransposeWorkload.cpp',['../_neon_transpose_workload_8cpp.xhtml',1,'']]],
  ['neontransposeworkload_2ehpp',['NeonTransposeWorkload.hpp',['../_neon_transpose_workload_8hpp.xhtml',1,'']]],
  ['neontransposeworkloadvalidate',['NeonTransposeWorkloadValidate',['../namespacearmnn.xhtml#a2b8555526752015115fa7fa00d88542b',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.xhtml',1,'NeonUnidirectionalSequenceLstmFloatWorkload'],['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.xhtml#acceeccc54cc2871ec72da81e48e7ef1c',1,'armnn::NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload()']]],
  ['neonunidirectionalsequencelstmfloatworkload_2ecpp',['NeonUnidirectionalSequenceLstmFloatWorkload.cpp',['../_neon_unidirectional_sequence_lstm_float_workload_8cpp.xhtml',1,'']]],
  ['neonunidirectionalsequencelstmfloatworkload_2ehpp',['NeonUnidirectionalSequenceLstmFloatWorkload.hpp',['../_neon_unidirectional_sequence_lstm_float_workload_8hpp.xhtml',1,'']]],
  ['neonunidirectionalsequencelstmfloatworkloadvalidate',['NeonUnidirectionalSequenceLstmFloatWorkloadValidate',['../namespacearmnn.xhtml#a963622d85527f420f0b922ef27de4f6b',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.xhtml',1,'NeonUnidirectionalSequenceLstmWorkload'],['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.xhtml#a39a30590f33a409c3c39181d446621aa',1,'armnn::NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload()']]],
  ['neonunidirectionalsequencelstmworkload_2ecpp',['NeonUnidirectionalSequenceLstmWorkload.cpp',['../_neon_unidirectional_sequence_lstm_workload_8cpp.xhtml',1,'']]],
  ['neonunidirectionalsequencelstmworkload_2ehpp',['NeonUnidirectionalSequenceLstmWorkload.hpp',['../_neon_unidirectional_sequence_lstm_workload_8hpp.xhtml',1,'']]],
  ['neonunidirectionalsequencelstmworkloadvalidate',['NeonUnidirectionalSequenceLstmWorkloadValidate',['../namespacearmnn.xhtml#a42561b8004ee341ac089d5f1657120db',1,'armnn']]],
  ['neonworkloadfactory',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.xhtml',1,'NeonWorkloadFactory'],['../classarmnn_1_1_neon_workload_factory.xhtml#a19a681524fa55169540fcccb9dcefaa6',1,'armnn::NeonWorkloadFactory::NeonWorkloadFactory(const std::shared_ptr&lt; NeonMemoryManager &gt; &amp;memoryManager)'],['../classarmnn_1_1_neon_workload_factory.xhtml#a4fd94de07f659ca8fac3dcb7440c8469',1,'armnn::NeonWorkloadFactory::NeonWorkloadFactory(const std::shared_ptr&lt; NeonMemoryManager &gt; &amp;memoryManager, const IBackendInternal::IBackendSpecificModelContextPtr &amp;modelContextPtr)']]],
  ['neonworkloadfactory_2ecpp',['NeonWorkloadFactory.cpp',['../_neon_workload_factory_8cpp.xhtml',1,'']]],
  ['neonworkloadfactory_2ehpp',['NeonWorkloadFactory.hpp',['../_neon_workload_factory_8hpp.xhtml',1,'']]],
  ['neonworkloads_2ehpp',['NeonWorkloads.hpp',['../_neon_workloads_8hpp.xhtml',1,'']]],
  ['neonworkloadutils_2ehpp',['NeonWorkloadUtils.hpp',['../_neon_workload_utils_8hpp.xhtml',1,'']]],
  ['network_2ecpp',['Network.cpp',['../_network_8cpp.xhtml',1,'']]],
  ['network_2ehpp',['Network.hpp',['../_network_8hpp.xhtml',1,'']]],
  ['networkfwd_2ehpp',['NetworkFwd.hpp',['../_network_fwd_8hpp.xhtml',1,'']]],
  ['networkid',['NetworkId',['../namespacearmnn.xhtml#a0d8160388a127c1a23b37bc88dc6e2ec',1,'armnn']]],
  ['networkimpl',['NetworkImpl',['../classarmnn_1_1_network_impl.xhtml',1,'NetworkImpl'],['../classarmnn_1_1_network_impl.xhtml#a1ba03515c88a4c042bffa446d306caf0',1,'armnn::NetworkImpl::NetworkImpl()']]],
  ['networkimplptr',['NetworkImplPtr',['../namespacearmnn.xhtml#a08eb5e20e6b0ce43c5729e8f88b6a910',1,'armnn']]],
  ['networkoptions',['NetworkOptions',['../namespacearmnn.xhtml#a4de71c3661093e5c4ae7775114f43413',1,'armnn']]],
  ['networkutils_2ecpp',['NetworkUtils.cpp',['../_network_utils_8cpp.xhtml',1,'']]],
  ['networkutils_2ehpp',['NetworkUtils.hpp',['../_network_utils_8hpp.xhtml',1,'']]],
  ['nextindex',['NextIndex',['../namespacearmnn.xhtml#a869f740e9c2fcb8642350c6e3d0b3742',1,'armnn']]],
  ['nhwc',['NHWC',['../namespacearmnn.xhtml#ad1d5cce2d9e9a5d61c243e5c989112e0ad066db54b89b0912e7e7c6da51e2da51',1,'armnn']]],
  ['nhwctoarmnn',['NHWCToArmNN',['../namespacearmnn_utils.xhtml#a12124184ac6aec018beb98b9715330c7',1,'armnnUtils']]],
  ['nodecontent',['NodeContent',['../classarmnn_1_1_node_content.xhtml',1,'NodeContent'],['../classarmnn_1_1_node_content.xhtml#ae21e7088e298197d3b906693af5d42c8',1,'armnn::NodeContent::NodeContent()']]],
  ['nodestate',['NodeState',['../_graph_topological_sort_8hpp.xhtml#a55999f3c61e69a9b5d871dcf480a8c5e',1,'armnnUtils::@360']]],
  ['nonconstweights',['NonConstWeights',['../namespacearmnn.xhtml#ab24d74259a053475f6040dd701a01952a0be89c9a624a5de3925150e3cd476245',1,'armnn']]],
  ['none',['None',['../namespacearmnn.xhtml#a707090747256af276c389e0cf1cb0a9aa6adf97f83acf6453d4a6a4b1070f3754',1,'armnn']]],
  ['nonmaxsuppression',['NonMaxSuppression',['../namespacearmnn.xhtml#ac8c641d4a69c9a85c487cfbc7ea4d73c',1,'armnn']]],
  ['nonnegative',['NonNegative',['../namespacearmnn_utils.xhtml#ab075020544612cd151ebdd08db537396',1,'armnnUtils']]],
  ['nonreft',['NonRefT',['../classarmnn_1_1_optional_reference_switch_3_01true_00_01_t_01_4.xhtml#aa35457bd4f798de06bf5742117fbaf16',1,'armnn::OptionalReferenceSwitch&lt; true, T &gt;']]],
  ['normal',['Normal',['../classarmnn_1_1_i_gpu_acc_tuned_parameters.xhtml#a707090747256af276c389e0cf1cb0a9aa960b44c579bc2f6818d2daaf9e4c16f0',1,'armnn::IGpuAccTunedParameters::Normal()'],['../namespacearmnn.xhtml#a707090747256af276c389e0cf1cb0a9aa960b44c579bc2f6818d2daaf9e4c16f0',1,'armnn::Normal()']]],
  ['normalization',['Normalization',['../namespacearmnn.xhtml#a56943a0946e5f15e5e58054b8e7a04a4aac61f2e17250a818dee4d12b112aa88f',1,'armnn']]],
  ['normalizationalgorithmchannel',['NormalizationAlgorithmChannel',['../namespacearmnn.xhtml#abe18a5033f2ab9c0de82c676b48f5437',1,'armnn']]],
  ['normalizationalgorithmmethod',['NormalizationAlgorithmMethod',['../namespacearmnn.xhtml#ad605d1661fa0d8c7fea651d82fbe11c9',1,'armnn']]],
  ['normalizationdescriptor',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.xhtml',1,'NormalizationDescriptor'],['../structarmnn_1_1_normalization_descriptor.xhtml#a8adc7995fc87683fb9a99b3a161904c6',1,'armnn::NormalizationDescriptor::NormalizationDescriptor()']]],
  ['normalizationdescriptorptr',['NormalizationDescriptorPtr',['../namespacearmnn_deserializer.xhtml#a2a282cf18fcfe848b47e946327ca1048',1,'armnnDeserializer']]],
  ['normalizationlayer',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.xhtml',1,'NormalizationLayer'],['../classarmnn_1_1_normalization_layer.xhtml#a5fb322b3b9c771b4038601c1c51369b6',1,'armnn::NormalizationLayer::NormalizationLayer()']]],
  ['normalizationlayer_2ecpp',['NormalizationLayer.cpp',['../_normalization_layer_8cpp.xhtml',1,'']]],
  ['normalizationlayer_2ehpp',['NormalizationLayer.hpp',['../_normalization_layer_8hpp.xhtml',1,'']]],
  ['normalizationqueuedescriptor',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.xhtml',1,'armnn']]],
  ['not_5frequired',['NOT_REQUIRED',['../namespacearmnn__driver.xhtml#a10c64daf22426af432d0a9ada03eee5caaf655f85da1fc9b6a348b9893ee6aef7',1,'armnn_driver']]],
  ['notequal',['NotEqual',['../namespacearmnn.xhtml#a2d299363c9fc33334c571fa29ca4f58ca19bb0af2c3c530538cb41aff7f235b96',1,'armnn']]],
  ['nothrowstrategy',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.xhtml',1,'armnn']]],
  ['notify',['Notify',['../classarmnn_1_1experimental_1_1_i_async_execution_callback.xhtml#ae08f101bbc3b0e6a50108a7da6f106b2',1,'armnn::experimental::IAsyncExecutionCallback::Notify()'],['../classarmnn_1_1experimental_1_1_async_execution_callback.xhtml#add3659cf62fe7fb95935edadacc10054',1,'armnn::experimental::AsyncExecutionCallback::Notify()']]],
  ['notspecified',['NotSpecified',['../namespacearmnn.xhtml#a8e1f31031ad31cd8cc22d7c9daa32681a4b7d504abac49ba24b4df86c129d3cbc',1,'armnn']]],
  ['nulldescriptor',['NullDescriptor',['../structarmnn_1_1_null_descriptor.xhtml',1,'armnn']]],
  ['nullpointerexception',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.xhtml',1,'armnn']]],
  ['nullworkload',['NullWorkload',['../classarmnn_1_1_null_workload.xhtml',1,'armnn']]],
  ['num_5fthreads',['num_threads',['../classarmnn_1_1_neon_interceptor_scheduler.xhtml#a0da94220ee1e0f4928aa31ed0d4b30f7',1,'armnn::NeonInterceptorScheduler']]],
  ['numchildren',['NumChildren',['../structarmnn_1_1_json_child_object.xhtml#a1f7ec083be66d58a3e02e12956bf005e',1,'armnn::JsonChildObject']]],
  ['numdetections',['numDetections',['../classarmnn_1_1_i_layer_support.xhtml#a3b204a7fda471668ab54dc967c5a7917',1,'armnn::ILayerSupport']]],
  ['numeric_5fcast',['numeric_cast',['../namespacearmnn.xhtml#a375ca3cff9f1b005d1412dc5f3cf5b6e',1,'armnn::numeric_cast(Source source)'],['../namespacearmnn.xhtml#a40a708e0ade241da31597eefab4ad8a9',1,'armnn::numeric_cast(Source source)'],['../namespacearmnn.xhtml#aec2a3221ba307e3f9f8d6b8cc69774fa',1,'armnn::numeric_cast(Source source)'],['../namespacearmnn.xhtml#a320f9416a8c5eda0210f1d0ec71dbe53',1,'armnn::numeric_cast(Source source)'],['../namespacearmnn.xhtml#a3afc74a78c7a7590fd1c35b0d5eb69db',1,'armnn::numeric_cast(Source source)'],['../namespacearmnn.xhtml#aa4039ab8f10849c09d08485cf6f113de',1,'armnn::numeric_cast(Source sValue)'],['../namespacearmnn.xhtml#aab0d3e691c3a26cc5c4aa5c6f12eaea0',1,'armnn::numeric_cast(Source sValue)'],['../namespacearmnn.xhtml#a4348c6348d681f6d0c7cc6d229435396',1,'armnn::numeric_cast(Source sValue)'],['../namespacearmnn.xhtml#a1b5cfb3269fecb1dda8d0aee3c8212e6',1,'armnn::numeric_cast(Source sValue)']]],
  ['numericcast_2ehpp',['NumericCast.hpp',['../_numeric_cast_8hpp.xhtml',1,'']]],
  ['nnapi_20support_20library',['NNAPI Support Library',['../supportlibrary.xhtml',1,'swtools']]]
];
