var searchData=
[
  ['tensor',['Tensor',['../classarmnn_1_1_tensor.xhtml',1,'armnn']]],
  ['tensorbufferarrayview',['TensorBufferArrayView',['../classarmnn_1_1_tensor_buffer_array_view.xhtml',1,'armnn']]],
  ['tensorhandle',['TensorHandle',['../classarmnn_1_1_tensor_handle.xhtml',1,'armnn']]],
  ['tensorhandlefactoryregistry',['TensorHandleFactoryRegistry',['../classarmnn_1_1_tensor_handle_factory_registry.xhtml',1,'armnn']]],
  ['tensorinfo',['TensorInfo',['../classarmnn_1_1_tensor_info.xhtml',1,'armnn']]],
  ['tensormemory',['TensorMemory',['../structarmnn_1_1_tensor_memory.xhtml',1,'armnn']]],
  ['tensornumdimensionsarecorrect',['TensorNumDimensionsAreCorrect',['../structarmnn_1_1_tensor_num_dimensions_are_correct.xhtml',1,'armnn']]],
  ['tensornumdimensionsaregreaterorequalto',['TensorNumDimensionsAreGreaterOrEqualTo',['../structarmnn_1_1_tensor_num_dimensions_are_greater_or_equal_to.xhtml',1,'armnn']]],
  ['tensorshape',['TensorShape',['../classarmnn_1_1_tensor_shape.xhtml',1,'armnn']]],
  ['tfliteparserimpl',['TfLiteParserImpl',['../classarmnn_tf_lite_parser_1_1_tf_lite_parser_impl.xhtml',1,'armnnTfLiteParser']]],
  ['tfliteparseroptions',['TfLiteParserOptions',['../structarmnn_tf_lite_parser_1_1_i_tf_lite_parser_1_1_tf_lite_parser_options.xhtml',1,'armnnTfLiteParser::ITfLiteParser']]],
  ['threadpool',['Threadpool',['../classarmnn_1_1experimental_1_1_threadpool.xhtml',1,'armnn::experimental']]],
  ['throwingstrategy',['ThrowingStrategy',['../structarmnn_1_1_throwing_strategy.xhtml',1,'armnn']]],
  ['timeoutexception',['TimeoutException',['../classarmnn_1_1_timeout_exception.xhtml',1,'armnn']]],
  ['tosaassertsize',['TosaAssertSize',['../struct_tosa_assert_size.xhtml',1,'']]],
  ['tosacontainercontainsthreetypes',['TosaContainerContainsThreeTypes',['../struct_tosa_container_contains_three_types.xhtml',1,'']]],
  ['tosacontainercontainstwotypes',['TosaContainerContainsTwoTypes',['../struct_tosa_container_contains_two_types.xhtml',1,'']]],
  ['tosaoperatorattributeofany',['TosaOperatorAttributeOfAny',['../struct_tosa_operator_attribute_of_any.xhtml',1,'']]],
  ['tosarefbackend',['TosaRefBackend',['../classarmnn_1_1_tosa_ref_backend.xhtml',1,'armnn']]],
  ['tosarefbaseworkload',['TosaRefBaseWorkload',['../classarmnn_1_1_tosa_ref_base_workload.xhtml',1,'armnn']]],
  ['tosareflayersupport',['TosaRefLayerSupport',['../classarmnn_1_1_tosa_ref_layer_support.xhtml',1,'armnn']]],
  ['tosarefmemorymanager',['TosaRefMemoryManager',['../classarmnn_1_1_tosa_ref_memory_manager.xhtml',1,'armnn']]],
  ['tosarefprecompiledworkload',['TosaRefPreCompiledWorkload',['../classarmnn_1_1_tosa_ref_pre_compiled_workload.xhtml',1,'armnn']]],
  ['tosareftensorhandle',['TosaRefTensorHandle',['../classarmnn_1_1_tosa_ref_tensor_handle.xhtml',1,'armnn']]],
  ['tosareftensorhandlefactory',['TosaRefTensorHandleFactory',['../classarmnn_1_1_tosa_ref_tensor_handle_factory.xhtml',1,'armnn']]],
  ['tosarefworkloadfactory',['TosaRefWorkloadFactory',['../classarmnn_1_1_tosa_ref_workload_factory.xhtml',1,'armnn']]],
  ['tosatensornumdimensionswithinbounds',['TosaTensorNumDimensionsWithinBounds',['../struct_tosa_tensor_num_dimensions_within_bounds.xhtml',1,'']]],
  ['tosatypeanyof',['TosaTypeAnyOf',['../struct_tosa_type_any_of.xhtml',1,'']]],
  ['transformiterator',['TransformIterator',['../classarmnn_1_1_transform_iterator.xhtml',1,'armnn']]],
  ['transposeasreshapeimpl',['TransposeAsReshapeImpl',['../classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.xhtml',1,'armnn::optimizations']]],
  ['transposeconvolution2ddescriptor',['TransposeConvolution2dDescriptor',['../structarmnn_1_1_transpose_convolution2d_descriptor.xhtml',1,'armnn']]],
  ['transposeconvolution2dlayer',['TransposeConvolution2dLayer',['../classarmnn_1_1_transpose_convolution2d_layer.xhtml',1,'armnn']]],
  ['transposeconvolution2dqueuedescriptor',['TransposeConvolution2dQueueDescriptor',['../structarmnn_1_1_transpose_convolution2d_queue_descriptor.xhtml',1,'armnn']]],
  ['transposedescriptor',['TransposeDescriptor',['../structarmnn_1_1_transpose_descriptor.xhtml',1,'armnn']]],
  ['transposelayer',['TransposeLayer',['../classarmnn_1_1_transpose_layer.xhtml',1,'armnn']]],
  ['transposequeuedescriptor',['TransposeQueueDescriptor',['../structarmnn_1_1_transpose_queue_descriptor.xhtml',1,'armnn']]],
  ['typeanyof',['TypeAnyOf',['../structarmnn_1_1_type_any_of.xhtml',1,'armnn']]],
  ['typediterator',['TypedIterator',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20float_2c_20decoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; const float, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20half_2c_20decoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; const Half, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int16_5ft_2c_20decoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; const int16_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; const int32_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20int32_5ft_20_3e_20_3e',['TypedIterator&lt; const int32_t, Decoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int8_5ft_2c_20decoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; const int8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20bool_20_3e_20_3e',['TypedIterator&lt; const uint8_t, Decoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; const uint8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20float_2c_20encoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; float, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20half_2c_20encoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; Half, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int16_5ft_2c_20encoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; int16_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; int32_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20int32_5ft_20_3e_20_3e',['TypedIterator&lt; int32_t, Encoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int8_5ft_2c_20encoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; int8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20bool_20_3e_20_3e',['TypedIterator&lt; uint8_t, Encoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20float_20_3e_20_3e',['TypedIterator&lt; uint8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typedworkload',['TypedWorkload',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typedworkload_3c_20debugqueuedescriptor_2c_20datatype_20_3e',['TypedWorkload&lt; DebugQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typedworkload_3c_20permutequeuedescriptor_2c_20datatype_20_3e',['TypedWorkload&lt; PermuteQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typedworkload_3c_20transposequeuedescriptor_2c_20datatype_20_3e',['TypedWorkload&lt; TransposeQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typeis',['TypeIs',['../structarmnn_1_1_type_is.xhtml',1,'armnn']]],
  ['typenotperaxisquantized',['TypeNotPerAxisQuantized',['../structarmnn_1_1_type_not_per_axis_quantized.xhtml',1,'armnn']]],
  ['typesareequal',['TypesAreEqual',['../structarmnn_1_1_types_are_equal.xhtml',1,'armnn']]]
];
