var searchData=
[
  ['backendcapabilityexception_5358',['BackendCapabilityException',['../classarmnn_1_1_backend_capability_exception.html',1,'armnn']]],
  ['backendid_5359',['BackendId',['../classarmnn_1_1_backend_id.html',1,'armnn']]],
  ['backendoption_5360',['BackendOption',['../structarmnn_1_1_backend_options_1_1_backend_option.html',1,'armnn::BackendOptions']]],
  ['backendoptions_5361',['BackendOptions',['../structarmnn_1_1_backend_options.html',1,'armnn']]],
  ['backendregistry_5362',['BackendRegistry',['../classarmnn_1_1_backend_registry.html',1,'armnn']]],
  ['backendsettings_5363',['BackendSettings',['../structarmnn_1_1_backend_settings.html',1,'armnn']]],
  ['backendunavailableexception_5364',['BackendUnavailableException',['../classarmnn_1_1_backend_unavailable_exception.html',1,'armnn']]],
  ['backendversion_5365',['BackendVersion',['../structarmnn_1_1_backend_version.html',1,'armnn']]],
  ['badoptionalaccessexception_5366',['BadOptionalAccessException',['../classarmnn_1_1_bad_optional_access_exception.html',1,'armnn']]],
  ['basedescriptor_5367',['BaseDescriptor',['../structarmnn_1_1_base_descriptor.html',1,'armnn']]],
  ['baseiterator_5368',['BaseIterator',['../classarmnn_1_1_base_iterator.html',1,'armnn']]],
  ['basememorymanager_5369',['BaseMemoryManager',['../classarmnn_1_1_base_memory_manager.html',1,'armnn']]],
  ['basetensor_5370',['BaseTensor',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20const_20void_20_2a_20_3e_5371',['BaseTensor&lt; const void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20void_20_2a_20_3e_5372',['BaseTensor&lt; void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['baseworkload_5373',['BaseWorkload',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20absqueuedescriptor_20_3e_5374',['BaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20activationqueuedescriptor_20_3e_5375',['BaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20additionqueuedescriptor_20_3e_5376',['BaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20argminmaxqueuedescriptor_20_3e_5377',['BaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20armnn_3a_3aadditionqueuedescriptor_20_3e_5378',['BaseWorkload&lt; armnn::AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5379',['BaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5380',['BaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5381',['BaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20broadcasttoqueuedescriptor_20_3e_5382',['BaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20castqueuedescriptor_20_3e_5383',['BaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20channelshufflequeuedescriptor_20_3e_5384',['BaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20comparisonqueuedescriptor_20_3e_5385',['BaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20concatqueuedescriptor_20_3e_5386',['BaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20constantqueuedescriptor_20_3e_5387',['BaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution2dqueuedescriptor_20_3e_5388',['BaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution3dqueuedescriptor_20_3e_5389',['BaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20debugqueuedescriptor_20_3e_5390',['BaseWorkload&lt; DebugQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthtospacequeuedescriptor_20_3e_5391',['BaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5392',['BaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20dequantizequeuedescriptor_20_3e_5393',['BaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5394',['BaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20divisionqueuedescriptor_20_3e_5395',['BaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5396',['BaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5397',['BaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fillqueuedescriptor_20_3e_5398',['BaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20floorqueuedescriptor_20_3e_5399',['BaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5400',['BaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fusedqueuedescriptor_20_3e_5401',['BaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherndqueuedescriptor_20_3e_5402',['BaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherqueuedescriptor_20_3e_5403',['BaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5404',['BaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5405',['BaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5406',['BaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5407',['BaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20lstmqueuedescriptor_20_3e_5408',['BaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20mapqueuedescriptor_20_3e_5409',['BaseWorkload&lt; MapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20maximumqueuedescriptor_20_3e_5410',['BaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20meanqueuedescriptor_20_3e_5411',['BaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memcopyqueuedescriptor_20_3e_5412',['BaseWorkload&lt; MemCopyQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memimportqueuedescriptor_20_3e_5413',['BaseWorkload&lt; MemImportQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memsyncqueuedescriptor_20_3e_5414',['BaseWorkload&lt; MemSyncQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20minimumqueuedescriptor_20_3e_5415',['BaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20multiplicationqueuedescriptor_20_3e_5416',['BaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20normalizationqueuedescriptor_20_3e_5417',['BaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20padqueuedescriptor_20_3e_5418',['BaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20parentdescriptor_20_3e_5419',['BaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20permutequeuedescriptor_20_3e_5420',['BaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling2dqueuedescriptor_20_3e_5421',['BaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling3dqueuedescriptor_20_3e_5422',['BaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20precompiledqueuedescriptor_20_3e_5423',['BaseWorkload&lt; PreCompiledQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20preluqueuedescriptor_20_3e_5424',['BaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20qlstmqueuedescriptor_20_3e_5425',['BaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5426',['BaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizequeuedescriptor_20_3e_5427',['BaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rankqueuedescriptor_20_3e_5428',['BaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reducequeuedescriptor_20_3e_5429',['BaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reshapequeuedescriptor_20_3e_5430',['BaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20resizequeuedescriptor_20_3e_5431',['BaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reversev2queuedescriptor_20_3e_5432',['BaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rsqrtqueuedescriptor_20_3e_5433',['BaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20scatterndqueuedescriptor_20_3e_5434',['BaseWorkload&lt; ScatterNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20shapequeuedescriptor_20_3e_5435',['BaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20slicequeuedescriptor_20_3e_5436',['BaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20softmaxqueuedescriptor_20_3e_5437',['BaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5438',['BaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5439',['BaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20splitterqueuedescriptor_20_3e_5440',['BaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stackqueuedescriptor_20_3e_5441',['BaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stridedslicequeuedescriptor_20_3e_5442',['BaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20subtractionqueuedescriptor_20_3e_5443',['BaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20tilequeuedescriptor_20_3e_5444',['BaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5445',['BaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposequeuedescriptor_20_3e_5446',['BaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5447',['BaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unmapqueuedescriptor_20_3e_5448',['BaseWorkload&lt; UnmapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['batchmatmul_5449',['BatchMatMul',['../classarmnn_1_1_batch_mat_mul.html',1,'armnn']]],
  ['batchmatmuldescriptor_5450',['BatchMatMulDescriptor',['../structarmnn_1_1_batch_mat_mul_descriptor.html',1,'armnn']]],
  ['batchmatmullayer_5451',['BatchMatMulLayer',['../classarmnn_1_1_batch_mat_mul_layer.html',1,'armnn']]],
  ['batchmatmulqueuedescriptor_5452',['BatchMatMulQueueDescriptor',['../structarmnn_1_1_batch_mat_mul_queue_descriptor.html',1,'armnn']]],
  ['batchnormalizationdescriptor_5453',['BatchNormalizationDescriptor',['../structarmnn_1_1_batch_normalization_descriptor.html',1,'armnn']]],
  ['batchnormalizationlayer_5454',['BatchNormalizationLayer',['../classarmnn_1_1_batch_normalization_layer.html',1,'armnn']]],
  ['batchnormalizationqueuedescriptor_5455',['BatchNormalizationQueueDescriptor',['../structarmnn_1_1_batch_normalization_queue_descriptor.html',1,'armnn']]],
  ['batchtospacenddescriptor_5456',['BatchToSpaceNdDescriptor',['../structarmnn_1_1_batch_to_space_nd_descriptor.html',1,'armnn']]],
  ['batchtospacendlayer_5457',['BatchToSpaceNdLayer',['../classarmnn_1_1_batch_to_space_nd_layer.html',1,'armnn']]],
  ['batchtospacendqueuedescriptor_5458',['BatchToSpaceNdQueueDescriptor',['../structarmnn_1_1_batch_to_space_nd_queue_descriptor.html',1,'armnn']]],
  ['bfloat16_5459',['BFloat16',['../classarmnn_1_1_b_float16.html',1,'armnn']]],
  ['biasandweightstypescompatible_5460',['BiasAndWeightsTypesCompatible',['../structarmnn_1_1_bias_and_weights_types_compatible.html',1,'armnn']]],
  ['biasandweightstypesmatch_5461',['BiasAndWeightsTypesMatch',['../structarmnn_1_1_bias_and_weights_types_match.html',1,'armnn']]],
  ['bindablelayer_5462',['BindableLayer',['../classarmnn_1_1_bindable_layer.html',1,'armnn']]],
  ['bindingpointinfo_5463',['BindingPointInfo',['../structarmnn_deserializer_1_1_binding_point_info.html',1,'armnnDeserializer']]],
  ['booleandecoder_5464',['BooleanDecoder',['../classarmnn_1_1_boolean_decoder.html',1,'armnn']]],
  ['booleandecoderbool_5465',['BooleanDecoderBool',['../classarmnn_1_1_boolean_decoder_bool.html',1,'armnn']]],
  ['booleanencoder_5466',['BooleanEncoder',['../classarmnn_1_1_boolean_encoder.html',1,'armnn']]],
  ['broadcastloop_5467',['BroadcastLoop',['../structarmnn_1_1_broadcast_loop.html',1,'armnn']]],
  ['broadcasttodescriptor_5468',['BroadcastToDescriptor',['../structarmnn_1_1_broadcast_to_descriptor.html',1,'armnn']]],
  ['broadcasttolayer_5469',['BroadcastToLayer',['../classarmnn_1_1_broadcast_to_layer.html',1,'armnn']]],
  ['broadcasttoqueuedescriptor_5470',['BroadcastToQueueDescriptor',['../structarmnn_1_1_broadcast_to_queue_descriptor.html',1,'armnn']]],
  ['bufferstorage_5471',['BufferStorage',['../structarmnn_1_1_buffer_storage.html',1,'armnn']]]
];
