var searchData=
[
  ['rangetracker_6365',['RangeTracker',['../classarmnn_1_1_range_tracker.html',1,'armnn']]],
  ['ranklayer_6366',['RankLayer',['../classarmnn_1_1_rank_layer.html',1,'armnn']]],
  ['rankqueuedescriptor_6367',['RankQueueDescriptor',['../structarmnn_1_1_rank_queue_descriptor.html',1,'armnn']]],
  ['reducedescriptor_6368',['ReduceDescriptor',['../structarmnn_1_1_reduce_descriptor.html',1,'armnn']]],
  ['reducelayer_6369',['ReduceLayer',['../classarmnn_1_1_reduce_layer.html',1,'armnn']]],
  ['reducequeuedescriptor_6370',['ReduceQueueDescriptor',['../structarmnn_1_1_reduce_queue_descriptor.html',1,'armnn']]],
  ['refactivationworkload_6371',['RefActivationWorkload',['../classarmnn_1_1_ref_activation_workload.html',1,'armnn']]],
  ['refargminmaxworkload_6372',['RefArgMinMaxWorkload',['../classarmnn_1_1_ref_arg_min_max_workload.html',1,'armnn']]],
  ['refbackend_6373',['RefBackend',['../classarmnn_1_1_ref_backend.html',1,'armnn']]],
  ['refbaseworkload_6374',['RefBaseWorkload',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20activationqueuedescriptor_20_3e_6375',['RefBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_6376',['RefBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_6377',['RefBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_6378',['RefBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_6379',['RefBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20broadcasttoqueuedescriptor_20_3e_6380',['RefBaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20castqueuedescriptor_20_3e_6381',['RefBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_6382',['RefBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20comparisonqueuedescriptor_20_3e_6383',['RefBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20concatqueuedescriptor_20_3e_6384',['RefBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20constantqueuedescriptor_20_3e_6385',['RefBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_6386',['RefBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_6387',['RefBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_6388',['RefBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_6389',['RefBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20dequantizequeuedescriptor_20_3e_6390',['RefBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_6391',['RefBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_6392',['RefBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_6393',['RefBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20fillqueuedescriptor_20_3e_6394',['RefBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20floorqueuedescriptor_20_3e_6395',['RefBaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_6396',['RefBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20gatherndqueuedescriptor_20_3e_6397',['RefBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20gatherqueuedescriptor_20_3e_6398',['RefBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_6399',['RefBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20l2normalizationqueuedescriptor_20_3e_6400',['RefBaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_6401',['RefBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_6402',['RefBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20lstmqueuedescriptor_20_3e_6403',['RefBaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20meanqueuedescriptor_20_3e_6404',['RefBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20normalizationqueuedescriptor_20_3e_6405',['RefBaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20padqueuedescriptor_20_3e_6406',['RefBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20parentdescriptor_20_3e_6407',['RefBaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_6408',['RefBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_6409',['RefBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20preluqueuedescriptor_20_3e_6410',['RefBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20qlstmqueuedescriptor_20_3e_6411',['RefBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20quantizequeuedescriptor_20_3e_6412',['RefBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20rankqueuedescriptor_20_3e_6413',['RefBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reducequeuedescriptor_20_3e_6414',['RefBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reshapequeuedescriptor_20_3e_6415',['RefBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20resizequeuedescriptor_20_3e_6416',['RefBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reversev2queuedescriptor_20_3e_6417',['RefBaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20scatterndqueuedescriptor_20_3e_6418',['RefBaseWorkload&lt; ScatterNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20shapequeuedescriptor_20_3e_6419',['RefBaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20slicequeuedescriptor_20_3e_6420',['RefBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20softmaxqueuedescriptor_20_3e_6421',['RefBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_6422',['RefBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_6423',['RefBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20splitterqueuedescriptor_20_3e_6424',['RefBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20stackqueuedescriptor_20_3e_6425',['RefBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_6426',['RefBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20tilequeuedescriptor_20_3e_6427',['RefBaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_6428',['RefBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_6429',['RefBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbatchmatmulworkload_6430',['RefBatchMatMulWorkload',['../classarmnn_1_1_ref_batch_mat_mul_workload.html',1,'armnn']]],
  ['refbatchnormalizationworkload_6431',['RefBatchNormalizationWorkload',['../classarmnn_1_1_ref_batch_normalization_workload.html',1,'armnn']]],
  ['refbatchtospacendworkload_6432',['RefBatchToSpaceNdWorkload',['../classarmnn_1_1_ref_batch_to_space_nd_workload.html',1,'armnn']]],
  ['refbroadcasttoworkload_6433',['RefBroadcastToWorkload',['../classarmnn_1_1_ref_broadcast_to_workload.html',1,'armnn']]],
  ['refcastworkload_6434',['RefCastWorkload',['../classarmnn_1_1_ref_cast_workload.html',1,'armnn']]],
  ['refchannelshuffleworkload_6435',['RefChannelShuffleWorkload',['../classarmnn_1_1_ref_channel_shuffle_workload.html',1,'armnn']]],
  ['refcomparisonworkload_6436',['RefComparisonWorkload',['../classarmnn_1_1_ref_comparison_workload.html',1,'armnn']]],
  ['refconcatworkload_6437',['RefConcatWorkload',['../classarmnn_1_1_ref_concat_workload.html',1,'armnn']]],
  ['refconstantworkload_6438',['RefConstantWorkload',['../classarmnn_1_1_ref_constant_workload.html',1,'armnn']]],
  ['refconvertfp16tofp32workload_6439',['RefConvertFp16ToFp32Workload',['../classarmnn_1_1_ref_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['refconvertfp32tofp16workload_6440',['RefConvertFp32ToFp16Workload',['../classarmnn_1_1_ref_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['refconvolution2dworkload_6441',['RefConvolution2dWorkload',['../classarmnn_1_1_ref_convolution2d_workload.html',1,'armnn']]],
  ['refconvolution3dworkload_6442',['RefConvolution3dWorkload',['../classarmnn_1_1_ref_convolution3d_workload.html',1,'armnn']]],
  ['refdebugworkload_6443',['RefDebugWorkload',['../classarmnn_1_1_ref_debug_workload.html',1,'armnn']]],
  ['refdepthtospaceworkload_6444',['RefDepthToSpaceWorkload',['../classarmnn_1_1_ref_depth_to_space_workload.html',1,'armnn']]],
  ['refdepthwiseconvolution2dworkload_6445',['RefDepthwiseConvolution2dWorkload',['../classarmnn_1_1_ref_depthwise_convolution2d_workload.html',1,'armnn']]],
  ['refdequantizeworkload_6446',['RefDequantizeWorkload',['../classarmnn_1_1_ref_dequantize_workload.html',1,'armnn']]],
  ['refdetectionpostprocessworkload_6447',['RefDetectionPostProcessWorkload',['../classarmnn_1_1_ref_detection_post_process_workload.html',1,'armnn']]],
  ['refelementwisebinaryworkload_6448',['RefElementwiseBinaryWorkload',['../classarmnn_1_1_ref_elementwise_binary_workload.html',1,'armnn']]],
  ['refelementwiseunaryworkload_6449',['RefElementwiseUnaryWorkload',['../classarmnn_1_1_ref_elementwise_unary_workload.html',1,'armnn']]],
  ['refelementwiseworkload_6450',['RefElementwiseWorkload',['../classarmnn_1_1_ref_elementwise_workload.html',1,'armnn']]],
  ['reffakequantizationfloat32workload_6451',['RefFakeQuantizationFloat32Workload',['../classarmnn_1_1_ref_fake_quantization_float32_workload.html',1,'armnn']]],
  ['reffillworkload_6452',['RefFillWorkload',['../classarmnn_1_1_ref_fill_workload.html',1,'armnn']]],
  ['reffloorworkload_6453',['RefFloorWorkload',['../classarmnn_1_1_ref_floor_workload.html',1,'armnn']]],
  ['reffullyconnectedworkload_6454',['RefFullyConnectedWorkload',['../classarmnn_1_1_ref_fully_connected_workload.html',1,'armnn']]],
  ['refgatherndworkload_6455',['RefGatherNdWorkload',['../classarmnn_1_1_ref_gather_nd_workload.html',1,'armnn']]],
  ['refgatherworkload_6456',['RefGatherWorkload',['../classarmnn_1_1_ref_gather_workload.html',1,'armnn']]],
  ['refinstancenormalizationworkload_6457',['RefInstanceNormalizationWorkload',['../classarmnn_1_1_ref_instance_normalization_workload.html',1,'armnn']]],
  ['refl2normalizationworkload_6458',['RefL2NormalizationWorkload',['../classarmnn_1_1_ref_l2_normalization_workload.html',1,'armnn']]],
  ['reflayersupport_6459',['RefLayerSupport',['../classarmnn_1_1_ref_layer_support.html',1,'armnn']]],
  ['reflogicalbinaryworkload_6460',['RefLogicalBinaryWorkload',['../classarmnn_1_1_ref_logical_binary_workload.html',1,'armnn']]],
  ['reflogicalunaryworkload_6461',['RefLogicalUnaryWorkload',['../classarmnn_1_1_ref_logical_unary_workload.html',1,'armnn']]],
  ['reflogsoftmaxworkload_6462',['RefLogSoftmaxWorkload',['../classarmnn_1_1_ref_log_softmax_workload.html',1,'armnn']]],
  ['reflstmworkload_6463',['RefLstmWorkload',['../classarmnn_1_1_ref_lstm_workload.html',1,'armnn']]],
  ['refmeanworkload_6464',['RefMeanWorkload',['../classarmnn_1_1_ref_mean_workload.html',1,'armnn']]],
  ['refmemorymanager_6465',['RefMemoryManager',['../classarmnn_1_1_ref_memory_manager.html',1,'armnn']]],
  ['refnormalizationworkload_6466',['RefNormalizationWorkload',['../classarmnn_1_1_ref_normalization_workload.html',1,'armnn']]],
  ['refpadworkload_6467',['RefPadWorkload',['../classarmnn_1_1_ref_pad_workload.html',1,'armnn']]],
  ['refpermuteworkload_6468',['RefPermuteWorkload',['../classarmnn_1_1_ref_permute_workload.html',1,'armnn']]],
  ['refpooling2dworkload_6469',['RefPooling2dWorkload',['../classarmnn_1_1_ref_pooling2d_workload.html',1,'armnn']]],
  ['refpooling3dworkload_6470',['RefPooling3dWorkload',['../classarmnn_1_1_ref_pooling3d_workload.html',1,'armnn']]],
  ['refpreluworkload_6471',['RefPreluWorkload',['../classarmnn_1_1_ref_prelu_workload.html',1,'armnn']]],
  ['refqlstmworkload_6472',['RefQLstmWorkload',['../classarmnn_1_1_ref_q_lstm_workload.html',1,'armnn']]],
  ['refquantizeworkload_6473',['RefQuantizeWorkload',['../classarmnn_1_1_ref_quantize_workload.html',1,'armnn']]],
  ['refrankworkload_6474',['RefRankWorkload',['../structarmnn_1_1_ref_rank_workload.html',1,'armnn']]],
  ['refreduceworkload_6475',['RefReduceWorkload',['../classarmnn_1_1_ref_reduce_workload.html',1,'armnn']]],
  ['refreshapeworkload_6476',['RefReshapeWorkload',['../classarmnn_1_1_ref_reshape_workload.html',1,'armnn']]],
  ['refresizeworkload_6477',['RefResizeWorkload',['../classarmnn_1_1_ref_resize_workload.html',1,'armnn']]],
  ['refreversev2workload_6478',['RefReverseV2Workload',['../classarmnn_1_1_ref_reverse_v2_workload.html',1,'armnn']]],
  ['refscatterndworkload_6479',['RefScatterNdWorkload',['../classarmnn_1_1_ref_scatter_nd_workload.html',1,'armnn']]],
  ['refshapeworkload_6480',['RefShapeWorkload',['../structarmnn_1_1_ref_shape_workload.html',1,'armnn']]],
  ['refsliceworkload_6481',['RefSliceWorkload',['../classarmnn_1_1_ref_slice_workload.html',1,'armnn']]],
  ['refsoftmaxworkload_6482',['RefSoftmaxWorkload',['../classarmnn_1_1_ref_softmax_workload.html',1,'armnn']]],
  ['refspacetobatchndworkload_6483',['RefSpaceToBatchNdWorkload',['../classarmnn_1_1_ref_space_to_batch_nd_workload.html',1,'armnn']]],
  ['refspacetodepthworkload_6484',['RefSpaceToDepthWorkload',['../classarmnn_1_1_ref_space_to_depth_workload.html',1,'armnn']]],
  ['refsplitterworkload_6485',['RefSplitterWorkload',['../classarmnn_1_1_ref_splitter_workload.html',1,'armnn']]],
  ['refstackworkload_6486',['RefStackWorkload',['../classarmnn_1_1_ref_stack_workload.html',1,'armnn']]],
  ['refstridedsliceworkload_6487',['RefStridedSliceWorkload',['../classarmnn_1_1_ref_strided_slice_workload.html',1,'armnn']]],
  ['reftensorhandle_6488',['RefTensorHandle',['../classarmnn_1_1_ref_tensor_handle.html',1,'armnn']]],
  ['reftensorhandledecorator_6489',['RefTensorHandleDecorator',['../classarmnn_1_1_ref_tensor_handle_decorator.html',1,'armnn']]],
  ['reftensorhandlefactory_6490',['RefTensorHandleFactory',['../classarmnn_1_1_ref_tensor_handle_factory.html',1,'armnn']]],
  ['reftileworkload_6491',['RefTileWorkload',['../classarmnn_1_1_ref_tile_workload.html',1,'armnn']]],
  ['reftransposeconvolution2dworkload_6492',['RefTransposeConvolution2dWorkload',['../classarmnn_1_1_ref_transpose_convolution2d_workload.html',1,'armnn']]],
  ['reftransposeworkload_6493',['RefTransposeWorkload',['../classarmnn_1_1_ref_transpose_workload.html',1,'armnn']]],
  ['refunidirectionalsequencelstmworkload_6494',['RefUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_ref_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['refworkloadfactory_6495',['RefWorkloadFactory',['../classarmnn_1_1_ref_workload_factory.html',1,'armnn']]],
  ['reshapedescriptor_6496',['ReshapeDescriptor',['../structarmnn_1_1_reshape_descriptor.html',1,'armnn']]],
  ['reshapelayer_6497',['ReshapeLayer',['../classarmnn_1_1_reshape_layer.html',1,'armnn']]],
  ['reshapequeuedescriptor_6498',['ReshapeQueueDescriptor',['../structarmnn_1_1_reshape_queue_descriptor.html',1,'armnn']]],
  ['resizedescriptor_6499',['ResizeDescriptor',['../structarmnn_1_1_resize_descriptor.html',1,'armnn']]],
  ['resizelayer_6500',['ResizeLayer',['../classarmnn_1_1_resize_layer.html',1,'armnn']]],
  ['resizequeuedescriptor_6501',['ResizeQueueDescriptor',['../structarmnn_1_1_resize_queue_descriptor.html',1,'armnn']]],
  ['resolvetypeimpl_6502',['ResolveTypeImpl',['../structarmnn_1_1_resolve_type_impl.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3abfloat16_20_3e_6503',['ResolveTypeImpl&lt; DataType::BFloat16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_b_float16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aboolean_20_3e_6504',['ResolveTypeImpl&lt; DataType::Boolean &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_boolean_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat16_20_3e_6505',['ResolveTypeImpl&lt; DataType::Float16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat32_20_3e_6506',['ResolveTypeImpl&lt; DataType::Float32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float32_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymms8_20_3e_6507',['ResolveTypeImpl&lt; DataType::QAsymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_s8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymmu8_20_3e_6508',['ResolveTypeImpl&lt; DataType::QAsymmU8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_u8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms16_20_3e_6509',['ResolveTypeImpl&lt; DataType::QSymmS16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms8_20_3e_6510',['ResolveTypeImpl&lt; DataType::QSymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned32_20_3e_6511',['ResolveTypeImpl&lt; DataType::Signed32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed32_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned64_20_3e_6512',['ResolveTypeImpl&lt; DataType::Signed64 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed64_01_4.html',1,'armnn']]],
  ['reversev2layer_6513',['ReverseV2Layer',['../classarmnn_1_1_reverse_v2_layer.html',1,'armnn']]],
  ['reversev2queuedescriptor_6514',['ReverseV2QueueDescriptor',['../structarmnn_1_1_reverse_v2_queue_descriptor.html',1,'armnn']]],
  ['rsqrt_6515',['rsqrt',['../structarmnn_1_1rsqrt.html',1,'armnn']]],
  ['rsqrtlayer_6516',['RsqrtLayer',['../classarmnn_1_1_rsqrt_layer.html',1,'armnn']]],
  ['rsqrtqueuedescriptor_6517',['RsqrtQueueDescriptor',['../structarmnn_1_1_rsqrt_queue_descriptor.html',1,'armnn']]],
  ['rule_6518',['Rule',['../structarmnn_1_1_rule.html',1,'armnn']]],
  ['runtimeexception_6519',['RuntimeException',['../classarmnn_1_1_runtime_exception.html',1,'armnn']]],
  ['runtimeimpl_6520',['RuntimeImpl',['../structarmnn_1_1_runtime_impl.html',1,'armnn']]]
];
