var searchData=
[
  ['qasymm8decoder_6287',['QASymm8Decoder',['../classarmnn_1_1_q_a_symm8_decoder.html',1,'armnn']]],
  ['qasymm8encoder_6288',['QASymm8Encoder',['../classarmnn_1_1_q_a_symm8_encoder.html',1,'armnn']]],
  ['qasymms8decoder_6289',['QASymmS8Decoder',['../classarmnn_1_1_q_a_symm_s8_decoder.html',1,'armnn']]],
  ['qasymms8encoder_6290',['QASymmS8Encoder',['../classarmnn_1_1_q_a_symm_s8_encoder.html',1,'armnn']]],
  ['qlstmbasicparameters_6291',['QLstmBasicParameters',['../structarmnn_1_1_q_lstm_basic_parameters.html',1,'armnn']]],
  ['qlstmdescriptor_6292',['QLstmDescriptor',['../structarmnn_1_1_q_lstm_descriptor.html',1,'armnn']]],
  ['qlstmlayer_6293',['QLstmLayer',['../classarmnn_1_1_q_lstm_layer.html',1,'armnn']]],
  ['qlstmoptcifgparameters_6294',['QLstmOptCifgParameters',['../structarmnn_1_1_q_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['qlstmoptlayernormparameters_6295',['QLstmOptLayerNormParameters',['../structarmnn_1_1_q_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['qlstmoptpeepholeparameters_6296',['QLstmOptPeepholeParameters',['../structarmnn_1_1_q_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['qlstmoptprojectionparameters_6297',['QLstmOptProjectionParameters',['../structarmnn_1_1_q_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['qlstmqueuedescriptor_6298',['QLstmQueueDescriptor',['../structarmnn_1_1_q_lstm_queue_descriptor.html',1,'armnn']]],
  ['qsymm16decoder_6299',['QSymm16Decoder',['../classarmnn_1_1_q_symm16_decoder.html',1,'armnn']]],
  ['qsymm16encoder_6300',['QSymm16Encoder',['../classarmnn_1_1_q_symm16_encoder.html',1,'armnn']]],
  ['qsymm16peraxisencoder_6301',['QSymm16PerAxisEncoder',['../classarmnn_1_1_q_symm16_per_axis_encoder.html',1,'armnn']]],
  ['qsymm8peraxisdecoder_6302',['QSymm8PerAxisDecoder',['../classarmnn_1_1_q_symm8_per_axis_decoder.html',1,'armnn']]],
  ['qsymm8peraxisencoder_6303',['QSymm8PerAxisEncoder',['../classarmnn_1_1_q_symm8_per_axis_encoder.html',1,'armnn']]],
  ['qsymms8decoder_6304',['QSymmS8Decoder',['../classarmnn_1_1_q_symm_s8_decoder.html',1,'armnn']]],
  ['qsymms8encoder_6305',['QSymmS8Encoder',['../classarmnn_1_1_q_symm_s8_encoder.html',1,'armnn']]],
  ['quantizationparametersareequal_6306',['QuantizationParametersAreEqual',['../structarmnn_1_1_quantization_parameters_are_equal.html',1,'armnn']]],
  ['quantizedlstminputparams_6307',['QuantizedLstmInputParams',['../structarmnn_1_1_quantized_lstm_input_params.html',1,'armnn']]],
  ['quantizedlstminputparamsinfo_6308',['QuantizedLstmInputParamsInfo',['../structarmnn_1_1_quantized_lstm_input_params_info.html',1,'armnn']]],
  ['quantizedlstmlayer_6309',['QuantizedLstmLayer',['../classarmnn_1_1_quantized_lstm_layer.html',1,'armnn']]],
  ['quantizedlstmparameters_6310',['QuantizedLstmParameters',['../structarmnn_1_1_quantized_lstm_parameters.html',1,'armnn']]],
  ['quantizedlstmqueuedescriptor_6311',['QuantizedLstmQueueDescriptor',['../structarmnn_1_1_quantized_lstm_queue_descriptor.html',1,'armnn']]],
  ['quantizedmultipliersmallerthanone_6312',['QuantizedMultiplierSmallerThanOne',['../structarmnn_1_1_quantized_multiplier_smaller_than_one.html',1,'armnn']]],
  ['quantizelayer_6313',['QuantizeLayer',['../classarmnn_1_1_quantize_layer.html',1,'armnn']]],
  ['quantizequeuedescriptor_6314',['QuantizeQueueDescriptor',['../structarmnn_1_1_quantize_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptor_6315',['QueueDescriptor',['../structarmnn_1_1_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptorwithparameters_6316',['QueueDescriptorWithParameters',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20activationdescriptor_20_3e_6317',['QueueDescriptorWithParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20argminmaxdescriptor_20_3e_6318',['QueueDescriptorWithParameters&lt; ArgMinMaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchmatmuldescriptor_20_3e_6319',['QueueDescriptorWithParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchnormalizationdescriptor_20_3e_6320',['QueueDescriptorWithParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchtospacenddescriptor_20_3e_6321',['QueueDescriptorWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20broadcasttodescriptor_20_3e_6322',['QueueDescriptorWithParameters&lt; BroadcastToDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20channelshuffledescriptor_20_3e_6323',['QueueDescriptorWithParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20comparisondescriptor_20_3e_6324',['QueueDescriptorWithParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution2ddescriptor_20_3e_6325',['QueueDescriptorWithParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution3ddescriptor_20_3e_6326',['QueueDescriptorWithParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthtospacedescriptor_20_3e_6327',['QueueDescriptorWithParameters&lt; DepthToSpaceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_6328',['QueueDescriptorWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20detectionpostprocessdescriptor_20_3e_6329',['QueueDescriptorWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwisebinarydescriptor_20_3e_6330',['QueueDescriptorWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwiseunarydescriptor_20_3e_6331',['QueueDescriptorWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fakequantizationdescriptor_20_3e_6332',['QueueDescriptorWithParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20filldescriptor_20_3e_6333',['QueueDescriptorWithParameters&lt; FillDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fullyconnecteddescriptor_20_3e_6334',['QueueDescriptorWithParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fuseddescriptor_20_3e_6335',['QueueDescriptorWithParameters&lt; FusedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20gatherdescriptor_20_3e_6336',['QueueDescriptorWithParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20instancenormalizationdescriptor_20_3e_6337',['QueueDescriptorWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20l2normalizationdescriptor_20_3e_6338',['QueueDescriptorWithParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logicalbinarydescriptor_20_3e_6339',['QueueDescriptorWithParameters&lt; LogicalBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logsoftmaxdescriptor_20_3e_6340',['QueueDescriptorWithParameters&lt; LogSoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20lstmdescriptor_20_3e_6341',['QueueDescriptorWithParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20meandescriptor_20_3e_6342',['QueueDescriptorWithParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20normalizationdescriptor_20_3e_6343',['QueueDescriptorWithParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20originsdescriptor_20_3e_6344',['QueueDescriptorWithParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20paddescriptor_20_3e_6345',['QueueDescriptorWithParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20permutedescriptor_20_3e_6346',['QueueDescriptorWithParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling2ddescriptor_20_3e_6347',['QueueDescriptorWithParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling3ddescriptor_20_3e_6348',['QueueDescriptorWithParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20precompileddescriptor_20_3e_6349',['QueueDescriptorWithParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20qlstmdescriptor_20_3e_6350',['QueueDescriptorWithParameters&lt; QLstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reducedescriptor_20_3e_6351',['QueueDescriptorWithParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reshapedescriptor_20_3e_6352',['QueueDescriptorWithParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20resizedescriptor_20_3e_6353',['QueueDescriptorWithParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20scatternddescriptor_20_3e_6354',['QueueDescriptorWithParameters&lt; ScatterNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20slicedescriptor_20_3e_6355',['QueueDescriptorWithParameters&lt; SliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20softmaxdescriptor_20_3e_6356',['QueueDescriptorWithParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetobatchnddescriptor_20_3e_6357',['QueueDescriptorWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetodepthdescriptor_20_3e_6358',['QueueDescriptorWithParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stackdescriptor_20_3e_6359',['QueueDescriptorWithParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stridedslicedescriptor_20_3e_6360',['QueueDescriptorWithParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20tiledescriptor_20_3e_6361',['QueueDescriptorWithParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_6362',['QueueDescriptorWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposedescriptor_20_3e_6363',['QueueDescriptorWithParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20viewsdescriptor_20_3e_6364',['QueueDescriptorWithParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]]
];
