var searchData=
[
  ['datalayoutindexed_0',['DataLayoutIndexed',['../classarmnn_utils_1_1_data_layout_indexed.html',1,'armnnUtils']]],
  ['debuglayer_1',['DebugLayer',['../classarmnn_1_1_debug_layer.html',1,'armnn']]],
  ['debugqueuedescriptor_2',['DebugQueueDescriptor',['../structarmnn_1_1_debug_queue_descriptor.html',1,'armnn']]],
  ['decoder_3',['Decoder',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20bool_20_3e_4',['Decoder&lt; bool &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20double_5ft_20_3e_5',['Decoder&lt; double_t &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20float_20_3e_6',['Decoder&lt; float &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20int32_5ft_20_3e_7',['Decoder&lt; int32_t &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['defaultallocator_8',['DefaultAllocator',['../classarmnn_1_1_default_allocator.html',1,'armnn']]],
  ['delegate_9',['Delegate',['../classarmnn_delegate_1_1_delegate.html',1,'armnnDelegate']]],
  ['delegatedata_10',['DelegateData',['../structarmnn_delegate_1_1_delegate_data.html',1,'DelegateData'],['../structarmnn_opaque_delegate_1_1_delegate_data.html',1,'DelegateData']]],
  ['deletebroadcasttoimpl_11',['DeleteBroadcastToImpl',['../classarmnn_1_1optimizations_1_1_delete_broadcast_to_impl.html',1,'armnn::optimizations']]],
  ['depthtospacelayer_12',['DepthToSpaceLayer',['../classarmnn_1_1_depth_to_space_layer.html',1,'armnn']]],
  ['depthtospacequeuedescriptor_13',['DepthToSpaceQueueDescriptor',['../structarmnn_1_1_depth_to_space_queue_descriptor.html',1,'armnn']]],
  ['depthwiseconvolution2ddescriptor_14',['DepthwiseConvolution2dDescriptor',['../structarmnn_1_1_depthwise_convolution2d_descriptor.html',1,'armnn']]],
  ['depthwiseconvolution2dlayer_15',['DepthwiseConvolution2dLayer',['../classarmnn_1_1_depthwise_convolution2d_layer.html',1,'armnn']]],
  ['depthwiseconvolution2dqueuedescriptor_16',['DepthwiseConvolution2dQueueDescriptor',['../structarmnn_1_1_depthwise_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['dequantizelayer_17',['DequantizeLayer',['../classarmnn_1_1_dequantize_layer.html',1,'armnn']]],
  ['dequantizequeuedescriptor_18',['DequantizeQueueDescriptor',['../structarmnn_1_1_dequantize_queue_descriptor.html',1,'armnn']]],
  ['deserializerimpl_19',['DeserializerImpl',['../classarmnn_deserializer_1_1_i_deserializer_1_1_deserializer_impl.html',1,'armnnDeserializer::IDeserializer']]],
  ['detectionpostprocessdescriptor_20',['DetectionPostProcessDescriptor',['../structarmnn_1_1_detection_post_process_descriptor.html',1,'armnn']]],
  ['detectionpostprocesslayer_21',['DetectionPostProcessLayer',['../classarmnn_1_1_detection_post_process_layer.html',1,'armnn']]],
  ['detectionpostprocessqueuedescriptor_22',['DetectionPostProcessQueueDescriptor',['../structarmnn_1_1_detection_post_process_queue_descriptor.html',1,'armnn']]],
  ['devicespec_23',['DeviceSpec',['../classarmnn_1_1_device_spec.html',1,'armnn']]],
  ['divisionlayer_24',['DivisionLayer',['../classarmnn_1_1_division_layer.html',1,'armnn']]],
  ['divisionqueuedescriptor_25',['DivisionQueueDescriptor',['../structarmnn_1_1_division_queue_descriptor.html',1,'armnn']]],
  ['dotattributeset_26',['DotAttributeSet',['../classarmnn_1_1_dot_attribute_set.html',1,'armnn']]],
  ['dotbase_27',['DotBase',['../classarmnn_1_1_dot_base.html',1,'armnn']]],
  ['dotdefaults_28',['DotDefaults',['../classarmnn_1_1_dot_defaults.html',1,'armnn']]],
  ['dotedge_29',['DotEdge',['../classarmnn_1_1_dot_edge.html',1,'armnn']]],
  ['dotgraph_30',['DotGraph',['../classarmnn_1_1_dot_graph.html',1,'armnn']]],
  ['dotnode_31',['DotNode',['../classarmnn_1_1_dot_node.html',1,'armnn']]],
  ['dynamicbackend_32',['DynamicBackend',['../classarmnn_1_1_dynamic_backend.html',1,'armnn']]],
  ['dynamicbackendutils_33',['DynamicBackendUtils',['../classarmnn_1_1_dynamic_backend_utils.html',1,'armnn']]]
];
