var searchData=
[
  ['neonabsworkload_0',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.html',1,'armnn']]],
  ['neonactivationworkload_1',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.html',1,'armnn']]],
  ['neonadditionworkload_2',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.html',1,'armnn']]],
  ['neonargminmaxworkload_3',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.html',1,'armnn']]],
  ['neonbackend_4',['NeonBackend',['../classarmnn_1_1_neon_backend.html',1,'armnn']]],
  ['neonbackendmodelcontext_5',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.html',1,'armnn']]],
  ['neonbaseworkload_6',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e_7',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e_8',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e_9',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_10',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_11',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_12',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_13',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e_14',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_15',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e_16',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e_17',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e_18',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_19',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_20',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_21',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_22',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e_23',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_24',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e_25',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_26',['NeonBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_27',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e_28',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_29',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fusedqueuedescriptor_20_3e_30',['NeonBaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e_31',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e_32',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_33',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_34',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_35',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e_36',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e_37',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e_38',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e_39',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e_40',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e_41',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_42',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_43',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e_44',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e_45',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_46',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e_47',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e_48',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e_49',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e_50',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e_51',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e_52',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e_53',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e_54',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_55',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_56',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e_57',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e_58',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_59',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e_60',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_61',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e_62',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_63',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbatchmatmulworkload_64',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.html',1,'armnn']]],
  ['neonbatchnormalizationworkload_65',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.html',1,'armnn']]],
  ['neonbatchtospacendworkload_66',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.html',1,'armnn']]],
  ['neoncastworkload_67',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.html',1,'armnn']]],
  ['neonchannelshuffleworkload_68',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.html',1,'armnn']]],
  ['neoncomparisonworkload_69',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.html',1,'armnn']]],
  ['neonconcatworkload_70',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.html',1,'armnn']]],
  ['neonconstantworkload_71',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.html',1,'armnn']]],
  ['neonconvertfp16tofp32workload_72',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['neonconvertfp32tofp16workload_73',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['neonconvolution2dworkload_74',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.html',1,'armnn']]],
  ['neonconvolution3dworkload_75',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.html',1,'armnn']]],
  ['neondepthtospaceworkload_76',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.html',1,'armnn']]],
  ['neondepthwiseconvolutionworkload_77',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.html',1,'armnn']]],
  ['neondequantizeworkload_78',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.html',1,'armnn']]],
  ['neondetectionpostprocessworkload_79',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.html',1,'armnn']]],
  ['neondivisionworkload_80',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.html',1,'armnn']]],
  ['neonelementwisebinaryworkload_81',['NeonElementwiseBinaryWorkload',['../classarmnn_1_1_neon_elementwise_binary_workload.html',1,'armnn']]],
  ['neonexpworkload_82',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.html',1,'armnn']]],
  ['neonfillworkload_83',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.html',1,'armnn']]],
  ['neonfloordivworkload_84',['NeonFloorDivWorkload',['../classarmnn_1_1_neon_floor_div_workload.html',1,'armnn']]],
  ['neonfloorfloatworkload_85',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.html',1,'armnn']]],
  ['neonfullyconnectedworkload_86',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.html',1,'armnn']]],
  ['neonfusedworkload_87',['NeonFusedWorkload',['../classarmnn_1_1_neon_fused_workload.html',1,'armnn']]],
  ['neongatherndworkload_88',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.html',1,'armnn']]],
  ['neongatherworkload_89',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.html',1,'armnn']]],
  ['neoninstancenormalizationworkload_90',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.html',1,'armnn']]],
  ['neoninterceptorscheduler_91',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.html',1,'armnn']]],
  ['neonl2normalizationfloatworkload_92',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.html',1,'armnn']]],
  ['neonlayersupport_93',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.html',1,'armnn']]],
  ['neonlogicalandworkload_94',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.html',1,'armnn']]],
  ['neonlogicalnotworkload_95',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.html',1,'armnn']]],
  ['neonlogicalorworkload_96',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.html',1,'armnn']]],
  ['neonlogsoftmaxworkload_97',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.html',1,'armnn']]],
  ['neonlogworkload_98',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.html',1,'armnn']]],
  ['neonlstmfloatworkload_99',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.html',1,'armnn']]],
  ['neonmaximumworkload_100',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.html',1,'armnn']]],
  ['neonmeanworkload_101',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.html',1,'armnn']]],
  ['neonmemorymanager_102',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.html',1,'armnn']]],
  ['neonminimumworkload_103',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.html',1,'armnn']]],
  ['neonmultiplicationworkload_104',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.html',1,'armnn']]],
  ['neonnegworkload_105',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.html',1,'armnn']]],
  ['neonnormalizationfloatworkload_106',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.html',1,'armnn']]],
  ['neonpadworkload_107',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.html',1,'armnn']]],
  ['neonpermuteworkload_108',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.html',1,'armnn']]],
  ['neonpooling2dworkload_109',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.html',1,'armnn']]],
  ['neonpooling3dworkload_110',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.html',1,'armnn']]],
  ['neonpreluworkload_111',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.html',1,'armnn']]],
  ['neonqlstmworkload_112',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.html',1,'armnn']]],
  ['neonquantizedlstmworkload_113',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.html',1,'armnn']]],
  ['neonquantizeworkload_114',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.html',1,'armnn']]],
  ['neonrankworkload_115',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.html',1,'armnn']]],
  ['neonreduceworkload_116',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.html',1,'armnn']]],
  ['neonreshapeworkload_117',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.html',1,'armnn']]],
  ['neonresizeworkload_118',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.html',1,'armnn']]],
  ['neonreversev2workload_119',['NeonReverseV2Workload',['../classarmnn_1_1_neon_reverse_v2_workload.html',1,'armnn']]],
  ['neonrsqrtworkload_120',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.html',1,'armnn']]],
  ['neonsinworkload_121',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.html',1,'armnn']]],
  ['neonsliceworkload_122',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.html',1,'armnn']]],
  ['neonsoftmaxworkload_123',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.html',1,'armnn']]],
  ['neonspacetobatchndworkload_124',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.html',1,'armnn']]],
  ['neonspacetodepthworkload_125',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.html',1,'armnn']]],
  ['neonsplitterworkload_126',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.html',1,'armnn']]],
  ['neonsqrtworkload_127',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.html',1,'armnn']]],
  ['neonstackworkload_128',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.html',1,'armnn']]],
  ['neonstridedsliceworkload_129',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.html',1,'armnn']]],
  ['neonsubtensorhandle_130',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.html',1,'armnn']]],
  ['neonsubtractionworkload_131',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.html',1,'armnn']]],
  ['neontensordecorator_132',['NeonTensorDecorator',['../classarmnn_1_1_neon_tensor_decorator.html',1,'armnn']]],
  ['neontensorhandle_133',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.html',1,'armnn']]],
  ['neontensorhandledecorator_134',['NeonTensorHandleDecorator',['../classarmnn_1_1_neon_tensor_handle_decorator.html',1,'armnn']]],
  ['neontensorhandlefactory_135',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.html',1,'armnn']]],
  ['neontileworkload_136',['NeonTileWorkload',['../classarmnn_1_1_neon_tile_workload.html',1,'armnn']]],
  ['neontimer_137',['NeonTimer',['../classarmnn_1_1_neon_timer.html',1,'armnn']]],
  ['neontransposeconvolution2dworkload_138',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.html',1,'armnn']]],
  ['neontransposeworkload_139',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload_140',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload_141',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['neonworkloadfactory_142',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.html',1,'armnn']]],
  ['networkimpl_143',['NetworkImpl',['../classarmnn_1_1_network_impl.html',1,'armnn']]],
  ['nodecontent_144',['NodeContent',['../classarmnn_1_1_node_content.html',1,'armnn']]],
  ['normalizationdescriptor_145',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.html',1,'armnn']]],
  ['normalizationlayer_146',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.html',1,'armnn']]],
  ['normalizationqueuedescriptor_147',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.html',1,'armnn']]],
  ['nothrowstrategy_148',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.html',1,'armnn']]],
  ['nulldescriptor_149',['NullDescriptor',['../structarmnn_1_1_null_descriptor.html',1,'armnn']]],
  ['nullpointerexception_150',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.html',1,'armnn']]],
  ['nullworkload_151',['NullWorkload',['../classarmnn_1_1_null_workload.html',1,'armnn']]]
];
