var searchData=
[
  ['tensor_0',['Tensor',['../classarmnn_1_1_tensor.html',1,'armnn']]],
  ['tensorbufferarrayview_1',['TensorBufferArrayView',['../classarmnn_1_1_tensor_buffer_array_view.html',1,'armnn']]],
  ['tensorhandle_2',['TensorHandle',['../classarmnn_1_1_tensor_handle.html',1,'armnn']]],
  ['tensorhandlefactoryregistry_3',['TensorHandleFactoryRegistry',['../classarmnn_1_1_tensor_handle_factory_registry.html',1,'armnn']]],
  ['tensorinfo_4',['TensorInfo',['../classarmnn_1_1_tensor_info.html',1,'armnn']]],
  ['tensormemory_5',['TensorMemory',['../structarmnn_1_1_tensor_memory.html',1,'armnn']]],
  ['tensornumdimensionsarecorrect_6',['TensorNumDimensionsAreCorrect',['../structarmnn_1_1_tensor_num_dimensions_are_correct.html',1,'armnn']]],
  ['tensornumdimensionsaregreaterorequalto_7',['TensorNumDimensionsAreGreaterOrEqualTo',['../structarmnn_1_1_tensor_num_dimensions_are_greater_or_equal_to.html',1,'armnn']]],
  ['tensorshape_8',['TensorShape',['../classarmnn_1_1_tensor_shape.html',1,'armnn']]],
  ['tfliteparserimpl_9',['TfLiteParserImpl',['../classarmnn_tf_lite_parser_1_1_tf_lite_parser_impl.html',1,'armnnTfLiteParser']]],
  ['tfliteparseroptions_10',['TfLiteParserOptions',['../structarmnn_tf_lite_parser_1_1_i_tf_lite_parser_1_1_tf_lite_parser_options.html',1,'armnnTfLiteParser::ITfLiteParser']]],
  ['throwingstrategy_11',['ThrowingStrategy',['../structarmnn_1_1_throwing_strategy.html',1,'armnn']]],
  ['tiledescriptor_12',['TileDescriptor',['../structarmnn_1_1_tile_descriptor.html',1,'armnn']]],
  ['tilelayer_13',['TileLayer',['../classarmnn_1_1_tile_layer.html',1,'armnn']]],
  ['tilequeuedescriptor_14',['TileQueueDescriptor',['../structarmnn_1_1_tile_queue_descriptor.html',1,'armnn']]],
  ['timeoutexception_15',['TimeoutException',['../classarmnn_1_1_timeout_exception.html',1,'armnn']]],
  ['tosaassertsize_16',['TosaAssertSize',['../struct_tosa_assert_size.html',1,'']]],
  ['tosacontainercontainsthreetypes_17',['TosaContainerContainsThreeTypes',['../struct_tosa_container_contains_three_types.html',1,'']]],
  ['tosacontainercontainstwotypes_18',['TosaContainerContainsTwoTypes',['../struct_tosa_container_contains_two_types.html',1,'']]],
  ['tosaoperatorattributeofany_19',['TosaOperatorAttributeOfAny',['../struct_tosa_operator_attribute_of_any.html',1,'']]],
  ['tosarefbackend_20',['TosaRefBackend',['../classarmnn_1_1_tosa_ref_backend.html',1,'armnn']]],
  ['tosarefbaseworkload_21',['TosaRefBaseWorkload',['../classarmnn_1_1_tosa_ref_base_workload.html',1,'armnn']]],
  ['tosareflayersupport_22',['TosaRefLayerSupport',['../classarmnn_1_1_tosa_ref_layer_support.html',1,'armnn']]],
  ['tosarefmemorymanager_23',['TosaRefMemoryManager',['../classarmnn_1_1_tosa_ref_memory_manager.html',1,'armnn']]],
  ['tosarefprecompiledworkload_24',['TosaRefPreCompiledWorkload',['../classarmnn_1_1_tosa_ref_pre_compiled_workload.html',1,'armnn']]],
  ['tosareftensorhandle_25',['TosaRefTensorHandle',['../classarmnn_1_1_tosa_ref_tensor_handle.html',1,'armnn']]],
  ['tosareftensorhandlefactory_26',['TosaRefTensorHandleFactory',['../classarmnn_1_1_tosa_ref_tensor_handle_factory.html',1,'armnn']]],
  ['tosarefworkloadfactory_27',['TosaRefWorkloadFactory',['../classarmnn_1_1_tosa_ref_workload_factory.html',1,'armnn']]],
  ['tosatensornumdimensionswithinbounds_28',['TosaTensorNumDimensionsWithinBounds',['../struct_tosa_tensor_num_dimensions_within_bounds.html',1,'']]],
  ['tosatypeanyof_29',['TosaTypeAnyOf',['../struct_tosa_type_any_of.html',1,'']]],
  ['transformiterator_30',['TransformIterator',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transformiterator_3c_20decltype_28_26ptrcast_3c_20const_20inputlayer_20_3e_29_2c_20iterator_20_3e_31',['TransformIterator&lt; decltype(&amp;PtrCast&lt; const InputLayer &gt;), Iterator &gt;',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transformiterator_3c_20decltype_28_26ptrcast_3c_20const_20layer_20_3e_29_2c_20iterator_20_3e_32',['TransformIterator&lt; decltype(&amp;PtrCast&lt; const Layer &gt;), Iterator &gt;',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transformiterator_3c_20decltype_28_26ptrcast_3c_20const_20outputlayer_20_3e_29_2c_20iterator_20_3e_33',['TransformIterator&lt; decltype(&amp;PtrCast&lt; const OutputLayer &gt;), Iterator &gt;',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transposeasreshapeimpl_34',['TransposeAsReshapeImpl',['../classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.html',1,'armnn::optimizations']]],
  ['transposeconvolution2ddescriptor_35',['TransposeConvolution2dDescriptor',['../structarmnn_1_1_transpose_convolution2d_descriptor.html',1,'armnn']]],
  ['transposeconvolution2dlayer_36',['TransposeConvolution2dLayer',['../classarmnn_1_1_transpose_convolution2d_layer.html',1,'armnn']]],
  ['transposeconvolution2dqueuedescriptor_37',['TransposeConvolution2dQueueDescriptor',['../structarmnn_1_1_transpose_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['transposedescriptor_38',['TransposeDescriptor',['../structarmnn_1_1_transpose_descriptor.html',1,'armnn']]],
  ['transposelayer_39',['TransposeLayer',['../classarmnn_1_1_transpose_layer.html',1,'armnn']]],
  ['transposequeuedescriptor_40',['TransposeQueueDescriptor',['../structarmnn_1_1_transpose_queue_descriptor.html',1,'armnn']]],
  ['turboconvertconstdequantisationlayerstoconstlayersimpl_41',['TurboConvertConstDequantisationLayersToConstLayersImpl',['../classarmnn_1_1optimizations_1_1_turbo_convert_const_dequantisation_layers_to_const_layers_impl.html',1,'armnn::optimizations']]],
  ['typeanyof_42',['TypeAnyOf',['../structarmnn_1_1_type_any_of.html',1,'armnn']]],
  ['typediterator_43',['TypedIterator',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20float_2c_20decoder_3c_20float_20_3e_20_3e_44',['TypedIterator&lt; const float, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20half_2c_20decoder_3c_20float_20_3e_20_3e_45',['TypedIterator&lt; const Half, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int16_5ft_2c_20decoder_3c_20float_20_3e_20_3e_46',['TypedIterator&lt; const int16_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20float_20_3e_20_3e_47',['TypedIterator&lt; const int32_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20int32_5ft_20_3e_20_3e_48',['TypedIterator&lt; const int32_t, Decoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int64_5ft_2c_20decoder_3c_20double_5ft_20_3e_20_3e_49',['TypedIterator&lt; const int64_t, Decoder&lt; double_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_50',['TypedIterator&lt; const int8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20bool_20_3e_20_3e_51',['TypedIterator&lt; const uint8_t, Decoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_52',['TypedIterator&lt; const uint8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20float_2c_20encoder_3c_20float_20_3e_20_3e_53',['TypedIterator&lt; float, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20half_2c_20encoder_3c_20float_20_3e_20_3e_54',['TypedIterator&lt; Half, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int16_5ft_2c_20encoder_3c_20float_20_3e_20_3e_55',['TypedIterator&lt; int16_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20float_20_3e_20_3e_56',['TypedIterator&lt; int32_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20int32_5ft_20_3e_20_3e_57',['TypedIterator&lt; int32_t, Encoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int64_5ft_2c_20encoder_3c_20double_20_3e_20_3e_58',['TypedIterator&lt; int64_t, Encoder&lt; double &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_59',['TypedIterator&lt; int8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20bool_20_3e_20_3e_60',['TypedIterator&lt; uint8_t, Encoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_61',['TypedIterator&lt; uint8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typedworkload_62',['TypedWorkload',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20debugqueuedescriptor_2c_20datatype_20_3e_63',['TypedWorkload&lt; DebugQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20permutequeuedescriptor_2c_20datatype_20_3e_64',['TypedWorkload&lt; PermuteQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20queuedescriptor_2c_20armnn_3a_3adatatype_3a_3aboolean_20_3e_65',['TypedWorkload&lt; QueueDescriptor, armnn::DataType::Boolean &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20queuedescriptor_2c_20armnn_3a_3adatatype_3a_3afloat16_2c_20armnn_3a_3adatatype_3a_3afloat32_20_3e_66',['TypedWorkload&lt; QueueDescriptor, armnn::DataType::Float16, armnn::DataType::Float32 &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20queuedescriptor_2c_20armnn_3a_3adatatype_3a_3afloat32_20_3e_67',['TypedWorkload&lt; QueueDescriptor, armnn::DataType::Float32 &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20queuedescriptor_2c_20armnn_3a_3adatatype_3a_3aqasymmu8_20_3e_68',['TypedWorkload&lt; QueueDescriptor, armnn::DataType::QAsymmU8 &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20queuedescriptor_2c_20armnn_3a_3adatatype_3a_3asigned32_20_3e_69',['TypedWorkload&lt; QueueDescriptor, armnn::DataType::Signed32 &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20transposequeuedescriptor_2c_20datatype_20_3e_70',['TypedWorkload&lt; TransposeQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typeis_71',['TypeIs',['../structarmnn_1_1_type_is.html',1,'armnn']]],
  ['typenotperaxisquantized_72',['TypeNotPerAxisQuantized',['../structarmnn_1_1_type_not_per_axis_quantized.html',1,'armnn']]],
  ['typesareequal_73',['TypesAreEqual',['../structarmnn_1_1_types_are_equal.html',1,'armnn']]]
];
