var _base_iterator_8hpp =
[
    [ "BaseIterator", "classarmnn_1_1_base_iterator.html", "classarmnn_1_1_base_iterator" ],
    [ "Decoder< IType >", "classarmnn_1_1_decoder.html", "classarmnn_1_1_decoder" ],
    [ "Encoder< IType >", "classarmnn_1_1_encoder.html", "classarmnn_1_1_encoder" ],
    [ "TypedIterator< T, Base >", "classarmnn_1_1_typed_iterator.html", "classarmnn_1_1_typed_iterator" ],
    [ "QASymm8Decoder", "classarmnn_1_1_q_a_symm8_decoder.html", "classarmnn_1_1_q_a_symm8_decoder" ],
    [ "QASymmS8Decoder", "classarmnn_1_1_q_a_symm_s8_decoder.html", "classarmnn_1_1_q_a_symm_s8_decoder" ],
    [ "QSymmS8Decoder", "classarmnn_1_1_q_symm_s8_decoder.html", "classarmnn_1_1_q_symm_s8_decoder" ],
    [ "QSymm16Decoder", "classarmnn_1_1_q_symm16_decoder.html", "classarmnn_1_1_q_symm16_decoder" ],
    [ "Float16Decoder", "classarmnn_1_1_float16_decoder.html", "classarmnn_1_1_float16_decoder" ],
    [ "Float32Decoder", "classarmnn_1_1_float32_decoder.html", "classarmnn_1_1_float32_decoder" ],
    [ "ScaledInt32Decoder", "classarmnn_1_1_scaled_int32_decoder.html", "classarmnn_1_1_scaled_int32_decoder" ],
    [ "Int32Decoder", "classarmnn_1_1_int32_decoder.html", "classarmnn_1_1_int32_decoder" ],
    [ "Int32ToInt32tDecoder", "classarmnn_1_1_int32_to_int32t_decoder.html", "classarmnn_1_1_int32_to_int32t_decoder" ],
    [ "Int64Decoder", "classarmnn_1_1_int64_decoder.html", "classarmnn_1_1_int64_decoder" ],
    [ "BooleanDecoder", "classarmnn_1_1_boolean_decoder.html", "classarmnn_1_1_boolean_decoder" ],
    [ "BooleanDecoderBool", "classarmnn_1_1_boolean_decoder_bool.html", "classarmnn_1_1_boolean_decoder_bool" ],
    [ "QASymm8Encoder", "classarmnn_1_1_q_a_symm8_encoder.html", "classarmnn_1_1_q_a_symm8_encoder" ],
    [ "QASymmS8Encoder", "classarmnn_1_1_q_a_symm_s8_encoder.html", "classarmnn_1_1_q_a_symm_s8_encoder" ],
    [ "QSymmS8Encoder", "classarmnn_1_1_q_symm_s8_encoder.html", "classarmnn_1_1_q_symm_s8_encoder" ],
    [ "QSymm16Encoder", "classarmnn_1_1_q_symm16_encoder.html", "classarmnn_1_1_q_symm16_encoder" ],
    [ "Float16Encoder", "classarmnn_1_1_float16_encoder.html", "classarmnn_1_1_float16_encoder" ],
    [ "Float32Encoder", "classarmnn_1_1_float32_encoder.html", "classarmnn_1_1_float32_encoder" ],
    [ "Int32Encoder", "classarmnn_1_1_int32_encoder.html", "classarmnn_1_1_int32_encoder" ],
    [ "Int32ToInt32tEncoder", "classarmnn_1_1_int32_to_int32t_encoder.html", "classarmnn_1_1_int32_to_int32t_encoder" ],
    [ "Int64Encoder", "classarmnn_1_1_int64_encoder.html", "classarmnn_1_1_int64_encoder" ],
    [ "BooleanEncoder", "classarmnn_1_1_boolean_encoder.html", "classarmnn_1_1_boolean_encoder" ],
    [ "PerAxisIterator< T, Base >", "classarmnn_1_1_per_axis_iterator.html", "classarmnn_1_1_per_axis_iterator" ],
    [ "QSymm8PerAxisDecoder", "classarmnn_1_1_q_symm8_per_axis_decoder.html", "classarmnn_1_1_q_symm8_per_axis_decoder" ],
    [ "QSymm8PerAxisEncoder", "classarmnn_1_1_q_symm8_per_axis_encoder.html", "classarmnn_1_1_q_symm8_per_axis_encoder" ],
    [ "ScaledInt32PerAxisDecoder", "classarmnn_1_1_scaled_int32_per_axis_decoder.html", "classarmnn_1_1_scaled_int32_per_axis_decoder" ],
    [ "QSymm16PerAxisEncoder", "classarmnn_1_1_q_symm16_per_axis_encoder.html", "classarmnn_1_1_q_symm16_per_axis_encoder" ]
];