Arm NN: RefTensorHandleDecorator Class Reference
RefTensorHandleDecorator Class Reference
#include <RefTensorHandle.hpp>
Public Member Functions
RefTensorHandleDecorator (const TensorInfo &tensorInfo, const RefTensorHandle &parent)
~RefTensorHandleDecorator ()=default
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
const TensorInfo & GetTensorInfo () const
virtual MemorySourceFlags GetImportFlags () const override
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source) override
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source) override
Implementations must determine if this memory block can be imported.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo) override
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
void CopyOutTo (void *) const override
Testing support to be able to verify and set tensor data content.
void CopyInFrom (const void *) override
void Unimport () override
Unimport externally allocated memory.
virtual const void * Map (bool blocking=true) const=0
Map the tensor data for access.
void * Map (bool blocking=true)
Map the tensor data for access.
Public Member Functions inherited from RefTensorHandle
RefTensorHandle (const TensorInfo &tensorInfo, std::shared_ptr< RefMemoryManager > &memoryManager)
RefTensorHandle (const TensorInfo &tensorInfo)
RefTensorHandle (const TensorInfo &tensorInfo, const RefTensorHandle &parent)
~RefTensorHandle ()
const TensorInfo & GetTensorInfo () const
virtual const void * Map (bool blocking=true) const=0
Map the tensor data for access.
void * Map (bool blocking=true)
Map the tensor data for access.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
Detailed Description
Definition at line 84 of file RefTensorHandle.hpp.
Constructor & Destructor Documentation
RefTensorHandleDecorator()
RefTensorHandleDecorator (const TensorInfo & tensorInfo, const RefTensorHandle & parent)
Definition at line 160 of file RefTensorHandle.cpp.
 : RefTensorHandle(tensorInfo)
 , m_TensorInfo(tensorInfo)
 , m_Parent(parent)
 {
 }
~RefTensorHandleDecorator()
~RefTensorHandleDecorator () default
Member Function Documentation
Allocate()
void Allocate () override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Reimplemented from RefTensorHandle.
Definition at line 171 of file RefTensorHandle.cpp.
 {
 }
CanBeImported()
bool CanBeImported (void * memory, MemorySource source) override virtual
Implementations must determine if this memory block can be imported.
This might be based on alignment or memory source type.
Returns
true if this memory can be imported.
false by default, cannot be imported.
Reimplemented from RefTensorHandle.
Definition at line 190 of file RefTensorHandle.cpp.
 {
     return false;
 }
CopyInFrom()
void CopyInFrom (const void *) inline override virtual
Reimplemented from RefTensorHandle.
Definition at line 146 of file RefTensorHandle.hpp.
     {};
CopyOutTo()
void CopyOutTo (void *) const inline override virtual
Testing support to be able to verify and set tensor data content.
Reimplemented from RefTensorHandle.
Definition at line 143 of file RefTensorHandle.hpp.
     {};
DecorateTensorHandle()
std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo & tensorInfo) override virtual
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Parameters
tensorInfo the overidden TensorInfo.
Reimplemented from RefTensorHandle.
Definition at line 195 of file RefTensorHandle.cpp.
 {
     return nullptr;
 }
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Get flags describing supported import sources.
Reimplemented from RefTensorHandle.
Definition at line 180 of file RefTensorHandle.cpp.
 {
     return static_cast<MemorySourceFlags>(MemorySource::Malloc);
 }
References armnn::Malloc.
GetParent()
virtual ITensorHandle* GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Reimplemented from RefTensorHandle.
Definition at line 95 of file RefTensorHandle.hpp.
     {
         return nullptr;
     }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Reimplemented from RefTensorHandle.
Definition at line 111 of file RefTensorHandle.hpp.
     {
         return m_TensorInfo.GetShape();
     }
References TensorInfo::GetShape().
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Reimplemented from RefTensorHandle.
Definition at line 106 of file RefTensorHandle.hpp.
     {
         return GetUnpaddedTensorStrides(m_TensorInfo);
     }
References armnn::GetUnpaddedTensorStrides().
GetTensorInfo()
const TensorInfo& GetTensorInfo () const inline
Definition at line 116 of file RefTensorHandle.hpp.
     {
         return m_TensorInfo;
     }
Import()
bool Import (void * memory, MemorySource source) override virtual
Import externally allocated memory.
Parameters
memory base address of the memory being imported.
source source of the allocation for the memory being imported.
Returns
true on success or false on failure
Reimplemented from RefTensorHandle.
Definition at line 185 of file RefTensorHandle.cpp.
 {
     return false;
 }
Manage()
void Manage () override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Reimplemented from RefTensorHandle.
Definition at line 167 of file RefTensorHandle.cpp.
 {
 }
Map() [1/4]
void* Map inline
Map the tensor data for access.
Must be paired with call to Unmap().
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Definition at line 44 of file ITensorHandle.hpp.
     {
         return const_cast<void*>(static_cast<const ITensorHandle*>(this)->Map(blocking));
     }
Map() [2/4]
void* Map (bool blocking = true) inline
Map the tensor data for access.
Must be paired with call to Unmap().
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Definition at line 131 of file RefTensorHandle.hpp.
     {
         return const_cast<void*>(static_cast<const ITensorHandle*>(this)->Map(blocking));
     }
References RefTensorHandleDecorator::Map().
Map() [3/4]
virtual const void* Map
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Map() [4/4]
const void * Map (bool blocking) const override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Reimplemented from RefTensorHandle.
Definition at line 175 of file RefTensorHandle.cpp.
 {
     return m_Parent.Map(unused);
 }
References RefTensorHandle::Map().
Referenced by RefTensorHandleDecorator::Map().
Unimport()
void Unimport () inline override virtual
Unimport externally allocated memory.
Reimplemented from ITensorHandle.
Definition at line 150 of file RefTensorHandle.hpp.
     {};
Unmap() [1/2]
void Unmap () inline
Unmap the tensor data that was previously mapped with call to Map().
Definition at line 137 of file RefTensorHandle.hpp.
     {
         return static_cast<const ITensorHandle*>(this)->Unmap();
     }
References RefTensorHandleDecorator::Unmap().
Unmap() [2/2]
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Reimplemented from RefTensorHandle.
Definition at line 103 of file RefTensorHandle.hpp.
     {}
Referenced by RefTensorHandleDecorator::Unmap().
The documentation for this class was generated from the following files:
src/backends/reference/RefTensorHandle.hpp
src/backends/reference/RefTensorHandle.cpp