ArmNN: ClNegWorkload Class Reference
ClNegWorkload Class Reference
#include <ClNegWorkload.hpp>
Public Member Functions
ClNegWorkload (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
virtual void Execute () const override
Public Member Functions inherited from ClBaseWorkload< ElementwiseUnaryQueueDescriptor >
ClBaseWorkload (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< ElementwiseUnaryQueueDescriptor >
BaseWorkload (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const ElementwiseUnaryQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual arm::pipe::ProfilingGuid GetGuid () const =0
virtual bool SupportsTensorHandleReplacement () const =0
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< ElementwiseUnaryQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< ElementwiseUnaryQueueDescriptor >
ElementwiseUnaryQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 18 of file ClNegWorkload.hpp.
Constructor & Destructor Documentation
ClNegWorkload()
ClNegWorkload (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 26 of file ClNegWorkload.cpp.
     : ClBaseWorkload<ElementwiseUnaryQueueDescriptor>(descriptor, info)
 {
     m_Data.ValidateInputsOutputs("ClNegWorkload", 1, 1);
     arm_compute::ICLTensor& input  = PolymorphicDowncast<ClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = PolymorphicDowncast<ClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     {
         ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClNegWorkload_configure");
         m_NegLayer.configure(clCompileContext, &input, &output);
     }
 }
References ARMNN_SCOPED_PROFILING_EVENT, armnn::info, BaseWorkload< ElementwiseUnaryQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, armnn::Undefined, and QueueDescriptor::ValidateInputsOutputs().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 42 of file ClNegWorkload.cpp.
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClNegWorkload_Execute", this->GetGuid());
     RunClFunction(m_NegLayer, CHECK_LOCATION());
 }
References ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< ElementwiseUnaryQueueDescriptor >::GetGuid(), and armnn::RunClFunction().
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClNegWorkload.hpp
src/backends/cl/workloads/ClNegWorkload.cpp