ArmNN: DeviceSpec Class Reference
DeviceSpec Class Reference
#include <DeviceSpec.hpp>
Public Member Functions
DeviceSpec ()
DeviceSpec (const BackendIdSet &supportedBackends)
virtual ~DeviceSpec ()
virtual const BackendIdSet & GetSupportedBackends () const override
void AddSupportedBackends (const BackendIdSet &backendIds, bool isDynamic=false)
void ClearDynamicBackends ()
const BackendIdSet & GetDynamicBackends () const
Additional Inherited Members
Protected Member Functions inherited from IDeviceSpec
IDeviceSpec ()
virtual ~IDeviceSpec ()
Detailed Description
Definition at line 14 of file DeviceSpec.hpp.
Constructor & Destructor Documentation
DeviceSpec() [1/2]
DeviceSpec () inline
Definition at line 17 of file DeviceSpec.hpp.
     {}
DeviceSpec() [2/2]
DeviceSpec (const BackendIdSet & supportedBackends) inline
Definition at line 20 of file DeviceSpec.hpp.
         : m_SupportedBackends{supportedBackends} {}
~DeviceSpec()
virtual ~DeviceSpec () inline virtual
Definition at line 23 of file DeviceSpec.hpp.
 {}
Member Function Documentation
AddSupportedBackends()
void AddSupportedBackends (const BackendIdSet & backendIds, bool isDynamic = false) inline
Definition at line 30 of file DeviceSpec.hpp.
     {
         m_SupportedBackends.insert(backendIds.begin(), backendIds.end());
         if (isDynamic)
         {
             m_DynamicBackends.insert(backendIds.begin(), backendIds.end());
         }
     }
ClearDynamicBackends()
void ClearDynamicBackends () inline
Definition at line 39 of file DeviceSpec.hpp.
     {
         for (const auto& id : m_DynamicBackends)
         {
             m_SupportedBackends.erase(id);
         }
         m_DynamicBackends.clear();
     }
Referenced by RuntimeImpl::RuntimeImpl(), and RuntimeImpl::~RuntimeImpl().
GetDynamicBackends()
const BackendIdSet& GetDynamicBackends () const inline
Definition at line 48 of file DeviceSpec.hpp.
     {
         return m_DynamicBackends;
     }
Referenced by RuntimeImpl::RuntimeImpl(), and RuntimeImpl::~RuntimeImpl().
GetSupportedBackends()
virtual const BackendIdSet& GetSupportedBackends () const inline override virtual
Implements IDeviceSpec.
Definition at line 25 of file DeviceSpec.hpp.
     {
         return m_SupportedBackends;
     }
The documentation for this class was generated from the following file:
src/armnn/DeviceSpec.hpp