ArmNN: PermuteAsReshapeImpl Class Reference
PermuteAsReshapeImpl Class Reference
#include <PermuteAsReshape.hpp>
Public Member Functions
void Run (Graph &graph, PermuteLayer &permute) const
Run for every PermuteLayer. Replaces it with a ReshapeLayer if they are equivalent.
Protected Member Functions
PermuteAsReshapeImpl ()=default
~PermuteAsReshapeImpl ()=default
Detailed Description
Definition at line 14 of file PermuteAsReshape.hpp.
Constructor & Destructor Documentation
PermuteAsReshapeImpl()
PermuteAsReshapeImpl () protected default
~PermuteAsReshapeImpl()
~PermuteAsReshapeImpl () protected default
Member Function Documentation
Run()
void Run (Graph & graph, PermuteLayer & permute) const inline
Run for every PermuteLayer. Replaces it with a ReshapeLayer if they are equivalent.
Definition at line 18 of file PermuteAsReshape.hpp.
     {
         if (IsReshape(permute))
         {
             const TensorInfo& outInfo = permute.GetOutputHandler().GetTensorInfo();
             const std::string name = std::string("as_reshape-") + permute.GetName();
             const ReshapeDescriptor descriptor{outInfo.GetShape()};
             // Inserts NewLayer so layers don't need to be re-sorted.
             auto reshape = graph.InsertNewLayer<ReshapeLayer>(permute.GetInputSlot(0), descriptor, name.c_str());
             // Bypass permute. It will be deleted since it's left unconnected.
             permute.GetOutputSlot().MoveAllConnections(reshape->GetOutputSlot());
         }
     }
References Layer::GetInputSlot(), Layer::GetName(), Layer::GetOutputHandler(), Layer::GetOutputSlot(), TensorInfo::GetShape(), OutputHandler::GetTensorInfo(), Graph::InsertNewLayer(), and OutputSlot::MoveAllConnections().
The documentation for this class was generated from the following file:
src/armnn/optimizations/PermuteAsReshape.hpp