ArmNN: DotDefaults Class Reference
DotDefaults Class Reference
#include <DotSerializer.hpp>
Public Member Functions
DotDefaults (std::ostream &stream, const char *type)
~DotDefaults ()
DotAttributeSet & GetAttributeSet ()
Public Member Functions inherited from DotBase
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 114 of file DotSerializer.hpp.
Constructor & Destructor Documentation
DotDefaults()
DotDefaults (std::ostream & stream, const char * type) explicit
Definition at line 208 of file DotSerializer.cpp.
     : DotBase(stream)
 {
     std::stringstream ss;
     ss << Indent(4) << type;
     GetStream() << ss.str() << " ";
     m_Attributes = std::make_unique<DotAttributeSet>(stream);
 }
References DotBase::GetStream().
~DotDefaults()
~DotDefaults ()
Definition at line 218 of file DotSerializer.cpp.
 {
     m_Attributes.reset(nullptr);
     GetStream() << ";" << std::endl;
 }
References DotBase::GetStream().
Member Function Documentation
GetAttributeSet()
DotAttributeSet& GetAttributeSet () inline
Definition at line 120 of file DotSerializer.hpp.
 { return *m_Attributes.get(); }
Referenced by Graph::SerializeToDot().
The documentation for this class was generated from the following files:
src/armnnUtils/DotSerializer.hpp
src/armnnUtils/DotSerializer.cpp