ArmNN: ProfilingDetails Class Reference
ProfilingDetails Class Reference
ProfilingDetails class records any details associated with the operator and passes on for outputting to the user.
#include <ProfilingDetails.hpp>
Public Member Functions
ProfilingDetails ()
Constructor.
~ProfilingDetails () noexcept
Destructor.
template<typename DescriptorType >
void AddDetailsToString (const std::string &workloadName, const DescriptorType &desc, const WorkloadInfo &infos, const arm::pipe::ProfilingGuid guid)
Add to the ProfilingDetails.
std::string GetProfilingDetails () const
Get the ProfilingDetails.
bool DetailsExist ()
Public Member Functions inherited from JsonUtils
JsonUtils (std::ostream &outputStream)
void PrintTabs ()
void DecrementNumberOfTabs ()
void IncrementNumberOfTabs ()
void PrintNewLine ()
void PrintFooter ()
void PrintHeader ()
void PrintArmNNHeader ()
void PrintSeparator ()
Detailed Description
ProfilingDetails class records any details associated with the operator and passes on for outputting to the user.
Definition at line 21 of file ProfilingDetails.hpp.
Constructor & Destructor Documentation
ProfilingDetails()
ProfilingDetails () inline
Constructor.
Definition at line 25 of file ProfilingDetails.hpp.
                        : JsonUtils(m_ProfilingDetails), m_DetailsExist(false)
     {}
~ProfilingDetails()
~ProfilingDetails () inline noexcept
Destructor.
Definition at line 29 of file ProfilingDetails.hpp.
     {}
Member Function Documentation
AddDetailsToString()
void AddDetailsToString (const std::string & workloadName, const DescriptorType & desc, const WorkloadInfo & infos, const arm::pipe::ProfilingGuid guid) inline
Add to the ProfilingDetails.
Definition at line 34 of file ProfilingDetails.hpp.
     {
         // Once details exist, we can assume we're on the second iteration of details
         if (m_DetailsExist)
         {
             PrintSeparator();
             PrintNewLine();
         }
         PrintHeader();
         PrintTabs();
         m_ProfilingDetails << std::quoted("Name") << ": " << std::quoted(workloadName);
         PrintSeparator();
         PrintNewLine();
         PrintTabs();
         m_ProfilingDetails << std::quoted("GUID") << ": " << std::quoted(std::to_string(guid));
         // From this point onwards everything is potentially optional so we must be careful of separators and new lines.
         // Print tensor infos and related data types
         if (!infos.m_InputTensorInfos.empty())
         {
             PrintSeparator();
             PrintNewLine();
             // Only add separator and new line if there is an output tensor info.
             PrintInfos(infos.m_InputTensorInfos, "Input", !infos.m_OutputTensorInfos.empty());
         }
         if (!infos.m_OutputTensorInfos.empty())
         {
             // Don't add a separator as we don't know what's next.
             PrintInfos(infos.m_OutputTensorInfos, "Output", false);
         }
         if (infos.m_BiasTensorInfo.has_value())
         {
             PrintSeparator();
             PrintNewLine();
             PrintInfo(infos.m_BiasTensorInfo.value(), "Bias", false);
         }
         if (infos.m_WeightsTensorInfo.has_value())
         {
             PrintSeparator();
             PrintNewLine();
             PrintInfo(infos.m_WeightsTensorInfo.value(), "Weights", false);
         }
         if (infos.m_ConvolutionMethod.has_value())
         {
             PrintSeparator();
             PrintNewLine();
             PrintTabs();
             m_ProfilingDetails << std::quoted("Convolution Method") << ": "
                                << std::quoted(infos.m_ConvolutionMethod.value());
         }
         ParameterStringifyFunction extractParams = [this](const std::string& name, const std::string& value) {
             // Always begin with a separator and new line.
             PrintSeparator();
             PrintNewLine();
             PrintTabs();
             m_ProfilingDetails << std::quoted(name) << " : " << std::quoted(value);
         };
         StringifyLayerParameters<DescriptorType>::Serialize(extractParams, desc);
         PrintNewLine();
         PrintFooter();
         m_DetailsExist = true;
     }
References OptionalBase::has_value(), WorkloadInfo::m_BiasTensorInfo, WorkloadInfo::m_ConvolutionMethod, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, WorkloadInfo::m_WeightsTensorInfo, JsonUtils::PrintFooter(), JsonUtils::PrintHeader(), JsonUtils::PrintNewLine(), JsonUtils::PrintSeparator(), JsonUtils::PrintTabs(), StringifyLayerParameters< LayerParameter >::Serialize(), and OptionalReferenceSwitch< IsReference, T >::value().
DetailsExist()
bool DetailsExist () inline
Definition at line 118 of file ProfilingDetails.hpp.
     {
         return m_DetailsExist;
     }
GetProfilingDetails()
std::string GetProfilingDetails () const inline
Get the ProfilingDetails.
Returns
the ProfilingDetails
Definition at line 113 of file ProfilingDetails.hpp.
     {
         return m_ProfilingDetails.str();
     }
The documentation for this class was generated from the following file:
src/armnn/ProfilingDetails.hpp