Arm NN: LayerInputHandle Class Reference
LayerInputHandle Class Reference
#include <ConversionUtils.hpp>
Public Member Functions
LayerInputHandle ()
LayerInputHandle (bool valid, armnn::IOutputSlot *outputSlot, armnn::TensorInfo tensorInfo)
bool IsValid () const
void Connect (armnn::IInputSlot &inputSlot)
void Disconnect (armnn::IInputSlot &inputSlot)
const armnn::TensorInfo & GetTensorInfo () const
void SanitizeQuantizationScale (LayerInputHandle &weight, LayerInputHandle &input)
armnn::IOutputSlot * GetOutputSlot () const
Detailed Description
Definition at line 66 of file ConversionUtils.hpp.
Constructor & Destructor Documentation
LayerInputHandle() [1/2]
LayerInputHandle ()
Definition at line 16 of file ConversionUtils.cpp.
     : m_OutputSlot(nullptr)
     , m_Valid(false)
 {}
LayerInputHandle() [2/2]
LayerInputHandle (bool valid, armnn::IOutputSlot * outputSlot, armnn::TensorInfo tensorInfo)
Definition at line 21 of file ConversionUtils.cpp.
     : m_OutputSlot(outputSlot)
     , m_Valid(valid)
     , m_TensorInfo(tensorInfo)
 {}
Member Function Documentation
Connect()
void Connect (armnn::IInputSlot & inputSlot)
Definition at line 32 of file ConversionUtils.cpp.
 {
     ARMNN_ASSERT(IsValid());
     if (m_OutputSlot)
     {
         m_OutputSlot->Connect(inputSlot);
     }
 }
References ARMNN_ASSERT, IOutputSlot::Connect(), and LayerInputHandle::IsValid().
Referenced by armnn_driver::ConvertPooling2d(), armnn_driver::ConvertReduce(), and armnn_driver::ConvertToActivation().
Disconnect()
void Disconnect (armnn::IInputSlot & inputSlot)
Definition at line 41 of file ConversionUtils.cpp.
 {
     ARMNN_ASSERT(IsValid());
     if (m_OutputSlot)
     {
         m_OutputSlot->Disconnect(inputSlot);
     }
 }
References ARMNN_ASSERT, IOutputSlot::Disconnect(), and LayerInputHandle::IsValid().
GetOutputSlot()
armnn::IOutputSlot * GetOutputSlot () const
Definition at line 70 of file ConversionUtils.cpp.
 {
     return m_OutputSlot;
 }
GetTensorInfo()
const armnn::TensorInfo & GetTensorInfo () const
Definition at line 50 of file ConversionUtils.cpp.
 {
     return m_TensorInfo;
 }
Referenced by armnn_driver::ConvertPooling2d(), armnn_driver::ConvertReduce(), armnn_driver::ConvertToActivation(), and LayerInputHandle::SanitizeQuantizationScale().
IsValid()
bool IsValid () const
Definition at line 27 of file ConversionUtils.cpp.
 {
     return m_Valid;
 }
Referenced by LayerInputHandle::Connect(), armnn_driver::ConvertPooling2d(), armnn_driver::ConvertReduce(), armnn_driver::ConvertToActivation(), and LayerInputHandle::Disconnect().
SanitizeQuantizationScale()
void SanitizeQuantizationScale (LayerInputHandle & weight, LayerInputHandle & input)
Definition at line 55 of file ConversionUtils.cpp.
 {
     if (m_OutputSlot)
     {
         armnn::TensorInfo weightInfo = weight.GetTensorInfo();
         armnn::TensorInfo inputInfo = input.GetTensorInfo();
         armnn::TensorInfo biasInfo = GetTensorInfo();
         SanitizeBiasQuantizationScale(biasInfo, weightInfo, inputInfo);
         m_TensorInfo = biasInfo;
         m_OutputSlot->SetTensorInfo(biasInfo);
     }
 }
References LayerInputHandle::GetTensorInfo(), and IOutputSlot::SetTensorInfo().
The documentation for this class was generated from the following files:
shim/sl/canonical/ConversionUtils.hpp
shim/sl/canonical/ConversionUtils.cpp