ArmNN: sdb Namespace Reference
sdb Namespace Reference
Classes
class SampleDynamicAdditionWorkload
class SampleDynamicLayerSupport
class SampleDynamicTensorHandleFactory
class SampleDynamicWorkloadFactory
class SampleMemoryManager
class SampleTensorHandle
Typedefs
using FactoryId = armnn::ITensorHandleFactory::FactoryId
Functions
const armnn::TensorInfo & GetTensorInfo (const armnn::ITensorHandle *tensorHandle)
const float * GetInputTensorData (unsigned int idx, const armnn::AdditionQueueDescriptor &data)
float * GetOutputTensorData (unsigned int idx, const armnn::AdditionQueueDescriptor &data)
constexpr const char * SampleDynamicBackendId ()
constexpr const char * SampleDynamicTensorHandleFactoryId ()
Typedef Documentation
FactoryId
using FactoryId = armnn::ITensorHandleFactory::FactoryId
Definition at line 14 of file SampleDynamicTensorHandleFactory.cpp.
Function Documentation
GetInputTensorData()
const float* sdb::GetInputTensorData (unsigned int idx, const armnn::AdditionQueueDescriptor & data)
Definition at line 22 of file SampleDynamicAdditionWorkload.cpp.
 {
     const armnn::ITensorHandle* tensorHandle = data.m_Inputs[idx];
     return reinterpret_cast<const float*>(tensorHandle->Map());
 }
References QueueDescriptor::m_Inputs, and ITensorHandle::Map().
Referenced by SampleDynamicAdditionWorkload::Execute().
GetOutputTensorData()
float* sdb::GetOutputTensorData (unsigned int idx, const armnn::AdditionQueueDescriptor & data)
Definition at line 28 of file SampleDynamicAdditionWorkload.cpp.
 {
     armnn::ITensorHandle* tensorHandle = data.m_Outputs[idx];
     return reinterpret_cast<float*>(tensorHandle->Map());
 }
References QueueDescriptor::m_Outputs, and ITensorHandle::Map().
Referenced by SampleDynamicAdditionWorkload::Execute().
GetTensorInfo()
const armnn::TensorInfo& sdb::GetTensorInfo (const armnn::ITensorHandle * tensorHandle) inline
Definition at line 14 of file SampleDynamicAdditionWorkload.cpp.
 {
     // We know that reference workloads use RefTensorHandles for inputs and outputs
     const SampleTensorHandle* sampleTensorHandle =
         static_cast<const SampleTensorHandle*>(tensorHandle);
     return sampleTensorHandle->GetTensorInfo();
 }
References SampleTensorHandle::GetTensorInfo().
Referenced by SampleDynamicAdditionWorkload::Execute().
SampleDynamicBackendId()
constexpr const char* sdb::SampleDynamicBackendId () constexpr
Definition at line 18 of file SampleDynamicBackend.cpp.
 { return "SampleDynamic"; }
SampleDynamicTensorHandleFactoryId()
constexpr const char* sdb::SampleDynamicTensorHandleFactoryId () constexpr
Definition at line 15 of file SampleDynamicTensorHandleFactory.hpp.
 { return "Arm/SampleDynamic/TensorHandleFactory"; }
Referenced by SampleDynamicTensorHandleFactory::GetIdStatic().