Arm NN: armnnUtils::Filesystem Namespace Reference
armnnUtils::Filesystem Namespace Reference
Typedefs
using FileContents = std::string
Functions
fs::path NamedTempFile (const char *fileName)
Returns a path to a file in the system temporary folder. If the file existed it will be deleted.
std::string CreateDirectory (std::string sPath)
Returns full path to temporary folder.
FileContents ReadFileContentsIntoString (const std::string &path)
void RemoveDirectoryAndContents (const std::string &path)
Remove a directory and its contents.
Typedef Documentation
FileContents
using FileContents = std::string
Definition at line 24 of file Filesystem.hpp.
Function Documentation
CreateDirectory()
std::string CreateDirectory (std::string path)
Returns full path to temporary folder.
Construct a temporary directory.
Given a specified directory name construct a path in the system temporary directory. If the directory already exists, it is deleted, otherwise create it. This could throw filesystem_error exceptions.
Parameters
path is the path required in the temporary directory.
Returns
path consisting of system temporary directory.
Exceptions
RuntimeException if the directory cannot be created or exists but cannot be removed.
Definition at line 47 of file Filesystem.cpp.
 {
     // This line is very unlikely to throw an exception.
     fs::path tmpDir = fs::temp_directory_path();
     std::string full_path = tmpDir.generic_string() + path;
     // This could throw a file permission exception.
     RemoveDirectoryAndContents(full_path);
 #if defined(_WIN32)
     result = _mkdir(full_path.c_str()); // can be used on Windows
     armnn::ConditionalThrow<armnn::RuntimeException>((result == 0), "Was unable to create temporary directory");
 #else
     try
     {
         if(!fs::create_directory(full_path))
         {
             throw armnn::RuntimeException("Unable to create directory: " + full_path);
         }
     }
     catch (const std::system_error& e)
     {
         std::string error = "Unable to create directory. Reason: ";
         error.append(e.what());
         throw armnn::RuntimeException(error);
     }
 #endif
     return full_path + "/";
 }
References armnn::error, and RemoveDirectoryAndContents().
Referenced by armnn::Optimize().
NamedTempFile()
fs::path NamedTempFile (const char * fileName)
Returns a path to a file in the system temporary folder. If the file existed it will be deleted.
Construct a temporary file name.
Given a specified file name construct a path to that file in the system temporary directory. If the file already exists it is deleted. This could throw filesystem_error exceptions.
Parameters
fileName the file name required in the temporary directory.
Returns
path consisting of system temporary directory and file name.
Definition at line 25 of file Filesystem.cpp.
 {
     fs::path tmpDir = fs::temp_directory_path();
     fs::path namedTempFile{tmpDir / fileName};
     if (fs::exists(namedTempFile))
     {
         fs::remove(namedTempFile);
     }
     return namedTempFile;
 }
Referenced by TEST_SUITE().
ReadFileContentsIntoString()
FileContents ReadFileContentsIntoString (const std::string & path)
Definition at line 102 of file Filesystem.cpp.
{
     if (!fs::exists(path))
     {
         throw armnn::RuntimeException("Path does not exist: " + path);
     }
     std::ifstream input_file(path);
     armnn::ConditionalThrow<armnn::RuntimeException>((input_file.is_open()), "Could not read file contents");
     return FileContents((std::istreambuf_iterator<char>(input_file)), std::istreambuf_iterator<char>());
 }
RemoveDirectoryAndContents()
void RemoveDirectoryAndContents (const std::string & path)
Remove a directory and its contents.
Given a directory path delete it's contents and the directory. If the specified directory doesn't exist this does nothing. If any item cannot be removed this will throw a RuntimeException.
Parameters
full_path
Definition at line 84 of file Filesystem.cpp.
 {
     if (fs::exists(path))
     {
         try
         {
             // This could throw an exception on a multi-user system.
             fs::remove_all(path);
         }
         catch (const std::system_error& e)
         {
             std::string error = "Directory exists and cannot be removed. Reason: ";
             error.append(e.what());
             throw armnn::RuntimeException(error);
         }
     }
 }
References armnn::error.
Referenced by CreateDirectory().