Arm NN: JsonChildObject Struct Reference
JsonChildObject Struct Reference
#include <JsonPrinter.hpp>
Public Member Functions
JsonChildObject (const std::string &label)
JsonChildObject (const JsonChildObject &)=default
void AddMeasurement (const double measurement)
void SetAndParseDetails (std::string layerDetailsStr)
void SetGuid (arm::pipe::ProfilingGuid guid)
void AddChild (const JsonChildObject &childObject)
JsonChildObject & GetChild (const unsigned int index)
void SetUnit (const Measurement::Unit unit)
size_t NumChildren () const
void SetType (JsonObjectType type)
JsonObjectType GetType () const
void EnableDetailsOnly ()
bool IsDetailsOnlyEnabled () const
~JsonChildObject ()=default
Public Attributes
std::string m_Label
Measurement::Unit m_Unit
JsonObjectType m_Type
Optional< arm::pipe::ProfilingGuid > m_Guid
std::vector< double > m_Measurements
std::vector< std::string > m_LayerDetailsList
std::vector< JsonChildObject > m_Children
Detailed Description
Definition at line 27 of file JsonPrinter.hpp.
Constructor & Destructor Documentation
JsonChildObject() [1/2]
JsonChildObject (const std::string & label) inline
Definition at line 30 of file JsonPrinter.hpp.
         : m_Label(label),
           m_Unit(Measurement::Unit::TIME_MS),
           m_Type(JsonObjectType::Event),
           m_Guid(armnn::EmptyOptional()),
           m_DetailsOnly(false)
     {}
JsonChildObject() [2/2]
JsonChildObject (const JsonChildObject &) default
~JsonChildObject()
~JsonChildObject () default
Member Function Documentation
AddChild()
void AddChild (const JsonChildObject & childObject) inline
Definition at line 59 of file JsonPrinter.hpp.
     {
         m_Children.push_back(childObject);
     }
References JsonChildObject::m_Children.
Referenced by armnn::ExtractJsonObjects().
AddMeasurement()
void AddMeasurement (const double measurement) inline
Definition at line 39 of file JsonPrinter.hpp.
     {
         m_Measurements.push_back(measurement);
     }
References JsonChildObject::m_Measurements.
Referenced by armnn::ExtractJsonObjects().
EnableDetailsOnly()
void EnableDetailsOnly () inline
Definition at line 89 of file JsonPrinter.hpp.
     {
         m_DetailsOnly = true;
     }
Referenced by ProfilerImpl::Print().
GetChild()
JsonChildObject& GetChild (const unsigned int index) inline
Definition at line 64 of file JsonPrinter.hpp.
     {
         return m_Children[index];
     }
References JsonChildObject::m_Children.
Referenced by armnn::ExtractJsonObjects().
GetType()
JsonObjectType GetType () const inline
Definition at line 84 of file JsonPrinter.hpp.
     {
         return m_Type;
     }
References JsonChildObject::m_Type.
IsDetailsOnlyEnabled()
bool IsDetailsOnlyEnabled () const inline
Definition at line 94 of file JsonPrinter.hpp.
     {
         return m_DetailsOnly;
     }
NumChildren()
size_t NumChildren () const inline
Definition at line 74 of file JsonPrinter.hpp.
     {
         return m_Children.size();
     }
References JsonChildObject::m_Children.
Referenced by armnn::ExtractJsonObjects().
SetAndParseDetails()
void SetAndParseDetails (std::string layerDetailsStr) inline
Definition at line 44 of file JsonPrinter.hpp.
     {
         std::stringstream layerDetails(layerDetailsStr);
         std::string stringLine;
         while (std::getline(layerDetails, stringLine, '\n'))
         {
             m_LayerDetailsList.push_back(stringLine);
         }
     }
References JsonChildObject::m_LayerDetailsList.
Referenced by armnn::ConfigureDetailsObject().
SetGuid()
void SetGuid (arm::pipe::ProfilingGuid guid) inline
Definition at line 54 of file JsonPrinter.hpp.
     {
         m_Guid = Optional<arm::pipe::ProfilingGuid>(guid);
     }
References JsonChildObject::m_Guid.
Referenced by armnn::ExtractJsonObjects().
SetType()
void SetType (JsonObjectType type) inline
Definition at line 79 of file JsonPrinter.hpp.
     {
         m_Type = type;
     }
References JsonChildObject::m_Type.
Referenced by armnn::ConfigureDetailsObject(), and armnn::ExtractJsonObjects().
SetUnit()
void SetUnit (const Measurement::Unit unit) inline
Definition at line 69 of file JsonPrinter.hpp.
     {
         m_Unit = unit;
     }
References JsonChildObject::m_Unit.
Referenced by armnn::ExtractJsonObjects().
Member Data Documentation
m_Children
std::vector<JsonChildObject> m_Children
Definition at line 107 of file JsonPrinter.hpp.
Referenced by JsonChildObject::AddChild(), armnn::ExtractJsonObjects(), JsonChildObject::GetChild(), and JsonChildObject::NumChildren().
m_Guid
Optional<arm::pipe::ProfilingGuid> m_Guid
Definition at line 104 of file JsonPrinter.hpp.
Referenced by JsonChildObject::SetGuid().
m_Label
std::string m_Label
Definition at line 101 of file JsonPrinter.hpp.
m_LayerDetailsList
std::vector<std::string> m_LayerDetailsList
Definition at line 106 of file JsonPrinter.hpp.
Referenced by JsonChildObject::SetAndParseDetails().
m_Measurements
std::vector<double> m_Measurements
Definition at line 105 of file JsonPrinter.hpp.
Referenced by JsonChildObject::AddMeasurement().
m_Type
JsonObjectType m_Type
Definition at line 103 of file JsonPrinter.hpp.
Referenced by JsonChildObject::GetType(), and JsonChildObject::SetType().
m_Unit
Measurement::Unit m_Unit
Definition at line 102 of file JsonPrinter.hpp.
Referenced by JsonChildObject::SetUnit().
The documentation for this struct was generated from the following file:
src/armnn/JsonPrinter.hpp