var searchData=
[
  ['rangetracker',['RangeTracker',['../classarmnn_1_1_range_tracker.xhtml',1,'armnn']]],
  ['recordbyrecordcaffeparser',['RecordByRecordCaffeParser',['../classarmnn_caffe_parser_1_1_record_by_record_caffe_parser.xhtml',1,'armnnCaffeParser']]],
  ['refactivationworkload',['RefActivationWorkload',['../classarmnn_1_1_ref_activation_workload.xhtml',1,'armnn']]],
  ['refargminmaxworkload',['RefArgMinMaxWorkload',['../classarmnn_1_1_ref_arg_min_max_workload.xhtml',1,'armnn']]],
  ['refbackend',['RefBackend',['../classarmnn_1_1_ref_backend.xhtml',1,'armnn']]],
  ['refbatchnormalizationworkload',['RefBatchNormalizationWorkload',['../classarmnn_1_1_ref_batch_normalization_workload.xhtml',1,'armnn']]],
  ['refbatchtospacendworkload',['RefBatchToSpaceNdWorkload',['../classarmnn_1_1_ref_batch_to_space_nd_workload.xhtml',1,'armnn']]],
  ['refcomparisonworkload',['RefComparisonWorkload',['../classarmnn_1_1_ref_comparison_workload.xhtml',1,'armnn']]],
  ['refconcatworkload',['RefConcatWorkload',['../classarmnn_1_1_ref_concat_workload.xhtml',1,'armnn']]],
  ['refconstantworkload',['RefConstantWorkload',['../classarmnn_1_1_ref_constant_workload.xhtml',1,'armnn']]],
  ['refconvertfp16tofp32workload',['RefConvertFp16ToFp32Workload',['../classarmnn_1_1_ref_convert_fp16_to_fp32_workload.xhtml',1,'armnn']]],
  ['refconvertfp32tofp16workload',['RefConvertFp32ToFp16Workload',['../classarmnn_1_1_ref_convert_fp32_to_fp16_workload.xhtml',1,'armnn']]],
  ['refconvolution2dworkload',['RefConvolution2dWorkload',['../classarmnn_1_1_ref_convolution2d_workload.xhtml',1,'armnn']]],
  ['refdebugworkload',['RefDebugWorkload',['../classarmnn_1_1_ref_debug_workload.xhtml',1,'armnn']]],
  ['refdepthtospaceworkload',['RefDepthToSpaceWorkload',['../classarmnn_1_1_ref_depth_to_space_workload.xhtml',1,'armnn']]],
  ['refdepthwiseconvolution2dworkload',['RefDepthwiseConvolution2dWorkload',['../classarmnn_1_1_ref_depthwise_convolution2d_workload.xhtml',1,'armnn']]],
  ['refdequantizeworkload',['RefDequantizeWorkload',['../classarmnn_1_1_ref_dequantize_workload.xhtml',1,'armnn']]],
  ['refdetectionpostprocessworkload',['RefDetectionPostProcessWorkload',['../classarmnn_1_1_ref_detection_post_process_workload.xhtml',1,'armnn']]],
  ['refelementwiseunaryworkload',['RefElementwiseUnaryWorkload',['../classarmnn_1_1_ref_elementwise_unary_workload.xhtml',1,'armnn']]],
  ['refelementwiseworkload',['RefElementwiseWorkload',['../classarmnn_1_1_ref_elementwise_workload.xhtml',1,'armnn']]],
  ['reffakequantizationfloat32workload',['RefFakeQuantizationFloat32Workload',['../classarmnn_1_1_ref_fake_quantization_float32_workload.xhtml',1,'armnn']]],
  ['reffloorworkload',['RefFloorWorkload',['../classarmnn_1_1_ref_floor_workload.xhtml',1,'armnn']]],
  ['reffullyconnectedworkload',['RefFullyConnectedWorkload',['../classarmnn_1_1_ref_fully_connected_workload.xhtml',1,'armnn']]],
  ['refgatherworkload',['RefGatherWorkload',['../classarmnn_1_1_ref_gather_workload.xhtml',1,'armnn']]],
  ['refinstancenormalizationworkload',['RefInstanceNormalizationWorkload',['../classarmnn_1_1_ref_instance_normalization_workload.xhtml',1,'armnn']]],
  ['refl2normalizationworkload',['RefL2NormalizationWorkload',['../classarmnn_1_1_ref_l2_normalization_workload.xhtml',1,'armnn']]],
  ['reflayersupport',['RefLayerSupport',['../classarmnn_1_1_ref_layer_support.xhtml',1,'armnn']]],
  ['reflogsoftmaxworkload',['RefLogSoftmaxWorkload',['../classarmnn_1_1_ref_log_softmax_workload.xhtml',1,'armnn']]],
  ['reflstmworkload',['RefLstmWorkload',['../classarmnn_1_1_ref_lstm_workload.xhtml',1,'armnn']]],
  ['refmeanworkload',['RefMeanWorkload',['../classarmnn_1_1_ref_mean_workload.xhtml',1,'armnn']]],
  ['refmemorymanager',['RefMemoryManager',['../classarmnn_1_1_ref_memory_manager.xhtml',1,'armnn']]],
  ['refnormalizationworkload',['RefNormalizationWorkload',['../classarmnn_1_1_ref_normalization_workload.xhtml',1,'armnn']]],
  ['refpadworkload',['RefPadWorkload',['../classarmnn_1_1_ref_pad_workload.xhtml',1,'armnn']]],
  ['refpermuteworkload',['RefPermuteWorkload',['../classarmnn_1_1_ref_permute_workload.xhtml',1,'armnn']]],
  ['refpooling2dworkload',['RefPooling2dWorkload',['../classarmnn_1_1_ref_pooling2d_workload.xhtml',1,'armnn']]],
  ['refpreluworkload',['RefPreluWorkload',['../classarmnn_1_1_ref_prelu_workload.xhtml',1,'armnn']]],
  ['refquantizeworkload',['RefQuantizeWorkload',['../classarmnn_1_1_ref_quantize_workload.xhtml',1,'armnn']]],
  ['refreshapeworkload',['RefReshapeWorkload',['../classarmnn_1_1_ref_reshape_workload.xhtml',1,'armnn']]],
  ['refresizebilinearworkload',['RefResizeBilinearWorkload',['../classarmnn_1_1_ref_resize_bilinear_workload.xhtml',1,'armnn']]],
  ['refresizeworkload',['RefResizeWorkload',['../classarmnn_1_1_ref_resize_workload.xhtml',1,'armnn']]],
  ['refsliceworkload',['RefSliceWorkload',['../classarmnn_1_1_ref_slice_workload.xhtml',1,'armnn']]],
  ['refsoftmaxworkload',['RefSoftmaxWorkload',['../classarmnn_1_1_ref_softmax_workload.xhtml',1,'armnn']]],
  ['refspacetobatchndworkload',['RefSpaceToBatchNdWorkload',['../classarmnn_1_1_ref_space_to_batch_nd_workload.xhtml',1,'armnn']]],
  ['refspacetodepthworkload',['RefSpaceToDepthWorkload',['../classarmnn_1_1_ref_space_to_depth_workload.xhtml',1,'armnn']]],
  ['refsplitterworkload',['RefSplitterWorkload',['../classarmnn_1_1_ref_splitter_workload.xhtml',1,'armnn']]],
  ['refstackworkload',['RefStackWorkload',['../classarmnn_1_1_ref_stack_workload.xhtml',1,'armnn']]],
  ['refstridedsliceworkload',['RefStridedSliceWorkload',['../classarmnn_1_1_ref_strided_slice_workload.xhtml',1,'armnn']]],
  ['reftensorhandle',['RefTensorHandle',['../classarmnn_1_1_ref_tensor_handle.xhtml',1,'armnn']]],
  ['reftensorhandlefactory',['RefTensorHandleFactory',['../classarmnn_1_1_ref_tensor_handle_factory.xhtml',1,'armnn']]],
  ['reftransposeconvolution2dworkload',['RefTransposeConvolution2dWorkload',['../classarmnn_1_1_ref_transpose_convolution2d_workload.xhtml',1,'armnn']]],
  ['reftransposeworkload',['RefTransposeWorkload',['../classarmnn_1_1_ref_transpose_workload.xhtml',1,'armnn']]],
  ['refworkloadfactory',['RefWorkloadFactory',['../classarmnn_1_1_ref_workload_factory.xhtml',1,'armnn']]],
  ['registerbackendcounters',['RegisterBackendCounters',['../classarmnn_1_1profiling_1_1_register_backend_counters.xhtml',1,'armnn::profiling']]],
  ['relationship',['Relationship',['../struct_i_timeline_decoder_1_1_relationship.xhtml',1,'ITimelineDecoder']]],
  ['requestcounterdirectorycommandhandler',['RequestCounterDirectoryCommandHandler',['../classarmnn_1_1profiling_1_1_request_counter_directory_command_handler.xhtml',1,'armnn::profiling']]],
  ['reshapedescriptor',['ReshapeDescriptor',['../structarmnn_1_1_reshape_descriptor.xhtml',1,'armnn']]],
  ['reshapelayer',['ReshapeLayer',['../classarmnn_1_1_reshape_layer.xhtml',1,'armnn']]],
  ['reshapequeuedescriptor',['ReshapeQueueDescriptor',['../structarmnn_1_1_reshape_queue_descriptor.xhtml',1,'armnn']]],
  ['resizebilineardescriptor',['ResizeBilinearDescriptor',['../structarmnn_1_1_resize_bilinear_descriptor.xhtml',1,'armnn']]],
  ['resizebilinearqueuedescriptor',['ResizeBilinearQueueDescriptor',['../structarmnn_1_1_resize_bilinear_queue_descriptor.xhtml',1,'armnn']]],
  ['resizedescriptor',['ResizeDescriptor',['../structarmnn_1_1_resize_descriptor.xhtml',1,'armnn']]],
  ['resizelayer',['ResizeLayer',['../classarmnn_1_1_resize_layer.xhtml',1,'armnn']]],
  ['resizequeuedescriptor',['ResizeQueueDescriptor',['../structarmnn_1_1_resize_queue_descriptor.xhtml',1,'armnn']]],
  ['resolvetypeimpl',['ResolveTypeImpl',['../structarmnn_1_1_resolve_type_impl.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3abfloat16_20_3e',['ResolveTypeImpl&lt; DataType::BFloat16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_b_float16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aboolean_20_3e',['ResolveTypeImpl&lt; DataType::Boolean &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_boolean_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat16_20_3e',['ResolveTypeImpl&lt; DataType::Float16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat32_20_3e',['ResolveTypeImpl&lt; DataType::Float32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float32_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymms8_20_3e',['ResolveTypeImpl&lt; DataType::QAsymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_s8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymmu8_20_3e',['ResolveTypeImpl&lt; DataType::QAsymmU8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_u8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms16_20_3e',['ResolveTypeImpl&lt; DataType::QSymmS16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms8_20_3e',['ResolveTypeImpl&lt; DataType::QSymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned32_20_3e',['ResolveTypeImpl&lt; DataType::Signed32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed32_01_4.xhtml',1,'armnn']]],
  ['rsqrt',['rsqrt',['../structarmnn_1_1rsqrt.xhtml',1,'armnn']]],
  ['rsqrtlayer',['RsqrtLayer',['../classarmnn_1_1_rsqrt_layer.xhtml',1,'armnn']]],
  ['rsqrtqueuedescriptor',['RsqrtQueueDescriptor',['../structarmnn_1_1_rsqrt_queue_descriptor.xhtml',1,'armnn']]],
  ['rule',['Rule',['../structarmnn_1_1_rule.xhtml',1,'armnn']]],
  ['runtime',['Runtime',['../classarmnn_1_1_runtime.xhtml',1,'armnn']]],
  ['runtimeexception',['RuntimeException',['../classarmnn_1_1_runtime_exception.xhtml',1,'armnn']]]
];
