var searchData=
[
  ['sampledynamicadditionworkload_6409',['SampleDynamicAdditionWorkload',['../classsdb_1_1_sample_dynamic_addition_workload.html',1,'sdb']]],
  ['sampledynamiclayersupport_6410',['SampleDynamicLayerSupport',['../classsdb_1_1_sample_dynamic_layer_support.html',1,'sdb']]],
  ['sampledynamictensorhandlefactory_6411',['SampleDynamicTensorHandleFactory',['../classsdb_1_1_sample_dynamic_tensor_handle_factory.html',1,'sdb']]],
  ['sampledynamicworkloadfactory_6412',['SampleDynamicWorkloadFactory',['../classsdb_1_1_sample_dynamic_workload_factory.html',1,'sdb']]],
  ['samplememorymanager_6413',['SampleMemoryManager',['../classsdb_1_1_sample_memory_manager.html',1,'sdb']]],
  ['sampletensorhandle_6414',['SampleTensorHandle',['../classsdb_1_1_sample_tensor_handle.html',1,'sdb']]],
  ['scaledint32decoder_6415',['ScaledInt32Decoder',['../classarmnn_1_1_scaled_int32_decoder.html',1,'armnn']]],
  ['scaledint32peraxisdecoder_6416',['ScaledInt32PerAxisDecoder',['../classarmnn_1_1_scaled_int32_per_axis_decoder.html',1,'armnn']]],
  ['scopedprofilingevent_6417',['ScopedProfilingEvent',['../classarmnn_1_1_scoped_profiling_event.html',1,'armnn']]],
  ['scopedrecord_6418',['ScopedRecord',['../structarmnn_1_1_scoped_record.html',1,'armnn']]],
  ['scopedtensorhandle_6419',['ScopedTensorHandle',['../classarmnn_1_1_scoped_tensor_handle.html',1,'armnn']]],
  ['selectivequantizer_6420',['SelectiveQuantizer',['../structarmnn_utils_1_1_selective_quantizer.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3abfloat16_2c_20false_20_3e_6421',['SelectiveQuantizer&lt; armnn::BFloat16, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_b_float16_00_01false_01_4.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3ahalf_2c_20false_20_3e_6422',['SelectiveQuantizer&lt; armnn::Half, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_half_00_01false_01_4.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20t_2c_20false_20_3e_6423',['SelectiveQuantizer&lt; T, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01_t_00_01false_01_4.html',1,'armnnUtils']]],
  ['serializerimpl_6424',['SerializerImpl',['../classarmnn_serializer_1_1_i_serializer_1_1_serializer_impl.html',1,'armnnSerializer::ISerializer']]],
  ['serializerstrategy_6425',['SerializerStrategy',['../classarmnn_serializer_1_1_serializer_strategy.html',1,'armnnSerializer']]],
  ['shapelayer_6426',['ShapeLayer',['../classarmnn_1_1_shape_layer.html',1,'armnn']]],
  ['shapequeuedescriptor_6427',['ShapeQueueDescriptor',['../structarmnn_1_1_shape_queue_descriptor.html',1,'armnn']]],
  ['shapesarebroadcastcompatible_6428',['ShapesAreBroadcastCompatible',['../structarmnn_1_1_shapes_are_broadcast_compatible.html',1,'armnn']]],
  ['shapesaresamerank_6429',['ShapesAreSameRank',['../structarmnn_1_1_shapes_are_same_rank.html',1,'armnn']]],
  ['shapesaresametotalsize_6430',['ShapesAreSameTotalSize',['../structarmnn_1_1_shapes_are_same_total_size.html',1,'armnn']]],
  ['simplelogger_6431',['SimpleLogger',['../classarmnn_1_1_simple_logger.html',1,'armnn']]],
  ['sin_6432',['sin',['../structarmnn_1_1sin.html',1,'armnn']]],
  ['singleaxisprioritylist_6433',['SingleAxisPriorityList',['../classarmnn_1_1_single_axis_priority_list.html',1,'armnn']]],
  ['slicedescriptor_6434',['SliceDescriptor',['../structarmnn_1_1_slice_descriptor.html',1,'armnn']]],
  ['slicelayer_6435',['SliceLayer',['../classarmnn_1_1_slice_layer.html',1,'armnn']]],
  ['slicequeuedescriptor_6436',['SliceQueueDescriptor',['../structarmnn_1_1_slice_queue_descriptor.html',1,'armnn']]],
  ['softmaxdescriptor_6437',['SoftmaxDescriptor',['../structarmnn_1_1_softmax_descriptor.html',1,'armnn']]],
  ['softmaxlayer_6438',['SoftmaxLayer',['../classarmnn_1_1_softmax_layer.html',1,'armnn']]],
  ['softmaxqueuedescriptor_6439',['SoftmaxQueueDescriptor',['../structarmnn_1_1_softmax_queue_descriptor.html',1,'armnn']]],
  ['spacetobatchnddescriptor_6440',['SpaceToBatchNdDescriptor',['../structarmnn_1_1_space_to_batch_nd_descriptor.html',1,'armnn']]],
  ['spacetobatchndlayer_6441',['SpaceToBatchNdLayer',['../classarmnn_1_1_space_to_batch_nd_layer.html',1,'armnn']]],
  ['spacetobatchndqueuedescriptor_6442',['SpaceToBatchNdQueueDescriptor',['../structarmnn_1_1_space_to_batch_nd_queue_descriptor.html',1,'armnn']]],
  ['spacetodepthdescriptor_6443',['SpaceToDepthDescriptor',['../structarmnn_1_1_space_to_depth_descriptor.html',1,'armnn']]],
  ['spacetodepthlayer_6444',['SpaceToDepthLayer',['../classarmnn_1_1_space_to_depth_layer.html',1,'armnn']]],
  ['spacetodepthqueuedescriptor_6445',['SpaceToDepthQueueDescriptor',['../structarmnn_1_1_space_to_depth_queue_descriptor.html',1,'armnn']]],
  ['splitterlayer_6446',['SplitterLayer',['../classarmnn_1_1_splitter_layer.html',1,'armnn']]],
  ['splitterqueuedescriptor_6447',['SplitterQueueDescriptor',['../structarmnn_1_1_splitter_queue_descriptor.html',1,'armnn']]],
  ['sqrt_6448',['sqrt',['../structarmnn_1_1sqrt.html',1,'armnn']]],
  ['squareddifference_6449',['squaredDifference',['../structarmnn_1_1squared_difference.html',1,'armnn']]],
  ['squashequalsiblingsimpl_6450',['SquashEqualSiblingsImpl',['../classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl.html',1,'armnn::optimizations']]],
  ['stackdescriptor_6451',['StackDescriptor',['../structarmnn_1_1_stack_descriptor.html',1,'armnn']]],
  ['stacklayer_6452',['StackLayer',['../classarmnn_1_1_stack_layer.html',1,'armnn']]],
  ['stackqueuedescriptor_6453',['StackQueueDescriptor',['../structarmnn_1_1_stack_queue_descriptor.html',1,'armnn']]],
  ['standardoutputsink_6454',['StandardOutputSink',['../classarmnn_1_1_standard_output_sink.html',1,'armnn']]],
  ['standindescriptor_6455',['StandInDescriptor',['../structarmnn_1_1_stand_in_descriptor.html',1,'armnn']]],
  ['standinlayer_6456',['StandInLayer',['../classarmnn_1_1_stand_in_layer.html',1,'armnn']]],
  ['staticregistryinitializer_6457',['StaticRegistryInitializer',['../structarmnn_1_1_backend_registry_1_1_static_registry_initializer.html',1,'armnn::BackendRegistry']]],
  ['strategybase_6458',['StrategyBase',['../classarmnn_1_1_strategy_base.html',1,'armnn']]],
  ['strategyfactory_6459',['StrategyFactory',['../structarmnn_1_1_strategy_factory.html',1,'armnn']]],
  ['strategyvalidator_6460',['StrategyValidator',['../classarmnn_1_1_strategy_validator.html',1,'armnn']]],
  ['stridedslicedescriptor_6461',['StridedSliceDescriptor',['../structarmnn_1_1_strided_slice_descriptor.html',1,'armnn']]],
  ['stridedslicelayer_6462',['StridedSliceLayer',['../classarmnn_1_1_strided_slice_layer.html',1,'armnn']]],
  ['stridedslicequeuedescriptor_6463',['StridedSliceQueueDescriptor',['../structarmnn_1_1_strided_slice_queue_descriptor.html',1,'armnn']]],
  ['stringifylayerparameters_6464',['StringifyLayerParameters',['../structarmnn_1_1_stringify_layer_parameters.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20activationdescriptor_20_3e_6465',['StringifyLayerParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_activation_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchmatmuldescriptor_20_3e_6466',['StringifyLayerParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_mat_mul_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchnormalizationdescriptor_20_3e_6467',['StringifyLayerParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchtospacenddescriptor_20_3e_6468',['StringifyLayerParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_to_space_nd_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20channelshuffledescriptor_20_3e_6469',['StringifyLayerParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_channel_shuffle_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20comparisondescriptor_20_3e_6470',['StringifyLayerParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_comparison_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution2ddescriptor_20_3e_6471',['StringifyLayerParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution3ddescriptor_20_3e_6472',['StringifyLayerParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution3d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_6473',['StringifyLayerParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_depthwise_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20detectionpostprocessdescriptor_20_3e_6474',['StringifyLayerParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_detection_post_process_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwisebinarydescriptor_20_3e_6475',['StringifyLayerParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_binary_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwiseunarydescriptor_20_3e_6476',['StringifyLayerParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_unary_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fakequantizationdescriptor_20_3e_6477',['StringifyLayerParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fake_quantization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fullyconnecteddescriptor_20_3e_6478',['StringifyLayerParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fully_connected_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fuseddescriptor_20_3e_6479',['StringifyLayerParameters&lt; FusedDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fused_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20gatherdescriptor_20_3e_6480',['StringifyLayerParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_gather_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20l2normalizationdescriptor_20_3e_6481',['StringifyLayerParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_l2_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20lstmdescriptor_20_3e_6482',['StringifyLayerParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_lstm_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20meandescriptor_20_3e_6483',['StringifyLayerParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_mean_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20normalizationdescriptor_20_3e_6484',['StringifyLayerParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20originsdescriptor_20_3e_6485',['StringifyLayerParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_origins_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20paddescriptor_20_3e_6486',['StringifyLayerParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pad_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20permutedescriptor_20_3e_6487',['StringifyLayerParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_permute_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling2ddescriptor_20_3e_6488',['StringifyLayerParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling3ddescriptor_20_3e_6489',['StringifyLayerParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling3d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20precompileddescriptor_20_3e_6490',['StringifyLayerParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pre_compiled_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20reducedescriptor_20_3e_6491',['StringifyLayerParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reduce_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20reshapedescriptor_20_3e_6492',['StringifyLayerParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reshape_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20resizedescriptor_20_3e_6493',['StringifyLayerParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_resize_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20softmaxdescriptor_20_3e_6494',['StringifyLayerParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_softmax_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetobatchnddescriptor_20_3e_6495',['StringifyLayerParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_batch_nd_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetodepthdescriptor_20_3e_6496',['StringifyLayerParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_depth_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20stackdescriptor_20_3e_6497',['StringifyLayerParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_stack_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20stridedslicedescriptor_20_3e_6498',['StringifyLayerParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_strided_slice_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20tiledescriptor_20_3e_6499',['StringifyLayerParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_tile_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposeconvolution2ddescriptor_20_3e_6500',['StringifyLayerParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposedescriptor_20_3e_6501',['StringifyLayerParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20viewsdescriptor_20_3e_6502',['StringifyLayerParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_views_descriptor_01_4.html',1,'armnn']]],
  ['stringmapping_6503',['StringMapping',['../structarmnn_1_1_string_mapping.html',1,'armnn']]],
  ['subgraphview_6504',['SubgraphView',['../classarmnn_1_1_subgraph_view.html',1,'armnn']]],
  ['subgraphviewselector_6505',['SubgraphViewSelector',['../classarmnn_1_1_subgraph_view_selector.html',1,'armnn']]],
  ['substitutionpair_6506',['SubstitutionPair',['../structarmnn_1_1_optimization_views_1_1_substitution_pair.html',1,'armnn::OptimizationViews']]],
  ['subtractionlayer_6507',['SubtractionLayer',['../classarmnn_1_1_subtraction_layer.html',1,'armnn']]],
  ['subtractionqueuedescriptor_6508',['SubtractionQueueDescriptor',['../structarmnn_1_1_subtraction_queue_descriptor.html',1,'armnn']]],
  ['switchlayer_6509',['SwitchLayer',['../classarmnn_1_1_switch_layer.html',1,'armnn']]],
  ['switchqueuedescriptor_6510',['SwitchQueueDescriptor',['../structarmnn_1_1_switch_queue_descriptor.html',1,'armnn']]],
  ['syncmemgenericworkload_6511',['SyncMemGenericWorkload',['../classarmnn_1_1_sync_mem_generic_workload.html',1,'armnn']]]
];
