var searchData=
[
  ['neonabsworkload_5939',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.html',1,'armnn']]],
  ['neonactivationworkload_5940',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.html',1,'armnn']]],
  ['neonadditionworkload_5941',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.html',1,'armnn']]],
  ['neonargminmaxworkload_5942',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.html',1,'armnn']]],
  ['neonbackend_5943',['NeonBackend',['../classarmnn_1_1_neon_backend.html',1,'armnn']]],
  ['neonbackendmodelcontext_5944',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.html',1,'armnn']]],
  ['neonbaseworkload_5945',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e_5946',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e_5947',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e_5948',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5949',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5950',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5951',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5952',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e_5953',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5954',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5955',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e_5956',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e_5957',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5958',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5959',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5960',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5961',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5962',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5963',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e_5964',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5965',['NeonBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5966',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e_5967',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5968',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fusedqueuedescriptor_20_3e_5969',['NeonBaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e_5970',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e_5971',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5972',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5973',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5974',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e_5975',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e_5976',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e_5977',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e_5978',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e_5979',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e_5980',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_5981',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_5982',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e_5983',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e_5984',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5985',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e_5986',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e_5987',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e_5988',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e_5989',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e_5990',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e_5991',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e_5992',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e_5993',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5994',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5995',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e_5996',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e_5997',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_5998',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e_5999',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_6000',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e_6001',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_6002',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbatchmatmulworkload_6003',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.html',1,'armnn']]],
  ['neonbatchnormalizationworkload_6004',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.html',1,'armnn']]],
  ['neonbatchtospacendworkload_6005',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.html',1,'armnn']]],
  ['neoncastworkload_6006',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.html',1,'armnn']]],
  ['neonchannelshuffleworkload_6007',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.html',1,'armnn']]],
  ['neoncomparisonworkload_6008',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.html',1,'armnn']]],
  ['neonconcatworkload_6009',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.html',1,'armnn']]],
  ['neonconstantworkload_6010',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.html',1,'armnn']]],
  ['neonconvertfp16tofp32workload_6011',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['neonconvertfp32tofp16workload_6012',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['neonconvolution2dworkload_6013',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.html',1,'armnn']]],
  ['neonconvolution3dworkload_6014',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.html',1,'armnn']]],
  ['neondepthtospaceworkload_6015',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.html',1,'armnn']]],
  ['neondepthwiseconvolutionworkload_6016',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.html',1,'armnn']]],
  ['neondequantizeworkload_6017',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.html',1,'armnn']]],
  ['neondetectionpostprocessworkload_6018',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.html',1,'armnn']]],
  ['neondivisionworkload_6019',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.html',1,'armnn']]],
  ['neonelementwisebinaryworkload_6020',['NeonElementwiseBinaryWorkload',['../classarmnn_1_1_neon_elementwise_binary_workload.html',1,'armnn']]],
  ['neonexpworkload_6021',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.html',1,'armnn']]],
  ['neonfillworkload_6022',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.html',1,'armnn']]],
  ['neonfloorfloatworkload_6023',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.html',1,'armnn']]],
  ['neonfullyconnectedworkload_6024',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.html',1,'armnn']]],
  ['neonfusedworkload_6025',['NeonFusedWorkload',['../classarmnn_1_1_neon_fused_workload.html',1,'armnn']]],
  ['neongatherndworkload_6026',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.html',1,'armnn']]],
  ['neongatherworkload_6027',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.html',1,'armnn']]],
  ['neoninstancenormalizationworkload_6028',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.html',1,'armnn']]],
  ['neoninterceptorscheduler_6029',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.html',1,'armnn']]],
  ['neonl2normalizationfloatworkload_6030',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.html',1,'armnn']]],
  ['neonlayersupport_6031',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.html',1,'armnn']]],
  ['neonlogicalandworkload_6032',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.html',1,'armnn']]],
  ['neonlogicalnotworkload_6033',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.html',1,'armnn']]],
  ['neonlogicalorworkload_6034',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.html',1,'armnn']]],
  ['neonlogsoftmaxworkload_6035',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.html',1,'armnn']]],
  ['neonlogworkload_6036',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.html',1,'armnn']]],
  ['neonlstmfloatworkload_6037',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.html',1,'armnn']]],
  ['neonmaximumworkload_6038',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.html',1,'armnn']]],
  ['neonmeanworkload_6039',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.html',1,'armnn']]],
  ['neonmemorymanager_6040',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.html',1,'armnn']]],
  ['neonminimumworkload_6041',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.html',1,'armnn']]],
  ['neonmultiplicationworkload_6042',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.html',1,'armnn']]],
  ['neonnegworkload_6043',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.html',1,'armnn']]],
  ['neonnormalizationfloatworkload_6044',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.html',1,'armnn']]],
  ['neonpadworkload_6045',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.html',1,'armnn']]],
  ['neonpermuteworkload_6046',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.html',1,'armnn']]],
  ['neonpooling2dworkload_6047',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.html',1,'armnn']]],
  ['neonpooling3dworkload_6048',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.html',1,'armnn']]],
  ['neonpreluworkload_6049',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.html',1,'armnn']]],
  ['neonqlstmworkload_6050',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.html',1,'armnn']]],
  ['neonquantizedlstmworkload_6051',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.html',1,'armnn']]],
  ['neonquantizeworkload_6052',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.html',1,'armnn']]],
  ['neonrankworkload_6053',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.html',1,'armnn']]],
  ['neonreduceworkload_6054',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.html',1,'armnn']]],
  ['neonreshapeworkload_6055',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.html',1,'armnn']]],
  ['neonresizeworkload_6056',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.html',1,'armnn']]],
  ['neonreversev2workload_6057',['NeonReverseV2Workload',['../classarmnn_1_1_neon_reverse_v2_workload.html',1,'armnn']]],
  ['neonrsqrtworkload_6058',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.html',1,'armnn']]],
  ['neonsinworkload_6059',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.html',1,'armnn']]],
  ['neonsliceworkload_6060',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.html',1,'armnn']]],
  ['neonsoftmaxworkload_6061',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.html',1,'armnn']]],
  ['neonspacetobatchndworkload_6062',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.html',1,'armnn']]],
  ['neonspacetodepthworkload_6063',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.html',1,'armnn']]],
  ['neonsplitterworkload_6064',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.html',1,'armnn']]],
  ['neonsqrtworkload_6065',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.html',1,'armnn']]],
  ['neonstackworkload_6066',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.html',1,'armnn']]],
  ['neonstridedsliceworkload_6067',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.html',1,'armnn']]],
  ['neonsubtensorhandle_6068',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.html',1,'armnn']]],
  ['neonsubtractionworkload_6069',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.html',1,'armnn']]],
  ['neontensordecorator_6070',['NeonTensorDecorator',['../classarmnn_1_1_neon_tensor_decorator.html',1,'armnn']]],
  ['neontensorhandle_6071',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.html',1,'armnn']]],
  ['neontensorhandledecorator_6072',['NeonTensorHandleDecorator',['../classarmnn_1_1_neon_tensor_handle_decorator.html',1,'armnn']]],
  ['neontensorhandlefactory_6073',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.html',1,'armnn']]],
  ['neontileworkload_6074',['NeonTileWorkload',['../classarmnn_1_1_neon_tile_workload.html',1,'armnn']]],
  ['neontimer_6075',['NeonTimer',['../classarmnn_1_1_neon_timer.html',1,'armnn']]],
  ['neontransposeconvolution2dworkload_6076',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.html',1,'armnn']]],
  ['neontransposeworkload_6077',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload_6078',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload_6079',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['neonworkloadfactory_6080',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.html',1,'armnn']]],
  ['networkimpl_6081',['NetworkImpl',['../classarmnn_1_1_network_impl.html',1,'armnn']]],
  ['nodecontent_6082',['NodeContent',['../classarmnn_1_1_node_content.html',1,'armnn']]],
  ['normalizationdescriptor_6083',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.html',1,'armnn']]],
  ['normalizationlayer_6084',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.html',1,'armnn']]],
  ['normalizationqueuedescriptor_6085',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.html',1,'armnn']]],
  ['nothrowstrategy_6086',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.html',1,'armnn']]],
  ['nulldescriptor_6087',['NullDescriptor',['../structarmnn_1_1_null_descriptor.html',1,'armnn']]],
  ['nullpointerexception_6088',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.html',1,'armnn']]],
  ['nullworkload_6089',['NullWorkload',['../classarmnn_1_1_null_workload.html',1,'armnn']]]
];
