var searchData=
[
  ['backendcapabilityexception_5258',['BackendCapabilityException',['../classarmnn_1_1_backend_capability_exception.html',1,'armnn']]],
  ['backendid_5259',['BackendId',['../classarmnn_1_1_backend_id.html',1,'armnn']]],
  ['backendoption_5260',['BackendOption',['../structarmnn_1_1_backend_options_1_1_backend_option.html',1,'armnn::BackendOptions']]],
  ['backendoptions_5261',['BackendOptions',['../structarmnn_1_1_backend_options.html',1,'armnn']]],
  ['backendregistry_5262',['BackendRegistry',['../classarmnn_1_1_backend_registry.html',1,'armnn']]],
  ['backendsettings_5263',['BackendSettings',['../structarmnn_1_1_backend_settings.html',1,'armnn']]],
  ['backendunavailableexception_5264',['BackendUnavailableException',['../classarmnn_1_1_backend_unavailable_exception.html',1,'armnn']]],
  ['backendversion_5265',['BackendVersion',['../structarmnn_1_1_backend_version.html',1,'armnn']]],
  ['badoptionalaccessexception_5266',['BadOptionalAccessException',['../classarmnn_1_1_bad_optional_access_exception.html',1,'armnn']]],
  ['basedescriptor_5267',['BaseDescriptor',['../structarmnn_1_1_base_descriptor.html',1,'armnn']]],
  ['baseiterator_5268',['BaseIterator',['../classarmnn_1_1_base_iterator.html',1,'armnn']]],
  ['basememorymanager_5269',['BaseMemoryManager',['../classarmnn_1_1_base_memory_manager.html',1,'armnn']]],
  ['basetensor_5270',['BaseTensor',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20const_20void_20_2a_20_3e_5271',['BaseTensor&lt; const void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20void_20_2a_20_3e_5272',['BaseTensor&lt; void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['baseworkload_5273',['BaseWorkload',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20absqueuedescriptor_20_3e_5274',['BaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20activationqueuedescriptor_20_3e_5275',['BaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20additionqueuedescriptor_20_3e_5276',['BaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20argminmaxqueuedescriptor_20_3e_5277',['BaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20armnn_3a_3aadditionqueuedescriptor_20_3e_5278',['BaseWorkload&lt; armnn::AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5279',['BaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5280',['BaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5281',['BaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20broadcasttoqueuedescriptor_20_3e_5282',['BaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20castqueuedescriptor_20_3e_5283',['BaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20channelshufflequeuedescriptor_20_3e_5284',['BaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20comparisonqueuedescriptor_20_3e_5285',['BaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20concatqueuedescriptor_20_3e_5286',['BaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20constantqueuedescriptor_20_3e_5287',['BaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution2dqueuedescriptor_20_3e_5288',['BaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution3dqueuedescriptor_20_3e_5289',['BaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20debugqueuedescriptor_20_3e_5290',['BaseWorkload&lt; DebugQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthtospacequeuedescriptor_20_3e_5291',['BaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5292',['BaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20dequantizequeuedescriptor_20_3e_5293',['BaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5294',['BaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20divisionqueuedescriptor_20_3e_5295',['BaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5296',['BaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5297',['BaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fillqueuedescriptor_20_3e_5298',['BaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20floorqueuedescriptor_20_3e_5299',['BaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5300',['BaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fusedqueuedescriptor_20_3e_5301',['BaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherndqueuedescriptor_20_3e_5302',['BaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherqueuedescriptor_20_3e_5303',['BaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5304',['BaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5305',['BaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5306',['BaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5307',['BaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20lstmqueuedescriptor_20_3e_5308',['BaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20mapqueuedescriptor_20_3e_5309',['BaseWorkload&lt; MapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20maximumqueuedescriptor_20_3e_5310',['BaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20meanqueuedescriptor_20_3e_5311',['BaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memcopyqueuedescriptor_20_3e_5312',['BaseWorkload&lt; MemCopyQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memimportqueuedescriptor_20_3e_5313',['BaseWorkload&lt; MemImportQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memsyncqueuedescriptor_20_3e_5314',['BaseWorkload&lt; MemSyncQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20minimumqueuedescriptor_20_3e_5315',['BaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20multiplicationqueuedescriptor_20_3e_5316',['BaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20normalizationqueuedescriptor_20_3e_5317',['BaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20padqueuedescriptor_20_3e_5318',['BaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20parentdescriptor_20_3e_5319',['BaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20permutequeuedescriptor_20_3e_5320',['BaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling2dqueuedescriptor_20_3e_5321',['BaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling3dqueuedescriptor_20_3e_5322',['BaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20precompiledqueuedescriptor_20_3e_5323',['BaseWorkload&lt; PreCompiledQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20preluqueuedescriptor_20_3e_5324',['BaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20qlstmqueuedescriptor_20_3e_5325',['BaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5326',['BaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizequeuedescriptor_20_3e_5327',['BaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rankqueuedescriptor_20_3e_5328',['BaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reducequeuedescriptor_20_3e_5329',['BaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reshapequeuedescriptor_20_3e_5330',['BaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20resizequeuedescriptor_20_3e_5331',['BaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reversev2queuedescriptor_20_3e_5332',['BaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rsqrtqueuedescriptor_20_3e_5333',['BaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20shapequeuedescriptor_20_3e_5334',['BaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20slicequeuedescriptor_20_3e_5335',['BaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20softmaxqueuedescriptor_20_3e_5336',['BaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5337',['BaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5338',['BaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20splitterqueuedescriptor_20_3e_5339',['BaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stackqueuedescriptor_20_3e_5340',['BaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stridedslicequeuedescriptor_20_3e_5341',['BaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20subtractionqueuedescriptor_20_3e_5342',['BaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20tilequeuedescriptor_20_3e_5343',['BaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5344',['BaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposequeuedescriptor_20_3e_5345',['BaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5346',['BaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unmapqueuedescriptor_20_3e_5347',['BaseWorkload&lt; UnmapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['batchmatmul_5348',['BatchMatMul',['../classarmnn_1_1_batch_mat_mul.html',1,'armnn']]],
  ['batchmatmuldescriptor_5349',['BatchMatMulDescriptor',['../structarmnn_1_1_batch_mat_mul_descriptor.html',1,'armnn']]],
  ['batchmatmullayer_5350',['BatchMatMulLayer',['../classarmnn_1_1_batch_mat_mul_layer.html',1,'armnn']]],
  ['batchmatmulqueuedescriptor_5351',['BatchMatMulQueueDescriptor',['../structarmnn_1_1_batch_mat_mul_queue_descriptor.html',1,'armnn']]],
  ['batchnormalizationdescriptor_5352',['BatchNormalizationDescriptor',['../structarmnn_1_1_batch_normalization_descriptor.html',1,'armnn']]],
  ['batchnormalizationlayer_5353',['BatchNormalizationLayer',['../classarmnn_1_1_batch_normalization_layer.html',1,'armnn']]],
  ['batchnormalizationqueuedescriptor_5354',['BatchNormalizationQueueDescriptor',['../structarmnn_1_1_batch_normalization_queue_descriptor.html',1,'armnn']]],
  ['batchtospacenddescriptor_5355',['BatchToSpaceNdDescriptor',['../structarmnn_1_1_batch_to_space_nd_descriptor.html',1,'armnn']]],
  ['batchtospacendlayer_5356',['BatchToSpaceNdLayer',['../classarmnn_1_1_batch_to_space_nd_layer.html',1,'armnn']]],
  ['batchtospacendqueuedescriptor_5357',['BatchToSpaceNdQueueDescriptor',['../structarmnn_1_1_batch_to_space_nd_queue_descriptor.html',1,'armnn']]],
  ['bfloat16_5358',['BFloat16',['../classarmnn_1_1_b_float16.html',1,'armnn']]],
  ['biasandweightstypescompatible_5359',['BiasAndWeightsTypesCompatible',['../structarmnn_1_1_bias_and_weights_types_compatible.html',1,'armnn']]],
  ['biasandweightstypesmatch_5360',['BiasAndWeightsTypesMatch',['../structarmnn_1_1_bias_and_weights_types_match.html',1,'armnn']]],
  ['bindablelayer_5361',['BindableLayer',['../classarmnn_1_1_bindable_layer.html',1,'armnn']]],
  ['bindingpointinfo_5362',['BindingPointInfo',['../structarmnn_deserializer_1_1_binding_point_info.html',1,'armnnDeserializer']]],
  ['booleandecoder_5363',['BooleanDecoder',['../classarmnn_1_1_boolean_decoder.html',1,'armnn']]],
  ['booleandecoderbool_5364',['BooleanDecoderBool',['../classarmnn_1_1_boolean_decoder_bool.html',1,'armnn']]],
  ['booleanencoder_5365',['BooleanEncoder',['../classarmnn_1_1_boolean_encoder.html',1,'armnn']]],
  ['broadcastloop_5366',['BroadcastLoop',['../structarmnn_1_1_broadcast_loop.html',1,'armnn']]],
  ['broadcasttodescriptor_5367',['BroadcastToDescriptor',['../structarmnn_1_1_broadcast_to_descriptor.html',1,'armnn']]],
  ['broadcasttolayer_5368',['BroadcastToLayer',['../classarmnn_1_1_broadcast_to_layer.html',1,'armnn']]],
  ['broadcasttoqueuedescriptor_5369',['BroadcastToQueueDescriptor',['../structarmnn_1_1_broadcast_to_queue_descriptor.html',1,'armnn']]],
  ['bufferstorage_5370',['BufferStorage',['../structarmnn_1_1_buffer_storage.html',1,'armnn']]]
];
