Arm NN: NeonTensorHandle Class Reference
NeonTensorHandle Class Reference
#include <NeonTensorHandle.hpp>
Public Member Functions
NeonTensorHandle (const TensorInfo &tensorInfo)
NeonTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, MemorySourceFlags importFlags=static_cast< MemorySourceFlags >(MemorySource::Malloc))
arm_compute::ITensor & GetTensor () override
arm_compute::ITensor const & GetTensor () const override
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual arm_compute::DataType GetDataType () const override
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > &memoryGroup) override
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
void SetImportFlags (MemorySourceFlags importFlags)
MemorySourceFlags GetImportFlags () const override
Get flags describing supported import sources.
void SetImportEnabledFlag (bool importEnabledFlag)
bool CanBeImported (void *memory, MemorySource source) override
Implementations must determine if this memory block can be imported.
virtual bool Import (void *memory, MemorySource source) override
Import externally allocated memory.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo) override
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual void Unimport ()
Unimport externally allocated memory.
Detailed Description
Definition at line 29 of file NeonTensorHandle.hpp.
Constructor & Destructor Documentation
NeonTensorHandle() [1/2]
NeonTensorHandle (const TensorInfo & tensorInfo) inline
Definition at line 32 of file NeonTensorHandle.hpp.
                      : m_ImportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc)),
                        m_Imported(false),
                        m_IsImportEnabled(false),
                        m_TypeAlignment(GetDataTypeSize(tensorInfo.GetDataType()))
     {
         armnn::armcomputetensorutils::BuildArmComputeTensor(m_Tensor, tensorInfo);
     }
References armnn::Malloc.
NeonTensorHandle() [2/2]
NeonTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, MemorySourceFlags importFlags = static_cast<MemorySourceFlags>(MemorySource::Malloc)) inline
Definition at line 41 of file NeonTensorHandle.hpp.
                      : m_ImportFlags(importFlags),
                        m_Imported(false),
                        m_IsImportEnabled(false),
                        m_TypeAlignment(GetDataTypeSize(tensorInfo.GetDataType()))
     {
         armnn::armcomputetensorutils::BuildArmComputeTensor(m_Tensor, tensorInfo, dataLayout);
     }
Member Function Documentation
Allocate()
virtual void Allocate () inline override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 57 of file NeonTensorHandle.hpp.
     {
         // If we have enabled Importing, don't Allocate the tensor
         if (!m_IsImportEnabled)
         {
             armnn::armcomputetensorutils::InitialiseArmComputeTensorEmpty(m_Tensor);
         }
     };
CanBeImported()
bool CanBeImported (void * memory, MemorySource source) inline override virtual
Implementations must determine if this memory block can be imported.
This might be based on alignment or memory source type.
Returns
true if this memory can be imported.
false by default, cannot be imported.
Reimplemented from ITensorHandle.
Definition at line 120 of file NeonTensorHandle.hpp.
     {
         if (source != MemorySource::Malloc || reinterpret_cast<uintptr_t>(memory) % m_TypeAlignment)
         {
             return false;
         }
         return true;
     }
References armnn::Malloc.
Referenced by NeonTensorHandle::Import().
DecorateTensorHandle()
std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo & tensorInfo) override virtual
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Parameters
tensorInfo the overidden TensorInfo.
Reimplemented from ITensorHandle.
Definition at line 12 of file NeonTensorHandle.cpp.
 {
     auto* parent = const_cast<NeonTensorHandle*>(this);
     auto decorated = std::make_shared<NeonTensorHandleDecorator>(parent, tensorInfo);
     m_Decorated.emplace_back(decorated);
     return decorated;
 }
GetDataType()
virtual arm_compute::DataType GetDataType () const inline override virtual
Implements IAclTensorHandle.
Definition at line 78 of file NeonTensorHandle.hpp.
     {
         return m_Tensor.info()->data_type();
     }
GetImportFlags()
MemorySourceFlags GetImportFlags () const inline override virtual
Get flags describing supported import sources.
Reimplemented from ITensorHandle.
Definition at line 110 of file NeonTensorHandle.hpp.
     {
         return m_ImportFlags;
     }
GetParent()
virtual ITensorHandle* GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Definition at line 76 of file NeonTensorHandle.hpp.
 { return nullptr; }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Definition at line 100 of file NeonTensorHandle.hpp.
     {
         return armcomputetensorutils::GetShape(m_Tensor.info()->tensor_shape());
     }
Referenced by NeonRankWorkload::Execute().
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Definition at line 95 of file NeonTensorHandle.hpp.
     {
         return armcomputetensorutils::GetStrides(m_Tensor.info()->strides_in_bytes());
     }
GetTensor() [1/2]
arm_compute::ITensor const& GetTensor () const inline override virtual
Implements IAclTensorHandle.
Definition at line 55 of file NeonTensorHandle.hpp.
 { return m_Tensor; }
GetTensor() [2/2]
arm_compute::ITensor& GetTensor () inline override virtual
Implements IAclTensorHandle.
Definition at line 54 of file NeonTensorHandle.hpp.
 { return m_Tensor; }
Import()
virtual bool Import (void * memory, MemorySource source) inline override virtual
Import externally allocated memory.
Parameters
memory base address of the memory being imported.
source source of the allocation for the memory being imported.
Returns
true on success or false on failure
Reimplemented from ITensorHandle.
Definition at line 129 of file NeonTensorHandle.hpp.
     {
         if (m_ImportFlags&  static_cast<MemorySourceFlags>(source))
         {
             if (source == MemorySource::Malloc && m_IsImportEnabled)
             {
                 if (!CanBeImported(memory, source))
                 {
                     throw MemoryImportException("NeonTensorHandle::Import Attempting to import unaligned memory");
                 }
                 // m_Tensor not yet Allocated
                 if (!m_Imported && !m_Tensor.buffer())
                 {
                     arm_compute::Status status = m_Tensor.allocator()->import_memory(memory);
                     // Use the overloaded bool operator of Status to check if it worked, if not throw an exception
                     // with the Status error message
                     m_Imported = bool(status);
                     if (!m_Imported)
                     {
                         throw MemoryImportException(status.error_description());
                     }
                     return m_Imported;
                 }
                 // m_Tensor.buffer() initially allocated with Allocate().
                 if (!m_Imported && m_Tensor.buffer())
                 {
                     throw MemoryImportException(
                         "NeonTensorHandle::Import Attempting to import on an already allocated tensor");
                 }
                 // m_Tensor.buffer() previously imported.
                 if (m_Imported)
                 {
                     arm_compute::Status status = m_Tensor.allocator()->import_memory(memory);
                     // Use the overloaded bool operator of Status to check if it worked, if not throw an exception
                     // with the Status error message
                     m_Imported = bool(status);
                     if (!m_Imported)
                     {
                         throw MemoryImportException(status.error_description());
                     }
                     return m_Imported;
                 }
             }
             else
             {
                 throw MemoryImportException("NeonTensorHandle::Import is disabled");
             }
         }
         else
         {
             throw MemoryImportException("NeonTensorHandle::Incorrect import flag");
         }
         return false;
     }
References NeonTensorHandle::CanBeImported(), and armnn::Malloc.
Manage()
virtual void Manage () inline override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 66 of file NeonTensorHandle.hpp.
     {
         // If we have enabled Importing, don't manage the tensor
         if (!m_IsImportEnabled)
         {
             ARMNN_ASSERT(m_MemoryGroup != nullptr);
             m_MemoryGroup->manage(&m_Tensor);
         }
     }
References ARMNN_ASSERT.
Map()
virtual const void* Map (bool blocking) const inline override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Definition at line 88 of file NeonTensorHandle.hpp.
     {
         return static_cast<const void*>(m_Tensor.buffer() + m_Tensor.info()->offset_first_element_in_bytes());
     }
SetImportEnabledFlag()
void SetImportEnabledFlag (bool importEnabledFlag) inline
Definition at line 115 of file NeonTensorHandle.hpp.
     {
         m_IsImportEnabled = importEnabledFlag;
     }
SetImportFlags()
void SetImportFlags (MemorySourceFlags importFlags) inline
Definition at line 105 of file NeonTensorHandle.hpp.
     {
         m_ImportFlags = importFlags;
     }
SetMemoryGroup()
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > & memoryGroup) inline override virtual
Implements IAclTensorHandle.
Definition at line 83 of file NeonTensorHandle.hpp.
     {
         m_MemoryGroup = PolymorphicPointerDowncast<arm_compute::MemoryGroup>(memoryGroup);
     }
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Definition at line 93 of file NeonTensorHandle.hpp.
 {}
The documentation for this class was generated from the following files:
src/backends/neon/NeonTensorHandle.hpp
src/backends/neon/NeonTensorHandle.cpp