Arm NN: OptimizedNetworkImpl Class Reference
OptimizedNetworkImpl Class Reference
#include <OptimizedNetworkImpl.hpp>
Public Member Functions
OptimizedNetworkImpl (const OptimizedNetworkImpl &other, const ModelOptions &modelOptions)
OptimizedNetworkImpl (std::unique_ptr< Graph > graph)
OptimizedNetworkImpl (std::unique_ptr< Graph > graph, const ModelOptions &modelOptions)
virtual ~OptimizedNetworkImpl ()
virtual Status PrintGraph ()
virtual Status SerializeToDot (std::ostream &stream) const
virtual arm::pipe::ProfilingGuid GetGuid () const
virtual size_t GetNumInputs () const
virtual size_t GetNumOutputs () const
Graph & GetGraph ()
Graph & GetGraph () const
ModelOptions & GetModelOptions ()
void ExecuteStrategy (IStrategy &strategy) const
Detailed Description
Definition at line 11 of file OptimizedNetworkImpl.hpp.
Constructor & Destructor Documentation
OptimizedNetworkImpl() [1/3]
OptimizedNetworkImpl (const OptimizedNetworkImpl & other, const ModelOptions & modelOptions)
Definition at line 3096 of file Network.cpp.
     : m_Graph(new Graph(*other.m_Graph.get()))
     , m_Guid(arm::pipe::IProfilingService::GetNextGuid())
     , m_ModelOptions(modelOptions)
 {
 }
OptimizedNetworkImpl() [2/3]
OptimizedNetworkImpl (std::unique_ptr< Graph > graph)
Definition at line 3103 of file Network.cpp.
     : m_Graph(std::move(graph)), m_Guid(arm::pipe::IProfilingService::GetNextGuid())
 {
 }
OptimizedNetworkImpl() [3/3]
OptimizedNetworkImpl (std::unique_ptr< Graph > graph, const ModelOptions & modelOptions)
Definition at line 3108 of file Network.cpp.
     : m_Graph(std::move(graph)), m_Guid(arm::pipe::IProfilingService::GetNextGuid()), m_ModelOptions(modelOptions)
 {
 }
~OptimizedNetworkImpl()
~OptimizedNetworkImpl () virtual
Definition at line 3113 of file Network.cpp.
 {
 }
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const
Definition at line 3122 of file Network.cpp.
 {
     for (auto layer : GetGraph())
     {
         layer->ExecuteStrategy(strategy);
     };
 }
References OptimizedNetworkImpl::GetGraph().
GetGraph() [1/2]
Graph& GetGraph () inline
Definition at line 27 of file OptimizedNetworkImpl.hpp.
 { return *m_Graph; }
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssignBackendsIConnectable(), and OptimizedNetworkImpl::ExecuteStrategy().
GetGraph() [2/2]
Graph& GetGraph () const inline
Definition at line 28 of file OptimizedNetworkImpl.hpp.
 { return *m_Graph; }
GetGuid()
virtual arm::pipe::ProfilingGuid GetGuid () const inline virtual
Definition at line 22 of file OptimizedNetworkImpl.hpp.
 { return m_Guid; };
GetModelOptions()
ModelOptions& GetModelOptions () inline
Definition at line 29 of file OptimizedNetworkImpl.hpp.
 { return m_ModelOptions; }
GetNumInputs()
size_t GetNumInputs () const virtual
Definition at line 746 of file Network.cpp.
 {
     return m_Graph->GetNumInputs();
 }
GetNumOutputs()
size_t GetNumOutputs () const virtual
Definition at line 751 of file Network.cpp.
 {
     return m_Graph->GetNumOutputs();
 }
PrintGraph()
Status PrintGraph () virtual
Definition at line 735 of file Network.cpp.
 {
     m_Graph->Print();
     return Status::Success;
 }
References armnn::Success.
SerializeToDot()
Status SerializeToDot (std::ostream & stream) const virtual
Definition at line 741 of file Network.cpp.
 {
     return m_Graph->SerializeToDot(stream);
 }
The documentation for this class was generated from the following files:
src/armnn/OptimizedNetworkImpl.hpp
src/armnn/Network.cpp