Arm NN: SerializerStrategy Class Reference
SerializerStrategy Class Reference
#include <Serializer.hpp>
Public Member Functions
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id) override
SerializerStrategy ()
~SerializerStrategy ()
flatbuffers::FlatBufferBuilder & GetFlatBufferBuilder ()
std::vector< int > & GetInputIds ()
std::vector< int > & GetOutputIds ()
std::vector< flatbuffers::Offset< armnnSerializer::AnyLayer > > & GetSerializedLayers ()
flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > GetVersionTable ()
Public Member Functions inherited from IStrategy
virtual void ExecuteStrategy (const IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0)=0
virtual void FinishStrategy ()
Additional Inherited Members
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Detailed Description
Definition at line 22 of file Serializer.hpp.
Constructor & Destructor Documentation
SerializerStrategy()
SerializerStrategy () inline
Definition at line 31 of file Serializer.hpp.
 : m_layerId(0) {}
~SerializerStrategy()
~SerializerStrategy () inline
Definition at line 32 of file Serializer.hpp.
 {}
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id) override
Definition at line 2029 of file Serializer.cpp.
 {
     IgnoreUnused(constants);
     switch (layer->GetType())
     {
         case armnn::LayerType::Activation :
         {
             const armnn::ActivationDescriptor& layerDescriptor =
                     static_cast<const armnn::ActivationDescriptor&>(descriptor);
             SerializeActivationLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Addition :
         {
             SerializeAdditionLayer(layer, name);
             break;
         }
         case armnn::LayerType::ArgMinMax :
         {
             const armnn::ArgMinMaxDescriptor& layerDescriptor =
                     static_cast<const armnn::ArgMinMaxDescriptor&>(descriptor);
             SerializeArgMinMaxLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::BatchMatMul:
         {
             const armnn::BatchMatMulDescriptor& layerDescriptor =
                     static_cast<const armnn::BatchMatMulDescriptor&>(descriptor);
             SerializeBatchMatMulLayer(layer,
                                       layerDescriptor,
                                       name);
             break;
         }
         case armnn::LayerType::BatchNormalization :
         {
             const armnn::BatchNormalizationDescriptor& layerDescriptor =
                     static_cast<const armnn::BatchNormalizationDescriptor&>(descriptor);
             SerializeBatchNormalizationLayer(layer,
                                              layerDescriptor,
                                              constants,
                                              name);
             break;
         }
         case armnn::LayerType::BatchToSpaceNd :
         {
             const armnn::BatchToSpaceNdDescriptor& layerDescriptor =
                     static_cast<const armnn::BatchToSpaceNdDescriptor&>(descriptor);
             SerializeBatchToSpaceNdLayer(layer,
                                          layerDescriptor,
                                          name);
             break;
         }
         case armnn::LayerType::Cast :
         {
             SerializeCastLayer(layer, name);
             break;
         }
         case armnn::LayerType::ChannelShuffle :
         {
             const armnn::ChannelShuffleDescriptor& layerDescriptor =
                                                      static_cast<const armnn::ChannelShuffleDescriptor&>(descriptor);
             SerializeChannelShuffleLayer(layer,
                                          layerDescriptor,
                                          name);
             break;
         }
         case armnn::LayerType::Comparison :
         {
             const armnn::ComparisonDescriptor& layerDescriptor =
                     static_cast<const armnn::ComparisonDescriptor&>(descriptor);
             SerializeComparisonLayer(layer,
                                      layerDescriptor,
                                      name);
             break;
         }
         case armnn::LayerType::Concat :
         {
             const armnn::ConcatDescriptor& layerDescriptor =
                     static_cast<const armnn::ConcatDescriptor&>(descriptor);
             SerializeConcatLayer(layer,
                                  layerDescriptor,
                                  name);
             break;
         }
         case armnn::LayerType::Constant :
         {
             SerializeConstantLayer(layer,
                                    constants,
                                    name);
             break;
         }
         case armnn::LayerType::Convolution2d :
         {
             const armnn::Convolution2dDescriptor& layerDescriptor =
                     static_cast<const armnn::Convolution2dDescriptor&>(descriptor);
             SerializeConvolution2dLayer(layer,
                                         layerDescriptor,
                                         name);
             break;
         }
         case armnn::LayerType::Convolution3d :
         {
             const armnn::Convolution3dDescriptor& layerDescriptor =
                     static_cast<const armnn::Convolution3dDescriptor&>(descriptor);
             SerializeConvolution3dLayer(layer,
                                         layerDescriptor,
                                         name);
             break;
         }
         case armnn::LayerType::DepthToSpace :
         {
             const armnn::DepthToSpaceDescriptor& layerDescriptor =
                     static_cast<const armnn::DepthToSpaceDescriptor&>(descriptor);
             SerializeDepthToSpaceLayer(layer,
                                        layerDescriptor,
                                        name);
             break;
         }
         case armnn::LayerType::DepthwiseConvolution2d :
         {
             const armnn::DepthwiseConvolution2dDescriptor& layerDescriptor =
                     static_cast<const armnn::DepthwiseConvolution2dDescriptor&>(descriptor);
             SerializeDepthwiseConvolution2dLayer(layer,
                                                  layerDescriptor,
                                                  name);
             break;
         }
         case armnn::LayerType::Dequantize :
         {
             SerializeDequantizeLayer(layer,
                                      name);
             break;
         }
         case armnn::LayerType::DetectionPostProcess :
         {
             const armnn::DetectionPostProcessDescriptor& layerDescriptor =
                     static_cast<const armnn::DetectionPostProcessDescriptor&>(descriptor);
             SerializeDetectionPostProcessLayer(layer, layerDescriptor, constants, name);
             break;
         }
         case armnn::LayerType::Division :
         {
             SerializeDivisionLayer(layer, name);
             break;
         }
         case armnn::LayerType::ElementwiseBinary :
         {
             const armnn::ElementwiseBinaryDescriptor& layerDescriptor =
                     static_cast<const armnn::ElementwiseBinaryDescriptor&>(descriptor);
             SerializeElementwiseBinaryLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::ElementwiseUnary :
         {
             const armnn::ElementwiseUnaryDescriptor& layerDescriptor =
                     static_cast<const armnn::ElementwiseUnaryDescriptor&>(descriptor);
             SerializeElementwiseUnaryLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Fill :
         {
             const armnn::FillDescriptor& layerDescriptor =
                     static_cast<const armnn::FillDescriptor&>(descriptor);
             SerializeFillLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Floor :
         {
             SerializeFloorLayer(layer, name);
             break;
         }
         case armnn::LayerType::FullyConnected :
         {
             const armnn::FullyConnectedDescriptor& layerDescriptor =
                     static_cast<const armnn::FullyConnectedDescriptor&>(descriptor);
             SerializeFullyConnectedLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Gather :
         {
             const armnn::GatherDescriptor& layerDescriptor =
                     static_cast<const armnn::GatherDescriptor&>(descriptor);
             SerializeGatherLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::GatherNd :
         {
             SerializeGatherNdLayer(layer, name);
             break;
         }
         case armnn::LayerType::Input:
         {
             SerializeInputLayer(layer, id, name);
             break;
         }
         case armnn::LayerType::InstanceNormalization :
         {
             const armnn::InstanceNormalizationDescriptor& layerDescriptor =
                     static_cast<const armnn::InstanceNormalizationDescriptor&>(descriptor);
             SerializeInstanceNormalizationLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::L2Normalization :
         {
             const armnn::L2NormalizationDescriptor& layerDescriptor =
                     static_cast<const armnn::L2NormalizationDescriptor&>(descriptor);
             SerializeL2NormalizationLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::LogicalBinary :
         {
             const armnn::LogicalBinaryDescriptor& layerDescriptor =
                     static_cast<const armnn::LogicalBinaryDescriptor&>(descriptor);
             SerializeLogicalBinaryLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::LogSoftmax :
         {
             const armnn::LogSoftmaxDescriptor& layerDescriptor =
                     static_cast<const armnn::LogSoftmaxDescriptor&>(descriptor);
             SerializeLogSoftmaxLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Lstm :
         {
             const armnn::LstmDescriptor& layerDescriptor =
                     static_cast<const armnn::LstmDescriptor&>(descriptor);
             SerializeLstmLayer(layer, layerDescriptor, constants, name);
             break;
         }
         case armnn::LayerType::QLstm :
         {
             const armnn::QLstmDescriptor& layerDescriptor =
                     static_cast<const armnn::QLstmDescriptor&>(descriptor);
             SerializeQLstmLayer(layer, layerDescriptor, constants, name);
             break;
         }
         case armnn::LayerType::Maximum :
         {
             SerializeMaximumLayer(layer, name);
             break;
         }
         case armnn::LayerType::Mean :
         {
             const armnn::MeanDescriptor& layerDescriptor =
                     static_cast<const armnn::MeanDescriptor&>(descriptor);
             SerializeMeanLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Merge :
         {
             SerializeMergeLayer(layer, name);
             break;
         }
         case armnn::LayerType::Minimum :
         {
             SerializeMinimumLayer(layer, name);
             break;
         }
         case armnn::LayerType::Multiplication :
         {
             SerializeMultiplicationLayer(layer, name);
             break;
         }
         case armnn::LayerType::Normalization :
         {
             const armnn::NormalizationDescriptor& layerDescriptor =
                     static_cast<const armnn::NormalizationDescriptor&>(descriptor);
             SerializeNormalizationLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Output:
         {
             SerializeOutputLayer(layer, id, name);
             break;
         }
         case armnn::LayerType::Pad :
         {
             const armnn::PadDescriptor& layerDescriptor =
                     static_cast<const armnn::PadDescriptor&>(descriptor);
             SerializePadLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Permute :
         {
             const armnn::PermuteDescriptor& layerDescriptor =
                     static_cast<const armnn::PermuteDescriptor&>(descriptor);
             SerializePermuteLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Pooling2d :
         {
             const armnn::Pooling2dDescriptor& layerDescriptor =
                     static_cast<const armnn::Pooling2dDescriptor&>(descriptor);
             SerializePooling2dLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Pooling3d :
         {
             const armnn::Pooling3dDescriptor& layerDescriptor =
                     static_cast<const armnn::Pooling3dDescriptor&>(descriptor);
             SerializePooling3dLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Prelu :
         {
             SerializePreluLayer(layer, name);
             break;
         }
         case armnn::LayerType::Quantize :
         {
             SerializeQuantizeLayer(layer, name);
             break;
         }
         case armnn::LayerType::QuantizedLstm:
             SerializeQuantizedLstmLayer(layer, constants, name);
             break;
         case armnn::LayerType::Reshape:
         {
             const armnn::ReshapeDescriptor &layerDescriptor =
                     static_cast<const armnn::ReshapeDescriptor &>(descriptor);
             SerializeReshapeLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Rank:
         {
             SerializeRankLayer(layer, name);
             break;
         }
         case armnn::LayerType::Reduce:
         {
             const armnn::ReduceDescriptor& layerDescriptor =
                     static_cast<const armnn::ReduceDescriptor&>(descriptor);
             SerializeReduceLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Resize:
         {
             const armnn::ResizeDescriptor& layerDescriptor =
                     static_cast<const armnn::ResizeDescriptor&>(descriptor);
             SerializeResizeLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::ReverseV2:
         {
             SerializeReverseV2Layer(layer, name);
             break;
         }
         case armnn::LayerType::Shape:
         {
             SerializeShapeLayer(layer, name);
             break;
         }
         case armnn::LayerType::Slice:
         {
             const armnn::SliceDescriptor& layerDescriptor =
                     static_cast<const armnn::SliceDescriptor&>(descriptor);
             SerializeSliceLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Softmax:
         {
             const armnn::SoftmaxDescriptor& layerDescriptor =
                     static_cast<const armnn::SoftmaxDescriptor&>(descriptor);
             SerializeSoftmaxLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::SpaceToBatchNd:
         {
             const armnn::SpaceToBatchNdDescriptor& layerDescriptor =
                     static_cast<const armnn::SpaceToBatchNdDescriptor&>(descriptor);
             SerializeSpaceToBatchNdLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::SpaceToDepth:
         {
             const armnn::SpaceToDepthDescriptor& layerDescriptor =
                     static_cast<const armnn::SpaceToDepthDescriptor&>(descriptor);
             SerializeSpaceToDepthLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Splitter:
         {
             const armnn::SplitterDescriptor& layerDescriptor =
                     static_cast<const armnn::SplitterDescriptor&>(descriptor);
             SerializeSplitterLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Stack:
         {
             const armnn::StackDescriptor& layerDescriptor =
                     static_cast<const armnn::StackDescriptor&>(descriptor);
             SerializeStackLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::StandIn:
         {
             const armnn::StandInDescriptor& layerDescriptor =
                     static_cast<const armnn::StandInDescriptor&>(descriptor);
             SerializeStandInLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::StridedSlice:
         {
             const armnn::StridedSliceDescriptor& layerDescriptor =
                     static_cast<const armnn::StridedSliceDescriptor&>(descriptor);
             SerializeStridedSliceLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Subtraction:
         {
             SerializeSubtractionLayer(layer, name);
             break;
         }
         case armnn::LayerType::Switch:
         {
             SerializeSwitchLayer(layer, name);
             break;
         }
         case armnn::LayerType::Tile:
         {
             const armnn::TileDescriptor& layerDescriptor =
                     static_cast<const armnn::TileDescriptor&>(descriptor);
             SerializeTileLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::Transpose:
         {
             const armnn::TransposeDescriptor& layerDescriptor =
                     static_cast<const armnn::TransposeDescriptor&>(descriptor);
             SerializeTransposeLayer(layer, layerDescriptor, name);
             break;
         }
         case armnn::LayerType::TransposeConvolution2d:
         {
             const armnn::TransposeConvolution2dDescriptor& layerDescriptor =
                     static_cast<const armnn::TransposeConvolution2dDescriptor&>(descriptor);
             SerializeTransposeConvolution2dLayer(layer, layerDescriptor, constants, name);
             break;
         }
         case armnn::LayerType::UnidirectionalSequenceLstm :
         {
             const armnn::UnidirectionalSequenceLstmDescriptor& layerDescriptor =
                     static_cast<const armnn::UnidirectionalSequenceLstmDescriptor&>(descriptor);
             SerializeUnidirectionalSequenceLstmLayer(layer, layerDescriptor, constants, name);
             break;
         }
         default:
         {
             throw InvalidArgumentException(
                     fmt::format("A layer of unknown type was given to the serializer. Layer name: {}; Layer Id: {}",
                                 layer->GetName(),
                                 id));
         }
     }
 }
References armnn::Activation, armnn::Addition, armnn::ArgMinMax, armnn::BatchMatMul, armnn::BatchNormalization, armnn::BatchToSpaceNd, armnn::Cast, armnn::ChannelShuffle, armnn::Comparison, armnn::Concat, armnn::Constant, armnn::Convolution2d, armnn::Convolution3d, armnn::DepthToSpace, armnn::DepthwiseConvolution2d, armnn::Dequantize, armnn::DetectionPostProcess, armnn::Division, armnn::ElementwiseBinary, armnn::ElementwiseUnary, armnn::Fill, armnn::Floor, armnn::FullyConnected, armnn::Gather, armnn::GatherNd, IConnectableLayer::GetName(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), armnn::Input, armnn::InstanceNormalization, armnn::L2Normalization, armnn::LogicalBinary, armnn::LogSoftmax, armnn::Lstm, armnn::Maximum, armnn::Mean, armnn::Merge, armnn::Minimum, armnn::Multiplication, armnn::Normalization, armnn::Output, armnn::Pad, armnn::Permute, armnn::Pooling2d, armnn::Pooling3d, armnn::Prelu, armnn::QLstm, armnn::Quantize, armnn::QuantizedLstm, armnn::Rank, armnn::Reduce, armnn::Reshape, armnn::Resize, armnn::ReverseV2, armnn::Shape, armnn::Slice, armnn::Softmax, armnn::SpaceToBatchNd, armnn::SpaceToDepth, armnn::Splitter, armnn::Stack, armnn::StandIn, armnn::StridedSlice, armnn::Subtraction, armnn::Switch, armnn::Tile, armnn::Transpose, armnn::TransposeConvolution2d, and armnn::UnidirectionalSequenceLstm.
GetFlatBufferBuilder()
flatbuffers::FlatBufferBuilder& GetFlatBufferBuilder () inline
Definition at line 34 of file Serializer.hpp.
     {
         return m_flatBufferBuilder;
     }
GetInputIds()
std::vector<int>& GetInputIds () inline
Definition at line 39 of file Serializer.hpp.
     {
         return m_inputIds;
     }
GetOutputIds()
std::vector<int>& GetOutputIds () inline
Definition at line 44 of file Serializer.hpp.
     {
         return m_outputIds;
     }
GetSerializedLayers()
std::vector<flatbuffers::Offset<armnnSerializer::AnyLayer> >& GetSerializedLayers () inline
Definition at line 49 of file Serializer.hpp.
     {
         return m_serializedLayers;
     }
GetVersionTable()
flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > GetVersionTable ()
Definition at line 1972 of file Serializer.cpp.
 {
     flatbuffers::Offset<armnnSerializer::FeatureCompatibilityVersions> versionsTable =
         serializer::CreateFeatureCompatibilityVersions(
                 m_flatBufferBuilder,
                 1, // Binding ids scheme version
                 1, // Weights layout scheme version
                 1  // Constant tensors as inputs version
             );
     return versionsTable;
 }
The documentation for this class was generated from the following files:
src/armnnSerializer/Serializer.hpp
src/armnnSerializer/Serializer.cpp