Arm NN: IBackendInternal Class Reference
IBackendInternal Class Reference abstract
#include <IBackendInternal.hpp>
Public Types
using IWorkloadFactoryPtr = std::unique_ptr< IWorkloadFactory >
using IBackendContextPtr = std::unique_ptr< IBackendContext >
using IBackendProfilingContextPtr = std::shared_ptr< arm::pipe::IBackendProfilingContext >
This is the bridge between backend and backend profiling we'll keep it in the backend namespace.
using IBackendProfilingPtr = std::unique_ptr< arm::pipe::IBackendProfiling >
using ILayerSupportSharedPtr = std::shared_ptr< ILayerSupport >
using IBackendSpecificModelContextPtr = std::shared_ptr< IBackendModelContext >
using IMemoryManagerUniquePtr = std::unique_ptr< IMemoryManager >
using IMemoryManagerSharedPtr = std::shared_ptr< IMemoryManager >
Public Member Functions
~IBackendInternal () override=default
Allow backends created by the factory function to be destroyed through IBackendInternal.
virtual IMemoryManagerUniquePtr CreateMemoryManager () const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr &memoryManager=nullptr) const =0
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr &memoryManager, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags) const
virtual IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const
Create the runtime context of the backend.
virtual IBackendSpecificModelContextPtr CreateBackendSpecificModelContext (const ModelOptions &modelOptions) const
virtual IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions &creationOptions, IBackendProfilingPtr &backendProfiling)
Create context specifically used for profiling interaction from backends.
virtual ILayerSupportSharedPtr GetLayerSupport () const =0
virtual ILayerSupportSharedPtr GetLayerSupport (const ModelOptions &modelOptions) const
virtual OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph) const
virtual OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph, const ModelOptions &modelOptions) const
bool SupportsTensorAllocatorAPI () const
ITensorHandleFactory::FactoryId GetBackwardCompatibleFavoriteHandleFactory ()
virtual std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &)
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor() IWorkloadFactory::CreateSubtensor() methods must be implemented.
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &registry, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags)
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor() IWorkloadFactory::CreateSubtensor() methods must be implemented.
virtual BackendCapabilities GetCapabilities () const
Returns a BackendCapability if the backend lists the capability The BackendCapability must then be inspected to check whether or not that BackendCapability is supported Otherwise returns an EmptyOptional if the BackendCapability is unlisted.
virtual bool UseCustomMemoryAllocator (std::shared_ptr< ICustomAllocator > allocator, armnn::Optional< std::string & > errMsg)
Signals the backend to use a custom memory allocator provided by the user.
virtual std::unique_ptr< ICustomAllocator > GetDefaultAllocator () const
Returns the default memory allocator for the backend.
virtual unsigned int GetNumberOfCacheFiles () const
Returns the number of files cached if backend supports caching.
virtual ExecutionData CreateExecutionData (WorkingMemDescriptor &workingMemDescriptor) const
Returns ExecutionData for the backend.
virtual void UpdateExecutionData (ExecutionData &executionData, WorkingMemDescriptor &workingMemDescriptor) const
Update the ExecutionData for a layer.
Public Member Functions inherited from IBackend
virtual const BackendId & GetId () const =0
Static Public Member Functions
static constexpr BackendVersion GetApiVersion ()
Returns the version of the Backend API.
Protected Member Functions
IBackendInternal ()=default
Creation must be done through a specific backend interface.
Protected Member Functions inherited from IBackend
IBackend ()
virtual ~IBackend ()
Detailed Description
Definition at line 77 of file IBackendInternal.hpp.
Member Typedef Documentation
IBackendContextPtr
using IBackendContextPtr = std::unique_ptr<IBackendContext>
Definition at line 90 of file IBackendInternal.hpp.
IBackendProfilingContextPtr
using IBackendProfilingContextPtr = std::shared_ptr<arm::pipe::IBackendProfilingContext>
This is the bridge between backend and backend profiling we'll keep it in the backend namespace.
Definition at line 92 of file IBackendInternal.hpp.
IBackendProfilingPtr
using IBackendProfilingPtr = std::unique_ptr<arm::pipe::IBackendProfiling>
Definition at line 93 of file IBackendInternal.hpp.
IBackendSpecificModelContextPtr
using IBackendSpecificModelContextPtr = std::shared_ptr<IBackendModelContext>
Definition at line 96 of file IBackendInternal.hpp.
ILayerSupportSharedPtr
using ILayerSupportSharedPtr = std::shared_ptr<ILayerSupport>
Definition at line 94 of file IBackendInternal.hpp.
IMemoryManagerSharedPtr
using IMemoryManagerSharedPtr = std::shared_ptr<IMemoryManager>
Definition at line 99 of file IBackendInternal.hpp.
IMemoryManagerUniquePtr
using IMemoryManagerUniquePtr = std::unique_ptr<IMemoryManager>
Definition at line 98 of file IBackendInternal.hpp.
IWorkloadFactoryPtr
using IWorkloadFactoryPtr = std::unique_ptr<IWorkloadFactory>
Definition at line 89 of file IBackendInternal.hpp.
Constructor & Destructor Documentation
IBackendInternal()
IBackendInternal () protected default
Creation must be done through a specific backend interface.
~IBackendInternal()
~IBackendInternal () override default
Allow backends created by the factory function to be destroyed through IBackendInternal.
Member Function Documentation
CreateBackendContext()
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const virtual
Create the runtime context of the backend.
Implementations may return a default-constructed IBackendContextPtr if no context is needed at runtime. Implementations must throw BackendUnavailableException if the backend cannot be used (for example, necessary accelerator hardware is not present). The default implementation always returns a default-constructed pointer.
Reimplemented in GpuFsaBackend, ClBackend, NeonBackend, RefBackend, and TosaRefBackend.
Definition at line 71 of file IBackendInternal.cpp.
 {
     return IBackendContextPtr{};
 }
CreateBackendProfilingContext()
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions & creationOptions, IBackendProfilingPtr & backendProfiling) virtual
Create context specifically used for profiling interaction from backends.
Reimplemented in RefBackend, TosaRefBackend, GpuFsaBackend, ClBackend, and NeonBackend.
Definition at line 82 of file IBackendInternal.cpp.
 {
     return IBackendProfilingContextPtr{};
 }
CreateBackendSpecificModelContext()
IBackendInternal::IBackendSpecificModelContextPtr CreateBackendSpecificModelContext (const ModelOptions & modelOptions) const virtual
Reimplemented in ClBackend, and NeonBackend.
Definition at line 76 of file IBackendInternal.cpp.
 {
     return IBackendSpecificModelContextPtr{};
 }
CreateExecutionData()
virtual ExecutionData CreateExecutionData (WorkingMemDescriptor & workingMemDescriptor) const inline virtual
Returns ExecutionData for the backend.
Parameters
workingMemDescriptor - Vectors of input and output TensorHandles for a layer
Returns
- Returns backend specific ExecutionData generated for a layer
Reimplemented in RefBackend.
Definition at line 215 of file IBackendInternal.hpp.
     {
         IgnoreUnused(workingMemDescriptor);
         throw armnn::Exception("CreateExecutionData: Function has not been implemented in backend.");
     };
References armnn::IgnoreUnused().
CreateMemoryManager()
IMemoryManagerUniquePtr CreateMemoryManager () const virtual
Reimplemented in GpuFsaBackend, RefBackend, ClBackend, NeonBackend, and TosaRefBackend.
Definition at line 13 of file IBackendInternal.cpp.
 {
     return IMemoryManagerUniquePtr();
 }
CreateWorkloadFactory() [1/5]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry & tensorHandleFactoryRegistry) const virtual
Reimplemented in GpuFsaBackend, ClBackend, RefBackend, NeonBackend, and TosaRefBackend.
Definition at line 18 of file IBackendInternal.cpp.
 {
     return IWorkloadFactoryPtr{};
 }
CreateWorkloadFactory() [2/5]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry & tensorHandleFactoryRegistry, const ModelOptions & modelOptions) const virtual
Reimplemented in ClBackend, and NeonBackend.
Definition at line 42 of file IBackendInternal.cpp.
 {
     if (!modelOptions.empty())
     {
         for (auto optionsGroup : modelOptions)
         {
             if (optionsGroup.GetBackendId() == GetId())
             {
                 return IWorkloadFactoryPtr{};
             }
         }
     }
     return CreateWorkloadFactory(tensorHandleFactoryRegistry);
 }
References IBackendInternal::CreateWorkloadFactory(), and IBackend::GetId().
CreateWorkloadFactory() [3/5]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry & tensorHandleFactoryRegistry, const ModelOptions & modelOptions, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags) const virtual
Reimplemented in GpuFsaBackend, and ClBackend.
Definition at line 60 of file IBackendInternal.cpp.
 {
     IgnoreUnused(inputFlags);
     IgnoreUnused(outputFlags);
     return CreateWorkloadFactory(tensorHandleFactoryRegistry, modelOptions);
 }
References IBackendInternal::CreateWorkloadFactory(), and armnn::IgnoreUnused().
CreateWorkloadFactory() [4/5]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr & memoryManager, const ModelOptions & modelOptions) const virtual
Reimplemented in ClBackend, and NeonBackend.
Definition at line 24 of file IBackendInternal.cpp.
 {
     if (!modelOptions.empty())
     {
         for (auto optionsGroup : modelOptions)
         {
             if (optionsGroup.GetBackendId() == GetId())
             {
                 return IWorkloadFactoryPtr{};
             }
         }
     }
     return CreateWorkloadFactory(memoryManager);
 }
References IBackendInternal::CreateWorkloadFactory(), and IBackend::GetId().
CreateWorkloadFactory() [5/5]
virtual IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr & memoryManager = nullptr) const pure virtual
Implemented in GpuFsaBackend, RefBackend, ClBackend, NeonBackend, and TosaRefBackend.
Referenced by IBackendInternal::CreateWorkloadFactory().
GetApiVersion()
static constexpr BackendVersion GetApiVersion () inline static constexpr
Returns the version of the Backend API.
Definition at line 167 of file IBackendInternal.hpp.
 { return BackendVersion(1, 0); }
Referenced by DynamicBackend::DynamicBackend(), GetVersion(), and DynamicBackendUtils::IsBackendCompatible().
GetBackwardCompatibleFavoriteHandleFactory()
ITensorHandleFactory::FactoryId GetBackwardCompatibleFavoriteHandleFactory ()
Definition at line 132 of file IBackendInternal.cpp.
 {
     auto favorites = GetHandleFactoryPreferences();
     if (favorites.empty())
     {
         return ITensorHandleFactory::LegacyFactoryId;
     }
     return favorites[0];
 }
References IBackendInternal::GetHandleFactoryPreferences(), and ITensorHandleFactory::LegacyFactoryId.
GetCapabilities()
virtual BackendCapabilities GetCapabilities () const inline virtual
Returns a BackendCapability if the backend lists the capability The BackendCapability must then be inspected to check whether or not that BackendCapability is supported Otherwise returns an EmptyOptional if the BackendCapability is unlisted.
Reimplemented in GpuFsaBackend, ClBackend, NeonBackend, and RefBackend.
Definition at line 172 of file IBackendInternal.hpp.
     {
         return BackendCapabilities("IBackendInternal NullCapabilities");
     };
GetDefaultAllocator()
virtual std::unique_ptr<ICustomAllocator> GetDefaultAllocator () const inline virtual
Returns the default memory allocator for the backend.
Returns
- Returns unique pointer to the Default Allocator of the Backend
Reimplemented in GpuFsaBackend, ClBackend, NeonBackend, RefBackend, and TosaRefBackend.
Definition at line 201 of file IBackendInternal.hpp.
     {
         throw armnn::Exception("GetDefaultAllocator: Function has not been implemented in backend.");
     }
GetHandleFactoryPreferences()
std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const virtual
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
Reimplemented in GpuFsaBackend, NeonBackend, ClBackend, RefBackend, and TosaRefBackend.
Definition at line 143 of file IBackendInternal.cpp.
 {
     return std::vector<ITensorHandleFactory::FactoryId>();
 }
Referenced by armnn::CalculateSlotOption(), IBackendInternal::GetBackwardCompatibleFavoriteHandleFactory(), and IBackendInternal::SupportsTensorAllocatorAPI().
GetLayerSupport() [1/2]
virtual ILayerSupportSharedPtr GetLayerSupport () const pure virtual
Implemented in GpuFsaBackend, ClBackend, NeonBackend, RefBackend, and TosaRefBackend.
Referenced by IBackendInternal::GetLayerSupport().
GetLayerSupport() [2/2]
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport (const ModelOptions & modelOptions) const virtual
Reimplemented in ClBackend, and NeonBackend.
Definition at line 88 of file IBackendInternal.cpp.
 {
     if (!modelOptions.empty())
     {
         for (auto optionsGroup : modelOptions)
         {
             if (optionsGroup.GetBackendId() == GetId())
             {
                 return ILayerSupportSharedPtr{};
             }
         }
     }
     return GetLayerSupport();
 }
References IBackend::GetId(), and IBackendInternal::GetLayerSupport().
GetNumberOfCacheFiles()
virtual unsigned int GetNumberOfCacheFiles () const inline virtual
Returns the number of files cached if backend supports caching.
Returns
- Returns 0 if backend does not support caching otherwise number of files cached
Reimplemented in ClBackend.
Definition at line 209 of file IBackendInternal.hpp.
 { return 0; }
OptimizeSubgraphView() [1/2]
OptimizationViews OptimizeSubgraphView (const SubgraphView & subgraph) const virtual
Definition at line 106 of file IBackendInternal.cpp.
 {
     OptimizationViews result;
     result.AddUntouchedSubgraph(SubgraphView(subgraph));
     return result;
 }
References OptimizationViews::AddUntouchedSubgraph().
Referenced by IBackendInternal::OptimizeSubgraphView().
OptimizeSubgraphView() [2/2]
OptimizationViews OptimizeSubgraphView (const SubgraphView & subgraph, const ModelOptions & modelOptions) const virtual
Reimplemented in GpuFsaBackend, ClBackend, NeonBackend, RefBackend, and TosaRefBackend.
Definition at line 114 of file IBackendInternal.cpp.
 {
     return OptimizeSubgraphView(subgraph);
 }
References IBackendInternal::OptimizeSubgraphView().
RegisterTensorHandleFactories() [1/2]
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &) inline virtual
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor() IWorkloadFactory::CreateSubtensor() methods must be implemented.
Reimplemented in GpuFsaBackend, ClBackend, NeonBackend, RefBackend, and TosaRefBackend.
Definition at line 157 of file IBackendInternal.hpp.
 {}
Referenced by IBackendInternal::RegisterTensorHandleFactories().
RegisterTensorHandleFactories() [2/2]
void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry & registry, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags) virtual
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor() IWorkloadFactory::CreateSubtensor() methods must be implemented.
Reimplemented in GpuFsaBackend, and ClBackend.
Definition at line 125 of file IBackendInternal.cpp.
 {
     return RegisterTensorHandleFactories(registry);
 }
References IBackendInternal::RegisterTensorHandleFactories().
SupportsTensorAllocatorAPI()
bool SupportsTensorAllocatorAPI () const
Definition at line 120 of file IBackendInternal.cpp.
 {
     return !GetHandleFactoryPreferences().empty();
 }
References IBackendInternal::GetHandleFactoryPreferences().
UpdateExecutionData()
virtual void UpdateExecutionData (ExecutionData & executionData, WorkingMemDescriptor & workingMemDescriptor) const inline virtual
Update the ExecutionData for a layer.
It is used to swap in pre-imported tensor handles
Parameters
executionData - Backend specific ExecutionData generated for a layer
workingMemDescriptor - Vectors of input and output TensorHandles for a layer
Reimplemented in RefBackend.
Definition at line 225 of file IBackendInternal.hpp.
     {
         IgnoreUnused(executionData);
         IgnoreUnused(workingMemDescriptor);
         throw armnn::Exception("UpdateExecutionData: Function has not been implemented in backend.");
     };
References armnn::IgnoreUnused().
UseCustomMemoryAllocator()
virtual bool UseCustomMemoryAllocator (std::shared_ptr< ICustomAllocator > allocator, armnn::Optional< std::string & > errMsg) inline virtual
Signals the backend to use a custom memory allocator provided by the user.
Parameters
allocator - a pointer to the provided ICustomAllocator to use with this backend
errMsg - Optional string variable to return error messages
Returns
- Returns true if switching to custom allocator was successful
Reimplemented in GpuFsaBackend, and ClBackend.
Definition at line 182 of file IBackendInternal.hpp.
     {
         IgnoreUnused(allocator);
         if (errMsg)
         {
             std::stringstream message;
             message << "The backend " << GetId() << " doesn't support using a custom allocator. This error might"
                                                     " be related with the protected mode if the backend doesn't"
                                                     " fully support it.";
             errMsg.value() = message.str();
         }
         return false;
     }
References IBackend::GetId(), armnn::IgnoreUnused(), and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
The documentation for this class was generated from the following files:
include/armnn/backends/IBackendInternal.hpp
src/backends/backendsCommon/IBackendInternal.cpp