Arm NN: armnn::stringUtils Namespace Reference
armnn::stringUtils Namespace Reference
Functions
std::vector< std::string > StringTokenizer (const std::string &str, const char *delimiters, bool tokenCompression=true)
Function to take a string and a list of delimiters and split the string into tokens based on those delimiters This assumes that tokens are also to be split by newlines Enabling tokenCompression merges adjacent delimiters together, preventing empty tokens.
std::string & StringStartTrim (std::string &str, const std::string &chars="\t\n\v\f\r ")
Trim from the start of a string.
std::string & StringEndTrim (std::string &str, const std::string &chars="\t\n\v\f\r ")
Trim for the end of a string.
std::string & StringTrim (std::string &str, const std::string &chars="\t\n\v\f\r ")
Trim from both the start and the end of a string.
std::string StringTrimCopy (const std::string &str, const std::string &chars="\t\n\v\f\r ")
Trim from both the start and the end of a string, returns a trimmed copy of the string.
std::string StringConcat (const std::vector< std::string > &strings, std::string seperator="")
Takes a vector of strings and concatenates them together into one long std::string with an optional seperator between each.
void StringReplaceAll (std::string &str, const std::string &oldStr, const std::string &newStr)
Iterates over a given str and replaces all instance of substring oldStr with newStr.
bool StringToBool (const std::string &s, bool throw_on_error=true)
Converts a string to bool.
Function Documentation
StringConcat()
std::string armnn::stringUtils::StringConcat (const std::vector< std::string > & strings, std::string seperator = "") inline
Takes a vector of strings and concatenates them together into one long std::string with an optional seperator between each.
Definition at line 96 of file StringUtils.hpp.
 {
     std::stringstream ss;
     for (auto string : strings)
     {
         ss << string << seperator;
     }
     return ss.str();
 }
StringEndTrim()
std::string& armnn::stringUtils::StringEndTrim (std::string & str, const std::string & chars = "\t\n\v\f\r ") inline
Trim for the end of a string.
Definition at line 71 of file StringUtils.hpp.
 {
     str.erase(str.find_last_not_of(chars) + 1);
     return str;
 }
Referenced by StringTrim(), and StringTrimCopy().
StringReplaceAll()
void armnn::stringUtils::StringReplaceAll (std::string & str, const std::string & oldStr, const std::string & newStr) inline
Iterates over a given str and replaces all instance of substring oldStr with newStr.
Definition at line 109 of file StringUtils.hpp.
 {
     std::string::size_type pos = 0u;
     while ((pos = str.find(oldStr, pos)) != std::string::npos)
     {
         str.replace(pos, oldStr.length(), newStr);
         pos += newStr.length();
     }
 }
StringStartTrim()
std::string& armnn::stringUtils::StringStartTrim (std::string & str, const std::string & chars = "\t\n\v\f\r ") inline
Trim from the start of a string.
Definition at line 62 of file StringUtils.hpp.
 {
     str.erase(0, str.find_first_not_of(chars));
     return str;
 }
Referenced by StringTrim(), and StringTrimCopy().
StringToBool()
bool armnn::stringUtils::StringToBool (const std::string & s, bool throw_on_error = true) inline
Converts a string to bool.
Accepts "true", "false" (case-insensitive) and numbers, 1 (true) or 0 (false).
Parameters
s String to convert to bool
throw_on_error Bool variable to suppress error if conversion failed (Will return false in that case)
Returns
bool value
Definition at line 129 of file StringUtils.hpp.
 {
     // in case of failure to convert returns false
     auto result = false;
     // isstringstream fails if parsing didn't work
     std::istringstream is(s);
     // try integer conversion first. For the case s is a number
     is >> result;
     if (is.fail())
     {
         // transform to lower case to make case-insensitive
         std::string s_lower = s;
         std::transform(s_lower.begin(),
                        s_lower.end(),
                        s_lower.begin(),
                        [](unsigned char c){ return std::tolower(c); });
         is.str(s_lower);
         // try boolean -> s="false" or "true"
         is.clear();
         is >> std::boolalpha >> result;
     }
     if (is.fail() && throw_on_error)
     {
         throw armnn::InvalidArgumentException(s + " is not convertable to bool");
     }
     return result;
 }
StringTokenizer()
std::vector<std::string> armnn::stringUtils::StringTokenizer (const std::string & str, const char * delimiters, bool tokenCompression = true) inline
Function to take a string and a list of delimiters and split the string into tokens based on those delimiters This assumes that tokens are also to be split by newlines Enabling tokenCompression merges adjacent delimiters together, preventing empty tokens.
Definition at line 23 of file StringUtils.hpp.
 {
     std::stringstream stringStream(str);
     std::string line;
     std::vector<std::string> tokenVector;
     while (std::getline(stringStream, line))
     {
         std::size_t prev = 0;
         std::size_t pos;
         while ((pos = line.find_first_of(delimiters, prev)) != std::string::npos)
         {
             // Ignore adjacent tokens
             if (pos > prev)
             {
                 tokenVector.push_back(line.substr(prev, pos - prev));
             }
             // Unless token compression is disabled
             else if (!tokenCompression)
             {
                 tokenVector.push_back(line.substr(prev, pos - prev));
             }
             prev = pos + 1;
         }
         if (prev < line.length())
         {
             tokenVector.push_back(line.substr(prev, std::string::npos));
         }
     }
     return tokenVector;
 }
Referenced by DynamicBackendUtils::GetBackendPathsImpl().
StringTrim()
std::string& armnn::stringUtils::StringTrim (std::string & str, const std::string & chars = "\t\n\v\f\r ") inline
Trim from both the start and the end of a string.
Definition at line 80 of file StringUtils.hpp.
 {
     return StringStartTrim(StringEndTrim(str, chars), chars);
 }
References StringEndTrim(), and StringStartTrim().
StringTrimCopy()
std::string armnn::stringUtils::StringTrimCopy (const std::string & str, const std::string & chars = "\t\n\v\f\r ") inline
Trim from both the start and the end of a string, returns a trimmed copy of the string.
Definition at line 88 of file StringUtils.hpp.
 {
     std::string strCopy = str;
     return StringStartTrim(StringEndTrim(strCopy, chars), chars);
 }
References StringEndTrim(), and StringStartTrim().