Arm NN: StringifyLayerParameters< ViewsDescriptor > Struct Reference
StringifyLayerParameters< ViewsDescriptor > Struct Reference
#include <SerializeLayerParameters.hpp>
Static Public Member Functions
static void Serialize (ParameterStringifyFunction &fn, const ViewsDescriptor &desc)
Detailed Description
Definition at line 212 of file SerializeLayerParameters.hpp.
Member Function Documentation
Serialize()
void Serialize (ParameterStringifyFunction & fn, const ViewsDescriptor & desc) static
Definition at line 628 of file SerializeLayerParameters.cpp.
 {
     uint32_t numViews = desc.GetNumViews();
     uint32_t numDims  = desc.GetNumDimensions();
     for (uint32_t view = 0; view < numViews; ++view) {
         std::stringstream key;
         key << "ViewSizes#" << view;
         std::stringstream value;
         value << "[";
         auto viewData = desc.GetViewSizes(view);
         for (uint32_t dim = 0; dim < numDims; ++dim)
         {
             if (dim > 0)
             {
                 value << ",";
             }
             value << viewData[dim];
         }
         value << "]";
         fn(key.str(), value.str());
         if (desc.HasAxis())
         {
             fn("Axis", std::to_string(desc.GetAxis()));
         }
     }
     StringifyLayerParameters<OriginsDescriptor>::Serialize(fn, desc.GetOrigins());
 }
References ViewsDescriptor::GetAxis(), ViewsDescriptor::GetNumDimensions(), ViewsDescriptor::GetNumViews(), ViewsDescriptor::GetOrigins(), ViewsDescriptor::GetViewSizes(), ViewsDescriptor::HasAxis(), and StringifyLayerParameters< LayerParameter >::Serialize().
The documentation for this struct was generated from the following files:
src/armnn/SerializeLayerParameters.hpp
src/armnn/SerializeLayerParameters.cpp