ArmNN: src/backends/backendsCommon/test/layerTests/BatchNormalizationTestImpl.cpp File Reference
BatchNormalizationTestImpl.cpp File Reference
#include "BatchNormalizationTestImpl.hpp"
#include <QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <armnnUtils/DataLayoutIndexed.hpp>
#include <backendsCommon/CpuTensorHandle.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
LayerTestResult< float, 4 > BatchNormFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > BatchNormFloat32NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > BatchNormFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > BatchNormFloat16NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > BatchNormUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > BatchNormUint8NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > BatchNormInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > BatchNormInt16NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > CompareBatchNormTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory)
Function Documentation
BatchNormFloat16NhwcTest()
LayerTestResult<armnn::Half, 4> BatchNormFloat16NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 349 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NHWC);
 }
BatchNormFloat16Test()
LayerTestResult<armnn::Half, 4> BatchNormFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 303 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NCHW);
 }
BatchNormFloat32NhwcTest()
LayerTestResult<float, 4> BatchNormFloat32NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 253 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NHWC);
 }
BatchNormFloat32Test()
LayerTestResult<float, 4> BatchNormFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 207 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NCHW);
 }
BatchNormInt16NhwcTest()
LayerTestResult<int16_t, 4> BatchNormInt16NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 537 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         1.f / 20.f,
         50,
         armnn::DataLayout::NHWC);
 }
BatchNormInt16Test()
LayerTestResult<int16_t, 4> BatchNormInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 491 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         1.f / 20.f,
         50,
         armnn::DataLayout::NCHW);
 }
BatchNormUint8NhwcTest()
LayerTestResult<uint8_t, 4> BatchNormUint8NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 445 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         inputOutputShape, inputValues, expectedOutputValues,
          1.f/20.f, 50, armnn::DataLayout::NHWC);
 }
BatchNormUint8Test()
LayerTestResult<uint8_t, 4> BatchNormUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 399 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         1.f / 20.f,
         50,
         armnn::DataLayout::NCHW);
 }
CompareBatchNormTest()
LayerTestResult<float,4> CompareBatchNormTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory)
Definition at line 587 of file BatchNormalizationTestImpl.cpp.
References AllocateAndCopyDataToITensorHandle(), CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateBatchNormalization(), IWorkloadFactory::CreateTensorHandle(), armnn::Float32, armnn::IgnoreUnused(), BatchNormalizationQueueDescriptor::m_Beta, BatchNormalizationDescriptor::m_Eps, BatchNormalizationQueueDescriptor::m_Gamma, BatchNormalizationQueueDescriptor::m_Mean, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and BatchNormalizationQueueDescriptor::m_Variance.
 {
     IgnoreUnused(memoryManager);
     const unsigned int width     = 2;
     const unsigned int height    = 3;
     const unsigned int channels  = 5;
     const unsigned int batchSize = 3;
     armnn::TensorInfo inputTensorInfo;
     armnn::TensorInfo outputTensorInfo;
     armnn::TensorInfo tensorInfo;
     constexpr unsigned int shape[]       = {batchSize, channels, height, width};
     constexpr unsigned int tensorShape[] = {channels};
     inputTensorInfo = armnn::TensorInfo(4, shape, armnn::DataType::Float32);
     outputTensorInfo = armnn::TensorInfo(4, shape, armnn::DataType::Float32);
     tensorInfo = armnn::TensorInfo(1, tensorShape, armnn::DataType::Float32);
     auto input = MakeRandomTensor<float, 4>(inputTensorInfo, 21312);
     auto mean     = MakeRandomTensor<float, 1>(tensorInfo, 123);
     auto variance = MakeRandomTensor<float, 1>(tensorInfo, 234, 0.0f);
     auto beta     = MakeRandomTensor<float, 1>(tensorInfo, 123);
     auto gamma    = MakeRandomTensor<float, 1>(tensorInfo, 345);
     LayerTestResult<float,4> ret(outputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> inputHandle  = workloadFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = workloadFactory.CreateTensorHandle(outputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> inputHandleRef  = refWorkloadFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandleRef = refWorkloadFactory.CreateTensorHandle(outputTensorInfo);
     armnn::BatchNormalizationQueueDescriptor data;
     armnn::WorkloadInfo info;
     armnn::ScopedCpuTensorHandle meanTensor(tensorInfo);
     armnn::ScopedCpuTensorHandle varianceTensor(tensorInfo);
     armnn::ScopedCpuTensorHandle betaTensor(tensorInfo);
     armnn::ScopedCpuTensorHandle gammaTensor(tensorInfo);
     AllocateAndCopyDataToITensorHandle(&meanTensor, &mean[0]);
     AllocateAndCopyDataToITensorHandle(&varianceTensor, &variance[0]);
     AllocateAndCopyDataToITensorHandle(&betaTensor, &beta[0]);
     AllocateAndCopyDataToITensorHandle(&gammaTensor, &gamma[0]);
     AddInputToWorkload(data, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_Mean             = &meanTensor;
     data.m_Variance         = &varianceTensor;
     data.m_Beta             = &betaTensor;
     data.m_Gamma            = &gammaTensor;
     data.m_Parameters.m_Eps = 0.01f;
     armnn::BatchNormalizationQueueDescriptor refData = data;
     armnn::WorkloadInfo refInfo = info;
     SetWorkloadInput(refData, refInfo, 0, inputTensorInfo, inputHandleRef.get());
     SetWorkloadOutput(refData, refInfo, 0, outputTensorInfo, outputHandleRef.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateBatchNormalization(data, info);
     std::unique_ptr<armnn::IWorkload> workloadRef = refWorkloadFactory.CreateBatchNormalization(refData, refInfo);
     inputHandle->Allocate();
     outputHandle->Allocate();
     inputHandleRef->Allocate();
     outputHandleRef->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &input[0][0][0][0]);
     CopyDataToITensorHandle(inputHandleRef.get(), &input[0][0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     workloadRef->PostAllocationConfigure();
     workloadRef->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0][0], outputHandle.get());
     CopyDataFromITensorHandle(&ret.outputExpected[0][0][0][0], outputHandleRef.get());
     return ret;
 }