ArmNN: src/armnnTfLiteParser/test/OutputShapeOfSqueeze.cpp File Reference
OutputShapeOfSqueeze.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "../TfLiteParser.hpp"
#include <iostream>
#include <string>
Functions
BOOST_AUTO_TEST_SUITE (TensorflowLiteParser)
BOOST_FIXTURE_TEST_CASE (EmptySqueezeDims_OutputWithAllDimensionsSqueezed, TfLiteParserFixture)
BOOST_FIXTURE_TEST_CASE (SqueezeDimsNotIncludingSizeOneDimensions_NoDimensionsSqueezedInOutput, TfLiteParserFixture)
BOOST_FIXTURE_TEST_CASE (SqueezeDimsRangePartial_OutputWithDimensionsWithinRangeSqueezed, TfLiteParserFixture)
BOOST_AUTO_TEST_SUITE_END ()
Function Documentation
BOOST_AUTO_TEST_SUITE()
BOOST_AUTO_TEST_SUITE (TensorflowLiteParser)
Referenced by BOOST_AUTO_TEST_CASE(), armnn::boost_test_print_type(), TestQuantizedLstmLayerVisitor::CheckInputParameters(), CheckLayers(), CheckOrder(), armnn::GetProfilerEventSequenceSize(), PacketWriter(), and armnn::RuntimeLoadedNetworksReserve().
BOOST_AUTO_TEST_SUITE_END()
BOOST_AUTO_TEST_SUITE_END ()
Referenced by BOOST_FIXTURE_TEST_CASE().
BOOST_FIXTURE_TEST_CASE() [1/3]
BOOST_FIXTURE_TEST_CASE (EmptySqueezeDims_OutputWithAllDimensionsSqueezed , TfLiteParserFixture)
Definition at line 27 of file OutputShapeOfSqueeze.cpp.
References armnn::Float32, TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), and TfLiteParser::OutputShapeOfSqueeze().
 {
     std::vector<uint32_t> squeezeDims = {  };
     armnn::TensorInfo inputTensorInfo = armnn::TensorInfo(4, m_InputShape, armnn::DataType::Float32);
     armnn::TensorInfo outputTensorInfo = m_Parser.OutputShapeOfSqueeze(squeezeDims, inputTensorInfo);
     BOOST_TEST(outputTensorInfo.GetNumElements() == 4);
     BOOST_TEST(outputTensorInfo.GetNumDimensions() == 2);
     BOOST_TEST((outputTensorInfo.GetShape() == armnn::TensorShape({ 2, 2 })));
 };
BOOST_FIXTURE_TEST_CASE() [2/3]
BOOST_FIXTURE_TEST_CASE (SqueezeDimsNotIncludingSizeOneDimensions_NoDimensionsSqueezedInOutput , TfLiteParserFixture)
Definition at line 39 of file OutputShapeOfSqueeze.cpp.
References armnn::Float32, TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), and TfLiteParser::OutputShapeOfSqueeze().
 {
     std::vector<uint32_t> squeezeDims = { 1, 2 };
     armnn::TensorInfo inputTensorInfo = armnn::TensorInfo(4, m_InputShape, armnn::DataType::Float32);
     armnn::TensorInfo outputTensorInfo = m_Parser.OutputShapeOfSqueeze(squeezeDims, inputTensorInfo);
     BOOST_TEST(outputTensorInfo.GetNumElements() == 4);
     BOOST_TEST(outputTensorInfo.GetNumDimensions() == 4);
     BOOST_TEST((outputTensorInfo.GetShape() == armnn::TensorShape({ 1, 2, 2, 1 })));
 };
BOOST_FIXTURE_TEST_CASE() [3/3]
BOOST_FIXTURE_TEST_CASE (SqueezeDimsRangePartial_OutputWithDimensionsWithinRangeSqueezed , TfLiteParserFixture)
Definition at line 50 of file OutputShapeOfSqueeze.cpp.
References BOOST_AUTO_TEST_SUITE_END(), armnn::Float32, TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), and TfLiteParser::OutputShapeOfSqueeze().
 {
     std::vector<uint32_t> squeezeDims = { 1, 3 };
     armnn::TensorInfo inputTensorInfo = armnn::TensorInfo(4, m_InputShape, armnn::DataType::Float32);
     armnn::TensorInfo outputTensorInfo = m_Parser.OutputShapeOfSqueeze(squeezeDims, inputTensorInfo);
     BOOST_TEST(outputTensorInfo.GetNumElements() == 4);
     BOOST_TEST(outputTensorInfo.GetNumDimensions() == 3);
     BOOST_TEST((outputTensorInfo.GetShape() == armnn::TensorShape({ 1, 2, 2 })));
 };