ArmNN: src/backends/backendsCommon/test/layerTests/SpaceToDepthTestImpl.cpp File Reference
SpaceToDepthTestImpl.cpp File Reference
#include "SpaceToDepthTestImpl.hpp"
#include <QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnUtils/Permute.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
LayerTestResult< uint8_t, 4 > SpaceToDepthNhwcAsymmQ8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > SpaceToDepthNchwAsymmQ8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > SpaceToDepthNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > SpaceToDepthNchwFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > SpaceToDepthNhwcFloat32Test1 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > SpaceToDepthNchwFloat32Test1 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > SpaceToDepthNhwcFloat32Test2 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > SpaceToDepthNchwFloat32Test2 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > SpaceToDepthNhwcQSymm16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > SpaceToDepthNchwQSymm16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
SpaceToDepthNchwAsymmQ8Test()
LayerTestResult<uint8_t, 4> SpaceToDepthNchwAsymmQ8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 166 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToDepthNchwFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 185 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwFloat32Test1()
LayerTestResult<float, 4> SpaceToDepthNchwFloat32Test1 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 204 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwFloat32Test2()
LayerTestResult<float, 4> SpaceToDepthNchwFloat32Test2 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 223 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwQSymm16Test()
LayerTestResult<int16_t, 4> SpaceToDepthNchwQSymm16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 242 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNhwcAsymmQ8Test()
LayerTestResult<uint8_t, 4> SpaceToDepthNhwcAsymmQ8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 157 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager);
 }
SpaceToDepthNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToDepthNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 176 of file SpaceToDepthTestImpl.cpp.
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager);
 }
SpaceToDepthNhwcFloat32Test1()
LayerTestResult<float, 4> SpaceToDepthNhwcFloat32Test1 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 195 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager);
 }
SpaceToDepthNhwcFloat32Test2()
LayerTestResult<float, 4> SpaceToDepthNhwcFloat32Test2 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 214 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager);
 }
SpaceToDepthNhwcQSymm16Test()
LayerTestResult<int16_t, 4> SpaceToDepthNhwcQSymm16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 233 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager);
 }