ArmNN: PeriodicCounterSelectionResponseHandler Class Reference
PeriodicCounterSelectionResponseHandler Class Reference
#include <PeriodicCounterSelectionResponseHandler.hpp>
Public Member Functions
PeriodicCounterSelectionResponseHandler (uint32_t familyId, uint32_t packetId, uint32_t version, bool quietOperation=true)
void operator() (const armnn::profiling::Packet &packet) override
Public Member Functions inherited from CommandHandlerFunctor
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
virtual void operator() (const Packet &packet)=0
virtual ~CommandHandlerFunctor ()
Detailed Description
Definition at line 18 of file PeriodicCounterSelectionResponseHandler.hpp.
Constructor & Destructor Documentation
PeriodicCounterSelectionResponseHandler()
PeriodicCounterSelectionResponseHandler (uint32_t familyId, uint32_t packetId, uint32_t version, bool quietOperation = true) inline
Parameters
packetId The id of packets this handler will process.
version The version of that id.
quietOperation Optional parameter to turn off printouts. This is useful for unittests.
Definition at line 28 of file PeriodicCounterSelectionResponseHandler.hpp.
References PeriodicCounterSelectionResponseHandler::operator()().
         : CommandHandlerFunctor(familyId, packetId, version)
         , m_QuietOperation(quietOperation)
     {}
Member Function Documentation
operator()()
void operator() (const armnn::profiling::Packet & packet) override
Definition at line 18 of file PeriodicCounterSelectionResponseHandler.cpp.
References armnn::profiling::ReadUint32().
Referenced by PeriodicCounterSelectionResponseHandler::PeriodicCounterSelectionResponseHandler().
 {
     if (!m_QuietOperation)    // Are we supposed to print to stdout?
     {
         uint32_t period = profiling::ReadUint32(reinterpret_cast<const unsigned char*>(packet.GetData()), 0);
         uint32_t numCounters = 0;
         // First check if there are any counters mentioned.
         if(packet.GetLength() > 4)
         {
             // Length will be 4 bytes for the period and then a list of 16 bit UIDS.
             numCounters = ((packet.GetLength() - 4) / 2);
         }
         std::cout << "PeriodicCounterSelectionResponse: Collection interval = " << std::dec << period << "uSec"
                   << " Num counters activated = " << numCounters << std::endl;
     }
 }
The documentation for this class was generated from the following files:
tests/profiling/gatordmock/PeriodicCounterSelectionResponseHandler.hpp
tests/profiling/gatordmock/PeriodicCounterSelectionResponseHandler.cpp