ArmNN: ActivateTimelineReportingCommandHandler Class Reference
ActivateTimelineReportingCommandHandler Class Reference
#include <ActivateTimelineReportingCommandHandler.hpp>
Public Member Functions
ActivateTimelineReportingCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, SendTimelinePacket &sendTimelinePacket, ProfilingStateMachine &profilingStateMachine, Optional< IReportStructure &> reportStructure, std::atomic< bool > &timelineReporting, INotifyBackends &notifyBackends)
void operator() (const Packet &packet) override
Public Member Functions inherited from CommandHandlerFunctor
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
virtual ~CommandHandlerFunctor ()
Detailed Description
Definition at line 25 of file ActivateTimelineReportingCommandHandler.hpp.
Constructor & Destructor Documentation
ActivateTimelineReportingCommandHandler()
ActivateTimelineReportingCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, SendTimelinePacket & sendTimelinePacket, ProfilingStateMachine & profilingStateMachine, Optional< IReportStructure &> reportStructure, std::atomic< bool > & timelineReporting, INotifyBackends & notifyBackends) inline
Definition at line 28 of file ActivateTimelineReportingCommandHandler.hpp.
References ActivateTimelineReportingCommandHandler::operator()().
         : CommandHandlerFunctor(familyId, packetId, version),
           m_SendTimelinePacket(sendTimelinePacket),
           m_StateMachine(profilingStateMachine),
           m_TimelineReporting(timelineReporting),
           m_BackendNotifier(notifyBackends),
           m_ReportStructure(reportStructure)
     {}
Member Function Documentation
operator()()
void operator() (const Packet & packet) override virtual
Implements CommandHandlerFunctor.
Definition at line 18 of file ActivateTimelineReportingCommandHandler.cpp.
References armnn::profiling::Active, ProfilingStateMachine::GetCurrentState(), armnn::profiling::GetProfilingStateName(), armnn::profiling::NotConnected, INotifyBackends::NotifyBackendsForTimelineReporting(), SendTimelinePacket::SendTimelineMessageDirectoryPackage(), TimelineUtilityMethods::SendWellKnownLabelsAndEventClasses(), armnn::profiling::Uninitialised, and armnn::profiling::WaitingForAck.
Referenced by ActivateTimelineReportingCommandHandler::ActivateTimelineReportingCommandHandler().
 {
     ProfilingState currentState = m_StateMachine.GetCurrentState();
     if (!m_ReportStructure.has_value())
     {
             throw armnn::Exception(std::string("Profiling Service constructor must be initialised with an "
                                                "IReportStructure argument in order to run timeline reporting"));
     }
     switch ( currentState )
     {
         case ProfilingState::Uninitialised:
         case ProfilingState::NotConnected:
         case ProfilingState::WaitingForAck:
             throw RuntimeException(boost::str(
                 boost::format("Activate Timeline Reporting Command Handler invoked while in a wrong state: %1%")
                     % GetProfilingStateName(currentState)));
         case ProfilingState::Active:
             if ( !( packet.GetPacketFamily() == 0u && packet.GetPacketId() == 6u ))
             {
                 throw armnn::Exception(std::string("Expected Packet family = 0, id = 6 but received family =")
                                            + std::to_string(packet.GetPacketFamily())
                                            + " id = " + std::to_string(packet.GetPacketId()));
             }
             m_SendTimelinePacket.SendTimelineMessageDirectoryPackage();
             TimelineUtilityMethods::SendWellKnownLabelsAndEventClasses(m_SendTimelinePacket);
             m_TimelineReporting = true;
             m_ReportStructure.value().ReportStructure();
             m_BackendNotifier.NotifyBackendsForTimelineReporting();
             break;
         default:
             throw RuntimeException(boost::str(boost::format("Unknown profiling service state: %1%")
                                                   % static_cast<int>(currentState)));
     }
 }
The documentation for this class was generated from the following files:
src/profiling/ActivateTimelineReportingCommandHandler.hpp
src/profiling/ActivateTimelineReportingCommandHandler.cpp