ArmNN: MockSendCounterPacket Class Reference
MockSendCounterPacket Class Reference
#include <ProfilingMocks.hpp>
Public Member Functions
MockSendCounterPacket (IBufferManager &sendBuffer)
void SendStreamMetaDataPacket () override
Create and write a StreamMetaDataPacket in the buffer.
void SendCounterDirectoryPacket (const ICounterDirectory &counterDirectory) override
Create and write a CounterDirectoryPacket from the parameters to the buffer.
void SendPeriodicCounterCapturePacket (uint64_t timestamp, const std::vector< CounterValue > &values) override
void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > &selectedCounterIds) override
Create and write a PeriodicCounterSelectionPacket from the parameters to the buffer.
Public Member Functions inherited from ISendCounterPacket
virtual ~ISendCounterPacket ()
virtual void SendPeriodicCounterCapturePacket (uint64_t timestamp, const IndexValuePairsVector &values)=0
Create and write a PeriodicCounterCapturePacket from the parameters to the buffer.
Additional Inherited Members
Public Types inherited from ISendCounterPacket
using IndexValuePairsVector = std::vector< CounterValue >
Detailed Description
Definition at line 388 of file ProfilingMocks.hpp.
Constructor & Destructor Documentation
MockSendCounterPacket()
MockSendCounterPacket (IBufferManager & sendBuffer) inline
Definition at line 391 of file ProfilingMocks.hpp.
 : m_BufferManager(sendBuffer) {}
Member Function Documentation
SendCounterDirectoryPacket()
void SendCounterDirectoryPacket (const ICounterDirectory & counterDirectory) inline override virtual
Create and write a CounterDirectoryPacket from the parameters to the buffer.
Implements ISendCounterPacket.
Definition at line 402 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         IgnoreUnused(counterDirectory);
         std::string message("SendCounterDirectoryPacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved);
     }
SendPeriodicCounterCapturePacket()
void SendPeriodicCounterCapturePacket (uint64_t timestamp, const std::vector< CounterValue > & values) inline override
Definition at line 413 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         IgnoreUnused(timestamp, values);
         std::string message("SendPeriodicCounterCapturePacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved);
     }
SendPeriodicCounterSelectionPacket()
void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > & selectedCounterIds) inline override virtual
Create and write a PeriodicCounterSelectionPacket from the parameters to the buffer.
Implements ISendCounterPacket.
Definition at line 425 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         IgnoreUnused(capturePeriod, selectedCounterIds);
         std::string message("SendPeriodicCounterSelectionPacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved);
     }
SendStreamMetaDataPacket()
void SendStreamMetaDataPacket () inline override virtual
Create and write a StreamMetaDataPacket in the buffer.
Implements ISendCounterPacket.
Definition at line 393 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         std::string message("SendStreamMetaDataPacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved, false);
     }
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingMocks.hpp