ArmNN: MockProfilingConnection Class Reference
MockProfilingConnection Class Reference
#include <ProfilingMocks.hpp>
Public Types
enum PacketType {
StreamMetaData, ConnectionAcknowledge, CounterDirectory, ReqCounterDirectory,
PeriodicCounterSelection, PerJobCounterSelection, TimelineMessageDirectory, PeriodicCounterCapture,
ActivateTimelineReporting, DeactivateTimelineReporting, Unknown
}
Public Member Functions
MockProfilingConnection ()
bool IsOpen () const override
void Close () override
bool WritePacket (const unsigned char *buffer, uint32_t length) override
long CheckForPacket (const std::pair< PacketType, uint32_t > packetInfo)
bool WritePacket (Packet &&packet)
Packet ReadPacket (uint32_t timeout) override
unsigned long GetWrittenDataSize ()
void Clear ()
Public Member Functions inherited from IProfilingConnection
virtual ~IProfilingConnection ()
Detailed Description
Definition at line 35 of file ProfilingMocks.hpp.
Member Enumeration Documentation
PacketType
enum PacketType strong
Enumerator
StreamMetaData
ConnectionAcknowledge
CounterDirectory
ReqCounterDirectory
PeriodicCounterSelection
PerJobCounterSelection
TimelineMessageDirectory
PeriodicCounterCapture
ActivateTimelineReporting
DeactivateTimelineReporting
Unknown
Definition at line 44 of file ProfilingMocks.hpp.
     {
         StreamMetaData,
         ConnectionAcknowledge,
         CounterDirectory,
         ReqCounterDirectory,
         PeriodicCounterSelection,
         PerJobCounterSelection,
         TimelineMessageDirectory,
         PeriodicCounterCapture,
         ActivateTimelineReporting,
         DeactivateTimelineReporting,
         Unknown
     };
Constructor & Destructor Documentation
MockProfilingConnection()
MockProfilingConnection () inline
Definition at line 38 of file ProfilingMocks.hpp.
         : m_IsOpen(true)
         , m_WrittenData()
         , m_Packet()
     {}
Member Function Documentation
CheckForPacket()
long CheckForPacket (const std::pair< PacketType, uint32_t > packetInfo) inline
Definition at line 108 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and SwapProfilingConnectionFactoryHelper::WaitForPacketsSent().
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         if(packetInfo.second != 0)
         {
             return std::count(m_WrittenData.begin(), m_WrittenData.end(), packetInfo);
         }
         else
         {
             return std::count_if(m_WrittenData.begin(), m_WrittenData.end(),
             [&packetInfo](const std::pair<PacketType, uint32_t> pair) { return packetInfo.first == pair.first; });
         }
     }
Clear()
void Clear () inline
Definition at line 148 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         m_WrittenData.clear();
     }
Close()
void Close () inline override virtual
Implements IProfilingConnection.
Definition at line 66 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         m_IsOpen = false;
     }
GetWrittenDataSize()
unsigned long GetWrittenDataSize () inline
Definition at line 141 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         return m_WrittenData.size();
     }
IsOpen()
bool IsOpen () const inline override virtual
Implements IProfilingConnection.
Definition at line 59 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         return m_IsOpen;
     }
ReadPacket()
Packet ReadPacket (uint32_t timeout) inline override virtual
Implements IProfilingConnection.
Definition at line 131 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
     {
         IgnoreUnused(timeout);
         // Simulate a delay in the reading process. The default timeout is way too long.
         std::this_thread::sleep_for(std::chrono::milliseconds(5));
         std::lock_guard<std::mutex> lock(m_Mutex);
         return std::move(m_Packet);
     }
WritePacket() [1/2]
bool WritePacket (const unsigned char * buffer, uint32_t length) inline override virtual
Implements IProfilingConnection.
Definition at line 73 of file ProfilingMocks.hpp.
References MockProfilingConnection::PeriodicCounterCapture, armnn::profiling::ReadUint32(), MockProfilingConnection::TimelineMessageDirectory, and MockProfilingConnection::Unknown.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         if (buffer == nullptr || length == 0)
         {
             return false;
         }
         uint32_t header = ReadUint32(buffer, 0);
         uint32_t packetFamily = (header >> 26);
         uint32_t packetId = ((header >> 16) & 1023);
         PacketType packetType;
         switch (packetFamily)
         {
             case 0:
                 packetType = packetId < 8 ? PacketType(packetId) : PacketType::Unknown;
                 break;
             case 1:
                 packetType = packetId == 0 ? PacketType::TimelineMessageDirectory : PacketType::Unknown;
                 break;
             case 3:
                 packetType = packetId == 0 ? PacketType::PeriodicCounterCapture : PacketType::Unknown;
                 break;
             default:
                 packetType = PacketType::Unknown;
         }
         std::lock_guard<std::mutex> lock(m_Mutex);
         m_WrittenData.push_back({ packetType, length });
         return true;
     }
WritePacket() [2/2]
bool WritePacket (Packet && packet) inline
Definition at line 123 of file ProfilingMocks.hpp.
     {
         std::lock_guard<std::mutex> lock(m_Mutex);
         m_Packet = std::move(packet);
         return true;
     }
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingMocks.hpp