ArmNN: BaseMemoryManager Class Reference
BaseMemoryManager Class Reference abstract
#include <BaseMemoryManager.hpp>
Public Types
enum MemoryAffinity { Buffer, Offset }
Public Member Functions
BaseMemoryManager ()
virtual ~BaseMemoryManager ()
void Acquire () override
void Release () override
BaseMemoryManager (std::unique_ptr< arm_compute::IAllocator > alloc, MemoryAffinity memoryAffinity)
std::shared_ptr< arm_compute::MemoryManagerOnDemand > & GetIntraLayerManager ()
std::shared_ptr< arm_compute::MemoryManagerOnDemand > & GetInterLayerManager ()
std::shared_ptr< arm_compute::IMemoryGroup > & GetInterLayerMemoryGroup ()
Public Member Functions inherited from IMemoryManager
virtual ~IMemoryManager ()
Protected Member Functions
std::shared_ptr< arm_compute::MemoryManagerOnDemand > CreateArmComputeMemoryManager (MemoryAffinity memoryAffinity)
virtual std::shared_ptr< arm_compute::IMemoryGroup > CreateMemoryGroup (const std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager)=0
Protected Member Functions inherited from IMemoryManager
IMemoryManager ()
Protected Attributes
std::unique_ptr< arm_compute::IAllocator > m_Allocator
std::shared_ptr< arm_compute::MemoryManagerOnDemand > m_IntraLayerMemoryMgr
std::shared_ptr< arm_compute::MemoryManagerOnDemand > m_InterLayerMemoryMgr
std::shared_ptr< arm_compute::IMemoryGroup > m_InterLayerMemoryGroup
Detailed Description
Definition at line 23 of file BaseMemoryManager.hpp.
Member Enumeration Documentation
MemoryAffinity
enum MemoryAffinity strong
Enumerator
Buffer
Offset
Definition at line 26 of file BaseMemoryManager.hpp.
     {
         Buffer,
         Offset
     };
Constructor & Destructor Documentation
BaseMemoryManager() [1/2]
BaseMemoryManager () inline
Definition at line 32 of file BaseMemoryManager.hpp.
Referenced by BaseMemoryManager::~BaseMemoryManager().
 { }
~BaseMemoryManager()
virtual ~BaseMemoryManager () inline virtual
Definition at line 33 of file BaseMemoryManager.hpp.
References BaseMemoryManager::Acquire(), BaseMemoryManager::BaseMemoryManager(), and BaseMemoryManager::Release().
 { }
BaseMemoryManager() [2/2]
BaseMemoryManager (std::unique_ptr< arm_compute::IAllocator > alloc, MemoryAffinity memoryAffinity)
Definition at line 18 of file BaseMemoryManager.cpp.
References ARMNN_ASSERT, BaseMemoryManager::CreateArmComputeMemoryManager(), BaseMemoryManager::m_Allocator, BaseMemoryManager::m_InterLayerMemoryMgr, and BaseMemoryManager::m_IntraLayerMemoryMgr.
 {
     ARMNN_ASSERT(alloc);
     m_Allocator = std::move(alloc);
     m_IntraLayerMemoryMgr = CreateArmComputeMemoryManager(memoryAffinity);
     m_InterLayerMemoryMgr = CreateArmComputeMemoryManager(memoryAffinity);
 }
Member Function Documentation
Acquire()
void Acquire () override virtual
Implements IMemoryManager.
Definition at line 48 of file BaseMemoryManager.cpp.
References ARMNN_ASSERT, BaseMemoryManager::m_Allocator, BaseMemoryManager::m_InterLayerMemoryGroup, BaseMemoryManager::m_InterLayerMemoryMgr, and BaseMemoryManager::m_IntraLayerMemoryMgr.
Referenced by BaseMemoryManager::Release(), and BaseMemoryManager::~BaseMemoryManager().
 {
     static const size_t s_NumPools = 1;
     // Allocate memory pools for intra-layer memory manager
     ARMNN_ASSERT(m_IntraLayerMemoryMgr);
     m_IntraLayerMemoryMgr->populate(*m_Allocator, s_NumPools);
     // Allocate memory pools for inter-layer memory manager
     ARMNN_ASSERT(m_InterLayerMemoryMgr);
     m_InterLayerMemoryMgr->populate(*m_Allocator, s_NumPools);
     // Acquire inter-layer memory group. NOTE: This has to come after allocating the pools
     ARMNN_ASSERT(m_InterLayerMemoryGroup);
     m_InterLayerMemoryGroup->acquire();
 }
CreateArmComputeMemoryManager()
std::shared_ptr< arm_compute::MemoryManagerOnDemand > CreateArmComputeMemoryManager (MemoryAffinity memoryAffinity) protected
Definition at line 29 of file BaseMemoryManager.cpp.
References BaseMemoryManager::Buffer.
Referenced by BaseMemoryManager::BaseMemoryManager().
 {
     std::shared_ptr<arm_compute::ILifetimeManager> lifetimeManager = nullptr;
     if (memoryAffinity == MemoryAffinity::Buffer)
     {
         lifetimeManager = std::make_shared<arm_compute::BlobLifetimeManager>();
     }
     else
     {
         lifetimeManager = std::make_shared<arm_compute::OffsetLifetimeManager>();
     }
     auto poolManager   = std::make_shared<arm_compute::PoolManager>();
     auto memoryManager = std::make_shared<arm_compute::MemoryManagerOnDemand>(lifetimeManager, poolManager);
     return memoryManager;
 }
CreateMemoryGroup()
virtual std::shared_ptr<arm_compute::IMemoryGroup> CreateMemoryGroup (const std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager) protected pure virtual
Implemented in ClMemoryManager, and NeonMemoryManager.
Referenced by ClMemoryManager::ClMemoryManager(), and NeonMemoryManager::NeonMemoryManager().
GetInterLayerManager()
std::shared_ptr<arm_compute::MemoryManagerOnDemand>& GetInterLayerManager () inline
Definition at line 42 of file BaseMemoryManager.hpp.
References BaseMemoryManager::m_InterLayerMemoryMgr.
 { return m_InterLayerMemoryMgr; }
GetInterLayerMemoryGroup()
std::shared_ptr<arm_compute::IMemoryGroup>& GetInterLayerMemoryGroup () inline
Definition at line 43 of file BaseMemoryManager.hpp.
References BaseMemoryManager::m_InterLayerMemoryGroup.
 { return m_InterLayerMemoryGroup; }
GetIntraLayerManager()
std::shared_ptr<arm_compute::MemoryManagerOnDemand>& GetIntraLayerManager () inline
Definition at line 41 of file BaseMemoryManager.hpp.
References BaseMemoryManager::m_IntraLayerMemoryMgr.
 { return m_IntraLayerMemoryMgr; }
Release()
void Release () override virtual
Implements IMemoryManager.
Definition at line 65 of file BaseMemoryManager.cpp.
References BaseMemoryManager::Acquire(), ARMNN_ASSERT, BaseMemoryManager::m_InterLayerMemoryGroup, BaseMemoryManager::m_InterLayerMemoryMgr, and BaseMemoryManager::m_IntraLayerMemoryMgr.
Referenced by BaseMemoryManager::~BaseMemoryManager().
 {
     // Release inter-layer memory group. NOTE: This has to come before releasing the pools
     ARMNN_ASSERT(m_InterLayerMemoryGroup);
     m_InterLayerMemoryGroup->release();
     // Release memory pools managed by intra-layer memory manager
     ARMNN_ASSERT(m_IntraLayerMemoryMgr);
     m_IntraLayerMemoryMgr->clear();
     // Release memory pools managed by inter-layer memory manager
     ARMNN_ASSERT(m_InterLayerMemoryMgr);
     m_InterLayerMemoryMgr->clear();
 }
Member Data Documentation
m_Allocator
std::unique_ptr<arm_compute::IAllocator> m_Allocator protected
Definition at line 46 of file BaseMemoryManager.hpp.
Referenced by BaseMemoryManager::Acquire(), and BaseMemoryManager::BaseMemoryManager().
m_InterLayerMemoryGroup
std::shared_ptr<arm_compute::IMemoryGroup> m_InterLayerMemoryGroup protected
Definition at line 49 of file BaseMemoryManager.hpp.
Referenced by BaseMemoryManager::Acquire(), ClMemoryManager::ClMemoryManager(), BaseMemoryManager::GetInterLayerMemoryGroup(), NeonMemoryManager::NeonMemoryManager(), and BaseMemoryManager::Release().
m_InterLayerMemoryMgr
std::shared_ptr<arm_compute::MemoryManagerOnDemand> m_InterLayerMemoryMgr protected
Definition at line 48 of file BaseMemoryManager.hpp.
Referenced by BaseMemoryManager::Acquire(), BaseMemoryManager::BaseMemoryManager(), ClMemoryManager::ClMemoryManager(), BaseMemoryManager::GetInterLayerManager(), NeonMemoryManager::NeonMemoryManager(), and BaseMemoryManager::Release().
m_IntraLayerMemoryMgr
std::shared_ptr<arm_compute::MemoryManagerOnDemand> m_IntraLayerMemoryMgr protected
Definition at line 47 of file BaseMemoryManager.hpp.
Referenced by BaseMemoryManager::Acquire(), BaseMemoryManager::BaseMemoryManager(), BaseMemoryManager::GetIntraLayerManager(), and BaseMemoryManager::Release().
The documentation for this class was generated from the following files:
src/backends/aclCommon/BaseMemoryManager.hpp
src/backends/aclCommon/BaseMemoryManager.cpp