ArmNN: IWorkloadFactory Class Reference
IWorkloadFactory Class Reference abstract
#include <WorkloadFactory.hpp>
Public Member Functions
virtual ~IWorkloadFactory ()
virtual const BackendId & GetBackendId () const =0
virtual bool SupportsSubTensors () const =0
virtual std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const =0
virtual std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &descriptor, const WorkloadInfo &info) const =0
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const =0
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const =0
virtual std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMerge (const MergeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMerger (const MergerQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateSwitch (const SwitchQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const
Static Public Member Functions
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
Detailed Description
Definition at line 21 of file WorkloadFactory.hpp.
Constructor & Destructor Documentation
~IWorkloadFactory()
virtual ~IWorkloadFactory () inline virtual
Definition at line 24 of file WorkloadFactory.hpp.
References ARMNN_DEPRECATED_MSG, IWorkloadFactory::CreateAbs(), IWorkloadFactory::CreateActivation(), IWorkloadFactory::CreateAddition(), IWorkloadFactory::CreateArgMinMax(), IWorkloadFactory::CreateBatchNormalization(), IWorkloadFactory::CreateBatchToSpaceNd(), IWorkloadFactory::CreateComparison(), IWorkloadFactory::CreateConcat(), IWorkloadFactory::CreateConstant(), IWorkloadFactory::CreateConvertBf16ToFp32(), IWorkloadFactory::CreateConvertFp16ToFp32(), IWorkloadFactory::CreateConvertFp32ToBf16(), IWorkloadFactory::CreateConvertFp32ToFp16(), IWorkloadFactory::CreateConvolution2d(), IWorkloadFactory::CreateDebug(), IWorkloadFactory::CreateDepthToSpace(), IWorkloadFactory::CreateDepthwiseConvolution2d(), IWorkloadFactory::CreateDequantize(), IWorkloadFactory::CreateDetectionPostProcess(), IWorkloadFactory::CreateDivision(), IWorkloadFactory::CreateElementwiseUnary(), IWorkloadFactory::CreateEqual(), IWorkloadFactory::CreateFakeQuantization(), IWorkloadFactory::CreateFloor(), IWorkloadFactory::CreateFullyConnected(), IWorkloadFactory::CreateGather(), IWorkloadFactory::CreateGreater(), IWorkloadFactory::CreateInput(), IWorkloadFactory::CreateInstanceNormalization(), IWorkloadFactory::CreateL2Normalization(), IWorkloadFactory::CreateLogSoftmax(), IWorkloadFactory::CreateLstm(), IWorkloadFactory::CreateMaximum(), IWorkloadFactory::CreateMean(), IWorkloadFactory::CreateMemCopy(), IWorkloadFactory::CreateMemImport(), IWorkloadFactory::CreateMerge(), IWorkloadFactory::CreateMerger(), IWorkloadFactory::CreateMinimum(), IWorkloadFactory::CreateMultiplication(), IWorkloadFactory::CreateNormalization(), IWorkloadFactory::CreateOutput(), IWorkloadFactory::CreatePad(), IWorkloadFactory::CreatePermute(), IWorkloadFactory::CreatePooling2d(), IWorkloadFactory::CreatePreCompiled(), IWorkloadFactory::CreatePrelu(), IWorkloadFactory::CreateQLstm(), IWorkloadFactory::CreateQuantize(), IWorkloadFactory::CreateQuantizedLstm(), IWorkloadFactory::CreateReshape(), IWorkloadFactory::CreateResize(), IWorkloadFactory::CreateResizeBilinear(), IWorkloadFactory::CreateRsqrt(), IWorkloadFactory::CreateSlice(), IWorkloadFactory::CreateSoftmax(), IWorkloadFactory::CreateSpaceToBatchNd(), IWorkloadFactory::CreateSpaceToDepth(), IWorkloadFactory::CreateSplitter(), IWorkloadFactory::CreateStack(), IWorkloadFactory::CreateStridedSlice(), IWorkloadFactory::CreateSubTensorHandle(), IWorkloadFactory::CreateSubtraction(), IWorkloadFactory::CreateSwitch(), IWorkloadFactory::CreateTensorHandle(), IWorkloadFactory::CreateTranspose(), IWorkloadFactory::CreateTransposeConvolution2d(), IWorkloadFactory::GetBackendId(), armnn::Info, armnn::info, IWorkloadFactory::IsLayerSupported(), and IWorkloadFactory::SupportsSubTensors().
 { }
Member Function Documentation
CreateAbs()
std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1201 of file WorkloadFactory.cpp.
Referenced by AbsLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateActivation()
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1207 of file WorkloadFactory.cpp.
Referenced by BoundedReLuTestCommon(), BoundedReLuUint8UpperAndLowerBoundTest(), CompareActivationTestImpl(), ConstantLinearActivationTestCommon(), ActivationLayer::CreateWorkload(), SimpleActivationTest(), SqrtNNTest(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateAddition()
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, SampleDynamicWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1213 of file WorkloadFactory.cpp.
Referenced by AdditionAfterMaxPoolTest(), AdditionBroadcast1ElementTestImpl(), AdditionBroadcastTestImpl(), CompareAdditionTest(), AdditionLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateArgMinMax()
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1219 of file WorkloadFactory.cpp.
Referenced by ArgMinMaxLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateBatchNormalization()
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1225 of file WorkloadFactory.cpp.
Referenced by CompareBatchNormTest(), BatchNormalizationLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateBatchToSpaceNd()
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 1231 of file WorkloadFactory.cpp.
Referenced by BatchToSpaceNdLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateComparison()
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 1237 of file WorkloadFactory.cpp.
Referenced by ComparisonLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConcat()
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 1243 of file WorkloadFactory.cpp.
Referenced by ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), ConcatLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConstant()
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 1249 of file WorkloadFactory.cpp.
Referenced by ConstantLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConvertBf16ToFp32()
std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, and NeonWorkloadFactory.
Definition at line 1255 of file WorkloadFactory.cpp.
Referenced by ConvertBf16ToFp32Test(), ConvertBf16ToFp32Layer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConvertFp16ToFp32()
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1261 of file WorkloadFactory.cpp.
Referenced by ConvertFp16ToFp32Layer::CreateWorkload(), SimpleConvertFp16ToFp32Test(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConvertFp32ToBf16()
std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, and NeonWorkloadFactory.
Definition at line 1267 of file WorkloadFactory.cpp.
Referenced by ConvertFp32ToBf16Test(), ConvertFp32ToBf16Layer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConvertFp32ToFp16()
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, NeonWorkloadFactory, WorkloadFactoryBase, and ClWorkloadFactory.
Definition at line 1273 of file WorkloadFactory.cpp.
Referenced by ConvertFp32ToFp16Layer::CreateWorkload(), SimpleConvertFp32ToFp16Test(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateConvolution2d()
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1279 of file WorkloadFactory.cpp.
Referenced by CompareConvolution2dTestImpl(), Convolution1dTestImpl(), Convolution2dPerAxisQuantTest(), Convolution2dLayer::CreateWorkload(), SimpleConvolution2dNhwcTestImpl(), SimpleConvolution2dTestImpl(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateDebug()
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1285 of file WorkloadFactory.cpp.
Referenced by DebugLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateDepthToSpace()
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1291 of file WorkloadFactory.cpp.
Referenced by DepthToSpaceLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateDepthwiseConvolution2d()
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1297 of file WorkloadFactory.cpp.
Referenced by CompareDepthwiseConvolution2dTestImpl(), DepthwiseConvolution2dLayer::CreateWorkload(), DepthwiseConvolution2dAsymmetricTestImpl(), DepthwiseConvolution2dDepthMul1TestImpl(), DepthwiseConvolution2dPerAxisQuantTest(), DepthwiseConvolution2dTestImpl(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateDequantize()
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1303 of file WorkloadFactory.cpp.
Referenced by DequantizeLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateDetectionPostProcess()
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1309 of file WorkloadFactory.cpp.
Referenced by DetectionPostProcessLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateDivision()
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1315 of file WorkloadFactory.cpp.
Referenced by DivisionLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateElementwiseUnary()
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1321 of file WorkloadFactory.cpp.
Referenced by ElementwiseUnaryLayer::CreateWorkload(), CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateEqual()
std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1327 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateFakeQuantization()
std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1333 of file WorkloadFactory.cpp.
Referenced by FakeQuantizationLayer::CreateWorkload(), FakeQuantizationTest(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateFloor()
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1339 of file WorkloadFactory.cpp.
Referenced by FloorLayer::CreateWorkload(), SimpleFloorTest(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateFullyConnected()
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1345 of file WorkloadFactory.cpp.
Referenced by FullyConnectedLayer::CreateWorkload(), SimpleFullyConnectedTestImpl(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateGather()
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1351 of file WorkloadFactory.cpp.
Referenced by GatherLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateGreater()
std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1357 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateInput()
virtual std::unique_ptr<IWorkload> CreateInput (const InputQueueDescriptor & descriptor, const WorkloadInfo & info) const pure virtual
Implemented in RefWorkloadFactory, NeonWorkloadFactory, ClWorkloadFactory, SampleDynamicWorkloadFactory, and WorkloadFactoryBase.
Referenced by IWorkloadFactory::~IWorkloadFactory().
CreateInstanceNormalization()
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1363 of file WorkloadFactory.cpp.
Referenced by InstanceNormalizationLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateL2Normalization()
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1370 of file WorkloadFactory.cpp.
Referenced by L2NormalizationLayer::CreateWorkload(), L2Normalization2dShapeTest(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateLogSoftmax()
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, and WorkloadFactoryBase.
Definition at line 1376 of file WorkloadFactory.cpp.
Referenced by LogSoftmaxLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateLstm()
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1382 of file WorkloadFactory.cpp.
Referenced by LstmLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMaximum()
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1388 of file WorkloadFactory.cpp.
Referenced by MaximumLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMean()
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1394 of file WorkloadFactory.cpp.
Referenced by MeanLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMemCopy()
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1400 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMemImport()
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1406 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMerge()
std::unique_ptr< IWorkload > CreateMerge (const MergeQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase.
Definition at line 1412 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMerger()
std::unique_ptr< IWorkload > CreateMerger (const MergerQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1418 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMinimum()
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1424 of file WorkloadFactory.cpp.
Referenced by MinimumLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateMultiplication()
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1430 of file WorkloadFactory.cpp.
Referenced by CompareMultiplicationTest(), MultiplicationLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateNormalization()
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1436 of file WorkloadFactory.cpp.
Referenced by NormalizationLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateOutput()
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, ClWorkloadFactory, and SampleDynamicWorkloadFactory.
Definition at line 1442 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreatePad()
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1448 of file WorkloadFactory.cpp.
Referenced by PadLayer::CreateWorkload(), Pad2dTestCommon(), Pad3dTestCommon(), Pad4dTestCommon(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreatePermute()
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1454 of file WorkloadFactory.cpp.
Referenced by PermuteLayer::CreateWorkload(), PermuteTensorData(), SimplePermuteTestImpl(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreatePooling2d()
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1460 of file WorkloadFactory.cpp.
Referenced by AdditionAfterMaxPoolTest(), Pooling2dLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreatePreCompiled()
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1466 of file WorkloadFactory.cpp.
Referenced by PreCompiledLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreatePrelu()
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1472 of file WorkloadFactory.cpp.
Referenced by PreluLayer::CreateWorkload(), PreluTest(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateQLstm()
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1484 of file WorkloadFactory.cpp.
Referenced by QLstmLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateQuantize()
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1478 of file WorkloadFactory.cpp.
Referenced by QuantizeLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateQuantizedLstm()
std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1490 of file WorkloadFactory.cpp.
Referenced by QuantizedLstmLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateReshape()
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1496 of file WorkloadFactory.cpp.
Referenced by ReshapeLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateResize()
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1508 of file WorkloadFactory.cpp.
Referenced by ResizeLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateResizeBilinear()
std::unique_ptr< IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1502 of file WorkloadFactory.cpp.
Referenced by IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateRsqrt()
std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1514 of file WorkloadFactory.cpp.
Referenced by RsqrtLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSlice()
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1520 of file WorkloadFactory.cpp.
Referenced by SliceLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSoftmax()
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1526 of file WorkloadFactory.cpp.
Referenced by SoftmaxLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSpaceToBatchNd()
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1538 of file WorkloadFactory.cpp.
Referenced by SpaceToBatchNdLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSpaceToDepth()
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1544 of file WorkloadFactory.cpp.
Referenced by SpaceToDepthLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSplitter()
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1532 of file WorkloadFactory.cpp.
Referenced by SplitterLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateStack()
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1550 of file WorkloadFactory.cpp.
Referenced by StackLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateStridedSlice()
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1556 of file WorkloadFactory.cpp.
Referenced by StridedSliceLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSubTensorHandle()
virtual std::unique_ptr<ITensorHandle> CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const pure virtual
Implemented in RefWorkloadFactory, SampleDynamicWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Referenced by ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), and IWorkloadFactory::~IWorkloadFactory().
CreateSubtraction()
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1562 of file WorkloadFactory.cpp.
Referenced by SubtractionLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateSwitch()
std::unique_ptr< IWorkload > CreateSwitch (const SwitchQueueDescriptor & descriptor, const WorkloadInfo & Info) const virtual
Reimplemented in WorkloadFactoryBase.
Definition at line 1568 of file WorkloadFactory.cpp.
Referenced by SwitchLayer::CreateWorkload(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateTensorHandle() [1/2]
virtual std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const pure virtual
Implemented in RefWorkloadFactory, SampleDynamicWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Referenced by AdditionAfterMaxPoolTest(), AdditionBroadcast1ElementTestImpl(), AdditionBroadcastTestImpl(), BoundedReLuTestCommon(), BoundedReLuUint8UpperAndLowerBoundTest(), CompareActivationTestImpl(), CompareAdditionTest(), CompareBatchNormTest(), CompareConvolution2dTestImpl(), CompareDepthwiseConvolution2dTestImpl(), CompareMultiplicationTest(), ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), ConstantLinearActivationTestCommon(), ConvertBf16ToFp32Test(), ConvertFp32ToBf16Test(), Convolution1dTestImpl(), Convolution2dPerAxisQuantTest(), OutputHandler::CreateTensorHandles(), DepthwiseConvolution2dAsymmetricTestImpl(), DepthwiseConvolution2dDepthMul1TestImpl(), DepthwiseConvolution2dPerAxisQuantTest(), DepthwiseConvolution2dTestImpl(), ElementwiseTestHelper(), ElementwiseUnaryTestHelper(), FakeQuantizationTest(), L2Normalization2dShapeTest(), Pad2dTestCommon(), Pad3dTestCommon(), Pad4dTestCommon(), PermuteTensorData(), PreluTest(), SimpleActivationTest(), SimpleConvertFp16ToFp32Test(), SimpleConvertFp32ToFp16Test(), SimpleConvolution2dNhwcTestImpl(), SimpleConvolution2dTestImpl(), SimpleFloorTest(), SimpleFullyConnectedTestImpl(), SimplePermuteTestImpl(), SimpleTransposeTestImpl(), SqrtNNTest(), TransposeConvolution2dPerAxisQuantTest(), and IWorkloadFactory::~IWorkloadFactory().
CreateTensorHandle() [2/2]
virtual std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const pure virtual
Implemented in RefWorkloadFactory, SampleDynamicWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
CreateTranspose()
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1574 of file WorkloadFactory.cpp.
Referenced by TransposeLayer::CreateWorkload(), SimpleTransposeTestImpl(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
CreateTransposeConvolution2d()
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const virtual
Reimplemented in WorkloadFactoryBase, RefWorkloadFactory, NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 1580 of file WorkloadFactory.cpp.
Referenced by TransposeConvolution2dLayer::CreateWorkload(), TransposeConvolution2dPerAxisQuantTest(), and IWorkloadFactory::~IWorkloadFactory().
 {
     return std::unique_ptr<IWorkload>();
 }
GetBackendId()
virtual const BackendId& GetBackendId () const pure virtual
Implemented in RefWorkloadFactory, SampleDynamicWorkloadFactory, ClWorkloadFactory, and NeonWorkloadFactory.
Referenced by IWorkloadFactory::~IWorkloadFactory().
IsLayerSupported() [1/2]
bool IsLayerSupported (const BackendId & backendId, const IConnectableLayer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 45 of file WorkloadFactory.cpp.
References armnn::Activation, armnn::Addition, anchors(), armnn::ArgMinMax, ARMNN_ASSERT, ARMNN_ASSERT_MSG, armnn::BackendRegistryInstance(), armnn::BatchNormalization, armnn::BatchToSpaceNd, armnn::BFloat16, armnn::Boolean, boxEncodings(), armnn::Comparison, armnn::Concat, armnn::Constant, armnn::ConvertBf16ToFp32, armnn::ConvertFp16ToFp32, armnn::ConvertFp32ToBf16, armnn::ConvertFp32ToFp16, armnn::Convolution2d, armnn::Debug, armnn::DepthToSpace, armnn::DepthwiseConvolution2d, armnn::Dequantize, armnn::DetectionPostProcess, armnn::Division, armnn::ElementwiseUnary, armnn::FakeQuantization, armnn::Float16, armnn::Float32, armnn::Floor, armnn::FullyConnected, armnn::Gather, armnn::GetBiasTypeFromWeightsType(), InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetInputSlots(), IConnectableLayer::GetName(), Layer::GetOutputSlot(), Layer::GetOutputSlots(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), Layer::GetType(), armnn::info, armnn::Input, armnn::InstanceNormalization, armnn::L2Normalization, armnn::LogSoftmax, armnn::Lstm, FullyConnectedDescriptor::m_BiasEnabled, LstmInputParamsInfo::m_CellBias, QuantizedLstmInputParamsInfo::m_CellBias, LstmInputParamsInfo::m_CellLayerNormWeights, LstmInputParamsInfo::m_CellToForgetWeights, LstmInputParamsInfo::m_CellToInputWeights, LstmInputParamsInfo::m_CellToOutputWeights, LstmInputParamsInfo::m_ForgetGateBias, QuantizedLstmInputParamsInfo::m_ForgetGateBias, LstmInputParamsInfo::m_ForgetLayerNormWeights, LstmInputParamsInfo::m_InputGateBias, QuantizedLstmInputParamsInfo::m_InputGateBias, LstmInputParamsInfo::m_InputLayerNormWeights, LstmInputParamsInfo::m_InputToCellWeights, QuantizedLstmInputParamsInfo::m_InputToCellWeights, LstmInputParamsInfo::m_InputToForgetWeights, QuantizedLstmInputParamsInfo::m_InputToForgetWeights, LstmInputParamsInfo::m_InputToInputWeights, QuantizedLstmInputParamsInfo::m_InputToInputWeights, LstmInputParamsInfo::m_InputToOutputWeights, QuantizedLstmInputParamsInfo::m_InputToOutputWeights, LstmInputParamsInfo::m_OutputGateBias, QuantizedLstmInputParamsInfo::m_OutputGateBias, LstmInputParamsInfo::m_OutputLayerNormWeights, LstmInputParamsInfo::m_ProjectionBias, LstmInputParamsInfo::m_ProjectionWeights, LstmInputParamsInfo::m_RecurrentToCellWeights, QuantizedLstmInputParamsInfo::m_RecurrentToCellWeights, LstmInputParamsInfo::m_RecurrentToForgetWeights, QuantizedLstmInputParamsInfo::m_RecurrentToForgetWeights, LstmInputParamsInfo::m_RecurrentToInputWeights, QuantizedLstmInputParamsInfo::m_RecurrentToInputWeights, LstmInputParamsInfo::m_RecurrentToOutputWeights, QuantizedLstmInputParamsInfo::m_RecurrentToOutputWeights, armnn::Maximum, armnn::Mean, armnn::MemCopy, armnn::MemImport, armnn::Merge, armnn::Minimum, armnn::Multiplication, armnn::Normalization, armnn::Output, armnn::Pad, armnn::Permute, armnn::Pooling2d, armnn::PreCompiled, armnn::Prelu, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QLstm, armnn::QSymmS16, armnn::QSymmS8, armnn::Quantize, armnn::QuantizedLstm, armnn::Reshape, armnn::Resize, scores(), armnn::Signed32, armnn::Slice, armnn::Softmax, armnn::SpaceToBatchNd, armnn::SpaceToDepth, armnn::Splitter, armnn::Stack, armnn::StandIn, armnn::StridedSlice, armnn::Subtraction, armnn::Switch, armnn::Transpose, armnn::TransposeConvolution2d, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by armnn::AttemptBackendAssignment(), LoadedNetwork::GetOutputTensorInfo(), ClWorkloadFactory::IsLayerSupported(), NeonWorkloadFactory::IsLayerSupported(), SampleDynamicWorkloadFactory::IsLayerSupported(), IWorkloadFactory::IsLayerSupported(), RefWorkloadFactory::IsLayerSupported(), and IWorkloadFactory::~IWorkloadFactory().
 {
     Optional<std::string&> reason = outReasonIfUnsupported;
     bool result;
     const Layer& layer = *(PolymorphicDowncast<const Layer*>(&connectableLayer));
     auto const& backendRegistry = BackendRegistryInstance();
     if (!backendRegistry.IsBackendRegistered(backendId))
     {
         std::stringstream ss;
         ss << connectableLayer.GetName() << " is not supported on " << backendId
            << " because this backend is not registered.";
         outReasonIfUnsupported = ss.str();
         return false;
     }
     auto backendFactory = backendRegistry.GetFactory(backendId);
     auto backendObject = backendFactory();
     auto layerSupportObject = backendObject->GetLayerSupport();
     switch(layer.GetType())
     {
         case LayerType::Activation:
         {
             auto cLayer = PolymorphicDowncast<const ActivationLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsActivationSupported(
                                            OverrideDataType(input, dataType),
                                            OverrideDataType(output, dataType),
                                            cLayer->GetParameters(),
                                            reason);
             break;
         }
         case LayerType::Addition:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsAdditionSupported(
                                         OverrideDataType(input0, dataType),
                                         OverrideDataType(input1, dataType),
                                         OverrideDataType(output, dataType),
                                         reason);
             break;
         }
         case LayerType::ArgMinMax:
         {
             auto cLayer = PolymorphicDowncast<const ArgMinMaxLayer*>(&layer);
             const ArgMinMaxDescriptor& descriptor = cLayer->GetParameters();
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsArgMinMaxSupported(
                     OverrideDataType(input, dataType),
                     OverrideDataType(output, DataType::Signed32),
                     descriptor,
                     reason);
             break;
         }
         case LayerType::BatchNormalization:
         {
             auto cLayer = PolymorphicDowncast<const BatchNormalizationLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             const TensorInfo& mean = cLayer->m_Mean->GetTensorInfo();
             const TensorInfo& var = cLayer->m_Variance->GetTensorInfo();
             const TensorInfo& beta = cLayer->m_Beta->GetTensorInfo();
             const TensorInfo& gamma = cLayer->m_Gamma->GetTensorInfo();
             result = layerSupportObject->IsBatchNormalizationSupported(
                                                    OverrideDataType(input, dataType),
                                                    OverrideDataType(output, dataType),
                                                    OverrideDataType(mean, dataType),
                                                    OverrideDataType(var, dataType),
                                                    OverrideDataType(beta, dataType),
                                                    OverrideDataType(gamma, dataType),
                                                    cLayer->GetParameters(),
                                                    reason);
             break;
         }
         case LayerType::BatchToSpaceNd:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             auto cLayer = PolymorphicDowncast<const BatchToSpaceNdLayer*>(&layer);
             result = layerSupportObject->IsBatchToSpaceNdSupported(OverrideDataType(input, dataType),
                                                                    OverrideDataType(output, dataType),
                                                                    cLayer->GetParameters(),
                                                                    reason);
             break;
         }
         case LayerType::Comparison:
         {
             auto cLayer = PolymorphicDowncast<const ComparisonLayer*>(&layer);
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsComparisonSupported(OverrideDataType(input0, dataType),
                                                                OverrideDataType(input1, dataType),
                                                                OverrideDataType(output, DataType::Boolean),
                                                                cLayer->GetParameters(),
                                                                reason);
             break;
         }
         case LayerType::Constant:
         {
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsConstantSupported(OverrideDataType(output, dataType), reason);
             break;
         }
         case LayerType::ConvertBf16ToFp32:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsConvertBf16ToFp32Supported(input, output, reason);
             break;
         }
         case LayerType::ConvertFp16ToFp32:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsConvertFp16ToFp32Supported(input, output, reason);
             break;
         }
         case LayerType::ConvertFp32ToBf16:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsConvertFp32ToBf16Supported(input, output, reason);
             break;
         }
         case LayerType::ConvertFp32ToFp16:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsConvertFp32ToFp16Supported(input, output, reason);
             break;
         }
         case LayerType::Convolution2d:
         {
             auto cLayer = PolymorphicDowncast<const Convolution2dLayer*>(&layer);
             const TensorInfo input  = OverrideDataType(layer.GetInputSlot(0).GetConnection()->GetTensorInfo(),
                                                        dataType);
             const TensorInfo output = OverrideDataType(layer.GetOutputSlot(0).GetTensorInfo(), dataType);
             ARMNN_ASSERT(cLayer->m_Weight.get() != nullptr);
             const Convolution2dDescriptor& descriptor  = cLayer->GetParameters();
             // Construct optional biases object based on the value of m_BiasEnabled
             Optional<TensorInfo> biases;
             if (descriptor.m_BiasEnabled)
             {
                 biases =
                     OverrideDataType(cLayer->m_Bias->GetTensorInfo(), GetBiasTypeFromWeightsType(dataType));
             }
             result = layerSupportObject->IsConvolution2dSupported(
                                               input,
                                               output,
                                               descriptor,
                                               OverrideDataType(cLayer->m_Weight->GetTensorInfo(), dataType),
                                               biases,
                                               reason);
             break;
         }
         case LayerType::Debug:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsDebugSupported(OverrideDataType(input, dataType),
                                                           OverrideDataType(output, dataType),
                                                           reason);
             break;
         }
         case LayerType::DepthToSpace:
         {
             auto cLayer = PolymorphicDowncast<const DepthToSpaceLayer*>(&layer);
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsDepthToSpaceSupported(OverrideDataType(input, dataType),
                                                                  OverrideDataType(output, dataType),
                                                                  cLayer->GetParameters(),
                                                                  reason);
             break;
         }
         case LayerType::DepthwiseConvolution2d:
         {
             auto cLayer = PolymorphicDowncast<const DepthwiseConvolution2dLayer*>(&layer);
             const TensorInfo& input = OverrideDataType(layer.GetInputSlot(0).GetConnection()->GetTensorInfo(),
                                                        dataType);
             const TensorInfo& output = OverrideDataType(layer.GetOutputSlot(0).GetTensorInfo(), dataType);
             ARMNN_ASSERT(cLayer->m_Weight.get() != nullptr);
             const DepthwiseConvolution2dDescriptor& descriptor = cLayer->GetParameters();
             // Construct optional biases object based on the value of m_BiasEnabled
             Optional<TensorInfo> biases;
             if (descriptor.m_BiasEnabled)
             {
                 biases =
                     OverrideDataType(cLayer->m_Bias->GetTensorInfo(), GetBiasTypeFromWeightsType(dataType));
             }
             result = layerSupportObject->IsDepthwiseConvolutionSupported(
                                                      input,
                                                      output,
                                                      descriptor,
                                                      OverrideDataType(cLayer->m_Weight->GetTensorInfo(), dataType),
                                                      biases,
                                                      reason);
             break;
         }
         case LayerType::Dequantize:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsDequantizeSupported(input,
                                                                OverrideDataType(output, dataType),
                                                                reason);
             break;
         }
         case LayerType::DetectionPostProcess:
         {
             auto cLayer = PolymorphicDowncast<const DetectionPostProcessLayer*>(&layer);
             const TensorInfo& boxEncodings = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& scores = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& anchors = cLayer->m_Anchors->GetTensorInfo();
             const TensorInfo& detectionBoxes = layer.GetOutputSlot(0).GetTensorInfo();
             const TensorInfo& detectionClasses = layer.GetOutputSlot(1).GetTensorInfo();
             const TensorInfo& detectionScores = layer.GetOutputSlot(2).GetTensorInfo();
             const TensorInfo& numDetections = layer.GetOutputSlot(3).GetTensorInfo();
             const DetectionPostProcessDescriptor& descriptor = cLayer->GetParameters();
             result = layerSupportObject->IsDetectionPostProcessSupported(boxEncodings,
                                                                          scores,
                                                                          anchors,
                                                                          detectionBoxes,
                                                                          detectionClasses,
                                                                          detectionScores,
                                                                          numDetections,
                                                                          descriptor,
                                                                          reason);
             break;
         }
         case LayerType::ElementwiseUnary:
         {
             auto cLayer = PolymorphicDowncast<const ElementwiseUnaryLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsElementwiseUnarySupported(OverrideDataType(input, dataType),
                                                                      OverrideDataType(output, dataType),
                                                                      cLayer->GetParameters(),
                                                                      reason);
             break;
         }
         case LayerType::FakeQuantization:
         {
             auto cLayer = PolymorphicDowncast<const FakeQuantizationLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             result = layerSupportObject->IsFakeQuantizationSupported(OverrideDataType(input, dataType),
                                                                      cLayer->GetParameters(),
                                                                      reason);
             break;
         }
         case LayerType::Floor:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsFloorSupported(OverrideDataType(input, dataType),
                                                           OverrideDataType(output, dataType),
                                                           reason);
             break;
         }
         case LayerType::FullyConnected:
         {
             auto cLayer = PolymorphicDowncast<const FullyConnectedLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             ARMNN_ASSERT(cLayer->m_Weight.get() != nullptr);
             TensorInfo biasInfo;
             const TensorInfo * biasInfoPtr = nullptr;
             static const TensorInfo dummyBFloat16Bias(TensorShape({1,1,1,1}), DataType::BFloat16);
             static const TensorInfo dummyFloat16Bias(TensorShape({1,1,1,1}), DataType::Float16);
             static const TensorInfo dummyFloat32Bias(TensorShape({1,1,1,1}), DataType::Float32);
             static const TensorInfo dummyQA8Bias(TensorShape({1,1,1,1}), DataType::Signed32);
             const FullyConnectedDescriptor& descriptor = cLayer->GetParameters();
             if (descriptor.m_BiasEnabled)
             {
                 ARMNN_ASSERT(cLayer->m_Bias.get() != nullptr);
                 biasInfo = OverrideDataType(cLayer->m_Bias->GetTensorInfo(), GetBiasTypeFromWeightsType(dataType));
                 biasInfoPtr = &biasInfo;
             }
             else
             {
                 // If biases are not enabled pass a dummy tensorinfo for the validation
                 switch(input.GetDataType())
                 {
                     case DataType::BFloat16:
                     {
                         biasInfoPtr = &dummyBFloat16Bias;
                         break;
                     }
                     case DataType::Float16:
                     {
                         biasInfoPtr = &dummyFloat16Bias;
                         break;
                     }
                     case DataType::Float32:
                     {
                         biasInfoPtr = &dummyFloat32Bias;
                         break;
                     }
                     case DataType::QAsymmU8:
                     case DataType::QAsymmS8:
                     case DataType::QSymmS8:
                     case DataType::QSymmS16:
                     {
                         biasInfoPtr = &dummyQA8Bias;
                         break;
                     }
                     default:
                     {
                         ARMNN_ASSERT_MSG(false, "Unexpected bias type");
                     }
                 }
             }
             result = layerSupportObject->IsFullyConnectedSupported(
                                                OverrideDataType(input, dataType),
                                                OverrideDataType(output, dataType),
                                                OverrideDataType(cLayer->m_Weight->GetTensorInfo(), dataType),
                                                *biasInfoPtr,
                                                descriptor,
                                                reason);
             break;
         }
         case LayerType::Gather:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsGatherSupported(OverrideDataType(input0, dataType),
                                                            input1,
                                                            OverrideDataType(output, dataType),
                                                            reason);
             break;
         }
         case LayerType::Input:
         {
             const TensorInfo& input = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsInputSupported(OverrideDataType(input, dataType), reason);
             break;
         }
         case LayerType::InstanceNormalization:
         {
             auto cLayer = PolymorphicDowncast<const InstanceNormalizationLayer*>(&layer);
             const InstanceNormalizationDescriptor& descriptor = cLayer->GetParameters();
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsInstanceNormalizationSupported(
                 OverrideDataType(input, dataType),
                 OverrideDataType(output, dataType),
                 descriptor,
                 reason);
             break;
         }
         case LayerType::L2Normalization:
         {
             auto cLayer = PolymorphicDowncast<const L2NormalizationLayer*>(&layer);
             const L2NormalizationDescriptor& descriptor = cLayer->GetParameters();
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsL2NormalizationSupported(
                                                 OverrideDataType(input, dataType),
                                                 OverrideDataType(output, dataType),
                                                 descriptor,
                                                 reason);
             break;
         }
         case LayerType::LogSoftmax:
         {
             auto cLayer = PolymorphicDowncast<const LogSoftmaxLayer*>(&layer);
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsLogSoftmaxSupported(OverrideDataType(input, dataType),
                                                                OverrideDataType(output, dataType),
                                                                cLayer->GetParameters(),
                                                                reason);
             break;
         }
         case LayerType::Lstm:
         {
             auto cLayer = PolymorphicDowncast<const LstmLayer*>(&layer);
             const LstmDescriptor& descriptor = cLayer->GetParameters();
             // All inputs.
             const TensorInfo& input = OverrideDataType(layer.GetInputSlot(0).GetConnection()->GetTensorInfo(),
                                                        dataType);
             const TensorInfo& outputStateIn = OverrideDataType(layer.GetInputSlot(1).GetConnection()->GetTensorInfo(),
                                                                dataType);
             const TensorInfo& cellStateIn = OverrideDataType(layer.GetInputSlot(2).GetConnection()->GetTensorInfo(),
                                                              dataType);
             // All outputs
             const TensorInfo& scratchBuffer = OverrideDataType(layer.GetOutputSlot(0).GetTensorInfo(), dataType);
             const TensorInfo& outputStateOut = OverrideDataType(layer.GetOutputSlot(1).GetTensorInfo(), dataType);
             const TensorInfo& cellStateOut = OverrideDataType(layer.GetOutputSlot(2).GetTensorInfo(), dataType);
             const TensorInfo& output = OverrideDataType(layer.GetOutputSlot(3).GetTensorInfo(), dataType);
             // Basic parameters
             const TensorInfo& inputToForgetWeights
                     = OverrideDataType(cLayer->m_BasicParameters.m_InputToForgetWeights->GetTensorInfo(), dataType);
             const TensorInfo& inputToCellWeights
                     = OverrideDataType(cLayer->m_BasicParameters.m_InputToCellWeights->GetTensorInfo(), dataType);
             const TensorInfo& inputToOutputWeights
                     = OverrideDataType(cLayer->m_BasicParameters.m_InputToOutputWeights->GetTensorInfo(), dataType);
             const TensorInfo& recurrentToForgetWeights
                     = OverrideDataType(cLayer->m_BasicParameters.m_RecurrentToForgetWeights->GetTensorInfo(), dataType);
             const TensorInfo& recurrentToCellWeights
                     = OverrideDataType(cLayer->m_BasicParameters.m_RecurrentToCellWeights->GetTensorInfo(), dataType);
             const TensorInfo& recurrentToOutputWeights
                     = OverrideDataType(cLayer->m_BasicParameters.m_RecurrentToOutputWeights->GetTensorInfo(), dataType);
             const TensorInfo& forgetGateBias
                     = OverrideDataType(cLayer->m_BasicParameters.m_ForgetGateBias->GetTensorInfo(), dataType);
             const TensorInfo& cellBias
                     = OverrideDataType(cLayer->m_BasicParameters.m_CellBias->GetTensorInfo(), dataType);
             const TensorInfo& outputGateBias
                     = OverrideDataType(cLayer->m_BasicParameters.m_OutputGateBias->GetTensorInfo(), dataType);
             LstmInputParamsInfo paramsInfo;
             paramsInfo.m_InputToForgetWeights     = &inputToForgetWeights;
             paramsInfo.m_InputToCellWeights       = &inputToCellWeights;
             paramsInfo.m_InputToOutputWeights     = &inputToOutputWeights;
             paramsInfo.m_RecurrentToForgetWeights = &recurrentToForgetWeights;
             paramsInfo.m_RecurrentToCellWeights   = &recurrentToCellWeights;
             paramsInfo.m_RecurrentToOutputWeights = &recurrentToOutputWeights;
             paramsInfo.m_ForgetGateBias           = &forgetGateBias;
             paramsInfo.m_CellBias                 = &cellBias;
             paramsInfo.m_OutputGateBias           = &outputGateBias;
             // Optional parameters
             TensorInfo optInputToInputWeights;
             TensorInfo optRecurrentToInputWeights;
             TensorInfo optCellToInputWeights;
             TensorInfo optInputGateBias;
             TensorInfo optProjectionWeights;
             TensorInfo optProjectionBias;
             TensorInfo optCellToForgetWeights;
             TensorInfo optCellToOutputWeights;
             TensorInfo optInputLayerNormWeights;
             TensorInfo optForgetLayerNormWeights;
             TensorInfo optCellLayerNormWeights;
             TensorInfo optOutputLayerNormWeights;
             if(!descriptor.m_CifgEnabled)
             {
                 optInputToInputWeights =
                     OverrideDataType(cLayer->m_CifgParameters.m_InputToInputWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_InputToInputWeights = &optInputToInputWeights;
                 optRecurrentToInputWeights =
                     OverrideDataType(cLayer->m_CifgParameters.m_RecurrentToInputWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_RecurrentToInputWeights = &optRecurrentToInputWeights;
                 optInputGateBias =
                        OverrideDataType(cLayer->m_CifgParameters.m_InputGateBias->GetTensorInfo(), dataType);
                 paramsInfo.m_InputGateBias = &optInputGateBias;
             }
             if(descriptor.m_ProjectionEnabled)
             {
                 optProjectionWeights =
                     OverrideDataType(cLayer->m_ProjectionParameters.m_ProjectionWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_ProjectionWeights = &optProjectionWeights;
                 if (cLayer->m_ProjectionParameters.m_ProjectionBias != nullptr)
                 {
                     optProjectionBias =
                         OverrideDataType(cLayer->m_ProjectionParameters.m_ProjectionBias->GetTensorInfo(), dataType);
                     paramsInfo.m_ProjectionBias = &optProjectionBias;
                 }
             }
             if(descriptor.m_PeepholeEnabled)
             {
                 if(!descriptor.m_CifgEnabled)
                 {
                     optCellToInputWeights =
                             OverrideDataType(cLayer->m_PeepholeParameters.m_CellToInputWeights->GetTensorInfo(),
                                              dataType);
                     paramsInfo.m_CellToInputWeights = &optCellToInputWeights;
                 }
                 optCellToForgetWeights =
                     OverrideDataType(cLayer->m_PeepholeParameters.m_CellToForgetWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_CellToForgetWeights = &optCellToForgetWeights;
                 optCellToOutputWeights =
                     OverrideDataType(cLayer->m_PeepholeParameters.m_CellToOutputWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_CellToOutputWeights = &optCellToOutputWeights;
             }
             if(descriptor.m_LayerNormEnabled)
             {
                 if (!descriptor.m_CifgEnabled)
                 {
                     optInputLayerNormWeights = OverrideDataType(
                             cLayer->m_LayerNormParameters.m_InputLayerNormWeights->GetTensorInfo(), dataType);
                     paramsInfo.m_InputLayerNormWeights = &optInputLayerNormWeights;
                 }
                 optForgetLayerNormWeights = OverrideDataType(
                         cLayer->m_LayerNormParameters.m_ForgetLayerNormWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_ForgetLayerNormWeights = &optForgetLayerNormWeights;
                 optCellLayerNormWeights = OverrideDataType(
                         cLayer->m_LayerNormParameters.m_CellLayerNormWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_CellLayerNormWeights = &optCellLayerNormWeights;
                 optOutputLayerNormWeights = OverrideDataType(
                         cLayer->m_LayerNormParameters.m_OutputLayerNormWeights->GetTensorInfo(), dataType);
                 paramsInfo.m_OutputLayerNormWeights = &optOutputLayerNormWeights;
             }
             result = layerSupportObject->IsLstmSupported(
                                      input,
                                      outputStateIn,
                                      cellStateIn,
                                      scratchBuffer,
                                      outputStateOut,
                                      cellStateOut,
                                      output,
                                      descriptor,
                                      paramsInfo,
                                      reason);
             break;
         }
         case LayerType::Maximum:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMaximumSupported(OverrideDataType(input0, dataType),
                                                             OverrideDataType(input1, dataType),
                                                             OverrideDataType(output, dataType),
                                                             reason);
             break;
         }
         case LayerType::MemCopy:
         {
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMemCopySupported(OverrideDataType(input, dataType),
                                                             OverrideDataType(output, dataType),
                                                             reason);
             break;
         }
         case LayerType::MemImport:
         {
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMemImportSupported(OverrideDataType(input, dataType),
                                                               OverrideDataType(output, dataType),
                                                               reason);
             break;
         }
         case LayerType::Merge:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMergeSupported(OverrideDataType(input0, dataType),
                                                           OverrideDataType(input1, dataType),
                                                           OverrideDataType(output, dataType),
                                                           reason);
             break;
         }
         case LayerType::Concat:
         {
             auto cLayer = PolymorphicDowncast<const ConcatLayer*>(&layer);
             // Get vector of all inputs.
             auto getTensorInfo = [&dataType](const InputSlot& slot)
                 {
                     return OverrideDataType(slot.GetConnectedOutputSlot()->GetTensorInfo(), dataType);
                 };
             auto beginI = boost::make_transform_iterator(layer.GetInputSlots().begin(), getTensorInfo);
             auto endI = boost::make_transform_iterator(layer.GetInputSlots().end(), getTensorInfo);
             std::vector<TensorInfo> inputs(beginI, endI);
             auto getTensorInfoPtr = [](const TensorInfo& info)
                 {
                     return &info;
                 };
             auto beginPtr = boost::make_transform_iterator(inputs.begin(), getTensorInfoPtr);
             auto endPtr = boost::make_transform_iterator(inputs.end(), getTensorInfoPtr);
             std::vector<const TensorInfo*> inputPtrs(beginPtr, endPtr);
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsConcatSupported(inputPtrs, output, cLayer->GetParameters(), reason);
             break;
         }
         case LayerType::Multiplication:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMultiplicationSupported(
                                                OverrideDataType(input0, dataType),
                                                OverrideDataType(input1, dataType),
                                                OverrideDataType(output, dataType),
                                                reason);
             break;
         }
         case LayerType::Normalization:
         {
             auto cLayer = PolymorphicDowncast<const NormalizationLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsNormalizationSupported(OverrideDataType(input, dataType),
                                                                   OverrideDataType(output, dataType),
                                                                   cLayer->GetParameters(),
                                                                   reason);
             break;
         }
         case LayerType::Output:
         {
             const TensorInfo& output = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             result = layerSupportObject->IsOutputSupported(OverrideDataType(output, dataType), reason);
             break;
         }
         case LayerType::Permute:
         {
             auto cLayer = PolymorphicDowncast<const PermuteLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsPermuteSupported(OverrideDataType(input, dataType),
                                                             OverrideDataType(output, dataType),
                                                             cLayer->GetParameters(),
                                                             reason);
             break;
         }
         case LayerType::Pad:
         {
             auto cLayer = PolymorphicDowncast<const PadLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsPadSupported(
                                     OverrideDataType(input, dataType),
                                     OverrideDataType(output, dataType),
                                     cLayer->GetParameters(),
                                     reason);
             break;
         }
         case LayerType::Pooling2d:
         {
             auto cLayer = PolymorphicDowncast<const Pooling2dLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsPooling2dSupported(OverrideDataType(input, dataType),
                                                               OverrideDataType(output, dataType),
                                                               cLayer->GetParameters(),
                                                               reason);
             break;
         }
         case LayerType::PreCompiled:
         {
             auto cLayer = PolymorphicDowncast<const PreCompiledLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             result = layerSupportObject->IsPreCompiledSupported(OverrideDataType(input, dataType),
                                                                 cLayer->GetParameters(),
                                                                 reason);
             break;
         }
         case LayerType::Quantize:
         {
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsQuantizeSupported(input, output, reason);
             break;
         }
         case LayerType::QLstm:
         {
             auto cLayer = PolymorphicDowncast<const QLstmLayer*>(&layer);
             const QLstmDescriptor& descriptor = cLayer->GetParameters();
             // Inputs
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& previousOutputIn = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& previousCellStateIn = layer.GetInputSlot(2).GetConnection()->GetTensorInfo();
             // Outputs
             const TensorInfo& outputStateOut = layer.GetOutputSlot(0).GetTensorInfo();
             const TensorInfo& cellStateOut = layer.GetOutputSlot(1).GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(2).GetTensorInfo();
             // Lstm parameters
             LstmInputParamsInfo paramsInfo;
             // Basic parameters
             paramsInfo.m_InputToForgetWeights = &cLayer->m_BasicParameters.m_InputToForgetWeights->GetTensorInfo();
             paramsInfo.m_InputToCellWeights   = &cLayer->m_BasicParameters.m_InputToCellWeights->GetTensorInfo();
             paramsInfo.m_InputToOutputWeights = &cLayer->m_BasicParameters.m_InputToOutputWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToForgetWeights =
                     &cLayer->m_BasicParameters.m_RecurrentToForgetWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToCellWeights   =
                     &cLayer->m_BasicParameters.m_RecurrentToCellWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToOutputWeights =
                     &cLayer->m_BasicParameters.m_RecurrentToOutputWeights->GetTensorInfo();
             paramsInfo.m_ForgetGateBias = &cLayer->m_BasicParameters.m_ForgetGateBias->GetTensorInfo();
             paramsInfo.m_CellBias       = &cLayer->m_BasicParameters.m_CellBias->GetTensorInfo();
             paramsInfo.m_OutputGateBias = &cLayer->m_BasicParameters.m_OutputGateBias->GetTensorInfo();
             if(!descriptor.m_CifgEnabled)
             {
                 paramsInfo.m_InputToInputWeights = &cLayer->m_CifgParameters.m_InputToInputWeights->GetTensorInfo();
                 paramsInfo.m_RecurrentToInputWeights =
                         &cLayer->m_CifgParameters.m_RecurrentToInputWeights->GetTensorInfo();
                 paramsInfo.m_InputGateBias = &cLayer->m_CifgParameters.m_InputGateBias->GetTensorInfo();
             }
             if(descriptor.m_ProjectionEnabled)
             {
                 paramsInfo.m_ProjectionWeights = &cLayer->m_ProjectionParameters.m_ProjectionWeights->GetTensorInfo();
                 // Projection bias is optional even if projection is enabled
                 if (cLayer->m_ProjectionParameters.m_ProjectionBias != nullptr)
                 {
                     paramsInfo.m_ProjectionBias = &cLayer->m_ProjectionParameters.m_ProjectionBias->GetTensorInfo();
                 }
             }
             if(descriptor.m_PeepholeEnabled)
             {
                 if (!descriptor.m_CifgEnabled)
                 {
                     paramsInfo.m_CellToInputWeights =
                             &cLayer->m_PeepholeParameters.m_CellToInputWeights->GetTensorInfo();
                 }
                 paramsInfo.m_CellToForgetWeights =
                         &cLayer->m_PeepholeParameters.m_CellToForgetWeights->GetTensorInfo();
                 paramsInfo.m_CellToOutputWeights = &cLayer->m_PeepholeParameters.m_CellToOutputWeights->GetTensorInfo();
             }
             if(descriptor.m_LayerNormEnabled)
             {
                 if (!descriptor.m_CifgEnabled)
                 {
                     paramsInfo.m_InputLayerNormWeights =
                             &cLayer->m_LayerNormParameters.m_InputLayerNormWeights->GetTensorInfo();
                 }
                 paramsInfo.m_ForgetLayerNormWeights =
                         &cLayer->m_LayerNormParameters.m_ForgetLayerNormWeights->GetTensorInfo();
                 paramsInfo.m_CellLayerNormWeights =
                         &cLayer->m_LayerNormParameters.m_CellLayerNormWeights->GetTensorInfo();
                 paramsInfo.m_OutputLayerNormWeights =
                         &cLayer->m_LayerNormParameters.m_OutputLayerNormWeights->GetTensorInfo();
             }
             result = layerSupportObject->IsQLstmSupported(input,
                                                           previousOutputIn,
                                                           previousCellStateIn,
                                                           outputStateOut,
                                                           cellStateOut,
                                                           output,
                                                           descriptor,
                                                           paramsInfo,
                                                           reason);
             break;
         }
         case LayerType::QuantizedLstm:
         {
             auto cLayer = PolymorphicDowncast<const QuantizedLstmLayer*>(&layer);
             // Inputs
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& previousCellStateIn = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& previousOutputIn = layer.GetInputSlot(2).GetConnection()->GetTensorInfo();
             // Outputs
             const TensorInfo& cellStateOut = layer.GetOutputSlot(0).GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(1).GetTensorInfo();
             // QuantizedLstm parameters
             QuantizedLstmInputParamsInfo paramsInfo;
             paramsInfo.m_InputToInputWeights      =
                     &cLayer->m_QuantizedLstmParameters.m_InputToInputWeights->GetTensorInfo();
             paramsInfo.m_InputToForgetWeights     =
                     &cLayer->m_QuantizedLstmParameters.m_InputToForgetWeights->GetTensorInfo();
             paramsInfo.m_InputToCellWeights       =
                     &cLayer->m_QuantizedLstmParameters.m_InputToCellWeights->GetTensorInfo();
             paramsInfo.m_InputToOutputWeights     =
                     &cLayer->m_QuantizedLstmParameters.m_InputToOutputWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToInputWeights  =
                     &cLayer->m_QuantizedLstmParameters.m_RecurrentToInputWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToForgetWeights =
                     &cLayer->m_QuantizedLstmParameters.m_RecurrentToForgetWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToCellWeights   =
                     &cLayer->m_QuantizedLstmParameters.m_RecurrentToCellWeights->GetTensorInfo();
             paramsInfo.m_RecurrentToOutputWeights =
                     &cLayer->m_QuantizedLstmParameters.m_RecurrentToOutputWeights->GetTensorInfo();
             paramsInfo.m_InputGateBias            =
                     &cLayer->m_QuantizedLstmParameters.m_InputGateBias->GetTensorInfo();
             paramsInfo.m_ForgetGateBias           =
                     &cLayer->m_QuantizedLstmParameters.m_ForgetGateBias->GetTensorInfo();
             paramsInfo.m_CellBias                 =
                     &cLayer->m_QuantizedLstmParameters.m_CellBias->GetTensorInfo();
             paramsInfo.m_OutputGateBias           =
                     &cLayer->m_QuantizedLstmParameters.m_OutputGateBias->GetTensorInfo();;
             result = layerSupportObject->IsQuantizedLstmSupported(input,
                                                                   previousCellStateIn,
                                                                   previousOutputIn,
                                                                   cellStateOut,
                                                                   output,
                                                                   paramsInfo,
                                                                   reason);
             break;
         }
         case LayerType::Division:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsDivisionSupported(
                                          OverrideDataType(input0, dataType),
                                          OverrideDataType(input1, dataType),
                                          OverrideDataType(output, dataType),
                                          reason);
             break;
         }
         case LayerType::Reshape:
         {
             auto cLayer = PolymorphicDowncast<const ReshapeLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsReshapeSupported(OverrideDataType(input, dataType),
                                                             OverrideDataType(output, dataType),
                                                             cLayer->GetParameters(),
                                                             reason);
             break;
         }
         case LayerType::Resize:
         {
             auto cLayer = PolymorphicDowncast<const ResizeLayer*>(&layer);
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsResizeSupported(OverrideDataType(input, dataType),
                                                            OverrideDataType(output, dataType),
                                                            cLayer->GetParameters(),
                                                            reason);
             break;
         }
         case LayerType::Slice:
         {
             auto cLayer = PolymorphicDowncast<const SliceLayer*>(&layer);
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsSliceSupported(OverrideDataType(input, dataType),
                                                           OverrideDataType(output, dataType),
                                                           cLayer->GetParameters(),
                                                           reason);
             break;
         }
         case LayerType::Softmax:
         {
             auto cLayer = PolymorphicDowncast<const SoftmaxLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsSoftmaxSupported(OverrideDataType(input, dataType),
                                                             OverrideDataType(output, dataType),
                                                             cLayer->GetParameters(),
                                                             reason);
             break;
         }
         case LayerType::SpaceToBatchNd:
         {
             auto cLayer = PolymorphicDowncast<const SpaceToBatchNdLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsSpaceToBatchNdSupported(OverrideDataType(input, dataType),
                                                                    OverrideDataType(output, dataType),
                                                                    cLayer->GetParameters(),
                                                                    reason);
             break;
         }
         case LayerType::SpaceToDepth:
         {
             auto cLayer = PolymorphicDowncast<const SpaceToDepthLayer*>(&layer);
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsSpaceToDepthSupported(OverrideDataType(input, dataType),
                                                                  OverrideDataType(output, dataType),
                                                                  cLayer->GetParameters(),
                                                                  reason);
             break;
         }
         case LayerType::Splitter:
         {
             auto cLayer = PolymorphicDowncast<const SplitterLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             // Get vector of all outputs.
             auto getTensorInfo = [&dataType](const OutputSlot& slot)
             {
                 return OverrideDataType(slot.GetTensorInfo(), dataType);
             };
             auto beginI = boost::make_transform_iterator(layer.GetOutputSlots().begin(), getTensorInfo);
             auto endI = boost::make_transform_iterator(layer.GetOutputSlots().end(), getTensorInfo);
             std::vector<TensorInfo> outputs(beginI, endI);
             const std::vector<std::reference_wrapper<TensorInfo>> outputPtrs(outputs.begin(), outputs.end());
             result = layerSupportObject->IsSplitterSupported(OverrideDataType(input, dataType),
                                                              outputPtrs,
                                                              cLayer->GetParameters(),
                                                              reason);
             break;
         }
         case LayerType::Stack:
         {
             auto cLayer = PolymorphicDowncast<const StackLayer*>(&layer);
             // Get vector of all inputs.
             auto getTensorInfo = [&dataType](const InputSlot& slot)
                 {
                     return OverrideDataType(slot.GetConnectedOutputSlot()->GetTensorInfo(), dataType);
                 };
             auto beginI = boost::make_transform_iterator(layer.GetInputSlots().begin(), getTensorInfo);
             auto endI = boost::make_transform_iterator(layer.GetInputSlots().end(), getTensorInfo);
             std::vector<TensorInfo> inputs(beginI, endI);
             auto getTensorInfoPtr = [](const TensorInfo& info)
                 {
                     return &info;
                 };
             auto beginPtr = boost::make_transform_iterator(inputs.begin(), getTensorInfoPtr);
             auto endPtr = boost::make_transform_iterator(inputs.end(), getTensorInfoPtr);
             std::vector<const TensorInfo*> inputPtrs(beginPtr, endPtr);
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsStackSupported(inputPtrs, output, cLayer->GetParameters(), reason);
             break;
         }
         case LayerType::StandIn:
         {
             auto cLayer = PolymorphicDowncast<const StandInLayer*>(&layer);
             // Get vector of all inputs.
             auto getTensorInfoIn = [&dataType](const InputSlot& slot)
                 {
                     return OverrideDataType(slot.GetConnectedOutputSlot()->GetTensorInfo(), dataType);
                 };
             auto getTensorInfoOut = [&dataType](const OutputSlot& slot)
                 {
                     return OverrideDataType(slot.GetTensorInfo(), dataType);
                 };
             auto beginI = boost::make_transform_iterator(layer.GetInputSlots().begin(), getTensorInfoIn);
             auto endI = boost::make_transform_iterator(layer.GetInputSlots().end(), getTensorInfoIn);
             std::vector<TensorInfo> inputs(beginI, endI);
             auto beginO = boost::make_transform_iterator(layer.GetOutputSlots().begin(), getTensorInfoOut);
             auto endO = boost::make_transform_iterator(layer.GetOutputSlots().end(), getTensorInfoOut);
             std::vector<TensorInfo> outputs(beginO, endO);
             auto getTensorInfoPtr = [](const TensorInfo& info)
                 {
                     return &info;
                 };
             auto beginPtrI = boost::make_transform_iterator(inputs.begin(), getTensorInfoPtr);
             auto endPtrI = boost::make_transform_iterator(inputs.end(), getTensorInfoPtr);
             std::vector<const TensorInfo*> inputPtrs(beginPtrI, endPtrI);
             auto beginPtrO = boost::make_transform_iterator(outputs.begin(), getTensorInfoPtr);
             auto endPtrO = boost::make_transform_iterator(outputs.end(), getTensorInfoPtr);
             std::vector<const TensorInfo*> outputPtrs(beginPtrO, endPtrO);
             result = layerSupportObject->IsStandInSupported(inputPtrs,
                                                             outputPtrs,
                                                             cLayer->GetParameters(),
                                                             reason);
             break;
         }
         case LayerType::StridedSlice:
         {
             auto cLayer = PolymorphicDowncast<const StridedSliceLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsStridedSliceSupported(OverrideDataType(input, dataType),
                                                                  OverrideDataType(output, dataType),
                                                                  cLayer->GetParameters(),
                                                                  reason);
             break;
         }
         case LayerType::Subtraction:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsSubtractionSupported(
                                             OverrideDataType(input0, dataType),
                                             OverrideDataType(input1, dataType),
                                             OverrideDataType(output, dataType),
                                             reason);
             break;
         }
         case LayerType::Switch:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output0 = layer.GetOutputSlot(0).GetTensorInfo();
             const TensorInfo& output1 = layer.GetOutputSlot(1).GetTensorInfo();
             result = layerSupportObject->IsSwitchSupported(OverrideDataType(input0, dataType),
                                                            OverrideDataType(input1, dataType),
                                                            OverrideDataType(output0, dataType),
                                                            OverrideDataType(output1, dataType),
                                                            reason);
             break;
         }
         case LayerType::Mean:
         {
             auto cLayer = PolymorphicDowncast<const MeanLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMeanSupported(
                                      OverrideDataType(input, dataType),
                                      OverrideDataType(output, dataType),
                                      cLayer->GetParameters(),
                                      reason);
             break;
         }
         case LayerType::Minimum:
         {
             const TensorInfo& input0 = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& input1 = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsMinimumSupported(OverrideDataType(input0, dataType),
                                                             OverrideDataType(input1, dataType),
                                                             OverrideDataType(output, dataType),
                                                             reason);
             break;
         }
         case LayerType::Prelu:
         {
             const TensorInfo& input  = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& alpha  = layer.GetInputSlot(1).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsPreluSupported(OverrideDataType(input,  dataType),
                                                           OverrideDataType(alpha,  dataType),
                                                           OverrideDataType(output, dataType),
                                                           reason);
             break;
         }
         case LayerType::Transpose:
         {
             auto cLayer = PolymorphicDowncast<const TransposeLayer*>(&layer);
             const TensorInfo& input = layer.GetInputSlot(0).GetConnection()->GetTensorInfo();
             const TensorInfo& output = layer.GetOutputSlot(0).GetTensorInfo();
             result = layerSupportObject->IsTransposeSupported(OverrideDataType(input, dataType),
                                                               OverrideDataType(output, dataType),
                                                               cLayer->GetParameters(),
                                                               reason);
             break;
         }
         case LayerType::TransposeConvolution2d:
         {
             auto cLayer = PolymorphicDowncast<const TransposeConvolution2dLayer*>(&layer);
             const TensorInfo input  = OverrideDataType(layer.GetInputSlot(0).GetConnection()->GetTensorInfo(),
                                                        dataType);
             const TensorInfo output = OverrideDataType(layer.GetOutputSlot(0).GetTensorInfo(), dataType);
             const TransposeConvolution2dDescriptor& descriptor  = cLayer->GetParameters();
             Optional<TensorInfo> biases;
             if (descriptor.m_BiasEnabled)
             {
                 ARMNN_ASSERT(cLayer->m_Bias.get() != nullptr);
                 biases = OverrideDataType(cLayer->m_Bias->GetTensorInfo(),
                                           GetBiasTypeFromWeightsType(dataType));
             }
             ARMNN_ASSERT(cLayer->m_Weight.get() != nullptr);
             const TensorInfo weights = OverrideDataType(cLayer->m_Weight->GetTensorInfo(), dataType);
             result = layerSupportObject->IsTransposeConvolution2dSupported(input,
                                                                            output,
                                                                            descriptor,
                                                                            weights,
                                                                            biases,
                                                                            reason);
             break;
         }
         default:
         {
             ARMNN_ASSERT_MSG(false, "WorkloadFactory did not recognise type of layer.");
             reason.value() = "Unrecognised layer type";
             result = false;
             break;
         }
     }
     return result;
 }
IsLayerSupported() [2/2]
bool IsLayerSupported (const IConnectableLayer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 1192 of file WorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
 {
     auto layer = PolymorphicDowncast<const Layer*>(&connectableLayer);
     return IsLayerSupported(layer->GetBackendId(), connectableLayer, dataType, outReasonIfUnsupported);
 }
SupportsSubTensors()
virtual bool SupportsSubTensors () const pure virtual
Implemented in RefWorkloadFactory, SampleDynamicWorkloadFactory, ClWorkloadFactory, NeonWorkloadFactory, and WorkloadFactoryBase.
Referenced by ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), and IWorkloadFactory::~IWorkloadFactory().
The documentation for this class was generated from the following files:
src/backends/backendsCommon/WorkloadFactory.hpp
src/backends/backendsCommon/WorkloadFactory.cpp