ArmNN: IMemoryManager Class Reference
IMemoryManager Class Reference abstract
#include <IMemoryManager.hpp>
Public Member Functions
virtual void Acquire ()=0
virtual void Release ()=0
virtual ~IMemoryManager ()
Protected Member Functions
IMemoryManager ()
Detailed Description
Definition at line 12 of file IMemoryManager.hpp.
Constructor & Destructor Documentation
IMemoryManager()
IMemoryManager () inline protected
Definition at line 15 of file IMemoryManager.hpp.
References IMemoryManager::Acquire(), and IMemoryManager::Release().
 {}
~IMemoryManager()
virtual ~IMemoryManager () inline virtual
Definition at line 21 of file IMemoryManager.hpp.
 {}
Member Function Documentation
Acquire()
virtual void Acquire () pure virtual
Implemented in BaseMemoryManager, RefMemoryManager, and SampleMemoryManager.
Referenced by IMemoryManager::IMemoryManager().
Release()
virtual void Release () pure virtual
Implemented in BaseMemoryManager, RefMemoryManager, and SampleMemoryManager.
Referenced by IMemoryManager::IMemoryManager().
The documentation for this class was generated from the following file:
include/armnn/backends/IMemoryManager.hpp