ArmNN: ITimelineDecoder Class Reference
ITimelineDecoder Class Reference abstract
#include <ITimelineDecoder.hpp>
Classes
struct Entity
struct Event
struct EventClass
struct Label
struct Relationship
Public Types
enum TimelineStatus { TimelineStatus_Success, TimelineStatus_Fail }
enum RelationshipType { RetentionLink, ExecutionLink, DataLink, LabelLink }
Public Member Functions
virtual ~ITimelineDecoder ()=default
virtual TimelineStatus CreateEntity (const Entity &)=0
virtual TimelineStatus CreateEventClass (const EventClass &)=0
virtual TimelineStatus CreateEvent (const Event &)=0
virtual TimelineStatus CreateLabel (const Label &)=0
virtual TimelineStatus CreateRelationship (const Relationship &)=0
Static Public Member Functions
static char const * GetRelationshipAsCString (RelationshipType rType)
Detailed Description
Definition at line 11 of file ITimelineDecoder.hpp.
Member Enumeration Documentation
RelationshipType
enum RelationshipType strong
Enumerator
RetentionLink
ExecutionLink
Head retains(parents) Tail.
DataLink
Head execution start depends on Tail execution completion.
LabelLink
Head uses data of Tail.
Head uses label Tail (Tail MUST be a guid of a label).
Definition at line 22 of file ITimelineDecoder.hpp.
     {
         RetentionLink, /// Head retains(parents) Tail
         ExecutionLink, /// Head execution start depends on Tail execution completion
         DataLink,      /// Head uses data of Tail
         LabelLink      /// Head uses label Tail (Tail MUST be a guid of a label).
     };
TimelineStatus
enum TimelineStatus strong
Enumerator
TimelineStatus_Success
TimelineStatus_Fail
Definition at line 16 of file ITimelineDecoder.hpp.
     {
         TimelineStatus_Success,
         TimelineStatus_Fail
     };
Constructor & Destructor Documentation
~ITimelineDecoder()
virtual ~ITimelineDecoder () virtual default
Member Function Documentation
CreateEntity()
virtual TimelineStatus CreateEntity (const Entity &) pure virtual
Implemented in JSONTimelineDecoder, TimelineDecoder, and TimelineMessageDecoder.
Referenced by TimelineCaptureCommandHandler::ReadEntity().
CreateEvent()
virtual TimelineStatus CreateEvent (const Event &) pure virtual
Implemented in JSONTimelineDecoder, TimelineDecoder, and TimelineMessageDecoder.
Referenced by TimelineCaptureCommandHandler::ReadEvent().
CreateEventClass()
virtual TimelineStatus CreateEventClass (const EventClass &) pure virtual
Implemented in JSONTimelineDecoder, TimelineDecoder, and TimelineMessageDecoder.
Referenced by TimelineCaptureCommandHandler::ReadEventClass().
CreateLabel()
virtual TimelineStatus CreateLabel (const Label &) pure virtual
Implemented in JSONTimelineDecoder, TimelineDecoder, and TimelineMessageDecoder.
Referenced by TimelineCaptureCommandHandler::ReadLabel().
CreateRelationship()
virtual TimelineStatus CreateRelationship (const Relationship &) pure virtual
Implemented in JSONTimelineDecoder, TimelineDecoder, and TimelineMessageDecoder.
Referenced by TimelineCaptureCommandHandler::ReadRelationship().
GetRelationshipAsCString()
static char const* GetRelationshipAsCString (RelationshipType rType) inline static
Definition at line 30 of file ITimelineDecoder.hpp.
References DataLink, ExecutionLink, LabelLink, and RetentionLink.
     {
         switch (rType)
         {
             case RelationshipType::RetentionLink: return "RetentionLink";
             case RelationshipType::ExecutionLink: return "ExecutionLink";
             case RelationshipType::DataLink: return "DataLink";
             case RelationshipType::LabelLink: return "LabelLink";
             default: return "Unknown";
         }
     }
The documentation for this class was generated from the following file:
include/armnn/profiling/ITimelineDecoder.hpp