ArmNN: ISendTimelinePacket Class Reference
ISendTimelinePacket Class Reference abstract
#include <ISendTimelinePacket.hpp>
Public Member Functions
virtual ~ISendTimelinePacket ()
virtual void Commit ()=0
Commits the current buffer and reset the member variables.
virtual void SendTimelineEntityBinaryPacket (uint64_t profilingGuid)=0
Create and write a TimelineEntityBinaryPacket from the parameters to the buffer.
virtual void SendTimelineEventBinaryPacket (uint64_t timestamp, std::thread::id threadId, uint64_t profilingGuid)=0
Create and write a TimelineEventBinaryPacket from the parameters to the buffer.
virtual void SendTimelineEventClassBinaryPacket (uint64_t profilingGuid)=0
Create and write a TimelineEventClassBinaryPacket from the parameters to the buffer.
virtual void SendTimelineLabelBinaryPacket (uint64_t profilingGuid, const std::string &label)=0
Create and write a TimelineLabelBinaryPacket from the parameters to the buffer.
virtual void SendTimelineMessageDirectoryPackage ()=0
Create and write a TimelineMessageDirectoryPackage in the buffer.
virtual void SendTimelineRelationshipBinaryPacket (ProfilingRelationshipType relationshipType, uint64_t relationshipGuid, uint64_t headGuid, uint64_t tailGuid)=0
Create and write a TimelineRelationshipBinaryPacket from the parameters to the buffer.
Detailed Description
Definition at line 27 of file ISendTimelinePacket.hpp.
Constructor & Destructor Documentation
~ISendTimelinePacket()
virtual ~ISendTimelinePacket () inline virtual
Definition at line 30 of file ISendTimelinePacket.hpp.
     {}
Member Function Documentation
Commit()
virtual void Commit () pure virtual
Commits the current buffer and reset the member variables.
Implemented in SendTimelinePacket.
Referenced by TimelineUtilityMethods::SendWellKnownLabelsAndEventClasses().
SendTimelineEntityBinaryPacket()
virtual void SendTimelineEntityBinaryPacket (uint64_t profilingGuid) pure virtual
Create and write a TimelineEntityBinaryPacket from the parameters to the buffer.
Implemented in SendTimelinePacket.
SendTimelineEventBinaryPacket()
virtual void SendTimelineEventBinaryPacket (uint64_t timestamp, std::thread::id threadId, uint64_t profilingGuid) pure virtual
Create and write a TimelineEventBinaryPacket from the parameters to the buffer.
Implemented in SendTimelinePacket.
SendTimelineEventClassBinaryPacket()
virtual void SendTimelineEventClassBinaryPacket (uint64_t profilingGuid) pure virtual
Create and write a TimelineEventClassBinaryPacket from the parameters to the buffer.
Implemented in SendTimelinePacket.
Referenced by TimelineUtilityMethods::SendWellKnownLabelsAndEventClasses().
SendTimelineLabelBinaryPacket()
virtual void SendTimelineLabelBinaryPacket (uint64_t profilingGuid, const std::string & label) pure virtual
Create and write a TimelineLabelBinaryPacket from the parameters to the buffer.
Implemented in SendTimelinePacket.
Referenced by TimelineUtilityMethods::SendWellKnownLabelsAndEventClasses().
SendTimelineMessageDirectoryPackage()
virtual void SendTimelineMessageDirectoryPackage () pure virtual
Create and write a TimelineMessageDirectoryPackage in the buffer.
Implemented in SendTimelinePacket.
Referenced by RequestCounterDirectoryCommandHandler::operator()(), and ConnectionAcknowledgedCommandHandler::operator()().
SendTimelineRelationshipBinaryPacket()
virtual void SendTimelineRelationshipBinaryPacket (ProfilingRelationshipType relationshipType, uint64_t relationshipGuid, uint64_t headGuid, uint64_t tailGuid) pure virtual
Create and write a TimelineRelationshipBinaryPacket from the parameters to the buffer.
Implemented in SendTimelinePacket.
The documentation for this class was generated from the following file:
include/armnn/profiling/ISendTimelinePacket.hpp