ArmNN: ExecutionFrame Class Reference
ExecutionFrame Class Reference
#include <ExecutionFrame.hpp>
Public Member Functions
ExecutionFrame ()
IExecutionFrame * ExecuteWorkloads (IExecutionFrame *previousFrame) override
void PostAllocationConfigure () override
void RegisterDebugCallback (const DebugCallbackFunction &func) override
void AddWorkloadToQueue (std::unique_ptr< IWorkload > workload)
void SetNextExecutionFrame (IExecutionFrame *nextExecutionFrame)
Public Member Functions inherited from IExecutionFrame
virtual ~IExecutionFrame ()
Detailed Description
Definition at line 27 of file ExecutionFrame.hpp.
Constructor & Destructor Documentation
ExecutionFrame()
ExecutionFrame ()
Definition at line 12 of file ExecutionFrame.cpp.
 {}
Member Function Documentation
AddWorkloadToQueue()
void AddWorkloadToQueue (std::unique_ptr< IWorkload > workload)
Definition at line 40 of file ExecutionFrame.cpp.
 {
     m_WorkloadQueue.push_back(move(workload));
 }
ExecuteWorkloads()
IExecutionFrame * ExecuteWorkloads (IExecutionFrame * previousFrame) override virtual
Implements IExecutionFrame.
Definition at line 14 of file ExecutionFrame.cpp.
References armnn::IgnoreUnused().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     IgnoreUnused(previousFrame);
     for (auto& workload: m_WorkloadQueue)
     {
         workload->Execute();
     }
     return m_NextExecutionFrame;
 }
PostAllocationConfigure()
void PostAllocationConfigure () override virtual
Reimplemented from IExecutionFrame.
Definition at line 24 of file ExecutionFrame.cpp.
 {
     for (auto&& workloadPtr: m_WorkloadQueue)
     {
         workloadPtr.get()->PostAllocationConfigure();
     }
 }
RegisterDebugCallback()
void RegisterDebugCallback (const DebugCallbackFunction & func) override virtual
Reimplemented from IExecutionFrame.
Definition at line 32 of file ExecutionFrame.cpp.
 {
     for (auto&& workloadPtr: m_WorkloadQueue)
     {
         workloadPtr.get()->RegisterDebugCallback(func);
     }
 }
SetNextExecutionFrame()
void SetNextExecutionFrame (IExecutionFrame * nextExecutionFrame)
Definition at line 45 of file ExecutionFrame.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     m_NextExecutionFrame = nextExecutionFrame;
 }
The documentation for this class was generated from the following files:
src/armnn/ExecutionFrame.hpp
src/armnn/ExecutionFrame.cpp