ArmNN: ISendCounterPacket Class Reference
ISendCounterPacket Class Reference abstract
#include <ISendCounterPacket.hpp>
Public Types
using IndexValuePairsVector = std::vector< CounterValue >
Public Member Functions
virtual ~ISendCounterPacket ()
virtual void SendStreamMetaDataPacket ()=0
Create and write a StreamMetaDataPacket in the buffer.
virtual void SendCounterDirectoryPacket (const ICounterDirectory &counterDirectory)=0
Create and write a CounterDirectoryPacket from the parameters to the buffer.
virtual void SendPeriodicCounterCapturePacket (uint64_t timestamp, const IndexValuePairsVector &values)=0
Create and write a PeriodicCounterCapturePacket from the parameters to the buffer.
virtual void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > &selectedCounterIds)=0
Create and write a PeriodicCounterSelectionPacket from the parameters to the buffer.
Detailed Description
Definition at line 17 of file ISendCounterPacket.hpp.
Member Typedef Documentation
IndexValuePairsVector
using IndexValuePairsVector = std::vector<CounterValue>
Definition at line 20 of file ISendCounterPacket.hpp.
Constructor & Destructor Documentation
~ISendCounterPacket()
virtual ~ISendCounterPacket () inline virtual
Definition at line 22 of file ISendCounterPacket.hpp.
References ISendCounterPacket::SendCounterDirectoryPacket(), ISendCounterPacket::SendPeriodicCounterCapturePacket(), ISendCounterPacket::SendPeriodicCounterSelectionPacket(), and ISendCounterPacket::SendStreamMetaDataPacket().
 {}
Member Function Documentation
SendCounterDirectoryPacket()
virtual void SendCounterDirectoryPacket (const ICounterDirectory & counterDirectory) pure virtual
Create and write a CounterDirectoryPacket from the parameters to the buffer.
Implemented in MockSendCounterPacket, and SendCounterPacket.
Referenced by RequestCounterDirectoryCommandHandler::operator()(), ConnectionAcknowledgedCommandHandler::operator()(), and ISendCounterPacket::~ISendCounterPacket().
SendPeriodicCounterCapturePacket()
virtual void SendPeriodicCounterCapturePacket (uint64_t timestamp, const IndexValuePairsVector & values) pure virtual
Create and write a PeriodicCounterCapturePacket from the parameters to the buffer.
Implemented in SendCounterPacket.
Referenced by BackendProfiling::ReportCounters(), PeriodicCounterCapture::Stop(), and ISendCounterPacket::~ISendCounterPacket().
SendPeriodicCounterSelectionPacket()
virtual void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > & selectedCounterIds) pure virtual
Create and write a PeriodicCounterSelectionPacket from the parameters to the buffer.
Implemented in MockSendCounterPacket, and SendCounterPacket.
Referenced by PeriodicCounterSelectionCommandHandler::operator()(), and ISendCounterPacket::~ISendCounterPacket().
SendStreamMetaDataPacket()
virtual void SendStreamMetaDataPacket () pure virtual
Create and write a StreamMetaDataPacket in the buffer.
Implemented in MockSendCounterPacket, and SendCounterPacket.
Referenced by SendThread::Stop(), and ISendCounterPacket::~ISendCounterPacket().
The documentation for this class was generated from the following file:
src/profiling/ISendCounterPacket.hpp