ArmNN: TimelineMessageDecoder Class Reference
TimelineMessageDecoder Class Reference
#include <TestTimelinePacketHandler.hpp>
Public Member Functions
TimelineMessageDecoder (TimelineModel &model)
virtual TimelineStatus CreateEntity (const Entity &) override
virtual TimelineStatus CreateEventClass (const EventClass &) override
virtual TimelineStatus CreateEvent (const Event &) override
virtual TimelineStatus CreateLabel (const Label &) override
virtual TimelineStatus CreateRelationship (const Relationship &) override
void SetPacketHandler (TestTimelinePacketHandler *packetHandler)
Public Member Functions inherited from ITimelineDecoder
virtual ~ITimelineDecoder ()=default
Additional Inherited Members
Public Types inherited from ITimelineDecoder
enum TimelineStatus { TimelineStatus_Success, TimelineStatus_Fail }
enum RelationshipType { RetentionLink, ExecutionLink, DataLink, LabelLink }
Static Public Member Functions inherited from ITimelineDecoder
static char const * GetRelationshipAsCString (RelationshipType rType)
Detailed Description
Definition at line 30 of file TestTimelinePacketHandler.hpp.
Constructor & Destructor Documentation
TimelineMessageDecoder()
TimelineMessageDecoder (TimelineModel & model) inline
Definition at line 33 of file TestTimelinePacketHandler.hpp.
References TimelineMessageDecoder::CreateEntity(), TimelineMessageDecoder::CreateEvent(), TimelineMessageDecoder::CreateEventClass(), TimelineMessageDecoder::CreateLabel(), and TimelineMessageDecoder::CreateRelationship().
 : m_PacketHandler(nullptr), m_TimelineModel(model) {}
Member Function Documentation
CreateEntity()
ITimelineDecoder::TimelineStatus CreateEntity (const Entity & entity) override virtual
Implements ITimelineDecoder.
Definition at line 92 of file TestTimelinePacketHandler.cpp.
References TimelineModel::AddEntity(), ITimelineDecoder::Entity::m_Guid, and ITimelineDecoder::TimelineStatus_Success.
Referenced by TimelineMessageDecoder::TimelineMessageDecoder().
 {
     m_TimelineModel.AddEntity(entity.m_Guid);
     return ITimelineDecoder::TimelineStatus::TimelineStatus_Success;
 }
CreateEvent()
ITimelineDecoder::TimelineStatus CreateEvent (const Event & event) override virtual
Implements ITimelineDecoder.
Definition at line 111 of file TestTimelinePacketHandler.cpp.
References armnn::IgnoreUnused(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by TimelineMessageDecoder::TimelineMessageDecoder().
 {
     IgnoreUnused(event);
     return ITimelineDecoder::TimelineStatus::TimelineStatus_Success;
 }
CreateEventClass()
ITimelineDecoder::TimelineStatus CreateEventClass (const EventClass & eventClass) override virtual
Implements ITimelineDecoder.
Definition at line 98 of file TestTimelinePacketHandler.cpp.
References armnn::IgnoreUnused(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by TimelineMessageDecoder::TimelineMessageDecoder().
 {
     // for the moment terminate the run here so we can get this code
     // onto master prior to a major re-organisation
     if (m_PacketHandler != nullptr)
     {
         m_PacketHandler->SetInferenceComplete();
     }
     IgnoreUnused(eventClass);
     return ITimelineDecoder::TimelineStatus::TimelineStatus_Success;
 }
CreateLabel()
ITimelineDecoder::TimelineStatus CreateLabel (const Label & label) override virtual
Implements ITimelineDecoder.
Definition at line 117 of file TestTimelinePacketHandler.cpp.
References TimelineModel::AddLabel(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by TimelineMessageDecoder::TimelineMessageDecoder().
 {
     m_TimelineModel.AddLabel(label);
     return ITimelineDecoder::TimelineStatus::TimelineStatus_Success;
 }
CreateRelationship()
ITimelineDecoder::TimelineStatus CreateRelationship (const Relationship & relationship) override virtual
Implements ITimelineDecoder.
Definition at line 123 of file TestTimelinePacketHandler.cpp.
References TimelineModel::AddRelationship(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by TimelineMessageDecoder::TimelineMessageDecoder().
 {
     m_TimelineModel.AddRelationship(relationship);
     return ITimelineDecoder::TimelineStatus::TimelineStatus_Success;
 }
SetPacketHandler()
void SetPacketHandler (TestTimelinePacketHandler * packetHandler) inline
Definition at line 39 of file TestTimelinePacketHandler.hpp.
 {m_PacketHandler = packetHandler;};
The documentation for this class was generated from the following files:
src/profiling/test/TestTimelinePacketHandler.hpp
src/profiling/test/TestTimelinePacketHandler.cpp