ArmNN: CommandHandlerRegistry Class Reference
CommandHandlerRegistry Class Reference
#include <CommandHandlerRegistry.hpp>
Public Member Functions
CommandHandlerRegistry ()=default
void RegisterFunctor (CommandHandlerFunctor *functor, uint32_t familyId, uint32_t packetId, uint32_t version)
void RegisterFunctor (CommandHandlerFunctor *functor)
CommandHandlerFunctor * GetFunctor (uint32_t familyId, uint32_t packetId, uint32_t version) const
Detailed Description
Definition at line 32 of file CommandHandlerRegistry.hpp.
Constructor & Destructor Documentation
CommandHandlerRegistry()
CommandHandlerRegistry () default
Member Function Documentation
GetFunctor()
CommandHandlerFunctor * GetFunctor (uint32_t familyId, uint32_t packetId, uint32_t version) const
Definition at line 36 of file CommandHandlerRegistry.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandler::Stop(), and GatordMockService::WaitCommand().
 {
     CommandHandlerKey key(familyId, packetId, version);
     // Check that the requested key exists
     if (registry.find(key) == registry.end())
     {
         throw armnn::InvalidArgumentException(
                     boost::str(boost::format("Functor with requested PacketId=%1% and Version=%2% does not exist")
                                % packetId
                                % version));
     }
     CommandHandlerFunctor* commandHandlerFunctor = registry.at(key);
     if (commandHandlerFunctor == nullptr)
     {
         throw RuntimeException(
                     boost::str(boost::format("Invalid functor registered for PacketId=%1% and Version=%2%")
                                % packetId
                                % version));
     }
     return commandHandlerFunctor;
 }
RegisterFunctor() [1/2]
void RegisterFunctor (CommandHandlerFunctor * functor, uint32_t familyId, uint32_t packetId, uint32_t version)
Definition at line 18 of file CommandHandlerRegistry.cpp.
References ARMNN_ASSERT_MSG.
Referenced by BOOST_AUTO_TEST_CASE(), GatordMockService::GatordMockService(), ProfilingService::ProfilingService(), and CommandHandlerRegistry::RegisterFunctor().
 {
     ARMNN_ASSERT_MSG(functor, "Provided functor should not be a nullptr");
     CommandHandlerKey key(familyId, packetId, version);
     registry[key] = functor;
 }
RegisterFunctor() [2/2]
void RegisterFunctor (CommandHandlerFunctor * functor)
Definition at line 29 of file CommandHandlerRegistry.cpp.
References ARMNN_ASSERT_MSG, CommandHandlerFunctor::GetFamilyId(), CommandHandlerFunctor::GetPacketId(), CommandHandlerFunctor::GetVersion(), and CommandHandlerRegistry::RegisterFunctor().
 {
     ARMNN_ASSERT_MSG(functor, "Provided functor should not be a nullptr");
     RegisterFunctor(functor, functor->GetFamilyId(), functor->GetPacketId(), functor->GetVersion());
 }
The documentation for this class was generated from the following files:
src/profiling/CommandHandlerRegistry.hpp
src/profiling/CommandHandlerRegistry.cpp