ArmNN: RefElementwiseWorkload< Functor, ParentDescriptor, DebugString > Class Template Reference
RefElementwiseWorkload< Functor, ParentDescriptor, DebugString > Class Template Reference
#include <RefElementwiseWorkload.hpp>
Public Types
using InType = typename ElementwiseBinaryFunction< Functor >::InType
using OutType = typename ElementwiseBinaryFunction< Functor >::OutType
Public Member Functions
RefElementwiseWorkload (const ParentDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
void Execute () const override
Public Member Functions inherited from BaseWorkload< ParentDescriptor >
BaseWorkload (const ParentDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const ParentDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ParentDescriptor >
const ParentDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
template<typename Functor, typename ParentDescriptor, typename armnn::StringMapping::Id DebugString>
class armnn::RefElementwiseWorkload< Functor, ParentDescriptor, DebugString >
Definition at line 21 of file RefElementwiseWorkload.hpp.
Member Typedef Documentation
InType
using InType = typename ElementwiseBinaryFunction<Functor>::InType
Definition at line 24 of file RefElementwiseWorkload.hpp.
OutType
using OutType = typename ElementwiseBinaryFunction<Functor>::OutType
Definition at line 25 of file RefElementwiseWorkload.hpp.
Constructor & Destructor Documentation
RefElementwiseWorkload()
RefElementwiseWorkload (const ParentDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 21 of file RefElementwiseWorkload.cpp.
     : BaseWorkload<ParentDescriptor>(desc, info)
 {
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 41 of file RefElementwiseWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, armnn::CpuRef, TensorInfo::GetShape(), armnn::GetTensorInfo(), StringMapping::Instance(), BaseWorkload< ParentDescriptor >::m_Data, StringMapping::RefAdditionWorkload_Execute, StringMapping::RefDivisionWorkload_Execute, StringMapping::RefMaximumWorkload_Execute, StringMapping::RefMinimumWorkload_Execute, StringMapping::RefMultiplicationWorkload_Execute, and StringMapping::RefSubtractionWorkload_Execute.
 {
     ARMNN_SCOPED_PROFILING_EVENT(Compute::CpuRef, StringMapping::Instance().Get(DebugString));
     const TensorInfo& inputInfo0 = GetTensorInfo(m_Data.m_Inputs[0]);
     const TensorInfo& inputInfo1 = GetTensorInfo(m_Data.m_Inputs[1]);
     const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
     const TensorShape& inShape0 = inputInfo0.GetShape();
     const TensorShape& inShape1 = inputInfo1.GetShape();
     const TensorShape& outShape = outputInfo.GetShape();
     m_Input0->Reset(m_Data.m_Inputs[0]->Map());
     m_Input1->Reset(m_Data.m_Inputs[1]->Map());
     m_Output->Reset(m_Data.m_Outputs[0]->Map());
     ElementwiseBinaryFunction<Functor>(inShape0,
                                        inShape1,
                                        outShape,
                                        *m_Input0,
                                        *m_Input1,
                                        *m_Output);
 }
PostAllocationConfigure()
void PostAllocationConfigure () override virtual
Implements IWorkload.
Definition at line 29 of file RefElementwiseWorkload.cpp.
References armnn::GetTensorInfo(), and BaseWorkload< ParentDescriptor >::m_Data.
 {
     const TensorInfo& inputInfo0 = GetTensorInfo(m_Data.m_Inputs[0]);
     const TensorInfo& inputInfo1 = GetTensorInfo(m_Data.m_Inputs[1]);
     const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
     m_Input0 = MakeDecoder<InType>(inputInfo0);
     m_Input1 = MakeDecoder<InType>(inputInfo1);
     m_Output = MakeEncoder<OutType>(outputInfo);
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefElementwiseWorkload.hpp
src/backends/reference/workloads/RefElementwiseWorkload.cpp