ArmNN: JSONTimelineDecoder Class Reference
JSONTimelineDecoder Class Reference
#include <JSONTimelineDecoder.hpp>
Classes
struct JSONEntity
struct Model
Public Member Functions
void PrintJSON (JSONEntity &entity)
std::string GetJSONString (JSONEntity &rootEntity)
std::string GetJSONEntityString (JSONEntity &entity, int &counter)
virtual TimelineStatus CreateEntity (const Entity &) override
virtual TimelineStatus CreateEventClass (const EventClass &) override
virtual TimelineStatus CreateEvent (const Event &) override
virtual TimelineStatus CreateLabel (const Label &) override
virtual TimelineStatus CreateRelationship (const Relationship &) override
const Model & GetModel ()
void SetOutgoingCaptureFile (const std::string &basicString)
Public Member Functions inherited from ITimelineDecoder
virtual ~ITimelineDecoder ()=default
Additional Inherited Members
Public Types inherited from ITimelineDecoder
enum TimelineStatus { TimelineStatus_Success, TimelineStatus_Fail }
enum RelationshipType { RetentionLink, ExecutionLink, DataLink, LabelLink }
Static Public Member Functions inherited from ITimelineDecoder
static char const * GetRelationshipAsCString (RelationshipType rType)
Detailed Description
Definition at line 19 of file JSONTimelineDecoder.hpp.
Member Function Documentation
CreateEntity()
JSONTimelineDecoder::TimelineStatus CreateEntity (const Entity & entity) override virtual
Implements ITimelineDecoder.
Definition at line 30 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::Model::jsonEntities, ITimelineDecoder::Entity::m_Guid, JSONTimelineDecoder::JSONEntity::SetType(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by RunSimpleModelThroughDecoder().
 {
     JSONEntity jsonEntity(entity.m_Guid);
     jsonEntity.SetType(ENTITY);
     this->m_Model.jsonEntities.insert({entity.m_Guid, jsonEntity});
     return TimelineStatus::TimelineStatus_Success;
 }
CreateEvent()
JSONTimelineDecoder::TimelineStatus CreateEvent (const Event & event) override virtual
Implements ITimelineDecoder.
Definition at line 47 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::Model::events, JSONTimelineDecoder::JSONEntity::GetGuid(), JSONTimelineDecoder::Model::jsonEntities, ITimelineDecoder::Event::m_Guid, JSONTimelineDecoder::JSONEntity::SetType(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by RunSimpleModelThroughDecoder().
 {
     JSONEntity jsonEntity(event.m_Guid);
     jsonEntity.SetType(EVENT);
     this->m_Model.events.insert({event.m_Guid, event});
     this->m_Model.jsonEntities.insert({jsonEntity.GetGuid(), jsonEntity});
     return TimelineStatus::TimelineStatus_Success;
 }
CreateEventClass()
JSONTimelineDecoder::TimelineStatus CreateEventClass (const EventClass & eventClass) override virtual
Implements ITimelineDecoder.
Definition at line 38 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::Model::eventClasses, JSONTimelineDecoder::Model::jsonEntities, ITimelineDecoder::EventClass::m_Guid, JSONTimelineDecoder::JSONEntity::SetType(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by RunSimpleModelThroughDecoder().
 {
     JSONEntity jsonEntity(eventClass.m_Guid);
     jsonEntity.SetType(EVENTCLASS);
     this->m_Model.eventClasses.insert({eventClass.m_Guid, eventClass});
     this->m_Model.jsonEntities.insert({eventClass.m_Guid, jsonEntity});
     return TimelineStatus::TimelineStatus_Success;
 }
CreateLabel()
JSONTimelineDecoder::TimelineStatus CreateLabel (const Label & label) override virtual
Implements ITimelineDecoder.
Definition at line 56 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::Model::labels, ITimelineDecoder::Label::m_Guid, and ITimelineDecoder::TimelineStatus_Success.
Referenced by RunSimpleModelThroughDecoder().
 {
     this->m_Model.labels.insert({label.m_Guid, label});
     return TimelineStatus::TimelineStatus_Success;
 }
CreateRelationship()
JSONTimelineDecoder::TimelineStatus CreateRelationship (const Relationship & relationship) override virtual
Implements ITimelineDecoder.
Definition at line 62 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::JSONEntity::AddConnection(), ITimelineDecoder::ExecutionLink, JSONTimelineDecoder::JSONEntity::extendedData, JSONTimelineDecoder::Model::jsonEntities, ITimelineDecoder::LabelLink, JSONTimelineDecoder::Model::labels, ITimelineDecoder::Relationship::m_Guid, ITimelineDecoder::Relationship::m_HeadGuid, ITimelineDecoder::Relationship::m_RelationshipType, ITimelineDecoder::Relationship::m_TailGuid, JSONTimelineDecoder::Model::relationships, ITimelineDecoder::RetentionLink, JSONTimelineDecoder::JSONEntity::SetName(), JSONTimelineDecoder::JSONEntity::SetParent(), JSONTimelineDecoder::JSONEntity::SetType(), and ITimelineDecoder::TimelineStatus_Success.
Referenced by RunSimpleModelThroughDecoder().
 {
     if (relationship.m_RelationshipType == ITimelineDecoder::RelationshipType::RetentionLink)
     {
         HandleRetentionLink(relationship);
     }
     else if (relationship.m_RelationshipType == ITimelineDecoder::RelationshipType::LabelLink)
     {
         HandleLabelLink(relationship);
     }
     else if (relationship.m_RelationshipType == ITimelineDecoder::RelationshipType::ExecutionLink)
     {
         HandleExecutionLink(relationship);
     }
     else
     {
         /*
          * TODO Handle DataLink
          */
         m_Model.relationships.insert({relationship.m_Guid, relationship});
     }
     return TimelineStatus::TimelineStatus_Success;
 }
GetJSONEntityString()
std::string GetJSONEntityString (JSONTimelineDecoder::JSONEntity & entity, int & counter)
Definition at line 274 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::JSONEntity::childEntities, JSONTimelineDecoder::Model::events, JSONTimelineDecoder::JSONEntity::extendedData, JSONTimelineDecoder::JSONEntity::GetGuid(), JSONTimelineDecoder::JSONEntity::GetName(), JSONTimelineDecoder::JSONEntity::GetType(), JSONTimelineDecoder::Model::jsonEntities, and ITimelineDecoder::Event::m_TimeStamp.
Referenced by JSONTimelineDecoder::GetJSONString().
 {
     std::string jsonEntityString;
     if(entity.GetType() == LAYER)
     {
         return GetLayerJSONString(entity, counter, jsonEntityString);
     }
     else if (entity.GetType() == WORKLOAD)
     {
         return GetWorkloadJSONString(entity, counter, jsonEntityString);
     }
     else if (entity.GetType() == WORKLOAD_EXECUTION)
     {
         return GetWorkloadExecutionJSONString(entity, jsonEntityString);
     }
     else if (entity.GetType() == INFERENCE)
     {
         return jsonEntityString;
     }
     else
     {
         for (uint64_t child_entity_id : entity.childEntities)
         {
             JSONEntity& childEntity = this->m_Model.jsonEntities.at(child_entity_id);
             jsonEntityString.append(GetJSONEntityString(childEntity, ++counter));
         }
         return jsonEntityString;
     }
 }
GetJSONString()
std::string GetJSONString (JSONTimelineDecoder::JSONEntity & rootEntity)
Definition at line 254 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::JSONEntity::childEntities, JSONTimelineDecoder::GetJSONEntityString(), JSONTimelineDecoder::JSONEntity::GetType(), and JSONTimelineDecoder::Model::jsonEntities.
Referenced by BOOST_AUTO_TEST_CASE(), and JSONTimelineDecoder::PrintJSON().
 {
     int counter = 0;
     std::string json;
     json.append("{\n");
     if(rootEntity.GetType() != "")
     {
         json.append("\tArmNN");
         json.append(": {\n");
         for (uint64_t childEntityId : rootEntity.childEntities)
         {
             JSONEntity& childEntity = this->m_Model.jsonEntities.at(childEntityId);
             json.append(GetJSONEntityString(childEntity, counter));
         }
     }
     json.append("}\n");
     return json;
 }
GetModel()
const JSONTimelineDecoder::Model & GetModel ()
Definition at line 376 of file JSONTimelineDecoder.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return m_Model;
 }
PrintJSON()
void PrintJSON (JSONTimelineDecoder::JSONEntity & rootEntity)
Definition at line 246 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::GetJSONString().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     std::string jsonString = GetJSONString(rootEntity);
     boost::filesystem::ofstream ofs{this->outputJSONFile};
     ofs << jsonString;
     ofs.close();
 }
SetOutgoingCaptureFile()
void SetOutgoingCaptureFile (const std::string & basicString)
Definition at line 381 of file JSONTimelineDecoder.cpp.
 {
     this->outputJSONFile = outgoingCaptureFile;
 }
The documentation for this class was generated from the following files:
src/timelineDecoder/JSONTimelineDecoder.hpp
src/timelineDecoder/JSONTimelineDecoder.cpp