ArmNN: OnnxParser Class Reference
OnnxParser Class Reference
#include <OnnxParser.hpp>
Public Types
using GraphPtr = std::unique_ptr< onnx::GraphProto >
Public Member Functions
virtual armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile) override
Create the network from a protobuf binary file on disk.
virtual armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile) override
Create the network from a protobuf text file on disk.
virtual armnn::INetworkPtr CreateNetworkFromString (const std::string &protoText) override
Create the network directly from protobuf text in a string. Useful for debugging/testing.
virtual BindingPointInfo GetNetworkInputBindingInfo (const std::string &name) const override
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
virtual BindingPointInfo GetNetworkOutputBindingInfo (const std::string &name) const override
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
OnnxParser ()
template<typename TypePair , typename Location >
void ValidateInputs (const onnx::NodeProto &node, TypePair validInputs, const Location &location)
Static Public Member Functions
static ModelPtr LoadModelFromBinaryFile (const char *fileName)
static ModelPtr LoadModelFromTextFile (const char *fileName)
static ModelPtr LoadModelFromString (const std::string &inputString)
static std::vector< std::string > GetInputs (ModelPtr &model)
Retrieve inputs names.
static std::vector< std::string > GetOutputs (ModelPtr &model)
Retrieve outputs names.
Static Public Member Functions inherited from IOnnxParser
static IOnnxParser * CreateRaw ()
static IOnnxParserPtr Create ()
static void Destroy (IOnnxParser *parser)
Additional Inherited Members
Protected Member Functions inherited from IOnnxParser
virtual ~IOnnxParser ()
Detailed Description
Definition at line 25 of file OnnxParser.hpp.
Member Typedef Documentation
GraphPtr
using GraphPtr = std::unique_ptr<onnx::GraphProto>
Definition at line 32 of file OnnxParser.hpp.
Constructor & Destructor Documentation
OnnxParser()
OnnxParser ()
Definition at line 449 of file OnnxParser.cpp.
References CHECK_LOCATION, TensorInfo::GetNumBytes(), and TensorInfo::GetNumElements().
     : m_Network(nullptr, nullptr)
 {
 }
Member Function Documentation
CreateNetworkFromBinaryFile()
INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile) override virtual
Create the network from a protobuf binary file on disk.
Implements IOnnxParser.
Definition at line 572 of file OnnxParser.cpp.
References OnnxParser::LoadModelFromBinaryFile().
 {
     ResetParser();
     ModelPtr modelProto = LoadModelFromBinaryFile(graphFile);
     return CreateNetworkFromModel(*modelProto);
 }
CreateNetworkFromString()
INetworkPtr CreateNetworkFromString (const std::string & protoText) override virtual
Create the network directly from protobuf text in a string. Useful for debugging/testing.
Implements IOnnxParser.
Definition at line 599 of file OnnxParser.cpp.
References ARMNN_ASSERT, armnnTfParser::CalcPadding(), CHECK_LOCATION, CHECK_VALID_DATATYPE, CHECK_VALID_SIZE, CHECKED_INT32, IConnectableLayer::GetInputSlot(), TensorShape::GetNumDimensions(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetNumOutputSlots(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), OnnxParser::LoadModelFromString(), ActivationDescriptor::m_A, ActivationDescriptor::m_B, FullyConnectedDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_BiasEnabled, BatchNormalizationDescriptor::m_Eps, ActivationDescriptor::m_Function, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Convolution2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, Convolution2dDescriptor::m_StrideY, ReshapeDescriptor::m_TargetShape, TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), STR_LIST, armnnDeserializer::ToTensorInfo(), and VALID_INPUTS.
 {
     ResetParser();
     ModelPtr modelProto = LoadModelFromString(protoText);
     return CreateNetworkFromModel(*modelProto);
 }
CreateNetworkFromTextFile()
INetworkPtr CreateNetworkFromTextFile (const char * graphFile) override virtual
Create the network from a protobuf text file on disk.
Implements IOnnxParser.
Definition at line 534 of file OnnxParser.cpp.
References OnnxParser::LoadModelFromTextFile().
 {
     ResetParser();
     ModelPtr modelProto = LoadModelFromTextFile(graphFile);
     return CreateNetworkFromModel(*modelProto);
 }
GetInputs()
std::vector< std::string > GetInputs (ModelPtr & model) static
Retrieve inputs names.
Definition at line 1791 of file OnnxParser.cpp.
References CHECK_LOCATION.
Referenced by BOOST_FIXTURE_TEST_CASE().
 {
     if(model == nullptr) {
         throw InvalidArgumentException(boost::str(
             boost::format("The given model cannot be null %1%")
             % CHECK_LOCATION().AsString()));
     }
     std::vector<std::string> inputNames;
     std::map<std::string, bool> isConstant;
     for(auto tensor : model->graph().initializer())
     {
         isConstant[tensor.name()] = true;
     }
     for(auto input : model->graph().input())
     {
         auto it = isConstant.find(input.name());
         if(it == isConstant.end())
         {
             inputNames.push_back(input.name());
         }
     }
     return inputNames;
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (const std::string & name) const override virtual
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Implements IOnnxParser.
Definition at line 1763 of file OnnxParser.cpp.
References CHECK_LOCATION, and armnnDeserializer::ToTensorInfo().
 {
     for(int i = 0; i < m_Graph->input_size(); ++i)
     {
         auto input = m_Graph->input(i);
         if(input.name() == name)
         {
             return std::make_pair(static_cast<armnn::LayerBindingId>(i), ToTensorInfo(input));
         }
     }
     throw InvalidArgumentException(boost::str(boost::format("The input layer '%1%' does not exist %2%")
                                                             % name % CHECK_LOCATION().AsString()));
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (const std::string & name) const override virtual
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Implements IOnnxParser.
Definition at line 1777 of file OnnxParser.cpp.
References CHECK_LOCATION, and armnnDeserializer::ToTensorInfo().
 {
     for(int i = 0; i < m_Graph->output_size(); ++i)
     {
         auto output = m_Graph->output(i);
         if(output.name() == name)
         {
             return std::make_pair(static_cast<armnn::LayerBindingId>(i), ToTensorInfo(output));
         }
     }
     throw InvalidArgumentException(boost::str(boost::format("The output layer '%1%' does not exist %2%")
                                                             % name % CHECK_LOCATION().AsString()));
 }
GetOutputs()
std::vector< std::string > GetOutputs (ModelPtr & model) static
Retrieve outputs names.
Definition at line 1816 of file OnnxParser.cpp.
References CHECK_LOCATION.
Referenced by BOOST_FIXTURE_TEST_CASE().
 {
     if(model == nullptr) {
         throw InvalidArgumentException(boost::str(
             boost::format("The given model cannot be null %1%")
             % CHECK_LOCATION().AsString()));
     }
     std::vector<std::string> outputNames;
     for(auto output : model->graph().output())
     {
         outputNames.push_back(output.name());
     }
     return outputNames;
 }
LoadModelFromBinaryFile()
ModelPtr LoadModelFromBinaryFile (const char * fileName) static
Definition at line 542 of file OnnxParser.cpp.
References CHECK_LOCATION, and armnn::error.
Referenced by OnnxParser::CreateNetworkFromBinaryFile().
 {
     FILE* fd = fopen(graphFile, "rb");
     if (fd == nullptr)
     {
         throw FileNotFoundException(boost::str(
             boost::format("Invalid (null) filename %1%") % CHECK_LOCATION().AsString()));
     }
     // Parse the file into a message
     ModelPtr modelProto = std::make_unique<onnx::ModelProto>();
     google::protobuf::io::FileInputStream  inStream(fileno(fd));
     google::protobuf::io::CodedInputStream codedStream(&inStream);
     codedStream.SetTotalBytesLimit(INT_MAX, INT_MAX);
     bool success = modelProto.get()->ParseFromCodedStream(&codedStream);
     fclose(fd);
     if (!success)
     {
         std::stringstream error;
         error << "Failed to parse graph file";
         throw ParseException(boost::str(
             boost::format("%1% %2%") % error.str() % CHECK_LOCATION().AsString()));
     }
     return modelProto;
 }
LoadModelFromString()
ModelPtr LoadModelFromString (const std::string & inputString) static
Definition at line 579 of file OnnxParser.cpp.
References CHECK_LOCATION, and armnn::error.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), and OnnxParser::CreateNetworkFromString().
 {
     if (protoText == "")
     {
         throw InvalidArgumentException(boost::str(
                 boost::format("Invalid (empty) string for model parameter %1%") % CHECK_LOCATION().AsString()));
     }
     // Parse the string into a message
     ModelPtr modelProto = std::make_unique<onnx::ModelProto>();
     bool success = google::protobuf::TextFormat::ParseFromString(protoText, modelProto.get());
     if (!success)
     {
         std::stringstream error;
         error << "Failed to parse graph file";
         throw ParseException(boost::str(
                 boost::format("%1% %2%") % error.str() % CHECK_LOCATION().AsString()));
     }
     return modelProto;
 }
LoadModelFromTextFile()
ModelPtr LoadModelFromTextFile (const char * fileName) static
Definition at line 507 of file OnnxParser.cpp.
References CHECK_LOCATION, and armnn::error.
Referenced by OnnxParser::CreateNetworkFromTextFile().
 {
     FILE* fd = fopen(graphFile, "r");
     if (fd == nullptr)
     {
         throw FileNotFoundException(boost::str(
             boost::format("Invalid (null) filename %1%") % CHECK_LOCATION().AsString()));
     }
     // Parse the file into a message
     ModelPtr     modelProto = std::make_unique<onnx::ModelProto>();
     using google::protobuf::io::FileInputStream;
     std::unique_ptr<FileInputStream> input = std::make_unique<FileInputStream>(fileno(fd));
     bool                 success = google::protobuf::TextFormat::Parse(input.get(), modelProto.get());
     fclose(fd);
     if (!success)
     {
         std::stringstream error;
         error << "Failed to parse graph file";
         throw ParseException(boost::str(
             boost::format("%1% %2%") % error.str() % CHECK_LOCATION().AsString()));
     }
     return modelProto;
 }
ValidateInputs()
void ValidateInputs (const onnx::NodeProto & node, TypePair validInputs, const Location & location)
Definition at line 382 of file OnnxParser.cpp.
 {
     for(auto input : node.input())
     {
         CheckValidDataType(validInputs.second,
                            m_TensorsInfo[input].m_dtype,
                            validInputs.first,
                            node.name(),
                            input,
                            location);
     }
 }
The documentation for this class was generated from the following files:
src/armnnOnnxParser/OnnxParser.hpp
src/armnnOnnxParser/OnnxParser.cpp