ArmNN: PacketKey Class Reference
PacketKey Class Reference final
#include <PacketVersionResolver.hpp>
Public Member Functions
PacketKey (uint32_t familyId, uint32_t packetId)
uint32_t GetFamilyId ()
uint32_t GetPacketId ()
bool operator< (const PacketKey &rhs) const
bool operator> (const PacketKey &rhs) const
bool operator<= (const PacketKey &rhs) const
bool operator>= (const PacketKey &rhs) const
bool operator== (const PacketKey &rhs) const
bool operator!= (const PacketKey &rhs) const
Detailed Description
Definition at line 16 of file PacketVersionResolver.hpp.
Constructor & Destructor Documentation
PacketKey()
PacketKey (uint32_t familyId, uint32_t packetId) inline
Definition at line 19 of file PacketVersionResolver.hpp.
 : m_FamilyId(familyId), m_PacketId(packetId) {}
Member Function Documentation
GetFamilyId()
uint32_t GetFamilyId () inline
Definition at line 21 of file PacketVersionResolver.hpp.
 { return m_FamilyId; }
GetPacketId()
uint32_t GetPacketId () inline
Definition at line 22 of file PacketVersionResolver.hpp.
References PacketKey::operator!=(), PacketKey::operator<(), PacketKey::operator<=(), PacketKey::operator==(), PacketKey::operator>(), and PacketKey::operator>=().
 { return m_PacketId; }
operator!=()
bool operator!= (const PacketKey & rhs) const
Definition at line 50 of file PacketVersionResolver.cpp.
Referenced by PacketKey::GetPacketId().
 {
     return !(*this == rhs);
 }
operator<()
bool operator< (const PacketKey & rhs) const
Definition at line 16 of file PacketVersionResolver.cpp.
Referenced by PacketKey::GetPacketId().
 {
     bool result = true;
     if (m_FamilyId == rhs.m_FamilyId)
     {
             result = m_PacketId < rhs.m_PacketId;
     }
     else if (m_FamilyId > rhs.m_FamilyId)
     {
         result = false;
     }
     return result;
 }
operator<=()
bool operator<= (const PacketKey & rhs) const
Definition at line 35 of file PacketVersionResolver.cpp.
Referenced by PacketKey::GetPacketId().
 {
     return !(*this > rhs);
 }
operator==()
bool operator== (const PacketKey & rhs) const
Definition at line 45 of file PacketVersionResolver.cpp.
Referenced by PacketKey::GetPacketId().
 {
     return m_FamilyId == rhs.m_FamilyId && m_PacketId == rhs.m_PacketId;
 }
operator>()
bool operator> (const PacketKey & rhs) const
Definition at line 30 of file PacketVersionResolver.cpp.
Referenced by PacketKey::GetPacketId().
 {
     return rhs < *this;
 }
operator>=()
bool operator>= (const PacketKey & rhs) const
Definition at line 40 of file PacketVersionResolver.cpp.
Referenced by PacketKey::GetPacketId().
 {
     return !(*this < rhs);
 }
The documentation for this class was generated from the following files:
src/profiling/PacketVersionResolver.hpp
src/profiling/PacketVersionResolver.cpp