ArmNN: TimelineCaptureCommandHandler Class Reference
TimelineCaptureCommandHandler Class Reference
#include <TimelineCaptureCommandHandler.hpp>
Public Member Functions
TimelineCaptureCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, ITimelineDecoder &timelineDecoder, uint32_t threadIdSize=0)
void operator() (const armnn::profiling::Packet &packet) override
void ReadLabel (const unsigned char *data, uint32_t &offset)
void ReadEntity (const unsigned char *data, uint32_t &offset)
void ReadEventClass (const unsigned char *data, uint32_t &offset)
void ReadRelationship (const unsigned char *data, uint32_t &offset)
void ReadEvent (const unsigned char *data, uint32_t &offset)
void SetThreadIdSize (uint32_t size)
Public Member Functions inherited from CommandHandlerFunctor
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
virtual void operator() (const Packet &packet)=0
virtual ~CommandHandlerFunctor ()
Detailed Description
Definition at line 20 of file TimelineCaptureCommandHandler.hpp.
Constructor & Destructor Documentation
TimelineCaptureCommandHandler()
TimelineCaptureCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, ITimelineDecoder & timelineDecoder, uint32_t threadIdSize = 0) inline
Definition at line 30 of file TimelineCaptureCommandHandler.hpp.
References TimelineCaptureCommandHandler::operator()(), TimelineCaptureCommandHandler::ReadEntity(), TimelineCaptureCommandHandler::ReadEvent(), TimelineCaptureCommandHandler::ReadEventClass(), TimelineCaptureCommandHandler::ReadLabel(), TimelineCaptureCommandHandler::ReadRelationship(), and TimelineCaptureCommandHandler::SetThreadIdSize().
         : CommandHandlerFunctor(familyId, packetId, version)
         , m_TimelineDecoder(timelineDecoder)
         , m_ThreadIdSize(threadIdSize)
         , m_PacketLength(0)
     {}
Member Function Documentation
operator()()
void operator() (const armnn::profiling::Packet & packet) override
Definition at line 141 of file TimelineCaptureCommandHandler.cpp.
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ParseData(packet);
 }
ReadEntity()
void ReadEntity (const unsigned char * data, uint32_t & offset)
Definition at line 79 of file TimelineCaptureCommandHandler.cpp.
References ITimelineDecoder::CreateEntity(), ITimelineDecoder::Entity::m_Guid, and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ITimelineDecoder::Entity entity;
     entity.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     m_TimelineDecoder.CreateEntity(entity);
 }
ReadEvent()
void ReadEvent (const unsigned char * data, uint32_t & offset)
Definition at line 113 of file TimelineCaptureCommandHandler.cpp.
References ITimelineDecoder::CreateEvent(), ITimelineDecoder::Event::m_TimeStamp, armnn::profiling::ReadUint32(), and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ITimelineDecoder::Event event;
     event.m_TimeStamp = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     if ( m_ThreadIdSize == 4 )
     {
         event.m_ThreadId = profiling::ReadUint32(data, offset);
     }
     else if ( m_ThreadIdSize == 8 )
     {
         event.m_ThreadId = profiling::ReadUint64(data, offset);
     }
     offset += m_ThreadIdSize;
     event.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     m_TimelineDecoder.CreateEvent(event);
 }
ReadEventClass()
void ReadEventClass (const unsigned char * data, uint32_t & offset)
Definition at line 87 of file TimelineCaptureCommandHandler.cpp.
References ITimelineDecoder::CreateEventClass(), ITimelineDecoder::EventClass::m_Guid, and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ITimelineDecoder::EventClass eventClass;
     eventClass.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     m_TimelineDecoder.CreateEventClass(eventClass);
 }
ReadLabel()
void ReadLabel (const unsigned char * data, uint32_t & offset)
Definition at line 57 of file TimelineCaptureCommandHandler.cpp.
References ITimelineDecoder::CreateLabel(), ITimelineDecoder::Label::m_Guid, ITimelineDecoder::Label::m_Name, armnn::profiling::ReadUint32(), armnn::profiling::ReadUint64(), and armnn::profiling::ReadUint8().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ITimelineDecoder::Label label;
     label.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     uint32_t nameLength = profiling::ReadUint32(data, offset);
     offset += uint32_t_size;
     uint32_t i = 0;
     // nameLength - 1 to account for null operator \0
     for ( i = 0; i < nameLength - 1; ++i )
     {
         label.m_Name += static_cast<char>(profiling::ReadUint8(data, offset + i));
     }
     // Shift offset past nameLength
     uint32_t uint32WordAmount = (nameLength / uint32_t_size) + (nameLength % uint32_t_size != 0 ? 1 : 0);
     offset += uint32WordAmount * uint32_t_size;
     m_TimelineDecoder.CreateLabel(label);
 }
ReadRelationship()
void ReadRelationship (const unsigned char * data, uint32_t & offset)
Definition at line 95 of file TimelineCaptureCommandHandler.cpp.
References ITimelineDecoder::CreateRelationship(), ITimelineDecoder::Relationship::m_Guid, ITimelineDecoder::Relationship::m_HeadGuid, ITimelineDecoder::Relationship::m_RelationshipType, ITimelineDecoder::Relationship::m_TailGuid, armnn::profiling::ReadUint32(), and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ITimelineDecoder::Relationship relationship;
     relationship.m_RelationshipType =
         static_cast<ITimelineDecoder::RelationshipType>(profiling::ReadUint32(data, offset));
     offset += uint32_t_size;
     relationship.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     relationship.m_HeadGuid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     relationship.m_TailGuid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     m_TimelineDecoder.CreateRelationship(relationship);
 }
SetThreadIdSize()
void SetThreadIdSize (uint32_t size)
Definition at line 136 of file TimelineCaptureCommandHandler.cpp.
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     m_ThreadIdSize = size;
 }
The documentation for this class was generated from the following files:
src/timelineDecoder/TimelineCaptureCommandHandler.hpp
src/timelineDecoder/TimelineCaptureCommandHandler.cpp