ArmNN: src/armnnTestUtils/CommonTestUtils.cpp File Reference
CommonTestUtils.cpp File Reference
#include "CommonTestUtils.hpp"
#include <armnn/backends/IBackendInternal.hpp>
Functions
SubgraphView::InputSlots CreateInputsFrom (Layer *layer, std::vector< unsigned int > ignoreSlots)
SubgraphView::InputSlots CreateInputsFrom (const std::vector< Layer * > &layers, std::vector< unsigned int > ignoreSlots)
SubgraphView::OutputSlots CreateOutputsFrom (const std::vector< Layer * > &layers)
SubgraphView::SubgraphViewPtr CreateSubgraphViewFrom (SubgraphView::InputSlots &&inputs, SubgraphView::OutputSlots &&outputs, SubgraphView::Layers &&layers)
armnn::IBackendInternalUniquePtr CreateBackendObject (const armnn::BackendId &backendId)
armnn::TensorShape MakeTensorShape (unsigned int batches, unsigned int channels, unsigned int height, unsigned int width, armnn::DataLayout layout)
Function Documentation
CreateBackendObject()
armnn::IBackendInternalUniquePtr CreateBackendObject (const armnn::BackendId & backendId)
Definition at line 72 of file CommonTestUtils.cpp.
 {
     auto& backendRegistry = BackendRegistryInstance();
     auto  backendFactory  = backendRegistry.GetFactory(backendId);
     auto  backendObjPtr   = backendFactory();
     return backendObjPtr;
 }
References armnn::BackendRegistryInstance().
CreateInputsFrom() [1/2]
SubgraphView::InputSlots CreateInputsFrom (const std::vector< Layer * > & layers, std::vector< unsigned int > ignoreSlots)
Definition at line 31 of file CommonTestUtils.cpp.
 {
     SubgraphView::InputSlots result;
     for (auto&& layer: layers)
     {
         for (auto&& it = layer->BeginInputSlots(); it != layer->EndInputSlots(); ++it)
         {
             if (std::find(ignoreSlots.begin(), ignoreSlots.end(), it->GetSlotIndex()) != ignoreSlots.end())
             {
                 continue;
             }
             else
             {
                 result.push_back(&(*it));
             }
         }
     }
     return result;
 }
CreateInputsFrom() [2/2]
SubgraphView::InputSlots CreateInputsFrom (Layer * layer, std::vector< unsigned int > ignoreSlots)
Definition at line 12 of file CommonTestUtils.cpp.
 {
     SubgraphView::InputSlots result;
     for (auto&& it = layer->BeginInputSlots(); it != layer->EndInputSlots(); ++it)
     {
         if (std::find(ignoreSlots.begin(), ignoreSlots.end(), it->GetSlotIndex()) != ignoreSlots.end())
         {
             continue;
         }
         else
         {
             result.push_back(&(*it));
         }
     }
         return result;
 }
References Layer::BeginInputSlots(), and Layer::EndInputSlots().
CreateOutputsFrom()
SubgraphView::OutputSlots CreateOutputsFrom (const std::vector< Layer * > & layers)
Definition at line 52 of file CommonTestUtils.cpp.
 {
     SubgraphView::OutputSlots result;
     for (auto && layer : layers)
     {
         for (auto&& it = layer->BeginOutputSlots(); it != layer->EndOutputSlots(); ++it)
         {
             result.push_back(&(*it));
         }
     }
     return result;
 }
CreateSubgraphViewFrom()
SubgraphView::SubgraphViewPtr CreateSubgraphViewFrom (SubgraphView::InputSlots && inputs, SubgraphView::OutputSlots && outputs, SubgraphView::Layers && layers)
Definition at line 65 of file CommonTestUtils.cpp.
 {
     return std::make_unique<SubgraphView>(std::move(inputs), std::move(outputs), std::move(layers));
 }
MakeTensorShape()
armnn::TensorShape MakeTensorShape (unsigned int batches, unsigned int channels, unsigned int height, unsigned int width, armnn::DataLayout layout)
Definition at line 81 of file CommonTestUtils.cpp.
 {
     using namespace armnn;
     switch (layout)
     {
         case DataLayout::NCHW:
             return TensorShape{ batches, channels, height, width };
         case DataLayout::NHWC:
             return TensorShape{ batches, height, width, channels };
         default:
             throw InvalidArgumentException(std::string("Unsupported data layout: ") + GetDataLayoutName(layout));
     }
 }
References armnn::GetDataLayoutName(), armnn::NCHW, and armnn::NHWC.