ArmNN: BackendRegistry Class Reference
BackendRegistry Class Reference
#include <BackendRegistry.hpp>
Classes
struct StaticRegistryInitializer
Public Types
using PointerType = IBackendInternalUniquePtr
using FactoryFunction = std::function< PointerType()>
Public Member Functions
void Register (const BackendId &id, FactoryFunction factory)
bool IsBackendRegistered (const BackendId &id) const
FactoryFunction GetFactory (const BackendId &id) const
size_t Size () const
BackendIdSet GetBackendIds () const
std::string GetBackendIdsAsString () const
void SetProfilingService (armnn::Optional< arm::pipe::IProfilingService & > profilingService)
void RegisterAllocator (const BackendId &id, std::shared_ptr< ICustomAllocator > alloc)
std::unordered_map< BackendId, std::shared_ptr< ICustomAllocator > > GetAllocators ()
void RegisterMemoryOptimizerStrategy (const BackendId &id, std::shared_ptr< IMemoryOptimizerStrategy > strategy)
MemoryOptimizerStrategiesMapRef GetMemoryOptimizerStrategies ()
BackendRegistry ()
virtual ~BackendRegistry ()
void Deregister (const BackendId &id)
void DeregisterAllocator (const BackendId &id)
void DeregisterMemoryOptimizerStrategy (const BackendId &id)
Protected Types
using FactoryStorage = std::unordered_map< BackendId, FactoryFunction >
Static Protected Member Functions
static void Swap (BackendRegistry &instance, FactoryStorage &other)
For testing only.
Detailed Description
Definition at line 35 of file BackendRegistry.hpp.
Member Typedef Documentation
FactoryFunction
using FactoryFunction = std::function<PointerType()>
Definition at line 39 of file BackendRegistry.hpp.
FactoryStorage
using FactoryStorage = std::unordered_map<BackendId, FactoryFunction> protected
Definition at line 71 of file BackendRegistry.hpp.
PointerType
using PointerType = IBackendInternalUniquePtr
Definition at line 38 of file BackendRegistry.hpp.
Constructor & Destructor Documentation
BackendRegistry()
BackendRegistry () inline
Definition at line 53 of file BackendRegistry.hpp.
 {}
~BackendRegistry()
virtual ~BackendRegistry () inline virtual
Definition at line 54 of file BackendRegistry.hpp.
 {}
Member Function Documentation
Deregister()
void Deregister (const BackendId & id)
Definition at line 41 of file BackendRegistry.cpp.
 {
     m_Factories.erase(id);
     DeregisterAllocator(id);
     if (m_ProfilingService.has_value() && m_ProfilingService.value().IsProfilingEnabled())
     {
         m_ProfilingService.value().IncrementCounterValue(arm::pipe::UNREGISTERED_BACKENDS);
     }
 }
References BackendRegistry::DeregisterAllocator(), OptionalBase::has_value(), and OptionalReferenceSwitch< IsReference, T >::value().
Referenced by DynamicBackendUtils::DeregisterDynamicBackends().
DeregisterAllocator()
void DeregisterAllocator (const BackendId & id)
Definition at line 123 of file BackendRegistry.cpp.
 {
     m_CustomMemoryAllocatorMap.erase(id);
 }
Referenced by BackendRegistry::Deregister().
DeregisterMemoryOptimizerStrategy()
void DeregisterMemoryOptimizerStrategy (const BackendId & id)
Definition at line 145 of file BackendRegistry.cpp.
 {
     m_MemoryOptimizerStrategyMap.erase(id);
 }
GetAllocators()
std::unordered_map< BackendId, std::shared_ptr< ICustomAllocator > > GetAllocators ()
Definition at line 128 of file BackendRegistry.cpp.
 {
     return m_CustomMemoryAllocatorMap;
 }
GetBackendIds()
BackendIdSet GetBackendIds () const
Definition at line 75 of file BackendRegistry.cpp.
 {
     BackendIdSet result;
     for (const auto& it : m_Factories)
     {
         result.insert(it.first);
     }
     return result;
 }
Referenced by BackendRegistry::GetBackendIdsAsString().
GetBackendIdsAsString()
std::string GetBackendIdsAsString () const
Definition at line 85 of file BackendRegistry.cpp.
 {
     static const std::string delimitator = ", ";
     std::stringstream output;
     for (auto& backendId : GetBackendIds())
     {
         if (output.tellp() != std::streampos(0))
         {
             output << delimitator;
         }
         output << backendId;
     }
     return output.str();
 }
References BackendRegistry::GetBackendIds().
GetFactory()
BackendRegistry::FactoryFunction GetFactory (const BackendId & id) const
Definition at line 57 of file BackendRegistry.cpp.
 {
     auto it = m_Factories.find(id);
     if (it == m_Factories.end())
     {
         throw InvalidArgumentException(
             std::string(id) + " has no IBackend factory registered",
             CHECK_LOCATION());
     }
     return it->second;
 }
References CHECK_LOCATION.
Referenced by armnn::GetILayerSupportByBackendId(), and RuntimeImpl::RuntimeImpl().
GetMemoryOptimizerStrategies()
MemoryOptimizerStrategiesMapRef GetMemoryOptimizerStrategies ()
Definition at line 150 of file BackendRegistry.cpp.
 {
     return m_MemoryOptimizerStrategyMap;
 }
IsBackendRegistered()
bool IsBackendRegistered (const BackendId & id) const
Definition at line 52 of file BackendRegistry.cpp.
 {
     return (m_Factories.find(id) != m_Factories.end());
 }
Referenced by armnn::GetILayerSupportByBackendId(), and DynamicBackendUtils::RegisterDynamicBackendsImpl().
Register()
void Register (const BackendId & id, BackendRegistry::FactoryFunction factory)
Definition at line 21 of file BackendRegistry.cpp.
 {
     if (m_Factories.find(id) != m_Factories.end())
     {
         throw InvalidArgumentException(
             std::string(id) + " already registered as IBackend factory",
             CHECK_LOCATION());
     }
     m_Factories[id] = factory;
     if (m_ProfilingService.has_value())
     {
         if (m_ProfilingService.has_value() && m_ProfilingService.value().IsProfilingEnabled())
         {
             m_ProfilingService.value().IncrementCounterValue(arm::pipe::REGISTERED_BACKENDS);
         }
     }
 }
References CHECK_LOCATION, OptionalBase::has_value(), and OptionalReferenceSwitch< IsReference, T >::value().
Referenced by DynamicBackendUtils::RegisterDynamicBackendsImpl(), and BackendRegistry::StaticRegistryInitializer::StaticRegistryInitializer().
RegisterAllocator()
void RegisterAllocator (const BackendId & id, std::shared_ptr< ICustomAllocator > alloc)
Definition at line 112 of file BackendRegistry.cpp.
 {
     if (m_CustomMemoryAllocatorMap.find(id) != m_CustomMemoryAllocatorMap.end())
     {
         throw InvalidArgumentException(
             std::string(id) + " already has an allocator associated with it",
             CHECK_LOCATION());
     }
     m_CustomMemoryAllocatorMap[id] = alloc;
 }
References CHECK_LOCATION.
Referenced by RuntimeImpl::RuntimeImpl().
RegisterMemoryOptimizerStrategy()
void RegisterMemoryOptimizerStrategy (const BackendId & id, std::shared_ptr< IMemoryOptimizerStrategy > strategy)
Definition at line 133 of file BackendRegistry.cpp.
 {
     if (m_MemoryOptimizerStrategyMap.find(id) != m_MemoryOptimizerStrategyMap.end())
     {
         throw InvalidArgumentException(
             std::string(id) + " already has an memory optimizer strategy associated with it",
             CHECK_LOCATION());
     }
     m_MemoryOptimizerStrategyMap[id] = strategy;
 }
References CHECK_LOCATION.
Referenced by RuntimeImpl::RuntimeImpl().
SetProfilingService()
void SetProfilingService (armnn::Optional< arm::pipe::IProfilingService & > profilingService)
Definition at line 107 of file BackendRegistry.cpp.
 {
     m_ProfilingService = profilingService;
 }
Referenced by RuntimeImpl::~RuntimeImpl().
Size()
size_t Size () const
Definition at line 70 of file BackendRegistry.cpp.
 {
     return m_Factories.size();
 }
Swap()
void Swap (BackendRegistry & instance, BackendRegistry::FactoryStorage & other) static protected
For testing only.
Definition at line 102 of file BackendRegistry.cpp.
 {
     std::swap(instance.m_Factories, other);
 }
References armnn::swap().
The documentation for this class was generated from the following files:
include/armnn/BackendRegistry.hpp
src/armnn/BackendRegistry.cpp