ArmNN: ClConstantWorkload Class Reference
ClConstantWorkload Class Reference
#include <ClConstantWorkload.hpp>
Public Member Functions
ClConstantWorkload (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
void Execute () const override
Public Member Functions inherited from ClBaseWorkload< ConstantQueueDescriptor >
ClBaseWorkload (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< ConstantQueueDescriptor >
BaseWorkload (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const ConstantQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual arm::pipe::ProfilingGuid GetGuid () const =0
virtual bool SupportsTensorHandleReplacement () const =0
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< ConstantQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< ConstantQueueDescriptor >
ConstantQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 17 of file ClConstantWorkload.hpp.
Constructor & Destructor Documentation
ClConstantWorkload()
ClConstantWorkload (const ConstantQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 44 of file ClConstantWorkload.cpp.
     : ClBaseWorkload<ConstantQueueDescriptor>(descriptor, info)
     , m_RanOnce(false)
 {
 }
References armnn::info.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 52 of file ClConstantWorkload.cpp.
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClConstantWorkload_Execute", this->GetGuid());
     // The intermediate tensor held by the corresponding layer output handler can be initialised with the given data
     // on the first inference, then reused for subsequent inferences.
     // The initialisation cannot happen at workload construction time since the ACL kernel for the next layer may not
     // have been configured at the time.
     if (!m_RanOnce)
     {
         const ConstantQueueDescriptor& data = this->m_Data;
         ARMNN_ASSERT(data.m_LayerOutput != nullptr);
         arm_compute::CLTensor& output = static_cast<ClTensorHandle*>(data.m_Outputs[0])->GetTensor();
         arm_compute::DataType computeDataType = static_cast<ClTensorHandle*>(data.m_Outputs[0])->GetDataType();
         switch (computeDataType)
         {
             case arm_compute::DataType::F16:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<Half>());
                 break;
             }
             case arm_compute::DataType::F32:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<float>());
                 break;
             }
             case arm_compute::DataType::QASYMM8:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<uint8_t>());
                 break;
             }
             case arm_compute::DataType::QASYMM8_SIGNED:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<int8_t>());
                 break;
             }
             case arm_compute::DataType::QSYMM16:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<int16_t>());
                 break;
             }
             case arm_compute::DataType::QSYMM8:
             case arm_compute::DataType::QSYMM8_PER_CHANNEL:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<int8_t>());
                 break;
             }
             case arm_compute::DataType::S32:
             {
                 CopyArmComputeClTensorData(output, data.m_LayerOutput->GetConstTensor<int32_t>());
                 break;
             }
             default:
             {
                 ARMNN_ASSERT_MSG(false, "Unknown data type");
                 break;
             }
         }
         m_RanOnce = true;
     }
 }
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, armnn::CopyArmComputeClTensorData(), ConstTensorHandle::GetConstTensor(), BaseWorkload< ConstantQueueDescriptor >::GetGuid(), BaseWorkload< ConstantQueueDescriptor >::m_Data, ConstantQueueDescriptor::m_LayerOutput, and QueueDescriptor::m_Outputs.
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClConstantWorkload.hpp
src/backends/cl/workloads/ClConstantWorkload.cpp