ArmNN: QuantizeLayer Class Reference
QuantizeLayer Class Reference
#include <QuantizeLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Layer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id) override
Set the backend of the IConnectableLayer.
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
Infer the shape of the output(s) based on the provided input shape(s)
virtual void SerializeLayerParameters (ParameterStringifyFunction &fn) const
Helper to serialize the layer parameters to string.
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer * >::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T >
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
virtual const BaseDescriptor & GetParameters () const override
If the layer has a descriptor return it.
Protected Member Functions
QuantizeLayer (const char *name)
~QuantizeLayer ()=default
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *Layer::CreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef () override final
virtual ImmutableConstantTensors GetConstantTensorsByRef () const override
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector< std::reference_wrapper< std::shared_ptr< ConstTensorHandle > >>
using ImmutableConstantTensors = std::vector< std::reference_wrapper< const std::shared_ptr< ConstTensorHandle > >>
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
Definition at line 16 of file QuantizeLayer.hpp.
Constructor & Destructor Documentation
QuantizeLayer()
QuantizeLayer (const char * name) protected
Definition at line 13 of file QuantizeLayer.cpp.
 : Layer(1, 1, LayerType::Quantize, name)
 {}
~QuantizeLayer()
~QuantizeLayer () protected default
Member Function Documentation
Clone()
Layer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
graph - The Graph into which this Layer is being cloned.
Implements Layer.
Definition at line 27 of file QuantizeLayer.cpp.
 {
     QuantizeLayer* clone = CloneBase<QuantizeLayer>(graph, GetName());
     return clone;
 }
References Layer::GetName().
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Implements Layer.
Definition at line 17 of file QuantizeLayer.cpp.
 {
     QuantizeQueueDescriptor descriptor;
     SetAdditionalInfo(descriptor);
     WorkloadInfo info = PrepInfoAndDesc(descriptor);
     return factory.CreateWorkload(LayerType::Quantize, descriptor, info);
 }
References IWorkloadFactory::CreateWorkload(), armnn::info, Layer::PrepInfoAndDesc(), armnn::Quantize, and Layer::SetAdditionalInfo().
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Reimplemented from Layer.
Definition at line 46 of file QuantizeLayer.cpp.
 {
     strategy.ExecuteStrategy(this, GetParameters(), {}, GetName());
 }
References IStrategy::ExecuteStrategy(), Layer::GetName(), and Layer::GetParameters().
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Implements Layer.
Definition at line 33 of file QuantizeLayer.cpp.
 {
     VerifyLayerConnections(1, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     auto inferredShapes = InferOutputShapes({ GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape() });
     ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "QuantizeLayer");
 }
References CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), Layer::InferOutputShapes(), Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
The documentation for this class was generated from the following files:
src/armnn/layers/QuantizeLayer.hpp
src/armnn/layers/QuantizeLayer.cpp