ArmNN: NeonLayerSupport Class Reference
NeonLayerSupport Class Reference
#include <NeonLayerSupport.hpp>
Public Member Functions
NeonLayerSupport (const IBackendInternal::IBackendSpecificModelContextPtr &modelContextPtr)
NeonLayerSupport ()
~NeonLayerSupport ()
bool IsLayerSupported (const LayerType &type, const std::vector< TensorInfo > &infos, const BaseDescriptor &descriptor, const Optional< LstmInputParamsInfo > &lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > &quantizedLstmParamsInfo, Optional< std::string & > reasonIfUnsupported) const override
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchMatMulSupported (const TensorInfo &inputX, const TensorInfo &inputY, const TensorInfo &output, const BatchMatMulDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const ComparisonDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo * > inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reason=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFillSupported (const TensorInfo &input, const TensorInfo &output, const FillDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherNdSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported) const
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizedLstmSupported (const TensorInfo &input, const TensorInfo &cellStateIn, const TensorInfo &outputStateIn, const TensorInfo &cellStateOut, const TensorInfo &outputStateOut, const QuantizedLstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo * > &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const UnidirectionalSequenceLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported) const override
Public Member Functions inherited from LayerSupportBase
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const ComparisonDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo * > inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDebugSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDetectionPostProcessSupported (const TensorInfo &boxEncodings, const TensorInfo &scores, const TensorInfo &anchors, const TensorInfo &detectionBoxes, const TensorInfo &detectionClasses, const TensorInfo &detectionScores, const TensorInfo &numDetections, const DetectionPostProcessDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFakeQuantizationSupported (const TensorInfo &input, const FakeQuantizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMemCopySupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMemImportSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMergeSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPreCompiledSupported (const TensorInfo &input, const PreCompiledDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizedLstmSupported (const TensorInfo &input, const TensorInfo &previousCellStateIn, const TensorInfo &previousOutputIn, const TensorInfo &cellStateOut, const TensorInfo &output, const QuantizedLstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsRankSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsShapeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo * > &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStandInSupported (const std::vector< const TensorInfo * > &inputs, const std::vector< const TensorInfo * > &outputs, const StandInDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSwitchSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output0, const TensorInfo &output1, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
Public Member Functions inherited from ILayerSupport
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsActivationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsAdditionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsArgMinMaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchToSpaceNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsCastSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsChannelShuffleSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsComparisonSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp32ToFp16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDebugSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthToSpaceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDequantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDetectionPostProcessSupported(const TensorInfo &boxEncodings
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDilatedDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDivisionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsElementwiseUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFakeQuantizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFillSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFloorSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFullyConnectedSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsGatherSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInputSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInstanceNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsL2NormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalBinarySupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMaximumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMeanSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemCopySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemImportSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMergeSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMinimumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMultiplicationSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsOutputSupported(const TensorInfo &output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPadSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPermuteSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreCompiledSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreluSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizedLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsRankSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReduceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReshapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsResizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsShapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSliceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToBatchNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToDepthSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSplitterSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSubtractionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSwitchSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsUnidirectionalSequenceLstmSupported(const TensorInfo &input
Additional Inherited Members
Public Attributes inherited from ILayerSupport
const TensorInfo & output
const TensorInfo const ActivationDescriptor & descriptor
const TensorInfo const ActivationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & input1
const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ArgMinMaxDescriptor & descriptor
const TensorInfo const ArgMinMaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & mean
const TensorInfo const TensorInfo const TensorInfo & var
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & beta
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & gamma
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const BatchToSpaceNdDescriptor & descriptor
const TensorInfo const BatchToSpaceNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ChannelShuffleDescriptor & descriptor
const TensorInfo const ChannelShuffleDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const ComparisonDescriptor & descriptor
const TensorInfo const TensorInfo const ComparisonDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConcatSupported(const std Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution2dDescriptor & descriptor
const TensorInfo const Convolution2dDescriptor const TensorInfo & weights
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution3dDescriptor & descriptor
const TensorInfo const Convolution3dDescriptor const TensorInfo & weights
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthToSpaceDescriptor & descriptor
const TensorInfo const DepthToSpaceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthwiseConvolution2dDescriptor & descriptor
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & scores
const TensorInfo const TensorInfo & anchors
const TensorInfo const TensorInfo const TensorInfo & detectionBoxes
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionClasses
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionScores
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & numDetections
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ElementwiseUnaryDescriptor & descriptor
const TensorInfo const ElementwiseUnaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const FakeQuantizationDescriptor & descriptor
const FakeQuantizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const FillDescriptor & descriptor
const TensorInfo const FillDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & weights
const TensorInfo const TensorInfo const TensorInfo & biases
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const GatherDescriptor & descriptor
const TensorInfo const TensorInfo const GatherDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const InstanceNormalizationDescriptor & descriptor
const TensorInfo const InstanceNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const L2NormalizationDescriptor & descriptor
const TensorInfo const L2NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const LogicalBinaryDescriptor & descriptor
const TensorInfo const TensorInfo const LogicalBinaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const LogSoftmaxDescriptor & descriptor
const TensorInfo const LogSoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & outputStateIn
const TensorInfo const TensorInfo & cellStateIn
const TensorInfo const TensorInfo const TensorInfo & scratchBuffer
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const MeanDescriptor & descriptor
const TensorInfo const MeanDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & ouput
const TensorInfo const NormalizationDescriptor & descriptor
const TensorInfo const NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PadDescriptor & descriptor
const TensorInfo const PadDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PermuteDescriptor & descriptor
const TensorInfo const PermuteDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling2dDescriptor & descriptor
const TensorInfo const Pooling2dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling3dDescriptor & descriptor
const TensorInfo const Pooling3dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const PreCompiledDescriptor & descriptor
const PreCompiledDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & alpha
const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReduceDescriptor & descriptor
const TensorInfo const ReduceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReshapeDescriptor & descriptor
const TensorInfo const ReshapeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ResizeDescriptor & descriptor
const TensorInfo const ResizeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SliceDescriptor & descriptor
const TensorInfo const SliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SoftmaxDescriptor & descriptor
const TensorInfo const SoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToBatchNdDescriptor & descriptor
const TensorInfo const SpaceToBatchNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToDepthDescriptor & descriptor
const TensorInfo const SpaceToDepthDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const std::vector< std::reference_wrapper< TensorInfo > > & outputs
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor & descriptor
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo & output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor & descriptor
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & output0
const TensorInfo const TensorInfo const TensorInfo & output1
const TensorInfo const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeConvolution2dDescriptor & descriptor
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeDescriptor & descriptor
const TensorInfo const TransposeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Protected Member Functions inherited from ILayerSupport
ILayerSupport ()
virtual ~ILayerSupport ()
Detailed Description
Definition at line 14 of file NeonLayerSupport.hpp.
Constructor & Destructor Documentation
NeonLayerSupport() [1/2]
NeonLayerSupport (const IBackendInternal::IBackendSpecificModelContextPtr & modelContextPtr) explicit
Definition at line 159 of file NeonLayerSupport.cpp.
     : m_ModelContextPtr(modelContextPtr)
 {
 }
NeonLayerSupport() [2/2]
NeonLayerSupport ()
Definition at line 164 of file NeonLayerSupport.cpp.
     : m_ModelContextPtr(nullptr)
 {
 }
~NeonLayerSupport()
~NeonLayerSupport () inline
Definition at line 20 of file NeonLayerSupport.hpp.
 {}
Member Function Documentation
IsActivationSupported()
bool IsActivationSupported (const TensorInfo & input, const TensorInfo & output, const ActivationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 719 of file NeonLayerSupport.cpp.
 {
     IgnoreUnused(descriptor);
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonActivationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::IgnoreUnused(), armnn::NeonActivationWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsAdditionSupported()
bool IsAdditionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 732 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonAdditionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonAdditionWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsArgMinMaxSupported()
bool IsArgMinMaxSupported (const TensorInfo & input, const TensorInfo & output, const ArgMinMaxDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 745 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonArgMinMaxWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonArgMinMaxWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsBatchMatMulSupported()
bool IsBatchMatMulSupported (const TensorInfo & inputX, const TensorInfo & inputY, const TensorInfo & output, const BatchMatMulDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Definition at line 757 of file NeonLayerSupport.cpp.
 {
     bool isFastMathEnabled = false;
 #if defined(ARMCOMPUTENEON_ENABLED)
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<NeonBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
 #endif
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonBatchMatMulValidate,
                                    reasonIfUnsupported,
                                    inputX,
                                    inputY,
                                    output,
                                    descriptor,
                                    isFastMathEnabled,
                                    nullptr);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, NeonBackendModelContext::IsFastMathEnabled(), armnn::NeonBatchMatMulValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsBatchNormalizationSupported()
bool IsBatchNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & mean, const TensorInfo & var, const TensorInfo & beta, const TensorInfo & gamma, const BatchNormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 787 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonBatchNormalizationValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    mean,
                                    var,
                                    beta,
                                    gamma,
                                    descriptor,
                                    nullptr);
 }
References ILayerSupport::beta, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::gamma, ILayerSupport::mean, armnn::NeonBatchNormalizationValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::var.
Referenced by armnn::IsLayerTypeSupported().
IsBatchToSpaceNdSupported()
bool IsBatchToSpaceNdSupported (const TensorInfo & input, const TensorInfo & output, const BatchToSpaceNdDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 808 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonBatchToSpaceNdWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonBatchToSpaceNdWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsCastSupported()
bool IsCastSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 820 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonCastValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonCastValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsChannelShuffleSupported()
bool IsChannelShuffleSupported (const TensorInfo & input, const TensorInfo & output, const ChannelShuffleDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 830 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonChannelShuffleValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonChannelShuffleValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsComparisonSupported()
bool IsComparisonSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const ComparisonDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 842 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonComparisonWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonComparisonWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsConcatSupported()
bool IsConcatSupported (const std::vector< const TensorInfo * > inputs, const TensorInfo & output, const OriginsDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 857 of file NeonLayerSupport.cpp.
 {
     if (descriptor.GetNumDimensions() <= descriptor.GetConcatAxis())
     {
         SetValueChecked(reasonIfUnsupported, "Neon Concat: Concat axis > Number of dimensions.");
         return false;
     }
     unsigned int concatInnerAxis = (descriptor.GetNumDimensions() - descriptor.GetConcatAxis()) - 1;
     if(concatInnerAxis < 3) // Width, height, or channels
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(NeonConcatWorkloadValidate,
                                        reasonIfUnsupported,
                                        inputs,
                                        output,
                                        descriptor);
     }
     else if (concatInnerAxis == 3)
     {
         for (auto& input : inputs)
         {
             if (input && !output.IsTypeSpaceMatch(*input)) // Cannot use sub-tensors if the types are not same space
             {
                 SetValueChecked(reasonIfUnsupported, "Neon Concat: Types and quantization parameters must match.");
                 return false;
             }
         }
         return true; // Sub-tensors support concat along batch
     }
     else // > 4 dimensions not supported.
     {
         SetValueChecked(reasonIfUnsupported, "Neon Concat: Maximum of 4 dimensions supported.");
         return false;
     }
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetNumDimensions(), TensorInfo::IsTypeSpaceMatch(), armnn::NeonConcatWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and armnn::SetValueChecked().
Referenced by armnn::IsLayerTypeSupported().
IsConstantSupported()
bool IsConstantSupported (const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 896 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonConstantWorkloadValidate,
                                    reasonIfUnsupported,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonConstantWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsConvertFp16ToFp32Supported()
bool IsConvertFp16ToFp32Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 904 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonConvertFp16ToFp32WorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonConvertFp16ToFp32WorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsConvertFp32ToFp16Supported()
bool IsConvertFp32ToFp16Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 914 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonConvertFp32ToFp16WorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonConvertFp32ToFp16WorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsConvolution2dSupported()
bool IsConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 924 of file NeonLayerSupport.cpp.
 {
     bool isFastMathEnabled = false;
 #if defined(ARMCOMPUTENEON_ENABLED)
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<NeonBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
 #endif
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonConvolution2dWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    isFastMathEnabled,
                                    nullptr);
 }
References ILayerSupport::biases, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, NeonBackendModelContext::IsFastMathEnabled(), armnn::NeonConvolution2dWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by armnn::IsLayerTypeSupported().
IsConvolution3dSupported()
bool IsConvolution3dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution3dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 957 of file NeonLayerSupport.cpp.
 {
     bool isFastMathEnabled = false;
 #if defined(ARMCOMPUTENEON_ENABLED)
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<NeonBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
 #endif
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonConvolution3dWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    isFastMathEnabled,
                                    nullptr);
 }
References ILayerSupport::biases, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, NeonBackendModelContext::IsFastMathEnabled(), armnn::NeonConvolution3dWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by armnn::IsLayerTypeSupported().
IsDepthToSpaceSupported()
bool IsDepthToSpaceSupported (const TensorInfo & input, const TensorInfo & output, const DepthToSpaceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 990 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonDepthToSpaceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonDepthToSpaceWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsDepthwiseConvolutionSupported()
bool IsDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1002 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonDepthwiseConvolutionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    nullptr);
 }
References ILayerSupport::biases, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonDepthwiseConvolutionWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by armnn::IsLayerTypeSupported().
IsDequantizeSupported()
bool IsDequantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1019 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonDequantizeWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonDequantizeWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsDilatedDepthwiseConvolutionSupported()
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reason = EmptyOptional()) const override
Definition at line 1029 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonDepthwiseConvolutionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    nullptr);
 }
References ILayerSupport::biases, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonDepthwiseConvolutionWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
IsDivisionSupported()
bool IsDivisionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1300 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonDivisionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonDivisionWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsElementwiseUnarySupported()
bool IsElementwiseUnarySupported (const TensorInfo & input, const TensorInfo & output, const ElementwiseUnaryDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1046 of file NeonLayerSupport.cpp.
 {
     switch(descriptor.m_Operation)
     {
         case UnaryOperation::Abs:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonAbsWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Exp:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonExpWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::LogicalNot:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonLogicalNotWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
        case UnaryOperation::Log:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonLogWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Neg:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonNegWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Rsqrt:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonRsqrtWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Sin:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSinWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Sqrt:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSqrtWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         default:
             return false;
     }
 }
References armnn::Abs, ILayerSupport::descriptor, armnn::Exp, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::Log, armnn::LogicalNot, armnn::Neg, armnn::NeonAbsWorkloadValidate(), armnn::NeonExpWorkloadValidate(), armnn::NeonLogicalNotWorkloadValidate(), armnn::NeonLogWorkloadValidate(), armnn::NeonNegWorkloadValidate(), armnn::NeonRsqrtWorkloadValidate(), armnn::NeonSinWorkloadValidate(), armnn::NeonSqrtWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, armnn::Rsqrt, armnn::Sin, and armnn::Sqrt.
Referenced by armnn::IsLayerTypeSupported().
IsFillSupported()
bool IsFillSupported (const TensorInfo & input, const TensorInfo & output, const FillDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override virtual
Reimplemented from LayerSupportBase.
Definition at line 1098 of file NeonLayerSupport.cpp.
 {
     armnn::IgnoreUnused(input);
     armnn::IgnoreUnused(output);
     armnn::IgnoreUnused(descriptor);
     return IsNeonBackendSupported(reasonIfUnsupported);
 }
References ILayerSupport::descriptor, armnn::IgnoreUnused(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsFloorSupported()
bool IsFloorSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1110 of file NeonLayerSupport.cpp.
 {
     armnn::IgnoreUnused(output);
     return IsNeonBackendSupported(reasonIfUnsupported) &&
            IsSupportedForDataTypeGeneric(reasonIfUnsupported,
                                          input.GetDataType(),
                                          &FalseFuncF16<>,
                                          &TrueFunc<>,
                                          &FalseFuncU8<>,
                                          &FalseFuncI32<>,
                                          &FalseFuncU8<>);
 }
References TensorInfo::GetDataType(), armnn::IgnoreUnused(), armnn::IsSupportedForDataTypeGeneric(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsFullyConnectedSupported()
bool IsFullyConnectedSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & weights, const TensorInfo & biases, const FullyConnectedDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1125 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonFullyConnectedWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    weights,
                                    biases,
                                    descriptor,
                                    nullptr);
 }
References ILayerSupport::biases, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonFullyConnectedWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by armnn::IsLayerTypeSupported().
IsGatherNdSupported()
bool IsGatherNdSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported) const
Definition at line 1156 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonGatherNdWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonGatherNdWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsGatherSupported()
bool IsGatherSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const GatherDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported) const override
Definition at line 1142 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonGatherWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonGatherWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsInputSupported()
bool IsInputSupported (const TensorInfo & input, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1168 of file NeonLayerSupport.cpp.
 {
     return IsNeonBackendSupported(reasonIfUnsupported, input);
 }
References ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsInstanceNormalizationSupported()
bool IsInstanceNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const InstanceNormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1174 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonInstanceNormalizationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonInstanceNormalizationWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsL2NormalizationSupported()
bool IsL2NormalizationSupported (const TensorInfo & input, const TensorInfo & output, const L2NormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1186 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonL2NormalizationWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonL2NormalizationWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsLayerSupported()
bool IsLayerSupported (const LayerType & type, const std::vector< TensorInfo > & infos, const BaseDescriptor & descriptor, const Optional< LstmInputParamsInfo > & lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > & quantizedLstmParamsInfo, Optional< std::string & > reasonIfUnsupported) const override virtual
Reimplemented from LayerSupportBase.
Definition at line 671 of file NeonLayerSupport.cpp.
 {
     bool isSupported = IsLayerTypeSupported(type,
                                             infos,
                                             descriptor,
                                             lstmParamsInfo,
                                             quantizedLstmParamsInfo,
                                             reasonIfUnsupported,
                                             *this);
     // For android-nn-driver and support library, to run FP16 operations on CpuAcc we need at least v8.2
     // architecture. If the available architecture is older than v8.2, we can check if the operator is
     // supported by changing operator inputs & outputs to be FP32.
     // This does not change the operator datatype in the above parsers to be FP32. We are simply reporting
     // to the parsers if the operator can supported in ArmNN. We will then re-enter ArmNN (Network.cpp)
     // where we will recheck IsLayerSupported() on the FP16 datatype, update the operator to be FP32,
     // and, insert convert layers around the FP32 operator.
     if (reasonIfUnsupported.has_value())
     {
         std::string checkStr = "This CPU architecture does not support F16 data type, you need v8.2 or above";
         if (!isSupported
             && reasonIfUnsupported.value().find(checkStr) != std::string::npos)
         {
             std::vector<TensorInfo> newInfos;
             for (auto               info: infos)
             {
                 newInfos.emplace_back(OverrideDataType(info, DataType::Float32));
             }
             std::string tmpString;
             return IsLayerTypeSupported(type,
                                         newInfos,
                                         descriptor,
                                         lstmParamsInfo,
                                         quantizedLstmParamsInfo,
                                         tmpString,
                                         *this);
         }
     }
     return isSupported;
 }
References ILayerSupport::descriptor, armnn::Float32, armnn::info, armnn::IsLayerTypeSupported(), and ILayerSupport::reasonIfUnsupported.
IsLogicalBinarySupported()
bool IsLogicalBinarySupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const LogicalBinaryDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported) const override
Definition at line 1194 of file NeonLayerSupport.cpp.
 {
     switch(descriptor.m_Operation)
     {
         case LogicalBinaryOperation::LogicalAnd:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonLogicalAndWorkloadValidate,
                                            reasonIfUnsupported,
                                            input0,
                                            input1,
                                            output);
         case LogicalBinaryOperation::LogicalOr:
             FORWARD_WORKLOAD_VALIDATE_FUNC(NeonLogicalOrWorkloadValidate,
                                            reasonIfUnsupported,
                                            input0,
                                            input1,
                                            output);
         default:
             return false;
     }
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::LogicalAnd, armnn::LogicalOr, armnn::NeonLogicalAndWorkloadValidate(), armnn::NeonLogicalOrWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsLogSoftmaxSupported()
bool IsLogSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const LogSoftmaxDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1219 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonLogSoftmaxWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonLogSoftmaxWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsLstmSupported()
bool IsLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & scratchBuffer, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const LstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1227 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonLstmFloatWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    outputStateIn,
                                    cellStateIn,
                                    scratchBuffer,
                                    outputStateOut,
                                    cellStateOut,
                                    output,
                                    descriptor,
                                    paramsInfo);
 }
References ILayerSupport::cellStateIn, ILayerSupport::cellStateOut, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonLstmFloatWorkloadValidate(), ILayerSupport::output, ILayerSupport::outputStateIn, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, ILayerSupport::reasonIfUnsupported, and ILayerSupport::scratchBuffer.
Referenced by armnn::IsLayerTypeSupported().
IsMaximumSupported()
bool IsMaximumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1251 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonMaximumWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonMaximumWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsMeanSupported()
bool IsMeanSupported (const TensorInfo & input, const TensorInfo & output, const MeanDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1263 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonMeanWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonMeanWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsMinimumSupported()
bool IsMinimumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1275 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonMinimumWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonMinimumWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsMultiplicationSupported()
bool IsMultiplicationSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1287 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonMultiplicationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonMultiplicationWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsNormalizationSupported()
bool IsNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const NormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1313 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonNormalizationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonNormalizationWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsOutputSupported()
bool IsOutputSupported (const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1325 of file NeonLayerSupport.cpp.
 {
     return IsNeonBackendSupported(reasonIfUnsupported, output);
 }
References ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsPadSupported()
bool IsPadSupported (const TensorInfo & input, const TensorInfo & output, const PadDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1331 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonPadWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonPadWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsPermuteSupported()
bool IsPermuteSupported (const TensorInfo & input, const TensorInfo & output, const PermuteDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1343 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonPermuteWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonPermuteWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsPooling2dSupported()
bool IsPooling2dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling2dDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1351 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonPooling2dWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonPooling2dWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsPooling3dSupported()
bool IsPooling3dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling3dDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1359 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonPooling3dWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonPooling3dWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsPreluSupported()
bool IsPreluSupported (const TensorInfo & input, const TensorInfo & alpha, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1367 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonPreluWorkloadValidate, reasonIfUnsupported, input, alpha, output);
 }
References ILayerSupport::alpha, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonPreluWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsQLstmSupported()
bool IsQLstmSupported (const TensorInfo & input, const TensorInfo & previousOutputIn, const TensorInfo & previousCellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const QLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1375 of file NeonLayerSupport.cpp.
 {
     // Check required here in order to pass IsLayerSupported for datatypes tests
     if (input.GetDataType()               == armnn::DataType::QAsymmS8 &&
         previousOutputIn.GetDataType()    == armnn::DataType::QAsymmS8 &&
         previousCellStateIn.GetDataType() == armnn::DataType::QSymmS16 &&
         outputStateOut.GetDataType()      == armnn::DataType::QAsymmS8 &&
         cellStateOut.GetDataType()        == armnn::DataType::QSymmS16 &&
         output.GetDataType()              == armnn::DataType::QAsymmS8)
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(NeonQLstmWorkloadValidate,
                                        reasonIfUnsupported,
                                        input,
                                        previousCellStateIn,
                                        previousOutputIn,
                                        cellStateOut,
                                        outputStateOut,
                                        output,
                                        descriptor,
                                        paramsInfo);
     }
     else
     {
         return false;
     }
 }
References ILayerSupport::cellStateOut, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetDataType(), armnn::NeonQLstmWorkloadValidate(), ILayerSupport::output, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, ILayerSupport::previousCellStateIn, ILayerSupport::previousOutputIn, armnn::QAsymmS8, armnn::QSymmS16, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsQuantizedLstmSupported()
bool IsQuantizedLstmSupported (const TensorInfo & input, const TensorInfo & cellStateIn, const TensorInfo & outputStateIn, const TensorInfo & cellStateOut, const TensorInfo & outputStateOut, const QuantizedLstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1420 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonQuantizedLstmWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    cellStateIn,
                                    outputStateIn,
                                    cellStateOut,
                                    outputStateOut,
                                    paramsInfo);
 }
References ILayerSupport::cellStateIn, ILayerSupport::cellStateOut, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonQuantizedLstmWorkloadValidate(), ILayerSupport::outputStateIn, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsQuantizeSupported()
bool IsQuantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1410 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonQuantizeWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonQuantizeWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsReduceSupported()
bool IsReduceSupported (const TensorInfo & input, const TensorInfo & output, const ReduceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1438 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonReduceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonReduceWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsReshapeSupported()
bool IsReshapeSupported (const TensorInfo & input, const TensorInfo & output, const ReshapeDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1450 of file NeonLayerSupport.cpp.
 {
     armnn::IgnoreUnused(descriptor);
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonReshapeWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::IgnoreUnused(), armnn::NeonReshapeWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsResizeSupported()
bool IsResizeSupported (const TensorInfo & input, const TensorInfo & output, const ResizeDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1462 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonResizeWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonResizeWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsSliceSupported()
bool IsSliceSupported (const TensorInfo & input, const TensorInfo & output, const SliceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1474 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSliceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonSliceWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsSoftmaxSupported()
bool IsSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const SoftmaxDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1486 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSoftmaxWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonSoftmaxWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsSpaceToBatchNdSupported()
bool IsSpaceToBatchNdSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToBatchNdDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1494 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSpaceToBatchNdWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonSpaceToBatchNdWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsSpaceToDepthSupported()
bool IsSpaceToDepthSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToDepthDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1506 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSpaceToDepthWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonSpaceToDepthWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsSplitterSupported()
bool IsSplitterSupported (const TensorInfo & input, const std::vector< std::reference_wrapper< TensorInfo >> & outputs, const ViewsDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1518 of file NeonLayerSupport.cpp.
 {
 #if defined(ARMCOMPUTENEON_ENABLED)
     // Split along the last dimension, cannot use sub-tensors
     // as width and height of the sub-tensors do not match
     // the width and height of the parent tensor
     // in case of input with more than 2D.
     std::set<unsigned int> splitAxis = ComputeSplitAxis(descriptor, input.GetShape());
     if (descriptor.GetNumDimensions() > 2 && splitAxis.size() == 1 &&
         *splitAxis.begin() == descriptor.GetNumDimensions() - 1 )
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSplitterWorkloadValidate,
                                        reasonIfUnsupported,
                                        input,
                                        outputs,
                                        *splitAxis.begin());
     }
 #endif
     IgnoreUnused(descriptor);
     for (auto output : outputs)
     {
         if (!input.IsTypeSpaceMatch(output)) // Cannot use sub-tensors if the types are not same space
         {
             SetValueChecked(reasonIfUnsupported, "Neon Splitter: Types and quantization parameters must match.");
             return false;
         }
     }
     return true;
 }
References armnn::ComputeSplitAxis(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), armnn::IgnoreUnused(), TensorInfo::IsTypeSpaceMatch(), armnn::NeonSplitterWorkloadValidate(), ILayerSupport::output, ILayerSupport::outputs, ILayerSupport::reasonIfUnsupported, and armnn::SetValueChecked().
Referenced by armnn::IsLayerTypeSupported().
IsStackSupported()
bool IsStackSupported (const std::vector< const TensorInfo * > & inputs, const TensorInfo & output, const StackDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1551 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonStackWorkloadValidate,
                                    reasonIfUnsupported,
                                    inputs,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonStackWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsStridedSliceSupported()
bool IsStridedSliceSupported (const TensorInfo & input, const TensorInfo & output, const StridedSliceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1563 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonStridedSliceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonStridedSliceWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsSubtractionSupported()
bool IsSubtractionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1575 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonSubtractionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, armnn::NeonSubtractionWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsTransposeConvolution2dSupported()
bool IsTransposeConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const TransposeConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1588 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonTransposeConvolution2dWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases);
 }
References ILayerSupport::biases, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonTransposeConvolution2dWorkloadValidate(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by armnn::IsLayerTypeSupported().
IsTransposeSupported()
bool IsTransposeSupported (const TensorInfo & input, const TensorInfo & output, const TransposeDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1604 of file NeonLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(NeonTransposeWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::NeonTransposeWorkloadValidate(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
IsUnidirectionalSequenceLstmSupported()
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const UnidirectionalSequenceLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported) const override
Definition at line 1612 of file NeonLayerSupport.cpp.
 {
     if (input.GetDataType() == armnn::DataType::QAsymmS8 &&
         outputStateIn.GetDataType() == armnn::DataType::QAsymmS8 &&
         cellStateIn.GetDataType() == armnn::DataType::QSymmS16 &&
         outputStateOut.GetDataType() == armnn::DataType::QAsymmS8 &&
         cellStateOut.GetDataType() == armnn::DataType::QSymmS16 &&
         output.GetDataType() == armnn::DataType::QAsymmS8)
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(NeonUnidirectionalSequenceLstmWorkloadValidate,
                                        reasonIfUnsupported,
                                        input,
                                        outputStateIn,
                                        cellStateIn,
                                        outputStateOut,
                                        cellStateOut,
                                        output,
                                        descriptor,
                                        paramsInfo);
     }
     else
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(NeonUnidirectionalSequenceLstmFloatWorkloadValidate,
                                        reasonIfUnsupported,
                                        input,
                                        outputStateIn,
                                        cellStateIn,
                                        outputStateOut,
                                        cellStateOut,
                                        output,
                                        descriptor,
                                        paramsInfo);
     }
 }
References ILayerSupport::cellStateIn, ILayerSupport::cellStateOut, ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetDataType(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmWorkloadValidate(), ILayerSupport::output, ILayerSupport::outputStateIn, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, armnn::QAsymmS8, armnn::QSymmS16, and ILayerSupport::reasonIfUnsupported.
Referenced by armnn::IsLayerTypeSupported().
The documentation for this class was generated from the following files:
src/backends/neon/NeonLayerSupport.hpp
src/backends/neon/NeonLayerSupport.cpp