ArmNN: ClLayerSupport Class Reference
ClLayerSupport Class Reference
#include <ClLayerSupport.hpp>
Public Member Functions
ClLayerSupport (const IBackendInternal::IBackendSpecificModelContextPtr &modelContextPtr)
ClLayerSupport ()
~ClLayerSupport ()
bool IsLayerSupported (const LayerType &type, const std::vector< TensorInfo > &infos, const BaseDescriptor &descriptor, const Optional< LstmInputParamsInfo > &lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > &quantizedLstmParamsInfo, Optional< std::string & > reasonIfUnsupported) const override
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchMatMulSupported (const TensorInfo &inputX, const TensorInfo &inputY, const TensorInfo &output, const BatchMatMulDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &ouput, const ComparisonDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo * > inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reason=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFillSupported (const TensorInfo &input, const TensorInfo &output, const FillDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherNdSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported) const
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizedLstmSupported (const TensorInfo &input, const TensorInfo &previousCellStateIn, const TensorInfo &previousOutputIn, const TensorInfo &cellStateOut, const TensorInfo &output, const QuantizedLstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo * > &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const UnidirectionalSequenceLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported) const override
Public Member Functions inherited from LayerSupportBase
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const ComparisonDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo * > inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDebugSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDetectionPostProcessSupported (const TensorInfo &boxEncodings, const TensorInfo &scores, const TensorInfo &anchors, const TensorInfo &detectionBoxes, const TensorInfo &detectionClasses, const TensorInfo &detectionScores, const TensorInfo &numDetections, const DetectionPostProcessDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFakeQuantizationSupported (const TensorInfo &input, const FakeQuantizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMemCopySupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMemImportSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMergeSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPreCompiledSupported (const TensorInfo &input, const PreCompiledDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizedLstmSupported (const TensorInfo &input, const TensorInfo &previousCellStateIn, const TensorInfo &previousOutputIn, const TensorInfo &cellStateOut, const TensorInfo &output, const QuantizedLstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsRankSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsShapeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo * > &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStandInSupported (const std::vector< const TensorInfo * > &inputs, const std::vector< const TensorInfo * > &outputs, const StandInDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsSwitchSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output0, const TensorInfo &output1, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string & > reasonIfUnsupported=EmptyOptional()) const override
Public Member Functions inherited from ILayerSupport
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsActivationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsAdditionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsArgMinMaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchToSpaceNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsCastSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsChannelShuffleSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsComparisonSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp32ToFp16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDebugSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthToSpaceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDequantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDetectionPostProcessSupported(const TensorInfo &boxEncodings
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDilatedDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDivisionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsElementwiseUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFakeQuantizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFillSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFloorSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFullyConnectedSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsGatherSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInputSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInstanceNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsL2NormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalBinarySupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMaximumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMeanSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemCopySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemImportSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMergeSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMinimumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMultiplicationSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsOutputSupported(const TensorInfo &output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPadSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPermuteSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreCompiledSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreluSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizedLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsRankSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReduceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReshapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsResizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsShapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSliceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToBatchNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToDepthSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSplitterSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSubtractionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSwitchSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsUnidirectionalSequenceLstmSupported(const TensorInfo &input
Additional Inherited Members
Public Attributes inherited from ILayerSupport
const TensorInfo & output
const TensorInfo const ActivationDescriptor & descriptor
const TensorInfo const ActivationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & input1
const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ArgMinMaxDescriptor & descriptor
const TensorInfo const ArgMinMaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & mean
const TensorInfo const TensorInfo const TensorInfo & var
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & beta
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & gamma
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const BatchToSpaceNdDescriptor & descriptor
const TensorInfo const BatchToSpaceNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ChannelShuffleDescriptor & descriptor
const TensorInfo const ChannelShuffleDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const ComparisonDescriptor & descriptor
const TensorInfo const TensorInfo const ComparisonDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConcatSupported(const std Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution2dDescriptor & descriptor
const TensorInfo const Convolution2dDescriptor const TensorInfo & weights
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution3dDescriptor & descriptor
const TensorInfo const Convolution3dDescriptor const TensorInfo & weights
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthToSpaceDescriptor & descriptor
const TensorInfo const DepthToSpaceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthwiseConvolution2dDescriptor & descriptor
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & scores
const TensorInfo const TensorInfo & anchors
const TensorInfo const TensorInfo const TensorInfo & detectionBoxes
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionClasses
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionScores
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & numDetections
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ElementwiseUnaryDescriptor & descriptor
const TensorInfo const ElementwiseUnaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const FakeQuantizationDescriptor & descriptor
const FakeQuantizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const FillDescriptor & descriptor
const TensorInfo const FillDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & weights
const TensorInfo const TensorInfo const TensorInfo & biases
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const GatherDescriptor & descriptor
const TensorInfo const TensorInfo const GatherDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const InstanceNormalizationDescriptor & descriptor
const TensorInfo const InstanceNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const L2NormalizationDescriptor & descriptor
const TensorInfo const L2NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const LogicalBinaryDescriptor & descriptor
const TensorInfo const TensorInfo const LogicalBinaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const LogSoftmaxDescriptor & descriptor
const TensorInfo const LogSoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & outputStateIn
const TensorInfo const TensorInfo & cellStateIn
const TensorInfo const TensorInfo const TensorInfo & scratchBuffer
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const MeanDescriptor & descriptor
const TensorInfo const MeanDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & ouput
const TensorInfo const NormalizationDescriptor & descriptor
const TensorInfo const NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PadDescriptor & descriptor
const TensorInfo const PadDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PermuteDescriptor & descriptor
const TensorInfo const PermuteDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling2dDescriptor & descriptor
const TensorInfo const Pooling2dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling3dDescriptor & descriptor
const TensorInfo const Pooling3dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const PreCompiledDescriptor & descriptor
const PreCompiledDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & alpha
const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReduceDescriptor & descriptor
const TensorInfo const ReduceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReshapeDescriptor & descriptor
const TensorInfo const ReshapeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ResizeDescriptor & descriptor
const TensorInfo const ResizeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SliceDescriptor & descriptor
const TensorInfo const SliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SoftmaxDescriptor & descriptor
const TensorInfo const SoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToBatchNdDescriptor & descriptor
const TensorInfo const SpaceToBatchNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToDepthDescriptor & descriptor
const TensorInfo const SpaceToDepthDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const std::vector< std::reference_wrapper< TensorInfo > > & outputs
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor & descriptor
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo & output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor & descriptor
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & output0
const TensorInfo const TensorInfo const TensorInfo & output1
const TensorInfo const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeConvolution2dDescriptor & descriptor
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeDescriptor & descriptor
const TensorInfo const TransposeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Protected Member Functions inherited from ILayerSupport
ILayerSupport ()
virtual ~ILayerSupport ()
Detailed Description
Definition at line 14 of file ClLayerSupport.hpp.
Constructor & Destructor Documentation
ClLayerSupport() [1/2]
ClLayerSupport (const IBackendInternal::IBackendSpecificModelContextPtr & modelContextPtr) explicit
Definition at line 174 of file ClLayerSupport.cpp.
     : m_ModelContextPtr(modelContextPtr)
 {
 }
ClLayerSupport() [2/2]
ClLayerSupport ()
Definition at line 179 of file ClLayerSupport.cpp.
     : m_ModelContextPtr(nullptr)
 {
 }
~ClLayerSupport()
~ClLayerSupport () inline
Definition at line 19 of file ClLayerSupport.hpp.
 {}
Member Function Documentation
IsActivationSupported()
bool IsActivationSupported (const TensorInfo & input, const TensorInfo & output, const ActivationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 674 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClActivationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClActivationWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsAdditionSupported()
bool IsAdditionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 686 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClAdditionValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References armnn::ClAdditionValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsArgMinMaxSupported()
bool IsArgMinMaxSupported (const TensorInfo & input, const TensorInfo & output, const ArgMinMaxDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 699 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClArgMinMaxWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClArgMinMaxWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsBatchMatMulSupported()
bool IsBatchMatMulSupported (const TensorInfo & inputX, const TensorInfo & inputY, const TensorInfo & output, const BatchMatMulDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Definition at line 712 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClBatchMatMulValidate,
                                    reasonIfUnsupported,
                                    inputX,
                                    inputY,
                                    output,
                                    descriptor,
                                    nullptr);
 }
References armnn::ClBatchMatMulValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsBatchNormalizationSupported()
bool IsBatchNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & mean, const TensorInfo & var, const TensorInfo & beta, const TensorInfo & gamma, const BatchNormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 727 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClBatchNormalizationValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    mean,
                                    var,
                                    beta,
                                    gamma,
                                    descriptor,
                                    nullptr);
 }
References ILayerSupport::beta, armnn::ClBatchNormalizationValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::gamma, ILayerSupport::mean, ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::var.
Referenced by ClLayerSupport::IsLayerSupported().
IsBatchToSpaceNdSupported()
bool IsBatchToSpaceNdSupported (const TensorInfo & input, const TensorInfo & output, const BatchToSpaceNdDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 748 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClBatchToSpaceNdWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClBatchToSpaceNdWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsCastSupported()
bool IsCastSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 760 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClCastValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References armnn::ClCastValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsChannelShuffleSupported()
bool IsChannelShuffleSupported (const TensorInfo & input, const TensorInfo & output, const ChannelShuffleDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 770 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClChannelShuffleValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClChannelShuffleValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsComparisonSupported()
bool IsComparisonSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & ouput, const ComparisonDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 782 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClComparisonWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    descriptor);
 }
References armnn::ClComparisonWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsConcatSupported()
bool IsConcatSupported (const std::vector< const TensorInfo * > inputs, const TensorInfo & output, const OriginsDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 796 of file ClLayerSupport.cpp.
 {
     if (descriptor.GetNumDimensions() <= descriptor.GetConcatAxis())
     {
         SetValueChecked(reasonIfUnsupported, "Cl Concat: Concat axis > Number of dimensions.");
         return false;
     }
     unsigned int concatInnerAxis = (descriptor.GetNumDimensions() - descriptor.GetConcatAxis()) - 1;
     if(concatInnerAxis < 3) // Width, height, or channels
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(ClConcatWorkloadValidate,
                                        reasonIfUnsupported,
                                        inputs,
                                        output,
                                        descriptor);
     }
     else if (concatInnerAxis == 3)
     {
         // We rely on the sub-tensor optimization to handle the batch dimension for 4D tensors. If we can't use
         // sub-tensors for this then we can't support it. Here is where we check that the sub-tensors will work.
         for (auto& input : inputs)
         {
             if (input && !output.IsTypeSpaceMatch(*input)) // Cannot use sub-tensors if the types are not same space
             {
                 SetValueChecked(reasonIfUnsupported, "Cl Concat: Types and quantization parameters must match.");
                 return false;
             }
         }
         return true; // Sub-tensors support concat along batch
     }
     else // > 4 dimensions not supported.
     {
         SetValueChecked(reasonIfUnsupported, "Cl Concat: Maximum of 4 dimensions supported.");
         return false;
     }
 }
References armnn::ClConcatWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetNumDimensions(), TensorInfo::IsTypeSpaceMatch(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and armnn::SetValueChecked().
Referenced by ClLayerSupport::IsLayerSupported().
IsConstantSupported()
bool IsConstantSupported (const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 837 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClConstantWorkloadValidate,
                                    reasonIfUnsupported,
                                    output);
 }
References armnn::ClConstantWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsConvertFp16ToFp32Supported()
bool IsConvertFp16ToFp32Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 845 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClConvertFp16ToFp32WorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References armnn::ClConvertFp16ToFp32WorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsConvertFp32ToFp16Supported()
bool IsConvertFp32ToFp16Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 855 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClConvertFp32ToFp16WorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References armnn::ClConvertFp32ToFp16WorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsConvolution2dSupported()
bool IsConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 865 of file ClLayerSupport.cpp.
 {
     bool isFastMathEnabled = false;
 #if defined(ARMCOMPUTECL_ENABLED)
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<ClBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
 #endif
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClConvolution2dWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    isFastMathEnabled,
                                    nullptr);
 }
References ILayerSupport::biases, armnn::ClConvolution2dWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ClBackendModelContext::IsFastMathEnabled(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by ClLayerSupport::IsLayerSupported().
IsConvolution3dSupported()
bool IsConvolution3dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution3dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 898 of file ClLayerSupport.cpp.
 {
     bool isFastMathEnabled = false;
 #if defined(ARMCOMPUTECL_ENABLED)
     if (m_ModelContextPtr)
 {
     if (m_ModelContextPtr.get() != nullptr)
     {
         auto modelOptions = dynamic_cast<ClBackendModelContext*>(m_ModelContextPtr.get());
         if (modelOptions)
         {
             isFastMathEnabled = modelOptions->IsFastMathEnabled();
         }
     }
 }
 #endif
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClConvolution3dWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    isFastMathEnabled,
                                    nullptr);
 }
References ILayerSupport::biases, armnn::ClConvolution3dWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ClBackendModelContext::IsFastMathEnabled(), ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by ClLayerSupport::IsLayerSupported().
IsDepthToSpaceSupported()
bool IsDepthToSpaceSupported (const TensorInfo & input, const TensorInfo & output, const DepthToSpaceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 941 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClDepthToSpaceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClDepthToSpaceWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsDepthwiseConvolutionSupported()
bool IsDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 953 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClDepthwiseConvolutionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    nullptr);
 }
References ILayerSupport::biases, armnn::ClDepthwiseConvolutionWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by ClLayerSupport::IsLayerSupported().
IsDequantizeSupported()
bool IsDequantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 931 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClDequantizeWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References armnn::ClDequantizeWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsDilatedDepthwiseConvolutionSupported()
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reason = EmptyOptional()) const override
Definition at line 970 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClDepthwiseConvolutionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases,
                                    nullptr);
 }
References ILayerSupport::biases, armnn::ClDepthwiseConvolutionWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
IsDivisionSupported()
bool IsDivisionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 988 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClDivisionWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References armnn::ClDivisionWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsElementwiseUnarySupported()
bool IsElementwiseUnarySupported (const TensorInfo & input, const TensorInfo & output, const ElementwiseUnaryDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1001 of file ClLayerSupport.cpp.
 {
     switch(descriptor.m_Operation)
     {
         case UnaryOperation::Abs:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClAbsWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Exp:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClExpWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Log:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClLogWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::LogicalNot:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClLogicalNotWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Neg:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClNegWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Rsqrt:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClRsqrtWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Sin:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClSinWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         case UnaryOperation::Sqrt:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClSqrtWorkloadValidate,
                                            reasonIfUnsupported,
                                            input,
                                            output);
         default:
             return false;
     }
 }
References armnn::Abs, armnn::ClAbsWorkloadValidate(), armnn::ClExpWorkloadValidate(), armnn::ClLogicalNotWorkloadValidate(), armnn::ClLogWorkloadValidate(), armnn::ClNegWorkloadValidate(), armnn::ClRsqrtWorkloadValidate(), armnn::ClSinWorkloadValidate(), armnn::ClSqrtWorkloadValidate(), ILayerSupport::descriptor, armnn::Exp, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::Log, armnn::LogicalNot, armnn::Neg, ILayerSupport::output, ILayerSupport::reasonIfUnsupported, armnn::Rsqrt, armnn::Sin, and armnn::Sqrt.
Referenced by ClLayerSupport::IsLayerSupported().
IsFillSupported()
bool IsFillSupported (const TensorInfo & input, const TensorInfo & output, const FillDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override virtual
Reimplemented from LayerSupportBase.
Definition at line 1053 of file ClLayerSupport.cpp.
 {
     armnn::IgnoreUnused(input);
     armnn::IgnoreUnused(output);
     armnn::IgnoreUnused(descriptor);
     return IsClBackendSupported(reasonIfUnsupported);
 }
References ILayerSupport::descriptor, armnn::IgnoreUnused(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsFloorSupported()
bool IsFloorSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1065 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClFloorWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References armnn::ClFloorWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsFullyConnectedSupported()
bool IsFullyConnectedSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & weights, const TensorInfo & biases, const FullyConnectedDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1075 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClFullyConnectedWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    weights,
                                    biases,
                                    descriptor,
                                    nullptr);
 }
References ILayerSupport::biases, armnn::ClFullyConnectedWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by ClLayerSupport::IsLayerSupported().
IsGatherNdSupported()
bool IsGatherNdSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported) const
Definition at line 1106 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClGatherNdWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output);
 }
References armnn::ClGatherNdWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsGatherSupported()
bool IsGatherSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const GatherDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported) const override
Definition at line 1092 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClGatherWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    descriptor);
 }
References armnn::ClGatherWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsInputSupported()
bool IsInputSupported (const TensorInfo & input, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1118 of file ClLayerSupport.cpp.
 {
     return IsClBackendSupported(reasonIfUnsupported, input);
 }
References ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsInstanceNormalizationSupported()
bool IsInstanceNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const InstanceNormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1124 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClInstanceNormalizationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClInstanceNormalizationWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsL2NormalizationSupported()
bool IsL2NormalizationSupported (const TensorInfo & input, const TensorInfo & output, const L2NormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1136 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClL2NormalizationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClL2NormalizationWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsLayerSupported()
bool IsLayerSupported (const LayerType & type, const std::vector< TensorInfo > & infos, const BaseDescriptor & descriptor, const Optional< LstmInputParamsInfo > & lstmParamsInfo, const Optional< QuantizedLstmInputParamsInfo > & quantizedLstmParamsInfo, Optional< std::string & > reasonIfUnsupported) const override virtual
Reimplemented from LayerSupportBase.
Definition at line 184 of file ClLayerSupport.cpp.
 {
     switch (type)
     {
         case LayerType::Activation:
             return IsActivationSupported(infos[0],
                                          infos[1],
                                          *(PolymorphicDowncast<const ActivationDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Addition:
             ARMNN_NO_DEPRECATE_WARN_BEGIN
             return IsAdditionSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
             ARMNN_NO_DEPRECATE_WARN_END
         case LayerType::ArgMinMax:
             return IsArgMinMaxSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const ArgMinMaxDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::BatchMatMul:
             return IsBatchMatMulSupported(infos[0],
                                           infos[1],
                                           infos[2],
                                           *(PolymorphicDowncast<const BatchMatMulDescriptor*>(&descriptor)),
                                           reasonIfUnsupported);
         case LayerType::BatchNormalization:
             return IsBatchNormalizationSupported(infos[0],
                                                  infos[1],
                                                  infos[2],
                                                  infos[3],
                                                  infos[4],
                                                  infos[5],
                                                  *(PolymorphicDowncast<const BatchNormalizationDescriptor*>
                                                      (&descriptor)),
                                                  reasonIfUnsupported);
         case LayerType::BatchToSpaceNd:
             return IsBatchToSpaceNdSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const BatchToSpaceNdDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Cast:
             return IsCastSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::ChannelShuffle:
             return IsChannelShuffleSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const ChannelShuffleDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Comparison:
             return IsComparisonSupported(infos[0],
                                          infos[1],
                                          infos[2],
                                          *(PolymorphicDowncast<const ComparisonDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Concat:
         {
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < (infos.size() - 1); i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             return IsConcatSupported(inputInfos,
                                      infos[infos.size() - 1],
                                      *(PolymorphicDowncast<const OriginsDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         }
         case LayerType::Constant:
             return IsConstantSupported(infos[0], reasonIfUnsupported);
         case LayerType::ConvertFp16ToFp32:
             return IsConvertFp16ToFp32Supported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::ConvertFp32ToFp16:
             return IsConvertFp32ToFp16Supported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Convolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const Convolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsConvolution2dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsConvolution2dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 infos[3],
                                                 reasonIfUnsupported);
             }
         }
         case LayerType::Convolution3d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution3d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const Convolution3dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsConvolution3dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsConvolution3dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 infos[3],
                                                 reasonIfUnsupported);
             }
         }
         case LayerType::DepthToSpace:
             return IsDepthToSpaceSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const DepthToSpaceDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::DepthwiseConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of DepthwiseConvolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const DepthwiseConvolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsDepthwiseConvolutionSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsDepthwiseConvolutionSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          infos[3],
                                                          reasonIfUnsupported);
             }
         }
         case LayerType::Dequantize:
             return IsDequantizeSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Division:
             ARMNN_NO_DEPRECATE_WARN_BEGIN
             return IsDivisionSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
             ARMNN_NO_DEPRECATE_WARN_END
         case LayerType::ElementwiseBinary:
         {
             auto desc = *(PolymorphicDowncast<const ElementwiseBinaryDescriptor *>(&descriptor));
             switch (desc.m_Operation)
             {
                 case BinaryOperation::Add:
                     FORWARD_WORKLOAD_VALIDATE_FUNC(ClAdditionValidate,
                                                    reasonIfUnsupported,
                                                    infos[0],
                                                    infos[1],
                                                    infos[2],
                                                    nullptr);
                 case BinaryOperation::Div:
                     FORWARD_WORKLOAD_VALIDATE_FUNC(ClDivisionWorkloadValidate,
                                                    reasonIfUnsupported,
                                                    infos[0],
                                                    infos[1],
                                                    infos[2],
                                                    nullptr);
                 case BinaryOperation::Minimum:
                     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMinimumWorkloadValidate,
                                                    reasonIfUnsupported,
                                                    infos[0],
                                                    infos[1],
                                                    infos[2]);
                 case BinaryOperation::Maximum:
                     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMaximumWorkloadValidate,
                                                    reasonIfUnsupported,
                                                    infos[0],
                                                    infos[1],
                                                    infos[2]);
                 case BinaryOperation::Mul:
                     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMultiplicationWorkloadValidate,
                                                    reasonIfUnsupported,
                                                    infos[0],
                                                    infos[1],
                                                    infos[2],
                                                    nullptr);
                 case BinaryOperation::Sub:
                     FORWARD_WORKLOAD_VALIDATE_FUNC(ClSubtractionValidate,
                                                    reasonIfUnsupported,
                                                    infos[0],
                                                    infos[1],
                                                    infos[2],
                                                    nullptr);
                 default:
                     return false;
             }
         }
         case LayerType::ElementwiseUnary:
             return IsElementwiseUnarySupported(infos[0],
                                                infos[1],
                                                *(PolymorphicDowncast<const ElementwiseUnaryDescriptor*>(&descriptor)),
                                                reasonIfUnsupported);
         case LayerType::Fill:
             return IsFillSupported(infos[0],
                                    infos[1],
                                    *(PolymorphicDowncast<const FillDescriptor*>(&descriptor)),
                                    reasonIfUnsupported);
         case LayerType::Floor:
             return IsFloorSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::FullyConnected:
             return IsFullyConnectedSupported(infos[0],
                                              infos[1],
                                              infos[2],
                                              infos[3],
                                              *(PolymorphicDowncast<const FullyConnectedDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Gather:
             return IsGatherSupported(infos[0],
                                      infos[1],
                                      infos[2],
                                      *(PolymorphicDowncast<const GatherDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::GatherNd:
             return IsGatherNdSupported(infos[0],
                                        infos[1],
                                        infos[2],
                                        reasonIfUnsupported);
         case LayerType::Input:
             return IsInputSupported(infos[0], reasonIfUnsupported);
         case LayerType::InstanceNormalization:
             return IsInstanceNormalizationSupported(infos[0],
                                                     infos[1],
                                                     *(PolymorphicDowncast<const InstanceNormalizationDescriptor*>
                                                         (&descriptor)),
                                                     reasonIfUnsupported);
         case LayerType::L2Normalization:
             return IsL2NormalizationSupported(infos[0],
                                               infos[1],
                                               *(PolymorphicDowncast<const L2NormalizationDescriptor*>(&descriptor)),
                                               reasonIfUnsupported);
         case LayerType::LogicalBinary:
             return IsLogicalBinarySupported(infos[0],
                                             infos[1],
                                             infos[2],
                                             *(PolymorphicDowncast<const LogicalBinaryDescriptor*>(&descriptor)),
                                             reasonIfUnsupported);
         case LayerType::LogSoftmax:
             return IsLogSoftmaxSupported(infos[0],
                                          infos[1],
                                          *(PolymorphicDowncast<const LogSoftmaxDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Lstm:
             return IsLstmSupported(infos[0],
                                    infos[1],
                                    infos[2],
                                    infos[3],
                                    infos[4],
                                    infos[5],
                                    infos[6],
                                    *(PolymorphicDowncast<const LstmDescriptor*>(&descriptor)),
                                    lstmParamsInfo.value(),
                                    reasonIfUnsupported);
         case LayerType::Map:
             return true;
         case LayerType::MemCopy:
             return LayerSupportBase::IsMemCopySupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::MemImport:
             return LayerSupportBase::IsMemImportSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Merge:
             return LayerSupportBase::IsMergeSupported(infos[0],
                                                       infos[1],
                                                       infos[2],
                                                       reasonIfUnsupported);
         case LayerType::Maximum:
             ARMNN_NO_DEPRECATE_WARN_BEGIN
             return IsMaximumSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
             ARMNN_NO_DEPRECATE_WARN_END
         case LayerType::Mean:
             return IsMeanSupported(infos[0],
                                    infos[1],
                                    *(PolymorphicDowncast<const MeanDescriptor*>(&descriptor)),
                                    reasonIfUnsupported);
         case LayerType::Minimum:
             ARMNN_NO_DEPRECATE_WARN_BEGIN
             return IsMinimumSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
             ARMNN_NO_DEPRECATE_WARN_END
         case LayerType::Multiplication:
             ARMNN_NO_DEPRECATE_WARN_BEGIN
             return IsMultiplicationSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
             ARMNN_NO_DEPRECATE_WARN_END
         case LayerType::Normalization:
             return IsNormalizationSupported(infos[0],
                                             infos[1],
                                             *(PolymorphicDowncast<const NormalizationDescriptor*>(&descriptor)),
                                             reasonIfUnsupported);
         case LayerType::Output:
             return IsOutputSupported(infos[0], reasonIfUnsupported);
         case LayerType::Pad:
             return IsPadSupported(infos[0],
                                   infos[1],
                                   *(PolymorphicDowncast<const PadDescriptor*>(&descriptor)),
                                   reasonIfUnsupported);
         case LayerType::Permute:
             return IsPermuteSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const PermuteDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::Pooling2d:
             return IsPooling2dSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const Pooling2dDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::Pooling3d:
             return IsPooling3dSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const Pooling3dDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::Prelu:
             return IsPreluSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
         case LayerType::QLstm:
             return IsQLstmSupported(infos[0],
                                     infos[1],
                                     infos[2],
                                     infos[3],
                                     infos[4],
                                     infos[5],
                                     *(PolymorphicDowncast<const QLstmDescriptor*>(&descriptor)),
                                     lstmParamsInfo.value(),
                                     reasonIfUnsupported);
         case LayerType::Quantize:
             return IsQuantizeSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::QuantizedLstm:
             return IsQuantizedLstmSupported(infos[0],
                                             infos[1],
                                             infos[2],
                                             infos[3],
                                             infos[4],
                                             quantizedLstmParamsInfo.value(),
                                             reasonIfUnsupported);
         case LayerType::Rank:
             return true;
         case LayerType::Reduce:
             return IsReduceSupported(infos[0],
                                      infos[1],
                                      *(PolymorphicDowncast<const ReduceDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Reshape:
             return IsReshapeSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const ReshapeDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::Resize:
             return IsResizeSupported(infos[0],
                                      infos[1],
                                      *(PolymorphicDowncast<const ResizeDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Shape:
             return LayerSupportBase::IsShapeSupported(infos[0],
                                                       infos[1],
                                                       reasonIfUnsupported);
         case LayerType::Slice:
             return IsSliceSupported(infos[0],
                                     infos[1],
                                     *(PolymorphicDowncast<const SliceDescriptor*>(&descriptor)),
                                     reasonIfUnsupported);
         case LayerType::Softmax:
             return IsSoftmaxSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const SoftmaxDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::SpaceToBatchNd:
             return IsSpaceToBatchNdSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const SpaceToBatchNdDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::SpaceToDepth:
             return IsSpaceToDepthSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const SpaceToDepthDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::Splitter:
         {
             std::vector<TensorInfo> outputInfos;
             for (uint32_t i = 1; i < infos.size(); i++)
             {
                 outputInfos.push_back(infos[i]);
             }
             return IsSplitterSupported(infos[0],
                                        {outputInfos.begin(), outputInfos.end()},
                                        *(PolymorphicDowncast<const ViewsDescriptor*>(&descriptor)),
                                        reasonIfUnsupported);
         }
         case LayerType::Stack:
         {
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < infos.size() - 1; i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             return IsStackSupported(inputInfos,
                                     infos[infos.size() - 1],
                                     *(PolymorphicDowncast<const StackDescriptor*>(&descriptor)),
                                     reasonIfUnsupported);
         }
         case LayerType::StridedSlice:
             return IsStridedSliceSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const StridedSliceDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::Subtraction:
             ARMNN_NO_DEPRECATE_WARN_BEGIN
             return IsSubtractionSupported(infos[0], infos[1], infos[2], reasonIfUnsupported);
             ARMNN_NO_DEPRECATE_WARN_END
         case LayerType::Transpose:
             return IsTransposeSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const TransposeDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::TransposeConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of TransposeConvolution2d TensorInfos. "
                                                "TensorInfos should be of format: {input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const TransposeConvolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsTransposeConvolution2dSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          EmptyOptional(),
                                                          reasonIfUnsupported);
             }
             else
             {
                 return IsTransposeConvolution2dSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          infos[3],
                                                          reasonIfUnsupported);
             }
         }
         case LayerType::UnidirectionalSequenceLstm:
             return IsUnidirectionalSequenceLstmSupported(infos[0],
                                                          infos[1],
                                                          infos[2],
                                                          infos[3],
                                                          infos[4],
                                                          infos[5],
                                                          *(PolymorphicDowncast<const
                                                             UnidirectionalSequenceLstmDescriptor*>(&descriptor)),
                                                          lstmParamsInfo.value(),
                                                          reasonIfUnsupported);
         case LayerType::Unmap:
             return true;
         default:
             // layers not supported in cl by default:
             // debug, detectionpostprocess, fakequantization,
             // precompiled, standin, switch, pooling3d
             return false;
     }
 }
References armnn::Activation, armnn::Add, armnn::Addition, armnn::ArgMinMax, ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, armnn::BatchMatMul, armnn::BatchNormalization, armnn::BatchToSpaceNd, armnn::Cast, armnn::ChannelShuffle, armnn::ClAdditionValidate(), armnn::ClDivisionWorkloadValidate(), armnn::ClMaximumWorkloadValidate(), armnn::ClMinimumWorkloadValidate(), armnn::ClMultiplicationWorkloadValidate(), armnn::ClSubtractionValidate(), armnn::Comparison, armnn::Concat, armnn::Constant, armnn::ConvertFp16ToFp32, armnn::ConvertFp32ToFp16, armnn::Convolution2d, armnn::Convolution3d, armnn::DepthToSpace, armnn::DepthwiseConvolution2d, armnn::Dequantize, ILayerSupport::descriptor, armnn::Div, armnn::Division, armnn::ElementwiseBinary, armnn::ElementwiseUnary, armnn::Fill, armnn::Floor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::FullyConnected, armnn::Gather, armnn::GatherNd, armnn::Input, armnn::InstanceNormalization, ClLayerSupport::IsActivationSupported(), ClLayerSupport::IsAdditionSupported(), ClLayerSupport::IsArgMinMaxSupported(), ClLayerSupport::IsBatchMatMulSupported(), ClLayerSupport::IsBatchNormalizationSupported(), ClLayerSupport::IsBatchToSpaceNdSupported(), ClLayerSupport::IsCastSupported(), ClLayerSupport::IsChannelShuffleSupported(), ClLayerSupport::IsComparisonSupported(), ClLayerSupport::IsConcatSupported(), ClLayerSupport::IsConstantSupported(), ClLayerSupport::IsConvertFp16ToFp32Supported(), ClLayerSupport::IsConvertFp32ToFp16Supported(), ClLayerSupport::IsConvolution2dSupported(), ClLayerSupport::IsConvolution3dSupported(), ClLayerSupport::IsDepthToSpaceSupported(), ClLayerSupport::IsDepthwiseConvolutionSupported(), ClLayerSupport::IsDequantizeSupported(), ClLayerSupport::IsDivisionSupported(), ClLayerSupport::IsElementwiseUnarySupported(), ClLayerSupport::IsFillSupported(), ClLayerSupport::IsFloorSupported(), ClLayerSupport::IsFullyConnectedSupported(), ClLayerSupport::IsGatherNdSupported(), ClLayerSupport::IsGatherSupported(), ClLayerSupport::IsInputSupported(), ClLayerSupport::IsInstanceNormalizationSupported(), ClLayerSupport::IsL2NormalizationSupported(), ClLayerSupport::IsLogicalBinarySupported(), ClLayerSupport::IsLogSoftmaxSupported(), ClLayerSupport::IsLstmSupported(), ClLayerSupport::IsMaximumSupported(), ClLayerSupport::IsMeanSupported(), LayerSupportBase::IsMemCopySupported(), LayerSupportBase::IsMemImportSupported(), LayerSupportBase::IsMergeSupported(), ClLayerSupport::IsMinimumSupported(), ClLayerSupport::IsMultiplicationSupported(), ClLayerSupport::IsNormalizationSupported(), ClLayerSupport::IsOutputSupported(), ClLayerSupport::IsPadSupported(), ClLayerSupport::IsPermuteSupported(), ClLayerSupport::IsPooling2dSupported(), ClLayerSupport::IsPooling3dSupported(), ClLayerSupport::IsPreluSupported(), ClLayerSupport::IsQLstmSupported(), ClLayerSupport::IsQuantizedLstmSupported(), ClLayerSupport::IsQuantizeSupported(), ClLayerSupport::IsReduceSupported(), ClLayerSupport::IsReshapeSupported(), ClLayerSupport::IsResizeSupported(), LayerSupportBase::IsShapeSupported(), ClLayerSupport::IsSliceSupported(), ClLayerSupport::IsSoftmaxSupported(), ClLayerSupport::IsSpaceToBatchNdSupported(), ClLayerSupport::IsSpaceToDepthSupported(), ClLayerSupport::IsSplitterSupported(), ClLayerSupport::IsStackSupported(), ClLayerSupport::IsStridedSliceSupported(), ClLayerSupport::IsSubtractionSupported(), ClLayerSupport::IsTransposeConvolution2dSupported(), ClLayerSupport::IsTransposeSupported(), ClLayerSupport::IsUnidirectionalSequenceLstmSupported(), armnn::L2Normalization, armnn::LogicalBinary, armnn::LogSoftmax, armnn::Lstm, armnn::Map, armnn::Maximum, armnn::Mean, armnn::MemCopy, armnn::MemImport, armnn::Merge, armnn::Minimum, armnn::Mul, armnn::Multiplication, armnn::Normalization, armnn::Output, armnn::Pad, armnn::Permute, armnn::PolymorphicDowncast(), armnn::Pooling2d, armnn::Pooling3d, armnn::Prelu, armnn::QLstm, armnn::Quantize, armnn::QuantizedLstm, armnn::Rank, ILayerSupport::reasonIfUnsupported, armnn::Reduce, armnn::Reshape, armnn::Resize, armnn::Shape, armnn::Slice, armnn::Softmax, armnn::SpaceToBatchNd, armnn::SpaceToDepth, armnn::Splitter, armnn::Stack, armnn::StridedSlice, armnn::Sub, armnn::Subtraction, armnn::Transpose, armnn::TransposeConvolution2d, armnn::UnidirectionalSequenceLstm, armnn::Unmap, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
IsLogicalBinarySupported()
bool IsLogicalBinarySupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const LogicalBinaryDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported) const override
Definition at line 1148 of file ClLayerSupport.cpp.
 {
     IgnoreUnused(output);
     switch(descriptor.m_Operation)
     {
         case LogicalBinaryOperation::LogicalAnd:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClLogicalAndWorkloadValidate,
                                            reasonIfUnsupported,
                                            input0,
                                            input1,
                                            output);
         case LogicalBinaryOperation::LogicalOr:
             FORWARD_WORKLOAD_VALIDATE_FUNC(ClLogicalOrWorkloadValidate,
                                            reasonIfUnsupported,
                                            input0,
                                            input1,
                                            output);
         default:
             return false;
     }
 }
References armnn::ClLogicalAndWorkloadValidate(), armnn::ClLogicalOrWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::IgnoreUnused(), ILayerSupport::input1, armnn::LogicalAnd, armnn::LogicalOr, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsLogSoftmaxSupported()
bool IsLogSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const LogSoftmaxDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1176 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClLogSoftmaxWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClLogSoftmaxWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsLstmSupported()
bool IsLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & scratchBuffer, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const LstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1188 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClLstmFloatWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    outputStateIn,
                                    cellStateIn,
                                    scratchBuffer,
                                    outputStateOut,
                                    cellStateOut,
                                    output,
                                    descriptor,
                                    paramsInfo);
 }
References ILayerSupport::cellStateIn, ILayerSupport::cellStateOut, armnn::ClLstmFloatWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::outputStateIn, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, ILayerSupport::reasonIfUnsupported, and ILayerSupport::scratchBuffer.
Referenced by ClLayerSupport::IsLayerSupported().
IsMaximumSupported()
bool IsMaximumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1212 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMaximumWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output);
 }
References armnn::ClMaximumWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsMeanSupported()
bool IsMeanSupported (const TensorInfo & input, const TensorInfo & output, const MeanDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1224 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMeanValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClMeanValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsMinimumSupported()
bool IsMinimumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1236 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMinimumWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output);
 }
References armnn::ClMinimumWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsMultiplicationSupported()
bool IsMultiplicationSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1248 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClMultiplicationWorkloadValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References armnn::ClMultiplicationWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsNormalizationSupported()
bool IsNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const NormalizationDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1261 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClNormalizationWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClNormalizationWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsOutputSupported()
bool IsOutputSupported (const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1269 of file ClLayerSupport.cpp.
 {
     return IsClBackendSupported(reasonIfUnsupported, output);
 }
References ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsPadSupported()
bool IsPadSupported (const TensorInfo & input, const TensorInfo & output, const PadDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1275 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClPadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClPadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsPermuteSupported()
bool IsPermuteSupported (const TensorInfo & input, const TensorInfo & output, const PermuteDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1287 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClPermuteWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClPermuteWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsPooling2dSupported()
bool IsPooling2dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling2dDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1295 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClPooling2dWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClPooling2dWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsPooling3dSupported()
bool IsPooling3dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling3dDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1303 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClPooling3dWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClPooling3dWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsPreluSupported()
bool IsPreluSupported (const TensorInfo & input, const TensorInfo & alpha, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1311 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClPreluWorkloadValidate, reasonIfUnsupported, input, alpha, output);
 }
References ILayerSupport::alpha, armnn::ClPreluWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsQLstmSupported()
bool IsQLstmSupported (const TensorInfo & input, const TensorInfo & previousOutputIn, const TensorInfo & previousCellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const QLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1319 of file ClLayerSupport.cpp.
 {
     if (input.GetDataType()               == armnn::DataType::QAsymmS8 &&
         previousOutputIn.GetDataType()    == armnn::DataType::QAsymmS8 &&
         previousCellStateIn.GetDataType() == armnn::DataType::QSymmS16 &&
         outputStateOut.GetDataType()      == armnn::DataType::QAsymmS8 &&
         cellStateOut.GetDataType()        == armnn::DataType::QSymmS16 &&
         output.GetDataType()              == armnn::DataType::QAsymmS8)
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(ClQLstmWorkloadValidate,
                                        reasonIfUnsupported,
                                        input,
                                        previousCellStateIn,
                                        previousOutputIn,
                                        cellStateOut,
                                        outputStateOut,
                                        output,
                                        descriptor,
                                        paramsInfo);
     }
     else
     {
         return false;
     }
 }
References ILayerSupport::cellStateOut, armnn::ClQLstmWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetDataType(), ILayerSupport::output, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, ILayerSupport::previousCellStateIn, ILayerSupport::previousOutputIn, armnn::QAsymmS8, armnn::QSymmS16, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsQuantizedLstmSupported()
bool IsQuantizedLstmSupported (const TensorInfo & input, const TensorInfo & previousCellStateIn, const TensorInfo & previousOutputIn, const TensorInfo & cellStateOut, const TensorInfo & output, const QuantizedLstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1353 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClQuantizedLstmWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    previousCellStateIn,
                                    previousOutputIn,
                                    cellStateOut,
                                    output,
                                    paramsInfo);
 }
References ILayerSupport::cellStateOut, armnn::ClQuantizedLstmWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::paramsInfo, ILayerSupport::previousCellStateIn, ILayerSupport::previousOutputIn, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsQuantizeSupported()
bool IsQuantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1371 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClQuantizeWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output);
 }
References armnn::ClQuantizeWorkloadValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsReduceSupported()
bool IsReduceSupported (const TensorInfo & input, const TensorInfo & output, const ReduceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1381 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClReduceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClReduceWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsReshapeSupported()
bool IsReshapeSupported (const TensorInfo & input, const TensorInfo & output, const ReshapeDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1393 of file ClLayerSupport.cpp.
 {
     IgnoreUnused(descriptor);
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClReshapeWorkloadValidate, reasonIfUnsupported, input, output);
 }
References armnn::ClReshapeWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, armnn::IgnoreUnused(), ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsResizeSupported()
bool IsResizeSupported (const TensorInfo & input, const TensorInfo & output, const ResizeDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1402 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClResizeWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClResizeWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsSliceSupported()
bool IsSliceSupported (const TensorInfo & input, const TensorInfo & output, const SliceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1410 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClSliceWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClSliceWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsSoftmaxSupported()
bool IsSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const SoftmaxDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1418 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClSoftmaxWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClSoftmaxWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsSpaceToBatchNdSupported()
bool IsSpaceToBatchNdSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToBatchNdDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1426 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClSpaceToBatchNdWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClSpaceToBatchNdWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsSpaceToDepthSupported()
bool IsSpaceToDepthSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToDepthDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1438 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClSpaceToDepthWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClSpaceToDepthWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsSplitterSupported()
bool IsSplitterSupported (const TensorInfo & input, const std::vector< std::reference_wrapper< TensorInfo >> & outputs, const ViewsDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1450 of file ClLayerSupport.cpp.
 {
 #if defined(ARMCOMPUTECL_ENABLED)
     // Split along the last dimension, cannot use sub-tensors
     // as width and height of the sub-tensors do not match
     // the width and height of the parent tensor
     // in case of input with more than 2D.
     std::set<unsigned int> splitAxis = ComputeSplitAxis(descriptor, input.GetShape());
     if (descriptor.GetNumDimensions() > 2 && splitAxis.size() == 1 &&
         *splitAxis.begin() == descriptor.GetNumDimensions() - 1 )
     {
         FORWARD_WORKLOAD_VALIDATE_FUNC(ClSplitterWorkloadValidate,
                                        reasonIfUnsupported,
                                        input,
                                        outputs,
                                        *splitAxis.begin());
     }
 #endif
     IgnoreUnused(descriptor);
     for (auto output : outputs)
     {
         if (!input.IsTypeSpaceMatch(output)) // Cannot use sub-tensors if the types are not same space
         {
             SetValueChecked(reasonIfUnsupported, "Cl Splitter: Types and quantization parameters must match.");
             return false;
         }
     }
     return true;
 }
References armnn::ClSplitterWorkloadValidate(), armnn::ComputeSplitAxis(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), armnn::IgnoreUnused(), TensorInfo::IsTypeSpaceMatch(), ILayerSupport::output, ILayerSupport::outputs, ILayerSupport::reasonIfUnsupported, and armnn::SetValueChecked().
Referenced by ClLayerSupport::IsLayerSupported().
IsStackSupported()
bool IsStackSupported (const std::vector< const TensorInfo * > & inputs, const TensorInfo & output, const StackDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1483 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClStackWorkloadValidate,
                                    reasonIfUnsupported,
                                    inputs,
                                    output,
                                    descriptor);
 }
References armnn::ClStackWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsStridedSliceSupported()
bool IsStridedSliceSupported (const TensorInfo & input, const TensorInfo & output, const StridedSliceDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1495 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClStridedSliceWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor);
 }
References armnn::ClStridedSliceWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsSubtractionSupported()
bool IsSubtractionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1507 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClSubtractionValidate,
                                    reasonIfUnsupported,
                                    input0,
                                    input1,
                                    output,
                                    nullptr);
 }
References armnn::ClSubtractionValidate(), FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::input1, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsTransposeConvolution2dSupported()
bool IsTransposeConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const TransposeConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1520 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClTransposeConvolution2dWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    output,
                                    descriptor,
                                    weights,
                                    biases);
 }
References ILayerSupport::biases, armnn::ClTransposeConvolution2dWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::reasonIfUnsupported, and ILayerSupport::weights.
Referenced by ClLayerSupport::IsLayerSupported().
IsTransposeSupported()
bool IsTransposeSupported (const TensorInfo & input, const TensorInfo & output, const TransposeDescriptor & descriptor, Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const override
Definition at line 1536 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClTransposeWorkloadValidate, reasonIfUnsupported, input, output, descriptor);
 }
References armnn::ClTransposeWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
IsUnidirectionalSequenceLstmSupported()
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const UnidirectionalSequenceLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string & > reasonIfUnsupported) const override
Definition at line 1544 of file ClLayerSupport.cpp.
 {
     FORWARD_WORKLOAD_VALIDATE_FUNC(ClUnidirectionalSequenceLstmFloatWorkloadValidate,
                                    reasonIfUnsupported,
                                    input,
                                    outputStateIn,
                                    cellStateIn,
                                    outputStateOut,
                                    cellStateOut,
                                    output,
                                    descriptor,
                                    paramsInfo);
 }
References ILayerSupport::cellStateIn, ILayerSupport::cellStateOut, armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), ILayerSupport::descriptor, FORWARD_WORKLOAD_VALIDATE_FUNC, ILayerSupport::output, ILayerSupport::outputStateIn, ILayerSupport::outputStateOut, ILayerSupport::paramsInfo, and ILayerSupport::reasonIfUnsupported.
Referenced by ClLayerSupport::IsLayerSupported().
The documentation for this class was generated from the following files:
src/backends/cl/ClLayerSupport.hpp
src/backends/cl/ClLayerSupport.cpp