ArmNN: NeonBackendModelContext Class Reference
NeonBackendModelContext Class Reference
The NeonBackendModelContext is used to pass in Neon specific backend ModelOptions.
#include <NeonBackendModelContext.hpp>
Public Member Functions
NeonBackendModelContext (const ModelOptions &modelOptions)
bool IsFastMathEnabled () const
unsigned int GetNumberOfThreads () const
Public Member Functions inherited from IBackendModelContext
virtual ~IBackendModelContext ()
Detailed Description
The NeonBackendModelContext is used to pass in Neon specific backend ModelOptions.
The supported backend ModelOptions are:
"FastMathEnabled"
Using the fast_math flag can lead to performance improvements in fp32 and fp16 layers but may result in
results with reduced or different precision. The fast_math flag will not have any effect on int8 performance.
"NumberOfThreads"
Specify the number of threads used by the CpuAcc backend.
Definition at line 19 of file NeonBackendModelContext.hpp.
Constructor & Destructor Documentation
NeonBackendModelContext()
NeonBackendModelContext (const ModelOptions & modelOptions)
Definition at line 34 of file NeonBackendModelContext.cpp.
     : m_IsFastMathEnabled(false), m_NumberOfThreads(0)
 {
    if (!modelOptions.empty())
    {
        ParseOptions(modelOptions, "CpuAcc", [&](std::string name, const BackendOptions::Var& value)
        {
            if (name == "FastMathEnabled")
            {
                m_IsFastMathEnabled |= ParseBool(value, false);
            }
            if (name == "NumberOfThreads")
            {
                m_NumberOfThreads |= ParseUnsignedInt(value, 0);
            }
        });
    }
 }
References armnn::ParseOptions().
Member Function Documentation
GetNumberOfThreads()
unsigned int GetNumberOfThreads () const
Definition at line 58 of file NeonBackendModelContext.cpp.
 {
     return m_NumberOfThreads;
 }
IsFastMathEnabled()
bool IsFastMathEnabled () const
Definition at line 53 of file NeonBackendModelContext.cpp.
 {
     return m_IsFastMathEnabled;
 }
Referenced by NeonWorkloadFactory::CreateWorkload(), NeonLayerSupport::IsBatchMatMulSupported(), NeonLayerSupport::IsConvolution2dSupported(), and NeonLayerSupport::IsConvolution3dSupported().
The documentation for this class was generated from the following files:
src/backends/neon/NeonBackendModelContext.hpp
src/backends/neon/NeonBackendModelContext.cpp