ArmNN: SubgraphView Class Reference
SubgraphView Class Reference final
The SubgraphView class represents a subgraph of a Graph.
#include <SubgraphView.hpp>
Public Types
using SubgraphViewPtr = std::shared_ptr< SubgraphView >
using InputSlots = std::vector< InputSlot * >
using IInputSlots = std::vector< IInputSlot * >
using OutputSlots = std::vector< OutputSlot * >
using IOutputSlots = std::vector< IOutputSlot * >
using Layers = std::list< Layer * >
using IConnectableLayers = std::list< IConnectableLayer * >
using Iterator = Layers::iterator
using IConnectableLayerIterator = IConnectableLayers::iterator
using ConstIterator = Layers::const_iterator
using ConstIConnectableIterator = IConnectableLayers::const_iterator
Public Member Functions
template<typename Func >
void ForEachLayer (Func func) const
template<typename Func >
void ForEachIConnectableLayer (Func func) const
SubgraphView (Graph &graph)
Constructs a sub-graph from the entire given graph.
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use constructor with arguments: " "IConnectableLayers, IInputSlots and IOutputSlots", "23.08") SubgraphView(InputSlots &&inputs
Constructs a sub-graph with the given arguments.
SubgraphView (IConnectableLayers &&layers, IInputSlots &&inputs, IOutputSlots &&outputs)
Constructs a sub-graph with the given arguments.
SubgraphView (const SubgraphView &subgraph)
Copy-constructor.
SubgraphView (SubgraphView &&subgraph)
Move-constructor.
SubgraphView (IConnectableLayer *layer)
Constructs a sub-graph with only the given layer.
SubgraphView & operator= (SubgraphView &&other)
Move-assignment operator.
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIInputSlots() returning" " public IInputSlots", "23.08") const InputSlots &GetInputSlots() const
const IInputSlots & GetIInputSlots () const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIOutputSlots() returning" " public IOutputSlots", "23.08") const OutputSlots &GetOutputSlots() const
const IOutputSlots & GetIOutputSlots () const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIConnectableLayers() " "returning public IConnectableLayers", "23.08") const Layers &GetLayers() const
const IConnectableLayers & GetIConnectableLayers () const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIInputSlot() returning public " "IInputSlot", "23.08") const InputSlot *GetInputSlot(unsigned int index) const
const IInputSlot * GetIInputSlot (unsigned int index) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIInputSlot() returning public " "IInputSlot", "23.08") InputSlot *GetInputSlot(unsigned int index)
IInputSlot * GetIInputSlot (unsigned int index)
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIOutputSlot() returning" " public IOutputSlot", "23.08") const OutputSlot *GetOutputSlot(unsigned int index) const
const IOutputSlot * GetIOutputSlot (unsigned int index) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIOutputSlot() returning" " public IOutputSlot", "23.08") OutputSlot *GetOutputSlot(unsigned int index)
IOutputSlot * GetIOutputSlot (unsigned int index)
unsigned int GetNumInputSlots () const
unsigned int GetNumOutputSlots () const
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " "IConnectableLayerIterator, until that occurs in 23.08; please use " "beginIConnectable() returning public IConnectableLayerIterator", "23.08") Iterator begin()
IConnectableLayerIterator beginIConnectable ()
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " "IConnectableLayerIterator, until that occurs in 23.08; please use " "endIConnectable() returning public IConnectableLayerIterator", "23.08") Iterator end()
IConnectableLayerIterator endIConnectable ()
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " "ConstIConnectableIterator, until that occurs in 23.08; please use " "beginIConnectable() returning public ConstIConnectableIterator", "23.08") ConstIterator begin() const
ConstIConnectableIterator beginIConnectable () const
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " "ConstIConnectableIterator, until that occurs in 23.08; please use " "endIConnectable() returning public ConstIConnectableIterator", "23.08") ConstIterator end() const
ConstIConnectableIterator endIConnectable () const
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " "ConstIConnectableIterator, until that occurs in 23.08; please use " "cbeginIConnectable() returning public ConstIConnectableIterator", "23.08") ConstIterator cbegin() const
ConstIConnectableIterator cbeginIConnectable () const
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " "ConstIConnectableIterator, until that occurs in 23.08; please use " "cendIConnectable() returning public ConstIConnectableIterator", "23.08") ConstIterator cend() const
ConstIConnectableIterator cendIConnectable () const
void Clear ()
SubgraphView GetWorkingCopy () const
This method returns a copy of the original SubgraphView provided by OptimizeSubgraphView with a separate underlying graph from the main ArmNN graph.
void SubstituteSubgraph (SubgraphView &, IConnectableLayer *)
These methods should be called on a working copy subgraph created from GetWorkingCopy.
void SubstituteSubgraph (SubgraphView &, const SubgraphView &)
const IInputSlots & GetOriginalInputSlots () const
These methods should be called on a working copy subgraph created from GetWorkingCopy.
const IOutputSlots & GetOriginalOutputSlots () const
Public Attributes
OutputSlots && outputs
OutputSlots Layers && layers
Detailed Description
The SubgraphView class represents a subgraph of a Graph.
The data it holds, points to data held by layers of the Graph, so the the contents of the SubgraphView become invalid when the Layers are destroyed or changed.
Definition at line 31 of file SubgraphView.hpp.
Member Typedef Documentation
ConstIConnectableIterator
using ConstIConnectableIterator = IConnectableLayers::const_iterator
Definition at line 66 of file SubgraphView.hpp.
ConstIterator
using ConstIterator = Layers::const_iterator
Definition at line 65 of file SubgraphView.hpp.
IConnectableLayerIterator
using IConnectableLayerIterator = IConnectableLayers::iterator
Definition at line 64 of file SubgraphView.hpp.
IConnectableLayers
using IConnectableLayers = std::list<IConnectableLayer*>
Definition at line 62 of file SubgraphView.hpp.
IInputSlots
using IInputSlots = std::vector<IInputSlot*>
Definition at line 58 of file SubgraphView.hpp.
InputSlots
using InputSlots = std::vector<InputSlot*>
Definition at line 57 of file SubgraphView.hpp.
IOutputSlots
using IOutputSlots = std::vector<IOutputSlot*>
Definition at line 60 of file SubgraphView.hpp.
Iterator
using Iterator = Layers::iterator
Definition at line 63 of file SubgraphView.hpp.
Layers
using Layers = std::list<Layer*>
Definition at line 61 of file SubgraphView.hpp.
OutputSlots
using OutputSlots = std::vector<OutputSlot*>
Definition at line 59 of file SubgraphView.hpp.
SubgraphViewPtr
using SubgraphViewPtr = std::shared_ptr<SubgraphView>
Definition at line 56 of file SubgraphView.hpp.
Constructor & Destructor Documentation
SubgraphView() [1/5]
SubgraphView (Graph & graph) explicit
Constructs a sub-graph from the entire given graph.
Definition at line 45 of file SubgraphView.cpp.
     : enable_shared_from_this()
     , m_InputSlots{}
     , m_OutputSlots{}
     , m_Layers(graph.begin(), graph.end())
     , m_IConnectableLayers(graph.begin(), graph.end())
 {
     ArrangeBySortOrder();
     CheckSubgraph();
 }
SubgraphView() [2/5]
SubgraphView (SubgraphView::IConnectableLayers && layers, SubgraphView::IInputSlots && inputs, SubgraphView::IOutputSlots && outputs)
Constructs a sub-graph with the given arguments.
IConnectable Duplication to maintain backwards compatibility.
Definition at line 71 of file SubgraphView.cpp.
         : enable_shared_from_this()
         , m_IInputSlots{inputs}
         , m_IOutputSlots{outputs}
         , m_IConnectableLayers(IConnectableLayers{layers.begin(), layers.end()})
 {
     // Cast from IConnectableLayer to Layer for backward compatibility
     auto f = [](IConnectableLayer* value)
     {
         return PolymorphicDowncast<Layer*>(value);
     };
     std::transform(layers.begin(), layers.end(), std::back_inserter(m_Layers), f);
     m_InputSlots.resize(inputs.size());
     m_IInputSlots.resize(inputs.size());
     for (unsigned int i = 0; i < inputs.size(); i++)
     {
         m_InputSlots.at(i) = PolymorphicDowncast<InputSlot*>(inputs[i]);
         m_IInputSlots.at(i) = inputs[i];
     }
     m_OutputSlots.resize(outputs.size());
     m_IOutputSlots.resize(outputs.size());
     for (unsigned int i = 0; i < outputs.size(); i++)
     {
         m_OutputSlots.at(i) = PolymorphicDowncast<OutputSlot*>(outputs[i]);
         m_IOutputSlots.at(i) = outputs[i];
     }
     ArrangeBySortOrder();
     CheckSubgraph();
 }
SubgraphView() [3/5]
SubgraphView (const SubgraphView & subgraph)
Copy-constructor.
Definition at line 144 of file SubgraphView.cpp.
     : enable_shared_from_this()
     , m_InputSlots(subgraph.m_InputSlots.begin(), subgraph.m_InputSlots.end())
     , m_IInputSlots(subgraph.m_IInputSlots.begin(), subgraph.m_IInputSlots.end())
     , m_OutputSlots(subgraph.m_OutputSlots.begin(), subgraph.m_OutputSlots.end())
     , m_IOutputSlots(subgraph.m_IOutputSlots.begin(), subgraph.m_IOutputSlots.end())
     , m_Layers(subgraph.m_Layers.begin(), subgraph.m_Layers.end())
     , m_IConnectableLayers(IConnectableLayers{subgraph.m_IConnectableLayers.begin(),
                                               subgraph.m_IConnectableLayers.end()})
 {
     ArrangeBySortOrder();
     CheckSubgraph();
 }
SubgraphView() [4/5]
SubgraphView (SubgraphView && subgraph)
Move-constructor.
Definition at line 158 of file SubgraphView.cpp.
     : enable_shared_from_this()
     , m_InputSlots(std::move(subgraph.m_InputSlots))
     , m_IInputSlots(std::move(subgraph.m_IInputSlots))
     , m_OutputSlots(std::move(subgraph.m_OutputSlots))
     , m_IOutputSlots(std::move(subgraph.m_IOutputSlots))
     , m_Layers(std::move(subgraph.m_Layers))
     , m_IConnectableLayers(std::move(subgraph.m_IConnectableLayers))
 {
     ArrangeBySortOrder();
     CheckSubgraph();
 }
SubgraphView() [5/5]
SubgraphView (IConnectableLayer * layer)
Constructs a sub-graph with only the given layer.
Definition at line 171 of file SubgraphView.cpp.
     : enable_shared_from_this()
     , m_Layers{PolymorphicDowncast<Layer*>(layer)}
     , m_IConnectableLayers{layer}
 {
     unsigned int numInputSlots = layer->GetNumInputSlots();
     m_InputSlots.resize(numInputSlots);
     m_IInputSlots.resize(numInputSlots);
     for (unsigned int i = 0; i < numInputSlots; i++)
     {
         m_InputSlots.at(i) = PolymorphicDowncast<InputSlot*>(&(layer->GetInputSlot(i)));
         m_IInputSlots.at(i) = &(layer->GetInputSlot(i));
     }
     unsigned int numOutputSlots = layer->GetNumOutputSlots();
     m_OutputSlots.resize(numOutputSlots);
     m_IOutputSlots.resize(numOutputSlots);
     for (unsigned int i = 0; i < numOutputSlots; i++)
     {
         m_OutputSlots.at(i) = PolymorphicDowncast<OutputSlot*>(&(layer->GetOutputSlot(i)));
         m_IOutputSlots.at(i) = &(layer->GetOutputSlot(i));
     }
     CheckSubgraph();
 }
Member Function Documentation
ARMNN_DEPRECATED_MSG_CHANGE_DATE() [1/6]
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " " ConstIConnectableIterator, until that occurs in 23.08;please use " "beginIConnectable() returning public ConstIConnectableIterator" , "23.08") const
ARMNN_DEPRECATED_MSG_CHANGE_DATE() [2/6]
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " " ConstIConnectableIterator, until that occurs in 23.08;please use " "cbeginIConnectable() returning public ConstIConnectableIterator" , "23.08") const
ARMNN_DEPRECATED_MSG_CHANGE_DATE() [3/6]
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " " ConstIConnectableIterator, until that occurs in 23.08;please use " "cendIConnectable() returning public ConstIConnectableIterator" , "23.08") const
ARMNN_DEPRECATED_MSG_CHANGE_DATE() [4/6]
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " " ConstIConnectableIterator, until that occurs in 23.08;please use " "endIConnectable() returning public ConstIConnectableIterator" , "23.08") const
ARMNN_DEPRECATED_MSG_CHANGE_DATE() [5/6]
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " " IConnectableLayerIterator, until that occurs in 23.08;please use " "beginIConnectable() returning public IConnectableLayerIterator" , "23.08")
ARMNN_DEPRECATED_MSG_CHANGE_DATE() [6/6]
ARMNN_DEPRECATED_MSG_CHANGE_DATE ("This function is deprecated and will be changed to return an " " IConnectableLayerIterator, until that occurs in 23.08;please use " "endIConnectable() returning public IConnectableLayerIterator" , "23.08")
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [1/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use constructor with arguments:" " IConnectableLayers, IInputSlots and IOutputSlots" , "23.08") &&
Constructs a sub-graph with the given arguments.
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [2/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIConnectableLayers() " "returning public IConnectableLayers" , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [3/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIInputSlot() returning public " "IInputSlot" , "23.08") const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [4/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIInputSlot() returning public " "IInputSlot" , "23.08")
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [5/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIInputSlots() returning" " public IInputSlots" , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [6/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIOutputSlot() returning" " public IOutputSlot" , "23.08") const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [7/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIOutputSlot() returning" " public IOutputSlot" , "23.08")
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [8/8]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This function has been deprecated, please use GetIOutputSlots() returning" " public IOutputSlots" , "23.08") const &
beginIConnectable() [1/2]
SubgraphView::ConstIConnectableIterator beginIConnectable ()
Definition at line 324 of file SubgraphView.cpp.
 {
     return m_IConnectableLayers.begin();
 }
Referenced by armnn::AssignBackends(), SubgraphView::cbeginIConnectable(), TosaRefBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), and ClBackend::OptimizeSubgraphView().
beginIConnectable() [2/2]
ConstIConnectableIterator beginIConnectable () const
cbeginIConnectable()
SubgraphView::ConstIConnectableIterator cbeginIConnectable () const
Definition at line 372 of file SubgraphView.cpp.
 {
     return beginIConnectable();
 }
References SubgraphView::beginIConnectable().
cendIConnectable()
SubgraphView::ConstIConnectableIterator cendIConnectable () const
Definition at line 377 of file SubgraphView.cpp.
 {
     return endIConnectable();
 }
References SubgraphView::endIConnectable().
Clear()
void Clear ()
Definition at line 382 of file SubgraphView.cpp.
 {
     m_InputSlots.clear();
     m_OutputSlots.clear();
     m_Layers.clear();
     m_IInputSlots.clear();
     m_IOutputSlots.clear();
     m_IConnectableLayers.clear();
 }
endIConnectable() [1/2]
SubgraphView::ConstIConnectableIterator endIConnectable ()
Definition at line 329 of file SubgraphView.cpp.
 {
     return m_IConnectableLayers.end();
 }
Referenced by armnn::AssignBackends(), SubgraphView::cendIConnectable(), TosaRefBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), and ClBackend::OptimizeSubgraphView().
endIConnectable() [2/2]
ConstIConnectableIterator endIConnectable () const
ForEachIConnectableLayer()
void ForEachIConnectableLayer (Func func) const inline
Definition at line 46 of file SubgraphView.hpp.
     {
         for (auto it = m_IConnectableLayers.begin(); it != m_IConnectableLayers.end(); )
         {
              auto next = std::next(it);
              func(*it);
              it = next;
         }
     }
Referenced by SubgraphView::SubstituteSubgraph(), and Graph::SubstituteSubgraph().
ForEachLayer()
void ForEachLayer (Func func) const inline
Definition at line 35 of file SubgraphView.hpp.
     {
         for (auto it = m_Layers.begin(); it != m_Layers.end(); )
         {
              auto next = std::next(it);
              func(*it);
              it = next;
         }
     }
GetIConnectableLayers()
const SubgraphView::IConnectableLayers & GetIConnectableLayers () const
Definition at line 308 of file SubgraphView.cpp.
 {
     return m_IConnectableLayers;
 }
Referenced by armnn::ApplyBackendOptimizations(), SubgraphView::GetWorkingCopy(), SubgraphViewSelector::SelectSubgraphs(), and OptimizationViews::Validate().
GetIInputSlot() [1/2]
IInputSlot * GetIInputSlot (unsigned int index)
Definition at line 268 of file SubgraphView.cpp.
 {
     return m_IInputSlots.at(index);
 }
GetIInputSlot() [2/2]
const IInputSlot * GetIInputSlot (unsigned int index) const
Definition at line 258 of file SubgraphView.cpp.
 {
     return m_IInputSlots.at(index);
 }
GetIInputSlots()
const SubgraphView::IInputSlots & GetIInputSlots () const
Definition at line 238 of file SubgraphView.cpp.
 {
     return m_IInputSlots;
 }
Referenced by SubgraphView::GetWorkingCopy(), SubgraphViewSelector::SelectSubgraphs(), SubgraphView::SubstituteSubgraph(), and OptimizationViews::Validate().
GetIOutputSlot() [1/2]
IOutputSlot * GetIOutputSlot (unsigned int index)
Definition at line 288 of file SubgraphView.cpp.
 {
     return m_IOutputSlots.at(index);
 }
GetIOutputSlot() [2/2]
const IOutputSlot * GetIOutputSlot (unsigned int index) const
Definition at line 278 of file SubgraphView.cpp.
 {
     return m_IOutputSlots.at(index);
 }
Referenced by TosaRefBackend::OptimizeSubgraphView().
GetIOutputSlots()
const SubgraphView::IOutputSlots & GetIOutputSlots () const
Definition at line 248 of file SubgraphView.cpp.
 {
     return m_IOutputSlots;
 }
Referenced by SubgraphView::GetWorkingCopy(), SubgraphView::SubstituteSubgraph(), and OptimizationViews::Validate().
GetNumInputSlots()
unsigned int GetNumInputSlots () const
Definition at line 293 of file SubgraphView.cpp.
 {
     return armnn::numeric_cast<unsigned int>(m_IInputSlots.size());
 }
Referenced by TosaRefBackend::OptimizeSubgraphView().
GetNumOutputSlots()
unsigned int GetNumOutputSlots () const
Definition at line 298 of file SubgraphView.cpp.
 {
     return armnn::numeric_cast<unsigned int>(m_IOutputSlots.size());
 }
Referenced by TosaRefBackend::OptimizeSubgraphView().
GetOriginalInputSlots()
const SubgraphView::IInputSlots & GetOriginalInputSlots () const
These methods should be called on a working copy subgraph created from GetWorkingCopy.
They return pointers to the input and output Slots belonging to the original SubgraphView that the working copy was created from. This may be used to find the original TensorInfo of connected boundary OutputSlots.
Definition at line 638 of file SubgraphView.cpp.
 {
     if (!p_WorkingCopyImpl)
     {
         throw NullPointerException("The SubgraphView calling GetOriginalInputSlots is not a working copy. "
                                    "Call this function on SubgraphView returned from SubgraphView::GetWorkingCopy()");
     }
     if (!p_WorkingCopyImpl->m_OriginalSubgraphView)
     {
         throw NullPointerException("The working copy SubgraphView pointer to its original SubgraphView is null.");
     }
     return p_WorkingCopyImpl->m_OriginalSubgraphView->GetIInputSlots();
 }
GetOriginalOutputSlots()
const SubgraphView::IOutputSlots & GetOriginalOutputSlots () const
Definition at line 651 of file SubgraphView.cpp.
 {
     if (!p_WorkingCopyImpl)
     {
         throw NullPointerException("The SubgraphView calling GetOriginalOutputSlots is not a working copy. "
                                    "Call this function on SubgraphView returned from SubgraphView::GetWorkingCopy()");
     }
     if (!p_WorkingCopyImpl->m_OriginalSubgraphView)
     {
         throw NullPointerException("The working copy SubgraphView pointer to its original SubgraphView is null.");
     }
     return p_WorkingCopyImpl->m_OriginalSubgraphView->GetIOutputSlots();
 }
GetWorkingCopy()
SubgraphView GetWorkingCopy () const
This method returns a copy of the original SubgraphView provided by OptimizeSubgraphView with a separate underlying graph from the main ArmNN graph.
Backend users should edit this working copy and then add it as a SubstitutionPair, along with original SubgraphView, to the OptimizationViews returned by OptimizeSubgraphView. ArmNN will then decide on whether or not to carry out Substitution of the two SubgraphViews.
Definition at line 429 of file SubgraphView.cpp.
 {
     if (p_WorkingCopyImpl)
     {
         throw Exception("The SubgraphView calling GetWorkingCopy() is already a working copy. This function "
                         "should be called on original SubgraphView obtained from OptimizeSubgraphView()");
     }
     // Create a cut down SubgraphView with underlying graph containing only the relevant layers.
     // It needs its own underlying layers so that they can be replaced safely.
     auto ptr = std::make_shared<SubgraphViewWorkingCopy>(Graph(), shared_from_this());
     std::unordered_map<const IConnectableLayer*, IConnectableLayer*> originalToClonedLayerMap;
     std::list<armnn::IConnectableLayer*> originalSubgraphLayers = GetIConnectableLayers();
     for (auto&& originalLayer : originalSubgraphLayers)
     {
         Layer* const layer = PolymorphicDowncast<const Layer*>(originalLayer)->Clone(ptr->m_Graph);
         originalToClonedLayerMap.emplace(originalLayer, layer);
     }
     SubgraphView::IInputSlots workingCopyInputs;
     // Add IInputSlots to workingCopy
     for (auto originalSubgraphInputSlot : GetIInputSlots())
     {
         const IConnectableLayer& originalSubgraphLayer =
                 PolymorphicDowncast<InputSlot*>(originalSubgraphInputSlot)->GetOwningLayer();
         auto* clonedLayer = originalToClonedLayerMap[&originalSubgraphLayer];
         workingCopyInputs.push_back(&clonedLayer->GetInputSlot(originalSubgraphInputSlot->GetSlotIndex()));
     }
     for (auto originalSubgraphLayer : originalSubgraphLayers)
     {
         IConnectableLayer* const clonedLayer = originalToClonedLayerMap[originalSubgraphLayer];
         // OutputLayers have no OutputSlots to be connected
         if (clonedLayer->GetType() != LayerType::Output)
         {
             // connect all cloned layers as per original subgraph
             for (unsigned int i = 0; i < clonedLayer->GetNumOutputSlots(); i++)
             {
                 auto& originalOutputSlot = originalSubgraphLayer->GetOutputSlot(i);
                 auto& clonedOutputSlot   = clonedLayer->GetOutputSlot(i);
                 for (unsigned int j = 0; j < originalOutputSlot.GetNumConnections(); j++)
                 {
                     // nextLayer is the layer with IInputSlot connected to IOutputSlot we are working on
                     const IConnectableLayer& nextLayerOnOriginalSubgraph =
                             originalOutputSlot.GetConnection(j)->GetOwningIConnectableLayer();
                     // Check the layer is in our map and so has a clonedLayer
                     if (originalToClonedLayerMap.find(&nextLayerOnOriginalSubgraph) != originalToClonedLayerMap.end())
                     {
                         auto* nextLayerOnClonedSubgraph = originalToClonedLayerMap[&nextLayerOnOriginalSubgraph];
                         auto index = PolymorphicDowncast<OutputSlot*>(
                                 &originalOutputSlot)->GetConnection(j)->GetSlotIndex();
                         IInputSlot& inputSlot = nextLayerOnClonedSubgraph->GetInputSlot(index);
                         // Then make the connection
                         clonedOutputSlot.Connect(inputSlot);
                     }
                 }
                 // Copy the tensorInfo to the clonedOutputSlot
                 clonedOutputSlot.SetTensorInfo(originalOutputSlot.GetTensorInfo());
             }
         }
     }
     SubgraphView::IOutputSlots workingCopyOutputs;
     // Add IOutputSlots to workingCopy
     for (auto outputSlot : GetIOutputSlots())
     {
         auto outputSlotIndex = outputSlot->CalculateIndexOnOwner();
         const IConnectableLayer& originalSubgraphLayer = outputSlot->GetOwningIConnectableLayer();
         // OutputLayers have no OutputSlots to be connected
         if (originalSubgraphLayer.GetType() != LayerType::Output)
         {
             IConnectableLayer* clonedLayer = originalToClonedLayerMap[&originalSubgraphLayer];
             // Add the OutputSlot of clonedLayer to WorkingCopy OutputSlots
             workingCopyOutputs.push_back(&clonedLayer->GetOutputSlot(outputSlotIndex));
         }
     }
     SubgraphView::IConnectableLayers workingCopyLayers;
     for (auto& pair : originalToClonedLayerMap)
     {
         workingCopyLayers.push_back(pair.second);
     }
     return {std::move(workingCopyLayers),
             std::move(workingCopyInputs),
             std::move(workingCopyOutputs),
             ptr};
 }
References Layer::Clone(), SubgraphView::GetIConnectableLayers(), SubgraphView::GetIInputSlots(), SubgraphView::GetIOutputSlots(), IConnectableLayer::GetNumOutputSlots(), IConnectableLayer::GetOutputSlot(), IConnectableLayer::GetType(), and armnn::Output.
operator=()
SubgraphView & operator= (SubgraphView && other)
Move-assignment operator.
Definition at line 197 of file SubgraphView.cpp.
 {
     m_InputSlots = std::move(other.m_InputSlots);
     m_IInputSlots = std::move(other.m_IInputSlots);
     m_OutputSlots = std::move(other.m_OutputSlots);
     m_IOutputSlots = std::move(other.m_IOutputSlots);
     m_Layers = std::move(other.m_Layers);
     m_IConnectableLayers = std::move(other.m_IConnectableLayers);
     CheckSubgraph();
     return *this;
 }
SubstituteSubgraph() [1/2]
void SubstituteSubgraph (SubgraphView & patternSubgraph, const SubgraphView & substituteSubgraph)
Definition at line 572 of file SubgraphView.cpp.
 {
     if (!p_WorkingCopyImpl)
     {
         throw NullPointerException("The SubgraphView calling SubstituteSubgraphView is not a working copy. "
                                    "Call this function on SubgraphView returned from SubgraphView::GetWorkingCopy()");
     }
     auto numPatternInputs = patternSubgraph.GetIInputSlots().size();
     auto numSubInputs = substituteSubgraph.GetIInputSlots().size();
     if (numPatternInputs != numSubInputs)
     {
         throw armnn::InvalidArgumentException(
            fmt::format("Number of InputSlots on substitute SubgraphView ({}) must equal the number of"
                        " InputSlots on pattern SubgraphView ({})",
                        numSubInputs,
                        numPatternInputs));
     }
     auto numPatternOutputs = patternSubgraph.GetIOutputSlots().size();
     auto numSubOutputs = substituteSubgraph.GetIOutputSlots().size();
     if (numPatternOutputs != numSubOutputs)
     {
         throw armnn::InvalidArgumentException(
            fmt::format("Number of OutputSlots on substitute SubgraphView ({}) must equal the number of"
                        " OutputSlots on pattern SubgraphView ({})",
                        numSubOutputs,
                        numPatternOutputs));
     }
     // Add substitute layer to the Main graph i.e. graph in p_WorkingCopyImpl
     auto workingCopyGraph = &p_WorkingCopyImpl->m_Graph;
     substituteSubgraph.ForEachIConnectableLayer([workingCopyGraph](IConnectableLayer* iConnectableLayer)
{
                                                     // Search WorkingCopy Graph for substituteLayer and add if missing
                                                     if (std::find(std::begin(workingCopyGraph->m_Layers),
                                                                   std::end(workingCopyGraph->m_Layers),
                                                                   iConnectableLayer) ==
                                                         std::end(workingCopyGraph->m_Layers))
{
                                                         auto layer = PolymorphicDowncast<Layer*>(iConnectableLayer);
                                                         layer->Reparent(*workingCopyGraph,
                                                                         (workingCopyGraph->m_Layers).end());
                                                         workingCopyGraph->m_LayersInOrder = false;
                                                     }
                                                 });
     // Replace the old connections with connections to new layer
     workingCopyGraph->ReplaceSubgraphConnections(patternSubgraph, substituteSubgraph);
     // Update input/outputSlot pointers
     UpdateSubgraphViewSlotPointers(patternSubgraph, substituteSubgraph);
     // Delete the old layers.
     workingCopyGraph->EraseSubgraphLayers(patternSubgraph);
     // Sort
     workingCopyGraph->TopologicalSort();
     // Update SubgraphView layer pointers to match those of the internal WorkingCopy layer pointers
     m_IConnectableLayers = IConnectableLayers{ workingCopyGraph->m_Layers.begin(),
                                                workingCopyGraph->m_Layers.end() };
 }
References SubgraphView::ForEachIConnectableLayer(), SubgraphView::GetIInputSlots(), and SubgraphView::GetIOutputSlots().
SubstituteSubgraph() [2/2]
void SubstituteSubgraph (SubgraphView & subgraph, IConnectableLayer * substituteLayer)
These methods should be called on a working copy subgraph created from GetWorkingCopy.
They take a SubgraphView pattern to replace and the substitute layer or subgraphView to substitute in.
Definition at line 530 of file SubgraphView.cpp.
 {
     ARMNN_ASSERT(substituteLayer != nullptr);
     SubgraphView substituteSubgraph(substituteLayer);
     SubstituteSubgraph(subgraph, substituteSubgraph);
 }
References ARMNN_ASSERT.
Member Data Documentation
layers
OutputSlots Layers&& layers
Definition at line 74 of file SubgraphView.hpp.
outputs
OutputSlots&& outputs
Definition at line 74 of file SubgraphView.hpp.
The documentation for this class was generated from the following files:
include/armnn/backends/SubgraphView.hpp
src/armnn/SubgraphView.cpp