ArmNN: OptimizerOptionsOpaque Class Reference
OptimizerOptionsOpaque Class Reference
#include <INetwork.hpp>
Public Member Functions
OptimizerOptionsOpaque ()
OptimizerOptionsOpaque (const OptimizerOptionsOpaque &other)
~OptimizerOptionsOpaque ()
OptimizerOptionsOpaque (const OptimizerOptions &OptimizerStruct)
OptimizerOptionsOpaque & operator= (OptimizerOptionsOpaque other)
OptimizerOptionsOpaque (bool reduceFp32ToFp16, bool debug, bool reduceFp32ToBf16, bool importEnabled, ModelOptions modelOptions={}, bool exportEnabled=false, bool debugToFile=false)
OptimizerOptionsOpaque (bool reduceFp32ToFp16, bool debug, bool reduceFp32ToBf16=false, ShapeInferenceMethod shapeInferenceMethod=armnn::ShapeInferenceMethod::ValidateOnly, bool importEnabled=false, ModelOptions modelOptions={}, bool exportEnabled=false, bool debugToFile=false, bool allowExpandedDims=false)
const std::string ToString () const
bool GetProfilingEnabled () const
bool GetImportEnabled () const
bool GetExportEnabled () const
bool GetReduceFp32ToFp16 () const
bool GetReduceFp32ToBf16 () const
bool GetDebugEnabled () const
bool GetDebugToFileEnabled () const
bool GetAllowExpandedDims () const
armnn::ModelOptions GetModelOptions () const
armnn::ShapeInferenceMethod GetShapeInferenceMethod () const
void SetImportEnabled (bool ImportState)
void SetExportEnabled (bool ExportState)
void SetProfilingEnabled (bool ProfilingState)
void SetDebugEnabled (bool DebugState)
void SetDebugToFileEnabled (bool DebugFileState)
void SetReduceFp32ToFp16 (bool ReduceFp32ToFp16State)
void SetShapeInferenceMethod (armnn::ShapeInferenceMethod ShapeInferenceMethodType)
void AddModelOption (armnn::BackendOptions)
void SetAllowExpandedDims (bool ExpandedDimsAllowed)
Detailed Description
Examples
CustomMemoryAllocatorSample.cpp.
Definition at line 260 of file INetwork.hpp.
Constructor & Destructor Documentation
OptimizerOptionsOpaque() [1/5]
OptimizerOptionsOpaque ()
Definition at line 48 of file Network.cpp.
         : p_OptimizerOptionsImpl(std::make_unique<OptimizerOptionsOpaqueImpl>())
 {
 }
OptimizerOptionsOpaque() [2/5]
OptimizerOptionsOpaque (const OptimizerOptionsOpaque & other)
Definition at line 53 of file Network.cpp.
         : p_OptimizerOptionsImpl(std::make_unique<OptimizerOptionsOpaqueImpl>(*other.p_OptimizerOptionsImpl))
 {
 }
~OptimizerOptionsOpaque()
~OptimizerOptionsOpaque () default
OptimizerOptionsOpaque() [3/5]
OptimizerOptionsOpaque (const OptimizerOptions & OptimizerStruct)
Definition at line 80 of file Network.cpp.
     : p_OptimizerOptionsImpl(std::make_unique<OptimizerOptionsOpaqueImpl>())
 {
     p_OptimizerOptionsImpl->m_ImportEnabled = OptimizerStruct.m_ImportEnabled;
     p_OptimizerOptionsImpl->m_shapeInferenceMethod = OptimizerStruct.m_shapeInferenceMethod;
     p_OptimizerOptionsImpl->m_ModelOptions = OptimizerStruct.m_ModelOptions;
     p_OptimizerOptionsImpl->m_ProfilingEnabled = OptimizerStruct.m_ProfilingEnabled;
     p_OptimizerOptionsImpl->m_DebugToFile = OptimizerStruct.m_DebugToFile;
     p_OptimizerOptionsImpl->m_Debug = OptimizerStruct.m_Debug;
     p_OptimizerOptionsImpl->m_ReduceFp32ToFp16 = OptimizerStruct.m_ReduceFp32ToFp16;
     p_OptimizerOptionsImpl->m_ExportEnabled = OptimizerStruct.m_ExportEnabled;
     p_OptimizerOptionsImpl->m_AllowExpandedDims = OptimizerStruct.m_AllowExpandedDims;
     p_OptimizerOptionsImpl->m_ReduceFp32ToBf16 = OptimizerStruct.m_ReduceFp32ToBf16;
 }
References OptimizerOptions::m_AllowExpandedDims, OptimizerOptions::m_Debug, OptimizerOptions::m_DebugToFile, OptimizerOptions::m_ExportEnabled, OptimizerOptions::m_ImportEnabled, OptimizerOptions::m_ModelOptions, OptimizerOptions::m_ProfilingEnabled, OptimizerOptions::m_ReduceFp32ToBf16, OptimizerOptions::m_ReduceFp32ToFp16, and OptimizerOptions::m_shapeInferenceMethod.
OptimizerOptionsOpaque() [4/5]
OptimizerOptionsOpaque (bool reduceFp32ToFp16, bool debug, bool reduceFp32ToBf16, bool importEnabled, ModelOptions modelOptions = {}, bool exportEnabled = false, bool debugToFile = false)
Definition at line 60 of file Network.cpp.
         : p_OptimizerOptionsImpl(std::make_unique<OptimizerOptionsOpaqueImpl>(reduceFp32ToFp16, debug, reduceFp32ToBf16,
                                                                               importEnabled, modelOptions,
                                                                               exportEnabled, debugToFile))
 {
 }
References armnn::debug.
OptimizerOptionsOpaque() [5/5]
OptimizerOptionsOpaque (bool reduceFp32ToFp16, bool debug, bool reduceFp32ToBf16 = false, ShapeInferenceMethod shapeInferenceMethod = armnn::ShapeInferenceMethod::ValidateOnly, bool importEnabled = false, ModelOptions modelOptions = {}, bool exportEnabled = false, bool debugToFile = false, bool allowExpandedDims = false)
Definition at line 69 of file Network.cpp.
         : p_OptimizerOptionsImpl(std::make_unique<OptimizerOptionsOpaqueImpl>(reduceFp32ToFp16, debug, reduceFp32ToBf16,
                                                                               shapeInferenceMethod, importEnabled,
                                                                               modelOptions, exportEnabled,
                                                                               debugToFile, allowExpandedDims))
 {
 }
References armnn::debug.
Member Function Documentation
AddModelOption()
void AddModelOption (armnn::BackendOptions NewModelOption)
Definition at line 150 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_ModelOptions.push_back(NewModelOption);
 }
Referenced by ArmnnDriverImpl::PrepareArmnnModel(), and ArmnnDriverImpl::PrepareArmnnModelFromCache().
GetAllowExpandedDims()
bool GetAllowExpandedDims () const
Definition at line 190 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_AllowExpandedDims;
 }
Referenced by OptimizerOptionsOpaque::operator=().
GetDebugEnabled()
bool GetDebugEnabled () const
Definition at line 180 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_Debug;
 }
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetDebugToFileEnabled()
bool GetDebugToFileEnabled () const
Definition at line 185 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_DebugToFile;
 }
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetExportEnabled()
bool GetExportEnabled () const
Definition at line 165 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_ExportEnabled;
 };
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetImportEnabled()
bool GetImportEnabled () const
Definition at line 160 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_ImportEnabled;
 };
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetModelOptions()
armnn::ModelOptions GetModelOptions () const
Definition at line 195 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_ModelOptions;
 }
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetProfilingEnabled()
bool GetProfilingEnabled () const
Definition at line 155 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_ProfilingEnabled;
 };
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetReduceFp32ToBf16()
bool GetReduceFp32ToBf16 () const
Definition at line 175 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_ReduceFp32ToBf16;
 }
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetReduceFp32ToFp16()
bool GetReduceFp32ToFp16 () const
Definition at line 170 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_ReduceFp32ToFp16;
 };
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
GetShapeInferenceMethod()
armnn::ShapeInferenceMethod GetShapeInferenceMethod () const
Definition at line 200 of file Network.cpp.
 {
     return p_OptimizerOptionsImpl->m_shapeInferenceMethod;
 }
Referenced by OptimizerOptionsOpaque::operator=(), and armnn::Optimize().
operator=()
OptimizerOptionsOpaque & operator= (OptimizerOptionsOpaque other)
Definition at line 95 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_ImportEnabled = other.GetImportEnabled();
     p_OptimizerOptionsImpl->m_shapeInferenceMethod = other.GetShapeInferenceMethod();
     p_OptimizerOptionsImpl->m_ModelOptions = other.GetModelOptions();
     p_OptimizerOptionsImpl->m_ProfilingEnabled = other.GetProfilingEnabled();
     p_OptimizerOptionsImpl->m_DebugToFile = other.GetDebugToFileEnabled();
     p_OptimizerOptionsImpl->m_Debug = other.GetDebugEnabled();
     p_OptimizerOptionsImpl->m_ReduceFp32ToFp16 = other.GetReduceFp32ToFp16();
     p_OptimizerOptionsImpl->m_ExportEnabled = other.GetExportEnabled();
     p_OptimizerOptionsImpl->m_AllowExpandedDims = other.GetAllowExpandedDims();
     p_OptimizerOptionsImpl->m_ReduceFp32ToBf16 = other.GetReduceFp32ToBf16();
     return *this;
 }
References OptimizerOptionsOpaque::GetAllowExpandedDims(), OptimizerOptionsOpaque::GetDebugEnabled(), OptimizerOptionsOpaque::GetDebugToFileEnabled(), OptimizerOptionsOpaque::GetExportEnabled(), OptimizerOptionsOpaque::GetImportEnabled(), OptimizerOptionsOpaque::GetModelOptions(), OptimizerOptionsOpaque::GetProfilingEnabled(), OptimizerOptionsOpaque::GetReduceFp32ToBf16(), OptimizerOptionsOpaque::GetReduceFp32ToFp16(), and OptimizerOptionsOpaque::GetShapeInferenceMethod().
SetAllowExpandedDims()
void SetAllowExpandedDims (bool ExpandedDimsAllowed)
Definition at line 145 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_AllowExpandedDims = ExpandedDimsAllowed;
 }
SetDebugEnabled()
void SetDebugEnabled (bool DebugState)
Definition at line 125 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_Debug = DebugState;
 }
SetDebugToFileEnabled()
void SetDebugToFileEnabled (bool DebugFileState)
Definition at line 130 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_DebugToFile = DebugFileState;
 }
SetExportEnabled()
void SetExportEnabled (bool ExportState)
Definition at line 115 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_ExportEnabled = ExportState;
 }
SetImportEnabled()
void SetImportEnabled (bool ImportState)
Examples
CustomMemoryAllocatorSample.cpp.
Definition at line 110 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_ImportEnabled = ImportState;
 }
SetProfilingEnabled()
void SetProfilingEnabled (bool ProfilingState)
Definition at line 120 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_ProfilingEnabled = ProfilingState;
 }
Referenced by ArmnnDriverImpl::PrepareArmnnModel(), and ArmnnDriverImpl::PrepareArmnnModelFromCache().
SetReduceFp32ToFp16()
void SetReduceFp32ToFp16 (bool ReduceFp32ToFp16State)
Definition at line 135 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_ReduceFp32ToFp16 = ReduceFp32ToFp16State;
 }
Referenced by ArmnnDriverImpl::PrepareArmnnModel(), and ArmnnDriverImpl::PrepareArmnnModelFromCache().
SetShapeInferenceMethod()
void SetShapeInferenceMethod (armnn::ShapeInferenceMethod ShapeInferenceMethodType)
Definition at line 140 of file Network.cpp.
 {
     p_OptimizerOptionsImpl->m_shapeInferenceMethod = ShapeInferenceMethodType;
 }
ToString()
const std::string ToString () const
Definition at line 205 of file Network.cpp.
 {
     std::stringstream stream;
     stream << "OptimizerOptions: \n";
     stream << "\tReduceFp32ToFp16: " << p_OptimizerOptionsImpl->m_ReduceFp32ToFp16 << "\n";
     stream << "\tReduceFp32ToBf16: " << p_OptimizerOptionsImpl->m_ReduceFp32ToBf16 << "\n";
     stream << "\tDebug: " << p_OptimizerOptionsImpl->m_Debug << "\n";
     stream << "\tDebug to file: " << p_OptimizerOptionsImpl->m_DebugToFile << "\n";
     stream << "\tShapeInferenceMethod: " <<
            (p_OptimizerOptionsImpl->m_shapeInferenceMethod == ShapeInferenceMethod::ValidateOnly ?
            "ValidateOnly" : "InferAndValidate") << "\n";
     stream << "\tImportEnabled: " << p_OptimizerOptionsImpl->m_ImportEnabled << "\n";
     stream << "\tExportEnabled: " << p_OptimizerOptionsImpl->m_ExportEnabled << "\n";
     stream << "\tProfilingEnabled: " << p_OptimizerOptionsImpl->m_ProfilingEnabled << "\n";
     stream << "\tAllowExpandedDims: " << p_OptimizerOptionsImpl->m_AllowExpandedDims << "\n";
     stream << "\tModelOptions: \n";
     for (auto optionsGroup : p_OptimizerOptionsImpl->m_ModelOptions)
     {
         for (size_t i=0; i < optionsGroup.GetOptionCount(); i++)
         {
             const armnn::BackendOptions::BackendOption option = optionsGroup.GetOption(i);
             stream << "\t\tBackend: "  << optionsGroup.GetBackendId() << "\n"
                    << "\t\t\tOption: " << option.GetName() << "\n"
                    << "\t\t\tValue: "  << std::string(option.GetValue().ToString()) << "\n";
         }
     }
     return stream.str();
 }
References BackendOptions::BackendOption::GetName(), BackendOptions::BackendOption::GetValue(), BackendOptions::Var::ToString(), and armnn::ValidateOnly.
Referenced by armnn::Optimize().
The documentation for this class was generated from the following files:
include/armnn/INetwork.hpp
src/armnn/Network.cpp