ArmNN: OptimizationResult Struct Reference
OptimizationResult Struct Reference
#include <Network.hpp>
Public Member Functions
OptimizationResult (bool warning, bool error)
OptimizationResult ()
bool IsOk () const
bool IsWarningOnly () const
bool IsError () const
Public Attributes
bool m_Warning
bool m_Error
Detailed Description
Definition at line 249 of file Network.hpp.
Constructor & Destructor Documentation
OptimizationResult() [1/2]
OptimizationResult (bool warning, bool error) inline
Definition at line 254 of file Network.hpp.
         : m_Warning(warning), m_Error(error)
     {}
References armnn::error, and armnn::warning.
OptimizationResult() [2/2]
OptimizationResult () inline
Definition at line 258 of file Network.hpp.
         : OptimizationResult(false, false)
     {}
Member Function Documentation
IsError()
bool IsError () const inline
Definition at line 266 of file Network.hpp.
     { return m_Error; }
Referenced by armnn::AssignBackendsIConnectable().
IsOk()
bool IsOk () const inline
Definition at line 262 of file Network.hpp.
     { return !m_Warning && !m_Error; }
Referenced by armnn::AssignBackendsIConnectable().
IsWarningOnly()
bool IsWarningOnly () const inline
Definition at line 264 of file Network.hpp.
     { return m_Warning && !m_Error; }
Referenced by armnn::AssignBackendsIConnectable().
Member Data Documentation
m_Error
bool m_Error
Definition at line 252 of file Network.hpp.
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssignBackends(), armnn::AssignBackendsIConnectable(), armnn::Optimize(), armnn::ReturnWithError(), and armnn::SelectTensorHandleStrategy().
m_Warning
bool m_Warning
Definition at line 251 of file Network.hpp.
The documentation for this struct was generated from the following file:
src/armnn/Network.hpp