Arm NN: src/backends/tosaCommon/operatorMappings/HardSwishOperator.cpp File Reference
HardSwishOperator.cpp File Reference
#include "HardSwishOperator.hpp"
#include <gemmlowp/fixedpoint.h>
Functions
std::vector< int16_t > getTosaConstHardSwish8bitTable (float inputScale, int32_t inputZp, float outputScale, int32_t outputZp)
TosaSerializationBasicBlock * ConvertHardSwishToTosaOperator (const Layer *layer, const std::vector< const TensorInfo * > &inputs, const std::vector< const TensorInfo * > &outputs, const ActivationDescriptor *desc)
Function Documentation
ConvertHardSwishToTosaOperator()
TosaSerializationBasicBlock* ConvertHardSwishToTosaOperator (const Layer * layer, const std::vector< const TensorInfo * > & inputs, const std::vector< const TensorInfo * > & outputs, const ActivationDescriptor * desc)
Definition at line 160 of file HardSwishOperator.cpp.
 {
     if (inputs.size() != 1)
     {
         throw armnn::Exception("ConvertHardSwishToTosaOperator: 1 input tensors required.");
     }
     if (outputs.size() != 1)
     {
         throw armnn::Exception("ConvertHardSwishToTosaOperator: 1 output tensor required.");
     }
     if (desc->m_Function != ActivationFunction::HardSwish)
     {
         throw armnn::Exception("ConvertHardSwishToTosaOperator ActivationDescriptor only supports function HardSwish.");
     }
     std::string inputName  = std::string("input_");
     std::string outputName = std::string("output0_");
     std::string blockName  = std::string("Op_HARDSWISH_block_") + GetUniqueTosaMappingID();
     // If a layer is present then the block will be used for execution, so input and output names need to be determined
     // using the previous and following layers so the graph is connected correctly. For validation this doesn't matter.
     if (layer != nullptr)
     {
         inputName  = GenerateUniqueInputName(layer->GetInputSlot(0));
         outputName = GenerateUniqueOutputName(*layer);
     }
     std::vector<TosaSerializationTensor*> tensors;
     std::vector<TosaSerializationOperator*> operators;
     DataType inputDType = inputs[0]->GetDataType();
     bool isInt8 = (inputDType == DataType::QAsymmS8 || inputDType == DataType::QSymmS8);
     if (isInt8)
     {
         float inputScale = inputs[0]->GetQuantizationScale();
         float outputScale = outputs[0]->GetQuantizationScale();
         int32_t inputZp = inputs[0]->GetQuantizationOffset();
         int32_t outputZp = outputs[0]->GetQuantizationOffset();
         TosaTableAttribute attribute(
             getTosaConstHardSwish8bitTable(inputScale, inputZp, outputScale, outputZp));
         operators.push_back(new TosaSerializationOperator(tosa::Op_TABLE,
                                                           Attribute_TableAttribute,
                                                           &attribute,
                                                           {inputName},
                                                           {outputName}));
     }
     else
     {
         throw Exception("ConvertHardSwishToTosaOperator() type currently unimplemented.");
     }
     // Only add input tensors if connected layer is an input layer.
     // As intermediate or constant tensors will be created separately.
     // There also can't be duplicate tensor.
     std::vector<int32_t> inputShape0;
     DType inputDType0 = ArmNNToDType(inputs[0]->GetDataType());
     if(inputName.find("input_") != std::string::npos)
     {
         inputShape0 = GetTosaTensorShape(inputs[0]->GetShape());
         tensors.push_back(new TosaSerializationTensor(inputName, inputShape0, inputDType0, {}));
     }
     std::vector<int32_t> outputShape0 = GetTosaTensorShape(outputs[0]->GetShape());
     DType outputDType0 = ArmNNToDType(outputs[0]->GetDataType());
     tensors.push_back(new TosaSerializationTensor(outputName, outputShape0, outputDType0, {}));
     // operatorInputNames/operatorOutputNames ends up being the same as
     // blockInputNames/blockOutputNames for one-to-one ArmNN to Tosa mappings
     return new TosaSerializationBasicBlock(blockName,      // name
                                            mainName,       // region name
                                            operators,      // operators
                                            tensors,        // tensors
                                            {inputName},    // inputs
                                            {outputName});  // outputs
 }
References ArmNNToDType(), GenerateUniqueInputName(), GenerateUniqueOutputName(), Layer::GetInputSlot(), getTosaConstHardSwish8bitTable(), GetTosaTensorShape(), GetUniqueTosaMappingID(), and ActivationDescriptor::m_Function.
Referenced by GetTosaMapping().
getTosaConstHardSwish8bitTable()
std::vector<int16_t> getTosaConstHardSwish8bitTable (float inputScale, int32_t inputZp, float outputScale, int32_t outputZp)
Definition at line 90 of file HardSwishOperator.cpp.
 {
     const float hiresInputScale = (1.0f / 128.0f) * inputScale;
     const float outputMultiplier = hiresInputScale / outputScale;
     int outputMultiplierExponent;
     int16_t outputMultiplierFixedpointInt16;
     int32_t outputMultiplierFixedpointInt32;
     quantizeMultiplier(outputMultiplier, &outputMultiplierFixedpointInt32, &outputMultiplierExponent);
     downScaleInt32ToInt16Multiplier(outputMultiplierFixedpointInt32, &outputMultiplierFixedpointInt16);
     ARMNN_THROW_INVALIDARG_IF_FALSE(outputMultiplierExponent <= 0);
     const float reluishScale = 3.0f / 32768.0f;
     const float reluishMultiplier = hiresInputScale / reluishScale;
     int reluishMultiplierExponent;
     int16_t reluishMultiplierFixedpointInt16;
     int32_t reluishMultiplierFixedpointInt32;
     quantizeMultiplier(reluishMultiplier, &reluishMultiplierFixedpointInt32, &reluishMultiplierExponent);
     downScaleInt32ToInt16Multiplier(reluishMultiplierFixedpointInt32, &reluishMultiplierFixedpointInt16);
     std::vector<int16_t> table;
     table.reserve(256);
     for (int32_t i = -128; i < 128; i++)
     {
         const int16_t inputValue = static_cast<int16_t>(i - inputZp);
         const int16_t inputValueHiresInputScale = static_cast<int16_t>(inputValue * (1 << 7));
         int16_t reluishValue = inputValueHiresInputScale;
         if (reluishMultiplierExponent > 0)
         {
             reluishValue = gemmlowp::ShiftLeft(reluishValue, reluishMultiplierExponent - 1);
         }
         reluishValue = gemmlowp::SaturatingRoundingDoublingHighMul(reluishValue, reluishMultiplierFixedpointInt16);
         if (reluishMultiplierExponent > 0)
         {
             reluishValue = gemmlowp::ShiftLeft(reluishValue, 1);
         }
         else if (reluishMultiplierExponent < 0)
         {
             reluishValue = gemmlowp::RoundingDivideByPOT(reluishValue, -reluishMultiplierExponent);
         }
         reluishValue = static_cast<int16_t>((reluishValue + (1 << 15)) >> 1);
         const int16_t inputValPreshiftOutputScale =
             gemmlowp::SaturatingRoundingDoublingHighMul(inputValueHiresInputScale, outputMultiplierFixedpointInt16);
         const int16_t preshiftOutputValue = saturatingDoublingHighMul(reluishValue, inputValPreshiftOutputScale);
         int16_t outputValue = gemmlowp::RoundingDivideByPOT(preshiftOutputValue, -outputMultiplierExponent);
         outputValue = static_cast<int16_t>(outputValue + outputZp);
         outputValue = std::min<int16_t>(outputValue, std::numeric_limits<int8_t>::max());
         outputValue = std::max<int16_t>(outputValue, std::numeric_limits<int8_t>::min());
         table.push_back(outputValue);
     }
     return table;
 }
Referenced by ConvertHardSwishToTosaOperator().