Arm NN: DotBase Class Reference
DotBase Class Reference
#include <DotSerializer.hpp>
Public Member Functions
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 17 of file DotSerializer.hpp.
Constructor & Destructor Documentation
DotBase()
DotBase (std::ostream & stream) inline explicit
Definition at line 20 of file DotSerializer.hpp.
         : m_Stream(stream) {}
Member Function Documentation
GetStream()
std::ostream& GetStream () inline
Definition at line 23 of file DotSerializer.hpp.
 { return m_Stream; }
Referenced by DotAttributeSet::DotAttributeSet(), DotDefaults::DotDefaults(), DotEdge::DotEdge(), DotGraph::DotGraph(), DotNode::DotNode(), HtmlFont::HtmlFont(), HtmlSection::HtmlSection(), HtmlSimpleTag::HtmlSimpleTag(), DotAttributeSet::~DotAttributeSet(), DotDefaults::~DotDefaults(), DotEdge::~DotEdge(), DotGraph::~DotGraph(), DotNode::~DotNode(), HtmlFont::~HtmlFont(), HtmlSection::~HtmlSection(), HtmlSimpleTag::~HtmlSimpleTag(), and NodeContent::~NodeContent().
The documentation for this class was generated from the following file:
src/armnnUtils/DotSerializer.hpp