Arm NN: InputSlot Class Reference
InputSlot Class Reference final
#include <Layer.hpp>
Public Member Functions
InputSlot (Layer &owner, unsigned int slotIndex)
~InputSlot ()
Layer & GetOwningLayer () const
unsigned int GetSlotIndex () const override
const OutputSlot * GetConnectedOutputSlot () const
OutputSlot * GetConnectedOutputSlot ()
const IConnectableLayer & GetOwningIConnectableLayer () const override
IConnectableLayer & GetOwningIConnectableLayer () override
void SetConnection (OutputSlot *source)
Links the slot to an output slot or breaks an existing link if passing nullptr.
void Insert (Layer &layer)
const IOutputSlot * GetConnection () const override
IOutputSlot * GetConnection () override
void SetTensorInfo (const TensorInfo tensorInfo) override
Sets the TensorInfo for this InputSlot.
const TensorInfo & GetTensorInfo () const override
Gets the TensorInfo for this InputSlot.
bool IsTensorInfoSet () const override
Returns true if this InputSlot either has an overridden TensorInfo for this InputSlot that was set through a call to SetTensorInfo() or is Connected to an OutputSlot that has its TensorInfo set.
bool IsTensorInfoOverridden () const override
Returns true if this InputSlot has an overridden TensorInfo that was set through a call to SetTensorInfo().
Additional Inherited Members
Protected Member Functions inherited from IInputSlot
~IInputSlot ()
Not user deletable.
Detailed Description
Definition at line 42 of file Layer.hpp.
Constructor & Destructor Documentation
InputSlot()
InputSlot (Layer & owner, unsigned int slotIndex) inline explicit
Definition at line 45 of file Layer.hpp.
     : m_OwningLayer(owner)
     , m_Connection(nullptr)
     , m_SlotIndex(slotIndex)
     {}
~InputSlot()
~InputSlot () inline
Definition at line 199 of file Layer.hpp.
 {
     if (m_Connection != nullptr)
     {
         try
         {
             // Coverity fix: Disconnect() may throw uncaught exceptions.
             m_Connection->Disconnect(*this);
         }
         catch (const std::exception& e)
         {
             // Coverity fix: BOOST_LOG_TRIVIAL (typically used to report errors) may throw an
             // exception of type std::length_error.
             // Using stderr instead in this context as there is no point in nesting try-catch blocks here.
             std::cerr << "WARNING: An error has occurred when disconnecting an input slot: "
                       << e.what() << std::endl;
         }
     }
 }
References OutputSlot::Disconnect().
Member Function Documentation
GetConnectedOutputSlot() [1/2]
OutputSlot* GetConnectedOutputSlot () inline
Definition at line 57 of file Layer.hpp.
 { return m_Connection; }
GetConnectedOutputSlot() [2/2]
const OutputSlot* GetConnectedOutputSlot () const inline
Definition at line 56 of file Layer.hpp.
 { return m_Connection; }
Referenced by armnn::BuildAddMulAddTensorInfoLists(), armnn::ConnectedToLayerType(), armnn::ConnectedToLayerWithNCHW(), ConvertSquaredDifferenceToTosaOperator(), DebugLayer::CreateWorkload(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), GenerateUniqueInputName(), LayerWithParameters< Parameters >::GetConnectedConstantAsInputTensors(), InputSlot::GetConnection(), armnn::GetLayerInOutDatatype(), InputSlot::Insert(), armnn::InsertConvertFp16ToFp32LayersBefore(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::InsertDebugLayerAfter(), Graph::InsertNewLayer(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), TosaRefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), MaxMinIntoBoundedReluImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::Run(), ConvertConstPermuteLayersToConstLayers::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), OptimizeInversePermutesImpl< PermuteType >::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), SquashEqualSiblingsImpl< Comparable >::Run(), TurboConvertConstDequantisationLayersToConstLayersImpl::Run(), AddBroadcastReshapeLayerImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
GetConnection() [1/2]
const IOutputSlot * GetConnection () const inline override virtual
Implements IInputSlot.
Definition at line 219 of file Layer.hpp.
 { return GetConnectedOutputSlot(); }
References InputSlot::GetConnectedOutputSlot().
Referenced by LayerWithParameters< Parameters >::GetConnectedConstantAsInputTensors(), InputSlot::GetTensorInfo(), and InputSlot::IsTensorInfoSet().
GetConnection() [2/2]
IOutputSlot * GetConnection () inline override virtual
Implements IInputSlot.
Definition at line 220 of file Layer.hpp.
 { return GetConnectedOutputSlot(); }
References InputSlot::GetConnectedOutputSlot().
GetOwningIConnectableLayer() [1/2]
const IConnectableLayer & GetOwningIConnectableLayer () const override virtual
Implements IInputSlot.
Definition at line 599 of file Layer.cpp.
 {
     return m_OwningLayer;
 }
GetOwningIConnectableLayer() [2/2]
IConnectableLayer & GetOwningIConnectableLayer () override virtual
Implements IInputSlot.
Definition at line 604 of file Layer.cpp.
 {
     return m_OwningLayer;
 }
GetOwningLayer()
Layer& GetOwningLayer () const inline
Definition at line 53 of file Layer.hpp.
 { return m_OwningLayer; }
Referenced by Graph::AddCompatibilityLayers(), armnn::BuildAddMulAddTensorInfoLists(), armnn::ConnectedToLayerType(), armnn::ConnectedToLayerWithNCHW(), ConvertConstantToTosaOperator(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), GenerateUniqueOutputName(), GetTosaMapping(), Graph::InsertNewLayer(), armnn::RemoveReshapeLayer(), DeleteBroadcastToImpl::Run(), MaxMinIntoBoundedReluImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::Run(), ConvertConstPermuteLayersToConstLayers::Run(), FoldPadIntoConvolution2dImpl::Run(), FoldPadIntoDepthwiseConvolution2dImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), OptimizeInversePermutesImpl< PermuteType >::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), SquashEqualSiblingsImpl< Comparable >::Run(), TurboConvertConstDequantisationLayersToConstLayersImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
GetSlotIndex()
unsigned int GetSlotIndex () const inline override virtual
Implements IInputSlot.
Definition at line 54 of file Layer.hpp.
 { return m_SlotIndex; }
Referenced by Graph::AddCompatibilityLayers(), GetTosaMapping(), and armnn::RemoveReshapeLayer().
GetTensorInfo()
const TensorInfo & GetTensorInfo () const override virtual
Gets the TensorInfo for this InputSlot.
If the InputSlot's TensorInfo has not been set then this will get the TensorInfo from the Connected TensorInfo.
Implements IInputSlot.
Definition at line 614 of file Layer.cpp.
 {
     if (m_OverriddenTensorInfo.has_value())
     {
         return m_OverriddenTensorInfo.value();
     }
     else
     {
         return GetConnection()->GetTensorInfo();
     }
 }
References InputSlot::GetConnection(), and IOutputSlot::GetTensorInfo().
Referenced by armnn::BuildAddMulAddTensorInfoLists(), armnn::ConnectedToLayerType(), ConvertConstantToTosaOperator(), LayerWithParameters< Parameters >::GetConnectedConstantAsInputTensors(), Layer::GetDataType(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), Convolution2dLayer::SerializeLayerParameters(), Convolution3dLayer::SerializeLayerParameters(), DepthwiseConvolution2dLayer::SerializeLayerParameters(), AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
Insert()
void Insert (Layer & layer)
Definition at line 53 of file Layer.cpp.
 {
     if (layer.GetNumOutputSlots() != 1)
     {
         throw armnn::Exception("layer must have one output slot.");
     }
     OutputSlot* const prevSlot = GetConnectedOutputSlot();
     if (prevSlot != nullptr)
     {
         // Disconnects parent from this.
         prevSlot->Disconnect(*this);
         AssertNumberOfInputSlots(layer);
         // Connects inserted layer to parent.
         int idx = prevSlot->Connect(layer.GetInputSlot(0));
         prevSlot->SetEdgeStrategy(armnn::numeric_cast<unsigned int>(idx), EdgeStrategy::Undefined);
         // Sets tensor info for inserted layer.
         const TensorInfo& tensorInfo = prevSlot->GetTensorInfo();
         layer.GetOutputHandler().SetTensorInfo(tensorInfo);
     }
     // Connects inserted layer to this.
     layer.GetOutputSlot(0).Connect(*this);
     layer.GetOutputSlot(0).SetEdgeStrategy(0, EdgeStrategy::Undefined);
 }
References armnn::AssertNumberOfInputSlots(), OutputSlot::Connect(), OutputSlot::Disconnect(), InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), Layer::GetNumOutputSlots(), Layer::GetOutputHandler(), Layer::GetOutputSlot(), OutputSlot::GetTensorInfo(), OutputSlot::SetEdgeStrategy(), OutputHandler::SetTensorInfo(), and armnn::Undefined.
Referenced by Graph::InsertNewLayer().
IsTensorInfoOverridden()
bool IsTensorInfoOverridden () const override virtual
Returns true if this InputSlot has an overridden TensorInfo that was set through a call to SetTensorInfo().
Implements IInputSlot.
Definition at line 631 of file Layer.cpp.
 {
     return m_OverriddenTensorInfo.has_value();
 }
IsTensorInfoSet()
bool IsTensorInfoSet () const override virtual
Returns true if this InputSlot either has an overridden TensorInfo for this InputSlot that was set through a call to SetTensorInfo() or is Connected to an OutputSlot that has its TensorInfo set.
Implements IInputSlot.
Definition at line 626 of file Layer.cpp.
 {
     return m_OverriddenTensorInfo.has_value() || (GetConnection() && GetConnection()->IsTensorInfoSet());
 }
References InputSlot::GetConnection(), and IOutputSlot::IsTensorInfoSet().
SetConnection()
void SetConnection (OutputSlot * source) inline
Links the slot to an output slot or breaks an existing link if passing nullptr.
Definition at line 63 of file Layer.hpp.
     {
         if (m_Connection != nullptr && source != nullptr)
         {
             throw InvalidArgumentException("Tried to connect an output slot to an input slot, "
                 "but the latter already has a connection");
         }
         m_Connection = source;
     }
Referenced by OutputSlot::Connect(), and OutputSlot::Disconnect().
SetTensorInfo()
void SetTensorInfo (const TensorInfo tensorInfo) override virtual
Sets the TensorInfo for this InputSlot.
This can be used to override the TensorInfo and if set will be returned instead of the TensorInfo for the Connected OutputSlot.
Implements IInputSlot.
Definition at line 609 of file Layer.cpp.
 {
     m_OverriddenTensorInfo = Optional<TensorInfo>(tensorInfo);
 }
Referenced by Graph::Graph(), and armnn::RemoveReshapeLayer().
The documentation for this class was generated from the following files:
src/armnn/Layer.hpp
src/armnn/Layer.cpp