Arm NN: IStrategy Class Reference
IStrategy Class Reference abstract
#include <IStrategy.hpp>
Public Member Functions
virtual void ExecuteStrategy (const IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0)=0
virtual void FinishStrategy ()
Protected Member Functions
IStrategy ()
virtual ~IStrategy ()
Detailed Description
Definition at line 16 of file IStrategy.hpp.
Constructor & Destructor Documentation
IStrategy()
IStrategy () inline protected
Definition at line 19 of file IStrategy.hpp.
 {}
~IStrategy()
virtual ~IStrategy () inline protected virtual
Definition at line 20 of file IStrategy.hpp.
 {}
Member Function Documentation
ExecuteStrategy()
virtual void ExecuteStrategy (const IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) pure virtual
Implemented in StrategyBase< DefaultStrategy >.
Referenced by Layer::ExecuteStrategy(), BindableLayer::ExecuteStrategy(), AbsLayer::ExecuteStrategy(), ActivationLayer::ExecuteStrategy(), AdditionLayer::ExecuteStrategy(), ArgMinMaxLayer::ExecuteStrategy(), BatchNormalizationLayer::ExecuteStrategy(), BatchToSpaceNdLayer::ExecuteStrategy(), BroadcastToLayer::ExecuteStrategy(), ComparisonLayer::ExecuteStrategy(), ConcatLayer::ExecuteStrategy(), ConstantLayer::ExecuteStrategy(), ConvertFp16ToFp32Layer::ExecuteStrategy(), ConvertFp32ToFp16Layer::ExecuteStrategy(), Convolution2dLayer::ExecuteStrategy(), Convolution3dLayer::ExecuteStrategy(), DebugLayer::ExecuteStrategy(), DepthToSpaceLayer::ExecuteStrategy(), DepthwiseConvolution2dLayer::ExecuteStrategy(), DequantizeLayer::ExecuteStrategy(), DetectionPostProcessLayer::ExecuteStrategy(), DivisionLayer::ExecuteStrategy(), ElementwiseBaseLayer::ExecuteStrategy(), ElementwiseBinaryLayer::ExecuteStrategy(), ElementwiseUnaryLayer::ExecuteStrategy(), FillLayer::ExecuteStrategy(), FloorLayer::ExecuteStrategy(), FullyConnectedLayer::ExecuteStrategy(), FusedLayer::ExecuteStrategy(), GatherLayer::ExecuteStrategy(), InputLayer::ExecuteStrategy(), InstanceNormalizationLayer::ExecuteStrategy(), L2NormalizationLayer::ExecuteStrategy(), LayerWithParameters< Parameters >::ExecuteStrategy(), LogicalBinaryLayer::ExecuteStrategy(), LogSoftmaxLayer::ExecuteStrategy(), LstmLayer::ExecuteStrategy(), MaximumLayer::ExecuteStrategy(), MeanLayer::ExecuteStrategy(), MemCopyLayer::ExecuteStrategy(), MergeLayer::ExecuteStrategy(), MinimumLayer::ExecuteStrategy(), MultiplicationLayer::ExecuteStrategy(), NormalizationLayer::ExecuteStrategy(), OutputLayer::ExecuteStrategy(), PadLayer::ExecuteStrategy(), PermuteLayer::ExecuteStrategy(), Pooling2dLayer::ExecuteStrategy(), Pooling3dLayer::ExecuteStrategy(), PreCompiledLayer::ExecuteStrategy(), PreluLayer::ExecuteStrategy(), QLstmLayer::ExecuteStrategy(), QuantizedLstmLayer::ExecuteStrategy(), QuantizeLayer::ExecuteStrategy(), RankLayer::ExecuteStrategy(), ReduceLayer::ExecuteStrategy(), ReshapeLayer::ExecuteStrategy(), ResizeLayer::ExecuteStrategy(), ReverseV2Layer::ExecuteStrategy(), RsqrtLayer::ExecuteStrategy(), ShapeLayer::ExecuteStrategy(), SliceLayer::ExecuteStrategy(), SoftmaxLayer::ExecuteStrategy(), SpaceToBatchNdLayer::ExecuteStrategy(), SpaceToDepthLayer::ExecuteStrategy(), SplitterLayer::ExecuteStrategy(), StackLayer::ExecuteStrategy(), StandInLayer::ExecuteStrategy(), StridedSliceLayer::ExecuteStrategy(), SubtractionLayer::ExecuteStrategy(), SwitchLayer::ExecuteStrategy(), TransposeConvolution2dLayer::ExecuteStrategy(), TransposeLayer::ExecuteStrategy(), and UnidirectionalSequenceLstmLayer::ExecuteStrategy().
FinishStrategy()
virtual void FinishStrategy () inline virtual
Definition at line 29 of file IStrategy.hpp.
 {};
The documentation for this class was generated from the following file:
include/armnn/IStrategy.hpp