Arm NN: NeonConvertFp32ToFp16Workload Class Reference
NeonConvertFp32ToFp16Workload Class Reference
#include <NeonConvertFp32ToFp16Workload.hpp>
Public Member Functions
NeonConvertFp32ToFp16Workload (const ConvertFp32ToFp16QueueDescriptor &descriptor, const WorkloadInfo &info)
virtual void Execute () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from MultiTypedWorkload< QueueDescriptor, InputDataType, OutputDataType >
MultiTypedWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
Public Member Functions inherited from BaseWorkload< QueueDescriptor >
BaseWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const QueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< QueueDescriptor >
QueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 19 of file NeonConvertFp32ToFp16Workload.hpp.
Constructor & Destructor Documentation
NeonConvertFp32ToFp16Workload()
NeonConvertFp32ToFp16Workload (const ConvertFp32ToFp16QueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 31 of file NeonConvertFp32ToFp16Workload.cpp.
     : Float32ToFloat16Workload<ConvertFp32ToFp16QueueDescriptor>(descriptor, info)
 {
     this->m_Data.ValidateInputsOutputs("NeonConvertFp32ToFp16Workload", 1, 1);
     arm_compute::ITensor& input  = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     if (arm_compute::NECast::validate(input.info(), output.info(), g_AclConvertPolicy))
     {
         // Use NECast if supported (needs hardware support for FP16)
         m_Cast.reset(new arm_compute::NECast);
         m_Cast->configure(&input, &output, g_AclConvertPolicy);
     }
     else
     {
         // Else use software implementation from Half.hpp
         GatherTensorHandlePairs(descriptor, m_TensorHandlePairs);
     }
 }
References armnn::GatherTensorHandlePairs(), armnn::info, BaseWorkload< QueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, and QueueDescriptor::ValidateInputsOutputs().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 53 of file NeonConvertFp32ToFp16Workload.cpp.
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID("NeonConvertFp32ToFp16Workload_Execute");
     if (m_Cast)
     {
         // Use NECast if supported and initialised
         m_Cast->run();
     }
     else
     {
         // Else use softwre implementabion using Half.hpp
         auto convertFunc = [](uint8_t* dst, const uint8_t* src, size_t size)
             {
                 auto input = reinterpret_cast<const float*>(src);
                 auto output = reinterpret_cast<Half*>(dst);
                 size_t numElements = size/2; // 2 bytes per fp16
                 armnnUtils::FloatingPointConverter::ConvertFloat32To16(input, numElements, output);
             };
         for (const auto& pair : m_TensorHandlePairs)
         {
             CopyTensorContentsGeneric(pair.first, pair.second, convertFunc);
         }
     }
 }
References ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID, FloatingPointConverter::ConvertFloat32To16(), and armnn::CopyTensorContentsGeneric().
ReplaceInputTensorHandle()
void ReplaceInputTensorHandle (ITensorHandle * tensorHandle, unsigned int slot) override virtual
Reimplemented from BaseWorkload< QueueDescriptor >.
Definition at line 80 of file NeonConvertFp32ToFp16Workload.cpp.
 {
     ITensorHandle* backupHandle = this->m_Data.m_Inputs[slot];
     this->m_Data.m_Inputs[slot] = tensorHandle;
     try
     {
         Reconfigure();
     }
     catch(armnn::UnimplementedException& e)
     {
         // Cannot reconfigure, revert the slot back and throw the exception.
         this->m_Data.m_Inputs[slot] = backupHandle;
         throw e;
     }
 }
References BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
ReplaceOutputTensorHandle()
void ReplaceOutputTensorHandle (ITensorHandle * tensorHandle, unsigned int slot) override virtual
Reimplemented from BaseWorkload< QueueDescriptor >.
Definition at line 97 of file NeonConvertFp32ToFp16Workload.cpp.
 {
     ITensorHandle* backupHandle = this->m_Data.m_Inputs[slot];
     this->m_Data.m_Inputs[slot] = tensorHandle;
     try
     {
         Reconfigure();
     }
     catch(armnn::UnimplementedException& e)
     {
         // Cannot reconfigure, revert the slot back and throw the exception.
         this->m_Data.m_Inputs[slot] = backupHandle;
         throw e;
     }
 }
References BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonConvertFp32ToFp16Workload.hpp
src/backends/neon/workloads/NeonConvertFp32ToFp16Workload.cpp