Arm NN: TosaRefMemoryManager::Pool Class Reference
TosaRefMemoryManager::Pool Class Reference
#include <TosaRefMemoryManager.hpp>
Public Member Functions
Pool (unsigned int numBytes)
~Pool ()
void Acquire ()
void Release ()
void * GetPointer ()
void Reserve (unsigned int numBytes)
Detailed Description
Definition at line 33 of file TosaRefMemoryManager.hpp.
Constructor & Destructor Documentation
Pool()
Pool (unsigned int numBytes)
Definition at line 62 of file TosaRefMemoryManager.cpp.
     : m_Size(numBytes),
       m_Pointer(nullptr)
 {}
~Pool()
~Pool ()
Definition at line 67 of file TosaRefMemoryManager.cpp.
 {
     if (m_Pointer)
     {
         Release();
     }
 }
References TosaRefMemoryManager::Release().
Member Function Documentation
Acquire()
void Acquire ()
Definition at line 89 of file TosaRefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(!m_Pointer, RuntimeException,
                              "TosaRefMemoryManager::Pool::Acquire() called when memory already acquired");
     m_Pointer = ::operator new(size_t(m_Size));
 }
References ARMNN_THROW_MSG_IF_FALSE.
GetPointer()
void * GetPointer ()
Definition at line 75 of file TosaRefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(m_Pointer, RuntimeException,
                              "TosaRefMemoryManager::Pool::GetPointer() called when memory not acquired");
     return m_Pointer;
 }
References ARMNN_THROW_MSG_IF_FALSE.
Referenced by TosaRefMemoryManager::GetPointer().
Release()
void Release ()
Definition at line 96 of file TosaRefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(m_Pointer, RuntimeException,
                              "TosaRefMemoryManager::Pool::Release() called when memory not acquired");
     ::operator delete(m_Pointer);
     m_Pointer = nullptr;
 }
References ARMNN_THROW_MSG_IF_FALSE.
Reserve()
void Reserve (unsigned int numBytes)
Definition at line 82 of file TosaRefMemoryManager.cpp.
 {
     ARMNN_THROW_MSG_IF_FALSE(!m_Pointer, RuntimeException,
                              "TosaRefMemoryManager::Pool::Reserve() cannot be called after memory acquired");
     m_Size = std::max(m_Size, numBytes);
 }
References ARMNN_THROW_MSG_IF_FALSE.
Referenced by TosaRefMemoryManager::Manage().
The documentation for this class was generated from the following files:
src/backends/tosaReference/TosaRefMemoryManager.hpp
src/backends/tosaReference/TosaRefMemoryManager.cpp