Arm NN: OptimizeInverseConversionsImpl Class Reference
OptimizeInverseConversionsImpl Class Reference
#include <OptimizeInverseConversions.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Run for every connection between two inverse data type conversion layers, i.e.
Protected Member Functions
OptimizeInverseConversionsImpl ()=default
~OptimizeInverseConversionsImpl ()=default
Detailed Description
Definition at line 16 of file OptimizeInverseConversions.hpp.
Constructor & Destructor Documentation
OptimizeInverseConversionsImpl()
OptimizeInverseConversionsImpl () protected default
~OptimizeInverseConversionsImpl()
~OptimizeInverseConversionsImpl () protected default
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Run for every connection between two inverse data type conversion layers, i.e.
Fp16ToFp32 followed by Fp32ToFp16 or vice-versa.
Definition at line 21 of file OptimizeInverseConversions.hpp.
     {
         IgnoreUnused(graph);
         Layer& base  = connection.GetConnectedOutputSlot()->GetOwningLayer();
         Layer& child = connection.GetOwningLayer();
         ARMNN_ASSERT((base.GetType() == LayerType::ConvertFp16ToFp32 &&
                      child.GetType() == LayerType::ConvertFp32ToFp16) ||
                      (base.GetType() == LayerType::ConvertFp32ToFp16 &&
                      child.GetType() == LayerType::ConvertFp16ToFp32));
         // Bypass both conversion layers
         child.GetOutputSlot().MoveAllConnections(*base.GetInputSlot(0).GetConnectedOutputSlot());
     }
References ARMNN_ASSERT, armnn::ConvertFp16ToFp32, armnn::ConvertFp32ToFp16, InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), Layer::GetType(), armnn::IgnoreUnused(), and OutputSlot::MoveAllConnections().
The documentation for this class was generated from the following file:
src/armnn/optimizations/OptimizeInverseConversions.hpp