Arm NN: OutputSlot Class Reference
OutputSlot Class Reference final
#include <Layer.hpp>
Public Member Functions
OutputSlot (Layer &owner, OutputHandler &outputHandler)
OutputSlot (const OutputSlot &)=delete
OutputSlot & operator= (const OutputSlot &)=delete
OutputSlot & operator= (OutputSlot &&)=delete
OutputSlot (OutputSlot &&)=default
~OutputSlot ()
Layer & GetOwningLayer () const
const IConnectableLayer & GetOwningIConnectableLayer () const override
IConnectableLayer & GetOwningIConnectableLayer () override
LayerGuid GetOwningLayerGuid () const override
const OutputHandler & GetOutputHandler () const
OutputHandler & GetOutputHandler ()
int Connect (InputSlot &destination)
void Disconnect (InputSlot &slot)
const std::vector< InputSlot * > & GetConnections () const
const std::vector< EdgeStrategy > & GetEdgeStrategies () const
bool ValidateTensorShape (const TensorShape &shape) const
void DisconnectAll ()
void MoveAllConnections (OutputSlot &destination)
Moves all connections to another OutputSlot.
unsigned int GetNumConnections () const override
const InputSlot * GetConnection (unsigned int index) const override
InputSlot * GetConnection (unsigned int index) override
void SetTensorInfo (const TensorInfo &tensorInfo) override
const TensorInfo & GetTensorInfo () const override
bool IsTensorInfoSet () const override
int Connect (IInputSlot &destination) override
void Disconnect (IInputSlot &slot) override
unsigned int CalculateIndexOnOwner () const override
bool operator== (const OutputSlot &other) const
void SetTensorHandleFactory (const ITensorHandleFactory::FactoryId &id)
ITensorHandleFactory::FactoryId GetTensorHandleFactoryId () const
void SetEdgeStrategy (unsigned int connectionIndex, EdgeStrategy strategy)
EdgeStrategy GetEdgeStrategyForConnection (unsigned int connectionIdx) const
Additional Inherited Members
Protected Member Functions inherited from IOutputSlot
~IOutputSlot ()
Not user deletable.
Detailed Description
Definition at line 100 of file Layer.hpp.
Constructor & Destructor Documentation
OutputSlot() [1/3]
OutputSlot (Layer & owner, OutputHandler & outputHandler) inline explicit
Definition at line 103 of file Layer.hpp.
     : m_OwningLayer(owner)
     , m_OutputHandler(outputHandler)
     , m_TensorHandleFactoryId(ITensorHandleFactory::LegacyFactoryId)
     {}
OutputSlot() [2/3]
OutputSlot (const OutputSlot &) delete
OutputSlot() [3/3]
OutputSlot (OutputSlot &&) default
~OutputSlot()
~OutputSlot () inline
Definition at line 115 of file Layer.hpp.
     {
         try
         {
             // Coverity fix: DisconnectAll() may throw uncaught exceptions.
             DisconnectAll();
         }
         catch (const std::exception& e)
         {
             // Coverity fix: BOOST_LOG_TRIVIAL (typically used to report errors) may throw an
             // exception of type std::length_error.
             // Using stderr instead in this context as there is no point in nesting try-catch blocks here.
             std::cerr << "WARNING: An error has occurred when disconnecting all output slots: "
                       << e.what() << std::endl;
         }
     }
References OutputSlot::DisconnectAll().
Member Function Documentation
CalculateIndexOnOwner()
unsigned int CalculateIndexOnOwner () const override virtual
Implements IOutputSlot.
Definition at line 172 of file Layer.cpp.
 {
     for (unsigned int i = 0; i < GetOwningLayer().GetNumOutputSlots(); i++)
     {
         if (GetOwningLayer().GetOutputSlot(i) == (*this))
         {
             return i;
         }
     }
     throw armnn::Exception("Did not find slot on owner.");
     return 0; // Error
 }
References Layer::GetNumOutputSlots(), Layer::GetOutputSlot(), and OutputSlot::GetOwningLayer().
Referenced by DebugLayer::CreateWorkload(), and GenerateUniqueInputName().
Connect() [1/2]
int Connect (IInputSlot & destination) inline override virtual
Implements IOutputSlot.
Definition at line 166 of file Layer.hpp.
     {
         return Connect(*PolymorphicDowncast<InputSlot*>(&destination));
     }
References OutputSlot::Connect().
Connect() [2/2]
int Connect (InputSlot & destination)
Definition at line 123 of file Layer.cpp.
 {
     destination.SetConnection(this);
     m_Connections.push_back(&destination);
     m_EdgeStrategies.push_back(EdgeStrategy::Undefined);
     return armnn::numeric_cast<int>(m_Connections.size() - 1);
 }
References InputSlot::SetConnection(), and armnn::Undefined.
Referenced by armnn::ApplyBackendOptimizations(), OutputSlot::Connect(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), InputSlot::Insert(), Graph::InsertNewLayer(), OutputSlot::MoveAllConnections(), and FuseBatchNorm< ConvLayer, ArmnnType, T >::Run().
Disconnect() [1/2]
void Disconnect (IInputSlot & slot) inline override virtual
Implements IOutputSlot.
Definition at line 171 of file Layer.hpp.
     {
         return Disconnect(*PolymorphicDowncast<InputSlot*>(&slot));
     }
References OutputSlot::Disconnect().
Disconnect() [2/2]
void Disconnect (InputSlot & slot)
Definition at line 131 of file Layer.cpp.
 {
     slot.SetConnection(nullptr);
     auto it = std::find(m_Connections.begin(), m_Connections.end(), &slot);
     if (it == m_Connections.end())
     {
         return;
     }
     auto idx = std::distance(m_Connections.begin(), it);
     m_Connections.erase(std::remove(m_Connections.begin(), m_Connections.end(), &slot), m_Connections.end());
     m_EdgeStrategies.erase(m_EdgeStrategies.begin() + idx);
 }
References InputSlot::SetConnection().
Referenced by armnn::ApplyBackendOptimizations(), OutputSlot::Disconnect(), OutputSlot::DisconnectAll(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), InputSlot::Insert(), OutputSlot::MoveAllConnections(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), and InputSlot::~InputSlot().
DisconnectAll()
void DisconnectAll ()
Definition at line 147 of file Layer.cpp.
 {
     while (GetNumConnections() > 0)
     {
         InputSlot& connection = *GetConnection(0);
         Disconnect(connection);
     }
 }
References OutputSlot::Disconnect(), OutputSlot::GetConnection(), and OutputSlot::GetNumConnections().
Referenced by OutputSlot::~OutputSlot().
GetConnection() [1/2]
const InputSlot * GetConnection (unsigned int index) const override virtual
Implements IOutputSlot.
Definition at line 83 of file Layer.cpp.
 {
     ValidateConnectionIndex(index);
     return m_Connections[index];
 }
Referenced by armnn::ApplyBackendOptimizations(), armnn::BuildAddMulAddTensorInfoLists(), armnn::ConnectedToLayerType(), armnn::ConnectedToLayerWithNCHW(), ConvertConstantToTosaOperator(), OutputSlot::DisconnectAll(), GenerateUniqueOutputName(), GetTosaMapping(), OutputSlot::MoveAllConnections(), OutputSlot::operator==(), armnn::RemoveReshapeLayer(), DeleteBroadcastToImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
GetConnection() [2/2]
InputSlot * GetConnection (unsigned int index) override virtual
Implements IOutputSlot.
Definition at line 89 of file Layer.cpp.
 {
     ValidateConnectionIndex(index);
     return m_Connections[index];
 }
GetConnections()
const std::vector<InputSlot*>& GetConnections () const inline
Definition at line 145 of file Layer.hpp.
 { return m_Connections; }
Referenced by Graph::AddCompatibilityLayers(), armnn::CalculateSlotOption(), armnn::CalculateSlotOptionForInput(), SquashEqualSiblingsImpl< Comparable >::Run(), and armnn::SelectTensorHandleStrategy().
GetEdgeStrategies()
const std::vector<EdgeStrategy>& GetEdgeStrategies () const inline
Definition at line 146 of file Layer.hpp.
 { return m_EdgeStrategies; }
Referenced by Graph::AddCompatibilityLayers().
GetEdgeStrategyForConnection()
EdgeStrategy GetEdgeStrategyForConnection (unsigned int connectionIdx) const
Definition at line 228 of file Layer.cpp.
 {
     return m_EdgeStrategies[connectionIdx];
 }
GetNumConnections()
unsigned int GetNumConnections () const inline override virtual
Implements IOutputSlot.
Definition at line 158 of file Layer.hpp.
 { return armnn::numeric_cast<unsigned int>(m_Connections.size()); }
Referenced by armnn::ApplyBackendOptimizations(), armnn::BuildAddMulAddTensorInfoLists(), OutputSlot::DisconnectAll(), OutputSlot::MoveAllConnections(), OutputSlot::operator==(), ClBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), SquashEqualSiblingsImpl< Comparable >::Run(), AddBroadcastReshapeLayerImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
GetOutputHandler() [1/2]
OutputHandler& GetOutputHandler () inline
Definition at line 140 of file Layer.hpp.
 { return m_OutputHandler; }
GetOutputHandler() [2/2]
const OutputHandler& GetOutputHandler () const inline
Definition at line 139 of file Layer.hpp.
 { return m_OutputHandler; }
Referenced by OutputSlot::GetTensorInfo(), OutputSlot::IsTensorInfoSet(), OutputSlot::MoveAllConnections(), DeleteBroadcastToImpl::Run(), and OutputSlot::SetTensorInfo().
GetOwningIConnectableLayer() [1/2]
const IConnectableLayer & GetOwningIConnectableLayer () const override virtual
Implements IOutputSlot.
Definition at line 589 of file Layer.cpp.
 {
     return m_OwningLayer;
 }
GetOwningIConnectableLayer() [2/2]
IConnectableLayer & GetOwningIConnectableLayer () override virtual
Implements IOutputSlot.
Definition at line 594 of file Layer.cpp.
 {
     return m_OwningLayer;
 }
GetOwningLayer()
Layer& GetOwningLayer () const inline
Definition at line 132 of file Layer.hpp.
 { return m_OwningLayer; }
Referenced by armnn::BuildAddMulAddTensorInfoLists(), OutputSlot::CalculateIndexOnOwner(), armnn::CalculateSlotOption(), armnn::CalculateSlotOptionForInput(), armnn::ConnectedToLayerType(), armnn::ConnectedToLayerWithNCHW(), ConvertSquaredDifferenceToTosaOperator(), DebugLayer::CreateWorkload(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), GenerateUniqueInputName(), LayerWithParameters< Parameters >::GetConnectedConstantAsInputTensors(), OutputSlot::GetOwningLayerGuid(), Layer::GetPriority(), Graph::InsertNewLayer(), OutputSlot::IsTensorInfoSet(), ClBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), TosaRefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), MaxMinIntoBoundedReluImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::Run(), ConvertConstPermuteLayersToConstLayers::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), OptimizeInversePermutesImpl< PermuteType >::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), TurboConvertConstDequantisationLayersToConstLayersImpl::Run(), AddBroadcastReshapeLayerImpl::Run(), and Graph::SerializeToDot().
GetOwningLayerGuid()
LayerGuid GetOwningLayerGuid () const override virtual
Implements IOutputSlot.
Definition at line 208 of file Layer.cpp.
 {
     return GetOwningLayer().GetGuid();
 }
References Layer::GetGuid(), and OutputSlot::GetOwningLayer().
GetTensorHandleFactoryId()
ITensorHandleFactory::FactoryId GetTensorHandleFactoryId () const
Definition at line 218 of file Layer.cpp.
 {
     return m_TensorHandleFactoryId;
 }
Referenced by Graph::AddCompatibilityLayers(), Layer::CreateTensorHandles(), ConcatLayer::CreateTensorHandles(), and SplitterLayer::CreateTensorHandles().
GetTensorInfo()
const TensorInfo & GetTensorInfo () const override virtual
Implements IOutputSlot.
Definition at line 100 of file Layer.cpp.
 {
     return GetOutputHandler().GetTensorInfo();
 }
References OutputSlot::GetOutputHandler(), and OutputHandler::GetTensorInfo().
Referenced by armnn::BuildAddMulAddTensorInfoLists(), armnn::CheckScaleSetOnQuantizedType(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), Layer::GetDataType(), armnn::GetLayerInOutDatatype(), InputSlot::Insert(), armnn::InsertConvertFp16ToFp32LayersBefore(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::InsertDebugLayerAfter(), OutputSlot::MoveAllConnections(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), DeleteBroadcastToImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), OptimizeConsecutiveReshapesImpl::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), AddBroadcastReshapeLayerImpl::Run(), Graph::SerializeToDot(), Layer::ValidateAndCopyShape(), AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), BroadcastToLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RankLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), SplitterLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), ConvertConstPermuteLayersToConstLayers::~ConvertConstPermuteLayersToConstLayers(), PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
IsTensorInfoSet()
bool IsTensorInfoSet () const override virtual
Implements IOutputSlot.
Definition at line 105 of file Layer.cpp.
 {
     if (GetOwningLayer().GetShapeInferenceMethod() == ShapeInferenceMethod::InferAndValidate)
     {
         GetOwningLayer().ValidateTensorShapesFromInputs();
     }
     return GetOutputHandler().IsTensorInfoSet();
 }
References OutputSlot::GetOutputHandler(), OutputSlot::GetOwningLayer(), armnn::InferAndValidate, OutputHandler::IsTensorInfoSet(), and Layer::ValidateTensorShapesFromInputs().
Referenced by AddBroadcastReshapeLayerImpl::Run(), and OutputSlot::ValidateTensorShape().
MoveAllConnections()
void MoveAllConnections (OutputSlot & destination)
Moves all connections to another OutputSlot.
Definition at line 156 of file Layer.cpp.
 {
     while (GetNumConnections() > 0)
     {
         if (m_EdgeStrategies[0] != EdgeStrategy::Undefined)
         {
             throw armnn::Exception("Cannot move connections once memory strategies have be established.");
         }
         InputSlot& connection = *GetConnection(0);
         Disconnect(connection);
         destination.Connect(connection);
         destination.GetOutputHandler().SetTensorInfo(GetOutputHandler().GetTensorInfo());
     }
 }
References OutputSlot::Connect(), OutputSlot::Disconnect(), OutputSlot::GetConnection(), OutputSlot::GetNumConnections(), OutputSlot::GetOutputHandler(), OutputSlot::GetTensorInfo(), OutputHandler::SetTensorInfo(), and armnn::Undefined.
Referenced by Graph::InsertNewLayer(), DeleteBroadcastToImpl::Run(), MaxMinIntoBoundedReluImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), PermuteAsReshapeImpl::Run(), TransposeAsReshapeImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), ConvertConstPermuteLayersToConstLayers::~ConvertConstPermuteLayersToConstLayers(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
operator=() [1/2]
OutputSlot& operator= (const OutputSlot &) delete
operator=() [2/2]
OutputSlot& operator= (OutputSlot &&) delete
operator==()
bool operator== (const OutputSlot & other) const
Definition at line 185 of file Layer.cpp.
 {
     bool isSame = other.GetNumConnections() == GetNumConnections();
     if (!isSame)
     {
         return false;
     }
     for (unsigned int i = 0; i < GetNumConnections(); i++)
     {
         isSame &= other.GetConnection(i) == GetConnection(i);
     }
     return isSame;
 }
References OutputSlot::GetConnection(), and OutputSlot::GetNumConnections().
SetEdgeStrategy()
void SetEdgeStrategy (unsigned int connectionIndex, EdgeStrategy strategy)
Definition at line 223 of file Layer.cpp.
 {
     m_EdgeStrategies[connectionIndex] = strategy;
 }
Referenced by Graph::AddCompatibilityLayers(), InputSlot::Insert(), and armnn::SelectTensorHandleStrategy().
SetTensorHandleFactory()
void SetTensorHandleFactory (const ITensorHandleFactory::FactoryId & id)
Definition at line 213 of file Layer.cpp.
 {
     m_TensorHandleFactoryId = id;
 }
Referenced by Graph::AddCompatibilityLayers(), and armnn::SelectTensorHandleStrategy().
SetTensorInfo()
void SetTensorInfo (const TensorInfo & tensorInfo) override virtual
Implements IOutputSlot.
Definition at line 95 of file Layer.cpp.
 {
     GetOutputHandler().SetTensorInfo(tensorInfo);
 }
References OutputSlot::GetOutputHandler(), and OutputHandler::SetTensorInfo().
Referenced by armnn::AttemptBackendAssignment(), armnn::BuildAddMulAddTensorInfoLists(), armnn::ChainReduceLayers(), armnn::CheckScaleSetOnQuantizedType(), armnn::InsertConvertFp16ToFp32LayersBefore(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::InsertDebugLayerAfter(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), AddBroadcastReshapeLayerImpl::Run(), Layer::ValidateAndCopyShape(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), ConvertConstPermuteLayersToConstLayers::~ConvertConstPermuteLayersToConstLayers(), PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
ValidateTensorShape()
bool ValidateTensorShape (const TensorShape & shape) const
Definition at line 114 of file Layer.cpp.
 {
     if (!IsTensorInfoSet())
     {
         throw armnn::Exception("TensorInfo must be set in order to validate the shape.");
     }
     return shape == m_OutputHandler.GetTensorInfo().GetShape();
 }
References TensorInfo::GetShape(), OutputHandler::GetTensorInfo(), and OutputSlot::IsTensorInfoSet().
The documentation for this class was generated from the following files:
src/armnn/Layer.hpp
src/armnn/Layer.cpp