Arm NN: DataLayoutIndexed Class Reference
DataLayoutIndexed Class Reference
Provides access to the appropriate indexes for Channels, Height and Width based on DataLayout.
#include <DataLayoutIndexed.hpp>
Public Member Functions
DataLayoutIndexed (armnn::DataLayout dataLayout)
armnn::DataLayout GetDataLayout () const
unsigned int GetChannelsIndex () const
unsigned int GetHeightIndex () const
unsigned int GetWidthIndex () const
unsigned int GetDepthIndex () const
unsigned int GetIndex (const armnn::TensorShape &shape, unsigned int batchIndex, unsigned int channelIndex, unsigned int heightIndex, unsigned int widthIndex) const
Detailed Description
Provides access to the appropriate indexes for Channels, Height and Width based on DataLayout.
Definition at line 17 of file DataLayoutIndexed.hpp.
Constructor & Destructor Documentation
DataLayoutIndexed()
DataLayoutIndexed (armnn::DataLayout dataLayout)
Definition at line 13 of file DataLayoutIndexed.cpp.
     : m_DataLayout(dataLayout)
 {
     switch (dataLayout)
     {
         case armnn::DataLayout::NHWC:
             m_ChannelsIndex = 3;
             m_HeightIndex   = 1;
             m_WidthIndex    = 2;
             break;
         case armnn::DataLayout::NCHW:
             m_ChannelsIndex = 1;
             m_HeightIndex   = 2;
             m_WidthIndex    = 3;
             break;
         case armnn::DataLayout::NDHWC:
             m_DepthIndex    = 1;
             m_HeightIndex   = 2;
             m_WidthIndex    = 3;
             m_ChannelsIndex = 4;
             break;
         case armnn::DataLayout::NCDHW:
             m_ChannelsIndex = 1;
             m_DepthIndex    = 2;
             m_HeightIndex   = 3;
             m_WidthIndex    = 4;
             break;
         default:
             throw armnn::InvalidArgumentException("Unknown DataLayout value: " +
                                                   std::to_string(static_cast<int>(dataLayout)));
     }
 }
References armnn::NCDHW, armnn::NCHW, armnn::NDHWC, and armnn::NHWC.
Member Function Documentation
GetChannelsIndex()
unsigned int GetChannelsIndex () const inline
Definition at line 23 of file DataLayoutIndexed.hpp.
 { return m_ChannelsIndex; }
Referenced by armnn::BatchNormImpl(), armnn::BatchToSpaceNd(), armnn::Convert1HWOtoMIHW(), armnn::Convolve(), armnn::Convolve3d(), armnn::DepthToSpace(), armnn::GetOffset(), DepthToSpaceLayer::InferOutputShapes(), Pooling2dLayer::InferOutputShapes(), Pooling3dLayer::InferOutputShapes(), ResizeLayer::InferOutputShapes(), armnn::InstanceNorm(), armnn::Offset(), armnn::Pooling2d(), armnn::Pooling3d(), armnn::Resize(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), armnn::SpaceToBatchNd(), armnn::SpaceToDepth(), armnn::TransposeConvolution2dImpl(), armnn::optimizations::pad_fold::TryFoldPadIntoLayer2d(), ResizeQueueDescriptor::Validate(), SpaceToDepthQueueDescriptor::Validate(), and DepthToSpaceQueueDescriptor::Validate().
GetDataLayout()
armnn::DataLayout GetDataLayout () const inline
Definition at line 22 of file DataLayoutIndexed.hpp.
 { return m_DataLayout; }
Referenced by armnn::Convolve(), armnn::Convolve3d(), armnn::GetOffset(), armnn::Offset(), armnnUtils::operator==(), and armnn::Pooling2d().
GetDepthIndex()
unsigned int GetDepthIndex () const inline
Definition at line 26 of file DataLayoutIndexed.hpp.
 { return m_DepthIndex; }
Referenced by armnn::Convolve3d(), Convolution3dLayer::InferOutputShapes(), Pooling3dLayer::InferOutputShapes(), and armnn::Pooling3d().
GetHeightIndex()
unsigned int GetHeightIndex () const inline
Definition at line 24 of file DataLayoutIndexed.hpp.
 { return m_HeightIndex; }
Referenced by armnn::BatchNormImpl(), armnn::BatchToSpaceNd(), armnn::Convolve(), armnn::Convolve3d(), armnn::DepthToSpace(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), armnn::GetOffset(), Convolution2dLayer::InferOutputShapes(), Convolution3dLayer::InferOutputShapes(), DepthToSpaceLayer::InferOutputShapes(), DepthwiseConvolution2dLayer::InferOutputShapes(), Pooling2dLayer::InferOutputShapes(), Pooling3dLayer::InferOutputShapes(), TransposeConvolution2dLayer::InferOutputShapes(), armnn::InstanceNorm(), armnn::Offset(), armnn::Pooling2d(), armnn::Pooling3d(), armnn::Resize(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), Convolution2dLayer::SerializeLayerParameters(), armnn::SpaceToBatchNd(), armnn::SpaceToDepth(), armnn::TransposeConvolution2dImpl(), armnn::optimizations::pad_fold::TryFoldPadIntoLayer2d(), SpaceToBatchNdQueueDescriptor::Validate(), SpaceToDepthQueueDescriptor::Validate(), and DepthToSpaceQueueDescriptor::Validate().
GetIndex()
unsigned int GetIndex (const armnn::TensorShape & shape, unsigned int batchIndex, unsigned int channelIndex, unsigned int heightIndex, unsigned int widthIndex) const inline
Offset the given indices appropriately depending on the data layout
channelIndex stays unchanged
widthIndex stays unchanged
Get the value using the correct offset
Definition at line 28 of file DataLayoutIndexed.hpp.
     {
         if (batchIndex >= shape[0] && !( shape[0] == 0 && batchIndex == 0))
         {
             throw armnn::Exception("Unable to get batch index", CHECK_LOCATION());
         }
         if (channelIndex >= shape[m_ChannelsIndex] &&
                     !(shape[m_ChannelsIndex] == 0 && channelIndex == 0))
         {
             throw armnn::Exception("Unable to get channel index", CHECK_LOCATION());
         }
         if (heightIndex >= shape[m_HeightIndex] &&
                     !( shape[m_HeightIndex] == 0 && heightIndex == 0))
         {
             throw armnn::Exception("Unable to get height index", CHECK_LOCATION());
         }
         if (widthIndex >= shape[m_WidthIndex] &&
                     ( shape[m_WidthIndex] == 0 && widthIndex == 0))
         {
             throw armnn::Exception("Unable to get width index", CHECK_LOCATION());
         }
         /// Offset the given indices appropriately depending on the data layout
         switch (m_DataLayout)
         {
         case armnn::DataLayout::NHWC:
             batchIndex  *= shape[1] * shape[2] * shape[3]; // batchIndex *= heightIndex * widthIndex * channelIndex
             heightIndex *= shape[m_WidthIndex] * shape[m_ChannelsIndex];
             widthIndex  *= shape[m_ChannelsIndex];
             /// channelIndex stays unchanged
             break;
         case armnn::DataLayout::NCHW:
         default:
             batchIndex   *= shape[1] * shape[2] * shape[3]; // batchIndex *= heightIndex * widthIndex * channelIndex
             channelIndex *= shape[m_HeightIndex] * shape[m_WidthIndex];
             heightIndex  *= shape[m_WidthIndex];
             /// widthIndex stays unchanged
             break;
         }
         /// Get the value using the correct offset
         return batchIndex + channelIndex + heightIndex + widthIndex;
     }
References CHECK_LOCATION, armnn::NCHW, and armnn::NHWC.
Referenced by armnn::BatchNormImpl(), TensorBufferArrayView< DataType >::Get(), armnn::InstanceNorm(), armnn::Resize(), and armnn::TransposeConvolution2dImpl().
GetWidthIndex()
unsigned int GetWidthIndex () const inline
Definition at line 25 of file DataLayoutIndexed.hpp.
 { return m_WidthIndex; }
Referenced by armnn::BatchNormImpl(), armnn::BatchToSpaceNd(), armnn::Convolve(), armnn::Convolve3d(), armnn::DepthToSpace(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), armnn::GetOffset(), Convolution2dLayer::InferOutputShapes(), Convolution3dLayer::InferOutputShapes(), DepthToSpaceLayer::InferOutputShapes(), DepthwiseConvolution2dLayer::InferOutputShapes(), Pooling2dLayer::InferOutputShapes(), Pooling3dLayer::InferOutputShapes(), TransposeConvolution2dLayer::InferOutputShapes(), armnn::InstanceNorm(), armnn::Offset(), armnn::Pooling2d(), armnn::Pooling3d(), armnn::Resize(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), Convolution2dLayer::SerializeLayerParameters(), armnn::SpaceToBatchNd(), armnn::SpaceToDepth(), armnn::TransposeConvolution2dImpl(), armnn::optimizations::pad_fold::TryFoldPadIntoLayer2d(), SpaceToBatchNdQueueDescriptor::Validate(), SpaceToDepthQueueDescriptor::Validate(), and DepthToSpaceQueueDescriptor::Validate().
The documentation for this class was generated from the following files:
include/armnnUtils/DataLayoutIndexed.hpp
src/armnnUtils/DataLayoutIndexed.cpp