Arm NN: QSymm8PerAxisDecoder Class Reference
QSymm8PerAxisDecoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
QSymm8PerAxisDecoder (const int8_t *data, const armnn::TensorInfo &tensorInfo)
float Get () const override
float GetScale () const
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const bool) override
Public Member Functions inherited from PerAxisIterator< const int8_t, Decoder< float > >
PerAxisIterator (const int8_t *data=nullptr, unsigned int axisFactor=0, unsigned int axisDimensionality=0)
PerAxisIterator (const int8_t *data=nullptr, const armnn::TensorShape &tensorShape=TensorShape(), const unsigned int axis=0)
void Reset (void *data) override
PerAxisIterator & operator++ () override
PerAxisIterator & operator+= (const unsigned int increment) override
PerAxisIterator & operator-= (const unsigned int decrement) override
PerAxisIterator & SetIndexOnMem (const unsigned int index)
PerAxisIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from PerAxisIterator< const int8_t, Decoder< float > >
const int8_t * m_Iterator
const int8_t * m_Start
unsigned int m_AxisIndex
unsigned int m_AxisDimensionality
unsigned int m_AxisFactor
unsigned int m_Index
Detailed Description
Definition at line 794 of file BaseIterator.hpp.
Constructor & Destructor Documentation
QSymm8PerAxisDecoder()
QSymm8PerAxisDecoder (const int8_t * data, const armnn::TensorInfo & tensorInfo) inline
Definition at line 797 of file BaseIterator.hpp.
             : PerAxisIterator(data, tensorInfo.GetShape(), tensorInfo.GetQuantizationDim().value()),
               m_Scales(tensorInfo.GetQuantizationScales()), m_Offset(tensorInfo.GetQuantizationOffset())
     {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, const bool) inline override virtual
Implements Decoder< float >.
Definition at line 813 of file BaseIterator.hpp.
     {
         const unsigned int size = tensorShape.GetNumElements();
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         for (uint32_t i = 0; i < size; ++i)
         {
             SetIndexOnMem(i);
             decodedTensor.emplace_back(armnn::Dequantize(*m_Iterator, GetScale(), m_Offset));
         }
         return decodedTensor;
     }
References armnn::Dequantize(), TensorShape::GetNumElements(), QSymm8PerAxisDecoder::GetScale(), PerAxisIterator< const int8_t, Decoder< float > >::m_Iterator, and PerAxisIterator< const int8_t, Decoder< float > >::SetIndexOnMem().
Get()
float Get () const inline override virtual
Implements Decoder< float >.
Definition at line 802 of file BaseIterator.hpp.
     {
         return armnn::Dequantize(*m_Iterator, GetScale(), m_Offset);
     }
References armnn::Dequantize(), QSymm8PerAxisDecoder::GetScale(), and PerAxisIterator< const int8_t, Decoder< float > >::m_Iterator.
GetScale()
float GetScale () const inline
Definition at line 808 of file BaseIterator.hpp.
     {
         return m_Scales[m_AxisIndex];
     }
References PerAxisIterator< const int8_t, Decoder< float > >::m_AxisIndex.
Referenced by QSymm8PerAxisDecoder::DecodeTensor(), and QSymm8PerAxisDecoder::Get().
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp