Arm NN: ClTensorHandleFactory Class Reference
ClTensorHandleFactory Class Reference
#include <ClTensorHandleFactory.hpp>
Public Member Functions
ClTensorHandleFactory (std::shared_ptr< ClMemoryManager > mgr)
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, const TensorShape &subTensorShape, const unsigned int *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const override
Utility Functions for backends which require TensorHandles to have unmanaged memory.
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override
const FactoryId & GetId () const override
bool SupportsSubTensors () const override
MemorySourceFlags GetExportFlags () const override
MemorySourceFlags GetImportFlags () const override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual bool SupportsInPlaceComputation () const
virtual bool SupportsMapUnmap () const
virtual std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass)
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Static Public Attributes
static const FactoryId m_Id
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Detailed Description
Definition at line 20 of file ClTensorHandleFactory.hpp.
Constructor & Destructor Documentation
ClTensorHandleFactory()
ClTensorHandleFactory (std::shared_ptr< ClMemoryManager > mgr) inline
Definition at line 25 of file ClTensorHandleFactory.hpp.
         : m_MemoryManager(mgr)
     {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, const TensorShape & subTensorShape, const unsigned int * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 22 of file ClTensorHandleFactory.cpp.
 {
     arm_compute::Coordinates coords;
     arm_compute::TensorShape shape = armcomputetensorutils::BuildArmComputeTensorShape(subTensorShape);
     coords.set_num_dimensions(subTensorShape.GetNumDimensions());
     for (unsigned int i = 0; i < subTensorShape.GetNumDimensions(); ++i)
     {
         // Arm compute indexes tensor coords in reverse order.
         unsigned int revertedIndex = subTensorShape.GetNumDimensions() - i - 1;
         coords.set(i, armnn::numeric_cast<int>(subTensorOrigin[revertedIndex]));
     }
     const arm_compute::TensorShape parentShape = armcomputetensorutils::BuildArmComputeTensorShape(parent.GetShape());
     // In order for ACL to support subtensors the concat axis cannot be on x or y and the values of x and y
     // must match the parent shapes
     if (coords.x() != 0 || coords.y() != 0)
     {
         return nullptr;
     }
     if ((parentShape.x() != shape.x()) || (parentShape.y() != shape.y()))
     {
         return nullptr;
     }
     if (!::arm_compute::error_on_invalid_subtensor(__func__, __FILE__, __LINE__, parentShape, coords, shape))
     {
         return nullptr;
     }
     return std::make_unique<ClSubTensorHandle>(PolymorphicDowncast<IClTensorHandle*>(&parent), shape, coords);
 }
CreateTensorHandle() [1/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 58 of file ClTensorHandleFactory.cpp.
 {
     return ClTensorHandleFactory::CreateTensorHandle(tensorInfo, true);
 }
Referenced by ClTensorHandleFactory::CreateTensorHandle().
CreateTensorHandle() [2/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged) const override virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented from ITensorHandleFactory.
Definition at line 69 of file ClTensorHandleFactory.cpp.
 {
     std::unique_ptr<ClTensorHandle> tensorHandle = std::make_unique<ClTensorHandle>(tensorInfo);
     if (!IsMemoryManaged)
     {
         ARMNN_LOG(warning) << "ClTensorHandleFactory only has support for memory managed.";
     }
     tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     return tensorHandle;
 }
References ARMNN_LOG, and armnn::warning.
CreateTensorHandle() [3/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 63 of file ClTensorHandleFactory.cpp.
 {
     return ClTensorHandleFactory::CreateTensorHandle(tensorInfo, dataLayout, true);
 }
References ClTensorHandleFactory::CreateTensorHandle().
CreateTensorHandle() [4/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 81 of file ClTensorHandleFactory.cpp.
 {
     std::unique_ptr<ClTensorHandle> tensorHandle = std::make_unique<ClTensorHandle>(tensorInfo, dataLayout);
     if (!IsMemoryManaged)
     {
         ARMNN_LOG(warning) << "ClTensorHandleFactory only has support for memory managed.";
     }
     tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     return tensorHandle;
 }
References ARMNN_LOG, and armnn::warning.
GetExportFlags()
MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 110 of file ClTensorHandleFactory.cpp.
 {
     return MemorySourceFlags(MemorySource::Undefined);
 }
References armnn::Undefined.
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 100 of file ClTensorHandleFactory.cpp.
 {
     return GetIdStatic();
 }
References ClTensorHandleFactory::GetIdStatic().
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 94 of file ClTensorHandleFactory.cpp.
 {
     static const FactoryId s_Id(ClTensorHandleFactoryId());
     return s_Id;
 }
References armnn::ClTensorHandleFactoryId().
Referenced by ClBackend::GetHandleFactoryPreferences(), and ClTensorHandleFactory::GetId().
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 115 of file ClTensorHandleFactory.cpp.
 {
     return MemorySourceFlags(MemorySource::Undefined);
 }
References armnn::Undefined.
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 105 of file ClTensorHandleFactory.cpp.
 {
     return false;
 }
Member Data Documentation
m_Id
const FactoryId m_Id static
Definition at line 23 of file ClTensorHandleFactory.hpp.
The documentation for this class was generated from the following files:
src/backends/cl/ClTensorHandleFactory.hpp
src/backends/cl/ClTensorHandleFactory.cpp