Arm NN: ShapesAreBroadcastCompatible Struct Reference
ShapesAreBroadcastCompatible Struct Reference
#include <LayerSupportRules.hpp>
Public Member Functions
unsigned int CalcInputSize (const TensorShape &in, const TensorShape &out, unsigned int idx)
ShapesAreBroadcastCompatible (const TensorInfo &in0, const TensorInfo &in1, const TensorInfo &out)
Public Member Functions inherited from Rule
bool operator() () const
Additional Inherited Members
Public Attributes inherited from Rule
bool m_Res = true
Detailed Description
Definition at line 153 of file LayerSupportRules.hpp.
Constructor & Destructor Documentation
ShapesAreBroadcastCompatible()
ShapesAreBroadcastCompatible (const TensorInfo & in0, const TensorInfo & in1, const TensorInfo & out) inline
Definition at line 162 of file LayerSupportRules.hpp.
     {
         const TensorShape& shape0 = in0.GetShape();
         const TensorShape& shape1 = in1.GetShape();
         const TensorShape& outShape = out.GetShape();
         for (unsigned int i=0; i < outShape.GetNumDimensions() && m_Res; i++)
         {
             unsigned int sizeOut = outShape[i];
             unsigned int sizeIn0 = CalcInputSize(shape0, outShape, i);
             unsigned int sizeIn1 = CalcInputSize(shape1, outShape, i);
             m_Res &= ((sizeIn0 == sizeOut) || (sizeIn0 == 1)) &&
                      ((sizeIn1 == sizeOut) || (sizeIn1 == 1));
         }
     }
References ShapesAreBroadcastCompatible::CalcInputSize(), TensorShape::GetNumDimensions(), TensorInfo::GetShape(), and Rule::m_Res.
Member Function Documentation
CalcInputSize()
unsigned int CalcInputSize (const TensorShape & in, const TensorShape & out, unsigned int idx) inline
Definition at line 155 of file LayerSupportRules.hpp.
     {
         unsigned int offset = out.GetNumDimensions() - in.GetNumDimensions();
         unsigned int sizeIn = (idx < offset) ? 1 : in[idx-offset];
         return sizeIn;
     }
References TensorShape::GetNumDimensions().
Referenced by ShapesAreBroadcastCompatible::ShapesAreBroadcastCompatible().
The documentation for this struct was generated from the following file:
src/backends/backendsCommon/LayerSupportRules.hpp