Arm NN: SpaceToDepthQueueDescriptor Struct Reference
SpaceToDepthQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< SpaceToDepthDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Additional Inherited Members
Public Attributes inherited from QueueDescriptorWithParameters< SpaceToDepthDescriptor >
SpaceToDepthDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions inherited from QueueDescriptorWithParameters< SpaceToDepthDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 390 of file WorkloadData.hpp.
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 1942 of file WorkloadData.cpp.
 {
     const std::string descriptorName{"SpaceToDepthQueueDescriptor"};
     ValidateNumInputs(workloadInfo,  descriptorName, 1);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     ValidateTensorNumDimensions(inputTensorInfo,  descriptorName, 4, "input");
     ValidateTensorNumDimensions(outputTensorInfo, descriptorName, 4, "output");
     std::vector<DataType> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::Signed32,
         DataType::Signed64
     };
     ValidateDataTypes(inputTensorInfo,  supportedTypes, descriptorName);
     ValidateDataTypes(outputTensorInfo, supportedTypes, descriptorName);
     ValidateTensorNumElementsMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
     if (m_Parameters.m_BlockSize == 0)
     {
         throw InvalidArgumentException(descriptorName + ": Block size cannot be 0.");
     }
     DataLayoutIndexed dimensionIndices(m_Parameters.m_DataLayout);
     const unsigned int wIndex = dimensionIndices.GetWidthIndex();
     const unsigned int hIndex = dimensionIndices.GetHeightIndex();
     const unsigned int cIndex = dimensionIndices.GetChannelsIndex();
     const TensorShape& inputShape = inputTensorInfo.GetShape();
     if (inputShape[hIndex] % m_Parameters.m_BlockSize != 0 || inputShape[wIndex]  % m_Parameters.m_BlockSize != 0)
     {
         throw InvalidArgumentException(descriptorName + ": Input shape must be divisible "
                                        "by block size in all spatial dimensions");
     }
     const TensorShape& outputShape = outputTensorInfo.GetShape();
     if (outputShape[cIndex] % (m_Parameters.m_BlockSize * m_Parameters.m_BlockSize) != 0)
     {
         throw InvalidArgumentException(descriptorName + ": The depth of the output tensor"
                                        "must be divisible by the square of block size." );
     }
 }
References armnn::BFloat16, armnn::Float16, armnn::Float32, DataLayoutIndexed::GetChannelsIndex(), DataLayoutIndexed::GetHeightIndex(), TensorInfo::GetShape(), DataLayoutIndexed::GetWidthIndex(), SpaceToDepthDescriptor::m_BlockSize, SpaceToDepthDescriptor::m_DataLayout, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< SpaceToDepthDescriptor >::m_Parameters, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::Signed32, armnn::Signed64, and QueueDescriptor::ValidateTensorNumDimensions().
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp