var searchData=
[
  ['datalayoutindexed',['DataLayoutIndexed',['../classarmnn_utils_1_1_data_layout_indexed.xhtml',1,'armnnUtils']]],
  ['deactivatetimelinereportingcommandhandler',['DeactivateTimelineReportingCommandHandler',['../classarmnn_1_1profiling_1_1_deactivate_timeline_reporting_command_handler.xhtml',1,'armnn::profiling']]],
  ['debuglayer',['DebugLayer',['../classarmnn_1_1_debug_layer.xhtml',1,'armnn']]],
  ['debugqueuedescriptor',['DebugQueueDescriptor',['../structarmnn_1_1_debug_queue_descriptor.xhtml',1,'armnn']]],
  ['decoder',['Decoder',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20bool_20_3e',['Decoder&lt; bool &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20float_20_3e',['Decoder&lt; float &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20int32_5ft_20_3e',['Decoder&lt; int32_t &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20int8_5ft_20_3e',['Decoder&lt; int8_t &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['delegate',['Delegate',['../classarmnn_delegate_1_1_delegate.xhtml',1,'armnnDelegate']]],
  ['delegatedata',['DelegateData',['../structarmnn_delegate_1_1_delegate_data.xhtml',1,'armnnDelegate']]],
  ['delegateoptions',['DelegateOptions',['../classarmnn_delegate_1_1_delegate_options.xhtml',1,'armnnDelegate']]],
  ['depthtospacedescriptorbuilder',['DepthToSpaceDescriptorBuilder',['../structarmnn_serializer_1_1_depth_to_space_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['depthtospacelayer',['DepthToSpaceLayer',['../classarmnn_1_1_depth_to_space_layer.xhtml',1,'armnn']]],
  ['depthtospacelayerbuilder',['DepthToSpaceLayerBuilder',['../structarmnn_serializer_1_1_depth_to_space_layer_builder.xhtml',1,'armnnSerializer']]],
  ['depthtospacequeuedescriptor',['DepthToSpaceQueueDescriptor',['../structarmnn_1_1_depth_to_space_queue_descriptor.xhtml',1,'armnn']]],
  ['depthwiseconvolution2ddescriptor',['DepthwiseConvolution2dDescriptor',['../structarmnn_1_1_depthwise_convolution2d_descriptor.xhtml',1,'armnn']]],
  ['depthwiseconvolution2ddescriptorbuilder',['DepthwiseConvolution2dDescriptorBuilder',['../structarmnn_serializer_1_1_depthwise_convolution2d_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['depthwiseconvolution2dlayer',['DepthwiseConvolution2dLayer',['../classarmnn_1_1_depthwise_convolution2d_layer.xhtml',1,'armnn']]],
  ['depthwiseconvolution2dlayerbuilder',['DepthwiseConvolution2dLayerBuilder',['../structarmnn_serializer_1_1_depthwise_convolution2d_layer_builder.xhtml',1,'armnnSerializer']]],
  ['depthwiseconvolution2dqueuedescriptor',['DepthwiseConvolution2dQueueDescriptor',['../structarmnn_1_1_depthwise_convolution2d_queue_descriptor.xhtml',1,'armnn']]],
  ['dequantizelayer',['DequantizeLayer',['../classarmnn_1_1_dequantize_layer.xhtml',1,'armnn']]],
  ['dequantizelayerbuilder',['DequantizeLayerBuilder',['../structarmnn_serializer_1_1_dequantize_layer_builder.xhtml',1,'armnnSerializer']]],
  ['dequantizequeuedescriptor',['DequantizeQueueDescriptor',['../structarmnn_1_1_dequantize_queue_descriptor.xhtml',1,'armnn']]],
  ['deserializerimpl',['DeserializerImpl',['../classarmnn_deserializer_1_1_i_deserializer_1_1_deserializer_impl.xhtml',1,'armnnDeserializer::IDeserializer']]],
  ['detection',['Detection',['../structyolov3_1_1_detection.xhtml',1,'yolov3']]],
  ['detectionpostprocessdescriptor',['DetectionPostProcessDescriptor',['../structarmnn_1_1_detection_post_process_descriptor.xhtml',1,'armnn']]],
  ['detectionpostprocessdescriptorbuilder',['DetectionPostProcessDescriptorBuilder',['../structarmnn_serializer_1_1_detection_post_process_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['detectionpostprocesslayer',['DetectionPostProcessLayer',['../classarmnn_1_1_detection_post_process_layer.xhtml',1,'armnn']]],
  ['detectionpostprocesslayerbuilder',['DetectionPostProcessLayerBuilder',['../structarmnn_serializer_1_1_detection_post_process_layer_builder.xhtml',1,'armnnSerializer']]],
  ['detectionpostprocessqueuedescriptor',['DetectionPostProcessQueueDescriptor',['../structarmnn_1_1_detection_post_process_queue_descriptor.xhtml',1,'armnn']]],
  ['device',['Device',['../classarmnn_1_1profiling_1_1_device.xhtml',1,'armnn::profiling']]],
  ['devicerecord',['DeviceRecord',['../structarmnn_1_1gatordmock_1_1_device_record.xhtml',1,'armnn::gatordmock']]],
  ['devicespec',['DeviceSpec',['../classarmnn_1_1_device_spec.xhtml',1,'armnn']]],
  ['directorycapturecommandhandler',['DirectoryCaptureCommandHandler',['../classarmnn_1_1profiling_1_1_directory_capture_command_handler.xhtml',1,'armnn::profiling']]],
  ['divisionlayer',['DivisionLayer',['../classarmnn_1_1_division_layer.xhtml',1,'armnn']]],
  ['divisionlayerbuilder',['DivisionLayerBuilder',['../structarmnn_serializer_1_1_division_layer_builder.xhtml',1,'armnnSerializer']]],
  ['divisionqueuedescriptor',['DivisionQueueDescriptor',['../structarmnn_1_1_division_queue_descriptor.xhtml',1,'armnn']]],
  ['dotattributeset',['DotAttributeSet',['../classarmnn_1_1_dot_attribute_set.xhtml',1,'armnn']]],
  ['dotbase',['DotBase',['../classarmnn_1_1_dot_base.xhtml',1,'armnn']]],
  ['dotdefaults',['DotDefaults',['../classarmnn_1_1_dot_defaults.xhtml',1,'armnn']]],
  ['dotedge',['DotEdge',['../classarmnn_1_1_dot_edge.xhtml',1,'armnn']]],
  ['dotgraph',['DotGraph',['../classarmnn_1_1_dot_graph.xhtml',1,'armnn']]],
  ['dotnode',['DotNode',['../classarmnn_1_1_dot_node.xhtml',1,'armnn']]],
  ['dynamicbackend',['DynamicBackend',['../classarmnn_1_1_dynamic_backend.xhtml',1,'armnn']]],
  ['dynamicbackendutils',['DynamicBackendUtils',['../classarmnn_1_1_dynamic_backend_utils.xhtml',1,'armnn']]]
];
