ArmNN: EthosnRefConvolution2dWorkload Class Reference
EthosnRefConvolution2dWorkload Class Reference
#include <EthosnRefConvolution2dWorkload.hpp>
Public Member Functions
EthosnRefConvolution2dWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info, bool winograd=false, std::string BlockConfigs="")
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< Convolution2dQueueDescriptor >
BaseWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const Convolution2dQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< Convolution2dQueueDescriptor >
Convolution2dQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 15 of file EthosnRefConvolution2dWorkload.hpp.
Constructor & Destructor Documentation
EthosnRefConvolution2dWorkload()
EthosnRefConvolution2dWorkload (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info, bool winograd = false, std::string BlockConfigs = "") explicit
Definition at line 34 of file EthosnRefConvolution2dWorkload.cpp.
References Convolution2dQueueDescriptor::m_Bias, Convolution2dDescriptor::m_BiasEnabled, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and Convolution2dQueueDescriptor::m_Weight.
         : BaseWorkload<Convolution2dQueueDescriptor>(descriptor, info)
 {
     m_Weight = std::make_unique<ScopedCpuTensorHandle>(*(descriptor.m_Weight));
     if (descriptor.m_Parameters.m_BiasEnabled)
     {
         m_Bias = std::make_unique<ScopedCpuTensorHandle>(*(descriptor.m_Bias));
     }
     m_Winograd = winograd;
     m_IsBlockConfigsWinograd2dCompatible = false;
     std::string part;
     std::size_t pos = 0;
     while (!(part = Split(BlockConfigs, ",", pos)).empty())
     {
         if (part == "16x8")
         {
             m_IsBlockConfigsWinograd2dCompatible = true;
         }
         else if (part == "8x16")
         {
             m_IsBlockConfigsWinograd2dCompatible = true;
         }
         else if (part == "8x8")
         {
             m_IsBlockConfigsWinograd2dCompatible = true;
         }
     }
     if (BlockConfigs == "")
     {
         m_IsBlockConfigsWinograd2dCompatible = true;
     }
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 72 of file EthosnRefConvolution2dWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_ETHOSN, armnn::ethosnref::CheckDataType(), armnn::ethosnref::DivideRoundUp(), TensorInfo::GetDataType(), DataLayoutIndexed::GetHeightIndex(), TensorInfo::GetQuantizationOffset(), TensorInfo::GetQuantizationScale(), TensorInfo::GetShape(), armnn::GetTensorInfo(), DataLayoutIndexed::GetWidthIndex(), Convolution2dDescriptor::m_BiasEnabled, BaseWorkload< Convolution2dQueueDescriptor >::m_Data, Convolution2dDescriptor::m_DataLayout, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, Convolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, armnn::QAsymmU8, armnn::QSymmS16, and armnn::QSymmS8.
{
     ARMNN_SCOPED_PROFILING_EVENT_ETHOSN("EthosnRefConvolution2dWorkload_Execute");
     const TensorInfo& inputInfo = GetTensorInfo(m_Data.m_Inputs[0]);
     const TensorInfo& weightsInfo = m_Weight->GetTensorInfo();
     bool useWinograd = false;
     if (m_Winograd == true) {
       const armnnUtils::DataLayoutIndexed dataLayoutIndexed(m_Data.m_Parameters.m_DataLayout);
       unsigned int weightsHeight = weightsInfo.GetShape()[dataLayoutIndexed.GetHeightIndex()];
       unsigned int weightsWidth  = weightsInfo.GetShape()[dataLayoutIndexed.GetWidthIndex()];
       unsigned int xStride       = m_Data.m_Parameters.m_StrideX;
       unsigned int yStride       = m_Data.m_Parameters.m_StrideY;
       bool isWinograd1D    = weightsWidth == 1 || weightsHeight == 1;
       bool isBlockSizeOk   = isWinograd1D? true : m_IsBlockConfigsWinograd2dCompatible;
       uint32_t numMultsDirect, numMultsWinograd;
       if ( weightsWidth == 1 || weightsHeight == 1)
       {
           // 1D convolution kernel dim w x 1 or 1 x h
           // numOfMultiplications = 2 * w or 2 * h                   DIRECT
           //                      = 4 * CEIL(W/3) or 4 * CEIL(H/3)   WINOGRAD
           numMultsDirect   = weightsWidth * weightsHeight * 2;
           numMultsWinograd = 4 * DivideRoundUp(weightsWidth * weightsHeight, 3);
       }
       else
       {
           // 2D convolution kernel dim w x h
           // numOfMultiplications = 4 * w * h                    DIRECT
           //                      = 16 * CEIL(W/3) * CEIL(H/3)   WINOGRAD
           numMultsDirect   = weightsWidth * weightsHeight * 4;
           numMultsWinograd = 16 *  DivideRoundUp(weightsWidth, 3) * DivideRoundUp(weightsHeight, 3);
       }
       if (numMultsWinograd < numMultsDirect &&
               isBlockSizeOk &&
               //TODO: FENCHSW-922 Need to revisit then when
               // SW add support for Winogard + Strided
               xStride == 1 && yStride == 1)
           useWinograd = true;
     }
     if (useWinograd == true)
     {
         std::cout << "[EthosNRef] Runnning in Winograd Mode.\n";
     }
     else
     {
         std::cout << "[EthosNRef] Runnning in Direct Mode.\n";
     }
     if (CheckDataType(DataType::QSymmS16, inputInfo.GetDataType(), weightsInfo.GetDataType())) {
         const int16_t* inputData = GetInputTensorData<int16_t>(0, m_Data);
         const int16_t* weightsData = m_Weight->template GetConstTensor<int16_t>();
         const int32_t* biasData = m_Data.m_Parameters.m_BiasEnabled ? m_Bias->template GetConstTensor<int32_t>() : nullptr;
         const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
         if(useWinograd == false)
         {
           EthosnRefConvImpl<armnn::Convolution2dQueueDescriptor, int16_t, int16_t, int32_t, int64_t>(
             m_Data,
             inputData, inputInfo.GetQuantizationScale(),  inputInfo.GetQuantizationOffset(),
             weightsData, weightsInfo.GetQuantizationScale(), weightsInfo.GetQuantizationOffset(),
             biasData,
             outputInfo.GetQuantizationScale(), outputInfo.GetQuantizationOffset(), weightsInfo);
         }
         else
         {
           EthosnRefWinogradConvImpl<armnn::Convolution2dQueueDescriptor, int16_t, int16_t, int32_t>(
             m_Data,
             inputData, inputInfo.GetQuantizationScale(),  inputInfo.GetQuantizationOffset(),
             weightsData, weightsInfo.GetQuantizationScale(), weightsInfo.GetQuantizationOffset(),
             biasData,
             outputInfo.GetQuantizationScale(), outputInfo.GetQuantizationOffset(), weightsInfo);
         }
     }
     else if (CheckDataType(DataType::QSymmS8, inputInfo.GetDataType(), weightsInfo.GetDataType())) {
         const int8_t* inputData = GetInputTensorData<int8_t>(0, m_Data);
         const int8_t* weightsData = m_Weight->template GetConstTensor<int8_t>();
         const int32_t* biasData = m_Data.m_Parameters.m_BiasEnabled ? m_Bias->template GetConstTensor<int32_t>() : nullptr;
         const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
         if(useWinograd == false)
         {
           EthosnRefConvImpl<armnn::Convolution2dQueueDescriptor, int8_t, int8_t, int32_t, int32_t>(
             m_Data,
             inputData, inputInfo.GetQuantizationScale(),  inputInfo.GetQuantizationOffset(),
             weightsData, weightsInfo.GetQuantizationScale(), weightsInfo.GetQuantizationOffset(),
             biasData,
             outputInfo.GetQuantizationScale(), outputInfo.GetQuantizationOffset(), weightsInfo);
         }
         else
         {
           EthosnRefWinogradConvImpl<armnn::Convolution2dQueueDescriptor, int8_t, int8_t, int32_t>(
             m_Data,
             inputData, inputInfo.GetQuantizationScale(),  inputInfo.GetQuantizationOffset(),
             weightsData, weightsInfo.GetQuantizationScale(), weightsInfo.GetQuantizationOffset(),
             biasData,
             outputInfo.GetQuantizationScale(), outputInfo.GetQuantizationOffset(), weightsInfo);
         }
     }
     else { // QAsymmU8
         assert(CheckDataType(DataType::QAsymmU8, inputInfo.GetDataType(), weightsInfo.GetDataType()));
         const uint8_t* inputData = GetInputTensorData<uint8_t>(0, m_Data);
         const uint8_t* weightsData = m_Weight->template GetConstTensor<uint8_t>();
         const int32_t* biasData = m_Data.m_Parameters.m_BiasEnabled ? m_Bias->template GetConstTensor<int32_t>() : nullptr;
         const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
         if(useWinograd == false)
         {
           EthosnRefConvImpl<armnn::Convolution2dQueueDescriptor, uint8_t, uint8_t, int32_t, int32_t>(
             m_Data,
             inputData, inputInfo.GetQuantizationScale(),  inputInfo.GetQuantizationOffset(),
             weightsData, weightsInfo.GetQuantizationScale(), weightsInfo.GetQuantizationOffset(),
             biasData,
             outputInfo.GetQuantizationScale(), outputInfo.GetQuantizationOffset(), weightsInfo);
         }
         else
         {
           EthosnRefWinogradConvImpl<armnn::Convolution2dQueueDescriptor, uint8_t, uint8_t, int32_t>(
             m_Data,
             inputData, inputInfo.GetQuantizationScale(),  inputInfo.GetQuantizationOffset(),
             weightsData, weightsInfo.GetQuantizationScale(), weightsInfo.GetQuantizationOffset(),
             biasData,
             outputInfo.GetQuantizationScale(), outputInfo.GetQuantizationOffset(), weightsInfo);
         }
     }
 }
The documentation for this class was generated from the following files:
src/backends/ethosnref/workloads/EthosnRefConvolution2dWorkload.hpp
src/backends/ethosnref/workloads/EthosnRefConvolution2dWorkload.cpp