ArmNN: ClassifierTestCaseProvider< TDatabase, InferenceModel > Class Template Reference
ClassifierTestCaseProvider< TDatabase, InferenceModel > Class Template Reference
#include <InferenceTest.hpp>
Public Member Functions
template<typename TConstructDatabaseCallable , typename TConstructModelCallable >
ClassifierTestCaseProvider (TConstructDatabaseCallable constructDatabase, TConstructModelCallable constructModel)
virtual void AddCommandLineOptions (cxxopts::Options &options, std::vector< std::string > &required) override
virtual bool ProcessCommandLineOptions (const InferenceTestOptions &commonOptions) override
virtual std::unique_ptr< IInferenceTestCase > GetTestCase (unsigned int testCaseId) override
virtual bool OnInferenceTestFinished () override
Public Member Functions inherited from IInferenceTestCaseProvider
virtual ~IInferenceTestCaseProvider ()
Detailed Description
template<typename TDatabase, typename InferenceModel>
class armnn::test::ClassifierTestCaseProvider< TDatabase, InferenceModel >
Definition at line 179 of file InferenceTest.hpp.
Constructor & Destructor Documentation
ClassifierTestCaseProvider()
ClassifierTestCaseProvider (TConstructDatabaseCallable constructDatabase, TConstructModelCallable constructModel)
Definition at line 183 of file InferenceTest.inl.
     : m_ConstructModel(constructModel)
     , m_ConstructDatabase(constructDatabase)
     , m_NumInferences(0)
     , m_NumCorrectInferences(0)
 {
 }
Member Function Documentation
AddCommandLineOptions()
void AddCommandLineOptions (cxxopts::Options & options, std::vector< std::string > & required) override virtual
Reimplemented from IInferenceTestCaseProvider.
Definition at line 193 of file InferenceTest.inl.
References InferenceModel< IParser, TDataType >::AddCommandLineOptions().
 {
     options
         .allow_unrecognised_options()
         .add_options()
             ("validation-file-in",
              "Reads expected predictions from the given file and confirms they match the actual predictions.",
              cxxopts::value<std::string>(m_ValidationFileIn)->default_value(""))
             ("validation-file-out", "Predictions are saved to the given file for later use via --validation-file-in.",
              cxxopts::value<std::string>(m_ValidationFileOut)->default_value(""))
             ("d,data-dir", "Path to directory containing test data", cxxopts::value<std::string>(m_DataDir));
     required.emplace_back("data-dir"); //add to required arguments to check
     InferenceModel::AddCommandLineOptions(options, m_ModelCommandLineOptions, required);
 }
GetTestCase()
std::unique_ptr< IInferenceTestCase > GetTestCase (unsigned int testCaseId) override virtual
Implements IInferenceTestCaseProvider.
Definition at line 239 of file InferenceTest.inl.
 {
     std::unique_ptr<typename TDatabase::TTestCaseData> testCaseData = m_Database->GetTestCaseData(testCaseId);
     if (testCaseData == nullptr)
     {
         return nullptr;
     }
     return std::make_unique<ClassifierTestCase<TDatabase, InferenceModel>>(
         m_NumInferences,
         m_NumCorrectInferences,
         m_ValidationPredictions,
         m_ValidationFileOut.empty() ? nullptr : &m_ValidationPredictionsOut,
         *m_Model,
         testCaseId,
         testCaseData->m_Label,
         std::move(testCaseData->m_InputImage));
 }
OnInferenceTestFinished()
bool OnInferenceTestFinished () override virtual
Reimplemented from IInferenceTestCaseProvider.
Definition at line 259 of file InferenceTest.inl.
References ARMNN_LOG, armnn::error, armnn::info, and armnn::numeric_cast().
 {
     const double accuracy = armnn::numeric_cast<double>(m_NumCorrectInferences) /
         armnn::numeric_cast<double>(m_NumInferences);
     ARMNN_LOG(info) << std::fixed << std::setprecision(3) << "Overall accuracy: " << accuracy;
     // If a validation file was requested as output, the predictions are saved to it.
     if (!m_ValidationFileOut.empty())
     {
         std::ofstream validationFileOut(m_ValidationFileOut.c_str(), std::ios_base::trunc | std::ios_base::out);
         if (validationFileOut.good())
         {
             for (const unsigned int prediction : m_ValidationPredictionsOut)
             {
                 validationFileOut << prediction << std::endl;
             }
         }
         else
         {
             ARMNN_LOG(error) << "Failed to open output validation file: " << m_ValidationFileOut;
             return false;
         }
     }
     return true;
 }
ProcessCommandLineOptions()
bool ProcessCommandLineOptions (const InferenceTestOptions & commonOptions) override virtual
Reimplemented from IInferenceTestCaseProvider.
Definition at line 212 of file InferenceTest.inl.
References armnn::test::ValidateDirectory().
 {
     if (!ValidateDirectory(m_DataDir))
     {
         return false;
     }
     ReadPredictions();
     m_Model = m_ConstructModel(commonOptions, m_ModelCommandLineOptions);
     if (!m_Model)
     {
         return false;
     }
     m_Database = std::make_unique<TDatabase>(m_ConstructDatabase(m_DataDir.c_str(), *m_Model));
     if (!m_Database)
     {
         return false;
     }
     return true;
 }
The documentation for this class was generated from the following files:
tests/InferenceTest.hpp
tests/InferenceTest.inl