ArmNN: EthosnRefBackend Class Reference
EthosnRefBackend Class Reference
#include <EthosnRefBackend.hpp>
Public Member Functions
EthosnRefBackend ()=default
~EthosnRefBackend ()=default
const BackendId & GetId () const override
IBackendInternal::IMemoryManagerUniquePtr CreateMemoryManager () const override
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IBackendInternal::IMemoryManagerSharedPtr &memoryManager=nullptr) const override
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry) const override
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const override
Create the runtime context of the backend.
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions &creationOptions, IBackendProfilingPtr &backendProfiling) override
Create context specifically used for profiling interaction from backends.
IBackendInternal::Optimizations GetOptimizations () const override
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport () const override
OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph) const override
std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const override
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &registry) override
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
Public Member Functions inherited from IBackendInternal
~IBackendInternal () override=default
Allow backends created by the factory function to be destroyed through IBackendInternal.
virtual IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr &memoryManager, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags) const
virtual IBackendSpecificModelContextPtr CreateBackendSpecificModelContext (const ModelOptions &modelOptions) const
virtual ILayerSupportSharedPtr GetLayerSupport (const ModelOptions &modelOptions) const
virtual OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph, const ModelOptions &modelOptions) const
bool SupportsTensorAllocatorAPI () const
ITensorHandleFactory::FactoryId GetBackwardCompatibleFavoriteHandleFactory ()
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &registry, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags)
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
virtual BackendCapabilities GetCapabilities () const
Returns a BackendCapability if the backend lists the capability The BackendCapability must then be inspected to check whether or not that BackendCapability is supported Otherwise returns an EmptyOptional if the BackendCapability is unlisted.
virtual bool UseCustomMemoryAllocator (std::shared_ptr< ICustomAllocator > allocator, armnn::Optional< std::string &> errMsg)
Signals the backend to use a custom memory allocator provided by the user.
virtual std::unique_ptr< ICustomAllocator > GetDefaultAllocator () const
Returns the default memory allocator for the backend.
virtual unsigned int GetNumberOfCacheFiles () const
Returns the number of files cached if backend supports caching.
virtual ExecutionData CreateExecutionData (WorkingMemDescriptor &workingMemDescriptor) const
Returns ExecutionData for the backend.
virtual void UpdateExecutionData (ExecutionData &executionData, WorkingMemDescriptor &workingMemDescriptor) const
Update the ExecutionData for a layer.
Static Public Member Functions
static const BackendId & GetIdStatic ()
Static Public Member Functions inherited from IBackendInternal
static constexpr BackendVersion GetApiVersion ()
Returns the version of the Backend API.
Additional Inherited Members
Public Types inherited from IBackendInternal
using IWorkloadFactoryPtr = std::unique_ptr< IWorkloadFactory >
using IBackendContextPtr = std::unique_ptr< IBackendContext >
using IBackendProfilingContextPtr = std::shared_ptr< arm::pipe::IBackendProfilingContext >
This is the bridge between backend and backend profiling we'll keep it in the backend namespace.
using IBackendProfilingPtr = std::unique_ptr< arm::pipe::IBackendProfiling >
using ILayerSupportSharedPtr = std::shared_ptr< ILayerSupport >
using IBackendSpecificModelContextPtr = std::shared_ptr< IBackendModelContext >
using IMemoryManagerUniquePtr = std::unique_ptr< IMemoryManager >
using IMemoryManagerSharedPtr = std::shared_ptr< IMemoryManager >
Protected Member Functions inherited from IBackendInternal
IBackendInternal ()=default
Creation must be done through a specific backend interface.
Protected Member Functions inherited from IBackend
IBackend ()
virtual ~IBackend ()
Detailed Description
Definition at line 12 of file EthosnRefBackend.hpp.
Constructor & Destructor Documentation
EthosnRefBackend()
EthosnRefBackend () default
~EthosnRefBackend()
~EthosnRefBackend () default
Member Function Documentation
CreateBackendContext()
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const override virtual
Create the runtime context of the backend.
Implementations may return a default-constructed IBackendContextPtr if no context is needed at runtime. Implementations must throw BackendUnavailableException if the backend cannot be used (for example, necessary accelerator hardware is not present). The default implementation always returns a default-constructed pointer.
Reimplemented from IBackendInternal.
Definition at line 50 of file EthosnRefBackend.cpp.
References BackendOptions::Var::AsBool(), BackendOptions::Var::AsString(), EthosnRefBackend::GetId(), BackendOptions::BackendOption::GetName(), BackendOptions::BackendOption::GetValue(), BackendOptions::Var::IsBool(), BackendOptions::Var::IsString(), and IRuntime::CreationOptions::m_BackendOptions.
Referenced by EthosnRefBackend::GetId().
 {
    VarGlobal_EnableWinograd = false;
    VarGlobal_BlockConfigs = "";
    for (auto optionsGroup : creationOptions.m_BackendOptions)
    {
       if (optionsGroup.GetBackendId() == EthosnRefBackend::GetId())
       {
          for (size_t i=0; i < optionsGroup.GetOptionCount(); i++)
          {
             const BackendOptions::BackendOption option = optionsGroup.GetOption(i);
             if(option.GetName() == "EnableWinograd" && option.GetValue().IsBool() == true) {
                VarGlobal_EnableWinograd = option.GetValue().AsBool();
             }
             if(option.GetName() == "BlockConfigs" && option.GetValue().IsString() == true) {
                VarGlobal_BlockConfigs = option.GetValue().AsString();
             }
          }
       }
    }
    return IBackendContextPtr{};
 }
CreateBackendProfilingContext()
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions & creationOptions, IBackendProfilingPtr & backendProfiling) override virtual
Create context specifically used for profiling interaction from backends.
Reimplemented from IBackendInternal.
Definition at line 75 of file EthosnRefBackend.cpp.
Referenced by EthosnRefBackend::GetId().
 {
     return IBackendProfilingContextPtr{};
 }
CreateMemoryManager()
IBackendInternal::IMemoryManagerUniquePtr CreateMemoryManager () const override virtual
Reimplemented from IBackendInternal.
Definition at line 81 of file EthosnRefBackend.cpp.
Referenced by EthosnRefBackend::GetId().
 {
     return std::make_unique<EthosnRefMemoryManager>();
 }
CreateWorkloadFactory() [1/2]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IBackendInternal::IMemoryManagerSharedPtr & memoryManager = nullptr) const override virtual
Implements IBackendInternal.
Definition at line 33 of file EthosnRefBackend.cpp.
Referenced by EthosnRefBackend::GetId().
 {
     return std::make_unique<EthosnRefWorkloadFactory>(PolymorphicPointerDowncast<EthosnRefMemoryManager>(memoryManager), VarGlobal_EnableWinograd, VarGlobal_BlockConfigs);
 }
CreateWorkloadFactory() [2/2]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry & tensorHandleFactoryRegistry) const override virtual
Reimplemented from IBackendInternal.
Definition at line 39 of file EthosnRefBackend.cpp.
References TensorHandleFactoryRegistry::RegisterFactory(), and TensorHandleFactoryRegistry::RegisterMemoryManager().
 {
     auto memoryManager = std::make_shared<EthosnRefMemoryManager>();
     tensorHandleFactoryRegistry.RegisterMemoryManager(memoryManager);
     tensorHandleFactoryRegistry.RegisterFactory(std::make_unique<EthosnRefTensorHandleFactory>(memoryManager));
     return std::make_unique<EthosnRefWorkloadFactory>(PolymorphicPointerDowncast<EthosnRefMemoryManager>(memoryManager), VarGlobal_EnableWinograd, VarGlobal_BlockConfigs);
 }
GetHandleFactoryPreferences()
std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const override virtual
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
Reimplemented from IBackendInternal.
Definition at line 106 of file EthosnRefBackend.cpp.
References EthosnRefTensorHandleFactory::GetIdStatic().
Referenced by EthosnRefBackend::GetId().
 {
     return std::vector<ITensorHandleFactory::FactoryId> { EthosnRefTensorHandleFactory::GetIdStatic() };
 }
GetId()
const BackendId& GetId () const inline override virtual
Implements IBackend.
Definition at line 19 of file EthosnRefBackend.hpp.
References EthosnRefBackend::CreateBackendContext(), EthosnRefBackend::CreateBackendProfilingContext(), EthosnRefBackend::CreateMemoryManager(), EthosnRefBackend::CreateWorkloadFactory(), EthosnRefBackend::GetHandleFactoryPreferences(), EthosnRefBackend::GetIdStatic(), EthosnRefBackend::GetLayerSupport(), EthosnRefBackend::GetOptimizations(), EthosnRefBackend::OptimizeSubgraphView(), and EthosnRefBackend::RegisterTensorHandleFactories().
Referenced by EthosnRefBackend::CreateBackendContext().
 { return GetIdStatic(); }
GetIdStatic()
const BackendId & GetIdStatic () static
Definition at line 27 of file EthosnRefBackend.cpp.
References armnn::EthosnRefBackendId().
Referenced by EthosnRefBackend::GetId().
 {
     static const BackendId s_Id{EthosnRefBackendId()};
     return s_Id;
 }
GetLayerSupport()
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport () const override virtual
Implements IBackendInternal.
Definition at line 91 of file EthosnRefBackend.cpp.
Referenced by EthosnRefBackend::GetId().
 {
     static ILayerSupportSharedPtr layerSupport{new EthosnRefLayerSupport};
     return layerSupport;
 }
GetOptimizations()
IBackendInternal::Optimizations GetOptimizations () const override
Definition at line 86 of file EthosnRefBackend.cpp.
Referenced by EthosnRefBackend::GetId().
 {
     return Optimizations{};
 }
OptimizeSubgraphView()
OptimizationViews OptimizeSubgraphView (const SubgraphView & subgraph) const override virtual
Reimplemented from IBackendInternal.
Definition at line 97 of file EthosnRefBackend.cpp.
References OptimizationViews::AddUntouchedSubgraph().
Referenced by EthosnRefBackend::GetId().
 {
     OptimizationViews optimizationViews;
     optimizationViews.AddUntouchedSubgraph(SubgraphView(subgraph));
     return optimizationViews;
 }
RegisterTensorHandleFactories()
void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &) override virtual
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
Reimplemented from IBackendInternal.
Definition at line 111 of file EthosnRefBackend.cpp.
References TensorHandleFactoryRegistry::RegisterFactory(), and TensorHandleFactoryRegistry::RegisterMemoryManager().
Referenced by EthosnRefBackend::GetId().
 {
     auto memoryManager = std::make_shared<EthosnRefMemoryManager>();
     registry.RegisterMemoryManager(memoryManager);
     registry.RegisterFactory(std::make_unique<EthosnRefTensorHandleFactory>(memoryManager));
 }
The documentation for this class was generated from the following files:
src/backends/ethosnref/EthosnRefBackend.hpp
src/backends/ethosnref/EthosnRefBackend.cpp