ArmNN: ClConvolution2dWorkload Class Reference
ClConvolution2dWorkload Class Reference
#include <ClConvolution2dWorkload.hpp>
Public Member Functions
ClConvolution2dWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager, const arm_compute::CLCompileContext &clCompileContext, const bool isFastMathEnabled=false)
void Execute () const override
arm_compute::ConvolutionMethod GetConvolutionMethod () const
bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from ClBaseWorkload< Convolution2dQueueDescriptor >
ClBaseWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< Convolution2dQueueDescriptor >
BaseWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const Convolution2dQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Protected Member Functions
void Reconfigure () override
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< Convolution2dQueueDescriptor >
Convolution2dQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 31 of file ClConvolution2dWorkload.hpp.
Constructor & Destructor Documentation
ClConvolution2dWorkload()
ClConvolution2dWorkload (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager, const arm_compute::CLCompileContext & clCompileContext, const bool isFastMathEnabled = false)
Definition at line 72 of file ClConvolution2dWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, and armnn::Undefined.
     : ClBaseWorkload<Convolution2dQueueDescriptor>(descriptor, info)
     , m_ConvolutionLayer(memoryManager)
 {
     ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClConvolution2dWorkload");
     const arm_compute::Size2D aclDilationInfo = BuildArmComputeSize2D(m_Data.m_Parameters.m_DilationX,
                                                                       m_Data.m_Parameters.m_DilationY);
     uint32_t numInputs = m_Data.m_Parameters.m_BiasEnabled ? 3: 2;
     m_Data.ValidateInputsOutputs("ClConvolution2dWorkload", numInputs, 1);
     arm_compute::ICLTensor& input  = static_cast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = static_cast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     arm_compute::ICLTensor& weights = static_cast<IClTensorHandle*>(m_Data.m_Inputs[1])->GetTensor();
     arm_compute::ICLTensor* bias  = nullptr;
     if (m_Data.m_Parameters.m_BiasEnabled)
     {
         bias = &static_cast<IClTensorHandle*>(m_Data.m_Inputs[2])->GetTensor();
     }
     // Create Proxy tensor and set the initial tensor handle to it
     m_InputProxy = std::make_unique<ICLTensorProxy>(&input);
     m_OutputProxy = std::make_unique<ICLTensorProxy>(&output);
     arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
     input.info()->set_data_layout(aclDataLayout);
     output.info()->set_data_layout(aclDataLayout);
     weights.info()->set_data_layout(aclDataLayout);
     arm_compute::PadStrideInfo padStrideInfo = BuildArmComputePadStrideInfo(m_Data.m_Parameters);
     const arm_compute::ActivationLayerInfo activationInfo = ConvertAdditionalInfoToAclActivationLayerInfo(descriptor);
     {
         ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClConvolution2dWorkload_configure");
         m_ConvolutionLayer.configure(clCompileContext,
                                      m_InputProxy.get(),
                                      &weights,
                                      bias,
                                      m_OutputProxy.get(),
                                      padStrideInfo,
                                      arm_compute::WeightsInfo(),
                                      aclDilationInfo,
                                      activationInfo,
                                      isFastMathEnabled);
     }
     m_ConvolutionMethod =
         m_ConvolutionLayer.get_convolution_method(input.info(),
                                                   weights.info(),
                                                   output.info(),
                                                   padStrideInfo,
                                                   arm_compute::WeightsInfo(),
                                                   activationInfo,
                                                   arm_compute::CLScheduler::get().target(),
                                                   aclDilationInfo,
                                                   isFastMathEnabled);
      // Add details for profiling output
     WorkloadInfo detailsInfo;
     detailsInfo.m_InputTensorInfos = info.m_InputTensorInfos;
     detailsInfo.m_OutputTensorInfos = info.m_OutputTensorInfos;
     detailsInfo.m_WeightsTensorInfo = armnn::Optional<armnn::TensorInfo>(descriptor.m_Weight->GetTensorInfo());
     detailsInfo.m_ConvolutionMethod = armnn::Optional<std::string>(GetConvolutionMethodString(m_ConvolutionMethod));
     if (descriptor.m_Parameters.m_BiasEnabled)
     {
         detailsInfo.m_BiasTensorInfo = armnn::Optional<armnn::TensorInfo>(descriptor.m_Bias->GetTensorInfo());
     }
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("ClConvolution2dWorkload_Construct",
                                          descriptor.m_Parameters,
                                          detailsInfo,
                                          GetGuid());
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 155 of file ClConvolution2dWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< Convolution2dQueueDescriptor >::GetGuid(), and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClConvolution2dWorkload_Execute", GetGuid());
     RunClFunction(m_ConvolutionLayer, CHECK_LOCATION());
 }
GetConvolutionMethod()
arm_compute::ConvolutionMethod GetConvolutionMethod () const
Definition at line 161 of file ClConvolution2dWorkload.cpp.
 {
     return m_ConvolutionMethod;
 }
Reconfigure()
void Reconfigure () override protected virtual
Reimplemented from ClBaseWorkload< Convolution2dQueueDescriptor >.
Definition at line 166 of file ClConvolution2dWorkload.cpp.
References BaseWorkload< Convolution2dQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, and QueueDescriptor::m_Outputs.
Referenced by ClConvolution2dWorkload::SupportsTensorHandleReplacement().
 {
     arm_compute::ICLTensor& input  = static_cast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = static_cast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     m_InputProxy->set(&input);
     m_OutputProxy->set(&output);
 }
SupportsTensorHandleReplacement()
bool SupportsTensorHandleReplacement () const inline override virtual
Reimplemented from BaseWorkload< Convolution2dQueueDescriptor >.
Definition at line 43 of file ClConvolution2dWorkload.hpp.
References BaseWorkload< Convolution2dQueueDescriptor >::m_Data, Convolution2dDescriptor::m_DataLayout, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::NCHW, and ClConvolution2dWorkload::Reconfigure().
     {
         // NCHW DataLayout on ACL still uses paddding for alignment on the Conv2d workload so importing is unreliable.
         if (m_Data.m_Parameters.m_DataLayout == DataLayout::NCHW)
         {
             return false;
         }
         else
         {
             return true;
         }
     }
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClConvolution2dWorkload.hpp
src/backends/cl/workloads/ClConvolution2dWorkload.cpp