ArmNN: LayerSupportBase Class Reference
LayerSupportBase Class Reference
#include <LayerSupportBase.hpp>
Public Member Functions
bool IsLayerSupported (const LayerType &type, const std::vector< TensorInfo > &infos, const BaseDescriptor &descriptor, const Optional< LstmInputParamsInfo > &lstmParamsInfo=EmptyOptional(), const Optional< QuantizedLstmInputParamsInfo > &quantizedLstmParamsInfo=EmptyOptional(), Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsActivationSupported (const TensorInfo &input, const TensorInfo &output, const ActivationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsAdditionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsArgMinMaxSupported (const TensorInfo &input, const TensorInfo &output, const ArgMinMaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &mean, const TensorInfo &var, const TensorInfo &beta, const TensorInfo &gamma, const BatchNormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsBatchToSpaceNdSupported (const TensorInfo &input, const TensorInfo &output, const BatchToSpaceNdDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsCastSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsChannelShuffleSupported (const TensorInfo &input, const TensorInfo &output, const ChannelShuffleDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsComparisonSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const ComparisonDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConcatSupported (const std::vector< const TensorInfo *> inputs, const TensorInfo &output, const OriginsDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConstantSupported (const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertBf16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp16ToFp32Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToBf16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvertFp32ToFp16Supported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsConvolution3dSupported (const TensorInfo &input, const TensorInfo &output, const Convolution3dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDebugSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthToSpaceSupported (const TensorInfo &input, const TensorInfo &output, const DepthToSpaceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDequantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDetectionPostProcessSupported (const TensorInfo &boxEncodings, const TensorInfo &scores, const TensorInfo &anchors, const TensorInfo &detectionBoxes, const TensorInfo &detectionClasses, const TensorInfo &detectionScores, const TensorInfo &numDetections, const DetectionPostProcessDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo &input, const TensorInfo &output, const DepthwiseConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsDivisionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsElementwiseUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFakeQuantizationSupported (const TensorInfo &input, const FakeQuantizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
virtual bool IsFillSupported (const TensorInfo &input, const TensorInfo &output, const FillDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFloorSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsFullyConnectedSupported (const TensorInfo &input, const TensorInfo &output, const TensorInfo &weights, const TensorInfo &biases, const FullyConnectedDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsGatherSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const GatherDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsInputSupported (const TensorInfo &input, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsInstanceNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const InstanceNormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsL2NormalizationSupported (const TensorInfo &input, const TensorInfo &output, const L2NormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalBinarySupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, const LogicalBinaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogicalUnarySupported (const TensorInfo &input, const TensorInfo &output, const ElementwiseUnaryDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLogSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const LogSoftmaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &scratchBuffer, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMaximumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMeanSupported (const TensorInfo &input, const TensorInfo &output, const MeanDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMemCopySupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMemImportSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMergeSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMinimumSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsMultiplicationSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsNormalizationSupported (const TensorInfo &input, const TensorInfo &output, const NormalizationDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsOutputSupported (const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPadSupported (const TensorInfo &input, const TensorInfo &output, const PadDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPermuteSupported (const TensorInfo &input, const TensorInfo &output, const PermuteDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling2dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling2dDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPooling3dSupported (const TensorInfo &input, const TensorInfo &output, const Pooling3dDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPreCompiledSupported (const TensorInfo &input, const PreCompiledDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsPreluSupported (const TensorInfo &input, const TensorInfo &alpha, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported) const override
bool IsQuantizeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsQLstmSupported (const TensorInfo &input, const TensorInfo &previousOutputIn, const TensorInfo &previousCellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const QLstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsQuantizedLstmSupported (const TensorInfo &input, const TensorInfo &previousCellStateIn, const TensorInfo &previousOutputIn, const TensorInfo &cellStateOut, const TensorInfo &output, const QuantizedLstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsRankSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported) const override
bool IsReduceSupported (const TensorInfo &input, const TensorInfo &output, const ReduceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsReshapeSupported (const TensorInfo &input, const TensorInfo &output, const ReshapeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsResizeSupported (const TensorInfo &input, const TensorInfo &output, const ResizeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsShapeSupported (const TensorInfo &input, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSliceSupported (const TensorInfo &input, const TensorInfo &output, const SliceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSoftmaxSupported (const TensorInfo &input, const TensorInfo &output, const SoftmaxDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToBatchNdSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToBatchNdDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSpaceToDepthSupported (const TensorInfo &input, const TensorInfo &output, const SpaceToDepthDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSplitterSupported (const TensorInfo &input, const std::vector< std::reference_wrapper< TensorInfo >> &outputs, const ViewsDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStackSupported (const std::vector< const TensorInfo *> &inputs, const TensorInfo &output, const StackDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStandInSupported (const std::vector< const TensorInfo *> &inputs, const std::vector< const TensorInfo *> &outputs, const StandInDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsStridedSliceSupported (const TensorInfo &input, const TensorInfo &output, const StridedSliceDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSubtractionSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsSwitchSupported (const TensorInfo &input0, const TensorInfo &input1, const TensorInfo &output0, const TensorInfo &output1, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeConvolution2dSupported (const TensorInfo &input, const TensorInfo &output, const TransposeConvolution2dDescriptor &descriptor, const TensorInfo &weights, const Optional< TensorInfo > &biases, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsTransposeSupported (const TensorInfo &input, const TensorInfo &output, const TransposeDescriptor &descriptor, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo &input, const TensorInfo &outputStateIn, const TensorInfo &cellStateIn, const TensorInfo &outputStateOut, const TensorInfo &cellStateOut, const TensorInfo &output, const LstmDescriptor &descriptor, const LstmInputParamsInfo &paramsInfo, Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const override
Public Member Functions inherited from ILayerSupport
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsActivationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsAdditionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsArgMinMaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchToSpaceNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsCastSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsChannelShuffleSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsComparisonSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertBf16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp32ToBf16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp32ToFp16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDebugSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthToSpaceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDequantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDetectionPostProcessSupported(const TensorInfo &boxEncodings
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDilatedDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDivisionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsElementwiseUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFakeQuantizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFillSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFloorSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFullyConnectedSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsGatherSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInputSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInstanceNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsL2NormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalBinarySupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMaximumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMeanSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemCopySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemImportSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMergeSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMinimumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMultiplicationSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsOutputSupported(const TensorInfo &output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPadSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPermuteSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreCompiledSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreluSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizedLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsRankSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReduceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReshapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsResizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsShapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSliceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToBatchNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToDepthSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSplitterSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSubtractionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSwitchSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsUnidirectionalSequenceLstmSupported(const TensorInfo &input
Additional Inherited Members
Public Attributes inherited from ILayerSupport
const TensorInfo & output
const TensorInfo const ActivationDescriptor & descriptor
const TensorInfo const ActivationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & input1
const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ArgMinMaxDescriptor & descriptor
const TensorInfo const ArgMinMaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & mean
const TensorInfo const TensorInfo const TensorInfo & var
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & beta
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & gamma
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const BatchToSpaceNdDescriptor & descriptor
const TensorInfo const BatchToSpaceNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ChannelShuffleDescriptor & descriptor
const TensorInfo const ChannelShuffleDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const ComparisonDescriptor & descriptor
const TensorInfo const TensorInfo const ComparisonDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConcatSupported(const std Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution2dDescriptor & descriptor
const TensorInfo const Convolution2dDescriptor const TensorInfo & weights
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution3dDescriptor & descriptor
const TensorInfo const Convolution3dDescriptor const TensorInfo & weights
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthToSpaceDescriptor & descriptor
const TensorInfo const DepthToSpaceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthwiseConvolution2dDescriptor & descriptor
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & scores
const TensorInfo const TensorInfo & anchors
const TensorInfo const TensorInfo const TensorInfo & detectionBoxes
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionClasses
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionScores
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & numDetections
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const =0
const TensorInfo const ElementwiseUnaryDescriptor & descriptor
const TensorInfo const ElementwiseUnaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const FakeQuantizationDescriptor & descriptor
const FakeQuantizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const FillDescriptor & descriptor
const TensorInfo const FillDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & weights
const TensorInfo const TensorInfo const TensorInfo & biases
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const GatherDescriptor & descriptor
const TensorInfo const TensorInfo const GatherDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const InstanceNormalizationDescriptor & descriptor
const TensorInfo const InstanceNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const L2NormalizationDescriptor & descriptor
const TensorInfo const L2NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const LogicalBinaryDescriptor & descriptor
const TensorInfo const TensorInfo const LogicalBinaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const LogSoftmaxDescriptor & descriptor
const TensorInfo const LogSoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & outputStateIn
const TensorInfo const TensorInfo & cellStateIn
const TensorInfo const TensorInfo const TensorInfo & scratchBuffer
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const MeanDescriptor & descriptor
const TensorInfo const MeanDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & ouput
const TensorInfo const NormalizationDescriptor & descriptor
const TensorInfo const NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PadDescriptor & descriptor
const TensorInfo const PadDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PermuteDescriptor & descriptor
const TensorInfo const PermuteDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling2dDescriptor & descriptor
const TensorInfo const Pooling2dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling3dDescriptor & descriptor
const TensorInfo const Pooling3dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const PreCompiledDescriptor & descriptor
const PreCompiledDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & alpha
const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReduceDescriptor & descriptor
const TensorInfo const ReduceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReshapeDescriptor & descriptor
const TensorInfo const ReshapeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ResizeDescriptor & descriptor
const TensorInfo const ResizeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SliceDescriptor & descriptor
const TensorInfo const SliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SoftmaxDescriptor & descriptor
const TensorInfo const SoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToBatchNdDescriptor & descriptor
const TensorInfo const SpaceToBatchNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToDepthDescriptor & descriptor
const TensorInfo const SpaceToDepthDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const std::vector< std::reference_wrapper< TensorInfo > > & outputs
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor & descriptor
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo & output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor & descriptor
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & output0
const TensorInfo const TensorInfo const TensorInfo & output1
const TensorInfo const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeConvolution2dDescriptor & descriptor
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeDescriptor & descriptor
const TensorInfo const TransposeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Protected Member Functions inherited from ILayerSupport
ILayerSupport ()
virtual ~ILayerSupport ()
Detailed Description
Definition at line 13 of file LayerSupportBase.hpp.
Member Function Documentation
IsActivationSupported()
bool IsActivationSupported (const TensorInfo & input, const TensorInfo & output, const ActivationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 85 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsAdditionSupported()
bool IsAdditionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 93 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsArgMinMaxSupported()
bool IsArgMinMaxSupported (const TensorInfo & input, const TensorInfo & output, const ArgMinMaxDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 101 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsBatchNormalizationSupported()
bool IsBatchNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & mean, const TensorInfo & var, const TensorInfo & beta, const TensorInfo & gamma, const BatchNormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 109 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsBatchToSpaceNdSupported()
bool IsBatchToSpaceNdSupported (const TensorInfo & input, const TensorInfo & output, const BatchToSpaceNdDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 121 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsCastSupported()
bool IsCastSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 129 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsChannelShuffleSupported()
bool IsChannelShuffleSupported (const TensorInfo & input, const TensorInfo & output, const ChannelShuffleDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 136 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsComparisonSupported()
bool IsComparisonSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const ComparisonDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 144 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConcatSupported()
bool IsConcatSupported (const std::vector< const TensorInfo *> inputs, const TensorInfo & output, const OriginsDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 153 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConstantSupported()
bool IsConstantSupported (const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 161 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConvertBf16ToFp32Supported()
bool IsConvertBf16ToFp32Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 167 of file LayerSupportBase.cpp.
Referenced by ClLayerSupport::IsLayerSupported().
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConvertFp16ToFp32Supported()
bool IsConvertFp16ToFp32Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 174 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConvertFp32ToBf16Supported()
bool IsConvertFp32ToBf16Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 181 of file LayerSupportBase.cpp.
Referenced by ClLayerSupport::IsLayerSupported().
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConvertFp32ToFp16Supported()
bool IsConvertFp32ToFp16Supported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 189 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConvolution2dSupported()
bool IsConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 196 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsConvolution3dSupported()
bool IsConvolution3dSupported (const TensorInfo & input, const TensorInfo & output, const Convolution3dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 206 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDebugSupported()
bool IsDebugSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 216 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDepthToSpaceSupported()
bool IsDepthToSpaceSupported (const TensorInfo & input, const TensorInfo & output, const DepthToSpaceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 223 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDepthwiseConvolutionSupported()
bool IsDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 231 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDequantizeSupported()
bool IsDequantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 241 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDetectionPostProcessSupported()
bool IsDetectionPostProcessSupported (const TensorInfo & boxEncodings, const TensorInfo & scores, const TensorInfo & anchors, const TensorInfo & detectionBoxes, const TensorInfo & detectionClasses, const TensorInfo & detectionScores, const TensorInfo & numDetections, const DetectionPostProcessDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 248 of file LayerSupportBase.cpp.
Referenced by NeonLayerSupport::IsLayerSupported().
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDilatedDepthwiseConvolutionSupported()
bool IsDilatedDepthwiseConvolutionSupported (const TensorInfo & input, const TensorInfo & output, const DepthwiseConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 261 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsDivisionSupported()
bool IsDivisionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 271 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsElementwiseUnarySupported()
bool IsElementwiseUnarySupported (const TensorInfo & input, const TensorInfo & output, const ElementwiseUnaryDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 279 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsFakeQuantizationSupported()
bool IsFakeQuantizationSupported (const TensorInfo & input, const FakeQuantizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 287 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsFillSupported()
bool IsFillSupported (const TensorInfo & input, const TensorInfo & output, const FillDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override virtual
Reimplemented in RefLayerSupport, NeonLayerSupport, and ClLayerSupport.
Definition at line 294 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsFloorSupported()
bool IsFloorSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 302 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsFullyConnectedSupported()
bool IsFullyConnectedSupported (const TensorInfo & input, const TensorInfo & output, const TensorInfo & weights, const TensorInfo & biases, const FullyConnectedDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 309 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsGatherSupported()
bool IsGatherSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const GatherDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 319 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsInputSupported()
bool IsInputSupported (const TensorInfo & input, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 328 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsInstanceNormalizationSupported()
bool IsInstanceNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const InstanceNormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 334 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsL2NormalizationSupported()
bool IsL2NormalizationSupported (const TensorInfo & input, const TensorInfo & output, const L2NormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 342 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsLayerSupported()
bool IsLayerSupported (const LayerType & type, const std::vector< TensorInfo > & infos, const BaseDescriptor & descriptor, const Optional< LstmInputParamsInfo > & lstmParamsInfo = EmptyOptional(), const Optional< QuantizedLstmInputParamsInfo > & quantizedLstmParamsInfo = EmptyOptional(), Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override virtual
Reimplemented from ILayerSupport.
Reimplemented in SampleDynamicLayerSupport, NeonLayerSupport, ClLayerSupport, MockImportLayerSupport, and RefLayerSupport.
Definition at line 40 of file LayerSupportBase.cpp.
References ILayerSupport::descriptor, LayerSupportBase::IsMemCopySupported(), LayerSupportBase::IsMemImportSupported(), LayerSupportBase::IsStandInSupported(), armnn::MemCopy, armnn::MemImport, and armnn::StandIn.
 {
     switch(type)
     {
         case LayerType::MemCopy:
             return IsMemCopySupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::MemImport:
             return IsMemImportSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::StandIn:
         {
             auto desc = *(PolymorphicDowncast<const StandInDescriptor*>(&descriptor));
             if (infos.size() != (desc.m_NumInputs + desc.m_NumOutputs))
             {
                 throw InvalidArgumentException("Number of StandIn layer TensorInfos does not equal "
                                                "the combined number of input and output slots assigned "
                                                "to the StandIn descriptor");
             }
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < desc.m_NumInputs; i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             std::vector<const TensorInfo*> outputInfos;
             for (uint32_t i = desc.m_NumInputs; i < infos.size(); i++)
             {
                 outputInfos.push_back(&infos[i]);
             }
             return IsStandInSupported(inputInfos,
                                       outputInfos,
                                       desc,
                                       reasonIfUnsupported);
         }
         default:
             return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
     }
 }
IsLogicalBinarySupported()
bool IsLogicalBinarySupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, const LogicalBinaryDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 350 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsLogicalUnarySupported()
bool IsLogicalUnarySupported (const TensorInfo & input, const TensorInfo & output, const ElementwiseUnaryDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 359 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsLogSoftmaxSupported()
bool IsLogSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const LogSoftmaxDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 367 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsLstmSupported()
bool IsLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & scratchBuffer, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const LstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 375 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsMaximumSupported()
bool IsMaximumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 389 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsMeanSupported()
bool IsMeanSupported (const TensorInfo & input, const TensorInfo & output, const MeanDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 397 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsMemCopySupported()
bool IsMemCopySupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 405 of file LayerSupportBase.cpp.
Referenced by LayerSupportBase::IsLayerSupported(), MockImportLayerSupport::IsLayerSupported(), ClLayerSupport::IsLayerSupported(), and NeonLayerSupport::IsLayerSupported().
 {
     return true;
 }
IsMemImportSupported()
bool IsMemImportSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 412 of file LayerSupportBase.cpp.
Referenced by RefLayerSupport::IsLayerSupported(), MockImportLayerSupport::IsLayerSupported(), LayerSupportBase::IsLayerSupported(), ClLayerSupport::IsLayerSupported(), and NeonLayerSupport::IsLayerSupported().
 {
     return true;
 }
IsMergeSupported()
bool IsMergeSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 419 of file LayerSupportBase.cpp.
Referenced by RefLayerSupport::IsLayerSupported(), ClLayerSupport::IsLayerSupported(), and NeonLayerSupport::IsLayerSupported().
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsMinimumSupported()
bool IsMinimumSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 427 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsMultiplicationSupported()
bool IsMultiplicationSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 435 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsNormalizationSupported()
bool IsNormalizationSupported (const TensorInfo & input, const TensorInfo & output, const NormalizationDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 443 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsOutputSupported()
bool IsOutputSupported (const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 451 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsPadSupported()
bool IsPadSupported (const TensorInfo & input, const TensorInfo & output, const PadDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 457 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsPermuteSupported()
bool IsPermuteSupported (const TensorInfo & input, const TensorInfo & output, const PermuteDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 465 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsPooling2dSupported()
bool IsPooling2dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling2dDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 473 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsPooling3dSupported()
bool IsPooling3dSupported (const TensorInfo & input, const TensorInfo & output, const Pooling3dDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 481 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsPreCompiledSupported()
bool IsPreCompiledSupported (const TensorInfo & input, const PreCompiledDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 489 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsPreluSupported()
bool IsPreluSupported (const TensorInfo & input, const TensorInfo & alpha, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported) const override
Definition at line 496 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsQLstmSupported()
bool IsQLstmSupported (const TensorInfo & input, const TensorInfo & previousOutputIn, const TensorInfo & previousCellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const QLstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 511 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsQuantizedLstmSupported()
bool IsQuantizedLstmSupported (const TensorInfo & input, const TensorInfo & previousCellStateIn, const TensorInfo & previousOutputIn, const TensorInfo & cellStateOut, const TensorInfo & output, const QuantizedLstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 524 of file LayerSupportBase.cpp.
Referenced by RefLayerSupport::IsLayerSupported().
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsQuantizeSupported()
bool IsQuantizeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 504 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsRankSupported()
bool IsRankSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported) const override
Definition at line 535 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsReduceSupported()
bool IsReduceSupported (const TensorInfo & input, const TensorInfo & output, const ReduceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 542 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsReshapeSupported()
bool IsReshapeSupported (const TensorInfo & input, const TensorInfo & output, const ReshapeDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 550 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsResizeSupported()
bool IsResizeSupported (const TensorInfo & input, const TensorInfo & output, const ResizeDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 558 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsShapeSupported()
bool IsShapeSupported (const TensorInfo & input, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 566 of file LayerSupportBase.cpp.
Referenced by ClLayerSupport::IsLayerSupported(), and NeonLayerSupport::IsLayerSupported().
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSliceSupported()
bool IsSliceSupported (const TensorInfo & input, const TensorInfo & output, const SliceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 573 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSoftmaxSupported()
bool IsSoftmaxSupported (const TensorInfo & input, const TensorInfo & output, const SoftmaxDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 581 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSpaceToBatchNdSupported()
bool IsSpaceToBatchNdSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToBatchNdDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 589 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSpaceToDepthSupported()
bool IsSpaceToDepthSupported (const TensorInfo & input, const TensorInfo & output, const SpaceToDepthDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 597 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSplitterSupported()
bool IsSplitterSupported (const TensorInfo & input, const std::vector< std::reference_wrapper< TensorInfo >> & outputs, const ViewsDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 605 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsStackSupported()
bool IsStackSupported (const std::vector< const TensorInfo *> & inputs, const TensorInfo & output, const StackDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 613 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsStandInSupported()
bool IsStandInSupported (const std::vector< const TensorInfo *> & inputs, const std::vector< const TensorInfo *> & outputs, const StandInDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 621 of file LayerSupportBase.cpp.
References OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by LayerSupportBase::IsLayerSupported().
 {
     if (reasonIfUnsupported)
     {
         std::stringstream message;
         message << "StandIn layer is not executable via backends";
         reasonIfUnsupported.value() = message.str();
     }
     return false;
 }
IsStridedSliceSupported()
bool IsStridedSliceSupported (const TensorInfo & input, const TensorInfo & output, const StridedSliceDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 637 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSubtractionSupported()
bool IsSubtractionSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 645 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsSwitchSupported()
bool IsSwitchSupported (const TensorInfo & input0, const TensorInfo & input1, const TensorInfo & output0, const TensorInfo & output1, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 653 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsTransposeConvolution2dSupported()
bool IsTransposeConvolution2dSupported (const TensorInfo & input, const TensorInfo & output, const TransposeConvolution2dDescriptor & descriptor, const TensorInfo & weights, const Optional< TensorInfo > & biases, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 662 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsTransposeSupported()
bool IsTransposeSupported (const TensorInfo & input, const TensorInfo & output, const TransposeDescriptor & descriptor, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 672 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
IsUnidirectionalSequenceLstmSupported()
bool IsUnidirectionalSequenceLstmSupported (const TensorInfo & input, const TensorInfo & outputStateIn, const TensorInfo & cellStateIn, const TensorInfo & outputStateOut, const TensorInfo & cellStateOut, const TensorInfo & output, const LstmDescriptor & descriptor, const LstmInputParamsInfo & paramsInfo, Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const override
Definition at line 680 of file LayerSupportBase.cpp.
 {
     return DefaultLayerSupport(__func__, __FILE__, __LINE__, reasonIfUnsupported);
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/LayerSupportBase.hpp
src/backends/backendsCommon/LayerSupportBase.cpp