ArmNN: EthosnRefPooling2dWorkload Class Reference
EthosnRefPooling2dWorkload Class Reference
#include <EthosnRefPooling2dWorkload.hpp>
Public Member Functions
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< Pooling2dQueueDescriptor >
BaseWorkload (const Pooling2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const Pooling2dQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< Pooling2dQueueDescriptor >
Pooling2dQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 16 of file EthosnRefPooling2dWorkload.hpp.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 15 of file EthosnRefPooling2dWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_ETHOSN, armnn::EthosnRefPooling2d(), TensorInfo::GetDataType(), armnn::ethosnref::GetTensorInfo(), armnn::QAsymmU8, armnn::QSymmS16, and armnn::QSymmS8.
 {
     ARMNN_SCOPED_PROFILING_EVENT_ETHOSN("EthosnRefPooling2dWorkload_Execute");
     const TensorInfo& inputInfo   = GetTensorInfo(m_Data.m_Inputs[0]);
     if (inputInfo.GetDataType() == DataType::QSymmS16) {
         const int16_t* inputData = GetInputTensorData<int16_t>(0, m_Data);
         EthosnRefPooling2d(m_Data, inputData);
     }
     else if (inputInfo.GetDataType() == DataType::QSymmS8) {
         const int8_t* inputData = GetInputTensorData<int8_t>(0, m_Data);
         EthosnRefPooling2d(m_Data, inputData);
     }
     else { // QAsymmU8
         assert(inputInfo.GetDataType() == DataType::QAsymmU8);
         const uint8_t* inputData = GetInputTensorData<uint8_t>(0, m_Data);
         EthosnRefPooling2d(m_Data, inputData);
     }
 }
The documentation for this class was generated from the following files:
src/backends/ethosnref/workloads/EthosnRefPooling2dWorkload.hpp
src/backends/ethosnref/workloads/EthosnRefPooling2dWorkload.cpp