ArmNN: DotAttributeSet Class Reference
DotAttributeSet Class Reference
#include <DotSerializer.hpp>
Public Member Functions
DotAttributeSet (std::ostream &stream)
~DotAttributeSet ()
DotAttributeSet & AddAttribute (const std::string &name, const std::stringstream &value)
DotAttributeSet & AddAttribute (const std::string &name, int value)
DotAttributeSet & AddAttribute (const std::string &name, const std::string &value)
Public Member Functions inherited from DotBase
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 64 of file DotSerializer.hpp.
Constructor & Destructor Documentation
DotAttributeSet()
DotAttributeSet (std::ostream & stream) explicit
Definition at line 72 of file DotSerializer.cpp.
References DotBase::GetStream().
     : DotBase(stream)
 {
     GetStream() << "[";
 }
~DotAttributeSet()
~DotAttributeSet ()
Definition at line 78 of file DotSerializer.cpp.
References DotBase::GetStream().
 {
     bool doSpace=false;
     for (auto&& attrib : m_Attributes)
     {
         if (doSpace)
         {
             GetStream() << " ";
         }
         GetStream() << attrib;
         doSpace=true;
     }
     GetStream() << "]";
 }
Member Function Documentation
AddAttribute() [1/3]
DotAttributeSet & AddAttribute (const std::string & name, const std::stringstream & value)
Definition at line 95 of file DotSerializer.cpp.
Referenced by Graph::SerializeToDot().
 {
     std::stringstream ss;
     ss << name <<"=" << value.str();
     m_Attributes.push_back(ss.str());
     return *this;
 }
AddAttribute() [2/3]
DotAttributeSet & AddAttribute (const std::string & name, int value)
Definition at line 103 of file DotSerializer.cpp.
 {
     std::stringstream ss;
     ss << name <<"=" << value;
     m_Attributes.push_back(ss.str());
     return *this;
 }
AddAttribute() [3/3]
DotAttributeSet & AddAttribute (const std::string & name, const std::string & value)
Definition at line 111 of file DotSerializer.cpp.
 {
     std::stringstream ss;
     ss << name <<"=\"" << value << "\"";
     m_Attributes.push_back(ss.str());
     return *this;
 }
The documentation for this class was generated from the following files:
src/armnnUtils/DotSerializer.hpp
src/armnnUtils/DotSerializer.cpp