ArmNN: MockSendCounterPacket Class Reference
MockSendCounterPacket Class Reference
#include <ProfilingMocks.hpp>
Public Member Functions
MockSendCounterPacket (IBufferManager &sendBuffer)
void SendStreamMetaDataPacket () override
void SendCounterDirectoryPacket (const ICounterDirectory &counterDirectory) override
void SendPeriodicCounterCapturePacket (uint64_t timestamp, const std::vector< CounterValue > &values) override
void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > &selectedCounterIds) override
Detailed Description
Definition at line 394 of file ProfilingMocks.hpp.
Constructor & Destructor Documentation
MockSendCounterPacket()
MockSendCounterPacket (IBufferManager & sendBuffer) inline
Definition at line 397 of file ProfilingMocks.hpp.
 : m_BufferManager(sendBuffer) {}
Member Function Documentation
SendCounterDirectoryPacket()
void SendCounterDirectoryPacket (const ICounterDirectory & counterDirectory) inline override
Definition at line 408 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
Referenced by TEST_SUITE().
     {
         arm::pipe::IgnoreUnused(counterDirectory);
         std::string message("SendCounterDirectoryPacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved);
     }
SendPeriodicCounterCapturePacket()
void SendPeriodicCounterCapturePacket (uint64_t timestamp, const std::vector< CounterValue > & values) inline override
Definition at line 419 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
Referenced by TEST_SUITE().
     {
         arm::pipe::IgnoreUnused(timestamp, values);
         std::string message("SendPeriodicCounterCapturePacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved);
     }
SendPeriodicCounterSelectionPacket()
void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > & selectedCounterIds) inline override
Definition at line 431 of file ProfilingMocks.hpp.
References armnn::IgnoreUnused().
Referenced by TEST_SUITE().
     {
         arm::pipe::IgnoreUnused(capturePeriod, selectedCounterIds);
         std::string message("SendPeriodicCounterSelectionPacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved);
     }
SendStreamMetaDataPacket()
void SendStreamMetaDataPacket () inline override
Definition at line 399 of file ProfilingMocks.hpp.
Referenced by TEST_SUITE().
     {
         std::string message("SendStreamMetaDataPacket");
         unsigned int reserved = 0;
         IPacketBufferPtr buffer = m_BufferManager.Reserve(1024, reserved);
         memcpy(buffer->GetWritableData(), message.c_str(), static_cast<unsigned int>(message.size()) + 1);
         m_BufferManager.Commit(buffer, reserved, false);
     }
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingMocks.hpp