ArmNN: TestStrategy Class Reference
TestStrategy Class Reference
#include <TestStrategy.hpp>
Public Member Functions
TestStrategy ()
std::string GetName () const override
MemBlockStrategyType GetMemBlockStrategyType () const override
std::vector< MemBin > Optimize (std::vector< MemBlock > &memBlocks) override
Public Member Functions inherited from IMemoryOptimizerStrategy
virtual ~IMemoryOptimizerStrategy ()
Detailed Description
Definition at line 13 of file TestStrategy.hpp.
Constructor & Destructor Documentation
TestStrategy()
TestStrategy () inline
Definition at line 16 of file TestStrategy.hpp.
References TestStrategy::GetMemBlockStrategyType(), TestStrategy::GetName(), and TestStrategy::Optimize().
                 : m_Name(std::string("TestStrategy"))
                 , m_MemBlockStrategyType(MemBlockStrategyType::MultiAxisPacking) {}
Member Function Documentation
GetMemBlockStrategyType()
MemBlockStrategyType GetMemBlockStrategyType () const override virtual
Implements IMemoryOptimizerStrategy.
Definition at line 16 of file TestStrategy.cpp.
Referenced by TestStrategy::TestStrategy().
     {
         return m_MemBlockStrategyType;
     }
GetName()
std::string GetName () const override virtual
Implements IMemoryOptimizerStrategy.
Definition at line 11 of file TestStrategy.cpp.
Referenced by TestStrategy::TestStrategy().
     {
         return m_Name;
     }
Optimize()
std::vector< MemBin > Optimize (std::vector< MemBlock > & memBlocks) override virtual
Implements IMemoryOptimizerStrategy.
Definition at line 25 of file TestStrategy.cpp.
References MemBin::m_MemBlocks, and MemBin::m_MemSize.
Referenced by TestStrategy::TestStrategy().
     {
         std::vector<MemBin> memBins;
         memBins.reserve(memBlocks.size());
         for (auto& memBlock : memBlocks)
         {
             MemBin memBin;
             memBin.m_MemSize = memBlock.m_MemSize;
             memBin.m_MemBlocks.reserve(1);
             memBlock.m_Offset = 0;
             memBin.m_MemBlocks.push_back(memBlock);
             memBins.push_back(memBin);
         }
         return memBins;
     }
The documentation for this class was generated from the following files:
tests/MemoryStrategyBenchmark/TestStrategy.hpp
tests/MemoryStrategyBenchmark/TestStrategy.cpp