ArmNN: SampleMemoryManager::Pool Class Reference
SampleMemoryManager::Pool Class Reference
#include <SampleMemoryManager.hpp>
Public Member Functions
Pool (unsigned int numBytes)
~Pool ()
void Acquire ()
void Release ()
void * GetPointer ()
void Reserve (unsigned int numBytes)
Detailed Description
Definition at line 33 of file SampleMemoryManager.hpp.
Constructor & Destructor Documentation
Pool()
Pool (unsigned int numBytes)
Definition at line 61 of file SampleMemoryManager.cpp.
     : m_Size(numBytes),
       m_Pointer(nullptr)
 {}
~Pool()
~Pool ()
Definition at line 66 of file SampleMemoryManager.cpp.
References SampleMemoryManager::Pool::Release().
 {
     if (m_Pointer)
     {
         Release();
     }
 }
Member Function Documentation
Acquire()
void Acquire ()
Definition at line 84 of file SampleMemoryManager.cpp.
 {
     m_Pointer = ::operator new(size_t(m_Size));
 }
GetPointer()
void * GetPointer ()
Definition at line 74 of file SampleMemoryManager.cpp.
Referenced by SampleMemoryManager::GetPointer().
 {
     return m_Pointer;
 }
Release()
void Release ()
Definition at line 89 of file SampleMemoryManager.cpp.
Referenced by SampleMemoryManager::Pool::~Pool().
 {
     ::operator delete(m_Pointer);
     m_Pointer = nullptr;
 }
Reserve()
void Reserve (unsigned int numBytes)
Definition at line 79 of file SampleMemoryManager.cpp.
Referenced by SampleMemoryManager::Manage().
 {
     m_Size = std::max(m_Size, numBytes);
 }
The documentation for this class was generated from the following files:
src/dynamic/sample/SampleMemoryManager.hpp
src/dynamic/sample/SampleMemoryManager.cpp