ArmNN: RefTransposeWorkload< DataType > Class Template Reference
RefTransposeWorkload< DataType > Class Template Reference
#include <RefTransposeWorkload.hpp>
Public Member Functions
void Execute () const override
void ExecuteAsync (ExecutionData &executionData) override
Public Member Functions inherited from TypedWorkload< TransposeQueueDescriptor, DataType >
TypedWorkload (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info)
Public Member Functions inherited from BaseWorkload< TransposeQueueDescriptor >
BaseWorkload (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const TransposeQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Static Public Member Functions
static const std::string & GetName ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< TransposeQueueDescriptor >
TransposeQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
template<armnn::DataType DataType>
class armnn::RefTransposeWorkload< DataType >
Definition at line 16 of file RefTransposeWorkload.hpp.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 17 of file RefTransposeWorkload.cpp.
Referenced by RefTransposeWorkload< DataType >::ExecuteAsync(), and RefTransposeWorkload< DataType >::GetName().
 {
     Execute(m_Data.m_Inputs, m_Data.m_Outputs);
 }
ExecuteAsync()
void ExecuteAsync (ExecutionData & executionData) override virtual
Implements IWorkload.
Definition at line 23 of file RefTransposeWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, armnn::CpuRef, RefTransposeWorkload< DataType >::Execute(), armnn::GetTensorInfo(), ExecutionData::m_Data, WorkingMemDescriptor::m_Inputs, WorkingMemDescriptor::m_Outputs, and armnn::Transpose.
Referenced by RefTransposeWorkload< DataType >::GetName().
 {
     WorkingMemDescriptor* workingMemDescriptor = static_cast<WorkingMemDescriptor*>(executionData.m_Data);
     Execute(workingMemDescriptor->m_Inputs, workingMemDescriptor->m_Outputs);
 }
GetName()
static const std::string& GetName () inline static
Definition at line 19 of file RefTransposeWorkload.hpp.
References RefTransposeWorkload< DataType >::Execute(), RefTransposeWorkload< DataType >::ExecuteAsync(), and armnn::GetDataTypeName().
     {
         static const std::string name = std::string("RefTranspose") + GetDataTypeName(DataType) + "Workload";
         return name;
     }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefTransposeWorkload.hpp
src/backends/reference/workloads/RefTransposeWorkload.cpp