ArmNN: FoldPadIntoConvolution2dImpl Class Reference
FoldPadIntoConvolution2dImpl Class Reference
#include <FoldPadIntoLayer2d.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Protected Member Functions
FoldPadIntoConvolution2dImpl ()=default
~FoldPadIntoConvolution2dImpl ()=default
Detailed Description
Definition at line 189 of file FoldPadIntoLayer2d.hpp.
Constructor & Destructor Documentation
FoldPadIntoConvolution2dImpl()
FoldPadIntoConvolution2dImpl () protected default
Referenced by FoldPadIntoConvolution2dImpl::Run().
~FoldPadIntoConvolution2dImpl()
~FoldPadIntoConvolution2dImpl () protected default
Referenced by FoldPadIntoConvolution2dImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Definition at line 192 of file FoldPadIntoLayer2d.hpp.
References ARMNN_ASSERT_MSG, FoldPadIntoConvolution2dImpl::FoldPadIntoConvolution2dImpl(), InputSlot::GetOwningLayer(), and FoldPadIntoConvolution2dImpl::~FoldPadIntoConvolution2dImpl().
     {
         const auto newConv2dLayer = FoldPadIntoLayer2dImpl<Convolution2dLayer>(graph, connection);
         if (newConv2dLayer != nullptr)
         {
             const auto conv2dLayer = PolymorphicDowncast<Convolution2dLayer*>(&connection.GetOwningLayer());
             // Copy weights and bias to the new convolution layer
             ARMNN_ASSERT_MSG(newConv2dLayer->GetInputSlot(1).GetConnection() != nullptr,
                              "FoldPadIntoConvolution2d: New convolution layer is missing connection to weights layer");
             // Deprecated 22.11
             newConv2dLayer->m_Weight = std::move(conv2dLayer->m_Weight);
             if (conv2dLayer->GetParameters().m_BiasEnabled)
             {
                 ARMNN_ASSERT_MSG(newConv2dLayer->GetInputSlot(2).GetConnection() != nullptr,
                                  "FoldPadIntoConvolution2d: New convolution layer is missing "
                                  "connection to bias layer.");
                 // Deprecated 22.11
                 newConv2dLayer->m_Bias = std::move(conv2dLayer->m_Bias);
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/FoldPadIntoLayer2d.hpp