ArmNN: EthosnRefWorkloadFactory Class Reference
EthosnRefWorkloadFactory Class Reference
#include <EthosnRefWorkloadFactory.hpp>
Public Member Functions
EthosnRefWorkloadFactory (const std::shared_ptr< EthosnRefMemoryManager > &memoryManager, bool winograd, std::string BlockConfigs)
EthosnRefWorkloadFactory ()
~EthosnRefWorkloadFactory ()
const BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual void AfterWorkloadsCreated ()
virtual std::unique_ptr< IWorkload > CreateWorkload (LayerType type, const QueueDescriptor &descriptor, const WorkloadInfo &info) const
Static Public Member Functions
static bool IsLayerSupported (const Layer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 19 of file EthosnRefWorkloadFactory.hpp.
Constructor & Destructor Documentation
EthosnRefWorkloadFactory() [1/2]
EthosnRefWorkloadFactory (const std::shared_ptr< EthosnRefMemoryManager > & memoryManager, bool winograd, std::string BlockConfigs) explicit
Definition at line 24 of file EthosnRefWorkloadFactory.cpp.
     : m_MemoryManager(memoryManager)
 {
   m_EnableWinograd = winograd;
   m_BlockConfigs = BlockConfigs;
 }
EthosnRefWorkloadFactory() [2/2]
EthosnRefWorkloadFactory ()
Definition at line 31 of file EthosnRefWorkloadFactory.cpp.
     : m_MemoryManager(new EthosnRefMemoryManager())
 {
 }
~EthosnRefWorkloadFactory()
~EthosnRefWorkloadFactory () inline
Definition at line 25 of file EthosnRefWorkloadFactory.hpp.
References EthosnRefWorkloadFactory::GetBackendId(), and EthosnRefWorkloadFactory::IsLayerSupported().
 {}
Member Function Documentation
CreateConvolution2d()
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override
Definition at line 107 of file EthosnRefWorkloadFactory.cpp.
References armnn::info.
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<EthosnRefConvolution2dWorkload>(descriptor, info, m_EnableWinograd, m_BlockConfigs);
 }
CreateDepthwiseConvolution2d()
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override
Definition at line 113 of file EthosnRefWorkloadFactory.cpp.
References armnn::info.
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<EthosnRefDepthwiseConvolution2dWorkload>(descriptor, info);
 }
CreateInput()
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Implements IWorkloadFactory.
Definition at line 68 of file EthosnRefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and WorkloadInfo::m_OutputTensorInfos.
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos.empty() )
     {
         throw InvalidArgumentException("EthosnRefWorkloadFactory::CreateInput: Input cannot be zero length");
     }
     if (info.m_OutputTensorInfos.empty())
     {
         throw InvalidArgumentException("EthosnRefWorkloadFactory::CreateInput: Output cannot be zero length");
     }
     if (info.m_InputTensorInfos[0].GetNumBytes() != info.m_OutputTensorInfos[0].GetNumBytes())
     {
         throw InvalidArgumentException("EthosnRefWorkloadFactory::CreateInput: data input and output differ in byte count.");
     }
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreateOutput()
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor & descriptor, const WorkloadInfo & info) const override
Definition at line 88 of file EthosnRefWorkloadFactory.cpp.
References armnn::info, WorkloadInfo::m_InputTensorInfos, and WorkloadInfo::m_OutputTensorInfos.
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     if (info.m_InputTensorInfos.empty() )
     {
         throw InvalidArgumentException("EthosnRefWorkloadFactory::CreateOutput: Input cannot be zero length");
     }
     if (info.m_OutputTensorInfos.empty())
     {
         throw InvalidArgumentException("EthosnRefWorkloadFactory::CreateOutput: Output cannot be zero length");
     }
     if (info.m_InputTensorInfos[0].GetNumBytes() != info.m_OutputTensorInfos[0].GetNumBytes())
     {
         throw InvalidArgumentException("EthosnRefWorkloadFactory::CreateOutput: data input and output differ in byte count.");
     }
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreatePooling2d()
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override
Definition at line 127 of file EthosnRefWorkloadFactory.cpp.
References armnn::info.
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<EthosnRefPooling2dWorkload>(descriptor, info);
 }
CreateSubTensorHandle()
std::unique_ptr<ITensorHandle> CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const inline override virtual
Implements IWorkloadFactory.
Definition at line 35 of file EthosnRefWorkloadFactory.hpp.
References EthosnRefWorkloadFactory::CreateConvolution2d(), EthosnRefWorkloadFactory::CreateDepthwiseConvolution2d(), EthosnRefWorkloadFactory::CreateInput(), EthosnRefWorkloadFactory::CreateOutput(), EthosnRefWorkloadFactory::CreatePooling2d(), EthosnRefWorkloadFactory::CreateTensorHandle(), EthosnRefWorkloadFactory::CreateTransposeConvolution2d(), armnn::IgnoreUnused(), and armnn::info.
     {
         IgnoreUnused(parent, subTensorShape, subTensorOrigin);
         return nullptr;
     }
CreateTensorHandle() [1/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 48 of file EthosnRefWorkloadFactory.cpp.
References armnn::IgnoreUnused().
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     // For EthosnRef it is okay to make the TensorHandle memory managed as it can also store a pointer
     // to unmanaged memory. This also ensures memory alignment.
     IgnoreUnused(isMemoryManaged);
     return std::make_unique<EthosnRefTensorHandle>(tensorInfo, m_MemoryManager);
 }
CreateTensorHandle() [2/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 57 of file EthosnRefWorkloadFactory.cpp.
References armnn::IgnoreUnused().
 {
     // For EthosnRef it is okay to make the TensorHandle memory managed as it can also store a pointer
     // to unmanaged memory. This also ensures memory alignment.
     IgnoreUnused(isMemoryManaged, dataLayout);
     return std::make_unique<EthosnRefTensorHandle>(tensorInfo, m_MemoryManager);
 }
CreateTransposeConvolution2d()
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override
Definition at line 120 of file EthosnRefWorkloadFactory.cpp.
References armnn::info.
Referenced by EthosnRefWorkloadFactory::CreateSubTensorHandle().
 {
     return std::make_unique<EthosnRefTransposeConvolution2dWorkload>(descriptor, info);
 }
GetBackendId()
const BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 36 of file EthosnRefWorkloadFactory.cpp.
Referenced by EthosnRefWorkloadFactory::~EthosnRefWorkloadFactory().
 {
     return s_Id;
 }
IsLayerSupported()
bool IsLayerSupported (const Layer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 41 of file EthosnRefWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
Referenced by EthosnRefWorkloadFactory::~EthosnRefWorkloadFactory().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported);
 }
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Implements IWorkloadFactory.
Definition at line 33 of file EthosnRefWorkloadFactory.hpp.
 { return false; }
The documentation for this class was generated from the following files:
src/backends/ethosnref/EthosnRefWorkloadFactory.hpp
src/backends/ethosnref/EthosnRefWorkloadFactory.cpp