ArmNN: Entity Class Reference
Entity Class Reference
#include <TimelineModel.hpp>
Public Member Functions
Entity (uint64_t guid)
uint64_t GetGuid () const
void AddChild (Entity *child)
void AddAttribute (const std::string &type, const std::string &value)
void AddConnection (const Connection &connection)
void AddExecution (Entity *execution)
void AddEvent (EventObj *event)
const Attributes & GetAttributes () const
const std::vector< Entity * > & GetChildren () const
const std::vector< Connection > & GetConnections () const
const std::vector< Entity * > & GetExecutions () const
const std::vector< EventObj * > & GetEvents () const
Detailed Description
Definition at line 88 of file TimelineModel.hpp.
Constructor & Destructor Documentation
Entity()
Entity (uint64_t guid) inline
Definition at line 91 of file TimelineModel.hpp.
 : m_Guid(guid) {}
Member Function Documentation
AddAttribute()
void AddAttribute (const std::string & type, const std::string & value) inline
Definition at line 100 of file TimelineModel.hpp.
Referenced by TimelineModel::AddRelationship().
     {
         Attribute attr(type, value);
         m_Attributes.emplace(type, attr);
     }
AddChild()
void AddChild (Entity * child) inline
Definition at line 93 of file TimelineModel.hpp.
     {
         if (child != nullptr)
         {
             m_Children.push_back(child);
         }
     }
AddConnection()
void AddConnection (const Connection & connection) inline
Definition at line 105 of file TimelineModel.hpp.
     {
         m_Connections.push_back(connection);
     }
AddEvent()
void AddEvent (EventObj * event) inline
Definition at line 116 of file TimelineModel.hpp.
     {
         if (event != nullptr)
         {
             m_Events.push_back(event);
         }
     }
AddExecution()
void AddExecution (Entity * execution) inline
Definition at line 109 of file TimelineModel.hpp.
     {
         if (execution != nullptr)
         {
             m_Executions.push_back(execution);
         }
     }
GetAttributes()
const Attributes& GetAttributes () const inline
Definition at line 123 of file TimelineModel.hpp.
Referenced by arm::pipe::GetEntityDescription().
 {return m_Attributes;}
GetChildren()
const std::vector<Entity*>& GetChildren () const inline
Definition at line 124 of file TimelineModel.hpp.
 {return m_Children;}
GetConnections()
const std::vector<Connection>& GetConnections () const inline
Definition at line 125 of file TimelineModel.hpp.
 {return m_Connections;}
GetEvents()
const std::vector<EventObj*>& GetEvents () const inline
Definition at line 127 of file TimelineModel.hpp.
 {return m_Events;}
GetExecutions()
const std::vector<Entity*>& GetExecutions () const inline
Definition at line 126 of file TimelineModel.hpp.
 {return m_Executions;}
GetGuid()
uint64_t GetGuid () const inline
Definition at line 92 of file TimelineModel.hpp.
Referenced by arm::pipe::GetConnectionDescription(), and arm::pipe::GetEntityDescription().
 {return m_Guid;}
The documentation for this class was generated from the following file:
src/profiling/test/TimelineModel.hpp