ArmNN: TestConvolution2dLayerVisitor Class Reference
TestConvolution2dLayerVisitor Class Reference
#include <ConstTensorLayerVisitor.hpp>
Public Member Functions
TestConvolution2dLayerVisitor (const Convolution2dDescriptor &convolution2dDescriptor, const char *name=nullptr)
virtual ~TestConvolution2dLayerVisitor ()
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Protected Member Functions
void CheckDescriptor (const Convolution2dDescriptor &convolution2dDescriptor)
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckConstTensors (const ConstTensor &expected, const ConstTensorHandle &actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const ConstTensor *actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const std::shared_ptr< ConstTensorHandle > actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from StrategyBase< NoThrowStrategy >
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Additional Inherited Members
Protected Attributes inherited from StrategyBase< NoThrowStrategy >
NoThrowStrategy m_DefaultStrategy
Detailed Description
Definition at line 20 of file ConstTensorLayerVisitor.hpp.
Constructor & Destructor Documentation
TestConvolution2dLayerVisitor()
TestConvolution2dLayerVisitor (const Convolution2dDescriptor & convolution2dDescriptor, const char * name = nullptr) inline explicit
Definition at line 23 of file ConstTensorLayerVisitor.hpp.
         : TestLayerVisitor(name)
         , m_Descriptor(convolution2dDescriptor)
     {}
~TestConvolution2dLayerVisitor()
virtual ~TestConvolution2dLayerVisitor () inline virtual
Definition at line 29 of file ConstTensorLayerVisitor.hpp.
 {}
Member Function Documentation
CheckDescriptor()
void CheckDescriptor (const Convolution2dDescriptor & convolution2dDescriptor) protected
Definition at line 14 of file ConstTensorLayerVisitor.cpp.
References Convolution2dDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, Convolution2dDescriptor::m_StrideX, and Convolution2dDescriptor::m_StrideY.
Referenced by TestConvolution2dLayerVisitor::ExecuteStrategy(), TestDepthwiseConvolution2dLayerVisitor::ExecuteStrategy(), TestFullyConnectedLayerVistor::ExecuteStrategy(), TestBatchNormalizationLayerVisitor::ExecuteStrategy(), TestLstmLayerVisitor::ExecuteStrategy(), and TestQLstmLayerVisitor::ExecuteStrategy().
 {
     CHECK(m_Descriptor.m_PadLeft == convolution2dDescriptor.m_PadLeft);
     CHECK(m_Descriptor.m_PadRight == convolution2dDescriptor.m_PadRight);
     CHECK(m_Descriptor.m_PadTop == convolution2dDescriptor.m_PadTop);
     CHECK(m_Descriptor.m_PadBottom == convolution2dDescriptor.m_PadBottom);
     CHECK(m_Descriptor.m_StrideX == convolution2dDescriptor.m_StrideX);
     CHECK(m_Descriptor.m_StrideY == convolution2dDescriptor.m_StrideY);
     CHECK(m_Descriptor.m_BiasEnabled == convolution2dDescriptor.m_BiasEnabled);
     CHECK(m_Descriptor.m_DataLayout == convolution2dDescriptor.m_DataLayout);
 }
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Reimplemented from StrategyBase< NoThrowStrategy >.
Definition at line 31 of file ConstTensorLayerVisitor.hpp.
References NoThrowStrategy::Apply(), TestConvolution2dLayerVisitor::CheckDescriptor(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), armnn::Convolution2d, armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), and StrategyBase< NoThrowStrategy >::m_DefaultStrategy.
     {
         armnn::IgnoreUnused(descriptor, constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::Convolution2d:
             {
                 CheckLayerPointer(layer);
                 CheckLayerName(name);
                 CheckDescriptor(static_cast<const armnn::Convolution2dDescriptor&>(descriptor));
                 break;
             }
             default:
             {
                 m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
             }
         }
     }
The documentation for this class was generated from the following files:
src/armnn/test/ConstTensorLayerVisitor.hpp
src/armnn/test/ConstTensorLayerVisitor.cpp