ArmNN: include/armnnTestUtils/DataLayoutUtils.hpp File Reference
DataLayoutUtils.hpp File Reference
#include <armnn/Tensor.hpp>
#include <armnn/Types.hpp>
#include <armnnUtils/Permute.hpp>
Functions
template<typename T >
void PermuteTensorNchwToNhwc (armnn::TensorInfo &tensorInfo, std::vector< T > &tensorData)
template<typename T >
void PermuteTensorNhwcToNchw (armnn::TensorInfo &tensorInfo, std::vector< T > &tensorData)
template<typename T >
void PermuteTensorNdhwcToNcdhw (armnn::TensorInfo &tensorInfo, std::vector< T > &tensorData)
template<typename T >
void PermuteTensorNcdhwToNdhwc (armnn::TensorInfo &tensorInfo, std::vector< T > &tensorData)
Function Documentation
PermuteTensorNcdhwToNdhwc()
void PermuteTensorNcdhwToNdhwc (armnn::TensorInfo & tensorInfo, std::vector< T > & tensorData)
Definition at line 51 of file DataLayoutUtils.hpp.
References TensorInfo::GetShape(), armnnUtils::Permute(), and armnnUtils::Permuted().
 {
     const armnn::PermutationVector ncdhwToNdhwc = { 0, 4, 1, 2, 3 };
     tensorInfo = armnnUtils::Permuted(tensorInfo, ncdhwToNdhwc);
     std::vector<T> tmp(tensorData.size());
     armnnUtils::Permute(tensorInfo.GetShape(), ncdhwToNdhwc, tensorData.data(), tmp.data(), sizeof(T));
     tensorData = tmp;
 }
PermuteTensorNchwToNhwc()
void PermuteTensorNchwToNhwc (armnn::TensorInfo & tensorInfo, std::vector< T > & tensorData)
Definition at line 14 of file DataLayoutUtils.hpp.
References TensorInfo::GetShape(), armnnUtils::Permute(), and armnnUtils::Permuted().
Referenced by TransposeConvolution2dPerAxisQuantTest().
 {
     const armnn::PermutationVector nchwToNhwc = { 0, 3, 1, 2 };
     tensorInfo = armnnUtils::Permuted(tensorInfo, nchwToNhwc);
     std::vector<T> tmp(tensorData.size());
     armnnUtils::Permute(tensorInfo.GetShape(), nchwToNhwc, tensorData.data(), tmp.data(), sizeof(T));
     tensorData = tmp;
 }
PermuteTensorNdhwcToNcdhw()
void PermuteTensorNdhwcToNcdhw (armnn::TensorInfo & tensorInfo, std::vector< T > & tensorData)
Definition at line 39 of file DataLayoutUtils.hpp.
References TensorInfo::GetShape(), armnnUtils::Permute(), and armnnUtils::Permuted().
Referenced by Convolution3dEndToEnd(), and SimpleConvolution3dTestImpl().
 {
     const armnn::PermutationVector ndhwcToNcdhw = { 0, 2, 3, 4, 1 };
     tensorInfo = armnnUtils::Permuted(tensorInfo, ndhwcToNcdhw);
     std::vector<T> tmp(tensorData.size());
     armnnUtils::Permute(tensorInfo.GetShape(), ndhwcToNcdhw, tensorData.data(), tmp.data(), sizeof(T));
     tensorData = tmp;
 }
PermuteTensorNhwcToNchw()
void PermuteTensorNhwcToNchw (armnn::TensorInfo & tensorInfo, std::vector< T > & tensorData)
Definition at line 26 of file DataLayoutUtils.hpp.
References TensorInfo::GetShape(), armnnUtils::Permute(), and armnnUtils::Permuted().
Referenced by Convolution2dPerAxisQuantTest(), DepthwiseConvolution2dEndToEnd(), and DepthwiseConvolution2dPerAxisQuantTest().
 {
     const armnn::PermutationVector nhwcToNchw = { 0, 2, 3, 1 };
     tensorInfo = armnnUtils::Permuted(tensorInfo, nhwcToNchw);
     std::vector<T> tmp(tensorData.size());
     armnnUtils::Permute(tensorInfo.GetShape(), nhwcToNchw, tensorData.data(), tmp.data(), sizeof(T));
     tensorData = tmp;
 }