var namespacearm_1_1pipe =
[
    [ "Connection", "classarm_1_1pipe_1_1_connection.xhtml", "classarm_1_1pipe_1_1_connection" ],
    [ "Entity", "classarm_1_1pipe_1_1_entity.xhtml", "classarm_1_1pipe_1_1_entity" ],
    [ "EventClassObj", "classarm_1_1pipe_1_1_event_class_obj.xhtml", "classarm_1_1pipe_1_1_event_class_obj" ],
    [ "EventObj", "classarm_1_1pipe_1_1_event_obj.xhtml", "classarm_1_1pipe_1_1_event_obj" ],
    [ "MockBufferManager", "classarm_1_1pipe_1_1_mock_buffer_manager.xhtml", "classarm_1_1pipe_1_1_mock_buffer_manager" ],
    [ "MockCounterDirectory", "classarm_1_1pipe_1_1_mock_counter_directory.xhtml", "classarm_1_1pipe_1_1_mock_counter_directory" ],
    [ "MockPacketBuffer", "classarm_1_1pipe_1_1_mock_packet_buffer.xhtml", "classarm_1_1pipe_1_1_mock_packet_buffer" ],
    [ "MockProfilingConnection", "classarm_1_1pipe_1_1_mock_profiling_connection.xhtml", "classarm_1_1pipe_1_1_mock_profiling_connection" ],
    [ "MockProfilingConnectionFactory", "classarm_1_1pipe_1_1_mock_profiling_connection_factory.xhtml", "classarm_1_1pipe_1_1_mock_profiling_connection_factory" ],
    [ "MockProfilingService", "classarm_1_1pipe_1_1_mock_profiling_service.xhtml", "classarm_1_1pipe_1_1_mock_profiling_service" ],
    [ "MockProfilingServiceStatus", "classarm_1_1pipe_1_1_mock_profiling_service_status.xhtml", "classarm_1_1pipe_1_1_mock_profiling_service_status" ],
    [ "MockSendCounterPacket", "classarm_1_1pipe_1_1_mock_send_counter_packet.xhtml", "classarm_1_1pipe_1_1_mock_send_counter_packet" ],
    [ "MockStreamCounterBuffer", "classarm_1_1pipe_1_1_mock_stream_counter_buffer.xhtml", "classarm_1_1pipe_1_1_mock_stream_counter_buffer" ],
    [ "ModelRelationship", "structarm_1_1pipe_1_1_model_relationship.xhtml", "structarm_1_1pipe_1_1_model_relationship" ],
    [ "PrintPacketHeaderHandler", "classarm_1_1pipe_1_1_print_packet_header_handler.xhtml", null ],
    [ "ProfilingServiceRuntimeHelper", "classarm_1_1pipe_1_1_profiling_service_runtime_helper.xhtml", "classarm_1_1pipe_1_1_profiling_service_runtime_helper" ],
    [ "RequestCountersPacketHandler", "classarm_1_1pipe_1_1_request_counters_packet_handler.xhtml", "classarm_1_1pipe_1_1_request_counters_packet_handler" ],
    [ "SendCounterPacketTest", "classarm_1_1pipe_1_1_send_counter_packet_test.xhtml", "classarm_1_1pipe_1_1_send_counter_packet_test" ],
    [ "StreamRedirector", "structarm_1_1pipe_1_1_stream_redirector.xhtml", "structarm_1_1pipe_1_1_stream_redirector" ],
    [ "SwapProfilingConnectionFactoryHelper", "classarm_1_1pipe_1_1_swap_profiling_connection_factory_helper.xhtml", "classarm_1_1pipe_1_1_swap_profiling_connection_factory_helper" ],
    [ "TestFunctorA", "classarm_1_1pipe_1_1_test_functor_a.xhtml", "classarm_1_1pipe_1_1_test_functor_a" ],
    [ "TestFunctorB", "classarm_1_1pipe_1_1_test_functor_b.xhtml", null ],
    [ "TestFunctorC", "classarm_1_1pipe_1_1_test_functor_c.xhtml", null ],
    [ "TestProfilingConnectionArmnnError", "classarm_1_1pipe_1_1_test_profiling_connection_armnn_error.xhtml", "classarm_1_1pipe_1_1_test_profiling_connection_armnn_error" ],
    [ "TestProfilingConnectionBadAckPacket", "classarm_1_1pipe_1_1_test_profiling_connection_bad_ack_packet.xhtml", "classarm_1_1pipe_1_1_test_profiling_connection_bad_ack_packet" ],
    [ "TestProfilingConnectionBase", "classarm_1_1pipe_1_1_test_profiling_connection_base.xhtml", "classarm_1_1pipe_1_1_test_profiling_connection_base" ],
    [ "TestProfilingConnectionTimeoutError", "classarm_1_1pipe_1_1_test_profiling_connection_timeout_error.xhtml", "classarm_1_1pipe_1_1_test_profiling_connection_timeout_error" ],
    [ "TestTimelinePacketHandler", "classarm_1_1pipe_1_1_test_timeline_packet_handler.xhtml", "classarm_1_1pipe_1_1_test_timeline_packet_handler" ],
    [ "TimelineMessageDecoder", "classarm_1_1pipe_1_1_timeline_message_decoder.xhtml", "classarm_1_1pipe_1_1_timeline_message_decoder" ],
    [ "TimelineModel", "classarm_1_1pipe_1_1_timeline_model.xhtml", "classarm_1_1pipe_1_1_timeline_model" ]
];