ArmNN: armnn::ethosnref Namespace Reference
armnn::ethosnref Namespace Reference
Functions
const TensorInfo & GetTensorInfo (const ITensorHandle *tensorHandle)
template<typename DataType , typename PayloadType >
const DataType * GetInputTensorData (unsigned int idx, const PayloadType &data)
template<typename DataType , typename PayloadType >
DataType * GetOutputTensorData (unsigned int idx, const PayloadType &data)
uint32_t DivideRoundUp (uint32_t numerator, uint32_t denominator)
bool CheckDataType (DataType type, DataType inputType, DataType weightsType)
Function Documentation
CheckDataType()
bool armnn::ethosnref::CheckDataType (DataType type, DataType inputType, DataType weightsType) inline
Definition at line 56 of file EthosnRefWorkloadUtils.hpp.
Referenced by EthosnRefDepthwiseConvolution2dWorkload::Execute(), EthosnRefTransposeConvolution2dWorkload::Execute(), and EthosnRefConvolution2dWorkload::Execute().
 {
     return (inputType == type || weightsType == type);
 }
DivideRoundUp()
uint32_t armnn::ethosnref::DivideRoundUp (uint32_t numerator, uint32_t denominator) inline
Definition at line 51 of file EthosnRefWorkloadUtils.hpp.
Referenced by EthosnRefConvolution2dWorkload::Execute().
 {
     return (numerator + denominator - 1) / denominator;
 }
GetInputTensorData()
const DataType* armnn::ethosnref::GetInputTensorData (unsigned int idx, const PayloadType & data)
Definition at line 38 of file EthosnRefWorkloadUtils.hpp.
References ITensorHandle::Map().
 {
     const ITensorHandle* tensorHandle = data.m_Inputs[idx];
     return reinterpret_cast<const DataType*>(tensorHandle->Map());
 }
GetOutputTensorData()
DataType* armnn::ethosnref::GetOutputTensorData (unsigned int idx, const PayloadType & data)
Definition at line 45 of file EthosnRefWorkloadUtils.hpp.
References ITensorHandle::Map().
 {
     ITensorHandle* tensorHandle = data.m_Outputs[idx];
     return reinterpret_cast<DataType*>(tensorHandle->Map());
 }
GetTensorInfo()
const TensorInfo& armnn::ethosnref::GetTensorInfo (const ITensorHandle * tensorHandle) inline
Definition at line 29 of file EthosnRefWorkloadUtils.hpp.
References EthosnRefTensorHandle::GetTensorInfo().
Referenced by armnn::EthosnRefPooling2d(), and EthosnRefPooling2dWorkload::Execute().
 {
     // We know that ethosn workloads use EthosnRefTensorHandles for inputs and outputs
     const EthosnRefTensorHandle* refTensorHandle =
         PolymorphicDowncast<const EthosnRefTensorHandle*>(tensorHandle);
     return refTensorHandle->GetTensorInfo();
 }