ArmNN: src/backends/cl/test/ClEndToEndTests.cpp File Reference
ClEndToEndTests.cpp File Reference
#include <backendsCommon/test/EndToEndTestImpl.hpp>
#include <backendsCommon/test/ActivationEndToEndTestImpl.hpp>
#include <backendsCommon/test/ArgMinMaxEndToEndTestImpl.hpp>
#include <backendsCommon/test/ComparisonEndToEndTestImpl.hpp>
#include <backendsCommon/test/ConcatEndToEndTestImpl.hpp>
#include <backendsCommon/test/DepthToSpaceEndToEndTestImpl.hpp>
#include <backendsCommon/test/DequantizeEndToEndTestImpl.hpp>
#include <backendsCommon/test/ElementwiseUnaryEndToEndTestImpl.hpp>
#include <backendsCommon/test/FillEndToEndTestImpl.hpp>
#include <backendsCommon/test/InstanceNormalizationEndToEndTestImpl.hpp>
#include <backendsCommon/test/PreluEndToEndTestImpl.hpp>
#include <backendsCommon/test/QLstmEndToEndTestImpl.hpp>
#include <backendsCommon/test/QuantizedLstmEndToEndTestImpl.hpp>
#include <backendsCommon/test/SpaceToDepthEndToEndTestImpl.hpp>
#include <backendsCommon/test/SplitterEndToEndTestImpl.hpp>
#include <backendsCommon/test/TransposeConvolution2dEndToEndTestImpl.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (ClAbsEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (ConstantUsage_Cl_Float32)
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim0Test)
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim0Uint8Test)
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim1Test)
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim1Uint8Test)
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim3Test)
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim3Uint8Test)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat32)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwUint8)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwInt16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat32)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcUint8)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcInt16)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleTest)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetTest)
BOOST_AUTO_TEST_CASE (ClStridedSliceInvalidSliceEndToEndTest)
BOOST_AUTO_TEST_CASE (ClEluEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (ClEluEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (ClGreaterSimpleEndToEndTest)
BOOST_AUTO_TEST_CASE (ClGreaterSimpleEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClGreaterBroadcastEndToEndTest)
BOOST_AUTO_TEST_CASE (ClGreaterBroadcastEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestQAsymmS8)
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestQSymmS16)
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNhwcEndToEndTest1)
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNchwEndToEndTest1)
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNhwcEndToEndTest2)
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNchwEndToEndTest2)
BOOST_AUTO_TEST_CASE (ClFillEndToEndTest)
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (ClFillEndToEndTestInt32)
BOOST_AUTO_TEST_CASE (ClPreluEndToEndFloat32Test)
BOOST_AUTO_TEST_CASE (ClPreluEndToEndTestUint8)
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNhwcEndToEndTest1)
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNchwEndToEndTest1)
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNhwcEndToEndTest2)
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNchwEndToEndTest2)
BOOST_AUTO_TEST_CASE (ClSplitter1dEndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter1dEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter2dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter2dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter2dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter2dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter3dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter3dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter3dDim2EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter3dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter3dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter3dDim2EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim2EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim3EndToEndTest)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim2EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClSplitter4dDim3EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndFloatNchwTest)
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndUint8NchwTest)
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndFloatNhwcTest)
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndUint8NhwcTest)
BOOST_AUTO_TEST_CASE (ClQuantizedLstmEndToEndTest)
BOOST_AUTO_TEST_CASE (ClArgMaxSimpleTest)
BOOST_AUTO_TEST_CASE (ClArgMinSimpleTest)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis0Test)
BOOST_AUTO_TEST_CASE (ClArgMinAxis0Test)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis1Test)
BOOST_AUTO_TEST_CASE (ClArgMinAxis1Test)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis2Test)
BOOST_AUTO_TEST_CASE (ClArgMinAxis2Test)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis3Test)
BOOST_AUTO_TEST_CASE (ClArgMinAxis3Test)
BOOST_AUTO_TEST_CASE (ClArgMaxSimpleTestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMinSimpleTestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis0TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMinAxis0TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis1TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMinAxis1TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis2TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMinAxis2TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMaxAxis3TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClArgMinAxis3TestQAsymmU8)
BOOST_AUTO_TEST_CASE (ClQLstmEndToEndTest)
Variables
std::vector< armnn::BackendId > defaultBackends = {armnn::Compute::GpuAcc}
Function Documentation
BOOST_AUTO_TEST_CASE() [1/89]
BOOST_AUTO_TEST_CASE (ClAbsEndToEndTestFloat32)
Definition at line 31 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     std::vector<float> expectedOutput =
     {
         1.f, 1.f, 1.f, 1.f, 5.f, 5.f, 5.f, 5.f,
         3.f, 3.f, 3.f, 3.f, 4.f, 4.f, 4.f, 4.f
     };
     ElementwiseUnarySimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                              UnaryOperation::Abs,
                                                              expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [2/89]
BOOST_AUTO_TEST_CASE (ConstantUsage_Cl_Float32)
Definition at line 45 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConstantUsageFloat32Test(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [3/89]
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim0Test)
Definition at line 50 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [4/89]
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim0Uint8Test)
Definition at line 55 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [5/89]
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim1Test)
Definition at line 60 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [6/89]
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim1Uint8Test)
Definition at line 65 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [7/89]
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim3Test)
Definition at line 70 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [8/89]
BOOST_AUTO_TEST_CASE (ClConcatEndToEndDim3Uint8Test)
Definition at line 75 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [9/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat32)
Definition at line 81 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [10/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat16)
Definition at line 86 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [11/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwUint8)
Definition at line 91 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [12/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwInt16)
Definition at line 96 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [13/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat32)
Definition at line 101 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [14/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat16)
Definition at line 106 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [15/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcUint8)
Definition at line 111 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [16/89]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcInt16)
Definition at line 116 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [17/89]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleTest)
Definition at line 122 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [18/89]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetTest)
Definition at line 127 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndOffset<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [19/89]
BOOST_AUTO_TEST_CASE (ClStridedSliceInvalidSliceEndToEndTest)
Definition at line 132 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     StridedSliceInvalidSliceEndToEndTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [20/89]
BOOST_AUTO_TEST_CASE (ClEluEndToEndTestFloat32)
Definition at line 137 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [21/89]
BOOST_AUTO_TEST_CASE (ClEluEndToEndTestFloat16)
Definition at line 142 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [22/89]
BOOST_AUTO_TEST_CASE (ClGreaterSimpleEndToEndTest)
Definition at line 147 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 0, 0, 0,  1, 1, 1, 1,
                                                 0, 0, 0, 0,  0, 0, 0, 0 });
     ComparisonSimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                        ComparisonOperation::Greater,
                                                        expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [23/89]
BOOST_AUTO_TEST_CASE (ClGreaterSimpleEndToEndUint8Test)
Definition at line 157 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 0, 0, 0,  1, 1, 1, 1,
                                                 0, 0, 0, 0,  0, 0, 0, 0 });
     ComparisonSimpleEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                ComparisonOperation::Greater,
                                                                expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [24/89]
BOOST_AUTO_TEST_CASE (ClGreaterBroadcastEndToEndTest)
Definition at line 167 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 1, 0, 0, 0, 1,
                                                 1, 1, 1, 1, 1, 1 });
     ComparisonBroadcastEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                           ComparisonOperation::Greater,
                                                           expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [25/89]
BOOST_AUTO_TEST_CASE (ClGreaterBroadcastEndToEndUint8Test)
Definition at line 177 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 1, 0, 0, 0, 1,
                                                 1, 1, 1, 1, 1, 1 });
     ComparisonBroadcastEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                   ComparisonOperation::Greater,
                                                                   expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [26/89]
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestFloat32)
Definition at line 188 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [27/89]
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestFloat16)
Definition at line 193 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [28/89]
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestQAsymmS8)
Definition at line 198 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QAsymmS8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [29/89]
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestQAsymmU8)
Definition at line 203 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [30/89]
BOOST_AUTO_TEST_CASE (ClHardSwishEndToEndTestQSymmS16)
Definition at line 208 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [31/89]
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNhwcEndToEndTest1)
Definition at line 214 of file ClEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNhwcEndToEndTest1().
 {
     InstanceNormalizationNhwcEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [32/89]
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNchwEndToEndTest1)
Definition at line 219 of file ClEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNchwEndToEndTest1().
 {
     InstanceNormalizationNchwEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [33/89]
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNhwcEndToEndTest2)
Definition at line 224 of file ClEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNhwcEndToEndTest2().
 {
     InstanceNormalizationNhwcEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [34/89]
BOOST_AUTO_TEST_CASE (ClInstanceNormalizationNchwEndToEndTest2)
Definition at line 229 of file ClEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNchwEndToEndTest2().
 {
     InstanceNormalizationNchwEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [35/89]
BOOST_AUTO_TEST_CASE (ClFillEndToEndTest)
Definition at line 235 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [36/89]
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestFloat16)
Definition at line 240 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [37/89]
BOOST_AUTO_TEST_CASE (ClFillEndToEndTestInt32)
Definition at line 245 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Signed32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [38/89]
BOOST_AUTO_TEST_CASE (ClPreluEndToEndFloat32Test)
Definition at line 251 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndNegativeTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [39/89]
BOOST_AUTO_TEST_CASE (ClPreluEndToEndTestUint8)
Definition at line 256 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndPositiveTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [40/89]
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNhwcEndToEndTest1)
Definition at line 261 of file ClEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNhwcEndToEndTest1().
 {
     SpaceToDepthNhwcEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [41/89]
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNchwEndToEndTest1)
Definition at line 266 of file ClEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNchwEndToEndTest1().
 {
     SpaceToDepthNchwEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [42/89]
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNhwcEndToEndTest2)
Definition at line 271 of file ClEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNhwcEndToEndTest2().
 {
     SpaceToDepthNhwcEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [43/89]
BOOST_AUTO_TEST_CASE (ClSpaceToDepthNchwEndToEndTest2)
Definition at line 276 of file ClEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNchwEndToEndTest2().
 {
     SpaceToDepthNchwEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [44/89]
BOOST_AUTO_TEST_CASE (ClSplitter1dEndToEndTest)
Definition at line 281 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter1dEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [45/89]
BOOST_AUTO_TEST_CASE (ClSplitter1dEndToEndUint8Test)
Definition at line 286 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter1dEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [46/89]
BOOST_AUTO_TEST_CASE (ClSplitter2dDim0EndToEndTest)
Definition at line 291 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [47/89]
BOOST_AUTO_TEST_CASE (ClSplitter2dDim1EndToEndTest)
Definition at line 296 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [48/89]
BOOST_AUTO_TEST_CASE (ClSplitter2dDim0EndToEndUint8Test)
Definition at line 301 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [49/89]
BOOST_AUTO_TEST_CASE (ClSplitter2dDim1EndToEndUint8Test)
Definition at line 306 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [50/89]
BOOST_AUTO_TEST_CASE (ClSplitter3dDim0EndToEndTest)
Definition at line 311 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [51/89]
BOOST_AUTO_TEST_CASE (ClSplitter3dDim1EndToEndTest)
Definition at line 316 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [52/89]
BOOST_AUTO_TEST_CASE (ClSplitter3dDim2EndToEndTest)
Definition at line 321 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [53/89]
BOOST_AUTO_TEST_CASE (ClSplitter3dDim0EndToEndUint8Test)
Definition at line 326 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [54/89]
BOOST_AUTO_TEST_CASE (ClSplitter3dDim1EndToEndUint8Test)
Definition at line 331 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [55/89]
BOOST_AUTO_TEST_CASE (ClSplitter3dDim2EndToEndUint8Test)
Definition at line 336 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [56/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim0EndToEndTest)
Definition at line 341 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [57/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim1EndToEndTest)
Definition at line 346 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [58/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim2EndToEndTest)
Definition at line 351 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [59/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim3EndToEndTest)
Definition at line 356 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [60/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim0EndToEndUint8Test)
Definition at line 361 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [61/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim1EndToEndUint8Test)
Definition at line 366 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [62/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim2EndToEndUint8Test)
Definition at line 371 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [63/89]
BOOST_AUTO_TEST_CASE (ClSplitter4dDim3EndToEndUint8Test)
Definition at line 376 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [64/89]
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndFloatNchwTest)
Definition at line 382 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::Float32, armnn::DataType::Float32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [65/89]
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndUint8NchwTest)
Definition at line 388 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [66/89]
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndFloatNhwcTest)
Definition at line 394 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::Float32, armnn::DataType::Float32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [67/89]
BOOST_AUTO_TEST_CASE (ClTransposeConvolution2dEndToEndUint8NhwcTest)
Definition at line 400 of file ClEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [68/89]
BOOST_AUTO_TEST_CASE (ClQuantizedLstmEndToEndTest)
Definition at line 406 of file ClEndToEndTests.cpp.
References defaultBackends, and QuantizedLstmEndToEnd().
 {
     QuantizedLstmEndToEnd(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [69/89]
BOOST_AUTO_TEST_CASE (ClArgMaxSimpleTest)
Definition at line 412 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxEndToEndSimple<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [70/89]
BOOST_AUTO_TEST_CASE (ClArgMinSimpleTest)
Definition at line 417 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinEndToEndSimple<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [71/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis0Test)
Definition at line 422 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [72/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis0Test)
Definition at line 427 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [73/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis1Test)
Definition at line 432 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [74/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis1Test)
Definition at line 437 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [75/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis2Test)
Definition at line 442 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [76/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis2Test)
Definition at line 447 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [77/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis3Test)
Definition at line 452 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [78/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis3Test)
Definition at line 457 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [79/89]
BOOST_AUTO_TEST_CASE (ClArgMaxSimpleTestQAsymmU8)
Definition at line 462 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [80/89]
BOOST_AUTO_TEST_CASE (ClArgMinSimpleTestQAsymmU8)
Definition at line 467 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [81/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis0TestQAsymmU8)
Definition at line 472 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [82/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis0TestQAsymmU8)
Definition at line 477 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [83/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis1TestQAsymmU8)
Definition at line 482 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [84/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis1TestQAsymmU8)
Definition at line 487 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [85/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis2TestQAsymmU8)
Definition at line 492 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [86/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis2TestQAsymmU8)
Definition at line 497 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [87/89]
BOOST_AUTO_TEST_CASE (ClArgMaxAxis3TestQAsymmU8)
Definition at line 502 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [88/89]
BOOST_AUTO_TEST_CASE (ClArgMinAxis3TestQAsymmU8)
Definition at line 507 of file ClEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [89/89]
BOOST_AUTO_TEST_CASE (ClQLstmEndToEndTest)
Definition at line 512 of file ClEndToEndTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), defaultBackends, and QLstmEndToEnd().
 {
     QLstmEndToEnd(defaultBackends);
 }
Variable Documentation
defaultBackends
std::vector<armnn::BackendId> defaultBackends = {armnn::Compute::GpuAcc}
Definition at line 28 of file ClEndToEndTests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), DepthToSpaceEndToEnd(), and main().