ArmNN: src/armnnOnnxParser/test/CreateNetwork.cpp File Reference
CreateNetwork.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "armnnOnnxParser/IOnnxParser.hpp"
#include "google/protobuf/stubs/logging.h"
Functions
BOOST_AUTO_TEST_CASE (CreateNetworkFromString)
BOOST_AUTO_TEST_CASE (CreateNetworkFromStringWithNullptr)
BOOST_AUTO_TEST_CASE (CreateNetworkWithInvalidString)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (CreateNetworkFromString)
Definition at line 12 of file CreateNetwork.cpp.
References IOnnxParser::Create().
 {
   std::string TestModel = R"(
                           ir_version: 3
                           producer_name:  "CNTK "
                           producer_version:  "2.5.1 "
                           domain:  "ai.cntk "
                           model_version: 1
                           graph {
                             name:  "CNTKGraph "
                             output {
                                  name:  "Output"
                                  type {
                                     tensor_type {
                                       elem_type: 1
                                       shape {
                                         dim {
                                            dim_value: 1
                                         }
                                         dim {
                                            dim_value: 10
                                         }
                                       }
                                     }
                                  }
                              }
                           }
                           opset_import {
                              version: 7
                            })";
     armnnOnnxParser::IOnnxParserPtr parser(armnnOnnxParser::IOnnxParser::Create());
     armnn::INetworkPtr network = parser->CreateNetworkFromString(TestModel.c_str());
     BOOST_TEST(network.get());
 }
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (CreateNetworkFromStringWithNullptr)
Definition at line 49 of file CreateNetwork.cpp.
References IOnnxParser::Create().
 {
     armnnOnnxParser::IOnnxParserPtr parser(armnnOnnxParser::IOnnxParser::Create());
     BOOST_CHECK_THROW(parser->CreateNetworkFromString(""), armnn::InvalidArgumentException );
 }
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (CreateNetworkWithInvalidString)
Definition at line 55 of file CreateNetwork.cpp.
References BOOST_AUTO_TEST_SUITE_END(), and IOnnxParser::Create().
 {
     auto silencer = google::protobuf::LogSilencer(); //get rid of errors from protobuf
     armnnOnnxParser::IOnnxParserPtr parser(armnnOnnxParser::IOnnxParser::Create());
     BOOST_CHECK_THROW(parser->CreateNetworkFromString( "I'm not a model so I should raise an error" ),
                       armnn::ParseException );
 }