ArmNN: src/armnn/test/EndToEndTest.cpp File Reference
EndToEndTest.cpp File Reference
#include <armnn/Descriptors.hpp>
#include <armnn/IRuntime.hpp>
#include <armnn/INetwork.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <boost/test/unit_test.hpp>
#include <set>
Functions
BOOST_AUTO_TEST_CASE (ErrorOnLoadNetwork)
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (ErrorOnLoadNetwork)
Definition at line 17 of file EndToEndTest.cpp.
References BOOST_AUTO_TEST_SUITE_END(), IOutputSlot::Connect(), armnn::CpuAcc, INetwork::Create(), IRuntime::Create(), armnn::Float32, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), armnn::Optimize(), and IOutputSlot::SetTensorInfo().
 {
     using namespace armnn;
     // Create runtime in which test will run
     // Note we don't allow falling back to CpuRef if an operation (excluding inputs, outputs, etc.) isn't supported
     IRuntime::CreationOptions options;
     IRuntimePtr runtime(IRuntime::Create(options));
     // build up the structure of the network
     INetworkPtr net(INetwork::Create());
     IConnectableLayer* input = net->AddInputLayer(0);
     // This layer configuration isn't supported by CpuAcc and isn't allowed to fall back, so Optimize will return null.
     NormalizationDescriptor descriptor;
     IConnectableLayer* pooling = net->AddNormalizationLayer(descriptor);
     IConnectableLayer* output = net->AddOutputLayer(0);
     input->GetOutputSlot(0).Connect(pooling->GetInputSlot(0));
     pooling->GetOutputSlot(0).Connect(output->GetInputSlot(0));
     input->GetOutputSlot(0).SetTensorInfo(TensorInfo({ 1, 1, 4, 4 }, DataType::Float32));
     pooling->GetOutputSlot(0).SetTensorInfo(TensorInfo({ 1, 1, 4, 4 }, DataType::Float32));
     // optimize the network
     std::vector<BackendId> backends = {Compute::CpuAcc};
     IOptimizedNetworkPtr optNet = Optimize(*net, backends, runtime->GetDeviceSpec());
     BOOST_CHECK(!optNet);
 }