ArmNN: src/armnn/test/optimizations/Fp32NetworkToFp16ConverterTests.cpp File Reference
Fp32NetworkToFp16ConverterTests.cpp File Reference
#include "../TestUtils.hpp"
#include <Optimizer.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (Fp32NetworkToFp16OptimizationTest)
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (Fp32NetworkToFp16OptimizationTest)
Definition at line 15 of file Fp32NetworkToFp16ConverterTests.cpp.
References Graph::AddLayer(), BOOST_AUTO_TEST_SUITE_END(), Graph::cbegin(), Graph::cend(), CheckSequence(), OutputSlot::Connect(), armnn::Float32, Layer::GetOutputSlot(), armnn::MakeOptimizations(), Optimizer::Pass(), and OutputSlot::SetTensorInfo().
 {
     armnn::Graph graph;
     const armnn::TensorInfo infoFP32({ 2, 2, 1, 3 }, armnn::DataType::Float32);
     // Create the simple test network
     auto input = graph.AddLayer<armnn::InputLayer>(0, "input");
     input->GetOutputSlot().SetTensorInfo(infoFP32);
     auto floor = graph.AddLayer<armnn::FloorLayer>("floor");
     floor->GetOutputSlot().SetTensorInfo(infoFP32);
     auto output = graph.AddLayer<armnn::OutputLayer>(1, "output");
     // Connect up the layers
     input->GetOutputSlot().Connect(floor->GetInputSlot(0));
     floor->GetOutputSlot().Connect(output->GetInputSlot(0));
     BOOST_TEST(CheckSequence(graph.cbegin(), graph.cend(), &IsLayerOfType<armnn::InputLayer>,
                              &IsLayerOfType<armnn::FloorLayer>, &IsLayerOfType<armnn::OutputLayer>));
     // Run the optimizer
     armnn::Optimizer::Pass(graph, armnn::MakeOptimizations(Fp32NetworkToFp16Converter()));
     BOOST_TEST(CheckSequence(graph.cbegin(), graph.cend(), &IsLayerOfType<armnn::InputLayer>,
                              &IsLayerOfType<armnn::ConvertFp32ToFp16Layer>, &IsLayerOfType<armnn::FloorLayer>,
                              &IsLayerOfType<armnn::ConvertFp16ToFp32Layer>, &IsLayerOfType<armnn::OutputLayer>));
 }