ArmNN: src/backends/backendsCommon/test/layerTests/GatherTestImpl.hpp File Reference
GatherTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <Half.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 1 > Gather1dParamsFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 1 > Gather1dParamsFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 1 > Gather1dParamsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 1 > Gather1dParamsInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int32_t, 1 > Gather1dParamsInt32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 2 > GatherMultiDimParamsFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 2 > GatherMultiDimParamsFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 2 > GatherMultiDimParamsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 2 > GatherMultiDimParamsInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int32_t, 2 > GatherMultiDimParamsInt32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > GatherMultiDimParamsMultiDimIndicesFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > GatherMultiDimParamsMultiDimIndicesFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > GatherMultiDimParamsMultiDimIndicesUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > GatherMultiDimParamsMultiDimIndicesInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int32_t, 4 > GatherMultiDimParamsMultiDimIndicesInt32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
Gather1dParamsFloat16Test()
LayerTestResult<armnn::Half, 1> Gather1dParamsFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 308 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float16>::Gather1dParamsTestImpl(workloadFactory, memoryManager);
 }
Gather1dParamsFloat32Test()
LayerTestResult<float, 1> Gather1dParamsFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 301 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float32>::Gather1dParamsTestImpl(workloadFactory, memoryManager);
 }
Gather1dParamsInt16Test()
LayerTestResult<int16_t, 1> Gather1dParamsInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 322 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QSymmS16>::Gather1dParamsTestImpl(workloadFactory, memoryManager);
 }
Gather1dParamsInt32Test()
LayerTestResult<int32_t, 1> Gather1dParamsInt32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 329 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Signed32>::Gather1dParamsTestImpl(workloadFactory, memoryManager);
 }
Gather1dParamsUint8Test()
LayerTestResult<uint8_t, 1> Gather1dParamsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 315 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QAsymmU8>::Gather1dParamsTestImpl(workloadFactory, memoryManager);
 }
GatherMultiDimParamsFloat16Test()
LayerTestResult<armnn::Half, 2> GatherMultiDimParamsFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 343 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float16>::GatherMultiDimParamsTestImpl(workloadFactory, memoryManager);
 }
GatherMultiDimParamsFloat32Test()
LayerTestResult<float, 2> GatherMultiDimParamsFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 336 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float32>::GatherMultiDimParamsTestImpl(workloadFactory, memoryManager);
 }
GatherMultiDimParamsInt16Test()
LayerTestResult<int16_t, 2> GatherMultiDimParamsInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 358 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QSymmS16>::GatherMultiDimParamsTestImpl(
         workloadFactory, memoryManager);
 }
GatherMultiDimParamsInt32Test()
LayerTestResult<int32_t, 2> GatherMultiDimParamsInt32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 366 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Signed32>::GatherMultiDimParamsTestImpl(
             workloadFactory, memoryManager);
 }
GatherMultiDimParamsMultiDimIndicesFloat16Test()
LayerTestResult<armnn::Half, 4> GatherMultiDimParamsMultiDimIndicesFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 382 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float16>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager);
 }
GatherMultiDimParamsMultiDimIndicesFloat32Test()
LayerTestResult<float, 4> GatherMultiDimParamsMultiDimIndicesFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 374 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Float32>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager);
 }
GatherMultiDimParamsMultiDimIndicesInt16Test()
LayerTestResult<int16_t, 4> GatherMultiDimParamsMultiDimIndicesInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 398 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QSymmS16>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager);
 }
GatherMultiDimParamsMultiDimIndicesInt32Test()
LayerTestResult<int32_t, 4> GatherMultiDimParamsMultiDimIndicesInt32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 406 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::Signed32>::GatherMultiDimParamsMultiDimIndicesTestImpl(
             workloadFactory, memoryManager);
 }
GatherMultiDimParamsMultiDimIndicesUint8Test()
LayerTestResult<uint8_t, 4> GatherMultiDimParamsMultiDimIndicesUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 390 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QAsymmU8>::GatherMultiDimParamsMultiDimIndicesTestImpl(
         workloadFactory, memoryManager);
 }
GatherMultiDimParamsUint8Test()
LayerTestResult<uint8_t, 2> GatherMultiDimParamsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 350 of file GatherTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return GatherTestHelper<armnn::DataType::QAsymmU8>::GatherMultiDimParamsTestImpl(
         workloadFactory, memoryManager);
 }