ArmNN: src/backends/backendsCommon/test/JsonPrinterTestImpl.hpp File Reference
JsonPrinterTestImpl.hpp File Reference
#include <armnn/BackendId.hpp>
#include <vector>
Functions
void RunSoftmaxProfilerJsonPrinterTest (const std::vector< armnn::BackendId > &backends)
Function Documentation
RunSoftmaxProfilerJsonPrinterTest()
void RunSoftmaxProfilerJsonPrinterTest (const std::vector< armnn::BackendId > & backends)
Definition at line 245 of file JsonPrinterTestImpl.cpp.
References armnn::CpuAcc, GetSoftmaxProfilerJson(), armnn::GpuAcc, and ValidateProfilerJson().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     // setup the test fixture and obtain JSON Printer result
     std::string result = GetSoftmaxProfilerJson(backends);
     // validate the JSON Printer result
     ValidateProfilerJson(result);
     const armnn::BackendId& firstBackend = backends.at(0);
     if (firstBackend == armnn::Compute::GpuAcc)
     {
         BOOST_CHECK(result.find("OpenClKernelTimer/: softmax_layer_max_shift_exp_sum_quantized_serial GWS[,,]")
                     != std::string::npos);
     }
     else if (firstBackend == armnn::Compute::CpuAcc)
     {
         BOOST_CHECK(result.find("NeonKernelTimer/: NEFillBorderKernel") != std::string::npos);
     }
 }