ArmNN: src/armnnTfLiteParser/test/L2Normalization.cpp File Reference
L2Normalization.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "ParserFlatbuffersFixture.hpp"
#include "../TfLiteParser.hpp"
#include <string>
#include <iostream>
Functions
float CalcL2Norm (std::initializer_list< float > elements)
BOOST_FIXTURE_TEST_CASE (ParseL2Normalization4D, L2NormalizationFixture4D)
BOOST_FIXTURE_TEST_CASE (ParseL2NormalizationEps4D, L2NormalizationSimpleFixture4D)
Function Documentation
BOOST_FIXTURE_TEST_CASE() [1/2]
BOOST_FIXTURE_TEST_CASE (ParseL2Normalization4D , L2NormalizationFixture4D)
Definition at line 85 of file L2Normalization.cpp.
References CalcL2Norm().
 {
   RunTest<4, armnn::DataType::Float32>(
       0,
       {{"inputTensor", { 1.0f,  2.0f,  3.0f,
                          4.0f,  5.0f,  6.0f,
                          7.0f,  8.0f,  9.0f,
                          10.0f, 11.0f, 12.0f }}},
       {{"outputTensor", { 1.0f  / CalcL2Norm({ 1.0f,  2.0f,  3.0f }),
                           2.0f  / CalcL2Norm({ 1.0f,  2.0f,  3.0f }),
                           3.0f  / CalcL2Norm({ 1.0f,  2.0f,  3.0f }),
                           4.0f  / CalcL2Norm({ 4.0f,  5.0f,  6.0f }),
                           5.0f  / CalcL2Norm({ 4.0f,  5.0f,  6.0f }),
                           6.0f  / CalcL2Norm({ 4.0f,  5.0f,  6.0f }),
                           7.0f  / CalcL2Norm({ 7.0f,  8.0f,  9.0f }),
                           8.0f  / CalcL2Norm({ 7.0f,  8.0f,  9.0f }),
                           9.0f  / CalcL2Norm({ 7.0f,  8.0f,  9.0f }),
                           10.0f / CalcL2Norm({ 10.0f, 11.0f, 12.0f }),
                           11.0f / CalcL2Norm({ 10.0f, 11.0f, 12.0f }),
                           12.0f / CalcL2Norm({ 10.0f, 11.0f, 12.0f }) }}});
 }
BOOST_FIXTURE_TEST_CASE() [2/2]
BOOST_FIXTURE_TEST_CASE (ParseL2NormalizationEps4D , L2NormalizationSimpleFixture4D)
Definition at line 116 of file L2Normalization.cpp.
References BOOST_AUTO_TEST_SUITE_END(), and CalcL2Norm().
 {
       RunTest<4, armnn::DataType::Float32>(
       0,
       {{"inputTensor", { 0.00000001f, 0.00000002f, 0.00000003f, 0.00000004f }}},
       {{"outputTensor", { 0.00000001f / CalcL2Norm({ 0.00000001f, 0.00000002f, 0.00000003f, 0.00000004f }),
                           0.00000002f / CalcL2Norm({ 0.00000001f, 0.00000002f, 0.00000003f, 0.00000004f }),
                           0.00000003f / CalcL2Norm({ 0.00000001f, 0.00000002f, 0.00000003f, 0.00000004f }),
                           0.00000004f / CalcL2Norm({ 0.00000001f, 0.00000002f, 0.00000003f, 0.00000004f }) }}});
 }
CalcL2Norm()
float CalcL2Norm (std::initializer_list< float > elements)
Definition at line 70 of file L2Normalization.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE().
 {
     const float reduction = std::accumulate(elements.begin(), elements.end(), 0.0f,
         [](float acc, float element) { return acc + element * element; });
     const float eps = 1e-12f;
     const float max = reduction < eps ? eps : reduction;
     return sqrtf(max);
 }