ArmNN: src/backends/backendsCommon/test/layerTests/L2NormalizationTestImpl.hpp File Reference
L2NormalizationTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <armnn/Types.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > L2NormalizationDefaultEpsilonTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2NormalizationNonDefaultEpsilonTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2Normalization1dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization1dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2Normalization2dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< float, 2 > L2Normalization2dShapeTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > L2Normalization3dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< float, 4 > L2Normalization4dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< int16_t, 4 > L2Normalization4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
LayerTestResult< uint8_t, 4 > L2Normalization4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::DataLayout layout)
Function Documentation
L2Normalization1dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization1dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 599 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization1dTest()
LayerTestResult<float, 4> L2Normalization1dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 584 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization1dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 614 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2Normalization2dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 644 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization2dShapeTest()
LayerTestResult<float, 2> L2Normalization2dShapeTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 674 of file L2NormalizationTestImpl.cpp.
References ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateL2Normalization(), IWorkloadFactory::CreateTensorHandle(), armnn::Float32, L2NormalizationDescriptor::m_Eps, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::NHWC.
 {
     const armnn::DataLayout layout = armnn::DataLayout::NHWC;
     const armnn::TensorShape inputOutputTensorShape = armnn::TensorShape({ 5, 2 });
     std::vector<float> inputData
     {
         1.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f, 8.f, 9.f, 10.f
     };
     std::vector<float> expectedOutputData
     {
         1.0f * CalcInvL2Norm({ 1.0f,  2.0f }),
         2.0f * CalcInvL2Norm({ 1.0f,  2.0f }),
         3.0f * CalcInvL2Norm({ 3.0f,  4.0f }),
         4.0f * CalcInvL2Norm({ 3.0f,  4.0f }),
         5.0f * CalcInvL2Norm({ 5.0f,  6.0f }),
         6.0f * CalcInvL2Norm({ 5.0f,  6.0f }),
         7.0f * CalcInvL2Norm({ 7.0f,  8.0f }),
         8.0f * CalcInvL2Norm({ 7.0f,  8.0f }),
         9.0f  * CalcInvL2Norm({ 9.0f, 10.0f }),
         10.0f * CalcInvL2Norm({ 9.0f, 10.0f })
     };
     const armnn::TensorInfo inputTensorInfo(inputOutputTensorShape, armnn::DataType::Float32, 0.f, 0);
     const armnn::TensorInfo outputTensorInfo(inputOutputTensorShape, armnn::DataType::Float32, 0.f, 0);
     auto inputTensor = MakeTensor<float, 2>(inputTensorInfo, inputData);
     LayerTestResult<float, 2> result(outputTensorInfo);
     result.outputExpected = MakeTensor<float, 2>(outputTensorInfo, expectedOutputData);
     ARMNN_NO_DEPRECATE_WARN_BEGIN
     std::unique_ptr<armnn::ITensorHandle> inputHandle = workloadFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = workloadFactory.CreateTensorHandle(outputTensorInfo);
     ARMNN_NO_DEPRECATE_WARN_END
     armnn::L2NormalizationQueueDescriptor descriptor;
     descriptor.m_Parameters.m_Eps = 1e-12f;
     descriptor.m_Parameters.m_DataLayout = layout;
     armnn::WorkloadInfo info;
     AddInputToWorkload(descriptor, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateL2Normalization(descriptor, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &inputTensor[0][0]);
     workload->PostAllocationConfigure();
     ExecuteWorkload(*workload, memoryManager);
     CopyDataFromITensorHandle(&result.output[0][0], outputHandle.get());
     return result;
 }
L2Normalization2dTest()
LayerTestResult<float, 4> L2Normalization2dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 629 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization2dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization2dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 659 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2Normalization3dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 750 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization3dTest()
LayerTestResult<float, 4> L2Normalization3dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 735 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization3dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization3dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 765 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2Normalization4dInt16Test()
LayerTestResult<int16_t, 4> L2Normalization4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 795 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f,
         0,
         layout);
 }
L2Normalization4dTest()
LayerTestResult<float, 4> L2Normalization4dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 780 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization4dTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         0.f,
         0,
         0.f,
         0,
         layout);
 }
L2Normalization4dUint8Test()
LayerTestResult<uint8_t, 4> L2Normalization4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 810 of file L2NormalizationTestImpl.cpp.
 {
     return L2Normalization1dTestCommon<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         1.f,
         0,
         1.f / 128,
         128,
         layout);
 }
L2NormalizationDefaultEpsilonTest()
LayerTestResult<float, 4> L2NormalizationDefaultEpsilonTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 549 of file L2NormalizationTestImpl.cpp.
References L2NormalizationDescriptor::m_Eps.
 {
     // Dummy descriptor to get the default value of epsilon.
     armnn::L2NormalizationDescriptor descriptor;
     return L2NormalizationEpsilonTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         0.f,
         0,
         0.f,
         0,
         layout,
         descriptor.m_Eps);
 }
L2NormalizationNonDefaultEpsilonTest()
LayerTestResult<float, 4> L2NormalizationNonDefaultEpsilonTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::DataLayout layout)
Definition at line 568 of file L2NormalizationTestImpl.cpp.
 {
     return L2NormalizationEpsilonTestCommon<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         0.f,
         0,
         0.f,
         0,
         layout,
         1e-9f);
 }