ArmNN: src/armnn/test/optimizations/PermuteAndBatchToSpaceAsDepthToSpaceTests.cpp File Reference
PermuteAndBatchToSpaceAsDepthToSpaceTests.cpp File Reference
#include "../TestUtils.hpp"
#include <Network.hpp>
#include <Optimizer.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (PermuteAndBatchToSpaceAsDepthToSpaceOptimizerTest)
Tests that the optimization performed by PermuteAndBatchToSpaceAsDepthToSpace is as expected.
BOOST_AUTO_TEST_CASE (TransposeAndBatchToSpaceAsDepthToSpaceOptimizerTest)
Tests that the optimization performed by PermuteAndBatchToSpaceAsDepthToSpace is as expected.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (PermuteAndBatchToSpaceAsDepthToSpaceOptimizerTest)
Tests that the optimization performed by PermuteAndBatchToSpaceAsDepthToSpace is as expected.
Note this does not ensure the correctness of the optimization - that is done in the below test.
Definition at line 87 of file PermuteAndBatchToSpaceAsDepthToSpaceTests.cpp.
References Graph::cbegin(), Graph::cend(), CheckSequence(), armnn::Float32, armnn::MakeOptimizations(), armnn::NHWC, and Optimizer::Pass().
 {
     INetworkPtr network = CreateTestNetwork();
     Graph graph         = static_cast<Network*>(network.get())->GetGraph();
     // Confirm initial graph is as we expect
     BOOST_TEST(CheckSequence(graph.cbegin(), graph.cend(), &IsLayerOfType<InputLayer>, &IsLayerOfType<PermuteLayer>,
                              &IsLayerOfType<BatchToSpaceNdLayer>, &IsLayerOfType<OutputLayer>));
     // Perform the optimization which should merge the two layers into a DepthToSpace
     armnn::Optimizer::Pass(graph, MakeOptimizations(PermuteAndBatchToSpaceAsDepthToSpace()));
     // Check that the replacement has been made as expected
     auto checkDepthToSpace = [](const Layer* const layer) -> bool {
         return IsLayerOfType<DepthToSpaceLayer>(layer) &&
                static_cast<const DepthToSpaceLayer*>(layer)->GetParameters().m_BlockSize == 2 &&
                static_cast<const DepthToSpaceLayer*>(layer)->GetParameters().m_DataLayout == DataLayout::NHWC &&
                layer->GetOutputHandler().GetTensorInfo() == TensorInfo({ 1, 4, 6, 1 }, DataType::Float32);
     };
     BOOST_TEST(CheckSequence(graph.cbegin(), graph.cend(), &IsLayerOfType<InputLayer>, checkDepthToSpace,
                              &IsLayerOfType<OutputLayer>));
     // Check the new layer has the two merged layers listed as related layers
     std::list<std::string> testRelatedLayers = { "batchToSpace", "permute" };
     BOOST_TEST(CheckRelatedLayers<DepthToSpaceLayer>(graph, testRelatedLayers));
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (TransposeAndBatchToSpaceAsDepthToSpaceOptimizerTest)
Tests that the optimization performed by PermuteAndBatchToSpaceAsDepthToSpace is as expected.
Note this does not ensure the correctness of the optimization - that is done in the below test.
Definition at line 117 of file PermuteAndBatchToSpaceAsDepthToSpaceTests.cpp.
References armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_SUITE_END(), Graph::cbegin(), Graph::cend(), CheckSequence(), armnn::CpuRef, IRuntime::Create(), armnn::Float32, armnn::MakeOptimizations(), armnn::NHWC, armnn::Optimize(), and Optimizer::Pass().
 {
     INetworkPtr network = CreateTransposeTestNetwork();
     Graph graph         = static_cast<Network*>(network.get())->GetGraph();
     // Confirm initial graph is as we expect
     BOOST_TEST(CheckSequence(graph.cbegin(), graph.cend(), &IsLayerOfType<InputLayer>, &IsLayerOfType<TransposeLayer>,
                              &IsLayerOfType<BatchToSpaceNdLayer>, &IsLayerOfType<OutputLayer>));
     // Perform the optimization which should merge the two layers into a DepthToSpace
     armnn::Optimizer::Pass(graph, MakeOptimizations(TransposeAndBatchToSpaceAsDepthToSpace()));
     // Check that the replacement has been made as expected
     auto checkDepthToSpace = [](const Layer* const layer) -> bool {
         return IsLayerOfType<DepthToSpaceLayer>(layer) &&
                static_cast<const DepthToSpaceLayer*>(layer)->GetParameters().m_BlockSize == 2 &&
                static_cast<const DepthToSpaceLayer*>(layer)->GetParameters().m_DataLayout == DataLayout::NHWC &&
                layer->GetOutputHandler().GetTensorInfo() == TensorInfo({ 1, 4, 6, 1 }, DataType::Float32);
     };
     BOOST_TEST(CheckSequence(graph.cbegin(), graph.cend(), &IsLayerOfType<InputLayer>, checkDepthToSpace,
                              &IsLayerOfType<OutputLayer>));
     // Check the new layer has the two merged layers listed as related layers
     std::list<std::string> testRelatedLayers = { "batchToSpace", "permute" };
     BOOST_TEST(CheckRelatedLayers<DepthToSpaceLayer>(graph, testRelatedLayers));
 }