ArmNN: src/backends/backendsCommon/test/layerTests/QuantizeTestImpl.hpp File Reference
QuantizeTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< uint8_t, 4 > QuantizeSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > QuantizeClampUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int8_t, 4 > QuantizeClampAsymmInt8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int8_t, 4 > QuantizeClampInt8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > QuantizeClampInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
QuantizeClampAsymmInt8Test()
LayerTestResult<int8_t, 4> QuantizeClampAsymmInt8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 144 of file QuantizeTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return QuantizeClampTest<armnn::DataType::QAsymmS8>(workloadFactory, memoryManager);
 }
QuantizeClampInt16Test()
LayerTestResult<int16_t, 4> QuantizeClampInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 158 of file QuantizeTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return QuantizeClampTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
QuantizeClampInt8Test()
LayerTestResult<int8_t, 4> QuantizeClampInt8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 151 of file QuantizeTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return QuantizeClampTest<armnn::DataType::QSymmS8>(workloadFactory, memoryManager);
 }
QuantizeClampUint8Test()
LayerTestResult<uint8_t, 4> QuantizeClampUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 137 of file QuantizeTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return QuantizeClampTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
QuantizeSimpleUint8Test()
LayerTestResult<uint8_t, 4> QuantizeSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 130 of file QuantizeTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return QuantizeSimpleTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }