ArmNN: src/backends/reference/test/RefDetectionPostProcessTests.cpp File Reference
RefDetectionPostProcessTests.cpp File Reference
#include <reference/workloads/DetectionPostProcess.hpp>
#include <armnn/Descriptors.hpp>
#include <armnn/Types.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (TopKSortTest)
BOOST_AUTO_TEST_CASE (FullTopKSortTest)
BOOST_AUTO_TEST_CASE (IouTest)
BOOST_AUTO_TEST_CASE (NmsFunction)
void DetectionPostProcessTestImpl (bool useRegularNms, const std::vector< float > &expectedDetectionBoxes, const std::vector< float > &expectedDetectionClasses, const std::vector< float > &expectedDetectionScores, const std::vector< float > &expectedNumDetections)
BOOST_AUTO_TEST_CASE (RegularNmsDetectionPostProcess)
BOOST_AUTO_TEST_CASE (FastNmsDetectionPostProcess)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (TopKSortTest)
Definition at line 15 of file RefDetectionPostProcessTests.cpp.
References armnn::TopKSort().
 {
     unsigned int k = 3;
     unsigned int indices[8] = { 0, 1, 2, 3, 4, 5, 6, 7 };
     float values[8] = { 0, 7, 6, 5, 4, 3, 2, 500 };
     armnn::TopKSort(k, indices, values, 8);
     BOOST_TEST(indices[0] == 7);
     BOOST_TEST(indices[1] == 1);
     BOOST_TEST(indices[2] == 2);
 }
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (FullTopKSortTest)
Definition at line 26 of file RefDetectionPostProcessTests.cpp.
References armnn::TopKSort().
 {
     unsigned int k = 8;
     unsigned int indices[8] = { 0, 1, 2, 3, 4, 5, 6, 7 };
     float values[8] = { 0, 7, 6, 5, 4, 3, 2, 500 };
     armnn::TopKSort(k, indices, values, 8);
     BOOST_TEST(indices[0] == 7);
     BOOST_TEST(indices[1] == 1);
     BOOST_TEST(indices[2] == 2);
     BOOST_TEST(indices[3] == 3);
     BOOST_TEST(indices[4] == 4);
     BOOST_TEST(indices[5] == 5);
     BOOST_TEST(indices[6] == 6);
     BOOST_TEST(indices[7] == 0);
 }
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (IouTest)
Definition at line 42 of file RefDetectionPostProcessTests.cpp.
References armnn::IntersectionOverUnion().
 {
     float boxI[4] = { 0.0f, 0.0f, 10.0f, 10.0f };
     float boxJ[4] = { 1.0f, 1.0f, 11.0f, 11.0f };
     float iou = armnn::IntersectionOverUnion(boxI, boxJ);
     BOOST_TEST(iou == 0.68, boost::test_tools::tolerance(0.001));
 }
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (NmsFunction)
Definition at line 50 of file RefDetectionPostProcessTests.cpp.
References armnn::NonMaxSuppression(), and scores().
 {
     std::vector<float> boxCorners({
         0.0f, 0.0f, 1.0f, 1.0f,
         0.0f, 0.1f, 1.0f, 1.1f,
         0.0f, -0.1f, 1.0f, 0.9f,
         0.0f, 10.0f, 1.0f, 11.0f,
         0.0f, 10.1f, 1.0f, 11.1f,
         0.0f, 100.0f, 1.0f, 101.0f
     });
     std::vector<float> scores({ 0.9f, 0.75f, 0.6f, 0.93f, 0.5f, 0.3f });
     std::vector<unsigned int> result =
         armnn::NonMaxSuppression(6, boxCorners, scores, 0.0, 3, 0.5);
     BOOST_TEST(result.size() == 3);
     BOOST_TEST(result[0] == 3);
     BOOST_TEST(result[1] == 0);
     BOOST_TEST(result[2] == 5);
 }
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (RegularNmsDetectionPostProcess)
Definition at line 173 of file RefDetectionPostProcessTests.cpp.
References DetectionPostProcessTestImpl().
 {
     std::vector<float> expectedDetectionBoxes({
         0.0f, 10.0f, 1.0f, 11.0f,
         0.0f, 10.0f, 1.0f, 11.0f,
         0.0f, 0.0f, 0.0f, 0.0f
     });
     std::vector<float> expectedDetectionScores({ 0.95f, 0.93f, 0.0f });
     std::vector<float> expectedDetectionClasses({ 1.0f, 0.0f, 0.0f });
     std::vector<float> expectedNumDetections({ 2.0f });
     DetectionPostProcessTestImpl(true, expectedDetectionBoxes, expectedDetectionClasses,
                                  expectedDetectionScores, expectedNumDetections);
 }
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (FastNmsDetectionPostProcess)
Definition at line 189 of file RefDetectionPostProcessTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), and DetectionPostProcessTestImpl().
 {
     std::vector<float> expectedDetectionBoxes({
         0.0f, 10.0f, 1.0f, 11.0f,
         0.0f, 0.0f, 1.0f, 1.0f,
         0.0f, 100.0f, 1.0f, 101.0f
     });
     std::vector<float> expectedDetectionScores({ 0.95f, 0.9f, 0.3f });
     std::vector<float> expectedDetectionClasses({ 1.0f, 0.0f, 0.0f });
     std::vector<float> expectedNumDetections({ 3.0f });
     DetectionPostProcessTestImpl(false, expectedDetectionBoxes, expectedDetectionClasses,
                                  expectedDetectionScores, expectedNumDetections);
 }
DetectionPostProcessTestImpl()
void DetectionPostProcessTestImpl (bool useRegularNms, const std::vector< float > & expectedDetectionBoxes, const std::vector< float > & expectedDetectionClasses, const std::vector< float > & expectedDetectionScores, const std::vector< float > & expectedNumDetections)
Definition at line 72 of file RefDetectionPostProcessTests.cpp.
References anchors(), anchorsInfo, boxEncodings(), armnn::DetectionPostProcess(), armnn::Float32, DetectionPostProcessDescriptor::m_UseRegularNms, scores(), and scoresInfo.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnn::TensorInfo boxEncodingsInfo({ 1, 6, 4 }, armnn::DataType::Float32);
     armnn::TensorInfo scoresInfo({ 1, 6, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo anchorsInfo({ 6, 4 }, armnn::DataType::Float32);
     armnn::TensorInfo detectionBoxesInfo({ 1, 3, 4 }, armnn::DataType::Float32);
     armnn::TensorInfo detectionScoresInfo({ 1, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo detectionClassesInfo({ 1, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo numDetectionInfo({ 1 }, armnn::DataType::Float32);
     armnn::DetectionPostProcessDescriptor desc;
     desc.m_UseRegularNms = useRegularNms;
     desc.m_MaxDetections = 3;
     desc.m_MaxClassesPerDetection = 1;
     desc.m_DetectionsPerClass =1;
     desc.m_NmsScoreThreshold = 0.0;
     desc.m_NmsIouThreshold = 0.5;
     desc.m_NumClasses = 2;
     desc.m_ScaleY = 10.0;
     desc.m_ScaleX = 10.0;
     desc.m_ScaleH = 5.0;
     desc.m_ScaleW = 5.0;
     std::vector<float> boxEncodings({
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, -1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f
     });
     std::vector<float> scores({
         0.0f, 0.9f, 0.8f,
         0.0f, 0.75f, 0.72f,
         0.0f, 0.6f, 0.5f,
         0.0f, 0.93f, 0.95f,
         0.0f, 0.5f, 0.4f,
         0.0f, 0.3f, 0.2f
     });
     std::vector<float> anchors({
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 100.5f, 1.0f, 1.0f
     });
     auto boxEncodingsDecoder = armnn::MakeDecoder<float>(boxEncodingsInfo, boxEncodings.data());
     auto scoresDecoder       = armnn::MakeDecoder<float>(scoresInfo, scores.data());
     auto anchorsDecoder      = armnn::MakeDecoder<float>(anchorsInfo, anchors.data());
     std::vector<float> detectionBoxes(detectionBoxesInfo.GetNumElements());
     std::vector<float> detectionScores(detectionScoresInfo.GetNumElements());
     std::vector<float> detectionClasses(detectionClassesInfo.GetNumElements());
     std::vector<float> numDetections(1);
     armnn::DetectionPostProcess(boxEncodingsInfo,
                                 scoresInfo,
                                 anchorsInfo,
                                 detectionBoxesInfo,
                                 detectionClassesInfo,
                                 detectionScoresInfo,
                                 numDetectionInfo,
                                 desc,
                                 *boxEncodingsDecoder,
                                 *scoresDecoder,
                                 *anchorsDecoder,
                                 detectionBoxes.data(),
                                 detectionClasses.data(),
                                 detectionScores.data(),
                                 numDetections.data());
     BOOST_CHECK_EQUAL_COLLECTIONS(detectionBoxes.begin(),
                                   detectionBoxes.end(),
                                   expectedDetectionBoxes.begin(),
                                   expectedDetectionBoxes.end());
     BOOST_CHECK_EQUAL_COLLECTIONS(detectionScores.begin(),
                                   detectionScores.end(),
                                   expectedDetectionScores.begin(),
                                   expectedDetectionScores.end());
     BOOST_CHECK_EQUAL_COLLECTIONS(detectionClasses.begin(),
                                   detectionClasses.end(),
                                   expectedDetectionClasses.begin(),
                                   expectedDetectionClasses.end());
     BOOST_CHECK_EQUAL_COLLECTIONS(numDetections.begin(),
                                   numDetections.end(),
                                   expectedNumDetections.begin(),
                                   expectedNumDetections.end());
 }