ArmNN: ConstPassthroughCpuTensorHandle Class Reference
ConstPassthroughCpuTensorHandle Class Reference
#include <CpuTensorHandle.hpp>
Public Member Functions
ConstPassthroughCpuTensorHandle (const TensorInfo &tensorInfo, const void *mem)
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
Public Member Functions inherited from ConstCpuTensorHandle
template<typename T >
const T * GetConstTensor () const
const TensorInfo & GetTensorInfo () const
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
Additional Inherited Members
Protected Member Functions inherited from ConstCpuTensorHandle
ConstCpuTensorHandle (const TensorInfo &tensorInfo)
void SetConstMemory (const void *mem)
Detailed Description
Definition at line 157 of file CpuTensorHandle.hpp.
Constructor & Destructor Documentation
ConstPassthroughCpuTensorHandle()
ConstPassthroughCpuTensorHandle (const TensorInfo & tensorInfo, const void * mem) inline
Definition at line 160 of file CpuTensorHandle.hpp.
References ITensorHandle::Allocate(), ConstCpuTensorHandle::GetConstTensor(), CpuTensorHandle::GetTensor(), and ConstCpuTensorHandle::SetConstMemory().
     :   ConstCpuTensorHandle(tensorInfo)
     {
         SetConstMemory(mem);
     }
Member Function Documentation
Allocate()
void Allocate () override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 136 of file CpuTensorHandle.cpp.
 {
     throw InvalidArgumentException("ConstPassthroughCpuTensorHandle::Allocate() should never be called");
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/CpuTensorHandle.hpp
src/backends/backendsCommon/CpuTensorHandle.cpp