ArmNN: InferenceTestImage Class Reference
InferenceTestImage Class Reference
#include <InferenceTestImage.hpp>
Public Types
enum WriteFormat { Png, Bmp, Tga }
enum ResizingMethods { STB, BilinearAndNormalized }
Public Member Functions
InferenceTestImage (const char *filePath)
InferenceTestImage (InferenceTestImage &&)=delete
InferenceTestImage (const InferenceTestImage &)=delete
InferenceTestImage & operator= (const InferenceTestImage &)=delete
InferenceTestImage & operator= (InferenceTestImage &&)=delete
unsigned int GetWidth () const
unsigned int GetHeight () const
unsigned int GetNumChannels () const
unsigned int GetNumElements () const
unsigned int GetSizeInBytes () const
std::tuple< uint8_t, uint8_t, uint8_t > GetPixelAs3Channels (unsigned int x, unsigned int y) const
void StbResize (InferenceTestImage &im, const unsigned int newWidth, const unsigned int newHeight)
std::vector< float > Resize (unsigned int newWidth, unsigned int newHeight, const armnn::CheckLocation &location, const ResizingMethods meth=ResizingMethods::STB, const std::array< float, 3 > &mean={{0.0, 0.0, 0.0}}, const std::array< float, 3 > &stddev={{1.0, 1.0, 1.0}}, const float scale=255.0f)
void Write (WriteFormat format, const char *filePath) const
Detailed Description
Definition at line 51 of file InferenceTestImage.hpp.
Member Enumeration Documentation
ResizingMethods
enum ResizingMethods strong
Enumerator
STB
BilinearAndNormalized
Definition at line 62 of file InferenceTestImage.hpp.
     {
         STB,
         BilinearAndNormalized,
     };
WriteFormat
enum WriteFormat strong
Enumerator
Png
Bmp
Tga
Definition at line 54 of file InferenceTestImage.hpp.
     {
         Png,
         Bmp,
         Tga
     };
Constructor & Destructor Documentation
InferenceTestImage() [1/3]
InferenceTestImage (const char * filePath) explicit
Definition at line 128 of file InferenceTestImage.cpp.
References GetSizeInBytes(), and armnn::numeric_cast().
  : m_Width(0u)
  , m_Height(0u)
  , m_NumChannels(0u)
 {
     int width;
     int height;
     int channels;
     using StbImageDataPtr = std::unique_ptr<unsigned char, decltype(&stbi_image_free)>;
     StbImageDataPtr stbData(stbi_load(filePath, &width, &height, &channels, 0), &stbi_image_free);
     if (stbData == nullptr)
     {
         throw InferenceTestImageLoadFailed(boost::str(boost::format("Could not load the image at %1%") % filePath));
     }
     if (width == 0 || height == 0)
     {
         throw InferenceTestImageLoadFailed(boost::str(boost::format("Could not load empty image at %1%") % filePath));
     }
     m_Width = boost::numeric_cast<unsigned int>(width);
     m_Height = boost::numeric_cast<unsigned int>(height);
     m_NumChannels = boost::numeric_cast<unsigned int>(channels);
     const unsigned int sizeInBytes = GetSizeInBytes();
     m_Data.resize(sizeInBytes);
     memcpy(m_Data.data(), stbData.get(), sizeInBytes);
 }
InferenceTestImage() [2/3]
InferenceTestImage (InferenceTestImage &&) delete
InferenceTestImage() [3/3]
InferenceTestImage (const InferenceTestImage &) delete
Member Function Documentation
GetHeight()
unsigned int GetHeight () const inline
Definition at line 76 of file InferenceTestImage.hpp.
Referenced by GetImageDataAsNormalizedFloats(), GetImageDataInArmNnLayoutAsFloats(), StbResize(), and Write().
 { return m_Height; }
GetNumChannels()
unsigned int GetNumChannels () const inline
Definition at line 77 of file InferenceTestImage.hpp.
Referenced by GetPixelAs3Channels(), StbResize(), and Write().
 { return m_NumChannels; }
GetNumElements()
unsigned int GetNumElements () const inline
Definition at line 78 of file InferenceTestImage.hpp.
 { return GetWidth() * GetHeight() * GetNumChannels(); }
GetPixelAs3Channels()
std::tuple< uint8_t, uint8_t, uint8_t > GetPixelAs3Channels (unsigned int x, unsigned int y) const
Definition at line 159 of file InferenceTestImage.cpp.
References ARMNN_ASSERT, GetNumChannels(), GetSizeInBytes(), and GetWidth().
Referenced by GetImageDataAsNormalizedFloats(), and GetImageDataInArmNnLayoutAsFloats().
 {
     if (x >= m_Width || y >= m_Height)
     {
         throw InferenceTestImageOutOfBoundsAccess(boost::str(boost::format("Attempted out of bounds image access. "
             "Requested (%1%, %2%). Maximum valid coordinates (%3%, %4%).") % x % y % (m_Width - 1) % (m_Height - 1)));
     }
     const unsigned int pixelOffset = x * GetNumChannels() + y * GetWidth() * GetNumChannels();
     const uint8_t* const pixelData = m_Data.data() + pixelOffset;
     ARMNN_ASSERT(pixelData <= (m_Data.data() + GetSizeInBytes()));
     std::array<uint8_t, 3> outPixelData;
     outPixelData.fill(0);
     const unsigned int maxChannelsInPixel = std::min(GetNumChannels(), static_cast<unsigned int>(outPixelData.size()));
     for (unsigned int c = 0; c < maxChannelsInPixel; ++c)
     {
         outPixelData[c] = pixelData[c];
     }
     return std::make_tuple(outPixelData[0], outPixelData[1], outPixelData[2]);
 }
GetSizeInBytes()
unsigned int GetSizeInBytes () const inline
Definition at line 79 of file InferenceTestImage.hpp.
References armnn::Resize().
Referenced by GetPixelAs3Channels(), and InferenceTestImage().
 { return GetNumElements() * GetSingleElementSizeInBytes(); }
GetWidth()
unsigned int GetWidth () const inline
Definition at line 75 of file InferenceTestImage.hpp.
Referenced by GetImageDataAsNormalizedFloats(), GetImageDataInArmNnLayoutAsFloats(), GetPixelAs3Channels(), PrepareImageTensor< float >(), StbResize(), and Write().
 { return m_Width; }
operator=() [1/2]
InferenceTestImage& operator= (const InferenceTestImage &) delete
operator=() [2/2]
InferenceTestImage& operator= (InferenceTestImage &&) delete
Resize()
std::vector< float > Resize (unsigned int newWidth, unsigned int newHeight, const armnn::CheckLocation & location, const ResizingMethods meth = ResizingMethods::STB, const std::array< float, 3 > & mean = {{0.0, 0.0, 0.0}}, const std::array< float, 3 > & stddev = {{1.0, 1.0, 1.0}}, const float scale = 255.0f)
Definition at line 210 of file InferenceTestImage.cpp.
References CheckLocation::AsString(), BilinearAndNormalized, STB, and StbResize().
Referenced by CaffePreprocessor::GetTestCaseData(), and YoloDatabase::GetTestCaseData().
 {
     std::vector<float> out;
     if (newWidth == 0 || newHeight == 0)
     {
         throw InferenceTestImageResizeFailed(boost::str(boost::format("None of the dimensions passed to a resize "
             "operation can be zero. Requested width: %1%. Requested height: %2%.") % newWidth % newHeight));
     }
     switch (meth) {
         case ResizingMethods::STB:
         {
             StbResize(*this, newWidth, newHeight);
             break;
         }
         case ResizingMethods::BilinearAndNormalized:
         {
             out = ResizeBilinearAndNormalize(*this, newWidth, newHeight, scale, mean, stddev);
             break;
         }
         default:
             throw InferenceTestImageResizeFailed(boost::str(
                 boost::format("Unknown resizing method asked ArmNN only supports {STB, BilinearAndNormalized} %1%")
                               % location.AsString()));
     }
     return out;
 }
StbResize()
void StbResize (InferenceTestImage & im, const unsigned int newWidth, const unsigned int newHeight)
Definition at line 184 of file InferenceTestImage.cpp.
References GetHeight(), GetNumChannels(), GetWidth(), and armnn::numeric_cast().
Referenced by Resize().
 {
     std::vector<uint8_t> newData;
     newData.resize(newWidth * newHeight * im.GetNumChannels() * im.GetSingleElementSizeInBytes());
     // boost::numeric_cast<>() is used for user-provided data (protecting about overflows).
     // static_cast<> is ok for internal data (assumes that, when internal data was originally provided by a user,
     // a boost::numeric_cast<>() handled the conversion).
     const int nW = boost::numeric_cast<int>(newWidth);
     const int nH = boost::numeric_cast<int>(newHeight);
     const int w = static_cast<int>(im.GetWidth());
     const int h = static_cast<int>(im.GetHeight());
     const int numChannels = static_cast<int>(im.GetNumChannels());
     const int res = stbir_resize_uint8(im.m_Data.data(), w, h, 0, newData.data(), nW, nH, 0, numChannels);
     if (res == 0)
     {
         throw InferenceTestImageResizeFailed("The resizing operation failed");
     }
     im.m_Data.swap(newData);
     im.m_Width = newWidth;
     im.m_Height = newHeight;
 }
Write()
void Write (WriteFormat format, const char * filePath) const
Definition at line 244 of file InferenceTestImage.cpp.
References Bmp, GetHeight(), GetNumChannels(), GetWidth(), Png, and Tga.
 {
     const int w = static_cast<int>(GetWidth());
     const int h = static_cast<int>(GetHeight());
     const int numChannels = static_cast<int>(GetNumChannels());
     int res = 0;
     switch (format)
     {
     case WriteFormat::Png:
         {
             res = stbi_write_png(filePath, w, h, numChannels, m_Data.data(), 0);
             break;
         }
     case WriteFormat::Bmp:
         {
             res = stbi_write_bmp(filePath, w, h, numChannels, m_Data.data());
             break;
         }
     case WriteFormat::Tga:
         {
             res = stbi_write_tga(filePath, w, h, numChannels, m_Data.data());
             break;
         }
     default:
         throw InferenceTestImageWriteFailed(boost::str(boost::format("Unknown format %1%")
             % static_cast<int>(format)));
     }
     if (res == 0)
     {
         throw InferenceTestImageWriteFailed(boost::str(boost::format("An error occurred when writing to file %1%")
             % filePath));
     }
 }
The documentation for this class was generated from the following files:
tests/InferenceTestImage.hpp
tests/InferenceTestImage.cpp