ArmNN: SocketProfilingConnection Class Reference
SocketProfilingConnection Class Reference
#include <SocketProfilingConnection.hpp>
Public Member Functions
SocketProfilingConnection ()
bool IsOpen () const final
void Close () final
bool WritePacket (const unsigned char *buffer, uint32_t length) final
arm::pipe::Packet ReadPacket (uint32_t timeout) final
Public Member Functions inherited from IProfilingConnection
virtual ~IProfilingConnection ()
Detailed Description
Definition at line 18 of file SocketProfilingConnection.hpp.
Constructor & Destructor Documentation
SocketProfilingConnection()
SocketProfilingConnection ()
Definition at line 20 of file SocketProfilingConnection.cpp.
References SocketProfilingConnection::Close().
 {
     arm::pipe::Initialize();
     memset(m_Socket, 0, sizeof(m_Socket));
     // Note: we're using Linux specific SOCK_CLOEXEC flag.
     m_Socket[0].fd = socket(PF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
     if (m_Socket[0].fd == -1)
     {
         throw arm::pipe::SocketConnectionException(
             std::string("SocketProfilingConnection: Socket construction failed: ")  + strerror(errno),
             m_Socket[0].fd,
             errno);
     }
     // Connect to the named unix domain socket.
     sockaddr_un server{};
     memset(&server, 0, sizeof(sockaddr_un));
     // As m_GatorNamespace begins with a null character we need to ignore that when getting its length.
     memcpy(server.sun_path, m_GatorNamespace, strlen(m_GatorNamespace + 1) + 1);
     server.sun_family = AF_UNIX;
     if (0 != connect(m_Socket[0].fd, reinterpret_cast<const sockaddr*>(&server), sizeof(sockaddr_un)))
     {
         Close();
         throw arm::pipe::SocketConnectionException(
             std::string("SocketProfilingConnection: Cannot connect to stream socket: ")  + strerror(errno),
             m_Socket[0].fd,
             errno);
     }
     // Our socket will only be interested in polling reads.
     m_Socket[0].events = POLLIN;
     // Make the socket non blocking.
     if (!arm::pipe::SetNonBlocking(m_Socket[0].fd))
     {
         Close();
         throw arm::pipe::SocketConnectionException(
             std::string("SocketProfilingConnection: Failed to set socket as non blocking: ")  + strerror(errno),
             m_Socket[0].fd,
             errno);
     }
 }
Member Function Documentation
Close()
void Close () final virtual
Implements IProfilingConnection.
Definition at line 68 of file SocketProfilingConnection.cpp.
Referenced by SocketProfilingConnection::ReadPacket(), and SocketProfilingConnection::SocketProfilingConnection().
 {
     if (arm::pipe::Close(m_Socket[0].fd) != 0)
     {
         throw arm::pipe::SocketConnectionException(
             std::string("SocketProfilingConnection: Cannot close stream socket: ")  + strerror(errno),
             m_Socket[0].fd,
             errno);
     }
     memset(m_Socket, 0, sizeof(m_Socket));
 }
IsOpen()
bool IsOpen () const final virtual
Implements IProfilingConnection.
Definition at line 63 of file SocketProfilingConnection.cpp.
 {
     return m_Socket[0].fd > 0;
 }
ReadPacket()
arm::pipe::Packet ReadPacket (uint32_t timeout) final virtual
Implements IProfilingConnection.
Definition at line 91 of file SocketProfilingConnection.cpp.
References SocketProfilingConnection::Close().
 {
     // Is there currently at least a header worth of data waiting to be read?
     int bytes_available = 0;
     arm::pipe::Ioctl(m_Socket[0].fd, FIONREAD, &bytes_available);
     if (bytes_available >= 8)
     {
         // Yes there is. Read it:
         return ReceivePacket();
     }
     // Poll for data on the socket or until timeout occurs
     int pollResult = arm::pipe::Poll(&m_Socket[0], 1, static_cast<int>(timeout));
     switch (pollResult)
     {
     case -1: // Error
         throw arm::pipe::SocketConnectionException(
             std::string("SocketProfilingConnection: Error occured while reading from socket: ") + strerror(errno),
             m_Socket[0].fd,
             errno);
     case 0: // Timeout
         throw arm::pipe::TimeoutException("SocketProfilingConnection: Timeout while reading from socket");
     default: // Normal poll return but it could still contain an error signal
         // Check if the socket reported an error
         if (m_Socket[0].revents & (POLLNVAL | POLLERR | POLLHUP))
         {
             if (m_Socket[0].revents == POLLNVAL)
             {
                 // This is an unrecoverable error.
                 Close();
                 throw arm::pipe::SocketConnectionException(
                     std::string("SocketProfilingConnection: Error occured while polling receiving socket: POLLNVAL."),
                     m_Socket[0].fd);
             }
             if (m_Socket[0].revents == POLLERR)
             {
                 throw arm::pipe::SocketConnectionException(
                     std::string(
                         "SocketProfilingConnection: Error occured while polling receiving socket: POLLERR: ")
                         + strerror(errno),
                     m_Socket[0].fd,
                     errno);
             }
             if (m_Socket[0].revents == POLLHUP)
             {
                 // This is an unrecoverable error.
                 Close();
                 throw arm::pipe::SocketConnectionException(
                     std::string("SocketProfilingConnection: Connection closed by remote client: POLLHUP."),
                     m_Socket[0].fd);
             }
         }
         // Check if there is data to read
         if (!(m_Socket[0].revents & (POLLIN)))
         {
             // This is a corner case. The socket as been woken up but not with any data.
             // We'll throw a timeout exception to loop around again.
             throw armnn::TimeoutException(
                 "SocketProfilingConnection: File descriptor was polled but no data was available to receive.");
         }
         return ReceivePacket();
     }
 }
WritePacket()
bool WritePacket (const unsigned char * buffer, uint32_t length) final virtual
Implements IProfilingConnection.
Definition at line 81 of file SocketProfilingConnection.cpp.
 {
     if (buffer == nullptr || length == 0)
     {
         return false;
     }
     return arm::pipe::Write(m_Socket[0].fd, buffer, length) != -1;
 }
The documentation for this class was generated from the following files:
src/profiling/SocketProfilingConnection.hpp
src/profiling/SocketProfilingConnection.cpp