ArmNN: IOutputSlot Class Reference
IOutputSlot Class Reference abstract
An output connection slot for a layer.
#include <INetwork.hpp>
Public Member Functions
virtual unsigned int GetNumConnections () const =0
virtual const IInputSlot * GetConnection (unsigned int index) const =0
virtual IInputSlot * GetConnection (unsigned int index)=0
virtual void SetTensorInfo (const TensorInfo &tensorInfo)=0
virtual const TensorInfo & GetTensorInfo () const =0
virtual bool IsTensorInfoSet () const =0
virtual int Connect (IInputSlot &destination)=0
virtual void Disconnect (IInputSlot &slot)=0
virtual unsigned int CalculateIndexOnOwner () const =0
virtual LayerGuid GetOwningLayerGuid () const =0
Protected Member Functions
~IOutputSlot ()
Not user deletable.
Detailed Description
An output connection slot for a layer.
The output slot may be connected to 1 or more input slots of subsequent layers in the graph.
Definition at line 37 of file INetwork.hpp.
Constructor & Destructor Documentation
~IOutputSlot()
~IOutputSlot () inline protected
Not user deletable.
Definition at line 57 of file INetwork.hpp.
 {}
Member Function Documentation
CalculateIndexOnOwner()
virtual unsigned int CalculateIndexOnOwner () const pure virtual
Implemented in OutputSlot.
Referenced by DynamicQuantizationVisitor::DynamicQuantizationVisitor(), SerializerVisitor::GetVersionTable(), StaticRangeVisitor::VisitConcatLayer(), and DynamicQuantizationVisitor::VisitConcatLayer().
Connect()
virtual int Connect (IInputSlot & destination) pure virtual
Implemented in OutputSlot.
Referenced by CaffeParserBase::AddConvLayerWithDepthwiseConv(), CaffeParserBase::AddConvLayerWithSplits(), BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), armnnTfParser::CalculatePaddedOutputTensorInfo(), armnn::CompleteLeakyReluNetwork(), armnnTfLiteParser::ComputeWrappedIndex(), Connect(), armnnTfParser::ConvertTfTensorDataType(), RecordByRecordCaffeParser::CreateNetworkFromBinaryFile(), armnn::CreateNetworkWithActivationLayer(), armnn::CreateNetworkWithFullyConnectedLayer(), armnn::CreateNetworkWithInputOutputLayers(), armnn::CreateNetworkWithSoftmaxLayer(), armnn::CreateStartOfLeakyReluNetwork(), GetSoftmaxProfilerJson(), Deserializer::LoadGraphFromBinary(), CaffeParserBase::LoadNetParam(), armnnTfParser::OutputShapeOfExpandDims(), TfLiteParser::OutputShapeOfReshape(), armnnTfParser::OutputShapeOfSqueeze(), CaffeParserBase::ParseConcatLayer(), CaffeParserBase::ParseConvLayer(), armnn::PreserveTypeTestImpl(), QuantizerVisitor::QuantizerVisitor(), Graph::SubstituteSubgraph(), armnn::TestQuantizeConvolution2d(), armnn::TestQuantizeDepthwiseConvolution2d(), armnn::TestQuantizeTransposeConvolution2d(), TfLiteParser::TfLiteParser(), TfParser::TfParser(), VerifyPostOptimisationStructureTestImpl(), QuantizerVisitor::VisitInputLayer(), and QuantizerVisitor::VisitOutputLayer().
Disconnect()
virtual void Disconnect (IInputSlot & slot) pure virtual
Implemented in OutputSlot.
Referenced by Graph::SubstituteSubgraph().
GetConnection() [1/2]
virtual const IInputSlot* GetConnection (unsigned int index) const pure virtual
Implemented in OutputSlot.
Referenced by BOOST_AUTO_TEST_CASE(), and IsConnected().
GetConnection() [2/2]
virtual IInputSlot* GetConnection (unsigned int index) pure virtual
Implemented in OutputSlot.
GetNumConnections()
virtual unsigned int GetNumConnections () const pure virtual
Implemented in OutputSlot.
Referenced by BOOST_AUTO_TEST_CASE(), and IsConnected().
GetOwningLayerGuid()
virtual LayerGuid GetOwningLayerGuid () const pure virtual
Implemented in OutputSlot.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), DynamicQuantizationVisitor::DynamicQuantizationVisitor(), SerializerVisitor::GetVersionTable(), StaticRangeVisitor::StaticRangeVisitor(), StaticRangeVisitor::VisitConcatLayer(), and DynamicQuantizationVisitor::VisitConcatLayer().
GetTensorInfo()
virtual const TensorInfo& GetTensorInfo () const pure virtual
Implemented in OutputSlot.
Referenced by armnn::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), armnnTfParser::CalculatePaddedOutputTensorInfo(), armnnTfParser::ConvertTfTensorDataType(), Layer::GetDataType(), SerializerVisitor::GetVersionTable(), IsConnected(), IWorkloadFactory::IsLayerSupported(), armnnTfParser::OutputShapeOfExpandDims(), armnnTfParser::OutputShapeOfSqueeze(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), DepthwiseConvolution2dLayer::SerializeLayerParameters(), Convolution2dLayer::SerializeLayerParameters(), TfParser::TfParser(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), ConvertBf16ToFp32Layer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), AbsLayer::ValidateTensorShapesFromInputs(), ConvertFp32ToBf16Layer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), InputLayerVisitor::VisitInputLayer(), QuantizerVisitor::VisitInputLayer(), armnn::VisitLayersTopologically(), and QuantizerVisitor::VisitOutputLayer().
IsTensorInfoSet()
virtual bool IsTensorInfoSet () const pure virtual
Implemented in OutputSlot.
Referenced by Graph::InferTensorInfos().
SetTensorInfo()
virtual void SetTensorInfo (const TensorInfo & tensorInfo) pure virtual
Implemented in OutputSlot.
Referenced by CaffeParserBase::AddConvLayerWithSplits(), BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), armnnTfParser::CalculatePaddedOutputTensorInfo(), armnn::CompleteLeakyReluNetwork(), armnnTfLiteParser::ComputeWrappedIndex(), Connect(), armnnTfParser::ConvertTfTensorDataType(), TfLiteParser::CreateNetworkFromBinary(), OnnxParser::CreateNetworkFromString(), armnn::CreateNetworkWithActivationLayer(), armnn::CreateNetworkWithFullyConnectedLayer(), armnn::CreateNetworkWithInputOutputLayers(), armnn::CreateNetworkWithSoftmaxLayer(), armnn::CreateStartOfLeakyReluNetwork(), Deserializer::GetLstmDescriptor(), Deserializer::GetNetworkOutputBindingInfo(), Deserializer::GetNormalizationDescriptor(), armnnDeserializer::GetOriginsDescriptor(), TfLiteParser::GetOutputTensorIds(), Deserializer::GetPoolingDescriptor(), Deserializer::GetQLstmDescriptor(), GetSoftmaxProfilerJson(), armnnTfParser::OutputShapeOfExpandDims(), Deserializer::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), armnnTfParser::OutputShapeOfSqueeze(), CaffeParserBase::ParseBatchNormLayer(), CaffeParserBase::ParseConcatLayer(), CaffeParserBase::ParseEltwiseLayer(), CaffeParserBase::ParseInnerProductLayer(), CaffeParserBase::ParseLRNLayer(), CaffeParserBase::ParsePoolingLayer(), CaffeParserBase::ParseReluLayer(), CaffeParserBase::ParseScaleLayer(), CaffeParserBase::ParseSoftmaxLayer(), armnn::PreserveTypeTestImpl(), QuantizerVisitor::QuantizerVisitor(), armnn::TestQuantizeConvolution2d(), armnn::TestQuantizeDepthwiseConvolution2d(), armnn::TestQuantizeTransposeConvolution2d(), TfLiteParser::TfLiteParser(), TfParser::TfParser(), VerifyPostOptimisationStructureTestImpl(), QuantizerVisitor::VisitInputLayer(), and QuantizerVisitor::VisitOutputLayer().
The documentation for this class was generated from the following file:
include/armnn/INetwork.hpp