ArmNN: RefConvertBf16ToFp32Workload Class Reference
RefConvertBf16ToFp32Workload Class Reference
#include <RefConvertBf16ToFp32Workload.hpp>
Public Member Functions
virtual void Execute () const override
Public Member Functions inherited from MultiTypedWorkload< QueueDescriptor, InputDataType, OutputDataType >
MultiTypedWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
Public Member Functions inherited from BaseWorkload< QueueDescriptor >
BaseWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const QueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< QueueDescriptor >
const QueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 14 of file RefConvertBf16ToFp32Workload.hpp.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 16 of file RefConvertBf16ToFp32Workload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, FloatingPointConverter::ConvertBFloat16ToFloat32(), armnn::CpuRef, armnn::GetInputTensorDataBFloat16(), TensorInfo::GetNumElements(), armnn::GetOutputTensorDataFloat(), armnn::GetTensorInfo(), BaseWorkload< QueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
 {
     ARMNN_SCOPED_PROFILING_EVENT(Compute::CpuRef, "RefConvertBf16ToFp32Workload_Execute");
     const BFloat16* const input = GetInputTensorDataBFloat16(0, m_Data);
     float* const output = GetOutputTensorDataFloat(0, m_Data);
     unsigned int numElements = GetTensorInfo(m_Data.m_Inputs[0]).GetNumElements();
     armnnUtils::FloatingPointConverter::ConvertBFloat16ToFloat32(input, numElements, output);
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefConvertBf16ToFp32Workload.hpp
src/backends/reference/workloads/RefConvertBf16ToFp32Workload.cpp