ArmNN: QLstmLayer Class Reference
QLstmLayer Class Reference
This layer represents a QLstm operation.
#include <QLstmLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the QLstm type.
QLstmLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of QLstmLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
void Accept (ILayerVisitor &visitor) const override
Apply a visitor to this layer.
Public Member Functions inherited from LayerWithParameters< QLstmDescriptor >
const QLstmDescriptor & GetParameters () const
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
Public Attributes
QLstmBasicParameters m_BasicParameters
QLstmOptCifgParameters m_CifgParameters
QLstmOptProjectionParameters m_ProjectionParameters
QLstmOptPeepholeParameters m_PeepholeParameters
QLstmOptLayerNormParameters m_LayerNormParameters
Protected Member Functions
QLstmLayer (const QLstmDescriptor &param, const char *name)
Constructor to create a QLstmLayer.
~QLstmLayer ()=default
Default destructor.
Layer::ConstantTensors GetConstantTensorsByRef () override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from LayerWithParameters< QLstmDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const QLstmDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< QLstmDescriptor >
using DescriptorType = QLstmDescriptor
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< QLstmDescriptor >
QLstmDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a QLstm operation.
Definition at line 79 of file QLstmLayer.hpp.
Constructor & Destructor Documentation
QLstmLayer()
QLstmLayer (const QLstmDescriptor & param, const char * name) protected
Constructor to create a QLstmLayer.
Parameters
[in] name Optional name for the layer.
Definition at line 17 of file QLstmLayer.cpp.
References armnn::QLstm.
         : LayerWithParameters(3, 3, LayerType::QLstm, param, name)
 {
 }
~QLstmLayer()
~QLstmLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Apply a visitor to this layer.
Implements IConnectableLayer.
Definition at line 303 of file QLstmLayer.cpp.
References Layer::GetName(), LayerWithParameters< QLstmDescriptor >::GetParameters(), QLstmLayer::m_BasicParameters, QLstmBasicParameters::m_CellBias, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, QLstmOptLayerNormParameters::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, QLstmOptPeepholeParameters::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, QLstmOptPeepholeParameters::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, QLstmOptPeepholeParameters::m_CellToOutputWeights, QLstmLayer::m_CifgParameters, QLstmBasicParameters::m_ForgetGateBias, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, QLstmOptLayerNormParameters::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, QLstmOptCifgParameters::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, QLstmOptLayerNormParameters::m_InputLayerNormWeights, QLstmBasicParameters::m_InputToCellWeights, LstmInputParams::m_InputToCellWeights, QLstmBasicParameters::m_InputToForgetWeights, LstmInputParams::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, QLstmOptCifgParameters::m_InputToInputWeights, QLstmBasicParameters::m_InputToOutputWeights, LstmInputParams::m_InputToOutputWeights, QLstmLayer::m_LayerNormParameters, QLstmBasicParameters::m_OutputGateBias, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, QLstmOptLayerNormParameters::m_OutputLayerNormWeights, QLstmLayer::m_PeepholeParameters, QLstmOptProjectionParameters::m_ProjectionBias, LstmInputParams::m_ProjectionBias, QLstmLayer::m_ProjectionParameters, QLstmOptProjectionParameters::m_ProjectionWeights, LstmInputParams::m_ProjectionWeights, QLstmBasicParameters::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToCellWeights, QLstmBasicParameters::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, QLstmOptCifgParameters::m_RecurrentToInputWeights, QLstmBasicParameters::m_RecurrentToOutputWeights, LstmInputParams::m_RecurrentToOutputWeights, and ILayerVisitor::VisitQLstmLayer().
 {
     LstmInputParams inputParams;
     ConstTensor inputToInputWeightsTensor;
     if (m_CifgParameters.m_InputToInputWeights != nullptr)
     {
         ConstTensor inputToInputWeightsTensorCopy(m_CifgParameters.m_InputToInputWeights->GetTensorInfo(),
                                                   m_CifgParameters.m_InputToInputWeights->Map(true));
         inputToInputWeightsTensor = inputToInputWeightsTensorCopy;
         inputParams.m_InputToInputWeights = &inputToInputWeightsTensor;
     }
     ConstTensor inputToForgetWeightsTensor;
     if (m_BasicParameters.m_InputToForgetWeights != nullptr)
     {
         ConstTensor inputToForgetWeightsTensorCopy(m_BasicParameters.m_InputToForgetWeights->GetTensorInfo(),
                                                    m_BasicParameters.m_InputToForgetWeights->Map(true));
         inputToForgetWeightsTensor = inputToForgetWeightsTensorCopy;
         inputParams.m_InputToForgetWeights = &inputToForgetWeightsTensor;
     }
     ConstTensor inputToCellWeightsTensor;
     if (m_BasicParameters.m_InputToCellWeights != nullptr)
     {
         ConstTensor inputToCellWeightsTensorCopy(m_BasicParameters.m_InputToCellWeights->GetTensorInfo(),
                                                  m_BasicParameters.m_InputToCellWeights->Map(true));
         inputToCellWeightsTensor = inputToCellWeightsTensorCopy;
         inputParams.m_InputToCellWeights = &inputToCellWeightsTensor;
     }
     ConstTensor inputToOutputWeightsTensor;
     if (m_BasicParameters.m_InputToOutputWeights != nullptr)
     {
         ConstTensor inputToOutputWeightsTensorCopy(m_BasicParameters.m_InputToOutputWeights->GetTensorInfo(),
                                                    m_BasicParameters.m_InputToOutputWeights->Map(true));
         inputToOutputWeightsTensor = inputToOutputWeightsTensorCopy;
         inputParams.m_InputToOutputWeights = &inputToOutputWeightsTensor;
     }
     ConstTensor recurrentToInputWeightsTensor;
     if (m_CifgParameters.m_RecurrentToInputWeights != nullptr)
     {
         ConstTensor recurrentToInputWeightsTensorCopy(
                 m_CifgParameters.m_RecurrentToInputWeights->GetTensorInfo(),
                 m_CifgParameters.m_RecurrentToInputWeights->Map(true));
         recurrentToInputWeightsTensor = recurrentToInputWeightsTensorCopy;
         inputParams.m_RecurrentToInputWeights = &recurrentToInputWeightsTensor;
     }
     ConstTensor recurrentToForgetWeightsTensor;
     if (m_BasicParameters.m_RecurrentToForgetWeights != nullptr)
     {
         ConstTensor recurrentToForgetWeightsTensorCopy(
                 m_BasicParameters.m_RecurrentToForgetWeights->GetTensorInfo(),
                 m_BasicParameters.m_RecurrentToForgetWeights->Map(true));
         recurrentToForgetWeightsTensor = recurrentToForgetWeightsTensorCopy;
         inputParams.m_RecurrentToForgetWeights = &recurrentToForgetWeightsTensor;
     }
     ConstTensor recurrentToCellWeightsTensor;
     if (m_BasicParameters.m_RecurrentToCellWeights != nullptr)
     {
         ConstTensor recurrentToCellWeightsTensorCopy(
                 m_BasicParameters.m_RecurrentToCellWeights->GetTensorInfo(),
                 m_BasicParameters.m_RecurrentToCellWeights->Map(true));
         recurrentToCellWeightsTensor = recurrentToCellWeightsTensorCopy;
         inputParams.m_RecurrentToCellWeights = &recurrentToCellWeightsTensor;
     }
     ConstTensor recurrentToOutputWeightsTensor;
     if (m_BasicParameters.m_RecurrentToOutputWeights != nullptr)
     {
         ConstTensor recurrentToOutputWeightsTensorCopy(
                 m_BasicParameters.m_RecurrentToOutputWeights->GetTensorInfo(),
                 m_BasicParameters.m_RecurrentToOutputWeights->Map(true));
         recurrentToOutputWeightsTensor = recurrentToOutputWeightsTensorCopy;
         inputParams.m_RecurrentToOutputWeights = &recurrentToOutputWeightsTensor;
     }
     ConstTensor cellToInputWeightsTensor;
     if (m_PeepholeParameters.m_CellToInputWeights != nullptr)
     {
         ConstTensor cellToInputWeightsTensorCopy(m_PeepholeParameters.m_CellToInputWeights->GetTensorInfo(),
                                                  m_PeepholeParameters.m_CellToInputWeights->Map(true));
         cellToInputWeightsTensor = cellToInputWeightsTensorCopy;
         inputParams.m_CellToInputWeights = &cellToInputWeightsTensor;
     }
     ConstTensor cellToForgetWeightsTensor;
     if (m_PeepholeParameters.m_CellToForgetWeights != nullptr)
     {
         ConstTensor cellToForgetWeightsTensorCopy(m_PeepholeParameters.m_CellToForgetWeights->GetTensorInfo(),
                                                   m_PeepholeParameters.m_CellToForgetWeights->Map(true));
         cellToForgetWeightsTensor = cellToForgetWeightsTensorCopy;
         inputParams.m_CellToForgetWeights = &cellToForgetWeightsTensor;
     }
     ConstTensor cellToOutputWeightsTensor;
     if (m_PeepholeParameters.m_CellToOutputWeights != nullptr)
     {
         ConstTensor cellToOutputWeightsTensorCopy(m_PeepholeParameters.m_CellToOutputWeights->GetTensorInfo(),
                                                   m_PeepholeParameters.m_CellToOutputWeights->Map(true));
         cellToOutputWeightsTensor = cellToOutputWeightsTensorCopy;
         inputParams.m_CellToOutputWeights = &cellToOutputWeightsTensor;
     }
     ConstTensor inputGateBiasTensor;
     if (m_CifgParameters.m_InputGateBias != nullptr)
     {
         ConstTensor inputGateBiasTensorCopy(m_CifgParameters.m_InputGateBias->GetTensorInfo(),
                                             m_CifgParameters.m_InputGateBias->Map(true));
         inputGateBiasTensor = inputGateBiasTensorCopy;
         inputParams.m_InputGateBias = &inputGateBiasTensor;
     }
     ConstTensor forgetGateBiasTensor;
     if (m_BasicParameters.m_ForgetGateBias != nullptr)
     {
         ConstTensor forgetGateBiasTensorCopy(m_BasicParameters.m_ForgetGateBias->GetTensorInfo(),
                                              m_BasicParameters.m_ForgetGateBias->Map(true));
         forgetGateBiasTensor = forgetGateBiasTensorCopy;
         inputParams.m_ForgetGateBias = &forgetGateBiasTensor;
     }
     ConstTensor cellBiasTensor;
     if (m_BasicParameters.m_CellBias != nullptr)
     {
         ConstTensor cellBiasTensorCopy(m_BasicParameters.m_CellBias->GetTensorInfo(),
                                        m_BasicParameters.m_CellBias->Map(true));
         cellBiasTensor = cellBiasTensorCopy;
         inputParams.m_CellBias = &cellBiasTensor;
     }
     ConstTensor outputGateBias;
     if (m_BasicParameters.m_OutputGateBias != nullptr)
     {
         ConstTensor outputGateBiasCopy(m_BasicParameters.m_OutputGateBias->GetTensorInfo(),
                                        m_BasicParameters.m_OutputGateBias->Map(true));
         outputGateBias = outputGateBiasCopy;
         inputParams.m_OutputGateBias = &outputGateBias;
     }
     ConstTensor projectionWeightsTensor;
     if (m_ProjectionParameters.m_ProjectionWeights != nullptr)
     {
         ConstTensor projectionWeightsTensorCopy(m_ProjectionParameters.m_ProjectionWeights->GetTensorInfo(),
                                                 m_ProjectionParameters.m_ProjectionWeights->Map(true));
         projectionWeightsTensor = projectionWeightsTensorCopy;
         inputParams.m_ProjectionWeights = &projectionWeightsTensor;
     }
     ConstTensor projectionBiasTensor;
     if (m_ProjectionParameters.m_ProjectionBias != nullptr)
     {
         ConstTensor projectionBiasTensorCopy(m_ProjectionParameters.m_ProjectionBias->GetTensorInfo(),
                                              m_ProjectionParameters.m_ProjectionBias->Map(true));
         projectionBiasTensor = projectionBiasTensorCopy;
         inputParams.m_ProjectionBias = &projectionBiasTensor;
     }
     ConstTensor inputLayerNormTensor;
     if (m_LayerNormParameters.m_InputLayerNormWeights != nullptr)
     {
         ConstTensor inputLayerNormTensorCopy(m_LayerNormParameters.m_InputLayerNormWeights->GetTensorInfo(),
                                              m_LayerNormParameters.m_InputLayerNormWeights->Map(true));
         inputLayerNormTensor = inputLayerNormTensorCopy;
         inputParams.m_InputLayerNormWeights = &inputLayerNormTensor;
     }
     ConstTensor forgetLayerNormTensor;
     if (m_LayerNormParameters.m_ForgetLayerNormWeights != nullptr)
     {
         ConstTensor forgetLayerNormTensorCopy(m_LayerNormParameters.m_ForgetLayerNormWeights->GetTensorInfo(),
                                               m_LayerNormParameters.m_ForgetLayerNormWeights->Map(true));
         forgetLayerNormTensor = forgetLayerNormTensorCopy;
         inputParams.m_ForgetLayerNormWeights = &forgetLayerNormTensor;
     }
     ConstTensor cellLayerNormTensor;
     if (m_LayerNormParameters.m_CellLayerNormWeights != nullptr)
     {
         ConstTensor cellLayerNormTensorCopy(m_LayerNormParameters.m_CellLayerNormWeights->GetTensorInfo(),
                                             m_LayerNormParameters.m_CellLayerNormWeights->Map(true));
         cellLayerNormTensor = cellLayerNormTensorCopy;
         inputParams.m_CellLayerNormWeights = &cellLayerNormTensor;
     }
     ConstTensor outputLayerNormTensor;
     if (m_LayerNormParameters.m_OutputLayerNormWeights != nullptr)
     {
         ConstTensor outputLayerNormTensorCopy(m_LayerNormParameters.m_OutputLayerNormWeights->GetTensorInfo(),
                                               m_LayerNormParameters.m_OutputLayerNormWeights->Map(true));
         outputLayerNormTensor = outputLayerNormTensorCopy;
         inputParams.m_OutputLayerNormWeights = &outputLayerNormTensor;
     }
     visitor.VisitQLstmLayer(this, GetParameters(), inputParams, GetName());
 }
Clone()
QLstmLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 79 of file QLstmLayer.cpp.
References Layer::GetName(), QLstmLayer::m_BasicParameters, QLstmBasicParameters::m_CellBias, QLstmOptLayerNormParameters::m_CellLayerNormWeights, QLstmOptPeepholeParameters::m_CellToForgetWeights, QLstmOptPeepholeParameters::m_CellToInputWeights, QLstmOptPeepholeParameters::m_CellToOutputWeights, QLstmLayer::m_CifgParameters, QLstmBasicParameters::m_ForgetGateBias, QLstmOptLayerNormParameters::m_ForgetLayerNormWeights, QLstmOptCifgParameters::m_InputGateBias, QLstmOptLayerNormParameters::m_InputLayerNormWeights, QLstmBasicParameters::m_InputToCellWeights, QLstmBasicParameters::m_InputToForgetWeights, QLstmOptCifgParameters::m_InputToInputWeights, QLstmBasicParameters::m_InputToOutputWeights, QLstmLayer::m_LayerNormParameters, QLstmBasicParameters::m_OutputGateBias, QLstmOptLayerNormParameters::m_OutputLayerNormWeights, LayerWithParameters< QLstmDescriptor >::m_Param, QLstmLayer::m_PeepholeParameters, QLstmOptProjectionParameters::m_ProjectionBias, QLstmLayer::m_ProjectionParameters, QLstmOptProjectionParameters::m_ProjectionWeights, QLstmBasicParameters::m_RecurrentToCellWeights, QLstmBasicParameters::m_RecurrentToForgetWeights, QLstmOptCifgParameters::m_RecurrentToInputWeights, and QLstmBasicParameters::m_RecurrentToOutputWeights.
 {
     auto layer = CloneBase<QLstmLayer>(graph, m_Param, GetName());
     layer->m_BasicParameters.m_InputToForgetWeights = m_BasicParameters.m_InputToForgetWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_InputToForgetWeights) : nullptr;
     layer->m_BasicParameters.m_InputToCellWeights = m_BasicParameters.m_InputToCellWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_InputToCellWeights) : nullptr;
     layer->m_BasicParameters.m_InputToOutputWeights = m_BasicParameters.m_InputToOutputWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_InputToOutputWeights) : nullptr;
     layer->m_BasicParameters.m_RecurrentToForgetWeights = m_BasicParameters.m_RecurrentToForgetWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_RecurrentToForgetWeights) : nullptr;
     layer->m_BasicParameters.m_RecurrentToCellWeights = m_BasicParameters.m_RecurrentToCellWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_RecurrentToCellWeights) : nullptr;
     layer->m_BasicParameters.m_RecurrentToOutputWeights = m_BasicParameters.m_RecurrentToOutputWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_RecurrentToOutputWeights) : nullptr;
     layer->m_BasicParameters.m_ForgetGateBias = m_BasicParameters.m_ForgetGateBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_ForgetGateBias) : nullptr;
     layer->m_BasicParameters.m_CellBias = m_BasicParameters.m_CellBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_CellBias) : nullptr;
     layer->m_BasicParameters.m_OutputGateBias = m_BasicParameters.m_OutputGateBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_BasicParameters.m_OutputGateBias) : nullptr;
     if (!m_Param.m_CifgEnabled)
     {
         layer->m_CifgParameters.m_InputToInputWeights = m_CifgParameters.m_InputToInputWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_CifgParameters.m_InputToInputWeights) : nullptr;
         layer->m_CifgParameters.m_RecurrentToInputWeights = m_CifgParameters.m_RecurrentToInputWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_CifgParameters.m_RecurrentToInputWeights) : nullptr;
         layer->m_CifgParameters.m_InputGateBias = m_CifgParameters.m_InputGateBias ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_CifgParameters.m_InputGateBias) : nullptr;
     }
     if (m_Param.m_ProjectionEnabled)
     {
         layer->m_ProjectionParameters.m_ProjectionWeights = m_ProjectionParameters.m_ProjectionWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_ProjectionParameters.m_ProjectionWeights) : nullptr;
         layer->m_ProjectionParameters.m_ProjectionBias = m_ProjectionParameters.m_ProjectionBias ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_ProjectionParameters.m_ProjectionBias) : nullptr;
     }
     if (m_Param.m_PeepholeEnabled)
     {
         if (!m_Param.m_CifgEnabled) {
             layer->m_PeepholeParameters.m_CellToInputWeights = m_PeepholeParameters.m_CellToInputWeights ?
                     std::make_unique<ScopedCpuTensorHandle>(*m_PeepholeParameters.m_CellToInputWeights) : nullptr;
         }
         layer->m_PeepholeParameters.m_CellToForgetWeights = m_PeepholeParameters.m_CellToForgetWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_PeepholeParameters.m_CellToForgetWeights) : nullptr;
         layer->m_PeepholeParameters.m_CellToOutputWeights = m_PeepholeParameters.m_CellToOutputWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_PeepholeParameters.m_CellToOutputWeights) : nullptr;
     }
     if (m_Param.m_LayerNormEnabled)
     {
         if (!m_Param.m_CifgEnabled) {
             layer->m_LayerNormParameters.m_InputLayerNormWeights = m_LayerNormParameters.m_InputLayerNormWeights ?
                     std::make_unique<ScopedCpuTensorHandle>(*m_LayerNormParameters.m_InputLayerNormWeights) : nullptr;
         }
         layer->m_LayerNormParameters.m_ForgetLayerNormWeights = m_LayerNormParameters.m_ForgetLayerNormWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_LayerNormParameters.m_ForgetLayerNormWeights) : nullptr;
         layer->m_LayerNormParameters.m_CellLayerNormWeights = m_LayerNormParameters.m_CellLayerNormWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_LayerNormParameters.m_CellLayerNormWeights) : nullptr;
         layer->m_LayerNormParameters.m_OutputLayerNormWeights = m_LayerNormParameters.m_OutputLayerNormWeights ?
                 std::make_unique<ScopedCpuTensorHandle>(*m_LayerNormParameters.m_OutputLayerNormWeights) : nullptr;
     }
     return std::move(layer);
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the QLstm type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 22 of file QLstmLayer.cpp.
References IWorkloadFactory::CreateQLstm(), QLstmLayer::m_BasicParameters, QLstmBasicParameters::m_CellBias, QLstmQueueDescriptor::m_CellBias, QLstmOptLayerNormParameters::m_CellLayerNormWeights, QLstmQueueDescriptor::m_CellLayerNormWeights, QLstmOptPeepholeParameters::m_CellToForgetWeights, QLstmQueueDescriptor::m_CellToForgetWeights, QLstmOptPeepholeParameters::m_CellToInputWeights, QLstmQueueDescriptor::m_CellToInputWeights, QLstmOptPeepholeParameters::m_CellToOutputWeights, QLstmQueueDescriptor::m_CellToOutputWeights, QLstmDescriptor::m_CifgEnabled, QLstmLayer::m_CifgParameters, QLstmBasicParameters::m_ForgetGateBias, QLstmQueueDescriptor::m_ForgetGateBias, QLstmOptLayerNormParameters::m_ForgetLayerNormWeights, QLstmQueueDescriptor::m_ForgetLayerNormWeights, QLstmOptCifgParameters::m_InputGateBias, QLstmQueueDescriptor::m_InputGateBias, QLstmOptLayerNormParameters::m_InputLayerNormWeights, QLstmQueueDescriptor::m_InputLayerNormWeights, QLstmBasicParameters::m_InputToCellWeights, QLstmQueueDescriptor::m_InputToCellWeights, QLstmBasicParameters::m_InputToForgetWeights, QLstmQueueDescriptor::m_InputToForgetWeights, QLstmOptCifgParameters::m_InputToInputWeights, QLstmQueueDescriptor::m_InputToInputWeights, QLstmBasicParameters::m_InputToOutputWeights, QLstmQueueDescriptor::m_InputToOutputWeights, QLstmDescriptor::m_LayerNormEnabled, QLstmLayer::m_LayerNormParameters, QLstmBasicParameters::m_OutputGateBias, QLstmQueueDescriptor::m_OutputGateBias, QLstmOptLayerNormParameters::m_OutputLayerNormWeights, QLstmQueueDescriptor::m_OutputLayerNormWeights, LayerWithParameters< QLstmDescriptor >::m_Param, QLstmDescriptor::m_PeepholeEnabled, QLstmLayer::m_PeepholeParameters, QLstmOptProjectionParameters::m_ProjectionBias, QLstmQueueDescriptor::m_ProjectionBias, QLstmDescriptor::m_ProjectionEnabled, QLstmLayer::m_ProjectionParameters, QLstmOptProjectionParameters::m_ProjectionWeights, QLstmQueueDescriptor::m_ProjectionWeights, QLstmBasicParameters::m_RecurrentToCellWeights, QLstmQueueDescriptor::m_RecurrentToCellWeights, QLstmBasicParameters::m_RecurrentToForgetWeights, QLstmQueueDescriptor::m_RecurrentToForgetWeights, QLstmOptCifgParameters::m_RecurrentToInputWeights, QLstmQueueDescriptor::m_RecurrentToInputWeights, QLstmBasicParameters::m_RecurrentToOutputWeights, QLstmQueueDescriptor::m_RecurrentToOutputWeights, and LayerWithParameters< QLstmDescriptor >::PrepInfoAndDesc().
 {
     QLstmQueueDescriptor descriptor;
     // Basic parameters
     descriptor.m_InputToForgetWeights = m_BasicParameters.m_InputToForgetWeights.get();
     descriptor.m_InputToCellWeights = m_BasicParameters.m_InputToCellWeights.get();
     descriptor.m_InputToOutputWeights = m_BasicParameters.m_InputToOutputWeights.get();
     descriptor.m_RecurrentToForgetWeights = m_BasicParameters.m_RecurrentToForgetWeights.get();
     descriptor.m_RecurrentToCellWeights = m_BasicParameters.m_RecurrentToCellWeights.get();
     descriptor.m_RecurrentToOutputWeights = m_BasicParameters.m_RecurrentToOutputWeights.get();
     descriptor.m_ForgetGateBias = m_BasicParameters.m_ForgetGateBias.get();
     descriptor.m_CellBias = m_BasicParameters.m_CellBias.get();
     descriptor.m_OutputGateBias = m_BasicParameters.m_OutputGateBias.get();
     // CIFG parameters
     if (!m_Param.m_CifgEnabled)
     {
         descriptor.m_InputToInputWeights     = m_CifgParameters.m_InputToInputWeights.get();
         descriptor.m_RecurrentToInputWeights = m_CifgParameters.m_RecurrentToInputWeights.get();
         descriptor.m_InputGateBias           = m_CifgParameters.m_InputGateBias.get();
     }
     // Projection parameters
     if (m_Param.m_ProjectionEnabled)
     {
         descriptor.m_ProjectionWeights = m_ProjectionParameters.m_ProjectionWeights.get();
         descriptor.m_ProjectionBias    = m_ProjectionParameters.m_ProjectionBias.get();
     }
     // Peephole parameters
     if (m_Param.m_PeepholeEnabled)
     {
         if (!m_Param.m_CifgEnabled)
         {
             descriptor.m_CellToInputWeights = m_PeepholeParameters.m_CellToInputWeights.get();
         }
         descriptor.m_CellToForgetWeights = m_PeepholeParameters.m_CellToForgetWeights.get();
         descriptor.m_CellToOutputWeights = m_PeepholeParameters.m_CellToOutputWeights.get();
     }
     // Layer normalisation parameters
     if(m_Param.m_LayerNormEnabled)
     {
         if (!m_Param.m_CifgEnabled)
         {
             descriptor.m_InputLayerNormWeights = m_LayerNormParameters.m_InputLayerNormWeights.get();
         }
         descriptor.m_ForgetLayerNormWeights = m_LayerNormParameters.m_ForgetLayerNormWeights.get();
         descriptor.m_CellLayerNormWeights   = m_LayerNormParameters.m_CellLayerNormWeights.get();
         descriptor.m_OutputLayerNormWeights = m_LayerNormParameters.m_OutputLayerNormWeights.get();
     }
     return factory.CreateQLstm(descriptor, PrepInfoAndDesc(descriptor));
 }
GetConstantTensorsByRef()
Layer::ConstantTensors GetConstantTensorsByRef () override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 270 of file QLstmLayer.cpp.
References QLstmLayer::m_BasicParameters, QLstmBasicParameters::m_CellBias, QLstmOptLayerNormParameters::m_CellLayerNormWeights, QLstmOptPeepholeParameters::m_CellToForgetWeights, QLstmOptPeepholeParameters::m_CellToInputWeights, QLstmOptPeepholeParameters::m_CellToOutputWeights, QLstmLayer::m_CifgParameters, QLstmBasicParameters::m_ForgetGateBias, QLstmOptLayerNormParameters::m_ForgetLayerNormWeights, QLstmOptCifgParameters::m_InputGateBias, QLstmOptLayerNormParameters::m_InputLayerNormWeights, QLstmBasicParameters::m_InputToCellWeights, QLstmBasicParameters::m_InputToForgetWeights, QLstmOptCifgParameters::m_InputToInputWeights, QLstmBasicParameters::m_InputToOutputWeights, QLstmLayer::m_LayerNormParameters, QLstmBasicParameters::m_OutputGateBias, QLstmOptLayerNormParameters::m_OutputLayerNormWeights, QLstmLayer::m_PeepholeParameters, QLstmOptProjectionParameters::m_ProjectionBias, QLstmLayer::m_ProjectionParameters, QLstmOptProjectionParameters::m_ProjectionWeights, QLstmBasicParameters::m_RecurrentToCellWeights, QLstmBasicParameters::m_RecurrentToForgetWeights, QLstmOptCifgParameters::m_RecurrentToInputWeights, and QLstmBasicParameters::m_RecurrentToOutputWeights.
 {
     return {m_BasicParameters.m_InputToForgetWeights,
             m_BasicParameters.m_InputToCellWeights,
             m_BasicParameters.m_InputToOutputWeights,
             m_BasicParameters.m_RecurrentToForgetWeights,
             m_BasicParameters.m_RecurrentToCellWeights,
             m_BasicParameters.m_RecurrentToOutputWeights,
             m_BasicParameters.m_ForgetGateBias,
             m_BasicParameters.m_CellBias,
             m_BasicParameters.m_OutputGateBias,
             // Cifg parameters
             m_CifgParameters.m_InputToInputWeights,
             m_CifgParameters.m_RecurrentToInputWeights,
             m_CifgParameters.m_InputGateBias,
             // Projection parameters
             m_ProjectionParameters.m_ProjectionWeights,
             m_ProjectionParameters.m_ProjectionBias,
             // Peephole parameters
             m_PeepholeParameters.m_CellToInputWeights,
             m_PeepholeParameters.m_CellToForgetWeights,
             m_PeepholeParameters.m_CellToOutputWeights,
             // Layer normalisation parameters
             m_LayerNormParameters.m_InputLayerNormWeights,
             m_LayerNormParameters.m_ForgetLayerNormWeights,
             m_LayerNormParameters.m_CellLayerNormWeights,
             m_LayerNormParameters.m_OutputLayerNormWeights};
 }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 151 of file QLstmLayer.cpp.
References ARMNN_ASSERT.
Referenced by QLstmInferOutputShapeImpl(), and QLstmLayer::ValidateTensorShapesFromInputs().
 {
     ARMNN_ASSERT(inputShapes.size() == 3);
     // Get input values for validation
     unsigned int batchSize = inputShapes[0][0];
     unsigned int outputSize = inputShapes[1][1];
     unsigned int numUnits = inputShapes[2][1];
     std::vector<TensorShape> outShapes;
     outShapes.push_back(TensorShape({ batchSize, outputSize })); // outputStateOut
     outShapes.push_back(TensorShape({ batchSize, numUnits })); // cellStateOut
     outShapes.push_back(TensorShape({ batchSize, outputSize })); // output
     return outShapes;
 }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of QLstmLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 168 of file QLstmLayer.cpp.
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), armnn::GetTensorInfo(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), QLstmLayer::InferOutputShapes(), QLstmLayer::m_BasicParameters, QLstmBasicParameters::m_CellBias, QLstmOptPeepholeParameters::m_CellToForgetWeights, QLstmOptPeepholeParameters::m_CellToInputWeights, QLstmOptPeepholeParameters::m_CellToOutputWeights, QLstmDescriptor::m_CifgEnabled, QLstmLayer::m_CifgParameters, QLstmBasicParameters::m_ForgetGateBias, QLstmOptCifgParameters::m_InputGateBias, QLstmBasicParameters::m_InputToCellWeights, QLstmBasicParameters::m_InputToForgetWeights, QLstmOptCifgParameters::m_InputToInputWeights, QLstmBasicParameters::m_InputToOutputWeights, QLstmBasicParameters::m_OutputGateBias, LayerWithParameters< QLstmDescriptor >::m_Param, QLstmDescriptor::m_PeepholeEnabled, QLstmLayer::m_PeepholeParameters, QLstmDescriptor::m_ProjectionEnabled, QLstmLayer::m_ProjectionParameters, QLstmOptProjectionParameters::m_ProjectionWeights, QLstmBasicParameters::m_RecurrentToCellWeights, QLstmBasicParameters::m_RecurrentToForgetWeights, QLstmOptCifgParameters::m_RecurrentToInputWeights, QLstmBasicParameters::m_RecurrentToOutputWeights, Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
 {
     VerifyLayerConnections(3, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     auto inferredShapes = InferOutputShapes(
     {
         GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape(), // input
         GetInputSlot(1).GetConnection()->GetTensorInfo().GetShape(), // previousOutputIn
         GetInputSlot(2).GetConnection()->GetTensorInfo().GetShape()  // previousCellStateIn
     });
     ARMNN_ASSERT(inferredShapes.size() == 3);
     // Check if the weights are nullptr for basic params
     ARMNN_ASSERT_MSG(m_BasicParameters.m_InputToForgetWeights != nullptr,
             "QLstmLayer: m_BasicParameters.m_InputToForgetWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_InputToCellWeights != nullptr,
             "QLstmLayer: m_BasicParameters.m_InputToCellWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_InputToOutputWeights != nullptr,
             "QLstmLayer: m_BasicParameters.m_InputToOutputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_RecurrentToForgetWeights != nullptr,
             "QLstmLayer: m_BasicParameters.m_RecurrentToForgetWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_RecurrentToCellWeights != nullptr,
             "QLstmLayer: m_BasicParameters.m_RecurrentToCellWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_RecurrentToOutputWeights != nullptr,
             "QLstmLayer: m_BasicParameters.m_RecurrentToOutputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_ForgetGateBias != nullptr,
             "QLstmLayer: m_BasicParameters.m_ForgetGateBias should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_CellBias != nullptr,
             "QLstmLayer: m_BasicParameters.m_CellBias should not be null.");
     ARMNN_ASSERT_MSG(m_BasicParameters.m_OutputGateBias != nullptr,
             "QLstmLayer: m_BasicParameters.m_OutputGateBias should not be null.");
     if (!m_Param.m_CifgEnabled)
     {
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputToInputWeights != nullptr,
                 "QLstmLayer: m_CifgParameters.m_InputToInputWeights should not be null.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_RecurrentToInputWeights != nullptr,
                 "QLstmLayer: m_CifgParameters.m_RecurrentToInputWeights should not be null.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputGateBias != nullptr,
                 "QLstmLayer: m_CifgParameters.m_InputGateBias should not be null.");
         ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "QLstmLayer");
     }
     else
     {
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputToInputWeights == nullptr,
                 "QLstmLayer: m_CifgParameters.m_InputToInputWeights should not have a value when CIFG is enabled.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_RecurrentToInputWeights == nullptr,
                 "QLstmLayer: m_CifgParameters.m_RecurrentToInputWeights should "
                              "not have a value when CIFG is enabled.");
         ARMNN_ASSERT_MSG(m_CifgParameters.m_InputGateBias == nullptr,
                 "QLstmLayer: m_CifgParameters.m_InputGateBias should not have a value when CIFG is enabled.");
         ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "QLstmLayer");
     }
     if (m_Param.m_ProjectionEnabled)
     {
         ARMNN_ASSERT_MSG(m_ProjectionParameters.m_ProjectionWeights != nullptr,
                          "QLstmLayer: m_ProjectionParameters.m_ProjectionWeights should not be null.");
     }
     if (m_Param.m_PeepholeEnabled)
     {
         if (!m_Param.m_CifgEnabled) {
             ARMNN_ASSERT_MSG(m_PeepholeParameters.m_CellToInputWeights != nullptr,
                     "QLstmLayer: m_PeepholeParameters.m_CellToInputWeights should not be null "
                     "when Peephole is enabled and CIFG is disabled.");
         }
         ARMNN_ASSERT_MSG(m_PeepholeParameters.m_CellToForgetWeights != nullptr,
                          "QLstmLayer: m_PeepholeParameters.m_CellToForgetWeights should not be null.");
         ARMNN_ASSERT_MSG(m_PeepholeParameters.m_CellToOutputWeights != nullptr,
                          "QLstmLayer: m_PeepholeParameters.m_CellToOutputWeights should not be null.");
     }
     ValidateAndCopyShape(
             GetOutputSlot(1).GetTensorInfo().GetShape(), inferredShapes[1], m_ShapeInferenceMethod, "QLstmLayer", 1);
     ValidateAndCopyShape(
             GetOutputSlot(2).GetTensorInfo().GetShape(), inferredShapes[2], m_ShapeInferenceMethod, "QLstmLayer", 2);
     if (m_Param.m_LayerNormEnabled)
     {
         if(!m_Param.m_CifgEnabled)
         {
             ARMNN_ASSERT_MSG(m_LayerNormParameters.m_InputLayerNormWeights != nullptr,
                              "QLstmLayer: m_LayerNormParameters.m_InputLayerNormWeights should not be null.");
         }
         ARMNN_ASSERT_MSG(m_LayerNormParameters.m_ForgetLayerNormWeights != nullptr,
                          "QLstmLayer: m_LayerNormParameters.m_ForgetLayerNormWeights should not be null.");
         ARMNN_ASSERT_MSG(m_LayerNormParameters.m_CellLayerNormWeights != nullptr,
                          "QLstmLayer: m_LayerNormParameters.m_CellLayerNormWeights should not be null.");
         ARMNN_ASSERT_MSG(m_LayerNormParameters.m_OutputLayerNormWeights != nullptr,
                          "QLstmLayer: m_LayerNormParameters.m_UutputLayerNormWeights should not be null.");
     }
 }
Member Data Documentation
m_BasicParameters
QLstmBasicParameters m_BasicParameters
Definition at line 83 of file QLstmLayer.hpp.
Referenced by QLstmLayer::Accept(), Network::AddQLstmLayer(), QLstmLayer::Clone(), QLstmLayer::CreateWorkload(), QLstmLayer::GetConstantTensorsByRef(), and QLstmLayer::ValidateTensorShapesFromInputs().
m_CifgParameters
QLstmOptCifgParameters m_CifgParameters
Definition at line 84 of file QLstmLayer.hpp.
Referenced by QLstmLayer::Accept(), QLstmLayer::Clone(), QLstmLayer::CreateWorkload(), QLstmLayer::GetConstantTensorsByRef(), and QLstmLayer::ValidateTensorShapesFromInputs().
m_LayerNormParameters
QLstmOptLayerNormParameters m_LayerNormParameters
Definition at line 87 of file QLstmLayer.hpp.
Referenced by QLstmLayer::Accept(), QLstmLayer::Clone(), QLstmLayer::CreateWorkload(), and QLstmLayer::GetConstantTensorsByRef().
m_PeepholeParameters
QLstmOptPeepholeParameters m_PeepholeParameters
Definition at line 86 of file QLstmLayer.hpp.
Referenced by QLstmLayer::Accept(), QLstmLayer::Clone(), QLstmLayer::CreateWorkload(), QLstmLayer::GetConstantTensorsByRef(), and QLstmLayer::ValidateTensorShapesFromInputs().
m_ProjectionParameters
QLstmOptProjectionParameters m_ProjectionParameters
Definition at line 85 of file QLstmLayer.hpp.
Referenced by QLstmLayer::Accept(), QLstmLayer::Clone(), QLstmLayer::CreateWorkload(), QLstmLayer::GetConstantTensorsByRef(), and QLstmLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/QLstmLayer.hpp
src/armnn/layers/QLstmLayer.cpp