ArmNN: Encoder< IType > Class Template Reference
Encoder< IType > Class Template Reference abstract
#include <BaseIterator.hpp>
Public Member Functions
Encoder ()
virtual ~Encoder ()
virtual void Reset (void *)=0
virtual void Set (IType right)=0
virtual IType Get () const =0
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
virtual BaseIterator & SetIndex (unsigned int index, unsigned int axisIndex=0)=0
virtual BaseIterator & operator++ ()=0
virtual BaseIterator & operator+= (const unsigned int increment)=0
virtual BaseIterator & operator-= (const unsigned int increment)=0
virtual BaseIterator & operator[] (const unsigned int index)=0
Detailed Description
template<typename IType>
class armnn::Encoder< IType >
Definition at line 50 of file BaseIterator.hpp.
Constructor & Destructor Documentation
Encoder()
Encoder () inline
Definition at line 53 of file BaseIterator.hpp.
 {}
~Encoder()
virtual ~Encoder () inline virtual
Definition at line 55 of file BaseIterator.hpp.
 {}
Member Function Documentation
Get()
virtual IType Get () const pure virtual
Implemented in QSymm8PerAxisEncoder, BooleanEncoder, Int32ToInt32tEncoder, Int32Encoder, Float32Encoder, Float16Encoder, BFloat16Encoder, QSymm16Encoder, QSymmS8Encoder, QASymmS8Encoder, and QASymm8Encoder.
Referenced by MatrixBatchVectorMultiplyAccumulate(), armnn::Split(), VectorBatchVectorCwiseProductAccumulate(), and VectorVectorCwiseProductAccumulate().
Reset()
virtual void Reset (void *) pure virtual
Implemented in PerAxisIterator< int8_t, Encoder< float > >, TypedIterator< int32_t, Encoder< float > >, TypedIterator< armnn::BFloat16, Encoder< float > >, TypedIterator< int8_t, Encoder< float > >, TypedIterator< uint8_t, Encoder< bool > >, TypedIterator< uint8_t, Encoder< float > >, TypedIterator< int16_t, Encoder< float > >, TypedIterator< int32_t, Encoder< int32_t > >, TypedIterator< float, Encoder< float > >, and TypedIterator< Half, Encoder< float > >.
Set()
virtual void Set (IType right) pure virtual
Implemented in QSymm8PerAxisEncoder, BooleanEncoder, Int32ToInt32tEncoder, Int32Encoder, Float32Encoder, Float16Encoder, BFloat16Encoder, QSymm16Encoder, QSymmS8Encoder, QASymmS8Encoder, and QASymm8Encoder.
Referenced by armnn::Activation(), armnn::BatchNormImpl(), armnn::BatchToSpaceNd(), ClipVector(), ConvertToDataType(), armnn::Convolve(), CopyVector(), armnn::Dequantize(), armnn::Fill(), armnn::FullyConnected(), armnn::Gather(), armnn::InstanceNorm(), armnn::LogSoftmax(), MatrixBatchVectorMultiplyAccumulate(), armnn::Mean(), MeanStddevNormalization(), armnn::Pad(), armnn::Pooling2d(), armnn::Resize(), armnn::Softmax(), armnn::SpaceToBatchNd(), armnn::SpaceToDepth(), armnn::Stack(), Sub1Vector(), armnn::TransposeConvolution2dImpl(), VectorBatchVectorAdd(), VectorBatchVectorAssign(), VectorBatchVectorCwiseProduct(), VectorBatchVectorCwiseProductAccumulate(), VectorVectorCwiseProduct(), VectorVectorCwiseProductAccumulate(), and ZeroVector().
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp