ArmNN: SendThread Class Reference
SendThread Class Reference
#include <SendThread.hpp>
Public Member Functions
SendThread (ProfilingStateMachine &profilingStateMachine, IBufferManager &buffer, ISendCounterPacket &sendCounterPacket, int timeout=1000)
~SendThread ()
void Start (IProfilingConnection &profilingConnection) override
Start the thread.
void Stop (bool rethrowSendThreadExceptions=true) override
Stop the thread.
void SetReadyToRead () override
Set a "ready to read" flag in the buffer to notify the reading thread to start reading it.
bool IsRunning ()
bool WaitForPacketSent (uint32_t timeout)
Public Member Functions inherited from ISendThread
virtual ~ISendThread ()
Public Member Functions inherited from IConsumer
virtual ~IConsumer ()
Detailed Description
Definition at line 29 of file SendThread.hpp.
Constructor & Destructor Documentation
SendThread()
SendThread (ProfilingStateMachine & profilingStateMachine, IBufferManager & buffer, ISendCounterPacket & sendCounterPacket, int timeout = 1000)
Definition at line 26 of file SendThread.cpp.
References IBufferManager::SetConsumer().
     : m_StateMachine(profilingStateMachine)
     , m_BufferManager(buffer)
     , m_SendCounterPacket(sendCounterPacket)
     , m_Timeout(timeout)
     , m_IsRunning(false)
     , m_KeepRunning(false)
     , m_SendThreadException(nullptr)
 {
     m_BufferManager.SetConsumer(this);
 }
~SendThread()
~SendThread () inline
Definition at line 34 of file SendThread.hpp.
References SendThread::SetReadyToRead(), SendThread::Start(), and SendThread::Stop().
     {
         // Don't rethrow when destructing the object
         Stop(false);
     }
Member Function Documentation
IsRunning()
bool IsRunning () inline
Definition at line 45 of file SendThread.hpp.
References SendThread::WaitForPacketSent().
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_IsRunning.load(); }
SetReadyToRead()
void SetReadyToRead () override virtual
Set a "ready to read" flag in the buffer to notify the reading thread to start reading it.
Implements IConsumer.
Definition at line 41 of file SendThread.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), SendThread::Stop(), and SendThread::~SendThread().
 {
     // We need to wait for the send thread to release its mutex
     {
         std::lock_guard<std::mutex> lck(m_WaitMutex);
         m_ReadyToRead = true;
     }
     // Signal the send thread that there's something to read in the buffer
     m_WaitCondition.notify_one();
 }
Start()
void Start (IProfilingConnection & profilingConnection) override virtual
Start the thread.
Implements ISendThread.
Definition at line 52 of file SendThread.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::Update(), and SendThread::~SendThread().
 {
     // Check if the send thread is already running
     if (m_IsRunning.load())
     {
         // The send thread is already running
         return;
     }
     if (m_SendThread.joinable())
     {
         m_SendThread.join();
     }
     // Mark the send thread as running
     m_IsRunning.store(true);
     // Keep the send procedure going until the send thread is signalled to stop
     m_KeepRunning.store(true);
     // Make sure the send thread will not flush the buffer until signaled to do so
     // no need for a mutex as the send thread can not be running at this point
     m_ReadyToRead = false;
     m_PacketSent = false;
     // Start the send thread
     m_SendThread = std::thread(&SendThread::Send, this, std::ref(profilingConnection));
 }
Stop()
void Stop (bool rethrowSendThreadExceptions = true) override virtual
Stop the thread.
Implements ISendThread.
Definition at line 82 of file SendThread.cpp.
References armnn::profiling::Active, ProfilingStateMachine::GetCurrentState(), IBufferManager::GetReadableBuffer(), IProfilingConnection::IsOpen(), IBufferManager::MarkRead(), armnn::profiling::NotConnected, ISendCounterPacket::SendStreamMetaDataPacket(), SendThread::SetReadyToRead(), armnn::profiling::Uninitialised, armnn::profiling::WaitingForAck, and IProfilingConnection::WritePacket().
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::GetSendTimelinePacket(), ProfilingService::Update(), and SendThread::~SendThread().
 {
     // Signal the send thread to stop
     m_KeepRunning.store(false);
     // Check that the send thread is running
     if (m_SendThread.joinable())
     {
         // Kick the send thread out of the wait condition
         SetReadyToRead();
         // Wait for the send thread to complete operations
         m_SendThread.join();
     }
     // Check if the send thread exception has to be rethrown
     if (!rethrowSendThreadExceptions)
     {
         // No need to rethrow the send thread exception, return immediately
         return;
     }
     // Check if there's an exception to rethrow
     if (m_SendThreadException)
     {
         // Rethrow the send thread exception
         std::rethrow_exception(m_SendThreadException);
         // Nullify the exception as it has been rethrown
         m_SendThreadException = nullptr;
     }
 }
WaitForPacketSent()
bool WaitForPacketSent (uint32_t timeout = 1000)
Definition at line 263 of file SendThread.cpp.
Referenced by SendThread::IsRunning(), and ProfilingService::WaitForPacketSent().
 {
     std::unique_lock<std::mutex> lock(m_PacketSentWaitMutex);
     // Blocks until notified that at least a packet has been sent or until timeout expires.
     bool timedOut = m_PacketSentWaitCondition.wait_for(lock,
                                                        std::chrono::milliseconds(timeout),
                                                        [&] { return m_PacketSent; });
     m_PacketSent = false;
     return timedOut;
 }
The documentation for this class was generated from the following files:
src/profiling/SendThread.hpp
src/profiling/SendThread.cpp