ArmNN: TestLayerVisitor Class Reference
TestLayerVisitor Class Reference
#include <TestLayerVisitor.hpp>
Public Member Functions
TestLayerVisitor (const char *name)
Public Member Functions inherited from LayerVisitorBase< VisitorNoThrowPolicy >
void VisitAbsLayer (const IConnectableLayer *, const char *) override
Function an absolute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitActivationLayer (const IConnectableLayer *, const ActivationDescriptor &, const char *) override
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitAdditionLayer (const IConnectableLayer *, const char *) override
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitArgMinMaxLayer (const IConnectableLayer *, const ArgMinMaxDescriptor &, const char *) override
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchNormalizationLayer (const IConnectableLayer *, const BatchNormalizationDescriptor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const char *) override
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchToSpaceNdLayer (const IConnectableLayer *, const BatchToSpaceNdDescriptor &, const char *) override
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitComparisonLayer (const IConnectableLayer *, const ComparisonDescriptor &, const char *) override
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConcatLayer (const IConnectableLayer *, const ConcatDescriptor &, const char *) override
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConstantLayer (const IConnectableLayer *, const ConstTensor &, const char *) override
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConvolution2dLayer (const IConnectableLayer *, const Convolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthToSpaceLayer (const IConnectableLayer *, const DepthToSpaceDescriptor &, const char *) override
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *, const DepthwiseConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDequantizeLayer (const IConnectableLayer *, const char *) override
Function that a Dequantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDetectionPostProcessLayer (const IConnectableLayer *, const DetectionPostProcessDescriptor &, const ConstTensor &, const char *) override
Function that a Detection PostProcess layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDivisionLayer (const IConnectableLayer *, const char *) override
Function a division layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitElementwiseUnaryLayer (const IConnectableLayer *, const ElementwiseUnaryDescriptor &, const char *) override
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitEqualLayer (const IConnectableLayer *, const char *) override
Function an Equal layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFillLayer (const IConnectableLayer *, const FillDescriptor &, const char *) override
Function a fill layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFloorLayer (const IConnectableLayer *, const char *) override
Function a floor layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFullyConnectedLayer (const IConnectableLayer *, const FullyConnectedDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGatherLayer (const IConnectableLayer *, const char *) override
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGatherLayer (const IConnectableLayer *, const GatherDescriptor &, const char *) override
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGreaterLayer (const IConnectableLayer *, const char *) override
Function a Greater layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInstanceNormalizationLayer (const IConnectableLayer *, const InstanceNormalizationDescriptor &, const char *) override
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitL2NormalizationLayer (const IConnectableLayer *, const L2NormalizationDescriptor &, const char *) override
Function that an L2 normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLogSoftmaxLayer (const IConnectableLayer *, const LogSoftmaxDescriptor &, const char *) override
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLstmLayer (const IConnectableLayer *, const LstmDescriptor &, const LstmInputParams &, const char *) override
Function an Lstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMaximumLayer (const IConnectableLayer *, const char *) override
Function a Maximum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMeanLayer (const IConnectableLayer *, const MeanDescriptor &, const char *) override
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMergeLayer (const IConnectableLayer *, const char *) override
Function that a merge layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMergerLayer (const IConnectableLayer *, const MergerDescriptor &, const char *) override
Function that a merger layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMinimumLayer (const IConnectableLayer *, const char *) override
Function a Minimum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMultiplicationLayer (const IConnectableLayer *, const char *) override
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitNormalizationLayer (const IConnectableLayer *, const NormalizationDescriptor &, const char *) override
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitOutputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPadLayer (const IConnectableLayer *, const PadDescriptor &, const char *) override
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPermuteLayer (const IConnectableLayer *, const PermuteDescriptor &, const char *) override
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPooling2dLayer (const IConnectableLayer *, const Pooling2dDescriptor &, const char *) override
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPreluLayer (const IConnectableLayer *, const char *) override
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQuantizeLayer (const IConnectableLayer *, const char *) override
Function a quantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQLstmLayer (const IConnectableLayer *, const QLstmDescriptor &, const LstmInputParams &, const char *) override
Function a QLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQuantizedLstmLayer (const IConnectableLayer *, const QuantizedLstmInputParams &, const char *) override
Function a QuantizedLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitRankLayer (const IConnectableLayer *, const char *) override
Function a rank layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitReshapeLayer (const IConnectableLayer *, const ReshapeDescriptor &, const char *) override
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeBilinearLayer (const IConnectableLayer *, const ResizeBilinearDescriptor &, const char *) override
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeLayer (const IConnectableLayer *, const ResizeDescriptor &, const char *) override
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitRsqrtLayer (const IConnectableLayer *, const char *) override
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSliceLayer (const IConnectableLayer *, const SliceDescriptor &, const char *) override
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSoftmaxLayer (const IConnectableLayer *, const SoftmaxDescriptor &, const char *) override
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToBatchNdLayer (const IConnectableLayer *, const SpaceToBatchNdDescriptor &, const char *) override
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToDepthLayer (const IConnectableLayer *, const SpaceToDepthDescriptor &, const char *) override
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSplitterLayer (const IConnectableLayer *, const ViewsDescriptor &, const char *) override
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStackLayer (const IConnectableLayer *, const StackDescriptor &, const char *) override
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStandInLayer (const IConnectableLayer *, const StandInDescriptor &, const char *) override
Function a StandInLayer should call back to when its Accept(ILaterVisitor&) function is invoked.
void VisitStridedSliceLayer (const IConnectableLayer *, const StridedSliceDescriptor &, const char *) override
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSubtractionLayer (const IConnectableLayer *, const char *) override
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSwitchLayer (const IConnectableLayer *, const char *) override
Function a switch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeConvolution2dLayer (const IConnectableLayer *, const TransposeConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeLayer (const IConnectableLayer *, const TransposeDescriptor &, const char *) override
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Public Member Functions inherited from ILayerVisitor
virtual void StartVisit ()
virtual void FinishVisit ()
Protected Member Functions
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from LayerVisitorBase< VisitorNoThrowPolicy >
LayerVisitorBase ()
virtual ~LayerVisitorBase ()
Protected Member Functions inherited from ILayerVisitor
ILayerVisitor ()
virtual ~ILayerVisitor ()
Detailed Description
Definition at line 13 of file TestLayerVisitor.hpp.
Constructor & Destructor Documentation
~TestLayerVisitor()
virtual ~TestLayerVisitor () inline protected virtual
Definition at line 16 of file TestLayerVisitor.hpp.
References TestLayerVisitor::CheckConstTensors(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), and TestLayerVisitor::CheckOptionalConstTensors().
 {}
TestLayerVisitor()
TestLayerVisitor (const char * name) inline explicit
Definition at line 30 of file TestLayerVisitor.hpp.
                                                 : m_LayerName(name)
     {
         if (name == nullptr)
         {
             m_LayerName = "";
         }
     }
Member Function Documentation
CheckConstTensors()
void CheckConstTensors (const ConstTensor & expected, const ConstTensor & actual) protected
Definition at line 33 of file TestLayerVisitor.cpp.
References BaseTensor< MemoryType >::GetInfo(), BaseTensor< MemoryType >::GetMemoryArea(), BaseTensor< MemoryType >::GetNumBytes(), BaseTensor< MemoryType >::GetNumDimensions(), and BaseTensor< MemoryType >::GetNumElements().
Referenced by TestLstmLayerVisitor::CheckConstTensorPtrs(), TestQLstmLayerVisitor::CheckConstTensorPtrs(), TestQuantizedLstmLayerVisitor::CheckConstTensorPtrs(), TestLayerVisitor::CheckOptionalConstTensors(), TestBatchNormalizationLayerVisitor::VisitBatchNormalizationLayer(), TestConstantLayerVisitor::VisitConstantLayer(), TestConvolution2dLayerVisitor::VisitConvolution2dLayer(), TestDepthwiseConvolution2dLayerVisitor::VisitDepthwiseConvolution2dLayer(), TestFullyConnectedLayerVistor::VisitFullyConnectedLayer(), and TestLayerVisitor::~TestLayerVisitor().
 {
     BOOST_CHECK(expected.GetInfo() == actual.GetInfo());
     BOOST_CHECK(expected.GetNumDimensions() == actual.GetNumDimensions());
     BOOST_CHECK(expected.GetNumElements() == actual.GetNumElements());
     BOOST_CHECK(expected.GetNumBytes() == actual.GetNumBytes());
     if (expected.GetNumBytes() == actual.GetNumBytes())
     {
         //check data is the same byte by byte
         const unsigned char* expectedPtr = static_cast<const unsigned char*>(expected.GetMemoryArea());
         const unsigned char* actualPtr = static_cast<const unsigned char*>(actual.GetMemoryArea());
         for (unsigned int i = 0; i < expected.GetNumBytes(); i++)
         {
             BOOST_CHECK(*(expectedPtr + i) == *(actualPtr + i));
         }
     }
 }
CheckLayerName()
void CheckLayerName (const char * name) protected
Definition at line 12 of file TestLayerVisitor.cpp.
Referenced by TestBatchNormalizationLayerVisitor::VisitBatchNormalizationLayer(), TestConstantLayerVisitor::VisitConstantLayer(), TestConvolution2dLayerVisitor::VisitConvolution2dLayer(), TestDepthwiseConvolution2dLayerVisitor::VisitDepthwiseConvolution2dLayer(), TestFullyConnectedLayerVistor::VisitFullyConnectedLayer(), TestInputLayerVisitor::VisitInputLayer(), TestLstmLayerVisitor::VisitLstmLayer(), TestOutputLayerVisitor::VisitOutputLayer(), TestQLstmLayerVisitor::VisitQLstmLayer(), TestQuantizedLstmLayerVisitor::VisitQuantizedLstmLayer(), and TestLayerVisitor::~TestLayerVisitor().
 {
     if (name == nullptr)
     {
         BOOST_CHECK(m_LayerName == nullptr);
     }
     else if (m_LayerName == nullptr)
     {
         BOOST_CHECK(name == nullptr);
     }
     else
     {
         BOOST_CHECK_EQUAL(m_LayerName, name);
     }
 }
CheckLayerPointer()
void CheckLayerPointer (const IConnectableLayer * layer) protected
Definition at line 28 of file TestLayerVisitor.cpp.
Referenced by TestBatchNormalizationLayerVisitor::VisitBatchNormalizationLayer(), TestConstantLayerVisitor::VisitConstantLayer(), TestConvolution2dLayerVisitor::VisitConvolution2dLayer(), TestDepthwiseConvolution2dLayerVisitor::VisitDepthwiseConvolution2dLayer(), TestFullyConnectedLayerVistor::VisitFullyConnectedLayer(), TestInputLayerVisitor::VisitInputLayer(), TestLstmLayerVisitor::VisitLstmLayer(), TestOutputLayerVisitor::VisitOutputLayer(), TestQLstmLayerVisitor::VisitQLstmLayer(), TestQuantizedLstmLayerVisitor::VisitQuantizedLstmLayer(), and TestLayerVisitor::~TestLayerVisitor().
 {
     BOOST_CHECK(layer != nullptr);
 }
CheckOptionalConstTensors()
void CheckOptionalConstTensors (const Optional< ConstTensor > & expected, const Optional< ConstTensor > & actual) protected
Definition at line 51 of file TestLayerVisitor.cpp.
References TestLayerVisitor::CheckConstTensors(), OptionalBase::has_value(), and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
Referenced by TestConvolution2dLayerVisitor::VisitConvolution2dLayer(), TestDepthwiseConvolution2dLayerVisitor::VisitDepthwiseConvolution2dLayer(), TestFullyConnectedLayerVistor::VisitFullyConnectedLayer(), and TestLayerVisitor::~TestLayerVisitor().
 {
     BOOST_CHECK(expected.has_value() == actual.has_value());
     if (expected.has_value() && actual.has_value())
     {
         CheckConstTensors(expected.value(), actual.value());
     }
 }
The documentation for this class was generated from the following files:
src/armnn/test/TestLayerVisitor.hpp
src/armnn/test/TestLayerVisitor.cpp