ArmNN: AddDebugImpl Class Reference
AddDebugImpl Class Reference
#include <AddDebug.hpp>
Public Member Functions
void Run (Graph &graph, Layer &layer) const
Protected Member Functions
AddDebugImpl ()=default
~AddDebugImpl ()=default
Detailed Description
Definition at line 15 of file AddDebug.hpp.
Constructor & Destructor Documentation
AddDebugImpl()
AddDebugImpl () protected default
Referenced by AddDebugImpl::Run().
~AddDebugImpl()
~AddDebugImpl () protected default
Referenced by AddDebugImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, Layer & layer) const inline
Definition at line 19 of file AddDebug.hpp.
References AddDebugImpl::AddDebugImpl(), armnn::Debug, Layer::GetType(), armnn::InsertDebugLayerAfter(), armnn::Output, and AddDebugImpl::~AddDebugImpl().
     {
         if (layer.GetType() != LayerType::Debug && layer.GetType() != LayerType::Output)
         {
             // if the inputs/outputs of this layer do not have a debug layer
             // insert the debug layer after them
             InsertDebugLayerAfter(graph, layer);
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/AddDebug.hpp