ArmNN: ILayerVisitor Class Reference
ILayerVisitor Class Reference abstract
#include <ILayerVisitor.hpp>
Public Member Functions
virtual void VisitAbsLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function an absolute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitActivationLayer (const IConnectableLayer *layer, const ActivationDescriptor &activationDescriptor, const char *name=nullptr)=0
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitAdditionLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitArgMinMaxLayer (const IConnectableLayer *layer, const ArgMinMaxDescriptor &argMinMaxDescriptor, const char *name=nullptr)=0
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitBatchNormalizationLayer (const IConnectableLayer *layer, const BatchNormalizationDescriptor &desc, const ConstTensor &mean, const ConstTensor &variance, const ConstTensor &beta, const ConstTensor &gamma, const char *name=nullptr)=0
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitBatchToSpaceNdLayer (const IConnectableLayer *layer, const BatchToSpaceNdDescriptor &batchToSpaceNdDescriptor, const char *name=nullptr)=0
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitComparisonLayer (const IConnectableLayer *layer, const ComparisonDescriptor &comparisonDescriptor, const char *name=nullptr)=0
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitConcatLayer (const IConnectableLayer *layer, const OriginsDescriptor &concatDescriptor, const char *name=nullptr)
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitConstantLayer (const IConnectableLayer *layer, const ConstTensor &input, const char *name=nullptr)=0
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitConvolution2dLayer (const IConnectableLayer *layer, const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)=0
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitDepthToSpaceLayer (const IConnectableLayer *layer, const DepthToSpaceDescriptor &depthToSpaceDescriptor, const char *name=nullptr)=0
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *layer, const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)=0
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitDequantizeLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function that a Dequantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitDetectionPostProcessLayer (const IConnectableLayer *layer, const DetectionPostProcessDescriptor &descriptor, const ConstTensor &anchors, const char *name=nullptr)=0
Function that a Detection PostProcess layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitDivisionLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a division layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitElementwiseUnaryLayer (const IConnectableLayer *layer, const ElementwiseUnaryDescriptor &elementwiseUnaryDescriptor, const char *name=nullptr)=0
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitEqualLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function an Equal layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitFillLayer (const IConnectableLayer *layer, const FillDescriptor &fillDescriptor, const char *name=nullptr)=0
Function a fill layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitFloorLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a floor layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitFullyConnectedLayer (const IConnectableLayer *layer, const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)=0
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitGatherLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitGatherLayer (const IConnectableLayer *layer, const GatherDescriptor &gatherDescriptor, const char *name=nullptr)=0
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitGreaterLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a Greater layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitInputLayer (const IConnectableLayer *layer, LayerBindingId id, const char *name=nullptr)=0
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitInstanceNormalizationLayer (const IConnectableLayer *layer, const InstanceNormalizationDescriptor &desc, const char *name=nullptr)=0
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitL2NormalizationLayer (const IConnectableLayer *layer, const L2NormalizationDescriptor &desc, const char *name=nullptr)=0
Function that an L2 normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitLogSoftmaxLayer (const IConnectableLayer *layer, const LogSoftmaxDescriptor &logSoftmaxDescriptor, const char *name=nullptr)=0
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitLstmLayer (const IConnectableLayer *layer, const LstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr)=0
Function an Lstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitMaximumLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a Maximum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitMeanLayer (const IConnectableLayer *layer, const MeanDescriptor &meanDescriptor, const char *name=nullptr)=0
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitMergeLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function that a merge layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitMergerLayer (const IConnectableLayer *layer, const MergerDescriptor &mergerDescriptor, const char *name=nullptr)=0
Function that a merger layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitMinimumLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a Minimum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitMultiplicationLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitNormalizationLayer (const IConnectableLayer *layer, const NormalizationDescriptor &normalizationDescriptor, const char *name=nullptr)=0
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitOutputLayer (const IConnectableLayer *layer, LayerBindingId id, const char *name=nullptr)=0
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitPadLayer (const IConnectableLayer *layer, const PadDescriptor &padDescriptor, const char *name=nullptr)=0
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitPermuteLayer (const IConnectableLayer *layer, const PermuteDescriptor &permuteDescriptor, const char *name=nullptr)=0
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitPooling2dLayer (const IConnectableLayer *layer, const Pooling2dDescriptor &pooling2dDescriptor, const char *name=nullptr)=0
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitPreluLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitQuantizeLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a quantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitQLstmLayer (const IConnectableLayer *layer, const QLstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr)=0
Function a QLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitQuantizedLstmLayer (const IConnectableLayer *layer, const QuantizedLstmInputParams &params, const char *name=nullptr)=0
Function a QuantizedLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitRankLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a rank layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitReshapeLayer (const IConnectableLayer *layer, const ReshapeDescriptor &reshapeDescriptor, const char *name=nullptr)=0
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitResizeBilinearLayer (const IConnectableLayer *layer, const ResizeBilinearDescriptor &resizeDesc, const char *name=nullptr)=0
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitResizeLayer (const IConnectableLayer *layer, const ResizeDescriptor &resizeDescriptor, const char *name=nullptr)=0
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitRsqrtLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSliceLayer (const IConnectableLayer *layer, const SliceDescriptor &sliceDescriptor, const char *name=nullptr)=0
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSoftmaxLayer (const IConnectableLayer *layer, const SoftmaxDescriptor &softmaxDescriptor, const char *name=nullptr)=0
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSpaceToBatchNdLayer (const IConnectableLayer *layer, const SpaceToBatchNdDescriptor &spaceToBatchNdDescriptor, const char *name=nullptr)=0
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSpaceToDepthLayer (const IConnectableLayer *layer, const SpaceToDepthDescriptor &spaceToDepthDescriptor, const char *name=nullptr)=0
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSplitterLayer (const IConnectableLayer *layer, const ViewsDescriptor &splitterDescriptor, const char *name=nullptr)=0
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitStackLayer (const IConnectableLayer *layer, const StackDescriptor &stackDescriptor, const char *name=nullptr)=0
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitStandInLayer (const IConnectableLayer *layer, const StandInDescriptor &standInDescriptor, const char *name=nullptr)=0
Function a StandInLayer should call back to when its Accept(ILaterVisitor&) function is invoked.
virtual void VisitStridedSliceLayer (const IConnectableLayer *layer, const StridedSliceDescriptor &stridedSliceDescriptor, const char *name=nullptr)=0
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSubtractionLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitSwitchLayer (const IConnectableLayer *layer, const char *name=nullptr)=0
Function a switch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitTransposeConvolution2dLayer (const IConnectableLayer *layer, const TransposeConvolution2dDescriptor &descriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)=0
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void VisitTransposeLayer (const IConnectableLayer *layer, const TransposeDescriptor &transposeDescriptor, const char *name=nullptr)=0
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
virtual void StartVisit ()
virtual void FinishVisit ()
Protected Member Functions
ILayerVisitor ()
virtual ~ILayerVisitor ()
Detailed Description
Definition at line 16 of file ILayerVisitor.hpp.
Constructor & Destructor Documentation
ILayerVisitor()
ILayerVisitor () inline protected
Definition at line 19 of file ILayerVisitor.hpp.
 {}
~ILayerVisitor()
virtual ~ILayerVisitor () inline protected virtual
Definition at line 20 of file ILayerVisitor.hpp.
References ARMNN_DEPRECATED_MSG, ILayerVisitor::VisitAbsLayer(), ILayerVisitor::VisitActivationLayer(), ILayerVisitor::VisitAdditionLayer(), ILayerVisitor::VisitArgMinMaxLayer(), ILayerVisitor::VisitBatchNormalizationLayer(), ILayerVisitor::VisitBatchToSpaceNdLayer(), and ILayerVisitor::VisitComparisonLayer().
 {}
Member Function Documentation
FinishVisit()
virtual void FinishVisit () inline virtual
Reimplemented in DynamicQuantizationVisitor.
Definition at line 539 of file ILayerVisitor.hpp.
Referenced by armnn::VisitLayers().
 {}
StartVisit()
virtual void StartVisit () inline virtual
Definition at line 538 of file ILayerVisitor.hpp.
Referenced by armnn::VisitLayers().
 {}
VisitAbsLayer()
virtual void VisitAbsLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function an absolute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and DynamicQuantizationVisitor.
Referenced by AbsLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitActivationLayer()
virtual void VisitActivationLayer (const IConnectableLayer * layer, const ActivationDescriptor & activationDescriptor, const char * name = nullptr) pure virtual
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
activationDescriptor - ActivationDescriptor to configure the activation.
name - Optional name for the layer.
Implemented in DynamicQuantizationVisitor, SerializerVisitor, StaticRangeVisitor, TestActivationLayerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by ActivationLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitAdditionLayer()
virtual void VisitAdditionLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, DynamicQuantizationVisitor, TestAdditionLayerVisitor, and StaticRangeVisitor.
Referenced by AdditionLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitArgMinMaxLayer()
virtual void VisitArgMinMaxLayer (const IConnectableLayer * layer, const ArgMinMaxDescriptor & argMinMaxDescriptor, const char * name = nullptr) pure virtual
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
argMinMaxDescriptor - ArgMinMaxDescriptor to configure the activation.
name - Optional name for the layer.
Implemented in SerializerVisitor, TestArgMinMaxLayerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and DynamicQuantizationVisitor.
Referenced by ArgMinMaxLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitBatchNormalizationLayer()
virtual void VisitBatchNormalizationLayer (const IConnectableLayer * layer, const BatchNormalizationDescriptor & desc, const ConstTensor & mean, const ConstTensor & variance, const ConstTensor & beta, const ConstTensor & gamma, const char * name = nullptr) pure virtual
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
mean - Pre-calculated mean for each channel.
variance - Pre-calculated variance for each channel.
beta - Per-channel additive factor.
gamma - Per-channel multiplicative factor.
name - Optional name for the layer.
Implemented in TestBatchNormalizationLayerVisitor, SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, DynamicQuantizationVisitor, and StaticRangeVisitor.
Referenced by BatchNormalizationLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitBatchToSpaceNdLayer()
virtual void VisitBatchToSpaceNdLayer (const IConnectableLayer * layer, const BatchToSpaceNdDescriptor & batchToSpaceNdDescriptor, const char * name = nullptr) pure virtual
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
batchToSpaceNdDescriptor - Description of the layer.
name - Optional name for the layer.
Implemented in DynamicQuantizationVisitor, StaticRangeVisitor, SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestBatchToSpaceNdLayerVisitor.
Referenced by BatchToSpaceNdLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitComparisonLayer()
virtual void VisitComparisonLayer (const IConnectableLayer * layer, const ComparisonDescriptor & comparisonDescriptor, const char * name = nullptr) pure virtual
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
comparisonDescriptor - Description of the layer.
name - Optional name for the layer.
Implemented in SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestComparisonLayerVisitor.
Referenced by ComparisonLayer::Accept(), and ILayerVisitor::~ILayerVisitor().
VisitConcatLayer()
virtual void VisitConcatLayer (const IConnectableLayer * layer, const OriginsDescriptor & concatDescriptor, const char * name = nullptr) inline virtual
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
concatDescriptor - ConcatDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Reimplemented in DynamicQuantizationVisitor, SerializerVisitor, StaticRangeVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestConcatLayerVisitor.
Definition at line 93 of file ILayerVisitor.hpp.
References anchors(), ARMNN_DEPRECATED_MSG, ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, ILayerVisitor::VisitConstantLayer(), ILayerVisitor::VisitConvolution2dLayer(), ILayerVisitor::VisitDepthToSpaceLayer(), ILayerVisitor::VisitDepthwiseConvolution2dLayer(), ILayerVisitor::VisitDequantizeLayer(), ILayerVisitor::VisitDetectionPostProcessLayer(), ILayerVisitor::VisitDivisionLayer(), ILayerVisitor::VisitElementwiseUnaryLayer(), ILayerVisitor::VisitEqualLayer(), ILayerVisitor::VisitFillLayer(), ILayerVisitor::VisitFloorLayer(), ILayerVisitor::VisitFullyConnectedLayer(), ILayerVisitor::VisitGatherLayer(), ILayerVisitor::VisitGreaterLayer(), ILayerVisitor::VisitInputLayer(), ILayerVisitor::VisitInstanceNormalizationLayer(), ILayerVisitor::VisitL2NormalizationLayer(), ILayerVisitor::VisitLogSoftmaxLayer(), ILayerVisitor::VisitLstmLayer(), ILayerVisitor::VisitMaximumLayer(), ILayerVisitor::VisitMeanLayer(), ILayerVisitor::VisitMergeLayer(), ILayerVisitor::VisitMergerLayer(), ILayerVisitor::VisitMinimumLayer(), ILayerVisitor::VisitMultiplicationLayer(), ILayerVisitor::VisitNormalizationLayer(), ILayerVisitor::VisitOutputLayer(), ILayerVisitor::VisitPadLayer(), ILayerVisitor::VisitPermuteLayer(), ILayerVisitor::VisitPooling2dLayer(), ILayerVisitor::VisitPreluLayer(), ILayerVisitor::VisitQLstmLayer(), ILayerVisitor::VisitQuantizedLstmLayer(), ILayerVisitor::VisitQuantizeLayer(), ILayerVisitor::VisitRankLayer(), ILayerVisitor::VisitReshapeLayer(), ILayerVisitor::VisitResizeBilinearLayer(), ILayerVisitor::VisitResizeLayer(), ILayerVisitor::VisitRsqrtLayer(), ILayerVisitor::VisitSliceLayer(), ILayerVisitor::VisitSoftmaxLayer(), ILayerVisitor::VisitSpaceToBatchNdLayer(), ILayerVisitor::VisitSpaceToDepthLayer(), ILayerVisitor::VisitSplitterLayer(), ILayerVisitor::VisitStackLayer(), ILayerVisitor::VisitStandInLayer(), ILayerVisitor::VisitStridedSliceLayer(), ILayerVisitor::VisitSubtractionLayer(), ILayerVisitor::VisitSwitchLayer(), ILayerVisitor::VisitTransposeConvolution2dLayer(), and ILayerVisitor::VisitTransposeLayer().
Referenced by ConcatLayer::Accept().
     {
         // default implementation to ease transition while MergerLayer is being deprecated
         ARMNN_NO_DEPRECATE_WARN_BEGIN
         VisitMergerLayer(layer, concatDescriptor, name);
         ARMNN_NO_DEPRECATE_WARN_END
     }
VisitConstantLayer()
virtual void VisitConstantLayer (const IConnectableLayer * layer, const ConstTensor & input, const char * name = nullptr) pure virtual
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
input - Tensor to be provided as the only output of the layer. The layer will maintain its own copy of the tensor data, meaning the memory referenced by input can be freed or reused after this function is called.
name - Optional name for the layer.
Implemented in TestConstantLayerVisitor, DynamicQuantizationVisitor, SerializerVisitor, StaticRangeVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by ConstantLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitConvolution2dLayer()
virtual void VisitConvolution2dLayer (const IConnectableLayer * layer, const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) pure virtual
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implemented in SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, DynamicQuantizationVisitor, StaticRangeVisitor, and TestConvolution2dLayerVisitor.
Referenced by Convolution2dLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitDepthToSpaceLayer()
virtual void VisitDepthToSpaceLayer (const IConnectableLayer * layer, const DepthToSpaceDescriptor & depthToSpaceDescriptor, const char * name = nullptr) pure virtual
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
depthToSpaceDescriptor - Parameters for the depth to space operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestDepthToSpaceLayerVisitor.
Referenced by DepthToSpaceLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitDepthwiseConvolution2dLayer()
virtual void VisitDepthwiseConvolution2dLayer (const IConnectableLayer * layer, const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) pure virtual
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D depthwise convolution layer.
weights - Tensor for the weights. Expected format: [channelMultiplier, inputChannels, height, width].
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implemented in SerializerVisitor, QuantizerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, TestDepthwiseConvolution2dLayerVisitor, DynamicQuantizationVisitor, and StaticRangeVisitor.
Referenced by DepthwiseConvolution2dLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitDequantizeLayer()
virtual void VisitDequantizeLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function that a Dequantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestDequantizeLayerVisitor.
Referenced by DequantizeLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitDetectionPostProcessLayer()
virtual void VisitDetectionPostProcessLayer (const IConnectableLayer * layer, const DetectionPostProcessDescriptor & descriptor, const ConstTensor & anchors, const char * name = nullptr) pure virtual
Function that a Detection PostProcess layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
descriptor - Description of the Detection PostProcess layer.
anchors - Tensor for the anchors.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by DetectionPostProcessLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitDivisionLayer()
virtual void VisitDivisionLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a division layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestDivisionLayerVisitor.
Referenced by DivisionLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitElementwiseUnaryLayer()
virtual void VisitElementwiseUnaryLayer (const IConnectableLayer * layer, const ElementwiseUnaryDescriptor & elementwiseUnaryDescriptor, const char * name = nullptr) pure virtual
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
elementwiseUnaryDescriptor - Description of the layer.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestElementwiseUnaryLayerVisitor.
Referenced by ElementwiseUnaryLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitEqualLayer()
virtual void VisitEqualLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function an Equal layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by ILayerVisitor::VisitConcatLayer().
VisitFillLayer()
virtual void VisitFillLayer (const IConnectableLayer * layer, const FillDescriptor & fillDescriptor, const char * name = nullptr) pure virtual
Function a fill layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
fillDescriptor - Description of the layer
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestFillLayerVisitor.
Referenced by FillLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitFloorLayer()
virtual void VisitFloorLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a floor layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestFloorLayerVisitor.
Referenced by FloorLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitFullyConnectedLayer()
virtual void VisitFullyConnectedLayer (const IConnectableLayer * layer, const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) pure virtual
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
fullyConnectedDescriptor - Description of the fully connected layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, TestFullyConnectedLayerVistor, QuantizerVisitor, DynamicQuantizationVisitor, and StaticRangeVisitor.
Referenced by FullyConnectedLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitGatherLayer() [1/2]
virtual void VisitGatherLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by GatherLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitGatherLayer() [2/2]
virtual void VisitGatherLayer (const IConnectableLayer * layer, const GatherDescriptor & gatherDescriptor, const char * name = nullptr) pure virtual
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
gatherDescriptor - Parameters for the gather operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestGatherLayerVisitor.
VisitGreaterLayer()
virtual void VisitGreaterLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a Greater layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by ILayerVisitor::VisitConcatLayer().
VisitInputLayer()
virtual void VisitInputLayer (const IConnectableLayer * layer, LayerBindingId id, const char * name = nullptr) pure virtual
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
id - User generated id to uniquely identify a particular input. The same id needs to be specified when passing the inputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, DynamicQuantizationVisitor, QuantizerVisitor, InputLayerVisitor, TestInputLayerVisitor, and OverrideInputRangeVisitor.
Referenced by InputLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitInstanceNormalizationLayer()
virtual void VisitInstanceNormalizationLayer (const IConnectableLayer * layer, const InstanceNormalizationDescriptor & desc, const char * name = nullptr) pure virtual
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
desc - Parameters for the instance normalization operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestInstanceNormalizationLayerVisitor.
Referenced by InstanceNormalizationLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitL2NormalizationLayer()
virtual void VisitL2NormalizationLayer (const IConnectableLayer * layer, const L2NormalizationDescriptor & desc, const char * name = nullptr) pure virtual
Function that an L2 normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Normalization is performed along dimension 1, but requires a 4d input.
Parameters
layer - pointer to the layer which is calling back to this visit function.
desc - Parameters for the L2 normalization operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestL2NormalizationLayerVisitor.
Referenced by L2NormalizationLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitLogSoftmaxLayer()
virtual void VisitLogSoftmaxLayer (const IConnectableLayer * layer, const LogSoftmaxDescriptor & logSoftmaxDescriptor, const char * name = nullptr) pure virtual
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
logSoftmaxDescriptor - LogSoftmaxDescriptor to configure the log softmax.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestLogSoftmaxLayerVisitor.
Referenced by LogSoftmaxLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitLstmLayer()
virtual void VisitLstmLayer (const IConnectableLayer * layer, const LstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr) pure virtual
Function an Lstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
descriptor - Parameters controlling the operation of the Lstm operation.
params - The weights and biases for the LSTM cell.
name - Optional name for the layer.
Implemented in TestLstmLayerVisitor, SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by LstmLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitMaximumLayer()
virtual void VisitMaximumLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a Maximum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestMaximumLayerVisitor.
Referenced by MaximumLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitMeanLayer()
virtual void VisitMeanLayer (const IConnectableLayer * layer, const MeanDescriptor & meanDescriptor, const char * name = nullptr) pure virtual
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
meanDescriptor - Parameters for the mean operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestMeanLayerVisitor.
Referenced by MeanLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitMergeLayer()
virtual void VisitMergeLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function that a merge layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestMergeLayerVisitor.
Referenced by MergeLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitMergerLayer()
virtual void VisitMergerLayer (const IConnectableLayer * layer, const MergerDescriptor & mergerDescriptor, const char * name = nullptr) pure virtual
Function that a merger layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
mergerDescriptor - MergerDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by ILayerVisitor::VisitConcatLayer().
VisitMinimumLayer()
virtual void VisitMinimumLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a Minimum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestMinimumLayerVisitor.
Referenced by MinimumLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitMultiplicationLayer()
virtual void VisitMultiplicationLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestMultiplicationLayerVisitor.
Referenced by MultiplicationLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitNormalizationLayer()
virtual void VisitNormalizationLayer (const IConnectableLayer * layer, const NormalizationDescriptor & normalizationDescriptor, const char * name = nullptr) pure virtual
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
normalizationDescriptor - NormalizationDescriptor to configure the normalization.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, TestNormalizationLayerVisitor, and DynamicQuantizationVisitor.
Referenced by NormalizationLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitOutputLayer()
virtual void VisitOutputLayer (const IConnectableLayer * layer, LayerBindingId id, const char * name = nullptr) pure virtual
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
id - User generated id to uniquely identify a particular output. The same id needs to be specified when passing the outputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, and TestOutputLayerVisitor.
Referenced by OutputLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitPadLayer()
virtual void VisitPadLayer (const IConnectableLayer * layer, const PadDescriptor & padDescriptor, const char * name = nullptr) pure virtual
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
paddings - n by 2 tensor, where n is the rank of the input tensor, such that paddings[i,0] indicates the amount of padding to add in front of dimension i, and paddings[i,1] indicates the amount of padding to add after the end of dimension i
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestPadLayerVisitor.
Referenced by PadLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitPermuteLayer()
virtual void VisitPermuteLayer (const IConnectableLayer * layer, const PermuteDescriptor & permuteDescriptor, const char * name = nullptr) pure virtual
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
permuteDescriptor - PermuteDescriptor to configure the permute.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, TestPermuteLayerVisitor, and StaticRangeVisitor.
Referenced by PermuteLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitPooling2dLayer()
virtual void VisitPooling2dLayer (const IConnectableLayer * layer, const Pooling2dDescriptor & pooling2dDescriptor, const char * name = nullptr) pure virtual
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
pooling2dDescriptor - Pooling2dDescriptor to configure the pooling.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, StaticRangeVisitor, and TestPooling2dLayerVisitor.
Referenced by Pooling2dLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitPreluLayer()
virtual void VisitPreluLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestPreluLayerVisitor.
Referenced by PreluLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitQLstmLayer()
virtual void VisitQLstmLayer (const IConnectableLayer * layer, const QLstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr) pure virtual
Function a QLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
descriptor - Parameters controlling the operation of the QLstm operation.
params - The weights and biases for the layer
name - Optional name for the layer.
Implemented in TestQLstmLayerVisitor, SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by QLstmLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitQuantizedLstmLayer()
virtual void VisitQuantizedLstmLayer (const IConnectableLayer * layer, const QuantizedLstmInputParams & params, const char * name = nullptr) pure virtual
Function a QuantizedLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
params - The weights and biases for the Quantized LSTM cell
name - Optional name for the layer.
Implemented in TestQuantizedLstmLayerVisitor, SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, and LayerVisitorBase< VisitorNoThrowPolicy >.
Referenced by QuantizedLstmLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitQuantizeLayer()
virtual void VisitQuantizeLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a quantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestQuantizeLayerVisitor.
Referenced by QuantizeLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitRankLayer()
virtual void VisitRankLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a rank layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestRankLayerVisitor.
Referenced by RankLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitReshapeLayer()
virtual void VisitReshapeLayer (const IConnectableLayer * layer, const ReshapeDescriptor & reshapeDescriptor, const char * name = nullptr) pure virtual
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
reshapeDescriptor - Parameters for the reshape operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, StaticRangeVisitor, and TestReshapeLayerVisitor.
Referenced by ReshapeLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitResizeBilinearLayer()
virtual void VisitResizeBilinearLayer (const IConnectableLayer * layer, const ResizeBilinearDescriptor & resizeDesc, const char * name = nullptr) pure virtual
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
resizeDesc - Parameters for the resize operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, and StaticRangeVisitor.
Referenced by ILayerVisitor::VisitConcatLayer().
VisitResizeLayer()
virtual void VisitResizeLayer (const IConnectableLayer * layer, const ResizeDescriptor & resizeDescriptor, const char * name = nullptr) pure virtual
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
resizeDescriptor - Parameters for the resize operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, StaticRangeVisitor, and TestResizeLayerVisitor.
Referenced by ResizeLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitRsqrtLayer()
virtual void VisitRsqrtLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and QuantizerVisitor.
Referenced by RsqrtLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSliceLayer()
virtual void VisitSliceLayer (const IConnectableLayer * layer, const SliceDescriptor & sliceDescriptor, const char * name = nullptr) pure virtual
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
sliceDescriptor - SliceDescriptor to configure the slice operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestSliceLayerVisitor.
Referenced by SliceLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSoftmaxLayer()
virtual void VisitSoftmaxLayer (const IConnectableLayer * layer, const SoftmaxDescriptor & softmaxDescriptor, const char * name = nullptr) pure virtual
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
softmaxDescriptor - SoftmaxDescriptor to configure the softmax.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, StaticRangeVisitor, and TestSoftmaxLayerVisitor.
Referenced by SoftmaxLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSpaceToBatchNdLayer()
virtual void VisitSpaceToBatchNdLayer (const IConnectableLayer * layer, const SpaceToBatchNdDescriptor & spaceToBatchNdDescriptor, const char * name = nullptr) pure virtual
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
spaceToBatchNdDescriptor - Parameters for the space to batch operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, TestSpaceToBatchNdLayerVisitor, and StaticRangeVisitor.
Referenced by SpaceToBatchNdLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSpaceToDepthLayer()
virtual void VisitSpaceToDepthLayer (const IConnectableLayer * layer, const SpaceToDepthDescriptor & spaceToDepthDescriptor, const char * name = nullptr) pure virtual
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
spaceToDepthDescriptor - Parameters for the space to depth operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestSpaceToDepthLayerVisitor.
Referenced by SpaceToDepthLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSplitterLayer()
virtual void VisitSplitterLayer (const IConnectableLayer * layer, const ViewsDescriptor & splitterDescriptor, const char * name = nullptr) pure virtual
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
splitterDescriptor - ViewsDescriptor to configure the splitting process. Number of Views must be equal to the number of outputs, and their order must match - e.g. first view corresponds to the first output, second view to the second output, etc....
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, StaticRangeVisitor, and TestSplitterLayerVisitor.
Referenced by SplitterLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitStackLayer()
virtual void VisitStackLayer (const IConnectableLayer * layer, const StackDescriptor & stackDescriptor, const char * name = nullptr) pure virtual
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
stackDescriptor - Parameters for the stack operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestStackLayerVisitor.
Referenced by StackLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitStandInLayer()
virtual void VisitStandInLayer (const IConnectableLayer * layer, const StandInDescriptor & standInDescriptor, const char * name = nullptr) pure virtual
Function a StandInLayer should call back to when its Accept(ILaterVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
standInDescriptor - Parameters for the stand-in layer.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestStandInLayerVisitor.
Referenced by StandInLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitStridedSliceLayer()
virtual void VisitStridedSliceLayer (const IConnectableLayer * layer, const StridedSliceDescriptor & stridedSliceDescriptor, const char * name = nullptr) pure virtual
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
stridedSliceDescriptor - Parameters for the strided slice operation.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, DynamicQuantizationVisitor, StaticRangeVisitor, and TestStridedSliceLayerVisitor.
Referenced by StridedSliceLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSubtractionLayer()
virtual void VisitSubtractionLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestSubtractionLayerVisitor.
Referenced by SubtractionLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitSwitchLayer()
virtual void VisitSwitchLayer (const IConnectableLayer * layer, const char * name = nullptr) pure virtual
Function a switch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and TestSwitchLayerVisitor.
Referenced by SwitchLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitTransposeConvolution2dLayer()
virtual void VisitTransposeConvolution2dLayer (const IConnectableLayer * layer, const TransposeConvolution2dDescriptor & descriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) pure virtual
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
descriptor - Description of the 2D transpose convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, and QuantizerVisitor.
Referenced by TransposeConvolution2dLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
VisitTransposeLayer()
virtual void VisitTransposeLayer (const IConnectableLayer * layer, const TransposeDescriptor & transposeDescriptor, const char * name = nullptr) pure virtual
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
transposeDescriptor - TransposeDescriptor to configure the transpose.
name - Optional name for the layer.
Implemented in SerializerVisitor, LayerVisitorBase< DefaultPolicy >, LayerVisitorBase< VisitorThrowingPolicy >, LayerVisitorBase< armnn::VisitorNoThrowPolicy >, LayerVisitorBase< VisitorNoThrowPolicy >, QuantizerVisitor, and TestTransposeLayerVisitor.
Referenced by TransposeLayer::Accept(), and ILayerVisitor::VisitConcatLayer().
The documentation for this class was generated from the following file:
include/armnn/ILayerVisitor.hpp