ArmNN: QuantizedLstmLayer Class Reference
QuantizedLstmLayer Class Reference
This layer represents a QuantizedLstm operation.
#include <QuantizedLstmLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the QuantizedLstm type.
QuantizedLstmLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of QuantizedLstmLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
void Accept (ILayerVisitor &visitor) const override
Apply a visitor to this layer.
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void SerializeLayerParameters (ParameterStringifyFunction &fn) const
Helper to serialize the layer parameters to string.
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
Public Attributes
QuantizedLstmParameters m_QuantizedLstmParameters
Protected Member Functions
QuantizedLstmLayer (const char *name)
Constructor to create a QuantizedLstmLayer.
~QuantizedLstmLayer ()=default
Default destructor.
Layer::ConstantTensors GetConstantTensorsByRef () override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a QuantizedLstm operation.
Definition at line 45 of file QuantizedLstmLayer.hpp.
Constructor & Destructor Documentation
QuantizedLstmLayer()
QuantizedLstmLayer (const char * name) protected
Constructor to create a QuantizedLstmLayer.
Parameters
[in] name Optional name for the layer.
Definition at line 17 of file QuantizedLstmLayer.cpp.
References armnn::QuantizedLstm.
     : Layer(3, 2, LayerType::QuantizedLstm, name)
 {
 }
~QuantizedLstmLayer()
~QuantizedLstmLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Apply a visitor to this layer.
Implements IConnectableLayer.
Definition at line 170 of file QuantizedLstmLayer.cpp.
References Layer::GetName(), QuantizedLstmParameters::m_CellBias, QuantizedLstmInputParams::m_CellBias, QuantizedLstmParameters::m_ForgetGateBias, QuantizedLstmInputParams::m_ForgetGateBias, QuantizedLstmParameters::m_InputGateBias, QuantizedLstmInputParams::m_InputGateBias, QuantizedLstmParameters::m_InputToCellWeights, QuantizedLstmInputParams::m_InputToCellWeights, QuantizedLstmParameters::m_InputToForgetWeights, QuantizedLstmInputParams::m_InputToForgetWeights, QuantizedLstmParameters::m_InputToInputWeights, QuantizedLstmInputParams::m_InputToInputWeights, QuantizedLstmParameters::m_InputToOutputWeights, QuantizedLstmInputParams::m_InputToOutputWeights, QuantizedLstmParameters::m_OutputGateBias, QuantizedLstmInputParams::m_OutputGateBias, QuantizedLstmLayer::m_QuantizedLstmParameters, QuantizedLstmParameters::m_RecurrentToCellWeights, QuantizedLstmInputParams::m_RecurrentToCellWeights, QuantizedLstmParameters::m_RecurrentToForgetWeights, QuantizedLstmInputParams::m_RecurrentToForgetWeights, QuantizedLstmParameters::m_RecurrentToInputWeights, QuantizedLstmInputParams::m_RecurrentToInputWeights, QuantizedLstmParameters::m_RecurrentToOutputWeights, QuantizedLstmInputParams::m_RecurrentToOutputWeights, and ILayerVisitor::VisitQuantizedLstmLayer().
 {
     QuantizedLstmInputParams inputParams;
     // InputToX weight tensors
     ConstTensor inputToInputWeightsTensor;
     if (m_QuantizedLstmParameters.m_InputToInputWeights != nullptr)
     {
         ConstTensor inputToInputWeightsTensorCopy(m_QuantizedLstmParameters.m_InputToInputWeights->GetTensorInfo(),
                                                   m_QuantizedLstmParameters.m_InputToInputWeights->Map(true));
         inputToInputWeightsTensor = inputToInputWeightsTensorCopy;
         inputParams.m_InputToInputWeights = &inputToInputWeightsTensor;
     }
     ConstTensor inputToForgetWeightsTensor;
     if (m_QuantizedLstmParameters.m_InputToForgetWeights != nullptr)
     {
         ConstTensor inputToForgetWeightsTensorCopy(m_QuantizedLstmParameters.m_InputToForgetWeights->GetTensorInfo(),
                                                    m_QuantizedLstmParameters.m_InputToForgetWeights->Map(true));
         inputToForgetWeightsTensor = inputToForgetWeightsTensorCopy;
         inputParams.m_InputToForgetWeights = &inputToForgetWeightsTensor;
     }
     ConstTensor inputToCellWeightsTensor;
     if (m_QuantizedLstmParameters.m_InputToCellWeights != nullptr)
     {
         ConstTensor inputToCellWeightsTensorCopy(m_QuantizedLstmParameters.m_InputToCellWeights->GetTensorInfo(),
                                                  m_QuantizedLstmParameters.m_InputToCellWeights->Map(true));
         inputToCellWeightsTensor = inputToCellWeightsTensorCopy;
         inputParams.m_InputToCellWeights = &inputToCellWeightsTensor;
     }
     ConstTensor inputToOutputWeightsTensor;
     if (m_QuantizedLstmParameters.m_InputToOutputWeights != nullptr)
     {
         ConstTensor inputToOutputWeightsTensorCopy(m_QuantizedLstmParameters.m_InputToOutputWeights->GetTensorInfo(),
                                                    m_QuantizedLstmParameters.m_InputToOutputWeights->Map(true));
         inputToOutputWeightsTensor = inputToOutputWeightsTensorCopy;
         inputParams.m_InputToOutputWeights = &inputToOutputWeightsTensor;
     }
     // RecurrentToX weight tensors
     ConstTensor recurrentToInputWeightsTensor;
     if (m_QuantizedLstmParameters.m_RecurrentToInputWeights != nullptr)
     {
         ConstTensor recurrentToInputWeightsTensorCopy(
                 m_QuantizedLstmParameters.m_RecurrentToInputWeights->GetTensorInfo(),
                 m_QuantizedLstmParameters.m_RecurrentToInputWeights->Map(true));
         recurrentToInputWeightsTensor = recurrentToInputWeightsTensorCopy;
         inputParams.m_RecurrentToInputWeights = &recurrentToInputWeightsTensor;
     }
     ConstTensor recurrentToForgetWeightsTensor;
     if (m_QuantizedLstmParameters.m_RecurrentToForgetWeights != nullptr)
     {
         ConstTensor recurrentToForgetWeightsTensorCopy(
                 m_QuantizedLstmParameters.m_RecurrentToForgetWeights->GetTensorInfo(),
                 m_QuantizedLstmParameters.m_RecurrentToForgetWeights->Map(true));
         recurrentToForgetWeightsTensor = recurrentToForgetWeightsTensorCopy;
         inputParams.m_RecurrentToForgetWeights = &recurrentToForgetWeightsTensor;
     }
     ConstTensor recurrentToCellWeightsTensor;
     if (m_QuantizedLstmParameters.m_RecurrentToCellWeights != nullptr)
     {
         ConstTensor recurrentToCellWeightsTensorCopy(
                 m_QuantizedLstmParameters.m_RecurrentToCellWeights->GetTensorInfo(),
                 m_QuantizedLstmParameters.m_RecurrentToCellWeights->Map(true));
         recurrentToCellWeightsTensor = recurrentToCellWeightsTensorCopy;
         inputParams.m_RecurrentToCellWeights = &recurrentToCellWeightsTensor;
     }
     ConstTensor recurrentToOutputWeightsTensor;
     if (m_QuantizedLstmParameters.m_RecurrentToOutputWeights != nullptr)
     {
         ConstTensor recurrentToOutputWeightsTensorCopy(
                 m_QuantizedLstmParameters.m_RecurrentToOutputWeights->GetTensorInfo(),
                 m_QuantizedLstmParameters.m_RecurrentToOutputWeights->Map(true));
         recurrentToOutputWeightsTensor = recurrentToOutputWeightsTensorCopy;
         inputParams.m_RecurrentToOutputWeights = &recurrentToOutputWeightsTensor;
     }
     // Bias tensors
     ConstTensor inputGateBiasTensor;
     if (m_QuantizedLstmParameters.m_InputGateBias != nullptr)
     {
         ConstTensor inputGateBiasTensorCopy(m_QuantizedLstmParameters.m_InputGateBias->GetTensorInfo(),
                                             m_QuantizedLstmParameters.m_InputGateBias->Map(true));
         inputGateBiasTensor = inputGateBiasTensorCopy;
         inputParams.m_InputGateBias = &inputGateBiasTensor;
     }
     ConstTensor forgetGateBiasTensor;
     if (m_QuantizedLstmParameters.m_ForgetGateBias != nullptr)
     {
         ConstTensor forgetGateBiasTensorCopy(m_QuantizedLstmParameters.m_ForgetGateBias->GetTensorInfo(),
                                              m_QuantizedLstmParameters.m_ForgetGateBias->Map(true));
         forgetGateBiasTensor = forgetGateBiasTensorCopy;
         inputParams.m_ForgetGateBias = &forgetGateBiasTensor;
     }
     ConstTensor cellBiasTensor;
     if (m_QuantizedLstmParameters.m_CellBias != nullptr)
     {
         ConstTensor cellBiasTensorCopy(m_QuantizedLstmParameters.m_CellBias->GetTensorInfo(),
                                        m_QuantizedLstmParameters.m_CellBias->Map(true));
         cellBiasTensor = cellBiasTensorCopy;
         inputParams.m_CellBias = &cellBiasTensor;
     }
     ConstTensor outputGateBiasTensor;
     if (m_QuantizedLstmParameters.m_OutputGateBias != nullptr)
     {
         ConstTensor outputGateBiasCopy(m_QuantizedLstmParameters.m_OutputGateBias->GetTensorInfo(),
                                        m_QuantizedLstmParameters.m_OutputGateBias->Map(true));
         outputGateBiasTensor = outputGateBiasCopy;
         inputParams.m_OutputGateBias = &outputGateBiasTensor;
     }
     visitor.VisitQuantizedLstmLayer(this, inputParams, GetName());
 }
Clone()
QuantizedLstmLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 45 of file QuantizedLstmLayer.cpp.
References Layer::GetName(), QuantizedLstmParameters::m_CellBias, QuantizedLstmParameters::m_ForgetGateBias, QuantizedLstmParameters::m_InputGateBias, QuantizedLstmParameters::m_InputToCellWeights, QuantizedLstmParameters::m_InputToForgetWeights, QuantizedLstmParameters::m_InputToInputWeights, QuantizedLstmParameters::m_InputToOutputWeights, QuantizedLstmParameters::m_OutputGateBias, QuantizedLstmLayer::m_QuantizedLstmParameters, QuantizedLstmParameters::m_RecurrentToCellWeights, QuantizedLstmParameters::m_RecurrentToForgetWeights, QuantizedLstmParameters::m_RecurrentToInputWeights, and QuantizedLstmParameters::m_RecurrentToOutputWeights.
 {
     auto layer = CloneBase<QuantizedLstmLayer>(graph, GetName());
     layer->m_QuantizedLstmParameters.m_InputToInputWeights = m_QuantizedLstmParameters.m_InputToInputWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_InputToInputWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_InputToForgetWeights = m_QuantizedLstmParameters.m_InputToForgetWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_InputToForgetWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_InputToCellWeights = m_QuantizedLstmParameters.m_InputToCellWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_InputToCellWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_InputToOutputWeights = m_QuantizedLstmParameters.m_InputToOutputWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_InputToOutputWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_RecurrentToInputWeights = m_QuantizedLstmParameters.m_RecurrentToInputWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_RecurrentToInputWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_RecurrentToForgetWeights = m_QuantizedLstmParameters.m_RecurrentToForgetWeights
             ? std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_RecurrentToForgetWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_RecurrentToCellWeights = m_QuantizedLstmParameters.m_RecurrentToCellWeights ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_RecurrentToCellWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_RecurrentToOutputWeights = m_QuantizedLstmParameters.m_RecurrentToOutputWeights
             ? std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_RecurrentToOutputWeights) : nullptr;
     layer->m_QuantizedLstmParameters.m_InputGateBias = m_QuantizedLstmParameters.m_InputGateBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_InputGateBias) : nullptr;
     layer->m_QuantizedLstmParameters.m_ForgetGateBias = m_QuantizedLstmParameters.m_ForgetGateBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_ForgetGateBias) : nullptr;
     layer->m_QuantizedLstmParameters.m_CellBias = m_QuantizedLstmParameters.m_CellBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_CellBias) : nullptr;
     layer->m_QuantizedLstmParameters.m_OutputGateBias = m_QuantizedLstmParameters.m_OutputGateBias ?
             std::make_unique<ScopedCpuTensorHandle>(*m_QuantizedLstmParameters.m_OutputGateBias) : nullptr;
     return std::move(layer);
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the QuantizedLstm type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 22 of file QuantizedLstmLayer.cpp.
References IWorkloadFactory::CreateQuantizedLstm(), QuantizedLstmParameters::m_CellBias, QuantizedLstmQueueDescriptor::m_CellBias, QuantizedLstmParameters::m_ForgetGateBias, QuantizedLstmQueueDescriptor::m_ForgetGateBias, QuantizedLstmParameters::m_InputGateBias, QuantizedLstmQueueDescriptor::m_InputGateBias, QuantizedLstmParameters::m_InputToCellWeights, QuantizedLstmQueueDescriptor::m_InputToCellWeights, QuantizedLstmParameters::m_InputToForgetWeights, QuantizedLstmQueueDescriptor::m_InputToForgetWeights, QuantizedLstmParameters::m_InputToInputWeights, QuantizedLstmQueueDescriptor::m_InputToInputWeights, QuantizedLstmParameters::m_InputToOutputWeights, QuantizedLstmQueueDescriptor::m_InputToOutputWeights, QuantizedLstmParameters::m_OutputGateBias, QuantizedLstmQueueDescriptor::m_OutputGateBias, QuantizedLstmLayer::m_QuantizedLstmParameters, QuantizedLstmParameters::m_RecurrentToCellWeights, QuantizedLstmQueueDescriptor::m_RecurrentToCellWeights, QuantizedLstmParameters::m_RecurrentToForgetWeights, QuantizedLstmQueueDescriptor::m_RecurrentToForgetWeights, QuantizedLstmParameters::m_RecurrentToInputWeights, QuantizedLstmQueueDescriptor::m_RecurrentToInputWeights, QuantizedLstmParameters::m_RecurrentToOutputWeights, QuantizedLstmQueueDescriptor::m_RecurrentToOutputWeights, and Layer::PrepInfoAndDesc().
 {
     QuantizedLstmQueueDescriptor descriptor;
     // QuantizedLstmLayer parameters - there are no optional params
     descriptor.m_InputToInputWeights  = m_QuantizedLstmParameters.m_InputToInputWeights.get();
     descriptor.m_InputToForgetWeights = m_QuantizedLstmParameters.m_InputToForgetWeights.get();
     descriptor.m_InputToCellWeights   = m_QuantizedLstmParameters.m_InputToCellWeights.get();
     descriptor.m_InputToOutputWeights = m_QuantizedLstmParameters.m_InputToOutputWeights.get();
     descriptor.m_RecurrentToInputWeights  = m_QuantizedLstmParameters.m_RecurrentToInputWeights.get();
     descriptor.m_RecurrentToForgetWeights = m_QuantizedLstmParameters.m_RecurrentToForgetWeights.get();
     descriptor.m_RecurrentToCellWeights   = m_QuantizedLstmParameters.m_RecurrentToCellWeights.get();
     descriptor.m_RecurrentToOutputWeights = m_QuantizedLstmParameters.m_RecurrentToOutputWeights.get();
     descriptor.m_InputGateBias  = m_QuantizedLstmParameters.m_InputGateBias.get();
     descriptor.m_ForgetGateBias = m_QuantizedLstmParameters.m_ForgetGateBias.get();
     descriptor.m_CellBias       = m_QuantizedLstmParameters.m_CellBias.get();
     descriptor.m_OutputGateBias = m_QuantizedLstmParameters.m_OutputGateBias.get();
     return factory.CreateQuantizedLstm(descriptor, PrepInfoAndDesc(descriptor));
 }
GetConstantTensorsByRef()
Layer::ConstantTensors GetConstantTensorsByRef () override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 149 of file QuantizedLstmLayer.cpp.
References QuantizedLstmParameters::m_CellBias, QuantizedLstmParameters::m_ForgetGateBias, QuantizedLstmParameters::m_InputGateBias, QuantizedLstmParameters::m_InputToCellWeights, QuantizedLstmParameters::m_InputToForgetWeights, QuantizedLstmParameters::m_InputToInputWeights, QuantizedLstmParameters::m_InputToOutputWeights, QuantizedLstmParameters::m_OutputGateBias, QuantizedLstmLayer::m_QuantizedLstmParameters, QuantizedLstmParameters::m_RecurrentToCellWeights, QuantizedLstmParameters::m_RecurrentToForgetWeights, QuantizedLstmParameters::m_RecurrentToInputWeights, and QuantizedLstmParameters::m_RecurrentToOutputWeights.
 {
     return
     {
         m_QuantizedLstmParameters.m_InputToInputWeights,
         m_QuantizedLstmParameters.m_InputToForgetWeights,
         m_QuantizedLstmParameters.m_InputToCellWeights,
         m_QuantizedLstmParameters.m_InputToOutputWeights,
         m_QuantizedLstmParameters.m_RecurrentToInputWeights,
         m_QuantizedLstmParameters.m_RecurrentToForgetWeights,
         m_QuantizedLstmParameters.m_RecurrentToCellWeights,
         m_QuantizedLstmParameters.m_RecurrentToOutputWeights,
         m_QuantizedLstmParameters.m_InputGateBias,
         m_QuantizedLstmParameters.m_ForgetGateBias,
         m_QuantizedLstmParameters.m_CellBias,
         m_QuantizedLstmParameters.m_OutputGateBias
     };
 }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 79 of file QuantizedLstmLayer.cpp.
References ARMNN_ASSERT.
Referenced by QuantizedLstmInferOutputShapeImpl(), and QuantizedLstmLayer::ValidateTensorShapesFromInputs().
 {
     ARMNN_ASSERT(inputShapes.size() == 3);
     // Get input values for validation
     unsigned int numBatches = inputShapes[0][0];
     unsigned int outputSize = inputShapes[1][1];
     std::vector<TensorShape> outShapes;
     outShapes.push_back(TensorShape({numBatches, outputSize})); // cellStateOut
     outShapes.push_back(TensorShape({numBatches, outputSize})); // output
     return outShapes;
 }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of QuantizedLstmLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 94 of file QuantizedLstmLayer.cpp.
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), armnn::GetTensorInfo(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), QuantizedLstmLayer::InferOutputShapes(), QuantizedLstmParameters::m_CellBias, QuantizedLstmParameters::m_ForgetGateBias, QuantizedLstmParameters::m_InputGateBias, QuantizedLstmParameters::m_InputToCellWeights, QuantizedLstmParameters::m_InputToForgetWeights, QuantizedLstmParameters::m_InputToInputWeights, QuantizedLstmParameters::m_InputToOutputWeights, QuantizedLstmParameters::m_OutputGateBias, QuantizedLstmLayer::m_QuantizedLstmParameters, QuantizedLstmParameters::m_RecurrentToCellWeights, QuantizedLstmParameters::m_RecurrentToForgetWeights, QuantizedLstmParameters::m_RecurrentToInputWeights, QuantizedLstmParameters::m_RecurrentToOutputWeights, Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
 {
     VerifyLayerConnections(3, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     auto inferredShapes = InferOutputShapes(
     {
         GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape(), // input
         GetInputSlot(1).GetConnection()->GetTensorInfo().GetShape(), // previousCellStateIn
         GetInputSlot(2).GetConnection()->GetTensorInfo().GetShape()  // previousOutputIn
     });
     ARMNN_ASSERT(inferredShapes.size() == 2);
     // Check weights and bias for nullptr
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_InputToInputWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_InputToInputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_InputToForgetWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_InputToForgetWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_InputToCellWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_InputToCellWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_InputToOutputWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_InputToOutputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_RecurrentToInputWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_RecurrentToInputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_RecurrentToForgetWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_RecurrentToForgetWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_RecurrentToCellWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_RecurrentToCellWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_RecurrentToOutputWeights != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_RecurrentToOutputWeights should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_InputGateBias != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_InputGateBias should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_ForgetGateBias != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_ForgetGateBias should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_CellBias != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_CellBias should not be null.");
     ARMNN_ASSERT_MSG(m_QuantizedLstmParameters.m_OutputGateBias != nullptr,
                      "QuantizedLstmLayer: m_QuantizedLstmParameters.m_OutputGateBias should not be null.");
     // Check output TensorShape(s) match inferred shape
     ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "QuantizedLstmLayer");
     ValidateAndCopyShape(GetOutputSlot(1).GetTensorInfo().GetShape(),
                          inferredShapes[1],
                          m_ShapeInferenceMethod,
                          "QuantizedLstmLayer",
                          1);
 }
Member Data Documentation
m_QuantizedLstmParameters
QuantizedLstmParameters m_QuantizedLstmParameters
Definition at line 49 of file QuantizedLstmLayer.hpp.
Referenced by QuantizedLstmLayer::Accept(), Network::AddQuantizedLstmLayer(), QuantizedLstmLayer::Clone(), QuantizedLstmLayer::CreateWorkload(), QuantizedLstmLayer::GetConstantTensorsByRef(), and QuantizedLstmLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/QuantizedLstmLayer.hpp
src/armnn/layers/QuantizedLstmLayer.cpp