ArmNN: SendTimelinePacket Class Reference
SendTimelinePacket Class Reference
#include <SendTimelinePacket.hpp>
Public Member Functions
SendTimelinePacket (IBufferManager &bufferManager)
void Commit () override
Commits the current buffer and reset the member variables.
void SendTimelineEntityBinaryPacket (uint64_t profilingGuid) override
Create and write a TimelineEntityBinaryPacket from the parameters to the buffer.
void SendTimelineEventBinaryPacket (uint64_t timestamp, int threadId, uint64_t profilingGuid) override
Create and write a TimelineEventBinaryPacket from the parameters to the buffer.
void SendTimelineEventClassBinaryPacket (uint64_t profilingGuid, uint64_t nameGuid) override
Create and write a TimelineEventClassBinaryPacket from the parameters to the buffer.
void SendTimelineLabelBinaryPacket (uint64_t profilingGuid, const std::string &label) override
Create and write a TimelineLabelBinaryPacket from the parameters to the buffer.
void SendTimelineMessageDirectoryPackage () override
Create and write a TimelineMessageDirectoryPackage in the buffer.
virtual void SendTimelineRelationshipBinaryPacket (ProfilingRelationshipType relationshipType, uint64_t relationshipGuid, uint64_t headGuid, uint64_t tailGuid, uint64_t attributeGuid) override
Create and write a TimelineRelationshipBinaryPacket from the parameters to the buffer.
Public Member Functions inherited from ISendTimelinePacket
virtual ~ISendTimelinePacket ()
Detailed Description
Definition at line 22 of file SendTimelinePacket.hpp.
Constructor & Destructor Documentation
SendTimelinePacket()
SendTimelinePacket (IBufferManager & bufferManager) inline
Definition at line 25 of file SendTimelinePacket.hpp.
References ARMNN_ASSERT, armnn::profiling::BufferExhaustion, CHECK_LOCATION, SendTimelinePacket::Commit(), armnn::profiling::Error, SendTimelinePacket::SendTimelineEntityBinaryPacket(), SendTimelinePacket::SendTimelineEventBinaryPacket(), SendTimelinePacket::SendTimelineEventClassBinaryPacket(), SendTimelinePacket::SendTimelineLabelBinaryPacket(), SendTimelinePacket::SendTimelineMessageDirectoryPackage(), and SendTimelinePacket::SendTimelineRelationshipBinaryPacket().
       : m_BufferManager(bufferManager)
       , m_WriteBuffer(nullptr)
       , m_Offset(8u)
       , m_RemainingBufferSize(0u)
     {}
Member Function Documentation
Commit()
void Commit () override virtual
Commits the current buffer and reset the member variables.
Implements ISendTimelinePacket.
Definition at line 14 of file SendTimelinePacket.cpp.
References armnn::profiling::BufferExhaustion, CHECK_LOCATION, IBufferManager::Commit(), armnn::profiling::CreateTimelinePacketHeader(), MAX_METADATA_PACKET_LENGTH, IBufferManager::Reserve(), and armnn::profiling::WriteUint32().
Referenced by SendTimelinePacket::SendTimelineMessageDirectoryPackage(), and SendTimelinePacket::SendTimelinePacket().
 {
     if (m_WriteBuffer == nullptr)
     {
         // Can't commit from a null buffer
         return;
     }
     if (!m_DirectoryPackage)
     {
         // Datalength should be Offset minus the two header words
         m_PacketDataLength = m_Offset - m_uint32_t_size * 2;
         // Reset offset to prepend header with full packet datalength
         m_Offset = 0;
         // Add header before commit
         m_PacketHeader = CreateTimelinePacketHeader(1,0,1,0,0,m_PacketDataLength);
         // Write the timeline binary packet header to the buffer
         WriteUint32(m_WriteBuffer->GetWritableData(), m_Offset, m_PacketHeader.first);
         m_Offset += m_uint32_t_size;
         WriteUint32(m_WriteBuffer->GetWritableData(), m_Offset, m_PacketHeader.second);
         m_BufferManager.Commit(m_WriteBuffer, m_PacketDataLength + m_uint32_t_size * 2);
     }
     else
     {
         m_DirectoryPackage = false;
         m_BufferManager.Commit(m_WriteBuffer, m_Offset);
     }
     // Commit the message
     m_WriteBuffer.reset(nullptr);
     // Reset offset to start after prepended header
     m_Offset = 8;
     m_RemainingBufferSize = 0;
 }
SendTimelineEntityBinaryPacket()
void SendTimelineEntityBinaryPacket (uint64_t profilingGuid) override virtual
Create and write a TimelineEntityBinaryPacket from the parameters to the buffer.
Implements ISendTimelinePacket.
Definition at line 85 of file SendTimelinePacket.cpp.
References armnn::profiling::WriteTimelineEntityBinary().
Referenced by SendTimelinePacket::SendTimelinePacket().
 {
     ForwardWriteBinaryFunction(WriteTimelineEntityBinary,
                                profilingGuid);
 }
SendTimelineEventBinaryPacket()
void SendTimelineEventBinaryPacket (uint64_t timestamp, int threadId, uint64_t profilingGuid) override virtual
Create and write a TimelineEventBinaryPacket from the parameters to the buffer.
Implements ISendTimelinePacket.
Definition at line 91 of file SendTimelinePacket.cpp.
References armnn::profiling::WriteTimelineEventBinary().
Referenced by SendTimelinePacket::SendTimelinePacket().
 {
     ForwardWriteBinaryFunction(WriteTimelineEventBinary,
                                timestamp,
                                threadId,
                                profilingGuid);
 }
SendTimelineEventClassBinaryPacket()
void SendTimelineEventClassBinaryPacket (uint64_t profilingGuid, uint64_t nameGuid) override virtual
Create and write a TimelineEventClassBinaryPacket from the parameters to the buffer.
Implements ISendTimelinePacket.
Definition at line 101 of file SendTimelinePacket.cpp.
References armnn::profiling::WriteTimelineEventClassBinary().
Referenced by SendTimelinePacket::SendTimelinePacket().
 {
     ForwardWriteBinaryFunction(WriteTimelineEventClassBinary,
                                profilingGuid,
                                nameGuid);
 }
SendTimelineLabelBinaryPacket()
void SendTimelineLabelBinaryPacket (uint64_t profilingGuid, const std::string & label) override virtual
Create and write a TimelineLabelBinaryPacket from the parameters to the buffer.
Implements ISendTimelinePacket.
Definition at line 108 of file SendTimelinePacket.cpp.
References armnn::profiling::WriteTimelineLabelBinaryPacket().
Referenced by SendTimelinePacket::SendTimelinePacket().
 {
     ForwardWriteBinaryFunction(WriteTimelineLabelBinaryPacket,
                                profilingGuid,
                                label);
 }
SendTimelineMessageDirectoryPackage()
void SendTimelineMessageDirectoryPackage () override virtual
Create and write a TimelineMessageDirectoryPackage in the buffer.
Implements ISendTimelinePacket.
Definition at line 129 of file SendTimelinePacket.cpp.
References CHECK_LOCATION, SendTimelinePacket::Commit(), armnn::profiling::Ok, and armnn::profiling::WriteTimelineMessageDirectoryPackage().
Referenced by ActivateTimelineReportingCommandHandler::operator()(), and SendTimelinePacket::SendTimelinePacket().
 {
     try
     {
         // Flag to Reserve & Commit() that a DirectoryPackage is being sent
         m_DirectoryPackage = true;
         // Reserve buffer if it hasn't already been reserved
         ReserveBuffer();
         // Write to buffer
         unsigned int numberOfBytesWritten = 0;
         // Offset is initialised to 8
         m_Offset = 0;
         TimelinePacketStatus result = WriteTimelineMessageDirectoryPackage(&m_WriteBuffer->GetWritableData()[m_Offset],
                                                                            m_RemainingBufferSize,
                                                                            numberOfBytesWritten);
         if (result != armnn::profiling::TimelinePacketStatus::Ok)
         {
             throw RuntimeException("Error processing TimelineMessageDirectoryPackage", CHECK_LOCATION());
         }
         // Commit the message
         m_Offset     += numberOfBytesWritten;
         m_RemainingBufferSize -= numberOfBytesWritten;
         Commit();
     }
     catch (...)
     {
         throw RuntimeException("Error processing TimelineMessageDirectoryPackage", CHECK_LOCATION());
     }
 }
SendTimelineRelationshipBinaryPacket()
void SendTimelineRelationshipBinaryPacket (ProfilingRelationshipType relationshipType, uint64_t relationshipGuid, uint64_t headGuid, uint64_t tailGuid, uint64_t attributeGuid) override virtual
Create and write a TimelineRelationshipBinaryPacket from the parameters to the buffer.
Implements ISendTimelinePacket.
Definition at line 115 of file SendTimelinePacket.cpp.
References armnn::profiling::WriteTimelineRelationshipBinary().
Referenced by SendTimelinePacket::SendTimelinePacket().
 {
     ForwardWriteBinaryFunction(WriteTimelineRelationshipBinary,
                                relationshipType,
                                relationshipGuid,
                                headGuid,
                                tailGuid,
                                attributeGuid);
 }
The documentation for this class was generated from the following files:
src/profiling/SendTimelinePacket.hpp
src/profiling/SendTimelinePacket.cpp