ArmNN: CaffePreprocessor Class Reference
CaffePreprocessor Class Reference
#include <CaffePreprocessor.hpp>
Public Types
using DataType = float
using TTestCaseData = ClassifierTestCaseData< DataType >
Public Member Functions
CaffePreprocessor (const std::string &binaryFileDirectory, unsigned int width=227, unsigned int height=227, const std::vector< ImageSet > &imageSet=std::vector< ImageSet >())
std::unique_ptr< TTestCaseData > GetTestCaseData (unsigned int testCaseId)
Detailed Description
Definition at line 18 of file CaffePreprocessor.hpp.
Member Typedef Documentation
DataType
using DataType = float
Definition at line 21 of file CaffePreprocessor.hpp.
TTestCaseData
using TTestCaseData = ClassifierTestCaseData<DataType>
Definition at line 22 of file CaffePreprocessor.hpp.
Constructor & Destructor Documentation
CaffePreprocessor()
CaffePreprocessor (const std::string & binaryFileDirectory, unsigned int width = 227, unsigned int height = 227, const std::vector< ImageSet > & imageSet = std::vector<ImageSet>()) explicit
Definition at line 20 of file CaffePreprocessor.cpp.
 :   m_BinaryDirectory(binaryFileDirectory)
 ,   m_Height(height)
 ,   m_Width(width)
 ,   m_ImageSet(imageSet.empty() ? g_DefaultImageSet : imageSet)
 {
 }
Member Function Documentation
GetTestCaseData()
std::unique_ptr< CaffePreprocessor::TTestCaseData > GetTestCaseData (unsigned int testCaseId)
Definition at line 29 of file CaffePreprocessor.cpp.
References Bgr, CHECK_LOCATION, GetImageDataInArmNnLayoutAsFloatsSubtractingMean(), armnn::numeric_cast(), and InferenceTestImage::Resize().
 {
     testCaseId = testCaseId % boost::numeric_cast<unsigned int>(m_ImageSet.size());
     const ImageSet& imageSet = m_ImageSet[testCaseId];
     const std::string fullPath = m_BinaryDirectory + imageSet.first;
     InferenceTestImage image(fullPath.c_str());
     image.Resize(m_Width, m_Height, CHECK_LOCATION());
     // The model expects image data in BGR format.
     std::vector<float> inputImageData = GetImageDataInArmNnLayoutAsFloatsSubtractingMean(ImageChannelLayout::Bgr,
                                                                                          image, m_MeanBgr);
     // List of labels: https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a
     const unsigned int label = imageSet.second;
     return std::make_unique<TTestCaseData>(label, std::move(inputImageData));
 }
The documentation for this class was generated from the following files:
tests/CaffePreprocessor.hpp
tests/CaffePreprocessor.cpp