ArmNN: TfLiteParser Class Reference
TfLiteParser Class Reference
#include <TfLiteParser.hpp>
Public Types
using ModelPtr = std::unique_ptr< tflite::ModelT >
using SubgraphPtr = std::unique_ptr< tflite::SubGraphT >
using OperatorPtr = std::unique_ptr< tflite::OperatorT >
using OperatorCodePtr = std::unique_ptr< tflite::OperatorCodeT >
using TensorPtr = std::unique_ptr< tflite::TensorT >
using TensorRawPtr = const tflite::TensorT *
using TensorRawPtrVector = std::vector< TensorRawPtr >
using TensorIdRawPtr = std::pair< size_t, TensorRawPtr >
using TensorIdRawPtrVector = std::vector< TensorIdRawPtr >
using BufferPtr = std::unique_ptr< tflite::BufferT >
using BufferRawPtr = const tflite::BufferT *
Public Member Functions
virtual armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile) override
Create the network from a flatbuffers binary file on disk.
virtual armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent) override
Create the network from a flatbuffers binary.
virtual BindingPointInfo GetNetworkInputBindingInfo (size_t subgraphId, const std::string &name) const override
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and subgraph id.
virtual BindingPointInfo GetNetworkOutputBindingInfo (size_t subgraphId, const std::string &name) const override
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and subgraph id.
virtual size_t GetSubgraphCount () const override
Return the number of subgraphs in the parsed model.
virtual std::vector< std::string > GetSubgraphInputTensorNames (size_t subgraphId) const override
Return the input tensor names for a given subgraph.
virtual std::vector< std::string > GetSubgraphOutputTensorNames (size_t subgraphId) const override
Return the output tensor names for a given subgraph.
TfLiteParser (const armnn::Optional< ITfLiteParser::TfLiteParserOptions > &options=armnn::EmptyOptional())
virtual ~TfLiteParser ()
Static Public Member Functions
static ModelPtr LoadModelFromFile (const char *fileName)
static ModelPtr LoadModelFromBinary (const uint8_t *binaryContent, size_t len)
static TensorRawPtrVector GetInputs (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static TensorRawPtrVector GetOutputs (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static TensorIdRawPtrVector GetSubgraphInputs (const ModelPtr &model, size_t subgraphIndex)
static TensorIdRawPtrVector GetSubgraphOutputs (const ModelPtr &model, size_t subgraphIndex)
static std::vector< int32_t > & GetInputTensorIds (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static std::vector< int32_t > & GetOutputTensorIds (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static BufferRawPtr GetBuffer (const ModelPtr &model, size_t bufferIndex)
static armnn::TensorInfo OutputShapeOfSqueeze (const std::vector< uint32_t > &squeezeDims, const armnn::TensorInfo &inputTensorInfo)
static armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo &inputTensorInfo, const std::vector< int32_t > &targetDimsIn)
Static Public Member Functions inherited from ITfLiteParser
static ITfLiteParser * CreateRaw (const armnn::Optional< TfLiteParserOptions > &options=armnn::EmptyOptional())
static ITfLiteParserPtr Create (const armnn::Optional< TfLiteParserOptions > &options=armnn::EmptyOptional())
static void Destroy (ITfLiteParser *parser)
Additional Inherited Members
Protected Member Functions inherited from ITfLiteParser
virtual ~ITfLiteParser ()
Detailed Description
Definition at line 19 of file TfLiteParser.hpp.
Member Typedef Documentation
BufferPtr
using BufferPtr = std::unique_ptr<tflite::BufferT>
Definition at line 32 of file TfLiteParser.hpp.
BufferRawPtr
using BufferRawPtr = const tflite::BufferT *
Definition at line 33 of file TfLiteParser.hpp.
ModelPtr
using ModelPtr = std::unique_ptr<tflite::ModelT>
Definition at line 23 of file TfLiteParser.hpp.
OperatorCodePtr
using OperatorCodePtr = std::unique_ptr<tflite::OperatorCodeT>
Definition at line 26 of file TfLiteParser.hpp.
OperatorPtr
using OperatorPtr = std::unique_ptr<tflite::OperatorT>
Definition at line 25 of file TfLiteParser.hpp.
SubgraphPtr
using SubgraphPtr = std::unique_ptr<tflite::SubGraphT>
Definition at line 24 of file TfLiteParser.hpp.
TensorIdRawPtr
using TensorIdRawPtr = std::pair<size_t, TensorRawPtr>
Definition at line 30 of file TfLiteParser.hpp.
TensorIdRawPtrVector
using TensorIdRawPtrVector = std::vector<TensorIdRawPtr>
Definition at line 31 of file TfLiteParser.hpp.
TensorPtr
using TensorPtr = std::unique_ptr<tflite::TensorT>
Definition at line 27 of file TfLiteParser.hpp.
TensorRawPtr
using TensorRawPtr = const tflite::TensorT *
Definition at line 28 of file TfLiteParser.hpp.
TensorRawPtrVector
using TensorRawPtrVector = std::vector<TensorRawPtr>
Definition at line 29 of file TfLiteParser.hpp.
Constructor & Destructor Documentation
TfLiteParser()
TfLiteParser (const armnn::Optional< ITfLiteParser::TfLiteParserOptions > & options = armnn::EmptyOptional())
Definition at line 555 of file TfLiteParser.cpp.
References ARMNN_ASSERT, CHECK_MODEL, CHECKED_NON_NEGATIVE, IOutputSlot::Connect(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetName(), TensorInfo::GetNumDimensions(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), ReshapeDescriptor::m_TargetShape, TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), and armnnDeserializer::ToTensorInfo().
Referenced by ITfLiteParser::CreateRaw(), and TfLiteParser::~TfLiteParser().
 : m_Options(options)
 , m_Network(nullptr, nullptr)
 , m_ParserFunctions(tflite::BuiltinOperator_MAX+1, &TfLiteParser::ParseUnsupportedOperator)
 {
     // register supported operators
     m_ParserFunctions[tflite::BuiltinOperator_ADD]                     = &TfLiteParser::ParseAdd;
     m_ParserFunctions[tflite::BuiltinOperator_AVERAGE_POOL_2D]         = &TfLiteParser::ParseAveragePool2D;
     m_ParserFunctions[tflite::BuiltinOperator_BATCH_TO_SPACE_ND]       = &TfLiteParser::ParseBatchToSpaceND;
     m_ParserFunctions[tflite::BuiltinOperator_CONCATENATION]           = &TfLiteParser::ParseConcatenation;
     m_ParserFunctions[tflite::BuiltinOperator_CONV_2D]                 = &TfLiteParser::ParseConv2D;
     m_ParserFunctions[tflite::BuiltinOperator_CUSTOM]                  = &TfLiteParser::ParseCustomOperator;
     m_ParserFunctions[tflite::BuiltinOperator_DEPTHWISE_CONV_2D]       = &TfLiteParser::ParseDepthwiseConv2D;
     m_ParserFunctions[tflite::BuiltinOperator_DEQUANTIZE]              = &TfLiteParser::ParseDequantize;
     m_ParserFunctions[tflite::BuiltinOperator_EXP]                     = &TfLiteParser::ParseExp;
     m_ParserFunctions[tflite::BuiltinOperator_FULLY_CONNECTED]         = &TfLiteParser::ParseFullyConnected;
     m_ParserFunctions[tflite::BuiltinOperator_HARD_SWISH]              = &TfLiteParser::ParseHardSwish;
     m_ParserFunctions[tflite::BuiltinOperator_LEAKY_RELU]              = &TfLiteParser::ParseLeakyRelu;
     m_ParserFunctions[tflite::BuiltinOperator_LOGISTIC]                = &TfLiteParser::ParseLogistic;
     m_ParserFunctions[tflite::BuiltinOperator_L2_NORMALIZATION]        = &TfLiteParser::ParseL2Normalization;
     m_ParserFunctions[tflite::BuiltinOperator_MAX_POOL_2D]             = &TfLiteParser::ParseMaxPool2D;
     m_ParserFunctions[tflite::BuiltinOperator_MAXIMUM]                 = &TfLiteParser::ParseMaximum;
     m_ParserFunctions[tflite::BuiltinOperator_MEAN]                    = &TfLiteParser::ParseMean;
     m_ParserFunctions[tflite::BuiltinOperator_MINIMUM]                 = &TfLiteParser::ParseMinimum;
     m_ParserFunctions[tflite::BuiltinOperator_MUL]                     = &TfLiteParser::ParseMul;
     m_ParserFunctions[tflite::BuiltinOperator_NEG]                     = &TfLiteParser::ParseNeg;
     m_ParserFunctions[tflite::BuiltinOperator_PACK]                    = &TfLiteParser::ParsePack;
     m_ParserFunctions[tflite::BuiltinOperator_PAD]                     = &TfLiteParser::ParsePad;
     m_ParserFunctions[tflite::BuiltinOperator_QUANTIZE]                = &TfLiteParser::ParseQuantize;
     m_ParserFunctions[tflite::BuiltinOperator_RELU]                    = &TfLiteParser::ParseRelu;
     m_ParserFunctions[tflite::BuiltinOperator_RELU6]                   = &TfLiteParser::ParseRelu6;
     m_ParserFunctions[tflite::BuiltinOperator_RESHAPE]                 = &TfLiteParser::ParseReshape;
     m_ParserFunctions[tflite::BuiltinOperator_RESIZE_BILINEAR]         = &TfLiteParser::ParseResizeBilinear;
     m_ParserFunctions[tflite::BuiltinOperator_RESIZE_NEAREST_NEIGHBOR] = &TfLiteParser::ParseResizeNearestNeighbor;
     m_ParserFunctions[tflite::BuiltinOperator_SLICE]                   = &TfLiteParser::ParseSlice;
     m_ParserFunctions[tflite::BuiltinOperator_SOFTMAX]                 = &TfLiteParser::ParseSoftmax;
     m_ParserFunctions[tflite::BuiltinOperator_SPACE_TO_BATCH_ND]       = &TfLiteParser::ParseSpaceToBatchND;
     m_ParserFunctions[tflite::BuiltinOperator_SPLIT]                   = &TfLiteParser::ParseSplit;
     m_ParserFunctions[tflite::BuiltinOperator_SPLIT_V]                 = &TfLiteParser::ParseSplitV;
     m_ParserFunctions[tflite::BuiltinOperator_SQUEEZE]                 = &TfLiteParser::ParseSqueeze;
     m_ParserFunctions[tflite::BuiltinOperator_STRIDED_SLICE]           = &TfLiteParser::ParseStridedSlice;
     m_ParserFunctions[tflite::BuiltinOperator_SUB]                     = &TfLiteParser::ParseSub;
     m_ParserFunctions[tflite::BuiltinOperator_TANH]                    = &TfLiteParser::ParseTanH;
     m_ParserFunctions[tflite::BuiltinOperator_TRANSPOSE]               = &TfLiteParser::ParseTranspose;
     m_ParserFunctions[tflite::BuiltinOperator_TRANSPOSE_CONV]          = &TfLiteParser::ParseTransposeConv;
     m_ParserFunctions[tflite::BuiltinOperator_UNPACK]                  = &TfLiteParser::ParseUnpack;
     m_ParserFunctions[tflite::BuiltinOperator_DIV]                     = &TfLiteParser::ParseDiv;
     // register supported custom operators
     m_CustomParserFunctions["TFLite_Detection_PostProcess"]      = &TfLiteParser::ParseDetectionPostProcess;
 }
~TfLiteParser()
virtual ~TfLiteParser () inline virtual
Definition at line 63 of file TfLiteParser.hpp.
References TfLiteParser::GetBuffer(), TfLiteParser::GetInputs(), TfLiteParser::GetInputTensorIds(), TfLiteParser::GetOutputs(), TfLiteParser::GetOutputTensorIds(), TfLiteParser::GetSubgraphInputs(), TfLiteParser::GetSubgraphOutputs(), TfLiteParser::LoadModelFromBinary(), TfLiteParser::LoadModelFromFile(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), and TfLiteParser::TfLiteParser().
 {}
Member Function Documentation
CreateNetworkFromBinary()
INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent) override virtual
Create the network from a flatbuffers binary.
Implements ITfLiteParser.
Definition at line 683 of file TfLiteParser.cpp.
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, ARMNN_LOG, armnnTfParser::CalcPadding(), CHECK_LOCATION, CHECK_MODEL, CHECK_SUPPORTED_FUSED_ACTIVATION, CHECK_TENSOR, CHECK_VALID_SIZE, CHECKED_NON_NEGATIVE, armnn::error, TfLiteParser::GetBuffer(), TensorInfo::GetDataType(), TfLiteParser::GetInputs(), TfLiteParser::GetInputTensorIds(), TensorInfo::GetNumBytes(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TfLiteParser::GetOutputs(), IConnectableLayer::GetOutputSlot(), TfLiteParser::GetOutputTensorIds(), TensorInfo::GetShape(), TfLiteParser::LoadModelFromBinary(), SoftmaxDescriptor::m_Beta, Convolution2dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, TransposeConvolution2dDescriptor::m_BiasEnabled, BatchToSpaceNdDescriptor::m_BlockShape, SpaceToBatchNdDescriptor::m_BlockShape, BatchToSpaceNdDescriptor::m_Crops, Pooling2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, L2NormalizationDescriptor::m_DataLayout, BatchToSpaceNdDescriptor::m_DataLayout, SpaceToBatchNdDescriptor::m_DataLayout, TransposeConvolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_DilationX, DepthwiseConvolution2dDescriptor::m_DilationX, Convolution2dDescriptor::m_DilationY, DepthwiseConvolution2dDescriptor::m_DilationY, ElementwiseUnaryDescriptor::m_Operation, TransposeConvolution2dDescriptor::m_OutputShape, TransposeConvolution2dDescriptor::m_OutputShapeEnabled, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, TransposeConvolution2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, TransposeConvolution2dDescriptor::m_PadLeft, SpaceToBatchNdDescriptor::m_PadList, Pooling2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, TransposeConvolution2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Convolution2dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, TransposeConvolution2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, TransposeConvolution2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, Convolution2dDescriptor::m_StrideY, DepthwiseConvolution2dDescriptor::m_StrideY, TransposeConvolution2dDescriptor::m_StrideY, armnn::NHWC, armnn::numeric_cast(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToTensorInfo(), and Exception::what().
 {
     ResetParser();
     m_Model = LoadModelFromBinary(binaryContent.data(), binaryContent.size());
     return CreateNetworkFromModel();
 }
CreateNetworkFromBinaryFile()
INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile) override virtual
Create the network from a flatbuffers binary file on disk.
Implements ITfLiteParser.
Definition at line 676 of file TfLiteParser.cpp.
References TfLiteParser::LoadModelFromFile().
 {
     ResetParser();
     m_Model = LoadModelFromFile(graphFile);
     return CreateNetworkFromModel();
 }
GetBuffer()
TfLiteParser::BufferRawPtr GetBuffer (const ModelPtr & model, size_t bufferIndex) static
Definition at line 3303 of file TfLiteParser.cpp.
References CHECK_BUFFER, CHECK_BUFFER_SIZE, CHECK_LOCATION, CHECK_TENSOR_PTR, armnn::Float32, TensorInfo::GetDataType(), armnn::GetDataTypeName(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS8, and armnn::Signed32.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParser::CreateNetworkFromBinary(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_BUFFER(model, bufferIndex);
     return model->buffers[bufferIndex].get();
 }
GetInputs()
TfLiteParser::TensorRawPtrVector GetInputs (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 3084 of file TfLiteParser.cpp.
References CHECK_MODEL, and CHECKED_NON_NEGATIVE.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParser::CreateNetworkFromBinary(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto & subgraphPtr = model->subgraphs[subgraphIndex];
     const auto & operatorPtr = subgraphPtr->operators[operatorIndex];
     size_t inputCount = operatorPtr->inputs.size();
     TensorRawPtrVector result(inputCount);
     for (size_t i=0; i<inputCount; ++i)
     {
         uint32_t inputId = CHECKED_NON_NEGATIVE(operatorPtr->inputs[i]);
         result[i] = subgraphPtr->tensors[inputId].get();
     }
     return result;
 }
GetInputTensorIds()
std::vector< int32_t > & GetInputTensorIds (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 3156 of file TfLiteParser.cpp.
References CHECK_MODEL.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParser::CreateNetworkFromBinary(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto & subgraphPtr = model->subgraphs[subgraphIndex];
     const auto & operatorPtr = subgraphPtr->operators[operatorIndex];
     return operatorPtr->inputs;
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (size_t subgraphId, const std::string & name) const override virtual
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and subgraph id.
Implements ITfLiteParser.
Definition at line 3372 of file TfLiteParser.cpp.
References CHECK_LOCATION, CHECK_SUBGRAPH, TfLiteParser::GetSubgraphInputs(), and armnnDeserializer::ToTensorInfo().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto inputs = GetSubgraphInputs(m_Model, subgraphId);
     for (auto const & input : inputs)
     {
         if (input.second->name == name)
         {
             auto bindingId = GenerateLayerBindingId(subgraphId, input.first);
             return std::make_pair(bindingId, ToTensorInfo(input.second));
         }
     }
     std::stringstream bindings;
     for (auto const & input : inputs)
     {
         bindings << "'" << input.second->name << "' ";
     }
     throw ParseException(
         boost::str(
             boost::format("No input binding found for subgraph:%1% and name:%2%. "
                           "Possible inputs are: [%3%] %4%") %
             subgraphId %
             name %
             bindings.str() %
             CHECK_LOCATION().AsString()));
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (size_t subgraphId, const std::string & name) const override virtual
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and subgraph id.
Implements ITfLiteParser.
Definition at line 3402 of file TfLiteParser.cpp.
References CHECK_LOCATION, CHECK_SUBGRAPH, TfLiteParser::GetSubgraphOutputs(), and armnnDeserializer::ToTensorInfo().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto outputs = GetSubgraphOutputs(m_Model, subgraphId);
     for (unsigned int i = 0; i < outputs.size(); ++i)
     {
         auto const output = outputs[i];
         if (output.second->name == name)
         {
             auto bindingId = GenerateLayerBindingId(subgraphId, output.first);
             std::vector<unsigned int> shape = m_OverridenOutputShapes.size() > 0 ?
                                                 m_OverridenOutputShapes[i] : AsUnsignedVector(output.second->shape);
             return std::make_pair(bindingId, ToTensorInfo(output.second, shape));
         }
     }
     std::stringstream bindings;
     for (auto const & output : outputs)
     {
         bindings << "'" << output.second->name << "' ";
     }
     throw ParseException(
         boost::str(
             boost::format("No output binding found for subgraph:%1% and name:%2%. "
                           "Possible outputs are: [%3%] %4%") %
             subgraphId %
             name %
             bindings.str() %
             CHECK_LOCATION().AsString()));
 }
GetOutputs()
TfLiteParser::TensorRawPtrVector GetOutputs (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 3103 of file TfLiteParser.cpp.
References CHECK_MODEL, CHECK_TENSOR, and CHECKED_NON_NEGATIVE.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParser::CreateNetworkFromBinary(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto & subgraphPtr = model->subgraphs[subgraphIndex];
     const auto & operatorPtr = subgraphPtr->operators[operatorIndex];
     size_t outputCount = operatorPtr->outputs.size();
     TensorRawPtrVector result(outputCount);
     for (size_t i=0; i<outputCount; ++i)
     {
         uint32_t outputId = CHECKED_NON_NEGATIVE(operatorPtr->outputs[i]);
         CHECK_TENSOR(model, subgraphIndex, outputId);
         result[i] = subgraphPtr->tensors[outputId].get();
     }
     return result;
 }
GetOutputTensorIds()
std::vector< int32_t > & GetOutputTensorIds (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 3166 of file TfLiteParser.cpp.
References ARMNN_ASSERT, CHECK_LOCATION, CHECK_MODEL, CHECK_SUBGRAPH, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetNumOutputSlots(), IConnectableLayer::GetOutputSlot(), TfLiteParser::GetSubgraphInputs(), TfLiteParser::GetSubgraphOutputs(), IOutputSlot::SetTensorInfo(), and armnnDeserializer::ToTensorInfo().
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParser::CreateNetworkFromBinary(), TfLiteParser::OutputShapeOfReshape(), TfLiteParser::OutputShapeOfSqueeze(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto & subgraphPtr = model->subgraphs[subgraphIndex];
     const auto & operatorPtr = subgraphPtr->operators[operatorIndex];
     return operatorPtr->outputs;
 }
GetSubgraphCount()
size_t GetSubgraphCount () const override virtual
Return the number of subgraphs in the parsed model.
Implements ITfLiteParser.
Definition at line 3435 of file TfLiteParser.cpp.
 {
     return m_Model->subgraphs.size();
 }
GetSubgraphInputs()
TfLiteParser::TensorIdRawPtrVector GetSubgraphInputs (const ModelPtr & model, size_t subgraphIndex) static
Definition at line 3123 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, CHECK_TENSOR, and CHECKED_NON_NEGATIVE.
Referenced by TfLiteParser::GetNetworkInputBindingInfo(), TfLiteParser::GetOutputTensorIds(), TfLiteParser::GetSubgraphInputTensorNames(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_SUBGRAPH(model, subgraphIndex);
     const auto & subgraphPtr = model->subgraphs[subgraphIndex];
     size_t inputCount = subgraphPtr->inputs.size();
     TensorIdRawPtrVector result(inputCount);
     for (size_t i=0; i<inputCount; ++i)
     {
         uint32_t inputId = CHECKED_NON_NEGATIVE(subgraphPtr->inputs[i]);
         CHECK_TENSOR(model, subgraphIndex, inputId);
         result[i] = std::make_pair(inputId, subgraphPtr->tensors[inputId].get());
     }
     return result;
 }
GetSubgraphInputTensorNames()
std::vector< std::string > GetSubgraphInputTensorNames (size_t subgraphId) const override virtual
Return the input tensor names for a given subgraph.
Implements ITfLiteParser.
Definition at line 3440 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, and TfLiteParser::GetSubgraphInputs().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto inputs = GetSubgraphInputs(m_Model, subgraphId);
     std::vector<std::string> result;
     result.reserve(inputs.size());
     for (auto const & input : inputs)
     {
         result.push_back(input.second->name);
     }
     return result;
 }
GetSubgraphOutputs()
TfLiteParser::TensorIdRawPtrVector GetSubgraphOutputs (const ModelPtr & model, size_t subgraphIndex) static
Definition at line 3140 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, and CHECKED_NON_NEGATIVE.
Referenced by TfLiteParser::GetNetworkOutputBindingInfo(), TfLiteParser::GetOutputTensorIds(), TfLiteParser::GetSubgraphOutputTensorNames(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_SUBGRAPH(model, subgraphIndex);
     const auto & subgraphPtr = model->subgraphs[subgraphIndex];
     size_t outputCount = subgraphPtr->outputs.size();
     TensorIdRawPtrVector result(outputCount);
     for (size_t i=0; i<outputCount; ++i)
     {
         uint32_t outputId = CHECKED_NON_NEGATIVE(subgraphPtr->outputs[i]);
         result[i] = std::make_pair(outputId, subgraphPtr->tensors[outputId].get());
     }
     return result;
 }
GetSubgraphOutputTensorNames()
std::vector< std::string > GetSubgraphOutputTensorNames (size_t subgraphId) const override virtual
Return the output tensor names for a given subgraph.
Implements ITfLiteParser.
Definition at line 3453 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, and TfLiteParser::GetSubgraphOutputs().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto outputs = GetSubgraphOutputs(m_Model, subgraphId);
     std::vector<std::string> result;
     result.reserve(outputs.size());
     for (auto const & output : outputs)
     {
         result.push_back(output.second->name);
     }
     return result;
 }
LoadModelFromBinary()
TfLiteParser::ModelPtr LoadModelFromBinary (const uint8_t * binaryContent, size_t len) static
Definition at line 3065 of file TfLiteParser.cpp.
References CHECK_LOCATION.
Referenced by TfLiteParser::CreateNetworkFromBinary(), TfLiteParser::LoadModelFromFile(), and TfLiteParser::~TfLiteParser().
 {
     if (binaryContent == nullptr)
      {
         throw InvalidArgumentException(boost::str(boost::format("Invalid (null) binary content %1%") %
                                        CHECK_LOCATION().AsString()));
      }
     flatbuffers::Verifier verifier(binaryContent, len);
     if (verifier.VerifyBuffer<tflite::Model>() == false)
     {
         throw ParseException(
             boost::str(boost::format("Buffer doesn't conform to the expected Tensorflow Lite "
                                      "flatbuffers format. size:%1% %2%") %
                        len %
                        CHECK_LOCATION().AsString()));
     }
     return tflite::UnPackModel(binaryContent);
 }
LoadModelFromFile()
TfLiteParser::ModelPtr LoadModelFromFile (const char * fileName) static
Definition at line 3041 of file TfLiteParser.cpp.
References CHECK_LOCATION, and TfLiteParser::LoadModelFromBinary().
Referenced by TfLiteParser::CreateNetworkFromBinaryFile(), and TfLiteParser::~TfLiteParser().
 {
     if (fileName == nullptr)
     {
         throw InvalidArgumentException(boost::str(boost::format("Invalid (null) file name %1%") %
                                        CHECK_LOCATION().AsString()));
     }
     std::error_code errorCode;
     fs::path pathToFile(fileName);
     if (!fs::exists(pathToFile, errorCode))
     {
         std::string locationString = CHECK_LOCATION().AsString();
         std::string msg = boost::str(boost::format("Cannot find the file (%1%) errorCode: %2% %3%") %
                                      fileName %
                                      errorCode %
                                          locationString);
         throw FileNotFoundException(msg);
     }
     std::ifstream file(fileName, std::ios::binary);
     std::string fileContent((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
     return LoadModelFromBinary(reinterpret_cast<const uint8_t *>(fileContent.c_str()),
                                fileContent.size());
 }
OutputShapeOfReshape()
armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo & inputTensorInfo, const std::vector< int32_t > & targetDimsIn) static
Definition at line 2151 of file TfLiteParser.cpp.
References ARMNN_ASSERT, ARMNN_THROW_PARSE_EXCEPTION, CHECK_LOCATION, CHECK_MODEL, CHECK_SUPPORTED_FUSED_ACTIVATION, CHECK_VALID_SIZE, CHECKED_NON_NEGATIVE, armnnDeserializer::CheckShape(), IOutputSlot::Connect(), TfLiteParser::GetBuffer(), TensorInfo::GetDataType(), TfLiteParser::GetInputs(), IConnectableLayer::GetInputSlot(), TfLiteParser::GetInputTensorIds(), IConnectableLayer::GetName(), TensorInfo::GetNumBytes(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), IConnectableLayer::GetNumOutputSlots(), TfLiteParser::GetOutputs(), IConnectableLayer::GetOutputSlot(), TfLiteParser::GetOutputTensorIds(), TensorInfo::GetQuantizationOffset(), TensorInfo::GetQuantizationScale(), TensorInfo::GetShape(), StackDescriptor::m_Axis, FullyConnectedDescriptor::m_BiasEnabled, DetectionPostProcessDescriptor::m_DetectionsPerClass, StackDescriptor::m_InputShape, DetectionPostProcessDescriptor::m_MaxClassesPerDetection, DetectionPostProcessDescriptor::m_MaxDetections, ResizeDescriptor::m_Method, DetectionPostProcessDescriptor::m_NmsIouThreshold, DetectionPostProcessDescriptor::m_NmsScoreThreshold, DetectionPostProcessDescriptor::m_NumClasses, StackDescriptor::m_NumInputs, DetectionPostProcessDescriptor::m_ScaleH, DetectionPostProcessDescriptor::m_ScaleW, DetectionPostProcessDescriptor::m_ScaleX, DetectionPostProcessDescriptor::m_ScaleY, ReshapeDescriptor::m_TargetShape, FullyConnectedDescriptor::m_TransposeWeightMatrix, DetectionPostProcessDescriptor::m_UseRegularNms, armnn::MaxNumOfTensorDimensions, armnn::NHWC, armnn::numeric_cast(), armnnUtils::ProcessConcatInputTensorInfo(), OriginsDescriptor::SetConcatAxis(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), ViewsDescriptor::SetViewOriginCoord(), ViewsDescriptor::SetViewSize(), and armnnDeserializer::ToTensorInfo().
Referenced by TfLiteParser::~TfLiteParser().
 {
     std::vector<unsigned int> outputDims(targetDimsIn.begin(), targetDimsIn.end());
     const auto stretchDim = std::find(targetDimsIn.begin(), targetDimsIn.end(), -1);
     if (stretchDim != targetDimsIn.end())
     {
         if (std::find(std::next(stretchDim), targetDimsIn.end(), -1) != targetDimsIn.end())
         {
             throw ParseException(
                 boost::str(
                     boost::format("At most one component of shape can be -1 %1%") % CHECK_LOCATION().AsString()));
         }
         auto targetNumElements =
             boost::numeric_cast<unsigned int>(
                 std::accumulate(targetDimsIn.begin(), targetDimsIn.end(), -1, std::multiplies<int32_t>()));
         auto stretchIndex = static_cast<size_t>(std::distance(targetDimsIn.begin(), stretchDim));
         outputDims[stretchIndex] = inputTensorInfo.GetNumElements() / targetNumElements;
     }
     TensorShape outputShape = TensorShape(static_cast<unsigned int>(outputDims.size()), outputDims.data());
     TensorInfo reshapeInfo = inputTensorInfo;
     reshapeInfo.SetShape(outputShape);
     return reshapeInfo;
 }
OutputShapeOfSqueeze()
armnn::TensorInfo OutputShapeOfSqueeze (const std::vector< uint32_t > & squeezeDims, const armnn::TensorInfo & inputTensorInfo) static
Definition at line 1625 of file TfLiteParser.cpp.
References ARMNN_ASSERT, CHECK_LOCATION, CHECK_MODEL, CHECK_VALID_SIZE, TfLiteParser::GetBuffer(), TfLiteParser::GetInputs(), TfLiteParser::GetInputTensorIds(), TensorInfo::GetNumBytes(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TfLiteParser::GetOutputs(), IConnectableLayer::GetOutputSlot(), TfLiteParser::GetOutputTensorIds(), TensorInfo::GetShape(), armnn::IgnoreUnused(), ActivationDescriptor::m_A, MeanDescriptor::m_Axis, ActivationDescriptor::m_B, StridedSliceDescriptor::m_Begin, StridedSliceDescriptor::m_BeginMask, StridedSliceDescriptor::m_DataLayout, StridedSliceDescriptor::m_EllipsisMask, StridedSliceDescriptor::m_End, StridedSliceDescriptor::m_EndMask, ActivationDescriptor::m_Function, MeanDescriptor::m_KeepDims, StridedSliceDescriptor::m_NewAxisMask, PadDescriptor::m_PadList, StridedSliceDescriptor::m_ShrinkAxisMask, StridedSliceDescriptor::m_Stride, ReshapeDescriptor::m_TargetShape, armnn::Neg, armnn::NHWC, TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToTensorInfo(), and true.
Referenced by BOOST_FIXTURE_TEST_CASE(), and TfLiteParser::~TfLiteParser().
 {
     CHECK_VALID_SIZE(squeezeDimsIn.size(), 0, 1, 2, 3, 4);
     std::vector<uint32_t> squeezeDims = squeezeDimsIn;
     static const uint32_t dimensionSequence[] = { 0, 1, 2, 3 };
     if (inputTensorInfo.GetNumDimensions() > 4)
     {
         std::stringstream ss;
         ss << "Input tensor has unexpected number of dimensions:" << inputTensorInfo.GetNumDimensions()
            << " shape:" << inputTensorInfo.GetShape() << " "
            << CHECK_LOCATION().AsString();
         throw ParseException(ss.str());
     }
     if (squeezeDims.empty())
     {
         squeezeDims.assign(dimensionSequence,
                            dimensionSequence+inputTensorInfo.GetNumDimensions());
     }
     std::vector<uint32_t> outputDims;
     for(unsigned int i = 0; i < inputTensorInfo.GetNumDimensions(); i++)
     {
         bool skipSqueeze = (std::find(squeezeDims.begin(), squeezeDims.end(), i) == squeezeDims.end());
         auto currentDimension = inputTensorInfo.GetShape()[i];
         if (skipSqueeze || currentDimension != 1)
         {
             outputDims.push_back(currentDimension);
         }
     }
     if (outputDims.size() > 4)
     {
         std::stringstream ss;
         ss << "Output tensor has unexpected number of dimensions:" << inputTensorInfo.GetNumDimensions()
            << " shape:" << inputTensorInfo.GetShape() << " "
            << CHECK_LOCATION().AsString();
         throw ParseException(ss.str());
     }
     TensorShape outShape = TensorShape(static_cast<unsigned int>(outputDims.size()),
                                        outputDims.data());
     // we need to preserve the tensor type and the quantization data as well
     TensorInfo outTensorInfo = inputTensorInfo;
     outTensorInfo.SetShape(outShape);
     return outTensorInfo;
 }
The documentation for this class was generated from the following files:
src/armnnTfLiteParser/TfLiteParser.hpp
src/armnnTfLiteParser/TfLiteParser.cpp