ArmNN: ClStridedSliceWorkload Class Reference
ClStridedSliceWorkload Class Reference
#include <ClStridedSliceWorkload.hpp>
Public Member Functions
ClStridedSliceWorkload (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info)
void Execute () const override
Public Member Functions inherited from BaseWorkload< StridedSliceQueueDescriptor >
BaseWorkload (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const StridedSliceQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< StridedSliceQueueDescriptor >
const StridedSliceQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 22 of file ClStridedSliceWorkload.hpp.
Constructor & Destructor Documentation
ClStridedSliceWorkload()
ClStridedSliceWorkload (const StridedSliceQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 54 of file ClStridedSliceWorkload.cpp.
References armnn::ConvertMaskToACLFormat(), StridedSliceDescriptor::m_Begin, StridedSliceDescriptor::m_BeginMask, BaseWorkload< StridedSliceQueueDescriptor >::m_Data, StridedSliceDescriptor::m_End, StridedSliceDescriptor::m_EndMask, QueueDescriptor::m_Inputs, WorkloadInfo::m_InputTensorInfos, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, StridedSliceDescriptor::m_ShrinkAxisMask, StridedSliceDescriptor::m_Stride, armnn::numeric_cast(), armnn::SetClStridedSliceData(), and QueueDescriptor::ValidateInputsOutputs().
     : BaseWorkload<StridedSliceQueueDescriptor>(descriptor, info)
 {
     m_Data.ValidateInputsOutputs("ClStridedSliceWorkload", 1, 1);
     arm_compute::ICLTensor& input = static_cast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = static_cast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     arm_compute::Coordinates starts;
     arm_compute::Coordinates ends;
     arm_compute::Coordinates strides;
     std::tie(starts, ends, strides) = SetClStridedSliceData(m_Data.m_Parameters.m_Begin,
                                                             m_Data.m_Parameters.m_End,
                                                             m_Data.m_Parameters.m_Stride);
     auto numDimensions       = boost::numeric_cast<int>(info.m_InputTensorInfos[0].GetNumDimensions());
     int32_t begin_mask       = ConvertMaskToACLFormat(m_Data.m_Parameters.m_BeginMask, numDimensions);
     int32_t end_mask         = ConvertMaskToACLFormat(m_Data.m_Parameters.m_EndMask, numDimensions);
     int32_t shrink_axis_mask = ConvertMaskToACLFormat(m_Data.m_Parameters.m_ShrinkAxisMask, numDimensions);
     arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
     input.info()->set_data_layout(aclDataLayout);
     output.info()->set_data_layout(aclDataLayout);
     m_StridedSliceLayer.configure(&input,
                                   &output,
                                   starts,
                                   ends,
                                   strides,
                                   begin_mask,
                                   end_mask,
                                   shrink_axis_mask);
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 90 of file ClStridedSliceWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_CL, CHECK_LOCATION, and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL("ClStridedSliceWorkload_Execute");
     RunClFunction(m_StridedSliceLayer, CHECK_LOCATION());
 }
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClStridedSliceWorkload.hpp
src/backends/cl/workloads/ClStridedSliceWorkload.cpp