ArmNN: TransposeConvolution2dQueueDescriptor Struct Reference
TransposeConvolution2dQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
TransposeConvolution2dQueueDescriptor ()
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptor
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
Public Attributes
const ConstCpuTensorHandle * m_Weight
const ConstCpuTensorHandle * m_Bias
Public Attributes inherited from QueueDescriptorWithParameters< TransposeConvolution2dDescriptor >
TransposeConvolution2dDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
Additional Inherited Members
Protected Member Functions inherited from QueueDescriptorWithParameters< TransposeConvolution2dDescriptor >
~QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
~QueueDescriptor ()=default
QueueDescriptor ()=default
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 516 of file WorkloadData.hpp.
Constructor & Destructor Documentation
TransposeConvolution2dQueueDescriptor()
TransposeConvolution2dQueueDescriptor () inline
Definition at line 518 of file WorkloadData.hpp.
                                             :
         m_Weight(nullptr),
         m_Bias(nullptr)
     {}
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 2794 of file WorkloadData.cpp.
References armnn::BFloat16, armnn::Float16, armnn::Float32, armnn::GetBiasDataType(), TensorInfo::GetDataType(), WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
 {
     const std::string descriptorName{"TransposeConvolution2dQueueDescriptor"};
     ValidateNumInputs(workloadInfo,  descriptorName, 1);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     ValidateTensorNumDimensions(inputTensorInfo,  descriptorName, 4, "input");
     ValidateTensorNumDimensions(outputTensorInfo, descriptorName, 4, "output");
     ValidatePointer(m_Weight, descriptorName, "weight");
     const TensorInfo& weightTensorInfo = m_Weight->GetTensorInfo();
     ValidateTensorNumDimensions(weightTensorInfo, descriptorName, 4, "weight");
     ValidateWeightDataType(inputTensorInfo, weightTensorInfo, descriptorName);
     Optional<TensorInfo> optionalBiasTensorInfo;
     if (m_Parameters.m_BiasEnabled)
     {
         ValidatePointer(m_Bias, descriptorName, "bias");
         optionalBiasTensorInfo = MakeOptional<TensorInfo>(m_Bias->GetTensorInfo());
         const TensorInfo& biasTensorInfo = optionalBiasTensorInfo.value();
         ValidateTensorDataType(biasTensorInfo, GetBiasDataType(inputTensorInfo.GetDataType()), descriptorName, "bias");
         ValidateBiasTensorQuantization(biasTensorInfo, inputTensorInfo, weightTensorInfo, descriptorName);
     }
     ValidatePerAxisQuantization(inputTensorInfo,
                                 outputTensorInfo,
                                 weightTensorInfo,
                                 optionalBiasTensorInfo,
                                 descriptorName);
     std::vector<DataType> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     ValidateDataTypes(inputTensorInfo, supportedTypes, descriptorName);
     ValidateTensorDataTypesMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
 }
Member Data Documentation
m_Bias
const ConstCpuTensorHandle* m_Bias
Definition at line 524 of file WorkloadData.hpp.
Referenced by TransposeConvolution2dLayer::CreateWorkload(), and RefTransposeConvolution2dWorkload::RefTransposeConvolution2dWorkload().
m_Weight
const ConstCpuTensorHandle* m_Weight
Definition at line 523 of file WorkloadData.hpp.
Referenced by ClTransposeConvolution2dWorkload::ClTransposeConvolution2dWorkload(), TransposeConvolution2dLayer::CreateWorkload(), and RefTransposeConvolution2dWorkload::RefTransposeConvolution2dWorkload().
The documentation for this struct was generated from the following files:
src/backends/backendsCommon/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp