var _exceptions_8hpp =
[
    [ "CheckLocation", "structarmnn_1_1_check_location.html", "structarmnn_1_1_check_location" ],
    [ "Exception", "classarmnn_1_1_exception.html", "classarmnn_1_1_exception" ],
    [ "BackendUnavailableException", "classarmnn_1_1_backend_unavailable_exception.html", "classarmnn_1_1_backend_unavailable_exception" ],
    [ "ClRuntimeUnavailableException", "classarmnn_1_1_cl_runtime_unavailable_exception.html", null ],
    [ "InvalidArgumentException", "classarmnn_1_1_invalid_argument_exception.html", "classarmnn_1_1_invalid_argument_exception" ],
    [ "FileNotFoundException", "classarmnn_1_1_file_not_found_exception.html", "classarmnn_1_1_file_not_found_exception" ],
    [ "ParseException", "classarmnn_1_1_parse_exception.html", "classarmnn_1_1_parse_exception" ],
    [ "UnimplementedException", "classarmnn_1_1_unimplemented_exception.html", "classarmnn_1_1_unimplemented_exception" ],
    [ "LayerValidationException", "classarmnn_1_1_layer_validation_exception.html", null ],
    [ "GraphValidationException", "classarmnn_1_1_graph_validation_exception.html", null ],
    [ "BadOptionalAccessException", "classarmnn_1_1_bad_optional_access_exception.html", null ],
    [ "RuntimeException", "classarmnn_1_1_runtime_exception.html", null ],
    [ "MemoryImportException", "classarmnn_1_1_memory_import_exception.html", null ],
    [ "MemoryExportException", "classarmnn_1_1_memory_export_exception.html", null ],
    [ "TimeoutException", "classarmnn_1_1_timeout_exception.html", null ],
    [ "PolymorphicDowncastException", "classarmnn_1_1_polymorphic_downcast_exception.html", "classarmnn_1_1_polymorphic_downcast_exception" ],
    [ "NullPointerException", "classarmnn_1_1_null_pointer_exception.html", "classarmnn_1_1_null_pointer_exception" ],
    [ "BackendCapabilityException", "classarmnn_1_1_backend_capability_exception.html", "classarmnn_1_1_backend_capability_exception" ],
    [ "MemoryValidationException", "classarmnn_1_1_memory_validation_exception.html", "classarmnn_1_1_memory_validation_exception" ],
    [ "ARMNN_THROW_IF_FALSE", "_exceptions_8hpp.html#a9b2494eef157fc6ffc5b82bd8935f7e4", null ],
    [ "ARMNN_THROW_INVALIDARG_IF_FALSE", "_exceptions_8hpp.html#a31e4268013316d114e8927e4c0035ec5", null ],
    [ "ARMNN_THROW_INVALIDARG_MSG_IF_FALSE", "_exceptions_8hpp.html#a5b0cd1f24b12298894d6367f186ea6dc", null ],
    [ "ARMNN_THROW_MSG_IF_FALSE", "_exceptions_8hpp.html#a797787c23ad8c69dee5f2ae6e0c69d63", null ],
    [ "CHECK_LOCATION", "_exceptions_8hpp.html#aa3be76aec4ce713822a5ea1ecbb7bc61", null ],
    [ "armnn::ConditionalThrow", "namespacearmnn.html#ae76e71928b6517c34f44cab8668c2a5f", null ],
    [ "armnn::ConditionalThrow", "namespacearmnn.html#afec78fc00c46b93efe94472879f9bfa7", null ],
    [ "armnn::ConditionalThrowIfNotEqual", "namespacearmnn.html#af4758af34dc6089fefa96126f0a96ad9", null ]
];