Arm NN: src/armnnTestUtils/GraphUtils.cpp File Reference
GraphUtils.cpp File Reference
#include "GraphUtils.hpp"
#include <armnn/utility/PolymorphicDowncast.hpp>
Functions
bool GraphHasNamedLayer (const armnn::Graph &graph, const std::string &name)
armnn::Layer * GetFirstLayerWithName (armnn::Graph &graph, const std::string &name)
bool CheckNumberOfInputSlot (armnn::Layer *layer, unsigned int num)
bool CheckNumberOfOutputSlot (armnn::Layer *layer, unsigned int num)
bool IsConnected (armnn::Layer *srcLayer, armnn::Layer *destLayer, unsigned int srcSlot, unsigned int destSlot, const armnn::TensorInfo &expectedTensorInfo)
bool CheckOrder (const armnn::Graph &graph, const armnn::Layer *first, const armnn::Layer *second)
Checks that first comes before second in the order.
Function Documentation
CheckNumberOfInputSlot()
bool CheckNumberOfInputSlot (armnn::Layer * layer, unsigned int num)
Definition at line 34 of file GraphUtils.cpp.
{
    return layer->GetNumInputSlots() == num;
}
References Layer::GetNumInputSlots().
CheckNumberOfOutputSlot()
bool CheckNumberOfOutputSlot (armnn::Layer * layer, unsigned int num)
Definition at line 39 of file GraphUtils.cpp.
{
    return layer->GetNumOutputSlots() == num;
}
References Layer::GetNumOutputSlots().
CheckOrder()
bool CheckOrder (const armnn::Graph & graph, const armnn::Layer * first, const armnn::Layer * second)
Checks that first comes before second in the order.
Definition at line 68 of file GraphUtils.cpp.
{
    graph.Print();
    const auto& order = graph.TopologicalSort();
    auto firstPos = std::find(order.begin(), order.end(), first);
    auto secondPos = std::find(firstPos, order.end(), second);
    return (secondPos != order.end());
}
References Graph::Print(), and Graph::TopologicalSort().
GetFirstLayerWithName()
armnn::Layer * GetFirstLayerWithName (armnn::Graph & graph, const std::string & name)
Definition at line 22 of file GraphUtils.cpp.
{
    for (auto&& layer : graph)
    {
        if (layer->GetNameStr() == name)
        {
            return layer;
        }
    }
    return nullptr;
}
GraphHasNamedLayer()
bool GraphHasNamedLayer (const armnn::Graph & graph, const std::string & name)
Definition at line 10 of file GraphUtils.cpp.
{
    for (auto&& layer : graph)
    {
        if (layer->GetName() == name)
        {
            return true;
        }
    }
    return false;
}
IsConnected()
bool IsConnected (armnn::Layer * srcLayer, armnn::Layer * destLayer, unsigned int srcSlot, unsigned int destSlot, const armnn::TensorInfo & expectedTensorInfo)
Definition at line 44 of file GraphUtils.cpp.
{
    const armnn::IOutputSlot& outputSlot = srcLayer->GetOutputSlot(srcSlot);
    const armnn::TensorInfo& tensorInfo = outputSlot.GetTensorInfo();
    if (expectedTensorInfo != tensorInfo)
    {
        return false;
    }
    const unsigned int numConnections = outputSlot.GetNumConnections();
    for (unsigned int c = 0; c < numConnections; ++c)
    {
        auto inputSlot = armnn::PolymorphicDowncast<const armnn::InputSlot*>(outputSlot.GetConnection(c));
        if (inputSlot->GetOwningLayer().GetNameStr() == destLayer->GetNameStr() &&
            inputSlot->GetSlotIndex() == destSlot)
        {
            return true;
        }
    }
    return false;
}
References IOutputSlot::GetConnection(), Layer::GetNameStr(), IOutputSlot::GetNumConnections(), Layer::GetOutputSlot(), IOutputSlot::GetTensorInfo(), and armnn::PolymorphicDowncast().