Arm NN: src/backends/reference/workloads/LstmUtils.cpp File Reference
LstmUtils.cpp File Reference
#include "LstmUtils.hpp"
#include "BaseIterator.hpp"
#include <armnn/backends/TensorHandle.hpp>
Functions
void VectorBatchVectorAdd (armnn::Decoder< float > &vector, uint32_t vSize, armnn::Decoder< float > &batchVector, uint32_t nBatch, armnn::Encoder< float > &outResult)
void MeanStddevNormalization (armnn::Decoder< float > &input_vector, armnn::Encoder< float > &output_vector, uint32_t v_size, uint32_t n_batch, float normalization_epsilon)
void ZeroVector (armnn::Encoder< float > &vector, uint32_t vSize)
void MatrixBatchVectorMultiplyAccumulate (armnn::Decoder< float > &matrix, uint32_t mRows, uint32_t mCols, armnn::Decoder< float > &vector, uint32_t nBatch, armnn::Encoder< float > &outResult)
void VectorBatchVectorAssign (armnn::Decoder< float > &vector, uint32_t vSize, uint32_t nBatch, armnn::Encoder< float > &outBatchVector)
void VectorBatchVectorCwiseProductAccumulate (armnn::Decoder< float > &vector, uint32_t vSize, armnn::Decoder< float > &batchVector, uint32_t nBatch, armnn::Encoder< float > &outResult)
void VectorBatchVectorCwiseProduct (armnn::Decoder< float > &vector, uint32_t vSize, armnn::Decoder< float > &batchVector, uint32_t nBatch, armnn::Encoder< float > &outResult)
void Sub1Vector (armnn::Decoder< float > &vector, uint32_t vSize, armnn::Encoder< float > &result)
void VectorVectorCwiseProduct (armnn::Decoder< float > &vector1, armnn::Decoder< float > &vector2, uint32_t vSize, armnn::Encoder< float > &outResult)
void VectorVectorCwiseProductAccumulate (armnn::Decoder< float > &vector1, armnn::Decoder< float > &vector2, uint32_t vSize, armnn::Encoder< float > &outResult)
float Clip (float f, float absLimit)
void ClipVector (armnn::Decoder< float > &vector, uint32_t vSize, float absLimit, armnn::Encoder< float > &outResult)
void CopyVector (armnn::Decoder< float > &vector, uint32_t vSize, armnn::Encoder< float > &outResult)
void SetActivationParameters (uint32_t activation, armnn::ActivationFunction &outArmnnActivation, float &outA, float &outB)
std::unique_ptr< armnn::ScopedTensorHandle > AssignScopedTensorHandle (const armnn::ConstTensorHandle *ptr)
Function Documentation
AssignScopedTensorHandle()
std::unique_ptr< armnn::ScopedTensorHandle > AssignScopedTensorHandle (const armnn::ConstTensorHandle * ptr)
Definition at line 299 of file LstmUtils.cpp.
{
    if (!ptr)
    {
        return nullptr;
    }
    return std::make_unique<armnn::ScopedTensorHandle>(*ptr);
}
Referenced by RefLstmWorkload::RefLstmWorkload(), RefQLstmWorkload::RefQLstmWorkload(), and RefUnidirectionalSequenceLstmWorkload::RefUnidirectionalSequenceLstmWorkload().
Clip()
float Clip (float f, float absLimit)
Definition at line 221 of file LstmUtils.cpp.
{
    float result = (absLimit < f) ? absLimit : f;
    result = (-absLimit > result) ? -absLimit : result;
    return result;
}
Referenced by ClipVector().
ClipVector()
void ClipVector (armnn::Decoder< float > & vector, uint32_t vSize, float absLimit, armnn::Encoder< float > & outResult)
Definition at line 229 of file LstmUtils.cpp.
{
    for (uint32_t v = 0; v < vSize; v++)
    {
        outResult.Set(Clip(vector.Get(), absLimit));
        ++vector;
        ++outResult;
    }
    vector -= vSize;
    outResult -= vSize;
}
References Clip(), Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
CopyVector()
void CopyVector (armnn::Decoder< float > & vector, uint32_t vSize, armnn::Encoder< float > & outResult)
Definition at line 244 of file LstmUtils.cpp.
{
    for (uint32_t v = 0; v < vSize; v++)
    {
        outResult.Set(vector.Get());
        ++outResult;
        ++vector;
    }
    outResult -= vSize;
    vector -= vSize;
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
MatrixBatchVectorMultiplyAccumulate()
void MatrixBatchVectorMultiplyAccumulate (armnn::Decoder< float > & matrix, uint32_t mRows, uint32_t mCols, armnn::Decoder< float > & vector, uint32_t nBatch, armnn::Encoder< float > & outResult)
Definition at line 87 of file LstmUtils.cpp.
{
    for (uint32_t b = 0; b < nBatch; b++)
    {
        for (uint32_t r = 0; r < mRows; r++)
        {
            vector += b * mCols;
            for (uint32_t c = 0; c < mCols; c++)
            {
                outResult.Set(outResult.Get() + matrix.Get() * vector.Get());
                ++matrix;
                ++vector;
            }
            outResult += 1;
            vector -= (b+1) * mCols;
        }
        matrix -= (mRows * mCols);
    }
    outResult -= (mRows * nBatch);
}
References Decoder< IType >::Get(), Encoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
MeanStddevNormalization()
void MeanStddevNormalization (armnn::Decoder< float > & input_vector, armnn::Encoder< float > & output_vector, uint32_t v_size, uint32_t n_batch, float normalization_epsilon)
Definition at line 40 of file LstmUtils.cpp.
{
    for (uint32_t batch = 0; batch < n_batch; ++batch) {
        float sum = 0.0f;
        float sum_sq = 0.0f;
        for (uint32_t i = 0; i < v_size; ++i) {
            sum += input_vector.Get();
            sum_sq += input_vector.Get() * input_vector.Get();
            ++input_vector;
        }
        input_vector -= v_size;
        const float mean = sum / static_cast<float>(v_size);
        float stddev_inv = 0.0f;
        const float variance = sum_sq / static_cast<float>(v_size) - mean * mean;
        if (variance == 0) {
            stddev_inv = 1.0f / std::sqrt(normalization_epsilon);
        } else {
            stddev_inv = 1.0f / std::sqrt(variance);
        }
        for (uint32_t i = 0; i < v_size; ++i) {
            output_vector.Set((input_vector.Get() - mean) * stddev_inv);
            ++output_vector;
            ++input_vector;
        }
        // Don't reset iterator to handle next batch
    }
    output_vector -= v_size * n_batch;
    input_vector -= v_size * n_batch;
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
SetActivationParameters()
void SetActivationParameters (uint32_t activation, armnn::ActivationFunction & outArmnnActivation, float & outA, float & outB)
Definition at line 258 of file LstmUtils.cpp.
{
    switch (activation)
    {
        case 0: // None
            outA = 0;
            outB = 0;
            return;
        case 1: // Relu
            outArmnnActivation = armnn::ActivationFunction::ReLu;
            outA = 0;
            outB = 0;
            return;
        case 3: // Relu6
            outArmnnActivation = armnn::ActivationFunction::BoundedReLu;
            outA = 6;
            outB = 0;
            return;
        case 4: // Tanh
            outArmnnActivation = armnn::ActivationFunction::TanH;
            outA = 1;
            outB = 1;
            return;
        case 6: // Sigmoid
            outArmnnActivation = armnn::ActivationFunction::Sigmoid;
            outA = 0;
            outB = 0;
            return;
        default:
            throw armnn::Exception("Unsupported activation function: " + std::to_string(activation));
    }
}
References armnn::BoundedReLu, armnn::ReLu, armnn::Sigmoid, and armnn::TanH.
Referenced by armnn::LstmImpl().
Sub1Vector()
void Sub1Vector (armnn::Decoder< float > & vector, uint32_t vSize, armnn::Encoder< float > & result)
Definition at line 173 of file LstmUtils.cpp.
{
    for (uint32_t v = 0; v < vSize; v++)
    {
        result.Set(1.0f - vector.Get());
        ++vector;
        ++result;
    }
    vector -= vSize;
    result -= vSize;
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
VectorBatchVectorAdd()
void VectorBatchVectorAdd (armnn::Decoder< float > & vector, uint32_t vSize, armnn::Decoder< float > & batchVector, uint32_t nBatch, armnn::Encoder< float > & outResult)
Definition at line 16 of file LstmUtils.cpp.
{
    for (uint32_t b = 0; b < nBatch; b++)
    {
        for (uint32_t v = 0; v < vSize; v++)
        {
            outResult.Set(batchVector.Get() + vector.Get());
            ++outResult;
            ++vector;
            ++batchVector;
        }
        vector -= vSize;
    }
    batchVector -= vSize * nBatch;
    outResult -= vSize * nBatch;
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
VectorBatchVectorAssign()
void VectorBatchVectorAssign (armnn::Decoder< float > & vector, uint32_t vSize, uint32_t nBatch, armnn::Encoder< float > & outBatchVector)
Definition at line 113 of file LstmUtils.cpp.
{
    for (uint32_t b = 0; b < nBatch; b++)
    {
        for (uint32_t v = 0; v < vSize; v++)
        {
            outBatchVector.Set(vector.Get());
            ++outBatchVector;
            ++vector;
        }
        vector -= vSize;
    }
    outBatchVector -= (nBatch * vSize);
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
VectorBatchVectorCwiseProduct()
void VectorBatchVectorCwiseProduct (armnn::Decoder< float > & vector, uint32_t vSize, armnn::Decoder< float > & batchVector, uint32_t nBatch, armnn::Encoder< float > & outResult)
Definition at line 152 of file LstmUtils.cpp.
{
    for (uint32_t b = 0; b < nBatch; b++)
    {
        for (uint32_t v = 0; v < vSize; v++)
        {
            outResult.Set(vector.Get() * batchVector.Get());
            ++outResult;
            ++vector;
            ++batchVector;
        }
        vector -= vSize;
    }
    batchVector -= vSize * nBatch;
    outResult -= vSize * nBatch;
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
VectorBatchVectorCwiseProductAccumulate()
void VectorBatchVectorCwiseProductAccumulate (armnn::Decoder< float > & vector, uint32_t vSize, armnn::Decoder< float > & batchVector, uint32_t nBatch, armnn::Encoder< float > & outResult)
Definition at line 131 of file LstmUtils.cpp.
{
    for (uint32_t b = 0; b < nBatch; b++)
    {
        for (uint32_t v = 0; v < vSize; v++)
        {
            outResult.Set(outResult.Get() + vector.Get() * batchVector.Get());
            ++outResult;
            ++vector;
            ++batchVector;
        }
        vector -= vSize;
    }
    batchVector -= vSize * nBatch;
    outResult -= vSize * nBatch;
}
References Decoder< IType >::Get(), Encoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
VectorVectorCwiseProduct()
void VectorVectorCwiseProduct (armnn::Decoder< float > & vector1, armnn::Decoder< float > & vector2, uint32_t vSize, armnn::Encoder< float > & outResult)
Definition at line 187 of file LstmUtils.cpp.
{
    for (uint32_t v = 0; v < vSize; v++)
    {
        outResult.Set(vector1.Get() * vector2.Get());
        ++outResult;
        ++vector1;
        ++vector2;
    }
    outResult -= vSize;
    vector1 -= vSize;
    vector2 -= vSize;
}
References Decoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
VectorVectorCwiseProductAccumulate()
void VectorVectorCwiseProductAccumulate (armnn::Decoder< float > & vector1, armnn::Decoder< float > & vector2, uint32_t vSize, armnn::Encoder< float > & outResult)
Definition at line 204 of file LstmUtils.cpp.
{
    for (uint32_t v = 0; v < vSize; v++)
    {
        outResult.Set(outResult.Get() + vector1.Get() * vector2.Get());
        ++outResult;
        ++vector1;
        ++vector2;
    }
    outResult -= vSize;
    vector1 -= vSize;
    vector2 -= vSize;
}
References Decoder< IType >::Get(), Encoder< IType >::Get(), and Encoder< IType >::Set().
Referenced by armnn::LstmImpl().
ZeroVector()
void ZeroVector (armnn::Encoder< float > & vector, uint32_t vSize)
Definition at line 76 of file LstmUtils.cpp.
{
    for (uint32_t v = 0; v < vSize; v++)
    {
        vector.Set(0.0f);
        ++vector;
    }
    vector -= vSize;
}
References Encoder< IType >::Set().
Referenced by armnn::LstmImpl().