Arm NN: src/backends/tosaCommon/operatorMappings/SliceOperator.hpp File Reference
SliceOperator.hpp File Reference
#include "TosaOperatorUtils.hpp"
Functions
TosaSerializationBasicBlock * ConvertSliceToTosaOperator (const Layer *layer, const std::vector< const TensorInfo * > &inputs, const std::vector< const TensorInfo * > &outputs, const SliceDescriptor *sliceDescriptor)
Function Documentation
ConvertSliceToTosaOperator()
TosaSerializationBasicBlock * ConvertSliceToTosaOperator (const Layer * layer, const std::vector< const TensorInfo * > & inputs, const std::vector< const TensorInfo * > & outputs, const SliceDescriptor * sliceDescriptor)
Definition at line 8 of file SliceOperator.cpp.
{
    std::string inputName = std::string("input_");
    std::string outputName = std::string("output0_");
    std::string blockName  = std::string("Op_SLICE_block_") + GetUniqueTosaMappingID();
    // If a layer is present then the block will be used for execution, so input and output names need to be determined
    // using the previous and following layers so the graph is connected correctly. For validation this doesn't matter.
    if(layer != nullptr)
    {
        inputName  = GenerateUniqueInputName(layer->GetInputSlot(0));
        outputName = GenerateUniqueOutputName(*layer);
    }
    std::vector<int32_t> begin(sliceDescriptor->m_Begin.begin(), sliceDescriptor->m_Begin.end());
    std::vector<int32_t> size(sliceDescriptor->m_Size.begin(), sliceDescriptor->m_Size.end());
    TosaSliceAttribute attribute(begin, size);
    auto* op = new TosaSerializationOperator(Op_SLICE,
                                             Attribute_SliceAttribute,
                                             &attribute,
                                             {inputName},
                                             {outputName});
    std::vector<TosaSerializationTensor*> tensors;
    // Only add input tensors if connected layer is an input layer.
    // As intermediate or constant tensors will be created separately.
    // There also can't be duplicate tensor.
    if(inputName.find("input_") != std::string::npos)
    {
        std::vector<int32_t> inputShape = GetTosaTensorShape(inputs[0]->GetShape());
        DType inputDType = ArmNNToDType(inputs[0]->GetDataType());
        tensors.push_back(new TosaSerializationTensor(inputName, inputShape, inputDType, {}));
    }
    std::vector<int32_t> outputShape = GetTosaTensorShape(outputs[0]->GetShape());
    DType outputDType = ArmNNToDType(outputs[0]->GetDataType());
    tensors.push_back(new TosaSerializationTensor(outputName, outputShape, outputDType, {}));
    // operatorInputNames/operatorOutputNames ends up being the same as
    // blockInputNames/blockOutputNames for one-to-one ArmNN to TOSA mappings
    return new TosaSerializationBasicBlock(blockName, // name
                                           mainName, // region name
                                           {op}, // operators
                                           tensors, // tensors
                                           {inputName}, // inputs
                                           {outputName}); // outputs
}
References ArmNNToDType(), GenerateUniqueInputName(), GenerateUniqueOutputName(), Layer::GetInputSlot(), GetTosaTensorShape(), GetUniqueTosaMappingID(), SliceDescriptor::m_Begin, SliceDescriptor::m_Size, and mainName.
Referenced by GetTosaMapping().