Arm NN: src/armnnTestUtils/TestUtils.hpp File Reference
TestUtils.hpp File Reference
#include <armnn/INetwork.hpp>
#include <Graph.hpp>
#include <Runtime.hpp>
Classes
class LayerNameAndTypeCheck
Namespaces
namespace armnn
Copyright (c) 2021 ARM Limited and Contributors.
Functions
void Connect (armnn::IConnectableLayer *from, armnn::IConnectableLayer *to, const armnn::TensorInfo &tensorInfo, unsigned int fromIndex=0, unsigned int toIndex=0)
template<typename LayerT>
bool IsLayerOfType (const armnn::Layer *const layer)
bool CheckSequence (const armnn::Graph::ConstIterator first, const armnn::Graph::ConstIterator last)
template<typename U, typename... Us>
bool CheckSequence (const armnn::Graph::ConstIterator first, const armnn::Graph::ConstIterator last, U &&u, Us &&... us)
Checks each unary function in Us evaluates true for each correspondent layer in the sequence [first, last).
template<typename LayerT>
bool CheckRelatedLayers (armnn::Graph &graph, const std::list< std::string > &testRelatedLayers)
Graph & GetGraphForTesting (IOptimizedNetwork *optNet)
ModelOptions & GetModelOptionsForTesting (IOptimizedNetwork *optNet)
arm::pipe::IProfilingService & GetProfilingService (armnn::RuntimeImpl *runtime)
Function Documentation
CheckRelatedLayers()
template<typename LayerT> bool CheckRelatedLayers (armnn::Graph & graph, const std::list< std::string > & testRelatedLayers)
Definition at line 52 of file TestUtils.hpp.
{
    for (auto& layer : graph)
    {
        if (layer->GetType() == armnn::LayerEnumOf<LayerT>())
        {
            auto& relatedLayers = layer->GetRelatedLayerNames();
            if (!std::equal(relatedLayers.begin(), relatedLayers.end(), testRelatedLayers.begin(),
                            testRelatedLayers.end()))
            {
                return false;
            }
        }
    }
    return true;
}
References armnn::LayerEnumOf().
CheckSequence() [1/2]
bool CheckSequence (const armnn::Graph::ConstIterator first, const armnn::Graph::ConstIterator last) inline
Definition at line 39 of file TestUtils.hpp.
{
    return (first == last);
}
Referenced by CheckSequence().
CheckSequence() [2/2]
template<typename U, typename... Us> bool CheckSequence (const armnn::Graph::ConstIterator first, const armnn::Graph::ConstIterator last, U && u, Us &&... us)
Checks each unary function in Us evaluates true for each correspondent layer in the sequence [first, last).
Definition at line 46 of file TestUtils.hpp.
{
    return u(*first) && CheckSequence(std::next(first), last, us...);
}
References CheckSequence().
Connect()
void Connect (armnn::IConnectableLayer * from, armnn::IConnectableLayer * to, const armnn::TensorInfo & tensorInfo, unsigned int fromIndex = 0, unsigned int toIndex = 0)
Definition at line 14 of file TestUtils.cpp.
{
    ARMNN_ASSERT(from);
    ARMNN_ASSERT(to);
    try
    {
        from->GetOutputSlot(fromIndex).Connect(to->GetInputSlot(toIndex));
    }
    catch (const std::out_of_range& exc)
    {
        std::ostringstream message;
        if (to->GetType() == armnn::LayerType::FullyConnected && toIndex == 2)
        {
            message << "Tried to connect bias to FullyConnected layer when bias is not enabled: ";
        }
        message << "Failed to connect to input slot "
                << toIndex
                << " on "
                << GetLayerTypeAsCString(to->GetType())
                << " layer "
                << std::quoted(to->GetName())
                << " as the slot does not exist or is unavailable";
        throw LayerValidationException(message.str());
    }
    from->GetOutputSlot(fromIndex).SetTensorInfo(tensorInfo);
}
References ARMNN_ASSERT, IOutputSlot::Connect(), armnn::FullyConnected, IConnectableLayer::GetInputSlot(), armnn::GetLayerTypeAsCString(), IConnectableLayer::GetName(), IConnectableLayer::GetOutputSlot(), IConnectableLayer::GetType(), and IOutputSlot::SetTensorInfo().
IsLayerOfType()
template<typename LayerT> bool IsLayerOfType (const armnn::Layer *const layer)
Definition at line 34 of file TestUtils.hpp.
{
    return (layer->GetType() == armnn::LayerEnumOf<LayerT>());
}
References Layer::GetType(), and armnn::LayerEnumOf().