Arm NN: src/armnnTestUtils/UnitTests.hpp File Reference
UnitTests.hpp File Reference
#include "armnnTestUtils/TensorHelpers.hpp"
#include <armnn/Logging.hpp>
#include <armnn/Utils.hpp>
#include <reference/RefWorkloadFactory.hpp>
#include <reference/test/RefWorkloadFactoryHelper.hpp>
#include <backendsCommon/test/WorkloadFactoryHelper.hpp>
#include <armnnTestUtils/LayerTestResult.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <doctest/doctest.h>
Macros
#define ARMNN_SIMPLE_TEST_CASE(TestName, TestFunction)
#define ARMNN_AUTO_TEST_CASE(TestName, TestFunction, ...)
#define ARMNN_AUTO_TEST_FIXTURE(TestName, Fixture, TestFunction, ...)
#define ARMNN_AUTO_TEST_CASE_WITH_THF(TestName, TestFunction, ...)
#define ARMNN_AUTO_TEST_FIXTURE_WITH_THF(TestName, Fixture, TestFunction, ...)
#define ARMNN_COMPARE_REF_AUTO_TEST_CASE(TestName, TestFunction, ...)
#define ARMNN_COMPARE_REF_AUTO_TEST_CASE_WITH_THF(TestName, TestFunction, ...)
#define ARMNN_COMPARE_REF_FIXTURE_TEST_CASE(TestName, Fixture, TestFunction, ...)
#define ARMNN_COMPARE_REF_FIXTURE_TEST_CASE_WITH_THF(TestName, Fixture, TestFunction, ...)
Functions
void ConfigureLoggingTest ()
template<typename T, std::size_t n>
void CompareTestResultIfSupported (const std::string &testName, const LayerTestResult< T, n > &testResult)
Executes CHECK_MESSAGE on CompareTensors() return value so that the predicate_result message is reported.
template<typename T, std::size_t n>
void CompareTestResultIfSupported (const std::string &testName, const std::vector< LayerTestResult< T, n > > &testResult)
template<typename FactoryType, typename TFuncPtr, typename... Args>
void RunTestFunction (const char *testName, TFuncPtr testFunction, Args... args)
template<typename FactoryType, typename TFuncPtr, typename... Args>
void RunTestFunctionUsingTensorHandleFactory (const char *testName, TFuncPtr testFunction, Args... args)
template<typename FactoryType, typename TFuncPtr, typename... Args>
void CompareRefTestFunction (const char *testName, TFuncPtr testFunction, Args... args)
template<typename FactoryType, typename TFuncPtr, typename... Args>
void CompareRefTestFunctionUsingTensorHandleFactory (const char *testName, TFuncPtr testFunction, Args... args)
Macro Definition Documentation
ARMNN_AUTO_TEST_CASE
#define ARMNN_AUTO_TEST_CASE (TestName, TestFunction, ...)
Value:
    TEST_CASE(#TestName) \
    { \
        RunTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 117 of file UnitTests.hpp.
#define ARMNN_AUTO_TEST_CASE(TestName, TestFunction, ...) \
    TEST_CASE(#TestName) \
    { \
        RunTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_AUTO_TEST_CASE_WITH_THF
#define ARMNN_AUTO_TEST_CASE_WITH_THF (TestName, TestFunction, ...)
Value:
    TEST_CASE(#TestName) \
    { \
        RunTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 129 of file UnitTests.hpp.
#define ARMNN_AUTO_TEST_CASE_WITH_THF(TestName, TestFunction, ...) \
    TEST_CASE(#TestName) \
    { \
        RunTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_AUTO_TEST_FIXTURE
#define ARMNN_AUTO_TEST_FIXTURE (TestName, Fixture, TestFunction, ...)
Value:
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        RunTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 123 of file UnitTests.hpp.
#define ARMNN_AUTO_TEST_FIXTURE(TestName, Fixture, TestFunction, ...) \
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        RunTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_AUTO_TEST_FIXTURE_WITH_THF
#define ARMNN_AUTO_TEST_FIXTURE_WITH_THF (TestName, Fixture, TestFunction, ...)
Value:
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        RunTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 135 of file UnitTests.hpp.
#define ARMNN_AUTO_TEST_FIXTURE_WITH_THF(TestName, Fixture, TestFunction, ...) \
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        RunTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_COMPARE_REF_AUTO_TEST_CASE
#define ARMNN_COMPARE_REF_AUTO_TEST_CASE (TestName, TestFunction, ...)
Value:
    TEST_CASE(#TestName) \
    { \
        CompareRefTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 169 of file UnitTests.hpp.
#define ARMNN_COMPARE_REF_AUTO_TEST_CASE(TestName, TestFunction, ...) \
    TEST_CASE(#TestName) \
    { \
        CompareRefTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_COMPARE_REF_AUTO_TEST_CASE_WITH_THF
#define ARMNN_COMPARE_REF_AUTO_TEST_CASE_WITH_THF (TestName, TestFunction, ...)
Value:
    TEST_CASE(#TestName) \
    { \
        CompareRefTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 175 of file UnitTests.hpp.
#define ARMNN_COMPARE_REF_AUTO_TEST_CASE_WITH_THF(TestName, TestFunction, ...) \
    TEST_CASE(#TestName) \
    { \
        CompareRefTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_COMPARE_REF_FIXTURE_TEST_CASE
#define ARMNN_COMPARE_REF_FIXTURE_TEST_CASE (TestName, Fixture, TestFunction, ...)
Value:
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        CompareRefTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 181 of file UnitTests.hpp.
#define ARMNN_COMPARE_REF_FIXTURE_TEST_CASE(TestName, Fixture, TestFunction, ...) \
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        CompareRefTestFunction<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_COMPARE_REF_FIXTURE_TEST_CASE_WITH_THF
#define ARMNN_COMPARE_REF_FIXTURE_TEST_CASE_WITH_THF (TestName, Fixture, TestFunction, ...)
Value:
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        CompareRefTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
Definition at line 187 of file UnitTests.hpp.
#define ARMNN_COMPARE_REF_FIXTURE_TEST_CASE_WITH_THF(TestName, Fixture, TestFunction, ...) \
    TEST_CASE_FIXTURE(Fixture, #TestName) \
    { \
        CompareRefTestFunctionUsingTensorHandleFactory<FactoryType>(#TestName, &TestFunction, ##__VA_ARGS__); \
    }
ARMNN_SIMPLE_TEST_CASE
#define ARMNN_SIMPLE_TEST_CASE (TestName, TestFunction)
Value:
    TEST_CASE(#TestName) \
    { \
        TestFunction(); \
    }
Definition at line 111 of file UnitTests.hpp.
#define ARMNN_SIMPLE_TEST_CASE(TestName, TestFunction) \
    TEST_CASE(#TestName) \
    { \
        TestFunction(); \
    }
Function Documentation
CompareRefTestFunction()
template<typename FactoryType, typename TFuncPtr, typename... Args> void CompareRefTestFunction (const char * testName, TFuncPtr testFunction, Args... args)
Definition at line 142 of file UnitTests.hpp.
{
    auto memoryManager = WorkloadFactoryHelper<FactoryType>::GetMemoryManager();
    FactoryType workloadFactory = WorkloadFactoryHelper<FactoryType>::GetFactory(memoryManager);
    armnn::RefWorkloadFactory refWorkloadFactory;
    auto testResult = (*testFunction)(workloadFactory, memoryManager, refWorkloadFactory, args...);
    CompareTestResultIfSupported(testName, testResult);
}
References CompareTestResultIfSupported().
CompareRefTestFunctionUsingTensorHandleFactory()
template<typename FactoryType, typename TFuncPtr, typename... Args> void CompareRefTestFunctionUsingTensorHandleFactory (const char * testName, TFuncPtr testFunction, Args... args)
Definition at line 154 of file UnitTests.hpp.
{
    auto memoryManager = WorkloadFactoryHelper<FactoryType>::GetMemoryManager();
    FactoryType workloadFactory = WorkloadFactoryHelper<FactoryType>::GetFactory(memoryManager);
    auto tensorHandleFactory = WorkloadFactoryHelper<FactoryType>::GetTensorHandleFactory(memoryManager);
    armnn::RefWorkloadFactory refWorkloadFactory;
    auto refMemoryManager = WorkloadFactoryHelper<armnn::RefWorkloadFactory>::GetMemoryManager();
    auto refTensorHandleFactory = RefWorkloadFactoryHelper::GetTensorHandleFactory(refMemoryManager);
    auto testResult = (*testFunction)(
        workloadFactory, memoryManager, refWorkloadFactory, tensorHandleFactory, refTensorHandleFactory, args...);
    CompareTestResultIfSupported(testName, testResult);
}
References CompareTestResultIfSupported().
CompareTestResultIfSupported() [1/2]
template<typename T, std::size_t n> void CompareTestResultIfSupported (const std::string & testName, const LayerTestResult< T, n > & testResult)
Executes CHECK_MESSAGE on CompareTensors() return value so that the predicate_result message is reported.
If the test reports itself as not supported then the tensors are not compared. Additionally this checks that the supportedness reported by the test matches the name of the test. Unsupported tests must be 'tagged' by including "UNSUPPORTED" in their name. This is useful because it clarifies that the feature being tested is not actually supported (a passed test with the name of a feature would imply that feature was supported). If support is added for a feature, the test case will fail because the name incorrectly contains UNSUPPORTED. If support is removed for a feature, the test case will fail because the name doesn't contain UNSUPPORTED.
Definition at line 43 of file UnitTests.hpp.
{
    bool testNameIndicatesUnsupported = testName.find("UNSUPPORTED") != std::string::npos;
    CHECK_MESSAGE(testNameIndicatesUnsupported != testResult.m_Supported,
                  "The test name does not match the supportedness it is reporting");
    if (testResult.m_Supported)
    {
        auto result = CompareTensors(testResult.m_ActualData,
                                     testResult.m_ExpectedData,
                                     testResult.m_ActualShape,
                                     testResult.m_ExpectedShape,
                                     testResult.m_CompareBoolean);
       CHECK_MESSAGE(result.m_Result, result.m_Message.str());
    }
}
Referenced by CompareRefTestFunction(), CompareRefTestFunctionUsingTensorHandleFactory(), RunTestFunction(), and RunTestFunctionUsingTensorHandleFactory().
CompareTestResultIfSupported() [2/2]
template<typename T, std::size_t n> void CompareTestResultIfSupported (const std::string & testName, const std::vector< LayerTestResult< T, n > > & testResult)
Definition at line 60 of file UnitTests.hpp.
{
    bool testNameIndicatesUnsupported = testName.find("UNSUPPORTED") != std::string::npos;
    for (unsigned int i = 0; i < testResult.size(); ++i)
    {
        CHECK_MESSAGE(testNameIndicatesUnsupported != testResult[i].m_Supported,
                      "The test name does not match the supportedness it is reporting");
        if (testResult[i].m_Supported)
        {
            auto result = CompareTensors(testResult[i].m_ActualData,
                                         testResult[i].m_ExpectedData,
                                         testResult[i].m_ActualShape,
                                         testResult[i].m_ExpectedShape);
            CHECK_MESSAGE(result.m_Result, result.m_Message.str());
        }
    }
}
ConfigureLoggingTest()
void ConfigureLoggingTest () inline
Definition at line 22 of file UnitTests.hpp.
{
    // Configures logging for both the ARMNN library and this test program.
    armnn::ConfigureLogging(true, true, armnn::LogSeverity::Fatal);
}
References armnn::ConfigureLogging(), and armnn::Fatal.
RunTestFunction()
template<typename FactoryType, typename TFuncPtr, typename... Args> void RunTestFunction (const char * testName, TFuncPtr testFunction, Args... args)
Definition at line 79 of file UnitTests.hpp.
{
    std::unique_ptr<armnn::IProfiler> profiler = std::make_unique<armnn::IProfiler>();
    armnn::ProfilerManager::GetInstance().RegisterProfiler(profiler.get());
    auto memoryManager = WorkloadFactoryHelper<FactoryType>::GetMemoryManager();
    FactoryType workloadFactory = WorkloadFactoryHelper<FactoryType>::GetFactory(memoryManager);
    auto testResult = (*testFunction)(workloadFactory, memoryManager, args...);
    CompareTestResultIfSupported(testName, testResult);
    armnn::ProfilerManager::GetInstance().RegisterProfiler(nullptr);
}
References CompareTestResultIfSupported(), ProfilerManager::GetInstance(), and ProfilerManager::RegisterProfiler().
RunTestFunctionUsingTensorHandleFactory()
template<typename FactoryType, typename TFuncPtr, typename... Args> void RunTestFunctionUsingTensorHandleFactory (const char * testName, TFuncPtr testFunction, Args... args)
Definition at line 95 of file UnitTests.hpp.
{
    std::unique_ptr<armnn::IProfiler> profiler = std::make_unique<armnn::IProfiler>();
    armnn::ProfilerManager::GetInstance().RegisterProfiler(profiler.get());
    auto memoryManager = WorkloadFactoryHelper<FactoryType>::GetMemoryManager();
    FactoryType workloadFactory = WorkloadFactoryHelper<FactoryType>::GetFactory(memoryManager);
    auto tensorHandleFactory = WorkloadFactoryHelper<FactoryType>::GetTensorHandleFactory(memoryManager);
    auto testResult = (*testFunction)(workloadFactory, memoryManager, tensorHandleFactory, args...);
    CompareTestResultIfSupported(testName, testResult);
    armnn::ProfilerManager::GetInstance().RegisterProfiler(nullptr);
}
References CompareTestResultIfSupported(), ProfilerManager::GetInstance(), and ProfilerManager::RegisterProfiler().