Arm NN: ISerializer Class Reference
ISerializer Class Reference
#include <ISerializer.hpp>
Classes
class SerializerImpl
Public Member Functions
void Serialize (const armnn::INetwork &inNetwork)
Serializes the network to ArmNN SerializedGraph.
bool SaveSerializedToStream (std::ostream &stream)
Serializes the SerializedGraph to the stream.
Static Public Member Functions
static ISerializer * CreateRaw ()
static ISerializerPtr Create ()
static void Destroy (ISerializer *serializer)
Detailed Description
Definition at line 17 of file ISerializer.hpp.
Member Function Documentation
Create()
ISerializerPtr Create () static
Definition at line 35 of file Serializer.cpp.
{
    return ISerializerPtr(CreateRaw(), &ISerializer::Destroy);
}
References Create(), CreateRaw(), and Destroy().
Referenced by Create().
CreateRaw()
ISerializer * CreateRaw () static
Definition at line 30 of file Serializer.cpp.
{
    return new ISerializer();
}
References CreateRaw().
Referenced by Create(), and CreateRaw().
Destroy()
void Destroy (ISerializer * serializer) static
Definition at line 40 of file Serializer.cpp.
{
    delete serializer;
}
References Destroy().
Referenced by Create(), and Destroy().
SaveSerializedToStream()
bool SaveSerializedToStream (std::ostream & stream)
Serializes the SerializedGraph to the stream.
Parameters
[stream] the stream to save to
Returns
true if graph is Serialized to the Stream, false otherwise
Definition at line 50 of file Serializer.cpp.
{
    return pSerializerImpl->SaveSerializedToStream(stream);
}
References SaveSerializedToStream().
Referenced by SaveSerializedToStream().
Serialize()
void Serialize (const armnn::INetwork & inNetwork)
Serializes the network to ArmNN SerializedGraph.
Parameters
[in] inNetwork The network to be serialized.
Definition at line 45 of file Serializer.cpp.
{
    pSerializerImpl->Serialize(inNetwork);
}
References Serialize().
Referenced by Serialize().
The documentation for this class was generated from the following files:
include/armnnSerializer/ISerializer.hpp
src/armnnSerializer/Serializer.cpp