Arm NN: ISerializer::SerializerImpl Class Reference
ISerializer::SerializerImpl Class Reference
#include <Serializer.hpp>
Public Member Functions
SerializerImpl ()=default
~SerializerImpl ()=default
void Serialize (const armnn::INetwork &inNetwork)
Serializes the network to ArmNN SerializedGraph.
bool SaveSerializedToStream (std::ostream &stream)
Serializes the SerializedGraph to the stream.
Detailed Description
Definition at line 365 of file Serializer.hpp.
Constructor & Destructor Documentation
SerializerImpl()
SerializerImpl () default
~SerializerImpl()
~SerializerImpl () default
Member Function Documentation
SaveSerializedToStream()
bool SaveSerializedToStream (std::ostream & stream)
Serializes the SerializedGraph to the stream.
Parameters
[stream] the stream to save to
Returns
true if graph is Serialized to the Stream, false otherwise
Definition at line 2562 of file Serializer.cpp.
{
    flatbuffers::FlatBufferBuilder& fbBuilder = m_SerializerStrategy.GetFlatBufferBuilder();
    auto bytesToWrite = armnn::numeric_cast<std::streamsize>(fbBuilder.GetSize());
    stream.write(reinterpret_cast<const char*>(fbBuilder.GetBufferPointer()), bytesToWrite);
    return !stream.bad();
}
References armnn::numeric_cast(), and SaveSerializedToStream().
Referenced by SaveSerializedToStream().
Serialize()
void Serialize (const armnn::INetwork & inNetwork)
Serializes the network to ArmNN SerializedGraph.
Parameters
[in] inNetwork The network to be serialized.
Definition at line 2543 of file Serializer.cpp.
{
    // Iterate through to network
    inNetwork.ExecuteStrategy(m_SerializerStrategy);
    flatbuffers::FlatBufferBuilder& fbBuilder = m_SerializerStrategy.GetFlatBufferBuilder();
    // Create FlatBuffer SerializedGraph
    auto serializedGraph = serializer::CreateSerializedGraph(
            fbBuilder,
            fbBuilder.CreateVector(m_SerializerStrategy.GetSerializedLayers()),
            fbBuilder.CreateVector(m_SerializerStrategy.GetInputIds()),
            fbBuilder.CreateVector(m_SerializerStrategy.GetOutputIds()),
            m_SerializerStrategy.GetVersionTable());
    // Serialize the graph
    fbBuilder.Finish(serializedGraph);
}
References INetwork::ExecuteStrategy(), and Serialize().
Referenced by Serialize().
The documentation for this class was generated from the following files:
src/armnnSerializer/Serializer.hpp
src/armnnSerializer/Serializer.cpp