Arm NN: DotEdge Class Reference
DotEdge Class Reference
#include <DotSerializer.hpp>
Public Member Functions
DotEdge (std::ostream &stream, LayerGuid fromNodeId, LayerGuid toNodeId)
~DotEdge ()
DotAttributeSet & GetAttributeSet ()
Public Member Functions inherited from DotBase
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 77 of file DotSerializer.hpp.
Constructor & Destructor Documentation
DotEdge()
DotEdge (std::ostream & stream, LayerGuid fromNodeId, LayerGuid toNodeId) explicit
Definition at line 119 of file DotSerializer.cpp.
    : DotBase(stream)
{
    std::stringstream ss;
    ss << Indent(4) << fromNodeId << " -> " << toNodeId << " ";
    GetStream() << ss.str();
    m_Attributes = std::make_unique<DotAttributeSet>(stream);
}
References DotBase::DotBase(), and DotBase::GetStream().
~DotEdge()
~DotEdge ()
Definition at line 129 of file DotSerializer.cpp.
{
    m_Attributes.reset(nullptr);
    GetStream() << ";" << std::endl;
}
References DotBase::GetStream().
Member Function Documentation
GetAttributeSet()
DotAttributeSet & GetAttributeSet () inline
Definition at line 83 of file DotSerializer.hpp.
{ return *m_Attributes.get(); }
Referenced by Graph::SerializeToDot().
The documentation for this class was generated from the following files:
src/armnnUtils/DotSerializer.hpp
src/armnnUtils/DotSerializer.cpp