Arm NN: ScopedTensorHandle Class Reference
ScopedTensorHandle Class Reference
#include <TensorHandle.hpp>
Public Member Functions
ScopedTensorHandle (const TensorInfo &tensorInfo)
ScopedTensorHandle (const ConstTensor &tensor)
ScopedTensorHandle (const ConstTensorHandle &tensorHandle)
ScopedTensorHandle (const ScopedTensorHandle &other)
ScopedTensorHandle & operator= (const ScopedTensorHandle &other)
~ScopedTensorHandle ()
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
Public Member Functions inherited from TensorHandle
template<typename T>
T * GetTensor () const
template<>
void * GetTensor () const
template<>
void * GetTensor () const
template<>
void * GetTensor () const
Public Member Functions inherited from ConstTensorHandle
template<typename T>
const T * GetConstTensor () const
const TensorInfo & GetTensorInfo () const
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo)
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Additional Inherited Members
Protected Member Functions inherited from TensorHandle
TensorHandle (const TensorInfo &tensorInfo)
void SetMemory (void *mem)
Protected Member Functions inherited from ConstTensorHandle
ConstTensorHandle (const TensorInfo &tensorInfo)
void SetConstMemory (const void *mem)
Detailed Description
Definition at line 115 of file TensorHandle.hpp.
Constructor & Destructor Documentation
ScopedTensorHandle() [1/4]
ScopedTensorHandle (const TensorInfo & tensorInfo) explicit
Definition at line 55 of file TensorHandle.cpp.
: TensorHandle(tensorInfo)
{
}
References TensorHandle::TensorHandle().
Referenced by operator=(), ScopedTensorHandle(), ScopedTensorHandle(), and ScopedTensorHandle().
ScopedTensorHandle() [2/4]
ScopedTensorHandle (const ConstTensor & tensor) explicit
Definition at line 60 of file TensorHandle.cpp.
: ScopedTensorHandle(tensor.GetInfo())
{
    CopyFrom(tensor.GetMemoryArea(), tensor.GetNumBytes());
}
References BaseTensor< MemoryType >::GetMemoryArea(), BaseTensor< MemoryType >::GetNumBytes(), and ScopedTensorHandle().
ScopedTensorHandle() [3/4]
ScopedTensorHandle (const ConstTensorHandle & tensorHandle) explicit
Definition at line 66 of file TensorHandle.cpp.
: ScopedTensorHandle(tensorHandle.GetTensorInfo())
{
    CopyFrom(tensorHandle.GetConstTensor<void>(), tensorHandle.GetTensorInfo().GetNumBytes());
}
References ConstTensorHandle::GetConstTensor(), TensorInfo::GetNumBytes(), ConstTensorHandle::GetTensorInfo(), and ScopedTensorHandle().
ScopedTensorHandle() [4/4]
ScopedTensorHandle (const ScopedTensorHandle & other)
Definition at line 72 of file TensorHandle.cpp.
: TensorHandle(other.GetTensorInfo())
{
    CopyFrom(other);
}
References ConstTensorHandle::GetTensorInfo(), ScopedTensorHandle(), and TensorHandle::TensorHandle().
~ScopedTensorHandle()
~ScopedTensorHandle ()
Definition at line 86 of file TensorHandle.cpp.
{
    ::operator delete(GetTensor<void>());
}
References TensorHandle::GetTensor().
Member Function Documentation
Allocate()
void Allocate () override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 91 of file TensorHandle.cpp.
{
    if (GetTensor<void>() == nullptr)
    {
        SetMemory(::operator new(GetTensorInfo().GetNumBytes()));
    }
    else
    {
        throw InvalidArgumentException("TensorHandle::Allocate Trying to allocate a TensorHandle"
            "that already has allocated memory.");
    }
}
References TensorHandle::GetTensor(), ConstTensorHandle::GetTensorInfo(), and TensorHandle::SetMemory().
operator=()
ScopedTensorHandle & operator= (const ScopedTensorHandle & other)
Definition at line 78 of file TensorHandle.cpp.
{
    ::operator delete(GetTensor<void>());
    SetMemory(nullptr);
    CopyFrom(other);
    return *this;
}
References TensorHandle::GetTensor(), ScopedTensorHandle(), and TensorHandle::SetMemory().
The documentation for this class was generated from the following files:
include/armnn/backends/TensorHandle.hpp
src/backends/backendsCommon/TensorHandle.cpp