Arm NN: OptimizeForTypeImpl< BaseType, Wrapped > Class Template Reference
OptimizeForTypeImpl< BaseType, Wrapped > Class Template Reference
Wrapper Optimization base class that calls Wrapped::Run() for every layer of type BaseType.
#include <Optimization.hpp>
Public Member Functions
void Run (Graph &graph, Layer &base) const override
Public Member Functions inherited from Optimization
Optimization ()=default
virtual ~Optimization ()=default
Protected Member Functions
~OptimizeForTypeImpl ()=default
Detailed Description
template<typename BaseType, typename Wrapped>
class armnn::OptimizeForTypeImpl< BaseType, Wrapped >
Wrapper Optimization base class that calls Wrapped::Run() for every layer of type BaseType.
Wrapped class mustn't remove the base layer. The optimizer will remove it if left unconnected after applying each optimization.
Definition at line 33 of file Optimization.hpp.
Constructor & Destructor Documentation
~OptimizeForTypeImpl()
template<typename BaseType, typename Wrapped> ~OptimizeForTypeImpl () protected default
Member Function Documentation
Run()
template<typename BaseType, typename Wrapped> void Run (Graph & graph, Layer & base) const inline override virtual
Implements Optimization.
Definition at line 38 of file Optimization.hpp.
    {
        if (base.GetType() == LayerEnumOf<BaseType>())
        {
            Wrapped::Run(graph, *PolymorphicDowncast<BaseType*>(&base));
        }
    }
References Layer::GetType(), armnn::LayerEnumOf(), and armnn::PolymorphicDowncast().
The documentation for this class was generated from the following file:
src/armnn/optimizations/Optimization.hpp