Arm NN: ClImportSubTensorHandle Class Reference
ClImportSubTensorHandle Class Reference
#include <ClImportTensorHandle.hpp>
Public Member Functions
ClImportSubTensorHandle (IClTensorHandle *parent, const arm_compute::TensorShape &shape, const arm_compute::Coordinates &coords)
arm_compute::CLSubTensor & GetTensor () override
arm_compute::CLSubTensor const & GetTensor () const override
virtual void Allocate () override
Indicate to the memory manager that this resource is no longer active.
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual const void * Map (bool blocking=true) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual arm_compute::DataType GetDataType () const override
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > &memoryGroup) override
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo)
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Detailed Description
Definition at line 336 of file ClImportTensorHandle.hpp.
Constructor & Destructor Documentation
ClImportSubTensorHandle()
ClImportSubTensorHandle (IClTensorHandle * parent, const arm_compute::TensorShape & shape, const arm_compute::Coordinates & coords) inline
Definition at line 339 of file ClImportTensorHandle.hpp.
    : m_Tensor(&parent->GetTensor(), shape, coords)
    {
        parentHandle = parent;
    }
References GetTensor().
Member Function Documentation
Allocate()
virtual void Allocate () inline override virtual
Indicate to the memory manager that this resource is no longer active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 350 of file ClImportTensorHandle.hpp.
{}
GetDataType()
virtual arm_compute::DataType GetDataType () const inline override virtual
Implements IClTensorHandle.
Definition at line 362 of file ClImportTensorHandle.hpp.
    {
        return m_Tensor.info()->data_type();
    }
GetParent()
virtual ITensorHandle * GetParent () const inline override virtual
Get the parent tensor if this is a subtensor.
Returns
a pointer to the parent tensor. Otherwise nullptr if not a subtensor.
Implements ITensorHandle.
Definition at line 360 of file ClImportTensorHandle.hpp.
{ return parentHandle; }
GetShape()
TensorShape GetShape () const inline override virtual
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
Returns
a TensorShape filled with the number of elements for each dimension.
Implements ITensorHandle.
Definition at line 377 of file ClImportTensorHandle.hpp.
    {
        return armcomputetensorutils::GetShape(m_Tensor.info()->tensor_shape());
    }
GetStrides()
TensorShape GetStrides () const inline override virtual
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
Returns
a TensorShape filled with the strides for each dimension
Implements ITensorHandle.
Definition at line 372 of file ClImportTensorHandle.hpp.
    {
        return armcomputetensorutils::GetStrides(m_Tensor.info()->strides_in_bytes());
    }
GetTensor() [1/2]
arm_compute::CLSubTensor const & GetTensor () const inline override virtual
Implements IClTensorHandle.
Definition at line 348 of file ClImportTensorHandle.hpp.
{ return m_Tensor; }
GetTensor() [2/2]
arm_compute::CLSubTensor & GetTensor () inline override virtual
Implements IClTensorHandle.
Definition at line 347 of file ClImportTensorHandle.hpp.
{ return m_Tensor; }
Referenced by ClImportSubTensorHandle().
Manage()
virtual void Manage () inline override virtual
Indicate to the memory manager that this resource is active.
This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 351 of file ClImportTensorHandle.hpp.
{}
Map()
virtual const void * Map (bool blocking = true) const inline override virtual
Map the tensor data for access.
Parameters
blocking hint to block the calling thread until all other accesses are complete. (backend dependent)
Returns
pointer to the first element of the mapped data.
Implements ITensorHandle.
Definition at line 353 of file ClImportTensorHandle.hpp.
    {
        IgnoreUnused(blocking);
        return static_cast<const void*>(m_Tensor.buffer() + m_Tensor.info()->offset_first_element_in_bytes());
    }
References armnn::IgnoreUnused().
SetMemoryGroup()
virtual void SetMemoryGroup (const std::shared_ptr< arm_compute::IMemoryGroup > & memoryGroup) inline override virtual
Implements IClTensorHandle.
Definition at line 367 of file ClImportTensorHandle.hpp.
    {
        IgnoreUnused(memoryGroup);
    }
References armnn::IgnoreUnused().
Unmap()
virtual void Unmap () const inline override virtual
Unmap the tensor data.
Implements ITensorHandle.
Definition at line 358 of file ClImportTensorHandle.hpp.
{}
The documentation for this class was generated from the following file:
src/backends/cl/ClImportTensorHandle.hpp