Arm NN: TensorHandle Class Reference
TensorHandle Class Reference
#include <TensorHandle.hpp>
Public Member Functions
template<typename T>
T * GetTensor () const
template<>
void * GetTensor () const
template<>
void * GetTensor () const
template<>
void * GetTensor () const
Public Member Functions inherited from ConstTensorHandle
template<typename T>
const T * GetConstTensor () const
const TensorInfo & GetTensorInfo () const
virtual void Manage () override
Indicate to the memory manager that this resource is active.
virtual ITensorHandle * GetParent () const override
Get the parent tensor if this is a subtensor.
virtual const void * Map (bool) const override
Map the tensor data for access.
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
Get the strides for each dimension ordered from largest to smallest where the smallest value is the same as the size of a single element in the tensor.
TensorShape GetShape () const override
Get the number of elements for each dimension ordered from slowest iterating dimension to fastest iterating dimension.
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
virtual void Allocate ()=0
Indicate to the memory manager that this resource is no longer active.
void * Map (bool blocking=true)
Map the tensor data for access.
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Import externally allocated memory.
virtual bool CanBeImported (void *memory, MemorySource source)
Implementations must determine if this memory block can be imported.
virtual void Unimport ()
Unimport externally allocated memory.
virtual std::shared_ptr< ITensorHandle > DecorateTensorHandle (const TensorInfo &tensorInfo)
Returns a decorated version of this TensorHandle allowing us to override the TensorInfo for it.
Protected Member Functions
TensorHandle (const TensorInfo &tensorInfo)
void SetMemory (void *mem)
Protected Member Functions inherited from ConstTensorHandle
ConstTensorHandle (const TensorInfo &tensorInfo)
void SetConstMemory (const void *mem)
Detailed Description
Definition at line 79 of file TensorHandle.hpp.
Constructor & Destructor Documentation
TensorHandle()
TensorHandle (const TensorInfo & tensorInfo) protected
Definition at line 43 of file TensorHandle.cpp.
: ConstTensorHandle(tensorInfo)
, m_MutableMemory(nullptr)
{
}
References ConstTensorHandle::ConstTensorHandle().
Referenced by PassthroughTensorHandle::PassthroughTensorHandle(), ScopedTensorHandle::ScopedTensorHandle(), and ScopedTensorHandle::ScopedTensorHandle().
Member Function Documentation
GetTensor() [1/4]
template<typename T> T * GetTensor () const inline
Definition at line 83 of file TensorHandle.hpp.
    {
        if (armnnUtils::CompatibleTypes<T>(GetTensorInfo().GetDataType()))
        {
            return reinterpret_cast<T*>(m_MutableMemory);
        }
        else
        {
            throw armnn::Exception("Attempting to get not compatible type tensor!");
        }
    }
References armnnUtils::CompatibleTypes(), and ConstTensorHandle::GetTensorInfo().
Referenced by ScopedTensorHandle::Allocate(), ScopedTensorHandle::operator=(), and ScopedTensorHandle::~ScopedTensorHandle().
GetTensor() [2/4]
template<> void * GetTensor () const
GetTensor() [3/4]
template<> void * GetTensor () const
GetTensor() [4/4]
template<> void * GetTensor () const
Definition at line 50 of file TensorHandle.cpp.
{
    return m_MutableMemory;
}
SetMemory()
void SetMemory (void * mem) inline protected
Definition at line 98 of file TensorHandle.hpp.
    {
        m_MutableMemory = mem;
        SetConstMemory(m_MutableMemory);
    }
References ConstTensorHandle::SetConstMemory().
Referenced by ScopedTensorHandle::Allocate(), ScopedTensorHandle::operator=(), and PassthroughTensorHandle::PassthroughTensorHandle().
The documentation for this class was generated from the following files:
include/armnn/backends/TensorHandle.hpp
src/backends/backendsCommon/TensorHandle.cpp