Arm NN: FoldPadIntoDepthwiseConvolution2dImpl Class Reference
FoldPadIntoDepthwiseConvolution2dImpl Class Reference
#include <FoldPadIntoLayer2d.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Protected Member Functions
FoldPadIntoDepthwiseConvolution2dImpl ()=default
~FoldPadIntoDepthwiseConvolution2dImpl ()=default
Detailed Description
Definition at line 238 of file FoldPadIntoLayer2d.hpp.
Constructor & Destructor Documentation
FoldPadIntoDepthwiseConvolution2dImpl()
FoldPadIntoDepthwiseConvolution2dImpl () protected default
~FoldPadIntoDepthwiseConvolution2dImpl()
~FoldPadIntoDepthwiseConvolution2dImpl () protected default
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Definition at line 241 of file FoldPadIntoLayer2d.hpp.
    {
        const auto newConv2dLayer = FoldPadIntoLayer2dImpl<DepthwiseConvolution2dLayer>(graph, connection);
        if (newConv2dLayer != nullptr)
        {
            const auto conv2dLayer = PolymorphicDowncast<DepthwiseConvolution2dLayer*>(&connection.GetOwningLayer());
            ARMNN_ASSERT_MSG(newConv2dLayer->GetInputSlot(1).GetConnection() != nullptr,
                             "FoldPadIntoDepthwiseConvolution2d: New convolution layer is missing "
                             "connection to weights layer");
            if (conv2dLayer->GetParameters().m_BiasEnabled)
            {
                ARMNN_ASSERT_MSG(newConv2dLayer->GetInputSlot(2).GetConnection() != nullptr,
                                 "FoldPadIntoConvolution2d: New convolution layer is missing "
                                 "connection to bias layer.");
            }
        }
    }
References ARMNN_ASSERT_MSG, armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), InputSlot::GetOwningLayer(), and armnn::PolymorphicDowncast().
The documentation for this class was generated from the following file:
src/armnn/optimizations/FoldPadIntoLayer2d.hpp