Arm NN: Float16Encoder Class Reference
Float16Encoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
Float16Encoder (Half *data)
Float16Encoder ()
void Set (float right) override
float Get () const override
Public Member Functions inherited from TypedIterator< Half, Encoder< float > >
TypedIterator (Half *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Encoder< float >
Encoder ()
virtual ~Encoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< Half, Encoder< float > >
Half * m_Iterator
Half * m_Start
Detailed Description
Definition at line 582 of file BaseIterator.hpp.
Constructor & Destructor Documentation
Float16Encoder() [1/2]
Float16Encoder (Half * data) inline
Definition at line 585 of file BaseIterator.hpp.
        : TypedIterator(data) {}
References TypedIterator< Half, Encoder< float > >::TypedIterator().
Referenced by Float16Encoder().
Float16Encoder() [2/2]
Float16Encoder () inline
Definition at line 588 of file BaseIterator.hpp.
        : Float16Encoder(nullptr) {}
References Float16Encoder().
Member Function Documentation
Get()
float Get () const inline override virtual
Implements Encoder< float >.
Definition at line 596 of file BaseIterator.hpp.
    {
        float val = 0.f;
        armnnUtils::FloatingPointConverter::ConvertFloat16To32(m_Iterator, 1, &val);
        return val;
    }
References FloatingPointConverter::ConvertFloat16To32(), and TypedIterator< Half, Encoder< float > >::m_Iterator.
Set()
void Set (float right) inline override virtual
Implements Encoder< float >.
Definition at line 591 of file BaseIterator.hpp.
    {
        armnnUtils::FloatingPointConverter::ConvertFloat32To16(&right, 1, m_Iterator);
    }
References FloatingPointConverter::ConvertFloat32To16(), and TypedIterator< Half, Encoder< float > >::m_Iterator.
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp