Arm NN: Convolution3dLayer Class Reference
Convolution3dLayer Class Reference
This layer represents a convolution 3d operation.
#include <Convolution3dLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the Convolution3d type.
Convolution3dLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of Convolution3dLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string.
Public Member Functions inherited from LayerWithParameters< Convolution3dDescriptor >
const Convolution3dDescriptor & GetParameters () const override
If the layer has a descriptor return it.
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id) override
Set the backend of the IConnectableLayer.
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
Infer the shape of the output(s) based on the provided input shape(s)
virtual void ReleaseConstantData ()
template<typename Op>
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer * >::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T>
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
Protected Member Functions
Convolution3dLayer (const Convolution3dDescriptor &param, const char *name)
Constructor to create a Convolution3dLayer.
~Convolution3dLayer ()=default
Default destructor.
Protected Member Functions inherited from LayerWithParameters< Convolution3dDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const Convolution3dDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Layer::ImmutableConstantTensors GetConnectedConstantAsInputTensors () const
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor>
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor>
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor>
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType, typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef () override final
virtual ImmutableConstantTensors GetConstantTensorsByRef () const override
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< Convolution3dDescriptor >
using DescriptorType
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector<std::reference_wrapper<std::shared_ptr<ConstTensorHandle>>>
using ImmutableConstantTensors = std::vector<std::reference_wrapper<const std::shared_ptr<ConstTensorHandle>>>
Protected Attributes inherited from LayerWithParameters< Convolution3dDescriptor >
Convolution3dDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a convolution 3d operation.
Definition at line 16 of file Convolution3dLayer.hpp.
Constructor & Destructor Documentation
Convolution3dLayer()
Convolution3dLayer (const Convolution3dDescriptor & param, const char * name) protected
Constructor to create a Convolution3dLayer.
Parameters
[in] param Convolution3dDescriptor to configure the convolution3d operation.
[in] name Optional name for the layer.
Definition at line 18 of file Convolution3dLayer.cpp.
    : LayerWithParameters(param.GetNumInputs(), 1, LayerType::Convolution3d, param, name)
{
}
References armnn::Convolution3d, armnn::GetNumInputs(), and LayerWithParameters< Convolution3dDescriptor >::LayerWithParameters().
Referenced by Clone().
~Convolution3dLayer()
~Convolution3dLayer () protected default
Default destructor.
Member Function Documentation
Clone()
Convolution3dLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 56 of file Convolution3dLayer.cpp.
{
    auto layer = CloneBase<Convolution3dLayer>(graph, m_Param, GetName());
    return std::move(layer);
}
References Layer::CloneBase(), Convolution3dLayer(), Layer::GetName(), and LayerWithParameters< Convolution3dDescriptor >::m_Param.
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the Convolution3d type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 48 of file Convolution3dLayer.cpp.
{
    Convolution3dQueueDescriptor descriptor;
    SetAdditionalInfo(descriptor);
    return factory.CreateWorkload(LayerType::Convolution3d, descriptor, PrepInfoAndDesc(descriptor));
}
References armnn::Convolution3d, IWorkloadFactory::CreateWorkload(), LayerWithParameters< Convolution3dDescriptor >::PrepInfoAndDesc(), and Layer::SetAdditionalInfo().
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Implements IConnectableLayer.
Definition at line 153 of file Convolution3dLayer.cpp.
{
    strategy.ExecuteStrategy(this, GetParameters(), {}, GetName());
}
References IStrategy::ExecuteStrategy(), Layer::GetName(), and LayerWithParameters< Convolution3dDescriptor >::GetParameters().
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Implements IConnectableLayer.
Definition at line 62 of file Convolution3dLayer.cpp.
{
    if (inputShapes.size() != 2)
    {
        throw armnn::Exception("inputShapes' size is \"" + std::to_string(inputShapes.size()) +
                               "\" - should be \"2\".");
    }
    const TensorShape& inputShape = inputShapes[0];
    const TensorShape& filterShape = inputShapes[1];
    if (inputShape.GetNumDimensions() != 5)
    {
        throw armnn::Exception("Convolutions will always have 5D input.");
    }
    if (m_Param.m_StrideX == 0)
    {
        throw armnn::Exception("m_StrideX cannot be 0.");
    }
    if (m_Param.m_StrideY == 0)
    {
        throw armnn::Exception("m_StrideY cannot be 0.");
    }
    if (m_Param.m_StrideZ == 0)
    {
        throw armnn::Exception("m_StrideZ cannot be 0.");
    }
    DataLayoutIndexed dataLayoutIndex(m_Param.m_DataLayout);
    unsigned int inWidth = inputShape[dataLayoutIndex.GetWidthIndex()];
    unsigned int inHeight = inputShape[dataLayoutIndex.GetHeightIndex()];
    unsigned int inDepth = inputShape[dataLayoutIndex.GetDepthIndex()];
    unsigned int inBatchSize = inputShape[0];
    // Conv3d Filter Layout: [D,H,W,I,O]
    unsigned int filterDepth = filterShape[0];
    unsigned int dilatedFilterDepth = filterDepth + (m_Param.m_DilationZ - 1) * (filterDepth - 1);
    unsigned int readDepth = (inDepth + m_Param.m_PadFront + m_Param.m_PadBack) - dilatedFilterDepth;
    unsigned int outDepth = 1 + (readDepth / m_Param.m_StrideZ);
    unsigned int filterHeight = filterShape[1];
    unsigned int dilatedFilterHeight = filterHeight + (m_Param.m_DilationY - 1) * (filterHeight - 1);
    unsigned int readHeight = (inHeight + m_Param.m_PadTop + m_Param.m_PadBottom) - dilatedFilterHeight;
    unsigned int outHeight = 1 + (readHeight / m_Param.m_StrideY);
    unsigned int filterWidth = filterShape[2];
    unsigned int dilatedFilterWidth = filterWidth + (m_Param.m_DilationX - 1) * (filterWidth - 1);
    unsigned int readWidth = (inWidth + m_Param.m_PadLeft + m_Param.m_PadRight) - dilatedFilterWidth;
    unsigned int outWidth = 1 + (readWidth / m_Param.m_StrideX);
    unsigned int outChannels = filterShape[4];
    unsigned int outBatchSize = inBatchSize;
    TensorShape tensorShape = m_Param.m_DataLayout == armnn::DataLayout::NDHWC ?
            TensorShape( { outBatchSize, outDepth, outHeight, outWidth, outChannels } ) :
            TensorShape( { outBatchSize, outChannels, outDepth, outHeight, outWidth });
    return std::vector<TensorShape>({ tensorShape });
}
References DataLayoutIndexed::GetDepthIndex(), DataLayoutIndexed::GetHeightIndex(), TensorShape::GetNumDimensions(), DataLayoutIndexed::GetWidthIndex(), LayerWithParameters< Convolution3dDescriptor >::m_Param, and armnn::NDHWC.
Referenced by ValidateTensorShapesFromInputs().
SerializeLayerParameters()
void SerializeLayerParameters (ParameterStringifyFunction & fn) const override virtual
Helper to serialize the layer parameters to string.
(currently used in DotSerializer and company).
Reimplemented from Layer.
Definition at line 23 of file Convolution3dLayer.cpp.
{
    const std::vector<TensorShape>& inputShapes =
    {
        GetInputSlot(0).GetTensorInfo().GetShape(),
        GetInputSlot(1).GetTensorInfo().GetShape(),
    };
    // Conv3d Filter Layout: [D,H,W,I,O]
    const TensorShape filterShape = inputShapes[1];
    unsigned int filterDepth = filterShape[0];
    unsigned int filterHeight = filterShape[1];
    unsigned int filterWidth = filterShape[2];
    unsigned int inChannels = filterShape[3];
    unsigned int outChannels = filterShape[4];
    fn("FilterDepth",std::to_string(filterDepth));
    fn("FilterHeight",std::to_string(filterHeight));
    fn("FilterWidth",std::to_string(filterWidth));
    fn("InputChannels",std::to_string(inChannels));
    fn("OutputChannels",std::to_string(outChannels));
    LayerWithParameters<Convolution3dDescriptor>::SerializeLayerParameters(fn);
}
References Layer::GetInputSlot(), TensorInfo::GetShape(), InputSlot::GetTensorInfo(), and LayerWithParameters< Parameters >::SerializeLayerParameters().
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of Convolution3dLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 126 of file Convolution3dLayer.cpp.
{
    VerifyLayerConnections(m_Param.GetNumInputs(), CHECK_LOCATION());
    const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
    VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
    if (!GetInputSlot(1).GetConnection())
    {
        throw armnn::LayerValidationException("Convolution3dLayer: Weights should be connected to input slot 1.");
    }
    auto inferredShapes = InferOutputShapes({
        GetInputSlot(0).GetTensorInfo().GetShape(),
        GetInputSlot(1).GetTensorInfo().GetShape() });
    if (inferredShapes.size() != 1)
    {
        throw armnn::LayerValidationException("inferredShapes has "
                                              + std::to_string(inferredShapes.size()) +
                                              " elements - should only have 1.");
    }
    ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "Convolution3dLayer");
}
References CHECK_LOCATION, Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), InputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), InferOutputShapes(), LayerWithParameters< Convolution3dDescriptor >::m_Param, Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
The documentation for this class was generated from the following files:
src/armnn/layers/Convolution3dLayer.hpp
src/armnn/layers/Convolution3dLayer.cpp