Arm NN: ClChannelShuffleWorkload Class Reference
ClChannelShuffleWorkload Class Reference
#include <ClChannelShuffleWorkload.hpp>
Public Member Functions
ClChannelShuffleWorkload (const ChannelShuffleQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
virtual void Execute () const override
Public Member Functions inherited from ClBaseWorkload< ChannelShuffleQueueDescriptor >
ClBaseWorkload (const ChannelShuffleQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< ChannelShuffleQueueDescriptor >
BaseWorkload (const ChannelShuffleQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const ChannelShuffleQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< ChannelShuffleQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< ChannelShuffleQueueDescriptor >
ChannelShuffleQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 20 of file ClChannelShuffleWorkload.hpp.
Constructor & Destructor Documentation
ClChannelShuffleWorkload()
ClChannelShuffleWorkload (const ChannelShuffleQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 54 of file ClChannelShuffleWorkload.cpp.
    : ClBaseWorkload<ChannelShuffleQueueDescriptor>(descriptor, info)
{
    // Report Profiling Details
    ARMNN_REPORT_PROFILING_WORKLOAD_DESC("ClChannelShufflenWorkload_Construct",
                                         descriptor.m_Parameters,
                                         info,
                                         this->GetGuid());
    m_Data.ValidateInputsOutputs("ClChannelShuffleWorkload", 1, 1);
    arm_compute::ICLTensor& input  = PolymorphicDowncast<ClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
    arm_compute::ICLTensor& output = PolymorphicDowncast<ClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
    // In Arm NN and in NNAPI, channel shuffle implementation is datalayout agnostic and it has axis as a parameter.
    // The channel shuffle Implementation for Neon is dependent on datalayout and does not have axis as a parameter,
    // it only supports channel shuffle for 4D tensors in dimension C (1 or 3).
    arm_compute::DataLayout aclDataLayout;
    switch (descriptor.m_Parameters.m_Axis)
    {
        case 1:
            aclDataLayout = ConvertDataLayout(armnn::DataLayout::NCHW);
            break;
        case 3:
            aclDataLayout = ConvertDataLayout(armnn::DataLayout::NHWC);
            break;
        default:
            throw InvalidArgumentException("Value for axis: " + std::to_string(descriptor.m_Parameters.m_Axis) +
                                           " is not valid");
    }
    input.info()->set_data_layout(aclDataLayout);
    output.info()->set_data_layout(aclDataLayout);
    {
        ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID("ClChannelShuffleWorkload_configure");
        m_ChannelShuffleLayer.configure(clCompileContext, &input, &output, descriptor.m_Parameters.m_NumGroups);
    }
}
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID, ClBaseWorkload< ChannelShuffleQueueDescriptor >::ClBaseWorkload(), armnn::info, ChannelShuffleDescriptor::m_Axis, BaseWorkload< ChannelShuffleQueueDescriptor >::m_Data, ChannelShuffleDescriptor::m_NumGroups, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::NCHW, armnn::NHWC, and armnn::PolymorphicDowncast().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 95 of file ClChannelShuffleWorkload.cpp.
{
    ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID("ClChannelShuffleWorkload_Execute");
    RunClFunction(m_ChannelShuffleLayer, CHECK_LOCATION());
}
References ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID, CHECK_LOCATION, and armnn::RunClFunction().
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClChannelShuffleWorkload.hpp
src/backends/cl/workloads/ClChannelShuffleWorkload.cpp