Arm NN: TosaRefTensorHandleFactory Class Reference
TosaRefTensorHandleFactory Class Reference
#include <TosaRefTensorHandleFactory.hpp>
Public Member Functions
TosaRefTensorHandleFactory (std::shared_ptr< TosaRefMemoryManager > mgr)
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const override
Utility Functions for backends which require TensorHandles to have unmanaged memory.
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override
const FactoryId & GetId () const override
bool SupportsSubTensors () const override
MemorySourceFlags GetExportFlags () const override
MemorySourceFlags GetImportFlags () const override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual bool SupportsInPlaceComputation () const
virtual bool SupportsMapUnmap () const
virtual std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass)
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Detailed Description
Definition at line 17 of file TosaRefTensorHandleFactory.hpp.
Constructor & Destructor Documentation
TosaRefTensorHandleFactory()
TosaRefTensorHandleFactory (std::shared_ptr< TosaRefMemoryManager > mgr) inline
Definition at line 21 of file TosaRefTensorHandleFactory.hpp.
    : m_MemoryManager(mgr)
    , m_ImportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc))
    , m_ExportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc))
    {}
References armnn::Malloc.
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 22 of file TosaRefTensorHandleFactory.cpp.
{
    IgnoreUnused(parent, subTensorShape, subTensorOrigin);
    return nullptr;
}
References armnn::IgnoreUnused().
CreateTensorHandle() [1/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 31 of file TosaRefTensorHandleFactory.cpp.
{
    return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_MemoryManager);
}
CreateTensorHandle() [2/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged) const override virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented from ITensorHandleFactory.
Definition at line 43 of file TosaRefTensorHandleFactory.cpp.
{
    if (IsMemoryManaged)
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_MemoryManager);
    }
    else
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_ImportFlags);
    }
}
CreateTensorHandle() [3/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 36 of file TosaRefTensorHandleFactory.cpp.
{
    IgnoreUnused(dataLayout);
    return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_MemoryManager);
}
References armnn::IgnoreUnused().
CreateTensorHandle() [4/4]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 56 of file TosaRefTensorHandleFactory.cpp.
{
    IgnoreUnused(dataLayout);
    if (IsMemoryManaged)
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_MemoryManager);
    }
    else
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_ImportFlags);
    }
}
References armnn::IgnoreUnused().
GetExportFlags()
MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 81 of file TosaRefTensorHandleFactory.cpp.
{
    return m_ExportFlags;
}
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 71 of file TosaRefTensorHandleFactory.cpp.
{
    return GetIdStatic();
}
References GetIdStatic().
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 16 of file TosaRefTensorHandleFactory.cpp.
{
    static const FactoryId s_Id(TosaRefTensorHandleFactoryId());
    return s_Id;
}
References armnn::TosaRefTensorHandleFactoryId().
Referenced by TosaRefBackend::GetHandleFactoryPreferences(), and GetId().
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 86 of file TosaRefTensorHandleFactory.cpp.
{
    return m_ImportFlags;
}
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 76 of file TosaRefTensorHandleFactory.cpp.
{
    return false;
}
The documentation for this class was generated from the following files:
src/backends/tosaReference/TosaRefTensorHandleFactory.hpp
src/backends/tosaReference/TosaRefTensorHandleFactory.cpp