Arm NN: IOnnxParser Class Reference
IOnnxParser Class Reference
#include <IOnnxParser.hpp>
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent)
Create the network from a protobuf binary vector.
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network from a protobuf binary vector, with inputShapes specified.
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile)
Create the network from a protobuf binary file on disk.
armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile)
Create the network from a protobuf text file on disk.
armnn::INetworkPtr CreateNetworkFromString (const std::string &protoText)
Create the network directly from protobuf text in a string. Useful for debugging/testing.
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network from a protobuf binary file on disk, with inputShapes specified.
armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network from a protobuf text file on disk, with inputShapes specified.
armnn::INetworkPtr CreateNetworkFromString (const std::string &protoText, const std::map< std::string, armnn::TensorShape > &inputShapes)
Create the network directly from protobuf text in a string, with inputShapes specified.
BindingPointInfo GetNetworkInputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
BindingPointInfo GetNetworkOutputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Static Public Member Functions
static IOnnxParser * CreateRaw ()
static IOnnxParserPtr Create ()
static void Destroy (IOnnxParser *parser)
Detailed Description
Definition at line 23 of file IOnnxParser.hpp.
Member Function Documentation
Create()
IOnnxParserPtr Create () static
Definition at line 38 of file OnnxParser.cpp.
{
ARMNN_NO_DEPRECATE_WARN_BEGIN
    return IOnnxParserPtr(CreateRaw(), &IOnnxParser::Destroy);
ARMNN_NO_DEPRECATE_WARN_END
}
References ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, Create(), CreateRaw(), and Destroy().
Referenced by Create().
CreateNetworkFromBinary() [1/2]
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent)
Create the network from a protobuf binary vector.
Definition at line 55 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromBinary(binaryContent);
}
References CreateNetworkFromBinary().
Referenced by CreateNetworkFromBinary(), and CreateNetworkFromBinary().
CreateNetworkFromBinary() [2/2]
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network from a protobuf binary vector, with inputShapes specified.
Definition at line 60 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromBinary(binaryContent, inputShapes);
}
References CreateNetworkFromBinary().
CreateNetworkFromBinaryFile() [1/2]
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile)
Create the network from a protobuf binary file on disk.
Definition at line 50 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromBinaryFile(graphFile);
}
References CreateNetworkFromBinaryFile().
Referenced by CreateNetworkFromBinaryFile(), and CreateNetworkFromBinaryFile().
CreateNetworkFromBinaryFile() [2/2]
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network from a protobuf binary file on disk, with inputShapes specified.
Definition at line 76 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromBinaryFile(graphFile, inputShapes);
}
References CreateNetworkFromBinaryFile().
CreateNetworkFromString() [1/2]
armnn::INetworkPtr CreateNetworkFromString (const std::string & protoText)
Create the network directly from protobuf text in a string. Useful for debugging/testing.
Definition at line 71 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromString(protoText);
}
References CreateNetworkFromString().
Referenced by CreateNetworkFromString(), and CreateNetworkFromString().
CreateNetworkFromString() [2/2]
armnn::INetworkPtr CreateNetworkFromString (const std::string & protoText, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network directly from protobuf text in a string, with inputShapes specified.
Useful for debugging/testing
Definition at line 89 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromString(protoText, inputShapes);
}
References CreateNetworkFromString().
CreateNetworkFromTextFile() [1/2]
armnn::INetworkPtr CreateNetworkFromTextFile (const char * graphFile)
Create the network from a protobuf text file on disk.
Definition at line 66 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromTextFile(graphFile);
}
References CreateNetworkFromTextFile().
Referenced by CreateNetworkFromTextFile(), and CreateNetworkFromTextFile().
CreateNetworkFromTextFile() [2/2]
armnn::INetworkPtr CreateNetworkFromTextFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes)
Create the network from a protobuf text file on disk, with inputShapes specified.
Definition at line 83 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->CreateNetworkFromTextFile(graphFile, inputShapes);
}
References CreateNetworkFromTextFile().
CreateRaw()
IOnnxParser * CreateRaw () static
Definition at line 33 of file OnnxParser.cpp.
{
    return new IOnnxParser();
}
References CreateRaw().
Referenced by Create(), and CreateRaw().
Destroy()
void Destroy (IOnnxParser * parser) static
Definition at line 45 of file OnnxParser.cpp.
{
    delete parser;
}
References Destroy().
Referenced by Create(), and Destroy().
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Definition at line 95 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->GetNetworkInputBindingInfo(name);
}
References GetNetworkInputBindingInfo().
Referenced by GetNetworkInputBindingInfo().
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Definition at line 100 of file OnnxParser.cpp.
{
    return pOnnxParserImpl->GetNetworkOutputBindingInfo(name);
}
References GetNetworkOutputBindingInfo().
Referenced by GetNetworkOutputBindingInfo().
The documentation for this class was generated from the following files:
include/armnnOnnxParser/IOnnxParser.hpp
src/armnnOnnxParser/OnnxParser.cpp