Arm NN: NeonConvolution3dWorkload Class Reference
NeonConvolution3dWorkload Class Reference
#include <NeonConvolution3dWorkload.hpp>
Public Member Functions
NeonConvolution3dWorkload (const Convolution3dQueueDescriptor &descriptor, const WorkloadInfo &info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager, const bool isFastMathENabled=false)
void Execute () const override
Public Member Functions inherited from NeonBaseWorkload< Convolution3dQueueDescriptor >
NeonBaseWorkload (const Convolution3dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< Convolution3dQueueDescriptor >
BaseWorkload (const Convolution3dQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const Convolution3dQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from NeonBaseWorkload< Convolution3dQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< Convolution3dQueueDescriptor >
Convolution3dQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 27 of file NeonConvolution3dWorkload.hpp.
Constructor & Destructor Documentation
NeonConvolution3dWorkload()
NeonConvolution3dWorkload (const Convolution3dQueueDescriptor & descriptor, const WorkloadInfo & info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager, const bool isFastMathENabled = false)
Definition at line 60 of file NeonConvolution3dWorkload.cpp.
    : NeonBaseWorkload<Convolution3dQueueDescriptor>(descriptor, info)
{
    IgnoreUnused(memoryManager);
    using arm_compute::NEConv3D;
    uint32_t numInputs = m_Data.m_Parameters.m_BiasEnabled ? 3: 2;
    m_Data.ValidateInputsOutputs("NeonConvolution3dWorkload", numInputs, 1);
    arm_compute::ITensor& input = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
    arm_compute::ITensor& weights = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[1])->GetTensor();
    arm_compute::ITensor* biasesPtr = nullptr;
    if (m_Data.m_Parameters.m_BiasEnabled)
    {
        biasesPtr = &PolymorphicDowncast<IAclTensorHandle *>(m_Data.m_Inputs[2])->GetTensor();
    }
    arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
    arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
    input.info()->set_data_layout(aclDataLayout);
    weights.info()->set_data_layout(aclDataLayout);
    output.info()->set_data_layout(aclDataLayout);
    const arm_compute::Conv3dInfo aclConv3DInfo = ComputeConv3DInfo(descriptor, isFastMathEnabled);
    auto convolutionLayer = std::make_unique<arm_compute::NEConv3D>();
    convolutionLayer->configure(&input,
                                &weights,
                                biasesPtr,
                                &output,
                                aclConv3DInfo);
    // Add details for profiling output
    WorkloadInfo detailsInfo;
    detailsInfo.m_InputTensorInfos = info.m_InputTensorInfos;
    detailsInfo.m_OutputTensorInfos = info.m_OutputTensorInfos;
    // Report Profiling Details
    ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonConvolution3dWorkload_Construct",
                                         descriptor.m_Parameters,
                                         detailsInfo,
                                         this->GetGuid());
    m_ConvolutionLayer.reset(convolutionLayer.release());
    m_ConvolutionLayer->prepare();
}
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, armnn::ComputeConv3DInfo(), armnn::IgnoreUnused(), armnn::info, BaseWorkload< Convolution3dQueueDescriptor >::m_Data, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, NeonBaseWorkload< Convolution3dQueueDescriptor >::NeonBaseWorkload(), and armnn::PolymorphicDowncast().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 111 of file NeonConvolution3dWorkload.cpp.
{
    ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID("NeonConvolution3dWorkload_Execute");
    m_ConvolutionLayer->run();
}
References ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID.
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonConvolution3dWorkload.hpp
src/backends/neon/workloads/NeonConvolution3dWorkload.cpp