Arm NN: QSymmS8Encoder Class Reference
QSymmS8Encoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
QSymmS8Encoder (int8_t *data, const float scale, const int32_t offset)
QSymmS8Encoder (const float scale, const int32_t offset)
void Set (float right) override
float Get () const override
Public Member Functions inherited from TypedIterator< int8_t, Encoder< float > >
TypedIterator (int8_t *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Encoder< float >
Encoder ()
virtual ~Encoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< int8_t, Encoder< float > >
int8_t * m_Iterator
int8_t * m_Start
Detailed Description
Definition at line 534 of file BaseIterator.hpp.
Constructor & Destructor Documentation
QSymmS8Encoder() [1/2]
QSymmS8Encoder (int8_t * data, const float scale, const int32_t offset) inline
Definition at line 537 of file BaseIterator.hpp.
            : TypedIterator(data), m_Scale(scale), m_Offset(offset) {}
References TypedIterator< int8_t, Encoder< float > >::TypedIterator().
Referenced by QSymmS8Encoder().
QSymmS8Encoder() [2/2]
QSymmS8Encoder (const float scale, const int32_t offset) inline
Definition at line 540 of file BaseIterator.hpp.
            : QSymmS8Encoder(nullptr, scale, offset) {}
References QSymmS8Encoder().
Member Function Documentation
Get()
float Get () const inline override virtual
Implements Encoder< float >.
Definition at line 548 of file BaseIterator.hpp.
    {
        return armnn::Dequantize(*m_Iterator, m_Scale, m_Offset);
    }
References armnn::Dequantize, and TypedIterator< int8_t, Encoder< float > >::m_Iterator.
Set()
void Set (float right) inline override virtual
Implements Encoder< float >.
Definition at line 543 of file BaseIterator.hpp.
    {
        *m_Iterator = armnn::Quantize<int8_t>(right, m_Scale, m_Offset);
    }
References TypedIterator< int8_t, Encoder< float > >::m_Iterator, and armnn::Quantize.
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp