Arm NN: Layer Class Reference
Layer Class Reference abstract
#include <Layer.hpp>
Public Member Functions
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id) override
Set the backend of the IConnectableLayer.
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const =0
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
virtual Layer * Clone (Graph &graph) const =0
Creates a dynamically-allocated copy of this layer.
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ValidateTensorShapesFromInputs ()=0
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
Infer the shape of the output(s) based on the provided input shape(s)
virtual void SerializeLayerParameters (ParameterStringifyFunction &fn) const
Helper to serialize the layer parameters to string.
virtual void ReleaseConstantData ()
template<typename Op>
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer * >::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T>
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
virtual const BaseDescriptor & GetParameters () const override
If the layer has a descriptor return it.
Protected Member Functions
virtual ~Layer ()=default
template<typename QueueDescriptor>
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor>
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor>
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType, typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef () override final
virtual ImmutableConstantTensors GetConstantTensorsByRef () const override
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Protected Attributes
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Friends
class Graph
Additional Inherited Members
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector<std::reference_wrapper<std::shared_ptr<ConstTensorHandle>>>
using ImmutableConstantTensors = std::vector<std::reference_wrapper<const std::shared_ptr<ConstTensorHandle>>>
Detailed Description
Definition at line 230 of file Layer.hpp.
Constructor & Destructor Documentation
Layer() [1/2]
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char * name)
Parameters
name - Optional name for the layer (may be nullptr).
Definition at line 260 of file Layer.cpp.
: Layer(numInputSlots, numOutputSlots, type, DataLayout::NCHW, name)
{
}
References Layer(), and armnn::NCHW.
Referenced by AbsLayer::AbsLayer(), BindableLayer::BindableLayer(), CastLayer::CastLayer(), Clone(), QuantizeLayer::Clone(), RankLayer::Clone(), ConstantLayer::ConstantLayer(), ConvertFp16ToFp32Layer::ConvertFp16ToFp32Layer(), ConvertFp32ToFp16Layer::ConvertFp32ToFp16Layer(), DebugLayer::CreateWorkload(), DebugLayer::DebugLayer(), DebugLayer::DebugLayer(), DequantizeLayer::DequantizeLayer(), ElementwiseBaseLayer::ElementwiseBaseLayer(), FloorLayer::FloorLayer(), GatherNdLayer::GatherNdLayer(), GetConstantTensorsByRef(), GetOutputHandler(), GetPriority(), Layer(), LayerWithParameters< Parameters >::LayerWithParameters(), MapLayer::MapLayer(), MemCopyLayer::MemCopyLayer(), MemImportLayer::MemImportLayer(), MergeLayer::MergeLayer(), PreluLayer::PreluLayer(), QuantizedLstmLayer::QuantizedLstmLayer(), QuantizeLayer::QuantizeLayer(), RankLayer::RankLayer(), ReverseV2Layer::ReverseV2Layer(), RsqrtLayer::RsqrtLayer(), ShapeLayer::ShapeLayer(), SwitchLayer::SwitchLayer(), and UnmapLayer::UnmapLayer().
Layer() [2/2]
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char * name)
Definition at line 233 of file Layer.cpp.
: m_OutputHandlers(numOutputSlots)
, m_ShapeInferenceMethod(ShapeInferenceMethod::ValidateOnly)
, m_LayerName(name ? name : "")
, m_Type(type)
, m_BackendId()
, m_BackendHint(EmptyOptional())
, m_Guid(arm::pipe::IProfilingService::GetNextGuid())
{
    IgnoreUnused(layout);
    m_InputSlots.reserve(numInputSlots);
    for (unsigned int i = 0; i < numInputSlots; ++i)
    {
        m_InputSlots.emplace_back(*this, i);
    }
    m_OutputSlots.reserve(numOutputSlots);
    for (unsigned int i = 0; i < numOutputSlots; ++i)
    {
        m_OutputSlots.emplace_back(*this, m_OutputHandlers[i]);
    }
}
References armnn::IgnoreUnused(), m_OutputHandlers, m_ShapeInferenceMethod, and armnn::ValidateOnly.
~Layer()
virtual ~Layer () protected virtual default
Member Function Documentation
AddRelatedLayerName()
void AddRelatedLayerName (const std::string layerName) inline
Definition at line 345 of file Layer.hpp.
{ m_RelatedLayerNames.emplace_back(layerName); }
BackendSelectionHint()
void BackendSelectionHint (Optional< BackendId > backend) inline final virtual
Provide a hint for the optimizer as to which backend to prefer for this layer.
By providing a BackendSelectionHint there is no guarantee the input backend supports that layer. If IsLayerSupported() returns false with the backend hint, we default to calling IsLayerSupported() on the BackendPreferences vector. Use SetBackendId() if we can guarantee a backend supports that layer (IsLayerSupported returns true for a specific backend).
Implements IConnectableLayer.
Definition at line 351 of file Layer.hpp.
    {
        m_BackendHint = backend;
    }
BeginInputSlots()
std::vector< InputSlot >::iterator BeginInputSlots () inline
Definition at line 262 of file Layer.hpp.
{ return m_InputSlots.begin(); }
Referenced by CreateInputsFrom(), armnn::InsertConvertFp16ToFp32LayersBefore(), ConvertFp32NetworkToFp16Impl::Run(), MovePermuteUpImpl::Run(), and MoveTransposeUpImpl::Run().
BeginOutputSlots()
std::vector< OutputSlot >::iterator BeginOutputSlots () inline
Definition at line 266 of file Layer.hpp.
{ return m_OutputSlots.begin(); }
Referenced by armnn::InsertDebugLayerAfter(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), ConvertFp32NetworkToFp16Impl::Run(), SquashEqualSiblingsImpl< Comparable >::Run(), and SplitterLayer::ValidateTensorShapesFromInputs().
Clone()
virtual Layer * Clone (Graph & graph) const pure virtual
Creates a dynamically-allocated copy of this layer.
Parameters
graph - The Graph into which this Layer is being cloned.
Implemented in AbsLayer, ActivationLayer, AdditionLayer, ArgMinMaxLayer, BatchMatMulLayer, BatchNormalizationLayer, BatchToSpaceNdLayer, BroadcastToLayer, CastLayer, ChannelShuffleLayer, ComparisonLayer, ConcatLayer, ConstantLayer, ConvertFp16ToFp32Layer, ConvertFp32ToFp16Layer, Convolution2dLayer, Convolution3dLayer, DebugLayer, DepthToSpaceLayer, DepthwiseConvolution2dLayer, DequantizeLayer, DetectionPostProcessLayer, DivisionLayer, ElementwiseBinaryLayer, ElementwiseUnaryLayer, FakeQuantizationLayer, FillLayer, FloorLayer, FullyConnectedLayer, FusedLayer, GatherLayer, GatherNdLayer, InputLayer, InstanceNormalizationLayer, L2NormalizationLayer, LogicalBinaryLayer, LogSoftmaxLayer, LstmLayer, MapLayer, MaximumLayer, MeanLayer, MemCopyLayer, MemImportLayer, MergeLayer, MinimumLayer, MultiplicationLayer, NormalizationLayer, OutputLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreCompiledLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, QuantizeLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, RsqrtLayer, ScatterNdLayer, ShapeLayer, SliceLayer, SoftmaxLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, SubtractionLayer, SwitchLayer, TileLayer, TransposeConvolution2dLayer, TransposeLayer, UnidirectionalSequenceLstmLayer, and UnmapLayer.
References Graph, and Layer().
Referenced by SubgraphView::GetWorkingCopy().
CloneBase()
template<typename LayerType, typename ... Params> LayerType * CloneBase (Graph & graph, Params &&... params) const protected
Definition at line 14 of file LayerCloneBase.hpp.
{
    LayerType* const layer = graph.AddLayer<LayerType>(std::forward<Params>(params)...);
    layer->BackendSelectionHint(GetBackendHint());
    layer->SetBackendId(GetBackendId());
    layer->SetGuid(GetGuid());
    layer->SetShapeInferenceMethod(m_ShapeInferenceMethod);
    layer->SetAllowExpandedDims(m_AllowExpandedDims);
    return layer;
}
References Graph::AddLayer(), GetBackendHint(), GetBackendId(), GetGuid(), Graph, and m_ShapeInferenceMethod.
Referenced by AbsLayer::Clone(), ActivationLayer::Clone(), AdditionLayer::Clone(), ArgMinMaxLayer::Clone(), BatchMatMulLayer::Clone(), BatchNormalizationLayer::Clone(), BatchToSpaceNdLayer::Clone(), BroadcastToLayer::Clone(), CastLayer::Clone(), ChannelShuffleLayer::Clone(), ComparisonLayer::Clone(), ConcatLayer::Clone(), ConstantLayer::Clone(), ConvertFp16ToFp32Layer::Clone(), ConvertFp32ToFp16Layer::Clone(), Convolution2dLayer::Clone(), Convolution3dLayer::Clone(), DebugLayer::Clone(), DepthToSpaceLayer::Clone(), DepthwiseConvolution2dLayer::Clone(), DequantizeLayer::Clone(), DetectionPostProcessLayer::Clone(), DivisionLayer::Clone(), ElementwiseBinaryLayer::Clone(), ElementwiseUnaryLayer::Clone(), FakeQuantizationLayer::Clone(), FillLayer::Clone(), FloorLayer::Clone(), FullyConnectedLayer::Clone(), FusedLayer::Clone(), GatherLayer::Clone(), GatherNdLayer::Clone(), InputLayer::Clone(), InstanceNormalizationLayer::Clone(), L2NormalizationLayer::Clone(), LogicalBinaryLayer::Clone(), LogSoftmaxLayer::Clone(), LstmLayer::Clone(), MapLayer::Clone(), MaximumLayer::Clone(), MeanLayer::Clone(), MemCopyLayer::Clone(), MemImportLayer::Clone(), MergeLayer::Clone(), MinimumLayer::Clone(), MultiplicationLayer::Clone(), NormalizationLayer::Clone(), OutputLayer::Clone(), PadLayer::Clone(), PermuteLayer::Clone(), Pooling2dLayer::Clone(), Pooling3dLayer::Clone(), PreCompiledLayer::Clone(), PreluLayer::Clone(), QLstmLayer::Clone(), QuantizedLstmLayer::Clone(), QuantizeLayer::Clone(), RankLayer::Clone(), ReduceLayer::Clone(), ReshapeLayer::Clone(), ResizeLayer::Clone(), ReverseV2Layer::Clone(), RsqrtLayer::Clone(), ScatterNdLayer::Clone(), ShapeLayer::Clone(), SliceLayer::Clone(), SoftmaxLayer::Clone(), SpaceToBatchNdLayer::Clone(), SpaceToDepthLayer::Clone(), SplitterLayer::Clone(), StackLayer::Clone(), StandInLayer::Clone(), StridedSliceLayer::Clone(), SubtractionLayer::Clone(), SwitchLayer::Clone(), TileLayer::Clone(), TransposeConvolution2dLayer::Clone(), TransposeLayer::Clone(), UnidirectionalSequenceLstmLayer::Clone(), and UnmapLayer::Clone().
CollectQueueDescriptorInputs()
template<typename QueueDescriptor> void CollectQueueDescriptorInputs (QueueDescriptor & descriptor, WorkloadInfo & info) const inline protected
Definition at line 386 of file Layer.hpp.
    {
        WorkloadDataCollector dataCollector(descriptor.m_Inputs, info.m_InputTensorInfos);
        CollectWorkloadInputs(dataCollector);
    }
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by PrepInfoAndDesc().
CollectQueueDescriptorOutputs()
template<typename QueueDescriptor> void CollectQueueDescriptorOutputs (QueueDescriptor & descriptor, WorkloadInfo & info) const inline protected
Definition at line 393 of file Layer.hpp.
    {
        WorkloadDataCollector dataCollector(descriptor.m_Outputs, info.m_OutputTensorInfos);
        CollectWorkloadOutputs(dataCollector);
    }
References armnn::info, and QueueDescriptor::m_Outputs.
Referenced by PrepInfoAndDesc().
CreateTensorHandles()
void CreateTensorHandles (const TensorHandleFactoryRegistry & registry, const IWorkloadFactory & factory, const bool IsMemoryManaged = true) virtual
Reimplemented in ConcatLayer, OutputLayer, and SplitterLayer.
Definition at line 308 of file Layer.cpp.
{
    for (unsigned int idx=0; idx < GetNumOutputSlots(); idx++)
    {
        OutputSlot& slot = GetOutputSlot(idx);
        ITensorHandleFactory::FactoryId factoryId = slot.GetTensorHandleFactoryId();
        OutputHandler& handler = GetOutputHandler(idx);
        if (factoryId == ITensorHandleFactory::LegacyFactoryId)
        {
            handler.CreateTensorHandles(workloadFactory, IsMemoryManaged);
        }
        else
        {
            ITensorHandleFactory* handleFactory;
            handleFactory = registry.GetFactory(factoryId);
            if (!handleFactory)
            {
                throw armnn::NullPointerException("handleFactory must not be null.");
            }
            handler.CreateTensorHandles(*handleFactory, IsMemoryManaged);
        }
    }
}
References OutputHandler::CreateTensorHandles(), TensorHandleFactoryRegistry::GetFactory(), GetNumOutputSlots(), GetOutputHandler(), GetOutputSlot(), OutputSlot::GetTensorHandleFactoryId(), and ITensorHandleFactory::LegacyFactoryId.
CreateWorkload()
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const pure virtual
Implemented in AbsLayer, ActivationLayer, AdditionLayer, ArgMinMaxLayer, BatchMatMulLayer, BatchNormalizationLayer, BatchToSpaceNdLayer, BroadcastToLayer, CastLayer, ChannelShuffleLayer, ComparisonLayer, ConcatLayer, ConstantLayer, ConvertFp16ToFp32Layer, ConvertFp32ToFp16Layer, Convolution2dLayer, Convolution3dLayer, DebugLayer, DepthToSpaceLayer, DepthwiseConvolution2dLayer, DequantizeLayer, DetectionPostProcessLayer, DivisionLayer, ElementwiseBinaryLayer, ElementwiseUnaryLayer, FakeQuantizationLayer, FillLayer, FloorLayer, FullyConnectedLayer, FusedLayer, GatherLayer, GatherNdLayer, InputLayer, InstanceNormalizationLayer, L2NormalizationLayer, LogicalBinaryLayer, LogSoftmaxLayer, LstmLayer, MapLayer, MaximumLayer, MeanLayer, MemCopyLayer, MemImportLayer, MergeLayer, MinimumLayer, MultiplicationLayer, NormalizationLayer, OutputLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreCompiledLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, QuantizeLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, RsqrtLayer, ScatterNdLayer, ShapeLayer, SliceLayer, SoftmaxLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, SubtractionLayer, SwitchLayer, TileLayer, TransposeConvolution2dLayer, TransposeLayer, UnidirectionalSequenceLstmLayer, and UnmapLayer.
EndInputSlots()
std::vector< InputSlot >::iterator EndInputSlots () inline
Definition at line 263 of file Layer.hpp.
{ return m_InputSlots.end(); }
Referenced by CreateInputsFrom(), armnn::InsertConvertFp16ToFp32LayersBefore(), ConvertFp32NetworkToFp16Impl::Run(), MovePermuteUpImpl::Run(), and MoveTransposeUpImpl::Run().
EndOutputSlots()
std::vector< OutputSlot >::iterator EndOutputSlots () inline
Definition at line 267 of file Layer.hpp.
{ return m_OutputSlots.end(); }
Referenced by armnn::InsertDebugLayerAfter(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), ConvertFp32NetworkToFp16Impl::Run(), SquashEqualSiblingsImpl< Comparable >::Run(), and SplitterLayer::ValidateTensorShapesFromInputs().
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Implements IConnectableLayer.
Reimplemented in LayerWithParameters< Parameters >, LayerWithParameters< ActivationDescriptor >, LayerWithParameters< ArgMinMaxDescriptor >, LayerWithParameters< BatchMatMulDescriptor >, LayerWithParameters< BatchNormalizationDescriptor >, LayerWithParameters< BatchToSpaceNdDescriptor >, LayerWithParameters< BroadcastToDescriptor >, LayerWithParameters< ChannelShuffleDescriptor >, LayerWithParameters< ComparisonDescriptor >, LayerWithParameters< Convolution2dDescriptor >, LayerWithParameters< Convolution3dDescriptor >, LayerWithParameters< DepthToSpaceDescriptor >, LayerWithParameters< DepthwiseConvolution2dDescriptor >, LayerWithParameters< DetectionPostProcessDescriptor >, LayerWithParameters< ElementwiseBinaryDescriptor >, LayerWithParameters< ElementwiseUnaryDescriptor >, LayerWithParameters< FakeQuantizationDescriptor >, LayerWithParameters< FillDescriptor >, LayerWithParameters< FullyConnectedDescriptor >, LayerWithParameters< FusedDescriptor >, LayerWithParameters< GatherDescriptor >, LayerWithParameters< InstanceNormalizationDescriptor >, LayerWithParameters< L2NormalizationDescriptor >, LayerWithParameters< LogicalBinaryDescriptor >, LayerWithParameters< LogSoftmaxDescriptor >, LayerWithParameters< LstmDescriptor >, LayerWithParameters< MeanDescriptor >, LayerWithParameters< NormalizationDescriptor >, LayerWithParameters< OriginsDescriptor >, LayerWithParameters< PadDescriptor >, LayerWithParameters< PermuteDescriptor >, LayerWithParameters< Pooling2dDescriptor >, LayerWithParameters< Pooling3dDescriptor >, LayerWithParameters< PreCompiledDescriptor >, LayerWithParameters< QLstmDescriptor >, LayerWithParameters< ReduceDescriptor >, LayerWithParameters< ReshapeDescriptor >, LayerWithParameters< ResizeDescriptor >, LayerWithParameters< ScatterNdDescriptor >, LayerWithParameters< SliceDescriptor >, LayerWithParameters< SoftmaxDescriptor >, LayerWithParameters< SpaceToBatchNdDescriptor >, LayerWithParameters< SpaceToDepthDescriptor >, LayerWithParameters< StackDescriptor >, LayerWithParameters< StandInDescriptor >, LayerWithParameters< StridedSliceDescriptor >, LayerWithParameters< TileDescriptor >, LayerWithParameters< TransposeConvolution2dDescriptor >, LayerWithParameters< TransposeDescriptor >, LayerWithParameters< ViewsDescriptor >, LogicalBinaryLayer, LogSoftmaxLayer, LstmLayer, MapLayer, MaximumLayer, MeanLayer, MemCopyLayer, MemImportLayer, MergeLayer, MinimumLayer, MultiplicationLayer, NormalizationLayer, OutputLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreCompiledLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, QuantizeLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, RsqrtLayer, ShapeLayer, SliceLayer, SoftmaxLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, SubtractionLayer, SwitchLayer, TransposeConvolution2dLayer, TransposeLayer, UnidirectionalSequenceLstmLayer, and UnmapLayer.
Definition at line 571 of file Layer.cpp.
{
    strategy.ExecuteStrategy(this, BaseDescriptor(), {}, GetName());
}
References IStrategy::ExecuteStrategy(), and GetName().
Referenced by armnn::IsNCHW().
GetAdditionalInformation()
template<typename T> std::shared_ptr< T > GetAdditionalInformation () const inline
Definition at line 368 of file Layer.hpp.
    {
        return std::static_pointer_cast<T>(m_AdditionalInfoObject);
    }
References m_AdditionalInfoObject.
Referenced by ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), and SerializeLayerParameters().
GetAllowExpandedDims()
bool GetAllowExpandedDims () const inline
Definition at line 256 of file Layer.hpp.
{ return m_AllowExpandedDims; };
Referenced by LayerWithParameters< Parameters >::PrepInfoAndDesc().
GetBackendHint()
Optional< BackendId > GetBackendHint () const inline
Definition at line 355 of file Layer.hpp.
{ return m_BackendHint; }
Referenced by NetworkImpl::AddPrecompiledLayer(), and CloneBase().
GetBackendId()
const BackendId & GetBackendId () const inline
Definition at line 290 of file Layer.hpp.
{ return m_BackendId; }
Referenced by Graph::AddCompatibilityLayers(), armnn::ApplyBackendOptimizations(), armnn::AttemptBackendAssignment(), armnn::CalculateEdgeStrategy(), armnn::CalculateSlotOption(), armnn::CalculateSlotOptionForInput(), CloneBase(), ConvertQuantizeToTosaOperator(), armnn::SelectTensorHandleStrategy(), and PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl().
GetConstantTensorsByRef() [1/2]
virtual ImmutableConstantTensors GetConstantTensorsByRef () const inline override protected virtual
Implements IConnectableLayer.
Reimplemented in BatchNormalizationLayer, ConstantLayer, Convolution2dLayer, DepthwiseConvolution2dLayer, DetectionPostProcessLayer, FullyConnectedLayer, LstmLayer, QLstmLayer, QuantizedLstmLayer, TransposeConvolution2dLayer, and UnidirectionalSequenceLstmLayer.
Definition at line 427 of file Layer.hpp.
{ return ImmutableConstantTensors(); };
References GetConstantTensorsByRef().
GetConstantTensorsByRef() [2/2]
Layer::ConstantTensors GetConstantTensorsByRef () final override protected virtual
Implements IConnectableLayer.
Definition at line 576 of file Layer.cpp.
{
    const Layer *constThis = const_cast<const Layer*>(this);
    ConstantTensors res;
    ImmutableConstantTensors immutableData = constThis->GetConstantTensorsByRef();
    for (auto i : immutableData)
    {
        res.push_back(const_cast<std::shared_ptr<ConstTensorHandle>&>(i.get()));
    }
    return res;
}
References GetConstantTensorsByRef(), and Layer().
Referenced by GetConstantTensorsByRef(), GetConstantTensorsByRef(), and OperateOnConstantTensors().
GetDataType()
DataType GetDataType () const
Definition at line 345 of file Layer.cpp.
{
    if (GetNumInputSlots() > 0) // Ignore the input layer.
    {
        return GetInputSlot(0).GetTensorInfo().GetDataType();
    }
    return GetOutputSlot(0).GetTensorInfo().GetDataType();
}
References TensorInfo::GetDataType(), GetInputSlot(), GetNumInputSlots(), GetOutputSlot(), InputSlot::GetTensorInfo(), and OutputSlot::GetTensorInfo().
Referenced by ConvertConstPermuteLayersToConstLayers::Run(), ConvertFp32NetworkToFp16Impl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), IsFloat16Layer::Test(), and IsFloat32Layer::Test().
GetGuid()
LayerGuid GetGuid () const inline final virtual
Returns the unique id of the layer.
Implements IConnectableLayer.
Definition at line 343 of file Layer.hpp.
{ return m_Guid; }
Referenced by CloneBase(), ConvertConstantToTosaOperator(), DebugLayer::CreateWorkload(), OutputSlot::GetOwningLayerGuid(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), and Graph::SerializeToDot().
GetInputSlot() [1/2]
const InputSlot & GetInputSlot (unsigned int index) const inline override virtual
Get a const input slot handle by slot index.
Implements IConnectableLayer.
Examples
SimpleSample.cpp.
Definition at line 337 of file Layer.hpp.
{ return m_InputSlots.at(index); }
Referenced by Graph::AddCompatibilityLayers(), armnn::ApplyBackendOptimizations(), armnn::BuildAddMulAddTensorInfoLists(), armnn::ChainReduceLayers(), armnn::ConnectedToLayerType(), armnn::ConnectedToLayerWithNCHW(), ConvertAvgPool2DIgnoreValueToTosaOperator(), ConvertBatchMatMulToTosaOperator(), ConvertBatchToSpaceToTosaOperator(), ConvertConcatToTosaOperator(), ConvertConstantToTosaOperator(), ConvertConv2dToTosaOperator(), ConvertConv3dToTosaOperator(), ConvertDepthToSpaceToTosaOperator(), ConvertDepthwiseConv2dToTosaOperator(), ConvertDequantizeToTosaOperator(), ConvertElementwiseBinaryToTosaOperator(), ConvertExpOperator(), ConvertFullyConnectedToTosaOperator(), ConvertGatherToTosaOperator(), ConvertGeluToTosaOperator(), ConvertHardSwishToTosaOperator(), ConvertLeakyReluToTosaOperator(), ConvertLogOperator(), ConvertPadToTosaOperator(), ConvertPooling2DToTosaOperator(), ConvertPReluToTosaOperator(), ConvertQuantizeToTosaOperator(), ConvertReduceToTosaOperator(), ConvertReluToTosaOperator(), ConvertReshapeToTosaOperator(), ConvertResizeToTosaOperator(), ConvertRsqrtOperator(), ConvertSigmoidToTosaOperator(), ConvertSliceToTosaOperator(), ConvertSoftmaxToTosaOperator(), ConvertSpaceToBatchToTosaOperator(), ConvertSplitToTosaOperator(), ConvertSquaredDifferenceToTosaOperator(), ConvertStackToTosaOperator(), ConvertStridedSliceToTosaOperator(), ConvertTanHToTosaOperator(), ConvertTransposeConv2dToTosaOperator(), ConvertTransposeToTosaOperator(), DebugLayer::CreateWorkload(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), LayerWithParameters< Parameters >::GetConnectedConstantAsInputTensors(), GetDataType(), armnn::GetLayerInOutDatatype(), InputSlot::Insert(), armnn::InsertConvertFp16ToFp32LayersBefore(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::InsertDebugLayerAfter(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), AddBroadcastReshapeLayerImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), OptimizeInversePermutesImpl< PermuteType >::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), PermuteAsReshapeImpl::Run(), TransposeAsReshapeImpl::Run(), Convolution2dLayer::SerializeLayerParameters(), Convolution3dLayer::SerializeLayerParameters(), DepthwiseConvolution2dLayer::SerializeLayerParameters(), AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), OutputLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs(), VerifyLayerConnections(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
GetInputSlot() [2/2]
InputSlot & GetInputSlot (unsigned int index) inline override virtual
Get the input slot handle by slot index.
Implements IConnectableLayer.
Definition at line 338 of file Layer.hpp.
{ return  m_InputSlots.at(index); }
GetInputSlots()
const std::vector< InputSlot > & GetInputSlots () const inline
Definition at line 258 of file Layer.hpp.
{ return m_InputSlots; }
Referenced by armnn::AttemptBackendAssignment(), armnn::CalculateSlotOption(), armnn::ForEachLayerInput(), GetPriority(), GetTosaMappingFromLayer(), ConvertFp32NetworkToFp16Impl::Run(), DeleteBroadcastToImpl::Run(), and WeightFromDifferentLayer().
GetName()
const char * GetName () const inline override virtual
Returns the name of the layer.
Implements IConnectableLayer.
Definition at line 332 of file Layer.hpp.
{ return m_LayerName.c_str(); }
Referenced by Graph::AddCompatibilityLayers(), AbsLayer::Clone(), ActivationLayer::Clone(), AdditionLayer::Clone(), ArgMinMaxLayer::Clone(), BatchMatMulLayer::Clone(), BatchNormalizationLayer::Clone(), BatchToSpaceNdLayer::Clone(), BroadcastToLayer::Clone(), CastLayer::Clone(), ChannelShuffleLayer::Clone(), ComparisonLayer::Clone(), ConcatLayer::Clone(), ConstantLayer::Clone(), ConvertFp16ToFp32Layer::Clone(), ConvertFp32ToFp16Layer::Clone(), Convolution2dLayer::Clone(), Convolution3dLayer::Clone(), DebugLayer::Clone(), DepthToSpaceLayer::Clone(), DepthwiseConvolution2dLayer::Clone(), DequantizeLayer::Clone(), DetectionPostProcessLayer::Clone(), DivisionLayer::Clone(), ElementwiseBinaryLayer::Clone(), ElementwiseUnaryLayer::Clone(), FakeQuantizationLayer::Clone(), FillLayer::Clone(), FloorLayer::Clone(), FullyConnectedLayer::Clone(), FusedLayer::Clone(), GatherLayer::Clone(), GatherNdLayer::Clone(), InputLayer::Clone(), InstanceNormalizationLayer::Clone(), L2NormalizationLayer::Clone(), LogicalBinaryLayer::Clone(), LogSoftmaxLayer::Clone(), LstmLayer::Clone(), MapLayer::Clone(), MaximumLayer::Clone(), MeanLayer::Clone(), MemCopyLayer::Clone(), MemImportLayer::Clone(), MergeLayer::Clone(), MinimumLayer::Clone(), MultiplicationLayer::Clone(), NormalizationLayer::Clone(), OutputLayer::Clone(), PadLayer::Clone(), PermuteLayer::Clone(), Pooling2dLayer::Clone(), Pooling3dLayer::Clone(), PreCompiledLayer::Clone(), PreluLayer::Clone(), QLstmLayer::Clone(), QuantizedLstmLayer::Clone(), QuantizeLayer::Clone(), RankLayer::Clone(), ReduceLayer::Clone(), ReshapeLayer::Clone(), ResizeLayer::Clone(), ReverseV2Layer::Clone(), RsqrtLayer::Clone(), ScatterNdLayer::Clone(), ShapeLayer::Clone(), SliceLayer::Clone(), SoftmaxLayer::Clone(), SpaceToBatchNdLayer::Clone(), SpaceToDepthLayer::Clone(), SplitterLayer::Clone(), StackLayer::Clone(), StandInLayer::Clone(), StridedSliceLayer::Clone(), SubtractionLayer::Clone(), SwitchLayer::Clone(), TileLayer::Clone(), TransposeConvolution2dLayer::Clone(), TransposeLayer::Clone(), UnidirectionalSequenceLstmLayer::Clone(), UnmapLayer::Clone(), ActivationLayer::ExecuteStrategy(), AdditionLayer::ExecuteStrategy(), ArgMinMaxLayer::ExecuteStrategy(), BatchNormalizationLayer::ExecuteStrategy(), BatchToSpaceNdLayer::ExecuteStrategy(), BindableLayer::ExecuteStrategy(), BroadcastToLayer::ExecuteStrategy(), ComparisonLayer::ExecuteStrategy(), ConcatLayer::ExecuteStrategy(), ConstantLayer::ExecuteStrategy(), ConvertFp16ToFp32Layer::ExecuteStrategy(), ConvertFp32ToFp16Layer::ExecuteStrategy(), Convolution2dLayer::ExecuteStrategy(), Convolution3dLayer::ExecuteStrategy(), DebugLayer::ExecuteStrategy(), DepthToSpaceLayer::ExecuteStrategy(), DepthwiseConvolution2dLayer::ExecuteStrategy(), DequantizeLayer::ExecuteStrategy(), DetectionPostProcessLayer::ExecuteStrategy(), DivisionLayer::ExecuteStrategy(), ElementwiseBaseLayer::ExecuteStrategy(), ElementwiseBinaryLayer::ExecuteStrategy(), ElementwiseUnaryLayer::ExecuteStrategy(), FillLayer::ExecuteStrategy(), FloorLayer::ExecuteStrategy(), FullyConnectedLayer::ExecuteStrategy(), FusedLayer::ExecuteStrategy(), GatherLayer::ExecuteStrategy(), InputLayer::ExecuteStrategy(), InstanceNormalizationLayer::ExecuteStrategy(), L2NormalizationLayer::ExecuteStrategy(), ExecuteStrategy(), LayerWithParameters< Parameters >::ExecuteStrategy(), LogicalBinaryLayer::ExecuteStrategy(), LogSoftmaxLayer::ExecuteStrategy(), LstmLayer::ExecuteStrategy(), MaximumLayer::ExecuteStrategy(), MeanLayer::ExecuteStrategy(), MemCopyLayer::ExecuteStrategy(), MergeLayer::ExecuteStrategy(), MinimumLayer::ExecuteStrategy(), MultiplicationLayer::ExecuteStrategy(), NormalizationLayer::ExecuteStrategy(), OutputLayer::ExecuteStrategy(), PadLayer::ExecuteStrategy(), PermuteLayer::ExecuteStrategy(), Pooling2dLayer::ExecuteStrategy(), Pooling3dLayer::ExecuteStrategy(), PreCompiledLayer::ExecuteStrategy(), PreluLayer::ExecuteStrategy(), QLstmLayer::ExecuteStrategy(), QuantizedLstmLayer::ExecuteStrategy(), QuantizeLayer::ExecuteStrategy(), RankLayer::ExecuteStrategy(), ReduceLayer::ExecuteStrategy(), ReshapeLayer::ExecuteStrategy(), ResizeLayer::ExecuteStrategy(), ReverseV2Layer::ExecuteStrategy(), RsqrtLayer::ExecuteStrategy(), ShapeLayer::ExecuteStrategy(), SliceLayer::ExecuteStrategy(), SoftmaxLayer::ExecuteStrategy(), SpaceToBatchNdLayer::ExecuteStrategy(), SpaceToDepthLayer::ExecuteStrategy(), SplitterLayer::ExecuteStrategy(), StackLayer::ExecuteStrategy(), StandInLayer::ExecuteStrategy(), StridedSliceLayer::ExecuteStrategy(), SubtractionLayer::ExecuteStrategy(), SwitchLayer::ExecuteStrategy(), TransposeConvolution2dLayer::ExecuteStrategy(), TransposeLayer::ExecuteStrategy(), UnidirectionalSequenceLstmLayer::ExecuteStrategy(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), armnn::FoldPadLayer2d(), armnn::InsertConvertFp16ToFp32LayersBefore(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::IsLayerOptimizable(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), PrepInfoAndDesc(), AddBroadcastReshapeLayerImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), OptimizeConsecutiveReshapesImpl::Run(), PermuteAsReshapeImpl::Run(), TransposeAsReshapeImpl::Run(), and ErasedLayerNamesObservable::Update().
GetNameStr()
const std::string & GetNameStr () const inline
Definition at line 240 of file Layer.hpp.
    {
        return m_LayerName;
    }
Referenced by DebugLayer::CreateWorkload(), armnn::GetFusedName(), InferOutputShapes(), armnn::InsertDebugLayerAfter(), IsConnected(), LayerNameAndTypeCheck::operator()(), AddBroadcastReshapeLayerImpl::Run(), and VerifyLayerConnections().
GetNumInputSlots()
unsigned int GetNumInputSlots () const inline override virtual
Returns the number of connectable input slots.
Implements IConnectableLayer.
Definition at line 334 of file Layer.hpp.
{ return static_cast<unsigned int>(m_InputSlots.size()); }
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssertNumberOfInputSlots(), CheckNumberOfInputSlot(), LayerWithParameters< Parameters >::GetConnectedConstantAsInputTensors(), GetDataType(), armnn::GetLayerInOutDatatype(), InferOutputShapes(), armnn::InsertConvertFp16ToFp32LayersBefore(), ConcatLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), VerifyLayerConnections(), and WeightFromDifferentLayer().
GetNumOutputSlots()
unsigned int GetNumOutputSlots () const inline override virtual
Returns the number of connectable output slots.
Implements IConnectableLayer.
Definition at line 335 of file Layer.hpp.
{ return static_cast<unsigned int>(m_OutputSlots.size()); }
Referenced by OutputSlot::CalculateIndexOnOwner(), CheckNumberOfOutputSlot(), armnn::CheckScaleSetOnQuantizedType(), CreateTensorHandles(), armnn::GetLayerInOutDatatype(), InferOutputShapes(), InputSlot::Insert(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::InsertDebugLayerAfter(), IsOutputUnconnected(), armnn::SelectTensorHandleStrategy(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), MapLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), UnmapLayer::ValidateTensorShapesFromInputs(), and ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl().
GetOutputHandler() [1/2]
OutputHandler & GetOutputHandler (unsigned int i = 0) inline
Definition at line 250 of file Layer.hpp.
    {
        return const_cast<OutputHandler&>(const_cast<const Layer*>(this)->GetOutputHandler(i));
    }
References Layer().
GetOutputHandler() [2/2]
const OutputHandler & GetOutputHandler (unsigned int i = 0) const inline
Definition at line 245 of file Layer.hpp.
    {
        return m_OutputHandlers[i];
    }
References m_OutputHandlers.
Referenced by CreateTensorHandles(), InputSlot::Insert(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), PermuteAsReshapeImpl::Run(), TransposeAsReshapeImpl::Run(), InputLayer::ValidateTensorShapesFromInputs(), PermuteAsReshapeImpl::~PermuteAsReshapeImpl(), and TransposeAsReshapeImpl::~TransposeAsReshapeImpl().
GetOutputSlot() [1/2]
const OutputSlot & GetOutputSlot (unsigned int index = 0) const inline override virtual
Get the const output slot handle by slot index.
Implements IConnectableLayer.
Examples
SimpleSample.cpp.
Definition at line 339 of file Layer.hpp.
{ return m_OutputSlots.at(index); }
Referenced by Graph::AddCompatibilityLayers(), armnn::ApplyBackendOptimizations(), armnn::AttemptBackendAssignment(), armnn::BuildAddMulAddTensorInfoLists(), armnn::ChainReduceLayers(), armnn::CheckScaleSetOnQuantizedType(), armnn::ConnectedToLayerType(), armnn::ConnectedToLayerWithNCHW(), ConvertConstantToTosaOperator(), ConcatLayer::CreateTensorHandles(), CreateTensorHandles(), SplitterLayer::CreateTensorHandles(), armnn::optimizations::pad_fold::FoldPadIntoLayer2dImpl(), GenerateUniqueOutputName(), GetDataType(), armnn::GetLayerInOutDatatype(), GetTosaMapping(), InputSlot::Insert(), armnn::InsertConvertFp16ToFp32LayersBefore(), armnn::InsertConvertFp32ToFp16LayersAfter(), armnn::InsertDebugLayerAfter(), IsConnected(), ClBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), AddBroadcastReshapeLayerImpl::Run(), DeleteBroadcastToImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), MovePermuteUpImpl::Run(), MoveTransposeUpImpl::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), PermuteAsReshapeImpl::Run(), TransposeAsReshapeImpl::Run(), armnn::SelectTensorHandleStrategy(), ValidateAndCopyShape(), AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), BroadcastToLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConstantLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RankLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), SplitterLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs(), ConvertConstDequantisationLayersToConstLayersImpl::~ConvertConstDequantisationLayersToConstLayersImpl(), ConvertConstPermuteLayersToConstLayers::~ConvertConstPermuteLayersToConstLayers(), PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl(), and TurboConvertConstDequantisationLayersToConstLayersImpl::~TurboConvertConstDequantisationLayersToConstLayersImpl().
GetOutputSlot() [2/2]
OutputSlot & GetOutputSlot (unsigned int index = 0) inline override virtual
Get the output slot handle by slot index.
Implements IConnectableLayer.
Definition at line 340 of file Layer.hpp.
{ return m_OutputSlots.at(index); }
GetOutputSlots()
const std::vector< OutputSlot > & GetOutputSlots () const inline
Definition at line 259 of file Layer.hpp.
{ return m_OutputSlots; }
Referenced by Graph::AddCompatibilityLayers(), armnn::ForEachLayerOutput(), GetTosaMappingFromLayer(), IsOutputUnconnected(), and Graph::Print().
GetParameters()
virtual const BaseDescriptor & GetParameters () const inline override virtual
If the layer has a descriptor return it.
The base descriptor can then be cast to the correct descriptor class. If the layer has no associated descriptor a struct of type NullDescriptor will be returned. Note: NullDescriptors can be detected because they return true when the BaseDescriptor IsNull function is invoked.
Implements IConnectableLayer.
Reimplemented in LayerWithParameters< Parameters >, LayerWithParameters< ActivationDescriptor >, LayerWithParameters< ArgMinMaxDescriptor >, LayerWithParameters< BatchMatMulDescriptor >, LayerWithParameters< BatchNormalizationDescriptor >, LayerWithParameters< BatchToSpaceNdDescriptor >, LayerWithParameters< BroadcastToDescriptor >, LayerWithParameters< ChannelShuffleDescriptor >, LayerWithParameters< ComparisonDescriptor >, LayerWithParameters< Convolution2dDescriptor >, LayerWithParameters< Convolution3dDescriptor >, LayerWithParameters< DepthToSpaceDescriptor >, LayerWithParameters< DepthwiseConvolution2dDescriptor >, LayerWithParameters< DetectionPostProcessDescriptor >, LayerWithParameters< ElementwiseBinaryDescriptor >, LayerWithParameters< ElementwiseUnaryDescriptor >, LayerWithParameters< FakeQuantizationDescriptor >, LayerWithParameters< FillDescriptor >, LayerWithParameters< FullyConnectedDescriptor >, LayerWithParameters< FusedDescriptor >, LayerWithParameters< GatherDescriptor >, LayerWithParameters< InstanceNormalizationDescriptor >, LayerWithParameters< L2NormalizationDescriptor >, LayerWithParameters< LogicalBinaryDescriptor >, LayerWithParameters< LogSoftmaxDescriptor >, LayerWithParameters< LstmDescriptor >, LayerWithParameters< MeanDescriptor >, LayerWithParameters< NormalizationDescriptor >, LayerWithParameters< OriginsDescriptor >, LayerWithParameters< PadDescriptor >, LayerWithParameters< PermuteDescriptor >, LayerWithParameters< Pooling2dDescriptor >, LayerWithParameters< Pooling3dDescriptor >, LayerWithParameters< PreCompiledDescriptor >, LayerWithParameters< QLstmDescriptor >, LayerWithParameters< ReduceDescriptor >, LayerWithParameters< ReshapeDescriptor >, LayerWithParameters< ResizeDescriptor >, LayerWithParameters< ScatterNdDescriptor >, LayerWithParameters< SliceDescriptor >, LayerWithParameters< SoftmaxDescriptor >, LayerWithParameters< SpaceToBatchNdDescriptor >, LayerWithParameters< SpaceToDepthDescriptor >, LayerWithParameters< StackDescriptor >, LayerWithParameters< StandInDescriptor >, LayerWithParameters< StridedSliceDescriptor >, LayerWithParameters< TileDescriptor >, LayerWithParameters< TransposeConvolution2dDescriptor >, LayerWithParameters< TransposeDescriptor >, and LayerWithParameters< ViewsDescriptor >.
Definition at line 378 of file Layer.hpp.
{ return m_NullDescriptor; }
Referenced by AbsLayer::ExecuteStrategy(), AdditionLayer::ExecuteStrategy(), ConvertFp16ToFp32Layer::ExecuteStrategy(), ConvertFp32ToFp16Layer::ExecuteStrategy(), DebugLayer::ExecuteStrategy(), DequantizeLayer::ExecuteStrategy(), DivisionLayer::ExecuteStrategy(), FloorLayer::ExecuteStrategy(), InputLayer::ExecuteStrategy(), MaximumLayer::ExecuteStrategy(), MemCopyLayer::ExecuteStrategy(), MergeLayer::ExecuteStrategy(), MinimumLayer::ExecuteStrategy(), MultiplicationLayer::ExecuteStrategy(), OutputLayer::ExecuteStrategy(), PreluLayer::ExecuteStrategy(), QuantizeLayer::ExecuteStrategy(), RsqrtLayer::ExecuteStrategy(), SubtractionLayer::ExecuteStrategy(), SwitchLayer::ExecuteStrategy(), GetTosaMappingFromLayer(), MovePermuteUpImpl::~MovePermuteUpImpl(), and MoveTransposeUpImpl::~MoveTransposeUpImpl().
GetPriority()
LayerPriority GetPriority () const
Definition at line 360 of file Layer.cpp.
{
    constexpr LayerPriority inputPrio = std::numeric_limits<LayerPriority>::lowest();
    constexpr LayerPriority outputPrio = std::numeric_limits<LayerPriority>::max();
    if (GetType() == LayerType::Input)
    {
        m_Priority = inputPrio;
    }
    else if (GetType() == LayerType::Output)
    {
        m_Priority = outputPrio;
    }
    else if (m_Priority == 0)
    {
        if (m_Visiting)
        {
            throw GraphValidationException("Graph has circular dependencies: cannot walk");
        }
        auto maxPrio = [](const LayerPriority prio, const InputSlot& slot) -> LayerPriority
            {
                const OutputSlot *outputSlot = slot.GetConnectedOutputSlot();
                if (outputSlot)
                {
                    const Layer& input = outputSlot->GetOwningLayer();
                    return std::max(prio, input.GetPriority());
                }
                else
                {
                    // unconnected input slot
                    return prio;
                }
            };
        m_Visiting = true;
        LayerPriority parentPrio = std::accumulate(GetInputSlots().cbegin(), GetInputSlots().cend(), 0U, maxPrio);
        m_Visiting = false;
        if (parentPrio >= outputPrio)
        {
            throw GraphValidationException("Graph has too many edges");
        }
        m_Priority = parentPrio + 1U;
    }
    return m_Priority;
}
References GetInputSlots(), OutputSlot::GetOwningLayer(), GetPriority(), GetType(), armnn::Input, Layer(), and armnn::Output.
Referenced by GetPriority(), and SquashEqualSiblingsImpl< Comparable >::Run().
GetRelatedLayerNames()
const std::list< std::string > & GetRelatedLayerNames () inline
Definition at line 347 of file Layer.hpp.
{ return m_RelatedLayerNames; }
Referenced by ErasedLayerNamesObservable::Update().
GetShapeInferenceMethod()
ShapeInferenceMethod GetShapeInferenceMethod () const inline
Definition at line 255 of file Layer.hpp.
{ return m_ShapeInferenceMethod; };
References m_ShapeInferenceMethod.
GetType()
LayerType GetType () const inline override virtual
Returns the armnn::LayerType of this layer.
Implements IConnectableLayer.
Definition at line 286 of file Layer.hpp.
{ return m_Type; }
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssertNumberOfInputSlots(), armnn::AttemptBackendAssignment(), armnn::BuildAddMulAddTensorInfoLists(), armnn::CalculateEdgeStrategy(), armnn::CalculateSlotOption(), armnn::CalculateSlotOptionForInput(), armnn::CheckScaleSetOnQuantizedType(), armnn::ConnectedToLayerType(), ConvertSquaredDifferenceToTosaOperator(), GenerateUniqueOutputName(), GetPriority(), GetTosaMapping(), GetTosaMappingFromLayer(), InferOutputShapes(), PermuteLayer::IsEqual(), ReshapeLayer::IsEqual(), TransposeLayer::IsEqual(), PermuteLayer::IsInverse(), TransposeLayer::IsInverse(), IsLayerOfType(), armnn::IsLayerSupported(), armnn::IsSequenceLayerType(), armnn::IsSequenceLayerType(), LayerNameAndTypeCheck::operator()(), ClBackend::OptimizeSubgraphView(), NeonBackend::OptimizeSubgraphView(), RefBackend::OptimizeSubgraphView(), TosaRefBackend::OptimizeSubgraphView(), armnn::RemoveReshapeLayer(), armnn::ReturnWithError(), AddBroadcastReshapeLayerImpl::Run(), AddDebugImpl::Run(), AddDebugToFileImpl::Run(), ConvertConstDequantisationLayersToConstLayersImpl::Run(), ConvertConstPermuteLayersToConstLayers::Run(), ConvertFp32NetworkToFp16Impl::Run(), DeleteBroadcastToImpl::Run(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), OptimizeConsecutiveReshapesImpl::Run(), OptimizeInverseConversionsImpl::Run(), PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteType >::Run(), PermuteDepthwiseConv2dWeightsImpl::Run(), TurboConvertConstDequantisationLayersToConstLayersImpl::Run(), OptimizeForTypeImpl< BaseType, Wrapped >::Run(), armnn::SelectTensorHandleStrategy(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), VerifyLayerConnections(), MovePermuteUpImpl::~MovePermuteUpImpl(), and MoveTransposeUpImpl::~MoveTransposeUpImpl().
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
Infer the shape of the output(s) based on the provided input shape(s)
Implements IConnectableLayer.
Reimplemented in LogicalBinaryLayer, LstmLayer, MeanLayer, MergeLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, ScatterNdLayer, ShapeLayer, SliceLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, TileLayer, TransposeConvolution2dLayer, TransposeLayer, and UnidirectionalSequenceLstmLayer.
Definition at line 432 of file Layer.cpp.
{
    ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(GetNumInputSlots()  != 0, "input slots must not be zero.");
    ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(GetNumOutputSlots() != 0, "output slots must not be zero.");
    // By default we return what we got, meaning the output shape(s) are the same as the input(s).
    // This only works if the number of inputs and outputs are the same. Since we are in the Layer
    // base class, this means the implementation needs to be overridden in the specific layers for
    // the other cases. So the missing implementation justifies the UnimplementedException.
    if (GetNumInputSlots() != GetNumOutputSlots())
    {
        throw UnimplementedException(
                fmt::format("Default implementation for InferOutputShapes can only be used for "
                            "layers with the same number of input and output slots. This doesn't "
                            "hold for {0} layer {1} (#inputs={2} #outputs={3}) {4}",
                            GetLayerTypeAsCString(this->GetType()),
                            GetNameStr(),
                            GetNumInputSlots(),
                            GetNumOutputSlots(),
                            CHECK_LOCATION().AsString()));
    }
    return inputShapes;
}
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, CHECK_LOCATION, armnn::GetLayerTypeAsCString(), GetNameStr(), GetNumInputSlots(), GetNumOutputSlots(), and GetType().
Referenced by AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), and SwitchLayer::ValidateTensorShapesFromInputs().
IsOutputUnconnected()
bool IsOutputUnconnected () inline
Definition at line 270 of file Layer.hpp.
    {
        unsigned int numConnections = 0;
        for (auto&& output : GetOutputSlots())
        {
            numConnections += output.GetNumConnections();
        }
        return (GetNumOutputSlots() > 0) && (numConnections == 0);
    }
References GetNumOutputSlots(), and GetOutputSlots().
Referenced by OptimizeForConnectionImpl< BaseType, ChildType, Wrapped >::Run(), and OptimizeForExclusiveConnectionImpl< BaseType, ChildType, Wrapped >::Run().
OperateOnConstantTensors()
template<typename Op> void OperateOnConstantTensors (Op op) inline
Definition at line 319 of file Layer.hpp.
    {
        for (auto constant : GetConstantTensorsByRef())
        {
            if (constant.get())
            {
                op(constant);
            }
        }
    };
References GetConstantTensorsByRef().
Referenced by ReleaseConstantData(), and ConvertConstants< Float16ToFloat32, IsFloat32Layer >::Run().
PrepInfoAndDesc()
template<typename QueueDescriptor> WorkloadInfo PrepInfoAndDesc (QueueDescriptor & descriptor) const inline protected
Helper function to reduce duplication in *LayerCreateWorkload.
Definition at line 409 of file Layer.hpp.
    {
        WorkloadInfo info;
        CollectQueueDescriptorInputs(descriptor, info);
        CollectQueueDescriptorOutputs(descriptor, info);
        info.m_Name = GetName();
        return info;
    }
References CollectQueueDescriptorInputs(), CollectQueueDescriptorOutputs(), GetName(), and armnn::info.
Referenced by AbsLayer::CreateWorkload(), AdditionLayer::CreateWorkload(), CastLayer::CreateWorkload(), ConstantLayer::CreateWorkload(), ConvertFp16ToFp32Layer::CreateWorkload(), ConvertFp32ToFp16Layer::CreateWorkload(), DebugLayer::CreateWorkload(), DequantizeLayer::CreateWorkload(), DivisionLayer::CreateWorkload(), FloorLayer::CreateWorkload(), GatherNdLayer::CreateWorkload(), MapLayer::CreateWorkload(), MaximumLayer::CreateWorkload(), MemCopyLayer::CreateWorkload(), MemImportLayer::CreateWorkload(), MinimumLayer::CreateWorkload(), MultiplicationLayer::CreateWorkload(), PreluLayer::CreateWorkload(), QuantizedLstmLayer::CreateWorkload(), QuantizeLayer::CreateWorkload(), RankLayer::CreateWorkload(), ReverseV2Layer::CreateWorkload(), RsqrtLayer::CreateWorkload(), ShapeLayer::CreateWorkload(), SubtractionLayer::CreateWorkload(), SwitchLayer::CreateWorkload(), UnmapLayer::CreateWorkload(), and LayerWithParameters< Parameters >::PrepInfoAndDesc().
ReleaseConstantData()
void ReleaseConstantData () virtual
Reimplemented in ConstantLayer, Convolution2dLayer, DepthwiseConvolution2dLayer, and FullyConnectedLayer.
Definition at line 336 of file Layer.cpp.
{
    // Now free up the static data.
    OperateOnConstantTensors([](std::shared_ptr<ConstTensorHandle>& handle)
{
                                     handle.reset();
                                 });
}
References OperateOnConstantTensors().
Reparent()
virtual void Reparent (Graph & dest, std::list< Layer * >::const_iterator iterator) pure virtual
References Graph.
Referenced by Graph::operator=().
ResetPriority()
void ResetPriority () const
Definition at line 354 of file Layer.cpp.
{
    m_Priority = 0;
    m_Visiting = false;
}
SerializeLayerParameters()
void SerializeLayerParameters (ParameterStringifyFunction & fn) const virtual
Helper to serialize the layer parameters to string.
(currently used in DotSerializer and company).
Reimplemented in ConstantLayer, Convolution2dLayer, Convolution3dLayer, DepthwiseConvolution2dLayer, LayerWithParameters< Parameters >, LayerWithParameters< ActivationDescriptor >, LayerWithParameters< ArgMinMaxDescriptor >, LayerWithParameters< BatchMatMulDescriptor >, LayerWithParameters< BatchNormalizationDescriptor >, LayerWithParameters< BatchToSpaceNdDescriptor >, LayerWithParameters< BroadcastToDescriptor >, LayerWithParameters< ChannelShuffleDescriptor >, LayerWithParameters< ComparisonDescriptor >, LayerWithParameters< Convolution2dDescriptor >, LayerWithParameters< Convolution3dDescriptor >, LayerWithParameters< DepthToSpaceDescriptor >, LayerWithParameters< DepthwiseConvolution2dDescriptor >, LayerWithParameters< DetectionPostProcessDescriptor >, LayerWithParameters< ElementwiseBinaryDescriptor >, LayerWithParameters< ElementwiseUnaryDescriptor >, LayerWithParameters< FakeQuantizationDescriptor >, LayerWithParameters< FillDescriptor >, LayerWithParameters< FullyConnectedDescriptor >, LayerWithParameters< FusedDescriptor >, LayerWithParameters< GatherDescriptor >, LayerWithParameters< InstanceNormalizationDescriptor >, LayerWithParameters< L2NormalizationDescriptor >, LayerWithParameters< LogicalBinaryDescriptor >, LayerWithParameters< LogSoftmaxDescriptor >, LayerWithParameters< LstmDescriptor >, LayerWithParameters< MeanDescriptor >, LayerWithParameters< NormalizationDescriptor >, LayerWithParameters< OriginsDescriptor >, LayerWithParameters< PadDescriptor >, LayerWithParameters< PermuteDescriptor >, LayerWithParameters< Pooling2dDescriptor >, LayerWithParameters< Pooling3dDescriptor >, LayerWithParameters< PreCompiledDescriptor >, LayerWithParameters< QLstmDescriptor >, LayerWithParameters< ReduceDescriptor >, LayerWithParameters< ReshapeDescriptor >, LayerWithParameters< ResizeDescriptor >, LayerWithParameters< ScatterNdDescriptor >, LayerWithParameters< SliceDescriptor >, LayerWithParameters< SoftmaxDescriptor >, LayerWithParameters< SpaceToBatchNdDescriptor >, LayerWithParameters< SpaceToDepthDescriptor >, LayerWithParameters< StackDescriptor >, LayerWithParameters< StandInDescriptor >, LayerWithParameters< StridedSliceDescriptor >, LayerWithParameters< TileDescriptor >, LayerWithParameters< TransposeConvolution2dDescriptor >, LayerWithParameters< TransposeDescriptor >, and LayerWithParameters< ViewsDescriptor >.
Definition at line 540 of file Layer.cpp.
{
    std::string guid = std::to_string(m_Guid);
    std::string layerType = GetLayerTypeAsCString(m_Type);
    std::string backendId = std::string(m_BackendId);
    if (!(guid.compare("") == 0) && !guid.empty())
    {
        fn("Guid", guid);
    }
    if(!(m_LayerName.compare("") == 0) && !m_LayerName.empty())
    {
        fn("LayerName",m_LayerName);
    }
    if(!(layerType.compare("") == 0) && !layerType.empty())
    {
        fn("LayerType",layerType);
    }
    if(!(backendId.compare("") == 0) && !backendId.empty())
    {
        fn("BackendID",backendId);
    }
    std::shared_ptr<ActivationDescriptor>
            activationDescPtr = GetAdditionalInformation<ActivationDescriptor>();
    if (activationDescPtr)
    {
        StringifyLayerParameters<ActivationDescriptor>::Serialize(fn, *activationDescPtr.get());
    }
}
References GetAdditionalInformation(), armnn::GetLayerTypeAsCString(), and StringifyLayerParameters< LayerParameter >::Serialize().
Referenced by ConstantLayer::SerializeLayerParameters(), and LayerWithParameters< Parameters >::SerializeLayerParameters().
SetAdditionalInfo()
void SetAdditionalInfo (QueueDescriptor & descriptor) const protected
Definition at line 303 of file Layer.cpp.
{
    descriptor.m_AdditionalInfoObject = m_AdditionalInfoObject.get();
}
References m_AdditionalInfoObject, and QueueDescriptor::m_AdditionalInfoObject.
Referenced by AbsLayer::CreateWorkload(), ActivationLayer::CreateWorkload(), AdditionLayer::CreateWorkload(), ArgMinMaxLayer::CreateWorkload(), BatchMatMulLayer::CreateWorkload(), BatchNormalizationLayer::CreateWorkload(), BatchToSpaceNdLayer::CreateWorkload(), BroadcastToLayer::CreateWorkload(), CastLayer::CreateWorkload(), ChannelShuffleLayer::CreateWorkload(), ComparisonLayer::CreateWorkload(), ConcatLayer::CreateWorkload(), ConstantLayer::CreateWorkload(), ConvertFp16ToFp32Layer::CreateWorkload(), ConvertFp32ToFp16Layer::CreateWorkload(), Convolution2dLayer::CreateWorkload(), Convolution3dLayer::CreateWorkload(), DebugLayer::CreateWorkload(), DepthToSpaceLayer::CreateWorkload(), DepthwiseConvolution2dLayer::CreateWorkload(), DequantizeLayer::CreateWorkload(), DetectionPostProcessLayer::CreateWorkload(), DivisionLayer::CreateWorkload(), ElementwiseBinaryLayer::CreateWorkload(), FakeQuantizationLayer::CreateWorkload(), FillLayer::CreateWorkload(), FloorLayer::CreateWorkload(), FullyConnectedLayer::CreateWorkload(), FusedLayer::CreateWorkload(), GatherLayer::CreateWorkload(), GatherNdLayer::CreateWorkload(), InstanceNormalizationLayer::CreateWorkload(), L2NormalizationLayer::CreateWorkload(), LogSoftmaxLayer::CreateWorkload(), LstmLayer::CreateWorkload(), MapLayer::CreateWorkload(), MaximumLayer::CreateWorkload(), MeanLayer::CreateWorkload(), MemCopyLayer::CreateWorkload(), MemImportLayer::CreateWorkload(), MinimumLayer::CreateWorkload(), MultiplicationLayer::CreateWorkload(), NormalizationLayer::CreateWorkload(), PadLayer::CreateWorkload(), PermuteLayer::CreateWorkload(), Pooling2dLayer::CreateWorkload(), Pooling3dLayer::CreateWorkload(), PreCompiledLayer::CreateWorkload(), PreluLayer::CreateWorkload(), QLstmLayer::CreateWorkload(), QuantizedLstmLayer::CreateWorkload(), QuantizeLayer::CreateWorkload(), RankLayer::CreateWorkload(), ReduceLayer::CreateWorkload(), ReshapeLayer::CreateWorkload(), ResizeLayer::CreateWorkload(), ReverseV2Layer::CreateWorkload(), RsqrtLayer::CreateWorkload(), ScatterNdLayer::CreateWorkload(), ShapeLayer::CreateWorkload(), SliceLayer::CreateWorkload(), SoftmaxLayer::CreateWorkload(), SpaceToBatchNdLayer::CreateWorkload(), SpaceToDepthLayer::CreateWorkload(), SplitterLayer::CreateWorkload(), StackLayer::CreateWorkload(), StridedSliceLayer::CreateWorkload(), SubtractionLayer::CreateWorkload(), SwitchLayer::CreateWorkload(), TileLayer::CreateWorkload(), TransposeConvolution2dLayer::CreateWorkload(), TransposeLayer::CreateWorkload(), UnidirectionalSequenceLstmLayer::CreateWorkload(), and UnmapLayer::CreateWorkload().
SetAdditionalInfoForObject()
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr & additionalInfo) inline
Definition at line 373 of file Layer.hpp.
    {
        m_AdditionalInfoObject = additionalInfo;
    }
References m_AdditionalInfoObject.
Referenced by NeonBackend::OptimizeSubgraphView().
SetAllowExpandedDims()
void SetAllowExpandedDims (bool allowExpandedDims) inline
Definition at line 362 of file Layer.hpp.
    {
        m_AllowExpandedDims = allowExpandedDims;
    }
SetBackendId()
void SetBackendId (const BackendId & id) inline override virtual
Set the backend of the IConnectableLayer.
By using SetBackendId() we guarantee that the input backend supports that layer (IsLayerSupported returns true for a specific backend). If there is no guarantee the input backend supports that layer use BackendSelectionHint().
Implements IConnectableLayer.
Definition at line 291 of file Layer.hpp.
{ m_BackendId = id; }
Referenced by Graph::AddCompatibilityLayers(), NetworkImpl::AddPrecompiledLayer(), armnn::AttemptBackendAssignment(), armnn::InsertDebugLayerAfter(), and PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl().
SetGuid()
void SetGuid (LayerGuid guid) inline
Definition at line 342 of file Layer.hpp.
{ m_Guid = guid; }
SetShapeInferenceMethod()
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod) inline
Definition at line 357 of file Layer.hpp.
    {
        m_ShapeInferenceMethod = shapeInferenceMethod;
    }
References m_ShapeInferenceMethod.
ValidateAndCopyShape()
void ValidateAndCopyShape (const TensorShape & outputShape, const TensorShape & inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string & layerName, const unsigned int outputSlotIndex = 0) protected
Definition at line 457 of file Layer.cpp.
{
    if (shapeInferenceMethod == ShapeInferenceMethod::ValidateOnly)
    {
        if (m_AllowExpandedDims)
        {
            std::vector<unsigned int> outputDims = armnnUtils::SqueezeDims(outputShape);
            std::vector<unsigned int> inferredDims = armnnUtils::SqueezeDims(inferredShape);
            if (outputDims.size() != inferredDims.size())
            {
                std::stringstream ss;
                ss << layerName << ": TensorShape set on OutputSlot[" << outputSlotIndex <<
                   "] does not match the inferred shape. ";
                ss << outputShape << " != " << inferredShape;
                throw LayerValidationException(ss.str());
            }
            for (unsigned int i = 0; i < outputDims.size(); ++i)
            {
                if (outputDims[i] != inferredDims[i])
                {
                    std::stringstream ss;
                    ss << layerName << ": TensorShape set on OutputSlot[" << outputSlotIndex <<
                       "] does not match the inferred shape at dimension index [";
                    ss << i << "] " << outputShape << " != " << inferredShape;
                    throw LayerValidationException(ss.str());
                }
            }
            return;
        }
        else
        {
            ConditionalThrowIfNotEqual<LayerValidationException>(
                    layerName + ": TensorShape set on OutputSlot[0] does not match the inferred shape.",
                    outputShape,
                    inferredShape);
            return;
        }
    }
    if (outputShape.GetDimensionality() == Dimensionality::Specified)
    {
        for (unsigned int i = 0; i < outputShape.GetNumDimensions(); ++i)
        {
            if (outputShape.GetDimensionSpecificity(i) && outputShape[i] != inferredShape[i])
            {
                std::stringstream ss;
                ss << layerName << ": TensorShape set on OutputSlot[" << outputSlotIndex <<
                "] does not match the inferred shape at dimension index [";
                ss << i << "] " << outputShape << " != " << inferredShape;
                throw LayerValidationException(ss.str());
            }
        }
    }
    TensorInfo info = GetOutputSlot(outputSlotIndex).GetTensorInfo();
    armnn::TensorInfo inferredTensorInfo(inferredShape,
                                         info.GetDataType(),
                                         info.GetQuantizationScale(),
                                         info.GetQuantizationOffset());
    GetOutputSlot(outputSlotIndex).SetTensorInfo(inferredTensorInfo);
}
References armnn::ConditionalThrowIfNotEqual(), TensorShape::GetDimensionality(), TensorShape::GetDimensionSpecificity(), TensorShape::GetNumDimensions(), GetOutputSlot(), OutputSlot::GetTensorInfo(), armnn::info, OutputSlot::SetTensorInfo(), armnn::Specified, armnnUtils::SqueezeDims(), and armnn::ValidateOnly.
Referenced by AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), BroadcastToLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RankLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), SplitterLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
ValidateTensorShapesFromInputs()
virtual void ValidateTensorShapesFromInputs () pure virtual
Implemented in AbsLayer, ActivationLayer, ArgMinMaxLayer, BatchMatMulLayer, BatchNormalizationLayer, BatchToSpaceNdLayer, BroadcastToLayer, CastLayer, ChannelShuffleLayer, ComparisonLayer, ConcatLayer, ConstantLayer, ConvertFp16ToFp32Layer, ConvertFp32ToFp16Layer, Convolution2dLayer, Convolution3dLayer, DebugLayer, DepthToSpaceLayer, DepthwiseConvolution2dLayer, DequantizeLayer, DetectionPostProcessLayer, ElementwiseBaseLayer, ElementwiseBinaryLayer, ElementwiseUnaryLayer, FakeQuantizationLayer, FillLayer, FloorLayer, FullyConnectedLayer, FusedLayer, GatherLayer, GatherNdLayer, InputLayer, InstanceNormalizationLayer, L2NormalizationLayer, LogicalBinaryLayer, LogSoftmaxLayer, LstmLayer, MapLayer, MeanLayer, MemCopyLayer, MemImportLayer, MergeLayer, NormalizationLayer, OutputLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreCompiledLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, QuantizeLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, RsqrtLayer, ScatterNdLayer, ShapeLayer, SliceLayer, SoftmaxLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, SwitchLayer, TileLayer, TransposeConvolution2dLayer, TransposeLayer, UnidirectionalSequenceLstmLayer, and UnmapLayer.
Referenced by OutputSlot::IsTensorInfoSet().
VerifyLayerConnections()
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation & location) const
Definition at line 410 of file Layer.cpp.
{
    if (GetNumInputSlots() != expectedConnections)
    {
        throw armnn::Exception("input slots must match expected connections.");
    }
    for (unsigned int i=0; i<expectedConnections; ++i)
    {
        if (GetInputSlot(i).GetConnection() == nullptr)
        {
            throw LayerValidationException(
                    fmt::format("Input connection #{0} must be connected "
                                "for {1} layer {2} {3}",
                                i,
                                GetLayerTypeAsCString(this->GetType()),
                                GetNameStr(),
                                location.AsString()));
        }
    }
}
References CheckLocation::AsString(), GetInputSlot(), armnn::GetLayerTypeAsCString(), GetNameStr(), GetNumInputSlots(), and GetType().
Referenced by AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), BroadcastToLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MapLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RankLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs(), and UnmapLayer::ValidateTensorShapesFromInputs().
VerifyShapeInferenceType()
void VerifyShapeInferenceType (const TensorShape & outputShape, ShapeInferenceMethod shapeInferenceMethod) protected
Definition at line 526 of file Layer.cpp.
{
    if (shapeInferenceMethod == ShapeInferenceMethod::ValidateOnly)
    {
        ConditionalThrow<LayerValidationException>(
                outputShape.GetDimensionality() != Dimensionality::NotSpecified,
                "Dimensionality can not be NotSpecified while using ShapeInferenceMethod::ValidateOnly");
        ConditionalThrow<LayerValidationException>(
                outputShape.AreAllDimensionsSpecified(),
                "Unspecified dimension while using ShapeInferenceMethod::ValidateOnly");
    }
}
References TensorShape::AreAllDimensionsSpecified(), armnn::ConditionalThrow(), TensorShape::GetDimensionality(), armnn::NotSpecified, and armnn::ValidateOnly.
Referenced by AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), BroadcastToLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RankLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), SplitterLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
Friends And Related Symbol Documentation
Graph
friend class Graph friend
Definition at line 382 of file Layer.hpp.
References Graph.
Referenced by AbsLayer::Clone(), CastLayer::Clone(), ConstantLayer::Clone(), ConvertFp16ToFp32Layer::Clone(), ConvertFp32ToFp16Layer::Clone(), DebugLayer::Clone(), DequantizeLayer::Clone(), FloorLayer::Clone(), GatherNdLayer::Clone(), Clone(), MapLayer::Clone(), MemCopyLayer::Clone(), MemImportLayer::Clone(), MergeLayer::Clone(), PreluLayer::Clone(), QuantizedLstmLayer::Clone(), QuantizeLayer::Clone(), RankLayer::Clone(), RsqrtLayer::Clone(), ShapeLayer::Clone(), SwitchLayer::Clone(), UnmapLayer::Clone(), CloneBase(), Graph, and Reparent().
Member Data Documentation
m_AdditionalInfoObject
AdditionalInfoObjectPtr m_AdditionalInfoObject protected
Definition at line 430 of file Layer.hpp.
Referenced by FusedLayer::Clone(), GetAdditionalInformation(), SetAdditionalInfo(), and SetAdditionalInfoForObject().
m_OutputHandlers
std::vector<OutputHandler> m_OutputHandlers protected
Definition at line 440 of file Layer.hpp.
Referenced by GetOutputHandler(), and Layer().
m_ShapeInferenceMethod
ShapeInferenceMethod m_ShapeInferenceMethod protected
Definition at line 441 of file Layer.hpp.
Referenced by CloneBase(), GetShapeInferenceMethod(), Layer(), SetShapeInferenceMethod(), AbsLayer::ValidateTensorShapesFromInputs(), ActivationLayer::ValidateTensorShapesFromInputs(), ArgMinMaxLayer::ValidateTensorShapesFromInputs(), BatchMatMulLayer::ValidateTensorShapesFromInputs(), BatchNormalizationLayer::ValidateTensorShapesFromInputs(), BatchToSpaceNdLayer::ValidateTensorShapesFromInputs(), BroadcastToLayer::ValidateTensorShapesFromInputs(), CastLayer::ValidateTensorShapesFromInputs(), ChannelShuffleLayer::ValidateTensorShapesFromInputs(), ComparisonLayer::ValidateTensorShapesFromInputs(), ConcatLayer::ValidateTensorShapesFromInputs(), ConvertFp16ToFp32Layer::ValidateTensorShapesFromInputs(), ConvertFp32ToFp16Layer::ValidateTensorShapesFromInputs(), Convolution2dLayer::ValidateTensorShapesFromInputs(), Convolution3dLayer::ValidateTensorShapesFromInputs(), DebugLayer::ValidateTensorShapesFromInputs(), DepthToSpaceLayer::ValidateTensorShapesFromInputs(), DepthwiseConvolution2dLayer::ValidateTensorShapesFromInputs(), DequantizeLayer::ValidateTensorShapesFromInputs(), DetectionPostProcessLayer::ValidateTensorShapesFromInputs(), ElementwiseBaseLayer::ValidateTensorShapesFromInputs(), ElementwiseBinaryLayer::ValidateTensorShapesFromInputs(), ElementwiseUnaryLayer::ValidateTensorShapesFromInputs(), FakeQuantizationLayer::ValidateTensorShapesFromInputs(), FillLayer::ValidateTensorShapesFromInputs(), FloorLayer::ValidateTensorShapesFromInputs(), FullyConnectedLayer::ValidateTensorShapesFromInputs(), GatherLayer::ValidateTensorShapesFromInputs(), GatherNdLayer::ValidateTensorShapesFromInputs(), InstanceNormalizationLayer::ValidateTensorShapesFromInputs(), L2NormalizationLayer::ValidateTensorShapesFromInputs(), LogicalBinaryLayer::ValidateTensorShapesFromInputs(), LogSoftmaxLayer::ValidateTensorShapesFromInputs(), LstmLayer::ValidateTensorShapesFromInputs(), MeanLayer::ValidateTensorShapesFromInputs(), MemCopyLayer::ValidateTensorShapesFromInputs(), MemImportLayer::ValidateTensorShapesFromInputs(), MergeLayer::ValidateTensorShapesFromInputs(), NormalizationLayer::ValidateTensorShapesFromInputs(), PadLayer::ValidateTensorShapesFromInputs(), PermuteLayer::ValidateTensorShapesFromInputs(), Pooling2dLayer::ValidateTensorShapesFromInputs(), Pooling3dLayer::ValidateTensorShapesFromInputs(), PreluLayer::ValidateTensorShapesFromInputs(), QLstmLayer::ValidateTensorShapesFromInputs(), QuantizedLstmLayer::ValidateTensorShapesFromInputs(), QuantizeLayer::ValidateTensorShapesFromInputs(), RankLayer::ValidateTensorShapesFromInputs(), ReduceLayer::ValidateTensorShapesFromInputs(), ReshapeLayer::ValidateTensorShapesFromInputs(), ResizeLayer::ValidateTensorShapesFromInputs(), ReverseV2Layer::ValidateTensorShapesFromInputs(), RsqrtLayer::ValidateTensorShapesFromInputs(), ScatterNdLayer::ValidateTensorShapesFromInputs(), ShapeLayer::ValidateTensorShapesFromInputs(), SliceLayer::ValidateTensorShapesFromInputs(), SoftmaxLayer::ValidateTensorShapesFromInputs(), SpaceToBatchNdLayer::ValidateTensorShapesFromInputs(), SpaceToDepthLayer::ValidateTensorShapesFromInputs(), SplitterLayer::ValidateTensorShapesFromInputs(), StackLayer::ValidateTensorShapesFromInputs(), StridedSliceLayer::ValidateTensorShapesFromInputs(), SwitchLayer::ValidateTensorShapesFromInputs(), TileLayer::ValidateTensorShapesFromInputs(), TransposeConvolution2dLayer::ValidateTensorShapesFromInputs(), TransposeLayer::ValidateTensorShapesFromInputs(), and UnidirectionalSequenceLstmLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/Layer.hpp
src/armnn/Layer.cpp
src/armnn/layers/LayerCloneBase.hpp