Arm NN: SampleDynamicWorkloadFactory Class Reference
SampleDynamicWorkloadFactory Class Reference
#include <SampleDynamicWorkloadFactory.hpp>
Public Member Functions
SampleDynamicWorkloadFactory (const std::shared_ptr< SampleMemoryManager > &memoryManager)
SampleDynamicWorkloadFactory ()
~SampleDynamicWorkloadFactory ()
const armnn::BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< armnn::ITensorHandle > CreateSubTensorHandle (armnn::ITensorHandle &parent, armnn::TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo &tensorInfo, armnn::DataLayout dataLayout, const bool IsMemoryManaged=true) const override
std::unique_ptr< armnn::IWorkload > CreateAddition (const armnn::AdditionQueueDescriptor &descriptor, const armnn::WorkloadInfo &info) const
std::unique_ptr< armnn::IWorkload > CreateInput (const armnn::InputQueueDescriptor &descriptor, const armnn::WorkloadInfo &info) const
std::unique_ptr< armnn::IWorkload > CreateOutput (const armnn::OutputQueueDescriptor &descriptor, const armnn::WorkloadInfo &info) const
std::unique_ptr< armnn::IWorkload > CreateWorkload (armnn::LayerType type, const armnn::QueueDescriptor &descriptor, const armnn::WorkloadInfo &info) const override
Backends should implement their own CreateWorkload function with a switch statement.
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual void AfterWorkloadsCreated ()
Static Public Member Functions
static bool IsLayerSupported (const armnn::IConnectableLayer &layer, armnn::Optional< armnn::DataType > dataType, std::string &outReasonIfUnsupported)
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 16 of file SampleDynamicWorkloadFactory.hpp.
Constructor & Destructor Documentation
SampleDynamicWorkloadFactory() [1/2]
SampleDynamicWorkloadFactory (const std::shared_ptr< SampleMemoryManager > & memoryManager) explicit
Definition at line 23 of file SampleDynamicWorkloadFactory.cpp.
    : m_MemoryManager(memoryManager)
{
}
SampleDynamicWorkloadFactory() [2/2]
SampleDynamicWorkloadFactory ()
Definition at line 28 of file SampleDynamicWorkloadFactory.cpp.
    : m_MemoryManager(new SampleMemoryManager())
{
}
~SampleDynamicWorkloadFactory()
~SampleDynamicWorkloadFactory () inline
Definition at line 22 of file SampleDynamicWorkloadFactory.hpp.
{}
Member Function Documentation
CreateAddition()
std::unique_ptr< armnn::IWorkload > CreateAddition (const armnn::AdditionQueueDescriptor & descriptor, const armnn::WorkloadInfo & info) const
Definition at line 60 of file SampleDynamicWorkloadFactory.cpp.
{
    return std::make_unique<SampleDynamicAdditionWorkload>(descriptor, info);
}
CreateInput()
std::unique_ptr< armnn::IWorkload > CreateInput (const armnn::InputQueueDescriptor & descriptor, const armnn::WorkloadInfo & info) const
Definition at line 67 of file SampleDynamicWorkloadFactory.cpp.
{
    return std::make_unique<armnn::CopyMemGenericWorkload>(descriptor, info);
}
CreateOutput()
std::unique_ptr< armnn::IWorkload > CreateOutput (const armnn::OutputQueueDescriptor & descriptor, const armnn::WorkloadInfo & info) const
Definition at line 74 of file SampleDynamicWorkloadFactory.cpp.
{
    return std::make_unique<armnn::CopyMemGenericWorkload>(descriptor, info);
}
CreateSubTensorHandle()
std::unique_ptr< armnn::ITensorHandle > CreateSubTensorHandle (armnn::ITensorHandle & parent, armnn::TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const inline override virtual
Implements IWorkloadFactory.
Definition at line 33 of file SampleDynamicWorkloadFactory.hpp.
    {
        IgnoreUnused(parent, subTensorShape, subTensorOrigin);
        return nullptr;
    }
References CreateSubTensorHandle().
Referenced by CreateSubTensorHandle().
CreateTensorHandle() [1/2]
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo & tensorInfo, armnn::DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 52 of file SampleDynamicWorkloadFactory.cpp.
{
    return std::make_unique<armnn::ScopedTensorHandle>(tensorInfo);
}
CreateTensorHandle() [2/2]
std::unique_ptr< armnn::ITensorHandle > CreateTensorHandle (const armnn::TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 45 of file SampleDynamicWorkloadFactory.cpp.
{
    return std::make_unique<armnn::ScopedTensorHandle>(tensorInfo);
}
CreateWorkload()
std::unique_ptr< armnn::IWorkload > CreateWorkload (armnn::LayerType type, const armnn::QueueDescriptor & descriptor, const armnn::WorkloadInfo & info) const override virtual
Backends should implement their own CreateWorkload function with a switch statement.
The case for the switch should be the LayerType and based on that they will call their specific workload creation functionality.
Implements IWorkloadFactory.
Definition at line 81 of file SampleDynamicWorkloadFactory.cpp.
{
    using namespace armnn;
    using namespace sdb;
    switch(type)
    {
        case LayerType::Addition:
        {
            auto additionQueueDescriptor = PolymorphicDowncast<const AdditionQueueDescriptor*>(&descriptor);
            return std::make_unique<SampleDynamicAdditionWorkload>(*additionQueueDescriptor, info);
        }
        case LayerType::Input:
        {
            auto inputQueueDescriptor = PolymorphicDowncast<const InputQueueDescriptor*>(&descriptor);
            return std::make_unique<CopyMemGenericWorkload>(*inputQueueDescriptor, info);
        }
        case LayerType::Output:
        {
            auto outputQueueDescriptor = PolymorphicDowncast<const OutputQueueDescriptor*>(&descriptor);
            return std::make_unique<CopyMemGenericWorkload>(*outputQueueDescriptor, info);
        }
        default:
            return nullptr;
    }
}
References armnn::Addition, armnn::info, armnn::Input, armnn::Output, and armnn::PolymorphicDowncast().
GetBackendId()
const armnn::BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 33 of file SampleDynamicWorkloadFactory.cpp.
{
    return s_Id;
}
IsLayerSupported()
bool IsLayerSupported (const armnn::IConnectableLayer & layer, armnn::Optional< armnn::DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 38 of file SampleDynamicWorkloadFactory.cpp.
{
    return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported);
}
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Implements IWorkloadFactory.
Definition at line 30 of file SampleDynamicWorkloadFactory.hpp.
{ return false; }
The documentation for this class was generated from the following files:
src/dynamic/sample/SampleDynamicWorkloadFactory.hpp
src/dynamic/sample/SampleDynamicWorkloadFactory.cpp