Arm NN: Graph::LayerInGraph< ConstantLayer > Class Reference
Graph::LayerInGraph< ConstantLayer > Class Reference final
#include <Graph.hpp>
Public Member Functions
template<typename... Args>
LayerInGraph (Graph &graph, Args &&... args)
template<typename... Args>
LayerInGraph (Graph &graph, Iterator, Args &&... args)
~LayerInGraph () override
Detailed Description
Definition at line 380 of file Graph.hpp.
Constructor & Destructor Documentation
LayerInGraph() [1/2]
template<typename... Args> LayerInGraph (Graph & graph, Args &&... args) inline
Definition at line 384 of file Graph.hpp.
            : LayerInGraphBase<ConstantLayer>(graph,
                                              // Always add to the back of the inputs.
                                              std::next(graph.begin(), IteratorDifference(graph.GetNumInputs())),
                                              std::forward<Args>(args)...)
    {}
References Graph::begin(), Graph::GetNumInputs(), and Graph::Graph().
Referenced by LayerInGraph().
LayerInGraph() [2/2]
template<typename... Args> LayerInGraph (Graph & graph, Iterator , Args &&... args) inline
Definition at line 391 of file Graph.hpp.
        : LayerInGraph(graph, std::forward<Args>(args)...)
    {}
References Graph::Graph(), and LayerInGraph().
~LayerInGraph()
~LayerInGraph () inline override
Definition at line 395 of file Graph.hpp.
    {}
The documentation for this class was generated from the following file:
src/armnn/Graph.hpp