Arm NN: StrategyBase< DefaultStrategy > Class Template Reference
StrategyBase< DefaultStrategy > Class Template Reference
Strategy base class with empty implementations.
#include <StrategyBase.hpp>
Public Member Functions
virtual void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Protected Member Functions
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Protected Attributes
DefaultStrategy m_DefaultStrategy
Detailed Description
template<typename DefaultStrategy>
class armnn::StrategyBase< DefaultStrategy >
Strategy base class with empty implementations.
Definition at line 27 of file StrategyBase.hpp.
Constructor & Destructor Documentation
~StrategyBase()
template<typename DefaultStrategy> virtual ~StrategyBase () inline protected virtual
Definition at line 30 of file StrategyBase.hpp.
{};
Member Function Documentation
ExecuteStrategy()
template<typename DefaultStrategy> virtual void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Implements IStrategy.
Definition at line 33 of file StrategyBase.hpp.
    {
        armnn::IgnoreUnused(descriptor, constants, id, name);
        switch (layer->GetType())
        {
            default:
            {
                m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
            }
        }
    }
References armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), and m_DefaultStrategy.
Member Data Documentation
m_DefaultStrategy
template<typename DefaultStrategy> DefaultStrategy m_DefaultStrategy protected
Definition at line 50 of file StrategyBase.hpp.
Referenced by ExecuteStrategy().
The documentation for this class was generated from the following file:
include/armnn/StrategyBase.hpp