Arm NN: ClElementwiseBinaryWorkload Class Reference
ClElementwiseBinaryWorkload Class Reference
#include <ClElementwiseBinaryWorkload.hpp>
Public Member Functions
ClElementwiseBinaryWorkload (const ElementwiseBinaryQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
void Execute () const override
Public Member Functions inherited from ClBaseWorkload< ElementwiseBinaryQueueDescriptor >
ClBaseWorkload (const ElementwiseBinaryQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< ElementwiseBinaryQueueDescriptor >
BaseWorkload (const ElementwiseBinaryQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const ElementwiseBinaryQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< ElementwiseBinaryQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< ElementwiseBinaryQueueDescriptor >
ElementwiseBinaryQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 15 of file ClElementwiseBinaryWorkload.hpp.
Constructor & Destructor Documentation
ClElementwiseBinaryWorkload()
ClElementwiseBinaryWorkload (const ElementwiseBinaryQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 19 of file ClElementwiseBinaryWorkload.cpp.
    : ClBaseWorkload<ElementwiseBinaryQueueDescriptor>(descriptor, info)
{
    this->m_Data.ValidateInputsOutputs("ClElementwiseBinaryWorkload", 2, 1);
    arm_compute::ICLTensor &input0 = static_cast<IClTensorHandle *>(this->m_Data.m_Inputs[0])->GetTensor();
    arm_compute::ICLTensor &input1 = static_cast<IClTensorHandle *>(this->m_Data.m_Inputs[1])->GetTensor();
    arm_compute::ICLTensor &output = static_cast<IClTensorHandle *>(this->m_Data.m_Outputs[0])->GetTensor();
    const arm_compute::ActivationLayerInfo activationInfo = ConvertAdditionalInfoToAclActivationLayerInfo(descriptor);
    {
        ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID("ClElementwiseBinaryWorkload_configure");
        switch (descriptor.m_Parameters.m_Operation)
        {
            case armnn::BinaryOperation::Power:
            {
                auto powerLayer = std::make_unique<arm_compute::CLElementwisePower>();
                powerLayer->configure(clCompileContext, &input0, &input1, &output, activationInfo);
                m_ElementwiseBinaryLayer.reset(powerLayer.release());
                break;
            }
            case armnn::BinaryOperation::SqDiff:
            {
                auto SqDiffLayer = std::make_unique<arm_compute::CLElementwiseSquaredDiff>();
                SqDiffLayer->configure(clCompileContext, &input0, &input1, &output, activationInfo);
                m_ElementwiseBinaryLayer.reset(SqDiffLayer.release());
                break;
            }
            default:
                throw InvalidArgumentException("Unknown binary operator", CHECK_LOCATION());
        }
    }
}
References ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID, CHECK_LOCATION, ClBaseWorkload< ElementwiseBinaryQueueDescriptor >::ClBaseWorkload(), armnn::ConvertAdditionalInfoToAclActivationLayerInfo(), IClTensorHandle::GetTensor(), armnn::info, BaseWorkload< ElementwiseBinaryQueueDescriptor >::m_Data, ElementwiseBinaryDescriptor::m_Operation, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::Power, and armnn::SqDiff.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 55 of file ClElementwiseBinaryWorkload.cpp.
{
    if (m_ElementwiseBinaryLayer)
    {
        ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID("ClElementwiseBinaryWorkload_Execute");
        m_ElementwiseBinaryLayer->run();
    }
}
References ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID.
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClElementwiseBinaryWorkload.hpp
src/backends/cl/workloads/ClElementwiseBinaryWorkload.cpp