Arm NN: OptimizeForConnectionImpl< BaseType, ChildType, Wrapped > Class Template Reference
OptimizeForConnectionImpl< BaseType, ChildType, Wrapped > Class Template Reference
Wrapper Optimization class that calls Wrapped::Run for every connection BaseType -> ChildType.
#include <Optimization.hpp>
Public Member Functions
void Run (Graph &graph, BaseType &base) const
Protected Member Functions
~OptimizeForConnectionImpl ()=default
Detailed Description
template<typename BaseType, typename ChildType, typename Wrapped>
class armnn::OptimizeForConnectionImpl< BaseType, ChildType, Wrapped >
Wrapper Optimization class that calls Wrapped::Run for every connection BaseType -> ChildType.
Wrapped class mustn't remove the base layer. The optimizer will remove it if left unconnected after applying each optimization.
Wrapped class mustn't affect existing connections in the same output. It might add new ones.
Children layers are removed if left unconnected after applying the wrapped optimization.
Definition at line 79 of file Optimization.hpp.
Constructor & Destructor Documentation
~OptimizeForConnectionImpl()
template<typename BaseType, typename ChildType, typename Wrapped> ~OptimizeForConnectionImpl () protected default
Member Function Documentation
Run()
template<typename BaseType, typename ChildType, typename Wrapped> void Run (Graph & graph, BaseType & base) const inline
Definition at line 84 of file Optimization.hpp.
    {
        for (auto output = base.BeginOutputSlots(); output != base.EndOutputSlots(); ++output)
        {
            for (auto&& childInput : output->GetConnections())
            {
                if (childInput->GetOwningLayer().GetType() == LayerEnumOf<ChildType>())
                {
                    Wrapped::Run(graph, *childInput);
                }
            }
            // Removes unconnected children.
            for (unsigned int i = 0; i < output->GetNumConnections();)
            {
                Layer* child = &output->GetConnection(i)->GetOwningLayer();
                if (child->IsOutputUnconnected())
                {
                    graph.EraseLayer(child);
                }
                else
                {
                    ++i;
                }
            }
        }
    }
References Graph::EraseLayer(), Layer::IsOutputUnconnected(), and armnn::LayerEnumOf().
The documentation for this class was generated from the following file:
src/armnn/optimizations/Optimization.hpp