Arm NN: ClMemoryManager Class Reference
ClMemoryManager Class Reference
#include <BaseMemoryManager.hpp>
Public Member Functions
ClMemoryManager ()
virtual ~ClMemoryManager ()
ClMemoryManager (std::shared_ptr< arm_compute::IAllocator > alloc)
Public Member Functions inherited from BaseMemoryManager
BaseMemoryManager ()
virtual ~BaseMemoryManager ()
void Acquire () override
void Release () override
BaseMemoryManager (std::shared_ptr< arm_compute::IAllocator > alloc, MemoryAffinity memoryAffinity)
std::shared_ptr< arm_compute::MemoryManagerOnDemand > & GetIntraLayerManager ()
std::shared_ptr< arm_compute::MemoryManagerOnDemand > & GetInterLayerManager ()
std::shared_ptr< arm_compute::IMemoryGroup > & GetInterLayerMemoryGroup ()
Public Member Functions inherited from IMemoryManager
virtual ~IMemoryManager ()
Protected Member Functions
std::shared_ptr< arm_compute::IMemoryGroup > CreateMemoryGroup (const std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager) override
Protected Member Functions inherited from BaseMemoryManager
std::shared_ptr< arm_compute::MemoryManagerOnDemand > CreateArmComputeMemoryManager (MemoryAffinity memoryAffinity)
Protected Member Functions inherited from IMemoryManager
IMemoryManager ()
Additional Inherited Members
Public Types inherited from BaseMemoryManager
enum class MemoryAffinity { Buffer , Offset }
Protected Attributes inherited from BaseMemoryManager
std::shared_ptr< arm_compute::IAllocator > m_Allocator
std::shared_ptr< arm_compute::MemoryManagerOnDemand > m_IntraLayerMemoryMgr
std::shared_ptr< arm_compute::MemoryManagerOnDemand > m_InterLayerMemoryMgr
std::shared_ptr< arm_compute::IMemoryGroup > m_InterLayerMemoryGroup
Detailed Description
Definition at line 79 of file BaseMemoryManager.hpp.
Constructor & Destructor Documentation
ClMemoryManager() [1/2]
ClMemoryManager () inline
Definition at line 82 of file BaseMemoryManager.hpp.
{}
~ClMemoryManager()
virtual ~ClMemoryManager () inline virtual
Definition at line 83 of file BaseMemoryManager.hpp.
{}
ClMemoryManager() [2/2]
ClMemoryManager (std::shared_ptr< arm_compute::IAllocator > alloc) inline
Definition at line 85 of file BaseMemoryManager.hpp.
    : BaseMemoryManager(std::move(alloc), MemoryAffinity::Buffer)
    {
        arm_compute::CLTensorAllocator::set_global_allocator(alloc.get());
        m_InterLayerMemoryGroup = CreateMemoryGroup(m_InterLayerMemoryMgr);
    }
References BaseMemoryManager::BaseMemoryManager(), BaseMemoryManager::Buffer, CreateMemoryGroup(), BaseMemoryManager::m_InterLayerMemoryGroup, and BaseMemoryManager::m_InterLayerMemoryMgr.
Member Function Documentation
CreateMemoryGroup()
std::shared_ptr< arm_compute::IMemoryGroup > CreateMemoryGroup (const std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager) override protected virtual
Implements BaseMemoryManager.
Definition at line 95 of file BaseMemoryManager.cpp.
{
    return std::make_shared<arm_compute::MemoryGroup>(memoryManager);
}
Referenced by ClMemoryManager().
The documentation for this class was generated from the following files:
src/backends/aclCommon/BaseMemoryManager.hpp
src/backends/aclCommon/BaseMemoryManager.cpp