Arm NN: TypedIterator< T, Base > Class Template Reference
TypedIterator< T, Base > Class Template Reference
#include <BaseIterator.hpp>
Public Member Functions
TypedIterator (T *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Protected Attributes
T * m_Iterator
T * m_Start
Detailed Description
template<typename T, typename Base>
class armnn::TypedIterator< T, Base >
Definition at line 65 of file BaseIterator.hpp.
Constructor & Destructor Documentation
TypedIterator()
template<typename T, typename Base> TypedIterator (T * data = nullptr) inline
Definition at line 68 of file BaseIterator.hpp.
        : m_Iterator(data), m_Start(data)
    {}
References m_Iterator, and m_Start.
Referenced by operator++(), operator+=(), operator-=(), and operator[]().
Member Function Documentation
operator++()
template<typename T, typename Base> TypedIterator & operator++ () inline override
Definition at line 78 of file BaseIterator.hpp.
    {
        ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(m_Iterator, "TypedIterator: m_Iterator is null!");
        ++m_Iterator;
        return *this;
    }
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, m_Iterator, and TypedIterator().
operator+=()
template<typename T, typename Base> TypedIterator & operator+= (const unsigned int increment) inline override
Definition at line 85 of file BaseIterator.hpp.
    {
        ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(m_Iterator, "TypedIterator: m_Iterator is null!");
        m_Iterator += increment;
        return *this;
    }
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, m_Iterator, and TypedIterator().
operator-=()
template<typename T, typename Base> TypedIterator & operator-= (const unsigned int increment) inline override
Definition at line 92 of file BaseIterator.hpp.
    {
        ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(m_Iterator, "TypedIterator: m_Iterator is null!");
        m_Iterator -= increment;
        return *this;
    }
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, m_Iterator, and TypedIterator().
operator[]()
template<typename T, typename Base> TypedIterator & operator[] (const unsigned int index) inline override
Definition at line 99 of file BaseIterator.hpp.
    {
        ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(m_Iterator, "TypedIterator: m_Iterator is null!");
        m_Iterator = m_Start + index;
        return *this;
    }
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE, m_Iterator, m_Start, and TypedIterator().
Reset()
template<typename T, typename Base> void Reset (void * data) inline override
Definition at line 72 of file BaseIterator.hpp.
    {
        m_Iterator = reinterpret_cast<T*>(data);
        m_Start = m_Iterator;
    }
References m_Iterator, and m_Start.
Member Data Documentation
m_Iterator
template<typename T, typename Base> T* m_Iterator protected
Definition at line 107 of file BaseIterator.hpp.
Referenced by operator++(), operator+=(), operator-=(), operator[](), Reset(), and TypedIterator().
m_Start
template<typename T, typename Base> T* m_Start protected
Definition at line 108 of file BaseIterator.hpp.
Referenced by operator[](), Reset(), and TypedIterator().
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp