Arm NN: TosaRefWorkloadFactory Class Reference
TosaRefWorkloadFactory Class Reference
#include <TosaRefWorkloadFactory.hpp>
Public Member Functions
TosaRefWorkloadFactory (const std::shared_ptr< TosaRefMemoryManager > &memoryManager)
TosaRefWorkloadFactory ()
~TosaRefWorkloadFactory ()
const BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
std::unique_ptr< IWorkload > CreateWorkload (LayerType type, const QueueDescriptor &descriptor, const WorkloadInfo &info) const override
Backends should implement their own CreateWorkload function with a switch statement.
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual void AfterWorkloadsCreated ()
Static Public Member Functions
static bool IsLayerSupported (const Layer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 18 of file TosaRefWorkloadFactory.hpp.
Constructor & Destructor Documentation
TosaRefWorkloadFactory() [1/2]
TosaRefWorkloadFactory (const std::shared_ptr< TosaRefMemoryManager > & memoryManager) explicit
Definition at line 49 of file TosaRefWorkloadFactory.cpp.
    : m_MemoryManager(memoryManager)
{
}
TosaRefWorkloadFactory() [2/2]
TosaRefWorkloadFactory ()
Definition at line 54 of file TosaRefWorkloadFactory.cpp.
    : m_MemoryManager(new TosaRefMemoryManager())
{
}
~TosaRefWorkloadFactory()
~TosaRefWorkloadFactory () inline
Definition at line 24 of file TosaRefWorkloadFactory.hpp.
{}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const inline override virtual
Implements IWorkloadFactory.
Definition at line 40 of file TosaRefWorkloadFactory.hpp.
    {
        IgnoreUnused(parent, subTensorShape, subTensorOrigin);
        return nullptr;
    }
References CreateSubTensorHandle(), and armnn::IgnoreUnused().
Referenced by CreateSubTensorHandle().
CreateTensorHandle() [1/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 79 of file TosaRefWorkloadFactory.cpp.
{
    if (isMemoryManaged)
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_MemoryManager);
    }
    else
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, static_cast<unsigned int>(MemorySource::Malloc));
    }
}
References armnn::Malloc.
CreateTensorHandle() [2/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Implements IWorkloadFactory.
Definition at line 92 of file TosaRefWorkloadFactory.cpp.
{
    // For TosaRef it is okay to make the TensorHandle memory managed as it can also store a pointer
    // to unmanaged memory. This also ensures memory alignment.
    IgnoreUnused(isMemoryManaged, dataLayout);
    if (isMemoryManaged)
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, m_MemoryManager);
    }
    else
    {
        return std::make_unique<TosaRefTensorHandle>(tensorInfo, static_cast<unsigned int>(MemorySource::Malloc));
    }
}
References armnn::IgnoreUnused(), and armnn::Malloc.
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (LayerType type, const QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Backends should implement their own CreateWorkload function with a switch statement.
The case for the switch should be the LayerType and based on that they will call their specific workload creation functionality.
Implements IWorkloadFactory.
Definition at line 110 of file TosaRefWorkloadFactory.cpp.
{
    switch(type)
    {
        case LayerType::PreCompiled:
        {
            auto precompiledQueueDescriptor = PolymorphicDowncast<const PreCompiledQueueDescriptor*>(&descriptor);
            return std::make_unique<TosaRefPreCompiledWorkload>(*precompiledQueueDescriptor, info);
        }
        default:
            return nullptr;
    }
}
References armnn::info, armnn::PolymorphicDowncast(), and armnn::PreCompiled.
GetBackendId()
const BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 59 of file TosaRefWorkloadFactory.cpp.
{
    return s_Id;
}
IsLayerSupported() [1/2]
bool IsLayerSupported (const IConnectableLayer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported, const ModelOptions & modelOptions) static
Definition at line 71 of file TosaRefWorkloadFactory.cpp.
{
    return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported, modelOptions);
}
References IWorkloadFactory::IsLayerSupported().
IsLayerSupported() [2/2]
bool IsLayerSupported (const Layer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 64 of file TosaRefWorkloadFactory.cpp.
{
    return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported);
}
References IWorkloadFactory::IsLayerSupported().
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Implements IWorkloadFactory.
Definition at line 37 of file TosaRefWorkloadFactory.hpp.
{ return false; }
The documentation for this class was generated from the following files:
src/backends/tosaReference/TosaRefWorkloadFactory.hpp
src/backends/tosaReference/TosaRefWorkloadFactory.cpp