Arm NN: IConnectableLayer Class Reference
IConnectableLayer Class Reference abstract
Interface for a layer that is connectable to other layers via InputSlots and OutputSlots.
#include <INetwork.hpp>
Public Types
using ConstantTensors = std::vector<std::reference_wrapper<std::shared_ptr<ConstTensorHandle>>>
using ImmutableConstantTensors = std::vector<std::reference_wrapper<const std::shared_ptr<ConstTensorHandle>>>
Public Member Functions
virtual const char * GetName () const =0
Returns the name of the layer.
virtual unsigned int GetNumInputSlots () const =0
Returns the number of connectable input slots.
virtual unsigned int GetNumOutputSlots () const =0
Returns the number of connectable output slots.
virtual const IInputSlot & GetInputSlot (unsigned int index) const =0
Get a const input slot handle by slot index.
virtual IInputSlot & GetInputSlot (unsigned int index)=0
Get the input slot handle by slot index.
virtual const IOutputSlot & GetOutputSlot (unsigned int index) const =0
Get the const output slot handle by slot index.
virtual IOutputSlot & GetOutputSlot (unsigned int index)=0
Get the output slot handle by slot index.
virtual std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const =0
Infer the shape of the output(s) based on the provided input shape(s)
virtual LayerGuid GetGuid () const =0
Returns the unique id of the layer.
virtual void ExecuteStrategy (IStrategy &strategy) const =0
Apply a visitor to this layer.
virtual void BackendSelectionHint (Optional< BackendId > backend)=0
Provide a hint for the optimizer as to which backend to prefer for this layer.
virtual LayerType GetType () const =0
Returns the armnn::LayerType of this layer.
virtual const BaseDescriptor & GetParameters () const =0
If the layer has a descriptor return it.
virtual void SetBackendId (const BackendId &id)=0
Set the backend of the IConnectableLayer.
virtual ConstantTensors GetConstantTensorsByRef ()=0
virtual ImmutableConstantTensors GetConstantTensorsByRef () const =0
Protected Member Functions
~IConnectableLayer ()
Objects are not deletable via the handle.
Detailed Description
Interface for a layer that is connectable to other layers via InputSlots and OutputSlots.
Examples
CustomMemoryAllocatorSample.cpp, DynamicSample.cpp, and SimpleSample.cpp.
Definition at line 80 of file INetwork.hpp.
Member Typedef Documentation
ConstantTensors
using ConstantTensors = std::vector<std::reference_wrapper<std::shared_ptr<ConstTensorHandle>>>
Definition at line 136 of file INetwork.hpp.
ImmutableConstantTensors
using ImmutableConstantTensors = std::vector<std::reference_wrapper<const std::shared_ptr<ConstTensorHandle>>>
Definition at line 141 of file INetwork.hpp.
Constructor & Destructor Documentation
~IConnectableLayer()
~IConnectableLayer () inline protected
Objects are not deletable via the handle.
Definition at line 148 of file INetwork.hpp.
{}
Member Function Documentation
BackendSelectionHint()
virtual void BackendSelectionHint (Optional< BackendId > backend) pure virtual
Provide a hint for the optimizer as to which backend to prefer for this layer.
By providing a BackendSelectionHint there is no guarantee the input backend supports that layer. If IsLayerSupported() returns false with the backend hint, we default to calling IsLayerSupported() on the BackendPreferences vector. Use SetBackendId() if we can guarantee a backend supports that layer (IsLayerSupported returns true for a specific backend).
Implemented in Layer.
ExecuteStrategy()
virtual void ExecuteStrategy (IStrategy & strategy) const pure virtual
Apply a visitor to this layer.
Implemented in AbsLayer, ActivationLayer, AdditionLayer, ArgMinMaxLayer, BatchNormalizationLayer, BatchToSpaceNdLayer, BindableLayer, BroadcastToLayer, ComparisonLayer, ConcatLayer, ConstantLayer, ConvertFp16ToFp32Layer, ConvertFp32ToFp16Layer, Convolution2dLayer, Convolution3dLayer, DebugLayer, DepthToSpaceLayer, DepthwiseConvolution2dLayer, DequantizeLayer, DetectionPostProcessLayer, DivisionLayer, ElementwiseBaseLayer, ElementwiseBinaryLayer, ElementwiseUnaryLayer, FakeQuantizationLayer, FillLayer, FloorLayer, FullyConnectedLayer, FusedLayer, GatherLayer, InputLayer, InstanceNormalizationLayer, L2NormalizationLayer, Layer, LayerWithParameters< Parameters >, LayerWithParameters< ActivationDescriptor >, LayerWithParameters< ArgMinMaxDescriptor >, LayerWithParameters< BatchMatMulDescriptor >, LayerWithParameters< BatchNormalizationDescriptor >, LayerWithParameters< BatchToSpaceNdDescriptor >, LayerWithParameters< BroadcastToDescriptor >, LayerWithParameters< ChannelShuffleDescriptor >, LayerWithParameters< ComparisonDescriptor >, LayerWithParameters< Convolution2dDescriptor >, LayerWithParameters< Convolution3dDescriptor >, LayerWithParameters< DepthToSpaceDescriptor >, LayerWithParameters< DepthwiseConvolution2dDescriptor >, LayerWithParameters< DetectionPostProcessDescriptor >, LayerWithParameters< ElementwiseBinaryDescriptor >, LayerWithParameters< ElementwiseUnaryDescriptor >, LayerWithParameters< FakeQuantizationDescriptor >, LayerWithParameters< FillDescriptor >, LayerWithParameters< FullyConnectedDescriptor >, LayerWithParameters< FusedDescriptor >, LayerWithParameters< GatherDescriptor >, LayerWithParameters< InstanceNormalizationDescriptor >, LayerWithParameters< L2NormalizationDescriptor >, LayerWithParameters< LogicalBinaryDescriptor >, LayerWithParameters< LogSoftmaxDescriptor >, LayerWithParameters< LstmDescriptor >, LayerWithParameters< MeanDescriptor >, LayerWithParameters< NormalizationDescriptor >, LayerWithParameters< OriginsDescriptor >, LayerWithParameters< PadDescriptor >, LayerWithParameters< PermuteDescriptor >, LayerWithParameters< Pooling2dDescriptor >, LayerWithParameters< Pooling3dDescriptor >, LayerWithParameters< PreCompiledDescriptor >, LayerWithParameters< QLstmDescriptor >, LayerWithParameters< ReduceDescriptor >, LayerWithParameters< ReshapeDescriptor >, LayerWithParameters< ResizeDescriptor >, LayerWithParameters< ScatterNdDescriptor >, LayerWithParameters< SliceDescriptor >, LayerWithParameters< SoftmaxDescriptor >, LayerWithParameters< SpaceToBatchNdDescriptor >, LayerWithParameters< SpaceToDepthDescriptor >, LayerWithParameters< StackDescriptor >, LayerWithParameters< StandInDescriptor >, LayerWithParameters< StridedSliceDescriptor >, LayerWithParameters< TileDescriptor >, LayerWithParameters< TransposeConvolution2dDescriptor >, LayerWithParameters< TransposeDescriptor >, LayerWithParameters< ViewsDescriptor >, LogicalBinaryLayer, LogSoftmaxLayer, LstmLayer, MapLayer, MaximumLayer, MeanLayer, MemCopyLayer, MemImportLayer, MergeLayer, MinimumLayer, MultiplicationLayer, NormalizationLayer, OutputLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreCompiledLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, QuantizeLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, RsqrtLayer, ShapeLayer, SliceLayer, SoftmaxLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, SubtractionLayer, SwitchLayer, TransposeConvolution2dLayer, TransposeLayer, UnidirectionalSequenceLstmLayer, and UnmapLayer.
GetConstantTensorsByRef() [1/2]
virtual ImmutableConstantTensors GetConstantTensorsByRef () const pure virtual
Implemented in BatchNormalizationLayer, ConstantLayer, Convolution2dLayer, DepthwiseConvolution2dLayer, DetectionPostProcessLayer, FullyConnectedLayer, Layer, LstmLayer, QLstmLayer, QuantizedLstmLayer, TransposeConvolution2dLayer, and UnidirectionalSequenceLstmLayer.
GetConstantTensorsByRef() [2/2]
virtual ConstantTensors GetConstantTensorsByRef () pure virtual
Implemented in Layer.
GetGuid()
virtual LayerGuid GetGuid () const pure virtual
Returns the unique id of the layer.
Implemented in Layer.
GetInputSlot() [1/2]
virtual const IInputSlot & GetInputSlot (unsigned int index) const pure virtual
Get a const input slot handle by slot index.
Implemented in Layer.
Examples
CustomMemoryAllocatorSample.cpp, DynamicSample.cpp, and SimpleSample.cpp.
Referenced by Connect(), armnn::IsLayerSequence(), and SubgraphView::SubgraphView().
GetInputSlot() [2/2]
virtual IInputSlot & GetInputSlot (unsigned int index) pure virtual
Get the input slot handle by slot index.
Implemented in Layer.
GetName()
virtual const char * GetName () const pure virtual
Returns the name of the layer.
Implemented in Layer.
Referenced by Connect(), and SerializerStrategy::ExecuteStrategy().
GetNumInputSlots()
virtual unsigned int GetNumInputSlots () const pure virtual
Returns the number of connectable input slots.
Implemented in Layer.
Referenced by SubgraphView::SubgraphView().
GetNumOutputSlots()
virtual unsigned int GetNumOutputSlots () const pure virtual
Returns the number of connectable output slots.
Implemented in Layer.
Referenced by SubgraphView::GetWorkingCopy(), and SubgraphView::SubgraphView().
GetOutputSlot() [1/2]
virtual const IOutputSlot & GetOutputSlot (unsigned int index) const pure virtual
Get the const output slot handle by slot index.
Implemented in Layer.
Examples
CustomMemoryAllocatorSample.cpp, DynamicSample.cpp, and SimpleSample.cpp.
Referenced by Connect(), SubgraphView::GetWorkingCopy(), armnn::IsLayerSequence(), TosaRefBackend::OptimizeSubgraphView(), and SubgraphView::SubgraphView().
GetOutputSlot() [2/2]
virtual IOutputSlot & GetOutputSlot (unsigned int index) pure virtual
Get the output slot handle by slot index.
Implemented in Layer.
GetParameters()
virtual const BaseDescriptor & GetParameters () const pure virtual
If the layer has a descriptor return it.
The base descriptor can then be cast to the correct descriptor class. If the layer has no associated descriptor a struct of type NullDescriptor will be returned. Note: NullDescriptors can be detected because they return true when the BaseDescriptor IsNull function is invoked.
Implemented in Layer, LayerWithParameters< Parameters >, LayerWithParameters< ActivationDescriptor >, LayerWithParameters< ArgMinMaxDescriptor >, LayerWithParameters< BatchMatMulDescriptor >, LayerWithParameters< BatchNormalizationDescriptor >, LayerWithParameters< BatchToSpaceNdDescriptor >, LayerWithParameters< BroadcastToDescriptor >, LayerWithParameters< ChannelShuffleDescriptor >, LayerWithParameters< ComparisonDescriptor >, LayerWithParameters< Convolution2dDescriptor >, LayerWithParameters< Convolution3dDescriptor >, LayerWithParameters< DepthToSpaceDescriptor >, LayerWithParameters< DepthwiseConvolution2dDescriptor >, LayerWithParameters< DetectionPostProcessDescriptor >, LayerWithParameters< ElementwiseBinaryDescriptor >, LayerWithParameters< ElementwiseUnaryDescriptor >, LayerWithParameters< FakeQuantizationDescriptor >, LayerWithParameters< FillDescriptor >, LayerWithParameters< FullyConnectedDescriptor >, LayerWithParameters< FusedDescriptor >, LayerWithParameters< GatherDescriptor >, LayerWithParameters< InstanceNormalizationDescriptor >, LayerWithParameters< L2NormalizationDescriptor >, LayerWithParameters< LogicalBinaryDescriptor >, LayerWithParameters< LogSoftmaxDescriptor >, LayerWithParameters< LstmDescriptor >, LayerWithParameters< MeanDescriptor >, LayerWithParameters< NormalizationDescriptor >, LayerWithParameters< OriginsDescriptor >, LayerWithParameters< PadDescriptor >, LayerWithParameters< PermuteDescriptor >, LayerWithParameters< Pooling2dDescriptor >, LayerWithParameters< Pooling3dDescriptor >, LayerWithParameters< PreCompiledDescriptor >, LayerWithParameters< QLstmDescriptor >, LayerWithParameters< ReduceDescriptor >, LayerWithParameters< ReshapeDescriptor >, LayerWithParameters< ResizeDescriptor >, LayerWithParameters< ScatterNdDescriptor >, LayerWithParameters< SliceDescriptor >, LayerWithParameters< SoftmaxDescriptor >, LayerWithParameters< SpaceToBatchNdDescriptor >, LayerWithParameters< SpaceToDepthDescriptor >, LayerWithParameters< StackDescriptor >, LayerWithParameters< StandInDescriptor >, LayerWithParameters< StridedSliceDescriptor >, LayerWithParameters< TileDescriptor >, LayerWithParameters< TransposeConvolution2dDescriptor >, LayerWithParameters< TransposeDescriptor >, and LayerWithParameters< ViewsDescriptor >.
GetType()
virtual LayerType GetType () const pure virtual
Returns the armnn::LayerType of this layer.
Implemented in Layer.
Referenced by Connect(), StrategyBase< DefaultStrategy >::ExecuteStrategy(), SerializerStrategy::ExecuteStrategy(), and SubgraphView::GetWorkingCopy().
InferOutputShapes()
virtual std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const pure virtual
Infer the shape of the output(s) based on the provided input shape(s)
Implemented in ArgMinMaxLayer, BatchMatMulLayer, BatchToSpaceNdLayer, BroadcastToLayer, ComparisonLayer, ConcatLayer, ConstantLayer, Convolution2dLayer, Convolution3dLayer, DepthToSpaceLayer, DepthwiseConvolution2dLayer, DetectionPostProcessLayer, ElementwiseBaseLayer, ElementwiseBinaryLayer, ElementwiseUnaryLayer, FullyConnectedLayer, GatherLayer, GatherNdLayer, Layer, LogicalBinaryLayer, LstmLayer, MeanLayer, MergeLayer, PadLayer, PermuteLayer, Pooling2dLayer, Pooling3dLayer, PreluLayer, QLstmLayer, QuantizedLstmLayer, RankLayer, ReduceLayer, ReshapeLayer, ResizeLayer, ReverseV2Layer, ScatterNdLayer, ShapeLayer, SliceLayer, SpaceToBatchNdLayer, SpaceToDepthLayer, SplitterLayer, StackLayer, StandInLayer, StridedSliceLayer, TileLayer, TransposeConvolution2dLayer, TransposeLayer, and UnidirectionalSequenceLstmLayer.
SetBackendId()
virtual void SetBackendId (const BackendId & id) pure virtual
Set the backend of the IConnectableLayer.
By using SetBackendId() we guarantee that the input backend supports that layer (IsLayerSupported returns true for a specific backend). If there is no guarantee the input backend supports that layer use BackendSelectionHint().
Implemented in Layer.
The documentation for this class was generated from the following file:
include/armnn/INetwork.hpp