Arm NN: ScaledInt32Decoder Class Reference
ScaledInt32Decoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
ScaledInt32Decoder (const int32_t *data, const float scale)
ScaledInt32Decoder (const float scale)
float Get () const override
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const bool) override
Public Member Functions inherited from TypedIterator< const int32_t, Decoder< float > >
TypedIterator (const int32_t *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< const int32_t, Decoder< float > >
const int32_t * m_Iterator
const int32_t * m_Start
Detailed Description
Definition at line 307 of file BaseIterator.hpp.
Constructor & Destructor Documentation
ScaledInt32Decoder() [1/2]
ScaledInt32Decoder (const int32_t * data, const float scale) inline
Definition at line 310 of file BaseIterator.hpp.
        : TypedIterator(data), m_Scale(scale) {}
References TypedIterator< const int32_t, Decoder< float > >::TypedIterator().
Referenced by ScaledInt32Decoder().
ScaledInt32Decoder() [2/2]
ScaledInt32Decoder (const float scale) inline
Definition at line 313 of file BaseIterator.hpp.
        : ScaledInt32Decoder(nullptr, scale) {}
References ScaledInt32Decoder().
Member Function Documentation
DecodeTensor()
std::vector< float > DecodeTensor (const TensorShape & tensorShape, const bool) inline override virtual
Implements Decoder< float >.
Definition at line 320 of file BaseIterator.hpp.
    {
        const unsigned int size = tensorShape.GetNumElements();
        std::vector<float> decodedTensor;
        decodedTensor.reserve(size);
        for (uint32_t i = 0; i < size; ++i)
        {
            this->operator[](i);
            decodedTensor.emplace_back(static_cast<float>(*m_Iterator) * m_Scale);
        }
        return decodedTensor;
    }
References TensorShape::GetNumElements(), TypedIterator< const int32_t, Decoder< float > >::m_Iterator, and TypedIterator< const int32_t, Decoder< float > >::operator[]().
Get()
float Get () const inline override virtual
Implements Decoder< float >.
Definition at line 316 of file BaseIterator.hpp.
    {
        return static_cast<float>(*m_Iterator) * m_Scale;
    }
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp