Arm NN: DotNode Class Reference
DotNode Class Reference
#include <DotSerializer.hpp>
Public Member Functions
DotNode (std::ostream &stream, LayerGuid nodeId, const char *label)
~DotNode ()
NodeContent & GetContents ()
DotAttributeSet & GetAttributeSet ()
Public Member Functions inherited from DotBase
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 101 of file DotSerializer.hpp.
Constructor & Destructor Documentation
DotNode()
DotNode (std::ostream & stream, LayerGuid nodeId, const char * label) explicit
Definition at line 179 of file DotSerializer.cpp.
    : DotBase(stream)
{
    std::stringstream ss;
    ss << Indent(4) << nodeId;
    GetStream() << ss.str() << " ";
    m_Contents = std::make_unique<NodeContent>(stream);
    m_Attributes = std::make_unique<DotAttributeSet>(stream);
    if (std::strlen(label) != 0)
    {
        m_Contents->SetName(label);
    }
    else
    {
        m_Contents->SetName("<noname>");
    }
}
References DotBase::DotBase(), and DotBase::GetStream().
~DotNode()
~DotNode ()
Definition at line 200 of file DotSerializer.cpp.
{
    m_Contents.reset(nullptr);
    m_Attributes.reset(nullptr);
    GetStream() << ";" << std::endl;
}
References DotBase::GetStream().
Member Function Documentation
GetAttributeSet()
DotAttributeSet & GetAttributeSet () inline
Definition at line 108 of file DotSerializer.hpp.
{ return *m_Attributes.get(); }
GetContents()
NodeContent & GetContents () inline
Definition at line 107 of file DotSerializer.hpp.
{ return *m_Contents.get(); }
Referenced by Graph::SerializeToDot().
The documentation for this class was generated from the following files:
src/armnnUtils/DotSerializer.hpp
src/armnnUtils/DotSerializer.cpp