Arm NN: ClSliceWorkload Class Reference
ClSliceWorkload Class Reference
#include <ClSliceWorkload.hpp>
Public Member Functions
ClSliceWorkload (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
virtual void Execute () const override
Public Member Functions inherited from ClBaseWorkload< SliceQueueDescriptor >
ClBaseWorkload (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< SliceQueueDescriptor >
BaseWorkload (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const SliceQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< SliceQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< SliceQueueDescriptor >
SliceQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 20 of file ClSliceWorkload.hpp.
Constructor & Destructor Documentation
ClSliceWorkload()
ClSliceWorkload (const SliceQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 33 of file ClSliceWorkload.cpp.
    : ClBaseWorkload<SliceQueueDescriptor>(descriptor, info)
{
    // Report Profiling Details
    ARMNN_REPORT_PROFILING_WORKLOAD_DESC("ClSliceWorkload_Construct",
                                         descriptor.m_Parameters,
                                         info,
                                         this->GetGuid());
    m_Data.ValidateInputsOutputs("ClSliceWorkload", 1, 1);
    arm_compute::ICLTensor& input  = PolymorphicDowncast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
    arm_compute::ICLTensor& output = PolymorphicDowncast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
    arm_compute::Coordinates starts;
    arm_compute::Coordinates ends;
    std::tie(starts, ends) = SetClSliceData(m_Data.m_Parameters.m_Begin, m_Data.m_Parameters.m_Size);
    {
        ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID("ClSliceWorkload_configure");
        m_SliceFunction.configure(clCompileContext, &input, &output, starts, ends);
    }
}
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID, ClBaseWorkload< SliceQueueDescriptor >::ClBaseWorkload(), armnn::info, BaseWorkload< SliceQueueDescriptor >::m_Data, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::PolymorphicDowncast(), and armnn::SetClSliceData().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 60 of file ClSliceWorkload.cpp.
{
    ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID("ClSliceWorkload_Execute");
    RunClFunction(m_SliceFunction, CHECK_LOCATION());
}
References ARMNN_SCOPED_PROFILING_EVENT_CL_NAME_GUID, CHECK_LOCATION, and armnn::RunClFunction().
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClSliceWorkload.hpp
src/backends/cl/workloads/ClSliceWorkload.cpp