Arm NN: OptionalBase Class Reference
OptionalBase Class Reference
OptionalBase is the common functionality between reference and non-reference optional types.
#include <Optional.hpp>
Public Member Functions
OptionalBase () noexcept
bool has_value () const noexcept
operator bool () const noexcept
Conversion to bool, so can be used in if-statements and similar contexts expecting a bool.
Protected Member Functions
OptionalBase (bool hasValue) noexcept
Protected Attributes
bool m_HasValue
Detailed Description
OptionalBase is the common functionality between reference and non-reference optional types.
Definition at line 45 of file Optional.hpp.
Constructor & Destructor Documentation
OptionalBase() [1/2]
OptionalBase () inline noexcept
Definition at line 48 of file Optional.hpp.
        : m_HasValue{false}
    {
    }
References m_HasValue.
OptionalBase() [2/2]
OptionalBase (bool hasValue) inline protected noexcept
Definition at line 67 of file Optional.hpp.
        : m_HasValue{hasValue}
    {
    }
References m_HasValue.
Member Function Documentation
has_value()
bool has_value () const inline noexcept
Definition at line 53 of file Optional.hpp.
    {
        return m_HasValue;
    }
References m_HasValue.
Referenced by ProfilingDetails::AddDetailsToString(), NetworkImpl::AddPrecompiledLayer(), NetworkImpl::AddTransposeConvolution2dLayer(), armnn::ClConvolution2dWorkloadValidate(), armnn::ClConvolution3dWorkloadValidate(), armnn::ClDepthwiseConvolutionWorkloadValidate(), armnn::ClFullyConnectedWorkloadValidate(), armnn::ClTransposeConvolution2dWorkloadValidate(), armnnOnnxParser::CreateConstTensorImpl(), armnn::ExtractJsonObjects(), LayerSupportHandle::IsConvolution2dSupported(), RefLayerSupport::IsConvolution2dSupported(), LayerSupportHandle::IsConvolution3dSupported(), RefLayerSupport::IsConvolution3dSupported(), LayerSupportHandle::IsDepthwiseConvolutionSupported(), RefLayerSupport::IsDepthwiseConvolutionSupported(), LayerSupportHandle::IsDilatedDepthwiseConvolutionSupported(), LayerSupportHandle::IsFullyConnectedSupported(), NeonLayerSupport::IsLayerSupported(), LayerSupportHandle::IsTransposeConvolution2dSupported(), RefLayerSupport::IsTransposeConvolution2dSupported(), armnn::NeonConvolution2dWorkloadValidate(), armnn::NeonConvolution3dWorkloadValidate(), armnn::NeonDepthwiseConvolutionWorkloadValidate(), armnn::NeonFullyConnectedWorkloadValidate(), armnn::NeonTransposeConvolution2dWorkloadValidate(), operator bool(), OptionalReferenceSwitch< std::is_reference< T >::value, T >::operator=(), OptionalReferenceSwitch< true, T >::operator=(), Optional< T >::operator==(), OptionalReferenceSwitch< std::is_reference< T >::value, T >::reset(), OptionalReferenceSwitch< std::is_reference< T >::value, T >::value(), OptionalReferenceSwitch< std::is_reference< T >::value, T >::value(), OptionalReferenceSwitch< true, T >::value(), and OptionalReferenceSwitch< true, T >::value().
operator bool()
operator bool () const inline explicit noexcept
Conversion to bool, so can be used in if-statements and similar contexts expecting a bool.
Note this is explicit so that it doesn't get implicitly converted to a bool in unwanted cases, for example "Optional<TypeA> == Optional<TypeB>" should not compile.
Definition at line 61 of file Optional.hpp.
    {
        return has_value();
    }
References has_value().
Member Data Documentation
m_HasValue
bool m_HasValue protected
Definition at line 72 of file Optional.hpp.
Referenced by has_value(), OptionalReferenceSwitch< true, T >::operator=(), OptionalReferenceSwitch< true, T >::operator=(), OptionalBase(), OptionalBase(), OptionalReferenceSwitch< std::is_reference< T >::value, T >::reset(), and OptionalReferenceSwitch< true, T >::reset().
The documentation for this class was generated from the following file:
include/armnn/Optional.hpp