Arm NN: Event Class Reference
Event Class Reference
Event class records measurements reported by BeginEvent()/EndEvent() and returns measurements when Event::GetMeasurements() is called.
#include <ProfilingEvent.hpp>
Public Types
using InstrumentPtr = std::unique_ptr<Instrument>
using Instruments = std::vector<InstrumentPtr>
Public Member Functions
Event (const std::string &eventName, IProfiler *profiler, Event *parent, const BackendId backendId, std::vector< InstrumentPtr > &&instrument, const Optional< arm::pipe::ProfilingGuid > guid)
Event (const Event &other)=delete
Event (Event &&other) noexcept
Move Constructor.
~Event () noexcept
Destructor.
void Start ()
Start the Event.
void Stop ()
Stop the Event.
const std::vector< Measurement > GetMeasurements () const
Get the recorded measurements calculated between Start() and Stop()
const std::vector< InstrumentPtr > & GetInstruments () const
Get the Instruments used by this Event.
const std::string & GetName () const
Get the name of the event.
const IProfiler * GetProfiler () const
Get the pointer of the profiler associated with this event.
const Event * GetParentEvent () const
Get the pointer of the parent event.
BackendId GetBackendId () const
Get the backend id of the event.
Optional< arm::pipe::ProfilingGuid > GetProfilingGuid () const
Get the associated profiling GUID if the event is a workload.
Event & operator= (const Event &other)=delete
Assignment operator.
Event & operator= (Event &&other) noexcept
Move Assignment operator.
Detailed Description
Event class records measurements reported by BeginEvent()/EndEvent() and returns measurements when Event::GetMeasurements() is called.
Definition at line 27 of file ProfilingEvent.hpp.
Member Typedef Documentation
InstrumentPtr
using InstrumentPtr = std::unique_ptr<Instrument>
Definition at line 30 of file ProfilingEvent.hpp.
Instruments
using Instruments = std::vector<InstrumentPtr>
Definition at line 31 of file ProfilingEvent.hpp.
Constructor & Destructor Documentation
Event() [1/3]
Event (const std::string & eventName, IProfiler * profiler, Event * parent, const BackendId backendId, std::vector< InstrumentPtr > && instrument, const Optional< arm::pipe::ProfilingGuid > guid)
Definition at line 11 of file ProfilingEvent.cpp.
    : m_EventName(eventName)
    , m_Profiler(profiler)
    , m_Parent(parent)
    , m_BackendId(backendId)
    , m_Instruments(std::move(instruments))
    , m_ProfilingGuid(guid)
{
}
References Event().
Referenced by Event(), Event(), Event(), GetParentEvent(), operator=(), and operator=().
Event() [2/3]
Event (const Event & other) delete
References Event(), GetBackendId(), GetInstruments(), GetMeasurements(), GetName(), GetParentEvent(), GetProfiler(), GetProfilingGuid(), Start(), and Stop().
Event() [3/3]
Event (Event && other) noexcept
Move Constructor.
Definition at line 26 of file ProfilingEvent.cpp.
    : m_EventName(std::move(other.m_EventName))
    , m_Profiler(other.m_Profiler)
    , m_Parent(other.m_Parent)
    , m_BackendId(other.m_BackendId)
    , m_Instruments(std::move(other.m_Instruments))
    , m_ProfilingGuid(other.m_ProfilingGuid)
{
}
References Event().
~Event()
~Event () noexcept
Destructor.
Definition at line 36 of file ProfilingEvent.cpp.
{
}
Member Function Documentation
GetBackendId()
BackendId GetBackendId () const
Get the backend id of the event.
Returns
Backend id of the event
Definition at line 89 of file ProfilingEvent.cpp.
{
    return m_BackendId;
}
Referenced by ProfilerImpl::AnalyzeEventSequenceAndWriteResults(), and Event().
GetInstruments()
const std::vector< Event::InstrumentPtr > & GetInstruments () const
Get the Instruments used by this Event.
Returns
Return a reference to the collection of Instruments
Definition at line 69 of file ProfilingEvent.cpp.
{
    return m_Instruments;
}
Referenced by Event(), and armnn::ExtractJsonObjects().
GetMeasurements()
const std::vector< Measurement > GetMeasurements () const
Get the recorded measurements calculated between Start() and Stop()
Returns
Recorded measurements of the event
Definition at line 56 of file ProfilingEvent.cpp.
{
    std::vector<Measurement> measurements;
    for (auto& instrument : m_Instruments)
    {
        for (auto& measurement : instrument->GetMeasurements())
        {
            measurements.emplace_back(std::move(measurement));
        }
    }
    return measurements;
}
Referenced by Event(), armnn::ExtractJsonObjects(), armnn::FindKernelMeasurements(), and armnn::FindMeasurement().
GetName()
const std::string & GetName () const
Get the name of the event.
Returns
Name of the event
Definition at line 74 of file ProfilingEvent.cpp.
{
    return m_EventName;
}
Referenced by ProfilerImpl::AnalyzeEventSequenceAndWriteResults(), Event(), and ProfilerImpl::PopulateParent().
GetParentEvent()
const Event * GetParentEvent () const
Get the pointer of the parent event.
Returns
Pointer of the parent event
Definition at line 84 of file ProfilingEvent.cpp.
{
    return m_Parent;
}
References Event().
Referenced by armnn::CalcLevel(), ProfilerImpl::EndEvent(), Event(), and ProfilerImpl::PopulateDescendants().
GetProfiler()
const IProfiler * GetProfiler () const
Get the pointer of the profiler associated with this event.
Returns
Pointer of the profiler associated with this event
Definition at line 79 of file ProfilingEvent.cpp.
{
    return m_Profiler;
}
Referenced by Event().
GetProfilingGuid()
Optional< arm::pipe::ProfilingGuid > GetProfilingGuid () const
Get the associated profiling GUID if the event is a workload.
Returns
Optional GUID of the event
Definition at line 94 of file ProfilingEvent.cpp.
{
    return m_ProfilingGuid;
}
Referenced by Event(), and armnn::ExtractJsonObjects().
operator=() [1/2]
Event & operator= (const Event & other) delete
Assignment operator.
References Event().
operator=() [2/2]
Event & operator= (Event && other) noexcept
Move Assignment operator.
Definition at line 100 of file ProfilingEvent.cpp.
{
    if (this == &other)
    {
        return *this;
    }
    m_EventName = other.m_EventName;
    m_Profiler = other.m_Profiler;
    m_Parent = other.m_Parent;
    m_BackendId = other.m_BackendId;
    m_ProfilingGuid = other.m_ProfilingGuid;
    other.m_Profiler = nullptr;
    other.m_Parent = nullptr;
    return *this;
}
References Event().
Start()
void Start ()
Start the Event.
Definition at line 40 of file ProfilingEvent.cpp.
{
    for (auto& instrument : m_Instruments)
    {
        instrument->Start();
    }
}
Referenced by Event().
Stop()
void Stop ()
Stop the Event.
Definition at line 48 of file ProfilingEvent.cpp.
{
    for (auto& instrument : m_Instruments)
    {
        instrument->Stop();
    }
}
Referenced by Event().
The documentation for this class was generated from the following files:
src/armnn/ProfilingEvent.hpp
src/armnn/ProfilingEvent.cpp