Arm NN: HtmlFont Class Reference
HtmlFont Class Reference
#include <DotSerializer.hpp>
Public Member Functions
HtmlFont (std::ostream &stream, int fontSize, const char *color, const char *face)
HtmlFont (std::ostream &stream)
~HtmlFont ()
Public Member Functions inherited from DotBase
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 56 of file DotSerializer.hpp.
Constructor & Destructor Documentation
HtmlFont() [1/2]
HtmlFont (std::ostream & stream, int fontSize, const char * color, const char * face) explicit
Definition at line 38 of file DotSerializer.cpp.
    : DotBase(stream)
{
    GetStream() << "<FONT";
    if (fontSize > -1)
    {
        GetStream() << " POINT-SIZE=" << "\"" << fontSize << "\"";
    }
    if (color && std::strlen(color) != 0)
    {
        GetStream() << " COLOR=\"" << color << "\" ";
    }
    if (face && std::strlen(face) != 0)
    {
        GetStream() << " FACE=\"" << face << "\" ";
    }
    GetStream() << ">";
}
References DotBase::DotBase(), and DotBase::GetStream().
Referenced by HtmlFont().
HtmlFont() [2/2]
HtmlFont (std::ostream & stream) explicit
Definition at line 62 of file DotSerializer.cpp.
    : HtmlFont(stream, -1, nullptr, nullptr)
{}
References HtmlFont().
~HtmlFont()
~HtmlFont ()
Definition at line 66 of file DotSerializer.cpp.
{
    GetStream() << "</FONT>";
}
References DotBase::GetStream().
The documentation for this class was generated from the following files:
src/armnnUtils/DotSerializer.hpp
src/armnnUtils/DotSerializer.cpp