Arm NN: TensorShape Class Reference
TensorShape Class Reference
#include <Tensor.hpp>
Public Member Functions
TensorShape ()
Empty (invalid) constructor.
TensorShape (unsigned int numDimensions, bool initDimensionsSpecificity=true)
Constructor for TensorShape.
TensorShape (unsigned int numDimensions, const unsigned int *dimensionSizes)
Constructor for TensorShape.
TensorShape (std::initializer_list< unsigned int > dimensionSizeList)
Constructor for TensorShape.
TensorShape (const TensorShape &other)
Copy Constructor for TensorShape.
TensorShape (unsigned int numDimensions, const unsigned int *dimensionSizes, const bool *dimensionsSpecificity)
Constructor for TensorShape.
TensorShape (std::initializer_list< unsigned int > dimensionSizeList, std::initializer_list< bool > dimensionsSpecificityList)
Constructor for TensorShape.
TensorShape (Dimensionality dimensionality)
Constructor for TensorShape.
TensorShape & operator= (const TensorShape &other)
Assignation function.
unsigned int operator[] (unsigned int i) const
Read only operator.
unsigned int & operator[] (unsigned int i)
Read and write operator.
bool operator== (const TensorShape &other) const
Equality comparison operator.
bool operator!= (const TensorShape &other) const
Inequality comparison operator.
unsigned int GetNumDimensions () const
Function that returns the tensor rank.
unsigned int GetNumElements () const
Function that calculates the tensor elements by multiplying all dimension size which are Specified.
Dimensionality GetDimensionality () const
Function that returns the tensor type.
bool GetDimensionSpecificity (unsigned int i) const
Gets information about if the dimension size has been specified or not.
void SetNumDimensions (unsigned int numDimensions, bool initDimensionsSpecificity=false)
Sets the tensor rank and therefore the Dimensionality is set to Specified if it was not.
void SetDimensionSize (unsigned int i, unsigned int dimensionSize)
Sets the size of the indicated dimension and Specificity for that dimension is set to true.
bool AreAllDimensionsSpecified () const
Checks if there is at least one dimension not specified.
bool IsAtLeastOneDimensionSpecified () const
Checks if there is at least one dimension specified.
Detailed Description
Examples
CustomMemoryAllocatorSample.cpp, DynamicSample.cpp, and SimpleSample.cpp.
Definition at line 20 of file Tensor.hpp.
Constructor & Destructor Documentation
TensorShape() [1/8]
TensorShape ()
Empty (invalid) constructor.
Definition at line 25 of file Tensor.cpp.
 : m_NumDimensions(0), m_Dimensionality(Dimensionality::Specified)
{
}
References armnn::Specified.
Referenced by operator!=(), operator=(), operator==(), TensorShape(), TensorShape(), and TensorShape().
TensorShape() [2/8]
TensorShape (unsigned int numDimensions, bool initDimensionsSpecificity = true) explicit
Constructor for TensorShape.
Parameters
numDimensions - Tensor rank.
initDimensionsSpecificity (optional) - value to initialize the specificity of each dimension size.
Definition at line 30 of file Tensor.cpp.
 : m_NumDimensions(numDimensions), m_Dimensionality(Dimensionality::Specified)
{
    CheckValidNumDimensions(numDimensions);
    std::fill(m_Dimensions.begin(), m_Dimensions.begin() + m_NumDimensions, 0);
    std::fill(m_DimensionsSpecificity.begin(), m_DimensionsSpecificity.begin() + m_NumDimensions,
              initDimensionsSpecificity);
}
References armnn::Specified.
TensorShape() [3/8]
TensorShape (unsigned int numDimensions, const unsigned int * dimensionSizes)
Constructor for TensorShape.
Parameters
numDimensions - Tensor rank.
dimensionSizes - Size of each of dimension.
Definition at line 40 of file Tensor.cpp.
 : m_NumDimensions(numDimensions), m_Dimensionality(Dimensionality::Specified)
{
    CheckValidNumDimensions(numDimensions);
    if (dimensionSizes == nullptr)
    {
        throw InvalidArgumentException("Tensor dimensionSizes must not be NULL");
    }
    std::copy(dimensionSizes, dimensionSizes + numDimensions, m_Dimensions.begin());
    std::fill(m_DimensionsSpecificity.begin(), m_DimensionsSpecificity.begin() + m_NumDimensions, true);
}
References armnn::Specified.
TensorShape() [4/8]
TensorShape (std::initializer_list< unsigned int > dimensionSizeList)
Constructor for TensorShape.
Parameters
dimensionSizeList - Size of each of dimension.
Definition at line 54 of file Tensor.cpp.
 : TensorShape(armnn::numeric_cast<unsigned int>(dimensionSizeList.size()), dimensionSizeList.begin())
{
}
References armnn::numeric_cast(), and TensorShape().
TensorShape() [5/8]
TensorShape (const TensorShape & other)
Copy Constructor for TensorShape.
Parameters
other - TensorShape to copy from.
Definition at line 116 of file Tensor.cpp.
 : m_NumDimensions(other.m_NumDimensions), m_Dimensionality(other.m_Dimensionality)
{
    std::copy(other.m_Dimensions.cbegin(), other.m_Dimensions.cbegin() + other.m_NumDimensions, m_Dimensions.begin());
    std::copy(other.m_DimensionsSpecificity.cbegin(), other.m_DimensionsSpecificity.cbegin() + other.m_NumDimensions,
              m_DimensionsSpecificity.begin());
}
References TensorShape().
TensorShape() [6/8]
TensorShape (unsigned int numDimensions, const unsigned int * dimensionSizes, const bool * dimensionsSpecificity)
Constructor for TensorShape.
Parameters
numDimensions - Tensor rank.
dimensionSizes - Size of each of dimension.
dimensionsSpecificity - Flags to indicate which dimension has its size specified.
Definition at line 59 of file Tensor.cpp.
                       : m_NumDimensions(numDimensions), m_Dimensionality(Dimensionality::Specified)
{
    CheckValidNumDimensions(numDimensions);
    if (dimensionSizes == nullptr)
    {
        throw InvalidArgumentException("Tensor dimensionSizes must not be NULL");
    }
    if (dimensionsSpecificity == nullptr)
    {
        throw InvalidArgumentException("Tensor dimensionsSpecificity must not be NULL");
    }
    std::copy(dimensionSizes, dimensionSizes + numDimensions, m_Dimensions.begin());
    std::copy(dimensionsSpecificity, dimensionsSpecificity + numDimensions, m_DimensionsSpecificity.begin());
}
References armnn::Specified.
TensorShape() [7/8]
TensorShape (std::initializer_list< unsigned int > dimensionSizeList, std::initializer_list< bool > dimensionsSpecificityList)
Constructor for TensorShape.
Parameters
dimensionSizeList - Size of each of dimension.
dimensionsSpecificityList - Flags to indicate which dimension size is specified.
Definition at line 80 of file Tensor.cpp.
{
    auto numDimensions = static_cast<unsigned int>(dimensionSizeList.size());
    if (dimensionsSpecificityList.size() != numDimensions)
    {
        throw InvalidArgumentException("Tensors dimensionSizeList and dimensionsSpecificityList must be same size");
    }
    *this = TensorShape(numDimensions, dimensionSizeList.begin(), dimensionsSpecificityList.begin());
}
References TensorShape().
TensorShape() [8/8]
TensorShape (Dimensionality dimensionality) explicit
Constructor for TensorShape.
Parameters
dimensionality - Parameter to indicate if the Tensor is a Scalar, a Tensor of known dimensionality or a Tensor of unknown dimensionality.
Definition at line 92 of file Tensor.cpp.
: m_Dimensionality(dimensionality)
{
    switch (dimensionality)
    {
        case Dimensionality::Specified:
            throw InvalidArgumentException("Use other constructor to specify the rest of the values, this one is only "
                                           "for tensors that have an unknown number of dimensions or that are scalar");
            break;
        case Dimensionality::NotSpecified:
            m_NumDimensions = 0;
            m_Dimensions = {0};
            m_DimensionsSpecificity = {false};
            break;
        case Dimensionality::Scalar:
            m_NumDimensions = 1;
            m_Dimensions = {1};
            m_DimensionsSpecificity = {true};
            break;
        default:
            throw InvalidArgumentException("Invalid Dimensionality value");
    }
}
References armnn::NotSpecified, armnn::Scalar, and armnn::Specified.
Member Function Documentation
AreAllDimensionsSpecified()
bool AreAllDimensionsSpecified () const
Checks if there is at least one dimension not specified.
AND of all array elements.
Returns
- True when all dimension sizes are specified. False when at least one dimension size is not specified.
Definition at line 241 of file Tensor.cpp.
{
    CheckUnspecifiedNumDimensions();
    bool areAllDimensionsSpecified = true;
    for (unsigned int i = 0; i < m_NumDimensions; ++i)
    {
        if (!m_DimensionsSpecificity[i])
        {
            areAllDimensionsSpecified = false;
            break;
        }
    }
    return areAllDimensionsSpecified;
}
Referenced by ConstantLayer::ValidateTensorShapesFromInputs(), and Layer::VerifyShapeInferenceType().
GetDimensionality()
Dimensionality GetDimensionality () const inline
Function that returns the tensor type.
Returns
- Parameter to indicate if the Tensor is a scalar, a Tensor of known dimensionality or a Tensor of unknown dimensionality
Definition at line 92 of file Tensor.hpp.
{ return m_Dimensionality; }
Referenced by GatherLayer::InferOutputShapes(), GatherNdLayer::InferOutputShapes(), armnn::operator<<(), Layer::ValidateAndCopyShape(), ConstantLayer::ValidateTensorShapesFromInputs(), and Layer::VerifyShapeInferenceType().
GetDimensionSpecificity()
bool GetDimensionSpecificity (unsigned int i) const
Gets information about if the dimension size has been specified or not.
Parameters
i - Dimension index.
Returns
- Flag to indicate if the dimension "i" has a specified size.
Definition at line 211 of file Tensor.cpp.
{
    CheckUnspecifiedNumDimensions();
    CheckDimensionIndex(i);
    return m_DimensionsSpecificity[i];
}
Referenced by armnn::operator<<(), and Layer::ValidateAndCopyShape().
GetNumDimensions()
unsigned int GetNumDimensions () const
Function that returns the tensor rank.
Returns
- Tensor rank.
Definition at line 174 of file Tensor.cpp.
{
    CheckUnspecifiedNumDimensions();
    return m_NumDimensions;
}
Referenced by BroadcastLoop::BroadcastLoop(), ShapesAreBroadcastCompatible::CalcInputSize(), armnnDeserializer::CheckShape(), ClStackWorkload::ClStackWorkload(), armnn::ClStackWorkloadValidate(), armnn::ClUnidirectionalSequenceLstmFloatWorkloadValidate(), armnnUtils::ConvertTensorShapeToString(), armnn::CoordinatesToIndex(), armnn::CopyTensorContentsGeneric(), ClImportTensorHandleFactory::CreateSubTensorHandle(), ClTensorHandleFactory::CreateSubTensorHandle(), ClWorkloadFactory::CreateSubTensorHandle(), NeonTensorHandleFactory::CreateSubTensorHandle(), NeonWorkloadFactory::CreateSubTensorHandle(), armnnUtils::ExpandDims(), armnnUtils::ExpandDimsToRank(), BatchMatMulDescriptor::GetAxesNotMul(), BatchMatMulDescriptor::GetAxesToMul(), armnnUtils::GetNumElementsAfter(), armnnUtils::GetNumElementsBetween(), armnn::GetOffset(), BatchMatMulDescriptor::GetPermuteVec(), GetTosaTensorShape(), armnn::GetUnpaddedTensorStrides(), ArgMinMaxLayer::InferOutputShapes(), BatchMatMulLayer::InferOutputShapes(), ComparisonLayer::InferOutputShapes(), Convolution2dLayer::InferOutputShapes(), Convolution3dLayer::InferOutputShapes(), DepthwiseConvolution2dLayer::InferOutputShapes(), ElementwiseBaseLayer::InferOutputShapes(), ElementwiseBinaryLayer::InferOutputShapes(), GatherLayer::InferOutputShapes(), GatherNdLayer::InferOutputShapes(), LogicalBinaryLayer::InferOutputShapes(), MeanLayer::InferOutputShapes(), PadLayer::InferOutputShapes(), Pooling2dLayer::InferOutputShapes(), Pooling3dLayer::InferOutputShapes(), PreluLayer::InferOutputShapes(), ReduceLayer::InferOutputShapes(), StackLayer::InferOutputShapes(), StridedSliceLayer::InferOutputShapes(), TileLayer::InferOutputShapes(), TransposeConvolution2dLayer::InferOutputShapes(), armnn::LogSoftmax(), armnn::MirrorPad(), NeonStackWorkload::NeonStackWorkload(), armnn::NeonStackWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmFloatWorkloadValidate(), armnn::NeonUnidirectionalSequenceLstmWorkloadValidate(), armnn::Offset(), armnn::operator<<(), armnn::Pad(), armnnUtils::Permuted(), armnnUtils::ReduceDims(), ShapesAreBroadcastCompatible::ShapesAreBroadcastCompatible(), ShapesAreSameRank::ShapesAreSameRank(), armnn::Slice(), armnn::Softmax(), armnnUtils::SqueezeDims(), armnnUtils::TransposeTensorShape(), ArgMinMaxQueueDescriptor::Validate(), StackQueueDescriptor::Validate(), Layer::ValidateAndCopyShape(), and armnnNumpy::WriteToNumpyFile().
GetNumElements()
unsigned int GetNumElements () const
Function that calculates the tensor elements by multiplying all dimension size which are Specified.
Returns
- Total number of elements in the tensor.
Definition at line 181 of file Tensor.cpp.
{
    CheckUnspecifiedNumDimensions();
    if (m_NumDimensions == 0)
    {
        return 0;
    }
    unsigned int count = 1;
    bool atLeastOneDimensionSpecified = false;
    for (unsigned int i = 0; i < m_NumDimensions; ++i)
    {
        if (m_DimensionsSpecificity[i])
        {
            atLeastOneDimensionSpecified = true;
            count *= m_Dimensions[i];
        }
    }
    if (atLeastOneDimensionSpecified)
    {
        return count;
    }
    else
    {
        return 0;
    }
}
Referenced by BooleanDecoder::DecodeTensor(), BooleanDecoderBool::DecodeTensor(), Float16Decoder::DecodeTensor(), Float32Decoder::DecodeTensor(), Int32Decoder::DecodeTensor(), Int32ToInt32tDecoder::DecodeTensor(), Int64Decoder::DecodeTensor(), QASymm8Decoder::DecodeTensor(), QASymmS8Decoder::DecodeTensor(), QSymm16Decoder::DecodeTensor(), QSymm8PerAxisDecoder::DecodeTensor(), QSymmS8Decoder::DecodeTensor(), ScaledInt32Decoder::DecodeTensor(), ScaledInt32PerAxisDecoder::DecodeTensor(), armnn::DepthToSpace(), armnn::Fill(), armnnUtils::FindMinMax(), armnn::TransposeConvolution2dImpl(), and ScatterNdLayer::ValidateTensorShapesFromInputs().
IsAtLeastOneDimensionSpecified()
bool IsAtLeastOneDimensionSpecified () const
Checks if there is at least one dimension specified.
OR of all array elements.
Returns
- True at least one dimension sizes is specified. False when all dimension sizes are not specified.
Definition at line 257 of file Tensor.cpp.
{
    CheckUnspecifiedNumDimensions();
    bool isAtLeastOneDimensionSpecified = false;
    for (unsigned int i = 0; i < m_NumDimensions; ++i)
    {
        if (m_DimensionsSpecificity[i])
        {
            isAtLeastOneDimensionSpecified = true;
            break;
        }
    }
    return isAtLeastOneDimensionSpecified;
}
operator!=()
bool operator!= (const TensorShape & other) const
Inequality comparison operator.
Parameters
other - TensorShape to compare with.
Definition at line 169 of file Tensor.cpp.
{
    return !(*this == other);
}
References TensorShape().
operator=()
TensorShape & operator= (const TensorShape & other)
Assignation function.
Parameters
other - TensorShape to copy from.
Definition at line 124 of file Tensor.cpp.
{
    m_NumDimensions = other.m_NumDimensions;
    m_Dimensionality = other.m_Dimensionality;
    std::copy(other.m_Dimensions.cbegin(), other.m_Dimensions.cbegin() + other.m_NumDimensions, m_Dimensions.begin());
    std::copy(other.m_DimensionsSpecificity.cbegin(), other.m_DimensionsSpecificity.cbegin() + other.m_NumDimensions,
              m_DimensionsSpecificity.begin());
    return *this;
}
References TensorShape().
operator==()
bool operator== (const TensorShape & other) const
Equality comparison operator.
Parameters
other - TensorShape to compare with.
Definition at line 160 of file Tensor.cpp.
{
    return ((m_NumDimensions == other.m_NumDimensions) &&
            (m_Dimensionality == other.m_Dimensionality) &&
             std::equal(m_Dimensions.cbegin(), m_Dimensions.cbegin() + m_NumDimensions, other.m_Dimensions.cbegin()) &&
             std::equal(m_DimensionsSpecificity.cbegin(), m_DimensionsSpecificity.cbegin() + m_NumDimensions,
                        other.m_DimensionsSpecificity.cbegin()));
}
References TensorShape().
operator[]() [1/2]
unsigned int & operator[] (unsigned int i)
Read and write operator.
Parameters
i - Dimension index.
Definition at line 145 of file Tensor.cpp.
{
    if (Dimensionality::Scalar == m_Dimensionality)
    {
        std::stringstream errorMessage;
        errorMessage << "TensorShape with Dimensionality::Scalar must be const to use operator[]";
        throw InvalidArgumentException(errorMessage.str(), CHECK_LOCATION());
    }
    CheckUnspecifiedNumDimensions();
    CheckDimensionIndex(i);
    CheckDimensionSpecified(i);
    return m_Dimensions.at(i);
}
References CHECK_LOCATION, and armnn::Scalar.
operator[]() [2/2]
unsigned int operator[] (unsigned int i) const
Read only operator.
Parameters
i - Dimension index.
Definition at line 135 of file Tensor.cpp.
{
    CheckUnspecifiedNumDimensions();
    CheckDimensionIndex(i);
    CheckDimensionSpecified(i);
    return m_Dimensions.at(i);
}
SetDimensionSize()
void SetDimensionSize (unsigned int i, unsigned int dimensionSize)
Sets the size of the indicated dimension and Specificity for that dimension is set to true.
Parameters
i - Dimension index.
dimensionSize - size of one dimension.
Definition at line 232 of file Tensor.cpp.
{
    CheckScalar();
    CheckDimensionIndex(i);
    m_Dimensions[i] = dimensionSize;
    m_DimensionsSpecificity[i] = true;
}
SetNumDimensions()
void SetNumDimensions (unsigned int numDimensions, bool initDimensionsSpecificity = false)
Sets the tensor rank and therefore the Dimensionality is set to Specified if it was not.
Parameters
numDimensions - Tensor rank.
initDimensionsSpecificity (optional) - value to initialize the specificity of each dimension size.
Definition at line 219 of file Tensor.cpp.
{
    CheckScalar();
    CheckSpecifiedNumDimensions();
    CheckValidNumDimensions(numDimensions);
    m_NumDimensions = numDimensions;
    m_Dimensionality = Dimensionality::Specified;
    std::fill(m_Dimensions.begin(), m_Dimensions.begin() + m_NumDimensions, 0);
    std::fill(m_DimensionsSpecificity.begin(), m_DimensionsSpecificity.begin() + m_NumDimensions,
              initDimensionsSpecificity);
}
References armnn::Specified.
The documentation for this class was generated from the following files:
include/armnn/Tensor.hpp
src/armnn/Tensor.cpp