Arm NN: DotGraph Class Reference
DotGraph Class Reference
#include <DotSerializer.hpp>
Public Member Functions
DotGraph (std::ostream &stream, const char *name)
~DotGraph ()
Public Member Functions inherited from DotBase
DotBase (std::ostream &stream)
std::ostream & GetStream ()
Detailed Description
Definition at line 125 of file DotSerializer.hpp.
Constructor & Destructor Documentation
DotGraph()
DotGraph (std::ostream & stream, const char * name) explicit
Definition at line 224 of file DotSerializer.cpp.
    : DotBase(stream)
{
    GetStream() << "digraph " << name << " {" << std::endl;
}
References DotBase::DotBase(), and DotBase::GetStream().
~DotGraph()
~DotGraph ()
Definition at line 230 of file DotSerializer.cpp.
{
    GetStream() << "}" << std::endl;
}
References DotBase::GetStream().
The documentation for this class was generated from the following files:
src/armnnUtils/DotSerializer.hpp
src/armnnUtils/DotSerializer.cpp