Arm NN: NeonStridedSliceWorkload Class Reference
NeonStridedSliceWorkload Class Reference
#include <NeonStridedSliceWorkload.hpp>
Public Member Functions
NeonStridedSliceWorkload (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual void Execute () const override
Public Member Functions inherited from NeonBaseWorkload< StridedSliceQueueDescriptor >
NeonBaseWorkload (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< StridedSliceQueueDescriptor >
BaseWorkload (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual const std::string & GetName () const override
void PostAllocationConfigure () override
const StridedSliceQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from NeonBaseWorkload< StridedSliceQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< StridedSliceQueueDescriptor >
StridedSliceQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
const std::string m_Name
Detailed Description
Definition at line 24 of file NeonStridedSliceWorkload.hpp.
Constructor & Destructor Documentation
NeonStridedSliceWorkload()
NeonStridedSliceWorkload (const StridedSliceQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 51 of file NeonStridedSliceWorkload.cpp.
        : NeonBaseWorkload<StridedSliceQueueDescriptor>(descriptor, info)
{
    // Report Profiling Details
    ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonStridedSliceWorkload_Construct",
                                         descriptor.m_Parameters,
                                         info,
                                         this->GetGuid());
    m_Data.ValidateInputsOutputs("NeonStridedSliceWorkload", 1, 1);
    arm_compute::ITensor& input = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
    arm_compute::ITensor& output = PolymorphicDowncast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
    arm_compute::Coordinates starts;
    arm_compute::Coordinates ends;
    arm_compute::Coordinates strides;
    std::tie(starts, ends, strides) = SetNeonStridedSliceData(m_Data.m_Parameters.m_Begin,
                                                              m_Data.m_Parameters.m_End,
                                                              m_Data.m_Parameters.m_Stride);
    auto numDimensions       = armnn::numeric_cast<int>(info.m_InputTensorInfos[0].GetNumDimensions());
    int32_t begin_mask       = ConvertMaskToACLFormat(m_Data.m_Parameters.m_BeginMask, numDimensions);
    int32_t end_mask         = ConvertMaskToACLFormat(m_Data.m_Parameters.m_EndMask, numDimensions);
    int32_t shrink_axis_mask = ConvertMaskToACLFormat(m_Data.m_Parameters.m_ShrinkAxisMask, numDimensions);
    arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
    input.info()->set_data_layout(aclDataLayout);
    output.info()->set_data_layout(aclDataLayout);
    auto layer = std::make_unique<arm_compute::NEStridedSlice>();
    layer->configure(&input,
                     &output,
                     starts,
                     ends,
                     strides,
                     begin_mask,
                     end_mask,
                     shrink_axis_mask);
    m_Layer.reset(layer.release());
}
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, armnn::ConvertMaskToACLFormat(), armnn::info, BaseWorkload< StridedSliceQueueDescriptor >::m_Data, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, NeonBaseWorkload< StridedSliceQueueDescriptor >::NeonBaseWorkload(), armnn::numeric_cast(), armnn::PolymorphicDowncast(), and armnn::SetNeonStridedSliceData().
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 96 of file NeonStridedSliceWorkload.cpp.
{
    ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID("NeonStridedSliceWorkload_Execute");
    m_Layer->run();
}
References ARMNN_SCOPED_PROFILING_EVENT_NEON_NAME_GUID.
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonStridedSliceWorkload.hpp
src/backends/neon/workloads/NeonStridedSliceWorkload.cpp