Arm NN: AddBroadcastReshapeLayerImpl Class Reference
AddBroadcastReshapeLayerImpl Class Reference
#include <AddBroadcastReshapeLayer.hpp>
Public Member Functions
void Run (Graph &graph, Layer &layer) const
Run for every ElementwiseBaseLayer. Add Broadcast reshape layer if the inputs shape are different.
Protected Member Functions
AddBroadcastReshapeLayerImpl ()=default
~AddBroadcastReshapeLayerImpl ()=default
Detailed Description
Definition at line 23 of file AddBroadcastReshapeLayer.hpp.
Constructor & Destructor Documentation
AddBroadcastReshapeLayerImpl()
AddBroadcastReshapeLayerImpl () protected default
~AddBroadcastReshapeLayerImpl()
~AddBroadcastReshapeLayerImpl () protected default
Member Function Documentation
Run()
void Run (Graph & graph, Layer & layer) const inline
Run for every ElementwiseBaseLayer. Add Broadcast reshape layer if the inputs shape are different.
Definition at line 27 of file AddBroadcastReshapeLayer.hpp.
    {
        if (std::find(broadcastOps.begin(), broadcastOps.end(), layer.GetType()) != broadcastOps.end())
        {
            layer.GetInputSlot(0).GetConnectedOutputSlot()->IsTensorInfoSet();
            layer.GetInputSlot(1).GetConnectedOutputSlot()->IsTensorInfoSet();
            const TensorInfo& inputInfo0 = layer.GetInputSlot(0).GetConnectedOutputSlot()->GetTensorInfo();
            const TensorInfo& inputInfo1 = layer.GetInputSlot(1).GetConnectedOutputSlot()->GetTensorInfo();
            if (inputInfo0.GetNumDimensions() == inputInfo1.GetNumDimensions())
            {
                return;
            }
            unsigned int reshapeSlot = 1;
            TensorInfo reshapeInfo   = inputInfo1;
            TensorInfo inputInfo     = inputInfo0;
            if (inputInfo0.GetNumDimensions() < inputInfo1.GetNumDimensions())
            {
                reshapeSlot = 0;
                reshapeInfo = inputInfo0;
                inputInfo   = inputInfo1;
            }
            uint32_t numDimensions = inputInfo.GetNumDimensions();
            std::vector<unsigned> reshapedDim;
            for (unsigned int i = 0; i < reshapeInfo.GetNumDimensions(); ++i)
            {
                reshapedDim.push_back(reshapeInfo.GetShape()[i]);
            }
            std::vector<unsigned int> reshapedDimensions(numDimensions, 1);
            std::copy_backward(reshapedDim.begin(), reshapedDim.end(), reshapedDimensions.end());
            reshapeInfo.SetShape(armnn::TensorShape{ numDimensions, reshapedDimensions.data() });
            // If the parent layer is a Constant layer and it is only used once or trying to reshape to 4D
            // we can short circuit by just changing the tensor info rather than adding a reshape layer.
            bool elementWiseMul = false;
            if (layer.GetType() == armnn::LayerType::ElementwiseBinary)
            {
                auto& binaryLayerOp = *PolymorphicDowncast<ElementwiseBinaryLayer*>(&layer);
                elementWiseMul = binaryLayerOp.GetParameters().m_Operation==BinaryOperation::Mul;
            }
            auto parentName = std::string(layer.GetInputSlot(0).GetConnectedOutputSlot()->GetOwningLayer().GetName());
            Layer& parentLayer = layer.GetInputSlot(reshapeSlot).GetConnectedOutputSlot()->GetOwningLayer();
            if ((parentLayer.GetType() == armnn::LayerType::Constant) &&
                ((parentLayer.GetOutputSlot(0).GetNumConnections() == 1) ||
                 (parentName.find("Quantize")!=std::string::npos && elementWiseMul)))
            {
                ConstantLayer& constantLayer = static_cast<ConstantLayer&>(parentLayer);
                constantLayer.m_LayerOutput = std::make_unique<ScopedTensorHandle>(
                    ConstTensor(reshapeInfo, constantLayer.m_LayerOutput.get()->GetConstTensor<void>()));
                constantLayer.GetOutputSlot().SetTensorInfo(reshapeInfo);
            }
            else
            {
                const std::string layerName = "Reshape_for:" + layer.GetNameStr() + "-" + std::to_string(reshapeSlot);
                const ReshapeDescriptor descriptor{ reshapeInfo.GetShape() };
                ReshapeLayer* reshapeLayer =
                    graph.InsertNewLayer<ReshapeLayer>(layer.GetInputSlot(reshapeSlot), descriptor, layerName.c_str());
                reshapeLayer->GetOutputSlot().SetTensorInfo(reshapeInfo);
            }
        }
    }
References armnn::Constant, armnn::ElementwiseBinary, InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), Layer::GetName(), Layer::GetNameStr(), OutputSlot::GetNumConnections(), TensorInfo::GetNumDimensions(), Layer::GetOutputSlot(), OutputSlot::GetOwningLayer(), TensorInfo::GetShape(), OutputSlot::GetTensorInfo(), Layer::GetType(), Graph::InsertNewLayer(), OutputSlot::IsTensorInfoSet(), ConstantLayer::m_LayerOutput, armnn::Mul, armnn::PolymorphicDowncast(), TensorInfo::SetShape(), and OutputSlot::SetTensorInfo().
The documentation for this class was generated from the following file:
src/armnn/optimizations/AddBroadcastReshapeLayer.hpp