Arm NN: IDeserializer Class Reference
IDeserializer Class Reference
#include <IDeserializer.hpp>
Classes
class DeserializerImpl
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent)
Create an input network from binary file contents.
armnn::INetworkPtr CreateNetworkFromBinary (std::istream &binaryContent)
Create an input network from a binary input stream.
BindingPointInfo GetNetworkInputBindingInfo (unsigned int layerId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and layers id.
BindingPointInfo GetNetworkOutputBindingInfo (unsigned int layerId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and layers id.
Static Public Member Functions
static IDeserializer * CreateRaw ()
static IDeserializerPtr Create ()
static void Destroy (IDeserializer *parser)
Detailed Description
Definition at line 27 of file IDeserializer.hpp.
Member Function Documentation
Create()
IDeserializerPtr Create () static
Definition at line 47 of file Deserializer.cpp.
{
    return IDeserializerPtr(CreateRaw(), &IDeserializer::Destroy);
}
References Create(), CreateRaw(), and Destroy().
Referenced by Create().
CreateNetworkFromBinary() [1/2]
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent)
Create an input network from binary file contents.
Definition at line 57 of file Deserializer.cpp.
{
    return pDeserializerImpl->CreateNetworkFromBinary(binaryContent);
}
References CreateNetworkFromBinary().
Referenced by CreateNetworkFromBinary(), and CreateNetworkFromBinary().
CreateNetworkFromBinary() [2/2]
armnn::INetworkPtr CreateNetworkFromBinary (std::istream & binaryContent)
Create an input network from a binary input stream.
Definition at line 62 of file Deserializer.cpp.
{
    return pDeserializerImpl->CreateNetworkFromBinary(binaryContent);
}
References CreateNetworkFromBinary().
CreateRaw()
IDeserializer * CreateRaw () static
Definition at line 42 of file Deserializer.cpp.
{
    return new IDeserializer();
}
References CreateRaw().
Referenced by Create(), and CreateRaw().
Destroy()
void Destroy (IDeserializer * parser) static
Definition at line 52 of file Deserializer.cpp.
{
    delete parser;
}
References Destroy().
Referenced by Create(), and Destroy().
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (unsigned int layerId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and layers id.
Definition at line 67 of file Deserializer.cpp.
{
    return pDeserializerImpl->GetNetworkInputBindingInfo(layerId, name);
}
References GetNetworkInputBindingInfo().
Referenced by GetNetworkInputBindingInfo().
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (unsigned int layerId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and layers id.
Definition at line 72 of file Deserializer.cpp.
{
    return pDeserializerImpl->GetNetworkOutputBindingInfo(layerId, name);
}
References GetNetworkOutputBindingInfo().
Referenced by GetNetworkOutputBindingInfo().
The documentation for this class was generated from the following files:
include/armnnDeserializer/IDeserializer.hpp
src/armnnDeserializer/Deserializer.cpp