Arm NN: armnnOpaqueDelegate Namespace Reference
armnnOpaqueDelegate Namespace Reference
Classes
class ArmnnDelegatePlugin
class ArmnnOpaqueDelegate
ArmNN Opaque Delegate.
class ArmnnSubgraph
ArmnnSubgraph class where parsing the nodes to ArmNN format and creating the ArmNN Graph.
struct DelegateData
Typedefs
using TfLiteOpaqueDelegatePtr = tflite::delegates::TfLiteDelegatePtr
Functions
::armnnDelegate::DelegateOptions TfLiteArmnnDelegateOptionsDefault ()
Forward declaration for functions initializing the ArmNN Delegate.
TfLiteOpaqueDelegate * TfLiteArmnnOpaqueDelegateCreate (armnnDelegate::DelegateOptions options)
void TfLiteArmnnOpaqueDelegateDelete (TfLiteOpaqueDelegate *tfLiteDelegate)
TfLiteStatus DoPrepare (TfLiteOpaqueContext *context, TfLiteOpaqueDelegate *delegate, void *data)
armnnDelegate::DelegateOptions ParseArmNNSettings (const tflite::TFLiteSettings *tflite_settings)
const TfLiteOpaqueDelegatePlugin * GetArmnnDelegatePluginApi ()
In order for the delegate to be loaded by TfLite.
Typedef Documentation
TfLiteOpaqueDelegatePtr
using TfLiteOpaqueDelegatePtr = tflite::delegates::TfLiteDelegatePtr
Definition at line 94 of file armnn_delegate.hpp.
Function Documentation
DoPrepare()
TfLiteStatus DoPrepare (TfLiteOpaqueContext * context, TfLiteOpaqueDelegate * delegate, void * data)
GetArmnnDelegatePluginApi()
const TfLiteOpaqueDelegatePlugin * GetArmnnDelegatePluginApi ()
In order for the delegate to be loaded by TfLite.
ParseArmNNSettings()
armnnDelegate::DelegateOptions ParseArmNNSettings (const tflite::TFLiteSettings * tflite_settings)
Referenced by ArmnnDelegatePlugin::ArmnnDelegatePlugin().
TfLiteArmnnDelegateOptionsDefault()
::armnnDelegate::DelegateOptions TfLiteArmnnDelegateOptionsDefault ()
Forward declaration for functions initializing the ArmNN Delegate.
TfLiteArmnnOpaqueDelegateCreate()
TfLiteOpaqueDelegate * TfLiteArmnnOpaqueDelegateCreate (armnnDelegate::DelegateOptions options)
Referenced by ArmnnDelegatePlugin::Create().
TfLiteArmnnOpaqueDelegateDelete()
void TfLiteArmnnOpaqueDelegateDelete (TfLiteOpaqueDelegate * tfLiteDelegate)
Referenced by ArmnnDelegatePlugin::Create().