Arm NN: ClContextBuilder Struct Reference
ClContextBuilder Struct Reference
#include <ClContextSchema_generated.h>
Public Types
typedef ClContext Table
Public Member Functions
void add_programs (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnn::Program > > > programs)
ClContextBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ClContextBuilder & operator= (const ClContextBuilder &)
flatbuffers::Offset< ClContext > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 38 of file ClContextSchema_generated.h.
Member Typedef Documentation
Table
typedef ClContext Table
Definition at line 39 of file ClContextSchema_generated.h.
Constructor & Destructor Documentation
ClContextBuilder()
ClContextBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 45 of file ClContextSchema_generated.h.
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
References fbb_, and start_.
Referenced by operator=().
Member Function Documentation
add_programs()
void add_programs (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnn::Program > > > programs) inline
Definition at line 42 of file ClContextSchema_generated.h.
{
    fbb_.AddOffset(ClContext::VT_PROGRAMS, programs);
  }
References fbb_.
Referenced by armnn::CreateClContext().
Finish()
flatbuffers::Offset< ClContext > Finish () inline
Definition at line 50 of file ClContextSchema_generated.h.
{
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ClContext>(end);
    return o;
  }
References fbb_, and start_.
Referenced by armnn::CreateClContext().
operator=()
ClContextBuilder & operator= (const ClContextBuilder &)
References ClContextBuilder().
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 40 of file ClContextSchema_generated.h.
Referenced by add_programs(), ClContextBuilder(), and Finish().
start_
flatbuffers::uoffset_t start_
Definition at line 41 of file ClContextSchema_generated.h.
Referenced by ClContextBuilder(), and Finish().
The documentation for this struct was generated from the following file:
src/backends/cl/ClContextSchema_generated.h