Arm NN: OriginsDescriptor Struct Reference
OriginsDescriptor Struct Reference
An OriginsDescriptor for the ConcatLayer.
#include <Descriptors.hpp>
Public Member Functions
OriginsDescriptor ()
OriginsDescriptor (uint32_t numViews, uint32_t numDimensions=4)
OriginsDescriptor (const OriginsDescriptor &other)
OriginsDescriptor (OriginsDescriptor &&other)
~OriginsDescriptor ()
OriginsDescriptor & operator= (OriginsDescriptor rhs)
bool operator== (const OriginsDescriptor &rhs) const
Status SetViewOriginCoord (uint32_t view, uint32_t coord, uint32_t value)
@Brief Set the view origin coordinates.
uint32_t GetNumViews () const
Get the number of views.
uint32_t GetNumDimensions () const
Get the number of dimensions.
const uint32_t * GetViewOrigin (uint32_t idx) const
Return the view origin at the int value idx.
void ReorderOrigins (unsigned int *newOrdering, unsigned int numNewOrdering)
Reorders the viewOrigins in accordance with the indices presented in newOrdering array.
void SetConcatAxis (unsigned int concatAxis)
Set the concatenation axis value.
unsigned int GetConcatAxis () const
Get the concatenation axis value.
Public Member Functions inherited from BaseDescriptor
virtual bool IsNull () const
virtual ~BaseDescriptor ()=default
Friends
void swap (OriginsDescriptor &first, OriginsDescriptor &second)
Swap the ViewsDescriptor values first and second.
Detailed Description
An OriginsDescriptor for the ConcatLayer.
Descriptor to configure the concatenation process. Number of views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc.
Definition at line 201 of file Descriptors.hpp.
Constructor & Destructor Documentation
OriginsDescriptor() [1/4]
OriginsDescriptor ()
Definition at line 82 of file Descriptors.cpp.
: m_ConcatAxis(1)
, m_NumViews(0)
, m_NumDimensions(0)
, m_ViewOrigins(nullptr)
{}
Referenced by operator=(), operator==(), OriginsDescriptor(), OriginsDescriptor(), and swap.
OriginsDescriptor() [2/4]
OriginsDescriptor (uint32_t numViews, uint32_t numDimensions = 4)
Definition at line 89 of file Descriptors.cpp.
: m_ConcatAxis(1)
, m_NumViews(numViews)
, m_NumDimensions(numDimensions)
, m_ViewOrigins(numViews && numDimensions > 0 ? new uint32_t *[numViews]() : nullptr)
{
    for (uint32_t i = 0; m_NumDimensions > 0 && i < m_NumViews; ++i)
    {
        m_ViewOrigins[i] = new uint32_t[m_NumDimensions]();
    }
}
OriginsDescriptor() [3/4]
OriginsDescriptor (const OriginsDescriptor & other)
Definition at line 101 of file Descriptors.cpp.
: m_ConcatAxis(other.m_ConcatAxis)
, m_NumViews(other.m_NumViews)
, m_NumDimensions(other.m_NumDimensions)
, m_ViewOrigins(other.m_NumViews && other.m_NumDimensions > 0 ? new uint32_t *[other.m_NumViews]() : nullptr)
{
    for (uint32_t i = 0; m_NumDimensions > 0 && i < m_NumViews; ++i)
    {
        m_ViewOrigins[i] = new uint32_t[m_NumDimensions]();
        memcpy(m_ViewOrigins[i], other.m_ViewOrigins[i], m_NumDimensions * sizeof(uint32_t));
    }
}
References OriginsDescriptor().
OriginsDescriptor() [4/4]
OriginsDescriptor (OriginsDescriptor && other)
Definition at line 114 of file Descriptors.cpp.
: OriginsDescriptor()
{
    swap(*this, other);
}
References OriginsDescriptor(), and swap.
~OriginsDescriptor()
~OriginsDescriptor ()
Definition at line 120 of file Descriptors.cpp.
{
    for (uint32_t i = 0; m_NumDimensions > 0 && i < m_NumViews; ++i)
    {
        delete[] m_ViewOrigins[i];
    }
    delete[] m_ViewOrigins;
}
Member Function Documentation
GetConcatAxis()
unsigned int GetConcatAxis () const
Get the concatenation axis value.
Definition at line 162 of file Descriptors.cpp.
{
    return m_ConcatAxis;
}
Referenced by ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), ConvertConcatToTosaOperator(), ClLayerSupport::IsConcatSupported(), NeonLayerSupport::IsConcatSupported(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload(), operator==(), and StringifyLayerParameters< OriginsDescriptor >::Serialize().
GetNumDimensions()
uint32_t GetNumDimensions () const
Get the number of dimensions.
Definition at line 192 of file Descriptors.cpp.
{
    return m_NumDimensions;
}
Referenced by ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), ClLayerSupport::IsConcatSupported(), NeonLayerSupport::IsConcatSupported(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload(), operator==(), armnnUtils::ProcessConcatInputTensorInfo(), and StringifyLayerParameters< OriginsDescriptor >::Serialize().
GetNumViews()
uint32_t GetNumViews () const
Get the number of views.
Definition at line 187 of file Descriptors.cpp.
{
    return m_NumViews;
}
Referenced by operator==(), and StringifyLayerParameters< OriginsDescriptor >::Serialize().
GetViewOrigin()
const uint32_t * GetViewOrigin (uint32_t idx) const
Return the view origin at the int value idx.
Definition at line 197 of file Descriptors.cpp.
{
    return m_ViewOrigins ? m_ViewOrigins[idx] : nullptr;
}
Referenced by operator==(), and StringifyLayerParameters< OriginsDescriptor >::Serialize().
operator=()
OriginsDescriptor & operator= (OriginsDescriptor rhs)
Definition at line 129 of file Descriptors.cpp.
{
    swap(*this, rhs);
    return *this;
}
References OriginsDescriptor(), and swap.
operator==()
bool operator== (const OriginsDescriptor & rhs) const
Definition at line 135 of file Descriptors.cpp.
{
    if (GetNumViews()      != rhs.GetNumViews() ||
        GetNumDimensions() != rhs.GetNumDimensions() ||
        GetConcatAxis()    != rhs.GetConcatAxis())
    {
        return false;
    }
    for (unsigned int i = 0u; i < GetNumViews(); ++i)
    {
        for (unsigned int j = 0u; j < GetNumDimensions(); ++j)
        {
            if (GetViewOrigin(i)[j] != rhs.GetViewOrigin(i)[j])
            {
                return false;
            }
        }
    }
    return true;
}
References GetConcatAxis(), GetNumDimensions(), GetNumViews(), GetViewOrigin(), and OriginsDescriptor().
ReorderOrigins()
void ReorderOrigins (unsigned int * newOrdering, unsigned int numNewOrdering)
Reorders the viewOrigins in accordance with the indices presented in newOrdering array.
The number of views must match number of elements in the new ordering array.
Definition at line 204 of file Descriptors.cpp.
{
    ARMNN_THROW_INVALIDARG_MSG_IF_FALSE(m_NumViews == numNewOrdering,
                                        "number of views must match number of elements in the new ordering array");
    std::vector<uint32_t*> viewOrigins(&m_ViewOrigins[0], &m_ViewOrigins[m_NumViews]);
    for (unsigned int i = 0; i < numNewOrdering; ++i)
    {
        m_ViewOrigins[i] = viewOrigins[newOrdering[i]];
    }
}
References ARMNN_THROW_INVALIDARG_MSG_IF_FALSE.
SetConcatAxis()
void SetConcatAxis (unsigned int concatAxis)
Set the concatenation axis value.
Definition at line 158 of file Descriptors.cpp.
{
    m_ConcatAxis = concatAxis;
}
Referenced by ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), armnn::CreateDescriptorForConcatenation(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), and NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload().
SetViewOriginCoord()
Status SetViewOriginCoord (uint32_t view, uint32_t coord, uint32_t value)
@Brief Set the view origin coordinates.
The arguments are: view, dimension, value. If the view is greater than or equal to GetNumViews(), then the view argument is out of range. If the coord is greater than or equal to GetNumDimensions(), then the coord argument is out of range.
Definition at line 167 of file Descriptors.cpp.
{
    if (view >= m_NumViews)
    {
        ARMNN_LOG(error) << "OriginsDescriptor::SetViewOriginCoord: view argument:" << view <<
            " is out of range";
        return Status::Failure;
    }
    if (coord >= m_NumDimensions)
    {
        ARMNN_LOG(error) << "OriginsDescriptor::SetViewOriginCoord: coord argument:" << coord <<
            " is out of range";
        return Status::Failure;
    }
    m_ViewOrigins[view][coord] = value;
    return Status::Success;
}
References ARMNN_LOG, armnn::error, armnn::Failure, and armnn::Success.
Referenced by ClUnidirectionalSequenceLstmFloatWorkload::ClUnidirectionalSequenceLstmFloatWorkload(), armnn::CreateDescriptorForConcatenation(), NeonUnidirectionalSequenceLstmFloatWorkload::NeonUnidirectionalSequenceLstmFloatWorkload(), NeonUnidirectionalSequenceLstmWorkload::NeonUnidirectionalSequenceLstmWorkload(), and armnnUtils::ProcessConcatInputTensorInfo().
Friends And Related Symbol Documentation
swap
void swap (OriginsDescriptor & first, OriginsDescriptor & second) friend
Swap the ViewsDescriptor values first and second.
Definition at line 357 of file Descriptors.cpp.
{
    using std::swap;
    swap(first.m_NumViews, second.m_NumViews);
    swap(first.m_NumDimensions, second.m_NumDimensions);
    swap(first.m_ViewOrigins, second.m_ViewOrigins);
    swap(first.m_ConcatAxis, second.m_ConcatAxis);
}
References OriginsDescriptor(), and armnn::swap().
Referenced by operator=(), and OriginsDescriptor().
The documentation for this struct was generated from the following files:
include/armnn/Descriptors.hpp
src/armnn/Descriptors.cpp