Arm NN: Measurement Struct Reference
Measurement Struct Reference
#include <Instrument.hpp>
Public Types
enum Unit { TIME_NS , TIME_US , TIME_MS }
Public Member Functions
Measurement (const std::string &name, double value, Unit unit)
Measurement (const Measurement &)=default
~Measurement ()=default
Static Public Member Functions
static const char * ToString (Unit unit)
Public Attributes
std::string m_Name
double m_Value
Unit m_Unit
Detailed Description
Definition at line 14 of file Instrument.hpp.
Member Enumeration Documentation
Unit
enum Unit
Enumerator
TIME_NS
TIME_US
TIME_MS
Definition at line 16 of file Instrument.hpp.
    {
        TIME_NS,
        TIME_US,
        TIME_MS,
    };
Constructor & Destructor Documentation
Measurement() [1/2]
Measurement (const std::string & name, double value, Unit unit) inline
Definition at line 34 of file Instrument.hpp.
        : m_Name(name)
        , m_Value(value)
        , m_Unit(unit)
    {}
References m_Name, m_Unit, and m_Value.
Referenced by Measurement().
Measurement() [2/2]
Measurement (const Measurement &) default
References Measurement().
~Measurement()
~Measurement () default
Member Function Documentation
ToString()
const char * ToString (Unit unit) inline static
Definition at line 23 of file Instrument.hpp.
    {
        switch (unit)
        {
            case TIME_NS: return "ns";
            case TIME_US: return "us";
            case TIME_MS: return "ms";
            default:      return "";
        }
    }
References TIME_MS, TIME_NS, and TIME_US.
Referenced by JsonPrinter::PrintUnit().
Member Data Documentation
m_Name
std::string m_Name
Definition at line 42 of file Instrument.hpp.
Referenced by Measurement().
m_Unit
Unit m_Unit
Definition at line 44 of file Instrument.hpp.
Referenced by Measurement().
m_Value
double m_Value
Definition at line 43 of file Instrument.hpp.
Referenced by ProfilerImpl::AnalyzeEventSequenceAndWriteResults(), ProfilerImpl::CalculateProfilingEventStats(), and Measurement().
The documentation for this struct was generated from the following file:
src/armnn/Instrument.hpp