Arm NN: BackendOptions::BackendOption Struct Reference
BackendOptions::BackendOption Struct Reference
#include <BackendOptions.hpp>
Public Member Functions
BackendOption (std::string name, bool value)
BackendOption (std::string name, int value)
BackendOption (std::string name, unsigned int value)
BackendOption (std::string name, float value)
BackendOption (std::string name, std::string value)
BackendOption (std::string name, const char *value)
template<typename DisallowedType>
BackendOption (std::string, DisallowedType)
BackendOption (const BackendOption &other)=default
BackendOption (BackendOption &&other)=default
BackendOption & operator= (const BackendOption &other)=default
BackendOption & operator= (BackendOption &&other)=default
~BackendOption ()=default
std::string GetName () const
Var GetValue () const
Detailed Description
Definition at line 215 of file BackendOptions.hpp.
Constructor & Destructor Documentation
BackendOption() [1/9]
BackendOption (std::string name, bool value) inline
Definition at line 218 of file BackendOptions.hpp.
            : m_Name(name), m_Value(value)
        {}
Referenced by BackendOption(), BackendOption(), operator=(), and operator=().
BackendOption() [2/9]
BackendOption (std::string name, int value) inline
Definition at line 221 of file BackendOptions.hpp.
            : m_Name(name), m_Value(value)
        {}
BackendOption() [3/9]
BackendOption (std::string name, unsigned int value) inline
Definition at line 224 of file BackendOptions.hpp.
                : m_Name(name), m_Value(value)
        {}
BackendOption() [4/9]
BackendOption (std::string name, float value) inline
Definition at line 227 of file BackendOptions.hpp.
            : m_Name(name), m_Value(value)
        {}
BackendOption() [5/9]
BackendOption (std::string name, std::string value) inline
Definition at line 230 of file BackendOptions.hpp.
            : m_Name(name), m_Value(value)
        {}
BackendOption() [6/9]
BackendOption (std::string name, const char * value) inline
Definition at line 233 of file BackendOptions.hpp.
            : m_Name(name), m_Value(value)
        {}
BackendOption() [7/9]
template<typename DisallowedType> BackendOption (std::string , DisallowedType) inline
Definition at line 238 of file BackendOptions.hpp.
            : m_Value(0)
        {
            static_assert(CheckAllowed<DisallowedType>::value, "Type is not allowed for BackendOption.");
            assert(false && "Unreachable code");
        }
BackendOption() [8/9]
BackendOption (const BackendOption & other) default
References BackendOption().
BackendOption() [9/9]
BackendOption (BackendOption && other) default
References BackendOption().
~BackendOption()
~BackendOption () default
Member Function Documentation
GetName()
std::string GetName () const inline
Definition at line 251 of file BackendOptions.hpp.
{ return m_Name; }
Referenced by armnn::HasMatchingCapability(), armnn::ParseOptions(), OptimizerOptions::ToString(), and OptimizerOptionsOpaque::ToString().
GetValue()
Var GetValue () const inline
Definition at line 252 of file BackendOptions.hpp.
{ return m_Value; }
Referenced by armnn::HasMatchingCapability(), armnn::ParseOptions(), OptimizerOptions::ToString(), and OptimizerOptionsOpaque::ToString().
operator=() [1/2]
BackendOption & operator= (BackendOption && other) default
References BackendOption().
operator=() [2/2]
BackendOption & operator= (const BackendOption & other) default
References BackendOption().
The documentation for this struct was generated from the following file:
include/armnn/BackendOptions.hpp