Arm NN: LogicalBinaryDescriptor Struct Reference
LogicalBinaryDescriptor Struct Reference
A LogicalBinaryDescriptor for the LogicalBinaryLayer.
#include <Descriptors.hpp>
Public Member Functions
LogicalBinaryDescriptor ()
LogicalBinaryDescriptor (LogicalBinaryOperation operation)
bool operator== (const LogicalBinaryDescriptor &rhs) const
Public Member Functions inherited from BaseDescriptor
virtual bool IsNull () const
virtual ~BaseDescriptor ()=default
Public Attributes
LogicalBinaryOperation m_Operation
Specifies the logical operation to execute.
Detailed Description
A LogicalBinaryDescriptor for the LogicalBinaryLayer.
Definition at line 1518 of file Descriptors.hpp.
Constructor & Destructor Documentation
LogicalBinaryDescriptor() [1/2]
LogicalBinaryDescriptor () inline
Definition at line 1520 of file Descriptors.hpp.
        : LogicalBinaryDescriptor(LogicalBinaryOperation::LogicalAnd)
    {}
References armnn::LogicalAnd, and LogicalBinaryDescriptor().
Referenced by LogicalBinaryDescriptor(), and operator==().
LogicalBinaryDescriptor() [2/2]
LogicalBinaryDescriptor (LogicalBinaryOperation operation) inline
Definition at line 1524 of file Descriptors.hpp.
        : m_Operation(operation)
    {}
References m_Operation.
Member Function Documentation
operator==()
bool operator== (const LogicalBinaryDescriptor & rhs) const inline
Definition at line 1528 of file Descriptors.hpp.
    {
        return m_Operation == rhs.m_Operation;
    }
References LogicalBinaryDescriptor(), and m_Operation.
Member Data Documentation
m_Operation
LogicalBinaryOperation m_Operation
Specifies the logical operation to execute.
Definition at line 1534 of file Descriptors.hpp.
Referenced by ClLayerSupport::IsLogicalBinarySupported(), NeonLayerSupport::IsLogicalBinarySupported(), LogicalBinaryDescriptor(), and operator==().
The documentation for this struct was generated from the following file:
include/armnn/Descriptors.hpp