Arm NN: FLATBUFFERS_FINAL_CLASS Struct Reference
FLATBUFFERS_FINAL_CLASS Struct Reference
#include <ClContextSchema_generated.h>
Public Types
typedef ClContextBuilder Builder
typedef ProgramBuilder Builder
Public Member Functions
const flatbuffers::Vector< flatbuffers::Offset< armnn::Program > > * programs () const
bool Verify (flatbuffers::Verifier &verifier) const
const flatbuffers::String * name () const
const flatbuffers::Vector< uint8_t > * binary () const
bool Verify (flatbuffers::Verifier &verifier) const
Detailed Description
Definition at line 21 of file ClContextSchema_generated.h.
Member Typedef Documentation
Builder [1/2]
typedef ClContextBuilder Builder
Definition at line 22 of file ClContextSchema_generated.h.
Builder [2/2]
typedef ProgramBuilder Builder
Definition at line 75 of file ClContextSchema_generated.h.
Member Function Documentation
binary()
const flatbuffers::Vector< uint8_t > * binary () const inline
Definition at line 83 of file ClContextSchema_generated.h.
{
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_BINARY);
  }
Referenced by Verify().
name()
const flatbuffers::String * name () const inline
Definition at line 80 of file ClContextSchema_generated.h.
{
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
References VT_NAME.
Referenced by Verify().
programs()
const flatbuffers::Vector< flatbuffers::Offset< armnn::Program > > * programs () const inline
Definition at line 26 of file ClContextSchema_generated.h.
{
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<armnn::Program>> *>(VT_PROGRAMS);
  }
Referenced by Verify().
Verify() [1/2]
bool Verify (flatbuffers::Verifier & verifier) const inline
Definition at line 29 of file ClContextSchema_generated.h.
{
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAMS) &&
           verifier.VerifyVector(programs()) &&
           verifier.VerifyVectorOfTables(programs()) &&
           verifier.EndTable();
  }
References programs().
Verify() [2/2]
bool Verify (flatbuffers::Verifier & verifier) const inline
Definition at line 86 of file ClContextSchema_generated.h.
{
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_BINARY) &&
           verifier.VerifyVector(binary()) &&
           verifier.EndTable();
  }
References binary(), name(), and VT_NAME.
The documentation for this struct was generated from the following file:
src/backends/cl/ClContextSchema_generated.h