Arm NN: QueueDescriptor Struct Reference
QueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T>
const T * GetAdditionalInformation () const
Public Attributes
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 24 of file WorkloadData.hpp.
Constructor & Destructor Documentation
~QueueDescriptor()
virtual ~QueueDescriptor () virtual default
QueueDescriptor() [1/2]
QueueDescriptor () inline protected
Definition at line 55 of file WorkloadData.hpp.
        : m_AdditionalInfoObject(nullptr)
    {}
References m_AdditionalInfoObject.
Referenced by operator=(), and QueueDescriptor().
QueueDescriptor() [2/2]
QueueDescriptor (QueueDescriptor const &) protected default
References QueueDescriptor().
Member Function Documentation
GetAdditionalInformation()
template<typename T> const T * GetAdditionalInformation () const inline
Definition at line 47 of file WorkloadData.hpp.
    {
        return static_cast<T*>(m_AdditionalInfoObject);
    }
References m_AdditionalInfoObject.
Referenced by armnn::ConvertAdditionalInfoToAclActivationLayerInfo().
operator=()
QueueDescriptor & operator= (QueueDescriptor const &) protected default
References QueueDescriptor().
ValidateInputsOutputs()
void ValidateInputsOutputs (const std::string & descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
Definition at line 447 of file WorkloadData.cpp.
{
    ValidateTensors(m_Inputs, numExpectedIn, descName, "input");
    ValidateTensors(m_Outputs, numExpectedOut, descName, "output");
}
References m_Inputs, and m_Outputs.
ValidateTensorNumDimensions()
void ValidateTensorNumDimensions (const TensorInfo & tensor, std::string const & descName, unsigned int numDimensions, std::string const & tensorName) const
Definition at line 398 of file WorkloadData.cpp.
{
    // If we're allowing expanded dimensions then numDimensions becomes the minimum number of Dimensions we can allow.
    // Throw an Exception if the tensors has fewer than numDimensions or if the squeezed dimensions are greater than
    // numDimensions.
    if (m_AllowExpandedDims)
    {
        unsigned int squeezedDims = 0;
        for (unsigned int i = 0; i < tensor.GetNumDimensions(); ++i)
        {
            if (tensor.GetShape()[i] != 1)
            {
                ++squeezedDims;
            }
        }
        if (tensor.GetNumDimensions() < numDimensions || squeezedDims > numDimensions)
        {
            throw InvalidArgumentException(descName + ": Expected " + to_string(numDimensions) + " or less but got " +
                                           to_string(tensor.GetNumDimensions()) + " dimensions for " +
                                           tensorName + " tensor.");
        }
    }
    else
    {
        if (tensor.GetNumDimensions() != numDimensions)
        {
            throw InvalidArgumentException(descName + ": Expected " + to_string(numDimensions) + " but got " +
                                           to_string(tensor.GetNumDimensions()) + " dimensions for " +
                                           tensorName + " tensor.");
        }
    }
}
References TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), and m_AllowExpandedDims.
Referenced by BatchNormalizationQueueDescriptor::Validate(), BatchToSpaceNdQueueDescriptor::Validate(), Convolution2dQueueDescriptor::Validate(), Convolution3dQueueDescriptor::Validate(), DepthToSpaceQueueDescriptor::Validate(), DepthwiseConvolution2dQueueDescriptor::Validate(), DetectionPostProcessQueueDescriptor::Validate(), FakeQuantizationQueueDescriptor::Validate(), FillQueueDescriptor::Validate(), FullyConnectedQueueDescriptor::Validate(), GatherNdQueueDescriptor::Validate(), GatherQueueDescriptor::Validate(), MeanQueueDescriptor::Validate(), PadQueueDescriptor::Validate(), PermuteQueueDescriptor::Validate(), Pooling2dQueueDescriptor::Validate(), Pooling3dQueueDescriptor::Validate(), RankQueueDescriptor::Validate(), ResizeQueueDescriptor::Validate(), SliceQueueDescriptor::Validate(), SpaceToBatchNdQueueDescriptor::Validate(), SpaceToDepthQueueDescriptor::Validate(), TransposeConvolution2dQueueDescriptor::Validate(), TransposeQueueDescriptor::Validate(), and ValidateTensorNumDimNumElem().
ValidateTensorNumDimNumElem()
void ValidateTensorNumDimNumElem (const TensorInfo & tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const & tensorName) const
Definition at line 436 of file WorkloadData.cpp.
{
    const std::string functionName{"ValidateTensorNumDimNumElem"};
    ValidateTensorNumDimensions(tensorInfo, functionName, numDimension, tensorName);
    ValidateTensorNumElements(tensorInfo, functionName, numElements, tensorName);
}
References ValidateTensorNumDimensions().
Referenced by LstmQueueDescriptor::Validate(), QLstmQueueDescriptor::Validate(), QuantizedLstmQueueDescriptor::Validate(), and UnidirectionalSequenceLstmQueueDescriptor::Validate().
Member Data Documentation
m_AdditionalInfoObject
void* m_AdditionalInfoObject
Definition at line 28 of file WorkloadData.hpp.
Referenced by ClWorkloadFactory::CreateWorkload(), GetAdditionalInformation(), QueueDescriptor(), and Layer::SetAdditionalInfo().
m_AllowExpandedDims
bool m_AllowExpandedDims = false
Definition at line 52 of file WorkloadData.hpp.
Referenced by LayerWithParameters< Parameters >::PrepInfoAndDesc(), and ValidateTensorNumDimensions().
m_Inputs
std::vector<ITensorHandle*> m_Inputs
Definition at line 26 of file WorkloadData.hpp.
Referenced by armnn::BatchNormImpl(), ClConcatWorkload::ClConcatWorkload(), Layer::CollectQueueDescriptorInputs(), ClWorkloadFactory::CreateWorkload(), NeonWorkloadFactory::CreateWorkload(), RefWorkloadFactory::CreateWorkload(), LoadedNetwork::EnqueueWorkload(), sdb::GetInputTensorData(), ImportMemGenericWorkload::ImportMemGenericWorkload(), NeonConcatWorkload::NeonConcatWorkload(), armnn::Stack(), SyncMemGenericWorkload::SyncMemGenericWorkload(), ConcatQueueDescriptor::Validate(), MapQueueDescriptor::Validate(), MemCopyQueueDescriptor::Validate(), MemImportQueueDescriptor::Validate(), MemSyncQueueDescriptor::Validate(), UnmapQueueDescriptor::Validate(), and ValidateInputsOutputs().
m_Outputs
std::vector<ITensorHandle*> m_Outputs
Definition at line 27 of file WorkloadData.hpp.
Referenced by Layer::CollectQueueDescriptorOutputs(), ClWorkloadFactory::CreateWorkload(), NeonWorkloadFactory::CreateWorkload(), ClConstantWorkload::Execute(), NeonConstantWorkload::Execute(), sdb::GetOutputTensorData(), ImportMemGenericWorkload::ImportMemGenericWorkload(), ConcatQueueDescriptor::Validate(), MemCopyQueueDescriptor::Validate(), MemImportQueueDescriptor::Validate(), MemSyncQueueDescriptor::Validate(), and ValidateInputsOutputs().
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp