Arm NN: ComparisonDescriptor Struct Reference
ComparisonDescriptor Struct Reference
A ComparisonDescriptor for the ComparisonLayer.
#include <Descriptors.hpp>
Public Member Functions
ComparisonDescriptor ()
ComparisonDescriptor (ComparisonOperation operation)
bool operator== (const ComparisonDescriptor &rhs) const
Public Member Functions inherited from BaseDescriptor
virtual bool IsNull () const
virtual ~BaseDescriptor ()=default
Public Attributes
ComparisonOperation m_Operation
Specifies the comparison operation to execute.
Detailed Description
A ComparisonDescriptor for the ComparisonLayer.
Definition at line 89 of file Descriptors.hpp.
Constructor & Destructor Documentation
ComparisonDescriptor() [1/2]
ComparisonDescriptor () inline
Definition at line 91 of file Descriptors.hpp.
        : ComparisonDescriptor(ComparisonOperation::Equal)
    {}
References ComparisonDescriptor(), and armnn::Equal.
Referenced by ComparisonDescriptor(), and operator==().
ComparisonDescriptor() [2/2]
ComparisonDescriptor (ComparisonOperation operation) inline
Definition at line 95 of file Descriptors.hpp.
        : m_Operation(operation)
    {}
References m_Operation.
Member Function Documentation
operator==()
bool operator== (const ComparisonDescriptor & rhs) const inline
Definition at line 99 of file Descriptors.hpp.
    {
        return m_Operation == rhs.m_Operation;
    }
References ComparisonDescriptor(), and m_Operation.
Member Data Documentation
m_Operation
ComparisonOperation m_Operation
Specifies the comparison operation to execute.
Definition at line 105 of file Descriptors.hpp.
Referenced by ComparisonDescriptor(), armnn::ConvertComparisonOperationToAcl(), operator==(), and StringifyLayerParameters< ComparisonDescriptor >::Serialize().
The documentation for this struct was generated from the following file:
include/armnn/Descriptors.hpp