ArmNN: src/backends/cl/test/ClMemCopyTests.cpp File Reference
ClMemCopyTests.cpp File Reference
#include "ClWorkloadFactoryHelper.hpp"
#include <cl/ClWorkloadFactory.hpp>
#include <aclCommon/test/MemCopyTestImpl.hpp>
#include <reference/RefWorkloadFactory.hpp>
#include <reference/test/RefWorkloadFactoryHelper.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndGpu)
BOOST_AUTO_TEST_CASE (CopyBetweenGpuAndCpu)
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndGpuWithSubtensors)
BOOST_AUTO_TEST_CASE (CopyBetweenGpuAndCpuWithSubtensors)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndGpu)
Definition at line 18 of file ClMemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::RefWorkloadFactory, armnn::ClWorkloadFactory, armnn::DataType::Float32>(false);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (CopyBetweenGpuAndCpu)
Definition at line 25 of file ClMemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::ClWorkloadFactory, armnn::RefWorkloadFactory, armnn::DataType::Float32>(false);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndGpuWithSubtensors)
Definition at line 32 of file ClMemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::RefWorkloadFactory, armnn::ClWorkloadFactory, armnn::DataType::Float32>(true);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (CopyBetweenGpuAndCpuWithSubtensors)
Definition at line 39 of file ClMemCopyTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::ClWorkloadFactory, armnn::RefWorkloadFactory, armnn::DataType::Float32>(true);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }