ArmNN: src/backends/backendsCommon/test/LayerReleaseConstantDataTest.cpp File Reference
LayerReleaseConstantDataTest.cpp File Reference
#include "CommonTestUtils.hpp"
#include <Graph.hpp>
#include <backendsCommon/CpuTensorHandle.hpp>
#include <backendsCommon/WorkloadData.hpp>
#include <boost/cast.hpp>
#include <boost/test/unit_test.hpp>
#include <utility>
Functions
BOOST_AUTO_TEST_CASE (ReleaseBatchNormalizationLayerConstantDataTest)
BOOST_AUTO_TEST_CASE (ReleaseConvolution2dLayerConstantDataTest)
BOOST_AUTO_TEST_CASE (ReleaseDepthwiseConvolution2dLayerConstantDataTest)
BOOST_AUTO_TEST_CASE (ReleaseFullyConnectedLayerConstantDataTest)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (ReleaseBatchNormalizationLayerConstantDataTest)
Definition at line 29 of file LayerReleaseConstantDataTest.cpp.
References Graph::AddLayer(), BOOST_CHECK(), Connect(), armnn::Float32, BatchNormalizationLayer::m_Beta, BatchNormalizationDescriptor::m_Eps, BatchNormalizationLayer::m_Gamma, BatchNormalizationLayer::m_Mean, BatchNormalizationLayer::m_Variance, and Layer::ReleaseConstantData().
 {
     Graph graph;
     // create the layer we're testing
     BatchNormalizationDescriptor layerDesc;
     layerDesc.m_Eps = 0.05f;
     BatchNormalizationLayer* const layer = graph.AddLayer<BatchNormalizationLayer>(layerDesc, "layer");
     armnn::TensorInfo weightInfo({3}, armnn::DataType::Float32);
     layer->m_Mean     = std::make_unique<ScopedCpuTensorHandle>(weightInfo);
     layer->m_Variance = std::make_unique<ScopedCpuTensorHandle>(weightInfo);
     layer->m_Beta     = std::make_unique<ScopedCpuTensorHandle>(weightInfo);
     layer->m_Gamma    = std::make_unique<ScopedCpuTensorHandle>(weightInfo);
     layer->m_Mean->Allocate();
     layer->m_Variance->Allocate();
     layer->m_Beta->Allocate();
     layer->m_Gamma->Allocate();
     // create extra layers
     Layer* const input = graph.AddLayer<InputLayer>(0, "input");
     Layer* const output = graph.AddLayer<OutputLayer>(0, "output");
     // connect up
     armnn::TensorInfo tensorInfo({2, 3, 1, 1}, armnn::DataType::Float32);
     Connect(input, layer, tensorInfo);
     Connect(layer, output, tensorInfo);
     // check the constants that they are not NULL
     BOOST_CHECK(layer->m_Mean != nullptr);
     BOOST_CHECK(layer->m_Variance != nullptr);
     BOOST_CHECK(layer->m_Beta != nullptr);
     BOOST_CHECK(layer->m_Gamma != nullptr);
     // free up the constants..
     layer->ReleaseConstantData();
     // check the constants that they are NULL now
     BOOST_CHECK(layer->m_Mean == nullptr);
     BOOST_CHECK(layer->m_Variance == nullptr);
     BOOST_CHECK(layer->m_Beta == nullptr);
     BOOST_CHECK(layer->m_Gamma == nullptr);
  }
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (ReleaseConvolution2dLayerConstantDataTest)
Definition at line 75 of file LayerReleaseConstantDataTest.cpp.
References Graph::AddLayer(), BOOST_CHECK(), Connect(), armnn::Float32, armnn::GetBiasDataType(), Convolution2dLayer::m_Bias, Convolution2dDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, Convolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, Convolution2dLayer::m_Weight, and Layer::ReleaseConstantData().
  {
      Graph graph;
      // create the layer we're testing
      Convolution2dDescriptor layerDesc;
      layerDesc.m_PadLeft = 3;
      layerDesc.m_PadRight = 3;
      layerDesc.m_PadTop = 1;
      layerDesc.m_PadBottom = 1;
      layerDesc.m_StrideX = 2;
      layerDesc.m_StrideY = 4;
      layerDesc.m_BiasEnabled = true;
      Convolution2dLayer* const layer = graph.AddLayer<Convolution2dLayer>(layerDesc, "layer");
      layer->m_Weight = std::make_unique<ScopedCpuTensorHandle>(TensorInfo({2, 3, 5, 3},
                                                                           armnn::DataType::Float32));
      layer->m_Bias   = std::make_unique<ScopedCpuTensorHandle>
              (TensorInfo({2}, GetBiasDataType(armnn::DataType::Float32)));
      layer->m_Weight->Allocate();
      layer->m_Bias->Allocate();
      // create extra layers
      Layer* const input = graph.AddLayer<InputLayer>(0, "input");
      Layer* const output = graph.AddLayer<OutputLayer>(0, "output");
      // connect up
      Connect(input, layer, TensorInfo({2, 3, 8, 16}, armnn::DataType::Float32));
      Connect(layer, output, TensorInfo({2, 2, 2, 10}, armnn::DataType::Float32));
      // check the constants that they are not NULL
      BOOST_CHECK(layer->m_Weight != nullptr);
      BOOST_CHECK(layer->m_Bias != nullptr);
      // free up the constants..
      layer->ReleaseConstantData();
      // check the constants that they are NULL now
      BOOST_CHECK(layer->m_Weight == nullptr);
      BOOST_CHECK(layer->m_Bias == nullptr);
 }
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (ReleaseDepthwiseConvolution2dLayerConstantDataTest)
Definition at line 119 of file LayerReleaseConstantDataTest.cpp.
References Graph::AddLayer(), BOOST_CHECK(), Connect(), armnn::Float32, DepthwiseConvolution2dLayer::m_Bias, DepthwiseConvolution2dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideY, DepthwiseConvolution2dLayer::m_Weight, and Layer::ReleaseConstantData().
 {
     Graph graph;
     // create the layer we're testing
     DepthwiseConvolution2dDescriptor layerDesc;
     layerDesc.m_PadLeft         = 3;
     layerDesc.m_PadRight        = 3;
     layerDesc.m_PadTop          = 1;
     layerDesc.m_PadBottom       = 1;
     layerDesc.m_StrideX         = 2;
     layerDesc.m_StrideY         = 4;
     layerDesc.m_BiasEnabled     = true;
     DepthwiseConvolution2dLayer* const layer = graph.AddLayer<DepthwiseConvolution2dLayer>(layerDesc, "layer");
     layer->m_Weight = std::make_unique<ScopedCpuTensorHandle>(TensorInfo({3, 3, 5, 3}, DataType::Float32));
     layer->m_Bias   = std::make_unique<ScopedCpuTensorHandle>(TensorInfo({9}, DataType::Float32));
     layer->m_Weight->Allocate();
     layer->m_Bias->Allocate();
     // create extra layers
     Layer* const input = graph.AddLayer<InputLayer>(0, "input");
     Layer* const output = graph.AddLayer<OutputLayer>(0, "output");
     // connect up
     Connect(input, layer, TensorInfo({2, 3, 8, 16}, armnn::DataType::Float32));
     Connect(layer, output, TensorInfo({2, 9, 2, 10}, armnn::DataType::Float32));
     // check the constants that they are not NULL
     BOOST_CHECK(layer->m_Weight != nullptr);
     BOOST_CHECK(layer->m_Bias != nullptr);
     // free up the constants..
     layer->ReleaseConstantData();
     // check the constants that they are NULL now
     BOOST_CHECK(layer->m_Weight == nullptr);
     BOOST_CHECK(layer->m_Bias == nullptr);
 }
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (ReleaseFullyConnectedLayerConstantDataTest)
Definition at line 160 of file LayerReleaseConstantDataTest.cpp.
References Graph::AddLayer(), BOOST_AUTO_TEST_SUITE_END(), BOOST_CHECK(), Connect(), armnn::GetBiasDataType(), FullyConnectedLayer::m_Bias, FullyConnectedDescriptor::m_BiasEnabled, FullyConnectedDescriptor::m_TransposeWeightMatrix, FullyConnectedLayer::m_Weight, armnn::QAsymmU8, and Layer::ReleaseConstantData().
 {
     Graph graph;
     // create the layer we're testing
     FullyConnectedDescriptor layerDesc;
     layerDesc.m_BiasEnabled = true;
     layerDesc.m_TransposeWeightMatrix = true;
     FullyConnectedLayer* const layer = graph.AddLayer<FullyConnectedLayer>(layerDesc, "layer");
     float inputsQScale = 1.0f;
     float outputQScale = 2.0f;
     layer->m_Weight = std::make_unique<ScopedCpuTensorHandle>(TensorInfo({7, 20},
                                                           DataType::QAsymmU8, inputsQScale, 0));
     layer->m_Bias   = std::make_unique<ScopedCpuTensorHandle>(TensorInfo({7},
                                                           GetBiasDataType(DataType::QAsymmU8), inputsQScale));
     layer->m_Weight->Allocate();
     layer->m_Bias->Allocate();
     // create extra layers
     Layer* const input = graph.AddLayer<InputLayer>(0, "input");
     Layer* const output = graph.AddLayer<OutputLayer>(0, "output");
     // connect up
     Connect(input, layer, TensorInfo({3, 1, 4, 5}, DataType::QAsymmU8, inputsQScale));
     Connect(layer, output, TensorInfo({3, 7}, DataType::QAsymmU8, outputQScale));
     // check the constants that they are not NULL
     BOOST_CHECK(layer->m_Weight != nullptr);
     BOOST_CHECK(layer->m_Bias != nullptr);
     // free up the constants..
     layer->ReleaseConstantData();
     // check the constants that they are NULL now
     BOOST_CHECK(layer->m_Weight == nullptr);
     BOOST_CHECK(layer->m_Bias == nullptr);
 }