ArmNN: src/armnn/test/UnitTests.cpp File Reference
UnitTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "UnitTests.hpp"
#include <armnn/Logging.hpp>
#include <boost/algorithm/string.hpp>
Macros
#define BOOST_TEST_MODULE UnitTests
Functions
BOOST_GLOBAL_FIXTURE (ConfigureLoggingFixture)
BOOST_AUTO_TEST_CASE (LoggerTest)
Macro Definition Documentation
BOOST_TEST_MODULE
#define BOOST_TEST_MODULE UnitTests
Definition at line 5 of file UnitTests.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (LoggerTest)
Definition at line 68 of file UnitTests.cpp.
References ARMNN_LOG, BOOST_AUTO_TEST_SUITE_END(), BOOST_CHECK(), armnn::debug, armnn::error, armnn::fatal, armnn::info, armnn::SetAllLoggingSinks(), armnn::SetLogFilter(), armnn::trace, and armnn::warning.
 {
     std::stringstream ss;
     {
         struct StreamRedirector
         {
         public:
             StreamRedirector(std::ostream& stream, std::streambuf* newStreamBuffer)
                 : m_Stream(stream)
                 , m_BackupBuffer(m_Stream.rdbuf(newStreamBuffer))
             {}
             ~StreamRedirector() { m_Stream.rdbuf(m_BackupBuffer); }
         private:
             std::ostream& m_Stream;
             std::streambuf* m_BackupBuffer;
         };
         StreamRedirector redirect(std::cout, ss.rdbuf());
         using namespace armnn;
         SetLogFilter(LogSeverity::Trace);
         SetAllLoggingSinks(true, false, false);
         ARMNN_LOG(trace) << "My trace message; " << -2;
         ARMNN_LOG(debug) << "My debug message; " << -1;
         ARMNN_LOG(info) << "My info message; " << 0;
         ARMNN_LOG(warning) << "My warning message; "  << 1;
         ARMNN_LOG(error) << "My error message; " << 2;
         ARMNN_LOG(fatal) << "My fatal message; "  << 3;
         SetLogFilter(LogSeverity::Fatal);
     }
     BOOST_CHECK(boost::contains(ss.str(), "Trace: My trace message; -2"));
     BOOST_CHECK(boost::contains(ss.str(), "Debug: My debug message; -1"));
     BOOST_CHECK(boost::contains(ss.str(), "Info: My info message; 0"));
     BOOST_CHECK(boost::contains(ss.str(), "Warning: My warning message; 1"));
     BOOST_CHECK(boost::contains(ss.str(), "Error: My error message; 2"));
     BOOST_CHECK(boost::contains(ss.str(), "Fatal: My fatal message; 3"));
 }
BOOST_GLOBAL_FIXTURE()
BOOST_GLOBAL_FIXTURE (ConfigureLoggingFixture)
Referenced by BOOST_AUTO_TEST_CASE().