ArmNN: CommandHandlerFunctor Class Reference
CommandHandlerFunctor Class Reference abstract
#include <CommandHandlerFunctor.hpp>
Public Member Functions
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
virtual void operator() (const Packet &packet)=0
virtual ~CommandHandlerFunctor ()
Detailed Description
Definition at line 20 of file CommandHandlerFunctor.hpp.
Constructor & Destructor Documentation
CommandHandlerFunctor()
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version) inline
Definition at line 23 of file CommandHandlerFunctor.hpp.
References CommandHandlerFunctor::GetFamilyId(), CommandHandlerFunctor::GetPacketId(), CommandHandlerFunctor::GetVersion(), and CommandHandlerFunctor::operator()().
         : m_FamilyId(familyId),
           m_PacketId(packetId)
         , m_Version(version)
     {}
~CommandHandlerFunctor()
virtual ~CommandHandlerFunctor () inline virtual
Definition at line 35 of file CommandHandlerFunctor.hpp.
 {}
Member Function Documentation
GetFamilyId()
uint32_t GetFamilyId () const
Definition at line 14 of file CommandHandlerFunctor.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandlerFunctor::CommandHandlerFunctor(), and CommandHandlerRegistry::RegisterFunctor().
 {
     return m_FamilyId;
 }
GetPacketId()
uint32_t GetPacketId () const
Definition at line 19 of file CommandHandlerFunctor.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandlerFunctor::CommandHandlerFunctor(), and CommandHandlerRegistry::RegisterFunctor().
 {
     return m_PacketId;
 }
GetVersion()
uint32_t GetVersion () const
Definition at line 24 of file CommandHandlerFunctor.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandlerFunctor::CommandHandlerFunctor(), and CommandHandlerRegistry::RegisterFunctor().
 {
     return m_Version;
 }
operator()()
virtual void operator() (const Packet & packet) pure virtual
Implemented in TestFunctorA, PeriodicCounterSelectionCommandHandler, PeriodicCounterCaptureCommandHandler, StreamMetadataCommandHandler, DirectoryCaptureCommandHandler, TimelineCaptureCommandHandler, ConnectionAcknowledgedCommandHandler, RequestCounterDirectoryCommandHandler, PeriodicCounterSelectionResponseHandler, TimelineDirectoryCaptureCommandHandler, and PerJobCounterSelectionCommandHandler.
Referenced by CommandHandlerFunctor::CommandHandlerFunctor().
The documentation for this class was generated from the following files:
src/profiling/CommandHandlerFunctor.hpp
src/profiling/CommandHandlerFunctor.cpp