ArmNN: Version Class Reference
Version Class Reference
#include <EncodeVersion.hpp>
Public Member Functions
Version (uint32_t encodedValue)
Version (uint32_t major, uint32_t minor, uint32_t patch)
uint32_t GetEncodedValue ()
uint32_t GetMajor ()
uint32_t GetMinor ()
uint32_t GetPatch ()
bool operator== (const Version &other) const
std::string ToString () const
Detailed Description
Definition at line 29 of file EncodeVersion.hpp.
Constructor & Destructor Documentation
Version() [1/2]
Version (uint32_t encodedValue) inline
Definition at line 32 of file EncodeVersion.hpp.
     {
         m_Major = (encodedValue >> 22) & 1023;
         m_Minor = (encodedValue >> 12) & 1023;
         m_Patch = encodedValue & 4095;
     }
Version() [2/2]
Version (uint32_t major, uint32_t minor, uint32_t patch) inline
Definition at line 39 of file EncodeVersion.hpp.
                                                             :
         m_Major(major),
         m_Minor(minor),
         m_Patch(patch)
     {}
Member Function Documentation
GetEncodedValue()
uint32_t GetEncodedValue () inline
Definition at line 45 of file EncodeVersion.hpp.
References armnn::profiling::EncodeVersion().
Referenced by BOOST_AUTO_TEST_CASE(), main(), CommandHandler::Stop(), GatordMockService::WaitCommand(), and FileOnlyProfilingConnection::WritePacket().
     {
         return EncodeVersion(m_Major, m_Minor, m_Patch);
     }
GetMajor()
uint32_t GetMajor () inline
Definition at line 50 of file EncodeVersion.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_Major; }
GetMinor()
uint32_t GetMinor () inline
Definition at line 51 of file EncodeVersion.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_Minor; }
GetPatch()
uint32_t GetPatch () inline
Definition at line 52 of file EncodeVersion.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_Patch; }
operator==()
bool operator== (const Version & other) const inline
Definition at line 54 of file EncodeVersion.hpp.
     {
         return m_Major == other.m_Major && m_Minor == other.m_Minor && m_Patch == other.m_Patch;
     }
ToString()
std::string ToString () const inline
Definition at line 59 of file EncodeVersion.hpp.
Referenced by armnn::profiling::operator<<().
     {
         constexpr char separator = '.';
         std::stringstream stringStream;
         stringStream << m_Major << separator << m_Minor << separator << m_Patch;
         return stringStream.str();
     }
The documentation for this class was generated from the following file:
src/profiling/EncodeVersion.hpp