ArmNN: WorkloadFactoryBase Class Reference
WorkloadFactoryBase Class Reference
#include <WorkloadFactoryBase.hpp>
Public Member Functions
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &, TensorShape const &, unsigned int const *) const override
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &, const bool) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &, DataLayout, const bool) const override
std::unique_ptr< IWorkload > CreateAbs (const AbsQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMerge (const MergeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateRsqrt (const RsqrtQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSwitch (const SwitchQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor &, const WorkloadInfo &) const override
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual const BackendId & GetBackendId () const =0
virtual std::unique_ptr< IWorkload > CreateEqual (const EqualQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateGreater (const GreaterQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateMerger (const MergerQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateResizeBilinear (const ResizeBilinearQueueDescriptor &descriptor, const WorkloadInfo &info) const
Additional Inherited Members
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
Detailed Description
Definition at line 13 of file WorkloadFactoryBase.hpp.
Member Function Documentation
CreateAbs()
std::unique_ptr<IWorkload> CreateAbs (const AbsQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 37 of file WorkloadFactoryBase.hpp.
Referenced by WorkloadFactoryBase::CreateElementwiseUnary().
     { return nullptr; }
CreateActivation()
std::unique_ptr<IWorkload> CreateActivation (const ActivationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 41 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateAddition()
std::unique_ptr<IWorkload> CreateAddition (const AdditionQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 45 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateArgMinMax()
std::unique_ptr<IWorkload> CreateArgMinMax (const ArgMinMaxQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 49 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateBatchNormalization()
std::unique_ptr<IWorkload> CreateBatchNormalization (const BatchNormalizationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 53 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateBatchToSpaceNd()
std::unique_ptr<IWorkload> CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 57 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateComparison()
std::unique_ptr<IWorkload> CreateComparison (const ComparisonQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 61 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateConcat()
std::unique_ptr<IWorkload> CreateConcat (const ConcatQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 65 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateConstant()
std::unique_ptr<IWorkload> CreateConstant (const ConstantQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 69 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateConvertFp16ToFp32()
std::unique_ptr<IWorkload> CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 73 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateConvertFp32ToFp16()
std::unique_ptr<IWorkload> CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 77 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateConvolution2d()
std::unique_ptr<IWorkload> CreateConvolution2d (const Convolution2dQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 81 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateDebug()
std::unique_ptr<IWorkload> CreateDebug (const DebugQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 85 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateDepthToSpace()
std::unique_ptr<IWorkload> CreateDepthToSpace (const DepthToSpaceQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 89 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateDepthwiseConvolution2d()
std::unique_ptr<IWorkload> CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 93 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateDequantize()
std::unique_ptr<IWorkload> CreateDequantize (const DequantizeQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 97 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateDetectionPostProcess()
std::unique_ptr<IWorkload> CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 101 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateDivision()
std::unique_ptr<IWorkload> CreateDivision (const DivisionQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 105 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateElementwiseUnary()
std::unique_ptr<IWorkload> CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & info) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 109 of file WorkloadFactoryBase.hpp.
References armnn::Abs, WorkloadFactoryBase::CreateAbs(), WorkloadFactoryBase::CreateRsqrt(), ElementwiseUnaryDescriptor::m_Operation, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::Rsqrt.
     {
         if (descriptor.m_Parameters.m_Operation == UnaryOperation::Abs)
         {
             AbsQueueDescriptor absDescriptor;
             return CreateAbs(absDescriptor, info);
         }
         else if (descriptor.m_Parameters.m_Operation == UnaryOperation::Rsqrt)
         {
             RsqrtQueueDescriptor rsqrtDescriptor;
             return CreateRsqrt(rsqrtDescriptor, info);
         }
         return nullptr;
     }
CreateFakeQuantization()
std::unique_ptr<IWorkload> CreateFakeQuantization (const FakeQuantizationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Definition at line 125 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateFloor()
std::unique_ptr<IWorkload> CreateFloor (const FloorQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 129 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateFullyConnected()
std::unique_ptr<IWorkload> CreateFullyConnected (const FullyConnectedQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 133 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateGather()
std::unique_ptr<IWorkload> CreateGather (const GatherQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 137 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateInput()
std::unique_ptr<IWorkload> CreateInput (const InputQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Implements IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 24 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateInstanceNormalization()
std::unique_ptr<IWorkload> CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 141 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateL2Normalization()
std::unique_ptr<IWorkload> CreateL2Normalization (const L2NormalizationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 145 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateLogSoftmax()
std::unique_ptr<IWorkload> CreateLogSoftmax (const LogSoftmaxQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Definition at line 149 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateLstm()
std::unique_ptr<IWorkload> CreateLstm (const LstmQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 153 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMaximum()
std::unique_ptr<IWorkload> CreateMaximum (const MaximumQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 157 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMean()
std::unique_ptr<IWorkload> CreateMean (const MeanQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 161 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMemCopy()
std::unique_ptr<IWorkload> CreateMemCopy (const MemCopyQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 165 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMemImport()
std::unique_ptr<IWorkload> CreateMemImport (const MemImportQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 169 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMerge()
std::unique_ptr<IWorkload> CreateMerge (const MergeQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Definition at line 173 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMinimum()
std::unique_ptr<IWorkload> CreateMinimum (const MinimumQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 177 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateMultiplication()
std::unique_ptr<IWorkload> CreateMultiplication (const MultiplicationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 181 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateNormalization()
std::unique_ptr<IWorkload> CreateNormalization (const NormalizationQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 185 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateOutput()
std::unique_ptr<IWorkload> CreateOutput (const OutputQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 189 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreatePad()
std::unique_ptr<IWorkload> CreatePad (const PadQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 193 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreatePermute()
std::unique_ptr<IWorkload> CreatePermute (const PermuteQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 197 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreatePooling2d()
std::unique_ptr<IWorkload> CreatePooling2d (const Pooling2dQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 201 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreatePreCompiled()
std::unique_ptr<IWorkload> CreatePreCompiled (const PreCompiledQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 205 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreatePrelu()
std::unique_ptr<IWorkload> CreatePrelu (const PreluQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 209 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateQuantize()
std::unique_ptr<IWorkload> CreateQuantize (const QuantizeQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 213 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateQuantizedLstm()
std::unique_ptr<IWorkload> CreateQuantizedLstm (const QuantizedLstmQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 217 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateReshape()
std::unique_ptr<IWorkload> CreateReshape (const ReshapeQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 221 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateResize()
std::unique_ptr<IWorkload> CreateResize (const ResizeQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 225 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateRsqrt()
std::unique_ptr<IWorkload> CreateRsqrt (const RsqrtQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 229 of file WorkloadFactoryBase.hpp.
Referenced by WorkloadFactoryBase::CreateElementwiseUnary().
     { return nullptr; }
CreateSlice()
std::unique_ptr<IWorkload> CreateSlice (const SliceQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 233 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateSoftmax()
std::unique_ptr<IWorkload> CreateSoftmax (const SoftmaxQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 237 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateSpaceToBatchNd()
std::unique_ptr<IWorkload> CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 241 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateSpaceToDepth()
std::unique_ptr<IWorkload> CreateSpaceToDepth (const SpaceToDepthQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 245 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateSplitter()
std::unique_ptr<IWorkload> CreateSplitter (const SplitterQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 253 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateStack()
std::unique_ptr<IWorkload> CreateStack (const StackQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 257 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateStridedSlice()
std::unique_ptr<IWorkload> CreateStridedSlice (const StridedSliceQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 261 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateSubTensorHandle()
std::unique_ptr<ITensorHandle> CreateSubTensorHandle (ITensorHandle & , TensorShape const & , unsigned int const *) const inline override virtual
Implements IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 19 of file WorkloadFactoryBase.hpp.
     { return nullptr; };
CreateSubtraction()
std::unique_ptr<IWorkload> CreateSubtraction (const SubtractionQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 249 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateSwitch()
std::unique_ptr<IWorkload> CreateSwitch (const SwitchQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Definition at line 265 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateTensorHandle() [1/2]
std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & , const bool) const inline override virtual
Implements IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 28 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateTensorHandle() [2/2]
std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & , DataLayout , const bool) const inline override virtual
Implements IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 32 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateTranspose()
std::unique_ptr<IWorkload> CreateTranspose (const TransposeQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 269 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
CreateTransposeConvolution2d()
std::unique_ptr<IWorkload> CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor & , const WorkloadInfo &) const inline override virtual
Reimplemented from IWorkloadFactory.
Reimplemented in NeonWorkloadFactory, and ClWorkloadFactory.
Definition at line 273 of file WorkloadFactoryBase.hpp.
     { return nullptr; }
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Implements IWorkloadFactory.
Reimplemented in ClWorkloadFactory, and NeonWorkloadFactory.
Definition at line 16 of file WorkloadFactoryBase.hpp.
     { return false; };
The documentation for this class was generated from the following file:
src/backends/backendsCommon/WorkloadFactoryBase.hpp