ArmNN: RefConvolution2dWorkload Class Reference
RefConvolution2dWorkload Class Reference
#include <RefConvolution2dWorkload.hpp>
Public Member Functions
RefConvolution2dWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< Convolution2dQueueDescriptor >
BaseWorkload (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const Convolution2dQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< Convolution2dQueueDescriptor >
const Convolution2dQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 16 of file RefConvolution2dWorkload.hpp.
Constructor & Destructor Documentation
RefConvolution2dWorkload()
RefConvolution2dWorkload (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) explicit
Definition at line 15 of file RefConvolution2dWorkload.cpp.
References TensorInfo::GetShape(), Convolution2dQueueDescriptor::m_Bias, Convolution2dDescriptor::m_BiasEnabled, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and Convolution2dQueueDescriptor::m_Weight.
         : BaseWorkload<Convolution2dQueueDescriptor>(descriptor, info)
 {
     m_Weight = std::make_unique<ScopedCpuTensorHandle>(*(descriptor.m_Weight));
     const TensorInfo& rFilterInfo = m_Weight->GetTensorInfo();
     m_FilterShape = rFilterInfo.GetShape();
     m_FilterDecoder = MakeDecoder<float>(rFilterInfo, m_Weight.get()->Map(true));
     if (descriptor.m_Parameters.m_BiasEnabled)
     {
         m_Bias = std::make_unique<ScopedCpuTensorHandle>(*(descriptor.m_Bias));
         const TensorInfo& biasInfo = m_Bias->GetTensorInfo();
         m_BiasDecoder = MakeDecoder<float>(biasInfo, m_Bias->Map(true));
     }
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 44 of file RefConvolution2dWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, armnn::Convolve(), armnn::CpuRef, Convolution2dDescriptor::m_BiasEnabled, BaseWorkload< Convolution2dQueueDescriptor >::m_Data, Convolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_DilationX, Convolution2dDescriptor::m_DilationY, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, Convolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadTop, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, Convolution2dDescriptor::m_StrideX, and Convolution2dDescriptor::m_StrideY.
{
     ARMNN_SCOPED_PROFILING_EVENT(Compute::CpuRef, "RefConvolution2dWorkload_Execute");
     m_InputDecoder->Reset(m_Data.m_Inputs[0]->Map());
     m_OutputEncoder->Reset(m_Data.m_Outputs[0]->Map());
     Convolve(m_InputShape, *m_InputDecoder, m_OutputShape, *m_OutputEncoder, m_FilterShape,
              *m_FilterDecoder, m_Data.m_Parameters.m_BiasEnabled, m_BiasDecoder.get(),
              m_Data.m_Parameters.m_DataLayout, m_Data.m_Parameters.m_PadTop, m_Data.m_Parameters.m_PadLeft,
              m_Data.m_Parameters.m_StrideX, m_Data.m_Parameters.m_StrideY,
              m_Data.m_Parameters.m_DilationX, m_Data.m_Parameters.m_DilationY);
 }
PostAllocationConfigure()
void PostAllocationConfigure () override virtual
Implements IWorkload.
Definition at line 33 of file RefConvolution2dWorkload.cpp.
References TensorInfo::GetShape(), armnn::GetTensorInfo(), BaseWorkload< Convolution2dQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, and QueueDescriptor::m_Outputs.
 {
     const TensorInfo& inputInfo = GetTensorInfo(m_Data.m_Inputs[0]);
     m_InputShape = inputInfo.GetShape();
     m_InputDecoder = MakeDecoder<float>(inputInfo);
     const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
     m_OutputShape = outputInfo.GetShape();
     m_OutputEncoder = MakeEncoder<float>(outputInfo);
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefConvolution2dWorkload.hpp
src/backends/reference/workloads/RefConvolution2dWorkload.cpp