ArmNN: DynamicQuantizationVisitor Class Reference
DynamicQuantizationVisitor Class Reference
Visitor class to establish min/max ranges based on the type of the layer.
#include <DynamicQuantizationVisitor.hpp>
Public Member Functions
DynamicQuantizationVisitor (RangeTracker &rangeTracker, Graph &graph)
~DynamicQuantizationVisitor ()=default
void VisitAdditionLayer (const IConnectableLayer *layer, const char *name=nullptr) override
Functions to set the Range on a per-layer-type basis.
void VisitBatchNormalizationLayer (const IConnectableLayer *layer, const BatchNormalizationDescriptor &desc, const ConstTensor &mean, const ConstTensor &variance, const ConstTensor &beta, const ConstTensor &gamma, const char *name=nullptr) override
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConvolution2dLayer (const IConnectableLayer *layer, const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *layer, const DepthwiseConvolution2dDescriptor &desc, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitActivationLayer (const IConnectableLayer *layer, const ActivationDescriptor &activationDescriptor, const char *name=nullptr) override
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFullyConnectedLayer (const IConnectableLayer *layer, const FullyConnectedDescriptor &desc, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name) override
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPermuteLayer (const IConnectableLayer *layer, const PermuteDescriptor &permuteDescriptor, const char *name) override
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToBatchNdLayer (const IConnectableLayer *layer, const SpaceToBatchNdDescriptor &spaceToBatchNdDescriptor, const char *name=nullptr) override
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPooling2dLayer (const IConnectableLayer *layer, const Pooling2dDescriptor &pooling2dDescriptor, const char *name) override
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSoftmaxLayer (const IConnectableLayer *layer, const SoftmaxDescriptor &softmaxDescriptor, const char *name=nullptr) override
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConcatLayer (const IConnectableLayer *layer, const ConcatDescriptor &originsDescriptor, const char *name=nullptr) override
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConstantLayer (const IConnectableLayer *layer, const ConstTensor &input, const char *name=nullptr) override
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitReshapeLayer (const IConnectableLayer *layer, const ReshapeDescriptor &reshapeDescriptor, const char *name=nullptr) override
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSplitterLayer (const IConnectableLayer *layer, const SplitterDescriptor &splitterDescriptor, const char *name=nullptr) override
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeBilinearLayer (const IConnectableLayer *layer, const ResizeBilinearDescriptor &resizeDesc, const char *name=nullptr) override
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStridedSliceLayer (const IConnectableLayer *layer, const StridedSliceDescriptor &stridedSliceDescriptor, const char *name=nullptr) override
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchToSpaceNdLayer (const IConnectableLayer *layer, const BatchToSpaceNdDescriptor &batchToSpaceNdDescriptor, const char *name=nullptr) override
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInputLayer (const IConnectableLayer *layer, LayerBindingId id, const char *name=nullptr) override
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitOutputLayer (const IConnectableLayer *layer, LayerBindingId id, const char *name=nullptr) override
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void FinishVisit () override
void VisitNonCalibratedLayers ()
const std::vector< armnn::LayerBindingId > & GetOutputLayers ()
Public Member Functions inherited from LayerVisitorBase< VisitorNoThrowPolicy >
void VisitAbsLayer (const IConnectableLayer *, const char *) override
Function an absolute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitActivationLayer (const IConnectableLayer *, const ActivationDescriptor &, const char *) override
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitAdditionLayer (const IConnectableLayer *, const char *) override
Function that an addition layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitArgMinMaxLayer (const IConnectableLayer *, const ArgMinMaxDescriptor &, const char *) override
Function that an arg min max layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchNormalizationLayer (const IConnectableLayer *, const BatchNormalizationDescriptor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const char *) override
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitBatchToSpaceNdLayer (const IConnectableLayer *, const BatchToSpaceNdDescriptor &, const char *) override
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitComparisonLayer (const IConnectableLayer *, const ComparisonDescriptor &, const char *) override
Function a Comparison layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConcatLayer (const IConnectableLayer *, const ConcatDescriptor &, const char *) override
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConstantLayer (const IConnectableLayer *, const ConstTensor &, const char *) override
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitConvolution2dLayer (const IConnectableLayer *, const Convolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthToSpaceLayer (const IConnectableLayer *, const DepthToSpaceDescriptor &, const char *) override
Function a depth to space layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *, const DepthwiseConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDequantizeLayer (const IConnectableLayer *, const char *) override
Function that a Dequantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDetectionPostProcessLayer (const IConnectableLayer *, const DetectionPostProcessDescriptor &, const ConstTensor &, const char *) override
Function that a Detection PostProcess layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitDivisionLayer (const IConnectableLayer *, const char *) override
Function a division layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitElementwiseUnaryLayer (const IConnectableLayer *, const ElementwiseUnaryDescriptor &, const char *) override
Function a ElementwiseUnary layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitEqualLayer (const IConnectableLayer *, const char *) override
Function an Equal layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFloorLayer (const IConnectableLayer *, const char *) override
Function a floor layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitFullyConnectedLayer (const IConnectableLayer *, const FullyConnectedDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGatherLayer (const IConnectableLayer *, const char *) override
Function a Gather layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitGreaterLayer (const IConnectableLayer *, const char *) override
Function a Greater layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitInstanceNormalizationLayer (const IConnectableLayer *, const InstanceNormalizationDescriptor &, const char *) override
Function that an instance normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitL2NormalizationLayer (const IConnectableLayer *, const L2NormalizationDescriptor &, const char *) override
Function that an L2 normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLogSoftmaxLayer (const IConnectableLayer *, const LogSoftmaxDescriptor &, const char *) override
Function that a log softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitLstmLayer (const IConnectableLayer *, const LstmDescriptor &, const LstmInputParams &, const char *) override
Function an Lstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMaximumLayer (const IConnectableLayer *, const char *) override
Function a Maximum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMeanLayer (const IConnectableLayer *, const MeanDescriptor &, const char *) override
Function a Mean layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMergeLayer (const IConnectableLayer *, const char *) override
Function that a merge layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMergerLayer (const IConnectableLayer *, const MergerDescriptor &, const char *) override
Function that a merger layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMinimumLayer (const IConnectableLayer *, const char *) override
Function a Minimum layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitMultiplicationLayer (const IConnectableLayer *, const char *) override
Function that a multiplication layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitNormalizationLayer (const IConnectableLayer *, const NormalizationDescriptor &, const char *) override
Function that a normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitOutputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPadLayer (const IConnectableLayer *, const PadDescriptor &, const char *) override
Function a pad layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPermuteLayer (const IConnectableLayer *, const PermuteDescriptor &, const char *) override
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPooling2dLayer (const IConnectableLayer *, const Pooling2dDescriptor &, const char *) override
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitPreluLayer (const IConnectableLayer *, const char *) override
Function that a PReLU activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQuantizeLayer (const IConnectableLayer *, const char *) override
Function a quantize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitQuantizedLstmLayer (const IConnectableLayer *, const QuantizedLstmInputParams &, const char *) override
Function a QuantizedLstm layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitReshapeLayer (const IConnectableLayer *, const ReshapeDescriptor &, const char *) override
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeBilinearLayer (const IConnectableLayer *, const ResizeBilinearDescriptor &, const char *) override
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitResizeLayer (const IConnectableLayer *, const ResizeDescriptor &, const char *) override
Function that a resize layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitRsqrtLayer (const IConnectableLayer *, const char *) override
Function a Reciprocal of square root layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSliceLayer (const IConnectableLayer *, const SliceDescriptor &, const char *) override
Function that a slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSoftmaxLayer (const IConnectableLayer *, const SoftmaxDescriptor &, const char *) override
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToBatchNdLayer (const IConnectableLayer *, const SpaceToBatchNdDescriptor &, const char *) override
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSpaceToDepthLayer (const IConnectableLayer *, const SpaceToDepthDescriptor &, const char *) override
Function a space to depth layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSplitterLayer (const IConnectableLayer *, const ViewsDescriptor &, const char *) override
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStackLayer (const IConnectableLayer *, const StackDescriptor &, const char *) override
Function a stack layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitStandInLayer (const IConnectableLayer *, const StandInDescriptor &, const char *) override
Function a StandInLayer should call back to when its Accept(ILaterVisitor&) function is invoked.
void VisitStridedSliceLayer (const IConnectableLayer *, const StridedSliceDescriptor &, const char *) override
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSubtractionLayer (const IConnectableLayer *, const char *) override
Function a subtraction layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitSwitchLayer (const IConnectableLayer *, const char *) override
Function a switch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeConvolution2dLayer (const IConnectableLayer *, const TransposeConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Function that a 2D transpose convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
void VisitTransposeLayer (const IConnectableLayer *, const TransposeDescriptor &, const char *) override
Function that a transpose layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Public Member Functions inherited from ILayerVisitor
virtual void StartVisit ()
Additional Inherited Members
Protected Member Functions inherited from LayerVisitorBase< VisitorNoThrowPolicy >
LayerVisitorBase ()
virtual ~LayerVisitorBase ()
Protected Member Functions inherited from ILayerVisitor
ILayerVisitor ()
virtual ~ILayerVisitor ()
Detailed Description
Visitor class to establish min/max ranges based on the type of the layer.
Definition at line 19 of file DynamicQuantizationVisitor.hpp.
Constructor & Destructor Documentation
DynamicQuantizationVisitor()
DynamicQuantizationVisitor (RangeTracker & rangeTracker, Graph & graph)
Definition at line 18 of file DynamicQuantizationVisitor.cpp.
References IOutputSlot::CalculateIndexOnOwner(), IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IOutputSlot::GetOwningLayerGuid(), RangeTracker::GetRange(), and RangeTracker::SetRange().
         : m_RangeTracker(rangeTracker),
           m_Graph(graph)
 {}
~DynamicQuantizationVisitor()
~DynamicQuantizationVisitor () default
Member Function Documentation
FinishVisit()
void FinishVisit () override virtual
Reimplemented from ILayerVisitor.
Definition at line 50 of file DynamicQuantizationVisitor.cpp.
References OutputSlot::Connect(), OutputSlot::Disconnect(), Graph::EraseLayer(), and armnn::InsertDebugLayerAfter().
 {
     for (const IConnectableLayer* layer : m_LayersToCalibrate)
     {
         std::vector<DebugLayer*> newDebugLayers = InsertDebugLayerAfter(
             m_Graph, *boost::polymorphic_downcast<Layer*>(const_cast<IConnectableLayer*>(layer)));
         // record them so we can take them out again efficiently afterward
         m_DebugLayers.insert(std::end(m_DebugLayers), std::begin(newDebugLayers), std::end(newDebugLayers));
     }
 }
GetOutputLayers()
const std::vector< LayerBindingId > & GetOutputLayers ()
Definition at line 330 of file DynamicQuantizationVisitor.cpp.
 {
     return m_OutputLayers;
 }
VisitActivationLayer()
void VisitActivationLayer (const IConnectableLayer * layer, const ActivationDescriptor & activationDescriptor, const char * name = nullptr) override virtual
Function that an activation layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
activationDescriptor - ActivationDescriptor to configure the activation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 139 of file DynamicQuantizationVisitor.cpp.
References armnn::Abs, armnn::BoundedReLu, armnn::IgnoreUnused(), armnn::LeakyReLu, armnn::Linear, ActivationDescriptor::m_A, ActivationDescriptor::m_Function, armnn::ReLu, armnn::SoftReLu, and armnn::TanH.
 {
     IgnoreUnused(name, activationDescriptor);
     switch (activationDescriptor.m_Function)
     {
         // Range is 0, 15 for Abs, Linear, ReLu and Soft ReLu
         case ActivationFunction::Abs:
         case ActivationFunction::Linear:
         case ActivationFunction::ReLu:
         case ActivationFunction::SoftReLu:
             SetRange(layer, 0, 0.f, 15.f);
             break;
         case ActivationFunction::BoundedReLu:
             SetRange(layer, 0, 0.f, activationDescriptor.m_A);
             break;
         case ActivationFunction::TanH:
             SetRange(layer, 0, -1.f, 1.f);
             break;
         case ActivationFunction::LeakyReLu:
             SetRange(layer, 0, -5.f, 15.f);
             break;
         default:
             SetRange(layer, 0, -15.f, 15.f);
             break;
     }
     AddToCalibratedLayers(layer);
 }
VisitAdditionLayer()
void VisitAdditionLayer (const IConnectableLayer * layer, const char * name = nullptr) override virtual
Functions to set the Range on a per-layer-type basis.
Implements ILayerVisitor.
Definition at line 86 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(name);
     SetRange(layer, 0, -20.f, 20.f);
     AddToCalibratedLayers(layer);
 }
VisitBatchNormalizationLayer()
void VisitBatchNormalizationLayer (const IConnectableLayer * layer, const BatchNormalizationDescriptor & desc, const ConstTensor & mean, const ConstTensor & variance, const ConstTensor & beta, const ConstTensor & gamma, const char * name = nullptr) override virtual
Function that a batch normalization layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
mean - Pre-calculated mean for each channel.
variance - Pre-calculated variance for each channel.
beta - Per-channel additive factor.
gamma - Per-channel multiplicative factor.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 93 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(desc);
     IgnoreUnused(mean);
     IgnoreUnused(variance);
     IgnoreUnused(beta);
     IgnoreUnused(gamma);
     IgnoreUnused(name);
     SetRange(layer, 0, -15.0f, 15.0f);
     AddToCalibratedLayers(layer);
 }
VisitBatchToSpaceNdLayer()
void VisitBatchToSpaceNdLayer (const IConnectableLayer * layer, const BatchToSpaceNdDescriptor & batchToSpaceNdDescriptor, const char * name = nullptr) override virtual
Function that a batch to space ND layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
batchToSpaceNdDescriptor - Description of the layer.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 305 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(batchToSpaceNdDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitConcatLayer()
void VisitConcatLayer (const IConnectableLayer * layer, const ConcatDescriptor & concatDescriptor, const char * name = nullptr) override virtual
Function that a concat layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
concatDescriptor - ConcatDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Reimplemented from ILayerVisitor.
Definition at line 248 of file DynamicQuantizationVisitor.cpp.
References IOutputSlot::CalculateIndexOnOwner(), IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IOutputSlot::GetOwningLayerGuid(), RangeTracker::GetRange(), and armnn::IgnoreUnused().
 {
     IgnoreUnused(name);
     IgnoreUnused(originsDescriptor);
     float min = std::numeric_limits<float>::max();
     float max = std::numeric_limits<float>::lowest();
     for (unsigned int i = 0; i < layer->GetNumInputSlots(); ++i)
     {
         const IOutputSlot* outputSlot = layer->GetInputSlot(i).GetConnection();
         LayerGuid layerId = outputSlot->GetOwningLayerGuid();
         unsigned int slotIndex = outputSlot->CalculateIndexOnOwner();
         RangeTracker::MinMaxRange range = m_RangeTracker.GetRange(layerId, slotIndex);
         min = std::min(min, range.first);
         max = std::max(max, range.second);
     }
     SetRange(layer, 0, min, max);
     AddToCalibratedLayers(layer);
 }
VisitConstantLayer()
void VisitConstantLayer (const IConnectableLayer * layer, const ConstTensor & input, const char * name = nullptr) override virtual
Function a layer with no inputs and a single output, which always corresponds to the passed in constant tensor should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
input - Tensor to be provided as the only output of the layer. The layer will maintain its own copy of the tensor data, meaning the memory referenced by input can be freed or reused after this function is called.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 220 of file DynamicQuantizationVisitor.cpp.
References armnn::Float32, BaseTensor< MemoryType >::GetDataType(), BaseTensor< MemoryType >::GetMemoryArea(), BaseTensor< MemoryType >::GetNumElements(), and armnn::IgnoreUnused().
 {
     IgnoreUnused(name);
     if (input.GetDataType() != DataType::Float32)
     {
         throw InvalidArgumentException("Quantization is supported only for FP32 tensors");
     }
     // Work out the range based on the input constants
     unsigned int inputNumElements = input.GetNumElements();
     const float* inputData = reinterpret_cast<const float*>(input.GetMemoryArea());
     float min = std::numeric_limits<float>::max();
     float max = std::numeric_limits<float>::lowest();
     for (unsigned int i = 0; i < inputNumElements; i++)
     {
         const float inputValue = inputData[i];
         min = std::min(min, inputValue);
         max = std::max(max, inputValue);
     }
     SetRange(layer, 0, min, max);
 }
VisitConvolution2dLayer()
void VisitConvolution2dLayer (const IConnectableLayer * layer, const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Function that a 2D convolution layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 111 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(convolution2dDescriptor);
     IgnoreUnused(weights);
     IgnoreUnused(biases);
     IgnoreUnused(name);
     SetRange(layer, 0, -15.0f, 15.0f);
     AddToCalibratedLayers(layer);
 }
VisitDepthwiseConvolution2dLayer()
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer * layer, const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) override virtual
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D depthwise convolution layer.
weights - Tensor for the weights. Expected format: [channelMultiplier, inputChannels, height, width].
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 125 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(desc);
     IgnoreUnused(weights);
     IgnoreUnused(biases);
     IgnoreUnused(name);
     SetRange(layer, 0, -15.0f, 15.0f);
     AddToCalibratedLayers(layer);
 }
VisitFullyConnectedLayer()
void VisitFullyConnectedLayer (const IConnectableLayer * layer, const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name) override virtual
Function that a fully connected layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
fullyConnectedDescriptor - Description of the fully connected layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 169 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(desc);
     IgnoreUnused(weights);
     IgnoreUnused(biases);
     IgnoreUnused(name);
     SetRange(layer, 0, -15.0f, 15.0f);
     AddToCalibratedLayers(layer);
 }
VisitInputLayer()
void VisitInputLayer (const IConnectableLayer * layer, LayerBindingId id, const char * name = nullptr) override virtual
Function that an InputLayer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
id - User generated id to uniquely identify a particular input. The same id needs to be specified when passing the inputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 314 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(id);
     IgnoreUnused(name);
     SetRange(layer, 0, -0.0f, 0.0f);
     AddToCalibratedLayers(layer);
 }
VisitNonCalibratedLayers()
void VisitNonCalibratedLayers ()
Definition at line 78 of file DynamicQuantizationVisitor.cpp.
{
     RemoveDebugLayers();
     for (const IConnectableLayer* layer : m_LayersNotToCalibrate)
     {
         ForwardParentParameters(layer);
     }
 }
VisitOutputLayer()
void VisitOutputLayer (const IConnectableLayer * layer, LayerBindingId id, const char * name = nullptr) override virtual
Function an output layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
id - User generated id to uniquely identify a particular output. The same id needs to be specified when passing the outputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 322 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(id);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
     m_OutputLayers.push_back(id);
 }
VisitPermuteLayer()
void VisitPermuteLayer (const IConnectableLayer * layer, const PermuteDescriptor & permuteDescriptor, const char * name) override virtual
Function that a permute layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
permuteDescriptor - PermuteDescriptor to configure the permute.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 183 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(permuteDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitPooling2dLayer()
void VisitPooling2dLayer (const IConnectableLayer * layer, const Pooling2dDescriptor & pooling2dDescriptor, const char * name) override virtual
Function that a pooling layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
pooling2dDescriptor - Pooling2dDescriptor to configure the pooling.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 201 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(pooling2dDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitReshapeLayer()
void VisitReshapeLayer (const IConnectableLayer * layer, const ReshapeDescriptor & reshapeDescriptor, const char * name = nullptr) override virtual
Function a reshape layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
reshapeDescriptor - Parameters for the reshape operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 269 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(reshapeDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitResizeBilinearLayer()
void VisitResizeBilinearLayer (const IConnectableLayer * layer, const ResizeBilinearDescriptor & resizeDesc, const char * name = nullptr) override virtual
Function that a resize bilinear layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
resizeDesc - Parameters for the resize operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 287 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(resizeDesc);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitSoftmaxLayer()
void VisitSoftmaxLayer (const IConnectableLayer * layer, const SoftmaxDescriptor & softmaxDescriptor, const char * name = nullptr) override virtual
Function that a softmax layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
softmaxDescriptor - SoftmaxDescriptor to configure the softmax.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 210 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(softmaxDescriptor);
     IgnoreUnused(name);
     SetRange(layer, 0, 0.f, 1.f);
     AddToCalibratedLayers(layer);
 }
VisitSpaceToBatchNdLayer()
void VisitSpaceToBatchNdLayer (const IConnectableLayer * layer, const SpaceToBatchNdDescriptor & spaceToBatchNdDescriptor, const char * name = nullptr) override virtual
Function a space to batch layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
spaceToBatchNdDescriptor - Parameters for the space to batch operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 192 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(spaceToBatchNdDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitSplitterLayer()
void VisitSplitterLayer (const IConnectableLayer * layer, const SplitterDescriptor & splitterDescriptor, const char * name = nullptr) override virtual
Function that a splitter layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
splitterDescriptor - ViewsDescriptor to configure the splitting process. Number of Views must be equal to the number of outputs, and their order must match - e.g. first view corresponds to the first output, second view to the second output, etc....
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 278 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(splitterDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
VisitStridedSliceLayer()
void VisitStridedSliceLayer (const IConnectableLayer * layer, const StridedSliceDescriptor & stridedSliceDescriptor, const char * name = nullptr) override virtual
Function a strided slice layer should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
stridedSliceDescriptor - Parameters for the strided slice operation.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 296 of file DynamicQuantizationVisitor.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(stridedSliceDescriptor);
     IgnoreUnused(name);
     AddToNonCalibratedLayers(layer);
 }
The documentation for this class was generated from the following files:
src/armnn/DynamicQuantizationVisitor.hpp
src/armnn/DynamicQuantizationVisitor.cpp