ArmNN: DynamicBackend Class Reference
DynamicBackend Class Reference final
#include <DynamicBackend.hpp>
Public Types
using HandleCloser = std::function< void(const void *)>
using HandlePtr = std::unique_ptr< void, HandleCloser >
Public Member Functions
DynamicBackend (const void *sharedObjectHandle)
BackendId GetBackendId ()
Public dynamic backend functions.
BackendVersion GetBackendVersion ()
IBackendInternalUniquePtr GetBackend ()
BackendRegistry::FactoryFunction GetFactoryFunction ()
Detailed Description
Definition at line 18 of file DynamicBackend.hpp.
Member Typedef Documentation
HandleCloser
using HandleCloser = std::function<void(const void*)>
Definition at line 21 of file DynamicBackend.hpp.
HandlePtr
using HandlePtr = std::unique_ptr<void, HandleCloser>
Definition at line 22 of file DynamicBackend.hpp.
Constructor & Destructor Documentation
DynamicBackend()
DynamicBackend (const void * sharedObjectHandle) explicit
Definition at line 12 of file DynamicBackend.cpp.
References IBackendInternal::GetApiVersion(), DynamicBackend::GetBackendId(), DynamicBackend::GetBackendVersion(), and DynamicBackendUtils::IsBackendCompatible().
     : m_BackendIdFunction(nullptr)
     , m_BackendVersionFunction(nullptr)
     , m_BackendFactoryFunction(nullptr)
     , m_Handle(const_cast<void*>(sharedObjectHandle), &DynamicBackendUtils::CloseHandle)
 {
     if (m_Handle == nullptr)
     {
         throw InvalidArgumentException("Cannot create a DynamicBackend object from an invalid shared object handle");
     }
     // These calls will throw in case of error
     m_BackendIdFunction      = SetFunctionPointer<IdFunctionType>("GetBackendId");
     m_BackendVersionFunction = SetFunctionPointer<VersionFunctionType>("GetVersion");
     m_BackendFactoryFunction = SetFunctionPointer<FactoryFunctionType>("BackendFactory");
     // Check that the backend is compatible with the current Backend API
     BackendId backendId = GetBackendId();
     BackendVersion backendVersion = GetBackendVersion();
     if (!DynamicBackendUtils::IsBackendCompatible(backendVersion))
     {
         throw RuntimeException(boost::str(boost::format("The dynamic backend %1% (version %2%) is not compatible"
                                                         "with the current Backend API (vesion %3%)")
                                           % backendId
                                           % backendVersion
                                           % IBackendInternal::GetApiVersion()));
     }
 }
Member Function Documentation
GetBackend()
IBackendInternalUniquePtr GetBackend ()
Definition at line 71 of file DynamicBackend.cpp.
 {
     // This call throws in case of error
     return CreateBackend();
 }
GetBackendId()
BackendId GetBackendId ()
Public dynamic backend functions.
Definition at line 41 of file DynamicBackend.cpp.
Referenced by DynamicBackend::DynamicBackend().
 {
     if (m_BackendIdFunction == nullptr)
     {
         throw RuntimeException("GetBackendId error: invalid function pointer");
     }
     const char* backendId = m_BackendIdFunction();
     if (backendId == nullptr)
     {
         throw RuntimeException("GetBackendId error: invalid backend id");
     }
     return BackendId(backendId);
 }
GetBackendVersion()
BackendVersion GetBackendVersion ()
Definition at line 57 of file DynamicBackend.cpp.
Referenced by DynamicBackend::DynamicBackend().
 {
     if (m_BackendVersionFunction == nullptr)
     {
         throw RuntimeException("GetBackendVersion error: invalid function pointer");
     }
     uint32_t major = 0;
     uint32_t minor = 0;
     m_BackendVersionFunction(&major, &minor);
     return BackendVersion{ major, minor };
 }
GetFactoryFunction()
BackendRegistry::FactoryFunction GetFactoryFunction ()
Definition at line 77 of file DynamicBackend.cpp.
 {
     if (m_BackendFactoryFunction == nullptr)
     {
         throw RuntimeException("GetFactoryFunction error: invalid function pointer");
     }
     return [this]() -> IBackendInternalUniquePtr
     {
         // This call throws in case of error
         return CreateBackend();
     };
 }
The documentation for this class was generated from the following files:
include/armnn/backends/DynamicBackend.hpp
src/backends/backendsCommon/DynamicBackend.cpp