ArmNN: DirectoryCaptureCommandHandler Class Reference
DirectoryCaptureCommandHandler Class Reference
#include <DirectoryCaptureCommandHandler.hpp>
Public Member Functions
DirectoryCaptureCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, bool quietOperation=true)
void operator() (const armnn::profiling::Packet &packet) override
const ICounterDirectory & GetCounterDirectory () const
bool ParsedCounterDirectory ()
uint16_t TranslateUIDCopyToOriginal (uint16_t copyUid)
Given a Uid that came from a copy of the counter directory translate it to the original.
Public Member Functions inherited from CommandHandlerFunctor
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
virtual ~CommandHandlerFunctor ()
Detailed Description
Definition at line 33 of file DirectoryCaptureCommandHandler.hpp.
Constructor & Destructor Documentation
DirectoryCaptureCommandHandler()
DirectoryCaptureCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, bool quietOperation = true) inline
Definition at line 37 of file DirectoryCaptureCommandHandler.hpp.
         : CommandHandlerFunctor(familyId, packetId, version)
         , m_QuietOperation(quietOperation)
         , m_AlreadyParsed(false)
     {}
Member Function Documentation
GetCounterDirectory()
const ICounterDirectory & GetCounterDirectory () const
Definition at line 310 of file DirectoryCaptureCommandHandler.cpp.
References armnn::profiling::ReadUint8().
 {
     return m_CounterDirectory;
 }
operator()()
void operator() (const armnn::profiling::Packet & packet) override virtual
Implements CommandHandlerFunctor.
Definition at line 290 of file DirectoryCaptureCommandHandler.cpp.
References DirectoryCaptureCommandHandler::ParsedCounterDirectory(), and armnn::profiling::PrintCounterDirectory().
 {
     if (!m_QuietOperation)    // Are we supposed to print to stdout?
     {
         std::cout << "Counter directory packet received." << std::endl;
     }
     // The ArmNN counter directory is static per ArmNN instance. Ensure we don't parse it a second time.
     if (!ParsedCounterDirectory())
     {
         ParseData(packet);
         m_AlreadyParsed = true;
     }
     if (!m_QuietOperation)
     {
         armnn::profiling::PrintCounterDirectory(m_CounterDirectory);
     }
 }
ParsedCounterDirectory()
bool ParsedCounterDirectory () inline
Definition at line 47 of file DirectoryCaptureCommandHandler.hpp.
Referenced by DirectoryCaptureCommandHandler::operator()().
     {
         return m_AlreadyParsed.load();
     }
TranslateUIDCopyToOriginal()
uint16_t TranslateUIDCopyToOriginal (uint16_t copyUid) inline
Given a Uid that came from a copy of the counter directory translate it to the original.
Parameters
copyUid
Returns
the original Uid that the copy maps to.
Definition at line 58 of file DirectoryCaptureCommandHandler.hpp.
     {
         return m_UidTranslation[copyUid];
     }
The documentation for this class was generated from the following files:
src/profiling/DirectoryCaptureCommandHandler.hpp
src/profiling/DirectoryCaptureCommandHandler.cpp