ArmNN: CommandLineProcessor Class Reference
CommandLineProcessor Class Reference
Use Boost program options to process the command line.
#include <CommandLineProcessor.hpp>
Public Member Functions
bool ProcessCommandLine (int argc, char *argv[])
bool IsEchoEnabled ()
std::string GetUdsNamespace ()
std::string GetCommandFile ()
Detailed Description
Use Boost program options to process the command line.
-h or –help to print the options. -n or –namespace to specify the UDS namespace that the server will be listening on. -e or –echo print all sent and received packets to stdout. -f or –file The path to the file that contains instructions for the mock gatord.
Definition at line 20 of file CommandLineProcessor.hpp.
Member Function Documentation
GetCommandFile()
std::string GetCommandFile () inline
Definition at line 33 of file CommandLineProcessor.hpp.
Referenced by main().
     {
         return m_File;
     }
GetUdsNamespace()
std::string GetUdsNamespace () inline
Definition at line 29 of file CommandLineProcessor.hpp.
Referenced by main().
     {
         return m_UdsNamespace;
     }
IsEchoEnabled()
bool IsEchoEnabled () inline
Definition at line 24 of file CommandLineProcessor.hpp.
Referenced by main().
     {
         return m_Echo;
     }
ProcessCommandLine()
bool ProcessCommandLine (int argc, char * argv[])
Definition at line 16 of file CommandLineProcessor.cpp.
References armnn::error.
Referenced by main().
 {
     namespace po = boost::program_options;
     po::options_description desc("Options");
     try
     {
         desc.add_options()
                 ("help,h", "Display help messages")
                 ("file,f",  po::value<std::string>(&m_File),
                                  "The path to the file that contains instructions for the mock gatord")
                 ("namespace,n", po::value<std::string>(&m_UdsNamespace)->default_value("gatord_namespace"),
                                 "The Unix domain socket namespace this server will bind to.\n"
                                 "This will always be prepended with \\0 to use the abstract namespace")
                 ("echo,e", po::bool_switch(&m_Echo)->default_value(false),
                                 "Echo packets sent and received to stdout. Disabled by default.\n");
     }
     catch (const std::exception& e)
     {
         std::cerr << "Fatal internal error: [" << e.what() << "]" << std::endl;
         return false;
     }
     po::variables_map vm;
     try
     {
         po::store(po::parse_command_line(argc, argv, desc), vm);
         if (vm.count("help"))
         {
             std::cout << "Simulate a Gatord server to interact with ArmNN external profiling." << std::endl;
             std::cout << std::endl;
             std::cout << desc << std::endl;
             return false;
         }
         // Currently the file parameter is mandatory.
         if (!vm.count("file"))
         {
             std::cout << std::endl << "*** Expected --file or -f parameter." << std::endl;
             std::cout << std::endl;
             std::cout << desc << std::endl;
             return false;
         }
         po::notify(vm);
     }
     catch (const po::error& e)
     {
         std::cerr << e.what() << std::endl << std::endl;
         std::cerr << desc << std::endl;
         return false;
     }
     return true;
 }
The documentation for this class was generated from the following files:
tests/profiling/gatordmock/CommandLineProcessor.hpp
tests/profiling/gatordmock/CommandLineProcessor.cpp