ArmNN: armnnTfParser Namespace Reference
armnnTfParser Namespace Reference
Classes
class ITfParser
Parses a directed acyclic graph from a tensorflow protobuf file.
class TfParser
struct WithOutputTensorIndex
WithOutputTensorIndex wraps a value and an index.
Typedefs
using BindingPointInfo = armnn::BindingPointInfo
using ITfParserPtr = std::unique_ptr< ITfParser, void(*)(ITfParser *parser)>
using ParsedTfOperationPtr = std::unique_ptr< ParsedTfOperation >
using OutputOfParsedTfOperation = WithOutputTensorIndex< ParsedTfOperation * >
using OutputOfConstNodeDef = WithOutputTensorIndex< const tensorflow::NodeDef * >
using OutputId = WithOutputTensorIndex< std::string >
Functions
void CalculateSamePadding (uint32_t inputSize, uint32_t stride, uint32_t filterSize, bool samePadding, uint32_t *paddingFront, uint32_t *paddingBack)
void CalcPadding (uint32_t input, uint32_t kernel, uint32_t stride, uint32_t &outPadHead, uint32_t &outPadTail, bool samePadding)
DataType ConvertTfTensorDataType (const tensorflow::DataType tfDataType, const tensorflow::NodeDef &nodeDef)
TensorInfo OutputShapeOfExpandDims (const tensorflow::NodeDef &nodeDef, TensorInfo inputTensorInfo)
unsigned int CheckPaddingTensor (const ConstTensor &paddingTensor, const TensorInfo &inputTensorInfo, const std::string &nodeName)
TensorInfo CalculatePaddedOutputTensorInfo (const TensorInfo &inputTensorInfo, const std::vector< std::pair< unsigned int, unsigned int >> &padList)
TensorInfo OutputShapeOfSqueeze (const tensorflow::NodeDef &nodeDef, TensorInfo inputTensorInfo)
Typedef Documentation
BindingPointInfo
using BindingPointInfo = armnn::BindingPointInfo
Definition at line 19 of file ITfParser.hpp.
ITfParserPtr
using ITfParserPtr = std::unique_ptr<ITfParser, void(*)(ITfParser* parser)>
Definition at line 22 of file ITfParser.hpp.
OutputId
using OutputId = WithOutputTensorIndex<std::string>
Definition at line 62 of file TfParser.hpp.
OutputOfConstNodeDef
using OutputOfConstNodeDef = WithOutputTensorIndex<const tensorflow::NodeDef*>
Definition at line 61 of file TfParser.hpp.
OutputOfParsedTfOperation
using OutputOfParsedTfOperation = WithOutputTensorIndex<ParsedTfOperation *>
Definition at line 60 of file TfParser.hpp.
ParsedTfOperationPtr
using ParsedTfOperationPtr = std::unique_ptr<ParsedTfOperation>
Definition at line 35 of file TfParser.hpp.
Function Documentation
CalcPadding()
void armnnTfParser::CalcPadding (uint32_t input, uint32_t kernel, uint32_t stride, uint32_t & outPadHead, uint32_t & outPadTail, bool samePadding)
Definition at line 421 of file TfParser.cpp.
References CalculateSamePadding(), CHECK_LOCATION, Layer::GetName(), Layer::GetNumOutputSlots(), Layer::GetOutputSlot(), and m_Layer.
Referenced by ConvertTfTensorDataType(), TfLiteParser::CreateNetworkFromBinary(), OnnxParser::CreateNetworkFromString(), and OutputShapeOfSqueeze().
 {
     CalculateSamePadding(input, stride, kernel, samePadding, &outPadHead, &outPadTail);
 }
CalculatePaddedOutputTensorInfo()
TensorInfo armnnTfParser::CalculatePaddedOutputTensorInfo (const TensorInfo & inputTensorInfo, const std::vector< std::pair< unsigned int, unsigned int >> & padList)
Definition at line 2138 of file TfParser.cpp.
References INetwork::AddConcatLayer(), INetwork::AddPadLayer(), INetwork::AddReshapeLayer(), INetwork::AddResizeLayer(), armnn::Bilinear, CHECK_LOCATION, CheckPaddingTensor(), IOutputSlot::Connect(), armnn::Float32, IConnectableLayer::GetInputSlot(), TensorInfo::GetNumDimensions(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), OriginsDescriptor::GetViewOrigin(), armnn::IgnoreUnused(), ResizeDescriptor::m_DataLayout, ResizeDescriptor::m_Method, ResizeDescriptor::m_TargetHeight, ReshapeDescriptor::m_TargetShape, ResizeDescriptor::m_TargetWidth, armnn::NHWC, OriginsDescriptor::SetConcatAxis(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), and OriginsDescriptor::SetViewOriginCoord().
 {
     unsigned int numDims = inputTensorInfo.GetNumDimensions();
     std::vector<unsigned int> outDims;
     for (unsigned int i = 0; i < numDims; ++i)
     {
         unsigned int dimSize = inputTensorInfo.GetShape()[i];
         const std::pair<unsigned int, unsigned int>& dimPadding = padList[i];
         dimSize += dimPadding.first;
         dimSize += dimPadding.second;
         outDims.push_back(dimSize);
     }
     TensorInfo paddedTensorInfo = inputTensorInfo;
     unsigned int outDimsSize = static_cast<unsigned int>(outDims.size());
     paddedTensorInfo.SetShape(TensorShape{ outDimsSize, outDims.data() });
     return paddedTensorInfo;
 }
CalculateSamePadding()
void armnnTfParser::CalculateSamePadding (uint32_t inputSize, uint32_t stride, uint32_t filterSize, bool samePadding, uint32_t * paddingFront, uint32_t * paddingBack) inline
Definition at line 405 of file TfParser.cpp.
Referenced by CalcPadding().
{
     *paddingFront = 0;
     *paddingBack = 0;
     if (samePadding) {
         uint32_t outputSize = (inputSize + stride - 1) / stride;
         uint32_t temp = (outputSize - 1) * stride + filterSize;
         if (temp > inputSize) {
             *paddingFront = (temp - inputSize) / 2;
             *paddingBack = (temp - inputSize) - *paddingFront;
         }
     }
 }
CheckPaddingTensor()
unsigned int armnnTfParser::CheckPaddingTensor (const ConstTensor & paddingTensor, const TensorInfo & inputTensorInfo, const std::string & nodeName)
Definition at line 2106 of file TfParser.cpp.
References CHECK_LOCATION, TensorInfo::GetNumDimensions(), and BaseTensor< MemoryType >::GetShape().
Referenced by CalculatePaddedOutputTensorInfo().
 {
     unsigned int rank = paddingTensor.GetShape()[0];
     unsigned int expectedRank = inputTensorInfo.GetNumDimensions();
     if (rank != expectedRank)
     {
         throw ParseException(
                 boost::str(
                         boost::format(
                                 "Expected the padding tensor to be of rank %1 not %2 on Node %3 %4.")
                         % expectedRank
                         % rank
                         % nodeName
                         % CHECK_LOCATION().AsString()));
     }
     unsigned int second = paddingTensor.GetShape()[1];
     if (second != 2)
     {
         throw ParseException(
                 boost::str(
                         boost::format(
                                 "Expected the padding tensor to be of dimensions [%1, 2] not [%1, %2] on Node %3 %4.")
                         % rank
                         % second
                         % nodeName
                         % CHECK_LOCATION().AsString()));
     }
     return rank;
 }
ConvertTfTensorDataType()
DataType armnnTfParser::ConvertTfTensorDataType (const tensorflow::DataType tfDataType, const tensorflow::NodeDef & nodeDef)
Definition at line 933 of file TfParser.cpp.
References INetwork::AddConvolution2dLayer(), INetwork::AddDepthwiseConvolution2dLayer(), CalcPadding(), CHECK_DATA_FORMAT, CHECK_LOCATION, CHECK_PADDING_TYPE, IOutputSlot::Connect(), armnn::GetDataTypeSize(), DataLayoutIndexed::GetHeightIndex(), IConnectableLayer::GetInputSlot(), TensorInfo::GetNumElements(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), BaseTensor< MemoryType >::GetShape(), IOutputSlot::GetTensorInfo(), DataLayoutIndexed::GetWidthIndex(), armnn::IgnoreUnused(), Convolution2dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, Convolution2dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, DepthwiseConvolution2dDescriptor::m_StrideY, armnnUtils::Permute(), armnnUtils::Permuted(), and IOutputSlot::SetTensorInfo().
 {
     switch (tfDataType)
     {
     case tensorflow::DT_FLOAT:
         return DataType::Float32;
         break;
     case tensorflow::DT_INT32:
         return DataType::Signed32;
         break;
     default:
         throw ParseException(
             boost::str(
                 boost::format(
                     "Unknown DataType %1% for node %2% %3%")
                     % tensorflow::DataType_Name(tfDataType)
                     % nodeDef.name()
                     % CHECK_LOCATION().AsString()));
     }
 }
OutputShapeOfExpandDims()
TensorInfo armnnTfParser::OutputShapeOfExpandDims (const tensorflow::NodeDef & nodeDef, TensorInfo inputTensorInfo)
Definition at line 1468 of file TfParser.cpp.
References INetwork::AddActivationLayer(), INetwork::AddBatchNormalizationLayer(), INetwork::AddComparisonLayer(), INetwork::AddGatherLayer(), INetwork::AddMinimumLayer(), INetwork::AddReshapeLayer(), INetwork::AddStackLayer(), INetwork::AddSubtractionLayer(), INetwork::AddTransposeLayer(), CHECK_DATA_FORMAT, CHECK_LOCATION, IOutputSlot::Connect(), TensorInfo::GetDataType(), IConnectableLayer::GetInputSlot(), TensorShape::GetNumDimensions(), TensorInfo::GetNumDimensions(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), armnn::IgnoreUnused(), ActivationDescriptor::m_A, StackDescriptor::m_Axis, BatchNormalizationDescriptor::m_DataLayout, BatchNormalizationDescriptor::m_Eps, ActivationDescriptor::m_Function, WithOutputTensorIndex< T >::m_Index, WithOutputTensorIndex< T >::m_IndexedValue, StackDescriptor::m_InputShape, StackDescriptor::m_NumInputs, ReshapeDescriptor::m_TargetShape, armnn::numeric_cast(), TensorInfo::SetDataType(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), and armnnUtils::TransposeTensorShape().
 {
     BOOST_ASSERT(nodeDef.op() == "ExpandDims");
     if (inputTensorInfo.GetNumDimensions() > 4) {
         throw ParseException(
                 boost::str(
                         boost::format(
                                 "Unsupported number of dimensions: %1% for input shape for ExpandDims %2% %3%")
                         % inputTensorInfo.GetNumDimensions()
                         % nodeDef.name()
                         % CHECK_LOCATION().AsString()));
     }
     std::int32_t expandDim = ReadMandatoryNodeInt32Attribute(nodeDef, "Tdim");
     std::int32_t inputDimSize = boost::numeric_cast<int32_t>(inputTensorInfo.GetNumDimensions());
     std::vector<uint32_t> outputDims;
     // expandDim operation requires: -1-input.dims() <= dim <= input.dims()
     if (expandDim >= -1 - inputDimSize && expandDim <= inputDimSize)
     {
         // add current input shape to outputDims
         for (unsigned int i = 0; i < inputTensorInfo.GetNumDimensions(); ++i) {
             auto currentDimension = inputTensorInfo.GetShape()[i];
             outputDims.push_back(currentDimension);
         }
         // insert a dimension of 1 at index 'expandDim' of inputs shape
         if (expandDim >= 0)
         {
             auto getPosition = std::next(outputDims.begin() + 0, expandDim);
             outputDims.insert(getPosition, 1);
         }
         // if negative number for 'expandDim' then count backwards from the last element
         // and insert 1 dimension at index 'expandDim'
         if (expandDim < 0)
         {
             int outputDimSize = boost::numeric_cast<int>(outputDims.size() + 1);
             auto getPosition = std::next(outputDims.begin() + outputDimSize, expandDim);
             outputDims.insert(getPosition, 1);
         }
     }
     else
     {
         throw InvalidArgumentException(
                 boost::str(
                         boost::format(
                                 "Cannot expand dimension %1% in input tensor with %2% dimension %3%")
                         % expandDim
                         % inputDimSize
                         % CHECK_LOCATION().AsString()));
     }
     if (outputDims.size() > 4)
     {
         throw ParseException(
                 boost::str(
                         boost::format(
                                 "Unsupported number of dimensions: %1% for output shape for ExpandDims %2% %3%")
                         % outputDims.size()
                         % nodeDef.name()
                         % CHECK_LOCATION().AsString()));
     }
     TensorShape outShape = TensorShape(static_cast<unsigned int>(outputDims.size()),
                                        outputDims.data());
     TensorInfo outTensorInfo = inputTensorInfo;
     outTensorInfo.SetShape(outShape);
     return outTensorInfo;
 }
OutputShapeOfSqueeze()
TensorInfo armnnTfParser::OutputShapeOfSqueeze (const tensorflow::NodeDef & nodeDef, TensorInfo inputTensorInfo)
Definition at line 2463 of file TfParser.cpp.
References INetwork::AddActivationLayer(), INetwork::AddAdditionLayer(), INetwork::AddDivisionLayer(), INetwork::AddElementwiseUnaryLayer(), INetwork::AddFullyConnectedLayer(), INetwork::AddInputLayer(), INetwork::AddMaximumLayer(), INetwork::AddMeanLayer(), INetwork::AddMultiplicationLayer(), INetwork::AddNormalizationLayer(), INetwork::AddOutputLayer(), INetwork::AddPooling2dLayer(), INetwork::AddReshapeLayer(), INetwork::AddSoftmaxLayer(), INetwork::AddSplitterLayer(), INetwork::AddStridedSliceLayer(), CalcPadding(), armnnUtils::CalculateReducedOutputTensoInfo(), armnnUtils::CalculateStridedSliceOutputTensorInfo(), CHECK_DATA_FORMAT, CHECK_LOCATION, CHECK_PADDING_TYPE, IOutputSlot::Connect(), TensorInfo::GetDataType(), DataLayoutIndexed::GetHeightIndex(), IConnectableLayer::GetInputSlot(), TensorShape::GetNumDimensions(), TensorInfo::GetNumDimensions(), IConnectableLayer::GetNumOutputSlots(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), BaseTensor< MemoryType >::GetShape(), IOutputSlot::GetTensorInfo(), DataLayoutIndexed::GetWidthIndex(), armnn::IgnoreUnused(), ActivationDescriptor::m_A, NormalizationDescriptor::m_Alpha, MeanDescriptor::m_Axis, ActivationDescriptor::m_B, StridedSliceDescriptor::m_Begin, StridedSliceDescriptor::m_BeginMask, NormalizationDescriptor::m_Beta, FullyConnectedDescriptor::m_BiasEnabled, Pooling2dDescriptor::m_DataLayout, NormalizationDescriptor::m_DataLayout, StridedSliceDescriptor::m_DataLayout, StridedSliceDescriptor::m_EllipsisMask, StridedSliceDescriptor::m_End, StridedSliceDescriptor::m_EndMask, ActivationDescriptor::m_Function, NormalizationDescriptor::m_K, MeanDescriptor::m_KeepDims, m_Layer, StridedSliceDescriptor::m_NewAxisMask, NormalizationDescriptor::m_NormChannelType, NormalizationDescriptor::m_NormMethodType, NormalizationDescriptor::m_NormSize, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, StridedSliceDescriptor::m_ShrinkAxisMask, StridedSliceDescriptor::m_Stride, Pooling2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, ReshapeDescriptor::m_TargetShape, armnn::NHWC, armnn::numeric_cast(), TfParser::ParsedMatMulTfOperation, TfParser::ParsedMulTfOperation, TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), ViewsDescriptor::SetViewOriginCoord(), and ViewsDescriptor::SetViewSize().
 {
     BOOST_ASSERT(nodeDef.op() == "Squeeze");
     tensorflow::DataType tfDataType = ReadMandatoryNodeTypeAttribute(nodeDef, "T");
     DataType type;
     if (tfDataType == tensorflow::DT_FLOAT)
     {
         type = DataType::Float32;
     }
     else if (tfDataType == tensorflow::DT_INT32)
     {
         type = DataType::Signed32;
     }
     else
     {
         throw ParseException(
             boost::str(
                 boost::format("Unsupported DataType %1% for Squeeze operation %2% %3%")
                 % tensorflow::DataType_Name(tfDataType)
                 % nodeDef.name()
                 % CHECK_LOCATION().AsString()));
     }
     if (inputTensorInfo.GetNumDimensions() > 4)
     {
         throw ParseException(
             boost::str(
                 boost::format(
                     "Unsupported number of dimensions: %1% for input shape for Squeeze %2% %3%")
                     % inputTensorInfo.GetNumDimensions()
                     % nodeDef.name()
                     % CHECK_LOCATION().AsString()));
     }
     std::vector<uint32_t> squeezeDims = ReadOptionalNodeUint32ListAttribute(nodeDef, "squeeze_dims");
     static const uint32_t dimensionSequence[] = { 0, 1, 2, 3 };
     if (squeezeDims.empty())
     {
         squeezeDims.assign(dimensionSequence,
                            dimensionSequence+inputTensorInfo.GetNumDimensions());
     }
     std::vector<uint32_t> outputDims;
     for(unsigned int i = 0; i < inputTensorInfo.GetNumDimensions(); i++)
     {
         bool skipSqueeze = (std::find(squeezeDims.begin(), squeezeDims.end(), i) == squeezeDims.end());
         auto currentDimension = inputTensorInfo.GetShape()[i];
         if (skipSqueeze || currentDimension != 1)
         {
             outputDims.push_back(currentDimension);
         }
     }
     if (outputDims.size() > 4)
     {
         throw ParseException(
             boost::str(
                 boost::format(
                     "Unsupported number of dimensions: %1% for output shape for Squeeze %2% %3%")
                     % outputDims.size()
                     % nodeDef.name()
                     % CHECK_LOCATION().AsString()));
     }
     TensorShape outShape = TensorShape(static_cast<unsigned int>(outputDims.size()),
                                        outputDims.data());
     TensorInfo outTensorInfo = inputTensorInfo;
     outTensorInfo.SetShape(outShape);
     outTensorInfo.SetDataType(type);
     return outTensorInfo;
 }