ArmNN: armnn::gatordmock Namespace Reference
armnn::gatordmock Namespace Reference
Classes
struct CategoryRecord
class CommandFileParser
This class parses a command file for the GatordMockService.
class CommandLineProcessor
Use Boost program options to process the command line.
struct CounterCaptureValues
struct CounterDirectory
struct CounterSetRecord
struct DeviceRecord
struct EventRecord
class GatordMockService
A class that implements a Mock Gatord server.
struct PacketVersion
class PeriodicCounterCaptureCommandHandler
class PeriodicCounterSelectionResponseHandler
class StreamMetadataCommandHandler
Enumerations
enum TargetEndianness { BeWire, LeWire }
enum PacketDirection { Sending, ReceivedHeader, ReceivedData }
Functions
std::string ReadString (const unsigned char *buffer, unsigned int &offset)
Enumeration Type Documentation
PacketDirection
enum PacketDirection strong
Enumerator
Sending
ReceivedHeader
ReceivedData
Definition at line 28 of file GatordMockService.hpp.
 {
     Sending,
     ReceivedHeader,
     ReceivedData
 };
TargetEndianness
enum TargetEndianness strong
Enumerator
BeWire
LeWire
Definition at line 22 of file GatordMockService.hpp.
 {
     BeWire,
     LeWire
 };
Function Documentation
ReadString()
std::string armnn::gatordmock::ReadString (const unsigned char * buffer, unsigned int & offset)
Definition at line 57 of file StreamMetadataCommandHandler.cpp.
References Packet::GetData(), Packet::GetLength(), armnn::profiling::ReadUint16(), armnn::profiling::ReadUint32(), armnn::profiling::uint16_t_size, and armnn::profiling::uint32_t_size.
 {
     const char* stringPtr = reinterpret_cast<const char*>(&buffer[offset]);
     return stringPtr != nullptr ? std::string(stringPtr) : "";
 }