var searchData=
[
  ['capability',['Capability',['../structarmnn_1_1_capability.xhtml',1,'armnn']]],
  ['capturedata',['CaptureData',['../classarmnn_1_1profiling_1_1_capture_data.xhtml',1,'armnn::profiling']]],
  ['castlayer',['CastLayer',['../classarmnn_1_1_cast_layer.xhtml',1,'armnn']]],
  ['castlayerbuilder',['CastLayerBuilder',['../structarmnn_serializer_1_1_cast_layer_builder.xhtml',1,'armnnSerializer']]],
  ['castqueuedescriptor',['CastQueueDescriptor',['../structarmnn_1_1_cast_queue_descriptor.xhtml',1,'armnn']]],
  ['category',['Category',['../classarmnn_1_1profiling_1_1_category.xhtml',1,'armnn::profiling']]],
  ['categoryrecord',['CategoryRecord',['../structarmnn_1_1gatordmock_1_1_category_record.xhtml',1,'armnn::gatordmock']]],
  ['channelshuffledescriptor',['ChannelShuffleDescriptor',['../structarmnn_1_1_channel_shuffle_descriptor.xhtml',1,'armnn']]],
  ['channelshuffledescriptorbuilder',['ChannelShuffleDescriptorBuilder',['../structarmnn_serializer_1_1_channel_shuffle_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['channelshufflelayer',['ChannelShuffleLayer',['../classarmnn_1_1_channel_shuffle_layer.xhtml',1,'armnn']]],
  ['channelshufflelayerbuilder',['ChannelShuffleLayerBuilder',['../structarmnn_serializer_1_1_channel_shuffle_layer_builder.xhtml',1,'armnnSerializer']]],
  ['channelshufflequeuedescriptor',['ChannelShuffleQueueDescriptor',['../structarmnn_1_1_channel_shuffle_queue_descriptor.xhtml',1,'armnn']]],
  ['checklocation',['CheckLocation',['../structarmnn_1_1_check_location.xhtml',1,'armnn']]],
  ['cifar10database',['Cifar10Database',['../class_cifar10_database.xhtml',1,'']]],
  ['clabsworkload',['ClAbsWorkload',['../classarmnn_1_1_cl_abs_workload.xhtml',1,'armnn']]],
  ['clactivationworkload',['ClActivationWorkload',['../classarmnn_1_1_cl_activation_workload.xhtml',1,'armnn']]],
  ['cladditionworkload',['ClAdditionWorkload',['../classarmnn_1_1_cl_addition_workload.xhtml',1,'armnn']]],
  ['clargminmaxworkload',['ClArgMinMaxWorkload',['../classarmnn_1_1_cl_arg_min_max_workload.xhtml',1,'armnn']]],
  ['classifiertestcase',['ClassifierTestCase',['../classarmnn_1_1test_1_1_classifier_test_case.xhtml',1,'armnn::test']]],
  ['classifiertestcasedata',['ClassifierTestCaseData',['../class_classifier_test_case_data.xhtml',1,'']]],
  ['classifiertestcaseprovider',['ClassifierTestCaseProvider',['../classarmnn_1_1test_1_1_classifier_test_case_provider.xhtml',1,'armnn::test']]],
  ['clbackend',['ClBackend',['../classarmnn_1_1_cl_backend.xhtml',1,'armnn']]],
  ['clbackendcontext',['ClBackendContext',['../classarmnn_1_1_cl_backend_context.xhtml',1,'armnn']]],
  ['clbackendcustomallocatormemoryregion',['ClBackendCustomAllocatorMemoryRegion',['../classarmnn_1_1_cl_backend_1_1_cl_backend_custom_allocator_memory_region.xhtml',1,'armnn::ClBackend']]],
  ['clbackendcustomallocatorwrapper',['ClBackendCustomAllocatorWrapper',['../classarmnn_1_1_cl_backend_1_1_cl_backend_custom_allocator_wrapper.xhtml',1,'armnn::ClBackend']]],
  ['clbackenddefaultallocator',['ClBackendDefaultAllocator',['../classarmnn_1_1_cl_backend_default_allocator.xhtml',1,'armnn']]],
  ['clbackendmodelcontext',['ClBackendModelContext',['../classarmnn_1_1_cl_backend_model_context.xhtml',1,'armnn']]],
  ['clbaseworkload',['ClBaseWorkload',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20absqueuedescriptor_20_3e',['ClBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20activationqueuedescriptor_20_3e',['ClBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20additionqueuedescriptor_20_3e',['ClBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20argminmaxqueuedescriptor_20_3e',['ClBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e',['ClBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20castqueuedescriptor_20_3e',['ClBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20channelshufflequeuedescriptor_20_3e',['ClBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20comparisonqueuedescriptor_20_3e',['ClBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20concatqueuedescriptor_20_3e',['ClBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20constantqueuedescriptor_20_3e',['ClBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20convolution2dqueuedescriptor_20_3e',['ClBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20convolution3dqueuedescriptor_20_3e',['ClBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20depthtospacequeuedescriptor_20_3e',['ClBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e',['ClBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20dequantizequeuedescriptor_20_3e',['ClBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20divisionqueuedescriptor_20_3e',['ClBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e',['ClBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20fillqueuedescriptor_20_3e',['ClBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e',['ClBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20gatherqueuedescriptor_20_3e',['ClBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e',['ClBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e',['ClBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e',['ClBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20maximumqueuedescriptor_20_3e',['ClBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20meanqueuedescriptor_20_3e',['ClBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20minimumqueuedescriptor_20_3e',['ClBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20multiplicationqueuedescriptor_20_3e',['ClBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20padqueuedescriptor_20_3e',['ClBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20permutequeuedescriptor_20_3e',['ClBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20pooling2dqueuedescriptor_20_3e',['ClBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20preluqueuedescriptor_20_3e',['ClBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20qlstmqueuedescriptor_20_3e',['ClBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e',['ClBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20quantizequeuedescriptor_20_3e',['ClBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20rankqueuedescriptor_20_3e',['ClBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20reducequeuedescriptor_20_3e',['ClBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20reshapequeuedescriptor_20_3e',['ClBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20resizequeuedescriptor_20_3e',['ClBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20rsqrtqueuedescriptor_20_3e',['ClBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20slicequeuedescriptor_20_3e',['ClBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20softmaxqueuedescriptor_20_3e',['ClBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e',['ClBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e',['ClBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20splitterqueuedescriptor_20_3e',['ClBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20stackqueuedescriptor_20_3e',['ClBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20stridedslicequeuedescriptor_20_3e',['ClBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20subtractionqueuedescriptor_20_3e',['ClBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e',['ClBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbaseworkload_3c_20transposequeuedescriptor_20_3e',['ClBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_cl_base_workload.xhtml',1,'armnn']]],
  ['clbatchnormalizationfloatworkload',['ClBatchNormalizationFloatWorkload',['../classarmnn_1_1_cl_batch_normalization_float_workload.xhtml',1,'armnn']]],
  ['clbatchtospacendworkload',['ClBatchToSpaceNdWorkload',['../classarmnn_1_1_cl_batch_to_space_nd_workload.xhtml',1,'armnn']]],
  ['clcastworkload',['ClCastWorkload',['../classarmnn_1_1_cl_cast_workload.xhtml',1,'armnn']]],
  ['clchannelshuffleworkload',['ClChannelShuffleWorkload',['../classarmnn_1_1_cl_channel_shuffle_workload.xhtml',1,'armnn']]],
  ['clcomparisonworkload',['ClComparisonWorkload',['../classarmnn_1_1_cl_comparison_workload.xhtml',1,'armnn']]],
  ['clconcatworkload',['ClConcatWorkload',['../classarmnn_1_1_cl_concat_workload.xhtml',1,'armnn']]],
  ['clconstantworkload',['ClConstantWorkload',['../classarmnn_1_1_cl_constant_workload.xhtml',1,'armnn']]],
  ['clcontextbuilder',['ClContextBuilder',['../structarmnn_1_1_cl_context_builder.xhtml',1,'armnn']]],
  ['clcontextcontrol',['ClContextControl',['../classarmnn_1_1_cl_context_control.xhtml',1,'armnn']]],
  ['clcontextcontrolfixturebase',['ClContextControlFixtureBase',['../struct_cl_context_control_fixture_base.xhtml',1,'']]],
  ['clcontextdeserializer',['ClContextDeserializer',['../classarmnn_1_1_cl_context_deserializer.xhtml',1,'armnn']]],
  ['clcontextserializer',['ClContextSerializer',['../classarmnn_1_1_cl_context_serializer.xhtml',1,'armnn']]],
  ['clconvertfp16tofp32workload',['ClConvertFp16ToFp32Workload',['../classarmnn_1_1_cl_convert_fp16_to_fp32_workload.xhtml',1,'armnn']]],
  ['clconvertfp32tofp16workload',['ClConvertFp32ToFp16Workload',['../classarmnn_1_1_cl_convert_fp32_to_fp16_workload.xhtml',1,'armnn']]],
  ['clconvolution2dworkload',['ClConvolution2dWorkload',['../classarmnn_1_1_cl_convolution2d_workload.xhtml',1,'armnn']]],
  ['clconvolution3dworkload',['ClConvolution3dWorkload',['../classarmnn_1_1_cl_convolution3d_workload.xhtml',1,'armnn']]],
  ['cldepthtospaceworkload',['ClDepthToSpaceWorkload',['../classarmnn_1_1_cl_depth_to_space_workload.xhtml',1,'armnn']]],
  ['cldepthwiseconvolutionworkload',['ClDepthwiseConvolutionWorkload',['../classarmnn_1_1_cl_depthwise_convolution_workload.xhtml',1,'armnn']]],
  ['cldequantizeworkload',['ClDequantizeWorkload',['../classarmnn_1_1_cl_dequantize_workload.xhtml',1,'armnn']]],
  ['cldivisionworkload',['ClDivisionWorkload',['../classarmnn_1_1_cl_division_workload.xhtml',1,'armnn']]],
  ['clexpworkload',['ClExpWorkload',['../classarmnn_1_1_cl_exp_workload.xhtml',1,'armnn']]],
  ['clfillworkload',['ClFillWorkload',['../classarmnn_1_1_cl_fill_workload.xhtml',1,'armnn']]],
  ['clfloorfloatworkload',['ClFloorFloatWorkload',['../classarmnn_1_1_cl_floor_float_workload.xhtml',1,'armnn']]],
  ['clfullyconnectedworkload',['ClFullyConnectedWorkload',['../classarmnn_1_1_cl_fully_connected_workload.xhtml',1,'armnn']]],
  ['clgatherworkload',['ClGatherWorkload',['../classarmnn_1_1_cl_gather_workload.xhtml',1,'armnn']]],
  ['climportsubtensorhandle',['ClImportSubTensorHandle',['../classarmnn_1_1_cl_import_sub_tensor_handle.xhtml',1,'armnn']]],
  ['climporttensorhandle',['ClImportTensorHandle',['../classarmnn_1_1_cl_import_tensor_handle.xhtml',1,'armnn']]],
  ['climporttensorhandlefactory',['ClImportTensorHandleFactory',['../classarmnn_1_1_cl_import_tensor_handle_factory.xhtml',1,'armnn']]],
  ['clinstancenormalizationworkload',['ClInstanceNormalizationWorkload',['../classarmnn_1_1_cl_instance_normalization_workload.xhtml',1,'armnn']]],
  ['cll2normalizationfloatworkload',['ClL2NormalizationFloatWorkload',['../classarmnn_1_1_cl_l2_normalization_float_workload.xhtml',1,'armnn']]],
  ['cllayersupport',['ClLayerSupport',['../classarmnn_1_1_cl_layer_support.xhtml',1,'armnn']]],
  ['cllogicalandworkload',['ClLogicalAndWorkload',['../classarmnn_1_1_cl_logical_and_workload.xhtml',1,'armnn']]],
  ['cllogicalnotworkload',['ClLogicalNotWorkload',['../classarmnn_1_1_cl_logical_not_workload.xhtml',1,'armnn']]],
  ['cllogicalorworkload',['ClLogicalOrWorkload',['../classarmnn_1_1_cl_logical_or_workload.xhtml',1,'armnn']]],
  ['cllogsoftmaxworkload',['ClLogSoftmaxWorkload',['../classarmnn_1_1_cl_log_softmax_workload.xhtml',1,'armnn']]],
  ['cllogworkload',['ClLogWorkload',['../classarmnn_1_1_cl_log_workload.xhtml',1,'armnn']]],
  ['cllstmfloatworkload',['ClLstmFloatWorkload',['../classarmnn_1_1_cl_lstm_float_workload.xhtml',1,'armnn']]],
  ['clmaximumworkload',['ClMaximumWorkload',['../classarmnn_1_1_cl_maximum_workload.xhtml',1,'armnn']]],
  ['clmeanworkload',['ClMeanWorkload',['../classarmnn_1_1_cl_mean_workload.xhtml',1,'armnn']]],
  ['clmemorymanager',['ClMemoryManager',['../classarmnn_1_1_cl_memory_manager.xhtml',1,'armnn']]],
  ['clminimumworkload',['ClMinimumWorkload',['../classarmnn_1_1_cl_minimum_workload.xhtml',1,'armnn']]],
  ['clmultiplicationworkload',['ClMultiplicationWorkload',['../classarmnn_1_1_cl_multiplication_workload.xhtml',1,'armnn']]],
  ['clnegworkload',['ClNegWorkload',['../classarmnn_1_1_cl_neg_workload.xhtml',1,'armnn']]],
  ['clnormalizationfloatworkload',['ClNormalizationFloatWorkload',['../classarmnn_1_1_cl_normalization_float_workload.xhtml',1,'armnn']]],
  ['clpadworkload',['ClPadWorkload',['../classarmnn_1_1_cl_pad_workload.xhtml',1,'armnn']]],
  ['clpermuteworkload',['ClPermuteWorkload',['../classarmnn_1_1_cl_permute_workload.xhtml',1,'armnn']]],
  ['clpooling2dworkload',['ClPooling2dWorkload',['../classarmnn_1_1_cl_pooling2d_workload.xhtml',1,'armnn']]],
  ['clpreluworkload',['ClPreluWorkload',['../classarmnn_1_1_cl_prelu_workload.xhtml',1,'armnn']]],
  ['clqlstmworkload',['ClQLstmWorkload',['../classarmnn_1_1_cl_q_lstm_workload.xhtml',1,'armnn']]],
  ['clquantizedlstmworkload',['ClQuantizedLstmWorkload',['../classarmnn_1_1_cl_quantized_lstm_workload.xhtml',1,'armnn']]],
  ['clquantizeworkload',['ClQuantizeWorkload',['../classarmnn_1_1_cl_quantize_workload.xhtml',1,'armnn']]],
  ['clrankworkload',['ClRankWorkload',['../structarmnn_1_1_cl_rank_workload.xhtml',1,'armnn']]],
  ['clreduceworkload',['ClReduceWorkload',['../classarmnn_1_1_cl_reduce_workload.xhtml',1,'armnn']]],
  ['clreshapeworkload',['ClReshapeWorkload',['../classarmnn_1_1_cl_reshape_workload.xhtml',1,'armnn']]],
  ['clresizeworkload',['ClResizeWorkload',['../classarmnn_1_1_cl_resize_workload.xhtml',1,'armnn']]],
  ['clrsqrtworkload',['ClRsqrtWorkload',['../classarmnn_1_1_cl_rsqrt_workload.xhtml',1,'armnn']]],
  ['clruntimeunavailableexception',['ClRuntimeUnavailableException',['../classarmnn_1_1_cl_runtime_unavailable_exception.xhtml',1,'armnn']]],
  ['clsinworkload',['ClSinWorkload',['../classarmnn_1_1_cl_sin_workload.xhtml',1,'armnn']]],
  ['clsliceworkload',['ClSliceWorkload',['../classarmnn_1_1_cl_slice_workload.xhtml',1,'armnn']]],
  ['clsoftmaxworkload',['ClSoftmaxWorkload',['../classarmnn_1_1_cl_softmax_workload.xhtml',1,'armnn']]],
  ['clspacetobatchndworkload',['ClSpaceToBatchNdWorkload',['../classarmnn_1_1_cl_space_to_batch_nd_workload.xhtml',1,'armnn']]],
  ['clspacetodepthworkload',['ClSpaceToDepthWorkload',['../classarmnn_1_1_cl_space_to_depth_workload.xhtml',1,'armnn']]],
  ['clsplitterworkload',['ClSplitterWorkload',['../classarmnn_1_1_cl_splitter_workload.xhtml',1,'armnn']]],
  ['clstackworkload',['ClStackWorkload',['../classarmnn_1_1_cl_stack_workload.xhtml',1,'armnn']]],
  ['clstridedsliceworkload',['ClStridedSliceWorkload',['../classarmnn_1_1_cl_strided_slice_workload.xhtml',1,'armnn']]],
  ['clsubtensorhandle',['ClSubTensorHandle',['../classarmnn_1_1_cl_sub_tensor_handle.xhtml',1,'armnn']]],
  ['clsubtractionworkload',['ClSubtractionWorkload',['../classarmnn_1_1_cl_subtraction_workload.xhtml',1,'armnn']]],
  ['cltensorhandle',['ClTensorHandle',['../classarmnn_1_1_cl_tensor_handle.xhtml',1,'armnn']]],
  ['cltensorhandlefactory',['ClTensorHandleFactory',['../classarmnn_1_1_cl_tensor_handle_factory.xhtml',1,'armnn']]],
  ['cltransposeconvolution2dworkload',['ClTransposeConvolution2dWorkload',['../classarmnn_1_1_cl_transpose_convolution2d_workload.xhtml',1,'armnn']]],
  ['cltransposeworkload',['ClTransposeWorkload',['../classarmnn_1_1_cl_transpose_workload.xhtml',1,'armnn']]],
  ['cltunedparameters',['ClTunedParameters',['../classarmnn_1_1_cl_tuned_parameters.xhtml',1,'armnn']]],
  ['clworkloadfactory',['ClWorkloadFactory',['../classarmnn_1_1_cl_workload_factory.xhtml',1,'armnn']]],
  ['commandfileparser',['CommandFileParser',['../classarmnn_1_1gatordmock_1_1_command_file_parser.xhtml',1,'armnn::gatordmock']]],
  ['commandhandler',['CommandHandler',['../classarmnn_1_1profiling_1_1_command_handler.xhtml',1,'armnn::profiling']]],
  ['commandlineoptions',['CommandLineOptions',['../struct_inference_model_1_1_command_line_options.xhtml',1,'InferenceModel']]],
  ['commandlineprocessor',['CommandLineProcessor',['../classarmnn_1_1gatordmock_1_1_command_line_processor.xhtml',1,'armnn::gatordmock']]],
  ['comparisondescriptor',['ComparisonDescriptor',['../structarmnn_1_1_comparison_descriptor.xhtml',1,'armnn']]],
  ['comparisondescriptorbuilder',['ComparisonDescriptorBuilder',['../structarmnn_serializer_1_1_comparison_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['comparisonlayer',['ComparisonLayer',['../classarmnn_1_1_comparison_layer.xhtml',1,'armnn']]],
  ['comparisonlayerbuilder',['ComparisonLayerBuilder',['../structarmnn_serializer_1_1_comparison_layer_builder.xhtml',1,'armnnSerializer']]],
  ['comparisonqueuedescriptor',['ComparisonQueueDescriptor',['../structarmnn_1_1_comparison_queue_descriptor.xhtml',1,'armnn']]],
  ['concatlayer',['ConcatLayer',['../classarmnn_1_1_concat_layer.xhtml',1,'armnn']]],
  ['concatlayerbuilder',['ConcatLayerBuilder',['../structarmnn_serializer_1_1_concat_layer_builder.xhtml',1,'armnnSerializer']]],
  ['concatqueuedescriptor',['ConcatQueueDescriptor',['../structarmnn_1_1_concat_queue_descriptor.xhtml',1,'armnn']]],
  ['connection',['Connection',['../classarmnn_1_1profiling_1_1_connection.xhtml',1,'armnn::profiling']]],
  ['connectionacknowledgedcommandhandler',['ConnectionAcknowledgedCommandHandler',['../classarmnn_1_1profiling_1_1_connection_acknowledged_command_handler.xhtml',1,'armnn::profiling']]],
  ['constantlayer',['ConstantLayer',['../classarmnn_1_1_constant_layer.xhtml',1,'armnn']]],
  ['constantlayerbuilder',['ConstantLayerBuilder',['../structarmnn_serializer_1_1_constant_layer_builder.xhtml',1,'armnnSerializer']]],
  ['constantmemorystrategy',['ConstantMemoryStrategy',['../classarmnn_1_1_constant_memory_strategy.xhtml',1,'armnn']]],
  ['constantqueuedescriptor',['ConstantQueueDescriptor',['../structarmnn_1_1_constant_queue_descriptor.xhtml',1,'armnn']]],
  ['constpassthroughtensorhandle',['ConstPassthroughTensorHandle',['../classarmnn_1_1_const_passthrough_tensor_handle.xhtml',1,'armnn']]],
  ['constructinplace',['ConstructInPlace',['../structarmnn_1_1_construct_in_place.xhtml',1,'armnn']]],
  ['consttensor',['ConstTensor',['../classarmnn_1_1_const_tensor.xhtml',1,'armnn']]],
  ['consttensorbuilder',['ConstTensorBuilder',['../structarmnn_serializer_1_1_const_tensor_builder.xhtml',1,'armnnSerializer']]],
  ['consttensordatatraits',['ConstTensorDataTraits',['../structarmnn_serializer_1_1_const_tensor_data_traits.xhtml',1,'armnnSerializer']]],
  ['consttensordatatraits_3c_20armnnserializer_3a_3abytedata_20_3e',['ConstTensorDataTraits&lt; armnnSerializer::ByteData &gt;',['../structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_byte_data_01_4.xhtml',1,'armnnSerializer']]],
  ['consttensordatatraits_3c_20armnnserializer_3a_3aintdata_20_3e',['ConstTensorDataTraits&lt; armnnSerializer::IntData &gt;',['../structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_int_data_01_4.xhtml',1,'armnnSerializer']]],
  ['consttensordatatraits_3c_20armnnserializer_3a_3alongdata_20_3e',['ConstTensorDataTraits&lt; armnnSerializer::LongData &gt;',['../structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_long_data_01_4.xhtml',1,'armnnSerializer']]],
  ['consttensordatatraits_3c_20armnnserializer_3a_3ashortdata_20_3e',['ConstTensorDataTraits&lt; armnnSerializer::ShortData &gt;',['../structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_short_data_01_4.xhtml',1,'armnnSerializer']]],
  ['consttensorhandle',['ConstTensorHandle',['../classarmnn_1_1_const_tensor_handle.xhtml',1,'armnn']]],
  ['convertbf16tofp32layer',['ConvertBf16ToFp32Layer',['../classarmnn_1_1_convert_bf16_to_fp32_layer.xhtml',1,'armnn']]],
  ['convertbf16tofp32queuedescriptor',['ConvertBf16ToFp32QueueDescriptor',['../structarmnn_1_1_convert_bf16_to_fp32_queue_descriptor.xhtml',1,'armnn']]],
  ['convertconstants',['ConvertConstants',['../classarmnn_1_1optimizations_1_1_convert_constants.xhtml',1,'armnn::optimizations']]],
  ['convertfp16tofp32layer',['ConvertFp16ToFp32Layer',['../classarmnn_1_1_convert_fp16_to_fp32_layer.xhtml',1,'armnn']]],
  ['convertfp16tofp32queuedescriptor',['ConvertFp16ToFp32QueueDescriptor',['../structarmnn_1_1_convert_fp16_to_fp32_queue_descriptor.xhtml',1,'armnn']]],
  ['convertfp32networktobf16impl',['ConvertFp32NetworkToBf16Impl',['../classarmnn_1_1optimizations_1_1_convert_fp32_network_to_bf16_impl.xhtml',1,'armnn::optimizations']]],
  ['convertfp32networktofp16impl',['ConvertFp32NetworkToFp16Impl',['../classarmnn_1_1optimizations_1_1_convert_fp32_network_to_fp16_impl.xhtml',1,'armnn::optimizations']]],
  ['convertfp32tobf16layer',['ConvertFp32ToBf16Layer',['../classarmnn_1_1_convert_fp32_to_bf16_layer.xhtml',1,'armnn']]],
  ['convertfp32tobf16queuedescriptor',['ConvertFp32ToBf16QueueDescriptor',['../structarmnn_1_1_convert_fp32_to_bf16_queue_descriptor.xhtml',1,'armnn']]],
  ['convertfp32tofp16layer',['ConvertFp32ToFp16Layer',['../classarmnn_1_1_convert_fp32_to_fp16_layer.xhtml',1,'armnn']]],
  ['convertfp32tofp16queuedescriptor',['ConvertFp32ToFp16QueueDescriptor',['../structarmnn_1_1_convert_fp32_to_fp16_queue_descriptor.xhtml',1,'armnn']]],
  ['convolution2ddescriptor',['Convolution2dDescriptor',['../structarmnn_1_1_convolution2d_descriptor.xhtml',1,'armnn']]],
  ['convolution2ddescriptorbuilder',['Convolution2dDescriptorBuilder',['../structarmnn_serializer_1_1_convolution2d_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['convolution2dlayer',['Convolution2dLayer',['../classarmnn_1_1_convolution2d_layer.xhtml',1,'armnn']]],
  ['convolution2dlayerbuilder',['Convolution2dLayerBuilder',['../structarmnn_serializer_1_1_convolution2d_layer_builder.xhtml',1,'armnnSerializer']]],
  ['convolution2dqueuedescriptor',['Convolution2dQueueDescriptor',['../structarmnn_1_1_convolution2d_queue_descriptor.xhtml',1,'armnn']]],
  ['convolution3ddescriptor',['Convolution3dDescriptor',['../structarmnn_1_1_convolution3d_descriptor.xhtml',1,'armnn']]],
  ['convolution3ddescriptorbuilder',['Convolution3dDescriptorBuilder',['../structarmnn_serializer_1_1_convolution3d_descriptor_builder.xhtml',1,'armnnSerializer']]],
  ['convolution3dlayer',['Convolution3dLayer',['../classarmnn_1_1_convolution3d_layer.xhtml',1,'armnn']]],
  ['convolution3dlayerbuilder',['Convolution3dLayerBuilder',['../structarmnn_serializer_1_1_convolution3d_layer_builder.xhtml',1,'armnnSerializer']]],
  ['convolution3dqueuedescriptor',['Convolution3dQueueDescriptor',['../structarmnn_1_1_convolution3d_queue_descriptor.xhtml',1,'armnn']]],
  ['copymemgenericworkload',['CopyMemGenericWorkload',['../classarmnn_1_1_copy_mem_generic_workload.xhtml',1,'armnn']]],
  ['counter',['Counter',['../classarmnn_1_1profiling_1_1_counter.xhtml',1,'armnn::profiling']]],
  ['countercapturevalues',['CounterCaptureValues',['../structarmnn_1_1gatordmock_1_1_counter_capture_values.xhtml',1,'armnn::gatordmock']]],
  ['counterdirectory',['CounterDirectory',['../classarmnn_1_1profiling_1_1_counter_directory.xhtml',1,'CounterDirectory'],['../structarmnn_1_1gatordmock_1_1_counter_directory.xhtml',1,'CounterDirectory']]],
  ['counterdirectoryeventrecord',['CounterDirectoryEventRecord',['../structarmnn_1_1profiling_1_1_counter_directory_event_record.xhtml',1,'armnn::profiling']]],
  ['counteridmap',['CounterIdMap',['../classarmnn_1_1profiling_1_1_counter_id_map.xhtml',1,'armnn::profiling']]],
  ['counterset',['CounterSet',['../classarmnn_1_1profiling_1_1_counter_set.xhtml',1,'armnn::profiling']]],
  ['countersetrecord',['CounterSetRecord',['../structarmnn_1_1gatordmock_1_1_counter_set_record.xhtml',1,'armnn::gatordmock']]],
  ['counterstatus',['CounterStatus',['../structarmnn_1_1profiling_1_1_counter_status.xhtml',1,'armnn::profiling']]],
  ['countervalue',['CounterValue',['../structarmnn_1_1profiling_1_1_counter_value.xhtml',1,'armnn::profiling']]],
  ['createnetworkimpl',['CreateNetworkImpl',['../struct_create_network_impl.xhtml',1,'']]],
  ['creationoptions',['CreationOptions',['../structarmnn_1_1_i_runtime_1_1_creation_options.xhtml',1,'armnn::IRuntime']]]
];
