var searchData=
[
  ['l2normalizationdescriptor_5784',['L2NormalizationDescriptor',['../structarmnn_1_1_l2_normalization_descriptor.html',1,'armnn']]],
  ['l2normalizationlayer_5785',['L2NormalizationLayer',['../classarmnn_1_1_l2_normalization_layer.html',1,'armnn']]],
  ['l2normalizationqueuedescriptor_5786',['L2NormalizationQueueDescriptor',['../structarmnn_1_1_l2_normalization_queue_descriptor.html',1,'armnn']]],
  ['layer_5787',['Layer',['../classarmnn_1_1_layer.html',1,'armnn']]],
  ['layeringraph_3c_20constantlayer_20_3e_5788',['LayerInGraph&lt; ConstantLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_constant_layer_01_4.html',1,'armnn::Graph']]],
  ['layeringraph_3c_20inputlayer_20_3e_5789',['LayerInGraph&lt; InputLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_input_layer_01_4.html',1,'armnn::Graph']]],
  ['layeringraph_3c_20outputlayer_20_3e_5790',['LayerInGraph&lt; OutputLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_output_layer_01_4.html',1,'armnn::Graph']]],
  ['layerinputhandle_5791',['LayerInputHandle',['../classarmnn__driver_1_1_layer_input_handle.html',1,'armnn_driver']]],
  ['layernameandtypecheck_5792',['LayerNameAndTypeCheck',['../class_layer_name_and_type_check.html',1,'']]],
  ['layersupportbase_5793',['LayerSupportBase',['../classarmnn_1_1_layer_support_base.html',1,'armnn']]],
  ['layersupporthandle_5794',['LayerSupportHandle',['../classarmnn_1_1_layer_support_handle.html',1,'armnn']]],
  ['layertypeofimpl_5795',['LayerTypeOfImpl',['../structarmnn_1_1_layer_type_of_impl.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aactivation_20_3e_5796',['LayerTypeOfImpl&lt; LayerType::Activation &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_activation_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aaddition_20_3e_5797',['LayerTypeOfImpl&lt; LayerType::Addition &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_addition_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aargminmax_20_3e_5798',['LayerTypeOfImpl&lt; LayerType::ArgMinMax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_arg_min_max_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchmatmul_20_3e_5799',['LayerTypeOfImpl&lt; LayerType::BatchMatMul &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_mat_mul_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchnormalization_20_3e_5800',['LayerTypeOfImpl&lt; LayerType::BatchNormalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchtospacend_20_3e_5801',['LayerTypeOfImpl&lt; LayerType::BatchToSpaceNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_to_space_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abroadcastto_20_3e_5802',['LayerTypeOfImpl&lt; LayerType::BroadcastTo &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_broadcast_to_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3acast_20_3e_5803',['LayerTypeOfImpl&lt; LayerType::Cast &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_cast_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3achannelshuffle_20_3e_5804',['LayerTypeOfImpl&lt; LayerType::ChannelShuffle &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_channel_shuffle_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3acomparison_20_3e_5805',['LayerTypeOfImpl&lt; LayerType::Comparison &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_comparison_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconcat_20_3e_5806',['LayerTypeOfImpl&lt; LayerType::Concat &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_concat_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconstant_20_3e_5807',['LayerTypeOfImpl&lt; LayerType::Constant &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_constant_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp16tofp32_20_3e_5808',['LayerTypeOfImpl&lt; LayerType::ConvertFp16ToFp32 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp16_to_fp32_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp32tofp16_20_3e_5809',['LayerTypeOfImpl&lt; LayerType::ConvertFp32ToFp16 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp32_to_fp16_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvolution2d_20_3e_5810',['LayerTypeOfImpl&lt; LayerType::Convolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convolution2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvolution3d_20_3e_5811',['LayerTypeOfImpl&lt; LayerType::Convolution3d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convolution3d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adebug_20_3e_5812',['LayerTypeOfImpl&lt; LayerType::Debug &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_debug_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adepthtospace_20_3e_5813',['LayerTypeOfImpl&lt; LayerType::DepthToSpace &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_depth_to_space_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adepthwiseconvolution2d_20_3e_5814',['LayerTypeOfImpl&lt; LayerType::DepthwiseConvolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_depthwise_convolution2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adequantize_20_3e_5815',['LayerTypeOfImpl&lt; LayerType::Dequantize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_dequantize_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adetectionpostprocess_20_3e_5816',['LayerTypeOfImpl&lt; LayerType::DetectionPostProcess &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_detection_post_process_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adivision_20_3e_5817',['LayerTypeOfImpl&lt; LayerType::Division &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_division_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aelementwisebinary_20_3e_5818',['LayerTypeOfImpl&lt; LayerType::ElementwiseBinary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_elementwise_binary_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aelementwiseunary_20_3e_5819',['LayerTypeOfImpl&lt; LayerType::ElementwiseUnary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_elementwise_unary_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afakequantization_20_3e_5820',['LayerTypeOfImpl&lt; LayerType::FakeQuantization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fake_quantization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afill_20_3e_5821',['LayerTypeOfImpl&lt; LayerType::Fill &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fill_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afloor_20_3e_5822',['LayerTypeOfImpl&lt; LayerType::Floor &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_floor_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afullyconnected_20_3e_5823',['LayerTypeOfImpl&lt; LayerType::FullyConnected &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fully_connected_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afused_20_3e_5824',['LayerTypeOfImpl&lt; LayerType::Fused &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fused_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3agather_20_3e_5825',['LayerTypeOfImpl&lt; LayerType::Gather &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_gather_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3agathernd_20_3e_5826',['LayerTypeOfImpl&lt; LayerType::GatherNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_gather_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ainput_20_3e_5827',['LayerTypeOfImpl&lt; LayerType::Input &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_input_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ainstancenormalization_20_3e_5828',['LayerTypeOfImpl&lt; LayerType::InstanceNormalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_instance_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3al2normalization_20_3e_5829',['LayerTypeOfImpl&lt; LayerType::L2Normalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_l2_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alogicalbinary_20_3e_5830',['LayerTypeOfImpl&lt; LayerType::LogicalBinary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_logical_binary_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alogsoftmax_20_3e_5831',['LayerTypeOfImpl&lt; LayerType::LogSoftmax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_log_softmax_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alstm_20_3e_5832',['LayerTypeOfImpl&lt; LayerType::Lstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amap_20_3e_5833',['LayerTypeOfImpl&lt; LayerType::Map &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_map_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amaximum_20_3e_5834',['LayerTypeOfImpl&lt; LayerType::Maximum &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_maximum_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amean_20_3e_5835',['LayerTypeOfImpl&lt; LayerType::Mean &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mean_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amemcopy_20_3e_5836',['LayerTypeOfImpl&lt; LayerType::MemCopy &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mem_copy_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amemimport_20_3e_5837',['LayerTypeOfImpl&lt; LayerType::MemImport &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mem_import_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amerge_20_3e_5838',['LayerTypeOfImpl&lt; LayerType::Merge &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_merge_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aminimum_20_3e_5839',['LayerTypeOfImpl&lt; LayerType::Minimum &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_minimum_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amultiplication_20_3e_5840',['LayerTypeOfImpl&lt; LayerType::Multiplication &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_multiplication_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3anormalization_20_3e_5841',['LayerTypeOfImpl&lt; LayerType::Normalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aoutput_20_3e_5842',['LayerTypeOfImpl&lt; LayerType::Output &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_output_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apad_20_3e_5843',['LayerTypeOfImpl&lt; LayerType::Pad &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pad_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apermute_20_3e_5844',['LayerTypeOfImpl&lt; LayerType::Permute &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_permute_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apooling2d_20_3e_5845',['LayerTypeOfImpl&lt; LayerType::Pooling2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pooling2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apooling3d_20_3e_5846',['LayerTypeOfImpl&lt; LayerType::Pooling3d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pooling3d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aprecompiled_20_3e_5847',['LayerTypeOfImpl&lt; LayerType::PreCompiled &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pre_compiled_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aprelu_20_3e_5848',['LayerTypeOfImpl&lt; LayerType::Prelu &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_prelu_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aqlstm_20_3e_5849',['LayerTypeOfImpl&lt; LayerType::QLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_q_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aquantize_20_3e_5850',['LayerTypeOfImpl&lt; LayerType::Quantize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_quantize_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aquantizedlstm_20_3e_5851',['LayerTypeOfImpl&lt; LayerType::QuantizedLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_quantized_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3arank_20_3e_5852',['LayerTypeOfImpl&lt; LayerType::Rank &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_rank_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areduce_20_3e_5853',['LayerTypeOfImpl&lt; LayerType::Reduce &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reduce_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areshape_20_3e_5854',['LayerTypeOfImpl&lt; LayerType::Reshape &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reshape_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aresize_20_3e_5855',['LayerTypeOfImpl&lt; LayerType::Resize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_resize_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areversev2_20_3e_5856',['LayerTypeOfImpl&lt; LayerType::ReverseV2 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reverse_v2_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ascatternd_20_3e_5857',['LayerTypeOfImpl&lt; LayerType::ScatterNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_scatter_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ashape_20_3e_5858',['LayerTypeOfImpl&lt; LayerType::Shape &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_shape_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aslice_20_3e_5859',['LayerTypeOfImpl&lt; LayerType::Slice &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_slice_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asoftmax_20_3e_5860',['LayerTypeOfImpl&lt; LayerType::Softmax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_softmax_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aspacetobatchnd_20_3e_5861',['LayerTypeOfImpl&lt; LayerType::SpaceToBatchNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_space_to_batch_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aspacetodepth_20_3e_5862',['LayerTypeOfImpl&lt; LayerType::SpaceToDepth &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_space_to_depth_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asplitter_20_3e_5863',['LayerTypeOfImpl&lt; LayerType::Splitter &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_splitter_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astack_20_3e_5864',['LayerTypeOfImpl&lt; LayerType::Stack &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_stack_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astandin_20_3e_5865',['LayerTypeOfImpl&lt; LayerType::StandIn &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_stand_in_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astridedslice_20_3e_5866',['LayerTypeOfImpl&lt; LayerType::StridedSlice &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_strided_slice_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asubtraction_20_3e_5867',['LayerTypeOfImpl&lt; LayerType::Subtraction &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_subtraction_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aswitch_20_3e_5868',['LayerTypeOfImpl&lt; LayerType::Switch &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_switch_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atile_20_3e_5869',['LayerTypeOfImpl&lt; LayerType::Tile &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_tile_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atranspose_20_3e_5870',['LayerTypeOfImpl&lt; LayerType::Transpose &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_transpose_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atransposeconvolution2d_20_3e_5871',['LayerTypeOfImpl&lt; LayerType::TransposeConvolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_transpose_convolution2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aunidirectionalsequencelstm_20_3e_5872',['LayerTypeOfImpl&lt; LayerType::UnidirectionalSequenceLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_unidirectional_sequence_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aunmap_20_3e_5873',['LayerTypeOfImpl&lt; LayerType::Unmap &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_unmap_01_4.html',1,'armnn']]],
  ['layervalidationexception_5874',['LayerValidationException',['../classarmnn_1_1_layer_validation_exception.html',1,'armnn']]],
  ['layerwithparameters_5875',['LayerWithParameters',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20activationdescriptor_20_3e_5876',['LayerWithParameters&lt; ActivationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20argminmaxdescriptor_20_3e_5877',['LayerWithParameters&lt; ArgMinMaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20batchmatmuldescriptor_20_3e_5878',['LayerWithParameters&lt; BatchMatMulDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20batchnormalizationdescriptor_20_3e_5879',['LayerWithParameters&lt; BatchNormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20batchtospacenddescriptor_20_3e_5880',['LayerWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20broadcasttodescriptor_20_3e_5881',['LayerWithParameters&lt; BroadcastToDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20channelshuffledescriptor_20_3e_5882',['LayerWithParameters&lt; ChannelShuffleDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20comparisondescriptor_20_3e_5883',['LayerWithParameters&lt; ComparisonDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20convolution2ddescriptor_20_3e_5884',['LayerWithParameters&lt; Convolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20convolution3ddescriptor_20_3e_5885',['LayerWithParameters&lt; Convolution3dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20depthtospacedescriptor_20_3e_5886',['LayerWithParameters&lt; DepthToSpaceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_5887',['LayerWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20detectionpostprocessdescriptor_20_3e_5888',['LayerWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20elementwisebinarydescriptor_20_3e_5889',['LayerWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20elementwiseunarydescriptor_20_3e_5890',['LayerWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20fakequantizationdescriptor_20_3e_5891',['LayerWithParameters&lt; FakeQuantizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20filldescriptor_20_3e_5892',['LayerWithParameters&lt; FillDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20fullyconnecteddescriptor_20_3e_5893',['LayerWithParameters&lt; FullyConnectedDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20fuseddescriptor_20_3e_5894',['LayerWithParameters&lt; FusedDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20gatherdescriptor_20_3e_5895',['LayerWithParameters&lt; GatherDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20instancenormalizationdescriptor_20_3e_5896',['LayerWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20l2normalizationdescriptor_20_3e_5897',['LayerWithParameters&lt; L2NormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20logicalbinarydescriptor_20_3e_5898',['LayerWithParameters&lt; LogicalBinaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20logsoftmaxdescriptor_20_3e_5899',['LayerWithParameters&lt; LogSoftmaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20lstmdescriptor_20_3e_5900',['LayerWithParameters&lt; LstmDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20meandescriptor_20_3e_5901',['LayerWithParameters&lt; MeanDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20normalizationdescriptor_20_3e_5902',['LayerWithParameters&lt; NormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20originsdescriptor_20_3e_5903',['LayerWithParameters&lt; OriginsDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20paddescriptor_20_3e_5904',['LayerWithParameters&lt; PadDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20permutedescriptor_20_3e_5905',['LayerWithParameters&lt; PermuteDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20pooling2ddescriptor_20_3e_5906',['LayerWithParameters&lt; Pooling2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20pooling3ddescriptor_20_3e_5907',['LayerWithParameters&lt; Pooling3dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20precompileddescriptor_20_3e_5908',['LayerWithParameters&lt; PreCompiledDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20qlstmdescriptor_20_3e_5909',['LayerWithParameters&lt; QLstmDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20reducedescriptor_20_3e_5910',['LayerWithParameters&lt; ReduceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20reshapedescriptor_20_3e_5911',['LayerWithParameters&lt; ReshapeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20resizedescriptor_20_3e_5912',['LayerWithParameters&lt; ResizeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20scatternddescriptor_20_3e_5913',['LayerWithParameters&lt; ScatterNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20slicedescriptor_20_3e_5914',['LayerWithParameters&lt; SliceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20softmaxdescriptor_20_3e_5915',['LayerWithParameters&lt; SoftmaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20spacetobatchnddescriptor_20_3e_5916',['LayerWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20spacetodepthdescriptor_20_3e_5917',['LayerWithParameters&lt; SpaceToDepthDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20stackdescriptor_20_3e_5918',['LayerWithParameters&lt; StackDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20standindescriptor_20_3e_5919',['LayerWithParameters&lt; StandInDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20stridedslicedescriptor_20_3e_5920',['LayerWithParameters&lt; StridedSliceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20tiledescriptor_20_3e_5921',['LayerWithParameters&lt; TileDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_5922',['LayerWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20transposedescriptor_20_3e_5923',['LayerWithParameters&lt; TransposeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20viewsdescriptor_20_3e_5924',['LayerWithParameters&lt; ViewsDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['loadednetwork_5925',['LoadedNetwork',['../classarmnn_1_1_loaded_network.html',1,'armnn']]],
  ['log_5926',['log',['../structarmnn_1_1log.html',1,'armnn']]],
  ['logicalbinarydescriptor_5927',['LogicalBinaryDescriptor',['../structarmnn_1_1_logical_binary_descriptor.html',1,'armnn']]],
  ['logicalbinaryfunction_5928',['LogicalBinaryFunction',['../structarmnn_1_1_logical_binary_function.html',1,'armnn']]],
  ['logicalbinarylayer_5929',['LogicalBinaryLayer',['../classarmnn_1_1_logical_binary_layer.html',1,'armnn']]],
  ['logicalbinaryqueuedescriptor_5930',['LogicalBinaryQueueDescriptor',['../structarmnn_1_1_logical_binary_queue_descriptor.html',1,'armnn']]],
  ['logicalunaryfunction_5931',['LogicalUnaryFunction',['../structarmnn_1_1_logical_unary_function.html',1,'armnn']]],
  ['logsink_5932',['LogSink',['../classarmnn_1_1_log_sink.html',1,'armnn']]],
  ['logsoftmaxlayer_5933',['LogSoftmaxLayer',['../classarmnn_1_1_log_softmax_layer.html',1,'armnn']]],
  ['logsoftmaxqueuedescriptor_5934',['LogSoftmaxQueueDescriptor',['../structarmnn_1_1_log_softmax_queue_descriptor.html',1,'armnn']]],
  ['lstmbasicparameters_5935',['LstmBasicParameters',['../structarmnn_1_1_lstm_basic_parameters.html',1,'armnn']]],
  ['lstmdescriptor_5936',['LstmDescriptor',['../structarmnn_1_1_lstm_descriptor.html',1,'armnn']]],
  ['lstminputparams_5937',['LstmInputParams',['../structarmnn_1_1_lstm_input_params.html',1,'armnn']]],
  ['lstminputparamsinfo_5938',['LstmInputParamsInfo',['../structarmnn_1_1_lstm_input_params_info.html',1,'armnn']]],
  ['lstmlayer_5939',['LstmLayer',['../classarmnn_1_1_lstm_layer.html',1,'armnn']]],
  ['lstmoptcifgparameters_5940',['LstmOptCifgParameters',['../structarmnn_1_1_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['lstmoptlayernormparameters_5941',['LstmOptLayerNormParameters',['../structarmnn_1_1_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['lstmoptpeepholeparameters_5942',['LstmOptPeepholeParameters',['../structarmnn_1_1_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['lstmoptprojectionparameters_5943',['LstmOptProjectionParameters',['../structarmnn_1_1_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['lstmqueuedescriptor_5944',['LstmQueueDescriptor',['../structarmnn_1_1_lstm_queue_descriptor.html',1,'armnn']]]
];
