var searchData=
[
  ['tensor_6565',['Tensor',['../classarmnn_1_1_tensor.html',1,'armnn']]],
  ['tensorbufferarrayview_6566',['TensorBufferArrayView',['../classarmnn_1_1_tensor_buffer_array_view.html',1,'armnn']]],
  ['tensorhandle_6567',['TensorHandle',['../classarmnn_1_1_tensor_handle.html',1,'armnn']]],
  ['tensorhandlefactoryregistry_6568',['TensorHandleFactoryRegistry',['../classarmnn_1_1_tensor_handle_factory_registry.html',1,'armnn']]],
  ['tensorinfo_6569',['TensorInfo',['../classarmnn_1_1_tensor_info.html',1,'armnn']]],
  ['tensormemory_6570',['TensorMemory',['../structarmnn_1_1_tensor_memory.html',1,'armnn']]],
  ['tensornumdimensionsarecorrect_6571',['TensorNumDimensionsAreCorrect',['../structarmnn_1_1_tensor_num_dimensions_are_correct.html',1,'armnn']]],
  ['tensornumdimensionsaregreaterorequalto_6572',['TensorNumDimensionsAreGreaterOrEqualTo',['../structarmnn_1_1_tensor_num_dimensions_are_greater_or_equal_to.html',1,'armnn']]],
  ['tensorshape_6573',['TensorShape',['../classarmnn_1_1_tensor_shape.html',1,'armnn']]],
  ['tfliteparserimpl_6574',['TfLiteParserImpl',['../classarmnn_tf_lite_parser_1_1_tf_lite_parser_impl.html',1,'armnnTfLiteParser']]],
  ['tfliteparseroptions_6575',['TfLiteParserOptions',['../structarmnn_tf_lite_parser_1_1_i_tf_lite_parser_1_1_tf_lite_parser_options.html',1,'armnnTfLiteParser::ITfLiteParser']]],
  ['threadpool_6576',['Threadpool',['../classarmnn_1_1experimental_1_1_threadpool.html',1,'armnn::experimental']]],
  ['throwingstrategy_6577',['ThrowingStrategy',['../structarmnn_1_1_throwing_strategy.html',1,'armnn']]],
  ['tiledescriptor_6578',['TileDescriptor',['../structarmnn_1_1_tile_descriptor.html',1,'armnn']]],
  ['tilelayer_6579',['TileLayer',['../classarmnn_1_1_tile_layer.html',1,'armnn']]],
  ['tilequeuedescriptor_6580',['TileQueueDescriptor',['../structarmnn_1_1_tile_queue_descriptor.html',1,'armnn']]],
  ['timeoutexception_6581',['TimeoutException',['../classarmnn_1_1_timeout_exception.html',1,'armnn']]],
  ['tosaassertsize_6582',['TosaAssertSize',['../struct_tosa_assert_size.html',1,'']]],
  ['tosacontainercontainsthreetypes_6583',['TosaContainerContainsThreeTypes',['../struct_tosa_container_contains_three_types.html',1,'']]],
  ['tosacontainercontainstwotypes_6584',['TosaContainerContainsTwoTypes',['../struct_tosa_container_contains_two_types.html',1,'']]],
  ['tosaoperatorattributeofany_6585',['TosaOperatorAttributeOfAny',['../struct_tosa_operator_attribute_of_any.html',1,'']]],
  ['tosarefbackend_6586',['TosaRefBackend',['../classarmnn_1_1_tosa_ref_backend.html',1,'armnn']]],
  ['tosarefbaseworkload_6587',['TosaRefBaseWorkload',['../classarmnn_1_1_tosa_ref_base_workload.html',1,'armnn']]],
  ['tosareflayersupport_6588',['TosaRefLayerSupport',['../classarmnn_1_1_tosa_ref_layer_support.html',1,'armnn']]],
  ['tosarefmemorymanager_6589',['TosaRefMemoryManager',['../classarmnn_1_1_tosa_ref_memory_manager.html',1,'armnn']]],
  ['tosarefprecompiledworkload_6590',['TosaRefPreCompiledWorkload',['../classarmnn_1_1_tosa_ref_pre_compiled_workload.html',1,'armnn']]],
  ['tosareftensorhandle_6591',['TosaRefTensorHandle',['../classarmnn_1_1_tosa_ref_tensor_handle.html',1,'armnn']]],
  ['tosareftensorhandlefactory_6592',['TosaRefTensorHandleFactory',['../classarmnn_1_1_tosa_ref_tensor_handle_factory.html',1,'armnn']]],
  ['tosarefworkloadfactory_6593',['TosaRefWorkloadFactory',['../classarmnn_1_1_tosa_ref_workload_factory.html',1,'armnn']]],
  ['tosatensornumdimensionswithinbounds_6594',['TosaTensorNumDimensionsWithinBounds',['../struct_tosa_tensor_num_dimensions_within_bounds.html',1,'']]],
  ['tosatypeanyof_6595',['TosaTypeAnyOf',['../struct_tosa_type_any_of.html',1,'']]],
  ['transformiterator_6596',['TransformIterator',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transposeasreshapeimpl_6597',['TransposeAsReshapeImpl',['../classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.html',1,'armnn::optimizations']]],
  ['transposeconvolution2ddescriptor_6598',['TransposeConvolution2dDescriptor',['../structarmnn_1_1_transpose_convolution2d_descriptor.html',1,'armnn']]],
  ['transposeconvolution2dlayer_6599',['TransposeConvolution2dLayer',['../classarmnn_1_1_transpose_convolution2d_layer.html',1,'armnn']]],
  ['transposeconvolution2dqueuedescriptor_6600',['TransposeConvolution2dQueueDescriptor',['../structarmnn_1_1_transpose_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['transposedescriptor_6601',['TransposeDescriptor',['../structarmnn_1_1_transpose_descriptor.html',1,'armnn']]],
  ['transposelayer_6602',['TransposeLayer',['../classarmnn_1_1_transpose_layer.html',1,'armnn']]],
  ['transposequeuedescriptor_6603',['TransposeQueueDescriptor',['../structarmnn_1_1_transpose_queue_descriptor.html',1,'armnn']]],
  ['turboconvertconstdequantisationlayerstoconstlayersimpl_6604',['TurboConvertConstDequantisationLayersToConstLayersImpl',['../classarmnn_1_1optimizations_1_1_turbo_convert_const_dequantisation_layers_to_const_layers_impl.html',1,'armnn::optimizations']]],
  ['typeanyof_6605',['TypeAnyOf',['../structarmnn_1_1_type_any_of.html',1,'armnn']]],
  ['typediterator_6606',['TypedIterator',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20float_2c_20decoder_3c_20float_20_3e_20_3e_6607',['TypedIterator&lt; const float, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20half_2c_20decoder_3c_20float_20_3e_20_3e_6608',['TypedIterator&lt; const Half, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int16_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6609',['TypedIterator&lt; const int16_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6610',['TypedIterator&lt; const int32_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20int32_5ft_20_3e_20_3e_6611',['TypedIterator&lt; const int32_t, Decoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int64_5ft_2c_20decoder_3c_20double_5ft_20_3e_20_3e_6612',['TypedIterator&lt; const int64_t, Decoder&lt; double_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6613',['TypedIterator&lt; const int8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20bool_20_3e_20_3e_6614',['TypedIterator&lt; const uint8_t, Decoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6615',['TypedIterator&lt; const uint8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20float_2c_20encoder_3c_20float_20_3e_20_3e_6616',['TypedIterator&lt; float, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20half_2c_20encoder_3c_20float_20_3e_20_3e_6617',['TypedIterator&lt; Half, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int16_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6618',['TypedIterator&lt; int16_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6619',['TypedIterator&lt; int32_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20int32_5ft_20_3e_20_3e_6620',['TypedIterator&lt; int32_t, Encoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int64_5ft_2c_20encoder_3c_20double_20_3e_20_3e_6621',['TypedIterator&lt; int64_t, Encoder&lt; double &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6622',['TypedIterator&lt; int8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20bool_20_3e_20_3e_6623',['TypedIterator&lt; uint8_t, Encoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6624',['TypedIterator&lt; uint8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typedworkload_6625',['TypedWorkload',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20debugqueuedescriptor_2c_20datatype_20_3e_6626',['TypedWorkload&lt; DebugQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20permutequeuedescriptor_2c_20datatype_20_3e_6627',['TypedWorkload&lt; PermuteQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20transposequeuedescriptor_2c_20datatype_20_3e_6628',['TypedWorkload&lt; TransposeQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typeis_6629',['TypeIs',['../structarmnn_1_1_type_is.html',1,'armnn']]],
  ['typenotperaxisquantized_6630',['TypeNotPerAxisQuantized',['../structarmnn_1_1_type_not_per_axis_quantized.html',1,'armnn']]],
  ['typesareequal_6631',['TypesAreEqual',['../structarmnn_1_1_types_are_equal.html',1,'armnn']]]
];
