ArmNN: src/backends/backendsCommon/test/layerTests/ComparisonTestImpl.cpp File Reference
ComparisonTestImpl.cpp File Reference
#include "ComparisonTestImpl.hpp"
#include <armnn/utility/Assert.hpp>
#include <Half.hpp>
#include <armnnUtils/QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnn/backends/Workload.hpp>
#include <armnn/backends/WorkloadData.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
Functions
LayerTestResult< uint8_t, 4 > EqualSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualBroadcast1ElementTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualBroadcast1dVectorTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > EqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterBroadcast1ElementTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterBroadcast1dVectorTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterBroadcast1ElementFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterBroadcast1ElementUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterBroadcast1dVectorUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualBroadcast1ElementTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualBroadcast1dVectorTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > GreaterOrEqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessBroadcast1ElementTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessBroadcast1dVectorTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessBroadcast1ElementFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessBroadcast1ElementUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessBroadcast1dVectorUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualBroadcast1ElementTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualBroadcast1dVectorTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LessOrEqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualBroadcast1ElementTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualBroadcast1dVectorTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualSimpleFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > NotEqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
EqualBroadcast1dVectorFloat16Test()
LayerTestResult<uint8_t, 4> EqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 407 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualBroadcast1dVectorTest()
LayerTestResult<uint8_t, 4> EqualBroadcast1dVectorTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 368 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualBroadcast1dVectorUint8Test()
LayerTestResult<uint8_t, 4> EqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 446 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualBroadcast1ElementFloat16Test()
LayerTestResult<uint8_t, 4> EqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 394 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualBroadcast1ElementTest()
LayerTestResult<uint8_t, 4> EqualBroadcast1ElementTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 355 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualBroadcast1ElementUint8Test()
LayerTestResult<uint8_t, 4> EqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 433 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualSimpleFloat16Test()
LayerTestResult<uint8_t, 4> EqualSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 381 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualSimpleTest()
LayerTestResult<uint8_t, 4> EqualSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 343 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Equal);
 }
EqualSimpleUint8Test()
LayerTestResult<uint8_t, 4> EqualSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 420 of file ComparisonTestImpl.cpp.
References armnn::Equal.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Equal);
 }
GreaterBroadcast1dVectorFloat16Test()
LayerTestResult<uint8_t, 4> GreaterBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 524 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterBroadcast1dVectorTest()
LayerTestResult<uint8_t, 4> GreaterBroadcast1dVectorTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 485 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterBroadcast1dVectorUint8Test()
LayerTestResult<uint8_t, 4> GreaterBroadcast1dVectorUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 563 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterBroadcast1ElementFloat16Test()
LayerTestResult<uint8_t, 4> GreaterBroadcast1ElementFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 511 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterBroadcast1ElementTest()
LayerTestResult<uint8_t, 4> GreaterBroadcast1ElementTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 472 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterBroadcast1ElementUint8Test()
LayerTestResult<uint8_t, 4> GreaterBroadcast1ElementUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 550 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterOrEqualBroadcast1dVectorFloat16Test()
LayerTestResult<uint8_t, 4> GreaterOrEqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 642 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualBroadcast1dVectorTest()
LayerTestResult<uint8_t, 4> GreaterOrEqualBroadcast1dVectorTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 603 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualBroadcast1dVectorUint8Test()
LayerTestResult<uint8_t, 4> GreaterOrEqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 681 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualBroadcast1ElementFloat16Test()
LayerTestResult<uint8_t, 4> GreaterOrEqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 629 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualBroadcast1ElementTest()
LayerTestResult<uint8_t, 4> GreaterOrEqualBroadcast1ElementTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 590 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualBroadcast1ElementUint8Test()
LayerTestResult<uint8_t, 4> GreaterOrEqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 668 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualSimpleFloat16Test()
LayerTestResult<uint8_t, 4> GreaterOrEqualSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 616 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualSimpleTest()
LayerTestResult<uint8_t, 4> GreaterOrEqualSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 577 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterOrEqualSimpleUint8Test()
LayerTestResult<uint8_t, 4> GreaterOrEqualSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 655 of file ComparisonTestImpl.cpp.
References armnn::GreaterOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::GreaterOrEqual);
 }
GreaterSimpleFloat16Test()
LayerTestResult<uint8_t, 4> GreaterSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 498 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterSimpleTest()
LayerTestResult<uint8_t, 4> GreaterSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 460 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Greater);
 }
GreaterSimpleUint8Test()
LayerTestResult<uint8_t, 4> GreaterSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 537 of file ComparisonTestImpl.cpp.
References armnn::Greater.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Greater);
 }
LessBroadcast1dVectorFloat16Test()
LayerTestResult<uint8_t, 4> LessBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 759 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Less);
 }
LessBroadcast1dVectorTest()
LayerTestResult<uint8_t, 4> LessBroadcast1dVectorTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 720 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Less);
 }
LessBroadcast1dVectorUint8Test()
LayerTestResult<uint8_t, 4> LessBroadcast1dVectorUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 798 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::Less);
 }
LessBroadcast1ElementFloat16Test()
LayerTestResult<uint8_t, 4> LessBroadcast1ElementFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 746 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Less);
 }
LessBroadcast1ElementTest()
LayerTestResult<uint8_t, 4> LessBroadcast1ElementTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 707 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Less);
 }
LessBroadcast1ElementUint8Test()
LayerTestResult<uint8_t, 4> LessBroadcast1ElementUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 785 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::Less);
 }
LessOrEqualBroadcast1dVectorFloat16Test()
LayerTestResult<uint8_t, 4> LessOrEqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 877 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualBroadcast1dVectorTest()
LayerTestResult<uint8_t, 4> LessOrEqualBroadcast1dVectorTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 838 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualBroadcast1dVectorUint8Test()
LayerTestResult<uint8_t, 4> LessOrEqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 916 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualBroadcast1ElementFloat16Test()
LayerTestResult<uint8_t, 4> LessOrEqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 864 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualBroadcast1ElementTest()
LayerTestResult<uint8_t, 4> LessOrEqualBroadcast1ElementTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 825 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualBroadcast1ElementUint8Test()
LayerTestResult<uint8_t, 4> LessOrEqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 903 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualSimpleFloat16Test()
LayerTestResult<uint8_t, 4> LessOrEqualSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 851 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualSimpleTest()
LayerTestResult<uint8_t, 4> LessOrEqualSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 812 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessOrEqualSimpleUint8Test()
LayerTestResult<uint8_t, 4> LessOrEqualSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 890 of file ComparisonTestImpl.cpp.
References armnn::LessOrEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::LessOrEqual);
 }
LessSimpleFloat16Test()
LayerTestResult<uint8_t, 4> LessSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 733 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Less);
 }
LessSimpleTest()
LayerTestResult<uint8_t, 4> LessSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 695 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Less);
 }
LessSimpleUint8Test()
LayerTestResult<uint8_t, 4> LessSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 772 of file ComparisonTestImpl.cpp.
References armnn::Less.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::Less);
 }
NotEqualBroadcast1dVectorFloat16Test()
LayerTestResult<uint8_t, 4> NotEqualBroadcast1dVectorFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 995 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualBroadcast1dVectorTest()
LayerTestResult<uint8_t, 4> NotEqualBroadcast1dVectorTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 956 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualBroadcast1dVectorUint8Test()
LayerTestResult<uint8_t, 4> NotEqualBroadcast1dVectorUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1034 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1dVectorTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualBroadcast1ElementFloat16Test()
LayerTestResult<uint8_t, 4> NotEqualBroadcast1ElementFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 982 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualBroadcast1ElementTest()
LayerTestResult<uint8_t, 4> NotEqualBroadcast1ElementTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 943 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualBroadcast1ElementUint8Test()
LayerTestResult<uint8_t, 4> NotEqualBroadcast1ElementUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1021 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_Broadcast1ElementTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualSimpleFloat16Test()
LayerTestResult<uint8_t, 4> NotEqualSimpleFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 969 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualSimpleTest()
LayerTestResult<uint8_t, 4> NotEqualSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 930 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::NotEqual);
 }
NotEqualSimpleUint8Test()
LayerTestResult<uint8_t, 4> NotEqualSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1008 of file ComparisonTestImpl.cpp.
References armnn::NotEqual.
Referenced by TEST_SUITE().
 {
     return ComparisonTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         s_SimpleTestData,
         armnn::ComparisonOperation::NotEqual);
 }