ArmNN: src/backends/backendsCommon/test/layerTests/ShapeTestImpl.cpp File Reference
ShapeTestImpl.cpp File Reference
#include "ShapeTestImpl.hpp"
#include <DataTypeUtils.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
Functions
template<typename T , std::size_t n>
LayerTestResult< int32_t, 1 > ShapeTest (armnn::TensorInfo inputTensorInfo, std::vector< T > input, armnn::TensorInfo outputTensorInfo, std::vector< int32_t > expectedOutputData, armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 1 > ShapeDimSize1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 1 > ShapeDimSize2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 1 > ShapeDimSize3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< int32_t, 1 > ShapeDimSize4Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize4Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize3Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize2Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< int32_t, 1 > ShapeDimSize1Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
ShapeDimSize1Test()
LayerTestResult<int32_t, 1> ShapeDimSize1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 54 of file ShapeTestImpl.cpp.
References armnn::Signed32.
 {
     armnn::TensorInfo inputTensorInfo({ 1 }, ArmnnType, 1.0f, 0);
     armnn::TensorInfo outputTensorInfo({ 1 }, armnn::DataType::Signed32);
     auto input = ConvertToDataType<ArmnnType>({ 1.0f }, inputTensorInfo);
     return ShapeTest<T, 1>(inputTensorInfo, input, outputTensorInfo, { 1 }, workloadFactory, memoryManager,
                            tensorHandleFactory);
 }
ShapeDimSize1Test< armnn::DataType::BFloat16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::QSymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize1Test< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize1Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test()
LayerTestResult<int32_t, 1> ShapeDimSize2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 69 of file ShapeTestImpl.cpp.
References armnn::Signed32.
 {
     armnn::TensorInfo inputTensorInfo({ 1, 2 }, ArmnnType, 1.0f, 0);
     armnn::TensorInfo outputTensorInfo({ 2 }, armnn::DataType::Signed32);
     auto input = ConvertToDataType<ArmnnType>({ 1.0f, 1.0f }, inputTensorInfo);
     return ShapeTest<T, 2>(inputTensorInfo, input, outputTensorInfo, { 1, 2 }, workloadFactory, memoryManager,
                            tensorHandleFactory);
 }
ShapeDimSize2Test< armnn::DataType::BFloat16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::QSymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize2Test< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize2Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test()
LayerTestResult<int32_t, 1> ShapeDimSize3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 84 of file ShapeTestImpl.cpp.
References armnn::Signed32.
 {
     armnn::TensorInfo inputTensorInfo({ 1, 2, 3 }, ArmnnType, 1.0f, 0);
     armnn::TensorInfo outputTensorInfo({ 3 }, armnn::DataType::Signed32);
     auto input = ConvertToDataType<ArmnnType>({ 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f }, inputTensorInfo);
     return ShapeTest<T, 3>(inputTensorInfo, input, outputTensorInfo, { 1, 2, 3 }, workloadFactory, memoryManager,
                            tensorHandleFactory);
 }
ShapeDimSize3Test< armnn::DataType::BFloat16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::QSymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize3Test< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize3Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test()
LayerTestResult<int32_t, 1> ShapeDimSize4Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 99 of file ShapeTestImpl.cpp.
References armnn::Signed32.
 {
     armnn::TensorInfo inputTensorInfo({ 2, 2, 3, 2 }, ArmnnType, 1.0f, 0);
     armnn::TensorInfo outputTensorInfo({ 4 }, armnn::DataType::Signed32);
     auto input = ConvertToDataType<ArmnnType>({ 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
                                                 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
                                                 1.0f },
                                               inputTensorInfo);
     return ShapeTest<T, 4>(inputTensorInfo, input, outputTensorInfo, { 2, 2, 3, 2 }, workloadFactory, memoryManager,
                            tensorHandleFactory);
 }
ShapeDimSize4Test< armnn::DataType::BFloat16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::BFloat16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::Float16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::Float16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::Float32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::QAsymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::QAsymmU8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::QSymmS16 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::QSymmS8 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::QSymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeDimSize4Test< armnn::DataType::Signed32 >()
template LayerTestResult<int32_t, 1> ShapeDimSize4Test< armnn::DataType::Signed32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ShapeTest()
LayerTestResult<int32_t, 1> ShapeTest (armnn::TensorInfo inputTensorInfo, std::vector< T > input, armnn::TensorInfo outputTensorInfo, std::vector< int32_t > expectedOutputData, armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 15 of file ShapeTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), ITensorHandleFactory::CreateTensorHandle(), IWorkloadFactory::CreateWorkload(), TensorInfo::GetNumElements(), TensorInfo::GetShape(), armnn::IgnoreUnused(), and armnn::Shape.
 {
     IgnoreUnused(memoryManager);
     std::vector<int32_t> actualOutput(outputTensorInfo.GetNumElements());
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::ShapeQueueDescriptor data;
     armnn::WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateWorkload(armnn::LayerType::Shape, data, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), input.data());
     workload->Execute();
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     return LayerTestResult<int32_t, 1>(actualOutput,
                                        expectedOutputData,
                                        outputHandle->GetShape(),
                                        outputTensorInfo.GetShape());
 }