ArmNN: src/backends/backendsCommon/test/layerTests/StridedSliceTestImpl.hpp File Reference
StridedSliceTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > StridedSlice4dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSlice4dReverseFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSliceSimpleStrideFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSliceSimpleRangeMaskFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StridedSliceShrinkAxisMaskCTSFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition0Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition1Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSliceShrinkAxisMaskBitPosition3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0And1Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0And2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSliceShrinkAxisMaskBitPosition0And3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 1 > StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSlice3dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StridedSlice3dReverseFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSlice2dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > StridedSlice2dReverseFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSlice4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSlice4dReverseUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSliceSimpleStrideUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > StridedSliceSimpleRangeMaskUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition0Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSliceShrinkAxisMaskBitPosition3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 1 > StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSlice3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > StridedSlice3dReverseUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSlice2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > StridedSlice2dReverseUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSlice4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSlice4dReverseInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSliceSimpleStrideInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > StridedSliceSimpleRangeMaskInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > StridedSliceShrinkAxisMaskInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 3 > StridedSlice3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 3 > StridedSlice3dReverseInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > StridedSlice2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 2 > StridedSlice2dReverseInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
StridedSlice2dFloat32Test()
LayerTestResult<float, 2> StridedSlice2dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1035 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dTest<armnn::DataType::Float32>(workloadFactory,
                                                         memoryManager,
                                                         tensorHandleFactory);
 }
StridedSlice2dInt16Test()
LayerTestResult<int16_t, 2> StridedSlice2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1289 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice2dReverseFloat32Test()
LayerTestResult<float, 2> StridedSlice2dReverseFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1045 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dReverseTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
StridedSlice2dReverseInt16Test()
LayerTestResult<int16_t, 2> StridedSlice2dReverseInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1297 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dReverseTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice2dReverseUint8Test()
LayerTestResult<uint8_t, 2> StridedSlice2dReverseUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1219 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dReverseTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice2dUint8Test()
LayerTestResult<uint8_t, 2> StridedSlice2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1211 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice2dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dFloat32Test()
LayerTestResult<float, 3> StridedSlice3dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1015 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dTest<armnn::DataType::Float32>(workloadFactory,
                                                         memoryManager,
                                                         tensorHandleFactory);
 }
StridedSlice3dInt16Test()
LayerTestResult<int16_t, 3> StridedSlice3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1273 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dReverseFloat32Test()
LayerTestResult<float, 3> StridedSlice3dReverseFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1025 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dReverseTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
StridedSlice3dReverseInt16Test()
LayerTestResult<int16_t, 3> StridedSlice3dReverseInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1281 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dReverseTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dReverseUint8Test()
LayerTestResult<uint8_t, 3> StridedSlice3dReverseUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1203 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dReverseTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice3dUint8Test()
LayerTestResult<uint8_t, 3> StridedSlice3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1195 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice3dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice4dFloat32Test()
LayerTestResult<float, 4> StridedSlice4dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 865 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dTest<armnn::DataType::Float32>(workloadFactory,
                                                         memoryManager,
                                                         tensorHandleFactory);
 }
StridedSlice4dInt16Test()
LayerTestResult<int16_t, 4> StridedSlice4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1227 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice4dReverseFloat32Test()
LayerTestResult<float, 4> StridedSlice4dReverseFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 875 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dReverseTest<armnn::DataType::Float32>(workloadFactory,
                                                                memoryManager,
                                                                tensorHandleFactory);
 }
StridedSlice4dReverseInt16Test()
LayerTestResult<int16_t, 4> StridedSlice4dReverseInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1235 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dReverseTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StridedSlice4dReverseUint8Test()
LayerTestResult<uint8_t, 4> StridedSlice4dReverseUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1065 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dReverseTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory);
 }
StridedSlice4dUint8Test()
LayerTestResult<uint8_t, 4> StridedSlice4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1055 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSlice4dTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                          memoryManager,
                                                          tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test()
LayerTestResult<float, 1> StridedSliceShrinkAxisMaskBitPosition0And1And3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1005 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1And3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                         memoryManager,
                                                                                         tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test()
LayerTestResult<uint8_t, 1> StridedSliceShrinkAxisMaskBitPosition0And1And3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1185 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1And3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                          memoryManager,
                                                                                          tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0And1Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 975 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0And1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1155 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And1Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And2Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0And2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 985 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And2Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0And2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1165 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And2Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And3Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0And3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 995 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0And3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1175 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0And3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskBitPosition0Dim3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 925 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Dim3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                     memoryManager,
                                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskBitPosition0Dim3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1105 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Dim3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                      memoryManager,
                                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition0Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 935 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition0Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition0Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1115 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition0Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition1Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition1Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 945 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition1Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition1Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1125 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition1Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition2Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 955 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition2Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition2Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1135 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition2Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition3Float32Test()
LayerTestResult<float, 3> StridedSliceShrinkAxisMaskBitPosition3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 965 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition3Test<armnn::DataType::Float32>(workloadFactory,
                                                                                 memoryManager,
                                                                                 tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskBitPosition3Uint8Test()
LayerTestResult<uint8_t, 3> StridedSliceShrinkAxisMaskBitPosition3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1145 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskBitPosition3Test<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                                  memoryManager,
                                                                                  tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskCTSFloat32Test()
LayerTestResult<float, 4> StridedSliceShrinkAxisMaskCTSFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 915 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskCTSTest<armnn::DataType::Float32>(workloadFactory,
                                                                        memoryManager,
                                                                        tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskFloat32Test()
LayerTestResult<float, 2> StridedSliceShrinkAxisMaskFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 905 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskTest<armnn::DataType::Float32>(workloadFactory,
                                                                     memoryManager,
                                                                     tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskInt16Test()
LayerTestResult<int16_t, 2> StridedSliceShrinkAxisMaskInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1263 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
StridedSliceShrinkAxisMaskUint8Test()
LayerTestResult<uint8_t, 2> StridedSliceShrinkAxisMaskUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1095 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceShrinkAxisMaskTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
StridedSliceSimpleRangeMaskFloat32Test()
LayerTestResult<float, 4> StridedSliceSimpleRangeMaskFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 895 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleRangeMaskTest<armnn::DataType::Float32>(workloadFactory,
                                                                      memoryManager,
                                                                      tensorHandleFactory);
 }
StridedSliceSimpleRangeMaskInt16Test()
LayerTestResult<int16_t, 4> StridedSliceSimpleRangeMaskInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1253 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleRangeMaskTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
StridedSliceSimpleRangeMaskUint8Test()
LayerTestResult<uint8_t, 4> StridedSliceSimpleRangeMaskUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1085 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleRangeMaskTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                       memoryManager,
                                                                       tensorHandleFactory);
 }
StridedSliceSimpleStrideFloat32Test()
LayerTestResult<float, 4> StridedSliceSimpleStrideFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 885 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleStrideTest<armnn::DataType::Float32>(workloadFactory,
                                                                   memoryManager,
                                                                   tensorHandleFactory);
 }
StridedSliceSimpleStrideInt16Test()
LayerTestResult<int16_t, 4> StridedSliceSimpleStrideInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1243 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleStrideTest<armnn::DataType::QSymmS16>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }
StridedSliceSimpleStrideUint8Test()
LayerTestResult<uint8_t, 4> StridedSliceSimpleStrideUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 1075 of file StridedSliceTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StridedSliceSimpleStrideTest<armnn::DataType::QAsymmU8>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory);
 }