ArmNN: RequestCounterDirectoryCommandHandler Class Reference
RequestCounterDirectoryCommandHandler Class Reference
#include <RequestCounterDirectoryCommandHandler.hpp>
Public Member Functions
RequestCounterDirectoryCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, ICounterDirectory &counterDirectory, ISendCounterPacket &sendCounterPacket, ISendTimelinePacket &sendTimelinePacket, ProfilingStateMachine &profilingStateMachine)
void operator() (const arm::pipe::Packet &packet) override
Detailed Description
Definition at line 21 of file RequestCounterDirectoryCommandHandler.hpp.
Constructor & Destructor Documentation
RequestCounterDirectoryCommandHandler()
RequestCounterDirectoryCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, ICounterDirectory & counterDirectory, ISendCounterPacket & sendCounterPacket, ISendTimelinePacket & sendTimelinePacket, ProfilingStateMachine & profilingStateMachine) inline
Definition at line 25 of file RequestCounterDirectoryCommandHandler.hpp.
References RequestCounterDirectoryCommandHandler::operator()().
         : CommandHandlerFunctor(familyId, packetId, version)
         , m_CounterDirectory(counterDirectory)
         , m_SendCounterPacket(sendCounterPacket)
         , m_SendTimelinePacket(sendTimelinePacket)
         , m_StateMachine(profilingStateMachine)
     {}
Member Function Documentation
operator()()
void operator() (const arm::pipe::Packet & packet) override
Definition at line 16 of file RequestCounterDirectoryCommandHandler.cpp.
References armnn::profiling::Active, ProfilingStateMachine::GetCurrentState(), armnn::profiling::GetProfilingStateName(), armnn::profiling::NotConnected, ISendCounterPacket::SendCounterDirectoryPacket(), ISendTimelinePacket::SendTimelineMessageDirectoryPackage(), armnn::profiling::Uninitialised, and armnn::profiling::WaitingForAck.
Referenced by RequestCounterDirectoryCommandHandler::RequestCounterDirectoryCommandHandler().
 {
     ProfilingState currentState = m_StateMachine.GetCurrentState();
     switch (currentState)
     {
     case ProfilingState::Uninitialised:
     case ProfilingState::NotConnected:
     case ProfilingState::WaitingForAck:
         throw RuntimeException(fmt::format("Request Counter Directory Comand Handler invoked while in an "
                                            "wrong state: {}",
                                            GetProfilingStateName(currentState)));
     case ProfilingState::Active:
         // Process the packet
         if (!(packet.GetPacketFamily() == 0u && packet.GetPacketId() == 3u))
         {
             throw armnn::InvalidArgumentException(fmt::format("Expected Packet family = 0, id = 3 but "
                                                               "received family = {}, id = {}",
                                                               packet.GetPacketFamily(),
                                                               packet.GetPacketId()));
         }
         // Send all the packet required for the handshake with the external profiling service
         m_SendCounterPacket.SendCounterDirectoryPacket(m_CounterDirectory);
         m_SendTimelinePacket.SendTimelineMessageDirectoryPackage();
         break;
     default:
         throw RuntimeException(fmt::format("Unknown profiling service state: {}",
                                            static_cast<int>(currentState)));
     }
 }
The documentation for this class was generated from the following files:
src/profiling/RequestCounterDirectoryCommandHandler.hpp
src/profiling/RequestCounterDirectoryCommandHandler.cpp