ArmNN: ProfilingStateMachine Class Reference
ProfilingStateMachine Class Reference
#include <ProfilingStateMachine.hpp>
Public Member Functions
ProfilingStateMachine ()
ProfilingStateMachine (ProfilingState state)
ProfilingState GetCurrentState () const
void TransitionToState (ProfilingState newState)
void Reset ()
bool IsOneOfStates (ProfilingState state1)
template<typename T , typename... Args>
bool IsOneOfStates (T state1, T state2, Args... args)
Detailed Description
Definition at line 26 of file ProfilingStateMachine.hpp.
Constructor & Destructor Documentation
ProfilingStateMachine() [1/2]
ProfilingStateMachine () inline
Definition at line 29 of file ProfilingStateMachine.hpp.
 : m_State(ProfilingState::Uninitialised) {}
ProfilingStateMachine() [2/2]
ProfilingStateMachine (ProfilingState state) inline
Definition at line 30 of file ProfilingStateMachine.hpp.
 : m_State(state) {}
Member Function Documentation
GetCurrentState()
ProfilingState GetCurrentState () const
Definition at line 31 of file ProfilingStateMachine.cpp.
Referenced by ProfilingService::ConfigureProfilingService(), ProfilingService::Disconnect(), ProfilingService::GetCurrentState(), PerJobCounterSelectionCommandHandler::operator()(), DeactivateTimelineReportingCommandHandler::operator()(), RequestCounterDirectoryCommandHandler::operator()(), ActivateTimelineReportingCommandHandler::operator()(), ConnectionAcknowledgedCommandHandler::operator()(), PeriodicCounterSelectionCommandHandler::operator()(), SendThread::Stop(), TEST_SUITE(), and ProfilingService::Update().
 {
     return m_State.load();
 }
IsOneOfStates() [1/2]
bool IsOneOfStates (ProfilingState state1) inline
Definition at line 36 of file ProfilingStateMachine.hpp.
References armnn::IgnoreUnused().
Referenced by ProfilingStateMachine::TransitionToState().
     {
         IgnoreUnused(state1);
         return false;
     }
IsOneOfStates() [2/2]
bool IsOneOfStates (T state1, T state2, Args... args) inline
Definition at line 43 of file ProfilingStateMachine.hpp.
     {
         if (state1 == state2)
         {
             return true;
         }
         else
         {
             return IsOneOfStates(state1, args...);
         }
     }
Reset()
void Reset ()
Definition at line 88 of file ProfilingStateMachine.cpp.
References armnn::profiling::Uninitialised.
Referenced by ProfilingService::GetSendTimelinePacket().
 {
     m_State.store(ProfilingState::Uninitialised);
 }
TransitionToState()
void TransitionToState (ProfilingState newState)
Definition at line 36 of file ProfilingStateMachine.cpp.
References armnn::profiling::Active, ProfilingStateMachine::IsOneOfStates(), armnn::profiling::NotConnected, armnn::profiling::Uninitialised, and armnn::profiling::WaitingForAck.
Referenced by ProfilingService::GetSendTimelinePacket(), ConnectionAcknowledgedCommandHandler::operator()(), TEST_SUITE(), ProfilingService::TransitionToState(), and ProfilingService::Update().
 {
     ProfilingState currentState = m_State.load(std::memory_order::memory_order_relaxed);
     switch (newState)
     {
     case ProfilingState::Uninitialised:
         do
         {
             if (!IsOneOfStates(currentState, ProfilingState::Uninitialised))
             {
                 ThrowStateTransitionException(currentState, newState);
             }
         }
         while (!m_State.compare_exchange_strong(currentState, newState, std::memory_order::memory_order_relaxed));
         break;
     case  ProfilingState::NotConnected:
         do
         {
             if (!IsOneOfStates(currentState, ProfilingState::Uninitialised, ProfilingState::NotConnected,
                                ProfilingState::Active, ProfilingState::WaitingForAck))
             {
                 ThrowStateTransitionException(currentState, newState);
             }
         }
         while (!m_State.compare_exchange_strong(currentState, newState, std::memory_order::memory_order_relaxed));
         break;
     case ProfilingState::WaitingForAck:
         do
         {
             if (!IsOneOfStates(currentState, ProfilingState::NotConnected, ProfilingState::WaitingForAck))
             {
                 ThrowStateTransitionException(currentState, newState);
             }
         }
         while (!m_State.compare_exchange_strong(currentState, newState, std::memory_order::memory_order_relaxed));
         break;
     case ProfilingState::Active:
         do
         {
             if (!IsOneOfStates(currentState, ProfilingState::WaitingForAck, ProfilingState::Active))
             {
                 ThrowStateTransitionException(currentState, newState);
             }
         }
         while (!m_State.compare_exchange_strong(currentState, newState, std::memory_order::memory_order_relaxed));
         break;
     default:
         break;
     }
 }
The documentation for this class was generated from the following files:
src/profiling/ProfilingStateMachine.hpp
src/profiling/ProfilingStateMachine.cpp