ArmNN: MockImportBackend Class Reference
MockImportBackend Class Reference
#include <MockImportBackend.hpp>
Public Member Functions
MockImportBackend ()=default
~MockImportBackend ()=default
const BackendId & GetId () const override
IBackendInternal::IMemoryManagerUniquePtr CreateMemoryManager () const override
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IBackendInternal::IMemoryManagerSharedPtr &memoryManager=nullptr) const override
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry) const override
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const override
Create the runtime context of the backend.
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions &creationOptions, IBackendProfilingPtr &backendProfiling) override
Create context specifically used for profiling interaction from backends.
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport () const override
OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph) const override
std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const override
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &registry) override
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
Public Member Functions inherited from IBackendInternal
~IBackendInternal () override=default
Allow backends created by the factory function to be destroyed through IBackendInternal.
virtual IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr &memoryManager, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags) const
virtual IBackendSpecificModelContextPtr CreateBackendSpecificModelContext (const ModelOptions &modelOptions) const
virtual ILayerSupportSharedPtr GetLayerSupport (const ModelOptions &modelOptions) const
virtual OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph, const ModelOptions &modelOptions) const
bool SupportsTensorAllocatorAPI () const
ITensorHandleFactory::FactoryId GetBackwardCompatibleFavoriteHandleFactory ()
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &registry, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags)
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
virtual BackendCapabilities GetCapabilities () const
Returns a BackendCapability if the backend lists the capability The BackendCapability must then be inspected to check whether or not that BackendCapability is supported Otherwise returns an EmptyOptional if the BackendCapability is unlisted.
virtual bool HasCapability (BackendCapability) const
Returns true if backend support the capability false otherwise.
virtual bool UseCustomMemoryAllocator (std::shared_ptr< ICustomAllocator > allocator, armnn::Optional< std::string &> errMsg)
Signals the backend to use a custom memory allocator provided by the user.
virtual std::unique_ptr< ICustomAllocator > GetDefaultAllocator () const
Returns the default memory allocator for the backend.
virtual unsigned int GetNumberOfCacheFiles () const
Returns the number of files cached if backend supports caching.
Static Public Member Functions
static const BackendId & GetIdStatic ()
Static Public Member Functions inherited from IBackendInternal
static constexpr BackendVersion GetApiVersion ()
Returns the version of the Backend API.
Additional Inherited Members
Public Types inherited from IBackendInternal
using IWorkloadFactoryPtr = std::unique_ptr< IWorkloadFactory >
using IBackendContextPtr = std::unique_ptr< IBackendContext >
using IBackendProfilingContextPtr = std::shared_ptr< armnn::profiling::IBackendProfilingContext >
This is the bridge between backend and backend profiling we'll keep it in the backend namespace.
using IBackendProfilingPtr = std::unique_ptr< armnn::profiling::IBackendProfiling >
using ILayerSupportSharedPtr = std::shared_ptr< ILayerSupport >
using IBackendSpecificModelContextPtr = std::shared_ptr< IBackendModelContext >
using IMemoryManagerUniquePtr = std::unique_ptr< IMemoryManager >
using IMemoryManagerSharedPtr = std::shared_ptr< IMemoryManager >
Protected Member Functions inherited from IBackendInternal
IBackendInternal ()=default
Creation must be done through a specific backend interface.
Protected Member Functions inherited from IBackend
IBackend ()
virtual ~IBackend ()
Detailed Description
Definition at line 21 of file MockImportBackend.hpp.
Constructor & Destructor Documentation
MockImportBackend()
MockImportBackend () default
~MockImportBackend()
~MockImportBackend () default
Member Function Documentation
CreateBackendContext()
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const override virtual
Create the runtime context of the backend.
Implementations may return a default-constructed IBackendContextPtr if no context is needed at runtime. Implementations must throw BackendUnavailableException if the backend cannot be used (for example, necessary accelerator hardware is not present). The default implementation always returns a default-constructed pointer.
Reimplemented from IBackendInternal.
Definition at line 66 of file MockImportBackend.cpp.
 {
     return IBackendContextPtr{};
 }
CreateBackendProfilingContext()
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions & creationOptions, IBackendProfilingPtr & backendProfiling) override virtual
Create context specifically used for profiling interaction from backends.
Reimplemented from IBackendInternal.
Definition at line 71 of file MockImportBackend.cpp.
 {
     return IBackendProfilingContextPtr{};
 }
CreateMemoryManager()
IBackendInternal::IMemoryManagerUniquePtr CreateMemoryManager () const override virtual
Reimplemented from IBackendInternal.
Definition at line 77 of file MockImportBackend.cpp.
 {
     return std::make_unique<RefMemoryManager>();
 }
CreateWorkloadFactory() [1/2]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IBackendInternal::IMemoryManagerSharedPtr & memoryManager = nullptr) const override virtual
Implements IBackendInternal.
Definition at line 49 of file MockImportBackend.cpp.
 {
     return std::make_unique<RefWorkloadFactory>(PolymorphicPointerDowncast<RefMemoryManager>(memoryManager));
 }
CreateWorkloadFactory() [2/2]
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry & tensorHandleFactoryRegistry) const override virtual
Reimplemented from IBackendInternal.
Definition at line 55 of file MockImportBackend.cpp.
References TensorHandleFactoryRegistry::RegisterFactory(), and TensorHandleFactoryRegistry::RegisterMemoryManager().
 {
     auto memoryManager = std::make_shared<RefMemoryManager>();
     tensorHandleFactoryRegistry.RegisterMemoryManager(memoryManager);
     tensorHandleFactoryRegistry.RegisterFactory(std::make_unique<RefTensorHandleFactory>(memoryManager));
     return std::make_unique<RefWorkloadFactory>(PolymorphicPointerDowncast<RefMemoryManager>(memoryManager));
 }
GetHandleFactoryPreferences()
std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const override virtual
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
Reimplemented from IBackendInternal.
Definition at line 97 of file MockImportBackend.cpp.
References RefTensorHandleFactory::GetIdStatic().
 {
     return std::vector<ITensorHandleFactory::FactoryId> { RefTensorHandleFactory::GetIdStatic() };
 }
GetId()
const BackendId& GetId () const inline override virtual
Implements IBackend.
Definition at line 28 of file MockImportBackend.hpp.
 { return GetIdStatic(); }
GetIdStatic()
const BackendId & GetIdStatic () static
Definition at line 43 of file MockImportBackend.cpp.
References armnn::MockImportBackendId().
Referenced by MockImportBackendInitialiser::MockImportBackendInitialiser(), and MockImportBackendInitialiser::~MockImportBackendInitialiser().
 {
     static const BackendId s_Id{ MockImportBackendId() };
     return s_Id;
 }
GetLayerSupport()
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport () const override virtual
Implements IBackendInternal.
Definition at line 82 of file MockImportBackend.cpp.
 {
     static ILayerSupportSharedPtr layerSupport{new MockImportLayerSupport};
     return layerSupport;
 }
OptimizeSubgraphView()
OptimizationViews OptimizeSubgraphView (const SubgraphView & subgraph) const override virtual
Reimplemented from IBackendInternal.
Definition at line 88 of file MockImportBackend.cpp.
References OptimizationViews::AddUntouchedSubgraph().
 {
     OptimizationViews optimizationViews;
     optimizationViews.AddUntouchedSubgraph(SubgraphView(subgraph));
     return optimizationViews;
 }
RegisterTensorHandleFactories()
void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &) override virtual
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
Reimplemented from IBackendInternal.
Definition at line 102 of file MockImportBackend.cpp.
References TensorHandleFactoryRegistry::RegisterFactory(), and TensorHandleFactoryRegistry::RegisterMemoryManager().
 {
     auto memoryManager = std::make_shared<RefMemoryManager>();
     registry.RegisterMemoryManager(memoryManager);
     registry.RegisterFactory(std::make_unique<RefTensorHandleFactory>(memoryManager));
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/test/mockBackend/MockImportBackend.hpp
src/backends/backendsCommon/test/mockBackend/MockImportBackend.cpp