ArmNN: PeriodicCounterCapture Class Reference
PeriodicCounterCapture Class Reference final
#include <PeriodicCounterCapture.hpp>
Public Member Functions
PeriodicCounterCapture (const Holder &data, ISendCounterPacket &packet, IReadCounterValues &readCounterValue, const ICounterMappings &counterIdMap, const std::unordered_map< armnn::BackendId, std::shared_ptr< armnn::profiling::IBackendProfilingContext >> &backendProfilingContexts)
~PeriodicCounterCapture ()
void Start () override
void Stop () override
bool IsRunning () const
Public Member Functions inherited from IPeriodicCounterCapture
virtual ~IPeriodicCounterCapture ()
Detailed Description
Definition at line 28 of file PeriodicCounterCapture.hpp.
Constructor & Destructor Documentation
PeriodicCounterCapture()
PeriodicCounterCapture (const Holder & data, ISendCounterPacket & packet, IReadCounterValues & readCounterValue, const ICounterMappings & counterIdMap, const std::unordered_map< armnn::BackendId, std::shared_ptr< armnn::profiling::IBackendProfilingContext >> & backendProfilingContexts) inline
Definition at line 31 of file PeriodicCounterCapture.hpp.
             : m_CaptureDataHolder(data)
             , m_IsRunning(false)
             , m_KeepRunning(false)
             , m_ReadCounterValues(readCounterValue)
             , m_SendCounterPacket(packet)
             , m_CounterIdMap(counterIdMap)
             , m_BackendProfilingContexts(backendProfilingContexts)
     {}
~PeriodicCounterCapture()
~PeriodicCounterCapture () inline
Definition at line 46 of file PeriodicCounterCapture.hpp.
References PeriodicCounterCapture::Start(), and PeriodicCounterCapture::Stop().
 { Stop(); }
Member Function Documentation
IsRunning()
bool IsRunning () const inline
Definition at line 50 of file PeriodicCounterCapture.hpp.
 { return m_IsRunning; }
Start()
void Start () override virtual
Implements IPeriodicCounterCapture.
Definition at line 18 of file PeriodicCounterCapture.cpp.
Referenced by TEST_SUITE(), and PeriodicCounterCapture::~PeriodicCounterCapture().
 {
     // Check if the capture thread is already running
     if (m_IsRunning)
     {
         // The capture thread is already running
         return;
     }
     // Mark the capture thread as running
     m_IsRunning = true;
     // Keep the capture procedure going until the capture thread is signalled to stop
     m_KeepRunning.store(true);
     // Start the new capture thread.
     m_PeriodCaptureThread = std::thread(&PeriodicCounterCapture::Capture, this, std::ref(m_ReadCounterValues));
 }
Stop()
void Stop () override virtual
Implements IPeriodicCounterCapture.
Definition at line 37 of file PeriodicCounterCapture.cpp.
References ARMNN_LOG, Holder::GetCaptureData(), IReadCounterValues::GetDeltaCounterValue(), ICounterMappings::GetGlobalId(), armnn::profiling::GetTimestamp(), ISendCounterPacket::SendPeriodicCounterCapturePacket(), armnn::warning, and Exception::what().
Referenced by ProfilingService::GetSendTimelinePacket(), TEST_SUITE(), ProfilingService::Update(), and PeriodicCounterCapture::~PeriodicCounterCapture().
 {
     // Signal the capture thread to stop
     m_KeepRunning.store(false);
     // Check that the capture thread is running
     if (m_PeriodCaptureThread.joinable())
     {
         // Wait for the capture thread to complete operations
         m_PeriodCaptureThread.join();
     }
     // Mark the capture thread as not running
     m_IsRunning = false;
 }
The documentation for this class was generated from the following files:
src/profiling/PeriodicCounterCapture.hpp
src/profiling/PeriodicCounterCapture.cpp