ArmNN: SimpleLogger< Level > Class Template Reference
SimpleLogger< Level > Class Template Reference
#include <Logging.hpp>
Public Member Functions
SimpleLogger ()
void Enable (bool enable=true)
ScopedRecord StartNewRecord ()
void RemoveAllSinks ()
void AddSink (std::shared_ptr< LogSink > sink)
template<>
SimpleLogger< LogSeverity::Debug > & Get ()
template<>
SimpleLogger< LogSeverity::Trace > & Get ()
template<>
SimpleLogger< LogSeverity::Info > & Get ()
template<>
SimpleLogger< LogSeverity::Warning > & Get ()
template<>
SimpleLogger< LogSeverity::Error > & Get ()
template<>
SimpleLogger< LogSeverity::Fatal > & Get ()
Static Public Member Functions
static SimpleLogger & Get ()
Detailed Description
template<LogSeverity Level>
class armnn::SimpleLogger< Level >
Definition at line 150 of file Logging.hpp.
Constructor & Destructor Documentation
SimpleLogger()
SimpleLogger () inline
Definition at line 153 of file Logging.hpp.
         : m_Sinks{std::make_shared<StandardOutputSink>()}
         , m_Enable(true)
     {
     }
Member Function Documentation
AddSink()
void AddSink (std::shared_ptr< LogSink > sink) inline
Definition at line 176 of file Logging.hpp.
References armnn::SetAllLoggingSinks(), and armnn::SetLogFilter().
Referenced by armnn::SetLoggingSinks().
     {
         m_Sinks.push_back(sink);
     }
Enable()
void Enable (bool enable = true) inline
Definition at line 161 of file Logging.hpp.
Referenced by armnn::SetLogFilter().
     {
         m_Enable = enable;
     }
Get() [1/7]
SimpleLogger< LogSeverity::Debug > & Get ()
Definition at line 32 of file Logging.cpp.
 {
     static SimpleLogger<LogSeverity::Debug> logger;
     return logger;
 }
Get() [2/7]
SimpleLogger< LogSeverity::Trace > & Get ()
Definition at line 39 of file Logging.cpp.
 {
     static SimpleLogger<LogSeverity::Trace> logger;
     return logger;
 }
Get() [3/7]
SimpleLogger< LogSeverity::Info > & Get ()
Definition at line 46 of file Logging.cpp.
 {
     static SimpleLogger<LogSeverity::Info> logger;
     return logger;
 }
Get() [4/7]
SimpleLogger< LogSeverity::Warning > & Get ()
Definition at line 53 of file Logging.cpp.
 {
     static SimpleLogger<LogSeverity::Warning> logger;
     return logger;
 }
Get() [5/7]
SimpleLogger< LogSeverity::Error > & Get ()
Definition at line 60 of file Logging.cpp.
 {
     static SimpleLogger<LogSeverity::Error> logger;
     return logger;
 }
Get() [6/7]
SimpleLogger< LogSeverity::Fatal > & Get ()
Definition at line 67 of file Logging.cpp.
 {
     static SimpleLogger<LogSeverity::Fatal> logger;
     return logger;
 }
Get() [7/7]
SimpleLogger< Level > & Get () static
Definition at line 25 of file Logging.cpp.
Referenced by armnn::SetLogFilter(), and armnn::SetLoggingSinks().
 {
     static SimpleLogger<Level> logger;
     return logger;
 }
RemoveAllSinks()
void RemoveAllSinks () inline
Definition at line 171 of file Logging.hpp.
Referenced by armnn::SetLoggingSinks().
     {
         m_Sinks.clear();
     }
StartNewRecord()
ScopedRecord StartNewRecord () inline
Definition at line 166 of file Logging.hpp.
     {
         return ScopedRecord(m_Sinks, Level, m_Enable);
     }
The documentation for this class was generated from the following files:
include/armnn/Logging.hpp
src/armnn/Logging.cpp