ArmNN: ClComparisonWorkload Class Reference
ClComparisonWorkload Class Reference
#include <ClComparisonWorkload.hpp>
Public Member Functions
ClComparisonWorkload (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
void Execute () const override
Public Member Functions inherited from ClBaseWorkload< ComparisonQueueDescriptor >
ClBaseWorkload (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< ComparisonQueueDescriptor >
BaseWorkload (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const ComparisonQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< ComparisonQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< ComparisonQueueDescriptor >
ComparisonQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 20 of file ClComparisonWorkload.hpp.
Constructor & Destructor Documentation
ClComparisonWorkload()
ClComparisonWorkload (const ComparisonQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 42 of file ClComparisonWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, ARMNN_SCOPED_PROFILING_EVENT, armnn::ConvertComparisonOperationToAcl(), BaseWorkload< ComparisonQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::Undefined, and QueueDescriptor::ValidateInputsOutputs().
     : ClBaseWorkload<ComparisonQueueDescriptor>(descriptor, info)
 {
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("NeonComparisonWorkload_Construct",
                                          descriptor.m_Parameters,
                                          info,
                                          this->GetGuid());
     m_Data.ValidateInputsOutputs("ClComparisonWorkload", 2, 1);
     arm_compute::ICLTensor& input0 = static_cast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& input1 = static_cast<IClTensorHandle*>(m_Data.m_Inputs[1])->GetTensor();
     arm_compute::ICLTensor& output = static_cast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     const arm_compute::ComparisonOperation comparisonOperation = ConvertComparisonOperationToAcl(m_Data.m_Parameters);
     {
         ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClComparisonWorkload_configure");
         m_ComparisonLayer.configure(clCompileContext, &input0, &input1, &output, comparisonOperation);
     }
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 67 of file ClComparisonWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< ComparisonQueueDescriptor >::GetGuid(), and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClComparisonWorkload_Execute", this->GetGuid());
     RunClFunction(m_ComparisonLayer, CHECK_LOCATION());
 }
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClComparisonWorkload.hpp
src/backends/cl/workloads/ClComparisonWorkload.cpp