ArmNN: IProfilingConnection Class Reference
IProfilingConnection Class Reference abstract
#include <IProfilingConnection.hpp>
Public Member Functions
virtual ~IProfilingConnection ()
virtual bool IsOpen () const =0
virtual void Close ()=0
virtual bool WritePacket (const unsigned char *buffer, uint32_t length)=0
virtual arm::pipe::Packet ReadPacket (uint32_t timeout)=0
Detailed Description
Definition at line 20 of file IProfilingConnection.hpp.
Constructor & Destructor Documentation
~IProfilingConnection()
virtual ~IProfilingConnection () inline virtual
Definition at line 23 of file IProfilingConnection.hpp.
References IProfilingConnection::Close(), IProfilingConnection::IsOpen(), IProfilingConnection::ReadPacket(), and IProfilingConnection::WritePacket().
 {}
Member Function Documentation
Close()
virtual void Close () pure virtual
Implemented in FileOnlyProfilingConnection, TestProfilingConnectionBase, MockProfilingConnection, ProfilingConnectionDumpToFileDecorator, and SocketProfilingConnection.
Referenced by IProfilingConnection::~IProfilingConnection().
IsOpen()
virtual bool IsOpen () const pure virtual
Implemented in FileOnlyProfilingConnection, TestProfilingConnectionBase, MockProfilingConnection, ProfilingConnectionDumpToFileDecorator, and SocketProfilingConnection.
Referenced by SendThread::Stop(), CommandHandler::Stop(), and IProfilingConnection::~IProfilingConnection().
ReadPacket()
virtual arm::pipe::Packet ReadPacket (uint32_t timeout) pure virtual
Implemented in TestProfilingConnectionBadAckPacket, TestProfilingConnectionArmnnError, MockProfilingConnection, TestProfilingConnectionTimeoutError, TestProfilingConnectionBase, FileOnlyProfilingConnection, ProfilingConnectionDumpToFileDecorator, and SocketProfilingConnection.
Referenced by CommandHandler::Stop(), and IProfilingConnection::~IProfilingConnection().
WritePacket()
virtual bool WritePacket (const unsigned char * buffer, uint32_t length) pure virtual
Implemented in FileOnlyProfilingConnection, TestProfilingConnectionBase, MockProfilingConnection, ProfilingConnectionDumpToFileDecorator, and SocketProfilingConnection.
Referenced by SendThread::Stop(), and IProfilingConnection::~IProfilingConnection().
The documentation for this class was generated from the following file:
src/profiling/IProfilingConnection.hpp