ArmNN: Connection Class Reference
Connection Class Reference
#include <TimelineModel.hpp>
Public Member Functions
Connection (uint64_t guid, Entity *head, Entity *tail)
uint64_t GetGuid () const
const Entity * GetHead () const
const Entity * GetTail () const
Detailed Description
Definition at line 24 of file TimelineModel.hpp.
Constructor & Destructor Documentation
Connection()
Connection (uint64_t guid, Entity * head, Entity * tail) inline
Definition at line 27 of file TimelineModel.hpp.
                                                           :
         m_Guid(guid), m_HeadEntity(head), m_TailEntity(tail)
     {
         if (head == nullptr)
         {
             std::stringstream ss;
             ss << "connection [" << guid << "] head cannot be null";
             throw arm::pipe::ProfilingException(ss.str());
         }
         if (tail == nullptr)
         {
             std::stringstream ss;
             ss << "connection [" << guid << "] tail cannot be null";
             throw arm::pipe::ProfilingException(ss.str());
         }
     }
Member Function Documentation
GetGuid()
uint64_t GetGuid () const inline
Definition at line 44 of file TimelineModel.hpp.
Referenced by armnn::profiling::GetConnectionDescription().
 {return m_Guid;}
GetHead()
const Entity* GetHead () const inline
Definition at line 45 of file TimelineModel.hpp.
Referenced by armnn::profiling::GetConnectionDescription().
 {return m_HeadEntity;}
GetTail()
const Entity* GetTail () const inline
Definition at line 46 of file TimelineModel.hpp.
Referenced by armnn::profiling::GetConnectionDescription().
 {return m_TailEntity;}
The documentation for this class was generated from the following file:
src/profiling/test/TimelineModel.hpp