ArmNN: Exception Class Reference
Exception Class Reference
Base class for all ArmNN exceptions so that users can filter to just those.
#include <Exceptions.hpp>
Public Member Functions
Exception (const std::string &message)
Exception (const std::string &message, const CheckLocation &location)
exception with context
Exception (const Exception &other, const std::string &message, const CheckLocation &location)
preserving previous exception context and adding local context information
virtual const char * what () const noexcept override
Detailed Description
Base class for all ArmNN exceptions so that users can filter to just those.
Examples:
CustomMemoryAllocatorSample.cpp.
Definition at line 46 of file Exceptions.hpp.
Constructor & Destructor Documentation
Exception() [1/3]
Exception (const std::string & message) explicit
Definition at line 12 of file Exceptions.cpp.
 : m_Message{message}
 {
 }
Exception() [2/3]
Exception (const std::string & message, const CheckLocation & location) explicit
exception with context
Definition at line 17 of file Exceptions.cpp.
 : m_Message{message}
 {
     m_Message += location.AsString();
 }
Exception() [3/3]
Exception (const Exception & other, const std::string & message, const CheckLocation & location) explicit
preserving previous exception context and adding local context information
Definition at line 24 of file Exceptions.cpp.
 : m_Message{other.m_Message}
 {
     m_Message += "\n" + message + location.AsString();
 }
Member Function Documentation
what()
const char * what () const override virtual noexcept
Definition at line 32 of file Exceptions.cpp.
Referenced by DynamicBackendUtils::CreateDynamicBackends(), YoloDatabase::GetTestCaseData(), armnn::test::InferenceTest(), armnn::test::InferenceTestMain(), TfLiteParserImpl::LoadModel(), main(), MainImpl(), DynamicBackendUtils::RegisterDynamicBackendsImpl(), CommandHandler::Stop(), PeriodicCounterCapture::Stop(), TEST_SUITE(), ProfilingService::Update(), and armnn::WrapClError().
 {
     return m_Message.c_str();
 }
The documentation for this class was generated from the following files:
include/armnn/Exceptions.hpp
src/armnn/Exceptions.cpp