ArmNN: MemoryManager Class Reference
MemoryManager Class Reference
#include <MemoryManager.hpp>
Public Member Functions
void StoreMemToAllocate (std::vector< BufferStorage > bufferStorageVector, std::shared_ptr< ICustomAllocator > customAllocator, size_t typeAlignment=0)
Initialization method to store in all information needed.
void Allocate ()
Allocate the amount of memory indicated by , and point each to each correspondent Tensor so that they are bytes separated.
void Deallocate ()
Deallocate memory.
Detailed Description
Definition at line 39 of file MemoryManager.hpp.
Member Function Documentation
Allocate()
void Allocate ()
Allocate the amount of memory indicated by , and point each to each correspondent Tensor so that they are bytes separated.
Definition at line 23 of file MemoryManager.cpp.
Referenced by armnn::TEST_SUITE().
 {
     for (auto& m_AllocatorBufferStoragePair : m_AllocatorBufferStoragePairVector)
     {
         auto& allocator = m_AllocatorBufferStoragePair.first;
         for (auto&& bufferStorage : m_AllocatorBufferStoragePair.second)
         {
            bufferStorage.m_Buffer = allocator.m_CustomAllocator->allocate(bufferStorage.m_BufferSize, 0);
             for (auto tensorMemory : bufferStorage.m_TensorMemoryVector)
             {
                 tensorMemory->m_Data = allocator.m_CustomAllocator->GetMemoryRegionAtOffset(bufferStorage.m_Buffer,
                                                                                             tensorMemory->m_Offset);
             }
         }
     }
 }
Deallocate()
void Deallocate ()
Deallocate memory.
Definition at line 41 of file MemoryManager.cpp.
Referenced by armnn::TEST_SUITE().
 {
     for (auto& m_AllocatorBufferStoragePair : m_AllocatorBufferStoragePairVector)
     {
         auto& allocator = m_AllocatorBufferStoragePair.first;
         for (auto&& bufferStorage : m_AllocatorBufferStoragePair.second)
         {
             allocator.m_CustomAllocator->free(bufferStorage.m_Buffer);
         }
     }
 }
StoreMemToAllocate()
void StoreMemToAllocate (std::vector< BufferStorage > bufferStorageVector, std::shared_ptr< ICustomAllocator > customAllocator, size_t typeAlignment = 0)
Initialization method to store in all information needed.
Parameters
[in] bufferStorageVector - Vector of .
[in] customAllocator - Pointer to .
[in] typeAlignment - Optional parameter. Value of which the size of each value has to be multiple of.
Definition at line 13 of file MemoryManager.cpp.
References armnn::IgnoreUnused().
Referenced by armnn::TEST_SUITE().
 {
     IgnoreUnused(typeAlignment);
     m_AllocatorBufferStoragePairVector.emplace_back(std::make_pair<Allocator, std::vector<BufferStorage>>(
                                                     Allocator{customAllocator},
                                                     std::move(bufferStorageVector)));
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/MemoryManager.hpp
src/backends/backendsCommon/MemoryManager.cpp