ArmNN: MockWorkloadFactory Class Reference
MockWorkloadFactory Class Reference
#include <MockBackend.hpp>
Public Member Functions
MockWorkloadFactory (const std::shared_ptr< MockMemoryManager > &memoryManager)
MockWorkloadFactory ()
~MockWorkloadFactory ()
const BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &, TensorShape const &, unsigned int const *) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual void AfterWorkloadsCreated ()
virtual std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &descriptor, const WorkloadInfo &info) const =0
virtual std::unique_ptr< IWorkload > CreateWorkload (LayerType type, const QueueDescriptor &descriptor, const WorkloadInfo &info) const
Public Attributes
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("Use ABI stable " "CreateWorkload(LayerType, const QueueDescriptor&, const WorkloadInfo& info) instead.", "22.11") std std::unique_ptr< IWorkload > CreateWorkload (LayerType type, const QueueDescriptor &descriptor, const WorkloadInfo &info) const override
Additional Inherited Members
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 41 of file MockBackend.hpp.
Constructor & Destructor Documentation
MockWorkloadFactory() [1/2]
MockWorkloadFactory (const std::shared_ptr< MockMemoryManager > & memoryManager) explicit
Definition at line 29 of file MockBackend.cpp.
     : m_MemoryManager(memoryManager)
 {}
MockWorkloadFactory() [2/2]
MockWorkloadFactory ()
Definition at line 33 of file MockBackend.cpp.
     : m_MemoryManager(new MockMemoryManager())
 {}
~MockWorkloadFactory()
~MockWorkloadFactory () inline
Definition at line 48 of file MockBackend.hpp.
References GetBackendId().
     {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr<ITensorHandle> CreateSubTensorHandle (ITensorHandle & , TensorShape const & , unsigned int const *) const inline override virtual
Implements IWorkloadFactory.
Definition at line 59 of file MockBackend.hpp.
References ARMNN_DEPRECATED_MSG.
     {
         return nullptr;
     }
CreateTensorHandle() [1/2]
std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const inline override virtual
Implements IWorkloadFactory.
Definition at line 67 of file MockBackend.hpp.
References ARMNN_DEPRECATED_MSG, and armnn::IgnoreUnused().
     {
         IgnoreUnused(IsMemoryManaged);
         return std::make_unique<MockTensorHandle>(tensorInfo, m_MemoryManager);
     };
CreateTensorHandle() [2/2]
std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const inline override virtual
Implements IWorkloadFactory.
Definition at line 75 of file MockBackend.hpp.
References armnn::ARMNN_DEPRECATED_MSG_REMOVAL_DATE(), armnn::IgnoreUnused(), armnn::info, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, and armnn::Malloc.
     {
         IgnoreUnused(dataLayout, IsMemoryManaged);
         return std::make_unique<MockTensorHandle>(tensorInfo, static_cast<unsigned int>(MemorySource::Malloc));
     };
GetBackendId()
const BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 37 of file MockBackend.cpp.
References MockWorkloadFactory::CreateWorkload, armnn::info, QueueDescriptor::m_Inputs, and armnn::MemCopy.
 {
     return s_Id;
 }
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Implements IWorkloadFactory.
Definition at line 53 of file MockBackend.hpp.
References ARMNN_DEPRECATED_MSG.
     {
         return false;
     }
Member Data Documentation
CreateWorkload
std::unique_ptr< IWorkload > CreateWorkload override
Definition at line 109 of file MockBackend.hpp.
Referenced by MockWorkloadFactory::GetBackendId().
The documentation for this class was generated from the following files:
include/armnnTestUtils/MockBackend.hpp
src/armnnTestUtils/MockBackend.cpp