ArmNN: ClContextSerializer Class Reference
ClContextSerializer Class Reference
#include <ClContextSerializer.hpp>
Public Member Functions
ClContextSerializer ()=default
~ClContextSerializer ()=default
void Serialize (const arm_compute::CLCompileContext &clCompileContext)
Serializes the CLCompileContext built-in programs.
bool SaveSerializedToStream (std::ostream &stream)
Serializes the ClContext to the stream.
Detailed Description
Definition at line 15 of file ClContextSerializer.hpp.
Constructor & Destructor Documentation
ClContextSerializer()
ClContextSerializer () default
~ClContextSerializer()
~ClContextSerializer () default
Member Function Documentation
SaveSerializedToStream()
bool SaveSerializedToStream (std::ostream & stream)
Serializes the ClContext to the stream.
Parameters
[stream] the stream to save to
Returns
true if ClContext is Serialized to the Stream, false otherwise
Definition at line 49 of file ClContextSerializer.cpp.
References armnn::numeric_cast().
Referenced by ClWorkloadFactory::AfterWorkloadsCreated().
 {
     // Write to a stream
     auto bytesToWrite = armnn::numeric_cast<std::streamsize>(m_FlatBufferBuilder.GetSize());
     stream.write(reinterpret_cast<const char*>(m_FlatBufferBuilder.GetBufferPointer()), bytesToWrite);
     return !stream.bad();
 }
Serialize()
void Serialize (const arm_compute::CLCompileContext & clCompileContext)
Serializes the CLCompileContext built-in programs.
Parameters
[in] clCompileContext The CLCompileContext to be serialized.
Definition at line 23 of file ClContextSerializer.cpp.
References ARMNN_LOG, armnn::CreateClContext(), armnn::CreateProgram(), and armnn::warning.
Referenced by ClWorkloadFactory::AfterWorkloadsCreated().
 {
     // Get map of built programs from clCompileContext
     std::map<std::string, cl::Program> builtProgramsMap = clCompileContext.get_built_programs();
     if (builtProgramsMap.empty())
     {
         ARMNN_LOG(warning) << "There are no built programs to be serialised.";
         return;
     }
     // Create Flatbuffer CL Programs
     std::vector<flatbuffers::Offset<armnn::Program>> clPrograms;
     for(const auto& program : builtProgramsMap)
     {
         std::vector<std::vector<uint8_t>> binaries = program.second.getInfo<CL_PROGRAM_BINARIES>();
         clPrograms.push_back(CreateProgram(m_FlatBufferBuilder,
                                            m_FlatBufferBuilder.CreateString(program.first),
                                            m_FlatBufferBuilder.CreateVector(binaries[0])));
     }
     // Create Flatbuffer CLContext
     auto clContext = CreateClContext(m_FlatBufferBuilder, m_FlatBufferBuilder.CreateVector(clPrograms));
     m_FlatBufferBuilder.Finish(clContext);
 }
The documentation for this class was generated from the following files:
src/backends/cl/ClContextSerializer.hpp
src/backends/cl/ClContextSerializer.cpp