var namespacearmnn_serializer =
[
    [ "AbsLayerBuilder", "structarmnn_serializer_1_1_abs_layer_builder.xhtml", "structarmnn_serializer_1_1_abs_layer_builder" ],
    [ "ActivationDescriptorBuilder", "structarmnn_serializer_1_1_activation_descriptor_builder.xhtml", "structarmnn_serializer_1_1_activation_descriptor_builder" ],
    [ "ActivationLayerBuilder", "structarmnn_serializer_1_1_activation_layer_builder.xhtml", "structarmnn_serializer_1_1_activation_layer_builder" ],
    [ "AdditionLayerBuilder", "structarmnn_serializer_1_1_addition_layer_builder.xhtml", "structarmnn_serializer_1_1_addition_layer_builder" ],
    [ "AnyLayerBuilder", "structarmnn_serializer_1_1_any_layer_builder.xhtml", "structarmnn_serializer_1_1_any_layer_builder" ],
    [ "ArgMinMaxDescriptorBuilder", "structarmnn_serializer_1_1_arg_min_max_descriptor_builder.xhtml", "structarmnn_serializer_1_1_arg_min_max_descriptor_builder" ],
    [ "ArgMinMaxLayerBuilder", "structarmnn_serializer_1_1_arg_min_max_layer_builder.xhtml", "structarmnn_serializer_1_1_arg_min_max_layer_builder" ],
    [ "BatchNormalizationDescriptorBuilder", "structarmnn_serializer_1_1_batch_normalization_descriptor_builder.xhtml", "structarmnn_serializer_1_1_batch_normalization_descriptor_builder" ],
    [ "BatchNormalizationLayerBuilder", "structarmnn_serializer_1_1_batch_normalization_layer_builder.xhtml", "structarmnn_serializer_1_1_batch_normalization_layer_builder" ],
    [ "BatchToSpaceNdDescriptorBuilder", "structarmnn_serializer_1_1_batch_to_space_nd_descriptor_builder.xhtml", "structarmnn_serializer_1_1_batch_to_space_nd_descriptor_builder" ],
    [ "BatchToSpaceNdLayerBuilder", "structarmnn_serializer_1_1_batch_to_space_nd_layer_builder.xhtml", "structarmnn_serializer_1_1_batch_to_space_nd_layer_builder" ],
    [ "BindableLayerBaseBuilder", "structarmnn_serializer_1_1_bindable_layer_base_builder.xhtml", "structarmnn_serializer_1_1_bindable_layer_base_builder" ],
    [ "ByteDataBuilder", "structarmnn_serializer_1_1_byte_data_builder.xhtml", "structarmnn_serializer_1_1_byte_data_builder" ],
    [ "CastLayerBuilder", "structarmnn_serializer_1_1_cast_layer_builder.xhtml", "structarmnn_serializer_1_1_cast_layer_builder" ],
    [ "ChannelShuffleDescriptorBuilder", "structarmnn_serializer_1_1_channel_shuffle_descriptor_builder.xhtml", "structarmnn_serializer_1_1_channel_shuffle_descriptor_builder" ],
    [ "ChannelShuffleLayerBuilder", "structarmnn_serializer_1_1_channel_shuffle_layer_builder.xhtml", "structarmnn_serializer_1_1_channel_shuffle_layer_builder" ],
    [ "ComparisonDescriptorBuilder", "structarmnn_serializer_1_1_comparison_descriptor_builder.xhtml", "structarmnn_serializer_1_1_comparison_descriptor_builder" ],
    [ "ComparisonLayerBuilder", "structarmnn_serializer_1_1_comparison_layer_builder.xhtml", "structarmnn_serializer_1_1_comparison_layer_builder" ],
    [ "ConcatLayerBuilder", "structarmnn_serializer_1_1_concat_layer_builder.xhtml", "structarmnn_serializer_1_1_concat_layer_builder" ],
    [ "ConstantLayerBuilder", "structarmnn_serializer_1_1_constant_layer_builder.xhtml", "structarmnn_serializer_1_1_constant_layer_builder" ],
    [ "ConstTensorBuilder", "structarmnn_serializer_1_1_const_tensor_builder.xhtml", "structarmnn_serializer_1_1_const_tensor_builder" ],
    [ "ConstTensorDataTraits", "structarmnn_serializer_1_1_const_tensor_data_traits.xhtml", null ],
    [ "ConstTensorDataTraits< armnnSerializer::ByteData >", "structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_byte_data_01_4.xhtml", null ],
    [ "ConstTensorDataTraits< armnnSerializer::IntData >", "structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_int_data_01_4.xhtml", null ],
    [ "ConstTensorDataTraits< armnnSerializer::LongData >", "structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_long_data_01_4.xhtml", null ],
    [ "ConstTensorDataTraits< armnnSerializer::ShortData >", "structarmnn_serializer_1_1_const_tensor_data_traits_3_01armnn_serializer_1_1_short_data_01_4.xhtml", null ],
    [ "Convolution2dDescriptorBuilder", "structarmnn_serializer_1_1_convolution2d_descriptor_builder.xhtml", "structarmnn_serializer_1_1_convolution2d_descriptor_builder" ],
    [ "Convolution2dLayerBuilder", "structarmnn_serializer_1_1_convolution2d_layer_builder.xhtml", "structarmnn_serializer_1_1_convolution2d_layer_builder" ],
    [ "Convolution3dDescriptorBuilder", "structarmnn_serializer_1_1_convolution3d_descriptor_builder.xhtml", "structarmnn_serializer_1_1_convolution3d_descriptor_builder" ],
    [ "Convolution3dLayerBuilder", "structarmnn_serializer_1_1_convolution3d_layer_builder.xhtml", "structarmnn_serializer_1_1_convolution3d_layer_builder" ],
    [ "DepthToSpaceDescriptorBuilder", "structarmnn_serializer_1_1_depth_to_space_descriptor_builder.xhtml", "structarmnn_serializer_1_1_depth_to_space_descriptor_builder" ],
    [ "DepthToSpaceLayerBuilder", "structarmnn_serializer_1_1_depth_to_space_layer_builder.xhtml", "structarmnn_serializer_1_1_depth_to_space_layer_builder" ],
    [ "DepthwiseConvolution2dDescriptorBuilder", "structarmnn_serializer_1_1_depthwise_convolution2d_descriptor_builder.xhtml", "structarmnn_serializer_1_1_depthwise_convolution2d_descriptor_builder" ],
    [ "DepthwiseConvolution2dLayerBuilder", "structarmnn_serializer_1_1_depthwise_convolution2d_layer_builder.xhtml", "structarmnn_serializer_1_1_depthwise_convolution2d_layer_builder" ],
    [ "DequantizeLayerBuilder", "structarmnn_serializer_1_1_dequantize_layer_builder.xhtml", "structarmnn_serializer_1_1_dequantize_layer_builder" ],
    [ "DetectionPostProcessDescriptorBuilder", "structarmnn_serializer_1_1_detection_post_process_descriptor_builder.xhtml", "structarmnn_serializer_1_1_detection_post_process_descriptor_builder" ],
    [ "DetectionPostProcessLayerBuilder", "structarmnn_serializer_1_1_detection_post_process_layer_builder.xhtml", "structarmnn_serializer_1_1_detection_post_process_layer_builder" ],
    [ "DivisionLayerBuilder", "structarmnn_serializer_1_1_division_layer_builder.xhtml", "structarmnn_serializer_1_1_division_layer_builder" ],
    [ "ElementwiseUnaryDescriptorBuilder", "structarmnn_serializer_1_1_elementwise_unary_descriptor_builder.xhtml", "structarmnn_serializer_1_1_elementwise_unary_descriptor_builder" ],
    [ "ElementwiseUnaryLayerBuilder", "structarmnn_serializer_1_1_elementwise_unary_layer_builder.xhtml", "structarmnn_serializer_1_1_elementwise_unary_layer_builder" ],
    [ "EqualLayerBuilder", "structarmnn_serializer_1_1_equal_layer_builder.xhtml", "structarmnn_serializer_1_1_equal_layer_builder" ],
    [ "FeatureCompatibilityVersionsBuilder", "structarmnn_serializer_1_1_feature_compatibility_versions_builder.xhtml", "structarmnn_serializer_1_1_feature_compatibility_versions_builder" ],
    [ "FillDescriptorBuilder", "structarmnn_serializer_1_1_fill_descriptor_builder.xhtml", "structarmnn_serializer_1_1_fill_descriptor_builder" ],
    [ "FillLayerBuilder", "structarmnn_serializer_1_1_fill_layer_builder.xhtml", "structarmnn_serializer_1_1_fill_layer_builder" ],
    [ "FLATBUFFERS_FINAL_CLASS", "structarmnn_serializer_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s.xhtml", "structarmnn_serializer_1_1_f_l_a_t_b_u_f_f_e_r_s___f_i_n_a_l___c_l_a_s_s" ],
    [ "FloorLayerBuilder", "structarmnn_serializer_1_1_floor_layer_builder.xhtml", "structarmnn_serializer_1_1_floor_layer_builder" ],
    [ "FullyConnectedDescriptorBuilder", "structarmnn_serializer_1_1_fully_connected_descriptor_builder.xhtml", "structarmnn_serializer_1_1_fully_connected_descriptor_builder" ],
    [ "FullyConnectedLayerBuilder", "structarmnn_serializer_1_1_fully_connected_layer_builder.xhtml", "structarmnn_serializer_1_1_fully_connected_layer_builder" ],
    [ "GatherDescriptorBuilder", "structarmnn_serializer_1_1_gather_descriptor_builder.xhtml", "structarmnn_serializer_1_1_gather_descriptor_builder" ],
    [ "GatherLayerBuilder", "structarmnn_serializer_1_1_gather_layer_builder.xhtml", "structarmnn_serializer_1_1_gather_layer_builder" ],
    [ "GreaterLayerBuilder", "structarmnn_serializer_1_1_greater_layer_builder.xhtml", "structarmnn_serializer_1_1_greater_layer_builder" ],
    [ "InputLayerBuilder", "structarmnn_serializer_1_1_input_layer_builder.xhtml", "structarmnn_serializer_1_1_input_layer_builder" ],
    [ "InputSlotBuilder", "structarmnn_serializer_1_1_input_slot_builder.xhtml", "structarmnn_serializer_1_1_input_slot_builder" ],
    [ "InstanceNormalizationDescriptorBuilder", "structarmnn_serializer_1_1_instance_normalization_descriptor_builder.xhtml", "structarmnn_serializer_1_1_instance_normalization_descriptor_builder" ],
    [ "InstanceNormalizationLayerBuilder", "structarmnn_serializer_1_1_instance_normalization_layer_builder.xhtml", "structarmnn_serializer_1_1_instance_normalization_layer_builder" ],
    [ "IntDataBuilder", "structarmnn_serializer_1_1_int_data_builder.xhtml", "structarmnn_serializer_1_1_int_data_builder" ],
    [ "ISerializer", "classarmnn_serializer_1_1_i_serializer.xhtml", "classarmnn_serializer_1_1_i_serializer" ],
    [ "L2NormalizationDescriptorBuilder", "structarmnn_serializer_1_1_l2_normalization_descriptor_builder.xhtml", "structarmnn_serializer_1_1_l2_normalization_descriptor_builder" ],
    [ "L2NormalizationLayerBuilder", "structarmnn_serializer_1_1_l2_normalization_layer_builder.xhtml", "structarmnn_serializer_1_1_l2_normalization_layer_builder" ],
    [ "LayerBaseBuilder", "structarmnn_serializer_1_1_layer_base_builder.xhtml", "structarmnn_serializer_1_1_layer_base_builder" ],
    [ "LayerTraits", "structarmnn_serializer_1_1_layer_traits.xhtml", null ],
    [ "LayerTraits< armnnSerializer::AbsLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_abs_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ActivationLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_activation_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::AdditionLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_addition_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ArgMinMaxLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_arg_min_max_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::BatchNormalizationLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_batch_normalization_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::BatchToSpaceNdLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_batch_to_space_nd_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::CastLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_cast_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ChannelShuffleLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_channel_shuffle_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ComparisonLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_comparison_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ConcatLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_concat_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ConstantLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_constant_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::Convolution2dLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_convolution2d_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::Convolution3dLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_convolution3d_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::DepthToSpaceLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_depth_to_space_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::DepthwiseConvolution2dLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_depthwise_convolution2d_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::DequantizeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_dequantize_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::DetectionPostProcessLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_detection_post_process_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::DivisionLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_division_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ElementwiseUnaryLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_elementwise_unary_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::EqualLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_equal_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::FillLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_fill_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::FloorLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_floor_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::FullyConnectedLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_fully_connected_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::GatherLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_gather_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::GreaterLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_greater_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::InputLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_input_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::InstanceNormalizationLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_instance_normalization_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::L2NormalizationLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_l2_normalization_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::LogicalBinaryLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_logical_binary_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::LogSoftmaxLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_log_softmax_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::LstmLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_lstm_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::MaximumLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_maximum_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::MeanLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_mean_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::MergeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_merge_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::MergerLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_merger_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::MinimumLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_minimum_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::MultiplicationLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_multiplication_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::NormalizationLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_normalization_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::OutputLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_output_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::PadLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_pad_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::PermuteLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_permute_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::Pooling2dLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_pooling2d_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::Pooling3dLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_pooling3d_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::PreluLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_prelu_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::QLstmLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_q_lstm_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::QuantizedLstmLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_quantized_lstm_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::QuantizeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_quantize_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::RankLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_rank_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ReduceLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_reduce_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ReshapeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_reshape_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ResizeBilinearLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_resize_bilinear_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ResizeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_resize_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::RsqrtLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_rsqrt_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::ShapeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_shape_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SliceLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_slice_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SoftmaxLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_softmax_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SpaceToBatchNdLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_space_to_batch_nd_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SpaceToDepthLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_space_to_depth_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SplitterLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_splitter_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::StackLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_stack_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::StandInLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_stand_in_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::StridedSliceLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_strided_slice_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SubtractionLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_subtraction_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::SwitchLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_switch_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::TransposeConvolution2dLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_transpose_convolution2d_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::TransposeLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_transpose_layer_01_4.xhtml", null ],
    [ "LayerTraits< armnnSerializer::UnidirectionalSequenceLstmLayer >", "structarmnn_serializer_1_1_layer_traits_3_01armnn_serializer_1_1_unidirectional_sequence_lstm_layer_01_4.xhtml", null ],
    [ "LogicalBinaryDescriptorBuilder", "structarmnn_serializer_1_1_logical_binary_descriptor_builder.xhtml", "structarmnn_serializer_1_1_logical_binary_descriptor_builder" ],
    [ "LogicalBinaryLayerBuilder", "structarmnn_serializer_1_1_logical_binary_layer_builder.xhtml", "structarmnn_serializer_1_1_logical_binary_layer_builder" ],
    [ "LogSoftmaxDescriptorBuilder", "structarmnn_serializer_1_1_log_softmax_descriptor_builder.xhtml", "structarmnn_serializer_1_1_log_softmax_descriptor_builder" ],
    [ "LogSoftmaxLayerBuilder", "structarmnn_serializer_1_1_log_softmax_layer_builder.xhtml", "structarmnn_serializer_1_1_log_softmax_layer_builder" ],
    [ "LongDataBuilder", "structarmnn_serializer_1_1_long_data_builder.xhtml", "structarmnn_serializer_1_1_long_data_builder" ],
    [ "LstmDescriptorBuilder", "structarmnn_serializer_1_1_lstm_descriptor_builder.xhtml", "structarmnn_serializer_1_1_lstm_descriptor_builder" ],
    [ "LstmInputParamsBuilder", "structarmnn_serializer_1_1_lstm_input_params_builder.xhtml", "structarmnn_serializer_1_1_lstm_input_params_builder" ],
    [ "LstmLayerBuilder", "structarmnn_serializer_1_1_lstm_layer_builder.xhtml", "structarmnn_serializer_1_1_lstm_layer_builder" ],
    [ "MaximumLayerBuilder", "structarmnn_serializer_1_1_maximum_layer_builder.xhtml", "structarmnn_serializer_1_1_maximum_layer_builder" ],
    [ "MeanDescriptorBuilder", "structarmnn_serializer_1_1_mean_descriptor_builder.xhtml", "structarmnn_serializer_1_1_mean_descriptor_builder" ],
    [ "MeanLayerBuilder", "structarmnn_serializer_1_1_mean_layer_builder.xhtml", "structarmnn_serializer_1_1_mean_layer_builder" ],
    [ "MergeLayerBuilder", "structarmnn_serializer_1_1_merge_layer_builder.xhtml", "structarmnn_serializer_1_1_merge_layer_builder" ],
    [ "MergerLayerBuilder", "structarmnn_serializer_1_1_merger_layer_builder.xhtml", "structarmnn_serializer_1_1_merger_layer_builder" ],
    [ "MinimumLayerBuilder", "structarmnn_serializer_1_1_minimum_layer_builder.xhtml", "structarmnn_serializer_1_1_minimum_layer_builder" ],
    [ "MultiplicationLayerBuilder", "structarmnn_serializer_1_1_multiplication_layer_builder.xhtml", "structarmnn_serializer_1_1_multiplication_layer_builder" ],
    [ "NormalizationDescriptorBuilder", "structarmnn_serializer_1_1_normalization_descriptor_builder.xhtml", "structarmnn_serializer_1_1_normalization_descriptor_builder" ],
    [ "NormalizationLayerBuilder", "structarmnn_serializer_1_1_normalization_layer_builder.xhtml", "structarmnn_serializer_1_1_normalization_layer_builder" ],
    [ "OriginsDescriptorBuilder", "structarmnn_serializer_1_1_origins_descriptor_builder.xhtml", "structarmnn_serializer_1_1_origins_descriptor_builder" ],
    [ "OutputLayerBuilder", "structarmnn_serializer_1_1_output_layer_builder.xhtml", "structarmnn_serializer_1_1_output_layer_builder" ],
    [ "OutputSlotBuilder", "structarmnn_serializer_1_1_output_slot_builder.xhtml", "structarmnn_serializer_1_1_output_slot_builder" ],
    [ "PadDescriptorBuilder", "structarmnn_serializer_1_1_pad_descriptor_builder.xhtml", "structarmnn_serializer_1_1_pad_descriptor_builder" ],
    [ "PadLayerBuilder", "structarmnn_serializer_1_1_pad_layer_builder.xhtml", "structarmnn_serializer_1_1_pad_layer_builder" ],
    [ "PermuteDescriptorBuilder", "structarmnn_serializer_1_1_permute_descriptor_builder.xhtml", "structarmnn_serializer_1_1_permute_descriptor_builder" ],
    [ "PermuteLayerBuilder", "structarmnn_serializer_1_1_permute_layer_builder.xhtml", "structarmnn_serializer_1_1_permute_layer_builder" ],
    [ "Pooling2dDescriptorBuilder", "structarmnn_serializer_1_1_pooling2d_descriptor_builder.xhtml", "structarmnn_serializer_1_1_pooling2d_descriptor_builder" ],
    [ "Pooling2dLayerBuilder", "structarmnn_serializer_1_1_pooling2d_layer_builder.xhtml", "structarmnn_serializer_1_1_pooling2d_layer_builder" ],
    [ "Pooling3dDescriptorBuilder", "structarmnn_serializer_1_1_pooling3d_descriptor_builder.xhtml", "structarmnn_serializer_1_1_pooling3d_descriptor_builder" ],
    [ "Pooling3dLayerBuilder", "structarmnn_serializer_1_1_pooling3d_layer_builder.xhtml", "structarmnn_serializer_1_1_pooling3d_layer_builder" ],
    [ "PreluLayerBuilder", "structarmnn_serializer_1_1_prelu_layer_builder.xhtml", "structarmnn_serializer_1_1_prelu_layer_builder" ],
    [ "QLstmDescriptorBuilder", "structarmnn_serializer_1_1_q_lstm_descriptor_builder.xhtml", "structarmnn_serializer_1_1_q_lstm_descriptor_builder" ],
    [ "QLstmInputParamsBuilder", "structarmnn_serializer_1_1_q_lstm_input_params_builder.xhtml", "structarmnn_serializer_1_1_q_lstm_input_params_builder" ],
    [ "QLstmLayerBuilder", "structarmnn_serializer_1_1_q_lstm_layer_builder.xhtml", "structarmnn_serializer_1_1_q_lstm_layer_builder" ],
    [ "QuantizedLstmInputParamsBuilder", "structarmnn_serializer_1_1_quantized_lstm_input_params_builder.xhtml", "structarmnn_serializer_1_1_quantized_lstm_input_params_builder" ],
    [ "QuantizedLstmLayerBuilder", "structarmnn_serializer_1_1_quantized_lstm_layer_builder.xhtml", "structarmnn_serializer_1_1_quantized_lstm_layer_builder" ],
    [ "QuantizeLayerBuilder", "structarmnn_serializer_1_1_quantize_layer_builder.xhtml", "structarmnn_serializer_1_1_quantize_layer_builder" ],
    [ "RankLayerBuilder", "structarmnn_serializer_1_1_rank_layer_builder.xhtml", "structarmnn_serializer_1_1_rank_layer_builder" ],
    [ "ReduceDescriptorBuilder", "structarmnn_serializer_1_1_reduce_descriptor_builder.xhtml", "structarmnn_serializer_1_1_reduce_descriptor_builder" ],
    [ "ReduceLayerBuilder", "structarmnn_serializer_1_1_reduce_layer_builder.xhtml", "structarmnn_serializer_1_1_reduce_layer_builder" ],
    [ "ReshapeDescriptorBuilder", "structarmnn_serializer_1_1_reshape_descriptor_builder.xhtml", "structarmnn_serializer_1_1_reshape_descriptor_builder" ],
    [ "ReshapeLayerBuilder", "structarmnn_serializer_1_1_reshape_layer_builder.xhtml", "structarmnn_serializer_1_1_reshape_layer_builder" ],
    [ "ResizeBilinearDescriptorBuilder", "structarmnn_serializer_1_1_resize_bilinear_descriptor_builder.xhtml", "structarmnn_serializer_1_1_resize_bilinear_descriptor_builder" ],
    [ "ResizeBilinearLayerBuilder", "structarmnn_serializer_1_1_resize_bilinear_layer_builder.xhtml", "structarmnn_serializer_1_1_resize_bilinear_layer_builder" ],
    [ "ResizeDescriptorBuilder", "structarmnn_serializer_1_1_resize_descriptor_builder.xhtml", "structarmnn_serializer_1_1_resize_descriptor_builder" ],
    [ "ResizeLayerBuilder", "structarmnn_serializer_1_1_resize_layer_builder.xhtml", "structarmnn_serializer_1_1_resize_layer_builder" ],
    [ "RsqrtLayerBuilder", "structarmnn_serializer_1_1_rsqrt_layer_builder.xhtml", "structarmnn_serializer_1_1_rsqrt_layer_builder" ],
    [ "SerializedGraphBuilder", "structarmnn_serializer_1_1_serialized_graph_builder.xhtml", "structarmnn_serializer_1_1_serialized_graph_builder" ],
    [ "SerializerStrategy", "classarmnn_serializer_1_1_serializer_strategy.xhtml", "classarmnn_serializer_1_1_serializer_strategy" ],
    [ "ShapeLayerBuilder", "structarmnn_serializer_1_1_shape_layer_builder.xhtml", "structarmnn_serializer_1_1_shape_layer_builder" ],
    [ "ShortDataBuilder", "structarmnn_serializer_1_1_short_data_builder.xhtml", "structarmnn_serializer_1_1_short_data_builder" ],
    [ "SliceDescriptorBuilder", "structarmnn_serializer_1_1_slice_descriptor_builder.xhtml", "structarmnn_serializer_1_1_slice_descriptor_builder" ],
    [ "SliceLayerBuilder", "structarmnn_serializer_1_1_slice_layer_builder.xhtml", "structarmnn_serializer_1_1_slice_layer_builder" ],
    [ "SoftmaxDescriptorBuilder", "structarmnn_serializer_1_1_softmax_descriptor_builder.xhtml", "structarmnn_serializer_1_1_softmax_descriptor_builder" ],
    [ "SoftmaxLayerBuilder", "structarmnn_serializer_1_1_softmax_layer_builder.xhtml", "structarmnn_serializer_1_1_softmax_layer_builder" ],
    [ "SpaceToBatchNdDescriptorBuilder", "structarmnn_serializer_1_1_space_to_batch_nd_descriptor_builder.xhtml", "structarmnn_serializer_1_1_space_to_batch_nd_descriptor_builder" ],
    [ "SpaceToBatchNdLayerBuilder", "structarmnn_serializer_1_1_space_to_batch_nd_layer_builder.xhtml", "structarmnn_serializer_1_1_space_to_batch_nd_layer_builder" ],
    [ "SpaceToDepthDescriptorBuilder", "structarmnn_serializer_1_1_space_to_depth_descriptor_builder.xhtml", "structarmnn_serializer_1_1_space_to_depth_descriptor_builder" ],
    [ "SpaceToDepthLayerBuilder", "structarmnn_serializer_1_1_space_to_depth_layer_builder.xhtml", "structarmnn_serializer_1_1_space_to_depth_layer_builder" ],
    [ "SplitterLayerBuilder", "structarmnn_serializer_1_1_splitter_layer_builder.xhtml", "structarmnn_serializer_1_1_splitter_layer_builder" ],
    [ "StackDescriptorBuilder", "structarmnn_serializer_1_1_stack_descriptor_builder.xhtml", "structarmnn_serializer_1_1_stack_descriptor_builder" ],
    [ "StackLayerBuilder", "structarmnn_serializer_1_1_stack_layer_builder.xhtml", "structarmnn_serializer_1_1_stack_layer_builder" ],
    [ "StandInDescriptorBuilder", "structarmnn_serializer_1_1_stand_in_descriptor_builder.xhtml", "structarmnn_serializer_1_1_stand_in_descriptor_builder" ],
    [ "StandInLayerBuilder", "structarmnn_serializer_1_1_stand_in_layer_builder.xhtml", "structarmnn_serializer_1_1_stand_in_layer_builder" ],
    [ "StridedSliceDescriptorBuilder", "structarmnn_serializer_1_1_strided_slice_descriptor_builder.xhtml", "structarmnn_serializer_1_1_strided_slice_descriptor_builder" ],
    [ "StridedSliceLayerBuilder", "structarmnn_serializer_1_1_strided_slice_layer_builder.xhtml", "structarmnn_serializer_1_1_strided_slice_layer_builder" ],
    [ "SubtractionLayerBuilder", "structarmnn_serializer_1_1_subtraction_layer_builder.xhtml", "structarmnn_serializer_1_1_subtraction_layer_builder" ],
    [ "SwitchLayerBuilder", "structarmnn_serializer_1_1_switch_layer_builder.xhtml", "structarmnn_serializer_1_1_switch_layer_builder" ],
    [ "TensorInfoBuilder", "structarmnn_serializer_1_1_tensor_info_builder.xhtml", "structarmnn_serializer_1_1_tensor_info_builder" ],
    [ "TransposeConvolution2dDescriptorBuilder", "structarmnn_serializer_1_1_transpose_convolution2d_descriptor_builder.xhtml", "structarmnn_serializer_1_1_transpose_convolution2d_descriptor_builder" ],
    [ "TransposeConvolution2dLayerBuilder", "structarmnn_serializer_1_1_transpose_convolution2d_layer_builder.xhtml", "structarmnn_serializer_1_1_transpose_convolution2d_layer_builder" ],
    [ "TransposeDescriptorBuilder", "structarmnn_serializer_1_1_transpose_descriptor_builder.xhtml", "structarmnn_serializer_1_1_transpose_descriptor_builder" ],
    [ "TransposeLayerBuilder", "structarmnn_serializer_1_1_transpose_layer_builder.xhtml", "structarmnn_serializer_1_1_transpose_layer_builder" ],
    [ "UintVectorBuilder", "structarmnn_serializer_1_1_uint_vector_builder.xhtml", "structarmnn_serializer_1_1_uint_vector_builder" ],
    [ "UnidirectionalSequenceLstmDescriptorBuilder", "structarmnn_serializer_1_1_unidirectional_sequence_lstm_descriptor_builder.xhtml", "structarmnn_serializer_1_1_unidirectional_sequence_lstm_descriptor_builder" ],
    [ "UnidirectionalSequenceLstmLayerBuilder", "structarmnn_serializer_1_1_unidirectional_sequence_lstm_layer_builder.xhtml", "structarmnn_serializer_1_1_unidirectional_sequence_lstm_layer_builder" ],
    [ "ViewsDescriptorBuilder", "structarmnn_serializer_1_1_views_descriptor_builder.xhtml", "structarmnn_serializer_1_1_views_descriptor_builder" ]
];