ArmNN: armnnUtils::Processes Namespace Reference
armnnUtils::Processes Namespace Reference
Functions
int GetCurrentId ()
Function Documentation
GetCurrentId()
int GetCurrentId ()
Definition at line 19 of file Processes.cpp.
Referenced by LoadedNetwork::MakeLoadedNetwork(), SendCounterPacket::SendStreamMetaDataPacket(), TEST_SUITE(), and VerifyPostOptimisationStructureTestImpl().
 {
 #if defined(__unix__) || defined(__APPLE__)
     return getpid();
 #elif defined(_MSC_VER)
     return ::GetCurrentProcessId();
 #endif
 }