ArmNN: TensorPrinter Struct Reference
TensorPrinter Struct Reference
#include <NetworkExecutionUtils.hpp>
Public Member Functions
TensorPrinter (const std::string &binding, const armnn::TensorInfo &info, const std::string &outputTensorFile, bool dequantizeOutput, bool printToConsole=true)
void operator() (const std::vector< float > &values)
void operator() (const std::vector< uint8_t > &values)
void operator() (const std::vector< int > &values)
void operator() (const std::vector< int8_t > &values)
Detailed Description
Definition at line 23 of file NetworkExecutionUtils.hpp.
Constructor & Destructor Documentation
TensorPrinter()
TensorPrinter (const std::string & binding, const armnn::TensorInfo & info, const std::string & outputTensorFile, bool dequantizeOutput, bool printToConsole = true)
Definition at line 116 of file NetworkExecutionUtils.cpp.
                              : m_OutputBinding(binding)
                              , m_Scale(info.GetQuantizationScale())
                              , m_Offset(info.GetQuantizationOffset())
                              , m_OutputTensorFile(outputTensorFile)
                              , m_DequantizeOutput(dequantizeOutput)
                              , m_PrintToConsole(printToConsole) {}
Member Function Documentation
operator()() [1/4]
void operator() (const std::vector< float > & values)
Definition at line 128 of file NetworkExecutionUtils.cpp.
Referenced by operator()().
 {
     if (m_PrintToConsole)
     {
         std::cout << m_OutputBinding << ": ";
         ForEachValue(values, [](float value)
         {
             printf("%f ", value);
         });
         printf("\n");
     }
     WriteToFile(values);
 }
operator()() [2/4]
void operator() (const std::vector< uint8_t > & values)
Definition at line 142 of file NetworkExecutionUtils.cpp.
References armnn::Dequantize(), and operator()().
 {
     if(m_DequantizeOutput)
     {
         auto& scale = m_Scale;
         auto& offset = m_Offset;
         std::vector<float> dequantizedValues;
         ForEachValue(values, [&scale, &offset, &dequantizedValues](uint8_t value)
         {
             auto dequantizedValue = armnn::Dequantize(value, scale, offset);
             dequantizedValues.push_back(dequantizedValue);
         });
         if (m_PrintToConsole)
         {
             std::cout << m_OutputBinding << ": ";
             ForEachValue(dequantizedValues, [](float value)
             {
                 printf("%f ", value);
             });
             printf("\n");
         }
         WriteToFile(dequantizedValues);
     }
     else
     {
         const std::vector<int> intValues(values.begin(), values.end());
         operator()(intValues);
     }
 }
operator()() [3/4]
void operator() (const std::vector< int > & values)
Definition at line 188 of file NetworkExecutionUtils.cpp.
References ARMNN_LOG.
 {
     if (m_PrintToConsole)
     {
         std::cout << m_OutputBinding << ": ";
         ForEachValue(values, [](int value)
         {
             printf("%d ", value);
         });
         printf("\n");
     }
     WriteToFile(values);
 }
operator()() [4/4]
void operator() (const std::vector< int8_t > & values)
Definition at line 174 of file NetworkExecutionUtils.cpp.
 {
     if (m_PrintToConsole)
     {
         std::cout << m_OutputBinding << ": ";
         ForEachValue(values, [](int8_t value)
         {
             printf("%d ", value);
         });
         printf("\n");
     }
     WriteToFile(values);
 }
The documentation for this struct was generated from the following files:
tests/NetworkExecutionUtils/NetworkExecutionUtils.hpp
tests/NetworkExecutionUtils/NetworkExecutionUtils.cpp