ArmNN: GatherLayerBuilder Struct Reference
GatherLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef GatherLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::GatherDescriptor > descriptor)
GatherLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
GatherLayerBuilder & operator= (const GatherLayerBuilder &)
flatbuffers::Offset< GatherLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 4115 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef GatherLayer Table
Definition at line 4116 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
GatherLayerBuilder()
GatherLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 4125 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 4119 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateGatherLayer().
{
     fbb_.AddOffset(GatherLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::GatherDescriptor > descriptor) inline
Definition at line 4122 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateGatherLayer().
{
     fbb_.AddOffset(GatherLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<GatherLayer> Finish () inline
Definition at line 4130 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateGatherLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<GatherLayer>(end);
     return o;
   }
operator=()
GatherLayerBuilder& operator= (const GatherLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 4117 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 4118 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h