ArmNN: FullyConnectedQueueDescriptor Struct Reference
FullyConnectedQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
FullyConnectedQueueDescriptor ()
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< FullyConnectedDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Public Attributes
const ConstTensorHandle * m_Weight
const ConstTensorHandle * m_Bias
Public Attributes inherited from QueueDescriptorWithParameters< FullyConnectedDescriptor >
FullyConnectedDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
Additional Inherited Members
Protected Member Functions inherited from QueueDescriptorWithParameters< FullyConnectedDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 168 of file WorkloadData.hpp.
Constructor & Destructor Documentation
FullyConnectedQueueDescriptor()
FullyConnectedQueueDescriptor () inline
Definition at line 170 of file WorkloadData.hpp.
         : m_Weight(nullptr)
         , m_Bias(nullptr)
     {
     }
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 1034 of file WorkloadData.cpp.
References armnn::BFloat16, armnn::Float16, armnn::Float32, armnn::GetBiasDataType(), TensorInfo::GetDataType(), TensorInfo::GetNumDimensions(), WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS16.
 {
     const std::string descriptorName{"FullyConnectedQueueDescriptor"};
     uint32_t numInputs = 2;
     if (m_Parameters.m_BiasEnabled)
     {
         numInputs = 3;
     }
     ValidateNumInputs(workloadInfo, descriptorName, numInputs);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     ValidateTensorNumDimensions(outputTensorInfo, descriptorName, 2, "output");
     if (!(inputTensorInfo.GetNumDimensions() == 2 || inputTensorInfo.GetNumDimensions() == 4))
     {
         throw InvalidArgumentException(descriptorName + ": Input tensor must have 2 or 4 dimensions.");
     }
     TensorInfo weightTensorInfo = workloadInfo.m_InputTensorInfos[1];
     ValidateTensorNumDimensions(weightTensorInfo, descriptorName, 2, "weight");
     if (m_Parameters.m_BiasEnabled)
     {
         TensorInfo biasTensorInfo = workloadInfo.m_InputTensorInfos[2];
         // Validates type and quantization values.
         ValidateBiasTensorQuantization(biasTensorInfo, inputTensorInfo, weightTensorInfo, descriptorName);
         ValidateTensorDataType(biasTensorInfo, GetBiasDataType(inputTensorInfo.GetDataType()), descriptorName, "bias");
         ValidateTensorNumDimensions(biasTensorInfo, descriptorName, 1, "bias");
     }
     // Check the supported data types
     std::vector<DataType> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float32,
         DataType::Float16,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16
     };
     ValidateDataTypes(inputTensorInfo, supportedTypes, descriptorName);
     // For FullyConnected, we allow to have BFloat16 input with Float32 output for optimization.
     if (inputTensorInfo.GetDataType() == DataType::BFloat16)
     {
         if (outputTensorInfo.GetDataType() != DataType::BFloat16 && outputTensorInfo.GetDataType() != DataType::Float32)
         {
             throw InvalidArgumentException(descriptorName  + ": " + " Output tensor type must be BFloat16 or Float32 "
                                            "for BFloat16 input.");
         }
     }
     else
     {
         ValidateTensorDataTypesMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
     }
 }
Member Data Documentation
m_Bias
const ConstTensorHandle* m_Bias
Definition at line 177 of file WorkloadData.hpp.
Referenced by ClFullyConnectedWorkload::ClFullyConnectedWorkload(), FullyConnectedLayer::CreateWorkload(), and TEST_SUITE().
m_Weight
const ConstTensorHandle* m_Weight
Definition at line 176 of file WorkloadData.hpp.
Referenced by ClFullyConnectedWorkload::ClFullyConnectedWorkload(), FullyConnectedLayer::CreateWorkload(), and TEST_SUITE().
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp