ArmNN: DepthwiseConvolution2dLayerBuilder Struct Reference
DepthwiseConvolution2dLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef DepthwiseConvolution2dLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::DepthwiseConvolution2dDescriptor > descriptor)
void add_weights (flatbuffers::Offset< armnnSerializer::ConstTensor > weights)
void add_biases (flatbuffers::Offset< armnnSerializer::ConstTensor > biases)
DepthwiseConvolution2dLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
DepthwiseConvolution2dLayerBuilder & operator= (const DepthwiseConvolution2dLayerBuilder &)
flatbuffers::Offset< DepthwiseConvolution2dLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5474 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef DepthwiseConvolution2dLayer Table
Definition at line 5475 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
DepthwiseConvolution2dLayerBuilder()
DepthwiseConvolution2dLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5490 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 5478 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dLayer().
{
     fbb_.AddOffset(DepthwiseConvolution2dLayer::VT_BASE, base);
   }
add_biases()
void add_biases (flatbuffers::Offset< armnnSerializer::ConstTensor > biases) inline
Definition at line 5487 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dLayer().
{
     fbb_.AddOffset(DepthwiseConvolution2dLayer::VT_BIASES, biases);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::DepthwiseConvolution2dDescriptor > descriptor) inline
Definition at line 5481 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dLayer().
{
     fbb_.AddOffset(DepthwiseConvolution2dLayer::VT_DESCRIPTOR, descriptor);
   }
add_weights()
void add_weights (flatbuffers::Offset< armnnSerializer::ConstTensor > weights) inline
Definition at line 5484 of file ArmnnSchema_generated.h.
References VT_WEIGHTS.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dLayer().
{
     fbb_.AddOffset(DepthwiseConvolution2dLayer::VT_WEIGHTS, weights);
   }
Finish()
flatbuffers::Offset<DepthwiseConvolution2dLayer> Finish () inline
Definition at line 5495 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDepthwiseConvolution2dLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<DepthwiseConvolution2dLayer>(end);
     return o;
   }
operator=()
DepthwiseConvolution2dLayerBuilder& operator= (const DepthwiseConvolution2dLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5476 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5477 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h