ArmNN: ConstantLayerBuilder Struct Reference
ConstantLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ConstantLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_input (flatbuffers::Offset< armnnSerializer::ConstTensor > input)
ConstantLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ConstantLayerBuilder & operator= (const ConstantLayerBuilder &)
flatbuffers::Offset< ConstantLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 3061 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ConstantLayer Table
Definition at line 3062 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ConstantLayerBuilder()
ConstantLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3071 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 3065 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateConstantLayer().
{
     fbb_.AddOffset(ConstantLayer::VT_BASE, base);
   }
add_input()
void add_input (flatbuffers::Offset< armnnSerializer::ConstTensor > input) inline
Definition at line 3068 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConstantLayer().
{
     fbb_.AddOffset(ConstantLayer::VT_INPUT, input);
   }
Finish()
flatbuffers::Offset<ConstantLayer> Finish () inline
Definition at line 3076 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConstantLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ConstantLayer>(end);
     return o;
   }
operator=()
ConstantLayerBuilder& operator= (const ConstantLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 3063 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 3064 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h