ArmNN: TransposeConvolution2dDescriptorBuilder Struct Reference
TransposeConvolution2dDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef TransposeConvolution2dDescriptor Table
Public Member Functions
void add_padLeft (uint32_t padLeft)
void add_padRight (uint32_t padRight)
void add_padTop (uint32_t padTop)
void add_padBottom (uint32_t padBottom)
void add_strideX (uint32_t strideX)
void add_strideY (uint32_t strideY)
void add_biasEnabled (bool biasEnabled)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
TransposeConvolution2dDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
TransposeConvolution2dDescriptorBuilder & operator= (const TransposeConvolution2dDescriptorBuilder &)
flatbuffers::Offset< TransposeConvolution2dDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9423 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef TransposeConvolution2dDescriptor Table
Definition at line 9424 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
TransposeConvolution2dDescriptorBuilder()
TransposeConvolution2dDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9451 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_biasEnabled()
void add_biasEnabled (bool biasEnabled) inline
Definition at line 9445 of file ArmnnSchema_generated.h.
References VT_BIASENABLED.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint8_t>(TransposeConvolution2dDescriptor::VT_BIASENABLED, static_cast<uint8_t>(biasEnabled), 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 9448 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<int8_t>(TransposeConvolution2dDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 1);
   }
add_padBottom()
void add_padBottom (uint32_t padBottom) inline
Definition at line 9436 of file ArmnnSchema_generated.h.
References VT_PADBOTTOM.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(TransposeConvolution2dDescriptor::VT_PADBOTTOM, padBottom, 0);
   }
add_padLeft()
void add_padLeft (uint32_t padLeft) inline
Definition at line 9427 of file ArmnnSchema_generated.h.
References VT_PADLEFT.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(TransposeConvolution2dDescriptor::VT_PADLEFT, padLeft, 0);
   }
add_padRight()
void add_padRight (uint32_t padRight) inline
Definition at line 9430 of file ArmnnSchema_generated.h.
References VT_PADRIGHT.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(TransposeConvolution2dDescriptor::VT_PADRIGHT, padRight, 0);
   }
add_padTop()
void add_padTop (uint32_t padTop) inline
Definition at line 9433 of file ArmnnSchema_generated.h.
References VT_PADTOP.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(TransposeConvolution2dDescriptor::VT_PADTOP, padTop, 0);
   }
add_strideX()
void add_strideX (uint32_t strideX) inline
Definition at line 9439 of file ArmnnSchema_generated.h.
References VT_STRIDEX.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(TransposeConvolution2dDescriptor::VT_STRIDEX, strideX, 0);
   }
add_strideY()
void add_strideY (uint32_t strideY) inline
Definition at line 9442 of file ArmnnSchema_generated.h.
References VT_STRIDEY.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(TransposeConvolution2dDescriptor::VT_STRIDEY, strideY, 0);
   }
Finish()
flatbuffers::Offset<TransposeConvolution2dDescriptor> Finish () inline
Definition at line 9456 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateTransposeConvolution2dDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<TransposeConvolution2dDescriptor>(end);
     return o;
   }
operator=()
TransposeConvolution2dDescriptorBuilder& operator= (const TransposeConvolution2dDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9425 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9426 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h