ArmNN: Pooling2dDescriptorBuilder Struct Reference
Pooling2dDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Pooling2dDescriptor Table
Public Member Functions
void add_poolType (armnnSerializer::PoolingAlgorithm poolType)
void add_padLeft (uint32_t padLeft)
void add_padRight (uint32_t padRight)
void add_padTop (uint32_t padTop)
void add_padBottom (uint32_t padBottom)
void add_poolWidth (uint32_t poolWidth)
void add_poolHeight (uint32_t poolHeight)
void add_strideX (uint32_t strideX)
void add_strideY (uint32_t strideY)
void add_outputShapeRounding (armnnSerializer::OutputShapeRounding outputShapeRounding)
void add_paddingMethod (armnnSerializer::PaddingMethod paddingMethod)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
Pooling2dDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Pooling2dDescriptorBuilder & operator= (const Pooling2dDescriptorBuilder &)
flatbuffers::Offset< Pooling2dDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5017 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Pooling2dDescriptor Table
Definition at line 5018 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Pooling2dDescriptorBuilder()
Pooling2dDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5057 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 5054 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling2dDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_outputShapeRounding()
void add_outputShapeRounding (armnnSerializer::OutputShapeRounding outputShapeRounding) inline
Definition at line 5048 of file ArmnnSchema_generated.h.
References VT_OUTPUTSHAPEROUNDING.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling2dDescriptor::VT_OUTPUTSHAPEROUNDING, static_cast<int8_t>(outputShapeRounding), 0);
   }
add_padBottom()
void add_padBottom (uint32_t padBottom) inline
Definition at line 5033 of file ArmnnSchema_generated.h.
References VT_PADBOTTOM.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_PADBOTTOM, padBottom, 0);
   }
add_paddingMethod()
void add_paddingMethod (armnnSerializer::PaddingMethod paddingMethod) inline
Definition at line 5051 of file ArmnnSchema_generated.h.
References VT_PADDINGMETHOD.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling2dDescriptor::VT_PADDINGMETHOD, static_cast<int8_t>(paddingMethod), 0);
   }
add_padLeft()
void add_padLeft (uint32_t padLeft) inline
Definition at line 5024 of file ArmnnSchema_generated.h.
References VT_PADLEFT.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_PADLEFT, padLeft, 0);
   }
add_padRight()
void add_padRight (uint32_t padRight) inline
Definition at line 5027 of file ArmnnSchema_generated.h.
References VT_PADRIGHT.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_PADRIGHT, padRight, 0);
   }
add_padTop()
void add_padTop (uint32_t padTop) inline
Definition at line 5030 of file ArmnnSchema_generated.h.
References VT_PADTOP.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_PADTOP, padTop, 0);
   }
add_poolHeight()
void add_poolHeight (uint32_t poolHeight) inline
Definition at line 5039 of file ArmnnSchema_generated.h.
References VT_POOLHEIGHT.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_POOLHEIGHT, poolHeight, 0);
   }
add_poolType()
void add_poolType (armnnSerializer::PoolingAlgorithm poolType) inline
Definition at line 5021 of file ArmnnSchema_generated.h.
References VT_POOLTYPE.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling2dDescriptor::VT_POOLTYPE, static_cast<int8_t>(poolType), 0);
   }
add_poolWidth()
void add_poolWidth (uint32_t poolWidth) inline
Definition at line 5036 of file ArmnnSchema_generated.h.
References VT_POOLWIDTH.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_POOLWIDTH, poolWidth, 0);
   }
add_strideX()
void add_strideX (uint32_t strideX) inline
Definition at line 5042 of file ArmnnSchema_generated.h.
References VT_STRIDEX.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_STRIDEX, strideX, 0);
   }
add_strideY()
void add_strideY (uint32_t strideY) inline
Definition at line 5045 of file ArmnnSchema_generated.h.
References VT_STRIDEY.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling2dDescriptor::VT_STRIDEY, strideY, 0);
   }
Finish()
flatbuffers::Offset<Pooling2dDescriptor> Finish () inline
Definition at line 5062 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePooling2dDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Pooling2dDescriptor>(end);
     return o;
   }
operator=()
Pooling2dDescriptorBuilder& operator= (const Pooling2dDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5019 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5020 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h