ArmNN: Pooling3dDescriptorBuilder Struct Reference
Pooling3dDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Pooling3dDescriptor Table
Public Member Functions
void add_poolType (armnnSerializer::PoolingAlgorithm poolType)
void add_padLeft (uint32_t padLeft)
void add_padRight (uint32_t padRight)
void add_padTop (uint32_t padTop)
void add_padBottom (uint32_t padBottom)
void add_padFront (uint32_t padFront)
void add_padBack (uint32_t padBack)
void add_poolWidth (uint32_t poolWidth)
void add_poolHeight (uint32_t poolHeight)
void add_poolDepth (uint32_t poolDepth)
void add_strideX (uint32_t strideX)
void add_strideY (uint32_t strideY)
void add_strideZ (uint32_t strideZ)
void add_outputShapeRounding (armnnSerializer::OutputShapeRounding outputShapeRounding)
void add_paddingMethod (armnnSerializer::PaddingMethod paddingMethod)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
Pooling3dDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Pooling3dDescriptorBuilder & operator= (const Pooling3dDescriptorBuilder &)
flatbuffers::Offset< Pooling3dDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5189 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Pooling3dDescriptor Table
Definition at line 5190 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Pooling3dDescriptorBuilder()
Pooling3dDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5241 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 5238 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling3dDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_outputShapeRounding()
void add_outputShapeRounding (armnnSerializer::OutputShapeRounding outputShapeRounding) inline
Definition at line 5232 of file ArmnnSchema_generated.h.
References VT_OUTPUTSHAPEROUNDING.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling3dDescriptor::VT_OUTPUTSHAPEROUNDING, static_cast<int8_t>(outputShapeRounding), 0);
   }
add_padBack()
void add_padBack (uint32_t padBack) inline
Definition at line 5211 of file ArmnnSchema_generated.h.
References VT_PADBACK.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_PADBACK, padBack, 0);
   }
add_padBottom()
void add_padBottom (uint32_t padBottom) inline
Definition at line 5205 of file ArmnnSchema_generated.h.
References VT_PADBOTTOM.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_PADBOTTOM, padBottom, 0);
   }
add_paddingMethod()
void add_paddingMethod (armnnSerializer::PaddingMethod paddingMethod) inline
Definition at line 5235 of file ArmnnSchema_generated.h.
References VT_PADDINGMETHOD.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling3dDescriptor::VT_PADDINGMETHOD, static_cast<int8_t>(paddingMethod), 0);
   }
add_padFront()
void add_padFront (uint32_t padFront) inline
Definition at line 5208 of file ArmnnSchema_generated.h.
References VT_PADFRONT.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_PADFRONT, padFront, 0);
   }
add_padLeft()
void add_padLeft (uint32_t padLeft) inline
Definition at line 5196 of file ArmnnSchema_generated.h.
References VT_PADLEFT.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_PADLEFT, padLeft, 0);
   }
add_padRight()
void add_padRight (uint32_t padRight) inline
Definition at line 5199 of file ArmnnSchema_generated.h.
References VT_PADRIGHT.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_PADRIGHT, padRight, 0);
   }
add_padTop()
void add_padTop (uint32_t padTop) inline
Definition at line 5202 of file ArmnnSchema_generated.h.
References VT_PADTOP.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_PADTOP, padTop, 0);
   }
add_poolDepth()
void add_poolDepth (uint32_t poolDepth) inline
Definition at line 5220 of file ArmnnSchema_generated.h.
References VT_POOLDEPTH.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_POOLDEPTH, poolDepth, 0);
   }
add_poolHeight()
void add_poolHeight (uint32_t poolHeight) inline
Definition at line 5217 of file ArmnnSchema_generated.h.
References VT_POOLHEIGHT.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_POOLHEIGHT, poolHeight, 0);
   }
add_poolType()
void add_poolType (armnnSerializer::PoolingAlgorithm poolType) inline
Definition at line 5193 of file ArmnnSchema_generated.h.
References VT_POOLTYPE.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<int8_t>(Pooling3dDescriptor::VT_POOLTYPE, static_cast<int8_t>(poolType), 0);
   }
add_poolWidth()
void add_poolWidth (uint32_t poolWidth) inline
Definition at line 5214 of file ArmnnSchema_generated.h.
References VT_POOLWIDTH.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_POOLWIDTH, poolWidth, 0);
   }
add_strideX()
void add_strideX (uint32_t strideX) inline
Definition at line 5223 of file ArmnnSchema_generated.h.
References VT_STRIDEX.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_STRIDEX, strideX, 0);
   }
add_strideY()
void add_strideY (uint32_t strideY) inline
Definition at line 5226 of file ArmnnSchema_generated.h.
References VT_STRIDEY.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_STRIDEY, strideY, 0);
   }
add_strideZ()
void add_strideZ (uint32_t strideZ) inline
Definition at line 5229 of file ArmnnSchema_generated.h.
References VT_STRIDEZ.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     fbb_.AddElement<uint32_t>(Pooling3dDescriptor::VT_STRIDEZ, strideZ, 0);
   }
Finish()
flatbuffers::Offset<Pooling3dDescriptor> Finish () inline
Definition at line 5246 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePooling3dDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Pooling3dDescriptor>(end);
     return o;
   }
operator=()
Pooling3dDescriptorBuilder& operator= (const Pooling3dDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5191 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5192 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h