ArmNN: QLstmInputParamsBuilder Struct Reference
QLstmInputParamsBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef QLstmInputParams Table
Public Member Functions
void add_inputToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights)
void add_inputToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights)
void add_inputToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights)
void add_recurrentToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights)
void add_recurrentToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights)
void add_recurrentToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights)
void add_forgetGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias)
void add_cellBias (flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias)
void add_outputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias)
void add_inputToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights)
void add_recurrentToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights)
void add_inputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias)
void add_projectionWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights)
void add_projectionBias (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias)
void add_cellToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights)
void add_cellToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights)
void add_cellToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights)
void add_inputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights)
void add_forgetLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights)
void add_cellLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights)
void add_outputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights)
QLstmInputParamsBuilder (flatbuffers::FlatBufferBuilder &_fbb)
QLstmInputParamsBuilder & operator= (const QLstmInputParamsBuilder &)
flatbuffers::Offset< QLstmInputParams > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8563 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef QLstmInputParams Table
Definition at line 8564 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
QLstmInputParamsBuilder()
QLstmInputParamsBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8630 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_cellBias()
void add_cellBias (flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias) inline
Definition at line 8588 of file ArmnnSchema_generated.h.
References VT_CELLBIAS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_CELLBIAS, cellBias);
   }
add_cellLayerNormWeights()
void add_cellLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights) inline
Definition at line 8624 of file ArmnnSchema_generated.h.
References VT_CELLLAYERNORMWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_CELLLAYERNORMWEIGHTS, cellLayerNormWeights);
   }
add_cellToForgetWeights()
void add_cellToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights) inline
Definition at line 8612 of file ArmnnSchema_generated.h.
References VT_CELLTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_CELLTOFORGETWEIGHTS, cellToForgetWeights);
   }
add_cellToInputWeights()
void add_cellToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights) inline
Definition at line 8609 of file ArmnnSchema_generated.h.
References VT_CELLTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_CELLTOINPUTWEIGHTS, cellToInputWeights);
   }
add_cellToOutputWeights()
void add_cellToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights) inline
Definition at line 8615 of file ArmnnSchema_generated.h.
References VT_CELLTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_CELLTOOUTPUTWEIGHTS, cellToOutputWeights);
   }
add_forgetGateBias()
void add_forgetGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias) inline
Definition at line 8585 of file ArmnnSchema_generated.h.
References VT_FORGETGATEBIAS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_FORGETGATEBIAS, forgetGateBias);
   }
add_forgetLayerNormWeights()
void add_forgetLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights) inline
Definition at line 8621 of file ArmnnSchema_generated.h.
References VT_FORGETLAYERNORMWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_FORGETLAYERNORMWEIGHTS, forgetLayerNormWeights);
   }
add_inputGateBias()
void add_inputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias) inline
Definition at line 8600 of file ArmnnSchema_generated.h.
References VT_INPUTGATEBIAS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_INPUTGATEBIAS, inputGateBias);
   }
add_inputLayerNormWeights()
void add_inputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights) inline
Definition at line 8618 of file ArmnnSchema_generated.h.
References VT_INPUTLAYERNORMWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_INPUTLAYERNORMWEIGHTS, inputLayerNormWeights);
   }
add_inputToCellWeights()
void add_inputToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights) inline
Definition at line 8570 of file ArmnnSchema_generated.h.
References VT_INPUTTOCELLWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_INPUTTOCELLWEIGHTS, inputToCellWeights);
   }
add_inputToForgetWeights()
void add_inputToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights) inline
Definition at line 8567 of file ArmnnSchema_generated.h.
References VT_INPUTTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_INPUTTOFORGETWEIGHTS, inputToForgetWeights);
   }
add_inputToInputWeights()
void add_inputToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights) inline
Definition at line 8594 of file ArmnnSchema_generated.h.
References VT_INPUTTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_INPUTTOINPUTWEIGHTS, inputToInputWeights);
   }
add_inputToOutputWeights()
void add_inputToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights) inline
Definition at line 8573 of file ArmnnSchema_generated.h.
References VT_INPUTTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_INPUTTOOUTPUTWEIGHTS, inputToOutputWeights);
   }
add_outputGateBias()
void add_outputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias) inline
Definition at line 8591 of file ArmnnSchema_generated.h.
References VT_OUTPUTGATEBIAS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_OUTPUTGATEBIAS, outputGateBias);
   }
add_outputLayerNormWeights()
void add_outputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights) inline
Definition at line 8627 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_OUTPUTLAYERNORMWEIGHTS, outputLayerNormWeights);
   }
add_projectionBias()
void add_projectionBias (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias) inline
Definition at line 8606 of file ArmnnSchema_generated.h.
References VT_PROJECTIONBIAS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_PROJECTIONBIAS, projectionBias);
   }
add_projectionWeights()
void add_projectionWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights) inline
Definition at line 8603 of file ArmnnSchema_generated.h.
References VT_PROJECTIONWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_PROJECTIONWEIGHTS, projectionWeights);
   }
add_recurrentToCellWeights()
void add_recurrentToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights) inline
Definition at line 8579 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOCELLWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_RECURRENTTOCELLWEIGHTS, recurrentToCellWeights);
   }
add_recurrentToForgetWeights()
void add_recurrentToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights) inline
Definition at line 8576 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_RECURRENTTOFORGETWEIGHTS, recurrentToForgetWeights);
   }
add_recurrentToInputWeights()
void add_recurrentToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights) inline
Definition at line 8597 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_RECURRENTTOINPUTWEIGHTS, recurrentToInputWeights);
   }
add_recurrentToOutputWeights()
void add_recurrentToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights) inline
Definition at line 8582 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     fbb_.AddOffset(QLstmInputParams::VT_RECURRENTTOOUTPUTWEIGHTS, recurrentToOutputWeights);
   }
Finish()
flatbuffers::Offset<QLstmInputParams> Finish () inline
Definition at line 8635 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQLstmInputParams().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<QLstmInputParams>(end);
     return o;
   }
operator=()
QLstmInputParamsBuilder& operator= (const QLstmInputParamsBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8565 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8566 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h