ArmNN: SliceLayerBuilder Struct Reference
SliceLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SliceLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::SliceDescriptor > descriptor)
SliceLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SliceLayerBuilder & operator= (const SliceLayerBuilder &)
flatbuffers::Offset< SliceLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7116 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SliceLayer Table
Definition at line 7117 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SliceLayerBuilder()
SliceLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7126 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 7120 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateSliceLayer().
{
     fbb_.AddOffset(SliceLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::SliceDescriptor > descriptor) inline
Definition at line 7123 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateSliceLayer().
{
     fbb_.AddOffset(SliceLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<SliceLayer> Finish () inline
Definition at line 7131 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSliceLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SliceLayer>(end);
     return o;
   }
operator=()
SliceLayerBuilder& operator= (const SliceLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7118 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7119 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h