ArmNN: StackDescriptorBuilder Struct Reference
StackDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef StackDescriptor Table
Public Member Functions
void add_axis (uint32_t axis)
void add_numInputs (uint32_t numInputs)
void add_inputShape (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> inputShape)
StackDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
StackDescriptorBuilder & operator= (const StackDescriptorBuilder &)
flatbuffers::Offset< StackDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9817 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef StackDescriptor Table
Definition at line 9818 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
StackDescriptorBuilder()
StackDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9830 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_axis()
void add_axis (uint32_t axis) inline
Definition at line 9821 of file ArmnnSchema_generated.h.
References VT_AXIS.
Referenced by armnnSerializer::CreateStackDescriptor().
{
     fbb_.AddElement<uint32_t>(StackDescriptor::VT_AXIS, axis, 0);
   }
add_inputShape()
void add_inputShape (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> inputShape) inline
Definition at line 9827 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateStackDescriptor().
{
     fbb_.AddOffset(StackDescriptor::VT_INPUTSHAPE, inputShape);
   }
add_numInputs()
void add_numInputs (uint32_t numInputs) inline
Definition at line 9824 of file ArmnnSchema_generated.h.
References VT_NUMINPUTS.
Referenced by armnnSerializer::CreateStackDescriptor().
{
     fbb_.AddElement<uint32_t>(StackDescriptor::VT_NUMINPUTS, numInputs, 0);
   }
Finish()
flatbuffers::Offset<StackDescriptor> Finish () inline
Definition at line 9835 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateStackDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<StackDescriptor>(end);
     return o;
   }
operator=()
StackDescriptorBuilder& operator= (const StackDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9819 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9820 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h