ArmNN: PadLayerBuilder Struct Reference
PadLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef PadLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::PadDescriptor > descriptor)
PadLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
PadLayerBuilder & operator= (const PadLayerBuilder &)
flatbuffers::Offset< PadLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6655 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef PadLayer Table
Definition at line 6656 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
PadLayerBuilder()
PadLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6665 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 6659 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreatePadLayer().
{
     fbb_.AddOffset(PadLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::PadDescriptor > descriptor) inline
Definition at line 6662 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreatePadLayer().
{
     fbb_.AddOffset(PadLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<PadLayer> Finish () inline
Definition at line 6670 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePadLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<PadLayer>(end);
     return o;
   }
operator=()
PadLayerBuilder& operator= (const PadLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6657 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6658 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h