ArmNN: DetectionPostProcessDescriptorBuilder Struct Reference
DetectionPostProcessDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef DetectionPostProcessDescriptor Table
Public Member Functions
void add_maxDetections (uint32_t maxDetections)
void add_maxClassesPerDetection (uint32_t maxClassesPerDetection)
void add_detectionsPerClass (uint32_t detectionsPerClass)
void add_nmsScoreThreshold (float nmsScoreThreshold)
void add_nmsIouThreshold (float nmsIouThreshold)
void add_numClasses (uint32_t numClasses)
void add_useRegularNms (bool useRegularNms)
void add_scaleX (float scaleX)
void add_scaleY (float scaleY)
void add_scaleW (float scaleW)
void add_scaleH (float scaleH)
DetectionPostProcessDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
DetectionPostProcessDescriptorBuilder & operator= (const DetectionPostProcessDescriptorBuilder &)
flatbuffers::Offset< DetectionPostProcessDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7920 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef DetectionPostProcessDescriptor Table
Definition at line 7921 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
DetectionPostProcessDescriptorBuilder()
DetectionPostProcessDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7957 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_detectionsPerClass()
void add_detectionsPerClass (uint32_t detectionsPerClass) inline
Definition at line 7930 of file ArmnnSchema_generated.h.
References VT_DETECTIONSPERCLASS.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<uint32_t>(DetectionPostProcessDescriptor::VT_DETECTIONSPERCLASS, detectionsPerClass, 0);
   }
add_maxClassesPerDetection()
void add_maxClassesPerDetection (uint32_t maxClassesPerDetection) inline
Definition at line 7927 of file ArmnnSchema_generated.h.
References VT_MAXCLASSESPERDETECTION.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<uint32_t>(DetectionPostProcessDescriptor::VT_MAXCLASSESPERDETECTION, maxClassesPerDetection, 0);
   }
add_maxDetections()
void add_maxDetections (uint32_t maxDetections) inline
Definition at line 7924 of file ArmnnSchema_generated.h.
References VT_MAXDETECTIONS.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<uint32_t>(DetectionPostProcessDescriptor::VT_MAXDETECTIONS, maxDetections, 0);
   }
add_nmsIouThreshold()
void add_nmsIouThreshold (float nmsIouThreshold) inline
Definition at line 7936 of file ArmnnSchema_generated.h.
References VT_NMSIOUTHRESHOLD.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<float>(DetectionPostProcessDescriptor::VT_NMSIOUTHRESHOLD, nmsIouThreshold, 0.0f);
   }
add_nmsScoreThreshold()
void add_nmsScoreThreshold (float nmsScoreThreshold) inline
Definition at line 7933 of file ArmnnSchema_generated.h.
References VT_NMSSCORETHRESHOLD.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<float>(DetectionPostProcessDescriptor::VT_NMSSCORETHRESHOLD, nmsScoreThreshold, 0.0f);
   }
add_numClasses()
void add_numClasses (uint32_t numClasses) inline
Definition at line 7939 of file ArmnnSchema_generated.h.
References VT_NUMCLASSES.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<uint32_t>(DetectionPostProcessDescriptor::VT_NUMCLASSES, numClasses, 0);
   }
add_scaleH()
void add_scaleH (float scaleH) inline
Definition at line 7954 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<float>(DetectionPostProcessDescriptor::VT_SCALEH, scaleH, 0.0f);
   }
add_scaleW()
void add_scaleW (float scaleW) inline
Definition at line 7951 of file ArmnnSchema_generated.h.
References VT_SCALEW.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<float>(DetectionPostProcessDescriptor::VT_SCALEW, scaleW, 0.0f);
   }
add_scaleX()
void add_scaleX (float scaleX) inline
Definition at line 7945 of file ArmnnSchema_generated.h.
References VT_SCALEX.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<float>(DetectionPostProcessDescriptor::VT_SCALEX, scaleX, 0.0f);
   }
add_scaleY()
void add_scaleY (float scaleY) inline
Definition at line 7948 of file ArmnnSchema_generated.h.
References VT_SCALEY.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<float>(DetectionPostProcessDescriptor::VT_SCALEY, scaleY, 0.0f);
   }
add_useRegularNms()
void add_useRegularNms (bool useRegularNms) inline
Definition at line 7942 of file ArmnnSchema_generated.h.
References VT_USEREGULARNMS.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     fbb_.AddElement<uint8_t>(DetectionPostProcessDescriptor::VT_USEREGULARNMS, static_cast<uint8_t>(useRegularNms), 0);
   }
Finish()
flatbuffers::Offset<DetectionPostProcessDescriptor> Finish () inline
Definition at line 7962 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDetectionPostProcessDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<DetectionPostProcessDescriptor>(end);
     return o;
   }
operator=()
DetectionPostProcessDescriptorBuilder& operator= (const DetectionPostProcessDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7922 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7923 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h