var searchData=
[
  ['sampledynamicadditionworkload_0',['SampleDynamicAdditionWorkload',['../classsdb_1_1_sample_dynamic_addition_workload.html',1,'sdb']]],
  ['sampledynamiclayersupport_1',['SampleDynamicLayerSupport',['../classsdb_1_1_sample_dynamic_layer_support.html',1,'sdb']]],
  ['sampledynamictensorhandlefactory_2',['SampleDynamicTensorHandleFactory',['../classsdb_1_1_sample_dynamic_tensor_handle_factory.html',1,'sdb']]],
  ['sampledynamicworkloadfactory_3',['SampleDynamicWorkloadFactory',['../classsdb_1_1_sample_dynamic_workload_factory.html',1,'sdb']]],
  ['samplememorymanager_4',['SampleMemoryManager',['../classsdb_1_1_sample_memory_manager.html',1,'sdb']]],
  ['sampletensorhandle_5',['SampleTensorHandle',['../classsdb_1_1_sample_tensor_handle.html',1,'sdb']]],
  ['scaledint32decoder_6',['ScaledInt32Decoder',['../classarmnn_1_1_scaled_int32_decoder.html',1,'armnn']]],
  ['scaledint32peraxisdecoder_7',['ScaledInt32PerAxisDecoder',['../classarmnn_1_1_scaled_int32_per_axis_decoder.html',1,'armnn']]],
  ['scatternddescriptor_8',['ScatterNdDescriptor',['../structarmnn_1_1_scatter_nd_descriptor.html',1,'armnn']]],
  ['scatterndlayer_9',['ScatterNdLayer',['../classarmnn_1_1_scatter_nd_layer.html',1,'armnn']]],
  ['scatterndqueuedescriptor_10',['ScatterNdQueueDescriptor',['../structarmnn_1_1_scatter_nd_queue_descriptor.html',1,'armnn']]],
  ['scopedprofilingevent_11',['ScopedProfilingEvent',['../classarmnn_1_1_scoped_profiling_event.html',1,'armnn']]],
  ['scopedrecord_12',['ScopedRecord',['../structarmnn_1_1_scoped_record.html',1,'armnn']]],
  ['scopedtensorhandle_13',['ScopedTensorHandle',['../classarmnn_1_1_scoped_tensor_handle.html',1,'armnn']]],
  ['selectivequantizer_14',['SelectiveQuantizer',['../structarmnn_utils_1_1_selective_quantizer.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3abfloat16_2c_20false_20_3e_15',['SelectiveQuantizer&lt; armnn::BFloat16, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_b_float16_00_01false_01_4.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3ahalf_2c_20false_20_3e_16',['SelectiveQuantizer&lt; armnn::Half, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_half_00_01false_01_4.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20t_2c_20false_20_3e_17',['SelectiveQuantizer&lt; T, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01_t_00_01false_01_4.html',1,'armnnUtils']]],
  ['serializerimpl_18',['SerializerImpl',['../classarmnn_serializer_1_1_i_serializer_1_1_serializer_impl.html',1,'armnnSerializer::ISerializer']]],
  ['serializerstrategy_19',['SerializerStrategy',['../classarmnn_serializer_1_1_serializer_strategy.html',1,'armnnSerializer']]],
  ['shapelayer_20',['ShapeLayer',['../classarmnn_1_1_shape_layer.html',1,'armnn']]],
  ['shapequeuedescriptor_21',['ShapeQueueDescriptor',['../structarmnn_1_1_shape_queue_descriptor.html',1,'armnn']]],
  ['shapesarebroadcastcompatible_22',['ShapesAreBroadcastCompatible',['../structarmnn_1_1_shapes_are_broadcast_compatible.html',1,'armnn']]],
  ['shapesaresamerank_23',['ShapesAreSameRank',['../structarmnn_1_1_shapes_are_same_rank.html',1,'armnn']]],
  ['shapesaresametotalsize_24',['ShapesAreSameTotalSize',['../structarmnn_1_1_shapes_are_same_total_size.html',1,'armnn']]],
  ['simplelogger_25',['SimpleLogger',['../classarmnn_1_1_simple_logger.html',1,'armnn']]],
  ['sin_26',['sin',['../structarmnn_1_1sin.html',1,'armnn']]],
  ['singleaxisprioritylist_27',['SingleAxisPriorityList',['../classarmnn_1_1_single_axis_priority_list.html',1,'armnn']]],
  ['slicedescriptor_28',['SliceDescriptor',['../structarmnn_1_1_slice_descriptor.html',1,'armnn']]],
  ['slicelayer_29',['SliceLayer',['../classarmnn_1_1_slice_layer.html',1,'armnn']]],
  ['slicequeuedescriptor_30',['SliceQueueDescriptor',['../structarmnn_1_1_slice_queue_descriptor.html',1,'armnn']]],
  ['softmaxdescriptor_31',['SoftmaxDescriptor',['../structarmnn_1_1_softmax_descriptor.html',1,'armnn']]],
  ['softmaxlayer_32',['SoftmaxLayer',['../classarmnn_1_1_softmax_layer.html',1,'armnn']]],
  ['softmaxqueuedescriptor_33',['SoftmaxQueueDescriptor',['../structarmnn_1_1_softmax_queue_descriptor.html',1,'armnn']]],
  ['spacetobatchnddescriptor_34',['SpaceToBatchNdDescriptor',['../structarmnn_1_1_space_to_batch_nd_descriptor.html',1,'armnn']]],
  ['spacetobatchndlayer_35',['SpaceToBatchNdLayer',['../classarmnn_1_1_space_to_batch_nd_layer.html',1,'armnn']]],
  ['spacetobatchndqueuedescriptor_36',['SpaceToBatchNdQueueDescriptor',['../structarmnn_1_1_space_to_batch_nd_queue_descriptor.html',1,'armnn']]],
  ['spacetodepthdescriptor_37',['SpaceToDepthDescriptor',['../structarmnn_1_1_space_to_depth_descriptor.html',1,'armnn']]],
  ['spacetodepthlayer_38',['SpaceToDepthLayer',['../classarmnn_1_1_space_to_depth_layer.html',1,'armnn']]],
  ['spacetodepthqueuedescriptor_39',['SpaceToDepthQueueDescriptor',['../structarmnn_1_1_space_to_depth_queue_descriptor.html',1,'armnn']]],
  ['splitterlayer_40',['SplitterLayer',['../classarmnn_1_1_splitter_layer.html',1,'armnn']]],
  ['splitterqueuedescriptor_41',['SplitterQueueDescriptor',['../structarmnn_1_1_splitter_queue_descriptor.html',1,'armnn']]],
  ['sqrt_42',['sqrt',['../structarmnn_1_1sqrt.html',1,'armnn']]],
  ['squareddifference_43',['squaredDifference',['../structarmnn_1_1squared_difference.html',1,'armnn']]],
  ['squashequalsiblingsimpl_44',['SquashEqualSiblingsImpl',['../classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl.html',1,'armnn::optimizations']]],
  ['stackdescriptor_45',['StackDescriptor',['../structarmnn_1_1_stack_descriptor.html',1,'armnn']]],
  ['stacklayer_46',['StackLayer',['../classarmnn_1_1_stack_layer.html',1,'armnn']]],
  ['stackqueuedescriptor_47',['StackQueueDescriptor',['../structarmnn_1_1_stack_queue_descriptor.html',1,'armnn']]],
  ['standardoutputsink_48',['StandardOutputSink',['../classarmnn_1_1_standard_output_sink.html',1,'armnn']]],
  ['standindescriptor_49',['StandInDescriptor',['../structarmnn_1_1_stand_in_descriptor.html',1,'armnn']]],
  ['standinlayer_50',['StandInLayer',['../classarmnn_1_1_stand_in_layer.html',1,'armnn']]],
  ['staticregistryinitializer_51',['StaticRegistryInitializer',['../structarmnn_1_1_backend_registry_1_1_static_registry_initializer.html',1,'armnn::BackendRegistry']]],
  ['strategybase_52',['StrategyBase',['../classarmnn_1_1_strategy_base.html',1,'armnn']]],
  ['strategyfactory_53',['StrategyFactory',['../structarmnn_1_1_strategy_factory.html',1,'armnn']]],
  ['strategyvalidator_54',['StrategyValidator',['../classarmnn_1_1_strategy_validator.html',1,'armnn']]],
  ['stridedslicedescriptor_55',['StridedSliceDescriptor',['../structarmnn_1_1_strided_slice_descriptor.html',1,'armnn']]],
  ['stridedslicelayer_56',['StridedSliceLayer',['../classarmnn_1_1_strided_slice_layer.html',1,'armnn']]],
  ['stridedslicequeuedescriptor_57',['StridedSliceQueueDescriptor',['../structarmnn_1_1_strided_slice_queue_descriptor.html',1,'armnn']]],
  ['stringifylayerparameters_58',['StringifyLayerParameters',['../structarmnn_1_1_stringify_layer_parameters.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20activationdescriptor_20_3e_59',['StringifyLayerParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_activation_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchmatmuldescriptor_20_3e_60',['StringifyLayerParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_mat_mul_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchnormalizationdescriptor_20_3e_61',['StringifyLayerParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchtospacenddescriptor_20_3e_62',['StringifyLayerParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_to_space_nd_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20channelshuffledescriptor_20_3e_63',['StringifyLayerParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_channel_shuffle_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20comparisondescriptor_20_3e_64',['StringifyLayerParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_comparison_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution2ddescriptor_20_3e_65',['StringifyLayerParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution3ddescriptor_20_3e_66',['StringifyLayerParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution3d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_67',['StringifyLayerParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_depthwise_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20detectionpostprocessdescriptor_20_3e_68',['StringifyLayerParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_detection_post_process_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwisebinarydescriptor_20_3e_69',['StringifyLayerParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_binary_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwiseunarydescriptor_20_3e_70',['StringifyLayerParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_unary_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fakequantizationdescriptor_20_3e_71',['StringifyLayerParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fake_quantization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fullyconnecteddescriptor_20_3e_72',['StringifyLayerParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fully_connected_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fuseddescriptor_20_3e_73',['StringifyLayerParameters&lt; FusedDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fused_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20gatherdescriptor_20_3e_74',['StringifyLayerParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_gather_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20l2normalizationdescriptor_20_3e_75',['StringifyLayerParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_l2_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20lstmdescriptor_20_3e_76',['StringifyLayerParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_lstm_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20meandescriptor_20_3e_77',['StringifyLayerParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_mean_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20normalizationdescriptor_20_3e_78',['StringifyLayerParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20originsdescriptor_20_3e_79',['StringifyLayerParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_origins_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20paddescriptor_20_3e_80',['StringifyLayerParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pad_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20permutedescriptor_20_3e_81',['StringifyLayerParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_permute_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling2ddescriptor_20_3e_82',['StringifyLayerParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling3ddescriptor_20_3e_83',['StringifyLayerParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling3d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20precompileddescriptor_20_3e_84',['StringifyLayerParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pre_compiled_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20reducedescriptor_20_3e_85',['StringifyLayerParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reduce_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20reshapedescriptor_20_3e_86',['StringifyLayerParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reshape_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20resizedescriptor_20_3e_87',['StringifyLayerParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_resize_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20softmaxdescriptor_20_3e_88',['StringifyLayerParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_softmax_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetobatchnddescriptor_20_3e_89',['StringifyLayerParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_batch_nd_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetodepthdescriptor_20_3e_90',['StringifyLayerParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_depth_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20stackdescriptor_20_3e_91',['StringifyLayerParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_stack_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20stridedslicedescriptor_20_3e_92',['StringifyLayerParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_strided_slice_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20tiledescriptor_20_3e_93',['StringifyLayerParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_tile_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposeconvolution2ddescriptor_20_3e_94',['StringifyLayerParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposedescriptor_20_3e_95',['StringifyLayerParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20viewsdescriptor_20_3e_96',['StringifyLayerParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_views_descriptor_01_4.html',1,'armnn']]],
  ['stringmapping_97',['StringMapping',['../structarmnn_1_1_string_mapping.html',1,'armnn']]],
  ['subgraphview_98',['SubgraphView',['../classarmnn_1_1_subgraph_view.html',1,'armnn']]],
  ['subgraphviewselector_99',['SubgraphViewSelector',['../classarmnn_1_1_subgraph_view_selector.html',1,'armnn']]],
  ['substitutionpair_100',['SubstitutionPair',['../structarmnn_1_1_optimization_views_1_1_substitution_pair.html',1,'armnn::OptimizationViews']]],
  ['subtractionlayer_101',['SubtractionLayer',['../classarmnn_1_1_subtraction_layer.html',1,'armnn']]],
  ['subtractionqueuedescriptor_102',['SubtractionQueueDescriptor',['../structarmnn_1_1_subtraction_queue_descriptor.html',1,'armnn']]],
  ['switchlayer_103',['SwitchLayer',['../classarmnn_1_1_switch_layer.html',1,'armnn']]],
  ['switchqueuedescriptor_104',['SwitchQueueDescriptor',['../structarmnn_1_1_switch_queue_descriptor.html',1,'armnn']]],
  ['syncmemgenericworkload_105',['SyncMemGenericWorkload',['../classarmnn_1_1_sync_mem_generic_workload.html',1,'armnn']]]
];
