Arm NN: src/backends/tosaCommon/operatorMappings/TransposeOperator.hpp File Reference
TransposeOperator.hpp File Reference
#include "TosaOperatorUtils.hpp"
#include <Layer.hpp>
#include <tosa_serialization_handler.h>
Functions
TosaSerializationBasicBlock * ConvertTransposeToTosaOperator (const Layer *layer, const std::vector< const TensorInfo * > &inputs, const std::vector< const TensorInfo * > &outputs, const TransposeDescriptor *transposeDescriptor)
Function Documentation
ConvertTransposeToTosaOperator()
TosaSerializationBasicBlock* ConvertTransposeToTosaOperator (const Layer * layer, const std::vector< const TensorInfo * > & inputs, const std::vector< const TensorInfo * > & outputs, const TransposeDescriptor * transposeDescriptor)
Definition at line 8 of file TransposeOperator.cpp.
 {
     std::string input0Name = std::string("input0_");
     std::string outputName = std::string("output0_");
     std::string blockName  = std::string("Op_TRANSPOSE_block_") + GetUniqueTosaMappingID();
     // If a layer is present then the block will be used for execution, so input and output names need to be determined
     // using the previous and following layers so the graph is connected correctly. For validation this doesn't matter.
     if(layer != nullptr)
     {
         // Get the layers connected to the input slot and determine unique tensor name.
         Layer& connectedLayer0 = layer->GetInputSlot(0).GetConnectedOutputSlot()->GetOwningLayer();
         input0Name = GenerateUniqueName(connectedLayer0, 0);
         // Determine unique output tensor name.
         outputName = GenerateUniqueOutputName(*layer, 0);
     }
     std::vector<int32_t> mappings(transposeDescriptor->m_DimMappings.begin(),
                                   transposeDescriptor->m_DimMappings.end());
     TosaTransposeAttribute attribute(mappings);
     auto* op = new TosaSerializationOperator(Op_TRANSPOSE,
                                              Attribute_TransposeAttribute,
                                              &attribute,
                                              {input0Name},
                                              {outputName});
     std::vector<TosaSerializationTensor*> tensors;
     // Only add input tensors if connected layer is an input layer.
     // As intermediate or constant tensors will be created separately.
     // There also can't be duplicate tensor.
     if(input0Name.find("input0_") != std::string::npos)
     {
         std::vector<int32_t> inputShape0 = GetTosaTensorShape(inputs[0]->GetShape());
         DType inputDType0 = ArmNNToDType(inputs[0]->GetDataType());
         tensors.push_back(new TosaSerializationTensor(input0Name, inputShape0, inputDType0, {}));
     }
     std::vector<int32_t> outputShape0 = GetTosaTensorShape(outputs[0]->GetShape());
     DType outputDType0 = ArmNNToDType(outputs[0]->GetDataType());
     tensors.push_back(new TosaSerializationTensor(outputName, outputShape0, outputDType0, {}));
     // operatorInputNames/operatorOutputNames ends up being the same as
     // blockInputNames/blockOutputNames for one-to-one ArmNN to TOSA mappings
     return new TosaSerializationBasicBlock(blockName, // name
                                            {op}, // operators
                                            tensors, // tensors
                                            {input0Name}, // inputs
                                            {outputName}); // outputs
 }
References PermutationVector::begin(), PermutationVector::end(), GenerateUniqueName(), GenerateUniqueOutputName(), InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), OutputSlot::GetOwningLayer(), GetTosaTensorShape(), GetUniqueTosaMappingID(), and TransposeDescriptor::m_DimMappings.
Referenced by GetTosaMapping().