Arm NN: DetectionPostProcessLayer Class Reference
DetectionPostProcessLayer Class Reference
This layer represents a detection postprocess operator.
#include <DetectionPostProcessLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the DetectionPostProcess type.
DetectionPostProcessLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of DetectionPostProcessLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
The model does not specify the output shapes.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Public Member Functions inherited from LayerWithParameters< DetectionPostProcessDescriptor >
const DetectionPostProcessDescriptor & GetParameters () const override
If the layer has a descriptor return it.
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
bool GetAllowExpandedDims () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id) override
Set the backend of the IConnectableLayer.
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer * >::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
void SetAllowExpandedDims (bool allowExpandedDims)
template<typename T >
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
virtual const BaseDescriptor & GetParameters () const override
If the layer has a descriptor return it.
Public Attributes
std::shared_ptr< ConstTensorHandle > m_Anchors
A unique pointer to store Anchor values.
Protected Member Functions
DetectionPostProcessLayer (const DetectionPostProcessDescriptor &param, const char *name)
Constructor to create a DetectionPostProcessLayer.
~DetectionPostProcessLayer ()=default
Default destructor.
ImmutableConstantTensors GetConstantTensorsByRef () const override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from LayerWithParameters< DetectionPostProcessDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const DetectionPostProcessDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *Layer::CreateWorkload.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Layer::ImmutableConstantTensors GetConnectedConstantAsInputTensors () const
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *Layer::CreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef () override final
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< DetectionPostProcessDescriptor >
using DescriptorType = DetectionPostProcessDescriptor
Public Types inherited from IConnectableLayer
using ConstantTensors = std::vector< std::reference_wrapper< std::shared_ptr< ConstTensorHandle > >>
using ImmutableConstantTensors = std::vector< std::reference_wrapper< const std::shared_ptr< ConstTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< DetectionPostProcessDescriptor >
DetectionPostProcessDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a detection postprocess operator.
Definition at line 16 of file DetectionPostProcessLayer.hpp.
Constructor & Destructor Documentation
DetectionPostProcessLayer()
DetectionPostProcessLayer (const DetectionPostProcessDescriptor & param, const char * name) protected
Constructor to create a DetectionPostProcessLayer.
Parameters
[in] param DetectionPostProcessDescriptor to configure the detection postprocess.
[in] name Optional name for the layer.
Definition at line 18 of file DetectionPostProcessLayer.cpp.
     : LayerWithParameters(2, 4, LayerType::DetectionPostProcess, param, name)
 {
 }
~DetectionPostProcessLayer()
~DetectionPostProcessLayer () protected default
Default destructor.
Member Function Documentation
Clone()
DetectionPostProcessLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 32 of file DetectionPostProcessLayer.cpp.
 {
     auto layer = CloneBase<DetectionPostProcessLayer>(graph, m_Param, GetName());
     layer->m_Anchors = m_Anchors ? m_Anchors : nullptr;
     return std::move(layer);
 }
References Layer::GetName(), DetectionPostProcessLayer::m_Anchors, and LayerWithParameters< DetectionPostProcessDescriptor >::m_Param.
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the DetectionPostProcess type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 23 of file DetectionPostProcessLayer.cpp.
 {
     DetectionPostProcessQueueDescriptor descriptor;
     descriptor.m_Anchors = m_Anchors.get();
     SetAdditionalInfo(descriptor);
     return factory.CreateWorkload(LayerType::DetectionPostProcess, descriptor, PrepInfoAndDesc(descriptor));
 }
References IWorkloadFactory::CreateWorkload(), armnn::DetectionPostProcess, DetectionPostProcessLayer::m_Anchors, DetectionPostProcessQueueDescriptor::m_Anchors, LayerWithParameters< DetectionPostProcessDescriptor >::PrepInfoAndDesc(), and Layer::SetAdditionalInfo().
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const override virtual
Apply a visitor to this layer.
Reimplemented from Layer.
Definition at line 98 of file DetectionPostProcessLayer.cpp.
 {
     ManagedConstTensorHandle managedAnchors(m_Anchors);
     std::vector<armnn::ConstTensor> constTensors { {managedAnchors.GetTensorInfo(), managedAnchors.Map()} };
     strategy.ExecuteStrategy(this, GetParameters(), constTensors, GetName());
 }
References IStrategy::ExecuteStrategy(), Layer::GetName(), LayerWithParameters< DetectionPostProcessDescriptor >::GetParameters(), ManagedConstTensorHandle::GetTensorInfo(), DetectionPostProcessLayer::m_Anchors, and ManagedConstTensorHandle::Map().
GetConstantTensorsByRef()
Layer::ImmutableConstantTensors GetConstantTensorsByRef () const override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 92 of file DetectionPostProcessLayer.cpp.
 {
     // For API stability DO NOT ALTER order and add new members to the end of vector
     return { m_Anchors };
 }
References DetectionPostProcessLayer::m_Anchors.
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
The model does not specify the output shapes.
The output shapes are calculated from the max_detection and max_classes_per_detection parameters in the DetectionPostProcessDescriptor.
Parameters
[in] inputShapes The input shapes layer has. These are ignored for DetectionPostProcessLayer.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 80 of file DetectionPostProcessLayer.cpp.
 {
     unsigned int detectedBoxes = m_Param.m_MaxDetections * m_Param.m_MaxClassesPerDetection;
     std::vector<TensorShape> results;
     results.push_back({ 1, detectedBoxes, 4 });
     results.push_back({ 1, detectedBoxes });
     results.push_back({ 1, detectedBoxes });
     results.push_back({ 1 });
     return results;
 }
References DetectionPostProcessDescriptor::m_MaxClassesPerDetection, DetectionPostProcessDescriptor::m_MaxDetections, and LayerWithParameters< DetectionPostProcessDescriptor >::m_Param.
Referenced by DetectionPostProcessLayer::ValidateTensorShapesFromInputs().
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of DetectionPostProcessLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 39 of file DetectionPostProcessLayer.cpp.
 {
     VerifyLayerConnections(2, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     // on this level constant data should not be released.
     ARMNN_ASSERT_MSG(m_Anchors != nullptr, "DetectionPostProcessLayer: Anchors data should not be null.");
     ARMNN_ASSERT_MSG(GetNumOutputSlots() == 4, "DetectionPostProcessLayer: The layer should return 4 outputs.");
     std::vector<TensorShape> inferredShapes = InferOutputShapes(
             { GetInputSlot(0).GetTensorInfo().GetShape(),
               GetInputSlot(1).GetTensorInfo().GetShape() });
     ARMNN_ASSERT(inferredShapes.size() == 4);
     ARMNN_ASSERT(inferredShapes[0].GetDimensionality() == Dimensionality::Specified);
     ARMNN_ASSERT(inferredShapes[1].GetDimensionality() == Dimensionality::Specified);
     ARMNN_ASSERT(inferredShapes[2].GetDimensionality() == Dimensionality::Specified);
     ARMNN_ASSERT(inferredShapes[3].GetDimensionality() == Dimensionality::Specified);
     ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "DetectionPostProcessLayer");
     ValidateAndCopyShape(GetOutputSlot(1).GetTensorInfo().GetShape(),
                          inferredShapes[1],
                          m_ShapeInferenceMethod,
                          "DetectionPostProcessLayer", 1);
     ValidateAndCopyShape(GetOutputSlot(2).GetTensorInfo().GetShape(),
                          inferredShapes[2],
                          m_ShapeInferenceMethod,
                          "DetectionPostProcessLayer", 2);
     ValidateAndCopyShape(GetOutputSlot(3).GetTensorInfo().GetShape(),
                          inferredShapes[3],
                          m_ShapeInferenceMethod,
                          "DetectionPostProcessLayer", 3);
 }
References ARMNN_ASSERT, ARMNN_ASSERT_MSG, CHECK_LOCATION, Layer::GetInputSlot(), Layer::GetNumOutputSlots(), Layer::GetOutputSlot(), TensorInfo::GetShape(), armnn::GetTensorInfo(), InputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), DetectionPostProcessLayer::InferOutputShapes(), DetectionPostProcessLayer::m_Anchors, Layer::m_ShapeInferenceMethod, armnn::Specified, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
Member Data Documentation
m_Anchors
std::shared_ptr<ConstTensorHandle> m_Anchors
A unique pointer to store Anchor values.
Definition at line 20 of file DetectionPostProcessLayer.hpp.
Referenced by NetworkImpl::AddDetectionPostProcessLayer(), DetectionPostProcessLayer::Clone(), DetectionPostProcessLayer::CreateWorkload(), DetectionPostProcessLayer::ExecuteStrategy(), DetectionPostProcessLayer::GetConstantTensorsByRef(), and DetectionPostProcessLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/DetectionPostProcessLayer.hpp
src/armnn/layers/DetectionPostProcessLayer.cpp