Arm NN: armnn_driver Namespace Reference
armnn_driver Namespace Reference
Helper classes.
Classes
class ArmnnDevice
class ArmnnDriver
class ArmnnDriverImpl
class ArmnnPreparedModel
struct CanonicalExecutionContext
class ConstTensorPin
struct ConversionData
class Converter
class DriverOptions
class LayerInputHandle
class ModelToINetworkTransformer
class UnsupportedOperand
Typedefs
template<typename TensorType >
using DumpElementFunction = void(*)(const TensorType &tensor, unsigned int elementIndex, std::ofstream &fileStream)
using Model = ::android::nn::Model
Helper classes.
using Operand = ::android::nn::Operand
using OperandLifeTime = ::android::nn::Operand::LifeTime
using OperandType = ::android::nn::OperandType
using Operation = ::android::nn::Operation
using OperationType = ::android::nn::OperationType
using ErrorStatus = ::android::nn::ErrorStatus
using DequantizeResult = std::tuple< std::unique_ptr< float[]>, size_t, armnn::TensorInfo, DequantizeStatus >
using Half = half_float::half
Enumerations
enum ConversionResult { Success, ErrorMappingPools, UnsupportedFeature }
enum DequantizeStatus { SUCCESS, NOT_REQUIRED, INVALID_OPERAND }
Functions
void SwizzleAndroidNn4dTensorToArmNn (armnn::TensorInfo &tensor, const void *input, void *output, const armnn::PermutationVector &mappings)
Swizzles tensor data in input according to the dimension mappings.
void * GetMemoryFromPool (DataLocation location, const std::vector< android::nn::RunTimePoolInfo > &memPools)
Returns a pointer to a specific location in a pool`.
void * GetMemoryFromPointer (const Request::Argument &requestArg)
armnn::TensorInfo GetTensorInfoForOperand (const Operand &operand)
std::string GetOperandSummary (const Operand &operand)
template<typename TensorType >
void DumpTensor (const std::string &dumpDir, const std::string &requestName, const std::string &tensorName, const TensorType &tensor)
template void DumpTensor< armnn::ConstTensor > (const std::string &dumpDir, const std::string &requestName, const std::string &tensorName, const armnn::ConstTensor &tensor)
template void DumpTensor< armnn::Tensor > (const std::string &dumpDir, const std::string &requestName, const std::string &tensorName, const armnn::Tensor &tensor)
void DumpJsonProfilingIfRequired (bool gpuProfilingEnabled, const std::string &dumpDir, armnn::NetworkId networkId, const armnn::IProfiler *profiler)
std::string ExportNetworkGraphToDotFile (const armnn::IOptimizedNetwork &optimizedNetwork, const std::string &dumpDir)
std::string SerializeNetwork (const armnn::INetwork &network, const std::string &dumpDir, std::vector< uint8_t > &dataCacheData, bool dataCachingActive)
bool IsDynamicTensor (const armnn::TensorInfo &outputInfo)
Checks if a tensor info represents a dynamic tensor.
bool AreDynamicTensorsSupported (void)
Checks for ArmNN support of dynamic tensors.
bool isQuantizedOperand (const OperandType &operandType)
std::string GetModelSummary (const Model &model)
std::string GetFileTimestamp ()
void RenameExportedFiles (const std::string &existingSerializedFileName, const std::string &existingDotFileName, const std::string &dumpDir, const armnn::NetworkId networkId)
void RenameFile (const std::string &existingName, const std::string &extension, const std::string &dumpDir, const armnn::NetworkId networkId)
void CommitPools (std::vector<::android::nn::RunTimePoolInfo > &memPools)
OutputShape ComputeShape (const armnn::TensorInfo &info)
bool IsWeightsValid (const Operation &operation, uint32_t inputIndex, const Model &model)
Utility functions.
ConstTensorPin ConvertOperandToConstTensorPin (const Operand &operand, const Model &model, const ConversionData &data, const armnn::PermutationVector &dimensionMappings, const armnn::TensorShape *overrideTensorShape, bool optional, const armnn::DataType *overrideDataType)
LayerInputHandle ConvertToLayerInputHandle (const Operation &operation, uint32_t inputIndex, const Model &model, ConversionData &data, const armnn::PermutationVector &dimensionMappings, const LayerInputHandle *inputHandle)
bool ConvertPaddings (const Operation &operation, const Model &model, ConversionData &data, unsigned int rank, armnn::PadDescriptor &padDescriptor)
bool ConvertPooling2d (const Operation &operation, const char *operationName, armnn::PoolingAlgorithm poolType, const Model &model, ConversionData &data)
bool ConvertReduce (const Operation &operation, const Model &model, ConversionData &data, armnn::ReduceOperation reduceOperation)
bool ConvertToActivation (const Operation &operation, const char *operationName, const armnn::ActivationDescriptor &activationDesc, const Model &model, ConversionData &data)
DequantizeResult DequantizeIfRequired (size_t operand_index, const Operation &operation, const Model &model, const ConversionData &data)
ConstTensorPin DequantizeAndMakeConstTensorPin (const Operation &operation, const Model &model, const ConversionData &data, size_t operandIndex, bool optional)
bool GetInputPaddingScheme (const Operation &operation, uint32_t inputIndex, PaddingScheme &outPaddingScheme, const Model &model, const ConversionData &data)
const void * GetOperandValueReadOnlyAddress (const Operand &operand, const Model &model, const ConversionData &data, bool optional)
bool GetTensorInt32Values (const Operand &operand, std::vector< int32_t > &outValues, const Model &model, const ConversionData &data)
armnn::DataLayout OptionalDataLayout (const Operation &operation, uint32_t inputIndex, const Model &model, ConversionData &data)
armnn::IConnectableLayer * ProcessActivation (const armnn::TensorInfo &tensorInfo, ActivationFn activation, armnn::IConnectableLayer *prevLayer, ConversionData &data)
bool SetupAndTrackLayerOutputSlot (const Operation &operation, uint32_t operationOutputIndex, armnn::IConnectableLayer &layer, uint32_t layerOutputIndex, const Model &model, ConversionData &data, const armnn::TensorInfo *overrideOutputInfo, const std::function< void(const armnn::TensorInfo &, bool &)> &validateFunc, const ActivationFn &activationFunction, bool inferOutputShapes)
bool IsConnectedToDequantize (armnn::IOutputSlot *ioutputSlot)
const Operand * GetInputOperand (const Operation &operation, uint32_t inputIndex, const Model &model, bool failOnIndexOutOfBounds=true)
const Operand * GetOutputOperand (const Operation &operation, uint32_t outputIndex, const Model &model)
bool GetOperandType (const Operation &operation, uint32_t inputIndex, const Model &model, OperandType &type)
bool IsOperandConstant (const Operand &operand)
ConstTensorPin ConvertOperationInputToConstTensorPin (const Operation &operation, uint32_t inputIndex, const Model &model, const ConversionData &data, const armnn::PermutationVector &dimensionMappings=g_DontPermute, const armnn::TensorShape *overrideTensorShape=nullptr, bool optional=false)
template<typename OutputType >
bool GetInputScalar (const Operation &operation, uint32_t inputIndex, OperandType type, OutputType &outValue, const Model &model, const ConversionData &data, bool optional=false)
bool GetInputInt32 (const Operation &operation, uint32_t inputIndex, int32_t &outValue, const Model &model, const ConversionData &data)
bool GetInputFloat32 (const Operation &operation, uint32_t inputIndex, float &outValue, const Model &model, const ConversionData &data)
bool GetInputActivationFunctionImpl (const Operation &operation, uint32_t inputIndex, OperandType type, ActivationFn &outActivationFunction, const Model &model, const ConversionData &data)
bool GetInputActivationFunction (const Operation &operation, uint32_t inputIndex, ActivationFn &outActivationFunction, const Model &model, const ConversionData &data)
bool GetInputActivationFunctionFromTensor (const Operation &operation, uint32_t inputIndex, ActivationFn &outActivationFunction, const Model &model, const ConversionData &data)
bool GetOptionalInputActivation (const Operation &operation, uint32_t inputIndex, ActivationFn &activationFunction, const Model &model, const ConversionData &data)
template<typename ConvolutionDescriptor >
bool GetOptionalConvolutionDilationParams (const Operation &operation, uint32_t dilationXIndex, ConvolutionDescriptor &descriptor, const Model &model, const ConversionData &data)
bool GetOptionalBool (const Operation &operation, uint32_t inputIndex, const Model &model, const ConversionData &data)
bool SetupAndTrackLayerOutputSlot (const Operation &operation, uint32_t outputIndex, armnn::IConnectableLayer &layer, const Model &model, ConversionData &data, const armnn::TensorInfo *overrideOutputInfo=nullptr, const std::function< void(const armnn::TensorInfo &, bool &)> &validateFunc=nullptr, const ActivationFn &activationFunction=ActivationFn::kActivationNone)
bool IsQSymm8 (const Operand &operand)
Variables
const armnn::PermutationVector g_DontPermute {}
Detailed Description
Helper classes.
Typedef Documentation
DequantizeResult
using DequantizeResult = std::tuple<std::unique_ptr<float[]>, size_t, armnn::TensorInfo, DequantizeStatus>
Definition at line 1014 of file ConversionUtils.hpp.
DumpElementFunction
using DumpElementFunction = void (*)(const TensorType& tensor, unsigned int elementIndex, std::ofstream& fileStream)
Definition at line 206 of file CanonicalUtils.cpp.
ErrorStatus
using ErrorStatus = ::android::nn::ErrorStatus
Definition at line 49 of file ConversionUtils.hpp.
Half
using Half = half_float::half
Definition at line 14 of file Converter.cpp.
Model
using Model = ::android::nn::Model
Helper classes.
Definition at line 43 of file ConversionUtils.hpp.
Operand
using Operand = ::android::nn::Operand
Definition at line 44 of file ConversionUtils.hpp.
OperandLifeTime
using OperandLifeTime = ::android::nn::Operand::LifeTime
Definition at line 45 of file ConversionUtils.hpp.
OperandType
using OperandType = ::android::nn::OperandType
Definition at line 46 of file ConversionUtils.hpp.
Operation
using Operation = ::android::nn::Operation
Definition at line 47 of file ConversionUtils.hpp.
OperationType
using OperationType = ::android::nn::OperationType
Definition at line 48 of file ConversionUtils.hpp.
Enumeration Type Documentation
ConversionResult
enum ConversionResult strong
Enumerator
Success
ErrorMappingPools
UnsupportedFeature
Definition at line 125 of file ConversionUtils.hpp.
 {
     Success,
     ErrorMappingPools,
     UnsupportedFeature
 };
DequantizeStatus
enum DequantizeStatus strong
Enumerator
SUCCESS
NOT_REQUIRED
INVALID_OPERAND
Definition at line 1007 of file ConversionUtils.hpp.
 {
     SUCCESS,
     NOT_REQUIRED,
     INVALID_OPERAND
 };
Function Documentation
AreDynamicTensorsSupported()
bool AreDynamicTensorsSupported ()
Checks for ArmNN support of dynamic tensors.
Definition at line 502 of file CanonicalUtils.cpp.
 {
     return true;
 }
Referenced by ConvertPooling2d(), ConvertReduce(), and ConvertToActivation().
CommitPools()
void CommitPools (std::vector<::android::nn::RunTimePoolInfo > & memPools)
Definition at line 612 of file CanonicalUtils.cpp.
 {
     // Commit output buffers.
     // Note that we update *all* pools, even if they aren't actually used as outputs -
     // this is simpler and is what the CpuExecutor does.
     for (auto& pool : memPools)
     {
         // Type android::nn::RunTimePoolInfo has changed between Android P & Q and Android R, where
         // update() has been removed and flush() added.
         pool.flush();
     }
 }
Referenced by ArmnnPreparedModel::ExecuteGraph().
ComputeShape()
OutputShape armnn_driver::ComputeShape (const armnn::TensorInfo & info) inline
Definition at line 95 of file CanonicalUtils.hpp.
 {
     OutputShape shape;
     armnn::TensorShape tensorShape = info.GetShape();
     // Android will expect scalars as a zero dimensional tensor
     if(tensorShape.GetDimensionality() == armnn::Dimensionality::Scalar)
     {
          shape.dimensions = std::vector<uint32_t>{};
     }
     else
     {
         std::vector<uint32_t> dimensions;
         const unsigned int numDims = tensorShape.GetNumDimensions();
         dimensions.resize(numDims);
         for (unsigned int outputIdx = 0u; outputIdx < numDims; ++outputIdx)
         {
             dimensions[outputIdx] = tensorShape[outputIdx];
         }
         shape.dimensions = dimensions;
     }
     shape.isSufficient = true;
     return shape;
 }
References TensorShape::GetDimensionality(), TensorShape::GetNumDimensions(), and armnn::Scalar.
Referenced by ArmnnPreparedModel::execute().
ConvertOperandToConstTensorPin()
ConstTensorPin ConvertOperandToConstTensorPin (const Operand & operand, const Model & model, const ConversionData & data, const armnn::PermutationVector & dimensionMappings, const armnn::TensorShape * overrideTensorShape, bool optional, const armnn::DataType * overrideDataType)
Definition at line 154 of file ConversionUtils.cpp.
 {
     if (!IsOperandTypeSupportedForTensors(operand.type))
     {
         VLOG(DRIVER) << __func__ << ": unsupported operand type for tensor" << operand.type;
         return ConstTensorPin();
     }
     if (!optional && !IsOperandConstant(operand))
     {
         VLOG(DRIVER) << __func__ << ": lifetime for input tensor: r" << operand.lifetime;
         return ConstTensorPin();
     }
     const void* const valueStart = GetOperandValueReadOnlyAddress(operand, model, data, optional);
     if (!valueStart)
     {
         if (optional)
         {
             // optional tensor with no values is not really an error; return it as invalid, but marked as optional
             return ConstTensorPin(true);
         }
         // mandatory tensor with no values
         Fail("%s: failed to get operand address", __func__);
         return ConstTensorPin();
     }
     armnn::TensorInfo tensorInfo = GetTensorInfoForOperand(operand);
     if (overrideTensorShape)
     {
         tensorInfo.SetShape(*overrideTensorShape);
     }
     if (overrideDataType)
     {
         tensorInfo.SetDataType(*overrideDataType);
     }
     // Make sure isConstant flag is set.
     tensorInfo.SetConstant();
     return ConstTensorPin(tensorInfo, valueStart, operand.location.length, dimensionMappings);
 }
References GetOperandValueReadOnlyAddress(), GetTensorInfoForOperand(), IsOperandConstant(), TensorInfo::SetConstant(), TensorInfo::SetDataType(), and TensorInfo::SetShape().
Referenced by ConvertOperationInputToConstTensorPin(), and ConvertToLayerInputHandle().
ConvertOperationInputToConstTensorPin()
ConstTensorPin armnn_driver::ConvertOperationInputToConstTensorPin (const Operation & operation, uint32_t inputIndex, const Model & model, const ConversionData & data, const armnn::PermutationVector & dimensionMappings = g_DontPermute, const armnn::TensorShape * overrideTensorShape = nullptr, bool optional = false) inline
Definition at line 718 of file ConversionUtils.hpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!operand)
     {
         Fail("%s: failed to get input operand: index=%u", __func__, inputIndex);
         return ConstTensorPin();
     }
     return ConvertOperandToConstTensorPin(*operand,
                                           model,
                                           data,
                                           dimensionMappings,
                                           overrideTensorShape,
                                           optional);
 }
References ConvertOperandToConstTensorPin(), and GetInputOperand().
Referenced by DequantizeAndMakeConstTensorPin().
ConvertPaddings()
bool ConvertPaddings (const Operation & operation, const Model & model, ConversionData & data, unsigned int rank, armnn::PadDescriptor & padDescriptor)
Definition at line 338 of file ConversionUtils.cpp.
 {
     const Operand* paddingsOperand = GetInputOperand(operation, 1, model);
     if (!paddingsOperand)
     {
         return Fail("%s: Could not read paddings operand", __func__);
     }
     armnn::TensorShape paddingsOperandShape = GetTensorShapeForOperand(*paddingsOperand);
     if (paddingsOperandShape.GetNumDimensions() != 2 || paddingsOperandShape.GetNumElements() != rank * 2)
     {
         return Fail("%s: Operation has invalid paddings operand: expected shape [%d, 2]",  __func__, rank);
     }
     std::vector<int32_t> paddings;
     if (!GetTensorInt32Values(*paddingsOperand, paddings, model, data))
     {
         return Fail("%s: Operation has invalid or unsupported paddings operand", __func__);
     }
     // add padding for each dimension of input tensor.
     for (unsigned int i = 0; i < paddings.size() - 1; i += 2)
     {
         int paddingBeforeInput = paddings[i];
         int paddingAfterInput  = paddings[i + 1];
         if (paddingBeforeInput < 0 || paddingAfterInput < 0)
         {
             return Fail("%s: Operation has invalid paddings operand, invalid padding values.",  __func__);
         }
         padDescriptor.m_PadList.emplace_back((unsigned int) paddingBeforeInput, (unsigned int) paddingAfterInput);
     }
     return true;
 }
References GetInputOperand(), TensorShape::GetNumDimensions(), TensorShape::GetNumElements(), GetTensorInt32Values(), and PadDescriptor::m_PadList.
ConvertPooling2d()
bool ConvertPooling2d (const Operation & operation, const char * operationName, armnn::PoolingAlgorithm poolType, const Model & model, ConversionData & data)
Definition at line 380 of file ConversionUtils.cpp.
 {
     VLOG(DRIVER) << "Converter::ConvertL2Pool2d()";
     LayerInputHandle input = ConvertToLayerInputHandle(operation, 0, model, data);
     if (!input.IsValid())
     {
         return Fail("%s: Operation Could not read input 0", operationName);
     }
     const Operand* output = GetOutputOperand(operation, 0, model);
     if (!output)
     {
         return Fail("%s: Could not read output 0", __func__);
     }
     const armnn::TensorInfo& inputInfo  = input.GetTensorInfo();
     const armnn::TensorInfo& outputInfo = GetTensorInfoForOperand(*output);
     armnn::Pooling2dDescriptor desc;
     desc.m_PoolType = poolType;
     desc.m_OutputShapeRounding = armnn::OutputShapeRounding::Floor;
     desc.m_DataLayout = armnn::DataLayout::NHWC;
     ActivationFn activation;
     auto inputSize = operation.inputs.size();
     if (inputSize >= 10)
     {
         // one input, 9 parameters (padding l r t b, stridex, stridey, width, height, activation type)
         if (!GetInputScalar(operation, 1, OperandType::INT32, desc.m_PadLeft, model, data) ||
             !GetInputScalar(operation, 2, OperandType::INT32, desc.m_PadRight, model, data) ||
             !GetInputScalar(operation, 3, OperandType::INT32, desc.m_PadTop, model, data) ||
             !GetInputScalar(operation, 4, OperandType::INT32, desc.m_PadBottom, model, data) ||
             !GetInputScalar(operation, 5, OperandType::INT32, desc.m_StrideX, model, data) ||
             !GetInputScalar(operation, 6, OperandType::INT32, desc.m_StrideY, model, data) ||
             !GetInputScalar(operation, 7, OperandType::INT32, desc.m_PoolWidth, model, data) ||
             !GetInputScalar(operation, 8, OperandType::INT32, desc.m_PoolHeight, model, data) ||
             !GetInputActivationFunction(operation, 9, activation, model, data))
         {
             return Fail("%s: Operation has invalid inputs", operationName);
         }
         if (Is12OrLaterOperand(*output))
         {
             desc.m_DataLayout = OptionalDataLayout(operation, 10, model, data);
         }
     }
     else
     {
         // one input, 6 parameters (padding, stridex, stridey, width, height, activation type)
         ::android::nn::PaddingScheme scheme;
         if (!GetInputPaddingScheme(operation, 1, scheme, model, data) ||
             !GetInputScalar(operation, 2, OperandType::INT32, desc.m_StrideX, model, data) ||
             !GetInputScalar(operation, 3, OperandType::INT32, desc.m_StrideY, model, data) ||
             !GetInputScalar(operation, 4, OperandType::INT32, desc.m_PoolWidth, model, data) ||
             !GetInputScalar(operation, 5, OperandType::INT32, desc.m_PoolHeight, model, data) ||
             !GetInputActivationFunction(operation, 6, activation, model, data))
         {
             return Fail("%s: Operation has invalid inputs", operationName);
         }
         if (Is12OrLaterOperand(*output))
         {
             desc.m_DataLayout = OptionalDataLayout(operation, 7, model, data);
         }
         const armnnUtils::DataLayoutIndexed dataLayout(desc.m_DataLayout);
         const unsigned int inputWidth  = inputInfo.GetShape()[dataLayout.GetWidthIndex()];
         const unsigned int inputHeight = inputInfo.GetShape()[dataLayout.GetHeightIndex()];
         CalcPadding(inputWidth, desc.m_PoolWidth, desc.m_StrideX, desc.m_PadLeft, desc.m_PadRight, scheme);
         CalcPadding(inputHeight, desc.m_PoolHeight, desc.m_StrideY, desc.m_PadTop, desc.m_PadBottom, scheme);
     }
     bool isSupported = false;
     armnn::BackendId setBackend;
     auto validateFunc = [&](const armnn::TensorInfo& outputInfo, bool& isSupported)
     {
         FORWARD_LAYER_SUPPORT_FUNC(__func__,
                                    IsPooling2dSupported,
                                    data.m_Backends,
                                    isSupported,
                                    setBackend,
                                    inputInfo,
                                    outputInfo,
                                    desc);
     };
     if(IsDynamicTensor(outputInfo))
     {
         isSupported = AreDynamicTensorsSupported();
     }
     else
     {
         validateFunc(outputInfo, isSupported);
     }
     if (!isSupported)
     {
         return false;
     }
     armnn::IConnectableLayer* pooling2dLayer = data.m_Network->AddPooling2dLayer(desc);
     pooling2dLayer->SetBackendId(setBackend);
     if (!pooling2dLayer)
     {
         return Fail("%s: AddPooling2dLayer failed", __func__);
     }
     input.Connect(pooling2dLayer->GetInputSlot(0));
     if (!isSupported)
     {
         return false;
     }
     return SetupAndTrackLayerOutputSlot(operation, 0, *pooling2dLayer, model,
                                         data, nullptr, validateFunc, activation);
 }
References AreDynamicTensorsSupported(), LayerInputHandle::Connect(), ConvertToLayerInputHandle(), armnn::Floor, FORWARD_LAYER_SUPPORT_FUNC, DataLayoutIndexed::GetHeightIndex(), GetInputActivationFunction(), GetInputPaddingScheme(), GetInputScalar(), IConnectableLayer::GetInputSlot(), GetOutputOperand(), TensorInfo::GetShape(), LayerInputHandle::GetTensorInfo(), GetTensorInfoForOperand(), DataLayoutIndexed::GetWidthIndex(), IsDynamicTensor(), LayerInputHandle::IsValid(), ConversionData::m_Backends, Pooling2dDescriptor::m_DataLayout, ConversionData::m_Network, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, armnn::NHWC, OptionalDataLayout(), IConnectableLayer::SetBackendId(), and SetupAndTrackLayerOutputSlot().
ConvertReduce()
bool ConvertReduce (const Operation & operation, const Model & model, ConversionData & data, armnn::ReduceOperation reduceOperation)
Definition at line 508 of file ConversionUtils.cpp.
 {
     armnn::ReduceDescriptor descriptor;
     descriptor.m_ReduceOperation = reduceOperation;
     LayerInputHandle input = ConvertToLayerInputHandle(operation, 0, model, data);
     if (!input.IsValid())
     {
         return Fail("%s: Operation has invalid inputs", __func__);
     }
     const armnn::TensorInfo& inputInfo = input.GetTensorInfo();
     const Operand* output = GetOutputOperand(operation, 0, model);
     if (!output)
     {
         return Fail("%s: Could not read output 0", __func__);
     }
     const armnn::TensorInfo& outputInfo = GetTensorInfoForOperand(*output);
     const Operand* axisOperand = GetInputOperand(operation, 1, model);
     if (!axisOperand)
     {
         return Fail("%s: Could not read input 1", __func__);
     }
     std::vector<int32_t> axis;
     if (!GetTensorInt32Values(*axisOperand, axis, model, data))
     {
         return Fail("%s: Input 1 has invalid values", __func__);
     }
     // Convert the axis to unsigned int and remove duplicates.
     unsigned int rank = inputInfo.GetNumDimensions();
     std::set<unsigned int> uniqueAxis;
     std::transform(axis.begin(), axis.end(),
                    std::inserter(uniqueAxis, uniqueAxis.begin()),
                    [rank](int i) -> unsigned int { return (i + rank) % rank; });
     descriptor.m_vAxis.assign(uniqueAxis.begin(), uniqueAxis.end());
     // Get the "keep dims" flag.
     if (!GetInputScalar(operation, 2, OperandType::BOOL, descriptor.m_KeepDims, model, data))
     {
         return Fail("%s: Could not read input 2", __func__);
     }
     bool isSupported = false;
     armnn::BackendId setBackend;
     auto validateFunc = [&](const armnn::TensorInfo& outputInfo, bool& isSupported)
     {
         FORWARD_LAYER_SUPPORT_FUNC(__func__,
                                    IsReduceSupported,
                                    data.m_Backends,
                                    isSupported,
                                    setBackend,
                                    inputInfo,
                                    outputInfo,
                                    descriptor);
     };
     if(!IsDynamicTensor(outputInfo))
     {
         validateFunc(outputInfo, isSupported);
     }
     else
     {
         isSupported = AreDynamicTensorsSupported();
     }
     if (!isSupported)
     {
         return false;
     }
     armnn::IConnectableLayer* const layer = data.m_Network->AddReduceLayer(descriptor);
     layer->SetBackendId(setBackend);
     assert(layer != nullptr);
     input.Connect(layer->GetInputSlot(0));
     return SetupAndTrackLayerOutputSlot(operation, 0, *layer, model, data, nullptr, validateFunc);
 }
References AreDynamicTensorsSupported(), LayerInputHandle::Connect(), ConvertToLayerInputHandle(), FORWARD_LAYER_SUPPORT_FUNC, GetInputOperand(), GetInputScalar(), IConnectableLayer::GetInputSlot(), TensorInfo::GetNumDimensions(), GetOutputOperand(), LayerInputHandle::GetTensorInfo(), GetTensorInfoForOperand(), GetTensorInt32Values(), IsDynamicTensor(), LayerInputHandle::IsValid(), ConversionData::m_Backends, ReduceDescriptor::m_KeepDims, ConversionData::m_Network, ReduceDescriptor::m_ReduceOperation, ReduceDescriptor::m_vAxis, IConnectableLayer::SetBackendId(), and SetupAndTrackLayerOutputSlot().
Referenced by Converter::ConvertOperation().
ConvertToActivation()
bool ConvertToActivation (const Operation & operation, const char * operationName, const armnn::ActivationDescriptor & activationDesc, const Model & model, ConversionData & data)
Definition at line 592 of file ConversionUtils.cpp.
 {
     LayerInputHandle input = ConvertToLayerInputHandle(operation, 0, model, data);
     if (!input.IsValid())
     {
         return Fail("%s: Input 0 is invalid", operationName);
     }
     const Operand* outputOperand = GetOutputOperand(operation, 0, model);
     if (!outputOperand)
     {
         return false;
     }
     const armnn::TensorInfo& outInfo = GetTensorInfoForOperand(*outputOperand);
     bool isSupported = false;
     armnn::BackendId setBackend;
     auto validateFunc = [&](const armnn::TensorInfo& outInfo, bool& isSupported)
     {
         FORWARD_LAYER_SUPPORT_FUNC(__func__,
                                    IsActivationSupported,
                                    data.m_Backends,
                                    isSupported,
                                    setBackend,
                                    input.GetTensorInfo(),
                                    outInfo,
                                    activationDesc);
     };
     if(IsDynamicTensor(outInfo))
     {
         isSupported = AreDynamicTensorsSupported();
     }
     else
     {
         validateFunc(outInfo, isSupported);
     }
     if (!isSupported)
     {
         return false;
     }
     armnn::IConnectableLayer* layer = data.m_Network->AddActivationLayer(activationDesc);
     layer->SetBackendId(setBackend);
     ARMNN_ASSERT(layer != nullptr);
     input.Connect(layer->GetInputSlot(0));
     return SetupAndTrackLayerOutputSlot(operation, 0, *layer, model, data, nullptr, validateFunc);
 }
References AreDynamicTensorsSupported(), ARMNN_ASSERT, LayerInputHandle::Connect(), ConvertToLayerInputHandle(), FORWARD_LAYER_SUPPORT_FUNC, IConnectableLayer::GetInputSlot(), GetOutputOperand(), LayerInputHandle::GetTensorInfo(), GetTensorInfoForOperand(), IsDynamicTensor(), LayerInputHandle::IsValid(), ConversionData::m_Backends, ConversionData::m_Network, IConnectableLayer::SetBackendId(), and SetupAndTrackLayerOutputSlot().
ConvertToLayerInputHandle()
LayerInputHandle ConvertToLayerInputHandle (const Operation & operation, uint32_t inputIndex, const Model & model, ConversionData & data, const armnn::PermutationVector & dimensionMappings, const LayerInputHandle * inputHandle)
Definition at line 204 of file ConversionUtils.cpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!operand)
     {
         Fail("%s: failed to get input operand %i", __func__, inputIndex);
         return LayerInputHandle();
     }
     if (!IsOperandTypeSupportedForTensors(operand->type))
     {
         VLOG(DRIVER) << __func__ << ": unsupported operand type for tensor: " << operand->type;
         return LayerInputHandle();
     }
     try
     {
         armnn::TensorInfo operandTensorInfo = GetTensorInfoForOperand(*operand);
         if (IsDynamicTensor(operandTensorInfo))
         {
             data.m_DynamicInputsEncountered = true;
             const uint32_t operandIndex = operation.inputs[inputIndex];
             // Check if the dynamic input tensors have been inferred by one of the previous layers
             // If not we can't support them
             if (data.m_OutputSlotForOperand.size() >= operandIndex && data.m_OutputSlotForOperand[operandIndex])
             {
                 operandTensorInfo = data.m_OutputSlotForOperand[operandIndex]->GetTensorInfo();
             }
             else
             {
                 Fail("%s: Type 2 dynamic input tensors are not supported", __func__);
                 return LayerInputHandle();
             }
         }
         switch (operand->lifetime)
         {
             case OperandLifeTime::SUBGRAPH_INPUT:
             {
                 // NOTE: We must check whether we can support the input tensor on at least one
                 // of the provided backends; otherwise we cannot convert the operation
                 bool isInputSupported = false;
                 FORWARD_LAYER_SUPPORT_FUNC(__func__,
                                            IsInputSupported,
                                            data.m_Backends,
                                            isInputSupported,
                                            armnn::BackendId(),
                                            operandTensorInfo);
                 if (!isInputSupported)
                 {
                     Fail("%s: unsupported input tensor", __func__);
                     return LayerInputHandle();
                 }
                 [[clang::fallthrough]]; // intentional fallthrough
             }
             case OperandLifeTime::TEMPORARY_VARIABLE: // intentional fallthrough
             case OperandLifeTime::SUBGRAPH_OUTPUT:
             {
                 // The tensor is either an operand internal to the model, or a model input.
                 // It can be associated with an ArmNN output slot for an existing layer.
                 // m_OutputSlotForOperand[...] can be nullptr if the previous layer could not be converted
                 const uint32_t operandIndex = operation.inputs[inputIndex];
                 return LayerInputHandle(true, data.m_OutputSlotForOperand[operandIndex], operandTensorInfo);
             }
             case OperandLifeTime::CONSTANT_COPY: // intentional fallthrough
             case OperandLifeTime::POINTER:
             case OperandLifeTime::CONSTANT_REFERENCE:
             {
                 auto constantTensorDataType = operandTensorInfo.GetDataType();
                 // The tensor has an already known constant value, and can be converted into an ArmNN Constant layer.
                 ConstTensorPin tensorPin = ConvertOperandToConstTensorPin(*operand,
                                                                           model,
                                                                           data,
                                                                           dimensionMappings,
                                                                           nullptr,
                                                                           false,
                                                                           &constantTensorDataType);
                 if (tensorPin.IsValid())
                 {
                     bool isSupported = false;
                     armnn::BackendId setBackend;
                     FORWARD_LAYER_SUPPORT_FUNC(__func__,
                                                IsConstantSupported,
                                                data.m_Backends,
                                                isSupported,
                                                setBackend,
                                                tensorPin.GetConstTensor().GetInfo());
                     if (!isSupported)
                     {
                         return LayerInputHandle();
                     }
                     armnn::IConnectableLayer* constantLayer =
                         data.m_Network->AddConstantLayer(tensorPin.GetConstTensor());
                     constantLayer->SetBackendId(setBackend);
                     armnn::IOutputSlot& outputSlot = constantLayer->GetOutputSlot(0);
                     armnn::TensorInfo constantTensorInfo = tensorPin.GetConstTensor().GetInfo();
                     outputSlot.SetTensorInfo(constantTensorInfo);
                     return LayerInputHandle(true, &outputSlot, constantTensorInfo);
                 }
                 else
                 {
                     Fail("%s: invalid operand tensor", __func__);
                     return LayerInputHandle();
                 }
                 break;
             }
             default:
             {
                 VLOG(DRIVER) << __func__ << ": unsupported lifetime for input tensor: " << operand->lifetime;
                 return LayerInputHandle();
             }
         }
     }
     catch (UnsupportedOperand<OperandType>& e)
     {
         VLOG(DRIVER) << __func__ << ": Operand type: " << e.m_type << " not supported in ArmnnDriver";
         return LayerInputHandle();
     }
 }
References ConvertOperandToConstTensorPin(), FORWARD_LAYER_SUPPORT_FUNC, ConstTensorPin::GetConstTensor(), TensorInfo::GetDataType(), BaseTensor< MemoryType >::GetInfo(), GetInputOperand(), IConnectableLayer::GetOutputSlot(), GetTensorInfoForOperand(), IsDynamicTensor(), ConstTensorPin::IsValid(), ConversionData::m_Backends, ConversionData::m_DynamicInputsEncountered, ConversionData::m_Network, ConversionData::m_OutputSlotForOperand, UnsupportedOperand< OperandType >::m_type, IConnectableLayer::SetBackendId(), and IOutputSlot::SetTensorInfo().
Referenced by ConvertPooling2d(), ConvertReduce(), and ConvertToActivation().
DequantizeAndMakeConstTensorPin()
ConstTensorPin DequantizeAndMakeConstTensorPin (const Operation & operation, const Model & model, const ConversionData & data, size_t operandIndex, bool optional)
Definition at line 731 of file ConversionUtils.cpp.
 {
     DequantizeResult dequantized = DequantizeIfRequired(operandIndex,operation, model, data);
     DequantizeStatus status = std::get<3>(dequantized);
     switch (status)
     {
         case DequantizeStatus::INVALID_OPERAND:
         {
             // return invalid const tensor pin
             return ConstTensorPin();
         }
         case DequantizeStatus::NOT_REQUIRED:
         {
             return ConvertOperationInputToConstTensorPin(
                 operation, operandIndex, model, data, g_DontPermute, nullptr, optional);
         }
         case DequantizeStatus::SUCCESS:
         default:
         {
             return ConstTensorPin(
                 std::get<2>(dequantized), std::get<0>(dequantized).get(), std::get<1>(dequantized), g_DontPermute);
         }
     }
 }
References ConvertOperationInputToConstTensorPin(), DequantizeIfRequired(), g_DontPermute, INVALID_OPERAND, NOT_REQUIRED, and SUCCESS.
DequantizeIfRequired()
DequantizeResult DequantizeIfRequired (size_t operand_index, const Operation & operation, const Model & model, const ConversionData & data)
Definition at line 648 of file ConversionUtils.cpp.
 {
     const Operand* weightsOperand = GetInputOperand(operation, operand_index, model);
     if (!weightsOperand)
     {
         return { nullptr, 0, armnn::TensorInfo(), DequantizeStatus::INVALID_OPERAND };
     }
     if (IsOperandConstant(*weightsOperand))
     {
         // Weights are already constant
         return { nullptr, 0, armnn::TensorInfo(), DequantizeStatus::NOT_REQUIRED };
     }
     const size_t weightsInputIndex = operation.inputs[operand_index];
     // The weights are a non const tensor, this indicates they might be the output of a dequantize op.
     // Iterate over the nodes and find the previous operation which should be DEQUANTIZE
     for (uint32_t operationIdx = 0; operationIdx < getMainModel(model).operations.size(); ++operationIdx)
     {
         // Search for the DEQUANTIZE op which has the operand with index equal to operandIndex
         const auto& operationIt = getMainModel(model).operations[operationIdx];
         if (operationIt.type != OperationType::DEQUANTIZE)
         {
             continue;
         }
         size_t outOpIndex = weightsInputIndex + 1;
         for (size_t i = 0; outOpIndex != weightsInputIndex && i < operationIt.outputs.size(); ++i)
         {
             outOpIndex = operationIt.outputs[i];
         }
         if (outOpIndex != weightsInputIndex)
         {
             continue;
         }
         const Operand* operand = GetInputOperand(operationIt, 0, model);
         ARMNN_ASSERT(operand);
         if (!IsQSymm8(*operand))
         {
             // Only supporting dequantize from QSYMM8 to FLOAT
             break;
         }
         // Allocate a new buffer for the dequantized data and manually dequantize
         const void* startValue = GetOperandValueReadOnlyAddress(*operand, model, data);
         if (!startValue)
         {
             // Failed to get the operand address
             break;
         }
         const uint8_t* quantizedBuffer = reinterpret_cast<const uint8_t*>(startValue);
         size_t dequantizedBufferLength = operand->location.length;
         const float quantizationScale  = operand->scale;
         auto dequantizedBuffer = std::make_unique<float[]>(dequantizedBufferLength + 1);
         for (size_t i = 0; i < dequantizedBufferLength; ++i)
         {
             float* dstPtr = dequantizedBuffer.get();
             ARMNN_ASSERT(dstPtr);
             *dstPtr++ = quantizedBuffer[i] * quantizationScale;
         }
         // Construct tensor info for dequantized ConstTensor
         armnn::TensorInfo tensorInfo(operand->dimensions.size(),
                                      operand->dimensions.data(),
                                      armnn::DataType::Float32);
         return { std::move(dequantizedBuffer), dequantizedBufferLength * sizeof(float),
                  std::move(tensorInfo),
                  DequantizeStatus::SUCCESS };
     }
     return { nullptr, 0, armnn::TensorInfo() , DequantizeStatus::NOT_REQUIRED};
 }
References ARMNN_ASSERT, armnn::Float32, GetInputOperand(), getMainModel(), GetOperandValueReadOnlyAddress(), INVALID_OPERAND, IsOperandConstant(), IsQSymm8(), NOT_REQUIRED, and SUCCESS.
Referenced by DequantizeAndMakeConstTensorPin().
DumpJsonProfilingIfRequired()
void DumpJsonProfilingIfRequired (bool gpuProfilingEnabled, const std::string & dumpDir, armnn::NetworkId networkId, const armnn::IProfiler * profiler)
Definition at line 352 of file CanonicalUtils.cpp.
 {
     // Check if profiling is required.
     if (!gpuProfilingEnabled)
     {
         return;
     }
     // The dump directory must exist in advance.
     if (dumpDir.empty())
     {
         return;
     }
     ARMNN_ASSERT(profiler);
     // Set the name of the output profiling file.
     fs::path dumpPath = dumpDir;
     const fs::path fileName = dumpPath / (std::to_string(networkId) + "_profiling.json");
     // Open the ouput file for writing.
     std::ofstream fileStream;
     fileStream.open(fileName.c_str(), std::ofstream::out | std::ofstream::trunc);
     if (!fileStream.good())
     {
         VLOG(DRIVER) << "Could not open file %s for writing" << fileName.c_str();
         return;
     }
     // Write the profiling info to a JSON file.
     profiler->Print(fileStream);
 }
References ARMNN_ASSERT, and IProfiler::Print().
Referenced by ArmnnPreparedModel::~ArmnnPreparedModel().
DumpTensor()
void DumpTensor (const std::string & dumpDir, const std::string & requestName, const std::string & tensorName, const TensorType & tensor)
Definition at line 219 of file CanonicalUtils.cpp.
 {
     // The dump directory must exist in advance.
     fs::path dumpPath = dumpDir;
     const fs::path fileName = dumpPath / (requestName + "_" + tensorName + ".dump");
     std::ofstream fileStream;
     fileStream.open(fileName.c_str(), std::ofstream::out | std::ofstream::trunc);
     if (!fileStream.good())
     {
         VLOG(DRIVER) << "Could not open file %s for writing" << fileName.c_str();
         return;
     }
     DumpElementFunction<TensorType> dumpElementFunction = nullptr;
     switch (tensor.GetDataType())
     {
         case armnn::DataType::Float32:
         {
             dumpElementFunction = &DumpTensorElement<TensorType, float>;
             break;
         }
         case armnn::DataType::QAsymmU8:
         {
             dumpElementFunction = &DumpTensorElement<TensorType, uint8_t, uint32_t>;
             break;
         }
         case armnn::DataType::Signed32:
         {
             dumpElementFunction = &DumpTensorElement<TensorType, int32_t>;
             break;
         }
         case armnn::DataType::Float16:
         {
             dumpElementFunction = &DumpTensorElement<TensorType, armnn::Half>;
             break;
         }
         case armnn::DataType::QAsymmS8:
         {
             dumpElementFunction = &DumpTensorElement<TensorType, int8_t, int32_t>;
             break;
         }
         case armnn::DataType::Boolean:
         {
             dumpElementFunction = &DumpTensorElement<TensorType, bool>;
             break;
         }
         default:
         {
             dumpElementFunction = nullptr;
         }
     }
     if (dumpElementFunction != nullptr)
     {
         const unsigned int numDimensions = tensor.GetNumDimensions();
         const armnn::TensorShape shape = tensor.GetShape();
         if (!shape.AreAllDimensionsSpecified())
         {
             fileStream << "Cannot dump tensor elements: not all dimensions are specified" << std::endl;
             return;
         }
         fileStream << "# Number of elements " << tensor.GetNumElements() << std::endl;
         if (numDimensions == 0)
         {
             fileStream << "# Shape []" << std::endl;
             return;
         }
         fileStream << "# Shape [" << shape[0];
         for (unsigned int d = 1; d < numDimensions; ++d)
         {
             fileStream << "," << shape[d];
         }
         fileStream << "]" << std::endl;
         fileStream << "Each line contains the data of each of the elements of dimension0. In NCHW and NHWC, each line"
                       " will be a batch" << std::endl << std::endl;
         // Split will create a new line after all elements of the first dimension
         // (in a 4, 3, 2, 3 tensor, there will be 4 lines of 18 elements)
         unsigned int split = 1;
         if (numDimensions == 1)
         {
             split = shape[0];
         }
         else
         {
             for (unsigned int i = 1; i < numDimensions; ++i)
             {
                 split *= shape[i];
             }
         }
         // Print all elements in the tensor
         for (unsigned int elementIndex = 0; elementIndex < tensor.GetNumElements(); ++elementIndex)
         {
             (*dumpElementFunction)(tensor, elementIndex, fileStream);
             if ( (elementIndex + 1) % split == 0 )
             {
                 fileStream << std::endl;
             }
         }
         fileStream << std::endl;
     }
     else
     {
         fileStream << "Cannot dump tensor elements: Unsupported data type "
             << static_cast<unsigned int>(tensor.GetDataType()) << std::endl;
     }
     if (!fileStream.good())
     {
         VLOG(DRIVER) << "An error occurred when writing to file %s" << fileName.c_str();
     }
 }
References TensorShape::AreAllDimensionsSpecified(), armnn::Boolean, armnn::Float16, armnn::Float32, TensorShape::GetNumElements(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::Signed32.
DumpTensor< armnn::ConstTensor >()
template void armnn_driver::DumpTensor< armnn::ConstTensor > (const std::string & dumpDir, const std::string & requestName, const std::string & tensorName, const armnn::ConstTensor & tensor)
DumpTensor< armnn::Tensor >()
template void armnn_driver::DumpTensor< armnn::Tensor > (const std::string & dumpDir, const std::string & requestName, const std::string & tensorName, const armnn::Tensor & tensor)
ExportNetworkGraphToDotFile()
std::string ExportNetworkGraphToDotFile (const armnn::IOptimizedNetwork & optimizedNetwork, const std::string & dumpDir)
Definition at line 389 of file CanonicalUtils.cpp.
 {
     std::string fileName;
     // The dump directory must exist in advance.
     if (dumpDir.empty())
     {
         return fileName;
     }
     std::string timestamp = GetFileTimestamp();
     if (timestamp.empty())
     {
         return fileName;
     }
     // Set the name of the output .dot file.
     fs::path dumpPath = dumpDir;
     fs::path tempFilePath = dumpPath / (timestamp + "_networkgraph.dot");
     fileName = tempFilePath.string();
     VLOG(DRIVER) << "Exporting the optimized network graph to file: %s" << fileName.c_str();
     // Write the network graph to a dot file.
     std::ofstream fileStream;
     fileStream.open(fileName, std::ofstream::out | std::ofstream::trunc);
     if (!fileStream.good())
     {
         VLOG(DRIVER) << "Could not open file %s for writing" << fileName.c_str();
         return fileName;
     }
     if (optimizedNetwork.SerializeToDot(fileStream) != armnn::Status::Success)
     {
         VLOG(DRIVER) << "An error occurred when writing to file %s" << fileName.c_str();
     }
     return fileName;
 }
References GetFileTimestamp(), IOptimizedNetwork::SerializeToDot(), and armnn::Success.
Referenced by ArmnnDriverImpl::PrepareArmnnModel(), and ArmnnDriverImpl::PrepareArmnnModelFromCache().
GetFileTimestamp()
std::string GetFileTimestamp ()
Definition at line 557 of file CanonicalUtils.cpp.
 {
     // used to get a timestamp to name diagnostic files (the ArmNN serialized graph
     // and getSupportedOperations.txt files)
     timespec ts;
     int iRet = clock_gettime(CLOCK_MONOTONIC_RAW, &ts);
     std::stringstream ss;
     if (iRet == 0)
     {
         ss << std::to_string(ts.tv_sec) << "_" << std::to_string(ts.tv_nsec);
     }
     else
     {
         VLOG(DRIVER) << "clock_gettime failed with errno " <<
             std::to_string(errno).c_str() << " : " <<
             std::strerror(errno);
     }
     return ss.str();
 }
Referenced by ExportNetworkGraphToDotFile(), and SerializeNetwork().
GetInputActivationFunction()
bool armnn_driver::GetInputActivationFunction (const Operation & operation, uint32_t inputIndex, ActivationFn & outActivationFunction, const Model & model, const ConversionData & data) inline
Definition at line 823 of file ConversionUtils.hpp.
 {
     return GetInputActivationFunctionImpl(operation,
                                           inputIndex,
                                           OperandType::INT32,
                                           outActivationFunction,
                                           model,
                                           data);
 }
References GetInputActivationFunctionImpl().
Referenced by ConvertPooling2d(), and GetOptionalInputActivation().
GetInputActivationFunctionFromTensor()
bool armnn_driver::GetInputActivationFunctionFromTensor (const Operation & operation, uint32_t inputIndex, ActivationFn & outActivationFunction, const Model & model, const ConversionData & data) inline
Definition at line 837 of file ConversionUtils.hpp.
 {
     // This only accepts a 1-D tensor of size 1
     return GetInputActivationFunctionImpl(operation,
                                           inputIndex,
                                           OperandType::INT32,
                                           outActivationFunction,
                                           model,
                                           data);
 }
References GetInputActivationFunctionImpl().
GetInputActivationFunctionImpl()
bool armnn_driver::GetInputActivationFunctionImpl (const Operation & operation, uint32_t inputIndex, OperandType type, ActivationFn & outActivationFunction, const Model & model, const ConversionData & data) inline
Definition at line 800 of file ConversionUtils.hpp.
 {
     if (type != OperandType::INT32 && type != OperandType::TENSOR_INT32)
     {
         VLOG(DRIVER) << __func__ << ": unexpected operand type: " << type
                      << " should be OperandType::INT32 or OperandType::TENSOR_INT32";
         return false;
     }
     int32_t activationFunctionAsInt;
     if (!GetInputScalar(operation, inputIndex, type, activationFunctionAsInt, model, data))
     {
         return Fail("%s: failed to get activation input value", __func__);
     }
     outActivationFunction = static_cast<ActivationFn>(activationFunctionAsInt);
     return true;
 }
References GetInputScalar().
Referenced by GetInputActivationFunction(), and GetInputActivationFunctionFromTensor().
GetInputFloat32()
bool armnn_driver::GetInputFloat32 (const Operation & operation, uint32_t inputIndex, float & outValue, const Model & model, const ConversionData & data) inline
Definition at line 791 of file ConversionUtils.hpp.
 {
     return GetInputScalar(operation, inputIndex, OperandType::FLOAT32, outValue, model, data);
 }
References GetInputScalar().
GetInputInt32()
bool armnn_driver::GetInputInt32 (const Operation & operation, uint32_t inputIndex, int32_t & outValue, const Model & model, const ConversionData & data) inline
Definition at line 782 of file ConversionUtils.hpp.
 {
     return GetInputScalar(operation, inputIndex, OperandType::INT32, outValue, model, data);
 }
References GetInputScalar().
Referenced by GetInputPaddingScheme().
GetInputOperand()
const Operand* armnn_driver::GetInputOperand (const Operation & operation, uint32_t inputIndex, const Model & model, bool failOnIndexOutOfBounds = true) inline
Definition at line 643 of file ConversionUtils.hpp.
 {
     if (inputIndex >= operation.inputs.size())
     {
         if (failOnIndexOutOfBounds)
         {
             Fail("%s: invalid input index: %i out of %i", __func__, inputIndex, operation.inputs.size());
         }
         return nullptr;
     }
     // Model should have been validated beforehand
     ARMNN_ASSERT(operation.inputs[inputIndex] < getMainModel(model).operands.size());
     return &getMainModel(model).operands[operation.inputs[inputIndex]];
 }
References ARMNN_ASSERT, and getMainModel().
Referenced by ConvertOperationInputToConstTensorPin(), ConvertPaddings(), ConvertReduce(), ConvertToLayerInputHandle(), DequantizeIfRequired(), GetInputScalar(), GetOperandType(), GetOptionalBool(), IsWeightsValid(), and OptionalDataLayout().
GetInputPaddingScheme()
bool GetInputPaddingScheme (const Operation & operation, uint32_t inputIndex, PaddingScheme & outPaddingScheme, const Model & model, const ConversionData & data)
Definition at line 761 of file ConversionUtils.cpp.
 {
     int32_t paddingSchemeAsInt;
     if (!GetInputInt32(operation, inputIndex, paddingSchemeAsInt, model, data))
     {
         return Fail("%s: failed to get padding scheme input value", __func__);
     }
     outPaddingScheme = static_cast<::android::nn::PaddingScheme>(paddingSchemeAsInt);
     return true;
 }
References GetInputInt32().
Referenced by ConvertPooling2d().
GetInputScalar()
bool armnn_driver::GetInputScalar (const Operation & operation, uint32_t inputIndex, OperandType type, OutputType & outValue, const Model & model, const ConversionData & data, bool optional = false)
Definition at line 742 of file ConversionUtils.hpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!optional && !operand)
     {
         return Fail("%s: invalid input operand at index %i", __func__, inputIndex);
     }
     if (!optional && operand->type != type)
     {
         VLOG(DRIVER) << __func__ << ": unexpected operand type: " << operand->type << " should be: " << type;
         return false;
     }
     if (!optional && operand->location.length != sizeof(OutputType))
     {
         return Fail("%s: incorrect operand location length: %i (should be %i)",
                     __func__, operand->location.length, sizeof(OutputType));
     }
     const void* valueAddress = GetOperandValueReadOnlyAddress(*operand, model, data);
     if (!optional && !valueAddress)
     {
         return Fail("%s: failed to get address for operand", __func__);
     }
     if(!optional)
     {
         outValue = *(static_cast<const OutputType*>(valueAddress));
     }
     return true;
 }
References GetInputOperand(), and GetOperandValueReadOnlyAddress().
Referenced by ConvertPooling2d(), ConvertReduce(), GetInputActivationFunctionImpl(), GetInputFloat32(), GetInputInt32(), and GetOptionalConvolutionDilationParams().
GetMemoryFromPointer()
void * GetMemoryFromPointer (const Request::Argument & requestArg)
Definition at line 77 of file CanonicalUtils.cpp.
 {
     // get the pointer memory
     auto ptrMemory = std::visit([](std::variant<const void*, void*>&& memory)
{
                                     if (std::holds_alternative<const void*>(memory))
{
                                         auto ptr = std::get<const void*>(memory);
                                         auto ptrMemory = static_cast<const uint8_t*>(ptr);
                                         return const_cast<uint8_t*>(ptrMemory);
                                     }
                                     else
{
                                         auto ptr = std::get<void*>(memory);
                                         return static_cast<uint8_t*>(ptr);
                                     }
                                 }, requestArg.location.pointer);
     return ptrMemory;
 }
GetMemoryFromPool()
void * GetMemoryFromPool (DataLocation location, const std::vector< android::nn::RunTimePoolInfo > & memPools)
Returns a pointer to a specific location in a pool`.
Definition at line 66 of file CanonicalUtils.cpp.
 {
     // find the location within the pool
     assert(location.poolIndex < memPools.size());
     const android::nn::RunTimePoolInfo& memPool = memPools[location.poolIndex];
     uint8_t* memPoolBuffer = memPool.getBuffer();
     uint8_t* memory = memPoolBuffer + location.offset;
     return memory;
 }
Referenced by GetOperandValueReadOnlyAddress().
GetModelSummary()
std::string GetModelSummary (const Model & model)
Definition at line 523 of file CanonicalUtils.cpp.
 {
     std::stringstream result;
     result << model.main.inputIndexes.size() << " input(s), "
            << model.main.operations.size() << " operation(s), "
            << model.main.outputIndexes.size() << " output(s), "
            << model.main.operands.size() << " operand(s) "
            << std::endl;
     result << "Inputs: ";
     for (uint32_t i = 0; i < model.main.inputIndexes.size(); i++)
     {
         result << GetOperandSummary(model.main.operands[model.main.inputIndexes[i]]) << ", ";
     }
     result << std::endl;
     result << "Operations: ";
     for (uint32_t i = 0; i < model.main.operations.size(); i++)
     {
         result << model.main.operations[i].type << ", ";
     }
     result << std::endl;
     result << "Outputs: ";
     for (uint32_t i = 0; i < model.main.outputIndexes.size(); i++)
     {
         result << GetOperandSummary(model.main.operands[model.main.outputIndexes[i]]) << ", ";
     }
     result << std::endl;
     return result.str();
 }
References GetOperandSummary().
Referenced by ArmnnPreparedModel::execute(), and ArmnnPreparedModel::executeFenced().
GetOperandSummary()
std::string GetOperandSummary (const Operand & operand)
Definition at line 191 of file CanonicalUtils.cpp.
 {
     std::stringstream ss;
     ss << "operand dimensions: [ ";
     for (unsigned int i = 0; i < operand.dimensions.size(); ++i)
     {
         ss << operand.dimensions[i] << " ";
     }
     ss << "] operand type: " << operand.type;
     return ss.str();
 }
Referenced by GetModelSummary().
GetOperandType()
bool armnn_driver::GetOperandType (const Operation & operation, uint32_t inputIndex, const Model & model, OperandType & type) inline
Definition at line 683 of file ConversionUtils.hpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!operand)
     {
         return Fail("%s: invalid input operand at index %i", __func__, inputIndex);
     }
     type = operand->type;
     return true;
 }
References GetInputOperand().
GetOperandValueReadOnlyAddress()
const void * GetOperandValueReadOnlyAddress (const Operand & operand, const Model & model, const ConversionData & data, bool optional)
Definition at line 777 of file ConversionUtils.cpp.
 {
     const void* valueStart = nullptr;
     switch (operand.lifetime)
     {
         case OperandLifeTime::CONSTANT_COPY:
         {
             valueStart = model.operandValues.data() + operand.location.offset;
             break;
         }
         case OperandLifeTime::POINTER:
         {
             // Pointer specified in the model
             valueStart = std::get<const void*>(operand.location.pointer);
             break;
         }
         case OperandLifeTime::CONSTANT_REFERENCE:
         {
             // Constant specified via a Memory object
             valueStart = GetMemoryFromPool(operand.location, data.m_MemPools);
             break;
         }
         case OperandLifeTime::NO_VALUE:
         {
             // An optional input tensor with no values is not an error so should not register as a fail
             if (optional)
             {
                 valueStart = nullptr;
                 break;
             }
             [[fallthrough]];
         }
         default:
         {
             VLOG(DRIVER) << __func__ << ": unsupported/invalid operand lifetime:: " << operand.lifetime;
             valueStart = nullptr;
         }
     }
     return valueStart;
 }
References GetMemoryFromPool(), and ConversionData::m_MemPools.
Referenced by ConvertOperandToConstTensorPin(), DequantizeIfRequired(), GetInputScalar(), GetOptionalBool(), GetTensorInt32Values(), and OptionalDataLayout().
GetOptionalBool()
bool armnn_driver::GetOptionalBool (const Operation & operation, uint32_t inputIndex, const Model & model, const ConversionData & data) inline
Definition at line 900 of file ConversionUtils.hpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!operand)
     {
         return false;
     }
     if (!IsBool(*operand))
     {
         return false;
     }
     const void* valueAddress = GetOperandValueReadOnlyAddress(*operand, model, data);
     if (!valueAddress)
     {
         return false;
     }
     return *(static_cast<const bool*>(valueAddress));
 }
References GetInputOperand(), and GetOperandValueReadOnlyAddress().
GetOptionalConvolutionDilationParams()
bool armnn_driver::GetOptionalConvolutionDilationParams (const Operation & operation, uint32_t dilationXIndex, ConvolutionDescriptor & descriptor, const Model & model, const ConversionData & data)
Definition at line 874 of file ConversionUtils.hpp.
 {
     bool success = true;
     if (operation.inputs.size() >= dilationXIndex + 2)
     {
         success &= GetInputScalar(operation,
                                   dilationXIndex,
                                   OperandType::INT32,
                                   descriptor.m_DilationX,
                                   model,
                                   data);
         success &= GetInputScalar(operation,
                                   dilationXIndex + 1,
                                   OperandType::INT32,
                                   descriptor.m_DilationY,
                                   model,
                                   data);
     }
     return success;
 }
References GetInputScalar().
GetOptionalInputActivation()
bool armnn_driver::GetOptionalInputActivation (const Operation & operation, uint32_t inputIndex, ActivationFn & activationFunction, const Model & model, const ConversionData & data) inline
Definition at line 853 of file ConversionUtils.hpp.
 {
     if (operation.inputs.size() <= inputIndex)
     {
         activationFunction = ActivationFn::kActivationNone;
     }
     else
     {
         if (!GetInputActivationFunction(operation, inputIndex, activationFunction, model, data))
         {
             return Fail("%s: Operation has invalid inputs", __func__);
         }
     }
     return true;
 }
References GetInputActivationFunction().
GetOutputOperand()
const Operand* armnn_driver::GetOutputOperand (const Operation & operation, uint32_t outputIndex, const Model & model) inline
Definition at line 662 of file ConversionUtils.hpp.
 {
     if (outputIndex >= operation.outputs.size())
     {
         Fail("%s: invalid output index: %i out of %i", __func__, outputIndex, operation.outputs.size());
         return nullptr;
     }
     // Model should have been validated beforehand
     ARMNN_ASSERT(operation.outputs[outputIndex] < getMainModel(model).operands.size());
     return &getMainModel(model).operands[operation.outputs[outputIndex]];
 }
References ARMNN_ASSERT, and getMainModel().
Referenced by ConvertPooling2d(), ConvertReduce(), ConvertToActivation(), and SetupAndTrackLayerOutputSlot().
GetTensorInfoForOperand()
armnn::TensorInfo GetTensorInfoForOperand (const Operand & operand)
Definition at line 97 of file CanonicalUtils.cpp.
 {
     using namespace armnn;
     bool perChannel = false;
     bool isScalar   = false;
     DataType type;
     switch (operand.type)
     {
         case OperandType::TENSOR_BOOL8:
             type = armnn::DataType::Boolean;
             break;
         case OperandType::TENSOR_FLOAT32:
             type = armnn::DataType::Float32;
             break;
         case OperandType::TENSOR_FLOAT16:
             type = armnn::DataType::Float16;
             break;
         case OperandType::TENSOR_QUANT8_ASYMM:
             type = armnn::DataType::QAsymmU8;
             break;
         case OperandType::TENSOR_QUANT8_SYMM_PER_CHANNEL:
             perChannel=true;
             ARMNN_FALLTHROUGH;
         case OperandType::TENSOR_QUANT8_SYMM:
             type = armnn::DataType::QSymmS8;
             break;
         case OperandType::TENSOR_QUANT16_SYMM:
             type = armnn::DataType::QSymmS16;
             break;
         case OperandType::TENSOR_INT32:
             type = armnn::DataType::Signed32;
             break;
         case OperandType::INT32:
             type = armnn::DataType::Signed32;
             isScalar = true;
             break;
         case OperandType::TENSOR_QUANT8_ASYMM_SIGNED:
             type = armnn::DataType::QAsymmS8;
             break;
         default:
             throw UnsupportedOperand<OperandType>(operand.type);
     }
     TensorInfo ret;
     if (isScalar)
     {
         ret = TensorInfo(TensorShape(armnn::Dimensionality::Scalar), type);
     }
     else
     {
         if (operand.dimensions.size() == 0)
         {
             TensorShape tensorShape(Dimensionality::NotSpecified);
             ret = TensorInfo(tensorShape, type);
         }
         else
         {
             std::vector<unsigned char> dimensionsSpecificity(operand.dimensions.size(), true);
             int count = 0;
             std::for_each(operand.dimensions.data(),
                           operand.dimensions.data() +  operand.dimensions.size(),
                           [&](const unsigned int val)
{
                               if (val == 0)
{
                                   dimensionsSpecificity[count] = false;
                               }
                               count++;
                           });
             TensorShape tensorShape(operand.dimensions.size(),
                                     operand.dimensions.data(),
                                     reinterpret_cast<const bool *>(dimensionsSpecificity.data()));
             ret = TensorInfo(tensorShape, type);
         }
     }
     if (perChannel)
     {
         // ExtraParams is expected to be of type channelQuant
         const auto& perAxisQuantParams = std::get<Operand::SymmPerChannelQuantParams>(operand.extraParams);
         ret.SetQuantizationScales(perAxisQuantParams.scales);
         ret.SetQuantizationDim(MakeOptional<unsigned int>(perAxisQuantParams.channelDim));
     }
     else
     {
         ret.SetQuantizationScale(operand.scale);
         ret.SetQuantizationOffset(operand.zeroPoint);
     }
     return ret;
 }
References ARMNN_FALLTHROUGH, armnn::Boolean, armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Scalar, and armnn::Signed32.
Referenced by ConvertOperandToConstTensorPin(), ConvertPooling2d(), ConvertReduce(), ConvertToActivation(), ConvertToLayerInputHandle(), and SetupAndTrackLayerOutputSlot().
GetTensorInt32Values()
bool GetTensorInt32Values (const Operand & operand, std::vector< int32_t > & outValues, const Model & model, const ConversionData & data)
Definition at line 822 of file ConversionUtils.cpp.
 {
     if (operand.type != OperandType::TENSOR_INT32)
     {
         VLOG(DRIVER) << __func__ << ": invalid operand type: " << operand.type;
         return false;
     }
     const void* startAddress = GetOperandValueReadOnlyAddress(operand, model, data);
     if (!startAddress)
     {
         VLOG(DRIVER) << __func__ << ": failed to get operand address " << operand.type;
         return false;
     }
     // Check number of bytes is sensible
     const uint32_t numBytes = operand.location.length;
     if (numBytes % sizeof(int32_t) != 0)
     {
         return Fail("%s: invalid number of bytes: %i, expected to be a multiple of %i",
                     __func__, numBytes, sizeof(int32_t));
     }
     outValues.resize(numBytes / sizeof(int32_t));
     memcpy(outValues.data(), startAddress, numBytes);
     return true;
 }
References GetOperandValueReadOnlyAddress().
Referenced by ConvertPaddings(), and ConvertReduce().
IsConnectedToDequantize()
bool IsConnectedToDequantize (armnn::IOutputSlot * ioutputSlot)
Definition at line 1040 of file ConversionUtils.cpp.
 {
     VLOG(DRIVER) << "ConversionUtils::IsConnectedToDequantize()";
     if (!ioutputSlot)
     {
         return false;
     }
     VLOG(DRIVER) << "ConversionUtils::IsConnectedToDequantize() ioutputSlot is valid.";
     // Find the connections and layers..
     armnn::IConnectableLayer& owningLayer = ioutputSlot->GetOwningIConnectableLayer();
     if (owningLayer.GetType() == armnn::LayerType::Dequantize)
     {
         VLOG(DRIVER) << "ConversionUtils::IsConnectedToDequantize() connected to Dequantize Layer.";
         armnn::IInputSlot& inputSlot = owningLayer.GetInputSlot(0);
         armnn::IOutputSlot* connection = inputSlot.GetConnection();
         if (connection)
         {
             VLOG(DRIVER) << "ConversionUtils::IsConnectedToDequantize() Dequantize Layer has a connection.";
             armnn::IConnectableLayer& connectedLayer =
                     connection->GetOwningIConnectableLayer();
             if (connectedLayer.GetType() == armnn::LayerType::Constant)
             {
                 VLOG(DRIVER) << "ConversionUtils::IsConnectedToDequantize() Dequantize Layer connected to Constant";
                 return true;
             }
         }
     }
     return false;
 }
References armnn::Constant, armnn::Dequantize, IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IOutputSlot::GetOwningIConnectableLayer(), and IConnectableLayer::GetType().
IsDynamicTensor()
bool IsDynamicTensor (const armnn::TensorInfo & tensorInfo)
Checks if a tensor info represents a dynamic tensor.
Definition at line 488 of file CanonicalUtils.cpp.
 {
     if (tensorInfo.GetShape().GetDimensionality() == armnn::Dimensionality::NotSpecified)
     {
         return true;
     }
     // Account for the usage of the TensorShape empty constructor
     if (tensorInfo.GetNumDimensions() == 0)
     {
         return true;
     }
     return !tensorInfo.GetShape().AreAllDimensionsSpecified();
 }
References TensorShape::AreAllDimensionsSpecified(), TensorShape::GetDimensionality(), TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), and armnn::NotSpecified.
Referenced by ConvertPooling2d(), ConvertReduce(), ConvertToActivation(), ConvertToLayerInputHandle(), and SetupAndTrackLayerOutputSlot().
IsOperandConstant()
bool armnn_driver::IsOperandConstant (const Operand & operand) inline
Definition at line 698 of file ConversionUtils.hpp.
 {
     OperandLifeTime lifetime = operand.lifetime;
     return lifetime == OperandLifeTime::CONSTANT_COPY ||
            lifetime == OperandLifeTime::CONSTANT_REFERENCE ||
            lifetime == OperandLifeTime::POINTER ||
            lifetime == OperandLifeTime::NO_VALUE;
 }
Referenced by ConvertOperandToConstTensorPin(), and DequantizeIfRequired().
IsQSymm8()
bool armnn_driver::IsQSymm8 (const Operand & operand) inline
Definition at line 1002 of file ConversionUtils.hpp.
 {
     return operand.type == OperandType::TENSOR_QUANT8_SYMM;
 }
Referenced by DequantizeIfRequired().
isQuantizedOperand()
bool isQuantizedOperand (const OperandType & operandType)
Definition at line 507 of file CanonicalUtils.cpp.
 {
     if (operandType == OperandType::TENSOR_QUANT8_ASYMM ||
         operandType == OperandType::TENSOR_QUANT8_SYMM_PER_CHANNEL ||
         operandType == OperandType::TENSOR_QUANT8_SYMM ||
         operandType == OperandType::TENSOR_QUANT16_SYMM ||
         operandType == OperandType::TENSOR_QUANT8_ASYMM_SIGNED)
     {
         return true;
     }
     else
     {
         return false;
     }
 }
IsWeightsValid()
bool IsWeightsValid (const Operation & operation, uint32_t inputIndex, const Model & model)
Utility functions.
Definition at line 134 of file ConversionUtils.cpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!operand)
     {
         Fail("%s: failed to get input operand %i", __func__, inputIndex);
         return false;
     }
     if (operand->lifetime    != OperandLifeTime::CONSTANT_COPY
         && operand->lifetime != OperandLifeTime::CONSTANT_REFERENCE
         && operand->lifetime != OperandLifeTime::NO_VALUE)
     {
         return false;
     }
     return true;
 }
References GetInputOperand().
OptionalDataLayout()
armnn::DataLayout OptionalDataLayout (const Operation & operation, uint32_t inputIndex, const Model & model, ConversionData & data)
Definition at line 853 of file ConversionUtils.cpp.
 {
     const Operand* operand = GetInputOperand(operation, inputIndex, model);
     if (!operand)
     {
         return armnn::DataLayout::NHWC;
     }
     if (!IsBool(*operand))
     {
         return armnn::DataLayout::NHWC;
     }
     const void* valueAddress = GetOperandValueReadOnlyAddress(*operand, model, data);
     if (!valueAddress)
     {
         return armnn::DataLayout::NHWC;
     }
     if (*(static_cast<const bool*>(valueAddress)))
     {
         return armnn::DataLayout::NCHW;
     }
     else
     {
         return armnn::DataLayout::NHWC;
     }
 }
References GetInputOperand(), GetOperandValueReadOnlyAddress(), armnn::NCHW, and armnn::NHWC.
Referenced by ConvertPooling2d().
ProcessActivation()
armnn::IConnectableLayer * ProcessActivation (const armnn::TensorInfo & tensorInfo, ActivationFn activation, armnn::IConnectableLayer * prevLayer, ConversionData & data)
Definition at line 885 of file ConversionUtils.cpp.
 {
     ARMNN_ASSERT(prevLayer->GetNumOutputSlots() == 1);
     prevLayer->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     armnn::IConnectableLayer* activationLayer = prevLayer;
     if (activation != ActivationFn::kActivationNone)
     {
         armnn::ActivationDescriptor activationDesc;
         switch (activation)
         {
             case ActivationFn::kActivationRelu:
             {
                 activationDesc.m_Function = armnn::ActivationFunction::ReLu;
                 break;
             }
             case ActivationFn::kActivationRelu1:
             {
                 activationDesc.m_Function = armnn::ActivationFunction::BoundedReLu;
                 activationDesc.m_A = 1.0f;
                 activationDesc.m_B = -1.0f;
                 break;
             }
             case ActivationFn::kActivationRelu6:
             {
                 activationDesc.m_Function = armnn::ActivationFunction::BoundedReLu;
                 activationDesc.m_A = 6.0f;
                 break;
             }
             case ActivationFn::kActivationSigmoid:
             {
                 activationDesc.m_Function = armnn::ActivationFunction::Sigmoid;
                 break;
             }
             case ActivationFn::kActivationTanh:
             {
                 activationDesc.m_Function = armnn::ActivationFunction::TanH;
                 activationDesc.m_A = 1.0f;
                 activationDesc.m_B = 1.0f;
                 break;
             }
             default:
             {
                 Fail("%s: Invalid activation enum value %i", __func__, activation);
                 return nullptr;
             }
         }
         bool isSupported = false;
         armnn::BackendId setBackend;
         FORWARD_LAYER_SUPPORT_FUNC(__func__,
                                    IsActivationSupported,
                                    data.m_Backends,
                                    isSupported,
                                    setBackend,
                                    prevLayer->GetOutputSlot(0).GetTensorInfo(),
                                    tensorInfo,
                                    activationDesc);
         if (!isSupported)
         {
             return nullptr;
         }
         activationLayer = data.m_Network->AddActivationLayer(activationDesc);
         activationLayer->SetBackendId(setBackend);
         prevLayer->GetOutputSlot(0).Connect(activationLayer->GetInputSlot(0));
         activationLayer->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     }
     return activationLayer;
 }
References ARMNN_ASSERT, armnn::BoundedReLu, IOutputSlot::Connect(), FORWARD_LAYER_SUPPORT_FUNC, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumOutputSlots(), IConnectableLayer::GetOutputSlot(), IOutputSlot::GetTensorInfo(), ActivationDescriptor::m_A, ActivationDescriptor::m_B, ConversionData::m_Backends, ActivationDescriptor::m_Function, ConversionData::m_Network, armnn::ReLu, IConnectableLayer::SetBackendId(), IOutputSlot::SetTensorInfo(), armnn::Sigmoid, and armnn::TanH.
Referenced by SetupAndTrackLayerOutputSlot().
RenameExportedFiles()
void RenameExportedFiles (const std::string & existingSerializedFileName, const std::string & existingDotFileName, const std::string & dumpDir, const armnn::NetworkId networkId)
Definition at line 577 of file CanonicalUtils.cpp.
 {
     if (dumpDir.empty())
     {
         return;
     }
     RenameFile(existingSerializedFileName, std::string("_network.armnn"), dumpDir, networkId);
     RenameFile(existingDotFileName, std::string("_networkgraph.dot"), dumpDir, networkId);
 }
References RenameFile().
Referenced by ArmnnDriverImpl::PrepareArmnnModel().
RenameFile()
void RenameFile (const std::string & existingName, const std::string & extension, const std::string & dumpDir, const armnn::NetworkId networkId)
Definition at line 590 of file CanonicalUtils.cpp.
 {
     if (existingName.empty() || dumpDir.empty())
     {
         return;
     }
     fs::path dumpPath = dumpDir;
     const fs::path newFileName = dumpPath / (std::to_string(networkId) + extension);
     int iRet = rename(existingName.c_str(), newFileName.c_str());
     if (iRet != 0)
     {
         std::stringstream ss;
         ss << "rename of [" << existingName << "] to [" << newFileName << "] failed with errno "
            << std::to_string(errno) << " : " << std::strerror(errno);
         VLOG(DRIVER) << ss.str().c_str();
     }
 }
Referenced by RenameExportedFiles().
SerializeNetwork()
std::string SerializeNetwork (const armnn::INetwork & network, const std::string & dumpDir, std::vector< uint8_t > & dataCacheData, bool dataCachingActive)
Definition at line 429 of file CanonicalUtils.cpp.
 {
     std::string fileName;
     bool bSerializeToFile = true;
     if (dumpDir.empty())
     {
         bSerializeToFile = false;
     }
     else
     {
         std::string timestamp = GetFileTimestamp();
         if (timestamp.empty())
         {
             bSerializeToFile = false;
         }
     }
     if (!bSerializeToFile && !dataCachingActive)
     {
         return fileName;
     }
     auto serializer(armnnSerializer::ISerializer::Create());
     // Serialize the Network
     serializer->Serialize(network);
     if (dataCachingActive)
     {
         std::stringstream stream;
         auto serialized = serializer->SaveSerializedToStream(stream);
         if (serialized)
         {
             std::string const serializedString{stream.str()};
             std::copy(serializedString.begin(),
                       serializedString.end(),
                       std::back_inserter(dataCacheData));
         }
     }
     if (bSerializeToFile)
     {
         // Set the name of the output .armnn file.
         fs::path dumpPath = dumpDir;
         std::string timestamp = GetFileTimestamp();
         fs::path tempFilePath = dumpPath / (timestamp + "_network.armnn");
         fileName = tempFilePath.string();
         // Save serialized network to a file
         std::ofstream serializedFile(fileName, std::ios::out | std::ios::binary);
         auto serialized = serializer->SaveSerializedToStream(serializedFile);
         if (!serialized)
         {
             VLOG(DRIVER) << "An error occurred when serializing to file %s" << fileName.c_str();
         }
     }
     return fileName;
 }
References ISerializer::Create(), and GetFileTimestamp().
Referenced by ArmnnDriverImpl::PrepareArmnnModel().
SetupAndTrackLayerOutputSlot() [1/2]
bool SetupAndTrackLayerOutputSlot (const Operation & operation, uint32_t operationOutputIndex, armnn::IConnectableLayer & layer, uint32_t layerOutputIndex, const Model & model, ConversionData & data, const armnn::TensorInfo * overrideOutputInfo, const std::function< void(const armnn::TensorInfo &, bool &)> & validateFunc, const ActivationFn & activationFunction, bool inferOutputShapes)
Definition at line 963 of file ConversionUtils.cpp.
 {
     const Operand* outputOperand = GetOutputOperand(operation, operationOutputIndex, model);
     if ((outputOperand == nullptr) || (operationOutputIndex >= layer.GetNumOutputSlots()))
     {
         return false;
     }
     armnn::IOutputSlot& outputSlot = layer.GetOutputSlot(layerOutputIndex);
     if (overrideOutputInfo == nullptr)
     {
         outputSlot.SetTensorInfo(GetTensorInfoForOperand(*outputOperand));
     }
     else
     {
         outputSlot.SetTensorInfo(*overrideOutputInfo);
     }
     bool isSupported = false;
     if (validateFunc && (IsDynamicTensor(outputSlot.GetTensorInfo()) || inferOutputShapes))
     {
         // Type one dynamic tensors require the previous layer's output shape for inference
         for (unsigned int inputSlotIndex = 0; inputSlotIndex < layer.GetNumInputSlots(); ++inputSlotIndex)
         {
             if(!layer.GetInputSlot(inputSlotIndex).GetConnection())
             {
                 return false;
             }
         }
         // IsTensorInfoSet will infer the dynamic output shape
         outputSlot.IsTensorInfoSet();
         // Once the shape is inferred we can validate it
         validateFunc(outputSlot.GetTensorInfo(), isSupported);
         if(!isSupported)
         {
             for (unsigned int inputSlotIndex = 0; inputSlotIndex < layer.GetNumInputSlots(); ++inputSlotIndex)
             {
                 layer.GetInputSlot(inputSlotIndex).GetConnection()->Disconnect(layer.GetInputSlot(inputSlotIndex));
             }
             return false;
         }
     }
     const uint32_t operandIndex = operation.outputs[operationOutputIndex];
     if (activationFunction != ActivationFn::kActivationNone)
     {
         const armnn::TensorInfo& activationOutputInfo = outputSlot.GetTensorInfo();
         armnn::IConnectableLayer* const endLayer = ProcessActivation(activationOutputInfo, activationFunction,
                                                                      &layer, data);
         if (!endLayer)
         {
             return Fail("%s: ProcessActivation failed", __func__);
         }
         armnn::IOutputSlot& activationOutputSlot = endLayer->GetOutputSlot(layerOutputIndex);
         data.m_OutputSlotForOperand[operandIndex] = &activationOutputSlot;
     }
     else
     {
         data.m_OutputSlotForOperand[operandIndex] = &outputSlot;
     }
     return true;
 }
References IOutputSlot::Disconnect(), IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetNumOutputSlots(), GetOutputOperand(), IConnectableLayer::GetOutputSlot(), IOutputSlot::GetTensorInfo(), GetTensorInfoForOperand(), IsDynamicTensor(), IOutputSlot::IsTensorInfoSet(), ConversionData::m_OutputSlotForOperand, ProcessActivation(), and IOutputSlot::SetTensorInfo().
Referenced by ConvertPooling2d(), ConvertReduce(), ConvertToActivation(), and SetupAndTrackLayerOutputSlot().
SetupAndTrackLayerOutputSlot() [2/2]
bool armnn_driver::SetupAndTrackLayerOutputSlot (const Operation & operation, uint32_t outputIndex, armnn::IConnectableLayer & layer, const Model & model, ConversionData & data, const armnn::TensorInfo * overrideOutputInfo = nullptr, const std::function< void(const armnn::TensorInfo &, bool &)> & validateFunc = nullptr, const ActivationFn & activationFunction = ActivationFn::kActivationNone) inline
Definition at line 959 of file ConversionUtils.hpp.
 {
     return SetupAndTrackLayerOutputSlot(operation,
                                         outputIndex,
                                         layer,
                                         outputIndex,
                                         model,
                                         data,
                                         overrideOutputInfo,
                                         validateFunc,
                                         activationFunction);
 }
References SetupAndTrackLayerOutputSlot().
SwizzleAndroidNn4dTensorToArmNn()
void SwizzleAndroidNn4dTensorToArmNn (armnn::TensorInfo & tensorInfo, const void * input, void * output, const armnn::PermutationVector & mappings)
Swizzles tensor data in input according to the dimension mappings.
Definition at line 40 of file CanonicalUtils.cpp.
 {
     assert(tensorInfo.GetNumDimensions() == 4U);
     armnn::DataType dataType = tensorInfo.GetDataType();
     switch (dataType)
     {
     case armnn::DataType::Float16:
     case armnn::DataType::Float32:
     case armnn::DataType::QAsymmU8:
     case armnn::DataType::QSymmS8:
     case armnn::DataType::QAsymmS8:
         // First swizzle tensor info
         tensorInfo = armnnUtils::Permuted(tensorInfo, mappings);
         // Then swizzle tensor data
         armnnUtils::Permute(tensorInfo.GetShape(), mappings, input, output, armnn::GetDataTypeSize(dataType));
         break;
     default:
         VLOG(DRIVER) << "Unknown armnn::DataType for swizzling";
         assert(0);
     }
 }
References armnn::Float16, armnn::Float32, TensorInfo::GetDataType(), armnn::GetDataTypeSize(), TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), armnnUtils::Permute(), armnnUtils::Permuted(), armnn::QAsymmS8, armnn::QAsymmU8, and armnn::QSymmS8.
Referenced by ConstTensorPin::ConstTensorPin().
Variable Documentation
g_DontPermute
const armnn::PermutationVector g_DontPermute {}
Definition at line 38 of file CanonicalUtils.cpp.
Referenced by DequantizeAndMakeConstTensorPin().