Arm NN: Convolution3dQueueDescriptor Struct Reference
Convolution3dQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< Convolution3dDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Additional Inherited Members
Public Attributes inherited from QueueDescriptorWithParameters< Convolution3dDescriptor >
Convolution3dDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions inherited from QueueDescriptorWithParameters< Convolution3dDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 211 of file WorkloadData.hpp.
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 1321 of file WorkloadData.cpp.
 {
     const std::string descriptorName{"Convolution3dQueueDescriptor"};
     uint32_t numInputs = 2;
     if (m_Parameters.m_BiasEnabled)
     {
         numInputs = 3;
     }
     ValidateNumInputs(workloadInfo,  descriptorName, numInputs);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     ValidateTensorNumDimensions(inputTensorInfo,  descriptorName, 5, "input");
     ValidateTensorNumDimensions(outputTensorInfo, descriptorName, 5, "output");
     const TensorInfo& weightTensorInfo = workloadInfo.m_InputTensorInfos[1];
     ValidateTensorNumDimensions(weightTensorInfo, descriptorName, 5, "weight");
     ValidateWeightDataType(inputTensorInfo, weightTensorInfo, descriptorName);
     Optional<TensorInfo> optionalBiasTensorInfo;
     if (m_Parameters.m_BiasEnabled)
     {
         optionalBiasTensorInfo = MakeOptional<TensorInfo>(workloadInfo.m_InputTensorInfos[2]);
         const TensorInfo& biasTensorInfo = optionalBiasTensorInfo.value();
         ValidateTensorDataType(biasTensorInfo, GetBiasDataType(inputTensorInfo.GetDataType()), descriptorName, "bias");
         ValidateBiasTensorQuantization(biasTensorInfo, weightTensorInfo, descriptorName);
     }
     if (m_Parameters.m_StrideX <= 0 || m_Parameters.m_StrideY <= 0 || m_Parameters.m_StrideZ <= 0 )
     {
         throw InvalidArgumentException(
                 fmt::format("{}: strideX (provided {}), strideY (provided {}) or strideZ (provided {})"
                             "cannot be either negative or 0.",
                             descriptorName, m_Parameters.m_StrideX, m_Parameters.m_StrideY, m_Parameters.m_StrideZ));
     }
     ValidatePerAxisQuantization(inputTensorInfo,
                                 outputTensorInfo,
                                 weightTensorInfo,
                                 optionalBiasTensorInfo,
                                 descriptorName);
     std::vector<DataType> supportedTypes =
     {
         DataType::BFloat16,
         DataType::Float16,
         DataType::Float32,
         DataType::QAsymmS8,
         DataType::QAsymmU8,
         DataType::QSymmS16,
         DataType::QSymmS8
     };
     ValidateDataTypes(inputTensorInfo, supportedTypes, descriptorName);
     ValidateTensorDataTypesMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
 }
References armnn::BFloat16, armnn::Float16, armnn::Float32, armnn::GetBiasDataType(), TensorInfo::GetDataType(), Convolution3dDescriptor::m_BiasEnabled, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< Convolution3dDescriptor >::m_Parameters, Convolution3dDescriptor::m_StrideX, Convolution3dDescriptor::m_StrideY, Convolution3dDescriptor::m_StrideZ, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, QueueDescriptor::ValidateTensorNumDimensions(), and OptionalReferenceSwitch< std::is_reference< T >::value, T >::value().
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp