//
// Copyright © 2017 Arm Ltd. All rights reserved.
// SPDX-License-Identifier: MIT
//

#pragma once
#include "NeonActivationFloatWorkload.hpp"
#include "NeonActivationUint8Workload.hpp"
#include "NeonAdditionFloatWorkload.hpp"
#include "NeonBaseConstantWorkload.hpp"
#include "NeonBaseMergerWorkload.hpp"
#include "NeonBaseSplitterWorkload.hpp"
#include "NeonBatchNormalizationFloatWorkload.hpp"
#include "NeonConstantFloatWorkload.hpp"
#include "NeonConstantUint8Workload.hpp"
#include "NeonConvertFp16ToFp32Workload.hpp"
#include "NeonConvertFp32ToFp16Workload.hpp"
#include "NeonConvolution2dBaseWorkload.hpp"
#include "NeonConvolution2dFloatWorkload.hpp"
#include "NeonConvolution2dUint8Workload.hpp"
#include "NeonDepthwiseConvolutionFloatWorkload.hpp"
#include "NeonDepthwiseConvolutionUint8Workload.hpp"
#include "NeonFloorFloatWorkload.hpp"
#include "NeonFullyConnectedWorkload.hpp"
#include "NeonL2NormalizationFloatWorkload.hpp"
#include "NeonLstmFloatWorkload.hpp"
#include "NeonMergerFloatWorkload.hpp"
#include "NeonMergerUint8Workload.hpp"
#include "NeonMultiplicationFloatWorkload.hpp"
#include "NeonNormalizationFloatWorkload.hpp"
#include "NeonPermuteWorkload.hpp"
#include "NeonPooling2dBaseWorkload.hpp"
#include "NeonPooling2dFloatWorkload.hpp"
#include "NeonPooling2dUint8Workload.hpp"
#include "NeonReshapeFloatWorkload.hpp"
#include "NeonReshapeUint8Workload.hpp"
#include "NeonSoftmaxFloatWorkload.hpp"
#include "NeonSoftmaxUint8Workload.hpp"
#include "NeonSplitterFloatWorkload.hpp"
#include "NeonSplitterUint8Workload.hpp"
#include "NeonSubtractionFloatWorkload.hpp"
