var searchData=
[
  ['datalayoutindexed_5601',['DataLayoutIndexed',['../classarmnn_utils_1_1_data_layout_indexed.html',1,'armnnUtils']]],
  ['debuglayer_5602',['DebugLayer',['../classarmnn_1_1_debug_layer.html',1,'armnn']]],
  ['debugqueuedescriptor_5603',['DebugQueueDescriptor',['../structarmnn_1_1_debug_queue_descriptor.html',1,'armnn']]],
  ['decoder_5604',['Decoder',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20bool_20_3e_5605',['Decoder&lt; bool &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20double_5ft_20_3e_5606',['Decoder&lt; double_t &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20float_20_3e_5607',['Decoder&lt; float &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20int32_5ft_20_3e_5608',['Decoder&lt; int32_t &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['defaultallocator_5609',['DefaultAllocator',['../classarmnn_1_1_default_allocator.html',1,'armnn']]],
  ['delegate_5610',['Delegate',['../classarmnn_delegate_1_1_delegate.html',1,'armnnDelegate']]],
  ['delegatedata_5611',['DelegateData',['../structarmnn_delegate_1_1_delegate_data.html',1,'DelegateData'],['../structarmnn_opaque_delegate_1_1_delegate_data.html',1,'DelegateData']]],
  ['deletebroadcasttoimpl_5612',['DeleteBroadcastToImpl',['../classarmnn_1_1optimizations_1_1_delete_broadcast_to_impl.html',1,'armnn::optimizations']]],
  ['depthtospacelayer_5613',['DepthToSpaceLayer',['../classarmnn_1_1_depth_to_space_layer.html',1,'armnn']]],
  ['depthtospacequeuedescriptor_5614',['DepthToSpaceQueueDescriptor',['../structarmnn_1_1_depth_to_space_queue_descriptor.html',1,'armnn']]],
  ['depthwiseconvolution2ddescriptor_5615',['DepthwiseConvolution2dDescriptor',['../structarmnn_1_1_depthwise_convolution2d_descriptor.html',1,'armnn']]],
  ['depthwiseconvolution2dlayer_5616',['DepthwiseConvolution2dLayer',['../classarmnn_1_1_depthwise_convolution2d_layer.html',1,'armnn']]],
  ['depthwiseconvolution2dqueuedescriptor_5617',['DepthwiseConvolution2dQueueDescriptor',['../structarmnn_1_1_depthwise_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['dequantizelayer_5618',['DequantizeLayer',['../classarmnn_1_1_dequantize_layer.html',1,'armnn']]],
  ['dequantizequeuedescriptor_5619',['DequantizeQueueDescriptor',['../structarmnn_1_1_dequantize_queue_descriptor.html',1,'armnn']]],
  ['deserializerimpl_5620',['DeserializerImpl',['../classarmnn_deserializer_1_1_i_deserializer_1_1_deserializer_impl.html',1,'armnnDeserializer::IDeserializer']]],
  ['detectionpostprocessdescriptor_5621',['DetectionPostProcessDescriptor',['../structarmnn_1_1_detection_post_process_descriptor.html',1,'armnn']]],
  ['detectionpostprocesslayer_5622',['DetectionPostProcessLayer',['../classarmnn_1_1_detection_post_process_layer.html',1,'armnn']]],
  ['detectionpostprocessqueuedescriptor_5623',['DetectionPostProcessQueueDescriptor',['../structarmnn_1_1_detection_post_process_queue_descriptor.html',1,'armnn']]],
  ['devicespec_5624',['DeviceSpec',['../classarmnn_1_1_device_spec.html',1,'armnn']]],
  ['divisionlayer_5625',['DivisionLayer',['../classarmnn_1_1_division_layer.html',1,'armnn']]],
  ['divisionqueuedescriptor_5626',['DivisionQueueDescriptor',['../structarmnn_1_1_division_queue_descriptor.html',1,'armnn']]],
  ['dotattributeset_5627',['DotAttributeSet',['../classarmnn_1_1_dot_attribute_set.html',1,'armnn']]],
  ['dotbase_5628',['DotBase',['../classarmnn_1_1_dot_base.html',1,'armnn']]],
  ['dotdefaults_5629',['DotDefaults',['../classarmnn_1_1_dot_defaults.html',1,'armnn']]],
  ['dotedge_5630',['DotEdge',['../classarmnn_1_1_dot_edge.html',1,'armnn']]],
  ['dotgraph_5631',['DotGraph',['../classarmnn_1_1_dot_graph.html',1,'armnn']]],
  ['dotnode_5632',['DotNode',['../classarmnn_1_1_dot_node.html',1,'armnn']]],
  ['driveroptions_5633',['DriverOptions',['../classarmnn__driver_1_1_driver_options.html',1,'armnn_driver']]],
  ['dynamicbackend_5634',['DynamicBackend',['../classarmnn_1_1_dynamic_backend.html',1,'armnn']]],
  ['dynamicbackendutils_5635',['DynamicBackendUtils',['../classarmnn_1_1_dynamic_backend_utils.html',1,'armnn']]]
];
