var searchData=
[
  ['qasymm8decoder_6225',['QASymm8Decoder',['../classarmnn_1_1_q_a_symm8_decoder.html',1,'armnn']]],
  ['qasymm8encoder_6226',['QASymm8Encoder',['../classarmnn_1_1_q_a_symm8_encoder.html',1,'armnn']]],
  ['qasymms8decoder_6227',['QASymmS8Decoder',['../classarmnn_1_1_q_a_symm_s8_decoder.html',1,'armnn']]],
  ['qasymms8encoder_6228',['QASymmS8Encoder',['../classarmnn_1_1_q_a_symm_s8_encoder.html',1,'armnn']]],
  ['qlstmbasicparameters_6229',['QLstmBasicParameters',['../structarmnn_1_1_q_lstm_basic_parameters.html',1,'armnn']]],
  ['qlstmdescriptor_6230',['QLstmDescriptor',['../structarmnn_1_1_q_lstm_descriptor.html',1,'armnn']]],
  ['qlstmlayer_6231',['QLstmLayer',['../classarmnn_1_1_q_lstm_layer.html',1,'armnn']]],
  ['qlstmoptcifgparameters_6232',['QLstmOptCifgParameters',['../structarmnn_1_1_q_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['qlstmoptlayernormparameters_6233',['QLstmOptLayerNormParameters',['../structarmnn_1_1_q_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['qlstmoptpeepholeparameters_6234',['QLstmOptPeepholeParameters',['../structarmnn_1_1_q_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['qlstmoptprojectionparameters_6235',['QLstmOptProjectionParameters',['../structarmnn_1_1_q_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['qlstmqueuedescriptor_6236',['QLstmQueueDescriptor',['../structarmnn_1_1_q_lstm_queue_descriptor.html',1,'armnn']]],
  ['qsymm16decoder_6237',['QSymm16Decoder',['../classarmnn_1_1_q_symm16_decoder.html',1,'armnn']]],
  ['qsymm16encoder_6238',['QSymm16Encoder',['../classarmnn_1_1_q_symm16_encoder.html',1,'armnn']]],
  ['qsymm16peraxisencoder_6239',['QSymm16PerAxisEncoder',['../classarmnn_1_1_q_symm16_per_axis_encoder.html',1,'armnn']]],
  ['qsymm8peraxisdecoder_6240',['QSymm8PerAxisDecoder',['../classarmnn_1_1_q_symm8_per_axis_decoder.html',1,'armnn']]],
  ['qsymm8peraxisencoder_6241',['QSymm8PerAxisEncoder',['../classarmnn_1_1_q_symm8_per_axis_encoder.html',1,'armnn']]],
  ['qsymms8decoder_6242',['QSymmS8Decoder',['../classarmnn_1_1_q_symm_s8_decoder.html',1,'armnn']]],
  ['qsymms8encoder_6243',['QSymmS8Encoder',['../classarmnn_1_1_q_symm_s8_encoder.html',1,'armnn']]],
  ['quantizationparametersareequal_6244',['QuantizationParametersAreEqual',['../structarmnn_1_1_quantization_parameters_are_equal.html',1,'armnn']]],
  ['quantizedlstminputparams_6245',['QuantizedLstmInputParams',['../structarmnn_1_1_quantized_lstm_input_params.html',1,'armnn']]],
  ['quantizedlstminputparamsinfo_6246',['QuantizedLstmInputParamsInfo',['../structarmnn_1_1_quantized_lstm_input_params_info.html',1,'armnn']]],
  ['quantizedlstmlayer_6247',['QuantizedLstmLayer',['../classarmnn_1_1_quantized_lstm_layer.html',1,'armnn']]],
  ['quantizedlstmparameters_6248',['QuantizedLstmParameters',['../structarmnn_1_1_quantized_lstm_parameters.html',1,'armnn']]],
  ['quantizedlstmqueuedescriptor_6249',['QuantizedLstmQueueDescriptor',['../structarmnn_1_1_quantized_lstm_queue_descriptor.html',1,'armnn']]],
  ['quantizedmultipliersmallerthanone_6250',['QuantizedMultiplierSmallerThanOne',['../structarmnn_1_1_quantized_multiplier_smaller_than_one.html',1,'armnn']]],
  ['quantizelayer_6251',['QuantizeLayer',['../classarmnn_1_1_quantize_layer.html',1,'armnn']]],
  ['quantizequeuedescriptor_6252',['QuantizeQueueDescriptor',['../structarmnn_1_1_quantize_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptor_6253',['QueueDescriptor',['../structarmnn_1_1_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptorwithparameters_6254',['QueueDescriptorWithParameters',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20activationdescriptor_20_3e_6255',['QueueDescriptorWithParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20argminmaxdescriptor_20_3e_6256',['QueueDescriptorWithParameters&lt; ArgMinMaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchmatmuldescriptor_20_3e_6257',['QueueDescriptorWithParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchnormalizationdescriptor_20_3e_6258',['QueueDescriptorWithParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchtospacenddescriptor_20_3e_6259',['QueueDescriptorWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20broadcasttodescriptor_20_3e_6260',['QueueDescriptorWithParameters&lt; BroadcastToDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20channelshuffledescriptor_20_3e_6261',['QueueDescriptorWithParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20comparisondescriptor_20_3e_6262',['QueueDescriptorWithParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution2ddescriptor_20_3e_6263',['QueueDescriptorWithParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution3ddescriptor_20_3e_6264',['QueueDescriptorWithParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthtospacedescriptor_20_3e_6265',['QueueDescriptorWithParameters&lt; DepthToSpaceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_6266',['QueueDescriptorWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20detectionpostprocessdescriptor_20_3e_6267',['QueueDescriptorWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwisebinarydescriptor_20_3e_6268',['QueueDescriptorWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwiseunarydescriptor_20_3e_6269',['QueueDescriptorWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fakequantizationdescriptor_20_3e_6270',['QueueDescriptorWithParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20filldescriptor_20_3e_6271',['QueueDescriptorWithParameters&lt; FillDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fullyconnecteddescriptor_20_3e_6272',['QueueDescriptorWithParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fuseddescriptor_20_3e_6273',['QueueDescriptorWithParameters&lt; FusedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20gatherdescriptor_20_3e_6274',['QueueDescriptorWithParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20instancenormalizationdescriptor_20_3e_6275',['QueueDescriptorWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20l2normalizationdescriptor_20_3e_6276',['QueueDescriptorWithParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logicalbinarydescriptor_20_3e_6277',['QueueDescriptorWithParameters&lt; LogicalBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logsoftmaxdescriptor_20_3e_6278',['QueueDescriptorWithParameters&lt; LogSoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20lstmdescriptor_20_3e_6279',['QueueDescriptorWithParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20meandescriptor_20_3e_6280',['QueueDescriptorWithParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20normalizationdescriptor_20_3e_6281',['QueueDescriptorWithParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20originsdescriptor_20_3e_6282',['QueueDescriptorWithParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20paddescriptor_20_3e_6283',['QueueDescriptorWithParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20permutedescriptor_20_3e_6284',['QueueDescriptorWithParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling2ddescriptor_20_3e_6285',['QueueDescriptorWithParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling3ddescriptor_20_3e_6286',['QueueDescriptorWithParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20precompileddescriptor_20_3e_6287',['QueueDescriptorWithParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20qlstmdescriptor_20_3e_6288',['QueueDescriptorWithParameters&lt; QLstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reducedescriptor_20_3e_6289',['QueueDescriptorWithParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reshapedescriptor_20_3e_6290',['QueueDescriptorWithParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20resizedescriptor_20_3e_6291',['QueueDescriptorWithParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20scatternddescriptor_20_3e_6292',['QueueDescriptorWithParameters&lt; ScatterNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20slicedescriptor_20_3e_6293',['QueueDescriptorWithParameters&lt; SliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20softmaxdescriptor_20_3e_6294',['QueueDescriptorWithParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetobatchnddescriptor_20_3e_6295',['QueueDescriptorWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetodepthdescriptor_20_3e_6296',['QueueDescriptorWithParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stackdescriptor_20_3e_6297',['QueueDescriptorWithParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stridedslicedescriptor_20_3e_6298',['QueueDescriptorWithParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20tiledescriptor_20_3e_6299',['QueueDescriptorWithParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_6300',['QueueDescriptorWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposedescriptor_20_3e_6301',['QueueDescriptorWithParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20viewsdescriptor_20_3e_6302',['QueueDescriptorWithParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]]
];
