var searchData=
[
  ['backendcapabilityexception_5299',['BackendCapabilityException',['../classarmnn_1_1_backend_capability_exception.html',1,'armnn']]],
  ['backendid_5300',['BackendId',['../classarmnn_1_1_backend_id.html',1,'armnn']]],
  ['backendoption_5301',['BackendOption',['../structarmnn_1_1_backend_options_1_1_backend_option.html',1,'armnn::BackendOptions']]],
  ['backendoptions_5302',['BackendOptions',['../structarmnn_1_1_backend_options.html',1,'armnn']]],
  ['backendregistry_5303',['BackendRegistry',['../classarmnn_1_1_backend_registry.html',1,'armnn']]],
  ['backendsettings_5304',['BackendSettings',['../structarmnn_1_1_backend_settings.html',1,'armnn']]],
  ['backendunavailableexception_5305',['BackendUnavailableException',['../classarmnn_1_1_backend_unavailable_exception.html',1,'armnn']]],
  ['backendversion_5306',['BackendVersion',['../structarmnn_1_1_backend_version.html',1,'armnn']]],
  ['badoptionalaccessexception_5307',['BadOptionalAccessException',['../classarmnn_1_1_bad_optional_access_exception.html',1,'armnn']]],
  ['basedescriptor_5308',['BaseDescriptor',['../structarmnn_1_1_base_descriptor.html',1,'armnn']]],
  ['baseiterator_5309',['BaseIterator',['../classarmnn_1_1_base_iterator.html',1,'armnn']]],
  ['basememorymanager_5310',['BaseMemoryManager',['../classarmnn_1_1_base_memory_manager.html',1,'armnn']]],
  ['basetensor_5311',['BaseTensor',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20const_20void_20_2a_20_3e_5312',['BaseTensor&lt; const void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20void_20_2a_20_3e_5313',['BaseTensor&lt; void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['baseworkload_5314',['BaseWorkload',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20absqueuedescriptor_20_3e_5315',['BaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20activationqueuedescriptor_20_3e_5316',['BaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20additionqueuedescriptor_20_3e_5317',['BaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20argminmaxqueuedescriptor_20_3e_5318',['BaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20armnn_3a_3aadditionqueuedescriptor_20_3e_5319',['BaseWorkload&lt; armnn::AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5320',['BaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5321',['BaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5322',['BaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20broadcasttoqueuedescriptor_20_3e_5323',['BaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20castqueuedescriptor_20_3e_5324',['BaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20channelshufflequeuedescriptor_20_3e_5325',['BaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20comparisonqueuedescriptor_20_3e_5326',['BaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20concatqueuedescriptor_20_3e_5327',['BaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20constantqueuedescriptor_20_3e_5328',['BaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution2dqueuedescriptor_20_3e_5329',['BaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution3dqueuedescriptor_20_3e_5330',['BaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20debugqueuedescriptor_20_3e_5331',['BaseWorkload&lt; DebugQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthtospacequeuedescriptor_20_3e_5332',['BaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5333',['BaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20dequantizequeuedescriptor_20_3e_5334',['BaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5335',['BaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20divisionqueuedescriptor_20_3e_5336',['BaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5337',['BaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5338',['BaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fillqueuedescriptor_20_3e_5339',['BaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20floorqueuedescriptor_20_3e_5340',['BaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5341',['BaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fusedqueuedescriptor_20_3e_5342',['BaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherndqueuedescriptor_20_3e_5343',['BaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherqueuedescriptor_20_3e_5344',['BaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5345',['BaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5346',['BaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5347',['BaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5348',['BaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20lstmqueuedescriptor_20_3e_5349',['BaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20mapqueuedescriptor_20_3e_5350',['BaseWorkload&lt; MapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20maximumqueuedescriptor_20_3e_5351',['BaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20meanqueuedescriptor_20_3e_5352',['BaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memcopyqueuedescriptor_20_3e_5353',['BaseWorkload&lt; MemCopyQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memimportqueuedescriptor_20_3e_5354',['BaseWorkload&lt; MemImportQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memsyncqueuedescriptor_20_3e_5355',['BaseWorkload&lt; MemSyncQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20minimumqueuedescriptor_20_3e_5356',['BaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20multiplicationqueuedescriptor_20_3e_5357',['BaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20normalizationqueuedescriptor_20_3e_5358',['BaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20padqueuedescriptor_20_3e_5359',['BaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20parentdescriptor_20_3e_5360',['BaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20permutequeuedescriptor_20_3e_5361',['BaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling2dqueuedescriptor_20_3e_5362',['BaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling3dqueuedescriptor_20_3e_5363',['BaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20precompiledqueuedescriptor_20_3e_5364',['BaseWorkload&lt; PreCompiledQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20preluqueuedescriptor_20_3e_5365',['BaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20qlstmqueuedescriptor_20_3e_5366',['BaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5367',['BaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizequeuedescriptor_20_3e_5368',['BaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rankqueuedescriptor_20_3e_5369',['BaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reducequeuedescriptor_20_3e_5370',['BaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reshapequeuedescriptor_20_3e_5371',['BaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20resizequeuedescriptor_20_3e_5372',['BaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reversev2queuedescriptor_20_3e_5373',['BaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rsqrtqueuedescriptor_20_3e_5374',['BaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20scatterndqueuedescriptor_20_3e_5375',['BaseWorkload&lt; ScatterNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20shapequeuedescriptor_20_3e_5376',['BaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20slicequeuedescriptor_20_3e_5377',['BaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20softmaxqueuedescriptor_20_3e_5378',['BaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5379',['BaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5380',['BaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20splitterqueuedescriptor_20_3e_5381',['BaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stackqueuedescriptor_20_3e_5382',['BaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stridedslicequeuedescriptor_20_3e_5383',['BaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20subtractionqueuedescriptor_20_3e_5384',['BaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20tilequeuedescriptor_20_3e_5385',['BaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5386',['BaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposequeuedescriptor_20_3e_5387',['BaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5388',['BaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unmapqueuedescriptor_20_3e_5389',['BaseWorkload&lt; UnmapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['batchmatmul_5390',['BatchMatMul',['../classarmnn_1_1_batch_mat_mul.html',1,'armnn']]],
  ['batchmatmuldescriptor_5391',['BatchMatMulDescriptor',['../structarmnn_1_1_batch_mat_mul_descriptor.html',1,'armnn']]],
  ['batchmatmullayer_5392',['BatchMatMulLayer',['../classarmnn_1_1_batch_mat_mul_layer.html',1,'armnn']]],
  ['batchmatmulqueuedescriptor_5393',['BatchMatMulQueueDescriptor',['../structarmnn_1_1_batch_mat_mul_queue_descriptor.html',1,'armnn']]],
  ['batchnormalizationdescriptor_5394',['BatchNormalizationDescriptor',['../structarmnn_1_1_batch_normalization_descriptor.html',1,'armnn']]],
  ['batchnormalizationlayer_5395',['BatchNormalizationLayer',['../classarmnn_1_1_batch_normalization_layer.html',1,'armnn']]],
  ['batchnormalizationqueuedescriptor_5396',['BatchNormalizationQueueDescriptor',['../structarmnn_1_1_batch_normalization_queue_descriptor.html',1,'armnn']]],
  ['batchtospacenddescriptor_5397',['BatchToSpaceNdDescriptor',['../structarmnn_1_1_batch_to_space_nd_descriptor.html',1,'armnn']]],
  ['batchtospacendlayer_5398',['BatchToSpaceNdLayer',['../classarmnn_1_1_batch_to_space_nd_layer.html',1,'armnn']]],
  ['batchtospacendqueuedescriptor_5399',['BatchToSpaceNdQueueDescriptor',['../structarmnn_1_1_batch_to_space_nd_queue_descriptor.html',1,'armnn']]],
  ['bfloat16_5400',['BFloat16',['../classarmnn_1_1_b_float16.html',1,'armnn']]],
  ['biasandweightstypescompatible_5401',['BiasAndWeightsTypesCompatible',['../structarmnn_1_1_bias_and_weights_types_compatible.html',1,'armnn']]],
  ['biasandweightstypesmatch_5402',['BiasAndWeightsTypesMatch',['../structarmnn_1_1_bias_and_weights_types_match.html',1,'armnn']]],
  ['bindablelayer_5403',['BindableLayer',['../classarmnn_1_1_bindable_layer.html',1,'armnn']]],
  ['bindingpointinfo_5404',['BindingPointInfo',['../structarmnn_deserializer_1_1_binding_point_info.html',1,'armnnDeserializer']]],
  ['booleandecoder_5405',['BooleanDecoder',['../classarmnn_1_1_boolean_decoder.html',1,'armnn']]],
  ['booleandecoderbool_5406',['BooleanDecoderBool',['../classarmnn_1_1_boolean_decoder_bool.html',1,'armnn']]],
  ['booleanencoder_5407',['BooleanEncoder',['../classarmnn_1_1_boolean_encoder.html',1,'armnn']]],
  ['broadcastloop_5408',['BroadcastLoop',['../structarmnn_1_1_broadcast_loop.html',1,'armnn']]],
  ['broadcasttodescriptor_5409',['BroadcastToDescriptor',['../structarmnn_1_1_broadcast_to_descriptor.html',1,'armnn']]],
  ['broadcasttolayer_5410',['BroadcastToLayer',['../classarmnn_1_1_broadcast_to_layer.html',1,'armnn']]],
  ['broadcasttoqueuedescriptor_5411',['BroadcastToQueueDescriptor',['../structarmnn_1_1_broadcast_to_queue_descriptor.html',1,'armnn']]],
  ['bufferstorage_5412',['BufferStorage',['../structarmnn_1_1_buffer_storage.html',1,'armnn']]]
];
