var searchData=
[
  ['l2normalizationdescriptor',['L2NormalizationDescriptor',['../structarmnn_1_1_l2_normalization_descriptor.xhtml',1,'armnn']]],
  ['l2normalizationlayer',['L2NormalizationLayer',['../classarmnn_1_1_l2_normalization_layer.xhtml',1,'armnn']]],
  ['l2normalizationqueuedescriptor',['L2NormalizationQueueDescriptor',['../structarmnn_1_1_l2_normalization_queue_descriptor.xhtml',1,'armnn']]],
  ['labelsandeventclasses',['LabelsAndEventClasses',['../classarmnn_1_1profiling_1_1_labels_and_event_classes.xhtml',1,'armnn::profiling']]],
  ['layer',['Layer',['../classarmnn_1_1_layer.xhtml',1,'armnn']]],
  ['layeringraph_3c_20inputlayer_20_3e',['LayerInGraph&lt; InputLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_input_layer_01_4.xhtml',1,'armnn::Graph']]],
  ['layeringraph_3c_20outputlayer_20_3e',['LayerInGraph&lt; OutputLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_output_layer_01_4.xhtml',1,'armnn::Graph']]],
  ['layersupportbase',['LayerSupportBase',['../classarmnn_1_1_layer_support_base.xhtml',1,'armnn']]],
  ['layertestresult',['LayerTestResult',['../struct_layer_test_result.xhtml',1,'']]],
  ['layertypeofimpl',['LayerTypeOfImpl',['../structarmnn_1_1_layer_type_of_impl.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aactivation_20_3e',['LayerTypeOfImpl&lt; LayerType::Activation &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_activation_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aaddition_20_3e',['LayerTypeOfImpl&lt; LayerType::Addition &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_addition_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aargminmax_20_3e',['LayerTypeOfImpl&lt; LayerType::ArgMinMax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_arg_min_max_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchnormalization_20_3e',['LayerTypeOfImpl&lt; LayerType::BatchNormalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_normalization_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchtospacend_20_3e',['LayerTypeOfImpl&lt; LayerType::BatchToSpaceNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_to_space_nd_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3acomparison_20_3e',['LayerTypeOfImpl&lt; LayerType::Comparison &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_comparison_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconcat_20_3e',['LayerTypeOfImpl&lt; LayerType::Concat &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_concat_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconstant_20_3e',['LayerTypeOfImpl&lt; LayerType::Constant &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_constant_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertbf16tofp32_20_3e',['LayerTypeOfImpl&lt; LayerType::ConvertBf16ToFp32 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_bf16_to_fp32_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp16tofp32_20_3e',['LayerTypeOfImpl&lt; LayerType::ConvertFp16ToFp32 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp16_to_fp32_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp32tobf16_20_3e',['LayerTypeOfImpl&lt; LayerType::ConvertFp32ToBf16 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp32_to_bf16_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp32tofp16_20_3e',['LayerTypeOfImpl&lt; LayerType::ConvertFp32ToFp16 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp32_to_fp16_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvolution2d_20_3e',['LayerTypeOfImpl&lt; LayerType::Convolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convolution2d_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adebug_20_3e',['LayerTypeOfImpl&lt; LayerType::Debug &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_debug_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adepthtospace_20_3e',['LayerTypeOfImpl&lt; LayerType::DepthToSpace &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_depth_to_space_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adepthwiseconvolution2d_20_3e',['LayerTypeOfImpl&lt; LayerType::DepthwiseConvolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_depthwise_convolution2d_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adequantize_20_3e',['LayerTypeOfImpl&lt; LayerType::Dequantize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_dequantize_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adetectionpostprocess_20_3e',['LayerTypeOfImpl&lt; LayerType::DetectionPostProcess &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_detection_post_process_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adivision_20_3e',['LayerTypeOfImpl&lt; LayerType::Division &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_division_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aelementwiseunary_20_3e',['LayerTypeOfImpl&lt; LayerType::ElementwiseUnary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_elementwise_unary_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afakequantization_20_3e',['LayerTypeOfImpl&lt; LayerType::FakeQuantization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fake_quantization_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afill_20_3e',['LayerTypeOfImpl&lt; LayerType::Fill &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fill_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afloor_20_3e',['LayerTypeOfImpl&lt; LayerType::Floor &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_floor_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afullyconnected_20_3e',['LayerTypeOfImpl&lt; LayerType::FullyConnected &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fully_connected_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3agather_20_3e',['LayerTypeOfImpl&lt; LayerType::Gather &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_gather_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ainput_20_3e',['LayerTypeOfImpl&lt; LayerType::Input &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_input_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ainstancenormalization_20_3e',['LayerTypeOfImpl&lt; LayerType::InstanceNormalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_instance_normalization_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3al2normalization_20_3e',['LayerTypeOfImpl&lt; LayerType::L2Normalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_l2_normalization_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alogsoftmax_20_3e',['LayerTypeOfImpl&lt; LayerType::LogSoftmax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_log_softmax_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alstm_20_3e',['LayerTypeOfImpl&lt; LayerType::Lstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_lstm_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amaximum_20_3e',['LayerTypeOfImpl&lt; LayerType::Maximum &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_maximum_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amean_20_3e',['LayerTypeOfImpl&lt; LayerType::Mean &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mean_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amemcopy_20_3e',['LayerTypeOfImpl&lt; LayerType::MemCopy &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mem_copy_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amemimport_20_3e',['LayerTypeOfImpl&lt; LayerType::MemImport &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mem_import_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amerge_20_3e',['LayerTypeOfImpl&lt; LayerType::Merge &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_merge_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aminimum_20_3e',['LayerTypeOfImpl&lt; LayerType::Minimum &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_minimum_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amultiplication_20_3e',['LayerTypeOfImpl&lt; LayerType::Multiplication &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_multiplication_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3anormalization_20_3e',['LayerTypeOfImpl&lt; LayerType::Normalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_normalization_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aoutput_20_3e',['LayerTypeOfImpl&lt; LayerType::Output &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_output_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apad_20_3e',['LayerTypeOfImpl&lt; LayerType::Pad &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pad_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apermute_20_3e',['LayerTypeOfImpl&lt; LayerType::Permute &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_permute_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apooling2d_20_3e',['LayerTypeOfImpl&lt; LayerType::Pooling2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pooling2d_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aprecompiled_20_3e',['LayerTypeOfImpl&lt; LayerType::PreCompiled &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pre_compiled_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aprelu_20_3e',['LayerTypeOfImpl&lt; LayerType::Prelu &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_prelu_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aqlstm_20_3e',['LayerTypeOfImpl&lt; LayerType::QLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_q_lstm_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aquantize_20_3e',['LayerTypeOfImpl&lt; LayerType::Quantize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_quantize_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aquantizedlstm_20_3e',['LayerTypeOfImpl&lt; LayerType::QuantizedLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_quantized_lstm_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3arank_20_3e',['LayerTypeOfImpl&lt; LayerType::Rank &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_rank_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areshape_20_3e',['LayerTypeOfImpl&lt; LayerType::Reshape &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reshape_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aresize_20_3e',['LayerTypeOfImpl&lt; LayerType::Resize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_resize_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aslice_20_3e',['LayerTypeOfImpl&lt; LayerType::Slice &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_slice_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asoftmax_20_3e',['LayerTypeOfImpl&lt; LayerType::Softmax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_softmax_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aspacetobatchnd_20_3e',['LayerTypeOfImpl&lt; LayerType::SpaceToBatchNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_space_to_batch_nd_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aspacetodepth_20_3e',['LayerTypeOfImpl&lt; LayerType::SpaceToDepth &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_space_to_depth_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asplitter_20_3e',['LayerTypeOfImpl&lt; LayerType::Splitter &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_splitter_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astack_20_3e',['LayerTypeOfImpl&lt; LayerType::Stack &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_stack_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astandin_20_3e',['LayerTypeOfImpl&lt; LayerType::StandIn &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_stand_in_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astridedslice_20_3e',['LayerTypeOfImpl&lt; LayerType::StridedSlice &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_strided_slice_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asubtraction_20_3e',['LayerTypeOfImpl&lt; LayerType::Subtraction &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_subtraction_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aswitch_20_3e',['LayerTypeOfImpl&lt; LayerType::Switch &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_switch_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atranspose_20_3e',['LayerTypeOfImpl&lt; LayerType::Transpose &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_transpose_01_4.xhtml',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atransposeconvolution2d_20_3e',['LayerTypeOfImpl&lt; LayerType::TransposeConvolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_transpose_convolution2d_01_4.xhtml',1,'armnn']]],
  ['layervalidationexception',['LayerValidationException',['../classarmnn_1_1_layer_validation_exception.xhtml',1,'armnn']]],
  ['layervisitorbase',['LayerVisitorBase',['../classarmnn_1_1_layer_visitor_base.xhtml',1,'armnn']]],
  ['layervisitorbase_3c_20armnn_3a_3avisitornothrowpolicy_20_3e',['LayerVisitorBase&lt; armnn::VisitorNoThrowPolicy &gt;',['../classarmnn_1_1_layer_visitor_base.xhtml',1,'armnn']]],
  ['layervisitorbase_3c_20visitornothrowpolicy_20_3e',['LayerVisitorBase&lt; VisitorNoThrowPolicy &gt;',['../classarmnn_1_1_layer_visitor_base.xhtml',1,'armnn']]],
  ['layervisitorbase_3c_20visitorthrowingpolicy_20_3e',['LayerVisitorBase&lt; VisitorThrowingPolicy &gt;',['../classarmnn_1_1_layer_visitor_base.xhtml',1,'armnn']]],
  ['layerwithparameters',['LayerWithParameters',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20activationdescriptor_20_3e',['LayerWithParameters&lt; ActivationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20argminmaxdescriptor_20_3e',['LayerWithParameters&lt; ArgMinMaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20batchnormalizationdescriptor_20_3e',['LayerWithParameters&lt; BatchNormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20batchtospacenddescriptor_20_3e',['LayerWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20comparisondescriptor_20_3e',['LayerWithParameters&lt; ComparisonDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20convolution2ddescriptor_20_3e',['LayerWithParameters&lt; Convolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20depthtospacedescriptor_20_3e',['LayerWithParameters&lt; DepthToSpaceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e',['LayerWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20detectionpostprocessdescriptor_20_3e',['LayerWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20elementwiseunarydescriptor_20_3e',['LayerWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20fakequantizationdescriptor_20_3e',['LayerWithParameters&lt; FakeQuantizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20filldescriptor_20_3e',['LayerWithParameters&lt; FillDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20fullyconnecteddescriptor_20_3e',['LayerWithParameters&lt; FullyConnectedDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20gatherdescriptor_20_3e',['LayerWithParameters&lt; GatherDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20instancenormalizationdescriptor_20_3e',['LayerWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20l2normalizationdescriptor_20_3e',['LayerWithParameters&lt; L2NormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20logsoftmaxdescriptor_20_3e',['LayerWithParameters&lt; LogSoftmaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20lstmdescriptor_20_3e',['LayerWithParameters&lt; LstmDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20meandescriptor_20_3e',['LayerWithParameters&lt; MeanDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20normalizationdescriptor_20_3e',['LayerWithParameters&lt; NormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20originsdescriptor_20_3e',['LayerWithParameters&lt; OriginsDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20paddescriptor_20_3e',['LayerWithParameters&lt; PadDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20permutedescriptor_20_3e',['LayerWithParameters&lt; PermuteDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20pooling2ddescriptor_20_3e',['LayerWithParameters&lt; Pooling2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20precompileddescriptor_20_3e',['LayerWithParameters&lt; PreCompiledDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20qlstmdescriptor_20_3e',['LayerWithParameters&lt; QLstmDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20reshapedescriptor_20_3e',['LayerWithParameters&lt; ReshapeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20resizedescriptor_20_3e',['LayerWithParameters&lt; ResizeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20slicedescriptor_20_3e',['LayerWithParameters&lt; SliceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20softmaxdescriptor_20_3e',['LayerWithParameters&lt; SoftmaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20spacetobatchnddescriptor_20_3e',['LayerWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20spacetodepthdescriptor_20_3e',['LayerWithParameters&lt; SpaceToDepthDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20stackdescriptor_20_3e',['LayerWithParameters&lt; StackDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20standindescriptor_20_3e',['LayerWithParameters&lt; StandInDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20stridedslicedescriptor_20_3e',['LayerWithParameters&lt; StridedSliceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20transposeconvolution2ddescriptor_20_3e',['LayerWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20transposedescriptor_20_3e',['LayerWithParameters&lt; TransposeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['layerwithparameters_3c_20viewsdescriptor_20_3e',['LayerWithParameters&lt; ViewsDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.xhtml',1,'armnn']]],
  ['loadednetwork',['LoadedNetwork',['../classarmnn_1_1_loaded_network.xhtml',1,'armnn']]],
  ['loglevelswapper',['LogLevelSwapper',['../structarmnn_1_1profiling_1_1_log_level_swapper.xhtml',1,'armnn::profiling']]],
  ['logsink',['LogSink',['../classarmnn_1_1_log_sink.xhtml',1,'armnn']]],
  ['logsoftmaxlayer',['LogSoftmaxLayer',['../classarmnn_1_1_log_softmax_layer.xhtml',1,'armnn']]],
  ['logsoftmaxqueuedescriptor',['LogSoftmaxQueueDescriptor',['../structarmnn_1_1_log_softmax_queue_descriptor.xhtml',1,'armnn']]],
  ['lstmbasicparameters',['LstmBasicParameters',['../structarmnn_1_1_lstm_basic_parameters.xhtml',1,'armnn']]],
  ['lstmdescriptor',['LstmDescriptor',['../structarmnn_1_1_lstm_descriptor.xhtml',1,'armnn']]],
  ['lstminputparams',['LstmInputParams',['../structarmnn_1_1_lstm_input_params.xhtml',1,'armnn']]],
  ['lstminputparamsinfo',['LstmInputParamsInfo',['../structarmnn_1_1_lstm_input_params_info.xhtml',1,'armnn']]],
  ['lstmlayer',['LstmLayer',['../classarmnn_1_1_lstm_layer.xhtml',1,'armnn']]],
  ['lstmoptcifgparameters',['LstmOptCifgParameters',['../structarmnn_1_1_lstm_opt_cifg_parameters.xhtml',1,'armnn']]],
  ['lstmoptlayernormparameters',['LstmOptLayerNormParameters',['../structarmnn_1_1_lstm_opt_layer_norm_parameters.xhtml',1,'armnn']]],
  ['lstmoptpeepholeparameters',['LstmOptPeepholeParameters',['../structarmnn_1_1_lstm_opt_peephole_parameters.xhtml',1,'armnn']]],
  ['lstmoptprojectionparameters',['LstmOptProjectionParameters',['../structarmnn_1_1_lstm_opt_projection_parameters.xhtml',1,'armnn']]],
  ['lstmqueuedescriptor',['LstmQueueDescriptor',['../structarmnn_1_1_lstm_queue_descriptor.xhtml',1,'armnn']]]
];
