ArmNN: ClTransposeConvolution2dWorkload Class Reference
ClTransposeConvolution2dWorkload Class Reference
#include <ClTransposeConvolution2dWorkload.hpp>
Public Member Functions
ClTransposeConvolution2dWorkload (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > &memoryManager, const arm_compute::CLCompileContext &clCompileContext)
void Execute () const override
Public Member Functions inherited from ClBaseWorkload< TransposeConvolution2dQueueDescriptor >
ClBaseWorkload (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< TransposeConvolution2dQueueDescriptor >
BaseWorkload (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const TransposeConvolution2dQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Member Functions inherited from ClBaseWorkload< TransposeConvolution2dQueueDescriptor >
virtual void Reconfigure ()
Protected Attributes inherited from BaseWorkload< TransposeConvolution2dQueueDescriptor >
TransposeConvolution2dQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 27 of file ClTransposeConvolution2dWorkload.hpp.
Constructor & Destructor Documentation
ClTransposeConvolution2dWorkload()
ClTransposeConvolution2dWorkload (const TransposeConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info, std::shared_ptr< arm_compute::MemoryManagerOnDemand > & memoryManager, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 56 of file ClTransposeConvolution2dWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, ConstTensorHandle::GetTensorInfo(), TransposeConvolution2dQueueDescriptor::m_Bias, TransposeConvolution2dDescriptor::m_BiasEnabled, WorkloadInfo::m_BiasTensorInfo, BaseWorkload< TransposeConvolution2dQueueDescriptor >::m_Data, WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, TransposeConvolution2dQueueDescriptor::m_Weight, and WorkloadInfo::m_WeightsTensorInfo.
     : ClBaseWorkload<TransposeConvolution2dQueueDescriptor>(descriptor, info)
     , m_Layer(memoryManager)
 {
     // Add details for profiling output
     WorkloadInfo detailsInfo;
     detailsInfo.m_InputTensorInfos = info.m_InputTensorInfos;
     detailsInfo.m_OutputTensorInfos = info.m_OutputTensorInfos;
     detailsInfo.m_WeightsTensorInfo = armnn::Optional<armnn::TensorInfo>(descriptor.m_Weight->GetTensorInfo());
     if (descriptor.m_Parameters.m_BiasEnabled)
     {
         detailsInfo.m_BiasTensorInfo = armnn::Optional<armnn::TensorInfo>(descriptor.m_Bias->GetTensorInfo());
     }
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("ClTransposeConvolution2dWorkload_Construct",
                                          descriptor.m_Parameters,
                                          detailsInfo,
                                          this->GetGuid());
     const TensorInfo& weightInfo = m_Data.m_Weight->GetTensorInfo();
     m_WeightsTensor = std::make_unique<arm_compute::CLTensor>();
     BuildArmComputeTensor(*m_WeightsTensor, weightInfo, m_Data.m_Parameters.m_DataLayout);
     if (m_Data.m_Parameters.m_BiasEnabled)
     {
         m_BiasesTensor = std::make_unique<arm_compute::CLTensor>();
         BuildArmComputeTensor(*m_BiasesTensor, m_Data.m_Bias->GetTensorInfo(), m_Data.m_Parameters.m_DataLayout);
     }
     m_Data.ValidateInputsOutputs("ClTransposeConvolution2dWorkload", 1, 1);
     arm_compute::ICLTensor& input  = static_cast<IClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = static_cast<IClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
     input.info()->set_data_layout(aclDataLayout);
     output.info()->set_data_layout(aclDataLayout);
     arm_compute::PadStrideInfo padStrideInfo = BuildArmComputePadStrideInfo(m_Data.m_Parameters);
     {
         ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClTransposeConvolution2dWorkload_configure");
         m_Layer.configure(clCompileContext, &input, m_WeightsTensor.get(), m_BiasesTensor.get(), &output,
                           padStrideInfo);
     }
     InitializeArmComputeClTensorData(*m_WeightsTensor, m_Data.m_Weight);
     if (m_BiasesTensor)
     {
         InitializeArmComputeClTensorData(*m_BiasesTensor, m_Data.m_Bias);
     }
     m_Layer.prepare();
     FreeUnusedTensors();
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 120 of file ClTransposeConvolution2dWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< TransposeConvolution2dQueueDescriptor >::GetGuid(), and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClTransposeConvolution2dWorkload_Execute", this->GetGuid());
     RunClFunction(m_Layer, CHECK_LOCATION());
 }
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClTransposeConvolution2dWorkload.hpp
src/backends/cl/workloads/ClTransposeConvolution2dWorkload.cpp