ArmNN: Int32Decoder Class Reference
Int32Decoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
Int32Decoder (const int32_t *data)
Int32Decoder ()
float Get () const override
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const bool isDepthwise) override
Public Member Functions inherited from TypedIterator< const int32_t, Decoder< float > >
TypedIterator (const int32_t *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< const int32_t, Decoder< float > >
const int32_t * m_Iterator
const int32_t * m_Start
Detailed Description
Definition at line 364 of file BaseIterator.hpp.
Constructor & Destructor Documentation
Int32Decoder() [1/2]
Int32Decoder (const int32_t * data) inline
Definition at line 367 of file BaseIterator.hpp.
         : TypedIterator(data) {}
Int32Decoder() [2/2]
Int32Decoder () inline
Definition at line 370 of file BaseIterator.hpp.
         : Int32Decoder(nullptr) {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, const bool isDepthwise) inline override virtual
Implements Decoder< float >.
Definition at line 377 of file BaseIterator.hpp.
References TensorShape::GetNumElements(), armnn::IgnoreUnused(), and BaseIterator::operator[]().
     {
         IgnoreUnused(isDepthwise);
         const unsigned int size = tensorShape.GetNumElements();
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         for (uint32_t i = 0; i < size; ++i)
         {
             this->operator[](i);
             decodedTensor.emplace_back(static_cast<float>(*m_Iterator));
         }
         return decodedTensor;
     }
Get()
float Get () const inline override virtual
Implements Decoder< float >.
Definition at line 373 of file BaseIterator.hpp.
     {
         return static_cast<float>(*m_Iterator);
     }
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp