ArmNN: TfLiteParserImpl Class Reference
TfLiteParserImpl Class Reference
#include <TfLiteParser.hpp>
Public Types
using ModelPtr = std::unique_ptr< tflite::ModelT >
using SubgraphPtr = std::unique_ptr< tflite::SubGraphT >
using OperatorPtr = std::unique_ptr< tflite::OperatorT >
using OperatorCodePtr = std::unique_ptr< tflite::OperatorCodeT >
using TensorPtr = std::unique_ptr< tflite::TensorT >
using TensorRawPtr = const tflite::TensorT *
using TensorRawPtrVector = std::vector< TensorRawPtr >
using TensorIdRawPtr = std::pair< size_t, TensorRawPtr >
using TensorIdRawPtrVector = std::vector< TensorIdRawPtr >
using BufferPtr = std::unique_ptr< tflite::BufferT >
using BufferRawPtr = const tflite::BufferT *
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile)
Create the network from a flatbuffers binary file on disk.
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent)
Create the network from a flatbuffers binary.
BindingPointInfo GetNetworkInputBindingInfo (size_t subgraphId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and subgraph id.
BindingPointInfo GetNetworkOutputBindingInfo (size_t subgraphId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and subgraph id.
size_t GetSubgraphCount () const
Return the number of subgraphs in the parsed model.
std::vector< std::string > GetSubgraphInputTensorNames (size_t subgraphId) const
Return the input tensor names for a given subgraph.
std::vector< std::string > GetSubgraphOutputTensorNames (size_t subgraphId) const
Return the output tensor names for a given subgraph.
TfLiteParserImpl (const armnn::Optional< ITfLiteParser::TfLiteParserOptions > &options=armnn::EmptyOptional())
~TfLiteParserImpl ()=default
armnn::INetworkPtr CreateNetworkFromBinaryAsDynamic (const std::vector< uint8_t > &binaryContent)
armnn::INetworkPtr LoadModel (std::unique_ptr< tflite::ModelT > model)
Static Public Member Functions
static ModelPtr LoadModelFromFile (const char *fileName)
static ModelPtr LoadModelFromBinary (const uint8_t *binaryContent, size_t len)
static TensorRawPtrVector GetInputs (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static TensorRawPtrVector GetOutputs (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static TensorIdRawPtrVector GetSubgraphInputs (const ModelPtr &model, size_t subgraphIndex)
static TensorIdRawPtrVector GetSubgraphOutputs (const ModelPtr &model, size_t subgraphIndex)
static std::vector< int32_t > & GetInputTensorIds (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static std::vector< int32_t > & GetOutputTensorIds (const ModelPtr &model, size_t subgraphIndex, size_t operatorIndex)
static BufferRawPtr GetBuffer (const ModelPtr &model, size_t bufferIndex)
static armnn::TensorInfo OutputShapeOfSqueeze (std::vector< uint32_t > squeezeDims, const armnn::TensorInfo &inputTensorInfo)
static armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo &inputTensorInfo, const std::vector< int32_t > &targetDimsIn)
static const std::string GetVersion ()
Retrieve version in X.Y.Z form.
Detailed Description
Definition at line 26 of file TfLiteParser.hpp.
Member Typedef Documentation
BufferPtr
using BufferPtr = std::unique_ptr<tflite::BufferT>
Definition at line 39 of file TfLiteParser.hpp.
BufferRawPtr
using BufferRawPtr = const tflite::BufferT *
Definition at line 40 of file TfLiteParser.hpp.
ModelPtr
using ModelPtr = std::unique_ptr<tflite::ModelT>
Definition at line 30 of file TfLiteParser.hpp.
OperatorCodePtr
using OperatorCodePtr = std::unique_ptr<tflite::OperatorCodeT>
Definition at line 33 of file TfLiteParser.hpp.
OperatorPtr
using OperatorPtr = std::unique_ptr<tflite::OperatorT>
Definition at line 32 of file TfLiteParser.hpp.
SubgraphPtr
using SubgraphPtr = std::unique_ptr<tflite::SubGraphT>
Definition at line 31 of file TfLiteParser.hpp.
TensorIdRawPtr
using TensorIdRawPtr = std::pair<size_t, TensorRawPtr>
Definition at line 37 of file TfLiteParser.hpp.
TensorIdRawPtrVector
using TensorIdRawPtrVector = std::vector<TensorIdRawPtr>
Definition at line 38 of file TfLiteParser.hpp.
TensorPtr
using TensorPtr = std::unique_ptr<tflite::TensorT>
Definition at line 34 of file TfLiteParser.hpp.
TensorRawPtr
using TensorRawPtr = const tflite::TensorT *
Definition at line 35 of file TfLiteParser.hpp.
TensorRawPtrVector
using TensorRawPtrVector = std::vector<TensorRawPtr>
Definition at line 36 of file TfLiteParser.hpp.
Constructor & Destructor Documentation
TfLiteParserImpl()
TfLiteParserImpl (const armnn::Optional< ITfLiteParser::TfLiteParserOptions > & options = armnn::EmptyOptional())
Definition at line 719 of file TfLiteParser.cpp.
References CHECKED_NON_NEGATIVE, TfLiteParserImpl::GetInputTensorIds(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::InferOutputShapes(), TensorInfo::SetShape(), and armnnDeserializer::ToTensorInfo().
 : m_Options(options)
 , m_Network(nullptr, nullptr)
 , m_ParserFunctions(tflite::BuiltinOperator_MAX+1, &TfLiteParserImpl::ParseUnsupportedOperator)
 {
     // register supported operators
     m_ParserFunctions[tflite::BuiltinOperator_ABS]                     = &TfLiteParserImpl::ParseAbs;
     m_ParserFunctions[tflite::BuiltinOperator_ADD]                     = &TfLiteParserImpl::ParseAdd;
     m_ParserFunctions[tflite::BuiltinOperator_ARG_MIN]                 = &TfLiteParserImpl::ParseArgMin;
     m_ParserFunctions[tflite::BuiltinOperator_ARG_MAX]                 = &TfLiteParserImpl::ParseArgMax;
     m_ParserFunctions[tflite::BuiltinOperator_AVERAGE_POOL_2D]         = &TfLiteParserImpl::ParseAveragePool2D;
     m_ParserFunctions[tflite::BuiltinOperator_BATCH_TO_SPACE_ND]       = &TfLiteParserImpl::ParseBatchToSpaceND;
     m_ParserFunctions[tflite::BuiltinOperator_BATCH_MATMUL]            = &TfLiteParserImpl::ParseBatchMatMul;
     m_ParserFunctions[tflite::BuiltinOperator_CAST]                    = &TfLiteParserImpl::ParseCast;
     m_ParserFunctions[tflite::BuiltinOperator_CONCATENATION]           = &TfLiteParserImpl::ParseConcatenation;
     m_ParserFunctions[tflite::BuiltinOperator_CONV_2D]                 = &TfLiteParserImpl::ParseConv2D;
     // Conv3D support was added in TF 2.5, so for backwards compatibility a hash define is needed.
     #if defined(ARMNN_POST_TFLITE_2_4)
     m_ParserFunctions[tflite::BuiltinOperator_CONV_3D]                 = &TfLiteParserImpl::ParseConv3D;
     #endif
     m_ParserFunctions[tflite::BuiltinOperator_CUSTOM]                  = &TfLiteParserImpl::ParseCustomOperator;
     m_ParserFunctions[tflite::BuiltinOperator_DEPTH_TO_SPACE]          = &TfLiteParserImpl::ParseDepthToSpace;
     m_ParserFunctions[tflite::BuiltinOperator_DEPTHWISE_CONV_2D]       = &TfLiteParserImpl::ParseDepthwiseConv2D;
     m_ParserFunctions[tflite::BuiltinOperator_DEQUANTIZE]              = &TfLiteParserImpl::ParseDequantize;
     m_ParserFunctions[tflite::BuiltinOperator_DIV]                     = &TfLiteParserImpl::ParseDiv;
     m_ParserFunctions[tflite::BuiltinOperator_ELU]                     = &TfLiteParserImpl::ParseElu;
     m_ParserFunctions[tflite::BuiltinOperator_EQUAL]                   = &TfLiteParserImpl::ParseEqual;
     m_ParserFunctions[tflite::BuiltinOperator_EXP]                     = &TfLiteParserImpl::ParseExp;
     m_ParserFunctions[tflite::BuiltinOperator_EXPAND_DIMS]             = &TfLiteParserImpl::ParseExpandDims;
     m_ParserFunctions[tflite::BuiltinOperator_FLOOR_DIV]               = &TfLiteParserImpl::ParseFloorDiv;
     m_ParserFunctions[tflite::BuiltinOperator_FULLY_CONNECTED]         = &TfLiteParserImpl::ParseFullyConnected;
     m_ParserFunctions[tflite::BuiltinOperator_GATHER]                  = &TfLiteParserImpl::ParseGather;
     m_ParserFunctions[tflite::BuiltinOperator_GATHER_ND]               = &TfLiteParserImpl::ParseGatherNd;
     m_ParserFunctions[tflite::BuiltinOperator_GREATER]                 = &TfLiteParserImpl::ParseGreater;
     m_ParserFunctions[tflite::BuiltinOperator_GREATER_EQUAL]           = &TfLiteParserImpl::ParseGreaterOrEqual;
     m_ParserFunctions[tflite::BuiltinOperator_HARD_SWISH]              = &TfLiteParserImpl::ParseHardSwish;
     m_ParserFunctions[tflite::BuiltinOperator_LEAKY_RELU]              = &TfLiteParserImpl::ParseLeakyRelu;
     m_ParserFunctions[tflite::BuiltinOperator_LESS]                    = &TfLiteParserImpl::ParseLess;
     m_ParserFunctions[tflite::BuiltinOperator_LESS_EQUAL]              = &TfLiteParserImpl::ParseLessOrEqual;
     m_ParserFunctions[tflite::BuiltinOperator_LOCAL_RESPONSE_NORMALIZATION]
             = &TfLiteParserImpl::ParseLocalResponseNormalization;
     m_ParserFunctions[tflite::BuiltinOperator_LOG]                     = &TfLiteParserImpl::ParseLog;
     m_ParserFunctions[tflite::BuiltinOperator_LOGICAL_NOT]             = &TfLiteParserImpl::ParseLogicalNot;
     m_ParserFunctions[tflite::BuiltinOperator_LOGISTIC]                = &TfLiteParserImpl::ParseLogistic;
     m_ParserFunctions[tflite::BuiltinOperator_LOG_SOFTMAX]             = &TfLiteParserImpl::ParseLogSoftmax;
     m_ParserFunctions[tflite::BuiltinOperator_L2_NORMALIZATION]        = &TfLiteParserImpl::ParseL2Normalization;
     m_ParserFunctions[tflite::BuiltinOperator_MAX_POOL_2D]             = &TfLiteParserImpl::ParseMaxPool2D;
     m_ParserFunctions[tflite::BuiltinOperator_MAXIMUM]                 = &TfLiteParserImpl::ParseMaximum;
     m_ParserFunctions[tflite::BuiltinOperator_MEAN]                    = &TfLiteParserImpl::ParseMean;
     m_ParserFunctions[tflite::BuiltinOperator_MINIMUM]                 = &TfLiteParserImpl::ParseMinimum;
     m_ParserFunctions[tflite::BuiltinOperator_MIRROR_PAD]              = &TfLiteParserImpl::ParseMirrorPad;
     m_ParserFunctions[tflite::BuiltinOperator_MUL]                     = &TfLiteParserImpl::ParseMul;
     m_ParserFunctions[tflite::BuiltinOperator_NEG]                     = &TfLiteParserImpl::ParseNeg;
     m_ParserFunctions[tflite::BuiltinOperator_NOT_EQUAL]               = &TfLiteParserImpl::ParseNotEqual;
     m_ParserFunctions[tflite::BuiltinOperator_PACK]                    = &TfLiteParserImpl::ParsePack;
     m_ParserFunctions[tflite::BuiltinOperator_PAD]                     = &TfLiteParserImpl::ParsePad;
     m_ParserFunctions[tflite::BuiltinOperator_PADV2]                   = &TfLiteParserImpl::ParsePad;
     m_ParserFunctions[tflite::BuiltinOperator_PRELU]                   = &TfLiteParserImpl::ParsePrelu;
     m_ParserFunctions[tflite::BuiltinOperator_QUANTIZE]                = &TfLiteParserImpl::ParseQuantize;
     m_ParserFunctions[tflite::BuiltinOperator_RELU]                    = &TfLiteParserImpl::ParseRelu;
     m_ParserFunctions[tflite::BuiltinOperator_RELU6]                   = &TfLiteParserImpl::ParseRelu6;
     m_ParserFunctions[tflite::BuiltinOperator_REDUCE_MAX]              = &TfLiteParserImpl::ParseReduceMax;
     m_ParserFunctions[tflite::BuiltinOperator_REDUCE_MIN]              = &TfLiteParserImpl::ParseReduceMin;
     m_ParserFunctions[tflite::BuiltinOperator_REDUCE_PROD]             = &TfLiteParserImpl::ParseReduceProd;
     m_ParserFunctions[tflite::BuiltinOperator_RESHAPE]                 = &TfLiteParserImpl::ParseReshape;
     m_ParserFunctions[tflite::BuiltinOperator_RESIZE_BILINEAR]         = &TfLiteParserImpl::ParseResizeBilinear;
     m_ParserFunctions[tflite::BuiltinOperator_RESIZE_NEAREST_NEIGHBOR] = &TfLiteParserImpl::ParseResizeNearestNeighbor;
     m_ParserFunctions[tflite::BuiltinOperator_RSQRT]                   = &TfLiteParserImpl::ParseRsqrt;
     m_ParserFunctions[tflite::BuiltinOperator_SQRT]                    = &TfLiteParserImpl::ParseSqrt;
     m_ParserFunctions[tflite::BuiltinOperator_SHAPE]                   = &TfLiteParserImpl::ParseShape;
     m_ParserFunctions[tflite::BuiltinOperator_SIN]                     = &TfLiteParserImpl::ParseSin;
     m_ParserFunctions[tflite::BuiltinOperator_SLICE]                   = &TfLiteParserImpl::ParseSlice;
     m_ParserFunctions[tflite::BuiltinOperator_SOFTMAX]                 = &TfLiteParserImpl::ParseSoftmax;
     m_ParserFunctions[tflite::BuiltinOperator_SPACE_TO_BATCH_ND]       = &TfLiteParserImpl::ParseSpaceToBatchND;
     m_ParserFunctions[tflite::BuiltinOperator_SPLIT]                   = &TfLiteParserImpl::ParseSplit;
     m_ParserFunctions[tflite::BuiltinOperator_SPLIT_V]                 = &TfLiteParserImpl::ParseSplitV;
     m_ParserFunctions[tflite::BuiltinOperator_SQUEEZE]                 = &TfLiteParserImpl::ParseSqueeze;
     m_ParserFunctions[tflite::BuiltinOperator_STRIDED_SLICE]           = &TfLiteParserImpl::ParseStridedSlice;
     m_ParserFunctions[tflite::BuiltinOperator_SUB]                     = &TfLiteParserImpl::ParseSub;
     m_ParserFunctions[tflite::BuiltinOperator_SUM]                     = &TfLiteParserImpl::ParseSum;
     m_ParserFunctions[tflite::BuiltinOperator_TANH]                    = &TfLiteParserImpl::ParseTanH;
     m_ParserFunctions[tflite::BuiltinOperator_TRANSPOSE]               = &TfLiteParserImpl::ParseTranspose;
     m_ParserFunctions[tflite::BuiltinOperator_TRANSPOSE_CONV]          = &TfLiteParserImpl::ParseTransposeConv;
     m_ParserFunctions[tflite::BuiltinOperator_UNIDIRECTIONAL_SEQUENCE_LSTM]
             = &TfLiteParserImpl::ParseUnidirectionalSequenceLSTM;
     m_ParserFunctions[tflite::BuiltinOperator_UNPACK]                  = &TfLiteParserImpl::ParseUnpack;
     // register supported custom operators
     m_CustomParserFunctions["TFLite_Detection_PostProcess"]      = &TfLiteParserImpl::ParseDetectionPostProcess;
 }
~TfLiteParserImpl()
~TfLiteParserImpl () default
Member Function Documentation
CreateNetworkFromBinary()
INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent)
Create the network from a flatbuffers binary.
Definition at line 930 of file TfLiteParser.cpp.
References TfLiteParserImpl::LoadModelFromBinary().
 {
     ResetParser();
     m_Model = LoadModelFromBinary(binaryContent.data(), binaryContent.size());
     return CreateNetworkFromModel();
 }
CreateNetworkFromBinaryAsDynamic()
armnn::INetworkPtr CreateNetworkFromBinaryAsDynamic (const std::vector< uint8_t > & binaryContent)
CreateNetworkFromBinaryFile()
INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile)
Create the network from a flatbuffers binary file on disk.
Definition at line 923 of file TfLiteParser.cpp.
References TfLiteParserImpl::LoadModelFromFile().
 {
     ResetParser();
     m_Model = LoadModelFromFile(graphFile);
     return CreateNetworkFromModel();
 }
GetBuffer()
TfLiteParserImpl::BufferRawPtr GetBuffer (const ModelPtr & model, size_t bufferIndex) static
Definition at line 5019 of file TfLiteParser.cpp.
References CHECK_BUFFER, CHECK_BUFFER_SIZE, CHECK_LOCATION, CHECK_TENSOR_PTR, armnn::Float32, TensorInfo::GetDataType(), armnn::GetDataTypeName(), TensorInfo::GetShape(), armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS8, TensorInfo::SetConstant(), armnn::Signed32, armnnUtils::ToFloatArray(), and armnnDeserializer::ToTensorInfo().
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParserImpl::OutputShapeOfReshape(), and TfLiteParserImpl::OutputShapeOfSqueeze().
 {
     CHECK_BUFFER(model, bufferIndex);
     return model->buffers[bufferIndex].get();
 }
GetInputs()
TfLiteParserImpl::TensorRawPtrVector GetInputs (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 4718 of file TfLiteParser.cpp.
References CHECK_MODEL, and CHECKED_NON_NEGATIVE.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParserImpl::LoadModel(), TfLiteParserImpl::OutputShapeOfReshape(), and TfLiteParserImpl::OutputShapeOfSqueeze().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto& subgraphPtr = model->subgraphs[subgraphIndex];
     const auto& operatorPtr = subgraphPtr->operators[operatorIndex];
     size_t inputCount = operatorPtr->inputs.size();
     TensorRawPtrVector result;
     for (size_t i = 0; i < inputCount; ++i)
     {
         // If the input location is -1 then assume input is turned off.
         if (operatorPtr->inputs[i] == -1)
         {
             continue;
         }
         else
         {
             uint32_t inputId = CHECKED_NON_NEGATIVE(operatorPtr->inputs[i]);
             result.push_back(subgraphPtr->tensors[inputId].get());
         }
     }
     return result;
 }
GetInputTensorIds()
std::vector< int32_t > & GetInputTensorIds (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 4798 of file TfLiteParser.cpp.
References CHECK_MODEL.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParserImpl::LoadModel(), TfLiteParserImpl::OutputShapeOfReshape(), TfLiteParserImpl::OutputShapeOfSqueeze(), and TfLiteParserImpl::TfLiteParserImpl().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto& subgraphPtr = model->subgraphs[subgraphIndex];
     const auto& operatorPtr = subgraphPtr->operators[operatorIndex];
     return operatorPtr->inputs;
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (size_t subgraphId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and subgraph id.
Definition at line 5197 of file TfLiteParser.cpp.
References CHECK_LOCATION, CHECK_SUBGRAPH, TfLiteParserImpl::GetSubgraphInputs(), TensorInfo::SetConstant(), and armnnDeserializer::ToTensorInfo().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto inputs = GetSubgraphInputs(m_Model, subgraphId);
     for (auto const& input : inputs)
     {
         if (input.second->name == name)
         {
             auto bindingId = GenerateLayerBindingId(subgraphId, input.first);
             auto inputTensorInfo = ToTensorInfo(input.second);
             // Input tensors are always treated as constant tensors during network execution.
             inputTensorInfo.SetConstant(true);
             return std::make_pair(bindingId, inputTensorInfo);
         }
     }
     std::stringstream bindings;
     for (auto const& input : inputs)
     {
         bindings << "'" << input.second->name << "' ";
     }
     throw ParseException(
         fmt::format("No input binding found for subgraph:{} and name:{}. "
                     "Possible inputs are: [{}] {}",
                     subgraphId,
                     name,
                     bindings.str(),
                     CHECK_LOCATION().AsString()));
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (size_t subgraphId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and subgraph id.
Definition at line 5229 of file TfLiteParser.cpp.
References CHECK_LOCATION, CHECK_SUBGRAPH, TfLiteParserImpl::GetSubgraphOutputs(), and armnnDeserializer::ToTensorInfo().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto outputs = GetSubgraphOutputs(m_Model, subgraphId);
     for (unsigned int i = 0; i < outputs.size(); ++i)
     {
         auto const output = outputs[i];
         if (output.second->name == name)
         {
             auto bindingId = GenerateLayerBindingId(subgraphId, output.first);
             std::vector<unsigned int> shape = m_OverriddenOutputShapes.size() > 0 ?
                                                 m_OverriddenOutputShapes[i] : AsUnsignedVector(output.second->shape);
             return std::make_pair(bindingId, ToTensorInfo(output.second, shape));
         }
     }
     std::stringstream bindings;
     for (auto const& output : outputs)
     {
         bindings << "'" << output.second->name << "' ";
     }
     throw ParseException(
         fmt::format("No output binding found for subgraph:{} and name:{}. "
                     "Possible outputs are: [{}] {}",
                     subgraphId,
                     name,
                     bindings.str(),
                     CHECK_LOCATION().AsString()));
 }
GetOutputs()
TfLiteParserImpl::TensorRawPtrVector GetOutputs (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 4745 of file TfLiteParser.cpp.
References CHECK_MODEL, CHECK_TENSOR, and CHECKED_NON_NEGATIVE.
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParserImpl::LoadModel(), TfLiteParserImpl::OutputShapeOfReshape(), and TfLiteParserImpl::OutputShapeOfSqueeze().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto& subgraphPtr = model->subgraphs[subgraphIndex];
     const auto& operatorPtr = subgraphPtr->operators[operatorIndex];
     size_t outputCount = operatorPtr->outputs.size();
     TensorRawPtrVector result(outputCount);
     for (size_t i = 0; i < outputCount; ++i)
     {
         uint32_t outputId = CHECKED_NON_NEGATIVE(operatorPtr->outputs[i]);
         CHECK_TENSOR(model, subgraphIndex, outputId);
         result[i] = subgraphPtr->tensors[outputId].get();
     }
     return result;
 }
GetOutputTensorIds()
std::vector< int32_t > & GetOutputTensorIds (const ModelPtr & model, size_t subgraphIndex, size_t operatorIndex) static
Definition at line 4808 of file TfLiteParser.cpp.
References ARMNN_ASSERT, CHECK_LOCATION, CHECK_MODEL, CHECK_SUBGRAPH, TensorInfo::GetDataType(), IConnectableLayer::GetInputSlot(), TensorInfo::GetNumBytes(), IConnectableLayer::GetNumInputSlots(), IConnectableLayer::GetNumOutputSlots(), IConnectableLayer::GetOutputSlot(), TfLiteParserImpl::GetSubgraphInputs(), TfLiteParserImpl::GetSubgraphOutputs(), TensorInfo::SetConstant(), TensorInfo::SetDataType(), IOutputSlot::SetTensorInfo(), and armnnDeserializer::ToTensorInfo().
Referenced by armnnTfLiteParser::ComputeWrappedIndex(), TfLiteParserImpl::LoadModel(), TfLiteParserImpl::OutputShapeOfReshape(), and TfLiteParserImpl::OutputShapeOfSqueeze().
 {
     CHECK_MODEL(model, subgraphIndex, operatorIndex);
     const auto& subgraphPtr = model->subgraphs[subgraphIndex];
     const auto& operatorPtr = subgraphPtr->operators[operatorIndex];
     return operatorPtr->outputs;
 }
GetSubgraphCount()
size_t GetSubgraphCount () const
Return the number of subgraphs in the parsed model.
Definition at line 5261 of file TfLiteParser.cpp.
 {
     return m_Model->subgraphs.size();
 }
GetSubgraphInputs()
TfLiteParserImpl::TensorIdRawPtrVector GetSubgraphInputs (const ModelPtr & model, size_t subgraphIndex) static
Definition at line 4765 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, CHECK_TENSOR, and CHECKED_NON_NEGATIVE.
Referenced by TfLiteParserImpl::GetNetworkInputBindingInfo(), TfLiteParserImpl::GetOutputTensorIds(), and TfLiteParserImpl::GetSubgraphInputTensorNames().
 {
     CHECK_SUBGRAPH(model, subgraphIndex);
     const auto& subgraphPtr = model->subgraphs[subgraphIndex];
     size_t inputCount = subgraphPtr->inputs.size();
     TensorIdRawPtrVector result(inputCount);
     for (size_t i = 0; i < inputCount; ++i)
     {
         uint32_t inputId = CHECKED_NON_NEGATIVE(subgraphPtr->inputs[i]);
         CHECK_TENSOR(model, subgraphIndex, inputId);
         result[i] = std::make_pair(inputId, subgraphPtr->tensors[inputId].get());
     }
     return result;
 }
GetSubgraphInputTensorNames()
std::vector< std::string > GetSubgraphInputTensorNames (size_t subgraphId) const
Return the input tensor names for a given subgraph.
Definition at line 5266 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, and TfLiteParserImpl::GetSubgraphInputs().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto inputs = GetSubgraphInputs(m_Model, subgraphId);
     std::vector<std::string> result;
     result.reserve(inputs.size());
     for (auto const& input : inputs)
     {
         result.push_back(input.second->name);
     }
     return result;
 }
GetSubgraphOutputs()
TfLiteParserImpl::TensorIdRawPtrVector GetSubgraphOutputs (const ModelPtr & model, size_t subgraphIndex) static
Definition at line 4782 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, and CHECKED_NON_NEGATIVE.
Referenced by TfLiteParserImpl::GetNetworkOutputBindingInfo(), TfLiteParserImpl::GetOutputTensorIds(), and TfLiteParserImpl::GetSubgraphOutputTensorNames().
 {
     CHECK_SUBGRAPH(model, subgraphIndex);
     const auto& subgraphPtr = model->subgraphs[subgraphIndex];
     size_t outputCount = subgraphPtr->outputs.size();
     TensorIdRawPtrVector result(outputCount);
     for (size_t i = 0; i < outputCount; ++i)
     {
         uint32_t outputId = CHECKED_NON_NEGATIVE(subgraphPtr->outputs[i]);
         result[i] = std::make_pair(outputId, subgraphPtr->tensors[outputId].get());
     }
     return result;
 }
GetSubgraphOutputTensorNames()
std::vector< std::string > GetSubgraphOutputTensorNames (size_t subgraphId) const
Return the output tensor names for a given subgraph.
Definition at line 5279 of file TfLiteParser.cpp.
References CHECK_SUBGRAPH, and TfLiteParserImpl::GetSubgraphOutputs().
 {
     CHECK_SUBGRAPH(m_Model, subgraphId);
     auto outputs = GetSubgraphOutputs(m_Model, subgraphId);
     std::vector<std::string> result;
     result.reserve(outputs.size());
     for (auto const& output : outputs)
     {
         result.push_back(output.second->name);
     }
     return result;
 }
GetVersion()
const std::string GetVersion () static
Retrieve version in X.Y.Z form.
Definition at line 5292 of file TfLiteParser.cpp.
References TFLITE_PARSER_VERSION.
 {
     return TFLITE_PARSER_VERSION;
 }
LoadModel()
armnn::INetworkPtr LoadModel (std::unique_ptr< tflite::ModelT > model)
Definition at line 938 of file TfLiteParser.cpp.
References TensorShape::AreAllDimensionsSpecified(), ARMNN_ASSERT, ARMNN_LOG, CHECK_LOCATION, CHECK_MODEL, CHECK_SUPPORTED_FUSED_ACTIVATION, CHECK_TENSOR, CHECK_VALID_SIZE, CHECKED_NON_NEGATIVE, armnn::error, TensorInfo::GetDataType(), TfLiteParserImpl::GetInputs(), TfLiteParserImpl::GetInputTensorIds(), TensorShape::GetNumDimensions(), TfLiteParserImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), TfLiteParserImpl::GetOutputTensorIds(), IOutputSlot::GetOwningIConnectableLayer(), TensorInfo::GetShape(), IConnectableLayer::GetType(), Convolution2dDescriptor::m_BiasEnabled, Convolution3dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, Convolution3dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, Convolution3dDescriptor::m_DilationX, DepthwiseConvolution2dDescriptor::m_DilationX, Convolution3dDescriptor::m_DilationY, DepthwiseConvolution2dDescriptor::m_DilationY, Convolution3dDescriptor::m_DilationZ, Convolution3dDescriptor::m_PadBack, Convolution3dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, Convolution3dDescriptor::m_PadFront, Convolution3dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, Convolution3dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, Convolution3dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, Convolution3dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, Convolution3dDescriptor::m_StrideY, DepthwiseConvolution2dDescriptor::m_StrideY, Convolution3dDescriptor::m_StrideZ, ReshapeDescriptor::m_TargetShape, armnn::NDHWC, armnn::NHWC, armnn::numeric_cast(), IOutputSlot::SetTensorInfo(), armnnDeserializer::ToTensorInfo(), and Exception::what().
 {
     ResetParser();
     m_Model = std::move(model);
     return CreateNetworkFromModel();
 }
LoadModelFromBinary()
TfLiteParserImpl::ModelPtr LoadModelFromBinary (const uint8_t * binaryContent, size_t len) static
Definition at line 4699 of file TfLiteParser.cpp.
References CHECK_LOCATION.
Referenced by TfLiteParserImpl::CreateNetworkFromBinary(), and TfLiteParserImpl::LoadModelFromFile().
 {
     if (binaryContent == nullptr)
      {
         throw InvalidArgumentException(fmt::format("Invalid (null) binary content {}",
                                        CHECK_LOCATION().AsString()));
      }
     flatbuffers::Verifier verifier(binaryContent, len);
     if (verifier.VerifyBuffer<tflite::Model>() == false)
     {
         throw ParseException(
             fmt::format("Buffer doesn't conform to the expected Tensorflow Lite "
                         "flatbuffers format. size:{} {}",
                         len,
                         CHECK_LOCATION().AsString()));
     }
     return tflite::UnPackModel(binaryContent);
 }
LoadModelFromFile()
TfLiteParserImpl::ModelPtr LoadModelFromFile (const char * fileName) static
Definition at line 4675 of file TfLiteParser.cpp.
References CHECK_LOCATION, and TfLiteParserImpl::LoadModelFromBinary().
Referenced by TfLiteParserImpl::CreateNetworkFromBinaryFile().
 {
     if (fileName == nullptr)
     {
         throw InvalidArgumentException(fmt::format("Invalid (null) file name {}",
                                        CHECK_LOCATION().AsString()));
     }
     std::error_code errorCode;
     fs::path pathToFile(fileName);
     if (!fs::exists(pathToFile, errorCode))
     {
         //fmt::format() could not be used here (format error)
         std::stringstream msg;
         msg << "Cannot find the file (" << fileName << ") errorCode: " << errorCode
             << " " << CHECK_LOCATION().AsString();
         throw FileNotFoundException(msg.str());
     }
     std::ifstream file(fileName, std::ios::binary);
     std::string fileContent((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
     return LoadModelFromBinary(reinterpret_cast<const uint8_t *>(fileContent.c_str()),
                                fileContent.size());
 }
OutputShapeOfReshape()
armnn::TensorInfo OutputShapeOfReshape (const armnn::TensorInfo & inputTensorInfo, const std::vector< int32_t > & targetDimsIn) static
Definition at line 2882 of file TfLiteParser.cpp.
References ARMNN_ASSERT, ARMNN_THROW_PARSE_EXCEPTION, CHECK_LOCATION, CHECK_MODEL, CHECK_SUPPORTED_FUSED_ACTIVATION, CHECK_VALID_SIZE, CHECKED_NON_NEGATIVE, armnnDeserializer::CheckShape(), IOutputSlot::Connect(), TfLiteParserImpl::GetBuffer(), TensorInfo::GetDataType(), BaseTensor< MemoryType >::GetInfo(), TfLiteParserImpl::GetInputs(), IConnectableLayer::GetInputSlot(), TfLiteParserImpl::GetInputTensorIds(), IConnectableLayer::GetName(), TensorInfo::GetNumBytes(), TensorShape::GetNumDimensions(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), IConnectableLayer::GetNumOutputSlots(), TfLiteParserImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), TfLiteParserImpl::GetOutputTensorIds(), TensorInfo::GetQuantizationOffset(), TensorInfo::GetQuantizationScale(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), armnnUtils::GetUnsignedAxis(), LstmDescriptor::m_ActivationFunc, StackDescriptor::m_Axis, FullyConnectedDescriptor::m_BiasEnabled, LstmInputParams::m_CellBias, LstmInputParams::m_CellLayerNormWeights, LstmInputParams::m_CellToForgetWeights, LstmInputParams::m_CellToInputWeights, LstmInputParams::m_CellToOutputWeights, FullyConnectedDescriptor::m_ConstantWeights, DetectionPostProcessDescriptor::m_DetectionsPerClass, LstmInputParams::m_ForgetGateBias, LstmInputParams::m_ForgetLayerNormWeights, LstmInputParams::m_InputGateBias, LstmInputParams::m_InputLayerNormWeights, StackDescriptor::m_InputShape, LstmInputParams::m_InputToCellWeights, LstmInputParams::m_InputToForgetWeights, LstmInputParamsInfo::m_InputToForgetWeights, LstmInputParams::m_InputToInputWeights, LstmInputParams::m_InputToOutputWeights, DetectionPostProcessDescriptor::m_MaxClassesPerDetection, DetectionPostProcessDescriptor::m_MaxDetections, ResizeDescriptor::m_Method, DetectionPostProcessDescriptor::m_NmsIouThreshold, DetectionPostProcessDescriptor::m_NmsScoreThreshold, DetectionPostProcessDescriptor::m_NumClasses, StackDescriptor::m_NumInputs, LstmInputParams::m_OutputGateBias, LstmInputParams::m_OutputLayerNormWeights, LstmInputParams::m_ProjectionBias, LstmInputParams::m_ProjectionWeights, LstmInputParams::m_RecurrentToCellWeights, LstmInputParams::m_RecurrentToForgetWeights, LstmInputParams::m_RecurrentToInputWeights, LstmInputParams::m_RecurrentToOutputWeights, DetectionPostProcessDescriptor::m_ScaleH, DetectionPostProcessDescriptor::m_ScaleW, DetectionPostProcessDescriptor::m_ScaleX, DetectionPostProcessDescriptor::m_ScaleY, ReshapeDescriptor::m_TargetShape, FullyConnectedDescriptor::m_TransposeWeightMatrix, DetectionPostProcessDescriptor::m_UseRegularNms, armnn::MaxNumOfTensorDimensions, armnn::NHWC, armnn::numeric_cast(), armnnUtils::ProcessConcatInputTensorInfo(), OriginsDescriptor::SetConcatAxis(), TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), ViewsDescriptor::SetViewOriginCoord(), ViewsDescriptor::SetViewSize(), and armnnDeserializer::ToTensorInfo().
 {
     std::vector<unsigned int> outputDims(targetDimsIn.begin(), targetDimsIn.end());
     const auto stretchDim = std::find(targetDimsIn.begin(), targetDimsIn.end(), -1);
     if (stretchDim != targetDimsIn.end())
     {
         if (std::find(std::next(stretchDim), targetDimsIn.end(), -1) != targetDimsIn.end())
         {
             throw ParseException(
                 fmt::format("At most one component of shape can be -1 {}", CHECK_LOCATION().AsString()));
         }
         auto targetNumElements =
             armnn::numeric_cast<unsigned int>(
                 std::accumulate(targetDimsIn.begin(), targetDimsIn.end(), -1, std::multiplies<int32_t>()));
         auto stretchIndex = static_cast<size_t>(std::distance(targetDimsIn.begin(), stretchDim));
         outputDims[stretchIndex] = inputTensorInfo.GetNumElements() / targetNumElements;
     }
     TensorShape outputShape = TensorShape(static_cast<unsigned int>(outputDims.size()), outputDims.data());
     TensorInfo reshapeInfo = inputTensorInfo;
     reshapeInfo.SetShape(outputShape);
     return reshapeInfo;
 }
OutputShapeOfSqueeze()
armnn::TensorInfo OutputShapeOfSqueeze (std::vector< uint32_t > squeezeDims, const armnn::TensorInfo & inputTensorInfo) static
Definition at line 2137 of file TfLiteParser.cpp.
References ARMNN_ASSERT, ARMNN_THROW_PARSE_EXCEPTION, CHECK_LOCATION, CHECK_MODEL, CHECK_VALID_SIZE, IOutputSlot::Connect(), armnn::Float32, TfLiteParserImpl::GetBuffer(), TensorInfo::GetDataType(), TfLiteParserImpl::GetInputs(), IConnectableLayer::GetInputSlot(), TfLiteParserImpl::GetInputTensorIds(), TensorInfo::GetNumBytes(), TensorShape::GetNumDimensions(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), TfLiteParserImpl::GetOutputs(), IConnectableLayer::GetOutputSlot(), TfLiteParserImpl::GetOutputTensorIds(), TensorInfo::GetShape(), armnn::IgnoreUnused(), ActivationDescriptor::m_A, MeanDescriptor::m_Axis, ActivationDescriptor::m_B, StridedSliceDescriptor::m_Begin, StridedSliceDescriptor::m_BeginMask, StridedSliceDescriptor::m_DataLayout, StridedSliceDescriptor::m_EllipsisMask, StridedSliceDescriptor::m_End, StridedSliceDescriptor::m_EndMask, ActivationDescriptor::m_Function, MeanDescriptor::m_KeepDims, StridedSliceDescriptor::m_NewAxisMask, PadDescriptor::m_PaddingMode, PadDescriptor::m_PadList, PadDescriptor::m_PadValue, StridedSliceDescriptor::m_ShrinkAxisMask, StridedSliceDescriptor::m_Stride, ReshapeDescriptor::m_TargetShape, armnn::NHWC, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS8, TensorInfo::SetShape(), IOutputSlot::SetTensorInfo(), armnn::Signed32, armnn::Signed64, and armnnDeserializer::ToTensorInfo().
 {
     CHECK_VALID_SIZE(squeezeDims.size(), 0, 1, 2, 3, 4);
     static const uint32_t dimensionSequence[] = { 0, 1, 2, 3 };
     if (inputTensorInfo.GetNumDimensions() > 4)
     {
         std::stringstream ss;
         ss << "Input tensor has unexpected number of dimensions:" << inputTensorInfo.GetNumDimensions()
            << " shape:" << inputTensorInfo.GetShape() << " "
            << CHECK_LOCATION().AsString();
         throw ParseException(ss.str());
     }
     if (squeezeDims.empty())
     {
         squeezeDims.assign(dimensionSequence,
                            dimensionSequence+inputTensorInfo.GetNumDimensions());
     }
     std::vector<uint32_t> outputDims;
     for(unsigned int i = 0; i < inputTensorInfo.GetNumDimensions(); i++)
     {
         bool skipSqueeze = (std::find(squeezeDims.begin(), squeezeDims.end(), i) == squeezeDims.end());
         auto currentDimension = inputTensorInfo.GetShape()[i];
         if (skipSqueeze || currentDimension != 1)
         {
             outputDims.push_back(currentDimension);
         }
     }
     if (outputDims.size() > 4)
     {
         std::stringstream ss;
         ss << "Output tensor has unexpected number of dimensions:" << inputTensorInfo.GetNumDimensions()
            << " shape:" << inputTensorInfo.GetShape() << " "
            << CHECK_LOCATION().AsString();
         throw ParseException(ss.str());
     }
     TensorShape outShape = TensorShape(static_cast<unsigned int>(outputDims.size()),
                                        outputDims.data());
     // we need to preserve the tensor type and the quantization data as well
     TensorInfo outTensorInfo = inputTensorInfo;
     outTensorInfo.SetShape(outShape);
     return outTensorInfo;
 }
The documentation for this class was generated from the following files:
src/armnnTfLiteParser/TfLiteParser.hpp
src/armnnTfLiteParser/TfLiteParser.cpp