ArmNN: SampleDynamicAdditionWorkload Class Reference
SampleDynamicAdditionWorkload Class Reference
#include <SampleDynamicAdditionWorkload.hpp>
Public Member Functions
SampleDynamicAdditionWorkload (const armnn::AdditionQueueDescriptor &descriptor, const armnn::WorkloadInfo &info)
void Execute () const override
Public Member Functions inherited from BaseWorkload< armnn::AdditionQueueDescriptor >
BaseWorkload (const armnn::AdditionQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const armnn::AdditionQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
virtual bool SupportsTensorHandleReplacement () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< armnn::AdditionQueueDescriptor >
armnn::AdditionQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 13 of file SampleDynamicAdditionWorkload.hpp.
Constructor & Destructor Documentation
SampleDynamicAdditionWorkload()
SampleDynamicAdditionWorkload (const armnn::AdditionQueueDescriptor & descriptor, const armnn::WorkloadInfo & info)
Definition at line 34 of file SampleDynamicAdditionWorkload.cpp.
     : BaseWorkload(descriptor, info)
 {}
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 39 of file SampleDynamicAdditionWorkload.cpp.
References sdb::GetInputTensorData(), TensorInfo::GetNumElements(), sdb::GetOutputTensorData(), sdb::GetTensorInfo(), BaseWorkload< armnn::AdditionQueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
 {
     const armnn::TensorInfo& info = GetTensorInfo(m_Data.m_Inputs[0]);
     unsigned int num = info.GetNumElements();
     const float* inputData0 = GetInputTensorData(0, m_Data);
     const float* inputData1 = GetInputTensorData(1, m_Data);
     float* outputData       = GetOutputTensorData(0, m_Data);
     for (unsigned int i = 0; i < num; ++i)
     {
         outputData[i] = inputData0[i] + inputData1[i];
     }
 }
The documentation for this class was generated from the following files:
src/dynamic/sample/SampleDynamicAdditionWorkload.hpp
src/dynamic/sample/SampleDynamicAdditionWorkload.cpp