ArmNN: IBackendContext Class Reference
IBackendContext Class Reference abstract
#include <IBackendContext.hpp>
Public Member Functions
virtual bool BeforeLoadNetwork (NetworkId networkId)=0
Before and after Load network events.
virtual bool AfterLoadNetwork (NetworkId networkId)=0
virtual bool BeforeUnloadNetwork (NetworkId networkId)=0
Before and after Unload network events.
virtual bool AfterUnloadNetwork (NetworkId networkId)=0
virtual bool AfterEnqueueWorkload (NetworkId networkId)=0
virtual ~IBackendContext ()
Protected Member Functions
IBackendContext (const IRuntime::CreationOptions &)
Detailed Description
Definition at line 14 of file IBackendContext.hpp.
Constructor & Destructor Documentation
IBackendContext()
IBackendContext (const IRuntime::CreationOptions &) inline protected
Definition at line 17 of file IBackendContext.hpp.
References IBackendContext::AfterEnqueueWorkload(), IBackendContext::AfterLoadNetwork(), IBackendContext::AfterUnloadNetwork(), IBackendContext::BeforeLoadNetwork(), and IBackendContext::BeforeUnloadNetwork().
 {}
~IBackendContext()
virtual ~IBackendContext () inline virtual
Definition at line 31 of file IBackendContext.hpp.
 {}
Member Function Documentation
AfterEnqueueWorkload()
virtual bool AfterEnqueueWorkload (NetworkId networkId) pure virtual
Implemented in ClBackendContext.
Referenced by IBackendContext::IBackendContext().
AfterLoadNetwork()
virtual bool AfterLoadNetwork (NetworkId networkId) pure virtual
Implemented in ClBackendContext.
Referenced by IBackendContext::IBackendContext().
AfterUnloadNetwork()
virtual bool AfterUnloadNetwork (NetworkId networkId) pure virtual
Implemented in ClBackendContext.
Referenced by IBackendContext::IBackendContext().
BeforeLoadNetwork()
virtual bool BeforeLoadNetwork (NetworkId networkId) pure virtual
Before and after Load network events.
Implemented in ClBackendContext.
Referenced by IBackendContext::IBackendContext().
BeforeUnloadNetwork()
virtual bool BeforeUnloadNetwork (NetworkId networkId) pure virtual
Before and after Unload network events.
Implemented in ClBackendContext.
Referenced by IBackendContext::IBackendContext().
The documentation for this class was generated from the following file:
include/armnn/backends/IBackendContext.hpp