ArmNN: ILayerSupport Class Reference
ILayerSupport Class Reference
#include <ILayerSupport.hpp>
Public Member Functions
virtual bool IsLayerSupported (const LayerType &type, const std::vector< TensorInfo > &infos, const BaseDescriptor &descriptor, const Optional< LstmInputParamsInfo > &lstmParamsInfo=EmptyOptional(), const Optional< QuantizedLstmInputParamsInfo > &quantizedLstmParamsInfo=EmptyOptional(), Optional< std::string &> reasonIfUnsupported=EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsActivationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsAdditionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsArgMinMaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsBatchToSpaceNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsCastSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsChannelShuffleSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsComparisonSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp16ToFp32Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvertFp32ToFp16Supported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConvolution3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDebugSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthToSpaceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDequantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDetectionPostProcessSupported(const TensorInfo &boxEncodings
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDilatedDepthwiseConvolutionSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsDivisionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsElementwiseUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFakeQuantizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFillSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFloorSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsFullyConnectedSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsGatherSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInputSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsInstanceNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsL2NormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalBinarySupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogicalUnarySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLogSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMaximumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMeanSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemCopySupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMemImportSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMergeSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMinimumSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsMultiplicationSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsNormalizationSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsOutputSupported(const TensorInfo &output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPadSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPermuteSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPooling3dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreCompiledSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsPreluSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsQuantizedLstmSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsRankSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReduceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsReshapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsResizeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsShapeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSliceSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSoftmaxSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToBatchNdSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSpaceToDepthSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSplitterSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSubtractionSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsSwitchSupported(const TensorInfo &input0
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeConvolution2dSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsTransposeSupported(const TensorInfo &input
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsUnidirectionalSequenceLstmSupported(const TensorInfo &input
Public Attributes
const TensorInfo & output
const TensorInfo const ActivationDescriptor & descriptor
const TensorInfo const ActivationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & input1
const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ArgMinMaxDescriptor & descriptor
const TensorInfo const ArgMinMaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & mean
const TensorInfo const TensorInfo const TensorInfo & var
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & beta
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & gamma
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const BatchToSpaceNdDescriptor & descriptor
const TensorInfo const BatchToSpaceNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ChannelShuffleDescriptor & descriptor
const TensorInfo const ChannelShuffleDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const ComparisonDescriptor & descriptor
const TensorInfo const TensorInfo const ComparisonDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConcatSupported(const std Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution2dDescriptor & descriptor
const TensorInfo const Convolution2dDescriptor const TensorInfo & weights
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Convolution3dDescriptor & descriptor
const TensorInfo const Convolution3dDescriptor const TensorInfo & weights
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthToSpaceDescriptor & descriptor
const TensorInfo const DepthToSpaceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const DepthwiseConvolution2dDescriptor & descriptor
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & scores
const TensorInfo const TensorInfo & anchors
const TensorInfo const TensorInfo const TensorInfo & detectionBoxes
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionClasses
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & detectionScores
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & numDetections
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ElementwiseUnaryDescriptor & descriptor
const TensorInfo const ElementwiseUnaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const FakeQuantizationDescriptor & descriptor
const FakeQuantizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const FillDescriptor & descriptor
const TensorInfo const FillDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & weights
const TensorInfo const TensorInfo const TensorInfo & biases
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const GatherDescriptor & descriptor
const TensorInfo const TensorInfo const GatherDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const InstanceNormalizationDescriptor & descriptor
const TensorInfo const InstanceNormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const L2NormalizationDescriptor & descriptor
const TensorInfo const L2NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const LogicalBinaryDescriptor & descriptor
const TensorInfo const TensorInfo const LogicalBinaryDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const LogSoftmaxDescriptor & descriptor
const TensorInfo const LogSoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & outputStateIn
const TensorInfo const TensorInfo & cellStateIn
const TensorInfo const TensorInfo const TensorInfo & scratchBuffer
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const MeanDescriptor & descriptor
const TensorInfo const MeanDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & ouput
const TensorInfo const NormalizationDescriptor & descriptor
const TensorInfo const NormalizationDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PadDescriptor & descriptor
const TensorInfo const PadDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const PermuteDescriptor & descriptor
const TensorInfo const PermuteDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling2dDescriptor & descriptor
const TensorInfo const Pooling2dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const Pooling3dDescriptor & descriptor
const TensorInfo const Pooling3dDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const PreCompiledDescriptor & descriptor
const PreCompiledDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & alpha
const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo const TensorInfo & outputStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo & previousCellStateIn
const TensorInfo const TensorInfo & previousOutputIn
const TensorInfo const TensorInfo const TensorInfo & cellStateOut
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReduceDescriptor & descriptor
const TensorInfo const ReduceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ReshapeDescriptor & descriptor
const TensorInfo const ReshapeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const ResizeDescriptor & descriptor
const TensorInfo const ResizeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SliceDescriptor & descriptor
const TensorInfo const SliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SoftmaxDescriptor & descriptor
const TensorInfo const SoftmaxDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToBatchNdDescriptor & descriptor
const TensorInfo const SpaceToBatchNdDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const SpaceToDepthDescriptor & descriptor
const TensorInfo const SpaceToDepthDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const std::vector< std::reference_wrapper< TensorInfo > > & outputs
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor & descriptor
const std::vector< std::reference_wrapper< TensorInfo > > const ViewsDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo & output
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor & descriptor
ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo & output0
const TensorInfo const TensorInfo const TensorInfo & output1
const TensorInfo const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeConvolution2dDescriptor & descriptor
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo & weights
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TransposeDescriptor & descriptor
const TensorInfo const TransposeDescriptor Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor & descriptor
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo & paramsInfo
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Protected Member Functions
ILayerSupport ()
virtual ~ILayerSupport ()
Detailed Description
Definition at line 23 of file ILayerSupport.hpp.
Constructor & Destructor Documentation
ILayerSupport()
ILayerSupport () inline protected
Definition at line 26 of file ILayerSupport.hpp.
 {}
~ILayerSupport()
virtual ~ILayerSupport () inline protected virtual
Definition at line 27 of file ILayerSupport.hpp.
References ILayerSupport::ARMNN_DEPRECATED_MSG_REMOVAL_DATE(), ILayerSupport::descriptor, armnn::IsActivationSupported(), ILayerSupport::IsLayerSupported(), and ILayerSupport::reasonIfUnsupported.
 {}
Member Function Documentation
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [1/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
Referenced by ILayerSupport::~ILayerSupport().
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [2/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [3/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [4/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [5/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [6/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [7/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [8/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [9/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [10/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [11/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [12/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [13/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [14/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [15/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [16/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [17/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [18/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [19/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [20/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [21/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [22/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [23/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [24/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [25/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [26/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [27/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [28/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [29/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [30/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [31/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [32/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [33/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [34/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [35/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [36/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [37/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [38/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [39/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [40/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [41/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [42/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [43/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [44/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [45/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [46/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [47/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [48/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [49/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [50/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [51/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [52/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [53/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [54/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [55/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [56/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [57/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [58/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [59/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [60/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [61/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [62/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [63/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [64/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
ARMNN_DEPRECATED_MSG_REMOVAL_DATE() [65/65]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead." , "23.08") const &
IsLayerSupported()
ARMNN_NO_DEPRECATE_WARN_BEGIN bool IsLayerSupported (const LayerType & type, const std::vector< TensorInfo > & infos, const BaseDescriptor & descriptor, const Optional< LstmInputParamsInfo > & lstmParamsInfo = EmptyOptional(), const Optional< QuantizedLstmInputParamsInfo > & quantizedLstmParamsInfo = EmptyOptional(), Optional< std::string &> reasonIfUnsupported = EmptyOptional()) const virtual
Reimplemented in SampleDynamicLayerSupport, NeonLayerSupport, ClLayerSupport, LayerSupportBase, RefLayerSupport, and TosaRefLayerSupport.
Definition at line 18 of file ILayerSupport.cpp.
References armnn::Activation, armnn::Addition, ILayerSupport::alpha, ILayerSupport::anchors, armnn::ArgMinMax, ARMNN_NO_DEPRECATE_WARN_END, armnn::BatchNormalization, armnn::BatchToSpaceNd, ILayerSupport::beta, ILayerSupport::biases, armnn::Cast, ILayerSupport::cellStateIn, ILayerSupport::cellStateOut, armnn::ChannelShuffle, armnn::Comparison, armnn::Concat, armnn::Constant, armnn::ConvertFp16ToFp32, armnn::ConvertFp32ToFp16, armnn::Convolution2d, armnn::Convolution3d, armnn::Debug, armnn::DepthToSpace, armnn::DepthwiseConvolution2d, armnn::Dequantize, ILayerSupport::descriptor, ILayerSupport::detectionBoxes, ILayerSupport::detectionClasses, armnn::DetectionPostProcess, ILayerSupport::detectionScores, armnn::Division, armnn::ElementwiseUnary, armnn::FakeQuantization, armnn::Fill, armnn::Floor, armnn::FullyConnected, ILayerSupport::gamma, armnn::Gather, armnn::IgnoreUnused(), armnn::Input, ILayerSupport::input1, armnn::InstanceNormalization, armnn::IsActivationSupported(), armnn::IsAdditionSupported(), armnn::IsBatchNormalizationSupported(), armnn::IsBatchToSpaceNdSupported(), armnn::IsConcatSupported(), armnn::IsConstantSupported(), armnn::IsConvertFp16ToFp32Supported(), armnn::IsConvertFp32ToFp16Supported(), armnn::IsConvolution2dSupported(), armnn::IsDebugSupported(), armnn::IsDepthwiseConvolutionSupported(), armnn::IsDequantizeSupported(), armnn::IsDivisionSupported(), armnn::IsFakeQuantizationSupported(), armnn::IsFloorSupported(), armnn::IsFullyConnectedSupported(), armnn::IsInputSupported(), armnn::IsL2NormalizationSupported(), armnn::IsLstmSupported(), armnn::IsMaximumSupported(), armnn::IsMeanSupported(), armnn::IsMemCopySupported(), armnn::IsMergeSupported(), armnn::IsMinimumSupported(), armnn::IsMultiplicationSupported(), armnn::IsNormalizationSupported(), armnn::IsOutputSupported(), armnn::IsPadSupported(), armnn::IsPermuteSupported(), armnn::IsPooling2dSupported(), armnn::IsPreCompiledSupported(), armnn::IsPreluSupported(), armnn::IsQuantizedLstmSupported(), armnn::IsReduceSupported(), armnn::IsReshapeSupported(), armnn::IsResizeSupported(), armnn::IsSoftmaxSupported(), armnn::IsSpaceToBatchNdSupported(), armnn::IsSpaceToDepthSupported(), armnn::IsSplitterSupported(), armnn::IsStackSupported(), armnn::IsStridedSliceSupported(), armnn::IsSubtractionSupported(), armnn::IsSwitchSupported(), armnn::IsTransposeConvolution2dSupported(), armnn::L2Normalization, armnn::LogicalBinary, armnn::LogSoftmax, armnn::Lstm, armnn::Map, armnn::Maximum, ILayerSupport::mean, armnn::Mean, armnn::MemCopy, armnn::MemImport, armnn::Merge, armnn::Minimum, armnn::Multiplication, armnn::Normalization, ILayerSupport::numDetections, ILayerSupport::output, armnn::Output, ILayerSupport::output0, ILayerSupport::output1, ILayerSupport::outputs, ILayerSupport::outputStateIn, ILayerSupport::outputStateOut, armnn::Pad, ILayerSupport::paramsInfo, armnn::Permute, armnn::Pooling2d, armnn::Pooling3d, armnn::PreCompiled, armnn::Prelu, ILayerSupport::previousCellStateIn, ILayerSupport::previousOutputIn, armnn::QLstm, armnn::Quantize, armnn::QuantizedLstm, armnn::Rank, ILayerSupport::reasonIfUnsupported, armnn::Reduce, armnn::Reshape, armnn::Resize, ILayerSupport::scores, ILayerSupport::scratchBuffer, armnn::Shape, armnn::Slice, armnn::Softmax, armnn::SpaceToBatchNd, armnn::SpaceToDepth, armnn::Splitter, armnn::Stack, armnn::StandIn, armnn::StridedSlice, armnn::Subtraction, armnn::Switch, armnn::Transpose, armnn::TransposeConvolution2d, armnn::UnidirectionalSequenceLstm, armnn::Unmap, OptionalReferenceSwitch< std::is_reference< T >::value, T >::value(), ILayerSupport::var, and ILayerSupport::weights.
Referenced by ILayerSupport::~ILayerSupport().
 {
     switch (type)
     {
         case LayerType::Activation:
             return IsActivationSupported(infos[0],
                                          infos[1],
                                          *(PolymorphicDowncast<const ActivationDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Addition:
             return IsAdditionSupported(infos[0],
                                        infos[1],
                                        infos[2],
                                        reasonIfUnsupported);
         case LayerType::ArgMinMax:
             return IsArgMinMaxSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const ArgMinMaxDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::BatchNormalization:
             return IsBatchNormalizationSupported(infos[0],
                                                  infos[1],
                                                  infos[2],
                                                  infos[3],
                                                  infos[4],
                                                  infos[5],
                                                  *(PolymorphicDowncast<const BatchNormalizationDescriptor*>
                                                      (&descriptor)),
                                                  reasonIfUnsupported);
         case LayerType::BatchToSpaceNd:
             return IsBatchToSpaceNdSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const BatchToSpaceNdDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Comparison:
         {
             return IsComparisonSupported(infos[0],
                                          infos[1],
                                          infos[2],
                                          *(PolymorphicDowncast<const ComparisonDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         }
         case LayerType::Concat:
         {
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < (infos.size() - 1); i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             return IsConcatSupported(inputInfos,
                                      infos[infos.size() - 1],
                                      *(PolymorphicDowncast<const OriginsDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         }
         case LayerType::Constant:
             return IsConstantSupported(infos[0],
                                        reasonIfUnsupported);
         case LayerType::ConvertFp16ToFp32:
             return IsConvertFp16ToFp32Supported(infos[0],
                                                 infos[1],
                                                 reasonIfUnsupported);
         case LayerType::ConvertFp32ToFp16:
             return IsConvertFp32ToFp16Supported(infos[0],
                                                 infos[1],
                                                 reasonIfUnsupported);
         case LayerType::Convolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution2d "
                                                "TensorInfos. TensorInfos should be of format: "
                                                "{input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const Convolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsConvolution2dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsConvolution2dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 infos[3],
                                                 reasonIfUnsupported);
             }
         }
         case LayerType::Debug:
             return IsDebugSupported(infos[0],
                                     infos[1],
                                     reasonIfUnsupported);
         case LayerType::DepthToSpace:
             return IsDepthToSpaceSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const DepthToSpaceDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::DepthwiseConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of DepthwiseConvolution2d "
                                                "TensorInfos. TensorInfos should be of format: "
                                                "{input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const DepthwiseConvolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsDepthwiseConvolutionSupported(infos[0],
                                                        infos[1],
                                                        desc,
                                                        infos[2],
                                                        EmptyOptional(),
                                                        reasonIfUnsupported);
             }
             else
             {
                 return IsDepthwiseConvolutionSupported(infos[0],
                                                        infos[1],
                                                        desc,
                                                        infos[2],
                                                        infos[3],
                                                        reasonIfUnsupported);
             }
         }
         case LayerType::Dequantize:
             return IsDequantizeSupported(infos[0],
                                          infos[1],
                                          reasonIfUnsupported);
         case LayerType::DetectionPostProcess:
             return IsDetectionPostProcessSupported(infos[0],
                                                    infos[1],
                                                    infos[2],
                                                    infos[3],
                                                    infos[4],
                                                    infos[5],
                                                    infos[6],
                                                    *(PolymorphicDowncast<const DetectionPostProcessDescriptor*>
                                                        (&descriptor)),
                                                    reasonIfUnsupported);
         case LayerType::Division:
             return IsDivisionSupported(infos[0],
                                        infos[1],
                                        infos[2],
                                        reasonIfUnsupported);
         case LayerType::ElementwiseUnary:
             return IsElementwiseUnarySupported(infos[0],
                                                infos[1],
                                                *(PolymorphicDowncast<const ElementwiseUnaryDescriptor*>
                                                    (&descriptor)),
                                                reasonIfUnsupported);
         case LayerType::FakeQuantization:
             return IsFakeQuantizationSupported(infos[0],
                                                *(PolymorphicDowncast<const FakeQuantizationDescriptor*>
                                                    (&descriptor)),
                                                reasonIfUnsupported);
         case LayerType::Fill:
             return IsFillSupported(infos[0],
                                    infos[1],
                                    *(PolymorphicDowncast<const FillDescriptor*>(&descriptor)),
                                    reasonIfUnsupported);
         case LayerType::Floor:
             return IsFloorSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::FullyConnected:
             return IsFullyConnectedSupported(infos[0],
                                              infos[1],
                                              infos[2],
                                              infos[3],
                                              *(PolymorphicDowncast<const FullyConnectedDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Gather:
             return IsGatherSupported(infos[0],
                                      infos[1],
                                      infos[2],
                                      *(PolymorphicDowncast<const GatherDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Input:
             return IsInputSupported(infos[0], reasonIfUnsupported);
         case LayerType::InstanceNormalization:
             return IsInstanceNormalizationSupported(infos[0],
                                                     infos[1],
                                                     *(PolymorphicDowncast<const InstanceNormalizationDescriptor*>
                                                         (&descriptor)),
                                                     reasonIfUnsupported);
         case LayerType::L2Normalization:
             return IsL2NormalizationSupported(infos[0],
                                               infos[1],
                                               *(PolymorphicDowncast<const L2NormalizationDescriptor*>
                                                   (&descriptor)),
                                               reasonIfUnsupported);
         case LayerType::LogicalBinary:
             return IsLogicalBinarySupported(infos[0],
                                             infos[1],
                                             infos[2],
                                             *(PolymorphicDowncast<const LogicalBinaryDescriptor*>(&descriptor)),
                                             reasonIfUnsupported);
         case LayerType::LogSoftmax:
             return IsLogSoftmaxSupported(infos[0],
                                          infos[1],
                                          *(PolymorphicDowncast<const LogSoftmaxDescriptor*>(&descriptor)),
                                          reasonIfUnsupported);
         case LayerType::Lstm:
             return IsLstmSupported(infos[0],
                                    infos[1],
                                    infos[2],
                                    infos[3],
                                    infos[4],
                                    infos[5],
                                    infos[6],
                                    *(PolymorphicDowncast<const LstmDescriptor*>(&descriptor)),
                                    lstmParamsInfo.value(),
                                    reasonIfUnsupported);
         case LayerType::QLstm:
             return IsQLstmSupported(infos[0],
                                     infos[1],
                                     infos[2],
                                     infos[3],
                                     infos[4],
                                     infos[5],
                                     *(PolymorphicDowncast<const QLstmDescriptor*>(&descriptor)),
                                     lstmParamsInfo.value(),
                                     reasonIfUnsupported);
         case LayerType::Map:
             return true;
         case LayerType::Maximum:
             return IsMaximumSupported(infos[0],
                                       infos[1],
                                       infos[2],
                                       reasonIfUnsupported);
         case LayerType::Mean:
             return IsMeanSupported(infos[0],
                                    infos[1],
                                    *(PolymorphicDowncast<const MeanDescriptor*>(&descriptor)),
                                    reasonIfUnsupported);
         case LayerType::MemCopy:
             return IsMemCopySupported(std::move(infos[0]),
                                       std::move(infos[1]),
                                       reasonIfUnsupported);
         case LayerType::MemImport:
             return IsMemImportSupported(infos[0],
                                         infos[1],
                                         reasonIfUnsupported);
         case LayerType::Merge:
             return IsMergeSupported(infos[0],
                                     infos[1],
                                     infos[2],
                                     reasonIfUnsupported);
         case LayerType::Minimum:
             return IsMinimumSupported(infos[0],
                                       infos[1],
                                       infos[2],
                                       reasonIfUnsupported);
         case LayerType::Multiplication:
             return IsMultiplicationSupported(infos[0],
                                              infos[1],
                                              infos[2],
                                              reasonIfUnsupported);
         case LayerType::Normalization:
             return IsNormalizationSupported(infos[0],
                                             infos[1],
                                             *(PolymorphicDowncast<const NormalizationDescriptor*>(&descriptor)),
                                             reasonIfUnsupported);
         case LayerType::Output:
             return IsOutputSupported(infos[0], reasonIfUnsupported);
         case LayerType::Pad:
             return IsPadSupported(infos[0],
                                   infos[1],
                                   *(PolymorphicDowncast<const PadDescriptor*>(&descriptor)),
                                   reasonIfUnsupported);
         case LayerType::Permute:
             return IsPermuteSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const PermuteDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::Pooling2d:
             return IsPooling2dSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const Pooling2dDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::PreCompiled:
             return IsPreCompiledSupported(infos[0],
                                           *(PolymorphicDowncast<const PreCompiledDescriptor*>(&descriptor)),
                                           reasonIfUnsupported);
         case LayerType::Prelu:
             return IsPreluSupported(infos[0],
                                     infos[1],
                                     infos[2],
                                     reasonIfUnsupported);
         case LayerType::Quantize:
             return IsQuantizeSupported(infos[0],
                                        infos[1],
                                        reasonIfUnsupported);
         case LayerType::QuantizedLstm:
             return IsQuantizedLstmSupported(infos[0],
                                             infos[1],
                                             infos[2],
                                             infos[3],
                                             infos[4],
                                             quantizedLstmParamsInfo.value(),
                                             reasonIfUnsupported);
         case LayerType::Reshape:
             return IsReshapeSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const ReshapeDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::Rank:
             return IsRankSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Resize:
             return IsResizeSupported(infos[0],
                                      infos[1],
                                      *(PolymorphicDowncast<const ResizeDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Reduce:
             return IsReduceSupported(infos[0],
                                      infos[1],
                                      *(PolymorphicDowncast<const ReduceDescriptor*>(&descriptor)),
                                      reasonIfUnsupported);
         case LayerType::Slice:
             return IsSliceSupported(infos[0],
                                     infos[1],
                                     *(PolymorphicDowncast<const SliceDescriptor*>(&descriptor)),
                                     reasonIfUnsupported);
         case LayerType::Softmax:
             return IsSoftmaxSupported(infos[0],
                                       infos[1],
                                       *(PolymorphicDowncast<const SoftmaxDescriptor*>(&descriptor)),
                                       reasonIfUnsupported);
         case LayerType::SpaceToBatchNd:
             return IsSpaceToBatchNdSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const SpaceToBatchNdDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::SpaceToDepth:
             return IsSpaceToDepthSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const SpaceToDepthDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::Splitter:
         {
             std::vector<TensorInfo> outputInfos;
             for (uint32_t i = 1; i < infos.size(); i++)
             {
                 outputInfos.push_back(infos[i]);
             }
             return IsSplitterSupported(infos[0],
                                        {outputInfos.begin(), outputInfos.end()},
                                        *(PolymorphicDowncast<const ViewsDescriptor*>(&descriptor)),
                                        reasonIfUnsupported);
         }
         case LayerType::Stack:
         {
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < infos.size() - 1; i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             return IsStackSupported(inputInfos,
                                     infos[infos.size() - 1],
                                     *(PolymorphicDowncast<const StackDescriptor*>(&descriptor)),
                                     reasonIfUnsupported);
         }
         case LayerType::StandIn:
         {
             auto desc = *(PolymorphicDowncast<const StandInDescriptor*>(&descriptor));
             if (infos.size() != (desc.m_NumInputs + desc.m_NumOutputs))
             {
                 throw InvalidArgumentException("Number of StandIn layer TensorInfos does not equal "
                                                "the combined number of input and output slots assigned "
                                                "to the StandIn descriptor");
             }
             std::vector<const TensorInfo*> inputInfos;
             for (uint32_t i = 0; i < desc.m_NumInputs; i++)
             {
                 inputInfos.push_back(&infos[i]);
             }
             std::vector<const TensorInfo*> outputInfos;
             for (uint32_t i = desc.m_NumInputs; i < infos.size(); i++)
             {
                 outputInfos.push_back(&infos[i]);
             }
             return IsStandInSupported(inputInfos,
                                       outputInfos,
                                       desc,
                                       reasonIfUnsupported);
         }
         case LayerType::StridedSlice:
             return IsStridedSliceSupported(infos[0],
                                            infos[1],
                                            *(PolymorphicDowncast<const StridedSliceDescriptor*>(&descriptor)),
                                            reasonIfUnsupported);
         case LayerType::Subtraction:
             return IsSubtractionSupported(infos[0],
                                           infos[1],
                                           infos[2],
                                           reasonIfUnsupported);
         case LayerType::Switch:
             return IsSwitchSupported(infos[0],
                                      infos[1],
                                      infos[2],
                                      infos[3],
                                      reasonIfUnsupported);
         case LayerType::Transpose:
             return IsTransposeSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const TransposeDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         case LayerType::TransposeConvolution2d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of TransposeConvolution2d "
                                                "TensorInfos. TensorInfos should be of format: "
                                                "{input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const TransposeConvolution2dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsTransposeConvolution2dSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          EmptyOptional(),
                                                          reasonIfUnsupported);
             }
             else
             {
                 return IsTransposeConvolution2dSupported(infos[0],
                                                          infos[1],
                                                          desc,
                                                          infos[2],
                                                          infos[3],
                                                          reasonIfUnsupported);
             }
         }
         case LayerType::Unmap:
             return true;
         case LayerType::Cast:
             return IsCastSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::Shape:
             return IsShapeSupported(infos[0], infos[1], reasonIfUnsupported);
         case LayerType::UnidirectionalSequenceLstm:
         {
             if (infos.size() != 6)
             {
                 throw InvalidArgumentException("Invalid number of TransposeConvolution2d TensorInfos. TensorInfos "
                                                "should be of format: {input, outputStateIn, cellStateIn, "
                                                "hiddenStateOutputVal, cellStateOutputVal, output}");
             }
             auto desc = *(PolymorphicDowncast<const UnidirectionalSequenceLstmDescriptor*>(&descriptor));
             return IsUnidirectionalSequenceLstmSupported(infos[0],
                                                          infos[1],
                                                          infos[2],
                                                          infos[3],
                                                          infos[4],
                                                          infos[5],
                                                          desc,
                                                          lstmParamsInfo.value(),
                                                          reasonIfUnsupported);
         }
         case LayerType::ChannelShuffle:
             return IsChannelShuffleSupported(infos[0],
                                              infos[1],
                                              *(PolymorphicDowncast<const ChannelShuffleDescriptor*>(&descriptor)),
                                              reasonIfUnsupported);
         case LayerType::Convolution3d:
         {
             if (infos.size() != 4)
             {
                 throw InvalidArgumentException("Invalid number of Convolution3d "
                                                "TensorInfos. TensorInfos should be of format: "
                                                "{input, output, weights, biases}.");
             }
             auto desc = *(PolymorphicDowncast<const Convolution3dDescriptor*>(&descriptor));
             if (infos[3] == TensorInfo())
             {
                 return IsConvolution3dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 EmptyOptional(),
                                                 reasonIfUnsupported);
             }
             else
             {
                 return IsConvolution3dSupported(infos[0],
                                                 infos[1],
                                                 desc,
                                                 infos[2],
                                                 infos[3],
                                                 reasonIfUnsupported);
             }
         }
         case LayerType::Pooling3d:
             return IsPooling3dSupported(infos[0],
                                         infos[1],
                                         *(PolymorphicDowncast<const Pooling3dDescriptor*>(&descriptor)),
                                         reasonIfUnsupported);
         default:
             return false;
     }
 }
Member Data Documentation
alpha
const TensorInfo& alpha
Definition at line 392 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
anchors
const TensorInfo const TensorInfo& anchors
Definition at line 172 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
beta
const TensorInfo const TensorInfo const TensorInfo const TensorInfo& beta
Definition at line 62 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
biases [1/5]
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional< TensorInfo > & biases
Definition at line 125 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
biases [2/5]
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional<TensorInfo>& biases
Definition at line 134 of file ILayerSupport.hpp.
biases [3/5]
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional<TensorInfo>& biases
Definition at line 157 of file ILayerSupport.hpp.
biases [4/5]
const TensorInfo const TensorInfo const TensorInfo& biases
Definition at line 227 of file ILayerSupport.hpp.
biases [5/5]
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional<TensorInfo>& biases
Definition at line 532 of file ILayerSupport.hpp.
cellStateIn
const TensorInfo const TensorInfo & cellStateIn
Definition at line 286 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
cellStateOut [1/3]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo & cellStateOut
Definition at line 286 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
cellStateOut [2/3]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo& cellStateOut
Definition at line 405 of file ILayerSupport.hpp.
cellStateOut [3/3]
const TensorInfo const TensorInfo const TensorInfo& cellStateOut
Definition at line 417 of file ILayerSupport.hpp.
descriptor [1/41]
const TensorInfo const ElementwiseUnaryDescriptor & descriptor
Definition at line 41 of file ILayerSupport.hpp.
Referenced by TosaRefLayerSupport::IsLayerSupported(), RefLayerSupport::IsLayerSupported(), LayerSupportBase::IsLayerSupported(), ClLayerSupport::IsLayerSupported(), ILayerSupport::IsLayerSupported(), armnn::IsLayerTypeSupported(), ClLayerSupport::~ClLayerSupport(), ILayerSupport::~ILayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
descriptor [2/41]
const TensorInfo const ArgMinMaxDescriptor& descriptor
Definition at line 55 of file ILayerSupport.hpp.
descriptor [3/41]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor& descriptor
Definition at line 62 of file ILayerSupport.hpp.
descriptor [4/41]
const TensorInfo const BatchToSpaceNdDescriptor& descriptor
Definition at line 73 of file ILayerSupport.hpp.
descriptor [5/41]
const TensorInfo const ChannelShuffleDescriptor& descriptor
Definition at line 86 of file ILayerSupport.hpp.
descriptor [6/41]
const TensorInfo const TensorInfo const ComparisonDescriptor& descriptor
Definition at line 93 of file ILayerSupport.hpp.
descriptor [7/41]
const TensorInfo const Convolution2dDescriptor& descriptor
Definition at line 125 of file ILayerSupport.hpp.
descriptor [8/41]
const TensorInfo const Convolution3dDescriptor& descriptor
Definition at line 134 of file ILayerSupport.hpp.
descriptor [9/41]
const TensorInfo const DepthToSpaceDescriptor& descriptor
Definition at line 149 of file ILayerSupport.hpp.
descriptor [10/41]
const TensorInfo const DepthwiseConvolution2dDescriptor& descriptor
Definition at line 157 of file ILayerSupport.hpp.
descriptor [11/41]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor& descriptor
Definition at line 172 of file ILayerSupport.hpp.
descriptor [12/41]
const TensorInfo const ElementwiseUnaryDescriptor& descriptor
Definition at line 201 of file ILayerSupport.hpp.
descriptor [13/41]
const FakeQuantizationDescriptor& descriptor
Definition at line 208 of file ILayerSupport.hpp.
descriptor [14/41]
const TensorInfo const FillDescriptor& descriptor
Definition at line 214 of file ILayerSupport.hpp.
descriptor [15/41]
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor& descriptor
Definition at line 227 of file ILayerSupport.hpp.
descriptor [16/41]
const TensorInfo const TensorInfo const GatherDescriptor& descriptor
Definition at line 236 of file ILayerSupport.hpp.
descriptor [17/41]
const TensorInfo const InstanceNormalizationDescriptor& descriptor
Definition at line 250 of file ILayerSupport.hpp.
descriptor [18/41]
const TensorInfo const L2NormalizationDescriptor& descriptor
Definition at line 257 of file ILayerSupport.hpp.
descriptor [19/41]
const TensorInfo const TensorInfo const LogicalBinaryDescriptor& descriptor
Definition at line 264 of file ILayerSupport.hpp.
descriptor [20/41]
const TensorInfo const LogSoftmaxDescriptor& descriptor
Definition at line 279 of file ILayerSupport.hpp.
descriptor [21/41]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor& descriptor
Definition at line 286 of file ILayerSupport.hpp.
descriptor [22/41]
const TensorInfo const MeanDescriptor& descriptor
Definition at line 306 of file ILayerSupport.hpp.
descriptor [23/41]
const TensorInfo const NormalizationDescriptor& descriptor
Definition at line 346 of file ILayerSupport.hpp.
descriptor [24/41]
const TensorInfo const PadDescriptor& descriptor
Definition at line 358 of file ILayerSupport.hpp.
descriptor [25/41]
const TensorInfo const PermuteDescriptor& descriptor
Definition at line 365 of file ILayerSupport.hpp.
descriptor [26/41]
const TensorInfo const Pooling2dDescriptor& descriptor
Definition at line 372 of file ILayerSupport.hpp.
descriptor [27/41]
const TensorInfo const Pooling3dDescriptor& descriptor
Definition at line 379 of file ILayerSupport.hpp.
descriptor [28/41]
const PreCompiledDescriptor& descriptor
Definition at line 386 of file ILayerSupport.hpp.
descriptor [29/41]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor& descriptor
Definition at line 405 of file ILayerSupport.hpp.
descriptor [30/41]
const TensorInfo const ReduceDescriptor& descriptor
Definition at line 433 of file ILayerSupport.hpp.
descriptor [31/41]
const TensorInfo const ReshapeDescriptor& descriptor
Definition at line 440 of file ILayerSupport.hpp.
descriptor [32/41]
const TensorInfo const ResizeDescriptor& descriptor
Definition at line 447 of file ILayerSupport.hpp.
descriptor [33/41]
const TensorInfo const SliceDescriptor& descriptor
Definition at line 460 of file ILayerSupport.hpp.
descriptor [34/41]
const TensorInfo const SoftmaxDescriptor& descriptor
Definition at line 467 of file ILayerSupport.hpp.
descriptor [35/41]
const TensorInfo const SpaceToBatchNdDescriptor& descriptor
Definition at line 474 of file ILayerSupport.hpp.
descriptor [36/41]
const TensorInfo const SpaceToDepthDescriptor& descriptor
Definition at line 481 of file ILayerSupport.hpp.
descriptor [37/41]
const std::vector<std::reference_wrapper<TensorInfo> > const ViewsDescriptor& descriptor
Definition at line 488 of file ILayerSupport.hpp.
descriptor [38/41]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor& descriptor
Definition at line 509 of file ILayerSupport.hpp.
descriptor [39/41]
const TensorInfo const TransposeConvolution2dDescriptor& descriptor
Definition at line 532 of file ILayerSupport.hpp.
descriptor [40/41]
const TensorInfo const TransposeDescriptor& descriptor
Definition at line 541 of file ILayerSupport.hpp.
descriptor [41/41]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor& descriptor
Definition at line 549 of file ILayerSupport.hpp.
detectionBoxes
const TensorInfo const TensorInfo const TensorInfo& detectionBoxes
Definition at line 172 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
detectionClasses
const TensorInfo const TensorInfo const TensorInfo const TensorInfo& detectionClasses
Definition at line 172 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
detectionScores
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo& detectionScores
Definition at line 172 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
gamma
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo& gamma
Definition at line 62 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
input1
const TensorInfo & input1
Definition at line 48 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
mean
const TensorInfo const TensorInfo& mean
Definition at line 62 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
numDetections
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo& numDetections
Definition at line 172 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
ouput
const TensorInfo const TensorInfo& ouput
Definition at line 332 of file ILayerSupport.hpp.
Referenced by ClLayerSupport::~ClLayerSupport().
output [1/6]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo & output
Definition at line 41 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::IsSplitterSupported(), NeonLayerSupport::IsSplitterSupported(), RefLayerSupport::IsSplitterSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
output [2/6]
const TensorInfo const TensorInfo& output
Definition at line 48 of file ILayerSupport.hpp.
output [3/6]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo& output
Definition at line 286 of file ILayerSupport.hpp.
output [4/6]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo& output
Definition at line 405 of file ILayerSupport.hpp.
output [5/6]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo& output
Definition at line 417 of file ILayerSupport.hpp.
output [6/6]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo& output
Definition at line 509 of file ILayerSupport.hpp.
output0
const TensorInfo const TensorInfo& output0
Definition at line 523 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
output1
const TensorInfo const TensorInfo const TensorInfo& output1
Definition at line 523 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
outputs
const std::vector<std::reference_wrapper<TensorInfo> >& outputs
Definition at line 488 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::IsSplitterSupported(), NeonLayerSupport::IsSplitterSupported(), RefLayerSupport::IsSplitterSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
outputStateIn
const TensorInfo & outputStateIn
Definition at line 286 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
outputStateOut [1/2]
const TensorInfo const TensorInfo const TensorInfo & outputStateOut
Definition at line 286 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
outputStateOut [2/2]
const TensorInfo const TensorInfo const TensorInfo& outputStateOut
Definition at line 405 of file ILayerSupport.hpp.
paramsInfo [1/4]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo& paramsInfo
Definition at line 286 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
paramsInfo [2/4]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo& paramsInfo
Definition at line 405 of file ILayerSupport.hpp.
paramsInfo [3/4]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo& paramsInfo
Definition at line 417 of file ILayerSupport.hpp.
paramsInfo [4/4]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo& paramsInfo
Definition at line 549 of file ILayerSupport.hpp.
previousCellStateIn [1/2]
const TensorInfo const TensorInfo& previousCellStateIn
Definition at line 405 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
previousCellStateIn [2/2]
const TensorInfo& previousCellStateIn
Definition at line 417 of file ILayerSupport.hpp.
previousOutputIn [1/2]
const TensorInfo& previousOutputIn
Definition at line 405 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
previousOutputIn [2/2]
const TensorInfo const TensorInfo& previousOutputIn
Definition at line 417 of file ILayerSupport.hpp.
reasonIfUnsupported [1/47]
const TensorInfo const TensorInfo Optional< std::string & > reasonIfUnsupported = EmptyOptional()) const
Definition at line 43 of file ILayerSupport.hpp.
Referenced by RefLayerSupport::IsLayerSupported(), ClLayerSupport::IsLayerSupported(), ILayerSupport::IsLayerSupported(), armnn::IsLayerTypeSupported(), ClLayerSupport::~ClLayerSupport(), ILayerSupport::~ILayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
reasonIfUnsupported [2/47]
const TensorInfo const TensorInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 50 of file ILayerSupport.hpp.
reasonIfUnsupported [3/47]
const TensorInfo const ArgMinMaxDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 57 of file ILayerSupport.hpp.
reasonIfUnsupported [4/47]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const BatchNormalizationDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 68 of file ILayerSupport.hpp.
reasonIfUnsupported [5/47]
const TensorInfo const BatchToSpaceNdDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 75 of file ILayerSupport.hpp.
reasonIfUnsupported [6/47]
const TensorInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 81 of file ILayerSupport.hpp.
reasonIfUnsupported [7/47]
const TensorInfo const ChannelShuffleDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 88 of file ILayerSupport.hpp.
reasonIfUnsupported [8/47]
const TensorInfo const TensorInfo const ComparisonDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 96 of file ILayerSupport.hpp.
reasonIfUnsupported [9/47]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsConcatSupported(const std Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 108 of file ILayerSupport.hpp.
reasonIfUnsupported [10/47]
const TensorInfo const Convolution2dDescriptor const TensorInfo const Optional<TensorInfo> Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 129 of file ILayerSupport.hpp.
reasonIfUnsupported [11/47]
const TensorInfo const Convolution3dDescriptor const TensorInfo const Optional<TensorInfo> Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 138 of file ILayerSupport.hpp.
reasonIfUnsupported [12/47]
const TensorInfo const DepthToSpaceDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 151 of file ILayerSupport.hpp.
reasonIfUnsupported [13/47]
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo const Optional<TensorInfo> Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 161 of file ILayerSupport.hpp.
reasonIfUnsupported [14/47]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const DetectionPostProcessDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 179 of file ILayerSupport.hpp.
reasonIfUnsupported [15/47]
const TensorInfo const ElementwiseUnaryDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 203 of file ILayerSupport.hpp.
reasonIfUnsupported [16/47]
const FakeQuantizationDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 209 of file ILayerSupport.hpp.
reasonIfUnsupported [17/47]
const TensorInfo const FillDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 216 of file ILayerSupport.hpp.
reasonIfUnsupported [18/47]
const TensorInfo const TensorInfo const TensorInfo const FullyConnectedDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 231 of file ILayerSupport.hpp.
reasonIfUnsupported [19/47]
const TensorInfo const TensorInfo const GatherDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 239 of file ILayerSupport.hpp.
reasonIfUnsupported [20/47]
Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 244 of file ILayerSupport.hpp.
reasonIfUnsupported [21/47]
const TensorInfo const InstanceNormalizationDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 252 of file ILayerSupport.hpp.
reasonIfUnsupported [22/47]
const TensorInfo const L2NormalizationDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 259 of file ILayerSupport.hpp.
reasonIfUnsupported [23/47]
const TensorInfo const TensorInfo const LogicalBinaryDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 267 of file ILayerSupport.hpp.
reasonIfUnsupported [24/47]
const TensorInfo const LogSoftmaxDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 281 of file ILayerSupport.hpp.
reasonIfUnsupported [25/47]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 294 of file ILayerSupport.hpp.
reasonIfUnsupported [26/47]
const TensorInfo const MeanDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 308 of file ILayerSupport.hpp.
reasonIfUnsupported [27/47]
const TensorInfo const NormalizationDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 348 of file ILayerSupport.hpp.
reasonIfUnsupported [28/47]
const TensorInfo const PadDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 360 of file ILayerSupport.hpp.
reasonIfUnsupported [29/47]
const TensorInfo const PermuteDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 367 of file ILayerSupport.hpp.
reasonIfUnsupported [30/47]
const TensorInfo const Pooling2dDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 374 of file ILayerSupport.hpp.
reasonIfUnsupported [31/47]
const TensorInfo const Pooling3dDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 381 of file ILayerSupport.hpp.
reasonIfUnsupported [32/47]
const PreCompiledDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 387 of file ILayerSupport.hpp.
reasonIfUnsupported [33/47]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QLstmDescriptor const LstmInputParamsInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 412 of file ILayerSupport.hpp.
reasonIfUnsupported [34/47]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const QuantizedLstmInputParamsInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 422 of file ILayerSupport.hpp.
reasonIfUnsupported [35/47]
const TensorInfo const ReduceDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 435 of file ILayerSupport.hpp.
reasonIfUnsupported [36/47]
const TensorInfo const ReshapeDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 442 of file ILayerSupport.hpp.
reasonIfUnsupported [37/47]
const TensorInfo const ResizeDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 449 of file ILayerSupport.hpp.
reasonIfUnsupported [38/47]
const TensorInfo const SliceDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 462 of file ILayerSupport.hpp.
reasonIfUnsupported [39/47]
const TensorInfo const SoftmaxDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 469 of file ILayerSupport.hpp.
reasonIfUnsupported [40/47]
const TensorInfo const SpaceToBatchNdDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 476 of file ILayerSupport.hpp.
reasonIfUnsupported [41/47]
const TensorInfo const SpaceToDepthDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 483 of file ILayerSupport.hpp.
reasonIfUnsupported [42/47]
const std::vector<std::reference_wrapper<TensorInfo> > const ViewsDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 490 of file ILayerSupport.hpp.
reasonIfUnsupported [43/47]
ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStackSupported(const std ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("This method is deprecated. " "Use ABI Stable IsLayerSupported accepting LayerType argument instead.", "23.08") virtual bool IsStandInSupported(const std const TensorInfo const StridedSliceDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 511 of file ILayerSupport.hpp.
reasonIfUnsupported [44/47]
const TensorInfo const TensorInfo const TensorInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 526 of file ILayerSupport.hpp.
reasonIfUnsupported [45/47]
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo const Optional<TensorInfo> Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 536 of file ILayerSupport.hpp.
reasonIfUnsupported [46/47]
const TensorInfo const TransposeDescriptor Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 543 of file ILayerSupport.hpp.
reasonIfUnsupported [47/47]
const TensorInfo const TensorInfo const TensorInfo const TensorInfo const TensorInfo const LstmDescriptor const LstmInputParamsInfo Optional<std::string&> reasonIfUnsupported = EmptyOptional()) const
Definition at line 556 of file ILayerSupport.hpp.
scores
const TensorInfo& scores
Definition at line 172 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported().
scratchBuffer
const TensorInfo const TensorInfo const TensorInfo& scratchBuffer
Definition at line 286 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
var
const TensorInfo const TensorInfo const TensorInfo& var
Definition at line 62 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
weights [1/5]
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo & weights
Definition at line 125 of file ILayerSupport.hpp.
Referenced by ILayerSupport::IsLayerSupported(), ClLayerSupport::~ClLayerSupport(), and NeonLayerSupport::~NeonLayerSupport().
weights [2/5]
const TensorInfo const Convolution3dDescriptor const TensorInfo& weights
Definition at line 134 of file ILayerSupport.hpp.
weights [3/5]
const TensorInfo const DepthwiseConvolution2dDescriptor const TensorInfo& weights
Definition at line 157 of file ILayerSupport.hpp.
weights [4/5]
const TensorInfo const TensorInfo& weights
Definition at line 227 of file ILayerSupport.hpp.
weights [5/5]
const TensorInfo const TransposeConvolution2dDescriptor const TensorInfo& weights
Definition at line 532 of file ILayerSupport.hpp.
The documentation for this class was generated from the following files:
include/armnn/backends/ILayerSupport.hpp
src/armnn/ILayerSupport.cpp