ArmNN: RefReshapeWorkload Class Reference
RefReshapeWorkload Class Reference
#include <RefReshapeWorkload.hpp>
Public Member Functions
void Execute () const override
void ExecuteAsync (ExecutionData &executionData) override
Public Member Functions inherited from RefBaseWorkload< ReshapeQueueDescriptor >
RefBaseWorkload (const ReshapeQueueDescriptor &descriptor, const WorkloadInfo &info)
virtual bool SupportsTensorHandleReplacement () const override
void ReplaceInputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
void ReplaceOutputTensorHandle (ITensorHandle *tensorHandle, unsigned int slot) override
Public Member Functions inherited from BaseWorkload< ReshapeQueueDescriptor >
BaseWorkload (const ReshapeQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (ExecutionData &executionData) override
void PostAllocationConfigure () override
const ReshapeQueueDescriptor & GetData () const
arm::pipe::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
virtual armnn::Optional< armnn::MemoryRequirements > GetMemoryRequirements ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ReshapeQueueDescriptor >
ReshapeQueueDescriptor m_Data
const arm::pipe::ProfilingGuid m_Guid
Detailed Description
Definition at line 14 of file RefReshapeWorkload.hpp.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 15 of file RefReshapeWorkload.cpp.
References BaseWorkload< ReshapeQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, and QueueDescriptor::m_Outputs.
Referenced by RefReshapeWorkload::ExecuteAsync().
 {
     Execute(m_Data.m_Inputs, m_Data.m_Outputs);
 }
ExecuteAsync()
void ExecuteAsync (ExecutionData & executionData) override virtual
Implements IWorkload.
Definition at line 20 of file RefReshapeWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, armnn::CpuRef, RefReshapeWorkload::Execute(), TensorInfo::GetNumBytes(), armnn::GetTensorInfo(), ExecutionData::m_Data, WorkingMemDescriptor::m_Inputs, and WorkingMemDescriptor::m_Outputs.
 {
     WorkingMemDescriptor* workingMemDescriptor = static_cast<WorkingMemDescriptor*>(executionData.m_Data);
     Execute(workingMemDescriptor->m_Inputs, workingMemDescriptor->m_Outputs);
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefReshapeWorkload.hpp
src/backends/reference/workloads/RefReshapeWorkload.cpp