ArmNN: PermuteQueueDescriptor Struct Reference
PermuteQueueDescriptor Struct Reference
#include <WorkloadData.hpp>
Public Member Functions
void Validate (const WorkloadInfo &workloadInfo) const
Public Member Functions inherited from QueueDescriptorWithParameters< PermuteDescriptor >
virtual ~QueueDescriptorWithParameters ()=default
Public Member Functions inherited from QueueDescriptor
virtual ~QueueDescriptor ()=default
void ValidateTensorNumDimensions (const TensorInfo &tensor, std::string const &descName, unsigned int numDimensions, std::string const &tensorName) const
void ValidateTensorNumDimNumElem (const TensorInfo &tensorInfo, unsigned int numDimension, unsigned int numElements, std::string const &tensorName) const
void ValidateInputsOutputs (const std::string &descName, unsigned int numExpectedIn, unsigned int numExpectedOut) const
template<typename T >
const T * GetAdditionalInformation () const
Additional Inherited Members
Public Attributes inherited from QueueDescriptorWithParameters< PermuteDescriptor >
PermuteDescriptor m_Parameters
Public Attributes inherited from QueueDescriptor
std::vector< ITensorHandle * > m_Inputs
std::vector< ITensorHandle * > m_Outputs
void * m_AdditionalInfoObject
bool m_AllowExpandedDims = false
Protected Member Functions inherited from QueueDescriptorWithParameters< PermuteDescriptor >
QueueDescriptorWithParameters ()=default
QueueDescriptorWithParameters (QueueDescriptorWithParameters const &)=default
QueueDescriptorWithParameters & operator= (QueueDescriptorWithParameters const &)=default
Protected Member Functions inherited from QueueDescriptor
QueueDescriptor ()
QueueDescriptor (QueueDescriptor const &)=default
QueueDescriptor & operator= (QueueDescriptor const &)=default
Detailed Description
Definition at line 186 of file WorkloadData.hpp.
Member Function Documentation
Validate()
void Validate (const WorkloadInfo & workloadInfo) const
Definition at line 1516 of file WorkloadData.cpp.
References TensorInfo::GetShape(), PermutationVector::GetSize(), WorkloadInfo::m_InputTensorInfos, WorkloadInfo::m_OutputTensorInfos, and QueueDescriptor::ValidateTensorNumDimensions().
 {
     const std::string descriptorName{"PermuteQueueDescriptor"};
     ValidateNumInputs(workloadInfo,  descriptorName, 1);
     ValidateNumOutputs(workloadInfo, descriptorName, 1);
     const PermutationVector& mapping = m_Parameters.m_DimMappings;
     const TensorInfo& inputTensorInfo  = workloadInfo.m_InputTensorInfos[0];
     const TensorInfo& outputTensorInfo = workloadInfo.m_OutputTensorInfos[0];
     ValidateTensorNumDimensions(inputTensorInfo,  descriptorName, mapping.GetSize(), "input");
     ValidateTensorNumDimensions(outputTensorInfo, descriptorName, mapping.GetSize(), "output");
     for (unsigned int i = 0u; i < mapping.GetSize(); ++i)
     {
         if (inputTensorInfo.GetShape()[i] != outputTensorInfo.GetShape()[mapping[i]])
         {
             throw InvalidArgumentException(descriptorName + ": src dimension " + to_string(i) +
                                            " (=" + to_string(inputTensorInfo.GetShape()[i]) + ") " +
                                            "must match dst dimension " + to_string(mapping[i]) +
                                            " (=" + to_string(outputTensorInfo.GetShape()[mapping[i]]) + ")");
         }
     }
     ValidateTensorDataTypesMatch(inputTensorInfo, outputTensorInfo, descriptorName, "input", "output");
 }
The documentation for this struct was generated from the following files:
include/armnn/backends/WorkloadData.hpp
src/backends/backendsCommon/WorkloadData.cpp