ArmNN: StringifyLayerParameters< Pooling3dDescriptor > Struct Template Reference
StringifyLayerParameters< Pooling3dDescriptor > Struct Template Reference
#include <SerializeLayerParameters.hpp>
Static Public Member Functions
static void Serialize (ParameterStringifyFunction &fn, const Pooling3dDescriptor &desc)
Detailed Description
template<>
struct armnn::StringifyLayerParameters< Pooling3dDescriptor >
Definition at line 137 of file SerializeLayerParameters.hpp.
Member Function Documentation
Serialize()
void Serialize (ParameterStringifyFunction & fn, const Pooling3dDescriptor & desc) static
Definition at line 349 of file SerializeLayerParameters.cpp.
References armnn::GetDataLayoutName(), armnn::GetOutputShapeRoundingAsCString(), armnn::GetPaddingMethodAsCString(), armnn::GetPoolingAlgorithmAsCString(), Pooling3dDescriptor::m_DataLayout, Pooling3dDescriptor::m_OutputShapeRounding, Pooling3dDescriptor::m_PadBack, Pooling3dDescriptor::m_PadBottom, Pooling3dDescriptor::m_PaddingMethod, Pooling3dDescriptor::m_PadFront, Pooling3dDescriptor::m_PadLeft, Pooling3dDescriptor::m_PadRight, Pooling3dDescriptor::m_PadTop, Pooling3dDescriptor::m_PoolDepth, Pooling3dDescriptor::m_PoolHeight, Pooling3dDescriptor::m_PoolType, Pooling3dDescriptor::m_PoolWidth, Pooling3dDescriptor::m_StrideX, Pooling3dDescriptor::m_StrideY, and Pooling3dDescriptor::m_StrideZ.
 {
     fn("Type", GetPoolingAlgorithmAsCString(desc.m_PoolType));
     {
         std::stringstream ss;
         ss << "(" << desc.m_PadTop    << "," << desc.m_PadLeft
            << "," << desc.m_PadBottom << "," << desc.m_PadRight
            << "," << desc.m_PadFront  << "," << desc.m_PadBack << ")";
         fn("Padding(T,L,B,R,F,B)", ss.str());
     }
     {
         std::stringstream ss;
         ss << "(" << desc.m_PoolWidth    << "," << desc.m_PoolHeight << "," << desc.m_PoolDepth << ")";
         fn("(Width,Height,Depth)", ss.str());
     }
     {
         std::stringstream ss;
         ss << "(" << desc.m_StrideX <<  "," << desc.m_StrideY << "," << desc.m_StrideZ << ")";
         fn("Stride(X,Y,Z)", ss.str());
     }
     fn("OutputShapeRounding", GetOutputShapeRoundingAsCString(desc.m_OutputShapeRounding));
     fn("PaddingMethod", GetPaddingMethodAsCString(desc.m_PaddingMethod));
     fn("DataLayout", GetDataLayoutName(desc.m_DataLayout));
 }
The documentation for this struct was generated from the following files:
src/armnn/SerializeLayerParameters.hpp
src/armnn/SerializeLayerParameters.cpp