ArmNN: src/armnnSerializer/test/ComparisonSerializationTests.cpp File Reference
ComparisonSerializationTests.cpp File Reference
#include "../Serializer.hpp"
#include "SerializerTestUtils.hpp"
#include <armnn/Descriptors.hpp>
#include <armnn/INetwork.hpp>
#include <armnn/IRuntime.hpp>
#include <armnnDeserializer/IDeserializer.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (SerializeEqual)
BOOST_AUTO_TEST_CASE (SerializeGreater)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (SerializeEqual)
Definition at line 85 of file ComparisonSerializationTests.cpp.
References armnn::Boolean, DeserializeNetwork(), armnn::Equal, armnn::Float32, and SerializeNetwork().
 {
     const std::string layerName("equal");
     const armnn::TensorShape shape{2, 1, 2, 4};
     const armnn::TensorInfo inputInfo  = armnn::TensorInfo(shape, armnn::DataType::Float32);
     const armnn::TensorInfo outputInfo = armnn::TensorInfo(shape, armnn::DataType::Boolean);
     armnn::ComparisonDescriptor descriptor (armnn::ComparisonOperation::Equal);
     ComparisonModel model(layerName, inputInfo, outputInfo, descriptor);
     armnn::INetworkPtr deserializedNetwork = DeserializeNetwork(SerializeNetwork(*model.m_network));
     BOOST_CHECK(deserializedNetwork);
     ComparisonLayerVerifier verifier(layerName, { inputInfo, inputInfo }, { outputInfo }, descriptor);
     deserializedNetwork->ExecuteStrategy(verifier);
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (SerializeGreater)
Definition at line 104 of file ComparisonSerializationTests.cpp.
References armnn::Boolean, BOOST_AUTO_TEST_SUITE_END(), DeserializeNetwork(), armnn::Float32, armnn::Greater, and SerializeNetwork().
 {
     const std::string layerName("greater");
     const armnn::TensorShape shape{2, 1, 2, 4};
     const armnn::TensorInfo inputInfo  = armnn::TensorInfo(shape, armnn::DataType::Float32);
     const armnn::TensorInfo outputInfo = armnn::TensorInfo(shape, armnn::DataType::Boolean);
     armnn::ComparisonDescriptor descriptor (armnn::ComparisonOperation::Greater);
     ComparisonModel model(layerName, inputInfo, outputInfo, descriptor);
     armnn::INetworkPtr deserializedNetwork = DeserializeNetwork(SerializeNetwork(*model.m_network));
     BOOST_CHECK(deserializedNetwork);
     ComparisonLayerVerifier verifier(layerName, { inputInfo, inputInfo }, { outputInfo }, descriptor);
     deserializedNetwork->ExecuteStrategy(verifier);
 }