ArmNN: src/backends/backendsCommon/test/layerTests/ConcatTestImpl.hpp File Reference
ConcatTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <BFloat16.hpp>
#include <Half.hpp>
#include <ResolveType.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 3 > ConcatDifferentInputOutputQParamTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< float, 3 > ConcatTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::BFloat16, 3 > ConcatBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 3 > ConcatFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > ConcatUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint16_t, 3 > ConcatUint16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > ConcatUint8DifferentQParamsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 1 > Concat1dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > Concat2dDim0Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > Concat2dDim1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > Concat2dDim0DiffInputDimsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > Concat2dDim1DiffInputDimsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > Concat3dDim0Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > Concat3dDim1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > Concat3dDim2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< float, 3 > Concat3dDim0DiffInputDimsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > Concat3dDim1DiffInputDimsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > Concat3dDim2DiffInputDimsTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< float, 4 > Concat4dDim0Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > Concat4dDim1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > Concat4dDim2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > Concat4dDim3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< float, 4 > Concat4dDiffShapeDim0Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > Concat4dDiffShapeDim1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > Concat4dDiffShapeDim2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > Concat4dDiffShapeDim3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< uint8_t, 4 > Concat4dDim0Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > Concat4dDim1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > Concat4dDim2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > Concat4dDim3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< uint8_t, 4 > Concat4dDiffShapeDim0Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > Concat4dDiffShapeDim1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > Concat4dDiffShapeDim2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > Concat4dDiffShapeDim3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< uint8_t, 1 > Concat1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > Concat2dDim0Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > Concat2dDim1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > Concat2dDim0DiffInputDimsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > Concat2dDim1DiffInputDimsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > Concat3dDim0Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > Concat3dDim1Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > Concat3dDim2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< uint8_t, 3 > Concat3dDim0DiffInputDimsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > Concat3dDim1DiffInputDimsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > Concat3dDim2DiffInputDimsUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< uint8_t, 3 > ConcatDifferentInputOutputQParamUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
LayerTestResult< int16_t, 3 > ConcatDifferentInputOutputQParamInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool useSubtensor)
Function Documentation
Concat1dTest()
LayerTestResult<float, 1> Concat1dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2237 of file ConcatTestImpl.cpp.
 {
     return Concat1dTestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat1dUint8Test()
LayerTestResult<uint8_t, 1> Concat1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2843 of file ConcatTestImpl.cpp.
 {
     return Concat1dTestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat2dDim0DiffInputDimsTest()
LayerTestResult<float, 2> Concat2dDim0DiffInputDimsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2261 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim0DiffInputDimsTestImpl<DataType::Float32>(workloadFactory, memoryManager,
                                                                 tensorHandleFactory, 0.0f, 0);
 }
Concat2dDim0DiffInputDimsUint8Test()
LayerTestResult<uint8_t, 2> Concat2dDim0DiffInputDimsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2867 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim0DiffInputDimsTestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat2dDim0Test()
LayerTestResult<float, 2> Concat2dDim0Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2245 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim0TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat2dDim0Uint8Test()
LayerTestResult<uint8_t, 2> Concat2dDim0Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2851 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim0TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat2dDim1DiffInputDimsTest()
LayerTestResult<float, 2> Concat2dDim1DiffInputDimsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2270 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim1DiffInputDimsTestImpl<DataType::Float32>(workloadFactory,
                                                                 memoryManager,
                                                                 tensorHandleFactory,
                                                                 0.0f,
                                                                 0);
 }
Concat2dDim1DiffInputDimsUint8Test()
LayerTestResult<uint8_t, 2> Concat2dDim1DiffInputDimsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2876 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim1DiffInputDimsTestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat2dDim1Test()
LayerTestResult<float, 2> Concat2dDim1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2253 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim1TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat2dDim1Uint8Test()
LayerTestResult<uint8_t, 2> Concat2dDim1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2859 of file ConcatTestImpl.cpp.
 {
     return Concat2dDim1TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat3dDim0DiffInputDimsTest()
LayerTestResult<float, 3> Concat3dDim0DiffInputDimsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2308 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim0DiffInputDimsTestImpl<DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat3dDim0DiffInputDimsUint8Test()
LayerTestResult<uint8_t, 3> Concat3dDim0DiffInputDimsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2911 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim0TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat3dDim0Test()
LayerTestResult<float, 3> Concat3dDim0Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2282 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim0TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat3dDim0Uint8Test()
LayerTestResult<uint8_t, 3> Concat3dDim0Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2885 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim0TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat3dDim1DiffInputDimsTest()
LayerTestResult<float, 3> Concat3dDim1DiffInputDimsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2317 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim1DiffInputDimsTestImpl<DataType::Float32>(workloadFactory, memoryManager,
                                                                 tensorHandleFactory, 0.0f, 0);
 }
Concat3dDim1DiffInputDimsUint8Test()
LayerTestResult<uint8_t, 3> Concat3dDim1DiffInputDimsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2919 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim1DiffInputDimsTestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat3dDim1Test()
LayerTestResult<float, 3> Concat3dDim1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2290 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim1TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat3dDim1Uint8Test()
LayerTestResult<uint8_t, 3> Concat3dDim1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2893 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim1TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat3dDim2DiffInputDimsTest()
LayerTestResult<float, 3> Concat3dDim2DiffInputDimsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2326 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim2DiffInputDimsTestImpl<DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, useSubtensor, 0.0f, 0);
 }
Concat3dDim2DiffInputDimsUint8Test()
LayerTestResult<uint8_t, 3> Concat3dDim2DiffInputDimsUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2928 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim2DiffInputDimsTestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, useSubtensor, 0.5f, -1);
 }
Concat3dDim2Test()
LayerTestResult<float, 3> Concat3dDim2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2298 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim2TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory,
                                                    useSubtensor, 0.0f, 0);
 }
Concat3dDim2Uint8Test()
LayerTestResult<uint8_t, 3> Concat3dDim2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2901 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim2TestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, useSubtensor, 0.5f, -1);
 }
Concat4dDiffShapeDim0Test()
LayerTestResult<float, 4> Concat4dDiffShapeDim0Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2370 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim0TestImpl<DataType::Float32>(workloadFactory, memoryManager,
                                                             tensorHandleFactory, 0.0f, 0);
 }
Concat4dDiffShapeDim0Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDiffShapeDim0Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2971 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim0TestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat4dDiffShapeDim1Test()
LayerTestResult<float, 4> Concat4dDiffShapeDim1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2379 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim1TestImpl<DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat4dDiffShapeDim1Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDiffShapeDim1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2980 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim1TestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat4dDiffShapeDim2Test()
LayerTestResult<float, 4> Concat4dDiffShapeDim2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2388 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim2TestImpl<DataType::Float32>(workloadFactory, memoryManager,
                                                             tensorHandleFactory, 0.0f, 0);
 }
Concat4dDiffShapeDim2Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDiffShapeDim2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2989 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim2TestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat4dDiffShapeDim3Test()
LayerTestResult<float, 4> Concat4dDiffShapeDim3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2397 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim3TestImpl<DataType::Float32>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, useSubtensor);
 }
Concat4dDiffShapeDim3Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDiffShapeDim3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2998 of file ConcatTestImpl.cpp.
 {
     return Concat4dDiffShapeDim3TestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1, useSubtensor);
 }
Concat4dDim0Test()
LayerTestResult<float, 4> Concat4dDim0Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2336 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim0TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat4dDim0Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDim0Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2938 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim0TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat4dDim1Test()
LayerTestResult<float, 4> Concat4dDim1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2344 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim1TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat4dDim1Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDim1Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2946 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim1TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat4dDim2Test()
LayerTestResult<float, 4> Concat4dDim2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2352 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim2TestImpl<DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
Concat4dDim2Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDim2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2954 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim2TestImpl<DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1);
 }
Concat4dDim3Test()
LayerTestResult<float, 4> Concat4dDim3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2360 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim3TestImpl<DataType::Float32>(workloadFactory, memoryManager,
                                                    tensorHandleFactory, 0.0f, 0, useSubtensor);
 }
Concat4dDim3Uint8Test()
LayerTestResult<uint8_t, 4> Concat4dDim3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 2962 of file ConcatTestImpl.cpp.
 {
     return Concat4dDim3TestImpl<DataType::QAsymmU8>(
         workloadFactory, memoryManager, tensorHandleFactory, 0.5f, -1, useSubtensor);
 }
ConcatBFloat16Test()
LayerTestResult<armnn::BFloat16, 3> ConcatBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2415 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim1TestImpl<DataType::BFloat16>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
ConcatDifferentInputOutputQParamInt16Test()
LayerTestResult<int16_t, 3> ConcatDifferentInputOutputQParamInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
ConcatDifferentInputOutputQParamTest()
LayerTestResult<T, 3> ConcatDifferentInputOutputQParamTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
Definition at line 1952 of file ConcatTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateConcat(), armnn::CreateDescriptorForConcatenation(), ITensorHandleFactory::CreateSubTensorHandle(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), armnn::info, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, ConcatQueueDescriptor::m_ViewOrigins, LayerTestResult< T, n >::output, LayerTestResult< T, n >::outputExpected, and IWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(memoryManager);
     // Defines the tensor descriptors.
     TensorInfo outputTensorInfo({ 3, 6, 3 }, ArmnnType);
     TensorInfo inputTensorInfo1({ 3, 6, 2 }, ArmnnType);
     TensorInfo inputTensorInfo2({ 3, 6, 1 }, ArmnnType);
     std::vector<TensorShape> inputTensorShapes({inputTensorInfo1.GetShape(), inputTensorInfo2.GetShape()});
     // Quantized input1 tensor.
     const float inputScale1 = 0.5f;
     const int32_t inputOffset1 = 5;
     auto input1 = MakeTensor<T, 3>(inputTensorInfo1, std::vector<T>(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36
     }));
     // Quatized input2 tensor.
     const float inputScale2 = 0.2f;
     const int32_t inputOffset2 = 10;
     auto input2 = MakeTensor<T, 3>(inputTensorInfo2, std::vector<T>(
     {
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48,
         49, 50, 51,
         52, 53, 54
     }));
     // Quantized output tensor.
     const float outputScale = 0.1f;
     const int32_t outputOffset = 20;
     LayerTestResult<T, 3> ret(outputTensorInfo);
     ret.outputExpected = MakeTensor<T, 3>(outputTensorInfo, std::vector<T>(
     {
         0,   5,  74,
         10,  15,  76,
         20,  25,  78,
         30,  35,  80,
         40,  45,  82,
         50,  55,  84,
         60,  65,  86,
         70,  75,  88,
         80,  85,  90,
         90,  95,  92,
         100, 105,  94,
         110, 115,  96,
         120, 125,  98,
         130, 135, 100,
         140, 145, 102,
         150, 155, 104,
         160, 165, 106,
         170, 175, 108
     }));
     outputTensorInfo.SetQuantizationScale(outputScale);
     outputTensorInfo.SetQuantizationOffset(outputOffset);
     inputTensorInfo1.SetQuantizationScale(inputScale1);
     inputTensorInfo1.SetQuantizationOffset(inputOffset1);
     inputTensorInfo2.SetQuantizationScale(inputScale2);
     inputTensorInfo2.SetQuantizationOffset(inputOffset2);
     std::vector<unsigned int> wOrigin1 = { 0, 0, 0 }; //Extent of the window is defined by size of input[0].
     ConcatQueueDescriptor::ViewOrigin window1(wOrigin1);
     std::vector<unsigned int> wOrigin2 = { 0, 0, 2 }; //Extent of the window is defined by size of input[1].
     ConcatQueueDescriptor::ViewOrigin window2(wOrigin2);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     bool subTensorsSupported = useSubtensor && workloadFactory.SupportsSubTensors();
     std::unique_ptr<ITensorHandle> inputHandle1 =
             subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo1.GetShape(), wOrigin1.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo1);
     std::unique_ptr<ITensorHandle> inputHandle2 =
             subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo2.GetShape(), wOrigin2.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo2);
     ConcatQueueDescriptor data;
     OriginsDescriptor desc = CreateDescriptorForConcatenation(
             inputTensorShapes.begin(),inputTensorShapes.end(), 2);
     data.m_Parameters = desc;
     WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo1, inputHandle1.get());
     AddInputToWorkload(data, info, inputTensorInfo2, inputHandle2.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_ViewOrigins.push_back(window1);
     data.m_ViewOrigins.push_back(window2);
     std::unique_ptr<IWorkload> workload = workloadFactory.CreateConcat(data, info);
     inputHandle1->Allocate();
     inputHandle2->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle1.get(), &input1[0][0][0]);
     CopyDataToITensorHandle(inputHandle2.get(), &input2[0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0], outputHandle.get());
     return ret;
 }
ConcatDifferentInputOutputQParamUint8Test()
LayerTestResult<uint8_t, 3> ConcatDifferentInputOutputQParamUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool useSubtensor)
ConcatFloat16Test()
LayerTestResult<armnn::Half, 3> ConcatFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2407 of file ConcatTestImpl.cpp.
 {
     return Concat3dDim1TestImpl<DataType::Float16>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
ConcatTest()
LayerTestResult<float, 3> ConcatTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2111 of file ConcatTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateConcat(), ITensorHandleFactory::CreateSubTensorHandle(), ITensorHandleFactory::CreateTensorHandle(), armnn::Float32, armnn::IgnoreUnused(), armnn::info, ConcatQueueDescriptor::m_ViewOrigins, and IWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(memoryManager);
     unsigned int outputWidth = 3;
     unsigned int outputHeight = 6;
     unsigned int outputChannels = 3;
     unsigned int inputWidth1 = 3;
     unsigned int inputHeight1 = 6;
     unsigned int inputChannels1 = 2;
     unsigned int inputWidth2 = 3;
     unsigned int inputHeight2 = 6;
     unsigned int inputChannels2 = 1;
     // Define the tensor descriptors.
     TensorInfo outputTensorInfo({ outputChannels, outputHeight, outputWidth }, DataType::Float32);
     TensorInfo inputTensorInfo1({ inputChannels1, inputHeight1, inputWidth1 }, DataType::Float32);
     TensorInfo inputTensorInfo2({ inputChannels2, inputHeight2, inputWidth2 }, DataType::Float32);
     LayerTestResult<float,3> ret(outputTensorInfo);
     ret.outputExpected = MakeTensor<float, 3>(outputTensorInfo, std::vector<float>(
     {
             1.0f, 2.0f, 3.0f,
             4.0f, 5.0f, 6.0f,
             7.0f, 8.0f, 9.0f,
             10.0f, 11.0f, 12.0f,
             13.0f, 14.0f, 15.0f,
             16.0f, 17.0f, 18.0f,
             19.0f, 20.0f, 21.0f,
             22.0f, 23.0f, 24.0f,
             25.0f, 26.0f, 27.0f,
             28.0f, 29.0f, 30.0f,
             31.0f, 32.0f, 33.0f,
             34.0f, 35.0f, 36.0f,
             37.0f, 38.0f, 39.0f,
             40.0f, 41.0f, 42.0f,
             43.0f, 44.0f, 45.0f,
             46.0f, 47.0f, 48.0f,
             49.0f, 50.0f, 51.0f,
             52.0f, 53.0f, 54.0f,
         })
     );
     auto input1 = MakeTensor<float, 3>(inputTensorInfo1, std::vector<float>(
         {
             1.0f, 2.0f, 3.0f,
             4.0f, 5.0f, 6.0f,
             7.0f, 8.0f, 9.0f,
             10.0f, 11.0f, 12.0f,
             13.0f, 14.0f, 15.0f,
             16.0f, 17.0f, 18.0f,
             19.0f, 20.0f, 21.0f,
             22.0f, 23.0f, 24.0f,
             25.0f, 26.0f, 27.0f,
             28.0f, 29.0f, 30.0f,
             31.0f, 32.0f, 33.0f,
             34.0f, 35.0f, 36.0f,
         })
     );
     auto input2 = MakeTensor<float, 3>(inputTensorInfo2, std::vector<float>(
         {
             37.0f, 38.0f, 39.0f,
             40.0f, 41.0f, 42.0f,
             43.0f, 44.0f, 45.0f,
             46.0f, 47.0f, 48.0f,
             49.0f, 50.0f, 51.0f,
             52.0f, 53.0f, 54.0f,
         })
     );
     std::vector<unsigned int> wOrigin1 = {0, 0, 0}; //Extent of the window is defined by size of input[0].
     ConcatQueueDescriptor::ViewOrigin window1(wOrigin1);
     std::vector<unsigned int> wOrigin2 = {2, 0, 0}; //Extent of the window is defined by size of input[1].
     ConcatQueueDescriptor::ViewOrigin window2(wOrigin2);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     bool subTensorsSupported = workloadFactory.SupportsSubTensors();
     std::unique_ptr<ITensorHandle> inputHandle1 =
         subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo1.GetShape(), wOrigin1.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo1);
     std::unique_ptr<ITensorHandle> inputHandle2  =
         subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo2.GetShape(), wOrigin2.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo2);
     ConcatQueueDescriptor data;
     WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo1, inputHandle1.get());
     AddInputToWorkload(data, info, inputTensorInfo2, inputHandle2.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_ViewOrigins.push_back(window1);
     data.m_ViewOrigins.push_back(window2);
     std::unique_ptr<IWorkload> workload = workloadFactory.CreateConcat(data, info);
     inputHandle1->Allocate();
     inputHandle2->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle1.get(), &input1[0][0][0]);
     CopyDataToITensorHandle(inputHandle2.get(), &input2[0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0], outputHandle.get());
     return ret;
 }
ConcatUint16Test()
LayerTestResult<uint16_t, 3> ConcatUint16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2707 of file ConcatTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateConcat(), ITensorHandleFactory::CreateSubTensorHandle(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), armnn::info, ConcatQueueDescriptor::m_ViewOrigins, LayerTestResult< T, n >::output, LayerTestResult< T, n >::outputExpected, armnn::QSymmS16, TensorInfo::SetQuantizationScale(), and IWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(memoryManager);
     unsigned int outputWidth = 3;
     unsigned int outputHeight = 6;
     unsigned int outputChannels = 3;
     unsigned int inputWidth1 = 3;
     unsigned int inputHeight1 = 6;
     unsigned int inputChannels1 = 2;
     unsigned int inputWidth2 = 3;
     unsigned int inputHeight2 = 6;
     unsigned int inputChannels2 = 1;
     // Defines the tensor descriptors.
     TensorInfo outputTensorInfo({ outputChannels, outputHeight, outputWidth }, DataType::QSymmS16);
     TensorInfo inputTensorInfo1({ inputChannels1, inputHeight1, inputWidth1 }, DataType::QSymmS16);
     TensorInfo inputTensorInfo2({ inputChannels2, inputHeight2, inputWidth2 }, DataType::QSymmS16);
     // Arbitrary scale and offsets. They don't really matter as the Concat operator doesn't dequantize/quantize them.
     const float scale = 0.13497836f;
     const int32_t offset = -7;
     outputTensorInfo.SetQuantizationScale(scale);
     outputTensorInfo.SetQuantizationOffset(offset);
     inputTensorInfo1.SetQuantizationScale(scale);
     inputTensorInfo1.SetQuantizationOffset(offset);
     inputTensorInfo2.SetQuantizationScale(scale);
     inputTensorInfo2.SetQuantizationOffset(offset);
     LayerTestResult<uint16_t, 3> ret(outputTensorInfo);
     ret.outputExpected = MakeTensor<uint16_t, 3>(outputTensorInfo, std::vector<uint16_t>(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48,
         49, 50, 51,
         52, 53, 54,
     }));
     auto input1 = MakeTensor<uint16_t, 3>(inputTensorInfo1, std::vector<uint16_t>(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
     }));
     auto input2 = MakeTensor<uint16_t, 3>(inputTensorInfo2, std::vector<uint16_t>(
     {
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48,
         49, 50, 51,
         52, 53, 54,
     }));
     std::vector<unsigned int> wOrigin1 = { 0, 0, 0 }; //Extent of the window is defined by size of input[0].
     ConcatQueueDescriptor::ViewOrigin window1(wOrigin1);
     std::vector<unsigned int> wOrigin2 = { 2, 0, 0 }; //Extent of the window is defined by size of input[1].
     ConcatQueueDescriptor::ViewOrigin window2(wOrigin2);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     bool subTensorsSupported = workloadFactory.SupportsSubTensors();
     std::unique_ptr<ITensorHandle> inputHandle1 =
             subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo1.GetShape(), wOrigin1.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo1);
     std::unique_ptr<ITensorHandle> inputHandle2 =
             subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo2.GetShape(), wOrigin2.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo2);
     ConcatQueueDescriptor data;
     WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo1, inputHandle1.get());
     AddInputToWorkload(data, info, inputTensorInfo2, inputHandle2.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_ViewOrigins.push_back(window1);
     data.m_ViewOrigins.push_back(window2);
     std::unique_ptr<IWorkload> workload = workloadFactory.CreateConcat(data, info);
     inputHandle1->Allocate();
     inputHandle2->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle1.get(), &input1[0][0][0]);
     CopyDataToITensorHandle(inputHandle2.get(), &input2[0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0], outputHandle.get());
     return ret;
 }
ConcatUint8DifferentQParamsTest()
LayerTestResult<uint8_t, 3> ConcatUint8DifferentQParamsTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2423 of file ConcatTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateConcat(), ITensorHandleFactory::CreateSubTensorHandle(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), armnn::info, ConcatQueueDescriptor::m_ViewOrigins, LayerTestResult< T, n >::output, LayerTestResult< T, n >::outputExpected, armnn::QAsymmU8, and IWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(memoryManager);
     unsigned int outputWidth = 3;
     unsigned int outputHeight = 6;
     unsigned int outputChannels = 3;
     unsigned int inputWidth1 = 3;
     unsigned int inputHeight1 = 6;
     unsigned int inputChannels1 = 2;
     unsigned int inputWidth2 = 3;
     unsigned int inputHeight2 = 6;
     unsigned int inputChannels2 = 1;
     // Defines the tensor descriptors.
     TensorInfo outputTensorInfo({ outputChannels, outputHeight, outputWidth }, DataType::QAsymmU8);
     TensorInfo inputTensorInfo1({ inputChannels1, inputHeight1, inputWidth1 }, DataType::QAsymmU8);
     TensorInfo inputTensorInfo2({ inputChannels2, inputHeight2, inputWidth2 }, DataType::QAsymmU8);
     // Quantized input1 tensor. Range [-3, 1]
     const float inputScale1 = 0.015686f;
     const int32_t inputOffset1 = 192;
     auto input1 = MakeTensor<uint8_t, 3>(inputTensorInfo1, std::vector<uint8_t>(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
     })
     );
     // Quatized input2 tensor. Range [-1, 4]
     const float inputScale2 = 0.019608f;
     const int32_t inputOffset2 = 50;
     auto input2 = MakeTensor<uint8_t, 3>(inputTensorInfo2, std::vector<uint8_t>(
     {
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48,
         49, 50, 51,
         52, 53, 54,
     })
     );
     // Output has the same quantization parameters than input1,
     // so that only the requantization of input2 is required
     const float outputScale = 0.015686f;
     const int32_t outputOffset = 192;
     LayerTestResult<uint8_t, 3> ret(outputTensorInfo);
     ret.outputExpected = MakeTensor<uint8_t, 3>(outputTensorInfo, std::vector<uint8_t>(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
         176, 177, 178,
         179, 181, 182,
         183, 184, 186,
         187, 188, 189,
         191, 192, 193,
         195, 196, 197,
     })
     );
     outputTensorInfo.SetQuantizationScale(outputScale);
     outputTensorInfo.SetQuantizationOffset(outputOffset);
     inputTensorInfo1.SetQuantizationScale(inputScale1);
     inputTensorInfo1.SetQuantizationOffset(inputOffset1);
     inputTensorInfo2.SetQuantizationScale(inputScale2);
     inputTensorInfo2.SetQuantizationOffset(inputOffset2);
     std::vector<unsigned int> wOrigin1 = { 0, 0, 0 }; //Extent of the window is defined by size of input[0].
     ConcatQueueDescriptor::ViewOrigin window1(wOrigin1);
     std::vector<unsigned int> wOrigin2 = { 2, 0, 0 }; //Extent of the window is defined by size of input[1].
     ConcatQueueDescriptor::ViewOrigin window2(wOrigin2);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     bool subTensorsSupported = workloadFactory.SupportsSubTensors();
     std::unique_ptr<ITensorHandle> inputHandle1 =
             subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo1.GetShape(), wOrigin1.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo1);
     std::unique_ptr<ITensorHandle> inputHandle2 =
             subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo2.GetShape(), wOrigin2.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo2);
     ConcatQueueDescriptor data;
     WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo1, inputHandle1.get());
     AddInputToWorkload(data, info, inputTensorInfo2, inputHandle2.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_ViewOrigins.push_back(window1);
     data.m_ViewOrigins.push_back(window2);
     std::unique_ptr<IWorkload> workload = workloadFactory.CreateConcat(data, info);
     inputHandle1->Allocate();
     inputHandle2->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle1.get(), &input1[0][0][0]);
     CopyDataToITensorHandle(inputHandle2.get(), &input2[0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0], outputHandle.get());
     return ret;
 }
ConcatUint8Test()
LayerTestResult<uint8_t, 3> ConcatUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 2569 of file ConcatTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateConcat(), ITensorHandleFactory::CreateSubTensorHandle(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), armnn::info, ConcatQueueDescriptor::m_ViewOrigins, LayerTestResult< T, n >::output, LayerTestResult< T, n >::outputExpected, armnn::QAsymmU8, TensorInfo::SetQuantizationScale(), and IWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(memoryManager);
     unsigned int outputWidth = 3;
     unsigned int outputHeight = 6;
     unsigned int outputChannels = 3;
     unsigned int inputWidth1 = 3;
     unsigned int inputHeight1 = 6;
     unsigned int inputChannels1 = 2;
     unsigned int inputWidth2 = 3;
     unsigned int inputHeight2 = 6;
     unsigned int inputChannels2 = 1;
     // Defines the tensor descriptors.
     TensorInfo outputTensorInfo({ outputChannels, outputHeight, outputWidth }, DataType::QAsymmU8);
     TensorInfo inputTensorInfo1({ inputChannels1, inputHeight1, inputWidth1 }, DataType::QAsymmU8);
     TensorInfo inputTensorInfo2({ inputChannels2, inputHeight2, inputWidth2 }, DataType::QAsymmU8);
     // Arbitrary scale and offsets. They don't really matter as the Concat operator doesn't dequantize/quantize them.
     const float scale = 0.13497836f;
     const int32_t offset = -7;
     outputTensorInfo.SetQuantizationScale(scale);
     outputTensorInfo.SetQuantizationOffset(offset);
     inputTensorInfo1.SetQuantizationScale(scale);
     inputTensorInfo1.SetQuantizationOffset(offset);
     inputTensorInfo2.SetQuantizationScale(scale);
     inputTensorInfo2.SetQuantizationOffset(offset);
     LayerTestResult<uint8_t, 3> ret(outputTensorInfo);
     ret.outputExpected = MakeTensor<uint8_t, 3>(outputTensorInfo, std::vector<uint8_t>(
         {
             1, 2, 3,
             4, 5, 6,
             7, 8, 9,
             10, 11, 12,
             13, 14, 15,
             16, 17, 18,
             19, 20, 21,
             22, 23, 24,
             25, 26, 27,
             28, 29, 30,
             31, 32, 33,
             34, 35, 36,
             37, 38, 39,
             40, 41, 42,
             43, 44, 45,
             46, 47, 48,
             49, 50, 51,
             52, 53, 54,
         })
     );
     auto input1 = MakeTensor<uint8_t, 3>(inputTensorInfo1, std::vector<uint8_t>(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
     })
     );
     auto input2 = MakeTensor<uint8_t, 3>(inputTensorInfo2, std::vector<uint8_t>(
     {
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48,
         49, 50, 51,
         52, 53, 54,
     })
     );
     std::vector<unsigned int> wOrigin1 = { 0, 0, 0 }; //Extent of the window is defined by size of input[0].
     ConcatQueueDescriptor::ViewOrigin window1(wOrigin1);
     std::vector<unsigned int> wOrigin2 = { 2, 0, 0 }; //Extent of the window is defined by size of input[1].
     ConcatQueueDescriptor::ViewOrigin window2(wOrigin2);
     std::unique_ptr<ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     bool subTensorsSupported = workloadFactory.SupportsSubTensors();
     std::unique_ptr<ITensorHandle> inputHandle1 =
         subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo1.GetShape(), wOrigin1.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo1);
     std::unique_ptr<ITensorHandle> inputHandle2 =
         subTensorsSupported ?
             tensorHandleFactory.CreateSubTensorHandle(*outputHandle, inputTensorInfo2.GetShape(), wOrigin2.data()) :
             tensorHandleFactory.CreateTensorHandle(inputTensorInfo2);
     ConcatQueueDescriptor data;
     WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo1, inputHandle1.get());
     AddInputToWorkload(data, info, inputTensorInfo2, inputHandle2.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_ViewOrigins.push_back(window1);
     data.m_ViewOrigins.push_back(window2);
     std::unique_ptr<IWorkload> workload = workloadFactory.CreateConcat(data, info);
     inputHandle1->Allocate();
     inputHandle2->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle1.get(), &input1[0][0][0]);
     CopyDataToITensorHandle(inputHandle2.get(), &input2[0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0], outputHandle.get());
     return ret;
 }