ArmNN: src/backends/backendsCommon/test/layerTests/DebugTestImpl.hpp File Reference
DebugTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <BFloat16.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > Debug4dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 3 > Debug3dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 2 > Debug2dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 1 > Debug1dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 4 > Debug4dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 3 > Debug3dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 2 > Debug2dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::BFloat16, 1 > Debug1dBFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > Debug4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 3 > Debug3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 2 > Debug2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 1 > Debug1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > Debug4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 3 > Debug3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 2 > Debug2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 1 > Debug1dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
Debug1dBFloat16Test()
LayerTestResult<armnn::BFloat16, 1> Debug1dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 332 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug1dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug1dFloat32Test()
LayerTestResult<float, 1> Debug1dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 304 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug1dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug1dInt16Test()
LayerTestResult<int16_t, 1> Debug1dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 388 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug1dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug1dUint8Test()
LayerTestResult<uint8_t, 1> Debug1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 360 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug1dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Debug2dBFloat16Test()
LayerTestResult<armnn::BFloat16, 2> Debug2dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 325 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug2dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug2dFloat32Test()
LayerTestResult<float, 2> Debug2dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 297 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug2dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug2dInt16Test()
LayerTestResult<int16_t, 2> Debug2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 381 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug2dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug2dUint8Test()
LayerTestResult<uint8_t, 2> Debug2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 353 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug2dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Debug3dBFloat16Test()
LayerTestResult<armnn::BFloat16, 3> Debug3dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 318 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug3dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug3dFloat32Test()
LayerTestResult<float, 3> Debug3dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 290 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug3dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug3dInt16Test()
LayerTestResult<int16_t, 3> Debug3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 374 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug3dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug3dUint8Test()
LayerTestResult<uint8_t, 3> Debug3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 346 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug3dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Debug4dBFloat16Test()
LayerTestResult<armnn::BFloat16, 4> Debug4dBFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 311 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug4dTest<armnn::DataType::BFloat16>(workloadFactory, memoryManager);
 }
Debug4dFloat32Test()
LayerTestResult<float, 4> Debug4dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 283 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug4dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Debug4dInt16Test()
LayerTestResult<int16_t, 4> Debug4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 367 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug4dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Debug4dUint8Test()
LayerTestResult<uint8_t, 4> Debug4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 339 of file DebugTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Debug4dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }