ArmNN: src/armnn/test/optimizations/FuseActivationTests.cpp File Reference
FuseActivationTests.cpp File Reference
#include "LayersFwd.hpp"
#include <Network.hpp>
#include <ResolveType.hpp>
#include <armnn/INetwork.hpp>
#include <test/TestUtils.hpp>
#include <boost/test/unit_test.hpp>
#include <QuantizeHelper.hpp>
#include <string>
Namespaces
armnn
Copyright (c) 2021 ARM Limited and Contributors.
Functions
template<typename T >
std::vector< T > GetVector (unsigned int size, float initial, float increment)
template<typename LayerTest , DataType ArmnnType>
INetworkPtr CreatNetwork (ActivationDescriptor activationDescriptor, bool preventFusing, float scale, int32_t offset)
template<typename LayerTest , DataType ArmnnType, typename LayerType = typename LayerTest::LayerType, typename T = ResolveType<ArmnnType>>
void FuseActivationIntoPreviousLayerTest (ActivationDescriptor activationDescriptor, float tolerance, Compute backendId, float scale=1.f, int32_t offset=0)
template<typename LayerTest , DataType ArmnnType, typename LayerType = typename LayerTest::LayerType, typename T = ResolveType<ArmnnType>>
bool FuseActivationSimpleTest (ActivationDescriptor activationDescriptor, Compute backendId, float scale=1.f, int32_t offset=0)
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoBatchNormFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoBatchNormFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvQAsymmU8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvQAsymmU8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedQAsymmU8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvQASymmS8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvQASymmS8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedQASymmS8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseTanHIntoConvFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoConvFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat32CpuAccTest)
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat16CpuAccTest)
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationQAsymmU8CpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoBatchNormFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoMulFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoAddFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoSubFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoDivFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoBatchNormFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoMulFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoAddFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoSubFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDivFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoBatchNormFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoMulFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoAddFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoSubFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUIntoDivFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUQIntoConvAsymmU8GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUQIntoDWConvAsymmU8GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseReLUQIntoFullyConnectedAsymmU8GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvQASymmS8GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvQASymmS8GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedQASymmS8GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseTanHIntoConvFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseTanHIntoMulFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseTanHIntoAddFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseTanHIntoSubFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseTanHIntoDivFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoConvFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoMulFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoAddFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoSubFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoDivFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat32GpuAccTest)
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat16GpuAccTest)
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationQAsymmU8GpuAccTest)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvFloat32CpuAccTest)
Definition at line 479 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [2/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvFloat32CpuAccTest)
Definition at line 487 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DWConvolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [3/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedFloat32CpuAccTest)
Definition at line 495 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [4/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoBatchNormFloat32CpuAccTest)
Definition at line 503 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<BatchNormTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [5/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvFloat32CpuAccTest)
Definition at line 513 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [6/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvFloat32CpuAccTest)
Definition at line 523 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest < DWConvolution2dTest < DataType::Float32 > , DataType::Float32 >
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [7/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedFloat32CpuAccTest)
Definition at line 533 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [8/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoBatchNormFloat32CpuAccTest)
Definition at line 543 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<BatchNormTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [9/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvQAsymmU8CpuAccTest)
Definition at line 555 of file FuseActivationTests.cpp.
References armnn::CpuAcc, ActivationDescriptor::m_Function, armnn::QAsymmU8, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [10/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvQAsymmU8CpuAccTest)
Definition at line 563 of file FuseActivationTests.cpp.
References armnn::CpuAcc, ActivationDescriptor::m_Function, armnn::QAsymmU8, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DWConvolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [11/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedQAsymmU8CpuAccTest)
Definition at line 571 of file FuseActivationTests.cpp.
References armnn::CpuAcc, ActivationDescriptor::m_Function, armnn::QAsymmU8, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [12/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvQASymmS8CpuAccTest)
Definition at line 581 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, and armnn::QAsymmS8.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 6.0f;
     activationDescriptor.m_B = 0.0f;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::QAsymmS8>, DataType::QAsymmS8>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [13/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvQASymmS8CpuAccTest)
Definition at line 591 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, and armnn::QAsymmS8.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 6.0f;
     activationDescriptor.m_B = 0.0f;
     FuseActivationIntoPreviousLayerTest < DWConvolution2dTest < DataType::QAsymmS8 > , DataType::QAsymmS8 >
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [14/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedQASymmS8CpuAccTest)
Definition at line 601 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, and armnn::QAsymmS8.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 6.0f;
     activationDescriptor.m_B = 0.0f;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::QAsymmS8>, DataType::QAsymmS8>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [15/62]
BOOST_AUTO_TEST_CASE (FuseTanHIntoConvFloat32CpuAccTest)
Definition at line 613 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, ActivationDescriptor::m_Function, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::TanH;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [16/62]
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoConvFloat32CpuAccTest)
Definition at line 623 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, armnn::HardSwish, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::CpuAcc);
 }
BOOST_AUTO_TEST_CASE() [17/62]
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat32CpuAccTest)
Definition at line 633 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float32, armnn::FuseActivationSimpleTest(), ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     for (int i = 0; i != 12; ++i)
     {
         activationDescriptor.m_Function = static_cast<ActivationFunction>(i);
         activationDescriptor.m_A = 1.0f;
         activationDescriptor.m_B = -1.0f;
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
             (activationDescriptor, Compute::CpuAcc)), "Convolution + Activation function " << i);
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<DWConvolution2dTest<DataType::Float32>, DataType::Float32>
             (activationDescriptor, Compute::CpuAcc)), "DepthwiseConvolution + Activation function " << i);
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::Float32>, DataType::Float32>
             (activationDescriptor, Compute::CpuAcc)), "FullyConnected + Activation function " << i);
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<BatchNormTest<DataType::Float32>, DataType::Float32>
             (activationDescriptor, Compute::CpuAcc)), "BatchNorm + Activation function " << i);
     }
 }
BOOST_AUTO_TEST_CASE() [18/62]
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat16CpuAccTest)
Definition at line 651 of file FuseActivationTests.cpp.
References armnn::CpuAcc, armnn::Float16, armnn::FuseActivationSimpleTest(), ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     for (int i = 0; i != 12; ++i)
     {
         activationDescriptor.m_Function = static_cast<ActivationFunction>(i);
         activationDescriptor.m_A = 1.0f;
         activationDescriptor.m_B = -1.0f;
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::Float16>, DataType::Float16>
             (activationDescriptor, Compute::CpuAcc)), "Convolution + Activation function " << i);
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<DWConvolution2dTest<DataType::Float16>, DataType::Float16>
             (activationDescriptor, Compute::CpuAcc)), "DepthwiseConvolution + Activation function " << i);
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::Float16>, DataType::Float16>
             (activationDescriptor, Compute::CpuAcc)), "FullyConnected + Activation function " << i);
         BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<BatchNormTest<DataType::Float16>, DataType::Float16>
             (activationDescriptor, Compute::CpuAcc)), "BatchNorm + Activation function " << i);
     }
 }
BOOST_AUTO_TEST_CASE() [19/62]
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationQAsymmU8CpuAccTest)
Definition at line 669 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::CpuAcc, armnn::FuseActivationSimpleTest(), armnn::HardSwish, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, armnn::QAsymmU8, armnn::ReLu, armnn::Sigmoid, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::Sigmoid;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc, 1.f / 256.f, 0)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc, 1.f / 256.f, 0)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::TanH;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc, 1.f / 128.f, 128)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc, 1.f / 128.f, 128)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::CpuAcc)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
 }
BOOST_AUTO_TEST_CASE() [20/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvFloat32GpuAccTest)
Definition at line 719 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [21/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvFloat32GpuAccTest)
Definition at line 727 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DWConvolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [22/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedFloat32GpuAccTest)
Definition at line 735 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [23/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoBatchNormFloat32GpuAccTest)
Definition at line 743 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<BatchNormTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [24/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoMulFloat32GpuAccTest)
Definition at line 751 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<MultiplicationTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [25/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoAddFloat32GpuAccTest)
Definition at line 759 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<AdditionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [26/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoSubFloat32GpuAccTest)
Definition at line 767 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<SubtractionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [27/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoDivFloat32GpuAccTest)
Definition at line 775 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DivisionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [28/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvFloat32GpuAccTest)
Definition at line 785 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [29/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvFloat32GpuAccTest)
Definition at line 795 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<DWConvolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [30/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedFloat32GpuAccTest)
Definition at line 805 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [31/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoBatchNormFloat32GpuAccTest)
Definition at line 815 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<BatchNormTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [32/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoMulFloat32GpuAccTest)
Definition at line 825 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<MultiplicationTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [33/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoAddFloat32GpuAccTest)
Definition at line 835 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<AdditionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [34/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoSubFloat32GpuAccTest)
Definition at line 845 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<SubtractionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [35/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDivFloat32GpuAccTest)
Definition at line 855 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     FuseActivationIntoPreviousLayerTest<DivisionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [36/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoConvFloat16GpuAccTest)
Definition at line 867 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [37/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoDWConvFloat16GpuAccTest)
Definition at line 875 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DWConvolution2dTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [38/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoFullyConnectedFloat16GpuAccTest)
Definition at line 883 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [39/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoBatchNormFloat16GpuAccTest)
Definition at line 891 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<BatchNormTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [40/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoMulFloat16GpuAccTest)
Definition at line 899 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<MultiplicationTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [41/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoAddFloat16GpuAccTest)
Definition at line 907 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<AdditionTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [42/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoSubFloat16GpuAccTest)
Definition at line 915 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<SubtractionTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [43/62]
BOOST_AUTO_TEST_CASE (FuseReLUIntoDivFloat16GpuAccTest)
Definition at line 923 of file FuseActivationTests.cpp.
References armnn::Float16, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DivisionTest<DataType::Float16>, DataType::Float16>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [44/62]
BOOST_AUTO_TEST_CASE (FuseReLUQIntoConvAsymmU8GpuAccTest)
Definition at line 933 of file FuseActivationTests.cpp.
References armnn::GpuAcc, ActivationDescriptor::m_Function, armnn::QAsymmU8, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [45/62]
BOOST_AUTO_TEST_CASE (FuseReLUQIntoDWConvAsymmU8GpuAccTest)
Definition at line 941 of file FuseActivationTests.cpp.
References armnn::GpuAcc, ActivationDescriptor::m_Function, armnn::QAsymmU8, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<DWConvolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [46/62]
BOOST_AUTO_TEST_CASE (FuseReLUQIntoFullyConnectedAsymmU8GpuAccTest)
Definition at line 949 of file FuseActivationTests.cpp.
References armnn::GpuAcc, ActivationDescriptor::m_Function, armnn::QAsymmU8, and armnn::ReLu.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [47/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoConvQASymmS8GpuAccTest)
Definition at line 959 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, and armnn::QAsymmS8.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 6.0f;
     activationDescriptor.m_B = 0.0f;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::QAsymmS8>, DataType::QAsymmS8>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [48/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoDWConvQASymmS8GpuAccTest)
Definition at line 969 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, and armnn::QAsymmS8.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 6.0f;
     activationDescriptor.m_B = 0.0f;
     FuseActivationIntoPreviousLayerTest < DWConvolution2dTest < DataType::QAsymmS8 > , DataType::QAsymmS8 >
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [49/62]
BOOST_AUTO_TEST_CASE (FuseBoundedReLUIntoFullyConnectedQASymmS8GpuAccTest)
Definition at line 979 of file FuseActivationTests.cpp.
References armnn::BoundedReLu, armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, and armnn::QAsymmS8.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 6.0f;
     activationDescriptor.m_B = 0.0f;
     FuseActivationIntoPreviousLayerTest<FullyConnectedTest<DataType::QAsymmS8>, DataType::QAsymmS8>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [50/62]
BOOST_AUTO_TEST_CASE (FuseTanHIntoConvFloat32GpuAccTest)
Definition at line 991 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::TanH;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [51/62]
BOOST_AUTO_TEST_CASE (FuseTanHIntoMulFloat32GpuAccTest)
Definition at line 999 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::TanH;
     FuseActivationIntoPreviousLayerTest<MultiplicationTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [52/62]
BOOST_AUTO_TEST_CASE (FuseTanHIntoAddFloat32GpuAccTest)
Definition at line 1007 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::TanH;
     FuseActivationIntoPreviousLayerTest<AdditionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [53/62]
BOOST_AUTO_TEST_CASE (FuseTanHIntoSubFloat32GpuAccTest)
Definition at line 1015 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::TanH;
     FuseActivationIntoPreviousLayerTest<SubtractionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [54/62]
BOOST_AUTO_TEST_CASE (FuseTanHIntoDivFloat32GpuAccTest)
Definition at line 1023 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, ActivationDescriptor::m_Function, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::TanH;
     FuseActivationIntoPreviousLayerTest<DivisionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [55/62]
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoConvFloat32GpuAccTest)
Definition at line 1033 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, armnn::HardSwish, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     FuseActivationIntoPreviousLayerTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [56/62]
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoMulFloat32GpuAccTest)
Definition at line 1041 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, armnn::HardSwish, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     FuseActivationIntoPreviousLayerTest<MultiplicationTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [57/62]
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoAddFloat32GpuAccTest)
Definition at line 1049 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, armnn::HardSwish, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     FuseActivationIntoPreviousLayerTest<AdditionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [58/62]
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoSubFloat32GpuAccTest)
Definition at line 1057 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, armnn::HardSwish, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     FuseActivationIntoPreviousLayerTest<SubtractionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [59/62]
BOOST_AUTO_TEST_CASE (FuseHardSwishIntoDivFloat32GpuAccTest)
Definition at line 1065 of file FuseActivationTests.cpp.
References armnn::Float32, armnn::GpuAcc, armnn::HardSwish, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     FuseActivationIntoPreviousLayerTest<DivisionTest<DataType::Float32>, DataType::Float32>
         (activationDescriptor, 0.0001f, Compute::GpuAcc);
 }
BOOST_AUTO_TEST_CASE() [60/62]
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat32GpuAccTest)
Definition at line 1075 of file FuseActivationTests.cpp.
References armnn::Elu, armnn::Float32, armnn::FuseActivationSimpleTest(), armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     for (int i = 0; i != 12; ++i)
     {
         activationDescriptor.m_Function = static_cast<ActivationFunction>(i);
         activationDescriptor.m_A = 1.0f;
         activationDescriptor.m_B = -1.0f;
         if (activationDescriptor.m_Function != ActivationFunction::Elu)
         {
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "Convolution + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<DWConvolution2dTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "DepthwiseConvolution + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "FullyConnected + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<BatchNormTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "BatchNorm + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<MultiplicationTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "Multiplication + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<AdditionTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "Addition + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<SubtractionTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "Subtraction + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<DivisionTest<DataType::Float32>, DataType::Float32>
                 (activationDescriptor, Compute::GpuAcc)), "Division + Activation function " << i);
         }
     }
 }
BOOST_AUTO_TEST_CASE() [61/62]
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationFloat16GpuAccTest)
Definition at line 1104 of file FuseActivationTests.cpp.
References armnn::Elu, armnn::Float16, armnn::FuseActivationSimpleTest(), armnn::GpuAcc, ActivationDescriptor::m_A, ActivationDescriptor::m_B, and ActivationDescriptor::m_Function.
 {
     ActivationDescriptor activationDescriptor;
     for (int i = 0; i != 12; ++i)
     {
         activationDescriptor.m_Function = static_cast<ActivationFunction>(i);
         activationDescriptor.m_A = 1.0f;
         activationDescriptor.m_B = -1.0f;
         if (activationDescriptor.m_Function != ActivationFunction::Elu)
         {
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "Convolution + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<DWConvolution2dTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "Depthwise + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "FullyConnected + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<BatchNormTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "BatchNorm + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<MultiplicationTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "Multiplication + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<AdditionTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "Addition + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<SubtractionTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "Subtraction + Activation function " << i);
             BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<DivisionTest<DataType::Float16>, DataType::Float16>
                 (activationDescriptor, Compute::GpuAcc)), "Division + Activation function " << i);
         }
     }
 }
BOOST_AUTO_TEST_CASE() [62/62]
BOOST_AUTO_TEST_CASE (LayerFollowedByActivationQAsymmU8GpuAccTest)
Definition at line 1133 of file FuseActivationTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), armnn::BoundedReLu, armnn::FuseActivationSimpleTest(), armnn::GpuAcc, armnn::HardSwish, ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, armnn::QAsymmU8, armnn::ReLu, armnn::Sigmoid, and armnn::TanH.
 {
     ActivationDescriptor activationDescriptor;
     activationDescriptor.m_Function = ActivationFunction::Sigmoid;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc, 1.f / 256.f, 0)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc, 1.f / 256.f, 0)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::TanH;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc, 1.f / 128.f, 128)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc, 1.f / 128.f, 128)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::ReLu;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::BoundedReLu;
     activationDescriptor.m_A = 1.0f;
     activationDescriptor.m_B = -1.0f;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     activationDescriptor.m_Function = ActivationFunction::HardSwish;
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<Convolution2dTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc)), "Convolution + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
     BOOST_CHECK_MESSAGE((FuseActivationSimpleTest<FullyConnectedTest<DataType::QAsymmU8>, DataType::QAsymmU8>
         (activationDescriptor, Compute::GpuAcc)), "FullyConnected + Activation function " <<
         static_cast<int>(activationDescriptor.m_Function));
 }