ArmNN: src/armnn/test/InstrumentTests.cpp File Reference
InstrumentTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "WallClockTimer.hpp"
#include <chrono>
#include <thread>
Functions
BOOST_AUTO_TEST_CASE (WallClockTimerInMicroseconds)
BOOST_AUTO_TEST_CASE (WallClockTimerInNanoseconds)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (WallClockTimerInMicroseconds)
Definition at line 16 of file InstrumentTests.cpp.
References WallClockTimer::GetMeasurements(), WallClockTimer::GetName(), WallClockTimer::Start(), WallClockTimer::Stop(), and WallClockTimer::WALL_CLOCK_TIME.
 {
     WallClockTimer wallClockTimer;
     BOOST_CHECK_EQUAL(wallClockTimer.GetName(), "WallClockTimer");
     // start the timer
     wallClockTimer.Start();
     // wait for 10 microseconds
     std::this_thread::sleep_for(std::chrono::microseconds(10));
    // stop the timer
     wallClockTimer.Stop();
     BOOST_CHECK_EQUAL(wallClockTimer.GetMeasurements().front().m_Name, WallClockTimer::WALL_CLOCK_TIME);
     // check that WallClockTimer measurement should be >= 10 microseconds
     BOOST_CHECK_GE(wallClockTimer.GetMeasurements().front().m_Value, std::chrono::microseconds(10).count());
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (WallClockTimerInNanoseconds)
Definition at line 37 of file InstrumentTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), WallClockTimer::GetMeasurements(), WallClockTimer::GetName(), WallClockTimer::Start(), WallClockTimer::Stop(), and WallClockTimer::WALL_CLOCK_TIME.
 {
     WallClockTimer wallClockTimer;
     BOOST_CHECK_EQUAL(wallClockTimer.GetName(), "WallClockTimer");
     // start the timer
     wallClockTimer.Start();
     // wait for 500 nanoseconds - 0.5 microseconds
     std::this_thread::sleep_for(std::chrono::nanoseconds(500));
     // stop the timer
     wallClockTimer.Stop();
     BOOST_CHECK_EQUAL(wallClockTimer.GetMeasurements().front().m_Name, WallClockTimer::WALL_CLOCK_TIME);
     // delta is 0.5 microseconds
     const auto delta =
         std::chrono::duration_cast<std::chrono::duration<double, std::micro>>(std::chrono::nanoseconds(500));
     // check that WallClockTimer measurement should be >= 0.5 microseconds
     BOOST_CHECK_GE(wallClockTimer.GetMeasurements().front().m_Value, delta.count());
 }