ArmNN: src/backends/backendsCommon/test/InstanceNormalizationEndToEndTestImpl.cpp File Reference
InstanceNormalizationEndToEndTestImpl.cpp File Reference
#include "InstanceNormalizationEndToEndTestImpl.hpp"
#include "EndToEndTestImpl.hpp"
#include "ResolveType.hpp"
#include <armnnUtils/Permute.hpp>
#include <armnnUtils/DataLayoutIndexed.hpp>
#include <armnn/INetwork.hpp>
#include <backendsCommon/test/DataLayoutUtils.hpp>
#include <test/TestUtils.hpp>
#include <boost/test/unit_test.hpp>
Functions
void InstanceNormalizationNhwcEndToEndTest1 (const std::vector< armnn::BackendId > &defaultBackends)
void InstanceNormalizationNchwEndToEndTest1 (const std::vector< armnn::BackendId > &defaultBackends)
void InstanceNormalizationNhwcEndToEndTest2 (const std::vector< armnn::BackendId > &defaultBackends)
void InstanceNormalizationNchwEndToEndTest2 (const std::vector< armnn::BackendId > &defaultBackends)
Function Documentation
InstanceNormalizationNchwEndToEndTest1()
void InstanceNormalizationNchwEndToEndTest1 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 168 of file InstanceNormalizationEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const float eps       = 0.0001f;
     const float beta      = 0.0f;
     const float gamma     = 1.0f;
     TensorShape inputShape{2, 2, 2, 2};
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     TensorShape outputShape{2, 2, 2, 2};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
         {
             // Batch 0, Height 0, Width 0 x Channel (2)
             0.f,  1.f,
             // Batch 0, Height 0, Width 1 x Channel (2)
             0.f,  2.f,
             // Batch 0, Height 1, Width 0 x Channel (2)
             0.f,  2.f,
             // Batch 0, Height 1, Width 1 x Channel (2)
             0.f,  4.f,
             // Batch 1, Height 0, Width 0 x Channel (2)
             1.f, -1.f,
             // Batch 1, Height 0, Width 1 x Channel (2)
             -1.f,  2.f,
             // Batch 1, Height 1, Width 0 x Channel (2)
             -1.f, -2.f,
             // Batch 1, Height 1, Width 1 x Channel (2)
             1.f,  4.f
         });
     std::vector<float> expectedOutputData = std::vector<float>(
         {
             // Batch 0, Height 0, Width 0 x Channel (2)
             0.f, -1.1470304f,
             // Batch 0, Height 0, Width 1 x Channel (2)
             0.f, -0.22940612f,
             // Batch 0, Height 1, Width 0 x Channel (2)
             0.f, -0.22940612f,
             // Batch 0, Height 1, Width 1 x Channel (2)
             0.f,  1.6058424f,
             // Batch 1, Height 0, Width 0 x Channel (2)
             0.99995005f, -0.7337929f,
             // Batch 1, Height 0, Width 1 x Channel (2)
             -0.99995005f,  0.52413774f,
             // Batch 1, Height 1, Width 0 x Channel (2)
             -0.99995005f, -1.1531031f,
             // Batch 1, Height 1, Width 1 x Channel (2)
             0.99995005f,  1.3627582f
         });
     InstanceNormalizationEndToEnd(defaultBackends,
                                   DataLayout::NCHW,
                                   inputTensorInfo,
                                   outputTensorInfo,
                                   inputData,
                                   expectedOutputData,
                                   gamma,
                                   beta,
                                   eps);
 }
InstanceNormalizationNchwEndToEndTest2()
void InstanceNormalizationNchwEndToEndTest2 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 310 of file InstanceNormalizationEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const float eps        = 0.0001f;
     const float beta       = 10.0f;
     const float gamma      = 2.0f;
     TensorShape inputShape{2, 2, 2, 2};
     TensorShape outputShape{2, 2, 2, 2};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
         {
             // Batch 0, Height 0, Width 0 x Channel (2)
             0.f,  1.f,
             // Batch 0, Height 0, Width 1 x Channel (2)
             0.f,  2.f,
             // Batch 0, Height 1, Width 0 x Channel (2)
             0.f,  2.f,
             // Batch 0, Height 1, Width 1 x Channel (2)
             0.f,  4.f,
             // Batch 1, Height 0, Width 0 x Channel (2)
             1.f, -1.f,
             // Batch 1, Height 0, Width 1 x Channel (2)
             -1.f,  2.f,
             // Batch 1, Height 1, Width 0 x Channel (2)
             -1.f, -2.f,
             // Batch 1, Height 1, Width 1 x Channel (2)
             1.f,  4.f
         });
     std::vector<float> expectedOutputData = std::vector<float>(
         {
             // Batch 0, Height 0, Width 0 x Channel (2)
             10.f,     7.7059393f,
             // Batch 0, Height 0, Width 1 x Channel (2)
             10.f,     9.541187f,
             // Batch 0, Height 1, Width 0 x Channel (2)
             10.f,     9.541187f,
             // Batch 0, Height 1, Width 1 x Channel (2)
             10.f,     13.211685f,
             // Batch 1, Height 0, Width 0 x Channel (2)
             11.9999f, 8.532414f,
             // Batch 1, Height 0, Width 1 x Channel (2)
             8.0001f,  11.048275f,
             // Batch 1, Height 1, Width 0 x Channel (2)
             8.0001f,  7.693794f,
             // Batch 1, Height 1, Width 1 x Channel (2)
             11.9999f, 12.725516f
         });
     InstanceNormalizationEndToEnd(defaultBackends,
                                   DataLayout::NCHW,
                                   inputTensorInfo,
                                   outputTensorInfo,
                                   inputData,
                                   expectedOutputData,
                                   gamma,
                                   beta,
                                   eps);
 }
InstanceNormalizationNhwcEndToEndTest1()
void InstanceNormalizationNhwcEndToEndTest1 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 98 of file InstanceNormalizationEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NHWC.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const float eps       = 0.0001f;
     const float beta      = 0.0f;
     const float gamma     = 1.0f;
     TensorShape inputShape{2, 2, 2, 2};
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     TensorShape outputShape{2, 2, 2, 2};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
     {
         // Batch 0, Height 0, Width 0 x Channel (2)
         0.f,  1.f,
         // Batch 0, Height 0, Width 1 x Channel (2)
         0.f,  2.f,
         // Batch 0, Height 1, Width 0 x Channel (2)
         0.f,  2.f,
         // Batch 0, Height 1, Width 1 x Channel (2)
         0.f,  4.f,
         // Batch 1, Height 0, Width 0 x Channel (2)
         1.f, -1.f,
         // Batch 1, Height 0, Width 1 x Channel (2)
         -1.f,  2.f,
         // Batch 1, Height 1, Width 0 x Channel (2)
         -1.f, -2.f,
         // Batch 1, Height 1, Width 1 x Channel (2)
         1.f,  4.f
     });
     std::vector<float> expectedOutputData = std::vector<float>(
     {
         // Batch 0, Height 0, Width 0 x Channel (2)
         0.f, -1.1470304f,
         // Batch 0, Height 0, Width 1 x Channel (2)
         0.f, -0.22940612f,
         // Batch 0, Height 1, Width 0 x Channel (2)
         0.f, -0.22940612f,
         // Batch 0, Height 1, Width 1 x Channel (2)
         0.f,  1.6058424f,
         // Batch 1, Height 0, Width 0 x Channel (2)
         0.99995005f, -0.7337929f,
         // Batch 1, Height 0, Width 1 x Channel (2)
         -0.99995005f,  0.52413774f,
         // Batch 1, Height 1, Width 0 x Channel (2)
         -0.99995005f, -1.1531031f,
         // Batch 1, Height 1, Width 1 x Channel (2)
         0.99995005f,  1.3627582f
     });
     InstanceNormalizationEndToEnd(defaultBackends,
                                   DataLayout::NHWC,
                                   inputTensorInfo,
                                   outputTensorInfo,
                                   inputData,
                                   expectedOutputData,
                                   gamma,
                                   beta,
                                   eps);
 }
InstanceNormalizationNhwcEndToEndTest2()
void InstanceNormalizationNhwcEndToEndTest2 (const std::vector< armnn::BackendId > & defaultBackends)
Definition at line 239 of file InstanceNormalizationEndToEndTestImpl.cpp.
References armnn::Float32, and armnn::NHWC.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace armnn;
     const float eps        = 0.0001f;
     const float beta       = 10.0f;
     const float gamma      = 2.0f;
     TensorShape inputShape{2, 2, 2, 2};
     TensorShape outputShape{2, 2, 2, 2};
     TensorInfo outputTensorInfo(outputShape, DataType::Float32);
     TensorInfo inputTensorInfo(inputShape, DataType::Float32);
     std::vector<float> inputData = std::vector<float>(
     {
         // Batch 0, Height 0, Width 0 x Channel (2)
         0.f,  1.f,
         // Batch 0, Height 0, Width 1 x Channel (2)
         0.f,  2.f,
         // Batch 0, Height 1, Width 0 x Channel (2)
         0.f,  2.f,
         // Batch 0, Height 1, Width 1 x Channel (2)
         0.f,  4.f,
         // Batch 1, Height 0, Width 0 x Channel (2)
         1.f, -1.f,
         // Batch 1, Height 0, Width 1 x Channel (2)
         -1.f,  2.f,
         // Batch 1, Height 1, Width 0 x Channel (2)
         -1.f, -2.f,
         // Batch 1, Height 1, Width 1 x Channel (2)
         1.f,  4.f
     });
     std::vector<float> expectedOutputData = std::vector<float>(
     {
         // Batch 0, Height 0, Width 0 x Channel (2)
         10.f,     7.7059393f,
         // Batch 0, Height 0, Width 1 x Channel (2)
         10.f,     9.541187f,
         // Batch 0, Height 1, Width 0 x Channel (2)
         10.f,     9.541187f,
         // Batch 0, Height 1, Width 1 x Channel (2)
         10.f,     13.211685f,
         // Batch 1, Height 0, Width 0 x Channel (2)
         11.9999f, 8.532414f,
         // Batch 1, Height 0, Width 1 x Channel (2)
         8.0001f,  11.048275f,
         // Batch 1, Height 1, Width 0 x Channel (2)
         8.0001f,  7.693794f,
         // Batch 1, Height 1, Width 1 x Channel (2)
         11.9999f, 12.725516f
     });
     InstanceNormalizationEndToEnd(defaultBackends,
                                   DataLayout::NHWC,
                                   inputTensorInfo,
                                   outputTensorInfo,
                                   inputData,
                                   expectedOutputData,
                                   gamma,
                                   beta,
                                   eps);
 }