ArmNN: src/backends/neon/test/NeonMemCopyTests.cpp File Reference
NeonMemCopyTests.cpp File Reference
#include "NeonWorkloadFactoryHelper.hpp"
#include <aclCommon/test/MemCopyTestImpl.hpp>
#include <neon/NeonWorkloadFactory.hpp>
#include <reference/RefWorkloadFactory.hpp>
#include <reference/test/RefWorkloadFactoryHelper.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndNeon)
BOOST_AUTO_TEST_CASE (CopyBetweenNeonAndCpu)
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndNeonWithSubtensors)
BOOST_AUTO_TEST_CASE (CopyBetweenNeonAndCpuWithSubtensors)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndNeon)
Definition at line 19 of file NeonMemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::RefWorkloadFactory, armnn::NeonWorkloadFactory, armnn::DataType::Float32>(false);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (CopyBetweenNeonAndCpu)
Definition at line 26 of file NeonMemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::NeonWorkloadFactory, armnn::RefWorkloadFactory, armnn::DataType::Float32>(false);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (CopyBetweenCpuAndNeonWithSubtensors)
Definition at line 33 of file NeonMemCopyTests.cpp.
References CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::RefWorkloadFactory, armnn::NeonWorkloadFactory, armnn::DataType::Float32>(true);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (CopyBetweenNeonAndCpuWithSubtensors)
Definition at line 40 of file NeonMemCopyTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), CompareTensors(), LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     LayerTestResult<float, 4> result =
         MemCopyTest<armnn::NeonWorkloadFactory, armnn::RefWorkloadFactory, armnn::DataType::Float32>(true);
     BOOST_TEST(CompareTensors(result.output, result.outputExpected));
 }