ArmNN: src/backends/neon/test/NeonEndToEndTests.cpp File Reference
NeonEndToEndTests.cpp File Reference
#include <backendsCommon/test/EndToEndTestImpl.hpp>
#include <backendsCommon/test/ActivationEndToEndTestImpl.hpp>
#include <backendsCommon/test/ArgMinMaxEndToEndTestImpl.hpp>
#include <backendsCommon/test/ComparisonEndToEndTestImpl.hpp>
#include <backendsCommon/test/ConcatEndToEndTestImpl.hpp>
#include <backendsCommon/test/DepthToSpaceEndToEndTestImpl.hpp>
#include <backendsCommon/test/DequantizeEndToEndTestImpl.hpp>
#include <backendsCommon/test/DetectionPostProcessEndToEndTestImpl.hpp>
#include <backendsCommon/test/ElementwiseUnaryEndToEndTestImpl.hpp>
#include <backendsCommon/test/FillEndToEndTestImpl.hpp>
#include <backendsCommon/test/InstanceNormalizationEndToEndTestImpl.hpp>
#include <backendsCommon/test/PreluEndToEndTestImpl.hpp>
#include <backendsCommon/test/QLstmEndToEndTestImpl.hpp>
#include <backendsCommon/test/QuantizedLstmEndToEndTestImpl.hpp>
#include <backendsCommon/test/SpaceToDepthEndToEndTestImpl.hpp>
#include <backendsCommon/test/SplitterEndToEndTestImpl.hpp>
#include <backendsCommon/test/TransposeConvolution2dEndToEndTestImpl.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (NeonAbsEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (ConstantUsage_Neon_Float32)
BOOST_AUTO_TEST_CASE (NeonGreaterSimpleEndToEndTest)
BOOST_AUTO_TEST_CASE (NeonGreaterSimpleEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonGreaterBroadcastEndToEndTest)
BOOST_AUTO_TEST_CASE (NeonGreaterBroadcastEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim0Test)
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim0Uint8Test)
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim1Test)
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim1Uint8Test)
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim3Test)
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim3Uint8Test)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat32)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwUint8)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwInt16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat32)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcUint8)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcInt16)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleTest)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetTest)
BOOST_AUTO_TEST_CASE (NeonEluEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (NeonEluEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestQAsymmS8)
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestQAsymmU8)
BOOST_AUTO_TEST_CASE (NeonPreluEndToEndFloat32Test)
BOOST_AUTO_TEST_CASE (NeonPreluEndToEndTestUint8Test)
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNhwcEndToEndTest1)
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNchwEndToEndTest1)
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNhwcEndToEndTest2)
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNchwEndToEndTest2)
BOOST_AUTO_TEST_CASE (NeonSplitter1dEndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter1dEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim2EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim2EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim2EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim3EndToEndTest)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim2EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim3EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (NeonQuantizedLstmEndToEndTest)
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndFloatNchwTest)
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndUint8NchwTest)
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndFloatNhwcTest)
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndUint8NhwcTest)
BOOST_AUTO_TEST_CASE (NeonImportNonAlignedInputPointerTest)
BOOST_AUTO_TEST_CASE (NeonExportNonAlignedOutputPointerTest)
BOOST_AUTO_TEST_CASE (NeonImportAlignedPointerTest)
BOOST_AUTO_TEST_CASE (NeonImportOnlyWorkload)
BOOST_AUTO_TEST_CASE (NeonExportOnlyWorkload)
BOOST_AUTO_TEST_CASE (NeonImportAndExportWorkload)
BOOST_AUTO_TEST_CASE (NeonExportOutputWithSeveralOutputSlotConnectionsTest)
BOOST_AUTO_TEST_CASE (NeonInstanceNormalizationNchwEndToEndTest1)
BOOST_AUTO_TEST_CASE (NeonInstanceNormalizationNchwEndToEndTest2)
BOOST_AUTO_TEST_CASE (NeonFillEndToEndTest)
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (NeonFillEndToEndTestInt32)
BOOST_AUTO_TEST_CASE (NeonArgMaxSimpleTest)
BOOST_AUTO_TEST_CASE (NeonArgMinSimpleTest)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis0Test)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis0Test)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis1Test)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis1Test)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis2Test)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis2Test)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis3Test)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis3Test)
BOOST_AUTO_TEST_CASE (NeonArgMaxSimpleTestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMinSimpleTestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis0TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis0TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis1TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis1TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis2TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis2TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis3TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonArgMinAxis3TestQuantisedAsymm8)
BOOST_AUTO_TEST_CASE (NeonStridedSliceInvalidSliceEndToEndTest)
std::vector< float > scores ({ 0.0f, 0.9f, 0.8f, 0.0f, 0.75f, 0.72f, 0.0f, 0.6f, 0.5f, 0.0f, 0.93f, 0.95f, 0.0f, 0.5f, 0.4f, 0.0f, 0.3f, 0.2f })
std::vector< float > anchors ({ 0.5f, 0.5f, 1.0f, 1.0f, 0.5f, 0.5f, 1.0f, 1.0f, 0.5f, 0.5f, 1.0f, 1.0f, 0.5f, 10.5f, 1.0f, 1.0f, 0.5f, 10.5f, 1.0f, 1.0f, 0.5f, 100.5f, 1.0f, 1.0f })
DetectionPostProcessRegularNmsEndToEnd< armnn::DataType::Float32 > (defaultBackends, boxEncodings, scores, anchors)
void QuantizeData (uint8_t *quant, const float *dequant, const TensorInfo &info)
boxEncodingsInfo SetQuantizationScale (1.0f)
boxEncodingsInfo SetQuantizationOffset (1)
scoresInfo SetQuantizationScale (0.01f)
scoresInfo SetQuantizationOffset (0)
std::vector< float > boxEncodings ({ 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f })
std::vector< uint8_t > qBoxEncodings (boxEncodings.size(), 0)
std::vector< uint8_t > qScores (scores.size(), 0)
std::vector< uint8_t > qAnchors (anchors.size(), 0)
QuantizeData (qBoxEncodings.data(), boxEncodings.data(), boxEncodingsInfo)
QuantizeData (qScores.data(), scores.data(), scoresInfo)
QuantizeData (qAnchors.data(), anchors.data(), anchorsInfo)
DetectionPostProcessRegularNmsEndToEnd< armnn::DataType::QAsymmU8 > (defaultBackends, qBoxEncodings, qScores, qAnchors, 1.0f, 1, 0.01f, 0, 0.5f, 0)
DetectionPostProcessFastNmsEndToEnd< armnn::DataType::Float32 > (defaultBackends, boxEncodings, scores, anchors)
armnn::TensorInfo scoresInfo ({ 1, 6, 3 }, armnn::DataType::Float32)
armnn::TensorInfo anchorsInfo ({ 6, 4 }, armnn::DataType::Float32)
DetectionPostProcessFastNmsEndToEnd< armnn::DataType::QAsymmU8 > (defaultBackends, qBoxEncodings, qScores, qAnchors, 1.0f, 1, 0.01f, 0, 0.5f, 0)
BOOST_AUTO_TEST_CASE (NeonQLstmEndToEndTest)
Variables
std::vector< armnn::BackendId > defaultBackends = {armnn::Compute::CpuAcc}
armnn::TensorInfo scoresInfo ({ 1, 6, 3 }, armnn::DataType::Float32)
armnn::TensorInfo anchorsInfo ({ 6, 4 }, armnn::DataType::Float32)
Function Documentation
anchors()
std::vector< float > anchors ({ 0.5f, 0.5f, 1.0f, 1.0f, 0.5f, 0.5f, 1.0f, 1.0f, 0.5f, 0.5f, 1.0f, 1.0f, 0.5f, 10.5f, 1.0f, 1.0f, 0.5f, 10.5f, 1.0f, 1.0f, 0.5f, 100.5f, 1.0f, 1.0f })
Referenced by NetworkImpl::AddDetectionPostProcessLayer(), BOOST_AUTO_TEST_CASE(), armnnSerializer::CreateDetectionPostProcessLayer(), armnn::DetectionPostProcess(), DetectionPostProcessImpl(), DetectionPostProcessTestImpl(), RefDetectionPostProcessWorkload::Execute(), armnnSerializer::GetFlatBufferArgMinMaxFunction(), NetworkImpl::GetGraph(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), LayerSupportHandle::LayerSupportHandle(), QuantizeData(), FLATBUFFERS_FINAL_CLASS::Verify(), ILayerVisitor::VisitConcatLayer(), and ILayerSupport::~ILayerSupport().
anchorsInfo()
armnn::TensorInfo anchorsInfo ({ 6, 4 } , armnn::DataType::Float32)
BOOST_AUTO_TEST_CASE() [1/93]
BOOST_AUTO_TEST_CASE (NeonAbsEndToEndTestFloat32)
Definition at line 32 of file NeonEndToEndTests.cpp.
References defaultBackends.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     std::vector<float> expectedOutput =
     {
         1.f, 1.f, 1.f, 1.f, 5.f, 5.f, 5.f, 5.f,
         3.f, 3.f, 3.f, 3.f, 4.f, 4.f, 4.f, 4.f
     };
     ElementwiseUnarySimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                              UnaryOperation::Abs,
                                                              expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [2/93]
BOOST_AUTO_TEST_CASE (ConstantUsage_Neon_Float32)
Definition at line 46 of file NeonEndToEndTests.cpp.
References BOOST_AUTO_TEST_CASE(), IOutputSlot::Connect(), armnn::CpuAcc, armnn::CpuRef, IRuntime::Create(), INetwork::Create(), defaultBackends, armnn::Float32, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), armnn::Optimize(), IOutputSlot::SetTensorInfo(), and armnn::Success.
 {
     BOOST_TEST(ConstantUsageFloat32Test(defaultBackends));
 }
BOOST_AUTO_TEST_CASE() [3/93]
BOOST_AUTO_TEST_CASE (NeonGreaterSimpleEndToEndTest)
Definition at line 91 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 0, 0, 0,  1, 1, 1, 1,
                                                 0, 0, 0, 0,  0, 0, 0, 0 });
     ComparisonSimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                        ComparisonOperation::Greater,
                                                        expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [4/93]
BOOST_AUTO_TEST_CASE (NeonGreaterSimpleEndToEndUint8Test)
Definition at line 101 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 0, 0, 0,  1, 1, 1, 1,
                                                 0, 0, 0, 0,  0, 0, 0, 0 });
     ComparisonSimpleEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                ComparisonOperation::Greater,
                                                                expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [5/93]
BOOST_AUTO_TEST_CASE (NeonGreaterBroadcastEndToEndTest)
Definition at line 111 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 1, 0, 0, 0, 1,
                                                 1, 1, 1, 1, 1, 1 });
     ComparisonBroadcastEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                           ComparisonOperation::Greater,
                                                           expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [6/93]
BOOST_AUTO_TEST_CASE (NeonGreaterBroadcastEndToEndUint8Test)
Definition at line 121 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 1, 0, 0, 0, 1,
                                                 1, 1, 1, 1, 1, 1 });
     ComparisonBroadcastEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                   ComparisonOperation::Greater,
                                                                   expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [7/93]
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim0Test)
Definition at line 131 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [8/93]
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim0Uint8Test)
Definition at line 136 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [9/93]
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim1Test)
Definition at line 141 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [10/93]
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim1Uint8Test)
Definition at line 146 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [11/93]
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim3Test)
Definition at line 151 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [12/93]
BOOST_AUTO_TEST_CASE (NeonConcatEndToEndDim3Uint8Test)
Definition at line 156 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [13/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat32)
Definition at line 162 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [14/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat16)
Definition at line 167 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [15/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwUint8)
Definition at line 172 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [16/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwInt16)
Definition at line 177 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [17/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat32)
Definition at line 182 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [18/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat16)
Definition at line 187 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [19/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcUint8)
Definition at line 192 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [20/93]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcInt16)
Definition at line 197 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [21/93]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleTest)
Definition at line 203 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [22/93]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetTest)
Definition at line 208 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndOffset<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [23/93]
BOOST_AUTO_TEST_CASE (NeonEluEndToEndTestFloat32)
Definition at line 213 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [24/93]
BOOST_AUTO_TEST_CASE (NeonEluEndToEndTestFloat16)
Definition at line 218 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [25/93]
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestFloat32)
Definition at line 224 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [26/93]
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestFloat16)
Definition at line 229 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [27/93]
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestQAsymmS8)
Definition at line 234 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QAsymmS8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [28/93]
BOOST_AUTO_TEST_CASE (NeonHardSwishEndToEndTestQAsymmU8)
Definition at line 239 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [29/93]
BOOST_AUTO_TEST_CASE (NeonPreluEndToEndFloat32Test)
Definition at line 244 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndNegativeTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [30/93]
BOOST_AUTO_TEST_CASE (NeonPreluEndToEndTestUint8Test)
Definition at line 249 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndPositiveTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [31/93]
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNhwcEndToEndTest1)
Definition at line 254 of file NeonEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNhwcEndToEndTest1().
 {
     SpaceToDepthNhwcEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [32/93]
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNchwEndToEndTest1)
Definition at line 259 of file NeonEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNchwEndToEndTest1().
 {
     SpaceToDepthNchwEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [33/93]
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNhwcEndToEndTest2)
Definition at line 264 of file NeonEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNhwcEndToEndTest2().
 {
     SpaceToDepthNhwcEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [34/93]
BOOST_AUTO_TEST_CASE (NeonSpaceToDepthNchwEndToEndTest2)
Definition at line 269 of file NeonEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNchwEndToEndTest2().
 {
     SpaceToDepthNchwEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [35/93]
BOOST_AUTO_TEST_CASE (NeonSplitter1dEndToEndTest)
Definition at line 274 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter1dEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [36/93]
BOOST_AUTO_TEST_CASE (NeonSplitter1dEndToEndUint8Test)
Definition at line 279 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter1dEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [37/93]
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim0EndToEndTest)
Definition at line 284 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [38/93]
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim1EndToEndTest)
Definition at line 289 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [39/93]
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim0EndToEndUint8Test)
Definition at line 294 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [40/93]
BOOST_AUTO_TEST_CASE (NeonSplitter2dDim1EndToEndUint8Test)
Definition at line 299 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [41/93]
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim0EndToEndTest)
Definition at line 304 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [42/93]
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim1EndToEndTest)
Definition at line 309 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [43/93]
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim2EndToEndTest)
Definition at line 314 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [44/93]
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim0EndToEndUint8Test)
Definition at line 319 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [45/93]
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim1EndToEndUint8Test)
Definition at line 324 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [46/93]
BOOST_AUTO_TEST_CASE (NeonSplitter3dDim2EndToEndUint8Test)
Definition at line 329 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [47/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim0EndToEndTest)
Definition at line 334 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [48/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim1EndToEndTest)
Definition at line 339 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [49/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim2EndToEndTest)
Definition at line 344 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [50/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim3EndToEndTest)
Definition at line 349 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [51/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim0EndToEndUint8Test)
Definition at line 354 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [52/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim1EndToEndUint8Test)
Definition at line 359 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [53/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim2EndToEndUint8Test)
Definition at line 364 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [54/93]
BOOST_AUTO_TEST_CASE (NeonSplitter4dDim3EndToEndUint8Test)
Definition at line 369 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [55/93]
BOOST_AUTO_TEST_CASE (NeonQuantizedLstmEndToEndTest)
Definition at line 374 of file NeonEndToEndTests.cpp.
References defaultBackends, and QuantizedLstmEndToEnd().
 {
     QuantizedLstmEndToEnd(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [56/93]
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndFloatNchwTest)
Definition at line 379 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::Float32, armnn::DataType::Float32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [57/93]
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndUint8NchwTest)
Definition at line 385 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [58/93]
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndFloatNhwcTest)
Definition at line 391 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::Float32, armnn::DataType::Float32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [59/93]
BOOST_AUTO_TEST_CASE (NeonTransposeConvolution2dEndToEndUint8NhwcTest)
Definition at line 397 of file NeonEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [60/93]
BOOST_AUTO_TEST_CASE (NeonImportNonAlignedInputPointerTest)
Definition at line 403 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ImportNonAlignedInputPointerTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [61/93]
BOOST_AUTO_TEST_CASE (NeonExportNonAlignedOutputPointerTest)
Definition at line 408 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ExportNonAlignedOutputPointerTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [62/93]
BOOST_AUTO_TEST_CASE (NeonImportAlignedPointerTest)
Definition at line 413 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ImportAlignedPointerTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [63/93]
BOOST_AUTO_TEST_CASE (NeonImportOnlyWorkload)
Definition at line 418 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ImportOnlyWorkload(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [64/93]
BOOST_AUTO_TEST_CASE (NeonExportOnlyWorkload)
Definition at line 423 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ExportOnlyWorkload(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [65/93]
BOOST_AUTO_TEST_CASE (NeonImportAndExportWorkload)
Definition at line 428 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ImportAndExportWorkload(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [66/93]
BOOST_AUTO_TEST_CASE (NeonExportOutputWithSeveralOutputSlotConnectionsTest)
Definition at line 433 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ExportOutputWithSeveralOutputSlotConnectionsTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [67/93]
BOOST_AUTO_TEST_CASE (NeonInstanceNormalizationNchwEndToEndTest1)
Definition at line 439 of file NeonEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNchwEndToEndTest1().
 {
     InstanceNormalizationNchwEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [68/93]
BOOST_AUTO_TEST_CASE (NeonInstanceNormalizationNchwEndToEndTest2)
Definition at line 444 of file NeonEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNchwEndToEndTest2().
 {
     InstanceNormalizationNchwEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [69/93]
BOOST_AUTO_TEST_CASE (NeonFillEndToEndTest)
Definition at line 450 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [70/93]
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestFloat16)
Definition at line 455 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [71/93]
BOOST_AUTO_TEST_CASE (NeonFillEndToEndTestInt32)
Definition at line 460 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Signed32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [72/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxSimpleTest)
Definition at line 466 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxEndToEndSimple<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [73/93]
BOOST_AUTO_TEST_CASE (NeonArgMinSimpleTest)
Definition at line 471 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinEndToEndSimple<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [74/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis0Test)
Definition at line 476 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [75/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis0Test)
Definition at line 481 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [76/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis1Test)
Definition at line 486 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [77/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis1Test)
Definition at line 491 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [78/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis2Test)
Definition at line 496 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [79/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis2Test)
Definition at line 501 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [80/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis3Test)
Definition at line 506 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [81/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis3Test)
Definition at line 511 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [82/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxSimpleTestQuantisedAsymm8)
Definition at line 516 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [83/93]
BOOST_AUTO_TEST_CASE (NeonArgMinSimpleTestQuantisedAsymm8)
Definition at line 521 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [84/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis0TestQuantisedAsymm8)
Definition at line 526 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [85/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis0TestQuantisedAsymm8)
Definition at line 531 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [86/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis1TestQuantisedAsymm8)
Definition at line 536 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [87/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis1TestQuantisedAsymm8)
Definition at line 541 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [88/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis2TestQuantisedAsymm8)
Definition at line 546 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [89/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis2TestQuantisedAsymm8)
Definition at line 551 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [90/93]
BOOST_AUTO_TEST_CASE (NeonArgMaxAxis3TestQuantisedAsymm8)
Definition at line 556 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [91/93]
BOOST_AUTO_TEST_CASE (NeonArgMinAxis3TestQuantisedAsymm8)
Definition at line 561 of file NeonEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [92/93]
BOOST_AUTO_TEST_CASE (NeonStridedSliceInvalidSliceEndToEndTest)
Definition at line 566 of file NeonEndToEndTests.cpp.
References anchors(), armnn::BOOST_AUTO_TEST_CASE(), boxEncodings(), defaultBackends, and scores().
 {
     StridedSliceInvalidSliceEndToEndTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [93/93]
BOOST_AUTO_TEST_CASE (NeonQLstmEndToEndTest)
Definition at line 735 of file NeonEndToEndTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), defaultBackends, and QLstmEndToEnd().
 {
     QLstmEndToEnd(defaultBackends);
 }
boxEncodings()
std::vector< float > boxEncodings ({ 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f })
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), armnn::DetectionPostProcess(), DetectionPostProcessImpl(), DetectionPostProcessTestImpl(), RefDetectionPostProcessWorkload::Execute(), LayerSupportHandle::LayerSupportHandle(), QuantizeData(), and ILayerSupport::~ILayerSupport().
DetectionPostProcessFastNmsEndToEnd< armnn::DataType::Float32 >()
DetectionPostProcessFastNmsEndToEnd< armnn::DataType::Float32 > (defaultBackends , boxEncodings , scores , anchors)
DetectionPostProcessFastNmsEndToEnd< armnn::DataType::QAsymmU8 >()
DetectionPostProcessFastNmsEndToEnd< armnn::DataType::QAsymmU8 > (defaultBackends , qBoxEncodings , qScores , qAnchors , 1. 0f, 1 , 0. 01f, 0 , 0. 5f, 0)
DetectionPostProcessRegularNmsEndToEnd< armnn::DataType::Float32 >()
DetectionPostProcessRegularNmsEndToEnd< armnn::DataType::Float32 > (defaultBackends , boxEncodings , scores , anchors)
DetectionPostProcessRegularNmsEndToEnd< armnn::DataType::QAsymmU8 >()
DetectionPostProcessRegularNmsEndToEnd< armnn::DataType::QAsymmU8 > (defaultBackends , qBoxEncodings , qScores , qAnchors , 1. 0f, 1 , 0. 01f, 0 , 0. 5f, 0)
qAnchors()
std::vector< uint8_t > qAnchors (anchors. size(), 0)
Referenced by BOOST_AUTO_TEST_CASE(), and QuantizeData().
qBoxEncodings()
std::vector< uint8_t > qBoxEncodings (boxEncodings. size(), 0)
Referenced by BOOST_AUTO_TEST_CASE(), and QuantizeData().
qScores()
std::vector< uint8_t > qScores (scores. size(), 0)
Referenced by BOOST_AUTO_TEST_CASE(), and QuantizeData().
QuantizeData() [1/4]
void QuantizeData (uint8_t * quant, const float * dequant, const TensorInfo & info) inline
Definition at line 600 of file NeonEndToEndTests.cpp.
References anchors(), anchorsInfo, armnn::BOOST_AUTO_TEST_CASE(), boxEncodings(), defaultBackends, armnn::Float32, TensorInfo::GetNumElements(), TensorInfo::GetQuantizationOffset(), TensorInfo::GetQuantizationScale(), qAnchors(), qBoxEncodings(), qScores(), scores(), scoresInfo, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     for (size_t i = 0; i < info.GetNumElements(); i++)
     {
         quant[i] = armnn::Quantize<uint8_t>(dequant[i], info.GetQuantizationScale(), info.GetQuantizationOffset());
     }
 }
QuantizeData() [2/4]
QuantizeData (qBoxEncodings. data(), boxEncodings. data(), boxEncodingsInfo)
QuantizeData() [3/4]
QuantizeData (qScores. data(), scores. data(), scoresInfo)
QuantizeData() [4/4]
QuantizeData (qAnchors. data(), anchors. data(), anchorsInfo)
scores()
std::vector< float > scores ({ 0.0f, 0.9f, 0.8f, 0.0f, 0.75f, 0.72f, 0.0f, 0.6f, 0.5f, 0.0f, 0.93f, 0.95f, 0.0f, 0.5f, 0.4f, 0.0f, 0.3f, 0.2f })
Initial value:
{
    std::vector<float> boxEncodings({
                                        0.0f, 0.0f, 0.0f, 0.0f,
                                        0.0f, 1.0f, 0.0f, 0.0f,
                                        0.0f, -1.0f, 0.0f, 0.0f,
                                        0.0f, 0.0f, 0.0f, 0.0f,
                                        0.0f, 1.0f, 0.0f, 0.0f,
                                        0.0f, 0.0f, 0.0f, 0.0f
                                    })
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), armnn::DetectionPostProcess(), DetectionPostProcessImpl(), DetectionPostProcessTestImpl(), RefDetectionPostProcessWorkload::Execute(), LayerSupportHandle::LayerSupportHandle(), QuantizeData(), and ILayerSupport::~ILayerSupport().
scoresInfo()
armnn::TensorInfo scoresInfo ({ 1, 6, 3 } , armnn::DataType::Float32)
SetQuantizationOffset() [1/2]
boxEncodingsInfo SetQuantizationOffset (1)
Referenced by TensorInfo::HasMultipleQuantizationScales().
SetQuantizationOffset() [2/2]
anchorsInfo SetQuantizationOffset (0)
SetQuantizationScale() [1/2]
boxEncodingsInfo SetQuantizationScale (1. 0f)
Referenced by TensorInfo::HasMultipleQuantizationScales().
SetQuantizationScale() [2/2]
anchorsInfo SetQuantizationScale (0. 01f)
Variable Documentation
anchorsInfo
armnn::TensorInfo anchorsInfo({ 6, 4 }, armnn::DataType::Float32) ({ 6, 4 } , armnn::DataType::Float32)
Referenced by BOOST_AUTO_TEST_CASE(), DetectionPostProcessFastNmsQuantizedTest(), DetectionPostProcessImpl(), DetectionPostProcessRegularNmsQuantizedTest(), DetectionPostProcessTestImpl(), RefDetectionPostProcessWorkload::Execute(), QuantizeData(), and DetectionPostProcessQueueDescriptor::Validate().
defaultBackends
std::vector<armnn::BackendId> defaultBackends = {armnn::Compute::CpuAcc}
Definition at line 29 of file NeonEndToEndTests.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and QuantizeData().
scoresInfo
armnn::TensorInfo scoresInfo({ 1, 6, 3 }, armnn::DataType::Float32) ({ 1, 6, 3 } , armnn::DataType::Float32)
Initial value:
{
    armnn::TensorInfo boxEncodingsInfo({ 1, 6, 4 }, armnn::DataType::Float32)
Referenced by BOOST_AUTO_TEST_CASE(), DetectionPostProcessFastNmsQuantizedTest(), DetectionPostProcessImpl(), DetectionPostProcessRegularNmsQuantizedTest(), DetectionPostProcessTestImpl(), RefDetectionPostProcessWorkload::Execute(), QuantizeData(), and DetectionPostProcessQueueDescriptor::Validate().