ArmNN: src/profiling/test/ProfilingConnectionDumpToFileDecoratorTests.cpp File Reference
ProfilingConnectionDumpToFileDecoratorTests.cpp File Reference
#include "../ProfilingConnectionDumpToFileDecorator.hpp"
#include <Filesystem.hpp>
#include <Runtime.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <armnn/utility/NumericCast.hpp>
#include <fstream>
#include <sstream>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (DumpIncomingInvalidFile)
BOOST_AUTO_TEST_CASE (DumpIncomingInvalidFileIgnoreErrors)
BOOST_AUTO_TEST_CASE (DumpIncomingValidFile)
BOOST_AUTO_TEST_CASE (DumpOutgoingInvalidFile)
BOOST_AUTO_TEST_CASE (DumpOutgoingInvalidFileIgnoreErrors)
BOOST_AUTO_TEST_CASE (DumpOutgoingValidFile)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (DumpIncomingInvalidFile)
Definition at line 79 of file ProfilingConnectionDumpToFileDecoratorTests.cpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, and ProfilingConnectionDumpToFileDecorator::ReadPacket().
 {
     armnn::IRuntime::CreationOptions::ExternalProfilingOptions options;
     options.m_IncomingCaptureFile = "/";
     options.m_OutgoingCaptureFile =  "";
     ProfilingConnectionDumpToFileDecorator decorator(std::make_unique<DummyProfilingConnection>(), options, false);
     BOOST_CHECK_THROW(decorator.ReadPacket(0), armnn::RuntimeException);
 }
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (DumpIncomingInvalidFileIgnoreErrors)
Definition at line 88 of file ProfilingConnectionDumpToFileDecoratorTests.cpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, and ProfilingConnectionDumpToFileDecorator::ReadPacket().
 {
     armnn::IRuntime::CreationOptions::ExternalProfilingOptions options;
     options.m_IncomingCaptureFile = "/";
     options.m_OutgoingCaptureFile =  "";
     ProfilingConnectionDumpToFileDecorator decorator(std::make_unique<DummyProfilingConnection>(), options, true);
     BOOST_CHECK_NO_THROW(decorator.ReadPacket(0));
 }
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (DumpIncomingValidFile)
Definition at line 97 of file ProfilingConnectionDumpToFileDecoratorTests.cpp.
References ProfilingConnectionDumpToFileDecorator::Close(), IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, armnnUtils::Filesystem::NamedTempFile(), and ProfilingConnectionDumpToFileDecorator::ReadPacket().
 {
     fs::path fileName = armnnUtils::Filesystem::NamedTempFile("Armnn-DumpIncomingValidFileTest-TempFile");
     armnn::IRuntime::CreationOptions::ExternalProfilingOptions options;
     options.m_IncomingCaptureFile = fileName.string();
     options.m_OutgoingCaptureFile =  "";
     ProfilingConnectionDumpToFileDecorator decorator(std::make_unique<DummyProfilingConnection>(), options, false);
     // NOTE: unique_ptr is needed here because operator=() is deleted for Packet
     std::unique_ptr<arm::pipe::Packet> packet;
     BOOST_CHECK_NO_THROW(packet = std::make_unique<arm::pipe::Packet>(decorator.ReadPacket(0)));
     decorator.Close();
     std::vector<char> data = ReadDumpFile(options.m_IncomingCaptureFile);
     const char* packetData = reinterpret_cast<const char*>(packet->GetData());
     // check if the data read back from the dump file matches the original
     constexpr unsigned int bytesToSkip = 2u * sizeof(uint32_t); // skip header and packet length
     int diff = std::strncmp(data.data() + bytesToSkip, packetData, g_DataLength);
     BOOST_CHECK(diff == 0);
     fs::remove(fileName);
 }
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (DumpOutgoingInvalidFile)
Definition at line 123 of file ProfilingConnectionDumpToFileDecoratorTests.cpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, and ProfilingConnectionDumpToFileDecorator::WritePacket().
 {
     armnn::IRuntime::CreationOptions::ExternalProfilingOptions options;
     options.m_IncomingCaptureFile = "";
     options.m_OutgoingCaptureFile = "/";
     ProfilingConnectionDumpToFileDecorator decorator(std::make_unique<DummyProfilingConnection>(), options, false);
     BOOST_CHECK_THROW(decorator.WritePacket(g_DataPtr, g_DataLength), armnn::RuntimeException);
 }
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (DumpOutgoingInvalidFileIgnoreErrors)
Definition at line 132 of file ProfilingConnectionDumpToFileDecoratorTests.cpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, and ProfilingConnectionDumpToFileDecorator::WritePacket().
 {
     armnn::IRuntime::CreationOptions::ExternalProfilingOptions options;
     options.m_IncomingCaptureFile = "";
     options.m_OutgoingCaptureFile = "/";
     ProfilingConnectionDumpToFileDecorator decorator(std::make_unique<DummyProfilingConnection>(), options, true);
     BOOST_CHECK_NO_THROW(decorator.WritePacket(g_DataPtr, g_DataLength));
     bool success = decorator.WritePacket(g_DataPtr, g_DataLength);
     BOOST_CHECK(!success);
 }
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (DumpOutgoingValidFile)
Definition at line 145 of file ProfilingConnectionDumpToFileDecoratorTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), ProfilingConnectionDumpToFileDecorator::Close(), IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, armnnUtils::Filesystem::NamedTempFile(), and ProfilingConnectionDumpToFileDecorator::WritePacket().
 {
     fs::path fileName = armnnUtils::Filesystem::NamedTempFile("Armnn-DumpOutgoingValidFileTest-TempFile");
     armnn::IRuntime::CreationOptions::ExternalProfilingOptions options;
     options.m_IncomingCaptureFile = "";
     options.m_OutgoingCaptureFile = fileName.string();
     ProfilingConnectionDumpToFileDecorator decorator(std::make_unique<DummyProfilingConnection>(), options, false);
     bool success = false;
     BOOST_CHECK_NO_THROW(success = decorator.WritePacket(g_DataPtr, g_DataLength));
     BOOST_CHECK(success);
     decorator.Close();
     std::vector<char> data = ReadDumpFile(options.m_OutgoingCaptureFile);
     // check if the data read back from the dump file matches the original
     int diff = std::strncmp(data.data(), g_Data.data(), g_DataLength);
     BOOST_CHECK(diff == 0);
     fs::remove(fileName);
 }