ArmNN: src/backends/backendsCommon/test/layerTests/ReductionTestImpl.cpp File Reference
ReductionTestImpl.cpp File Reference
#include "ReductionTestImpl.hpp"
#include <backendsCommon/test/DataTypeUtils.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
#include <iostream>
Functions
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< float, 4 > ReduceMaxSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< float, 4 > ReduceMaxNegativeAxisTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< float, 4 > ReduceMaxSimpleTest2 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< float, 4 > ReduceMinSimpleTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< float, 4 > ReduceMinNegativeAxisTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< float, 4 > ReduceMaxSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< float, 4 > ReduceMaxNegativeAxisTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< float, 4 > ReduceMaxSimpleTest2< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< float, 4 > ReduceMinSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template LayerTestResult< float, 4 > ReduceMinNegativeAxisTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
ReduceMaxNegativeAxisTest()
LayerTestResult<float, 4> ReduceMaxNegativeAxisTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 122 of file ReductionTestImpl.cpp.
References armnn::Float32, armnn::Max, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     const armnn::TensorShape inputShape{ 1, 1, 2, 3 };
     const armnn::TensorShape outputShape{ 1, 1, 2, 1};
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Float32);
     std::vector<float> inputValues
     ({
          1001.0f, 11.0f,   1003.0f,
          10.0f,   1002.0f, 12.0f
     });
     std::vector<float> outputValues
     ({
         1003.0f, 1002.0f
      });
     return ReductionTestCommon<ArmnnType>(workloadFactory,
                                           memoryManager,
                                           tensorHandleFactory,
                                           inputTensorInfo,
                                           outputTensorInfo,
                                           inputValues,
                                           outputValues,
                                           { -1 },
                                           armnn::ReduceOperation::Max,
                                           true);
 }
ReduceMaxNegativeAxisTest< armnn::DataType::Float32 >()
template LayerTestResult<float, 4> ReduceMaxNegativeAxisTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ReduceMaxSimpleTest()
LayerTestResult<float, 4> ReduceMaxSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 82 of file ReductionTestImpl.cpp.
References armnn::Float32, armnn::Max, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     const armnn::TensorShape inputShape{ 1, 1, 2, 3 };
     const armnn::TensorShape outputShape{ 1, 1, 1, 3};
         armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Float32);
     std::vector<float> inputValues
     ({
         1001.0f, 11.0f,   1003.0f,
         10.0f,   1002.0f, 12.0f
     });
     std::vector<float> outputValues
     ({
         1001.0f, 1002.0f, 1003.0f
     });
     return ReductionTestCommon<ArmnnType>(workloadFactory,
                                        memoryManager,
                                        tensorHandleFactory,
                                        inputTensorInfo,
                                        outputTensorInfo,
                                        inputValues,
                                        outputValues,
                                        { 2 },
                                        armnn::ReduceOperation::Max);
 }
ReduceMaxSimpleTest2()
LayerTestResult<float, 4> ReduceMaxSimpleTest2 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 163 of file ReductionTestImpl.cpp.
References armnn::Float32, armnn::Max, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     const armnn::TensorShape inputShape{ 1, 1, 2, 3 };
     const armnn::TensorShape outputShape{ 1, 1, 2, 1 };
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Float32);
     std::vector<float> inputValues
     ({
          1.0f, 3.0f, 2.0f,
          6.0f, 4.0f, 5.0f
     });
     std::vector<float> outputValues
     ({
         3.0f, 6.0f
     });
     return ReductionTestCommon<ArmnnType>(workloadFactory,
                                           memoryManager,
                                           tensorHandleFactory,
                                           inputTensorInfo,
                                           outputTensorInfo,
                                           inputValues,
                                           outputValues,
                                           { 3 },
                                           armnn::ReduceOperation::Max,
                                           true);
 }
ReduceMaxSimpleTest2< armnn::DataType::Float32 >()
template LayerTestResult<float, 4> ReduceMaxSimpleTest2< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ReduceMaxSimpleTest< armnn::DataType::Float32 >()
template LayerTestResult<float, 4> ReduceMaxSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ReduceMinNegativeAxisTest()
LayerTestResult<float, 4> ReduceMinNegativeAxisTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 245 of file ReductionTestImpl.cpp.
References armnn::Float32, armnn::Min, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     const armnn::TensorShape inputShape{ 1, 1, 2, 3 };
     const armnn::TensorShape outputShape{ 1, 1, 2, 1};
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Float32);
     std::vector<float> inputValues
     ({
          1001.0f, 11.0f,   1003.0f,
          10.0f,   1002.0f, 12.0f
     });
     std::vector<float> outputValues
     ({
         11.0f, 10.0f
      });
     return ReductionTestCommon<ArmnnType>(workloadFactory,
                                           memoryManager,
                                           tensorHandleFactory,
                                           inputTensorInfo,
                                           outputTensorInfo,
                                           inputValues,
                                           outputValues,
                                           { -1 },
                                           armnn::ReduceOperation::Min,
                                           true);
 }
ReduceMinNegativeAxisTest< armnn::DataType::Float32 >()
template LayerTestResult<float, 4> ReduceMinNegativeAxisTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
ReduceMinSimpleTest()
LayerTestResult<float, 4> ReduceMinSimpleTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 205 of file ReductionTestImpl.cpp.
References armnn::Float32, armnn::Min, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     const armnn::TensorShape inputShape  { 1, 1, 2, 3 };
     const armnn::TensorShape outputShape { 1, 1, 1, 3};
     armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType);
     if (armnn::IsQuantizedType<T>())
     {
         inputTensorInfo.SetQuantizationScale(1.0f);
         inputTensorInfo.SetQuantizationOffset(0);
     }
     armnn::TensorInfo outputTensorInfo(outputShape, armnn::DataType::Float32);
     std::vector<float> inputValues
     ({
         1001.0f, 11.0f,   1003.0f,
         10.0f,   1002.0f, 12.0f
     });
     std::vector<float> outputValues
     ({
         10.0f, 11.0f, 12.0f
     });
     return ReductionTestCommon<ArmnnType>(workloadFactory,
                                           memoryManager,
                                           tensorHandleFactory,
                                           inputTensorInfo,
                                           outputTensorInfo,
                                           inputValues,
                                           outputValues,
                                           { 2 },
                                           armnn::ReduceOperation::Min);
 }
ReduceMinSimpleTest< armnn::DataType::Float32 >()
template LayerTestResult<float, 4> ReduceMinSimpleTest< armnn::DataType::Float32 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)