ArmNN: src/backends/reference/test/RefMemoryManagerTests.cpp File Reference
RefMemoryManagerTests.cpp File Reference
#include <reference/RefMemoryManager.hpp>
#include <boost/test/unit_test.hpp>
Typedefs
using Pool = RefMemoryManager::Pool
Functions
BOOST_AUTO_TEST_CASE (ManageOneThing)
BOOST_AUTO_TEST_CASE (ManageTwoThings)
Typedef Documentation
Pool
using Pool = RefMemoryManager::Pool
Definition at line 12 of file RefMemoryManagerTests.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (ManageOneThing)
Definition at line 14 of file RefMemoryManagerTests.cpp.
References RefMemoryManager::Acquire(), RefMemoryManager::GetPointer(), RefMemoryManager::Manage(), and RefMemoryManager::Release().
 {
     RefMemoryManager memoryManager;
     Pool* pool = memoryManager.Manage(10);
     BOOST_CHECK(pool);
     memoryManager.Acquire();
     BOOST_CHECK(memoryManager.GetPointer(pool) != nullptr); // Yields a valid pointer
     memoryManager.Release();
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (ManageTwoThings)
Definition at line 29 of file RefMemoryManagerTests.cpp.
References RefMemoryManager::Acquire(), BOOST_AUTO_TEST_SUITE_END(), RefMemoryManager::GetPointer(), RefMemoryManager::Manage(), and RefMemoryManager::Release().
 {
     RefMemoryManager memoryManager;
     Pool* pool1 = memoryManager.Manage(10);
     Pool* pool2 = memoryManager.Manage(5);
     BOOST_CHECK(pool1);
     BOOST_CHECK(pool2);
     memoryManager.Acquire();
     void *p1 = memoryManager.GetPointer(pool1);
     void *p2 = memoryManager.GetPointer(pool2);
     BOOST_CHECK(p1);
     BOOST_CHECK(p2);
     BOOST_CHECK(p1 != p2);
     memoryManager.Release();
 }