ArmNN: src/backends/reference/test/RefEndToEndTests.cpp File Reference
RefEndToEndTests.cpp File Reference
#include <backendsCommon/test/EndToEndTestImpl.hpp>
#include <backendsCommon/test/ActivationEndToEndTestImpl.hpp>
#include <backendsCommon/test/ArgMinMaxEndToEndTestImpl.hpp>
#include <backendsCommon/test/BatchToSpaceNdEndToEndTestImpl.hpp>
#include <backendsCommon/test/ComparisonEndToEndTestImpl.hpp>
#include <backendsCommon/test/ConcatEndToEndTestImpl.hpp>
#include <backendsCommon/test/DepthToSpaceEndToEndTestImpl.hpp>
#include <backendsCommon/test/DequantizeEndToEndTestImpl.hpp>
#include <backendsCommon/test/DetectionPostProcessEndToEndTestImpl.hpp>
#include <backendsCommon/test/ElementwiseUnaryEndToEndTestImpl.hpp>
#include <backendsCommon/test/FillEndToEndTestImpl.hpp>
#include <backendsCommon/test/GatherEndToEndTestImpl.hpp>
#include <backendsCommon/test/InstanceNormalizationEndToEndTestImpl.hpp>
#include <backendsCommon/test/LogSoftmaxEndToEndTestImpl.hpp>
#include <backendsCommon/test/PreluEndToEndTestImpl.hpp>
#include <backendsCommon/test/QLstmEndToEndTestImpl.hpp>
#include <backendsCommon/test/RankEndToEndTestImpl.hpp>
#include <backendsCommon/test/ResizeEndToEndTestImpl.hpp>
#include <backendsCommon/test/SpaceToDepthEndToEndTestImpl.hpp>
#include <backendsCommon/test/SplitterEndToEndTestImpl.hpp>
#include <backendsCommon/test/TransposeConvolution2dEndToEndTestImpl.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/test/execution_monitor.hpp>
Functions
BOOST_AUTO_TEST_CASE (RefAbsEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (RefAbsEndToEndTestUint8)
BOOST_AUTO_TEST_CASE (RefAbsEndToEndTestInt16)
BOOST_AUTO_TEST_CASE (ConstantUsage_Ref_Float32)
BOOST_AUTO_TEST_CASE (ConstantUsage_Ref_Uint8)
BOOST_AUTO_TEST_CASE (Unsigned8)
BOOST_AUTO_TEST_CASE (TrivialAdd)
BOOST_AUTO_TEST_CASE (MultipleOutputs)
BOOST_AUTO_TEST_CASE (TrivialMin)
BOOST_AUTO_TEST_CASE (RefEqualSimpleEndToEndTest)
BOOST_AUTO_TEST_CASE (RefGreaterSimpleEndToEndTest)
BOOST_AUTO_TEST_CASE (RefEqualSimpleEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefGreaterSimpleEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefEqualBroadcastEndToEndTest)
BOOST_AUTO_TEST_CASE (RefGreaterBroadcastEndToEndTest)
BOOST_AUTO_TEST_CASE (RefEqualBroadcastEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefGreaterBroadcastEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndFloat32NHWCTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndUint8NHWCTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndQSymm16NHWCTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndFloat32NCHWTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndUint8NCHWTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndQSymm16NCHWTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexFloat32NHWCTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexUint8NHWCTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexQSymm16NHWCTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexFloat32NCHWTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexUint8NCHWTest)
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexQSymm16NCHWTest)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim0Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim0Uint8Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim1Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim1Uint8Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim2Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim2Uint8Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim3Test)
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim3Uint8Test)
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestBFloat16)
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestQAsymmS8)
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestQAsymmU8)
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestQSymmS16)
BOOST_AUTO_TEST_CASE (RefFillEndToEndTest)
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestInt32)
BOOST_AUTO_TEST_CASE (RefGatherFloatTest)
BOOST_AUTO_TEST_CASE (RefGatherUint8Test)
BOOST_AUTO_TEST_CASE (RefGatherInt16Test)
BOOST_AUTO_TEST_CASE (RefGatherMultiDimFloatTest)
BOOST_AUTO_TEST_CASE (RefGatherMultiDimUint8Test)
BOOST_AUTO_TEST_CASE (RefGatherMultiDimInt16Test)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat32)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwUint8)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwInt16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat32)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat16)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcUint8)
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcInt16)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleTest)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetTest)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleInt16Test)
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetInt16Test)
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessRegularNmsTest)
void QuantizeData (uint8_t *quant, const float *dequant, const TensorInfo &info)
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessRegularNmsUint8Test)
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessFastNmsTest)
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessFastNmsUint8Test)
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestBFloat16)
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestQAsymmS8)
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestQAsymmU8)
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestQSymmS16)
BOOST_AUTO_TEST_CASE (RefLogSoftmaxEndToEndTest)
BOOST_AUTO_TEST_CASE (RefPreluEndToEndTestFloat32)
BOOST_AUTO_TEST_CASE (RefPreluEndToEndTestUint8)
BOOST_AUTO_TEST_CASE (RefPreluEndToEndTestQSymm16)
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNhwcEndToEndTest1)
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNchwEndToEndTest1)
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNhwcEndToEndTest2)
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNchwEndToEndTest2)
BOOST_AUTO_TEST_CASE (RefSplitter1dEndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter1dEndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter2dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter2dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter2dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter2dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter3dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter3dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter3dDim2EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter3dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter3dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter3dDim2EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim0EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim1EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim2EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim3EndToEndTest)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim0EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim1EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim2EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefSplitter4dDim3EndToEndUint8Test)
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndFloatNchwTest)
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndUint8NchwTest)
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndInt16NchwTest)
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndFloatNhwcTest)
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndUint8NhwcTest)
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndInt16NhwcTest)
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndFloatNchwTest)
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndUint8NchwTest)
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndInt16NchwTest)
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndFloatNhwcTest)
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndUint8NhwcTest)
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndInt16NhwcTest)
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndFloatNchwTest)
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndUint8NchwTest)
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndInt16NchwTest)
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndFloatNhwcTest)
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndUint8NhwcTest)
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndInt16NhwcTest)
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNhwcEndToEndTest1)
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNchwEndToEndTest1)
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNhwcEndToEndTest2)
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNchwEndToEndTest2)
BOOST_AUTO_TEST_CASE (RefArgMaxSimpleTest)
BOOST_AUTO_TEST_CASE (RefArgMaxSimpleUint8Test)
BOOST_AUTO_TEST_CASE (RefArgMinSimpleTest)
BOOST_AUTO_TEST_CASE (RefArgMinSimpleUint8Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis0Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis0Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis0Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis0Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis1Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis1Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis1Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis1Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis2Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis2Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis2Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis2Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis3Test)
BOOST_AUTO_TEST_CASE (RefArgMaxAxis3Uint8Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis3Test)
BOOST_AUTO_TEST_CASE (RefArgMinAxis3Uint8Test)
BOOST_AUTO_TEST_CASE (RefQLstmEndToEndTest)
BOOST_AUTO_TEST_CASE (RefRankEndToEndTest)
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestFloat16)
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestInt32)
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestQAsymmS8)
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestQSymmS16)
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestQSymmS8)
BOOST_AUTO_TEST_CASE (RefImportNonAlignedPointerTest)
BOOST_AUTO_TEST_CASE (RefExportNonAlignedPointerTest)
BOOST_AUTO_TEST_CASE (RefImportAlignedPointerTest)
BOOST_AUTO_TEST_CASE (RefImportOnlyWorkload)
BOOST_AUTO_TEST_CASE (RefExportOnlyWorkload)
BOOST_AUTO_TEST_CASE (RefImportAndExportWorkload)
BOOST_AUTO_TEST_CASE (RefExportOutputWithSeveralOutputSlotConnectionsTest)
BOOST_AUTO_TEST_CASE (RefStridedSliceInvalidSliceEndToEndTest)
Variables
std::vector< armnn::BackendId > defaultBackends = {armnn::Compute::CpuRef}
Function Documentation
BOOST_AUTO_TEST_CASE() [1/159]
BOOST_AUTO_TEST_CASE (RefAbsEndToEndTestFloat32)
Definition at line 37 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     std::vector<float> expectedOutput =
     {
         1.f, 1.f, 1.f, 1.f, 5.f, 5.f, 5.f, 5.f,
         3.f, 3.f, 3.f, 3.f, 4.f, 4.f, 4.f, 4.f
     };
     ElementwiseUnarySimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                              UnaryOperation::Abs,
                                                              expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [2/159]
BOOST_AUTO_TEST_CASE (RefAbsEndToEndTestUint8)
Definition at line 50 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     // Note the expected output will be implicitly quantized by the below test function
     std::vector<float> expectedOutput =
     {
         1.f, 1.f, 1.f, 1.f, 5.f, 5.f, 5.f, 5.f,
         3.f, 3.f, 3.f, 3.f, 4.f, 4.f, 4.f, 4.f
     };
     ElementwiseUnarySimpleEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                      UnaryOperation::Abs,
                                                                      expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [3/159]
BOOST_AUTO_TEST_CASE (RefAbsEndToEndTestInt16)
Definition at line 64 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     // Note the expected output will be implicitly quantized by the below test function
     std::vector<float> expectedOutput =
     {
         1.f, 1.f, 1.f, 1.f, 5.f, 5.f, 5.f, 5.f,
         3.f, 3.f, 3.f, 3.f, 4.f, 4.f, 4.f, 4.f
     };
     ElementwiseUnarySimpleEndToEnd<armnn::DataType::QSymmS16>(defaultBackends,
                                                                      UnaryOperation::Abs,
                                                                      expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [4/159]
BOOST_AUTO_TEST_CASE (ConstantUsage_Ref_Float32)
Definition at line 79 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     BOOST_TEST(ConstantUsageFloat32Test(defaultBackends));
 }
BOOST_AUTO_TEST_CASE() [5/159]
BOOST_AUTO_TEST_CASE (ConstantUsage_Ref_Uint8)
Definition at line 84 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     BOOST_TEST(ConstantUsageUint8Test(defaultBackends));
 }
BOOST_AUTO_TEST_CASE() [6/159]
BOOST_AUTO_TEST_CASE (Unsigned8)
Definition at line 89 of file RefEndToEndTests.cpp.
References IOutputSlot::Connect(), IRuntime::Create(), INetwork::Create(), defaultBackends, armnn::error, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), armnn::Optimize(), armnn::QAsymmU8, TensorInfo::SetQuantizationOffset(), TensorInfo::SetQuantizationScale(), IOutputSlot::SetTensorInfo(), and armnn::Success.
 {
     using namespace armnn;
     // Create runtime in which test will run
     armnn::IRuntime::CreationOptions options;
     armnn::IRuntimePtr runtime(armnn::IRuntime::Create(options));
     // Builds up the structure of the network.
     armnn::INetworkPtr net(INetwork::Create());
     IConnectableLayer* input = net->AddInputLayer(0, "input");
     IConnectableLayer* softmax = net->AddSoftmaxLayer(SoftmaxDescriptor(), "softmax");
     IConnectableLayer* output  = net->AddOutputLayer(0, "output");
     input->GetOutputSlot(0).Connect(softmax->GetInputSlot(0));
     softmax->GetOutputSlot(0).Connect(output->GetInputSlot(0));
     // Sets the tensors in the network.
     TensorInfo inputTensorInfo(TensorShape({1, 5}), DataType::QAsymmU8);
     inputTensorInfo.SetQuantizationOffset(100);
     inputTensorInfo.SetQuantizationScale(10000.0f);
     input->GetOutputSlot(0).SetTensorInfo(inputTensorInfo);
     TensorInfo outputTensorInfo(TensorShape({1, 5}), DataType::QAsymmU8);
     outputTensorInfo.SetQuantizationOffset(0);
     outputTensorInfo.SetQuantizationScale(1.0f/255.0f);
     softmax->GetOutputSlot(0).SetTensorInfo(outputTensorInfo);
     // optimize the network
     IOptimizedNetworkPtr optNet = Optimize(*net, defaultBackends, runtime->GetDeviceSpec());
     // Loads it into the runtime.
     NetworkId netId;
     auto error = runtime->LoadNetwork(netId, std::move(optNet));
     BOOST_TEST(error == Status::Success);
     // Creates structures for input & output.
     std::vector<uint8_t> inputData
     {
         1, 10, 3, 200, 5 // Some inputs - one of which is sufficiently larger than the others to saturate softmax.
     };
     std::vector<uint8_t> outputData(5);
     armnn::InputTensors inputTensors
     {
         {0, armnn::ConstTensor(runtime->GetInputTensorInfo(netId, 0), inputData.data())}
     };
     armnn::OutputTensors outputTensors
     {
         {0, armnn::Tensor(runtime->GetOutputTensorInfo(netId, 0), outputData.data())}
     };
     // Does the inference.
     runtime->EnqueueWorkload(netId, inputTensors, outputTensors);
     // Checks the results.
     BOOST_TEST(outputData[0] == 0);
     BOOST_TEST(outputData[1] == 0);
     BOOST_TEST(outputData[2] == 0);
     BOOST_TEST(outputData[3] == 255); // softmax has been saturated.
     BOOST_TEST(outputData[4] == 0);
 }
BOOST_AUTO_TEST_CASE() [7/159]
BOOST_AUTO_TEST_CASE (TrivialAdd)
Definition at line 153 of file RefEndToEndTests.cpp.
References IOutputSlot::Connect(), IRuntime::Create(), INetwork::Create(), defaultBackends, armnn::Float32, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), armnn::Optimize(), and IOutputSlot::SetTensorInfo().
 {
     // This test was designed to match "AddTwo" in android nn/runtime/test/TestTrivialModel.cpp.
     using namespace armnn;
     // Create runtime in which test will run
     armnn::IRuntime::CreationOptions options;
     armnn::IRuntimePtr runtime(armnn::IRuntime::Create(options));
     // Builds up the structure of the network.
     armnn::INetworkPtr net(INetwork::Create());
     IConnectableLayer* input1 = net->AddInputLayer(0);
     IConnectableLayer* input2 = net->AddInputLayer(1);
     IConnectableLayer* add    = net->AddAdditionLayer();
     IConnectableLayer* output = net->AddOutputLayer(0);
     input1->GetOutputSlot(0).Connect(add->GetInputSlot(0));
     input2->GetOutputSlot(0).Connect(add->GetInputSlot(1));
     add->GetOutputSlot(0).Connect(output->GetInputSlot(0));
     // Sets the tensors in the network.
     TensorInfo tensorInfo(TensorShape({3, 4}), DataType::Float32);
     input1->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     input2->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     add->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     // optimize the network
     IOptimizedNetworkPtr optNet = Optimize(*net, defaultBackends, runtime->GetDeviceSpec());
     // Loads it into the runtime.
     NetworkId netId;
     runtime->LoadNetwork(netId, std::move(optNet));
     // Creates structures for input & output - matching android nn test.
     std::vector<float> input1Data
     {
         1.f, 2.f, 3.f, 4.f, 5.f, 6.f, 7.f, 8.f, 9.f, 10.f, 11.f, 12.f
     };
     std::vector<float> input2Data
     {
         100.f, 200.f, 300.f, 400.f, 500.f, 600.f, 700.f, 800.f, 900.f, 1000.f, 1100.f, 1200.f
     };
     std::vector<float> outputData(12);
     InputTensors inputTensors
     {
         {0,armnn::ConstTensor(runtime->GetInputTensorInfo(netId, 0), input1Data.data())},
         {1,armnn::ConstTensor(runtime->GetInputTensorInfo(netId, 0), input2Data.data())}
     };
     OutputTensors outputTensors
     {
         {0,armnn::Tensor(runtime->GetOutputTensorInfo(netId, 0), outputData.data())}
     };
     // Does the inference.
     runtime->EnqueueWorkload(netId, inputTensors, outputTensors);
     // Checks the results
     BOOST_TEST(outputData[0] == 101);
     BOOST_TEST(outputData[1] == 202);
     BOOST_TEST(outputData[2] == 303);
     BOOST_TEST(outputData[3] == 404);
     BOOST_TEST(outputData[4] == 505);
     BOOST_TEST(outputData[5] == 606);
     BOOST_TEST(outputData[6] == 707);
     BOOST_TEST(outputData[7] == 808);
     BOOST_TEST(outputData[8] == 909);
     BOOST_TEST(outputData[9] == 1010);
     BOOST_TEST(outputData[10] == 1111);
     BOOST_TEST(outputData[11] == 1212);
 }
BOOST_AUTO_TEST_CASE() [8/159]
BOOST_AUTO_TEST_CASE (MultipleOutputs)
Definition at line 227 of file RefEndToEndTests.cpp.
References armnn::BoundedReLu, IOutputSlot::Connect(), IRuntime::Create(), INetwork::Create(), defaultBackends, armnn::Float32, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), ActivationDescriptor::m_A, ActivationDescriptor::m_B, ActivationDescriptor::m_Function, armnn::Optimize(), and IOutputSlot::SetTensorInfo().
 {
     using namespace armnn;
     // Create runtime in which test will run
     armnn::IRuntime::CreationOptions options;
     armnn::IRuntimePtr  runtime(armnn::IRuntime::Create(options));
     // Builds up the structure of the network.
     INetworkPtr net(INetwork::Create());
     IConnectableLayer* input = net->AddInputLayer(0);
     // ReLu1
     ActivationDescriptor activation1Descriptor;
     activation1Descriptor.m_Function = ActivationFunction::BoundedReLu;
     activation1Descriptor.m_A = 1.f;
     activation1Descriptor.m_B = -1.f;
     IConnectableLayer* activation1 = net->AddActivationLayer(activation1Descriptor);
     // ReLu6
     ActivationDescriptor activation2Descriptor;
     activation2Descriptor.m_Function = ActivationFunction::BoundedReLu;
     activation2Descriptor.m_A = 6.0f;
     IConnectableLayer* activation2 = net->AddActivationLayer(activation2Descriptor);
     // BoundedReLu(min=2, max=5)
     ActivationDescriptor activation3Descriptor;
     activation3Descriptor.m_Function = ActivationFunction::BoundedReLu;
     activation3Descriptor.m_A = 5.0f;
     activation3Descriptor.m_B = 2.0f;
     IConnectableLayer* activation3 = net->AddActivationLayer(activation3Descriptor);
     IConnectableLayer* output1 = net->AddOutputLayer(0);
     IConnectableLayer* output2 = net->AddOutputLayer(1);
     IConnectableLayer* output3 = net->AddOutputLayer(2);
     input->GetOutputSlot(0).Connect(activation1->GetInputSlot(0));
     input->GetOutputSlot(0).Connect(activation2->GetInputSlot(0));
     input->GetOutputSlot(0).Connect(activation3->GetInputSlot(0));
     activation1->GetOutputSlot(0).Connect(output1->GetInputSlot(0));
     activation2->GetOutputSlot(0).Connect(output2->GetInputSlot(0));
     activation3->GetOutputSlot(0).Connect(output3->GetInputSlot(0));
     // Sets the tensors in the network.
     TensorInfo tensorInfo(TensorShape({ 10 }), DataType::Float32);
     input->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     activation1->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     activation2->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     activation3->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     // optimize the network
     IOptimizedNetworkPtr optNet = Optimize(*net, defaultBackends, runtime->GetDeviceSpec());
     // Loads it into the runtime.
     NetworkId netId;
     runtime->LoadNetwork(netId, std::move(optNet));
     // Creates structures for input & output.
     const std::vector<float> inputData{ 3.f, 5.f, 2.f, 3.f, 7.f, 0.f, -2.f, -1.f, 3.f, 3.f };
     std::vector<float> output1Data(inputData.size());
     std::vector<float> output2Data(inputData.size());
     std::vector<float> output3Data(inputData.size());
     InputTensors inputTensors
     {
         {0,armnn::ConstTensor(runtime->GetInputTensorInfo(netId, 0), inputData.data())}
     };
     OutputTensors outputTensors
     {
         {0,armnn::Tensor(runtime->GetOutputTensorInfo(netId, 0), output1Data.data())},
         {1,armnn::Tensor(runtime->GetOutputTensorInfo(netId, 1), output2Data.data())},
         {2,armnn::Tensor(runtime->GetOutputTensorInfo(netId, 2), output3Data.data())}
     };
     // Does the inference.
     runtime->EnqueueWorkload(netId, inputTensors, outputTensors);
     // Checks the results.
     BOOST_TEST(output1Data == std::vector<float>({ 1.f, 1.f, 1.f, 1.f, 1.f, 0.f, -1.f, -1.f, 1.f, 1.f })); // ReLu1
     BOOST_TEST(output2Data == std::vector<float>({ 3.f, 5.f, 2.f, 3.f, 6.f, 0.f, 0.f, 0.f, 3.f, 3.f })); // ReLu6
     BOOST_TEST(output3Data == std::vector<float>({ 3.f, 5.f, 2.f, 3.f, 5.f, 2.f, 2.f, 2.f, 3.f, 3.f })); // [2, 5]
 }
BOOST_AUTO_TEST_CASE() [9/159]
BOOST_AUTO_TEST_CASE (TrivialMin)
Definition at line 313 of file RefEndToEndTests.cpp.
References IOutputSlot::Connect(), IRuntime::Create(), INetwork::Create(), defaultBackends, armnn::Float32, IConnectableLayer::GetInputSlot(), IConnectableLayer::GetOutputSlot(), armnn::Optimize(), and IOutputSlot::SetTensorInfo().
 {
     using namespace armnn;
     // Create runtime in which test will run
     armnn::IRuntime::CreationOptions options;
     armnn::IRuntimePtr runtime(armnn::IRuntime::Create(options));
     // Builds up the structure of the network.
     armnn::INetworkPtr net(INetwork::Create());
     IConnectableLayer* input1 = net->AddInputLayer(0);
     IConnectableLayer* input2 = net->AddInputLayer(1);
     IConnectableLayer* min    = net->AddMinimumLayer();
     IConnectableLayer* output = net->AddOutputLayer(0);
     input1->GetOutputSlot(0).Connect(min->GetInputSlot(0));
     input2->GetOutputSlot(0).Connect(min->GetInputSlot(1));
     min->GetOutputSlot(0).Connect(output->GetInputSlot(0));
     // Sets the tensors in the network.
     TensorInfo tensorInfo(TensorShape({1, 1, 1, 4}), DataType::Float32);
     input1->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     input2->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     min->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     // optimize the network
     IOptimizedNetworkPtr optNet = Optimize(*net, defaultBackends, runtime->GetDeviceSpec());
     // Loads it into the runtime.
     NetworkId netId;
     runtime->LoadNetwork(netId, std::move(optNet));
     // Creates structures for input & output - matching android nn test.
     std::vector<float> input1Data
         {
             1.0f, 2.0f, 3.0f, 4.0f
         };
     std::vector<float> input2Data
         {
             2.0f, 1.0f, 5.0f, 2.0f
         };
     std::vector<float> outputData(4);
     InputTensors inputTensors
         {
             {0,armnn::ConstTensor(runtime->GetInputTensorInfo(netId, 0), input1Data.data())},
             {1,armnn::ConstTensor(runtime->GetInputTensorInfo(netId, 0), input2Data.data())}
         };
     OutputTensors outputTensors
         {
             {0,armnn::Tensor(runtime->GetOutputTensorInfo(netId, 0), outputData.data())}
         };
     // Does the inference.
     runtime->EnqueueWorkload(netId, inputTensors, outputTensors);
     // Checks the results
     BOOST_TEST(outputData[0] == 1);
     BOOST_TEST(outputData[1] == 1);
     BOOST_TEST(outputData[2] == 3);
     BOOST_TEST(outputData[3] == 2);
 }
BOOST_AUTO_TEST_CASE() [10/159]
BOOST_AUTO_TEST_CASE (RefEqualSimpleEndToEndTest)
Definition at line 377 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Equal.
 {
     const std::vector<uint8_t> expectedOutput({ 1, 1, 1, 1,  0, 0, 0, 0,
                                                 0, 0, 0, 0,  1, 1, 1, 1 });
     ComparisonSimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                        ComparisonOperation::Equal,
                                                        expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [11/159]
BOOST_AUTO_TEST_CASE (RefGreaterSimpleEndToEndTest)
Definition at line 387 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 0, 0, 0,  1, 1, 1, 1,
                                                 0, 0, 0, 0,  0, 0, 0, 0 });
     ComparisonSimpleEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                        ComparisonOperation::Greater,
                                                        expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [12/159]
BOOST_AUTO_TEST_CASE (RefEqualSimpleEndToEndUint8Test)
Definition at line 397 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Equal.
 {
     const std::vector<uint8_t> expectedOutput({ 1, 1, 1, 1,  0, 0, 0, 0,
                                                 0, 0, 0, 0,  1, 1, 1, 1 });
     ComparisonSimpleEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                ComparisonOperation::Equal,
                                                                expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [13/159]
BOOST_AUTO_TEST_CASE (RefGreaterSimpleEndToEndUint8Test)
Definition at line 407 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 0, 0, 0,  1, 1, 1, 1,
                                                 0, 0, 0, 0,  0, 0, 0, 0 });
     ComparisonSimpleEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                ComparisonOperation::Greater,
                                                                expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [14/159]
BOOST_AUTO_TEST_CASE (RefEqualBroadcastEndToEndTest)
Definition at line 417 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Equal.
 {
     const std::vector<uint8_t> expectedOutput({ 1, 0, 1, 1, 0, 0,
                                                 0, 0, 0, 0, 0, 0 });
     ComparisonBroadcastEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                           ComparisonOperation::Equal,
                                                           expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [15/159]
BOOST_AUTO_TEST_CASE (RefGreaterBroadcastEndToEndTest)
Definition at line 427 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 1, 0, 0, 0, 1,
                                                 1, 1, 1, 1, 1, 1 });
     ComparisonBroadcastEndToEnd<armnn::DataType::Float32>(defaultBackends,
                                                           ComparisonOperation::Greater,
                                                           expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [16/159]
BOOST_AUTO_TEST_CASE (RefEqualBroadcastEndToEndUint8Test)
Definition at line 437 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Equal.
 {
     const std::vector<uint8_t > expectedOutput({ 1, 0, 1, 1, 0, 0,
                                                  0, 0, 0, 0, 0, 0 });
     ComparisonBroadcastEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                   ComparisonOperation::Equal,
                                                                   expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [17/159]
BOOST_AUTO_TEST_CASE (RefGreaterBroadcastEndToEndUint8Test)
Definition at line 447 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::Greater.
 {
     const std::vector<uint8_t> expectedOutput({ 0, 1, 0, 0, 0, 1,
                                                 1, 1, 1, 1, 1, 1 });
     ComparisonBroadcastEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends,
                                                                   ComparisonOperation::Greater,
                                                                   expectedOutput);
 }
BOOST_AUTO_TEST_CASE() [18/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndFloat32NHWCTest)
Definition at line 457 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     BatchToSpaceNdEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [19/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndUint8NHWCTest)
Definition at line 462 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     BatchToSpaceNdEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [20/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndQSymm16NHWCTest)
Definition at line 467 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     BatchToSpaceNdEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [21/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndFloat32NCHWTest)
Definition at line 472 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     BatchToSpaceNdEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [22/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndUint8NCHWTest)
Definition at line 477 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     BatchToSpaceNdEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [23/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndQSymm16NCHWTest)
Definition at line 482 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     BatchToSpaceNdEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [24/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexFloat32NHWCTest)
Definition at line 487 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     BatchToSpaceNdComplexEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [25/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexUint8NHWCTest)
Definition at line 492 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     BatchToSpaceNdComplexEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [26/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexQSymm16NHWCTest)
Definition at line 497 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     BatchToSpaceNdComplexEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [27/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexFloat32NCHWTest)
Definition at line 502 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     BatchToSpaceNdComplexEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [28/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexUint8NCHWTest)
Definition at line 507 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     BatchToSpaceNdComplexEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [29/159]
BOOST_AUTO_TEST_CASE (RefBatchToSpaceNdEndToEndComplexQSymm16NCHWTest)
Definition at line 512 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     BatchToSpaceNdComplexEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [30/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim0Test)
Definition at line 517 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [31/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim0Uint8Test)
Definition at line 522 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [32/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim1Test)
Definition at line 527 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [33/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim1Uint8Test)
Definition at line 532 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [34/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim2Test)
Definition at line 537 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [35/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim2Uint8Test)
Definition at line 542 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [36/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim3Test)
Definition at line 547 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [37/159]
BOOST_AUTO_TEST_CASE (RefConcatEndToEndDim3Uint8Test)
Definition at line 552 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ConcatDim3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [38/159]
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestFloat32)
Definition at line 557 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [39/159]
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestFloat16)
Definition at line 562 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [40/159]
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestBFloat16)
Definition at line 567 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::BFloat16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [41/159]
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestQAsymmS8)
Definition at line 572 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::QAsymmS8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [42/159]
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestQAsymmU8)
Definition at line 577 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [43/159]
BOOST_AUTO_TEST_CASE (RefEluEndToEndTestQSymmS16)
Definition at line 582 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     EluEndToEndTest<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [44/159]
BOOST_AUTO_TEST_CASE (RefFillEndToEndTest)
Definition at line 587 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [45/159]
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestFloat16)
Definition at line 592 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [46/159]
BOOST_AUTO_TEST_CASE (RefFillEndToEndTestInt32)
Definition at line 597 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     FillEndToEnd<armnn::DataType::Signed32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [47/159]
BOOST_AUTO_TEST_CASE (RefGatherFloatTest)
Definition at line 602 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     GatherEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [48/159]
BOOST_AUTO_TEST_CASE (RefGatherUint8Test)
Definition at line 607 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     GatherEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [49/159]
BOOST_AUTO_TEST_CASE (RefGatherInt16Test)
Definition at line 612 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     GatherEndToEnd<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [50/159]
BOOST_AUTO_TEST_CASE (RefGatherMultiDimFloatTest)
Definition at line 617 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     GatherMultiDimEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [51/159]
BOOST_AUTO_TEST_CASE (RefGatherMultiDimUint8Test)
Definition at line 622 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     GatherMultiDimEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [52/159]
BOOST_AUTO_TEST_CASE (RefGatherMultiDimInt16Test)
Definition at line 627 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     GatherMultiDimEndToEnd<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [53/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat32)
Definition at line 633 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [54/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwFloat16)
Definition at line 638 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [55/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwUint8)
Definition at line 643 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [56/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNchwInt16)
Definition at line 648 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [57/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat32)
Definition at line 653 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [58/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcFloat16)
Definition at line 658 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::Float16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [59/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcUint8)
Definition at line 663 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [60/159]
BOOST_AUTO_TEST_CASE (DephtToSpaceEndToEndNhwcInt16)
Definition at line 668 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     DepthToSpaceEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [61/159]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleTest)
Definition at line 674 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [62/159]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetTest)
Definition at line 679 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndOffset<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [63/159]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndSimpleInt16Test)
Definition at line 684 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndSimple<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [64/159]
BOOST_AUTO_TEST_CASE (DequantizeEndToEndOffsetInt16Test)
Definition at line 689 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     DequantizeEndToEndOffset<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [65/159]
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessRegularNmsTest)
Definition at line 694 of file RefEndToEndTests.cpp.
References anchors(), boxEncodings(), defaultBackends, and scores().
 {
     std::vector<float> boxEncodings({
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, -1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f
     });
     std::vector<float> scores({
         0.0f, 0.9f, 0.8f,
         0.0f, 0.75f, 0.72f,
         0.0f, 0.6f, 0.5f,
         0.0f, 0.93f, 0.95f,
         0.0f, 0.5f, 0.4f,
         0.0f, 0.3f, 0.2f
     });
     std::vector<float> anchors({
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 100.5f, 1.0f, 1.0f
     });
     DetectionPostProcessRegularNmsEndToEnd<armnn::DataType::Float32>(defaultBackends, boxEncodings, scores, anchors);
 }
BOOST_AUTO_TEST_CASE() [66/159]
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessRegularNmsUint8Test)
Definition at line 731 of file RefEndToEndTests.cpp.
References anchors(), anchorsInfo, boxEncodings(), defaultBackends, armnn::Float32, qAnchors(), qBoxEncodings(), qScores(), QuantizeData(), scores(), scoresInfo, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo boxEncodingsInfo({ 1, 6, 4 }, armnn::DataType::Float32);
     armnn::TensorInfo scoresInfo({ 1, 6, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo anchorsInfo({ 6, 4 }, armnn::DataType::Float32);
     boxEncodingsInfo.SetQuantizationScale(1.0f);
     boxEncodingsInfo.SetQuantizationOffset(1);
     scoresInfo.SetQuantizationScale(0.01f);
     scoresInfo.SetQuantizationOffset(0);
     anchorsInfo.SetQuantizationScale(0.5f);
     anchorsInfo.SetQuantizationOffset(0);
     std::vector<float> boxEncodings({
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, -1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f
     });
     std::vector<float> scores({
         0.0f, 0.9f, 0.8f,
         0.0f, 0.75f, 0.72f,
         0.0f, 0.6f, 0.5f,
         0.0f, 0.93f, 0.95f,
         0.0f, 0.5f, 0.4f,
         0.0f, 0.3f, 0.2f
     });
     std::vector<float> anchors({
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 100.5f, 1.0f, 1.0f
     });
     std::vector<uint8_t> qBoxEncodings(boxEncodings.size(), 0);
     std::vector<uint8_t> qScores(scores.size(), 0);
     std::vector<uint8_t> qAnchors(anchors.size(), 0);
     QuantizeData(qBoxEncodings.data(), boxEncodings.data(), boxEncodingsInfo);
     QuantizeData(qScores.data(), scores.data(), scoresInfo);
     QuantizeData(qAnchors.data(), anchors.data(), anchorsInfo);
     DetectionPostProcessRegularNmsEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, qBoxEncodings,
                                                                              qScores, qAnchors,
                                                                              1.0f, 1, 0.01f, 0, 0.5f, 0);
 }
BOOST_AUTO_TEST_CASE() [67/159]
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessFastNmsTest)
Definition at line 780 of file RefEndToEndTests.cpp.
References anchors(), boxEncodings(), defaultBackends, and scores().
 {
     std::vector<float> boxEncodings({
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, -1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f
     });
     std::vector<float> scores({
         0.0f, 0.9f, 0.8f,
         0.0f, 0.75f, 0.72f,
         0.0f, 0.6f, 0.5f,
         0.0f, 0.93f, 0.95f,
         0.0f, 0.5f, 0.4f,
         0.0f, 0.3f, 0.2f
     });
     std::vector<float> anchors({
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 100.5f, 1.0f, 1.0f
     });
     DetectionPostProcessFastNmsEndToEnd<armnn::DataType::Float32>(defaultBackends, boxEncodings, scores, anchors);
 }
BOOST_AUTO_TEST_CASE() [68/159]
BOOST_AUTO_TEST_CASE (RefDetectionPostProcessFastNmsUint8Test)
Definition at line 809 of file RefEndToEndTests.cpp.
References anchors(), anchorsInfo, boxEncodings(), defaultBackends, armnn::Float32, qAnchors(), qBoxEncodings(), qScores(), QuantizeData(), scores(), scoresInfo, TensorInfo::SetQuantizationOffset(), and TensorInfo::SetQuantizationScale().
 {
     armnn::TensorInfo boxEncodingsInfo({ 1, 6, 4 }, armnn::DataType::Float32);
     armnn::TensorInfo scoresInfo({ 1, 6, 3 }, armnn::DataType::Float32);
     armnn::TensorInfo anchorsInfo({ 6, 4 }, armnn::DataType::Float32);
     boxEncodingsInfo.SetQuantizationScale(1.0f);
     boxEncodingsInfo.SetQuantizationOffset(1);
     scoresInfo.SetQuantizationScale(0.01f);
     scoresInfo.SetQuantizationOffset(0);
     anchorsInfo.SetQuantizationScale(0.5f);
     anchorsInfo.SetQuantizationOffset(0);
     std::vector<float> boxEncodings({
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, -1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f,
         0.0f, 1.0f, 0.0f, 0.0f,
         0.0f, 0.0f, 0.0f, 0.0f
     });
     std::vector<float> scores({
         0.0f, 0.9f, 0.8f,
         0.0f, 0.75f, 0.72f,
         0.0f, 0.6f, 0.5f,
         0.0f, 0.93f, 0.95f,
         0.0f, 0.5f, 0.4f,
         0.0f, 0.3f, 0.2f
     });
     std::vector<float> anchors({
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 0.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 10.5f, 1.0f, 1.0f,
         0.5f, 100.5f, 1.0f, 1.0f
     });
     std::vector<uint8_t> qBoxEncodings(boxEncodings.size(), 0);
     std::vector<uint8_t> qScores(scores.size(), 0);
     std::vector<uint8_t> qAnchors(anchors.size(), 0);
     QuantizeData(qBoxEncodings.data(), boxEncodings.data(), boxEncodingsInfo);
     QuantizeData(qScores.data(), scores.data(), scoresInfo);
     QuantizeData(qAnchors.data(), anchors.data(), anchorsInfo);
     DetectionPostProcessFastNmsEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, qBoxEncodings,
                                                                           qScores, qAnchors,
                                                                           1.0f, 1, 0.01f, 0, 0.5f, 0);
 }
BOOST_AUTO_TEST_CASE() [69/159]
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestFloat32)
Definition at line 859 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [70/159]
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestFloat16)
Definition at line 864 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [71/159]
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestBFloat16)
Definition at line 869 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
 HardSwishEndToEndTest<armnn::DataType::BFloat16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [72/159]
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestQAsymmS8)
Definition at line 874 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QAsymmS8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [73/159]
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestQAsymmU8)
Definition at line 879 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [74/159]
BOOST_AUTO_TEST_CASE (RefHardSwishEndToEndTestQSymmS16)
Definition at line 884 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     HardSwishEndToEndTest<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [75/159]
BOOST_AUTO_TEST_CASE (RefLogSoftmaxEndToEndTest)
Definition at line 890 of file RefEndToEndTests.cpp.
References defaultBackends, and LogSoftmaxEndToEndTest().
 {
     LogSoftmaxEndToEndTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [76/159]
BOOST_AUTO_TEST_CASE (RefPreluEndToEndTestFloat32)
Definition at line 895 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndNegativeTest<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [77/159]
BOOST_AUTO_TEST_CASE (RefPreluEndToEndTestUint8)
Definition at line 900 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndPositiveTest<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [78/159]
BOOST_AUTO_TEST_CASE (RefPreluEndToEndTestQSymm16)
Definition at line 905 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     PreluEndToEndPositiveTest<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [79/159]
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNhwcEndToEndTest1)
Definition at line 910 of file RefEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNhwcEndToEndTest1().
 {
     SpaceToDepthNhwcEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [80/159]
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNchwEndToEndTest1)
Definition at line 915 of file RefEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNchwEndToEndTest1().
 {
     SpaceToDepthNchwEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [81/159]
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNhwcEndToEndTest2)
Definition at line 921 of file RefEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNhwcEndToEndTest2().
 {
     SpaceToDepthNhwcEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [82/159]
BOOST_AUTO_TEST_CASE (RefSpaceToDepthNchwEndToEndTest2)
Definition at line 926 of file RefEndToEndTests.cpp.
References defaultBackends, and SpaceToDepthNchwEndToEndTest2().
 {
     SpaceToDepthNchwEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [83/159]
BOOST_AUTO_TEST_CASE (RefSplitter1dEndToEndTest)
Definition at line 931 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter1dEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [84/159]
BOOST_AUTO_TEST_CASE (RefSplitter1dEndToEndUint8Test)
Definition at line 936 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter1dEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [85/159]
BOOST_AUTO_TEST_CASE (RefSplitter2dDim0EndToEndTest)
Definition at line 941 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [86/159]
BOOST_AUTO_TEST_CASE (RefSplitter2dDim1EndToEndTest)
Definition at line 946 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [87/159]
BOOST_AUTO_TEST_CASE (RefSplitter2dDim0EndToEndUint8Test)
Definition at line 951 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [88/159]
BOOST_AUTO_TEST_CASE (RefSplitter2dDim1EndToEndUint8Test)
Definition at line 956 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter2dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [89/159]
BOOST_AUTO_TEST_CASE (RefSplitter3dDim0EndToEndTest)
Definition at line 961 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [90/159]
BOOST_AUTO_TEST_CASE (RefSplitter3dDim1EndToEndTest)
Definition at line 966 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [91/159]
BOOST_AUTO_TEST_CASE (RefSplitter3dDim2EndToEndTest)
Definition at line 971 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [92/159]
BOOST_AUTO_TEST_CASE (RefSplitter3dDim0EndToEndUint8Test)
Definition at line 976 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [93/159]
BOOST_AUTO_TEST_CASE (RefSplitter3dDim1EndToEndUint8Test)
Definition at line 981 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [94/159]
BOOST_AUTO_TEST_CASE (RefSplitter3dDim2EndToEndUint8Test)
Definition at line 986 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter3dDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [95/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim0EndToEndTest)
Definition at line 991 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [96/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim1EndToEndTest)
Definition at line 996 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [97/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim2EndToEndTest)
Definition at line 1001 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [98/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim3EndToEndTest)
Definition at line 1006 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [99/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim0EndToEndUint8Test)
Definition at line 1011 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [100/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim1EndToEndUint8Test)
Definition at line 1016 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [101/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim2EndToEndUint8Test)
Definition at line 1021 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [102/159]
BOOST_AUTO_TEST_CASE (RefSplitter4dDim3EndToEndUint8Test)
Definition at line 1026 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     Splitter4dDim3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [103/159]
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndFloatNchwTest)
Definition at line 1032 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::Float32, armnn::DataType::Float32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [104/159]
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndUint8NchwTest)
Definition at line 1038 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [105/159]
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndInt16NchwTest)
Definition at line 1044 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [106/159]
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndFloatNhwcTest)
Definition at line 1050 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::Float32, armnn::DataType::Float32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [107/159]
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndUint8NhwcTest)
Definition at line 1056 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [108/159]
BOOST_AUTO_TEST_CASE (RefTransposeConvolution2dEndToEndInt16NhwcTest)
Definition at line 1062 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     TransposeConvolution2dEndToEnd<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
         defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [109/159]
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndFloatNchwTest)
Definition at line 1069 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     ResizeBilinearEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [110/159]
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndUint8NchwTest)
Definition at line 1074 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     ResizeBilinearEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [111/159]
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndInt16NchwTest)
Definition at line 1079 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     ResizeBilinearEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [112/159]
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndFloatNhwcTest)
Definition at line 1084 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     ResizeBilinearEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [113/159]
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndUint8NhwcTest)
Definition at line 1089 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     ResizeBilinearEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [114/159]
BOOST_AUTO_TEST_CASE (RefResizeBilinearEndToEndInt16NhwcTest)
Definition at line 1094 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     ResizeBilinearEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [115/159]
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndFloatNchwTest)
Definition at line 1100 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     ResizeNearestNeighborEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [116/159]
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndUint8NchwTest)
Definition at line 1105 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     ResizeNearestNeighborEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [117/159]
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndInt16NchwTest)
Definition at line 1110 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NCHW.
 {
     ResizeNearestNeighborEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NCHW);
 }
BOOST_AUTO_TEST_CASE() [118/159]
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndFloatNhwcTest)
Definition at line 1115 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     ResizeNearestNeighborEndToEnd<armnn::DataType::Float32>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [119/159]
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndUint8NhwcTest)
Definition at line 1120 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     ResizeNearestNeighborEndToEnd<armnn::DataType::QAsymmU8>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [120/159]
BOOST_AUTO_TEST_CASE (RefResizeNearestNeighborEndToEndInt16NhwcTest)
Definition at line 1125 of file RefEndToEndTests.cpp.
References defaultBackends, and armnn::NHWC.
 {
     ResizeNearestNeighborEndToEnd<armnn::DataType::QSymmS16>(defaultBackends, armnn::DataLayout::NHWC);
 }
BOOST_AUTO_TEST_CASE() [121/159]
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNhwcEndToEndTest1)
Definition at line 1131 of file RefEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNhwcEndToEndTest1().
 {
     InstanceNormalizationNhwcEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [122/159]
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNchwEndToEndTest1)
Definition at line 1136 of file RefEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNchwEndToEndTest1().
 {
     InstanceNormalizationNchwEndToEndTest1(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [123/159]
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNhwcEndToEndTest2)
Definition at line 1141 of file RefEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNhwcEndToEndTest2().
 {
     InstanceNormalizationNhwcEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [124/159]
BOOST_AUTO_TEST_CASE (RefInstanceNormalizationNchwEndToEndTest2)
Definition at line 1146 of file RefEndToEndTests.cpp.
References defaultBackends, and InstanceNormalizationNchwEndToEndTest2().
 {
     InstanceNormalizationNchwEndToEndTest2(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [125/159]
BOOST_AUTO_TEST_CASE (RefArgMaxSimpleTest)
Definition at line 1152 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxEndToEndSimple<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [126/159]
BOOST_AUTO_TEST_CASE (RefArgMaxSimpleUint8Test)
Definition at line 1157 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [127/159]
BOOST_AUTO_TEST_CASE (RefArgMinSimpleTest)
Definition at line 1162 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinEndToEndSimple<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [128/159]
BOOST_AUTO_TEST_CASE (RefArgMinSimpleUint8Test)
Definition at line 1167 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinEndToEndSimple<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [129/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis0Test)
Definition at line 1172 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [130/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis0Uint8Test)
Definition at line 1177 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [131/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis0Test)
Definition at line 1182 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis0EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [132/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis0Uint8Test)
Definition at line 1187 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis0EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [133/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis1Test)
Definition at line 1193 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [134/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis1Uint8Test)
Definition at line 1198 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [135/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis1Test)
Definition at line 1203 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis1EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [136/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis1Uint8Test)
Definition at line 1208 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis1EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [137/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis2Test)
Definition at line 1214 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [138/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis2Uint8Test)
Definition at line 1219 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [139/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis2Test)
Definition at line 1224 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis2EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [140/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis2Uint8Test)
Definition at line 1229 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis2EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [141/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis3Test)
Definition at line 1235 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [142/159]
BOOST_AUTO_TEST_CASE (RefArgMaxAxis3Uint8Test)
Definition at line 1240 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMaxAxis3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [143/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis3Test)
Definition at line 1245 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis3EndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [144/159]
BOOST_AUTO_TEST_CASE (RefArgMinAxis3Uint8Test)
Definition at line 1250 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ArgMinAxis3EndToEnd<armnn::DataType::QAsymmU8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [145/159]
BOOST_AUTO_TEST_CASE (RefQLstmEndToEndTest)
Definition at line 1256 of file RefEndToEndTests.cpp.
References defaultBackends, and QLstmEndToEnd().
 {
     QLstmEndToEnd(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [146/159]
BOOST_AUTO_TEST_CASE (RefRankEndToEndTest)
Definition at line 1261 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     RankEndToEnd<armnn::DataType::Float32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [147/159]
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestFloat16)
Definition at line 1266 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     RankEndToEnd<armnn::DataType::Float16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [148/159]
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestInt32)
Definition at line 1271 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     RankEndToEnd<armnn::DataType::Signed32>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [149/159]
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestQAsymmS8)
Definition at line 1276 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     RankEndToEnd<armnn::DataType::QAsymmS8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [150/159]
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestQSymmS16)
Definition at line 1281 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     RankEndToEnd<armnn::DataType::QSymmS16>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [151/159]
BOOST_AUTO_TEST_CASE (RefRankEndToEndTestQSymmS8)
Definition at line 1286 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     RankEndToEnd<armnn::DataType::QSymmS8>(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [152/159]
BOOST_AUTO_TEST_CASE (RefImportNonAlignedPointerTest)
Definition at line 1293 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ImportNonAlignedInputPointerTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [153/159]
BOOST_AUTO_TEST_CASE (RefExportNonAlignedPointerTest)
Definition at line 1298 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ExportNonAlignedOutputPointerTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [154/159]
BOOST_AUTO_TEST_CASE (RefImportAlignedPointerTest)
Definition at line 1303 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ImportAlignedPointerTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [155/159]
BOOST_AUTO_TEST_CASE (RefImportOnlyWorkload)
Definition at line 1308 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ImportOnlyWorkload(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [156/159]
BOOST_AUTO_TEST_CASE (RefExportOnlyWorkload)
Definition at line 1313 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ExportOnlyWorkload(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [157/159]
BOOST_AUTO_TEST_CASE (RefImportAndExportWorkload)
Definition at line 1318 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ImportAndExportWorkload(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [158/159]
BOOST_AUTO_TEST_CASE (RefExportOutputWithSeveralOutputSlotConnectionsTest)
Definition at line 1323 of file RefEndToEndTests.cpp.
References defaultBackends.
 {
     ExportOutputWithSeveralOutputSlotConnectionsTest(defaultBackends);
 }
BOOST_AUTO_TEST_CASE() [159/159]
BOOST_AUTO_TEST_CASE (RefStridedSliceInvalidSliceEndToEndTest)
Definition at line 1328 of file RefEndToEndTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), and defaultBackends.
 {
     StridedSliceInvalidSliceEndToEndTest(defaultBackends);
 }
QuantizeData()
void QuantizeData (uint8_t * quant, const float * dequant, const TensorInfo & info) inline
Definition at line 723 of file RefEndToEndTests.cpp.
References TensorInfo::GetNumElements(), TensorInfo::GetQuantizationOffset(), and TensorInfo::GetQuantizationScale().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     for (size_t i = 0; i < info.GetNumElements(); i++)
     {
         quant[i] = armnn::Quantize<uint8_t>(dequant[i], info.GetQuantizationScale(), info.GetQuantizationOffset());
     }
 }
Variable Documentation
defaultBackends
std::vector<armnn::BackendId> defaultBackends = {armnn::Compute::CpuRef}
Definition at line 34 of file RefEndToEndTests.cpp.
Referenced by BOOST_AUTO_TEST_CASE().