ArmNN: src/armnnSerializer/test/SerializerTestUtils.cpp File Reference
SerializerTestUtils.cpp File Reference
#include "SerializerTestUtils.hpp"
#include "../Serializer.hpp"
Functions
void CompareConstTensor (const armnn::ConstTensor &tensor1, const armnn::ConstTensor &tensor2)
armnn::INetworkPtr DeserializeNetwork (const std::string &serializerString)
std::string SerializeNetwork (const armnn::INetwork &network)
Function Documentation
CompareConstTensor()
void CompareConstTensor (const armnn::ConstTensor & tensor1, const armnn::ConstTensor & tensor2)
Definition at line 115 of file SerializerTestUtils.cpp.
References armnn::Boolean, armnn::Float32, BaseTensor< MemoryType >::GetDataType(), armnn::GetDataTypeName(), BaseTensor< MemoryType >::GetMemoryArea(), BaseTensor< MemoryType >::GetNumElements(), BaseTensor< MemoryType >::GetShape(), armnn::QAsymmU8, armnn::QSymmS8, and armnn::Signed32.
Referenced by BOOST_AUTO_TEST_CASE(), and LayerVerifierBaseWithDescriptorAndConstants< Descriptor >::ExecuteStrategy().
 {
     BOOST_TEST(tensor1.GetShape() == tensor2.GetShape());
     BOOST_TEST(GetDataTypeName(tensor1.GetDataType()) == GetDataTypeName(tensor2.GetDataType()));
     switch (tensor1.GetDataType())
     {
         case armnn::DataType::Float32:
             CompareConstTensorData<const float*>(
                 tensor1.GetMemoryArea(), tensor2.GetMemoryArea(), tensor1.GetNumElements());
             break;
         case armnn::DataType::QAsymmU8:
         case armnn::DataType::Boolean:
             CompareConstTensorData<const uint8_t*>(
                 tensor1.GetMemoryArea(), tensor2.GetMemoryArea(), tensor1.GetNumElements());
             break;
         case armnn::DataType::QSymmS8:
             CompareConstTensorData<const int8_t*>(
                 tensor1.GetMemoryArea(), tensor2.GetMemoryArea(), tensor1.GetNumElements());
             break;
         case armnn::DataType::Signed32:
             CompareConstTensorData<const int32_t*>(
                 tensor1.GetMemoryArea(), tensor2.GetMemoryArea(), tensor1.GetNumElements());
             break;
         default:
             // Note that Float16 is not yet implemented
             BOOST_TEST_MESSAGE("Unexpected datatype");
             BOOST_TEST(false);
     }
 }
DeserializeNetwork()
armnn::INetworkPtr DeserializeNetwork (const std::string & serializerString)
Definition at line 146 of file SerializerTestUtils.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     std::vector<std::uint8_t> const serializerVector{serializerString.begin(), serializerString.end()};
     return IDeserializer::Create()->CreateNetworkFromBinary(serializerVector);
 }
SerializeNetwork()
std::string SerializeNetwork (const armnn::INetwork & network)
Definition at line 152 of file SerializerTestUtils.cpp.
References ISerializer::Create().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     armnnSerializer::ISerializerPtr serializer = armnnSerializer::ISerializer::Create();
     serializer->Serialize(network);
     std::stringstream stream;
     serializer->SaveSerializedToStream(stream);
     std::string serializerString{stream.str()};
     return serializerString;
 }