ArmNN: src/backends/backendsCommon/test/layerTests/SpaceToDepthTestImpl.hpp File Reference
SpaceToDepthTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <Half.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< uint8_t, 4 > SpaceToDepthNchwAsymmQ8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > SpaceToDepthNhwcAsymmQ8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToDepthNchwFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > SpaceToDepthNhwcFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToDepthNhwcFloat32Test1 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToDepthNchwFloat32Test1 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToDepthNhwcFloat32Test2 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > SpaceToDepthNchwFloat32Test2 (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToDepthNhwcQSymm16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > SpaceToDepthNchwQSymm16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
SpaceToDepthNchwAsymmQ8Test()
LayerTestResult<uint8_t, 4> SpaceToDepthNchwAsymmQ8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 173 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToDepthNchwFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 196 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwFloat32Test1()
LayerTestResult<float, 4> SpaceToDepthNchwFloat32Test1 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 219 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwFloat32Test2()
LayerTestResult<float, 4> SpaceToDepthNchwFloat32Test2 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 242 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNchwQSymm16Test()
LayerTestResult<int16_t, 4> SpaceToDepthNchwQSymm16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 265 of file SpaceToDepthTestImpl.cpp.
References armnn::NCHW.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         armnn::DataLayout::NCHW);
 }
SpaceToDepthNhwcAsymmQ8Test()
LayerTestResult<uint8_t, 4> SpaceToDepthNhwcAsymmQ8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 162 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory);
 }
SpaceToDepthNhwcFloat16Test()
LayerTestResult<armnn::Half, 4> SpaceToDepthNhwcFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 185 of file SpaceToDepthTestImpl.cpp.
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory);
 }
SpaceToDepthNhwcFloat32Test1()
LayerTestResult<float, 4> SpaceToDepthNhwcFloat32Test1 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 208 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest1<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory);
 }
SpaceToDepthNhwcFloat32Test2()
LayerTestResult<float, 4> SpaceToDepthNhwcFloat32Test2 (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 231 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory);
 }
SpaceToDepthNhwcQSymm16Test()
LayerTestResult<int16_t, 4> SpaceToDepthNhwcQSymm16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 254 of file SpaceToDepthTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return SpaceToDepthSimpleTest2<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory);
 }