ArmNN: src/backends/backendsCommon/test/layerTests/StackTestImpl.cpp File Reference
StackTestImpl.cpp File Reference
#include "StackTestImpl.hpp"
#include "LayerTestResult.hpp"
#include <ResolveType.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > StackAxis0TestImpl (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > StackOutput4DAxis1TestImpl (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > StackOutput4DAxis2TestImpl (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 4 > StackOutput4DAxis3TestImpl (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 3 > StackOutput3DInputs3TestImpl (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 5 > StackOutput5DTestImpl (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackAxis0Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackOutput4DAxis1Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackOutput4DAxis2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackOutput4DAxis3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StackOutput3DInputs3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > StackOutput5DFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > StackFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
StackAxis0Float32Test()
LayerTestResult<float, 4> StackAxis0Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 517 of file StackTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return StackAxis0TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackAxis0TestImpl()
LayerTestResult<T, 4> StackAxis0TestImpl (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 85 of file StackTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo ({ 3, 2, 3 }, ArmnnType);
     armnn::TensorInfo outputTensorInfo({ 2, 3, 2, 3 }, ArmnnType);
     std::vector<std::vector<T>> inputData;
     inputData.push_back(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18
     });
     inputData.push_back(
     {
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36
     });
     std::vector<T> outputExpectedData =
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36
     };
     return StackTestHelper<ArmnnType, T, 4>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         0U,
         inputData,
         outputExpectedData
     );
 }
StackFloat16Test()
LayerTestResult<armnn::Half, 4> StackFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 565 of file StackTestImpl.cpp.
References armnn::Float16.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     using namespace half_float::literal;
     armnn::TensorInfo inputTensorInfo ({ 3, 2, 3 }, armnn::DataType::Float16);
     armnn::TensorInfo outputTensorInfo({ 3, 2, 2, 3 }, armnn::DataType::Float16);
     std::vector<std::vector<armnn::Half>> inputData;
     inputData.push_back(
     {
         1.0_h,  2.0_h,  3.0_h,
         4.0_h,  5.0_h,  6.0_h,
         7.0_h,  8.0_h,  9.0_h,
         10.0_h, 11.0_h, 12.0_h,
         13.0_h, 14.0_h, 15.0_h,
         16.0_h, 17.0_h, 18.0_h
     });
     inputData.push_back(
     {
         19.0_h, 20.0_h, 21.0_h,
         22.0_h, 23.0_h, 24.0_h,
         25.0_h, 26.0_h, 27.0_h,
         28.0_h, 29.0_h, 30.0_h,
         31.0_h, 32.0_h, 33.0_h,
         34.0_h, 35.0_h, 36.0_h
     });
     std::vector<armnn::Half> outputExpectedData =
     {
         1.0_h,  2.0_h,  3.0_h,
         19.0_h, 20.0_h, 21.0_h,
         4.0_h,  5.0_h,  6.0_h,
         22.0_h, 23.0_h, 24.0_h,
         7.0_h,  8.0_h,  9.0_h,
         25.0_h, 26.0_h, 27.0_h,
         10.0_h, 11.0_h, 12.0_h,
         28.0_h, 29.0_h, 30.0_h,
         13.0_h, 14.0_h, 15.0_h,
         31.0_h, 32.0_h, 33.0_h,
         16.0_h, 17.0_h, 18.0_h,
         34.0_h, 35.0_h, 36.0_h
     };
     return StackTestHelper<armnn::DataType::Float16, armnn::Half, 4>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         2U,
         inputData,
         outputExpectedData
     );
 }
StackOutput3DInputs3Float32Test()
LayerTestResult<float, 3> StackOutput3DInputs3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 549 of file StackTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return StackOutput3DInputs3TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput3DInputs3TestImpl()
LayerTestResult<T, 3> StackOutput3DInputs3TestImpl (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 368 of file StackTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo ({ 3, 3 }, ArmnnType);
     armnn::TensorInfo outputTensorInfo({ 3, 3, 3 }, ArmnnType);
     std::vector<std::vector<T>> inputData;
     inputData.push_back(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9
     });
     inputData.push_back(
     {
         10, 11, 12,
         13, 14, 15,
         16, 17, 18
     });
     inputData.push_back(
     {
         19, 20, 21,
         22, 23, 24,
         25, 26, 27
     });
     std::vector<T> outputExpectedData =
     {
         1, 2, 3,
         10, 11, 12,
         19, 20, 21,
         4, 5, 6,
         13, 14, 15,
         22, 23, 24,
         7, 8, 9,
         16, 17, 18,
         25, 26, 27
     };
     return StackTestHelper<ArmnnType, T, 3>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         1U,
         inputData,
         outputExpectedData
     );
 }
StackOutput4DAxis1Float32Test()
LayerTestResult<float, 4> StackOutput4DAxis1Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 525 of file StackTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return StackOutput4DAxis1TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput4DAxis1TestImpl()
LayerTestResult<T, 4> StackOutput4DAxis1TestImpl (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 154 of file StackTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo ({ 3, 2, 3 }, ArmnnType);
     armnn::TensorInfo outputTensorInfo({ 3, 2, 2, 3 }, ArmnnType);
     std::vector<std::vector<T>> inputData;
     inputData.push_back(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18
     });
     inputData.push_back(
     {
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36
     });
     std::vector<T> outputExpectedData =
     {
         1, 2, 3,
         4, 5, 6,
         19, 20, 21,
         22, 23, 24,
         7, 8, 9,
         10, 11, 12,
         25, 26, 27,
         28, 29, 30,
         13, 14, 15,
         16, 17, 18,
         31, 32, 33,
         34, 35, 36
     };
     return StackTestHelper<ArmnnType, T, 4>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         1U,
         inputData,
         outputExpectedData
     );
 }
StackOutput4DAxis2Float32Test()
LayerTestResult<float, 4> StackOutput4DAxis2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 533 of file StackTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return StackOutput4DAxis2TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput4DAxis2TestImpl()
LayerTestResult<T, 4> StackOutput4DAxis2TestImpl (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 224 of file StackTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo ({ 3, 2, 3 }, ArmnnType);
     armnn::TensorInfo outputTensorInfo({ 3, 2, 2, 3 }, ArmnnType);
     std::vector<std::vector<T>> inputData;
     inputData.push_back(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18
     });
     inputData.push_back(
     {
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36
     });
     std::vector<T> outputExpectedData =
     {
         1, 2, 3,
         19, 20, 21,
         4, 5, 6,
         22, 23, 24,
         7, 8, 9,
         25, 26, 27,
         10, 11, 12,
         28, 29, 30,
         13, 14, 15,
         31, 32, 33,
         16, 17, 18,
         34, 35, 36
     };
     return StackTestHelper<ArmnnType, T, 4>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         2U,
         inputData,
         outputExpectedData
     );
 }
StackOutput4DAxis3Float32Test()
LayerTestResult<float, 4> StackOutput4DAxis3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 541 of file StackTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return StackOutput4DAxis3TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput4DAxis3TestImpl()
LayerTestResult<T, 4> StackOutput4DAxis3TestImpl (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 292 of file StackTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo ({ 3, 2, 3 }, ArmnnType);
     armnn::TensorInfo outputTensorInfo({ 3, 2, 3, 2 }, ArmnnType);
     std::vector<std::vector<T>> inputData;
     inputData.push_back(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18
     });
     inputData.push_back(
     {
         19, 20, 21,
         22, 23, 24,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36
     });
     std::vector<T> outputExpectedData =
     {
         1, 19,
         2, 20,
         3, 21,
         4, 22,
         5, 23,
         6, 24,
         7, 25,
         8, 26,
         9, 27,
         10, 28,
         11, 29,
         12, 30,
         13, 31,
         14, 32,
         15, 33,
         16, 34,
         17, 35,
         18, 36
     };
     return StackTestHelper<ArmnnType, T, 4>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         3U,
         inputData,
         outputExpectedData
     );
 }
StackOutput5DFloat32Test()
LayerTestResult<float, 5> StackOutput5DFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 557 of file StackTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return StackOutput5DTestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput5DTestImpl()
LayerTestResult<T, 5> StackOutput5DTestImpl (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 427 of file StackTestImpl.cpp.
 {
     armnn::TensorInfo inputTensorInfo ({ 2, 2, 2, 3 }, ArmnnType);
     armnn::TensorInfo outputTensorInfo({ 2, 2, 2, 2, 3 }, ArmnnType);
     std::vector<std::vector<T>> inputData;
     inputData.push_back(
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24
     });
     inputData.push_back(
     {
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48
     });
     std::vector<T> outputExpectedData =
     {
         1, 2, 3,
         4, 5, 6,
         7, 8, 9,
         10, 11, 12,
         25, 26, 27,
         28, 29, 30,
         31, 32, 33,
         34, 35, 36,
         13, 14, 15,
         16, 17, 18,
         19, 20, 21,
         22, 23, 24,
         37, 38, 39,
         40, 41, 42,
         43, 44, 45,
         46, 47, 48
     };
     return StackTestHelper<ArmnnType, T, 5>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         1U,
         inputData,
         outputExpectedData
     );
 }