ArmNN: src/armnnUtils/test/TensorUtilsTest.cpp File Reference
TensorUtilsTest.cpp File Reference
#include <armnn/Types.hpp>
#include <armnnUtils/TensorUtils.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (ExpandDimsAxis0Test)
BOOST_AUTO_TEST_CASE (ExpandDimsAxis1Test)
BOOST_AUTO_TEST_CASE (ExpandDimsAxis2Test)
BOOST_AUTO_TEST_CASE (ExpandDimsAxis3Test)
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis1Test)
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis2Test)
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis3Test)
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis4Test)
BOOST_AUTO_TEST_CASE (ExpandDimsInvalidAxisTest)
BOOST_AUTO_TEST_CASE (ExpandDimsInvalidNegativeAxisTest)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/10]
BOOST_AUTO_TEST_CASE (ExpandDimsAxis0Test)
Definition at line 17 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension 0
     armnn::TensorShape outputShape = ExpandDims(inputShape, 0);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 1);
     BOOST_TEST(outputShape[1] == 2);
     BOOST_TEST(outputShape[2] == 3);
     BOOST_TEST(outputShape[3] == 4);
 }
BOOST_AUTO_TEST_CASE() [2/10]
BOOST_AUTO_TEST_CASE (ExpandDimsAxis1Test)
Definition at line 30 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension 1
     armnn::TensorShape outputShape = ExpandDims(inputShape, 1);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 2);
     BOOST_TEST(outputShape[1] == 1);
     BOOST_TEST(outputShape[2] == 3);
     BOOST_TEST(outputShape[3] == 4);
 }
BOOST_AUTO_TEST_CASE() [3/10]
BOOST_AUTO_TEST_CASE (ExpandDimsAxis2Test)
Definition at line 43 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension 2
     armnn::TensorShape outputShape = ExpandDims(inputShape, 2);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 2);
     BOOST_TEST(outputShape[1] == 3);
     BOOST_TEST(outputShape[2] == 1);
     BOOST_TEST(outputShape[3] == 4);
 }
BOOST_AUTO_TEST_CASE() [4/10]
BOOST_AUTO_TEST_CASE (ExpandDimsAxis3Test)
Definition at line 56 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension 3
     armnn::TensorShape outputShape = ExpandDims(inputShape, 3);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 2);
     BOOST_TEST(outputShape[1] == 3);
     BOOST_TEST(outputShape[2] == 4);
     BOOST_TEST(outputShape[3] == 1);
 }
BOOST_AUTO_TEST_CASE() [5/10]
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis1Test)
Definition at line 69 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension -1
     armnn::TensorShape outputShape = ExpandDims(inputShape, -1);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 2);
     BOOST_TEST(outputShape[1] == 3);
     BOOST_TEST(outputShape[2] == 4);
     BOOST_TEST(outputShape[3] == 1);
 }
BOOST_AUTO_TEST_CASE() [6/10]
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis2Test)
Definition at line 82 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension -2
     armnn::TensorShape outputShape = ExpandDims(inputShape, -2);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 2);
     BOOST_TEST(outputShape[1] == 3);
     BOOST_TEST(outputShape[2] == 1);
     BOOST_TEST(outputShape[3] == 4);
 }
BOOST_AUTO_TEST_CASE() [7/10]
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis3Test)
Definition at line 95 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension -3
     armnn::TensorShape outputShape = ExpandDims(inputShape, -3);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 2);
     BOOST_TEST(outputShape[1] == 1);
     BOOST_TEST(outputShape[2] == 3);
     BOOST_TEST(outputShape[3] == 4);
 }
BOOST_AUTO_TEST_CASE() [8/10]
BOOST_AUTO_TEST_CASE (ExpandDimsNegativeAxis4Test)
Definition at line 108 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Expand dimension -4
     armnn::TensorShape outputShape = ExpandDims(inputShape, -4);
     BOOST_TEST(outputShape.GetNumDimensions() == 4);
     BOOST_TEST(outputShape[0] == 1);
     BOOST_TEST(outputShape[1] == 2);
     BOOST_TEST(outputShape[2] == 3);
     BOOST_TEST(outputShape[3] == 4);
 }
BOOST_AUTO_TEST_CASE() [9/10]
BOOST_AUTO_TEST_CASE (ExpandDimsInvalidAxisTest)
Definition at line 121 of file TensorUtilsTest.cpp.
References armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Invalid expand dimension 4
     BOOST_CHECK_THROW(ExpandDims(inputShape, 4), armnn::InvalidArgumentException);
 }
BOOST_AUTO_TEST_CASE() [10/10]
BOOST_AUTO_TEST_CASE (ExpandDimsInvalidNegativeAxisTest)
Definition at line 129 of file TensorUtilsTest.cpp.
References BOOST_AUTO_TEST_SUITE_END(), and armnnUtils::ExpandDims().
 {
     armnn::TensorShape inputShape({ 2, 3, 4 });
     // Invalid expand dimension -5
     BOOST_CHECK_THROW(ExpandDims(inputShape, -5), armnn::InvalidArgumentException);
 }