ArmNN: src/armnnTfParser/test/TestDependencies.cpp File Reference
TestDependencies.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "armnnTfParser/ITfParser.hpp"
#include "ParserPrototxtFixture.hpp"
Functions
BOOST_FIXTURE_TEST_CASE (RediscoveredDependencies, RediscoveredDependenciesFixture)
BOOST_AUTO_TEST_CASE (SimpleCycle)
BOOST_AUTO_TEST_CASE (SingleNodeCycle)
BOOST_AUTO_TEST_CASE (ComplexCycle)
BOOST_AUTO_TEST_CASE (InvalidInput)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (SimpleCycle)
Definition at line 124 of file TestDependencies.cpp.
References ITfParser::Create().
 {
     const char* prototext = R"(
 node {
   name: "r1"
   op: "Relu"
   input: "r2"
   attr {
     key: "T"
     value {
       type: DT_FLOAT
     }
   }
 }
 node {
   name: "r2"
   op: "Relu"
   input: "r1"
   attr {
     key: "T"
     value {
       type: DT_FLOAT
     }
   }
 }
     )";
     armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
     BOOST_CHECK_THROW(parser->CreateNetworkFromString(prototext, {}, { "r2" }), armnn::ParseException);
 }
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (SingleNodeCycle)
Definition at line 155 of file TestDependencies.cpp.
References ITfParser::Create().
 {
     const char* prototext = R"(
 node {
   name: "r1"
   op: "Relu"
   input: "r1"
   attr {
     key: "T"
     value {
       type: DT_FLOAT
     }
   }
 }
     )";
     armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
     BOOST_CHECK_THROW(parser->CreateNetworkFromString(prototext, {}, { "r1" }), armnn::ParseException);
 }
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (ComplexCycle)
Definition at line 185 of file TestDependencies.cpp.
References ITfParser::Create().
 {
     // Input = tf.placeholder(tf.float32, 1, "input")
     // Add2 = tf.nn.relu(input, add1, "add2") // This line won't actually run in TF, because add1 is not yet defined
     // Relu1 = tf.nn.relu(relu0, "relu1")
     // Relu2 = tf.nn.relu(relu0, "relu2")
     // Relu3 = tf.nn.relu(relu2, "relu3")
     // Add1 = tf.add(relu1, relu3, "add1")
     const char* prototext = R"(
         node {
             name: "input"
             op: "Placeholder"
             attr {
             key: "dtype"
             value {
                 type: DT_FLOAT
             }
             }
             attr {
             key: "shape"
             value {
                 shape {
                 dim {
                     size: 1
                 }
                 }
             }
             }
         }
         node {
             name: "add2"
             op: "Add"
             input: "input"
             input: "add1"
             attr {
             key: "T"
             value {
                 type: DT_FLOAT
             }
             }
         }
         node {
             name: "relu1"
             op: "Relu"
             input: "add2"
             attr {
             key: "T"
             value {
                 type: DT_FLOAT
             }
             }
         }
         node {
             name: "relu2"
             op: "Relu"
             input: "add2"
             attr {
             key: "T"
             value {
                 type: DT_FLOAT
             }
             }
         }
         node {
             name: "relu3"
             op: "Relu"
             input: "relu2"
             attr {
             key: "T"
             value {
                 type: DT_FLOAT
             }
             }
         }
         node {
             name: "add1"
             op: "Add"
             input: "relu1"
             input: "relu3"
             attr {
             key: "T"
             value {
                 type: DT_FLOAT
             }
             }
         }
     )";
     armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
     BOOST_CHECK_THROW(parser->CreateNetworkFromString(prototext, {}, { "add1" }), armnn::ParseException);
 }
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (InvalidInput)
Definition at line 277 of file TestDependencies.cpp.
References BOOST_AUTO_TEST_SUITE_END(), and ITfParser::Create().
 {
     const char* prototext = R"(
 node {
   name: "r1"
   op: "Relu"
   input: "a-node-that-does-not-exist"
   attr {
     key: "T"
     value {
       type: DT_FLOAT
     }
   }
 }
     )";
     armnnTfParser::ITfParserPtr parser = armnnTfParser::ITfParser::Create();
     BOOST_CHECK_THROW(parser->CreateNetworkFromString(prototext, {}, { "r1" }), armnn::ParseException);
 }
BOOST_FIXTURE_TEST_CASE()
BOOST_FIXTURE_TEST_CASE (RediscoveredDependencies , RediscoveredDependenciesFixture)
Definition at line 117 of file TestDependencies.cpp.
 {
     RunTest<1>({1}, {2});
 }