ArmNN: tests/TfLiteYoloV3Big-Armnn/TfLiteYoloV3Big-Armnn.cpp File Reference
TfLiteYoloV3Big-Armnn.cpp File Reference
#include "armnnTfLiteParser/ITfLiteParser.hpp"
#include "NMS.hpp"
#include <stb/stb_image.h>
#include <armnn/INetwork.hpp>
#include <armnn/IRuntime.hpp>
#include <armnn/Logging.hpp>
#include <armnn/utility/IgnoreUnused.hpp>
#include <cxxopts/cxxopts.hpp>
#include <ghc/filesystem.hpp>
#include <chrono>
#include <fstream>
#include <iostream>
#include <stdlib.h>
Macros
#define CHECK_OK(v)
#define S_BOOL(name) enum class name {False=0, True=1};
Enumerations
enum ImportMemory { False =0, True =1 }
enum DumpToDot { False =0, True =1 }
enum ExpectFile { False =0, True =1 }
enum OptionalArg { False =0, True =1 }
Functions
template<typename TContainer >
armnn::InputTensors MakeInputTensors (const std::vector< armnn::BindingPointInfo > &inputBindings, const std::vector< std::reference_wrapper< TContainer >> &inputDataContainers)
template<typename TContainer >
armnn::OutputTensors MakeOutputTensors (const std::vector< armnn::BindingPointInfo > &outputBindings, const std::vector< std::reference_wrapper< TContainer >> &outputDataContainers)
int LoadModel (const char *filename, ITfLiteParser &parser, IRuntime &runtime, NetworkId &networkId, const std::vector< BackendId > &backendPreferences, ImportMemory enableImport, DumpToDot dumpToDot)
std::vector< float > LoadImage (const char *filename)
bool ValidateFilePath (std::string &file, ExpectFile expectFile)
void CheckAccuracy (std::vector< float > *toDetector0, std::vector< float > *toDetector1, std::vector< float > *toDetector2, std::vector< float > *detectorOutput, const std::vector< yolov3::Detection > &nmsOut, const std::vector< std::string > &filePaths)
int main (int argc, char *argv[])
Macro Definition Documentation
CHECK_OK
#define CHECK_OK (v)
Value:
do {                                                \
        try {                                           \
            auto r_local = v;                           \
            if (r_local != 0) { return r_local;}        \
        }                                               \
        catch (const armnn::Exception& e)               \
        {                                               \
            ARMNN_LOG(error) << "Oops: " << e.what();   \
            return GENERAL_ERROR;                       \
        }                                               \
    } while(0)
Definition at line 34 of file TfLiteYoloV3Big-Armnn.cpp.
Referenced by main().
S_BOOL
#define S_BOOL (name) enum class name {False=0, True=1};
Definition at line 100 of file TfLiteYoloV3Big-Armnn.cpp.
Enumeration Type Documentation
DumpToDot
enum DumpToDot strong
Enumerator
False
True
Definition at line 103 of file TfLiteYoloV3Big-Armnn.cpp.
ExpectFile
enum ExpectFile strong
Enumerator
False
True
Definition at line 104 of file TfLiteYoloV3Big-Armnn.cpp.
ImportMemory
enum ImportMemory strong
Enumerator
False
True
Definition at line 102 of file TfLiteYoloV3Big-Armnn.cpp.
OptionalArg
enum OptionalArg strong
Enumerator
False
True
Definition at line 105 of file TfLiteYoloV3Big-Armnn.cpp.
Function Documentation
CheckAccuracy()
void CheckAccuracy (std::vector< float > * toDetector0, std::vector< float > * toDetector1, std::vector< float > * toDetector2, std::vector< float > * detectorOutput, const std::vector< yolov3::Detection > & nmsOut, const std::vector< std::string > & filePaths)
Definition at line 223 of file TfLiteYoloV3Big-Armnn.cpp.
References ARMNN_LOG, yolov3::compare_detection(), armnn::error, False, GetBackendIDs(), armnn::info, True, and ValidateFilePath().
 {
     std::ifstream pathStream;
     std::vector<float> expected;
     std::vector<std::vector<float>*> outputs;
     float compare = 0;
     unsigned int count = 0;
     //Push back output vectors from inference for use in loop
     outputs.push_back(toDetector0);
     outputs.push_back(toDetector1);
     outputs.push_back(toDetector2);
     outputs.push_back(detectorOutput);
     for (unsigned int i = 0; i < outputs.size(); ++i)
     {
         // Reading expected output files and assigning them to @expected. Close and Clear to reuse stream and clean RAM
         pathStream.open(filePaths[i]);
         if (!pathStream.is_open())
         {
             ARMNN_LOG(error) << "Expected output file can not be opened: " << filePaths[i];
             continue;
         }
         expected.assign(std::istream_iterator<float>(pathStream), {});
         pathStream.close();
         pathStream.clear();
         // Ensure each vector is the same length
         if (expected.size() != outputs[i]->size())
         {
             ARMNN_LOG(error) << "Expected output size does not match actual output size: " << filePaths[i];
         }
         else
         {
             count = 0;
             // Compare abs(difference) with tolerance to check for value by value equality
             for (unsigned int j = 0; j < outputs[i]->size(); ++j)
             {
                 compare = abs(expected[j] - outputs[i]->at(j));
                 if (compare > 0.001f)
                 {
                     count++;
                 }
             }
             if (count > 0)
             {
                 ARMNN_LOG(error) << count << " output(s) do not match expected values in: " << filePaths[i];
             }
         }
     }
     pathStream.open(filePaths[4]);
     if (!pathStream.is_open())
     {
         ARMNN_LOG(error) << "Expected output file can not be opened: " << filePaths[4];
     }
     else
     {
         expected.assign(std::istream_iterator<float>(pathStream), {});
         pathStream.close();
         pathStream.clear();
         unsigned int y = 0;
         unsigned int numOfMember = 6;
         std::vector<float> intermediate;
         for (auto& detection: nmsOut)
         {
             for (unsigned int x = y * numOfMember; x < ((y * numOfMember) + numOfMember); ++x)
             {
                 intermediate.push_back(expected[x]);
             }
             if (!yolov3::compare_detection(detection, intermediate))
             {
                 ARMNN_LOG(error) << "Expected NMS output does not match: Detection " << y + 1;
             }
             intermediate.clear();
             y++;
         }
     }
 }
LoadImage()
std::vector<float> LoadImage (const char * filename)
Definition at line 162 of file TfLiteYoloV3Big-Armnn.cpp.
References ARMNN_LOG, and armnn::error.
Referenced by main().
 {
     if (strlen(filename) == 0)
     {
         return std::vector<float>(1920*10180*3, 0.0f);
     }
     struct Memory
     {
         ~Memory() {stbi_image_free(m_Data);}
         bool IsLoaded() const { return m_Data != nullptr;}
         unsigned char* m_Data;
     };
     std::vector<float> image;
     int width;
     int height;
     int channels;
     Memory mem = {stbi_load(filename, &width, &height, &channels, 3)};
     if (!mem.IsLoaded())
     {
         ARMNN_LOG(error) << "Could not load input image file: " << filename;
         return image;
     }
     if (width != 1920 || height != 1080 || channels != 3)
     {
         ARMNN_LOG(error) << "Input image has wong dimension: " << width << "x" << height << "x" << channels << ". "
           " Expected 1920x1080x3.";
         return image;
     }
     image.resize(1920*1080*3);
     // Expand to float. Does this need de-gamma?
     for (unsigned int idx=0; idx <= 1920*1080*3; idx++)
     {
         image[idx] = static_cast<float>(mem.m_Data[idx]) /255.0f;
     }
     return image;
 }
LoadModel()
int LoadModel (const char * filename, ITfLiteParser & parser, IRuntime & runtime, NetworkId & networkId, const std::vector< BackendId > & backendPreferences, ImportMemory enableImport, DumpToDot dumpToDot)
Definition at line 107 of file TfLiteYoloV3Big-Armnn.cpp.
References ARMNN_LOG, and armnn::error.
Referenced by main().
 {
     std::ifstream stream(filename, std::ios::in | std::ios::binary);
     if (!stream.is_open())
     {
         ARMNN_LOG(error) << "Could not open model: " << filename;
         return OPEN_FILE_ERROR;
     }
     std::vector<uint8_t> contents((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());
     stream.close();
     auto model = parser.CreateNetworkFromBinary(contents);
     contents.clear();
     ARMNN_LOG(debug) << "Model loaded ok: " << filename;
     // Optimize backbone model
     OptimizerOptions options;
     options.m_ImportEnabled = enableImport != ImportMemory::False;
     auto optimizedModel = Optimize(*model, backendPreferences, runtime.GetDeviceSpec(), options);
     if (!optimizedModel)
     {
         ARMNN_LOG(fatal) << "Could not optimize the model:" << filename;
         return OPTIMIZE_NETWORK_ERROR;
     }
     if (dumpToDot != DumpToDot::False)
     {
         std::stringstream ss;
         ss << filename << ".dot";
         std::ofstream dotStream(ss.str().c_str(), std::ofstream::out);
         optimizedModel->SerializeToDot(dotStream);
         dotStream.close();
     }
     // Load model into runtime
     {
         std::string errorMessage;
         INetworkProperties modelProps(options.m_ImportEnabled, options.m_ImportEnabled);
         Status status = runtime.LoadNetwork(networkId, std::move(optimizedModel), errorMessage, modelProps);
         if (status != Status::Success)
         {
             ARMNN_LOG(fatal) << "Could not load " << filename << " model into runtime: " << errorMessage;
             return LOAD_NETWORK_ERROR;
         }
     }
     return 0;
 }
main()
int main (int argc, char * argv[])
Definition at line 481 of file TfLiteYoloV3Big-Armnn.cpp.
References ARMNN_LOG, CHECK_OK, ITfLiteParser::Create(), False, armnn::fatal, armnn::info, LoadImage(), LoadModel(), IRuntime::CreationOptions::m_DynamicBackendsPath, armnn::SetAllLoggingSinks(), armnn::SetLogFilter(), and True.
 {
     // Configure logging
     SetAllLoggingSinks(true, true, true);
     SetLogFilter(LogSeverity::Trace);
     // Check and get given program arguments
     ParseArgs progArgs = ParseArgs(argc, argv);
     // Create runtime
     IRuntime::CreationOptions runtimeOptions; // default
     if (!progArgs.dynamicBackendPath.empty())
     {
         std::cout << "Loading backends from" << progArgs.dynamicBackendPath << "\n";
         runtimeOptions.m_DynamicBackendsPath = progArgs.dynamicBackendPath;
     }
     auto runtime = IRuntime::Create(runtimeOptions);
     if (!runtime)
     {
         ARMNN_LOG(fatal) << "Could not create runtime.";
         return -1;
     }
     // Create TfLite Parsers
     ITfLiteParser::TfLiteParserOptions parserOptions;
     auto parser = ITfLiteParser::Create(parserOptions);
     // Load backbone model
     ARMNN_LOG(info) << "Loading backbone...";
     NetworkId backboneId;
     const DumpToDot dumpToDot = progArgs.dumpToDot;
     CHECK_OK(LoadModel(progArgs.backboneDir.c_str(),
                        *parser,
                        *runtime,
                        backboneId,
                        progArgs.prefBackendsBackbone,
                        ImportMemory::False,
                        dumpToDot));
     auto inputId = parser->GetNetworkInputBindingInfo(0, "inputs");
     auto bbOut0Id = parser->GetNetworkOutputBindingInfo(0, "input_to_detector_1");
     auto bbOut1Id = parser->GetNetworkOutputBindingInfo(0, "input_to_detector_2");
     auto bbOut2Id = parser->GetNetworkOutputBindingInfo(0, "input_to_detector_3");
     auto backboneProfile = runtime->GetProfiler(backboneId);
     backboneProfile->EnableProfiling(true);
     // Load detector model
     ARMNN_LOG(info) << "Loading detector...";
     NetworkId detectorId;
     CHECK_OK(LoadModel(progArgs.detectorDir.c_str(),
                        *parser,
                        *runtime,
                        detectorId,
                        progArgs.prefBackendsDetector,
                        ImportMemory::True,
                        dumpToDot));
     auto detectIn0Id = parser->GetNetworkInputBindingInfo(0, "input_to_detector_1");
     auto detectIn1Id = parser->GetNetworkInputBindingInfo(0, "input_to_detector_2");
     auto detectIn2Id = parser->GetNetworkInputBindingInfo(0, "input_to_detector_3");
     auto outputBoxesId = parser->GetNetworkOutputBindingInfo(0, "output_boxes");
     auto detectorProfile = runtime->GetProfiler(detectorId);
     // Load input from file
     ARMNN_LOG(info) << "Loading test image...";
     auto image = LoadImage(progArgs.imageDir.c_str());
     if (image.empty())
     {
         return LOAD_IMAGE_ERROR;
     }
     // Allocate the intermediate tensors
     std::vector<float> intermediateMem0(bbOut0Id.second.GetNumElements());
     std::vector<float> intermediateMem1(bbOut1Id.second.GetNumElements());
     std::vector<float> intermediateMem2(bbOut2Id.second.GetNumElements());
     std::vector<float> intermediateMem3(outputBoxesId.second.GetNumElements());
     // Setup inputs and outputs
     using BindingInfos = std::vector<armnn::BindingPointInfo>;
     using FloatTensors = std::vector<std::reference_wrapper<std::vector<float>>>;
     InputTensors bbInputTensors = MakeInputTensors(BindingInfos{ inputId },
                                                    FloatTensors{ image });
     OutputTensors bbOutputTensors = MakeOutputTensors(BindingInfos{ bbOut0Id, bbOut1Id, bbOut2Id },
                                                       FloatTensors{ intermediateMem0,
                                                                     intermediateMem1,
                                                                     intermediateMem2 });
     InputTensors detectInputTensors = MakeInputTensors(BindingInfos{ detectIn0Id,
                                                                      detectIn1Id,
                                                                      detectIn2Id } ,
                                                        FloatTensors{ intermediateMem0,
                                                                      intermediateMem1,
                                                                      intermediateMem2 });
     OutputTensors detectOutputTensors = MakeOutputTensors(BindingInfos{ outputBoxesId },
                                                           FloatTensors{ intermediateMem3 });
     static const int numIterations=2;
     using DurationUS = std::chrono::duration<double, std::micro>;
     std::vector<DurationUS> nmsDurations(0);
     std::vector<yolov3::Detection> filtered_boxes;
     nmsDurations.reserve(numIterations);
     for (int i=0; i < numIterations; i++)
     {
         // Execute backbone
         ARMNN_LOG(info) << "Running backbone...";
         runtime->EnqueueWorkload(backboneId, bbInputTensors, bbOutputTensors);
         // Execute detector
         ARMNN_LOG(info) << "Running detector...";
         runtime->EnqueueWorkload(detectorId, detectInputTensors, detectOutputTensors);
         // Execute NMS
         ARMNN_LOG(info) << "Running nms...";
         using clock = std::chrono::steady_clock;
         auto nmsStartTime = clock::now();
         yolov3::NMSConfig config;
         config.num_boxes = 127800;
         config.num_classes = 80;
         config.confidence_threshold = 0.9f;
         config.iou_threshold = 0.5f;
         filtered_boxes = yolov3::nms(config, intermediateMem3);
         auto nmsEndTime = clock::now();
         // Enable the profiling after the warm-up run
         if (i>0)
         {
             print_detection(std::cout, filtered_boxes);
             const auto nmsDuration = DurationUS(nmsStartTime - nmsEndTime);
             nmsDurations.push_back(nmsDuration);
         }
         backboneProfile->EnableProfiling(true);
         detectorProfile->EnableProfiling(true);
     }
     // Log timings to file
     std::ofstream backboneProfileStream("backbone.json");
     backboneProfile->Print(backboneProfileStream);
     backboneProfileStream.close();
     std::ofstream detectorProfileStream("detector.json");
     detectorProfile->Print(detectorProfileStream);
     detectorProfileStream.close();
     // Manually construct the json output
     std::ofstream nmsProfileStream("nms.json");
     nmsProfileStream << "{" << "\n";
     nmsProfileStream << R"(  "NmsTimings": {)" << "\n";
     nmsProfileStream << R"(    "raw": [)" << "\n";
     bool isFirst = true;
     for (auto duration : nmsDurations)
     {
         if (!isFirst)
         {
             nmsProfileStream << ",\n";
         }
         nmsProfileStream << "      " << duration.count();
         isFirst = false;
     }
     nmsProfileStream << "\n";
     nmsProfileStream << R"(    "units": "us")" << "\n";
     nmsProfileStream << "    ]" << "\n";
     nmsProfileStream << "  }" << "\n";
     nmsProfileStream << "}" << "\n";
     nmsProfileStream.close();
     if (progArgs.comparisonFiles.size() > 0)
     {
         CheckAccuracy(&intermediateMem0,
                       &intermediateMem1,
                       &intermediateMem2,
                       &intermediateMem3,
                       filtered_boxes,
                       progArgs.comparisonFiles);
     }
     ARMNN_LOG(info) << "Run completed";
     return 0;
 }
MakeInputTensors()
armnn::InputTensors MakeInputTensors (const std::vector< armnn::BindingPointInfo > & inputBindings, const std::vector< std::reference_wrapper< TContainer >> & inputDataContainers) inline
Definition at line 50 of file TfLiteYoloV3Big-Armnn.cpp.
Referenced by InferenceModel< IParser, TDataType >::GetAllQuantizationParams(), and InferenceModel< IParser, TDataType >::Run().
 {
     armnn::InputTensors inputTensors;
     const size_t numInputs = inputBindings.size();
     if (numInputs != inputDataContainers.size())
     {
         throw armnn::Exception("Mismatching vectors");
     }
     for (size_t i = 0; i < numInputs; i++)
     {
         const armnn::BindingPointInfo& inputBinding = inputBindings[i];
         const TContainer& inputData = inputDataContainers[i].get();
         armnn::ConstTensor inputTensor(inputBinding.second, inputData.data());
         inputTensors.push_back(std::make_pair(inputBinding.first, inputTensor));
     }
     return inputTensors;
 }
MakeOutputTensors()
armnn::OutputTensors MakeOutputTensors (const std::vector< armnn::BindingPointInfo > & outputBindings, const std::vector< std::reference_wrapper< TContainer >> & outputDataContainers) inline
Definition at line 74 of file TfLiteYoloV3Big-Armnn.cpp.
Referenced by InferenceModel< IParser, TDataType >::GetAllQuantizationParams(), and InferenceModel< IParser, TDataType >::Run().
 {
     armnn::OutputTensors outputTensors;
     const size_t numOutputs = outputBindings.size();
     if (numOutputs != outputDataContainers.size())
     {
         throw armnn::Exception("Mismatching vectors");
     }
     outputTensors.reserve(numOutputs);
     for (size_t i = 0; i < numOutputs; i++)
     {
         const armnn::BindingPointInfo& outputBinding = outputBindings[i];
         const TContainer& outputData = outputDataContainers[i].get();
         armnn::Tensor outputTensor(outputBinding.second, const_cast<float*>(outputData.data()));
         outputTensors.push_back(std::make_pair(outputBinding.first, outputTensor));
     }
     return outputTensors;
 }
ValidateFilePath()
bool ValidateFilePath (std::string & file, ExpectFile expectFile)
Definition at line 208 of file TfLiteYoloV3Big-Armnn.cpp.
References True.
Referenced by CheckAccuracy().
 {
     if (!ghc::filesystem::exists(file))
     {
         std::cerr << "Given file path " << file << " does not exist" << std::endl;
         return false;
     }
     if (!ghc::filesystem::is_regular_file(file) && expectFile == ExpectFile::True)
     {
         std::cerr << "Given file path " << file << " is not a regular file" << std::endl;
         return false;
     }
     return true;
 }