ArmNN: CommandLineProcessor Class Reference
CommandLineProcessor Class Reference
#include <CommandLineProcessor.hpp>
Public Member Functions
bool ProcessCommandLine (int argc, char *argv[])
std::string GetInputFileName ()
std::string GetCsvFileName ()
std::string GetCsvFileDirectory ()
std::string GetOutputDirectoryName ()
std::string GetOutputFileName ()
std::string GetQuantizationScheme ()
QuantizationDataSet GetQuantizationDataSet ()
bool HasPreservedDataType ()
bool HasQuantizationData ()
Protected Attributes
std::string m_InputFileName
std::string m_CsvFileName
std::string m_CsvFileDirectory
std::string m_OutputDirectory
std::string m_OutputFileName
std::string m_QuantizationScheme
QuantizationDataSet m_QuantizationDataSet
bool m_PreserveDataType
Detailed Description
Definition at line 25 of file CommandLineProcessor.hpp.
Member Function Documentation
GetCsvFileDirectory()
std::string GetCsvFileDirectory () inline
Definition at line 32 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_CsvFileDirectory.
 {return m_CsvFileDirectory;}
GetCsvFileName()
std::string GetCsvFileName () inline
Definition at line 31 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_CsvFileName.
 {return m_CsvFileName;}
GetInputFileName()
std::string GetInputFileName () inline
Definition at line 30 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_InputFileName.
Referenced by main().
 {return m_InputFileName;}
GetOutputDirectoryName()
std::string GetOutputDirectoryName () inline
Definition at line 33 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_OutputDirectory.
Referenced by main().
 {return m_OutputDirectory;}
GetOutputFileName()
std::string GetOutputFileName () inline
Definition at line 34 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_OutputFileName.
Referenced by main().
 {return m_OutputFileName;}
GetQuantizationDataSet()
QuantizationDataSet GetQuantizationDataSet () inline
Definition at line 36 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_QuantizationDataSet.
Referenced by main().
 {return m_QuantizationDataSet;}
GetQuantizationScheme()
std::string GetQuantizationScheme () inline
Definition at line 35 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_QuantizationScheme.
Referenced by main().
 {return m_QuantizationScheme;}
HasPreservedDataType()
bool HasPreservedDataType () inline
Definition at line 37 of file CommandLineProcessor.hpp.
References CommandLineProcessor::m_PreserveDataType.
Referenced by main().
 {return m_PreserveDataType;}
HasQuantizationData()
bool HasQuantizationData () inline
Definition at line 38 of file CommandLineProcessor.hpp.
References QuantizationDataSet::IsEmpty(), and CommandLineProcessor::m_QuantizationDataSet.
Referenced by main().
 {return !m_QuantizationDataSet.IsEmpty();}
ProcessCommandLine()
bool ProcessCommandLine (int argc, char * argv[])
Definition at line 84 of file CommandLineProcessor.cpp.
References CommandLineProcessor::m_CsvFileDirectory, CommandLineProcessor::m_CsvFileName, CommandLineProcessor::m_InputFileName, CommandLineProcessor::m_OutputDirectory, CommandLineProcessor::m_OutputFileName, CommandLineProcessor::m_PreserveDataType, CommandLineProcessor::m_QuantizationDataSet, CommandLineProcessor::m_QuantizationScheme, armnnQuantizer::ValidateOutputDirectory(), armnnQuantizer::ValidateProvidedFile(), and armnnQuantizer::ValidateQuantizationScheme().
Referenced by main().
 {
     try
     {
         cxxopts::Options options("ArmnnQuantizer","Convert a Fp32 ArmNN model to a quantized ArmNN model.");
         options.add_options()
             ("h,help", "Display help messages")
             ("f,infile",
                 "Input file containing float 32 ArmNN Input Graph",
                 cxxopts::value<std::string>(m_InputFileName))
             ("s,scheme",
                 "Quantization scheme,"
                 " \"QAsymmU8\" or \"QAsymmS8\" or \"QSymm16\","
                 " default value QAsymmU8",
                 cxxopts::value<std::string>(m_QuantizationScheme)->default_value("QAsymmU8"))
             ("c,csvfile",
                 "CSV file containing paths for RAW input tensors",
                 cxxopts::value<std::string>(m_CsvFileName)->default_value(""))
             ("p,preserve-data-type",
                 "Preserve the input and output data types",
                 cxxopts::value<bool>(m_PreserveDataType)->default_value("false"))
             ("d,outdir",
                 "Directory that output file will be written to",
                 cxxopts::value<std::string>(m_OutputDirectory))
             ("o,outfile",
                 "ArmNN output file name",
                 cxxopts::value<std::string>(m_OutputFileName));
         auto result = options.parse(argc, argv);
         if (result.count("help") > 0 || argc <= 1)
         {
             std::cout << options.help() << std::endl;
             return false;
         }
         // Check for mandatory single options.
         std::string mandatorySingleParameters[] = { "infile", "outdir", "outfile" };
         for (auto param : mandatorySingleParameters)
         {
             if (result.count(param) != 1)
             {
                 std::cerr << "Parameter \'--" << param << "\' is required but missing." << std::endl;
                 return false;
             }
         }
     }
     catch (const cxxopts::OptionException& e)
     {
         std::cerr << e.what() << std::endl << std::endl;
         return false;
     }
     catch (const std::exception& e)
     {
         std::cerr << "Fatal internal error: [" << e.what() << "]" << std::endl;
         return false;
     }
     if (!armnnQuantizer::ValidateProvidedFile(m_InputFileName))
     {
         return false;
     }
     if (!ValidateQuantizationScheme(m_QuantizationScheme))
     {
         return false;
     }
     if (m_CsvFileName != "")
     {
         if (!armnnQuantizer::ValidateProvidedFile(m_CsvFileName))
         {
             return false;
         }
         else
         {
             fs::path csvFilePath(m_CsvFileName);
             m_CsvFileDirectory = csvFilePath.parent_path().c_str();
         }
         // If CSV file is defined, create a QuantizationDataSet for specified CSV file.
         m_QuantizationDataSet = QuantizationDataSet(m_CsvFileName);
     }
     if (!armnnQuantizer::ValidateOutputDirectory(m_OutputDirectory))
     {
         return false;
     }
     std::string output(m_OutputDirectory);
     output.append(m_OutputFileName);
     if (fs::exists(output))
     {
         std::cerr << "Output file [" << output << "] already exists" << std::endl;
         return false;
     }
     return true;
 }
Member Data Documentation
m_CsvFileDirectory
std::string m_CsvFileDirectory protected
Definition at line 43 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetCsvFileDirectory(), and CommandLineProcessor::ProcessCommandLine().
m_CsvFileName
std::string m_CsvFileName protected
Definition at line 42 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetCsvFileName(), and CommandLineProcessor::ProcessCommandLine().
m_InputFileName
std::string m_InputFileName protected
Definition at line 41 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetInputFileName(), and CommandLineProcessor::ProcessCommandLine().
m_OutputDirectory
std::string m_OutputDirectory protected
Definition at line 44 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetOutputDirectoryName(), and CommandLineProcessor::ProcessCommandLine().
m_OutputFileName
std::string m_OutputFileName protected
Definition at line 45 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetOutputFileName(), and CommandLineProcessor::ProcessCommandLine().
m_PreserveDataType
bool m_PreserveDataType protected
Definition at line 48 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::HasPreservedDataType(), and CommandLineProcessor::ProcessCommandLine().
m_QuantizationDataSet
QuantizationDataSet m_QuantizationDataSet protected
Definition at line 47 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetQuantizationDataSet(), CommandLineProcessor::HasQuantizationData(), and CommandLineProcessor::ProcessCommandLine().
m_QuantizationScheme
std::string m_QuantizationScheme protected
Definition at line 46 of file CommandLineProcessor.hpp.
Referenced by CommandLineProcessor::GetQuantizationScheme(), and CommandLineProcessor::ProcessCommandLine().
The documentation for this class was generated from the following files:
src/armnnQuantizer/CommandLineProcessor.hpp
src/armnnQuantizer/CommandLineProcessor.cpp