ArmNN: ITfLiteParser Class Reference
ITfLiteParser Class Reference
#include <ITfLiteParser.hpp>
Classes
struct TfLiteParserOptions
Public Member Functions
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile)
Create the network from a flatbuffers binary file on disk.
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > &binaryContent)
Create the network from a flatbuffers binary.
BindingPointInfo GetNetworkInputBindingInfo (size_t subgraphId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and subgraph id.
BindingPointInfo GetNetworkOutputBindingInfo (size_t subgraphId, const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and subgraph id.
size_t GetSubgraphCount () const
Return the number of subgraphs in the parsed model.
std::vector< std::string > GetSubgraphInputTensorNames (size_t subgraphId) const
Return the input tensor names for a given subgraph.
std::vector< std::string > GetSubgraphOutputTensorNames (size_t subgraphId) const
Return the output tensor names for a given subgraph.
Static Public Member Functions
static ITfLiteParser * CreateRaw (const armnn::Optional< TfLiteParserOptions > &options=armnn::EmptyOptional())
static ITfLiteParserPtr Create (const armnn::Optional< TfLiteParserOptions > &options=armnn::EmptyOptional())
static void Destroy (ITfLiteParser *parser)
Detailed Description
Definition at line 26 of file ITfLiteParser.hpp.
Member Function Documentation
Create()
ITfLiteParserPtr Create (const armnn::Optional< TfLiteParserOptions > & options = armnn::EmptyOptional()) static
Definition at line 64 of file TfLiteParser.cpp.
Referenced by main().
 {
     return ITfLiteParserPtr(CreateRaw(options), &ITfLiteParser::Destroy);
 }
CreateNetworkFromBinary()
armnn::INetworkPtr CreateNetworkFromBinary (const std::vector< uint8_t > & binaryContent)
Create the network from a flatbuffers binary.
Definition at line 79 of file TfLiteParser.cpp.
 {
     return pTfLiteParserImpl->CreateNetworkFromBinary(binaryContent);
 }
CreateNetworkFromBinaryFile()
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile)
Create the network from a flatbuffers binary file on disk.
Definition at line 74 of file TfLiteParser.cpp.
References ITfLiteParser::CreateNetworkFromBinaryFile().
Referenced by ITfLiteParser::CreateNetworkFromBinaryFile().
 {
     return pTfLiteParserImpl->CreateNetworkFromBinaryFile(graphFile);
 }
CreateRaw()
ITfLiteParser * CreateRaw (const armnn::Optional< TfLiteParserOptions > & options = armnn::EmptyOptional()) static
Definition at line 59 of file TfLiteParser.cpp.
 {
     return new ITfLiteParser(options);
 }
Destroy()
void Destroy (ITfLiteParser * parser) static
Definition at line 69 of file TfLiteParser.cpp.
 {
     delete parser;
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (size_t subgraphId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name and subgraph id.
Definition at line 84 of file TfLiteParser.cpp.
 {
     return pTfLiteParserImpl->GetNetworkInputBindingInfo(subgraphId, name);
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (size_t subgraphId, const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name and subgraph id.
Definition at line 90 of file TfLiteParser.cpp.
 {
     return pTfLiteParserImpl->GetNetworkOutputBindingInfo(subgraphId, name);
 }
GetSubgraphCount()
size_t GetSubgraphCount () const
Return the number of subgraphs in the parsed model.
Definition at line 96 of file TfLiteParser.cpp.
 {
     return pTfLiteParserImpl->GetSubgraphCount();
 }
GetSubgraphInputTensorNames()
std::vector< std::string > GetSubgraphInputTensorNames (size_t subgraphId) const
Return the input tensor names for a given subgraph.
Definition at line 101 of file TfLiteParser.cpp.
 {
     return pTfLiteParserImpl->GetSubgraphInputTensorNames(subgraphId);
 }
GetSubgraphOutputTensorNames()
std::vector< std::string > GetSubgraphOutputTensorNames (size_t subgraphId) const
Return the output tensor names for a given subgraph.
Definition at line 106 of file TfLiteParser.cpp.
References CheckLocation::FileLine(), and CheckLocation::m_Function.
 {
     return pTfLiteParserImpl->GetSubgraphOutputTensorNames(subgraphId);
 }
The documentation for this class was generated from the following files:
include/armnnTfLiteParser/ITfLiteParser.hpp
src/armnnTfLiteParser/TfLiteParser.cpp