ArmNN: TimelineModel Class Reference
TimelineModel Class Reference
#include <TimelineModel.hpp>
Public Member Functions
void AddLabel (const arm::pipe::ITimelineDecoder::Label &label)
std::string * FindLabel (uint64_t guid)
void AddEntity (uint64_t guid)
Entity * FindEntity (uint64_t id)
void AddRelationship (const arm::pipe::ITimelineDecoder::Relationship &relationship)
ModelRelationship * FindRelationship (uint64_t id)
const LabelMap & GetLabelMap () const
const Entities & GetEntities () const
const std::vector< arm::pipe::ProfilingException > & GetErrors () const
bool IsInferenceGuid (uint64_t guid) const
void AddEventClass (const arm::pipe::ITimelineDecoder::EventClass &eventClass)
const EventClasses & GetEventClasses () const
EventClassObj * FindEventClass (uint64_t id)
void AddEvent (const arm::pipe::ITimelineDecoder::Event &event)
EventObj * FindEvent (uint64_t id)
Detailed Description
Definition at line 146 of file TimelineModel.hpp.
Member Function Documentation
AddEntity()
void AddEntity (uint64_t guid)
Definition at line 35 of file TimelineModel.cpp.
Referenced by TimelineMessageDecoder::CreateEntity().
 {
     m_Entities.emplace(guid, guid);
 }
AddEvent()
void AddEvent (const arm::pipe::ITimelineDecoder::Event & event)
Definition at line 310 of file TimelineModel.cpp.
Referenced by TimelineMessageDecoder::CreateEvent().
 {
     EventObj evt(event.m_Guid, event.m_TimeStamp, event.m_ThreadId);
     m_Events.emplace(event.m_Guid, evt);
 }
AddEventClass()
void AddEventClass (const arm::pipe::ITimelineDecoder::EventClass & eventClass)
Definition at line 280 of file TimelineModel.cpp.
References TimelineModel::FindLabel(), and EventClassObj::GetGuid().
Referenced by TimelineMessageDecoder::CreateEventClass().
 {
     std::string* eventClassName = FindLabel(eventClass.m_NameGuid);
     if (eventClassName != nullptr)
     {
         EventClassObj eventClassObj(eventClass.m_Guid, *eventClassName);
         m_EventClasses.emplace(eventClassObj.GetGuid(), eventClassObj);
     }
     else
     {
         std::stringstream ss;
         ss << "could not find name [" << eventClass.m_NameGuid << "]";
         ss << " of of event class  [" << eventClass.m_Guid << "]";
         m_Errors.push_back(arm::pipe::ProfilingException(ss.str()));
     }
 }
AddLabel()
void AddLabel (const arm::pipe::ITimelineDecoder::Label & label)
Definition at line 17 of file TimelineModel.cpp.
Referenced by TimelineMessageDecoder::CreateLabel().
 {
     m_LabelMap.emplace(label.m_Guid, label);
 }
AddRelationship()
void AddRelationship (const arm::pipe::ITimelineDecoder::Relationship & relationship)
Definition at line 53 of file TimelineModel.cpp.
References Entity::AddAttribute(), Entity::AddChild(), Entity::AddConnection(), Entity::AddEvent(), Entity::AddExecution(), LabelsAndEventClasses::CHILD_GUID, LabelsAndEventClasses::CONNECTION_GUID, LabelsAndEventClasses::EXECUTION_OF_GUID, TimelineModel::FindEntity(), TimelineModel::FindEvent(), TimelineModel::FindEventClass(), TimelineModel::FindLabel(), LabelsAndEventClasses::INFERENCE, EventObj::SetEventClass(), and LabelsAndEventClasses::TYPE_LABEL.
Referenced by TimelineMessageDecoder::CreateRelationship().
 {
     m_Relationships.emplace(relationship.m_Guid, relationship);
     if (relationship.m_RelationshipType == arm::pipe::ITimelineDecoder::RelationshipType::LabelLink)
     {
         HandleLabelLink(relationship);
     }
     else if (relationship.m_RelationshipType == arm::pipe::ITimelineDecoder::RelationshipType::RetentionLink)
     {
         // Take care of the special case of a connection between layers in ArmNN
         // modelled by a retention link between two layer entities with an attribute GUID
         // of connection
         if (relationship.m_AttributeGuid == armnn::profiling::LabelsAndEventClasses::CONNECTION_GUID)
         {
             HandleConnection(relationship);
         }
         else if (relationship.m_AttributeGuid == armnn::profiling::LabelsAndEventClasses::CHILD_GUID)
         {
             HandleChild(relationship);
         }
         else if (relationship.m_AttributeGuid == armnn::profiling::LabelsAndEventClasses::EXECUTION_OF_GUID)
         {
             HandleExecutionOf(relationship);
         }
         else
         {
             // report unknown relationship type
             std::stringstream ss;
             ss << "Encountered a RetentionLink of unknown type [" << relationship.m_AttributeGuid << "]";
             m_Errors.push_back(arm::pipe::ProfilingException(ss.str()));
         }
     }
     else if (relationship.m_RelationshipType == arm::pipe::ITimelineDecoder::RelationshipType::ExecutionLink)
     {
         HandleExecutionLink(relationship);
     }
 }
FindEntity()
Entity * FindEntity (uint64_t id)
Definition at line 40 of file TimelineModel.cpp.
Referenced by TimelineModel::AddRelationship().
 {
     auto iter = m_Entities.find(id);
     if (iter != m_Entities.end())
     {
         return &(iter->second);
     }
     else
     {
         return nullptr;
     }
 }
FindEvent()
EventObj * FindEvent (uint64_t id)
Definition at line 316 of file TimelineModel.cpp.
Referenced by TimelineModel::AddRelationship().
 {
     auto iter = m_Events.find(id);
     if (iter != m_Events.end())
     {
         return &(iter->second);
     }
     else
     {
         return nullptr;
     }
 }
FindEventClass()
EventClassObj * FindEventClass (uint64_t id)
Definition at line 297 of file TimelineModel.cpp.
Referenced by TimelineModel::AddRelationship().
 {
     auto iter = m_EventClasses.find(id);
     if (iter != m_EventClasses.end())
     {
         return &(iter->second);
     }
     else
     {
         return nullptr;
     }
 }
FindLabel()
std::string * FindLabel (uint64_t guid)
Definition at line 22 of file TimelineModel.cpp.
Referenced by TimelineModel::AddEventClass(), and TimelineModel::AddRelationship().
 {
     auto iter = m_LabelMap.find(guid);
     if (iter != m_LabelMap.end())
     {
         return &iter->second.m_Name;
     }
     else
     {
         return nullptr;
     }
 }
FindRelationship()
ModelRelationship * FindRelationship (uint64_t id)
Definition at line 261 of file TimelineModel.cpp.
 {
     auto iter = m_Relationships.find(id);
     if (iter != m_Relationships.end())
     {
         return &(iter->second);
     }
     else
     {
         return nullptr;
     }
 }
GetEntities()
const Entities& GetEntities () const inline
Definition at line 156 of file TimelineModel.hpp.
Referenced by armnn::profiling::GetModelDescription().
 {return m_Entities;}
GetErrors()
const std::vector<arm::pipe::ProfilingException>& GetErrors () const inline
Definition at line 157 of file TimelineModel.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {return m_Errors;}
GetEventClasses()
const EventClasses& GetEventClasses () const inline
Definition at line 160 of file TimelineModel.hpp.
References armnn::profiling::GetChildDescription(), armnn::profiling::GetConnectionDescription(), armnn::profiling::GetEntityDescription(), armnn::profiling::GetEventDescription(), armnn::profiling::GetExecutionDescription(), and armnn::profiling::GetModelDescription().
 {return m_EventClasses;}
GetLabelMap()
const LabelMap& GetLabelMap () const inline
Definition at line 155 of file TimelineModel.hpp.
 {return m_LabelMap;}
IsInferenceGuid()
bool IsInferenceGuid (uint64_t guid) const
Definition at line 274 of file TimelineModel.cpp.
Referenced by TimelineMessageDecoder::CreateRelationship().
 {
     auto it = std::find(m_InferenceGuids.begin(), m_InferenceGuids.end(), guid);
     return it != m_InferenceGuids.end();
 }
The documentation for this class was generated from the following files:
src/profiling/test/TimelineModel.hpp
src/profiling/test/TimelineModel.cpp