ArmNN: ITensorHandleFactory Class Reference
ITensorHandleFactory Class Reference abstract
#include <ITensorHandleFactory.hpp>
Public Types
using FactoryId = std::string
Public Member Functions
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const =0
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const =0
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const =0
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const
Utility Functions for backends which require TensorHandles to have unmanaged memory.
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const
virtual const FactoryId & GetId () const =0
virtual bool SupportsInPlaceComputation () const
virtual bool SupportsSubTensors () const =0
virtual bool SupportsMapUnmap () const final
virtual MemorySourceFlags GetExportFlags () const
virtual MemorySourceFlags GetImportFlags () const
virtual std::vector< Capability > GetCapabilities (const IConnectableLayer *layer, const IConnectableLayer *connectedLayer, CapabilityClass capabilityClass)
Static Public Attributes
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Detailed Description
Definition at line 41 of file ITensorHandleFactory.hpp.
Member Typedef Documentation
FactoryId
using FactoryId = std::string
Definition at line 44 of file ITensorHandleFactory.hpp.
Constructor & Destructor Documentation
~ITensorHandleFactory()
virtual ~ITensorHandleFactory () inline virtual
Some TensorHandleFactory decisions are deferred to run-time.
Definition at line 48 of file ITensorHandleFactory.hpp.
 {}
Member Function Documentation
CreateSubTensorHandle()
virtual std::unique_ptr<ITensorHandle> CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const pure virtual
Implemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Referenced by ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), and ConcatUint8Test().
CreateTensorHandle() [1/4]
virtual std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo) const pure virtual
Implemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Referenced by AdditionAfterMaxPoolTest(), AdditionBroadcast1ElementTestImpl(), AdditionBroadcastTestImpl(), BoundedReLuTestCommon(), BoundedReLuUint8UpperAndLowerBoundTest(), CompareActivationTestImpl(), CompareAdditionTest(), CompareBatchNormTest(), CompareConvolution2dTestImpl(), CompareDepthwiseConvolution2dTestImpl(), CompareMultiplicationTest(), ConcatDifferentInputOutputQParamTest(), Concatenate(), ConcatTest(), ConcatUint16Test(), ConcatUint8DifferentQParamsTest(), ConcatUint8Test(), ConstantLinearActivationTestCommon(), ConvertBf16ToFp32Test(), ConvertFp32ToBf16Test(), Convolution1dTestImpl(), Convolution2dPerAxisQuantTest(), OutputHandler::CreateTensorHandles(), DepthwiseConvolution2dAsymmetricTestImpl(), DepthwiseConvolution2dDepthMul1TestImpl(), DepthwiseConvolution2dPerAxisQuantTest(), DepthwiseConvolution2dTestImpl(), ElementwiseTestHelper(), ElementwiseUnaryTestHelper(), FakeQuantizationTest(), L2Normalization2dShapeTest(), Pad2dTestCommon(), Pad3dTestCommon(), Pad4dTestCommon(), PadQAsymmTestCommon(), PermuteTensorData(), PreluTest(), RankTest(), SimpleActivationTest(), SimpleConvertFp16ToFp32Test(), SimpleConvertFp32ToFp16Test(), SimpleConvolution2dNhwcTestImpl(), SimpleConvolution2dTestImpl(), SimpleFillTest(), SimpleFloorTest(), SimpleFullyConnectedTestImpl(), SimplePermuteTestImpl(), SimpleTransposeTestImpl(), SqrtNNTest(), and TransposeConvolution2dPerAxisQuantTest().
CreateTensorHandle() [2/4]
virtual std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const pure virtual
Implemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
CreateTensorHandle() [3/4]
virtual std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged) const inline virtual
Utility Functions for backends which require TensorHandles to have unmanaged memory.
These should be overloaded if required to facilitate direct import of input tensors and direct export of output tensors.
Reimplemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Definition at line 62 of file ITensorHandleFactory.hpp.
References armnn::IgnoreUnused().
     {
         IgnoreUnused(IsMemoryManaged);
         return CreateTensorHandle(tensorInfo);
     }
CreateTensorHandle() [4/4]
virtual std::unique_ptr<ITensorHandle> CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const inline virtual
Reimplemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Definition at line 69 of file ITensorHandleFactory.hpp.
References armnn::IgnoreUnused().
     {
         IgnoreUnused(IsMemoryManaged);
         return CreateTensorHandle(tensorInfo, dataLayout);
     }
GetCapabilities()
virtual std::vector<Capability> GetCapabilities (const IConnectableLayer * layer, const IConnectableLayer * connectedLayer, CapabilityClass capabilityClass) inline virtual
Reimplemented in NeonTensorHandleFactory.
Definition at line 88 of file ITensorHandleFactory.hpp.
References armnn::IgnoreUnused().
Referenced by armnn::CalculateEdgeStrategy(), ConcatLayer::CreateWorkload(), and SplitterLayer::CreateWorkload().
     {
         IgnoreUnused(layer);
         IgnoreUnused(connectedLayer);
         IgnoreUnused(capabilityClass);
         return std::vector<Capability>();
     }
GetExportFlags()
virtual MemorySourceFlags GetExportFlags () const inline virtual
Reimplemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Definition at line 85 of file ITensorHandleFactory.hpp.
Referenced by armnn::CalculateEdgeStrategy(), and armnn::RequiresCopy().
 { return 0; }
GetId()
virtual const FactoryId& GetId () const pure virtual
Implemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
GetImportFlags()
virtual MemorySourceFlags GetImportFlags () const inline virtual
Reimplemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Definition at line 86 of file ITensorHandleFactory.hpp.
Referenced by armnn::CalculateEdgeStrategy(), armnn::CalculateSlotOptionForInput(), and armnn::RequiresCopy().
 { return 0; }
SupportsInPlaceComputation()
virtual bool SupportsInPlaceComputation () const inline virtual
Reimplemented in NeonTensorHandleFactory.
Definition at line 79 of file ITensorHandleFactory.hpp.
 { return false; }
SupportsMapUnmap()
virtual bool SupportsMapUnmap () const inline final virtual
Definition at line 83 of file ITensorHandleFactory.hpp.
Referenced by armnn::CalculateEdgeStrategy(), armnn::CalculateSlotOption(), and armnn::CalculateSlotOptionForInput().
 { return true; }
SupportsSubTensors()
virtual bool SupportsSubTensors () const pure virtual
Implemented in NeonTensorHandleFactory, ClTensorHandleFactory, RefTensorHandleFactory, and SampleDynamicTensorHandleFactory.
Member Data Documentation
DeferredFactoryId
const ITensorHandleFactory::FactoryId DeferredFactoryId = "armnn_deferred_factory" static
Use the workload factory to create the tensor handle.
Definition at line 46 of file ITensorHandleFactory.hpp.
Referenced by armnn::CalculateSlotOptionForOutput().
LegacyFactoryId
const ITensorHandleFactory::FactoryId LegacyFactoryId = "armnn_legacy_factory" static
Definition at line 45 of file ITensorHandleFactory.hpp.
Referenced by Graph::AddCompatibilityLayers(), armnn::CalculateEdgeStrategy(), armnn::CalculateSlotOption(), armnn::CalculateSlotOptionForInput(), ConcatLayer::CreateTensorHandles(), SplitterLayer::CreateTensorHandles(), Layer::CreateTensorHandles(), IBackendInternal::GetBackwardCompatibleFavoriteHandleFactory(), and armnn::SelectTensorHandleStrategy().
The documentation for this class was generated from the following files:
include/armnn/backends/ITensorHandleFactory.hpp
src/backends/backendsCommon/ITensorHandleFactory.cpp