ArmNN: INetwork Class Reference
INetwork Class Reference
Main network class which provides the interface for building up a neural network.
#include <INetwork.hpp>
Public Member Functions
Status PrintGraph ()
IConnectableLayer * AddInputLayer (LayerBindingId id, const char *name=nullptr)
Adds an input layer to the network.
IConnectableLayer * AddArgMinMaxLayer (const ArgMinMaxDescriptor &desc, const char *name=nullptr)
Adds an ArgMinMax layer to the network.
IConnectableLayer * AddComparisonLayer (const ComparisonDescriptor &comparisonDescriptor, const char *name=nullptr)
Add a Comparison layer to the network.
IConnectableLayer * AddConcatLayer (const ConcatDescriptor &concatDescriptor, const char *name=nullptr)
Adds a concatenation layer to the network.
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)
Adds a 2D convolution layer to the network.
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const char *name=nullptr)
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const ConstTensor &biases, const char *name=nullptr)
IConnectableLayer * AddDepthToSpaceLayer (const DepthToSpaceDescriptor &depthToSpaceDescriptor, const char *name=nullptr)
Adds a depth to space layer to the network.
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)
Adds a 2D depthwise convolution layer to the network.
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const char *name=nullptr)
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const ConstTensor &biases, const char *name=nullptr)
IConnectableLayer * AddDequantizeLayer (const char *name=nullptr)
Adds a Dequantize layer to the network.
IConnectableLayer * AddDetectionPostProcessLayer (const DetectionPostProcessDescriptor &descriptor, const ConstTensor &anchors, const char *name=nullptr)
Adds a Detection PostProcess layer to the network.
IConnectableLayer * AddElementwiseUnaryLayer (const ElementwiseUnaryDescriptor &elementwiseUnaryDescriptor, const char *name=nullptr)
Add an ElementwiseUnary layer to the network.
IConnectableLayer * AddFillLayer (const FillDescriptor &fillDescriptor, const char *name=nullptr)
Add an Fill layer to the network.
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)
Adds a fully connected layer to the network.
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const char *name=nullptr)
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor &fullyConnectedDescriptor, const ConstTensor &weights, const ConstTensor &biases, const char *name=nullptr)
IConnectableLayer * AddPermuteLayer (const PermuteDescriptor &permuteDescriptor, const char *name=nullptr)
Adds a permute layer to the network.
IConnectableLayer * AddBatchToSpaceNdLayer (const BatchToSpaceNdDescriptor &batchToSpaceNdDescriptor, const char *name=nullptr)
Adds a batch to space ND layer to the network.
IConnectableLayer * AddPooling2dLayer (const Pooling2dDescriptor &pooling2dDescriptor, const char *name=nullptr)
Adds a pooling layer to the network.
IConnectableLayer * AddActivationLayer (const ActivationDescriptor &activationDescriptor, const char *name=nullptr)
Adds an activation layer to the network.
IConnectableLayer * AddNormalizationLayer (const NormalizationDescriptor &normalizationDescriptor, const char *name=nullptr)
Adds a normalization layer to the network.
IConnectableLayer * AddSliceLayer (const SliceDescriptor &sliceDescriptor, const char *name=nullptr)
Adds a slice layer to the network.
IConnectableLayer * AddSoftmaxLayer (const SoftmaxDescriptor &softmaxDescriptor, const char *name=nullptr)
Adds a softmax layer to the network.
IConnectableLayer * AddSplitterLayer (const ViewsDescriptor &splitterDescriptor, const char *name=nullptr)
Adds a splitter layer to the network.
IConnectableLayer * AddMergeLayer (const char *name=nullptr)
Adds a merge layer to the network.
IConnectableLayer * AddMergerLayer (const MergerDescriptor &mergerDescriptor, const char *name=nullptr)
Adds a concat layer to the network.
IConnectableLayer * AddAbsLayer (const char *name=nullptr)
Add absolute layer to the network.
IConnectableLayer * AddAdditionLayer (const char *name=nullptr)
Adds an addition layer to the network.
IConnectableLayer * AddMultiplicationLayer (const char *name=nullptr)
Adds a multiplication layer to the network.
IConnectableLayer * AddBatchNormalizationLayer (const BatchNormalizationDescriptor &desc, const ConstTensor &mean, const ConstTensor &variance, const ConstTensor &beta, const ConstTensor &gamma, const char *name=nullptr)
Adds a batch normalization layer to the network.
IConnectableLayer * AddRankLayer (const char *name=nullptr)
Adds a rank layer to the network.
IConnectableLayer * AddResizeBilinearLayer (const ResizeBilinearDescriptor &resizeDesc, const char *name=nullptr)
Adds a resize bilinear layer to the network.
IConnectableLayer * AddResizeLayer (const ResizeDescriptor &resizeDescriptor, const char *name=nullptr)
Adds a resize layer to the network.
IConnectableLayer * AddReduceLayer (const ReduceDescriptor &reduceDescriptor, const char *name=nullptr)
Adds a reduce layer to the network.
IConnectableLayer * AddInstanceNormalizationLayer (const InstanceNormalizationDescriptor &desc, const char *name=nullptr)
Adds an instance normalization layer to the network.
IConnectableLayer * AddL2NormalizationLayer (const L2NormalizationDescriptor &desc, const char *name=nullptr)
Adds an L2 normalization layer to the network.
IConnectableLayer * AddLogSoftmaxLayer (const LogSoftmaxDescriptor &logSoftmaxDescriptor, const char *name=nullptr)
Adds a log softmax layer to the network.
IConnectableLayer * AddConstantLayer (const ConstTensor &input, const char *name=nullptr)
Adds a layer with no inputs and a single output, which always corresponds to the passed in constant tensor.
IConnectableLayer * AddReshapeLayer (const ReshapeDescriptor &reshapeDescriptor, const char *name=nullptr)
Adds a reshape layer to the network.
IConnectableLayer * AddSpaceToBatchNdLayer (const SpaceToBatchNdDescriptor &spaceToBatchNdDescriptor, const char *name=nullptr)
Adds a space to batch layer to the network.
IConnectableLayer * AddSpaceToDepthLayer (const SpaceToDepthDescriptor &spaceToDepthDescriptor, const char *name=nullptr)
Adds a space to depth layer to the network.
IConnectableLayer * AddFloorLayer (const char *name=nullptr)
Adds a floor layer to the network.
IConnectableLayer * AddOutputLayer (LayerBindingId id, const char *name=nullptr)
Adds an output layer to the network.
IConnectableLayer * AddLstmLayer (const LstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr)
Add a Lstm layer to the network.
IConnectableLayer * AddDivisionLayer (const char *name=nullptr)
Adds a division layer to the network.
IConnectableLayer * AddSubtractionLayer (const char *name=nullptr)
Adds a subtraction layer to the network.
IConnectableLayer * AddMaximumLayer (const char *name=nullptr)
Add a Maximum layer to the network.
IConnectableLayer * AddMeanLayer (const MeanDescriptor &meanDescriptor, const char *name=nullptr)
Add a Mean layer to the network.
IConnectableLayer * AddPadLayer (const PadDescriptor &padDescriptor, const char *name=nullptr)
Adds a fully pad layer to the network.
IConnectableLayer * AddQuantizeLayer (const char *name=nullptr)
Add a quantize layer to the network.
IConnectableLayer * AddStridedSliceLayer (const StridedSliceDescriptor &stridedSliceDescriptor, const char *name=nullptr)
Adds a strided slice layer to the network.
IConnectableLayer * AddMinimumLayer (const char *name=nullptr)
Add a Minimum layer to the network.
IConnectableLayer * AddGreaterLayer (const char *name=nullptr)
Add a Greater layer to the network.
IConnectableLayer * AddEqualLayer (const char *name=nullptr)
Add a Equal layer to the network.
IConnectableLayer * AddRsqrtLayer (const char *name=nullptr)
Add Reciprocal of square root layer to the network.
IConnectableLayer * AddGatherLayer (const char *name=nullptr)
Add Gather layer to the network.
IConnectableLayer * AddGatherLayer (const GatherDescriptor &descriptor, const char *name=nullptr)
Add Gather layer to the network.
IConnectableLayer * AddSwitchLayer (const char *name=nullptr)
Adds a switch layer to the network.
IConnectableLayer * AddPreluLayer (const char *name=nullptr)
Adds a PReLU layer to the network.
IConnectableLayer * AddTransposeConvolution2dLayer (const TransposeConvolution2dDescriptor &descriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)
Adds a 2D transpose convolution layer to the network.
IConnectableLayer * AddTransposeLayer (const TransposeDescriptor &transposeDescriptor, const char *name=nullptr)
Adds a transpose layer to the network.
IConnectableLayer * AddStackLayer (const StackDescriptor &descriptor, const char *name=nullptr)
Adds a stack layer to the network.
IConnectableLayer * AddStandInLayer (const StandInDescriptor &descriptor, const char *name=nullptr)
Add a stand-in layer for a type unknown to the Arm NN framework.
IConnectableLayer * AddQuantizedLstmLayer (const QuantizedLstmInputParams &params, const char *name=nullptr)
Add a QuantizedLstm layer to the network.
IConnectableLayer * AddQLstmLayer (const QLstmDescriptor &descriptor, const LstmInputParams &params, const char *name=nullptr)
Add a QLstm layer to the network.
IConnectableLayer * AddLogicalBinaryLayer (const LogicalBinaryDescriptor &descriptor, const char *name=nullptr)
Adds a Logical Binary layer to the network.
void Accept (ILayerVisitor &visitor) const
void ExecuteStrategy (IStrategy &strategy) const
Static Public Member Functions
static INetwork * CreateRaw (NetworkOptions networkOptions={})
static INetworkPtr Create (NetworkOptions networkOptions={})
static void Destroy (INetwork *network)
Protected Member Functions
~INetwork ()
INetwork (NetworkOptions networkOptions={})
Protected Attributes
std::unique_ptr< NetworkImpl > pNetworkImpl
Friends
class NetworkQuantizer
class TestConnectionPreservation
void VisitLayersTopologically (const INetwork *inputNetwork, IStrategy &strategy)
TensorInfo GetInputTensorInfo (const INetwork *network)
IOptimizedNetworkPtr Optimize (const INetwork &network, const std::vector< BackendId > &backendPreferences, const IDeviceSpec &deviceSpec, const OptimizerOptions &options, Optional< std::vector< std::string > &> messages)
Create an optimized version of the network.
Detailed Description
Main network class which provides the interface for building up a neural network.
This object is subsequently required by the IRuntime::Load() method.
Definition at line 178 of file INetwork.hpp.
Constructor & Destructor Documentation
~INetwork()
~INetwork () protected default
Referenced by INetwork::INetwork().
INetwork()
INetwork (NetworkOptions networkOptions = {}) protected
Definition at line 41 of file Network.cpp.
References INetwork::~INetwork().
Referenced by INetwork::CreateRaw().
 : pNetworkImpl(new NetworkImpl(networkOptions)) {}
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const
Definition at line 495 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->Accept(visitor);
 }
AddAbsLayer()
IConnectableLayer * AddAbsLayer (const char * name = nullptr)
Add absolute layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 257 of file Network.cpp.
References armnn::Abs, and INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddElementwiseUnaryLayer(ElementwiseUnaryDescriptor(UnaryOperation::Abs), name);
 }
AddActivationLayer()
IConnectableLayer * AddActivationLayer (const ActivationDescriptor & activationDescriptor, const char * name = nullptr)
Adds an activation layer to the network.
Parameters
activationDescriptor - ActivationDescriptor to configure the activation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 218 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::CreateStartOfLeakyReluNetwork().
 {
     return pNetworkImpl->AddActivationLayer(activationDescriptor, name);
 }
AddAdditionLayer()
IConnectableLayer * AddAdditionLayer (const char * name = nullptr)
Adds an addition layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 262 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddAdditionLayer(name);
 }
AddArgMinMaxLayer()
IConnectableLayer * AddArgMinMaxLayer (const ArgMinMaxDescriptor & desc, const char * name = nullptr)
Adds an ArgMinMax layer to the network.
Parameters
desc - Parameters for the L2 normalization operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 56 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddArgMinMaxLayer(desc, name);
 }
AddBatchNormalizationLayer()
IConnectableLayer * AddBatchNormalizationLayer (const BatchNormalizationDescriptor & desc, const ConstTensor & mean, const ConstTensor & variance, const ConstTensor & beta, const ConstTensor & gamma, const char * name = nullptr)
Adds a batch normalization layer to the network.
Parameters
mean - Pre-calculated mean for each channel.
variance - Pre-calculated variance for each channel.
beta - Per-channel additive factor.
gamma - Per-channel multiplicative factor.
Returns
- Interface for configuring the layer.
Parameters
name - Optional name for the layer.
Definition at line 272 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddBatchNormalizationLayer(desc, mean, variance, beta, gamma, name);
 }
AddBatchToSpaceNdLayer()
IConnectableLayer * AddBatchToSpaceNdLayer (const BatchToSpaceNdDescriptor & batchToSpaceNdDescriptor, const char * name = nullptr)
Adds a batch to space ND layer to the network.
Parameters
batchToSpaceNdDescriptor - Description of the layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 206 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddBatchToSpaceNdLayer(batchToSpaceNdDescriptor, name);
 }
AddComparisonLayer()
IConnectableLayer * AddComparisonLayer (const ComparisonDescriptor & comparisonDescriptor, const char * name = nullptr)
Add a Comparison layer to the network.
Parameters
name - Optional name for the layer.
desc - Descriptor for the comparison operation.
Returns
- Interface for configuring the layer.
Definition at line 63 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddComparisonLayer(comparisonDescriptor, name);
 }
AddConcatLayer()
IConnectableLayer * AddConcatLayer (const ConcatDescriptor & concatDescriptor, const char * name = nullptr)
Adds a concatenation layer to the network.
Parameters
concatDescriptor - ConcatDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 70 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddConcatLayer(concatDescriptor, name);
 }
AddConstantLayer()
IConnectableLayer * AddConstantLayer (const ConstTensor & input, const char * name = nullptr)
Adds a layer with no inputs and a single output, which always corresponds to the passed in constant tensor.
Parameters
input - Tensor to be provided as the only output of the layer. The layer will maintain its own copy of the tensor data, meaning the memory referenced by input can be freed or reused after this function is called.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 331 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddConstantLayer(input, name);
 }
AddConvolution2dLayer() [1/3]
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr)
Adds a 2D convolution layer to the network.
Parameters
convolution2dDescriptor - Description of the 2D convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 77 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddConvolution2dLayer(convolution2dDescriptor, weights, biases, name);
 }
AddConvolution2dLayer() [2/3]
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const char * name = nullptr)
Definition at line 86 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     Optional<ConstTensor> biases;
     return pNetworkImpl->AddConvolution2dLayer(convolution2dDescriptor, weights, biases, name);
 }
AddConvolution2dLayer() [3/3]
IConnectableLayer * AddConvolution2dLayer (const Convolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const ConstTensor & biases, const char * name = nullptr)
Definition at line 95 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddConvolution2dLayer(convolution2dDescriptor,
                                                weights,
                                                armnn::Optional<ConstTensor>(biases),
                                                name);
 }
AddDepthToSpaceLayer()
IConnectableLayer * AddDepthToSpaceLayer (const DepthToSpaceDescriptor & depthToSpaceDescriptor, const char * name = nullptr)
Adds a depth to space layer to the network.
Parameters
depthToSpaceDescriptor - Parameters for the depth to space operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 108 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddDepthToSpaceLayer(depthToSpaceDescriptor, name);
 }
AddDepthwiseConvolution2dLayer() [1/3]
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr)
Adds a 2D depthwise convolution layer to the network.
Parameters
convolution2dDescriptor - Description of the 2D depthwise convolution layer.
weights - Tensor for the weights. Expected format: [channelMultiplier, inputChannels, height, width].
biases Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 115 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddDepthwiseConvolution2dLayer(convolution2dDescriptor, weights, biases, name);
 }
AddDepthwiseConvolution2dLayer() [2/3]
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const char * name = nullptr)
Definition at line 125 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     Optional<ConstTensor> biases;
     return pNetworkImpl->AddDepthwiseConvolution2dLayer(convolution2dDescriptor, weights, biases, name);
 }
AddDepthwiseConvolution2dLayer() [3/3]
IConnectableLayer * AddDepthwiseConvolution2dLayer (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const ConstTensor & biases, const char * name = nullptr)
Definition at line 135 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddDepthwiseConvolution2dLayer(convolution2dDescriptor, weights,
                                                         armnn::Optional<ConstTensor>(biases), name);
 }
AddDequantizeLayer()
IConnectableLayer * AddDequantizeLayer (const char * name = nullptr)
Adds a Dequantize layer to the network.
Returns
- Interface for configuring the layer.
Definition at line 146 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddDequantizeLayer(name);
 }
AddDetectionPostProcessLayer()
IConnectableLayer * AddDetectionPostProcessLayer (const DetectionPostProcessDescriptor & descriptor, const ConstTensor & anchors, const char * name = nullptr)
Adds a Detection PostProcess layer to the network.
Parameters
descriptor - Description of the Detection PostProcess layer.
anchors - Tensor for anchors.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 152 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddDetectionPostProcessLayer(descriptor, anchors, name);
 }
AddDivisionLayer()
IConnectableLayer * AddDivisionLayer (const char * name = nullptr)
Adds a division layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 371 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddDivisionLayer(name);
 }
AddElementwiseUnaryLayer()
IConnectableLayer * AddElementwiseUnaryLayer (const ElementwiseUnaryDescriptor & elementwiseUnaryDescriptor, const char * name = nullptr)
Add an ElementwiseUnary layer to the network.
Parameters
name - Optional name for the layer.
desc - Descriptor for the elementwiseUnary operation.
Returns
- Interface for configuring the layer.
Definition at line 161 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddElementwiseUnaryLayer(elementwiseUnaryDescriptor, name);
 }
AddEqualLayer()
IConnectableLayer * AddEqualLayer (const char * name = nullptr)
Add a Equal layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 418 of file Network.cpp.
References armnn::Equal, and INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddComparisonLayer(ComparisonDescriptor(ComparisonOperation::Equal), name);
 }
AddFillLayer()
IConnectableLayer * AddFillLayer (const FillDescriptor & fillDescriptor, const char * name = nullptr)
Add an Fill layer to the network.
Parameters
name - Optional name for the layer.
fillDescriptor - Descriptor for the fill operation.
Returns
- Interface for configuring the layer.
Definition at line 168 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddFillLayer(fillDescriptor, name);
 }
AddFloorLayer()
IConnectableLayer * AddFloorLayer (const char * name = nullptr)
Adds a floor layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 355 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddFloorLayer(name);
 }
AddFullyConnectedLayer() [1/3]
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr)
Adds a fully connected layer to the network.
Parameters
fullyConnectedDescriptor - Description of the fully connected layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 175 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddFullyConnectedLayer(fullyConnectedDescriptor, weights, biases, name);
 }
AddFullyConnectedLayer() [2/3]
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const char * name = nullptr)
Definition at line 183 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     Optional<ConstTensor> biases;
     return pNetworkImpl->AddFullyConnectedLayer(fullyConnectedDescriptor, weights, biases, name);
 }
AddFullyConnectedLayer() [3/3]
IConnectableLayer * AddFullyConnectedLayer (const FullyConnectedDescriptor & fullyConnectedDescriptor, const ConstTensor & weights, const ConstTensor & biases, const char * name = nullptr)
Definition at line 191 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddFullyConnectedLayer(fullyConnectedDescriptor, weights,
                                                 armnn::Optional<ConstTensor>(biases), name);
 }
AddGatherLayer() [1/2]
IConnectableLayer * AddGatherLayer (const char * name = nullptr)
Add Gather layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 428 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     GatherDescriptor gatherDescriptor{};
     return pNetworkImpl->AddGatherLayer(gatherDescriptor, name);
 }
AddGatherLayer() [2/2]
IConnectableLayer * AddGatherLayer (const GatherDescriptor & descriptor, const char * name = nullptr)
Add Gather layer to the network.
Parameters
descriptor - Description of the gather layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 434 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddGatherLayer(descriptor, name);
 }
AddGreaterLayer()
IConnectableLayer * AddGreaterLayer (const char * name = nullptr)
Add a Greater layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 413 of file Network.cpp.
References armnn::Greater, and INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddComparisonLayer(ComparisonDescriptor(ComparisonOperation::Greater), name);
 }
AddInputLayer()
IConnectableLayer * AddInputLayer (LayerBindingId id, const char * name = nullptr)
Adds an input layer to the network.
Parameters
id - User generated id to uniquely identify a particular input. The same id needs to be specified. when passing the inputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 50 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::CreateStartOfLeakyReluNetwork().
 {
     return pNetworkImpl->AddInputLayer(id, name);
 }
AddInstanceNormalizationLayer()
IConnectableLayer * AddInstanceNormalizationLayer (const InstanceNormalizationDescriptor & desc, const char * name = nullptr)
Adds an instance normalization layer to the network.
Parameters
desc - Parameters for the instance normalization operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 313 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddInstanceNormalizationLayer(desc, name);
 }
AddL2NormalizationLayer()
IConnectableLayer * AddL2NormalizationLayer (const L2NormalizationDescriptor & desc, const char * name = nullptr)
Adds an L2 normalization layer to the network.
Normalization is performed along dimension 1, but requires a 4d input.
Parameters
desc - Parameters for the L2 normalization operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 319 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddL2NormalizationLayer(desc, name);
 }
AddLogicalBinaryLayer()
IConnectableLayer * AddLogicalBinaryLayer (const LogicalBinaryDescriptor & descriptor, const char * name = nullptr)
Adds a Logical Binary layer to the network.
Parameters
descriptor - Description of the Logical Binary layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 489 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddLogicalBinaryLayer(descriptor, name);
 }
AddLogSoftmaxLayer()
IConnectableLayer * AddLogSoftmaxLayer (const LogSoftmaxDescriptor & logSoftmaxDescriptor, const char * name = nullptr)
Adds a log softmax layer to the network.
Parameters
logSoftmaxDescriptor - LogSoftmaxDescriptor to configure the log softmax.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 325 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddLogSoftmaxLayer(logSoftmaxDescriptor, name);
 }
AddLstmLayer()
IConnectableLayer * AddLstmLayer (const LstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr)
Add a Lstm layer to the network.
Parameters
descriptor - Parameters for the Lstm operation
params - Weights and biases for the LSTM cell
name - Optional name for the layer
Returns
- Interface for configuring the layer.
Definition at line 364 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddLstmLayer(descriptor, params, name);
 }
AddMaximumLayer()
IConnectableLayer * AddMaximumLayer (const char * name = nullptr)
Add a Maximum layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 381 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddMaximumLayer(name);
 }
AddMeanLayer()
IConnectableLayer * AddMeanLayer (const MeanDescriptor & meanDescriptor, const char * name = nullptr)
Add a Mean layer to the network.
Parameters
meanDescriptor - Parameters for the mean operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 386 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddMeanLayer(meanDescriptor, name);
 }
AddMergeLayer()
IConnectableLayer * AddMergeLayer (const char * name = nullptr)
Adds a merge layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 246 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddMergeLayer(name);
 }
AddMergerLayer()
IConnectableLayer * AddMergerLayer (const MergerDescriptor & mergerDescriptor, const char * name = nullptr)
Adds a concat layer to the network.
Parameters
mergerDescriptor - MergerDescriptor (synonym for OriginsDescriptor) to configure the concatenation process. Number of Views must be equal to the number of inputs, and their order must match - e.g. first view corresponds to the first input, second view to the second input, etc....
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 251 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddConcatLayer(mergerDescriptor, name);
 }
AddMinimumLayer()
IConnectableLayer * AddMinimumLayer (const char * name = nullptr)
Add a Minimum layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 408 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddMinimumLayer(name);
 }
AddMultiplicationLayer()
IConnectableLayer * AddMultiplicationLayer (const char * name = nullptr)
Adds a multiplication layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 267 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddMultiplicationLayer(name);
 }
AddNormalizationLayer()
IConnectableLayer * AddNormalizationLayer (const NormalizationDescriptor & normalizationDescriptor, const char * name = nullptr)
Adds a normalization layer to the network.
Parameters
normalizationDescriptor - NormalizationDescriptor to configure the normalization.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 224 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddNormalizationLayer(normalizationDescriptor, name);
 }
AddOutputLayer()
IConnectableLayer * AddOutputLayer (LayerBindingId id, const char * name = nullptr)
Adds an output layer to the network.
Parameters
id - User generated id to uniquely identify a particular output. The same id needs to be specified when passing the outputs to the IRuntime::EnqueueWorkload() function.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 359 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::CompleteLeakyReluNetwork().
 {
     return pNetworkImpl->AddOutputLayer(id, name);
 }
AddPadLayer()
IConnectableLayer * AddPadLayer (const PadDescriptor & padDescriptor, const char * name = nullptr)
Adds a fully pad layer to the network.
Parameters
paddings - n by 2 tensor, where n is the rank of the input tensor, such that paddings[i,0] indicates the amount of padding to add in front of dimonsion i, and paddings[i,1] indicates the amount of padding to add after the end of dimension i
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 391 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddPadLayer(padDescriptor, name);
 }
AddPermuteLayer()
IConnectableLayer * AddPermuteLayer (const PermuteDescriptor & permuteDescriptor, const char * name = nullptr)
Adds a permute layer to the network.
Parameters
permuteDescriptor - PermuteDescriptor to configure the permute.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 200 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddPermuteLayer(permuteDescriptor, name);
 }
AddPooling2dLayer()
IConnectableLayer * AddPooling2dLayer (const Pooling2dDescriptor & pooling2dDescriptor, const char * name = nullptr)
Adds a pooling layer to the network.
Parameters
pooling2dDescriptor - Pooling2dDescriptor to configure the pooling.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 212 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddPooling2dLayer(pooling2dDescriptor, name);
 }
AddPreluLayer()
IConnectableLayer * AddPreluLayer (const char * name = nullptr)
Adds a PReLU layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 445 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddPreluLayer(name);
 }
AddQLstmLayer()
IConnectableLayer * AddQLstmLayer (const QLstmDescriptor & descriptor, const LstmInputParams & params, const char * name = nullptr)
Add a QLstm layer to the network.
Parameters
descriptor - Parameters for the QLstm operation
params - Weights and biases for the layer
name - Optional name for the layer
Returns
- Interface for configuring the layer.
Definition at line 482 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddQLstmLayer(descriptor, params, name);
 }
AddQuantizedLstmLayer()
IConnectableLayer * AddQuantizedLstmLayer (const QuantizedLstmInputParams & params, const char * name = nullptr)
Add a QuantizedLstm layer to the network.
Parameters
params - The weights and biases for the Quantized LSTM cell
name - Optional name for the layer
Returns
- Interface for configuring the layer.
Definition at line 476 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddQuantizedLstmLayer(params, name);
 }
AddQuantizeLayer()
IConnectableLayer * AddQuantizeLayer (const char * name = nullptr)
Add a quantize layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 397 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddQuantizeLayer(name);
 }
AddRankLayer()
IConnectableLayer * AddRankLayer (const char * name = nullptr)
Adds a rank layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 282 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddRankLayer(name);
 }
AddReduceLayer()
IConnectableLayer * AddReduceLayer (const ReduceDescriptor & reduceDescriptor, const char * name = nullptr)
Adds a reduce layer to the network.
Parameters
ReduceDescriptor - Parameters for the reduce operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 307 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddReduceLayer(reduceDescriptor, name);
 }
AddReshapeLayer()
IConnectableLayer * AddReshapeLayer (const ReshapeDescriptor & reshapeDescriptor, const char * name = nullptr)
Adds a reshape layer to the network.
Parameters
reshapeDescriptor - Parameters for the reshape operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 337 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by ITfParser::GetNetworkOutputBindingInfo().
 {
     return pNetworkImpl->AddReshapeLayer(reshapeDescriptor, name);
 }
AddResizeBilinearLayer()
IConnectableLayer * AddResizeBilinearLayer (const ResizeBilinearDescriptor & resizeDesc, const char * name = nullptr)
Adds a resize bilinear layer to the network.
Parameters
resizeDesc - Parameters for the resize operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 287 of file Network.cpp.
References armnn::Bilinear, ResizeBilinearDescriptor::m_AlignCorners, ResizeDescriptor::m_AlignCorners, ResizeBilinearDescriptor::m_DataLayout, ResizeDescriptor::m_DataLayout, ResizeBilinearDescriptor::m_HalfPixelCenters, ResizeDescriptor::m_HalfPixelCenters, ResizeDescriptor::m_Method, ResizeBilinearDescriptor::m_TargetHeight, ResizeDescriptor::m_TargetHeight, ResizeBilinearDescriptor::m_TargetWidth, ResizeDescriptor::m_TargetWidth, and INetwork::pNetworkImpl.
 {
     ResizeDescriptor resizeDescriptor;
     resizeDescriptor.m_Method           = ResizeMethod::Bilinear;
     resizeDescriptor.m_DataLayout       = descriptor.m_DataLayout;
     resizeDescriptor.m_TargetWidth      = descriptor.m_TargetWidth;
     resizeDescriptor.m_TargetHeight     = descriptor.m_TargetHeight;
     resizeDescriptor.m_AlignCorners     = descriptor.m_AlignCorners;
     resizeDescriptor.m_HalfPixelCenters = descriptor.m_HalfPixelCenters;
     return pNetworkImpl->AddResizeLayer(resizeDescriptor, name);
 }
AddResizeLayer()
IConnectableLayer * AddResizeLayer (const ResizeDescriptor & resizeDescriptor, const char * name = nullptr)
Adds a resize layer to the network.
Parameters
resizeDescriptor - Parameters for the resize operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 301 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddResizeLayer(resizeDescriptor, name);
 }
AddRsqrtLayer()
IConnectableLayer * AddRsqrtLayer (const char * name = nullptr)
Add Reciprocal of square root layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 423 of file Network.cpp.
References INetwork::pNetworkImpl, and armnn::Rsqrt.
 {
     return pNetworkImpl->AddElementwiseUnaryLayer(ElementwiseUnaryDescriptor(UnaryOperation::Rsqrt), name);
 }
AddSliceLayer()
IConnectableLayer * AddSliceLayer (const SliceDescriptor & sliceDescriptor, const char * name = nullptr)
Adds a slice layer to the network.
Parameters
sliceDescriptor - SliceDescriptor to configure the slice operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 230 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddSliceLayer(sliceDescriptor, name);
 }
AddSoftmaxLayer()
IConnectableLayer * AddSoftmaxLayer (const SoftmaxDescriptor & softmaxDescriptor, const char * name = nullptr)
Adds a softmax layer to the network.
If the data type is QAsymm8, then the output quantization parameters must have a scale of 1/256 and an offset of 0
Parameters
softmaxDescriptor - SoftmaxDescriptor to configure the softmax.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 234 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddSoftmaxLayer(softmaxDescriptor, name);
 }
AddSpaceToBatchNdLayer()
IConnectableLayer * AddSpaceToBatchNdLayer (const SpaceToBatchNdDescriptor & spaceToBatchNdDescriptor, const char * name = nullptr)
Adds a space to batch layer to the network.
Parameters
spaceToBatchNdDescriptor - Parameters for the space to batch operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 343 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddSpaceToBatchNdLayer(spaceToBatchNdDescriptor, name);
 }
AddSpaceToDepthLayer()
IConnectableLayer * AddSpaceToDepthLayer (const SpaceToDepthDescriptor & spaceToDepthDescriptor, const char * name = nullptr)
Adds a space to depth layer to the network.
Parameters
spaceToDepthDescriptor - Parameters for the space to depth operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 349 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddSpaceToDepthLayer(spaceToDepthDescriptor, name);
 }
AddSplitterLayer()
IConnectableLayer * AddSplitterLayer (const ViewsDescriptor & splitterDescriptor, const char * name = nullptr)
Adds a splitter layer to the network.
Parameters
splitterDescriptor - ViewsDescriptor to configure the splitting process. Number of Views must be equal to the number of outputs, and their order must match - e.g. first view corresponds to the first output, second view to the second output, etc....
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 240 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddSplitterLayer(splitterDescriptor, name);
 }
AddStackLayer()
IConnectableLayer * AddStackLayer (const StackDescriptor & descriptor, const char * name = nullptr)
Adds a stack layer to the network.
Parameters
descriptor - Description of the stack layer.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 464 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddStackLayer(descriptor, name);
 }
AddStandInLayer()
IConnectableLayer * AddStandInLayer (const StandInDescriptor & descriptor, const char * name = nullptr)
Add a stand-in layer for a type unknown to the Arm NN framework.
Note: Due to the nature of this layer, no validation can be performed by the framework. Furthermore, Any model containing this layer cannot make use of dynamic tensors since the tensor sizes cannot be inferred. - Descriptor for the StandIn layer.
Returns
- Interface for configuring the layer.
Definition at line 470 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddStandInLayer(descriptor, name);
 }
AddStridedSliceLayer()
IConnectableLayer * AddStridedSliceLayer (const StridedSliceDescriptor & stridedSliceDescriptor, const char * name = nullptr)
Adds a strided slice layer to the network.
Parameters
StridedSliceDescriptor - Parameters for the strided slice operation.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 402 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddStridedSliceLayer(stridedSliceDescriptor, name);
 }
AddSubtractionLayer()
IConnectableLayer * AddSubtractionLayer (const char * name = nullptr)
Adds a subtraction layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 376 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by armnn::GetVector().
 {
     return pNetworkImpl->AddSubtractionLayer(name);
 }
AddSwitchLayer()
IConnectableLayer * AddSwitchLayer (const char * name = nullptr)
Adds a switch layer to the network.
Parameters
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 440 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddSwitchLayer(name);
 }
AddTransposeConvolution2dLayer()
IConnectableLayer * AddTransposeConvolution2dLayer (const TransposeConvolution2dDescriptor & descriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr)
Adds a 2D transpose convolution layer to the network.
Parameters
descriptor - Description of the 2D transpose convolution layer.
weights - Tensor for the weights data.
biases - Optional tensor for the bias data.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 450 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddTransposeConvolution2dLayer(descriptor, weights, biases, name);
 }
AddTransposeLayer()
IConnectableLayer * AddTransposeLayer (const TransposeDescriptor & transposeDescriptor, const char * name = nullptr)
Adds a transpose layer to the network.
Parameters
transposeDescriptor - TransposeDescriptor to configure the transpose.
name - Optional name for the layer.
Returns
- Interface for configuring the layer.
Definition at line 458 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->AddTransposeLayer(transposeDescriptor, name);
 }
Create()
armnn::INetworkPtr Create (NetworkOptions networkOptions = {}) static
Definition at line 510 of file Network.cpp.
References INetwork::CreateRaw(), and INetwork::Destroy().
Referenced by BOOST_AUTO_TEST_CASE(), armnn::BOOST_AUTO_TEST_CASE(), RecordByRecordCaffeParser::CreateNetworkFromBinaryFile(), ICaffeParser::CaffeParserImpl::CreateNetworkFromNetParameter(), armnn::CreateNetworkWithActivationLayer(), armnn::CreateNetworkWithArgMinMaxLayer(), armnn::CreateNetworkWithFullyConnectedLayer(), armnn::CreateNetworkWithInputOutputLayers(), armnn::CreateNetworkWithSoftmaxLayer(), CreatNetwork(), armnn::CreatNetwork(), GetSoftmaxProfilerJson(), armnn::PreserveTypeTestImpl(), QLstmEndToEnd(), armnn::TestQuantizeConvolution2d(), armnn::TestQuantizeDepthwiseConvolution2d(), armnn::TestQuantizeTransposeConvolution2d(), and VerifyPostOptimisationStructureTestImpl().
 {
     return INetworkPtr(CreateRaw(networkOptions), &INetwork::Destroy);
 }
CreateRaw()
armnn::INetwork * CreateRaw (NetworkOptions networkOptions = {}) static
Definition at line 505 of file Network.cpp.
References INetwork::INetwork().
Referenced by INetwork::Create().
 {
     return new INetwork(networkOptions);
 }
Destroy()
void Destroy (INetwork * network) static
Definition at line 515 of file Network.cpp.
Referenced by INetwork::Create().
 {
     delete network;
 }
ExecuteStrategy()
void ExecuteStrategy (IStrategy & strategy) const
Definition at line 500 of file Network.cpp.
References INetwork::pNetworkImpl.
Referenced by ISerializer::SerializerImpl::Serialize().
 {
     return pNetworkImpl->ExecuteStrategy(strategy);
 }
PrintGraph()
Status PrintGraph ()
Definition at line 45 of file Network.cpp.
References INetwork::pNetworkImpl.
 {
     return pNetworkImpl->PrintGraph();
 }
Friends And Related Function Documentation
GetInputTensorInfo
TensorInfo GetInputTensorInfo (const INetwork * network) friend
Definition at line 80 of file QuantizerTest.cpp.
 {
     for (auto&& inputLayer : network->pNetworkImpl->GetGraph().GetInputLayers())
     {
         ARMNN_ASSERT_MSG(inputLayer->GetNumOutputSlots() == 1, "Input layer should have exactly 1 output slot");
         return inputLayer->GetOutputSlot(0).GetTensorInfo();
     }
     throw InvalidArgumentException("Network has no input layers");
 }
NetworkQuantizer
friend class NetworkQuantizer friend
Definition at line 681 of file INetwork.hpp.
Optimize
IOptimizedNetworkPtr Optimize (const INetwork & network, const std::vector< BackendId > & backendPreferences, const IDeviceSpec & deviceSpec, const OptimizerOptions & options = OptimizerOptions(), Optional< std::vector< std::string > &> messages = EmptyOptional()) friend
Create an optimized version of the network.
Parameters
network INetwork description of the network to be optimized.
backendPreferences The choice of the backend ordered by user preferences.
deviceSpec DeviceSpec object as queried from the runtime. See IRuntime::GetDeviceSpec()
messages If there are failures or warnings a string describing same will be added to the vector
options OptimizerOptions object with optimizer configuration options
Returns
An IOptimizedNetworkPtr interface to the optimized network, throws an exception derived from armnn::Exception if process fails.
Definition at line 1502 of file Network.cpp.
 {
     if (backendPreferences.empty())
     {
         throw InvalidArgumentException("Invoked Optimize with no backends specified");
     }
     if (options.m_ReduceFp32ToFp16 && options.m_ReduceFp32ToBf16)
     {
         throw InvalidArgumentException("BFloat16 and Float16 optimization cannot be enabled at the same time.");
     }
     std::unique_ptr<Graph> graph = std::make_unique<Graph>(inNetwork.pNetworkImpl->GetGraph());
     auto optNet = IOptimizedNetworkPtr(new IOptimizedNetwork(std::move(graph), options.m_ModelOptions),
                                        &IOptimizedNetwork::Destroy);
     IOptimizedNetwork* optNetObjPtr = optNet.get();
     // Get the optimized graph
     Graph& optGraph = optNetObjPtr->pOptimizedNetworkImpl->GetGraph();
     // Perform AddBroadcastReshapeLayer optimisation
     using namespace optimizations;
     Optimizer::Pass(optGraph, MakeOptimizations(AddBroadcastReshapeLayer()));
     // Infer the tensor infos for all output slots. Throws an exception on failure
     optGraph.InferTensorInfos();
     // Perform optimisation passes
     Optimizer::Pass(optGraph, MakeOptimizations(SquashEqualPermuteSiblings(),
                                                 SquashEqualTransposeSiblings(),
                                                 SquashEqualReshapeSiblings(),
                                                 OptimizeInversePermutes(),
                                                 OptimizeInverseTransposes(),
                                                 MovePermuteUp(),
                                                 MoveTransposeUp(),
                                                 PermuteAsReshape(),
                                                 TransposeAsReshape(),
                                                 OptimizeConsecutiveReshapes(),
                                                 FoldPadIntoConvolution2d(),
                                                 PermuteAndBatchToSpaceAsDepthToSpace(),
                                                 TransposeAndBatchToSpaceAsDepthToSpace(),
                                                 FuseBatchNormIntoConvolution2DFloat32(),
                                                 FuseBatchNormIntoConvolution2DFloat16(),
                                                 FuseBatchNormIntoDepthwiseConvolution2DFloat32(),
                                                 FuseBatchNormIntoDepthwiseConvolution2DFloat16()));
     // If Fp32 to Fp16 optimization is set convert Fp32 network to Fp16
     if (options.m_ReduceFp32ToFp16)
     {
         Optimizer::Pass(optGraph, MakeOptimizations(Fp32NetworkToFp16Converter()));
         Optimizer::Pass(optGraph, MakeOptimizations(ConvertConstantsFloatToHalf()));
     }
     // If Fp32 to Bf16 optimization is set convert Fp32 network to Bf16
     // Convert input of Convolution2d and FullyConnected from Fp32 to Bf16
     // Only Constant weight of Convolution2d and FullyConnected are converted from Fp32 to Bf16
     if (options.m_ReduceFp32ToBf16)
     {
         Optimizer::Pass(optGraph, MakeOptimizations(Fp32NetworkToBf16Converter()));
     }
     // Initialize backend settings
     BackendSettings backendSettings(backendPreferences, deviceSpec);
     if (backendSettings.GetAvailablePreferredBackends().empty())
     {
         std::stringstream failureMsg;
         failureMsg << "None of the preferred backends " << backendPreferences
                    << " are supported. Current platform provides " << backendSettings.m_SupportedBackends;
         ReportError(failureMsg.str(), messages);
         throw InvalidArgumentException(failureMsg.str());
     }
     // Create a map to temporarily hold initialized backend objects
     TensorHandleFactoryRegistry tensorHandleFactoryRegistry;
     BackendsMap backends = CreateSupportedBackends(tensorHandleFactoryRegistry, backendSettings);
     // Assign an available backend to each layer
     Graph::Iterator firstLayer = optGraph.begin();
     Graph::Iterator lastLayer  = optGraph.end();
     OptimizationResult assignBackendsResult = AssignBackends(optNetObjPtr->pOptimizedNetworkImpl.get(),
                                                              backendSettings,
                                                              firstLayer,
                                                              lastLayer,
                                                              messages);
     if (assignBackendsResult.m_Error)
     {
         // Failed to assign a backend to each layer
         throw InvalidArgumentException("Failed to assign a backend to each layer");
     }
     Optimizer::Pass(optGraph, MakeOptimizations(OptimizeInverseConversionsFp16(),
                                                 OptimizeInverseConversionsFp32()));
     // Apply the backend-specific optimizations
     OptimizationResult backendOptimizationResult = ApplyBackendOptimizations(optNetObjPtr->pOptimizedNetworkImpl.get(),
                                                                              backendSettings,
                                                                              backends,
                                                                              options.m_ModelOptions,
                                                                              messages);
     if (backendOptimizationResult.m_Error)
     {
         // Failed to apply the backend-specific optimizations
         throw InvalidArgumentException("Failed to apply the backend-specific optimizations");
     }
     // If the debug flag is set, then insert a DebugLayer after each layer
     // Doing this after applying the backend optimizations as they might have changed some layers
     if (options.m_Debug)
     {
         Optimizer::Pass(optGraph, MakeOptimizations(InsertDebugLayer()));
     }
     // Calculate the compatibility strategies for tensor handles
     OptimizationResult strategyResult = SelectTensorHandleStrategy(optGraph,
                                                                    backends,
                                                                    tensorHandleFactoryRegistry,
                                                                    options.m_ImportEnabled,
                                                                    messages);
     if (strategyResult.m_Error)
     {
         // Failed to apply the backend-specific optimizations
         return IOptimizedNetworkPtr(nullptr, &IOptimizedNetwork::Destroy);
     }
     // Based on the tensor handle strategy determined above, insert copy layers where required.
     optGraph.AddCompatibilityLayers(backends, tensorHandleFactoryRegistry);
     // Convert constants
     Optimizer::Pass(optGraph, MakeOptimizations(ConvertConstantsFloatToHalf()));
     Optimizer::Pass(optGraph, MakeOptimizations(ConvertConstantsHalfToFloat()));
     // Run backend specific optimizations (deprecated)
     for (auto&& chosenBackend : backendSettings.m_SelectedBackends)
     {
         auto factoryFun = BackendRegistryInstance().GetFactory(chosenBackend);
         auto backendPtr = factoryFun();
         ARMNN_ASSERT(backendPtr.get() != nullptr);
         ARMNN_NO_DEPRECATE_WARN_BEGIN
         auto backendSpecificOptimizations = backendPtr->GetOptimizations();
         ARMNN_NO_DEPRECATE_WARN_END
         if (!backendSpecificOptimizations.empty())
         {
             Optimizer::Pass(optNetObjPtr->pOptimizedNetworkImpl->GetGraph(), backendSpecificOptimizations);
         }
     }
     return optNet;
 }
TestConnectionPreservation
friend class TestConnectionPreservation friend
Definition at line 683 of file INetwork.hpp.
VisitLayersTopologically
void VisitLayersTopologically (const INetwork * inputNetwork, IStrategy & strategy) friend
Definition at line 73 of file QuantizerTest.cpp.
 {
     auto graph = inputNetwork->pNetworkImpl->GetGraph().TopologicalSort();
     ApplyStrategyToLayers(graph, visitor);
 }
Member Data Documentation
pNetworkImpl
std::unique_ptr<NetworkImpl> pNetworkImpl protected
Definition at line 693 of file INetwork.hpp.
Referenced by INetwork::Accept(), INetwork::AddAbsLayer(), INetwork::AddActivationLayer(), INetwork::AddAdditionLayer(), INetwork::AddArgMinMaxLayer(), INetwork::AddBatchNormalizationLayer(), INetwork::AddBatchToSpaceNdLayer(), INetwork::AddComparisonLayer(), INetwork::AddConcatLayer(), INetwork::AddConstantLayer(), INetwork::AddConvolution2dLayer(), INetwork::AddDepthToSpaceLayer(), INetwork::AddDepthwiseConvolution2dLayer(), INetwork::AddDequantizeLayer(), INetwork::AddDetectionPostProcessLayer(), INetwork::AddDivisionLayer(), INetwork::AddElementwiseUnaryLayer(), INetwork::AddEqualLayer(), INetwork::AddFillLayer(), INetwork::AddFloorLayer(), INetwork::AddFullyConnectedLayer(), INetwork::AddGatherLayer(), INetwork::AddGreaterLayer(), INetwork::AddInputLayer(), INetwork::AddInstanceNormalizationLayer(), INetwork::AddL2NormalizationLayer(), INetwork::AddLogicalBinaryLayer(), INetwork::AddLogSoftmaxLayer(), INetwork::AddLstmLayer(), INetwork::AddMaximumLayer(), INetwork::AddMeanLayer(), INetwork::AddMergeLayer(), INetwork::AddMergerLayer(), INetwork::AddMinimumLayer(), INetwork::AddMultiplicationLayer(), INetwork::AddNormalizationLayer(), INetwork::AddOutputLayer(), INetwork::AddPadLayer(), INetwork::AddPermuteLayer(), INetwork::AddPooling2dLayer(), INetwork::AddPreluLayer(), INetwork::AddQLstmLayer(), INetwork::AddQuantizedLstmLayer(), INetwork::AddQuantizeLayer(), INetwork::AddRankLayer(), INetwork::AddReduceLayer(), INetwork::AddReshapeLayer(), INetwork::AddResizeBilinearLayer(), INetwork::AddResizeLayer(), INetwork::AddRsqrtLayer(), INetwork::AddSliceLayer(), INetwork::AddSoftmaxLayer(), INetwork::AddSpaceToBatchNdLayer(), INetwork::AddSpaceToDepthLayer(), INetwork::AddSplitterLayer(), INetwork::AddStackLayer(), INetwork::AddStandInLayer(), INetwork::AddStridedSliceLayer(), INetwork::AddSubtractionLayer(), INetwork::AddSwitchLayer(), INetwork::AddTransposeConvolution2dLayer(), INetwork::AddTransposeLayer(), INetwork::ExecuteStrategy(), armnn::GetInputTensorInfo(), armnn::Optimize(), INetwork::PrintGraph(), and armnn::VisitLayersTopologically().
The documentation for this class was generated from the following files:
include/armnn/INetwork.hpp
src/armnn/Network.cpp