ArmNN: IInferenceTestCaseProvider Class Reference
IInferenceTestCaseProvider Class Reference abstract
#include <InferenceTest.hpp>
Public Member Functions
virtual ~IInferenceTestCaseProvider ()
virtual void AddCommandLineOptions (cxxopts::Options &options, std::vector< std::string > &required)
virtual bool ProcessCommandLineOptions (const InferenceTestOptions &commonOptions)
virtual std::unique_ptr< IInferenceTestCase > GetTestCase (unsigned int testCaseId)=0
virtual bool OnInferenceTestFinished ()
Detailed Description
Definition at line 91 of file InferenceTest.hpp.
Constructor & Destructor Documentation
~IInferenceTestCaseProvider()
virtual ~IInferenceTestCaseProvider () inline virtual
Definition at line 94 of file InferenceTest.hpp.
 {}
Member Function Documentation
AddCommandLineOptions()
virtual void AddCommandLineOptions (cxxopts::Options & options, std::vector< std::string > & required) inline virtual
Reimplemented in YoloTestCaseProvider< Model >, and ClassifierTestCaseProvider< TDatabase, InferenceModel >.
Definition at line 96 of file InferenceTest.hpp.
References armnn::IgnoreUnused().
Referenced by armnn::test::ParseCommandLine().
     {
         IgnoreUnused(options, required);
     };
GetTestCase()
virtual std::unique_ptr<IInferenceTestCase> GetTestCase (unsigned int testCaseId) pure virtual
Implemented in YoloTestCaseProvider< Model >, and ClassifierTestCaseProvider< TDatabase, InferenceModel >.
Referenced by armnn::test::InferenceTest().
OnInferenceTestFinished()
virtual bool OnInferenceTestFinished () inline virtual
Reimplemented in ClassifierTestCaseProvider< TDatabase, InferenceModel >.
Definition at line 106 of file InferenceTest.hpp.
Referenced by armnn::test::InferenceTest().
 { return true; };
ProcessCommandLineOptions()
virtual bool ProcessCommandLineOptions (const InferenceTestOptions & commonOptions) inline virtual
Reimplemented in YoloTestCaseProvider< Model >, and ClassifierTestCaseProvider< TDatabase, InferenceModel >.
Definition at line 100 of file InferenceTest.hpp.
References armnn::IgnoreUnused().
Referenced by armnn::test::ParseCommandLine().
     {
         IgnoreUnused(commonOptions);
         return true;
     };
The documentation for this class was generated from the following file:
tests/InferenceTest.hpp