ArmNN: ICaffeParser Class Reference
ICaffeParser Class Reference
#include <ICaffeParser.hpp>
Classes
class CaffeParserImpl
Public Member Functions
armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Create the network from a protobuf text file on the disk.
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Create the network from a protobuf binary file on the disk.
armnn::INetworkPtr CreateNetworkFromString (const char *protoText, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Create the network directly from protobuf text in a string. Useful for debugging/testin.g.
BindingPointInfo GetNetworkInputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
BindingPointInfo GetNetworkOutputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Static Public Member Functions
static ICaffeParser * CreateRaw ()
static ICaffeParserPtr Create ()
static void Destroy (ICaffeParser *parser)
Friends
class CaffeParser
class RecordByRecordCaffeParser
Detailed Description
Definition at line 24 of file ICaffeParser.hpp.
Member Function Documentation
Create()
ICaffeParserPtr Create () static
Definition at line 75 of file CaffeParser.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and main().
 {
     return ICaffeParserPtr(CreateRaw(), &ICaffeParser::Destroy);
 }
CreateNetworkFromBinaryFile()
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Create the network from a protobuf binary file on the disk.
Definition at line 93 of file CaffeParser.cpp.
 {
     return pCaffeParserImpl->CreateNetworkFromBinaryFile(graphFile, inputShapes,requestedOutputs);
 }
CreateNetworkFromString()
armnn::INetworkPtr CreateNetworkFromString (const char * protoText, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Create the network directly from protobuf text in a string. Useful for debugging/testin.g.
Definition at line 101 of file CaffeParser.cpp.
 {
     return pCaffeParserImpl->CreateNetworkFromString(protoText, inputShapes, requestedOutputs);
 }
CreateNetworkFromTextFile()
armnn::INetworkPtr CreateNetworkFromTextFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Create the network from a protobuf text file on the disk.
Definition at line 85 of file CaffeParser.cpp.
References ICaffeParser::CreateNetworkFromTextFile().
Referenced by ICaffeParser::CreateNetworkFromTextFile().
 {
     return pCaffeParserImpl->CreateNetworkFromTextFile(graphFile, inputShapes, requestedOutputs);
 }
CreateRaw()
ICaffeParser * CreateRaw () static
Definition at line 70 of file CaffeParser.cpp.
 {
     return new ICaffeParser();
 }
Destroy()
void Destroy (ICaffeParser * parser) static
Definition at line 80 of file CaffeParser.cpp.
 {
     delete parser;
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Definition at line 109 of file CaffeParser.cpp.
 {
     return pCaffeParserImpl->GetNetworkInputBindingInfo(name);
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Definition at line 114 of file CaffeParser.cpp.
References CHECK_LOCATION, and armnn::numeric_cast().
 {
     return pCaffeParserImpl->GetNetworkOutputBindingInfo(name);
 }
Friends And Related Function Documentation
CaffeParser
friend class CaffeParser friend
Definition at line 56 of file ICaffeParser.hpp.
RecordByRecordCaffeParser
friend class RecordByRecordCaffeParser friend
Definition at line 57 of file ICaffeParser.hpp.
The documentation for this class was generated from the following files:
include/armnnCaffeParser/ICaffeParser.hpp
src/armnnCaffeParser/CaffeParser.cpp