ArmNN: ClContextControl Class Reference
ClContextControl Class Reference
#include <ClContextControl.hpp>
Public Member Functions
ClContextControl (arm_compute::CLTuner *=nullptr, arm_compute::CLGEMMHeuristicsHandle *=nullptr, bool profilingEnabled=false)
virtual ~ClContextControl ()
void LoadOpenClRuntime ()
void UnloadOpenClRuntime ()
void ClearClCache ()
Detailed Description
Definition at line 16 of file ClContextControl.hpp.
Constructor & Destructor Documentation
ClContextControl()
ClContextControl (arm_compute::CLTuner * tuner = nullptr, arm_compute::CLGEMMHeuristicsHandle * heuristicsHandle = nullptr, bool profilingEnabled = false)
Definition at line 30 of file ClContextControl.cpp.
References ARMNN_ASSERT, armnn::Error, armnn::IgnoreUnused(), and ClContextControl::LoadOpenClRuntime().
     : m_Tuner(tuner)
     , m_HeuristicsHandle(heuristicsHandle)
     , m_ProfilingEnabled(profilingEnabled)
 {
     // Ignore m_ProfilingEnabled if unused to avoid compiling problems when ArmCompute is disabled.
     IgnoreUnused(m_ProfilingEnabled);
     try
     {
         std::vector<cl::Platform> platforms;
         cl::Platform::get(&platforms);
         // Selects default platform for the first element.
         cl::Platform::setDefault(platforms[0]);
         std::vector<cl::Device> devices;
         platforms[0].getDevices(CL_DEVICE_TYPE_GPU, &devices);
         // Selects default device for the first element.
         cl::Device::setDefault(devices[0]);
     }
     catch (const cl::Error& clError)
     {
         throw ClRuntimeUnavailableException(fmt::format(
             "Could not initialize the CL runtime. Error description: {0}. CL error code: {1}",
             clError.what(), clError.err()));
     }
     // Removes the use of global CL context.
     cl::Context::setDefault(cl::Context{});
     ARMNN_ASSERT(cl::Context::getDefault()() == NULL);
     // Removes the use of global CL command queue.
     cl::CommandQueue::setDefault(cl::CommandQueue{});
     ARMNN_ASSERT(cl::CommandQueue::getDefault()() == NULL);
     // Always load the OpenCL runtime.
     LoadOpenClRuntime();
 }
~ClContextControl()
~ClContextControl () virtual
Definition at line 73 of file ClContextControl.cpp.
References armnn::Error, and ClContextControl::UnloadOpenClRuntime().
 {
     // Load the OpencCL runtime without the tuned parameters to free the memory for them.
     try
     {
         UnloadOpenClRuntime();
     }
     catch (const cl::Error& clError)
     {
         // This should not happen, it is ignored if it does.
         // Coverity fix: BOOST_LOG_TRIVIAL (previously used here to report the error) may throw an
         // exception of type std::length_error.
         // Using stderr instead in this context as there is no point in nesting try-catch blocks here.
         std::cerr << "A CL error occurred unloading the runtime tuner parameters: "
                   << clError.what() << ". CL error code is: " << clError.err() << std::endl;
     }
 }
Member Function Documentation
ClearClCache()
void ClearClCache ()
Definition at line 164 of file ClContextControl.cpp.
 {
     DoLoadOpenClRuntime(true);
 }
LoadOpenClRuntime()
void LoadOpenClRuntime ()
Definition at line 92 of file ClContextControl.cpp.
Referenced by ClContextControl::ClContextControl().
 {
     DoLoadOpenClRuntime(true);
 }
UnloadOpenClRuntime()
void UnloadOpenClRuntime ()
Definition at line 97 of file ClContextControl.cpp.
References ARMNN_DISABLE_LEAK_CHECKING_IN_SCOPE, and armnn::Error.
Referenced by ClContextControl::~ClContextControl().
 {
     DoLoadOpenClRuntime(false);
 }
The documentation for this class was generated from the following files:
src/backends/cl/ClContextControl.hpp
src/backends/cl/ClContextControl.cpp