ArmNN: TestDynamicBackendUtils Class Reference
TestDynamicBackendUtils Class Reference
#include <DynamicBackendTests.hpp>
Static Public Member Functions
static bool IsBackendCompatibleTest (const armnn::BackendVersion &backendApiVersion, const armnn::BackendVersion &backendVersion)
static std::vector< std::string > GetBackendPathsImplTest (const std::string &path)
static armnn::BackendIdSet RegisterDynamicBackendsImplTest (armnn::BackendRegistry &backendRegistry, const std::vector< armnn::DynamicBackendPtr > &dynamicBackends)
Static Public Member Functions inherited from DynamicBackendUtils
static void * OpenHandle (const std::string &sharedObjectPath)
static void CloseHandle (const void *sharedObjectHandle)
template<typename EntryPointType >
static EntryPointType GetEntryPoint (const void *sharedObjectHandle, const char *symbolName)
static bool IsBackendCompatible (const BackendVersion &backendVersion)
static std::vector< std::string > GetBackendPaths (const std::string &overrideBackendPath="")
static bool IsPathValid (const std::string &path)
static std::vector< std::string > GetSharedObjects (const std::vector< std::string > &backendPaths)
static std::vector< DynamicBackendPtr > CreateDynamicBackends (const std::vector< std::string > &sharedObjects)
static BackendIdSet RegisterDynamicBackends (const std::vector< DynamicBackendPtr > &dynamicBackends)
static void DeregisterDynamicBackends (const BackendIdSet &dynamicBackends)
Additional Inherited Members
Static Protected Member Functions inherited from DynamicBackendUtils
static bool IsBackendCompatibleImpl (const BackendVersion &backendApiVersion, const BackendVersion &backendVersion)
Protected methods for testing purposes.
static std::vector< std::string > GetBackendPathsImpl (const std::string &backendPaths)
static BackendIdSet RegisterDynamicBackendsImpl (BackendRegistry &backendRegistry, const std::vector< DynamicBackendPtr > &dynamicBackends)
Detailed Description
Definition at line 69 of file DynamicBackendTests.hpp.
Member Function Documentation
GetBackendPathsImplTest()
static std::vector<std::string> GetBackendPathsImplTest (const std::string & path) inline static
Definition at line 78 of file DynamicBackendTests.hpp.
References DynamicBackendUtils::GetBackendPathsImpl().
     {
         return GetBackendPathsImpl(path);
     }
IsBackendCompatibleTest()
static bool IsBackendCompatibleTest (const armnn::BackendVersion & backendApiVersion, const armnn::BackendVersion & backendVersion) inline static
Definition at line 72 of file DynamicBackendTests.hpp.
References DynamicBackendUtils::IsBackendCompatibleImpl().
Referenced by BackendVersioningTestImpl().
     {
         return IsBackendCompatibleImpl(backendApiVersion, backendVersion);
     }
RegisterDynamicBackendsImplTest()
static armnn::BackendIdSet RegisterDynamicBackendsImplTest (armnn::BackendRegistry & backendRegistry, const std::vector< armnn::DynamicBackendPtr > & dynamicBackends) inline static
Definition at line 83 of file DynamicBackendTests.hpp.
References DynamicBackendUtils::RegisterDynamicBackendsImpl().
     {
         return RegisterDynamicBackendsImpl(backendRegistry, dynamicBackends);
     }
The documentation for this class was generated from the following file:
src/backends/backendsCommon/test/DynamicBackendTests.hpp