ArmNN: MockBackendProfilingService Class Reference
MockBackendProfilingService Class Reference
#include <MockBackend.hpp>
Public Member Functions
MockBackendProfilingContext * GetContext ()
void SetProfilingContextPtr (std::shared_ptr< MockBackendProfilingContext > shared)
Static Public Member Functions
static MockBackendProfilingService & Instance ()
Detailed Description
Definition at line 119 of file MockBackend.hpp.
Member Function Documentation
GetContext()
MockBackendProfilingContext* GetContext () inline
Definition at line 129 of file MockBackend.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         return m_sharedContext.get();
     }
Instance()
static MockBackendProfilingService& Instance () inline static
Definition at line 123 of file MockBackend.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and MockBackend::CreateBackendProfilingContext().
     {
         static MockBackendProfilingService instance;
         return instance;
     }
SetProfilingContextPtr()
void SetProfilingContextPtr (std::shared_ptr< MockBackendProfilingContext > shared) inline
Definition at line 134 of file MockBackend.hpp.
Referenced by MockBackend::CreateBackendProfilingContext().
     {
         m_sharedContext = shared;
     }
The documentation for this class was generated from the following file:
src/backends/backendsCommon/test/MockBackend.hpp