ArmNN: BufferManager Class Reference
BufferManager Class Reference
#include <BufferManager.hpp>
Public Member Functions
BufferManager (unsigned int numberOfBuffers=5, unsigned int maxPacketSize=4096)
~BufferManager ()
IPacketBufferPtr Reserve (unsigned int requestedSize, unsigned int &reservedSize) override
void Reset ()
void Commit (IPacketBufferPtr &packetBuffer, unsigned int size, bool notifyConsumer=true) override
void Release (IPacketBufferPtr &packetBuffer) override
IPacketBufferPtr GetReadableBuffer () override
void MarkRead (IPacketBufferPtr &packetBuffer) override
void SetConsumer (IConsumer *consumer) override
Set Consumer on the buffer manager to be notified when there is a Commit Can only be one consumer.
void FlushReadList () override
Notify the Consumer buffer can be read.
Public Member Functions inherited from IBufferManager
virtual ~IBufferManager ()
Detailed Description
Definition at line 22 of file BufferManager.hpp.
Constructor & Destructor Documentation
BufferManager()
BufferManager (unsigned int numberOfBuffers = 5, unsigned int maxPacketSize = 4096)
Definition at line 15 of file BufferManager.cpp.
     : m_MaxBufferSize(maxPacketSize),
       m_NumberOfBuffers(numberOfBuffers),
       m_MaxNumberOfBuffers(numberOfBuffers * 3),
       m_CurrentNumberOfBuffers(numberOfBuffers)
 {
     Initialize();
 }
~BufferManager()
~BufferManager () inline
Definition at line 27 of file BufferManager.hpp.
References BufferManager::Commit(), BufferManager::FlushReadList(), BufferManager::GetReadableBuffer(), BufferManager::MarkRead(), BufferManager::Release(), BufferManager::Reserve(), BufferManager::Reset(), and BufferManager::SetConsumer().
 {}
Member Function Documentation
Commit()
void Commit (IPacketBufferPtr & packetBuffer, unsigned int size, bool notifyConsumer = true) override virtual
Implements IBufferManager.
Definition at line 58 of file BufferManager.cpp.
References BufferManager::FlushReadList().
Referenced by BOOST_AUTO_TEST_CASE(), and BufferManager::~BufferManager().
 {
     std::unique_lock<std::mutex> readableListLock(m_ReadableMutex, std::defer_lock);
     packetBuffer->Commit(size);
     readableListLock.lock();
     m_ReadableList.push(std::move(packetBuffer));
     readableListLock.unlock();
     if (notifyConsumer)
     {
         FlushReadList();
     }
 }
FlushReadList()
void FlushReadList () override virtual
Notify the Consumer buffer can be read.
Implements IBufferManager.
Definition at line 155 of file BufferManager.cpp.
References IConsumer::SetReadyToRead().
Referenced by BufferManager::Commit(), and BufferManager::~BufferManager().
 {
     // notify consumer that packet is ready to read
     if (m_Consumer != nullptr)
     {
         m_Consumer->SetReadyToRead();
     }
 }
GetReadableBuffer()
IPacketBufferPtr GetReadableBuffer () override virtual
Implements IBufferManager.
Definition at line 116 of file BufferManager.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CheckTimelineDirectory(), VerifyPostOptimisationStructureTestImpl(), and BufferManager::~BufferManager().
 {
     std::unique_lock<std::mutex> readableListLock(m_ReadableMutex);
     if (!m_ReadableList.empty())
     {
         IPacketBufferPtr buffer = std::move(m_ReadableList.front());
         m_ReadableList.pop();
         readableListLock.unlock();
         return buffer;
     }
     return nullptr;
 }
MarkRead()
void MarkRead (IPacketBufferPtr & packetBuffer) override virtual
Implements IBufferManager.
Definition at line 129 of file BufferManager.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and BufferManager::~BufferManager().
 {
     std::unique_lock<std::mutex> availableListLock(m_AvailableMutex, std::defer_lock);
     packetBuffer->MarkRead();
     availableListLock.lock();
     if (m_AvailableList.size() <= m_NumberOfBuffers)
     {
         m_AvailableList.push_back(std::move(packetBuffer));
     }
     else
     {
         // we have been handed a temporary overflow/surge buffer get rid of it
         packetBuffer->Destroy();
         if (m_CurrentNumberOfBuffers > m_NumberOfBuffers)
         {
             --m_CurrentNumberOfBuffers;
         }
     }
     availableListLock.unlock();
 }
Release()
void Release (IPacketBufferPtr & packetBuffer) override virtual
Implements IBufferManager.
Definition at line 83 of file BufferManager.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and BufferManager::~BufferManager().
 {
     std::unique_lock<std::mutex> availableListLock(m_AvailableMutex, std::defer_lock);
     packetBuffer->Release();
     availableListLock.lock();
     if (m_AvailableList.size() <= m_NumberOfBuffers)
     {
         m_AvailableList.push_back(std::move(packetBuffer));
     }
     else
     {
         // we have been handed a temporary overflow/surge buffer get rid of it
         packetBuffer->Destroy();
         if (m_CurrentNumberOfBuffers > m_NumberOfBuffers)
         {
             --m_CurrentNumberOfBuffers;
         }
     }
     availableListLock.unlock();
 }
Reserve()
IPacketBufferPtr Reserve (unsigned int requestedSize, unsigned int & reservedSize) override virtual
Implements IBufferManager.
Definition at line 24 of file BufferManager.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and BufferManager::~BufferManager().
 {
     reservedSize = 0;
     std::unique_lock<std::mutex> availableListLock(m_AvailableMutex, std::defer_lock);
     if (requestedSize > m_MaxBufferSize)
     {
         return nullptr;
     }
     availableListLock.lock();
     if (m_AvailableList.empty())
     {
         if (m_CurrentNumberOfBuffers < m_MaxNumberOfBuffers)
         {
             // create a temporary overflow/surge buffer and hand it back
             m_CurrentNumberOfBuffers++;
             availableListLock.unlock();
             IPacketBufferPtr buffer = std::make_unique<PacketBuffer>(m_MaxBufferSize);
             reservedSize = requestedSize;
             return buffer;
         }
         else
         {
             // we have totally busted the limit. call a halt to new memory allocations.
             availableListLock.unlock();
             return nullptr;
         }
     }
     IPacketBufferPtr buffer = std::move(m_AvailableList.back());
     m_AvailableList.pop_back();
     availableListLock.unlock();
     reservedSize = requestedSize;
     return buffer;
 }
Reset()
void Reset ()
Definition at line 104 of file BufferManager.cpp.
References armnn::swap().
Referenced by ProfilingService::GetSendTimelinePacket(), and BufferManager::~BufferManager().
 {
     //This method should only be called once all threads have been joined
     std::lock_guard<std::mutex> readableListLock(m_ReadableMutex);
     std::lock_guard<std::mutex> availableListLock(m_AvailableMutex);
     m_AvailableList.clear();
     std::queue<IPacketBufferPtr>().swap(m_ReadableList);
     Initialize();
 }
SetConsumer()
void SetConsumer (IConsumer * consumer) override virtual
Set Consumer on the buffer manager to be notified when there is a Commit Can only be one consumer.
Implements IBufferManager.
Definition at line 150 of file BufferManager.cpp.
Referenced by BufferManager::~BufferManager().
 {
     m_Consumer = consumer;
 }
The documentation for this class was generated from the following files:
src/profiling/BufferManager.hpp
src/profiling/BufferManager.cpp