ArmNN: StaticRangeStrategy Class Reference
StaticRangeStrategy Class Reference
#include <StaticRangeStrategy.hpp>
Public Member Functions
StaticRangeStrategy (RangeTracker &rangeTracker)
~StaticRangeStrategy ()=default
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id) override
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Additional Inherited Members
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Detailed Description
Definition at line 18 of file StaticRangeStrategy.hpp.
Constructor & Destructor Documentation
StaticRangeStrategy()
StaticRangeStrategy (RangeTracker & rangeTracker)
Definition at line 17 of file StaticRangeStrategy.cpp.
References IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IOutputSlot::GetOwningLayerGuid(), RangeTracker::GetRange(), and RangeTracker::SetRange().
     : m_RangeTracker(rangeTracker)
 {}
~StaticRangeStrategy()
~StaticRangeStrategy () default
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id) override virtual
Implements IStrategy.
Definition at line 33 of file StaticRangeStrategy.cpp.
References armnn::Abs, armnn::Activation, armnn::Addition, armnn::ArgMinMax, armnn::BatchNormalization, armnn::BatchToSpaceNd, armnn::BoundedReLu, IOutputSlot::CalculateIndexOnOwner(), armnn::Concat, armnn::Constant, armnn::Convolution2d, armnn::DepthwiseConvolution2d, armnn::Float32, armnn::FullyConnected, IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IOutputSlot::GetOwningLayerGuid(), RangeTracker::GetRange(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), armnn::LeakyReLu, armnn::Linear, ActivationDescriptor::m_A, ActivationDescriptor::m_Function, armnn::Permute, armnn::Pooling2d, armnn::ReLu, armnn::Reshape, armnn::Resize, armnn::Softmax, armnn::SoftReLu, armnn::SpaceToBatchNd, armnn::Splitter, armnn::StridedSlice, and armnn::TanH.
 {
 IgnoreUnused(id, name);
 switch (layer->GetType())
 {
     case armnn::LayerType::Activation :
     {
         const ActivationDescriptor& activationDescriptor = static_cast<const ActivationDescriptor&>(descriptor);
         switch (activationDescriptor.m_Function)
         {
             // Range is 0, 15 for Abs, Linear, ReLu and Soft ReLu
             case ActivationFunction::Abs:
             case ActivationFunction::Linear:
             case ActivationFunction::ReLu:
             case ActivationFunction::SoftReLu:
                 SetRange(layer, 0, 0.f, 15.f);
                 break;
             case ActivationFunction::BoundedReLu:
                 SetRange(layer, 0, 0.f, activationDescriptor.m_A);
                 break;
             case ActivationFunction::TanH:
                 SetRange(layer, 0, -1.f, 1.f);
                 break;
             case ActivationFunction::LeakyReLu:
                 SetRange(layer, 0, -5.f, 15.f);
                 break;
             default:
                 SetRange(layer, 0, -15.f, 15.f);
                 break;
         }
         break;
     }
     case armnn::LayerType::Addition :
     {
         SetRange(layer, 0, -20.f, 20.f);
         break;
     }
     case armnn::LayerType::ArgMinMax :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::BatchToSpaceNd :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::BatchNormalization :
     {
         SetRange(layer, 0, -15.0f, 15.0f);
         break;
     }
     case armnn::LayerType::Concat :
     {
         float min = std::numeric_limits<float>::max();
         float max = std::numeric_limits<float>::lowest();
         for (unsigned int i = 0; i < layer->GetNumInputSlots(); ++i)
         {
             const IOutputSlot* outputSlot = layer->GetInputSlot(i).GetConnection();
             LayerGuid layerId = outputSlot->GetOwningLayerGuid();
             unsigned int slotIndex = outputSlot->CalculateIndexOnOwner();
             RangeTracker::MinMaxRange range = m_RangeTracker.GetRange(layerId, slotIndex);
             min = std::min(min, range.first);
             max = std::max(max, range.second);
         }
         SetRange(layer, 0, min, max);
         break;
     }
     case armnn::LayerType::Constant :
     {
         if (constants[0].GetDataType() != DataType::Float32)
         {
             throw InvalidArgumentException("Quantization is supported only for FP32 tensors");
         }
         // Work out the range based on the input constants
         unsigned int inputNumElements = constants[0].GetNumElements();
         const float* inputData = reinterpret_cast<const float*>(constants[0].GetMemoryArea());
         float min = std::numeric_limits<float>::max();
         float max = std::numeric_limits<float>::lowest();
         for (unsigned int i = 0; i < inputNumElements; i++)
         {
             const float inputValue = inputData[i];
             min = std::min(min, inputValue);
             max = std::max(max, inputValue);
         }
         SetRange(layer, 0, min, max);
         break;
     }
     case armnn::LayerType::Convolution2d :
     {
         SetRange(layer, 0, -15.0f, 15.0f);
         break;
     }
     case armnn::LayerType::DepthwiseConvolution2d :
     {
         SetRange(layer, 0, -15.0f, 15.0f);
         break;
     }
     case armnn::LayerType::FullyConnected :
     {
         SetRange(layer, 0, -15.0f, 15.0f);
         break;
     }
     case armnn::LayerType::Permute :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::Pooling2d :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::Reshape :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::Resize :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::Splitter :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::SpaceToBatchNd :
     {
         ForwardParentParameters(layer);
         break;
     }
     case armnn::LayerType::Softmax :
     {
         SetRange(layer, 0, 0.f, 1.f);
         break;
     }
     case armnn::LayerType::StridedSlice :
     {
         ForwardParentParameters(layer);
         break;
     }
     default:
     {
     }
 }
 }
The documentation for this class was generated from the following files:
src/armnn/StaticRangeStrategy.hpp
src/armnn/StaticRangeStrategy.cpp