ArmNN: InputLayerStrategy Class Reference
InputLayerStrategy Class Reference
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
#include <QuantizationDataSet.hpp>
Public Member Functions
virtual void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
armnn::TensorInfo GetTensorInfo (armnn::LayerBindingId)
Public Member Functions inherited from IStrategy
virtual void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0)=0
virtual void FinishStrategy ()
Additional Inherited Members
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Detailed Description
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
Definition at line 46 of file QuantizationDataSet.hpp.
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) override virtual
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
Definition at line 53 of file QuantizationDataSet.cpp.
References IConnectableLayer::GetOutputSlot(), IOutputSlot::GetTensorInfo(), and armnn::IgnoreUnused().
Referenced by main().
 {
     armnn::IgnoreUnused(name, descriptor, constants);
     m_TensorInfos.emplace(id, layer->GetOutputSlot(0).GetTensorInfo());
 }
GetTensorInfo()
armnn::TensorInfo GetTensorInfo (armnn::LayerBindingId layerBindingId)
Definition at line 67 of file QuantizationDataSet.cpp.
Referenced by main().
 {
     auto iterator = m_TensorInfos.find(layerBindingId);
     if (iterator != m_TensorInfos.end())
     {
         return m_TensorInfos.at(layerBindingId);
     }
     else
     {
         throw armnn::Exception("Could not retrieve tensor info for binding ID " + std::to_string(layerBindingId));
     }
 }
The documentation for this class was generated from the following files:
src/armnnQuantizer/QuantizationDataSet.hpp
src/armnnQuantizer/QuantizationDataSet.cpp