ArmNN: LayerVerifierBaseWithDescriptor< Descriptor > Class Template Reference
LayerVerifierBaseWithDescriptor< Descriptor > Class Template Reference
#include <SerializerTestUtils.hpp>
Public Member Functions
LayerVerifierBaseWithDescriptor (const std::string &layerName, const std::vector< armnn::TensorInfo > &inputInfos, const std::vector< armnn::TensorInfo > &outputInfos, const Descriptor &descriptor)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from LayerVerifierBase
LayerVerifierBase (const std::string &layerName, const std::vector< armnn::TensorInfo > &inputInfos, const std::vector< armnn::TensorInfo > &outputInfos)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from IStrategy
virtual void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0)=0
virtual void FinishStrategy ()
Protected Member Functions
void VerifyDescriptor (const Descriptor &descriptor)
Protected Member Functions inherited from LayerVerifierBase
void VerifyNameAndConnections (const armnn::IConnectableLayer *layer, const char *name)
void VerifyConstTensors (const std::string &tensorName, const armnn::ConstTensor *expectedPtr, const armnn::ConstTensor *actualPtr)
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Protected Attributes
Descriptor m_Descriptor
Detailed Description
template<typename Descriptor>
class LayerVerifierBaseWithDescriptor< Descriptor >
Definition at line 51 of file SerializerTestUtils.hpp.
Constructor & Destructor Documentation
LayerVerifierBaseWithDescriptor()
LayerVerifierBaseWithDescriptor (const std::string & layerName, const std::vector< armnn::TensorInfo > & inputInfos, const std::vector< armnn::TensorInfo > & outputInfos, const Descriptor & descriptor) inline
Definition at line 54 of file SerializerTestUtils.hpp.
         : LayerVerifierBase(layerName, inputInfos, outputInfos)
         , m_Descriptor(descriptor) {}
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override
Definition at line 61 of file SerializerTestUtils.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ConstantVector2LstmInputParams().
     {
         armnn::IgnoreUnused(constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::Input: break;
             case armnn::LayerType::Output: break;
             default:
             {
                 VerifyNameAndConnections(layer, name);
                 const Descriptor& internalDescriptor = static_cast<const Descriptor&>(descriptor);
                 VerifyDescriptor(internalDescriptor);
                 break;
             }
         }
     }
VerifyDescriptor()
void VerifyDescriptor (const Descriptor & descriptor) inline protected
Definition at line 83 of file SerializerTestUtils.hpp.
Referenced by ConstantVector2LstmInputParams().
     {
         BOOST_CHECK(descriptor == m_Descriptor);
     }
Member Data Documentation
m_Descriptor
Descriptor m_Descriptor protected
Definition at line 88 of file SerializerTestUtils.hpp.
The documentation for this class was generated from the following file:
src/armnnSerializer/test/SerializerTestUtils.hpp