ArmNN: OverrideInputRangeStrategy Class Reference
OverrideInputRangeStrategy Class Reference
#include <OverrideInputRangeVisitor.hpp>
Public Member Functions
OverrideInputRangeStrategy (RangeTracker &ranges, LayerBindingId layerId, const MinMaxRange &minMaxRange)
~OverrideInputRangeStrategy ()=default
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id) override
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Additional Inherited Members
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Detailed Description
Definition at line 16 of file OverrideInputRangeVisitor.hpp.
Constructor & Destructor Documentation
OverrideInputRangeStrategy()
OverrideInputRangeStrategy (RangeTracker & ranges, LayerBindingId layerId, const MinMaxRange & minMaxRange) inline
Definition at line 21 of file OverrideInputRangeVisitor.hpp.
References OverrideInputRangeStrategy::~OverrideInputRangeStrategy().
                                : m_Ranges(ranges)
             , m_LayerId(layerId)
             , m_MinMaxRange(minMaxRange){}
~OverrideInputRangeStrategy()
~OverrideInputRangeStrategy () default
Referenced by OverrideInputRangeStrategy::OverrideInputRangeStrategy().
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id) inline override virtual
Implements IStrategy.
Definition at line 30 of file OverrideInputRangeVisitor.hpp.
References IConnectableLayer::GetType(), armnn::IgnoreUnused(), armnn::Input, and RangeTracker::SetRange().
     {
         IgnoreUnused(name, constants, id, descriptor);
         switch (layer->GetType())
         {
             case armnn::LayerType::Input :
             {
                 if (m_LayerId == id)
                 {
                     m_Ranges.SetRange(layer, 0, m_MinMaxRange.first, m_MinMaxRange.second);
                 }
                 break;
             }
             default:
             {
                 std::cout << "dont know this one" << std::endl;
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/OverrideInputRangeVisitor.hpp