ArmNN: IBufferManager Class Reference
IBufferManager Class Reference abstract
#include <IBufferManager.hpp>
Public Member Functions
virtual ~IBufferManager ()
virtual IPacketBufferPtr Reserve (unsigned int requestedSize, unsigned int &reservedSize)=0
virtual void Commit (IPacketBufferPtr &packetBuffer, unsigned int size, bool notifyConsumer=true)=0
virtual void Release (IPacketBufferPtr &packetBuffer)=0
virtual IPacketBufferPtr GetReadableBuffer ()=0
virtual void MarkRead (IPacketBufferPtr &packetBuffer)=0
virtual void SetConsumer (IConsumer *consumer)=0
virtual void FlushReadList ()=0
Detailed Description
Definition at line 21 of file IBufferManager.hpp.
Constructor & Destructor Documentation
~IBufferManager()
virtual ~IBufferManager () inline virtual
Definition at line 24 of file IBufferManager.hpp.
References IBufferManager::Commit(), IBufferManager::FlushReadList(), IBufferManager::GetReadableBuffer(), IBufferManager::MarkRead(), IBufferManager::Release(), IBufferManager::Reserve(), and IBufferManager::SetConsumer().
 {}
Member Function Documentation
Commit()
virtual void Commit (IPacketBufferPtr & packetBuffer, unsigned int size, bool notifyConsumer = true) pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendTimelinePacket::Commit(), SendCounterPacket::SendPeriodicCounterCapturePacket(), SendCounterPacket::SendPeriodicCounterSelectionPacket(), SendCounterPacket::SendStreamMetaDataPacket(), and IBufferManager::~IBufferManager().
FlushReadList()
virtual void FlushReadList () pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendCounterPacket::SendCounterPacket(), and IBufferManager::~IBufferManager().
GetReadableBuffer()
virtual IPacketBufferPtr GetReadableBuffer () pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendThread::Stop(), and IBufferManager::~IBufferManager().
MarkRead()
virtual void MarkRead (IPacketBufferPtr & packetBuffer) pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendThread::Stop(), and IBufferManager::~IBufferManager().
Release()
virtual void Release (IPacketBufferPtr & packetBuffer) pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendCounterPacket::SendCounterPacket(), and IBufferManager::~IBufferManager().
Reserve()
virtual IPacketBufferPtr Reserve (unsigned int requestedSize, unsigned int & reservedSize) pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendTimelinePacket::Commit(), SendCounterPacket::SendPeriodicCounterCapturePacket(), SendCounterPacket::SendPeriodicCounterSelectionPacket(), SendCounterPacket::SendStreamMetaDataPacket(), and IBufferManager::~IBufferManager().
SetConsumer()
virtual void SetConsumer (IConsumer * consumer) pure virtual
Implemented in MockStreamCounterBuffer, MockBufferManager, and BufferManager.
Referenced by SendThread::SendThread(), and IBufferManager::~IBufferManager().
The documentation for this class was generated from the following file:
src/profiling/IBufferManager.hpp