ArmNN: DynamicQuantizationStrategy Class Reference
DynamicQuantizationStrategy Class Reference
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
#include <DynamicQuantizationStrategy.hpp>
Public Member Functions
DynamicQuantizationStrategy (RangeTracker &rangeTracker, Graph &graph)
~DynamicQuantizationStrategy ()=default
virtual void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
const std::vector< armnn::LayerBindingId > & GetOutputLayers ()
void VisitNonCalibratedLayers ()
void FinishStrategy () override
Additional Inherited Members
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Detailed Description
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
Definition at line 19 of file DynamicQuantizationStrategy.hpp.
Constructor & Destructor Documentation
DynamicQuantizationStrategy()
DynamicQuantizationStrategy (RangeTracker & rangeTracker, Graph & graph)
Definition at line 18 of file DynamicQuantizationStrategy.cpp.
References IOutputSlot::CalculateIndexOnOwner(), IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IOutputSlot::GetOwningLayerGuid(), RangeTracker::GetRange(), and RangeTracker::SetRange().
         : m_RangeTracker(rangeTracker),
           m_Graph(graph)
 {}
~DynamicQuantizationStrategy()
~DynamicQuantizationStrategy () default
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) override virtual
Implements IStrategy.
Definition at line 87 of file DynamicQuantizationStrategy.cpp.
References armnn::Abs, armnn::Activation, armnn::Addition, armnn::ArgMinMax, armnn::BatchNormalization, armnn::BatchToSpaceNd, armnn::BoundedReLu, IOutputSlot::CalculateIndexOnOwner(), armnn::Concat, armnn::Constant, armnn::Convolution2d, armnn::DepthwiseConvolution2d, armnn::Float32, armnn::FullyConnected, IInputSlot::GetConnection(), IConnectableLayer::GetInputSlot(), IConnectableLayer::GetNumInputSlots(), IOutputSlot::GetOwningLayerGuid(), RangeTracker::GetRange(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), armnn::Input, armnn::LeakyReLu, armnn::Linear, ActivationDescriptor::m_A, ActivationDescriptor::m_Function, armnn::Normalization, armnn::Output, armnn::Permute, armnn::Pooling2d, armnn::ReLu, armnn::Reshape, armnn::Resize, armnn::Softmax, armnn::SoftReLu, armnn::SpaceToBatchNd, armnn::Splitter, armnn::StridedSlice, and armnn::TanH.
 {
     IgnoreUnused(name);
     IgnoreUnused(id);
     IgnoreUnused(descriptor);
     switch (layer->GetType())
     {
         case armnn::LayerType::Activation :
         {
             const ActivationDescriptor& activationDescriptor = static_cast<const ActivationDescriptor&>(descriptor);
             switch (activationDescriptor.m_Function)
             {
                 // Range is 0, 15 for Abs, Linear, ReLu and Soft ReLu
                 case ActivationFunction::Abs:
                 case ActivationFunction::Linear:
                 case ActivationFunction::ReLu:
                 case ActivationFunction::SoftReLu:
                     SetRange(layer, 0, 0.f, 15.f);
                     break;
                 case ActivationFunction::BoundedReLu:
                     SetRange(layer, 0, 0.f, activationDescriptor.m_A);
                     break;
                 case ActivationFunction::TanH:
                     SetRange(layer, 0, -1.f, 1.f);
                     break;
                 case ActivationFunction::LeakyReLu:
                     SetRange(layer, 0, -5.f, 15.f);
                     break;
                 default:
                     SetRange(layer, 0, -15.f, 15.f);
                     break;
             }
             break;
         }
         case armnn::LayerType::Addition :
         {
             SetRange(layer, 0, -20.f, 20.f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::ArgMinMax :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::BatchNormalization :
         {
             SetRange(layer, 0, -15.0f, 15.0f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Normalization:
         {
             SetRange(layer, 0, -15.0f, 15.0f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Convolution2d:
         {
             SetRange(layer, 0, -15.0f, 15.0f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::DepthwiseConvolution2d:
         {
             SetRange(layer, 0, -15.0f, 15.0f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::FullyConnected :
         {
             SetRange(layer, 0, -15.0f, 15.0f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Permute :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::SpaceToBatchNd :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Pooling2d :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Softmax :
         {
             SetRange(layer, 0, 0.f, 1.f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Constant :
         {
             if (constants[0].GetDataType() != DataType::Float32)
             {
                 throw InvalidArgumentException("Quantization is supported only for FP32 tensors");
             }
             // Work out the range based on the input constants
             unsigned int inputNumElements = constants[0].GetNumElements();
             const float* inputData = reinterpret_cast<const float*>(constants[0].GetMemoryArea());
             float min = std::numeric_limits<float>::max();
             float max = std::numeric_limits<float>::lowest();
             for (unsigned int i = 0; i < inputNumElements; i++)
             {
                 const float inputValue = inputData[i];
                 min = std::min(min, inputValue);
                 max = std::max(max, inputValue);
             }
             SetRange(layer, 0, min, max);
             break;
         }
         case armnn::LayerType::Concat :
         {
             float min = std::numeric_limits<float>::max();
             float max = std::numeric_limits<float>::lowest();
             for (unsigned int i = 0; i < layer->GetNumInputSlots(); ++i)
             {
                 const IOutputSlot* outputSlot = layer->GetInputSlot(i).GetConnection();
                 LayerGuid layerId = outputSlot->GetOwningLayerGuid();
                 unsigned int slotIndex = outputSlot->CalculateIndexOnOwner();
                 RangeTracker::MinMaxRange range = m_RangeTracker.GetRange(layerId, slotIndex);
                 min = std::min(min, range.first);
                 max = std::max(max, range.second);
             }
             SetRange(layer, 0, min, max);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Reshape :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Splitter :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Resize :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::StridedSlice :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::BatchToSpaceNd :
         {
             AddToNonCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Input :
         {
             SetRange(layer, 0, -0.0f, 0.0f);
             AddToCalibratedLayers(layer);
             break;
         }
         case armnn::LayerType::Output :
         {
             AddToNonCalibratedLayers(layer);
             m_OutputLayers.push_back(id);
             break;
         }
         default:
         {}
     }
 }
FinishStrategy()
void FinishStrategy () override virtual
Reimplemented from IStrategy.
Definition at line 50 of file DynamicQuantizationStrategy.cpp.
References OutputSlot::Connect(), OutputSlot::Disconnect(), Graph::EraseLayer(), and armnn::InsertDebugLayerAfter().
 {
     for (const IConnectableLayer* layer : m_LayersToCalibrate)
     {
         std::vector<DebugLayer*> newDebugLayers = InsertDebugLayerAfter(
             m_Graph, *PolymorphicDowncast<Layer*>(const_cast<IConnectableLayer*>(layer)));
         // record them so we can take them out again efficiently afterward
         m_DebugLayers.insert(std::end(m_DebugLayers), std::begin(newDebugLayers), std::end(newDebugLayers));
     }
 }
GetOutputLayers()
const std::vector< LayerBindingId > & GetOutputLayers ()
Definition at line 271 of file DynamicQuantizationStrategy.cpp.
 {
     return m_OutputLayers;
 }
VisitNonCalibratedLayers()
void VisitNonCalibratedLayers ()
Definition at line 78 of file DynamicQuantizationStrategy.cpp.
{
     RemoveDebugLayers();
     for (const IConnectableLayer* layer : m_LayersNotToCalibrate)
     {
         ForwardParentParameters(layer);
     }
 }
The documentation for this class was generated from the following files:
src/armnn/DynamicQuantizationStrategy.hpp
src/armnn/DynamicQuantizationStrategy.cpp