ArmNN: ITfParser Class Reference
ITfParser Class Reference
Parses a directed acyclic graph from a tensorflow protobuf file.
#include <ITfParser.hpp>
Classes
struct TfParserImpl
Public Member Functions
armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Create the network from a protobuf text file on the disk.
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Create the network from a protobuf binary file on the disk.
armnn::INetworkPtr CreateNetworkFromString (const char *protoText, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs)
Create the network directly from protobuf text in a string. Useful for debugging/testing.
BindingPointInfo GetNetworkInputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
BindingPointInfo GetNetworkOutputBindingInfo (const std::string &name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Static Public Member Functions
static ITfParser * CreateRaw ()
static ITfParserPtr Create ()
static void Destroy (ITfParser *parser)
Friends
template<typename T >
class ParsedConstTfOperation
class ParsedMatMulTfOperation
class ParsedMulTfOperation
class ParsedTfOperation
class SingleLayerParsedTfOperation
class DeferredSingleLayerParsedTfOperation
class ParsedIdentityTfOperation
template<template< typename > class OperatorType, typename T >
struct MakeTfOperation
Detailed Description
Parses a directed acyclic graph from a tensorflow protobuf file.
Definition at line 25 of file ITfParser.hpp.
Member Function Documentation
Create()
ITfParserPtr Create () static
Definition at line 48 of file TfParser.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return ITfParserPtr(CreateRaw(), &ITfParser::Destroy);
 }
CreateNetworkFromBinaryFile()
armnn::INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Create the network from a protobuf binary file on the disk.
Definition at line 65 of file TfParser.cpp.
 {
     return pTfParserImpl->CreateNetworkFromBinaryFile(graphFile, inputShapes, requestedOutputs);
 }
CreateNetworkFromString()
armnn::INetworkPtr CreateNetworkFromString (const char * protoText, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Create the network directly from protobuf text in a string. Useful for debugging/testing.
Definition at line 72 of file TfParser.cpp.
 {
     return pTfParserImpl->CreateNetworkFromString(protoText, inputShapes, requestedOutputs);
 }
CreateNetworkFromTextFile()
armnn::INetworkPtr CreateNetworkFromTextFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs)
Create the network from a protobuf text file on the disk.
Definition at line 58 of file TfParser.cpp.
References ITfParser::CreateNetworkFromTextFile().
Referenced by ITfParser::CreateNetworkFromTextFile().
 {
     return pTfParserImpl->CreateNetworkFromTextFile(graphFile, inputShapes, requestedOutputs);
 }
CreateRaw()
ITfParser * CreateRaw () static
Definition at line 43 of file TfParser.cpp.
 {
     return new ITfParser();
 }
Destroy()
void Destroy (ITfParser * parser) static
Definition at line 53 of file TfParser.cpp.
 {
     delete parser;
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network input identified by the given layer name.
Definition at line 79 of file TfParser.cpp.
 {
     return pTfParserImpl->GetNetworkInputBindingInfo(name);
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (const std::string & name) const
Retrieve binding info (layer id and tensor info) for the network output identified by the given layer name.
Definition at line 84 of file TfParser.cpp.
References INetwork::AddReshapeLayer(), armnnUtils::ArmNNToNHWC, CHECK_LOCATION, IOutputSlot::Connect(), IConnectableLayer::GetInputSlot(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), ReshapeDescriptor::m_TargetShape, armnnUtils::NHWCToArmNN, armnn::numeric_cast(), TensorInfo::SetShape(), and IOutputSlot::SetTensorInfo().
 {
     return pTfParserImpl->GetNetworkOutputBindingInfo(name);
 }
Friends And Related Function Documentation
DeferredSingleLayerParsedTfOperation
friend class DeferredSingleLayerParsedTfOperation friend
Definition at line 63 of file ITfParser.hpp.
Referenced by ITfParser::TfParserImpl::ParseIdentity(), ITfParser::TfParserImpl::ParseLrn(), and ITfParser::TfParserImpl::ParseMean().
MakeTfOperation
friend struct MakeTfOperation friend
Definition at line 67 of file ITfParser.hpp.
Referenced by armnnTfParser::ConvertTfTensorDataType().
ParsedConstTfOperation
friend class ParsedConstTfOperation friend
Definition at line 58 of file ITfParser.hpp.
Referenced by ITfParser::TfParserImpl::ParseIdentity().
ParsedIdentityTfOperation
friend class ParsedIdentityTfOperation friend
Definition at line 64 of file ITfParser.hpp.
Referenced by ITfParser::TfParserImpl::ParseBiasAdd().
ParsedMatMulTfOperation
friend class ParsedMatMulTfOperation friend
Definition at line 59 of file ITfParser.hpp.
Referenced by ITfParser::TfParserImpl::ParseLrn().
ParsedMulTfOperation
friend class ParsedMulTfOperation friend
Definition at line 60 of file ITfParser.hpp.
Referenced by ITfParser::TfParserImpl::ParseMean().
ParsedTfOperation
friend class ParsedTfOperation friend
Definition at line 61 of file ITfParser.hpp.
Referenced by ITfParser::TfParserImpl::AddFullyConnectedLayer(), ITfParser::TfParserImpl::GetInputParsedTfOperationsChecked(), ITfParser::TfParserImpl::LoadNodeDef(), ITfParser::TfParserImpl::ParseBiasAdd(), and ITfParser::TfParserImpl::ParseReshape().
SingleLayerParsedTfOperation
friend class SingleLayerParsedTfOperation friend
Definition at line 62 of file ITfParser.hpp.
The documentation for this class was generated from the following files:
include/armnnTfParser/ITfParser.hpp
src/armnnTfParser/TfParser.cpp