ArmNN: ErasedLayerNamesObservable Class Reference
ErasedLayerNamesObservable Class Reference
#include <Observable.hpp>
Public Member Functions
ErasedLayerNamesObservable (Graph &subject)
void Update (Layer *graphLayer) override
Public Member Functions inherited from GraphObservable< std::string >
GraphObservable (Graph &subject, GraphEvent notifyOnEvent)
void Clear ()
Iterator begin ()
Iterator end ()
Additional Inherited Members
Public Types inherited from GraphObservable< std::string >
using Iterator = typename std::list< std::string >::const_iterator
Protected Member Functions inherited from GraphObservable< std::string >
~GraphObservable ()
Protected Member Functions inherited from IGraphObservable
virtual ~IGraphObservable ()=default
Protected Attributes inherited from GraphObservable< std::string >
GraphEvent m_NotifyOnEvent
Graph * m_Subject
std::list< std::string > m_ObservedObjects
Detailed Description
Definition at line 56 of file Observable.hpp.
Constructor & Destructor Documentation
ErasedLayerNamesObservable()
ErasedLayerNamesObservable (Graph & subject) inline explicit
Definition at line 59 of file Observable.hpp.
References IGraphObservable::Update().
     : GraphObservable<std::string>(subject, GraphEvent::LayerErased)
     {};
Member Function Documentation
Update()
void Update (Layer * graphLayer) override virtual
Implements IGraphObservable.
Definition at line 16 of file Observable.cpp.
References Layer::GetName(), Layer::GetRelatedLayerNames(), and GraphObservable< Layer *>::m_ObservedObjects.
 {
     auto& relatedLayerNames = graphLayer->GetRelatedLayerNames();
     // If the erased layer has no related layers we take the erased layer's name
     // Otherwise we need to preserve the related layer names,
     // since we want to preserve the original graph's information
     if (relatedLayerNames.empty())
     {
         m_ObservedObjects.emplace_back(graphLayer->GetName());
     }
     else
     {
         for (auto& relatedLayerName : relatedLayerNames)
         {
             m_ObservedObjects.emplace_back(relatedLayerName);
         }
     }
 }
The documentation for this class was generated from the following files:
src/armnn/Observable.hpp
src/armnn/Observable.cpp