ArmNN: armnnQuantizer Namespace Reference
armnnQuantizer Namespace Reference
Classes
class CommandLineProcessor
class InputLayerStrategy
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
class InputLayerVisitor
Visitor class implementation to gather the TensorInfo for LayerBindingID for creation of ConstTensor for Refine.
class QuantizationDataSet
QuantizationDataSet is a structure which is created after parsing a quantization CSV file.
class QuantizationInput
QuantizationInput for specific pass ID, can list a corresponding raw data file for each LayerBindingId.
Functions
bool ValidateOutputDirectory (std::string &dir)
bool ValidateProvidedFile (const std::string &inputFileName)
bool ValidateQuantizationScheme (const std::string &scheme)
void AddInputData (unsigned int passId, armnn::LayerBindingId bindingId, const std::string &inputFilePath, std::map< unsigned int, QuantizationInput > &passIdToQuantizationInput)
unsigned int GetPassIdFromCsvRow (std::vector< std::string > tokens, unsigned int lineIndex)
armnn::LayerBindingId GetBindingIdFromCsvRow (std::vector< std::string > tokens, unsigned int lineIndex)
std::string GetFileNameFromCsvRow (std::vector< std::string > tokens, unsigned int lineIndex)
Function Documentation
AddInputData()
void armnnQuantizer::AddInputData (unsigned int passId, armnn::LayerBindingId bindingId, const std::string & inputFilePath, std::map< unsigned int, QuantizationInput > & passIdToQuantizationInput)
Definition at line 28 of file QuantizationDataSet.cpp.
Referenced by GetFileNameFromCsvRow().
 {
     auto iterator = passIdToQuantizationInput.find(passId);
     if (iterator == passIdToQuantizationInput.end())
     {
         QuantizationInput input(passId, bindingId, inputFilePath);
         passIdToQuantizationInput.emplace(passId, input);
     }
     else
     {
         auto existingQuantizationInput = iterator->second;
         existingQuantizationInput.AddEntry(bindingId, inputFilePath);
     }
 }
GetBindingIdFromCsvRow()
armnn::LayerBindingId armnnQuantizer::GetBindingIdFromCsvRow (std::vector< std::string > tokens, unsigned int lineIndex)
Definition at line 117 of file QuantizationDataSet.cpp.
Referenced by GetFileNameFromCsvRow().
 {
     armnn::LayerBindingId bindingId;
     try
     {
         bindingId = std::stoi(tokens[1]);
     }
     catch (const std::invalid_argument&)
     {
         throw armnn::ParseException(fmt::format("Binding ID [{}] is not correct format on CSV row {}",
                                                 tokens[1], lineIndex));
     }
     return bindingId;
 }
GetFileNameFromCsvRow()
std::string armnnQuantizer::GetFileNameFromCsvRow (std::vector< std::string > tokens, unsigned int lineIndex)
Definition at line 132 of file QuantizationDataSet.cpp.
References AddInputData(), GetBindingIdFromCsvRow(), GetPassIdFromCsvRow(), armnn::stringUtils::StringTokenizer(), and armnn::stringUtils::StringTrim().
 {
     std::string fileName = armnn::stringUtils::StringTrim(tokens[2]);
     if (!fs::exists(fileName))
     {
         throw armnn::ParseException(fmt::format("File [{}] provided on CSV row {} does not exist.",
                                                 fileName, lineIndex));
     }
     if (fileName.empty())
     {
         throw armnn::ParseException(fmt::format("Filename cannot be empty on CSV row {} ", lineIndex));
     }
     return fileName;
 }
GetPassIdFromCsvRow()
unsigned int armnnQuantizer::GetPassIdFromCsvRow (std::vector< std::string > tokens, unsigned int lineIndex)
Definition at line 102 of file QuantizationDataSet.cpp.
Referenced by GetFileNameFromCsvRow().
 {
     unsigned int passId;
     try
     {
         passId = static_cast<unsigned int>(std::stoi(tokens[0]));
     }
     catch (const std::invalid_argument&)
     {
         throw armnn::ParseException(fmt::format("Pass ID [{}] is not correct format on CSV row {}",
                                                 tokens[0], lineIndex));
     }
     return passId;
 }
ValidateOutputDirectory()
bool armnnQuantizer::ValidateOutputDirectory (std::string & dir)
Definition at line 14 of file CommandLineProcessor.cpp.
Referenced by CommandLineProcessor::ProcessCommandLine().
 {
     if (dir.empty())
     {
         std::cerr << "No output directory specified" << std::endl;
         return false;
     }
     if (dir[dir.length() - 1] != '/')
     {
         dir += "/";
     }
     if (!fs::exists(dir))
     {
         std::cerr << "Output directory [" << dir << "] does not exist" << std::endl;
         return false;
     }
     if (!fs::is_directory(dir))
     {
         std::cerr << "Given output directory [" << dir << "] is not a directory" << std::endl;
         return false;
     }
     return true;
 }
ValidateProvidedFile()
bool armnnQuantizer::ValidateProvidedFile (const std::string & inputFileName)
Definition at line 42 of file CommandLineProcessor.cpp.
Referenced by CommandLineProcessor::ProcessCommandLine().
 {
     if (!fs::exists(inputFileName))
     {
         std::cerr << "Provided file [" << inputFileName << "] does not exist" << std::endl;
         return false;
     }
     if (fs::is_directory(inputFileName))
     {
         std::cerr << "Given file [" << inputFileName << "] is a directory" << std::endl;
         return false;
     }
     return true;
 }
ValidateQuantizationScheme()
bool armnnQuantizer::ValidateQuantizationScheme (const std::string & scheme)
Definition at line 59 of file CommandLineProcessor.cpp.
Referenced by CommandLineProcessor::ProcessCommandLine().
 {
     if (scheme.empty())
     {
         std::cerr << "No Quantization Scheme specified" << std::endl;
         return false;
     }
     std::vector<std::string> supportedSchemes =
     {
         "QAsymmS8",
         "QAsymmU8",
         "QSymm16"
     };
     auto iterator = std::find(supportedSchemes.begin(), supportedSchemes.end(), scheme);
     if (iterator == supportedSchemes.end())
     {
         std::cerr << "Quantization Scheme [" << scheme << "] is not supported" << std::endl;
         return false;
     }
     return true;
 }