ArmNN: armnnUtils::Threads Namespace Reference
armnnUtils::Threads Namespace Reference
Functions
int GetCurrentThreadId ()
Function Documentation
GetCurrentThreadId()
int GetCurrentThreadId ()
Definition at line 27 of file Threads.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), TimelineUtilityMethods::RecordEvent(), and VerifyTimelineEventBinaryPacket().
 {
 #if defined(__linux__)
     return static_cast<int>(gettid());
 #elif defined(_MSC_VER)
     return ::GetCurrentThreadId();
 #elif defined(__APPLE__)
     uint64_t threadId;
     int iRet = pthread_threadid_np(NULL, &threadId);
     if (iRet != 0)
     {
         return 0;
     }
     return static_cast<int>(threadId);
 #endif
 }