ArmNN: QuantizedLstmInputParamsBuilder Struct Reference
QuantizedLstmInputParamsBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef QuantizedLstmInputParams Table
Public Member Functions
void add_inputToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights)
void add_inputToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights)
void add_inputToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights)
void add_inputToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights)
void add_recurrentToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights)
void add_recurrentToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights)
void add_recurrentToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights)
void add_recurrentToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights)
void add_inputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias)
void add_forgetGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias)
void add_cellBias (flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias)
void add_outputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias)
QuantizedLstmInputParamsBuilder (flatbuffers::FlatBufferBuilder &_fbb)
QuantizedLstmInputParamsBuilder & operator= (const QuantizedLstmInputParamsBuilder &)
flatbuffers::Offset< QuantizedLstmInputParams > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8140 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef QuantizedLstmInputParams Table
Definition at line 8141 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
QuantizedLstmInputParamsBuilder()
QuantizedLstmInputParamsBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8180 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_cellBias()
void add_cellBias (flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias) inline
Definition at line 8174 of file ArmnnSchema_generated.h.
References VT_CELLBIAS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_CELLBIAS, cellBias);
   }
add_forgetGateBias()
void add_forgetGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias) inline
Definition at line 8171 of file ArmnnSchema_generated.h.
References VT_FORGETGATEBIAS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_FORGETGATEBIAS, forgetGateBias);
   }
add_inputGateBias()
void add_inputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias) inline
Definition at line 8168 of file ArmnnSchema_generated.h.
References VT_INPUTGATEBIAS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_INPUTGATEBIAS, inputGateBias);
   }
add_inputToCellWeights()
void add_inputToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights) inline
Definition at line 8150 of file ArmnnSchema_generated.h.
References VT_INPUTTOCELLWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_INPUTTOCELLWEIGHTS, inputToCellWeights);
   }
add_inputToForgetWeights()
void add_inputToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights) inline
Definition at line 8147 of file ArmnnSchema_generated.h.
References VT_INPUTTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_INPUTTOFORGETWEIGHTS, inputToForgetWeights);
   }
add_inputToInputWeights()
void add_inputToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights) inline
Definition at line 8144 of file ArmnnSchema_generated.h.
References VT_INPUTTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_INPUTTOINPUTWEIGHTS, inputToInputWeights);
   }
add_inputToOutputWeights()
void add_inputToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights) inline
Definition at line 8153 of file ArmnnSchema_generated.h.
References VT_INPUTTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_INPUTTOOUTPUTWEIGHTS, inputToOutputWeights);
   }
add_outputGateBias()
void add_outputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias) inline
Definition at line 8177 of file ArmnnSchema_generated.h.
References VT_OUTPUTGATEBIAS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_OUTPUTGATEBIAS, outputGateBias);
   }
add_recurrentToCellWeights()
void add_recurrentToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights) inline
Definition at line 8162 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOCELLWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_RECURRENTTOCELLWEIGHTS, recurrentToCellWeights);
   }
add_recurrentToForgetWeights()
void add_recurrentToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights) inline
Definition at line 8159 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_RECURRENTTOFORGETWEIGHTS, recurrentToForgetWeights);
   }
add_recurrentToInputWeights()
void add_recurrentToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights) inline
Definition at line 8156 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_RECURRENTTOINPUTWEIGHTS, recurrentToInputWeights);
   }
add_recurrentToOutputWeights()
void add_recurrentToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights) inline
Definition at line 8165 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     fbb_.AddOffset(QuantizedLstmInputParams::VT_RECURRENTTOOUTPUTWEIGHTS, recurrentToOutputWeights);
   }
Finish()
flatbuffers::Offset<QuantizedLstmInputParams> Finish () inline
Definition at line 8185 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateQuantizedLstmInputParams().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<QuantizedLstmInputParams>(end);
     return o;
   }
operator=()
QuantizedLstmInputParamsBuilder& operator= (const QuantizedLstmInputParamsBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8142 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8143 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h