ArmNN: NormalizationDescriptorBuilder Struct Reference
NormalizationDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef NormalizationDescriptor Table
Public Member Functions
void add_normChannelType (armnnSerializer::NormalizationAlgorithmChannel normChannelType)
void add_normMethodType (armnnSerializer::NormalizationAlgorithmMethod normMethodType)
void add_normSize (uint32_t normSize)
void add_alpha (float alpha)
void add_beta (float beta)
void add_k (float k)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
NormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
NormalizationDescriptorBuilder & operator= (const NormalizationDescriptorBuilder &)
flatbuffers::Offset< NormalizationDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5621 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef NormalizationDescriptor Table
Definition at line 5622 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
NormalizationDescriptorBuilder()
NormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5646 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_alpha()
void add_alpha (float alpha) inline
Definition at line 5634 of file ArmnnSchema_generated.h.
References VT_ALPHA.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     fbb_.AddElement<float>(NormalizationDescriptor::VT_ALPHA, alpha, 0.0f);
   }
add_beta()
void add_beta (float beta) inline
Definition at line 5637 of file ArmnnSchema_generated.h.
References VT_BETA.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     fbb_.AddElement<float>(NormalizationDescriptor::VT_BETA, beta, 0.0f);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 5643 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     fbb_.AddElement<int8_t>(NormalizationDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 1);
   }
add_k()
void add_k (float k) inline
Definition at line 5640 of file ArmnnSchema_generated.h.
References VT_K.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
                       {
     fbb_.AddElement<float>(NormalizationDescriptor::VT_K, k, 0.0f);
   }
add_normChannelType()
void add_normChannelType (armnnSerializer::NormalizationAlgorithmChannel normChannelType) inline
Definition at line 5625 of file ArmnnSchema_generated.h.
References VT_NORMCHANNELTYPE.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     fbb_.AddElement<int8_t>(NormalizationDescriptor::VT_NORMCHANNELTYPE, static_cast<int8_t>(normChannelType), 0);
   }
add_normMethodType()
void add_normMethodType (armnnSerializer::NormalizationAlgorithmMethod normMethodType) inline
Definition at line 5628 of file ArmnnSchema_generated.h.
References VT_NORMMETHODTYPE.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     fbb_.AddElement<int8_t>(NormalizationDescriptor::VT_NORMMETHODTYPE, static_cast<int8_t>(normMethodType), 0);
   }
add_normSize()
void add_normSize (uint32_t normSize) inline
Definition at line 5631 of file ArmnnSchema_generated.h.
References VT_NORMSIZE.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     fbb_.AddElement<uint32_t>(NormalizationDescriptor::VT_NORMSIZE, normSize, 0);
   }
Finish()
flatbuffers::Offset<NormalizationDescriptor> Finish () inline
Definition at line 5651 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateNormalizationDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<NormalizationDescriptor>(end);
     return o;
   }
operator=()
NormalizationDescriptorBuilder& operator= (const NormalizationDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5623 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5624 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h