ArmNN: TransposeLayerBuilder Struct Reference
TransposeLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef TransposeLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::TransposeDescriptor > descriptor)
TransposeLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
TransposeLayerBuilder & operator= (const TransposeLayerBuilder &)
flatbuffers::Offset< TransposeLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8658 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef TransposeLayer Table
Definition at line 8659 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
TransposeLayerBuilder()
TransposeLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8668 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 8662 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateTransposeLayer().
{
     fbb_.AddOffset(TransposeLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::TransposeDescriptor > descriptor) inline
Definition at line 8665 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateTransposeLayer().
{
     fbb_.AddOffset(TransposeLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<TransposeLayer> Finish () inline
Definition at line 8673 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateTransposeLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<TransposeLayer>(end);
     return o;
   }
operator=()
TransposeLayerBuilder& operator= (const TransposeLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8660 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8661 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h