ArmNN: DeviceRecord Struct Reference
DeviceRecord Struct Reference
#include <CounterDirectory.hpp>
Public Member Functions
void printContents () const
Static Public Member Functions
static void printHeader ()
Public Attributes
uint16_t m_DeviceUid
uint16_t m_DeviceCores
std::string m_DeviceName
Detailed Description
Definition at line 190 of file CounterDirectory.hpp.
Member Function Documentation
printContents()
void printContents () const inline
Definition at line 214 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting().
Referenced by CounterDirectory::print().
     {
         std::string body;
         body.append(gatordmock::CentreAlignFormatting(m_DeviceName, 20));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_DeviceUid), 13));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_DeviceCores), 10));
         body.append("\n");
         std::cout << std::string(body.size(), '-') << "\n";
         std::cout<< body;
     }
printHeader()
static void printHeader () inline static
Definition at line 196 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting().
Referenced by CounterDirectory::print().
     {
         std::string header;
         header.append(gatordmock::CentreAlignFormatting("Device name", 20));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("UID",13));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Cores",10));
         header.append("\n");
         std::cout << "\n" << "\n";
         std::cout << gatordmock::CentreAlignFormatting("DEVICES", static_cast<int>(header.size()));
         std::cout << "\n";
         std::cout << std::string(header.size(), '=') << "\n";
         std::cout<< header;
     }
Member Data Documentation
m_DeviceCores
uint16_t m_DeviceCores
Definition at line 193 of file CounterDirectory.hpp.
m_DeviceName
std::string m_DeviceName
Definition at line 194 of file CounterDirectory.hpp.
m_DeviceUid
uint16_t m_DeviceUid
Definition at line 192 of file CounterDirectory.hpp.
The documentation for this struct was generated from the following file:
tests/profiling/gatordmock/CounterDirectory.hpp