ArmNN: SelectiveQuantizer< T, DoQuantize > Struct Template Reference
SelectiveQuantizer< T, DoQuantize > Struct Template Reference
#include <QuantizeHelper.hpp>
Static Public Member Functions
static T Quantize (float value, float scale, int32_t offset)
static float Dequantize (T value, float scale, int32_t offset)
Detailed Description
template<typename T, bool DoQuantize = true>
struct armnnUtils::SelectiveQuantizer< T, DoQuantize >
Definition at line 23 of file QuantizeHelper.hpp.
Member Function Documentation
Dequantize()
static float Dequantize (T value, float scale, int32_t offset) inline static
Definition at line 30 of file QuantizeHelper.hpp.
References armnn::Dequantize().
Referenced by armnnUtils::SelectiveDequantize().
     {
         return armnn::Dequantize(value, scale, offset);
     }
Quantize()
static T Quantize (float value, float scale, int32_t offset) inline static
Definition at line 25 of file QuantizeHelper.hpp.
Referenced by armnnUtils::SelectiveQuantize().
     {
         return armnn::Quantize<T>(value, scale, offset);
     }
The documentation for this struct was generated from the following file:
src/armnnUtils/QuantizeHelper.hpp