ArmNN: EventRecord Struct Reference
EventRecord Struct Reference
#include <CounterDirectory.hpp>
Public Member Functions
void printContents () const
Static Public Member Functions
static void printHeader (std::string categoryName)
Public Attributes
uint16_t m_CounterUid
uint16_t m_MaxCounterUid
uint16_t m_DeviceUid
uint16_t m_CounterSetUid
uint16_t m_CounterClass
uint16_t m_CounterInterpolation
double m_CounterMultiplier
std::string m_CounterName
std::string m_CounterDescription
std::string m_CounterUnits
Detailed Description
Definition at line 30 of file CounterDirectory.hpp.
Member Function Documentation
printContents()
void printContents () const inline
Definition at line 76 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting().
Referenced by CategoryRecord::print().
     {
         std::string body;
         body.append(gatordmock::CentreAlignFormatting(m_CounterName, 20));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(m_CounterDescription, 50));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(m_CounterUnits, 14));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterUid), 6));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_MaxCounterUid), 10));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterClass), 8));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterInterpolation), 14));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterMultiplier), 20));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_CounterSetUid), 16));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_DeviceUid), 14));
         body.append("\n");
         std::cout << std::string(body.size(), '-') << "\n";
         std::cout << body;
     }
printHeader()
static void printHeader (std::string categoryName) inline static
Definition at line 43 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting().
Referenced by CategoryRecord::print().
     {
         std::string header;
         header.append(gatordmock::CentreAlignFormatting("Counter Name", 20));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Description", 50));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Units", 14));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("UID", 6));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Max UID",10));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Class", 8));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Interpolation", 14));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Multiplier", 20));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Counter set UID", 16));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Device UID", 14));
         header.append("\n");
         std::cout << "\n" << "\n";
         std::cout << gatordmock::CentreAlignFormatting("EVENTS IN CATEGORY: " + categoryName,
                                                        static_cast<int>(header.size()));
         std::cout << "\n";
         std::cout << std::string(header.size(), '=') << "\n";
         std::cout << header;
     }
Member Data Documentation
m_CounterClass
uint16_t m_CounterClass
Definition at line 36 of file CounterDirectory.hpp.
m_CounterDescription
std::string m_CounterDescription
Definition at line 40 of file CounterDirectory.hpp.
m_CounterInterpolation
uint16_t m_CounterInterpolation
Definition at line 37 of file CounterDirectory.hpp.
m_CounterMultiplier
double m_CounterMultiplier
Definition at line 38 of file CounterDirectory.hpp.
m_CounterName
std::string m_CounterName
Definition at line 39 of file CounterDirectory.hpp.
m_CounterSetUid
uint16_t m_CounterSetUid
Definition at line 35 of file CounterDirectory.hpp.
m_CounterUid
uint16_t m_CounterUid
Definition at line 32 of file CounterDirectory.hpp.
m_CounterUnits
std::string m_CounterUnits
Definition at line 41 of file CounterDirectory.hpp.
m_DeviceUid
uint16_t m_DeviceUid
Definition at line 34 of file CounterDirectory.hpp.
m_MaxCounterUid
uint16_t m_MaxCounterUid
Definition at line 33 of file CounterDirectory.hpp.
The documentation for this struct was generated from the following file:
tests/profiling/gatordmock/CounterDirectory.hpp