ArmNN: SpaceToDepthLayerBuilder Struct Reference
SpaceToDepthLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SpaceToDepthLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::SpaceToDepthDescriptor > descriptor)
SpaceToDepthLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SpaceToDepthLayerBuilder & operator= (const SpaceToDepthLayerBuilder &)
flatbuffers::Offset< SpaceToDepthLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5263 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SpaceToDepthLayer Table
Definition at line 5264 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SpaceToDepthLayerBuilder()
SpaceToDepthLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5273 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 5267 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateSpaceToDepthLayer().
{
     fbb_.AddOffset(SpaceToDepthLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::SpaceToDepthDescriptor > descriptor) inline
Definition at line 5270 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateSpaceToDepthLayer().
{
     fbb_.AddOffset(SpaceToDepthLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<SpaceToDepthLayer> Finish () inline
Definition at line 5278 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSpaceToDepthLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SpaceToDepthLayer>(end);
     return o;
   }
operator=()
SpaceToDepthLayerBuilder& operator= (const SpaceToDepthLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5265 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5266 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h