ArmNN: StackLayerBuilder Struct Reference
StackLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef StackLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::StackDescriptor > descriptor)
StackLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
StackLayerBuilder & operator= (const StackLayerBuilder &)
flatbuffers::Offset< StackLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8910 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef StackLayer Table
Definition at line 8911 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
StackLayerBuilder()
StackLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8920 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 8914 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateStackLayer().
{
     fbb_.AddOffset(StackLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::StackDescriptor > descriptor) inline
Definition at line 8917 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateStackLayer().
{
     fbb_.AddOffset(StackLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<StackLayer> Finish () inline
Definition at line 8925 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateStackLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<StackLayer>(end);
     return o;
   }
operator=()
StackLayerBuilder& operator= (const StackLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8912 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8913 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h