ArmNN: ResizeBilinearDescriptorBuilder Struct Reference
ResizeBilinearDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ResizeBilinearDescriptor Table
Public Member Functions
void add_targetWidth (uint32_t targetWidth)
void add_targetHeight (uint32_t targetHeight)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
void add_alignCorners (bool alignCorners)
void add_halfPixelCenters (bool halfPixelCenters)
ResizeBilinearDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ResizeBilinearDescriptorBuilder & operator= (const ResizeBilinearDescriptorBuilder &)
flatbuffers::Offset< ResizeBilinearDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6198 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ResizeBilinearDescriptor Table
Definition at line 6199 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ResizeBilinearDescriptorBuilder()
ResizeBilinearDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6217 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_alignCorners()
void add_alignCorners (bool alignCorners) inline
Definition at line 6211 of file ArmnnSchema_generated.h.
References VT_ALIGNCORNERS.
Referenced by armnnSerializer::CreateResizeBilinearDescriptor().
{
     fbb_.AddElement<uint8_t>(ResizeBilinearDescriptor::VT_ALIGNCORNERS, static_cast<uint8_t>(alignCorners), 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 6208 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateResizeBilinearDescriptor().
{
     fbb_.AddElement<int8_t>(ResizeBilinearDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_halfPixelCenters()
void add_halfPixelCenters (bool halfPixelCenters) inline
Definition at line 6214 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateResizeBilinearDescriptor().
{
     fbb_.AddElement<uint8_t>(ResizeBilinearDescriptor::VT_HALFPIXELCENTERS, static_cast<uint8_t>(halfPixelCenters), 0);
   }
add_targetHeight()
void add_targetHeight (uint32_t targetHeight) inline
Definition at line 6205 of file ArmnnSchema_generated.h.
References VT_TARGETHEIGHT.
Referenced by armnnSerializer::CreateResizeBilinearDescriptor().
{
     fbb_.AddElement<uint32_t>(ResizeBilinearDescriptor::VT_TARGETHEIGHT, targetHeight, 0);
   }
add_targetWidth()
void add_targetWidth (uint32_t targetWidth) inline
Definition at line 6202 of file ArmnnSchema_generated.h.
References VT_TARGETWIDTH.
Referenced by armnnSerializer::CreateResizeBilinearDescriptor().
{
     fbb_.AddElement<uint32_t>(ResizeBilinearDescriptor::VT_TARGETWIDTH, targetWidth, 0);
   }
Finish()
flatbuffers::Offset<ResizeBilinearDescriptor> Finish () inline
Definition at line 6222 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateResizeBilinearDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ResizeBilinearDescriptor>(end);
     return o;
   }
operator=()
ResizeBilinearDescriptorBuilder& operator= (const ResizeBilinearDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6200 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6201 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h