ArmNN: Convolution2dDescriptorBuilder Struct Reference
Convolution2dDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Convolution2dDescriptor Table
Public Member Functions
void add_padLeft (uint32_t padLeft)
void add_padRight (uint32_t padRight)
void add_padTop (uint32_t padTop)
void add_padBottom (uint32_t padBottom)
void add_strideX (uint32_t strideX)
void add_strideY (uint32_t strideY)
void add_dilationX (uint32_t dilationX)
void add_dilationY (uint32_t dilationY)
void add_biasEnabled (bool biasEnabled)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
Convolution2dDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Convolution2dDescriptorBuilder & operator= (const Convolution2dDescriptorBuilder &)
flatbuffers::Offset< Convolution2dDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2927 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Convolution2dDescriptor Table
Definition at line 2928 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Convolution2dDescriptorBuilder()
Convolution2dDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2961 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_biasEnabled()
void add_biasEnabled (bool biasEnabled) inline
Definition at line 2955 of file ArmnnSchema_generated.h.
References VT_BIASENABLED.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint8_t>(Convolution2dDescriptor::VT_BIASENABLED, static_cast<uint8_t>(biasEnabled), 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 2958 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<int8_t>(Convolution2dDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 1);
   }
add_dilationX()
void add_dilationX (uint32_t dilationX) inline
Definition at line 2949 of file ArmnnSchema_generated.h.
References VT_DILATIONX.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_DILATIONX, dilationX, 1);
   }
add_dilationY()
void add_dilationY (uint32_t dilationY) inline
Definition at line 2952 of file ArmnnSchema_generated.h.
References VT_DILATIONY.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_DILATIONY, dilationY, 1);
   }
add_padBottom()
void add_padBottom (uint32_t padBottom) inline
Definition at line 2940 of file ArmnnSchema_generated.h.
References VT_PADBOTTOM.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_PADBOTTOM, padBottom, 0);
   }
add_padLeft()
void add_padLeft (uint32_t padLeft) inline
Definition at line 2931 of file ArmnnSchema_generated.h.
References VT_PADLEFT.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_PADLEFT, padLeft, 0);
   }
add_padRight()
void add_padRight (uint32_t padRight) inline
Definition at line 2934 of file ArmnnSchema_generated.h.
References VT_PADRIGHT.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_PADRIGHT, padRight, 0);
   }
add_padTop()
void add_padTop (uint32_t padTop) inline
Definition at line 2937 of file ArmnnSchema_generated.h.
References VT_PADTOP.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_PADTOP, padTop, 0);
   }
add_strideX()
void add_strideX (uint32_t strideX) inline
Definition at line 2943 of file ArmnnSchema_generated.h.
References VT_STRIDEX.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_STRIDEX, strideX, 0);
   }
add_strideY()
void add_strideY (uint32_t strideY) inline
Definition at line 2946 of file ArmnnSchema_generated.h.
References VT_STRIDEY.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     fbb_.AddElement<uint32_t>(Convolution2dDescriptor::VT_STRIDEY, strideY, 0);
   }
Finish()
flatbuffers::Offset<Convolution2dDescriptor> Finish () inline
Definition at line 2966 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConvolution2dDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Convolution2dDescriptor>(end);
     return o;
   }
operator=()
Convolution2dDescriptorBuilder& operator= (const Convolution2dDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2929 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2930 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h