ArmNN: ArgMinMaxLayerBuilder Struct Reference
ArgMinMaxLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ArgMinMaxLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::ArgMinMaxDescriptor > descriptor)
ArgMinMaxLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ArgMinMaxLayerBuilder & operator= (const ArgMinMaxLayerBuilder &)
flatbuffers::Offset< ArgMinMaxLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2557 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ArgMinMaxLayer Table
Definition at line 2558 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ArgMinMaxLayerBuilder()
ArgMinMaxLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2567 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 2561 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateArgMinMaxLayer().
{
     fbb_.AddOffset(ArgMinMaxLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::ArgMinMaxDescriptor > descriptor) inline
Definition at line 2564 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateArgMinMaxLayer().
{
     fbb_.AddOffset(ArgMinMaxLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<ArgMinMaxLayer> Finish () inline
Definition at line 2572 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateArgMinMaxLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ArgMinMaxLayer>(end);
     return o;
   }
operator=()
ArgMinMaxLayerBuilder& operator= (const ArgMinMaxLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2559 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2560 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h