ArmNN: IQuantizationScheme Struct Reference
IQuantizationScheme Struct Reference abstract
#include <NetworkQuantizationScheme.hpp>
Public Member Functions
virtual OffsetScalePair ComputeScheme (double min, double max) const =0
virtual int NumBits () const =0
virtual DataType GetDataType () const =0
virtual ~IQuantizationScheme ()
Detailed Description
Definition at line 18 of file NetworkQuantizationScheme.hpp.
Constructor & Destructor Documentation
~IQuantizationScheme()
virtual ~IQuantizationScheme () inline virtual
Definition at line 26 of file NetworkQuantizationScheme.hpp.
 {}
Member Function Documentation
ComputeScheme()
virtual OffsetScalePair ComputeScheme (double min, double max) const pure virtual
Implemented in QSymm16QuantizationScheme, QSymmS8QuantizationScheme, QAsymmS8QuantizationScheme, and QAsymmU8QuantizationScheme.
Referenced by QuantizerStrategy::QuantizerStrategy().
GetDataType()
virtual DataType GetDataType () const pure virtual
Implemented in QSymm16QuantizationScheme, QSymmS8QuantizationScheme, QAsymmS8QuantizationScheme, and QAsymmU8QuantizationScheme.
Referenced by QuantizerStrategy::QuantizerStrategy().
NumBits()
virtual int NumBits () const pure virtual
Implemented in QSymm16QuantizationScheme, QSymmS8QuantizationScheme, QAsymmS8QuantizationScheme, and QAsymmU8QuantizationScheme.
Referenced by QAsymmU8QuantizationScheme::ComputeScheme(), QAsymmS8QuantizationScheme::ComputeScheme(), QSymmS8QuantizationScheme::ComputeScheme(), and QSymm16QuantizationScheme::ComputeScheme().
The documentation for this struct was generated from the following file:
src/armnn/NetworkQuantizationScheme.hpp