ArmNN: DetectionPostProcessLayerBuilder Struct Reference
DetectionPostProcessLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef DetectionPostProcessLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::DetectionPostProcessDescriptor > descriptor)
void add_anchors (flatbuffers::Offset< armnnSerializer::ConstTensor > anchors)
DetectionPostProcessLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
DetectionPostProcessLayerBuilder & operator= (const DetectionPostProcessLayerBuilder &)
flatbuffers::Offset< DetectionPostProcessLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6969 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef DetectionPostProcessLayer Table
Definition at line 6970 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
DetectionPostProcessLayerBuilder()
DetectionPostProcessLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6982 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_anchors()
void add_anchors (flatbuffers::Offset< armnnSerializer::ConstTensor > anchors) inline
Definition at line 6979 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDetectionPostProcessLayer().
{
     fbb_.AddOffset(DetectionPostProcessLayer::VT_ANCHORS, anchors);
   }
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 6973 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateDetectionPostProcessLayer().
{
     fbb_.AddOffset(DetectionPostProcessLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::DetectionPostProcessDescriptor > descriptor) inline
Definition at line 6976 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateDetectionPostProcessLayer().
{
     fbb_.AddOffset(DetectionPostProcessLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<DetectionPostProcessLayer> Finish () inline
Definition at line 6987 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDetectionPostProcessLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<DetectionPostProcessLayer>(end);
     return o;
   }
operator=()
DetectionPostProcessLayerBuilder& operator= (const DetectionPostProcessLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6971 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6972 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h