ArmNN: ResizeLayerBuilder Struct Reference
ResizeLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ResizeLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::ResizeDescriptor > descriptor)
ResizeLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ResizeLayerBuilder & operator= (const ResizeLayerBuilder &)
flatbuffers::Offset< ResizeLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8764 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ResizeLayer Table
Definition at line 8765 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ResizeLayerBuilder()
ResizeLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8774 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 8768 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateResizeLayer().
{
     fbb_.AddOffset(ResizeLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::ResizeDescriptor > descriptor) inline
Definition at line 8771 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateResizeLayer().
{
     fbb_.AddOffset(ResizeLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<ResizeLayer> Finish () inline
Definition at line 8779 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateResizeLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ResizeLayer>(end);
     return o;
   }
operator=()
ResizeLayerBuilder& operator= (const ResizeLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8766 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8767 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h