ArmNN: BatchNormalizationLayerBuilder Struct Reference
BatchNormalizationLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef BatchNormalizationLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::BatchNormalizationDescriptor > descriptor)
void add_mean (flatbuffers::Offset< armnnSerializer::ConstTensor > mean)
void add_variance (flatbuffers::Offset< armnnSerializer::ConstTensor > variance)
void add_beta (flatbuffers::Offset< armnnSerializer::ConstTensor > beta)
void add_gamma (flatbuffers::Offset< armnnSerializer::ConstTensor > gamma)
BatchNormalizationLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
BatchNormalizationLayerBuilder & operator= (const BatchNormalizationLayerBuilder &)
flatbuffers::Offset< BatchNormalizationLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6004 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef BatchNormalizationLayer Table
Definition at line 6005 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
BatchNormalizationLayerBuilder()
BatchNormalizationLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6026 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 6008 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     fbb_.AddOffset(BatchNormalizationLayer::VT_BASE, base);
   }
add_beta()
void add_beta (flatbuffers::Offset< armnnSerializer::ConstTensor > beta) inline
Definition at line 6020 of file ArmnnSchema_generated.h.
References VT_BETA.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     fbb_.AddOffset(BatchNormalizationLayer::VT_BETA, beta);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::BatchNormalizationDescriptor > descriptor) inline
Definition at line 6011 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     fbb_.AddOffset(BatchNormalizationLayer::VT_DESCRIPTOR, descriptor);
   }
add_gamma()
void add_gamma (flatbuffers::Offset< armnnSerializer::ConstTensor > gamma) inline
Definition at line 6023 of file ArmnnSchema_generated.h.
References VT_GAMMA.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     fbb_.AddOffset(BatchNormalizationLayer::VT_GAMMA, gamma);
   }
add_mean()
void add_mean (flatbuffers::Offset< armnnSerializer::ConstTensor > mean) inline
Definition at line 6014 of file ArmnnSchema_generated.h.
References VT_MEAN.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     fbb_.AddOffset(BatchNormalizationLayer::VT_MEAN, mean);
   }
add_variance()
void add_variance (flatbuffers::Offset< armnnSerializer::ConstTensor > variance) inline
Definition at line 6017 of file ArmnnSchema_generated.h.
References VT_VARIANCE.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     fbb_.AddOffset(BatchNormalizationLayer::VT_VARIANCE, variance);
   }
Finish()
flatbuffers::Offset<BatchNormalizationLayer> Finish () inline
Definition at line 6031 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateBatchNormalizationLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<BatchNormalizationLayer>(end);
     return o;
   }
operator=()
BatchNormalizationLayerBuilder& operator= (const BatchNormalizationLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6006 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6007 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h