ArmNN: LogSoftmaxDescriptorBuilder Struct Reference
LogSoftmaxDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef LogSoftmaxDescriptor Table
Public Member Functions
void add_beta (float beta)
void add_axis (int32_t axis)
LogSoftmaxDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
LogSoftmaxDescriptorBuilder & operator= (const LogSoftmaxDescriptorBuilder &)
flatbuffers::Offset< LogSoftmaxDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 3938 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef LogSoftmaxDescriptor Table
Definition at line 3939 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
LogSoftmaxDescriptorBuilder()
LogSoftmaxDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3948 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_axis()
void add_axis (int32_t axis) inline
Definition at line 3945 of file ArmnnSchema_generated.h.
References VT_AXIS.
Referenced by armnnSerializer::CreateLogSoftmaxDescriptor().
{
     fbb_.AddElement<int32_t>(LogSoftmaxDescriptor::VT_AXIS, axis, -1);
   }
add_beta()
void add_beta (float beta) inline
Definition at line 3942 of file ArmnnSchema_generated.h.
References VT_BETA.
Referenced by armnnSerializer::CreateLogSoftmaxDescriptor().
{
     fbb_.AddElement<float>(LogSoftmaxDescriptor::VT_BETA, beta, 1.0f);
   }
Finish()
flatbuffers::Offset<LogSoftmaxDescriptor> Finish () inline
Definition at line 3953 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLogSoftmaxDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<LogSoftmaxDescriptor>(end);
     return o;
   }
operator=()
LogSoftmaxDescriptorBuilder& operator= (const LogSoftmaxDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 3940 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 3941 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h