ArmNN: PadDescriptorBuilder Struct Reference
PadDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef PadDescriptor Table
Public Member Functions
void add_padList (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList)
void add_padValue (float padValue)
PadDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
PadDescriptorBuilder & operator= (const PadDescriptorBuilder &)
flatbuffers::Offset< PadDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5871 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef PadDescriptor Table
Definition at line 5872 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
PadDescriptorBuilder()
PadDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5881 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_padList()
void add_padList (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList) inline
Definition at line 5875 of file ArmnnSchema_generated.h.
References VT_PADLIST.
Referenced by armnnSerializer::CreatePadDescriptor().
{
     fbb_.AddOffset(PadDescriptor::VT_PADLIST, padList);
   }
add_padValue()
void add_padValue (float padValue) inline
Definition at line 5878 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePadDescriptor().
{
     fbb_.AddElement<float>(PadDescriptor::VT_PADVALUE, padValue, 0.0f);
   }
Finish()
flatbuffers::Offset<PadDescriptor> Finish () inline
Definition at line 5886 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePadDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<PadDescriptor>(end);
     return o;
   }
operator=()
PadDescriptorBuilder& operator= (const PadDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5873 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5874 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h