ArmNN: MergerLayerBuilder Struct Reference
MergerLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef MergerLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::OriginsDescriptor > descriptor)
MergerLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
MergerLayerBuilder & operator= (const MergerLayerBuilder &)
flatbuffers::Offset< MergerLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 6648 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef MergerLayer Table
Definition at line 6649 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
MergerLayerBuilder()
MergerLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 6658 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 6652 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateMergerLayer().
{
     fbb_.AddOffset(MergerLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::OriginsDescriptor > descriptor) inline
Definition at line 6655 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateMergerLayer().
{
     fbb_.AddOffset(MergerLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<MergerLayer> Finish () inline
Definition at line 6663 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateMergerLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<MergerLayer>(end);
     return o;
   }
operator=()
MergerLayerBuilder& operator= (const MergerLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 6650 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 6651 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h