ArmNN: ActivationDescriptorBuilder Struct Reference
ActivationDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ActivationDescriptor Table
Public Member Functions
void add_activationFunction (armnnSerializer::ActivationFunction activationFunction)
void add_a (float a)
void add_b (float b)
ActivationDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ActivationDescriptorBuilder & operator= (const ActivationDescriptorBuilder &)
flatbuffers::Offset< ActivationDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2455 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ActivationDescriptor Table
Definition at line 2456 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ActivationDescriptorBuilder()
ActivationDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2468 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_a()
void add_a (float a) inline
Definition at line 2462 of file ArmnnSchema_generated.h.
References VT_A.
Referenced by armnnSerializer::CreateActivationDescriptor().
                       {
     fbb_.AddElement<float>(ActivationDescriptor::VT_A, a, 0.0f);
   }
add_activationFunction()
void add_activationFunction (armnnSerializer::ActivationFunction activationFunction) inline
Definition at line 2459 of file ArmnnSchema_generated.h.
References VT_ACTIVATIONFUNCTION.
Referenced by armnnSerializer::CreateActivationDescriptor().
{
     fbb_.AddElement<int8_t>(ActivationDescriptor::VT_ACTIVATIONFUNCTION, static_cast<int8_t>(activationFunction), 0);
   }
add_b()
void add_b (float b) inline
Definition at line 2465 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateActivationDescriptor().
                       {
     fbb_.AddElement<float>(ActivationDescriptor::VT_B, b, 0.0f);
   }
Finish()
flatbuffers::Offset<ActivationDescriptor> Finish () inline
Definition at line 2473 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateActivationDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ActivationDescriptor>(end);
     return o;
   }
operator=()
ActivationDescriptorBuilder& operator= (const ActivationDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2457 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2458 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h