ArmNN: src/backends/backendsCommon/test/BackendRegistryTests.cpp File Reference
BackendRegistryTests.cpp File Reference
#include <armnn/Types.hpp>
#include <armnn/BackendRegistry.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <reference/RefBackend.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (SwapRegistry)
BOOST_AUTO_TEST_CASE (TestRegistryHelper)
BOOST_AUTO_TEST_CASE (TestDirectCallToRegistry)
BOOST_AUTO_TEST_CASE (ThrowBackendUnavailableException)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (SwapRegistry)
Definition at line 38 of file BackendRegistryTests.cpp.
References armnn::BackendRegistryInstance(), and BackendRegistry::Size().
 {
     using namespace armnn;
     auto nFactories = BackendRegistryInstance().Size();
     {
         SwapRegistryStorage helper;
         BOOST_TEST(BackendRegistryInstance().Size() == 0);
     }
     BOOST_TEST(BackendRegistryInstance().Size() == nFactories);
 }
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (TestRegistryHelper)
Definition at line 49 of file BackendRegistryTests.cpp.
References armnn::BackendRegistryInstance(), BackendRegistry::Deregister(), and BackendRegistry::GetFactory().
 {
     using namespace armnn;
     SwapRegistryStorage helper;
     bool called = false;
     BackendRegistry::StaticRegistryInitializer factoryHelper(
         BackendRegistryInstance(),
         "HelloWorld",
         [&called]()
         {
             called = true;
             return armnn::IBackendInternalUniquePtr(nullptr);
         }
     );
     // sanity check: the factory has not been called yet
     BOOST_TEST(called == false);
     auto factoryFunction = BackendRegistryInstance().GetFactory("HelloWorld");
     // sanity check: the factory still not called
     BOOST_TEST(called == false);
     factoryFunction();
     BOOST_TEST(called == true);
     BackendRegistryInstance().Deregister("HelloWorld");
 }
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (TestDirectCallToRegistry)
Definition at line 79 of file BackendRegistryTests.cpp.
References armnn::BackendRegistryInstance(), BackendRegistry::Deregister(), BackendRegistry::GetFactory(), and BackendRegistry::Register().
 {
     using namespace armnn;
     SwapRegistryStorage helper;
     bool called = false;
     BackendRegistryInstance().Register(
         "HelloWorld",
         [&called]()
         {
             called = true;
             return armnn::IBackendInternalUniquePtr(nullptr);
         }
     );
     // sanity check: the factory has not been called yet
     BOOST_TEST(called == false);
     auto factoryFunction = BackendRegistryInstance().GetFactory("HelloWorld");
     // sanity check: the factory still not called
     BOOST_TEST(called == false);
     factoryFunction();
     BOOST_TEST(called == true);
     BackendRegistryInstance().Deregister("HelloWorld");
 }
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (ThrowBackendUnavailableException)
Definition at line 114 of file BackendRegistryTests.cpp.
References ARMNN_LOG, armnn::BackendRegistryInstance(), BOOST_AUTO_TEST_SUITE_END(), BackendRegistry::GetFactory(), armnn::info, BackendRegistry::Register(), and Exception::what().
 {
     using namespace armnn;
     const BackendId mockBackendId("MockDynamicBackend");
     const std::string exceptionMessage("Neon support not found on device, could not register CpuAcc Backend.\n");
     // Register the mock backend with a factory function lambda equivalent to NeonRegisterInitializer
     BackendRegistryInstance().Register(mockBackendId,
             [exceptionMessage]()
             {
                 if (false)
                 {
                     return IBackendInternalUniquePtr(new RefBackend);
                 }
                 ARMNN_LOG(info) << "Neon support not found on device, could not register CpuAcc Backend.";
                 throw armnn::BackendUnavailableException(exceptionMessage);
             });
     // Get the factory function of the mock backend
     auto factoryFunc = BackendRegistryInstance().GetFactory(mockBackendId);
     try
     {
         // Call the factory function as done during runtime backend registering
         auto backend = factoryFunc();
     }
     catch (const BackendUnavailableException& e)
     {
         // Caught
         BOOST_CHECK_EQUAL(e.what(), exceptionMessage);
         BOOST_TEST_MESSAGE("ThrowBackendUnavailableExceptionImpl: BackendUnavailableException caught.");
     }
 }