ArmNN: src/backends/backendsCommon/test/layerTests/FullyConnectedTestImpl.hpp File Reference
FullyConnectedTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <ResolveType.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
template<armnn::DataType ArmnnType, typename T = armnn::ResolveType<ArmnnType>>
LayerTestResult< T, 2 > FullyConnectedTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, bool constantWeights)
LayerTestResult< float, 2 > FullyConnectedFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, bool transposeWeights)
LayerTestResult< float, 2 > FullyConnectedLargeTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool transposeWeights)
Function Documentation
FullyConnectedFloat32Test()
LayerTestResult<float, 2> FullyConnectedFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, bool transposeWeights)
Definition at line 334 of file FullyConnectedTestImpl.cpp.
References armnn::Float32, LayerTestResult< T, n >::outputExpected, and armnn::swap().
 {
     unsigned int inputWidth = 1;
     unsigned int inputHeight = 1;
     unsigned int inputChannels = 5;
     unsigned int inputNum = 2;
     unsigned int outputChannels = 3;
     unsigned int outputNum = 2;
     // Define the tensor descriptors.
     armnn::TensorInfo inputTensorInfo;
     armnn::TensorInfo outputTensorInfo;
     armnn::TensorInfo weightsDesc;
     armnn::TensorInfo biasesDesc;
     unsigned int inputShape[]   = { inputNum, inputChannels, inputHeight, inputWidth };
     unsigned int outputShape[]  = { outputNum, outputChannels };
     unsigned int weightsShape[] = { inputChannels, outputChannels };
     if (transposeWeights)
     {
         std::swap(weightsShape[0], weightsShape[1]);
     }
     unsigned int biasShape[] = { outputChannels };
     inputTensorInfo = armnn::TensorInfo(4, inputShape, armnn::DataType::Float32);
     outputTensorInfo = armnn::TensorInfo(2, outputShape, armnn::DataType::Float32);
     weightsDesc = armnn::TensorInfo(2, weightsShape, armnn::DataType::Float32);
     biasesDesc = armnn::TensorInfo(1, biasShape, armnn::DataType::Float32);
     LayerTestResult<float, 2> result(outputTensorInfo);
     boost::multi_array<float, 4> input = MakeTensor<float, 4>(inputTensorInfo, std::vector<float>(
         {
             1.0f, 2.0f, 3.0f, 4.0f, 5.0f,
             5.0f, 4.0f, 3.0f, 2.0f, 1.0f
         })
     );
     boost::multi_array<float, 2> weights = MakeTensor<float, 2>(weightsDesc, std::vector<float>(
         {
             .5f, 2.f, .5f,
             .5f, 2.f, 1.f,
             .5f, 2.f, 2.f,
             .5f, 2.f, 3.f,
             .5f, 2.f, 4.f
         }));
     if (transposeWeights)
     {
         weights = MakeTensor<float, 2>(weightsDesc, std::vector<float>(
         {
             .5f, .5f, .5f, .5f, .5f,
             2.f, 2.f, 2.f, 2.f, 2.f,
             .5f, 1.f, 2.f, 3.f, 4.f
         }));
     }
     std::vector<float> biasValues({0.f, 0.f, 0.f});
     if (biasEnabled)
     {
         biasValues =  std::vector<float>({10.f, 20.f, 30.f});
     }
     boost::multi_array<float, 1> bias = MakeTensor<float, 1>(biasesDesc, biasValues);
     result = SimpleFullyConnectedTestImpl<float>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo, outputTensorInfo,
         weightsDesc, biasesDesc,
         weights, bias, input,
         biasEnabled, transposeWeights
     );
     result.outputExpected = MakeTensor<float, 2>(outputTensorInfo, std::vector<float>(
         {
             0.5f + 1.0f + 1.5f + 2.0f + 2.5f + biasValues[0],
             2.0f + 4.0f + 6.0f + 8.0f + 10.f + biasValues[1],
             0.5f + 2.0f + 6.0f + 12.f + 20.f + biasValues[2],
             2.5f + 2.0f + 1.5f + 1.0f + 0.5f + biasValues[0],
             10.0f + 8.0f + 6.0f + 4.0f + 2.f + biasValues[1],
             2.5f + 4.0f + 6.0f + 6.f + 4.f   + biasValues[2]
         })
     );
     return result;
 }
FullyConnectedLargeTest()
LayerTestResult<float, 2> FullyConnectedLargeTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool transposeWeights)
Definition at line 433 of file FullyConnectedTestImpl.cpp.
 {
     return FullyConnectedLargeTestCommon<armnn::DataType::Float32>(workloadFactory,
                                                                    memoryManager,
                                                                    tensorHandleFactory,
                                                                    transposeWeights);
 }
FullyConnectedTest()
LayerTestResult<T, 2> FullyConnectedTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, bool constantWeights)
Definition at line 128 of file FullyConnectedTestImpl.cpp.
References armnn::GetBiasTypeFromWeightsType(), LayerTestResult< T, n >::outputExpected, and TensorInfo::SetQuantizationScale().
Referenced by armnn::GetVector().
 {
     constexpr static unsigned int inputWidth = 3u;
     constexpr static unsigned int inputHeight = 2u;
     constexpr static unsigned int inputChannels = 1u;
     constexpr static unsigned int inputSize = inputWidth * inputHeight * inputChannels;
     constexpr static unsigned int outputChannels = 2u;
     armnn::TensorInfo inputTensorInfo({ 1, inputChannels, inputHeight, inputWidth }, ArmnnType);
     inputTensorInfo.SetQuantizationScale(0.1f);
     inputTensorInfo.SetQuantizationOffset(63);
     armnn::TensorInfo outputTensorInfo({ 1, outputChannels }, ArmnnType);
     outputTensorInfo.SetQuantizationScale(5.f);
     outputTensorInfo.SetQuantizationOffset(biasEnabled ? -50 : 10);
     armnn::TensorInfo weightsDesc({ outputChannels, inputSize }, ArmnnType);
     weightsDesc.SetQuantizationScale(0.2f);
     weightsDesc.SetQuantizationOffset(93);
     armnn::TensorInfo biasesDesc({ outputChannels }, GetBiasTypeFromWeightsType(weightsDesc.GetDataType()).value());
     biasesDesc.SetQuantizationScale(inputTensorInfo.GetQuantizationScale() * weightsDesc.GetQuantizationScale());
     biasesDesc.SetQuantizationOffset(0);
     LayerTestResult<T, 2> result(outputTensorInfo);
     auto input = MakeTensor<T, 4>(inputTensorInfo, ConvertToDataType<ArmnnType>(
         {
             -1.2f, 6.1f, -3.5f,
             18.8f, -5.5f, 2.9f
         },
         inputTensorInfo));
     auto weights = MakeTensor<T, 2>(weightsDesc, ConvertToDataType<ArmnnType>(
         {
             -8.4f, 20.0f, -10.4f, -8, 16.4f, -11.8f,
             23.4f, 10.4f, -14.0f, -3.8f, -11.8f, 11.4f
         },
         weightsDesc));
     auto bias = MakeTensor<int32_t, 1>(biasesDesc, std::vector<int32_t>{9250, 67500});
     if (constantWeights)
     {
         result = SimpleFullyConnectedTestImpl<T>(workloadFactory,
                                                  memoryManager,
                                                  tensorHandleFactory,
                                                  inputTensorInfo,
                                                  outputTensorInfo,
                                                  weightsDesc,
                                                  biasesDesc,
                                                  weights,
                                                  bias,
                                                  input,
                                                  biasEnabled,
                                                  true);
     }
     else
     {
         result = SimpleFullyConnectedTestWeightsAsInputsImpl<T>(workloadFactory,
                                                  memoryManager,
                                                  tensorHandleFactory,
                                                  inputTensorInfo,
                                                  outputTensorInfo,
                                                  weightsDesc,
                                                  biasesDesc,
                                                  weights,
                                                  bias,
                                                  input,
                                                  biasEnabled,
                                                  true);
     }
     if (biasEnabled)
     {
         result.outputExpected = MakeTensor<T, 2>(outputTensorInfo,
                                                  ConvertToDataType<ArmnnType>({80.f, 1460.f}, outputTensorInfo));
     }
     else
     {
         result.outputExpected = MakeTensor<T, 2>(outputTensorInfo,
                                                  ConvertToDataType<ArmnnType>({-107.04f, 110.f}, outputTensorInfo));
     }
     return result;
 }