ArmNN: src/armnn/test/ModelAccuracyCheckerTest.cpp File Reference
ModelAccuracyCheckerTest.cpp File Reference
#include "ModelAccuracyChecker.hpp"
#include <boost/test/unit_test.hpp>
#include <iostream>
#include <string>
Typedefs
using TContainer = mapbox::util::variant< std::vector< float >, std::vector< int >, std::vector< unsigned char >, std::vector< int8_t > >
Functions
BOOST_FIXTURE_TEST_CASE (TestFloat32OutputTensorAccuracy, TestHelper)
Typedef Documentation
TContainer
using TContainer = mapbox::util::variant<std::vector<float>, std::vector<int>, std::vector<unsigned char>, std::vector<int8_t> >
Definition at line 56 of file ModelAccuracyCheckerTest.cpp.
Function Documentation
BOOST_FIXTURE_TEST_CASE()
BOOST_FIXTURE_TEST_CASE (TestFloat32OutputTensorAccuracy , TestHelper)
Definition at line 58 of file ModelAccuracyCheckerTest.cpp.
References ModelAccuracyChecker::AddImageResult(), BOOST_AUTO_TEST_SUITE_END(), and ModelAccuracyChecker::GetAccuracy().
 {
     ModelAccuracyChecker checker(GetValidationLabelSet(), GetModelOutputLabels());
     // Add image 1 and check accuracy
     std::vector<float> inferenceOutputVector1 = {0.05f, 0.10f, 0.70f, 0.15f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
     TContainer inference1Container(inferenceOutputVector1);
     std::vector<TContainer> outputTensor1;
     outputTensor1.push_back(inference1Container);
     std::string imageName = "val_01.JPEG";
     checker.AddImageResult<TContainer>(imageName, outputTensor1);
     // Top 1 Accuracy
     float totalAccuracy = checker.GetAccuracy(1);
     BOOST_CHECK(totalAccuracy == 100.0f);
     // Add image 2 and check accuracy
     std::vector<float> inferenceOutputVector2 = {0.10f, 0.0f, 0.0f, 0.0f, 0.05f, 0.70f, 0.0f, 0.0f, 0.0f, 0.15f};
     TContainer inference2Container(inferenceOutputVector2);
     std::vector<TContainer> outputTensor2;
     outputTensor2.push_back(inference2Container);
     imageName = "val_02.JPEG";
     checker.AddImageResult<TContainer>(imageName, outputTensor2);
     // Top 1 Accuracy
     totalAccuracy = checker.GetAccuracy(1);
     BOOST_CHECK(totalAccuracy == 50.0f);
     // Top 2 Accuracy
     totalAccuracy = checker.GetAccuracy(2);
     BOOST_CHECK(totalAccuracy == 100.0f);
     // Add image 3 and check accuracy
     std::vector<float> inferenceOutputVector3 = {0.0f, 0.10f, 0.0f, 0.0f, 0.05f, 0.70f, 0.0f, 0.0f, 0.0f, 0.15f};
     TContainer inference3Container(inferenceOutputVector3);
     std::vector<TContainer> outputTensor3;
     outputTensor3.push_back(inference3Container);
     imageName = "val_03.JPEG";
     checker.AddImageResult<TContainer>(imageName, outputTensor3);
     // Top 1 Accuracy
     totalAccuracy = checker.GetAccuracy(1);
     BOOST_CHECK(totalAccuracy == 33.3333321f);
     // Top 2 Accuracy
     totalAccuracy = checker.GetAccuracy(2);
     BOOST_CHECK(totalAccuracy == 66.6666641f);
     // Top 3 Accuracy
     totalAccuracy = checker.GetAccuracy(3);
     BOOST_CHECK(totalAccuracy == 100.0f);
 }