ArmNN: src/backends/backendsCommon/test/layerTests/PadTestImpl.cpp File Reference
PadTestImpl.cpp File Reference
#include "PadTestImpl.hpp"
#include <QuantizeHelper.hpp>
#include <backendsCommon/test/TensorCopyUtils.hpp>
#include <backendsCommon/test/WorkloadTestUtils.hpp>
#include <test/TensorHelpers.hpp>
Functions
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< T, 2 > Pad2dTestCommon (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< T, 3 > Pad3dTestCommon (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< T, 4 > Pad4dTestCommon (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset)
template<armnn::DataType ArmnnType, typename T >
LayerTestResult< T, 2 > PadQAsymmTestCommon (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
template LayerTestResult< armnn::ResolveType< armnn::DataType::QSymmS16 >, 2 > Pad2dTestCommon< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
template LayerTestResult< armnn::ResolveType< armnn::DataType::QSymmS16 >, 3 > Pad3dTestCommon< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset)
template LayerTestResult< armnn::ResolveType< armnn::DataType::QSymmS16 >, 4 > Pad4dTestCommon< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset)
template LayerTestResult< armnn::ResolveType< armnn::DataType::QAsymmS8 >, 2 > PadQAsymmTestCommon< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
template LayerTestResult< armnn::ResolveType< armnn::DataType::QAsymmU8 >, 2 > PadQAsymmTestCommon< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
LayerTestResult< uint8_t, 2 > PadUint82dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 2 > PadUint82dCustomPaddingTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > PadUint83dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > PadUint84dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > PadFloat322dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 2 > PadFloat322dCustomPaddingTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > PadFloat323dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > PadFloat324dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::BFloat16, 2 > PadBFloat162dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::BFloat16, 2 > PadBFloat162dCustomPaddingTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::BFloat16, 3 > PadBFloat163dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::BFloat16, 4 > PadBFloat164dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > PadInt82dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > PadInt82dCustomPaddingTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 3 > PadInt83dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 4 > PadInt84dTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > PadInt8AsymmTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int8_t, 2 > PadInt8CustomPaddingAsymmTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
Pad2dTestCommon()
LayerTestResult<T, 2> Pad2dTestCommon (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
Definition at line 20 of file PadTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreatePad(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), PadDescriptor::m_PadList, PadDescriptor::m_PadValue, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     IgnoreUnused(memoryManager);
     const armnn::TensorShape inputShape{ 3, 3 };
     const armnn::TensorShape outputShape{ 7, 7 };
     const armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType, qScale, qOffset);
     const armnn::TensorInfo outputTensorInfo(outputShape, ArmnnType, qScale, qOffset);
     std::vector<T> inputValues = armnnUtils::QuantizedVector<T>(
         {
             // Height (3) x Width (3)
             4, 8, 6,
             7, 4, 4,
             3, 2, 4
         },
         qScale, qOffset);
     auto p = customPaddingValue;
     std::vector<T> expectedOutputValues = armnnUtils::QuantizedVector<T>(
         {
             p, p, p, p, p, p, p,
             p, p, p, p, p, p, p,
             p, p, 4, 8, 6, p, p,
             p, p, 7, 4, 4, p, p,
             p, p, 3, 2, 4, p, p,
             p, p, p, p, p, p, p,
             p, p, p, p, p, p, p
         },
         qScale, qOffset);
     auto inputTensor = MakeTensor<T, 2>(inputTensorInfo, std::vector<T>(inputValues));
     LayerTestResult<T, 2> result(outputTensorInfo);
     result.outputExpected = MakeTensor<T, 2>(outputTensorInfo, std::vector<T>(expectedOutputValues));
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::PadQueueDescriptor descriptor;
     std::vector<std::pair<unsigned int, unsigned int>> padList;
     padList.push_back(std::pair<unsigned int, unsigned int>(2,2));
     padList.push_back(std::pair<unsigned int, unsigned int>(2,2));
     descriptor.m_Parameters.m_PadList = padList;
     descriptor.m_Parameters.m_PadValue = customPaddingValue;
     armnn::WorkloadInfo info;
     AddInputToWorkload(descriptor, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreatePad(descriptor, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &inputTensor[0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&result.output[0][0], outputHandle.get());
     return result;
 }
Pad2dTestCommon< armnn::DataType::QSymmS16 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::QSymmS16>, 2> Pad2dTestCommon< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
Pad3dTestCommon()
LayerTestResult<T, 3> Pad3dTestCommon (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset)
Definition at line 95 of file PadTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreatePad(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), PadDescriptor::m_PadList, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     IgnoreUnused(memoryManager);
     const armnn::TensorShape inputShape{ 2, 2, 2 };
     const armnn::TensorShape outputShape{ 3, 5, 6 };
     const armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType, qScale, qOffset);
     const armnn::TensorInfo outputTensorInfo(outputShape, ArmnnType, qScale, qOffset);
     std::vector<T> inputValues = armnnUtils::QuantizedVector<T>(
         {
             // Channel 0, Height (2) x Width (2)
             0, 4,
             2, 5,
             // Channel 1, Height (2) x Width (2)
             6, 1,
             5, 2
         },
         qScale, qOffset);
     std::vector<T> expectedOutputValues = armnnUtils::QuantizedVector<T>(
         {
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 4, 0, 0,
             0, 0, 2, 5, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 6, 1, 0, 0,
             0, 0, 5, 2, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0
        },
        qScale, qOffset);
     auto inputTensor = MakeTensor<T, 3>(inputTensorInfo, std::vector<T>(inputValues));
     LayerTestResult<T, 3> result(outputTensorInfo);
     result.outputExpected = MakeTensor<T, 3>(outputTensorInfo, std::vector<T>(expectedOutputValues));
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::PadQueueDescriptor descriptor;
     std::vector<std::pair<unsigned int, unsigned int>> PadList;
     PadList.push_back(std::pair<unsigned int, unsigned int>(0,1));
     PadList.push_back(std::pair<unsigned int, unsigned int>(2,1));
     PadList.push_back(std::pair<unsigned int, unsigned int>(2,2));
     descriptor.m_Parameters.m_PadList = PadList;
     armnn::WorkloadInfo info;
     AddInputToWorkload(descriptor, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreatePad(descriptor, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &inputTensor[0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&result.output[0][0][0], outputHandle.get());
     return result;
 }
Pad3dTestCommon< armnn::DataType::QSymmS16 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::QSymmS16>, 3> Pad3dTestCommon< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset)
Pad4dTestCommon()
LayerTestResult<T, 4> Pad4dTestCommon (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset)
Definition at line 181 of file PadTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreatePad(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), PadDescriptor::m_PadList, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     IgnoreUnused(memoryManager);
     const armnn::TensorShape inputShape{ 2, 2, 3, 2 };
     const armnn::TensorShape outputShape{ 4, 5, 7, 4 };
     const armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType, qScale, qOffset);
     const armnn::TensorInfo outputTensorInfo(outputShape, ArmnnType, qScale, qOffset);
     std::vector<T> inputValues = armnnUtils::QuantizedVector<T>(
         {
             // Batch 0, Channel 0, Height (3) x Width (2)
              0,  1,
              2,  3,
              4,  5,
             // Batch 0, Channel 1, Height (3) x Width (2)
              6,  7,
              8,  9,
             10, 11,
             // Batch 1, Channel 0, Height (3) x Width (2)
             12, 13,
             14, 15,
             16, 17,
             // Batch 1, Channel 1, Height (3) x Width (2)
             18, 19,
             20, 21,
             22, 23
         },
         qScale, qOffset);
     std::vector<T> expectedOutputValues = armnnUtils::QuantizedVector<T>(
         {
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 1, 0,
             0, 2, 3, 0,
             0, 4, 5, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 6, 7, 0,
             0, 8, 9, 0,
             0, 10, 11, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 12, 13, 0,
             0, 14, 15, 0,
             0, 16, 17, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 18, 19, 0,
             0, 20, 21, 0,
             0, 22, 23, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0
         },
         qScale, qOffset);
     auto inputTensor = MakeTensor<T, 4>(inputTensorInfo, std::vector<T>(inputValues));
     LayerTestResult<T, 4> result(outputTensorInfo);
     result.outputExpected = MakeTensor<T, 4>(outputTensorInfo, std::vector<T>(expectedOutputValues));
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::PadQueueDescriptor descriptor;
     std::vector<std::pair<unsigned int, unsigned int>> PadList;
     PadList.push_back(std::pair<unsigned int, unsigned int>(1,1));
     PadList.push_back(std::pair<unsigned int, unsigned int>(2,1));
     PadList.push_back(std::pair<unsigned int, unsigned int>(3,1));
     PadList.push_back(std::pair<unsigned int, unsigned int>(1,1));
     descriptor.m_Parameters.m_PadList = PadList;
     armnn::WorkloadInfo info;
     AddInputToWorkload(descriptor, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreatePad(descriptor, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &inputTensor[0][0][0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&result.output[0][0][0][0], outputHandle.get());
     return result;
 }
Pad4dTestCommon< armnn::DataType::QSymmS16 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::QSymmS16>, 4> Pad4dTestCommon< armnn::DataType::QSymmS16 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset)
PadBFloat162dCustomPaddingTest()
LayerTestResult<armnn::BFloat16, 2> PadBFloat162dCustomPaddingTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 618 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::BFloat16>(
             workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, 1.0f);
 }
PadBFloat162dTest()
LayerTestResult<armnn::BFloat16, 2> PadBFloat162dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 610 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::BFloat16>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
PadBFloat163dTest()
LayerTestResult<armnn::BFloat16, 3> PadBFloat163dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 627 of file PadTestImpl.cpp.
 {
     return Pad3dTestCommon<armnn::DataType::BFloat16>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
PadBFloat164dTest()
LayerTestResult<armnn::BFloat16, 4> PadBFloat164dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 635 of file PadTestImpl.cpp.
 {
     return Pad4dTestCommon<armnn::DataType::BFloat16>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
PadFloat322dCustomPaddingTest()
LayerTestResult<float, 2> PadFloat322dCustomPaddingTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 585 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0, 1.0f);
 }
PadFloat322dTest()
LayerTestResult<float, 2> PadFloat322dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 577 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
PadFloat323dTest()
LayerTestResult<float, 3> PadFloat323dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 594 of file PadTestImpl.cpp.
 {
     return Pad3dTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
PadFloat324dTest()
LayerTestResult<float, 4> PadFloat324dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 602 of file PadTestImpl.cpp.
 {
     return Pad4dTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory, 0.0f, 0);
 }
PadInt82dCustomPaddingTest()
LayerTestResult<int8_t, 2> PadInt82dCustomPaddingTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 652 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::QSymmS8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0, 1.0f);
 }
PadInt82dTest()
LayerTestResult<int8_t, 2> PadInt82dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 643 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::QSymmS8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }
PadInt83dTest()
LayerTestResult<int8_t, 3> PadInt83dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 661 of file PadTestImpl.cpp.
 {
     return Pad3dTestCommon<armnn::DataType::QSymmS8>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }
PadInt84dTest()
LayerTestResult<int8_t, 4> PadInt84dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 669 of file PadTestImpl.cpp.
 {
     return Pad4dTestCommon<armnn::DataType::QSymmS8>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }
PadInt8AsymmTest()
LayerTestResult<int8_t, 2> PadInt8AsymmTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 677 of file PadTestImpl.cpp.
 {
     return PadQAsymmTestCommon<armnn::DataType::QAsymmS8>(
         workloadFactory, memoryManager, tensorHandleFactory, 2.0f, 2);
 }
PadInt8CustomPaddingAsymmTest()
LayerTestResult<int8_t, 2> PadInt8CustomPaddingAsymmTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 686 of file PadTestImpl.cpp.
 {
     return PadQAsymmTestCommon<armnn::DataType::QAsymmS8>(
         workloadFactory, memoryManager, tensorHandleFactory, 2.0f, 3, 1.0f);
 }
PadQAsymmTestCommon()
LayerTestResult<T, 2> PadQAsymmTestCommon (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
Definition at line 421 of file PadTestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreatePad(), ITensorHandleFactory::CreateTensorHandle(), armnn::IgnoreUnused(), PadDescriptor::m_PadList, PadDescriptor::m_PadValue, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, LayerTestResult< T, n >::output, and LayerTestResult< T, n >::outputExpected.
 {
     IgnoreUnused(memoryManager);
     const armnn::TensorShape inputShape{ 3, 3 };
     const armnn::TensorShape outputShape{ 7, 7 };
     const armnn::TensorInfo inputTensorInfo(inputShape, ArmnnType, qScale, qOffset);
     const armnn::TensorInfo outputTensorInfo(outputShape, ArmnnType, qScale, qOffset);
     std::vector<T> inputValues =
         {
             // Height (3) x Width (3)
             4, 8, 6,
             7, 4, 4,
             3, 2, 4
         };
     T p = static_cast<T>(customPaddingValue);
     std::vector<T> expectedOutputValues =
         {
             p, p, p, p, p, p, p,
             p, p, p, p, p, p, p,
             p, p, 4, 8, 6, p, p,
             p, p, 7, 4, 4, p, p,
             p, p, 3, 2, 4, p, p,
             p, p, p, p, p, p, p,
             p, p, p, p, p, p, p
         };
     auto inputTensor = MakeTensor<T, 2>(inputTensorInfo, std::vector<T>(inputValues));
     LayerTestResult<T, 2> result(outputTensorInfo);
     result.outputExpected = MakeTensor<T, 2>(outputTensorInfo, std::vector<T>(expectedOutputValues));
     std::unique_ptr<armnn::ITensorHandle> inputHandle = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::PadQueueDescriptor descriptor;
     std::vector<std::pair<unsigned int, unsigned int>> padList;
     padList.push_back(std::pair<unsigned int, unsigned int>(2,2));
     padList.push_back(std::pair<unsigned int, unsigned int>(2,2));
     descriptor.m_Parameters.m_PadList = padList;
     descriptor.m_Parameters.m_PadValue = customPaddingValue;
     armnn::WorkloadInfo info;
     AddInputToWorkload(descriptor, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(descriptor, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreatePad(descriptor, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &inputTensor[0][0]);
     workload->PostAllocationConfigure();
     workload->Execute();
     CopyDataFromITensorHandle(&result.output[0][0], outputHandle.get());
     return result;
 }
PadQAsymmTestCommon< armnn::DataType::QAsymmS8 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::QAsymmS8>, 2> PadQAsymmTestCommon< armnn::DataType::QAsymmS8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
PadQAsymmTestCommon< armnn::DataType::QAsymmU8 >()
template LayerTestResult<armnn::ResolveType<armnn::DataType::QAsymmU8>, 2> PadQAsymmTestCommon< armnn::DataType::QAsymmU8 > (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, float qScale, int32_t qOffset, const float customPaddingValue)
PadUint82dCustomPaddingTest()
LayerTestResult<uint8_t, 2> PadUint82dCustomPaddingTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 552 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::QAsymmU8>(
             workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0, 1.0f);
 }
PadUint82dTest()
LayerTestResult<uint8_t, 2> PadUint82dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 544 of file PadTestImpl.cpp.
 {
     return Pad2dTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }
PadUint83dTest()
LayerTestResult<uint8_t, 3> PadUint83dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 561 of file PadTestImpl.cpp.
 {
     return Pad3dTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }
PadUint84dTest()
LayerTestResult<uint8_t, 4> PadUint84dTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 569 of file PadTestImpl.cpp.
 {
     return Pad4dTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }