ArmNN: src/armnnTfLiteParser/test/DetectionPostProcess.cpp File Reference
DetectionPostProcess.cpp File Reference
#include "../TfLiteParser.hpp"
#include "ParserFlatbuffersFixture.hpp"
#include "ParserPrototxtFixture.hpp"
#include "ParserHelper.hpp"
#include "test/GraphUtils.hpp"
#include <armnn/utility/PolymorphicDowncast.hpp>
#include <QuantizeHelper.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_FIXTURE_TEST_CASE (ParseDetectionPostProcess, ParseDetectionPostProcessCustomOptions)
BOOST_FIXTURE_TEST_CASE (DetectionPostProcessGraphStructureTest, ParseDetectionPostProcessCustomOptions)
Function Documentation
BOOST_FIXTURE_TEST_CASE() [1/2]
BOOST_FIXTURE_TEST_CASE (ParseDetectionPostProcess , ParseDetectionPostProcessCustomOptions)
Definition at line 164 of file DetectionPostProcess.cpp.
References boxEncodings(), and scores().
 {
     Setup();
     // Inputs
     using UnquantizedContainer = std::vector<float>;
     UnquantizedContainer boxEncodings =
     {
         0.0f,  0.0f, 0.0f, 0.0f,
         0.0f,  1.0f, 0.0f, 0.0f,
         0.0f, -1.0f, 0.0f, 0.0f,
         0.0f,  0.0f, 0.0f, 0.0f,
         0.0f,  1.0f, 0.0f, 0.0f,
         0.0f,  0.0f, 0.0f, 0.0f
     };
     UnquantizedContainer scores =
     {
         0.0f, 0.9f,  0.8f,
         0.0f, 0.75f, 0.72f,
         0.0f, 0.6f,  0.5f,
         0.0f, 0.93f, 0.95f,
         0.0f, 0.5f,  0.4f,
         0.0f, 0.3f,  0.2f
     };
     // Outputs
     UnquantizedContainer detectionBoxes =
     {
         0.0f, 10.0f, 1.0f, 11.0f,
         0.0f, 10.0f, 1.0f, 11.0f,
         0.0f, 0.0f,  0.0f, 0.0f
     };
     UnquantizedContainer detectionClasses = { 1.0f,  0.0f,  0.0f };
     UnquantizedContainer detectionScores  = { 0.95f, 0.93f, 0.0f };
     UnquantizedContainer numDetections    = { 2.0f };
     // Quantize inputs and outputs
     using QuantizedContainer = std::vector<uint8_t>;
     QuantizedContainer quantBoxEncodings = armnnUtils::QuantizedVector<uint8_t>(boxEncodings, 1.00f, 1);
     QuantizedContainer quantScores       = armnnUtils::QuantizedVector<uint8_t>(scores,       0.01f, 0);
     std::map<std::string, QuantizedContainer> input =
     {
         { "box_encodings", quantBoxEncodings },
         { "scores", quantScores }
     };
     std::map<std::string, UnquantizedContainer> output =
     {
         { "detection_boxes", detectionBoxes},
         { "detection_classes", detectionClasses},
         { "detection_scores", detectionScores},
         { "num_detections", numDetections}
     };
     RunTest<armnn::DataType::QAsymmU8, armnn::DataType::Float32>(0, input, output);
 }
BOOST_FIXTURE_TEST_CASE() [2/2]
BOOST_FIXTURE_TEST_CASE (DetectionPostProcessGraphStructureTest , ParseDetectionPostProcessCustomOptions)
Definition at line 226 of file DetectionPostProcess.cpp.
References BOOST_AUTO_TEST_SUITE_END(), CheckNumberOfInputSlot(), CheckNumberOfOutputSlot(), armnn::CpuRef, armnn::DetectionPostProcess, armnn::Float32, GetFirstLayerWithName(), armnn::GetGraphForTesting(), Layer::GetType(), armnn::Input, IsConnected(), armnn::Optimize(), armnn::Output, and armnn::QAsymmU8.
 {
     /*
        Inputs:            box_encodings  scores
                                \          /
                             DetectionPostProcess
                           /        /     \       \
                          /        /       \       \
        Outputs:     detection detection detection num_detections
                     boxes     classes   scores
     */
     ReadStringToBinary();
     armnn::INetworkPtr network = m_Parser->CreateNetworkFromBinary(m_GraphBinary);
     auto optimized = Optimize(*network, { armnn::Compute::CpuRef }, m_Runtime->GetDeviceSpec());
     armnn::Graph& graph = GetGraphForTesting(optimized.get());
     // Check the number of layers in the graph
     BOOST_TEST((graph.GetNumInputs() == 2));
     BOOST_TEST((graph.GetNumOutputs() == 4));
     BOOST_TEST((graph.GetNumLayers() == 7));
     // Input layers
     armnn::Layer* boxEncodingLayer = GetFirstLayerWithName(graph, "box_encodings");
     BOOST_TEST((boxEncodingLayer->GetType() == armnn::LayerType::Input));
     BOOST_TEST(CheckNumberOfInputSlot(boxEncodingLayer, 0));
     BOOST_TEST(CheckNumberOfOutputSlot(boxEncodingLayer, 1));
     armnn::Layer* scoresLayer = GetFirstLayerWithName(graph, "scores");
     BOOST_TEST((scoresLayer->GetType() == armnn::LayerType::Input));
     BOOST_TEST(CheckNumberOfInputSlot(scoresLayer, 0));
     BOOST_TEST(CheckNumberOfOutputSlot(scoresLayer, 1));
     // DetectionPostProcess layer
     armnn::Layer* detectionPostProcessLayer = GetFirstLayerWithName(graph, "DetectionPostProcess:0:0");
     BOOST_TEST((detectionPostProcessLayer->GetType() == armnn::LayerType::DetectionPostProcess));
     BOOST_TEST(CheckNumberOfInputSlot(detectionPostProcessLayer, 2));
     BOOST_TEST(CheckNumberOfOutputSlot(detectionPostProcessLayer, 4));
     // Output layers
     armnn::Layer* detectionBoxesLayer = GetFirstLayerWithName(graph, "detection_boxes");
     BOOST_TEST((detectionBoxesLayer->GetType() == armnn::LayerType::Output));
     BOOST_TEST(CheckNumberOfInputSlot(detectionBoxesLayer, 1));
     BOOST_TEST(CheckNumberOfOutputSlot(detectionBoxesLayer, 0));
     armnn::Layer* detectionClassesLayer = GetFirstLayerWithName(graph, "detection_classes");
     BOOST_TEST((detectionClassesLayer->GetType() == armnn::LayerType::Output));
     BOOST_TEST(CheckNumberOfInputSlot(detectionClassesLayer, 1));
     BOOST_TEST(CheckNumberOfOutputSlot(detectionClassesLayer, 0));
     armnn::Layer* detectionScoresLayer = GetFirstLayerWithName(graph, "detection_scores");
     BOOST_TEST((detectionScoresLayer->GetType() == armnn::LayerType::Output));
     BOOST_TEST(CheckNumberOfInputSlot(detectionScoresLayer, 1));
     BOOST_TEST(CheckNumberOfOutputSlot(detectionScoresLayer, 0));
     armnn::Layer* numDetectionsLayer = GetFirstLayerWithName(graph, "num_detections");
     BOOST_TEST((numDetectionsLayer->GetType() == armnn::LayerType::Output));
     BOOST_TEST(CheckNumberOfInputSlot(numDetectionsLayer, 1));
     BOOST_TEST(CheckNumberOfOutputSlot(numDetectionsLayer, 0));
     // Check the connections
     armnn::TensorInfo boxEncodingTensor(armnn::TensorShape({ 1, 6, 4 }), armnn::DataType::QAsymmU8, 1, 1);
     armnn::TensorInfo scoresTensor(armnn::TensorShape({ 1, 6, 3 }), armnn::DataType::QAsymmU8,
                                                       0.00999999978f, 0);
     armnn::TensorInfo detectionBoxesTensor(armnn::TensorShape({ 1, 3, 4 }), armnn::DataType::Float32, 0, 0);
     armnn::TensorInfo detectionClassesTensor(armnn::TensorShape({ 1, 3 }), armnn::DataType::Float32, 0, 0);
     armnn::TensorInfo detectionScoresTensor(armnn::TensorShape({ 1, 3 }), armnn::DataType::Float32, 0, 0);
     armnn::TensorInfo numDetectionsTensor(armnn::TensorShape({ 1} ), armnn::DataType::Float32, 0, 0);
     BOOST_TEST(IsConnected(boxEncodingLayer, detectionPostProcessLayer, 0, 0, boxEncodingTensor));
     BOOST_TEST(IsConnected(scoresLayer, detectionPostProcessLayer, 0, 1, scoresTensor));
     BOOST_TEST(IsConnected(detectionPostProcessLayer, detectionBoxesLayer, 0, 0, detectionBoxesTensor));
     BOOST_TEST(IsConnected(detectionPostProcessLayer, detectionClassesLayer, 1, 0, detectionClassesTensor));
     BOOST_TEST(IsConnected(detectionPostProcessLayer, detectionScoresLayer, 2, 0, detectionScoresTensor));
     BOOST_TEST(IsConnected(detectionPostProcessLayer, numDetectionsLayer, 3, 0, numDetectionsTensor));
 }