ArmNN: RefFullyConnectedWorkload Class Reference
RefFullyConnectedWorkload Class Reference
#include <RefFullyConnectedWorkload.hpp>
Public Member Functions
RefFullyConnectedWorkload (const FullyConnectedQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
void Execute () const override
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
Public Member Functions inherited from BaseWorkload< FullyConnectedQueueDescriptor >
BaseWorkload (const FullyConnectedQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const FullyConnectedQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< FullyConnectedQueueDescriptor >
FullyConnectedQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 18 of file RefFullyConnectedWorkload.hpp.
Constructor & Destructor Documentation
RefFullyConnectedWorkload()
RefFullyConnectedWorkload (const FullyConnectedQueueDescriptor & descriptor, const WorkloadInfo & info) explicit
Definition at line 15 of file RefFullyConnectedWorkload.cpp.
References TensorInfo::GetShape(), FullyConnectedQueueDescriptor::m_Bias, FullyConnectedDescriptor::m_BiasEnabled, FullyConnectedDescriptor::m_ConstantWeights, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and FullyConnectedQueueDescriptor::m_Weight.
         : BaseWorkload<FullyConnectedQueueDescriptor>(descriptor, info)
 {
     if (descriptor.m_Parameters.m_ConstantWeights)
     {
         m_Weight = std::make_unique<ScopedTensorHandle>(*(descriptor.m_Weight));
         const TensorInfo& rWeightInfo = m_Weight->GetTensorInfo();
         m_WeightShape = rWeightInfo.GetShape();
         m_WeightDecoder = MakeDecoder<float>(rWeightInfo, m_Weight->Map(true));
         if (descriptor.m_Parameters.m_BiasEnabled)
         {
             m_Bias = std::make_unique<ScopedTensorHandle>(*(descriptor.m_Bias));
             const TensorInfo& biasInfo = m_Bias->GetTensorInfo();
             m_BiasDecoder = MakeDecoder<float>(biasInfo, m_Bias->Map(true));
         }
     }
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 71 of file RefFullyConnectedWorkload.cpp.
References BaseWorkload< FullyConnectedQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, and QueueDescriptor::m_Outputs.
Referenced by RefFullyConnectedWorkload::ExecuteAsync().
 {
     Execute(m_Data.m_Inputs, m_Data.m_Outputs);
 }
ExecuteAsync()
void ExecuteAsync (WorkingMemDescriptor & workingMemDescriptor) override virtual
Implements IWorkload.
Definition at line 76 of file RefFullyConnectedWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, armnn::CpuRef, RefFullyConnectedWorkload::Execute(), armnn::FullyConnected, armnn::GetTensorInfo(), FullyConnectedDescriptor::m_BiasEnabled, FullyConnectedDescriptor::m_ConstantWeights, BaseWorkload< FullyConnectedQueueDescriptor >::m_Data, WorkingMemDescriptor::m_Inputs, WorkingMemDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, FullyConnectedDescriptor::m_TransposeWeightMatrix, armnn::Map, and RefFullyConnectedWorkload::PostAllocationConfigure().
 {
     PostAllocationConfigure(workingMemDescriptor.m_Inputs, workingMemDescriptor.m_Outputs);
     Execute(workingMemDescriptor.m_Inputs, workingMemDescriptor.m_Outputs);
 }
PostAllocationConfigure()
void PostAllocationConfigure () override virtual
Implements IWorkload.
Definition at line 35 of file RefFullyConnectedWorkload.cpp.
References ARMNN_ASSERT, TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), armnn::GetTensorInfo(), FullyConnectedDescriptor::m_BiasEnabled, FullyConnectedDescriptor::m_ConstantWeights, BaseWorkload< FullyConnectedQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by RefFullyConnectedWorkload::ExecuteAsync().
 {
     PostAllocationConfigure(m_Data.m_Inputs, m_Data.m_Outputs);
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefFullyConnectedWorkload.hpp
src/backends/reference/workloads/RefFullyConnectedWorkload.cpp