ArmNN: IAsyncExecutionCallback Class Reference
IAsyncExecutionCallback Class Reference abstract
#include <IAsyncExecutionCallback.hpp>
Public Member Functions
virtual ~IAsyncExecutionCallback ()
virtual void Notify (armnn::Status status, InferenceTimingPair timeTaken)=0
virtual void Wait () const =0
virtual armnn::Status GetStatus () const =0
virtual HighResolutionClock GetStartTime () const =0
virtual HighResolutionClock GetEndTime () const =0
Detailed Description
Definition at line 19 of file IAsyncExecutionCallback.hpp.
Constructor & Destructor Documentation
~IAsyncExecutionCallback()
virtual ~IAsyncExecutionCallback () inline virtual
Definition at line 22 of file IAsyncExecutionCallback.hpp.
References IAsyncExecutionCallback::GetEndTime(), IAsyncExecutionCallback::GetStartTime(), IAsyncExecutionCallback::GetStatus(), IAsyncExecutionCallback::Notify(), and IAsyncExecutionCallback::Wait().
 {};
Member Function Documentation
GetEndTime()
virtual HighResolutionClock GetEndTime () const pure virtual
Implemented in AsyncExecutionCallback.
Referenced by IAsyncExecutionCallback::~IAsyncExecutionCallback().
GetStartTime()
virtual HighResolutionClock GetStartTime () const pure virtual
Implemented in AsyncExecutionCallback.
Referenced by IAsyncExecutionCallback::~IAsyncExecutionCallback().
GetStatus()
virtual armnn::Status GetStatus () const pure virtual
Implemented in AsyncExecutionCallback.
Referenced by IAsyncExecutionCallback::~IAsyncExecutionCallback().
Notify()
virtual void Notify (armnn::Status status, InferenceTimingPair timeTaken) pure virtual
Implemented in AsyncExecutionCallback.
Referenced by IAsyncExecutionCallback::~IAsyncExecutionCallback().
Wait()
virtual void Wait () const pure virtual
Implemented in AsyncExecutionCallback.
Referenced by IAsyncExecutionCallback::~IAsyncExecutionCallback().
The documentation for this class was generated from the following file:
include/armnn/IAsyncExecutionCallback.hpp