ArmNN: AsyncExecutionCallback Class Reference
AsyncExecutionCallback Class Reference final
#include <AsyncExecutionCallback.hpp>
Public Member Functions
AsyncExecutionCallback ()
~AsyncExecutionCallback ()
void Notify (armnn::Status status, InferenceTimingPair timeTaken)
void Wait () const
armnn::Status GetStatus () const
HighResolutionClock GetStartTime () const
HighResolutionClock GetEndTime () const
Public Member Functions inherited from IAsyncExecutionCallback
virtual ~IAsyncExecutionCallback ()
Detailed Description
Definition at line 21 of file AsyncExecutionCallback.hpp.
Constructor & Destructor Documentation
AsyncExecutionCallback()
AsyncExecutionCallback () inline
Definition at line 24 of file AsyncExecutionCallback.hpp.
     {}
~AsyncExecutionCallback()
~AsyncExecutionCallback () inline
Definition at line 26 of file AsyncExecutionCallback.hpp.
References armnn::Failure, AsyncExecutionCallback::GetEndTime(), AsyncExecutionCallback::GetStartTime(), AsyncExecutionCallback::GetStatus(), AsyncExecutionCallback::Notify(), and AsyncExecutionCallback::Wait().
     {}
Member Function Documentation
GetEndTime()
HighResolutionClock GetEndTime () const virtual
Implements IAsyncExecutionCallback.
Definition at line 49 of file AsyncExecutionCallback.cpp.
References AsyncExecutionCallback::Wait().
Referenced by AsyncExecutionCallback::~AsyncExecutionCallback().
 {
     Wait();
     return m_EndTime;
 }
GetStartTime()
HighResolutionClock GetStartTime () const virtual
Implements IAsyncExecutionCallback.
Definition at line 43 of file AsyncExecutionCallback.cpp.
References AsyncExecutionCallback::Wait().
Referenced by AsyncExecutionCallback::~AsyncExecutionCallback().
 {
     Wait();
     return m_StartTime;
 }
GetStatus()
armnn::Status GetStatus () const virtual
Implements IAsyncExecutionCallback.
Definition at line 37 of file AsyncExecutionCallback.cpp.
References AsyncExecutionCallback::Wait().
Referenced by AsyncExecutionCallback::~AsyncExecutionCallback().
 {
     Wait();
     return m_Status;
 }
Notify()
void Notify (armnn::Status status, InferenceTimingPair timeTaken) virtual
Implements IAsyncExecutionCallback.
Definition at line 14 of file AsyncExecutionCallback.cpp.
Referenced by AsyncExecutionCallback::~AsyncExecutionCallback().
 {
     {
         std::lock_guard<std::mutex> hold(m_Mutex);
         if (m_Notified)
         {
             return;
         }
         // store results and mark as notified
         m_Status    = status;
         m_StartTime = timeTaken.first;
         m_EndTime   = timeTaken.second;
         m_Notified  = true;
     }
     m_Condition.notify_all();
 }
Wait()
void Wait () const virtual
Implements IAsyncExecutionCallback.
Definition at line 31 of file AsyncExecutionCallback.cpp.
Referenced by AsyncExecutionCallback::GetEndTime(), AsyncExecutionCallback::GetStartTime(), AsyncExecutionCallback::GetStatus(), and AsyncExecutionCallback::~AsyncExecutionCallback().
 {
     std::unique_lock<std::mutex> lock(m_Mutex);
     m_Condition.wait(lock, [this] { return m_Notified; });
 }
The documentation for this class was generated from the following files:
src/armnn/AsyncExecutionCallback.hpp
src/armnn/AsyncExecutionCallback.cpp