ArmNN: SendCounterPacketTest Class Reference
SendCounterPacketTest Class Reference
#include <SendCounterPacketTests.hpp>
Public Member Functions
SendCounterPacketTest (IBufferManager &buffer)
bool CreateDeviceRecordTest (const DevicePtr &device, DeviceRecord &deviceRecord, std::string &errorMessage)
bool CreateCounterSetRecordTest (const CounterSetPtr &counterSet, CounterSetRecord &counterSetRecord, std::string &errorMessage)
bool CreateEventRecordTest (const CounterPtr &counter, EventRecord &eventRecord, std::string &errorMessage)
bool CreateCategoryRecordTest (const CategoryPtr &category, const Counters &counters, CategoryRecord &categoryRecord, std::string &errorMessage)
Public Member Functions inherited from SendCounterPacket
SendCounterPacket (IBufferManager &buffer)
void SendStreamMetaDataPacket () override
Create and write a StreamMetaDataPacket in the buffer.
void SendCounterDirectoryPacket (const ICounterDirectory &counterDirectory) override
Create and write a CounterDirectoryPacket from the parameters to the buffer.
void SendPeriodicCounterCapturePacket (uint64_t timestamp, const IndexValuePairsVector &values) override
Create and write a PeriodicCounterCapturePacket from the parameters to the buffer.
void SendPeriodicCounterSelectionPacket (uint32_t capturePeriod, const std::vector< uint16_t > &selectedCounterIds) override
Create and write a PeriodicCounterSelectionPacket from the parameters to the buffer.
Public Member Functions inherited from ISendCounterPacket
virtual ~ISendCounterPacket ()
Additional Inherited Members
Public Types inherited from SendCounterPacket
using CategoryRecord = std::vector< uint32_t >
using DeviceRecord = std::vector< uint32_t >
using CounterSetRecord = std::vector< uint32_t >
using EventRecord = std::vector< uint32_t >
using IndexValuePairsVector = std::vector< CounterValue >
Public Types inherited from ISendCounterPacket
using IndexValuePairsVector = std::vector< CounterValue >
Protected Member Functions inherited from SendCounterPacket
bool CreateCategoryRecord (const CategoryPtr &category, const Counters &counters, CategoryRecord &categoryRecord, std::string &errorMessage)
bool CreateDeviceRecord (const DevicePtr &device, DeviceRecord &deviceRecord, std::string &errorMessage)
bool CreateCounterSetRecord (const CounterSetPtr &counterSet, CounterSetRecord &counterSetRecord, std::string &errorMessage)
bool CreateEventRecord (const CounterPtr &counter, EventRecord &eventRecord, std::string &errorMessage)
Detailed Description
Definition at line 31 of file SendCounterPacketTests.hpp.
Constructor & Destructor Documentation
SendCounterPacketTest()
SendCounterPacketTest (IBufferManager & buffer) inline
Definition at line 34 of file SendCounterPacketTests.hpp.
         : SendCounterPacket(buffer)
     {}
Member Function Documentation
CreateCategoryRecordTest()
bool CreateCategoryRecordTest (const CategoryPtr & category, const Counters & counters, CategoryRecord & categoryRecord, std::string & errorMessage) inline
Definition at line 59 of file SendCounterPacketTests.hpp.
References SendCounterPacket::CreateCategoryRecord().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         return CreateCategoryRecord(category, counters, categoryRecord, errorMessage);
     }
CreateCounterSetRecordTest()
bool CreateCounterSetRecordTest (const CounterSetPtr & counterSet, CounterSetRecord & counterSetRecord, std::string & errorMessage) inline
Definition at line 45 of file SendCounterPacketTests.hpp.
References SendCounterPacket::CreateCounterSetRecord().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         return CreateCounterSetRecord(counterSet, counterSetRecord, errorMessage);
     }
CreateDeviceRecordTest()
bool CreateDeviceRecordTest (const DevicePtr & device, DeviceRecord & deviceRecord, std::string & errorMessage) inline
Definition at line 38 of file SendCounterPacketTests.hpp.
References SendCounterPacket::CreateDeviceRecord().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         return CreateDeviceRecord(device, deviceRecord, errorMessage);
     }
CreateEventRecordTest()
bool CreateEventRecordTest (const CounterPtr & counter, EventRecord & eventRecord, std::string & errorMessage) inline
Definition at line 52 of file SendCounterPacketTests.hpp.
References SendCounterPacket::CreateEventRecord().
Referenced by BOOST_AUTO_TEST_CASE().
     {
         return CreateEventRecord(counter, eventRecord, errorMessage);
     }
The documentation for this class was generated from the following file:
src/profiling/test/SendCounterPacketTests.hpp