ArmNN: BooleanDecoder Class Reference
BooleanDecoder Class Reference
#include <BaseIterator.hpp>
Public Member Functions
BooleanDecoder (const uint8_t *data)
BooleanDecoder ()
float Get () const override
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const unsigned int channelMultiplier, const bool isDepthwise) override
Public Member Functions inherited from TypedIterator< const uint8_t, Decoder< float > >
TypedIterator (const uint8_t *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
TypedIterator & SetIndex (unsigned int index, unsigned int axisIndex=0) override
Public Member Functions inherited from Decoder< float >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< const uint8_t, Decoder< float > >
const uint8_t * m_Iterator
const uint8_t * m_Start
Detailed Description
Definition at line 485 of file BaseIterator.hpp.
Constructor & Destructor Documentation
BooleanDecoder() [1/2]
BooleanDecoder (const uint8_t * data) inline
Definition at line 488 of file BaseIterator.hpp.
             : TypedIterator(data) {}
BooleanDecoder() [2/2]
BooleanDecoder () inline
Definition at line 491 of file BaseIterator.hpp.
             : BooleanDecoder(nullptr) {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, const unsigned int channelMultiplier, const bool isDepthwise) inline override virtual
Implements Decoder< float >.
Definition at line 498 of file BaseIterator.hpp.
References TensorShape::GetNumElements(), armnn::IgnoreUnused(), and BaseIterator::operator[]().
     {
         IgnoreUnused(channelMultiplier, isDepthwise);
         const unsigned int size = tensorShape.GetNumElements();
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         for (uint32_t i = 0; i < size; ++i)
         {
             this->operator[](i);
             decodedTensor.emplace_back(*m_Iterator);
         }
         return decodedTensor;
     }
Get()
float Get () const inline override virtual
Implements Decoder< float >.
Definition at line 494 of file BaseIterator.hpp.
     {
         return *m_Iterator;
     }
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp