var namespacearmnn_1_1optimizations =
[
    [ "pad_fold", "namespacearmnn_1_1optimizations_1_1pad__fold.xhtml", "namespacearmnn_1_1optimizations_1_1pad__fold" ],
    [ "AddBroadcastReshapeLayerImpl", "classarmnn_1_1optimizations_1_1_add_broadcast_reshape_layer_impl.xhtml", "classarmnn_1_1optimizations_1_1_add_broadcast_reshape_layer_impl" ],
    [ "AddDebugImpl", "classarmnn_1_1optimizations_1_1_add_debug_impl.xhtml", "classarmnn_1_1optimizations_1_1_add_debug_impl" ],
    [ "BFloat16ToFloat32", "structarmnn_1_1optimizations_1_1_b_float16_to_float32.xhtml", null ],
    [ "ConvertConstants", "classarmnn_1_1optimizations_1_1_convert_constants.xhtml", "classarmnn_1_1optimizations_1_1_convert_constants" ],
    [ "ConvertFp32NetworkToBf16Impl", "classarmnn_1_1optimizations_1_1_convert_fp32_network_to_bf16_impl.xhtml", "classarmnn_1_1optimizations_1_1_convert_fp32_network_to_bf16_impl" ],
    [ "ConvertFp32NetworkToFp16Impl", "classarmnn_1_1optimizations_1_1_convert_fp32_network_to_fp16_impl.xhtml", "classarmnn_1_1optimizations_1_1_convert_fp32_network_to_fp16_impl" ],
    [ "Float16ToFloat32", "structarmnn_1_1optimizations_1_1_float16_to_float32.xhtml", null ],
    [ "Float32ToBFloat16", "structarmnn_1_1optimizations_1_1_float32_to_b_float16.xhtml", null ],
    [ "Float32ToFloat16", "structarmnn_1_1optimizations_1_1_float32_to_float16.xhtml", null ],
    [ "FuseBatchNorm", "classarmnn_1_1optimizations_1_1_fuse_batch_norm.xhtml", "classarmnn_1_1optimizations_1_1_fuse_batch_norm" ],
    [ "IsBFloat16Layer", "structarmnn_1_1optimizations_1_1_is_b_float16_layer.xhtml", null ],
    [ "IsFloat16Layer", "structarmnn_1_1optimizations_1_1_is_float16_layer.xhtml", null ],
    [ "IsFloat32Layer", "structarmnn_1_1optimizations_1_1_is_float32_layer.xhtml", null ],
    [ "MovePermuteUpImpl", "classarmnn_1_1optimizations_1_1_move_permute_up_impl.xhtml", "classarmnn_1_1optimizations_1_1_move_permute_up_impl" ],
    [ "MoveTransposeUpImpl", "classarmnn_1_1optimizations_1_1_move_transpose_up_impl.xhtml", "classarmnn_1_1optimizations_1_1_move_transpose_up_impl" ],
    [ "OptimizeConsecutiveReshapesImpl", "classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl.xhtml", "classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl" ],
    [ "OptimizeInverseConversionsImpl", "classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl.xhtml", "classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl" ],
    [ "OptimizeInversePermutesImpl", "classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl.xhtml", "classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl" ],
    [ "PermuteAndBatchToSpaceAsDepthToSpaceImpl", "classarmnn_1_1optimizations_1_1_permute_and_batch_to_space_as_depth_to_space_impl.xhtml", "classarmnn_1_1optimizations_1_1_permute_and_batch_to_space_as_depth_to_space_impl" ],
    [ "PermuteAsReshapeImpl", "classarmnn_1_1optimizations_1_1_permute_as_reshape_impl.xhtml", "classarmnn_1_1optimizations_1_1_permute_as_reshape_impl" ],
    [ "SquashEqualSiblingsImpl", "classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl.xhtml", "classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl" ],
    [ "TransposeAsReshapeImpl", "classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.xhtml", "classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl" ]
];