ArmNN: armnn::optimizations Namespace Reference
armnn::optimizations Namespace Reference
Namespaces
pad_fold
Classes
class AddBroadcastReshapeLayerImpl
class AddDebugImpl
struct BFloat16ToFloat32
class ConvertConstants
class ConvertFp32NetworkToBf16Impl
class ConvertFp32NetworkToFp16Impl
struct Float16ToFloat32
struct Float32ToBFloat16
struct Float32ToFloat16
class FuseBatchNorm
struct IsBFloat16Layer
struct IsFloat16Layer
struct IsFloat32Layer
class MovePermuteUpImpl
class MoveTransposeUpImpl
class OptimizeConsecutiveReshapesImpl
class OptimizeInverseConversionsImpl
class OptimizeInversePermutesImpl
class PermuteAndBatchToSpaceAsDepthToSpaceImpl
Replaces Permute leading into BatchToSpace with a DepthToSpace in the case where the Permute swaps the batch and channels dimensions such that the replacement is valid.
class PermuteAsReshapeImpl
class SquashEqualSiblingsImpl
class TransposeAsReshapeImpl
Typedefs
using AddBroadcastReshapeLayer = OptimizeForType< Layer, AddBroadcastReshapeLayerImpl >
using InsertDebugLayer = OptimizeForType< Layer, AddDebugImpl >
using ConvertConstantsBFloatToFloat = ConvertConstants< BFloat16ToFloat32, IsFloat32Layer >
using ConvertConstantsFloatToBFloat = ConvertConstants< Float32ToBFloat16, IsBFloat16Layer >
using ConvertConstantsHalfToFloat = ConvertConstants< Float16ToFloat32, IsFloat32Layer >
using ConvertConstantsFloatToHalf = ConvertConstants< Float32ToFloat16, IsFloat16Layer >
using Fp32NetworkToBf16Converter = OptimizeForType< Layer, ConvertFp32NetworkToBf16Impl >
using Fp32NetworkToFp16Converter = OptimizeForType< Layer, ConvertFp32NetworkToFp16Impl >
using FoldPadIntoConvolution2d = OptimizeForExclusiveConnection< PadLayer, Convolution2dLayer, pad_fold::FoldPadIntoConvolution2dImpl >
using FoldPadIntoPooling2d = OptimizeForExclusiveConnection< PadLayer, Pooling2dLayer, pad_fold::FoldPadIntoPooling2dImpl >
using FuseBatchNormIntoConvolution2DFloat32 = OptimizeForExclusiveConnection< Convolution2dLayer, BatchNormalizationLayer, FuseBatchNorm< Convolution2dLayer, armnn::DataType::Float32 > >
using FuseBatchNormIntoConvolution2DFloat16 = OptimizeForExclusiveConnection< Convolution2dLayer, BatchNormalizationLayer, FuseBatchNorm< Convolution2dLayer, armnn::DataType::Float16 > >
using FuseBatchNormIntoDepthwiseConvolution2DFloat32 = OptimizeForExclusiveConnection< DepthwiseConvolution2dLayer, BatchNormalizationLayer, FuseBatchNorm< DepthwiseConvolution2dLayer, armnn::DataType::Float32 > >
using FuseBatchNormIntoDepthwiseConvolution2DFloat16 = OptimizeForExclusiveConnection< DepthwiseConvolution2dLayer, BatchNormalizationLayer, FuseBatchNorm< DepthwiseConvolution2dLayer, armnn::DataType::Float16 > >
using MovePermuteUp = OptimizeForConnection< Layer, PermuteLayer, MovePermuteUpImpl >
using MoveTransposeUp = OptimizeForConnection< Layer, TransposeLayer, MoveTransposeUpImpl >
using OptimizeConsecutiveReshapes = OptimizeForConnection< ReshapeLayer, ReshapeLayer, OptimizeConsecutiveReshapesImpl >
using OptimizeInverseConversionsFp16 = OptimizeForConnection< ConvertFp16ToFp32Layer, ConvertFp32ToFp16Layer, OptimizeInverseConversionsImpl >
using OptimizeInverseConversionsFp32 = OptimizeForConnection< ConvertFp32ToFp16Layer, ConvertFp16ToFp32Layer, OptimizeInverseConversionsImpl >
using OptimizeInversePermutes = OptimizeForConnection< PermuteLayer, PermuteLayer, OptimizeInversePermutesImpl< PermuteLayer > >
using OptimizeInverseTransposes = OptimizeForConnection< TransposeLayer, TransposeLayer, OptimizeInversePermutesImpl< TransposeLayer > >
using PermuteAndBatchToSpaceAsDepthToSpace = OptimizeForConnection< PermuteLayer, BatchToSpaceNdLayer, PermuteAndBatchToSpaceAsDepthToSpaceImpl< PermuteLayer > >
using TransposeAndBatchToSpaceAsDepthToSpace = OptimizeForConnection< TransposeLayer, BatchToSpaceNdLayer, PermuteAndBatchToSpaceAsDepthToSpaceImpl< TransposeLayer > >
using PermuteAsReshape = OptimizeForType< PermuteLayer, PermuteAsReshapeImpl >
using SquashEqualPermuteSiblings = OptimizeForConnection< Layer, PermuteLayer, SquashEqualSiblingsImpl< PermuteLayer > >
using SquashEqualTransposeSiblings = OptimizeForConnection< Layer, TransposeLayer, SquashEqualSiblingsImpl< TransposeLayer > >
using SquashEqualReshapeSiblings = OptimizeForConnection< Layer, ReshapeLayer, SquashEqualSiblingsImpl< ReshapeLayer > >
using TransposeAsReshape = OptimizeForType< TransposeLayer, TransposeAsReshapeImpl >
Functions
template<typename LayerT >
LayerT * ConvertWeight (Layer *l)
Typedef Documentation
AddBroadcastReshapeLayer
using AddBroadcastReshapeLayer = OptimizeForType<Layer, AddBroadcastReshapeLayerImpl>
Definition at line 93 of file AddBroadcastReshapeLayer.hpp.
ConvertConstantsBFloatToFloat
using ConvertConstantsBFloatToFloat = ConvertConstants<BFloat16ToFloat32, IsFloat32Layer>
Definition at line 151 of file ConvertConstants.hpp.
ConvertConstantsFloatToBFloat
using ConvertConstantsFloatToBFloat = ConvertConstants<Float32ToBFloat16, IsBFloat16Layer>
Definition at line 152 of file ConvertConstants.hpp.
ConvertConstantsFloatToHalf
using ConvertConstantsFloatToHalf = ConvertConstants<Float32ToFloat16, IsFloat16Layer>
Definition at line 155 of file ConvertConstants.hpp.
ConvertConstantsHalfToFloat
using ConvertConstantsHalfToFloat = ConvertConstants<Float16ToFloat32, IsFloat32Layer>
Definition at line 154 of file ConvertConstants.hpp.
FoldPadIntoConvolution2d
using FoldPadIntoConvolution2d = OptimizeForExclusiveConnection<PadLayer, Convolution2dLayer, pad_fold::FoldPadIntoConvolution2dImpl>
Definition at line 197 of file FoldPadIntoLayer2d.hpp.
FoldPadIntoPooling2d
using FoldPadIntoPooling2d = OptimizeForExclusiveConnection<PadLayer, Pooling2dLayer, pad_fold::FoldPadIntoPooling2dImpl>
Definition at line 199 of file FoldPadIntoLayer2d.hpp.
Fp32NetworkToBf16Converter
using Fp32NetworkToBf16Converter = OptimizeForType<Layer, ConvertFp32NetworkToBf16Impl>
Definition at line 76 of file ConvertFp32NetworkToBf16.hpp.
Fp32NetworkToFp16Converter
using Fp32NetworkToFp16Converter = OptimizeForType<Layer, ConvertFp32NetworkToFp16Impl>
Definition at line 87 of file ConvertFp32NetworkToFp16.hpp.
FuseBatchNormIntoConvolution2DFloat16
using FuseBatchNormIntoConvolution2DFloat16 = OptimizeForExclusiveConnection<Convolution2dLayer, BatchNormalizationLayer, FuseBatchNorm<Convolution2dLayer, armnn::DataType::Float16> >
Definition at line 192 of file FuseBatchNorm.hpp.
FuseBatchNormIntoConvolution2DFloat32
using FuseBatchNormIntoConvolution2DFloat32 = OptimizeForExclusiveConnection<Convolution2dLayer, BatchNormalizationLayer, FuseBatchNorm<Convolution2dLayer, armnn::DataType::Float32> >
Definition at line 187 of file FuseBatchNorm.hpp.
FuseBatchNormIntoDepthwiseConvolution2DFloat16
using FuseBatchNormIntoDepthwiseConvolution2DFloat16 = OptimizeForExclusiveConnection<DepthwiseConvolution2dLayer, BatchNormalizationLayer, FuseBatchNorm<DepthwiseConvolution2dLayer, armnn::DataType::Float16> >
Definition at line 202 of file FuseBatchNorm.hpp.
FuseBatchNormIntoDepthwiseConvolution2DFloat32
using FuseBatchNormIntoDepthwiseConvolution2DFloat32 = OptimizeForExclusiveConnection<DepthwiseConvolution2dLayer, BatchNormalizationLayer, FuseBatchNorm<DepthwiseConvolution2dLayer, armnn::DataType::Float32> >
Definition at line 197 of file FuseBatchNorm.hpp.
InsertDebugLayer
using InsertDebugLayer = OptimizeForType<Layer, AddDebugImpl>
Definition at line 34 of file AddDebug.hpp.
MovePermuteUp
using MovePermuteUp = OptimizeForConnection<Layer, PermuteLayer, MovePermuteUpImpl>
Definition at line 77 of file MovePermuteUp.hpp.
MoveTransposeUp
using MoveTransposeUp = OptimizeForConnection<Layer, TransposeLayer, MoveTransposeUpImpl>
Definition at line 77 of file MoveTransposeUp.hpp.
OptimizeConsecutiveReshapes
using OptimizeConsecutiveReshapes = OptimizeForConnection<ReshapeLayer, ReshapeLayer, OptimizeConsecutiveReshapesImpl>
Definition at line 61 of file OptimizeConsecutiveReshapes.hpp.
OptimizeInverseConversionsFp16
using OptimizeInverseConversionsFp16 = OptimizeForConnection<ConvertFp16ToFp32Layer, ConvertFp32ToFp16Layer, OptimizeInverseConversionsImpl>
Definition at line 42 of file OptimizeInverseConversions.hpp.
OptimizeInverseConversionsFp32
using OptimizeInverseConversionsFp32 = OptimizeForConnection<ConvertFp32ToFp16Layer, ConvertFp16ToFp32Layer, OptimizeInverseConversionsImpl>
Definition at line 44 of file OptimizeInverseConversions.hpp.
OptimizeInversePermutes
using OptimizeInversePermutes = OptimizeForConnection<PermuteLayer, PermuteLayer, OptimizeInversePermutesImpl<PermuteLayer> >
Definition at line 43 of file OptimizeInversePermutes.hpp.
OptimizeInverseTransposes
using OptimizeInverseTransposes = OptimizeForConnection<TransposeLayer, TransposeLayer, OptimizeInversePermutesImpl<TransposeLayer> >
Definition at line 45 of file OptimizeInversePermutes.hpp.
PermuteAndBatchToSpaceAsDepthToSpace
using PermuteAndBatchToSpaceAsDepthToSpace = OptimizeForConnection<PermuteLayer, BatchToSpaceNdLayer, PermuteAndBatchToSpaceAsDepthToSpaceImpl<PermuteLayer> >
Definition at line 102 of file PermuteAndBatchToSpaceAsDepthToSpace.hpp.
PermuteAsReshape
using PermuteAsReshape = OptimizeForType<PermuteLayer, PermuteAsReshapeImpl>
Definition at line 66 of file PermuteAsReshape.hpp.
SquashEqualPermuteSiblings
using SquashEqualPermuteSiblings = OptimizeForConnection<Layer, PermuteLayer, SquashEqualSiblingsImpl<PermuteLayer> >
Definition at line 67 of file SquashEqualSiblings.hpp.
SquashEqualReshapeSiblings
using SquashEqualReshapeSiblings = OptimizeForConnection<Layer, ReshapeLayer, SquashEqualSiblingsImpl<ReshapeLayer> >
Definition at line 70 of file SquashEqualSiblings.hpp.
SquashEqualTransposeSiblings
using SquashEqualTransposeSiblings = OptimizeForConnection<Layer, TransposeLayer, SquashEqualSiblingsImpl<TransposeLayer> >
Definition at line 69 of file SquashEqualSiblings.hpp.
TransposeAndBatchToSpaceAsDepthToSpace
using TransposeAndBatchToSpaceAsDepthToSpace = OptimizeForConnection<TransposeLayer, BatchToSpaceNdLayer, PermuteAndBatchToSpaceAsDepthToSpaceImpl<TransposeLayer> >
Definition at line 104 of file PermuteAndBatchToSpaceAsDepthToSpace.hpp.
TransposeAsReshape
using TransposeAsReshape = OptimizeForType<TransposeLayer, TransposeAsReshapeImpl>
Definition at line 77 of file TransposeAsReshape.hpp.
Function Documentation
ConvertWeight()
LayerT* armnn::optimizations::ConvertWeight (Layer * l) inline
Definition at line 18 of file ConvertFp32NetworkToBf16.hpp.
References armnn::BFloat16, FloatingPointConverter::ConvertFloat32ToBFloat16(), armnn::Convolution2d, armnn::Float32, armnn::FullyConnected, TensorInfo::GetDataType(), TensorInfo::GetNumElements(), and armnn::info.
 {
     LayerT* layer = PolymorphicDowncast<LayerT*>(l);
     if ((layer->GetType() == LayerType::Convolution2d || layer->GetType() == LayerType::FullyConnected)
          && layer->m_Weight)
     {
         const TensorInfo& info = layer->m_Weight->GetTensorInfo();
         if (info.GetDataType() == DataType::Float32)
         {
             std::vector<BFloat16> newValues(info.GetNumElements());
             armnnUtils::FloatingPointConverter::ConvertFloat32ToBFloat16(
                     layer->m_Weight->template GetConstTensor<float>(),
                     info.GetNumElements(),
                     newValues.data());
             TensorInfo newInfo(info);
             newInfo.SetDataType(DataType::BFloat16);
             ConstTensor newInput(newInfo, newValues);
             layer->m_Weight.reset(new ScopedTensorHandle(newInput));
         }
     }
     return layer;
 }