ArmNN: NormalizationLayerBuilder Struct Reference
NormalizationLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef NormalizationLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::NormalizationDescriptor > descriptor)
NormalizationLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
NormalizationLayerBuilder & operator= (const NormalizationLayerBuilder &)
flatbuffers::Offset< NormalizationLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5612 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef NormalizationLayer Table
Definition at line 5613 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
NormalizationLayerBuilder()
NormalizationLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5622 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 5616 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateNormalizationLayer().
{
     fbb_.AddOffset(NormalizationLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::NormalizationDescriptor > descriptor) inline
Definition at line 5619 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateNormalizationLayer().
{
     fbb_.AddOffset(NormalizationLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<NormalizationLayer> Finish () inline
Definition at line 5627 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateNormalizationLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<NormalizationLayer>(end);
     return o;
   }
operator=()
NormalizationLayerBuilder& operator= (const NormalizationLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5614 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5615 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h