ArmNN: MeanDescriptorBuilder Struct Reference
MeanDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef MeanDescriptor Table
Public Member Functions
void add_axis (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis)
void add_keepDims (bool keepDims)
MeanDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
MeanDescriptorBuilder & operator= (const MeanDescriptorBuilder &)
flatbuffers::Offset< MeanDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5821 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef MeanDescriptor Table
Definition at line 5822 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
MeanDescriptorBuilder()
MeanDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5831 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_axis()
void add_axis (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis) inline
Definition at line 5825 of file ArmnnSchema_generated.h.
References VT_AXIS.
Referenced by armnnSerializer::CreateMeanDescriptor().
{
     fbb_.AddOffset(MeanDescriptor::VT_AXIS, axis);
   }
add_keepDims()
void add_keepDims (bool keepDims) inline
Definition at line 5828 of file ArmnnSchema_generated.h.
References VT_KEEPDIMS.
Referenced by armnnSerializer::CreateMeanDescriptor().
{
     fbb_.AddElement<uint8_t>(MeanDescriptor::VT_KEEPDIMS, static_cast<uint8_t>(keepDims), 0);
   }
Finish()
flatbuffers::Offset<MeanDescriptor> Finish () inline
Definition at line 5836 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateMeanDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<MeanDescriptor>(end);
     return o;
   }
operator=()
MeanDescriptorBuilder& operator= (const MeanDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5823 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5824 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h