ArmNN: LstmLayerBuilder Struct Reference
LstmLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef LstmLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::LstmDescriptor > descriptor)
void add_inputParams (flatbuffers::Offset< armnnSerializer::LstmInputParams > inputParams)
LstmLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
LstmLayerBuilder & operator= (const LstmLayerBuilder &)
flatbuffers::Offset< LstmLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7609 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef LstmLayer Table
Definition at line 7610 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
LstmLayerBuilder()
LstmLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7622 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 7613 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateLstmLayer().
{
     fbb_.AddOffset(LstmLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::LstmDescriptor > descriptor) inline
Definition at line 7616 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateLstmLayer().
{
     fbb_.AddOffset(LstmLayer::VT_DESCRIPTOR, descriptor);
   }
add_inputParams()
void add_inputParams (flatbuffers::Offset< armnnSerializer::LstmInputParams > inputParams) inline
Definition at line 7619 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLstmLayer().
{
     fbb_.AddOffset(LstmLayer::VT_INPUTPARAMS, inputParams);
   }
Finish()
flatbuffers::Offset<LstmLayer> Finish () inline
Definition at line 7627 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLstmLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<LstmLayer>(end);
     return o;
   }
operator=()
LstmLayerBuilder& operator= (const LstmLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7611 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7612 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h