ArmNN: LstmDescriptorBuilder Struct Reference
LstmDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef LstmDescriptor Table
Public Member Functions
void add_activationFunc (uint32_t activationFunc)
void add_clippingThresCell (float clippingThresCell)
void add_clippingThresProj (float clippingThresProj)
void add_cifgEnabled (bool cifgEnabled)
void add_peepholeEnabled (bool peepholeEnabled)
void add_projectionEnabled (bool projectionEnabled)
void add_layerNormEnabled (bool layerNormEnabled)
LstmDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
LstmDescriptorBuilder & operator= (const LstmDescriptorBuilder &)
flatbuffers::Offset< LstmDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 7524 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef LstmDescriptor Table
Definition at line 7525 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
LstmDescriptorBuilder()
LstmDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 7549 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_activationFunc()
void add_activationFunc (uint32_t activationFunc) inline
Definition at line 7528 of file ArmnnSchema_generated.h.
References VT_ACTIVATIONFUNC.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<uint32_t>(LstmDescriptor::VT_ACTIVATIONFUNC, activationFunc, 0);
   }
add_cifgEnabled()
void add_cifgEnabled (bool cifgEnabled) inline
Definition at line 7537 of file ArmnnSchema_generated.h.
References VT_CIFGENABLED.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(LstmDescriptor::VT_CIFGENABLED, static_cast<uint8_t>(cifgEnabled), 1);
   }
add_clippingThresCell()
void add_clippingThresCell (float clippingThresCell) inline
Definition at line 7531 of file ArmnnSchema_generated.h.
References VT_CLIPPINGTHRESCELL.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<float>(LstmDescriptor::VT_CLIPPINGTHRESCELL, clippingThresCell, 0.0f);
   }
add_clippingThresProj()
void add_clippingThresProj (float clippingThresProj) inline
Definition at line 7534 of file ArmnnSchema_generated.h.
References VT_CLIPPINGTHRESPROJ.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<float>(LstmDescriptor::VT_CLIPPINGTHRESPROJ, clippingThresProj, 0.0f);
   }
add_layerNormEnabled()
void add_layerNormEnabled (bool layerNormEnabled) inline
Definition at line 7546 of file ArmnnSchema_generated.h.
References VT_LAYERNORMENABLED.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(LstmDescriptor::VT_LAYERNORMENABLED, static_cast<uint8_t>(layerNormEnabled), 0);
   }
add_peepholeEnabled()
void add_peepholeEnabled (bool peepholeEnabled) inline
Definition at line 7540 of file ArmnnSchema_generated.h.
References VT_PEEPHOLEENABLED.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(LstmDescriptor::VT_PEEPHOLEENABLED, static_cast<uint8_t>(peepholeEnabled), 0);
   }
add_projectionEnabled()
void add_projectionEnabled (bool projectionEnabled) inline
Definition at line 7543 of file ArmnnSchema_generated.h.
References VT_PROJECTIONENABLED.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     fbb_.AddElement<uint8_t>(LstmDescriptor::VT_PROJECTIONENABLED, static_cast<uint8_t>(projectionEnabled), 0);
   }
Finish()
flatbuffers::Offset<LstmDescriptor> Finish () inline
Definition at line 7554 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLstmDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<LstmDescriptor>(end);
     return o;
   }
operator=()
LstmDescriptorBuilder& operator= (const LstmDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 7526 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 7527 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h