ArmNN: JSONTimelineDecoder::JSONEntity Struct Reference
JSONTimelineDecoder::JSONEntity Struct Reference
#include <JSONTimelineDecoder.hpp>
Public Member Functions
JSONEntity (uint64_t guid)
uint64_t GetGuid ()
std::string GetName ()
std::string GetType ()
void SetName (std::string entityName)
void SetType (std::string entityType)
void SetParent (JSONEntity &parent)
void AddConnection (JSONEntity &headEntity, JSONEntity &connectedEntity)
Public Attributes
std::vector< uint64_t > connected_entities
std::vector< uint64_t > childEntities
std::map< std::string, std::string > extendedData
Detailed Description
Definition at line 21 of file JSONTimelineDecoder.hpp.
Constructor & Destructor Documentation
JSONEntity()
JSONEntity (uint64_t guid) inline
Definition at line 27 of file JSONTimelineDecoder.hpp.
References JSONTimelineDecoder::JSONEntity::AddConnection(), JSONTimelineDecoder::JSONEntity::GetGuid(), JSONTimelineDecoder::JSONEntity::GetName(), JSONTimelineDecoder::JSONEntity::GetType(), JSONTimelineDecoder::JSONEntity::SetName(), JSONTimelineDecoder::JSONEntity::SetParent(), and JSONTimelineDecoder::JSONEntity::SetType().
 : m_Guid(guid){}
Member Function Documentation
AddConnection()
void AddConnection (JSONEntity & headEntity, JSONEntity & connectedEntity)
Definition at line 359 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::JSONEntity::childEntities, JSONTimelineDecoder::JSONEntity::connected_entities, and JSONTimelineDecoder::JSONEntity::GetGuid().
Referenced by JSONTimelineDecoder::CreateRelationship(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     std::vector<uint64_t>::iterator it = std::find(headEntity.childEntities.begin(),
             headEntity.childEntities.end(), connectedEntity.GetGuid());
     headEntity.childEntities.erase(it);
     headEntity.connected_entities.push_back(connectedEntity.m_Guid);
 }
GetGuid()
uint64_t GetGuid ()
Definition at line 367 of file JSONTimelineDecoder.cpp.
Referenced by JSONTimelineDecoder::JSONEntity::AddConnection(), JSONTimelineDecoder::CreateEvent(), JSONTimelineDecoder::GetJSONEntityString(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     return m_Guid;
 }
GetName()
std::string GetName ()
Definition at line 382 of file JSONTimelineDecoder.cpp.
Referenced by JSONTimelineDecoder::GetJSONEntityString(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     return this->name;
 }
GetType()
std::string GetType ()
Definition at line 392 of file JSONTimelineDecoder.cpp.
Referenced by JSONTimelineDecoder::GetJSONEntityString(), JSONTimelineDecoder::GetJSONString(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     return this->type;
 }
SetName()
void SetName (std::string entityName)
Definition at line 377 of file JSONTimelineDecoder.cpp.
Referenced by JSONTimelineDecoder::CreateRelationship(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     this->name = entityName;
 }
SetParent()
void SetParent (JSONEntity & parent)
Definition at line 239 of file JSONTimelineDecoder.cpp.
References JSONTimelineDecoder::JSONEntity::childEntities.
Referenced by JSONTimelineDecoder::CreateRelationship(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     parent.childEntities.push_back(GetGuid());
 }
SetType()
void SetType (std::string entityType)
Definition at line 387 of file JSONTimelineDecoder.cpp.
Referenced by JSONTimelineDecoder::CreateEntity(), JSONTimelineDecoder::CreateEvent(), JSONTimelineDecoder::CreateEventClass(), JSONTimelineDecoder::CreateRelationship(), and JSONTimelineDecoder::JSONEntity::JSONEntity().
 {
     this->type = entityType;
 }
Member Data Documentation
childEntities
std::vector<uint64_t> childEntities
Definition at line 25 of file JSONTimelineDecoder.hpp.
Referenced by JSONTimelineDecoder::JSONEntity::AddConnection(), JSONTimelineDecoder::GetJSONEntityString(), JSONTimelineDecoder::GetJSONString(), and JSONTimelineDecoder::JSONEntity::SetParent().
connected_entities
std::vector<uint64_t> connected_entities
Definition at line 24 of file JSONTimelineDecoder.hpp.
Referenced by JSONTimelineDecoder::JSONEntity::AddConnection().
extendedData
std::map<std::string, std::string> extendedData
Definition at line 35 of file JSONTimelineDecoder.hpp.
Referenced by JSONTimelineDecoder::CreateRelationship(), and JSONTimelineDecoder::GetJSONEntityString().
The documentation for this struct was generated from the following files:
src/timelineDecoder/JSONTimelineDecoder.hpp
src/timelineDecoder/JSONTimelineDecoder.cpp