ArmNN: DepthToSpaceDescriptorBuilder Struct Reference
DepthToSpaceDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef DepthToSpaceDescriptor Table
Public Member Functions
void add_blockSize (uint32_t blockSize)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
DepthToSpaceDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
DepthToSpaceDescriptorBuilder & operator= (const DepthToSpaceDescriptorBuilder &)
flatbuffers::Offset< DepthToSpaceDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 3131 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef DepthToSpaceDescriptor Table
Definition at line 3132 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
DepthToSpaceDescriptorBuilder()
DepthToSpaceDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3141 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_blockSize()
void add_blockSize (uint32_t blockSize) inline
Definition at line 3135 of file ArmnnSchema_generated.h.
References VT_BLOCKSIZE.
Referenced by armnnSerializer::CreateDepthToSpaceDescriptor().
{
     fbb_.AddElement<uint32_t>(DepthToSpaceDescriptor::VT_BLOCKSIZE, blockSize, 0);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 3138 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateDepthToSpaceDescriptor().
{
     fbb_.AddElement<int8_t>(DepthToSpaceDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
Finish()
flatbuffers::Offset<DepthToSpaceDescriptor> Finish () inline
Definition at line 3146 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateDepthToSpaceDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<DepthToSpaceDescriptor>(end);
     return o;
   }
operator=()
DepthToSpaceDescriptorBuilder& operator= (const DepthToSpaceDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 3133 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 3134 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h