ArmNN: SerializedGraphBuilder Struct Reference
SerializedGraphBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SerializedGraph Table
Public Member Functions
void add_layers (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::AnyLayer >>> layers)
void add_inputIds (flatbuffers::Offset< flatbuffers::Vector< int32_t >> inputIds)
void add_outputIds (flatbuffers::Offset< flatbuffers::Vector< int32_t >> outputIds)
void add_featureVersions (flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > featureVersions)
SerializedGraphBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SerializedGraphBuilder & operator= (const SerializedGraphBuilder &)
flatbuffers::Offset< SerializedGraph > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9930 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SerializedGraph Table
Definition at line 9931 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SerializedGraphBuilder()
SerializedGraphBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9946 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_featureVersions()
void add_featureVersions (flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > featureVersions) inline
Definition at line 9943 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSerializedGraph().
{
     fbb_.AddOffset(SerializedGraph::VT_FEATUREVERSIONS, featureVersions);
   }
add_inputIds()
void add_inputIds (flatbuffers::Offset< flatbuffers::Vector< int32_t >> inputIds) inline
Definition at line 9937 of file ArmnnSchema_generated.h.
References VT_INPUTIDS.
Referenced by armnnSerializer::CreateSerializedGraph().
{
     fbb_.AddOffset(SerializedGraph::VT_INPUTIDS, inputIds);
   }
add_layers()
void add_layers (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::AnyLayer >>> layers) inline
Definition at line 9934 of file ArmnnSchema_generated.h.
References VT_LAYERS.
Referenced by armnnSerializer::CreateSerializedGraph().
{
     fbb_.AddOffset(SerializedGraph::VT_LAYERS, layers);
   }
add_outputIds()
void add_outputIds (flatbuffers::Offset< flatbuffers::Vector< int32_t >> outputIds) inline
Definition at line 9940 of file ArmnnSchema_generated.h.
References VT_OUTPUTIDS.
Referenced by armnnSerializer::CreateSerializedGraph().
{
     fbb_.AddOffset(SerializedGraph::VT_OUTPUTIDS, outputIds);
   }
Finish()
flatbuffers::Offset<SerializedGraph> Finish () inline
Definition at line 9951 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSerializedGraph().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SerializedGraph>(end);
     return o;
   }
operator=()
SerializedGraphBuilder& operator= (const SerializedGraphBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9932 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9933 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h