ArmNN: InstanceNormalizationDescriptorBuilder Struct Reference
InstanceNormalizationDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef InstanceNormalizationDescriptor Table
Public Member Functions
void add_gamma (float gamma)
void add_beta (float beta)
void add_eps (float eps)
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
InstanceNormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
InstanceNormalizationDescriptorBuilder & operator= (const InstanceNormalizationDescriptorBuilder &)
flatbuffers::Offset< InstanceNormalizationDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 3890 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef InstanceNormalizationDescriptor Table
Definition at line 3891 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
InstanceNormalizationDescriptorBuilder()
InstanceNormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3906 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_beta()
void add_beta (float beta) inline
Definition at line 3897 of file ArmnnSchema_generated.h.
References VT_BETA.
Referenced by armnnSerializer::CreateInstanceNormalizationDescriptor().
{
     fbb_.AddElement<float>(InstanceNormalizationDescriptor::VT_BETA, beta, 0.0f);
   }
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 3903 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateInstanceNormalizationDescriptor().
{
     fbb_.AddElement<int8_t>(InstanceNormalizationDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 0);
   }
add_eps()
void add_eps (float eps) inline
Definition at line 3900 of file ArmnnSchema_generated.h.
References VT_EPS.
Referenced by armnnSerializer::CreateInstanceNormalizationDescriptor().
{
     fbb_.AddElement<float>(InstanceNormalizationDescriptor::VT_EPS, eps, 0.0f);
   }
add_gamma()
void add_gamma (float gamma) inline
Definition at line 3894 of file ArmnnSchema_generated.h.
References VT_GAMMA.
Referenced by armnnSerializer::CreateInstanceNormalizationDescriptor().
{
     fbb_.AddElement<float>(InstanceNormalizationDescriptor::VT_GAMMA, gamma, 0.0f);
   }
Finish()
flatbuffers::Offset<InstanceNormalizationDescriptor> Finish () inline
Definition at line 3911 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateInstanceNormalizationDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<InstanceNormalizationDescriptor>(end);
     return o;
   }
operator=()
InstanceNormalizationDescriptorBuilder& operator= (const InstanceNormalizationDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 3892 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 3893 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h