ArmNN: ReduceDescriptorBuilder Struct Reference
ReduceDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ReduceDescriptor Table
Public Member Functions
void add_keepDims (bool keepDims)
void add_axis (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis)
void add_reduceOperation (armnnSerializer::ReduceOperation reduceOperation)
ReduceDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ReduceDescriptorBuilder & operator= (const ReduceDescriptorBuilder &)
flatbuffers::Offset< ReduceDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 9315 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ReduceDescriptor Table
Definition at line 9316 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ReduceDescriptorBuilder()
ReduceDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 9328 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_axis()
void add_axis (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis) inline
Definition at line 9322 of file ArmnnSchema_generated.h.
References VT_AXIS.
Referenced by armnnSerializer::CreateReduceDescriptor().
{
     fbb_.AddOffset(ReduceDescriptor::VT_AXIS, axis);
   }
add_keepDims()
void add_keepDims (bool keepDims) inline
Definition at line 9319 of file ArmnnSchema_generated.h.
References VT_KEEPDIMS.
Referenced by armnnSerializer::CreateReduceDescriptor().
{
     fbb_.AddElement<uint8_t>(ReduceDescriptor::VT_KEEPDIMS, static_cast<uint8_t>(keepDims), 0);
   }
add_reduceOperation()
void add_reduceOperation (armnnSerializer::ReduceOperation reduceOperation) inline
Definition at line 9325 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateReduceDescriptor().
{
     fbb_.AddElement<int8_t>(ReduceDescriptor::VT_REDUCEOPERATION, static_cast<int8_t>(reduceOperation), 0);
   }
Finish()
flatbuffers::Offset<ReduceDescriptor> Finish () inline
Definition at line 9333 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateReduceDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ReduceDescriptor>(end);
     return o;
   }
operator=()
ReduceDescriptorBuilder& operator= (const ReduceDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 9317 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 9318 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h