ArmNN: src/backends/backendsCommon/test/layerTests/Conv3dTestImpl.hpp File Reference
Conv3dTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <Half.hpp>
#include <ResolveType.hpp>
#include <armnn/Types.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 5 > SimpleConvolution3d3x3x3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int8_t, 5 > SimpleConvolution3d3x3x3Int8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > SimpleConvolution3d3x3x3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > SimpleConvolution3d3x3x3Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > Convolution3d2x2x2Strides3x5x5Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int8_t, 5 > Convolution3d2x2x2Strides3x5x5Int8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > Convolution3d2x2x2Strides3x5x5Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > Convolution3d2x2x2Strides3x5x5Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > Convolution3d2x2x2Dilation2x2x2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int8_t, 5 > Convolution3d2x2x2Dilation2x2x2Int8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > Convolution3d2x2x2Dilation2x2x2Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > Convolution3d2x2x2Dilation2x2x2Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > Convolution3dPaddingSame3x3x3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int8_t, 5 > Convolution3dPaddingSame3x3x3Int8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< uint8_t, 5 > Convolution3dPaddingSame3x3x3Uint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< int16_t, 5 > Convolution3dPaddingSame3x3x3Int16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > Convolution3dStrideDilationPadding3x3x3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< float, 5 > Convolution3d2x2x2Stride3x3x3SmallFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< armnn::Half, 5 > Convolution3d2x3x3Float16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
LayerTestResult< armnn::Half, 5 > Convolution3d2x2x2SmallFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Function Documentation
Convolution3d2x2x2Dilation2x2x2Float32Test()
LayerTestResult<float, 5> Convolution3d2x2x2Dilation2x2x2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 948 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Dilation2x2x2TestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Dilation2x2x2Int16Test()
LayerTestResult<int16_t, 5> Convolution3d2x2x2Dilation2x2x2Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 981 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Dilation2x2x2TestCommon<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Dilation2x2x2Int8Test()
LayerTestResult<int8_t , 5> Convolution3d2x2x2Dilation2x2x2Int8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 959 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Dilation2x2x2TestCommon<armnn::DataType::QAsymmS8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Dilation2x2x2Uint8Test()
LayerTestResult<uint8_t, 5> Convolution3d2x2x2Dilation2x2x2Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 970 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Dilation2x2x2TestCommon<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2SmallFloat16Test()
LayerTestResult<armnn::Half, 5> Convolution3d2x2x2SmallFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1069 of file Conv3dTestImpl.cpp.
References Convolution3d2x2x2SmallTestCommonFloat16().
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2SmallTestCommonFloat16(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Stride3x3x3SmallFloat32Test()
LayerTestResult<float, 5> Convolution3d2x2x2Stride3x3x3SmallFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1047 of file Conv3dTestImpl.cpp.
References Convolution3d2x2x2Stride3x3x3SmallTestCommonFloat32().
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Stride3x3x3SmallTestCommonFloat32(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Strides3x5x5Float32Test()
LayerTestResult<float, 5> Convolution3d2x2x2Strides3x5x5Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 904 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Strides3x5x5TestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Strides3x5x5Int16Test()
LayerTestResult<int16_t, 5> Convolution3d2x2x2Strides3x5x5Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 937 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Strides3x5x5TestCommon<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Strides3x5x5Int8Test()
LayerTestResult<int8_t , 5> Convolution3d2x2x2Strides3x5x5Int8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 915 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Strides3x5x5TestCommon<armnn::DataType::QAsymmS8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x2x2Strides3x5x5Uint8Test()
LayerTestResult<uint8_t, 5> Convolution3d2x2x2Strides3x5x5Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 926 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3d2x2x2Strides3x5x5TestCommon<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3d2x3x3Float16Test()
LayerTestResult<armnn::Half, 5> Convolution3d2x3x3Float16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1058 of file Conv3dTestImpl.cpp.
References Convolution3d2x3x3TestCommonFloat16().
Referenced by TEST_SUITE().
 {
     return Convolution3d2x3x3TestCommonFloat16(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3dPaddingSame3x3x3Float32Test()
LayerTestResult<float, 5> Convolution3dPaddingSame3x3x3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 992 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3dPaddingSame3x3x3TestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3dPaddingSame3x3x3Int16Test()
LayerTestResult<int16_t, 5> Convolution3dPaddingSame3x3x3Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1025 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3dPaddingSame3x3x3TestCommon<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3dPaddingSame3x3x3Int8Test()
LayerTestResult<int8_t , 5> Convolution3dPaddingSame3x3x3Int8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1003 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3dPaddingSame3x3x3TestCommon<armnn::DataType::QAsymmS8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3dPaddingSame3x3x3Uint8Test()
LayerTestResult<uint8_t, 5> Convolution3dPaddingSame3x3x3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1014 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return Convolution3dPaddingSame3x3x3TestCommon<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
Convolution3dStrideDilationPadding3x3x3Float32Test()
LayerTestResult<float, 5> Convolution3dStrideDilationPadding3x3x3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 1036 of file Conv3dTestImpl.cpp.
References Convolution3dStrideDilationPadding3x3x3TestCommonFloat32().
Referenced by TEST_SUITE().
 {
     return Convolution3dStrideDilationPadding3x3x3TestCommonFloat32(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
SimpleConvolution3d3x3x3Float32Test()
LayerTestResult<float, 5> SimpleConvolution3d3x3x3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 859 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution3d3x3x3TestCommon<armnn::DataType::Float32, armnn::DataType::Float32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
SimpleConvolution3d3x3x3Int16Test()
LayerTestResult<int16_t, 5> SimpleConvolution3d3x3x3Int16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 892 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution3d3x3x3TestCommon<armnn::DataType::QSymmS16, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
SimpleConvolution3d3x3x3Int8Test()
LayerTestResult<int8_t , 5> SimpleConvolution3d3x3x3Int8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 870 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution3d3x3x3TestCommon<armnn::DataType::QAsymmS8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }
SimpleConvolution3d3x3x3Uint8Test()
LayerTestResult<uint8_t, 5> SimpleConvolution3d3x3x3Uint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory, bool biasEnabled, armnn::DataLayout dataLayout)
Definition at line 881 of file Conv3dTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SimpleConvolution3d3x3x3TestCommon<armnn::DataType::QAsymmU8, armnn::DataType::Signed32>(
             workloadFactory, memoryManager, tensorHandleFactory, biasEnabled, dataLayout);
 }