ArmNN: src/backends/backendsCommon/test/layerTests/LogicalTestImpl.hpp File Reference
LogicalTestImpl.hpp File Reference
#include <armnnTestUtils/LayerTestResult.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <armnn/backends/WorkloadFactory.hpp>
Functions
LayerTestResult< uint8_t, 4 > LogicalNotTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalNotIntTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalAndTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalOrTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalAndIntTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalOrIntTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalAndBroadcast1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalOrBroadcast1Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalAndBroadcast2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalOrBroadcast2Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalAndBroadcast3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > LogicalOrBroadcast3Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
LogicalAndBroadcast1Test()
LayerTestResult<uint8_t, 4> LogicalAndBroadcast1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 466 of file LogicalTestImpl.cpp.
References armnn::LogicalAnd.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalAnd,
                                       s_BroadcastBinary1TestData.m_InputShape0,
                                       s_BroadcastBinary1TestData.m_InputShape1,
                                       s_BroadcastBinary1TestData.m_InputData0,
                                       s_BroadcastBinary1TestData.m_InputData1,
                                       s_BroadcastBinary1TestData.m_OutputShape,
                                       s_BroadcastBinary1TestData.m_OutputAnd,
                                       tensorHandleFactory);
 }
LogicalAndBroadcast2Test()
LayerTestResult<uint8_t, 4> LogicalAndBroadcast2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 502 of file LogicalTestImpl.cpp.
References armnn::LogicalAnd.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalAnd,
                                       s_BroadcastBinary2TestData.m_InputShape0,
                                       s_BroadcastBinary2TestData.m_InputShape1,
                                       s_BroadcastBinary2TestData.m_InputData0,
                                       s_BroadcastBinary2TestData.m_InputData1,
                                       s_BroadcastBinary2TestData.m_OutputShape,
                                       s_BroadcastBinary2TestData.m_OutputAnd,
                                       tensorHandleFactory);
 }
LogicalAndBroadcast3Test()
LayerTestResult<uint8_t, 4> LogicalAndBroadcast3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 538 of file LogicalTestImpl.cpp.
References armnn::LogicalAnd.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalAnd,
                                       s_BroadcastBinary3TestData.m_InputShape0,
                                       s_BroadcastBinary3TestData.m_InputShape1,
                                       s_BroadcastBinary3TestData.m_InputData0,
                                       s_BroadcastBinary3TestData.m_InputData1,
                                       s_BroadcastBinary3TestData.m_OutputShape,
                                       s_BroadcastBinary3TestData.m_OutputAnd,
                                       tensorHandleFactory);
 }
LogicalAndIntTest()
LayerTestResult<uint8_t, 4> LogicalAndIntTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 432 of file LogicalTestImpl.cpp.
References armnn::LogicalAnd.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalAnd,
                                       s_SimpleBinaryIntTestData.m_InputShape0,
                                       s_SimpleBinaryIntTestData.m_InputShape1,
                                       s_SimpleBinaryIntTestData.m_InputData0,
                                       s_SimpleBinaryIntTestData.m_InputData1,
                                       s_SimpleBinaryIntTestData.m_OutputShape,
                                       s_SimpleBinaryIntTestData.m_OutputAnd,
                                       tensorHandleFactory);
 }
LogicalAndTest()
LayerTestResult<uint8_t, 4> LogicalAndTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 398 of file LogicalTestImpl.cpp.
References armnn::LogicalAnd.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalAnd,
                                       s_SimpleBinaryTestData.m_InputShape0,
                                       s_SimpleBinaryTestData.m_InputShape1,
                                       s_SimpleBinaryTestData.m_InputData0,
                                       s_SimpleBinaryTestData.m_InputData1,
                                       s_SimpleBinaryTestData.m_OutputShape,
                                       s_SimpleBinaryTestData.m_OutputAnd,
                                       tensorHandleFactory);
 }
LogicalNotIntTest()
LayerTestResult<uint8_t, 4> LogicalNotIntTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 383 of file LogicalTestImpl.cpp.
References armnn::LogicalNot.
Referenced by TEST_SUITE().
 {
     return LogicalUnaryTestHelper<4>(workloadFactory,
                                      memoryManager,
                                      armnn::UnaryOperation::LogicalNot,
                                      s_SimpleUnaryIntTestData.m_InputShape,
                                      s_SimpleUnaryIntTestData.m_InputData,
                                      s_SimpleUnaryIntTestData.m_OutputShape,
                                      s_SimpleUnaryIntTestData.m_OutputNot,
                                      tensorHandleFactory);
 }
LogicalNotTest()
LayerTestResult<uint8_t, 4> LogicalNotTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 368 of file LogicalTestImpl.cpp.
References armnn::LogicalNot.
Referenced by TEST_SUITE().
 {
     return LogicalUnaryTestHelper<4>(workloadFactory,
                                      memoryManager,
                                      armnn::UnaryOperation::LogicalNot,
                                      s_SimpleUnaryTestData.m_InputShape,
                                      s_SimpleUnaryTestData.m_InputData,
                                      s_SimpleUnaryTestData.m_OutputShape,
                                      s_SimpleUnaryTestData.m_OutputNot,
                                      tensorHandleFactory);
 }
LogicalOrBroadcast1Test()
LayerTestResult<uint8_t, 4> LogicalOrBroadcast1Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 484 of file LogicalTestImpl.cpp.
References armnn::LogicalOr.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalOr,
                                       s_BroadcastBinary1TestData.m_InputShape0,
                                       s_BroadcastBinary1TestData.m_InputShape1,
                                       s_BroadcastBinary1TestData.m_InputData0,
                                       s_BroadcastBinary1TestData.m_InputData1,
                                       s_BroadcastBinary1TestData.m_OutputShape,
                                       s_BroadcastBinary1TestData.m_OutputOr,
                                       tensorHandleFactory);
 }
LogicalOrBroadcast2Test()
LayerTestResult<uint8_t, 4> LogicalOrBroadcast2Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 520 of file LogicalTestImpl.cpp.
References armnn::LogicalOr.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalOr,
                                       s_BroadcastBinary2TestData.m_InputShape0,
                                       s_BroadcastBinary2TestData.m_InputShape1,
                                       s_BroadcastBinary2TestData.m_InputData0,
                                       s_BroadcastBinary2TestData.m_InputData1,
                                       s_BroadcastBinary2TestData.m_OutputShape,
                                       s_BroadcastBinary2TestData.m_OutputOr,
                                       tensorHandleFactory);
 }
LogicalOrBroadcast3Test()
LayerTestResult<uint8_t, 4> LogicalOrBroadcast3Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 556 of file LogicalTestImpl.cpp.
References armnn::LogicalOr.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalOr,
                                       s_BroadcastBinary3TestData.m_InputShape0,
                                       s_BroadcastBinary3TestData.m_InputShape1,
                                       s_BroadcastBinary3TestData.m_InputData0,
                                       s_BroadcastBinary3TestData.m_InputData1,
                                       s_BroadcastBinary3TestData.m_OutputShape,
                                       s_BroadcastBinary3TestData.m_OutputOr,
                                       tensorHandleFactory);
 }
LogicalOrIntTest()
LayerTestResult<uint8_t, 4> LogicalOrIntTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 449 of file LogicalTestImpl.cpp.
References armnn::LogicalOr.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalOr,
                                       s_SimpleBinaryIntTestData.m_InputShape0,
                                       s_SimpleBinaryIntTestData.m_InputShape1,
                                       s_SimpleBinaryIntTestData.m_InputData0,
                                       s_SimpleBinaryIntTestData.m_InputData1,
                                       s_SimpleBinaryIntTestData.m_OutputShape,
                                       s_SimpleBinaryIntTestData.m_OutputOr,
                                       tensorHandleFactory);
 }
LogicalOrTest()
LayerTestResult<uint8_t, 4> LogicalOrTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 415 of file LogicalTestImpl.cpp.
References armnn::LogicalOr.
Referenced by TEST_SUITE().
 {
     return LogicalBinaryTestHelper<4>(workloadFactory,
                                       memoryManager,
                                       armnn::LogicalBinaryOperation::LogicalOr,
                                       s_SimpleBinaryTestData.m_InputShape0,
                                       s_SimpleBinaryTestData.m_InputShape1,
                                       s_SimpleBinaryTestData.m_InputData0,
                                       s_SimpleBinaryTestData.m_InputData1,
                                       s_SimpleBinaryTestData.m_OutputShape,
                                       s_SimpleBinaryTestData.m_OutputOr,
                                       tensorHandleFactory);
 }