ArmNN: src/backends/backendsCommon/test/layerTests/SplitterTestImpl.cpp File Reference
SplitterTestImpl.cpp File Reference
#include "SplitterTestImpl.hpp"
#include <armnnUtils/QuantizeHelper.hpp>
#include <ResolveType.hpp>
#include <armnnTestUtils/TensorCopyUtils.hpp>
#include <armnnTestUtils/WorkloadTestUtils.hpp>
#include <armnnTestUtils/TensorHelpers.hpp>
Functions
std::vector< LayerTestResult< float, 3 > > SplitterFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
std::vector< LayerTestResult< armnn::Half, 3 > > SplitterFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
std::vector< LayerTestResult< uint8_t, 3 > > SplitterUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
std::vector< LayerTestResult< int16_t, 3 > > SplitterInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > CopyViaSplitterFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 3 > CopyViaSplitterFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 3 > CopyViaSplitterUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 3 > CopyViaSplitterInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
CopyViaSplitterFloat16Test()
LayerTestResult<armnn::Half, 3> CopyViaSplitterFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 377 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CopyViaSplitterTestImpl<armnn::DataType::Float16>(workloadFactory,
                                                              memoryManager,
                                                              tensorHandleFactory,
                                                              0.0f,
                                                              0);
 }
CopyViaSplitterFloat32Test()
LayerTestResult<float, 3> CopyViaSplitterFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 365 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CopyViaSplitterTestImpl<armnn::DataType::Float32>(workloadFactory,
                                                              memoryManager,
                                                              tensorHandleFactory,
                                                              0.0f,
                                                              0);
 }
CopyViaSplitterInt16Test()
LayerTestResult<int16_t, 3> CopyViaSplitterInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 401 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CopyViaSplitterTestImpl<armnn::DataType::QSymmS16>(workloadFactory,
                                                               memoryManager,
                                                               tensorHandleFactory,
                                                               1.0f,
                                                               0);
 }
CopyViaSplitterUint8Test()
LayerTestResult<uint8_t, 3> CopyViaSplitterUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 389 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return CopyViaSplitterTestImpl<armnn::DataType::QAsymmU8>(workloadFactory,
                                                               memoryManager,
                                                               tensorHandleFactory,
                                                               1.0f,
                                                               0);
 }
SplitterFloat16Test()
std::vector<LayerTestResult<armnn::Half,3> > SplitterFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 341 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SplitterTestCommon<armnn::DataType::Float16>(workloadFactory, memoryManager, tensorHandleFactory);
 }
SplitterFloat32Test()
std::vector<LayerTestResult<float,3> > SplitterFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 333 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SplitterTestCommon<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
SplitterInt16Test()
std::vector<LayerTestResult<int16_t,3> > SplitterInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 357 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SplitterTestCommon<armnn::DataType::QSymmS16>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }
SplitterUint8Test()
std::vector<LayerTestResult<uint8_t,3> > SplitterUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 349 of file SplitterTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return SplitterTestCommon<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager, tensorHandleFactory, 1.0f, 0);
 }