ArmNN: src/armnnTestUtils/TestUtils.cpp File Reference
TestUtils.cpp File Reference
#include "TestUtils.hpp"
#include <armnn/utility/Assert.hpp>
#include "armnnTestUtils/Version.hpp"
Namespaces
armnn
Copyright (c) 2021 ARM Limited and Contributors.
Functions
void Connect (armnn::IConnectableLayer *from, armnn::IConnectableLayer *to, const armnn::TensorInfo &tensorInfo, unsigned int fromIndex, unsigned int toIndex)
Graph & GetGraphForTesting (IOptimizedNetwork *optNet)
ModelOptions & GetModelOptionsForTesting (IOptimizedNetwork *optNet)
arm::pipe::IProfilingService & GetProfilingService (armnn::RuntimeImpl *runtime)
Function Documentation
Connect()
void Connect (armnn::IConnectableLayer * from, armnn::IConnectableLayer * to, const armnn::TensorInfo & tensorInfo, unsigned int fromIndex, unsigned int toIndex)
Definition at line 14 of file TestUtils.cpp.
References ARMNN_ASSERT, IOutputSlot::Connect(), armnn::FullyConnected, IConnectableLayer::GetInputSlot(), armnn::GetLayerTypeAsCString(), IConnectableLayer::GetName(), IConnectableLayer::GetOutputSlot(), IConnectableLayer::GetType(), and IOutputSlot::SetTensorInfo().
Referenced by OutputSlot::Connect(), CreatePreluLayerHelper(), CreateStackLayerHelper(), armnn::experimental::CreateStridedSliceNetwork(), OutputSlot::GetOutputHandler(), QLstmEndToEnd(), and TEST_SUITE().
 {
     ARMNN_ASSERT(from);
     ARMNN_ASSERT(to);
     try
     {
         from->GetOutputSlot(fromIndex).Connect(to->GetInputSlot(toIndex));
     }
     catch (const std::out_of_range& exc)
     {
         std::ostringstream message;
         if (to->GetType() == armnn::LayerType::FullyConnected && toIndex == 2)
         {
             message << "Tried to connect bias to FullyConnected layer when bias is not enabled: ";
         }
         message << "Failed to connect to input slot "
                 << toIndex
                 << " on "
                 << GetLayerTypeAsCString(to->GetType())
                 << " layer "
                 << std::quoted(to->GetName())
                 << " as the slot does not exist or is unavailable";
         throw LayerValidationException(message.str());
     }
     from->GetOutputSlot(fromIndex).SetTensorInfo(tensorInfo);
 }