ArmNN: RequestCountersPacketHandler Class Reference
RequestCountersPacketHandler Class Reference
#include <RequestCountersPacketHandler.hpp>
Public Member Functions
RequestCountersPacketHandler (uint32_t capturePeriod=arm::pipe::LOWEST_CAPTURE_PERIOD)
std::vector< uint32_t > GetHeadersAccepted () override
void HandlePacket (const arm::pipe::Packet &packet) override
void SetConnection (IInternalProfilingConnection *profilingConnection) override
Detailed Description
Definition at line 21 of file RequestCountersPacketHandler.hpp.
Constructor & Destructor Documentation
RequestCountersPacketHandler()
RequestCountersPacketHandler (uint32_t capturePeriod = arm::pipe::LOWEST_CAPTURE_PERIOD) inline explicit
Definition at line 24 of file RequestCountersPacketHandler.hpp.
References RequestCountersPacketHandler::GetHeadersAccepted(), and RequestCountersPacketHandler::HandlePacket().
                                                                                                  :
         m_CapturePeriod(capturePeriod),
         m_Connection(nullptr),
         m_CounterDirectoryMessageHeader(ConstructHeader(0, 2)) {}
Member Function Documentation
GetHeadersAccepted()
std::vector< uint32_t > GetHeadersAccepted () override
Definition at line 20 of file RequestCountersPacketHandler.cpp.
Referenced by RequestCountersPacketHandler::RequestCountersPacketHandler().
 {
     std::vector<uint32_t> headers;
     headers.push_back(m_CounterDirectoryMessageHeader); // counter directory
     return headers;
 }
HandlePacket()
void HandlePacket (const arm::pipe::Packet & packet) override
Definition at line 27 of file RequestCountersPacketHandler.cpp.
References armnn::numeric_cast().
Referenced by RequestCountersPacketHandler::RequestCountersPacketHandler().
 {
     if (packet.GetHeader() != m_CounterDirectoryMessageHeader)
     {
         return;
     }
     arm::pipe::PacketVersionResolver packetVersionResolver;
     DirectoryCaptureCommandHandler directoryCaptureCommandHandler(
         "ARMNN", 0, 2, packetVersionResolver.ResolvePacketVersion(0, 2).GetEncodedValue());
     directoryCaptureCommandHandler.operator()(packet);
     const ICounterDirectory& counterDirectory = directoryCaptureCommandHandler.GetCounterDirectory();
     for (auto& category : counterDirectory.GetCategories())
     {
         // Remember we need to translate the Uid's from our CounterDirectory instance to the parent one.
         std::vector<uint16_t> translatedCounters;
         for (auto const& copyUid : category->m_Counters)
         {
             translatedCounters.emplace_back(directoryCaptureCommandHandler.TranslateUIDCopyToOriginal(copyUid));
         }
         m_IdList.insert(std::end(m_IdList), std::begin(translatedCounters), std::end(translatedCounters));
     }
     SendCounterSelectionPacket();
 }
SetConnection()
void SetConnection (IInternalProfilingConnection * profilingConnection) inline override
Definition at line 33 of file RequestCountersPacketHandler.hpp.
     {
         m_Connection = profilingConnection;
     }
The documentation for this class was generated from the following files:
src/profiling/test/RequestCountersPacketHandler.hpp
src/profiling/test/RequestCountersPacketHandler.cpp