ArmNN: ConvertFp32NetworkToBf16Impl Class Reference
ConvertFp32NetworkToBf16Impl Class Reference
#include <ConvertFp32NetworkToBf16.hpp>
Public Member Functions
void Run (Graph &graph, Layer &layer) const
Protected Member Functions
ConvertFp32NetworkToBf16Impl ()=default
~ConvertFp32NetworkToBf16Impl ()=default
Detailed Description
Definition at line 44 of file ConvertFp32NetworkToBf16.hpp.
Constructor & Destructor Documentation
ConvertFp32NetworkToBf16Impl()
ConvertFp32NetworkToBf16Impl () protected default
Referenced by ConvertFp32NetworkToBf16Impl::Run().
~ConvertFp32NetworkToBf16Impl()
~ConvertFp32NetworkToBf16Impl () protected default
Referenced by ConvertFp32NetworkToBf16Impl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, Layer & layer) const inline
Definition at line 48 of file ConvertFp32NetworkToBf16.hpp.
References ConvertFp32NetworkToBf16Impl::ConvertFp32NetworkToBf16Impl(), armnn::Convolution2d, armnn::Float32, armnn::FullyConnected, Layer::GetDataType(), Layer::GetType(), armnn::InsertConvertFp32ToBf16LayersBefore(), and ConvertFp32NetworkToBf16Impl::~ConvertFp32NetworkToBf16Impl().
     {
         // Only convert Float32 To BFloat16 for the Input of Convolution2d layer and FullyConnected layer.
         // And also convert weight data type from Float32 to Bfloat16.
         // Do not convert bias data type.
         if (layer.GetType() == LayerType::Convolution2d)
         {
             if (layer.GetDataType() == DataType::Float32)
             {
                 InsertConvertFp32ToBf16LayersBefore(graph,layer);
                 ConvertWeight<Convolution2dLayer>(&layer);
             }
         }
         else if (layer.GetType() == LayerType::FullyConnected)
         {
             if (layer.GetDataType() == DataType::Float32)
             {
                 InsertConvertFp32ToBf16LayersBefore(graph,layer);
                 ConvertWeight<FullyConnectedLayer>(&layer);
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/ConvertFp32NetworkToBf16.hpp