ArmNN: MockBackend Class Reference
MockBackend Class Reference
#include <MockBackend.hpp>
Public Member Functions
MockBackend ()=default
~MockBackend ()=default
const BackendId & GetId () const override
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IBackendInternal::IMemoryManagerSharedPtr &memoryManager=nullptr) const override
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport () const override
IBackendInternal::IMemoryManagerUniquePtr CreateMemoryManager () const override
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const override
Create the runtime context of the backend.
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions &creationOptions, IBackendProfilingPtr &backendProfiling) override
Create context specifically used for profiling interaction from backends.
OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph) const override
std::unique_ptr< ICustomAllocator > GetDefaultAllocator () const override
Returns the default memory allocator for the backend.
Public Member Functions inherited from IBackendInternal
~IBackendInternal () override=default
Allow backends created by the factory function to be destroyed through IBackendInternal.
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (const IMemoryManagerSharedPtr &memoryManager, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions) const
virtual IWorkloadFactoryPtr CreateWorkloadFactory (class TensorHandleFactoryRegistry &tensorHandleFactoryRegistry, const ModelOptions &modelOptions, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags) const
virtual IBackendSpecificModelContextPtr CreateBackendSpecificModelContext (const ModelOptions &modelOptions) const
virtual ILayerSupportSharedPtr GetLayerSupport (const ModelOptions &modelOptions) const
virtual OptimizationViews OptimizeSubgraphView (const SubgraphView &subgraph, const ModelOptions &modelOptions) const
bool SupportsTensorAllocatorAPI () const
ITensorHandleFactory::FactoryId GetBackwardCompatibleFavoriteHandleFactory ()
virtual std::vector< ITensorHandleFactory::FactoryId > GetHandleFactoryPreferences () const
(Optional) Returns a vector of supported TensorHandleFactory ids in preference order.
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &)
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
virtual void RegisterTensorHandleFactories (class TensorHandleFactoryRegistry &registry, MemorySourceFlags inputFlags, MemorySourceFlags outputFlags)
(Optional) Register TensorHandleFactories Either this method or CreateMemoryManager() and IWorkloadFactory::CreateTensor()/IWorkloadFactory::CreateSubtensor() methods must be implemented.
virtual BackendCapabilities GetCapabilities () const
Returns a BackendCapability if the backend lists the capability The BackendCapability must then be inspected to check whether or not that BackendCapability is supported Otherwise returns an EmptyOptional if the BackendCapability is unlisted.
virtual bool HasCapability (BackendCapability) const
Returns true if backend support the capability false otherwise.
virtual bool UseCustomMemoryAllocator (std::shared_ptr< ICustomAllocator > allocator, armnn::Optional< std::string &> errMsg)
Signals the backend to use a custom memory allocator provided by the user.
virtual unsigned int GetNumberOfCacheFiles () const
Returns the number of files cached if backend supports caching.
Static Public Member Functions
static const BackendId & GetIdStatic ()
Static Public Member Functions inherited from IBackendInternal
static constexpr BackendVersion GetApiVersion ()
Returns the version of the Backend API.
Additional Inherited Members
Public Types inherited from IBackendInternal
using IWorkloadFactoryPtr = std::unique_ptr< IWorkloadFactory >
using IBackendContextPtr = std::unique_ptr< IBackendContext >
using IBackendProfilingContextPtr = std::shared_ptr< arm::pipe::IBackendProfilingContext >
This is the bridge between backend and backend profiling we'll keep it in the backend namespace.
using IBackendProfilingPtr = std::unique_ptr< arm::pipe::IBackendProfiling >
using ILayerSupportSharedPtr = std::shared_ptr< ILayerSupport >
using IBackendSpecificModelContextPtr = std::shared_ptr< IBackendModelContext >
using IMemoryManagerUniquePtr = std::unique_ptr< IMemoryManager >
using IMemoryManagerSharedPtr = std::shared_ptr< IMemoryManager >
Protected Member Functions inherited from IBackendInternal
IBackendInternal ()=default
Creation must be done through a specific backend interface.
Protected Member Functions inherited from IBackend
IBackend ()
virtual ~IBackend ()
Detailed Description
Definition at line 18 of file MockBackend.hpp.
Constructor & Destructor Documentation
MockBackend()
MockBackend () default
~MockBackend()
~MockBackend () default
Member Function Documentation
CreateBackendContext()
IBackendInternal::IBackendContextPtr CreateBackendContext (const IRuntime::CreationOptions &) const override virtual
Create the runtime context of the backend.
Implementations may return a default-constructed IBackendContextPtr if no context is needed at runtime. Implementations must throw BackendUnavailableException if the backend cannot be used (for example, necessary accelerator hardware is not present). The default implementation always returns a default-constructed pointer.
Reimplemented from IBackendInternal.
Definition at line 133 of file MockBackend.cpp.
Referenced by MockBackend::GetId().
 {
     return IBackendContextPtr{};
 }
CreateBackendProfilingContext()
IBackendInternal::IBackendProfilingContextPtr CreateBackendProfilingContext (const IRuntime::CreationOptions & creationOptions, IBackendProfilingPtr & backendProfiling) override virtual
Create context specifically used for profiling interaction from backends.
Reimplemented from IBackendInternal.
Definition at line 138 of file MockBackend.cpp.
References armnn::IgnoreUnused(), MockBackendProfilingService::Instance(), and MockBackendProfilingService::SetProfilingContextPtr().
Referenced by MockBackend::GetId().
 {
     IgnoreUnused(options);
     std::shared_ptr<armnn::MockBackendProfilingContext> context =
         std::make_shared<MockBackendProfilingContext>(backendProfiling);
     MockBackendProfilingService::Instance().SetProfilingContextPtr(context);
     return context;
 }
CreateMemoryManager()
IBackendInternal::IMemoryManagerUniquePtr CreateMemoryManager () const override virtual
Reimplemented from IBackendInternal.
Definition at line 148 of file MockBackend.cpp.
Referenced by MockBackend::GetId().
 {
     return IMemoryManagerUniquePtr{};
 }
CreateWorkloadFactory()
IBackendInternal::IWorkloadFactoryPtr CreateWorkloadFactory (const IBackendInternal::IMemoryManagerSharedPtr & memoryManager = nullptr) const override virtual
Implements IBackendInternal.
Definition at line 127 of file MockBackend.cpp.
Referenced by MockBackend::GetId().
 {
     return IWorkloadFactoryPtr{};
 }
GetDefaultAllocator()
std::unique_ptr< ICustomAllocator > GetDefaultAllocator () const override virtual
Returns the default memory allocator for the backend.
Returns
- Returns unique pointer to the Default Allocator of the Backend
Reimplemented from IBackendInternal.
Definition at line 298 of file MockBackend.cpp.
Referenced by MockBackend::GetId().
 {
     return std::make_unique<DefaultAllocator>();
 }
GetId()
const BackendId& GetId () const inline override virtual
Implements IBackend.
Definition at line 27 of file MockBackend.hpp.
References MockBackend::CreateBackendContext(), MockBackend::CreateBackendProfilingContext(), MockBackend::CreateMemoryManager(), MockBackend::CreateWorkloadFactory(), MockBackend::GetDefaultAllocator(), MockBackend::GetIdStatic(), MockBackend::GetLayerSupport(), and MockBackend::OptimizeSubgraphView().
     {
         return GetIdStatic();
     }
GetIdStatic()
const BackendId & GetIdStatic () static
Definition at line 17 of file MockBackend.cpp.
References armnn::MockBackendId().
Referenced by MockBackend::GetId(), MockBackendInitialiser::MockBackendInitialiser(), TEST_SUITE(), and MockBackendInitialiser::~MockBackendInitialiser().
 {
     static const BackendId s_Id{MockBackendId()};
     return s_Id;
 }
GetLayerSupport()
IBackendInternal::ILayerSupportSharedPtr GetLayerSupport () const override virtual
Implements IBackendInternal.
Definition at line 153 of file MockBackend.cpp.
Referenced by MockBackend::GetId().
 {
     static ILayerSupportSharedPtr layerSupport{new MockLayerSupport};
     return layerSupport;
 }
OptimizeSubgraphView()
OptimizationViews OptimizeSubgraphView (const SubgraphView & subgraph) const override virtual
Reimplemented from IBackendInternal.
Definition at line 159 of file MockBackend.cpp.
References OptimizationViews::AddFailedSubgraph(), OptimizationViews::AddSubstitution(), OptimizationViews::AddUntouchedSubgraph(), ARMNN_ASSERT, SubgraphView::GetIConnectableLayers(), OptimizationViews::GetINetwork(), armnn::Input, armnn::IsLayerOptimizable(), IWorkloadFactory::IsLayerSupported(), armnn::MockBackendId(), armnn::Output, and SubgraphViewSelector::SelectSubgraphs().
Referenced by MockBackend::GetId().
 {
     // Prepare the optimization views
     OptimizationViews optimizationViews;
     // Get the layers of the input sub-graph
     const SubgraphView::IConnectableLayers& subgraphLayers = subgraph.GetIConnectableLayers();
     // Parse the layers
     SubgraphView::IConnectableLayers supportedLayers;
     SubgraphView::IConnectableLayers unsupportedLayers;
     SubgraphView::IConnectableLayers untouchedLayers;
     std::for_each(subgraphLayers.begin(),
                   subgraphLayers.end(),
                   [&](IConnectableLayer* layer)
                   {
                       bool supported = IsLayerSupported(PolymorphicDowncast<Layer*>(layer));
                       if (supported)
                       {
                           // Layer supported, check if it's optimizable
                           bool optimizable = IsLayerOptimizable(PolymorphicDowncast<Layer*>(layer));
                           if (optimizable)
{
                               // Layer fully supported
                               supportedLayers.push_back(layer);
                           }
                           else
{
                               // Layer supported but not optimizable
                               untouchedLayers.push_back(layer);
                           }
                       }
                       else
                       {
                           // Layer unsupported
                           unsupportedLayers.push_back(layer);
                       }
                   });
     // Check if there are supported layers
     if (!supportedLayers.empty())
     {
         // Select the layers that are neither inputs or outputs, but that are optimizable
         auto supportedSubgraphSelector = [](const Layer& layer)
         {
             return layer.GetType() != LayerType::Input &&
                 layer.GetType() != LayerType::Output &&
                 IsLayerSupported(layer) &&
                 IsLayerOptimizable(layer);
         };
         // Apply the subgraph selector to the supported layers to group them into sub-graphs were appropriate
         SubgraphView mutableSubgraph(subgraph);
         SubgraphViewSelector::Subgraphs supportedSubgraphs =
                          SubgraphViewSelector::SelectSubgraphs(mutableSubgraph, supportedSubgraphSelector);
         // Create a substitution pair for each supported sub-graph
         std::for_each(supportedSubgraphs.begin(),
                       supportedSubgraphs.end(),
                       [&optimizationViews](const SubgraphView::SubgraphViewPtr& supportedSubgraph)
                       {
                           ARMNN_ASSERT(supportedSubgraph != nullptr);
                           CompiledBlobPtr blobPtr;
                           BackendId backend = MockBackendId();
                           IConnectableLayer* preCompiledLayer =
                                                optimizationViews.GetINetwork()->AddPrecompiledLayer(
                                                    PreCompiledDescriptor(supportedSubgraph->GetNumInputSlots(),
                                                                          supportedSubgraph->GetNumOutputSlots()),
                                                    std::move(blobPtr),
                                                    backend,
                                                    nullptr);
                           SubgraphView substitutionSubgraph(*supportedSubgraph);
                           SubgraphView replacementSubgraph(preCompiledLayer);
                           optimizationViews.AddSubstitution({ substitutionSubgraph, replacementSubgraph });
                       });
     }
     // Check if there are unsupported layers
     if (!unsupportedLayers.empty())
     {
         // Select the layers that are neither inputs or outputs, and are not optimizable
         auto unsupportedSubgraphSelector = [](const Layer& layer)
         {
             return layer.GetType() != LayerType::Input &&
                 layer.GetType() != LayerType::Output &&
                 !IsLayerSupported(layer);
         };
         // Apply the subgraph selector to the unsupported layers to group them into sub-graphs were appropriate
         SubgraphView mutableSubgraph(subgraph);
         SubgraphViewSelector::Subgraphs unsupportedSubgraphs =
                          SubgraphViewSelector::SelectSubgraphs(mutableSubgraph, unsupportedSubgraphSelector);
         // Add each unsupported sub-graph to the list of failed sub-graphs in the optimizization views
         std::for_each(unsupportedSubgraphs.begin(),
                       unsupportedSubgraphs.end(),
                       [&optimizationViews](const SubgraphView::SubgraphViewPtr& unsupportedSubgraph)
                       {
                           ARMNN_ASSERT(unsupportedSubgraph != nullptr);
                           optimizationViews.AddFailedSubgraph(SubgraphView(*unsupportedSubgraph));
                       });
     }
     // Check if there are untouched layers
     if (!untouchedLayers.empty())
     {
         // Select the layers that are neither inputs or outputs, that are supported but that and are not optimizable
         auto untouchedSubgraphSelector = [](const Layer& layer)
         {
             return layer.GetType() != LayerType::Input &&
                 layer.GetType() != LayerType::Output &&
                 IsLayerSupported(layer) &&
                 !IsLayerOptimizable(layer);
         };
         // Apply the subgraph selector to the untouched layers to group them into sub-graphs were appropriate
         SubgraphView mutableSubgraph(subgraph);
         SubgraphViewSelector::Subgraphs untouchedSubgraphs =
                          SubgraphViewSelector::SelectSubgraphs(mutableSubgraph, untouchedSubgraphSelector);
         // Add each untouched sub-graph to the list of untouched sub-graphs in the optimizization views
         std::for_each(untouchedSubgraphs.begin(),
                       untouchedSubgraphs.end(),
                       [&optimizationViews](const SubgraphView::SubgraphViewPtr& untouchedSubgraph)
                       {
                           ARMNN_ASSERT(untouchedSubgraph != nullptr);
                           optimizationViews.AddUntouchedSubgraph(SubgraphView(*untouchedSubgraph));
                       });
     }
     return optimizationViews;
 }
The documentation for this class was generated from the following files:
include/armnnTestUtils/MockBackend.hpp
src/armnnTestUtils/MockBackend.cpp