ArmNN: LayerVerifierBaseWithDescriptorAndConstants< Descriptor > Class Template Reference
LayerVerifierBaseWithDescriptorAndConstants< Descriptor > Class Template Reference
#include <SerializerTestUtils.hpp>
Public Member Functions
LayerVerifierBaseWithDescriptorAndConstants (const std::string &layerName, const std::vector< armnn::TensorInfo > &inputInfos, const std::vector< armnn::TensorInfo > &outputInfos, const Descriptor &descriptor, const std::vector< armnn::ConstTensor > &constants)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from LayerVerifierBaseWithDescriptor< Descriptor >
LayerVerifierBaseWithDescriptor (const std::string &layerName, const std::vector< armnn::TensorInfo > &inputInfos, const std::vector< armnn::TensorInfo > &outputInfos, const Descriptor &descriptor)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from LayerVerifierBase
LayerVerifierBase (const std::string &layerName, const std::vector< armnn::TensorInfo > &inputInfos, const std::vector< armnn::TensorInfo > &outputInfos)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from IStrategy
virtual void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0)=0
virtual void FinishStrategy ()
Additional Inherited Members
Protected Member Functions inherited from LayerVerifierBaseWithDescriptor< Descriptor >
void VerifyDescriptor (const Descriptor &descriptor)
Protected Member Functions inherited from LayerVerifierBase
void VerifyNameAndConnections (const armnn::IConnectableLayer *layer, const char *name)
void VerifyConstTensors (const std::string &tensorName, const armnn::ConstTensor *expectedPtr, const armnn::ConstTensor *actualPtr)
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Protected Attributes inherited from LayerVerifierBaseWithDescriptor< Descriptor >
Descriptor m_Descriptor
Detailed Description
template<typename Descriptor>
class LayerVerifierBaseWithDescriptorAndConstants< Descriptor >
Definition at line 108 of file SerializerTestUtils.hpp.
Constructor & Destructor Documentation
LayerVerifierBaseWithDescriptorAndConstants()
LayerVerifierBaseWithDescriptorAndConstants (const std::string & layerName, const std::vector< armnn::TensorInfo > & inputInfos, const std::vector< armnn::TensorInfo > & outputInfos, const Descriptor & descriptor, const std::vector< armnn::ConstTensor > & constants) inline
Definition at line 111 of file SerializerTestUtils.hpp.
             : LayerVerifierBaseWithDescriptor<Descriptor>(layerName, inputInfos, outputInfos, descriptor)
             , m_Constants(constants) {}
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override
Definition at line 119 of file SerializerTestUtils.hpp.
References CompareConstTensor(), armnn::Constant, IConnectableLayer::GetType(), armnn::IgnoreUnused(), armnn::Input, armnn::Output, and LayerVerifierBase::VerifyNameAndConnections().
Referenced by TEST_SUITE().
     {
         armnn::IgnoreUnused(id);
         switch (layer->GetType())
         {
             case armnn::LayerType::Input: break;
             case armnn::LayerType::Output: break;
             case armnn::LayerType::Constant: break;
             default:
             {
                 this->VerifyNameAndConnections(layer, name);
                 const Descriptor& internalDescriptor = static_cast<const Descriptor&>(descriptor);
                 this->VerifyDescriptor(internalDescriptor);
                 for(std::size_t i = 0; i < constants.size(); i++)
                 {
                     CompareConstTensor(constants[i], m_Constants[i]);
                 }
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnnSerializer/test/SerializerTestUtils.hpp