ArmNN: BaseTensor< MemoryType > Class Template Reference
BaseTensor< MemoryType > Class Template Reference
#include <Tensor.hpp>
Public Member Functions
BaseTensor ()
Empty (invalid) constructor.
BaseTensor (const TensorInfo &info, MemoryType memoryArea)
Constructor from a raw memory pointer.
BaseTensor (const BaseTensor &other)
Tensors are copyable.
BaseTensor & operator= (const BaseTensor &)
Tensors are copyable.
const TensorInfo & GetInfo () const
TensorInfo & GetInfo ()
const TensorShape & GetShape () const
TensorShape & GetShape ()
DataType GetDataType () const
unsigned int GetNumDimensions () const
unsigned int GetNumBytes () const
unsigned int GetNumElements () const
MemoryType GetMemoryArea () const
Protected Member Functions
~BaseTensor ()
Protected destructor to stop users from making these (could still new one on the heap and then leak it...)
Protected Attributes
MemoryType m_MemoryArea
Detailed Description
template<typename MemoryType>
class armnn::BaseTensor< MemoryType >
Definition at line 277 of file Tensor.hpp.
Constructor & Destructor Documentation
BaseTensor() [1/3]
BaseTensor ()
Empty (invalid) constructor.
Definition at line 524 of file Tensor.cpp.
  : m_MemoryArea(nullptr)
 {
 }
BaseTensor() [2/3]
BaseTensor (const TensorInfo & info, MemoryType memoryArea)
Constructor from a raw memory pointer.
Parameters
memoryArea - Region of CPU-addressable memory where tensor data will be stored. Must be valid while workloads are on the fly. Tensor instances do not claim ownership of referenced memory regions, that is, no attempt will be made by ArmNN to free these memory regions automatically.
Definition at line 530 of file Tensor.cpp.
  : m_MemoryArea(memoryArea)
  , m_Info(info)
 {
 }
BaseTensor() [3/3]
BaseTensor (const BaseTensor< MemoryType > & other)
Tensors are copyable.
~BaseTensor()
~BaseTensor () inline protected
Protected destructor to stop users from making these (could still new one on the heap and then leak it...)
Definition at line 310 of file Tensor.hpp.
 {}
Member Function Documentation
GetDataType()
DataType GetDataType () const inline
Definition at line 300 of file Tensor.hpp.
Referenced by CompareConstTensor(), and armnn::ConvertWeightTensorFromArmnnToAcl().
 { return m_Info.GetDataType(); }
GetInfo() [1/2]
const TensorInfo& GetInfo () const inline
Definition at line 295 of file Tensor.hpp.
Referenced by BaseTensor< const void *>::BaseTensor(), TestLayerVisitor::CheckConstTensors(), armnn::ConvertWeightTensorFromArmnnToAcl(), armnn::CopyToOutputTensor(), LoadedNetwork::FreeWorkingMemory(), armnnSerializer::GetFlatBufferArgMinMaxFunction(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), armnnDeserializer::GetOriginsDescriptor(), LoadedNetwork::ImportInputs(), TfLiteParserImpl::OutputShapeOfReshape(), armnn::ReorderWeightChannelsForAcl(), FuseBatchNorm< ConvLayer, ArmnnType, T >::Run(), TEST_SUITE(), and LayerVerifierBase::VerifyConstTensors().
 { return m_Info; }
GetInfo() [2/2]
TensorInfo& GetInfo () inline
Definition at line 296 of file Tensor.hpp.
 { return m_Info; }
GetMemoryArea()
MemoryType GetMemoryArea () const inline
Definition at line 305 of file Tensor.hpp.
Referenced by TestLayerVisitor::CheckConstTensors(), CompareConstTensor(), armnn::CopyToOutputTensor(), LoadedNetwork::FreeWorkingMemory(), armnnSerializer::GetFlatBufferArgMinMaxFunction(), IDeserializer::DeserializerImpl::GetNetworkOutputBindingInfo(), LoadedNetwork::ImportInputs(), LoadedNetwork::ImportOutputs(), ScopedTensorHandle::ScopedTensorHandle(), and LayerVerifierBase::VerifyConstTensors().
 { return m_MemoryArea; }
GetNumBytes()
unsigned int GetNumBytes () const inline
Definition at line 302 of file Tensor.hpp.
Referenced by TestLayerVisitor::CheckConstTensors(), armnnSerializer::GetFlatBufferArgMinMaxFunction(), ScopedTensorHandle::ScopedTensorHandle(), and LayerVerifierBase::VerifyConstTensors().
 { return m_Info.GetNumBytes(); }
GetNumDimensions()
unsigned int GetNumDimensions () const inline
Definition at line 301 of file Tensor.hpp.
Referenced by TestLayerVisitor::CheckConstTensors().
 { return m_Info.GetNumDimensions(); }
GetNumElements()
unsigned int GetNumElements () const inline
Definition at line 303 of file Tensor.hpp.
Referenced by TestLayerVisitor::CheckConstTensors(), CompareConstTensor(), and FuseBatchNorm< ConvLayer, ArmnnType, T >::Run().
 { return m_Info.GetNumElements(); }
GetShape() [1/2]
const TensorShape& GetShape () const inline
Definition at line 297 of file Tensor.hpp.
Referenced by CompareConstTensor(), and armnn::ReorderWeightChannelsForAcl().
 { return m_Info.GetShape(); }
GetShape() [2/2]
TensorShape& GetShape () inline
Definition at line 298 of file Tensor.hpp.
 { return m_Info.GetShape(); }
operator=()
BaseTensor< MemoryType > & operator= (const BaseTensor< MemoryType > &)
Tensors are copyable.
Definition at line 544 of file Tensor.cpp.
 {
     m_Info = other.m_Info;
     m_MemoryArea = other.m_MemoryArea;
     return *this;
 }
Member Data Documentation
m_MemoryArea
MemoryType m_MemoryArea protected
Definition at line 312 of file Tensor.hpp.
Referenced by BaseTensor< const void *>::BaseTensor(), and BaseTensor< const void *>::operator=().
The documentation for this class was generated from the following files:
include/armnn/Tensor.hpp
src/armnn/Tensor.cpp