ArmNN: PermuteDepthwiseConv2dWeightsImpl Class Reference
PermuteDepthwiseConv2dWeightsImpl Class Reference
#include <PermuteDepthwiseConv2dWeights.hpp>
Public Member Functions
void Run (Graph &graph, Layer &layer) const
Protected Member Functions
PermuteDepthwiseConv2dWeightsImpl ()=default
~PermuteDepthwiseConv2dWeightsImpl ()=default
Detailed Description
Definition at line 19 of file PermuteDepthwiseConv2dWeights.hpp.
Constructor & Destructor Documentation
PermuteDepthwiseConv2dWeightsImpl()
PermuteDepthwiseConv2dWeightsImpl () protected default
Referenced by PermuteDepthwiseConv2dWeightsImpl::Run().
~PermuteDepthwiseConv2dWeightsImpl()
~PermuteDepthwiseConv2dWeightsImpl () protected default
Referenced by PermuteDepthwiseConv2dWeightsImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, Layer & layer) const inline
Definition at line 23 of file PermuteDepthwiseConv2dWeights.hpp.
References armnn::DepthwiseConvolution2d, Layer::GetBackendId(), InputSlot::GetConnectedOutputSlot(), armnn::GetDataLayoutName(), Layer::GetInputSlot(), Layer::GetOutputSlot(), LayerWithParameters< Parameters >::GetParameters(), OutputSlot::GetTensorInfo(), Layer::GetType(), Graph::InsertNewLayer(), DepthwiseConvolution2dDescriptor::m_DataLayout, armnn::NCHW, armnn::NHWC, armnnUtils::Permuted(), PermuteDepthwiseConv2dWeightsImpl::PermuteDepthwiseConv2dWeightsImpl(), Layer::SetBackendId(), OutputSlot::SetTensorInfo(), and PermuteDepthwiseConv2dWeightsImpl::~PermuteDepthwiseConv2dWeightsImpl().
     {
         if (layer.GetType() == LayerType::DepthwiseConvolution2d)
         {
             AddPermuteLayer(graph, PolymorphicDowncast<DepthwiseConvolution2dLayer*>(&layer));
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/PermuteDepthwiseConv2dWeights.hpp