ArmNN: ProfilingServiceRuntimeHelper Class Reference
ProfilingServiceRuntimeHelper Class Reference
#include <ProfilingTestUtils.hpp>
Public Member Functions
ProfilingServiceRuntimeHelper (uint16_t maxGlobalCounterId, IInitialiseProfilingService &initialiser, arm::pipe::IProfilingService &profilingService)
~ProfilingServiceRuntimeHelper ()=default
BufferManager & GetProfilingBufferManager ()
void ForceTransitionToState (ProfilingState newState)
Public Attributes
arm::pipe::IProfilingService & m_ProfilingService
Detailed Description
Definition at line 74 of file ProfilingTestUtils.hpp.
Constructor & Destructor Documentation
ProfilingServiceRuntimeHelper()
ProfilingServiceRuntimeHelper (uint16_t maxGlobalCounterId, IInitialiseProfilingService & initialiser, arm::pipe::IProfilingService & profilingService) inline
Definition at line 77 of file ProfilingTestUtils.hpp.
         : ProfilingService(maxGlobalCounterId,
                            initialiser,
                            arm::pipe::ARMNN_SOFTWARE_INFO,
                            arm::pipe::ARMNN_SOFTWARE_VERSION,
                            arm::pipe::ARMNN_HARDWARE_VERSION),
           m_ProfilingService(profilingService) {}
~ProfilingServiceRuntimeHelper()
~ProfilingServiceRuntimeHelper () default
Member Function Documentation
ForceTransitionToState()
void ForceTransitionToState (ProfilingState newState) inline
Definition at line 94 of file ProfilingTestUtils.hpp.
References armnn::ConfigureLogging().
Referenced by TEST_SUITE(), and VerifyPostOptimisationStructureTestImpl().
     {
         TransitionToState(static_cast<arm::pipe::ProfilingService&>(m_ProfilingService), newState);
     }
GetProfilingBufferManager()
BufferManager& GetProfilingBufferManager () inline
Definition at line 88 of file ProfilingTestUtils.hpp.
Referenced by TEST_SUITE(), and VerifyPostOptimisationStructureTestImpl().
     {
         return GetBufferManager(static_cast<arm::pipe::ProfilingService&>(m_ProfilingService));
     }
Member Data Documentation
m_ProfilingService
arm::pipe::IProfilingService& m_ProfilingService
Definition at line 92 of file ProfilingTestUtils.hpp.
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingTestUtils.hpp