ArmNN: arm::pipe Namespace Reference
arm::pipe Namespace Reference
Classes
class Connection
class Entity
class EventClassObj
class EventObj
class MockBufferManager
class MockCounterDirectory
class MockPacketBuffer
class MockProfilingConnection
class MockProfilingConnectionFactory
class MockProfilingService
class MockProfilingServiceStatus
class MockSendCounterPacket
class MockStreamCounterBuffer
struct ModelRelationship
class PrintPacketHeaderHandler
class ProfilingServiceRuntimeHelper
class RequestCountersPacketHandler
class SendCounterPacketTest
struct StreamRedirector
class SwapProfilingConnectionFactoryHelper
class TestFunctorA
class TestFunctorB
class TestFunctorC
class TestProfilingConnectionArmnnError
class TestProfilingConnectionBadAckPacket
class TestProfilingConnectionBase
class TestProfilingConnectionTimeoutError
class TestTimelinePacketHandler
class TimelineMessageDecoder
class TimelineModel
Typedefs
using LabelMap = std::map< uint64_t, arm::pipe::ITimelineDecoder::Label >
using Attribute = std::pair< std::string, std::string >
using Attributes = std::map< std::string, Attribute >
using Entities = std::map< uint64_t, Entity >
using Relationships = std::map< uint64_t, ModelRelationship >
using EventClasses = std::map< uint64_t, EventClassObj >
using Events = std::map< uint64_t, EventObj >
Functions
ProfilingOptions ConvertExternalProfilingOptions (const armnn::IRuntime::CreationOptions::ExternalProfilingOptions &options)
std::vector< std::string > GetModelDescription (const TimelineModel &model)
std::string GetEntityDescription (const Entity &entity)
std::string GetChildDescription (Entity *entity)
std::string GetConnectionDescription (const Connection &connection)
std::string GetExecutionDescription (Entity *execution)
std::string GetEventDescription (EventObj *event)
Typedef Documentation
Attribute
using Attribute = std::pair<std::string, std::string>
Definition at line 21 of file TimelineModel.hpp.
Attributes
using Attributes = std::map<std::string, Attribute>
Definition at line 22 of file TimelineModel.hpp.
Entities
using Entities = std::map<uint64_t, Entity>
Definition at line 136 of file TimelineModel.hpp.
EventClasses
using EventClasses = std::map<uint64_t, EventClassObj>
Definition at line 144 of file TimelineModel.hpp.
Events
using Events = std::map<uint64_t, EventObj>
Definition at line 145 of file TimelineModel.hpp.
LabelMap
using LabelMap = std::map<uint64_t, arm::pipe::ITimelineDecoder::Label>
Definition at line 20 of file TimelineModel.hpp.
Relationships
using Relationships = std::map<uint64_t, ModelRelationship>
Definition at line 143 of file TimelineModel.hpp.
Function Documentation
ConvertExternalProfilingOptions()
ProfilingOptions ConvertExternalProfilingOptions (const armnn::IRuntime::CreationOptions::ExternalProfilingOptions & options)
Definition at line 17 of file ProfilingOptionsConverter.cpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_CapturePeriod, IRuntime::CreationOptions::ExternalProfilingOptions::m_EnableProfiling, IRuntime::CreationOptions::ExternalProfilingOptions::m_FileFormat, IRuntime::CreationOptions::ExternalProfilingOptions::m_FileOnly, IRuntime::CreationOptions::ExternalProfilingOptions::m_IncomingCaptureFile, IRuntime::CreationOptions::ExternalProfilingOptions::m_LocalPacketHandlers, IRuntime::CreationOptions::ExternalProfilingOptions::m_OutgoingCaptureFile, and IRuntime::CreationOptions::ExternalProfilingOptions::m_TimelineEnabled.
Referenced by CheckInferenceTimeThreshold(), RuntimeImpl::RuntimeImpl(), TEST_SUITE(), and VerifyPostOptimisationStructureTestImpl().
 {
     ProfilingOptions convertedOptions;
     convertedOptions.m_EnableProfiling     = options.m_EnableProfiling;
     convertedOptions.m_TimelineEnabled     = options.m_TimelineEnabled;
     convertedOptions.m_OutgoingCaptureFile = options.m_OutgoingCaptureFile;
     convertedOptions.m_IncomingCaptureFile = options.m_IncomingCaptureFile;
     convertedOptions.m_FileOnly            = options.m_FileOnly;
     convertedOptions.m_CapturePeriod       = options.m_CapturePeriod;
     convertedOptions.m_FileFormat          = options.m_FileFormat;
     std::copy(options.m_LocalPacketHandlers.begin(), options.m_LocalPacketHandlers.end(),
               std::back_inserter(convertedOptions.m_LocalPacketHandlers));
     return convertedOptions;
 }
GetChildDescription()
std::string GetChildDescription (Entity * entity)
Definition at line 374 of file TimelineModel.cpp.
References GetEntityDescription().
Referenced by TimelineModel::GetEventClasses(), and GetModelDescription().
 {
     std::stringstream ss;
     ss << "   child: " << GetEntityDescription(*entity);
     return ss.str();
 }
GetConnectionDescription()
std::string GetConnectionDescription (const Connection & connection)
Definition at line 381 of file TimelineModel.cpp.
References Connection::GetGuid(), Entity::GetGuid(), Connection::GetHead(), and Connection::GetTail().
Referenced by TimelineModel::GetEventClasses(), and GetModelDescription().
 {
     std::stringstream ss;
     ss << "   connection [" << connection.GetGuid() << "] from entity [";
     ss << connection.GetHead()->GetGuid() << "] to entity [" << connection.GetTail()->GetGuid() << "]";
     return ss.str();
 }
GetEntityDescription()
std::string GetEntityDescription (const Entity & entity)
Definition at line 357 of file TimelineModel.cpp.
References Entity::GetAttributes(), and Entity::GetGuid().
Referenced by GetChildDescription(), TimelineModel::GetEventClasses(), GetExecutionDescription(), and GetModelDescription().
 {
     std::stringstream ss;
     ss << "Entity [" << entity.GetGuid() << "]";
     for (auto& attributeEntry : entity.GetAttributes())
     {
         if (LabelsAndEventClasses::PROCESS_ID_LABEL == attributeEntry.second.first)
         {
             ss << " " << attributeEntry.second.first << " = [processId]";
         }
         else {
             ss << " " << attributeEntry.second.first << " = " << attributeEntry.second.second;
         }
     }
     return ss.str();
 }
GetEventDescription()
std::string GetEventDescription (EventObj * event)
Definition at line 396 of file TimelineModel.cpp.
Referenced by TimelineModel::GetEventClasses(), and GetModelDescription().
 {
     std::stringstream ss;
     ss << "   event: [" << event->GetGuid() << "] class [" << event->GetEventClass() << "]";
     return ss.str();
 }
GetExecutionDescription()
std::string GetExecutionDescription (Entity * execution)
Definition at line 389 of file TimelineModel.cpp.
References GetEntityDescription().
Referenced by TimelineModel::GetEventClasses(), and GetModelDescription().
 {
     std::stringstream ss;
     ss << "   execution: " << GetEntityDescription(*execution);
     return ss.str();
 }
GetModelDescription()
std::vector< std::string > GetModelDescription (const TimelineModel & model)
Definition at line 330 of file TimelineModel.cpp.
References GetChildDescription(), GetConnectionDescription(), TimelineModel::GetEntities(), GetEntityDescription(), GetEventDescription(), and GetExecutionDescription().
Referenced by TimelineModel::GetEventClasses(), and TEST_SUITE().
 {
     std::vector<std::string> desc;
     for (auto& entry : model.GetEntities())
     {
         auto& entity = entry.second;
         desc.push_back(GetEntityDescription(entity));
         for (auto& connection : entity.GetConnections())
         {
             desc.push_back(GetConnectionDescription(connection));
         }
         for (auto child : entity.GetChildren())
         {
             desc.push_back(GetChildDescription(child));
         }
         for (auto execution : entity.GetExecutions())
         {
             desc.push_back(GetExecutionDescription(execution));
         }
         for (auto event : entity.GetEvents())
         {
             desc.push_back(GetEventDescription(event));
         }
     }
     return desc;
 }