ArmNN: armnnSerializer Namespace Reference
armnnSerializer Namespace Reference
Classes
struct AbsLayerBuilder
struct ActivationDescriptorBuilder
struct ActivationLayerBuilder
struct AdditionLayerBuilder
struct AnyLayerBuilder
struct ArgMinMaxDescriptorBuilder
struct ArgMinMaxLayerBuilder
struct BatchNormalizationDescriptorBuilder
struct BatchNormalizationLayerBuilder
struct BatchToSpaceNdDescriptorBuilder
struct BatchToSpaceNdLayerBuilder
struct BindableLayerBaseBuilder
struct ByteDataBuilder
struct CastLayerBuilder
struct ChannelShuffleDescriptorBuilder
struct ChannelShuffleLayerBuilder
struct ComparisonDescriptorBuilder
struct ComparisonLayerBuilder
struct ConcatLayerBuilder
struct ConstantLayerBuilder
struct ConstTensorBuilder
struct ConstTensorDataTraits
struct ConstTensorDataTraits< armnnSerializer::ByteData >
struct ConstTensorDataTraits< armnnSerializer::IntData >
struct ConstTensorDataTraits< armnnSerializer::LongData >
struct ConstTensorDataTraits< armnnSerializer::ShortData >
struct Convolution2dDescriptorBuilder
struct Convolution2dLayerBuilder
struct Convolution3dDescriptorBuilder
struct Convolution3dLayerBuilder
struct DepthToSpaceDescriptorBuilder
struct DepthToSpaceLayerBuilder
struct DepthwiseConvolution2dDescriptorBuilder
struct DepthwiseConvolution2dLayerBuilder
struct DequantizeLayerBuilder
struct DetectionPostProcessDescriptorBuilder
struct DetectionPostProcessLayerBuilder
struct DivisionLayerBuilder
struct ElementwiseUnaryDescriptorBuilder
struct ElementwiseUnaryLayerBuilder
struct EqualLayerBuilder
struct FeatureCompatibilityVersionsBuilder
struct FillDescriptorBuilder
struct FillLayerBuilder
struct FLATBUFFERS_FINAL_CLASS
struct FloorLayerBuilder
struct FullyConnectedDescriptorBuilder
struct FullyConnectedLayerBuilder
struct GatherDescriptorBuilder
struct GatherLayerBuilder
struct GatherNdLayerBuilder
struct GreaterLayerBuilder
struct InputLayerBuilder
struct InputSlotBuilder
struct InstanceNormalizationDescriptorBuilder
struct InstanceNormalizationLayerBuilder
struct IntDataBuilder
class ISerializer
struct L2NormalizationDescriptorBuilder
struct L2NormalizationLayerBuilder
struct LayerBaseBuilder
struct LayerTraits
struct LayerTraits< armnnSerializer::AbsLayer >
struct LayerTraits< armnnSerializer::ActivationLayer >
struct LayerTraits< armnnSerializer::AdditionLayer >
struct LayerTraits< armnnSerializer::ArgMinMaxLayer >
struct LayerTraits< armnnSerializer::BatchNormalizationLayer >
struct LayerTraits< armnnSerializer::BatchToSpaceNdLayer >
struct LayerTraits< armnnSerializer::CastLayer >
struct LayerTraits< armnnSerializer::ChannelShuffleLayer >
struct LayerTraits< armnnSerializer::ComparisonLayer >
struct LayerTraits< armnnSerializer::ConcatLayer >
struct LayerTraits< armnnSerializer::ConstantLayer >
struct LayerTraits< armnnSerializer::Convolution2dLayer >
struct LayerTraits< armnnSerializer::Convolution3dLayer >
struct LayerTraits< armnnSerializer::DepthToSpaceLayer >
struct LayerTraits< armnnSerializer::DepthwiseConvolution2dLayer >
struct LayerTraits< armnnSerializer::DequantizeLayer >
struct LayerTraits< armnnSerializer::DetectionPostProcessLayer >
struct LayerTraits< armnnSerializer::DivisionLayer >
struct LayerTraits< armnnSerializer::ElementwiseUnaryLayer >
struct LayerTraits< armnnSerializer::EqualLayer >
struct LayerTraits< armnnSerializer::FillLayer >
struct LayerTraits< armnnSerializer::FloorLayer >
struct LayerTraits< armnnSerializer::FullyConnectedLayer >
struct LayerTraits< armnnSerializer::GatherLayer >
struct LayerTraits< armnnSerializer::GatherNdLayer >
struct LayerTraits< armnnSerializer::GreaterLayer >
struct LayerTraits< armnnSerializer::InputLayer >
struct LayerTraits< armnnSerializer::InstanceNormalizationLayer >
struct LayerTraits< armnnSerializer::L2NormalizationLayer >
struct LayerTraits< armnnSerializer::LogicalBinaryLayer >
struct LayerTraits< armnnSerializer::LogSoftmaxLayer >
struct LayerTraits< armnnSerializer::LstmLayer >
struct LayerTraits< armnnSerializer::MaximumLayer >
struct LayerTraits< armnnSerializer::MeanLayer >
struct LayerTraits< armnnSerializer::MergeLayer >
struct LayerTraits< armnnSerializer::MergerLayer >
struct LayerTraits< armnnSerializer::MinimumLayer >
struct LayerTraits< armnnSerializer::MultiplicationLayer >
struct LayerTraits< armnnSerializer::NormalizationLayer >
struct LayerTraits< armnnSerializer::OutputLayer >
struct LayerTraits< armnnSerializer::PadLayer >
struct LayerTraits< armnnSerializer::PermuteLayer >
struct LayerTraits< armnnSerializer::Pooling2dLayer >
struct LayerTraits< armnnSerializer::Pooling3dLayer >
struct LayerTraits< armnnSerializer::PreluLayer >
struct LayerTraits< armnnSerializer::QLstmLayer >
struct LayerTraits< armnnSerializer::QuantizedLstmLayer >
struct LayerTraits< armnnSerializer::QuantizeLayer >
struct LayerTraits< armnnSerializer::RankLayer >
struct LayerTraits< armnnSerializer::ReduceLayer >
struct LayerTraits< armnnSerializer::ReshapeLayer >
struct LayerTraits< armnnSerializer::ResizeBilinearLayer >
struct LayerTraits< armnnSerializer::ResizeLayer >
struct LayerTraits< armnnSerializer::RsqrtLayer >
struct LayerTraits< armnnSerializer::ShapeLayer >
struct LayerTraits< armnnSerializer::SliceLayer >
struct LayerTraits< armnnSerializer::SoftmaxLayer >
struct LayerTraits< armnnSerializer::SpaceToBatchNdLayer >
struct LayerTraits< armnnSerializer::SpaceToDepthLayer >
struct LayerTraits< armnnSerializer::SplitterLayer >
struct LayerTraits< armnnSerializer::StackLayer >
struct LayerTraits< armnnSerializer::StandInLayer >
struct LayerTraits< armnnSerializer::StridedSliceLayer >
struct LayerTraits< armnnSerializer::SubtractionLayer >
struct LayerTraits< armnnSerializer::SwitchLayer >
struct LayerTraits< armnnSerializer::TransposeConvolution2dLayer >
struct LayerTraits< armnnSerializer::TransposeLayer >
struct LayerTraits< armnnSerializer::UnidirectionalSequenceLstmLayer >
struct LogicalBinaryDescriptorBuilder
struct LogicalBinaryLayerBuilder
struct LogSoftmaxDescriptorBuilder
struct LogSoftmaxLayerBuilder
struct LongDataBuilder
struct LstmDescriptorBuilder
struct LstmInputParamsBuilder
struct LstmLayerBuilder
struct MaximumLayerBuilder
struct MeanDescriptorBuilder
struct MeanLayerBuilder
struct MergeLayerBuilder
struct MergerLayerBuilder
struct MinimumLayerBuilder
struct MultiplicationLayerBuilder
struct NormalizationDescriptorBuilder
struct NormalizationLayerBuilder
struct OriginsDescriptorBuilder
struct OutputLayerBuilder
struct OutputSlotBuilder
struct PadDescriptorBuilder
struct PadLayerBuilder
struct PermuteDescriptorBuilder
struct PermuteLayerBuilder
struct Pooling2dDescriptorBuilder
struct Pooling2dLayerBuilder
struct Pooling3dDescriptorBuilder
struct Pooling3dLayerBuilder
struct PreluLayerBuilder
struct QLstmDescriptorBuilder
struct QLstmInputParamsBuilder
struct QLstmLayerBuilder
struct QuantizedLstmInputParamsBuilder
struct QuantizedLstmLayerBuilder
struct QuantizeLayerBuilder
struct RankLayerBuilder
struct ReduceDescriptorBuilder
struct ReduceLayerBuilder
struct ReshapeDescriptorBuilder
struct ReshapeLayerBuilder
struct ResizeBilinearDescriptorBuilder
struct ResizeBilinearLayerBuilder
struct ResizeDescriptorBuilder
struct ResizeLayerBuilder
struct RsqrtLayerBuilder
struct SerializedGraphBuilder
class SerializerStrategy
struct ShapeLayerBuilder
struct ShortDataBuilder
struct SliceDescriptorBuilder
struct SliceLayerBuilder
struct SoftmaxDescriptorBuilder
struct SoftmaxLayerBuilder
struct SpaceToBatchNdDescriptorBuilder
struct SpaceToBatchNdLayerBuilder
struct SpaceToDepthDescriptorBuilder
struct SpaceToDepthLayerBuilder
struct SplitterLayerBuilder
struct StackDescriptorBuilder
struct StackLayerBuilder
struct StandInDescriptorBuilder
struct StandInLayerBuilder
struct StridedSliceDescriptorBuilder
struct StridedSliceLayerBuilder
struct SubtractionLayerBuilder
struct SwitchLayerBuilder
struct TensorInfoBuilder
struct TransposeConvolution2dDescriptorBuilder
struct TransposeConvolution2dLayerBuilder
struct TransposeDescriptorBuilder
struct TransposeLayerBuilder
struct UintVectorBuilder
struct UnidirectionalSequenceLstmDescriptorBuilder
struct UnidirectionalSequenceLstmLayerBuilder
struct ViewsDescriptorBuilder
Typedefs
using ISerializerPtr = std::unique_ptr< ISerializer, void(*)(ISerializer *serializer)>
Enumerations
enum ActivationFunction {
ActivationFunction_Sigmoid = 0, ActivationFunction_TanH = 1, ActivationFunction_Linear = 2, ActivationFunction_ReLu = 3,
ActivationFunction_BoundedReLu = 4, ActivationFunction_SoftReLu = 5, ActivationFunction_LeakyReLu = 6, ActivationFunction_Abs = 7,
ActivationFunction_Sqrt = 8, ActivationFunction_Square = 9, ActivationFunction_Elu = 10, ActivationFunction_HardSwish = 11,
ActivationFunction_MIN = ActivationFunction_Sigmoid, ActivationFunction_MAX = ActivationFunction_HardSwish
}
enum ArgMinMaxFunction { ArgMinMaxFunction_Min = 0, ArgMinMaxFunction_Max = 1, ArgMinMaxFunction_MIN = ArgMinMaxFunction_Min, ArgMinMaxFunction_MAX = ArgMinMaxFunction_Max }
enum DataType {
DataType_Float16 = 0, DataType_Float32 = 1, DataType_QuantisedAsymm8 = 2, DataType_Signed32 = 3,
DataType_Boolean = 4, DataType_QuantisedSymm16 = 5, DataType_QAsymmU8 = 6, DataType_QSymmS16 = 7,
DataType_QAsymmS8 = 8, DataType_QSymmS8 = 9, DataType_Signed64 = 10, DataType_MIN = DataType_Float16,
DataType_MAX = DataType_Signed64
}
enum DataLayout {
DataLayout_NHWC = 0, DataLayout_NCHW = 1, DataLayout_NDHWC = 2, DataLayout_NCDHW = 3,
DataLayout_MIN = DataLayout_NHWC, DataLayout_MAX = DataLayout_NCDHW
}
enum ReduceOperation {
ReduceOperation_Sum = 0, ReduceOperation_Max = 1, ReduceOperation_Mean = 2, ReduceOperation_Min = 3,
ReduceOperation_Prod = 4, ReduceOperation_MIN = ReduceOperation_Sum, ReduceOperation_MAX = ReduceOperation_Prod
}
enum ResizeMethod { ResizeMethod_NearestNeighbor = 0, ResizeMethod_Bilinear = 1, ResizeMethod_MIN = ResizeMethod_NearestNeighbor, ResizeMethod_MAX = ResizeMethod_Bilinear }
enum ConstTensorData {
ConstTensorData_NONE = 0, ConstTensorData_ByteData = 1, ConstTensorData_ShortData = 2, ConstTensorData_IntData = 3,
ConstTensorData_LongData = 4, ConstTensorData_MIN = ConstTensorData_NONE, ConstTensorData_MAX = ConstTensorData_LongData
}
enum LayerType {
LayerType_Addition = 0, LayerType_Input = 1, LayerType_Multiplication = 2, LayerType_Output = 3,
LayerType_Pooling2d = 4, LayerType_Reshape = 5, LayerType_Softmax = 6, LayerType_Convolution2d = 7,
LayerType_DepthwiseConvolution2d = 8, LayerType_Activation = 9, LayerType_Permute = 10, LayerType_FullyConnected = 11,
LayerType_Constant = 12, LayerType_SpaceToBatchNd = 13, LayerType_BatchToSpaceNd = 14, LayerType_Division = 15,
LayerType_Minimum = 16, LayerType_Equal = 17, LayerType_Maximum = 18, LayerType_Normalization = 19,
LayerType_Pad = 20, LayerType_Rsqrt = 21, LayerType_Floor = 22, LayerType_BatchNormalization = 23,
LayerType_Greater = 24, LayerType_ResizeBilinear = 25, LayerType_Subtraction = 26, LayerType_StridedSlice = 27,
LayerType_Gather = 28, LayerType_Mean = 29, LayerType_Merger = 30, LayerType_L2Normalization = 31,
LayerType_Splitter = 32, LayerType_DetectionPostProcess = 33, LayerType_Lstm = 34, LayerType_Quantize = 35,
LayerType_Dequantize = 36, LayerType_Merge = 37, LayerType_Switch = 38, LayerType_Concat = 39,
LayerType_SpaceToDepth = 40, LayerType_Prelu = 41, LayerType_TransposeConvolution2d = 42, LayerType_Resize = 43,
LayerType_Stack = 44, LayerType_QuantizedLstm = 45, LayerType_Abs = 46, LayerType_ArgMinMax = 47,
LayerType_Slice = 48, LayerType_DepthToSpace = 49, LayerType_InstanceNormalization = 50, LayerType_LogSoftmax = 51,
LayerType_Comparison = 52, LayerType_StandIn = 53, LayerType_ElementwiseUnary = 54, LayerType_Transpose = 55,
LayerType_QLstm = 56, LayerType_Fill = 57, LayerType_Rank = 58, LayerType_LogicalBinary = 59,
LayerType_Reduce = 60, LayerType_Cast = 61, LayerType_Shape = 62, LayerType_UnidirectionalSequenceLstm = 63,
LayerType_ChannelShuffle = 64, LayerType_Convolution3d = 65, LayerType_Pooling3d = 66, LayerType_GatherNd = 67,
LayerType_MIN = LayerType_Addition, LayerType_MAX = LayerType_GatherNd
}
enum ComparisonOperation {
ComparisonOperation_Equal = 0, ComparisonOperation_Greater = 1, ComparisonOperation_GreaterOrEqual = 2, ComparisonOperation_Less = 3,
ComparisonOperation_LessOrEqual = 4, ComparisonOperation_NotEqual = 5, ComparisonOperation_MIN = ComparisonOperation_Equal, ComparisonOperation_MAX = ComparisonOperation_NotEqual
}
enum UnaryOperation {
UnaryOperation_Abs = 0, UnaryOperation_Rsqrt = 1, UnaryOperation_Sqrt = 2, UnaryOperation_Exp = 3,
UnaryOperation_Neg = 4, UnaryOperation_LogicalNot = 5, UnaryOperation_Log = 6, UnaryOperation_Sin = 7,
UnaryOperation_MIN = UnaryOperation_Abs, UnaryOperation_MAX = UnaryOperation_Sin
}
enum LogicalBinaryOperation { LogicalBinaryOperation_LogicalAnd = 0, LogicalBinaryOperation_LogicalOr = 1, LogicalBinaryOperation_MIN = LogicalBinaryOperation_LogicalAnd, LogicalBinaryOperation_MAX = LogicalBinaryOperation_LogicalOr }
enum PoolingAlgorithm {
PoolingAlgorithm_Max = 0, PoolingAlgorithm_Average = 1, PoolingAlgorithm_L2 = 2, PoolingAlgorithm_MIN = PoolingAlgorithm_Max,
PoolingAlgorithm_MAX = PoolingAlgorithm_L2
}
enum OutputShapeRounding { OutputShapeRounding_Floor = 0, OutputShapeRounding_Ceiling = 1, OutputShapeRounding_MIN = OutputShapeRounding_Floor, OutputShapeRounding_MAX = OutputShapeRounding_Ceiling }
enum PaddingMethod { PaddingMethod_IgnoreValue = 0, PaddingMethod_Exclude = 1, PaddingMethod_MIN = PaddingMethod_IgnoreValue, PaddingMethod_MAX = PaddingMethod_Exclude }
enum NormalizationAlgorithmChannel { NormalizationAlgorithmChannel_Across = 0, NormalizationAlgorithmChannel_Within = 1, NormalizationAlgorithmChannel_MIN = NormalizationAlgorithmChannel_Across, NormalizationAlgorithmChannel_MAX = NormalizationAlgorithmChannel_Within }
enum NormalizationAlgorithmMethod { NormalizationAlgorithmMethod_LocalBrightness = 0, NormalizationAlgorithmMethod_LocalContrast = 1, NormalizationAlgorithmMethod_MIN = NormalizationAlgorithmMethod_LocalBrightness, NormalizationAlgorithmMethod_MAX = NormalizationAlgorithmMethod_LocalContrast }
enum PaddingMode {
PaddingMode_Constant = 0, PaddingMode_Reflect = 1, PaddingMode_Symmetric = 2, PaddingMode_MIN = PaddingMode_Constant,
PaddingMode_MAX = PaddingMode_Symmetric
}
enum Layer {
Layer_NONE = 0, Layer_ActivationLayer = 1, Layer_AdditionLayer = 2, Layer_BatchToSpaceNdLayer = 3,
Layer_BatchNormalizationLayer = 4, Layer_ConstantLayer = 5, Layer_Convolution2dLayer = 6, Layer_DepthwiseConvolution2dLayer = 7,
Layer_FullyConnectedLayer = 8, Layer_InputLayer = 9, Layer_MultiplicationLayer = 10, Layer_OutputLayer = 11,
Layer_PermuteLayer = 12, Layer_Pooling2dLayer = 13, Layer_ReshapeLayer = 14, Layer_SoftmaxLayer = 15,
Layer_SpaceToBatchNdLayer = 16, Layer_DivisionLayer = 17, Layer_MinimumLayer = 18, Layer_EqualLayer = 19,
Layer_MaximumLayer = 20, Layer_NormalizationLayer = 21, Layer_PadLayer = 22, Layer_RsqrtLayer = 23,
Layer_FloorLayer = 24, Layer_GreaterLayer = 25, Layer_ResizeBilinearLayer = 26, Layer_SubtractionLayer = 27,
Layer_StridedSliceLayer = 28, Layer_GatherLayer = 29, Layer_MeanLayer = 30, Layer_MergerLayer = 31,
Layer_L2NormalizationLayer = 32, Layer_SplitterLayer = 33, Layer_DetectionPostProcessLayer = 34, Layer_LstmLayer = 35,
Layer_QuantizedLstmLayer = 36, Layer_QuantizeLayer = 37, Layer_DequantizeLayer = 38, Layer_MergeLayer = 39,
Layer_SwitchLayer = 40, Layer_ConcatLayer = 41, Layer_SpaceToDepthLayer = 42, Layer_PreluLayer = 43,
Layer_TransposeConvolution2dLayer = 44, Layer_ResizeLayer = 45, Layer_StackLayer = 46, Layer_AbsLayer = 47,
Layer_ArgMinMaxLayer = 48, Layer_SliceLayer = 49, Layer_DepthToSpaceLayer = 50, Layer_InstanceNormalizationLayer = 51,
Layer_LogSoftmaxLayer = 52, Layer_ComparisonLayer = 53, Layer_StandInLayer = 54, Layer_ElementwiseUnaryLayer = 55,
Layer_TransposeLayer = 56, Layer_QLstmLayer = 57, Layer_FillLayer = 58, Layer_RankLayer = 59,
Layer_LogicalBinaryLayer = 60, Layer_ReduceLayer = 61, Layer_CastLayer = 62, Layer_ShapeLayer = 63,
Layer_UnidirectionalSequenceLstmLayer = 64, Layer_ChannelShuffleLayer = 65, Layer_Convolution3dLayer = 66, Layer_Pooling3dLayer = 67,
Layer_GatherNdLayer = 68, Layer_MIN = Layer_NONE, Layer_MAX = Layer_GatherNdLayer
}
Functions
const ActivationFunction(& EnumValuesActivationFunction ())[12]
const char *const * EnumNamesActivationFunction ()
const char * EnumNameActivationFunction (ActivationFunction e)
const ArgMinMaxFunction(& EnumValuesArgMinMaxFunction ())[2]
const char *const * EnumNamesArgMinMaxFunction ()
const char * EnumNameArgMinMaxFunction (ArgMinMaxFunction e)
const DataType(& EnumValuesDataType ())[11]
const char *const * EnumNamesDataType ()
const char * EnumNameDataType (DataType e)
const DataLayout(& EnumValuesDataLayout ())[4]
const char *const * EnumNamesDataLayout ()
const char * EnumNameDataLayout (DataLayout e)
const ReduceOperation(& EnumValuesReduceOperation ())[5]
const char *const * EnumNamesReduceOperation ()
const char * EnumNameReduceOperation (ReduceOperation e)
const ResizeMethod(& EnumValuesResizeMethod ())[2]
const char *const * EnumNamesResizeMethod ()
const char * EnumNameResizeMethod (ResizeMethod e)
const ConstTensorData(& EnumValuesConstTensorData ())[5]
const char *const * EnumNamesConstTensorData ()
const char * EnumNameConstTensorData (ConstTensorData e)
bool VerifyConstTensorData (flatbuffers::Verifier &verifier, const void *obj, ConstTensorData type)
bool VerifyConstTensorDataVector (flatbuffers::Verifier &verifier, const flatbuffers::Vector< flatbuffers::Offset< void >> *values, const flatbuffers::Vector< uint8_t > *types)
const LayerType(& EnumValuesLayerType ())[68]
const char *const * EnumNamesLayerType ()
const char * EnumNameLayerType (LayerType e)
const ComparisonOperation(& EnumValuesComparisonOperation ())[6]
const char *const * EnumNamesComparisonOperation ()
const char * EnumNameComparisonOperation (ComparisonOperation e)
const UnaryOperation(& EnumValuesUnaryOperation ())[8]
const char *const * EnumNamesUnaryOperation ()
const char * EnumNameUnaryOperation (UnaryOperation e)
const LogicalBinaryOperation(& EnumValuesLogicalBinaryOperation ())[2]
const char *const * EnumNamesLogicalBinaryOperation ()
const char * EnumNameLogicalBinaryOperation (LogicalBinaryOperation e)
const PoolingAlgorithm(& EnumValuesPoolingAlgorithm ())[3]
const char *const * EnumNamesPoolingAlgorithm ()
const char * EnumNamePoolingAlgorithm (PoolingAlgorithm e)
const OutputShapeRounding(& EnumValuesOutputShapeRounding ())[2]
const char *const * EnumNamesOutputShapeRounding ()
const char * EnumNameOutputShapeRounding (OutputShapeRounding e)
const PaddingMethod(& EnumValuesPaddingMethod ())[2]
const char *const * EnumNamesPaddingMethod ()
const char * EnumNamePaddingMethod (PaddingMethod e)
const NormalizationAlgorithmChannel(& EnumValuesNormalizationAlgorithmChannel ())[2]
const char *const * EnumNamesNormalizationAlgorithmChannel ()
const char * EnumNameNormalizationAlgorithmChannel (NormalizationAlgorithmChannel e)
const NormalizationAlgorithmMethod(& EnumValuesNormalizationAlgorithmMethod ())[2]
const char *const * EnumNamesNormalizationAlgorithmMethod ()
const char * EnumNameNormalizationAlgorithmMethod (NormalizationAlgorithmMethod e)
const PaddingMode(& EnumValuesPaddingMode ())[3]
const char *const * EnumNamesPaddingMode ()
const char * EnumNamePaddingMode (PaddingMode e)
const Layer(& EnumValuesLayer ())[69]
const char *const * EnumNamesLayer ()
const char * EnumNameLayer (Layer e)
bool VerifyLayer (flatbuffers::Verifier &verifier, const void *obj, Layer type)
bool VerifyLayerVector (flatbuffers::Verifier &verifier, const flatbuffers::Vector< flatbuffers::Offset< void >> *values, const flatbuffers::Vector< uint8_t > *types)
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT (4) Connection FLATBUFFERS_FINAL_CLASS
FLATBUFFERS_STRUCT_END (Connection, 8)
flatbuffers::Offset< TensorInfo > CreateTensorInfo (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimensions=0, armnnSerializer::DataType dataType=armnnSerializer::DataType_Float16, float quantizationScale=1.0f, int32_t quantizationOffset=0, flatbuffers::Offset< flatbuffers::Vector< float >> quantizationScales=0, uint32_t quantizationDim=0, uint32_t dimensionality=1, flatbuffers::Offset< flatbuffers::Vector< uint8_t >> dimensionSpecificity=0, bool isConstant=false)
flatbuffers::Offset< TensorInfo > CreateTensorInfoDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *dimensions=nullptr, armnnSerializer::DataType dataType=armnnSerializer::DataType_Float16, float quantizationScale=1.0f, int32_t quantizationOffset=0, const std::vector< float > *quantizationScales=nullptr, uint32_t quantizationDim=0, uint32_t dimensionality=1, const std::vector< uint8_t > *dimensionSpecificity=nullptr, bool isConstant=false)
flatbuffers::Offset< ByteData > CreateByteData (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< int8_t >> data=0)
flatbuffers::Offset< ByteData > CreateByteDataDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< int8_t > *data=nullptr)
flatbuffers::Offset< ShortData > CreateShortData (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< int16_t >> data=0)
flatbuffers::Offset< ShortData > CreateShortDataDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< int16_t > *data=nullptr)
flatbuffers::Offset< IntData > CreateIntData (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< int32_t >> data=0)
flatbuffers::Offset< IntData > CreateIntDataDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< int32_t > *data=nullptr)
flatbuffers::Offset< LongData > CreateLongData (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< int64_t >> data=0)
flatbuffers::Offset< LongData > CreateLongDataDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< int64_t > *data=nullptr)
template<>
const armnnSerializer::ByteData * ConstTensor::data_as< armnnSerializer::ByteData > () const
template<>
const armnnSerializer::ShortData * ConstTensor::data_as< armnnSerializer::ShortData > () const
template<>
const armnnSerializer::IntData * ConstTensor::data_as< armnnSerializer::IntData > () const
template<>
const armnnSerializer::LongData * ConstTensor::data_as< armnnSerializer::LongData > () const
flatbuffers::Offset< ConstTensor > CreateConstTensor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::TensorInfo > info=0, armnnSerializer::ConstTensorData data_type=armnnSerializer::ConstTensorData_NONE, flatbuffers::Offset< void > data=0)
flatbuffers::Offset< InputSlot > CreateInputSlot (flatbuffers::FlatBufferBuilder &_fbb, uint32_t index=0, const armnnSerializer::Connection *connection=0)
flatbuffers::Offset< OutputSlot > CreateOutputSlot (flatbuffers::FlatBufferBuilder &_fbb, uint32_t index=0, flatbuffers::Offset< armnnSerializer::TensorInfo > tensorInfo=0)
flatbuffers::Offset< LayerBase > CreateLayerBase (flatbuffers::FlatBufferBuilder &_fbb, uint32_t index=0, flatbuffers::Offset< flatbuffers::String > layerName=0, armnnSerializer::LayerType layerType=armnnSerializer::LayerType_Addition, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::InputSlot >>> inputSlots=0, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::OutputSlot >>> outputSlots=0)
flatbuffers::Offset< LayerBase > CreateLayerBaseDirect (flatbuffers::FlatBufferBuilder &_fbb, uint32_t index=0, const char *layerName=nullptr, armnnSerializer::LayerType layerType=armnnSerializer::LayerType_Addition, const std::vector< flatbuffers::Offset< armnnSerializer::InputSlot >> *inputSlots=nullptr, const std::vector< flatbuffers::Offset< armnnSerializer::OutputSlot >> *outputSlots=nullptr)
flatbuffers::Offset< BindableLayerBase > CreateBindableLayerBase (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, int32_t layerBindingId=0)
flatbuffers::Offset< AbsLayer > CreateAbsLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< ActivationLayer > CreateActivationLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ActivationDescriptor > descriptor=0)
flatbuffers::Offset< ActivationDescriptor > CreateActivationDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::ActivationFunction activationFunction=armnnSerializer::ActivationFunction_Sigmoid, float a=0.0f, float b=0.0f)
flatbuffers::Offset< AdditionLayer > CreateAdditionLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< ArgMinMaxLayer > CreateArgMinMaxLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ArgMinMaxDescriptor > descriptor=0)
flatbuffers::Offset< ArgMinMaxDescriptor > CreateArgMinMaxDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::ArgMinMaxFunction argMinMaxFunction=armnnSerializer::ArgMinMaxFunction_Min, int32_t axis=0)
flatbuffers::Offset< CastLayer > CreateCastLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< ChannelShuffleLayer > CreateChannelShuffleLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ChannelShuffleDescriptor > descriptor=0)
flatbuffers::Offset< ChannelShuffleDescriptor > CreateChannelShuffleDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t axis=0, uint32_t numGroups=0)
flatbuffers::Offset< ComparisonDescriptor > CreateComparisonDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::ComparisonOperation operation=armnnSerializer::ComparisonOperation_Equal)
flatbuffers::Offset< ComparisonLayer > CreateComparisonLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ComparisonDescriptor > descriptor=0)
flatbuffers::Offset< ConstantLayer > CreateConstantLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ConstTensor > input=0)
flatbuffers::Offset< Convolution2dLayer > CreateConvolution2dLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::Convolution2dDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases=0)
flatbuffers::Offset< Convolution2dDescriptor > CreateConvolution2dDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t padLeft=0, uint32_t padRight=0, uint32_t padTop=0, uint32_t padBottom=0, uint32_t strideX=0, uint32_t strideY=0, uint32_t dilationX=1, uint32_t dilationY=1, bool biasEnabled=false, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NCHW)
flatbuffers::Offset< Convolution3dLayer > CreateConvolution3dLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::Convolution3dDescriptor > descriptor=0)
flatbuffers::Offset< Convolution3dDescriptor > CreateConvolution3dDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t padLeft=0, uint32_t padRight=0, uint32_t padTop=0, uint32_t padBottom=0, uint32_t padFront=0, uint32_t padBack=0, uint32_t strideX=0, uint32_t strideY=0, uint32_t strideZ=0, uint32_t dilationX=1, uint32_t dilationY=1, uint32_t dilationZ=1, bool biasEnabled=false, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NDHWC)
flatbuffers::Offset< DepthToSpaceLayer > CreateDepthToSpaceLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::DepthToSpaceDescriptor > descriptor=0)
flatbuffers::Offset< DepthToSpaceDescriptor > CreateDepthToSpaceDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t blockSize=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< DivisionLayer > CreateDivisionLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< ElementwiseUnaryDescriptor > CreateElementwiseUnaryDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::UnaryOperation operation=armnnSerializer::UnaryOperation_Abs)
flatbuffers::Offset< ElementwiseUnaryLayer > CreateElementwiseUnaryLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ElementwiseUnaryDescriptor > descriptor=0)
flatbuffers::Offset< EqualLayer > CreateEqualLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< FillLayer > CreateFillLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::FillDescriptor > descriptor=0)
flatbuffers::Offset< FillDescriptor > CreateFillDescriptor (flatbuffers::FlatBufferBuilder &_fbb, float value=0.0f)
flatbuffers::Offset< FloorLayer > CreateFloorLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< FullyConnectedLayer > CreateFullyConnectedLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::FullyConnectedDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases=0)
flatbuffers::Offset< FullyConnectedDescriptor > CreateFullyConnectedDescriptor (flatbuffers::FlatBufferBuilder &_fbb, bool biasEnabled=false, bool transposeWeightsMatrix=false, bool constantWeights=true)
flatbuffers::Offset< GatherLayer > CreateGatherLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::GatherDescriptor > descriptor=0)
flatbuffers::Offset< GatherDescriptor > CreateGatherDescriptor (flatbuffers::FlatBufferBuilder &_fbb, int32_t axis=0)
flatbuffers::Offset< GatherNdLayer > CreateGatherNdLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< GreaterLayer > CreateGreaterLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< InputLayer > CreateInputLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::BindableLayerBase > base=0)
flatbuffers::Offset< InstanceNormalizationLayer > CreateInstanceNormalizationLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::InstanceNormalizationDescriptor > descriptor=0)
flatbuffers::Offset< InstanceNormalizationDescriptor > CreateInstanceNormalizationDescriptor (flatbuffers::FlatBufferBuilder &_fbb, float gamma=0.0f, float beta=0.0f, float eps=0.0f, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< LogSoftmaxLayer > CreateLogSoftmaxLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::LogSoftmaxDescriptor > descriptor=0)
flatbuffers::Offset< LogSoftmaxDescriptor > CreateLogSoftmaxDescriptor (flatbuffers::FlatBufferBuilder &_fbb, float beta=1.0f, int32_t axis=-1)
flatbuffers::Offset< L2NormalizationLayer > CreateL2NormalizationLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::L2NormalizationDescriptor > descriptor=0)
flatbuffers::Offset< L2NormalizationDescriptor > CreateL2NormalizationDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NCHW, float eps=1e-12f)
flatbuffers::Offset< LogicalBinaryDescriptor > CreateLogicalBinaryDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::LogicalBinaryOperation operation=armnnSerializer::LogicalBinaryOperation_LogicalAnd)
flatbuffers::Offset< LogicalBinaryLayer > CreateLogicalBinaryLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::LogicalBinaryDescriptor > descriptor=0)
flatbuffers::Offset< MinimumLayer > CreateMinimumLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< MaximumLayer > CreateMaximumLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< MultiplicationLayer > CreateMultiplicationLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< Pooling2dLayer > CreatePooling2dLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::Pooling2dDescriptor > descriptor=0)
flatbuffers::Offset< Pooling3dLayer > CreatePooling3dLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::Pooling3dDescriptor > descriptor=0)
flatbuffers::Offset< Pooling2dDescriptor > CreatePooling2dDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::PoolingAlgorithm poolType=armnnSerializer::PoolingAlgorithm_Max, uint32_t padLeft=0, uint32_t padRight=0, uint32_t padTop=0, uint32_t padBottom=0, uint32_t poolWidth=0, uint32_t poolHeight=0, uint32_t strideX=0, uint32_t strideY=0, armnnSerializer::OutputShapeRounding outputShapeRounding=armnnSerializer::OutputShapeRounding_Floor, armnnSerializer::PaddingMethod paddingMethod=armnnSerializer::PaddingMethod_IgnoreValue, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< Pooling3dDescriptor > CreatePooling3dDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::PoolingAlgorithm poolType=armnnSerializer::PoolingAlgorithm_Max, uint32_t padLeft=0, uint32_t padRight=0, uint32_t padTop=0, uint32_t padBottom=0, uint32_t padFront=0, uint32_t padBack=0, uint32_t poolWidth=0, uint32_t poolHeight=0, uint32_t poolDepth=0, uint32_t strideX=0, uint32_t strideY=0, uint32_t strideZ=0, armnnSerializer::OutputShapeRounding outputShapeRounding=armnnSerializer::OutputShapeRounding_Floor, armnnSerializer::PaddingMethod paddingMethod=armnnSerializer::PaddingMethod_IgnoreValue, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< QuantizeLayer > CreateQuantizeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< SoftmaxLayer > CreateSoftmaxLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::SoftmaxDescriptor > descriptor=0)
flatbuffers::Offset< SoftmaxDescriptor > CreateSoftmaxDescriptor (flatbuffers::FlatBufferBuilder &_fbb, float beta=0.0f, int32_t axis=-1)
flatbuffers::Offset< DepthwiseConvolution2dLayer > CreateDepthwiseConvolution2dLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::DepthwiseConvolution2dDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases=0)
flatbuffers::Offset< DepthwiseConvolution2dDescriptor > CreateDepthwiseConvolution2dDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t padLeft=0, uint32_t padRight=0, uint32_t padTop=0, uint32_t padBottom=0, uint32_t strideX=0, uint32_t strideY=0, uint32_t dilationX=1, uint32_t dilationY=1, bool biasEnabled=false, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NCHW)
flatbuffers::Offset< OutputLayer > CreateOutputLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::BindableLayerBase > base=0)
flatbuffers::Offset< ReshapeLayer > CreateReshapeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ReshapeDescriptor > descriptor=0)
flatbuffers::Offset< ReshapeDescriptor > CreateReshapeDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> targetShape=0)
flatbuffers::Offset< ReshapeDescriptor > CreateReshapeDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *targetShape=nullptr)
flatbuffers::Offset< PermuteLayer > CreatePermuteLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::PermuteDescriptor > descriptor=0)
flatbuffers::Offset< PermuteDescriptor > CreatePermuteDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimMappings=0)
flatbuffers::Offset< PermuteDescriptor > CreatePermuteDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *dimMappings=nullptr)
flatbuffers::Offset< ShapeLayer > CreateShapeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< SpaceToBatchNdLayer > CreateSpaceToBatchNdLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::SpaceToBatchNdDescriptor > descriptor=0)
flatbuffers::Offset< SpaceToBatchNdDescriptor > CreateSpaceToBatchNdDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape=0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< SpaceToBatchNdDescriptor > CreateSpaceToBatchNdDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *blockShape=nullptr, const std::vector< uint32_t > *padList=nullptr, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< SpaceToDepthLayer > CreateSpaceToDepthLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::SpaceToDepthDescriptor > descriptor=0)
flatbuffers::Offset< SpaceToDepthDescriptor > CreateSpaceToDepthDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t blockSize=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< SubtractionLayer > CreateSubtractionLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< BatchToSpaceNdLayer > CreateBatchToSpaceNdLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::BatchToSpaceNdDescriptor > descriptor=0)
flatbuffers::Offset< BatchToSpaceNdDescriptor > CreateBatchToSpaceNdDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape=0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> crops=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< BatchToSpaceNdDescriptor > CreateBatchToSpaceNdDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *blockShape=nullptr, const std::vector< uint32_t > *crops=nullptr, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< NormalizationLayer > CreateNormalizationLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::NormalizationDescriptor > descriptor=0)
flatbuffers::Offset< NormalizationDescriptor > CreateNormalizationDescriptor (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::NormalizationAlgorithmChannel normChannelType=armnnSerializer::NormalizationAlgorithmChannel_Across, armnnSerializer::NormalizationAlgorithmMethod normMethodType=armnnSerializer::NormalizationAlgorithmMethod_LocalBrightness, uint32_t normSize=0, float alpha=0.0f, float beta=0.0f, float k=0.0f, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NCHW)
flatbuffers::Offset< MeanLayer > CreateMeanLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::MeanDescriptor > descriptor=0)
flatbuffers::Offset< MeanDescriptor > CreateMeanDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis=0, bool keepDims=false)
flatbuffers::Offset< MeanDescriptor > CreateMeanDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *axis=nullptr, bool keepDims=false)
flatbuffers::Offset< PadLayer > CreatePadLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::PadDescriptor > descriptor=0)
flatbuffers::Offset< PadDescriptor > CreatePadDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList=0, float padValue=0.0f, armnnSerializer::PaddingMode paddingMode=armnnSerializer::PaddingMode_Constant)
flatbuffers::Offset< PadDescriptor > CreatePadDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *padList=nullptr, float padValue=0.0f, armnnSerializer::PaddingMode paddingMode=armnnSerializer::PaddingMode_Constant)
flatbuffers::Offset< RsqrtLayer > CreateRsqrtLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< BatchNormalizationLayer > CreateBatchNormalizationLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::BatchNormalizationDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::ConstTensor > mean=0, flatbuffers::Offset< armnnSerializer::ConstTensor > variance=0, flatbuffers::Offset< armnnSerializer::ConstTensor > beta=0, flatbuffers::Offset< armnnSerializer::ConstTensor > gamma=0)
flatbuffers::Offset< BatchNormalizationDescriptor > CreateBatchNormalizationDescriptor (flatbuffers::FlatBufferBuilder &_fbb, float eps=0.0f, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< ResizeBilinearLayer > CreateResizeBilinearLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ResizeBilinearDescriptor > descriptor=0)
flatbuffers::Offset< ResizeBilinearDescriptor > CreateResizeBilinearDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t targetWidth=0, uint32_t targetHeight=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC, bool alignCorners=false, bool halfPixelCenters=false)
flatbuffers::Offset< SliceLayer > CreateSliceLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::SliceDescriptor > descriptor=0)
flatbuffers::Offset< SliceDescriptor > CreateSliceDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> begin=0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> size=0)
flatbuffers::Offset< SliceDescriptor > CreateSliceDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *begin=nullptr, const std::vector< uint32_t > *size=nullptr)
flatbuffers::Offset< StridedSliceLayer > CreateStridedSliceLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::StridedSliceDescriptor > descriptor=0)
flatbuffers::Offset< StridedSliceDescriptor > CreateStridedSliceDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< int32_t >> begin=0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> end=0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> stride=0, int32_t beginMask=0, int32_t endMask=0, int32_t shrinkAxisMask=0, int32_t ellipsisMask=0, int32_t newAxisMask=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< StridedSliceDescriptor > CreateStridedSliceDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< int32_t > *begin=nullptr, const std::vector< int32_t > *end=nullptr, const std::vector< int32_t > *stride=nullptr, int32_t beginMask=0, int32_t endMask=0, int32_t shrinkAxisMask=0, int32_t ellipsisMask=0, int32_t newAxisMask=0, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC)
flatbuffers::Offset< ConcatLayer > CreateConcatLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > descriptor=0)
flatbuffers::Offset< MergerLayer > CreateMergerLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > descriptor=0)
flatbuffers::Offset< UintVector > CreateUintVector (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> data=0)
flatbuffers::Offset< UintVector > CreateUintVectorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *data=nullptr)
flatbuffers::Offset< OriginsDescriptor > CreateOriginsDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t concatAxis=0, uint32_t numViews=0, uint32_t numDimensions=0, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewOrigins=0)
flatbuffers::Offset< OriginsDescriptor > CreateOriginsDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, uint32_t concatAxis=0, uint32_t numViews=0, uint32_t numDimensions=0, const std::vector< flatbuffers::Offset< armnnSerializer::UintVector >> *viewOrigins=nullptr)
flatbuffers::Offset< ViewsDescriptor > CreateViewsDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > origins=0, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewSizes=0)
flatbuffers::Offset< ViewsDescriptor > CreateViewsDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > origins=0, const std::vector< flatbuffers::Offset< armnnSerializer::UintVector >> *viewSizes=nullptr)
flatbuffers::Offset< SplitterLayer > CreateSplitterLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ViewsDescriptor > descriptor=0)
flatbuffers::Offset< DetectionPostProcessLayer > CreateDetectionPostProcessLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::DetectionPostProcessDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::ConstTensor > anchors=0)
flatbuffers::Offset< DetectionPostProcessDescriptor > CreateDetectionPostProcessDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t maxDetections=0, uint32_t maxClassesPerDetection=0, uint32_t detectionsPerClass=0, float nmsScoreThreshold=0.0f, float nmsIouThreshold=0.0f, uint32_t numClasses=0, bool useRegularNms=false, float scaleX=0.0f, float scaleY=0.0f, float scaleW=0.0f, float scaleH=0.0f)
flatbuffers::Offset< LstmInputParams > CreateLstmInputParams (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights=0)
flatbuffers::Offset< LstmDescriptor > CreateLstmDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t activationFunc=0, float clippingThresCell=0.0f, float clippingThresProj=0.0f, bool cifgEnabled=true, bool peepholeEnabled=false, bool projectionEnabled=false, bool layerNormEnabled=false)
flatbuffers::Offset< LstmLayer > CreateLstmLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::LstmDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::LstmInputParams > inputParams=0)
flatbuffers::Offset< QLstmInputParams > CreateQLstmInputParams (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights=0)
flatbuffers::Offset< QLstmDescriptor > CreateQLstmDescriptor (flatbuffers::FlatBufferBuilder &_fbb, bool cifgEnabled=true, bool peepholeEnabled=false, bool projectionEnabled=false, bool layerNormEnabled=false, float cellClip=0.0f, float projectionClip=0.0f, float inputIntermediateScale=0.0f, float forgetIntermediateScale=0.0f, float cellIntermediateScale=0.0f, float outputIntermediateScale=0.0f, int32_t hiddenStateZeroPoint=0, float hiddenStateScale=0.0f)
flatbuffers::Offset< QLstmLayer > CreateQLstmLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::QLstmDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::QLstmInputParams > inputParams=0)
flatbuffers::Offset< QuantizedLstmInputParams > CreateQuantizedLstmInputParams (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias=0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias=0)
flatbuffers::Offset< QuantizedLstmLayer > CreateQuantizedLstmLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::QuantizedLstmInputParams > inputParams=0)
flatbuffers::Offset< DequantizeLayer > CreateDequantizeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< MergeLayer > CreateMergeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< SwitchLayer > CreateSwitchLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< PreluLayer > CreatePreluLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< TransposeConvolution2dLayer > CreateTransposeConvolution2dLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::TransposeConvolution2dDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights=0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases=0)
flatbuffers::Offset< TransposeConvolution2dDescriptor > CreateTransposeConvolution2dDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t padLeft=0, uint32_t padRight=0, uint32_t padTop=0, uint32_t padBottom=0, uint32_t strideX=0, uint32_t strideY=0, bool biasEnabled=false, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NCHW)
flatbuffers::Offset< TransposeLayer > CreateTransposeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::TransposeDescriptor > descriptor=0)
flatbuffers::Offset< TransposeDescriptor > CreateTransposeDescriptor (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimMappings=0)
flatbuffers::Offset< TransposeDescriptor > CreateTransposeDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< uint32_t > *dimMappings=nullptr)
flatbuffers::Offset< ResizeLayer > CreateResizeLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ResizeDescriptor > descriptor=0)
flatbuffers::Offset< ResizeDescriptor > CreateResizeDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t targetHeight=0, uint32_t targetWidth=0, armnnSerializer::ResizeMethod method=armnnSerializer::ResizeMethod_NearestNeighbor, armnnSerializer::DataLayout dataLayout=armnnSerializer::DataLayout_NHWC, bool alignCorners=false, bool halfPixelCenters=false)
flatbuffers::Offset< StackLayer > CreateStackLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::StackDescriptor > descriptor=0)
flatbuffers::Offset< StackDescriptor > CreateStackDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t axis=0, uint32_t numInputs=0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> inputShape=0)
flatbuffers::Offset< StackDescriptor > CreateStackDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, uint32_t axis=0, uint32_t numInputs=0, const std::vector< uint32_t > *inputShape=nullptr)
flatbuffers::Offset< StandInDescriptor > CreateStandInDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t numInputs=0, uint32_t numOutputs=0)
flatbuffers::Offset< StandInLayer > CreateStandInLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::StandInDescriptor > descriptor=0)
flatbuffers::Offset< RankLayer > CreateRankLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0)
flatbuffers::Offset< ReduceLayer > CreateReduceLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::ReduceDescriptor > descriptor=0)
flatbuffers::Offset< ReduceDescriptor > CreateReduceDescriptor (flatbuffers::FlatBufferBuilder &_fbb, bool keepDims=false, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis=0, armnnSerializer::ReduceOperation reduceOperation=armnnSerializer::ReduceOperation_Sum)
flatbuffers::Offset< ReduceDescriptor > CreateReduceDescriptorDirect (flatbuffers::FlatBufferBuilder &_fbb, bool keepDims=false, const std::vector< uint32_t > *axis=nullptr, armnnSerializer::ReduceOperation reduceOperation=armnnSerializer::ReduceOperation_Sum)
flatbuffers::Offset< UnidirectionalSequenceLstmDescriptor > CreateUnidirectionalSequenceLstmDescriptor (flatbuffers::FlatBufferBuilder &_fbb, uint32_t activationFunc=0, float clippingThresCell=0.0f, float clippingThresProj=0.0f, bool cifgEnabled=true, bool peepholeEnabled=false, bool projectionEnabled=false, bool layerNormEnabled=false, bool timeMajor=false)
flatbuffers::Offset< UnidirectionalSequenceLstmLayer > CreateUnidirectionalSequenceLstmLayer (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base=0, flatbuffers::Offset< armnnSerializer::UnidirectionalSequenceLstmDescriptor > descriptor=0, flatbuffers::Offset< armnnSerializer::LstmInputParams > inputParams=0)
template<>
const armnnSerializer::ActivationLayer * AnyLayer::layer_as< armnnSerializer::ActivationLayer > () const
template<>
const armnnSerializer::AdditionLayer * AnyLayer::layer_as< armnnSerializer::AdditionLayer > () const
template<>
const armnnSerializer::BatchToSpaceNdLayer * AnyLayer::layer_as< armnnSerializer::BatchToSpaceNdLayer > () const
template<>
const armnnSerializer::BatchNormalizationLayer * AnyLayer::layer_as< armnnSerializer::BatchNormalizationLayer > () const
template<>
const armnnSerializer::ConstantLayer * AnyLayer::layer_as< armnnSerializer::ConstantLayer > () const
template<>
const armnnSerializer::Convolution2dLayer * AnyLayer::layer_as< armnnSerializer::Convolution2dLayer > () const
template<>
const armnnSerializer::DepthwiseConvolution2dLayer * AnyLayer::layer_as< armnnSerializer::DepthwiseConvolution2dLayer > () const
template<>
const armnnSerializer::FullyConnectedLayer * AnyLayer::layer_as< armnnSerializer::FullyConnectedLayer > () const
template<>
const armnnSerializer::InputLayer * AnyLayer::layer_as< armnnSerializer::InputLayer > () const
template<>
const armnnSerializer::MultiplicationLayer * AnyLayer::layer_as< armnnSerializer::MultiplicationLayer > () const
template<>
const armnnSerializer::OutputLayer * AnyLayer::layer_as< armnnSerializer::OutputLayer > () const
template<>
const armnnSerializer::PermuteLayer * AnyLayer::layer_as< armnnSerializer::PermuteLayer > () const
template<>
const armnnSerializer::Pooling2dLayer * AnyLayer::layer_as< armnnSerializer::Pooling2dLayer > () const
template<>
const armnnSerializer::ReshapeLayer * AnyLayer::layer_as< armnnSerializer::ReshapeLayer > () const
template<>
const armnnSerializer::SoftmaxLayer * AnyLayer::layer_as< armnnSerializer::SoftmaxLayer > () const
template<>
const armnnSerializer::SpaceToBatchNdLayer * AnyLayer::layer_as< armnnSerializer::SpaceToBatchNdLayer > () const
template<>
const armnnSerializer::DivisionLayer * AnyLayer::layer_as< armnnSerializer::DivisionLayer > () const
template<>
const armnnSerializer::MinimumLayer * AnyLayer::layer_as< armnnSerializer::MinimumLayer > () const
template<>
const armnnSerializer::EqualLayer * AnyLayer::layer_as< armnnSerializer::EqualLayer > () const
template<>
const armnnSerializer::MaximumLayer * AnyLayer::layer_as< armnnSerializer::MaximumLayer > () const
template<>
const armnnSerializer::NormalizationLayer * AnyLayer::layer_as< armnnSerializer::NormalizationLayer > () const
template<>
const armnnSerializer::PadLayer * AnyLayer::layer_as< armnnSerializer::PadLayer > () const
template<>
const armnnSerializer::RsqrtLayer * AnyLayer::layer_as< armnnSerializer::RsqrtLayer > () const
template<>
const armnnSerializer::FloorLayer * AnyLayer::layer_as< armnnSerializer::FloorLayer > () const
template<>
const armnnSerializer::GreaterLayer * AnyLayer::layer_as< armnnSerializer::GreaterLayer > () const
template<>
const armnnSerializer::ResizeBilinearLayer * AnyLayer::layer_as< armnnSerializer::ResizeBilinearLayer > () const
template<>
const armnnSerializer::SubtractionLayer * AnyLayer::layer_as< armnnSerializer::SubtractionLayer > () const
template<>
const armnnSerializer::StridedSliceLayer * AnyLayer::layer_as< armnnSerializer::StridedSliceLayer > () const
template<>
const armnnSerializer::GatherLayer * AnyLayer::layer_as< armnnSerializer::GatherLayer > () const
template<>
const armnnSerializer::MeanLayer * AnyLayer::layer_as< armnnSerializer::MeanLayer > () const
template<>
const armnnSerializer::MergerLayer * AnyLayer::layer_as< armnnSerializer::MergerLayer > () const
template<>
const armnnSerializer::L2NormalizationLayer * AnyLayer::layer_as< armnnSerializer::L2NormalizationLayer > () const
template<>
const armnnSerializer::SplitterLayer * AnyLayer::layer_as< armnnSerializer::SplitterLayer > () const
template<>
const armnnSerializer::DetectionPostProcessLayer * AnyLayer::layer_as< armnnSerializer::DetectionPostProcessLayer > () const
template<>
const armnnSerializer::LstmLayer * AnyLayer::layer_as< armnnSerializer::LstmLayer > () const
template<>
const armnnSerializer::QuantizedLstmLayer * AnyLayer::layer_as< armnnSerializer::QuantizedLstmLayer > () const
template<>
const armnnSerializer::QuantizeLayer * AnyLayer::layer_as< armnnSerializer::QuantizeLayer > () const
template<>
const armnnSerializer::DequantizeLayer * AnyLayer::layer_as< armnnSerializer::DequantizeLayer > () const
template<>
const armnnSerializer::MergeLayer * AnyLayer::layer_as< armnnSerializer::MergeLayer > () const
template<>
const armnnSerializer::SwitchLayer * AnyLayer::layer_as< armnnSerializer::SwitchLayer > () const
template<>
const armnnSerializer::ConcatLayer * AnyLayer::layer_as< armnnSerializer::ConcatLayer > () const
template<>
const armnnSerializer::SpaceToDepthLayer * AnyLayer::layer_as< armnnSerializer::SpaceToDepthLayer > () const
template<>
const armnnSerializer::PreluLayer * AnyLayer::layer_as< armnnSerializer::PreluLayer > () const
template<>
const armnnSerializer::TransposeConvolution2dLayer * AnyLayer::layer_as< armnnSerializer::TransposeConvolution2dLayer > () const
template<>
const armnnSerializer::ResizeLayer * AnyLayer::layer_as< armnnSerializer::ResizeLayer > () const
template<>
const armnnSerializer::StackLayer * AnyLayer::layer_as< armnnSerializer::StackLayer > () const
template<>
const armnnSerializer::AbsLayer * AnyLayer::layer_as< armnnSerializer::AbsLayer > () const
template<>
const armnnSerializer::ArgMinMaxLayer * AnyLayer::layer_as< armnnSerializer::ArgMinMaxLayer > () const
template<>
const armnnSerializer::SliceLayer * AnyLayer::layer_as< armnnSerializer::SliceLayer > () const
template<>
const armnnSerializer::DepthToSpaceLayer * AnyLayer::layer_as< armnnSerializer::DepthToSpaceLayer > () const
template<>
const armnnSerializer::InstanceNormalizationLayer * AnyLayer::layer_as< armnnSerializer::InstanceNormalizationLayer > () const
template<>
const armnnSerializer::LogSoftmaxLayer * AnyLayer::layer_as< armnnSerializer::LogSoftmaxLayer > () const
template<>
const armnnSerializer::ComparisonLayer * AnyLayer::layer_as< armnnSerializer::ComparisonLayer > () const
template<>
const armnnSerializer::StandInLayer * AnyLayer::layer_as< armnnSerializer::StandInLayer > () const
template<>
const armnnSerializer::ElementwiseUnaryLayer * AnyLayer::layer_as< armnnSerializer::ElementwiseUnaryLayer > () const
template<>
const armnnSerializer::TransposeLayer * AnyLayer::layer_as< armnnSerializer::TransposeLayer > () const
template<>
const armnnSerializer::QLstmLayer * AnyLayer::layer_as< armnnSerializer::QLstmLayer > () const
template<>
const armnnSerializer::FillLayer * AnyLayer::layer_as< armnnSerializer::FillLayer > () const
template<>
const armnnSerializer::RankLayer * AnyLayer::layer_as< armnnSerializer::RankLayer > () const
template<>
const armnnSerializer::LogicalBinaryLayer * AnyLayer::layer_as< armnnSerializer::LogicalBinaryLayer > () const
template<>
const armnnSerializer::ReduceLayer * AnyLayer::layer_as< armnnSerializer::ReduceLayer > () const
template<>
const armnnSerializer::CastLayer * AnyLayer::layer_as< armnnSerializer::CastLayer > () const
template<>
const armnnSerializer::ShapeLayer * AnyLayer::layer_as< armnnSerializer::ShapeLayer > () const
template<>
const armnnSerializer::UnidirectionalSequenceLstmLayer * AnyLayer::layer_as< armnnSerializer::UnidirectionalSequenceLstmLayer > () const
template<>
const armnnSerializer::ChannelShuffleLayer * AnyLayer::layer_as< armnnSerializer::ChannelShuffleLayer > () const
template<>
const armnnSerializer::Convolution3dLayer * AnyLayer::layer_as< armnnSerializer::Convolution3dLayer > () const
template<>
const armnnSerializer::Pooling3dLayer * AnyLayer::layer_as< armnnSerializer::Pooling3dLayer > () const
template<>
const armnnSerializer::GatherNdLayer * AnyLayer::layer_as< armnnSerializer::GatherNdLayer > () const
flatbuffers::Offset< AnyLayer > CreateAnyLayer (flatbuffers::FlatBufferBuilder &_fbb, armnnSerializer::Layer layer_type=armnnSerializer::Layer_NONE, flatbuffers::Offset< void > layer=0)
flatbuffers::Offset< FeatureCompatibilityVersions > CreateFeatureCompatibilityVersions (flatbuffers::FlatBufferBuilder &_fbb, uint32_t bindingIdsScheme=0, uint32_t weightsLayoutScheme=0, uint32_t constantTensorsAsInputs=0)
flatbuffers::Offset< SerializedGraph > CreateSerializedGraph (flatbuffers::FlatBufferBuilder &_fbb, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::AnyLayer >>> layers=0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> inputIds=0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> outputIds=0, flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > featureVersions=0)
flatbuffers::Offset< SerializedGraph > CreateSerializedGraphDirect (flatbuffers::FlatBufferBuilder &_fbb, const std::vector< flatbuffers::Offset< armnnSerializer::AnyLayer >> *layers=nullptr, const std::vector< int32_t > *inputIds=nullptr, const std::vector< int32_t > *outputIds=nullptr, flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > featureVersions=0)
const armnnSerializer::SerializedGraph * GetSerializedGraph (const void *buf)
const armnnSerializer::SerializedGraph * GetSizePrefixedSerializedGraph (const void *buf)
const char * SerializedGraphIdentifier ()
bool SerializedGraphBufferHasIdentifier (const void *buf)
bool VerifySerializedGraphBuffer (flatbuffers::Verifier &verifier)
bool VerifySizePrefixedSerializedGraphBuffer (flatbuffers::Verifier &verifier)
const char * SerializedGraphExtension ()
void FinishSerializedGraphBuffer (flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset< armnnSerializer::SerializedGraph > root)
void FinishSizePrefixedSerializedGraphBuffer (flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset< armnnSerializer::SerializedGraph > root)
serializer::ActivationFunction GetFlatBufferActivationFunction (armnn::ActivationFunction function)
serializer::ArgMinMaxFunction GetFlatBufferArgMinMaxFunction (armnn::ArgMinMaxFunction function)
armnnSerializer::ComparisonOperation GetFlatBufferComparisonOperation (armnn::ComparisonOperation comparisonOperation)
armnnSerializer::LogicalBinaryOperation GetFlatBufferLogicalBinaryOperation (armnn::LogicalBinaryOperation logicalBinaryOperation)
armnnSerializer::ConstTensorData GetFlatBufferConstTensorData (armnn::DataType dataType)
armnnSerializer::DataType GetFlatBufferDataType (armnn::DataType dataType)
armnnSerializer::DataLayout GetFlatBufferDataLayout (armnn::DataLayout dataLayout)
armnnSerializer::UnaryOperation GetFlatBufferUnaryOperation (armnn::UnaryOperation comparisonOperation)
armnnSerializer::PoolingAlgorithm GetFlatBufferPoolingAlgorithm (armnn::PoolingAlgorithm poolingAlgorithm)
armnnSerializer::OutputShapeRounding GetFlatBufferOutputShapeRounding (armnn::OutputShapeRounding outputShapeRounding)
armnnSerializer::PaddingMethod GetFlatBufferPaddingMethod (armnn::PaddingMethod paddingMethod)
armnnSerializer::PaddingMode GetFlatBufferPaddingMode (armnn::PaddingMode paddingMode)
armnnSerializer::NormalizationAlgorithmChannel GetFlatBufferNormalizationAlgorithmChannel (armnn::NormalizationAlgorithmChannel normalizationAlgorithmChannel)
armnnSerializer::NormalizationAlgorithmMethod GetFlatBufferNormalizationAlgorithmMethod (armnn::NormalizationAlgorithmMethod normalizationAlgorithmMethod)
armnnSerializer::ResizeMethod GetFlatBufferResizeMethod (armnn::ResizeMethod method)
armnnSerializer::ReduceOperation GetFlatBufferReduceOperation (armnn::ReduceOperation reduceOperation)
Typedef Documentation
ISerializerPtr
using ISerializerPtr = std::unique_ptr<ISerializer, void(*)(ISerializer* serializer)>
Definition at line 15 of file ISerializer.hpp.
Enumeration Type Documentation
ActivationFunction
enum ActivationFunction
Enumerator
ActivationFunction_Sigmoid
ActivationFunction_TanH
ActivationFunction_Linear
ActivationFunction_ReLu
ActivationFunction_BoundedReLu
ActivationFunction_SoftReLu
ActivationFunction_LeakyReLu
ActivationFunction_Abs
ActivationFunction_Sqrt
ActivationFunction_Square
ActivationFunction_Elu
ActivationFunction_HardSwish
ActivationFunction_MIN
ActivationFunction_MAX
Definition at line 401 of file ArmnnSchema_generated.h.
{
   ActivationFunction_Sigmoid = 0,
   ActivationFunction_TanH = 1,
   ActivationFunction_Linear = 2,
   ActivationFunction_ReLu = 3,
   ActivationFunction_BoundedReLu = 4,
   ActivationFunction_SoftReLu = 5,
   ActivationFunction_LeakyReLu = 6,
   ActivationFunction_Abs = 7,
   ActivationFunction_Sqrt = 8,
   ActivationFunction_Square = 9,
   ActivationFunction_Elu = 10,
   ActivationFunction_HardSwish = 11,
   ActivationFunction_MIN = ActivationFunction_Sigmoid,
   ActivationFunction_MAX = ActivationFunction_HardSwish
 };
ArgMinMaxFunction
enum ArgMinMaxFunction
Enumerator
ArgMinMaxFunction_Min
ArgMinMaxFunction_Max
ArgMinMaxFunction_MIN
ArgMinMaxFunction_MAX
Definition at line 461 of file ArmnnSchema_generated.h.
{
   ArgMinMaxFunction_Min = 0,
   ArgMinMaxFunction_Max = 1,
   ArgMinMaxFunction_MIN = ArgMinMaxFunction_Min,
   ArgMinMaxFunction_MAX = ArgMinMaxFunction_Max
 };
ComparisonOperation
enum ComparisonOperation
Enumerator
ComparisonOperation_Equal
ComparisonOperation_Greater
ComparisonOperation_GreaterOrEqual
ComparisonOperation_Less
ComparisonOperation_LessOrEqual
ComparisonOperation_NotEqual
ComparisonOperation_MIN
ComparisonOperation_MAX
Definition at line 943 of file ArmnnSchema_generated.h.
{
   ComparisonOperation_Equal = 0,
   ComparisonOperation_Greater = 1,
   ComparisonOperation_GreaterOrEqual = 2,
   ComparisonOperation_Less = 3,
   ComparisonOperation_LessOrEqual = 4,
   ComparisonOperation_NotEqual = 5,
   ComparisonOperation_MIN = ComparisonOperation_Equal,
   ComparisonOperation_MAX = ComparisonOperation_NotEqual
 };
ConstTensorData
enum ConstTensorData
Enumerator
ConstTensorData_NONE
ConstTensorData_ByteData
ConstTensorData_ShortData
ConstTensorData_IntData
ConstTensorData_LongData
ConstTensorData_MIN
ConstTensorData_MAX
Definition at line 653 of file ArmnnSchema_generated.h.
                      {
   ConstTensorData_NONE = 0,
   ConstTensorData_ByteData = 1,
   ConstTensorData_ShortData = 2,
   ConstTensorData_IntData = 3,
   ConstTensorData_LongData = 4,
   ConstTensorData_MIN = ConstTensorData_NONE,
   ConstTensorData_MAX = ConstTensorData_LongData
 };
DataLayout
enum DataLayout
Enumerator
DataLayout_NHWC
DataLayout_NCHW
DataLayout_NDHWC
DataLayout_NCDHW
DataLayout_MIN
DataLayout_MAX
Definition at line 548 of file ArmnnSchema_generated.h.
                 {
   DataLayout_NHWC = 0,
   DataLayout_NCHW = 1,
   DataLayout_NDHWC = 2,
   DataLayout_NCDHW = 3,
   DataLayout_MIN = DataLayout_NHWC,
   DataLayout_MAX = DataLayout_NCDHW
 };
DataType
enum DataType
Enumerator
DataType_Float16
DataType_Float32
DataType_QuantisedAsymm8
DataType_Signed32
DataType_Boolean
DataType_QuantisedSymm16
DataType_QAsymmU8
DataType_QSymmS16
DataType_QAsymmS8
DataType_QSymmS8
DataType_Signed64
DataType_MIN
DataType_MAX
Definition at line 491 of file ArmnnSchema_generated.h.
               {
   DataType_Float16 = 0,
   DataType_Float32 = 1,
   DataType_QuantisedAsymm8 = 2,
   DataType_Signed32 = 3,
   DataType_Boolean = 4,
   DataType_QuantisedSymm16 = 5,
   DataType_QAsymmU8 = 6,
   DataType_QSymmS16 = 7,
   DataType_QAsymmS8 = 8,
   DataType_QSymmS8 = 9,
   DataType_Signed64 = 10,
   DataType_MIN = DataType_Float16,
   DataType_MAX = DataType_Signed64
 };
Layer
enum Layer
Enumerator
Layer_NONE
Layer_ActivationLayer
Layer_AdditionLayer
Layer_BatchToSpaceNdLayer
Layer_BatchNormalizationLayer
Layer_ConstantLayer
Layer_Convolution2dLayer
Layer_DepthwiseConvolution2dLayer
Layer_FullyConnectedLayer
Layer_InputLayer
Layer_MultiplicationLayer
Layer_OutputLayer
Layer_PermuteLayer
Layer_Pooling2dLayer
Layer_ReshapeLayer
Layer_SoftmaxLayer
Layer_SpaceToBatchNdLayer
Layer_DivisionLayer
Layer_MinimumLayer
Layer_EqualLayer
Layer_MaximumLayer
Layer_NormalizationLayer
Layer_PadLayer
Layer_RsqrtLayer
Layer_FloorLayer
Layer_GreaterLayer
Layer_ResizeBilinearLayer
Layer_SubtractionLayer
Layer_StridedSliceLayer
Layer_GatherLayer
Layer_MeanLayer
Layer_MergerLayer
Layer_L2NormalizationLayer
Layer_SplitterLayer
Layer_DetectionPostProcessLayer
Layer_LstmLayer
Layer_QuantizedLstmLayer
Layer_QuantizeLayer
Layer_DequantizeLayer
Layer_MergeLayer
Layer_SwitchLayer
Layer_ConcatLayer
Layer_SpaceToDepthLayer
Layer_PreluLayer
Layer_TransposeConvolution2dLayer
Layer_ResizeLayer
Layer_StackLayer
Layer_AbsLayer
Layer_ArgMinMaxLayer
Layer_SliceLayer
Layer_DepthToSpaceLayer
Layer_InstanceNormalizationLayer
Layer_LogSoftmaxLayer
Layer_ComparisonLayer
Layer_StandInLayer
Layer_ElementwiseUnaryLayer
Layer_TransposeLayer
Layer_QLstmLayer
Layer_FillLayer
Layer_RankLayer
Layer_LogicalBinaryLayer
Layer_ReduceLayer
Layer_CastLayer
Layer_ShapeLayer
Layer_UnidirectionalSequenceLstmLayer
Layer_ChannelShuffleLayer
Layer_Convolution3dLayer
Layer_Pooling3dLayer
Layer_GatherNdLayer
Layer_MIN
Layer_MAX
Definition at line 1249 of file ArmnnSchema_generated.h.
            {
   Layer_NONE = 0,
   Layer_ActivationLayer = 1,
   Layer_AdditionLayer = 2,
   Layer_BatchToSpaceNdLayer = 3,
   Layer_BatchNormalizationLayer = 4,
   Layer_ConstantLayer = 5,
   Layer_Convolution2dLayer = 6,
   Layer_DepthwiseConvolution2dLayer = 7,
   Layer_FullyConnectedLayer = 8,
   Layer_InputLayer = 9,
   Layer_MultiplicationLayer = 10,
   Layer_OutputLayer = 11,
   Layer_PermuteLayer = 12,
   Layer_Pooling2dLayer = 13,
   Layer_ReshapeLayer = 14,
   Layer_SoftmaxLayer = 15,
   Layer_SpaceToBatchNdLayer = 16,
   Layer_DivisionLayer = 17,
   Layer_MinimumLayer = 18,
   Layer_EqualLayer = 19,
   Layer_MaximumLayer = 20,
   Layer_NormalizationLayer = 21,
   Layer_PadLayer = 22,
   Layer_RsqrtLayer = 23,
   Layer_FloorLayer = 24,
   Layer_GreaterLayer = 25,
   Layer_ResizeBilinearLayer = 26,
   Layer_SubtractionLayer = 27,
   Layer_StridedSliceLayer = 28,
   Layer_GatherLayer = 29,
   Layer_MeanLayer = 30,
   Layer_MergerLayer = 31,
   Layer_L2NormalizationLayer = 32,
   Layer_SplitterLayer = 33,
   Layer_DetectionPostProcessLayer = 34,
   Layer_LstmLayer = 35,
   Layer_QuantizedLstmLayer = 36,
   Layer_QuantizeLayer = 37,
   Layer_DequantizeLayer = 38,
   Layer_MergeLayer = 39,
   Layer_SwitchLayer = 40,
   Layer_ConcatLayer = 41,
   Layer_SpaceToDepthLayer = 42,
   Layer_PreluLayer = 43,
   Layer_TransposeConvolution2dLayer = 44,
   Layer_ResizeLayer = 45,
   Layer_StackLayer = 46,
   Layer_AbsLayer = 47,
   Layer_ArgMinMaxLayer = 48,
   Layer_SliceLayer = 49,
   Layer_DepthToSpaceLayer = 50,
   Layer_InstanceNormalizationLayer = 51,
   Layer_LogSoftmaxLayer = 52,
   Layer_ComparisonLayer = 53,
   Layer_StandInLayer = 54,
   Layer_ElementwiseUnaryLayer = 55,
   Layer_TransposeLayer = 56,
   Layer_QLstmLayer = 57,
   Layer_FillLayer = 58,
   Layer_RankLayer = 59,
   Layer_LogicalBinaryLayer = 60,
   Layer_ReduceLayer = 61,
   Layer_CastLayer = 62,
   Layer_ShapeLayer = 63,
   Layer_UnidirectionalSequenceLstmLayer = 64,
   Layer_ChannelShuffleLayer = 65,
   Layer_Convolution3dLayer = 66,
   Layer_Pooling3dLayer = 67,
   Layer_GatherNdLayer = 68,
   Layer_MIN = Layer_NONE,
   Layer_MAX = Layer_GatherNdLayer
 };
LayerType
enum LayerType
Enumerator
LayerType_Addition
LayerType_Input
LayerType_Multiplication
LayerType_Output
LayerType_Pooling2d
LayerType_Reshape
LayerType_Softmax
LayerType_Convolution2d
LayerType_DepthwiseConvolution2d
LayerType_Activation
LayerType_Permute
LayerType_FullyConnected
LayerType_Constant
LayerType_SpaceToBatchNd
LayerType_BatchToSpaceNd
LayerType_Division
LayerType_Minimum
LayerType_Equal
LayerType_Maximum
LayerType_Normalization
LayerType_Pad
LayerType_Rsqrt
LayerType_Floor
LayerType_BatchNormalization
LayerType_Greater
LayerType_ResizeBilinear
LayerType_Subtraction
LayerType_StridedSlice
LayerType_Gather
LayerType_Mean
LayerType_Merger
LayerType_L2Normalization
LayerType_Splitter
LayerType_DetectionPostProcess
LayerType_Lstm
LayerType_Quantize
LayerType_Dequantize
LayerType_Merge
LayerType_Switch
LayerType_Concat
LayerType_SpaceToDepth
LayerType_Prelu
LayerType_TransposeConvolution2d
LayerType_Resize
LayerType_Stack
LayerType_QuantizedLstm
LayerType_Abs
LayerType_ArgMinMax
LayerType_Slice
LayerType_DepthToSpace
LayerType_InstanceNormalization
LayerType_LogSoftmax
LayerType_Comparison
LayerType_StandIn
LayerType_ElementwiseUnary
LayerType_Transpose
LayerType_QLstm
LayerType_Fill
LayerType_Rank
LayerType_LogicalBinary
LayerType_Reduce
LayerType_Cast
LayerType_Shape
LayerType_UnidirectionalSequenceLstm
LayerType_ChannelShuffle
LayerType_Convolution3d
LayerType_Pooling3d
LayerType_GatherNd
LayerType_MIN
LayerType_MAX
Definition at line 715 of file ArmnnSchema_generated.h.
                {
   LayerType_Addition = 0,
   LayerType_Input = 1,
   LayerType_Multiplication = 2,
   LayerType_Output = 3,
   LayerType_Pooling2d = 4,
   LayerType_Reshape = 5,
   LayerType_Softmax = 6,
   LayerType_Convolution2d = 7,
   LayerType_DepthwiseConvolution2d = 8,
   LayerType_Activation = 9,
   LayerType_Permute = 10,
   LayerType_FullyConnected = 11,
   LayerType_Constant = 12,
   LayerType_SpaceToBatchNd = 13,
   LayerType_BatchToSpaceNd = 14,
   LayerType_Division = 15,
   LayerType_Minimum = 16,
   LayerType_Equal = 17,
   LayerType_Maximum = 18,
   LayerType_Normalization = 19,
   LayerType_Pad = 20,
   LayerType_Rsqrt = 21,
   LayerType_Floor = 22,
   LayerType_BatchNormalization = 23,
   LayerType_Greater = 24,
   LayerType_ResizeBilinear = 25,
   LayerType_Subtraction = 26,
   LayerType_StridedSlice = 27,
   LayerType_Gather = 28,
   LayerType_Mean = 29,
   LayerType_Merger = 30,
   LayerType_L2Normalization = 31,
   LayerType_Splitter = 32,
   LayerType_DetectionPostProcess = 33,
   LayerType_Lstm = 34,
   LayerType_Quantize = 35,
   LayerType_Dequantize = 36,
   LayerType_Merge = 37,
   LayerType_Switch = 38,
   LayerType_Concat = 39,
   LayerType_SpaceToDepth = 40,
   LayerType_Prelu = 41,
   LayerType_TransposeConvolution2d = 42,
   LayerType_Resize = 43,
   LayerType_Stack = 44,
   LayerType_QuantizedLstm = 45,
   LayerType_Abs = 46,
   LayerType_ArgMinMax = 47,
   LayerType_Slice = 48,
   LayerType_DepthToSpace = 49,
   LayerType_InstanceNormalization = 50,
   LayerType_LogSoftmax = 51,
   LayerType_Comparison = 52,
   LayerType_StandIn = 53,
   LayerType_ElementwiseUnary = 54,
   LayerType_Transpose = 55,
   LayerType_QLstm = 56,
   LayerType_Fill = 57,
   LayerType_Rank = 58,
   LayerType_LogicalBinary = 59,
   LayerType_Reduce = 60,
   LayerType_Cast = 61,
   LayerType_Shape = 62,
   LayerType_UnidirectionalSequenceLstm = 63,
   LayerType_ChannelShuffle = 64,
   LayerType_Convolution3d = 65,
   LayerType_Pooling3d = 66,
   LayerType_GatherNd = 67,
   LayerType_MIN = LayerType_Addition,
   LayerType_MAX = LayerType_GatherNd
 };
LogicalBinaryOperation
enum LogicalBinaryOperation
Enumerator
LogicalBinaryOperation_LogicalAnd
LogicalBinaryOperation_LogicalOr
LogicalBinaryOperation_MIN
LogicalBinaryOperation_MAX
Definition at line 1033 of file ArmnnSchema_generated.h.
{
   LogicalBinaryOperation_LogicalAnd = 0,
   LogicalBinaryOperation_LogicalOr = 1,
   LogicalBinaryOperation_MIN = LogicalBinaryOperation_LogicalAnd,
   LogicalBinaryOperation_MAX = LogicalBinaryOperation_LogicalOr
 };
NormalizationAlgorithmChannel
enum NormalizationAlgorithmChannel
Enumerator
NormalizationAlgorithmChannel_Across
NormalizationAlgorithmChannel_Within
NormalizationAlgorithmChannel_MIN
NormalizationAlgorithmChannel_MAX
Definition at line 1156 of file ArmnnSchema_generated.h.
{
   NormalizationAlgorithmChannel_Across = 0,
   NormalizationAlgorithmChannel_Within = 1,
   NormalizationAlgorithmChannel_MIN = NormalizationAlgorithmChannel_Across,
   NormalizationAlgorithmChannel_MAX = NormalizationAlgorithmChannel_Within
 };
NormalizationAlgorithmMethod
enum NormalizationAlgorithmMethod
Enumerator
NormalizationAlgorithmMethod_LocalBrightness
NormalizationAlgorithmMethod_LocalContrast
NormalizationAlgorithmMethod_MIN
NormalizationAlgorithmMethod_MAX
Definition at line 1186 of file ArmnnSchema_generated.h.
{
   NormalizationAlgorithmMethod_LocalBrightness = 0,
   NormalizationAlgorithmMethod_LocalContrast = 1,
   NormalizationAlgorithmMethod_MIN = NormalizationAlgorithmMethod_LocalBrightness,
   NormalizationAlgorithmMethod_MAX = NormalizationAlgorithmMethod_LocalContrast
 };
OutputShapeRounding
enum OutputShapeRounding
Enumerator
OutputShapeRounding_Floor
OutputShapeRounding_Ceiling
OutputShapeRounding_MIN
OutputShapeRounding_MAX
Definition at line 1096 of file ArmnnSchema_generated.h.
{
   OutputShapeRounding_Floor = 0,
   OutputShapeRounding_Ceiling = 1,
   OutputShapeRounding_MIN = OutputShapeRounding_Floor,
   OutputShapeRounding_MAX = OutputShapeRounding_Ceiling
 };
PaddingMethod
enum PaddingMethod
Enumerator
PaddingMethod_IgnoreValue
PaddingMethod_Exclude
PaddingMethod_MIN
PaddingMethod_MAX
Definition at line 1126 of file ArmnnSchema_generated.h.
                    {
   PaddingMethod_IgnoreValue = 0,
   PaddingMethod_Exclude = 1,
   PaddingMethod_MIN = PaddingMethod_IgnoreValue,
   PaddingMethod_MAX = PaddingMethod_Exclude
 };
PaddingMode
enum PaddingMode
Enumerator
PaddingMode_Constant
PaddingMode_Reflect
PaddingMode_Symmetric
PaddingMode_MIN
PaddingMode_MAX
Definition at line 1216 of file ArmnnSchema_generated.h.
                  {
   PaddingMode_Constant = 0,
   PaddingMode_Reflect = 1,
   PaddingMode_Symmetric = 2,
   PaddingMode_MIN = PaddingMode_Constant,
   PaddingMode_MAX = PaddingMode_Symmetric
 };
PoolingAlgorithm
enum PoolingAlgorithm
Enumerator
PoolingAlgorithm_Max
PoolingAlgorithm_Average
PoolingAlgorithm_L2
PoolingAlgorithm_MIN
PoolingAlgorithm_MAX
Definition at line 1063 of file ArmnnSchema_generated.h.
                       {
   PoolingAlgorithm_Max = 0,
   PoolingAlgorithm_Average = 1,
   PoolingAlgorithm_L2 = 2,
   PoolingAlgorithm_MIN = PoolingAlgorithm_Max,
   PoolingAlgorithm_MAX = PoolingAlgorithm_L2
 };
ReduceOperation
enum ReduceOperation
Enumerator
ReduceOperation_Sum
ReduceOperation_Max
ReduceOperation_Mean
ReduceOperation_Min
ReduceOperation_Prod
ReduceOperation_MIN
ReduceOperation_MAX
Definition at line 584 of file ArmnnSchema_generated.h.
                      {
   ReduceOperation_Sum = 0,
   ReduceOperation_Max = 1,
   ReduceOperation_Mean = 2,
   ReduceOperation_Min = 3,
   ReduceOperation_Prod = 4,
   ReduceOperation_MIN = ReduceOperation_Sum,
   ReduceOperation_MAX = ReduceOperation_Prod
 };
ResizeMethod
enum ResizeMethod
Enumerator
ResizeMethod_NearestNeighbor
ResizeMethod_Bilinear
ResizeMethod_MIN
ResizeMethod_MAX
Definition at line 623 of file ArmnnSchema_generated.h.
                   {
   ResizeMethod_NearestNeighbor = 0,
   ResizeMethod_Bilinear = 1,
   ResizeMethod_MIN = ResizeMethod_NearestNeighbor,
   ResizeMethod_MAX = ResizeMethod_Bilinear
 };
UnaryOperation
enum UnaryOperation
Enumerator
UnaryOperation_Abs
UnaryOperation_Rsqrt
UnaryOperation_Sqrt
UnaryOperation_Exp
UnaryOperation_Neg
UnaryOperation_LogicalNot
UnaryOperation_Log
UnaryOperation_Sin
UnaryOperation_MIN
UnaryOperation_MAX
Definition at line 985 of file ArmnnSchema_generated.h.
                     {
   UnaryOperation_Abs = 0,
   UnaryOperation_Rsqrt = 1,
   UnaryOperation_Sqrt = 2,
   UnaryOperation_Exp = 3,
   UnaryOperation_Neg = 4,
   UnaryOperation_LogicalNot = 5,
   UnaryOperation_Log = 6,
   UnaryOperation_Sin = 7,
   UnaryOperation_MIN = UnaryOperation_Abs,
   UnaryOperation_MAX = UnaryOperation_Sin
 };
Function Documentation
AnyLayer::layer_as< armnnSerializer::AbsLayer >()
const armnnSerializer::AbsLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::AbsLayer > () const inline
Definition at line 10789 of file ArmnnSchema_generated.h.
{
   return layer_as_AbsLayer();
 }
AnyLayer::layer_as< armnnSerializer::ActivationLayer >()
const armnnSerializer::ActivationLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ActivationLayer > () const inline
Definition at line 10605 of file ArmnnSchema_generated.h.
{
   return layer_as_ActivationLayer();
 }
AnyLayer::layer_as< armnnSerializer::AdditionLayer >()
const armnnSerializer::AdditionLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::AdditionLayer > () const inline
Definition at line 10609 of file ArmnnSchema_generated.h.
{
   return layer_as_AdditionLayer();
 }
AnyLayer::layer_as< armnnSerializer::ArgMinMaxLayer >()
const armnnSerializer::ArgMinMaxLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ArgMinMaxLayer > () const inline
Definition at line 10793 of file ArmnnSchema_generated.h.
{
   return layer_as_ArgMinMaxLayer();
 }
AnyLayer::layer_as< armnnSerializer::BatchNormalizationLayer >()
const armnnSerializer::BatchNormalizationLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::BatchNormalizationLayer > () const inline
Definition at line 10617 of file ArmnnSchema_generated.h.
{
   return layer_as_BatchNormalizationLayer();
 }
AnyLayer::layer_as< armnnSerializer::BatchToSpaceNdLayer >()
const armnnSerializer::BatchToSpaceNdLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::BatchToSpaceNdLayer > () const inline
Definition at line 10613 of file ArmnnSchema_generated.h.
{
   return layer_as_BatchToSpaceNdLayer();
 }
AnyLayer::layer_as< armnnSerializer::CastLayer >()
const armnnSerializer::CastLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::CastLayer > () const inline
Definition at line 10849 of file ArmnnSchema_generated.h.
{
   return layer_as_CastLayer();
 }
AnyLayer::layer_as< armnnSerializer::ChannelShuffleLayer >()
const armnnSerializer::ChannelShuffleLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ChannelShuffleLayer > () const inline
Definition at line 10861 of file ArmnnSchema_generated.h.
{
   return layer_as_ChannelShuffleLayer();
 }
AnyLayer::layer_as< armnnSerializer::ComparisonLayer >()
const armnnSerializer::ComparisonLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ComparisonLayer > () const inline
Definition at line 10813 of file ArmnnSchema_generated.h.
{
   return layer_as_ComparisonLayer();
 }
AnyLayer::layer_as< armnnSerializer::ConcatLayer >()
const armnnSerializer::ConcatLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ConcatLayer > () const inline
Definition at line 10765 of file ArmnnSchema_generated.h.
{
   return layer_as_ConcatLayer();
 }
AnyLayer::layer_as< armnnSerializer::ConstantLayer >()
const armnnSerializer::ConstantLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ConstantLayer > () const inline
Definition at line 10621 of file ArmnnSchema_generated.h.
{
   return layer_as_ConstantLayer();
 }
AnyLayer::layer_as< armnnSerializer::Convolution2dLayer >()
const armnnSerializer::Convolution2dLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::Convolution2dLayer > () const inline
Definition at line 10625 of file ArmnnSchema_generated.h.
{
   return layer_as_Convolution2dLayer();
 }
AnyLayer::layer_as< armnnSerializer::Convolution3dLayer >()
const armnnSerializer::Convolution3dLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::Convolution3dLayer > () const inline
Definition at line 10865 of file ArmnnSchema_generated.h.
{
   return layer_as_Convolution3dLayer();
 }
AnyLayer::layer_as< armnnSerializer::DepthToSpaceLayer >()
const armnnSerializer::DepthToSpaceLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::DepthToSpaceLayer > () const inline
Definition at line 10801 of file ArmnnSchema_generated.h.
{
   return layer_as_DepthToSpaceLayer();
 }
AnyLayer::layer_as< armnnSerializer::DepthwiseConvolution2dLayer >()
const armnnSerializer::DepthwiseConvolution2dLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::DepthwiseConvolution2dLayer > () const inline
Definition at line 10629 of file ArmnnSchema_generated.h.
{
   return layer_as_DepthwiseConvolution2dLayer();
 }
AnyLayer::layer_as< armnnSerializer::DequantizeLayer >()
const armnnSerializer::DequantizeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::DequantizeLayer > () const inline
Definition at line 10753 of file ArmnnSchema_generated.h.
{
   return layer_as_DequantizeLayer();
 }
AnyLayer::layer_as< armnnSerializer::DetectionPostProcessLayer >()
const armnnSerializer::DetectionPostProcessLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::DetectionPostProcessLayer > () const inline
Definition at line 10737 of file ArmnnSchema_generated.h.
{
   return layer_as_DetectionPostProcessLayer();
 }
AnyLayer::layer_as< armnnSerializer::DivisionLayer >()
const armnnSerializer::DivisionLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::DivisionLayer > () const inline
Definition at line 10669 of file ArmnnSchema_generated.h.
{
   return layer_as_DivisionLayer();
 }
AnyLayer::layer_as< armnnSerializer::ElementwiseUnaryLayer >()
const armnnSerializer::ElementwiseUnaryLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ElementwiseUnaryLayer > () const inline
Definition at line 10821 of file ArmnnSchema_generated.h.
{
   return layer_as_ElementwiseUnaryLayer();
 }
AnyLayer::layer_as< armnnSerializer::EqualLayer >()
const armnnSerializer::EqualLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::EqualLayer > () const inline
Definition at line 10677 of file ArmnnSchema_generated.h.
{
   return layer_as_EqualLayer();
 }
AnyLayer::layer_as< armnnSerializer::FillLayer >()
const armnnSerializer::FillLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::FillLayer > () const inline
Definition at line 10833 of file ArmnnSchema_generated.h.
{
   return layer_as_FillLayer();
 }
AnyLayer::layer_as< armnnSerializer::FloorLayer >()
const armnnSerializer::FloorLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::FloorLayer > () const inline
Definition at line 10697 of file ArmnnSchema_generated.h.
{
   return layer_as_FloorLayer();
 }
AnyLayer::layer_as< armnnSerializer::FullyConnectedLayer >()
const armnnSerializer::FullyConnectedLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::FullyConnectedLayer > () const inline
Definition at line 10633 of file ArmnnSchema_generated.h.
{
   return layer_as_FullyConnectedLayer();
 }
AnyLayer::layer_as< armnnSerializer::GatherLayer >()
const armnnSerializer::GatherLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::GatherLayer > () const inline
Definition at line 10717 of file ArmnnSchema_generated.h.
{
   return layer_as_GatherLayer();
 }
AnyLayer::layer_as< armnnSerializer::GatherNdLayer >()
const armnnSerializer::GatherNdLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::GatherNdLayer > () const inline
Definition at line 10873 of file ArmnnSchema_generated.h.
{
   return layer_as_GatherNdLayer();
 }
AnyLayer::layer_as< armnnSerializer::GreaterLayer >()
const armnnSerializer::GreaterLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::GreaterLayer > () const inline
Definition at line 10701 of file ArmnnSchema_generated.h.
{
   return layer_as_GreaterLayer();
 }
AnyLayer::layer_as< armnnSerializer::InputLayer >()
const armnnSerializer::InputLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::InputLayer > () const inline
Definition at line 10637 of file ArmnnSchema_generated.h.
{
   return layer_as_InputLayer();
 }
AnyLayer::layer_as< armnnSerializer::InstanceNormalizationLayer >()
const armnnSerializer::InstanceNormalizationLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::InstanceNormalizationLayer > () const inline
Definition at line 10805 of file ArmnnSchema_generated.h.
{
   return layer_as_InstanceNormalizationLayer();
 }
AnyLayer::layer_as< armnnSerializer::L2NormalizationLayer >()
const armnnSerializer::L2NormalizationLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::L2NormalizationLayer > () const inline
Definition at line 10729 of file ArmnnSchema_generated.h.
{
   return layer_as_L2NormalizationLayer();
 }
AnyLayer::layer_as< armnnSerializer::LogicalBinaryLayer >()
const armnnSerializer::LogicalBinaryLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::LogicalBinaryLayer > () const inline
Definition at line 10841 of file ArmnnSchema_generated.h.
{
   return layer_as_LogicalBinaryLayer();
 }
AnyLayer::layer_as< armnnSerializer::LogSoftmaxLayer >()
const armnnSerializer::LogSoftmaxLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::LogSoftmaxLayer > () const inline
Definition at line 10809 of file ArmnnSchema_generated.h.
{
   return layer_as_LogSoftmaxLayer();
 }
AnyLayer::layer_as< armnnSerializer::LstmLayer >()
const armnnSerializer::LstmLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::LstmLayer > () const inline
Definition at line 10741 of file ArmnnSchema_generated.h.
{
   return layer_as_LstmLayer();
 }
AnyLayer::layer_as< armnnSerializer::MaximumLayer >()
const armnnSerializer::MaximumLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::MaximumLayer > () const inline
Definition at line 10681 of file ArmnnSchema_generated.h.
{
   return layer_as_MaximumLayer();
 }
AnyLayer::layer_as< armnnSerializer::MeanLayer >()
const armnnSerializer::MeanLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::MeanLayer > () const inline
Definition at line 10721 of file ArmnnSchema_generated.h.
{
   return layer_as_MeanLayer();
 }
AnyLayer::layer_as< armnnSerializer::MergeLayer >()
const armnnSerializer::MergeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::MergeLayer > () const inline
Definition at line 10757 of file ArmnnSchema_generated.h.
{
   return layer_as_MergeLayer();
 }
AnyLayer::layer_as< armnnSerializer::MergerLayer >()
const armnnSerializer::MergerLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::MergerLayer > () const inline
Definition at line 10725 of file ArmnnSchema_generated.h.
{
   return layer_as_MergerLayer();
 }
AnyLayer::layer_as< armnnSerializer::MinimumLayer >()
const armnnSerializer::MinimumLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::MinimumLayer > () const inline
Definition at line 10673 of file ArmnnSchema_generated.h.
{
   return layer_as_MinimumLayer();
 }
AnyLayer::layer_as< armnnSerializer::MultiplicationLayer >()
const armnnSerializer::MultiplicationLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::MultiplicationLayer > () const inline
Definition at line 10641 of file ArmnnSchema_generated.h.
{
   return layer_as_MultiplicationLayer();
 }
AnyLayer::layer_as< armnnSerializer::NormalizationLayer >()
const armnnSerializer::NormalizationLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::NormalizationLayer > () const inline
Definition at line 10685 of file ArmnnSchema_generated.h.
{
   return layer_as_NormalizationLayer();
 }
AnyLayer::layer_as< armnnSerializer::OutputLayer >()
const armnnSerializer::OutputLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::OutputLayer > () const inline
Definition at line 10645 of file ArmnnSchema_generated.h.
{
   return layer_as_OutputLayer();
 }
AnyLayer::layer_as< armnnSerializer::PadLayer >()
const armnnSerializer::PadLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::PadLayer > () const inline
Definition at line 10689 of file ArmnnSchema_generated.h.
{
   return layer_as_PadLayer();
 }
AnyLayer::layer_as< armnnSerializer::PermuteLayer >()
const armnnSerializer::PermuteLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::PermuteLayer > () const inline
Definition at line 10649 of file ArmnnSchema_generated.h.
{
   return layer_as_PermuteLayer();
 }
AnyLayer::layer_as< armnnSerializer::Pooling2dLayer >()
const armnnSerializer::Pooling2dLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::Pooling2dLayer > () const inline
Definition at line 10653 of file ArmnnSchema_generated.h.
{
   return layer_as_Pooling2dLayer();
 }
AnyLayer::layer_as< armnnSerializer::Pooling3dLayer >()
const armnnSerializer::Pooling3dLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::Pooling3dLayer > () const inline
Definition at line 10869 of file ArmnnSchema_generated.h.
{
   return layer_as_Pooling3dLayer();
 }
AnyLayer::layer_as< armnnSerializer::PreluLayer >()
const armnnSerializer::PreluLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::PreluLayer > () const inline
Definition at line 10773 of file ArmnnSchema_generated.h.
{
   return layer_as_PreluLayer();
 }
AnyLayer::layer_as< armnnSerializer::QLstmLayer >()
const armnnSerializer::QLstmLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::QLstmLayer > () const inline
Definition at line 10829 of file ArmnnSchema_generated.h.
{
   return layer_as_QLstmLayer();
 }
AnyLayer::layer_as< armnnSerializer::QuantizedLstmLayer >()
const armnnSerializer::QuantizedLstmLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::QuantizedLstmLayer > () const inline
Definition at line 10745 of file ArmnnSchema_generated.h.
{
   return layer_as_QuantizedLstmLayer();
 }
AnyLayer::layer_as< armnnSerializer::QuantizeLayer >()
const armnnSerializer::QuantizeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::QuantizeLayer > () const inline
Definition at line 10749 of file ArmnnSchema_generated.h.
{
   return layer_as_QuantizeLayer();
 }
AnyLayer::layer_as< armnnSerializer::RankLayer >()
const armnnSerializer::RankLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::RankLayer > () const inline
Definition at line 10837 of file ArmnnSchema_generated.h.
{
   return layer_as_RankLayer();
 }
AnyLayer::layer_as< armnnSerializer::ReduceLayer >()
const armnnSerializer::ReduceLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ReduceLayer > () const inline
Definition at line 10845 of file ArmnnSchema_generated.h.
{
   return layer_as_ReduceLayer();
 }
AnyLayer::layer_as< armnnSerializer::ReshapeLayer >()
const armnnSerializer::ReshapeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ReshapeLayer > () const inline
Definition at line 10657 of file ArmnnSchema_generated.h.
{
   return layer_as_ReshapeLayer();
 }
AnyLayer::layer_as< armnnSerializer::ResizeBilinearLayer >()
const armnnSerializer::ResizeBilinearLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ResizeBilinearLayer > () const inline
Definition at line 10705 of file ArmnnSchema_generated.h.
{
   return layer_as_ResizeBilinearLayer();
 }
AnyLayer::layer_as< armnnSerializer::ResizeLayer >()
const armnnSerializer::ResizeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ResizeLayer > () const inline
Definition at line 10781 of file ArmnnSchema_generated.h.
{
   return layer_as_ResizeLayer();
 }
AnyLayer::layer_as< armnnSerializer::RsqrtLayer >()
const armnnSerializer::RsqrtLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::RsqrtLayer > () const inline
Definition at line 10693 of file ArmnnSchema_generated.h.
{
   return layer_as_RsqrtLayer();
 }
AnyLayer::layer_as< armnnSerializer::ShapeLayer >()
const armnnSerializer::ShapeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::ShapeLayer > () const inline
Definition at line 10853 of file ArmnnSchema_generated.h.
{
   return layer_as_ShapeLayer();
 }
AnyLayer::layer_as< armnnSerializer::SliceLayer >()
const armnnSerializer::SliceLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SliceLayer > () const inline
Definition at line 10797 of file ArmnnSchema_generated.h.
{
   return layer_as_SliceLayer();
 }
AnyLayer::layer_as< armnnSerializer::SoftmaxLayer >()
const armnnSerializer::SoftmaxLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SoftmaxLayer > () const inline
Definition at line 10661 of file ArmnnSchema_generated.h.
{
   return layer_as_SoftmaxLayer();
 }
AnyLayer::layer_as< armnnSerializer::SpaceToBatchNdLayer >()
const armnnSerializer::SpaceToBatchNdLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SpaceToBatchNdLayer > () const inline
Definition at line 10665 of file ArmnnSchema_generated.h.
{
   return layer_as_SpaceToBatchNdLayer();
 }
AnyLayer::layer_as< armnnSerializer::SpaceToDepthLayer >()
const armnnSerializer::SpaceToDepthLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SpaceToDepthLayer > () const inline
Definition at line 10769 of file ArmnnSchema_generated.h.
{
   return layer_as_SpaceToDepthLayer();
 }
AnyLayer::layer_as< armnnSerializer::SplitterLayer >()
const armnnSerializer::SplitterLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SplitterLayer > () const inline
Definition at line 10733 of file ArmnnSchema_generated.h.
{
   return layer_as_SplitterLayer();
 }
AnyLayer::layer_as< armnnSerializer::StackLayer >()
const armnnSerializer::StackLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::StackLayer > () const inline
Definition at line 10785 of file ArmnnSchema_generated.h.
{
   return layer_as_StackLayer();
 }
AnyLayer::layer_as< armnnSerializer::StandInLayer >()
const armnnSerializer::StandInLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::StandInLayer > () const inline
Definition at line 10817 of file ArmnnSchema_generated.h.
{
   return layer_as_StandInLayer();
 }
AnyLayer::layer_as< armnnSerializer::StridedSliceLayer >()
const armnnSerializer::StridedSliceLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::StridedSliceLayer > () const inline
Definition at line 10713 of file ArmnnSchema_generated.h.
{
   return layer_as_StridedSliceLayer();
 }
AnyLayer::layer_as< armnnSerializer::SubtractionLayer >()
const armnnSerializer::SubtractionLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SubtractionLayer > () const inline
Definition at line 10709 of file ArmnnSchema_generated.h.
{
   return layer_as_SubtractionLayer();
 }
AnyLayer::layer_as< armnnSerializer::SwitchLayer >()
const armnnSerializer::SwitchLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::SwitchLayer > () const inline
Definition at line 10761 of file ArmnnSchema_generated.h.
{
   return layer_as_SwitchLayer();
 }
AnyLayer::layer_as< armnnSerializer::TransposeConvolution2dLayer >()
const armnnSerializer::TransposeConvolution2dLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::TransposeConvolution2dLayer > () const inline
Definition at line 10777 of file ArmnnSchema_generated.h.
{
   return layer_as_TransposeConvolution2dLayer();
 }
AnyLayer::layer_as< armnnSerializer::TransposeLayer >()
const armnnSerializer::TransposeLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::TransposeLayer > () const inline
Definition at line 10825 of file ArmnnSchema_generated.h.
{
   return layer_as_TransposeLayer();
 }
AnyLayer::layer_as< armnnSerializer::UnidirectionalSequenceLstmLayer >()
const armnnSerializer::UnidirectionalSequenceLstmLayer* armnnSerializer::AnyLayer::layer_as< armnnSerializer::UnidirectionalSequenceLstmLayer > () const inline
Definition at line 10857 of file ArmnnSchema_generated.h.
{
   return layer_as_UnidirectionalSequenceLstmLayer();
 }
ConstTensor::data_as< armnnSerializer::ByteData >()
const armnnSerializer::ByteData* armnnSerializer::ConstTensor::data_as< armnnSerializer::ByteData > () const inline
Definition at line 2181 of file ArmnnSchema_generated.h.
{
   return data_as_ByteData();
 }
ConstTensor::data_as< armnnSerializer::IntData >()
const armnnSerializer::IntData* armnnSerializer::ConstTensor::data_as< armnnSerializer::IntData > () const inline
Definition at line 2189 of file ArmnnSchema_generated.h.
{
   return data_as_IntData();
 }
ConstTensor::data_as< armnnSerializer::LongData >()
const armnnSerializer::LongData* armnnSerializer::ConstTensor::data_as< armnnSerializer::LongData > () const inline
Definition at line 2193 of file ArmnnSchema_generated.h.
{
   return data_as_LongData();
 }
ConstTensor::data_as< armnnSerializer::ShortData >()
const armnnSerializer::ShortData* armnnSerializer::ConstTensor::data_as< armnnSerializer::ShortData > () const inline
Definition at line 2185 of file ArmnnSchema_generated.h.
{
   return data_as_ShortData();
 }
CreateAbsLayer()
flatbuffers::Offset<AbsLayer> armnnSerializer::CreateAbsLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 2534 of file ArmnnSchema_generated.h.
References AbsLayerBuilder::add_base(), and AbsLayerBuilder::Finish().
{
   AbsLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateActivationDescriptor()
flatbuffers::Offset<ActivationDescriptor> armnnSerializer::CreateActivationDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::ActivationFunction activationFunction = armnnSerializer::ActivationFunction_Sigmoid, float a = 0.0f, float b = 0.0f) inline
Definition at line 2646 of file ArmnnSchema_generated.h.
References ActivationDescriptorBuilder::add_a(), ActivationDescriptorBuilder::add_activationFunction(), ActivationDescriptorBuilder::add_b(), and ActivationDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
                     {
   ActivationDescriptorBuilder builder_(_fbb);
   builder_.add_b(b);
   builder_.add_a(a);
   builder_.add_activationFunction(activationFunction);
   return builder_.Finish();
 }
CreateActivationLayer()
flatbuffers::Offset<ActivationLayer> armnnSerializer::CreateActivationLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ActivationDescriptor > descriptor = 0) inline
Definition at line 2586 of file ArmnnSchema_generated.h.
References ActivationLayerBuilder::add_base(), ActivationLayerBuilder::add_descriptor(), and ActivationLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ActivationLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateAdditionLayer()
flatbuffers::Offset<AdditionLayer> armnnSerializer::CreateAdditionLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 2693 of file ArmnnSchema_generated.h.
References AdditionLayerBuilder::add_base(), and AdditionLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   AdditionLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateAnyLayer()
flatbuffers::Offset<AnyLayer> armnnSerializer::CreateAnyLayer (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::Layer layer_type = armnnSerializer::Layer_NONE, flatbuffers::Offset< void > layer = 0) inline
Definition at line 10899 of file ArmnnSchema_generated.h.
References AnyLayerBuilder::add_layer(), AnyLayerBuilder::add_layer_type(), and AnyLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   AnyLayerBuilder builder_(_fbb);
   builder_.add_layer(layer);
   builder_.add_layer_type(layer_type);
   return builder_.Finish();
 }
CreateArgMinMaxDescriptor()
flatbuffers::Offset<ArgMinMaxDescriptor> armnnSerializer::CreateArgMinMaxDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::ArgMinMaxFunction argMinMaxFunction = armnnSerializer::ArgMinMaxFunction_Min, int32_t axis = 0) inline
Definition at line 2797 of file ArmnnSchema_generated.h.
References ArgMinMaxDescriptorBuilder::add_argMinMaxFunction(), ArgMinMaxDescriptorBuilder::add_axis(), and ArgMinMaxDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
                       {
   ArgMinMaxDescriptorBuilder builder_(_fbb);
   builder_.add_axis(axis);
   builder_.add_argMinMaxFunction(argMinMaxFunction);
   return builder_.Finish();
 }
CreateArgMinMaxLayer()
flatbuffers::Offset<ArgMinMaxLayer> armnnSerializer::CreateArgMinMaxLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ArgMinMaxDescriptor > descriptor = 0) inline
Definition at line 2745 of file ArmnnSchema_generated.h.
References ArgMinMaxLayerBuilder::add_base(), ArgMinMaxLayerBuilder::add_descriptor(), and ArgMinMaxLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ArgMinMaxLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateBatchNormalizationDescriptor()
flatbuffers::Offset<BatchNormalizationDescriptor> armnnSerializer::CreateBatchNormalizationDescriptor (flatbuffers::FlatBufferBuilder & _fbb, float eps = 0.0f, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 7003 of file ArmnnSchema_generated.h.
References BatchNormalizationDescriptorBuilder::add_dataLayout(), BatchNormalizationDescriptorBuilder::add_eps(), and BatchNormalizationDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   BatchNormalizationDescriptorBuilder builder_(_fbb);
   builder_.add_eps(eps);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateBatchNormalizationLayer()
flatbuffers::Offset<BatchNormalizationLayer> armnnSerializer::CreateBatchNormalizationLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::BatchNormalizationDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > mean = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > variance = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > beta = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > gamma = 0) inline
Definition at line 6943 of file ArmnnSchema_generated.h.
References BatchNormalizationLayerBuilder::add_base(), BatchNormalizationLayerBuilder::add_beta(), BatchNormalizationLayerBuilder::add_descriptor(), BatchNormalizationLayerBuilder::add_gamma(), BatchNormalizationLayerBuilder::add_mean(), BatchNormalizationLayerBuilder::add_variance(), and BatchNormalizationLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   BatchNormalizationLayerBuilder builder_(_fbb);
   builder_.add_gamma(gamma);
   builder_.add_beta(beta);
   builder_.add_variance(variance);
   builder_.add_mean(mean);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateBatchToSpaceNdDescriptor()
flatbuffers::Offset<BatchToSpaceNdDescriptor> armnnSerializer::CreateBatchToSpaceNdDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape = 0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> crops = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 6389 of file ArmnnSchema_generated.h.
References BatchToSpaceNdDescriptorBuilder::add_blockShape(), BatchToSpaceNdDescriptorBuilder::add_crops(), BatchToSpaceNdDescriptorBuilder::add_dataLayout(), and BatchToSpaceNdDescriptorBuilder::Finish().
Referenced by CreateBatchToSpaceNdDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   BatchToSpaceNdDescriptorBuilder builder_(_fbb);
   builder_.add_crops(crops);
   builder_.add_blockShape(blockShape);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateBatchToSpaceNdDescriptorDirect()
flatbuffers::Offset<BatchToSpaceNdDescriptor> armnnSerializer::CreateBatchToSpaceNdDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * blockShape = nullptr, const std::vector< uint32_t > * crops = nullptr, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 6401 of file ArmnnSchema_generated.h.
References CreateBatchToSpaceNdDescriptor().
{
   auto blockShape__ = blockShape ? _fbb.CreateVector<uint32_t>(*blockShape) : 0;
   auto crops__ = crops ? _fbb.CreateVector<uint32_t>(*crops) : 0;
   return armnnSerializer::CreateBatchToSpaceNdDescriptor(
       _fbb,
       blockShape__,
       crops__,
       dataLayout);
 }
CreateBatchToSpaceNdLayer()
flatbuffers::Offset<BatchToSpaceNdLayer> armnnSerializer::CreateBatchToSpaceNdLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::BatchToSpaceNdDescriptor > descriptor = 0) inline
Definition at line 6327 of file ArmnnSchema_generated.h.
References BatchToSpaceNdLayerBuilder::add_base(), BatchToSpaceNdLayerBuilder::add_descriptor(), and BatchToSpaceNdLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   BatchToSpaceNdLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateBindableLayerBase()
flatbuffers::Offset<BindableLayerBase> armnnSerializer::CreateBindableLayerBase (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, int32_t layerBindingId = 0) inline
Definition at line 2488 of file ArmnnSchema_generated.h.
References BindableLayerBaseBuilder::add_base(), BindableLayerBaseBuilder::add_layerBindingId(), and BindableLayerBaseBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   BindableLayerBaseBuilder builder_(_fbb);
   builder_.add_layerBindingId(layerBindingId);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateByteData()
flatbuffers::Offset<ByteData> armnnSerializer::CreateByteData (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< int8_t >> data = 0) inline
Definition at line 1968 of file ArmnnSchema_generated.h.
References ByteDataBuilder::add_data(), and ByteDataBuilder::Finish().
Referenced by CreateByteDataDirect(), and GetFlatBufferArgMinMaxFunction().
{
   ByteDataBuilder builder_(_fbb);
   builder_.add_data(data);
   return builder_.Finish();
 }
CreateByteDataDirect()
flatbuffers::Offset<ByteData> armnnSerializer::CreateByteDataDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< int8_t > * data = nullptr) inline
Definition at line 1976 of file ArmnnSchema_generated.h.
References CreateByteData().
{
   auto data__ = data ? _fbb.CreateVector<int8_t>(*data) : 0;
   return armnnSerializer::CreateByteData(
       _fbb,
       data__);
 }
CreateCastLayer()
flatbuffers::Offset<CastLayer> armnnSerializer::CreateCastLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 2842 of file ArmnnSchema_generated.h.
References CastLayerBuilder::add_base(), and CastLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   CastLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateChannelShuffleDescriptor()
flatbuffers::Offset<ChannelShuffleDescriptor> armnnSerializer::CreateChannelShuffleDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t axis = 0, uint32_t numGroups = 0) inline
Definition at line 2946 of file ArmnnSchema_generated.h.
References ChannelShuffleDescriptorBuilder::add_axis(), ChannelShuffleDescriptorBuilder::add_numGroups(), and ChannelShuffleDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ChannelShuffleDescriptorBuilder builder_(_fbb);
   builder_.add_numGroups(numGroups);
   builder_.add_axis(axis);
   return builder_.Finish();
 }
CreateChannelShuffleLayer()
flatbuffers::Offset<ChannelShuffleLayer> armnnSerializer::CreateChannelShuffleLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ChannelShuffleDescriptor > descriptor = 0) inline
Definition at line 2894 of file ArmnnSchema_generated.h.
References ChannelShuffleLayerBuilder::add_base(), ChannelShuffleLayerBuilder::add_descriptor(), and ChannelShuffleLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ChannelShuffleLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateComparisonDescriptor()
flatbuffers::Offset<ComparisonDescriptor> armnnSerializer::CreateComparisonDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::ComparisonOperation operation = armnnSerializer::ComparisonOperation_Equal) inline
Definition at line 2990 of file ArmnnSchema_generated.h.
References ComparisonDescriptorBuilder::add_operation(), and ComparisonDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ComparisonDescriptorBuilder builder_(_fbb);
   builder_.add_operation(operation);
   return builder_.Finish();
 }
CreateComparisonLayer()
flatbuffers::Offset<ComparisonLayer> armnnSerializer::CreateComparisonLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ComparisonDescriptor > descriptor = 0) inline
Definition at line 3042 of file ArmnnSchema_generated.h.
References ComparisonLayerBuilder::add_base(), ComparisonLayerBuilder::add_descriptor(), and ComparisonLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ComparisonLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateConcatLayer()
flatbuffers::Offset<ConcatLayer> armnnSerializer::CreateConcatLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > descriptor = 0) inline
Definition at line 7520 of file ArmnnSchema_generated.h.
References ConcatLayerBuilder::add_base(), ConcatLayerBuilder::add_descriptor(), and ConcatLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ConcatLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateConstantLayer()
flatbuffers::Offset<ConstantLayer> armnnSerializer::CreateConstantLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > input = 0) inline
Definition at line 3096 of file ArmnnSchema_generated.h.
References ConstantLayerBuilder::add_base(), ConstantLayerBuilder::add_input(), and ConstantLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ConstantLayerBuilder builder_(_fbb);
   builder_.add_input(input);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateConstTensor()
flatbuffers::Offset<ConstTensor> armnnSerializer::CreateConstTensor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::TensorInfo > info = 0, armnnSerializer::ConstTensorData data_type = armnnSerializer::ConstTensorData_NONE, flatbuffers::Offset< void > data = 0) inline
Definition at line 2222 of file ArmnnSchema_generated.h.
References ConstTensorBuilder::add_data(), ConstTensorBuilder::add_data_type(), ConstTensorBuilder::add_info(), and ConstTensorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ConstTensorBuilder builder_(_fbb);
   builder_.add_data(data);
   builder_.add_info(info);
   builder_.add_data_type(data_type);
   return builder_.Finish();
 }
CreateConvolution2dDescriptor()
flatbuffers::Offset<Convolution2dDescriptor> armnnSerializer::CreateConvolution2dDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t padLeft = 0, uint32_t padRight = 0, uint32_t padTop = 0, uint32_t padBottom = 0, uint32_t strideX = 0, uint32_t strideY = 0, uint32_t dilationX = 1, uint32_t dilationY = 1, bool biasEnabled = false, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NCHW) inline
Definition at line 3288 of file ArmnnSchema_generated.h.
References Convolution2dDescriptorBuilder::add_biasEnabled(), Convolution2dDescriptorBuilder::add_dataLayout(), Convolution2dDescriptorBuilder::add_dilationX(), Convolution2dDescriptorBuilder::add_dilationY(), Convolution2dDescriptorBuilder::add_padBottom(), Convolution2dDescriptorBuilder::add_padLeft(), Convolution2dDescriptorBuilder::add_padRight(), Convolution2dDescriptorBuilder::add_padTop(), Convolution2dDescriptorBuilder::add_strideX(), Convolution2dDescriptorBuilder::add_strideY(), and Convolution2dDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Convolution2dDescriptorBuilder builder_(_fbb);
   builder_.add_dilationY(dilationY);
   builder_.add_dilationX(dilationX);
   builder_.add_strideY(strideY);
   builder_.add_strideX(strideX);
   builder_.add_padBottom(padBottom);
   builder_.add_padTop(padTop);
   builder_.add_padRight(padRight);
   builder_.add_padLeft(padLeft);
   builder_.add_dataLayout(dataLayout);
   builder_.add_biasEnabled(biasEnabled);
   return builder_.Finish();
 }
CreateConvolution2dLayer()
flatbuffers::Offset<Convolution2dLayer> armnnSerializer::CreateConvolution2dLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::Convolution2dDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases = 0) inline
Definition at line 3168 of file ArmnnSchema_generated.h.
References Convolution2dLayerBuilder::add_base(), Convolution2dLayerBuilder::add_biases(), Convolution2dLayerBuilder::add_descriptor(), Convolution2dLayerBuilder::add_weights(), and Convolution2dLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Convolution2dLayerBuilder builder_(_fbb);
   builder_.add_biases(biases);
   builder_.add_weights(weights);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateConvolution3dDescriptor()
flatbuffers::Offset<Convolution3dDescriptor> armnnSerializer::CreateConvolution3dDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t padLeft = 0, uint32_t padRight = 0, uint32_t padTop = 0, uint32_t padBottom = 0, uint32_t padFront = 0, uint32_t padBack = 0, uint32_t strideX = 0, uint32_t strideY = 0, uint32_t strideZ = 0, uint32_t dilationX = 1, uint32_t dilationY = 1, uint32_t dilationZ = 1, bool biasEnabled = false, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NDHWC) inline
Definition at line 3506 of file ArmnnSchema_generated.h.
References Convolution3dDescriptorBuilder::add_biasEnabled(), Convolution3dDescriptorBuilder::add_dataLayout(), Convolution3dDescriptorBuilder::add_dilationX(), Convolution3dDescriptorBuilder::add_dilationY(), Convolution3dDescriptorBuilder::add_dilationZ(), Convolution3dDescriptorBuilder::add_padBack(), Convolution3dDescriptorBuilder::add_padBottom(), Convolution3dDescriptorBuilder::add_padFront(), Convolution3dDescriptorBuilder::add_padLeft(), Convolution3dDescriptorBuilder::add_padRight(), Convolution3dDescriptorBuilder::add_padTop(), Convolution3dDescriptorBuilder::add_strideX(), Convolution3dDescriptorBuilder::add_strideY(), Convolution3dDescriptorBuilder::add_strideZ(), and Convolution3dDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Convolution3dDescriptorBuilder builder_(_fbb);
   builder_.add_dilationZ(dilationZ);
   builder_.add_dilationY(dilationY);
   builder_.add_dilationX(dilationX);
   builder_.add_strideZ(strideZ);
   builder_.add_strideY(strideY);
   builder_.add_strideX(strideX);
   builder_.add_padBack(padBack);
   builder_.add_padFront(padFront);
   builder_.add_padBottom(padBottom);
   builder_.add_padTop(padTop);
   builder_.add_padRight(padRight);
   builder_.add_padLeft(padLeft);
   builder_.add_dataLayout(dataLayout);
   builder_.add_biasEnabled(biasEnabled);
   return builder_.Finish();
 }
CreateConvolution3dLayer()
flatbuffers::Offset<Convolution3dLayer> armnnSerializer::CreateConvolution3dLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::Convolution3dDescriptor > descriptor = 0) inline
Definition at line 3358 of file ArmnnSchema_generated.h.
References Convolution3dLayerBuilder::add_base(), Convolution3dLayerBuilder::add_descriptor(), and Convolution3dLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Convolution3dLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateDepthToSpaceDescriptor()
flatbuffers::Offset<DepthToSpaceDescriptor> armnnSerializer::CreateDepthToSpaceDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t blockSize = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 3636 of file ArmnnSchema_generated.h.
References DepthToSpaceDescriptorBuilder::add_blockSize(), DepthToSpaceDescriptorBuilder::add_dataLayout(), and DepthToSpaceDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DepthToSpaceDescriptorBuilder builder_(_fbb);
   builder_.add_blockSize(blockSize);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateDepthToSpaceLayer()
flatbuffers::Offset<DepthToSpaceLayer> armnnSerializer::CreateDepthToSpaceLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::DepthToSpaceDescriptor > descriptor = 0) inline
Definition at line 3584 of file ArmnnSchema_generated.h.
References DepthToSpaceLayerBuilder::add_base(), DepthToSpaceLayerBuilder::add_descriptor(), and DepthToSpaceLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DepthToSpaceLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateDepthwiseConvolution2dDescriptor()
flatbuffers::Offset<DepthwiseConvolution2dDescriptor> armnnSerializer::CreateDepthwiseConvolution2dDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t padLeft = 0, uint32_t padRight = 0, uint32_t padTop = 0, uint32_t padBottom = 0, uint32_t strideX = 0, uint32_t strideY = 0, uint32_t dilationX = 1, uint32_t dilationY = 1, bool biasEnabled = false, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NCHW) inline
Definition at line 5678 of file ArmnnSchema_generated.h.
References DepthwiseConvolution2dDescriptorBuilder::add_biasEnabled(), DepthwiseConvolution2dDescriptorBuilder::add_dataLayout(), DepthwiseConvolution2dDescriptorBuilder::add_dilationX(), DepthwiseConvolution2dDescriptorBuilder::add_dilationY(), DepthwiseConvolution2dDescriptorBuilder::add_padBottom(), DepthwiseConvolution2dDescriptorBuilder::add_padLeft(), DepthwiseConvolution2dDescriptorBuilder::add_padRight(), DepthwiseConvolution2dDescriptorBuilder::add_padTop(), DepthwiseConvolution2dDescriptorBuilder::add_strideX(), DepthwiseConvolution2dDescriptorBuilder::add_strideY(), and DepthwiseConvolution2dDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DepthwiseConvolution2dDescriptorBuilder builder_(_fbb);
   builder_.add_dilationY(dilationY);
   builder_.add_dilationX(dilationX);
   builder_.add_strideY(strideY);
   builder_.add_strideX(strideX);
   builder_.add_padBottom(padBottom);
   builder_.add_padTop(padTop);
   builder_.add_padRight(padRight);
   builder_.add_padLeft(padLeft);
   builder_.add_dataLayout(dataLayout);
   builder_.add_biasEnabled(biasEnabled);
   return builder_.Finish();
 }
CreateDepthwiseConvolution2dLayer()
flatbuffers::Offset<DepthwiseConvolution2dLayer> armnnSerializer::CreateDepthwiseConvolution2dLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::DepthwiseConvolution2dDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases = 0) inline
Definition at line 5558 of file ArmnnSchema_generated.h.
References DepthwiseConvolution2dLayerBuilder::add_base(), DepthwiseConvolution2dLayerBuilder::add_biases(), DepthwiseConvolution2dLayerBuilder::add_descriptor(), DepthwiseConvolution2dLayerBuilder::add_weights(), and DepthwiseConvolution2dLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DepthwiseConvolution2dLayerBuilder builder_(_fbb);
   builder_.add_biases(biases);
   builder_.add_weights(weights);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateDequantizeLayer()
flatbuffers::Offset<DequantizeLayer> armnnSerializer::CreateDequantizeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 9216 of file ArmnnSchema_generated.h.
References DequantizeLayerBuilder::add_base(), and DequantizeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DequantizeLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateDetectionPostProcessDescriptor()
flatbuffers::Offset<DetectionPostProcessDescriptor> armnnSerializer::CreateDetectionPostProcessDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t maxDetections = 0, uint32_t maxClassesPerDetection = 0, uint32_t detectionsPerClass = 0, float nmsScoreThreshold = 0.0f, float nmsIouThreshold = 0.0f, uint32_t numClasses = 0, bool useRegularNms = false, float scaleX = 0.0f, float scaleY = 0.0f, float scaleW = 0.0f, float scaleH = 0.0f) inline
Definition at line 8025 of file ArmnnSchema_generated.h.
References DetectionPostProcessDescriptorBuilder::add_detectionsPerClass(), DetectionPostProcessDescriptorBuilder::add_maxClassesPerDetection(), DetectionPostProcessDescriptorBuilder::add_maxDetections(), DetectionPostProcessDescriptorBuilder::add_nmsIouThreshold(), DetectionPostProcessDescriptorBuilder::add_nmsScoreThreshold(), DetectionPostProcessDescriptorBuilder::add_numClasses(), DetectionPostProcessDescriptorBuilder::add_scaleH(), DetectionPostProcessDescriptorBuilder::add_scaleW(), DetectionPostProcessDescriptorBuilder::add_scaleX(), DetectionPostProcessDescriptorBuilder::add_scaleY(), DetectionPostProcessDescriptorBuilder::add_useRegularNms(), and DetectionPostProcessDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DetectionPostProcessDescriptorBuilder builder_(_fbb);
   builder_.add_scaleH(scaleH);
   builder_.add_scaleW(scaleW);
   builder_.add_scaleY(scaleY);
   builder_.add_scaleX(scaleX);
   builder_.add_numClasses(numClasses);
   builder_.add_nmsIouThreshold(nmsIouThreshold);
   builder_.add_nmsScoreThreshold(nmsScoreThreshold);
   builder_.add_detectionsPerClass(detectionsPerClass);
   builder_.add_maxClassesPerDetection(maxClassesPerDetection);
   builder_.add_maxDetections(maxDetections);
   builder_.add_useRegularNms(useRegularNms);
   return builder_.Finish();
 }
CreateDetectionPostProcessLayer()
flatbuffers::Offset<DetectionPostProcessLayer> armnnSerializer::CreateDetectionPostProcessLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::DetectionPostProcessDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > anchors = 0) inline
Definition at line 7899 of file ArmnnSchema_generated.h.
References DetectionPostProcessLayerBuilder::add_anchors(), DetectionPostProcessLayerBuilder::add_base(), DetectionPostProcessLayerBuilder::add_descriptor(), and DetectionPostProcessLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DetectionPostProcessLayerBuilder builder_(_fbb);
   builder_.add_anchors(anchors);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateDivisionLayer()
flatbuffers::Offset<DivisionLayer> armnnSerializer::CreateDivisionLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 3681 of file ArmnnSchema_generated.h.
References DivisionLayerBuilder::add_base(), and DivisionLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   DivisionLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateElementwiseUnaryDescriptor()
flatbuffers::Offset<ElementwiseUnaryDescriptor> armnnSerializer::CreateElementwiseUnaryDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::UnaryOperation operation = armnnSerializer::UnaryOperation_Abs) inline
Definition at line 3723 of file ArmnnSchema_generated.h.
References ElementwiseUnaryDescriptorBuilder::add_operation(), and ElementwiseUnaryDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ElementwiseUnaryDescriptorBuilder builder_(_fbb);
   builder_.add_operation(operation);
   return builder_.Finish();
 }
CreateElementwiseUnaryLayer()
flatbuffers::Offset<ElementwiseUnaryLayer> armnnSerializer::CreateElementwiseUnaryLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ElementwiseUnaryDescriptor > descriptor = 0) inline
Definition at line 3775 of file ArmnnSchema_generated.h.
References ElementwiseUnaryLayerBuilder::add_base(), ElementwiseUnaryLayerBuilder::add_descriptor(), and ElementwiseUnaryLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ElementwiseUnaryLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateEqualLayer()
flatbuffers::Offset<EqualLayer> armnnSerializer::CreateEqualLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 3821 of file ArmnnSchema_generated.h.
References EqualLayerBuilder::add_base(), and EqualLayerBuilder::Finish().
{
   EqualLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateFeatureCompatibilityVersions()
flatbuffers::Offset<FeatureCompatibilityVersions> armnnSerializer::CreateFeatureCompatibilityVersions (flatbuffers::FlatBufferBuilder & _fbb, uint32_t bindingIdsScheme = 0, uint32_t weightsLayoutScheme = 0, uint32_t constantTensorsAsInputs = 0) inline
Definition at line 10959 of file ArmnnSchema_generated.h.
References FeatureCompatibilityVersionsBuilder::add_bindingIdsScheme(), FeatureCompatibilityVersionsBuilder::add_constantTensorsAsInputs(), FeatureCompatibilityVersionsBuilder::add_weightsLayoutScheme(), and FeatureCompatibilityVersionsBuilder::Finish().
Referenced by SerializerStrategy::GetVersionTable().
{
   FeatureCompatibilityVersionsBuilder builder_(_fbb);
   builder_.add_constantTensorsAsInputs(constantTensorsAsInputs);
   builder_.add_weightsLayoutScheme(weightsLayoutScheme);
   builder_.add_bindingIdsScheme(bindingIdsScheme);
   return builder_.Finish();
 }
CreateFillDescriptor()
flatbuffers::Offset<FillDescriptor> armnnSerializer::CreateFillDescriptor (flatbuffers::FlatBufferBuilder & _fbb, float value = 0.0f) inline
Definition at line 3917 of file ArmnnSchema_generated.h.
References FillDescriptorBuilder::add_value(), and FillDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   FillDescriptorBuilder builder_(_fbb);
   builder_.add_value(value);
   return builder_.Finish();
 }
CreateFillLayer()
flatbuffers::Offset<FillLayer> armnnSerializer::CreateFillLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::FillDescriptor > descriptor = 0) inline
Definition at line 3873 of file ArmnnSchema_generated.h.
References FillLayerBuilder::add_base(), FillLayerBuilder::add_descriptor(), and FillLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   FillLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateFloorLayer()
flatbuffers::Offset<FloorLayer> armnnSerializer::CreateFloorLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 3960 of file ArmnnSchema_generated.h.
References FloorLayerBuilder::add_base(), and FloorLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   FloorLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateFullyConnectedDescriptor()
flatbuffers::Offset<FullyConnectedDescriptor> armnnSerializer::CreateFullyConnectedDescriptor (flatbuffers::FlatBufferBuilder & _fbb, bool biasEnabled = false, bool transposeWeightsMatrix = false, bool constantWeights = true) inline
Definition at line 4094 of file ArmnnSchema_generated.h.
References FullyConnectedDescriptorBuilder::add_biasEnabled(), FullyConnectedDescriptorBuilder::add_constantWeights(), FullyConnectedDescriptorBuilder::add_transposeWeightsMatrix(), and FullyConnectedDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   FullyConnectedDescriptorBuilder builder_(_fbb);
   builder_.add_constantWeights(constantWeights);
   builder_.add_transposeWeightsMatrix(transposeWeightsMatrix);
   builder_.add_biasEnabled(biasEnabled);
   return builder_.Finish();
 }
CreateFullyConnectedLayer()
flatbuffers::Offset<FullyConnectedLayer> armnnSerializer::CreateFullyConnectedLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::FullyConnectedDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases = 0) inline
Definition at line 4030 of file ArmnnSchema_generated.h.
References FullyConnectedLayerBuilder::add_base(), FullyConnectedLayerBuilder::add_biases(), FullyConnectedLayerBuilder::add_descriptor(), FullyConnectedLayerBuilder::add_weights(), and FullyConnectedLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   FullyConnectedLayerBuilder builder_(_fbb);
   builder_.add_biases(biases);
   builder_.add_weights(weights);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateGatherDescriptor()
flatbuffers::Offset<GatherDescriptor> armnnSerializer::CreateGatherDescriptor (flatbuffers::FlatBufferBuilder & _fbb, int32_t axis = 0) inline
Definition at line 4194 of file ArmnnSchema_generated.h.
References GatherDescriptorBuilder::add_axis(), and GatherDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
                       {
   GatherDescriptorBuilder builder_(_fbb);
   builder_.add_axis(axis);
   return builder_.Finish();
 }
CreateGatherLayer()
flatbuffers::Offset<GatherLayer> armnnSerializer::CreateGatherLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::GatherDescriptor > descriptor = 0) inline
Definition at line 4150 of file ArmnnSchema_generated.h.
References GatherLayerBuilder::add_base(), GatherLayerBuilder::add_descriptor(), and GatherLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   GatherLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateGatherNdLayer()
flatbuffers::Offset<GatherNdLayer> armnnSerializer::CreateGatherNdLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 4237 of file ArmnnSchema_generated.h.
References GatherNdLayerBuilder::add_base(), and GatherNdLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   GatherNdLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateGreaterLayer()
flatbuffers::Offset<GreaterLayer> armnnSerializer::CreateGreaterLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 4281 of file ArmnnSchema_generated.h.
References GreaterLayerBuilder::add_base(), and GreaterLayerBuilder::Finish().
{
   GreaterLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateInputLayer()
flatbuffers::Offset<InputLayer> armnnSerializer::CreateInputLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::BindableLayerBase > base = 0) inline
Definition at line 4324 of file ArmnnSchema_generated.h.
References InputLayerBuilder::add_base(), and InputLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   InputLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateInputSlot()
flatbuffers::Offset<InputSlot> armnnSerializer::CreateInputSlot (flatbuffers::FlatBufferBuilder & _fbb, uint32_t index = 0, const armnnSerializer::Connection * connection = 0) inline
Definition at line 2276 of file ArmnnSchema_generated.h.
References InputSlotBuilder::add_connection(), InputSlotBuilder::add_index(), and InputSlotBuilder::Finish().
Referenced by SerializerStrategy::GetVersionTable().
{
   InputSlotBuilder builder_(_fbb);
   builder_.add_connection(connection);
   builder_.add_index(index);
   return builder_.Finish();
 }
CreateInstanceNormalizationDescriptor()
flatbuffers::Offset<InstanceNormalizationDescriptor> armnnSerializer::CreateInstanceNormalizationDescriptor (flatbuffers::FlatBufferBuilder & _fbb, float gamma = 0.0f, float beta = 0.0f, float eps = 0.0f, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 4444 of file ArmnnSchema_generated.h.
References InstanceNormalizationDescriptorBuilder::add_beta(), InstanceNormalizationDescriptorBuilder::add_dataLayout(), InstanceNormalizationDescriptorBuilder::add_eps(), InstanceNormalizationDescriptorBuilder::add_gamma(), and InstanceNormalizationDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   InstanceNormalizationDescriptorBuilder builder_(_fbb);
   builder_.add_eps(eps);
   builder_.add_beta(beta);
   builder_.add_gamma(gamma);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateInstanceNormalizationLayer()
flatbuffers::Offset<InstanceNormalizationLayer> armnnSerializer::CreateInstanceNormalizationLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::InstanceNormalizationDescriptor > descriptor = 0) inline
Definition at line 4376 of file ArmnnSchema_generated.h.
References InstanceNormalizationLayerBuilder::add_base(), InstanceNormalizationLayerBuilder::add_descriptor(), and InstanceNormalizationLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   InstanceNormalizationLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateIntData()
flatbuffers::Offset<IntData> armnnSerializer::CreateIntData (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< int32_t >> data = 0) inline
Definition at line 2072 of file ArmnnSchema_generated.h.
References IntDataBuilder::add_data(), and IntDataBuilder::Finish().
Referenced by CreateIntDataDirect(), and GetFlatBufferArgMinMaxFunction().
{
   IntDataBuilder builder_(_fbb);
   builder_.add_data(data);
   return builder_.Finish();
 }
CreateIntDataDirect()
flatbuffers::Offset<IntData> armnnSerializer::CreateIntDataDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< int32_t > * data = nullptr) inline
Definition at line 2080 of file ArmnnSchema_generated.h.
References CreateIntData().
{
   auto data__ = data ? _fbb.CreateVector<int32_t>(*data) : 0;
   return armnnSerializer::CreateIntData(
       _fbb,
       data__);
 }
CreateL2NormalizationDescriptor()
flatbuffers::Offset<L2NormalizationDescriptor> armnnSerializer::CreateL2NormalizationDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NCHW, float eps = 1e-12f) inline
Definition at line 4660 of file ArmnnSchema_generated.h.
References L2NormalizationDescriptorBuilder::add_dataLayout(), L2NormalizationDescriptorBuilder::add_eps(), and L2NormalizationDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   L2NormalizationDescriptorBuilder builder_(_fbb);
   builder_.add_eps(eps);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateL2NormalizationLayer()
flatbuffers::Offset<L2NormalizationLayer> armnnSerializer::CreateL2NormalizationLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::L2NormalizationDescriptor > descriptor = 0) inline
Definition at line 4608 of file ArmnnSchema_generated.h.
References L2NormalizationLayerBuilder::add_base(), L2NormalizationLayerBuilder::add_descriptor(), and L2NormalizationLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   L2NormalizationLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateLayerBase()
flatbuffers::Offset<LayerBase> armnnSerializer::CreateLayerBase (flatbuffers::FlatBufferBuilder & _fbb, uint32_t index = 0, flatbuffers::Offset< flatbuffers::String > layerName = 0, armnnSerializer::LayerType layerType = armnnSerializer::LayerType_Addition, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::InputSlot >>> inputSlots = 0, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::OutputSlot >>> outputSlots = 0) inline
Definition at line 2410 of file ArmnnSchema_generated.h.
References LayerBaseBuilder::add_index(), LayerBaseBuilder::add_inputSlots(), LayerBaseBuilder::add_layerName(), LayerBaseBuilder::add_layerType(), LayerBaseBuilder::add_outputSlots(), and LayerBaseBuilder::Finish().
Referenced by CreateLayerBaseDirect(), and GetFlatBufferArgMinMaxFunction().
{
   LayerBaseBuilder builder_(_fbb);
   builder_.add_outputSlots(outputSlots);
   builder_.add_inputSlots(inputSlots);
   builder_.add_layerType(layerType);
   builder_.add_layerName(layerName);
   builder_.add_index(index);
   return builder_.Finish();
 }
CreateLayerBaseDirect()
flatbuffers::Offset<LayerBase> armnnSerializer::CreateLayerBaseDirect (flatbuffers::FlatBufferBuilder & _fbb, uint32_t index = 0, const char * layerName = nullptr, armnnSerializer::LayerType layerType = armnnSerializer::LayerType_Addition, const std::vector< flatbuffers::Offset< armnnSerializer::InputSlot >> * inputSlots = nullptr, const std::vector< flatbuffers::Offset< armnnSerializer::OutputSlot >> * outputSlots = nullptr) inline
Definition at line 2426 of file ArmnnSchema_generated.h.
References CreateLayerBase().
{
   auto layerName__ = layerName ? _fbb.CreateString(layerName) : 0;
   auto inputSlots__ = inputSlots ? _fbb.CreateVector<flatbuffers::Offset<armnnSerializer::InputSlot>>(*inputSlots) : 0;
   auto outputSlots__ = outputSlots ? _fbb.CreateVector<flatbuffers::Offset<armnnSerializer::OutputSlot>>(*outputSlots) : 0;
   return armnnSerializer::CreateLayerBase(
       _fbb,
       index,
       layerName__,
       layerType,
       inputSlots__,
       outputSlots__);
 }
CreateLogicalBinaryDescriptor()
flatbuffers::Offset<LogicalBinaryDescriptor> armnnSerializer::CreateLogicalBinaryDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::LogicalBinaryOperation operation = armnnSerializer::LogicalBinaryOperation_LogicalAnd) inline
Definition at line 4704 of file ArmnnSchema_generated.h.
References LogicalBinaryDescriptorBuilder::add_operation(), and LogicalBinaryDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LogicalBinaryDescriptorBuilder builder_(_fbb);
   builder_.add_operation(operation);
   return builder_.Finish();
 }
CreateLogicalBinaryLayer()
flatbuffers::Offset<LogicalBinaryLayer> armnnSerializer::CreateLogicalBinaryLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::LogicalBinaryDescriptor > descriptor = 0) inline
Definition at line 4756 of file ArmnnSchema_generated.h.
References LogicalBinaryLayerBuilder::add_base(), LogicalBinaryLayerBuilder::add_descriptor(), and LogicalBinaryLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LogicalBinaryLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateLogSoftmaxDescriptor()
flatbuffers::Offset<LogSoftmaxDescriptor> armnnSerializer::CreateLogSoftmaxDescriptor (flatbuffers::FlatBufferBuilder & _fbb, float beta = 1.0f, int32_t axis = -1) inline
Definition at line 4554 of file ArmnnSchema_generated.h.
References LogSoftmaxDescriptorBuilder::add_axis(), LogSoftmaxDescriptorBuilder::add_beta(), and LogSoftmaxDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LogSoftmaxDescriptorBuilder builder_(_fbb);
   builder_.add_axis(axis);
   builder_.add_beta(beta);
   return builder_.Finish();
 }
CreateLogSoftmaxLayer()
flatbuffers::Offset<LogSoftmaxLayer> armnnSerializer::CreateLogSoftmaxLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::LogSoftmaxDescriptor > descriptor = 0) inline
Definition at line 4502 of file ArmnnSchema_generated.h.
References LogSoftmaxLayerBuilder::add_base(), LogSoftmaxLayerBuilder::add_descriptor(), and LogSoftmaxLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LogSoftmaxLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateLongData()
flatbuffers::Offset<LongData> armnnSerializer::CreateLongData (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< int64_t >> data = 0) inline
Definition at line 2124 of file ArmnnSchema_generated.h.
References LongDataBuilder::add_data(), and LongDataBuilder::Finish().
Referenced by CreateLongDataDirect(), and GetFlatBufferArgMinMaxFunction().
{
   LongDataBuilder builder_(_fbb);
   builder_.add_data(data);
   return builder_.Finish();
 }
CreateLongDataDirect()
flatbuffers::Offset<LongData> armnnSerializer::CreateLongDataDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< int64_t > * data = nullptr) inline
Definition at line 2132 of file ArmnnSchema_generated.h.
References CreateLongData().
{
   auto data__ = data ? _fbb.CreateVector<int64_t>(*data) : 0;
   return armnnSerializer::CreateLongData(
       _fbb,
       data__);
 }
CreateLstmDescriptor()
flatbuffers::Offset<LstmDescriptor> armnnSerializer::CreateLstmDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t activationFunc = 0, float clippingThresCell = 0.0f, float clippingThresProj = 0.0f, bool cifgEnabled = true, bool peepholeEnabled = false, bool projectionEnabled = false, bool layerNormEnabled = false) inline
Definition at line 8398 of file ArmnnSchema_generated.h.
References LstmDescriptorBuilder::add_activationFunc(), LstmDescriptorBuilder::add_cifgEnabled(), LstmDescriptorBuilder::add_clippingThresCell(), LstmDescriptorBuilder::add_clippingThresProj(), LstmDescriptorBuilder::add_layerNormEnabled(), LstmDescriptorBuilder::add_peepholeEnabled(), LstmDescriptorBuilder::add_projectionEnabled(), and LstmDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LstmDescriptorBuilder builder_(_fbb);
   builder_.add_clippingThresProj(clippingThresProj);
   builder_.add_clippingThresCell(clippingThresCell);
   builder_.add_activationFunc(activationFunc);
   builder_.add_layerNormEnabled(layerNormEnabled);
   builder_.add_projectionEnabled(projectionEnabled);
   builder_.add_peepholeEnabled(peepholeEnabled);
   builder_.add_cifgEnabled(cifgEnabled);
   return builder_.Finish();
 }
CreateLstmInputParams()
flatbuffers::Offset<LstmInputParams> armnnSerializer::CreateLstmInputParams (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights = 0) inline
Definition at line 8268 of file ArmnnSchema_generated.h.
References LstmInputParamsBuilder::add_cellBias(), LstmInputParamsBuilder::add_cellLayerNormWeights(), LstmInputParamsBuilder::add_cellToForgetWeights(), LstmInputParamsBuilder::add_cellToInputWeights(), LstmInputParamsBuilder::add_cellToOutputWeights(), LstmInputParamsBuilder::add_forgetGateBias(), LstmInputParamsBuilder::add_forgetLayerNormWeights(), LstmInputParamsBuilder::add_inputGateBias(), LstmInputParamsBuilder::add_inputLayerNormWeights(), LstmInputParamsBuilder::add_inputToCellWeights(), LstmInputParamsBuilder::add_inputToForgetWeights(), LstmInputParamsBuilder::add_inputToInputWeights(), LstmInputParamsBuilder::add_inputToOutputWeights(), LstmInputParamsBuilder::add_outputGateBias(), LstmInputParamsBuilder::add_outputLayerNormWeights(), LstmInputParamsBuilder::add_projectionBias(), LstmInputParamsBuilder::add_projectionWeights(), LstmInputParamsBuilder::add_recurrentToCellWeights(), LstmInputParamsBuilder::add_recurrentToForgetWeights(), LstmInputParamsBuilder::add_recurrentToInputWeights(), LstmInputParamsBuilder::add_recurrentToOutputWeights(), and LstmInputParamsBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LstmInputParamsBuilder builder_(_fbb);
   builder_.add_outputLayerNormWeights(outputLayerNormWeights);
   builder_.add_cellLayerNormWeights(cellLayerNormWeights);
   builder_.add_forgetLayerNormWeights(forgetLayerNormWeights);
   builder_.add_inputLayerNormWeights(inputLayerNormWeights);
   builder_.add_cellToOutputWeights(cellToOutputWeights);
   builder_.add_cellToForgetWeights(cellToForgetWeights);
   builder_.add_projectionBias(projectionBias);
   builder_.add_projectionWeights(projectionWeights);
   builder_.add_inputGateBias(inputGateBias);
   builder_.add_cellToInputWeights(cellToInputWeights);
   builder_.add_recurrentToInputWeights(recurrentToInputWeights);
   builder_.add_inputToInputWeights(inputToInputWeights);
   builder_.add_outputGateBias(outputGateBias);
   builder_.add_cellBias(cellBias);
   builder_.add_forgetGateBias(forgetGateBias);
   builder_.add_recurrentToOutputWeights(recurrentToOutputWeights);
   builder_.add_recurrentToCellWeights(recurrentToCellWeights);
   builder_.add_recurrentToForgetWeights(recurrentToForgetWeights);
   builder_.add_inputToOutputWeights(inputToOutputWeights);
   builder_.add_inputToCellWeights(inputToCellWeights);
   builder_.add_inputToForgetWeights(inputToForgetWeights);
   return builder_.Finish();
 }
CreateLstmLayer()
flatbuffers::Offset<LstmLayer> armnnSerializer::CreateLstmLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::LstmDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::LstmInputParams > inputParams = 0) inline
Definition at line 8471 of file ArmnnSchema_generated.h.
References LstmLayerBuilder::add_base(), LstmLayerBuilder::add_descriptor(), LstmLayerBuilder::add_inputParams(), and LstmLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   LstmLayerBuilder builder_(_fbb);
   builder_.add_inputParams(inputParams);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateMaximumLayer()
flatbuffers::Offset<MaximumLayer> armnnSerializer::CreateMaximumLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 4844 of file ArmnnSchema_generated.h.
References MaximumLayerBuilder::add_base(), and MaximumLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   MaximumLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateMeanDescriptor()
flatbuffers::Offset<MeanDescriptor> armnnSerializer::CreateMeanDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis = 0, bool keepDims = false) inline
Definition at line 6668 of file ArmnnSchema_generated.h.
References MeanDescriptorBuilder::add_axis(), MeanDescriptorBuilder::add_keepDims(), and MeanDescriptorBuilder::Finish().
Referenced by CreateMeanDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   MeanDescriptorBuilder builder_(_fbb);
   builder_.add_axis(axis);
   builder_.add_keepDims(keepDims);
   return builder_.Finish();
 }
CreateMeanDescriptorDirect()
flatbuffers::Offset<MeanDescriptor> armnnSerializer::CreateMeanDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * axis = nullptr, bool keepDims = false) inline
Definition at line 6678 of file ArmnnSchema_generated.h.
References CreateMeanDescriptor().
{
   auto axis__ = axis ? _fbb.CreateVector<uint32_t>(*axis) : 0;
   return armnnSerializer::CreateMeanDescriptor(
       _fbb,
       axis__,
       keepDims);
 }
CreateMeanLayer()
flatbuffers::Offset<MeanLayer> armnnSerializer::CreateMeanLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::MeanDescriptor > descriptor = 0) inline
Definition at line 6615 of file ArmnnSchema_generated.h.
References MeanLayerBuilder::add_base(), MeanLayerBuilder::add_descriptor(), and MeanLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   MeanLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateMergeLayer()
flatbuffers::Offset<MergeLayer> armnnSerializer::CreateMergeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 9259 of file ArmnnSchema_generated.h.
References MergeLayerBuilder::add_base(), and MergeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   MergeLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateMergerLayer()
flatbuffers::Offset<MergerLayer> armnnSerializer::CreateMergerLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > descriptor = 0) inline
Definition at line 7575 of file ArmnnSchema_generated.h.
References MergerLayerBuilder::add_base(), MergerLayerBuilder::add_descriptor(), and MergerLayerBuilder::Finish().
{
   MergerLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateMinimumLayer()
flatbuffers::Offset<MinimumLayer> armnnSerializer::CreateMinimumLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 4801 of file ArmnnSchema_generated.h.
References MinimumLayerBuilder::add_base(), and MinimumLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   MinimumLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateMultiplicationLayer()
flatbuffers::Offset<MultiplicationLayer> armnnSerializer::CreateMultiplicationLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 4887 of file ArmnnSchema_generated.h.
References MultiplicationLayerBuilder::add_base(), and MultiplicationLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   MultiplicationLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateNormalizationDescriptor()
flatbuffers::Offset<NormalizationDescriptor> armnnSerializer::CreateNormalizationDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::NormalizationAlgorithmChannel normChannelType = armnnSerializer::NormalizationAlgorithmChannel_Across, armnnSerializer::NormalizationAlgorithmMethod normMethodType = armnnSerializer::NormalizationAlgorithmMethod_LocalBrightness, uint32_t normSize = 0, float alpha = 0.0f, float beta = 0.0f, float k = 0.0f, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NCHW) inline
Definition at line 6551 of file ArmnnSchema_generated.h.
References NormalizationDescriptorBuilder::add_alpha(), NormalizationDescriptorBuilder::add_beta(), NormalizationDescriptorBuilder::add_dataLayout(), NormalizationDescriptorBuilder::add_k(), NormalizationDescriptorBuilder::add_normChannelType(), NormalizationDescriptorBuilder::add_normMethodType(), NormalizationDescriptorBuilder::add_normSize(), and NormalizationDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   NormalizationDescriptorBuilder builder_(_fbb);
   builder_.add_k(k);
   builder_.add_beta(beta);
   builder_.add_alpha(alpha);
   builder_.add_normSize(normSize);
   builder_.add_dataLayout(dataLayout);
   builder_.add_normMethodType(normMethodType);
   builder_.add_normChannelType(normChannelType);
   return builder_.Finish();
 }
CreateNormalizationLayer()
flatbuffers::Offset<NormalizationLayer> armnnSerializer::CreateNormalizationLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::NormalizationDescriptor > descriptor = 0) inline
Definition at line 6459 of file ArmnnSchema_generated.h.
References NormalizationLayerBuilder::add_base(), NormalizationLayerBuilder::add_descriptor(), and NormalizationLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   NormalizationLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateOriginsDescriptor()
flatbuffers::Offset<OriginsDescriptor> armnnSerializer::CreateOriginsDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t concatAxis = 0, uint32_t numViews = 0, uint32_t numDimensions = 0, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewOrigins = 0) inline
Definition at line 7697 of file ArmnnSchema_generated.h.
References OriginsDescriptorBuilder::add_concatAxis(), OriginsDescriptorBuilder::add_numDimensions(), OriginsDescriptorBuilder::add_numViews(), OriginsDescriptorBuilder::add_viewOrigins(), and OriginsDescriptorBuilder::Finish().
Referenced by CreateOriginsDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   OriginsDescriptorBuilder builder_(_fbb);
   builder_.add_viewOrigins(viewOrigins);
   builder_.add_numDimensions(numDimensions);
   builder_.add_numViews(numViews);
   builder_.add_concatAxis(concatAxis);
   return builder_.Finish();
 }
CreateOriginsDescriptorDirect()
flatbuffers::Offset<OriginsDescriptor> armnnSerializer::CreateOriginsDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, uint32_t concatAxis = 0, uint32_t numViews = 0, uint32_t numDimensions = 0, const std::vector< flatbuffers::Offset< armnnSerializer::UintVector >> * viewOrigins = nullptr) inline
Definition at line 7711 of file ArmnnSchema_generated.h.
References CreateOriginsDescriptor().
{
   auto viewOrigins__ = viewOrigins ? _fbb.CreateVector<flatbuffers::Offset<armnnSerializer::UintVector>>(*viewOrigins) : 0;
   return armnnSerializer::CreateOriginsDescriptor(
       _fbb,
       concatAxis,
       numViews,
       numDimensions,
       viewOrigins__);
 }
CreateOutputLayer()
flatbuffers::Offset<OutputLayer> armnnSerializer::CreateOutputLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::BindableLayerBase > base = 0) inline
Definition at line 5739 of file ArmnnSchema_generated.h.
References OutputLayerBuilder::add_base(), and OutputLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   OutputLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateOutputSlot()
flatbuffers::Offset<OutputSlot> armnnSerializer::CreateOutputSlot (flatbuffers::FlatBufferBuilder & _fbb, uint32_t index = 0, flatbuffers::Offset< armnnSerializer::TensorInfo > tensorInfo = 0) inline
Definition at line 2329 of file ArmnnSchema_generated.h.
References OutputSlotBuilder::add_index(), OutputSlotBuilder::add_tensorInfo(), and OutputSlotBuilder::Finish().
Referenced by SerializerStrategy::GetVersionTable().
{
   OutputSlotBuilder builder_(_fbb);
   builder_.add_tensorInfo(tensorInfo);
   builder_.add_index(index);
   return builder_.Finish();
 }
CreatePadDescriptor()
flatbuffers::Offset<PadDescriptor> armnnSerializer::CreatePadDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList = 0, float padValue = 0.0f, armnnSerializer::PaddingMode paddingMode = armnnSerializer::PaddingMode_Constant) inline
Definition at line 6794 of file ArmnnSchema_generated.h.
References PadDescriptorBuilder::add_paddingMode(), PadDescriptorBuilder::add_padList(), PadDescriptorBuilder::add_padValue(), and PadDescriptorBuilder::Finish().
Referenced by CreatePadDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   PadDescriptorBuilder builder_(_fbb);
   builder_.add_padValue(padValue);
   builder_.add_padList(padList);
   builder_.add_paddingMode(paddingMode);
   return builder_.Finish();
 }
CreatePadDescriptorDirect()
flatbuffers::Offset<PadDescriptor> armnnSerializer::CreatePadDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * padList = nullptr, float padValue = 0.0f, armnnSerializer::PaddingMode paddingMode = armnnSerializer::PaddingMode_Constant) inline
Definition at line 6806 of file ArmnnSchema_generated.h.
References CreatePadDescriptor().
{
   auto padList__ = padList ? _fbb.CreateVector<uint32_t>(*padList) : 0;
   return armnnSerializer::CreatePadDescriptor(
       _fbb,
       padList__,
       padValue,
       paddingMode);
 }
CreatePadLayer()
flatbuffers::Offset<PadLayer> armnnSerializer::CreatePadLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::PadDescriptor > descriptor = 0) inline
Definition at line 6733 of file ArmnnSchema_generated.h.
References PadLayerBuilder::add_base(), PadLayerBuilder::add_descriptor(), and PadLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   PadLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreatePermuteDescriptor()
flatbuffers::Offset<PermuteDescriptor> armnnSerializer::CreatePermuteDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimMappings = 0) inline
Definition at line 5942 of file ArmnnSchema_generated.h.
References PermuteDescriptorBuilder::add_dimMappings(), and PermuteDescriptorBuilder::Finish().
Referenced by CreatePermuteDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   PermuteDescriptorBuilder builder_(_fbb);
   builder_.add_dimMappings(dimMappings);
   return builder_.Finish();
 }
CreatePermuteDescriptorDirect()
flatbuffers::Offset<PermuteDescriptor> armnnSerializer::CreatePermuteDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * dimMappings = nullptr) inline
Definition at line 5950 of file ArmnnSchema_generated.h.
References CreatePermuteDescriptor().
{
   auto dimMappings__ = dimMappings ? _fbb.CreateVector<uint32_t>(*dimMappings) : 0;
   return armnnSerializer::CreatePermuteDescriptor(
       _fbb,
       dimMappings__);
 }
CreatePermuteLayer()
flatbuffers::Offset<PermuteLayer> armnnSerializer::CreatePermuteLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::PermuteDescriptor > descriptor = 0) inline
Definition at line 5897 of file ArmnnSchema_generated.h.
References PermuteLayerBuilder::add_base(), PermuteLayerBuilder::add_descriptor(), and PermuteLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   PermuteLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreatePooling2dDescriptor()
flatbuffers::Offset<Pooling2dDescriptor> armnnSerializer::CreatePooling2dDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::PoolingAlgorithm poolType = armnnSerializer::PoolingAlgorithm_Max, uint32_t padLeft = 0, uint32_t padRight = 0, uint32_t padTop = 0, uint32_t padBottom = 0, uint32_t poolWidth = 0, uint32_t poolHeight = 0, uint32_t strideX = 0, uint32_t strideY = 0, armnnSerializer::OutputShapeRounding outputShapeRounding = armnnSerializer::OutputShapeRounding_Floor, armnnSerializer::PaddingMethod paddingMethod = armnnSerializer::PaddingMethod_IgnoreValue, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 5125 of file ArmnnSchema_generated.h.
References Pooling2dDescriptorBuilder::add_dataLayout(), Pooling2dDescriptorBuilder::add_outputShapeRounding(), Pooling2dDescriptorBuilder::add_padBottom(), Pooling2dDescriptorBuilder::add_paddingMethod(), Pooling2dDescriptorBuilder::add_padLeft(), Pooling2dDescriptorBuilder::add_padRight(), Pooling2dDescriptorBuilder::add_padTop(), Pooling2dDescriptorBuilder::add_poolHeight(), Pooling2dDescriptorBuilder::add_poolType(), Pooling2dDescriptorBuilder::add_poolWidth(), Pooling2dDescriptorBuilder::add_strideX(), Pooling2dDescriptorBuilder::add_strideY(), and Pooling2dDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Pooling2dDescriptorBuilder builder_(_fbb);
   builder_.add_strideY(strideY);
   builder_.add_strideX(strideX);
   builder_.add_poolHeight(poolHeight);
   builder_.add_poolWidth(poolWidth);
   builder_.add_padBottom(padBottom);
   builder_.add_padTop(padTop);
   builder_.add_padRight(padRight);
   builder_.add_padLeft(padLeft);
   builder_.add_dataLayout(dataLayout);
   builder_.add_paddingMethod(paddingMethod);
   builder_.add_outputShapeRounding(outputShapeRounding);
   builder_.add_poolType(poolType);
   return builder_.Finish();
 }
CreatePooling2dLayer()
flatbuffers::Offset<Pooling2dLayer> armnnSerializer::CreatePooling2dLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::Pooling2dDescriptor > descriptor = 0) inline
Definition at line 4939 of file ArmnnSchema_generated.h.
References Pooling2dLayerBuilder::add_base(), Pooling2dLayerBuilder::add_descriptor(), and Pooling2dLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Pooling2dLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreatePooling3dDescriptor()
flatbuffers::Offset<Pooling3dDescriptor> armnnSerializer::CreatePooling3dDescriptor (flatbuffers::FlatBufferBuilder & _fbb, armnnSerializer::PoolingAlgorithm poolType = armnnSerializer::PoolingAlgorithm_Max, uint32_t padLeft = 0, uint32_t padRight = 0, uint32_t padTop = 0, uint32_t padBottom = 0, uint32_t padFront = 0, uint32_t padBack = 0, uint32_t poolWidth = 0, uint32_t poolHeight = 0, uint32_t poolDepth = 0, uint32_t strideX = 0, uint32_t strideY = 0, uint32_t strideZ = 0, armnnSerializer::OutputShapeRounding outputShapeRounding = armnnSerializer::OutputShapeRounding_Floor, armnnSerializer::PaddingMethod paddingMethod = armnnSerializer::PaddingMethod_IgnoreValue, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 5309 of file ArmnnSchema_generated.h.
References Pooling3dDescriptorBuilder::add_dataLayout(), Pooling3dDescriptorBuilder::add_outputShapeRounding(), Pooling3dDescriptorBuilder::add_padBack(), Pooling3dDescriptorBuilder::add_padBottom(), Pooling3dDescriptorBuilder::add_paddingMethod(), Pooling3dDescriptorBuilder::add_padFront(), Pooling3dDescriptorBuilder::add_padLeft(), Pooling3dDescriptorBuilder::add_padRight(), Pooling3dDescriptorBuilder::add_padTop(), Pooling3dDescriptorBuilder::add_poolDepth(), Pooling3dDescriptorBuilder::add_poolHeight(), Pooling3dDescriptorBuilder::add_poolType(), Pooling3dDescriptorBuilder::add_poolWidth(), Pooling3dDescriptorBuilder::add_strideX(), Pooling3dDescriptorBuilder::add_strideY(), Pooling3dDescriptorBuilder::add_strideZ(), and Pooling3dDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Pooling3dDescriptorBuilder builder_(_fbb);
   builder_.add_strideZ(strideZ);
   builder_.add_strideY(strideY);
   builder_.add_strideX(strideX);
   builder_.add_poolDepth(poolDepth);
   builder_.add_poolHeight(poolHeight);
   builder_.add_poolWidth(poolWidth);
   builder_.add_padBack(padBack);
   builder_.add_padFront(padFront);
   builder_.add_padBottom(padBottom);
   builder_.add_padTop(padTop);
   builder_.add_padRight(padRight);
   builder_.add_padLeft(padLeft);
   builder_.add_dataLayout(dataLayout);
   builder_.add_paddingMethod(paddingMethod);
   builder_.add_outputShapeRounding(outputShapeRounding);
   builder_.add_poolType(poolType);
   return builder_.Finish();
 }
CreatePooling3dLayer()
flatbuffers::Offset<Pooling3dLayer> armnnSerializer::CreatePooling3dLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::Pooling3dDescriptor > descriptor = 0) inline
Definition at line 4993 of file ArmnnSchema_generated.h.
References Pooling3dLayerBuilder::add_base(), Pooling3dLayerBuilder::add_descriptor(), and Pooling3dLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   Pooling3dLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreatePreluLayer()
flatbuffers::Offset<PreluLayer> armnnSerializer::CreatePreluLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 9345 of file ArmnnSchema_generated.h.
References PreluLayerBuilder::add_base(), and PreluLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   PreluLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateQLstmDescriptor()
flatbuffers::Offset<QLstmDescriptor> armnnSerializer::CreateQLstmDescriptor (flatbuffers::FlatBufferBuilder & _fbb, bool cifgEnabled = true, bool peepholeEnabled = false, bool projectionEnabled = false, bool layerNormEnabled = false, float cellClip = 0.0f, float projectionClip = 0.0f, float inputIntermediateScale = 0.0f, float forgetIntermediateScale = 0.0f, float cellIntermediateScale = 0.0f, float outputIntermediateScale = 0.0f, int32_t hiddenStateZeroPoint = 0, float hiddenStateScale = 0.0f) inline
Definition at line 8868 of file ArmnnSchema_generated.h.
References QLstmDescriptorBuilder::add_cellClip(), QLstmDescriptorBuilder::add_cellIntermediateScale(), QLstmDescriptorBuilder::add_cifgEnabled(), QLstmDescriptorBuilder::add_forgetIntermediateScale(), QLstmDescriptorBuilder::add_hiddenStateScale(), QLstmDescriptorBuilder::add_hiddenStateZeroPoint(), QLstmDescriptorBuilder::add_inputIntermediateScale(), QLstmDescriptorBuilder::add_layerNormEnabled(), QLstmDescriptorBuilder::add_outputIntermediateScale(), QLstmDescriptorBuilder::add_peepholeEnabled(), QLstmDescriptorBuilder::add_projectionClip(), QLstmDescriptorBuilder::add_projectionEnabled(), and QLstmDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   QLstmDescriptorBuilder builder_(_fbb);
   builder_.add_hiddenStateScale(hiddenStateScale);
   builder_.add_hiddenStateZeroPoint(hiddenStateZeroPoint);
   builder_.add_outputIntermediateScale(outputIntermediateScale);
   builder_.add_cellIntermediateScale(cellIntermediateScale);
   builder_.add_forgetIntermediateScale(forgetIntermediateScale);
   builder_.add_inputIntermediateScale(inputIntermediateScale);
   builder_.add_projectionClip(projectionClip);
   builder_.add_cellClip(cellClip);
   builder_.add_layerNormEnabled(layerNormEnabled);
   builder_.add_projectionEnabled(projectionEnabled);
   builder_.add_peepholeEnabled(peepholeEnabled);
   builder_.add_cifgEnabled(cifgEnabled);
   return builder_.Finish();
 }
CreateQLstmInputParams()
flatbuffers::Offset<QLstmInputParams> armnnSerializer::CreateQLstmInputParams (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights = 0) inline
Definition at line 8698 of file ArmnnSchema_generated.h.
References QLstmInputParamsBuilder::add_cellBias(), QLstmInputParamsBuilder::add_cellLayerNormWeights(), QLstmInputParamsBuilder::add_cellToForgetWeights(), QLstmInputParamsBuilder::add_cellToInputWeights(), QLstmInputParamsBuilder::add_cellToOutputWeights(), QLstmInputParamsBuilder::add_forgetGateBias(), QLstmInputParamsBuilder::add_forgetLayerNormWeights(), QLstmInputParamsBuilder::add_inputGateBias(), QLstmInputParamsBuilder::add_inputLayerNormWeights(), QLstmInputParamsBuilder::add_inputToCellWeights(), QLstmInputParamsBuilder::add_inputToForgetWeights(), QLstmInputParamsBuilder::add_inputToInputWeights(), QLstmInputParamsBuilder::add_inputToOutputWeights(), QLstmInputParamsBuilder::add_outputGateBias(), QLstmInputParamsBuilder::add_outputLayerNormWeights(), QLstmInputParamsBuilder::add_projectionBias(), QLstmInputParamsBuilder::add_projectionWeights(), QLstmInputParamsBuilder::add_recurrentToCellWeights(), QLstmInputParamsBuilder::add_recurrentToForgetWeights(), QLstmInputParamsBuilder::add_recurrentToInputWeights(), QLstmInputParamsBuilder::add_recurrentToOutputWeights(), and QLstmInputParamsBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   QLstmInputParamsBuilder builder_(_fbb);
   builder_.add_outputLayerNormWeights(outputLayerNormWeights);
   builder_.add_cellLayerNormWeights(cellLayerNormWeights);
   builder_.add_forgetLayerNormWeights(forgetLayerNormWeights);
   builder_.add_inputLayerNormWeights(inputLayerNormWeights);
   builder_.add_cellToOutputWeights(cellToOutputWeights);
   builder_.add_cellToForgetWeights(cellToForgetWeights);
   builder_.add_cellToInputWeights(cellToInputWeights);
   builder_.add_projectionBias(projectionBias);
   builder_.add_projectionWeights(projectionWeights);
   builder_.add_inputGateBias(inputGateBias);
   builder_.add_recurrentToInputWeights(recurrentToInputWeights);
   builder_.add_inputToInputWeights(inputToInputWeights);
   builder_.add_outputGateBias(outputGateBias);
   builder_.add_cellBias(cellBias);
   builder_.add_forgetGateBias(forgetGateBias);
   builder_.add_recurrentToOutputWeights(recurrentToOutputWeights);
   builder_.add_recurrentToCellWeights(recurrentToCellWeights);
   builder_.add_recurrentToForgetWeights(recurrentToForgetWeights);
   builder_.add_inputToOutputWeights(inputToOutputWeights);
   builder_.add_inputToCellWeights(inputToCellWeights);
   builder_.add_inputToForgetWeights(inputToForgetWeights);
   return builder_.Finish();
 }
CreateQLstmLayer()
flatbuffers::Offset<QLstmLayer> armnnSerializer::CreateQLstmLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::QLstmDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::QLstmInputParams > inputParams = 0) inline
Definition at line 8951 of file ArmnnSchema_generated.h.
References QLstmLayerBuilder::add_base(), QLstmLayerBuilder::add_descriptor(), QLstmLayerBuilder::add_inputParams(), and QLstmLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   QLstmLayerBuilder builder_(_fbb);
   builder_.add_inputParams(inputParams);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateQuantizedLstmInputParams()
flatbuffers::Offset<QuantizedLstmInputParams> armnnSerializer::CreateQuantizedLstmInputParams (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias = 0) inline
Definition at line 9097 of file ArmnnSchema_generated.h.
References QuantizedLstmInputParamsBuilder::add_cellBias(), QuantizedLstmInputParamsBuilder::add_forgetGateBias(), QuantizedLstmInputParamsBuilder::add_inputGateBias(), QuantizedLstmInputParamsBuilder::add_inputToCellWeights(), QuantizedLstmInputParamsBuilder::add_inputToForgetWeights(), QuantizedLstmInputParamsBuilder::add_inputToInputWeights(), QuantizedLstmInputParamsBuilder::add_inputToOutputWeights(), QuantizedLstmInputParamsBuilder::add_outputGateBias(), QuantizedLstmInputParamsBuilder::add_recurrentToCellWeights(), QuantizedLstmInputParamsBuilder::add_recurrentToForgetWeights(), QuantizedLstmInputParamsBuilder::add_recurrentToInputWeights(), QuantizedLstmInputParamsBuilder::add_recurrentToOutputWeights(), and QuantizedLstmInputParamsBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   QuantizedLstmInputParamsBuilder builder_(_fbb);
   builder_.add_outputGateBias(outputGateBias);
   builder_.add_cellBias(cellBias);
   builder_.add_forgetGateBias(forgetGateBias);
   builder_.add_inputGateBias(inputGateBias);
   builder_.add_recurrentToOutputWeights(recurrentToOutputWeights);
   builder_.add_recurrentToCellWeights(recurrentToCellWeights);
   builder_.add_recurrentToForgetWeights(recurrentToForgetWeights);
   builder_.add_recurrentToInputWeights(recurrentToInputWeights);
   builder_.add_inputToOutputWeights(inputToOutputWeights);
   builder_.add_inputToCellWeights(inputToCellWeights);
   builder_.add_inputToForgetWeights(inputToForgetWeights);
   builder_.add_inputToInputWeights(inputToInputWeights);
   return builder_.Finish();
 }
CreateQuantizedLstmLayer()
flatbuffers::Offset<QuantizedLstmLayer> armnnSerializer::CreateQuantizedLstmLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::QuantizedLstmInputParams > inputParams = 0) inline
Definition at line 9171 of file ArmnnSchema_generated.h.
References QuantizedLstmLayerBuilder::add_base(), QuantizedLstmLayerBuilder::add_inputParams(), and QuantizedLstmLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   QuantizedLstmLayerBuilder builder_(_fbb);
   builder_.add_inputParams(inputParams);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateQuantizeLayer()
flatbuffers::Offset<QuantizeLayer> armnnSerializer::CreateQuantizeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 5382 of file ArmnnSchema_generated.h.
References QuantizeLayerBuilder::add_base(), and QuantizeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   QuantizeLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateRankLayer()
flatbuffers::Offset<RankLayer> armnnSerializer::CreateRankLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 10064 of file ArmnnSchema_generated.h.
References RankLayerBuilder::add_base(), and RankLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   RankLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateReduceDescriptor()
flatbuffers::Offset<ReduceDescriptor> armnnSerializer::CreateReduceDescriptor (flatbuffers::FlatBufferBuilder & _fbb, bool keepDims = false, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> axis = 0, armnnSerializer::ReduceOperation reduceOperation = armnnSerializer::ReduceOperation_Sum) inline
Definition at line 10177 of file ArmnnSchema_generated.h.
References ReduceDescriptorBuilder::add_axis(), ReduceDescriptorBuilder::add_keepDims(), ReduceDescriptorBuilder::add_reduceOperation(), and ReduceDescriptorBuilder::Finish().
Referenced by CreateReduceDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   ReduceDescriptorBuilder builder_(_fbb);
   builder_.add_axis(axis);
   builder_.add_reduceOperation(reduceOperation);
   builder_.add_keepDims(keepDims);
   return builder_.Finish();
 }
CreateReduceDescriptorDirect()
flatbuffers::Offset<ReduceDescriptor> armnnSerializer::CreateReduceDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, bool keepDims = false, const std::vector< uint32_t > * axis = nullptr, armnnSerializer::ReduceOperation reduceOperation = armnnSerializer::ReduceOperation_Sum) inline
Definition at line 10189 of file ArmnnSchema_generated.h.
References CreateReduceDescriptor().
{
   auto axis__ = axis ? _fbb.CreateVector<uint32_t>(*axis) : 0;
   return armnnSerializer::CreateReduceDescriptor(
       _fbb,
       keepDims,
       axis__,
       reduceOperation);
 }
CreateReduceLayer()
flatbuffers::Offset<ReduceLayer> armnnSerializer::CreateReduceLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ReduceDescriptor > descriptor = 0) inline
Definition at line 10116 of file ArmnnSchema_generated.h.
References ReduceLayerBuilder::add_base(), ReduceLayerBuilder::add_descriptor(), and ReduceLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ReduceLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateReshapeDescriptor()
flatbuffers::Offset<ReshapeDescriptor> armnnSerializer::CreateReshapeDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> targetShape = 0) inline
Definition at line 5836 of file ArmnnSchema_generated.h.
References ReshapeDescriptorBuilder::add_targetShape(), and ReshapeDescriptorBuilder::Finish().
Referenced by CreateReshapeDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   ReshapeDescriptorBuilder builder_(_fbb);
   builder_.add_targetShape(targetShape);
   return builder_.Finish();
 }
CreateReshapeDescriptorDirect()
flatbuffers::Offset<ReshapeDescriptor> armnnSerializer::CreateReshapeDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * targetShape = nullptr) inline
Definition at line 5844 of file ArmnnSchema_generated.h.
References CreateReshapeDescriptor().
{
   auto targetShape__ = targetShape ? _fbb.CreateVector<uint32_t>(*targetShape) : 0;
   return armnnSerializer::CreateReshapeDescriptor(
       _fbb,
       targetShape__);
 }
CreateReshapeLayer()
flatbuffers::Offset<ReshapeLayer> armnnSerializer::CreateReshapeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ReshapeDescriptor > descriptor = 0) inline
Definition at line 5791 of file ArmnnSchema_generated.h.
References ReshapeLayerBuilder::add_base(), ReshapeLayerBuilder::add_descriptor(), and ReshapeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ReshapeLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateResizeBilinearDescriptor()
flatbuffers::Offset<ResizeBilinearDescriptor> armnnSerializer::CreateResizeBilinearDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t targetWidth = 0, uint32_t targetHeight = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC, bool alignCorners = false, bool halfPixelCenters = false) inline
Definition at line 7134 of file ArmnnSchema_generated.h.
References ResizeBilinearDescriptorBuilder::add_alignCorners(), ResizeBilinearDescriptorBuilder::add_dataLayout(), ResizeBilinearDescriptorBuilder::add_halfPixelCenters(), ResizeBilinearDescriptorBuilder::add_targetHeight(), ResizeBilinearDescriptorBuilder::add_targetWidth(), and ResizeBilinearDescriptorBuilder::Finish().
{
   ResizeBilinearDescriptorBuilder builder_(_fbb);
   builder_.add_targetHeight(targetHeight);
   builder_.add_targetWidth(targetWidth);
   builder_.add_halfPixelCenters(halfPixelCenters);
   builder_.add_alignCorners(alignCorners);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateResizeBilinearLayer()
flatbuffers::Offset<ResizeBilinearLayer> armnnSerializer::CreateResizeBilinearLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ResizeBilinearDescriptor > descriptor = 0) inline
Definition at line 7058 of file ArmnnSchema_generated.h.
References ResizeBilinearLayerBuilder::add_base(), ResizeBilinearLayerBuilder::add_descriptor(), and ResizeBilinearLayerBuilder::Finish().
{
   ResizeBilinearLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateResizeDescriptor()
flatbuffers::Offset<ResizeDescriptor> armnnSerializer::CreateResizeDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t targetHeight = 0, uint32_t targetWidth = 0, armnnSerializer::ResizeMethod method = armnnSerializer::ResizeMethod_NearestNeighbor, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC, bool alignCorners = false, bool halfPixelCenters = false) inline
Definition at line 9775 of file ArmnnSchema_generated.h.
References ResizeDescriptorBuilder::add_alignCorners(), ResizeDescriptorBuilder::add_dataLayout(), ResizeDescriptorBuilder::add_halfPixelCenters(), ResizeDescriptorBuilder::add_method(), ResizeDescriptorBuilder::add_targetHeight(), ResizeDescriptorBuilder::add_targetWidth(), and ResizeDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ResizeDescriptorBuilder builder_(_fbb);
   builder_.add_targetWidth(targetWidth);
   builder_.add_targetHeight(targetHeight);
   builder_.add_halfPixelCenters(halfPixelCenters);
   builder_.add_alignCorners(alignCorners);
   builder_.add_dataLayout(dataLayout);
   builder_.add_method(method);
   return builder_.Finish();
 }
CreateResizeLayer()
flatbuffers::Offset<ResizeLayer> armnnSerializer::CreateResizeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ResizeDescriptor > descriptor = 0) inline
Definition at line 9691 of file ArmnnSchema_generated.h.
References ResizeLayerBuilder::add_base(), ResizeLayerBuilder::add_descriptor(), and ResizeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ResizeLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateRsqrtLayer()
flatbuffers::Offset<RsqrtLayer> armnnSerializer::CreateRsqrtLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 6855 of file ArmnnSchema_generated.h.
References RsqrtLayerBuilder::add_base(), and RsqrtLayerBuilder::Finish().
{
   RsqrtLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSerializedGraph()
flatbuffers::Offset<SerializedGraph> armnnSerializer::CreateSerializedGraph (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::AnyLayer >>> layers = 0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> inputIds = 0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> outputIds = 0, flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > featureVersions = 0) inline
Definition at line 11034 of file ArmnnSchema_generated.h.
References SerializedGraphBuilder::add_featureVersions(), SerializedGraphBuilder::add_inputIds(), SerializedGraphBuilder::add_layers(), SerializedGraphBuilder::add_outputIds(), and SerializedGraphBuilder::Finish().
Referenced by CreateSerializedGraphDirect(), and ISerializer::SerializerImpl::Serialize().
{
   SerializedGraphBuilder builder_(_fbb);
   builder_.add_featureVersions(featureVersions);
   builder_.add_outputIds(outputIds);
   builder_.add_inputIds(inputIds);
   builder_.add_layers(layers);
   return builder_.Finish();
 }
CreateSerializedGraphDirect()
flatbuffers::Offset<SerializedGraph> armnnSerializer::CreateSerializedGraphDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< flatbuffers::Offset< armnnSerializer::AnyLayer >> * layers = nullptr, const std::vector< int32_t > * inputIds = nullptr, const std::vector< int32_t > * outputIds = nullptr, flatbuffers::Offset< armnnSerializer::FeatureCompatibilityVersions > featureVersions = 0) inline
Definition at line 11048 of file ArmnnSchema_generated.h.
References CreateSerializedGraph().
{
   auto layers__ = layers ? _fbb.CreateVector<flatbuffers::Offset<armnnSerializer::AnyLayer>>(*layers) : 0;
   auto inputIds__ = inputIds ? _fbb.CreateVector<int32_t>(*inputIds) : 0;
   auto outputIds__ = outputIds ? _fbb.CreateVector<int32_t>(*outputIds) : 0;
   return armnnSerializer::CreateSerializedGraph(
       _fbb,
       layers__,
       inputIds__,
       outputIds__,
       featureVersions);
 }
CreateShapeLayer()
flatbuffers::Offset<ShapeLayer> armnnSerializer::CreateShapeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 5994 of file ArmnnSchema_generated.h.
References ShapeLayerBuilder::add_base(), and ShapeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   ShapeLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateShortData()
flatbuffers::Offset<ShortData> armnnSerializer::CreateShortData (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< int16_t >> data = 0) inline
Definition at line 2020 of file ArmnnSchema_generated.h.
References ShortDataBuilder::add_data(), and ShortDataBuilder::Finish().
Referenced by CreateShortDataDirect(), and GetFlatBufferArgMinMaxFunction().
{
   ShortDataBuilder builder_(_fbb);
   builder_.add_data(data);
   return builder_.Finish();
 }
CreateShortDataDirect()
flatbuffers::Offset<ShortData> armnnSerializer::CreateShortDataDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< int16_t > * data = nullptr) inline
Definition at line 2028 of file ArmnnSchema_generated.h.
References CreateShortData().
{
   auto data__ = data ? _fbb.CreateVector<int16_t>(*data) : 0;
   return armnnSerializer::CreateShortData(
       _fbb,
       data__);
 }
CreateSliceDescriptor()
flatbuffers::Offset<SliceDescriptor> armnnSerializer::CreateSliceDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> begin = 0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> size = 0) inline
Definition at line 7248 of file ArmnnSchema_generated.h.
References SliceDescriptorBuilder::add_begin(), SliceDescriptorBuilder::add_size(), and SliceDescriptorBuilder::Finish().
Referenced by CreateSliceDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   SliceDescriptorBuilder builder_(_fbb);
   builder_.add_size(size);
   builder_.add_begin(begin);
   return builder_.Finish();
 }
CreateSliceDescriptorDirect()
flatbuffers::Offset<SliceDescriptor> armnnSerializer::CreateSliceDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * begin = nullptr, const std::vector< uint32_t > * size = nullptr) inline
Definition at line 7258 of file ArmnnSchema_generated.h.
References CreateSliceDescriptor().
{
   auto begin__ = begin ? _fbb.CreateVector<uint32_t>(*begin) : 0;
   auto size__ = size ? _fbb.CreateVector<uint32_t>(*size) : 0;
   return armnnSerializer::CreateSliceDescriptor(
       _fbb,
       begin__,
       size__);
 }
CreateSliceLayer()
flatbuffers::Offset<SliceLayer> armnnSerializer::CreateSliceLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::SliceDescriptor > descriptor = 0) inline
Definition at line 7194 of file ArmnnSchema_generated.h.
References SliceLayerBuilder::add_base(), SliceLayerBuilder::add_descriptor(), and SliceLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SliceLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSoftmaxDescriptor()
flatbuffers::Offset<SoftmaxDescriptor> armnnSerializer::CreateSoftmaxDescriptor (flatbuffers::FlatBufferBuilder & _fbb, float beta = 0.0f, int32_t axis = -1) inline
Definition at line 5486 of file ArmnnSchema_generated.h.
References SoftmaxDescriptorBuilder::add_axis(), SoftmaxDescriptorBuilder::add_beta(), and SoftmaxDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SoftmaxDescriptorBuilder builder_(_fbb);
   builder_.add_axis(axis);
   builder_.add_beta(beta);
   return builder_.Finish();
 }
CreateSoftmaxLayer()
flatbuffers::Offset<SoftmaxLayer> armnnSerializer::CreateSoftmaxLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::SoftmaxDescriptor > descriptor = 0) inline
Definition at line 5434 of file ArmnnSchema_generated.h.
References SoftmaxLayerBuilder::add_base(), SoftmaxLayerBuilder::add_descriptor(), and SoftmaxLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SoftmaxLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSpaceToBatchNdDescriptor()
flatbuffers::Offset<SpaceToBatchNdDescriptor> armnnSerializer::CreateSpaceToBatchNdDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> blockShape = 0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> padList = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 6108 of file ArmnnSchema_generated.h.
References SpaceToBatchNdDescriptorBuilder::add_blockShape(), SpaceToBatchNdDescriptorBuilder::add_dataLayout(), SpaceToBatchNdDescriptorBuilder::add_padList(), and SpaceToBatchNdDescriptorBuilder::Finish().
Referenced by CreateSpaceToBatchNdDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   SpaceToBatchNdDescriptorBuilder builder_(_fbb);
   builder_.add_padList(padList);
   builder_.add_blockShape(blockShape);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateSpaceToBatchNdDescriptorDirect()
flatbuffers::Offset<SpaceToBatchNdDescriptor> armnnSerializer::CreateSpaceToBatchNdDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * blockShape = nullptr, const std::vector< uint32_t > * padList = nullptr, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 6120 of file ArmnnSchema_generated.h.
References CreateSpaceToBatchNdDescriptor().
{
   auto blockShape__ = blockShape ? _fbb.CreateVector<uint32_t>(*blockShape) : 0;
   auto padList__ = padList ? _fbb.CreateVector<uint32_t>(*padList) : 0;
   return armnnSerializer::CreateSpaceToBatchNdDescriptor(
       _fbb,
       blockShape__,
       padList__,
       dataLayout);
 }
CreateSpaceToBatchNdLayer()
flatbuffers::Offset<SpaceToBatchNdLayer> armnnSerializer::CreateSpaceToBatchNdLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::SpaceToBatchNdDescriptor > descriptor = 0) inline
Definition at line 6046 of file ArmnnSchema_generated.h.
References SpaceToBatchNdLayerBuilder::add_base(), SpaceToBatchNdLayerBuilder::add_descriptor(), and SpaceToBatchNdLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SpaceToBatchNdLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSpaceToDepthDescriptor()
flatbuffers::Offset<SpaceToDepthDescriptor> armnnSerializer::CreateSpaceToDepthDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t blockSize = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 6230 of file ArmnnSchema_generated.h.
References SpaceToDepthDescriptorBuilder::add_blockSize(), SpaceToDepthDescriptorBuilder::add_dataLayout(), and SpaceToDepthDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SpaceToDepthDescriptorBuilder builder_(_fbb);
   builder_.add_blockSize(blockSize);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateSpaceToDepthLayer()
flatbuffers::Offset<SpaceToDepthLayer> armnnSerializer::CreateSpaceToDepthLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::SpaceToDepthDescriptor > descriptor = 0) inline
Definition at line 6178 of file ArmnnSchema_generated.h.
References SpaceToDepthLayerBuilder::add_base(), SpaceToDepthLayerBuilder::add_descriptor(), and SpaceToDepthLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SpaceToDepthLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSplitterLayer()
flatbuffers::Offset<SplitterLayer> armnnSerializer::CreateSplitterLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::ViewsDescriptor > descriptor = 0) inline
Definition at line 7836 of file ArmnnSchema_generated.h.
References SplitterLayerBuilder::add_base(), SplitterLayerBuilder::add_descriptor(), and SplitterLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SplitterLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateStackDescriptor()
flatbuffers::Offset<StackDescriptor> armnnSerializer::CreateStackDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t axis = 0, uint32_t numInputs = 0, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> inputShape = 0) inline
Definition at line 9898 of file ArmnnSchema_generated.h.
References StackDescriptorBuilder::add_axis(), StackDescriptorBuilder::add_inputShape(), StackDescriptorBuilder::add_numInputs(), and StackDescriptorBuilder::Finish().
Referenced by CreateStackDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   StackDescriptorBuilder builder_(_fbb);
   builder_.add_inputShape(inputShape);
   builder_.add_numInputs(numInputs);
   builder_.add_axis(axis);
   return builder_.Finish();
 }
CreateStackDescriptorDirect()
flatbuffers::Offset<StackDescriptor> armnnSerializer::CreateStackDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, uint32_t axis = 0, uint32_t numInputs = 0, const std::vector< uint32_t > * inputShape = nullptr) inline
Definition at line 9910 of file ArmnnSchema_generated.h.
References CreateStackDescriptor().
{
   auto inputShape__ = inputShape ? _fbb.CreateVector<uint32_t>(*inputShape) : 0;
   return armnnSerializer::CreateStackDescriptor(
       _fbb,
       axis,
       numInputs,
       inputShape__);
 }
CreateStackLayer()
flatbuffers::Offset<StackLayer> armnnSerializer::CreateStackLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::StackDescriptor > descriptor = 0) inline
Definition at line 9837 of file ArmnnSchema_generated.h.
References StackLayerBuilder::add_base(), StackLayerBuilder::add_descriptor(), and StackLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   StackLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateStandInDescriptor()
flatbuffers::Offset<StandInDescriptor> armnnSerializer::CreateStandInDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t numInputs = 0, uint32_t numOutputs = 0) inline
Definition at line 9965 of file ArmnnSchema_generated.h.
References StandInDescriptorBuilder::add_numInputs(), StandInDescriptorBuilder::add_numOutputs(), and StandInDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   StandInDescriptorBuilder builder_(_fbb);
   builder_.add_numOutputs(numOutputs);
   builder_.add_numInputs(numInputs);
   return builder_.Finish();
 }
CreateStandInLayer()
flatbuffers::Offset<StandInLayer> armnnSerializer::CreateStandInLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::StandInDescriptor > descriptor = 0) inline
Definition at line 10019 of file ArmnnSchema_generated.h.
References StandInLayerBuilder::add_base(), StandInLayerBuilder::add_descriptor(), and StandInLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   StandInLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateStridedSliceDescriptor()
flatbuffers::Offset<StridedSliceDescriptor> armnnSerializer::CreateStridedSliceDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< int32_t >> begin = 0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> end = 0, flatbuffers::Offset< flatbuffers::Vector< int32_t >> stride = 0, int32_t beginMask = 0, int32_t endMask = 0, int32_t shrinkAxisMask = 0, int32_t ellipsisMask = 0, int32_t newAxisMask = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 7425 of file ArmnnSchema_generated.h.
References StridedSliceDescriptorBuilder::add_begin(), StridedSliceDescriptorBuilder::add_beginMask(), StridedSliceDescriptorBuilder::add_dataLayout(), StridedSliceDescriptorBuilder::add_ellipsisMask(), StridedSliceDescriptorBuilder::add_end(), StridedSliceDescriptorBuilder::add_endMask(), StridedSliceDescriptorBuilder::add_newAxisMask(), StridedSliceDescriptorBuilder::add_shrinkAxisMask(), StridedSliceDescriptorBuilder::add_stride(), and StridedSliceDescriptorBuilder::Finish().
Referenced by CreateStridedSliceDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   StridedSliceDescriptorBuilder builder_(_fbb);
   builder_.add_newAxisMask(newAxisMask);
   builder_.add_ellipsisMask(ellipsisMask);
   builder_.add_shrinkAxisMask(shrinkAxisMask);
   builder_.add_endMask(endMask);
   builder_.add_beginMask(beginMask);
   builder_.add_stride(stride);
   builder_.add_end(end);
   builder_.add_begin(begin);
   builder_.add_dataLayout(dataLayout);
   return builder_.Finish();
 }
CreateStridedSliceDescriptorDirect()
flatbuffers::Offset<StridedSliceDescriptor> armnnSerializer::CreateStridedSliceDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< int32_t > * begin = nullptr, const std::vector< int32_t > * end = nullptr, const std::vector< int32_t > * stride = nullptr, int32_t beginMask = 0, int32_t endMask = 0, int32_t shrinkAxisMask = 0, int32_t ellipsisMask = 0, int32_t newAxisMask = 0, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NHWC) inline
Definition at line 7449 of file ArmnnSchema_generated.h.
References CreateStridedSliceDescriptor().
{
   auto begin__ = begin ? _fbb.CreateVector<int32_t>(*begin) : 0;
   auto end__ = end ? _fbb.CreateVector<int32_t>(*end) : 0;
   auto stride__ = stride ? _fbb.CreateVector<int32_t>(*stride) : 0;
   return armnnSerializer::CreateStridedSliceDescriptor(
       _fbb,
       begin__,
       end__,
       stride__,
       beginMask,
       endMask,
       shrinkAxisMask,
       ellipsisMask,
       newAxisMask,
       dataLayout);
 }
CreateStridedSliceLayer()
flatbuffers::Offset<StridedSliceLayer> armnnSerializer::CreateStridedSliceLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::StridedSliceDescriptor > descriptor = 0) inline
Definition at line 7314 of file ArmnnSchema_generated.h.
References StridedSliceLayerBuilder::add_base(), StridedSliceLayerBuilder::add_descriptor(), and StridedSliceLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   StridedSliceLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSubtractionLayer()
flatbuffers::Offset<SubtractionLayer> armnnSerializer::CreateSubtractionLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 6275 of file ArmnnSchema_generated.h.
References SubtractionLayerBuilder::add_base(), and SubtractionLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SubtractionLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateSwitchLayer()
flatbuffers::Offset<SwitchLayer> armnnSerializer::CreateSwitchLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0) inline
Definition at line 9302 of file ArmnnSchema_generated.h.
References SwitchLayerBuilder::add_base(), and SwitchLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   SwitchLayerBuilder builder_(_fbb);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateTensorInfo()
flatbuffers::Offset<TensorInfo> armnnSerializer::CreateTensorInfo (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimensions = 0, armnnSerializer::DataType dataType = armnnSerializer::DataType_Float16, float quantizationScale = 1.0f, int32_t quantizationOffset = 0, flatbuffers::Offset< flatbuffers::Vector< float >> quantizationScales = 0, uint32_t quantizationDim = 0, uint32_t dimensionality = 1, flatbuffers::Offset< flatbuffers::Vector< uint8_t >> dimensionSpecificity = 0, bool isConstant = false) inline
Definition at line 1882 of file ArmnnSchema_generated.h.
References TensorInfoBuilder::add_dataType(), TensorInfoBuilder::add_dimensionality(), TensorInfoBuilder::add_dimensions(), TensorInfoBuilder::add_dimensionSpecificity(), TensorInfoBuilder::add_isConstant(), TensorInfoBuilder::add_quantizationDim(), TensorInfoBuilder::add_quantizationOffset(), TensorInfoBuilder::add_quantizationScale(), TensorInfoBuilder::add_quantizationScales(), and TensorInfoBuilder::Finish().
Referenced by CreateTensorInfoDirect(), GetFlatBufferArgMinMaxFunction(), and SerializerStrategy::GetVersionTable().
{
   TensorInfoBuilder builder_(_fbb);
   builder_.add_dimensionSpecificity(dimensionSpecificity);
   builder_.add_dimensionality(dimensionality);
   builder_.add_quantizationDim(quantizationDim);
   builder_.add_quantizationScales(quantizationScales);
   builder_.add_quantizationOffset(quantizationOffset);
   builder_.add_quantizationScale(quantizationScale);
   builder_.add_dimensions(dimensions);
   builder_.add_isConstant(isConstant);
   builder_.add_dataType(dataType);
   return builder_.Finish();
 }
CreateTensorInfoDirect()
flatbuffers::Offset<TensorInfo> armnnSerializer::CreateTensorInfoDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * dimensions = nullptr, armnnSerializer::DataType dataType = armnnSerializer::DataType_Float16, float quantizationScale = 1.0f, int32_t quantizationOffset = 0, const std::vector< float > * quantizationScales = nullptr, uint32_t quantizationDim = 0, uint32_t dimensionality = 1, const std::vector< uint8_t > * dimensionSpecificity = nullptr, bool isConstant = false) inline
Definition at line 1906 of file ArmnnSchema_generated.h.
References CreateTensorInfo().
{
   auto dimensions__ = dimensions ? _fbb.CreateVector<uint32_t>(*dimensions) : 0;
   auto quantizationScales__ = quantizationScales ? _fbb.CreateVector<float>(*quantizationScales) : 0;
   auto dimensionSpecificity__ = dimensionSpecificity ? _fbb.CreateVector<uint8_t>(*dimensionSpecificity) : 0;
   return armnnSerializer::CreateTensorInfo(
       _fbb,
       dimensions__,
       dataType,
       quantizationScale,
       quantizationOffset,
       quantizationScales__,
       quantizationDim,
       dimensionality,
       dimensionSpecificity__,
       isConstant);
 }
CreateTransposeConvolution2dDescriptor()
flatbuffers::Offset<TransposeConvolution2dDescriptor> armnnSerializer::CreateTransposeConvolution2dDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t padLeft = 0, uint32_t padRight = 0, uint32_t padTop = 0, uint32_t padBottom = 0, uint32_t strideX = 0, uint32_t strideY = 0, bool biasEnabled = false, armnnSerializer::DataLayout dataLayout = armnnSerializer::DataLayout_NCHW) inline
Definition at line 9519 of file ArmnnSchema_generated.h.
References TransposeConvolution2dDescriptorBuilder::add_biasEnabled(), TransposeConvolution2dDescriptorBuilder::add_dataLayout(), TransposeConvolution2dDescriptorBuilder::add_padBottom(), TransposeConvolution2dDescriptorBuilder::add_padLeft(), TransposeConvolution2dDescriptorBuilder::add_padRight(), TransposeConvolution2dDescriptorBuilder::add_padTop(), TransposeConvolution2dDescriptorBuilder::add_strideX(), TransposeConvolution2dDescriptorBuilder::add_strideY(), and TransposeConvolution2dDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   TransposeConvolution2dDescriptorBuilder builder_(_fbb);
   builder_.add_strideY(strideY);
   builder_.add_strideX(strideX);
   builder_.add_padBottom(padBottom);
   builder_.add_padTop(padTop);
   builder_.add_padRight(padRight);
   builder_.add_padLeft(padLeft);
   builder_.add_dataLayout(dataLayout);
   builder_.add_biasEnabled(biasEnabled);
   return builder_.Finish();
 }
CreateTransposeConvolution2dLayer()
flatbuffers::Offset<TransposeConvolution2dLayer> armnnSerializer::CreateTransposeConvolution2dLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::TransposeConvolution2dDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > weights = 0, flatbuffers::Offset< armnnSerializer::ConstTensor > biases = 0) inline
Definition at line 9415 of file ArmnnSchema_generated.h.
References TransposeConvolution2dLayerBuilder::add_base(), TransposeConvolution2dLayerBuilder::add_biases(), TransposeConvolution2dLayerBuilder::add_descriptor(), TransposeConvolution2dLayerBuilder::add_weights(), and TransposeConvolution2dLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   TransposeConvolution2dLayerBuilder builder_(_fbb);
   builder_.add_biases(biases);
   builder_.add_weights(weights);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateTransposeDescriptor()
flatbuffers::Offset<TransposeDescriptor> armnnSerializer::CreateTransposeDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimMappings = 0) inline
Definition at line 9630 of file ArmnnSchema_generated.h.
References TransposeDescriptorBuilder::add_dimMappings(), and TransposeDescriptorBuilder::Finish().
Referenced by CreateTransposeDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   TransposeDescriptorBuilder builder_(_fbb);
   builder_.add_dimMappings(dimMappings);
   return builder_.Finish();
 }
CreateTransposeDescriptorDirect()
flatbuffers::Offset<TransposeDescriptor> armnnSerializer::CreateTransposeDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * dimMappings = nullptr) inline
Definition at line 9638 of file ArmnnSchema_generated.h.
References CreateTransposeDescriptor().
{
   auto dimMappings__ = dimMappings ? _fbb.CreateVector<uint32_t>(*dimMappings) : 0;
   return armnnSerializer::CreateTransposeDescriptor(
       _fbb,
       dimMappings__);
 }
CreateTransposeLayer()
flatbuffers::Offset<TransposeLayer> armnnSerializer::CreateTransposeLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::TransposeDescriptor > descriptor = 0) inline
Definition at line 9585 of file ArmnnSchema_generated.h.
References TransposeLayerBuilder::add_base(), TransposeLayerBuilder::add_descriptor(), and TransposeLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   TransposeLayerBuilder builder_(_fbb);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateUintVector()
flatbuffers::Offset<UintVector> armnnSerializer::CreateUintVector (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< flatbuffers::Vector< uint32_t >> data = 0) inline
Definition at line 7620 of file ArmnnSchema_generated.h.
References UintVectorBuilder::add_data(), and UintVectorBuilder::Finish().
Referenced by CreateUintVectorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   UintVectorBuilder builder_(_fbb);
   builder_.add_data(data);
   return builder_.Finish();
 }
CreateUintVectorDirect()
flatbuffers::Offset<UintVector> armnnSerializer::CreateUintVectorDirect (flatbuffers::FlatBufferBuilder & _fbb, const std::vector< uint32_t > * data = nullptr) inline
Definition at line 7628 of file ArmnnSchema_generated.h.
References CreateUintVector().
{
   auto data__ = data ? _fbb.CreateVector<uint32_t>(*data) : 0;
   return armnnSerializer::CreateUintVector(
       _fbb,
       data__);
 }
CreateUnidirectionalSequenceLstmDescriptor()
flatbuffers::Offset<UnidirectionalSequenceLstmDescriptor> armnnSerializer::CreateUnidirectionalSequenceLstmDescriptor (flatbuffers::FlatBufferBuilder & _fbb, uint32_t activationFunc = 0, float clippingThresCell = 0.0f, float clippingThresProj = 0.0f, bool cifgEnabled = true, bool peepholeEnabled = false, bool projectionEnabled = false, bool layerNormEnabled = false, bool timeMajor = false) inline
Definition at line 10292 of file ArmnnSchema_generated.h.
References UnidirectionalSequenceLstmDescriptorBuilder::add_activationFunc(), UnidirectionalSequenceLstmDescriptorBuilder::add_cifgEnabled(), UnidirectionalSequenceLstmDescriptorBuilder::add_clippingThresCell(), UnidirectionalSequenceLstmDescriptorBuilder::add_clippingThresProj(), UnidirectionalSequenceLstmDescriptorBuilder::add_layerNormEnabled(), UnidirectionalSequenceLstmDescriptorBuilder::add_peepholeEnabled(), UnidirectionalSequenceLstmDescriptorBuilder::add_projectionEnabled(), UnidirectionalSequenceLstmDescriptorBuilder::add_timeMajor(), and UnidirectionalSequenceLstmDescriptorBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   UnidirectionalSequenceLstmDescriptorBuilder builder_(_fbb);
   builder_.add_clippingThresProj(clippingThresProj);
   builder_.add_clippingThresCell(clippingThresCell);
   builder_.add_activationFunc(activationFunc);
   builder_.add_timeMajor(timeMajor);
   builder_.add_layerNormEnabled(layerNormEnabled);
   builder_.add_projectionEnabled(projectionEnabled);
   builder_.add_peepholeEnabled(peepholeEnabled);
   builder_.add_cifgEnabled(cifgEnabled);
   return builder_.Finish();
 }
CreateUnidirectionalSequenceLstmLayer()
flatbuffers::Offset<UnidirectionalSequenceLstmLayer> armnnSerializer::CreateUnidirectionalSequenceLstmLayer (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::LayerBase > base = 0, flatbuffers::Offset< armnnSerializer::UnidirectionalSequenceLstmDescriptor > descriptor = 0, flatbuffers::Offset< armnnSerializer::LstmInputParams > inputParams = 0) inline
Definition at line 10367 of file ArmnnSchema_generated.h.
References UnidirectionalSequenceLstmLayerBuilder::add_base(), UnidirectionalSequenceLstmLayerBuilder::add_descriptor(), UnidirectionalSequenceLstmLayerBuilder::add_inputParams(), and UnidirectionalSequenceLstmLayerBuilder::Finish().
Referenced by GetFlatBufferArgMinMaxFunction().
{
   UnidirectionalSequenceLstmLayerBuilder builder_(_fbb);
   builder_.add_inputParams(inputParams);
   builder_.add_descriptor(descriptor);
   builder_.add_base(base);
   return builder_.Finish();
 }
CreateViewsDescriptor()
flatbuffers::Offset<ViewsDescriptor> armnnSerializer::CreateViewsDescriptor (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > origins = 0, flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::UintVector >>> viewSizes = 0) inline
Definition at line 7771 of file ArmnnSchema_generated.h.
References ViewsDescriptorBuilder::add_origins(), ViewsDescriptorBuilder::add_viewSizes(), and ViewsDescriptorBuilder::Finish().
Referenced by CreateViewsDescriptorDirect(), and GetFlatBufferArgMinMaxFunction().
{
   ViewsDescriptorBuilder builder_(_fbb);
   builder_.add_viewSizes(viewSizes);
   builder_.add_origins(origins);
   return builder_.Finish();
 }
CreateViewsDescriptorDirect()
flatbuffers::Offset<ViewsDescriptor> armnnSerializer::CreateViewsDescriptorDirect (flatbuffers::FlatBufferBuilder & _fbb, flatbuffers::Offset< armnnSerializer::OriginsDescriptor > origins = 0, const std::vector< flatbuffers::Offset< armnnSerializer::UintVector >> * viewSizes = nullptr) inline
Definition at line 7781 of file ArmnnSchema_generated.h.
References CreateViewsDescriptor().
{
   auto viewSizes__ = viewSizes ? _fbb.CreateVector<flatbuffers::Offset<armnnSerializer::UintVector>>(*viewSizes) : 0;
   return armnnSerializer::CreateViewsDescriptor(
       _fbb,
       origins,
       viewSizes__);
 }
EnumNameActivationFunction()
const char* armnnSerializer::EnumNameActivationFunction (ActivationFunction e) inline
Definition at line 455 of file ArmnnSchema_generated.h.
References ActivationFunction_HardSwish, ActivationFunction_Sigmoid, and EnumNamesActivationFunction().
{
   if (flatbuffers::IsOutRange(e, ActivationFunction_Sigmoid, ActivationFunction_HardSwish)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesActivationFunction()[index];
 }
EnumNameArgMinMaxFunction()
const char* armnnSerializer::EnumNameArgMinMaxFunction (ArgMinMaxFunction e) inline
Definition at line 485 of file ArmnnSchema_generated.h.
References ArgMinMaxFunction_Max, ArgMinMaxFunction_Min, and EnumNamesArgMinMaxFunction().
{
   if (flatbuffers::IsOutRange(e, ArgMinMaxFunction_Min, ArgMinMaxFunction_Max)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesArgMinMaxFunction()[index];
 }
EnumNameComparisonOperation()
const char* armnnSerializer::EnumNameComparisonOperation (ComparisonOperation e) inline
Definition at line 979 of file ArmnnSchema_generated.h.
References ComparisonOperation_Equal, ComparisonOperation_NotEqual, and EnumNamesComparisonOperation().
{
   if (flatbuffers::IsOutRange(e, ComparisonOperation_Equal, ComparisonOperation_NotEqual)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesComparisonOperation()[index];
 }
EnumNameConstTensorData()
const char* armnnSerializer::EnumNameConstTensorData (ConstTensorData e) inline
Definition at line 686 of file ArmnnSchema_generated.h.
References ConstTensorData_LongData, ConstTensorData_NONE, and EnumNamesConstTensorData().
Referenced by armnnDeserializer::ToConstTensor().
{
   if (flatbuffers::IsOutRange(e, ConstTensorData_NONE, ConstTensorData_LongData)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesConstTensorData()[index];
 }
EnumNameDataLayout()
const char* armnnSerializer::EnumNameDataLayout (DataLayout e) inline
Definition at line 578 of file ArmnnSchema_generated.h.
References DataLayout_NCDHW, DataLayout_NHWC, and EnumNamesDataLayout().
{
   if (flatbuffers::IsOutRange(e, DataLayout_NHWC, DataLayout_NCDHW)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesDataLayout()[index];
 }
EnumNameDataType()
const char* armnnSerializer::EnumNameDataType (DataType e) inline
Definition at line 542 of file ArmnnSchema_generated.h.
References DataType_Float16, DataType_Signed64, and EnumNamesDataType().
Referenced by armnnDeserializer::ToTensorInfo().
{
   if (flatbuffers::IsOutRange(e, DataType_Float16, DataType_Signed64)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesDataType()[index];
 }
EnumNameLayer()
const char* armnnSerializer::EnumNameLayer (Layer e) inline
Definition at line 1474 of file ArmnnSchema_generated.h.
References EnumNamesLayer(), Layer_GatherNdLayer, and Layer_NONE.
{
   if (flatbuffers::IsOutRange(e, Layer_NONE, Layer_GatherNdLayer)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesLayer()[index];
 }
EnumNameLayerType()
const char* armnnSerializer::EnumNameLayerType (LayerType e) inline
Definition at line 937 of file ArmnnSchema_generated.h.
References EnumNamesLayerType(), LayerType_Addition, and LayerType_GatherNd.
{
   if (flatbuffers::IsOutRange(e, LayerType_Addition, LayerType_GatherNd)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesLayerType()[index];
 }
EnumNameLogicalBinaryOperation()
const char* armnnSerializer::EnumNameLogicalBinaryOperation (LogicalBinaryOperation e) inline
Definition at line 1057 of file ArmnnSchema_generated.h.
References EnumNamesLogicalBinaryOperation(), LogicalBinaryOperation_LogicalAnd, and LogicalBinaryOperation_LogicalOr.
{
   if (flatbuffers::IsOutRange(e, LogicalBinaryOperation_LogicalAnd, LogicalBinaryOperation_LogicalOr)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesLogicalBinaryOperation()[index];
 }
EnumNameNormalizationAlgorithmChannel()
const char* armnnSerializer::EnumNameNormalizationAlgorithmChannel (NormalizationAlgorithmChannel e) inline
Definition at line 1180 of file ArmnnSchema_generated.h.
References EnumNamesNormalizationAlgorithmChannel(), NormalizationAlgorithmChannel_Across, and NormalizationAlgorithmChannel_Within.
{
   if (flatbuffers::IsOutRange(e, NormalizationAlgorithmChannel_Across, NormalizationAlgorithmChannel_Within)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesNormalizationAlgorithmChannel()[index];
 }
EnumNameNormalizationAlgorithmMethod()
const char* armnnSerializer::EnumNameNormalizationAlgorithmMethod (NormalizationAlgorithmMethod e) inline
Definition at line 1210 of file ArmnnSchema_generated.h.
References EnumNamesNormalizationAlgorithmMethod(), NormalizationAlgorithmMethod_LocalBrightness, and NormalizationAlgorithmMethod_LocalContrast.
{
   if (flatbuffers::IsOutRange(e, NormalizationAlgorithmMethod_LocalBrightness, NormalizationAlgorithmMethod_LocalContrast)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesNormalizationAlgorithmMethod()[index];
 }
EnumNameOutputShapeRounding()
const char* armnnSerializer::EnumNameOutputShapeRounding (OutputShapeRounding e) inline
Definition at line 1120 of file ArmnnSchema_generated.h.
References EnumNamesOutputShapeRounding(), OutputShapeRounding_Ceiling, and OutputShapeRounding_Floor.
{
   if (flatbuffers::IsOutRange(e, OutputShapeRounding_Floor, OutputShapeRounding_Ceiling)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesOutputShapeRounding()[index];
 }
EnumNamePaddingMethod()
const char* armnnSerializer::EnumNamePaddingMethod (PaddingMethod e) inline
Definition at line 1150 of file ArmnnSchema_generated.h.
References EnumNamesPaddingMethod(), PaddingMethod_Exclude, and PaddingMethod_IgnoreValue.
{
   if (flatbuffers::IsOutRange(e, PaddingMethod_IgnoreValue, PaddingMethod_Exclude)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesPaddingMethod()[index];
 }
EnumNamePaddingMode()
const char* armnnSerializer::EnumNamePaddingMode (PaddingMode e) inline
Definition at line 1243 of file ArmnnSchema_generated.h.
References EnumNamesPaddingMode(), PaddingMode_Constant, and PaddingMode_Symmetric.
{
   if (flatbuffers::IsOutRange(e, PaddingMode_Constant, PaddingMode_Symmetric)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesPaddingMode()[index];
 }
EnumNamePoolingAlgorithm()
const char* armnnSerializer::EnumNamePoolingAlgorithm (PoolingAlgorithm e) inline
Definition at line 1090 of file ArmnnSchema_generated.h.
References EnumNamesPoolingAlgorithm(), PoolingAlgorithm_L2, and PoolingAlgorithm_Max.
{
   if (flatbuffers::IsOutRange(e, PoolingAlgorithm_Max, PoolingAlgorithm_L2)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesPoolingAlgorithm()[index];
 }
EnumNameReduceOperation()
const char* armnnSerializer::EnumNameReduceOperation (ReduceOperation e) inline
Definition at line 617 of file ArmnnSchema_generated.h.
References EnumNamesReduceOperation(), ReduceOperation_Prod, and ReduceOperation_Sum.
{
   if (flatbuffers::IsOutRange(e, ReduceOperation_Sum, ReduceOperation_Prod)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesReduceOperation()[index];
 }
EnumNameResizeMethod()
const char* armnnSerializer::EnumNameResizeMethod (ResizeMethod e) inline
Definition at line 647 of file ArmnnSchema_generated.h.
References EnumNamesResizeMethod(), ResizeMethod_Bilinear, and ResizeMethod_NearestNeighbor.
{
   if (flatbuffers::IsOutRange(e, ResizeMethod_NearestNeighbor, ResizeMethod_Bilinear)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesResizeMethod()[index];
 }
EnumNamesActivationFunction()
const char* const* armnnSerializer::EnumNamesActivationFunction () inline
Definition at line 436 of file ArmnnSchema_generated.h.
Referenced by EnumNameActivationFunction().
{
   static const char * const names[13] = {
     "Sigmoid",
     "TanH",
     "Linear",
     "ReLu",
     "BoundedReLu",
     "SoftReLu",
     "LeakyReLu",
     "Abs",
     "Sqrt",
     "Square",
     "Elu",
     "HardSwish",
     nullptr
   };
   return names;
 }
EnumNamesArgMinMaxFunction()
const char* const* armnnSerializer::EnumNamesArgMinMaxFunction () inline
Definition at line 476 of file ArmnnSchema_generated.h.
Referenced by EnumNameArgMinMaxFunction().
{
   static const char * const names[3] = {
     "Min",
     "Max",
     nullptr
   };
   return names;
 }
EnumNamesComparisonOperation()
const char* const* armnnSerializer::EnumNamesComparisonOperation () inline
Definition at line 966 of file ArmnnSchema_generated.h.
Referenced by EnumNameComparisonOperation().
{
   static const char * const names[7] = {
     "Equal",
     "Greater",
     "GreaterOrEqual",
     "Less",
     "LessOrEqual",
     "NotEqual",
     nullptr
   };
   return names;
 }
EnumNamesConstTensorData()
const char* const* armnnSerializer::EnumNamesConstTensorData () inline
Definition at line 674 of file ArmnnSchema_generated.h.
Referenced by EnumNameConstTensorData().
{
   static const char * const names[6] = {
     "NONE",
     "ByteData",
     "ShortData",
     "IntData",
     "LongData",
     nullptr
   };
   return names;
 }
EnumNamesDataLayout()
const char* const* armnnSerializer::EnumNamesDataLayout () inline
Definition at line 567 of file ArmnnSchema_generated.h.
Referenced by EnumNameDataLayout().
{
   static const char * const names[5] = {
     "NHWC",
     "NCHW",
     "NDHWC",
     "NCDHW",
     nullptr
   };
   return names;
 }
EnumNamesDataType()
const char* const* armnnSerializer::EnumNamesDataType () inline
Definition at line 524 of file ArmnnSchema_generated.h.
Referenced by EnumNameDataType().
{
   static const char * const names[12] = {
     "Float16",
     "Float32",
     "QuantisedAsymm8",
     "Signed32",
     "Boolean",
     "QuantisedSymm16",
     "QAsymmU8",
     "QSymmS16",
     "QAsymmS8",
     "QSymmS8",
     "Signed64",
     nullptr
   };
   return names;
 }
EnumNamesLayer()
const char* const* armnnSerializer::EnumNamesLayer () inline
Definition at line 1398 of file ArmnnSchema_generated.h.
Referenced by EnumNameLayer().
{
   static const char * const names[70] = {
     "NONE",
     "ActivationLayer",
     "AdditionLayer",
     "BatchToSpaceNdLayer",
     "BatchNormalizationLayer",
     "ConstantLayer",
     "Convolution2dLayer",
     "DepthwiseConvolution2dLayer",
     "FullyConnectedLayer",
     "InputLayer",
     "MultiplicationLayer",
     "OutputLayer",
     "PermuteLayer",
     "Pooling2dLayer",
     "ReshapeLayer",
     "SoftmaxLayer",
     "SpaceToBatchNdLayer",
     "DivisionLayer",
     "MinimumLayer",
     "EqualLayer",
     "MaximumLayer",
     "NormalizationLayer",
     "PadLayer",
     "RsqrtLayer",
     "FloorLayer",
     "GreaterLayer",
     "ResizeBilinearLayer",
     "SubtractionLayer",
     "StridedSliceLayer",
     "GatherLayer",
     "MeanLayer",
     "MergerLayer",
     "L2NormalizationLayer",
     "SplitterLayer",
     "DetectionPostProcessLayer",
     "LstmLayer",
     "QuantizedLstmLayer",
     "QuantizeLayer",
     "DequantizeLayer",
     "MergeLayer",
     "SwitchLayer",
     "ConcatLayer",
     "SpaceToDepthLayer",
     "PreluLayer",
     "TransposeConvolution2dLayer",
     "ResizeLayer",
     "StackLayer",
     "AbsLayer",
     "ArgMinMaxLayer",
     "SliceLayer",
     "DepthToSpaceLayer",
     "InstanceNormalizationLayer",
     "LogSoftmaxLayer",
     "ComparisonLayer",
     "StandInLayer",
     "ElementwiseUnaryLayer",
     "TransposeLayer",
     "QLstmLayer",
     "FillLayer",
     "RankLayer",
     "LogicalBinaryLayer",
     "ReduceLayer",
     "CastLayer",
     "ShapeLayer",
     "UnidirectionalSequenceLstmLayer",
     "ChannelShuffleLayer",
     "Convolution3dLayer",
     "Pooling3dLayer",
     "GatherNdLayer",
     nullptr
   };
   return names;
 }
EnumNamesLayerType()
const char* const* armnnSerializer::EnumNamesLayerType () inline
Definition at line 862 of file ArmnnSchema_generated.h.
Referenced by EnumNameLayerType().
{
   static const char * const names[69] = {
     "Addition",
     "Input",
     "Multiplication",
     "Output",
     "Pooling2d",
     "Reshape",
     "Softmax",
     "Convolution2d",
     "DepthwiseConvolution2d",
     "Activation",
     "Permute",
     "FullyConnected",
     "Constant",
     "SpaceToBatchNd",
     "BatchToSpaceNd",
     "Division",
     "Minimum",
     "Equal",
     "Maximum",
     "Normalization",
     "Pad",
     "Rsqrt",
     "Floor",
     "BatchNormalization",
     "Greater",
     "ResizeBilinear",
     "Subtraction",
     "StridedSlice",
     "Gather",
     "Mean",
     "Merger",
     "L2Normalization",
     "Splitter",
     "DetectionPostProcess",
     "Lstm",
     "Quantize",
     "Dequantize",
     "Merge",
     "Switch",
     "Concat",
     "SpaceToDepth",
     "Prelu",
     "TransposeConvolution2d",
     "Resize",
     "Stack",
     "QuantizedLstm",
     "Abs",
     "ArgMinMax",
     "Slice",
     "DepthToSpace",
     "InstanceNormalization",
     "LogSoftmax",
     "Comparison",
     "StandIn",
     "ElementwiseUnary",
     "Transpose",
     "QLstm",
     "Fill",
     "Rank",
     "LogicalBinary",
     "Reduce",
     "Cast",
     "Shape",
     "UnidirectionalSequenceLstm",
     "ChannelShuffle",
     "Convolution3d",
     "Pooling3d",
     "GatherNd",
     nullptr
   };
   return names;
 }
EnumNamesLogicalBinaryOperation()
const char* const* armnnSerializer::EnumNamesLogicalBinaryOperation () inline
Definition at line 1048 of file ArmnnSchema_generated.h.
Referenced by EnumNameLogicalBinaryOperation().
{
   static const char * const names[3] = {
     "LogicalAnd",
     "LogicalOr",
     nullptr
   };
   return names;
 }
EnumNamesNormalizationAlgorithmChannel()
const char* const* armnnSerializer::EnumNamesNormalizationAlgorithmChannel () inline
Definition at line 1171 of file ArmnnSchema_generated.h.
Referenced by EnumNameNormalizationAlgorithmChannel().
{
   static const char * const names[3] = {
     "Across",
     "Within",
     nullptr
   };
   return names;
 }
EnumNamesNormalizationAlgorithmMethod()
const char* const* armnnSerializer::EnumNamesNormalizationAlgorithmMethod () inline
Definition at line 1201 of file ArmnnSchema_generated.h.
Referenced by EnumNameNormalizationAlgorithmMethod().
{
   static const char * const names[3] = {
     "LocalBrightness",
     "LocalContrast",
     nullptr
   };
   return names;
 }
EnumNamesOutputShapeRounding()
const char* const* armnnSerializer::EnumNamesOutputShapeRounding () inline
Definition at line 1111 of file ArmnnSchema_generated.h.
Referenced by EnumNameOutputShapeRounding().
{
   static const char * const names[3] = {
     "Floor",
     "Ceiling",
     nullptr
   };
   return names;
 }
EnumNamesPaddingMethod()
const char* const* armnnSerializer::EnumNamesPaddingMethod () inline
Definition at line 1141 of file ArmnnSchema_generated.h.
Referenced by EnumNamePaddingMethod().
{
   static const char * const names[3] = {
     "IgnoreValue",
     "Exclude",
     nullptr
   };
   return names;
 }
EnumNamesPaddingMode()
const char* const* armnnSerializer::EnumNamesPaddingMode () inline
Definition at line 1233 of file ArmnnSchema_generated.h.
Referenced by EnumNamePaddingMode().
{
   static const char * const names[4] = {
     "Constant",
     "Reflect",
     "Symmetric",
     nullptr
   };
   return names;
 }
EnumNamesPoolingAlgorithm()
const char* const* armnnSerializer::EnumNamesPoolingAlgorithm () inline
Definition at line 1080 of file ArmnnSchema_generated.h.
Referenced by EnumNamePoolingAlgorithm().
{
   static const char * const names[4] = {
     "Max",
     "Average",
     "L2",
     nullptr
   };
   return names;
 }
EnumNamesReduceOperation()
const char* const* armnnSerializer::EnumNamesReduceOperation () inline
Definition at line 605 of file ArmnnSchema_generated.h.
Referenced by EnumNameReduceOperation().
{
   static const char * const names[6] = {
     "Sum",
     "Max",
     "Mean",
     "Min",
     "Prod",
     nullptr
   };
   return names;
 }
EnumNamesResizeMethod()
const char* const* armnnSerializer::EnumNamesResizeMethod () inline
Definition at line 638 of file ArmnnSchema_generated.h.
Referenced by EnumNameResizeMethod().
{
   static const char * const names[3] = {
     "NearestNeighbor",
     "Bilinear",
     nullptr
   };
   return names;
 }
EnumNamesUnaryOperation()
const char* const* armnnSerializer::EnumNamesUnaryOperation () inline
Definition at line 1012 of file ArmnnSchema_generated.h.
Referenced by EnumNameUnaryOperation().
{
   static const char * const names[9] = {
     "Abs",
     "Rsqrt",
     "Sqrt",
     "Exp",
     "Neg",
     "LogicalNot",
     "Log",
     "Sin",
     nullptr
   };
   return names;
 }
EnumNameUnaryOperation()
const char* armnnSerializer::EnumNameUnaryOperation (UnaryOperation e) inline
Definition at line 1027 of file ArmnnSchema_generated.h.
References EnumNamesUnaryOperation(), UnaryOperation_Abs, and UnaryOperation_Sin.
{
   if (flatbuffers::IsOutRange(e, UnaryOperation_Abs, UnaryOperation_Sin)) return "";
   const size_t index = static_cast<size_t>(e);
   return EnumNamesUnaryOperation()[index];
 }
EnumValuesActivationFunction()
const ActivationFunction(& armnnSerializer::EnumValuesActivationFunction ())[12] inline
Definition at line 418 of file ArmnnSchema_generated.h.
References ActivationFunction_Abs, ActivationFunction_BoundedReLu, ActivationFunction_Elu, ActivationFunction_HardSwish, ActivationFunction_LeakyReLu, ActivationFunction_Linear, ActivationFunction_ReLu, ActivationFunction_Sigmoid, ActivationFunction_SoftReLu, ActivationFunction_Sqrt, ActivationFunction_Square, and ActivationFunction_TanH.
{
   static const ActivationFunction values[] = {
     ActivationFunction_Sigmoid,
     ActivationFunction_TanH,
     ActivationFunction_Linear,
     ActivationFunction_ReLu,
     ActivationFunction_BoundedReLu,
     ActivationFunction_SoftReLu,
     ActivationFunction_LeakyReLu,
     ActivationFunction_Abs,
     ActivationFunction_Sqrt,
     ActivationFunction_Square,
     ActivationFunction_Elu,
     ActivationFunction_HardSwish
   };
   return values;
 }
EnumValuesArgMinMaxFunction()
const ArgMinMaxFunction(& armnnSerializer::EnumValuesArgMinMaxFunction ())[2] inline
Definition at line 468 of file ArmnnSchema_generated.h.
References ArgMinMaxFunction_Max, and ArgMinMaxFunction_Min.
{
   static const ArgMinMaxFunction values[] = {
     ArgMinMaxFunction_Min,
     ArgMinMaxFunction_Max
   };
   return values;
 }
EnumValuesComparisonOperation()
const ComparisonOperation(& armnnSerializer::EnumValuesComparisonOperation ())[6] inline
Definition at line 954 of file ArmnnSchema_generated.h.
References ComparisonOperation_Equal, ComparisonOperation_Greater, ComparisonOperation_GreaterOrEqual, ComparisonOperation_Less, ComparisonOperation_LessOrEqual, and ComparisonOperation_NotEqual.
{
   static const ComparisonOperation values[] = {
     ComparisonOperation_Equal,
     ComparisonOperation_Greater,
     ComparisonOperation_GreaterOrEqual,
     ComparisonOperation_Less,
     ComparisonOperation_LessOrEqual,
     ComparisonOperation_NotEqual
   };
   return values;
 }
EnumValuesConstTensorData()
const ConstTensorData(& armnnSerializer::EnumValuesConstTensorData ())[5] inline
Definition at line 663 of file ArmnnSchema_generated.h.
References ConstTensorData_ByteData, ConstTensorData_IntData, ConstTensorData_LongData, ConstTensorData_NONE, and ConstTensorData_ShortData.
{
   static const ConstTensorData values[] = {
     ConstTensorData_NONE,
     ConstTensorData_ByteData,
     ConstTensorData_ShortData,
     ConstTensorData_IntData,
     ConstTensorData_LongData
   };
   return values;
 }
EnumValuesDataLayout()
const DataLayout(& armnnSerializer::EnumValuesDataLayout ())[4] inline
Definition at line 557 of file ArmnnSchema_generated.h.
References DataLayout_NCDHW, DataLayout_NCHW, DataLayout_NDHWC, and DataLayout_NHWC.
{
   static const DataLayout values[] = {
     DataLayout_NHWC,
     DataLayout_NCHW,
     DataLayout_NDHWC,
     DataLayout_NCDHW
   };
   return values;
 }
EnumValuesDataType()
const DataType(& armnnSerializer::EnumValuesDataType ())[11] inline
Definition at line 507 of file ArmnnSchema_generated.h.
References DataType_Boolean, DataType_Float16, DataType_Float32, DataType_QAsymmS8, DataType_QAsymmU8, DataType_QSymmS16, DataType_QSymmS8, DataType_QuantisedAsymm8, DataType_QuantisedSymm16, DataType_Signed32, and DataType_Signed64.
{
   static const DataType values[] = {
     DataType_Float16,
     DataType_Float32,
     DataType_QuantisedAsymm8,
     DataType_Signed32,
     DataType_Boolean,
     DataType_QuantisedSymm16,
     DataType_QAsymmU8,
     DataType_QSymmS16,
     DataType_QAsymmS8,
     DataType_QSymmS8,
     DataType_Signed64
   };
   return values;
 }
EnumValuesLayer()
const Layer(& armnnSerializer::EnumValuesLayer ())[69] inline
Definition at line 1323 of file ArmnnSchema_generated.h.
References Layer_AbsLayer, Layer_ActivationLayer, Layer_AdditionLayer, Layer_ArgMinMaxLayer, Layer_BatchNormalizationLayer, Layer_BatchToSpaceNdLayer, Layer_CastLayer, Layer_ChannelShuffleLayer, Layer_ComparisonLayer, Layer_ConcatLayer, Layer_ConstantLayer, Layer_Convolution2dLayer, Layer_Convolution3dLayer, Layer_DepthToSpaceLayer, Layer_DepthwiseConvolution2dLayer, Layer_DequantizeLayer, Layer_DetectionPostProcessLayer, Layer_DivisionLayer, Layer_ElementwiseUnaryLayer, Layer_EqualLayer, Layer_FillLayer, Layer_FloorLayer, Layer_FullyConnectedLayer, Layer_GatherLayer, Layer_GatherNdLayer, Layer_GreaterLayer, Layer_InputLayer, Layer_InstanceNormalizationLayer, Layer_L2NormalizationLayer, Layer_LogicalBinaryLayer, Layer_LogSoftmaxLayer, Layer_LstmLayer, Layer_MaximumLayer, Layer_MeanLayer, Layer_MergeLayer, Layer_MergerLayer, Layer_MinimumLayer, Layer_MultiplicationLayer, Layer_NONE, Layer_NormalizationLayer, Layer_OutputLayer, Layer_PadLayer, Layer_PermuteLayer, Layer_Pooling2dLayer, Layer_Pooling3dLayer, Layer_PreluLayer, Layer_QLstmLayer, Layer_QuantizedLstmLayer, Layer_QuantizeLayer, Layer_RankLayer, Layer_ReduceLayer, Layer_ReshapeLayer, Layer_ResizeBilinearLayer, Layer_ResizeLayer, Layer_RsqrtLayer, Layer_ShapeLayer, Layer_SliceLayer, Layer_SoftmaxLayer, Layer_SpaceToBatchNdLayer, Layer_SpaceToDepthLayer, Layer_SplitterLayer, Layer_StackLayer, Layer_StandInLayer, Layer_StridedSliceLayer, Layer_SubtractionLayer, Layer_SwitchLayer, Layer_TransposeConvolution2dLayer, Layer_TransposeLayer, and Layer_UnidirectionalSequenceLstmLayer.
{
   static const Layer values[] = {
     Layer_NONE,
     Layer_ActivationLayer,
     Layer_AdditionLayer,
     Layer_BatchToSpaceNdLayer,
     Layer_BatchNormalizationLayer,
     Layer_ConstantLayer,
     Layer_Convolution2dLayer,
     Layer_DepthwiseConvolution2dLayer,
     Layer_FullyConnectedLayer,
     Layer_InputLayer,
     Layer_MultiplicationLayer,
     Layer_OutputLayer,
     Layer_PermuteLayer,
     Layer_Pooling2dLayer,
     Layer_ReshapeLayer,
     Layer_SoftmaxLayer,
     Layer_SpaceToBatchNdLayer,
     Layer_DivisionLayer,
     Layer_MinimumLayer,
     Layer_EqualLayer,
     Layer_MaximumLayer,
     Layer_NormalizationLayer,
     Layer_PadLayer,
     Layer_RsqrtLayer,
     Layer_FloorLayer,
     Layer_GreaterLayer,
     Layer_ResizeBilinearLayer,
     Layer_SubtractionLayer,
     Layer_StridedSliceLayer,
     Layer_GatherLayer,
     Layer_MeanLayer,
     Layer_MergerLayer,
     Layer_L2NormalizationLayer,
     Layer_SplitterLayer,
     Layer_DetectionPostProcessLayer,
     Layer_LstmLayer,
     Layer_QuantizedLstmLayer,
     Layer_QuantizeLayer,
     Layer_DequantizeLayer,
     Layer_MergeLayer,
     Layer_SwitchLayer,
     Layer_ConcatLayer,
     Layer_SpaceToDepthLayer,
     Layer_PreluLayer,
     Layer_TransposeConvolution2dLayer,
     Layer_ResizeLayer,
     Layer_StackLayer,
     Layer_AbsLayer,
     Layer_ArgMinMaxLayer,
     Layer_SliceLayer,
     Layer_DepthToSpaceLayer,
     Layer_InstanceNormalizationLayer,
     Layer_LogSoftmaxLayer,
     Layer_ComparisonLayer,
     Layer_StandInLayer,
     Layer_ElementwiseUnaryLayer,
     Layer_TransposeLayer,
     Layer_QLstmLayer,
     Layer_FillLayer,
     Layer_RankLayer,
     Layer_LogicalBinaryLayer,
     Layer_ReduceLayer,
     Layer_CastLayer,
     Layer_ShapeLayer,
     Layer_UnidirectionalSequenceLstmLayer,
     Layer_ChannelShuffleLayer,
     Layer_Convolution3dLayer,
     Layer_Pooling3dLayer,
     Layer_GatherNdLayer
   };
   return values;
 }
EnumValuesLayerType()
const LayerType(& armnnSerializer::EnumValuesLayerType ())[68] inline
Definition at line 788 of file ArmnnSchema_generated.h.
References LayerType_Abs, LayerType_Activation, LayerType_Addition, LayerType_ArgMinMax, LayerType_BatchNormalization, LayerType_BatchToSpaceNd, LayerType_Cast, LayerType_ChannelShuffle, LayerType_Comparison, LayerType_Concat, LayerType_Constant, LayerType_Convolution2d, LayerType_Convolution3d, LayerType_DepthToSpace, LayerType_DepthwiseConvolution2d, LayerType_Dequantize, LayerType_DetectionPostProcess, LayerType_Division, LayerType_ElementwiseUnary, LayerType_Equal, LayerType_Fill, LayerType_Floor, LayerType_FullyConnected, LayerType_Gather, LayerType_GatherNd, LayerType_Greater, LayerType_Input, LayerType_InstanceNormalization, LayerType_L2Normalization, LayerType_LogicalBinary, LayerType_LogSoftmax, LayerType_Lstm, LayerType_Maximum, LayerType_Mean, LayerType_Merge, LayerType_Merger, LayerType_Minimum, LayerType_Multiplication, LayerType_Normalization, LayerType_Output, LayerType_Pad, LayerType_Permute, LayerType_Pooling2d, LayerType_Pooling3d, LayerType_Prelu, LayerType_QLstm, LayerType_Quantize, LayerType_QuantizedLstm, LayerType_Rank, LayerType_Reduce, LayerType_Reshape, LayerType_Resize, LayerType_ResizeBilinear, LayerType_Rsqrt, LayerType_Shape, LayerType_Slice, LayerType_Softmax, LayerType_SpaceToBatchNd, LayerType_SpaceToDepth, LayerType_Splitter, LayerType_Stack, LayerType_StandIn, LayerType_StridedSlice, LayerType_Subtraction, LayerType_Switch, LayerType_Transpose, LayerType_TransposeConvolution2d, and LayerType_UnidirectionalSequenceLstm.
{
   static const LayerType values[] = {
     LayerType_Addition,
     LayerType_Input,
     LayerType_Multiplication,
     LayerType_Output,
     LayerType_Pooling2d,
     LayerType_Reshape,
     LayerType_Softmax,
     LayerType_Convolution2d,
     LayerType_DepthwiseConvolution2d,
     LayerType_Activation,
     LayerType_Permute,
     LayerType_FullyConnected,
     LayerType_Constant,
     LayerType_SpaceToBatchNd,
     LayerType_BatchToSpaceNd,
     LayerType_Division,
     LayerType_Minimum,
     LayerType_Equal,
     LayerType_Maximum,
     LayerType_Normalization,
     LayerType_Pad,
     LayerType_Rsqrt,
     LayerType_Floor,
     LayerType_BatchNormalization,
     LayerType_Greater,
     LayerType_ResizeBilinear,
     LayerType_Subtraction,
     LayerType_StridedSlice,
     LayerType_Gather,
     LayerType_Mean,
     LayerType_Merger,
     LayerType_L2Normalization,
     LayerType_Splitter,
     LayerType_DetectionPostProcess,
     LayerType_Lstm,
     LayerType_Quantize,
     LayerType_Dequantize,
     LayerType_Merge,
     LayerType_Switch,
     LayerType_Concat,
     LayerType_SpaceToDepth,
     LayerType_Prelu,
     LayerType_TransposeConvolution2d,
     LayerType_Resize,
     LayerType_Stack,
     LayerType_QuantizedLstm,
     LayerType_Abs,
     LayerType_ArgMinMax,
     LayerType_Slice,
     LayerType_DepthToSpace,
     LayerType_InstanceNormalization,
     LayerType_LogSoftmax,
     LayerType_Comparison,
     LayerType_StandIn,
     LayerType_ElementwiseUnary,
     LayerType_Transpose,
     LayerType_QLstm,
     LayerType_Fill,
     LayerType_Rank,
     LayerType_LogicalBinary,
     LayerType_Reduce,
     LayerType_Cast,
     LayerType_Shape,
     LayerType_UnidirectionalSequenceLstm,
     LayerType_ChannelShuffle,
     LayerType_Convolution3d,
     LayerType_Pooling3d,
     LayerType_GatherNd
   };
   return values;
 }
EnumValuesLogicalBinaryOperation()
const LogicalBinaryOperation(& armnnSerializer::EnumValuesLogicalBinaryOperation ())[2] inline
Definition at line 1040 of file ArmnnSchema_generated.h.
References LogicalBinaryOperation_LogicalAnd, and LogicalBinaryOperation_LogicalOr.
{
   static const LogicalBinaryOperation values[] = {
     LogicalBinaryOperation_LogicalAnd,
     LogicalBinaryOperation_LogicalOr
   };
   return values;
 }
EnumValuesNormalizationAlgorithmChannel()
const NormalizationAlgorithmChannel(& armnnSerializer::EnumValuesNormalizationAlgorithmChannel ())[2] inline
Definition at line 1163 of file ArmnnSchema_generated.h.
References NormalizationAlgorithmChannel_Across, and NormalizationAlgorithmChannel_Within.
{
   static const NormalizationAlgorithmChannel values[] = {
     NormalizationAlgorithmChannel_Across,
     NormalizationAlgorithmChannel_Within
   };
   return values;
 }
EnumValuesNormalizationAlgorithmMethod()
const NormalizationAlgorithmMethod(& armnnSerializer::EnumValuesNormalizationAlgorithmMethod ())[2] inline
Definition at line 1193 of file ArmnnSchema_generated.h.
References NormalizationAlgorithmMethod_LocalBrightness, and NormalizationAlgorithmMethod_LocalContrast.
{
   static const NormalizationAlgorithmMethod values[] = {
     NormalizationAlgorithmMethod_LocalBrightness,
     NormalizationAlgorithmMethod_LocalContrast
   };
   return values;
 }
EnumValuesOutputShapeRounding()
const OutputShapeRounding(& armnnSerializer::EnumValuesOutputShapeRounding ())[2] inline
Definition at line 1103 of file ArmnnSchema_generated.h.
References OutputShapeRounding_Ceiling, and OutputShapeRounding_Floor.
{
   static const OutputShapeRounding values[] = {
     OutputShapeRounding_Floor,
     OutputShapeRounding_Ceiling
   };
   return values;
 }
EnumValuesPaddingMethod()
const PaddingMethod(& armnnSerializer::EnumValuesPaddingMethod ())[2] inline
Definition at line 1133 of file ArmnnSchema_generated.h.
References PaddingMethod_Exclude, and PaddingMethod_IgnoreValue.
{
   static const PaddingMethod values[] = {
     PaddingMethod_IgnoreValue,
     PaddingMethod_Exclude
   };
   return values;
 }
EnumValuesPaddingMode()
const PaddingMode(& armnnSerializer::EnumValuesPaddingMode ())[3] inline
Definition at line 1224 of file ArmnnSchema_generated.h.
References PaddingMode_Constant, PaddingMode_Reflect, and PaddingMode_Symmetric.
{
   static const PaddingMode values[] = {
     PaddingMode_Constant,
     PaddingMode_Reflect,
     PaddingMode_Symmetric
   };
   return values;
 }
EnumValuesPoolingAlgorithm()
const PoolingAlgorithm(& armnnSerializer::EnumValuesPoolingAlgorithm ())[3] inline
Definition at line 1071 of file ArmnnSchema_generated.h.
References PoolingAlgorithm_Average, PoolingAlgorithm_L2, and PoolingAlgorithm_Max.
{
   static const PoolingAlgorithm values[] = {
     PoolingAlgorithm_Max,
     PoolingAlgorithm_Average,
     PoolingAlgorithm_L2
   };
   return values;
 }
EnumValuesReduceOperation()
const ReduceOperation(& armnnSerializer::EnumValuesReduceOperation ())[5] inline
Definition at line 594 of file ArmnnSchema_generated.h.
References ReduceOperation_Max, ReduceOperation_Mean, ReduceOperation_Min, ReduceOperation_Prod, and ReduceOperation_Sum.
{
   static const ReduceOperation values[] = {
     ReduceOperation_Sum,
     ReduceOperation_Max,
     ReduceOperation_Mean,
     ReduceOperation_Min,
     ReduceOperation_Prod
   };
   return values;
 }
EnumValuesResizeMethod()
const ResizeMethod(& armnnSerializer::EnumValuesResizeMethod ())[2] inline
Definition at line 630 of file ArmnnSchema_generated.h.
References ResizeMethod_Bilinear, and ResizeMethod_NearestNeighbor.
{
   static const ResizeMethod values[] = {
     ResizeMethod_NearestNeighbor,
     ResizeMethod_Bilinear
   };
   return values;
 }
EnumValuesUnaryOperation()
const UnaryOperation(& armnnSerializer::EnumValuesUnaryOperation ())[8] inline
Definition at line 998 of file ArmnnSchema_generated.h.
References UnaryOperation_Abs, UnaryOperation_Exp, UnaryOperation_Log, UnaryOperation_LogicalNot, UnaryOperation_Neg, UnaryOperation_Rsqrt, UnaryOperation_Sin, and UnaryOperation_Sqrt.
{
   static const UnaryOperation values[] = {
     UnaryOperation_Abs,
     UnaryOperation_Rsqrt,
     UnaryOperation_Sqrt,
     UnaryOperation_Exp,
     UnaryOperation_Neg,
     UnaryOperation_LogicalNot,
     UnaryOperation_Log,
     UnaryOperation_Sin
   };
   return values;
 }
FinishSerializedGraphBuffer()
void armnnSerializer::FinishSerializedGraphBuffer (flatbuffers::FlatBufferBuilder & fbb, flatbuffers::Offset< armnnSerializer::SerializedGraph > root) inline
Definition at line 11426 of file ArmnnSchema_generated.h.
References SerializedGraphIdentifier().
{
   fbb.Finish(root, SerializedGraphIdentifier());
 }
FinishSizePrefixedSerializedGraphBuffer()
void armnnSerializer::FinishSizePrefixedSerializedGraphBuffer (flatbuffers::FlatBufferBuilder & fbb, flatbuffers::Offset< armnnSerializer::SerializedGraph > root) inline
Definition at line 11432 of file ArmnnSchema_generated.h.
References SerializedGraphIdentifier().
{
   fbb.FinishSizePrefixed(root, SerializedGraphIdentifier());
 }
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT()
armnnSerializer::FLATBUFFERS_MANUALLY_ALIGNED_STRUCT (4)
Definition at line 1759 of file ArmnnSchema_generated.h.
References FLATBUFFERS_STRUCT_END().
{
  private:
   uint32_t sourceLayerIndex_;
   uint32_t outputSlotIndex_;
  public:
   Connection() {
     memset(static_cast<void *>(this), 0, sizeof(Connection));
   }
   Connection(uint32_t _sourceLayerIndex, uint32_t _outputSlotIndex)
       : sourceLayerIndex_(flatbuffers::EndianScalar(_sourceLayerIndex)),
         outputSlotIndex_(flatbuffers::EndianScalar(_outputSlotIndex)) {
   }
   uint32_t sourceLayerIndex() const {
     return flatbuffers::EndianScalar(sourceLayerIndex_);
   }
   uint32_t outputSlotIndex() const {
     return flatbuffers::EndianScalar(outputSlotIndex_);
   }
 };
FLATBUFFERS_STRUCT_END()
armnnSerializer::FLATBUFFERS_STRUCT_END (Connection , 8)
Referenced by FLATBUFFERS_MANUALLY_ALIGNED_STRUCT().
GetFlatBufferActivationFunction()
serializer::ActivationFunction armnnSerializer::GetFlatBufferActivationFunction (armnn::ActivationFunction function)
Definition at line 55 of file Serializer.cpp.
References armnn::Abs, ActivationFunction_Abs, ActivationFunction_BoundedReLu, ActivationFunction_Elu, ActivationFunction_HardSwish, ActivationFunction_LeakyReLu, ActivationFunction_Linear, ActivationFunction_ReLu, ActivationFunction_Sigmoid, ActivationFunction_Sqrt, ActivationFunction_Square, ActivationFunction_TanH, armnn::BoundedReLu, armnn::Elu, armnn::HardSwish, armnn::LeakyReLu, armnn::Linear, armnn::ReLu, armnn::Sigmoid, armnn::Sqrt, armnn::Square, and armnn::TanH.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (function)
     {
         case armnn::ActivationFunction::Sigmoid:
             return serializer::ActivationFunction::ActivationFunction_Sigmoid;
         case armnn::ActivationFunction::TanH:
             return serializer::ActivationFunction::ActivationFunction_TanH;
         case armnn::ActivationFunction::Linear:
             return serializer::ActivationFunction::ActivationFunction_Linear;
         case armnn::ActivationFunction::ReLu:
             return serializer::ActivationFunction::ActivationFunction_ReLu;
         case armnn::ActivationFunction::BoundedReLu:
             return serializer::ActivationFunction::ActivationFunction_BoundedReLu;
         case armnn::ActivationFunction::LeakyReLu:
             return serializer::ActivationFunction::ActivationFunction_LeakyReLu;
         case armnn::ActivationFunction::Abs:
             return serializer::ActivationFunction::ActivationFunction_Abs;
         case armnn::ActivationFunction::Sqrt:
             return serializer::ActivationFunction::ActivationFunction_Sqrt;
         case armnn::ActivationFunction::Square:
             return serializer::ActivationFunction::ActivationFunction_Square;
         case armnn::ActivationFunction::Elu:
             return serializer::ActivationFunction::ActivationFunction_Elu;
         case armnn::ActivationFunction::HardSwish:
             return serializer::ActivationFunction::ActivationFunction_HardSwish;
         default:
             return serializer::ActivationFunction::ActivationFunction_Sigmoid;
     }
 }
GetFlatBufferArgMinMaxFunction()
serializer::ArgMinMaxFunction armnnSerializer::GetFlatBufferArgMinMaxFunction (armnn::ArgMinMaxFunction function)
Definition at line 86 of file Serializer.cpp.
References ArgMinMaxFunction_Max, ArgMinMaxFunction_Min, armnn::BFloat16, armnn::Boolean, CreateActivationDescriptor(), CreateActivationLayer(), CreateAdditionLayer(), CreateAnyLayer(), CreateArgMinMaxDescriptor(), CreateArgMinMaxLayer(), CreateBatchNormalizationDescriptor(), CreateBatchNormalizationLayer(), CreateBatchToSpaceNdDescriptor(), CreateBatchToSpaceNdLayer(), CreateBindableLayerBase(), CreateByteData(), CreateCastLayer(), CreateChannelShuffleDescriptor(), CreateChannelShuffleLayer(), CreateComparisonDescriptor(), CreateComparisonLayer(), CreateConcatLayer(), CreateConstantLayer(), CreateConstTensor(), CreateConvolution2dDescriptor(), CreateConvolution2dLayer(), CreateConvolution3dDescriptor(), CreateConvolution3dLayer(), CreateDepthToSpaceDescriptor(), CreateDepthToSpaceLayer(), CreateDepthwiseConvolution2dDescriptor(), CreateDepthwiseConvolution2dLayer(), CreateDequantizeLayer(), CreateDetectionPostProcessDescriptor(), CreateDetectionPostProcessLayer(), CreateDivisionLayer(), CreateElementwiseUnaryDescriptor(), CreateElementwiseUnaryLayer(), CreateFillDescriptor(), CreateFillLayer(), CreateFloorLayer(), CreateFullyConnectedDescriptor(), CreateFullyConnectedLayer(), CreateGatherDescriptor(), CreateGatherLayer(), CreateGatherNdLayer(), CreateInputLayer(), CreateInstanceNormalizationDescriptor(), CreateInstanceNormalizationLayer(), CreateIntData(), CreateL2NormalizationDescriptor(), CreateL2NormalizationLayer(), CreateLayerBase(), CreateLogicalBinaryDescriptor(), CreateLogicalBinaryLayer(), CreateLogSoftmaxDescriptor(), CreateLogSoftmaxLayer(), CreateLongData(), CreateLstmDescriptor(), CreateLstmInputParams(), CreateLstmLayer(), CreateMaximumLayer(), CreateMeanDescriptor(), CreateMeanLayer(), CreateMergeLayer(), CreateMinimumLayer(), CreateMultiplicationLayer(), CreateNormalizationDescriptor(), CreateNormalizationLayer(), CreateOriginsDescriptor(), CreateOutputLayer(), CreatePadDescriptor(), CreatePadLayer(), CreatePermuteDescriptor(), CreatePermuteLayer(), CreatePooling2dDescriptor(), CreatePooling2dLayer(), CreatePooling3dDescriptor(), CreatePooling3dLayer(), CreatePreluLayer(), CreateQLstmDescriptor(), CreateQLstmInputParams(), CreateQLstmLayer(), CreateQuantizedLstmInputParams(), CreateQuantizedLstmLayer(), CreateQuantizeLayer(), CreateRankLayer(), CreateReduceDescriptor(), CreateReduceLayer(), CreateReshapeDescriptor(), CreateReshapeLayer(), CreateResizeDescriptor(), CreateResizeLayer(), CreateShapeLayer(), CreateShortData(), CreateSliceDescriptor(), CreateSliceLayer(), CreateSoftmaxDescriptor(), CreateSoftmaxLayer(), CreateSpaceToBatchNdDescriptor(), CreateSpaceToBatchNdLayer(), CreateSpaceToDepthDescriptor(), CreateSpaceToDepthLayer(), CreateSplitterLayer(), CreateStackDescriptor(), CreateStackLayer(), CreateStandInDescriptor(), CreateStandInLayer(), CreateStridedSliceDescriptor(), CreateStridedSliceLayer(), CreateSubtractionLayer(), CreateSwitchLayer(), CreateTensorInfo(), CreateTransposeConvolution2dDescriptor(), CreateTransposeConvolution2dLayer(), CreateTransposeDescriptor(), CreateTransposeLayer(), CreateUintVector(), CreateUnidirectionalSequenceLstmDescriptor(), CreateUnidirectionalSequenceLstmLayer(), CreateViewsDescriptor(), armnn::Float16, armnn::Float32, OriginsDescriptor::GetConcatAxis(), TensorInfo::GetDataType(), TensorShape::GetDimensionality(), TensorShape::GetDimensionSpecificity(), GetFlatBufferActivationFunction(), GetFlatBufferComparisonOperation(), GetFlatBufferConstTensorData(), GetFlatBufferDataLayout(), GetFlatBufferDataType(), GetFlatBufferLogicalBinaryOperation(), GetFlatBufferNormalizationAlgorithmChannel(), GetFlatBufferNormalizationAlgorithmMethod(), GetFlatBufferOutputShapeRounding(), GetFlatBufferPaddingMethod(), GetFlatBufferPaddingMode(), GetFlatBufferPoolingAlgorithm(), GetFlatBufferReduceOperation(), GetFlatBufferResizeMethod(), GetFlatBufferUnaryOperation(), IConnectableLayer::GetGuid(), BaseTensor< MemoryType >::GetInfo(), BaseTensor< MemoryType >::GetMemoryArea(), IConnectableLayer::GetName(), BaseTensor< MemoryType >::GetNumBytes(), TensorShape::GetNumDimensions(), OriginsDescriptor::GetNumDimensions(), ViewsDescriptor::GetNumDimensions(), OriginsDescriptor::GetNumViews(), ViewsDescriptor::GetNumViews(), ViewsDescriptor::GetOrigins(), TensorInfo::GetQuantizationDim(), TensorInfo::GetQuantizationOffset(), TensorInfo::GetQuantizationScale(), TensorInfo::GetQuantizationScales(), TensorInfo::GetShape(), PermutationVector::GetSize(), OriginsDescriptor::GetViewOrigin(), ViewsDescriptor::GetViewOrigin(), ViewsDescriptor::GetViewSizes(), TensorInfo::HasPerAxisQuantization(), armnn::IgnoreUnused(), Layer_ActivationLayer, Layer_AdditionLayer, Layer_ArgMinMaxLayer, Layer_BatchNormalizationLayer, Layer_BatchToSpaceNdLayer, Layer_CastLayer, Layer_ChannelShuffleLayer, Layer_ComparisonLayer, Layer_ConcatLayer, Layer_ConstantLayer, Layer_Convolution2dLayer, Layer_Convolution3dLayer, Layer_DepthToSpaceLayer, Layer_DepthwiseConvolution2dLayer, Layer_DequantizeLayer, Layer_DetectionPostProcessLayer, Layer_DivisionLayer, Layer_ElementwiseUnaryLayer, Layer_FillLayer, Layer_FloorLayer, Layer_FullyConnectedLayer, Layer_GatherLayer, Layer_GatherNdLayer, Layer_InputLayer, Layer_InstanceNormalizationLayer, Layer_L2NormalizationLayer, Layer_LogicalBinaryLayer, Layer_LogSoftmaxLayer, Layer_LstmLayer, Layer_MaximumLayer, Layer_MeanLayer, Layer_MergeLayer, Layer_MinimumLayer, Layer_MultiplicationLayer, Layer_NormalizationLayer, Layer_OutputLayer, Layer_PadLayer, Layer_PermuteLayer, Layer_Pooling2dLayer, Layer_Pooling3dLayer, Layer_PreluLayer, Layer_QLstmLayer, Layer_QuantizedLstmLayer, Layer_QuantizeLayer, Layer_RankLayer, Layer_ReduceLayer, Layer_ReshapeLayer, Layer_ResizeLayer, Layer_ShapeLayer, Layer_SliceLayer, Layer_SoftmaxLayer, Layer_SpaceToBatchNdLayer, Layer_SpaceToDepthLayer, Layer_SplitterLayer, Layer_StackLayer, Layer_StandInLayer, Layer_StridedSliceLayer, Layer_SubtractionLayer, Layer_SwitchLayer, Layer_TransposeConvolution2dLayer, Layer_TransposeLayer, Layer_UnidirectionalSequenceLstmLayer, LayerType_Activation, LayerType_Addition, LayerType_ArgMinMax, LayerType_BatchNormalization, LayerType_BatchToSpaceNd, LayerType_Cast, LayerType_ChannelShuffle, LayerType_Comparison, LayerType_Concat, LayerType_Constant, LayerType_Convolution2d, LayerType_Convolution3d, LayerType_DepthToSpace, LayerType_DepthwiseConvolution2d, LayerType_Dequantize, LayerType_DetectionPostProcess, LayerType_Division, LayerType_ElementwiseUnary, LayerType_Fill, LayerType_Floor, LayerType_FullyConnected, LayerType_Gather, LayerType_GatherNd, LayerType_Input, LayerType_InstanceNormalization, LayerType_L2Normalization, LayerType_LogicalBinary, LayerType_LogSoftmax, LayerType_Lstm, LayerType_Maximum, LayerType_Mean, LayerType_Merge, LayerType_Minimum, LayerType_Multiplication, LayerType_Normalization, LayerType_Output, LayerType_Pad, LayerType_Permute, LayerType_Pooling2d, LayerType_Pooling3d, LayerType_Prelu, LayerType_QLstm, LayerType_Quantize, LayerType_QuantizedLstm, LayerType_Rank, LayerType_Reduce, LayerType_Reshape, LayerType_Resize, LayerType_Shape, LayerType_Slice, LayerType_Softmax, LayerType_SpaceToBatchNd, LayerType_SpaceToDepth, LayerType_Splitter, LayerType_Stack, LayerType_StandIn, LayerType_StridedSlice, LayerType_Subtraction, LayerType_Switch, LayerType_Transpose, LayerType_UnidirectionalSequenceLstm, ActivationDescriptor::m_A, LstmDescriptor::m_ActivationFunc, ResizeDescriptor::m_AlignCorners, NormalizationDescriptor::m_Alpha, ArgMinMaxDescriptor::m_Axis, SoftmaxDescriptor::m_Axis, GatherDescriptor::m_Axis, MeanDescriptor::m_Axis, StackDescriptor::m_Axis, ChannelShuffleDescriptor::m_Axis, ActivationDescriptor::m_B, SliceDescriptor::m_Begin, StridedSliceDescriptor::m_Begin, StridedSliceDescriptor::m_BeginMask, SoftmaxDescriptor::m_Beta, NormalizationDescriptor::m_Beta, InstanceNormalizationDescriptor::m_Beta, FullyConnectedDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_BiasEnabled, Convolution3dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, TransposeConvolution2dDescriptor::m_BiasEnabled, BatchToSpaceNdDescriptor::m_BlockShape, SpaceToBatchNdDescriptor::m_BlockShape, SpaceToDepthDescriptor::m_BlockSize, QLstmDescriptor::m_CellClip, QLstmDescriptor::m_CellIntermediateScale, LstmDescriptor::m_CifgEnabled, QLstmDescriptor::m_CifgEnabled, LstmDescriptor::m_ClippingThresCell, LstmDescriptor::m_ClippingThresProj, FullyConnectedDescriptor::m_ConstantWeights, BatchToSpaceNdDescriptor::m_Crops, Pooling2dDescriptor::m_DataLayout, Pooling3dDescriptor::m_DataLayout, Convolution2dDescriptor::m_DataLayout, Convolution3dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, NormalizationDescriptor::m_DataLayout, L2NormalizationDescriptor::m_DataLayout, BatchNormalizationDescriptor::m_DataLayout, InstanceNormalizationDescriptor::m_DataLayout, BatchToSpaceNdDescriptor::m_DataLayout, ResizeDescriptor::m_DataLayout, SpaceToBatchNdDescriptor::m_DataLayout, SpaceToDepthDescriptor::m_DataLayout, StridedSliceDescriptor::m_DataLayout, TransposeConvolution2dDescriptor::m_DataLayout, DetectionPostProcessDescriptor::m_DetectionsPerClass, Convolution2dDescriptor::m_DilationX, Convolution3dDescriptor::m_DilationX, DepthwiseConvolution2dDescriptor::m_DilationX, Convolution2dDescriptor::m_DilationY, Convolution3dDescriptor::m_DilationY, DepthwiseConvolution2dDescriptor::m_DilationY, Convolution3dDescriptor::m_DilationZ, PermuteDescriptor::m_DimMappings, TransposeDescriptor::m_DimMappings, StridedSliceDescriptor::m_EllipsisMask, StridedSliceDescriptor::m_End, StridedSliceDescriptor::m_EndMask, L2NormalizationDescriptor::m_Eps, BatchNormalizationDescriptor::m_Eps, InstanceNormalizationDescriptor::m_Eps, QLstmDescriptor::m_ForgetIntermediateScale, ActivationDescriptor::m_Function, ArgMinMaxDescriptor::m_Function, InstanceNormalizationDescriptor::m_Gamma, ResizeDescriptor::m_HalfPixelCenters, QLstmDescriptor::m_HiddenStateScale, QLstmDescriptor::m_HiddenStateZeroPoint, QLstmDescriptor::m_InputIntermediateScale, StackDescriptor::m_InputShape, NormalizationDescriptor::m_K, MeanDescriptor::m_KeepDims, ReduceDescriptor::m_KeepDims, LstmDescriptor::m_LayerNormEnabled, QLstmDescriptor::m_LayerNormEnabled, DetectionPostProcessDescriptor::m_MaxClassesPerDetection, DetectionPostProcessDescriptor::m_MaxDetections, ResizeDescriptor::m_Method, StridedSliceDescriptor::m_NewAxisMask, DetectionPostProcessDescriptor::m_NmsIouThreshold, DetectionPostProcessDescriptor::m_NmsScoreThreshold, NormalizationDescriptor::m_NormChannelType, NormalizationDescriptor::m_NormMethodType, NormalizationDescriptor::m_NormSize, DetectionPostProcessDescriptor::m_NumClasses, ChannelShuffleDescriptor::m_NumGroups, StackDescriptor::m_NumInputs, StandInDescriptor::m_NumInputs, StandInDescriptor::m_NumOutputs, ComparisonDescriptor::m_Operation, ElementwiseUnaryDescriptor::m_Operation, LogicalBinaryDescriptor::m_Operation, QLstmDescriptor::m_OutputIntermediateScale, Pooling2dDescriptor::m_OutputShapeRounding, Pooling3dDescriptor::m_OutputShapeRounding, Pooling3dDescriptor::m_PadBack, Convolution3dDescriptor::m_PadBack, Pooling2dDescriptor::m_PadBottom, Pooling3dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadBottom, Convolution3dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, TransposeConvolution2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PaddingMethod, Pooling3dDescriptor::m_PaddingMethod, PadDescriptor::m_PaddingMode, Pooling3dDescriptor::m_PadFront, Convolution3dDescriptor::m_PadFront, Pooling2dDescriptor::m_PadLeft, Pooling3dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadLeft, Convolution3dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, TransposeConvolution2dDescriptor::m_PadLeft, SpaceToBatchNdDescriptor::m_PadList, PadDescriptor::m_PadList, Pooling2dDescriptor::m_PadRight, Pooling3dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadRight, Convolution3dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, TransposeConvolution2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, Pooling3dDescriptor::m_PadTop, Convolution2dDescriptor::m_PadTop, Convolution3dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, TransposeConvolution2dDescriptor::m_PadTop, PadDescriptor::m_PadValue, LstmDescriptor::m_PeepholeEnabled, QLstmDescriptor::m_PeepholeEnabled, Pooling3dDescriptor::m_PoolDepth, Pooling2dDescriptor::m_PoolHeight, Pooling3dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolType, Pooling3dDescriptor::m_PoolType, Pooling2dDescriptor::m_PoolWidth, Pooling3dDescriptor::m_PoolWidth, QLstmDescriptor::m_ProjectionClip, LstmDescriptor::m_ProjectionEnabled, QLstmDescriptor::m_ProjectionEnabled, ReduceDescriptor::m_ReduceOperation, DetectionPostProcessDescriptor::m_ScaleH, DetectionPostProcessDescriptor::m_ScaleW, DetectionPostProcessDescriptor::m_ScaleX, DetectionPostProcessDescriptor::m_ScaleY, StridedSliceDescriptor::m_ShrinkAxisMask, SliceDescriptor::m_Size, StridedSliceDescriptor::m_Stride, Pooling2dDescriptor::m_StrideX, Pooling3dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideX, Convolution3dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, TransposeConvolution2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, Pooling3dDescriptor::m_StrideY, Convolution2dDescriptor::m_StrideY, Convolution3dDescriptor::m_StrideY, DepthwiseConvolution2dDescriptor::m_StrideY, TransposeConvolution2dDescriptor::m_StrideY, Pooling3dDescriptor::m_StrideZ, Convolution3dDescriptor::m_StrideZ, ResizeDescriptor::m_TargetHeight, ReshapeDescriptor::m_TargetShape, ResizeDescriptor::m_TargetWidth, LstmDescriptor::m_TimeMajor, FullyConnectedDescriptor::m_TransposeWeightMatrix, DetectionPostProcessDescriptor::m_UseRegularNms, FillDescriptor::m_Value, ReduceDescriptor::m_vAxis, armnn::Max, armnn::Min, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, armnn::Signed64, and OptionalReferenceSwitch< IsReference, T >::value().
 {
     switch (function)
     {
         case armnn::ArgMinMaxFunction::Max:
             return serializer::ArgMinMaxFunction::ArgMinMaxFunction_Max;
         case armnn::ArgMinMaxFunction::Min:
         default:
             return serializer::ArgMinMaxFunction::ArgMinMaxFunction_Min;
     }
 }
GetFlatBufferComparisonOperation()
armnnSerializer::ComparisonOperation GetFlatBufferComparisonOperation (armnn::ComparisonOperation comparisonOperation)
Definition at line 11 of file SerializerUtils.cpp.
References ComparisonOperation_Equal, ComparisonOperation_Greater, ComparisonOperation_GreaterOrEqual, ComparisonOperation_Less, ComparisonOperation_LessOrEqual, ComparisonOperation_NotEqual, armnn::Equal, armnn::Greater, armnn::GreaterOrEqual, armnn::Less, armnn::LessOrEqual, and armnn::NotEqual.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (comparisonOperation)
     {
         case armnn::ComparisonOperation::Equal:
             return armnnSerializer::ComparisonOperation::ComparisonOperation_Equal;
         case armnn::ComparisonOperation::Greater:
             return armnnSerializer::ComparisonOperation::ComparisonOperation_Greater;
         case armnn::ComparisonOperation::GreaterOrEqual:
             return armnnSerializer::ComparisonOperation::ComparisonOperation_GreaterOrEqual;
         case armnn::ComparisonOperation::Less:
             return armnnSerializer::ComparisonOperation::ComparisonOperation_Less;
         case armnn::ComparisonOperation::LessOrEqual:
             return armnnSerializer::ComparisonOperation::ComparisonOperation_LessOrEqual;
         case armnn::ComparisonOperation::NotEqual:
         default:
             return armnnSerializer::ComparisonOperation::ComparisonOperation_NotEqual;
     }
 }
GetFlatBufferConstTensorData()
armnnSerializer::ConstTensorData GetFlatBufferConstTensorData (armnn::DataType dataType)
Definition at line 45 of file SerializerUtils.cpp.
References armnn::Boolean, ConstTensorData_ByteData, ConstTensorData_IntData, ConstTensorData_LongData, ConstTensorData_NONE, ConstTensorData_ShortData, armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and armnn::Signed64.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (dataType)
     {
         case armnn::DataType::Float32:
         case armnn::DataType::Signed32:
             return armnnSerializer::ConstTensorData::ConstTensorData_IntData;
         case armnn::DataType::Float16:
         case armnn::DataType::QSymmS16:
             return armnnSerializer::ConstTensorData::ConstTensorData_ShortData;
         case armnn::DataType::QAsymmS8:
         case armnn::DataType::QAsymmU8:
         case armnn::DataType::QSymmS8:
         case armnn::DataType::Boolean:
             return armnnSerializer::ConstTensorData::ConstTensorData_ByteData;
         case armnn::DataType::Signed64:
             return armnnSerializer::ConstTensorData::ConstTensorData_LongData;
         default:
             return armnnSerializer::ConstTensorData::ConstTensorData_NONE;
     }
 }
GetFlatBufferDataLayout()
armnnSerializer::DataLayout GetFlatBufferDataLayout (armnn::DataLayout dataLayout)
Definition at line 94 of file SerializerUtils.cpp.
References DataLayout_NCDHW, DataLayout_NCHW, DataLayout_NDHWC, DataLayout_NHWC, armnn::NCDHW, armnn::NCHW, armnn::NDHWC, and armnn::NHWC.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (dataLayout)
     {
         case armnn::DataLayout::NHWC:
             return armnnSerializer::DataLayout::DataLayout_NHWC;
         case armnn::DataLayout::NDHWC:
             return armnnSerializer::DataLayout::DataLayout_NDHWC;
         case armnn::DataLayout::NCDHW:
             return armnnSerializer::DataLayout::DataLayout_NCDHW;
         case armnn::DataLayout::NCHW:
         default:
             return armnnSerializer::DataLayout::DataLayout_NCHW;
     }
 }
GetFlatBufferDataType()
armnnSerializer::DataType GetFlatBufferDataType (armnn::DataType dataType)
Definition at line 67 of file SerializerUtils.cpp.
References armnn::Boolean, DataType_Boolean, DataType_Float16, DataType_Float32, DataType_QAsymmS8, DataType_QAsymmU8, DataType_QSymmS16, DataType_QSymmS8, DataType_Signed32, DataType_Signed64, armnn::Float16, armnn::Float32, armnn::QAsymmS8, armnn::QAsymmU8, armnn::QSymmS16, armnn::QSymmS8, armnn::Signed32, and armnn::Signed64.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (dataType)
     {
         case armnn::DataType::Float32:
             return armnnSerializer::DataType::DataType_Float32;
         case armnn::DataType::Float16:
             return armnnSerializer::DataType::DataType_Float16;
         case armnn::DataType::Signed32:
             return armnnSerializer::DataType::DataType_Signed32;
         case armnn::DataType::Signed64:
             return armnnSerializer::DataType::DataType_Signed64;
         case armnn::DataType::QSymmS16:
             return armnnSerializer::DataType::DataType_QSymmS16;
         case armnn::DataType::QAsymmS8:
             return armnnSerializer::DataType::DataType_QAsymmS8;
         case armnn::DataType::QAsymmU8:
             return armnnSerializer::DataType::DataType_QAsymmU8;
         case armnn::DataType::QSymmS8:
             return armnnSerializer::DataType::DataType_QSymmS8;
         case armnn::DataType::Boolean:
             return armnnSerializer::DataType::DataType_Boolean;
         default:
             return armnnSerializer::DataType::DataType_Float16;
     }
 }
GetFlatBufferLogicalBinaryOperation()
armnnSerializer::LogicalBinaryOperation GetFlatBufferLogicalBinaryOperation (armnn::LogicalBinaryOperation logicalBinaryOperation)
Definition at line 31 of file SerializerUtils.cpp.
References armnn::LogicalAnd, LogicalBinaryOperation_LogicalAnd, LogicalBinaryOperation_LogicalOr, and armnn::LogicalOr.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (logicalBinaryOperation)
     {
         case armnn::LogicalBinaryOperation::LogicalAnd:
             return armnnSerializer::LogicalBinaryOperation::LogicalBinaryOperation_LogicalAnd;
         case armnn::LogicalBinaryOperation::LogicalOr:
             return armnnSerializer::LogicalBinaryOperation::LogicalBinaryOperation_LogicalOr;
         default:
             throw armnn::InvalidArgumentException("Logical Binary operation unknown");
     }
 }
GetFlatBufferNormalizationAlgorithmChannel()
armnnSerializer::NormalizationAlgorithmChannel GetFlatBufferNormalizationAlgorithmChannel (armnn::NormalizationAlgorithmChannel normalizationAlgorithmChannel)
Definition at line 186 of file SerializerUtils.cpp.
References armnn::Across, NormalizationAlgorithmChannel_Across, NormalizationAlgorithmChannel_Within, and armnn::Within.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (normalizationAlgorithmChannel)
     {
         case armnn::NormalizationAlgorithmChannel::Across:
             return armnnSerializer::NormalizationAlgorithmChannel::NormalizationAlgorithmChannel_Across;
         case armnn::NormalizationAlgorithmChannel::Within:
             return armnnSerializer::NormalizationAlgorithmChannel::NormalizationAlgorithmChannel_Within;
         default:
             return armnnSerializer::NormalizationAlgorithmChannel::NormalizationAlgorithmChannel_Across;
     }
 }
GetFlatBufferNormalizationAlgorithmMethod()
armnnSerializer::NormalizationAlgorithmMethod GetFlatBufferNormalizationAlgorithmMethod (armnn::NormalizationAlgorithmMethod normalizationAlgorithmMethod)
Definition at line 200 of file SerializerUtils.cpp.
References armnn::LocalBrightness, armnn::LocalContrast, NormalizationAlgorithmMethod_LocalBrightness, and NormalizationAlgorithmMethod_LocalContrast.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (normalizationAlgorithmMethod)
     {
         case armnn::NormalizationAlgorithmMethod::LocalBrightness:
             return armnnSerializer::NormalizationAlgorithmMethod::NormalizationAlgorithmMethod_LocalBrightness;
         case armnn::NormalizationAlgorithmMethod::LocalContrast:
             return armnnSerializer::NormalizationAlgorithmMethod::NormalizationAlgorithmMethod_LocalContrast;
         default:
             return armnnSerializer::NormalizationAlgorithmMethod::NormalizationAlgorithmMethod_LocalBrightness;
     }
 }
GetFlatBufferOutputShapeRounding()
armnnSerializer::OutputShapeRounding GetFlatBufferOutputShapeRounding (armnn::OutputShapeRounding outputShapeRounding)
Definition at line 149 of file SerializerUtils.cpp.
References armnn::Ceiling, armnn::Floor, OutputShapeRounding_Ceiling, and OutputShapeRounding_Floor.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (outputShapeRounding)
     {
         case armnn::OutputShapeRounding::Ceiling:
             return armnnSerializer::OutputShapeRounding::OutputShapeRounding_Ceiling;
         case armnn::OutputShapeRounding::Floor:
         default:
             return armnnSerializer::OutputShapeRounding::OutputShapeRounding_Floor;
     }
 }
GetFlatBufferPaddingMethod()
armnnSerializer::PaddingMethod GetFlatBufferPaddingMethod (armnn::PaddingMethod paddingMethod)
Definition at line 161 of file SerializerUtils.cpp.
References armnn::Exclude, armnn::IgnoreValue, PaddingMethod_Exclude, and PaddingMethod_IgnoreValue.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (paddingMethod)
     {
         case armnn::PaddingMethod::IgnoreValue:
             return armnnSerializer::PaddingMethod::PaddingMethod_IgnoreValue;
         case armnn::PaddingMethod::Exclude:
         default:
             return armnnSerializer::PaddingMethod::PaddingMethod_Exclude;
     }
 }
GetFlatBufferPaddingMode()
armnnSerializer::PaddingMode GetFlatBufferPaddingMode (armnn::PaddingMode paddingMode)
Definition at line 173 of file SerializerUtils.cpp.
References PaddingMode_Constant, PaddingMode_Reflect, PaddingMode_Symmetric, armnn::Reflect, and armnn::Symmetric.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (paddingMode)
     {
         case armnn::PaddingMode::Reflect:
             return armnnSerializer::PaddingMode::PaddingMode_Reflect;
         case armnn::PaddingMode::Symmetric:
             return armnnSerializer::PaddingMode::PaddingMode_Symmetric;
         default:
             return armnnSerializer::PaddingMode::PaddingMode_Constant;
     }
 }
GetFlatBufferPoolingAlgorithm()
armnnSerializer::PoolingAlgorithm GetFlatBufferPoolingAlgorithm (armnn::PoolingAlgorithm poolingAlgorithm)
Definition at line 135 of file SerializerUtils.cpp.
References armnn::Average, armnn::L2, armnn::Max, PoolingAlgorithm_Average, PoolingAlgorithm_L2, and PoolingAlgorithm_Max.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (poolingAlgorithm)
     {
         case armnn::PoolingAlgorithm::Average:
             return armnnSerializer::PoolingAlgorithm::PoolingAlgorithm_Average;
         case armnn::PoolingAlgorithm::L2:
             return armnnSerializer::PoolingAlgorithm::PoolingAlgorithm_L2;
         case armnn::PoolingAlgorithm::Max:
         default:
             return armnnSerializer::PoolingAlgorithm::PoolingAlgorithm_Max;
     }
 }
GetFlatBufferReduceOperation()
armnnSerializer::ReduceOperation GetFlatBufferReduceOperation (armnn::ReduceOperation reduceOperation)
Definition at line 227 of file SerializerUtils.cpp.
References armnn::Max, armnn::Mean, armnn::Min, armnn::Prod, ReduceOperation_Max, ReduceOperation_Mean, ReduceOperation_Min, ReduceOperation_Prod, ReduceOperation_Sum, and armnn::Sum.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (reduceOperation)
     {
         case armnn::ReduceOperation::Sum:
             return armnnSerializer::ReduceOperation::ReduceOperation_Sum;
         case armnn::ReduceOperation::Max:
             return armnnSerializer::ReduceOperation::ReduceOperation_Max;
         case armnn::ReduceOperation::Mean:
             return armnnSerializer::ReduceOperation::ReduceOperation_Mean;
         case armnn::ReduceOperation::Min:
             return armnnSerializer::ReduceOperation::ReduceOperation_Min;
         case armnn::ReduceOperation::Prod:
             return armnnSerializer::ReduceOperation::ReduceOperation_Prod;
         default:
             return armnnSerializer::ReduceOperation::ReduceOperation_Sum;
     }
 }
GetFlatBufferResizeMethod()
armnnSerializer::ResizeMethod GetFlatBufferResizeMethod (armnn::ResizeMethod method)
Definition at line 214 of file SerializerUtils.cpp.
References armnn::Bilinear, armnn::NearestNeighbor, ResizeMethod_Bilinear, and ResizeMethod_NearestNeighbor.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (method)
     {
         case armnn::ResizeMethod::NearestNeighbor:
             return armnnSerializer::ResizeMethod_NearestNeighbor;
         case armnn::ResizeMethod::Bilinear:
             return armnnSerializer::ResizeMethod_Bilinear;
         default:
             return armnnSerializer::ResizeMethod_NearestNeighbor;
     }
 }
GetFlatBufferUnaryOperation()
armnnSerializer::UnaryOperation GetFlatBufferUnaryOperation (armnn::UnaryOperation comparisonOperation)
Definition at line 110 of file SerializerUtils.cpp.
References armnn::Abs, armnn::Exp, armnn::Log, armnn::LogicalNot, armnn::Neg, armnn::Rsqrt, armnn::Sin, armnn::Sqrt, UnaryOperation_Abs, UnaryOperation_Exp, UnaryOperation_Log, UnaryOperation_LogicalNot, UnaryOperation_Neg, UnaryOperation_Rsqrt, UnaryOperation_Sin, and UnaryOperation_Sqrt.
Referenced by GetFlatBufferArgMinMaxFunction().
 {
     switch (comparisonOperation)
     {
         case armnn::UnaryOperation::Abs:
             return armnnSerializer::UnaryOperation::UnaryOperation_Abs;
         case armnn::UnaryOperation::Rsqrt:
             return armnnSerializer::UnaryOperation::UnaryOperation_Rsqrt;
         case armnn::UnaryOperation::Sqrt:
             return armnnSerializer::UnaryOperation::UnaryOperation_Sqrt;
         case armnn::UnaryOperation::Exp:
             return armnnSerializer::UnaryOperation::UnaryOperation_Exp;
         case armnn::UnaryOperation::Neg:
             return armnnSerializer::UnaryOperation::UnaryOperation_Neg;
         case armnn::UnaryOperation::LogicalNot:
             return armnnSerializer::UnaryOperation::UnaryOperation_LogicalNot;
         case armnn::UnaryOperation::Log:
             return armnnSerializer::UnaryOperation::UnaryOperation_Log;
         case armnn::UnaryOperation::Sin:
             return armnnSerializer::UnaryOperation::UnaryOperation_Sin;
         default:
             throw armnn::InvalidArgumentException("Unary operation unknown");
     }
 }
GetSerializedGraph()
const armnnSerializer::SerializedGraph* armnnSerializer::GetSerializedGraph (const void * buf) inline
Definition at line 11395 of file ArmnnSchema_generated.h.
Referenced by IDeserializer::DeserializerImpl::LoadGraphFromBinary().
{
   return flatbuffers::GetRoot<armnnSerializer::SerializedGraph>(buf);
 }
GetSizePrefixedSerializedGraph()
const armnnSerializer::SerializedGraph* armnnSerializer::GetSizePrefixedSerializedGraph (const void * buf) inline
Definition at line 11399 of file ArmnnSchema_generated.h.
{
   return flatbuffers::GetSizePrefixedRoot<armnnSerializer::SerializedGraph>(buf);
 }
SerializedGraphBufferHasIdentifier()
bool armnnSerializer::SerializedGraphBufferHasIdentifier (const void * buf) inline
Definition at line 11407 of file ArmnnSchema_generated.h.
References SerializedGraphIdentifier().
{
   return flatbuffers::BufferHasIdentifier(
       buf, SerializedGraphIdentifier());
 }
SerializedGraphExtension()
const char* armnnSerializer::SerializedGraphExtension () inline
Definition at line 11422 of file ArmnnSchema_generated.h.
{
   return "armnn";
 }
SerializedGraphIdentifier()
const char* armnnSerializer::SerializedGraphIdentifier () inline
Definition at line 11403 of file ArmnnSchema_generated.h.
Referenced by FinishSerializedGraphBuffer(), FinishSizePrefixedSerializedGraphBuffer(), SerializedGraphBufferHasIdentifier(), VerifySerializedGraphBuffer(), and VerifySizePrefixedSerializedGraphBuffer().
{
   return "ARMN";
 }
VerifyConstTensorData()
bool VerifyConstTensorData (flatbuffers::Verifier & verifier, const void * obj, ConstTensorData type) inline
Definition at line 11065 of file ArmnnSchema_generated.h.
References ConstTensorData_ByteData, ConstTensorData_IntData, ConstTensorData_LongData, ConstTensorData_NONE, and ConstTensorData_ShortData.
Referenced by FLATBUFFERS_FINAL_CLASS::Verify(), and VerifyConstTensorDataVector().
{
   switch (type) {
     case ConstTensorData_NONE: {
       return true;
     }
     case ConstTensorData_ByteData: {
       auto ptr = reinterpret_cast<const armnnSerializer::ByteData *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case ConstTensorData_ShortData: {
       auto ptr = reinterpret_cast<const armnnSerializer::ShortData *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case ConstTensorData_IntData: {
       auto ptr = reinterpret_cast<const armnnSerializer::IntData *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case ConstTensorData_LongData: {
       auto ptr = reinterpret_cast<const armnnSerializer::LongData *>(obj);
       return verifier.VerifyTable(ptr);
     }
     default: return true;
   }
 }
VerifyConstTensorDataVector()
bool VerifyConstTensorDataVector (flatbuffers::Verifier & verifier, const flatbuffers::Vector< flatbuffers::Offset< void >> * values, const flatbuffers::Vector< uint8_t > * types) inline
Definition at line 11090 of file ArmnnSchema_generated.h.
References VerifyConstTensorData().
{
   if (!values || !types) return !values && !types;
   if (values->size() != types->size()) return false;
   for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
     if (!VerifyConstTensorData(
         verifier,  values->Get(i), types->GetEnum<ConstTensorData>(i))) {
       return false;
     }
   }
   return true;
 }
VerifyLayer()
bool VerifyLayer (flatbuffers::Verifier & verifier, const void * obj, Layer type) inline
Definition at line 11102 of file ArmnnSchema_generated.h.
References Layer_AbsLayer, Layer_ActivationLayer, Layer_AdditionLayer, Layer_ArgMinMaxLayer, Layer_BatchNormalizationLayer, Layer_BatchToSpaceNdLayer, Layer_CastLayer, Layer_ChannelShuffleLayer, Layer_ComparisonLayer, Layer_ConcatLayer, Layer_ConstantLayer, Layer_Convolution2dLayer, Layer_Convolution3dLayer, Layer_DepthToSpaceLayer, Layer_DepthwiseConvolution2dLayer, Layer_DequantizeLayer, Layer_DetectionPostProcessLayer, Layer_DivisionLayer, Layer_ElementwiseUnaryLayer, Layer_EqualLayer, Layer_FillLayer, Layer_FloorLayer, Layer_FullyConnectedLayer, Layer_GatherLayer, Layer_GatherNdLayer, Layer_GreaterLayer, Layer_InputLayer, Layer_InstanceNormalizationLayer, Layer_L2NormalizationLayer, Layer_LogicalBinaryLayer, Layer_LogSoftmaxLayer, Layer_LstmLayer, Layer_MaximumLayer, Layer_MeanLayer, Layer_MergeLayer, Layer_MergerLayer, Layer_MinimumLayer, Layer_MultiplicationLayer, Layer_NONE, Layer_NormalizationLayer, Layer_OutputLayer, Layer_PadLayer, Layer_PermuteLayer, Layer_Pooling2dLayer, Layer_Pooling3dLayer, Layer_PreluLayer, Layer_QLstmLayer, Layer_QuantizedLstmLayer, Layer_QuantizeLayer, Layer_RankLayer, Layer_ReduceLayer, Layer_ReshapeLayer, Layer_ResizeBilinearLayer, Layer_ResizeLayer, Layer_RsqrtLayer, Layer_ShapeLayer, Layer_SliceLayer, Layer_SoftmaxLayer, Layer_SpaceToBatchNdLayer, Layer_SpaceToDepthLayer, Layer_SplitterLayer, Layer_StackLayer, Layer_StandInLayer, Layer_StridedSliceLayer, Layer_SubtractionLayer, Layer_SwitchLayer, Layer_TransposeConvolution2dLayer, Layer_TransposeLayer, and Layer_UnidirectionalSequenceLstmLayer.
Referenced by FLATBUFFERS_FINAL_CLASS::Verify(), and VerifyLayerVector().
{
   switch (type) {
     case Layer_NONE: {
       return true;
     }
     case Layer_ActivationLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ActivationLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_AdditionLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::AdditionLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_BatchToSpaceNdLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::BatchToSpaceNdLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_BatchNormalizationLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::BatchNormalizationLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ConstantLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ConstantLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_Convolution2dLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::Convolution2dLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_DepthwiseConvolution2dLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::DepthwiseConvolution2dLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_FullyConnectedLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::FullyConnectedLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_InputLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::InputLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_MultiplicationLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::MultiplicationLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_OutputLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::OutputLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_PermuteLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::PermuteLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_Pooling2dLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::Pooling2dLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ReshapeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ReshapeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SoftmaxLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SoftmaxLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SpaceToBatchNdLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SpaceToBatchNdLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_DivisionLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::DivisionLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_MinimumLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::MinimumLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_EqualLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::EqualLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_MaximumLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::MaximumLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_NormalizationLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::NormalizationLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_PadLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::PadLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_RsqrtLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::RsqrtLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_FloorLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::FloorLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_GreaterLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::GreaterLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ResizeBilinearLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ResizeBilinearLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SubtractionLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SubtractionLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_StridedSliceLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::StridedSliceLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_GatherLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::GatherLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_MeanLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::MeanLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_MergerLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::MergerLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_L2NormalizationLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::L2NormalizationLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SplitterLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SplitterLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_DetectionPostProcessLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::DetectionPostProcessLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_LstmLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::LstmLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_QuantizedLstmLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::QuantizedLstmLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_QuantizeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::QuantizeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_DequantizeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::DequantizeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_MergeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::MergeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SwitchLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SwitchLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ConcatLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ConcatLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SpaceToDepthLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SpaceToDepthLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_PreluLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::PreluLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_TransposeConvolution2dLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::TransposeConvolution2dLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ResizeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ResizeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_StackLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::StackLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_AbsLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::AbsLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ArgMinMaxLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ArgMinMaxLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_SliceLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::SliceLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_DepthToSpaceLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::DepthToSpaceLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_InstanceNormalizationLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::InstanceNormalizationLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_LogSoftmaxLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::LogSoftmaxLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ComparisonLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ComparisonLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_StandInLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::StandInLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ElementwiseUnaryLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ElementwiseUnaryLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_TransposeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::TransposeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_QLstmLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::QLstmLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_FillLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::FillLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_RankLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::RankLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_LogicalBinaryLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::LogicalBinaryLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ReduceLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ReduceLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_CastLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::CastLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ShapeLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ShapeLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_UnidirectionalSequenceLstmLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::UnidirectionalSequenceLstmLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_ChannelShuffleLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::ChannelShuffleLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_Convolution3dLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::Convolution3dLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_Pooling3dLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::Pooling3dLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     case Layer_GatherNdLayer: {
       auto ptr = reinterpret_cast<const armnnSerializer::GatherNdLayer *>(obj);
       return verifier.VerifyTable(ptr);
     }
     default: return true;
   }
 }
VerifyLayerVector()
bool VerifyLayerVector (flatbuffers::Verifier & verifier, const flatbuffers::Vector< flatbuffers::Offset< void >> * values, const flatbuffers::Vector< uint8_t > * types) inline
Definition at line 11383 of file ArmnnSchema_generated.h.
References VerifyLayer().
{
   if (!values || !types) return !values && !types;
   if (values->size() != types->size()) return false;
   for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
     if (!VerifyLayer(
         verifier,  values->Get(i), types->GetEnum<Layer>(i))) {
       return false;
     }
   }
   return true;
 }
VerifySerializedGraphBuffer()
bool armnnSerializer::VerifySerializedGraphBuffer (flatbuffers::Verifier & verifier) inline
Definition at line 11412 of file ArmnnSchema_generated.h.
References SerializedGraphIdentifier().
{
   return verifier.VerifyBuffer<armnnSerializer::SerializedGraph>(SerializedGraphIdentifier());
 }
VerifySizePrefixedSerializedGraphBuffer()
bool armnnSerializer::VerifySizePrefixedSerializedGraphBuffer (flatbuffers::Verifier & verifier) inline
Definition at line 11417 of file ArmnnSchema_generated.h.
References SerializedGraphIdentifier().
{
   return verifier.VerifySizePrefixedBuffer<armnnSerializer::SerializedGraph>(SerializedGraphIdentifier());
 }