ArmNN: Convolution3dLayerBuilder Struct Reference
Convolution3dLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Convolution3dLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::Convolution3dDescriptor > descriptor)
Convolution3dLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Convolution3dLayerBuilder & operator= (const Convolution3dLayerBuilder &)
flatbuffers::Offset< Convolution3dLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 3336 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Convolution3dLayer Table
Definition at line 3337 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Convolution3dLayerBuilder()
Convolution3dLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3346 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 3340 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateConvolution3dLayer().
{
     fbb_.AddOffset(Convolution3dLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::Convolution3dDescriptor > descriptor) inline
Definition at line 3343 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateConvolution3dLayer().
{
     fbb_.AddOffset(Convolution3dLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<Convolution3dLayer> Finish () inline
Definition at line 3351 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConvolution3dLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Convolution3dLayer>(end);
     return o;
   }
operator=()
Convolution3dLayerBuilder& operator= (const Convolution3dLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 3338 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 3339 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h