ArmNN: TensorInfoBuilder Struct Reference
TensorInfoBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef TensorInfo Table
Public Member Functions
void add_dimensions (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimensions)
void add_dataType (armnnSerializer::DataType dataType)
void add_quantizationScale (float quantizationScale)
void add_quantizationOffset (int32_t quantizationOffset)
void add_quantizationScales (flatbuffers::Offset< flatbuffers::Vector< float >> quantizationScales)
void add_quantizationDim (uint32_t quantizationDim)
void add_dimensionality (uint32_t dimensionality)
void add_dimensionSpecificity (flatbuffers::Offset< flatbuffers::Vector< uint8_t >> dimensionSpecificity)
void add_isConstant (bool isConstant)
TensorInfoBuilder (flatbuffers::FlatBufferBuilder &_fbb)
TensorInfoBuilder & operator= (const TensorInfoBuilder &)
flatbuffers::Offset< TensorInfo > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 1839 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef TensorInfo Table
Definition at line 1840 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
TensorInfoBuilder()
TensorInfoBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 1870 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_dataType()
void add_dataType (armnnSerializer::DataType dataType) inline
Definition at line 1846 of file ArmnnSchema_generated.h.
References VT_DATATYPE.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddElement<int8_t>(TensorInfo::VT_DATATYPE, static_cast<int8_t>(dataType), 0);
   }
add_dimensionality()
void add_dimensionality (uint32_t dimensionality) inline
Definition at line 1861 of file ArmnnSchema_generated.h.
References VT_DIMENSIONALITY.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddElement<uint32_t>(TensorInfo::VT_DIMENSIONALITY, dimensionality, 1);
   }
add_dimensions()
void add_dimensions (flatbuffers::Offset< flatbuffers::Vector< uint32_t >> dimensions) inline
Definition at line 1843 of file ArmnnSchema_generated.h.
References VT_DIMENSIONS.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddOffset(TensorInfo::VT_DIMENSIONS, dimensions);
   }
add_dimensionSpecificity()
void add_dimensionSpecificity (flatbuffers::Offset< flatbuffers::Vector< uint8_t >> dimensionSpecificity) inline
Definition at line 1864 of file ArmnnSchema_generated.h.
References VT_DIMENSIONSPECIFICITY.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddOffset(TensorInfo::VT_DIMENSIONSPECIFICITY, dimensionSpecificity);
   }
add_isConstant()
void add_isConstant (bool isConstant) inline
Definition at line 1867 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddElement<uint8_t>(TensorInfo::VT_ISCONSTANT, static_cast<uint8_t>(isConstant), 0);
   }
add_quantizationDim()
void add_quantizationDim (uint32_t quantizationDim) inline
Definition at line 1858 of file ArmnnSchema_generated.h.
References VT_QUANTIZATIONDIM.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddElement<uint32_t>(TensorInfo::VT_QUANTIZATIONDIM, quantizationDim, 0);
   }
add_quantizationOffset()
void add_quantizationOffset (int32_t quantizationOffset) inline
Definition at line 1852 of file ArmnnSchema_generated.h.
References VT_QUANTIZATIONOFFSET.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddElement<int32_t>(TensorInfo::VT_QUANTIZATIONOFFSET, quantizationOffset, 0);
   }
add_quantizationScale()
void add_quantizationScale (float quantizationScale) inline
Definition at line 1849 of file ArmnnSchema_generated.h.
References VT_QUANTIZATIONSCALE.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddElement<float>(TensorInfo::VT_QUANTIZATIONSCALE, quantizationScale, 1.0f);
   }
add_quantizationScales()
void add_quantizationScales (flatbuffers::Offset< flatbuffers::Vector< float >> quantizationScales) inline
Definition at line 1855 of file ArmnnSchema_generated.h.
References VT_QUANTIZATIONSCALES.
Referenced by armnnSerializer::CreateTensorInfo().
{
     fbb_.AddOffset(TensorInfo::VT_QUANTIZATIONSCALES, quantizationScales);
   }
Finish()
flatbuffers::Offset<TensorInfo> Finish () inline
Definition at line 1875 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateTensorInfo().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<TensorInfo>(end);
     return o;
   }
operator=()
TensorInfoBuilder& operator= (const TensorInfoBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 1841 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 1842 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h