ArmNN: LayerBaseBuilder Struct Reference
LayerBaseBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef LayerBase Table
Public Member Functions
void add_index (uint32_t index)
void add_layerName (flatbuffers::Offset< flatbuffers::String > layerName)
void add_layerType (armnnSerializer::LayerType layerType)
void add_inputSlots (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::InputSlot >>> inputSlots)
void add_outputSlots (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::OutputSlot >>> outputSlots)
LayerBaseBuilder (flatbuffers::FlatBufferBuilder &_fbb)
LayerBaseBuilder & operator= (const LayerBaseBuilder &)
flatbuffers::Offset< LayerBase > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2379 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef LayerBase Table
Definition at line 2380 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
LayerBaseBuilder()
LayerBaseBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2398 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_index()
void add_index (uint32_t index) inline
Definition at line 2383 of file ArmnnSchema_generated.h.
References VT_INDEX.
Referenced by armnnSerializer::CreateLayerBase().
{
     fbb_.AddElement<uint32_t>(LayerBase::VT_INDEX, index, 0);
   }
add_inputSlots()
void add_inputSlots (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::InputSlot >>> inputSlots) inline
Definition at line 2392 of file ArmnnSchema_generated.h.
References VT_INPUTSLOTS.
Referenced by armnnSerializer::CreateLayerBase().
{
     fbb_.AddOffset(LayerBase::VT_INPUTSLOTS, inputSlots);
   }
add_layerName()
void add_layerName (flatbuffers::Offset< flatbuffers::String > layerName) inline
Definition at line 2386 of file ArmnnSchema_generated.h.
References VT_LAYERNAME.
Referenced by armnnSerializer::CreateLayerBase().
{
     fbb_.AddOffset(LayerBase::VT_LAYERNAME, layerName);
   }
add_layerType()
void add_layerType (armnnSerializer::LayerType layerType) inline
Definition at line 2389 of file ArmnnSchema_generated.h.
References VT_LAYERTYPE.
Referenced by armnnSerializer::CreateLayerBase().
{
     fbb_.AddElement<uint32_t>(LayerBase::VT_LAYERTYPE, static_cast<uint32_t>(layerType), 0);
   }
add_outputSlots()
void add_outputSlots (flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< armnnSerializer::OutputSlot >>> outputSlots) inline
Definition at line 2395 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLayerBase().
{
     fbb_.AddOffset(LayerBase::VT_OUTPUTSLOTS, outputSlots);
   }
Finish()
flatbuffers::Offset<LayerBase> Finish () inline
Definition at line 2403 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLayerBase().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<LayerBase>(end);
     return o;
   }
operator=()
LayerBaseBuilder& operator= (const LayerBaseBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2381 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2382 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h