ArmNN: LstmInputParamsBuilder Struct Reference
LstmInputParamsBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef LstmInputParams Table
Public Member Functions
void add_inputToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights)
void add_inputToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights)
void add_inputToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights)
void add_recurrentToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights)
void add_recurrentToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights)
void add_recurrentToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights)
void add_forgetGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias)
void add_cellBias (flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias)
void add_outputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias)
void add_inputToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights)
void add_recurrentToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights)
void add_cellToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights)
void add_inputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias)
void add_projectionWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights)
void add_projectionBias (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias)
void add_cellToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights)
void add_cellToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights)
void add_inputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights)
void add_forgetLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights)
void add_cellLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights)
void add_outputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights)
LstmInputParamsBuilder (flatbuffers::FlatBufferBuilder &_fbb)
LstmInputParamsBuilder & operator= (const LstmInputParamsBuilder &)
flatbuffers::Offset< LstmInputParams > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 8189 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef LstmInputParams Table
Definition at line 8190 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
LstmInputParamsBuilder()
LstmInputParamsBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 8256 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_cellBias()
void add_cellBias (flatbuffers::Offset< armnnSerializer::ConstTensor > cellBias) inline
Definition at line 8214 of file ArmnnSchema_generated.h.
References VT_CELLBIAS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_CELLBIAS, cellBias);
   }
add_cellLayerNormWeights()
void add_cellLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellLayerNormWeights) inline
Definition at line 8250 of file ArmnnSchema_generated.h.
References VT_CELLLAYERNORMWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_CELLLAYERNORMWEIGHTS, cellLayerNormWeights);
   }
add_cellToForgetWeights()
void add_cellToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToForgetWeights) inline
Definition at line 8238 of file ArmnnSchema_generated.h.
References VT_CELLTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_CELLTOFORGETWEIGHTS, cellToForgetWeights);
   }
add_cellToInputWeights()
void add_cellToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToInputWeights) inline
Definition at line 8226 of file ArmnnSchema_generated.h.
References VT_CELLTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_CELLTOINPUTWEIGHTS, cellToInputWeights);
   }
add_cellToOutputWeights()
void add_cellToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > cellToOutputWeights) inline
Definition at line 8241 of file ArmnnSchema_generated.h.
References VT_CELLTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_CELLTOOUTPUTWEIGHTS, cellToOutputWeights);
   }
add_forgetGateBias()
void add_forgetGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetGateBias) inline
Definition at line 8211 of file ArmnnSchema_generated.h.
References VT_FORGETGATEBIAS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_FORGETGATEBIAS, forgetGateBias);
   }
add_forgetLayerNormWeights()
void add_forgetLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > forgetLayerNormWeights) inline
Definition at line 8247 of file ArmnnSchema_generated.h.
References VT_FORGETLAYERNORMWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_FORGETLAYERNORMWEIGHTS, forgetLayerNormWeights);
   }
add_inputGateBias()
void add_inputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > inputGateBias) inline
Definition at line 8229 of file ArmnnSchema_generated.h.
References VT_INPUTGATEBIAS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_INPUTGATEBIAS, inputGateBias);
   }
add_inputLayerNormWeights()
void add_inputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputLayerNormWeights) inline
Definition at line 8244 of file ArmnnSchema_generated.h.
References VT_INPUTLAYERNORMWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_INPUTLAYERNORMWEIGHTS, inputLayerNormWeights);
   }
add_inputToCellWeights()
void add_inputToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToCellWeights) inline
Definition at line 8196 of file ArmnnSchema_generated.h.
References VT_INPUTTOCELLWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_INPUTTOCELLWEIGHTS, inputToCellWeights);
   }
add_inputToForgetWeights()
void add_inputToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToForgetWeights) inline
Definition at line 8193 of file ArmnnSchema_generated.h.
References VT_INPUTTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_INPUTTOFORGETWEIGHTS, inputToForgetWeights);
   }
add_inputToInputWeights()
void add_inputToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToInputWeights) inline
Definition at line 8220 of file ArmnnSchema_generated.h.
References VT_INPUTTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_INPUTTOINPUTWEIGHTS, inputToInputWeights);
   }
add_inputToOutputWeights()
void add_inputToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > inputToOutputWeights) inline
Definition at line 8199 of file ArmnnSchema_generated.h.
References VT_INPUTTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_INPUTTOOUTPUTWEIGHTS, inputToOutputWeights);
   }
add_outputGateBias()
void add_outputGateBias (flatbuffers::Offset< armnnSerializer::ConstTensor > outputGateBias) inline
Definition at line 8217 of file ArmnnSchema_generated.h.
References VT_OUTPUTGATEBIAS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_OUTPUTGATEBIAS, outputGateBias);
   }
add_outputLayerNormWeights()
void add_outputLayerNormWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > outputLayerNormWeights) inline
Definition at line 8253 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_OUTPUTLAYERNORMWEIGHTS, outputLayerNormWeights);
   }
add_projectionBias()
void add_projectionBias (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionBias) inline
Definition at line 8235 of file ArmnnSchema_generated.h.
References VT_PROJECTIONBIAS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_PROJECTIONBIAS, projectionBias);
   }
add_projectionWeights()
void add_projectionWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > projectionWeights) inline
Definition at line 8232 of file ArmnnSchema_generated.h.
References VT_PROJECTIONWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_PROJECTIONWEIGHTS, projectionWeights);
   }
add_recurrentToCellWeights()
void add_recurrentToCellWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToCellWeights) inline
Definition at line 8205 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOCELLWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_RECURRENTTOCELLWEIGHTS, recurrentToCellWeights);
   }
add_recurrentToForgetWeights()
void add_recurrentToForgetWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToForgetWeights) inline
Definition at line 8202 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOFORGETWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_RECURRENTTOFORGETWEIGHTS, recurrentToForgetWeights);
   }
add_recurrentToInputWeights()
void add_recurrentToInputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToInputWeights) inline
Definition at line 8223 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOINPUTWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_RECURRENTTOINPUTWEIGHTS, recurrentToInputWeights);
   }
add_recurrentToOutputWeights()
void add_recurrentToOutputWeights (flatbuffers::Offset< armnnSerializer::ConstTensor > recurrentToOutputWeights) inline
Definition at line 8208 of file ArmnnSchema_generated.h.
References VT_RECURRENTTOOUTPUTWEIGHTS.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     fbb_.AddOffset(LstmInputParams::VT_RECURRENTTOOUTPUTWEIGHTS, recurrentToOutputWeights);
   }
Finish()
flatbuffers::Offset<LstmInputParams> Finish () inline
Definition at line 8261 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateLstmInputParams().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<LstmInputParams>(end);
     return o;
   }
operator=()
LstmInputParamsBuilder& operator= (const LstmInputParamsBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 8191 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 8192 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h