ArmNN: L2NormalizationDescriptorBuilder Struct Reference
L2NormalizationDescriptorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef L2NormalizationDescriptor Table
Public Member Functions
void add_dataLayout (armnnSerializer::DataLayout dataLayout)
void add_eps (float eps)
L2NormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
L2NormalizationDescriptorBuilder & operator= (const L2NormalizationDescriptorBuilder &)
flatbuffers::Offset< L2NormalizationDescriptor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 4638 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef L2NormalizationDescriptor Table
Definition at line 4639 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
L2NormalizationDescriptorBuilder()
L2NormalizationDescriptorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 4648 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_dataLayout()
void add_dataLayout (armnnSerializer::DataLayout dataLayout) inline
Definition at line 4642 of file ArmnnSchema_generated.h.
References VT_DATALAYOUT.
Referenced by armnnSerializer::CreateL2NormalizationDescriptor().
{
     fbb_.AddElement<int8_t>(L2NormalizationDescriptor::VT_DATALAYOUT, static_cast<int8_t>(dataLayout), 1);
   }
add_eps()
void add_eps (float eps) inline
Definition at line 4645 of file ArmnnSchema_generated.h.
References VT_EPS.
Referenced by armnnSerializer::CreateL2NormalizationDescriptor().
{
     fbb_.AddElement<float>(L2NormalizationDescriptor::VT_EPS, eps, 1e-12f);
   }
Finish()
flatbuffers::Offset<L2NormalizationDescriptor> Finish () inline
Definition at line 4653 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateL2NormalizationDescriptor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<L2NormalizationDescriptor>(end);
     return o;
   }
operator=()
L2NormalizationDescriptorBuilder& operator= (const L2NormalizationDescriptorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 4640 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 4641 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h