ArmNN: AnyLayerBuilder Struct Reference
AnyLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef AnyLayer Table
Public Member Functions
void add_layer_type (armnnSerializer::Layer layer_type)
void add_layer (flatbuffers::Offset< void > layer)
AnyLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
AnyLayerBuilder & operator= (const AnyLayerBuilder &)
flatbuffers::Offset< AnyLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 10877 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef AnyLayer Table
Definition at line 10878 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
AnyLayerBuilder()
AnyLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 10887 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_layer()
void add_layer (flatbuffers::Offset< void > layer) inline
Definition at line 10884 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateAnyLayer().
{
     fbb_.AddOffset(AnyLayer::VT_LAYER, layer);
   }
add_layer_type()
void add_layer_type (armnnSerializer::Layer layer_type) inline
Definition at line 10881 of file ArmnnSchema_generated.h.
References VT_LAYER_TYPE.
Referenced by armnnSerializer::CreateAnyLayer().
{
     fbb_.AddElement<uint8_t>(AnyLayer::VT_LAYER_TYPE, static_cast<uint8_t>(layer_type), 0);
   }
Finish()
flatbuffers::Offset<AnyLayer> Finish () inline
Definition at line 10892 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateAnyLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<AnyLayer>(end);
     return o;
   }
operator=()
AnyLayerBuilder& operator= (const AnyLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 10879 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 10880 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h