var searchData=
[
  ['neonabsworkload_5798',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.html',1,'armnn']]],
  ['neonactivationworkload_5799',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.html',1,'armnn']]],
  ['neonadditionworkload_5800',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.html',1,'armnn']]],
  ['neonargminmaxworkload_5801',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.html',1,'armnn']]],
  ['neonbackend_5802',['NeonBackend',['../classarmnn_1_1_neon_backend.html',1,'armnn']]],
  ['neonbackendmodelcontext_5803',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.html',1,'armnn']]],
  ['neonbaseworkload_5804',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e_5805',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e_5806',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e_5807',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5808',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5809',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5810',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5811',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e_5812',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5813',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5814',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e_5815',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e_5816',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5817',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5818',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5819',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5820',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5821',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5822',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e_5823',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5824',['NeonBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5825',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e_5826',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5827',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fusedqueuedescriptor_20_3e_5828',['NeonBaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e_5829',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e_5830',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5831',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5832',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5833',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e_5834',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e_5835',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e_5836',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e_5837',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e_5838',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e_5839',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_5840',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_5841',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e_5842',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e_5843',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5844',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e_5845',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e_5846',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e_5847',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e_5848',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e_5849',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e_5850',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e_5851',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e_5852',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5853',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5854',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e_5855',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e_5856',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_5857',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e_5858',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5859',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e_5860',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5861',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbatchmatmulworkload_5862',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.html',1,'armnn']]],
  ['neonbatchnormalizationworkload_5863',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.html',1,'armnn']]],
  ['neonbatchtospacendworkload_5864',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.html',1,'armnn']]],
  ['neoncastworkload_5865',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.html',1,'armnn']]],
  ['neonchannelshuffleworkload_5866',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.html',1,'armnn']]],
  ['neoncomparisonworkload_5867',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.html',1,'armnn']]],
  ['neonconcatworkload_5868',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.html',1,'armnn']]],
  ['neonconstantworkload_5869',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.html',1,'armnn']]],
  ['neonconvertfp16tofp32workload_5870',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['neonconvertfp32tofp16workload_5871',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['neonconvolution2dworkload_5872',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.html',1,'armnn']]],
  ['neonconvolution3dworkload_5873',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.html',1,'armnn']]],
  ['neondepthtospaceworkload_5874',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.html',1,'armnn']]],
  ['neondepthwiseconvolutionworkload_5875',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.html',1,'armnn']]],
  ['neondequantizeworkload_5876',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.html',1,'armnn']]],
  ['neondetectionpostprocessworkload_5877',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.html',1,'armnn']]],
  ['neondivisionworkload_5878',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.html',1,'armnn']]],
  ['neonelementwisebinaryworkload_5879',['NeonElementwiseBinaryWorkload',['../classarmnn_1_1_neon_elementwise_binary_workload.html',1,'armnn']]],
  ['neonexpworkload_5880',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.html',1,'armnn']]],
  ['neonfillworkload_5881',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.html',1,'armnn']]],
  ['neonfloorfloatworkload_5882',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.html',1,'armnn']]],
  ['neonfullyconnectedworkload_5883',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.html',1,'armnn']]],
  ['neonfusedworkload_5884',['NeonFusedWorkload',['../classarmnn_1_1_neon_fused_workload.html',1,'armnn']]],
  ['neongatherndworkload_5885',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.html',1,'armnn']]],
  ['neongatherworkload_5886',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.html',1,'armnn']]],
  ['neoninstancenormalizationworkload_5887',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.html',1,'armnn']]],
  ['neoninterceptorscheduler_5888',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.html',1,'armnn']]],
  ['neonl2normalizationfloatworkload_5889',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.html',1,'armnn']]],
  ['neonlayersupport_5890',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.html',1,'armnn']]],
  ['neonlogicalandworkload_5891',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.html',1,'armnn']]],
  ['neonlogicalnotworkload_5892',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.html',1,'armnn']]],
  ['neonlogicalorworkload_5893',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.html',1,'armnn']]],
  ['neonlogsoftmaxworkload_5894',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.html',1,'armnn']]],
  ['neonlogworkload_5895',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.html',1,'armnn']]],
  ['neonlstmfloatworkload_5896',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.html',1,'armnn']]],
  ['neonmaximumworkload_5897',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.html',1,'armnn']]],
  ['neonmeanworkload_5898',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.html',1,'armnn']]],
  ['neonmemorymanager_5899',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.html',1,'armnn']]],
  ['neonminimumworkload_5900',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.html',1,'armnn']]],
  ['neonmultiplicationworkload_5901',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.html',1,'armnn']]],
  ['neonnegworkload_5902',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.html',1,'armnn']]],
  ['neonnormalizationfloatworkload_5903',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.html',1,'armnn']]],
  ['neonpadworkload_5904',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.html',1,'armnn']]],
  ['neonpermuteworkload_5905',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.html',1,'armnn']]],
  ['neonpooling2dworkload_5906',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.html',1,'armnn']]],
  ['neonpooling3dworkload_5907',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.html',1,'armnn']]],
  ['neonpreluworkload_5908',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.html',1,'armnn']]],
  ['neonqlstmworkload_5909',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.html',1,'armnn']]],
  ['neonquantizedlstmworkload_5910',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.html',1,'armnn']]],
  ['neonquantizeworkload_5911',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.html',1,'armnn']]],
  ['neonrankworkload_5912',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.html',1,'armnn']]],
  ['neonreduceworkload_5913',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.html',1,'armnn']]],
  ['neonreshapeworkload_5914',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.html',1,'armnn']]],
  ['neonresizeworkload_5915',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.html',1,'armnn']]],
  ['neonreversev2workload_5916',['NeonReverseV2Workload',['../classarmnn_1_1_neon_reverse_v2_workload.html',1,'armnn']]],
  ['neonrsqrtworkload_5917',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.html',1,'armnn']]],
  ['neonsinworkload_5918',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.html',1,'armnn']]],
  ['neonsliceworkload_5919',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.html',1,'armnn']]],
  ['neonsoftmaxworkload_5920',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.html',1,'armnn']]],
  ['neonspacetobatchndworkload_5921',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.html',1,'armnn']]],
  ['neonspacetodepthworkload_5922',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.html',1,'armnn']]],
  ['neonsplitterworkload_5923',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.html',1,'armnn']]],
  ['neonsqrtworkload_5924',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.html',1,'armnn']]],
  ['neonstackworkload_5925',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.html',1,'armnn']]],
  ['neonstridedsliceworkload_5926',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.html',1,'armnn']]],
  ['neonsubtensorhandle_5927',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.html',1,'armnn']]],
  ['neonsubtractionworkload_5928',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.html',1,'armnn']]],
  ['neontensordecorator_5929',['NeonTensorDecorator',['../classarmnn_1_1_neon_tensor_decorator.html',1,'armnn']]],
  ['neontensorhandle_5930',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.html',1,'armnn']]],
  ['neontensorhandledecorator_5931',['NeonTensorHandleDecorator',['../classarmnn_1_1_neon_tensor_handle_decorator.html',1,'armnn']]],
  ['neontensorhandlefactory_5932',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.html',1,'armnn']]],
  ['neontileworkload_5933',['NeonTileWorkload',['../classarmnn_1_1_neon_tile_workload.html',1,'armnn']]],
  ['neontimer_5934',['NeonTimer',['../classarmnn_1_1_neon_timer.html',1,'armnn']]],
  ['neontransposeconvolution2dworkload_5935',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.html',1,'armnn']]],
  ['neontransposeworkload_5936',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload_5937',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload_5938',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['neonworkloadfactory_5939',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.html',1,'armnn']]],
  ['networkimpl_5940',['NetworkImpl',['../classarmnn_1_1_network_impl.html',1,'armnn']]],
  ['nodecontent_5941',['NodeContent',['../classarmnn_1_1_node_content.html',1,'armnn']]],
  ['normalizationdescriptor_5942',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.html',1,'armnn']]],
  ['normalizationlayer_5943',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.html',1,'armnn']]],
  ['normalizationqueuedescriptor_5944',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.html',1,'armnn']]],
  ['nothrowstrategy_5945',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.html',1,'armnn']]],
  ['nulldescriptor_5946',['NullDescriptor',['../structarmnn_1_1_null_descriptor.html',1,'armnn']]],
  ['nullpointerexception_5947',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.html',1,'armnn']]],
  ['nullworkload_5948',['NullWorkload',['../classarmnn_1_1_null_workload.html',1,'armnn']]]
];
