var searchData=
[
  ['onnxparserimpl_5949',['OnnxParserImpl',['../classarmnn_onnx_parser_1_1_onnx_parser_impl.html',1,'armnnOnnxParser']]],
  ['opencltimer_5950',['OpenClTimer',['../classarmnn_1_1_open_cl_timer.html',1,'armnn']]],
  ['optimization_5951',['Optimization',['../classarmnn_1_1_optimization.html',1,'armnn']]],
  ['optimizationresult_5952',['OptimizationResult',['../structarmnn_1_1_optimization_result.html',1,'armnn']]],
  ['optimizationviews_5953',['OptimizationViews',['../classarmnn_1_1_optimization_views.html',1,'armnn']]],
  ['optimizeconsecutivereshapesimpl_5954',['OptimizeConsecutiveReshapesImpl',['../classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl.html',1,'armnn::optimizations']]],
  ['optimizednetworkimpl_5955',['OptimizedNetworkImpl',['../classarmnn_1_1_optimized_network_impl.html',1,'armnn']]],
  ['optimizeforconnection_5956',['OptimizeForConnection',['../classarmnn_1_1_optimize_for_connection.html',1,'armnn']]],
  ['optimizeforconnectionimpl_5957',['OptimizeForConnectionImpl',['../classarmnn_1_1_optimize_for_connection_impl.html',1,'armnn']]],
  ['optimizeforexclusiveconnection_5958',['OptimizeForExclusiveConnection',['../classarmnn_1_1_optimize_for_exclusive_connection.html',1,'armnn']]],
  ['optimizeforexclusiveconnectionimpl_5959',['OptimizeForExclusiveConnectionImpl',['../classarmnn_1_1_optimize_for_exclusive_connection_impl.html',1,'armnn']]],
  ['optimizefortype_5960',['OptimizeForType',['../classarmnn_1_1_optimize_for_type.html',1,'armnn']]],
  ['optimizefortypeimpl_5961',['OptimizeForTypeImpl',['../classarmnn_1_1_optimize_for_type_impl.html',1,'armnn']]],
  ['optimizefortypeimpl_3c_20basetype_2c_20optimizeforconnectionimpl_3c_20basetype_2c_20childtype_2c_20wrapped_20_3e_20_3e_5962',['OptimizeForTypeImpl&lt; BaseType, OptimizeForConnectionImpl&lt; BaseType, ChildType, Wrapped &gt; &gt;',['../classarmnn_1_1_optimize_for_type_impl.html',1,'armnn']]],
  ['optimizefortypeimpl_3c_20basetype_2c_20optimizeforexclusiveconnectionimpl_3c_20basetype_2c_20childtype_2c_20wrapped_20_3e_20_3e_5963',['OptimizeForTypeImpl&lt; BaseType, OptimizeForExclusiveConnectionImpl&lt; BaseType, ChildType, Wrapped &gt; &gt;',['../classarmnn_1_1_optimize_for_type_impl.html',1,'armnn']]],
  ['optimizefortypeimpl_3c_20layer_2c_20wrapped_20_3e_5964',['OptimizeForTypeImpl&lt; Layer, Wrapped &gt;',['../classarmnn_1_1_optimize_for_type_impl_3_01_layer_00_01_wrapped_01_4.html',1,'armnn']]],
  ['optimizeinverseconversionsimpl_5965',['OptimizeInverseConversionsImpl',['../classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl.html',1,'armnn::optimizations']]],
  ['optimizeinversepermutesimpl_5966',['OptimizeInversePermutesImpl',['../classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl.html',1,'armnn::optimizations']]],
  ['optimizer_5967',['Optimizer',['../classarmnn_1_1_optimizer.html',1,'armnn']]],
  ['optimizeroptions_5968',['OptimizerOptions',['../structarmnn_1_1_optimizer_options.html',1,'armnn']]],
  ['optimizeroptionsopaque_5969',['OptimizerOptionsOpaque',['../classarmnn_1_1_optimizer_options_opaque.html',1,'armnn']]],
  ['optimizeroptionsopaqueimpl_5970',['OptimizerOptionsOpaqueImpl',['../structarmnn_1_1_optimizer_options_opaque_impl.html',1,'armnn']]],
  ['optional_5971',['Optional',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_5972',['Optional&lt; arm::pipe::IProfilingService &amp; &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_5973',['Optional&lt; arm::pipe::ProfilingGuid &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20armnn_3a_3abackendid_20_3e_5974',['Optional&lt; armnn::BackendId &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20armnn_3a_3atensorinfo_20_3e_5975',['Optional&lt; armnn::TensorInfo &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_5976',['Optional&lt; armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20int32_5ft_20_3e_5977',['Optional&lt; int32_t &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20std_3a_3astring_20_3e_5978',['Optional&lt; std::string &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_5979',['Optional&lt; std::vector&lt; armnn::MemoryInfo &gt; &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optional_3c_20unsigned_20int_20_3e_5980',['Optional&lt; unsigned int &gt;',['../classarmnn_1_1_optional.html',1,'armnn']]],
  ['optionalbase_5981',['OptionalBase',['../classarmnn_1_1_optional_base.html',1,'armnn']]],
  ['optionalreferenceswitch_5982',['OptionalReferenceSwitch',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_3a_3avalue_2c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_5983',['OptionalReferenceSwitch&lt; std::is_reference&lt; arm::pipe::IProfilingService &amp; &gt;::value, arm::pipe::IProfilingService &amp; &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_3a_3avalue_2c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_5984',['OptionalReferenceSwitch&lt; std::is_reference&lt; arm::pipe::ProfilingGuid &gt;::value, arm::pipe::ProfilingGuid &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20armnn_3a_3abackendid_20_3e_3a_3avalue_2c_20armnn_3a_3abackendid_20_3e_5985',['OptionalReferenceSwitch&lt; std::is_reference&lt; armnn::BackendId &gt;::value, armnn::BackendId &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20armnn_3a_3atensorinfo_20_3e_3a_3avalue_2c_20armnn_3a_3atensorinfo_20_3e_5986',['OptionalReferenceSwitch&lt; std::is_reference&lt; armnn::TensorInfo &gt;::value, armnn::TensorInfo &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_3a_3avalue_2c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_5987',['OptionalReferenceSwitch&lt; std::is_reference&lt; armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;::value, armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20int32_5ft_20_3e_3a_3avalue_2c_20int32_5ft_20_3e_5988',['OptionalReferenceSwitch&lt; std::is_reference&lt; int32_t &gt;::value, int32_t &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20std_3a_3astring_20_3e_3a_3avalue_2c_20std_3a_3astring_20_3e_5989',['OptionalReferenceSwitch&lt; std::is_reference&lt; std::string &gt;::value, std::string &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_3a_3avalue_2c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_5990',['OptionalReferenceSwitch&lt; std::is_reference&lt; std::vector&lt; armnn::MemoryInfo &gt; &gt;::value, std::vector&lt; armnn::MemoryInfo &gt; &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20t_20_3e_3a_3avalue_2c_20t_20_3e_5991',['OptionalReferenceSwitch&lt; std::is_reference&lt; T &gt;::value, T &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20unsigned_20int_20_3e_3a_3avalue_2c_20unsigned_20int_20_3e_5992',['OptionalReferenceSwitch&lt; std::is_reference&lt; unsigned int &gt;::value, unsigned int &gt;',['../classarmnn_1_1_optional_reference_switch.html',1,'armnn']]],
  ['optionalreferenceswitch_3c_20true_2c_20t_20_3e_5993',['OptionalReferenceSwitch&lt; true, T &gt;',['../classarmnn_1_1_optional_reference_switch_3_01true_00_01_t_01_4.html',1,'armnn']]],
  ['originsdescriptor_5994',['OriginsDescriptor',['../structarmnn_1_1_origins_descriptor.html',1,'armnn']]],
  ['outputhandler_5995',['OutputHandler',['../classarmnn_1_1_output_handler.html',1,'armnn']]],
  ['outputlayer_5996',['OutputLayer',['../classarmnn_1_1_output_layer.html',1,'armnn']]],
  ['outputlayersaccessor_5997',['OutputLayersAccessor',['../structarmnn_1_1_graph_1_1_output_layers_accessor.html',1,'armnn::Graph']]],
  ['outputmemdescriptorcoords_5998',['OutputMemDescriptorCoords',['../structarmnn_1_1experimental_1_1_working_mem_handle_1_1_output_mem_descriptor_coords.html',1,'armnn::experimental::WorkingMemHandle']]],
  ['outputslot_5999',['OutputSlot',['../classarmnn_1_1_output_slot.html',1,'armnn']]]
];
