var searchData=
[
  ['backendcapabilityexception_5133',['BackendCapabilityException',['../classarmnn_1_1_backend_capability_exception.html',1,'armnn']]],
  ['backendid_5134',['BackendId',['../classarmnn_1_1_backend_id.html',1,'armnn']]],
  ['backendoption_5135',['BackendOption',['../structarmnn_1_1_backend_options_1_1_backend_option.html',1,'armnn::BackendOptions']]],
  ['backendoptions_5136',['BackendOptions',['../structarmnn_1_1_backend_options.html',1,'armnn']]],
  ['backendregistry_5137',['BackendRegistry',['../classarmnn_1_1_backend_registry.html',1,'armnn']]],
  ['backendsettings_5138',['BackendSettings',['../structarmnn_1_1_backend_settings.html',1,'armnn']]],
  ['backendunavailableexception_5139',['BackendUnavailableException',['../classarmnn_1_1_backend_unavailable_exception.html',1,'armnn']]],
  ['backendversion_5140',['BackendVersion',['../structarmnn_1_1_backend_version.html',1,'armnn']]],
  ['badoptionalaccessexception_5141',['BadOptionalAccessException',['../classarmnn_1_1_bad_optional_access_exception.html',1,'armnn']]],
  ['basedescriptor_5142',['BaseDescriptor',['../structarmnn_1_1_base_descriptor.html',1,'armnn']]],
  ['baseiterator_5143',['BaseIterator',['../classarmnn_1_1_base_iterator.html',1,'armnn']]],
  ['basememorymanager_5144',['BaseMemoryManager',['../classarmnn_1_1_base_memory_manager.html',1,'armnn']]],
  ['basetensor_5145',['BaseTensor',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20const_20void_20_2a_20_3e_5146',['BaseTensor&lt; const void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20void_20_2a_20_3e_5147',['BaseTensor&lt; void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['baseworkload_5148',['BaseWorkload',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20absqueuedescriptor_20_3e_5149',['BaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20activationqueuedescriptor_20_3e_5150',['BaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20additionqueuedescriptor_20_3e_5151',['BaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20argminmaxqueuedescriptor_20_3e_5152',['BaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20armnn_3a_3aadditionqueuedescriptor_20_3e_5153',['BaseWorkload&lt; armnn::AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5154',['BaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5155',['BaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5156',['BaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20broadcasttoqueuedescriptor_20_3e_5157',['BaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20castqueuedescriptor_20_3e_5158',['BaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20channelshufflequeuedescriptor_20_3e_5159',['BaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20comparisonqueuedescriptor_20_3e_5160',['BaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20concatqueuedescriptor_20_3e_5161',['BaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20constantqueuedescriptor_20_3e_5162',['BaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution2dqueuedescriptor_20_3e_5163',['BaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution3dqueuedescriptor_20_3e_5164',['BaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20debugqueuedescriptor_20_3e_5165',['BaseWorkload&lt; DebugQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthtospacequeuedescriptor_20_3e_5166',['BaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5167',['BaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20dequantizequeuedescriptor_20_3e_5168',['BaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5169',['BaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20divisionqueuedescriptor_20_3e_5170',['BaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5171',['BaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5172',['BaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fillqueuedescriptor_20_3e_5173',['BaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20floorqueuedescriptor_20_3e_5174',['BaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5175',['BaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fusedqueuedescriptor_20_3e_5176',['BaseWorkload&lt; FusedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherndqueuedescriptor_20_3e_5177',['BaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherqueuedescriptor_20_3e_5178',['BaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5179',['BaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5180',['BaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5181',['BaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5182',['BaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20lstmqueuedescriptor_20_3e_5183',['BaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20mapqueuedescriptor_20_3e_5184',['BaseWorkload&lt; MapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20maximumqueuedescriptor_20_3e_5185',['BaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20meanqueuedescriptor_20_3e_5186',['BaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memcopyqueuedescriptor_20_3e_5187',['BaseWorkload&lt; MemCopyQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memimportqueuedescriptor_20_3e_5188',['BaseWorkload&lt; MemImportQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memsyncqueuedescriptor_20_3e_5189',['BaseWorkload&lt; MemSyncQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20minimumqueuedescriptor_20_3e_5190',['BaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20multiplicationqueuedescriptor_20_3e_5191',['BaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20normalizationqueuedescriptor_20_3e_5192',['BaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20padqueuedescriptor_20_3e_5193',['BaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20parentdescriptor_20_3e_5194',['BaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20permutequeuedescriptor_20_3e_5195',['BaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling2dqueuedescriptor_20_3e_5196',['BaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling3dqueuedescriptor_20_3e_5197',['BaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20precompiledqueuedescriptor_20_3e_5198',['BaseWorkload&lt; PreCompiledQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20preluqueuedescriptor_20_3e_5199',['BaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20qlstmqueuedescriptor_20_3e_5200',['BaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5201',['BaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizequeuedescriptor_20_3e_5202',['BaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rankqueuedescriptor_20_3e_5203',['BaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reducequeuedescriptor_20_3e_5204',['BaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reshapequeuedescriptor_20_3e_5205',['BaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20resizequeuedescriptor_20_3e_5206',['BaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reversev2queuedescriptor_20_3e_5207',['BaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rsqrtqueuedescriptor_20_3e_5208',['BaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20shapequeuedescriptor_20_3e_5209',['BaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20slicequeuedescriptor_20_3e_5210',['BaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20softmaxqueuedescriptor_20_3e_5211',['BaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5212',['BaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5213',['BaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20splitterqueuedescriptor_20_3e_5214',['BaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stackqueuedescriptor_20_3e_5215',['BaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stridedslicequeuedescriptor_20_3e_5216',['BaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20subtractionqueuedescriptor_20_3e_5217',['BaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20tilequeuedescriptor_20_3e_5218',['BaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5219',['BaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposequeuedescriptor_20_3e_5220',['BaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5221',['BaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unmapqueuedescriptor_20_3e_5222',['BaseWorkload&lt; UnmapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['batchmatmul_5223',['BatchMatMul',['../classarmnn_1_1_batch_mat_mul.html',1,'armnn']]],
  ['batchmatmuldescriptor_5224',['BatchMatMulDescriptor',['../structarmnn_1_1_batch_mat_mul_descriptor.html',1,'armnn']]],
  ['batchmatmullayer_5225',['BatchMatMulLayer',['../classarmnn_1_1_batch_mat_mul_layer.html',1,'armnn']]],
  ['batchmatmulqueuedescriptor_5226',['BatchMatMulQueueDescriptor',['../structarmnn_1_1_batch_mat_mul_queue_descriptor.html',1,'armnn']]],
  ['batchnormalizationdescriptor_5227',['BatchNormalizationDescriptor',['../structarmnn_1_1_batch_normalization_descriptor.html',1,'armnn']]],
  ['batchnormalizationlayer_5228',['BatchNormalizationLayer',['../classarmnn_1_1_batch_normalization_layer.html',1,'armnn']]],
  ['batchnormalizationqueuedescriptor_5229',['BatchNormalizationQueueDescriptor',['../structarmnn_1_1_batch_normalization_queue_descriptor.html',1,'armnn']]],
  ['batchtospacenddescriptor_5230',['BatchToSpaceNdDescriptor',['../structarmnn_1_1_batch_to_space_nd_descriptor.html',1,'armnn']]],
  ['batchtospacendlayer_5231',['BatchToSpaceNdLayer',['../classarmnn_1_1_batch_to_space_nd_layer.html',1,'armnn']]],
  ['batchtospacendqueuedescriptor_5232',['BatchToSpaceNdQueueDescriptor',['../structarmnn_1_1_batch_to_space_nd_queue_descriptor.html',1,'armnn']]],
  ['bfloat16_5233',['BFloat16',['../classarmnn_1_1_b_float16.html',1,'armnn']]],
  ['biasandweightstypescompatible_5234',['BiasAndWeightsTypesCompatible',['../structarmnn_1_1_bias_and_weights_types_compatible.html',1,'armnn']]],
  ['biasandweightstypesmatch_5235',['BiasAndWeightsTypesMatch',['../structarmnn_1_1_bias_and_weights_types_match.html',1,'armnn']]],
  ['bindablelayer_5236',['BindableLayer',['../classarmnn_1_1_bindable_layer.html',1,'armnn']]],
  ['bindingpointinfo_5237',['BindingPointInfo',['../structarmnn_deserializer_1_1_binding_point_info.html',1,'armnnDeserializer']]],
  ['booleandecoder_5238',['BooleanDecoder',['../classarmnn_1_1_boolean_decoder.html',1,'armnn']]],
  ['booleandecoderbool_5239',['BooleanDecoderBool',['../classarmnn_1_1_boolean_decoder_bool.html',1,'armnn']]],
  ['booleanencoder_5240',['BooleanEncoder',['../classarmnn_1_1_boolean_encoder.html',1,'armnn']]],
  ['broadcastloop_5241',['BroadcastLoop',['../structarmnn_1_1_broadcast_loop.html',1,'armnn']]],
  ['broadcasttodescriptor_5242',['BroadcastToDescriptor',['../structarmnn_1_1_broadcast_to_descriptor.html',1,'armnn']]],
  ['broadcasttolayer_5243',['BroadcastToLayer',['../classarmnn_1_1_broadcast_to_layer.html',1,'armnn']]],
  ['broadcasttoqueuedescriptor_5244',['BroadcastToQueueDescriptor',['../structarmnn_1_1_broadcast_to_queue_descriptor.html',1,'armnn']]],
  ['bufferstorage_5245',['BufferStorage',['../structarmnn_1_1_buffer_storage.html',1,'armnn']]]
];
