var searchData=
[
  ['datalayoutindexed_5432',['DataLayoutIndexed',['../classarmnn_utils_1_1_data_layout_indexed.html',1,'armnnUtils']]],
  ['debuglayer_5433',['DebugLayer',['../classarmnn_1_1_debug_layer.html',1,'armnn']]],
  ['debugqueuedescriptor_5434',['DebugQueueDescriptor',['../structarmnn_1_1_debug_queue_descriptor.html',1,'armnn']]],
  ['decoder_5435',['Decoder',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20bool_20_3e_5436',['Decoder&lt; bool &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20double_5ft_20_3e_5437',['Decoder&lt; double_t &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20float_20_3e_5438',['Decoder&lt; float &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['decoder_3c_20int32_5ft_20_3e_5439',['Decoder&lt; int32_t &gt;',['../classarmnn_1_1_decoder.html',1,'armnn']]],
  ['defaultallocator_5440',['DefaultAllocator',['../classarmnn_1_1_default_allocator.html',1,'armnn']]],
  ['delegate_5441',['Delegate',['../classarmnn_delegate_1_1_delegate.html',1,'armnnDelegate']]],
  ['delegatedata_5442',['DelegateData',['../structarmnn_delegate_1_1_delegate_data.html',1,'DelegateData'],['../structarmnn_opaque_delegate_1_1_delegate_data.html',1,'DelegateData']]],
  ['deletebroadcasttoimpl_5443',['DeleteBroadcastToImpl',['../classarmnn_1_1optimizations_1_1_delete_broadcast_to_impl.html',1,'armnn::optimizations']]],
  ['depthtospacelayer_5444',['DepthToSpaceLayer',['../classarmnn_1_1_depth_to_space_layer.html',1,'armnn']]],
  ['depthtospacequeuedescriptor_5445',['DepthToSpaceQueueDescriptor',['../structarmnn_1_1_depth_to_space_queue_descriptor.html',1,'armnn']]],
  ['depthwiseconvolution2ddescriptor_5446',['DepthwiseConvolution2dDescriptor',['../structarmnn_1_1_depthwise_convolution2d_descriptor.html',1,'armnn']]],
  ['depthwiseconvolution2dlayer_5447',['DepthwiseConvolution2dLayer',['../classarmnn_1_1_depthwise_convolution2d_layer.html',1,'armnn']]],
  ['depthwiseconvolution2dqueuedescriptor_5448',['DepthwiseConvolution2dQueueDescriptor',['../structarmnn_1_1_depthwise_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['dequantizelayer_5449',['DequantizeLayer',['../classarmnn_1_1_dequantize_layer.html',1,'armnn']]],
  ['dequantizequeuedescriptor_5450',['DequantizeQueueDescriptor',['../structarmnn_1_1_dequantize_queue_descriptor.html',1,'armnn']]],
  ['deserializerimpl_5451',['DeserializerImpl',['../classarmnn_deserializer_1_1_i_deserializer_1_1_deserializer_impl.html',1,'armnnDeserializer::IDeserializer']]],
  ['detectionpostprocessdescriptor_5452',['DetectionPostProcessDescriptor',['../structarmnn_1_1_detection_post_process_descriptor.html',1,'armnn']]],
  ['detectionpostprocesslayer_5453',['DetectionPostProcessLayer',['../classarmnn_1_1_detection_post_process_layer.html',1,'armnn']]],
  ['detectionpostprocessqueuedescriptor_5454',['DetectionPostProcessQueueDescriptor',['../structarmnn_1_1_detection_post_process_queue_descriptor.html',1,'armnn']]],
  ['devicespec_5455',['DeviceSpec',['../classarmnn_1_1_device_spec.html',1,'armnn']]],
  ['divisionlayer_5456',['DivisionLayer',['../classarmnn_1_1_division_layer.html',1,'armnn']]],
  ['divisionqueuedescriptor_5457',['DivisionQueueDescriptor',['../structarmnn_1_1_division_queue_descriptor.html',1,'armnn']]],
  ['dotattributeset_5458',['DotAttributeSet',['../classarmnn_1_1_dot_attribute_set.html',1,'armnn']]],
  ['dotbase_5459',['DotBase',['../classarmnn_1_1_dot_base.html',1,'armnn']]],
  ['dotdefaults_5460',['DotDefaults',['../classarmnn_1_1_dot_defaults.html',1,'armnn']]],
  ['dotedge_5461',['DotEdge',['../classarmnn_1_1_dot_edge.html',1,'armnn']]],
  ['dotgraph_5462',['DotGraph',['../classarmnn_1_1_dot_graph.html',1,'armnn']]],
  ['dotnode_5463',['DotNode',['../classarmnn_1_1_dot_node.html',1,'armnn']]],
  ['driveroptions_5464',['DriverOptions',['../classarmnn__driver_1_1_driver_options.html',1,'armnn_driver']]],
  ['dynamicbackend_5465',['DynamicBackend',['../classarmnn_1_1_dynamic_backend.html',1,'armnn']]],
  ['dynamicbackendutils_5466',['DynamicBackendUtils',['../classarmnn_1_1_dynamic_backend_utils.html',1,'armnn']]]
];
