var searchData=
[
  ['rangetracker_6114',['RangeTracker',['../classarmnn_1_1_range_tracker.html',1,'armnn']]],
  ['ranklayer_6115',['RankLayer',['../classarmnn_1_1_rank_layer.html',1,'armnn']]],
  ['rankqueuedescriptor_6116',['RankQueueDescriptor',['../structarmnn_1_1_rank_queue_descriptor.html',1,'armnn']]],
  ['reducedescriptor_6117',['ReduceDescriptor',['../structarmnn_1_1_reduce_descriptor.html',1,'armnn']]],
  ['reducelayer_6118',['ReduceLayer',['../classarmnn_1_1_reduce_layer.html',1,'armnn']]],
  ['reducequeuedescriptor_6119',['ReduceQueueDescriptor',['../structarmnn_1_1_reduce_queue_descriptor.html',1,'armnn']]],
  ['refactivationworkload_6120',['RefActivationWorkload',['../classarmnn_1_1_ref_activation_workload.html',1,'armnn']]],
  ['refargminmaxworkload_6121',['RefArgMinMaxWorkload',['../classarmnn_1_1_ref_arg_min_max_workload.html',1,'armnn']]],
  ['refbackend_6122',['RefBackend',['../classarmnn_1_1_ref_backend.html',1,'armnn']]],
  ['refbaseworkload_6123',['RefBaseWorkload',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20activationqueuedescriptor_20_3e_6124',['RefBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_6125',['RefBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_6126',['RefBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_6127',['RefBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_6128',['RefBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20broadcasttoqueuedescriptor_20_3e_6129',['RefBaseWorkload&lt; BroadcastToQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20castqueuedescriptor_20_3e_6130',['RefBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_6131',['RefBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20comparisonqueuedescriptor_20_3e_6132',['RefBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20concatqueuedescriptor_20_3e_6133',['RefBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20constantqueuedescriptor_20_3e_6134',['RefBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_6135',['RefBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_6136',['RefBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_6137',['RefBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_6138',['RefBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20dequantizequeuedescriptor_20_3e_6139',['RefBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_6140',['RefBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_6141',['RefBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_6142',['RefBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20fillqueuedescriptor_20_3e_6143',['RefBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20floorqueuedescriptor_20_3e_6144',['RefBaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_6145',['RefBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20gatherndqueuedescriptor_20_3e_6146',['RefBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20gatherqueuedescriptor_20_3e_6147',['RefBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_6148',['RefBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20l2normalizationqueuedescriptor_20_3e_6149',['RefBaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_6150',['RefBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_6151',['RefBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20lstmqueuedescriptor_20_3e_6152',['RefBaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20meanqueuedescriptor_20_3e_6153',['RefBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20normalizationqueuedescriptor_20_3e_6154',['RefBaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20padqueuedescriptor_20_3e_6155',['RefBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20parentdescriptor_20_3e_6156',['RefBaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_6157',['RefBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_6158',['RefBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20preluqueuedescriptor_20_3e_6159',['RefBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20qlstmqueuedescriptor_20_3e_6160',['RefBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20quantizequeuedescriptor_20_3e_6161',['RefBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20rankqueuedescriptor_20_3e_6162',['RefBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reducequeuedescriptor_20_3e_6163',['RefBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reshapequeuedescriptor_20_3e_6164',['RefBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20resizequeuedescriptor_20_3e_6165',['RefBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20reversev2queuedescriptor_20_3e_6166',['RefBaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20shapequeuedescriptor_20_3e_6167',['RefBaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20slicequeuedescriptor_20_3e_6168',['RefBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20softmaxqueuedescriptor_20_3e_6169',['RefBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_6170',['RefBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_6171',['RefBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20splitterqueuedescriptor_20_3e_6172',['RefBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20stackqueuedescriptor_20_3e_6173',['RefBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_6174',['RefBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20tilequeuedescriptor_20_3e_6175',['RefBaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_6176',['RefBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_6177',['RefBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.html',1,'armnn']]],
  ['refbatchmatmulworkload_6178',['RefBatchMatMulWorkload',['../classarmnn_1_1_ref_batch_mat_mul_workload.html',1,'armnn']]],
  ['refbatchnormalizationworkload_6179',['RefBatchNormalizationWorkload',['../classarmnn_1_1_ref_batch_normalization_workload.html',1,'armnn']]],
  ['refbatchtospacendworkload_6180',['RefBatchToSpaceNdWorkload',['../classarmnn_1_1_ref_batch_to_space_nd_workload.html',1,'armnn']]],
  ['refbroadcasttoworkload_6181',['RefBroadcastToWorkload',['../classarmnn_1_1_ref_broadcast_to_workload.html',1,'armnn']]],
  ['refcastworkload_6182',['RefCastWorkload',['../classarmnn_1_1_ref_cast_workload.html',1,'armnn']]],
  ['refchannelshuffleworkload_6183',['RefChannelShuffleWorkload',['../classarmnn_1_1_ref_channel_shuffle_workload.html',1,'armnn']]],
  ['refcomparisonworkload_6184',['RefComparisonWorkload',['../classarmnn_1_1_ref_comparison_workload.html',1,'armnn']]],
  ['refconcatworkload_6185',['RefConcatWorkload',['../classarmnn_1_1_ref_concat_workload.html',1,'armnn']]],
  ['refconstantworkload_6186',['RefConstantWorkload',['../classarmnn_1_1_ref_constant_workload.html',1,'armnn']]],
  ['refconvertfp16tofp32workload_6187',['RefConvertFp16ToFp32Workload',['../classarmnn_1_1_ref_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['refconvertfp32tofp16workload_6188',['RefConvertFp32ToFp16Workload',['../classarmnn_1_1_ref_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['refconvolution2dworkload_6189',['RefConvolution2dWorkload',['../classarmnn_1_1_ref_convolution2d_workload.html',1,'armnn']]],
  ['refconvolution3dworkload_6190',['RefConvolution3dWorkload',['../classarmnn_1_1_ref_convolution3d_workload.html',1,'armnn']]],
  ['refdebugworkload_6191',['RefDebugWorkload',['../classarmnn_1_1_ref_debug_workload.html',1,'armnn']]],
  ['refdepthtospaceworkload_6192',['RefDepthToSpaceWorkload',['../classarmnn_1_1_ref_depth_to_space_workload.html',1,'armnn']]],
  ['refdepthwiseconvolution2dworkload_6193',['RefDepthwiseConvolution2dWorkload',['../classarmnn_1_1_ref_depthwise_convolution2d_workload.html',1,'armnn']]],
  ['refdequantizeworkload_6194',['RefDequantizeWorkload',['../classarmnn_1_1_ref_dequantize_workload.html',1,'armnn']]],
  ['refdetectionpostprocessworkload_6195',['RefDetectionPostProcessWorkload',['../classarmnn_1_1_ref_detection_post_process_workload.html',1,'armnn']]],
  ['refelementwisebinaryworkload_6196',['RefElementwiseBinaryWorkload',['../classarmnn_1_1_ref_elementwise_binary_workload.html',1,'armnn']]],
  ['refelementwiseunaryworkload_6197',['RefElementwiseUnaryWorkload',['../classarmnn_1_1_ref_elementwise_unary_workload.html',1,'armnn']]],
  ['refelementwiseworkload_6198',['RefElementwiseWorkload',['../classarmnn_1_1_ref_elementwise_workload.html',1,'armnn']]],
  ['reffakequantizationfloat32workload_6199',['RefFakeQuantizationFloat32Workload',['../classarmnn_1_1_ref_fake_quantization_float32_workload.html',1,'armnn']]],
  ['reffillworkload_6200',['RefFillWorkload',['../classarmnn_1_1_ref_fill_workload.html',1,'armnn']]],
  ['reffloorworkload_6201',['RefFloorWorkload',['../classarmnn_1_1_ref_floor_workload.html',1,'armnn']]],
  ['reffullyconnectedworkload_6202',['RefFullyConnectedWorkload',['../classarmnn_1_1_ref_fully_connected_workload.html',1,'armnn']]],
  ['refgatherndworkload_6203',['RefGatherNdWorkload',['../classarmnn_1_1_ref_gather_nd_workload.html',1,'armnn']]],
  ['refgatherworkload_6204',['RefGatherWorkload',['../classarmnn_1_1_ref_gather_workload.html',1,'armnn']]],
  ['refinstancenormalizationworkload_6205',['RefInstanceNormalizationWorkload',['../classarmnn_1_1_ref_instance_normalization_workload.html',1,'armnn']]],
  ['refl2normalizationworkload_6206',['RefL2NormalizationWorkload',['../classarmnn_1_1_ref_l2_normalization_workload.html',1,'armnn']]],
  ['reflayersupport_6207',['RefLayerSupport',['../classarmnn_1_1_ref_layer_support.html',1,'armnn']]],
  ['reflogicalbinaryworkload_6208',['RefLogicalBinaryWorkload',['../classarmnn_1_1_ref_logical_binary_workload.html',1,'armnn']]],
  ['reflogicalunaryworkload_6209',['RefLogicalUnaryWorkload',['../classarmnn_1_1_ref_logical_unary_workload.html',1,'armnn']]],
  ['reflogsoftmaxworkload_6210',['RefLogSoftmaxWorkload',['../classarmnn_1_1_ref_log_softmax_workload.html',1,'armnn']]],
  ['reflstmworkload_6211',['RefLstmWorkload',['../classarmnn_1_1_ref_lstm_workload.html',1,'armnn']]],
  ['refmeanworkload_6212',['RefMeanWorkload',['../classarmnn_1_1_ref_mean_workload.html',1,'armnn']]],
  ['refmemorymanager_6213',['RefMemoryManager',['../classarmnn_1_1_ref_memory_manager.html',1,'armnn']]],
  ['refnormalizationworkload_6214',['RefNormalizationWorkload',['../classarmnn_1_1_ref_normalization_workload.html',1,'armnn']]],
  ['refpadworkload_6215',['RefPadWorkload',['../classarmnn_1_1_ref_pad_workload.html',1,'armnn']]],
  ['refpermuteworkload_6216',['RefPermuteWorkload',['../classarmnn_1_1_ref_permute_workload.html',1,'armnn']]],
  ['refpooling2dworkload_6217',['RefPooling2dWorkload',['../classarmnn_1_1_ref_pooling2d_workload.html',1,'armnn']]],
  ['refpooling3dworkload_6218',['RefPooling3dWorkload',['../classarmnn_1_1_ref_pooling3d_workload.html',1,'armnn']]],
  ['refpreluworkload_6219',['RefPreluWorkload',['../classarmnn_1_1_ref_prelu_workload.html',1,'armnn']]],
  ['refqlstmworkload_6220',['RefQLstmWorkload',['../classarmnn_1_1_ref_q_lstm_workload.html',1,'armnn']]],
  ['refquantizeworkload_6221',['RefQuantizeWorkload',['../classarmnn_1_1_ref_quantize_workload.html',1,'armnn']]],
  ['refrankworkload_6222',['RefRankWorkload',['../structarmnn_1_1_ref_rank_workload.html',1,'armnn']]],
  ['refreduceworkload_6223',['RefReduceWorkload',['../classarmnn_1_1_ref_reduce_workload.html',1,'armnn']]],
  ['refreshapeworkload_6224',['RefReshapeWorkload',['../classarmnn_1_1_ref_reshape_workload.html',1,'armnn']]],
  ['refresizeworkload_6225',['RefResizeWorkload',['../classarmnn_1_1_ref_resize_workload.html',1,'armnn']]],
  ['refreversev2workload_6226',['RefReverseV2Workload',['../classarmnn_1_1_ref_reverse_v2_workload.html',1,'armnn']]],
  ['refshapeworkload_6227',['RefShapeWorkload',['../structarmnn_1_1_ref_shape_workload.html',1,'armnn']]],
  ['refsliceworkload_6228',['RefSliceWorkload',['../classarmnn_1_1_ref_slice_workload.html',1,'armnn']]],
  ['refsoftmaxworkload_6229',['RefSoftmaxWorkload',['../classarmnn_1_1_ref_softmax_workload.html',1,'armnn']]],
  ['refspacetobatchndworkload_6230',['RefSpaceToBatchNdWorkload',['../classarmnn_1_1_ref_space_to_batch_nd_workload.html',1,'armnn']]],
  ['refspacetodepthworkload_6231',['RefSpaceToDepthWorkload',['../classarmnn_1_1_ref_space_to_depth_workload.html',1,'armnn']]],
  ['refsplitterworkload_6232',['RefSplitterWorkload',['../classarmnn_1_1_ref_splitter_workload.html',1,'armnn']]],
  ['refstackworkload_6233',['RefStackWorkload',['../classarmnn_1_1_ref_stack_workload.html',1,'armnn']]],
  ['refstridedsliceworkload_6234',['RefStridedSliceWorkload',['../classarmnn_1_1_ref_strided_slice_workload.html',1,'armnn']]],
  ['reftensorhandle_6235',['RefTensorHandle',['../classarmnn_1_1_ref_tensor_handle.html',1,'armnn']]],
  ['reftensorhandledecorator_6236',['RefTensorHandleDecorator',['../classarmnn_1_1_ref_tensor_handle_decorator.html',1,'armnn']]],
  ['reftensorhandlefactory_6237',['RefTensorHandleFactory',['../classarmnn_1_1_ref_tensor_handle_factory.html',1,'armnn']]],
  ['reftileworkload_6238',['RefTileWorkload',['../classarmnn_1_1_ref_tile_workload.html',1,'armnn']]],
  ['reftransposeconvolution2dworkload_6239',['RefTransposeConvolution2dWorkload',['../classarmnn_1_1_ref_transpose_convolution2d_workload.html',1,'armnn']]],
  ['reftransposeworkload_6240',['RefTransposeWorkload',['../classarmnn_1_1_ref_transpose_workload.html',1,'armnn']]],
  ['refunidirectionalsequencelstmworkload_6241',['RefUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_ref_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['refworkloadfactory_6242',['RefWorkloadFactory',['../classarmnn_1_1_ref_workload_factory.html',1,'armnn']]],
  ['reshapedescriptor_6243',['ReshapeDescriptor',['../structarmnn_1_1_reshape_descriptor.html',1,'armnn']]],
  ['reshapelayer_6244',['ReshapeLayer',['../classarmnn_1_1_reshape_layer.html',1,'armnn']]],
  ['reshapequeuedescriptor_6245',['ReshapeQueueDescriptor',['../structarmnn_1_1_reshape_queue_descriptor.html',1,'armnn']]],
  ['resizedescriptor_6246',['ResizeDescriptor',['../structarmnn_1_1_resize_descriptor.html',1,'armnn']]],
  ['resizelayer_6247',['ResizeLayer',['../classarmnn_1_1_resize_layer.html',1,'armnn']]],
  ['resizequeuedescriptor_6248',['ResizeQueueDescriptor',['../structarmnn_1_1_resize_queue_descriptor.html',1,'armnn']]],
  ['resolvetypeimpl_6249',['ResolveTypeImpl',['../structarmnn_1_1_resolve_type_impl.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3abfloat16_20_3e_6250',['ResolveTypeImpl&lt; DataType::BFloat16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_b_float16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aboolean_20_3e_6251',['ResolveTypeImpl&lt; DataType::Boolean &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_boolean_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat16_20_3e_6252',['ResolveTypeImpl&lt; DataType::Float16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat32_20_3e_6253',['ResolveTypeImpl&lt; DataType::Float32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float32_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymms8_20_3e_6254',['ResolveTypeImpl&lt; DataType::QAsymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_s8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymmu8_20_3e_6255',['ResolveTypeImpl&lt; DataType::QAsymmU8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_u8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms16_20_3e_6256',['ResolveTypeImpl&lt; DataType::QSymmS16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s16_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms8_20_3e_6257',['ResolveTypeImpl&lt; DataType::QSymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s8_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned32_20_3e_6258',['ResolveTypeImpl&lt; DataType::Signed32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed32_01_4.html',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned64_20_3e_6259',['ResolveTypeImpl&lt; DataType::Signed64 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed64_01_4.html',1,'armnn']]],
  ['reversev2layer_6260',['ReverseV2Layer',['../classarmnn_1_1_reverse_v2_layer.html',1,'armnn']]],
  ['reversev2queuedescriptor_6261',['ReverseV2QueueDescriptor',['../structarmnn_1_1_reverse_v2_queue_descriptor.html',1,'armnn']]],
  ['rsqrt_6262',['rsqrt',['../structarmnn_1_1rsqrt.html',1,'armnn']]],
  ['rsqrtlayer_6263',['RsqrtLayer',['../classarmnn_1_1_rsqrt_layer.html',1,'armnn']]],
  ['rsqrtqueuedescriptor_6264',['RsqrtQueueDescriptor',['../structarmnn_1_1_rsqrt_queue_descriptor.html',1,'armnn']]],
  ['rule_6265',['Rule',['../structarmnn_1_1_rule.html',1,'armnn']]],
  ['runtimeexception_6266',['RuntimeException',['../classarmnn_1_1_runtime_exception.html',1,'armnn']]],
  ['runtimeimpl_6267',['RuntimeImpl',['../structarmnn_1_1_runtime_impl.html',1,'armnn']]]
];
