var searchData=
[
  ['backendcapabilityexception_5055',['BackendCapabilityException',['../classarmnn_1_1_backend_capability_exception.html',1,'armnn']]],
  ['backendid_5056',['BackendId',['../classarmnn_1_1_backend_id.html',1,'armnn']]],
  ['backendoption_5057',['BackendOption',['../structarmnn_1_1_backend_options_1_1_backend_option.html',1,'armnn::BackendOptions']]],
  ['backendoptions_5058',['BackendOptions',['../structarmnn_1_1_backend_options.html',1,'armnn']]],
  ['backendregistry_5059',['BackendRegistry',['../classarmnn_1_1_backend_registry.html',1,'armnn']]],
  ['backendsettings_5060',['BackendSettings',['../structarmnn_1_1_backend_settings.html',1,'armnn']]],
  ['backendunavailableexception_5061',['BackendUnavailableException',['../classarmnn_1_1_backend_unavailable_exception.html',1,'armnn']]],
  ['backendversion_5062',['BackendVersion',['../structarmnn_1_1_backend_version.html',1,'armnn']]],
  ['badoptionalaccessexception_5063',['BadOptionalAccessException',['../classarmnn_1_1_bad_optional_access_exception.html',1,'armnn']]],
  ['basedescriptor_5064',['BaseDescriptor',['../structarmnn_1_1_base_descriptor.html',1,'armnn']]],
  ['baseiterator_5065',['BaseIterator',['../classarmnn_1_1_base_iterator.html',1,'armnn']]],
  ['basememorymanager_5066',['BaseMemoryManager',['../classarmnn_1_1_base_memory_manager.html',1,'armnn']]],
  ['basetensor_5067',['BaseTensor',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20const_20void_20_2a_20_3e_5068',['BaseTensor&lt; const void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['basetensor_3c_20void_20_2a_20_3e_5069',['BaseTensor&lt; void * &gt;',['../classarmnn_1_1_base_tensor.html',1,'armnn']]],
  ['baseworkload_5070',['BaseWorkload',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20absqueuedescriptor_20_3e_5071',['BaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20activationqueuedescriptor_20_3e_5072',['BaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20additionqueuedescriptor_20_3e_5073',['BaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20argminmaxqueuedescriptor_20_3e_5074',['BaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20armnn_3a_3aadditionqueuedescriptor_20_3e_5075',['BaseWorkload&lt; armnn::AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5076',['BaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5077',['BaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5078',['BaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20castqueuedescriptor_20_3e_5079',['BaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20channelshufflequeuedescriptor_20_3e_5080',['BaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20comparisonqueuedescriptor_20_3e_5081',['BaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20concatqueuedescriptor_20_3e_5082',['BaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20constantqueuedescriptor_20_3e_5083',['BaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution2dqueuedescriptor_20_3e_5084',['BaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20convolution3dqueuedescriptor_20_3e_5085',['BaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20debugqueuedescriptor_20_3e_5086',['BaseWorkload&lt; DebugQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthtospacequeuedescriptor_20_3e_5087',['BaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5088',['BaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20dequantizequeuedescriptor_20_3e_5089',['BaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5090',['BaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20divisionqueuedescriptor_20_3e_5091',['BaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5092',['BaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5093',['BaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fillqueuedescriptor_20_3e_5094',['BaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20floorqueuedescriptor_20_3e_5095',['BaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5096',['BaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherndqueuedescriptor_20_3e_5097',['BaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20gatherqueuedescriptor_20_3e_5098',['BaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5099',['BaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5100',['BaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5101',['BaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5102',['BaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20lstmqueuedescriptor_20_3e_5103',['BaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20mapqueuedescriptor_20_3e_5104',['BaseWorkload&lt; MapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20maximumqueuedescriptor_20_3e_5105',['BaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20meanqueuedescriptor_20_3e_5106',['BaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memcopyqueuedescriptor_20_3e_5107',['BaseWorkload&lt; MemCopyQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memimportqueuedescriptor_20_3e_5108',['BaseWorkload&lt; MemImportQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20memsyncqueuedescriptor_20_3e_5109',['BaseWorkload&lt; MemSyncQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20minimumqueuedescriptor_20_3e_5110',['BaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20multiplicationqueuedescriptor_20_3e_5111',['BaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20normalizationqueuedescriptor_20_3e_5112',['BaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20padqueuedescriptor_20_3e_5113',['BaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20parentdescriptor_20_3e_5114',['BaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20permutequeuedescriptor_20_3e_5115',['BaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling2dqueuedescriptor_20_3e_5116',['BaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20pooling3dqueuedescriptor_20_3e_5117',['BaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20precompiledqueuedescriptor_20_3e_5118',['BaseWorkload&lt; PreCompiledQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20preluqueuedescriptor_20_3e_5119',['BaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20qlstmqueuedescriptor_20_3e_5120',['BaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5121',['BaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20quantizequeuedescriptor_20_3e_5122',['BaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rankqueuedescriptor_20_3e_5123',['BaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reducequeuedescriptor_20_3e_5124',['BaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reshapequeuedescriptor_20_3e_5125',['BaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20resizequeuedescriptor_20_3e_5126',['BaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20reversev2queuedescriptor_20_3e_5127',['BaseWorkload&lt; ReverseV2QueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20rsqrtqueuedescriptor_20_3e_5128',['BaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20shapequeuedescriptor_20_3e_5129',['BaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20slicequeuedescriptor_20_3e_5130',['BaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20softmaxqueuedescriptor_20_3e_5131',['BaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5132',['BaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5133',['BaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20splitterqueuedescriptor_20_3e_5134',['BaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stackqueuedescriptor_20_3e_5135',['BaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20stridedslicequeuedescriptor_20_3e_5136',['BaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20subtractionqueuedescriptor_20_3e_5137',['BaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20tilequeuedescriptor_20_3e_5138',['BaseWorkload&lt; TileQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5139',['BaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20transposequeuedescriptor_20_3e_5140',['BaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5141',['BaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['baseworkload_3c_20unmapqueuedescriptor_20_3e_5142',['BaseWorkload&lt; UnmapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.html',1,'armnn']]],
  ['batchmatmul_5143',['BatchMatMul',['../classarmnn_1_1_batch_mat_mul.html',1,'armnn']]],
  ['batchmatmuldescriptor_5144',['BatchMatMulDescriptor',['../structarmnn_1_1_batch_mat_mul_descriptor.html',1,'armnn']]],
  ['batchmatmullayer_5145',['BatchMatMulLayer',['../classarmnn_1_1_batch_mat_mul_layer.html',1,'armnn']]],
  ['batchmatmulqueuedescriptor_5146',['BatchMatMulQueueDescriptor',['../structarmnn_1_1_batch_mat_mul_queue_descriptor.html',1,'armnn']]],
  ['batchnormalizationdescriptor_5147',['BatchNormalizationDescriptor',['../structarmnn_1_1_batch_normalization_descriptor.html',1,'armnn']]],
  ['batchnormalizationlayer_5148',['BatchNormalizationLayer',['../classarmnn_1_1_batch_normalization_layer.html',1,'armnn']]],
  ['batchnormalizationqueuedescriptor_5149',['BatchNormalizationQueueDescriptor',['../structarmnn_1_1_batch_normalization_queue_descriptor.html',1,'armnn']]],
  ['batchtospacenddescriptor_5150',['BatchToSpaceNdDescriptor',['../structarmnn_1_1_batch_to_space_nd_descriptor.html',1,'armnn']]],
  ['batchtospacendlayer_5151',['BatchToSpaceNdLayer',['../classarmnn_1_1_batch_to_space_nd_layer.html',1,'armnn']]],
  ['batchtospacendqueuedescriptor_5152',['BatchToSpaceNdQueueDescriptor',['../structarmnn_1_1_batch_to_space_nd_queue_descriptor.html',1,'armnn']]],
  ['bfloat16_5153',['BFloat16',['../classarmnn_1_1_b_float16.html',1,'armnn']]],
  ['biasandweightstypescompatible_5154',['BiasAndWeightsTypesCompatible',['../structarmnn_1_1_bias_and_weights_types_compatible.html',1,'armnn']]],
  ['biasandweightstypesmatch_5155',['BiasAndWeightsTypesMatch',['../structarmnn_1_1_bias_and_weights_types_match.html',1,'armnn']]],
  ['bindablelayer_5156',['BindableLayer',['../classarmnn_1_1_bindable_layer.html',1,'armnn']]],
  ['bindingpointinfo_5157',['BindingPointInfo',['../structarmnn_deserializer_1_1_binding_point_info.html',1,'armnnDeserializer']]],
  ['booleandecoder_5158',['BooleanDecoder',['../classarmnn_1_1_boolean_decoder.html',1,'armnn']]],
  ['booleandecoderbool_5159',['BooleanDecoderBool',['../classarmnn_1_1_boolean_decoder_bool.html',1,'armnn']]],
  ['booleanencoder_5160',['BooleanEncoder',['../classarmnn_1_1_boolean_encoder.html',1,'armnn']]],
  ['broadcastloop_5161',['BroadcastLoop',['../structarmnn_1_1_broadcast_loop.html',1,'armnn']]],
  ['bufferstorage_5162',['BufferStorage',['../structarmnn_1_1_buffer_storage.html',1,'armnn']]]
];
