var searchData=
[
  ['l2normalizationdescriptor_5508',['L2NormalizationDescriptor',['../structarmnn_1_1_l2_normalization_descriptor.html',1,'armnn']]],
  ['l2normalizationlayer_5509',['L2NormalizationLayer',['../classarmnn_1_1_l2_normalization_layer.html',1,'armnn']]],
  ['l2normalizationqueuedescriptor_5510',['L2NormalizationQueueDescriptor',['../structarmnn_1_1_l2_normalization_queue_descriptor.html',1,'armnn']]],
  ['layer_5511',['Layer',['../classarmnn_1_1_layer.html',1,'armnn']]],
  ['layeringraph_3c_20constantlayer_20_3e_5512',['LayerInGraph&lt; ConstantLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_constant_layer_01_4.html',1,'armnn::Graph']]],
  ['layeringraph_3c_20inputlayer_20_3e_5513',['LayerInGraph&lt; InputLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_input_layer_01_4.html',1,'armnn::Graph']]],
  ['layeringraph_3c_20outputlayer_20_3e_5514',['LayerInGraph&lt; OutputLayer &gt;',['../classarmnn_1_1_graph_1_1_layer_in_graph_3_01_output_layer_01_4.html',1,'armnn::Graph']]],
  ['layerinputhandle_5515',['LayerInputHandle',['../classarmnn__driver_1_1_layer_input_handle.html',1,'armnn_driver']]],
  ['layernameandtypecheck_5516',['LayerNameAndTypeCheck',['../class_layer_name_and_type_check.html',1,'']]],
  ['layersupportbase_5517',['LayerSupportBase',['../classarmnn_1_1_layer_support_base.html',1,'armnn']]],
  ['layersupporthandle_5518',['LayerSupportHandle',['../classarmnn_1_1_layer_support_handle.html',1,'armnn']]],
  ['layertypeofimpl_5519',['LayerTypeOfImpl',['../structarmnn_1_1_layer_type_of_impl.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aactivation_20_3e_5520',['LayerTypeOfImpl&lt; LayerType::Activation &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_activation_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aaddition_20_3e_5521',['LayerTypeOfImpl&lt; LayerType::Addition &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_addition_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aargminmax_20_3e_5522',['LayerTypeOfImpl&lt; LayerType::ArgMinMax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_arg_min_max_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchmatmul_20_3e_5523',['LayerTypeOfImpl&lt; LayerType::BatchMatMul &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_mat_mul_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchnormalization_20_3e_5524',['LayerTypeOfImpl&lt; LayerType::BatchNormalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3abatchtospacend_20_3e_5525',['LayerTypeOfImpl&lt; LayerType::BatchToSpaceNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_batch_to_space_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3acast_20_3e_5526',['LayerTypeOfImpl&lt; LayerType::Cast &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_cast_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3achannelshuffle_20_3e_5527',['LayerTypeOfImpl&lt; LayerType::ChannelShuffle &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_channel_shuffle_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3acomparison_20_3e_5528',['LayerTypeOfImpl&lt; LayerType::Comparison &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_comparison_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconcat_20_3e_5529',['LayerTypeOfImpl&lt; LayerType::Concat &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_concat_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconstant_20_3e_5530',['LayerTypeOfImpl&lt; LayerType::Constant &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_constant_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp16tofp32_20_3e_5531',['LayerTypeOfImpl&lt; LayerType::ConvertFp16ToFp32 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp16_to_fp32_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvertfp32tofp16_20_3e_5532',['LayerTypeOfImpl&lt; LayerType::ConvertFp32ToFp16 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convert_fp32_to_fp16_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvolution2d_20_3e_5533',['LayerTypeOfImpl&lt; LayerType::Convolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convolution2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aconvolution3d_20_3e_5534',['LayerTypeOfImpl&lt; LayerType::Convolution3d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_convolution3d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adebug_20_3e_5535',['LayerTypeOfImpl&lt; LayerType::Debug &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_debug_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adepthtospace_20_3e_5536',['LayerTypeOfImpl&lt; LayerType::DepthToSpace &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_depth_to_space_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adepthwiseconvolution2d_20_3e_5537',['LayerTypeOfImpl&lt; LayerType::DepthwiseConvolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_depthwise_convolution2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adequantize_20_3e_5538',['LayerTypeOfImpl&lt; LayerType::Dequantize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_dequantize_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adetectionpostprocess_20_3e_5539',['LayerTypeOfImpl&lt; LayerType::DetectionPostProcess &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_detection_post_process_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3adivision_20_3e_5540',['LayerTypeOfImpl&lt; LayerType::Division &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_division_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aelementwisebinary_20_3e_5541',['LayerTypeOfImpl&lt; LayerType::ElementwiseBinary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_elementwise_binary_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aelementwiseunary_20_3e_5542',['LayerTypeOfImpl&lt; LayerType::ElementwiseUnary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_elementwise_unary_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afakequantization_20_3e_5543',['LayerTypeOfImpl&lt; LayerType::FakeQuantization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fake_quantization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afill_20_3e_5544',['LayerTypeOfImpl&lt; LayerType::Fill &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fill_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afloor_20_3e_5545',['LayerTypeOfImpl&lt; LayerType::Floor &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_floor_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3afullyconnected_20_3e_5546',['LayerTypeOfImpl&lt; LayerType::FullyConnected &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_fully_connected_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3agather_20_3e_5547',['LayerTypeOfImpl&lt; LayerType::Gather &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_gather_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3agathernd_20_3e_5548',['LayerTypeOfImpl&lt; LayerType::GatherNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_gather_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ainput_20_3e_5549',['LayerTypeOfImpl&lt; LayerType::Input &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_input_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ainstancenormalization_20_3e_5550',['LayerTypeOfImpl&lt; LayerType::InstanceNormalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_instance_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3al2normalization_20_3e_5551',['LayerTypeOfImpl&lt; LayerType::L2Normalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_l2_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alogicalbinary_20_3e_5552',['LayerTypeOfImpl&lt; LayerType::LogicalBinary &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_logical_binary_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alogsoftmax_20_3e_5553',['LayerTypeOfImpl&lt; LayerType::LogSoftmax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_log_softmax_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3alstm_20_3e_5554',['LayerTypeOfImpl&lt; LayerType::Lstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amap_20_3e_5555',['LayerTypeOfImpl&lt; LayerType::Map &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_map_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amaximum_20_3e_5556',['LayerTypeOfImpl&lt; LayerType::Maximum &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_maximum_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amean_20_3e_5557',['LayerTypeOfImpl&lt; LayerType::Mean &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mean_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amemcopy_20_3e_5558',['LayerTypeOfImpl&lt; LayerType::MemCopy &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mem_copy_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amemimport_20_3e_5559',['LayerTypeOfImpl&lt; LayerType::MemImport &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_mem_import_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amerge_20_3e_5560',['LayerTypeOfImpl&lt; LayerType::Merge &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_merge_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aminimum_20_3e_5561',['LayerTypeOfImpl&lt; LayerType::Minimum &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_minimum_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3amultiplication_20_3e_5562',['LayerTypeOfImpl&lt; LayerType::Multiplication &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_multiplication_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3anormalization_20_3e_5563',['LayerTypeOfImpl&lt; LayerType::Normalization &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_normalization_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aoutput_20_3e_5564',['LayerTypeOfImpl&lt; LayerType::Output &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_output_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apad_20_3e_5565',['LayerTypeOfImpl&lt; LayerType::Pad &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pad_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apermute_20_3e_5566',['LayerTypeOfImpl&lt; LayerType::Permute &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_permute_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apooling2d_20_3e_5567',['LayerTypeOfImpl&lt; LayerType::Pooling2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pooling2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3apooling3d_20_3e_5568',['LayerTypeOfImpl&lt; LayerType::Pooling3d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pooling3d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aprecompiled_20_3e_5569',['LayerTypeOfImpl&lt; LayerType::PreCompiled &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_pre_compiled_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aprelu_20_3e_5570',['LayerTypeOfImpl&lt; LayerType::Prelu &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_prelu_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aqlstm_20_3e_5571',['LayerTypeOfImpl&lt; LayerType::QLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_q_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aquantize_20_3e_5572',['LayerTypeOfImpl&lt; LayerType::Quantize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_quantize_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aquantizedlstm_20_3e_5573',['LayerTypeOfImpl&lt; LayerType::QuantizedLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_quantized_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3arank_20_3e_5574',['LayerTypeOfImpl&lt; LayerType::Rank &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_rank_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areduce_20_3e_5575',['LayerTypeOfImpl&lt; LayerType::Reduce &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reduce_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areshape_20_3e_5576',['LayerTypeOfImpl&lt; LayerType::Reshape &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reshape_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aresize_20_3e_5577',['LayerTypeOfImpl&lt; LayerType::Resize &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_resize_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3areversev2_20_3e_5578',['LayerTypeOfImpl&lt; LayerType::ReverseV2 &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_reverse_v2_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3ashape_20_3e_5579',['LayerTypeOfImpl&lt; LayerType::Shape &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_shape_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aslice_20_3e_5580',['LayerTypeOfImpl&lt; LayerType::Slice &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_slice_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asoftmax_20_3e_5581',['LayerTypeOfImpl&lt; LayerType::Softmax &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_softmax_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aspacetobatchnd_20_3e_5582',['LayerTypeOfImpl&lt; LayerType::SpaceToBatchNd &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_space_to_batch_nd_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aspacetodepth_20_3e_5583',['LayerTypeOfImpl&lt; LayerType::SpaceToDepth &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_space_to_depth_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asplitter_20_3e_5584',['LayerTypeOfImpl&lt; LayerType::Splitter &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_splitter_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astack_20_3e_5585',['LayerTypeOfImpl&lt; LayerType::Stack &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_stack_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astandin_20_3e_5586',['LayerTypeOfImpl&lt; LayerType::StandIn &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_stand_in_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3astridedslice_20_3e_5587',['LayerTypeOfImpl&lt; LayerType::StridedSlice &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_strided_slice_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3asubtraction_20_3e_5588',['LayerTypeOfImpl&lt; LayerType::Subtraction &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_subtraction_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aswitch_20_3e_5589',['LayerTypeOfImpl&lt; LayerType::Switch &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_switch_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atile_20_3e_5590',['LayerTypeOfImpl&lt; LayerType::Tile &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_tile_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atranspose_20_3e_5591',['LayerTypeOfImpl&lt; LayerType::Transpose &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_transpose_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3atransposeconvolution2d_20_3e_5592',['LayerTypeOfImpl&lt; LayerType::TransposeConvolution2d &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_transpose_convolution2d_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aunidirectionalsequencelstm_20_3e_5593',['LayerTypeOfImpl&lt; LayerType::UnidirectionalSequenceLstm &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_unidirectional_sequence_lstm_01_4.html',1,'armnn']]],
  ['layertypeofimpl_3c_20layertype_3a_3aunmap_20_3e_5594',['LayerTypeOfImpl&lt; LayerType::Unmap &gt;',['../structarmnn_1_1_layer_type_of_impl_3_01_layer_type_1_1_unmap_01_4.html',1,'armnn']]],
  ['layervalidationexception_5595',['LayerValidationException',['../classarmnn_1_1_layer_validation_exception.html',1,'armnn']]],
  ['layerwithparameters_5596',['LayerWithParameters',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20activationdescriptor_20_3e_5597',['LayerWithParameters&lt; ActivationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20argminmaxdescriptor_20_3e_5598',['LayerWithParameters&lt; ArgMinMaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20batchmatmuldescriptor_20_3e_5599',['LayerWithParameters&lt; BatchMatMulDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20batchnormalizationdescriptor_20_3e_5600',['LayerWithParameters&lt; BatchNormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20batchtospacenddescriptor_20_3e_5601',['LayerWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20channelshuffledescriptor_20_3e_5602',['LayerWithParameters&lt; ChannelShuffleDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20comparisondescriptor_20_3e_5603',['LayerWithParameters&lt; ComparisonDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20convolution2ddescriptor_20_3e_5604',['LayerWithParameters&lt; Convolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20convolution3ddescriptor_20_3e_5605',['LayerWithParameters&lt; Convolution3dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20depthtospacedescriptor_20_3e_5606',['LayerWithParameters&lt; DepthToSpaceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_5607',['LayerWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20detectionpostprocessdescriptor_20_3e_5608',['LayerWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20elementwisebinarydescriptor_20_3e_5609',['LayerWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20elementwiseunarydescriptor_20_3e_5610',['LayerWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20fakequantizationdescriptor_20_3e_5611',['LayerWithParameters&lt; FakeQuantizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20filldescriptor_20_3e_5612',['LayerWithParameters&lt; FillDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20fullyconnecteddescriptor_20_3e_5613',['LayerWithParameters&lt; FullyConnectedDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20gatherdescriptor_20_3e_5614',['LayerWithParameters&lt; GatherDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20instancenormalizationdescriptor_20_3e_5615',['LayerWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20l2normalizationdescriptor_20_3e_5616',['LayerWithParameters&lt; L2NormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20logicalbinarydescriptor_20_3e_5617',['LayerWithParameters&lt; LogicalBinaryDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20logsoftmaxdescriptor_20_3e_5618',['LayerWithParameters&lt; LogSoftmaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20lstmdescriptor_20_3e_5619',['LayerWithParameters&lt; LstmDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20meandescriptor_20_3e_5620',['LayerWithParameters&lt; MeanDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20normalizationdescriptor_20_3e_5621',['LayerWithParameters&lt; NormalizationDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20originsdescriptor_20_3e_5622',['LayerWithParameters&lt; OriginsDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20paddescriptor_20_3e_5623',['LayerWithParameters&lt; PadDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20permutedescriptor_20_3e_5624',['LayerWithParameters&lt; PermuteDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20pooling2ddescriptor_20_3e_5625',['LayerWithParameters&lt; Pooling2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20pooling3ddescriptor_20_3e_5626',['LayerWithParameters&lt; Pooling3dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20precompileddescriptor_20_3e_5627',['LayerWithParameters&lt; PreCompiledDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20qlstmdescriptor_20_3e_5628',['LayerWithParameters&lt; QLstmDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20reducedescriptor_20_3e_5629',['LayerWithParameters&lt; ReduceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20reshapedescriptor_20_3e_5630',['LayerWithParameters&lt; ReshapeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20resizedescriptor_20_3e_5631',['LayerWithParameters&lt; ResizeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20slicedescriptor_20_3e_5632',['LayerWithParameters&lt; SliceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20softmaxdescriptor_20_3e_5633',['LayerWithParameters&lt; SoftmaxDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20spacetobatchnddescriptor_20_3e_5634',['LayerWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20spacetodepthdescriptor_20_3e_5635',['LayerWithParameters&lt; SpaceToDepthDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20stackdescriptor_20_3e_5636',['LayerWithParameters&lt; StackDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20standindescriptor_20_3e_5637',['LayerWithParameters&lt; StandInDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20stridedslicedescriptor_20_3e_5638',['LayerWithParameters&lt; StridedSliceDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20tiledescriptor_20_3e_5639',['LayerWithParameters&lt; TileDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_5640',['LayerWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20transposedescriptor_20_3e_5641',['LayerWithParameters&lt; TransposeDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['layerwithparameters_3c_20viewsdescriptor_20_3e_5642',['LayerWithParameters&lt; ViewsDescriptor &gt;',['../classarmnn_1_1_layer_with_parameters.html',1,'armnn']]],
  ['loadednetwork_5643',['LoadedNetwork',['../classarmnn_1_1_loaded_network.html',1,'armnn']]],
  ['log_5644',['log',['../structarmnn_1_1log.html',1,'armnn']]],
  ['logicalbinarydescriptor_5645',['LogicalBinaryDescriptor',['../structarmnn_1_1_logical_binary_descriptor.html',1,'armnn']]],
  ['logicalbinaryfunction_5646',['LogicalBinaryFunction',['../structarmnn_1_1_logical_binary_function.html',1,'armnn']]],
  ['logicalbinarylayer_5647',['LogicalBinaryLayer',['../classarmnn_1_1_logical_binary_layer.html',1,'armnn']]],
  ['logicalbinaryqueuedescriptor_5648',['LogicalBinaryQueueDescriptor',['../structarmnn_1_1_logical_binary_queue_descriptor.html',1,'armnn']]],
  ['logicalunaryfunction_5649',['LogicalUnaryFunction',['../structarmnn_1_1_logical_unary_function.html',1,'armnn']]],
  ['logsink_5650',['LogSink',['../classarmnn_1_1_log_sink.html',1,'armnn']]],
  ['logsoftmaxlayer_5651',['LogSoftmaxLayer',['../classarmnn_1_1_log_softmax_layer.html',1,'armnn']]],
  ['logsoftmaxqueuedescriptor_5652',['LogSoftmaxQueueDescriptor',['../structarmnn_1_1_log_softmax_queue_descriptor.html',1,'armnn']]],
  ['lstmbasicparameters_5653',['LstmBasicParameters',['../structarmnn_1_1_lstm_basic_parameters.html',1,'armnn']]],
  ['lstmdescriptor_5654',['LstmDescriptor',['../structarmnn_1_1_lstm_descriptor.html',1,'armnn']]],
  ['lstminputparams_5655',['LstmInputParams',['../structarmnn_1_1_lstm_input_params.html',1,'armnn']]],
  ['lstminputparamsinfo_5656',['LstmInputParamsInfo',['../structarmnn_1_1_lstm_input_params_info.html',1,'armnn']]],
  ['lstmlayer_5657',['LstmLayer',['../classarmnn_1_1_lstm_layer.html',1,'armnn']]],
  ['lstmoptcifgparameters_5658',['LstmOptCifgParameters',['../structarmnn_1_1_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['lstmoptlayernormparameters_5659',['LstmOptLayerNormParameters',['../structarmnn_1_1_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['lstmoptpeepholeparameters_5660',['LstmOptPeepholeParameters',['../structarmnn_1_1_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['lstmoptprojectionparameters_5661',['LstmOptProjectionParameters',['../structarmnn_1_1_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['lstmqueuedescriptor_5662',['LstmQueueDescriptor',['../structarmnn_1_1_lstm_queue_descriptor.html',1,'armnn']]]
];
