var searchData=
[
  ['neonabsworkload_5702',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.html',1,'armnn']]],
  ['neonactivationworkload_5703',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.html',1,'armnn']]],
  ['neonadditionworkload_5704',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.html',1,'armnn']]],
  ['neonargminmaxworkload_5705',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.html',1,'armnn']]],
  ['neonbackend_5706',['NeonBackend',['../classarmnn_1_1_neon_backend.html',1,'armnn']]],
  ['neonbackendmodelcontext_5707',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.html',1,'armnn']]],
  ['neonbaseworkload_5708',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e_5709',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e_5710',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e_5711',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5712',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5713',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5714',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5715',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e_5716',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5717',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5718',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e_5719',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e_5720',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5721',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5722',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5723',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5724',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5725',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5726',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e_5727',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5728',['NeonBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5729',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e_5730',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5731',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e_5732',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e_5733',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5734',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5735',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5736',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e_5737',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e_5738',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e_5739',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e_5740',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e_5741',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e_5742',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_5743',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_5744',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e_5745',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e_5746',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5747',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e_5748',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e_5749',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e_5750',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e_5751',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e_5752',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e_5753',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e_5754',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e_5755',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5756',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5757',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e_5758',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e_5759',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_5760',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e_5761',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5762',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e_5763',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5764',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.html',1,'armnn']]],
  ['neonbatchmatmulworkload_5765',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.html',1,'armnn']]],
  ['neonbatchnormalizationworkload_5766',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.html',1,'armnn']]],
  ['neonbatchtospacendworkload_5767',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.html',1,'armnn']]],
  ['neoncastworkload_5768',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.html',1,'armnn']]],
  ['neonchannelshuffleworkload_5769',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.html',1,'armnn']]],
  ['neoncomparisonworkload_5770',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.html',1,'armnn']]],
  ['neonconcatworkload_5771',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.html',1,'armnn']]],
  ['neonconstantworkload_5772',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.html',1,'armnn']]],
  ['neonconvertfp16tofp32workload_5773',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.html',1,'armnn']]],
  ['neonconvertfp32tofp16workload_5774',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.html',1,'armnn']]],
  ['neonconvolution2dworkload_5775',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.html',1,'armnn']]],
  ['neonconvolution3dworkload_5776',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.html',1,'armnn']]],
  ['neondepthtospaceworkload_5777',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.html',1,'armnn']]],
  ['neondepthwiseconvolutionworkload_5778',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.html',1,'armnn']]],
  ['neondequantizeworkload_5779',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.html',1,'armnn']]],
  ['neondetectionpostprocessworkload_5780',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.html',1,'armnn']]],
  ['neondivisionworkload_5781',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.html',1,'armnn']]],
  ['neonelementwisebinaryworkload_5782',['NeonElementwiseBinaryWorkload',['../classarmnn_1_1_neon_elementwise_binary_workload.html',1,'armnn']]],
  ['neonexpworkload_5783',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.html',1,'armnn']]],
  ['neonfillworkload_5784',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.html',1,'armnn']]],
  ['neonfloorfloatworkload_5785',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.html',1,'armnn']]],
  ['neonfullyconnectedworkload_5786',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.html',1,'armnn']]],
  ['neongatherndworkload_5787',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.html',1,'armnn']]],
  ['neongatherworkload_5788',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.html',1,'armnn']]],
  ['neoninstancenormalizationworkload_5789',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.html',1,'armnn']]],
  ['neoninterceptorscheduler_5790',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.html',1,'armnn']]],
  ['neonl2normalizationfloatworkload_5791',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.html',1,'armnn']]],
  ['neonlayersupport_5792',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.html',1,'armnn']]],
  ['neonlogicalandworkload_5793',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.html',1,'armnn']]],
  ['neonlogicalnotworkload_5794',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.html',1,'armnn']]],
  ['neonlogicalorworkload_5795',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.html',1,'armnn']]],
  ['neonlogsoftmaxworkload_5796',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.html',1,'armnn']]],
  ['neonlogworkload_5797',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.html',1,'armnn']]],
  ['neonlstmfloatworkload_5798',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.html',1,'armnn']]],
  ['neonmaximumworkload_5799',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.html',1,'armnn']]],
  ['neonmeanworkload_5800',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.html',1,'armnn']]],
  ['neonmemorymanager_5801',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.html',1,'armnn']]],
  ['neonminimumworkload_5802',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.html',1,'armnn']]],
  ['neonmultiplicationworkload_5803',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.html',1,'armnn']]],
  ['neonnegworkload_5804',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.html',1,'armnn']]],
  ['neonnormalizationfloatworkload_5805',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.html',1,'armnn']]],
  ['neonpadworkload_5806',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.html',1,'armnn']]],
  ['neonpermuteworkload_5807',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.html',1,'armnn']]],
  ['neonpooling2dworkload_5808',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.html',1,'armnn']]],
  ['neonpooling3dworkload_5809',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.html',1,'armnn']]],
  ['neonpreluworkload_5810',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.html',1,'armnn']]],
  ['neonqlstmworkload_5811',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.html',1,'armnn']]],
  ['neonquantizedlstmworkload_5812',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.html',1,'armnn']]],
  ['neonquantizeworkload_5813',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.html',1,'armnn']]],
  ['neonrankworkload_5814',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.html',1,'armnn']]],
  ['neonreduceworkload_5815',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.html',1,'armnn']]],
  ['neonreshapeworkload_5816',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.html',1,'armnn']]],
  ['neonresizeworkload_5817',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.html',1,'armnn']]],
  ['neonrsqrtworkload_5818',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.html',1,'armnn']]],
  ['neonsinworkload_5819',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.html',1,'armnn']]],
  ['neonsliceworkload_5820',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.html',1,'armnn']]],
  ['neonsoftmaxworkload_5821',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.html',1,'armnn']]],
  ['neonspacetobatchndworkload_5822',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.html',1,'armnn']]],
  ['neonspacetodepthworkload_5823',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.html',1,'armnn']]],
  ['neonsplitterworkload_5824',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.html',1,'armnn']]],
  ['neonsqrtworkload_5825',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.html',1,'armnn']]],
  ['neonstackworkload_5826',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.html',1,'armnn']]],
  ['neonstridedsliceworkload_5827',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.html',1,'armnn']]],
  ['neonsubtensorhandle_5828',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.html',1,'armnn']]],
  ['neonsubtractionworkload_5829',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.html',1,'armnn']]],
  ['neontensordecorator_5830',['NeonTensorDecorator',['../classarmnn_1_1_neon_tensor_decorator.html',1,'armnn']]],
  ['neontensorhandle_5831',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.html',1,'armnn']]],
  ['neontensorhandledecorator_5832',['NeonTensorHandleDecorator',['../classarmnn_1_1_neon_tensor_handle_decorator.html',1,'armnn']]],
  ['neontensorhandlefactory_5833',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.html',1,'armnn']]],
  ['neontileworkload_5834',['NeonTileWorkload',['../classarmnn_1_1_neon_tile_workload.html',1,'armnn']]],
  ['neontimer_5835',['NeonTimer',['../classarmnn_1_1_neon_timer.html',1,'armnn']]],
  ['neontransposeconvolution2dworkload_5836',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.html',1,'armnn']]],
  ['neontransposeworkload_5837',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload_5838',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.html',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload_5839',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.html',1,'armnn']]],
  ['neonworkloadfactory_5840',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.html',1,'armnn']]],
  ['networkimpl_5841',['NetworkImpl',['../classarmnn_1_1_network_impl.html',1,'armnn']]],
  ['nodecontent_5842',['NodeContent',['../classarmnn_1_1_node_content.html',1,'armnn']]],
  ['normalizationdescriptor_5843',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.html',1,'armnn']]],
  ['normalizationlayer_5844',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.html',1,'armnn']]],
  ['normalizationqueuedescriptor_5845',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.html',1,'armnn']]],
  ['nothrowstrategy_5846',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.html',1,'armnn']]],
  ['nulldescriptor_5847',['NullDescriptor',['../structarmnn_1_1_null_descriptor.html',1,'armnn']]],
  ['nullpointerexception_5848',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.html',1,'armnn']]],
  ['nullworkload_5849',['NullWorkload',['../classarmnn_1_1_null_workload.html',1,'armnn']]]
];
