var searchData=
[
  ['sampledynamicadditionworkload_6163',['SampleDynamicAdditionWorkload',['../classsdb_1_1_sample_dynamic_addition_workload.html',1,'sdb']]],
  ['sampledynamiclayersupport_6164',['SampleDynamicLayerSupport',['../classsdb_1_1_sample_dynamic_layer_support.html',1,'sdb']]],
  ['sampledynamictensorhandlefactory_6165',['SampleDynamicTensorHandleFactory',['../classsdb_1_1_sample_dynamic_tensor_handle_factory.html',1,'sdb']]],
  ['sampledynamicworkloadfactory_6166',['SampleDynamicWorkloadFactory',['../classsdb_1_1_sample_dynamic_workload_factory.html',1,'sdb']]],
  ['samplememorymanager_6167',['SampleMemoryManager',['../classsdb_1_1_sample_memory_manager.html',1,'sdb']]],
  ['sampletensorhandle_6168',['SampleTensorHandle',['../classsdb_1_1_sample_tensor_handle.html',1,'sdb']]],
  ['scaledint32decoder_6169',['ScaledInt32Decoder',['../classarmnn_1_1_scaled_int32_decoder.html',1,'armnn']]],
  ['scaledint32peraxisdecoder_6170',['ScaledInt32PerAxisDecoder',['../classarmnn_1_1_scaled_int32_per_axis_decoder.html',1,'armnn']]],
  ['scopedprofilingevent_6171',['ScopedProfilingEvent',['../classarmnn_1_1_scoped_profiling_event.html',1,'armnn']]],
  ['scopedrecord_6172',['ScopedRecord',['../structarmnn_1_1_scoped_record.html',1,'armnn']]],
  ['scopedtensorhandle_6173',['ScopedTensorHandle',['../classarmnn_1_1_scoped_tensor_handle.html',1,'armnn']]],
  ['selectivequantizer_6174',['SelectiveQuantizer',['../structarmnn_utils_1_1_selective_quantizer.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3abfloat16_2c_20false_20_3e_6175',['SelectiveQuantizer&lt; armnn::BFloat16, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_b_float16_00_01false_01_4.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3ahalf_2c_20false_20_3e_6176',['SelectiveQuantizer&lt; armnn::Half, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_half_00_01false_01_4.html',1,'armnnUtils']]],
  ['selectivequantizer_3c_20t_2c_20false_20_3e_6177',['SelectiveQuantizer&lt; T, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01_t_00_01false_01_4.html',1,'armnnUtils']]],
  ['serializerimpl_6178',['SerializerImpl',['../classarmnn_serializer_1_1_i_serializer_1_1_serializer_impl.html',1,'armnnSerializer::ISerializer']]],
  ['serializerstrategy_6179',['SerializerStrategy',['../classarmnn_serializer_1_1_serializer_strategy.html',1,'armnnSerializer']]],
  ['shapelayer_6180',['ShapeLayer',['../classarmnn_1_1_shape_layer.html',1,'armnn']]],
  ['shapequeuedescriptor_6181',['ShapeQueueDescriptor',['../structarmnn_1_1_shape_queue_descriptor.html',1,'armnn']]],
  ['shapesarebroadcastcompatible_6182',['ShapesAreBroadcastCompatible',['../structarmnn_1_1_shapes_are_broadcast_compatible.html',1,'armnn']]],
  ['shapesaresamerank_6183',['ShapesAreSameRank',['../structarmnn_1_1_shapes_are_same_rank.html',1,'armnn']]],
  ['shapesaresametotalsize_6184',['ShapesAreSameTotalSize',['../structarmnn_1_1_shapes_are_same_total_size.html',1,'armnn']]],
  ['simplelogger_6185',['SimpleLogger',['../classarmnn_1_1_simple_logger.html',1,'armnn']]],
  ['sin_6186',['sin',['../structarmnn_1_1sin.html',1,'armnn']]],
  ['singleaxisprioritylist_6187',['SingleAxisPriorityList',['../classarmnn_1_1_single_axis_priority_list.html',1,'armnn']]],
  ['slicedescriptor_6188',['SliceDescriptor',['../structarmnn_1_1_slice_descriptor.html',1,'armnn']]],
  ['slicelayer_6189',['SliceLayer',['../classarmnn_1_1_slice_layer.html',1,'armnn']]],
  ['slicequeuedescriptor_6190',['SliceQueueDescriptor',['../structarmnn_1_1_slice_queue_descriptor.html',1,'armnn']]],
  ['softmaxdescriptor_6191',['SoftmaxDescriptor',['../structarmnn_1_1_softmax_descriptor.html',1,'armnn']]],
  ['softmaxlayer_6192',['SoftmaxLayer',['../classarmnn_1_1_softmax_layer.html',1,'armnn']]],
  ['softmaxqueuedescriptor_6193',['SoftmaxQueueDescriptor',['../structarmnn_1_1_softmax_queue_descriptor.html',1,'armnn']]],
  ['spacetobatchnddescriptor_6194',['SpaceToBatchNdDescriptor',['../structarmnn_1_1_space_to_batch_nd_descriptor.html',1,'armnn']]],
  ['spacetobatchndlayer_6195',['SpaceToBatchNdLayer',['../classarmnn_1_1_space_to_batch_nd_layer.html',1,'armnn']]],
  ['spacetobatchndqueuedescriptor_6196',['SpaceToBatchNdQueueDescriptor',['../structarmnn_1_1_space_to_batch_nd_queue_descriptor.html',1,'armnn']]],
  ['spacetodepthdescriptor_6197',['SpaceToDepthDescriptor',['../structarmnn_1_1_space_to_depth_descriptor.html',1,'armnn']]],
  ['spacetodepthlayer_6198',['SpaceToDepthLayer',['../classarmnn_1_1_space_to_depth_layer.html',1,'armnn']]],
  ['spacetodepthqueuedescriptor_6199',['SpaceToDepthQueueDescriptor',['../structarmnn_1_1_space_to_depth_queue_descriptor.html',1,'armnn']]],
  ['splitterlayer_6200',['SplitterLayer',['../classarmnn_1_1_splitter_layer.html',1,'armnn']]],
  ['splitterqueuedescriptor_6201',['SplitterQueueDescriptor',['../structarmnn_1_1_splitter_queue_descriptor.html',1,'armnn']]],
  ['sqrt_6202',['sqrt',['../structarmnn_1_1sqrt.html',1,'armnn']]],
  ['squareddifference_6203',['squaredDifference',['../structarmnn_1_1squared_difference.html',1,'armnn']]],
  ['squashequalsiblingsimpl_6204',['SquashEqualSiblingsImpl',['../classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl.html',1,'armnn::optimizations']]],
  ['stackdescriptor_6205',['StackDescriptor',['../structarmnn_1_1_stack_descriptor.html',1,'armnn']]],
  ['stacklayer_6206',['StackLayer',['../classarmnn_1_1_stack_layer.html',1,'armnn']]],
  ['stackqueuedescriptor_6207',['StackQueueDescriptor',['../structarmnn_1_1_stack_queue_descriptor.html',1,'armnn']]],
  ['standardoutputsink_6208',['StandardOutputSink',['../classarmnn_1_1_standard_output_sink.html',1,'armnn']]],
  ['standindescriptor_6209',['StandInDescriptor',['../structarmnn_1_1_stand_in_descriptor.html',1,'armnn']]],
  ['standinlayer_6210',['StandInLayer',['../classarmnn_1_1_stand_in_layer.html',1,'armnn']]],
  ['staticregistryinitializer_6211',['StaticRegistryInitializer',['../structarmnn_1_1_backend_registry_1_1_static_registry_initializer.html',1,'armnn::BackendRegistry']]],
  ['strategybase_6212',['StrategyBase',['../classarmnn_1_1_strategy_base.html',1,'armnn']]],
  ['strategyfactory_6213',['StrategyFactory',['../structarmnn_1_1_strategy_factory.html',1,'armnn']]],
  ['strategyvalidator_6214',['StrategyValidator',['../classarmnn_1_1_strategy_validator.html',1,'armnn']]],
  ['stridedslicedescriptor_6215',['StridedSliceDescriptor',['../structarmnn_1_1_strided_slice_descriptor.html',1,'armnn']]],
  ['stridedslicelayer_6216',['StridedSliceLayer',['../classarmnn_1_1_strided_slice_layer.html',1,'armnn']]],
  ['stridedslicequeuedescriptor_6217',['StridedSliceQueueDescriptor',['../structarmnn_1_1_strided_slice_queue_descriptor.html',1,'armnn']]],
  ['stringifylayerparameters_6218',['StringifyLayerParameters',['../structarmnn_1_1_stringify_layer_parameters.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20activationdescriptor_20_3e_6219',['StringifyLayerParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_activation_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchmatmuldescriptor_20_3e_6220',['StringifyLayerParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_mat_mul_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchnormalizationdescriptor_20_3e_6221',['StringifyLayerParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchtospacenddescriptor_20_3e_6222',['StringifyLayerParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_to_space_nd_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20channelshuffledescriptor_20_3e_6223',['StringifyLayerParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_channel_shuffle_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20comparisondescriptor_20_3e_6224',['StringifyLayerParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_comparison_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution2ddescriptor_20_3e_6225',['StringifyLayerParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution3ddescriptor_20_3e_6226',['StringifyLayerParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution3d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_6227',['StringifyLayerParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_depthwise_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20detectionpostprocessdescriptor_20_3e_6228',['StringifyLayerParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_detection_post_process_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwisebinarydescriptor_20_3e_6229',['StringifyLayerParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_binary_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwiseunarydescriptor_20_3e_6230',['StringifyLayerParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_unary_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fakequantizationdescriptor_20_3e_6231',['StringifyLayerParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fake_quantization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20fullyconnecteddescriptor_20_3e_6232',['StringifyLayerParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fully_connected_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20gatherdescriptor_20_3e_6233',['StringifyLayerParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_gather_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20l2normalizationdescriptor_20_3e_6234',['StringifyLayerParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_l2_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20lstmdescriptor_20_3e_6235',['StringifyLayerParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_lstm_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20meandescriptor_20_3e_6236',['StringifyLayerParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_mean_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20normalizationdescriptor_20_3e_6237',['StringifyLayerParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_normalization_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20originsdescriptor_20_3e_6238',['StringifyLayerParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_origins_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20paddescriptor_20_3e_6239',['StringifyLayerParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pad_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20permutedescriptor_20_3e_6240',['StringifyLayerParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_permute_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling2ddescriptor_20_3e_6241',['StringifyLayerParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling3ddescriptor_20_3e_6242',['StringifyLayerParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling3d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20precompileddescriptor_20_3e_6243',['StringifyLayerParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pre_compiled_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20reducedescriptor_20_3e_6244',['StringifyLayerParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reduce_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20reshapedescriptor_20_3e_6245',['StringifyLayerParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reshape_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20resizedescriptor_20_3e_6246',['StringifyLayerParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_resize_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20softmaxdescriptor_20_3e_6247',['StringifyLayerParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_softmax_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetobatchnddescriptor_20_3e_6248',['StringifyLayerParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_batch_nd_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetodepthdescriptor_20_3e_6249',['StringifyLayerParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_depth_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20stackdescriptor_20_3e_6250',['StringifyLayerParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_stack_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20stridedslicedescriptor_20_3e_6251',['StringifyLayerParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_strided_slice_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20tiledescriptor_20_3e_6252',['StringifyLayerParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_tile_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposeconvolution2ddescriptor_20_3e_6253',['StringifyLayerParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_convolution2d_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposedescriptor_20_3e_6254',['StringifyLayerParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_descriptor_01_4.html',1,'armnn']]],
  ['stringifylayerparameters_3c_20viewsdescriptor_20_3e_6255',['StringifyLayerParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_views_descriptor_01_4.html',1,'armnn']]],
  ['stringmapping_6256',['StringMapping',['../structarmnn_1_1_string_mapping.html',1,'armnn']]],
  ['subgraphview_6257',['SubgraphView',['../classarmnn_1_1_subgraph_view.html',1,'armnn']]],
  ['subgraphviewselector_6258',['SubgraphViewSelector',['../classarmnn_1_1_subgraph_view_selector.html',1,'armnn']]],
  ['substitutionpair_6259',['SubstitutionPair',['../structarmnn_1_1_optimization_views_1_1_substitution_pair.html',1,'armnn::OptimizationViews']]],
  ['subtractionlayer_6260',['SubtractionLayer',['../classarmnn_1_1_subtraction_layer.html',1,'armnn']]],
  ['subtractionqueuedescriptor_6261',['SubtractionQueueDescriptor',['../structarmnn_1_1_subtraction_queue_descriptor.html',1,'armnn']]],
  ['switchlayer_6262',['SwitchLayer',['../classarmnn_1_1_switch_layer.html',1,'armnn']]],
  ['switchqueuedescriptor_6263',['SwitchQueueDescriptor',['../structarmnn_1_1_switch_queue_descriptor.html',1,'armnn']]],
  ['syncmemgenericworkload_6264',['SyncMemGenericWorkload',['../classarmnn_1_1_sync_mem_generic_workload.html',1,'armnn']]]
];
