var searchData=
[
  ['qasymm8decoder_5937',['QASymm8Decoder',['../classarmnn_1_1_q_a_symm8_decoder.html',1,'armnn']]],
  ['qasymm8encoder_5938',['QASymm8Encoder',['../classarmnn_1_1_q_a_symm8_encoder.html',1,'armnn']]],
  ['qasymms8decoder_5939',['QASymmS8Decoder',['../classarmnn_1_1_q_a_symm_s8_decoder.html',1,'armnn']]],
  ['qasymms8encoder_5940',['QASymmS8Encoder',['../classarmnn_1_1_q_a_symm_s8_encoder.html',1,'armnn']]],
  ['qlstmbasicparameters_5941',['QLstmBasicParameters',['../structarmnn_1_1_q_lstm_basic_parameters.html',1,'armnn']]],
  ['qlstmdescriptor_5942',['QLstmDescriptor',['../structarmnn_1_1_q_lstm_descriptor.html',1,'armnn']]],
  ['qlstmlayer_5943',['QLstmLayer',['../classarmnn_1_1_q_lstm_layer.html',1,'armnn']]],
  ['qlstmoptcifgparameters_5944',['QLstmOptCifgParameters',['../structarmnn_1_1_q_lstm_opt_cifg_parameters.html',1,'armnn']]],
  ['qlstmoptlayernormparameters_5945',['QLstmOptLayerNormParameters',['../structarmnn_1_1_q_lstm_opt_layer_norm_parameters.html',1,'armnn']]],
  ['qlstmoptpeepholeparameters_5946',['QLstmOptPeepholeParameters',['../structarmnn_1_1_q_lstm_opt_peephole_parameters.html',1,'armnn']]],
  ['qlstmoptprojectionparameters_5947',['QLstmOptProjectionParameters',['../structarmnn_1_1_q_lstm_opt_projection_parameters.html',1,'armnn']]],
  ['qlstmqueuedescriptor_5948',['QLstmQueueDescriptor',['../structarmnn_1_1_q_lstm_queue_descriptor.html',1,'armnn']]],
  ['qsymm16decoder_5949',['QSymm16Decoder',['../classarmnn_1_1_q_symm16_decoder.html',1,'armnn']]],
  ['qsymm16encoder_5950',['QSymm16Encoder',['../classarmnn_1_1_q_symm16_encoder.html',1,'armnn']]],
  ['qsymm8peraxisdecoder_5951',['QSymm8PerAxisDecoder',['../classarmnn_1_1_q_symm8_per_axis_decoder.html',1,'armnn']]],
  ['qsymm8peraxisencoder_5952',['QSymm8PerAxisEncoder',['../classarmnn_1_1_q_symm8_per_axis_encoder.html',1,'armnn']]],
  ['qsymms8decoder_5953',['QSymmS8Decoder',['../classarmnn_1_1_q_symm_s8_decoder.html',1,'armnn']]],
  ['qsymms8encoder_5954',['QSymmS8Encoder',['../classarmnn_1_1_q_symm_s8_encoder.html',1,'armnn']]],
  ['quantizationparametersareequal_5955',['QuantizationParametersAreEqual',['../structarmnn_1_1_quantization_parameters_are_equal.html',1,'armnn']]],
  ['quantizedlstminputparams_5956',['QuantizedLstmInputParams',['../structarmnn_1_1_quantized_lstm_input_params.html',1,'armnn']]],
  ['quantizedlstminputparamsinfo_5957',['QuantizedLstmInputParamsInfo',['../structarmnn_1_1_quantized_lstm_input_params_info.html',1,'armnn']]],
  ['quantizedlstmlayer_5958',['QuantizedLstmLayer',['../classarmnn_1_1_quantized_lstm_layer.html',1,'armnn']]],
  ['quantizedlstmparameters_5959',['QuantizedLstmParameters',['../structarmnn_1_1_quantized_lstm_parameters.html',1,'armnn']]],
  ['quantizedlstmqueuedescriptor_5960',['QuantizedLstmQueueDescriptor',['../structarmnn_1_1_quantized_lstm_queue_descriptor.html',1,'armnn']]],
  ['quantizedmultipliersmallerthanone_5961',['QuantizedMultiplierSmallerThanOne',['../structarmnn_1_1_quantized_multiplier_smaller_than_one.html',1,'armnn']]],
  ['quantizelayer_5962',['QuantizeLayer',['../classarmnn_1_1_quantize_layer.html',1,'armnn']]],
  ['quantizequeuedescriptor_5963',['QuantizeQueueDescriptor',['../structarmnn_1_1_quantize_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptor_5964',['QueueDescriptor',['../structarmnn_1_1_queue_descriptor.html',1,'armnn']]],
  ['queuedescriptorwithparameters_5965',['QueueDescriptorWithParameters',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20activationdescriptor_20_3e_5966',['QueueDescriptorWithParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20argminmaxdescriptor_20_3e_5967',['QueueDescriptorWithParameters&lt; ArgMinMaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchmatmuldescriptor_20_3e_5968',['QueueDescriptorWithParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchnormalizationdescriptor_20_3e_5969',['QueueDescriptorWithParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchtospacenddescriptor_20_3e_5970',['QueueDescriptorWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20channelshuffledescriptor_20_3e_5971',['QueueDescriptorWithParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20comparisondescriptor_20_3e_5972',['QueueDescriptorWithParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution2ddescriptor_20_3e_5973',['QueueDescriptorWithParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution3ddescriptor_20_3e_5974',['QueueDescriptorWithParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthtospacedescriptor_20_3e_5975',['QueueDescriptorWithParameters&lt; DepthToSpaceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_5976',['QueueDescriptorWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20detectionpostprocessdescriptor_20_3e_5977',['QueueDescriptorWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwisebinarydescriptor_20_3e_5978',['QueueDescriptorWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwiseunarydescriptor_20_3e_5979',['QueueDescriptorWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fakequantizationdescriptor_20_3e_5980',['QueueDescriptorWithParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20filldescriptor_20_3e_5981',['QueueDescriptorWithParameters&lt; FillDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fullyconnecteddescriptor_20_3e_5982',['QueueDescriptorWithParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20gatherdescriptor_20_3e_5983',['QueueDescriptorWithParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20instancenormalizationdescriptor_20_3e_5984',['QueueDescriptorWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20l2normalizationdescriptor_20_3e_5985',['QueueDescriptorWithParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logicalbinarydescriptor_20_3e_5986',['QueueDescriptorWithParameters&lt; LogicalBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logsoftmaxdescriptor_20_3e_5987',['QueueDescriptorWithParameters&lt; LogSoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20lstmdescriptor_20_3e_5988',['QueueDescriptorWithParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20meandescriptor_20_3e_5989',['QueueDescriptorWithParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20normalizationdescriptor_20_3e_5990',['QueueDescriptorWithParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20originsdescriptor_20_3e_5991',['QueueDescriptorWithParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20paddescriptor_20_3e_5992',['QueueDescriptorWithParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20permutedescriptor_20_3e_5993',['QueueDescriptorWithParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling2ddescriptor_20_3e_5994',['QueueDescriptorWithParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling3ddescriptor_20_3e_5995',['QueueDescriptorWithParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20precompileddescriptor_20_3e_5996',['QueueDescriptorWithParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20qlstmdescriptor_20_3e_5997',['QueueDescriptorWithParameters&lt; QLstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reducedescriptor_20_3e_5998',['QueueDescriptorWithParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reshapedescriptor_20_3e_5999',['QueueDescriptorWithParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20resizedescriptor_20_3e_6000',['QueueDescriptorWithParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20slicedescriptor_20_3e_6001',['QueueDescriptorWithParameters&lt; SliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20softmaxdescriptor_20_3e_6002',['QueueDescriptorWithParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetobatchnddescriptor_20_3e_6003',['QueueDescriptorWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetodepthdescriptor_20_3e_6004',['QueueDescriptorWithParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stackdescriptor_20_3e_6005',['QueueDescriptorWithParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stridedslicedescriptor_20_3e_6006',['QueueDescriptorWithParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20tiledescriptor_20_3e_6007',['QueueDescriptorWithParameters&lt; TileDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_6008',['QueueDescriptorWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposedescriptor_20_3e_6009',['QueueDescriptorWithParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20viewsdescriptor_20_3e_6010',['QueueDescriptorWithParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.html',1,'armnn']]]
];
