var searchData=
[
  ['tensor_6265',['Tensor',['../classarmnn_1_1_tensor.html',1,'armnn']]],
  ['tensorbufferarrayview_6266',['TensorBufferArrayView',['../classarmnn_1_1_tensor_buffer_array_view.html',1,'armnn']]],
  ['tensorhandle_6267',['TensorHandle',['../classarmnn_1_1_tensor_handle.html',1,'armnn']]],
  ['tensorhandlefactoryregistry_6268',['TensorHandleFactoryRegistry',['../classarmnn_1_1_tensor_handle_factory_registry.html',1,'armnn']]],
  ['tensorinfo_6269',['TensorInfo',['../classarmnn_1_1_tensor_info.html',1,'armnn']]],
  ['tensormemory_6270',['TensorMemory',['../structarmnn_1_1_tensor_memory.html',1,'armnn']]],
  ['tensornumdimensionsarecorrect_6271',['TensorNumDimensionsAreCorrect',['../structarmnn_1_1_tensor_num_dimensions_are_correct.html',1,'armnn']]],
  ['tensornumdimensionsaregreaterorequalto_6272',['TensorNumDimensionsAreGreaterOrEqualTo',['../structarmnn_1_1_tensor_num_dimensions_are_greater_or_equal_to.html',1,'armnn']]],
  ['tensorshape_6273',['TensorShape',['../classarmnn_1_1_tensor_shape.html',1,'armnn']]],
  ['tfliteparserimpl_6274',['TfLiteParserImpl',['../classarmnn_tf_lite_parser_1_1_tf_lite_parser_impl.html',1,'armnnTfLiteParser']]],
  ['tfliteparseroptions_6275',['TfLiteParserOptions',['../structarmnn_tf_lite_parser_1_1_i_tf_lite_parser_1_1_tf_lite_parser_options.html',1,'armnnTfLiteParser::ITfLiteParser']]],
  ['threadpool_6276',['Threadpool',['../classarmnn_1_1experimental_1_1_threadpool.html',1,'armnn::experimental']]],
  ['throwingstrategy_6277',['ThrowingStrategy',['../structarmnn_1_1_throwing_strategy.html',1,'armnn']]],
  ['tiledescriptor_6278',['TileDescriptor',['../structarmnn_1_1_tile_descriptor.html',1,'armnn']]],
  ['tilelayer_6279',['TileLayer',['../classarmnn_1_1_tile_layer.html',1,'armnn']]],
  ['tilequeuedescriptor_6280',['TileQueueDescriptor',['../structarmnn_1_1_tile_queue_descriptor.html',1,'armnn']]],
  ['timeoutexception_6281',['TimeoutException',['../classarmnn_1_1_timeout_exception.html',1,'armnn']]],
  ['tosaassertsize_6282',['TosaAssertSize',['../struct_tosa_assert_size.html',1,'']]],
  ['tosacontainercontainsthreetypes_6283',['TosaContainerContainsThreeTypes',['../struct_tosa_container_contains_three_types.html',1,'']]],
  ['tosacontainercontainstwotypes_6284',['TosaContainerContainsTwoTypes',['../struct_tosa_container_contains_two_types.html',1,'']]],
  ['tosaoperatorattributeofany_6285',['TosaOperatorAttributeOfAny',['../struct_tosa_operator_attribute_of_any.html',1,'']]],
  ['tosarefbackend_6286',['TosaRefBackend',['../classarmnn_1_1_tosa_ref_backend.html',1,'armnn']]],
  ['tosarefbaseworkload_6287',['TosaRefBaseWorkload',['../classarmnn_1_1_tosa_ref_base_workload.html',1,'armnn']]],
  ['tosareflayersupport_6288',['TosaRefLayerSupport',['../classarmnn_1_1_tosa_ref_layer_support.html',1,'armnn']]],
  ['tosarefmemorymanager_6289',['TosaRefMemoryManager',['../classarmnn_1_1_tosa_ref_memory_manager.html',1,'armnn']]],
  ['tosarefprecompiledworkload_6290',['TosaRefPreCompiledWorkload',['../classarmnn_1_1_tosa_ref_pre_compiled_workload.html',1,'armnn']]],
  ['tosareftensorhandle_6291',['TosaRefTensorHandle',['../classarmnn_1_1_tosa_ref_tensor_handle.html',1,'armnn']]],
  ['tosareftensorhandlefactory_6292',['TosaRefTensorHandleFactory',['../classarmnn_1_1_tosa_ref_tensor_handle_factory.html',1,'armnn']]],
  ['tosarefworkloadfactory_6293',['TosaRefWorkloadFactory',['../classarmnn_1_1_tosa_ref_workload_factory.html',1,'armnn']]],
  ['tosatensornumdimensionswithinbounds_6294',['TosaTensorNumDimensionsWithinBounds',['../struct_tosa_tensor_num_dimensions_within_bounds.html',1,'']]],
  ['tosatypeanyof_6295',['TosaTypeAnyOf',['../struct_tosa_type_any_of.html',1,'']]],
  ['transformiterator_6296',['TransformIterator',['../classarmnn_1_1_transform_iterator.html',1,'armnn']]],
  ['transposeasreshapeimpl_6297',['TransposeAsReshapeImpl',['../classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.html',1,'armnn::optimizations']]],
  ['transposeconvolution2ddescriptor_6298',['TransposeConvolution2dDescriptor',['../structarmnn_1_1_transpose_convolution2d_descriptor.html',1,'armnn']]],
  ['transposeconvolution2dlayer_6299',['TransposeConvolution2dLayer',['../classarmnn_1_1_transpose_convolution2d_layer.html',1,'armnn']]],
  ['transposeconvolution2dqueuedescriptor_6300',['TransposeConvolution2dQueueDescriptor',['../structarmnn_1_1_transpose_convolution2d_queue_descriptor.html',1,'armnn']]],
  ['transposedescriptor_6301',['TransposeDescriptor',['../structarmnn_1_1_transpose_descriptor.html',1,'armnn']]],
  ['transposelayer_6302',['TransposeLayer',['../classarmnn_1_1_transpose_layer.html',1,'armnn']]],
  ['transposequeuedescriptor_6303',['TransposeQueueDescriptor',['../structarmnn_1_1_transpose_queue_descriptor.html',1,'armnn']]],
  ['typeanyof_6304',['TypeAnyOf',['../structarmnn_1_1_type_any_of.html',1,'armnn']]],
  ['typediterator_6305',['TypedIterator',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20float_2c_20decoder_3c_20float_20_3e_20_3e_6306',['TypedIterator&lt; const float, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20half_2c_20decoder_3c_20float_20_3e_20_3e_6307',['TypedIterator&lt; const Half, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int16_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6308',['TypedIterator&lt; const int16_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6309',['TypedIterator&lt; const int32_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20int32_5ft_20_3e_20_3e_6310',['TypedIterator&lt; const int32_t, Decoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20int8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6311',['TypedIterator&lt; const int8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20bool_20_3e_20_3e_6312',['TypedIterator&lt; const uint8_t, Decoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6313',['TypedIterator&lt; const uint8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20float_2c_20encoder_3c_20float_20_3e_20_3e_6314',['TypedIterator&lt; float, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20half_2c_20encoder_3c_20float_20_3e_20_3e_6315',['TypedIterator&lt; Half, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int16_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6316',['TypedIterator&lt; int16_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6317',['TypedIterator&lt; int32_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20int32_5ft_20_3e_20_3e_6318',['TypedIterator&lt; int32_t, Encoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20int8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6319',['TypedIterator&lt; int8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20bool_20_3e_20_3e_6320',['TypedIterator&lt; uint8_t, Encoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6321',['TypedIterator&lt; uint8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.html',1,'armnn']]],
  ['typedworkload_6322',['TypedWorkload',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20debugqueuedescriptor_2c_20datatype_20_3e_6323',['TypedWorkload&lt; DebugQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20permutequeuedescriptor_2c_20datatype_20_3e_6324',['TypedWorkload&lt; PermuteQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typedworkload_3c_20transposequeuedescriptor_2c_20datatype_20_3e_6325',['TypedWorkload&lt; TransposeQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.html',1,'armnn']]],
  ['typeis_6326',['TypeIs',['../structarmnn_1_1_type_is.html',1,'armnn']]],
  ['typenotperaxisquantized_6327',['TypeNotPerAxisQuantized',['../structarmnn_1_1_type_not_per_axis_quantized.html',1,'armnn']]],
  ['typesareequal_6328',['TypesAreEqual',['../structarmnn_1_1_types_are_equal.html',1,'armnn']]]
];
