ArmNN: src/armnnTfParser/test/Assert.cpp File Reference
Assert.cpp File Reference
#include "armnnTfParser/ITfParser.hpp"
#include "ParserPrototxtFixture.hpp"
#include "test/GraphUtils.hpp"
#include <boost/test/unit_test.hpp>
Functions
BOOST_FIXTURE_TEST_CASE (AssertSimpleTest, AssertSimpleFixture)
BOOST_FIXTURE_TEST_CASE (AssertSimpleGraphStructureTest, AssertSimpleFixture)
BOOST_FIXTURE_TEST_CASE (AssertTest, AssertFixture)
BOOST_FIXTURE_TEST_CASE (AssertGraphStructureTest, AssertFixture)
Function Documentation
BOOST_FIXTURE_TEST_CASE() [1/4]
BOOST_FIXTURE_TEST_CASE (AssertSimpleTest , AssertSimpleFixture)
Definition at line 93 of file Assert.cpp.
References ParserPrototxtFixture< TParser >::SetupSingleInputSingleOutput().
 {
     SetupSingleInputSingleOutput({ 1, 1, 1, 4 }, "Placeholder", "Add");
     RunTest<4>({ 1.0f, 2.0f, 3.0f, 4.0f }, { 2.0f, 4.0f, 6.0f, 8.0f });
 }
BOOST_FIXTURE_TEST_CASE() [2/4]
BOOST_FIXTURE_TEST_CASE (AssertSimpleGraphStructureTest , AssertSimpleFixture)
Definition at line 99 of file Assert.cpp.
References armnn::Addition, CheckNumberOfInputSlot(), CheckNumberOfOutputSlot(), armnn::Float32, GetFirstLayerWithName(), Layer::GetType(), armnn::Input, IsConnected(), and ParserPrototxtFixture< TParser >::SetupOptimizedNetwork().
 {
     auto optimized = SetupOptimizedNetwork({ { "Placeholder", { 1, 1, 1, 4 } } }, { "Add" });
     auto optimizedNetwork = boost::polymorphic_downcast<armnn::OptimizedNetwork*>(optimized.get());
     auto graph = optimizedNetwork->GetGraph();
     BOOST_TEST((graph.GetNumInputs() == 1));
     BOOST_TEST((graph.GetNumOutputs() == 1));
     BOOST_TEST((graph.GetNumLayers() == 3));
     armnn::Layer* inputLayer = GetFirstLayerWithName(graph, "Placeholder");
     BOOST_TEST((inputLayer->GetType() == armnn::LayerType::Input));
     BOOST_TEST(CheckNumberOfInputSlot(inputLayer, 0));
     BOOST_TEST(CheckNumberOfOutputSlot(inputLayer, 1));
     armnn::Layer* addLayer = GetFirstLayerWithName(graph, "Add");
     BOOST_TEST((addLayer->GetType() == armnn::LayerType::Addition));
     BOOST_TEST(CheckNumberOfInputSlot(addLayer, 2));
     BOOST_TEST(CheckNumberOfOutputSlot(addLayer, 1));
     armnn::TensorInfo tensorInfo(armnn::TensorShape({1, 1, 1, 4}), armnn::DataType::Float32);
     BOOST_TEST(IsConnected(inputLayer, addLayer, 0, 0, tensorInfo));
     BOOST_TEST(IsConnected(inputLayer, addLayer, 0, 1, tensorInfo));
     for (auto&& outputLayer : graph.GetOutputLayers())
     {
         BOOST_TEST(IsConnected(addLayer, const_cast<armnn::OutputLayer*>(outputLayer), 0, 0, tensorInfo));
     }
 }
BOOST_FIXTURE_TEST_CASE() [3/4]
BOOST_FIXTURE_TEST_CASE (AssertTest , AssertFixture)
Definition at line 237 of file Assert.cpp.
 {
     Setup({ { "Input0", { 1, 1, 2, 2 } },
             { "Input1", { 1, 1, 2, 2 } } },
           { "Output" });
     RunTest<4>({ { "Input0", { 4.0f,   3.0f,
                                2.0f,   1.0f } },
                  { "Input1", { 1.0f,   2.0f,
                                3.0f,   4.0f } } },
                { { "Output", { 7.0f,   4.0f,
                                1.0f,  -2.0f } } });
 }
BOOST_FIXTURE_TEST_CASE() [4/4]
BOOST_FIXTURE_TEST_CASE (AssertGraphStructureTest , AssertFixture)
Definition at line 253 of file Assert.cpp.
References armnn::Addition, BOOST_AUTO_TEST_SUITE_END(), CheckNumberOfInputSlot(), CheckNumberOfOutputSlot(), armnn::Float32, GetFirstLayerWithName(), Layer::GetType(), armnn::Input, IsConnected(), and armnn::Subtraction.
 {
     auto optimized = SetupOptimizedNetwork({ { "Input0", { 1, 1, 2, 2 } },
                                              { "Input1", { 1, 1, 2, 2 } } },
                                            { "Output" });
     auto optimizedNetwork = boost::polymorphic_downcast<armnn::OptimizedNetwork*>(optimized.get());
     auto graph = optimizedNetwork->GetGraph();
     BOOST_TEST((graph.GetNumInputs() == 2));
     BOOST_TEST((graph.GetNumOutputs() == 1));
     BOOST_TEST((graph.GetNumLayers() == 5));
     armnn::Layer* inputLayer0 = GetFirstLayerWithName(graph, "Input0");
     BOOST_TEST((inputLayer0->GetType() == armnn::LayerType::Input));
     BOOST_TEST(CheckNumberOfInputSlot(inputLayer0, 0));
     BOOST_TEST(CheckNumberOfOutputSlot(inputLayer0, 1));
     armnn::Layer* inputLayer1 = GetFirstLayerWithName(graph, "Input1");
     BOOST_TEST((inputLayer1->GetType() == armnn::LayerType::Input));
     BOOST_TEST(CheckNumberOfInputSlot(inputLayer1, 0));
     BOOST_TEST(CheckNumberOfOutputSlot(inputLayer1, 1));
     armnn::Layer* subLayer = GetFirstLayerWithName(graph, "Sub");
     BOOST_TEST((subLayer->GetType() == armnn::LayerType::Subtraction));
     BOOST_TEST(CheckNumberOfInputSlot(subLayer, 2));
     BOOST_TEST(CheckNumberOfOutputSlot(subLayer, 1));
     armnn::Layer* addLayer = GetFirstLayerWithName(graph, "Output");
     BOOST_TEST((addLayer->GetType() == armnn::LayerType::Addition));
     BOOST_TEST(CheckNumberOfInputSlot(addLayer, 2));
     BOOST_TEST(CheckNumberOfOutputSlot(addLayer, 1));
     armnn::TensorInfo tensorInfo(armnn::TensorShape({1, 1, 2, 2}), armnn::DataType::Float32);
     BOOST_TEST(IsConnected(inputLayer0, subLayer, 0, 0, tensorInfo));
     BOOST_TEST(IsConnected(inputLayer1, subLayer, 0, 1, tensorInfo));
     BOOST_TEST(IsConnected(inputLayer0, addLayer, 0, 0, tensorInfo));
     BOOST_TEST(IsConnected(subLayer, addLayer, 0, 1, tensorInfo));
     for (auto&& outputLayer : graph.GetOutputLayers())
     {
         BOOST_TEST(IsConnected(addLayer, const_cast<armnn::OutputLayer*>(outputLayer), 0, 0, tensorInfo));
     }
 }