ArmNN: src/backends/backendsCommon/test/BackendIdTests.cpp File Reference
BackendIdTests.cpp File Reference
#include <armnn/BackendId.hpp>
#include <armnn/Types.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (CreateBackendIdFromCompute)
BOOST_AUTO_TEST_CASE (CreateBackendIdVectorFromCompute)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (CreateBackendIdFromCompute)
Definition at line 15 of file BackendIdTests.cpp.
References armnn::GetComputeDeviceAsCString(), and armnn::GpuAcc.
 {
     BackendId fromCompute{Compute::GpuAcc};
     BOOST_TEST(fromCompute.Get() == GetComputeDeviceAsCString(Compute::GpuAcc));
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (CreateBackendIdVectorFromCompute)
Definition at line 21 of file BackendIdTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), armnn::CpuRef, armnn::GetComputeDeviceAsCString(), and armnn::GpuAcc.
 {
     std::vector<BackendId> fromComputes = {Compute::GpuAcc, Compute::CpuRef};
     BOOST_TEST(fromComputes[0].Get() == GetComputeDeviceAsCString(Compute::GpuAcc));
     BOOST_TEST(fromComputes[1].Get() == GetComputeDeviceAsCString(Compute::CpuRef));
 }