ArmNN: src/backends/backendsCommon/test/layerTests/ConvertFp32ToFp16TestImpl.hpp File Reference
ConvertFp32ToFp16TestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <Half.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< armnn::Half, 4 > SimpleConvertFp32ToFp16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
SimpleConvertFp32ToFp16Test()
LayerTestResult<armnn::Half, 4> SimpleConvertFp32ToFp16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 14 of file ConvertFp32ToFp16TestImpl.cpp.
References CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateConvertFp32ToFp16(), IWorkloadFactory::CreateTensorHandle(), armnn::Float16, armnn::Float32, and armnn::IgnoreUnused().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     IgnoreUnused(memoryManager);
     using namespace half_float::literal;
     const armnn::TensorInfo inputTensorInfo({1, 3, 2, 3}, armnn::DataType::Float32);
     const armnn::TensorInfo outputTensorInfo({1, 3, 2, 3}, armnn::DataType::Float16);
     auto input = MakeTensor<float, 4>(inputTensorInfo,
         { -37.5f, -15.2f, -8.76f, -2.0f, -1.5f, -1.3f, -0.5f, -0.4f, 0.0f,
           1.0f, 0.4f, 0.5f, 1.3f, 1.5f, 2.0f, 8.76f, 15.2f, 37.5f });
     LayerTestResult<armnn::Half, 4> ret(outputTensorInfo);
     ret.outputExpected = MakeTensor<armnn::Half, 4>(outputTensorInfo,
         { -37.5_h, -15.2_h, -8.76_h, -2.0_h, -1.5_h, -1.3_h, -0.5_h, -0.4_h, 0.0_h,
           1.0_h, 0.4_h, 0.5_h, 1.3_h, 1.5_h, 2.0_h, 8.76_h, 15.2_h, 37.5_h });
     std::unique_ptr<armnn::ITensorHandle> inputHandle = workloadFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = workloadFactory.CreateTensorHandle(outputTensorInfo);
     armnn::ConvertFp32ToFp16QueueDescriptor data;
     armnn::WorkloadInfo info;
     AddInputToWorkload(data, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateConvertFp32ToFp16(data, info);
     inputHandle->Allocate();
     outputHandle->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), &input[0][0][0][0]);
     workload->Execute();
     CopyDataFromITensorHandle(&ret.output[0][0][0][0], outputHandle.get());
     return ret;
 }