ArmNN: src/armnn/test/CsvReaderTest.cpp File Reference
CsvReaderTest.cpp File Reference
#include "CsvReader.hpp"
#include <boost/algorithm/string.hpp>
#include <boost/test/unit_test.hpp>
#include <iostream>
#include <string>
#include <boost/filesystem.hpp>
#include <boost/optional.hpp>
Functions
BOOST_FIXTURE_TEST_CASE (TestParseVector, TestHelper)
BOOST_FIXTURE_TEST_CASE (TestLoadingFileFromDisk, TestHelper)
Function Documentation
BOOST_FIXTURE_TEST_CASE() [1/2]
BOOST_FIXTURE_TEST_CASE (TestParseVector , TestHelper)
Definition at line 83 of file CsvReaderTest.cpp.
References BOOST_CHECK(), CsvReader::ParseVector(), and CsvRow::values.
 {
     CsvReader reader;
     std::vector<std::string> csvStrings;
     csvStrings.reserve(2);
     csvStrings.push_back("airplane, automobile , bird , \"c,a,t\"");
     csvStrings.push_back("banana, shoe, \"ice\"");
     std::vector<CsvRow> row = reader.ParseVector(csvStrings);
     CsvRow row1 = row[0];
     CsvRow row2 = row[1];
     BOOST_CHECK(row.size() == 2);
     BOOST_CHECK(row1.values.size() == 4);
     BOOST_CHECK(CheckStringsMatch(row1, 0, "airplane") == 0);
     BOOST_CHECK(CheckStringsMatch(row1, 1, "automobile") == 0);
     BOOST_CHECK(CheckStringsMatch(row1, 2, "bird") == 0);
     BOOST_CHECK(CheckStringsMatch(row1, 3, "c,a,t") == 0);
     BOOST_CHECK(row2.values.size() == 3);
     BOOST_CHECK(CheckStringsMatch(row2, 0, "banana") == 0);
     BOOST_CHECK(CheckStringsMatch(row2, 1, "shoe") == 0);
     BOOST_CHECK(CheckStringsMatch(row2, 2, "ice") == 0);
 }
BOOST_FIXTURE_TEST_CASE() [2/2]
BOOST_FIXTURE_TEST_CASE (TestLoadingFileFromDisk , TestHelper)
Definition at line 109 of file CsvReaderTest.cpp.
References BOOST_AUTO_TEST_SUITE_END(), BOOST_CHECK(), CsvReader::ParseFile(), and CsvRow::values.
 {
     CsvReader reader;
     std::string theFilePath = TestHelper::CreateTempCsvFile();
     std::vector<CsvRow> row = reader.ParseFile(theFilePath);
     CsvRow row1 = row[0];
     CsvRow row2 = row[1];
     BOOST_CHECK(row.size() == 2);
     BOOST_CHECK(row1.values.size() == 4);
     BOOST_CHECK(CheckStringsMatch(row1, 0, "airplane") == 0);
     BOOST_CHECK(CheckStringsMatch(row1, 1, "bicycle") == 0);
     BOOST_CHECK(CheckStringsMatch(row1, 2, "bird") == 0);
     BOOST_CHECK(CheckStringsMatch(row1, 3, "m,o,n,k,e,y") == 0);
     BOOST_CHECK(row2.values.size() == 3);
     BOOST_CHECK(CheckStringsMatch(row2, 0, "banana") == 0);
     BOOST_CHECK(CheckStringsMatch(row2, 1, "shoe") == 0);
     BOOST_CHECK(CheckStringsMatch(row2, 2, "ice") == 0);
 }