ArmNN: src/armnn/test/ExecutionFrameTest.cpp File Reference
ExecutionFrameTest.cpp File Reference
#include <boost/test/unit_test.hpp>
#include <ExecutionFrame.hpp>
Functions
BOOST_AUTO_TEST_CASE (NextExecutionFrameTest)
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (NextExecutionFrameTest)
Definition at line 17 of file ExecutionFrameTest.cpp.
References BOOST_CHECK(), ExecutionFrame::ExecuteWorkloads(), and ExecutionFrame::SetNextExecutionFrame().
 {
     armnn::ExecutionFrame executionFrameA;
     armnn::ExecutionFrame executionFrameB;
     armnn::ExecutionFrame executionFrameC;
     executionFrameA.SetNextExecutionFrame(&executionFrameB);
     executionFrameB.SetNextExecutionFrame(&executionFrameC);
     //not setting C to check that the default setting is nullptr.
     auto nextExecutionFrameA = executionFrameA.ExecuteWorkloads(nullptr);
     auto nextExecutionFrameB = executionFrameB.ExecuteWorkloads(&executionFrameA);
     auto nextExecutionFrameC = executionFrameC.ExecuteWorkloads(&executionFrameB);
     BOOST_CHECK_EQUAL(nextExecutionFrameA, &executionFrameB);
     BOOST_CHECK_EQUAL(nextExecutionFrameB, &executionFrameC);
     BOOST_CHECK(!nextExecutionFrameC);
     BOOST_CHECK_NE(nextExecutionFrameA, &executionFrameC);
 }