ArmNN: src/armnn/test/GraphTests.cpp File Reference
GraphTests.cpp File Reference
#include "GraphUtils.hpp"
#include <Graph.hpp>
#include <Layer.hpp>
#include <armnn/TypesUtils.hpp>
#include <armnn/Exceptions.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/CpuTensorHandle.hpp>
#include <backendsCommon/TensorHandleFactoryRegistry.hpp>
#include <boost/cast.hpp>
#include <boost/test/unit_test.hpp>
Functions
bool CheckOrder (const armnn::Graph &graph, const armnn::Layer *first, const armnn::Layer *second)
Checks that first comes before second in the order.
BOOST_AUTO_TEST_CASE (ClassGraph)
BOOST_AUTO_TEST_CASE (TopologicalSort)
BOOST_AUTO_TEST_CASE (InsertNewLayerBefore)
BOOST_AUTO_TEST_CASE (InsertNewLayerAfter)
BOOST_FIXTURE_TEST_CASE (AddCopyLayers, CopyLayersFixture)
BOOST_FIXTURE_TEST_CASE (AddCopyLayersSeveralTimes, CopyLayersFixture)
BOOST_FIXTURE_TEST_CASE (CopyLayersAddedBetweenSameLayersHaveDifferentNames, CopyLayersFixture)
BOOST_AUTO_TEST_CASE (DuplicateLayerNames)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (ClassGraph)
Definition at line 36 of file GraphTests.cpp.
References Graph::AddLayer(), and GraphHasNamedLayer().
 {
     armnn::Graph graph;
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::InputLayer>(0, "layerA"));
     BOOST_TEST(GraphHasNamedLayer(graph, "layerA"));
 }
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (TopologicalSort)
Definition at line 43 of file GraphTests.cpp.
References Graph::AddLayer(), CheckOrder(), OutputSlot::Connect(), GetFirstLayerWithName(), Layer::GetInputSlot(), and Layer::GetOutputSlot().
 {
     armnn::Graph graph;
     armnn::ActivationDescriptor activationDefaults;
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::InputLayer>(0, "layerA"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerB"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::AdditionLayer>("layerC"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::OutputLayer>(0, "output"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerD"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerE"));
     armnn::Layer* const layerA = GetFirstLayerWithName(graph, "layerA");
     armnn::Layer* const layerB = GetFirstLayerWithName(graph, "layerB");
     armnn::Layer* const layerC = GetFirstLayerWithName(graph, "layerC");
     armnn::Layer* const layerO = GetFirstLayerWithName(graph, "output");
     armnn::Layer* const layerE = GetFirstLayerWithName(graph, "layerE");
     armnn::Layer* const layerD = GetFirstLayerWithName(graph, "layerD");
     // Simple graph which branches and rejoins.
     //    A
     //   / \'
     //  D   E
     //   \  |
     //    \ B
     //     \|
     //      C
     layerA->GetOutputSlot(0).Connect(layerD->GetInputSlot(0));
     layerA->GetOutputSlot(0).Connect(layerE->GetInputSlot(0));
     layerE->GetOutputSlot(0).Connect(layerB->GetInputSlot(0));
     layerD->GetOutputSlot(0).Connect(layerC->GetInputSlot(0));
     layerB->GetOutputSlot(0).Connect(layerC->GetInputSlot(1));
     layerC->GetOutputSlot(0).Connect(layerO->GetInputSlot(0));
     // check order is valid
     BOOST_TEST(CheckOrder(graph, layerA, layerD));
     BOOST_TEST(CheckOrder(graph, layerA, layerE));
     BOOST_TEST(CheckOrder(graph, layerD, layerC));
     BOOST_TEST(CheckOrder(graph, layerE, layerB));
     BOOST_TEST(CheckOrder(graph, layerB, layerC));
 }
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (InsertNewLayerBefore)
Definition at line 86 of file GraphTests.cpp.
References Graph::AddLayer(), CheckOrder(), OutputSlot::Connect(), armnn::Float32, GetFirstLayerWithName(), Layer::GetInputSlot(), Layer::GetOutputSlot(), Graph::InsertNewLayer(), and OutputSlot::SetTensorInfo().
 {
     armnn::Graph graph;
     armnn::TensorInfo tensorInfo({ 1, 1, 1, 1 }, armnn::DataType::Float32);
     std::vector<armnn::Layer*> order;
     armnn::ActivationDescriptor activationDefaults;
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::InputLayer>(0, "layerA"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerB"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerC"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::AdditionLayer>("layerD"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::OutputLayer>(0, "output"));
     armnn::Layer* const layerA = GetFirstLayerWithName(graph, "layerA");
     armnn::Layer* const layerB = GetFirstLayerWithName(graph, "layerB");
     armnn::Layer* const layerC = GetFirstLayerWithName(graph, "layerC");
     armnn::Layer* const layerD = GetFirstLayerWithName(graph, "layerD");
     armnn::Layer* const layerO = GetFirstLayerWithName(graph, "output");
     //    A
     //   / \'
     //  B   C
     //   \ /
     //    D
     layerA->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerB->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerC->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerD->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerA->GetOutputSlot(0).Connect(layerB->GetInputSlot(0));
     layerA->GetOutputSlot(0).Connect(layerC->GetInputSlot(0));
     layerB->GetOutputSlot(0).Connect(layerD->GetInputSlot(0));
     layerC->GetOutputSlot(0).Connect(layerD->GetInputSlot(1));
     layerD->GetOutputSlot(0).Connect(layerO->GetInputSlot(0));
     // Checks order is valid.
     BOOST_TEST(CheckOrder(graph, layerA, layerB));
     BOOST_TEST(CheckOrder(graph, layerA, layerC));
     BOOST_TEST(CheckOrder(graph, layerB, layerD));
     BOOST_TEST(CheckOrder(graph, layerC, layerD));
     //    A
     //   / \'
     //  B   C
     //   \  |
     //    \ E
     //     \|
     //      D
     BOOST_CHECK_NO_THROW(graph.InsertNewLayer<armnn::ActivationLayer>(layerD->GetInputSlot(1),
                                                                       activationDefaults,
                                                                       "layerE"));
     armnn::Layer* const layerE = GetFirstLayerWithName(graph, "layerE");
     // Checks order is valid.
     BOOST_TEST(CheckOrder(graph, layerA, layerB));
     BOOST_TEST(CheckOrder(graph, layerA, layerC));
     BOOST_TEST(CheckOrder(graph, layerB, layerD));
     BOOST_TEST(CheckOrder(graph, layerC, layerE));
     BOOST_TEST(CheckOrder(graph, layerE, layerD));
     //      A
     //     /|
     //    / F
     //   /  |
     //  B   C
     //   \  |
     //    \ E
     //     \|
     //      D
     BOOST_CHECK_NO_THROW(graph.InsertNewLayer<armnn::ActivationLayer>(layerC->GetInputSlot(0),
                                                                       activationDefaults,
                                                                       "layerF"));
     armnn::Layer* const layerF = GetFirstLayerWithName(graph, "layerF");
     // Checks order is valid.
     BOOST_TEST(CheckOrder(graph, layerA, layerB));
     BOOST_TEST(CheckOrder(graph, layerA, layerF));
     BOOST_TEST(CheckOrder(graph, layerF, layerC));
     BOOST_TEST(CheckOrder(graph, layerB, layerD));
     BOOST_TEST(CheckOrder(graph, layerC, layerE));
     BOOST_TEST(CheckOrder(graph, layerE, layerD));
 }
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (InsertNewLayerAfter)
Definition at line 172 of file GraphTests.cpp.
References Graph::AddLayer(), CheckOrder(), OutputSlot::Connect(), armnn::Float32, GetFirstLayerWithName(), Layer::GetInputSlot(), Layer::GetOutputSlot(), Graph::InsertNewLayer(), and OutputSlot::SetTensorInfo().
 {
     armnn::Graph graph;
     armnn::TensorInfo tensorInfo({ 1, 1, 1, 1 }, armnn::DataType::Float32);
     std::vector<armnn::Layer*> order;
     armnn::ActivationDescriptor activationDefaults;
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::InputLayer>(0, "layerA"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerB"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::ActivationLayer>(activationDefaults, "layerC"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::AdditionLayer>("layerD"));
     BOOST_CHECK_NO_THROW(graph.AddLayer<armnn::OutputLayer>(0, "output"));
     armnn::Layer* const layerA = GetFirstLayerWithName(graph, "layerA");
     armnn::Layer* const layerB = GetFirstLayerWithName(graph, "layerB");
     armnn::Layer* const layerC = GetFirstLayerWithName(graph, "layerC");
     armnn::Layer* const layerD = GetFirstLayerWithName(graph, "layerD");
     armnn::Layer* const layerO = GetFirstLayerWithName(graph, "output");
     //    A
     //   / \'
     //  B   C
     //   \ /
     //    D
     layerA->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerB->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerC->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerD->GetOutputSlot(0).SetTensorInfo(tensorInfo);
     layerA->GetOutputSlot(0).Connect(layerB->GetInputSlot(0));
     layerA->GetOutputSlot(0).Connect(layerC->GetInputSlot(0));
     layerB->GetOutputSlot(0).Connect(layerD->GetInputSlot(0));
     layerC->GetOutputSlot(0).Connect(layerD->GetInputSlot(1));
     layerD->GetOutputSlot(0).Connect(layerO->GetInputSlot(0));
     // Checks order is valid.
     BOOST_TEST(CheckOrder(graph, layerA, layerB));
     BOOST_TEST(CheckOrder(graph, layerA, layerC));
     BOOST_TEST(CheckOrder(graph, layerB, layerD));
     BOOST_TEST(CheckOrder(graph, layerC, layerD));
     //    A
     //   / \'
     //  B   C
     //   \  |
     //    \ E
     //     \|
     //      D
     BOOST_CHECK_NO_THROW(graph.InsertNewLayer<armnn::ActivationLayer>(layerC->GetOutputSlot(),
                                                                       activationDefaults,
                                                                       "layerE"));
     armnn::Layer* const layerE = GetFirstLayerWithName(graph, "layerE");
     // Checks order is valid.
     BOOST_TEST(CheckOrder(graph, layerA, layerB));
     BOOST_TEST(CheckOrder(graph, layerA, layerC));
     BOOST_TEST(CheckOrder(graph, layerB, layerD));
     BOOST_TEST(CheckOrder(graph, layerC, layerE));
     BOOST_TEST(CheckOrder(graph, layerE, layerD));
     //    A
     //    |
     //    F
     //   / \'
     //  B   C
     //  \   |
     //   \  E
     //    \ /
     //     D
     BOOST_CHECK_NO_THROW(graph.InsertNewLayer<armnn::ActivationLayer>(layerA->GetOutputSlot(),
                                                                       activationDefaults,
                                                                       "layerF"));
     armnn::Layer* const layerF = GetFirstLayerWithName(graph, "layerF");
     // Checks order is valid.
     BOOST_TEST(CheckOrder(graph, layerA, layerF));
     BOOST_TEST(CheckOrder(graph, layerF, layerB));
     BOOST_TEST(CheckOrder(graph, layerF, layerC));
     BOOST_TEST(CheckOrder(graph, layerB, layerD));
     BOOST_TEST(CheckOrder(graph, layerC, layerE));
     BOOST_TEST(CheckOrder(graph, layerE, layerD));
 }
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (DuplicateLayerNames)
Definition at line 588 of file GraphTests.cpp.
References Graph::AddLayer(), Graph::begin(), BOOST_AUTO_TEST_SUITE_END(), OutputSlot::Connect(), armnn::CpuRef, Layer::GetInputSlot(), Layer::GetOutputSlot(), armnn::Input, armnn::Output, Layer::SetBackendId(), and Graph::TopologicalSort().
 {
     armnn::Graph graph;
     armnn::InputLayer* const inputLayer = graph.AddLayer<armnn::InputLayer>(0, "layer");
     inputLayer->SetBackendId(armnn::Compute::CpuRef);
     armnn::OutputLayer* const outputLayer = graph.AddLayer<armnn::OutputLayer>(0, "layer");
     outputLayer->SetBackendId(armnn::Compute::CpuRef);
     inputLayer->GetOutputSlot(0).Connect(outputLayer->GetInputSlot(0));
     auto it = graph.TopologicalSort().begin();
     BOOST_TEST(((*it)->GetType() == armnn::LayerType::Input));
     BOOST_TEST(((*std::next(it))->GetType() == armnn::LayerType::Output));
 }
BOOST_FIXTURE_TEST_CASE() [1/3]
BOOST_FIXTURE_TEST_CASE (AddCopyLayers , CopyLayersFixture)
Definition at line 528 of file GraphTests.cpp.
 {
     InitialiseTestGraph();
     const armnn::Graph origGraph(m_Graph);
     m_Graph.AddCompatibilityLayers(m_Backends, m_FactoryRegistry);
     TestGraphAfterAddingCopyLayers(m_Graph, origGraph);
 }
BOOST_FIXTURE_TEST_CASE() [2/3]
BOOST_FIXTURE_TEST_CASE (AddCopyLayersSeveralTimes , CopyLayersFixture)
Definition at line 537 of file GraphTests.cpp.
 {
     InitialiseTestGraph();
     m_Graph.AddCompatibilityLayers(m_Backends, m_FactoryRegistry);
     // Calling AddCompatibilityLayers() several times should not change the connections.
     const std::vector<Edge> edges = GetEdgeList(m_Graph);
     for (int i = 0; i < 4; ++i)
     {
         m_Graph.AddCompatibilityLayers(m_Backends, m_FactoryRegistry);
         const std::vector<Edge> otherEdges = GetEdgeList(m_Graph);
         BOOST_TEST((edges == otherEdges));
     }
 }
BOOST_FIXTURE_TEST_CASE() [3/3]
BOOST_FIXTURE_TEST_CASE (CopyLayersAddedBetweenSameLayersHaveDifferentNames , CopyLayersFixture)
Definition at line 552 of file GraphTests.cpp.
References Graph::AddCompatibilityLayers(), Graph::AddLayer(), OutputSlot::Connect(), armnn::CopyToTarget, armnn::CpuRef, armnn::DirectCompatibility, Layer::GetInputSlot(), Layer::GetOutputSlot(), armnn::GpuAcc, Layer::SetBackendId(), and OutputSlot::SetEdgeStrategy().
 {
     armnn::Graph graph;
     armnn::InputLayer* const inputLayer = graph.AddLayer<armnn::InputLayer>(0, "input");
     inputLayer->SetBackendId(armnn::Compute::CpuRef);
     armnn::ViewsDescriptor splitterDesc(2);
     armnn::SplitterLayer* const splitterLayer = graph.AddLayer<armnn::SplitterLayer>(splitterDesc, "splitter");
     splitterLayer->SetBackendId(armnn::Compute::GpuAcc);
     armnn::AdditionLayer* const additionLayer = graph.AddLayer<armnn::AdditionLayer>("addition");
     additionLayer->SetBackendId(armnn::Compute::CpuRef);
     armnn::OutputLayer* const outputLayer = graph.AddLayer<armnn::OutputLayer>(0, "output");
     outputLayer->SetBackendId(armnn::Compute::CpuRef);
     inputLayer->GetOutputSlot(0).Connect(splitterLayer->GetInputSlot(0));
     splitterLayer->GetOutputSlot(0).Connect(additionLayer->GetInputSlot(0));
     splitterLayer->GetOutputSlot(1).Connect(additionLayer->GetInputSlot(1));
     additionLayer->GetOutputSlot(0).Connect(outputLayer->GetInputSlot(0));
     inputLayer->GetOutputSlot(0).SetEdgeStrategy(0, armnn::EdgeStrategy::DirectCompatibility);
     splitterLayer->GetOutputSlot(0).SetEdgeStrategy(0, armnn::EdgeStrategy::CopyToTarget);
     splitterLayer->GetOutputSlot(1).SetEdgeStrategy(0, armnn::EdgeStrategy::CopyToTarget);
     additionLayer->GetOutputSlot(0).SetEdgeStrategy(0, armnn::EdgeStrategy::DirectCompatibility);
     graph.AddCompatibilityLayers(m_Backends, m_FactoryRegistry);
     std::vector<Edge> edges = GetEdgeList(graph);
     BOOST_CHECK(edges.size() == 6u);
     std::sort(edges.begin(), edges.end());
     auto last = std::unique(edges.begin(), edges.end());
     BOOST_CHECK_MESSAGE(last == edges.end(), "Found duplicated edges after AddCompatibilityLayers()");
 }
CheckOrder()
bool CheckOrder (const armnn::Graph & graph, const armnn::Layer * first, const armnn::Layer * second)
Checks that first comes before second in the order.
Definition at line 22 of file GraphTests.cpp.
References BOOST_AUTO_TEST_SUITE(), Graph::Print(), and Graph::TopologicalSort().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     graph.Print();
     const auto& order = graph.TopologicalSort();
     auto firstPos = std::find(order.begin(), order.end(), first);
     auto secondPos = std::find(firstPos, order.end(), second);
     return (secondPos != order.end());
 }