ArmNN: tests/profiling/timelineDecoder/ITimelineDecoder.h File Reference
ITimelineDecoder.h File Reference
#include "TimelineModel.h"
Typedefs
typedef enum ErrorCode ErrorCode
Enumerations
enum ErrorCode { ErrorCode_Success, ErrorCode_Fail }
Functions
ErrorCode CreateModel (Model **model)
ErrorCode DestroyModel (Model **model)
ErrorCode SetEntityCallback (OnNewEntityCallback cb, Model *model)
ErrorCode SetEventClassCallback (OnNewEventClassCallback cb, Model *model)
ErrorCode SetEventCallback (OnNewEventCallback cb, Model *model)
ErrorCode SetLabelCallback (OnNewLabelCallback cb, Model *model)
ErrorCode SetRelationshipCallback (OnNewRelationshipCallback cb, Model *model)
ErrorCode CreateEntity (const Entity entity, Model *model)
ErrorCode CreateEventClass (const EventClass eventClass, Model *model)
ErrorCode CreateEvent (const Event event, Model *model)
ErrorCode CreateLabel (const Label label, Model *model)
ErrorCode CreateRelationship (const Relationship relationship, Model *model)
Typedef Documentation
ErrorCode
typedef enum ErrorCode ErrorCode
Enumeration Type Documentation
ErrorCode
enum ErrorCode
Enumerator
ErrorCode_Success
ErrorCode_Fail
Definition at line 16 of file ITimelineDecoder.h.
 {
     ErrorCode_Success,
     ErrorCode_Fail
 } ErrorCode;
Function Documentation
CreateEntity()
ErrorCode CreateEntity (const Entity entity, Model * model)
Definition at line 8 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_EntityCb.
Referenced by TimelineCaptureCommandHandler::ReadEntity().
 {
     if (model == nullptr || model->m_EntityCb == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_EntityCb(entity, model);
     return ErrorCode::ErrorCode_Success;
 }
CreateEvent()
ErrorCode CreateEvent (const Event event, Model * model)
Definition at line 28 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_EventCb.
Referenced by TimelineCaptureCommandHandler::ReadEvent().
 {
     if (model == nullptr || model->m_EventCb == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_EventCb(event, model);
     return ErrorCode::ErrorCode_Success;
 }
CreateEventClass()
ErrorCode CreateEventClass (const EventClass eventClass, Model * model)
Definition at line 18 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_EventClassCb.
Referenced by TimelineCaptureCommandHandler::ReadEventClass().
 {
     if (model == nullptr || model->m_EventClassCb == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_EventClassCb(eventClass, model);
     return ErrorCode::ErrorCode_Success;
 }
CreateLabel()
ErrorCode CreateLabel (const Label label, Model * model)
Definition at line 38 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_LabelCb.
Referenced by TimelineCaptureCommandHandler::ReadLabel().
 {
     if (model == nullptr || model->m_LabelCb == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_LabelCb(label, model);
     return ErrorCode::ErrorCode_Success;
 }
CreateModel()
ErrorCode CreateModel (Model ** model)
Definition at line 108 of file TimelineDecoder.cpp.
References ErrorCode_Success, Model::m_EntityCount, Model::m_EventClassCount, Model::m_EventCount, Model::m_LabelCount, and Model::m_RelationshipCount.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     Model* modelPtr = new Model;
     modelPtr->m_EntityCount = 0;
     modelPtr->m_EventClassCount = 0;
     modelPtr->m_EventCount = 0;
     modelPtr->m_LabelCount = 0;
     modelPtr->m_RelationshipCount = 0;
     *model = modelPtr;
     return ErrorCode::ErrorCode_Success;
 }
CreateRelationship()
ErrorCode CreateRelationship (const Relationship relationship, Model * model)
Definition at line 48 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_RelationshipCb.
Referenced by TimelineCaptureCommandHandler::ReadRelationship().
 {
     if (model == nullptr || model->m_RelationshipCb == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_RelationshipCb(relationship, model);
     return ErrorCode::ErrorCode_Success;
 }
DestroyModel()
ErrorCode DestroyModel (Model ** model)
Definition at line 122 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, Model::m_Entities, Model::m_EntityCount, Model::m_EventClassCount, Model::m_EventClasses, Model::m_EventCount, Model::m_Events, Model::m_LabelCount, Model::m_Labels, Label::m_Name, Model::m_RelationshipCount, Model::m_Relationships, and Event::m_ThreadId.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (*model == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     Model* modelPtr = *model;
     for (uint32_t i = 0; i < modelPtr->m_EntityCount; ++i)
     {
         delete modelPtr->m_Entities[i];
     }
     for (uint32_t i = 0; i < modelPtr->m_EventClassCount; ++i)
     {
         delete modelPtr->m_EventClasses[i];
     }
     for (uint32_t i = 0; i < modelPtr->m_EventCount; ++i)
     {
         delete[] modelPtr->m_Events[i]->m_ThreadId;
         delete modelPtr->m_Events[i];
     }
     for (uint32_t i = 0; i < modelPtr->m_LabelCount; ++i)
     {
         delete[] modelPtr->m_Labels[i]->m_Name;
         delete modelPtr->m_Labels[i];
     }
     for (uint32_t i = 0; i < modelPtr->m_RelationshipCount; ++i)
     {
         delete modelPtr->m_Relationships[i];
     }
     delete[] modelPtr->m_Entities;
     delete[] modelPtr->m_EventClasses;
     delete[] modelPtr->m_Events;
     delete[] modelPtr->m_Labels;
     delete[] modelPtr->m_Relationships;
     delete modelPtr;
     return ErrorCode::ErrorCode_Success;
 }
SetEntityCallback()
ErrorCode SetEntityCallback (OnNewEntityCallback cb, Model * model)
Definition at line 58 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_EntityCb.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr || model == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_EntityCb = cb;
     return ErrorCode::ErrorCode_Success;
 }
SetEventCallback()
ErrorCode SetEventCallback (OnNewEventCallback cb, Model * model)
Definition at line 78 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_EventCb.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr || model == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_EventCb = cb;
     return ErrorCode::ErrorCode_Success;
 }
SetEventClassCallback()
ErrorCode SetEventClassCallback (OnNewEventClassCallback cb, Model * model)
Definition at line 68 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_EventClassCb.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr || model == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_EventClassCb = cb;
     return ErrorCode::ErrorCode_Success;
 }
SetLabelCallback()
ErrorCode SetLabelCallback (OnNewLabelCallback cb, Model * model)
Definition at line 88 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_LabelCb.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr || model == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_LabelCb = cb;
     return ErrorCode::ErrorCode_Success;
 }
SetRelationshipCallback()
ErrorCode SetRelationshipCallback (OnNewRelationshipCallback cb, Model * model)
Definition at line 98 of file TimelineDecoder.cpp.
References ErrorCode_Fail, ErrorCode_Success, and Model::m_RelationshipCb.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr || model == nullptr)
     {
         return ErrorCode::ErrorCode_Fail;
     }
     model->m_RelationshipCb = cb;
     return ErrorCode::ErrorCode_Success;
 }