ArmNN: src/backends/neon/test/NeonLayerSupportTests.cpp File Reference
NeonLayerSupportTests.cpp File Reference
#include "NeonWorkloadFactoryHelper.hpp"
#include <layers/ConvertFp16ToFp32Layer.hpp>
#include <layers/ConvertFp32ToFp16Layer.hpp>
#include <test/TensorHelpers.hpp>
#include <backendsCommon/CpuTensorHandle.hpp>
#include <neon/NeonWorkloadFactory.hpp>
#include <backendsCommon/test/IsLayerSupportedTestImpl.hpp>
#include <backendsCommon/test/LayerTests.hpp>
#include <boost/test/unit_test.hpp>
#include <string>
Functions
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat16Neon)
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat32Neon)
BOOST_AUTO_TEST_CASE (IsLayerSupportedUint8Neon)
BOOST_AUTO_TEST_CASE (IsLayerSupportedInt8Neon)
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedNeon)
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedNeon)
BOOST_AUTO_TEST_CASE (IsMeanSupportedNeon)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat16Neon)
Definition at line 23 of file NeonLayerSupportTests.cpp.
 {
     armnn::NeonWorkloadFactory factory =
         NeonWorkloadFactoryHelper::GetFactory(NeonWorkloadFactoryHelper::GetMemoryManager());
     IsLayerSupportedTests<armnn::NeonWorkloadFactory, armnn::DataType::Float16>(&factory);
 }
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat32Neon)
Definition at line 30 of file NeonLayerSupportTests.cpp.
 {
     armnn::NeonWorkloadFactory factory =
         NeonWorkloadFactoryHelper::GetFactory(NeonWorkloadFactoryHelper::GetMemoryManager());
     IsLayerSupportedTests<armnn::NeonWorkloadFactory, armnn::DataType::Float32>(&factory);
 }
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (IsLayerSupportedUint8Neon)
Definition at line 37 of file NeonLayerSupportTests.cpp.
 {
     armnn::NeonWorkloadFactory factory =
         NeonWorkloadFactoryHelper::GetFactory(NeonWorkloadFactoryHelper::GetMemoryManager());
     IsLayerSupportedTests<armnn::NeonWorkloadFactory, armnn::DataType::QAsymmU8>(&factory);
 }
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (IsLayerSupportedInt8Neon)
Definition at line 44 of file NeonLayerSupportTests.cpp.
 {
     armnn::NeonWorkloadFactory factory =
         NeonWorkloadFactoryHelper::GetFactory(NeonWorkloadFactoryHelper::GetMemoryManager());
     IsLayerSupportedTests<armnn::NeonWorkloadFactory, armnn::DataType::QSymmS8>(&factory);
 }
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedNeon)
Definition at line 51 of file NeonLayerSupportTests.cpp.
References BOOST_CHECK(), armnn::Float16, and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::NeonWorkloadFactory, armnn::ConvertFp16ToFp32Layer,
       armnn::DataType::Float16, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(result);
 }
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedNeon)
Definition at line 61 of file NeonLayerSupportTests.cpp.
References BOOST_CHECK(), armnn::Float16, and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::NeonWorkloadFactory, armnn::ConvertFp32ToFp16Layer,
       armnn::DataType::Float32, armnn::DataType::Float16>(reasonIfUnsupported);
     BOOST_CHECK(result);
 }
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (IsMeanSupportedNeon)
Definition at line 71 of file NeonLayerSupportTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), BOOST_CHECK(), and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsMeanLayerSupportedTests<armnn::NeonWorkloadFactory,
       armnn::DataType::Float32, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(result);
 }