ArmNN: src/profiling/test/ProfilingGuidTest.cpp File Reference
ProfilingGuidTest.cpp File Reference
#include <armnn/Types.hpp>
#include "LabelsAndEventClasses.hpp"
#include "ProfilingGuidGenerator.hpp"
#include <set>
#include <boost/test/unit_test.hpp>
#include <boost/format.hpp>
Functions
BOOST_AUTO_TEST_CASE (GuidTest)
BOOST_AUTO_TEST_CASE (StaticGuidTest)
BOOST_AUTO_TEST_CASE (DynamicGuidTest)
void CheckStaticGuid (uint64_t guid, uint64_t expectedGuid)
void CheckDynamicGuid (uint64_t guid, uint64_t expectedGuid)
BOOST_AUTO_TEST_CASE (StaticGuidGeneratorCollisionTest)
BOOST_AUTO_TEST_CASE (StaticGuidGeneratorTest)
BOOST_AUTO_TEST_CASE (DynamicGuidGeneratorTest)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (GuidTest)
Definition at line 20 of file ProfilingGuidTest.cpp.
 {
     ProfilingGuid guid0(0);
     ProfilingGuid guid1(1);
     ProfilingGuid guid2(1);
     BOOST_TEST(guid0 != guid1);
     BOOST_TEST(guid1 == guid2);
     BOOST_TEST(guid0 < guid1);
     BOOST_TEST(guid0 <= guid1);
     BOOST_TEST(guid1 <= guid2);
     BOOST_TEST(guid1 > guid0);
     BOOST_TEST(guid1 >= guid0);
     BOOST_TEST(guid1 >= guid2);
 }
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (StaticGuidTest)
Definition at line 36 of file ProfilingGuidTest.cpp.
 {
     ProfilingStaticGuid guid0(0);
     ProfilingStaticGuid guid1(1);
     ProfilingStaticGuid guid2(1);
     BOOST_TEST(guid0 != guid1);
     BOOST_TEST(guid1 == guid2);
     BOOST_TEST(guid0 < guid1);
     BOOST_TEST(guid0 <= guid1);
     BOOST_TEST(guid1 <= guid2);
     BOOST_TEST(guid1 > guid0);
     BOOST_TEST(guid1 >= guid0);
     BOOST_TEST(guid1 >= guid2);
 }
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (DynamicGuidTest)
Definition at line 52 of file ProfilingGuidTest.cpp.
 {
     ProfilingDynamicGuid guid0(0);
     ProfilingDynamicGuid guid1(1);
     ProfilingDynamicGuid guid2(1);
     BOOST_TEST(guid0 != guid1);
     BOOST_TEST(guid1 == guid2);
     BOOST_TEST(guid0 < guid1);
     BOOST_TEST(guid0 <= guid1);
     BOOST_TEST(guid1 <= guid2);
     BOOST_TEST(guid1 > guid0);
     BOOST_TEST(guid1 >= guid0);
     BOOST_TEST(guid1 >= guid2);
 }
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (StaticGuidGeneratorCollisionTest)
Definition at line 80 of file ProfilingGuidTest.cpp.
References ProfilingGuidGenerator::GenerateStaticId().
 {
     ProfilingGuidGenerator generator;
     std::set<uint64_t> guids;
     for ( int i = 0; i < 100000; ++i )
     {
         std::stringstream ss;
         ss << i;
         std::string str = ss.str();
         ProfilingStaticGuid guid = generator.GenerateStaticId(str.c_str());
         if (guids.find(guid) != guids.end())
         {
             BOOST_ERROR(boost::str(boost::format("GUID collision occurred: %1% -> %2%") % str % guid));
             break;
         }
         guids.insert(guid);
     }
 }
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (StaticGuidGeneratorTest)
Definition at line 99 of file ProfilingGuidTest.cpp.
References CheckStaticGuid(), ProfilingGuidGenerator::GenerateStaticId(), LabelsAndEventClasses::INDEX_GUID, LabelsAndEventClasses::NAME_GUID, and LabelsAndEventClasses::TYPE_GUID.
 {
     ProfilingGuidGenerator generator;
     ProfilingStaticGuid staticGuid0 = generator.GenerateStaticId("name");
     CheckStaticGuid(staticGuid0, LabelsAndEventClasses::NAME_GUID);
     BOOST_TEST(staticGuid0 != generator.GenerateStaticId("Name"));
     ProfilingStaticGuid staticGuid1 = generator.GenerateStaticId("type");
     CheckStaticGuid(staticGuid1, LabelsAndEventClasses::TYPE_GUID);
     BOOST_TEST(staticGuid1 != generator.GenerateStaticId("Type"));
     ProfilingStaticGuid staticGuid2 = generator.GenerateStaticId("index");
     CheckStaticGuid(staticGuid2, LabelsAndEventClasses::INDEX_GUID);
     BOOST_TEST(staticGuid2 != generator.GenerateStaticId("Index"));
 }
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (DynamicGuidGeneratorTest)
Definition at line 116 of file ProfilingGuidTest.cpp.
References BOOST_AUTO_TEST_SUITE_END(), CheckDynamicGuid(), and ProfilingGuidGenerator::NextGuid().
 {
     ProfilingGuidGenerator generator;
     for (unsigned int i = 0; i < 100; ++i)
     {
         ProfilingDynamicGuid guid = generator.NextGuid();
         CheckDynamicGuid(guid, i);
     }
 }
CheckDynamicGuid()
void CheckDynamicGuid (uint64_t guid, uint64_t expectedGuid)
Definition at line 74 of file ProfilingGuidTest.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     BOOST_TEST(guid == expectedGuid);
     BOOST_TEST(guid < MIN_STATIC_GUID);
 }
CheckStaticGuid()
void CheckStaticGuid (uint64_t guid, uint64_t expectedGuid)
Definition at line 68 of file ProfilingGuidTest.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     BOOST_TEST(guid == expectedGuid);
     BOOST_TEST(guid >= MIN_STATIC_GUID);
 }