ArmNN: src/backends/reference/test/RefLayerSupportTests.cpp File Reference
RefLayerSupportTests.cpp File Reference
#include <layers/ConvertFp16ToFp32Layer.hpp>
#include <layers/ConvertFp32ToFp16Layer.hpp>
#include <test/TensorHelpers.hpp>
#include <backendsCommon/CpuTensorHandle.hpp>
#include <reference/RefWorkloadFactory.hpp>
#include <reference/RefLayerSupport.hpp>
#include <backendsCommon/test/LayerTests.hpp>
#include <backendsCommon/test/IsLayerSupportedTestImpl.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/algorithm/string/trim.hpp>
#include <string>
Functions
BOOST_AUTO_TEST_CASE (IsLayerSupportedLayerTypeMatches)
BOOST_AUTO_TEST_CASE (IsLayerSupportedReferenceAddition)
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat16Reference)
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat32Reference)
BOOST_AUTO_TEST_CASE (IsLayerSupportedUint8Reference)
BOOST_AUTO_TEST_CASE (IsLayerSupportedInt8Reference)
BOOST_AUTO_TEST_CASE (IsLayerSupportedInt16Reference)
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedReference)
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedFp32InputReference)
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedFp16OutputReference)
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedReference)
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedFp16InputReference)
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedFp32OutputReference)
BOOST_AUTO_TEST_CASE (IsLayerSupportedMeanDimensionsReference)
BOOST_AUTO_TEST_CASE (IsLayerNotSupportedMeanDimensionsReference)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedLayerTypeMatches)
Definition at line 33 of file RefLayerSupportTests.cpp.
 {
     LayerTypeMatchesTest();
 }
BOOST_AUTO_TEST_CASE() [2/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedReferenceAddition)
Definition at line 37 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), armnn::Float32, and RefLayerSupport::IsAdditionSupported().
 {
     armnn::TensorShape shape0 = {1,1,3,4};
     armnn::TensorShape shape1 = {4};
     armnn::TensorShape outShape = {1,1,3,4};
     armnn::TensorInfo in0(shape0, armnn::DataType::Float32);
     armnn::TensorInfo in1(shape1, armnn::DataType::Float32);
     armnn::TensorInfo out(outShape, armnn::DataType::Float32);
     armnn::RefLayerSupport supportChecker;
     std::string reasonNotSupported;
     BOOST_CHECK(supportChecker.IsAdditionSupported(in0, in1, out, reasonNotSupported));
 }
BOOST_AUTO_TEST_CASE() [3/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat16Reference)
Definition at line 51 of file RefLayerSupportTests.cpp.
 {
     armnn::RefWorkloadFactory factory;
     IsLayerSupportedTests<armnn::RefWorkloadFactory, armnn::DataType::Float16>(&factory);
 }
BOOST_AUTO_TEST_CASE() [4/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedFloat32Reference)
Definition at line 57 of file RefLayerSupportTests.cpp.
 {
     armnn::RefWorkloadFactory factory;
     IsLayerSupportedTests<armnn::RefWorkloadFactory, armnn::DataType::Float32>(&factory);
 }
BOOST_AUTO_TEST_CASE() [5/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedUint8Reference)
Definition at line 63 of file RefLayerSupportTests.cpp.
 {
     armnn::RefWorkloadFactory factory;
     IsLayerSupportedTests<armnn::RefWorkloadFactory, armnn::DataType::QAsymmU8>(&factory);
 }
BOOST_AUTO_TEST_CASE() [6/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedInt8Reference)
Definition at line 69 of file RefLayerSupportTests.cpp.
 {
     armnn::RefWorkloadFactory factory;
     IsLayerSupportedTests<armnn::RefWorkloadFactory, armnn::DataType::QSymmS8>(&factory);
 }
BOOST_AUTO_TEST_CASE() [7/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedInt16Reference)
Definition at line 75 of file RefLayerSupportTests.cpp.
 {
     armnn::RefWorkloadFactory factory;
     IsLayerSupportedTests<armnn::RefWorkloadFactory, armnn::DataType::QSymmS16>(&factory);
 }
BOOST_AUTO_TEST_CASE() [8/15]
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedReference)
Definition at line 81 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), armnn::Float16, and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::RefWorkloadFactory, armnn::ConvertFp16ToFp32Layer,
       armnn::DataType::Float16, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(result);
 }
BOOST_AUTO_TEST_CASE() [9/15]
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedFp32InputReference)
Definition at line 91 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::RefWorkloadFactory, armnn::ConvertFp16ToFp32Layer,
       armnn::DataType::Float32, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(!result);
     BOOST_CHECK_EQUAL(reasonIfUnsupported, "Layer is not supported with float32 data type input");
 }
BOOST_AUTO_TEST_CASE() [10/15]
BOOST_AUTO_TEST_CASE (IsConvertFp16ToFp32SupportedFp16OutputReference)
Definition at line 102 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), and armnn::Float16.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::RefWorkloadFactory, armnn::ConvertFp16ToFp32Layer,
       armnn::DataType::Float16, armnn::DataType::Float16>(reasonIfUnsupported);
     BOOST_CHECK(!result);
     BOOST_CHECK_EQUAL(reasonIfUnsupported, "Layer is not supported with float16 data type output");
 }
BOOST_AUTO_TEST_CASE() [11/15]
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedReference)
Definition at line 113 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), armnn::Float16, and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::RefWorkloadFactory, armnn::ConvertFp32ToFp16Layer,
       armnn::DataType::Float32, armnn::DataType::Float16>(reasonIfUnsupported);
     BOOST_CHECK(result);
 }
BOOST_AUTO_TEST_CASE() [12/15]
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedFp16InputReference)
Definition at line 123 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), and armnn::Float16.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::RefWorkloadFactory, armnn::ConvertFp32ToFp16Layer,
       armnn::DataType::Float16, armnn::DataType::Float16>(reasonIfUnsupported);
     BOOST_CHECK(!result);
     BOOST_CHECK_EQUAL(reasonIfUnsupported, "Layer is not supported with float16 data type input");
 }
BOOST_AUTO_TEST_CASE() [13/15]
BOOST_AUTO_TEST_CASE (IsConvertFp32ToFp16SupportedFp32OutputReference)
Definition at line 134 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsConvertLayerSupportedTests<armnn::RefWorkloadFactory, armnn::ConvertFp32ToFp16Layer,
       armnn::DataType::Float32, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(!result);
     BOOST_CHECK_EQUAL(reasonIfUnsupported, "Layer is not supported with float32 data type output");
 }
BOOST_AUTO_TEST_CASE() [14/15]
BOOST_AUTO_TEST_CASE (IsLayerSupportedMeanDimensionsReference)
Definition at line 145 of file RefLayerSupportTests.cpp.
References BOOST_CHECK(), and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsMeanLayerSupportedTests<armnn::RefWorkloadFactory,
             armnn::DataType::Float32, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(result);
 }
BOOST_AUTO_TEST_CASE() [15/15]
BOOST_AUTO_TEST_CASE (IsLayerNotSupportedMeanDimensionsReference)
Definition at line 155 of file RefLayerSupportTests.cpp.
References BOOST_AUTO_TEST_SUITE_END(), BOOST_CHECK(), and armnn::Float32.
 {
     std::string reasonIfUnsupported;
     bool result = IsMeanLayerNotSupportedTests<armnn::RefWorkloadFactory,
             armnn::DataType::Float32, armnn::DataType::Float32>(reasonIfUnsupported);
     BOOST_CHECK(!result);
     boost::algorithm::trim(reasonIfUnsupported);
     BOOST_CHECK_EQUAL(reasonIfUnsupported,
                       "Reference Mean: Expected 4 dimensions but got 2 dimensions instead, for the 'output' tensor.");
 }