ArmNN: src/backends/backendsCommon/test/layerTests/SliceTestImpl.hpp File Reference
SliceTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > Slice4dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 3 > Slice3dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 2 > Slice2dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 1 > Slice1dFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 4 > Slice4dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 3 > Slice3dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 2 > Slice2dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< uint8_t, 1 > Slice1dUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 4 > Slice4dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 3 > Slice3dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 2 > Slice2dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< int16_t, 1 > Slice1dInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
Slice1dFloat32Test()
LayerTestResult<float, 1> Slice1dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 238 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice1dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Slice1dInt16Test()
LayerTestResult<int16_t, 1> Slice1dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 288 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice1dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Slice1dUint8Test()
LayerTestResult<uint8_t, 1> Slice1dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 263 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice1dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Slice2dFloat32Test()
LayerTestResult<float, 2> Slice2dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 232 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice2dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Slice2dInt16Test()
LayerTestResult<int16_t, 2> Slice2dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 282 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice2dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Slice2dUint8Test()
LayerTestResult<uint8_t, 2> Slice2dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 257 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice2dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Slice3dFloat32Test()
LayerTestResult<float, 3> Slice3dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 226 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice3dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Slice3dInt16Test()
LayerTestResult<int16_t, 3> Slice3dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 276 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice3dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Slice3dUint8Test()
LayerTestResult<uint8_t, 3> Slice3dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 251 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice3dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
Slice4dFloat32Test()
LayerTestResult<float, 4> Slice4dFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 220 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice4dTest<armnn::DataType::Float32>(workloadFactory, memoryManager);
 }
Slice4dInt16Test()
LayerTestResult<int16_t, 4> Slice4dInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 270 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice4dTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
Slice4dUint8Test()
LayerTestResult<uint8_t, 4> Slice4dUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 245 of file SliceTestImpl.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return Slice4dTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }