ArmNN: tests/profiling/timelineDecoder/tests/TimelineTestFunctions.hpp File Reference
TimelineTestFunctions.hpp File Reference
#include <algorithm>
#include "../TimelineModel.h"
Functions
void PushEntity (const Entity entity, Model *model)
void PushEventClass (const EventClass eventClass, Model *model)
void PushEvent (const Event event, Model *model)
void PushLabel (const Label label, Model *model)
void PushRelationship (const Relationship relationship, Model *model)
Function Documentation
PushEntity()
void PushEntity (const Entity entity, Model * model)
Definition at line 9 of file TimelineTestFunctions.hpp.
References Model::m_Entities, Model::m_EntityCapacity, Model::m_EntityCount, and Entity::m_Guid.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if(model->m_EntityCount == 0)
     {
         model->m_EntityCapacity = 1;
         model->m_Entities = new Entity*[model->m_EntityCapacity];
     }
     else if(model->m_EntityCount >= model->m_EntityCapacity)
     {
         Entity** newEntityArray = new Entity*[model->m_EntityCapacity*2];
         std::copy(model->m_Entities, model->m_Entities + model->m_EntityCapacity, newEntityArray);
         delete[] model->m_Entities;
         model->m_Entities = newEntityArray;
         model->m_EntityCapacity = model->m_EntityCapacity *2;
     }
     Entity* newEntity = new Entity;
     newEntity->m_Guid = entity.m_Guid;
     model->m_Entities[model->m_EntityCount] = newEntity;
     model->m_EntityCount++;
 };
PushEvent()
void PushEvent (const Event event, Model * model)
Definition at line 61 of file TimelineTestFunctions.hpp.
References Model::m_EventCapacity, Model::m_EventCount, Model::m_Events, Event::m_Guid, Event::m_ThreadId, and Event::m_TimeStamp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if(model->m_EventCount == 0)
     {
         model->m_EventCapacity = 1;
         model->m_Events = new Event*[model->m_EventCapacity];
     }
     else if(model->m_EventCount >= model->m_EventCapacity)
     {
         Event** newEventArray = new Event*[model->m_EventCapacity * 2];
         std::copy(model->m_Events, model->m_Events + model->m_EventCapacity, newEventArray);
         delete[] model->m_Events;
         model->m_Events = newEventArray;
         model->m_EventCapacity = model->m_EventCapacity *2;
     }
     Event* newEvent = new Event;
     newEvent->m_TimeStamp = event.m_TimeStamp;
     newEvent->m_ThreadId = event.m_ThreadId;
     newEvent->m_Guid = event.m_Guid;
     model->m_Events[model->m_EventCount] = newEvent;
     model->m_EventCount++;
 };
PushEventClass()
void PushEventClass (const EventClass eventClass, Model * model)
Definition at line 35 of file TimelineTestFunctions.hpp.
References Model::m_EventClassCapacity, Model::m_EventClassCount, Model::m_EventClasses, and EventClass::m_Guid.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if(model->m_EventClassCount == 0)
     {
         model->m_EventClassCapacity = 1;
         model->m_EventClasses = new EventClass*[model->m_EventClassCapacity];
     }
     else if(model->m_EventClassCount >= model->m_EventClassCapacity)
     {
         EventClass** newEventClassArray = new EventClass*[model->m_EventClassCapacity *2];
         std::copy(model->m_EventClasses, model->m_EventClasses + model->m_EventClassCapacity, newEventClassArray);
         delete[] model->m_EventClasses;
         model->m_EventClasses = newEventClassArray;
         model->m_EventClassCapacity = model->m_EventClassCapacity *2;
     }
     EventClass* newEventClass = new EventClass;
     newEventClass->m_Guid = eventClass.m_Guid;
     model->m_EventClasses[model->m_EventClassCount] = newEventClass;
     model->m_EventClassCount++;
 };
PushLabel()
void PushLabel (const Label label, Model * model)
Definition at line 89 of file TimelineTestFunctions.hpp.
References Label::m_Guid, Model::m_LabelCapacity, Model::m_LabelCount, Model::m_Labels, and Label::m_Name.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if(model->m_LabelCount == 0)
     {
         model->m_LabelCapacity = 1;
         model->m_Labels = new Label*[model->m_LabelCapacity];
     }
     else if(model->m_LabelCount >= model->m_LabelCapacity)
     {
         Label** newLabelArray = new Label*[model->m_LabelCapacity *2];
         std::copy(model->m_Labels, model->m_Labels + model->m_LabelCapacity, newLabelArray);
         delete[] model->m_Labels;
         model->m_Labels = newLabelArray;
         model->m_LabelCapacity = model->m_LabelCapacity *2;
     }
     Label* newLabel = new Label;
     newLabel->m_Guid = label.m_Guid;
     newLabel->m_Name = label.m_Name;
     model->m_Labels[model->m_LabelCount] = newLabel;
     model->m_LabelCount++;
 };
PushRelationship()
void PushRelationship (const Relationship relationship, Model * model)
Definition at line 116 of file TimelineTestFunctions.hpp.
References Relationship::m_Guid, Relationship::m_HeadGuid, Model::m_RelationshipCapacity, Model::m_RelationshipCount, Model::m_Relationships, Relationship::m_RelationshipType, and Relationship::m_TailGuid.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if(model->m_RelationshipCount == 0)
     {
         model->m_RelationshipCapacity = 1;
         model->m_Relationships = new Relationship*[model->m_RelationshipCapacity];
     }
     else if(model->m_RelationshipCount >= model->m_RelationshipCapacity)
     {
         Relationship** newRelationshipArray = new Relationship*[model->m_RelationshipCapacity *2];
         std::copy(model->m_Relationships, model->m_Relationships + model->m_RelationshipCapacity, newRelationshipArray);
         delete[] model->m_Relationships;
         model->m_Relationships = newRelationshipArray;
         model->m_RelationshipCapacity = model->m_RelationshipCapacity *2;
     }
     Relationship* newRelationship = new Relationship;
     newRelationship->m_Guid = relationship.m_Guid;
     newRelationship->m_RelationshipType = relationship.m_RelationshipType;
     newRelationship->m_HeadGuid = relationship.m_HeadGuid;
     newRelationship->m_TailGuid = relationship.m_TailGuid;
     model->m_Relationships[model->m_RelationshipCount] = newRelationship;
     model->m_RelationshipCount++;
 };