ArmNN: MockCounterDirectory Class Reference
MockCounterDirectory Class Reference
#include <ProfilingMocks.hpp>
Public Member Functions
MockCounterDirectory ()=default
~MockCounterDirectory ()=default
const Category * RegisterCategory (const std::string &categoryName, const armnn::Optional< uint16_t > &deviceUid=armnn::EmptyOptional(), const armnn::Optional< uint16_t > &counterSetUid=armnn::EmptyOptional())
const Device * RegisterDevice (const std::string &deviceName, uint16_t cores=0, const armnn::Optional< std::string > &parentCategoryName=armnn::EmptyOptional())
const CounterSet * RegisterCounterSet (const std::string &counterSetName, uint16_t count=0, const armnn::Optional< std::string > &parentCategoryName=armnn::EmptyOptional())
const Counter * RegisterCounter (const BackendId &backendId, const uint16_t uid, const std::string &parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string &name, const std::string &description, const armnn::Optional< std::string > &units=armnn::EmptyOptional(), const armnn::Optional< uint16_t > &numberOfCores=armnn::EmptyOptional(), const armnn::Optional< uint16_t > &deviceUid=armnn::EmptyOptional(), const armnn::Optional< uint16_t > &counterSetUid=armnn::EmptyOptional())
uint16_t GetCategoryCount () const override
uint16_t GetDeviceCount () const override
uint16_t GetCounterSetCount () const override
uint16_t GetCounterCount () const override
const Categories & GetCategories () const override
const Devices & GetDevices () const override
const CounterSets & GetCounterSets () const override
const Counters & GetCounters () const override
const Category * GetCategory (const std::string &name) const override
const Device * GetDevice (uint16_t uid) const override
const CounterSet * GetCounterSet (uint16_t uid) const override
const Counter * GetCounter (uint16_t uid) const override
Public Member Functions inherited from ICounterDirectory
virtual ~ICounterDirectory ()
Detailed Description
Definition at line 439 of file ProfilingMocks.hpp.
Constructor & Destructor Documentation
MockCounterDirectory()
MockCounterDirectory () default
~MockCounterDirectory()
~MockCounterDirectory () default
Member Function Documentation
GetCategories()
const Categories& GetCategories () const inline override virtual
Implements ICounterDirectory.
Definition at line 603 of file ProfilingMocks.hpp.
 { return m_Categories;  }
GetCategory()
const Category* GetCategory (const std::string & name) const inline override virtual
Implements ICounterDirectory.
Definition at line 609 of file ProfilingMocks.hpp.
     {
         auto it = std::find_if(m_Categories.begin(), m_Categories.end(), [&name](const CategoryPtr& category)
         {
             BOOST_ASSERT(category);
             return category->m_Name == name;
         });
         if (it == m_Categories.end())
         {
             return nullptr;
         }
         return it->get();
     }
GetCategoryCount()
uint16_t GetCategoryCount () const inline override virtual
Implements ICounterDirectory.
Definition at line 597 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return boost::numeric_cast<uint16_t>(m_Categories.size());  }
GetCounter()
const Counter* GetCounter (uint16_t uid) const inline override virtual
Implements ICounterDirectory.
Definition at line 638 of file ProfilingMocks.hpp.
     {
         boost::ignore_unused(uid);
         return nullptr; // Not used by the unit tests
     }
GetCounterCount()
uint16_t GetCounterCount () const inline override virtual
Implements ICounterDirectory.
Definition at line 600 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return boost::numeric_cast<uint16_t>(m_Counters.size());    }
GetCounters()
const Counters& GetCounters () const inline override virtual
Implements ICounterDirectory.
Definition at line 606 of file ProfilingMocks.hpp.
 { return m_Counters;    }
GetCounterSet()
const CounterSet* GetCounterSet (uint16_t uid) const inline override virtual
Implements ICounterDirectory.
Definition at line 632 of file ProfilingMocks.hpp.
     {
         boost::ignore_unused(uid);
         return nullptr; // Not used by the unit tests
     }
GetCounterSetCount()
uint16_t GetCounterSetCount () const inline override virtual
Implements ICounterDirectory.
Definition at line 599 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return boost::numeric_cast<uint16_t>(m_CounterSets.size()); }
GetCounterSets()
const CounterSets& GetCounterSets () const inline override virtual
Implements ICounterDirectory.
Definition at line 605 of file ProfilingMocks.hpp.
 { return m_CounterSets; }
GetDevice()
const Device* GetDevice (uint16_t uid) const inline override virtual
Implements ICounterDirectory.
Definition at line 626 of file ProfilingMocks.hpp.
     {
         boost::ignore_unused(uid);
         return nullptr; // Not used by the unit tests
     }
GetDeviceCount()
uint16_t GetDeviceCount () const inline override virtual
Implements ICounterDirectory.
Definition at line 598 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return boost::numeric_cast<uint16_t>(m_Devices.size());     }
GetDevices()
const Devices& GetDevices () const inline override virtual
Implements ICounterDirectory.
Definition at line 604 of file ProfilingMocks.hpp.
 { return m_Devices;     }
RegisterCategory()
const Category* RegisterCategory (const std::string & categoryName, const armnn::Optional< uint16_t > & deviceUid = armnn::EmptyOptional(), const armnn::Optional< uint16_t > & counterSetUid = armnn::EmptyOptional()) inline
Definition at line 446 of file ProfilingMocks.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         // Get the device UID
         uint16_t deviceUidValue = deviceUid.has_value() ? deviceUid.value() : 0;
         // Get the counter set UID
         uint16_t counterSetUidValue = counterSetUid.has_value() ? counterSetUid.value() : 0;
         // Create the category
         CategoryPtr category = std::make_unique<Category>(categoryName, deviceUidValue, counterSetUidValue);
         BOOST_ASSERT(category);
         // Get the raw category pointer
         const Category* categoryPtr = category.get();
         BOOST_ASSERT(categoryPtr);
         // Register the category
         m_Categories.insert(std::move(category));
         return categoryPtr;
     }
RegisterCounter()
const Counter* RegisterCounter (const BackendId & backendId, const uint16_t uid, const std::string & parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string & name, const std::string & description, const armnn::Optional< std::string > & units = armnn::EmptyOptional(), const armnn::Optional< uint16_t > & numberOfCores = armnn::EmptyOptional(), const armnn::Optional< uint16_t > & deviceUid = armnn::EmptyOptional(), const armnn::Optional< uint16_t > & counterSetUid = armnn::EmptyOptional()) inline
Definition at line 531 of file ProfilingMocks.hpp.
References armnn::profiling::GetNextCounterUids(), and Category::m_Counters.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         boost::ignore_unused(backendId);
         // Get the number of cores from the argument only
         uint16_t deviceCores = numberOfCores.has_value() ? numberOfCores.value() : 0;
         // Get the device UID
         uint16_t deviceUidValue = deviceUid.has_value() ? deviceUid.value() : 0;
         // Get the counter set UID
         uint16_t counterSetUidValue = counterSetUid.has_value() ? counterSetUid.value() : 0;
         // Get the counter UIDs and calculate the max counter UID
         std::vector<uint16_t> counterUids = GetNextCounterUids(uid, deviceCores);
         BOOST_ASSERT(!counterUids.empty());
         uint16_t maxCounterUid = deviceCores <= 1 ? counterUids.front() : counterUids.back();
         // Get the counter units
         const std::string unitsValue = units.has_value() ? units.value() : "";
         // Create the counter
         CounterPtr counter = std::make_shared<Counter>(armnn::profiling::BACKEND_ID,
                                                        counterUids.front(),
                                                        maxCounterUid,
                                                        counterClass,
                                                        interpolation,
                                                        multiplier,
                                                        name,
                                                        description,
                                                        unitsValue,
                                                        deviceUidValue,
                                                        counterSetUidValue);
         BOOST_ASSERT(counter);
         // Get the raw counter pointer
         const Counter* counterPtr = counter.get();
         BOOST_ASSERT(counterPtr);
         // Process multiple counters if necessary
         for (uint16_t counterUid : counterUids)
         {
             // Connect the counter to the parent category
             Category* parentCategory = const_cast<Category*>(GetCategory(parentCategoryName));
             BOOST_ASSERT(parentCategory);
             parentCategory->m_Counters.push_back(counterUid);
             // Register the counter
             m_Counters.insert(std::make_pair(counterUid, counter));
         }
         return counterPtr;
     }
RegisterCounterSet()
const CounterSet* RegisterCounterSet (const std::string & counterSetName, uint16_t count = 0, const armnn::Optional< std::string > & parentCategoryName = armnn::EmptyOptional()) inline
Definition at line 500 of file ProfilingMocks.hpp.
References armnn::profiling::GetNextUid(), and Category::m_CounterSetUid.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         // Get the counter set UID
         uint16_t counterSetUid = GetNextUid();
         // Create the counter set
         CounterSetPtr counterSet = std::make_unique<CounterSet>(counterSetUid, counterSetName, count);
         BOOST_ASSERT(counterSet);
         // Get the raw counter set pointer
         const CounterSet* counterSetPtr = counterSet.get();
         BOOST_ASSERT(counterSetPtr);
         // Register the counter set
         m_CounterSets.insert(std::make_pair(counterSetUid, std::move(counterSet)));
         // Connect the counter set to the parent category, if required
         if (parentCategoryName.has_value())
         {
             // Set the counter set UID in the parent category
             Category* parentCategory = const_cast<Category*>(GetCategory(parentCategoryName.value()));
             BOOST_ASSERT(parentCategory);
             parentCategory->m_CounterSetUid = counterSetUid;
         }
         return counterSetPtr;
     }
RegisterDevice()
const Device* RegisterDevice (const std::string & deviceName, uint16_t cores = 0, const armnn::Optional< std::string > & parentCategoryName = armnn::EmptyOptional()) inline
Definition at line 470 of file ProfilingMocks.hpp.
References armnn::profiling::GetNextUid(), and Category::m_DeviceUid.
Referenced by BOOST_AUTO_TEST_CASE().
     {
         // Get the device UID
         uint16_t deviceUid = GetNextUid();
         // Create the device
         DevicePtr device = std::make_unique<Device>(deviceUid, deviceName, cores);
         BOOST_ASSERT(device);
         // Get the raw device pointer
         const Device* devicePtr = device.get();
         BOOST_ASSERT(devicePtr);
         // Register the device
         m_Devices.insert(std::make_pair(deviceUid, std::move(device)));
         // Connect the counter set to the parent category, if required
         if (parentCategoryName.has_value())
         {
             // Set the counter set UID in the parent category
             Category* parentCategory = const_cast<Category*>(GetCategory(parentCategoryName.value()));
             BOOST_ASSERT(parentCategory);
             parentCategory->m_DeviceUid = deviceUid;
         }
         return devicePtr;
     }
The documentation for this class was generated from the following file:
src/profiling/test/ProfilingMocks.hpp