ArmNN: NeonPermuteWorkload Class Reference
NeonPermuteWorkload Class Reference
#include <NeonPermuteWorkload.hpp>
Public Member Functions
NeonPermuteWorkload (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info)
void Execute () const override
Public Member Functions inherited from BaseWorkload< PermuteQueueDescriptor >
BaseWorkload (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const PermuteQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Static Public Member Functions
static const std::string & GetName ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< PermuteQueueDescriptor >
const PermuteQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 22 of file NeonPermuteWorkload.hpp.
Constructor & Destructor Documentation
NeonPermuteWorkload()
NeonPermuteWorkload (const PermuteQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 27 of file NeonPermuteWorkload.cpp.
Referenced by NeonPermuteWorkload::GetName().
         : BaseWorkload<PermuteQueueDescriptor>(descriptor, info)
 {
     using armcomputetensorutils::BuildArmComputePermutationVector;
     m_Data.ValidateInputsOutputs(GetName(), 1, 1);
     const arm_compute::ITensor& input = static_cast<IAclTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ITensor& output = static_cast<IAclTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     const armnn::PermutationVector& mappings = m_Data.m_Parameters.m_DimMappings;
     // Run the layer.
     m_PermuteFunction.configure(&input, &output, BuildArmComputePermutationVector(mappings));
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 43 of file NeonPermuteWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_NEON, and NeonPermuteWorkload::GetName().
Referenced by NeonPermuteWorkload::GetName().
 {
     ARMNN_SCOPED_PROFILING_EVENT_NEON(GetName() + "_Execute");
     m_PermuteFunction.run();
 }
GetName()
static const std::string& GetName () inline static
Definition at line 25 of file NeonPermuteWorkload.hpp.
References NeonPermuteWorkload::Execute(), armnn::info, and NeonPermuteWorkload::NeonPermuteWorkload().
Referenced by NeonPermuteWorkload::Execute().
     {
         static const std::string name = std::string("NeonPermuteWorkload");
         return name;
     }
The documentation for this class was generated from the following files:
src/backends/neon/workloads/NeonPermuteWorkload.hpp
src/backends/neon/workloads/NeonPermuteWorkload.cpp