ArmNN: RegisterBackendCounters Class Reference
RegisterBackendCounters Class Reference
#include <RegisterBackendCounters.hpp>
Public Member Functions
RegisterBackendCounters (uint16_t currentMaxGlobalCounterID, const BackendId &backendId)
~RegisterBackendCounters ()=default
void RegisterCategory (const std::string &categoryName, const Optional< uint16_t > &deviceUid=EmptyOptional(), const Optional< uint16_t > &counterSetUid=EmptyOptional()) override
uint16_t RegisterDevice (const std::string &deviceName, uint16_t cores=0, const Optional< std::string > &parentCategoryName=EmptyOptional()) override
uint16_t RegisterCounterSet (const std::string &counterSetName, uint16_t count=0, const Optional< std::string > &parentCategoryName=EmptyOptional()) override
uint16_t RegisterCounter (const uint16_t uid, const std::string &parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string &name, const std::string &description, const Optional< std::string > &units=EmptyOptional(), const Optional< uint16_t > &numberOfCores=EmptyOptional(), const Optional< uint16_t > &deviceUid=EmptyOptional(), const Optional< uint16_t > &counterSetUid=EmptyOptional()) override
Public Member Functions inherited from IRegisterBackendCounters
virtual ~IRegisterBackendCounters ()
Detailed Description
Definition at line 19 of file RegisterBackendCounters.hpp.
Constructor & Destructor Documentation
RegisterBackendCounters()
RegisterBackendCounters (uint16_t currentMaxGlobalCounterID, const BackendId & backendId) inline
Definition at line 23 of file RegisterBackendCounters.hpp.
References RegisterBackendCounters::RegisterCategory(), RegisterBackendCounters::RegisterCounter(), RegisterBackendCounters::RegisterCounterSet(), RegisterBackendCounters::RegisterDevice(), and RegisterBackendCounters::~RegisterBackendCounters().
                             : m_CurrentMaxGlobalCounterID(currentMaxGlobalCounterID),
                               m_CounterDirectory(ProfilingService::Instance().GetCounterRegistry()),
                               m_BackendId(backendId) {}
~RegisterBackendCounters()
~RegisterBackendCounters () default
Referenced by RegisterBackendCounters::RegisterBackendCounters().
Member Function Documentation
RegisterCategory()
void RegisterCategory (const std::string & categoryName, const Optional< uint16_t > & deviceUid = EmptyOptional(), const Optional< uint16_t > & counterSetUid = EmptyOptional()) override virtual
Implements IRegisterBackendCounters.
Definition at line 14 of file RegisterBackendCounters.cpp.
References ICounterRegistry::RegisterCategory().
Referenced by BOOST_AUTO_TEST_CASE(), and RegisterBackendCounters::RegisterBackendCounters().
 {
      m_CounterDirectory.RegisterCategory(categoryName, deviceUid, counterSetUid);
 }
RegisterCounter()
uint16_t RegisterCounter (const uint16_t uid, const std::string & parentCategoryName, uint16_t counterClass, uint16_t interpolation, double multiplier, const std::string & name, const std::string & description, const Optional< std::string > & units = EmptyOptional(), const Optional< uint16_t > & numberOfCores = EmptyOptional(), const Optional< uint16_t > & deviceUid = EmptyOptional(), const Optional< uint16_t > & counterSetUid = EmptyOptional()) override virtual
Implements IRegisterBackendCounters.
Definition at line 37 of file RegisterBackendCounters.cpp.
References ProfilingService::GetCounterMappingRegistry(), ProfilingService::Instance(), Counter::m_MaxCounterUid, Counter::m_Uid, ICounterRegistry::RegisterCounter(), and IRegisterCounterMapping::RegisterMapping().
Referenced by BOOST_AUTO_TEST_CASE(), and RegisterBackendCounters::RegisterBackendCounters().
 {
     ++m_CurrentMaxGlobalCounterID;
     const Counter* counterPtr = m_CounterDirectory.RegisterCounter(m_BackendId,
                                                                    m_CurrentMaxGlobalCounterID,
                                                                    parentCategoryName,
                                                                    counterClass,
                                                                    interpolation,
                                                                    multiplier,
                                                                    name,
                                                                    description,
                                                                    units,
                                                                    numberOfCores,
                                                                    deviceUid,
                                                                    counterSetUid);
     m_CurrentMaxGlobalCounterID = counterPtr->m_MaxCounterUid;
     // register mappings
     IRegisterCounterMapping& counterIdMap = ProfilingService::Instance().GetCounterMappingRegistry();
     uint16_t globalCounterId = counterPtr->m_Uid;
     if (globalCounterId == counterPtr->m_MaxCounterUid)
     {
         counterIdMap.RegisterMapping(globalCounterId, uid, m_BackendId);
     }
     else
     {
         uint16_t backendCounterId = uid;
         while (globalCounterId <= counterPtr->m_MaxCounterUid)
         {
             // register mapping
             // globalCounterId -> backendCounterId, m_BackendId
             counterIdMap.RegisterMapping(globalCounterId, backendCounterId, m_BackendId);
             ++globalCounterId;
             ++backendCounterId;
         }
     }
     return m_CurrentMaxGlobalCounterID;
 }
RegisterCounterSet()
uint16_t RegisterCounterSet (const std::string & counterSetName, uint16_t count = 0, const Optional< std::string > & parentCategoryName = EmptyOptional()) override virtual
Implements IRegisterBackendCounters.
Definition at line 29 of file RegisterBackendCounters.cpp.
References CounterSet::m_Uid, and ICounterRegistry::RegisterCounterSet().
Referenced by BOOST_AUTO_TEST_CASE(), and RegisterBackendCounters::RegisterBackendCounters().
 {
     const CounterSet* counterSetPtr = m_CounterDirectory.RegisterCounterSet(counterSetName, count, parentCategoryName);
     return counterSetPtr->m_Uid;
 }
RegisterDevice()
uint16_t RegisterDevice (const std::string & deviceName, uint16_t cores = 0, const Optional< std::string > & parentCategoryName = EmptyOptional()) override virtual
Implements IRegisterBackendCounters.
Definition at line 21 of file RegisterBackendCounters.cpp.
References Device::m_Uid, and ICounterRegistry::RegisterDevice().
Referenced by BOOST_AUTO_TEST_CASE(), and RegisterBackendCounters::RegisterBackendCounters().
 {
     const Device* devicePtr = m_CounterDirectory.RegisterDevice(deviceName, cores, parentCategoryName);
     return devicePtr->m_Uid;
 }
The documentation for this class was generated from the following files:
src/profiling/RegisterBackendCounters.hpp
src/profiling/RegisterBackendCounters.cpp