ArmNN: PacketVersionResolver Class Reference
PacketVersionResolver Class Reference final
#include <PacketVersionResolver.hpp>
Public Member Functions
PacketVersionResolver ()=default
~PacketVersionResolver ()=default
Version ResolvePacketVersion (uint32_t familyId, uint32_t packetId) const
Detailed Description
Definition at line 36 of file PacketVersionResolver.hpp.
Constructor & Destructor Documentation
PacketVersionResolver()
PacketVersionResolver () default
~PacketVersionResolver()
~PacketVersionResolver () default
Member Function Documentation
ResolvePacketVersion()
Version ResolvePacketVersion (uint32_t familyId, uint32_t packetId) const
Definition at line 55 of file PacketVersionResolver.cpp.
References armnn::IgnoreUnused().
Referenced by BOOST_AUTO_TEST_CASE(), main(), CommandHandler::Stop(), GatordMockService::WaitCommand(), and FileOnlyProfilingConnection::WritePacket().
 {
     IgnoreUnused(familyId, packetId);
     // NOTE: For now every packet specification is at version 1.0.0
     return Version(1, 0, 0);
 }
The documentation for this class was generated from the following files:
src/profiling/PacketVersionResolver.hpp
src/profiling/PacketVersionResolver.cpp