ArmNN: MockBackendInitialiser Class Reference
MockBackendInitialiser Class Reference
#include <MockBackend.hpp>
Public Member Functions
MockBackendInitialiser ()
~MockBackendInitialiser ()
Detailed Description
Definition at line 22 of file MockBackend.hpp.
Constructor & Destructor Documentation
MockBackendInitialiser()
MockBackendInitialiser ()
Definition at line 70 of file MockBackend.cpp.
References armnn::BackendRegistryInstance(), MockBackend::GetIdStatic(), and BackendRegistry::Register().
 {
     BackendRegistryInstance().Register(MockBackend::GetIdStatic(),
                                        []()
{
                                            return IBackendInternalUniquePtr(new MockBackend);
                                        });
 }
~MockBackendInitialiser()
~MockBackendInitialiser ()
Definition at line 79 of file MockBackend.cpp.
References armnn::BackendRegistryInstance(), BackendRegistry::Deregister(), and MockBackend::GetIdStatic().
 {
     try
     {
         BackendRegistryInstance().Deregister(MockBackend::GetIdStatic());
     }
     catch (...)
     {
         std::cerr << "could not deregister mock backend" << std::endl;
     }
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/test/MockBackend.hpp
src/backends/backendsCommon/test/MockBackend.cpp