ArmNN: Convolution2dLayer Class Reference
Convolution2dLayer Class Reference
This layer represents a convolution 2d operation.
#include <Convolution2dLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Convolution2dLayer * Clone (Graph &graph) const override
void ValidateTensorShapesFromInputs () override
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
void Accept (ILayerVisitor &visitor) const override
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Public Member Functions inherited from LayerWithParameters< Convolution2dDescriptor >
const Convolution2dDescriptor & GetParameters () const
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
unsigned int GetNumInputSlots () const override
unsigned int GetNumOutputSlots () const override
const InputSlot & GetInputSlot (unsigned int index) const override
InputSlot & GetInputSlot (unsigned int index) override
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
OutputSlot & GetOutputSlot (unsigned int index=0) override
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
Public Attributes
std::unique_ptr< ScopedCpuTensorHandle > m_Weight
A unique pointer to store Weight values.
std::unique_ptr< ScopedCpuTensorHandle > m_Bias
A unique pointer to store Bias values.
Protected Member Functions
Convolution2dLayer (const Convolution2dDescriptor &param, const char *name)
~Convolution2dLayer ()=default
Default destructor.
ConstantTensors GetConstantTensorsByRef () override
Protected Member Functions inherited from LayerWithParameters< Convolution2dDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const Convolution2dDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< Convolution2dDescriptor >
using DescriptorType = Convolution2dDescriptor
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< Convolution2dDescriptor >
Convolution2dDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
Detailed Description
This layer represents a convolution 2d operation.
Definition at line 15 of file Convolution2dLayer.hpp.
Constructor & Destructor Documentation
Convolution2dLayer()
Convolution2dLayer (const Convolution2dDescriptor & param, const char * name) protected
Constructor to create a Convolution2dLayer.
Parameters
[in] param Convolution2dDescriptor to configure the convolution2d operation.
[in] name Optional name for the layer.
Definition at line 23 of file Convolution2dLayer.cpp.
References armnn::Convolution2d.
     : LayerWithParameters(1, 1, LayerType::Convolution2d, param, name)
 {
 }
~Convolution2dLayer()
~Convolution2dLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Implements IConnectableLayer.
Definition at line 139 of file Convolution2dLayer.cpp.
References Layer::GetName(), LayerWithParameters< Convolution2dDescriptor >::GetParameters(), Convolution2dLayer::m_Bias, Convolution2dLayer::m_Weight, and ILayerVisitor::VisitConvolution2dLayer().
 {
     ConstTensor weightsTensor(m_Weight->GetTensorInfo(), m_Weight->Map(true)) ;
     Optional<ConstTensor> optionalBiasTensor = EmptyOptional();
     if (GetParameters().m_BiasEnabled)
     {
         ConstTensor biasTensor(m_Bias->GetTensorInfo(), m_Bias->Map(true));
         optionalBiasTensor = Optional<ConstTensor>(biasTensor);
     }
     visitor.VisitConvolution2dLayer(this, GetParameters(), weightsTensor, optionalBiasTensor, GetName());
 }
Clone()
Convolution2dLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 66 of file Convolution2dLayer.cpp.
References Layer::GetName(), Convolution2dLayer::m_Bias, LayerWithParameters< Convolution2dDescriptor >::m_Param, and Convolution2dLayer::m_Weight.
 {
     auto layer = CloneBase<Convolution2dLayer>(graph, m_Param, GetName());
     layer->m_Weight = m_Weight ? std::make_unique<ScopedCpuTensorHandle>(*m_Weight) : nullptr;
     if (layer->m_Param.m_BiasEnabled)
     {
         layer->m_Bias = m_Bias ? std::make_unique<ScopedCpuTensorHandle>(*m_Bias) : nullptr;
     }
     return std::move(layer);
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the Convolution2d type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 49 of file Convolution2dLayer.cpp.
References IWorkloadFactory::CreateConvolution2d(), Convolution2dLayer::m_Bias, Convolution2dQueueDescriptor::m_Bias, Convolution2dDescriptor::m_BiasEnabled, LayerWithParameters< Convolution2dDescriptor >::m_Param, Convolution2dLayer::m_Weight, Convolution2dQueueDescriptor::m_Weight, and LayerWithParameters< Convolution2dDescriptor >::PrepInfoAndDesc().
 {
     // on this level constant data should not be released..
     BOOST_ASSERT_MSG(m_Weight != nullptr, "Convolution2dLayer: Weights data should not be null.");
     Convolution2dQueueDescriptor descriptor;
     descriptor.m_Weight = m_Weight.get();
     if (m_Param.m_BiasEnabled)
     {
         BOOST_ASSERT_MSG(m_Bias != nullptr, "Convolution2dLayer: Bias data should not be null.");
         descriptor.m_Bias = m_Bias.get();
     }
     return factory.CreateConvolution2d(descriptor, PrepInfoAndDesc(descriptor));
 }
GetConstantTensorsByRef()
Layer::ConstantTensors GetConstantTensorsByRef () override protected virtual
Retrieve the handles to the constant values stored by the layer.
Returns
A vector of the constant tensors stored by this layer.
Reimplemented from Layer.
Definition at line 134 of file Convolution2dLayer.cpp.
References Convolution2dLayer::m_Bias, and Convolution2dLayer::m_Weight.
 {
     return {m_Weight, m_Bias};
 }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 80 of file Convolution2dLayer.cpp.
References Convolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_DilationX, Convolution2dDescriptor::m_DilationY, Convolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, LayerWithParameters< Convolution2dDescriptor >::m_Param, Convolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, and armnn::NHWC.
Referenced by Convolution2dInferOutputShapeTest(), and Convolution2dLayer::ValidateTensorShapesFromInputs().
 {
     BOOST_ASSERT(inputShapes.size() == 2);
     const TensorShape& inputShape = inputShapes[0];
     const TensorShape filterShape = inputShapes[1];
     // If we support multiple batch dimensions in the future, then this assert will need to change.
     BOOST_ASSERT_MSG(inputShape.GetNumDimensions() == 4, "Convolutions will always have 4D input.");
     DataLayoutIndexed dataLayoutIndex(m_Param.m_DataLayout);
     unsigned int inWidth = inputShape[dataLayoutIndex.GetWidthIndex()];
     unsigned int inHeight = inputShape[dataLayoutIndex.GetHeightIndex()];
     unsigned int inBatchSize = inputShape[0];
     unsigned int filterWidth = filterShape[dataLayoutIndex.GetWidthIndex()];
     unsigned int dilatedFilterWidth = filterWidth + (m_Param.m_DilationX - 1) * (filterWidth - 1);
     unsigned int readWidth = (inWidth + m_Param.m_PadLeft + m_Param.m_PadRight) - dilatedFilterWidth;
     unsigned int outWidth = 1 + (readWidth / m_Param.m_StrideX);
     unsigned int filterHeight = filterShape[dataLayoutIndex.GetHeightIndex()];
     unsigned int dilatedFilterHeight = filterHeight + (m_Param.m_DilationY - 1) * (filterHeight - 1);
     unsigned int readHeight = (inHeight + m_Param.m_PadTop + m_Param.m_PadBottom) - dilatedFilterHeight;
     unsigned int outHeight = 1 + (readHeight / m_Param.m_StrideY);
     unsigned int outChannels = filterShape[0];
     unsigned int outBatchSize = inBatchSize;
     TensorShape tensorShape = m_Param.m_DataLayout == armnn::DataLayout::NHWC ?
         TensorShape( { outBatchSize, outHeight, outWidth, outChannels } ) :
         TensorShape( { outBatchSize, outChannels, outHeight, outWidth });
     return std::vector<TensorShape>({ tensorShape });
 }
SerializeLayerParameters()
void SerializeLayerParameters (ParameterStringifyFunction & fn) const override virtual
Helper to serialize the layer parameters to string. (currently used in DotSerializer and company).
Reimplemented from Layer.
Definition at line 29 of file Convolution2dLayer.cpp.
References InputSlot::GetConnection(), DataLayoutIndexed::GetHeightIndex(), Layer::GetInputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), DataLayoutIndexed::GetWidthIndex(), Convolution2dDescriptor::m_DataLayout, LayerWithParameters< Convolution2dDescriptor >::m_Param, Convolution2dLayer::m_Weight, and LayerWithParameters< Parameters >::SerializeLayerParameters().
 {
     //using DescriptorType = Parameters;
     const std::vector<TensorShape>& inputShapes =
     {
         GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape(),
         m_Weight->GetTensorInfo().GetShape()
     };
     const TensorShape filterShape = inputShapes[1];
     DataLayoutIndexed dataLayoutIndex(m_Param.m_DataLayout);
     unsigned int filterWidth = filterShape[dataLayoutIndex.GetWidthIndex()];
     unsigned int filterHeight = filterShape[dataLayoutIndex.GetHeightIndex()];
     unsigned int outChannels = filterShape[0];
     fn("OutputChannels",std::to_string(outChannels));
     fn("FilterWidth",std::to_string(filterWidth));
     fn("FilterHeight",std::to_string(filterHeight));
     LayerWithParameters<Convolution2dDescriptor>::SerializeLayerParameters(fn);
 }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of Convolution2dLayer.
Implements Layer.
Definition at line 115 of file Convolution2dLayer.cpp.
References CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), Convolution2dLayer::InferOutputShapes(), Convolution2dLayer::m_Weight, and Layer::VerifyLayerConnections().
 {
     VerifyLayerConnections(1, CHECK_LOCATION());
     // check if we m_Weight data is not nullptr
     BOOST_ASSERT_MSG(m_Weight != nullptr, "Convolution2dLayer: Weights data should not be null.");
     auto inferredShapes = InferOutputShapes({
         GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape(),
         m_Weight->GetTensorInfo().GetShape() });
     BOOST_ASSERT(inferredShapes.size() == 1);
     ConditionalThrowIfNotEqual<LayerValidationException>(
         "Convolution2dLayer: TensorShape set on OutputSlot[0] does not match the inferred shape.",
         GetOutputSlot(0).GetTensorInfo().GetShape(),
         inferredShapes[0]);
 }
Member Data Documentation
m_Bias
std::unique_ptr<ScopedCpuTensorHandle> m_Bias
A unique pointer to store Bias values.
Definition at line 22 of file Convolution2dLayer.hpp.
Referenced by Convolution2dLayer::Accept(), BOOST_AUTO_TEST_CASE(), Convolution2dLayer::Clone(), Convolution2dLayer::CreateWorkload(), and Convolution2dLayer::GetConstantTensorsByRef().
m_Weight
std::unique_ptr<ScopedCpuTensorHandle> m_Weight
A unique pointer to store Weight values.
Definition at line 20 of file Convolution2dLayer.hpp.
Referenced by Convolution2dLayer::Accept(), Network::AddConcatLayer(), BOOST_AUTO_TEST_CASE(), Convolution2dLayer::Clone(), CreateConvolution2dGraph(), Convolution2dLayer::CreateWorkload(), Convolution2dLayer::GetConstantTensorsByRef(), Convolution2dLayer::SerializeLayerParameters(), and Convolution2dLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/Convolution2dLayer.hpp
src/armnn/layers/Convolution2dLayer.cpp