ArmNN: RefPermuteWorkload< DataType > Class Template Reference
RefPermuteWorkload< DataType > Class Template Reference
#include <RefPermuteWorkload.hpp>
Public Member Functions
void Execute () const override
Public Member Functions inherited from TypedWorkload< PermuteQueueDescriptor, DataType >
TypedWorkload (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info)
Public Member Functions inherited from BaseWorkload< PermuteQueueDescriptor >
BaseWorkload (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const PermuteQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Static Public Member Functions
static const std::string & GetName ()
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< PermuteQueueDescriptor >
const PermuteQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
template<armnn::DataType DataType>
class armnn::RefPermuteWorkload< DataType >
Definition at line 16 of file RefPermuteWorkload.hpp.
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 17 of file RefPermuteWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, armnn::CpuRef, armnn::GetTensorInfo(), and armnn::Permute.
Referenced by RefPermuteWorkload< DataType >::GetName().
 {
     using T = ResolveType<DataType>;
     ARMNN_SCOPED_PROFILING_EVENT(Compute::CpuRef, GetName() + "_Execute");
     const ITensorHandle*     src      = m_Data.m_Inputs[0];
     ITensorHandle*           dst      = m_Data.m_Outputs[0];
     const PermutationVector& mappings = m_Data.m_Parameters.m_DimMappings;
     armnnUtils::Permute(GetTensorInfo(dst).GetShape(), mappings,
                         src->Map(), dst->Map(), sizeof(T));
 }
GetName()
static const std::string& GetName () inline static
Definition at line 19 of file RefPermuteWorkload.hpp.
References RefPermuteWorkload< DataType >::Execute(), and armnn::GetDataTypeName().
     {
         static const std::string name = std::string("RefPermute") + GetDataTypeName(DataType) + "Workload";
         return name;
     }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefPermuteWorkload.hpp
src/backends/reference/workloads/RefPermuteWorkload.cpp