ArmNN: FoldPadIntoConvolution2dImpl Class Reference
FoldPadIntoConvolution2dImpl Class Reference
#include <FoldPadIntoConvolution2d.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Protected Member Functions
FoldPadIntoConvolution2dImpl ()=default
~FoldPadIntoConvolution2dImpl ()=default
Detailed Description
Definition at line 15 of file FoldPadIntoConvolution2d.hpp.
Constructor & Destructor Documentation
FoldPadIntoConvolution2dImpl()
FoldPadIntoConvolution2dImpl () protected default
Referenced by FoldPadIntoConvolution2dImpl::Run().
~FoldPadIntoConvolution2dImpl()
~FoldPadIntoConvolution2dImpl () protected default
Referenced by FoldPadIntoConvolution2dImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Definition at line 19 of file FoldPadIntoConvolution2d.hpp.
References armnn::Convolution2d, FoldPadIntoConvolution2dImpl::FoldPadIntoConvolution2dImpl(), InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), Layer::GetName(), Layer::GetOutputHandler(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), OutputHandler::GetTensorInfo(), Layer::GetType(), Graph::InsertNewLayer(), Convolution2dDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, OutputSlot::MoveAllConnections(), armnn::NHWC, armnn::Pad, OutputHandler::SetTensorInfo(), and FoldPadIntoConvolution2dImpl::~FoldPadIntoConvolution2dImpl().
     {
         Layer& base = connection.GetConnectedOutputSlot()->GetOwningLayer();
         Layer& child = connection.GetOwningLayer();
         BOOST_ASSERT(base.GetType() == LayerType::Pad);
         BOOST_ASSERT(child.GetType() == LayerType::Convolution2d);
         PadLayer* padLayer = boost::polymorphic_downcast<PadLayer*>(&base);
         Convolution2dLayer* convolution2dLayer = boost::polymorphic_downcast<Convolution2dLayer*>(&child);
         OutputSlot* parentOut = base.GetInputSlot(0).GetConnectedOutputSlot();
         const TensorInfo& outInfo = child.GetOutputHandler().GetTensorInfo();
         const std::string name = std::string("folded-") + base.GetName() + std::string("-into-") + child.GetName();
         Convolution2dDescriptor descriptor = convolution2dLayer->GetParameters();
         auto padList = padLayer->GetParameters().m_PadList;
         armnn::DataLayout dataLayout = descriptor.m_DataLayout;
         // In Convolution2dDescriptor, padLeft and padRight are defined as paddings on width dimension
         // whereas padTop and padBottom - paddings on height dimension, so setting these according to data layout
         if(dataLayout == armnn::DataLayout::NHWC)
         {
             descriptor.m_PadLeft = padList[2].first;
             descriptor.m_PadRight = padList[2].second;
             descriptor.m_PadTop = padList[1].first;
             descriptor.m_PadBottom = padList[1].second;
         }
         else
         {
             descriptor.m_PadLeft = padList[3].first;
             descriptor.m_PadRight = padList[3].second;
             descriptor.m_PadTop = padList[2].first;
             descriptor.m_PadBottom = padList[2].second;
         }
         auto& newConv2dLayer = *graph.InsertNewLayer<Convolution2dLayer>(base.GetInputSlot(0),
                                                                          descriptor,
                                                                          name.c_str());
         newConv2dLayer.GetOutputHandler().SetTensorInfo(outInfo);
         // Copy weights and bias to the new convolution layer
         BOOST_ASSERT_MSG(convolution2dLayer->m_Weight != nullptr,
                          "FoldPadIntoConvolution2d: Weights data should not be null.");
         newConv2dLayer.m_Weight = std::move(convolution2dLayer->m_Weight);
         if (descriptor.m_BiasEnabled)
         {
             BOOST_ASSERT_MSG(convolution2dLayer->m_Bias != nullptr,
                              "FoldPadIntoConvolution2d: Bias data should not be null if bias is enabled.");
             newConv2dLayer.m_Bias = std::move(convolution2dLayer->m_Bias);
         }
         // Reconnects with original parent.
         newConv2dLayer.GetOutputSlot().MoveAllConnections(*parentOut);
         // Parent is now the new convolution2d layer.
         parentOut = &newConv2dLayer.GetOutputSlot();
         // Moves connections in child output to parent layer.
         // Child layer will be removed as it's left unconnected.
         // Base layer will be removed if left unconnected.
         child.GetOutputSlot().MoveAllConnections(*parentOut);
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/FoldPadIntoConvolution2d.hpp