ArmNN: MovePermuteUpImpl Class Reference
MovePermuteUpImpl Class Reference
#include <MovePermuteUp.hpp>
Public Member Functions
void Run (Graph &graph, InputSlot &connection) const
Run for every connection between a base Layer (any) and a child PermuteLayer.
Protected Member Functions
MovePermuteUpImpl ()=default
~MovePermuteUpImpl ()=default
Detailed Description
Definition at line 15 of file MovePermuteUp.hpp.
Constructor & Destructor Documentation
MovePermuteUpImpl()
MovePermuteUpImpl () protected default
Referenced by MovePermuteUpImpl::Run().
~MovePermuteUpImpl()
~MovePermuteUpImpl () protected default
Referenced by MovePermuteUpImpl::Run().
Member Function Documentation
Run()
void Run (Graph & graph, InputSlot & connection) const inline
Run for every connection between a base Layer (any) and a child PermuteLayer.
If the type of the base layer allows it, it moves the permutation to the inputs of the base layer. I.e., adds equivalent permutations before the inputs of the base layer and moves the connections in the output of the child permute layer to the output of the base layer.
Definition at line 22 of file MovePermuteUp.hpp.
References armnn::Activation, armnn::Addition, Layer::BeginInputSlots(), Layer::EndInputSlots(), armnn::FakeQuantization, armnn::Floor, InputSlot::GetConnectedOutputSlot(), Layer::GetInputSlot(), OutputSlot::GetNumConnections(), Layer::GetOutputHandler(), Layer::GetOutputSlot(), InputSlot::GetOwningLayer(), OutputSlot::GetOwningLayer(), Layer::GetType(), Graph::InsertNewLayer(), armnn::MemCopy, MovePermuteUpImpl::MovePermuteUpImpl(), armnn::Multiplication, armnnUtils::Permuted(), OutputHandler::SetTensorInfo(), and MovePermuteUpImpl::~MovePermuteUpImpl().
     {
         OutputSlot& baseOutput = *connection.GetConnectedOutputSlot();
         if (baseOutput.GetNumConnections() == 1U)
         {
             Layer& base = baseOutput.GetOwningLayer();
             if (CanMovePermuteToInputs(base))
             {
                 auto permute = boost::polymorphic_downcast<PermuteLayer*>(&connection.GetOwningLayer());
                 const PermutationVector& perm = permute->GetPermutation();
                 // Inserts an equivalent permute before every input of the base layer.
                 for (auto baseInput = base.BeginInputSlots(); baseInput != base.EndInputSlots(); ++baseInput)
                 {
                     // Inserts a new permute layer.
                     const std::string name = std::string("moved_up-") + permute->GetName();
                     PermuteLayer& permLayer = *graph.InsertNewLayer<PermuteLayer>(*baseInput, perm, name.c_str());
                     // Sets output tensor info for the new layer.
                     OutputSlot& parentOutput = *permLayer.GetInputSlot(0).GetConnectedOutputSlot();
                     const TensorInfo permOutInfo = armnnUtils::Permuted(parentOutput.GetTensorInfo(), perm);
                     permLayer.GetOutputHandler().SetTensorInfo(permOutInfo);
                 }
                 // Sets permuted output tensor info
                 const TensorInfo& childOutInfo = permute->GetOutputHandler().GetTensorInfo();
                 base.GetOutputHandler().SetTensorInfo(childOutInfo);
                 // Bypasses permute. It will be removed as it's left unconnected.
                 permute->GetOutputSlot().MoveAllConnections(base.GetOutputSlot());
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/optimizations/MovePermuteUp.hpp