ArmNN: SpaceToBatchNdLayer Class Reference
SpaceToBatchNdLayer Class Reference
This layer represents a SpaceToBatchNd operation.
#include <SpaceToBatchNdLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
SpaceToBatchNdLayer * Clone (Graph &graph) const override
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
void ValidateTensorShapesFromInputs () override
void Accept (ILayerVisitor &visitor) const override
Public Member Functions inherited from LayerWithParameters< SpaceToBatchNdDescriptor >
const SpaceToBatchNdDescriptor & GetParameters () const
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
unsigned int GetNumInputSlots () const override
unsigned int GetNumOutputSlots () const override
const InputSlot & GetInputSlot (unsigned int index) const override
InputSlot & GetInputSlot (unsigned int index) override
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
OutputSlot & GetOutputSlot (unsigned int index=0) override
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
Protected Member Functions
SpaceToBatchNdLayer (const SpaceToBatchNdDescriptor param, const char *name)
~SpaceToBatchNdLayer ()=default
Default destructor.
Protected Member Functions inherited from LayerWithParameters< SpaceToBatchNdDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const SpaceToBatchNdDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef ()
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< SpaceToBatchNdDescriptor >
using DescriptorType = SpaceToBatchNdDescriptor
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< SpaceToBatchNdDescriptor >
SpaceToBatchNdDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
Detailed Description
This layer represents a SpaceToBatchNd operation.
Definition at line 14 of file SpaceToBatchNdLayer.hpp.
Constructor & Destructor Documentation
SpaceToBatchNdLayer()
SpaceToBatchNdLayer (const SpaceToBatchNdDescriptor param, const char * name) protected
Constructor to create a SpaceToBatchNdLayer.
Parameters
[in] param SpaceToBatchNdDescriptor to configure the SpaceToBatchNdLayer operation.
[in] name Optional name for the layer.
Definition at line 23 of file SpaceToBatchNdLayer.cpp.
References armnn::SpaceToBatchNd().
     : LayerWithParameters(1, 1, LayerType::SpaceToBatchNd, param, name)
 {}
~SpaceToBatchNdLayer()
~SpaceToBatchNdLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Implements IConnectableLayer.
Definition at line 84 of file SpaceToBatchNdLayer.cpp.
References Layer::GetName(), LayerWithParameters< SpaceToBatchNdDescriptor >::GetParameters(), and ILayerVisitor::VisitSpaceToBatchNdLayer().
 {
     visitor.VisitSpaceToBatchNdLayer(this, GetParameters(), GetName());
 }
Clone()
SpaceToBatchNdLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 36 of file SpaceToBatchNdLayer.cpp.
References Layer::GetName(), and LayerWithParameters< SpaceToBatchNdDescriptor >::m_Param.
 {
     boost::ignore_unused(graph);
     return CloneBase<SpaceToBatchNdLayer>(graph, m_Param, GetName());
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the SpaceToBatchNd type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 27 of file SpaceToBatchNdLayer.cpp.
References IWorkloadFactory::CreateSpaceToBatchNd(), SpaceToBatchNdDescriptor::m_BlockShape, SpaceToBatchNdDescriptor::m_PadList, LayerWithParameters< SpaceToBatchNdDescriptor >::m_Param, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and LayerWithParameters< SpaceToBatchNdDescriptor >::PrepInfoAndDesc().
 {
    SpaceToBatchNdQueueDescriptor descriptor;
     descriptor.m_Parameters.m_BlockShape = m_Param.m_BlockShape;
     descriptor.m_Parameters.m_PadList = m_Param.m_PadList;
     return factory.CreateSpaceToBatchNd(descriptor, PrepInfoAndDesc(descriptor));
 }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 42 of file SpaceToBatchNdLayer.cpp.
References DataLayoutIndexed::GetHeightIndex(), DataLayoutIndexed::GetWidthIndex(), SpaceToBatchNdDescriptor::m_BlockShape, SpaceToBatchNdDescriptor::m_DataLayout, SpaceToBatchNdDescriptor::m_PadList, and LayerWithParameters< SpaceToBatchNdDescriptor >::m_Param.
Referenced by SpaceToBatchNdLayer::ValidateTensorShapesFromInputs().
 {
     BOOST_ASSERT(inputShapes.size() == 1);
     TensorShape inputShape = inputShapes[0];
     TensorShape outputShape(inputShape);
     outputShape[0] = inputShape[0] * std::accumulate(m_Param.m_BlockShape.begin(),
                                                      m_Param.m_BlockShape.end(),
                                                      1U,
                                                      std::multiplies<>());
     DataLayoutIndexed dimensionIndices = m_Param.m_DataLayout;
     unsigned int heightIndex = dimensionIndices.GetHeightIndex();
     unsigned int widthIndex = dimensionIndices.GetWidthIndex();
     std::pair<unsigned int, unsigned int> heightPad = m_Param.m_PadList[0];
     std::pair<unsigned int, unsigned int> widthPad = m_Param.m_PadList[1];
     outputShape[heightIndex] =
         (inputShape[heightIndex] + heightPad.first + heightPad.second) / m_Param.m_BlockShape[0];
     outputShape[widthIndex] =
         (inputShape[widthIndex] + widthPad.first + widthPad.second) / m_Param.m_BlockShape[1];
     return std::vector<TensorShape>({ outputShape });
 }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of SpaceToBatchNdLayer.
Implements Layer.
Definition at line 69 of file SpaceToBatchNdLayer.cpp.
References CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), SpaceToBatchNdLayer::InferOutputShapes(), and Layer::VerifyLayerConnections().
 {
     VerifyLayerConnections(1, CHECK_LOCATION());
     std::vector<TensorShape> inferredShapes = InferOutputShapes({
         GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape() });
     BOOST_ASSERT(inferredShapes.size() == 1);
     ConditionalThrowIfNotEqual<LayerValidationException>(
         "SpaceToBatchNdLayer: TensorShape set on OutputSlot[0] does not match the inferred shape.",
         GetOutputSlot(0).GetTensorInfo().GetShape(),
         inferredShapes[0]);
 }
The documentation for this class was generated from the following files:
src/armnn/layers/SpaceToBatchNdLayer.hpp
src/armnn/layers/SpaceToBatchNdLayer.cpp