ArmNN: GatordMockService Class Reference
GatordMockService Class Reference
A class that implements a Mock Gatord server.
#include <GatordMockService.hpp>
Public Member Functions
GatordMockService (armnn::profiling::CommandHandlerRegistry &registry, bool echoPackets)
~GatordMockService ()
bool OpenListeningSocket (std::string udsNamespace)
Establish the Unix domain socket and set it to listen for connections.
armnnUtils::Sockets::Socket BlockForOneClient ()
Block waiting to accept one client to connect to the UDS.
bool WaitForStreamMetaData ()
Once the connection is open wait to receive the stream meta data packet from the client.
void SendConnectionAck ()
Send a connection acknowledged packet back to the client.
void SendRequestCounterDir ()
Send a request counter directory packet back to the client.
bool LaunchReceivingThread ()
Start the thread that will receive all packets and print them nicely to stdout.
uint32_t GetPacketsReceivedCount ()
Return the total number of periodic counter capture packets received since the receive thread started.
void WaitForReceivingThread ()
This is a placeholder method to prevent main exiting.
bool ReceiveThreadRunning ()
void SendPeriodicCounterSelectionList (uint32_t period, std::vector< uint16_t > counters)
Send the counter list to ArmNN.
void WaitCommand (uint32_t timeout)
Execute the WAIT command from the comamnd file.
uint32_t GetStreamMetadataVersion ()
uint32_t GetStreamMetadataMaxDataLen ()
uint32_t GetStreamMetadataPid ()
Detailed Description
A class that implements a Mock Gatord server.
It will listen on a specified Unix domain socket (UDS) namespace for client connections. It will then allow opertaions to manage coutners while receiving counter data.
Definition at line 37 of file GatordMockService.hpp.
Constructor & Destructor Documentation
GatordMockService()
GatordMockService (armnn::profiling::CommandHandlerRegistry & registry, bool echoPackets) inline
Parameters
registry reference to a command handler registry.
echoPackets if true the raw packets will be printed to stdout.
Definition at line 42 of file GatordMockService.hpp.
         : m_HandlerRegistry(registry)
         , m_EchoPackets(echoPackets)
         , m_CloseReceivingThread(false)
     {
         m_PacketsReceivedCount.store(0, std::memory_order_relaxed);
     }
~GatordMockService()
~GatordMockService () inline
Definition at line 50 of file GatordMockService.hpp.
References armnnUtils::Sockets::Close().
     {
         // We have set SOCK_CLOEXEC on these sockets but we'll close them to be good citizens.
         armnnUtils::Sockets::Close(m_ClientConnection);
         armnnUtils::Sockets::Close(m_ListeningSocket);
     }
Member Function Documentation
BlockForOneClient()
Sockets::Socket BlockForOneClient ()
Block waiting to accept one client to connect to the UDS.
Returns
the file descriptor of the client connection.
Definition at line 58 of file GatordMockService.cpp.
References armnnUtils::Sockets::Accept().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     m_ClientConnection = Sockets::Accept(m_ListeningSocket, nullptr, nullptr, SOCK_CLOEXEC);
     if (-1 == m_ClientConnection)
     {
         std::cerr << ": Failure when waiting for a client connection: " << strerror(errno) << std::endl;
         return -1;
     }
     return m_ClientConnection;
 }
GetPacketsReceivedCount()
uint32_t GetPacketsReceivedCount () inline
Return the total number of periodic counter capture packets received since the receive thread started.
Returns
number of periodic counter capture packets received.
Definition at line 82 of file GatordMockService.hpp.
     {
         return m_PacketsReceivedCount.load(std::memory_order_acquire);
     }
GetStreamMetadataMaxDataLen()
uint32_t GetStreamMetadataMaxDataLen () inline
Definition at line 108 of file GatordMockService.hpp.
     {
         return m_StreamMetaDataMaxDataLen;
     }
GetStreamMetadataPid()
uint32_t GetStreamMetadataPid () inline
Definition at line 113 of file GatordMockService.hpp.
     {
         return m_StreamMetaDataPid;
     }
GetStreamMetadataVersion()
uint32_t GetStreamMetadataVersion () inline
Definition at line 103 of file GatordMockService.hpp.
     {
         return m_StreamMetaDataVersion;
     }
LaunchReceivingThread()
bool LaunchReceivingThread ()
Start the thread that will receive all packets and print them nicely to stdout.
Definition at line 149 of file GatordMockService.cpp.
References armnnUtils::Sockets::Close(), and armnnUtils::Sockets::SetNonBlocking().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (m_EchoPackets)
     {
         std::cout << "Launching receiving thread." << std::endl;
     }
     // At this point we want to make the socket non blocking.
     if (!Sockets::SetNonBlocking(m_ClientConnection))
     {
         Sockets::Close(m_ClientConnection);
         std::cerr << "Failed to set socket as non blocking: " << strerror(errno) << std::endl;
         return false;
     }
     m_ListeningThread = std::thread(&GatordMockService::ReceiveLoop, this, std::ref(*this));
     return true;
 }
OpenListeningSocket()
bool OpenListeningSocket (std::string udsNamespace)
Establish the Unix domain socket and set it to listen for connections.
Parameters
udsNamespace the namespace (socket address) associated with the listener.
Returns
true only if the socket has been correctly setup.
Definition at line 27 of file GatordMockService.cpp.
References armnnUtils::Sockets::Initialize().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     Sockets::Initialize();
     m_ListeningSocket = socket(PF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
     if (-1 == m_ListeningSocket)
     {
         std::cerr << ": Socket construction failed: " << strerror(errno) << std::endl;
         return false;
     }
     sockaddr_un udsAddress;
     memset(&udsAddress, 0, sizeof(sockaddr_un));
     // We've set the first element of sun_path to be 0, skip over it and copy the namespace after it.
     memcpy(udsAddress.sun_path + 1, udsNamespace.c_str(), strlen(udsNamespace.c_str()));
     udsAddress.sun_family = AF_UNIX;
     // Bind the socket to the UDS namespace.
     if (-1 == bind(m_ListeningSocket, reinterpret_cast<const sockaddr*>(&udsAddress), sizeof(sockaddr_un)))
     {
         std::cerr << ": Binding on socket failed: " << strerror(errno) << std::endl;
         return false;
     }
     // Listen for 1 connection.
     if (-1 == listen(m_ListeningSocket, 1))
     {
         std::cerr << ": Listen call on socket failed: " << strerror(errno) << std::endl;
         return false;
     }
     return true;
 }
ReceiveThreadRunning()
bool ReceiveThreadRunning () inline
Definition at line 92 of file GatordMockService.hpp.
Referenced by CommandFileParser::ParseFile(), and GatordMockService::WaitCommand().
     {
         return !m_CloseReceivingThread.load();
     }
SendConnectionAck()
void SendConnectionAck ()
Send a connection acknowledged packet back to the client.
Definition at line 129 of file GatordMockService.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (m_EchoPackets)
     {
         std::cout << "Sending connection acknowledgement." << std::endl;
     }
     // The connection ack packet is an empty data packet with packetId == 1.
     SendPacket(0, 1, nullptr, 0);
 }
SendPeriodicCounterSelectionList()
void SendPeriodicCounterSelectionList (uint32_t period, std::vector< uint16_t > counters)
Send the counter list to ArmNN.
Definition at line 181 of file GatordMockService.cpp.
References armnn::profiling::WriteUint16(), and armnn::profiling::WriteUint32().
Referenced by CommandFileParser::ParseFile().
 {
     // The packet body consists of a UINT32 representing the period following by zero or more
     // UINT16's representing counter UID's. If the list is empty it implies all counters are to
     // be disabled.
     if (m_EchoPackets)
     {
         std::cout << "SendPeriodicCounterSelectionList: Period=" << std::dec << period << "uSec" << std::endl;
         std::cout << "List length=" << counters.size() << std::endl;
         ;
     }
     // Start by calculating the length of the packet body in bytes. This will be at least 4.
     uint32_t dataLength = static_cast<uint32_t>(4 + (counters.size() * 2));
     std::unique_ptr<unsigned char[]> uniqueData = std::make_unique<unsigned char[]>(dataLength);
     unsigned char* data                         = reinterpret_cast<unsigned char*>(uniqueData.get());
     uint32_t offset = 0;
     profiling::WriteUint32(data, offset, period);
     offset += 4;
     for (std::vector<uint16_t>::iterator it = counters.begin(); it != counters.end(); ++it)
     {
         profiling::WriteUint16(data, offset, *it);
         offset += 2;
     }
     // Send the packet.
     SendPacket(0, 4, data, dataLength);
     // There will be an echo response packet sitting in the receive thread. PeriodicCounterSelectionResponseHandler
     // should deal with it.
 }
SendRequestCounterDir()
void SendRequestCounterDir ()
Send a request counter directory packet back to the client.
Definition at line 139 of file GatordMockService.cpp.
Referenced by CommandFileParser::ParseFile().
 {
     if (m_EchoPackets)
     {
         std::cout << "Sending connection acknowledgement." << std::endl;
     }
     // The connection ack packet is an empty data packet with packetId == 1.
     SendPacket(0, 3, nullptr, 0);
 }
WaitCommand()
void WaitCommand (uint32_t timeout)
Execute the WAIT command from the comamnd file.
Definition at line 214 of file GatordMockService.cpp.
References armnn::gatordmock::BeWire, Version::GetEncodedValue(), Packet::GetLength(), Packet::GetPacketFamily(), Packet::GetPacketId(), armnnUtils::Sockets::Ioctl(), armnnUtils::Sockets::Poll(), armnnUtils::Sockets::Read(), armnn::gatordmock::ReceivedData, armnn::gatordmock::ReceivedHeader, GatordMockService::ReceiveThreadRunning(), PacketVersionResolver::ResolvePacketVersion(), armnn::gatordmock::Sending, Exception::what(), and armnnUtils::Sockets::Write().
Referenced by CommandFileParser::ParseFile().
 {
     // Wait for a maximum of timeout microseconds or if the receive thread has closed.
     // There is a certain level of rounding involved in this timing.
     uint32_t iterations = timeout / 1000;
     std::cout << std::dec << "Wait command with timeout of " << timeout << " iterations =  " << iterations << std::endl;
     uint32_t count = 0;
     while ((this->ReceiveThreadRunning() && (count < iterations)))
     {
         std::this_thread::sleep_for(std::chrono::microseconds(1000));
         ++count;
     }
     if (m_EchoPackets)
     {
         std::cout << std::dec << "Wait command with timeout of " << timeout << " microseconds completed. " << std::endl;
     }
 }
WaitForReceivingThread()
void WaitForReceivingThread ()
This is a placeholder method to prevent main exiting.
It can be removed once the command handling code is added.
Definition at line 166 of file GatordMockService.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     // The receiving thread may already have died.
     if (m_CloseReceivingThread != true)
     {
         m_CloseReceivingThread.store(true);
     }
     // Check that the receiving thread is running
     if (m_ListeningThread.joinable())
     {
         // Wait for the receiving thread to complete operations
         m_ListeningThread.join();
     }
 }
WaitForStreamMetaData()
bool WaitForStreamMetaData ()
Once the connection is open wait to receive the stream meta data packet from the client.
Reading this packet differs from others as we need to determine endianness.
Returns
true only if a valid stream met data packet has been received.
Definition at line 69 of file GatordMockService.cpp.
References armnn::gatordmock::BeWire, armnn::gatordmock::LeWire, armnnUtils::Sockets::Read(), armnn::gatordmock::ReceivedData, and armnn::gatordmock::ReceivedHeader.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (m_EchoPackets)
     {
         std::cout << "Waiting for stream meta data..." << std::endl;
     }
     // The start of the stream metadata is 2x32bit words, 0 and packet length.
     uint8_t header[8];
     if (!ReadFromSocket(header, 8))
     {
         return false;
     }
     EchoPacket(PacketDirection::ReceivedHeader, header, 8);
     // The first word, stream_metadata_identifer, should always be 0.
     if (ToUint32(&header[0], TargetEndianness::BeWire) != 0)
     {
         std::cerr << ": Protocol error. The stream_metadata_identifer was not 0." << std::endl;
         return false;
     }
     uint8_t pipeMagic[4];
     if (!ReadFromSocket(pipeMagic, 4))
     {
         return false;
     }
     EchoPacket(PacketDirection::ReceivedData, pipeMagic, 4);
     // Before we interpret the length we need to read the pipe_magic word to determine endianness.
     if (ToUint32(&pipeMagic[0], TargetEndianness::BeWire) == PIPE_MAGIC)
     {
         m_Endianness = TargetEndianness::BeWire;
     }
     else if (ToUint32(&pipeMagic[0], TargetEndianness::LeWire) == PIPE_MAGIC)
     {
         m_Endianness = TargetEndianness::LeWire;
     }
     else
     {
         std::cerr << ": Protocol read error. Unable to read PIPE_MAGIC value." << std::endl;
         return false;
     }
     // Now we know the endianness we can get the length from the header.
     // Remember we already read the pipe magic 4 bytes.
     uint32_t metaDataLength = ToUint32(&header[4], m_Endianness) - 4;
     // Read the entire packet.
     std::vector<uint8_t> packetData(metaDataLength);
     if (metaDataLength !=
         boost::numeric_cast<uint32_t>(Sockets::Read(m_ClientConnection, packetData.data(), metaDataLength)))
     {
         std::cerr << ": Protocol read error. Data length mismatch." << std::endl;
         return false;
     }
     EchoPacket(PacketDirection::ReceivedData, packetData.data(), metaDataLength);
     m_StreamMetaDataVersion    = ToUint32(&packetData[0], m_Endianness);
     m_StreamMetaDataMaxDataLen = ToUint32(&packetData[4], m_Endianness);
     m_StreamMetaDataPid        = ToUint32(&packetData[8], m_Endianness);
     return true;
 }
The documentation for this class was generated from the following files:
tests/profiling/gatordmock/GatordMockService.hpp
tests/profiling/gatordmock/GatordMockService.cpp