ArmNN: ConstantLayer Class Reference
ConstantLayer Class Reference
A layer that the constant data can be bound to.
#include <ConstantLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
ConstantLayer * Clone (Graph &graph) const override
void ValidateTensorShapesFromInputs () override
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
void ReleaseConstantData () override
Free up the constant source data stored by the layer.
void Accept (ILayerVisitor &visitor) const override
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void SerializeLayerParameters (ParameterStringifyFunction &fn) const
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
unsigned int GetNumInputSlots () const override
unsigned int GetNumOutputSlots () const override
const InputSlot & GetInputSlot (unsigned int index) const override
InputSlot & GetInputSlot (unsigned int index) override
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
OutputSlot & GetOutputSlot (unsigned int index=0) override
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
Public Attributes
std::unique_ptr< ScopedCpuTensorHandle > m_LayerOutput
Protected Member Functions
ConstantLayer (const char *name)
~ConstantLayer ()=default
Default destructor.
ConstantTensors GetConstantTensorsByRef () override
Retrieve the handles to the constant values stored by the layer.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
Detailed Description
A layer that the constant data can be bound to.
Definition at line 15 of file ConstantLayer.hpp.
Constructor & Destructor Documentation
ConstantLayer()
ConstantLayer (const char * name) protected
Constructor to create a ConstantLayer.
Parameters
[in] name Optional name for the layer.
Definition at line 16 of file ConstantLayer.cpp.
References armnn::Constant.
     : Layer(0, 1, LayerType::Constant, name)
 {
 }
~ConstantLayer()
~ConstantLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Implements IConnectableLayer.
Definition at line 53 of file ConstantLayer.cpp.
References Layer::GetName(), ConstantLayer::m_LayerOutput, and ILayerVisitor::VisitConstantLayer().
Referenced by ConstantLayer::ReleaseConstantData().
 {
     ConstTensor layerOutputTensor(m_LayerOutput->GetTensorInfo(), m_LayerOutput->Map(true)) ;
     visitor.VisitConstantLayer(this, layerOutputTensor, GetName());
 }
Clone()
ConstantLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 28 of file ConstantLayer.cpp.
References Layer::GetName(), and ConstantLayer::m_LayerOutput.
 {
     // Cloned layers share the same layer output object.
     auto layer = CloneBase<ConstantLayer>(graph, GetName());
     layer->m_LayerOutput = m_LayerOutput ? std::make_unique<ScopedCpuTensorHandle>(*m_LayerOutput) : nullptr;
     return std::move(layer);
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the Constant type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 21 of file ConstantLayer.cpp.
References IWorkloadFactory::CreateConstant(), ConstantLayer::m_LayerOutput, ConstantQueueDescriptor::m_LayerOutput, and Layer::PrepInfoAndDesc().
 {
     ConstantQueueDescriptor descriptor;
     descriptor.m_LayerOutput = m_LayerOutput.get();
     return factory.CreateConstant(descriptor, PrepInfoAndDesc(descriptor));
 }
GetConstantTensorsByRef()
ConstantTensors GetConstantTensorsByRef () inline override protected virtual
Retrieve the handles to the constant values stored by the layer.
Reimplemented from Layer.
Definition at line 54 of file ConstantLayer.hpp.
 { return {m_LayerOutput}; }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
a vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 38 of file ConstantLayer.cpp.
 {
     return std::vector<TensorShape>({  inputShapes[0] });
 }
ReleaseConstantData()
void ReleaseConstantData () inline override virtual
Free up the constant source data stored by the layer.
Reimplemented from Layer.
Definition at line 39 of file ConstantLayer.hpp.
References ConstantLayer::Accept().
 {}
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of ConstantLayer
Implements Layer.
Definition at line 43 of file ConstantLayer.cpp.
References Layer::GetOutputSlot(), TensorInfo::GetShape(), OutputSlot::GetTensorInfo(), and ConstantLayer::m_LayerOutput.
 {
     // Get the output shape from the value of the constant layer.
     TensorShape const& outShape = m_LayerOutput->GetTensorInfo().GetShape();
     ConditionalThrowIfNotEqual<LayerValidationException>(
         "ConstantLayer: TensorShape set on OutputSlot[0] does not match the inferred shape.",
         GetOutputSlot(0).GetTensorInfo().GetShape(),
         outShape);
 }
Member Data Documentation
m_LayerOutput
std::unique_ptr<ScopedCpuTensorHandle> m_LayerOutput
Definition at line 43 of file ConstantLayer.hpp.
Referenced by ConstantLayer::Accept(), Network::AddConstantLayer(), ConstantLayer::Clone(), ConstantLayer::CreateWorkload(), and ConstantLayer::ValidateTensorShapesFromInputs().
The documentation for this class was generated from the following files:
src/armnn/layers/ConstantLayer.hpp
src/armnn/layers/ConstantLayer.cpp