ArmNN: Packet Class Reference
Packet Class Reference
#include <Packet.hpp>
Public Member Functions
Packet ()
Packet (uint32_t header)
Packet (uint32_t header, uint32_t length, std::unique_ptr< unsigned char[]> &data)
Packet (Packet &&other)
~Packet ()=default
Packet (const Packet &other)=delete
Packet & operator= (const Packet &)=delete
Packet & operator= (Packet &&)=default
uint32_t GetHeader () const
uint32_t GetPacketFamily () const
uint32_t GetPacketId () const
uint32_t GetPacketClass () const
uint32_t GetPacketType () const
uint32_t GetLength () const
const unsigned char * GetData () const
bool IsEmpty ()
Detailed Description
Definition at line 18 of file Packet.hpp.
Constructor & Destructor Documentation
Packet() [1/5]
Packet () inline
Definition at line 21 of file Packet.hpp.
Referenced by Packet::Packet().
         : m_Header(0)
         , m_Length(0)
         , m_Data(nullptr)
     {}
Packet() [2/5]
Packet (uint32_t header) inline
Definition at line 27 of file Packet.hpp.
         : m_Header(header)
         , m_Length(0)
         , m_Data(nullptr)
     {
         m_PacketId = ((header >> 16) & 1023);
         m_PacketFamily = (header >> 26);
     }
Packet() [3/5]
Packet (uint32_t header, uint32_t length, std::unique_ptr< unsigned char[]> & data) inline
Definition at line 36 of file Packet.hpp.
         : m_Header(header)
         , m_Length(length)
         , m_Data(std::move(data))
     {
         m_PacketId = ((header >> 16) & 1023);
         m_PacketFamily = (header >> 26);
         if (length == 0 && m_Data != nullptr)
         {
             throw armnn::InvalidArgumentException("Data should be null when length is zero");
         }
     }
Packet() [4/5]
Packet (Packet && other) inline
Definition at line 50 of file Packet.hpp.
References Packet::operator=(), Packet::Packet(), and Packet::~Packet().
         : m_Header(other.m_Header)
         , m_PacketFamily(other.m_PacketFamily)
         , m_PacketId(other.m_PacketId)
         , m_Length(other.m_Length)
         , m_Data(std::move(other.m_Data))
     {
         other.m_Header = 0;
         other.m_PacketFamily = 0;
         other.m_PacketId = 0;
         other.m_Length = 0;
     }
~Packet()
~Packet () default
Referenced by Packet::Packet().
Packet() [5/5]
Packet (const Packet & other) delete
Member Function Documentation
GetData()
const unsigned char* GetData () const inline
Definition at line 75 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), PeriodicCounterSelectionResponseHandler::operator()(), ProfilingConnectionDumpToFileDecorator::ReadPacket(), and armnn::gatordmock::ReadString().
 { return m_Data.get();    }
GetHeader()
uint32_t GetHeader () const inline
Definition at line 69 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingConnectionDumpToFileDecorator::ReadPacket().
 { return m_Header;        }
GetLength()
uint32_t GetLength () const inline
Definition at line 74 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), PeriodicCounterSelectionResponseHandler::operator()(), ProfilingConnectionDumpToFileDecorator::ReadPacket(), armnn::gatordmock::ReadString(), and GatordMockService::WaitCommand().
 { return m_Length;        }
GetPacketClass()
uint32_t GetPacketClass () const inline
Definition at line 72 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_PacketId >> 3; }
GetPacketFamily()
uint32_t GetPacketFamily () const inline
Definition at line 70 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), PerJobCounterSelectionCommandHandler::operator()(), ConnectionAcknowledgedCommandHandler::operator()(), RequestCounterDirectoryCommandHandler::operator()(), PeriodicCounterSelectionCommandHandler::operator()(), CommandHandler::Stop(), and GatordMockService::WaitCommand().
 { return m_PacketFamily;  }
GetPacketId()
uint32_t GetPacketId () const inline
Definition at line 71 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), PerJobCounterSelectionCommandHandler::operator()(), ConnectionAcknowledgedCommandHandler::operator()(), RequestCounterDirectoryCommandHandler::operator()(), PeriodicCounterSelectionCommandHandler::operator()(), CommandHandler::Stop(), and GatordMockService::WaitCommand().
 { return m_PacketId;      }
GetPacketType()
uint32_t GetPacketType () const inline
Definition at line 73 of file Packet.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
 { return m_PacketId & 7;  }
IsEmpty()
bool IsEmpty () inline
Definition at line 77 of file Packet.hpp.
Referenced by CommandHandler::Stop().
 { return m_Header == 0 && m_Length == 0; }
operator=() [1/2]
Packet& operator= (const Packet &) delete
Referenced by Packet::Packet().
operator=() [2/2]
Packet& operator= (Packet &&) default
The documentation for this class was generated from the following file:
src/profiling/Packet.hpp