ArmNN: CommandHandlerKey Class Reference
CommandHandlerKey Class Reference
#include <CommandHandlerKey.hpp>
Public Member Functions
CommandHandlerKey (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
bool operator< (const CommandHandlerKey &rhs) const
bool operator> (const CommandHandlerKey &rhs) const
bool operator<= (const CommandHandlerKey &rhs) const
bool operator>= (const CommandHandlerKey &rhs) const
bool operator== (const CommandHandlerKey &rhs) const
bool operator!= (const CommandHandlerKey &rhs) const
Detailed Description
Definition at line 16 of file CommandHandlerKey.hpp.
Constructor & Destructor Documentation
CommandHandlerKey()
CommandHandlerKey (uint32_t familyId, uint32_t packetId, uint32_t version) inline
Definition at line 19 of file CommandHandlerKey.hpp.
References CommandHandlerKey::GetFamilyId(), CommandHandlerKey::GetPacketId(), CommandHandlerKey::GetVersion(), CommandHandlerKey::operator!=(), CommandHandlerKey::operator<(), CommandHandlerKey::operator<=(), CommandHandlerKey::operator==(), CommandHandlerKey::operator>(), and CommandHandlerKey::operator>=().
     : m_FamilyId(familyId), m_PacketId(packetId), m_Version(version) {};
Member Function Documentation
GetFamilyId()
uint32_t GetFamilyId () const
Definition at line 14 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     return m_FamilyId;
 }
GetPacketId()
uint32_t GetPacketId () const
Definition at line 19 of file CommandHandlerKey.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandlerKey::CommandHandlerKey(), and CommandHandlerHash::operator()().
 {
     return m_PacketId;
 }
GetVersion()
uint32_t GetVersion () const
Definition at line 24 of file CommandHandlerKey.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), CommandHandlerKey::CommandHandlerKey(), and CommandHandlerHash::operator()().
 {
     return m_Version;
 }
operator!=()
bool operator!= (const CommandHandlerKey & rhs) const
Definition at line 70 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     return !(*this == rhs);
 }
operator<()
bool operator< (const CommandHandlerKey & rhs) const
Definition at line 29 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     bool result = true;
     if (m_FamilyId == rhs.m_FamilyId)
     {
         if (m_PacketId == rhs.m_PacketId)
         {
             result = m_Version < rhs.m_Version;
         }
         else if (m_PacketId > rhs.m_PacketId)
         {
             result = false;
         }
     }
     else if (m_FamilyId > rhs.m_FamilyId)
     {
         result = false;
     }
     return result;
 }
operator<=()
bool operator<= (const CommandHandlerKey & rhs) const
Definition at line 55 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     return !(*this > rhs);
 }
operator==()
bool operator== (const CommandHandlerKey & rhs) const
Definition at line 65 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     return m_FamilyId == rhs.m_FamilyId && m_PacketId == rhs.m_PacketId && m_Version == rhs.m_Version;
 }
operator>()
bool operator> (const CommandHandlerKey & rhs) const
Definition at line 50 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     return rhs < *this;
 }
operator>=()
bool operator>= (const CommandHandlerKey & rhs) const
Definition at line 60 of file CommandHandlerKey.cpp.
Referenced by CommandHandlerKey::CommandHandlerKey().
 {
     return !(*this < rhs);
 }
The documentation for this class was generated from the following files:
src/profiling/CommandHandlerKey.hpp
src/profiling/CommandHandlerKey.cpp