ArmNN: TfParser Class Reference
TfParser Class Reference
#include <TfParser.hpp>
Public Member Functions
virtual armnn::INetworkPtr CreateNetworkFromTextFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs) override
Creates the network from a protobuf text file on the disk.
virtual armnn::INetworkPtr CreateNetworkFromBinaryFile (const char *graphFile, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs) override
Creates the network from a protobuf binary file on the disk.
virtual armnn::INetworkPtr CreateNetworkFromString (const char *protoText, const std::map< std::string, armnn::TensorShape > &inputShapes, const std::vector< std::string > &requestedOutputs) override
Creates the network directly from protobuf text in a string. Useful for debugging/testing.
virtual BindingPointInfo GetNetworkInputBindingInfo (const std::string &name) const override
Retrieves binding info (layer id and tensor info) for the network input identified by the given layer name.
virtual BindingPointInfo GetNetworkOutputBindingInfo (const std::string &name) const override
Retrieves binding info (layer id and tensor info) for the network output identified by the given layer name.
TfParser ()
Friends
template<typename T >
class ParsedConstTfOperation
class ParsedMatMulTfOperation
class ParsedMulTfOperation
Additional Inherited Members
Static Public Member Functions inherited from ITfParser
static ITfParser * CreateRaw ()
static ITfParserPtr Create ()
static void Destroy (ITfParser *parser)
Protected Member Functions inherited from ITfParser
virtual ~ITfParser ()
Detailed Description
Definition at line 64 of file TfParser.hpp.
Constructor & Destructor Documentation
TfParser()
TfParser ()
Definition at line 513 of file TfParser.cpp.
References INetwork::AddAdditionLayer(), CHECK_LOCATION, IOutputSlot::Connect(), IConnectableLayer::GetInputSlot(), TensorShape::GetNumDimensions(), TensorInfo::GetNumDimensions(), TensorInfo::GetNumElements(), IConnectableLayer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), WithOutputTensorIndex< T >::m_Index, WithOutputTensorIndex< T >::m_IndexedValue, TfParser::ParsedConstTfOperation, TensorInfo::SetShape(), and IOutputSlot::SetTensorInfo().
     : m_Network(nullptr, nullptr)
 {
 }
Member Function Documentation
CreateNetworkFromBinaryFile()
INetworkPtr CreateNetworkFromBinaryFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs) override virtual
Creates the network from a protobuf binary file on the disk.
Implements ITfParser.
Definition at line 3566 of file TfParser.cpp.
References CHECK_LOCATION.
 {
     FILE* fd = fopen(graphFile, "rb");
     if (fd == nullptr)
     {
         throw FileNotFoundException(
             boost::str(
                 boost::format(
                     "Graph file %1% failed to open %2%")
                     % graphFile
                     % CHECK_LOCATION().AsString()));
     }
     // Parses the file into a message.
     tensorflow::GraphDef graphDef;
     google::protobuf::io::FileInputStream  inStream(fileno(fd));
     google::protobuf::io::CodedInputStream codedStream(&inStream);
     codedStream.SetTotalBytesLimit(INT_MAX, INT_MAX);
     bool success = graphDef.ParseFromCodedStream(&codedStream);
     fclose(fd);
     if (!success)
     {
         throw ParseException(
             boost::str(
                 boost::format(
                     "Failed to parse protobuf file %1% %2%")
                     % graphFile
                     % CHECK_LOCATION().AsString()));
     }
     return CreateNetworkFromGraphDef(graphDef, inputShapes, requestedOutputs);
 }
CreateNetworkFromString()
INetworkPtr CreateNetworkFromString (const char * protoText, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs) override virtual
Creates the network directly from protobuf text in a string. Useful for debugging/testing.
Implements ITfParser.
Definition at line 3546 of file TfParser.cpp.
References CHECK_LOCATION.
 {
     // Parses the string into a message.
     tensorflow::GraphDef graphDef;
     bool success = google::protobuf::TextFormat::ParseFromString(protoText, &graphDef);
     if (!success)
     {
         throw ParseException(
             boost::str(
                 boost::format(
                     "Failed to parse graph file %1%")
                     % CHECK_LOCATION().AsString()));
     }
     return CreateNetworkFromGraphDef(graphDef, inputShapes, requestedOutputs);
 }
CreateNetworkFromTextFile()
INetworkPtr CreateNetworkFromTextFile (const char * graphFile, const std::map< std::string, armnn::TensorShape > & inputShapes, const std::vector< std::string > & requestedOutputs) override virtual
Creates the network from a protobuf text file on the disk.
Implements ITfParser.
Definition at line 3511 of file TfParser.cpp.
References CHECK_LOCATION.
 {
     FILE* fd = fopen(graphFile, "r");
     if (fd == nullptr)
     {
         throw FileNotFoundException(
             boost::str(
                 boost::format(
                     "Graph file %1% failed to open %2%")
                     % graphFile
                     % CHECK_LOCATION().AsString()));
     }
     // Parses the file into a message.
     tensorflow::GraphDef graphDef;
     auto                 input   = new google::protobuf::io::FileInputStream(fileno(fd));
     bool                 success = google::protobuf::TextFormat::Parse(input, &graphDef);
     delete input;
     fclose(fd);
     if (!success)
     {
         throw ParseException(
             boost::str(
                 boost::format(
                     "Failed to parse graph file %1%")
                     % CHECK_LOCATION().AsString()));
     }
     return CreateNetworkFromGraphDef(graphDef, inputShapes, requestedOutputs);
 }
GetNetworkInputBindingInfo()
BindingPointInfo GetNetworkInputBindingInfo (const std::string & name) const override virtual
Retrieves binding info (layer id and tensor info) for the network input identified by the given layer name.
Implements ITfParser.
Definition at line 3645 of file TfParser.cpp.
 {
     return GetBindingInfo(name, "input", m_NetworkInputsBindingInfo);
 }
GetNetworkOutputBindingInfo()
BindingPointInfo GetNetworkOutputBindingInfo (const std::string & name) const override virtual
Retrieves binding info (layer id and tensor info) for the network output identified by the given layer name.
Implements ITfParser.
Definition at line 3650 of file TfParser.cpp.
References CHECK_LOCATION, and IConnectableLayer::GetName().
 {
     return GetBindingInfo(name, "output", m_NetworkOutputsBindingInfo);
 }
Friends And Related Function Documentation
ParsedConstTfOperation
friend class ParsedConstTfOperation friend
Definition at line 96 of file TfParser.hpp.
Referenced by TfParser::TfParser().
ParsedMatMulTfOperation
friend class ParsedMatMulTfOperation friend
Definition at line 97 of file TfParser.hpp.
Referenced by armnnTfParser::OutputShapeOfSqueeze().
ParsedMulTfOperation
friend class ParsedMulTfOperation friend
Definition at line 98 of file TfParser.hpp.
Referenced by armnnTfParser::OutputShapeOfSqueeze().
The documentation for this class was generated from the following files:
src/armnnTfParser/TfParser.hpp
src/armnnTfParser/TfParser.cpp