ArmNN: SampleDynamicAdditionWorkload Class Reference
SampleDynamicAdditionWorkload Class Reference
#include <SampleDynamicAdditionWorkload.hpp>
Public Member Functions
SampleDynamicAdditionWorkload (const AdditionQueueDescriptor &descriptor, const WorkloadInfo &info)
void Execute () const override
Public Member Functions inherited from BaseWorkload< AdditionQueueDescriptor >
BaseWorkload (const AdditionQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const AdditionQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< AdditionQueueDescriptor >
const AdditionQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 13 of file SampleDynamicAdditionWorkload.hpp.
Constructor & Destructor Documentation
SampleDynamicAdditionWorkload()
SampleDynamicAdditionWorkload (const AdditionQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 34 of file SampleDynamicAdditionWorkload.cpp.
     : BaseWorkload(descriptor, info)
 {}
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 39 of file SampleDynamicAdditionWorkload.cpp.
References armnn::GetInputTensorData(), TensorInfo::GetNumElements(), armnn::GetOutputTensorData(), armnn::GetTensorInfo(), armnn::info, BaseWorkload< AdditionQueueDescriptor >::m_Data, and QueueDescriptor::m_Inputs.
 {
     const TensorInfo& info = GetTensorInfo(m_Data.m_Inputs[0]);
     unsigned int num = info.GetNumElements();
     const float* inputData0 = GetInputTensorData(0, m_Data);
     const float* inputData1 = GetInputTensorData(1, m_Data);
     float* outputData       = GetOutputTensorData(0, m_Data);
     for (unsigned int i = 0; i < num; ++i)
     {
         outputData[i] = inputData0[i] + inputData1[i];
     }
 }
The documentation for this class was generated from the following files:
src/dynamic/sample/SampleDynamicAdditionWorkload.hpp
src/dynamic/sample/SampleDynamicAdditionWorkload.cpp