ArmNN: Pooling2dLayer Class Reference
Pooling2dLayer Class Reference
This layer represents a pooling 2d operation.
#include <Pooling2dLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Pooling2dLayer * Clone (Graph &graph) const override
void ValidateTensorShapesFromInputs () override
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
void Accept (ILayerVisitor &visitor) const override
Public Member Functions inherited from LayerWithParameters< Pooling2dDescriptor >
const Pooling2dDescriptor & GetParameters () const
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
unsigned int GetNumInputSlots () const override
unsigned int GetNumOutputSlots () const override
const InputSlot & GetInputSlot (unsigned int index) const override
InputSlot & GetInputSlot (unsigned int index) override
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
OutputSlot & GetOutputSlot (unsigned int index=0) override
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
Protected Member Functions
Pooling2dLayer (const Pooling2dDescriptor &param, const char *name)
~Pooling2dLayer ()=default
Default destructor.
Protected Member Functions inherited from LayerWithParameters< Pooling2dDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const Pooling2dDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef ()
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< Pooling2dDescriptor >
using DescriptorType = Pooling2dDescriptor
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< Pooling2dDescriptor >
Pooling2dDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
Detailed Description
This layer represents a pooling 2d operation.
Definition at line 13 of file Pooling2dLayer.hpp.
Constructor & Destructor Documentation
Pooling2dLayer()
Pooling2dLayer (const Pooling2dDescriptor & param, const char * name) protected
Constructor to create a Pooling2dLayer.
Parameters
[in] param Pooling2dDescriptor to configure the pooling2d operation.
[in] name Optional name for the layer.
Definition at line 22 of file Pooling2dLayer.cpp.
References armnn::Pooling2d().
     : LayerWithParameters(1, 1, LayerType::Pooling2d, param, name)
 {
 }
~Pooling2dLayer()
~Pooling2dLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Implements IConnectableLayer.
Definition at line 117 of file Pooling2dLayer.cpp.
References Layer::GetName(), LayerWithParameters< Pooling2dDescriptor >::GetParameters(), and ILayerVisitor::VisitPooling2dLayer().
 {
     visitor.VisitPooling2dLayer(this, GetParameters(), GetName());
 }
Clone()
Pooling2dLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 33 of file Pooling2dLayer.cpp.
References Layer::GetName(), and LayerWithParameters< Pooling2dDescriptor >::m_Param.
 {
     return CloneBase<Pooling2dLayer>(graph, m_Param, GetName());
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the Pooling2d type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 27 of file Pooling2dLayer.cpp.
References IWorkloadFactory::CreatePooling2d(), and LayerWithParameters< Pooling2dDescriptor >::PrepInfoAndDesc().
 {
     Pooling2dQueueDescriptor descriptor;
     return factory.CreatePooling2d(descriptor, PrepInfoAndDesc(descriptor));
 }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 38 of file Pooling2dLayer.cpp.
References armnn::Ceiling, armnn::Floor, DataLayoutIndexed::GetChannelsIndex(), DataLayoutIndexed::GetHeightIndex(), DataLayoutIndexed::GetWidthIndex(), Pooling2dDescriptor::m_DataLayout, Pooling2dDescriptor::m_OutputShapeRounding, Pooling2dDescriptor::m_PadBottom, Pooling2dDescriptor::m_PadLeft, Pooling2dDescriptor::m_PadRight, Pooling2dDescriptor::m_PadTop, LayerWithParameters< Pooling2dDescriptor >::m_Param, Pooling2dDescriptor::m_PoolHeight, Pooling2dDescriptor::m_PoolWidth, Pooling2dDescriptor::m_StrideX, Pooling2dDescriptor::m_StrideY, and armnn::NHWC.
Referenced by Pooling2dLayer::ValidateTensorShapesFromInputs().
 {
     BOOST_ASSERT(inputShapes.size() == 1);
     const TensorShape& inputShape = inputShapes[0];
     const DataLayoutIndexed dimensionIndices = m_Param.m_DataLayout;
     // If we support multiple batch dimensions in the future, then this assert will need to change.
     BOOST_ASSERT_MSG(inputShape.GetNumDimensions() == 4, "Pooling2dLayer will always have 4D input.");
     unsigned int inWidth = inputShape[dimensionIndices.GetWidthIndex()];
     unsigned int inHeight = inputShape[dimensionIndices.GetHeightIndex()];
     unsigned int inChannels = inputShape[dimensionIndices.GetChannelsIndex()];
     unsigned int inBatchSize = inputShape[0];
     bool isGlobalPooling = (m_Param.m_StrideX==0 && m_Param.m_StrideY==0);
     unsigned int outWidth = 1;
     unsigned int outHeight = 1;
     if (!isGlobalPooling)
     {
         BOOST_ASSERT_MSG(m_Param.m_StrideX!=0 && m_Param.m_StrideY!=0,
                          "Stride can only be zero when performing global pooling");
         auto CalcSize = [](auto inSize, auto lowPad, auto highPad, auto poolSize, auto stride, auto outputShapeRounding)
             {
                 unsigned int readSize = inSize + lowPad + highPad - poolSize;
                 float div = static_cast<float>(readSize) / static_cast<float>(stride);
                 unsigned int size = 0;
                 switch (outputShapeRounding)
                 {
                     case OutputShapeRounding::Ceiling:
                         size = static_cast<unsigned int>(ceil(div)) + 1;
                         break;
                     case OutputShapeRounding ::Floor:
                         size = static_cast<unsigned int>(floor(div)) + 1;
                         break;
                     default:
                         BOOST_ASSERT_MSG(false, "Unsupported Output Shape Rounding");
                 }
                 // MakeS sure that border operations will start from inside the input and not the padded area.
                 // This is what both Caffe and CL do...
                 if ((size - 1)*stride >= inSize + lowPad)
                 {
                     --size;
                 }
                 return size;
             };
         outWidth = CalcSize(inWidth, m_Param.m_PadLeft, m_Param.m_PadRight, m_Param.m_PoolWidth, m_Param.m_StrideX,
                             m_Param.m_OutputShapeRounding);
         outHeight = CalcSize(inHeight, m_Param.m_PadTop, m_Param.m_PadBottom, m_Param.m_PoolHeight, m_Param.m_StrideY,
                             m_Param.m_OutputShapeRounding);
     }
     unsigned int outChannels = inChannels;
     unsigned int outBatchSize = inBatchSize;
     TensorShape tensorShape = m_Param.m_DataLayout == armnn::DataLayout::NHWC ?
         TensorShape( { outBatchSize, outHeight, outWidth, outChannels } ) :
         TensorShape( { outBatchSize, outChannels, outHeight, outWidth });
     return std::vector<TensorShape>({ tensorShape });
 }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of Pooling2dLayer.
Implements Layer.
Definition at line 103 of file Pooling2dLayer.cpp.
References CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), Pooling2dLayer::InferOutputShapes(), and Layer::VerifyLayerConnections().
 {
     VerifyLayerConnections(1, CHECK_LOCATION());
     auto inferredShapes = InferOutputShapes({ GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape() });
     BOOST_ASSERT(inferredShapes.size() == 1);
     ConditionalThrowIfNotEqual<LayerValidationException>(
         "Pooling2dLayer: TensorShape set on OutputSlot[0] does not match the inferred shape.",
         GetOutputSlot(0).GetTensorInfo().GetShape(),
         inferredShapes[0]);
 }
The documentation for this class was generated from the following files:
src/armnn/layers/Pooling2dLayer.hpp
src/armnn/layers/Pooling2dLayer.cpp