ArmNN: ProfilingService Class Reference
ProfilingService Class Reference
#include <ProfilingService.hpp>
Public Types
using ExternalProfilingOptions = IRuntime::CreationOptions::ExternalProfilingOptions
using IProfilingConnectionFactoryPtr = std::unique_ptr< IProfilingConnectionFactory >
using IProfilingConnectionPtr = std::unique_ptr< IProfilingConnection >
using CounterIndices = std::vector< std::atomic< uint32_t > * >
using CounterValues = std::list< std::atomic< uint32_t > >
Public Member Functions
void ResetExternalProfilingOptions (const ExternalProfilingOptions &options, bool resetProfilingService=false)
ProfilingState ConfigureProfilingService (const ExternalProfilingOptions &options, bool resetProfilingService=false)
void Update ()
void Disconnect ()
void AddBackendProfilingContext (const BackendId backendId, std::shared_ptr< armnn::profiling::IBackendProfilingContext > profilingContext)
const ICounterDirectory & GetCounterDirectory () const
ICounterRegistry & GetCounterRegistry ()
ProfilingState GetCurrentState () const
bool IsCounterRegistered (uint16_t counterUid) const override
uint32_t GetCounterValue (uint16_t counterUid) const override
uint16_t GetCounterCount () const override
const ICounterMappings & GetCounterMappings () const override
IRegisterCounterMapping & GetCounterMappingRegistry ()
bool IsProfilingEnabled () const override
CaptureData GetCaptureData () override
void SetCaptureData (uint32_t capturePeriod, const std::vector< uint16_t > &counterIds, const std::set< BackendId > &activeBackends)
void SetCounterValue (uint16_t counterUid, uint32_t value) override
uint32_t AddCounterValue (uint16_t counterUid, uint32_t value) override
uint32_t SubtractCounterValue (uint16_t counterUid, uint32_t value) override
uint32_t IncrementCounterValue (uint16_t counterUid) override
ProfilingDynamicGuid NextGuid () override
Return the next random Guid in the sequence.
ProfilingStaticGuid GenerateStaticId (const std::string &str) override
Create a ProfilingStaticGuid based on a hash of the string.
std::unique_ptr< ISendTimelinePacket > GetSendTimelinePacket () const override
ISendCounterPacket & GetSendCounterPacket () override
bool IsEnabled ()
Check if the profiling is enabled.
Public Member Functions inherited from IReadWriteCounterValues
virtual ~IReadWriteCounterValues ()
Public Member Functions inherited from IReadCounterValues
virtual ~IReadCounterValues ()
Public Member Functions inherited from IWriteCounterValues
virtual ~IWriteCounterValues ()
Public Member Functions inherited from IProfilingService
virtual ~IProfilingService ()
Public Member Functions inherited from IProfilingGuidGenerator
virtual ~IProfilingGuidGenerator ()
Static Public Member Functions
static ProfilingService & Instance ()
Protected Member Functions
ProfilingService ()
~ProfilingService ()
void SwapProfilingConnectionFactory (ProfilingService &instance, IProfilingConnectionFactory *other, IProfilingConnectionFactory *&backup)
IProfilingConnection * GetProfilingConnection (ProfilingService &instance)
void TransitionToState (ProfilingService &instance, ProfilingState newState)
bool WaitForPacketSent (ProfilingService &instance, uint32_t timeout=1000)
BufferManager & GetBufferManager (ProfilingService &instance)
Detailed Description
Definition at line 42 of file ProfilingService.hpp.
Member Typedef Documentation
CounterIndices
using CounterIndices = std::vector<std::atomic<uint32_t>*>
Definition at line 48 of file ProfilingService.hpp.
CounterValues
using CounterValues = std::list<std::atomic<uint32_t> >
Definition at line 49 of file ProfilingService.hpp.
ExternalProfilingOptions
using ExternalProfilingOptions = IRuntime::CreationOptions::ExternalProfilingOptions
Definition at line 45 of file ProfilingService.hpp.
IProfilingConnectionFactoryPtr
using IProfilingConnectionFactoryPtr = std::unique_ptr<IProfilingConnectionFactory>
Definition at line 46 of file ProfilingService.hpp.
IProfilingConnectionPtr
using IProfilingConnectionPtr = std::unique_ptr<IProfilingConnection>
Definition at line 47 of file ProfilingService.hpp.
Constructor & Destructor Documentation
ProfilingService()
ProfilingService () inline protected
Definition at line 160 of file ProfilingService.hpp.
References CommandHandlerRegistry::RegisterFunctor(), and ProfilingService::~ProfilingService().
Referenced by ProfilingService::IsEnabled().
         : m_Options()
         , m_CounterDirectory()
         , m_ProfilingConnectionFactory(new ProfilingConnectionFactory())
         , m_ProfilingConnection()
         , m_StateMachine()
         , m_CounterIndex()
         , m_CounterValues()
         , m_CommandHandlerRegistry()
         , m_PacketVersionResolver()
         , m_CommandHandler(1000,
                            false,
                            m_CommandHandlerRegistry,
                            m_PacketVersionResolver)
         , m_BufferManager()
         , m_SendCounterPacket(m_BufferManager)
         , m_SendThread(m_StateMachine, m_BufferManager, m_SendCounterPacket)
         , m_SendTimelinePacket(m_BufferManager)
         , m_PeriodicCounterCapture(m_Holder, m_SendCounterPacket, *this, m_CounterIdMap, m_BackendProfilingContexts)
         , m_ConnectionAcknowledgedCommandHandler(0,
                                                  1,
                                                  m_PacketVersionResolver.ResolvePacketVersion(0, 1).GetEncodedValue(),
                                                  m_CounterDirectory,
                                                  m_SendCounterPacket,
                                                  m_SendTimelinePacket,
                                                  m_StateMachine)
         , m_RequestCounterDirectoryCommandHandler(0,
                                                   3,
                                                   m_PacketVersionResolver.ResolvePacketVersion(0, 3).GetEncodedValue(),
                                                   m_CounterDirectory,
                                                   m_SendCounterPacket,
                                                   m_SendTimelinePacket,
                                                   m_StateMachine)
         , m_PeriodicCounterSelectionCommandHandler(0,
                                                    4,
                                                    m_PacketVersionResolver.ResolvePacketVersion(0, 4).GetEncodedValue(),
                                                    m_BackendProfilingContexts,
                                                    m_CounterIdMap,
                                                    m_Holder,
                                                    MAX_ARMNN_COUNTER,
                                                    m_PeriodicCounterCapture,
                                                    *this,
                                                    m_SendCounterPacket,
                                                    m_StateMachine)
         , m_PerJobCounterSelectionCommandHandler(0,
                                                  5,
                                                  m_PacketVersionResolver.ResolvePacketVersion(0, 5).GetEncodedValue(),
                                                  m_StateMachine)
         , m_TimelinePacketWriterFactory(m_BufferManager)
         , m_MaxGlobalCounterId(armnn::profiling::INFERENCES_RUN)
     {
         // Register the "Connection Acknowledged" command handler
         m_CommandHandlerRegistry.RegisterFunctor(&m_ConnectionAcknowledgedCommandHandler);
         // Register the "Request Counter Directory" command handler
         m_CommandHandlerRegistry.RegisterFunctor(&m_RequestCounterDirectoryCommandHandler);
         // Register the "Periodic Counter Selection" command handler
         m_CommandHandlerRegistry.RegisterFunctor(&m_PeriodicCounterSelectionCommandHandler);
         // Register the "Per-Job Counter Selection" command handler
         m_CommandHandlerRegistry.RegisterFunctor(&m_PerJobCounterSelectionCommandHandler);
     }
~ProfilingService()
~ProfilingService () protected
Definition at line 448 of file ProfilingService.cpp.
Referenced by ProfilingService::ProfilingService().
 {
     Stop();
 }
Member Function Documentation
AddBackendProfilingContext()
void AddBackendProfilingContext (const BackendId backendId, std::shared_ptr< armnn::profiling::IBackendProfilingContext > profilingContext)
Definition at line 185 of file ProfilingService.cpp.
Referenced by ProfilingService::Instance(), and Runtime::Runtime().
 {
     BOOST_ASSERT(profilingContext != nullptr);
     // Register the backend counters
     m_MaxGlobalCounterId = profilingContext->RegisterCounters(m_MaxGlobalCounterId);
     m_BackendProfilingContexts.emplace(backendId, std::move(profilingContext));
 }
AddCounterValue()
uint32_t AddCounterValue (uint16_t counterUid, uint32_t value) override virtual
Implements IWriteCounterValues.
Definition at line 256 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::Instance().
 {
     CheckCounterUid(counterUid);
     std::atomic<uint32_t>* counterValuePtr = m_CounterIndex.at(counterUid);
     BOOST_ASSERT(counterValuePtr);
     return counterValuePtr->fetch_add(value, std::memory_order::memory_order_relaxed);
 }
ConfigureProfilingService()
ProfilingState ConfigureProfilingService (const ExternalProfilingOptions & options, bool resetProfilingService = false)
Definition at line 38 of file ProfilingService.cpp.
References ProfilingStateMachine::GetCurrentState(), IRuntime::CreationOptions::ExternalProfilingOptions::m_EnableProfiling, armnn::profiling::NotConnected, ProfilingService::ResetExternalProfilingOptions(), armnn::profiling::Uninitialised, ProfilingService::Update(), and armnn::profiling::WaitingForAck.
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::Instance(), Runtime::Runtime(), and VerifyPostOptimisationStructureTestImpl().
 {
     ResetExternalProfilingOptions(options, resetProfilingService);
     ProfilingState currentState = m_StateMachine.GetCurrentState();
     if (options.m_EnableProfiling)
     {
         switch (currentState)
         {
             case ProfilingState::Uninitialised:
                 Update(); // should transition to NotConnected
                 Update(); // will either stay in NotConnected because there is no server
                           // or will enter WaitingForAck.
                 currentState = m_StateMachine.GetCurrentState();
                 if (currentState == ProfilingState::WaitingForAck)
                 {
                     Update(); // poke it again to send out the metadata packet
                 }
                 currentState = m_StateMachine.GetCurrentState();
                 return currentState;
             case ProfilingState::NotConnected:
                 Update(); // will either stay in NotConnected because there is no server
                           // or will enter WaitingForAck
                 currentState = m_StateMachine.GetCurrentState();
                 if (currentState == ProfilingState::WaitingForAck)
                 {
                     Update(); // poke it again to send out the metadata packet
                 }
                 currentState = m_StateMachine.GetCurrentState();
                 return currentState;
             default:
                 return currentState;
         }
     }
     else
     {
         // Make sure profiling is shutdown
         switch (currentState)
         {
             case ProfilingState::Uninitialised:
             case ProfilingState::NotConnected:
                 return currentState;
             default:
                 Stop();
                 return m_StateMachine.GetCurrentState();
         }
     }
 }
Disconnect()
void Disconnect ()
Definition at line 164 of file ProfilingService.cpp.
References armnn::profiling::Active, ProfilingStateMachine::GetCurrentState(), armnn::profiling::NotConnected, armnn::profiling::Uninitialised, and armnn::profiling::WaitingForAck.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::Instance().
 {
     ProfilingState currentState = m_StateMachine.GetCurrentState();
     switch (currentState)
     {
     case ProfilingState::Uninitialised:
     case ProfilingState::NotConnected:
     case ProfilingState::WaitingForAck:
         return; // NOP
     case ProfilingState::Active:
         // Stop the command thread (if running)
         Stop();
         break;
     default:
         throw RuntimeException(boost::str(boost::format("Unknown profiling service state: %1")
                                           % static_cast<int>(currentState)));
     }
 }
GenerateStaticId()
ProfilingStaticGuid GenerateStaticId (const std::string & str) override virtual
Create a ProfilingStaticGuid based on a hash of the string.
Implements IProfilingGuidGenerator.
Definition at line 285 of file ProfilingService.cpp.
References ProfilingGuidGenerator::GenerateStaticId().
Referenced by BOOST_AUTO_TEST_CASE(), TimelineUtilityMethods::DeclareLabel(), and ProfilingService::Instance().
 {
     return m_GuidGenerator.GenerateStaticId(str);
 }
GetBufferManager()
BufferManager& GetBufferManager (ProfilingService & instance) inline protected
Definition at line 249 of file ProfilingService.hpp.
     {
         return instance.m_BufferManager;
     }
GetCaptureData()
CaptureData GetCaptureData () override virtual
Implements IProfilingService.
Definition at line 236 of file ProfilingService.cpp.
References Holder::GetCaptureData().
Referenced by ProfilingService::Instance().
 {
     return m_Holder.GetCaptureData();
 }
GetCounterCount()
uint16_t GetCounterCount () const override virtual
Implements IReadCounterValues.
Definition at line 208 of file ProfilingService.cpp.
References CounterDirectory::GetCounterCount().
Referenced by ProfilingService::Instance().
 {
     return m_CounterDirectory.GetCounterCount();
 }
GetCounterDirectory()
const ICounterDirectory & GetCounterDirectory () const
Definition at line 193 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::Instance().
 {
     return m_CounterDirectory;
 }
GetCounterMappingRegistry()
IRegisterCounterMapping & GetCounterMappingRegistry ()
Definition at line 231 of file ProfilingService.cpp.
Referenced by ProfilingService::Instance(), and RegisterBackendCounters::RegisterCounter().
 {
     return m_CounterIdMap;
 }
GetCounterMappings()
const ICounterMappings & GetCounterMappings () const override virtual
Implements IProfilingService.
Definition at line 226 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BackendProfiling::GetActiveCounters(), and ProfilingService::Instance().
 {
     return m_CounterIdMap;
 }
GetCounterRegistry()
ICounterRegistry & GetCounterRegistry ()
Definition at line 198 of file ProfilingService.cpp.
Referenced by ProfilingService::Instance().
 {
     return m_CounterDirectory;
 }
GetCounterValue()
uint32_t GetCounterValue (uint16_t counterUid) const override virtual
Implements IReadCounterValues.
Definition at line 218 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::Instance(), and while().
 {
     CheckCounterUid(counterUid);
     std::atomic<uint32_t>* counterValuePtr = m_CounterIndex.at(counterUid);
     BOOST_ASSERT(counterValuePtr);
     return counterValuePtr->load(std::memory_order::memory_order_relaxed);
 }
GetCurrentState()
ProfilingState GetCurrentState () const
Definition at line 203 of file ProfilingService.cpp.
References ProfilingStateMachine::GetCurrentState().
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::Instance(), and while().
 {
     return m_StateMachine.GetCurrentState();
 }
GetProfilingConnection()
IProfilingConnection* GetProfilingConnection (ProfilingService & instance) inline protected
Definition at line 236 of file ProfilingService.hpp.
     {
         return instance.m_ProfilingConnection.get();
     }
GetSendCounterPacket()
ISendCounterPacket& GetSendCounterPacket () inline override virtual
Implements IProfilingService.
Definition at line 106 of file ProfilingService.hpp.
     {
         return m_SendCounterPacket;
     }
GetSendTimelinePacket()
std::unique_ptr< ISendTimelinePacket > GetSendTimelinePacket () const override virtual
Implements IProfilingService.
Definition at line 290 of file ProfilingService.cpp.
References CounterDirectory::Clear(), TimelinePacketWriterFactory::GetSendTimelinePacket(), CounterDirectory::IsCategoryRegistered(), CounterDirectory::IsCounterRegistered(), ProfilingService::IsCounterRegistered(), Counter::m_Uid, armnn::profiling::NotConnected, CounterDirectory::RegisterCategory(), CounterDirectory::RegisterCounter(), BufferManager::Reset(), ProfilingStateMachine::Reset(), CounterIdMap::Reset(), SendThread::Stop(), CommandHandler::Stop(), PeriodicCounterCapture::Stop(), and ProfilingStateMachine::TransitionToState().
Referenced by BOOST_AUTO_TEST_CASE(), TimelineUtilityMethods::GetTimelineUtils(), and ProfilingService::Instance().
 {
     return m_TimelinePacketWriterFactory.GetSendTimelinePacket();
 }
IncrementCounterValue()
uint32_t IncrementCounterValue (uint16_t counterUid) override virtual
Implements IWriteCounterValues.
Definition at line 272 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BackendRegistry::Deregister(), LoadedNetwork::EnqueueWorkload(), ProfilingService::Instance(), Runtime::LoadNetwork(), BackendRegistry::Register(), Runtime::UnloadNetwork(), and while().
 {
     CheckCounterUid(counterUid);
     std::atomic<uint32_t>* counterValuePtr = m_CounterIndex.at(counterUid);
     BOOST_ASSERT(counterValuePtr);
     return counterValuePtr->operator++(std::memory_order::memory_order_relaxed);
 }
Instance()
static ProfilingService& Instance () inline static
Definition at line 52 of file ProfilingService.hpp.
References ProfilingService::AddBackendProfilingContext(), ProfilingService::AddCounterValue(), ProfilingService::ConfigureProfilingService(), ProfilingService::Disconnect(), ProfilingService::GenerateStaticId(), ProfilingService::GetCaptureData(), ProfilingService::GetCounterCount(), ProfilingService::GetCounterDirectory(), ProfilingService::GetCounterMappingRegistry(), ProfilingService::GetCounterMappings(), ProfilingService::GetCounterRegistry(), ProfilingService::GetCounterValue(), ProfilingService::GetCurrentState(), ProfilingService::GetSendTimelinePacket(), ProfilingService::IncrementCounterValue(), ProfilingService::IsCounterRegistered(), ProfilingService::IsProfilingEnabled(), ProfilingService::NextGuid(), options, ProfilingService::ResetExternalProfilingOptions(), ProfilingService::SetCaptureData(), ProfilingService::SetCounterValue(), ProfilingService::SubtractCounterValue(), and ProfilingService::Update().
Referenced by BOOST_AUTO_TEST_CASE(), TimelineUtilityMethods::CreateConnectionRelationship(), TimelineUtilityMethods::CreateNamedTypedChildEntity(), TimelineUtilityMethods::CreateNamedTypedEntity(), TimelineUtilityMethods::CreateRelationship(), TimelineUtilityMethods::DeclareLabel(), BackendRegistry::Deregister(), LoadedNetwork::EnqueueWorkload(), SwapProfilingConnectionFactoryHelper::ForceTransitionToState(), BackendProfiling::GetActiveCounters(), SwapProfilingConnectionFactoryHelper::GetMockProfilingConnection(), ProfilingServiceRuntimeHelper::GetProfilingBufferManager(), TimelineUtilityMethods::GetTimelineUtils(), Runtime::LoadNetwork(), TimelineUtilityMethods::MarkEntityWithLabel(), TimelineUtilityMethods::MarkEntityWithType(), TimelineUtilityMethods::RecordEvent(), TimelineUtilityMethods::RecordWorkloadInferenceAndStartOfLifeEvent(), BackendRegistry::Register(), RegisterBackendCounters::RegisterCounter(), Runtime::Runtime(), SwapProfilingConnectionFactoryHelper::SwapProfilingConnectionFactoryHelper(), Runtime::UnloadNetwork(), VerifyPostOptimisationStructureTestImpl(), SwapProfilingConnectionFactoryHelper::WaitForPacketsSent(), and SwapProfilingConnectionFactoryHelper::~SwapProfilingConnectionFactoryHelper().
     {
         static ProfilingService instance;
         return instance;
     }
IsCounterRegistered()
bool IsCounterRegistered (uint16_t counterUid) const override virtual
Implements IReadCounterValues.
Definition at line 213 of file ProfilingService.cpp.
Referenced by ProfilingService::GetSendTimelinePacket(), ProfilingService::Instance(), and while().
 {
     return counterUid < m_CounterIndex.size();
 }
IsEnabled()
bool IsEnabled () inline
Check if the profiling is enabled.
Definition at line 112 of file ProfilingService.hpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_EnableProfiling, and ProfilingService::ProfilingService().
 { return m_Options.m_EnableProfiling; }
IsProfilingEnabled()
bool IsProfilingEnabled () const override virtual
Implements IProfilingService.
Definition at line 33 of file ProfilingService.cpp.
References IRuntime::CreationOptions::ExternalProfilingOptions::m_EnableProfiling.
Referenced by ProfilingService::Instance().
 {
     return m_Options.m_EnableProfiling;
 }
NextGuid()
ProfilingDynamicGuid NextGuid () override virtual
Return the next random Guid in the sequence.
Implements IProfilingGuidGenerator.
Definition at line 280 of file ProfilingService.cpp.
References ProfilingGuidGenerator::NextGuid().
Referenced by BOOST_AUTO_TEST_CASE(), TimelineUtilityMethods::CreateConnectionRelationship(), TimelineUtilityMethods::CreateNamedTypedChildEntity(), TimelineUtilityMethods::CreateNamedTypedEntity(), TimelineUtilityMethods::CreateRelationship(), LoadedNetwork::EnqueueWorkload(), ProfilingService::Instance(), TimelineUtilityMethods::MarkEntityWithLabel(), TimelineUtilityMethods::MarkEntityWithType(), TimelineUtilityMethods::RecordEvent(), and TimelineUtilityMethods::RecordWorkloadInferenceAndStartOfLifeEvent().
 {
     return m_GuidGenerator.NextGuid();
 }
ResetExternalProfilingOptions()
void ResetExternalProfilingOptions (const ExternalProfilingOptions & options, bool resetProfilingService = false)
Definition at line 19 of file ProfilingService.cpp.
References options.
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::ConfigureProfilingService(), ProfilingService::Instance(), and while().
 {
     // Update the profiling options
     m_Options = options;
     // Check if the profiling service needs to be reset
     if (resetProfilingService)
     {
         // Reset the profiling service
         Reset();
     }
 }
SetCaptureData()
void SetCaptureData (uint32_t capturePeriod, const std::vector< uint16_t > & counterIds, const std::set< BackendId > & activeBackends)
Definition at line 241 of file ProfilingService.cpp.
References Holder::SetCaptureData().
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::Instance().
 {
     m_Holder.SetCaptureData(capturePeriod, counterIds, activeBackends);
 }
SetCounterValue()
void SetCounterValue (uint16_t counterUid, uint32_t value) override virtual
Implements IWriteCounterValues.
Definition at line 248 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::Instance().
 {
     CheckCounterUid(counterUid);
     std::atomic<uint32_t>* counterValuePtr = m_CounterIndex.at(counterUid);
     BOOST_ASSERT(counterValuePtr);
     counterValuePtr->store(value, std::memory_order::memory_order_relaxed);
 }
SubtractCounterValue()
uint32_t SubtractCounterValue (uint16_t counterUid, uint32_t value) override virtual
Implements IWriteCounterValues.
Definition at line 264 of file ProfilingService.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and ProfilingService::Instance().
 {
     CheckCounterUid(counterUid);
     std::atomic<uint32_t>* counterValuePtr = m_CounterIndex.at(counterUid);
     BOOST_ASSERT(counterValuePtr);
     return counterValuePtr->fetch_sub(value, std::memory_order::memory_order_relaxed);
 }
SwapProfilingConnectionFactory()
void SwapProfilingConnectionFactory (ProfilingService & instance, IProfilingConnectionFactory * other, IProfilingConnectionFactory *& backup) inline protected
Definition at line 226 of file ProfilingService.hpp.
     {
         BOOST_ASSERT(instance.m_ProfilingConnectionFactory);
         BOOST_ASSERT(other);
         backup = instance.m_ProfilingConnectionFactory.release();
         instance.m_ProfilingConnectionFactory.reset(other);
     }
TransitionToState()
void TransitionToState (ProfilingService & instance, ProfilingState newState) inline protected
Definition at line 240 of file ProfilingService.hpp.
References ProfilingStateMachine::TransitionToState().
     {
         instance.m_StateMachine.TransitionToState(newState);
     }
Update()
void Update ()
Definition at line 88 of file ProfilingService.cpp.
References armnn::profiling::Active, ARMNN_LOG, ProfilingStateMachine::GetCurrentState(), IRuntime::CreationOptions::ExternalProfilingOptions::m_EnableProfiling, armnn::profiling::NotConnected, SendThread::Start(), CommandHandler::Start(), SendThread::Stop(), CommandHandler::Stop(), PeriodicCounterCapture::Stop(), ProfilingStateMachine::TransitionToState(), armnn::profiling::Uninitialised, armnn::profiling::WaitingForAck, armnn::warning, and Exception::what().
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingService::ConfigureProfilingService(), and ProfilingService::Instance().
 {
     if (!m_Options.m_EnableProfiling)
     {
         // Don't run if profiling is disabled
         return;
     }
     ProfilingState currentState = m_StateMachine.GetCurrentState();
     switch (currentState)
     {
     case ProfilingState::Uninitialised:
         // Initialize the profiling service
         Initialize();
         // Move to the next state
         m_StateMachine.TransitionToState(ProfilingState::NotConnected);
         break;
     case ProfilingState::NotConnected:
         // Stop the command thread (if running)
         m_CommandHandler.Stop();
         // Stop the send thread (if running)
         m_SendThread.Stop(false);
         // Stop the periodic counter capture thread (if running)
         m_PeriodicCounterCapture.Stop();
         // Reset any existing profiling connection
         m_ProfilingConnection.reset();
         try
         {
             // Setup the profiling connection
             BOOST_ASSERT(m_ProfilingConnectionFactory);
             m_ProfilingConnection = m_ProfilingConnectionFactory->GetProfilingConnection(m_Options);
         }
         catch (const Exception& e)
         {
             ARMNN_LOG(warning) << "An error has occurred when creating the profiling connection: "
                                        << e.what();
         }
         // Move to the next state
         m_StateMachine.TransitionToState(m_ProfilingConnection
                                          ? ProfilingState::WaitingForAck  // Profiling connection obtained, wait for ack
                                          : ProfilingState::NotConnected); // Profiling connection failed, stay in the
                                                                           // "NotConnected" state
         break;
     case ProfilingState::WaitingForAck:
         BOOST_ASSERT(m_ProfilingConnection);
         // Start the command thread
         m_CommandHandler.Start(*m_ProfilingConnection);
         // Start the send thread, while in "WaitingForAck" state it'll send out a "Stream MetaData" packet waiting for
         // a valid "Connection Acknowledged" packet confirming the connection
         m_SendThread.Start(*m_ProfilingConnection);
         // The connection acknowledged command handler will automatically transition the state to "Active" once a
         // valid "Connection Acknowledged" packet has been received
         break;
     case ProfilingState::Active:
         // The period counter capture thread is started by the Periodic Counter Selection command handler upon
         // request by an external profiling service
         break;
     default:
         throw RuntimeException(boost::str(boost::format("Unknown profiling service state: %1")
                                           % static_cast<int>(currentState)));
     }
 }
WaitForPacketSent()
bool WaitForPacketSent (ProfilingService & instance, uint32_t timeout = 1000) inline protected
Definition at line 244 of file ProfilingService.hpp.
References SendThread::WaitForPacketSent().
Referenced by SwapProfilingConnectionFactoryHelper::WaitForPacketsSent().
     {
         return instance.m_SendThread.WaitForPacketSent(timeout);
     }
The documentation for this class was generated from the following files:
src/profiling/ProfilingService.hpp
src/profiling/ProfilingService.cpp