ArmNN: ScopedCpuTensorHandle Class Reference
ScopedCpuTensorHandle Class Reference
#include <CpuTensorHandle.hpp>
Public Member Functions
ScopedCpuTensorHandle (const TensorInfo &tensorInfo)
ScopedCpuTensorHandle (const ConstTensor &tensor)
ScopedCpuTensorHandle (const ConstCpuTensorHandle &tensorHandle)
ScopedCpuTensorHandle (const ScopedCpuTensorHandle &other)
ScopedCpuTensorHandle & operator= (const ScopedCpuTensorHandle &other)
~ScopedCpuTensorHandle ()
virtual void Allocate () override
Public Member Functions inherited from CpuTensorHandle
template<typename T >
T * GetTensor () const
template<>
void * GetTensor () const
template<>
void * GetTensor () const
Public Member Functions inherited from ConstCpuTensorHandle
template<typename T >
const T * GetConstTensor () const
const TensorInfo & GetTensorInfo () const
virtual void Manage () override
virtual ITensorHandle * GetParent () const override
virtual const void * Map (bool) const override
virtual void Unmap () const override
Unmap the tensor data.
TensorShape GetStrides () const override
TensorShape GetShape () const override
template<>
const void * GetConstTensor () const
template<>
const void * GetConstTensor () const
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()
void * Map (bool blocking=true)
void Unmap ()
Unmap the tensor data that was previously mapped with call to Map().
virtual unsigned int GetImportFlags () const
Get flags describing supported import sources.
virtual bool Import (void *memory, MemorySource source)
Additional Inherited Members
Protected Member Functions inherited from CpuTensorHandle
CpuTensorHandle (const TensorInfo &tensorInfo)
void SetMemory (void *mem)
Protected Member Functions inherited from ConstCpuTensorHandle
ConstCpuTensorHandle (const TensorInfo &tensorInfo)
void SetConstMemory (const void *mem)
Detailed Description
Definition at line 106 of file CpuTensorHandle.hpp.
Constructor & Destructor Documentation
ScopedCpuTensorHandle() [1/4]
ScopedCpuTensorHandle (const TensorInfo & tensorInfo) explicit
Definition at line 54 of file CpuTensorHandle.cpp.
 : CpuTensorHandle(tensorInfo)
 {
 }
ScopedCpuTensorHandle() [2/4]
ScopedCpuTensorHandle (const ConstTensor & tensor) explicit
Definition at line 59 of file CpuTensorHandle.cpp.
References BaseTensor< MemoryType >::GetMemoryArea(), and BaseTensor< MemoryType >::GetNumBytes().
 : ScopedCpuTensorHandle(tensor.GetInfo())
 {
     CopyFrom(tensor.GetMemoryArea(), tensor.GetNumBytes());
 }
ScopedCpuTensorHandle() [3/4]
ScopedCpuTensorHandle (const ConstCpuTensorHandle & tensorHandle) explicit
Definition at line 65 of file CpuTensorHandle.cpp.
References ConstCpuTensorHandle::GetConstTensor(), TensorInfo::GetNumBytes(), and ConstCpuTensorHandle::GetTensorInfo().
 : ScopedCpuTensorHandle(tensorHandle.GetTensorInfo())
 {
     CopyFrom(tensorHandle.GetConstTensor<void>(), tensorHandle.GetTensorInfo().GetNumBytes());
 }
ScopedCpuTensorHandle() [4/4]
ScopedCpuTensorHandle (const ScopedCpuTensorHandle & other)
Definition at line 71 of file CpuTensorHandle.cpp.
 : CpuTensorHandle(other.GetTensorInfo())
 {
     CopyFrom(other);
 }
~ScopedCpuTensorHandle()
~ScopedCpuTensorHandle ()
Definition at line 85 of file CpuTensorHandle.cpp.
 {
     ::operator delete(GetTensor<void>());
 }
Member Function Documentation
Allocate()
void Allocate () override virtual
Indicate to the memory manager that this resource is no longer active. This is used to compute overlapping lifetimes of resources.
Implements ITensorHandle.
Definition at line 90 of file CpuTensorHandle.cpp.
References TensorInfo::GetNumBytes(), CpuTensorHandle::GetTensor(), ConstCpuTensorHandle::GetTensorInfo(), and CpuTensorHandle::SetMemory().
 {
     if (GetTensor<void>() == nullptr)
     {
         SetMemory(::operator new(GetTensorInfo().GetNumBytes()));
     }
     else
     {
         throw InvalidArgumentException("CpuTensorHandle::Allocate Trying to allocate a CpuTensorHandle"
             "that already has allocated memory.");
     }
 }
operator=()
ScopedCpuTensorHandle & operator= (const ScopedCpuTensorHandle & other)
Definition at line 77 of file CpuTensorHandle.cpp.
References CpuTensorHandle::SetMemory().
 {
     ::operator delete(GetTensor<void>());
     SetMemory(nullptr);
     CopyFrom(other);
     return *this;
 }
The documentation for this class was generated from the following files:
src/backends/backendsCommon/CpuTensorHandle.hpp
src/backends/backendsCommon/CpuTensorHandle.cpp