ArmNN: TimelineDecoder Class Reference
TimelineDecoder Class Reference
#include <TimelineDecoder.hpp>
Classes
struct Model
Public Types
using OnNewEntityCallback = void(*)(Model &, const Entity)
using OnNewEventClassCallback = void(*)(Model &, const EventClass)
using OnNewEventCallback = void(*)(Model &, const Event)
using OnNewLabelCallback = void(*)(Model &, const Label)
using OnNewRelationshipCallback = void(*)(Model &, const Relationship)
Public Types inherited from ITimelineDecoder
enum TimelineStatus { TimelineStatus_Success, TimelineStatus_Fail }
enum RelationshipType { RetentionLink, ExecutionLink, DataLink, LabelLink }
Public Member Functions
virtual TimelineStatus CreateEntity (const Entity &) override
virtual TimelineStatus CreateEventClass (const EventClass &) override
virtual TimelineStatus CreateEvent (const Event &) override
virtual TimelineStatus CreateLabel (const Label &) override
virtual TimelineStatus CreateRelationship (const Relationship &) override
const Model & GetModel ()
TimelineStatus SetEntityCallback (const OnNewEntityCallback)
TimelineStatus SetEventClassCallback (const OnNewEventClassCallback)
TimelineStatus SetEventCallback (const OnNewEventCallback)
TimelineStatus SetLabelCallback (const OnNewLabelCallback)
TimelineStatus SetRelationshipCallback (const OnNewRelationshipCallback)
void print ()
Public Member Functions inherited from ITimelineDecoder
virtual ~ITimelineDecoder ()=default
Detailed Description
Definition at line 14 of file TimelineDecoder.hpp.
Member Typedef Documentation
OnNewEntityCallback
using OnNewEntityCallback = void (*)(Model &, const Entity)
Definition at line 28 of file TimelineDecoder.hpp.
OnNewEventCallback
using OnNewEventCallback = void (*)(Model &, const Event)
Definition at line 30 of file TimelineDecoder.hpp.
OnNewEventClassCallback
using OnNewEventClassCallback = void (*)(Model &, const EventClass)
Definition at line 29 of file TimelineDecoder.hpp.
OnNewLabelCallback
using OnNewLabelCallback = void (*)(Model &, const Label)
Definition at line 31 of file TimelineDecoder.hpp.
OnNewRelationshipCallback
using OnNewRelationshipCallback = void (*)(Model &, const Relationship)
Definition at line 32 of file TimelineDecoder.hpp.
Member Function Documentation
CreateEntity()
TimelineDecoder::TimelineStatus CreateEntity (const Entity & entity) override virtual
Implements ITimelineDecoder.
Definition at line 14 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
 {
     if (m_OnNewEntityCallback == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewEntityCallback(m_Model, entity);
     return TimelineStatus::TimelineStatus_Success;
 }
CreateEvent()
TimelineDecoder::TimelineStatus CreateEvent (const Event & event) override virtual
Implements ITimelineDecoder.
Definition at line 36 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
 {
     if (m_OnNewEventCallback == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewEventCallback(m_Model, event);
     return TimelineStatus::TimelineStatus_Success;
 }
CreateEventClass()
TimelineDecoder::TimelineStatus CreateEventClass (const EventClass & eventClass) override virtual
Implements ITimelineDecoder.
Definition at line 25 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
 {
     if (m_OnNewEventClassCallback == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewEventClassCallback(m_Model, eventClass);
     return TimelineStatus::TimelineStatus_Success;
 }
CreateLabel()
TimelineDecoder::TimelineStatus CreateLabel (const Label & label) override virtual
Implements ITimelineDecoder.
Definition at line 47 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
 {
     if (m_OnNewLabelCallback == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewLabelCallback(m_Model, label);
     return TimelineStatus::TimelineStatus_Success;
 }
CreateRelationship()
TimelineDecoder::TimelineStatus CreateRelationship (const Relationship & relationship) override virtual
Implements ITimelineDecoder.
Definition at line 58 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
 {
     if (m_OnNewRelationshipCallback == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewRelationshipCallback(m_Model, relationship);
     return TimelineStatus::TimelineStatus_Success;
 }
GetModel()
const TimelineDecoder::Model & GetModel ()
Definition at line 68 of file TimelineDecoder.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     return m_Model;
 }
print()
void print ()
Definition at line 123 of file TimelineDecoder.cpp.
References armnn::profiling::CentreAlignFormatting(), TimelineDecoder::Model::m_Entities, TimelineDecoder::Model::m_EventClasses, TimelineDecoder::Model::m_Events, TimelineDecoder::Model::m_Labels, and TimelineDecoder::Model::m_Relationships.
 {
     printLabels();
     printEntities();
     printEventClasses();
     printEvents();
     printRelationships();
 }
SetEntityCallback()
TimelineDecoder::TimelineStatus SetEntityCallback (const OnNewEntityCallback cb)
Definition at line 73 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewEntityCallback = cb;
     return TimelineStatus::TimelineStatus_Success;
 }
SetEventCallback()
TimelineDecoder::TimelineStatus SetEventCallback (const OnNewEventCallback cb)
Definition at line 93 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewEventCallback = cb;
     return TimelineStatus::TimelineStatus_Success;
 }
SetEventClassCallback()
TimelineDecoder::TimelineStatus SetEventClassCallback (const OnNewEventClassCallback cb)
Definition at line 83 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewEventClassCallback = cb;
     return TimelineStatus::TimelineStatus_Success;
 }
SetLabelCallback()
TimelineDecoder::TimelineStatus SetLabelCallback (const OnNewLabelCallback cb)
Definition at line 103 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewLabelCallback = cb;
     return TimelineStatus::TimelineStatus_Success;
 }
SetRelationshipCallback()
TimelineDecoder::TimelineStatus SetRelationshipCallback (const OnNewRelationshipCallback cb)
Definition at line 113 of file TimelineDecoder.cpp.
References ITimelineDecoder::TimelineStatus_Fail, and ITimelineDecoder::TimelineStatus_Success.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     if (cb == nullptr)
     {
         return TimelineStatus::TimelineStatus_Fail;
     }
     m_OnNewRelationshipCallback = cb;
     return TimelineStatus::TimelineStatus_Success;
 }
The documentation for this class was generated from the following files:
src/timelineDecoder/TimelineDecoder.hpp
src/timelineDecoder/TimelineDecoder.cpp