ArmNN: RefTensorHandleFactory Class Reference
RefTensorHandleFactory Class Reference
#include <RefTensorHandleFactory.hpp>
Public Member Functions
RefTensorHandleFactory (std::shared_ptr< RefMemoryManager > mgr)
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout) const override
const FactoryId & GetId () const override
bool SupportsSubTensors () const override
MemorySourceFlags GetExportFlags () const override
MemorySourceFlags GetImportFlags () const override
Public Member Functions inherited from ITensorHandleFactory
virtual ~ITensorHandleFactory ()
Some TensorHandleFactory decisions are deferred to run-time.
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged) const
Utility Functions for backends which require TensorHandles to have unmanaged memory.
virtual std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged) const
virtual bool SupportsMapUnmap () const final
Static Public Member Functions
static const FactoryId & GetIdStatic ()
Additional Inherited Members
Public Types inherited from ITensorHandleFactory
using FactoryId = std::string
Static Public Attributes inherited from ITensorHandleFactory
static const FactoryId LegacyFactoryId = "armnn_legacy_factory"
static const FactoryId DeferredFactoryId = "armnn_deferred_factory"
Use the workload factory to create the tensor handle.
Detailed Description
Definition at line 17 of file RefTensorHandleFactory.hpp.
Constructor & Destructor Documentation
RefTensorHandleFactory()
RefTensorHandleFactory (std::shared_ptr< RefMemoryManager > mgr) inline
Definition at line 21 of file RefTensorHandleFactory.hpp.
References RefTensorHandleFactory::CreateSubTensorHandle(), RefTensorHandleFactory::CreateTensorHandle(), RefTensorHandleFactory::GetExportFlags(), RefTensorHandleFactory::GetId(), RefTensorHandleFactory::GetIdStatic(), RefTensorHandleFactory::GetImportFlags(), and RefTensorHandleFactory::SupportsSubTensors().
     : m_MemoryManager(mgr),
       m_ImportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc)),
       m_ExportFlags(static_cast<MemorySourceFlags>(MemorySource::Malloc))
     {}
Member Function Documentation
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const override virtual
Implements ITensorHandleFactory.
Definition at line 22 of file RefTensorHandleFactory.cpp.
References armnn::IgnoreUnused().
Referenced by RefTensorHandleFactory::RefTensorHandleFactory().
 {
     IgnoreUnused(parent, subTensorShape, subTensorOrigin);
     return nullptr;
 }
CreateTensorHandle() [1/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo) const override virtual
Implements ITensorHandleFactory.
Definition at line 30 of file RefTensorHandleFactory.cpp.
Referenced by RefTensorHandleFactory::RefTensorHandleFactory().
 {
     return std::make_unique<RefTensorHandle>(tensorInfo, m_MemoryManager, m_ImportFlags);
 }
CreateTensorHandle() [2/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout) const override virtual
Implements ITensorHandleFactory.
Definition at line 35 of file RefTensorHandleFactory.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(dataLayout);
     return std::make_unique<RefTensorHandle>(tensorInfo, m_MemoryManager, m_ImportFlags);
 }
GetExportFlags()
MemorySourceFlags GetExportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 52 of file RefTensorHandleFactory.cpp.
Referenced by RefTensorHandleFactory::RefTensorHandleFactory().
 {
     return m_ExportFlags;
 }
GetId()
const FactoryId & GetId () const override virtual
Implements ITensorHandleFactory.
Definition at line 42 of file RefTensorHandleFactory.cpp.
References RefTensorHandleFactory::GetIdStatic().
Referenced by RefTensorHandleFactory::RefTensorHandleFactory().
 {
     return GetIdStatic();
 }
GetIdStatic()
const FactoryId & GetIdStatic () static
Definition at line 16 of file RefTensorHandleFactory.cpp.
References armnn::RefTensorHandleFactoryId().
Referenced by RefBackend::GetHandleFactoryPreferences(), RefTensorHandleFactory::GetId(), and RefTensorHandleFactory::RefTensorHandleFactory().
 {
     static const FactoryId s_Id(RefTensorHandleFactoryId());
     return s_Id;
 }
GetImportFlags()
MemorySourceFlags GetImportFlags () const override virtual
Reimplemented from ITensorHandleFactory.
Definition at line 57 of file RefTensorHandleFactory.cpp.
Referenced by RefTensorHandleFactory::RefTensorHandleFactory().
 {
     return m_ImportFlags;
 }
SupportsSubTensors()
bool SupportsSubTensors () const override virtual
Implements ITensorHandleFactory.
Definition at line 47 of file RefTensorHandleFactory.cpp.
Referenced by RefTensorHandleFactory::RefTensorHandleFactory().
 {
     return false;
 }
The documentation for this class was generated from the following files:
src/backends/reference/RefTensorHandleFactory.hpp
src/backends/reference/RefTensorHandleFactory.cpp