ArmNN: TestDepthwiseConvolution2dLayerVisitor Class Reference
TestDepthwiseConvolution2dLayerVisitor Class Reference
#include <ConstTensorLayerVisitor.hpp>
Public Member Functions
TestDepthwiseConvolution2dLayerVisitor (const DepthwiseConvolution2dDescriptor &descriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr)
virtual ~TestDepthwiseConvolution2dLayerVisitor ()
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *layer, const DepthwiseConvolution2dDescriptor &convolution2dDescriptor, const ConstTensor &weights, const Optional< ConstTensor > &biases, const char *name=nullptr) override
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from LayerVisitorBase< VisitorNoThrowPolicy >
void VisitAbsLayer (const IConnectableLayer *, const char *) override
void VisitActivationLayer (const IConnectableLayer *, const ActivationDescriptor &, const char *) override
void VisitAdditionLayer (const IConnectableLayer *, const char *) override
void VisitArgMinMaxLayer (const IConnectableLayer *, const ArgMinMaxDescriptor &, const char *) override
void VisitBatchNormalizationLayer (const IConnectableLayer *, const BatchNormalizationDescriptor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const ConstTensor &, const char *) override
void VisitBatchToSpaceNdLayer (const IConnectableLayer *, const BatchToSpaceNdDescriptor &, const char *) override
void VisitComparisonLayer (const IConnectableLayer *, const ComparisonDescriptor &, const char *) override
void VisitConcatLayer (const IConnectableLayer *, const ConcatDescriptor &, const char *) override
void VisitConstantLayer (const IConnectableLayer *, const ConstTensor &, const char *) override
void VisitConvolution2dLayer (const IConnectableLayer *, const Convolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
void VisitDepthToSpaceLayer (const IConnectableLayer *, const DepthToSpaceDescriptor &, const char *) override
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer *, const DepthwiseConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
void VisitDequantizeLayer (const IConnectableLayer *, const char *) override
void VisitDetectionPostProcessLayer (const IConnectableLayer *, const DetectionPostProcessDescriptor &, const ConstTensor &, const char *) override
void VisitDivisionLayer (const IConnectableLayer *, const char *) override
void VisitElementwiseUnaryLayer (const IConnectableLayer *, const ElementwiseUnaryDescriptor &, const char *) override
void VisitEqualLayer (const IConnectableLayer *, const char *) override
void VisitFloorLayer (const IConnectableLayer *, const char *) override
void VisitFullyConnectedLayer (const IConnectableLayer *, const FullyConnectedDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
void VisitGatherLayer (const IConnectableLayer *, const char *) override
void VisitGreaterLayer (const IConnectableLayer *, const char *) override
void VisitInputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
void VisitInstanceNormalizationLayer (const IConnectableLayer *, const InstanceNormalizationDescriptor &, const char *) override
void VisitL2NormalizationLayer (const IConnectableLayer *, const L2NormalizationDescriptor &, const char *) override
void VisitLogSoftmaxLayer (const IConnectableLayer *, const LogSoftmaxDescriptor &, const char *) override
void VisitLstmLayer (const IConnectableLayer *, const LstmDescriptor &, const LstmInputParams &, const char *) override
void VisitMaximumLayer (const IConnectableLayer *, const char *) override
void VisitMeanLayer (const IConnectableLayer *, const MeanDescriptor &, const char *) override
void VisitMergeLayer (const IConnectableLayer *, const char *) override
void VisitMergerLayer (const IConnectableLayer *, const MergerDescriptor &, const char *) override
void VisitMinimumLayer (const IConnectableLayer *, const char *) override
void VisitMultiplicationLayer (const IConnectableLayer *, const char *) override
void VisitNormalizationLayer (const IConnectableLayer *, const NormalizationDescriptor &, const char *) override
void VisitOutputLayer (const IConnectableLayer *, LayerBindingId, const char *) override
void VisitPadLayer (const IConnectableLayer *, const PadDescriptor &, const char *) override
void VisitPermuteLayer (const IConnectableLayer *, const PermuteDescriptor &, const char *) override
void VisitPooling2dLayer (const IConnectableLayer *, const Pooling2dDescriptor &, const char *) override
void VisitPreluLayer (const IConnectableLayer *, const char *) override
void VisitQuantizeLayer (const IConnectableLayer *, const char *) override
void VisitQuantizedLstmLayer (const IConnectableLayer *, const QuantizedLstmInputParams &, const char *) override
void VisitReshapeLayer (const IConnectableLayer *, const ReshapeDescriptor &, const char *) override
void VisitResizeBilinearLayer (const IConnectableLayer *, const ResizeBilinearDescriptor &, const char *) override
void VisitResizeLayer (const IConnectableLayer *, const ResizeDescriptor &, const char *) override
void VisitRsqrtLayer (const IConnectableLayer *, const char *) override
void VisitSliceLayer (const IConnectableLayer *, const SliceDescriptor &, const char *) override
void VisitSoftmaxLayer (const IConnectableLayer *, const SoftmaxDescriptor &, const char *) override
void VisitSpaceToBatchNdLayer (const IConnectableLayer *, const SpaceToBatchNdDescriptor &, const char *) override
void VisitSpaceToDepthLayer (const IConnectableLayer *, const SpaceToDepthDescriptor &, const char *) override
void VisitSplitterLayer (const IConnectableLayer *, const ViewsDescriptor &, const char *) override
void VisitStackLayer (const IConnectableLayer *, const StackDescriptor &, const char *) override
void VisitStandInLayer (const IConnectableLayer *, const StandInDescriptor &, const char *) override
void VisitStridedSliceLayer (const IConnectableLayer *, const StridedSliceDescriptor &, const char *) override
void VisitSubtractionLayer (const IConnectableLayer *, const char *) override
void VisitSwitchLayer (const IConnectableLayer *, const char *) override
void VisitTransposeConvolution2dLayer (const IConnectableLayer *, const TransposeConvolution2dDescriptor &, const ConstTensor &, const Optional< ConstTensor > &, const char *) override
Public Member Functions inherited from ILayerVisitor
virtual void StartVisit ()
virtual void FinishVisit ()
Protected Member Functions
void CheckDescriptor (const DepthwiseConvolution2dDescriptor &convolution2dDescriptor)
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from LayerVisitorBase< VisitorNoThrowPolicy >
LayerVisitorBase ()
virtual ~LayerVisitorBase ()
Protected Member Functions inherited from ILayerVisitor
ILayerVisitor ()
virtual ~ILayerVisitor ()
Detailed Description
Definition at line 52 of file ConstTensorLayerVisitor.hpp.
Constructor & Destructor Documentation
TestDepthwiseConvolution2dLayerVisitor()
TestDepthwiseConvolution2dLayerVisitor (const DepthwiseConvolution2dDescriptor & descriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) inline explicit
Definition at line 55 of file ConstTensorLayerVisitor.hpp.
         : TestLayerVisitor(name)
         , m_Descriptor(descriptor)
         , m_Weights(weights)
         , m_Biases(biases)
     {}
~TestDepthwiseConvolution2dLayerVisitor()
virtual ~TestDepthwiseConvolution2dLayerVisitor () inline virtual
Definition at line 65 of file ConstTensorLayerVisitor.hpp.
 {}
Member Function Documentation
CheckDescriptor()
void CheckDescriptor (const DepthwiseConvolution2dDescriptor & convolution2dDescriptor) protected
Definition at line 26 of file ConstTensorLayerVisitor.cpp.
References BOOST_CHECK(), Convolution2dDescriptor::m_BiasEnabled, DepthwiseConvolution2dDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_DataLayout, DepthwiseConvolution2dDescriptor::m_DataLayout, Convolution2dDescriptor::m_PadBottom, DepthwiseConvolution2dDescriptor::m_PadBottom, Convolution2dDescriptor::m_PadLeft, DepthwiseConvolution2dDescriptor::m_PadLeft, Convolution2dDescriptor::m_PadRight, DepthwiseConvolution2dDescriptor::m_PadRight, Convolution2dDescriptor::m_PadTop, DepthwiseConvolution2dDescriptor::m_PadTop, Convolution2dDescriptor::m_StrideX, DepthwiseConvolution2dDescriptor::m_StrideX, Convolution2dDescriptor::m_StrideY, and DepthwiseConvolution2dDescriptor::m_StrideY.
 {
     BOOST_CHECK(m_Descriptor.m_PadLeft == convolution2dDescriptor.m_PadLeft);
     BOOST_CHECK(m_Descriptor.m_PadRight == convolution2dDescriptor.m_PadRight);
     BOOST_CHECK(m_Descriptor.m_PadTop == convolution2dDescriptor.m_PadTop);
     BOOST_CHECK(m_Descriptor.m_PadBottom == convolution2dDescriptor.m_PadBottom);
     BOOST_CHECK(m_Descriptor.m_StrideX == convolution2dDescriptor.m_StrideX);
     BOOST_CHECK(m_Descriptor.m_StrideY == convolution2dDescriptor.m_StrideY);
     BOOST_CHECK(m_Descriptor.m_BiasEnabled == convolution2dDescriptor.m_BiasEnabled);
     BOOST_CHECK(m_Descriptor.m_DataLayout == convolution2dDescriptor.m_DataLayout);
 }
VisitDepthwiseConvolution2dLayer()
void VisitDepthwiseConvolution2dLayer (const IConnectableLayer * layer, const DepthwiseConvolution2dDescriptor & convolution2dDescriptor, const ConstTensor & weights, const Optional< ConstTensor > & biases, const char * name = nullptr) inline override virtual
Function that a 2D depthwise convolution layer with biases should call back to when its Accept(ILayerVisitor&) function is invoked.
Parameters
layer - pointer to the layer which is calling back to this visit function.
convolution2dDescriptor - Description of the 2D depthwise convolution layer.
weights - Tensor for the weights. Expected format: [channelMultiplier, inputChannels, height, width].
biases - Optional tensor for the bias data. If specified, must match the output tensor shape.
name - Optional name for the layer.
Implements ILayerVisitor.
Definition at line 67 of file ConstTensorLayerVisitor.hpp.
References TestLayerVisitor::CheckConstTensors(), TestConvolution2dLayerVisitor::CheckDescriptor(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), and TestLayerVisitor::CheckOptionalConstTensors().
     {
         CheckLayerPointer(layer);
         CheckLayerName(name);
         CheckDescriptor(convolution2dDescriptor);
         CheckConstTensors(m_Weights, weights);
         CheckOptionalConstTensors(m_Biases, biases);
     }
The documentation for this class was generated from the following files:
src/armnn/test/ConstTensorLayerVisitor.hpp
src/armnn/test/ConstTensorLayerVisitor.cpp