ArmNN: CsvReader Class Reference
CsvReader Class Reference
#include <CsvReader.hpp>
Static Public Member Functions
static std::vector< CsvRow > ParseFile (const std::string &csvFile)
static std::vector< CsvRow > ParseVector (const std::vector< std::string > &csvVector)
Detailed Description
Definition at line 18 of file CsvReader.hpp.
Member Function Documentation
ParseFile()
std::vector< CsvRow > ParseFile (const std::string & csvFile) static
Definition at line 32 of file CsvReader.cpp.
References armnnUtils::ParseLine().
Referenced by BOOST_FIXTURE_TEST_CASE(), armnnQuantizer::GetFileNameFromCsvRow(), and main().
 {
     std::vector<CsvRow> result;
     std::ifstream in(csvFile.c_str());
     if (!in.is_open())
         return result;
     std::string line;
     while (getline(in, line))
     {
         if(!line.empty())
         {
             CsvRow entry = ParseLine(line);
             result.push_back(entry);
         }
     }
     return result;
 }
ParseVector()
std::vector< CsvRow > ParseVector (const std::vector< std::string > & csvVector) static
Definition at line 52 of file CsvReader.cpp.
References armnnUtils::ParseLine().
Referenced by BOOST_FIXTURE_TEST_CASE().
 {
     std::vector<CsvRow> result;
     for (auto const& line: csvVector)
     {
         CsvRow entry = ParseLine(line);
         result.push_back(entry);
     }
     return result;
 }
The documentation for this class was generated from the following files:
src/armnnUtils/CsvReader.hpp
src/armnnUtils/CsvReader.cpp