ArmNN: ProfilingConnectionDumpToFileDecorator Class Reference
ProfilingConnectionDumpToFileDecorator Class Reference
#include <ProfilingConnectionDumpToFileDecorator.hpp>
Public Member Functions
ProfilingConnectionDumpToFileDecorator (std::unique_ptr< IProfilingConnection > connection, const Runtime::CreationOptions::ExternalProfilingOptions &options, bool ignoreFailures=false)
~ProfilingConnectionDumpToFileDecorator ()
bool IsOpen () const override
void Close () override
bool WritePacket (const unsigned char *buffer, uint32_t length) override
Packet ReadPacket (uint32_t timeout) override
Public Member Functions inherited from IProfilingConnection
virtual ~IProfilingConnection ()
Detailed Description
Definition at line 25 of file ProfilingConnectionDumpToFileDecorator.hpp.
Constructor & Destructor Documentation
ProfilingConnectionDumpToFileDecorator()
ProfilingConnectionDumpToFileDecorator (std::unique_ptr< IProfilingConnection > connection, const Runtime::CreationOptions::ExternalProfilingOptions & options, bool ignoreFailures = false)
Definition at line 20 of file ProfilingConnectionDumpToFileDecorator.cpp.
       : m_Connection(std::move(connection))
       , m_Options(options)
       , m_IgnoreFileErrors(ignoreFailures)
 {
     if (!m_Connection)
     {
         throw InvalidArgumentException("Connection cannot be nullptr");
     }
 }
~ProfilingConnectionDumpToFileDecorator()
~ProfilingConnectionDumpToFileDecorator ()
Definition at line 34 of file ProfilingConnectionDumpToFileDecorator.cpp.
References ProfilingConnectionDumpToFileDecorator::Close().
 {
     Close();
 }
Member Function Documentation
Close()
void Close () override virtual
Implements IProfilingConnection.
Definition at line 44 of file ProfilingConnectionDumpToFileDecorator.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), ProfilingConnectionDumpToFileDecorator::ReadPacket(), and ProfilingConnectionDumpToFileDecorator::~ProfilingConnectionDumpToFileDecorator().
 {
     m_IncomingDumpFileStream.flush();
     m_IncomingDumpFileStream.close();
     m_OutgoingDumpFileStream.flush();
     m_OutgoingDumpFileStream.close();
     m_Connection->Close();
 }
IsOpen()
bool IsOpen () const override virtual
Implements IProfilingConnection.
Definition at line 39 of file ProfilingConnectionDumpToFileDecorator.cpp.
 {
     return m_Connection->IsOpen();
 }
ReadPacket()
Packet ReadPacket (uint32_t timeout) override virtual
Implements IProfilingConnection.
Definition at line 64 of file ProfilingConnectionDumpToFileDecorator.cpp.
References ProfilingConnectionDumpToFileDecorator::Close(), Packet::GetData(), Packet::GetHeader(), and Packet::GetLength().
Referenced by BOOST_AUTO_TEST_CASE().
 {
     Packet packet = m_Connection->ReadPacket(timeout);
     if (!m_Options.m_IncomingCaptureFile.empty())
     {
         DumpIncomingToFile(packet);
     }
     return packet;
 }
WritePacket()
bool WritePacket (const unsigned char * buffer, uint32_t length) override virtual
Implements IProfilingConnection.
Definition at line 53 of file ProfilingConnectionDumpToFileDecorator.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
 {
     bool success = true;
     if (!m_Options.m_OutgoingCaptureFile.empty())
     {
         success &= DumpOutgoingToFile(buffer, length);
     }
     success &= m_Connection->WritePacket(buffer, length);
     return success;
 }
The documentation for this class was generated from the following files:
src/profiling/ProfilingConnectionDumpToFileDecorator.hpp
src/profiling/ProfilingConnectionDumpToFileDecorator.cpp