ArmNN: OptimizedNetwork Class Reference
OptimizedNetwork Class Reference final
#include <Network.hpp>
Public Member Functions
OptimizedNetwork (std::unique_ptr< Graph > graph)
~OptimizedNetwork ()
Status PrintGraph () override
Status SerializeToDot (std::ostream &stream) const override
profiling::ProfilingGuid GetGuid () const final
Graph & GetGraph ()
Additional Inherited Members
Static Public Member Functions inherited from IOptimizedNetwork
static void Destroy (IOptimizedNetwork *network)
Protected Member Functions inherited from IOptimizedNetwork
~IOptimizedNetwork ()
Detailed Description
Definition at line 265 of file Network.hpp.
Constructor & Destructor Documentation
OptimizedNetwork()
OptimizedNetwork (std::unique_ptr< Graph > graph)
Definition at line 1682 of file Network.cpp.
     : m_Graph(std::move(graph)),
       m_Guid(profiling::ProfilingService::Instance().NextGuid())
 {
 }
~OptimizedNetwork()
~OptimizedNetwork ()
Definition at line 1688 of file Network.cpp.
 {
 }
Member Function Documentation
GetGraph()
Graph& GetGraph () inline
Definition at line 276 of file Network.hpp.
Referenced by armnn::ApplyBackendOptimizations(), armnn::AssignBackends(), BOOST_AUTO_TEST_CASE(), and armnn::Optimize().
 { return *m_Graph; }
GetGuid()
profiling::ProfilingGuid GetGuid () const inline final virtual
Implements IOptimizedNetwork.
Definition at line 274 of file Network.hpp.
 { return m_Guid; };
PrintGraph()
Status PrintGraph () override virtual
Implements IOptimizedNetwork.
Definition at line 64 of file Network.cpp.
References armnn::Success.
 {
     m_Graph->Print();
     return Status::Success;
 }
SerializeToDot()
Status SerializeToDot (std::ostream & stream) const override virtual
Implements IOptimizedNetwork.
Definition at line 70 of file Network.cpp.
 {
     return m_Graph->SerializeToDot(stream);
 }
The documentation for this class was generated from the following files:
src/armnn/Network.hpp
src/armnn/Network.cpp