ArmNN: TimelineCaptureCommandHandler Class Reference
TimelineCaptureCommandHandler Class Reference
#include <TimelineCaptureCommandHandler.hpp>
Public Member Functions
TimelineCaptureCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, Model *model, bool quietOperation=false)
void operator() (const armnn::profiling::Packet &packet) override
void ReadLabel (const unsigned char *data, uint32_t offset)
void ReadEntity (const unsigned char *data, uint32_t offset)
void ReadEventClass (const unsigned char *data, uint32_t offset)
void ReadRelationship (const unsigned char *data, uint32_t offset)
void ReadEvent (const unsigned char *data, uint32_t offset)
void print ()
Public Member Functions inherited from CommandHandlerFunctor
CommandHandlerFunctor (uint32_t familyId, uint32_t packetId, uint32_t version)
uint32_t GetFamilyId () const
uint32_t GetPacketId () const
uint32_t GetVersion () const
virtual ~CommandHandlerFunctor ()
Detailed Description
Definition at line 20 of file TimelineCaptureCommandHandler.hpp.
Constructor & Destructor Documentation
TimelineCaptureCommandHandler()
TimelineCaptureCommandHandler (uint32_t familyId, uint32_t packetId, uint32_t version, Model * model, bool quietOperation = false) inline
Definition at line 30 of file TimelineCaptureCommandHandler.hpp.
References TimelineCaptureCommandHandler::operator()(), TimelineCaptureCommandHandler::print(), TimelineCaptureCommandHandler::ReadEntity(), TimelineCaptureCommandHandler::ReadEvent(), TimelineCaptureCommandHandler::ReadEventClass(), TimelineCaptureCommandHandler::ReadLabel(), and TimelineCaptureCommandHandler::ReadRelationship().
             : CommandHandlerFunctor(familyId, packetId, version)
             , m_Model(model)
             , m_QuietOperation(quietOperation)
     {}
Member Function Documentation
operator()()
void operator() (const armnn::profiling::Packet & packet) override virtual
Implements CommandHandlerFunctor.
Definition at line 139 of file TimelineCaptureCommandHandler.cpp.
References armnn::profiling::CentreAlignFormatting(), Model::m_Entities, Model::m_EntityCount, Model::m_EventClassCount, Model::m_EventClasses, Model::m_EventCount, Model::m_Events, Entity::m_Guid, EventClass::m_Guid, Event::m_Guid, Label::m_Guid, Relationship::m_Guid, Relationship::m_HeadGuid, Model::m_LabelCount, Model::m_Labels, Label::m_Name, Model::m_RelationshipCount, Model::m_Relationships, Relationship::m_RelationshipType, Relationship::m_TailGuid, Event::m_ThreadId, and Event::m_TimeStamp.
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     ParseData(packet);
 }
print()
void print ()
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
ReadEntity()
void ReadEntity (const unsigned char * data, uint32_t offset)
Definition at line 69 of file TimelineCaptureCommandHandler.cpp.
References CreateEntity(), Entity::m_Guid, and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     Entity entity;
     entity.m_Guid = profiling::ReadUint64(data, offset);
     CreateEntity(entity, m_Model);
     if (!m_QuietOperation)
     {
         printEntities();
     }
 }
ReadEvent()
void ReadEvent (const unsigned char * data, uint32_t offset)
Definition at line 119 of file TimelineCaptureCommandHandler.cpp.
References CreateEvent(), armnn::profiling::ReadBytes(), and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     Event event;
     event.m_TimeStamp = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     event.m_ThreadId = new uint8_t[threadId_size];
     profiling::ReadBytes(data, offset, threadId_size, event.m_ThreadId);
     offset += threadId_size;
     event.m_Guid = profiling::ReadUint64(data, offset);
     CreateEvent(event, m_Model);
     if (!m_QuietOperation)
     {
         printEvents();
     }
 }
ReadEventClass()
void ReadEventClass (const unsigned char * data, uint32_t offset)
Definition at line 82 of file TimelineCaptureCommandHandler.cpp.
References CreateEventClass(), EventClass::m_Guid, and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     EventClass eventClass;
     eventClass.m_Guid = profiling::ReadUint64(data, offset);
     CreateEventClass(eventClass, m_Model);
     if (!m_QuietOperation)
     {
         printEventClasses();
     }
 }
ReadLabel()
void ReadLabel (const unsigned char * data, uint32_t offset)
Definition at line 46 of file TimelineCaptureCommandHandler.cpp.
References CreateLabel(), Label::m_Guid, Label::m_Name, armnn::profiling::ReadUint32(), armnn::profiling::ReadUint64(), and armnn::profiling::ReadUint8().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     Label label;
     label.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     uint32_t nameLength = profiling::ReadUint32(data, offset);
     offset += uint32_t_size;
     label.m_Name = new char[nameLength];
     for (uint32_t i = 0; i< nameLength; ++i)
     {
         label.m_Name[i] = static_cast<char>(profiling::ReadUint8(data, offset + i));
     }
     CreateLabel(label, m_Model);
     if (!m_QuietOperation)
     {
         printLabels();
     }
 }
ReadRelationship()
void ReadRelationship (const unsigned char * data, uint32_t offset)
Definition at line 95 of file TimelineCaptureCommandHandler.cpp.
References CreateRelationship(), Relationship::m_Guid, Relationship::m_HeadGuid, Relationship::m_RelationshipType, Relationship::m_TailGuid, armnn::profiling::ReadUint32(), and armnn::profiling::ReadUint64().
Referenced by TimelineCaptureCommandHandler::TimelineCaptureCommandHandler().
 {
     Relationship relationship;
     relationship.m_RelationshipType = static_cast<RelationshipType>(profiling::ReadUint32(data, offset));
     offset += uint32_t_size;
     relationship.m_Guid = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     relationship.m_HeadGuid  = profiling::ReadUint64(data, offset);
     offset += uint64_t_size;
     relationship.m_TailGuid = profiling::ReadUint64(data, offset);
     CreateRelationship(relationship, m_Model);
     if (!m_QuietOperation)
     {
         printRelationships();
     }
 }
The documentation for this class was generated from the following files:
tests/profiling/timelineDecoder/TimelineCaptureCommandHandler.hpp
tests/profiling/timelineDecoder/TimelineCaptureCommandHandler.cpp