ArmNN: DivisionLayer Class Reference
DivisionLayer Class Reference
This layer represents a division operation.
#include <DivisionLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
DivisionLayer * Clone (Graph &graph) const override
void Accept (ILayerVisitor &visitor) const override
Public Member Functions inherited from ElementwiseBaseLayer
void ValidateTensorShapesFromInputs () override
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void SerializeLayerParameters (ParameterStringifyFunction &fn) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
unsigned int GetNumInputSlots () const override
unsigned int GetNumOutputSlots () const override
const InputSlot & GetInputSlot (unsigned int index) const override
InputSlot & GetInputSlot (unsigned int index) override
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
OutputSlot & GetOutputSlot (unsigned int index=0) override
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
Protected Member Functions
DivisionLayer (const char *name)
~DivisionLayer ()=default
Default destructor.
Protected Member Functions inherited from ElementwiseBaseLayer
ElementwiseBaseLayer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
~ElementwiseBaseLayer ()=default
Default destructor.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef ()
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::unique_ptr< ScopedCpuTensorHandle > >>
Protected Attributes inherited from Layer
std::vector< OutputHandler > m_OutputHandlers
Detailed Description
This layer represents a division operation.
Definition at line 14 of file DivisionLayer.hpp.
Constructor & Destructor Documentation
DivisionLayer()
DivisionLayer (const char * name) protected
Constructor to create a DivisionLayer.
Parameters
[in] name Optional name for the layer.
Definition at line 17 of file DivisionLayer.cpp.
References armnn::Division.
     : ElementwiseBaseLayer(2, 1, LayerType::Division, name)
 {
 }
~DivisionLayer()
~DivisionLayer () protected default
Default destructor.
Member Function Documentation
Accept()
void Accept (ILayerVisitor & visitor) const override virtual
Implements IConnectableLayer.
Definition at line 33 of file DivisionLayer.cpp.
References Layer::GetName(), and ILayerVisitor::VisitDivisionLayer().
 {
     visitor.VisitDivisionLayer(this, GetName());
 }
Clone()
DivisionLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 28 of file DivisionLayer.cpp.
References Layer::GetName().
 {
     return CloneBase<DivisionLayer>(graph, GetName());
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the Division type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 22 of file DivisionLayer.cpp.
References IWorkloadFactory::CreateDivision(), and Layer::PrepInfoAndDesc().
 {
     DivisionQueueDescriptor descriptor;
     return factory.CreateDivision(descriptor, PrepInfoAndDesc(descriptor));
 }
The documentation for this class was generated from the following files:
src/armnn/layers/DivisionLayer.hpp
src/armnn/layers/DivisionLayer.cpp