ArmNN: ICounterDirectory Class Reference
ICounterDirectory Class Reference abstract
#include <ICounterDirectory.hpp>
Public Member Functions
virtual ~ICounterDirectory ()
virtual uint16_t GetCategoryCount () const =0
virtual uint16_t GetDeviceCount () const =0
virtual uint16_t GetCounterSetCount () const =0
virtual uint16_t GetCounterCount () const =0
virtual const Categories & GetCategories () const =0
virtual const Devices & GetDevices () const =0
virtual const CounterSets & GetCounterSets () const =0
virtual const Counters & GetCounters () const =0
virtual const Category * GetCategory (const std::string &name) const =0
virtual const Device * GetDevice (uint16_t uid) const =0
virtual const CounterSet * GetCounterSet (uint16_t uid) const =0
virtual const Counter * GetCounter (uint16_t uid) const =0
Detailed Description
Definition at line 143 of file ICounterDirectory.hpp.
Constructor & Destructor Documentation
~ICounterDirectory()
virtual ~ICounterDirectory () inline virtual
Definition at line 146 of file ICounterDirectory.hpp.
 {}
Member Function Documentation
GetCategories()
virtual const Categories& GetCategories () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::profiling::PrintCounterDirectory(), SendCounterPacket::SendCounterDirectoryPacket(), and FileOnlyProfilingConnection::WritePacket().
GetCategory()
virtual const Category* GetCategory (const std::string & name) const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE().
GetCategoryCount()
virtual uint16_t GetCategoryCount () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), and SendCounterPacket::SendCounterDirectoryPacket().
GetCounter()
virtual const Counter* GetCounter (uint16_t uid) const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE().
GetCounterCount()
virtual uint16_t GetCounterCount () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE().
GetCounters()
virtual const Counters& GetCounters () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::profiling::PrintCounterDirectory(), and SendCounterPacket::SendCounterDirectoryPacket().
GetCounterSet()
virtual const CounterSet* GetCounterSet (uint16_t uid) const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE().
GetCounterSetCount()
virtual uint16_t GetCounterSetCount () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), and SendCounterPacket::SendCounterDirectoryPacket().
GetCounterSets()
virtual const CounterSets& GetCounterSets () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::profiling::PrintCounterDirectory(), and SendCounterPacket::SendCounterDirectoryPacket().
GetDevice()
virtual const Device* GetDevice (uint16_t uid) const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE().
GetDeviceCount()
virtual uint16_t GetDeviceCount () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), and SendCounterPacket::SendCounterDirectoryPacket().
GetDevices()
virtual const Devices& GetDevices () const pure virtual
Implemented in MockCounterDirectory, and CounterDirectory.
Referenced by BOOST_AUTO_TEST_CASE(), armnn::profiling::PrintCounterDirectory(), and SendCounterPacket::SendCounterDirectoryPacket().
The documentation for this class was generated from the following file:
src/profiling/ICounterDirectory.hpp