ArmNN: RefComparisonWorkload Class Reference
RefComparisonWorkload Class Reference
#include <RefComparisonWorkload.hpp>
Public Member Functions
RefComparisonWorkload (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
void Execute () const override
Public Member Functions inherited from BaseWorkload< ComparisonQueueDescriptor >
BaseWorkload (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info)
void PostAllocationConfigure () override
const ComparisonQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ComparisonQueueDescriptor >
const ComparisonQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 16 of file RefComparisonWorkload.hpp.
Constructor & Destructor Documentation
RefComparisonWorkload()
RefComparisonWorkload (const ComparisonQueueDescriptor & descriptor, const WorkloadInfo & info)
Definition at line 22 of file RefComparisonWorkload.cpp.
     : BaseWorkload<ComparisonQueueDescriptor>(desc, info)
 {}
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 39 of file RefComparisonWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, CHECK_LOCATION, armnn::CpuRef, armnn::Equal, armnn::GetComparisonOperationAsCString(), TensorInfo::GetShape(), armnn::GetTensorInfo(), armnn::Greater, armnn::GreaterOrEqual, armnn::Less, armnn::LessOrEqual, BaseWorkload< ComparisonQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, ComparisonDescriptor::m_Operation, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and armnn::NotEqual.
 {
     ARMNN_SCOPED_PROFILING_EVENT(Compute::CpuRef, "RefComparisonWorkload_Execute");
     const TensorInfo& inputInfo0 = GetTensorInfo(m_Data.m_Inputs[0]);
     const TensorInfo& inputInfo1 = GetTensorInfo(m_Data.m_Inputs[1]);
     const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
     const TensorShape& inShape0 = inputInfo0.GetShape();
     const TensorShape& inShape1 = inputInfo1.GetShape();
     const TensorShape& outShape = outputInfo.GetShape();
     m_Input0->Reset(m_Data.m_Inputs[0]->Map());
     m_Input1->Reset(m_Data.m_Inputs[1]->Map());
     m_Output->Reset(m_Data.m_Outputs[0]->Map());
     using EqualFunction          = ElementwiseBinaryFunction<std::equal_to<InType>>;
     using GreaterFunction        = ElementwiseBinaryFunction<std::greater<InType>>;
     using GreaterOrEqualFunction = ElementwiseBinaryFunction<std::greater_equal<InType>>;
     using LessFunction           = ElementwiseBinaryFunction<std::less<InType>>;
     using LessOrEqualFunction    = ElementwiseBinaryFunction<std::less_equal<InType>>;
     using NotEqualFunction       = ElementwiseBinaryFunction<std::not_equal_to<InType>>;
     switch (m_Data.m_Parameters.m_Operation)
     {
         case ComparisonOperation::Equal:
         {
             EqualFunction(inShape0, inShape1, outShape, *m_Input0, *m_Input1, *m_Output);
             break;
         }
         case ComparisonOperation::Greater:
         {
             GreaterFunction(inShape0, inShape1, outShape, *m_Input0, *m_Input1, *m_Output);
             break;
         }
         case ComparisonOperation::GreaterOrEqual:
         {
             GreaterOrEqualFunction(inShape0, inShape1, outShape, *m_Input0, *m_Input1, *m_Output);
             break;
         }
         case ComparisonOperation::Less:
         {
             LessFunction(inShape0, inShape1, outShape, *m_Input0, *m_Input1, *m_Output);
             break;
         }
         case ComparisonOperation::LessOrEqual:
         {
             LessOrEqualFunction(inShape0, inShape1, outShape, *m_Input0, *m_Input1, *m_Output);
             break;
         }
         case ComparisonOperation::NotEqual:
         {
             NotEqualFunction(inShape0, inShape1, outShape, *m_Input0, *m_Input1, *m_Output);
             break;
         }
         default:
         {
             throw InvalidArgumentException(std::string("Unsupported comparison operation ") +
                 GetComparisonOperationAsCString(m_Data.m_Parameters.m_Operation), CHECK_LOCATION());
         }
     }
 }
PostAllocationConfigure()
void PostAllocationConfigure () override virtual
Implements IWorkload.
Definition at line 27 of file RefComparisonWorkload.cpp.
References armnn::GetTensorInfo(), BaseWorkload< ComparisonQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, and QueueDescriptor::m_Outputs.
 {
     const TensorInfo& inputInfo0 = GetTensorInfo(m_Data.m_Inputs[0]);
     const TensorInfo& inputInfo1 = GetTensorInfo(m_Data.m_Inputs[1]);
     const TensorInfo& outputInfo = GetTensorInfo(m_Data.m_Outputs[0]);
     m_Input0 = MakeDecoder<InType>(inputInfo0);
     m_Input1 = MakeDecoder<InType>(inputInfo1);
     m_Output = MakeEncoder<OutType>(outputInfo);
 }
The documentation for this class was generated from the following files:
src/backends/reference/workloads/RefComparisonWorkload.hpp
src/backends/reference/workloads/RefComparisonWorkload.cpp