ArmNN: armnnUtils::Sockets Namespace Reference
armnnUtils::Sockets Namespace Reference
Functions
bool Initialize ()
Performs any required one-time setup.
int Close (Socket s)
bool SetNonBlocking (Socket s)
long Write (Socket s, const void *buf, size_t len)
long Read (Socket s, void *buf, size_t len)
int Ioctl (Socket s, unsigned long int cmd, void *arg)
int Poll (PollFd *fds, nfds_t numFds, int timeout)
armnnUtils::Sockets::Socket Accept (Socket s, sockaddr *addr, socklen_t *addrlen, int flags)
Function Documentation
Accept()
Socket Accept (Socket s, sockaddr * addr, socklen_t * addrlen, int flags)
Definition at line 91 of file NetworkSockets.cpp.
Referenced by GatordMockService::BlockForOneClient().
 {
 #if defined(__unix__)
     return accept4(s, addr, addrlen, flags);
 #elif defined(_MSC_VER)
     return accept(s, addr, reinterpret_cast<int*>(addrlen));
 #endif
 }
Close()
int Close (Socket s)
Definition at line 28 of file NetworkSockets.cpp.
Referenced by SocketProfilingConnection::Close(), FileOnlyProfilingConnection::FileOnlyProfilingConnection(), GatordMockService::LaunchReceivingThread(), and GatordMockService::~GatordMockService().
 {
 #if defined(__unix__)
     return close(s);
 #elif defined(_MSC_VER)
     return closesocket(s);
 #endif
 }
Initialize()
bool Initialize ()
Performs any required one-time setup.
Definition at line 18 of file NetworkSockets.cpp.
Referenced by GatordMockService::OpenListeningSocket(), and SocketProfilingConnection::SocketProfilingConnection().
 {
 #if defined(__unix__)
     return true;
 #elif defined(_MSC_VER)
     WSADATA wsaData;
     return WSAStartup(MAKEWORD(2, 2), &wsaData) == 0;
 #endif
 }
Ioctl()
int Ioctl (Socket s, unsigned long int cmd, void * arg)
Definition at line 69 of file NetworkSockets.cpp.
Referenced by SocketProfilingConnection::ReadPacket(), and GatordMockService::WaitCommand().
 {
 #if defined(__ANDROID__)
     return ioctl(s, static_cast<int>(cmd), arg);
 #elif defined(__unix__)
     return ioctl(s, cmd, arg);
 #elif defined(_MSC_VER)
     return ioctlsocket(s, cmd, static_cast<u_long*>(arg));
 #endif
 }
Poll()
int Poll (PollFd * fds, nfds_t numFds, int timeout)
Definition at line 81 of file NetworkSockets.cpp.
Referenced by SocketProfilingConnection::ReadPacket(), and GatordMockService::WaitCommand().
 {
 #if defined(__unix__)
     return poll(fds, numFds, timeout);
 #elif defined(_MSC_VER)
     return WSAPoll(fds, numFds, timeout);
 #endif
 }
Read()
long Read (Socket s, void * buf, size_t len)
Definition at line 60 of file NetworkSockets.cpp.
Referenced by SocketProfilingConnection::ReadPacket(), GatordMockService::WaitCommand(), and GatordMockService::WaitForStreamMetaData().
 {
 #if defined(__unix__)
     return read(s, buf, len);
 #elif defined(_MSC_VER)
     return recv(s, static_cast<char*>(buf), len, 0);
 #endif
 }
SetNonBlocking()
bool SetNonBlocking (Socket s)
Definition at line 38 of file NetworkSockets.cpp.
Referenced by GatordMockService::LaunchReceivingThread(), and SocketProfilingConnection::SocketProfilingConnection().
 {
 #if defined(__unix__)
     const int currentFlags = fcntl(s, F_GETFL);
     return fcntl(s, F_SETFL, currentFlags | O_NONBLOCK) == 0;
 #elif defined(_MSC_VER)
     u_long mode = 1;
     return ioctlsocket(s, FIONBIO, &mode) == 0;
 #endif
 }
Write()
long Write (Socket s, const void * buf, size_t len)
Definition at line 50 of file NetworkSockets.cpp.
Referenced by InferenceTestImage::GetSizeInBytes(), GatordMockService::WaitCommand(), and SocketProfilingConnection::WritePacket().
 {
 #if defined(__unix__)
     return write(s, buf, len);
 #elif defined(_MSC_VER)
     return send(s, static_cast<const char*>(buf), len, 0);
 #endif
 }