ArmNN: CategoryRecord Struct Reference
CategoryRecord Struct Reference
#include <CounterDirectory.hpp>
Public Member Functions
void print () const
Public Attributes
uint16_t m_EventCount
std::string m_CategoryName
std::vector< EventRecord > m_EventRecords
Detailed Description
Definition at line 107 of file CounterDirectory.hpp.
Member Function Documentation
print()
void print () const inline
Definition at line 113 of file CounterDirectory.hpp.
References armnn::profiling::CentreAlignFormatting(), EventRecord::printContents(), and EventRecord::printHeader().
Referenced by CounterDirectory::print().
     {
         std::string body;
         std::string header;
         header.append(gatordmock::CentreAlignFormatting("Name", 20));
         header.append(" | ");
         header.append(gatordmock::CentreAlignFormatting("Event Count", 14));
         header.append("\n");
         body.append(gatordmock::CentreAlignFormatting(m_CategoryName, 20));
         body.append(" | ");
         body.append(gatordmock::CentreAlignFormatting(std::to_string(m_EventCount), 14));
         std::cout << "\n" << "\n";
         std::cout << gatordmock::CentreAlignFormatting("CATEGORY", static_cast<int>(header.size()));
         std::cout << "\n";
         std::cout << std::string(header.size(), '=') << "\n";
         std::cout<< header;
         std::cout << std::string(body.size(), '-') << "\n";
         std::cout<< body;
         if(m_EventRecords.size() > 0)
         {
             EventRecord::printHeader(m_CategoryName);
             std::for_each(m_EventRecords.begin(), m_EventRecords.end(), std::mem_fun_ref(&EventRecord::printContents));
         }
     }
Member Data Documentation
m_CategoryName
std::string m_CategoryName
Definition at line 110 of file CounterDirectory.hpp.
m_EventCount
uint16_t m_EventCount
Definition at line 109 of file CounterDirectory.hpp.
m_EventRecords
std::vector<EventRecord> m_EventRecords
Definition at line 111 of file CounterDirectory.hpp.
The documentation for this struct was generated from the following file:
tests/profiling/gatordmock/CounterDirectory.hpp