ArmNN: CounterDirectory Struct Reference
CounterDirectory Struct Reference
#include <CounterDirectory.hpp>
Public Member Functions
void print () const
Public Attributes
std::vector< CategoryRecord > m_Categories
std::vector< CounterSetRecord > m_CounterSets
std::vector< DeviceRecord > m_DeviceRecords
Detailed Description
Definition at line 229 of file CounterDirectory.hpp.
Member Function Documentation
print()
void print () const inline
Definition at line 235 of file CounterDirectory.hpp.
References CategoryRecord::print(), CounterSetRecord::printContents(), DeviceRecord::printContents(), CounterSetRecord::printHeader(), and DeviceRecord::printHeader().
     {
         DeviceRecord::printHeader();
         std::for_each(m_DeviceRecords.begin(), m_DeviceRecords.end(),
                       std::mem_fun_ref(&DeviceRecord::printContents));
         CounterSetRecord::printHeader();
         std::for_each(m_CounterSets.begin(), m_CounterSets.end(),
                       std::mem_fun_ref(&CounterSetRecord::printContents));
         std::for_each(m_Categories.begin(), m_Categories.end(),
                       std::mem_fun_ref(&CategoryRecord::print));
         std::cout << "\n";
     }
Member Data Documentation
m_Categories
std::vector<CategoryRecord> m_Categories
Definition at line 231 of file CounterDirectory.hpp.
m_CounterSets
std::vector<CounterSetRecord> m_CounterSets
Definition at line 232 of file CounterDirectory.hpp.
m_DeviceRecords
std::vector<DeviceRecord> m_DeviceRecords
Definition at line 233 of file CounterDirectory.hpp.
The documentation for this struct was generated from the following file:
tests/profiling/gatordmock/CounterDirectory.hpp