var searchData=
[
  ['rangetracker_5952',['RangeTracker',['../classarmnn_1_1_range_tracker.xhtml',1,'armnn']]],
  ['ranklayer_5953',['RankLayer',['../classarmnn_1_1_rank_layer.xhtml',1,'armnn']]],
  ['rankqueuedescriptor_5954',['RankQueueDescriptor',['../structarmnn_1_1_rank_queue_descriptor.xhtml',1,'armnn']]],
  ['reducedescriptor_5955',['ReduceDescriptor',['../structarmnn_1_1_reduce_descriptor.xhtml',1,'armnn']]],
  ['reducelayer_5956',['ReduceLayer',['../classarmnn_1_1_reduce_layer.xhtml',1,'armnn']]],
  ['reducequeuedescriptor_5957',['ReduceQueueDescriptor',['../structarmnn_1_1_reduce_queue_descriptor.xhtml',1,'armnn']]],
  ['refactivationworkload_5958',['RefActivationWorkload',['../classarmnn_1_1_ref_activation_workload.xhtml',1,'armnn']]],
  ['refargminmaxworkload_5959',['RefArgMinMaxWorkload',['../classarmnn_1_1_ref_arg_min_max_workload.xhtml',1,'armnn']]],
  ['refbackend_5960',['RefBackend',['../classarmnn_1_1_ref_backend.xhtml',1,'armnn']]],
  ['refbaseworkload_5961',['RefBaseWorkload',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20activationqueuedescriptor_20_3e_5962',['RefBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5963',['RefBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5964',['RefBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5965',['RefBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5966',['RefBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20castqueuedescriptor_20_3e_5967',['RefBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5968',['RefBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5969',['RefBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20concatqueuedescriptor_20_3e_5970',['RefBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20constantqueuedescriptor_20_3e_5971',['RefBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5972',['RefBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5973',['RefBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5974',['RefBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5975',['RefBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5976',['RefBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5977',['RefBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20elementwisebinaryqueuedescriptor_20_3e_5978',['RefBaseWorkload&lt; ElementwiseBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5979',['RefBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20fillqueuedescriptor_20_3e_5980',['RefBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20floorqueuedescriptor_20_3e_5981',['RefBaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5982',['RefBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20gatherndqueuedescriptor_20_3e_5983',['RefBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20gatherqueuedescriptor_20_3e_5984',['RefBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5985',['RefBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5986',['RefBaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5987',['RefBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5988',['RefBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20lstmqueuedescriptor_20_3e_5989',['RefBaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20meanqueuedescriptor_20_3e_5990',['RefBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20normalizationqueuedescriptor_20_3e_5991',['RefBaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20padqueuedescriptor_20_3e_5992',['RefBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20parentdescriptor_20_3e_5993',['RefBaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_5994',['RefBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_5995',['RefBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20preluqueuedescriptor_20_3e_5996',['RefBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20qlstmqueuedescriptor_20_3e_5997',['RefBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20quantizequeuedescriptor_20_3e_5998',['RefBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20rankqueuedescriptor_20_3e_5999',['RefBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20reducequeuedescriptor_20_3e_6000',['RefBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20reshapequeuedescriptor_20_3e_6001',['RefBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20resizequeuedescriptor_20_3e_6002',['RefBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20shapequeuedescriptor_20_3e_6003',['RefBaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20slicequeuedescriptor_20_3e_6004',['RefBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20softmaxqueuedescriptor_20_3e_6005',['RefBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_6006',['RefBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_6007',['RefBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20splitterqueuedescriptor_20_3e_6008',['RefBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20stackqueuedescriptor_20_3e_6009',['RefBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_6010',['RefBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_6011',['RefBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_6012',['RefBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_ref_base_workload.xhtml',1,'armnn']]],
  ['refbatchmatmulworkload_6013',['RefBatchMatMulWorkload',['../classarmnn_1_1_ref_batch_mat_mul_workload.xhtml',1,'armnn']]],
  ['refbatchnormalizationworkload_6014',['RefBatchNormalizationWorkload',['../classarmnn_1_1_ref_batch_normalization_workload.xhtml',1,'armnn']]],
  ['refbatchtospacendworkload_6015',['RefBatchToSpaceNdWorkload',['../classarmnn_1_1_ref_batch_to_space_nd_workload.xhtml',1,'armnn']]],
  ['refcastworkload_6016',['RefCastWorkload',['../classarmnn_1_1_ref_cast_workload.xhtml',1,'armnn']]],
  ['refchannelshuffleworkload_6017',['RefChannelShuffleWorkload',['../classarmnn_1_1_ref_channel_shuffle_workload.xhtml',1,'armnn']]],
  ['refcomparisonworkload_6018',['RefComparisonWorkload',['../classarmnn_1_1_ref_comparison_workload.xhtml',1,'armnn']]],
  ['refconcatworkload_6019',['RefConcatWorkload',['../classarmnn_1_1_ref_concat_workload.xhtml',1,'armnn']]],
  ['refconstantworkload_6020',['RefConstantWorkload',['../classarmnn_1_1_ref_constant_workload.xhtml',1,'armnn']]],
  ['refconvertfp16tofp32workload_6021',['RefConvertFp16ToFp32Workload',['../classarmnn_1_1_ref_convert_fp16_to_fp32_workload.xhtml',1,'armnn']]],
  ['refconvertfp32tofp16workload_6022',['RefConvertFp32ToFp16Workload',['../classarmnn_1_1_ref_convert_fp32_to_fp16_workload.xhtml',1,'armnn']]],
  ['refconvolution2dworkload_6023',['RefConvolution2dWorkload',['../classarmnn_1_1_ref_convolution2d_workload.xhtml',1,'armnn']]],
  ['refconvolution3dworkload_6024',['RefConvolution3dWorkload',['../classarmnn_1_1_ref_convolution3d_workload.xhtml',1,'armnn']]],
  ['refdebugworkload_6025',['RefDebugWorkload',['../classarmnn_1_1_ref_debug_workload.xhtml',1,'armnn']]],
  ['refdepthtospaceworkload_6026',['RefDepthToSpaceWorkload',['../classarmnn_1_1_ref_depth_to_space_workload.xhtml',1,'armnn']]],
  ['refdepthwiseconvolution2dworkload_6027',['RefDepthwiseConvolution2dWorkload',['../classarmnn_1_1_ref_depthwise_convolution2d_workload.xhtml',1,'armnn']]],
  ['refdequantizeworkload_6028',['RefDequantizeWorkload',['../classarmnn_1_1_ref_dequantize_workload.xhtml',1,'armnn']]],
  ['refdetectionpostprocessworkload_6029',['RefDetectionPostProcessWorkload',['../classarmnn_1_1_ref_detection_post_process_workload.xhtml',1,'armnn']]],
  ['refelementwisebinaryworkload_6030',['RefElementwiseBinaryWorkload',['../classarmnn_1_1_ref_elementwise_binary_workload.xhtml',1,'armnn']]],
  ['refelementwiseunaryworkload_6031',['RefElementwiseUnaryWorkload',['../classarmnn_1_1_ref_elementwise_unary_workload.xhtml',1,'armnn']]],
  ['refelementwiseworkload_6032',['RefElementwiseWorkload',['../classarmnn_1_1_ref_elementwise_workload.xhtml',1,'armnn']]],
  ['reffakequantizationfloat32workload_6033',['RefFakeQuantizationFloat32Workload',['../classarmnn_1_1_ref_fake_quantization_float32_workload.xhtml',1,'armnn']]],
  ['reffillworkload_6034',['RefFillWorkload',['../classarmnn_1_1_ref_fill_workload.xhtml',1,'armnn']]],
  ['reffloorworkload_6035',['RefFloorWorkload',['../classarmnn_1_1_ref_floor_workload.xhtml',1,'armnn']]],
  ['reffullyconnectedworkload_6036',['RefFullyConnectedWorkload',['../classarmnn_1_1_ref_fully_connected_workload.xhtml',1,'armnn']]],
  ['refgatherndworkload_6037',['RefGatherNdWorkload',['../classarmnn_1_1_ref_gather_nd_workload.xhtml',1,'armnn']]],
  ['refgatherworkload_6038',['RefGatherWorkload',['../classarmnn_1_1_ref_gather_workload.xhtml',1,'armnn']]],
  ['refinstancenormalizationworkload_6039',['RefInstanceNormalizationWorkload',['../classarmnn_1_1_ref_instance_normalization_workload.xhtml',1,'armnn']]],
  ['refl2normalizationworkload_6040',['RefL2NormalizationWorkload',['../classarmnn_1_1_ref_l2_normalization_workload.xhtml',1,'armnn']]],
  ['reflayersupport_6041',['RefLayerSupport',['../classarmnn_1_1_ref_layer_support.xhtml',1,'armnn']]],
  ['reflogicalbinaryworkload_6042',['RefLogicalBinaryWorkload',['../classarmnn_1_1_ref_logical_binary_workload.xhtml',1,'armnn']]],
  ['reflogicalunaryworkload_6043',['RefLogicalUnaryWorkload',['../classarmnn_1_1_ref_logical_unary_workload.xhtml',1,'armnn']]],
  ['reflogsoftmaxworkload_6044',['RefLogSoftmaxWorkload',['../classarmnn_1_1_ref_log_softmax_workload.xhtml',1,'armnn']]],
  ['reflstmworkload_6045',['RefLstmWorkload',['../classarmnn_1_1_ref_lstm_workload.xhtml',1,'armnn']]],
  ['refmeanworkload_6046',['RefMeanWorkload',['../classarmnn_1_1_ref_mean_workload.xhtml',1,'armnn']]],
  ['refmemorymanager_6047',['RefMemoryManager',['../classarmnn_1_1_ref_memory_manager.xhtml',1,'armnn']]],
  ['refnormalizationworkload_6048',['RefNormalizationWorkload',['../classarmnn_1_1_ref_normalization_workload.xhtml',1,'armnn']]],
  ['refpadworkload_6049',['RefPadWorkload',['../classarmnn_1_1_ref_pad_workload.xhtml',1,'armnn']]],
  ['refpermuteworkload_6050',['RefPermuteWorkload',['../classarmnn_1_1_ref_permute_workload.xhtml',1,'armnn']]],
  ['refpooling2dworkload_6051',['RefPooling2dWorkload',['../classarmnn_1_1_ref_pooling2d_workload.xhtml',1,'armnn']]],
  ['refpooling3dworkload_6052',['RefPooling3dWorkload',['../classarmnn_1_1_ref_pooling3d_workload.xhtml',1,'armnn']]],
  ['refpreluworkload_6053',['RefPreluWorkload',['../classarmnn_1_1_ref_prelu_workload.xhtml',1,'armnn']]],
  ['refqlstmworkload_6054',['RefQLstmWorkload',['../classarmnn_1_1_ref_q_lstm_workload.xhtml',1,'armnn']]],
  ['refquantizeworkload_6055',['RefQuantizeWorkload',['../classarmnn_1_1_ref_quantize_workload.xhtml',1,'armnn']]],
  ['refrankworkload_6056',['RefRankWorkload',['../structarmnn_1_1_ref_rank_workload.xhtml',1,'armnn']]],
  ['refreduceworkload_6057',['RefReduceWorkload',['../classarmnn_1_1_ref_reduce_workload.xhtml',1,'armnn']]],
  ['refreshapeworkload_6058',['RefReshapeWorkload',['../classarmnn_1_1_ref_reshape_workload.xhtml',1,'armnn']]],
  ['refresizeworkload_6059',['RefResizeWorkload',['../classarmnn_1_1_ref_resize_workload.xhtml',1,'armnn']]],
  ['refshapeworkload_6060',['RefShapeWorkload',['../structarmnn_1_1_ref_shape_workload.xhtml',1,'armnn']]],
  ['refsliceworkload_6061',['RefSliceWorkload',['../classarmnn_1_1_ref_slice_workload.xhtml',1,'armnn']]],
  ['refsoftmaxworkload_6062',['RefSoftmaxWorkload',['../classarmnn_1_1_ref_softmax_workload.xhtml',1,'armnn']]],
  ['refspacetobatchndworkload_6063',['RefSpaceToBatchNdWorkload',['../classarmnn_1_1_ref_space_to_batch_nd_workload.xhtml',1,'armnn']]],
  ['refspacetodepthworkload_6064',['RefSpaceToDepthWorkload',['../classarmnn_1_1_ref_space_to_depth_workload.xhtml',1,'armnn']]],
  ['refsplitterworkload_6065',['RefSplitterWorkload',['../classarmnn_1_1_ref_splitter_workload.xhtml',1,'armnn']]],
  ['refstackworkload_6066',['RefStackWorkload',['../classarmnn_1_1_ref_stack_workload.xhtml',1,'armnn']]],
  ['refstridedsliceworkload_6067',['RefStridedSliceWorkload',['../classarmnn_1_1_ref_strided_slice_workload.xhtml',1,'armnn']]],
  ['reftensorhandle_6068',['RefTensorHandle',['../classarmnn_1_1_ref_tensor_handle.xhtml',1,'armnn']]],
  ['reftensorhandlefactory_6069',['RefTensorHandleFactory',['../classarmnn_1_1_ref_tensor_handle_factory.xhtml',1,'armnn']]],
  ['reftransposeconvolution2dworkload_6070',['RefTransposeConvolution2dWorkload',['../classarmnn_1_1_ref_transpose_convolution2d_workload.xhtml',1,'armnn']]],
  ['reftransposeworkload_6071',['RefTransposeWorkload',['../classarmnn_1_1_ref_transpose_workload.xhtml',1,'armnn']]],
  ['refunidirectionalsequencelstmworkload_6072',['RefUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_ref_unidirectional_sequence_lstm_workload.xhtml',1,'armnn']]],
  ['refworkloadfactory_6073',['RefWorkloadFactory',['../classarmnn_1_1_ref_workload_factory.xhtml',1,'armnn']]],
  ['reshapedescriptor_6074',['ReshapeDescriptor',['../structarmnn_1_1_reshape_descriptor.xhtml',1,'armnn']]],
  ['reshapelayer_6075',['ReshapeLayer',['../classarmnn_1_1_reshape_layer.xhtml',1,'armnn']]],
  ['reshapequeuedescriptor_6076',['ReshapeQueueDescriptor',['../structarmnn_1_1_reshape_queue_descriptor.xhtml',1,'armnn']]],
  ['resizedescriptor_6077',['ResizeDescriptor',['../structarmnn_1_1_resize_descriptor.xhtml',1,'armnn']]],
  ['resizelayer_6078',['ResizeLayer',['../classarmnn_1_1_resize_layer.xhtml',1,'armnn']]],
  ['resizequeuedescriptor_6079',['ResizeQueueDescriptor',['../structarmnn_1_1_resize_queue_descriptor.xhtml',1,'armnn']]],
  ['resolvetypeimpl_6080',['ResolveTypeImpl',['../structarmnn_1_1_resolve_type_impl.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3abfloat16_20_3e_6081',['ResolveTypeImpl&lt; DataType::BFloat16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_b_float16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aboolean_20_3e_6082',['ResolveTypeImpl&lt; DataType::Boolean &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_boolean_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat16_20_3e_6083',['ResolveTypeImpl&lt; DataType::Float16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3afloat32_20_3e_6084',['ResolveTypeImpl&lt; DataType::Float32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_float32_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymms8_20_3e_6085',['ResolveTypeImpl&lt; DataType::QAsymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_s8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqasymmu8_20_3e_6086',['ResolveTypeImpl&lt; DataType::QAsymmU8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_asymm_u8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms16_20_3e_6087',['ResolveTypeImpl&lt; DataType::QSymmS16 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s16_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3aqsymms8_20_3e_6088',['ResolveTypeImpl&lt; DataType::QSymmS8 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_q_symm_s8_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned32_20_3e_6089',['ResolveTypeImpl&lt; DataType::Signed32 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed32_01_4.xhtml',1,'armnn']]],
  ['resolvetypeimpl_3c_20datatype_3a_3asigned64_20_3e_6090',['ResolveTypeImpl&lt; DataType::Signed64 &gt;',['../structarmnn_1_1_resolve_type_impl_3_01_data_type_1_1_signed64_01_4.xhtml',1,'armnn']]],
  ['rsqrt_6091',['rsqrt',['../structarmnn_1_1rsqrt.xhtml',1,'armnn']]],
  ['rsqrtlayer_6092',['RsqrtLayer',['../classarmnn_1_1_rsqrt_layer.xhtml',1,'armnn']]],
  ['rsqrtqueuedescriptor_6093',['RsqrtQueueDescriptor',['../structarmnn_1_1_rsqrt_queue_descriptor.xhtml',1,'armnn']]],
  ['rule_6094',['Rule',['../structarmnn_1_1_rule.xhtml',1,'armnn']]],
  ['runtimeexception_6095',['RuntimeException',['../classarmnn_1_1_runtime_exception.xhtml',1,'armnn']]],
  ['runtimeimpl_6096',['RuntimeImpl',['../structarmnn_1_1_runtime_impl.xhtml',1,'armnn']]]
];
