var searchData=
[
  ['qasymm8decoder_5879',['QASymm8Decoder',['../classarmnn_1_1_q_a_symm8_decoder.xhtml',1,'armnn']]],
  ['qasymm8encoder_5880',['QASymm8Encoder',['../classarmnn_1_1_q_a_symm8_encoder.xhtml',1,'armnn']]],
  ['qasymms8decoder_5881',['QASymmS8Decoder',['../classarmnn_1_1_q_a_symm_s8_decoder.xhtml',1,'armnn']]],
  ['qasymms8encoder_5882',['QASymmS8Encoder',['../classarmnn_1_1_q_a_symm_s8_encoder.xhtml',1,'armnn']]],
  ['qlstmbasicparameters_5883',['QLstmBasicParameters',['../structarmnn_1_1_q_lstm_basic_parameters.xhtml',1,'armnn']]],
  ['qlstmdescriptor_5884',['QLstmDescriptor',['../structarmnn_1_1_q_lstm_descriptor.xhtml',1,'armnn']]],
  ['qlstmlayer_5885',['QLstmLayer',['../classarmnn_1_1_q_lstm_layer.xhtml',1,'armnn']]],
  ['qlstmoptcifgparameters_5886',['QLstmOptCifgParameters',['../structarmnn_1_1_q_lstm_opt_cifg_parameters.xhtml',1,'armnn']]],
  ['qlstmoptlayernormparameters_5887',['QLstmOptLayerNormParameters',['../structarmnn_1_1_q_lstm_opt_layer_norm_parameters.xhtml',1,'armnn']]],
  ['qlstmoptpeepholeparameters_5888',['QLstmOptPeepholeParameters',['../structarmnn_1_1_q_lstm_opt_peephole_parameters.xhtml',1,'armnn']]],
  ['qlstmoptprojectionparameters_5889',['QLstmOptProjectionParameters',['../structarmnn_1_1_q_lstm_opt_projection_parameters.xhtml',1,'armnn']]],
  ['qlstmqueuedescriptor_5890',['QLstmQueueDescriptor',['../structarmnn_1_1_q_lstm_queue_descriptor.xhtml',1,'armnn']]],
  ['qsymm16decoder_5891',['QSymm16Decoder',['../classarmnn_1_1_q_symm16_decoder.xhtml',1,'armnn']]],
  ['qsymm16encoder_5892',['QSymm16Encoder',['../classarmnn_1_1_q_symm16_encoder.xhtml',1,'armnn']]],
  ['qsymm8peraxisdecoder_5893',['QSymm8PerAxisDecoder',['../classarmnn_1_1_q_symm8_per_axis_decoder.xhtml',1,'armnn']]],
  ['qsymm8peraxisencoder_5894',['QSymm8PerAxisEncoder',['../classarmnn_1_1_q_symm8_per_axis_encoder.xhtml',1,'armnn']]],
  ['qsymms8decoder_5895',['QSymmS8Decoder',['../classarmnn_1_1_q_symm_s8_decoder.xhtml',1,'armnn']]],
  ['qsymms8encoder_5896',['QSymmS8Encoder',['../classarmnn_1_1_q_symm_s8_encoder.xhtml',1,'armnn']]],
  ['quantizationparametersareequal_5897',['QuantizationParametersAreEqual',['../structarmnn_1_1_quantization_parameters_are_equal.xhtml',1,'armnn']]],
  ['quantizedlstminputparams_5898',['QuantizedLstmInputParams',['../structarmnn_1_1_quantized_lstm_input_params.xhtml',1,'armnn']]],
  ['quantizedlstminputparamsinfo_5899',['QuantizedLstmInputParamsInfo',['../structarmnn_1_1_quantized_lstm_input_params_info.xhtml',1,'armnn']]],
  ['quantizedlstmlayer_5900',['QuantizedLstmLayer',['../classarmnn_1_1_quantized_lstm_layer.xhtml',1,'armnn']]],
  ['quantizedlstmparameters_5901',['QuantizedLstmParameters',['../structarmnn_1_1_quantized_lstm_parameters.xhtml',1,'armnn']]],
  ['quantizedlstmqueuedescriptor_5902',['QuantizedLstmQueueDescriptor',['../structarmnn_1_1_quantized_lstm_queue_descriptor.xhtml',1,'armnn']]],
  ['quantizedmultipliersmallerthanone_5903',['QuantizedMultiplierSmallerThanOne',['../structarmnn_1_1_quantized_multiplier_smaller_than_one.xhtml',1,'armnn']]],
  ['quantizelayer_5904',['QuantizeLayer',['../classarmnn_1_1_quantize_layer.xhtml',1,'armnn']]],
  ['quantizequeuedescriptor_5905',['QuantizeQueueDescriptor',['../structarmnn_1_1_quantize_queue_descriptor.xhtml',1,'armnn']]],
  ['queuedescriptor_5906',['QueueDescriptor',['../structarmnn_1_1_queue_descriptor.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_5907',['QueueDescriptorWithParameters',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20activationdescriptor_20_3e_5908',['QueueDescriptorWithParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20argminmaxdescriptor_20_3e_5909',['QueueDescriptorWithParameters&lt; ArgMinMaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchmatmuldescriptor_20_3e_5910',['QueueDescriptorWithParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchnormalizationdescriptor_20_3e_5911',['QueueDescriptorWithParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20batchtospacenddescriptor_20_3e_5912',['QueueDescriptorWithParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20channelshuffledescriptor_20_3e_5913',['QueueDescriptorWithParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20comparisondescriptor_20_3e_5914',['QueueDescriptorWithParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution2ddescriptor_20_3e_5915',['QueueDescriptorWithParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20convolution3ddescriptor_20_3e_5916',['QueueDescriptorWithParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthtospacedescriptor_20_3e_5917',['QueueDescriptorWithParameters&lt; DepthToSpaceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_5918',['QueueDescriptorWithParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20detectionpostprocessdescriptor_20_3e_5919',['QueueDescriptorWithParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwisebinarydescriptor_20_3e_5920',['QueueDescriptorWithParameters&lt; ElementwiseBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20elementwiseunarydescriptor_20_3e_5921',['QueueDescriptorWithParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fakequantizationdescriptor_20_3e_5922',['QueueDescriptorWithParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20filldescriptor_20_3e_5923',['QueueDescriptorWithParameters&lt; FillDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20fullyconnecteddescriptor_20_3e_5924',['QueueDescriptorWithParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20gatherdescriptor_20_3e_5925',['QueueDescriptorWithParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20instancenormalizationdescriptor_20_3e_5926',['QueueDescriptorWithParameters&lt; InstanceNormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20l2normalizationdescriptor_20_3e_5927',['QueueDescriptorWithParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logicalbinarydescriptor_20_3e_5928',['QueueDescriptorWithParameters&lt; LogicalBinaryDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20logsoftmaxdescriptor_20_3e_5929',['QueueDescriptorWithParameters&lt; LogSoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20lstmdescriptor_20_3e_5930',['QueueDescriptorWithParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20meandescriptor_20_3e_5931',['QueueDescriptorWithParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20normalizationdescriptor_20_3e_5932',['QueueDescriptorWithParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20originsdescriptor_20_3e_5933',['QueueDescriptorWithParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20paddescriptor_20_3e_5934',['QueueDescriptorWithParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20permutedescriptor_20_3e_5935',['QueueDescriptorWithParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling2ddescriptor_20_3e_5936',['QueueDescriptorWithParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20pooling3ddescriptor_20_3e_5937',['QueueDescriptorWithParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20precompileddescriptor_20_3e_5938',['QueueDescriptorWithParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20qlstmdescriptor_20_3e_5939',['QueueDescriptorWithParameters&lt; QLstmDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reducedescriptor_20_3e_5940',['QueueDescriptorWithParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20reshapedescriptor_20_3e_5941',['QueueDescriptorWithParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20resizedescriptor_20_3e_5942',['QueueDescriptorWithParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20slicedescriptor_20_3e_5943',['QueueDescriptorWithParameters&lt; SliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20softmaxdescriptor_20_3e_5944',['QueueDescriptorWithParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetobatchnddescriptor_20_3e_5945',['QueueDescriptorWithParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20spacetodepthdescriptor_20_3e_5946',['QueueDescriptorWithParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stackdescriptor_20_3e_5947',['QueueDescriptorWithParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20stridedslicedescriptor_20_3e_5948',['QueueDescriptorWithParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposeconvolution2ddescriptor_20_3e_5949',['QueueDescriptorWithParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20transposedescriptor_20_3e_5950',['QueueDescriptorWithParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]],
  ['queuedescriptorwithparameters_3c_20viewsdescriptor_20_3e_5951',['QueueDescriptorWithParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_queue_descriptor_with_parameters.xhtml',1,'armnn']]]
];
