var searchData=
[
  ['onnxparserimpl_5791',['OnnxParserImpl',['../classarmnn_onnx_parser_1_1_onnx_parser_impl.xhtml',1,'armnnOnnxParser']]],
  ['opencltimer_5792',['OpenClTimer',['../classarmnn_1_1_open_cl_timer.xhtml',1,'armnn']]],
  ['optimization_5793',['Optimization',['../classarmnn_1_1_optimization.xhtml',1,'armnn']]],
  ['optimizationresult_5794',['OptimizationResult',['../structarmnn_1_1_optimization_result.xhtml',1,'armnn']]],
  ['optimizationviews_5795',['OptimizationViews',['../classarmnn_1_1_optimization_views.xhtml',1,'armnn']]],
  ['optimizeconsecutivereshapesimpl_5796',['OptimizeConsecutiveReshapesImpl',['../classarmnn_1_1optimizations_1_1_optimize_consecutive_reshapes_impl.xhtml',1,'armnn::optimizations']]],
  ['optimizednetworkimpl_5797',['OptimizedNetworkImpl',['../classarmnn_1_1_optimized_network_impl.xhtml',1,'armnn']]],
  ['optimizeforconnection_5798',['OptimizeForConnection',['../classarmnn_1_1_optimize_for_connection.xhtml',1,'armnn']]],
  ['optimizeforconnectionimpl_5799',['OptimizeForConnectionImpl',['../classarmnn_1_1_optimize_for_connection_impl.xhtml',1,'armnn']]],
  ['optimizeforexclusiveconnection_5800',['OptimizeForExclusiveConnection',['../classarmnn_1_1_optimize_for_exclusive_connection.xhtml',1,'armnn']]],
  ['optimizeforexclusiveconnectionimpl_5801',['OptimizeForExclusiveConnectionImpl',['../classarmnn_1_1_optimize_for_exclusive_connection_impl.xhtml',1,'armnn']]],
  ['optimizefortype_5802',['OptimizeForType',['../classarmnn_1_1_optimize_for_type.xhtml',1,'armnn']]],
  ['optimizefortypeimpl_5803',['OptimizeForTypeImpl',['../classarmnn_1_1_optimize_for_type_impl.xhtml',1,'armnn']]],
  ['optimizefortypeimpl_3c_20basetype_2c_20optimizeforconnectionimpl_3c_20basetype_2c_20childtype_2c_20wrapped_20_3e_20_3e_5804',['OptimizeForTypeImpl&lt; BaseType, OptimizeForConnectionImpl&lt; BaseType, ChildType, Wrapped &gt; &gt;',['../classarmnn_1_1_optimize_for_type_impl.xhtml',1,'armnn']]],
  ['optimizefortypeimpl_3c_20basetype_2c_20optimizeforexclusiveconnectionimpl_3c_20basetype_2c_20childtype_2c_20wrapped_20_3e_20_3e_5805',['OptimizeForTypeImpl&lt; BaseType, OptimizeForExclusiveConnectionImpl&lt; BaseType, ChildType, Wrapped &gt; &gt;',['../classarmnn_1_1_optimize_for_type_impl.xhtml',1,'armnn']]],
  ['optimizefortypeimpl_3c_20layer_2c_20wrapped_20_3e_5806',['OptimizeForTypeImpl&lt; Layer, Wrapped &gt;',['../classarmnn_1_1_optimize_for_type_impl_3_01_layer_00_01_wrapped_01_4.xhtml',1,'armnn']]],
  ['optimizeinverseconversionsimpl_5807',['OptimizeInverseConversionsImpl',['../classarmnn_1_1optimizations_1_1_optimize_inverse_conversions_impl.xhtml',1,'armnn::optimizations']]],
  ['optimizeinversepermutesimpl_5808',['OptimizeInversePermutesImpl',['../classarmnn_1_1optimizations_1_1_optimize_inverse_permutes_impl.xhtml',1,'armnn::optimizations']]],
  ['optimizer_5809',['Optimizer',['../classarmnn_1_1_optimizer.xhtml',1,'armnn']]],
  ['optimizeroptions_5810',['OptimizerOptions',['../structarmnn_1_1_optimizer_options.xhtml',1,'armnn']]],
  ['optimizeroptionsopaque_5811',['OptimizerOptionsOpaque',['../classarmnn_1_1_optimizer_options_opaque.xhtml',1,'armnn']]],
  ['optimizeroptionsopaqueimpl_5812',['OptimizerOptionsOpaqueImpl',['../structarmnn_1_1_optimizer_options_opaque_impl.xhtml',1,'armnn']]],
  ['optional_5813',['Optional',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_5814',['Optional&lt; arm::pipe::IProfilingService &amp; &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_5815',['Optional&lt; arm::pipe::ProfilingGuid &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20armnn_3a_3abackendid_20_3e_5816',['Optional&lt; armnn::BackendId &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20armnn_3a_3atensorinfo_20_3e_5817',['Optional&lt; armnn::TensorInfo &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_5818',['Optional&lt; armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20int32_5ft_20_3e_5819',['Optional&lt; int32_t &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20std_3a_3astring_20_26_20_3e_5820',['Optional&lt; std::string &amp; &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20std_3a_3astring_20_3e_5821',['Optional&lt; std::string &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_5822',['Optional&lt; std::vector&lt; armnn::MemoryInfo &gt; &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optional_3c_20unsigned_20int_20_3e_5823',['Optional&lt; unsigned int &gt;',['../classarmnn_1_1_optional.xhtml',1,'armnn']]],
  ['optionalbase_5824',['OptionalBase',['../classarmnn_1_1_optional_base.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_5825',['OptionalReferenceSwitch',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_3a_3avalue_2c_20arm_3a_3apipe_3a_3aiprofilingservice_20_26_20_3e_5826',['OptionalReferenceSwitch&lt; std::is_reference&lt; arm::pipe::IProfilingService &amp; &gt;::value, arm::pipe::IProfilingService &amp; &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_3a_3avalue_2c_20arm_3a_3apipe_3a_3aprofilingguid_20_3e_5827',['OptionalReferenceSwitch&lt; std::is_reference&lt; arm::pipe::ProfilingGuid &gt;::value, arm::pipe::ProfilingGuid &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20armnn_3a_3abackendid_20_3e_3a_3avalue_2c_20armnn_3a_3abackendid_20_3e_5828',['OptionalReferenceSwitch&lt; std::is_reference&lt; armnn::BackendId &gt;::value, armnn::BackendId &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20armnn_3a_3atensorinfo_20_3e_3a_3avalue_2c_20armnn_3a_3atensorinfo_20_3e_5829',['OptionalReferenceSwitch&lt; std::is_reference&lt; armnn::TensorInfo &gt;::value, armnn::TensorInfo &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_3a_3avalue_2c_20armnntfliteparser_3a_3aitfliteparser_3a_3atfliteparseroptions_20_3e_5830',['OptionalReferenceSwitch&lt; std::is_reference&lt; armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;::value, armnnTfLiteParser::ITfLiteParser::TfLiteParserOptions &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20int32_5ft_20_3e_3a_3avalue_2c_20int32_5ft_20_3e_5831',['OptionalReferenceSwitch&lt; std::is_reference&lt; int32_t &gt;::value, int32_t &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20std_3a_3astring_20_26_20_3e_3a_3avalue_2c_20std_3a_3astring_20_26_20_3e_5832',['OptionalReferenceSwitch&lt; std::is_reference&lt; std::string &amp; &gt;::value, std::string &amp; &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20std_3a_3astring_20_3e_3a_3avalue_2c_20std_3a_3astring_20_3e_5833',['OptionalReferenceSwitch&lt; std::is_reference&lt; std::string &gt;::value, std::string &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_3a_3avalue_2c_20std_3a_3avector_3c_20armnn_3a_3amemoryinfo_20_3e_20_3e_5834',['OptionalReferenceSwitch&lt; std::is_reference&lt; std::vector&lt; armnn::MemoryInfo &gt; &gt;::value, std::vector&lt; armnn::MemoryInfo &gt; &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20t_20_3e_3a_3avalue_2c_20t_20_3e_5835',['OptionalReferenceSwitch&lt; std::is_reference&lt; T &gt;::value, T &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20std_3a_3ais_5freference_3c_20unsigned_20int_20_3e_3a_3avalue_2c_20unsigned_20int_20_3e_5836',['OptionalReferenceSwitch&lt; std::is_reference&lt; unsigned int &gt;::value, unsigned int &gt;',['../classarmnn_1_1_optional_reference_switch.xhtml',1,'armnn']]],
  ['optionalreferenceswitch_3c_20true_2c_20t_20_3e_5837',['OptionalReferenceSwitch&lt; true, T &gt;',['../classarmnn_1_1_optional_reference_switch_3_01true_00_01_t_01_4.xhtml',1,'armnn']]],
  ['originsdescriptor_5838',['OriginsDescriptor',['../structarmnn_1_1_origins_descriptor.xhtml',1,'armnn']]],
  ['outputhandler_5839',['OutputHandler',['../classarmnn_1_1_output_handler.xhtml',1,'armnn']]],
  ['outputlayer_5840',['OutputLayer',['../classarmnn_1_1_output_layer.xhtml',1,'armnn']]],
  ['outputlayersaccessor_5841',['OutputLayersAccessor',['../structarmnn_1_1_graph_1_1_output_layers_accessor.xhtml',1,'armnn::Graph']]],
  ['outputmemdescriptorcoords_5842',['OutputMemDescriptorCoords',['../structarmnn_1_1experimental_1_1_working_mem_handle_1_1_output_mem_descriptor_coords.xhtml',1,'armnn::experimental::WorkingMemHandle']]],
  ['outputslot_5843',['OutputSlot',['../classarmnn_1_1_output_slot.xhtml',1,'armnn']]]
];
