var searchData=
[
  ['sampledynamicadditionworkload_6097',['SampleDynamicAdditionWorkload',['../classsdb_1_1_sample_dynamic_addition_workload.xhtml',1,'sdb']]],
  ['sampledynamiclayersupport_6098',['SampleDynamicLayerSupport',['../classsdb_1_1_sample_dynamic_layer_support.xhtml',1,'sdb']]],
  ['sampledynamictensorhandlefactory_6099',['SampleDynamicTensorHandleFactory',['../classsdb_1_1_sample_dynamic_tensor_handle_factory.xhtml',1,'sdb']]],
  ['sampledynamicworkloadfactory_6100',['SampleDynamicWorkloadFactory',['../classsdb_1_1_sample_dynamic_workload_factory.xhtml',1,'sdb']]],
  ['samplememorymanager_6101',['SampleMemoryManager',['../classsdb_1_1_sample_memory_manager.xhtml',1,'sdb']]],
  ['sampletensorhandle_6102',['SampleTensorHandle',['../classsdb_1_1_sample_tensor_handle.xhtml',1,'sdb']]],
  ['scaledint32decoder_6103',['ScaledInt32Decoder',['../classarmnn_1_1_scaled_int32_decoder.xhtml',1,'armnn']]],
  ['scaledint32peraxisdecoder_6104',['ScaledInt32PerAxisDecoder',['../classarmnn_1_1_scaled_int32_per_axis_decoder.xhtml',1,'armnn']]],
  ['scopedprofilingevent_6105',['ScopedProfilingEvent',['../classarmnn_1_1_scoped_profiling_event.xhtml',1,'armnn']]],
  ['scopedrecord_6106',['ScopedRecord',['../structarmnn_1_1_scoped_record.xhtml',1,'armnn']]],
  ['scopedtensorhandle_6107',['ScopedTensorHandle',['../classarmnn_1_1_scoped_tensor_handle.xhtml',1,'armnn']]],
  ['selectivequantizer_6108',['SelectiveQuantizer',['../structarmnn_utils_1_1_selective_quantizer.xhtml',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3abfloat16_2c_20false_20_3e_6109',['SelectiveQuantizer&lt; armnn::BFloat16, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_b_float16_00_01false_01_4.xhtml',1,'armnnUtils']]],
  ['selectivequantizer_3c_20armnn_3a_3ahalf_2c_20false_20_3e_6110',['SelectiveQuantizer&lt; armnn::Half, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01armnn_1_1_half_00_01false_01_4.xhtml',1,'armnnUtils']]],
  ['selectivequantizer_3c_20t_2c_20false_20_3e_6111',['SelectiveQuantizer&lt; T, false &gt;',['../structarmnn_utils_1_1_selective_quantizer_3_01_t_00_01false_01_4.xhtml',1,'armnnUtils']]],
  ['serializerimpl_6112',['SerializerImpl',['../classarmnn_serializer_1_1_i_serializer_1_1_serializer_impl.xhtml',1,'armnnSerializer::ISerializer']]],
  ['serializerstrategy_6113',['SerializerStrategy',['../classarmnn_serializer_1_1_serializer_strategy.xhtml',1,'armnnSerializer']]],
  ['shapelayer_6114',['ShapeLayer',['../classarmnn_1_1_shape_layer.xhtml',1,'armnn']]],
  ['shapequeuedescriptor_6115',['ShapeQueueDescriptor',['../structarmnn_1_1_shape_queue_descriptor.xhtml',1,'armnn']]],
  ['shapesarebroadcastcompatible_6116',['ShapesAreBroadcastCompatible',['../structarmnn_1_1_shapes_are_broadcast_compatible.xhtml',1,'armnn']]],
  ['shapesaresamerank_6117',['ShapesAreSameRank',['../structarmnn_1_1_shapes_are_same_rank.xhtml',1,'armnn']]],
  ['shapesaresametotalsize_6118',['ShapesAreSameTotalSize',['../structarmnn_1_1_shapes_are_same_total_size.xhtml',1,'armnn']]],
  ['simplelogger_6119',['SimpleLogger',['../classarmnn_1_1_simple_logger.xhtml',1,'armnn']]],
  ['sin_6120',['sin',['../structarmnn_1_1sin.xhtml',1,'armnn']]],
  ['singleaxisprioritylist_6121',['SingleAxisPriorityList',['../classarmnn_1_1_single_axis_priority_list.xhtml',1,'armnn']]],
  ['slicedescriptor_6122',['SliceDescriptor',['../structarmnn_1_1_slice_descriptor.xhtml',1,'armnn']]],
  ['slicelayer_6123',['SliceLayer',['../classarmnn_1_1_slice_layer.xhtml',1,'armnn']]],
  ['slicequeuedescriptor_6124',['SliceQueueDescriptor',['../structarmnn_1_1_slice_queue_descriptor.xhtml',1,'armnn']]],
  ['softmaxdescriptor_6125',['SoftmaxDescriptor',['../structarmnn_1_1_softmax_descriptor.xhtml',1,'armnn']]],
  ['softmaxlayer_6126',['SoftmaxLayer',['../classarmnn_1_1_softmax_layer.xhtml',1,'armnn']]],
  ['softmaxqueuedescriptor_6127',['SoftmaxQueueDescriptor',['../structarmnn_1_1_softmax_queue_descriptor.xhtml',1,'armnn']]],
  ['spacetobatchnddescriptor_6128',['SpaceToBatchNdDescriptor',['../structarmnn_1_1_space_to_batch_nd_descriptor.xhtml',1,'armnn']]],
  ['spacetobatchndlayer_6129',['SpaceToBatchNdLayer',['../classarmnn_1_1_space_to_batch_nd_layer.xhtml',1,'armnn']]],
  ['spacetobatchndqueuedescriptor_6130',['SpaceToBatchNdQueueDescriptor',['../structarmnn_1_1_space_to_batch_nd_queue_descriptor.xhtml',1,'armnn']]],
  ['spacetodepthdescriptor_6131',['SpaceToDepthDescriptor',['../structarmnn_1_1_space_to_depth_descriptor.xhtml',1,'armnn']]],
  ['spacetodepthlayer_6132',['SpaceToDepthLayer',['../classarmnn_1_1_space_to_depth_layer.xhtml',1,'armnn']]],
  ['spacetodepthqueuedescriptor_6133',['SpaceToDepthQueueDescriptor',['../structarmnn_1_1_space_to_depth_queue_descriptor.xhtml',1,'armnn']]],
  ['splitterlayer_6134',['SplitterLayer',['../classarmnn_1_1_splitter_layer.xhtml',1,'armnn']]],
  ['splitterqueuedescriptor_6135',['SplitterQueueDescriptor',['../structarmnn_1_1_splitter_queue_descriptor.xhtml',1,'armnn']]],
  ['sqrt_6136',['sqrt',['../structarmnn_1_1sqrt.xhtml',1,'armnn']]],
  ['squashequalsiblingsimpl_6137',['SquashEqualSiblingsImpl',['../classarmnn_1_1optimizations_1_1_squash_equal_siblings_impl.xhtml',1,'armnn::optimizations']]],
  ['stackdescriptor_6138',['StackDescriptor',['../structarmnn_1_1_stack_descriptor.xhtml',1,'armnn']]],
  ['stacklayer_6139',['StackLayer',['../classarmnn_1_1_stack_layer.xhtml',1,'armnn']]],
  ['stackqueuedescriptor_6140',['StackQueueDescriptor',['../structarmnn_1_1_stack_queue_descriptor.xhtml',1,'armnn']]],
  ['standardoutputsink_6141',['StandardOutputSink',['../classarmnn_1_1_standard_output_sink.xhtml',1,'armnn']]],
  ['standindescriptor_6142',['StandInDescriptor',['../structarmnn_1_1_stand_in_descriptor.xhtml',1,'armnn']]],
  ['standinlayer_6143',['StandInLayer',['../classarmnn_1_1_stand_in_layer.xhtml',1,'armnn']]],
  ['staticregistryinitializer_6144',['StaticRegistryInitializer',['../structarmnn_1_1_backend_registry_1_1_static_registry_initializer.xhtml',1,'armnn::BackendRegistry']]],
  ['strategybase_6145',['StrategyBase',['../classarmnn_1_1_strategy_base.xhtml',1,'armnn']]],
  ['strategyfactory_6146',['StrategyFactory',['../structarmnn_1_1_strategy_factory.xhtml',1,'armnn']]],
  ['strategyvalidator_6147',['StrategyValidator',['../classarmnn_1_1_strategy_validator.xhtml',1,'armnn']]],
  ['stridedslicedescriptor_6148',['StridedSliceDescriptor',['../structarmnn_1_1_strided_slice_descriptor.xhtml',1,'armnn']]],
  ['stridedslicelayer_6149',['StridedSliceLayer',['../classarmnn_1_1_strided_slice_layer.xhtml',1,'armnn']]],
  ['stridedslicequeuedescriptor_6150',['StridedSliceQueueDescriptor',['../structarmnn_1_1_strided_slice_queue_descriptor.xhtml',1,'armnn']]],
  ['stringifylayerparameters_6151',['StringifyLayerParameters',['../structarmnn_1_1_stringify_layer_parameters.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20activationdescriptor_20_3e_6152',['StringifyLayerParameters&lt; ActivationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_activation_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchmatmuldescriptor_20_3e_6153',['StringifyLayerParameters&lt; BatchMatMulDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_mat_mul_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchnormalizationdescriptor_20_3e_6154',['StringifyLayerParameters&lt; BatchNormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_normalization_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20batchtospacenddescriptor_20_3e_6155',['StringifyLayerParameters&lt; BatchToSpaceNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_batch_to_space_nd_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20channelshuffledescriptor_20_3e_6156',['StringifyLayerParameters&lt; ChannelShuffleDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_channel_shuffle_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20comparisondescriptor_20_3e_6157',['StringifyLayerParameters&lt; ComparisonDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_comparison_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution2ddescriptor_20_3e_6158',['StringifyLayerParameters&lt; Convolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution2d_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20convolution3ddescriptor_20_3e_6159',['StringifyLayerParameters&lt; Convolution3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_convolution3d_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20depthwiseconvolution2ddescriptor_20_3e_6160',['StringifyLayerParameters&lt; DepthwiseConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_depthwise_convolution2d_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20detectionpostprocessdescriptor_20_3e_6161',['StringifyLayerParameters&lt; DetectionPostProcessDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_detection_post_process_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20elementwiseunarydescriptor_20_3e_6162',['StringifyLayerParameters&lt; ElementwiseUnaryDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_elementwise_unary_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20fakequantizationdescriptor_20_3e_6163',['StringifyLayerParameters&lt; FakeQuantizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fake_quantization_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20fullyconnecteddescriptor_20_3e_6164',['StringifyLayerParameters&lt; FullyConnectedDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_fully_connected_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20gatherdescriptor_20_3e_6165',['StringifyLayerParameters&lt; GatherDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_gather_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20l2normalizationdescriptor_20_3e_6166',['StringifyLayerParameters&lt; L2NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_l2_normalization_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20lstmdescriptor_20_3e_6167',['StringifyLayerParameters&lt; LstmDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_lstm_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20meandescriptor_20_3e_6168',['StringifyLayerParameters&lt; MeanDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_mean_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20normalizationdescriptor_20_3e_6169',['StringifyLayerParameters&lt; NormalizationDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_normalization_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20originsdescriptor_20_3e_6170',['StringifyLayerParameters&lt; OriginsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_origins_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20paddescriptor_20_3e_6171',['StringifyLayerParameters&lt; PadDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pad_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20permutedescriptor_20_3e_6172',['StringifyLayerParameters&lt; PermuteDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_permute_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling2ddescriptor_20_3e_6173',['StringifyLayerParameters&lt; Pooling2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling2d_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20pooling3ddescriptor_20_3e_6174',['StringifyLayerParameters&lt; Pooling3dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pooling3d_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20precompileddescriptor_20_3e_6175',['StringifyLayerParameters&lt; PreCompiledDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_pre_compiled_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20reducedescriptor_20_3e_6176',['StringifyLayerParameters&lt; ReduceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reduce_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20reshapedescriptor_20_3e_6177',['StringifyLayerParameters&lt; ReshapeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_reshape_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20resizedescriptor_20_3e_6178',['StringifyLayerParameters&lt; ResizeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_resize_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20softmaxdescriptor_20_3e_6179',['StringifyLayerParameters&lt; SoftmaxDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_softmax_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetobatchnddescriptor_20_3e_6180',['StringifyLayerParameters&lt; SpaceToBatchNdDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_batch_nd_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20spacetodepthdescriptor_20_3e_6181',['StringifyLayerParameters&lt; SpaceToDepthDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_space_to_depth_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20stackdescriptor_20_3e_6182',['StringifyLayerParameters&lt; StackDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_stack_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20stridedslicedescriptor_20_3e_6183',['StringifyLayerParameters&lt; StridedSliceDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_strided_slice_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposeconvolution2ddescriptor_20_3e_6184',['StringifyLayerParameters&lt; TransposeConvolution2dDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_convolution2d_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20transposedescriptor_20_3e_6185',['StringifyLayerParameters&lt; TransposeDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_transpose_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringifylayerparameters_3c_20viewsdescriptor_20_3e_6186',['StringifyLayerParameters&lt; ViewsDescriptor &gt;',['../structarmnn_1_1_stringify_layer_parameters_3_01_views_descriptor_01_4.xhtml',1,'armnn']]],
  ['stringmapping_6187',['StringMapping',['../structarmnn_1_1_string_mapping.xhtml',1,'armnn']]],
  ['subgraphview_6188',['SubgraphView',['../classarmnn_1_1_subgraph_view.xhtml',1,'armnn']]],
  ['subgraphviewselector_6189',['SubgraphViewSelector',['../classarmnn_1_1_subgraph_view_selector.xhtml',1,'armnn']]],
  ['substitutionpair_6190',['SubstitutionPair',['../structarmnn_1_1_optimization_views_1_1_substitution_pair.xhtml',1,'armnn::OptimizationViews']]],
  ['subtractionlayer_6191',['SubtractionLayer',['../classarmnn_1_1_subtraction_layer.xhtml',1,'armnn']]],
  ['subtractionqueuedescriptor_6192',['SubtractionQueueDescriptor',['../structarmnn_1_1_subtraction_queue_descriptor.xhtml',1,'armnn']]],
  ['switchlayer_6193',['SwitchLayer',['../classarmnn_1_1_switch_layer.xhtml',1,'armnn']]],
  ['switchqueuedescriptor_6194',['SwitchQueueDescriptor',['../structarmnn_1_1_switch_queue_descriptor.xhtml',1,'armnn']]],
  ['syncmemgenericworkload_6195',['SyncMemGenericWorkload',['../classarmnn_1_1_sync_mem_generic_workload.xhtml',1,'armnn']]]
];
