ArmNN: src/backends/backendsCommon/test/layerTests/BatchNormalizationTestImpl.hpp File Reference
BatchNormalizationTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <Half.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > BatchNormFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > BatchNormFloat32NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > BatchNormFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > BatchNormFloat16NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > BatchNormUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< uint8_t, 4 > BatchNormUint8NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > BatchNormInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< int16_t, 4 > BatchNormInt16NhwcTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > CompareBatchNormTest (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, armnn::IWorkloadFactory &refWorkloadFactory, const armnn::ITensorHandleFactory &tensorHandleFactory, const armnn::ITensorHandleFactory &refTensorHandleFactory)
Function Documentation
BatchNormFloat16NhwcTest()
LayerTestResult<armnn::Half, 4> BatchNormFloat16NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 362 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NHWC);
 }
BatchNormFloat16Test()
LayerTestResult<armnn::Half, 4> BatchNormFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 314 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NCHW);
 }
BatchNormFloat32NhwcTest()
LayerTestResult<float, 4> BatchNormFloat32NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 262 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NHWC);
 }
BatchNormFloat32Test()
LayerTestResult<float, 4> BatchNormFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 214 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::Float32>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         0.f,
         0,
         armnn::DataLayout::NCHW);
 }
BatchNormInt16NhwcTest()
LayerTestResult<int16_t, 4> BatchNormInt16NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 558 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         1.f / 20.f,
         50,
         armnn::DataLayout::NHWC);
 }
BatchNormInt16Test()
LayerTestResult<int16_t, 4> BatchNormInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 510 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QSymmS16>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         1.f / 20.f,
         50,
         armnn::DataLayout::NCHW);
 }
BatchNormUint8NhwcTest()
LayerTestResult<uint8_t, 4> BatchNormUint8NhwcTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 462 of file BatchNormalizationTestImpl.cpp.
References armnn::NHWC.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Height: 3
     // Width: 2
     // Channels: 2
     const armnn::TensorShape inputOutputShape{ 1, 3, 2, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f,  1.f,
         4.f,  1.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f,  4.f,
         2.f,  1.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, -2.f,
         6.f,  4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Height 0, Width (2) x Channel (2)
         1.f, 3.f,
         4.f, 3.f,
         // Batch 0, Height 1, Width (2) x Channel (2)
         4.f, 4.f,
         2.f, 3.f,
         // Batch 0, Height 2, Width (2) x Channel (2)
         1.f, 2.f,
         6.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape, inputValues, expectedOutputValues,
          1.f/20.f, 50, armnn::DataLayout::NHWC);
 }
BatchNormUint8Test()
LayerTestResult<uint8_t, 4> BatchNormUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 414 of file BatchNormalizationTestImpl.cpp.
References armnn::NCHW.
Referenced by TEST_SUITE().
 {
     // BatchSize: 1
     // Channels: 2
     // Height: 3
     // Width: 2
     const armnn::TensorShape inputOutputShape{ 1, 2, 3, 2 };
     std::vector<float> inputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
          1.f, 4.f,
          4.f, 2.f,
          1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
          1.f, 1.f,
          4.f, 1.f,
         -2.f, 4.f
     };
     std::vector<float> expectedOutputValues
     {
         // Batch 0, Channel 0, Height (3) x Width (2)
         1.f, 4.f,
         4.f, 2.f,
         1.f, 6.f,
         // Batch 0, Channel 1, Height (3) x Width (2)
         3.f, 3.f,
         4.f, 3.f,
         2.f, 4.f
     };
     return BatchNormTestImpl<armnn::DataType::QAsymmU8>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputOutputShape,
         inputValues,
         expectedOutputValues,
         1.f / 20.f,
         50,
         armnn::DataLayout::NCHW);
 }
CompareBatchNormTest()
LayerTestResult<float, 4> CompareBatchNormTest (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, armnn::IWorkloadFactory & refWorkloadFactory, const armnn::ITensorHandleFactory & tensorHandleFactory, const armnn::ITensorHandleFactory & refTensorHandleFactory)
Definition at line 610 of file BatchNormalizationTestImpl.cpp.
References AllocateAndCopyDataToITensorHandle(), CopyDataFromITensorHandle(), CopyDataToITensorHandle(), IWorkloadFactory::CreateBatchNormalization(), ITensorHandleFactory::CreateTensorHandle(), armnn::Float32, TensorInfo::GetNumElements(), TensorInfo::GetShape(), armnn::IgnoreUnused(), BatchNormalizationQueueDescriptor::m_Beta, BatchNormalizationDescriptor::m_Eps, BatchNormalizationQueueDescriptor::m_Gamma, BatchNormalizationQueueDescriptor::m_Mean, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and BatchNormalizationQueueDescriptor::m_Variance.
Referenced by TEST_SUITE().
 {
     IgnoreUnused(memoryManager);
     const unsigned int width     = 2;
     const unsigned int height    = 3;
     const unsigned int channels  = 5;
     const unsigned int batchSize = 3;
     armnn::TensorInfo inputTensorInfo;
     armnn::TensorInfo outputTensorInfo;
     armnn::TensorInfo tensorInfo;
     constexpr unsigned int shape[]       = {batchSize, channels, height, width};
     constexpr unsigned int tensorShape[] = {channels};
     inputTensorInfo = armnn::TensorInfo(4, shape, armnn::DataType::Float32);
     outputTensorInfo = armnn::TensorInfo(4, shape, armnn::DataType::Float32);
     tensorInfo = armnn::TensorInfo(1, tensorShape, armnn::DataType::Float32);
     auto input = MakeRandomTensor<float>(inputTensorInfo, 21312);
     auto mean     = MakeRandomTensor<float>(tensorInfo, 123);
     auto variance = MakeRandomTensor<float>(tensorInfo, 234, 0.0f);
     auto beta     = MakeRandomTensor<float>(tensorInfo, 123);
     auto gamma    = MakeRandomTensor<float>(tensorInfo, 345);
     std::vector<float> actualOutput(outputTensorInfo.GetNumElements());
     std::vector<float> expectedOutput(outputTensorInfo.GetNumElements());
     std::unique_ptr<armnn::ITensorHandle> inputHandle  = tensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandle = tensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> inputHandleRef  = refTensorHandleFactory.CreateTensorHandle(inputTensorInfo);
     std::unique_ptr<armnn::ITensorHandle> outputHandleRef = refTensorHandleFactory.CreateTensorHandle(outputTensorInfo);
     armnn::BatchNormalizationQueueDescriptor data;
     armnn::WorkloadInfo info;
     armnn::ScopedTensorHandle meanTensor(tensorInfo);
     armnn::ScopedTensorHandle varianceTensor(tensorInfo);
     armnn::ScopedTensorHandle betaTensor(tensorInfo);
     armnn::ScopedTensorHandle gammaTensor(tensorInfo);
     AllocateAndCopyDataToITensorHandle(&meanTensor, &mean[0]);
     AllocateAndCopyDataToITensorHandle(&varianceTensor, &variance[0]);
     AllocateAndCopyDataToITensorHandle(&betaTensor, &beta[0]);
     AllocateAndCopyDataToITensorHandle(&gammaTensor, &gamma[0]);
     AddInputToWorkload(data, info, inputTensorInfo, inputHandle.get());
     AddOutputToWorkload(data, info, outputTensorInfo, outputHandle.get());
     data.m_Mean             = &meanTensor;
     data.m_Variance         = &varianceTensor;
     data.m_Beta             = &betaTensor;
     data.m_Gamma            = &gammaTensor;
     data.m_Parameters.m_Eps = 0.01f;
     armnn::BatchNormalizationQueueDescriptor refData = data;
     armnn::WorkloadInfo refInfo = info;
     SetWorkloadInput(refData, refInfo, 0, inputTensorInfo, inputHandleRef.get());
     SetWorkloadOutput(refData, refInfo, 0, outputTensorInfo, outputHandleRef.get());
     std::unique_ptr<armnn::IWorkload> workload = workloadFactory.CreateBatchNormalization(data, info);
     std::unique_ptr<armnn::IWorkload> workloadRef = refWorkloadFactory.CreateBatchNormalization(refData, refInfo);
     inputHandle->Allocate();
     outputHandle->Allocate();
     inputHandleRef->Allocate();
     outputHandleRef->Allocate();
     CopyDataToITensorHandle(inputHandle.get(), input.data());
     CopyDataToITensorHandle(inputHandleRef.get(), input.data());
     workload->PostAllocationConfigure();
     workload->Execute();
     workloadRef->PostAllocationConfigure();
     workloadRef->Execute();
     CopyDataFromITensorHandle(actualOutput.data(), outputHandle.get());
     CopyDataFromITensorHandle(expectedOutput.data(), outputHandleRef.get());
     return LayerTestResult<float, 4>(actualOutput,
                                      expectedOutput,
                                      outputHandle->GetShape(),
                                      outputTensorInfo.GetShape());
 }