ArmNN: src/backends/backendsCommon/test/layerTests/DequantizeTestImpl.hpp File Reference
DequantizeTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
#include <Half.hpp>
Functions
LayerTestResult< float, 4 > DequantizeSimpleUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > DequantizeOffsetUint8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > DequantizeSimpleAsymmInt8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > DequantizeOffsetAsymmInt8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > DequantizeSimpleInt8Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< float, 4 > DequantizeSimpleInt16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > DequantizeSimpleUint8ToFp16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > DequantizeSimpleInt8ToFp16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
LayerTestResult< armnn::Half, 4 > DequantizeSimpleInt16ToFp16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager)
Function Documentation
DequantizeOffsetAsymmInt8Test()
LayerTestResult<float, 4> DequantizeOffsetAsymmInt8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 156 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeOffsetTest<armnn::DataType::QAsymmS8>(workloadFactory, memoryManager);
 }
DequantizeOffsetUint8Test()
LayerTestResult<float, 4> DequantizeOffsetUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 142 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeOffsetTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
DequantizeSimpleAsymmInt8Test()
LayerTestResult<float, 4> DequantizeSimpleAsymmInt8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 149 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QAsymmS8>(workloadFactory, memoryManager);
 }
DequantizeSimpleInt16Test()
LayerTestResult<float, 4> DequantizeSimpleInt16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 170 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QSymmS16>(workloadFactory, memoryManager);
 }
DequantizeSimpleInt16ToFp16Test()
LayerTestResult<armnn::Half, 4> DequantizeSimpleInt16ToFp16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 192 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QSymmS16, armnn::DataType::Float16>(workloadFactory,
                                                                                             memoryManager);
 }
DequantizeSimpleInt8Test()
LayerTestResult<float, 4> DequantizeSimpleInt8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 163 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QSymmS8>(workloadFactory, memoryManager);
 }
DequantizeSimpleInt8ToFp16Test()
LayerTestResult<armnn::Half, 4> DequantizeSimpleInt8ToFp16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 185 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QSymmS8, armnn::DataType::Float16>(workloadFactory, memoryManager);
 }
DequantizeSimpleUint8Test()
LayerTestResult<float, 4> DequantizeSimpleUint8Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 135 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QAsymmU8>(workloadFactory, memoryManager);
 }
DequantizeSimpleUint8ToFp16Test()
LayerTestResult<armnn::Half, 4> DequantizeSimpleUint8ToFp16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager)
Definition at line 177 of file DequantizeTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return DequantizeSimpleTest<armnn::DataType::QAsymmU8, armnn::DataType::Float16>(workloadFactory,
                                                                                             memoryManager);
 }