ArmNN: tests/InferenceTestImage.hpp File Reference
InferenceTestImage.hpp File Reference
#include <armnn/Exceptions.hpp>
#include <VerificationHelpers.hpp>
#include <array>
#include <cstdint>
#include <vector>
#include <utility>
Classes
class InferenceTestImageException
class InferenceTestImageLoadFailed
class InferenceTestImageOutOfBoundsAccess
class InferenceTestImageResizeFailed
class InferenceTestImageWriteFailed
class UnknownImageChannelLayout
class InferenceTestImage
Enumerations
enum ImageChannel { R, G, B }
enum ImageChannelLayout { Rgb, Bgr }
Functions
std::vector< float > GetImageDataInArmNnLayoutAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage &image)
std::vector< float > GetImageDataInArmNnLayoutAsFloatsSubtractingMean (ImageChannelLayout layout, const InferenceTestImage &image, const std::array< float, 3 > &mean)
std::vector< float > GetImageDataAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage &image)
Enumeration Type Documentation
ImageChannel
enum ImageChannel strong
Enumerator
R
G
B
Definition at line 113 of file InferenceTestImage.hpp.
 {
     R,
     G,
     B
 };
ImageChannelLayout
enum ImageChannelLayout strong
Enumerator
Rgb
Bgr
Definition at line 121 of file InferenceTestImage.hpp.
 {
     Rgb,
     Bgr
 };
Function Documentation
GetImageDataAsNormalizedFloats()
std::vector<float> GetImageDataAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage & image)
Definition at line 333 of file InferenceTestImage.cpp.
References B, G, InferenceTestImage::GetHeight(), InferenceTestImage::GetPixelAs3Channels(), InferenceTestImage::GetWidth(), and R.
 {
     std::vector<float> imageData;
     const unsigned int h = image.GetHeight();
     const unsigned int w = image.GetWidth();
     const unsigned int rDstIndex = GetImageChannelIndex(layout, ImageChannel::R);
     const unsigned int gDstIndex = GetImageChannelIndex(layout, ImageChannel::G);
     const unsigned int bDstIndex = GetImageChannelIndex(layout, ImageChannel::B);
     imageData.resize(h * w * 3);
     unsigned int offset = 0;
     for (unsigned int j = 0; j < h; ++j)
     {
         for (unsigned int i = 0; i < w; ++i)
         {
             uint8_t r, g, b;
             std::tie(r, g, b) = image.GetPixelAs3Channels(i, j);
             imageData[offset+rDstIndex] = float(r) / 255.0f;
             imageData[offset+gDstIndex] = float(g) / 255.0f;
             imageData[offset+bDstIndex] = float(b) / 255.0f;
             offset += 3;
         }
     }
     return imageData;
 }
GetImageDataInArmNnLayoutAsFloatsSubtractingMean()
std::vector<float> GetImageDataInArmNnLayoutAsFloatsSubtractingMean (ImageChannelLayout layout, const InferenceTestImage & image, const std::array< float, 3 > & mean)
Definition at line 321 of file InferenceTestImage.cpp.
References GetImageDataInArmNnLayoutAsFloats().
 {
     return GetImageDataInArmNnLayoutAsFloats(layout, image,
         [layout, &mean](ImageChannel channel, float value)
         {
             const unsigned int channelIndex = GetImageChannelIndex(layout, channel);
             return value - mean[channelIndex];
         });
 }
GetImageDataInArmNnLayoutAsNormalizedFloats()
std::vector<float> GetImageDataInArmNnLayoutAsNormalizedFloats (ImageChannelLayout layout, const InferenceTestImage & image)
Definition at line 310 of file InferenceTestImage.cpp.
References GetImageDataInArmNnLayoutAsFloats(), and armnn::IgnoreUnused().
Referenced by YoloDatabase::GetTestCaseData().
 {
     return GetImageDataInArmNnLayoutAsFloats(layout, image,
         [](ImageChannel channel, float value)
         {
             armnn::IgnoreUnused(channel);
             return value / 255.f;
         });
 }