ArmNN: src/backends/backendsCommon/test/layerTests/StackTestImpl.hpp File Reference
StackTestImpl.hpp File Reference
#include "LayerTestResult.hpp"
#include <Half.hpp>
#include <armnn/backends/IBackendInternal.hpp>
#include <backendsCommon/WorkloadFactory.hpp>
Functions
LayerTestResult< float, 4 > StackAxis0Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackOutput4DAxis1Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackOutput4DAxis2Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 4 > StackOutput4DAxis3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 3 > StackOutput3DInputs3Float32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< float, 5 > StackOutput5DFloat32Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
LayerTestResult< armnn::Half, 4 > StackFloat16Test (armnn::IWorkloadFactory &workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr &memoryManager, const armnn::ITensorHandleFactory &tensorHandleFactory)
Function Documentation
StackAxis0Float32Test()
LayerTestResult<float, 4> StackAxis0Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 519 of file StackTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StackAxis0TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackFloat16Test()
LayerTestResult<armnn::Half, 4> StackFloat16Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 567 of file StackTestImpl.cpp.
References armnn::Float16.
Referenced by TEST_SUITE().
 {
     using namespace half_float::literal;
     armnn::TensorInfo inputTensorInfo ({ 3, 2, 3 }, armnn::DataType::Float16);
     armnn::TensorInfo outputTensorInfo({ 3, 2, 2, 3 }, armnn::DataType::Float16);
     std::vector<std::vector<armnn::Half>> inputData;
     inputData.push_back(
     {
         1.0_h,  2.0_h,  3.0_h,
         4.0_h,  5.0_h,  6.0_h,
         7.0_h,  8.0_h,  9.0_h,
         10.0_h, 11.0_h, 12.0_h,
         13.0_h, 14.0_h, 15.0_h,
         16.0_h, 17.0_h, 18.0_h
     });
     inputData.push_back(
     {
         19.0_h, 20.0_h, 21.0_h,
         22.0_h, 23.0_h, 24.0_h,
         25.0_h, 26.0_h, 27.0_h,
         28.0_h, 29.0_h, 30.0_h,
         31.0_h, 32.0_h, 33.0_h,
         34.0_h, 35.0_h, 36.0_h
     });
     std::vector<armnn::Half> outputExpectedData =
     {
         1.0_h,  2.0_h,  3.0_h,
         19.0_h, 20.0_h, 21.0_h,
         4.0_h,  5.0_h,  6.0_h,
         22.0_h, 23.0_h, 24.0_h,
         7.0_h,  8.0_h,  9.0_h,
         25.0_h, 26.0_h, 27.0_h,
         10.0_h, 11.0_h, 12.0_h,
         28.0_h, 29.0_h, 30.0_h,
         13.0_h, 14.0_h, 15.0_h,
         31.0_h, 32.0_h, 33.0_h,
         16.0_h, 17.0_h, 18.0_h,
         34.0_h, 35.0_h, 36.0_h
     };
     return StackTestHelper<armnn::DataType::Float16, armnn::Half, 4>(
         workloadFactory,
         memoryManager,
         tensorHandleFactory,
         inputTensorInfo,
         outputTensorInfo,
         2U,
         inputData,
         outputExpectedData
     );
 }
StackOutput3DInputs3Float32Test()
LayerTestResult<float, 3> StackOutput3DInputs3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 551 of file StackTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StackOutput3DInputs3TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput4DAxis1Float32Test()
LayerTestResult<float, 4> StackOutput4DAxis1Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 527 of file StackTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StackOutput4DAxis1TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput4DAxis2Float32Test()
LayerTestResult<float, 4> StackOutput4DAxis2Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 535 of file StackTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StackOutput4DAxis2TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput4DAxis3Float32Test()
LayerTestResult<float, 4> StackOutput4DAxis3Float32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 543 of file StackTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StackOutput4DAxis3TestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }
StackOutput5DFloat32Test()
LayerTestResult<float, 5> StackOutput5DFloat32Test (armnn::IWorkloadFactory & workloadFactory, const armnn::IBackendInternal::IMemoryManagerSharedPtr & memoryManager, const armnn::ITensorHandleFactory & tensorHandleFactory)
Definition at line 559 of file StackTestImpl.cpp.
Referenced by TEST_SUITE().
 {
     return StackOutput5DTestImpl<armnn::DataType::Float32>(workloadFactory, memoryManager, tensorHandleFactory);
 }