ArmNN: TestOutputLayerVisitor Class Reference
TestOutputLayerVisitor Class Reference
#include <TestInputOutputLayerVisitor.hpp>
Public Member Functions
TestOutputLayerVisitor (LayerBindingId id, const char *name=nullptr)
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Additional Inherited Members
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckConstTensors (const ConstTensor &expected, const ConstTensorHandle &actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const ConstTensor *actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const std::shared_ptr< ConstTensorHandle > actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from StrategyBase< NoThrowStrategy >
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Protected Attributes inherited from StrategyBase< NoThrowStrategy >
NoThrowStrategy m_DefaultStrategy
Detailed Description
Definition at line 54 of file TestInputOutputLayerVisitor.hpp.
Constructor & Destructor Documentation
TestOutputLayerVisitor()
TestOutputLayerVisitor (LayerBindingId id, const char * name = nullptr) inline explicit
Definition at line 60 of file TestInputOutputLayerVisitor.hpp.
         : TestLayerVisitor(name)
         , visitorId(id)
     {};
Member Function Documentation
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Reimplemented from StrategyBase< NoThrowStrategy >.
Definition at line 65 of file TestInputOutputLayerVisitor.hpp.
References NoThrowStrategy::Apply(), armnn::CheckLayerBindingId(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), StrategyBase< NoThrowStrategy >::m_DefaultStrategy, and armnn::Output.
     {
         armnn::IgnoreUnused(descriptor, constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::Output:
             {
                 CheckLayerPointer(layer);
                 CheckLayerBindingId(visitorId, id);
                 CheckLayerName(name);
                 break;
             }
             default:
             {
                 m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
             }
         }
     }
The documentation for this class was generated from the following file:
src/armnn/test/TestInputOutputLayerVisitor.hpp