ArmNN: IReadOnlyPacketBuffer Class Reference
IReadOnlyPacketBuffer Class Reference abstract
#include <IPacketBuffer.hpp>
Public Member Functions
virtual ~IReadOnlyPacketBuffer ()
virtual const unsigned char * GetReadableData () const =0
virtual unsigned int GetSize () const =0
virtual void MarkRead ()=0
Detailed Description
Definition at line 16 of file IPacketBuffer.hpp.
Constructor & Destructor Documentation
~IReadOnlyPacketBuffer()
virtual ~IReadOnlyPacketBuffer () inline virtual
Definition at line 19 of file IPacketBuffer.hpp.
References IReadOnlyPacketBuffer::GetReadableData(), IReadOnlyPacketBuffer::GetSize(), and IReadOnlyPacketBuffer::MarkRead().
 {}
Member Function Documentation
GetReadableData()
virtual const unsigned char* GetReadableData () const pure virtual
Implemented in MockPacketBuffer, and PacketBuffer.
Referenced by IReadOnlyPacketBuffer::~IReadOnlyPacketBuffer().
GetSize()
virtual unsigned int GetSize () const pure virtual
Implemented in MockPacketBuffer, and PacketBuffer.
Referenced by IReadOnlyPacketBuffer::~IReadOnlyPacketBuffer().
MarkRead()
virtual void MarkRead () pure virtual
Implemented in MockPacketBuffer, and PacketBuffer.
Referenced by IReadOnlyPacketBuffer::~IReadOnlyPacketBuffer().
The documentation for this class was generated from the following file:
src/profiling/IPacketBuffer.hpp