ArmNN: ClWorkloadFactory Class Reference
ClWorkloadFactory Class Reference
#include <ClWorkloadFactory.hpp>
Public Member Functions
ClWorkloadFactory (const std::shared_ptr< ClMemoryManager > &memoryManager)
ClWorkloadFactory (const std::shared_ptr< ClMemoryManager > &memoryManager, const IBackendInternal::IBackendSpecificModelContextPtr &modelContextPtr)
void AfterWorkloadsCreated () override
const BackendId & GetBackendId () const override
bool SupportsSubTensors () const override
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle &parent, TensorShape const &subTensorShape, unsigned int const *subTensorOrigin) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, const bool IsMemoryManaged=true) const override
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo &tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged=true) const override
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateCast (const CastQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateChannelShuffle (const ChannelShuffleQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateConvolution3d (const Convolution3dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFill (const FillQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLogicalBinary (const LogicalBinaryQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor &descriptor, const WorkloadInfo &Info) const override
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateRank (const RankQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateReduce (const ReduceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor &descriptor, const WorkloadInfo &info) const override
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor &descriptor, const WorkloadInfo &info) const override
Public Member Functions inherited from WorkloadFactoryBase
std::unique_ptr< IWorkload > CreateFakeQuantization (const FakeQuantizationQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateMerge (const MergeQueueDescriptor &, const WorkloadInfo &) const override
std::unique_ptr< IWorkload > CreateSwitch (const SwitchQueueDescriptor &, const WorkloadInfo &) const override
Public Member Functions inherited from IWorkloadFactory
virtual ~IWorkloadFactory ()
virtual std::unique_ptr< IWorkload > CreateConvertBf16ToFp32 (const ConvertBf16ToFp32QueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateConvertFp32ToBf16 (const ConvertFp32ToBf16QueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateLogicalUnary (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &Info) const
virtual std::unique_ptr< IWorkload > CreateShape (const ShapeQueueDescriptor &descriptor, const WorkloadInfo &info) const
virtual std::unique_ptr< IWorkload > CreateUnidirectionalSequenceLstm (const UnidirectionalSequenceLstmQueueDescriptor &descriptor, const WorkloadInfo &info) const
Static Public Member Functions
static bool IsLayerSupported (const Layer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Static Public Member Functions inherited from IWorkloadFactory
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported)
static bool IsLayerSupported (const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
static bool IsLayerSupported (const BackendId &backendId, const IConnectableLayer &layer, Optional< DataType > dataType, std::string &outReasonIfUnsupported, const ModelOptions &modelOptions)
Detailed Description
Definition at line 21 of file ClWorkloadFactory.hpp.
Constructor & Destructor Documentation
ClWorkloadFactory() [1/2]
ClWorkloadFactory (const std::shared_ptr< ClMemoryManager > & memoryManager)
Definition at line 188 of file ClWorkloadFactory.cpp.
     : m_MemoryManager(memoryManager), m_ModelContextPtr(IBackendInternal::IBackendSpecificModelContextPtr{})
 {
     InitializeCLCompileContext();
 }
ClWorkloadFactory() [2/2]
ClWorkloadFactory (const std::shared_ptr< ClMemoryManager > & memoryManager, const IBackendInternal::IBackendSpecificModelContextPtr & modelContextPtr)
Definition at line 194 of file ClWorkloadFactory.cpp.
     : m_MemoryManager(memoryManager), m_ModelContextPtr(modelContextPtr)
 {
     InitializeCLCompileContext();
 }
Member Function Documentation
AfterWorkloadsCreated()
void AfterWorkloadsCreated () override virtual
Reimplemented from IWorkloadFactory.
Definition at line 66 of file ClWorkloadFactory.cpp.
References ARMNN_LOG, CHECK_LOCATION, ClContextDeserializer::Deserialize(), ClContextDeserializer::DeserializeFromBinary(), armnn::Error, ClBackendModelContext::GetCachedNetworkFilePath(), armnn::info, ClContextSerializer::SaveSerializedToStream(), ClContextSerializer::Serialize(), and armnn::WrapClError().
 {
     if(m_ModelContextPtr)
     {
         auto modelOptions = dynamic_cast<ClBackendModelContext*>(m_ModelContextPtr.get());
         if (modelOptions->SaveCachedNetwork())
         {
             ClContextSerializer serializer;
             serializer.Serialize(m_CLCompileContext);
             auto cachedFd = modelOptions->GetCachedFileDescriptor();
             if (cachedFd != -1)
             {
                 std::vector<uint8_t> compiledContextData;
                 std::stringstream stream;
                 bool serialized = serializer.SaveSerializedToStream(stream);
                 if (serialized)
                 {
                     std::string const serializedString{stream.str()};
                     std::copy(serializedString.begin(),
                               serializedString.end(),
                               std::back_inserter(compiledContextData));
                     auto success = write(cachedFd, compiledContextData.data(), compiledContextData.size());
                     if (success == -1)
                     {
                         ARMNN_LOG(info) << "ClWorkloadFactory:: Could not cache the compiled context!";
                     }
                 }
             }
             // Save map to a filepath provided in ModelOptions
             auto filePath = modelOptions->GetCachedNetworkFilePath();
             if (filePath != "" && fs::exists(filePath) && fs::is_regular_file(filePath))
             {
                 // Serialize ClContext to the file specified
                 std::ofstream file(filePath, std::ios::out | std::ios::binary);
                 serializer.SaveSerializedToStream(file);
             }
         }
     }
 }
CreateActivation()
std::unique_ptr< IWorkload > CreateActivation (const ActivationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 247 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClActivationWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateAddition()
std::unique_ptr< IWorkload > CreateAddition (const AdditionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 253 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClAdditionWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateArgMinMax()
std::unique_ptr< IWorkload > CreateArgMinMax (const ArgMinMaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 259 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClArgMinMaxWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateBatchNormalization()
std::unique_ptr< IWorkload > CreateBatchNormalization (const BatchNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 265 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClBatchNormalizationFloatWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateBatchToSpaceNd()
std::unique_ptr< IWorkload > CreateBatchToSpaceNd (const BatchToSpaceNdQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 272 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClBatchToSpaceNdWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateCast()
std::unique_ptr< IWorkload > CreateCast (const CastQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 278 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClCastWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateChannelShuffle()
std::unique_ptr< IWorkload > CreateChannelShuffle (const ChannelShuffleQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 284 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClChannelShuffleWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateComparison()
std::unique_ptr< IWorkload > CreateComparison (const ComparisonQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 290 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClComparisonWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateConcat()
std::unique_ptr< IWorkload > CreateConcat (const ConcatQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 296 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClConcatWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateConstant()
std::unique_ptr< IWorkload > CreateConstant (const ConstantQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 302 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClConstantWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateConvertFp16ToFp32()
std::unique_ptr< IWorkload > CreateConvertFp16ToFp32 (const ConvertFp16ToFp32QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 308 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClConvertFp16ToFp32Workload>(descriptor, info, m_CLCompileContext);
 }
CreateConvertFp32ToFp16()
std::unique_ptr< IWorkload > CreateConvertFp32ToFp16 (const ConvertFp32ToFp16QueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 315 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClConvertFp32ToFp16Workload>(descriptor, info, m_CLCompileContext);
 }
CreateConvolution2d()
std::unique_ptr< IWorkload > CreateConvolution2d (const Convolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 322 of file ClWorkloadFactory.cpp.
References armnn::info, and ClBackendModelContext::IsFastMathEnabled().
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     bool isFastMathEnabled = false;
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<ClBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
     return MakeWorkload<ClConvolution2dWorkload>(descriptor,
                                                  info,
                                                  m_MemoryManager->GetIntraLayerManager(),
                                                  m_CLCompileContext,
                                                  isFastMathEnabled);
 }
CreateConvolution3d()
std::unique_ptr< IWorkload > CreateConvolution3d (const Convolution3dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 344 of file ClWorkloadFactory.cpp.
References armnn::info, and ClBackendModelContext::IsFastMathEnabled().
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     bool isFastMathEnabled = false;
     if (m_ModelContextPtr)
     {
         if (m_ModelContextPtr.get() != nullptr)
         {
             auto modelOptions = dynamic_cast<ClBackendModelContext*>(m_ModelContextPtr.get());
             if (modelOptions)
             {
                 isFastMathEnabled = modelOptions->IsFastMathEnabled();
             }
         }
     }
     return MakeWorkload<ClConvolution3dWorkload>(descriptor,
                                                  info,
                                                  m_MemoryManager->GetIntraLayerManager(),
                                                  m_CLCompileContext,
                                                  isFastMathEnabled);
 }
CreateDebug()
std::unique_ptr< IWorkload > CreateDebug (const DebugQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 366 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<NullWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateDepthToSpace()
std::unique_ptr< IWorkload > CreateDepthToSpace (const DepthToSpaceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 372 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClDepthToSpaceWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateDepthwiseConvolution2d()
std::unique_ptr< IWorkload > CreateDepthwiseConvolution2d (const DepthwiseConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 378 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClDepthwiseConvolutionWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateDequantize()
std::unique_ptr< IWorkload > CreateDequantize (const DequantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 385 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClDequantizeWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateDetectionPostProcess()
std::unique_ptr< IWorkload > CreateDetectionPostProcess (const DetectionPostProcessQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 391 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<NullWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateDivision()
std::unique_ptr< IWorkload > CreateDivision (const DivisionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 398 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClDivisionWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateElementwiseUnary()
std::unique_ptr< IWorkload > CreateElementwiseUnary (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 404 of file ClWorkloadFactory.cpp.
References armnn::Abs, armnn::Exp, armnn::info, armnn::Log, armnn::LogicalNot, QueueDescriptor::m_Inputs, ElementwiseUnaryDescriptor::m_Operation, QueueDescriptor::m_Outputs, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, armnn::Neg, armnn::Rsqrt, and armnn::Sin.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     switch(descriptor.m_Parameters.m_Operation)
     {
         case UnaryOperation::Abs:
         {
             AbsQueueDescriptor absQueueDescriptor;
             absQueueDescriptor.m_Inputs  = descriptor.m_Inputs;
             absQueueDescriptor.m_Outputs = descriptor.m_Outputs;
             return  std::make_unique<ClAbsWorkload>(absQueueDescriptor, info, m_CLCompileContext);
         }
         case UnaryOperation::Exp:
             return std::make_unique<ClExpWorkload>(descriptor, info, m_CLCompileContext);
          case UnaryOperation::Log:
             return std::make_unique<ClLogWorkload>(descriptor, info, m_CLCompileContext);
         case UnaryOperation::LogicalNot:
             return std::make_unique<ClLogicalNotWorkload>(descriptor, info, m_CLCompileContext);
         case UnaryOperation::Neg:
             return std::make_unique<ClNegWorkload>(descriptor, info, m_CLCompileContext);
         case UnaryOperation::Rsqrt:
         {
             RsqrtQueueDescriptor rsqrtQueueDescriptor;
             rsqrtQueueDescriptor.m_Inputs  = descriptor.m_Inputs;
             rsqrtQueueDescriptor.m_Outputs = descriptor.m_Outputs;
             return std::make_unique<ClRsqrtWorkload>(rsqrtQueueDescriptor, info, m_CLCompileContext);
         }
         case UnaryOperation::Sin:
             return std::make_unique<ClSinWorkload>(descriptor, info, m_CLCompileContext);
         default:
             return nullptr;
     }
 }
CreateFill()
std::unique_ptr< IWorkload > CreateFill (const FillQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 440 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClFillWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateFloor()
std::unique_ptr< IWorkload > CreateFloor (const FloorQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 446 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClFloorFloatWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateFullyConnected()
std::unique_ptr< IWorkload > CreateFullyConnected (const FullyConnectedQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 452 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClFullyConnectedWorkload>(descriptor,
                                                   info,
                                                   m_MemoryManager->GetIntraLayerManager(),
                                                   m_CLCompileContext);
 }
CreateGather()
std::unique_ptr< IWorkload > CreateGather (const GatherQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 461 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClGatherWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateInput()
std::unique_ptr< IWorkload > CreateInput (const InputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 467 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreateInstanceNormalization()
std::unique_ptr< IWorkload > CreateInstanceNormalization (const InstanceNormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 473 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClInstanceNormalizationWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateL2Normalization()
std::unique_ptr< IWorkload > CreateL2Normalization (const L2NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 480 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClL2NormalizationFloatWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateLogicalBinary()
std::unique_ptr< IWorkload > CreateLogicalBinary (const LogicalBinaryQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 486 of file ClWorkloadFactory.cpp.
References armnn::info, armnn::LogicalAnd, armnn::LogicalOr, LogicalBinaryDescriptor::m_Operation, and QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     switch(descriptor.m_Parameters.m_Operation)
     {
         case LogicalBinaryOperation::LogicalAnd:
             return std::make_unique<ClLogicalAndWorkload>(descriptor, info, m_CLCompileContext);
         case LogicalBinaryOperation::LogicalOr:
             return std::make_unique<ClLogicalOrWorkload>(descriptor, info, m_CLCompileContext);
         default:
             return nullptr;
     }
 }
CreateLogSoftmax()
std::unique_ptr< IWorkload > CreateLogSoftmax (const LogSoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 500 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClLogSoftmaxWorkload>(descriptor,
                                               info,
                                               m_MemoryManager->GetIntraLayerManager(),
                                               m_CLCompileContext);
 }
CreateLstm()
std::unique_ptr< IWorkload > CreateLstm (const LstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 509 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClLstmFloatWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateMaximum()
std::unique_ptr< IWorkload > CreateMaximum (const MaximumQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 515 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClMaximumWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateMean()
std::unique_ptr< IWorkload > CreateMean (const MeanQueueDescriptor & descriptor, const WorkloadInfo & Info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 521 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClMeanWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateMemCopy()
std::unique_ptr< IWorkload > CreateMemCopy (const MemCopyQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 527 of file ClWorkloadFactory.cpp.
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     if (descriptor.m_Inputs.empty() || !descriptor.m_Inputs[0])
     {
         throw InvalidArgumentException("ClWorkloadFactory: Invalid null input for MemCopy workload");
     }
     return MakeWorkload<CopyMemGenericWorkload>(descriptor, info);
 }
CreateMemImport()
std::unique_ptr< IWorkload > CreateMemImport (const MemImportQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 538 of file ClWorkloadFactory.cpp.
References armnn::info, and QueueDescriptor::m_Inputs.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     if (descriptor.m_Inputs.empty() || !descriptor.m_Inputs[0])
     {
         throw InvalidArgumentException("ClWorkloadFactory: Invalid null input for MemImport workload");
     }
     return std::make_unique<ImportMemGenericWorkload>(descriptor, info);
 }
CreateMinimum()
std::unique_ptr< IWorkload > CreateMinimum (const MinimumQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 549 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClMinimumWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateMultiplication()
std::unique_ptr< IWorkload > CreateMultiplication (const MultiplicationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 555 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClMultiplicationWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateNormalization()
std::unique_ptr< IWorkload > CreateNormalization (const NormalizationQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 561 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClNormalizationFloatWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateOutput()
std::unique_ptr< IWorkload > CreateOutput (const OutputQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 567 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<CopyMemGenericWorkload>(descriptor, info);
 }
CreatePad()
std::unique_ptr< IWorkload > CreatePad (const PadQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 573 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClPadWorkload>(descriptor, info, m_CLCompileContext);
 }
CreatePermute()
std::unique_ptr< IWorkload > CreatePermute (const PermuteQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 579 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClPermuteWorkload>(descriptor, info, m_CLCompileContext);
 }
CreatePooling2d()
std::unique_ptr< IWorkload > CreatePooling2d (const Pooling2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 585 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClPooling2dWorkload>(descriptor, info, m_CLCompileContext);
 }
CreatePreCompiled()
std::unique_ptr< IWorkload > CreatePreCompiled (const PreCompiledQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 591 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<NullWorkload, NullWorkload>(descriptor, info, m_CLCompileContext);
 }
CreatePrelu()
std::unique_ptr< IWorkload > CreatePrelu (const PreluQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 597 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClPreluWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateQLstm()
std::unique_ptr< IWorkload > CreateQLstm (const QLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 603 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClQLstmWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateQuantize()
std::unique_ptr< IWorkload > CreateQuantize (const QuantizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 609 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClQuantizeWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateQuantizedLstm()
std::unique_ptr< IWorkload > CreateQuantizedLstm (const QuantizedLstmQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 615 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClQuantizedLstmWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateRank()
std::unique_ptr< IWorkload > CreateRank (const RankQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 621 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClRankWorkload>(descriptor, info);
 }
CreateReduce()
std::unique_ptr< IWorkload > CreateReduce (const ReduceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from IWorkloadFactory.
Definition at line 627 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClReduceWorkload>(descriptor, info);
 }
CreateReshape()
std::unique_ptr< IWorkload > CreateReshape (const ReshapeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 633 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClReshapeWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateResize()
std::unique_ptr< IWorkload > CreateResize (const ResizeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 639 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClResizeWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateSlice()
std::unique_ptr< IWorkload > CreateSlice (const SliceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 645 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClSliceWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateSoftmax()
std::unique_ptr< IWorkload > CreateSoftmax (const SoftmaxQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 651 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return std::make_unique<ClSoftmaxWorkload>(descriptor,
                                                info,
                                                m_MemoryManager->GetIntraLayerManager(),
                                                m_CLCompileContext);
 }
CreateSpaceToBatchNd()
std::unique_ptr< IWorkload > CreateSpaceToBatchNd (const SpaceToBatchNdQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 660 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClSpaceToBatchNdWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateSpaceToDepth()
std::unique_ptr< IWorkload > CreateSpaceToDepth (const SpaceToDepthQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 666 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClSpaceToDepthWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateSplitter()
std::unique_ptr< IWorkload > CreateSplitter (const SplitterQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 672 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClSplitterWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateStack()
std::unique_ptr< IWorkload > CreateStack (const StackQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 678 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClStackWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateStridedSlice()
std::unique_ptr< IWorkload > CreateStridedSlice (const StridedSliceQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 684 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClStridedSliceWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateSubTensorHandle()
std::unique_ptr< ITensorHandle > CreateSubTensorHandle (ITensorHandle & parent, TensorShape const & subTensorShape, unsigned int const * subTensorOrigin) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 222 of file ClWorkloadFactory.cpp.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     arm_compute::Coordinates coords;
     arm_compute::TensorShape shape = armcomputetensorutils::BuildArmComputeTensorShape(subTensorShape);
     coords.set_num_dimensions(subTensorShape.GetNumDimensions());
     for (unsigned int i = 0; i < subTensorShape.GetNumDimensions(); i++)
     {
         // Arm compute indexes tensor coords in reverse order.
         unsigned int revertedIndex = subTensorShape.GetNumDimensions() - i - 1;
         coords.set(i, armnn::numeric_cast<int>(subTensorOrigin[revertedIndex]));
     }
     const arm_compute::TensorShape parentShape = armcomputetensorutils::BuildArmComputeTensorShape(parent.GetShape());
     if (!::arm_compute::error_on_invalid_subtensor(__func__, __FILE__, __LINE__, parentShape, coords, shape))
     {
         return nullptr;
     }
     return std::make_unique<ClSubTensorHandle>(
         PolymorphicDowncast<IClTensorHandle*>(&parent), shape, coords);
 }
CreateSubtraction()
std::unique_ptr< IWorkload > CreateSubtraction (const SubtractionQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 690 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClSubtractionWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateTensorHandle() [1/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, const bool IsMemoryManaged = true) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 201 of file ClWorkloadFactory.cpp.
References armnn::IgnoreUnused().
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     IgnoreUnused(IsMemoryManaged);
     std::unique_ptr<ClTensorHandle> tensorHandle = std::make_unique<ClTensorHandle>(tensorInfo);
     tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     return tensorHandle;
 }
CreateTensorHandle() [2/2]
std::unique_ptr< ITensorHandle > CreateTensorHandle (const TensorInfo & tensorInfo, DataLayout dataLayout, const bool IsMemoryManaged = true) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 211 of file ClWorkloadFactory.cpp.
References armnn::IgnoreUnused().
 {
     IgnoreUnused(IsMemoryManaged);
     std::unique_ptr<ClTensorHandle> tensorHandle = std::make_unique<ClTensorHandle>(tensorInfo, dataLayout);
     tensorHandle->SetMemoryGroup(m_MemoryManager->GetInterLayerMemoryGroup());
     return tensorHandle;
 }
CreateTranspose()
std::unique_ptr< IWorkload > CreateTranspose (const TransposeQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 696 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClTransposeWorkload>(descriptor, info, m_CLCompileContext);
 }
CreateTransposeConvolution2d()
std::unique_ptr< IWorkload > CreateTransposeConvolution2d (const TransposeConvolution2dQueueDescriptor & descriptor, const WorkloadInfo & info) const override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 702 of file ClWorkloadFactory.cpp.
References armnn::info.
Referenced by ClWorkloadFactory::SupportsSubTensors().
 {
     return MakeWorkload<ClTransposeConvolution2dWorkload>(descriptor,
                                                           info,
                                                           m_MemoryManager->GetIntraLayerManager(),
                                                           m_CLCompileContext);
 }
GetBackendId()
const BackendId & GetBackendId () const override virtual
Implements IWorkloadFactory.
Definition at line 61 of file ClWorkloadFactory.cpp.
 {
     return s_Id;
 }
IsLayerSupported() [1/2]
bool IsLayerSupported (const Layer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported) static
Definition at line 46 of file ClWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported);
 }
IsLayerSupported() [2/2]
bool IsLayerSupported (const IConnectableLayer & layer, Optional< DataType > dataType, std::string & outReasonIfUnsupported, const ModelOptions & modelOptions) static
Definition at line 53 of file ClWorkloadFactory.cpp.
References IWorkloadFactory::IsLayerSupported().
 {
     return IWorkloadFactory::IsLayerSupported(s_Id, layer, dataType, outReasonIfUnsupported, modelOptions);
 }
SupportsSubTensors()
bool SupportsSubTensors () const inline override virtual
Reimplemented from WorkloadFactoryBase.
Definition at line 42 of file ClWorkloadFactory.hpp.
References ARMNN_DEPRECATED_MSG, ClWorkloadFactory::CreateActivation(), ClWorkloadFactory::CreateAddition(), ClWorkloadFactory::CreateArgMinMax(), ClWorkloadFactory::CreateBatchNormalization(), ClWorkloadFactory::CreateBatchToSpaceNd(), ClWorkloadFactory::CreateCast(), ClWorkloadFactory::CreateChannelShuffle(), ClWorkloadFactory::CreateComparison(), ClWorkloadFactory::CreateConcat(), ClWorkloadFactory::CreateConstant(), ClWorkloadFactory::CreateConvertFp16ToFp32(), ClWorkloadFactory::CreateConvertFp32ToFp16(), ClWorkloadFactory::CreateConvolution2d(), ClWorkloadFactory::CreateConvolution3d(), ClWorkloadFactory::CreateDebug(), ClWorkloadFactory::CreateDepthToSpace(), ClWorkloadFactory::CreateDepthwiseConvolution2d(), ClWorkloadFactory::CreateDequantize(), ClWorkloadFactory::CreateDetectionPostProcess(), ClWorkloadFactory::CreateDivision(), ClWorkloadFactory::CreateElementwiseUnary(), ClWorkloadFactory::CreateFill(), ClWorkloadFactory::CreateFloor(), ClWorkloadFactory::CreateFullyConnected(), ClWorkloadFactory::CreateGather(), ClWorkloadFactory::CreateInput(), ClWorkloadFactory::CreateInstanceNormalization(), ClWorkloadFactory::CreateL2Normalization(), ClWorkloadFactory::CreateLogicalBinary(), ClWorkloadFactory::CreateLogSoftmax(), ClWorkloadFactory::CreateLstm(), ClWorkloadFactory::CreateMaximum(), ClWorkloadFactory::CreateMean(), ClWorkloadFactory::CreateMemCopy(), ClWorkloadFactory::CreateMemImport(), ClWorkloadFactory::CreateMinimum(), ClWorkloadFactory::CreateMultiplication(), ClWorkloadFactory::CreateNormalization(), ClWorkloadFactory::CreateOutput(), ClWorkloadFactory::CreatePad(), ClWorkloadFactory::CreatePermute(), ClWorkloadFactory::CreatePooling2d(), ClWorkloadFactory::CreatePreCompiled(), ClWorkloadFactory::CreatePrelu(), ClWorkloadFactory::CreateQLstm(), ClWorkloadFactory::CreateQuantize(), ClWorkloadFactory::CreateQuantizedLstm(), ClWorkloadFactory::CreateRank(), ClWorkloadFactory::CreateReduce(), ClWorkloadFactory::CreateReshape(), ClWorkloadFactory::CreateResize(), ClWorkloadFactory::CreateSlice(), ClWorkloadFactory::CreateSoftmax(), ClWorkloadFactory::CreateSpaceToBatchNd(), ClWorkloadFactory::CreateSpaceToDepth(), ClWorkloadFactory::CreateSplitter(), ClWorkloadFactory::CreateStack(), ClWorkloadFactory::CreateStridedSlice(), ClWorkloadFactory::CreateSubTensorHandle(), ClWorkloadFactory::CreateSubtraction(), ClWorkloadFactory::CreateTensorHandle(), ClWorkloadFactory::CreateTranspose(), ClWorkloadFactory::CreateTransposeConvolution2d(), armnn::Info, and armnn::info.
 { return true; }
The documentation for this class was generated from the following files:
src/backends/cl/ClWorkloadFactory.hpp
src/backends/cl/ClWorkloadFactory.cpp