ArmNN: ClLogWorkload Class Reference
ClLogWorkload Class Reference
#include <ClLogWorkload.hpp>
Public Member Functions
ClLogWorkload (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
virtual void Execute () const override
Public Member Functions inherited from BaseWorkload< ElementwiseUnaryQueueDescriptor >
BaseWorkload (const ElementwiseUnaryQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const ElementwiseUnaryQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ElementwiseUnaryQueueDescriptor >
ElementwiseUnaryQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 18 of file ClLogWorkload.hpp.
Constructor & Destructor Documentation
ClLogWorkload()
ClLogWorkload (const ElementwiseUnaryQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 26 of file ClLogWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT, BaseWorkload< ElementwiseUnaryQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, QueueDescriptor::m_Outputs, armnn::Undefined, and QueueDescriptor::ValidateInputsOutputs().
     : BaseWorkload<ElementwiseUnaryQueueDescriptor>(descriptor, info)
 {
     m_Data.ValidateInputsOutputs("ClLogWorkload", 1, 1);
     arm_compute::ICLTensor& input  = PolymorphicDowncast<ClTensorHandle*>(m_Data.m_Inputs[0])->GetTensor();
     arm_compute::ICLTensor& output = PolymorphicDowncast<ClTensorHandle*>(m_Data.m_Outputs[0])->GetTensor();
     {
         ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClLogWorkload_configure");
         m_LogLayer.configure(clCompileContext, &input, &output);
     }
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 42 of file ClLogWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< ElementwiseUnaryQueueDescriptor >::GetGuid(), and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClLogWorkload_Execute", this->GetGuid());
     RunClFunction(m_LogLayer, CHECK_LOCATION());
 }
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClLogWorkload.hpp
src/backends/cl/workloads/ClLogWorkload.cpp