ArmNN: ClDepthToSpaceWorkload Class Reference
ClDepthToSpaceWorkload Class Reference
#include <ClDepthToSpaceWorkload.hpp>
Public Member Functions
ClDepthToSpaceWorkload (const DepthToSpaceQueueDescriptor &descriptor, const WorkloadInfo &info, const arm_compute::CLCompileContext &clCompileContext)
void Execute () const override
Public Member Functions inherited from BaseWorkload< DepthToSpaceQueueDescriptor >
BaseWorkload (const DepthToSpaceQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const DepthToSpaceQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< DepthToSpaceQueueDescriptor >
DepthToSpaceQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 21 of file ClDepthToSpaceWorkload.hpp.
Constructor & Destructor Documentation
ClDepthToSpaceWorkload()
ClDepthToSpaceWorkload (const DepthToSpaceQueueDescriptor & descriptor, const WorkloadInfo & info, const arm_compute::CLCompileContext & clCompileContext)
Definition at line 39 of file ClDepthToSpaceWorkload.cpp.
References ARMNN_REPORT_PROFILING_WORKLOAD_DESC, BaseWorkload< DepthToSpaceQueueDescriptor >::m_Data, QueueDescriptorWithParameters< LayerDescriptor >::m_Parameters, and QueueDescriptor::ValidateInputsOutputs().
     : BaseWorkload<DepthToSpaceQueueDescriptor>(descriptor, info)
 {
     // Report Profiling Details
     ARMNN_REPORT_PROFILING_WORKLOAD_DESC("ClDepthToSpaceWorkload_Construct",
                                          descriptor.m_Parameters,
                                          info,
                                          this->GetGuid());
     m_Data.ValidateInputsOutputs("ClDepthToSpaceWorkload", 1, 1);
     arm_compute::DataLayout aclDataLayout = ConvertDataLayout(m_Data.m_Parameters.m_DataLayout);
     arm_compute::ICLTensor& input =
         PolymorphicPointerDowncast<IClTensorHandle>(m_Data.m_Inputs[0])->GetTensor();
     input.info()->set_data_layout(aclDataLayout);
     int32_t blockSize = armnn::numeric_cast<int32_t>(descriptor.m_Parameters.m_BlockSize);
     arm_compute::ICLTensor& output =
         PolymorphicPointerDowncast<IClTensorHandle>(m_Data.m_Outputs[0])->GetTensor();
     output.info()->set_data_layout(aclDataLayout);
     {
         ARMNN_SCOPED_PROFILING_EVENT(Compute::Undefined, "ClDepthToSpaceWorkload_configure");
         m_Layer.configure(clCompileContext, &input, &output, blockSize);
     }
 }
Member Function Documentation
Execute()
void Execute () const override virtual
Implements IWorkload.
Definition at line 70 of file ClDepthToSpaceWorkload.cpp.
References ARMNN_SCOPED_PROFILING_EVENT_CL_GUID, CHECK_LOCATION, BaseWorkload< DepthToSpaceQueueDescriptor >::GetGuid(), and armnn::RunClFunction().
 {
     ARMNN_SCOPED_PROFILING_EVENT_CL_GUID("ClDepthToSpaceWorkload_Execute", this->GetGuid());
     RunClFunction(m_Layer, CHECK_LOCATION());
 }
The documentation for this class was generated from the following files:
src/backends/cl/workloads/ClDepthToSpaceWorkload.hpp
src/backends/cl/workloads/ClDepthToSpaceWorkload.cpp