ArmNN: ISendThread Class Reference
ISendThread Class Reference abstract
#include <ISendThread.hpp>
Public Member Functions
virtual ~ISendThread ()
virtual void Start (IProfilingConnection &profilingConnection)=0
Start the thread.
virtual void Stop (bool rethrowSendThreadExceptions=true)=0
Stop the thread.
Detailed Description
Definition at line 16 of file ISendThread.hpp.
Constructor & Destructor Documentation
~ISendThread()
virtual ~ISendThread () inline virtual
Definition at line 19 of file ISendThread.hpp.
References ISendThread::Start(), and ISendThread::Stop().
 {}
Member Function Documentation
Start()
virtual void Start (IProfilingConnection & profilingConnection) pure virtual
Start the thread.
Implemented in SendThread.
Referenced by ISendThread::~ISendThread().
Stop()
virtual void Stop (bool rethrowSendThreadExceptions = true) pure virtual
Stop the thread.
Implemented in SendThread.
Referenced by ISendThread::~ISendThread().
The documentation for this class was generated from the following file:
src/profiling/ISendThread.hpp