ArmNN: PermuteLayer Class Reference
PermuteLayer Class Reference
This layer represents a permutation operation.
#include <PermuteLayer.hpp>
Public Member Functions
virtual std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory &factory) const override
Makes a workload for the Permute type.
PermuteLayer * Clone (Graph &graph) const override
Creates a dynamically-allocated copy of this layer.
void ValidateTensorShapesFromInputs () override
Check if the input tensor shape(s) will lead to a valid configuration of PermuteLayer.
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > &inputShapes) const override
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
const PermutationVector & GetPermutation () const
bool IsInverse (const Layer &other) const
Indicates if the other layer received is inverse of this one.
bool IsEqual (const Layer &other) const
Indicates if the other layer received is equal to this one.
ARMNN_NO_DEPRECATE_WARN_BEGIN void Accept (ILayerVisitor &visitor) const override
Public Member Functions inherited from LayerWithParameters< PermuteDescriptor >
const PermuteDescriptor & GetParameters () const
void SerializeLayerParameters (ParameterStringifyFunction &fn) const override
Helper to serialize the layer parameters to string (currently used in DotSerializer and company).
Public Member Functions inherited from Layer
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const char *name)
Layer (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, DataLayout layout, const char *name)
const std::string & GetNameStr () const
const OutputHandler & GetOutputHandler (unsigned int i=0) const
OutputHandler & GetOutputHandler (unsigned int i=0)
ShapeInferenceMethod GetShapeInferenceMethod () const
const std::vector< InputSlot > & GetInputSlots () const
const std::vector< OutputSlot > & GetOutputSlots () const
std::vector< InputSlot >::iterator BeginInputSlots ()
std::vector< InputSlot >::iterator EndInputSlots ()
std::vector< OutputSlot >::iterator BeginOutputSlots ()
std::vector< OutputSlot >::iterator EndOutputSlots ()
bool IsOutputUnconnected ()
void ResetPriority () const
LayerPriority GetPriority () const
LayerType GetType () const override
Returns the armnn::LayerType of this layer.
DataType GetDataType () const
const BackendId & GetBackendId () const
void SetBackendId (const BackendId &id)
virtual void CreateTensorHandles (const TensorHandleFactoryRegistry &registry, const IWorkloadFactory &factory, const bool IsMemoryManaged=true)
void VerifyLayerConnections (unsigned int expectedConnections, const CheckLocation &location) const
virtual void ReleaseConstantData ()
template<typename Op >
void OperateOnConstantTensors (Op op)
const char * GetName () const override
Returns the name of the layer.
unsigned int GetNumInputSlots () const override
Returns the number of connectable input slots.
unsigned int GetNumOutputSlots () const override
Returns the number of connectable output slots.
const InputSlot & GetInputSlot (unsigned int index) const override
Get a const input slot handle by slot index.
InputSlot & GetInputSlot (unsigned int index) override
Get the input slot handle by slot index.
const OutputSlot & GetOutputSlot (unsigned int index=0) const override
Get the const output slot handle by slot index.
OutputSlot & GetOutputSlot (unsigned int index=0) override
Get the output slot handle by slot index.
void SetGuid (LayerGuid guid)
LayerGuid GetGuid () const final
Returns the unique id of the layer.
void AddRelatedLayerName (const std::string layerName)
const std::list< std::string > & GetRelatedLayerNames ()
virtual void Reparent (Graph &dest, std::list< Layer *>::const_iterator iterator)=0
void BackendSelectionHint (Optional< BackendId > backend) final
Provide a hint for the optimizer as to which backend to prefer for this layer.
Optional< BackendId > GetBackendHint () const
void SetShapeInferenceMethod (ShapeInferenceMethod shapeInferenceMethod)
template<typename T >
std::shared_ptr< T > GetAdditionalInformation () const
void SetAdditionalInfoForObject (const AdditionalInfoObjectPtr &additionalInfo)
Public Member Functions inherited from IConnectableLayer
ARMNN_NO_DEPRECATE_WARN_BEGIN ARMNN_DEPRECATED_MSG_REMOVAL_DATE ("Accept is deprecated. The ILayerVisitor that works in conjunction with this " "Accept function is deprecated. Use IStrategy in combination with " "ExecuteStrategy instead, which is an ABI/API stable version of the " "visitor pattern.", "22.05") virtual void Accept(ILayerVisitor &visitor) const =0
Apply a visitor to this layer.
Protected Member Functions
PermuteLayer (const PermuteDescriptor &param, const char *name)
Constructor to create a PermuteLayer.
~PermuteLayer ()=default
Default destructor.
Protected Member Functions inherited from LayerWithParameters< PermuteDescriptor >
LayerWithParameters (unsigned int numInputSlots, unsigned int numOutputSlots, LayerType type, const PermuteDescriptor &param, const char *name)
~LayerWithParameters ()=default
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
void ExecuteStrategy (IStrategy &strategy) const override
Apply a visitor to this layer.
Protected Member Functions inherited from Layer
virtual ~Layer ()=default
template<typename QueueDescriptor >
void CollectQueueDescriptorInputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
template<typename QueueDescriptor >
void CollectQueueDescriptorOutputs (QueueDescriptor &descriptor, WorkloadInfo &info) const
void ValidateAndCopyShape (const TensorShape &outputShape, const TensorShape &inferredShape, const ShapeInferenceMethod shapeInferenceMethod, const std::string &layerName, const unsigned int outputSlotIndex=0)
void VerifyShapeInferenceType (const TensorShape &outputShape, ShapeInferenceMethod shapeInferenceMethod)
template<typename QueueDescriptor >
WorkloadInfo PrepInfoAndDesc (QueueDescriptor &descriptor) const
Helper function to reduce duplication in *LayerCreateWorkload.
template<typename LayerType , typename ... Params>
LayerType * CloneBase (Graph &graph, Params &&... params) const
virtual ConstantTensors GetConstantTensorsByRef ()
void SetAdditionalInfo (QueueDescriptor &descriptor) const
Protected Member Functions inherited from IConnectableLayer
~IConnectableLayer ()
Objects are not deletable via the handle.
Additional Inherited Members
Public Types inherited from LayerWithParameters< PermuteDescriptor >
using DescriptorType = PermuteDescriptor
Protected Types inherited from Layer
using ConstantTensors = std::vector< std::reference_wrapper< std::shared_ptr< ConstTensorHandle > >>
Protected Attributes inherited from LayerWithParameters< PermuteDescriptor >
PermuteDescriptor m_Param
The parameters for the layer (not including tensor-valued weights etc.).
Protected Attributes inherited from Layer
AdditionalInfoObjectPtr m_AdditionalInfoObject
std::vector< OutputHandler > m_OutputHandlers
ShapeInferenceMethod m_ShapeInferenceMethod
Detailed Description
This layer represents a permutation operation.
Definition at line 15 of file PermuteLayer.hpp.
Constructor & Destructor Documentation
PermuteLayer()
PermuteLayer (const PermuteDescriptor & param, const char * name) protected
Constructor to create a PermuteLayer.
Parameters
[in] param PermuteDescriptor to configure the permute operation.
[in] name Optional name for the layer.
Definition at line 20 of file PermuteLayer.cpp.
References armnnUtils::Permute().
Referenced by PermuteLayer::IsEqual().
     : LayerWithParameters(1, 1, LayerType::Permute, param, name)
 {
 }
~PermuteLayer()
~PermuteLayer () protected default
Default destructor.
Referenced by PermuteLayer::IsEqual().
Member Function Documentation
Accept()
ARMNN_NO_DEPRECATE_WARN_BEGIN void Accept (ILayerVisitor & visitor) const override
Definition at line 61 of file PermuteLayer.cpp.
References ARMNN_NO_DEPRECATE_WARN_END, Layer::GetName(), and LayerWithParameters< PermuteDescriptor >::GetParameters().
Referenced by PermuteLayer::IsEqual().
 {
     visitor.VisitPermuteLayer(this, GetParameters(), GetName());
 }
Clone()
PermuteLayer * Clone (Graph & graph) const override virtual
Creates a dynamically-allocated copy of this layer.
Parameters
[in] graph The graph into which this layer is being cloned.
Implements Layer.
Definition at line 33 of file PermuteLayer.cpp.
References Layer::GetName(), and LayerWithParameters< PermuteDescriptor >::m_Param.
 {
     return CloneBase<PermuteLayer>(graph, m_Param, GetName());
 }
CreateWorkload()
std::unique_ptr< IWorkload > CreateWorkload (const IWorkloadFactory & factory) const override virtual
Makes a workload for the Permute type.
Parameters
[in] graph The graph where this layer can be found.
[in] factory The workload factory which will create the workload.
Returns
A pointer to the created workload, or nullptr if not created.
Implements Layer.
Definition at line 25 of file PermuteLayer.cpp.
References IWorkloadFactory::CreatePermute(), LayerWithParameters< PermuteDescriptor >::PrepInfoAndDesc(), and Layer::SetAdditionalInfo().
 {
     PermuteQueueDescriptor descriptor;
     SetAdditionalInfo(descriptor);
     return factory.CreatePermute(descriptor, PrepInfoAndDesc(descriptor));
 }
GetPermutation()
const PermutationVector& GetPermutation () const inline
Returns
a permutation vector represents the memory layout of the tensor elements.
Definition at line 40 of file PermuteLayer.hpp.
References PermuteDescriptor::m_DimMappings, and LayerWithParameters< PermuteDescriptor >::m_Param.
Referenced by PermuteLayer::IsEqual(), PermuteLayer::IsInverse(), and PermuteAsReshapeImpl::Run().
     {
         return m_Param.m_DimMappings;
     }
InferOutputShapes()
std::vector< TensorShape > InferOutputShapes (const std::vector< TensorShape > & inputShapes) const override virtual
By default returns inputShapes if the number of inputs are equal to number of outputs, otherwise infers the output shapes from given input shapes and layer properties.
Parameters
[in] inputShapes The input shapes layer has.
Returns
A vector to the inferred output shape.
Reimplemented from Layer.
Definition at line 38 of file PermuteLayer.cpp.
References ARMNN_ASSERT, PermuteDescriptor::m_DimMappings, LayerWithParameters< PermuteDescriptor >::m_Param, and armnnUtils::Permuted().
Referenced by PermuteLayer::ValidateTensorShapesFromInputs().
 {
     ARMNN_ASSERT(inputShapes.size() == 1);
     const TensorShape& inShape = inputShapes[0];
     return std::vector<TensorShape> ({armnnUtils::Permuted(inShape, m_Param.m_DimMappings)});
 }
IsEqual()
bool IsEqual (const Layer & other) const inline
Indicates if the other layer received is equal to this one.
Parameters
other The other layer to be compare with.
Returns
true if other layer is equal to this false otherwise.
Definition at line 57 of file PermuteLayer.hpp.
References PermuteLayer::Accept(), ARMNN_NO_DEPRECATE_WARN_BEGIN, ARMNN_NO_DEPRECATE_WARN_END, PermuteLayer::GetPermutation(), Layer::GetType(), PermutationVector::IsEqual(), armnn::Permute, PermuteLayer::PermuteLayer(), and PermuteLayer::~PermuteLayer().
     {
         return (other.GetType() == LayerType::Permute) &&
                GetPermutation().IsEqual(PolymorphicDowncast<const PermuteLayer*>(&other)->GetPermutation());
     }
IsInverse()
bool IsInverse (const Layer & other) const inline
Indicates if the other layer received is inverse of this one.
Parameters
other The other layer to be compared with.
Returns
true if other layer is inverse of this false otherwise.
Definition at line 48 of file PermuteLayer.hpp.
References PermuteLayer::GetPermutation(), Layer::GetType(), PermutationVector::IsInverse(), and armnn::Permute.
     {
         return (other.GetType() == LayerType::Permute) &&
             GetPermutation().IsInverse(PolymorphicDowncast<const PermuteLayer*>(&other)->GetPermutation());
     }
ValidateTensorShapesFromInputs()
void ValidateTensorShapesFromInputs () override virtual
Check if the input tensor shape(s) will lead to a valid configuration of PermuteLayer.
Parameters
[in] shapeInferenceMethod Indicates if output shape shall be overwritten or just validated.
Implements Layer.
Definition at line 45 of file PermuteLayer.cpp.
References ARMNN_ASSERT, ARMNN_NO_DEPRECATE_WARN_BEGIN, CHECK_LOCATION, InputSlot::GetConnection(), Layer::GetInputSlot(), Layer::GetOutputSlot(), TensorInfo::GetShape(), IOutputSlot::GetTensorInfo(), OutputSlot::GetTensorInfo(), PermuteLayer::InferOutputShapes(), Layer::m_ShapeInferenceMethod, Layer::ValidateAndCopyShape(), Layer::VerifyLayerConnections(), and Layer::VerifyShapeInferenceType().
 {
     VerifyLayerConnections(1, CHECK_LOCATION());
     const TensorShape& outputShape = GetOutputSlot(0).GetTensorInfo().GetShape();
     VerifyShapeInferenceType(outputShape, m_ShapeInferenceMethod);
     auto inferredShapes = InferOutputShapes({ GetInputSlot(0).GetConnection()->GetTensorInfo().GetShape() });
     ARMNN_ASSERT(inferredShapes.size() == 1);
     ValidateAndCopyShape(outputShape, inferredShapes[0], m_ShapeInferenceMethod, "PermuteLayer");
 }
The documentation for this class was generated from the following files:
src/armnn/layers/PermuteLayer.hpp
src/armnn/layers/PermuteLayer.cpp