ArmNN: RangeTracker Class Reference
RangeTracker Class Reference
#include <RangeTracker.hpp>
Public Types
using MinMaxRange = std::pair< float, float >
Public Member Functions
MinMaxRange GetRange (LayerGuid guid, unsigned int idx) const
Retrieve the Range for a particular output slot on a particular layer.
void SetRange (const IConnectableLayer *layer, unsigned int outputIdx, float min, float max)
Set the range for an output slot on a layer.
bool IsEmpty () const
Query function to check that the RangeTracker is empty.
bool HasRanges (LayerGuid guid) const
Query that there is an entry for a layer.
void RefineMin (LayerGuid guid, unsigned int slotIndex, float newMin)
Update min in RangeTracker with new_min if it is lower than current value.
void RefineMax (LayerGuid guid, unsigned int slotIndex, float newMax)
Update max in RangeTracker with new_max if it is greater than current value.
void ResetMinMax (LayerGuid guid, unsigned int idx, float newMin, float newMax)
Overwrite min and max in RangeTracker with newMin and newMax.
void Reset ()
void SetDynamicMode (bool flag)
bool IsInDynamicMode () const
Detailed Description
Definition at line 19 of file RangeTracker.hpp.
Member Typedef Documentation
MinMaxRange
using MinMaxRange = std::pair<float, float>
Definition at line 22 of file RangeTracker.hpp.
Member Function Documentation
GetRange()
RangeTracker::MinMaxRange GetRange (armnn::LayerGuid guid, unsigned int idx) const
Retrieve the Range for a particular output slot on a particular layer.
Definition at line 29 of file RangeTracker.cpp.
References RangeTracker::IsInDynamicMode().
 {
     auto search = m_GuidToRangesMap.find(guid);
     if (search == m_GuidToRangesMap.end())
     {
         if (IsInDynamicMode())
         {
             throw armnn::Exception("Have no entry for layer GUID [" + std::to_string(guid) + "]");
         }
         else
         {
             return DefaultRange();
         }
     }
     return search->second.at(idx);
 }
HasRanges()
bool HasRanges (LayerGuid guid) const inline
Query that there is an entry for a layer.
Definition at line 34 of file RangeTracker.hpp.
References RangeTracker::RefineMax(), RangeTracker::RefineMin(), RangeTracker::Reset(), and RangeTracker::ResetMinMax().
 { return m_GuidToRangesMap.find(guid) != m_GuidToRangesMap.end(); }
IsEmpty()
bool IsEmpty () const inline
Query function to check that the RangeTracker is empty.
Definition at line 31 of file RangeTracker.hpp.
 { return m_GuidToRangesMap.empty(); }
IsInDynamicMode()
bool IsInDynamicMode () const inline
Definition at line 49 of file RangeTracker.hpp.
Referenced by RangeTracker::GetRange().
 { return m_DynamicMode; }
RefineMax()
void RefineMax (LayerGuid guid, unsigned int slotIndex, float newMax)
Update max in RangeTracker with new_max if it is greater than current value.
Definition at line 55 of file RangeTracker.cpp.
Referenced by RangeTracker::HasRanges().
 {
     auto& currentMax = m_GuidToRangesMap.find(guid)->second.at(idx).second;
     if (newMax > currentMax)
     {
         currentMax = newMax;
     }
 }
RefineMin()
void RefineMin (LayerGuid guid, unsigned int slotIndex, float newMin)
Update min in RangeTracker with new_min if it is lower than current value.
Definition at line 46 of file RangeTracker.cpp.
Referenced by RangeTracker::HasRanges().
 {
     auto& currentMin = m_GuidToRangesMap.find(guid)->second.at(idx).first;
     if (newMin < currentMin)
     {
         currentMin = newMin;
     }
 }
Reset()
void Reset ()
Definition at line 74 of file RangeTracker.cpp.
Referenced by RangeTracker::HasRanges().
 {
     m_GuidToRangesMap.clear();
 }
ResetMinMax()
void ResetMinMax (LayerGuid guid, unsigned int idx, float newMin, float newMax)
Overwrite min and max in RangeTracker with newMin and newMax.
Definition at line 64 of file RangeTracker.cpp.
Referenced by RangeTracker::HasRanges().
 {
     auto minMaxPair = m_GuidToRangesMap.find(guid);
     auto& currentMin = minMaxPair->second.at(idx).first;
     auto& currentMax = minMaxPair->second.at(idx).second;
     currentMin = newMin;
     currentMax = newMax;
 }
SetDynamicMode()
void SetDynamicMode (bool flag) inline
Definition at line 47 of file RangeTracker.hpp.
 { m_DynamicMode = flag; }
SetRange()
void SetRange (const IConnectableLayer * layer, unsigned int outputIdx, float min, float max)
Set the range for an output slot on a layer.
Definition at line 12 of file RangeTracker.cpp.
References IConnectableLayer::GetGuid(), and IConnectableLayer::GetNumOutputSlots().
 {
     auto& ranges = m_GuidToRangesMap[layer->GetGuid()];
     unsigned int numOfOutputSlots = layer->GetNumOutputSlots();
     // output layers are a special case
     if (numOfOutputSlots == 0)
     {
         ++numOfOutputSlots;
     }
     if (ranges.size() < numOfOutputSlots)
     {
         ranges.resize(numOfOutputSlots);
     }
     ranges[outputIdx] = std::make_pair(min, max);
 }
The documentation for this class was generated from the following files:
src/armnn/RangeTracker.hpp
src/armnn/RangeTracker.cpp