ArmNN: BooleanDecoderBool Class Reference
BooleanDecoderBool Class Reference
#include <BaseIterator.hpp>
Public Member Functions
BooleanDecoderBool (const uint8_t *data)
BooleanDecoderBool ()
bool Get () const override
std::vector< float > DecodeTensor (const TensorShape &tensorShape, const bool isDepthwise) override
Public Member Functions inherited from TypedIterator< const uint8_t, Decoder< bool > >
TypedIterator (const uint8_t *data=nullptr)
void Reset (void *data) override
TypedIterator & operator++ () override
TypedIterator & operator+= (const unsigned int increment) override
TypedIterator & operator-= (const unsigned int increment) override
TypedIterator & operator[] (const unsigned int index) override
Public Member Functions inherited from Decoder< bool >
Decoder ()
virtual ~Decoder ()
Public Member Functions inherited from BaseIterator
BaseIterator ()
virtual ~BaseIterator ()
Additional Inherited Members
Protected Attributes inherited from TypedIterator< const uint8_t, Decoder< bool > >
const uint8_t * m_Iterator
const uint8_t * m_Start
Detailed Description
Definition at line 498 of file BaseIterator.hpp.
Constructor & Destructor Documentation
BooleanDecoderBool() [1/2]
BooleanDecoderBool (const uint8_t * data) inline
Definition at line 501 of file BaseIterator.hpp.
         : TypedIterator(data) {}
BooleanDecoderBool() [2/2]
BooleanDecoderBool () inline
Definition at line 504 of file BaseIterator.hpp.
         : BooleanDecoderBool(nullptr) {}
Member Function Documentation
DecodeTensor()
std::vector<float> DecodeTensor (const TensorShape & tensorShape, const bool isDepthwise) inline override virtual
Implements Decoder< bool >.
Definition at line 512 of file BaseIterator.hpp.
References TensorShape::GetNumElements(), armnn::IgnoreUnused(), and BaseIterator::operator[]().
     {
         IgnoreUnused(isDepthwise);
         const unsigned int size = tensorShape.GetNumElements();
         std::vector<float> decodedTensor;
         decodedTensor.reserve(size);
         for (uint32_t i = 0; i < size; ++i)
         {
             this->operator[](i);
             decodedTensor.emplace_back(*m_Iterator);
         }
         return decodedTensor;
     }
Get()
bool Get () const inline override virtual
Implements Decoder< bool >.
Definition at line 507 of file BaseIterator.hpp.
     {
         return *m_Iterator;
     }
The documentation for this class was generated from the following file:
src/backends/reference/workloads/BaseIterator.hpp