ArmNN: IMemoryOptimizerStrategy Class Reference
IMemoryOptimizerStrategy Class Reference abstract
#include <IMemoryOptimizerStrategy.hpp>
Public Member Functions
virtual ~IMemoryOptimizerStrategy ()
virtual std::string GetName () const =0
virtual MemBlockStrategyType GetMemBlockStrategyType () const =0
virtual std::vector< MemBin > Optimize (std::vector< MemBlock > &memBlocks)=0
Detailed Description
Definition at line 45 of file IMemoryOptimizerStrategy.hpp.
Constructor & Destructor Documentation
~IMemoryOptimizerStrategy()
virtual ~IMemoryOptimizerStrategy () inline virtual
Definition at line 48 of file IMemoryOptimizerStrategy.hpp.
References armnn::Optimize().
 {}
Member Function Documentation
GetMemBlockStrategyType()
virtual MemBlockStrategyType GetMemBlockStrategyType () const pure virtual
Implemented in SingleAxisPriorityList, StrategyValidator, ConstantMemoryStrategy, and TestStrategy.
GetName()
virtual std::string GetName () const pure virtual
Implemented in SingleAxisPriorityList, StrategyValidator, ConstantMemoryStrategy, and TestStrategy.
Referenced by RunBenchmark().
Optimize()
virtual std::vector<MemBin> Optimize (std::vector< MemBlock > & memBlocks) pure virtual
Implemented in StrategyValidator, SingleAxisPriorityList, ConstantMemoryStrategy, and TestStrategy.
Referenced by RunBenchmark().
The documentation for this class was generated from the following file:
include/armnn/backends/IMemoryOptimizerStrategy.hpp