ArmNN: JsonPrinter Class Reference
JsonPrinter Class Reference
#include <JsonPrinter.hpp>
Public Member Functions
void PrintJsonChildObject (const JsonChildObject &object, size_t &id)
void PrintLabel (const std::string &label, size_t id)
void PrintUnit (armnn::Measurement::Unit unit)
void PrintType (armnn::JsonObjectType type)
void PrintGuid (armnn::profiling::ProfilingGuid guid)
void PrintMeasurementsList (const std::vector< double > &measurementsVector)
JsonPrinter (std::ostream &outputStream)
Public Member Functions inherited from JsonUtils
JsonUtils (std::ostream &outputStream)
void PrintTabs ()
void DecrementNumberOfTabs ()
void IncrementNumberOfTabs ()
void PrintNewLine ()
void PrintFooter ()
void PrintHeader ()
void PrintArmNNHeader ()
void PrintSeparator ()
Detailed Description
Definition at line 114 of file JsonPrinter.hpp.
Constructor & Destructor Documentation
JsonPrinter()
JsonPrinter (std::ostream & outputStream) inline
Definition at line 125 of file JsonPrinter.hpp.
         : JsonUtils(outputStream), m_OutputStream(outputStream)
     {}
Member Function Documentation
PrintGuid()
void PrintGuid (armnn::profiling::ProfilingGuid guid)
Definition at line 141 of file JsonPrinter.cpp.
References JsonUtils::PrintTabs().
Referenced by JsonPrinter::PrintJsonChildObject().
 {
     PrintTabs();
     m_OutputStream << std::quoted("GUID") << ": " << std::quoted(std::to_string(guid))  << "," << std::endl;
 }
PrintJsonChildObject()
void PrintJsonChildObject (const JsonChildObject & object, size_t & id)
Definition at line 15 of file JsonPrinter.cpp.
References JsonUtils::DecrementNumberOfTabs(), armnn::Event, armnn::ExecObjectDesc, JsonUtils::IncrementNumberOfTabs(), armnn::Measurement, JsonUtils::PrintFooter(), JsonPrinter::PrintGuid(), JsonPrinter::PrintLabel(), JsonPrinter::PrintMeasurementsList(), JsonUtils::PrintNewLine(), JsonUtils::PrintSeparator(), JsonUtils::PrintTabs(), JsonPrinter::PrintType(), and JsonPrinter::PrintUnit().
Referenced by ProfilerImpl::Print().
 {
     if (object.GetType() == JsonObjectType::Event)
     {
         // Increase the Id for new events. This ensures a new event has a unique ID and any measurements belonging
         // to the event have the same id. This id is appended to the name during the call to PrintLabel() below.
         id++;
     }
     if (object.GetType() != JsonObjectType::ExecObjectDesc)
     {
         PrintLabel(object.m_Label, id);
         if (object.m_Guid.has_value())
         {
             PrintGuid(object.m_Guid.value());
         }
         PrintType(object.m_Type);
     }
     if (!object.m_Measurements.empty() || !object.m_Children.empty())
     {
         PrintSeparator();
         PrintNewLine();
     }
     if (object.GetType() == JsonObjectType::Measurement)
     {
         PrintMeasurementsList(object.m_Measurements);
         PrintSeparator();
         PrintNewLine();
         PrintUnit(object.m_Unit);
     }
     else if (object.GetType() == JsonObjectType::ExecObjectDesc)
     {
         // Add details opening
         DecrementNumberOfTabs();
         PrintTabs();
         m_OutputStream << std::quoted("Graph") << ":[";
         PrintNewLine();
         // Fill details body
         for (std::string stringLine : object.m_LayerDetailsList)
         {
            PrintTabs();
            m_OutputStream << stringLine;
            PrintNewLine();
         }
         // Close out details
         PrintTabs();
         object.IsDetailsOnlyEnabled() ? m_OutputStream << "]" : m_OutputStream << "],";
         PrintNewLine();
         IncrementNumberOfTabs();
     }
     if (!object.m_Children.empty())
     {
         for (unsigned int childIndex = 0; childIndex < object.m_Children.size(); ++childIndex)
         {
             PrintJsonChildObject(object.m_Children[childIndex], id);
             // Only print separator and new line if current child is not the last element.
             if (&object.m_Children[childIndex] != &object.m_Children.back())
             {
                 PrintSeparator();
                 PrintNewLine();
             }
         }
     }
     if (object.GetType() != JsonObjectType::ExecObjectDesc)
     {
         PrintNewLine();
         PrintFooter();
     }
 }
PrintLabel()
void PrintLabel (const std::string & label, size_t id)
Definition at line 96 of file JsonPrinter.cpp.
References JsonUtils::IncrementNumberOfTabs(), and JsonUtils::PrintTabs().
Referenced by JsonPrinter::PrintJsonChildObject().
 {
     PrintTabs();
     m_OutputStream << R"(")" << MakeKey(label, id) << R"(": {)" << std::endl;
     IncrementNumberOfTabs();
 }
PrintMeasurementsList()
void PrintMeasurementsList (const std::vector< double > & measurementsVector)
Definition at line 147 of file JsonPrinter.cpp.
References JsonUtils::DecrementNumberOfTabs(), JsonUtils::IncrementNumberOfTabs(), and JsonUtils::PrintTabs().
Referenced by JsonPrinter::PrintJsonChildObject().
 {
     if (measurementsVector.empty())
     {
         return;
     }
     PrintTabs();
     m_OutputStream << R"("raw": [)" << std::endl;
     IncrementNumberOfTabs();
     PrintTabs();
     auto iter = measurementsVector.begin();
     m_OutputStream << *iter;
     for (iter = std::next(iter); iter != measurementsVector.end(); ++iter)
     {
         m_OutputStream << "," << std::endl;
         PrintTabs();
         m_OutputStream << *iter;
     }
     m_OutputStream << std::endl;
     DecrementNumberOfTabs();
     PrintTabs();
     m_OutputStream << "]";
 }
PrintType()
void PrintType (armnn::JsonObjectType type)
Definition at line 111 of file JsonPrinter.cpp.
References armnn::Event, armnn::ExecObjectDesc, armnn::Measurement, and JsonUtils::PrintTabs().
Referenced by JsonPrinter::PrintJsonChildObject().
 {
     auto ToString = [](armnn::JsonObjectType type)
         {
             switch (type)
             {
                 case JsonObjectType::Measurement:
                 {
                     return "Measurement";
                 }
                 case JsonObjectType::Event:
                 {
                     return "Event";
                 }
                 case JsonObjectType::ExecObjectDesc:
                 {
                     return "Operator Description";
                 }
                 default:
                 {
                     return "Unknown";
                 }
             }
         };
     PrintTabs();
     m_OutputStream << R"("type": ")";
     m_OutputStream << ToString(type);
     m_OutputStream << R"(")";
 }
PrintUnit()
void PrintUnit (armnn::Measurement::Unit unit)
Definition at line 103 of file JsonPrinter.cpp.
References JsonUtils::PrintTabs(), and Measurement::ToString().
Referenced by JsonPrinter::PrintJsonChildObject().
 {
     PrintTabs();
     m_OutputStream << R"("unit": ")";
     m_OutputStream << armnn::Measurement::ToString(unit);
     m_OutputStream << R"(")";
 }
The documentation for this class was generated from the following files:
src/armnn/JsonPrinter.hpp
src/armnn/JsonPrinter.cpp