ArmNN: BaseWorkload< QueueDescriptor > Class Template Reference
BaseWorkload< QueueDescriptor > Class Template Reference
#include <Workload.hpp>
Public Member Functions
BaseWorkload (const QueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const QueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void Execute () const =0
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Protected Attributes
QueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
template<typename QueueDescriptor>
class armnn::BaseWorkload< QueueDescriptor >
Definition at line 29 of file Workload.hpp.
Constructor & Destructor Documentation
BaseWorkload()
BaseWorkload (const QueueDescriptor & descriptor, const WorkloadInfo & info) inline
Definition at line 33 of file Workload.hpp.
         : m_Data(descriptor),
           m_Guid(profiling::ProfilingService::GetNextGuid())
     {
         m_Data.Validate(info);
     }
Member Function Documentation
ExecuteAsync()
void ExecuteAsync (WorkingMemDescriptor & workingMemDescriptor) inline override virtual
Implements IWorkload.
Reimplemented in RefConvertBf16ToFp32Workload, RefConvertFp16ToFp32Workload, RefConvertFp32ToBf16Workload, RefConvertFp32ToFp16Workload, and RefFakeQuantizationFloat32Workload.
Definition at line 40 of file Workload.hpp.
     {
         ARMNN_LOG(info) << "Using default async workload execution, this will network affect performance";
         std::lock_guard<std::mutex> lockGuard(m_AsyncWorkloadMutex);
         m_Data.m_Inputs = workingMemDescriptor.m_Inputs;
         m_Data.m_Outputs = workingMemDescriptor.m_Outputs;
         Execute();
     };
GetData()
const QueueDescriptor& GetData () const inline
Definition at line 53 of file Workload.hpp.
 { return m_Data; }
GetGuid()
profiling::ProfilingGuid GetGuid () const inline final virtual
Implements IWorkload.
Definition at line 55 of file Workload.hpp.
Referenced by NeonConvertBf16ToFp32Workload::Execute(), NeonConvertFp16ToFp32Workload::Execute(), NeonConvertFp32ToBf16Workload::Execute(), NeonConvertFp32ToFp16Workload::Execute(), ClConvertFp16ToFp32Workload::Execute(), ClConvertFp32ToFp16Workload::Execute(), NeonFloorFloatWorkload::Execute(), NeonLstmFloatWorkload::Execute(), ClLstmFloatWorkload::Execute(), ClFloorFloatWorkload::Execute(), ClNormalizationFloatWorkload::Execute(), ClL2NormalizationFloatWorkload::Execute(), NeonNormalizationFloatWorkload::Execute(), NeonL2NormalizationFloatWorkload::Execute(), and ClBatchNormalizationFloatWorkload::Execute().
 { return m_Guid; }
PostAllocationConfigure()
void PostAllocationConfigure () inline override virtual
Implements IWorkload.
Definition at line 51 of file Workload.hpp.
 {}
Member Data Documentation
m_Data
QueueDescriptor m_Data protected
Definition at line 58 of file Workload.hpp.
Referenced by ClConvertFp16ToFp32Workload::ClConvertFp16ToFp32Workload(), ClConvertFp32ToFp16Workload::ClConvertFp32ToFp16Workload(), ClFloorFloatWorkload::ClFloorFloatWorkload(), ClL2NormalizationFloatWorkload::ClL2NormalizationFloatWorkload(), ClNormalizationFloatWorkload::ClNormalizationFloatWorkload(), RefConvertFp32ToBf16Workload::Execute(), RefConvertFp32ToFp16Workload::Execute(), RefFakeQuantizationFloat32Workload::Execute(), RefConvertBf16ToFp32Workload::Execute(), RefConvertFp16ToFp32Workload::Execute(), RefFakeQuantizationFloat32Workload::ExecuteAsync(), NeonConvertBf16ToFp32Workload::NeonConvertBf16ToFp32Workload(), NeonConvertFp16ToFp32Workload::NeonConvertFp16ToFp32Workload(), NeonConvertFp32ToBf16Workload::NeonConvertFp32ToBf16Workload(), NeonConvertFp32ToFp16Workload::NeonConvertFp32ToFp16Workload(), NeonFloorFloatWorkload::NeonFloorFloatWorkload(), NeonL2NormalizationFloatWorkload::NeonL2NormalizationFloatWorkload(), and NeonNormalizationFloatWorkload::NeonNormalizationFloatWorkload().
m_Guid
const profiling::ProfilingGuid m_Guid protected
Definition at line 59 of file Workload.hpp.
The documentation for this class was generated from the following file:
src/backends/backendsCommon/Workload.hpp