ArmNN: TestFullyConnectedLayerVistor Class Reference
TestFullyConnectedLayerVistor Class Reference
#include <ConstTensorLayerVisitor.hpp>
Public Member Functions
TestFullyConnectedLayerVistor (const FullyConnectedDescriptor &descriptor, const char *name=nullptr)
virtual ~TestFullyConnectedLayerVistor ()
void ExecuteStrategy (const armnn::IConnectableLayer *layer, const armnn::BaseDescriptor &descriptor, const std::vector< armnn::ConstTensor > &constants, const char *name, const armnn::LayerBindingId id=0) override
Public Member Functions inherited from TestLayerVisitor
TestLayerVisitor (const char *name)
Public Member Functions inherited from IStrategy
virtual void FinishStrategy ()
Protected Member Functions
void CheckDescriptor (const FullyConnectedDescriptor &descriptor)
Protected Member Functions inherited from TestLayerVisitor
virtual ~TestLayerVisitor ()
void CheckLayerName (const char *name)
void CheckLayerPointer (const IConnectableLayer *layer)
void CheckConstTensors (const ConstTensor &expected, const ConstTensor &actual)
void CheckConstTensors (const ConstTensor &expected, const ConstTensorHandle &actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const ConstTensor *actual)
void CheckConstTensorPtrs (const std::string &name, const ConstTensor *expected, const std::shared_ptr< ConstTensorHandle > actual)
void CheckOptionalConstTensors (const Optional< ConstTensor > &expected, const Optional< ConstTensor > &actual)
Protected Member Functions inherited from StrategyBase< NoThrowStrategy >
virtual ~StrategyBase ()
Protected Member Functions inherited from IStrategy
IStrategy ()
virtual ~IStrategy ()
Additional Inherited Members
Protected Attributes inherited from StrategyBase< NoThrowStrategy >
NoThrowStrategy m_DefaultStrategy
Detailed Description
Definition at line 126 of file ConstTensorLayerVisitor.hpp.
Constructor & Destructor Documentation
TestFullyConnectedLayerVistor()
TestFullyConnectedLayerVistor (const FullyConnectedDescriptor & descriptor, const char * name = nullptr) inline explicit
Definition at line 129 of file ConstTensorLayerVisitor.hpp.
         : TestLayerVisitor(name)
         , m_Descriptor(descriptor)
     {}
~TestFullyConnectedLayerVistor()
virtual ~TestFullyConnectedLayerVistor () inline virtual
Definition at line 135 of file ConstTensorLayerVisitor.hpp.
 {}
Member Function Documentation
CheckDescriptor()
void CheckDescriptor (const FullyConnectedDescriptor & descriptor) protected
Definition at line 39 of file ConstTensorLayerVisitor.cpp.
References FullyConnectedDescriptor::m_BiasEnabled, Convolution2dDescriptor::m_BiasEnabled, and FullyConnectedDescriptor::m_TransposeWeightMatrix.
 {
     CHECK(m_Descriptor.m_BiasEnabled == descriptor.m_BiasEnabled);
     CHECK(m_Descriptor.m_TransposeWeightMatrix == descriptor.m_TransposeWeightMatrix);
 }
ExecuteStrategy()
void ExecuteStrategy (const armnn::IConnectableLayer * layer, const armnn::BaseDescriptor & descriptor, const std::vector< armnn::ConstTensor > & constants, const char * name, const armnn::LayerBindingId id = 0) inline override virtual
Reimplemented from StrategyBase< NoThrowStrategy >.
Definition at line 137 of file ConstTensorLayerVisitor.hpp.
References NoThrowStrategy::Apply(), TestConvolution2dLayerVisitor::CheckDescriptor(), TestLayerVisitor::CheckLayerName(), TestLayerVisitor::CheckLayerPointer(), armnn::FullyConnected, armnn::GetLayerTypeAsCString(), IConnectableLayer::GetType(), armnn::IgnoreUnused(), and StrategyBase< NoThrowStrategy >::m_DefaultStrategy.
     {
         armnn::IgnoreUnused(descriptor, constants, id);
         switch (layer->GetType())
         {
             case armnn::LayerType::FullyConnected:
             {
                 CheckLayerPointer(layer);
                 CheckLayerName(name);
                 CheckDescriptor(static_cast<const armnn::FullyConnectedDescriptor&>(descriptor));
                 break;
             }
             default:
             {
                 m_DefaultStrategy.Apply(GetLayerTypeAsCString(layer->GetType()));
             }
         }
     }
The documentation for this class was generated from the following files:
src/armnn/test/ConstTensorLayerVisitor.hpp
src/armnn/test/ConstTensorLayerVisitor.cpp