ArmNN: SoftmaxLayerBuilder Struct Reference
SoftmaxLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef SoftmaxLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::SoftmaxDescriptor > descriptor)
SoftmaxLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
SoftmaxLayerBuilder & operator= (const SoftmaxLayerBuilder &)
flatbuffers::Offset< SoftmaxLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5094 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef SoftmaxLayer Table
Definition at line 5095 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
SoftmaxLayerBuilder()
SoftmaxLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5104 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 5098 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateSoftmaxLayer().
{
     fbb_.AddOffset(SoftmaxLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::SoftmaxDescriptor > descriptor) inline
Definition at line 5101 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateSoftmaxLayer().
{
     fbb_.AddOffset(SoftmaxLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<SoftmaxLayer> Finish () inline
Definition at line 5109 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateSoftmaxLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<SoftmaxLayer>(end);
     return o;
   }
operator=()
SoftmaxLayerBuilder& operator= (const SoftmaxLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5096 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5097 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h