ArmNN: Graph::InputLayersAccessor Struct Reference
Graph::InputLayersAccessor Struct Reference
Wrapper class returned by Graph::GetInputLayers()
#include <Graph.hpp>
Public Member Functions
InputLayersAccessor (const Graph &graph)
ConstIteratorInputs begin () const
ConstIteratorInputs end () const
Public Attributes
const Graph & m_Graph
Detailed Description
Wrapper class returned by Graph::GetInputLayers()
Definition at line 59 of file Graph.hpp.
Constructor & Destructor Documentation
InputLayersAccessor()
InputLayersAccessor (const Graph & graph) inline explicit
Definition at line 61 of file Graph.hpp.
Referenced by Graph::GetInputLayers().
 : m_Graph(graph) {}
Member Function Documentation
begin()
ConstIteratorInputs begin () const inline
Definition at line 63 of file Graph.hpp.
References Graph::InputLayersAccessor::m_Graph.
Referenced by Graph::cbegin(), and LoadedNetwork::ImportInputs().
         {
             return { m_Graph.m_Layers.begin(), &(PtrCast<const InputLayer>) };
         }
end()
ConstIteratorInputs end () const inline
Definition at line 68 of file Graph.hpp.
References Graph::GetNumInputs(), and Graph::InputLayersAccessor::m_Graph.
Referenced by Graph::cend(), and LoadedNetwork::ImportInputs().
         {
             return { std::next(m_Graph.m_Layers.begin(), static_cast<IteratorDifference>(m_Graph.GetNumInputs())),
                      &(PtrCast<const InputLayer>) };
         }
Member Data Documentation
m_Graph
const Graph& m_Graph
Definition at line 74 of file Graph.hpp.
Referenced by Graph::InputLayersAccessor::begin(), Graph::OutputLayersAccessor::begin(), Graph::DetachObservable(), Graph::InputLayersAccessor::end(), Graph::OutputLayersAccessor::end(), Graph::LayerInGraph< InputLayer >::LayerInGraph(), Graph::LayerInGraph< OutputLayer >::LayerInGraph(), Graph::LayerInGraph< InputLayer >::~LayerInGraph(), and Graph::LayerInGraph< OutputLayer >::~LayerInGraph().
The documentation for this struct was generated from the following file:
src/armnn/Graph.hpp