ArmNN: Pooling2dLayerBuilder Struct Reference
Pooling2dLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef Pooling2dLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::Pooling2dDescriptor > descriptor)
Pooling2dLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
Pooling2dLayerBuilder & operator= (const Pooling2dLayerBuilder &)
flatbuffers::Offset< Pooling2dLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 4845 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef Pooling2dLayer Table
Definition at line 4846 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
Pooling2dLayerBuilder()
Pooling2dLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 4855 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 4849 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreatePooling2dLayer().
{
     fbb_.AddOffset(Pooling2dLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::Pooling2dDescriptor > descriptor) inline
Definition at line 4852 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreatePooling2dLayer().
{
     fbb_.AddOffset(Pooling2dLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<Pooling2dLayer> Finish () inline
Definition at line 4860 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePooling2dLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<Pooling2dLayer>(end);
     return o;
   }
operator=()
Pooling2dLayerBuilder& operator= (const Pooling2dLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 4847 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 4848 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h