ArmNN: PermuteLayerBuilder Struct Reference
PermuteLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef PermuteLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::PermuteDescriptor > descriptor)
PermuteLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
PermuteLayerBuilder & operator= (const PermuteLayerBuilder &)
flatbuffers::Offset< PermuteLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 5557 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef PermuteLayer Table
Definition at line 5558 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
PermuteLayerBuilder()
PermuteLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 5567 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 5561 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreatePermuteLayer().
{
     fbb_.AddOffset(PermuteLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::PermuteDescriptor > descriptor) inline
Definition at line 5564 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreatePermuteLayer().
{
     fbb_.AddOffset(PermuteLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<PermuteLayer> Finish () inline
Definition at line 5572 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreatePermuteLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<PermuteLayer>(end);
     return o;
   }
operator=()
PermuteLayerBuilder& operator= (const PermuteLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 5559 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 5560 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h