ArmNN: ConstTensorBuilder Struct Reference
ConstTensorBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ConstTensor Table
Public Member Functions
void add_info (flatbuffers::Offset< armnnSerializer::TensorInfo > info)
void add_data_type (armnnSerializer::ConstTensorData data_type)
void add_data (flatbuffers::Offset< void > data)
ConstTensorBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ConstTensorBuilder & operator= (const ConstTensorBuilder &)
flatbuffers::Offset< ConstTensor > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2168 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ConstTensor Table
Definition at line 2169 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ConstTensorBuilder()
ConstTensorBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 2181 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_data()
void add_data (flatbuffers::Offset< void > data) inline
Definition at line 2178 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConstTensor().
{
     fbb_.AddOffset(ConstTensor::VT_DATA, data);
   }
add_data_type()
void add_data_type (armnnSerializer::ConstTensorData data_type) inline
Definition at line 2175 of file ArmnnSchema_generated.h.
References VT_DATA_TYPE.
Referenced by armnnSerializer::CreateConstTensor().
{
     fbb_.AddElement<uint8_t>(ConstTensor::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
   }
add_info()
void add_info (flatbuffers::Offset< armnnSerializer::TensorInfo > info) inline
Definition at line 2172 of file ArmnnSchema_generated.h.
References VT_INFO.
Referenced by armnnSerializer::CreateConstTensor().
{
     fbb_.AddOffset(ConstTensor::VT_INFO, info);
   }
Finish()
flatbuffers::Offset<ConstTensor> Finish () inline
Definition at line 2186 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateConstTensor().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ConstTensor>(end);
     return o;
   }
operator=()
ConstTensorBuilder& operator= (const ConstTensorBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2170 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2171 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h