ArmNN: RefShapeWorkload Struct Reference
RefShapeWorkload Struct Reference
#include <RefShapeWorkload.hpp>
Public Member Functions
virtual void Execute () const override
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
Public Member Functions inherited from BaseWorkload< ShapeQueueDescriptor >
BaseWorkload (const ShapeQueueDescriptor &descriptor, const WorkloadInfo &info)
void ExecuteAsync (WorkingMemDescriptor &workingMemDescriptor) override
void PostAllocationConfigure () override
const ShapeQueueDescriptor & GetData () const
profiling::ProfilingGuid GetGuid () const final
Public Member Functions inherited from IWorkload
virtual ~IWorkload ()
virtual void RegisterDebugCallback (const DebugCallbackFunction &)
Additional Inherited Members
Protected Attributes inherited from BaseWorkload< ShapeQueueDescriptor >
ShapeQueueDescriptor m_Data
const profiling::ProfilingGuid m_Guid
Detailed Description
Definition at line 16 of file RefShapeWorkload.hpp.
Member Function Documentation
Execute()
virtual void Execute () const inline override virtual
Implements IWorkload.
Definition at line 20 of file RefShapeWorkload.hpp.
References BaseWorkload< ShapeQueueDescriptor >::m_Data, QueueDescriptor::m_Inputs, and QueueDescriptor::m_Outputs.
Referenced by RefShapeWorkload::ExecuteAsync().
     {
         Execute(m_Data.m_Inputs, m_Data.m_Outputs);
     }
ExecuteAsync()
void ExecuteAsync (WorkingMemDescriptor & workingMemDescriptor) inline override virtual
Implements IWorkload.
Definition at line 24 of file RefShapeWorkload.hpp.
References RefShapeWorkload::Execute(), TensorInfo::GetDataType(), armnn::GetDataTypeSize(), TensorInfo::GetNumDimensions(), TensorInfo::GetShape(), armnn::GetTensorInfo(), WorkingMemDescriptor::m_Inputs, WorkingMemDescriptor::m_Outputs, armnn::Map, and armnn::Shape.
     {
         Execute(workingMemDescriptor.m_Inputs, workingMemDescriptor.m_Outputs);
     }
The documentation for this struct was generated from the following file:
src/backends/reference/workloads/RefShapeWorkload.hpp