ArmNN: ComparisonLayerBuilder Struct Reference
ComparisonLayerBuilder Struct Reference
#include <ArmnnSchema_generated.h>
Public Types
typedef ComparisonLayer Table
Public Member Functions
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base)
void add_descriptor (flatbuffers::Offset< armnnSerializer::ComparisonDescriptor > descriptor)
ComparisonLayerBuilder (flatbuffers::FlatBufferBuilder &_fbb)
ComparisonLayerBuilder & operator= (const ComparisonLayerBuilder &)
flatbuffers::Offset< ComparisonLayer > Finish ()
Public Attributes
flatbuffers::FlatBufferBuilder & fbb_
flatbuffers::uoffset_t start_
Detailed Description
Definition at line 2991 of file ArmnnSchema_generated.h.
Member Typedef Documentation
Table
typedef ComparisonLayer Table
Definition at line 2992 of file ArmnnSchema_generated.h.
Constructor & Destructor Documentation
ComparisonLayerBuilder()
ComparisonLayerBuilder (flatbuffers::FlatBufferBuilder & _fbb) inline explicit
Definition at line 3001 of file ArmnnSchema_generated.h.
         : fbb_(_fbb) {
     start_ = fbb_.StartTable();
   }
Member Function Documentation
add_base()
void add_base (flatbuffers::Offset< armnnSerializer::LayerBase > base) inline
Definition at line 2995 of file ArmnnSchema_generated.h.
References VT_BASE.
Referenced by armnnSerializer::CreateComparisonLayer().
{
     fbb_.AddOffset(ComparisonLayer::VT_BASE, base);
   }
add_descriptor()
void add_descriptor (flatbuffers::Offset< armnnSerializer::ComparisonDescriptor > descriptor) inline
Definition at line 2998 of file ArmnnSchema_generated.h.
References VT_DESCRIPTOR.
Referenced by armnnSerializer::CreateComparisonLayer().
{
     fbb_.AddOffset(ComparisonLayer::VT_DESCRIPTOR, descriptor);
   }
Finish()
flatbuffers::Offset<ComparisonLayer> Finish () inline
Definition at line 3006 of file ArmnnSchema_generated.h.
Referenced by armnnSerializer::CreateComparisonLayer().
{
     const auto end = fbb_.EndTable(start_);
     auto o = flatbuffers::Offset<ComparisonLayer>(end);
     return o;
   }
operator=()
ComparisonLayerBuilder& operator= (const ComparisonLayerBuilder &)
Member Data Documentation
fbb_
flatbuffers::FlatBufferBuilder& fbb_
Definition at line 2993 of file ArmnnSchema_generated.h.
start_
flatbuffers::uoffset_t start_
Definition at line 2994 of file ArmnnSchema_generated.h.
The documentation for this struct was generated from the following file:
src/armnnSerializer/ArmnnSchema_generated.h