var searchData=
[
  ['tensor_6185',['Tensor',['../classarmnn_1_1_tensor.xhtml',1,'armnn']]],
  ['tensorbufferarrayview_6186',['TensorBufferArrayView',['../classarmnn_1_1_tensor_buffer_array_view.xhtml',1,'armnn']]],
  ['tensorhandle_6187',['TensorHandle',['../classarmnn_1_1_tensor_handle.xhtml',1,'armnn']]],
  ['tensorhandlefactoryregistry_6188',['TensorHandleFactoryRegistry',['../classarmnn_1_1_tensor_handle_factory_registry.xhtml',1,'armnn']]],
  ['tensorinfo_6189',['TensorInfo',['../classarmnn_1_1_tensor_info.xhtml',1,'armnn']]],
  ['tensormemory_6190',['TensorMemory',['../structarmnn_1_1_tensor_memory.xhtml',1,'armnn']]],
  ['tensornumdimensionsarecorrect_6191',['TensorNumDimensionsAreCorrect',['../structarmnn_1_1_tensor_num_dimensions_are_correct.xhtml',1,'armnn']]],
  ['tensornumdimensionsaregreaterorequalto_6192',['TensorNumDimensionsAreGreaterOrEqualTo',['../structarmnn_1_1_tensor_num_dimensions_are_greater_or_equal_to.xhtml',1,'armnn']]],
  ['tensorshape_6193',['TensorShape',['../classarmnn_1_1_tensor_shape.xhtml',1,'armnn']]],
  ['tfliteparserimpl_6194',['TfLiteParserImpl',['../classarmnn_tf_lite_parser_1_1_tf_lite_parser_impl.xhtml',1,'armnnTfLiteParser']]],
  ['tfliteparseroptions_6195',['TfLiteParserOptions',['../structarmnn_tf_lite_parser_1_1_i_tf_lite_parser_1_1_tf_lite_parser_options.xhtml',1,'armnnTfLiteParser::ITfLiteParser']]],
  ['threadpool_6196',['Threadpool',['../classarmnn_1_1experimental_1_1_threadpool.xhtml',1,'armnn::experimental']]],
  ['throwingstrategy_6197',['ThrowingStrategy',['../structarmnn_1_1_throwing_strategy.xhtml',1,'armnn']]],
  ['timeoutexception_6198',['TimeoutException',['../classarmnn_1_1_timeout_exception.xhtml',1,'armnn']]],
  ['tosaassertsize_6199',['TosaAssertSize',['../struct_tosa_assert_size.xhtml',1,'']]],
  ['tosacontainercontainsthreetypes_6200',['TosaContainerContainsThreeTypes',['../struct_tosa_container_contains_three_types.xhtml',1,'']]],
  ['tosacontainercontainstwotypes_6201',['TosaContainerContainsTwoTypes',['../struct_tosa_container_contains_two_types.xhtml',1,'']]],
  ['tosaoperatorattributeofany_6202',['TosaOperatorAttributeOfAny',['../struct_tosa_operator_attribute_of_any.xhtml',1,'']]],
  ['tosarefbackend_6203',['TosaRefBackend',['../classarmnn_1_1_tosa_ref_backend.xhtml',1,'armnn']]],
  ['tosarefbaseworkload_6204',['TosaRefBaseWorkload',['../classarmnn_1_1_tosa_ref_base_workload.xhtml',1,'armnn']]],
  ['tosareflayersupport_6205',['TosaRefLayerSupport',['../classarmnn_1_1_tosa_ref_layer_support.xhtml',1,'armnn']]],
  ['tosarefmemorymanager_6206',['TosaRefMemoryManager',['../classarmnn_1_1_tosa_ref_memory_manager.xhtml',1,'armnn']]],
  ['tosarefprecompiledworkload_6207',['TosaRefPreCompiledWorkload',['../classarmnn_1_1_tosa_ref_pre_compiled_workload.xhtml',1,'armnn']]],
  ['tosareftensorhandle_6208',['TosaRefTensorHandle',['../classarmnn_1_1_tosa_ref_tensor_handle.xhtml',1,'armnn']]],
  ['tosareftensorhandlefactory_6209',['TosaRefTensorHandleFactory',['../classarmnn_1_1_tosa_ref_tensor_handle_factory.xhtml',1,'armnn']]],
  ['tosarefworkloadfactory_6210',['TosaRefWorkloadFactory',['../classarmnn_1_1_tosa_ref_workload_factory.xhtml',1,'armnn']]],
  ['tosatensornumdimensionswithinbounds_6211',['TosaTensorNumDimensionsWithinBounds',['../struct_tosa_tensor_num_dimensions_within_bounds.xhtml',1,'']]],
  ['tosatypeanyof_6212',['TosaTypeAnyOf',['../struct_tosa_type_any_of.xhtml',1,'']]],
  ['transformiterator_6213',['TransformIterator',['../classarmnn_1_1_transform_iterator.xhtml',1,'armnn']]],
  ['transposeasreshapeimpl_6214',['TransposeAsReshapeImpl',['../classarmnn_1_1optimizations_1_1_transpose_as_reshape_impl.xhtml',1,'armnn::optimizations']]],
  ['transposeconvolution2ddescriptor_6215',['TransposeConvolution2dDescriptor',['../structarmnn_1_1_transpose_convolution2d_descriptor.xhtml',1,'armnn']]],
  ['transposeconvolution2dlayer_6216',['TransposeConvolution2dLayer',['../classarmnn_1_1_transpose_convolution2d_layer.xhtml',1,'armnn']]],
  ['transposeconvolution2dqueuedescriptor_6217',['TransposeConvolution2dQueueDescriptor',['../structarmnn_1_1_transpose_convolution2d_queue_descriptor.xhtml',1,'armnn']]],
  ['transposedescriptor_6218',['TransposeDescriptor',['../structarmnn_1_1_transpose_descriptor.xhtml',1,'armnn']]],
  ['transposelayer_6219',['TransposeLayer',['../classarmnn_1_1_transpose_layer.xhtml',1,'armnn']]],
  ['transposequeuedescriptor_6220',['TransposeQueueDescriptor',['../structarmnn_1_1_transpose_queue_descriptor.xhtml',1,'armnn']]],
  ['typeanyof_6221',['TypeAnyOf',['../structarmnn_1_1_type_any_of.xhtml',1,'armnn']]],
  ['typediterator_6222',['TypedIterator',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20float_2c_20decoder_3c_20float_20_3e_20_3e_6223',['TypedIterator&lt; const float, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20half_2c_20decoder_3c_20float_20_3e_20_3e_6224',['TypedIterator&lt; const Half, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int16_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6225',['TypedIterator&lt; const int16_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6226',['TypedIterator&lt; const int32_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int32_5ft_2c_20decoder_3c_20int32_5ft_20_3e_20_3e_6227',['TypedIterator&lt; const int32_t, Decoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20int8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6228',['TypedIterator&lt; const int8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20bool_20_3e_20_3e_6229',['TypedIterator&lt; const uint8_t, Decoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20const_20uint8_5ft_2c_20decoder_3c_20float_20_3e_20_3e_6230',['TypedIterator&lt; const uint8_t, Decoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20float_2c_20encoder_3c_20float_20_3e_20_3e_6231',['TypedIterator&lt; float, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20half_2c_20encoder_3c_20float_20_3e_20_3e_6232',['TypedIterator&lt; Half, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int16_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6233',['TypedIterator&lt; int16_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6234',['TypedIterator&lt; int32_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int32_5ft_2c_20encoder_3c_20int32_5ft_20_3e_20_3e_6235',['TypedIterator&lt; int32_t, Encoder&lt; int32_t &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20int8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6236',['TypedIterator&lt; int8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20bool_20_3e_20_3e_6237',['TypedIterator&lt; uint8_t, Encoder&lt; bool &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typediterator_3c_20uint8_5ft_2c_20encoder_3c_20float_20_3e_20_3e_6238',['TypedIterator&lt; uint8_t, Encoder&lt; float &gt; &gt;',['../classarmnn_1_1_typed_iterator.xhtml',1,'armnn']]],
  ['typedworkload_6239',['TypedWorkload',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typedworkload_3c_20debugqueuedescriptor_2c_20datatype_20_3e_6240',['TypedWorkload&lt; DebugQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typedworkload_3c_20permutequeuedescriptor_2c_20datatype_20_3e_6241',['TypedWorkload&lt; PermuteQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typedworkload_3c_20transposequeuedescriptor_2c_20datatype_20_3e_6242',['TypedWorkload&lt; TransposeQueueDescriptor, DataType &gt;',['../classarmnn_1_1_typed_workload.xhtml',1,'armnn']]],
  ['typeis_6243',['TypeIs',['../structarmnn_1_1_type_is.xhtml',1,'armnn']]],
  ['typenotperaxisquantized_6244',['TypeNotPerAxisQuantized',['../structarmnn_1_1_type_not_per_axis_quantized.xhtml',1,'armnn']]],
  ['typesareequal_6245',['TypesAreEqual',['../structarmnn_1_1_types_are_equal.xhtml',1,'armnn']]]
];
