var searchData=
[
  ['neonabsworkload_5638',['NeonAbsWorkload',['../classarmnn_1_1_neon_abs_workload.xhtml',1,'armnn']]],
  ['neonactivationworkload_5639',['NeonActivationWorkload',['../classarmnn_1_1_neon_activation_workload.xhtml',1,'armnn']]],
  ['neonadditionworkload_5640',['NeonAdditionWorkload',['../classarmnn_1_1_neon_addition_workload.xhtml',1,'armnn']]],
  ['neonargminmaxworkload_5641',['NeonArgMinMaxWorkload',['../classarmnn_1_1_neon_arg_min_max_workload.xhtml',1,'armnn']]],
  ['neonbackend_5642',['NeonBackend',['../classarmnn_1_1_neon_backend.xhtml',1,'armnn']]],
  ['neonbackendmodelcontext_5643',['NeonBackendModelContext',['../classarmnn_1_1_neon_backend_model_context.xhtml',1,'armnn']]],
  ['neonbaseworkload_5644',['NeonBaseWorkload',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20absqueuedescriptor_20_3e_5645',['NeonBaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20activationqueuedescriptor_20_3e_5646',['NeonBaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20additionqueuedescriptor_20_3e_5647',['NeonBaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20argminmaxqueuedescriptor_20_3e_5648',['NeonBaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5649',['NeonBaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5650',['NeonBaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5651',['NeonBaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20castqueuedescriptor_20_3e_5652',['NeonBaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20channelshufflequeuedescriptor_20_3e_5653',['NeonBaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20comparisonqueuedescriptor_20_3e_5654',['NeonBaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20concatqueuedescriptor_20_3e_5655',['NeonBaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20constantqueuedescriptor_20_3e_5656',['NeonBaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution2dqueuedescriptor_20_3e_5657',['NeonBaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20convolution3dqueuedescriptor_20_3e_5658',['NeonBaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20depthtospacequeuedescriptor_20_3e_5659',['NeonBaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5660',['NeonBaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20dequantizequeuedescriptor_20_3e_5661',['NeonBaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5662',['NeonBaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20divisionqueuedescriptor_20_3e_5663',['NeonBaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5664',['NeonBaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20fillqueuedescriptor_20_3e_5665',['NeonBaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5666',['NeonBaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherndqueuedescriptor_20_3e_5667',['NeonBaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20gatherqueuedescriptor_20_3e_5668',['NeonBaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5669',['NeonBaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5670',['NeonBaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5671',['NeonBaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20maximumqueuedescriptor_20_3e_5672',['NeonBaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20meanqueuedescriptor_20_3e_5673',['NeonBaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20minimumqueuedescriptor_20_3e_5674',['NeonBaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20multiplicationqueuedescriptor_20_3e_5675',['NeonBaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20padqueuedescriptor_20_3e_5676',['NeonBaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20permutequeuedescriptor_20_3e_5677',['NeonBaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling2dqueuedescriptor_20_3e_5678',['NeonBaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20pooling3dqueuedescriptor_20_3e_5679',['NeonBaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20preluqueuedescriptor_20_3e_5680',['NeonBaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20qlstmqueuedescriptor_20_3e_5681',['NeonBaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5682',['NeonBaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20quantizequeuedescriptor_20_3e_5683',['NeonBaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20rankqueuedescriptor_20_3e_5684',['NeonBaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20reducequeuedescriptor_20_3e_5685',['NeonBaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20reshapequeuedescriptor_20_3e_5686',['NeonBaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20resizequeuedescriptor_20_3e_5687',['NeonBaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20rsqrtqueuedescriptor_20_3e_5688',['NeonBaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20slicequeuedescriptor_20_3e_5689',['NeonBaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20softmaxqueuedescriptor_20_3e_5690',['NeonBaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5691',['NeonBaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5692',['NeonBaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20splitterqueuedescriptor_20_3e_5693',['NeonBaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20stackqueuedescriptor_20_3e_5694',['NeonBaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20stridedslicequeuedescriptor_20_3e_5695',['NeonBaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20subtractionqueuedescriptor_20_3e_5696',['NeonBaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5697',['NeonBaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20transposequeuedescriptor_20_3e_5698',['NeonBaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbaseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5699',['NeonBaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_neon_base_workload.xhtml',1,'armnn']]],
  ['neonbatchmatmulworkload_5700',['NeonBatchMatMulWorkload',['../classarmnn_1_1_neon_batch_mat_mul_workload.xhtml',1,'armnn']]],
  ['neonbatchnormalizationworkload_5701',['NeonBatchNormalizationWorkload',['../classarmnn_1_1_neon_batch_normalization_workload.xhtml',1,'armnn']]],
  ['neonbatchtospacendworkload_5702',['NeonBatchToSpaceNdWorkload',['../classarmnn_1_1_neon_batch_to_space_nd_workload.xhtml',1,'armnn']]],
  ['neoncastworkload_5703',['NeonCastWorkload',['../classarmnn_1_1_neon_cast_workload.xhtml',1,'armnn']]],
  ['neonchannelshuffleworkload_5704',['NeonChannelShuffleWorkload',['../classarmnn_1_1_neon_channel_shuffle_workload.xhtml',1,'armnn']]],
  ['neoncomparisonworkload_5705',['NeonComparisonWorkload',['../classarmnn_1_1_neon_comparison_workload.xhtml',1,'armnn']]],
  ['neonconcatworkload_5706',['NeonConcatWorkload',['../classarmnn_1_1_neon_concat_workload.xhtml',1,'armnn']]],
  ['neonconstantworkload_5707',['NeonConstantWorkload',['../classarmnn_1_1_neon_constant_workload.xhtml',1,'armnn']]],
  ['neonconvertfp16tofp32workload_5708',['NeonConvertFp16ToFp32Workload',['../classarmnn_1_1_neon_convert_fp16_to_fp32_workload.xhtml',1,'armnn']]],
  ['neonconvertfp32tofp16workload_5709',['NeonConvertFp32ToFp16Workload',['../classarmnn_1_1_neon_convert_fp32_to_fp16_workload.xhtml',1,'armnn']]],
  ['neonconvolution2dworkload_5710',['NeonConvolution2dWorkload',['../classarmnn_1_1_neon_convolution2d_workload.xhtml',1,'armnn']]],
  ['neonconvolution3dworkload_5711',['NeonConvolution3dWorkload',['../classarmnn_1_1_neon_convolution3d_workload.xhtml',1,'armnn']]],
  ['neondepthtospaceworkload_5712',['NeonDepthToSpaceWorkload',['../classarmnn_1_1_neon_depth_to_space_workload.xhtml',1,'armnn']]],
  ['neondepthwiseconvolutionworkload_5713',['NeonDepthwiseConvolutionWorkload',['../classarmnn_1_1_neon_depthwise_convolution_workload.xhtml',1,'armnn']]],
  ['neondequantizeworkload_5714',['NeonDequantizeWorkload',['../classarmnn_1_1_neon_dequantize_workload.xhtml',1,'armnn']]],
  ['neondetectionpostprocessworkload_5715',['NeonDetectionPostProcessWorkload',['../classarmnn_1_1_neon_detection_post_process_workload.xhtml',1,'armnn']]],
  ['neondivisionworkload_5716',['NeonDivisionWorkload',['../classarmnn_1_1_neon_division_workload.xhtml',1,'armnn']]],
  ['neonexpworkload_5717',['NeonExpWorkload',['../classarmnn_1_1_neon_exp_workload.xhtml',1,'armnn']]],
  ['neonfillworkload_5718',['NeonFillWorkload',['../classarmnn_1_1_neon_fill_workload.xhtml',1,'armnn']]],
  ['neonfloorfloatworkload_5719',['NeonFloorFloatWorkload',['../classarmnn_1_1_neon_floor_float_workload.xhtml',1,'armnn']]],
  ['neonfullyconnectedworkload_5720',['NeonFullyConnectedWorkload',['../classarmnn_1_1_neon_fully_connected_workload.xhtml',1,'armnn']]],
  ['neongatherndworkload_5721',['NeonGatherNdWorkload',['../classarmnn_1_1_neon_gather_nd_workload.xhtml',1,'armnn']]],
  ['neongatherworkload_5722',['NeonGatherWorkload',['../classarmnn_1_1_neon_gather_workload.xhtml',1,'armnn']]],
  ['neoninstancenormalizationworkload_5723',['NeonInstanceNormalizationWorkload',['../classarmnn_1_1_neon_instance_normalization_workload.xhtml',1,'armnn']]],
  ['neoninterceptorscheduler_5724',['NeonInterceptorScheduler',['../classarmnn_1_1_neon_interceptor_scheduler.xhtml',1,'armnn']]],
  ['neonl2normalizationfloatworkload_5725',['NeonL2NormalizationFloatWorkload',['../classarmnn_1_1_neon_l2_normalization_float_workload.xhtml',1,'armnn']]],
  ['neonlayersupport_5726',['NeonLayerSupport',['../classarmnn_1_1_neon_layer_support.xhtml',1,'armnn']]],
  ['neonlogicalandworkload_5727',['NeonLogicalAndWorkload',['../classarmnn_1_1_neon_logical_and_workload.xhtml',1,'armnn']]],
  ['neonlogicalnotworkload_5728',['NeonLogicalNotWorkload',['../classarmnn_1_1_neon_logical_not_workload.xhtml',1,'armnn']]],
  ['neonlogicalorworkload_5729',['NeonLogicalOrWorkload',['../classarmnn_1_1_neon_logical_or_workload.xhtml',1,'armnn']]],
  ['neonlogsoftmaxworkload_5730',['NeonLogSoftmaxWorkload',['../classarmnn_1_1_neon_log_softmax_workload.xhtml',1,'armnn']]],
  ['neonlogworkload_5731',['NeonLogWorkload',['../classarmnn_1_1_neon_log_workload.xhtml',1,'armnn']]],
  ['neonlstmfloatworkload_5732',['NeonLstmFloatWorkload',['../classarmnn_1_1_neon_lstm_float_workload.xhtml',1,'armnn']]],
  ['neonmaximumworkload_5733',['NeonMaximumWorkload',['../classarmnn_1_1_neon_maximum_workload.xhtml',1,'armnn']]],
  ['neonmeanworkload_5734',['NeonMeanWorkload',['../classarmnn_1_1_neon_mean_workload.xhtml',1,'armnn']]],
  ['neonmemorymanager_5735',['NeonMemoryManager',['../classarmnn_1_1_neon_memory_manager.xhtml',1,'armnn']]],
  ['neonminimumworkload_5736',['NeonMinimumWorkload',['../classarmnn_1_1_neon_minimum_workload.xhtml',1,'armnn']]],
  ['neonmultiplicationworkload_5737',['NeonMultiplicationWorkload',['../classarmnn_1_1_neon_multiplication_workload.xhtml',1,'armnn']]],
  ['neonnegworkload_5738',['NeonNegWorkload',['../classarmnn_1_1_neon_neg_workload.xhtml',1,'armnn']]],
  ['neonnormalizationfloatworkload_5739',['NeonNormalizationFloatWorkload',['../classarmnn_1_1_neon_normalization_float_workload.xhtml',1,'armnn']]],
  ['neonpadworkload_5740',['NeonPadWorkload',['../classarmnn_1_1_neon_pad_workload.xhtml',1,'armnn']]],
  ['neonpermuteworkload_5741',['NeonPermuteWorkload',['../classarmnn_1_1_neon_permute_workload.xhtml',1,'armnn']]],
  ['neonpooling2dworkload_5742',['NeonPooling2dWorkload',['../classarmnn_1_1_neon_pooling2d_workload.xhtml',1,'armnn']]],
  ['neonpooling3dworkload_5743',['NeonPooling3dWorkload',['../classarmnn_1_1_neon_pooling3d_workload.xhtml',1,'armnn']]],
  ['neonpreluworkload_5744',['NeonPreluWorkload',['../classarmnn_1_1_neon_prelu_workload.xhtml',1,'armnn']]],
  ['neonqlstmworkload_5745',['NeonQLstmWorkload',['../classarmnn_1_1_neon_q_lstm_workload.xhtml',1,'armnn']]],
  ['neonquantizedlstmworkload_5746',['NeonQuantizedLstmWorkload',['../classarmnn_1_1_neon_quantized_lstm_workload.xhtml',1,'armnn']]],
  ['neonquantizeworkload_5747',['NeonQuantizeWorkload',['../classarmnn_1_1_neon_quantize_workload.xhtml',1,'armnn']]],
  ['neonrankworkload_5748',['NeonRankWorkload',['../structarmnn_1_1_neon_rank_workload.xhtml',1,'armnn']]],
  ['neonreduceworkload_5749',['NeonReduceWorkload',['../classarmnn_1_1_neon_reduce_workload.xhtml',1,'armnn']]],
  ['neonreshapeworkload_5750',['NeonReshapeWorkload',['../classarmnn_1_1_neon_reshape_workload.xhtml',1,'armnn']]],
  ['neonresizeworkload_5751',['NeonResizeWorkload',['../classarmnn_1_1_neon_resize_workload.xhtml',1,'armnn']]],
  ['neonrsqrtworkload_5752',['NeonRsqrtWorkload',['../classarmnn_1_1_neon_rsqrt_workload.xhtml',1,'armnn']]],
  ['neonsinworkload_5753',['NeonSinWorkload',['../classarmnn_1_1_neon_sin_workload.xhtml',1,'armnn']]],
  ['neonsliceworkload_5754',['NeonSliceWorkload',['../classarmnn_1_1_neon_slice_workload.xhtml',1,'armnn']]],
  ['neonsoftmaxworkload_5755',['NeonSoftmaxWorkload',['../classarmnn_1_1_neon_softmax_workload.xhtml',1,'armnn']]],
  ['neonspacetobatchndworkload_5756',['NeonSpaceToBatchNdWorkload',['../classarmnn_1_1_neon_space_to_batch_nd_workload.xhtml',1,'armnn']]],
  ['neonspacetodepthworkload_5757',['NeonSpaceToDepthWorkload',['../classarmnn_1_1_neon_space_to_depth_workload.xhtml',1,'armnn']]],
  ['neonsplitterworkload_5758',['NeonSplitterWorkload',['../classarmnn_1_1_neon_splitter_workload.xhtml',1,'armnn']]],
  ['neonsqrtworkload_5759',['NeonSqrtWorkload',['../classarmnn_1_1_neon_sqrt_workload.xhtml',1,'armnn']]],
  ['neonstackworkload_5760',['NeonStackWorkload',['../classarmnn_1_1_neon_stack_workload.xhtml',1,'armnn']]],
  ['neonstridedsliceworkload_5761',['NeonStridedSliceWorkload',['../classarmnn_1_1_neon_strided_slice_workload.xhtml',1,'armnn']]],
  ['neonsubtensorhandle_5762',['NeonSubTensorHandle',['../classarmnn_1_1_neon_sub_tensor_handle.xhtml',1,'armnn']]],
  ['neonsubtractionworkload_5763',['NeonSubtractionWorkload',['../classarmnn_1_1_neon_subtraction_workload.xhtml',1,'armnn']]],
  ['neontensorhandle_5764',['NeonTensorHandle',['../classarmnn_1_1_neon_tensor_handle.xhtml',1,'armnn']]],
  ['neontensorhandlefactory_5765',['NeonTensorHandleFactory',['../classarmnn_1_1_neon_tensor_handle_factory.xhtml',1,'armnn']]],
  ['neontimer_5766',['NeonTimer',['../classarmnn_1_1_neon_timer.xhtml',1,'armnn']]],
  ['neontransposeconvolution2dworkload_5767',['NeonTransposeConvolution2dWorkload',['../classarmnn_1_1_neon_transpose_convolution2d_workload.xhtml',1,'armnn']]],
  ['neontransposeworkload_5768',['NeonTransposeWorkload',['../classarmnn_1_1_neon_transpose_workload.xhtml',1,'armnn']]],
  ['neonunidirectionalsequencelstmfloatworkload_5769',['NeonUnidirectionalSequenceLstmFloatWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_float_workload.xhtml',1,'armnn']]],
  ['neonunidirectionalsequencelstmworkload_5770',['NeonUnidirectionalSequenceLstmWorkload',['../classarmnn_1_1_neon_unidirectional_sequence_lstm_workload.xhtml',1,'armnn']]],
  ['neonworkloadfactory_5771',['NeonWorkloadFactory',['../classarmnn_1_1_neon_workload_factory.xhtml',1,'armnn']]],
  ['networkimpl_5772',['NetworkImpl',['../classarmnn_1_1_network_impl.xhtml',1,'armnn']]],
  ['nodecontent_5773',['NodeContent',['../classarmnn_1_1_node_content.xhtml',1,'armnn']]],
  ['normalizationdescriptor_5774',['NormalizationDescriptor',['../structarmnn_1_1_normalization_descriptor.xhtml',1,'armnn']]],
  ['normalizationlayer_5775',['NormalizationLayer',['../classarmnn_1_1_normalization_layer.xhtml',1,'armnn']]],
  ['normalizationqueuedescriptor_5776',['NormalizationQueueDescriptor',['../structarmnn_1_1_normalization_queue_descriptor.xhtml',1,'armnn']]],
  ['nothrowstrategy_5777',['NoThrowStrategy',['../structarmnn_1_1_no_throw_strategy.xhtml',1,'armnn']]],
  ['nulldescriptor_5778',['NullDescriptor',['../structarmnn_1_1_null_descriptor.xhtml',1,'armnn']]],
  ['nullpointerexception_5779',['NullPointerException',['../classarmnn_1_1_null_pointer_exception.xhtml',1,'armnn']]],
  ['nullworkload_5780',['NullWorkload',['../classarmnn_1_1_null_workload.xhtml',1,'armnn']]]
];
