var searchData=
[
  ['backendcapabilityexception_5008',['BackendCapabilityException',['../classarmnn_1_1_backend_capability_exception.xhtml',1,'armnn']]],
  ['backendid_5009',['BackendId',['../classarmnn_1_1_backend_id.xhtml',1,'armnn']]],
  ['backendoption_5010',['BackendOption',['../structarmnn_1_1_backend_options_1_1_backend_option.xhtml',1,'armnn::BackendOptions']]],
  ['backendoptions_5011',['BackendOptions',['../structarmnn_1_1_backend_options.xhtml',1,'armnn']]],
  ['backendregistry_5012',['BackendRegistry',['../classarmnn_1_1_backend_registry.xhtml',1,'armnn']]],
  ['backendsettings_5013',['BackendSettings',['../structarmnn_1_1_backend_settings.xhtml',1,'armnn']]],
  ['backendunavailableexception_5014',['BackendUnavailableException',['../classarmnn_1_1_backend_unavailable_exception.xhtml',1,'armnn']]],
  ['backendversion_5015',['BackendVersion',['../structarmnn_1_1_backend_version.xhtml',1,'armnn']]],
  ['badoptionalaccessexception_5016',['BadOptionalAccessException',['../classarmnn_1_1_bad_optional_access_exception.xhtml',1,'armnn']]],
  ['basedescriptor_5017',['BaseDescriptor',['../structarmnn_1_1_base_descriptor.xhtml',1,'armnn']]],
  ['baseiterator_5018',['BaseIterator',['../classarmnn_1_1_base_iterator.xhtml',1,'armnn']]],
  ['basememorymanager_5019',['BaseMemoryManager',['../classarmnn_1_1_base_memory_manager.xhtml',1,'armnn']]],
  ['basetensor_5020',['BaseTensor',['../classarmnn_1_1_base_tensor.xhtml',1,'armnn']]],
  ['basetensor_3c_20const_20void_20_2a_20_3e_5021',['BaseTensor&lt; const void * &gt;',['../classarmnn_1_1_base_tensor.xhtml',1,'armnn']]],
  ['basetensor_3c_20void_20_2a_20_3e_5022',['BaseTensor&lt; void * &gt;',['../classarmnn_1_1_base_tensor.xhtml',1,'armnn']]],
  ['baseworkload_5023',['BaseWorkload',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20absqueuedescriptor_20_3e_5024',['BaseWorkload&lt; AbsQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20activationqueuedescriptor_20_3e_5025',['BaseWorkload&lt; ActivationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20additionqueuedescriptor_20_3e_5026',['BaseWorkload&lt; AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20argminmaxqueuedescriptor_20_3e_5027',['BaseWorkload&lt; ArgMinMaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20armnn_3a_3aadditionqueuedescriptor_20_3e_5028',['BaseWorkload&lt; armnn::AdditionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20batchmatmulqueuedescriptor_20_3e_5029',['BaseWorkload&lt; BatchMatMulQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20batchnormalizationqueuedescriptor_20_3e_5030',['BaseWorkload&lt; BatchNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20batchtospacendqueuedescriptor_20_3e_5031',['BaseWorkload&lt; BatchToSpaceNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20castqueuedescriptor_20_3e_5032',['BaseWorkload&lt; CastQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20channelshufflequeuedescriptor_20_3e_5033',['BaseWorkload&lt; ChannelShuffleQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20comparisonqueuedescriptor_20_3e_5034',['BaseWorkload&lt; ComparisonQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20concatqueuedescriptor_20_3e_5035',['BaseWorkload&lt; ConcatQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20constantqueuedescriptor_20_3e_5036',['BaseWorkload&lt; ConstantQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20convolution2dqueuedescriptor_20_3e_5037',['BaseWorkload&lt; Convolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20convolution3dqueuedescriptor_20_3e_5038',['BaseWorkload&lt; Convolution3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20debugqueuedescriptor_20_3e_5039',['BaseWorkload&lt; DebugQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20depthtospacequeuedescriptor_20_3e_5040',['BaseWorkload&lt; DepthToSpaceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20depthwiseconvolution2dqueuedescriptor_20_3e_5041',['BaseWorkload&lt; DepthwiseConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20dequantizequeuedescriptor_20_3e_5042',['BaseWorkload&lt; DequantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20detectionpostprocessqueuedescriptor_20_3e_5043',['BaseWorkload&lt; DetectionPostProcessQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20divisionqueuedescriptor_20_3e_5044',['BaseWorkload&lt; DivisionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20elementwiseunaryqueuedescriptor_20_3e_5045',['BaseWorkload&lt; ElementwiseUnaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20fillqueuedescriptor_20_3e_5046',['BaseWorkload&lt; FillQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20floorqueuedescriptor_20_3e_5047',['BaseWorkload&lt; FloorQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20fullyconnectedqueuedescriptor_20_3e_5048',['BaseWorkload&lt; FullyConnectedQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20gatherndqueuedescriptor_20_3e_5049',['BaseWorkload&lt; GatherNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20gatherqueuedescriptor_20_3e_5050',['BaseWorkload&lt; GatherQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20instancenormalizationqueuedescriptor_20_3e_5051',['BaseWorkload&lt; InstanceNormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20l2normalizationqueuedescriptor_20_3e_5052',['BaseWorkload&lt; L2NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20logicalbinaryqueuedescriptor_20_3e_5053',['BaseWorkload&lt; LogicalBinaryQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20logsoftmaxqueuedescriptor_20_3e_5054',['BaseWorkload&lt; LogSoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20lstmqueuedescriptor_20_3e_5055',['BaseWorkload&lt; LstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20mapqueuedescriptor_20_3e_5056',['BaseWorkload&lt; MapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20maximumqueuedescriptor_20_3e_5057',['BaseWorkload&lt; MaximumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20meanqueuedescriptor_20_3e_5058',['BaseWorkload&lt; MeanQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20memcopyqueuedescriptor_20_3e_5059',['BaseWorkload&lt; MemCopyQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20memimportqueuedescriptor_20_3e_5060',['BaseWorkload&lt; MemImportQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20memsyncqueuedescriptor_20_3e_5061',['BaseWorkload&lt; MemSyncQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20minimumqueuedescriptor_20_3e_5062',['BaseWorkload&lt; MinimumQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20multiplicationqueuedescriptor_20_3e_5063',['BaseWorkload&lt; MultiplicationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20normalizationqueuedescriptor_20_3e_5064',['BaseWorkload&lt; NormalizationQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20padqueuedescriptor_20_3e_5065',['BaseWorkload&lt; PadQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20parentdescriptor_20_3e_5066',['BaseWorkload&lt; ParentDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20permutequeuedescriptor_20_3e_5067',['BaseWorkload&lt; PermuteQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20pooling2dqueuedescriptor_20_3e_5068',['BaseWorkload&lt; Pooling2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20pooling3dqueuedescriptor_20_3e_5069',['BaseWorkload&lt; Pooling3dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20precompiledqueuedescriptor_20_3e_5070',['BaseWorkload&lt; PreCompiledQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20preluqueuedescriptor_20_3e_5071',['BaseWorkload&lt; PreluQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20qlstmqueuedescriptor_20_3e_5072',['BaseWorkload&lt; QLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20quantizedlstmqueuedescriptor_20_3e_5073',['BaseWorkload&lt; QuantizedLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20quantizequeuedescriptor_20_3e_5074',['BaseWorkload&lt; QuantizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20rankqueuedescriptor_20_3e_5075',['BaseWorkload&lt; RankQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20reducequeuedescriptor_20_3e_5076',['BaseWorkload&lt; ReduceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20reshapequeuedescriptor_20_3e_5077',['BaseWorkload&lt; ReshapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20resizequeuedescriptor_20_3e_5078',['BaseWorkload&lt; ResizeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20rsqrtqueuedescriptor_20_3e_5079',['BaseWorkload&lt; RsqrtQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20shapequeuedescriptor_20_3e_5080',['BaseWorkload&lt; ShapeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20slicequeuedescriptor_20_3e_5081',['BaseWorkload&lt; SliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20softmaxqueuedescriptor_20_3e_5082',['BaseWorkload&lt; SoftmaxQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20spacetobatchndqueuedescriptor_20_3e_5083',['BaseWorkload&lt; SpaceToBatchNdQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20spacetodepthqueuedescriptor_20_3e_5084',['BaseWorkload&lt; SpaceToDepthQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20splitterqueuedescriptor_20_3e_5085',['BaseWorkload&lt; SplitterQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20stackqueuedescriptor_20_3e_5086',['BaseWorkload&lt; StackQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20stridedslicequeuedescriptor_20_3e_5087',['BaseWorkload&lt; StridedSliceQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20subtractionqueuedescriptor_20_3e_5088',['BaseWorkload&lt; SubtractionQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20transposeconvolution2dqueuedescriptor_20_3e_5089',['BaseWorkload&lt; TransposeConvolution2dQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20transposequeuedescriptor_20_3e_5090',['BaseWorkload&lt; TransposeQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20unidirectionalsequencelstmqueuedescriptor_20_3e_5091',['BaseWorkload&lt; UnidirectionalSequenceLstmQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['baseworkload_3c_20unmapqueuedescriptor_20_3e_5092',['BaseWorkload&lt; UnmapQueueDescriptor &gt;',['../classarmnn_1_1_base_workload.xhtml',1,'armnn']]],
  ['batchmatmul_5093',['BatchMatMul',['../classarmnn_1_1_batch_mat_mul.xhtml',1,'armnn']]],
  ['batchmatmuldescriptor_5094',['BatchMatMulDescriptor',['../structarmnn_1_1_batch_mat_mul_descriptor.xhtml',1,'armnn']]],
  ['batchmatmullayer_5095',['BatchMatMulLayer',['../classarmnn_1_1_batch_mat_mul_layer.xhtml',1,'armnn']]],
  ['batchmatmulqueuedescriptor_5096',['BatchMatMulQueueDescriptor',['../structarmnn_1_1_batch_mat_mul_queue_descriptor.xhtml',1,'armnn']]],
  ['batchnormalizationdescriptor_5097',['BatchNormalizationDescriptor',['../structarmnn_1_1_batch_normalization_descriptor.xhtml',1,'armnn']]],
  ['batchnormalizationlayer_5098',['BatchNormalizationLayer',['../classarmnn_1_1_batch_normalization_layer.xhtml',1,'armnn']]],
  ['batchnormalizationqueuedescriptor_5099',['BatchNormalizationQueueDescriptor',['../structarmnn_1_1_batch_normalization_queue_descriptor.xhtml',1,'armnn']]],
  ['batchtospacenddescriptor_5100',['BatchToSpaceNdDescriptor',['../structarmnn_1_1_batch_to_space_nd_descriptor.xhtml',1,'armnn']]],
  ['batchtospacendlayer_5101',['BatchToSpaceNdLayer',['../classarmnn_1_1_batch_to_space_nd_layer.xhtml',1,'armnn']]],
  ['batchtospacendqueuedescriptor_5102',['BatchToSpaceNdQueueDescriptor',['../structarmnn_1_1_batch_to_space_nd_queue_descriptor.xhtml',1,'armnn']]],
  ['bfloat16_5103',['BFloat16',['../classarmnn_1_1_b_float16.xhtml',1,'armnn']]],
  ['biasandweightstypescompatible_5104',['BiasAndWeightsTypesCompatible',['../structarmnn_1_1_bias_and_weights_types_compatible.xhtml',1,'armnn']]],
  ['biasandweightstypesmatch_5105',['BiasAndWeightsTypesMatch',['../structarmnn_1_1_bias_and_weights_types_match.xhtml',1,'armnn']]],
  ['bindablelayer_5106',['BindableLayer',['../classarmnn_1_1_bindable_layer.xhtml',1,'armnn']]],
  ['bindingpointinfo_5107',['BindingPointInfo',['../structarmnn_deserializer_1_1_binding_point_info.xhtml',1,'armnnDeserializer']]],
  ['booleandecoder_5108',['BooleanDecoder',['../classarmnn_1_1_boolean_decoder.xhtml',1,'armnn']]],
  ['booleandecoderbool_5109',['BooleanDecoderBool',['../classarmnn_1_1_boolean_decoder_bool.xhtml',1,'armnn']]],
  ['booleanencoder_5110',['BooleanEncoder',['../classarmnn_1_1_boolean_encoder.xhtml',1,'armnn']]],
  ['broadcastloop_5111',['BroadcastLoop',['../structarmnn_1_1_broadcast_loop.xhtml',1,'armnn']]],
  ['bufferstorage_5112',['BufferStorage',['../structarmnn_1_1_buffer_storage.xhtml',1,'armnn']]]
];
