var searchData=
[
  ['datalayoutindexed_5292',['DataLayoutIndexed',['../classarmnn_utils_1_1_data_layout_indexed.xhtml',1,'armnnUtils']]],
  ['debuglayer_5293',['DebugLayer',['../classarmnn_1_1_debug_layer.xhtml',1,'armnn']]],
  ['debugqueuedescriptor_5294',['DebugQueueDescriptor',['../structarmnn_1_1_debug_queue_descriptor.xhtml',1,'armnn']]],
  ['decoder_5295',['Decoder',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20bool_20_3e_5296',['Decoder&lt; bool &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20float_20_3e_5297',['Decoder&lt; float &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['decoder_3c_20int32_5ft_20_3e_5298',['Decoder&lt; int32_t &gt;',['../classarmnn_1_1_decoder.xhtml',1,'armnn']]],
  ['defaultallocator_5299',['DefaultAllocator',['../classarmnn_1_1_default_allocator.xhtml',1,'armnn']]],
  ['delegate_5300',['Delegate',['../classarmnn_delegate_1_1_delegate.xhtml',1,'armnnDelegate']]],
  ['delegatedata_5301',['DelegateData',['../structarmnn_delegate_1_1_delegate_data.xhtml',1,'armnnDelegate']]],
  ['delegateoptions_5302',['DelegateOptions',['../classarmnn_delegate_1_1_delegate_options.xhtml',1,'armnnDelegate']]],
  ['depthtospacelayer_5303',['DepthToSpaceLayer',['../classarmnn_1_1_depth_to_space_layer.xhtml',1,'armnn']]],
  ['depthtospacequeuedescriptor_5304',['DepthToSpaceQueueDescriptor',['../structarmnn_1_1_depth_to_space_queue_descriptor.xhtml',1,'armnn']]],
  ['depthwiseconvolution2ddescriptor_5305',['DepthwiseConvolution2dDescriptor',['../structarmnn_1_1_depthwise_convolution2d_descriptor.xhtml',1,'armnn']]],
  ['depthwiseconvolution2dlayer_5306',['DepthwiseConvolution2dLayer',['../classarmnn_1_1_depthwise_convolution2d_layer.xhtml',1,'armnn']]],
  ['depthwiseconvolution2dqueuedescriptor_5307',['DepthwiseConvolution2dQueueDescriptor',['../structarmnn_1_1_depthwise_convolution2d_queue_descriptor.xhtml',1,'armnn']]],
  ['dequantizelayer_5308',['DequantizeLayer',['../classarmnn_1_1_dequantize_layer.xhtml',1,'armnn']]],
  ['dequantizequeuedescriptor_5309',['DequantizeQueueDescriptor',['../structarmnn_1_1_dequantize_queue_descriptor.xhtml',1,'armnn']]],
  ['deserializerimpl_5310',['DeserializerImpl',['../classarmnn_deserializer_1_1_i_deserializer_1_1_deserializer_impl.xhtml',1,'armnnDeserializer::IDeserializer']]],
  ['detectionpostprocessdescriptor_5311',['DetectionPostProcessDescriptor',['../structarmnn_1_1_detection_post_process_descriptor.xhtml',1,'armnn']]],
  ['detectionpostprocesslayer_5312',['DetectionPostProcessLayer',['../classarmnn_1_1_detection_post_process_layer.xhtml',1,'armnn']]],
  ['detectionpostprocessqueuedescriptor_5313',['DetectionPostProcessQueueDescriptor',['../structarmnn_1_1_detection_post_process_queue_descriptor.xhtml',1,'armnn']]],
  ['devicespec_5314',['DeviceSpec',['../classarmnn_1_1_device_spec.xhtml',1,'armnn']]],
  ['divisionlayer_5315',['DivisionLayer',['../classarmnn_1_1_division_layer.xhtml',1,'armnn']]],
  ['divisionqueuedescriptor_5316',['DivisionQueueDescriptor',['../structarmnn_1_1_division_queue_descriptor.xhtml',1,'armnn']]],
  ['dotattributeset_5317',['DotAttributeSet',['../classarmnn_1_1_dot_attribute_set.xhtml',1,'armnn']]],
  ['dotbase_5318',['DotBase',['../classarmnn_1_1_dot_base.xhtml',1,'armnn']]],
  ['dotdefaults_5319',['DotDefaults',['../classarmnn_1_1_dot_defaults.xhtml',1,'armnn']]],
  ['dotedge_5320',['DotEdge',['../classarmnn_1_1_dot_edge.xhtml',1,'armnn']]],
  ['dotgraph_5321',['DotGraph',['../classarmnn_1_1_dot_graph.xhtml',1,'armnn']]],
  ['dotnode_5322',['DotNode',['../classarmnn_1_1_dot_node.xhtml',1,'armnn']]],
  ['driveroptions_5323',['DriverOptions',['../classarmnn__driver_1_1_driver_options.xhtml',1,'armnn_driver']]],
  ['dynamicbackend_5324',['DynamicBackend',['../classarmnn_1_1_dynamic_backend.xhtml',1,'armnn']]],
  ['dynamicbackendutils_5325',['DynamicBackendUtils',['../classarmnn_1_1_dynamic_backend_utils.xhtml',1,'armnn']]]
];
